### ISSUE TITLE
Unfair rule modification : /impression?

### ISSUE THREAD

**Issue by LaurentBarbareau** [easylist/easylist#1]
Don't you think it's a bit strong to add that kind of rule:
/impression?

https://github.com/easylist/easylist/commit/1e01de538239fb80d3734cb2c911f54267c7b1cf

Our intranet application is using that pattern for printings. I lost 2 days of development because of that modification.

Beyond this case, I think you also could add a wild card like * and then you'll never miss any ad URL... grrr

Please be very careful with those too blind patterns.

**Comment by Khrin** [comment]
"Unfair"... Well, you says so, bring an example where I can verify that this rule is too much generic and I'll be willing to find for a solution.

**Comment by LaurentBarbareau** [comment]
In fact, I don't understand why this rule is necessary.
Why "impression" and why not all the words of the dictionary? I took a rapid look at the other rules and for me it's quite scary, there's not enough discrimination between what can be considered as advertising and what is not.
Really, maybe I missed something, do you have an explanation, a link or anything else? How can a so simple rule as "/impression?" (and plenty of others) can be set? According to the problem I was confronted, for me it looks too generic.
The only thing I can understand is that it's really complex to set efficient rules.
Thx

**Comment by monzta** [comment]
Since that filter causes issues in your intranet application I have removed it: https://github.com/easylist/easylist/commit/ba3307a08262bf766c464762acc8c7709a51a0d4 

Other than that I have moved the other filter to EasyPrivacy. Blocking impression tracking should be avoided in EasyList imo.

**Comment by LaurentBarbareau** [comment]
I'm not aware of the purpose of each list... But thank you.
