### ISSUE TITLE
speedtest.net

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#10]
`http://www.speedtest.net/`
`http://beta.speedtest.net/`

Report: https://forums.lanik.us/viewtopic.php?f=62&t=30394

**Comment by AlphaT3ch** [comment]
Same results here. I've tried finding the code to block it. Nothing is seeming to work. I'll post the code here if I can get it working...

**Comment by monzta** [comment]
I'm not seeing any ads. Tested with FF and Chrome.

**Comment by AlphaT3ch** [comment]
Ads showing on [Speedtest.net](http://speedtest.net): ![Ads](http://i.imgur.com/JugDTAq.png)
Current Settings using easylist (Updated June 20, 2016 at 11:43:03 AM EST): ![Settings](http://i.imgur.com/crBGH09.png)

**Comment by terrorist96** [comment]
What he said^
beta.speedtest.net had ads being displayed due to it detecting Ghostery, so ignore that.

**Comment by terrorist96** [comment]
The ads on speedtest.net have been unblocked for 14 months now. First reported April 25
https://forums.lanik.us/viewtopic.php?f=62&t=30394

**Comment by monzta** [comment]
Please manually update EasyList and check if you are still seeing those ads.

**Comment by terrorist96** [comment]
Looks to be fixed. Thanks!
