### ISSUE TITLE
pdfhost.io

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10008]
### List the website(s) you're having issues:
`https://pdfhost.io/v/SWKmIUP0H_How_to_Setup_the_OnlyFans_Scraper`

### What happens?
Not really an ad but there's an `advert.js` script calling `addthis.com` and `googletagmanager.com`
`https://pdfhost.io/static/advert.js?id=SWKmIUP0H_How_to_Setup_the_OnlyFans_Scraper`
Looks like blocking it stops making connections to both domains and doesn't have any breakage.

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0
- Adblock Extension/version: ublock 1.39.2

### Other details:

![image](https://user-images.githubusercontent.com/66517106/145661080-13858545-04c5-433b-8d34-425081a8400f.png)

Proposed filter:

`/advert.js$script,domain=pdfhost.io`

**Comment by Khrin** [comment]
I don't think that's necessary to block this script.
