### ISSUE TITLE
[EasyPrivacy] https://raygun.com/ https://raygun.io/

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#10018]
### List the website(s) you're having issues:

```
https://g1.globo.com/sp/sao-jose-do-rio-preto-aracatuba/noticia/2021/12/11/mulher-que-ligou-a-policia-e-denunciou-companheiro-ao-pedir-para-fazer-cabelo-fala-de-relacionamento-abusivo.ghtml
```

### What happens?

There is this site called `raygun.io` that runs in the background of `g1.globo.com`. It seems to track problems that might occur with users. When I access `raygun.io`, it redirects to `raygun.com`, and there it says:

```
Real User Monitoring

Quickly identify and resolve front-end performance issues impacting real users, in real-time. Understand exactly how your application performed for every user session and page load.
```

### List Subscriptions you're using:

uBlock Filters
uBlock Filters - Badware risks
uBlock Filters - Privacy
uBlock Filters - Resource abuse
uBlock Filters - Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe's Ad and tracking server list
spa, por: AdGuard Spanish/Portuguese

### Your settings

- OS/version: Windows 10 Pro 21H1
- Browser/version: Google Chrome 96.0.4664.93
- Adblock Extension/version: uBlock Origin 1.39.2

### Other details:
Screenshot of uBlock in g1.globo.com:
![image](https://user-images.githubusercontent.com/30274161/145692893-cd764428-f117-4e06-b737-579711977bd3.png)

**Comment by spirillen** [comment]
Smells like `sentry.io`

What happens if you put this rule in your local filter??

```css
||raygun.io^
```

**Comment by Tiagoquix** [comment]
> What happens if you put this rule in your local filter??

Strangely, g1.globo.com no longer runs raygun.io in the background. But on raygun.com, blocking raygun.io doesn't seem to have made any visual difference. So I think the filter is all right.

**Comment by ryanbr** [comment]
We're blocking the event's for them, is there a privacy issue needing to block the entire domain?

**Comment by Tiagoquix** [comment]
> We're blocking the event's for them, is there a privacy issue needing to block the entire domain?

I'm not sure, I don't think so.

**Comment by spirillen** [comment]
Most admit, reading about what amount of data they do collect, I'm putting them to my Tracking blacklist

![image](https://user-images.githubusercontent.com/44526987/145821589-c159cb68-e28c-4916-af99-09540235ad0f.png)

![image](https://user-images.githubusercontent.com/44526987/145821617-c9c90c88-361d-46a6-8bf4-1e2ed974c5fc.png)

This is to close, to be randomized.

------------

Found this one in the archives as I was about to add this one `https://github.com/ryanbr/fanboy-adblock/pull/323` 

> Sources from https://github.com/ryanbr/fanboy-adblock/pull/323

**Comment by ryanbr** [comment]
I'm leaving it for the time being
