### ISSUE TITLE
zpaste.net

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10023]
### List the website(s) you're having issues:
`https://www.zpaste.net/p/rxukn`

### What happens?
Ads banner.

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0
- Adblock Extension/version: ublock 1.39.2

### Other details:
![image](https://user-images.githubusercontent.com/66517106/145714429-5e7504a2-9477-4865-83c0-64c17b6ebdfd.png)

Proposed filter:

`zpaste.net##.uk-animation-shake`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ea172f79157210e82f9dbc80eff43a714a93f8b3
