### ISSUE TITLE
androidsage.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10029]
### List the website(s) you're having issues:
`https://www.androidsage.com/`

### What happens?
Ads placeholder

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0
- Adblock Extension/version: ublock 1.39.2

### Other details:
![image](https://user-images.githubusercontent.com/66517106/145749936-73e6521e-660b-45e6-90bd-3b64a4ae218f.png)

Proposed filter:

`androidsage.com##.code-block-1`

**Comment by Nojuuu** [comment]
I'd suggest:
`androidsage.com#?#.code-block:-abp-has([data-ad-slot])`
