### ISSUE TITLE
gogoanime.se

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#1002]
https://gogoanime.se

`//jsc.mgid.com/g/o/gogoanime.io.192041.js?t=`

Found it was this one which show those currently unblocked ads.

**Comment by Khrin** [comment]
And also this is already blocked, are you trying to just guessing? I don't see any unblocked advert on this site.

**Comment by runboy93** [comment]
Using Fanboy Ultimate list, for some reason under "Advertisements" place on the websites there is text "mgid" and under it some random dating ads.

Strange.

**Comment by runboy93** [comment]
I guess local variable just makes it harder to block.

**Comment by runboy93** [comment]
`http://mgid.com/advertisers?utm_source=widget&utm_medium=text&utm_campaign=add&utm_content=192145`

**Comment by runboy93** [comment]
`https://www.mgid.com/ghits/2635970/i/18469/0/src/138805866/pp/1/2?h=dEom8uSGLLkoZDNxFURHtYLbMQgTG8HMR3dy_6UcAMu9bq2Khm5tQCF6MgeUb2di&rid=04bb9e24-3408-11e8-92c0-141877677254&tt=Direct&k=192145fch4s328RmIfX!fWJ6ho1tfWJ6jM4mfIufh%3DfV%24f!ffU%24f0!fk!fSfLb6LbBfV%24fQf%3AfaHR0cHM6Ly9nb2dvYW5pbWUuc2Uvfff%3Afh%3DfV%24f!fU%24fcfT*feAfQ8fWJ6hoyvf!fTW96aWxsY%2481LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChL%24FRNTCwgbGlrZ%24BHZWNrbykgQ2hyb21lLzY1LjAuMzMyN%244xODEgU2FmYXJpLzUzNy4zNiBPUFIvNTIuMC4yODcxLjM3fQ2hyb21pdW1QREZQbHVnaW58Q2hyb21pdW1QREZWaWV3ZXJ8TmV3c2ZlZWRoYW5kbGVy*FdpZGV2aW5lQ29udGVudERlY3J5cHRpb25Nb2R1bGU%3Df%2BfV2luMzI%3DfMTgwf%3DfeAfQaf!f!f*f*f*f*`

`https://www.mgid.com/ghits/2669376/i/18469/0/src/138805866/pp/2/2?h=dEom8uSGLLkoZDNxFURHtYF8MS6eN2GsCAhby1bVFmmHcVAepd9Sn1CPcUczezVJ&rid=04bb9e24-3408-11e8-92c0-141877677254&tt=Direct&k=192145fch4s328RmIfu!fWJ6ho1tfWJ6jS_HfIufg*fr%3Bf!ffp%24fa%3Dfk~fifLb6LbBfr%3BfQf%3AfaHR0cHM6Ly9nb2dvYW5pbWUuc2Uvfff%3Afg*fr%3Bf!fp%24fcfT*feAfQ8fWJ6hoyvf!fTW96aWxsY%2481LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChL%24FRNTCwgbGlrZ%24BHZWNrbykgQ2hyb21lLzY1LjAuMzMyN%244xODEgU2FmYXJpLzUzNy4zNiBPUFIvNTIuMC4yODcxLjM3fQ2hyb21pdW1QREZQbHVnaW58Q2hyb21pdW1QREZWaWV3ZXJ8TmV3c2ZlZWRoYW5kbGVy*FdpZGV2aW5lQ29udGVudERlY3J5cHRpb25Nb2R1bGU%3Df%2BfV2luMzI%3DfMTgwf%3DfeAfQaf!f!f*f*f*f*`

`https://www.mgid.com/ghits/2656173/i/18469/0/src/138805866/pp/3/2?h=dEom8uSGLLkoZDNxFURHtas9lhjjiqbvZgZRVerUxl1S2ef9VUvV0ol7rmZUYocm&rid=04bb9e24-3408-11e8-92c0-141877677254&tt=Direct&k=192145fch4s328RmIfIbfWJ6ho1tfWJ6jYO8fIufd%3Af9%2Bf!ffv*fM*fl%3DfU%3BfLb6LbBf9%2BfQf%3AfaHR0cHM6Ly9nb2dvYW5pbWUuc2Uvfff%3Afd%3Af9%2Bf!fv*fcfT*feAfQ8fWJ6hoyvf!fTW96aWxsY%2481LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChL%24FRNTCwgbGlrZ%24BHZWNrbykgQ2hyb21lLzY1LjAuMzMyN%244xODEgU2FmYXJpLzUzNy4zNiBPUFIvNTIuMC4yODcxLjM3fQ2hyb21pdW1QREZQbHVnaW58Q2hyb21pdW1QREZWaWV3ZXJ8TmV3c2ZlZWRoYW5kbGVy*FdpZGV2aW5lQ29udGVudERlY3J5cHRpb25Nb2R1bGU%3Df%2BfV2luMzI%3DfMTgwf%3DfeAfQaf!f!f*f*f*f*`

OK :D

**Comment by runboy93** [comment]
I also noticed from Ultimate list txt, that "https" variant for mgid seem to be missing from list.
