### ISSUE TITLE
uploadcloud.pro

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10028]
### List the website(s) you're having issues:
`https://www.uploadcloud.pro/hzug6vgx4fsk/Awesome_Bundles_35_Best_Seller_Font_Collection-sanet.st.rar.html`

### What happens?
Ads banner

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0
- Adblock Extension/version: ublock 1.39.2

### Other details:

![image](https://user-images.githubusercontent.com/66517106/145747153-0eaa2cb1-8c79-45a3-b550-a412a86c4aa3.png)

Proposed filter:

`||desirefx.com^$domain=uploadcloud.pro`

**Comment by stephenhawk8054** [comment]
Oh sorry, looks like blocking it triggers an anti-adblock

**Comment by JobcenterTycoon** [comment]
`desirefx.com##img[src^="https://www.desirefx.com/wp-content/uploads/Baners/"]` works without triggering anti adb
