### ISSUE TITLE
[EasyPrivacy] Soundcloud tracking

### ISSUE THREAD

**Issue by D4v1dH03** [easylist/easylist#10022]
### List the website(s) you're having issues:

`https://s.pwt.soundcloud.com/1.gif`
`https://l9bjkkhaycw6f8f4.soundcloud.com/me`
### What happens?

The first URL above generates 1x1 tracking pixels
while the second URL sends `POST` method analytical events (and the subdomain is changing periodically)
### List Subscriptions you're using:

uBlock filters

uBlock filters – Badware risks

uBlock filters – Privacy

uBlock filters – Resource abuse

uBlock filters – Unbreak

EasyList

Block Outsider Intrusion into LAN

EasyPrivacy

Online Malicious URL Blocklist

PUP Domains Blocklist

Anti-Facebook

Fanboy’s Social

uBlock filters – Annoyance
### Your settings

- OS/version:  macOS 12.0.0.1
- Browser/version: Firefox Nightly (2021-12-11)
- Adblock Extension/version: uBlock origin 1.39.3b8

### Other details:

<img width="1280" alt="Screenshot 2021-12-11 at 23 50 46" src="https://user-images.githubusercontent.com/81270448/145704918-67f3b188-08d3-4996-a344-6773a88a296f.png">

Purposed filters:
```
||pwt.soundcloud.com
```
I don't know what to do with the second one though

**Comment by D4v1dH03** [comment]
@ryanbr this is a major tracker network

**Comment by ryanbr** [comment]
What exactly is a "major tracker network" ?  Soundcloud?

**Comment by D4v1dH03** [comment]
> What exactly is a "major tracker network" ?  Soundcloud?

Yes. Exactly. And here is their privacy policy excerpt which proves that. (Especially in the last screenshot)

Whether you have an account or not they track you.
![Screenshot_20211215-092259.jpg](https://user-images.githubusercontent.com/81270448/146234659-6ec881d8-e5fa-4e35-95cb-2bcf8d5a4423.jpg)
![Screenshot_20211215-092439.jpg](https://user-images.githubusercontent.com/81270448/146234831-78ac5d4c-f7a9-4cee-afe0-b053585fc09d.jpg)
![Screenshot_20211215-092456.jpg](https://user-images.githubusercontent.com/81270448/146234857-da180f55-5c83-4251-9b4f-b38878a9f83d.jpg)

**Comment by spirillen** [comment]
Thanks for that feedback @D4v1dH03 

Is it possible (as reader of this thread) to have you adding 

```
<details><summary>Click to expand</summary>

</details>
```

Around the imaes to decrease the amount of scrolling when revisiting this issue?

**Comment by D4v1dH03** [comment]
OK, done!

**Comment by D4v1dH03** [comment]
For the second domain though the following POST request in JSON proves it
```
{"events":[{"event":"pageview","version":"v0.0.0","payload":{"user":"[REDACTED]","level":"homepage","chapter":"home::home/main","page_name":"homepage:main","locale":"en","navigation_type":"initial","currently_playing":"false","anonymous_id":"[REDACTED]","client_id":"[REDACTED]","ts":"1639596546858","url":"https://soundcloud.com/","app_version":"1639583478","part_of_variants":"2441"}}]}
```
whether logged in or not

The subdomain rotates periodically, which makes it difficult to match
