### ISSUE TITLE
Blank Empty Spaces

### ISSUE THREAD

**Issue by blogmangit** [easylist/easylist#10021]
There are lots of blank empty spaces on the following sites:

https://m.timesofindia.com/tv/news/hindi/taarak-mehta-ka-ooltah-chashmahs-raj-anadkat-aka-tapu-to-quit-the-show-will-wrap-up-shoot-before-christmas-exclusive/amp_articleshow/88221988.cms

https://indianexpress.com/article/entertainment/movie-review/chandigarh-kare-aashiqui-movie-review-the-ayushmann-khurrana-starrer-oddly-generic-7665262/lite/

https://m.timesofindia.com/entertainment/hindi/bollywood/news/samantha-ruth-prabhu-reacts-to-her-divorce-with-naga-chaitanya-exclusive/amp_articleshow/88215245.cms

https://www.hindustantimes.com/amp

https://www.hindustantimes.com/entertainment/bollywood/mira-rajput-reacts-to-trolls-commenting-on-her-feet-with-sassy-new-post-fans-call-it-best-clap-back-ever-101639208539406-amp.html

https://indianexpress.com/article/entertainment/web-series/aarya-2-review-sushmita-sen-is-back-with-a-bang-7665323/lite/

https://www.moneycontrol.com/news/business/companies/vedanta-board-approves-rs-5019-crore-as-second-dividend-for-fy2021-22-7815721.html/amp

https://www.ndtv.com/education/cbse-class-10-english-exam-2021-both-questions-were-complete-controller-sanyam-bhardwaj-cbseonline-nic-in/amp

https://m.economictimes.com/news/india/how-to-win-customers-and-influence-buying/amp_articleshow/88214251.cms

https://www.ndtv.com/entertainment/bharti-singh-and-husband-haarsh-limbachiyaa-announce-pregnancy-see-trending-post-2646359/amp/1

https://www.ndtv.com/entertainment/bharti-singh-and-husband-haarsh-limbachiyaa-announce-pregnancy-see-trending-post-2646359#comments_result

**Comment by DandelionSprout** [comment]
My personal understanding is that https://filters.adtidy.org/ios/filters/11.txt has a lot of entries for `AMP` sites. Although the list is designed solely for AdGuard and uBlock Origin, approx. 80% of its entries work in ABP.

**Comment by Khrin** [comment]
Added the relevant filters.
