### ISSUE TITLE
foxbusiness.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10027]
### List the website(s) you're having issues:
`https://www.foxbusiness.com/entertainment/ryan-reynolds-makes-an-official-peloton-ad-after-viral-and-just-like-that-moment`

### What happens?
Ads placeholder

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0
- Adblock Extension/version: ublock 1.39.2

### Other details:
![image](https://user-images.githubusercontent.com/66517106/145742465-528395e3-a163-4c69-ba71-f41964594318.png)

Proposed filter:

`foxbusiness.com##.pre-content`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e8b5cf62eb54227961166e24db52b679175295a4
