### ISSUE TITLE
ckstatic.com/js/historyjs/history.js

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#10039]
### List the website(s) you're having issues:
```
https://ckstatic.com/js/historyjs/history.js
```

## Relations?
  - https://mypdns.org/my-privacy-dns/matrix/-/issues/3877
  - https://mypdns.org/my-privacy-dns/matrix/-/issues/3875
  - https://mypdns.org/my-privacy-dns/matrix/-/issues/3876
  - https://github.com/easylist/easylist/pull/10009#issuecomment-991468347

### What happens?
 - [ ] Exit popup -under
 - [ ] on click script redirecting to other sites + pop- (under|up)
 - [ ] Exit script redirecting to other porno sites
 - [ ] AdWare 
 - [ ] Tracking
- [x] not sure

### List Subscriptions and settings:

```yml
uBlock Origin: 1.39.2
Firefox: 91
filterset (summary): 
  network: 148341
  cosmetic: 155499
  scriptlet: 33391
  html: 1271
listset (total-discarded, last updated): 
  removed: 
    ublock-unbreak: null
  added: 
    https://my-external-stuff.github.io/ublockorigin-rules/blockrules.txt: 282687-21526, 1d.1h.50m
  default: 
    ublock-filters: 30335-30237, 1d.2h.5m
    ublock-badware: 3543-3543, 1d.2h.3m
    ublock-privacy: 185-185, 1d.2h.1m
    ublock-abuse: 72-72, 1d.1h.59m
    easylist: 61639-5575, 1d.1h.57m
    easyprivacy: 26486-12918, 1d.1h.55m
    urlhaus-1: 7830-0, 1d.1h.52m
    plowe-0: 3698-3688, 5d.6h.9m
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1600
  launchFromSelfie: true

```

### Other details:
I found this script inside the js code in https://github.com/easylist/easylist/pull/10009#issuecomment-992659192

The problem is I#m not sure how this one should be classified, Maybe a JS geek could give a hand.

## Disclaimer
<details><summary>Free commit</summary>

Unlike other, who are harassing other users, an [taking toll](https://github.com/easylist/easylist/issues/9981#issuecomment-989728630) for there "commit"

![image](https://user-images.githubusercontent.com/44526987/145450145-0df3baca-ed52-4b12-8d56-1703b7d72070.png)

</details>

This commit was added at no charge and without any personal beneficial.

**Comment by ryanbr** [comment]
Sample website @spirillen ?

**Comment by spirillen** [comment]
ohhh which was it... it origined from on @Yuki2718 just posted.....

It came from [vfghc.com](https://mypdns.org/my-privacy-dns/matrix/-/issues/3877) via `irtya.com` and `irtyc.com`

Have the code snippet here https://mypdns.org/my-privacy-dns/matrix/-/issues/3877#relevant-comments

**Comment by spirillen** [comment]
Trada... found the original PR https://github.com/easylist/easylist/pull/10009

**Comment by ryanbr** [comment]
Wasnt seen here.

**Comment by spirillen** [comment]
Well that is actually not the most important for this issue, the question is if any of you JS guys could decode the script for what it is doing; is it a neutral or evil script?

**Comment by ryanbr** [comment]
Its hard to say what it does, https://pastebin.com/p4RcrsFB  (cleaned up), but without actual tests/examples this has to be denied.

**Comment by spirillen** [comment]
Ok, thanks for trying ryan
