### ISSUE TITLE
DanskeBank sites - Broken (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#10035]
Full info here:
https://github.com/AdguardTeam/AdguardFilters/issues/102909#issuecomment-992330510

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e7b54192e4bd7a70c0c29be9e88134cb94a5ee75

**Comment by THEtomaso** [comment]
> https://github.com/easylist/easylist/commit/e7b54192e4bd7a70c0c29be9e88134cb94a5ee75

That only fixes the issue @ `danica.no`, `danicapension.dk` and `danskeci.com`.
The rest of the sites are still broken, like before!

Also, instead of only adding whitelistings for the bare minimum of problem rules, why not include whitelistings for all of the problem rules, which I pointed out?
This would allow users to actually read up on the agreement terms, instead of just blindly having to accepting them!

**Comment by ryanbr** [comment]
I must be blind, but I counted 8 domains in that one commit.

**Comment by THEtomaso** [comment]
Yeah, but `#@#.cookie-consent-banner` is not enough for `danskebank.co.uk`, `danskebank.com`, `danskebank.dk`, `danskebank.fi`, `danskebank.no` and `danskebank.se` !

**Comment by ryanbr** [comment]
What we already have; I'm not seeing issues currently

```
danskebank.*##+js(remove-class, cookie-consent-banner-open, html)
danica.no,danicapension.dk,danskebank.co.uk,danskebank.com,danskebank.dk,danskebank.fi,danskebank.no,danskebank.se,danskeci.com#@#.cookie-consent-banner
```

**Comment by THEtomaso** [comment]
From my end, the sites are still broken, because of this rule (which you need to remove):
`danskebank.*##.cookie-consent-banner-modal`
@DandelionSprout; Could you please confirm this, from your location?

Preferably, this rule should be whitelisted too:
`###cookie-text`
..in order to allow users to read up on the cookie terms.

**Comment by DandelionSprout** [comment]
After testing with EasyList cookie on and the IDCAC extension off, I am sorry to say that I can't seem to reproduce this in Chrome.

**Comment by THEtomaso** [comment]
Thanks for testing, DS.
I've found the problem..

This rule does NOT work in uBO Legacy!:
`danskebank.*##+js(rc, cookie-consent-banner-open, html)`

Does it even work in ABP-based blockers now?

**Comment by AroKol78** [comment]
> This rule does NOT work in uBO Legacy!:

does not work **only** in "My filters" (use the full name for tests)
in other filters it works - it is automatically converted
https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/src/js/assets.js#L363

**Comment by THEtomaso** [comment]
@AroKol78:
Look at my edits, in my previous post.

**Comment by THEtomaso** [comment]
@okiehsch:
Until these issues have been sorted out, could you add the rules that I posted here (under "Possible fix") to `uBlock filters - Legacy`?:
https://github.com/AdguardTeam/AdguardFilters/issues/102909#issuecomment-992330510

**Comment by THEtomaso** [comment]
I didn't get an answer to my question here:
https://github.com/easylist/easylist/issues/10035#issuecomment-994794684
..which was "what about people using ABP-based blockers?".

They don't take advantage of the uBO-specific `##+js` rule.
Therefore, this remaining problem rule still breaks the sites for them!:
`danskebank.*##.cookie-consent-banner-modal`
Right?

Also, this rule still prevents users from reading the cookie terms:
`###cookie-text`
Easylist Cookie List already allows it for the `.fi` domain, with this rule:
`danskebank.fi#@##cookie-text`
It should be changed into this:
`danica.no,danicapension.dk,danskebank.co.uk,danskebank.com,danskebank.dk,danskebank.fi,danskebank.no,danskebank.se,danskeci.com#@##cookie-text`
