### ISSUE TITLE
wiki.iota.org & iota.org

### ISSUE THREAD

**Issue by r-c-k** [easylist/easylist#10067]
### List the website(s) you're having issues:

`https://wiki.iota.org`
`https://iota.org`

### What happens?

Fanboy's Annoyances causes several misplaced elements on `iota.org` domains, especially `wiki.iota.org`.

### List Subscriptions you're using:

- EasyList + AdGuard basis
- _**Fanboy's Annoyances**_
- Web Annoyances Ultralist

### Your settings

- OS/version: macOS 12.1 
- Browser/version: Safari 15.2
- Adblock Extension/version: AdGuard for Safari 1.10.4

### Other details:

Turning off _**Fanboy's Annoyances**_ resolves the issue.
<img width="1344" alt="Bildschirmfoto 2021-12-14 um 18 14 40" src="https://user-images.githubusercontent.com/17240275/146052324-2ca0697f-c81e-42cd-b9ea-095fdc5d4593.png">
<img width="985" alt="Bildschirmfoto 2021-12-14 um 18 15 28" src="https://user-images.githubusercontent.com/17240275/146052349-0e166a4f-5ab5-40fc-a77f-f3a1546ea8a1.png">
<img width="654" alt="Bildschirmfoto 2021-12-14 um 18 16 09" src="https://user-images.githubusercontent.com/17240275/146052362-f8a19079-208b-46b8-a8ed-171f4dd4f6eb.png">

**Comment by ryanbr** [comment]
@r-c-k  I'm not seeing any issues with the site (Tested in Brave + Annoyances, and uBO +Annoyances)

**Comment by ryanbr** [comment]
No further followup, closing.
