### ISSUE TITLE
Foxnews videos only work if EasyPrivacy is disabled

### ISSUE THREAD

**Issue by lakrsrool** [easylist/easylist#1007]
URL example: http://www.foxnews.com/science/2018/04/01/11-foot-alligator-caught-in-florida-pool.html

Video fails to play unless I disable EasyPrivacy in the ABPrime add-on (same situation if using uBlock Origin as well)

Using subscriptions: Disable Malware and EasyPrivacy in ABPrime extension.

OS: Windows 7
Browser: Pale Moon 27.8.3
ABPrime version: 1.0.4

ADDENDUM: FWIW - I just now found out I get the same problem if I use EasyList as well.  So if either EasyPrivacy or EasyList is used then videos will not play on Foxnews.com (example video above).

**Comment by ryanbr** [comment]
Seems fine here, update subscriptions and re-test.
