### ISSUE TITLE
thefederalist.com ads loading through customads.co

### ISSUE THREAD

**Issue by yourduskquibbles** [easylist/easylist#10072]
### List the website(s) you're having issues:

`https://thefederalist.com/2021/12/15/during-january-6-hearing-schiff-doctored-text-messages-between-mark-meadows-and-rep-jim-jordan/`

### What happens?

Ad at bottom of page coming in from `customads.co` iframe 
![federalist](https://user-images.githubusercontent.com/22258847/146250508-544ba397-6ed3-4966-bc70-4ff36c5a05b8.png)

### List Subscriptions you're using:

- Default uBlock Origin lists + uBlock filters - Annoyances

### Your settings

- Chrome test profile with default uBlock Origin settings and lists + uBlock Annoyances
- OS/version: Windows 11 64bit
- Browser/version: Chrome Version 97.0.4692.45 (Official Build) beta (64-bit)
- Adblock Extension/version: uBlock Origin 1.39.3b10 (Latest Dev Build available on Chrome Web Store)

### Other details:

@pgl may want to add this domain to Peter Lowe host file as well?

**Comment by pgl** [comment]
@spirillen Thank you, added: https://pgl.yoyo.org/adservers/details.php?hostname=customads.co

**Comment by spirillen** [comment]
@pgl isn't it host file style you are using for blacklisting? in that case I believe you should choose `cdn2.customads.co` over `customads.co` as that is where the script is hosted. Just a note

https://pgl.yoyo.org/adservers/details.php?hostname=cdn2.customads.co

**Comment by pgl** [comment]
@spirillen It can be used as a hosts file, but that's not the most efficient use. I only add the highest-level part of a domain I can.

For a domain like `customads.co` with a blank page at the root, it seems that the whole domain is going to be used for serving ads or tracking or something similar. A hostname like `cdn2.customads.co` indicates that there's probably at least a `cdn.customads.co` or `cdn1`, probably more.

**Comment by spirillen** [comment]
Then we are actually doing the very same thing, based on the very same arguments. I couldn't have written your answer better myself. it will however also leave hosts file based filters rather crippled :smirk: 

Nice you pointed that out as I was clearly convinced you went all hosts style.

**Comment by pgl** [comment]
There are far better resources than my list out there for people who want to use hosts files. @StevenBlack's list, among others, is excellent.
