### ISSUE TITLE
thestar.co.uk [breakage, video in articles not loading]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#10070]
### List the website(s) you're having issues:

Example article: `https://www.thestar.co.uk/news/crime/high-street-sheffield-police-and-paramedics-deployed-to-city-centre-over-reports-of-womans-death-3494963`

### What happens?

Breakage, video in articles not loading.

### List Subscriptions you're using:

Lists causing the video breakage:
- EasyList
- AdGuard Tracking Protection
- uBlock Privacy

### Your settings

- OS/version: Win
- Browser/version: Firefox / Opera
- Adblock Extension/version: -

### Broken:
![1 (3)](https://user-images.githubusercontent.com/75935068/146164354-d5f56b7a-e091-4893-9514-7160f367449e.png)

### Working:
![1 (4)](https://user-images.githubusercontent.com/75935068/146164367-2060aac0-a38c-4d6b-b4cb-ae98ddab3564.png)

**Comment by ryanbr** [comment]
Invideo ads.

**Comment by felix-22** [comment]
To be clear: "Considered invideo advert" (like in https://github.com/easylist/easylist/issues/9738#issuecomment-971140337) sounds better, stick to the same terminology and avoid offensive manipulation / half-truth because that can wrongly suggest people that I have been reporting an invalid issue. What I reported was a "legitimate" video, not an in-video ad, it's not my job to further analyse whether a legitimate video still turns out to be treated as an ad or not, by a filter list maintentainer.


<details>
<summary>screenshoot 1 - invideo ad (has AD label)</summary>

![w](https://user-images.githubusercontent.com/75935068/146169323-b413b9d5-a7d1-41a0-9593-f6469e3eb432.png)

</details>


<details>
<summary>screenshoot 2 - a "legitimate" video (doesn't have AD label)</summary>

![3333](https://user-images.githubusercontent.com/75935068/146169473-afd2318b-f1fd-4f0a-ac5f-a33220d1ebcd.png)

</details>

Now fuuck off asshole.
