### ISSUE TITLE
nullpress.net

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10075]
### List the website(s) you're having issues:
`https://nullpress.net/`

### What happens?
Ads banner and placeholder

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0
- Adblock Extension/version: ublock 1.39.2

### Other details:
![image](https://user-images.githubusercontent.com/66517106/146303143-5a14af64-c433-4bfe-9e22-64d3b98f9990.png)

Proposed filter:

`nullpress.net##.sidebar`

**Comment by edivaniadc** [comment]
@ryanbr can you please also hide sidebar placeholder?
Proposed filter:`nullpress.net##.wrapper-sticky`

<img width="1353" alt="np" src="https://user-images.githubusercontent.com/57706597/147121059-07cf606c-2320-4340-8b7c-92972e460568.png">
