### ISSUE TITLE
qreferat.com blank spaces

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#10121]
### List the website(s) you're having issues:
`https://www.qreferat.com/referate/turism/Turismul-montan-aspecte-genera318.php`

### What happens?
I see some blank spaces on the site I posted above.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:
![imageedit_2_7789642478](https://user-images.githubusercontent.com/79897301/146530104-448c39a3-db97-4c34-931f-c03326edd137.gif)
![imageedit_1_7307004187](https://user-images.githubusercontent.com/79897301/146530098-c7e388d6-1e53-4a5f-8b7d-e3a934341c37.gif)

**Comment by ryanbr** [comment]
Need to submit to Romanian regional list.  `qreferat.com##[style^="overflow:auto;"]`
