### ISSUE TITLE
glosbe.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10163]
### List the website(s) you're having issues:
`https://en.glosbe.com/en/de/translation`

### What happens?
Ads placeholder at the top

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0.1
- Adblock Extension/version: ublock 1.39.2

### Other details:
![image](https://user-images.githubusercontent.com/66517106/146637140-98373a22-dd2e-4f6d-a2ce-f4bea307c9cf.png)

Proposed filter:

`glosbe.com###topBannerContainer`

**Comment by Khrin** [comment]
Seems to be already blocked.

**Comment by okiehsch** [comment]
I can reproduce on every page.
You have only `danpatrick.com###topBannerContainer` in EasyList, so I don't think that this is already blocked.
