### ISSUE TITLE
techbone.net cookie

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#10160]
### List the website(s) you're having issues:
`https://www.techbone.net/xiaomi/redmi-8`

### List Subscriptions you're using:
Easylist Cookie

### Your settings

- OS/version: Windows
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin

### Other details:
This filter causes the issue: `###cookie_banner`
* Easylist Cookie enabled:
![image](https://user-images.githubusercontent.com/17685483/146634557-b5b08a77-5600-48fd-86ad-ad8873906b50.png)
* Easylist Cookie disabled:
![image](https://user-images.githubusercontent.com/17685483/146634569-4d0c08f0-7652-4785-b846-7905279adeb5.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/cd23c06cecd1f24a103279e83493442e80012383
