### ISSUE TITLE
nomoresecrets.pl [EasyPrivacy]

### ISSUE THREAD

**Issue by WowDude** [easylist/easylist#1017]
https://github.com/MajkiIT/polish-ads-filter/issues/6807

**Comment by Khrin** [comment]
What's the issue there?

**Comment by WowDude** [comment]
@Khrin 

With EasyPrivacy enabled, the popup appears:

> Your browser blocks some of the features of this site. Follow the instructions at http://support.heateor.com/browser-blocking-social-features/ to unlock them.

After disabling EasyPrivacy the popup disappears.

**Comment by ryanbr** [comment]
Its more of a site issue, we shouldn't compromise privacy because of a warning.
