### ISSUE TITLE
symbolab.com cookie

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#10170]
### List the website(s) you're having issues:
`https://www.symbolab.com/solver/`

### What happens?
Cookie banner isn't removed

### List Subscriptions you're using:

EasyList Cookie
### Your settings

- OS/version: Windows
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin

### Other details:
Solution: `symbolab.com##.nl-cookiepolicy`

![image](https://user-images.githubusercontent.com/17685483/146669584-baa83b25-46e1-4b15-970e-89258ffbdda3.png)

**Comment by ryanbr** [comment]
We already have `##.nl-cookiepolicy` as a generic filter, maybe clear cache/force update.
