### ISSUE TITLE
[NSFW] imgbabes.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10178]
### List the website(s) you're having issues:
`https://www.imgbabes.com/f/7zvfh6yjmdtt/SIM-080_s.jpg.html`

### What happens?
Ads placeholder at the top.

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0.2
- Adblock Extension/version: ublock 1.39.2

### Other details:
<details><summary>Screenshot</summary>

https://user-images.githubusercontent.com/66517106/146696741-59a35770-3476-468b-aea5-f4ee0e5fe4d1.png

</details>

Proposed filter:

`imgbabes.com###download > div > div`

**Comment by spirillen** [comment]
Hmm I never get passed the  `Preparing your request...` `Continue to your image`
