### ISSUE TITLE
Adobe Fonts `primer.typekit.net` tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#10176]
https://theinitium.com/article/20210225-hongkong-cable-tv-china-desk-feature/ --> `POST` `https://primer.typekit.net/primer/******************`

```
||primer.typekit.net^
```

![image](https://user-images.githubusercontent.com/75058881/146687058-a4413dba-4576-4c16-9c98-3e6248170f10.png)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/9f96be9e981d2045aa00b42610356dbd1b17f983
