### ISSUE TITLE
wolframalpha.com is broken with EasyPrivacy

### ISSUE THREAD

**Issue by henk23** [easylist/easylist#10194]
### List the website(s) you're having issues:

```
wolframalpha.com
```

### What happens?

Cannot load required JS from wal.wolfram.com

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: macOS 12.1
- Browser/version: Firefox 95
- Adblock Extension/version: Pi-Hole 5.6

**Comment by ryanbr** [comment]
What is the issue, `wolframalpha.com` loads. https://www.wolframalpha.com/input/?i=how+many+elements+in+the+periodic+table&lk=3   Will close this request if not enough infomation supplied.

**Comment by henk23** [comment]
Sorry. Seems to have resolved itself. Yesterday I had to whitelist *.wolfram.com for the page to load. Now it loads fine without the whitelist entry.

Thanks for looking into it, the issue can be closed.
