### ISSUE TITLE
New tracker?: pixel.streetmetrics.io

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#10206]
### List the website(s) you're having issues:

`https://geologie.com`

### What happens?

`pixel.streetmetrics.io`

### List Subscriptions you're using:

![ublock lists 14 Nov](https://user-images.githubusercontent.com/11689349/146974047-9ff37a16-4a72-4150-b6a8-14bc801c884e.jpg)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by spirillen** [comment]
Missed the "Sign up" overlay

```css
geologie.com###smsbump-form-39373
```

**Comment by spirillen** [comment]
My answer to your question is, I've added it as [SpyWare](https://mypdns.org/my-privacy-dns/matrix/-/issues/4004) in my end.
