### ISSUE TITLE
videobin.co (NSFW) cams.imagetwist.com ads

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#10208]
https://videobin.co/zm1golu3rgmj

Click anything on the website and it opens up new window to cams.imagetwist.com + there are advertisement under video player about same website.

Filterlists:

Fanboy Ultimate, uBlock filters (filters, privacy, resource abuse, annoyances), adguard filters (base, mobile, tracking protection, annoyances, social, experimental), Peter Lowe’s Ad and tracking server list and Web Annoyances Ultralist.

- OS/version: Lubuntu 20.04
- Browser/version: Vivaldi 5.0
- Adblock Extension/version: uBlock Origin development build 1.39.1b1

**Comment by spirillen** [comment]
I can't reproduce this in tor, and I only see a top bar.

**Comment by ryanbr** [comment]
Should be resolved.
