### ISSUE TITLE
[NSFW] assesphoto.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10213]
### List the website(s) you're having issues:
`https://www.assesphoto.com/adolescentes.shtml`

### What happens?
Ads banners at the top.

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0.2
- Adblock Extension/version: ublock 1.39.2

### Other details:
<details><summary>Screenshot</summary>

https://user-images.githubusercontent.com/66517106/147038564-2a0617bb-0d2f-4939-8e6e-ac23ad533993.png

</details>

Proposed filter:

`||nudedworld.com/js/*$domain=assesphoto.com`

**Comment by spirillen** [comment]
You should make it more generic as it is served on more sites

https://mypdns.org/search?scope=issues&search=nudedworld.com = Current 2 external sites
