### ISSUE TITLE
wnycstudios.org broken

### ISSUE THREAD

**Issue by prodan1234** [easylist/easylist#1021]
```
wnycstudios.org 
```

Header image broken. [This](https://imgur.com/a/MzCiM) is what it looks like with easylist. [This](https://imgur.com/a/XNVEY) is what it should look like.

OS/version: macOS 10.13.4
Browser/version: Chrome 66.0.3359.117 
Adblock Extension/version: uBlock Origin 1.15.24

**Comment by ryanbr** [comment]
Looks fine here, update subscriptions and report again.

**Comment by prodan1234** [comment]
Do you not get the huge white space? I still do.

**Comment by prodan1234** [comment]
It's blocking one of the pngs on the page for some reason. https://imgur.com/a/c8AZrNP

EDIT: Turns out it was the Web Annoyances list that was causing the problem https://github.com/yourduskquibbles/webannoyances

**Comment by ryanbr** [comment]
Probably not the most efficient list I've seen.

**Comment by prodan1234** [comment]
Yeah, it's not the best but it hasn't broken that many websites. Do you have any lists that you recommend besides the default ones (Easylist, Adguard, uBlock, Fanboy's, etc)?

**Comment by ryanbr** [comment]
Install the ultimate list, but I'm just biased; https://www.fanboy.co.nz/filters.html
