### ISSUE TITLE
Chinese `bilibili` tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#10259]
https://www.bilibili.com/video/BV1R34y1R7ps/ --> https://api.bilibili.com/x/player/online/total?aid=934529384&cid=454387327&bvid=BV12M4y1P7ML&ts=54676440

You can check the streaming viewer numbers for the same video at this URL:
`https://api.bilibili.com/x/player/online/total?aid=934529384&cid=454387327&bvid=BV12M4y1P7ML&ts=54676440`

`https://api.bilibili.com/x/player/online/total?aid={video's aid ID}&cid={video's cid ID}&bvid={video's bvid ID}&ts={what part of the video you are watching at the moment}`

It will automatically refresh every few seconds, and no `Cookie` is needed to get the content, so...~

```
||api.bilibili.com/x/player/online/total$removeparam=ts
||api.bilibili.com/x/player/online/total$cookie
```

**Comment by c2xusnpq6** [comment]
One more, https://www.bilibili.com/video/BV1R34y1R7ps/ --> https://upos-hz-mirrorakam.akamaized.net/upgcxcode/76/95/452019576/452019576-1-30080.m4s?hdnts=exp=1640301325~hmac=502507765248beb5fa12c923763fc9a1643307b6a6b24de274d8f6a8cffbe956&mid=1108298144&bvc=vod&orderid=0,1&agrr=0&bw=328804&logo=80000000

```
||akamaized.$removeparam=uparams
||akamaized.$removeparam=upsig
||akamaized.$removeparam=platform
||akamaized.$removeparam=trid
||akamaized.$removeparam=oi
||akamaized.$removeparam=os
||akamaized.$removeparam=gen
||akamaized.$removeparam=deadline
||akamaized.$removeparam=nbs
||akamaized.$removeparam=uipk
||akamaized.$removeparam=e

or

upgcxcode$removeparam=uparams
upgcxcode$removeparam=upsig
upgcxcode$removeparam=platform
upgcxcode$removeparam=trid
upgcxcode$removeparam=oi
upgcxcode$removeparam=os
upgcxcode$removeparam=gen
upgcxcode$removeparam=deadline
upgcxcode$removeparam=nbs
upgcxcode$removeparam=uipk
upgcxcode$removeparam=e
```

**Comment by ryanbr** [comment]
We don't support any of those flags in EL/EP.
