### ISSUE TITLE
repost.aws

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#10255]
### List the website(s) you're having issues:

```
https://www.repost.aws/
```

### What happens?

App performance is being reported to following endpoint

```
https://clientlogger.marketplace.aws.a2z.com/v3/analytics/logs
```

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/62358249/124452393-41884700-dd7e-11eb-9f76-7820fcee5844.png)

</details>

### Your settings

- OS/version: macos 12.1
- Browser/version: Firefox 95.0.2
- Adblock Extension/version: ublock origin 1.39.3rc1

### Other details:

Suggested filter

```
/analytics/logs
```
or

```
||clientlogger.marketplace.aws.a2z.com^
```

**Comment by spirillen** [comment]
```css
||clientlogger.marketplace.aws.a2z.com^
```

Replace with (https://mypdns.org/my-privacy-dns/matrix/-/issues/3204)

```css
||a2z.com^
```

also related with:
- https://github.com/easylist/easylist/commit/108e13557bf92b5044553994df8348e30db75546
- https://github.com/easylist/easylist/issues/9474
