### ISSUE TITLE
myair2.resmed.com : cookie

### ISSUE THREAD

**Issue by Gitoffthelawn** [easylist/easylist#10269]
### List the website(s) you're having issues:

https://myair2.resmed.com

### What happens?

Cookie banner on top

### List Subscriptions you're using:

EasyList Cookie

### Your settings

- OS/version: Linux
- Browser/version: Firefox 95.0.2
- Adblock Extension/version:  uBO 1.40.0

**Comment by ryanbr** [comment]
Not seeing any cookie popup? screenshot? @Gitoffthelawn

**Comment by Gitoffthelawn** [comment]
@ryanbr Click on the names of any of the countries in the first 2 columns.  The cookie banner should appear on the top of the viewport on the resultant page.  If it doesn't, just let me know, and I'll get to a box on which I can take a helpful screenshot.
