### ISSUE TITLE
videocelebs.net (ad)

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#10261]
### List the website(s) you're having issues:
`https://videocelebs.net`
### What happens?

Top ad.

### List Subscriptions you're using:

Default uBlock Origin lists.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 95.0
- Adblock Extension/version: uBlock Origin 1.39.2

### Other details:

<details><summary>Screenshot (**NSFW**):</summary>

![image](https://user-images.githubusercontent.com/52135169/147323941-66e4dfaa-fd86-4474-b490-0a175173cc8e.png)

</details><br/>

**Comment by spirillen** [comment]
```css
videocelebs.net##.recl
```
