### ISSUE TITLE
Blocking badges and charts from Simple Analytics

### ISSUE THREAD

**Issue by adriaanvanrossum** [easylist/easylist#10265]
At Simple Analytics we created a domain that is completely separate from our other domains so keep our website working for people with ad-blockers. For that, we created [scripts.simpleanalyticscdn.com](https://scripts.simpleanalyticscdn.com).

https://github.com/easylist/easylist/blob/33f3d6c37d58252ef093c4ad243507fba64a4c48/easyprivacy/easyprivacy_trackingservers.txt#L2177-L2180

It's totally fine of course to block the simpleanalyticscdn.com domain, but it's super annoying that the badges don't work anymore and some embed charts stopped working. I don't think this was the intention of the contributor, but it would be nice to get this solved.

I think it's added in https://github.com/easylist/easylist/commit/834f81d7f3c09819e674c3a5c1a1e83167cee0ae.

It would be great if `simpleanalytics.com`, `simpleanalytics.io`, `simpleanalyticsbadge.com` would be allowed and just block `simpleanalyticscdn.com`. Everybody happy and we don't have a broken website anymore.

Here a screenshot of Easylist blocking a badge:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/1079135/147353458-4f7f07a2-b0e7-4261-b45f-5abd7914f0cb.png">

Thanks a lot for taking a look at this!

**Comment by spirillen** [comment]
Related to https://github.com/easylist/easylist/pull/1855

**Comment by krystian3w** [comment]
Normal clients no read bugs (something like newbie/noobs in webmastering) form console, so as long page render correctly filter may exist.
