### ISSUE TITLE
www.lego.com

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#10285]
### List the website(s) you're having issues:
`https://www.lego.com/en-us`

### What happens?
Cookie banner not only for the US language, but for any language.

### List Subscriptions you're using:
Fanboy Annoyance

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/aee455401e06568c3f203c2a4fb912108d64407b
