### ISSUE TITLE
reno.ro cosmetic filtering

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#10286]
### List the website(s) you're having issues:
`https://www.reno.ro/-t306101.html`

### What happens?
Blank spaces  
![imageedit_2_2564432719](https://user-images.githubusercontent.com/79897301/147405852-7f2579b0-cafa-4da5-bbe4-6707a4ad5e16.gif)

### List Subscriptions you're using:

Fanboy Annoyance
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
These should be fixed in ro list (ads)
