### ISSUE TITLE
`Brave` browser / `Startpage` tracking param

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#10288]
https://www.startpage.com/do/search?q=testing&segment=startpage.brave

```
||startpage.com^$removeparam=segment
```

**Comment by Nojuuu** [comment]
@iam-py-test

**Comment by iam-py-test** [comment]
@c2xusnpq6 Easylist does not cover tracking parameters. 
@Nojuuu Thank you. I fixed it in https://github.com/DandelionSprout/adfilt/commit/1a0187d54daa89e3e1466c2acbb642b280dc8886
Just quick question; does that domain use any other TLDs (i.e. net, cn, es)?

**Comment by ryanbr** [comment]
We don't support removeparam in EL
