### ISSUE TITLE
Today's Deals ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#103]
`http://www.timesunion.com/`
`http://www.timesunion.com/local/article/County-fair-to-gun-group-No-raffles-here-8353416.php`

Today's Deals powered by DealNews

and "latest news sponsored by st. peter's health" on the homepage link.

**Comment by terrorist96** [comment]
`http://www.chron.com/`
`http://www.chron.com/entertainment/celebrities/article/This-is-what-summer-fun-looks-like-for-Houston-9132020.php`

Today's Deals.

**Comment by terrorist96** [comment]
`http://www.ctpost.com/`
`http://www.ctpost.com/news/article/Most-anticipated-food-retail-additions-headed-to-10164421.php`

Todays' deals

**Comment by terrorist96** [comment]
`http://www.seattlepi.com/local/crime/article/Seattle-won-t-release-its-gun-tax-revenue-Here-s-10591975.php`

**Comment by monzta** [comment]
Added 
https://github.com/easylist/easylist/commit/c166e214557224740896ab7b0a86b1f552a646ca 
https://github.com/easylist/easylist/commit/7112a69a0b1971e991c9bcba66f40d98c65fdac8 
https://github.com/easylist/easylist/commit/ed39373c3af292ce20d8604ab37972815aeaace6 

Haven't seen it on chron.com though. Do you still see it?

**Comment by terrorist96** [comment]
Looks good. Thanks
