### ISSUE TITLE
zamel.com

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#10300]
https://github.com/easylist/easylist/blob/b7bfe007eda6e4e88722bea740d6065f93c4c3f9/fanboy-addon/fanboy_social_general_hide.txt#L10722

 `##.social-small` break top header with navigation at pages: 

`https://zamel.com/en/`
`https://zamel.com/pl/`
`https://zamel.com/ru/`
`https://zamel.com/it/`
`https://zamel.com/de/`
`https://zamel.com/uk/`

screen:

![obraz](https://user-images.githubusercontent.com/35370833/147504676-11c35544-16ac-41d6-8dff-429d53c1f335.png) |  ![obraz](https://user-images.githubusercontent.com/35370833/147504710-5f9fba3b-b8c5-4a90-a328-4e219cf37461.png)
--- | ---
bad | after manual fix

Possible fix:
`zamel.com#@#.social-small`

**Comment by spirillen** [comment]
Nice move @krystian3w using tables to control the screenshot sizes :+1:
