### ISSUE TITLE
bugs.avm99963.com

### ISSUE THREAD

**Issue by avm99963** [easylist/easylist#10305]
### List the website(s) you're having issues:

`bugs.avm99963.com`

### What happens?

Some features of the issue tracker don't work correctly (starring an issue, creating a new issue, etc.).

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: macOS 10.15
- Browser/version: Chrome 96.0.4664.110
- Adblock Extension/version: uBlock Origin 1.39.2

### Other details:

The filter which blocks the scripts which break the site is the following:

https://github.com/easylist/easylist/blob/8cf83867b4ceca9639e2121e581dfbdd160e3306/easyprivacy/easyprivacy_general.txt#L4434

As you can see there is already an exception for `bugs.chromium.org` (added in 66815f9), but `bugs.avm99963.com` also uses the same issue tracker software ([Monorail](https://chromium.googlesource.com/infra/infra/+/main/appengine/monorail/)) and so has the same problem.

This was reported initially for `bugs.chromium.org` by gorhill here: https://forums.lanik.us/viewtopic.php?f=64&t=40883

**Disclaimer**: `bugs.avm99963.com` is my issue tracker, which I host to track issues in my open source projects.

**Comment by spirillen** [comment]
Not much to see there.

```
drill bugs.avm99963.com
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 21044
```

**Comment by avm99963** [comment]
I understand you might be concerned with the fact that the website is hosted in Google Cloud, but I don't see how I'm "relying on spyware". Could you please expand on that?

`dns{n}.registrar-servers.com` are the nameservers my domain registrar provides me (Namecheap), and the CNAME record directs to Google servers.

**Comment by spirillen** [comment]
> "relying on spyware". Could you please expand on that?

What is it G is doing? anything for you, or providing you with cookies in exchange for all your data by spying on you? 

Every time your connection is touching any G it is used to profile you, and yes they now who you are just by touching there DNS servers, that is the first log, the next is from there other servers, G is giving you nothing, they are only taking, even if it appears they are giving, it's only honey to harvest your internal organ called free will.

This is also the very same reason I do not support Github but spending the bugs on hosting my own non tracking server.

Without Privacy, democracy can't prevail.

> ... record directs to Google servers.

All that I know and it is here the issue start with the G dns as they are block one several layers in my systems, this includes DNS and Firewall.

I'm thinking non of this matter a lot to you, as you are developing to the Chrome spyware :smirk:
