### ISSUE TITLE
[Easyprivacy request] [Meta] IP logger links

### ISSUE THREAD

**Issue by D4v1dH03** [easylist/easylist#10318]
### List the website(s) you're having issues:

See screenshots below:

<img width="122" alt="Screenshot 2021-12-28 at 21 54 07" src="https://user-images.githubusercontent.com/81270448/147631676-12005c6a-6113-49a6-b3ea-5d445a5268d0.png">

<img width="371" alt="Screenshot 2021-12-28 at 22 01 44" src="https://user-images.githubusercontent.com/81270448/147632171-0154cf7b-7668-400b-bd83-35ca52203f40.png">

### What happens?

When a visitor click such links with the domains above their full IP, user agent, referrer, ISP and geolocation are logged by a third and unknown party.

### List Subscriptions you're using:

EasyPrivacy
Easylist
Fanboy annoyances
Easylist cookies

### Your settings

- OS/version: macOS 12.1
- Browser/version: 
```
Brave | 1.35.62 Chromium: 97.0.4692.56 (Official Build) nightly (arm64)
Revision | 04da6c66398ca50e603cc236a07dc7dfd3bbc750-refs/branch-heads/4692@{#990}
```

- Adblock Extension/version: 
Aggressive ad block, aggressive fingerprint block
### Other details:
Those domains are SOLELY used for tracking and sometimes even doxxing.

<img width="903" alt="Screenshot 2021-12-28 at 21 58 13" src="https://user-images.githubusercontent.com/81270448/147631808-88eb6a06-286b-464a-81fd-73f940d87526.png">

<img width="1010" alt="Screenshot 2021-12-28 at 22 02 18" src="https://user-images.githubusercontent.com/81270448/147632016-40ecef4c-8c08-4361-a292-9aa18c17c74c.png">

Here is a good repo for reference for a rather comprehensive but not exhaustive links of IP loggers:
https://github.com/piperun/iploggerfilter/ 
They utilize `^$important,all`

**Comment by ryanbr** [comment]
I'm not seeing any issues. Create a link via `https://grabify.link/` Which just forwards to link'd website.

Enabling "Smart Logger" didn't make any difference.

**Comment by D4v1dH03** [comment]
> I'm not seeing any issues. Create a link via `https://grabify.link/` Which just forwards to link'd website.
> 
> Enabling "Smart Logger" didn't make any difference.

Yes, and the link creator can see the IP address of the visitor

**Comment by D4v1dH03** [comment]
<img width="1440" alt="Screenshot 2022-01-02 at 14 54 11" src="https://user-images.githubusercontent.com/81270448/147891599-dae5b988-4eec-4d8f-b0d4-987d84007cec.png">

Ryan, if the victim clicks or even `curl` _this_ link, then the creator can see everything

**Comment by ryanbr** [comment]
Using:: `https://grabify.link/1TRXYB` 

Logger off:
![grab-logger-off](https://user-images.githubusercontent.com/1659004/147891765-dcc10522-6ad7-4ab6-adca-0aa15bc35d5e.png)
Logger on:
![grab-logger-on](https://user-images.githubusercontent.com/1659004/147891767-0328af55-0116-4821-8f6c-2daec3a3ab61.png)

No network requests in the redirection, as per screenshots.

**Comment by D4v1dH03** [comment]
There is an "access link" when you created the link
See if you can see your IP and other info

**Comment by ryanbr** [comment]
I'm referring too the all the 3rd-party domains listed in the orginal request

**Comment by D4v1dH03** [comment]
<img width="888" alt="Screenshot 2022-01-02 at 15 18 00" src="https://user-images.githubusercontent.com/81270448/147892039-34f364ec-468b-44a6-ba28-11a185616786.png">


Wow, they got a lot info

**Comment by spirillen** [comment]
Wow @D4v1dH03 did you found all these in https://github.com/piperun/iploggerfilter/ :+1:  Could you do @shadowWhisper and me the favor to make a quick run over this list to see is you spot anything that you consider active? https://github.com/dns-test/iploggerfilter/blob/master/Test_results/inactive.txt

**Comment by D4v1dH03** [comment]
> Wow @D4v1dH03 did you found all these in https://github.com/piperun/iploggerfilter/ 👍 Could you do @ShadowWhisper and me the favor to make a quick run over this list to see is you spot anything that you consider active? https://github.com/dns-test/iploggerfilter/blob/master/Test_results/inactive.txt

Done.
Most of those "inactive" domains are NXDOMAIN, while some of them are globally censored with SERVFAIL (EDNS Error code 15, Censored) with all DNSes

I haven't found a single active domain in the inactive list

**Comment by iam-py-test** [comment]
> I'm not seeing any issues. Create a link via `https://grabify.link/` Which just forwards to link'd website.

That's a _very_ well known service for logging IPs. Often it's used on scammers/spammers, but anyone can abuse it

**Comment by spirillen** [comment]
> > Wow @D4v1dH03 did you found all these in https://github.com/piperun/iploggerfilter/ +1 Could you do @ShadowWhisper and me the favor to make a quick run over this list to see is you spot anything that you consider active? https://github.com/dns-test/iploggerfilter/blob/master/Test_results/inactive.txt
> 
> Done. Most of those "inactive" domains are NXDOMAIN, while some of them are globally censored with SERVFAIL (and with EDNS Error code 22, No reachable authority in case of Cloudflare) with all major DNSes (Cloudflare, Google, OpenDNS etc.)
> 
> I haven't found a single active domain in the inactive list
> 
> However in the "invalid" list I found some active ones!

Super thanks for the reply and follow up testing @D4v1dH03

For the invalid file is not that important as the active/and inactive are from a later run, the invalid file is from a initial test. but you for sure makes me ensuring they are i the active list :smile: 

> @iam-py-test wrote: That's a well known service for logging IPs

Where do you have this info from?

**Comment by iam-py-test** [comment]
> Where do you have this info from?

I have seen it on YouTube (and we know everything there is true) and some people I know have used it

**Comment by D4v1dH03** [comment]
I even become the victim once:
Someone sent me a "catpic" link on Discord and that guy then send me a pic with IP, referrer, geolocation and ISP etc. on it

**Comment by spirillen** [comment]
Damned solid and trustworthy source :laughing: 

cats, well I had a dog who loved cats (chowing) always funny to see the neighbors cats on visit :rofl: 

Non the less all ~500 are now on my wildcard, this proof seems rather good to me https://github.com/easylist/easylist/issues/10318#issuecomment-1003792379

And before you wake up and mentions bulk commits... Yes I do have a exception rule for that https://mypdns.org/mypdns/support/-/wikis/Contributing#bulk-commits

**Comment by D4v1dH03** [comment]
Wait. I reported a bunch of them and ended up only one domain and that domain's specific path being blocked. Sed

**Comment by gwarser** [comment]
@D4v1dH03  What you expect to be blocked here? You said this data is collected based on IP, so mere server redirection is needed to collect it. You will need to block all these domains to prevent this, but then how you will navigate to the target website? You should rather start using something like https://github.com/FastForwardTeam/FastForward and check if all these domains are handled by this add-on.

**Comment by D4v1dH03** [comment]
OK sorry for that. I will refrain from commenting more.
