### ISSUE TITLE
JioPages-Mobile Ads are not blocking on adult sites hdtube.porn / xhamster16.desi / hdpornmax.com / hdporn24.org

### ISSUE THREAD

**Issue by mediumkreation** [easylist/easylist#10321]
Migrating this issue submitted on IndianList [#4255](https://github.com/mediumkreation/IndianList/issues/4255)

- OS/version: Android
- Browser/version: JioPagesMobile
- Adblock Extension/version: 

### Other details:

Steps to reproduce:

    Launch browser -> Enable adbloker from menu
    load hdtube.porn / xhamster16.desi / hdpornmax.com / hdporn24.org

Actual Behavior: Ads are not blocking on adult sites
Expected Behavior: Ads should be blocking on adult sites

OS: Android 11
Tyep: JioPages(Mobile Browser)
Active Filter lists: Indian filter-lists
Location: India-> Karnataka
Screeshots:

**Comment by spirillen** [comment]
Hmm Where should those ads be? I can't see any ads.
