### ISSUE TITLE
`Brave Search` tracking param

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#10337]
https://search.brave.com/search?q=test&source=desktop

```
||search.brave.com^$removeparam=source
```

**Comment by Khrin** [comment]
What's unclear of "[We don't support removeparam in EL](https://github.com/easylist/easylist/issues/10288#issuecomment-1001775185)"?

**Comment by c2xusnpq6** [comment]
@DandelionSprout 👀

![image](https://user-images.githubusercontent.com/75058881/147795943-72581b03-51ee-4dcb-bf93-1e4eb3dd2b9d.png)

**Comment by c2xusnpq6** [comment]
@iam-py-test

**Comment by spirillen** [comment]
@c2xusnpq6 Don't know if you can use this to anything, but I have added it to my list here:
`https://mypdns.org/my-external-stuff/ublockorigin-rules/-/commit/3428f66efcb2799e122e4b38f6816f3580ec5232`

**Comment by iam-py-test** [comment]
I'm not sure why you are blocked. I'll ask
I have added that in https://github.com/DandelionSprout/adfilt/commit/e5139877f0147b8b296ff222ff19e7392cc6939f. Thanks for @ mentioning me.
As to both save time for the @Easylist team and for me, once I resolve the issue, please report issues at https://github.com/DandelionSprout/adfilt/discussions/163. You also can report issues at [a repo I control](https://github.com/iam-py-test/my_filters_001) until I resolve the block issue

**Comment by iam-py-test** [comment]
Wait, @c2xusnpq6 what action did you try?
