### ISSUE TITLE
theguardian.com cookie

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#10338]
### List the website(s) you're having issues:
`https://www.theguardian.com/technology/2016/oct/10/mafia-3-review-1960s-shooter-gameplay`

### What happens?
Cookie banner isn't blocked

### List Subscriptions you're using:
Easylist cookie

uBlock origin
### Your settings

- OS/version: Windows
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin

### Other details:
* Proposed filter:
`theguardian.com###sp_message_container_514494`

![image](https://user-images.githubusercontent.com/17685483/147807754-483a2c93-591f-4a95-87a1-1442c807a5e3.png)

**Comment by spirillen** [comment]
I like the text

It's your choice

OK then, where is the `hell no` choice? :smirk: :laughing:

**Comment by ryanbr** [comment]
Was previously adjusted due to https://github.com/easylist/easylist/issues/9786

But lets see how this goes. https://github.com/easylist/easylist/commit/9ffabacfb91d5304262162f46cfe1c99ee934921

**Comment by MasterKia** [comment]
> lets see how this goes. [9ffabac](https://github.com/easylist/easylist/commit/9ffabacfb91d5304262162f46cfe1c99ee934921)

Why is https://github.com/easylist/easylist/commit/9ffabacfb91d5304262162f46cfe1c99ee934921 reverted? (I can't find `theguardian.com` or `sp_message_` in the Easylist Cookie filterlist)

The cookie notice is back.

**Comment by MasterKia** [comment]
@ryanbr

**Comment by valynor** [comment]
![Screenshot 2022-05-28 at 19 47 55](https://user-images.githubusercontent.com/23384233/170837108-6a258f67-032c-41b7-828e-fc999d1a3cae.png)

theguardian.com has an annoying cookie banner on every page again (I block all cookies with uMatrix)

**Comment by MasterKia** [comment]
Maybe you should create a new issue since my latest ping was unnoticed.
