### ISSUE TITLE
merriam-webster.com

### ISSUE THREAD

**Issue by ponhon** [easylist/easylist#10331]
### List the website(s) you're having issues:

`https://www.merriam-webster.com/dictionary/dispermous`

### What happens?

![placeholders](https://user-images.githubusercontent.com/95446723/147701663-39228eca-929e-459b-a2ab-33faf934d727.png)
2 ad placeholders.

### List Subscriptions you're using:

![filters](https://user-images.githubusercontent.com/95446723/147701975-e5705e75-7cc0-4eab-b236-f1136cfc7e76.png)

### Your settings

uBlock Origin Medium Mode.
- OS/version: Chrome OS Version 96.0.4664.111
- Browser/version: Google Chrome Version 96.0.4664.111
- Adblock Extension/version: uBlock Origin 1.39.2

### Other details:

`merriam-webster.com##[class*="mt-"]` removes them.

**Comment by iam-py-test** [comment]
Already fixed in https://github.com/easylist/easylist/commit/8cc6fe98784a5e1fa73cdc6fb8fb8ad858334b01
