### ISSUE TITLE
chollometro.com

### ISSUE THREAD

**Issue by UUNKK** [easylist/easylist#10336]
### List the website(s) you're having issues:

`https://www.chollometro.com`
and possible same issues with others websites of group `https://www.pepper.com`

### What happens?

Not possible click at Regístrate / Inicio sesión for login/logout and button + Comparte not function

### List Subscriptions you're using:

Problem only occur when use/activate Fanboy’s Annoyance or EasyList Cookie.

Advise: This not occur with AdGuard Annoyances and uBlock filters – Annoyances

### Your settings

Default lists of Ublock Origin

- OS/version: Windows 10 Pro X64
- Browser/version: Opera Browser 82.0.4227.43
- Adblock Extension/version:  Ublock Origin 1.39.2 for Chrome

### Other details:

Tested various lists and variants and the problem i know it's related when activate/use this lists: Fanboy’s Annoyance or EasyList Cookie inclusive.

**Comment by ryanbr** [comment]
See if this helps.
