### ISSUE TITLE
Add a category in Fanboy's Annoyance to block content farms

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylist#10346]
Hello!
I think it is necessary to add a category to Fanboy's Annoyance to intercept content farms. adguard is planning to do so:
https://github.com/AdguardTeam/AdguardFilters/pull/104557#issuecomment-1003364521
Content farms usually have no useful content and can be a waste of time. This fits the definition of "annoying".
Thanks!

**Comment by ryanbr** [comment]
Not blindly imported various urls. Any english sites using these, and samples. Otherwise it would be more suitable as a regional list.

**Comment by ryanbr** [comment]
There would be too many "judgement calls", and blocking such sites would cause many reports when a user visits. We'll stay out of this
