### ISSUE TITLE
EasyPrivacy: Way to relax wasm-blocking on github.io?

### ISSUE THREAD

**Issue by hein09** [easylist/easylist#1034]
This rule is quite fierce:
```
/.*(\/proxy|\.wasm|\.wsm|\.wa)$/$websocket,xmlhttprequest,domain=github.io|rawgit.com|reactor.cc|sickrage.ca|streamplay.to|tubetitties.com|vidfile.net
```
I don't know how all this adblocking stuff works, but shouldn't there be a way to focus on blocking loading remote code?
If it's not possible, maybe you can at least add .js to the regex, so it fails more obviously to the user ;)

**Comment by ryanbr** [comment]
Because every other week Coinminers are hosting on github. I've atleast reported this to github 4-5 times already.

**Comment by hein09** [comment]
Sure, I know about this.
but isn't it possible to block only remote code, while the GitHub page you're currently visiting stays whitelisted?
This rule surely is no long-term solution, for me it makes this ruleset unusable...

**Comment by hein09** [comment]
...and for the user it's rather confusing that one type of code may be executed while the other may not. What's the argument for allowing .js? Is there anything in place that distinguishes between good and bad? Don't the miners have a fallback to asm.js?

**Comment by KnicKnic** [comment]
@sgsaenger the block has been removed, see commit https://github.com/easylist/easylist/commit/5e6a19ccb057f452dfeb825299d23feb64d102ae

**Comment by sgsaenger** [comment]
Thanks for your efforts!
