### ISSUE TITLE
Singaporean MediaCorp tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#10382]
```
||rt.mediacorp.sg/ocpageanalytics^
||rt.mediacorp.sg/oc8worldarticle/analytics^
```

![Screenshot.png](https://user-images.githubusercontent.com/75058881/148146017-be9367de-fa60-4fc3-b28d-b823b17a3381.png)

![Screenshot.png](https://user-images.githubusercontent.com/75058881/148146029-3407c9bd-7226-4011-b313-240f27f9fc2e.png)

![Screenshot.png](https://user-images.githubusercontent.com/75058881/148146037-7dabc9c8-8ef6-483e-84de-67e9919e3bd5.png)

From `8world` app

**Comment by c2xusnpq6** [comment]
![Screenshot.png](https://user-images.githubusercontent.com/75058881/148146673-203734d2-fc18-4ed9-aee2-341b5a1d5118.png)

![Screenshot.png](https://user-images.githubusercontent.com/75058881/148146683-83f5904a-333e-4514-8131-92493bbd0e0a.png)

**Comment by c2xusnpq6** [comment]
@iam-py-test @DandelionSprout `You can't perform that action at this time.`

`(English) List entry submission` --> and then --> `You can't perform that action at this time.`

**Comment by iam-py-test** [comment]
@c2xusnpq6 you have been banned from the adflit repo.
Only @DandelionSprout can unban you and he has so far refused.

**Comment by c2xusnpq6** [comment]
> @c2xusnpq6 you have been banned from the adflit repo.
> Only @DandelionSprout can unban you and he has so far refused. 

🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔

**Comment by c2xusnpq6** [comment]
> @c2xusnpq6 you have been banned from the adflit repo.
> Only @DandelionSprout can unban you and he has so far refused. 

But I didn't even post anything on his repository yet...???

**Comment by iam-py-test** [comment]
Take it up with Imre, I don't have the ability to unblock you and I wasn't the one who made that decision. 
However, I believe it was partly because of `https://github.com/AdguardTeam/FiltersRegistry/issues/457`

**Comment by c2xusnpq6** [comment]
> Take it up with Imre, I don't have the ability to unblock you and I wasn't the one who made that decision. 
> However, I believe it was partly because of `https://github.com/AdguardTeam/FiltersRegistry/issues/457`

Oh... He's the guy! Haha!
