### ISSUE TITLE
gumtree.com.au

### ISSUE THREAD

**Issue by jrbarrick** [easylist/easylist#10389]
### List the website(s) you're having issues:
`gumtree.com.au`

### What happens?
After doing a search, the top menu bar and search box are missing on the results page

### List Subscriptions you're using:

EasyList -> Specific element hiding rules

### Other details:
This rule seems to be causing the issue:
`gumtree.com.au##.header--is-new-sticky-behaviour`

I replaced with this rule and it seems to fix it, though there may be a better rule:
`gumtree.com.au##.header__leaderboard-ad--sticky-visible.header__leaderboard-ad--sticky-top.header__leaderboard-ad`

**Comment by TomW1605** [comment]
how did you replace the rule with the working one?

**Comment by jrbarrick** [comment]
Just checked My Filters again, this is what I've got for gumtree now. First line disables the broken rule, other two were the rules I needed to get everything blocked again:
`gumtree.com.au#@#.header--is-new-sticky-behaviour
gumtree.com.au##.header__leaderboard-ad--sticky-visible.header__leaderboard-ad--sticky-top.header__leaderboard-ad
gumtree.com.au##.view-item-page__leaderboard-wrapper-sticky`
