### ISSUE TITLE
n.rivals.com  ad placeholders

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#10401]
### List the website(s) you're having issues:

```
https://n.rivals.com/
```

### What happens?

![image](https://user-images.githubusercontent.com/84513173/148402840-2b67bf2d-f228-4bb1-8672-86ad9958bf98.png)

![image](https://user-images.githubusercontent.com/84513173/148403071-f78e9b50-2e5d-4e80-9688-aa2802044d69.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 95.0.2  (64-bit)
- Adblock Extension/version: uBlock Origin 1.40.2

</details>

### Other details:

```
n.rivals.com##.lrec-container
```
```
n.rivals.com##.horizontal-ad-container
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/55a2ea0631f376cc62895ba7b7abb0e5d3300f53
