### ISSUE TITLE
[Urgent] Remove gigafyde.dev from easyprivacy_trackingservers.txt

### ISSUE THREAD

**Issue by GigaFyde** [easylist/easylist#10414]
@Khrin Hi, please remove my domain name from that list.

I don't mind umami being added to it.
But I do take issue with just throwing the root domain onto the lists with without any care in the world.

Kind regards,
GigaFyde

**Comment by GigaFyde** [comment]
The inclusion of my domain to that list has been seriously hampering ongoing development.

**Comment by GigaFyde** [comment]
@ryanbr please have a look at this as well

**Comment by GigaFyde** [comment]
Please advice that I have now removed the script entirely.
So I kindly request that my domain be removed from the lists

**Comment by GigaFyde** [comment]
@monzta please have a look if you can as well

**Comment by Khrin** [comment]
Ok, it's removed now.

**Comment by GigaFyde** [comment]
Much appreciated, thank you very much.

Have a great day!
