### ISSUE TITLE
howtogeek.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#10420]
### List the website(s) you're having issues:

`howtogeek.com`
*specific example:* `https://www.howtogeek.com/775869/critical-stats-every-pc-gamer-should-monitor/`

### What happens?

Between the text of the article are three grey boxes with the text `advertisement`.
To block those I propose the rule:

```
howtogeek.com##[data-nosnippet="data-nosnippet"]:has(.future_inline_clone_target)
```

### List Subscriptions you're using:

- EasyList
- EasyPrivacy
- EasyList Dutch
- uBlock filters
- uBlock unbreak
- uBlock Privacy

### Your settings

<summary>
<details>

```
uBlock Origin: 1.39.2
Chromium: 96
filterset (summary): 
  network: 67246
  cosmetic: 42313
  scriptlet: 16412
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/r/fanboy-complete.txt: 92378-93, 6h.38m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 1926-3, 6h.38m
  default: 
    ublock-filters: 30162-208, 6h.29m
    ublock-unbreak: 1705-47, 6h.27m
filterset (user): [array of 147 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  firewallPaneMinimized: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#4242CA 00001
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  uiFlavor: classic
  updateAssetBypassBrowserCache: true
supportStats: 
  launchToReadiness: 21998
  launchFromSelfie: false

```
</details>
</summary>

- OS/version: Windows 10, 21H2
- Browser/version:  MS Edge v96
- Adblock Extension/version: uBlock 1.39.2

### Other details:

**See https://github.com/uBlockOrigin/uAssets/issues/11229  for more information.**

**Comment by THEtomaso** [comment]
https://github.com/easylist/easylist/blob/6bcec836eb8e7d3802833886f1d150d0e0b731a3/fanboy-addon/fanboy_newsletter_specific_hide.txt#L1014

**Comment by JohnyP36** [comment]
> https://github.com/easylist/easylist/blob/6bcec836eb8e7d3802833886f1d150d0e0b731a3/fanboy-addon/fanboy_newsletter_specific_hide.txt#L1014

I don't know how long that rule is in there. Otherwise, it must have been an error on my site loading the filterlist correctly when the site was loaded.

**Comment by THEtomaso** [comment]
Nevertheless, it's for blocking their newsletter nag.
Since it now also works for blocking ad boxes, it should be moved to EasyList.
..or at least some version of it, like the one that you proposed.

**Comment by ryanbr** [comment]
Looks fine here

**Comment by SeriousHoax** [comment]
@ryanbr Can you check again? I'm also seeing the advertisement text. 
Example page: `https://www.howtogeek.com/783377/dont-worry-microsoft-already-tried-to-buy-nintendo-and-failed/`
![image](https://user-images.githubusercontent.com/29574622/152053405-2e419511-51a1-42ae-be11-06da056b405c.png)

**Comment by JohnyP36** [comment]
Yes, I'm seeing it too.

**Comment by THEtomaso** [comment]
@SeriousHoax:
ryanbr doesn't respond to pings.
You'll have to open a new issue.
