### ISSUE TITLE
Google Ads loading from www.google.com/afs/ads?... 

### ISSUE THREAD

**Issue by rahilpathan** [easylist/easylist#1043]
### List the website(s) you're having issues:
Sample1:
https://www.bestbuy.com/site/google-pixel-2-4g-lte-with-128gb-memory-cell-phone-clearly-white-verizon/6099985.p?skuId=6099985

### What happens?
![image](https://user-images.githubusercontent.com/20379786/38761485-1e07bffa-3f51-11e8-8433-660f8c8026bf.png)

Google ads started appearing all of sudden.

### List Subscriptions you're using:

- EASYLIST
- EASYPRIVACY
- FANBOY'S ENHANCED TRACKING LIST

### Your settings
Default uBlock Settings

- OS/version: Win 10
- Browser/version: Google Chrome version 65.0.3325.181 (Official Build) (64-bit)
- Adblock Extension/verson:  uBlock Origin 1.15.24

**Comment by monzta** [comment]
I was able to reproduce this some days ago. When I test it now with updated lists, it's blocked. 

Can you confirm it?

**Comment by rahilpathan** [comment]
It has something to do with the browser, In my other device with the same setting and same browser, Ad was getting blocked. So, I reinstalled the browser in this device and it got fixed. 

I suggest to close this thread.

Thank you.
Rahil

**Comment by monzta** [comment]
Ok, thanks.
