### ISSUE TITLE
prowritingaid.com

### ISSUE THREAD

**Issue by ttypow** [easylist/easylist#10446]
### List the website(s) you're having issues:

`https://prowritingaid.com/art/2290/em-dash.aspx`

### What happens?

Pop-up.

### List Subscriptions you're using:

<details>
<img src="https://user-images.githubusercontent.com/97240061/148886184-7ac8a883-9235-4199-9156-c53b844ff5ea.png">
</details>

### Your settings

- OS/version: Chrome OS Version 96.0.4664.111
- Browser/version: Google Chrome Version 96.0.4664.111
- Adblock Extension/version: uBlock Origin 1.40.4

### Other details:

![screenshot](https://user-images.githubusercontent.com/97240061/148885619-ea723c05-2302-4ca8-8f00-077353c8c97c.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/0af5026a7b82b21ab3336e82aa254ff1e1400a3f
