### ISSUE TITLE
Comicbook.com Videos Do Not Play

### ISSUE THREAD

**Issue by abadore** [easylist/easylist#10456]
### List the website(s) you're having issues:

https://comicbook.com/anime/news/naruto-boruto-rogue-samurai-anime/

### What happens?

This commit https://github.com/easylist/easylist/commit/e85455471f10682af3039f502028ed1147f6e87e seems to have introduced changes that broke video playback on this site. I can no longer watch video content with ad block on.

### Your settings

- OS/version: Chrome Mac OS
- Browser/version: Version 96.0.4664.110 (Official Build) (x86_64)
- Adblock Extension/version:  3.11.4

### Other details:

The area where the video would appear is missing now. If I disable ad block it appears.

**Comment by ryanbr** [comment]
Considered inadvert video advertising. The video content is literally unrelated to the page content.

**Comment by abadore** [comment]
Guess I'll need to stop using this list with this site then.

**Comment by abadore** [comment]
> Considered inadvert video advertising. The video content is literally unrelated to the page content.

that was not the case with the link in this ticket.

**Comment by stephenhawk8054** [comment]
> > Considered inadvert video advertising. The video content is literally unrelated to the page content.
> 
> that was not the case with the link in this ticket.

I think it was? The video is in the article, but its content is about Attack on Titan while the article is about Naruto?

**Comment by abadore** [comment]
> > > Considered inadvert video advertising. The video content is literally unrelated to the page content.
> > 
> > 
> > that was not the case with the link in this ticket.
> 
> I think it was? The video is in the article, but its content is about Attack on Titan while the article is about Naruto?

Yeah, I guess it was their blog video. Still isn't that legit content? This seems like editorializing to me.

**Comment by stephenhawk8054** [comment]
> > > > Considered inadvert video advertising. The video content is literally unrelated to the page content.
> > > 
> > > 
> > > that was not the case with the link in this ticket.
> > 
> > 
> > I think it was? The video is in the article, but its content is about Attack on Titan while the article is about Naruto?
> 
> Yeah, I guess it was their blog video. Still isn't that legit content? This seems like editorializing to me.

I guess what EasyList means is that if it's "in" the article (from the title to the final words of it -  in this case the `What do you think` part), the content should be related to the article to be considered legit content. Or else they should put it outside the scope of the article, like the spotify link below it. That's my guess.
