### ISSUE TITLE
Recent rule update for www.hltv.org breaks much of the site

### ISSUE THREAD

**Issue by spand** [easylist/easylist#1046]
Recent update in 1b31781788f863a841ed97c9857bb5c11848ea56 breaks much of the site.

### List the website(s) you're having issues:

```
www.hltv.org
```

### What happens?

Almost all ajax functionality is broken. Forum posting, editing, user settings etc.
I think most of these live on the main domain so this new rule is way too broad.

**Comment by WojciechBoczarski** [comment]
Read what it says on top. Constant abuse of bypassing adblock functionality. 
Block  Deserved.

**Comment by MalalaCS** [comment]
I had uBlock and never saw any adverts, only empty boxes from where the ad would be which I blocked using resource picker, this move was retarded, now I've disabled Easylist

**Comment by spand** [comment]
It got a bit better in b7a82796dd4ad235c83dadf2455887b9bed4e6f6 but stuff is still broken:
forum post edit
search in the top menu bar
search for player, team and event in filter sidebar on ie. `https://www.hltv.org/results`
embedded streams (twitch and such) dont work

Is this really the best strategy ? Seems like this will be perpetually broken.

**Comment by spand** [comment]
Note that this is in AdBlock. uBlock seems to be different (both with updated lists)

**Comment by ryanbr** [comment]
Most of this is resolved now.

**Comment by perlambaek** [comment]
@ryanbr there is still a lot of broken functionality, I am the main programmer of the site, can we come to an agreement? If you block geo*.hltv.org, I'll make sure we keep serving our ad-json from there, and then you can remove all other blocks, and we both get to go on with making a good product for our respective users? I'll make sure no attempts to dodge this will happen going forward.

**Comment by ryanbr** [comment]
Okay, We've reverted it. Tho if do get any user reports of ads slipping back in. We'll re-instate the filters.

https://github.com/easylist/easylist/commit/4090e4932384d39b8e5a8bb41ac77f82826154a8
