### ISSUE TITLE
meagup.net - "DISABLE ADBLOCK"

### ISSUE THREAD

**Issue by vertigo220** [easylist/easylist#10485]
### List the website(s) you're having issues:

`megaup.net`

### What happens?

Most recently used within the past week without major issues, and would previously only get this message very rarely, which was always fixed simply be reloading. Now the message is constant, only way to get rid of it and access the download is to disable EasyList in uBO.

### List Subscriptions you're using:

Multiple but disabling EL fixes the issue, reenabling causes it to come back.

### Your settings

- OS/version: W10 19043.1415
- Browser/version: Vivaldi 5.0.2497.35
- Adblock Extension/version: uBO 1.40.4

### Other details:

`https://megaup.net/themes/flow/frontend_assets/images/adblock/primary.png`

**Comment by Khrin** [comment]
No chances to get this fixed by EasyList.
