### ISSUE TITLE
Anti-adblock on `keybr.com/`

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#10484]
### List the website(s) you're having issues:

`https://www.keybr.com/`

### What happens?

Anti-adblock on left and top of page.

### List Subscriptions you're using:

![filters 10 Jan](https://user-images.githubusercontent.com/11689349/149552401-66f4b7d4-00ae-41b7-83aa-4fe31869d73b.jpg)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Not fixed in EL
