### ISSUE TITLE
Filter blocking voting/verification and autocomplete function at torrentz2.eu again

### ISSUE THREAD

**Issue by billyjeanis** [easylist/easylist#1048]
This issue https://github.com/easylist/easylist/issues/936 is appearing again.
The issue is not fixed. I will write again the same as in https://github.com/easylist/easylist/issues/936

the filter that is causing the problem is :
||torrentz2.eu^$xmlhttprequest

Is blocking all xmlhttprequest requests !
example of url
https://torrentz2.eu/930854178824ef9a19222fb82dc919810feb2fd1
You cannot verify torrent by pressing the
    "Verify as a good torrent"
button or any other button that has to do with verification.
This filter is also blocking the "autocomplete" function in search box!
Cannot find any logical reason why you are blocking all xmlhttprequest functions in this page. Please advice.

**Comment by ryanbr** [comment]
Was removed because they used our whitelists to serve ads. Not fixing this.

**Comment by billyjeanis** [comment]
The ads are still there so the whitelists are not used anymore please add again
@@||torrentz2.eu/report_$~third-party,xmlhttprequest
@@||torrentz2.eu/suggestions/$~third-party,xmlhttprequest
in the list so the site will function properly.

**Comment by billyjeanis** [comment]
I see that my attempt to fix this problem resulted in the issues https://github.com/easylist/easylist/issues/1058
https://github.com/easylist/easylist/issues/1061 to be locked as spam.

As I said in previous posts I changed the ad at the page so it will not use your old whitelist, 
```
@@||torrentz2.eu/report_$~third-party,xmlhttprequest
@@||torrentz2.eu/suggestions/$~third-party,xmlhttprequest
```
proof of that is that you can see the one line text ad for the SpyOFF-VPN, example page: https://torrentz2.eu/f07e0b0584745b7bcb35e98097488d34e68623d0 . At the moment
you can remove all the filters that have to do with torrentz2.eu domain and
the pages will appear the same but will have a working autocomplete and voting
functionality. I have already promised that I'll not use your whitelist again to
serve ads what else should I do to fix this issue?

**Comment by ryanbr** [comment]
Okay, I've removed the filter. If we get any reports of Adblocking countering or revolving adservers, we'll re-implement these filters.

**Comment by billyjeanis** [comment]
I don't understand what exactly means "Adblocking countering or revolving adservers". I have promise not to use your whitelists but I want to find a way load this one line VPN ad again, will you destroy the autocomplete and voting function if I do this ?
