### ISSUE TITLE
katu.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#10495]
### List the website(s) you're having issues:
`https://katu.com/news/local/tsunami-advisory-issued-for-west-coast-after-undersea-volcanic-eruption-near-tonga`

### What happens?
Ads placeholders

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 96.0
- Adblock Extension/version: ublock 1.40.8

### Other details:
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/149663028-6bf266cf-a7a2-49e6-bd8f-f8cab0b1b8d3.png)

</details>

Proposed filters:

```
##[class^="index-module_adBeforeContent"]
##[class^="index-module_adAfterContent"]
##[id^="nativeAdContainer"]
```

**Comment by ryanbr** [comment]
Its fine.

**Comment by stephenhawk8054** [comment]
Just to clarify, you mean it's cannot be reproduced or it won't be fixed?

**Comment by ryanbr** [comment]
both
