### ISSUE TITLE
boohoo.com -- cookie background overlay + can't scroll

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#10496]
### List the website(s) you're having issues:

```
https://www.boohoo.com/
```

### What happens?

Cookie dialog backgound overlay and can't scroll.

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 96.0.1  (64-bit)
- Adblock Extension/version: uBlock Origin 1.40.8

</details>

### Other details:

Fix:

```
boohoo.com##html[class*="cookies-visible"] > body::before
boohoo.com##body:style(overflow: auto !important)
```

or

```
boohoo.com##+js(rc, header-cookies-visible|header-gdrp-cookies-visible|dialog-opened, html, stay)
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/bbab48e85df27e3fce82c53aff54080ff4d7b34e
