### ISSUE TITLE
HLTV.org doesnt work anymore

### ISSUE THREAD

**Issue by nannak88** [easylist/easylist#1050]
### List the website(s) you're having issues:

http://www.hltv.org

### What happens?

NOTHING! 

After the recent update the site have lost functionality. 

Streams doesnt load, search feature dead, comments bugs. 

Now I have to disable adblock in order to use the site. Please fix Dreamhack just started!

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/issues/1046
