### ISSUE TITLE
Intersport.no - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR] 

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#10513]
### Affected site:
`https://www.intersport.no/`

### Issue:
Broken site / no scrollbar.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rule:
`/cookiewall?`

### Possible fix:
```
- /cookiewall?
+ /cookiewall?$domain=~intersport.no
```

### Temporary fix:
`@@||intersport.no/cookiewall?`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.4.4 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by DandelionSprout** [comment]
Out of curiosity: Why don't do you add screenshots to any of the reports you submit? They are pretty convenient to include nevertheless, especially since I don't use EasyList Cookie List on the regular.

**Comment by THEtomaso** [comment]
> Why don't do you add screenshots to any of the reports you submit?

That's not entirely true.
In this case (like most others), I really don't see what possible use anyone could have from a screenshot.
It would simply show a missing scrollbar, like described.
Also, including screenshots for every single report means that I would have to spend/waste even more time with them, although they already include far more details than an average one.
If I feel that something can be gained from a screenshot (like when site accounts are needed for reproduction), I DO include them!

BTW; As usual, I only ping you for Nordic site issues, in order for you to add the necessary fixes to your list, awaiting potential fixes in the actual problem filter (which is more of 50/50 chance here).

**Comment by DandelionSprout** [comment]
>It would simply show a missing scrollbar, like described.

Ah, that explains it.

>BTW; As usual, I only ping you for Nordic site issues, in order for you to add the necessary fixes to your list, awaiting potential fixes in the actual problem filter (which is more of a 50/50 chance here).

I've been working very extensively on AdGuard Filters in the past week, so Nordic Filters is a less urgent priority at the moment. 😅

**Comment by krystian3w** [comment]
My issue about allegro also don't have photo, I wrote where of page is gallery so anybody can found glitched section.

**Comment by THEtomaso** [comment]
> https://github.com/DandelionSprout/adfilt/commit/9c6788c42a4e0e96bbff90e25490e9abe830b6c4

`.*` doesn't appear to be necessary in this case.
Before filing my report, I actually checked all of Intersport's TLDs, and found that the `.no` domain was the only one that is affected.
..but OTOH, `.*` doesn't hurt either, of course. :)

**Comment by DandelionSprout** [comment]
Ah, okay. Good to know.
