### ISSUE TITLE
allegro.pl [breakage]

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#10514]
### List the website(s) you're having issues: [](https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/2908)

`https://allegro.pl/oferta/vitakraft-szalka-poesie-dorsz-makaron-pomidor-85g-8532588503`

### What happens?

* Gallery into offers is blank.

* Gallery is on left under header with product name, after click page is blank and we must refresh page.

### List Subscriptions you're using:

EasyList Cookie

### Your settings

- OS/version: Windows 10 Pro (any version is good to reproduce)
- Browser/version: FX 96.0.1
- Adblock Extension/version: uBo 1.40.8

### Other details:

Bad works now:

https://github.com/easylist/easylist/blob/9e6e1da0031861ae9a6313007adcb37af05a1933/easylist_cookie/easylist_cookie_specific_uBO.txt#L34

If we still hide GDPR pop-up then we can test:

`allegro.pl##body:style(overflow: auto !important;)`

fyi: @DandelionSprout / @Yuki2718 / @peace2000

**Comment by ryanbr** [comment]
Looks fine here, the Gallery works as intended. @krystian3w

**Comment by krystian3w** [comment]
You should open gallery to see bigger photos then page are blank, I can record mp4 later.

**Comment by bremich** [comment]
@ryanbr This seems to result from a conflict with the AdGuard Annoyances list, which is also one of the lists suggested by uBO. 

Their filters work well on their own, but in combination with EasyList Cookie the website breaks. 
They use the following to get rid of the cookie message: 

```
allegro.pl#$#body { overflow-y: auto !important; }
allegro.pl#$#div[data-prototype-id="allegro.gdpr.consents"] { display: none !important; }
```

**Comment by krystian3w** [comment]
@AdamWr try use `visible` instead `auto` or `scroll` on body.

**Comment by ryanbr** [comment]
When I test, I don't use Adguard Annoyances, but happy too work with them to adjust either there filter or mine.

**Comment by krystian3w** [comment]
Maybe @Yuki2718 generate 2 PR to fix problem in both lists.

**Comment by AdamWr** [comment]
It seems that this issue occurs only in Firefox if `EasyList Cookie List` + `AdGuard Annoyances filter`/`Polish GDPR-Cookies Filters` are enabled (I can't reproduce it in Chrome).

>try use visible / initial/ unset / revert instead auto or scroll on body.

It rather doesn't fix the problem.

In AdGuard Annoyances filter we usually adds style `overflow` to element which has `overflow` added by website.
On `allegro.pl` it's used on class `meqh_en` which is added to `body` tag, so in this case, I would prefer to not change this rule.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/150746611-5a8d4a39-b335-4cd9-a11a-af21155243ef.png)

</details>

**Comment by krystian3w** [comment]
For uBlock Origin safe is change to `body { overflow: visible !important }` so AG addon may have but with `tabs.insertCSS()`(¿?).

I can try in Polish Rodo-GDPR remove repair on only `-y` direction, but I don't like create PR in EC if this must wait in quarantine 2 months.
