### ISSUE TITLE
reginamaria.ro login issue

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#10568]
### List the website(s) you're having issues:
`https://contulmeu.reginamaria.ro/`

### What happens?
When I open the link from above, the page has an infinite loading and can't reach the login page.

### List Subscriptions you're using:
Anti-Facebook

### Your settings
only uBlock, default settings

- OS/version: Windows 10
- Browser/version: Firefox 96.0.1
- Adblock Extension/version: Ublock 1.40.8

**Comment by Khrin** [comment]
Please ask here https://github.com/ryanbr/fanboy-adblock for the Anti Facebook list.
