### ISSUE TITLE
Instagram cookie consent popup (EU and Switzerland only)

### ISSUE THREAD

**Issue by D4v1dH03** [easylist/easylist#10567]
### List the website(s) you're having issues:
`https://www.instagram.com/`

### What happens?
When user's IP is detected to be from EU countries or Switzerland, it would show the undismissable cookie consent pop up which no matter how the user chooses to "opt-out", he/she is still subjected to first party tracking by Meta (previously Facebook)

Proof: this network request
```
POST https://graphql.instagram.com/graphql/

Payload (form data, encoded): doc_id=[REMOVED]&variables=%7B%22ig_did%22%3A%[REMOVED]%22%2C%22first_party_tracking_opt_in%22%3Atrue%2C%22third_party_tracking_opt_in%22%3Afalse%2C%22input%22%3A%7B%22client_mutation_id%22%3A0%7D%7D

Response: {"data":{"ig_browser_terminal_consent_mutation":{"success":true}},"extensions":{"is_final":true}}
```

### List Subscriptions you're using:
EasyList
EasyPrivacy
Fanboy Annoyances
uBlock Annoyances
+ All uBlock origin default lists

### Your settings

- OS/version: macOS 12.1
- Browser/version: Firefox Nightly (2022-01-23)
- Adblock Extension/version: uBlock Origin 1.40.9b2

### Other details:

This is geo-specific. You will need an EU or Switzerland VPN, or physically living in the EU or Switzerland to reproduce this.

<img width="544" alt="Screen Shot 2022-01-22 at 8 56 16 PM" src="https://user-images.githubusercontent.com/81270448/150665527-868b2a0a-ccbf-474c-9c9d-add45c46380a.png">

**Comment by D4v1dH03** [comment]
There have been reports before in #8824 but the original report was lacking any details other than an URL
This is not a "banner" as the original issue author in that issue referenced. It is now an intrusive and un-dismissable popup which forces users to opt into Meta's own tracking system.

**Comment by krystian3w** [comment]
Possible safe convert to:

`||graphql.instagram.com/graphql/`

❓

**Comment by ryanbr** [comment]
From a EU ip, I get this. 

![insta](https://user-images.githubusercontent.com/1659004/150715408-a68b3c8b-1ab8-450d-8a74-5f282b9feec1.png)

`www.instagram.com##._4Yzd2.Yx5HN.RnEpo`  But not sure if it causes issues.

**Comment by krystian3w** [comment]
`.Yx5HN.RnEpo` or `.RnEpo` mean "generic pop-up" in Instagram React template so must be used with `._4Yzd2`.
