### ISSUE TITLE
onaplatterofgold.com

### ISSUE THREAD

**Issue by SMed79** [easylist/easylist#1056]
**List the website(s) you're having issues:**

http\://www.onaplatterofgold.com/
https\://nairatips.com/
http\://swooptheworld.com/

**What happens?**

bluehost affiliat iframe

**filter**

```
||bluehost.com/web-hosting/domaincheckapi/?affiliate=
```

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/04415a1bd5805cf1835985c21af32c736a47bcff
