### ISSUE TITLE
Blaklader sites - Broken (EasyList Cookie List / EasyPrivacy / Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#10565]
### Issue 1:
Blank pages!

**Affected sites:**
```
https://www.blaklader.at/
https://www.blaklader.be/
https://www.blaklader.ca/
https://www.blaklader.com/
https://www.blaklader.cz/
https://www.blaklader.de/
https://www.blaklader.dk/
https://www.blaklader.ee/
https://www.blaklader.es/
https://www.blaklader.fi/
https://www.blaklader.fr/
https://www.blaklader.ie/
https://www.blaklader.it/
https://www.blaklader.nl/
https://www.blaklader.no/
https://www.blaklader.pl/
https://www.blaklader.se/
https://www.blaklader.uk/
```

**Examples:**
```
https://www.blaklader.ca/en/
https://www.blaklader.com/en/
https://portal.blaklader.dk/en?showLogin=true
https://portal.blaklader.no/nb?showLogin=true
```

**Screenshots:**

Not needed, as the problem is obvious.

**Problem filter / rule:**

* Fanboy's Annoyance List
`###to-the-top`

**Possible fix (ABP-compatible):**
`blaklader.at,blaklader.be,blaklader.ca,blaklader.com,blaklader.cz,blaklader.de,blaklader.dk,blaklader.ee,blaklader.es,blaklader.fi,blaklader.fr,blaklader.ie,blaklader.it,blaklader.nl,blaklader.no,blaklader.pl,blaklader.se,blaklader.uk#@##to-the-top`

--

### Issue 2:
Some elements are hidden, until the cookie terms have been accepted.
However, the cookie terms can't be accepted, because they're blocked!

**Affected sites:**
```
https://www.blaklader.at/
https://www.blaklader.be/
https://www.blaklader.ca/
https://www.blaklader.com/
https://www.blaklader.cz/
https://www.blaklader.de/
https://www.blaklader.dk/
https://www.blaklader.ee/
https://www.blaklader.es/
https://www.blaklader.fi/
https://www.blaklader.fr/
https://www.blaklader.ie/
https://www.blaklader.it/
https://www.blaklader.nl/
https://www.blaklader.no/
https://www.blaklader.pl/
https://www.blaklader.se/
https://www.blaklader.uk/
```

**Examples:**
```
https://www.blaklader.ca/en/
https://www.blaklader.com/en/
```

**Screenshot:**

![filterissue-blaklader](https://user-images.githubusercontent.com/9382674/150605300-77fa3bad-253d-4261-9a4e-a47e29b5f1a9.jpg)

**Problem filters / rules:**

* EasyList Cookie List / Fanboy's Annoyance List
`##.optanon-show-settings`
`###onetrust-banner-sdk`
`###onetrust-consent-sdk`

* EasyPrivacy
`/gtm.js`
`||googletagmanager.com^`

**Possible fix (ABP-compatible):**
```
blaklader.at,blaklader.be,blaklader.ca,blaklader.com,blaklader.cz,blaklader.de,blaklader.dk,blaklader.ee,blaklader.es,blaklader.fi,blaklader.fr,blaklader.ie,blaklader.it,blaklader.nl,blaklader.no,blaklader.pl,blaklader.se,blaklader.uk#@#.optanon-show-settings
blaklader.at,blaklader.be,blaklader.ca,blaklader.com,blaklader.cz,blaklader.de,blaklader.dk,blaklader.ee,blaklader.es,blaklader.fi,blaklader.fr,blaklader.ie,blaklader.it,blaklader.nl,blaklader.no,blaklader.pl,blaklader.se,blaklader.uk#@##onetrust-banner-sdk
blaklader.at,blaklader.be,blaklader.ca,blaklader.com,blaklader.cz,blaklader.de,blaklader.dk,blaklader.ee,blaklader.es,blaklader.fi,blaklader.fr,blaklader.ie,blaklader.it,blaklader.nl,blaklader.no,blaklader.pl,blaklader.se,blaklader.uk#@##onetrust-consent-sdk
@@||googletagmanager.com/gtm.js$domain=blaklader.at|blaklader.be|blaklader.ca|blaklader.com|blaklader.cz|blaklader.de|blaklader.dk|blaklader.ee|blaklader.es|blaklader.fi|blaklader.fr|blaklader.ie|blaklader.it|blaklader.nl|blaklader.no|blaklader.pl|blaklader.se|blaklader.uk
```
**Note:**

The issue seems to be partially browser-dependent.
More info here:
https://github.com/uBlockOrigin/uAssets/issues/11422#issuecomment-1018916867

**Other problem filters:**

* AdGuard Annoyances filter / AdGuard Tracking Protection filter https://github.com/AdguardTeam/AdguardFilters/issues/107716/
`###onetrust-consent-sdk`
`||cookielaw.org^$third-party`
`||googletagmanager.com/gtm.js$third-party`

* hpHosts - Ad and Tracking servers only _(DISCONTINUED)_
`googletagmanager.com`
`www.googletagmanager.com`

* I don't care about cookies (@kiboke)
`~msn.com,~eurogamer.net,~rtlxl.nl,~zdf.de,~crfashionbook.com,~rockpapershotgun.com,~zdnet.com,~mensjournal.com,~cbsnews.com,~cbslocal.com,~assetstore.unity.com,~gmx.com,~gmx.es,~gmx.fr,~gmx.co.uk,~mail.com,~kruidvat.nl,~kruidvat.be,~trekpleister.nl,~tvn24.pl,~popsugar.co.uk,~rte.ie,~tunein.com,~oe24.at,~sika.com,~merkurmarkt.at,~boomerang-tv.pl,~cnbc.com,~1001spiele.de,~dhl.de,~sport.pl,~reisetopia.de,~mtvuutiset.fi,~billa.at,~aerztezeitung.de,~okazii.ro###onetrust-consent-sdk`

* Peter Lowe's Ad and tracking server list
`googletagmanager.com`

* ~~uBlock filters - Privacy https://github.com/uBlockOrigin/uAssets/issues/11422/~~ _(FIXED)_
~~`||googletagmanager.com/gtm.js$script,redirect=google-analytics.com/analytics.js`~~

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.4.4 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by krystian3w** [comment]
ABP may need implement use rewrite and resource to override google files.

**Comment by kiboke** [comment]
@THEtomaso I can't see that problem in "I don't care about cookies".

**Comment by krystian3w** [comment]
Check `.com/en` page at  bottom - block load embedded YT video and Instagram embedded post.

**Comment by kiboke** [comment]
OneTrust is fairly problematic on many websites :)
I see the problem now - I'll add all the needed exceptions, although a simple refresh fixes the video and Instagram problem even without accepting anything.
