### ISSUE TITLE
paletawin.pl

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#10570]
https://github.com/AdguardTeam/AdguardFilters/issues/107918

filter hide wrong pop-up:
https://github.com/easylist/easylist/blob/22926137ba2c93fd012220550eeab1c7b55d1c94/easylist_cookie/easylist_cookie_general_hide.txt#L685

Also pop-up lock scroll - so need careful hide if worth move to only FA list and add exception in EC.

Fyi @DandelionSprout / @Yuki2718 / @peace2000

**Comment by ryanbr** [comment]
No longer applicable

**Comment by krystian3w** [comment]
Page still active and broken if you not removed line:

https://github.com/easylist/easylist/blob/22926137ba2c93fd012220550eeab1c7b55d1c94/easylist_cookie/easylist_cookie_general_hide.txt#L685

**Comment by krystian3w** [comment]
Page not removed node or not renamed:

![Uploading Screenshot_20220220-132919_Firefox.jpg…]()

**Comment by krystian3w** [comment]
ed493e4e7d84f19ed9ac6e31988d3d2a1da8f7d9
https://github.com/easylist/easylist/commit/ed493e4e7d84f19ed9ac6e31988d3d2a1da8f7d9#diff-598464b7d3b10a0fa9680313e1e06e960b37e1ddf6e151c9eed5abc54cf35180L689
