### ISSUE TITLE
skinnyms.com

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#10571]
`https://skinnyms.com/9-ways-to-get-a-butt-lift-for-free/`

in footer:

```
##.social-links
```

On lef of article:

```
##.shared-counts-wrap
```

after end of article:

```
##.share-article
```

Newsletter:

`skinnyms.com##.join-today`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ba577a9c41b2062924815bfd794eb598bb1a2560
