### ISSUE TITLE
Filter blocking voting/verification and autocomplete function at torrentz2.eu again (update).

### ISSUE THREAD

**Issue by billyjeanis** [easylist/easylist#1058]
update from https://github.com/easylist/easylist/issues/1048
whitelists are not used anymore to serve ads please add again

```
@@||torrentz2.eu/report_$~third-party,xmlhttprequest
@@||torrentz2.eu/suggestions/$~third-party,xmlhttprequest
```

in the list so the site will function properly.

**Comment by ryanbr** [comment]
Why should we trust torrentz2 to just re-use another whitelist to serve ads?

**Comment by billyjeanis** [comment]
I can promise as a torrentz2 developer that I'll not use the white list to serve ads.
