### ISSUE TITLE
quora.com

### ISSUE THREAD

**Issue by buffbit** [easylist/easylist#1059]
### What happens?

Can't open external links on quora; new tab opened up quickly and closed.

### List Subscriptions you're using:

<img width="376" alt="screen shot 2018-04-19 at 11 11 35 am" src="https://user-images.githubusercontent.com/38538647/39010106-78dd39d0-43c2-11e8-9570-e128ead99724.png">

### Your settings

- OS/version: MacOS 10.13.2
- Browser/version: Chrome 65.0.3325.181
- Adblock Extension/version: uBlockOrigin 1.15.24

### Other details:

See a link I'm interested in: 
<img width="607" alt="screen shot 2018-04-19 at 11 16 40 am" src="https://user-images.githubusercontent.com/38538647/39010339-30897b66-43c3-11e8-8593-c1ffd837e690.png">

Clicked the link, new tab quickly opened and closed. UBlock logger suggests it's this filter
<img width="1318" alt="screen shot 2018-04-19 at 11 17 21 am" src="https://user-images.githubusercontent.com/38538647/39010939-f213004e-43c4-11e8-8baa-82f7093cb8af.png">

This also happened in some answers I read, such as 
https://www.quora.com/Do-you-have-any-tips-for-the-Stanford-GSB-application/answer/Linda-Abraham

**Comment by monzta** [comment]
This should be fixed now.
