### ISSUE TITLE
wwlp.com EasyList performance

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#106]
http://wwlp.com/2016/07/21/gun-rights-groups-protesting-healeys-crackdown-on-copycat-weapons/

EasyList doesn't **block** the video from playing, but causes it to take a lot longer to play. Though then the ad would play. But I have Ghostery/Privacy Badger/etc and they all block the ad as well without causing the video to take a long time to start playing.
So.. maybe the **way** that the ad is being blocked isn't optimal? Idk.

**Comment by monzta** [comment]
I wasn't able to find out what's actually causing it.
