### ISSUE TITLE
Too wide filter ##.cdk-overlay-container

### ISSUE THREAD

**Issue by samber** [easylist/easylist#10623]
### List the website(s) you're having issues:

Please remove the rule `##.cdk-overlay-container` since this is part of CDK (angular-material component kit).

It may break overlays on many websites.

### List Subscriptions you're using:

Fanboy annoyance + Fanboy cookie monster

### Your settings

I'm using uBlock Origin, with up-to-date filters.

### Other details:

Here is the doc for `overlay` component => https://material.angular.io/cdk/overlay/overview

**Comment by THEtomaso** [comment]
For there to be any chance of this happening, you really need provide a rather large amount of examples.
Otherwise, exceptions are added on a per-site basis, when single examples are provided.

**Comment by ryanbr** [comment]
Was adjusted https://github.com/easylist/easylist/commit/1f80432e352b48b80663ed962eec3563f7bf8af3
