### ISSUE TITLE
https://semiconductor.samsung.com/

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#10621]
### List the website(s) you're having issues:

`https://semiconductor.samsung.com/`

### What happens?

Website has a cookie acceptance banner that needs to be blocked.

### List Subscriptions you're using:

uBlock Origin default lists & default settings

### Your settings

- OS/version: Manjaro Linux KDE
- Browser/version: Firefox Nightly 98.0
- Adblock Extension/version: uBlock Origin 1.40.9b3

### Other details:

![semiconductor samsung com](https://user-images.githubusercontent.com/95879668/151192504-f04798ae-8ba7-45c3-bfac-4bf4ba548578.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8a94063f2e8a5fffda8c476376947426f2f23963

**Comment by q1800** [comment]
Thank you for the fix! Works great!
