### ISSUE TITLE
unsplash.com - links are incorrectly blocked/removed

### ISSUE THREAD

**Issue by OliverJAsh** [easylist/easylist#10645]
### List the website(s) you're having issues:

`unsplash.com`

### What happens?

(I work at Unsplash.)

Since https://github.com/easylist/easylist/commit/7badbbf1f78ef19775097017fbbd79a69e0e8514#diff-d95e1ad0368a5fb3bacb89fc7f209b9fa33a9974d9d2cf4b9a98903b7aa356a2, the EasyList filter blocks `unsplash.com##.eziW_`. /cc @ryanbr

`.eziW_` is our `resetAnchor` class which is a very generic class used almost everywhere across the site for styling links. As a result, many links are blocked/removed across the site.

Some examples:

![image](https://user-images.githubusercontent.com/921609/150767719-71b49802-1e51-464b-a25d-a9b76604c7c2.png)

![image](https://user-images.githubusercontent.com/921609/150767725-973351cf-2343-40e9-9edb-81a1fb919559.png)

![image](https://user-images.githubusercontent.com/921609/151344320-1ab4ca61-2f2d-4d7b-8318-acd483ebecd5.png)

![image](https://user-images.githubusercontent.com/921609/151345651-67a8350f-d331-4392-95cd-d54ccef2a84a.png)

![image](https://user-images.githubusercontent.com/921609/151345667-d3aef916-c1b3-4d21-9573-3c34aeb062d2.png)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by OliverJAsh** [comment]
@ryanbr What was the intention of your change in https://github.com/easylist/easylist/commit/7badbbf1f78ef19775097017fbbd79a69e0e8514 to block classes `HjpWP` and `eziW_`? I work at Unsplash and I would be happy to provide a hook/selector for the specific element you're trying to target.

I know we show an ad on `/t/wallpapers` but I don't think it's necessary to block these classes for that because it's already blocked by the filter for `a[href*="adzerk.net"]`:

https://github.com/easylist/easylist/blob/f142038998d7426fb4e9ecc50f55c26402674838/easylist/easylist_general_hide.txt#L22538

**Comment by OliverJAsh** [comment]
Fixed by https://github.com/easylist/easylist/commit/79714187fd585eb39148204e6e0841a41fabf93f by the looks of it

**Comment by OliverJAsh** [comment]
@ryanbr Regarding my previous comment, I would still be keen to hear why the class `HjpWP` was added to the filter list?

**Comment by urvbcn88** [comment]
@OliverJAsh 

Don't wait here for the answer. He won't answer you. He cares about no one, but himself.

**Comment by ryanbr** [comment]
@OliverJAsh ad elements being shown on the site, which is why its added

**Comment by OliverJAsh** [comment]
> ad elements being shown on the site, which is why its added

@ryanbr The ads are already hidden by another selector:

https://github.com/easylist/easylist/blob/f142038998d7426fb4e9ecc50f55c26402674838/easylist/easylist_general_hide.txt#L22538

So I'm not sure why it was necessary to block this class?

**Comment by OliverJAsh** [comment]
Since https://github.com/easylist/easylist/commit/0e94ece1c490d299496225b01e28ea9e60db9d8d this issue is occurring once again so I'm re-opening this.

@Edivania Please remove `unsplash.com##.eziW_` as per above.

**Comment by edivaniadc** [comment]
> Since [0e94ece](https://github.com/easylist/easylist/commit/0e94ece1c490d299496225b01e28ea9e60db9d8d) this issue is occurring once again so I'm re-opening this.
> 
> @Edivania Please remove `unsplash.com##.eziW_` as per above. #11744
Thanks for noticing and I'm so sorry for that @OliverJAsh  I hope it won't happen again. Filter has been removed accordingly by @ryanbr https://github.com/easylist/easylist/commit/3e01f7b
