### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by ijd** [easylist/easylist#10657]
### List the website(s) you're having issues:

`https://www.instagram.com/zuck/followers/`
`https://www.instagram.com/zuck/following/`

### What happens?

Pop-up window is blocked when clicking on an accounts followers/following.

Rule that is causing the window to be blocked:
`instagram.com##.Yx5HN.RnEpo`

### List Subscriptions you're using:

EasyList Cookie

**Comment by ryanbr** [comment]
filter was removed, should be okay now. @ijd
