### ISSUE TITLE
lalena.ro

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#10680]
### List the website(s) you're having issues:
`https://www.lalena.ro/c/110/salate/`

### What happens?
annoyance or annoyances 

### List Subscriptions you're using:
uBO ebd (macOS, eng)

### Your settings

- OS/version: macOS
- Browser/version: Google Chrome
- Adblock Extension/version: uBO

### Other details:
Could `lalena.ro##[id="c28"]` and `||lalena.ro/assets/js/all.1638382957.js$script` be added ?

**Comment by ryanbr** [comment]
Which Annoyances?

**Comment by BottledSoda** [comment]
![image](https://user-images.githubusercontent.com/98048296/152063379-a3a5ff36-5a4f-4777-a31f-233f94283a54.png)
the other one was a popup I believe

**Comment by ryanbr** [comment]
Leaving.
