### ISSUE TITLE
EasyList Cookie: [crownimg.com]

### ISSUE THREAD

**Issue by unknowboy1991** [easylist/easylist#10692]
### List the website(s) you're having issues:

```
https://crownimg.com/
```

### What happens?

Displays cookie consent notification (annoying)

```
CrownImg.com and its partners use cookies and similar technology to collect and analyse information about the users of this website.
We use this information to enhance the content, advertising and other services available on the site.
```

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

```
<div id="gdpr-cookie-notice" style="">
   <div style="float: left">
      CrownImg.com and its partners use cookies and similar technology to collect and analyse information about the users of this website.
      <br>We use this information to enhance the content, advertising and other services available on the site.
   </div>
   <input type="button" style="float: right; margin-right: 50px; padding: 20px; font-size: 16px; line-height: 0" value="Agree" onclick="cookiesAgree()">
</div>
```

**Comment by ryanbr** [comment]
We should already be blocking this, force an update @unknowboy1991

**Comment by unknowboy1991** [comment]
@ryanbr I did to be sure, but the cookie notice is still being displayed unfortunately.

As you said, `fanboy-cookiemonster` is already blocking `#gdpr-cookie-notice`, and I'm using this list with uBlock Origin, but the notice is not being removed, weird 

As this is not an issue with Easylist, I'm closing this; although I'm still not sure why it's not working on this particular website
