### ISSUE TITLE
https://www.cryptocoinsnews.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#107]
`https://www.cryptocoinsnews.com/`

bitStarz ad on right

**Comment by terrorist96** [comment]
@ryanbr can you please look at the issues here as well? I've been banned on lanik's forum lol

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/0e9fbaee816ccf211b51bbaf3d6270d0ef6bc087
