### ISSUE TITLE
www.thefork.com [EasyList Cookie List]

### ISSUE THREAD

**Issue by vitaliemaldur** [easylist/easylist#10710]
### List the website(s) you're having issues:
https://www.thefork.com/

### What happens?
The background from the blocked CMP/Cookie notice is still visible.

### List Subscriptions you're using:
`EasyList Cookie List`

### Your settings

- OS/version: macOS Monterey 12.1
- Browser/version: Chrome 97
- Adblock Extension/version: AdblockPlus

**Comment by krystian3w** [comment]
`###_evidon_banner, #_evidon-background`


but Evidon can break pages due inccorect implementation for 🇲🇩 and 🇳🇴  users.

**Comment by ryanbr** [comment]
I have asked around, so far no one can reproduce this.

**Comment by krystian3w** [comment]
Breakge in Norway or Moldavia? Then the best ask @DandelionSprout (his have Moldavian friend) and @THEtomaso.

Or you cannot reproduce backgorund named as `#_evidon-background`?

**Comment by THEtomaso** [comment]
Just whitelist the damn things!:
`https://github.com/DandelionSprout/adfilt/issues/7/#issuecomment-431578932`

**Comment by krystian3w** [comment]
https://github.com/DandelionSprout/adfilt/issues/7
