### ISSUE TITLE
hxc-power.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#1071]
### List the website(s) you're having issues:

http\://www.hxc-power.com/col.jsp?id=110

### What happens?

annoyance (back to top button)
privacy

### List Subscriptions you're using:

EasyList
EasyPrivacy
Fanboy's Annoyances

### Your settings

- Adblock Extension/version: ABP latest version

### Other details:

```
###siteBackToTop_small_box
##.fk_siteBackToTop
```
```
/log_h.jsp
/statistics_h.jsp
/logAjaxErr_h.jsp
```

**Comment by peace2000** [comment]
Still relevant @smed79

**Comment by Khrin** [comment]
Site looks dead to me.
