### ISSUE TITLE
[breakage] [Fanboy’s Annoyance] doctorofcredit.com

### ISSUE THREAD

**Issue by Ryan-Goldstein** [easylist/easylist#10726]
### List the website(s) you're having issues:

`https://www.doctorofcredit.com/sofi-receives-regulatory-approval-to-be-nationwide-bank-will-offer-1-apy/`
(and all other articles on that website - this also affects all websites that use the wpDiscuz Wordpress plugin)

### What happens?

On sites that use the wpDiscuz Wordpress plugin, the `##.wpdiscuz-subscribe-bar` filter in Fanboy's Annoyance List prevents the expansion of the Subscribe section under a post when the user clicks on it.

For example, on the website in the section above, below the article, indicated by the red arrow:

![image](https://user-images.githubusercontent.com/8300089/152269318-c1a6a2de-8619-4129-a0d2-559a5d6bba2f.png)

That section is supposed to expand when Subscribe is clicked, as below:

![image](https://user-images.githubusercontent.com/8300089/152269353-1880be05-3aea-454a-99d9-171e814b3646.png)

However, with the `##.wpdiscuz-subscribe-bar` filter, nothing happens when Subscribe is clicked.

### List Subscriptions you're using:

Fanboy's Annoyance List

### Your settings

- OS/version: Windows 11
- Browser/version: Chrome 98.0.4758.87
- Adblock Extension/version: uBlock Origin 1.40.8

### Other details:

Since the `##.wpdiscuz-subscribe-bar` filter is breaking functionality that would only expand that section when it's manually clicked by the user (i.e., the user clearly has intent to expand that section, to subscribe to comments), I'd propose the removal of this rule.

Alternatively, if that rule is blocking a legitimate annoyance, I'd propose that it be more narrowly targeted to stop preventing expansion of that section when Subscribe is clicked.

**Comment by Ryan-Goldstein** [comment]
The same behavior can be seen on the demo site of the wpDiscuz plugin, right above the "Join the discussion" text field: `https://wpdiscuz.com/demo/`

**Comment by krystian3w** [comment]
that button floating on whole Internet?

**Comment by ryanbr** [comment]
We do block subscription notification, newsletter popups. So its expected? resolved for this site.

**Comment by Ryan-Goldstein** [comment]
Thank you for resolving it for this site, as that's the only place I've encountered it personally.

However, for purposes of this filter list overall, I don't quite understand why the block is in place for that plugin generally, unless there are different implementations of which I'm unaware that cause annoyances. It's not a notification or popup or anything like that. As far as I can tell, all the filter rule is doing is preventing the user from clicking the Subscribe button to expand an otherwise hidden section to enter their email address, and clicking 'Subscribe' would of course mean the user had the intention to subscribe.

Regardless, thanks again for your consideration and for exempting the site.
