### ISSUE TITLE
Remove video playlist api entry from easylist_specific_block.txt 

### ISSUE THREAD

**Issue by sri123-m** [easylist/easylist#10728]
### List the website(s) you're having issues:
[finance.yahoo.com](https://finance.yahoo.com/), [sports.yahoo.com](https://sports.yahoo.com/), and all other yahoo sites.

### What happens?
Go to [finance.yahoo.com](https://finance.yahoo.com/)  and play any video from the page. Open  network  tab from developer tools and observe all  related video playlist API calls are blocked due to this  https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt#L510

This "related-videos" API provides a video playlist related to current playing video. This API is not ment for playing ads.  Could you please help remove our API "video-api.yql.yahoo.com^*/wf-channel=related-videos?" from the block list?

![image-fin](https://user-images.githubusercontent.com/4697060/152291955-f8747835-3f6d-48a1-8e77-a1c95898e73d.png)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by chsanthosh** [comment]
This was impacting related video playings in the Yahoo websites. Thank you for looking into.

**Comment by lingyan** [comment]
Add a bit more info about settings where I noticed this issue:

- OS/version: macOS Big Sur 11.6.2
- Browser/version: Chrome  97.0.4692.99, 98.0.4758.80
- Adblock Extension/version: Adblocker Ultimate 3.7.15, uBlock Origin 1.40.8, Adblock Plus 3.12 (All with default settings)

**Comment by ryanbr** [comment]
Related videos are considered invideo advertising.

**Comment by aagoath** [comment]
@ryanbr the related videos is an api for video recommendation and not in-video advertising. It is called when player is about to exhaust the playlist, and makes a backend request more content videos from the repository to fill the playlist. It is meant to improve the user experience, by delivering more content. The current blocking rule prevents users from enjoying continuous video playback experience. 

Just wanted to re-emphasize that this api is not meant for in-video advertising. Happy to answer any questions you may have.

**Comment by ryanbr** [comment]
`It is meant to improve the user experience, by delivering more content.`  

While in the yahoo world it maybe considered fine. For us, its just another invideo advert.
