### ISSUE TITLE
youjax.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#10737]
`https://youjax.com/aCxqOu`
### What happens?
Advertising

### List Subscriptions you're using:
AdGuard Base Filter, AdGuard Tracking Protection Filter, AdGuard Social Media Filter, AdGuard Annoyances Filter

### Your settings

- OS/version: macOS
- Browser/version: Google Chrome
- Adblock Extension/version: AdGuard for Mac

**Comment by ryanbr** [comment]
As a ref,

`https://www.downloadoperagx.com/ef/?tl=aHR0cHM6Ly93d3cub3N0bG9uLmNvbS9jbXAvQlg3SkY4L1A1SFBIQi8K&sub1=4759591&sub2=514045915713515564`

https://twitter.com/fanboynz/status/1487362759272833026   Just another trend of spamming, no time for this shit.
