### ISSUE TITLE
whathifi.com - ad placeholders

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#10735]
### List the website(s) you're having issues:

```
https://www.whathifi.com/
```
```
https://forums.whathifi.com/threads/best-smart-speakers-the-best-voice-assistant-speakers.111294/
```

### What happens?

![image](https://user-images.githubusercontent.com/84513173/152437405-ede40bff-4f6e-4858-b1c0-b635b26c073b.png)

![image](https://user-images.githubusercontent.com/84513173/152437130-0994d464-1eb1-4459-ac08-95814097084c.png)

### List Subscriptions you're using:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>
<summary>Details</summary>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 96.0.3  (64-bit)
- Adblock Extension/version: uBlock Origin 1.40.8

</details>

### Other details:

```
whathifi.com##.ad-unit
forums.whathifi.com###header_leaderboard
forums.whathifi.com###rightcol_top
```

**Comment by THEtomaso** [comment]
Note to ryanbr:
The following rule, found in '**uBlock filters – Annoyances**' effectively disables all generic element hiding rules for `whathifi.com`:
`@@||whathifi.com^$ghide`
Therefore, all such rules needs to be site-specific, like Nojuuu suggested.

--

Also, there are two whitelisting rules, found in '**AdGuard Annoyances filter**' and '**Easylist Cookie List**' / '**Fanboy's Annoyance List**' which doesn't play well together..

In '**AdGuard Annoyances filter**':
`@@||quantcast.mgr.consensu.org/tcfv2^`

In '**Easylist Cookie List**' / '**Fanboy's Annoyance List**':
`@@||quantcast.mgr.consensu.org^*/choice.js$domain=bikeperfect.com|cyclingnews.com|digitalcameraworld.com|einthusan.tv|express.co.uk|gamesradar.com|guitarplayer.com|independent.co.uk|indy100.com|laptopmag.com|livescience.com|livingetc.com|mahjong.com|musicradar.com|pcgamer.com|protothema.gr|realhomes.com|space.com|t3.com|techradar.com|tomsguide.com|whathifi.com|whattowatch.com`

Combined, those rules allows the cookie consent to pop up, without the possibility to be accepted (pressing AGREE only results in a infinite loading animation)!

@Yuki2718:
Possible fix for '**AdGuard Annoyances filter**'?:
```
- @@||quantcast.mgr.consensu.org/tcfv2^
+ @@||quantcast.mgr.consensu.org/tcfv2^$domain=~whathifi.com
```

**Comment by ryanbr** [comment]
Any other fixes for ghide should be in uBO lists specifically

**Comment by Nojuuu** [comment]
Sorry, my bad. I've opened so many issuess/prs here recently related to generichide here that I just assumed that the filter was in EasyList without checking further.
