### ISSUE TITLE
jmmv.dev

### ISSUE THREAD

**Issue by Jap2-0** [easylist/easylist#10732]
### List the website(s) you're having issues:

`https://jmmv.dev/2022/02/diy-web-analytics.html`

### What happens?

Tracking - appears to be a script loaded from an inline module, falling back to a tracking pixel in `<noscript>`.

### List Subscriptions you're using:

uBO defaults plus a few additions, this isn't blocked (and there are no exception filters in the logger).

### Your settings

- OS/version: Windows 10 (20H2)
- Browser/version: Firefox Nightly (98)
- Adblock Extension/version: uBO 1.40.9b9

### Other details:

See above

**Comment by ryanbr** [comment]
Not much we can do in easylist, try submitting to uBO
