### ISSUE TITLE
deviantart.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylist#10744]
### List the website(s) you're having issues:

https://www.deviantart.com/

### What happens?

When I visit this website, it loads `https://www.deviantart.com/_adslot/...` in the background.

I suspect it's related to ad.

### List Subscriptions you're using:

EasyList

**Comment by THEtomaso** [comment]
https://github.com/AdguardTeam/AdguardFilters/blob/2c48f5a8381c616ffad58638d2afdb8217a53c9d/EnglishFilter/sections/specific.txt#L5169
