### ISSUE TITLE
w3techs.com

### ISSUE THREAD

**Issue by theel0ja** [easylist/easylist#1074]
### List the website(s) you're having issues:

`https://w3techs.com/`

### What happens?

unblocked ads

### List Subscriptions you're using:

easylist

### Your settings

- OS/version: windows 10
- Browser/version: chrome stable
- Adblock Extension/version: ublock origin

### Other details:

```
||a.w3techs.com/images/61/20180403081740-UMANG_SOFTWARE_Hire_Technology_Experts_Programmers_India.png
```

**Comment by krystian3w** [comment]
`###hdc > a > img`
`###hdc > a`

**Comment by spirillen** [comment]
Is the `a.w3techs.com` solely used for ads and/or tracking?
