### ISSUE TITLE
Whiteaway Group sites - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#10757]
### Affected sites:
```
https://www.skousen.dk/
https://www.skousen.no/
https://www.whiteaway.com/
https://www.whiteaway.no/
https://www.whiteaway.se/
```

### Issue:
Several things doesn't work, due to a blocked cookie consent, which needs to be accepted!

### How to reproduce:
* Try using the site's search funcion (it doesn't work).
* Add something to the shopping basket, then open it (it's empty).

### Screenshots:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
```
###coiOverlay[role="banner"][style*="flex"]
###CookieConsent
||cookieinformation.com^$subdocument,third-party
||cookieinformation.com/*/*.js
```

### Possible fix (ABP and uBO Legacy compatible):
```
skousen.dk,skousen.no,whiteaway.com,whiteaway.no,whiteaway.se#@##coiOverlay[role="banner"][style*="flex"]
skousen.dk,skousen.no,whiteaway.com,whiteaway.no,whiteaway.se#@##CookieConsent
@@||policy.app.cookieinformation.com^$domain=skousen.dk|skousen.no|whiteaway.com|whiteaway.no|whiteaway.se
```

### Other problem filters:
* **AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/109380/
```
###CookieConsent
||policy*.cookieinformation.com^$third-party
```

* **I don't care about cookies** (@kiboke)
```
###Coi-Renew
###CookieConsent:not(.modal)
policy.app.cookieinformation.com$domain=~kartor.eniro.se|~kart.gulesider.no|~kort.degulesider.dk|~map.krak.dk|~altibox.no|~babysam.dk|~minaftale.dk|~dvdoo.dk
```

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Chromium-ungoogled v98.0.4758.80-r950365 (x64)
* Adblock Extension/version: uBlock Origin v1.40.8

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by kiboke** [comment]
@THEtomaso thanks! I'll whitelist `policy.app.cookieinformation.com` for all of them in IDCAC. Other mentioned filters do not seem to be needed.

**Comment by THEtomaso** [comment]
skousen.dk and skousen.no are broken again by **Easylist Cookie List** / **Fanboy's Annoyance List**, because of this commit:
https://github.com/easylist/easylist/commit/31ee4f8110508bd0ff557ee0b851c9675e43c33d
(The issues are the same as the ones described in the first post)

Solution: Remove the commit!
