### ISSUE TITLE
Fanboy's Annoyances breaks retrogames' images

### ISSUE THREAD

**Issue by Felipefpl** [easylist/easylist#10767]
Please see the issue reported below:

https://github.com/uBlockOrigin/uAssets/issues/11588#issuecomment-1030170822

**Comment by THEtomaso** [comment]
### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rule:
`/cookieconsent.$~stylesheet`

### Possible fix:
`@@||retrogames.cc/js/cookieconsent.min.js`

--

### Other problem filters:
 * **AdGuard Annoyances filter** (@Yuki2718)
`/cookieconsent.$domain=~crm.cat|~alginor.no|~khl.ru|~kundenkonto.lidl-connect.de|~shmoop.com`

* **I don't care about cookies** (@kiboke)
`/cookieconsent.min.js$domain=~sonnenverlauf.de`

**Comment by Felipefpl** [comment]
Thank you both for fixing the issue. :) 👍

**Comment by kiboke** [comment]
@THEtomaso thanks, it will be fixed in IDCAC.
