### ISSUE TITLE
atishmkv.life ads

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#10768]
There are ads on

`https://atishmkv.life/antim-the-final-truth-2021-zee5-web-dl-hindi-dd2-0-1080p-720p-480p/`

Using Default Ubo 1.40.8 settings
Google chrome stable

**Comment by BottledSoda** [comment]
Is `tawk.to` used for tracking and/or data collection in this case?

**Comment by BottledSoda** [comment]
@ryanbr `tkr.arc.io`

**Comment by THEtomaso** [comment]
> Is `tawk.to` used for tracking and/or data collection in this case?

All chat services are,
But at that site, it should probably be the least of your worries.

**Comment by ghajini** [comment]
site changed to `atishmkv.site` @ryanbr so the cosmetic filters
