### ISSUE TITLE
support.creative.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#10782]
### List the website(s) you're having issues:

`https://support.creative.com/`

### What happens?

Website Breakage

### List Subscriptions you're using:

uBO default lists
Fanboy’s Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 97.0.2
- Adblock Extension/version: uBO 1.41.9b0

### Other details:

I filed #10016 for the same problem, but the fix did not solve anything. The webpage exhibits the same original issue. Can someone please take another look into this? Thank you.

**Comment by ryanbr** [comment]
It works for me, unless there is more debug info. I won't touch this.

**Comment by q1800** [comment]
@ryanbr @Khrin 

I have further troubleshot this issue and found the filter that is causing the website breakage in the Fanboy’s Annoyance filter list. See screenshots below for various information and troubleshooting steps showing the filter both enabled and disabled.

`||zdassets.com/ekr/snippet.js`

Can you please create a fix or an exception for this issue?

Thank you!

![ubo-asset-viewer-fanboy-annoyance](https://user-images.githubusercontent.com/95879668/157967592-dac1a83c-9819-4a93-80b9-45dc722b9ce7.png)

![inspector-with-fanboy-annoyance-enabled](https://user-images.githubusercontent.com/95879668/157967461-4e229c6e-5e2c-4f87-b18c-3b1f8f42d70a.png)

![console-error-with-fanboy-annoyance-enabled](https://user-images.githubusercontent.com/95879668/157967731-d18c052a-e922-47d7-94a4-67c09a26638a.png)

![ubo-filter-list-with-fanboy-annoyance-enabled](https://user-images.githubusercontent.com/95879668/157967527-a980e5c9-0c49-476b-9c2e-89d95fd349b1.png)

![inspector-with-fanboy-annoyance-disabled](https://user-images.githubusercontent.com/95879668/157967617-f41a53f5-1106-4f99-93dd-6daff2fb0338.png)

![console-error-with-fanboy-annoyance-disabled](https://user-images.githubusercontent.com/95879668/157967627-3f657b0b-a530-410d-8cd9-f4ac6a37967b.png)

![ubo-filter-list-with-fanboy-annoyance-disabled](https://user-images.githubusercontent.com/95879668/157967678-2b6e6e4e-f6ac-40f2-bfec-9004e09a6067.png)

![ubo-with-breakage-filter-enabled](https://user-images.githubusercontent.com/95879668/157967815-d09f46ed-d53c-43cf-a48a-c65a8157b9e9.png)

![ubo-with-breakage-filter-disabled](https://user-images.githubusercontent.com/95879668/157967823-fc0e844d-1076-42da-8c40-2399391b5cfe.png)

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16856
