### ISSUE TITLE
cloud.mail.ru

### ISSUE THREAD

**Issue by timv32** [easylist/easylist#10799]
### List the website(s) you're having issues:
`https://cloud.mail.ru/public/BYEw/jKQZvk4Fp`

### What happens?

<details>
 <summary>Screenshot</summary>

![cl2](https://user-images.githubusercontent.com/95632675/152889589-b403ee3a-2232-413b-ad3d-0fe859561b18.png)

</details>

### List Subscriptions you're using: 
`EasyList, EasyPrivacy, Fanboy's Annoyances`

### Your settings

Bitwarden
Decentraleyes

- OS/version: Windows 10
- Browser/version: Firefox 96.0.3
- Adblock Extension/version: uBlock Origin 1.40.8

### Other details:

The `~mail.ru` exclusion causes ads to appear on `cloud.mail.ru` So, I removed the exclusion altogether.

**Comment by Khrin** [comment]
Use RU AdList (`https://easylist-downloads.adblockplus.org/advblock.txt`) to block ads on Russian-language sites.
