### ISSUE TITLE
[Incorrect blocking] pornhub.com

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#1079]
Actual behavior:

<details>

![image](https://user-images.githubusercontent.com/8361299/39119202-f25039a0-46f3-11e8-8a68-1269a9b0ff20.png)

</details>

Expected behavior:

<details>

![image](https://user-images.githubusercontent.com/8361299/39119100-b65e5c06-46f3-11e8-8397-ad2ea1ccd6d9.png)
</details>

Caused by this rule:
```
extremetube.com,pornhub.com,redtube.com,tube8.com,tube8.es,tube8.fr,xtube.com,xvideos.com,youjizz.com,youporn.com,youporngay.com##[style*="display: block;"]
```

**Comment by ryanbr** [comment]
was removed.
