### ISSUE TITLE
Alienvault OSSIM and USM

### ISSUE THREAD

**Issue by Peetz0r** [easylist/easylist#108]
### URL(s) where the issue occurs

https://demo.alienvault.com/ossim/#analysis/alarms/alarms-1E5697B759C511E69DEC0A830B0255F0
- user: **guest**
- password: **alienvault**
### Describe the issue

The alarm details don't display on that page.
### Screenshot(s)

http://i.imgur.com/zuYlH2b.png
http://i.imgur.com/yPfl6t4.png
### Versions
- uBO 1.7.6 in Chrome 52 on Windows 10
- uBO 1.8.0 in Chromium 51 on Ubuntu 14.04
### Settings

Default
### Notes

This is because the page uses divs named **ad_header** and **ad_content** and more (see uBO log) which are seen as ads but ad stands for alarm detail.

This happens not just for me, but for all of my coworkers. We use Alienvault OSSIM inside our company, but the public Alienvault USM demo linked above has the exact same behavior.

Alienvault does not always run on *.alienvault.com but could be on any host.

`@@/ossim/*$generichide` works, but it would be bad to see advertisers changing all their urls to something with /ossim/ in them, wouldn't it?

This is a continuation of https://github.com/uBlockOrigin/uAssets/issues/91

**Comment by monzta** [comment]
Looks like Alienvault fixed this on their end. Can you confirm this?
