### ISSUE TITLE
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=CZE-0

### ISSUE THREAD

**Issue by olithereum** [easylist/easylist#1080]
### What happens?
Most of the advertisings, media agencies and other links of similar related businesses, are whitelisted!!! 

### List Subscriptions you're using:
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=CZE-0

### Your settings

- OS/version: OS X El Capitan / version 10.11.6 (15G20015)
- Browser/version: Chrome Version 66.0.3359.117 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin v1.15.24

### Other details:
the whitelisting paragraphs need to be fully reviewed if may be as well some defect regarding regular websites which does not show some images.

**Comment by ryanbr** [comment]
Not an adblock issue.
