### ISSUE TITLE
Multiplayer.it

### ISSUE THREAD

**Issue by yomeci** [easylist/easylist#10835]
https://multiplayer.it/notizie/pubblicita-videogiochi-anni-90-2000-sessualizzate-folli-imbarazzo.html

Images gets blocked on page if Easylist Italy is turned on, tested with Adguard and uBlock Origin.

![2](https://user-images.githubusercontent.com/99401022/153396447-d6dde4b5-c8e6-46ea-a495-599e01eb0142.jpeg)
![Acquisisci schermata Web_10-2-2022_115827_multiplayer it](https://user-images.githubusercontent.com/99401022/153396477-0e7cad29-2027-4c25-985f-913b419be046.jpeg)

**Comment by Khrin** [comment]
See https://github.com/easylist/easylistitaly/issues/12
