### ISSUE TITLE
https://www.asus.com.cn/Motherboards-Components/Motherboards/All-series/

### ISSUE THREAD

**Issue by dunkeng** [easylist/easylist#10837]
### List the website(s) you're having issues:
[](https://www.asus.com.cn/Motherboards-Components/Motherboards/All-series/
)

### What happens?

cookie filter error 

### List Subscriptions you're using:

EasyList Cookie

### Your settings

- OS/version:  Windows 11 22000.493
- Browser/version:  EDGE 98.0.1108.43 
- Adblock Extension/version:  uBlock Origin 1.40.8

**Comment by ryanbr** [comment]
Thanks @dunkeng any more issues, do submit!
