### ISSUE TITLE
Trackers on `ally.com`

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#10851]
### List the website(s) you're having issues:
`https://secure.ally.com/dashboard` (Dashboard after you login to `ally.com`)

### What happens?

Loads requests for LogRocket and DatadogHQ.

![Screenshot 2022-02-11 at 10 46 14 AM](https://user-images.githubusercontent.com/11689349/153622790-de5ab336-69b4-4f53-9214-27f8476dac18.jpg)

![Screenshot 2022-02-11 at 10 39 22 AM](https://user-images.githubusercontent.com/11689349/153622742-caf33cb5-9710-4696-849f-14513ec41bae.jpg)

Suggested:
```
||rum-http-intake.logs.datadoghq.com^
||browser-intake-datadoghq.com^
||prod-default.lb.logrocket.network^
||lr-in.com^$3p
||lr-hv-in.com^$3p
```

### List Subscriptions you're using:

![ublock list 11 feb](https://user-images.githubusercontent.com/11689349/153625611-49502cbd-4b63-4675-8271-15424de0cac9.jpg)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by S0dV** [comment]
> (Dashboard after you login to `ally.com`)

Does someone have to bank with `Ally` in order to create an account?

**Comment by yokoffing** [comment]
> Do people have to bank with `Ally` in order to create an account?

AFAIK

**Comment by yokoffing** [comment]
`https://screencast-o-matic.com/` also uses a DatadDogHQ request: `datadoghq-browser-agent.com^`
