### ISSUE TITLE
diffnow.com (cookies)

### ISSUE THREAD

**Issue by Gitoffthelawn** [easylist/easylist#10875]
https://www.diffnow.com/

### What happens?

Cookie notice at bottom of viewport.

### List Subscriptions you're using:

Easylist Cookies

### Your settings

- OS/version: Linux
- Browser/version: Firefox 97
- Adblock Extension/version: uBO 1.41.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/cfe7084f870046cea10ac300f46acd0412342d61
