### ISSUE TITLE
wenku.baidu.com

### ISSUE THREAD

**Issue by Git-Learn1** [easylist/easylist#10879]
### List the website(s) you're having issues:
https://wenku.baidu.com/view/65c7c0d3bc64783e0912a21614791711cd79790e.html

### What happens?
It has ADs.

### List Subscriptions you're using:
EasyList, EasyPrivacy, EasyListChina

### Your settings

- OS/version: Windows 10 21H2 x86_64 (Build 19044.1526)
- Browser/version: Microsoft Edge 98.0.1108.50
- Adblock Extension/version: uBlock Origin 1.41.0

### Other details:
I added some custom rules to solve this problem. Here are my custom rules:
```
wenku.baidu.com##div.hx-warp
wenku.baidu.com##.hx-recom-wrapper
```

**Comment by ryanbr** [comment]
Report to EL China, not here.
