### ISSUE TITLE
lustre.ai mistakenly reported as ad server

### ISSUE THREAD

**Issue by ybentz** [easylist/easylist#10882]
### List the website(s) you're having issues:

- `https://lustre.ai`

### What happens?

Lustre's browser extension started being blocked a few days ago because of [this change](https://github.com/easylist/easylist/commit/4b7eea02dcfc1a7b959972f8af121ebbe72d757e) where `lustre.ai` was mistakenly identified as an ad server. 

To reproduce:
- Install Lustre's extension from `https://chrome.google.com/webstore/detail/lustre/cjmfiochlaffhnellbhffgnjocahinnh`
- Go to Amazon and search for "monitor" for example.
- A big empty space shows up at the top of the page due to the iframe being blocked.

### List Subscriptions you're using:

Default

### Your settings

- OS/version: macOS Catalina 10.15.7 
- Browser/version: Chrome 98
- Adblock Extension/version: uBlock Origin 1.41.2

### Other details:

`slant.co` and `lustre.ai` are made by the same company (full disclosure - I work there). In order to promote Lustre which is our newer product we put a banner on slant which I can agree looks like an ad. In this [issue](https://github.com/easylist/easylist/issues/10708) and [commit](https://github.com/easylist/easylist/commit/4b7eea02dcfc1a7b959972f8af121ebbe72d757e) Lustre was reported and added to the ad servers list even though it's not at all an ad server but a functioning website. Lustre has a browser extension that loads content on 3rd party online retailers (e.g. Amazon) via iframes, as soon as this commit was deployed Lustre's extension stopped working for user who also uses ad blockers that use easylist.

My request is that Lustre's hostname will be removed from the ad server list but keep the `slant.co##.SummaryPage-LustreEmbed` addition in the `easylist_specific_hide.txt` list so the "ad" is blocked on Slant.
I'd be happy to provide more details if necessary.

**Comment by ryanbr** [comment]
These are ads, and lustre is considered an adserver

**Comment by ybentz** [comment]
Thank you for the day response. Can you explain what you mean? Lustre's server doesn't serve ads, the content we put on slant is an interactive embedded page that we also use as part of the extension and on our website.
Like I said, blocking it on slant is completely understandable since slant users never explicitly asked for it but every user of Lustre's extension explicitly installed it on their browser via the extensions store for the sole purpose of seeing our content on 3rd party sites and now we have users reaching out to us and asking why the extension isn't working for them.

**Comment by ryanbr** [comment]
We don't use the extension. The moment lustre embedded ads into web pages like in the previous PR. its considered an Adserver without question.

That said, I've adjusted the block to avoid breaking the extension and tested. https://github.com/easylist/easylist/commit/ebd85152107fd948f68039329397cecaefb398d9  And keeps user privacy.

If we find any issue of work arounds to show lustre embedded ads on 3rd-party sites (without the extension) we'll reevaluate the block again.
