### ISSUE TITLE
Gmail/Quora issue

### ISSUE THREAD

**Issue by fakkura** [easylist/easylist#1088]
### List the website(s) you're having issues:

https://mail.google.com/mail/u/0/#inbox
https://www.quora.com/qemail/track_click

### What happens?

Clicking on Quora digest links in Gmail closes the newly opened tab immediately. 
It works if i disable easylist from filters.
I'm not sure if it's Google's tracking url or Quora tracking url but when i manually open a new tab and paste quora tracking url that leads to the article the tab isn't closed..

### List Subscriptions you're using:

uBlock filters
uBlock badware risks
uBlock privacy
uBlock resource abuse
uBlock unbreak
AdBlock warning removal list
EasyList
Malware domain list
Malware domains
Peter Lowe’s Ad and tracking server list

I'm pretty certain EasyList is the problem since it works just fine if i uncheck EasyList

### Your settings

- OS/version: Windows 7 Ultimate x64 SP1/6.1.7601
- Browser/version: Chrome/65.0.3325.181
- Adblock Extension/version: uBlock Origin/v1.16.0

**Comment by monzta** [comment]
This should fix it: https://github.com/easylist/easylist/commit/59eeb829f9eb191c8f7776249dd3d8f749c195b8
