### ISSUE TITLE
quora.com: non-ad component clicks are being blocked

### ISSUE THREAD

**Issue by hulagu** [easylist/easylist#1089]
### List the website(s) you're having issues:

`https://www.quora.com/`

### What happens?

Quora digest story clicks are being blocked by my ad blocker. Note that these components are not related to ads in any way. 

To reproduce, try clicking on any story you receive in quora's digest. If you are not a Quora user and do not have access to a digest, try opening the following digest story link as a popup (new tab): 

https://www.quora.com/qemail/track_click?uid=YHzvvt0vIN4&al_imp=eyJoYXNoIjogIjIzMTY0Nzc3NjYzNzczNjAwOHwxfDF8MTQwNjQyNCIsICJ0eXBlIjogMzN9&aoid=9iUA8czrclY&request_id=231647776637736008&aoty=2&et=2&al_pri=QuestionLinkClickthrough&id=s9-fE7VSui3V2mt2J56zyg%3D%3D&ct=1475745194759952&src=1&ty_data=YH1qrGBmhTh&ty=1&click_pos=1&st=1475745194759952&source=1&stories=1_YH1qrGBmhTh%7C1_Lb8BBy4l1zr%7C1_mW3FG0Y0cpU%7C1_zijOKlTVsU%7C1_c5cuK4oJnK%7C1_RR5HLO4OSEY%7C1_q9P1d9d2dxB%7C1_akcV3PAcX5y%7C1_qxt0MvZo8vW%7C1_4lmnxKWpXUa&v=0&aty=4

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: MacOS High Sierra 10.13.4 (17E199)
- Browser/version: Chrome 65.0.3325.181 (64-bit)
- Adblock Extension/version: Adblock Plus 3.0.3

### Other details:

This seems to be the offending filter: `||quora.com^*?*=*%$popup`

Digest stories screenshot:
![image](https://user-images.githubusercontent.com/38670795/39154037-caeaad6a-4701-11e8-8588-69fec42f107e.png)

**Comment by monzta** [comment]
see https://github.com/easylist/easylist/issues/1088
