### ISSUE TITLE
No video only sound in adult website +18 

### ISSUE THREAD

**Issue by xswuper24** [easylist/easylist#1090]
### List the website(s) you're having issues:
https://www.xvideos.com/video33073733/vid-20180116-wa0005

### What happens?

No video only sound, but when I disabled easylist filter everything will work just fine but with ads 

### List Subscriptions you're using:
Acceptable Adsupdated
AdBlock custom filters
EasyList

adblock 3.28.0

### Your settings

- OS/version:  windows 10 pro 
- Browser/version: chrome Version 65.0.3325.181 (Official Build) (64-bit)

- Adblock Extension/version:  3.28.0

### Other details:

setSeekBarColor : #de2600
player.html5hls.static.js:10 Useragent:mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/65.0.3325.181 safari/537.36
player.html5hls.static.js:10 Is a desktop
player.html5hls.static.js:13 supportHLSjs : true
player.html5hls.static.js:13 Send debug event 'hls_loaded'
player.html5hls.static.js:11 Thumb Slide : FULL
player.html5hls.static.js:13 closeAd() : Closing ad
player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:10 Video initial draw done
player.html5hls.static.js:10 Chrome >= 64 do not display popunder
player.html5hls.static.js:10 Storage available
player.html5hls.static.js:12 Init HLS
player.html5hls.static.js:12 Hls.Events.MANIFEST_LOADING hlsManifestLoading https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls.m3u8
player.html5hls.static.js:12 setBuffering: is Buffering
player.html5hls.static.js:12 checkVideoAds() Video ads already viewed
player.html5hls.static.js:13 closeAd() : Ad already closed
player.html5hls.static.js:10 VideoEvent: loadstart
player.html5hls.static.js:12 Hls.Events.MEDIA_ATTACHED
default.js:2 GET https://rpc-php.trafficfactory.biz/json/square-2xfooter-1/22731083e740969283b8fec183a5489b//xvideos////content.json?v=0.7214152364296817 net::ERR_BLOCKED_BY_CLIENT
P @ default.js:2
R @ default.js:2
(anonymous) @ default.js:2
execCb @ require.static.js:2
check @ require.static.js:2
enable @ require.static.js:2
enable @ require.static.js:2
(anonymous) @ require.static.js:2
(anonymous) @ require.static.js:2
each @ require.static.js:2
enable @ require.static.js:2
init @ require.static.js:2
(anonymous) @ require.static.js:2
setTimeout (async)
req.nextTick @ require.static.js:2
localRequire @ require.static.js:2
requirejs @ require.static.js:2
(anonymous) @ default.js:8
default.header.static.js:2 => ''
default.js:5 no chat if !logged and not a profile page with recent chat interaction
default.js:12 Video 33073733 already registered
default.header.static.js:2 POST https://www.xvideos.com/picserror//-/2/1 404 (Not Found)
checkOrSend @ default.header.static.js:2
P.c.onreadystatechange @ default.js:2
XMLHttpRequest.send (async)
P @ default.js:2
R @ default.js:2
(anonymous) @ default.js:2
execCb @ require.static.js:2
check @ require.static.js:2
enable @ require.static.js:2
enable @ require.static.js:2
(anonymous) @ require.static.js:2
(anonymous) @ require.static.js:2
each @ require.static.js:2
enable @ require.static.js:2
init @ require.static.js:2
(anonymous) @ require.static.js:2
setTimeout (async)
req.nextTick @ require.static.js:2
localRequire @ require.static.js:2
requirejs @ require.static.js:2
(anonymous) @ default.js:8
6player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:10 ChromeCast: onInitSuccess
player.html5hls.static.js:10 ChromeCast: receiverListener unavailable
player.html5hls.static.js:13 Show buffer
3player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:12 Hls.Events.MANIFEST_PARSED hlsManifestParsed {levels: Array(2), audioTracks: Array(0), firstLevel: 1, stats: {…}, audio: false, …}
player.html5hls.static.js:12 Hls.Events.MANIFEST_LOADED hlsManifestLoaded nb levels 2
player.html5hls.static.js:13 getLocalStorage forcequality null
player.html5hls.static.js:13 Key forcequality doesn't exist
player.html5hls.static.js:12 Best level 1 for speed 10129 Kb/s
player.html5hls.static.js:12 Hls.Events.MEDIA_DETACHED
player.html5hls.static.js:10 VideoEvent: loadstart
player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:12 Hls.Events.MEDIA_ATTACHED
3player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:12 Hls.Events.LEVEL_LOADED hlsLevelLoaded 1
player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:12 Hls.Events.LEVEL_LOADED hlsLevelLoaded 0
8player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:13 Not enought stats
player.html5hls.static.js:12 Progress https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p0.ts 215824 / 215824 : 100 % (Paused : true, Seeking : false, ReadyState : 0, CurrentTime 0/NaN)
player.html5hls.static.js:12 Hls.Events.FRAG_PARSING_INIT_SEGMENT hlsFragParsingInitSegment id = main level = undefined
player.html5hls.static.js:13 Show buffer
player.html5hls.static.js:12 setBuffering: is not Buffering in 1300 ms
player.html5hls.static.js:13 Send debug event 'hls_buffer_duration'
player.html5hls.static.js:10 Video ratio 0.7591623036649214
player.html5hls.static.js:12 Hls.Events.FRAG_BUFFERED hlsFragBuffered url = https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p0.ts
player.html5hls.static.js:12 Hls.Events.FRAG_CHANGED hlsFragChanged Level 0 Url https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p0.ts
player.html5hls.static.js:13 Not enought stats
player.html5hls.static.js:12 Progress https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p1.ts 255304 / 255304 : 100 % (Paused : true, Seeking : false, ReadyState : 4, CurrentTime 0/33.5)
player.html5hls.static.js:11 Small Play Butt click
player.html5hls.static.js:12 displayVideosAds: Not the 2nd play (or more). Bypass videosads display
player.html5hls.static.js:13 closeAd() : Ad already closed
player.html5hls.static.js:13 html5player.play()
player.html5hls.static.js:13 closeAd() : Ad already closed
player.html5hls.static.js:13 Send debug event 'hls_playing'
player.html5hls.static.js:12 Hls.Events.FRAG_BUFFERED hlsFragBuffered url = https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p1.ts
player.html5hls.static.js:13 Not enought stats
player.html5hls.static.js:12 Progress https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p2.ts 263200 / 263200 : 100 % (Paused : false, Seeking : false, ReadyState : 4, CurrentTime 0.21/33.5)
player.html5hls.static.js:12 Hls.Events.FRAG_BUFFERED hlsFragBuffered url = https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p2.ts
player.html5hls.static.js:13 Not enought stats
player.html5hls.static.js:12 Progress https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p3.ts 83096 / 83096 : 100 % (Paused : false, Seeking : false, ReadyState : 4, CurrentTime 0.38/33.5)
player.html5hls.static.js:12 Hls.Events.FRAG_BUFFERED hlsFragBuffered url = https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p3.ts
player.html5hls.static.js:13 Show Info end
default.js:12 Try to declare link
player.html5hls.static.js:12 Hls.Events.FRAG_CHANGED hlsFragChanged Level 0 Url https://hls4-l3.xvideos-cdn.com/1bfb0ea51fcb87b6c50406df05fb10ef235170fb-1524562147/videos/hls/ee/c0/cd/eec0cd1e86bf4ad28505692020fe3cb1/hls-250p1.ts
player.html5hls.static.js:13 Send pending video duration
player.html5hls.static.js:13 Sending duration 33.5247 for video 33073733
player.html5hls.static.js:13 Send pending video duration
player.html5hls.static.js:13 Sending duration 68.89181 for video 35653269

**Comment by ryanbr** [comment]
Update your subs.
