### ISSUE TITLE
Puzzle about FOP.py

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylist#10910]
FOP.py cannot handle lists which contains rules like `example.com##*:not(.example)`.

I tried to use FOP.py to arrange [AdGuard Chinese filter](https://filters.adtidy.org/windows/filters/224_optimized.txt). Then I found FOP.py failed as long as this rule `duonaolive.com##*:not(.carousel-item) > a[href][rel="nofollow"][onclick*="track"] > img` exists. Then I added `example.com##*:not(.example)` to easylist, and FOP.py failed again.

`example.com##*:not(.example)` doesn't report sytanx error in uBlock, so it may be a bug of FOP.py?

**Comment by krystian3w** [comment]
Test this fop fork:

https://github.com/FiltersHeroes/ScriptsPlayground/blob/master/scripts/FOP.py

Is updated okayonally by [hawkeye116477](https://github.com/hawkeye116477).

**Comment by MkQtS** [comment]
> Test this fop fork:
> 
> https://github.com/FiltersHeroes/ScriptsPlayground/blob/master/scripts/FOP.py
> 
> Is updated okayonally by **[@hawkeye116477](https://github.com/hawkeye116477)**.

It works well.

**Comment by krystian3w** [comment]
So EL use a little outdated - maybe need wait 2+ months to fix bugs.

**Comment by MkQtS** [comment]
I found another puzzle. When handling list contains these rules:

```
||example1.com/example/example.js
||example1.com^
||example2.com^
||example2.com^$third-party
```

FOP.py don't combine them into `||example1.com^` & `||example2.com^`. So it can be better optimized?

**Comment by krystian3w** [comment]
I suppose possible add warmings:
```
||example1.com/example/example.js has been made redundant by ||example1.com^
||example2.com^$third-party has been made redundant by ||example2.com^
```

To less check list in:

- https://abpvn.com/ruleChecker/redundantRuleChecker.html
- https://redundantcheck.certyficate.it/redundantRuleChecker.html
- https://adblockplus.org/redundancy_check

Off-topic checker: https://www.reddragonwebdesign.com/projects/adblock-filter-analyzer/

**Comment by ryanbr** [comment]
Closing ticket, will test the other FOP script at some stage.  Anyone can open a PR for FOP, just test before hand.
