### ISSUE TITLE
open.spotify.com Search Breakage

### ISSUE THREAD

**Issue by solxr** [easylist/easylist#10919]
### What happens?
Artist profile box does not display in search results

### List Subscriptions you're using: 
Fanboy’s Annoyance

### Your settings

- OS/version: Windows 10 21H2
- Browser/version: Chrome 98.0.4758.102 (works on all chromium-based)
- Adblock Extension/version: uBlock Origin 1.41.2

### Other details:
![msedge_yNSAzvtBTe](https://user-images.githubusercontent.com/71159832/154716733-6b3d2047-9f29-46ee-899a-63f02b8eae20.png)
(Example)

**Comment by THEtomaso** [comment]
### Problem filters:
* **EasyList Cookie List**
* **Fanboy's Annoyance List**

### Problem rule:
`spotify.com##div > div[aria-live="polite"]`

### Possible fix:
```
- spotify.com##div > div[aria-live="polite"]
+ spotify.com##div > div[aria-live="polite"]:not([data-testid="top-result-card"])
```

### Temp fix:
```
spotify.com#@#div > div[aria-live="polite"]
spotify.com##div > div[aria-live="polite"]:not([data-testid="top-result-card"])
```
