### ISSUE TITLE
ipv6test.google.com does not work with ublock origin

### ISSUE THREAD

**Issue by henriquenj** [easylist/easylist#1091]
### List the website(s) you're having issues:

`https://ipv6test.google.com/`

### What happens?

The test does not work because it triggers the filter for `metric.gstatic.com` on EasyPrivacy

### List Subscriptions you're using:

EasyPrivacy
EasyList

In summary the default ones from uBlock origin.

### Your settings

- OS/version: 
Ubuntu 16.04.4 LTS (Xenial Xerus)
- Browser/version: 
Google Chrome Version 66.0.3359.117
- Adblock Extension/version: 
uBlock Origin 1.16.0

### Other details:

**Comment by monzta** [comment]
Thanks, fixed: https://github.com/easylist/easylist/commit/d5626a52f0d201a773e017e4b92bb35748f0c2bd

**Comment by henriquenj** [comment]
Thanks!
