### ISSUE TITLE
Microsoft Edge StartPage/Homepage

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#10955]
### List the website(s) you're having issues:
It's Microsoft Edge's Homepage. So can't really provide an URL.

### What happens?

In Microsoft Edgee's Homepage, Adguard Browser extension using Adguard Tracking filter is blocking something with this filter of their: `ntp.msn.com#%#AG_defineProperty("navigator.getBattery",{value:function(){return Promise.resolve()}});`
Correct me if I'm wrong, but looks like Edge is trying to know users laptop battery percentage, which seems a privacy issue to me. I guess that's why Adguard added it to their list.
Should something like this be added to EasyPrivacy?

<details><summary>Screenshots:</summary>

![adg](https://user-images.githubusercontent.com/29574622/155565883-ec7cac8e-bd20-49c9-89c6-3d5a1fbf80ea.png)

![adg2](https://user-images.githubusercontent.com/29574622/155566436-2b6fe11d-d09b-4748-b070-b9e00baad760.gif)

</details><br/>
### List Subscriptions you're using:
Default uBO filters, EasyList, EasyPrivacy, AdGuard URL Tracking Protection.

### Your settings

- OS/version: Windows 11
- Browser/version: Microsoft Edge Latest 98.0.1108.56 
- Adblock Extension/version: uBlock Origin 1.41.2

**Comment by iam-py-test** [comment]
That specific filter can not be added to EasyPrivacy as it is AG specific syntax.
If you mean the homepage which shows up when you go to the New Tab page, I don't think uBlock Origin (or any browser extension) can access it for security reasons.

**Comment by SeriousHoax** [comment]
> That specific filter can not be added to EasyPrivacy as it is AG specific syntax.
> If you mean the homepage which shows up when you go to the New Tab page, I don't think uBlock Origin (or any browser extension) can access it for security reasons.

Yes, the new tab page. Edge's new tab page has some third-party dependencies or something like that. Maybe that's why Both uBlock Origin and Adguard can block things there. 
To check this out, enable Adguard Annoyance on uBlock Origin. Open the log of uBO, load the new tab page, check the logs and you'll see the filter in action. Make sure you have Image of the day enabled on Edge's new tab. You can also import the AG+uBO optimized filter. It also blocks things.
I'm not on my PC at the moment. Otherwise, I would share screenshots.

**Comment by SeriousHoax** [comment]
Here's GIF:
<details><summary>Screenshot:</summary>

![edge](https://user-images.githubusercontent.com/29574622/155564822-b66faf89-cf50-4340-81f4-cf1fc5e33a20.gif)

</details><br/>

**Comment by gwarser** [comment]
Probably iframes

![image](https://user-images.githubusercontent.com/886325/155569715-af7e75bc-1a21-44c7-846e-a5fd77aa90eb.png)

Useless.

**Comment by SeriousHoax** [comment]
> Probably iframes, I see two:
> 
> ![image](https://user-images.githubusercontent.com/886325/155569715-af7e75bc-1a21-44c7-846e-a5fd77aa90eb.png)
> 
> Useless.
> 
> @gorhill ?

Ow! Adguard's log shows type as HTML. Are they the same thing? I'm no expert.
![image](https://user-images.githubusercontent.com/29574622/155570481-c00dee35-3553-46e3-ac22-363b3fae00ed.png)

**Comment by gwarser** [comment]
`debugScriptlets`, `debugScriptletInjector` are not pausing on anything.

**Comment by gwarser** [comment]
Filter is logged on compile time, before being injected.

**Comment by iam-py-test** [comment]
> Ow! Adguard's log shows type as HTML. Are they the same thing? I'm no expert.

Maybe I am confused, but I _think_ AdGuard is showing the content-type (HTML) which uBo is showing the request type (document, iframe, xhr, etc)

**Comment by ryanbr** [comment]
Won't be fixed in EL/EP.
