### ISSUE TITLE
can not load css file - ad-shield.io

### ISSUE THREAD

**Issue by mephi831** [easylist/easylist#10959]
### List the website(s) you're having issues:
- `https://ad-shield.io/home`

### What happens?
The website is broken because the css file cannot be loaded.

### List Subscriptions you're using:
- EasyList General Rule

### Your settings

- OS/version: macOS Big Sur
- Browser/version: Chrome
- Adblock Extension/version: AdGuard

### Other details:
![image](https://user-images.githubusercontent.com/100127953/155067842-c446ffec-5e8a-4eea-a789-d1ce21a7197e.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6976764617fb15ed012047f451ec3d61db508c6b
