### ISSUE TITLE
RapidVideo ads

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#1096]
http://kissanime.ru/Anime/You-re-Under-Arrest-Second-Season/Episode-001?id=103050&s=default

https://www.rapidvideo.com/e/FF2N8WG1DT

Click play button and you notice favicon page?

`https://www.google.com/favicon.ico`

Then after few moments, it will transform:

`https://2d52156c065481.com`

`https://2d52156c065481.com/1/1199241/?var=1561207`

`www.goodtime.tech`

Fanboy Ultimate in use.

**Comment by runboy93** [comment]
Also noticed this page source:

`<script type="text/javascript" src="//ads.2mdnsys.com/qcad.php?did=42&unit=59df4a6465382&tm=1507805796&sid=20&zid=1034&k=59df4a64653d2"></script>
`

`ads.2mdnsys.com` doesn't seem to be on either of Easylist, Fanboy Ultimate list or anywhere.

**Comment by BigGiantHeadsHighCommander** [comment]
see also youtube-dl

https://github.com/rg3/youtube-dl/pull/13348
