### ISSUE TITLE
telegraph.co.uk

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#11]
`http://www.telegraph.co.uk/news/worldnews/centralamericaandthecaribbean/mexico/11992259/Mexican-woman-I-was-raped-43200-times.html`

Dunhill Travel Deals (More from the web)
Outbrain (Promoted stories and Telegraph Sponsored)

Original report: https://forums.lanik.us/viewtopic.php?f=62&t=25847

These filters completely block all ads: https://forums.lanik.us/viewtopic.php?f=62&t=25847&start=30#p85950

**Comment by AlphaT3ch** [comment]
Same issue here on the latest version running Chrome.
Here's the code to fix it:
```telegraph.co.uk##div[class="summary iframeSummary mnIframe"]```

**Comment by monzta** [comment]
Where are those "Dunhill Travel Deals"? 

Not sure why the Outbrain stuff ins't removed in Chrome though. Need to look into this.

**Comment by terrorist96** [comment]
![capture1](https://cloud.githubusercontent.com/assets/12802056/16251620/9ddee2f4-37f5-11e6-9f0e-8c18aa867c81.PNG)

**Comment by monzta** [comment]
@terrorist96 May I ask you from which location you visited the page?

**Comment by terrorist96** [comment]
If you mean what my IP address is, I'm in the USA.

**Comment by AlphaT3ch** [comment]
I'm also still seeing the ads. I'm accessing the page from New York, USA.

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/67a45f1252d6a0cc9564de857b6f10c928f48d60

**Comment by terrorist96** [comment]
@monzta Dunhilldeals are blocked, but I still see Outbrain ads.

**Comment by monzta** [comment]
@terrorist96 https://issues.adblockplus.org/ticket/4171

**Comment by terrorist96** [comment]
@monzta Thanks. Can you please keep this open until it gets resolved then?

Thanks!
