### ISSUE TITLE
patreon.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11006]
### List the website(s) you're having issues:

`https://www.patreon.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox Nightly 99
- Adblock Extension/version: uBO 1.41.7b3

### Other details:

![image](https://user-images.githubusercontent.com/95879668/155444695-96789cef-1d5e-47cb-981c-97b28b726878.png)

**Comment by ryanbr** [comment]
Already blocked?
