### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11005]
### List the website(s) you're having issues:

`https://twitter.com/windows` --- Just as an example.

### What happens?

Annoyance? (Log in / Sign up banner at bottom of screenshot).

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 97.0.2
- Adblock Extension/version: uBO 1.41.9b0

### Other details:

![image](https://user-images.githubusercontent.com/95879668/155439541-cb20da68-13f4-4dac-ad03-589937a88a57.png)

**Comment by ryanbr** [comment]
Won't break logins.

**Comment by Rudxain** [comment]
https://github.com/Rudxain/uBO-rules/blob/731adb67100e37d9dce5ffe9f3717c9c379c856f/rx.abp#L9-L10
