### ISSUE TITLE
www.thurrott.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11001]
### List the website(s) you're having issues:

`https://www.thurrott.com/`

### What happens?

1. Cookie Notice
2. Ad / Annoyance?
3. Ad / Annoyance?

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox Nightly 99
- Adblock Extension/version: uBO 1.41.7b3

### Other details:

![image](https://user-images.githubusercontent.com/95879668/155368347-b350a076-dfe7-4b3e-a715-343359823fcd.png)

**Comment by ryanbr** [comment]
Cookie message should already be blocked, maybe cache and update?

For the rest: https://github.com/easylist/easylist/commit/b326f36b92de1cd939e3dc9faca150706d3c0e97

**Comment by q1800** [comment]
My apologies about the cookie message. It is already blocked. Many thanks!
