### ISSUE TITLE
Closing after much discussion.  It's not like Youtube, or Vimeo. User content being made not specifically for advertising (products/websites/services/etc). Youtube is just user content embedded video, it's primary function. To call any invideo advertising "it's like youtube" misses the point, and its often used a defense by invideo providers not wanting to be blocked.

### ISSUE THREAD

**Issue by SyedSan1** [easylist/easylist#11054]
Closing after much discussion.  It's not like Youtube, or Vimeo. User content being made not specifically for advertising (products/websites/services/etc). Youtube is just user content embedded video, it's primary function. To call any invideo advertising "it's like youtube" misses the point, and its often used a defense by invideo providers not wanting to be blocked.

Not to say we haven't seen websites sites use youtube.com to embed a "video advert". Which we also blocked in Easylist. But that is an exception to the rule, very rarely have I see this occur recently. So rare I can't actually recall the last time this occurred.

Firework isn't the only invideo advertising service being blocked in Easylist (no doubt we'll add more over time). Invideo advertising can't be made "Easylist Compliant".  If we allow one service this would open the doors for others.

_Originally posted by @ryanbr in https://github.com/easylist/easylist/issues/9588#issuecomment-979060440_

**Comment by SyedSan1** [comment]
Reopening this issue as we have seen the right way to solve this problem. Recently, AdGuard correctly solved this problem [here](https://github.com/AdguardTeam/AdguardFilters/issues/111021).

Following is how AdGuard solved this:
1) Firework's content videos by themselves don't count as adverts, they don't lead to some outside advertiser.  (they can be rather annoying though, see point 3).
2) There are ad videos that are mixed into the feed which can be successfully blocked by blocking one ad domain.
3) Some of the Firework's videos can be counted as an "annoyance"

AdGuard is blocking the ads (#2) and allowing the content videos (#1) to work.
We can work with you to help identify anything that you'd consider as #3 "annoyance" to help resolve this issue.

Please let us know if this is acceptable to you @ryanbr ?

**Comment by Khrin** [comment]
Already resolved.
