### ISSUE TITLE
1337x.to (Ad)

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#11051]
### List the website(s) you're having issues:
`https://1337x.to/popular-apps`

### What happens?

Advertise

<details><summary>Screenshot:</summary>

![z](https://user-images.githubusercontent.com/29574622/155845743-b98f93ee-06dd-4c8d-8a09-afff48d873cd.png)

</details><br/>
### List Subscriptions you're using:

Default uBO, EasyList, EasyPrivacy, Fanboy's Annoyances, Anti-Facebook
### Your settings

- OS/version: Windows 11
- Browser/version: Firefox 97.0.1
- Adblock Extension/version: uBO 1.41.8

### Other details:
Adguard Base solving it with: `||1337x.to/images/x28.jpg` rule.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/8f8f8d3e921e908df9f664add99179e1c96a80c6
