### ISSUE TITLE
gmail.com

### ISSUE THREAD

**Issue by hawkeye116477** [easylist/easylist#1105]
### List the website(s) you're having issues:

`https://www.google.com/intl/en_uk/gmail/about/`

### What happens?
Social icons on bottom.

### List Subscriptions you're using:
Fanboy's Social Blocking List

### Your settings

- OS/version: Manjaro Linux Hakoila
- Browser/version: Waterfox 56.1.0
- Adblock Extension/version: Nano Adblocker 1.0.0.42

### Other details:

@ryanbr Can you add `google.com##.standard-footer__bar__social-icons, .gplus`?

**Comment by BigGiantHeadsHighCommander** [comment]
#deleteGoogle 👍 

https://mail.zoho.com

email, CalDAV, CardDAV

**Comment by peace2000** [comment]
I don't see social icons on that link nor I see an element that goes by that name. Google has probably changed things.

@Khrin

**Comment by hawkeye116477** [comment]
Yeah, Google+ was removed some time ago.
