### ISSUE TITLE
businessinsider.in

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#11052]
### List the website(s) you're having issues:
`https://www.businessinsider.in/tech/news/russia-ukraine-war-anonymous-hackers-launch-cyberwar-against-russia-taking-down-government-websites/articleshow/89817168.cms`

### What happens?

Ad placeholders. There are  more than one in the page. Scroll down to check them all.
<details><summary>Screenshots:</summary>

![c](https://user-images.githubusercontent.com/29574622/155847638-54e44a57-060c-4168-bece-383e57b5fade.png)
![v](https://user-images.githubusercontent.com/29574622/155847639-40b400a1-8f3f-4829-8248-07158e90773d.png)
![b](https://user-images.githubusercontent.com/29574622/155847640-f50bb29c-8648-452e-af45-cbb9e9a216fa.png)

</details><br/>
### List Subscriptions you're using:

Default uBO, EasyList, EasyPrivacy, Fanboy's Annoyances, Anti-Facebook
### Your settings

- OS/version: Windows 11
- Browser/version: Firefox 97.0.1
- Adblock Extension/version: uBO 1.41.8

**Comment by ryanbr** [comment]
Looks good here, closing.

**Comment by SeriousHoax** [comment]
@Khrin @felippesantos46 Can you guys have a look? I'm still seeing those empty placeholders.

**Comment by Yuki2718** [comment]
Not fully fixed
