### ISSUE TITLE
patreon.com [Re-Open Issue #11006] - Cookie Notice Is Not Blocked - See New Screenshot Included

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11066]
### List the website(s) you're having issues:

`https://www.patreon.com/`

### What happens?

Cookie Notice

**NOTE:** The previous issue #11006 I opened was closed with the assumption that the Cookie Notice I mentioned was already blocked. The Cookie Notice is not blocked. I have included a new screenshot below showing the issue still happening and also my exact filter list page setup in uBO. I have all the default lists in uBO enabled plus all of the EasyList / Fanboy Lists enabled that are included with uBO. I have force refreshed all the lists and restarted the browser as well.

Can someone please take another look into this? Thank you.

### List Subscriptions you're using:

See Screenshot below.

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox Nightly 99
- Adblock Extension/version: uBO 1.41.9b0

### Other details:

![image](https://user-images.githubusercontent.com/95879668/155890609-215a8de6-c93a-41af-9633-c1cedcf5e7db.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e1538d25616759a34f634d1dde15fd46b8000ee8 Okay, does this help?

**Comment by q1800** [comment]
Yes, absolutely! That does indeed take care of the problem. Thank you! 👍
