### ISSUE TITLE
`cint.com^$third-party` is probably too aggressive

### ISSUE THREAD

**Issue by Malvoz** [easylist/easylist#11063]
I believe that the following is too aggressive / lacks real motivation:

https://github.com/easylist/easylist/blob/0e90ecdb35bc5209c6d652e37bd7ba18ae65f765/easyprivacy/easyprivacy_trackingservers.txt#L620

https://github.com/easylist/easylist/blob/0e90ecdb35bc5209c6d652e37bd7ba18ae65f765/easyprivacy/easyprivacy_trackingservers.txt#L621

Re https://github.com/easylist/easylist/issues/354:

> "Welcome to the world’s insights exchange. Technology that transforms and accelerates how companies gather insights" - https://www.cint.com/

Cint is not a tracking software, it is a survey respondent platform. It allows companies to gather insights through incentivized surveys which people choose to partake in.

The use case is survey panels which require iframe embeds with user-facing UI, such as on https://tyckomtv.se/logga-in/ (Swedish site).

**Comment by ryanbr** [comment]
We don't track, but we `accelerates how companies gather insights`.

**Comment by ryanbr** [comment]
Okay removed cint.com: https://github.com/easylist/easylist/commit/3fd4ef4c74375290a9ec6d0edfc7f1cccbcbf56d

**Comment by Malvoz** [comment]
Thanks @ryanbr!
