### ISSUE TITLE
Issue with /services/analytics/* pattern

### ISSUE THREAD

**Issue by alphabetek** [easylist/easylist#1109]
### List the website(s) you're having issues:

https://us.cloud.talend.com

### Describe the issue

1- Create a trial account 
2- Log into the app and launch Management Console app
3- Navigate to "Subscription" menu

Two URLs are being blocked:

https://tmc.us.cloud.talend.com/api/ipaas/services/analytics/engines/credit
https://tmc.us.cloud.talend.com/api/ipaas/services/analytics/engines/status

### Screenshot(s)

![ublock](https://user-images.githubusercontent.com/5899023/39407200-812766da-4bc2-11e8-95df-47d3e36811ca.png)

### Versions

- Browser/version: Chrome and FF
- uBlock Origin version: 1.16.0

### Notes
The pattern /services/analytics/* is very generic and could be used by any organization.
Ublock Debugger shows that the links are being blocked by easyprivacy rules, line to be removed:
 https://github.com/easylist/easylist/blob/d0a67e61ee7ba1f066f11070babf13fac035e716/easyprivacy/easyprivacy_general.txt#L2629

**Comment by Khrin** [comment]
Does adding this whitelist filter is helpful for you? `@@||cloud.talend.com/api/ipaas/services/analytics/$script,~third-party`

**Comment by alphabetek** [comment]
@Khrin I'm afraid it doesn't work.
Issue is faced by other users reporting this and they don't know it is being blocked by uBlock, so I'm not sure adding a whitelist filter in end user side is the right solution.

**Comment by Khrin** [comment]
Ok, then this change should work instead.
