### ISSUE TITLE
instagram.com & facebook.com - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#11099]
### List the website(s) you're having issues:

- `https://instagram.com`
- `https://facebook.com`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.1
Browser/version: Chrome 97
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/156146486-d06c7feb-d401-456b-a1f7-dc9c8ad86f22.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/156146617-261fd57a-a42c-4d5a-94fe-076e35b0caa7.png">

**Comment by krystian3w** [comment]
This need to accept, becasue lock load older post on main wall (logged users)/fanpages.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/issues/11005
