### ISSUE TITLE
Doubleclick ads and promoted stories not blocked on pcmag.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#111]
`http://www.pcmag.com/article2/0,2817,2500086,00.asp`

Give it about 10-20 seconds to load.
2 ads on the right.

Oh, and promoted stores POWERED BY ZERGNET at the bottom.

**Comment by monzta** [comment]
Seems to be gone.

**Comment by terrorist96** [comment]
@monzta I currently see a banner ad and the ZERGNET promoted stories at the bottom on Chrome.

**Comment by monzta** [comment]
Not appearing there for me. :/

**Comment by terrorist96** [comment]
I just tried on a new Chrome profile with only ABP installed. I see the doubleclick banner ad, the ZERGNET ads at the bottom and though I don't see the ads on the right anymore, there's also "Related Topics" ads with an example URL being: 

`http://834917445.keywordblocks.com/Presentation_Projectors.cfm?&vsid=1263335283588706&vi=1483331738483740054&dytm=1483331928229&kbbq=%26sde%3D1%26adepth%3D1%26ddepth%3D1&tdAdd[]=%7C%40%7Csde%3D1%7C%40%7Cadepth%3D1%7C%40%7Cddepth%3D1&verid=121199&hvsid=00001483331926276029072695096943&upk=1483331925.47&sttm=1483331926276&=&kp=1&kbc=58091&kt=266&ki=23083293&ktd=1375489063256380&kbc2=0&fdkt=266&oref=http%3A%2F%2Fwww.pcmag.com&fp=0n12xEuQCr1Uy8-Oyjm2dtiIeouKz-42LnvwVP5v9CL5rBbEkiAwaT7fUDh-GR0nukelM5jIeV7PmjbQ78cRnwnUmR1t_b4vlP_lTkRRzag4rzCyvzc0RQ%3D%3D&c=SbIDXAM3blGTn6pWVl_Z6Q&cme=yl2SRicu_VXjuD7LPKlMmo-fwAy7Mtfd8yXhh_z1M31XiddT4JAm-mVmnH0tHu5wEP_xpW1yT-tjwXJ-mK-nDyf37U28RHfsKlUg7TbV1RnrH7vlAmLseyhFM7hsGv9Q8Dw0IolwU_pI0F0Y8eXXIWIvlO4Z7EK3BbGtJPbi5kCPhDPPfHq9xe2iT7lS3w_Q%7C%7CSKuUSfCLRUlNpF0kfyfqhmofrP9J7U7P%7C5gDUJdTGiJzedmq9hanWYg%3D%3D%7CN7fu2vKt8_s%3D%7CUzIRyxpEc7HI4fHh3OLipCmCpC24Tpz8c7uJHqfAPtvBgR7_2Jw1n5clj-FDqRGtcln2xDJjxPV0Qktkh-1mkBPNfGkkJrmz-cAsah4yje4eb1peJ59S3SoLYPz_SLYmeoLTqG72zZ0ajBc1CiQwTyeb0ojDs9Kefi2zwu9flfQ%3D%7CJf0d-WoAdPvB4PrDJZeiaT4lsL_dgC4dERw4sNYyZ28%3D%7CaWvHkslLNooyC7dqvjMSAIkCV9HwojclR220HvvWcCscm5LNcMoi3-hbvUgcOvY97ydTJxIEEmI%3D%7C&ib=0&cid=8CUSTYQ1J&crid=486383188&size=750x175&lpid=&tsid=1283&ksu=142&chid=200494174&https=0&extKwds=0&kwdsMaxTm=400&ugd=4&maxProviderPixel1=&maxProviderPixel2=&rms=1483331929&&abpl=2&kct=75990`

Oh wow, I think this may be where the site will load differently if it noticed the console is open, so ads don't load when the console is open. See here for the interesting discussion:
https://github.com/uBlockOrigin/uAssets/issues/227

**Comment by monzta** [comment]
Do these filters work for you? 

```
@@|http://$image,third-party,domain=pcmag.com
@@|https://$image,third-party,domain=pcmag.com
@@||pcmag.com^$generichide
```

**Comment by terrorist96** [comment]
Unfortunately, no, they don't work for me.
