### ISSUE TITLE
twitter.com - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#11100]
### List the website(s) you're having issues:

- `https://twitter.com`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.1
Browser/version: Chrome 97
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/156147466-a2cfeb75-3853-4c14-baaf-d43de609da67.png">

**Comment by krystian3w** [comment]
test:

```
twitter.com#?##layers > div[class*="css-"][class*=" r-"] > div:last-child > div:only-child > div:only-child > div:only-child:-abp-has( > div:not(:only-child) > div:not(:only-child) > span:only-child > span:only-child:-abp-contains(your choices))
```

**Comment by ryanbr** [comment]
Left alone since its so problematic, and likely breaks the site everytime they change it
