### ISSUE TITLE
Small ad on megagames.com

### ISSUE THREAD

**Issue by Felipefpl** [easylist/easylist#11108]
small ad for screensnipe, it's displayed in all pages:

https://megagames.com/

**Comment by THEtomaso** [comment]
`megagames.com#?#.block:-abp-has(a[href*="screensnipe.com"])`

**Comment by krystian3w** [comment]
Maybe id "4" are stable, then Sweeden list like:

`###block-block-4`
or
`##.block-block-4`

Maybe footer rare have many blocks then works:

`##.block-region-footer:last-child`

**Comment by THEtomaso** [comment]
> Maybe..

I wouldn't recommend it.
Sooner or later, such rules will probably end up breaking something!

**Comment by krystian3w** [comment]
In ABP can blink with -abp-.
