### ISSUE TITLE
diyperks.com - Cookie notice broken

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#11116]
### List the website(s) you're having issues:

- `https://diyperks.com/`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.1
Browser/version: Chrome 97
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/156366780-6dfa6e96-2c1e-4026-a342-84ef2d6bd499.png">

**Comment by ryanbr** [comment]
Not seeing this issue @alexm92  Is it still occuring?

**Comment by ryanbr** [comment]
Free to re-open, re-test. I checked again, looking good in Brave
