### ISSUE TITLE
newyorker.com 

### ISSUE THREAD

**Issue by prodan1234** [easylist/easylist#1114]
```
newyorker.com 
```

Ads to subscribe to the magazine are not blocked. [This](https://imgur.com/a/j2fIVs9) is what it looks like with easylist enabled.

OS/version: macOS 10.13.4
Browser/version: Chrome 67.0.3396.18 
Adblock Extension/version: uBlock Origin 1.16.2

**Comment by Khrin** [comment]
This looks like to be self-romotion and will not be blocked by EasyList, but seems to be a good candidate for the Annoyances List.
