### ISSUE TITLE
prothomalo.com (ads and ads leftovers)

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#11149]
### List the website(s) you're having issues:
`https://www.prothomalo.com/`

### What happens?

ads and ads leftovers
### List Subscriptions you're using:

Default uBO, EasyList, EasyPrivacy, Fanboy's Annoyances, Anti-Facebook
### Your settings

- OS/version: Windows 11
- Browser/version: 97.0.1
- Adblock Extension/version: uBO 1.41.8

### Other details:

![1](https://user-images.githubusercontent.com/29574622/156877132-9c6f1188-94cd-4e42-b944-c27ee1920c38.png)
![2](https://user-images.githubusercontent.com/29574622/156877146-bfba97c5-3d6b-42d9-b9a3-39ca006d4ff3.png)

**Comment by Khrin** [comment]
For sites in one of the India's languages, please ask to https://github.com/mediumkreation/IndianList
