### ISSUE TITLE
surfshark.com (Cookie Notice)

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#11152]
### List the website(s) you're having issues:
`https://surfshark.com/blog/free-fake-news-warning-feature`

### What happens?

Cookie Notice
### List Subscriptions you're using:
Default uBO, EasyList, EasyPrivacy, Fanboy's Annoyances, Anti-Facebook

### Your settings

- OS/version: Windows 11
- Browser/version: Microsoft Edge
- Adblock Extension/version: uBO 1.41.8

### Other details:
![co](https://user-images.githubusercontent.com/29574622/156894605-2645efbd-ede4-463c-a9b9-e4d43591d24a.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b5cad11438279e24cc79bc3224eb5d195b139799

**Comment by krystian3w** [comment]
I found these domain:

`surf-chiny.com` - IMO mirror.
