### ISSUE TITLE
versus.com

### ISSUE THREAD

**Issue by Lemonadez** [easylist/easylist#11153]
### List the website(s) you're having issues:

`https://versus.com/en/samsung-galaxy-a51-vs-samsung-galaxy-a72`

### What happens?

When You compare phones and then when you scroll down, the page itself "Hide".

### List Subscriptions you're using:

Just Using Easylist 

### Your settings

No Other Extension just Ublock Origin Latest 1.41.8.

- OS/version: Windows 11
- Browser/version: Firefox / Edge (Chromium) version (Latest)

Using Latest Ublock Origin from Firefox and Chrome Addon.

**Comment by ryanbr** [comment]
No issues here.

**Comment by Lemonadez** [comment]
Here the video of my Firefox. even on my Chromium Browser like Edge. Have this problem
`https://streamable.com/hndqea`

**Comment by krystian3w** [comment]
Maybe need report into Microsoft and Mozilla only.

**Comment by ryanbr** [comment]
I tested in Edge/Firefox. Didn't see this issue, What other subs are enabled? does enabled all the default uBO subs help?

**Comment by Lemonadez** [comment]
I dont have any other subs enabled.
`https://i.imgur.com/kQa2wyj.png`

My Rules is also default and My Filters are empty.
```
no-large-media: behind-the-scene false
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop
```

**Comment by krystian3w** [comment]
Maybe Geo IP bug, try use many VPN to mask your country.

**Comment by ryanbr** [comment]
Maybe paste a screenshot of blocked items?

**Comment by ryanbr** [comment]
Closing, no further responses.
