### ISSUE TITLE
NSFW - tube8.com / tube8.fr / tube8.es

### ISSUE THREAD

**Issue by Lairub** [easylist/easylist#11154]
Orgin: https://github.com/uBlockOrigin/uAssets/issues/12077

I found bad working filter:

https://github.com/easylist/easylist/blob/5a82b843e1cc7da790e2e85bd1c0f6fe78095d83/easylist_adult/adult_specific_hide.txt#L572

Hide sections under video like:

 *   Related
 *   Newest Ebony
 *  Channel

demo NSWF url: `https://www.tube8.com/ebony/ebony-cali-calientes-training-turns-to-gangbang/81843551/`

IMO filter may need a little update if still are needed.

**Comment by Tube8-troubles** [comment]
https://github.com/easylist/easylist/commit/401c6cbfa09b464a82532a128c5e1c034e02879f

**Comment by Lairub** [comment]
Maybe almost all videos use blob to procet easy copy videos:

https://github.com/uBlockOrigin/uAssets/issues/12077#issuecomment-1100753092
