### ISSUE TITLE
[NSFW] video.laxd.com/a/

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11155]
### List the website(s) you're having issues:

`https://video.laxd.com/a/` - Screenshot 1

`https://video.laxd.com/a/content/202105311AP1x0r1` - Screenshot 2

`https://video.laxd.com/a/trend` - Screenshot 3

### What happens?

Ads / Annoyances - See screenshots below.

**NOTE:** You may have to refresh the webpages several times to get all the ads to show as they appear in the screenshots below.

### List Subscriptions you're using:

uBO default lists
Anti-Facebook
EasyList Cookie
Fanboy’s Annoyance
Fanboy’s Social
uBlock filters – Annoyances

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 97.0.2
- Adblock Extension/version: uBO 1.41.9b0

### Other details:

<details>
<summary>Screenshot 1</summary>

[https://user-images.githubusercontent.com/95879668/156933904-edb732cc-4d67-4544-84a9-42a38ad36bb7.png](https://user-images.githubusercontent.com/95879668/156933904-edb732cc-4d67-4544-84a9-42a38ad36bb7.png)

</details>

<details>
<summary>Screenshot 2</summary>

[https://user-images.githubusercontent.com/95879668/156933667-7ee4e04f-e25a-4ad7-a5e5-dee2896a62b3.png](https://user-images.githubusercontent.com/95879668/156933667-7ee4e04f-e25a-4ad7-a5e5-dee2896a62b3.png)

</details>

<details>
<summary>Screenshot 3</summary>

[https://user-images.githubusercontent.com/95879668/156961700-37e1c45d-a724-4776-9157-b0fe3e29a6f9.png](https://user-images.githubusercontent.com/95879668/156961700-37e1c45d-a724-4776-9157-b0fe3e29a6f9.png)

</details>

**Comment by Yuki2718** [comment]
Indeed they're half self-promo and half ads. Will be blocked in Japanese filters, but it'll be okay to be blocked in Annoyances filters too.

**Comment by q1800** [comment]
Hi @Yuki2718,

Thank you for your help on this. I hope I can ask a few clarifying questions.

I see that your fixes for this go into the Adguard Filters. I also believe that EasyList doesn't have a dedicated Japanese filter list themselves.

Will the fixes for this also be implemented into any EasyList / Fanboy filters?

Is there some standard procedure to have different list groups (brands) cross-talk to each other? (What I mean is if Adguard Filters get a specific fix, is there an automatic or manual way that these fixes also get put into the EasyList / Fanboy filters?). Or is the duplication of such fixes discouraged between different filter groups (brands)?

**Comment by Yuki2718** [comment]
> Will the fixes for this also be implemented into any EasyList / Fanboy filters?

I internally talked with an EL maintainer about this and they may be added to Fanboy Annoyance as well but it's his decision eventually.

> Is there some standard procedure

We cross-talk every day, but usually it's mostly about issues reported to the one yet to be fixed in another. There's no regular procedure an issue affecting both parties to be shared, imagine how many issues we address every day. That said, some high-impact issues or intersitng issues may be shared.

**Comment by q1800** [comment]
@Yuki2718,

I understand. Thank you for the extra clarification and how the behind the scenes works!

Have a great day! 👍
