### ISSUE TITLE
di.fm

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11158]
### List the website(s) you're having issues:

`https://www.di.fm/`

### What happens?

Ad Placement Leftover

### List Subscriptions you're using:

uBO default lists
Anti-Facebook
EasyList Cookie
Fanboy’s Annoyance
Fanboy’s Social
uBlock filters – Annoyances

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 97.0.2
- Adblock Extension/version: uBO 1.41.9b0

### Other details:

![image](https://user-images.githubusercontent.com/95879668/156963837-ca14de6d-6688-4950-889c-8c4fb58cb0c0.png)

**Comment by ryanbr** [comment]
Looks fine here, maybe force an purge/update of the lists

**Comment by q1800** [comment]
Hi @ryanbr,

Can you verify if you even see the box I have highlighted in the screenshots of the webpage or is it not showing for you at all? I am in the US. Maybe it is a regional / location based ad server / network? I really don't know what is the actual issue, but I am not able to get rid of that ad placement leftover box.

I have verified in a new, fresh profile in both Microsoft Edge 99 & Firefox 98 that I still see the same behavior as reported above.

I have forced a purge / update of all the lists in both browsers.

I have included screenshots for both browsers and filter list setups.

Windows 10
Microsoft Edge 99
uBO 1.41.8

![di-fm-edge](https://user-images.githubusercontent.com/95879668/157161356-ed546011-fae4-47bd-84a7-993161977b88.png)

![ublock-edge](https://user-images.githubusercontent.com/95879668/157161369-8907604b-d7ff-4bff-8647-3df3f625dac2.png)

Windows 10
Firefox 98
uBO 1.41.9b0

![di-fm-ff](https://user-images.githubusercontent.com/95879668/157161401-642d5fcf-426b-4456-97d0-335aef75b6d4.png)

![ublock-ff](https://user-images.githubusercontent.com/95879668/157161413-a61eb311-0e3c-45b7-899d-3f03d4396b7c.png)
