### ISSUE TITLE
masterani.me new popup

### ISSUE THREAD

**Issue by ArbitraryFox** [easylist/easylist#1116]
There is a new popup ad that will appear momentarily and close immediately, URL was `http://35.184.188.211/MTAxODIyMDg0MjIzLzEwMTgyMzE1NzQ3Mi8wbjU3MHcxdzJ0`. If you go to the site linked below, used the stream.moe or openload hosts, the popup will appear upon clicking play.

`https://www.masterani.me/anime/watch/2837-uma-musume-pretty-derby-tv/6`

uBlock Origin logger caught this:
![screenshot from 2018-05-01 16-27-13](https://user-images.githubusercontent.com/29243416/39466694-cdfabfde-4d5c-11e8-9af7-2667916e7059.png)

And upon clicking the video player that launches the popup:
![screenshot from 2018-05-01 16-27-31](https://user-images.githubusercontent.com/29243416/39466714-e61fa340-4d5c-11e8-92fc-8f409c97ae93.png)

I'm on uBlock Origin for Chrome Stable running:
1. All uBlock filters
2. EasyList
3. EasyPrivacy
4. StevenBlack's Hosts

I'm not using any other blocking/privacy extensions.

**Comment by ryanbr** [comment]
Expected, popup gone due to filter, because its an advert (IP based site)
