### ISSUE TITLE
cnn.com

### ISSUE THREAD

**Issue by PerfectSalad** [easylist/easylist#11178]
Advertising on `https://www.cnn.com/` -- encountered with a US IP.

**Comment by ryanbr** [comment]
Fine with me, no issues with the homepage and articles.

**Comment by PerfectSalad** [comment]
@ryanbr Did you encounter "Paid Partner Content"?

**Comment by ryanbr** [comment]
Closing, no further details or debug info.

**Comment by AmCarte** [comment]
@ryanbr @Khrin Could you please see if you can encounter "Paid Partner Content" on `https://www.cnn.com/` with a USA IP address?
