### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by alexkoala** [easylist/easylist#1119]
### List the website(s) you're having issues:
[https://www.twitch.tv/ninja](https://www.twitch.tv/ninja)
[https://player.twitch.tv/?channel=ninja](https://player.twitch.tv/?channel=ninja)
and all channels.

### What happens?
When I turn off easylist, it shows like this.

> **Ninja**
> (description)
> playing Fortnite for 100,000 viewers

but when I use easylist, it shows like this.
> (description)
> playing for 100,000 viewers

and also easylist removes profile images in player.

This issue is on all channels and all languages.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10/1803(17134.1)
- Browser/version: Chrome/66.0.3359.139
- Adblock Extension/version: uBlock Origin/1.16.2

### Other details:

**Comment by monzta** [comment]
Thanks, removed https://github.com/easylist/easylist/commit/4a07ba0a314f0025b1119ad6ef6a4d9c98a756e9
