### ISSUE TITLE
EasyPrivacy breaks O2 coverage checker

### ISSUE THREAD

**Issue by AlecRobertson** [easylist/easylist#112]
EasyPrivacy breaks the O2 UK coverage checker (http://www.o2.co.uk/coveragechecker): the map isn't rendered correctly.

![screen shot 2016-08-12 at 09 22 37](https://cloud.githubusercontent.com/assets/4457688/17616821/6b59a930-606e-11e6-9bcf-a3e9e87416c7.png)

What it should look like:

![screen shot 2016-08-12 at 09 23 35](https://cloud.githubusercontent.com/assets/4457688/17616834/793ce314-606e-11e6-960c-fc5b43a7c6c9.png)

**Comment by Daniel15** [comment]
It's caused by this rule:
```
||virtualearth.net^*/loggingservice/
```

It seems like this service authenticates to Virtual Earth / Bing Maps in addition to being used for logging.

**Comment by monzta** [comment]
This should fix it: https://github.com/easylist/easylist/commit/121f086089eab96b421c6617b1a9a314759ee971

**Comment by AlecRobertson** [comment]
Can confirm this is now fixed. Thanks!
