### ISSUE TITLE
https://sbplay2.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#11210]
### List the website(s) you're having issues:
https://sbplay2.com/e/nkud0jt6sfmc
https://www1.cuevana3.cx/ (streamSB proxy)

### What happens?
(Broken) Video cannot be played.

**Comment by mapx-** [comment]
Video running well here using uBlock Origin.
Popups on peliplus fixed => https://github.com/uBlockOrigin/uAssets/commit/a9fe31d48b247403114d6b5a5744c1047ed4334e

**Comment by Khrin** [comment]
Apparently has been fixed by the site itself.
