### ISSUE TITLE
di.fm [Re-Open Issue #11158]

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11226]
### List the website(s) you're having issues:

`https://www.di.fm/`

### What happens?

The previous issue #11158 I opened was closed with the suggestion to force update filter lists. The filters lists were already force updated when the initial report was made. The Ad placement leftover box is still present on the webpage.

Can you tell me if you even see the box I have highlighted in the screenshots of the webpage or is it not showing for you at all? I am in the US. Maybe it is a regional / location based ad server / network? I really don't know what is the actual issue, but I am not able to get rid of that ad placement leftover box.

**NOTE:** This was retested in a new, fresh profile in both Firefox 98 & Microsoft Edge 99. All filter lists were force updated. I have included screenshots for both browsers and filter list setups to dispel any further uncertainties.

Can someone please take another look into this? Thank you.

### List Subscriptions you're using:

See screenshots below.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 98 / Microsoft Edge 99
- Adblock Extension/version: uBO 1.41.9b0 / uBO 1.41.8

### Other details:

Windows 10
Firefox 98
uBO 1.41.9b0

![di-fm-ff](https://user-images.githubusercontent.com/95879668/157161401-642d5fcf-426b-4456-97d0-335aef75b6d4.png)

![ublock-ff](https://user-images.githubusercontent.com/95879668/157161413-a61eb311-0e3c-45b7-899d-3f03d4396b7c.png)

Windows 10
Microsoft Edge 99
uBO 1.41.8

![di-fm-edge](https://user-images.githubusercontent.com/95879668/157161356-ed546011-fae4-47bd-84a7-993161977b88.png)

![ublock-edge](https://user-images.githubusercontent.com/95879668/157161369-8907604b-d7ff-4bff-8647-3df3f625dac2.png)

**Comment by Khrin** [comment]
Correctly blocked here. 

Please don't reopen the issue, as it's a your problem, perhaps something faulty with Ublock Origin, EasyList's fine.
