### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by adbloc** [easylist/easylist#1125]
### List the website(s) you're having issues:
```
https://www.msn.com/en-us/tv/news/%E2%80%98x-force%E2%80%99-tj-miller-won%E2%80%99t-be-in-%E2%80%98deadpool-2%E2%80%99-spinoff-ryan-reynolds-confirms/ar-AAwLkhE
```

### What happens?

Click on any link in the article. Nothing happens.

### List Subscriptions you're using:

standard Easylist, tracking blocking and social blocking.

### Your settings

- Windows 10
- Chrome latest
- Adblock latest edition

### Other details:
same problem with msn new tab extension.

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/a16ab54677e0e2d8cbb91cf285b011ed7af043c8
