### ISSUE TITLE
Ads from nytive.com and yengo.com

### ISSUE THREAD

**Issue by kowith337** [easylist/easylist#1126]
### List the website(s) you're having issues:
`https://www.isranews.org/isranews-scoop/65068-sms05.html`

### What happens?
- `nytive.com` and `yengo.com` is regional (Thai) third party ads, interface is likely article suggestions
- None of any lists blocked two hosts, even hosts file and built-in tracking protection (e.g. Mozilla Firefox private browsing, DuckDuckGo App, Firefox Klar)

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/16535467/39669339-399d5058-5113-11e8-82d5-bb1095e730b7.png)

### Your settings
- OS/version: Windows 10 April Update
- Browser/version: Chromium 68.0.3399.0 (dev-codecs-nosync)
- Adblock Extension/version: NanoAdBlocker 1.0.0.45
- Out-of-box default
- uMatrix installed, but turned off to test with NanoAdblocker

### Other details:
**Ads Placeholder**
![Ads placeholder](https://user-images.githubusercontent.com/16535467/39669433-bbcdc51a-5115-11e8-93f9-9ac97ec4cd52.png)

**Expected after blocked**
![Expected](https://user-images.githubusercontent.com/16535467/39669437-da08d86c-5115-11e8-80b7-095b879d5905.png)

**Comment by monzta** [comment]
Our [policy](https://easylist.to/pages/policy.html) states: 

> Coverage: Filters should only be added for English websites; supplements support other languages. 

You should add [ABPVN](http://abpvn.com/) for Thai sites.

@abpvn Could you please block these ads in your filter list?

**Comment by abpvn** [comment]
@monzta Sorry ABPVN only support Vietnamese website. Not Thai site
