### ISSUE TITLE
gogoanime.gg

### ISSUE THREAD

**Issue by git-101-collab** [easylist/easylist#11268]
### List the website(s) you're having issues:

```
https://gogoanime.gg/wan-yu-feng-shen-episode-25
https://gogoplay1.com/videos/shikkakumon-no-saikyou-kenja-episode-10
```

### What happens?

Pop up and ads when choosing vidstream server (default).

### List Subscriptions you're using:

<details>

![list](https://user-images.githubusercontent.com/83709703/158025373-77798796-3b24-4dc3-8568-014cbd012fdc.png)

</details>

### Your settings

- OS/version: 
- Browser/version: Mozilla Firefox 98.0
- Adblock Extension/version: uBlock Origin 1.41.9b1

### Other details:

It seems they keep changing domains for this purpose:

`||uwbcefluof.com^`
`||mlnyndkde.com^`
`||untvwqvrk.com^`
`||nxwipuoybxc.com^`
`||slbtwnuj.com^`
`||glcqfurkygcrni.com^`
`||fgbsrtolbscjy.com^`
`||qyhshcrwqvaft.com^`
`||aqmgnoik.com^`
`||rgfftupf.com^`
`||fxhpaoxqyajvmdg.com^`

![image](https://user-images.githubusercontent.com/83709703/158025509-af8a3d40-3146-45b3-82b1-20242a88a208.png)

![image2](https://user-images.githubusercontent.com/83709703/158025519-e2f86132-083c-4da9-9079-243c758b86f6.png)

<details><summary>Logger output</summary>

![logger](https://user-images.githubusercontent.com/83709703/158025523-ab7e3e12-974c-41ae-8af3-d65cf61f7867.png)

![logger2](https://user-images.githubusercontent.com/83709703/158025730-7a5dcf2e-7728-479b-8e0a-aa6ce35ea879.png)

![logger3](https://user-images.githubusercontent.com/83709703/158028427-9e3e3095-40e9-434a-871e-fd2e16b18486.png)

**Comment by ghajini** [comment]
update your ublock filters & use default settings

**Comment by git-101-collab** [comment]
> update your ublock filters & use default settings

done. still the same, after reloading the page a few times or switching videos it keeps appearing

<details>

![logger4](https://user-images.githubusercontent.com/83709703/158053885-c883b0bb-4737-4b44-8706-5fbd1399aa9e.png)

![logger5](https://user-images.githubusercontent.com/83709703/158054114-58244609-345b-4b74-a22c-97052f467d1f.png)


</details>

**Comment by ghajini** [comment]
ok i can reproduce
switching different videos brings back propeller
add

`gogoplay4.com##+js(aost, Math.random, /\st\.[a-zA-Z]*\s/)`

**Comment by git-101-collab** [comment]
> add
> 
> `gogoplay4.com##+js(aost, Math.random, /\st\.[a-zA-Z]*\s/)`

thanks, this worked

**Comment by ghajini** [comment]
next time you have

Issues involving


ad-reinsertion

anti-adblock

contextmenu blockage

copy/cut/paste blockage

popups/popunders

site breakage

video ads

open issue here
 `https://github.com/uBlockOrigin/uAssets/issues`
