### ISSUE TITLE
infomaniak.com cookie consent not blocked

### ISSUE THREAD

**Issue by D4v1dH03** [easylist/easylist#11265]
I am using Brave Nightly Android, however even with Easylist cookies as the default list browser flag enabled and shields set to aggressive, the cookie consent popup still shows up

![Screenshot_20220311-075736.png](https://user-images.githubusercontent.com/81270448/157902844-a11f1fe5-692d-48cd-9785-007ff5026af7.png)

**Comment by ryanbr** [comment]
Thanks @D4v1dH03
