### ISSUE TITLE
[hdfilme.cx] AdBlock detection added for previously free 720p playback.

### ISSUE THREAD

**Issue by gettysburg** [easylist/easylist#11264]
### List the website(s) you're having issues:

`https://hdfilme.cx/filme1/james-bond-007-keine-zeit-zu-sterben-17824-stream/deutsch`

### What happens?

The site promises free 720p streams, however, has also implemented Ad Block detection and denies 720p streaming (by falling back to 360p) if an Ad Blocker is detected with the following message:

`Bitte deaktivieren Sie die Werbeblockierung, um 720P anzuzeigen. Vielen Dank, dass Sie uns unterstützen.`

Translated, this basically is them telling you, no 720p unless you uninstall your ad blocker or add an exception for all their domains (1st and 3rd party).

This is contrary to their paid service, which also allows 1080p streaming with whatever extensions you like. The site advertises free 720p streaming but doesn't mention that Ad Blockers need to be disabled to use this service, until you actually try.

### List Subscriptions you're using:

Every single one available in the latest developer build of uBlock Origin, except for the region-related ones, where I only enable EasyList Germany.

### Your settings

- OS/version: Windows Server 2019 LTSC / 1809 17763.2628
- Browser/version: 91.7.0esr (64-bit)
- Adblock Extension/version: uBlock Origin 1.41.9b0
- Additional Extensions: HTTPS Everywhere in blocking mode

Noteworthy browser settings:

```
javascript.options.asmjs = false
javascript.options.baselinejit = false
javascript.options.ion = false
javascript.options.native_regexp = false
javascript.options.wasm = false

privacy.resistFingerprinting = true
```

.. and many more security / hardening related changes, Firefox' built in "Enhanced Tracking Protection" is set to 'Strict' as well.

**Comment by ghajini** [comment]
@mapx- 
```
hdfilme.cx##+js(aopr, console.clear)
hdfilme.cx##+js(aopr, adBlocked)
```

**Comment by krystian3w** [comment]
No report anti-adblock here.

**Comment by gettysburg** [comment]
@krystian3w Because it was added to the filters already, closing.

**Comment by mapx-** [comment]
For anti adblocking / popups (as you are using uBO) report directly here:
https://github.com/uBlockOrigin/uAssets/issues

**Comment by gettysburg** [comment]
@mapx- Noted.
