### ISSUE TITLE
Is `/peel.js` from EasyList needed?

### ISSUE THREAD

**Issue by PerfectSalad** [easylist/easylist#11272]
It was used for bait for anti-adb

**Comment by krystian3w** [comment]
If have 10 year and more and block only bait then can by removed by follow:

> Any historical anti-adblock rules

**Comment by krystian3w** [comment]
In modern content blockers test:

### uBO/AdGuard and maybe Brave
`/peel.js$script,redirect=noop.js`

### ABP only
`/peel.js$script,rewrite=abp-resource:blank-jsblank-js`

**Comment by PerfectSalad** [comment]
> `/peel.js$script,redirect=noop.js`

didn't work, hence I opened https://github.com/uBlockOrigin/uBlock-issues/issues/2044

**Comment by PerfectSalad** [comment]
> If have 10 year and more and block only bait then can by removed by follow:
> 
> >

I remember 1 filter that was being used as bait was removed last year.

**Comment by Khrin** [comment]
Yes, it's needed.
