### ISSUE TITLE
Easyprivacy issue with embbed videos on facebook

### ISSUE THREAD

**Issue by rayman89** [easylist/easylist#113]
On facebook after you click on the the thumbnail with a play button created when someone leaves a link for a video, like youtube for example, the embed video for it should appear but the "/referer_frame." filter from EasyPrivacy is blocking it.

Example: http://www.imagebam.com/image/904626500871732

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=101764#p101764
