### ISSUE TITLE
Wentronic.* - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#11322]
### Affected sites:
```
https://www.wentronic.com/
https://www.wentronic.pl/
```

### Issue:
Modal overlay / missing scrollbar / unclickable items

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
```
##.cookie-modal
##cookie-modal
```

### Possible fixes:
* **Alternative 1** (ABP-compatible):
```
wentronic.com,wentronic.pl#@#.cookie-modal
wentronic.com,wentronic.pl#@#cookie-modal
```

* **Alternative 2** (uBO-only):
```
wentronic.*##.overlay-block
wentronic.*##body:style(overflow: auto !important;)
```

### Other problem filters:
* **AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/113044/
`##.cookie-modal`

* **I don't care about cookies** _(@kiboke)_
`~schuurman-schoenen.nl##.js-cookie-modal:not(body):not(html)`

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: Pale Moon v29.4.4 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by kiboke** [comment]
@THEtomaso If I see correctly, scrolling is not disabled (at least in IDCAC). It looks like blocking `.overlay-block` would be a better solution. Can you recheck, please?

**Comment by THEtomaso** [comment]
@kiboke:
I rechecked just now..
When blocking the modal overlay, scrolling appears to work with IDCAC only at first glance.
The issue seems to be a bit inconsistent though.
If you click on a product, you'll notice that the scroll bar disappears, then reappears when the product page has finnished loading.
A couple of times when I was testing, it didn't reappear at all, so your rule does indeed need to be modified to this!:
`~schuurman-schoenen.nl,~wentronic.com,~wentronic.pl##.js-cookie-modal:not(body):not(html)`

**Comment by THEtomaso** [comment]
@Khrin:

> https://github.com/easylist/easylist/commit/26ae49504b48add884ee985a4b26174c1d6f7b41

`wentronic.com,wentronic.pl##.overlay-block` should be modified to this:
`wentronic.com##.overlay-block:not(.overlay-block--gallery-modal-open)`
..like in **AdGuard Annoyances filter**:
https://github.com/AdguardTeam/AdguardFilters/commit/c310f3ec2df7eb5e01ac218ff7e52f5fc2ec7f9d

This will avoid visual confusion, when using the site's gallery slider.

How to reproduce:
1 - Go to `https://www.wentronic.com/en/wg-318o-57883`
2 - Click on the picure of the glove.
Result: The background modal is blocked, making it not-so-obvious for users that the gallery slider can be closed.

**Comment by kiboke** [comment]
@THEtomaso I see the problem, it will be fixed today. Thanks!
