### ISSUE TITLE
outlook.live.com/owa

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11345]
### List the website(s) you're having issues:

`https://outlook.live.com/owa/`

### What happens?

Ad / Annoyance

### List Subscriptions you're using:

See screenshot.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 98.0.1
- Adblock Extension/version: uBO 1.41.9b1

### Other details:

![outlook](https://user-images.githubusercontent.com/95879668/158848557-b0d445bd-0a11-482a-9b0a-9ffd04211656.png)

**Comment by Khrin** [comment]
I don't think it should be blocked.
