### ISSUE TITLE
HvemDer.no - Blocked object (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#11357]
### Affected site:
`https://hvemder.no/`

### Issue:
Blocked object.

### Example:
`https://hvemder.no/11111111/`

### Screenshot (blocked object):

![filterissue-hvemder](https://user-images.githubusercontent.com/9382674/159022805-1a199e71-9bfc-4a92-af73-8b4a4bb1b892.jpg)

### Note:
This site is for checking possible fraudulent phone numbers.
The blocked object is a window that show statistics for the number that you search for.

### Problem filter:
* **EasyPrivacy**

### Problem rules:
```
/hitcount.
/hitcount/*
```

### Possible fix:
`@@||hvemder.no^*/hitcount*$script,xmlhttprequest`

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: Pale Moon v29.4.4 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/564fb7ce32819329f311f7a402d276b627407c27
