### ISSUE TITLE
msn.com Skype plugin

### ISSUE THREAD

**Issue by adbloc** [easylist/easylist#1135]
Skype is broken on msn.com

### List the website(s) you're having issues:

```
https://www.msn.com/
```

### What happens?

Log into your outlook account and hover over Skype icon. 
Chat messages don't have avatar images.
Open a chat window for "Skype test call".  Click on the :) to open emojis list. No emojis show up.

### List Subscriptions you're using:

Easylist and tracking blocking

### Your settings

- Windows 10
- MS Edge latest 
- Adblock plus latest

**Comment by ryanbr** [comment]
Re-test it? Does it still happen?

**Comment by adbloc** [comment]
It is still happening on MS Edge latest.

**Comment by BigGiantHeadsHighCommander** [comment]
Consider https://riot.im as a video alternative ;)
