### ISSUE TITLE
A rule from Fanboy's annoyances doesn't respect the domain and blocks an unrelated script

### ISSUE THREAD

**Issue by Yardanico** [easylist/easylist#11401]
### List the website(s) you're having issues:

`https://paste.baalajimaestro.me/`

### What happens?

notifications.js gets blocked by uBlock origin because it matches the rule `/modules/notifications.$domain=~forum.vivaldi.net` from https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_notifications_general_block.txt#L21

![image](https://user-images.githubusercontent.com/21169548/159537879-5febe28d-3ed5-4da9-bedf-81f2c5121021.png)

**Comment by ryanbr** [comment]
Need more explaining. What is broken, why should it be changed. @Yardanico

**Comment by Yardanico** [comment]
@ryanbr i'm not sure if it's intended, but this rule from the list blocks an unrelated script from another website because it has the same path and name - https://paste.baalajimaestro.me/assets/js/modules/notifications.js

**Comment by ryanbr** [comment]
Again. what is the issue. we're blocking notifications. Closing.

**Comment by divadsn** [comment]
![image](https://user-images.githubusercontent.com/28547847/160242237-e50e38a5-afb7-4221-8869-444982585ea6.png)

But back to topic, the rule is clearly misbehaving since the domains are not even closely matched, so there is the issue.
