### ISSUE TITLE
[EasyCookies] Stack exchange sites cookie notices aren't blocked

### ISSUE THREAD

**Issue by D4v1dH03** [easylist/easylist#11415]
Includes Stackoverflow, Superuser, serverfault, unix stackexchange, meta sites  and all the sites under the umbrella of StackExchange
The cookie notices are still there even if easyprivacy and easycookies are enabled

**Comment by D4v1dH03** [comment]
This is happening with all sites that use stack exchange network

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8a0d4d5036000dd1b90476ccbc62c3f88a3f8041 Should help
