### ISSUE TITLE
journaldemontreal.com - incorrect blocking

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#1143]
### URL:
`http://www.journaldemontreal.com/2018/04/29/referendum-sur-lavenir-du-bloc-quebecois-1`

### What happens?

Facebook comments are not visible.

With Easylist
<details>

![image](https://user-images.githubusercontent.com/8361299/39922467-e7bb8df4-5527-11e8-8196-d957e05f8d23.png)

</details>

With `@@||automate-prod.s3.amazonaws.com/minified_logic.js$domain=journaldemontreal.com`

<details>

![image](https://user-images.githubusercontent.com/8361299/39922539-35c1c946-5528-11e8-8705-8a1d45557021.png)

</details>

### List Subscriptions you're using:
Easylist

### Your settings

ABP with Easylist

### Other details:

This is caused by
```
||automate-prod.s3.amazonaws.com^
```

**Comment by Khrin** [comment]
I don't see any hits for this filter on this site and I can load correctly the comments widget.

@smed79 If the issue is confirmed, probably this is more a matter for Liste FR, please can you take a look?

**Comment by Alex-302** [comment]
This is easily reproduced on my end
![image](https://user-images.githubusercontent.com/8361299/39937167-9042b612-5557-11e8-9a00-0e4bf4536e6c.png)
Original issue is from our French user.

Please try in private tab.

But why this domain is blocked in the filter?

**Comment by smed79** [comment]
> Please try in private tab.

In private tab, the FB comments widget is blocked by the FF [Tracking Protection](https://support.mozilla.org/kb/tracking-protection) even with ABP completely disabled http://i.imgur.com/zt7OY6I.png

FF, Tracking Protection disabled + ABP enabled > no issue http://i.imgur.com/uXzB31s.png

Chromium private tab + ABP enabled no issue http://i.imgur.com/QE6YD4k.png

**Comment by Alex-302** [comment]
Ok. Another example
http://www.velonews.com/2018/04/news/outer-line-scapegoat-travails-michele-acquarone_464374
![image](https://user-images.githubusercontent.com/8361299/39958536-0ae291d4-560d-11e8-896f-d41b24961c43.png)
I think automate-prod.s3.amazonaws.com(Rakuten Automate) should be [partially?]unblocked, or make it domain specific.

**Comment by Khrin** [comment]
Also here I don't have any problem to load these images...

**Comment by Alex-302** [comment]
Thanks.

**Comment by smed79** [comment]
https://github.com/easylist/easylist/commit/353e6bb9580cc5c0746a438ea2f9e85e2e1755bb
