### ISSUE TITLE
uploadever.com breakage

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#11449]
### List the website(s) you're having issues:

`https://uploadever.com/rbic8jxh1wcm`

### What happens?

website blocked due to `||lyricsmint.red^` in easylist

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: opera browser stable
- Adblock Extension/version: 1.41.8

### Other details:
`||lyricsmint.red^$badfilter`

**Comment by Yuki2718** [comment]
Is this really false positive? Looks to be a bad redirect caused by inline eval. `uploadever.in##+js(noeval)` works.

**Comment by Yuki2718** [comment]
Okay, going through `lyricsmint.red` let me reach the original link. Maybe it's only for them to earn $.

**Comment by ghajini** [comment]
i haven't get much time to workaround it
