### ISSUE TITLE
Some items are repeat in same meanings.

### ISSUE THREAD

**Issue by kazegh** [easylist/easylist#11441]
https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
Hello.
The problem is that some items are in same meanings.
1.Block the main parent website will block its subdomain one in adblock.
2.The short filter item will replace the long item.
Thanks.
This is the list:
cas.*.[criteo.com](http://criteo.com/)^
cas.*.[criteo.com](http://criteo.com/)^$domain=[spiegel.de](http://spiegel.de/)

line 69522: ||[xxxiijmp.com](http://xxxiijmp.com/)^
74935: ||[go.xxxiijmp.com](http://go.xxxiijmp.com/)

60292: ||haradeiu.rocks^
 72269: ||haradeiu.rocks^$popup
 75381: ||m.haradeiu.rocks^

 26117: /delivery/*?advplaces=
 28842: ?advplaces=

**Comment by ryanbr** [comment]
The others are fine
