### ISSUE TITLE
theengineeringmindset.com

### ISSUE THREAD

**Issue by joebagadonuts188** [easylist/easylist#11453]
### List the website(s) you're having issues:

https://theengineeringmindset.com/specific-heat-capacity-of-materials/

### What happens?

A cookie notification bar appears at the bottom. I think adding filter `###cookie-law-info-bar` to EasyList Cookie should work, but it doesn't need to be site specific.

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
AdGuard URL Tracking Protection
EasyPrivacy
Online Malicious URL Blocklist
Phishing URL Blocklist
EasyList Cookie

### Your settings

- OS/version: Win 10 Pro 64-Bit
- Browser/version: Chrome 99.0.4844.82 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.41.8

**Comment by ryanbr** [comment]
Force an update? is it still an issue? ###cookie-law-info-bar Filter had to remove/adjust the filter to avoid sites using disabling the scrollbar  @joebagadonuts188

**Comment by Khrin** [comment]
Blocked by `###cookie-law-info-bar ~ .cli-modal-backdrop`.
