### ISSUE TITLE
gitlab.com new cookie banner

### ISSUE THREAD

**Issue by D4v1dH03** [easylist/easylist#11451]
### List the website(s) you're having issues:
`https://gitlab.com` and all self hosted gitlab instances

### List Subscriptions you're using:

Default ublock lists+EasyCookies+EasyPrivacy
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

<img width="1440" alt="Screen Shot 2022-03-25 at 11 14 38" src="https://user-images.githubusercontent.com/81270448/160178434-851ce65f-a4ee-4a5b-845f-35cafec38a38.png">

**Comment by spirillen** [comment]
Relate to https://github.com/easylist/easylist/issues/9052

**Comment by Khrin** [comment]
> Relate to #9052

Nowhere near the truth.
