### ISSUE TITLE
www.flightradar24.com (Fanboy’s Annoyance)

### ISSUE THREAD

**Issue by DesertBear** [easylist/easylist#11498]
### List the website(s) you're having issues:

`https://www.flightradar24.com`

### What happens?

When accessing the website and clicking on an aircraft to get further details, because the cookie consent popup is blocked by the Fanboy’s Annoyance filter, the bottom of the details panel on the left (that contains further details/options) remains cut off.

When the filter is disabled in uBlock Origin and the cookie warning dialogue box dismissed, the details panel on the left appears correctly.  See screenshots below.

The issue is due to the following filter rule:

```
Filter       ##.important-banner--cookies
Filter list  Fanboy’s Annoyance 
Context      www.flightradar24.com
Type         dom
URL          https://www.flightradar24.com/UAE5CL/2b4f23d5
```

Below is a filter rule added by AdGuard to fix the same issue in the AdGuard Annoyances filters:

```
flightradar24.com##+js(remove-class, has-banner, body.has-banner, stay)
```

### List Subscriptions you're using:

Fanboy’s Annoyance filter

### Your settings

```
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 88199
  cosmetic: 101389
  scriptlet: 19894
  html: 0
listset (total-discarded, last updated): 
  added: 
    block-lan: 43-0, 2d.17h.8m
    fanboy-annoyance: 66026-188, 36m
    ublock-annoyances: 4355-119, 2d.17h.8m
  default: 
    user-filters: 91-3, never
    easylist: 64848-51, 2d.17h.8m
    easyprivacy: 26724-121, 2d.17h.8m
    plowe-0: 3687-809, 2d.17h.8m
    ublock-abuse: 72-0, 2d.17h.8m
    ublock-badware: 3947-86, 2d.17h.8m
    ublock-filters: 30498-104, 2d.17h.8m
    ublock-privacy: 203-10, 2d.17h.8m
    ublock-quick-fixes: 135-15, 16h.19m
    ublock-unbreak: 1741-44, 2d.17h.8m
    urlhaus-1: 8819-0, 16h.18m
filterset (user): [array of 91 redacted]
trustedset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 20 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1643 ms (selfie)
  maxAssetCacheWait: 242 ms

```

Fanboy’s Annoyance (202203262050)
Microsoft Edge - 99.0.1150.55
Windows 10 - 21H2 (19044.1620)

### Other details:

**Screenshot 1** – Fanboy’s Annoyance Filter Enabled (failed condition):
![Screenshot 01](https://user-images.githubusercontent.com/27423064/160629635-eaf9bc06-101d-426e-81e1-1d4a6a8adb21.jpg)

**Screenshot 2** – Fanboy’s Annoyance Filter Disabled (cookie dialogue visible):
![Screenshot 02](https://user-images.githubusercontent.com/27423064/160629664-c93405bb-8f32-41fe-ab18-7d7dd2c58c0a.jpg)

**Screenshot 3** – Fanboy’s Annoyance Filter Disabled and Cookie Dialogue Dismissed (details panel on the left is correct):
![Screenshot 03](https://user-images.githubusercontent.com/27423064/160629702-d33ea743-8f12-4e9f-92dd-7280ebf83cac.jpg)

**Comment by THEtomaso** [comment]
A fix is also needed for **I don't care about cookies** @kiboke

**Comment by kiboke** [comment]
Thanks @THEtomaso - fixed.

**Comment by THEtomaso** [comment]
Also, uBO Legacy's syntax converter doesn't convert the fix found in AdGuard Annoyances filter to a compatible one.

Original AdGuard rule:
`flightradar24.com#%#//scriptlet('remove-class', 'has-banner', 'body.has-banner', 'stay')`

In uBO's main branch (converted):
`flightradar24.com##+js(remove-class, has-banner, body.has-banner, stay)`

In uBO Legacy, the rule needs to be like this:
`flightradar24.com##+js(remove-class.js, has-banner, body.has-banner, stay)`
Its syntax converter already has this:
`'(rc,': '(remove-class.js,',`
..but also needs this:
`'(remove-class,': '(remove-class.js,',`

@hawkeye116477 / @SeaHOH:
This should be a quick fix.
Do any of you guys have admin access to the uBO Legacy repo?

**Comment by SeaHOH** [comment]
No, I don't.

**Comment by THEtomaso** [comment]
Seems that it also need this:
`'(abort-current-script,': '(abort-current-inline-script.js,',`

Perhaps more are needed too?

**Comment by hawkeye116477** [comment]
> Do any of you guys have admin access to the uBO Legacy repo?

No.
