### ISSUE TITLE
https://igg-games.com - anti-adblock active

### ISSUE THREAD

**Issue by Felipefpl** [easylist/easylist#11503]
The site has an anti-adblocker active.

**Comment by spirillen** [comment]
They are not fixed by easylist you should report it to adblock instead 

@Yuki2718

**Comment by smed79** [comment]
add as a custom filter
```
igg-games.com#@#.widget-advads-ad-widget
```
or
```
igg-games.com#$#abort-on-property-read document.getElementsByTagName
```

**Comment by Felipefpl** [comment]
Thank you very much to everyone who answered me and suggested/made the fix for this problem. :+1:
