### ISSUE TITLE
camping-residentiel-les-marronniers-jura.fr easylist cookie

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#11523]
### List the website(s) you're having issues:

`https://www.camping-residentiel-les-marronniers-jura.fr`

### What happens?

easylist cookie blocks the cookie acception popup, but the page is blurry 
![image](https://user-images.githubusercontent.com/83005/161052891-4add3c23-e42e-4070-b522-2842ee98784b.png)

### List Subscriptions you're using:

easylist fr
easylist
easylist cookie

### Your settings

- OS/version: 
- Browser/version: firefox
- Adblock Extension/version: ublock origin

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e044f75a5fe3754f1ba572556fec505cf2789934

**Comment by momala454** [comment]
i wonder if a fix compatible with all of the websites doing the same thing could be done, instead of doing a per-site fix ?

**Comment by momala454** [comment]
@ryanbr what do you think about my previous message ?

**Comment by ryanbr** [comment]
Will invesitgate a fix, /newCookieChoice.js won't stop the overlay btw

**Comment by momala454** [comment]
for me, blocking newCookieChoice.js in addition to the other filters is enough to block the overlay and popup
