### ISSUE TITLE
msguides.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#11525]
### List the website(s) you're having issues:

`https://msguides.com/`

### What happens?

ad in the left corner
<img width="249" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/161087294-fe0c5b53-5cea-49e0-904a-f2f5ec49eeff.PNG">

### List Subscriptions you're using:

uBlock Origin default with EasyList, EasyPrivacy and EasyList germany

### Your settings

- OS/version:  win 10
- Browser/version: firefox developer
- Adblock Extension/version: uBlock Origin 1.41.8

**Comment by BoomBookTR** [comment]
Add to Filters 

! 2022-03-31 https://msguides.com
||cpkshop.com/campaign/type/300.gif$image
