### ISSUE TITLE
Fanboy's Enhanced Tracking shows "Failed, checksum mismatch"

### ISSUE THREAD

**Issue by rjjiii** [easylist/easylist#11559]
I tried to subscribe to Fanboy's filters on this page: https://www.fanboy.co.nz/filters.html
They all worked except for "Enhanced Tracking" which both yesterday and today on separate computers gave the error "Failed, checksum mismatch."

- OS/version: Windows 10
- Browser/version: Pale Moon 30.0.1
- Adblock Extension/version: ABPrime 3.1

**Comment by krystian3w** [comment]
ABP droped checksum, so last was updated 14 months ago: https://github.com/ryanbr/fanboy-adblock/blame/a319a3fa41d5d716d6f683191a1bb68e6b8de7a1/enhancedstats-addon.txt#L2

https://github.com/ryanbr/fanboy-adblock/commit/9af0c8a10ded4332969fb3bca2544f2954228c12

ABP Prime may need use outdated version https://raw.githubusercontent.com/ryanbr/fanboy-adblock/9af0c8a10ded4332969fb3bca2544f2954228c12/enhancedstats-addon.txt or forked with deleted/updated.

Or change blocker content to uBlock Legacy:

https://addons.palemoon.org/search/?terms=uBlock+origin

**Comment by rjjiii** [comment]
Thanks! That solves my issue. I wonder why the checksum is still present if it's not being updated?
