### ISSUE TITLE
analytics.aita.gov.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [easylist/easylist#11558]
### List the website(s) you're having issues:

**analytics.aita.gov.vn**
### What happens?
tracking

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard DNS filter, Steven Black...

### Your settings

- OS/version: Windows/Android
- Browser/version: Chromium/Firefox
- Adblock Extension/version: uBlock Origin/NextDNS CLI

**Comment by spirillen** [comment]
Confirmed https://mypdns.org/my-privacy-dns/matrix/-/issues/967021

**Comment by spirillen** [comment]
And there are more under gov.vn: https://mypdns.org/my-privacy-dns/matrix/-/issues/966865

```
f-emc.ngsp.gov.vn   CNAME . ; Tracking
stats.muasamcong.gov.vn   CNAME . ; Tracking (T3778)
tracking.aita.gov.vn   CNAME . ; Tracking (T2102)
log.ttbc-hcm.gov.vn   CNAME . ; Tracking (T2019)
log.ca.gov.vn    CNAME . ; Tracking
```

**Comment by Khrin** [comment]
@vhpcdpgl Where's located? Any example link to give?

**Comment by vhpcdpgl** [comment]
> Where's located? Any example link to give?

**URL:** `https://mic.gov.vn/Pages/trangchu.aspx`
**Script:**
```<!-- Analytics -->
<!--
<script type="text/javascript">


//<![CDATA[
  
  var _paq = _paq || [];
  _paq.push(["setCookieDomain", "*.mic.gov.vn"]);
  _paq.push(["setDomains", ["*.mic.gov.vn","*.dvc.mic.gov.vn","*.english.mic.gov.vn","*.spdv.mic.gov.vn"]]);
  _paq.push(['setDocumentTitle', document.domain + "/" + document.title]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//analytics.aita.gov.vn/";
    _paq.push(['setTrackerUrl', u+'analytics.php']);
    _paq.push(['setSiteId', 29]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'analytics.js'; s.parentNode.insertBefore(g,s);
  })();
//]]></script>
-->
<!-- End Analytics Code -->```

**Comment by vhpcdpgl** [comment]
`analytics.aita.gov.vn` is being blocked by ABPVN List, AdGuard DNS filter, hostsVN, NextDNS Ads & Trackers Blocklist and Steven Black.
