### ISSUE TITLE
console.amazon.com/ecs/

### ISSUE THREAD

**Issue by rmasters** [easylist/easylist#1155]
### List the website(s) you're having issues:

An EasyPrivacy rule intended to block Amazon.com events tracking is affecting AJAX requests in the AWS console.

Blocked URLs:

```
(Page) https://eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/clusters/CLUSTERNAME/scheduledTasks
(Blocked AJAX) https://eu-west-1.console.aws.amazon.com/ecs/proxy/events/listRulesByTarget?limit=100&region=eu-west-1
```

### What happens?

An AJAX request to get scheduled tasks ("events") is blocked, which breaks the scheduled tasks manager. 

### List Subscriptions you're using:

* EasyPrivacy (static rule reported by uBlock)

### Your settings

* Confirmed working with uBlock Origin whitelisted for aws.amazon.com.
* macOS High Sierra; Google Chrome 66.0.3359.139; uBlock Origin 1.16.4
* No custom filters

### Other details:

I think this rule ([`||amazon.com^*/events/`](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_specific.txt#L120)) needs to exclude `aws.amazon.com`.

**Comment by ryanbr** [comment]
||amazon.com^*/events/$domain=~aws.amazon.com
