### ISSUE TITLE
mriyaresort.com

### ISSUE THREAD

**Issue by StudioMaX** [easylist/easylist#11579]
### List the website(s) you're having issues:

``
cloud.roistat.com
``

### What happens?

Analytics

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list
RUS: RU AdList

### Your settings

- OS/version: Windows 11
- Browser/version: Chrome 100
- Adblock Extension/version: uBlock Origin 1.42.2

### Other details:

![image](https://user-images.githubusercontent.com/9878458/162204377-bf384226-5f1f-4275-a574-a16b541d7b54.png)
![image](https://user-images.githubusercontent.com/9878458/162204700-12cf5c40-5c6e-4dc2-baa5-8b9923e5bf78.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/078cebc3fe7180da1c1a0d406c0e7b43d2909a2b
