### ISSUE TITLE
Request to exclude our domain from the « EasyPrivacy » list.

### ISSUE THREAD

**Issue by sensmg** [easylist/easylist#11574]
Hello,

Some of our customers use ad blocker like Adblock Plus, AdBlock and uBlock Origin.

It seems that your solution blocks our script from the « EasyPrivacy » list :

![image](https://user-images.githubusercontent.com/103174445/162144971-f37ab775-dc32-4b75-affd-b71fa6ef6cdc.png)

![image](https://user-images.githubusercontent.com/103174445/162145013-46b94091-314e-48e7-a7ab-2be1a0aafcbc.png)

Would it be possible to exclude our domain so that our customers are not blocked (https://tag.search.sensefuel.live/) ? 

We are up to date with the RGPD rules. 

Thank you in advance for your help.

Best regards,

**Comment by ryanbr** [comment]
useragent checks
fingerprinting
mouse movement/clicks checks
embedded google checks + recorder
embedded trustpilot


So no. Read; https://github.com/easylist/easylist/blob/master/README.md#easyprivacy
