### ISSUE TITLE
pik-arenda.ru

### ISSUE THREAD

**Issue by StudioMaX** [easylist/easylist#11580]
### List the website(s) you're having issues:

``
tracker.comagic.ru
``
And maybe
``
app.comagic.ru
``
``
server.comagic.ru
``

### What happens?

Analytics

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list
RUS: RU AdList

### Your settings

- OS/version: Windows 11
- Browser/version: Chrome 100
- Adblock Extension/version: uBlock Origin 1.42.2

### Other details:

![изображение](https://user-images.githubusercontent.com/9878458/162206591-4bf970b1-7aeb-4bed-a43b-321e5bca0f24.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/038b4da333555c7b2ce3db2fbaf9939bc58ab07f
