### ISSUE TITLE
Request: rrweb (via jsdelivr)

### ISSUE THREAD

**Issue by Kurtoid** [easylist/easylist#11584]
### List the website(s) you're having issues:
rrweb recomends that it's users deliver via jsdeliver, which is blockable via a single filter line. I'm not sure to how block self-hosted rrweb instances.

example rrweb url:
https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js

proposed filter line:
`||jsdelivr.net^*/rrweb.min.js`

### Why?
Like FullStory and Smartlook (which easylist blocks), rrweb is a tool/library for recording user sessions.

**Comment by ryanbr** [comment]
Fixed. thanks for the notification.
