### ISSUE TITLE
Puzzles about easylist_adservers.txt

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylist#11608]
These 3 rules seem to be placed in a wrong place. They should belong to url block rules?

https://github.com/easylist/easylist/blob/9cb24fd3d6cef8a5f8c5190eb25de2afc38b6ddb/easylist/easylist_adservers.txt#L14303

https://github.com/easylist/easylist/blob/9cb24fd3d6cef8a5f8c5190eb25de2afc38b6ddb/easylist/easylist_adservers.txt#L16473

https://github.com/easylist/easylist/blob/9cb24fd3d6cef8a5f8c5190eb25de2afc38b6ddb/easylist/easylist_adservers.txt#L17104

And this rule, `||pxlk9.net.^`, seems to be missing the top level domain. Should it be `||pxlk9.net^` or `||pxlk9.net.*^` ?

https://github.com/easylist/easylist/blob/9cb24fd3d6cef8a5f8c5190eb25de2afc38b6ddb/easylist/easylist_adservers.txt#L11666

**Comment by ryanbr** [comment]
||pxlk9.net.^  isn't the same as ||pxlk9.net^

ANyways, cleaned up EL.
