### ISSUE TITLE
www.shpock.com

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#11601]
### List the website(s) you're having issues:
`https://www.shpock.com/en-gb`

### What happens?
Cookie pop-up

### List Subscriptions you're using:

Fanboy Annoyance, Adguard Annoyance 
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Recommend opening a ticket on https://github.com/uBlockOrigin/uAssets/issues they may have a better fix. @andreewmat
