### ISSUE TITLE
www.nmsu.edu

### ISSUE THREAD

**Issue by amcginni** [easylist/easylist#11607]
### List the website(s) you're having issues:
- `www.nmsu.edu`

### What happens?

When visiting the homepage of www.nmsu.edu with either EasyList Cookie or Fanboy's Annoyance enabled and no cookie from the site stored on the computer, scrollbars are hidden and scrolling is not possible.  There is also annoying white space on the right, which is not visible when the list is not used and after the user has acknowledged cookies.  See the screenshot below.
![image](https://user-images.githubusercontent.com/46615954/162599301-8cc013a5-9508-4373-aa9f-c3d7f2e397c6.png)

### List Subscriptions you're using:
- EasyList Cookie
- Fanboy's Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 99.0
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:
This issue appears to be triggered by the page's inline `_shouldShowPopup` JavaScript function, which displays `cookieModal` when no cookie from this site is detected.  When this happens, the `modal-open` class is assigned to the HTML `<body>` tag.  This class has the following CSS attribute: `overflow: hidden`.

The whitespace appears to be triggered by a `style="padding-right: 17px;"` attribute in the `<body>` tag.

I found a workaround by adding the following line to my filter rules:
`nmsu.edu##.modal-open:style(overflow:visible !important; padding-right:0px !important)`

**Comment by Yuki2718** [comment]
@Khrin This can be blocked: `||fast.wistia.net/assets/external/googleAds.js`
