### ISSUE TITLE
Elkjop.no - User reviews won't show (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#11611]
Full info here:
https://github.com/uBlockOrigin/uAssets/issues/12680#issuecomment-1094297890

**Comment by ryanbr** [comment]
resolved

**Comment by THEtomaso** [comment]
Broken again, by the following filter:
* **EasyList – Cookie Notices** / **Fanboy's Annoyance List**
`elkjop.no###cookie-information-template-wrapper`

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by THEtomaso** [comment]
> https://github.com/easylist/easylist/commit/46a8215172d02eb84b962cd731a640d71123f86b

@Khrin:

OK, that fixes the issue.
..but now the list contains both a blocking rule and a whitelisting rule!
Why didn't you simply remove the blocking rule?

BTW; In addition to the actual blocking rule, I would assume that this rule is redundant too now:
`elkjop.no##body:style(overflow: auto !important; position: initial !important;)`
