### ISSUE TITLE
 https://www.numerama.com/

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#11628]
`https://www.numerama.com/pop-culture/905135-disney-a-censure-des-scenes-violentes-de-falcon-et-le-soldat-de-lhiver.html`*

missing twitter integration with easylist cookie

with ublock origin on firefox:
![image](https://user-images.githubusercontent.com/83005/161020163-8ec20b79-dc9d-4f00-b166-153569e971da.png)

without:
![image](https://user-images.githubusercontent.com/83005/161020206-af9e6384-feaa-4c19-9916-613c2c3f30c2.png)

edit: it looks like  `https://cache.consentframework.com/` and `https://choices.consentframework.com/` must be allowed, but this bring back the cookie popup.
The twitter widget is added on the script `https://choices.consentframework.com/js/pa/22805/c/xDJmn/cmp` in the function `_addTagListeners`. I wonder if it's possible for ublock to modify the script on the fly to only execute the callback, or something ?

similar problem with consentframework on `https://www.frandroid.com/marques/apple/1191269_le-gros-probleme-dapple-derriere-lescroquerie-ampme-sur-iphone`

**Comment by ryanbr** [comment]
Looking at `https://www.frandroid.com/marques/apple/1191269_le-gros-probleme-dapple-derriere-lescroquerie-ampme-sur-iphone` I see a tweet, but nothing embedded, even disabling the tweet. Need more info on whats broken on that site specifically

numerama.com was easily reproducible.  @momala454 https://github.com/easylist/easylist/commit/724fa86963dd66ef82b9d1322b13989ad8c32e38

**Comment by momala454** [comment]
For FrAndroid, there is an embedded Twitter below "C’est 520 dollars par an pour cette unique fonction. A priori avec de tels tarifs, l’objectif des développeurs est qu’un pourcentage d’utilisateurs oublie d’annuler cet abonnement. En gros, c’est une escroquerie"

It shows when disabling ublock and allowing cookies

**Comment by momala454** [comment]
@ryanbr 
see screenshot : 
![image](https://user-images.githubusercontent.com/83005/163843005-5991ec32-b1a1-458b-909c-05585e543eef.png)


the tweet should be embedded

**Comment by momala454** [comment]
how can i reopen ?
