### ISSUE TITLE
spaceweather.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11630]
### List the website(s) you're having issues:

`https://spaceweather.com/`

### What happens?

2 Columns of Ads / Annoyances

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly 101
- Adblock Extension/version: uBO 1.42.5b0

### Other details:

![spaceweather](https://user-images.githubusercontent.com/95879668/162871572-9eecc848-5e8d-4d23-8991-126db96ad21a.png)

**Comment by ryanbr** [comment]
No easy fix, blocking the images seems to make things more ugly. If you some simplified rule suggestions it could be re-reviewd.
