### ISSUE TITLE
wetter.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11633]
### List the website(s) you're having issues:

`https://www.wetter.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly 101
- Adblock Extension/version: uBO 1.42.5b0

### Other details:

![image](https://user-images.githubusercontent.com/95879668/162876973-1c00ecb8-1b74-42f0-95b2-092427e153c6.png)

**Comment by ryanbr** [comment]
if you have a suggested filter, it'll break the video playback https://www.wetter.com/hd-live-webcams/deutschland/brandenburger-tor-berlin/6101d5490b52e/  @q1800

**Comment by q1800** [comment]
@ryanbr,

I believe you are correct. I can't seem to find anything that works either. We might just have to let this one be as is?

Thank you for looking into this. This one is a real pain in the neck. 🤣
