### ISSUE TITLE
[Incorrect blocking ] r-ulybka.ru - product filter is broken

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#1163]
Can't select product
URL: `https://www.r-ulybka.ru/search/?q=var&where=catalog&where-section-id=&go-search=`
Screenshot:
<details>

![image](https://user-images.githubusercontent.com/8361299/40182248-a4983024-59f3-11e8-9254-f4b92b76a79f.png)

</details>

Caused by `/filter.php?pro$script`
According to `https://publicwww.com/websites/%22%2Ffilter.php%3Fpro%22/` this rule can be changed to `/tp/filter.php?pro=$script`

**Comment by ryanbr** [comment]
Removed.

**Comment by Alex-302** [comment]
@ryanbr but `/tp/filter.php?pro=$script` will block without incorrect blocking. It seems this is a tracker on a lot of nsfw sites.

**Comment by ryanbr** [comment]
Example sites?

**Comment by Alex-302** [comment]
Please take a look:
https://publicwww.com/websites/%22%2Ffilter.php%3Fpro%22/
