### ISSUE TITLE
[youtube.com] Filter set to disable annoying "Verify it's you" check on privacy-hardened browsers.

### ISSUE THREAD

**Issue by gettysburg** [easylist/easylist#11640]
Hi, first of all sorry for not using the template, I am in a hurry.

Many people using uBlock Origin on Firefox are also concerned about their privacy and fingerprinting, and in response set the Enhanced Tracking Protection setting to ``Strict`` and / or enable ``privacy.resistFingerprinting``, a feature initially designed for the Tor Browser project, which now lives on in Firefox.

This has the side effect of Google's services, especially YouTube, sometimes thinking a new login  or even worse, an account breach, occurred. 

This is despite using the same IP, sub-net and ISP / ASN all the time, and when you go check the log-in history, it's also only my static IP listed there. 🤦‍♂️

This renders YouTube unusable, as a pop-up instantly appears on any site visited, forcing you to re-verify your account, for me they always ask for a phone number, which I am reluctant to give to them, for good reasons, however it varies, depending on what account recovery data you already gave them.

According to Reddit posts, these in-site pop-ups can theoretically happen on any service by Google, however for me, so far they only appeared on _https://youtube.com_.

You can just filter the HTML elements out, for example:

```
youtube.com###confirmation-dialog > .ytcp-confirmation-dialog.style-scope
youtube.com##body > .opened
youtube.com##body > ytcp-auth-confirmation-dialog
```

This fully restores the usability of YouTube, and **has no implications for your account**, such as punishments for not re-verifying your account.

The pop-up eventually goes away on it's own (as confirmed by uBlock Origin no longer logging the custom rules being triggered when visiting YouTube).

Regards.

**Comment by ryanbr** [comment]
I'm happy to leave this, Its good for a personal list. but may be more problematic for others.
