### ISSUE TITLE
Annoyance: phpdelusions.net

### ISSUE THREAD

**Issue by DRSDavidSoft** [easylist/easylist#11667]
### List the website(s) you're having issues:

`http://phpdelusions.net/pdo`

### What happens?

A large flag in the bottom left corner of the page obstructs the view of actual page content.

### List Subscriptions you're using:

Standard/default subscriptions on uBlock Origin

### Your settings

- OS/version: Windows 11 Pro
- Browser/version: Chrome 100
- Adblock Extension/version: uBlock Origin 1.41.8

### Other details:

Here's the relevant filter:

```
phpdelusions.net###we-stand-with-ukraine
```

Appropriate list name: Fanboy annoyance

**Comment by ryanbr** [comment]
It'll blocking this would imply I'm taking a stand on this. And also imply future blocks. I'll avoid this.
