### ISSUE TITLE
Links to our sponsors blocked on www.meerdangewenst.nl

### ISSUE THREAD

**Issue by stkams** [easylist/easylist#11679]
in easylistdutch there are two entries that block links to sponsors of our non-profit organisation. These links are _not_ ads.

block_first_party_resource.txt: `||meerdangewenst.nl^*/sponsors/`
hide_specific.txt: `meerdangewenst.nl##.tg-site-footer-section-1`

Could these entries be removed, please?

### List the website(s) you're having issues:

https://www.meerdangewenst.nl

### What happens?

Links to sponsors of our non-profit organisation are removed. These links are _not_ ads.

### List Subscriptions you're using:

Noticed with AdGuard

### Other details:

You can contact the webmaster (me) on the usual email address if confirmation is required.

**Comment by stkams** [comment]
I could also create a pull request myself

**Comment by ryanbr** [comment]
Sure, but it's not in Easylist.
```
fanboy@Ubuntu:~/git/easylist$ grep -r meerdangewenst *
fanboy@Ubuntu:~/git/easylist$
```

**Comment by stkams** [comment]
Created in easylistdutch https://github.com/easylist/easylistdutch/issues/47
