### ISSUE TITLE
[EasyPrivacy] ezoic.net

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#11693]
### List the website(s) you're having issues:
```
https://imagecolorpicker.com/
```

### What happens?

I think that `ezoic.net` running in the background collects data usage or something like that. `https://ezoic.net` states things related to revenue.

### List Subscriptions you're using:

uBlock Origin with default lists.
All official uBlock Filters; EasyList; EasyPrivacy; Online Malicious URL Blocklist; Peter Lowe's Ad and tracking server list; spa, por: AdGuard Spanish/Portuguese.

### Your settings

- OS/version: Windows 10 Pro 21H2
- Browser/version: Google Chrome 64 bits 100.0.4896.127
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:

`ezoic.net` screenshots:
![image](https://user-images.githubusercontent.com/30274161/163893621-c25fb33d-4d57-41ba-aa26-02f5b91b8904.png)
![image](https://user-images.githubusercontent.com/30274161/163893636-b950af8d-295e-4060-a886-2b1e812baa27.png)
![image](https://user-images.githubusercontent.com/30274161/163893655-ebc7166b-52bd-4956-8a43-42d8c9cf44b9.png)

**Comment by ryanbr** [comment]
Aware of it, its mostly addressed without causing false positives.
