### ISSUE TITLE
Easyprivacy magento2 subdomains

### ISSUE THREAD

**Issue by magentix** [easylist/easylist#11716]
### List the website(s) you're having issues:

https://magento2.magentix.fr
https://magento2.algolia.com
https://magento2.demo.ubertheme.com
...

[allinurl::https://magento2.](https://www.google.com/search?q=allinurl%3A%3Ahttps%3A%2F%2Fmagento2.&client=ubuntu&hs=1ZU&channel=fs&biw=1853&bih=967&ei=wshfYo-POcGWaPCcrYgL&ved=0ahUKEwiP-IHpoKL3AhVBCxoKHXBOC7E4FBDh1QMIDQ&uact=5&oq=allinurl%3A%3Ahttps%3A%2F%2Fmagento2.&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsANKBAhBGABKBAhGGABQAFgAYKsDaAFwAXgAgAEAiAEAkgEAmAEAyAEIwAEB&sclient=gws-wiz)

### What happens?

324dc95170d871a4025dcbc947df1a5e98734bc9

This was added to block the *​https://webservices.data-8.co.uk/javascript/magento2.js* script on clearchemist.co.uk.

But it blocks requests from all **magento2** subdomains, used by hundreds of sites for Magento2 demos.

### List Subscriptions you're using:

easyprivacy

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/159be428154b4d3ac33cca1939a1d214dbd4bdb3
