### ISSUE TITLE
popular upload JS lib. not working

### ISSUE THREAD

**Issue by thatdom** [easylist/easylist#11728]
We are using [Uppy](https://uppy.io/) library in our web app and we noticed that uBlock Origin is blocking one file from the library - ["EventTracker.js" file](https://github.com/transloadit/uppy/blob/0cccb686fdbeba2de39b1d8eb524db4dbccca3a7/packages/%40uppy/utils/src/EventTracker.js)

Looks like it's blocked because of this rule:
https://github.com/easylist/easylist/blob/159be428154b4d3ac33cca1939a1d214dbd4bdb3/easyprivacy/easyprivacy_general.txt#L1827

<img width="1215" alt="Screenshot 2022-04-20 at 15 13 00" src="https://user-images.githubusercontent.com/129972/164250374-d49af5b1-7346-4ec1-ad1a-5cfcbfc5fe1c.png">

**Comment by ryanbr** [comment]
There is no fix for this, we block event trackers which going by the source https://github.com/transloadit/uppy/blob/0cccb686fdbeba2de39b1d8eb524db4dbccca3a7/packages/%40uppy/utils/src/EventTracker.js seems to be a fine to block this.
