### ISSUE TITLE
.me + websocket = blocked?

### ISSUE THREAD

**Issue by Tucsky** [easylist/easylist#1173]
### List the website(s) you're having issues:
http://tucsky.github.io/SignificantTrades
which contains ws source : wss://btcusd.kevinrostagni.me/

### What happens?
So I use uBlock and just saw that my site got blocked by this :
https://github.com/easylist/easylist/blob/d381b625771fbf009f91e564e6ff9b2d7aea3842/easyprivacy/easyprivacy_trackingservers.txt#L2350

Its a .me, and use websocket, so its blocked ... I don't know maybe its a bit too restrictive ?

Its like assuming all in browser miner use .me domain, pretty sure Im not the only one affected by this.

### List Subscriptions you're using:
the default, that issue come from the **easyprivacy** list

### Your settings
- OS/version: OSX
- Browser/version: Chrome 66
- Adblock Extension/version: uBlock Origin 1.16.6

### Other details:
Just block munero.me !

**Comment by rpendleton** [comment]
Were you able to resolve this? I'm running into this issue with my .me domain as well...

**Comment by Tucsky** [comment]
Yes I changed the domain
