### ISSUE TITLE
interactivebrokers.co.uk - Cookie notice broken

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#11753]
### List the website(s) you're having issues:

- `https://www.interactivebrokers.co.uk/en/home.php`

### What happens?

The CMP/Cookie modal is not visible, but the backdrop is and it's causing the website to not be accessible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.1
Browser/version: Chrome 97
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/164469253-927bcb88-a3d0-4e98-bf47-b47f68d51f3d.png">

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a97cbb2442e6d470984235380c6ce73e6623052e
