### ISSUE TITLE
bosch-home.* not fixed fully yet

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#11754]
This was only partially fixed: https://github.com/easylist/easylist/pull/9502

These domains still not fixed:

https://www.bosch-home.bg/
https://www.bosch-home.ee/
https://www.bosch-home.gr/
https://www.bosch-home.ie/
https://www.bosch-home.lv/
https://www.bosch-home.pt/
https://www.bosch-home.pl/
https://www.bosch-home.si/
https://www.bosch-home.rs/
https://www.bosch-home.com.tr/

Suggestion:

instead of adding many domains individually (as it's currently done), why not using `bosch-home.*` instead as uBO supports using an asterisk? That would be a lot easier to handle and would cover any possible new top level domains that would be added in the future.

**Comment by krystian3w** [comment]
Bad idea is use asterisk if we don't know how parse this very old AdBlock and Adblock Plus on retro browsers as long list support release 1.1 of extension.

**Comment by ryanbr** [comment]
Does that help?

**Comment by peace2000** [comment]
Yep it's fine now.

@krystian3w these filters are meant for uBO so ABP compatibility is not needed.
