### ISSUE TITLE
Reclassification request: transcend.io

### ISSUE THREAD

**Issue by eligrey** [easylist/easylist#11762]
`transcend.io` was recently added to your cookie consent warning / notice list. This is causing some privacy tools to block our domain, which actually increases first-party tracking as our tools are used for privacy compliance and are designed in a privacy-respecting manner. This also causes Privacy Centers for our customers to not load due to an inability to interface with our backend endpoints.

We do host a tracking consent banner notice / prompt in the form of an optional (inactive by default) consent UI for our customers. Due to our modular architecture, this UI alone could easily be blocked on the network level by easylist instead of all of `transcend.io`. We would prefer if you replaced the current entry in easylist_cookie with the following rule:

```
||cdn.transcend.io/*/ui.js$third-party
```

Non-essential tracking disclosure:
- We have an optional telemetry domain (`telemetry.transcend.io`) that [collects non-PII operational data](https://www.notion.so/transcend/Compliance-4551414bf7434c309e532b817f625017) that you may want to add to easylist_cookie.
- We support optional private local cross-domain consent & quarantine sync that doesn't expose sync data over network requests. These endpoints are hosted at `sync.transcend.io` by default although they can be easily self-hosted by customers with a static HTML snippet at a predetermined location.

### List the website(s) you're having issues:

This is only causing issues with Ghostery users at the moment, but a couple examples are:
- `indiegogo.com` - Consent manager can't regulate network traffic
- `privacy.patreon.com` - Site doesn't load due to blocked Transcend backend endpoints

### What happens?

Everything from transcend.io in a third-party context is blocked by some content blockers, for reasoning that is not in line with the intended purpose of easylist_cookie.

### List Subscriptions you're using:

- easylist_cookie

**Comment by ryanbr** [comment]
"Privacy Centers" are consent managers, I see no reason to reclassify. Reviewed the JS; https://www.pastiebin.com/626284218f23b

**Comment by dmattia** [comment]
@ryanbr A "Privacy Center" would be a page like privacy.patreon.com or https://privacy.groupon.com/policies/en-US.

That link you have is to the consent manager code, which is the part that @eligrey asked to be explicitly blocked as consent manager code, as opposed to the entirety of transcend.io domains, which contain other products.

By blocking all of transcend.io, easylist users can lose access to exercise their data rights through things like access/deletion/opt-out requests

**Comment by ryanbr** [comment]
This is the point of Easylist Cookie, we're blocking GDPR/CCPA/Cookie/Consent messages.

**Comment by eligrey** [comment]
Also, the specific JavaScript file that you reviewed has no user interface code. It does not trigger any user tracking, unlike some consent managers (mostly those that implement IAB TCF) that end up uniquely tracking you. Every line of JavaScript in that file is used for implementing and enforcing network regulations

As for the Privacy Centers: those aren't consent managers. Privacy centers are where users submit requests to download, delete, or modify their data as legally required under some new privacy laws. The Privacy Center does not have a consent manager. Please review the network traffic on `privacy.patreon.com`.

**Comment by eligrey** [comment]
> I don't have access to privacy.patreon.com, but browsing patreon.com seemed okay.

No, that's the issue. That's a public website. Try browsing without any content blockers. Our essential GraphQL endpoint on `api.transcend.io` is likely being blocked for you.

> I would expect ELC would break consent managers from checking/confirming checks etc

It would for most that share consent externally. Transcend Consent Manager works on local-only consent data by default isn't simply "checking" consent to propagate to business partners, it's actively enforcing privacy rules onto all network requests locally. I wrote [a blog post which explains what our tool does](https://transcend.io/blog/defeating-cookie-banners/) (note: one of the code screenshots is currently broken, working to restore it soon) 

> The transcend.io script is also a privacy issue (useragent, fingerprinting/cookie, analytics checks)

More context please. I can step you through the purpose of every line of code in airgap.js, as I wrote it myself while following privacy-first principles and using zero third party dependancies.

Responses to your claims:

- fingerprinting: airgap.js has no fingerprinting and makes no attempt to uniquely identify users. Random numbers are generated and used locally-only to [privately *count* sessions](https://www.notion.so/transcend/Compliance-4551414bf7434c309e532b817f625017#db05bc1a1af34147bdcf0a30af9e9635). Please provide specific lines or blocks or code from airgap.js that you suspect to be fingerprinting users.
- cookie (assuming you mean 'local storage'): We have a general-purpose network & cookie event quarantine. This could be force-disabled via our pre-init load API (set `data-replay="off"` on the script element) via scriptlets. Admittedly that's not the best experience for content blocker devs
- useragent: We inspect the useragent for each of the following browser differences, and don't use the useragent for any form of fingerprinting:
  - EdgeHTML & Safari < 14: Detecting that `EventTarget` isn't instantiable without a `try..catch` test
  - EdgeHTML: `document.implementation.createHTMLDocument()` normalization without a runtime test
  - Firefox: Mitigating Firefox-specific PerformanceObserver resource timing buffer browser bugs (e.g. `performance.setResourceTimingBufferSize(0)` doesn't work)
- analytics checks: We do not integrate with any third party tag management systems other than to pre-insert opt-out signals into Google's dataLayer and Facebook's  `The transcend.io script is also a privacy issue. This is a general purpose event quarantine, which content blockers can force-disable. We only [integrate **consent signals** to Google and Facebook](https://www.notion.so/transcend/Integrations-44506170eb9340c98efc573354648783#68b3c5a5e3fc4557a50f0bb7515e1912). We goes as far as actively rewriting requests to some Google and Facebook properties to force privacy-preserving behaviors. We expose a [public API for actively rewriting requests](https://www.notion.so/transcend/airgap-js-API-Reference-b5d0842399474eb99040c08b5ac0036c#b3f767a91d994fe5a6aa8388876d1b7d) that this functionality is built on top of.

**Comment by eligrey** [comment]
@ryanbr Can we please get a response? As I previously stated, you have mistakenly confused `privacy.patreon.com` to be a private website. Please visit the website with *all* of your content blockers disabled.

We believe that our privacy compliance services deserve more finely-grained annoyance blocker rules.

Transcend Privacy Requests and Transcend Consent are not consent managers. Transcend Consent *contains* an optional consent manager and a privacy-aware network firewall that is designed to not track users or user behavior. Customers use Transcend Consent to reign in analytics behavior, and this can include first-party tracking components that may not be on EasyList or may not be possible for you to properly block without significant site breakage. Transcend Consent works similarly to an ad blocker by ensuring that these components cannot track you without your consent. We allow some scripts through (without credentials, similar to our own script if you have noticed) 

Please consider blocking our consent manager (`cdn.transcend.io/*/ui.js`) and also look into force-disabling our network firewall's quarantine feature with just-in-time [`data-replay="off"` attribute](https://docs.transcend.io/docs/consent/api#replay-control-(default:-on)) insertion or by seeding our [load options API](https://docs.transcend.io/docs/consent/api#load-options) with `self.airgap = { loadOptions: { replay: 'off' } }` upon encounter with any script that matches `cdn.transcend.io/*/airgap.js`.

We are willing to work with you on this to provide the best developer ergonomics for blocking our consent manager and force-disabling our network firewall quarantine feature. All that will remain after such blocking is our core legal compliance technology, which I genuinely believe is entirely user-beneficial (we don't share data with third parties and hope for downstream compliance like other privacy tools).

Note that our consent manager UI is [automatically suppressed](https://github.com/transcend-io/consent-manager-ui/pull/25) if you enable Do-Not-Track in any regime or Global Privacy Control in any CPRA-like regime. e.g. This means that Brave users in California do not get a banner on Indiegogo's site *at all*, since Brave defaults Global Privacy Control on.

**Comment by ryanbr** [comment]
We're not treating other content managers differently too transcend. And to create any new exemption would send create a new precedence to other providers being blocked by Easylist Cookie list.

We block everything and anything related to consent compliance/messaging, gdpr, ccpa, cookie messages, constant popups, dialogs/content/compliance/messaging/nags/banners/controls etc.  Regardless how its implemented, at it's core its still a content/consent management service which is within the scope of the list.

It was strongly considered to have Transcend blocked in Easyprivacy due to the tracking (which would have affected far more people). but felt Easylist Cookie list is the best fit.  Easylist Cookie is purpose built for these cookie/content/consent managers. Which after consideration is still he best place for this.

For the most popular extensions ABP and uBO, Easylist Cookie isn't a default list. So unless you explicitly enable this list it won't affect anyone else.  "How to work with you", since its unless you change your business modal, Transcend  is still content consent management service, which is still in scope of this specific list.

As a simple list we can't check which regions people are in, or browser settings like DNT. But what we can do suppress and/or remove these content consent messaging. Which is why it remains in Easylist Cookie.

**Comment by eligrey** [comment]
> I don't have access to privacy.patreon.com, but browsing patreon.com seemed okay.

You didn't respond to the part about our privacy centers being blocked.

**Comment by eligrey** [comment]
@ryanbr Some of our customers self-host airgap.js. If the goal of ELC is to hide cookie consent notices, consider adding CSS to hide `#transcend-consent-manager` (the well-defined ID used by our default consent UI) with `{ display: none }`.

**Comment by Khrin** [comment]
sorry @eligrey , misunderstood your true intentions

**Comment by ryanbr** [comment]
Happy to leave it, nothing public front facing I can see. If its internal, seems fine.

**Comment by eligrey** [comment]
We also changed CDNs recently. I've updated suggestions in the OP to reflect our CDN changes.
