### ISSUE TITLE
teleboy.ch

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#11783]
### List the website(s) you're having issues:

`https://www.teleboy.ch/en/tv-guide/gulli/22056619/my-little-pony-nouvelle-generation`

### What happens?

Large placeholder near the top.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/22780683/164947976-c3ad8140-474e-467b-b06c-1395b9437237.png)

</details>

### Your settings

- OS/version: Windows 11 x64
- Browser/version: Chrome 100.0.4896.127 x64
- Adblock Extension/version: uBO 1.42.4 + IDCAC 3.3.8

### Other details:

I propose `teleboy.ch##.grid-col-content-leaderboard`

![image](https://user-images.githubusercontent.com/22780683/164948388-ffc0bbb2-e231-437d-88a1-86512cd434be.png)

**Comment by ryanbr** [comment]
French list? @DandelionSprout

**Comment by DandelionSprout** [comment]
The site has an English version, including in the example link.

For that matter, it also has German and Italian versions selected on the page's lower-right.
