### ISSUE TITLE
getdroidtips.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#11781]
### List the website(s) you're having issues:

`https://www.getdroidtips.com/motorola-one-zoom-android-11-update/`

### What happens?

Various placeholders, the largest ones of them 250px tall. One placeholder ~55% into the article is shown regardless of the window width; the rest are visible at ≤960px.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/22780683/164947976-c3ad8140-474e-467b-b06c-1395b9437237.png)

</details>

### Your settings

- OS/version: Windows 11 x64
- Browser/version: Chrome 100.0.4896.127 x64
- Adblock Extension/version: uBO 1.42.4 + IDCAC 3.3.8

### Other details:

I propose `getdroidtips.com##.code-block`

![image](https://user-images.githubusercontent.com/22780683/164948189-7dca0f34-abb6-4856-94ab-79fd58f5659c.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/68067208e18faa7c6fae410256b69f05b5de474d
