### ISSUE TITLE
My website was wrongfully added to the list

### ISSUE THREAD

**Issue by NexPB** [easylist/easylist#118]
I woud appreciate if my website was removed from the list, it's blocking disqus from my website. I do not serve ads directly from this domain.

Website: masterani.me
Commit: https://github.com/easylist/easylist/commit/8296e8a47829510c9512645a449077c726e65069

**Comment by terrorist96** [comment]
There's an unblocked ad on your homepage and disqus isn't blocked for me.

**Comment by xMunch** [comment]
http://i.imgur.com/zEPjexo.png
http://i.imgur.com/fZYR8RL.png

For me it blocks both embed.js (for disqus) and jQuery when accessing some pages that utilize it.
