### ISSUE TITLE
bimbim.com - all streams broken

### ISSUE THREAD

**Issue by gene-pavlovsky** [easylist/easylist#11833]
### List the website(s) you're having issues:
https://bimbim.com
Then open any online model's page from the gallery

### What happens?
The model's page loads but the stream doesn't start. Several network requests are visible as blocked in Chrome DevTools Network tab

### List Subscriptions you're using:
Default lists used by uBlock Origin, the rule from EasyList breaks this site

### Your settings

- OS/version: macOS 12.3.1
- Browser/version: Chrome 100.0.4896.127 (x86_64)
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:
The rule that breaks this site is `||bimbim.com^` and comes from EasyList and is apparently too general to work properly.
Related uBlock Origin issue: https://github.com/uBlockOrigin/uAssets/issues/12961

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/63bc9c6d68b5c054ce2cc71056e8f29450174ed6

**Comment by gene-pavlovsky** [comment]
Thank you
