### ISSUE TITLE
enginey.altex.ro/events/

### ISSUE THREAD

**Issue by alinchican** [easylist/easylist#11832]
### List the website(s) you're having issues:

`https://altex.ro/`

### What happens?

Daily promoted offers and related/sale/clearance items sold by us aren't visible to our store visitors.

### List Subscriptions you're using:

EasyPrivacy

### Other details:

Hello! Alin from Altex here.

EngineY is an internal search and recommendation engine developed by us in order to display various products to visitors. We do track things like product views, purchases, adding to cart but only for ranking products. EngineY helps us improve website performance for visitors and reduce used resources on our end.

We kindly ask you to modify the current rule from `enginey.altex.ro/events/` to `enginey.altex.ro/events/v*/events`. This new rule continues to block events sent to us but will allow visitors to see product deals.

Thanks for your time!

**Comment by ryanbr** [comment]
See https://github.com/easylist/easylist/blob/master/README.md#easyprivacy
