### ISSUE TITLE
[EasyPrivacy] edisound.com/api/p/stats

### ISSUE THREAD

**Issue by ErnadoO** [easylist/easylist#11835]
### List the website(s) you're having issues:

`https://www.autoplus.fr/renault/clio/renault-clio-voici-voiture-plus-chere-monde-561011.html`
`https://www.maison-travaux.fr/maison-travaux/conseils-pratiques/vinaigre-blanc-erreurs-a-absolument-eviter-vinaigre-blanc-303813.html`

### What happens?
Hello

edisound.com/api/p/stats was recently added to your easyprivacy list in commit https://github.com/easylist/easylist/commit/c24fd1f04882d2d310bf16a5ff36fa0f41cab2d2

This url (called by our player during listening) doesn't track the user, it's fully anonymous, we don't record any user data. The goal is just to send us the listening time of a podcast listened, like spotify and many other players make it, to know which episode is the most listened to. No more no less.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 99
- Adblock Extension/version: uBlock Origin 1.37.2

**Comment by ryanbr** [comment]
See: https://github.com/easylist/easylist/blob/master/README.md#easyprivacy
