### ISSUE TITLE
outlook.com

### ISSUE THREAD

**Issue by DesertBear** [easylist/easylist#11847]
### List the website(s) you're having issues:

`https://outlook.live.com/owa/`

### What happens?

Microsoft have recently made some changes to outlook.com.  While the ad at the top of the inbox is blocked by uBlock Origin, a placeholder now displays for some Microsoft accounts.

### Screenshots

**Screenshot A - uBlock Origin off (ad displayed):**
![Screenshot A](https://user-images.githubusercontent.com/27423064/165598466-24835c2b-1854-430e-8076-449960ade20d.jpg)

**Screenshot B - uBlock Origin on (placeholder still displayed):**
![Screenshot B](https://user-images.githubusercontent.com/27423064/165598508-7da90884-bfe8-4740-a516-7639bd755910.jpg)

### Your settings
```
uBlock Origin: 1.42.2
Chromium: 100
filterset (summary): 
  network: 86535
  cosmetic: 89133
  scriptlet: 21967
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 52381-172, 4h.2m
    block-lan: 43-0, 4h.2m
    ublock-annoyances: 4354-147, 4h.2m
  default: 
    user-filters: 87-0, never
    easylist: 66557-90, 4h.2m
    easyprivacy: 26907-214, 4h.2m
    plowe-0: 3679-806, 4h.2m
    ublock-abuse: 75-0, 4h.2m
    ublock-badware: 4109-93, 4h.2m
    ublock-filters: 30965-446, 4h.2m
    ublock-privacy: 213-2, 4h.2m
    ublock-quick-fixes: 183-4, 4h.2m
    ublock-unbreak: 1767-46, 4h.2m
    urlhaus-1: 8492-0, 4h.2m
filterset (user): [array of 87 redacted]
trustedset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 20 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1344 ms (selfie)
  maxAssetCacheWait: 227 ms

```

### Other details:

Adding the below rule using the uBlock Origin element picker removed the placeholder, however there may be a better rule to use than the one from the element picker.

`outlook.live.com##._BAY1XlyQSIe6kyKPlYP`

**Comment by Yuki2718** [comment]
Is this safe? I don't even see the class.

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets/pull/12517
Probably the class changes randomly.
