### ISSUE TITLE
www.cnx-software.com banner ads

### ISSUE THREAD

**Issue by maurerr** [easylist/easylist#11853]
### List the website(s) you're having issues:

`www.cnx-software.com](https://www.cnx-software.com/2022/04/28/khadas-vim4-review-part-1-unboxing-kit-assembly-and-first-boot-with-oowow/`

### What happens?

banner ads hosted internally

### List Subscriptions you're using:

default uBlockOrigin filters, easylist, easyprivacy

### Your settings

- OS/version: Windows 10 19H2
- Browser/version: Chromium 100.0.4896.88
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:

![image](https://user-images.githubusercontent.com/7603227/165748396-81e62690-0658-4723-80aa-b88d00572a0a.png)

**Comment by maurerr** [comment]
fix adblock rule is
`cnx-software.com##.gxmas`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/d26ba8b02984bff57e781efec16b577118970d6e
