### ISSUE TITLE
VGlive.no - Blocked provider (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#1185]
### List the website(s) you're having issues:
`https://vglive.no/`
(Probably other sites too)

### What happens?:
Third party provider is blocked, so scoreboards can't be shown.
Also, users can't log in!

### Example:
`https://vglive.no/tournaments/seasons/104/standings/`

### Screenshots:

* Scoreboards:
![filterissue-vglive1](https://user-images.githubusercontent.com/9382674/40378177-4b11769e-5de2-11e8-88d4-3549a23bc10c.jpg)

* After clicking on the login button:
![filterissue-vglive2](https://user-images.githubusercontent.com/9382674/40378306-b24404d0-5de2-11e8-98d4-e70ee6a37c0c.jpg)

### Problem filter:
EasyPrivacy

### Problem rule:
`||cis.schibsted.com^`

### Possible fix:
`@@||cis.schibsted.com^$domain=schibsted.no|vglive.no`
..but the whole domain should probably be whitelisted all together, like this:
`@@||cis.schibsted.com^`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.2 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4 (XUL)

**Comment by ryanbr** [comment]
Removed.
