### ISSUE TITLE
ask.fm

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#11858]
annoying overlay
- `https://ask.fm/otbakh`

```
||d3r6ceqp4shltl.cloudfront.net/assets/application-
```

**Comment by ryanbr** [comment]
Doesn't fix the overlay ^ @smed79

**Comment by smed79** [comment]
Do you mean you can't scroll the page ?

**Comment by ryanbr** [comment]
I still get the overlay when I load the site @smed79

**Comment by krystian3w** [comment]
Pop-up with text "unlock functions" may now use new subdomain.
