### ISSUE TITLE
yplay.de

### ISSUE THREAD

**Issue by VolatileCable** [easylist/easylist#11884]
`https://yplay.de/internet-und-telefon/verfuegbarkeit-pruefen/`

The service availability check breaks when the cookie banner is blocked. I guess because of a missing consent cookie.

Caused by Easylist Cookies
`yplay.de##+js(abort-on-property-read, realCookieBanner)`

To test if it's working you can try entering '6' in the PLZ field and it should suggest values.

The flow make it work with allowed consent form, you have two options:
1) Either have to accept all cookies (The first overlay banner's blue button)
2) Only accept necessary cookies (gray button), in which case it will prompt you again with another banner for google cookies under the availability form

Neither of them show with the filter active.

My system:
uBo, Chrome
Lists:
uBo builtin filters, EasyList, EasyPrivacy, Online Malicious, EasyCookie, PeterLoweAd, EasylistDEU

**Comment by ryanbr** [comment]
Which menu option is the service availability check? @VolatileCable

**Comment by VolatileCable** [comment]
Sorry about the late reply; I accidentally had notifications off.

Also I'm not sure what you mean by menu option. The availability check is the link in the code tag.

**Comment by VolatileCable** [comment]
But just incase, it's "Internet & Telefon" > "Verfügbarkeit prüfen"

**Comment by ryanbr** [comment]
Works for me @VolatileCable I click on `Verfügbarkeit prüfen` opens the https://yplay.de/internet-und-telefon/verfuegbarkeit-pruefen/ page. Tested in Brave + FF.

**Comment by VolatileCable** [comment]
@ryanbr It's not about opening the page itself from the menu, but about the service check on the page itself. I've already explained the issue in great detail in the first post.. This widget here is at fault:
![easylist yplay](https://user-images.githubusercontent.com/54342781/168453339-a8d94db7-9f4b-4d44-8d64-7be6d49967db.png)

**Comment by ryanbr** [comment]
Well the widget loads, and fed it some fake details. so everythhing is fine?

**Comment by VolatileCable** [comment]
I just tested it some more after reading your last message, which for some reason is gone now.

I created a new Firefox profile with only UBlock + defaults (which has EL DEU for me) and EL Cookie and there weirdly enough it does show the cookie prompt and subsequently the check works. But in a new Chrome profile I created with the same settings it doesn't show the cookie prompt.

For both it shows the yellow defuser script entry "yplay.de##+js(abort-on-property-read, realCookieBanner)" in the logger, but it seems to have differing behaviour in Chrome, I guess? Also as this filter entry is in EL Cookie, it does work with ublock default lists.

And about the usefulness of this endeavor: As far as I can tell the check always returns "false" for any address and serves no real purpose yet, I doubt many people care about this local ISP's site, I fixed it for myself already and it appears this is possibly a deeper problem. I don't want to waste more of your (and mine) time, so if you want you can just close it.

**Comment by ryanbr** [comment]
Sure, realCookieBanner seems to be quite popular so aslong as its not causing issues.
