### ISSUE TITLE
positivr.fr

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#11895]
### List the website(s) you're having issues:

`https://positivr.fr/plant-moms-les-conseils-pour-verdir-nos-interieurs-fleurissent-sur-tiktok/`

### What happens?

Fixed small player in right corner.

### List Subscriptions you're using:

Fanboy Annoyances

### Your settings

- OS/version: Windows 10 Pro 21H2
- Browser/version: Firefox 102 Nightly
- Adblock Extension/version: uBlock Origin 1.42b5

### Other details:

Possible use something like:

`positivr.fr##.viously-sticked.viously-sticked-top-right`

".viously-sticked-top-right" is optional, so can works too `##.viously-sticked`

**Comment by Lairub** [comment]
If cover for uBO only this also works great:
```
! disable filters for ABP only
positivr.fr#@#.viously-sticked.viously-sticked-top-right
positivr.fr#@#.viously-sticked
! uBO solution
positivr.fr##.viously-sticked:style(position: absolute;  top: 0 !important;  left: 0 !important;  bottom: 0 !important;  right: 0 !important;  width: 100% !important;  height: 100% !important;  z-index: 1 !important;  display: block !important;)
positivr.fr##.viously-sticked #unstick-button
```

**Comment by ryanbr** [comment]
Why are we blocking this? maybe in listfr?
