### ISSUE TITLE
reddit.com: ad audio playing in background while scrolling

### ISSUE THREAD

**Issue by mica** [easylist/easylist#11904]
As you scroll through reddit, periodically, in the spots where video ads usually get inserted, audio from said ads starts playing in the background. Here's a little snippet from the uBlock logger from where it starts:

| +172 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_audio.mp4` |
| +172 |  |  | `www.reddit.com` | 1 | xhr | `https://gql.reddit.com/` |
| +171 |  |  | `www.reddit.com` | 1 | xhr | `https://gql.reddit.com/` |
| +170 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_720.mp4` |
| +170 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_audio.mp4` |
| +169 |  |  | `www.reddit.com` | 1 | xhr | `https://gql.reddit.com/` |
| +169 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_audio.mp4` |
| +169 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_720.mp4` |
| +169 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_audio.mp4` |
| +169 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_720.mp4` |
| +169 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_audio.mp4` |
| +169 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_720.mp4` |
| +169 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_480.mp4` |
| +169 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_360.mp4` |
| +169 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASH_240.mp4` |
| +168 |  |  | `www.reddit.com` | 3 | xhr | `https://v.redd.it/67x1yth7adq81/DASHPlaylist.mpd?a=1654211122%2CZTY2NDYyMGUzYjIzN2YwNzIyZGI4MjU1YTQ0MjA4NmEwYjc4OTc2MjlmNDczMDFjZWJlN2U0OGMwZjRhNzJhYw%3D%3D&v=1&f=sd` |

**Comment by ryanbr** [comment]
Does just blocking `https://v.redd.it^*/DASHPlaylist.mpd` block it @mica ? also does it cause any issues with the site.

**Comment by mica** [comment]
That prevents all reddit-hosted videos from loading

**Comment by ryanbr** [comment]
`||v.redd.it^*/DASH_` then? @mica

**Comment by ryanbr** [comment]
Closing, no response. and probably will cause issues with other content.

**Comment by mica** [comment]
> `||v.redd.it^*/DASH_` then?

Same issue. Both regular videos and ads use the same url format. Would be nice to reopen this and continue looking for a solution.

**Comment by krystian3w** [comment]
Then try ask on reddit: https://www.reddit.com/r/uBlockOrigin/

**Comment by mica** [comment]
Wouldn't it be nice to resolve this for easylist? Seems like it belongs here. Closing this before it's resolved is a wasted opportunity, @ryanbr

**Comment by krystian3w** [comment]
Maybe no without spinnets, then can help wrote fix compatible with uBo or AdGuard - but sometimes change only syntax no help and ABP Filters (anti-cv) need manually debug page and write own solution if was rejected in EasyList.

**Comment by ryanbr** [comment]
If there is a way to implement a fix, we would. But without causing false positives. we can't "Fix" this

**Comment by krystian3w** [comment]
If page use `video` or `audio` tag then possible use `:remove()` in `filters.txt` or `filters-2022.txt`.
