### ISSUE TITLE
di.fm/content/volunteer-channel-application

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#11917]
### List the website(s) you're having issues:

`https://www.di.fm/content/volunteer-channel-application`

### What happens?

Ad

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly 102
- Adblock Extension/version: uBO 1.42.5b3

### Other details:

![DIFM-Ad](https://user-images.githubusercontent.com/95879668/166931459-b3b7bdf0-578f-453c-a34e-8231552c8fa9.png)

**Comment by ryanbr** [comment]
Self promo on the embedded form, up'd into annoyances instead.
