### ISSUE TITLE
dongknows.com anti-adblock 

### ISSUE THREAD

**Issue by Pentaphon** [easylist/easylist#11941]
### List the website(s) you're having issues:
`https://dongknows.com/how-to-fix-wi-fi-dropping-and-disconnection-issues/`

### What happens?

When you go to this link or any page on this site, there is an adblock warning that dims the page, displays this message, and keeps you from scrolling further

### List Subscriptions you're using:

All of uBO's custom filter lists: checked
EasyList: checked
Peter Lowe’s Ad server list: checked
EasyPrivacy: checked
Online Malicious URL Blocklist‎: checked
### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 100
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:
![Screenshot 2022-05-08 at 00-42-23 Wi-Fi Dropping 2022's Best Tips Dong Knows Tech](https://user-images.githubusercontent.com/49374058/167286783-df61fe41-0732-4866-98a6-35f6844b2ed6.png)

**Comment by ryanbr** [comment]
Anti-adblock, submit in https://github.com/uBlockOrigin/uAssets
