### ISSUE TITLE
Remove domain from adservers list

### ISSUE THREAD

**Issue by synthXR** [easylist/easylist#11950]
Please remove the domain cubics.com from the adservers list. It is not an adserver anymore and our users seem to experience issues because the site appears on https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers.txt

### List the website(s) you're having issues:

https://cubics.com

### What happens?

Site keeps getting blocked by addons using Easylist

Thank you

**Comment by ryanbr** [comment]
Was adjusted to third-party to avoid false positive
