### ISSUE TITLE
Issue #6140 [reopen-reopen]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#11960]
Why was this closed again, without being fixed?
The problem is still present!

Full report here:
https://github.com/easylist/easylist/issues/6140/

**Comment by ryanbr** [comment]
What exactly is the issue, I had no issues on https://www.rollingstone.com/

**Comment by THEtomaso** [comment]
> What exactly is the issue

Nothing happens when clicking on "**Log In**", because of this filter:
* **EasyPrivacy**
`/rollbar.min.js`

**Comment by DandelionSprout** [comment]
I can indeed confirm the problem, and that clicking on the "Log in" button in the upper right doesn't do anything no matter how many times I click on it.
