### ISSUE TITLE
Twitch embed PSOD (perhaps not site- but rather widget-specific)

### ISSUE THREAD

**Issue by CherrySG379** [easylist/easylist#11991]
hello! just started having issues this morning watching a `twitch.tv` embed (stream now finished) through a site called `aqstream.com` where a purple screen pops up for random 30-second intervals asking me to go to the main stream page and turn off adblocker and the like. never seen it before but Google results say it's a long-running issue called the Purple Screen of Death (hence the acronym in the issue title). another user on the site mentioned using uBlockOrigin and having the same issue, and then I saw this mentioned in the changelog for this filter, so I thought I'd ask here about what might've changed recently that I'm suddenly seeing this screen but never before. unless Twitch changed something their end perhaps? 
when the issue first happened I had this filter and the default ABP filters, but it's still happening after adding the CPBL and Fanboy filters respectively and refreshing the page. issue seems to pop up whether or not I have ABP on or off.
system is Win10 Pro 21H2 (oh dear it just updated, is that the culprit somehow?), browser is Chrome version 101.0.4951.64 (Official Build) (64-bit), ABP version 3.12

### List the website(s) you're having issues:

`aqstream.com`, `twitch.tv`

### What happens?

"purple screen of death" I've never seen before but which is apparently a common Twitch issue especially with embeds. idk why I'm only seeing it this morning though

### List Subscriptions you're using:

initially:
ABP filters, EasyList (also "Allow nonintrusive advertising" but idk if that counts)

now also:
CPBL Filters for ABP & uBO, Fanboy's Notifications Blocking List

issue persists

### Your settings

- OS/version: Windows 10 Pro 21H2
- Browser/version: Chrome 101.0.4951.64 (Official Build) (64-bit)
- Adblock Extension/version: ABP 3.12

**Comment by CherrySG379** [comment]
also, sorry, first post, looks like I completed it wrong, sorry

**Comment by ryanbr** [comment]
I'm not seeing aqstream, I'm careful to make a block esp if it involves something as large as twitch.tv
