### ISSUE TITLE
http://www.thefreedictionary.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#12]
`http://www.thefreedictionary.com/test`

Grammarly ads.

Original report: https://forums.lanik.us/viewtopic.php?f=62&t=26605

**Comment by mapx-** [comment]
||img.tfd.com^$image
@@||img.tfd.com/*.$image
||thefreedictionary.com^$image

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/55cc9fc18b92422ce7bf17ee312fd2cd6636c9ab
