### ISSUE TITLE
http://www.complaintsboard.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#120]
`http://www.complaintsboard.com/`

BDomains ad at end of right column.

@ryanbr @monzta @Khrin @nitrox @Hubird-au @palant 
Please check the issue list here on github. I was banned on the lanik forum so this is the only way I can report filter issues. Thanks!

**Comment by ryanbr** [comment]
Don't abuse tags, or you'll be blocked from here too.

**Comment by terrorist96** [comment]
:disappointed: 
How else am I supposed to get someone's attention?
And why are you closing this? The ad is still there.
