### ISSUE TITLE
fastweb.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#12013]
### List the website(s) you're having issues:

`https://www.fastweb.com/career-planning/articles/the-35-weird-but-cool-college-majors`

### What happens?

Three placeholders early on in the article, measured to 822x51px each for a total of 822x153px of space.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/22780683/168390170-0c3dd5e3-1618-4e9d-822e-d20bec0df35d.png)

</details>

### Your settings

- OS/version: Windows 11 x64
- Browser/version: Chrome 101.0.4951.64 x64
- Adblock Extension/version: uBO 1.42.4 + IDCAC 3.3.9

### Other details:

I propose `fastweb.com##div[id^=FastWeb_Desktop_Native_]`

Screenshot:
<details>

![image](https://user-images.githubusercontent.com/22780683/168390366-4dd58060-77d2-4149-9438-18abac9c26c1.png)

</details>

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c2e7dae9b9f54d866e82d8d29914aa395ca41d1e
