### ISSUE TITLE
Unblockable Trackers

### ISSUE THREAD

**Issue by KARINA76756** [easylist/easylist#12021]
Please add the rules below to the EasyPrivacy filter. The tracker is right. However, there is no rules below in the EasyList filter. For reference, I found it myself. Copy the rules below and add it to EasyPrivacy. If you added, please reply. thank you.

||firebase*.googleapis.com^
||coc-fever.naver.com^
||auth.buzzvil.com^
||screen.buzzvil.com^
||*-analytics.
||analytics
||www.googleadservices.com^
||events.data.microsoft.com^
||amazonclix.com^
||amazonaax.com^
||nelo2-col.navercorp.com^
||mplweb.ahnlab.com^
||mqtt-mini.facebook.com^
||affiliationjs.s3.amazonaws.com^
||advertising-api-eu.amazon.com^
||etm.tech^
||advice-ads..amazonaws.com^
||mon-normal-c-useast1a.tiktokv.com^
||mon-*.tiktokv.com^
||mssdk-sg.tiktokv.com^
||gos-api.gos-gsp.io^
||gecko-sg.tiktokv.com^

- OS/version: Androud 12
- Browser/version: Edge
- Adblock Extension/version: AdGuard

**Comment by ryanbr** [comment]
Just install Easyprivacy. and re-test. Any missing trackers create a `report for each site.`
