### ISSUE TITLE
sbofficial.in

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#12023]
### List the website(s) you're having issues:

`https://www.sbofficial.in/the-kashmir-files`

### What happens?

unblocked ads
amazon promotions

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win 10
- Browser/version: firefox /opera
- Adblock Extension/version: 1.42.4

**Comment by ryanbr** [comment]
Not perfect, and plenty of empty space, but blocking will cause false positives.

**Comment by ghajini** [comment]
ok for blank space 
ad is left of upstox
![image](https://user-images.githubusercontent.com/20338483/169224632-668ccede-19ca-498b-adc2-22f68da4b07a.png)

filter
`sbofficial.in##[href^="https://link.upstox.com/"]`

also do you get performance issue when using this website?
