### ISSUE TITLE
Gambling license seal and link are blocked on many licensees, e.g. https://www.lottokings.com/

### ISSUE THREAD

**Issue by npetevn** [easylist/easylist#12049]
### List the website(s) you're having issues:
`https://www.lottokings.com/`

### What happens?
The gambling license seal and link of Antillephone, a master license holder in charge of keeping gambling sites under compliance, that are blocked.

### List Subscriptions you're using:
EasyList Privacy

- OS/version: OSX
- Browser/version: Chrome
- Adblock Extension/version: uBlockOrigin

### Other details:
We noticed you blocked the main domain + all subdomains of Antillephone in [this commit](https://github.com/easylist/easylist/commit/15068df3b24020eff6e83aa25e30038ad7fe1bb1). The site in relation to which you blocked it (`https://csgolounge.com/`) is no longer using them, but there are plenty of other gaming sites that do - e.g. `https://www.lottokings.com/`.
The major points of this seal are to:
  - trigger a warning of a scam site that has just copied the html of a duly licensed one (happens extremely often)
  - assure the master license holder that geo-targeting compliance rules are not broken by the licensee - e.g. users from specific country are not allowed, as the licensee's word cannot be taken for granted
  - link to a page, validating for the actual users that the licensee is in fact legit and if they need, they can launch complaints from there in front of the regulator
  - ensure the license validating page is not too easy to spoof - i.e. the links are temporary and can only be issued from sites that have the seal in place
 All of the above is achieved from serving through a CDN the apg-seal.js, which inserts a timestamped image (the logo of the licensing company) and a timestamped temporary link to the validating page. All those resources are cached on the CDN side based on the country of the user and are also cached on the browser side (which you can verify) so they cannot be used for tracking. They are however both useful to the sites and to the site users.

As an additional feature, the master license holders like to get shiny charts of page loads and country distribution, so a beacon pixel is served as well. It is not used for fingerprinting and tracking, but I agree this cannot be proven in a satisfactory way. The beacon pixel itself is not vital to the license.

I suggest you change the blocking entry from all subdomains, to a specific one only for the beacon pixel - `/54f396e0-b046-49b1-9cb3-0c69281d7ea9-beacon.png`, served on subdomains of `antillephone.com`.

**Comment by npetevn** [comment]
The seal itself should not be a privacy concern, mainly due to the browser caching (the CDN caching I listed cannot be proven, I agree on that). This seal is also not an ad, as it links to a validation page that is of interest to the site and it's users.

The beacon pixel is not cached and so can be used to violate user privacy. That's why I propose to block it specifically, I'm not asking to violate your policies on that.

**Comment by ryanbr** [comment]
We have to be consistent, we cannot make one rule for one seals provider and not apply here. I've moved the filter to the appropriate (seals) section. If we removed this, we would get requests from other seals providers proclaiming the same thing.

**Comment by npetevn** [comment]
I don't understand the inconsistency in question and which other seal providers you have in mind. This particular seal is needed by the users on the sites as they look for it and the company info it links to both to validate the site is not going to scam them for their money and to have a contact to the regulating body in case of disputes.
As it is also useful and needed by the site owners, if you do not address it in a way that works for them, they will have to add adblock detection to their sites of some sort or another and advise on whitelisting. As those whitelists are global, they will allow the beacon pixel (which again, is not used for user tracking, but easily can be), which kind of defeats the privacy goal.

**Comment by npetevn** [comment]
Kindly ask for a response to my last question and reconsidering/reopening this issue.
