### ISSUE TITLE
9anime.is

### ISSUE THREAD

**Issue by TheMather1** [easylist/easylist#1204]
### List the website(s) you're having issues:

`https://www4.9anime.is/`

### What happens?

Video element blocked.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome (Official Build) (64-bit)/66.0.3359.181
- Adblock Extension/version: AdNauseam/3.3.403

### Other details:

Applying the following exception filters fixes the issue:
`9anime.is#@#[id*="ScriptRoot"]`
`9anime.is#@#div[id^="MarketGid"]`
`9anime.is#@#[id*="MarketGid"]`
`9anime.is#@##rc-row-container`
`9anime.is#@#.rc-item-wrapper`
`@@||trends.revcontent.com/serve.js.php$script,domain=9anime.is`
`@@||jsc.mgid.com/9/a$script,domain=9anime.is`
`@@||servicer.mgid.com$script,domain=9anime.is`

**Comment by Khrin** [comment]
Website is dead.
