### ISSUE TITLE
francebleu.fr

### ISSUE THREAD

**Issue by lica98** [easylist/easylist#12055]
### List the website(s) you're having issues:
`https://www.francebleu.fr/infos/meteo/chaleur-plusieurs-records-de-temperature-battus-ou-egales-ce-mercredi-1652892079`

### What happens?
facebook and twitter icons are blocked

### List Subscriptions you're using:
 Fanboy's Annoyances

### Your settings

![image](https://user-images.githubusercontent.com/74957561/169171977-5c3ce579-9063-4e55-8d7d-e17ef191a821.png)

**Comment by lica98** [comment]
now the whole panel got completely blocked 😕

**Comment by Khrin** [comment]
> now the whole panel got completely blocked 😕

Which is the purpose of the _Fanboy's Social list_, included into the _Fanboy's Annoyances List_. (https://www.fanboy.co.nz/)

If you don't want to see social buttons blocked, just don't use the list.

**Comment by lica98** [comment]
> > now the whole panel got completely blocked 😕
> 
> Which is the purpose of the _Fanboy's Social list_, included into the _Fanboy's Annoyances List_. (https://www.fanboy.co.nz/)
> 
> If you don't want to see social buttons blocked, just don't use the list.


but for example [here](https://github.com/AdguardTeam/AdguardFilters/issues/118033) I had a similar issue and he didn't block the panel but instead unblocked the logo 🤔
