### ISSUE TITLE
ClasOhlson.com - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#12067]
### Affected site:
`https://www.clasohlson.com/`

**Note:**
Depending on your location, you'll get redirected to the appropriate subdirectory.
In my case, this is `https://www.clasohlson.com/no/`.

### Issue:
Grey modal overlay / unclickable items.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
`##.cookie-bar:not(body):not(html)`
`###js-cookie-notification`

### Possible fix:
`clasohlson.com##.cookie-bar-overlay`

### Other problem filters:
* ~~**AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/119290/~~ _(FIXED)_
~~`##.cookie-bar:not(body)`~~

* **I don't care about cookies** _(@kiboke)_
`~cafe-royal.com,~rituals.com##.cookie-bar:not(body):not(html)`
`##.cookie-bar__container`
`###js-cookie-notification`

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: Pale Moon v29.4.6 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by ryanbr** [comment]
```
clasohlson.com##.cookie-bar-overlay
clasohlson.com##body,html:style(overflow: auto !important; position: initial !important;)
```

Does that work for you @THEtomaso

**Comment by kiboke** [comment]
Thanks @THEtomaso it will be fixed today in IDCAC.

**Comment by THEtomaso** [comment]
> ```
> clasohlson.com##.cookie-bar-overlay
> clasohlson.com##body,html:style(overflow: auto !important; position: initial !important;)
> ```
> 
> Does that work for you THEtomaso

Sure.
That first rule (which is the one that I suggested in my first post) seems to be sufficient though.
The CSS rule doesn't appear to be needed in this case (at least not when connecting from my location).

**Comment by DandelionSprout** [comment]
I sadly can't add `clasohlson.com##.cookie-bar-overlay` as a tempfix; it'd have to be whitelisting entries only, from my understanding of how anti-ad lists work like.

**Comment by THEtomaso** [comment]
> as a tempfix; it'd have to be whitelisting entries only

Well, in the case of modal overlays, blocking them doesn't really break anything, even if users aren't using additional cookie filters.
The idea behind them is simply to make coexisting popups somewhat more visible.

So, which alterative is the worst?
A missing overlay, which only results in a popup which stands out slightly less then before, on a purely cosmetical level?
..or a page that is broken, and doesn't work at all?
