### ISSUE TITLE
money.ro

### ISSUE THREAD

**Issue by CannedWater** [easylist/easylist#12073]
### List the website(s) you're having issues:
`https://www.money.ro/top-7-cele-mai-ieftine-masini-hibrid-pe-care-le-poti-cumpara-in-romania/`

### What happens?
`exejuudkhvm.exactdn.com/wp-content/uploads/2022/05/279085209_1949018861952383_1657499025380174235_n.png?strip=all&lossy=1&ssl=1`

### List Subscriptions you're using:
uBO ebd (eng, PC) + ro-adblock lite

### Your settings

- OS/version: macOS
- Browser/version: Google Chrome
- Adblock Extension/version: uBO

### Other details:
Could this be addressed in EasyPrivacy?

Also, could you take a look at `https://confection.io/trackers/exactdn-com/`?

**Comment by ryanbr** [comment]
Nup, this is an advert. should be sorted via ro regional list.

**Comment by CannedWater** [comment]
@ryanbr https://publicwww.com/websites/exactdn.com/
