### ISSUE TITLE
cnn.com

### ISSUE THREAD

**Issue by CannedWater** [easylist/easylist#12074]
### List the website(s) you're having issues:
`https://www.cnn.com/`
`https://www.cnn.com/2022/05/19/us/blackouts-summer-heat-extreme-weather/index.html`

### What happens?
Advertising 

### List Subscriptions you're using:
uBO enabled-by-default (PC, english)

### Your settings

- OS/version: macOS
- Browser/version: Google Chrome
- Adblock Extension/version: uBO

### Other details:
I encountered advertising using a US IP.

Are:
```
cnn.com###partner-zone
cnn.com###story-bottom > .zn__background--content-relative.l-container > .zn__containers
cnn.com#?#.zn--idx-11.zn-ondemand.zn-loaded.zn-has-9-containers.zn-has-multiple-containers.t-light.zn--ordinary.zn-balanced.zn-homepage4-zone-6.zn:-abp-contains(Paid Partner Content)
```
good filters?

**Comment by ryanbr** [comment]
Looks fine here

**Comment by CannedWater** [comment]
<img width="1509" alt="for EasyList issue report" src="https://user-images.githubusercontent.com/105892020/169436482-01873e7c-0fb4-4967-94d8-f812650d2fe1.png">

**Comment by CannedWater** [comment]
And @ryanbr , did you scroll on `https://www.cnn.com/` with a US IP address in order to encounter "Paid Partner Content"? (I'm not blaming you, I'm just trying to help)
