### ISSUE TITLE
rambox.app cookie notice

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#12089]
### List the website(s) you're having issues:
`https://rambox.app`

### What happens?
Cookie notice on the bottom right

### List Subscriptions you're using:
EasyList Cookie

### Your settings

- OS/version: Windows
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin

### Other details:
https://user-images.githubusercontent.com/17685483/169680782-aa4079b1-66b3-4601-a41d-92ff6b7451de.png

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6a0aa738984b62cf6c274b592ac7e399f4e4cde5
