### ISSUE TITLE
adblock detected https://finance.yahoo.com/

### ISSUE THREAD

**Issue by motovate** [easylist/easylist#12090]
### List the website(s) you're having issues:

`https://finance.yahoo.com/`

### What happens?

Popup

### List Subscriptions you're using:

uBlock Origin: 1.42.4
Firefox: 91
filterset (summary): 
  network: 90336
  cosmetic: 107053
  scriptlet: 21286
  html: 664
listset (total-discarded, last updated): 
  added: 
    adguard-spyware-url: 603-14, 43m
    block-lan: 43-0, 43m
    fanboy-annoyance: 71205-297, 43m
    ublock-annoyances: 4434-4, 43m
  default: 
    user-filters: 26-1, never
    ublock-filters: 32056-32, 38m
    ublock-badware: 4132-3, 37m
    ublock-privacy: 219-0, 36m
    ublock-abuse: 75-0, 35m
    ublock-unbreak: 1801-5, 34m
    ublock-quick-fixes: 186-0, 33m
    easylist: 67359-611, 32m
    easyprivacy: 27058-579, 31m
    urlhaus-1: 8181-0, 30m
    plowe-0: 3671-3, 29m
![yahoo](https://user-images.githubusercontent.com/54693336/169719565-34da63a0-2af4-4df2-8fde-7c4313971f33.png)

**Comment by ryanbr** [comment]
we won't touch anti-adblock @motovate

**Comment by ghajini** [comment]
@motovate 
report here anti-adblock issues

https://github.com/uBlockOrigin/uAssets/issues
