### ISSUE TITLE
https://extratorrent.cc/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#121]
`https://extratorrent.cc/`

VPN ad

**Comment by monzta** [comment]
Seems to be taken care of already.

**Comment by terrorist96** [comment]
@monzta I see the ads still.

![1](https://cloud.githubusercontent.com/assets/12802056/20867574/2358dbfe-ba16-11e6-873c-ec891e3a6e79.PNG)

Inside a torrent description:
![2](https://cloud.githubusercontent.com/assets/12802056/20867575/235ad710-ba16-11e6-92fc-45a4e663c20e.PNG)
