### ISSUE TITLE
nydailynews.com "free account" prompt

### ISSUE THREAD

**Issue by Pentaphon** [easylist/easylist#12109]
### List the website(s) you're having issues:
`https://www.nydailynews.com/new-york/nyc-crime/ny-manhattan-subway-shooter-surveillance-images-nypd-20220523-253pzvdf5bbitldwswvyrkqj2m-story.html`

### What happens?

Fullscreen page blocker/prompt to make a "free account" by typing in your email before reading news article

### List Subscriptions you're using:

Default uBlock settings

### Your settings

- OS/version: Ubuntu 22.04
- Browser/version: Firefox 100.0.2
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:

![Screenshot 2022-05-24 at 10-12-36 New York Daily News](https://user-images.githubusercontent.com/49374058/170094632-bab30315-c5c5-464a-a61a-54ce3faf75b6.png)

**Comment by ryanbr** [comment]
Can't touch the paywall, but `||assets.zephr.com/zephr-browser/$script,domain=www.nydailynews.com` should help as a personal filter
