### ISSUE TITLE
game-state.com

### ISSUE THREAD

**Issue by Branzeturi** [easylist/easylist#12102]
### List the website(s) you're having issues:
`https://www.game-state.com/`

### What happens?
Unhiden element or elements

### List Subscriptions you're using:
uBO enabled-by-default (PC, english)

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome
- Adblock Extension/version: uBO

### Other details:
Is `game-state.com##.box[style="width: 358px;"]` a good filter?

**Comment by ryanbr** [comment]
Too minor.
