### ISSUE TITLE
All urls with *com/banners/* getting blocked

### ISSUE THREAD

**Issue by TheodoorP** [easylist/easylist#12111]
### List the website(s) you're having issues:
`*com/banners/*`
(example) `https://pivity.com/banners/pivity-dark.png`

### What happens?

Any url that contains `*com/banners/*` is currently getting blocked.

I presume the intention was to only block these urls for the `pingdom.com`, `thetvdb.com`, and `tooltrucks.com` domains, but that doesn't seem to be working.

The second url I linked as an example is only serving an image, and shouldn't be blocked I think?

### List Subscriptions you're using:

easylist_general_block.txt

### Your settings
- OS/version: Windows 11 22000
- Browser/version: Firefox 100
- Adblock Extension/version: ublock 1.42.4

### Other details:

The rule causing this issue seems to be the following: https://github.com/easylist/easylist/blob/e989c11992e466778470117ad2d8be4891a48d1c/easylist/easylist_general_block.txt#L7252

This is the output of the ublock logger regarding that image getting blocked:
![image](https://user-images.githubusercontent.com/17050455/170230972-844c9671-bed3-462f-b022-521bd667fae6.png)

**Comment by JobcenterTycoon** [comment]
`~` negate it. So `domain=~example.com` get applied to all domains except `example.com`

On your example `pivity.com` i see no blocked images

**Comment by TheodoorP** [comment]
> `~` negate it. So `domain=~example.com` get applied to all domains except `example.com`. The filter works as expected
> 
> On your example `pivity.com` i see no blocked images.

Ah okay gotcha, that makes sense on why it's getting blocked then. 

As for the `pivity.com` domain, there is indeed not any images blocked on front facing pages, but we currently use the `/banners/pivity-dark.png` image in our meta tags. So our brand image currently isn't embedded on any external page relying on og tags.

I don't mind moving the images to a different directory, I'm just not too certain why such a specific directory is being blocked in the first place?

**Comment by ryanbr** [comment]
Changing the folder name would be easiest. com/banners/ is a common location for hosted ad images.
