### ISSUE TITLE
Nu.nl

### ISSUE THREAD

**Issue by M1Aston** [easylist/easylist#12126]
### List the website(s) you're having issues:

Nu.nl

### What happens?

Page\website stopsloading at "cookie level\message"

### List Subscriptions you're using:

Easylist Cookie list

### Your settings

- OS/version: Android
- Browser/version: Fennec
- Adblock Extension/version: ublock

**Comment by ryanbr** [comment]
Can't get around this consent @M1Aston  breaks too much .
