### ISSUE TITLE
Meteoblue.com

### ISSUE THREAD

**Issue by M1Aston** [easylist/easylist#12127]
### List the website(s) you're having issues:
meteoblue.com

### What happens?
Cookie message not removed

### List Subscriptions you're using:
Easylist

### Your settings

- OS/version: Android
- Browser/version: Fennec
- Adblock Extension/version: ublock

**Comment by ryanbr** [comment]
No cookie messages are being shown here in Firefox/uBO. (same in desktop) @M1Aston  Clear cache and update?

**Comment by M1Aston** [comment]
Thanks for your quick reply.
First of all, I also use the Cookie list (I didn't mention that before).
After accepting the cookie{s} everything works normally until cache, cookies, etc. are deleted. Then this message pops up again
![Screenshot_20220527-070251](https://user-images.githubusercontent.com/43113612/170633336-bd13377e-3fde-48b8-90ec-af8a794daea2.png)
:

**Comment by einstein95** [comment]
Was able to replicate, filter to block it is
```
||meteoblue.com##.gdpr-message
```
"Adguard Annoyances" has this filter which covers it
```
meteoblue.com,ajinomoto.co.jp,wsj.com##.gdpr-message
```
