### ISSUE TITLE
MilwaukeeTool.eu - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#12139]
### Affected site:
`https://www.milwaukeetool.eu/`

### Issue:
Unclickable / non-working elements, due to a blocked cookie consent, which needs to be accepted!
E.g.; the "PRODUCTS" menu doesn't work.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
`###onetrust-banner-sdk`
`###onetrust-consent-sdk`

### Possible fix:
`milwaukeetool.eu#@##onetrust-banner-sdk`
`milwaukeetool.eu#@##onetrust-consent-sdk`

### Other problem filters:
* **AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/120111/
`###onetrust-consent-sdk`
`||cookielaw.org^$third-party`

* **I don't care about cookies** _(@kiboke)_
`~msn.com,~eurogamer.net,~rtlxl.nl,~zdf.de,~crfashionbook.com,~rockpapershotgun.com,~zdnet.com,~mensjournal.com,~cbsnews.com,~cbslocal.com,~assetstore.unity.com,~gmx.com,~gmx.es,~gmx.fr,~gmx.co.uk,~mail.com,~kruidvat.nl,~kruidvat.be,~trekpleister.nl,~tvn24.pl,~popsugar.co.uk,~rte.ie,~tunein.com,~oe24.at,~sika.com,~merkurmarkt.at,~boomerang-tv.pl,~cnbc.com,~1001spiele.de,~dhl.de,~sport.pl,~reisetopia.de,~mtvuutiset.fi,~billa.at,~aerztezeitung.de,~okazii.ro,~credit-suisse.com,~avisendanmark.dk,~blaklader.at,~blaklader.be,~blaklader.ca,~blaklader.com,~blaklader.cz,~blaklader.de,~blaklader.dk,~blaklader.ee,~blaklader.es,~blaklader.fi,~blaklader.fr,~blaklader.ie,~blaklader.it,~blaklader.nl,~blaklader.no,~blaklader.pl,~blaklader.se,~blaklader.uk###onetrust-consent-sdk`

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: Pale Moon v29.4.6 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by kiboke** [comment]
Thanks @THEtomaso it will be fixed in IDCAC.
