### ISSUE TITLE
[EasyList] Some breakages in Persian websites

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#12147]
Hi, I've created a new Persian filterlist ([PersianBlocker](https://github.com/MasterKia/PersianBlocker)) that might possibly replace the current regional list in uBlock Origin (adblock-iran); in doing so I've encountered some breakages coming from EasyList and I've marked them with "TODO" in my list which you can check out.

Please feel free to make changes to my suggested solutions in order to suit EasyList's syntax or to reduce their broadness.
Also please feel free to ask for more clarification and elaboration about why each object shouldn't be blocked.

1- `zoomit.ir/advertisement/`, `zoomg.ir/advertise/`:
`cdn01.zoomit.ir/assets/img/advertise-2.jpg` and `cdn.zoomg.ir/banners/demo/advertise-zoomg.jpg` get blocked because of `/advertise-$~script,domain=~ads.microsoft.com|~advertise-solution.nl|~bingads.microsoft.com`
Solution: 
```
@@||cdn01.zoomit.ir/assets/img/advertise-2.jpg$image,domain=zoomit.ir
@@||cdn.zoomg.ir/banners/demo/advertise-zoomg.jpg$image,domain=zoomg.ir
```

2- `webii.ir`:
`webii.ir/upload/ads/*/*.jpg` gets blocked because of `/upload/ads/*$domain=~ads.ae`
Also some cosmetic items get blocked.
Solution:
```
webii.ir#@#.ads-sidebar
webii.ir#@#.ads-box
`@@||webii.ir/upload/ads/$image` 
```

3- `tamin.ir` (is a government website and it's geo-specific so you might not be able to visit it):
Broken: https://user-images.githubusercontent.com/17685483/170836714-8f7603f2-115c-449d-8ea7-03640e0df4ee.png
Fixed: 
https://user-images.githubusercontent.com/17685483/170836752-92e0138f-c28f-4115-8d4b-5ed918609d71.png
Solution:
```
tamin.ir#@#.ads2
@@||tamin.ir/content/ads/
```
4- `1000site.ir/home/ads/%D9%81%D8%B1%D9%88%D8%B4-%D8%A8%DA%A9-%D9%84%DB%8C%D9%86%DA%A9`:
Broken: https://user-images.githubusercontent.com/17685483/170836823-9fbd131b-8969-4270-b53f-d17388827879.png
Solution (Pictures with /ads/ or /adpage/ are only present in the `1000site.ir/home/ads/` address):
```
@@||1000site.ir/asset/images/images/adpage/$image
@@1000site.ir/home/ads/asset/favicon.ico
```

5- `sakhtafzar.com/تبلیغات/`:
The page is completely broken.
Solution:
```
sakhtafzar.com#@#.ads-title
sakhtafzar.com#@#.ads-content
```
`sakhtafzar.com`:
The Telegram banner (`sakhtafzar.com/wp-content/uploads/2018/11/telegram-banner-2.png` on the left is blocked.
Solution:
```
sakhtafzar.com#@#.ads_box
sakhtafzar.com#@#.tz_ad300_widget
```

6- `sourceiran.com/podcasts/`:
`sourceiran.com/wp-content/uploads/300-250.jpg` is blocked because of `/300-250.`, but it's not an ads.
Solution: `@@||sourceiran.com/wp-content/uploads/*.jpg`

7- `forum.p30world.com`
On the bottom of the page, `عضویت در خبرنامه P30World` and `دانلود نرم افزار های جدید :` aren't ads but they're blocked.
Solution: `forum.p30world.com#@##ad_global_above_footer`

8- `persianv.com/adv/`:
`persianv.com/wp-content/uploads/2021/11/adv-1.jpg` is blocked but it's not an ads.
Solution: `@@||persianv.com/wp-content/uploads/*/adv-*.jpg`

9- `parsiblog.com/adv/default.htm`:
It's partially broken.
Solution: `@@||parsiblog.com/Adv/imgs/`

10- `niksalehi.com/adv`:
`niksalehi.com/wp-content/uploads/2021/11/adv-1.jpg` and `niksalehi.com/wp-content/uploads/2021/11/adv-2.jpg` are blocked but they're not ads.
Solution: `@@||niksalehi.com/wp-content/uploads/*/adv`

11- `nicmusic.net`:
These are blocked but they're not ads: 
https://user-images.githubusercontent.com/17685483/170837306-c6c578f0-82e9-40a7-a951-3fac1ec1be4e.png
Solution: `nicmusic.net#@#.boxads`

12- `kojaro.com/advertisement/`:
`images.kojaro.com/assets/ad/advertise-2.jpg` is blocked but it's not an ads.
Solution: `@@||images.kojaro.com/assets/ad/advertise-*.jpg`

13- `gooyait.com/ads`:
It's completely broken.
Solution:
```
gooyait.com#@#.page-ads
gooyait.com#@#.banner-ads
```

14- `gamesib.ir`:
`##.ads_2` blocks the "بازی های آنلاین دو نفره (=Online multiplayer games)" section on top.
Solution: `gamesib.ir##.ads_2`

15- `farsroid.com/ads/`:
`##.place-ads`: https://user-images.githubusercontent.com/17685483/170837686-4a72173f-8f9d-4f2e-8e72-e55ffa512180.png
Solution: `farsroid.com#@#.place-ads`

16- `cooldl.net`:
`##.ads-box` and `##.ads-content` and block top portion of the website which is not ads.
https://user-images.githubusercontent.com/17685483/170837808-3f462f38-9318-46f7-9dec-250854793c3c.png
Solution:
```
cooldl.net#@#.ads-box
cooldl.net#@#.ads-content
```

17- `https://www.beytoote.com/ads/advertising.php` (Visit this one only using https and www):
Several `beytoote.com/ads/images_pc/` and `beytoote.com/ads/images_mob/` are blocked but they're not ads.
Solution: `@@||beytoote.com/ads/images_pc/$image` and `beytoote.com/ads/images_mob/$image`

18- `blogfa.com/ads/`:
Two `blogfa.com/static/ads/*.gif` are blocked.
Solution: `@@||blogfa.com/static/ads/`

19- `asandl.com/ads/`:
Several `asandl.com/ads/img/` are blocked but they're not ads.
Solution: `@@||asandl.com/ads/img/$image`

**Comment by Khrin** [comment]
Looks like it's all stuff that fits more appropriately in your list.

**Comment by MasterKia** [comment]
I don't think so.
Shouldn't breakages get addressed _**upstream**_?
For example number 3 is an important website here and not many people would use my list to unbreak it but many people would use the EasyList.

**Comment by MasterKia** [comment]
Also the number of people who use EasyList and visit those site, is an _order of magnitude_ higher than people who would possibly use my list.

**Comment by MasterKia** [comment]
https://github.com/easylist/easylist#list-issues
**List issues**
Filter issues can be raised via [Github](https://github.com/easylist/easylist/issues).
Attempt fix website false-positives where applicable such as:
* **_Website breakages_**
* Allow direct link fixes
* Web page rendering issues

**Comment by MasterKia** [comment]
@ryanbr

**Comment by Khrin** [comment]
Please read "Coverage" at [https://easylist.to/pages/policy.html](https://easylist.to/pages/policy.html)
