### ISSUE TITLE
romanialibera.ro

### ISSUE THREAD

**Issue by Branzeturi** [easylist/easylist#12145]
`https://romanialibera.ro/la-zi/politica/ccr-noi-precizari-pentru-neconstitutionalitatea-textului-din-codul-penal-privind-intreruperea-cursului-termenului-prescriptiei/` -- `https://pahthf.tech/c/www.romanialibera.ro.js` third-party connection

Encountered `https://cdn.pabidding.io/c/romanialibera.ro.min.js` third-party connection accompanying `https://romanialibera.ro/`

**Comment by Branzeturi** [comment]
@Yuki2718 regex for uBO / AG ?

https://github.com/easylist/easylist/issues/12138

**Comment by Yuki2718** [comment]
`.tech/c/*.ro.js^$script,third-party` or something will be enough. Adding domains is fine too unless it's really endless.

**Comment by Branzeturi** [comment]
> ~`.tech/c/*.ro.js|$script,third-party` or something will be enough.~ Adding domains is fine too unless it's really endless. Okay not always ro.js.

I encountered two fairly similar `.tech` domains; Is `.tech` really that needed as a 3p?

**Comment by Yuki2718** [comment]
`/^https?:\/\/[a-z]{4,10}\.tech\/c\/(?:www.)?[-0-9a-zA-Z]{3,}(?:\.[a-z]{2,4})?\.js(?:\?schain=)?/$script,3p,match-case` but maybe too risky to add to public list.
