### ISSUE TITLE
pioneerproaudio.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12144]
### List the website(s) you're having issues:

`https://www.pioneerproaudio.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly 102
- Adblock Extension/version: uBO 1.42.5rc0

### Other details:

![image](https://user-images.githubusercontent.com/95879668/170832900-8cfa834f-cceb-40ca-b056-eadc6db1349e.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3272e46851b9f29c68a3b76e0463185d948e444c
