### ISSUE TITLE
promotor.ro

### ISSUE THREAD

**Issue by Branzeturi** [easylist/easylist#12141]
`https://www.promotor.ro/stiri-auto/top-10-cele-mai-bune-masini-diesel-galerie-foto-15283516` - `aff.carvertical.com` and `https://views.2222.ro/track.js?v=2022.03.07.1` as third-party

**Comment by ryanbr** [comment]
aff.carvertical.com should be in ro regional.

**Comment by Branzeturi** [comment]
What about EasyPrivacy, @ryanbr ?
