### ISSUE TITLE
www.theguardian.com/international cookie banner

### ISSUE THREAD

**Issue by valynor** [easylist/easylist#12154]
https://www.theguardian.com/international
has a cookie banner again.  (I'm blocking all cookies via uMatrix).

![Screenshot 2022-05-29 at 15 57 10](https://user-images.githubusercontent.com/23384233/170872869-af6ee4b8-2118-4d96-ac2f-b345a8763a34.png)

**Comment by ryanbr** [comment]
breaks to much, unable to 'fix' it.
