### ISSUE TITLE
tamrieltradecentre.com

### ISSUE THREAD

**Issue by WizardShotTheFood** [easylist/easylist#12155]
### List the website(s) you're having issues:
`tamrieltradecentre.com`

### What happens?

Any attempt to search for an ingame item gives a "disable your adblocker" error that cannot be bypassed.

### List Subscriptions you're using:

AdGuard Annoyances AdGuard Base, AdGuard Mobile Ads, AdGuard Tracking Protection, EasyList, EasyPrivacy, Peter Lowe’s Ad and tracking server list

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 100.0.2
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:

![image](https://user-images.githubusercontent.com/4625609/170883225-9cad9be6-c359-4f48-a5b4-f7efd0d3b6d5.png)

**Comment by Branzeturi** [comment]
Hi! I don't think anti-adblock is deliberately addressed in this repository. 
Such issues can be reported in uBlock Origin's [`uAssets`](https://github.com/uBlockOrigin/uAssets)

Have a nice day!

**Comment by WizardShotTheFood** [comment]
According to EasyList policy, "Anti-Adblock should only be challenged if the system limits website functionality or causes significant disruption to browsing". Literally stopping the site from working seems like it falls under "limits website functionality".

**Comment by Branzeturi** [comment]
`https://adblockplus.org/en/terms`
https://github.com/easylist/easylist/issues/12090#issuecomment-1134023475

**Comment by WizardShotTheFood** [comment]
Then why do you mention anti-adblock stuff as something you handle in the README.MD?
