### ISSUE TITLE
`https://www.snopes.com/`

### ISSUE THREAD

**Issue by Branzeturi** [easylist/easylist#12159]
On `https://www.snopes.com/` : an annoying dismissible overlay was encountered with `uBO [enabled-by-default filters on a PC with english as its primary language + Fanboy's Annoyance]`

**Comment by ryanbr** [comment]
What overlay? I havent' seen anything yet

**Comment by Branzeturi** [comment]
@ryanbr Did you scroll on that web page?

**Comment by ryanbr** [comment]
If its related to tinypass paywall, can't touch

**Comment by Branzeturi** [comment]
The annoyance I just encountered was dismissible. Anyhow, I get why you may not want to add any filter for it I guess.

**Comment by Branzeturi** [comment]
I think it was dismissible, but anyhow I can see why someone wouldn't want to hide/block that
