### ISSUE TITLE
siccness.net/wp

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12164]
### List the website(s) you're having issues:

`https://www.siccness.net/wp/`

### What happens?

Ad Placement Leftover (At the bottom of the page.)

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly 102
- Adblock Extension/version: uBO 1.42.5rc0

### Other details:

Website w/Ad Blocked:

![siccness-normal](https://user-images.githubusercontent.com/95879668/170897649-79459934-9e93-41c8-acca-3607bd74fd42.png)

Website w/Ad:

![siccness-ubo-ad-leftover](https://user-images.githubusercontent.com/95879668/170897641-99b08227-4df5-448e-9e47-1923ca725bdb.png)

**Comment by ryanbr** [comment]
Too minor.
