### ISSUE TITLE
elevenforum.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12161]
### List the website(s) you're having issues:

`https://www.elevenforum.com/t/how-to-set-the-lock-screen-wallpaper-to-fit.6768/` - Just as an example. (All forum threads have these.)

### What happens?

Ad Placement Leftovers

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly 102
- Adblock Extension/version: uBO 1.42.5rc0

### Other details:

Website w/Ads Blocked:

![eleven-forums-ubo-ad-leftovers](https://user-images.githubusercontent.com/95879668/170897009-aef55631-b569-4214-9d38-160b60a2f05b.png)

Website w/Ads:

![eleven-forums-normal](https://user-images.githubusercontent.com/95879668/170897004-3b07ce51-f471-43ac-ab6e-cad541788593.png)

**Comment by Branzeturi** [comment]
Is `elevenforum.com##.gads` a good filter?
