### ISSUE TITLE
tenforums.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12162]
### List the website(s) you're having issues:

`https://www.tenforums.com/general-support/194822-instead-pasting-clipboard-i-get-cortana.html` - Just as an example. (All forum threads have these.)

### What happens?

Ad Placement Leftovers

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly 102
- Adblock Extension/version: uBO 1.42.5rc0

### Other details:

Website w/Ads Blocked:

![ten-forums-ubo-ad-leftovers](https://user-images.githubusercontent.com/95879668/170897258-8ed86ff1-ed3c-4b82-bfa9-83d07a7b4053.png)

Website w/Ads:

![ten-forums-normal](https://user-images.githubusercontent.com/95879668/170897395-34224e8f-fc5b-48ca-a4da-1e0c7b8ab2cf.png)

**Comment by Branzeturi** [comment]
```
tenforums.com##.body_wrapper > div[style="min-height:250px;"]
sevenforums.com,tenforums.com##[id^="yui-gen"]
sevenforums.com##.chill
```
