### ISSUE TITLE
sevenforums.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12163]
### List the website(s) you're having issues:

`https://www.sevenforums.com/general-discussion/427317-windows-7-wont-shutdown-windows-logon-wont-close.html` - Just as an example. (All forum threads have these.)

### What happens?

Ad Placement Leftovers

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly 102
- Adblock Extension/version: uBO 1.42.5rc0

### Other details:

Website w/Ads Blocked:

![seven-forums-ubo-ad-leftovers](https://user-images.githubusercontent.com/95879668/170897501-b293accd-ca61-4869-8370-59061f137a26.png)

Website w/Ads:

![seven-forums-normal](https://user-images.githubusercontent.com/95879668/170897521-ff3c2690-ddd6-4049-8118-a4e82b573800.png)

**Comment by Branzeturi** [comment]
Are:
```
sevenforums.com##[id^="yui-gen"]
sevenforums.com##.chill
```
good filters?

**Comment by Branzeturi** [comment]
You're welcome!

**Comment by Daxy7** [comment]
@Yuki2718 ad placeholders
```
https://www.sevenforums.com/bsod-help-support/50621-why-does-my-hard-drive-activity-light-constantly-blink-6.html
```
```
sevenforums.com##.infeed1
```
