### ISSUE TITLE
www.geenstijl.nl

### ISSUE THREAD

**Issue by M1Aston** [easylist/easylist#12172]
### List the website(s) you're having issues:
https://www.geenstijl.nl

### What happens?
Cookie mesage doesn't load completely, which makes it impossible to click any of the options.

### List Subscriptions you're using:
I think the Cookie list is causing this problem.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox
- Adblock Extension/version: ublock

### Other details:
The bottom part of the window is missing.

![2012-06-01_000006](https://user-images.githubusercontent.com/43113612/171048351-e6e2e5c8-0af3-4402-b87c-5bed0d434174.jpg)

**Comment by ryanbr** [comment]
Should be resolved? Force an update of the lists @M1Aston

**Comment by M1Aston** [comment]
I don't think it's working. After disabling the Cookie list it does work normally.

**Comment by ryanbr** [comment]
Should be fixed now, just update.
