### ISSUE TITLE
howtogeek.com (hides the article author information)

### ISSUE THREAD

**Issue by 07416** [easylist/easylist#12195]
### List the website(s) you're having issues:

`https://www.howtogeek.com/444233/how-to-use-the-less-command-on-linux/` [or any other article]

### What happens?

The `.entry-meta` element gets hidden by the 'Fanboy’s Annoyance' list.

### List Subscriptions you're using:

Only Fanboy's Annoyance.

### Your settings

- OS/version: Fedora 36
- Browser/version: Firefox 100.x (a fresh profile)
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:

![image](https://user-images.githubusercontent.com/14923168/171603467-d4cc7974-ff50-4689-9792-68fc5c23634f.png)

**Comment by ryanbr** [comment]
We're not hiding `.entry-meta` @07416

**Comment by THEtomaso** [comment]
### Problem filter:
* **Fanboy's Annoyance List**

### Problem rule:
`howtogeek.com##[data-nosnippet="data-nosnippet"]`

### Possible fix:
```
- howtogeek.com##[data-nosnippet="data-nosnippet"]
+ howtogeek.com##[data-nosnippet="data-nosnippet"]:not(.entry-meta)
```

### Temp fix:
`howtogeek.com#@#[data-nosnippet="data-nosnippet"]`

**Comment by 07416** [comment]
> ### Problem rule:
> 
> `howtogeek.com##[data-nosnippet="data-nosnippet"]`

@THEtomaso Did you find the cause trivially in the uBlock Origin logger? I've had less success with troubleshooting cosmetic breakage.

**Comment by THEtomaso** [comment]
> Did you find the cause trivially in the uBlock Origin logger?

Yes

**Comment by 07416** [comment]
> You don't see it in uBO's logger?

I do when searching for `[data-nosnippet="data-nosnippet"]`, I mean I'm not sure how you discovered the conflict in the first place.

**Comment by THEtomaso** [comment]
> I'm not sure how you discovered the conflict in the first place.

By simply disabling the suspects, one by one.
I think the offending rule was the second one that I tried.
