### ISSUE TITLE
torrentdownloads.me

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#122]
`https://www.torrentdownloads.me/search/?search=linux`

Sponsored search results. Also lots of popups throughout the site when clicking around.
And "Free and Direct Download" when selecting a torrent (friendlyquacks) plus 2 fake buttons. Only the middle one is real.

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/2e7f1cab8380a4b4e0983eea5473c3254e0f5da5

**Comment by terrorist96** [comment]
@monzta I still see the Sponsored search results at the top on Chrome.
`https://www.torrentdownloads.me/search/?search=linux`

There's also a `Watch Online @ Movie4u` ad in the torrent info section too. How can you stream a book? lol
`https://www.torrentdownloads.me/torrent/1662440002/Hacking+University+Senior+Edition+Linux+Optimal+beginner%27s+guide+to+precisely+learn+and+conquer+the+Linux+operating+system+%282016%29+%5BWWRG%5D`
