### ISSUE TITLE
[NSFW] Exist ads on website: [https://dood.pm/d/ez4q34fief1w]

### ISSUE THREAD

**Issue by hoang-rio** [easylist/easylist#12226]
### List the website(s) you're having issues:
https://dood.pm/d/ez4q34fief1w

### What happens?

Popunder ads when click play
### Your settings

- OS/version: iOS
- Browser/version: CocCoc Browser lastest version
- Adblock Extension/version: CocCoc Build In Adblocker

### Other details:

Reference abpvn/abpvn#408

**Comment by hangtt1** [comment]
@hoang-rio Could please help tag me when this issue has been fixed from easylist? I will need to check from my side and inform our user.

Thanks!

**Comment by hoang-rio** [comment]
> @hoang-rio Could please help tag me when this issue has been fixed from easylist? I will need to check from my side and inform our user.
> 
> Thanks!

When you comment on this issue you will be receive notification when has update in this issue.

**Comment by ryanbr** [comment]
Force an update, but the site will keep changing/adding randomised servers.

**Comment by hoang-rio** [comment]
@ryanbr Can you add a reference to commit fixed this issue?

**Comment by hoang-rio** [comment]
@hangtt1 Did CocCoc brower use [ABP Filters](https://github.com/abp-filters/abp-filters-anti-cv)? I think this type of ads can not blocked by normal way by static filter rule. If your browser is not support Snippet rule I can said no way to block this type of ads in  your browser. Additional I remember I have been request about remote debug feature in Coc Coc browser for better support from me and another filter list author. Have plan for this feature from your dev team?

**Comment by hangtt1** [comment]
@hoang-rio @GhenadiePusca 
My reply below: 
#1: We are using minified file, kindly help follow: https://easylist-downloads.adblockplus.org/easylist+abpvn-minified.json
#2: Remote debug feature in Coc Coc browser - We may need to discuss further with @GhenadiePusca on how to do it in the best way in our next training with your side

**Comment by hoang-rio** [comment]
@GhenadiePusca @hangtt1 I'm not sure but I think [here](https://github.com/easylist/easylist/commit/84a763d2a4ada62c6fca0f34326af4800910f1f1) is commit fixed this issue

**Comment by GhenadiePusca** [comment]
> @GhenadiePusca @hangtt1 I'm not sure but I think [here](https://github.com/easylist/easylist/commit/84a763d2a4ada62c6fca0f34326af4800910f1f1) is commit fixed this issue

Ok, I am not sure if those filters would actually fix the problem, but I will check.
