### ISSUE TITLE
velikolepnyivek.com

### ISSUE THREAD

**Issue by dcxstq2** [easylist/easylist#12222]
### List the website(s) you're having issues:

`https://www.velikolepnyivek.com/online/season_3_three.php`

### What happens?

Tracker
It will show itself after you click the play button.

<details>
 <summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/104112959/172081772-26dd848f-92e6-42fb-b3d6-c381b216dd45.png)

</details>

### List Subscriptions you're using: 
```
AdGuard Base
AdGuard Annoyances
AdGuard Social
AdGuard Tracking Protection
AdGuard Turkish
```

### Your settings

- OS/version: Win 10 21H2
- Browser/version: Chrome 102
- Adblock Extension/version: AdGuard 4.0.171

### Other details:

Also used on the following websites:

```
https://www.tvsoap.ru/online/dikii_angel_online/muneca_brava.php
https://www.bonestv.ru/online/bones_season_2_online.php
https://www.walkingdeadru.com/seasons/1_season.php
```

**Comment by ryanbr** [comment]
`||allvideometrika.com^`  does that help? or cause any issues? @dcxstq2

**Comment by dcxstq2** [comment]
@dcxstq2 
Yes it helps. I did not encounter any problems using the rule. It seems safe.
