### ISSUE TITLE
(NSFW) luscious.net

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#12221]
### List the website(s) you're having issues:

`https://www.luscious.net/pictures/album/rash_guard_323475/id/20757116/@original_drawn_by_tetsuo_amenohutikoma_sample_cb61?index=15&id=20757116`

### What happens?

One animated ad in the upper right and one placeholder on image pages.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/22780683/172061515-3367fe19-ae98-44d0-80df-74c2e1ae23a0.png)

</details>

### Your settings

- OS/version: Windows 11 x64
- Browser/version: Chrome 102.0.5005.63 x64
- Adblock Extension/version: uBO 1.42.4 + IDCAC 3.4.0

### Other details:

I propose:
```
/iframe$subdocument,domain=luscious.net
luscious.net##.o-padding-top-bottom
```

Screenshot: `https://images2.imgbox.com/6a/a4/UAMdPx1J_o.png`

**Comment by THEtomaso** [comment]
> https://github.com/easylist/easylist/commit/fef64c9a3afd097110106ec95b5cf5997a58792c
> `luscious.net##.adDisplay-module__ad_banner--Drna4`

To include the last dynamic part of such rules is usually not a good idea, since it's likely to change at some point.
This would be better:
`luscious.net##[class^="adDisplay-module__ad_banner"]`

**Comment by herpyderp308** [comment]
Hello
I have noticed that as of the 7th that none of the images load
Believe that it is the luscious.net##.o-padding-top-bottom that is causing it.
