### ISSUE TITLE
leroymerlin.ro - blocking the cookie notice breaks the website search functionality

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#12233]
### List the website(s) you're having issues:

- `https://www.leroymerlin.ro/produse/search/lemn`

### What happens?

The website does not hide the loading animation because the cookie dialog is blocked.

### List Subscriptions you're using:
- `EasyList Cookie List`

### Your settings

- OS/version: macOS Monterey 12.1
- Browser/version: Chrome 102
- Adblock Extension/version: Adblock Plus

### Other details:
With the list
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/172330716-4306264f-25db-4975-b12f-fe3f8e16c41e.png">

Without the list
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/172330179-be12dfd9-c250-4ae9-b824-3275e769d22a.png">

**Comment by ryanbr** [comment]
Does `leroymerlin.ro##.loader` work for you @alexm92
