### ISSUE TITLE
tetrisfriends.com [Incorect blocking]

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#1223]
### List the website(s) you're having issues:

`http://www.tetrisfriends.com/games/index.php`

### What happens?

Game icons are hidden.
Caused by:
`almasdarnews.com,antonymsfor.com,breakingisraelnews.com,coed.com,collectivelyconscious.net,colourlovers.com,connectedly.com,convert-me.com,convertcase.net,daclips.in,dailygalaxy.com,datpiff.com,dietlast.com,diffen.com,drudgereport.com,dwatchseries.to,easybib.com,eurweb.com,freewarefiles.com,fullmatchesandshows.com,gelbooru.com,genfb.com,getinmybelly.com,gorillavid.in,grammarist.com,imagepearl.com,indiewire.com,israelnationalnews.com,jerusalemonline.com,jewsnews.co.il,jpost.com,kizi.com,kshowonline.com,magnetdl.com,movpod.in,msn.com,nba-stream.com,newsarama.com,omgcheckitout.com,opensubtitles.org,phonesreview.co.uk,playbill.com,readmng.com,roadracerunner.com,robinwidget.com,rule34.xxx,sh.st,sportspickle.com,teslacentral.com,tetrisfriends.com,the4thofficial.net,thebarchive.com,thefreethoughtproject.com,toptenz.net,trifind.com,unblckd.org,uproxx.com,usherald.com,veteranstoday.com,videotoolbox.com,vrheads.com,watchseries.sk,wnd.com,xda-developers.com##[style*="background-image:"]`

<details>

![image]()
![image](https://user-images.githubusercontent.com/8361299/40617142-0dd55544-6296-11e8-86c1-ea11804aeefd.png)

</details>

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Win7
- Browser/version: Chrome
- Adblock Extension/version: ABP

**Comment by ryanbr** [comment]
Resolved.
