### ISSUE TITLE
blocket.se

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12232]
### List the website(s) you're having issues:

`https://www.blocket.se/`

### What happens?

Personal Data Policy Notice - Screenshot 1
Privacy Policy Notice - Screenshot 2

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly 103
- Adblock Extension/version: uBO 1.42.5rc1

### Other details:

Screenshot 1:

![blocket](https://user-images.githubusercontent.com/95879668/172311048-3422a77d-6a49-41f6-afbc-b9f05bd6e725.png)

Screenshot 2:

![blocket2](https://user-images.githubusercontent.com/95879668/172316186-28bc6d5c-8d13-45ae-bd96-c89b5b6c9c02.png)

**Comment by ryanbr** [comment]
Okay, does adding this help `blocket.se##*:style(filter: none !important;opacity:1 !important;pointer-events:auto !important)` ? @q1800

**Comment by ryanbr** [comment]
Okay, I'll leave it be. Not worth breaking.
