### ISSUE TITLE
Autoscroll is blocked on erome.com (adult)

### ISSUE THREAD

**Issue by eromecom** [easylist/easylist#12244]
Hi,

We have implemented autoscroll on mobile only.

With a mobile browser that has adblock as brave, our users complain about being able to scroll and reach page 2 and following.

Url : (NSFW)
https://www.erome.com/explore

Can you check, thank you

**Comment by ryanbr** [comment]
`erome.com##+js(abort-current-script, $, ready)` from uBO. Possibly included to avoid ad insertion on page scroll "Meet & Fuck" insert for example. Should be taken up with https://github.com/uBlockOrigin/uAssets to see if its still a valid filter.

Just reference this ticket in https://github.com/uBlockOrigin/uAssets

@eromecom
