### ISSUE TITLE
dynatrace-managed URLs and generic rules added to tracking server blocklist

### ISSUE THREAD

**Issue by thermiteTermite** [easylist/easylist#12240]
### List the website(s) you're having issues:

dynatrace-managed is added to easylist trackers along with general domains

```
||dynatrace-managed.com^
||dynatrace.com^$third-party,domain=~dynatracelabs.com
||dynatracesaas.com^$third-party
```
https://github.com/easylist/easylist/blob/f502f5e5cf20e563a622b8e9f3a49f3f678c4330/easyprivacy/easyprivacy_trackingservers.txt#L54

### What happens?

dynatrace-managed is typically not a set of tracking servers.  It is a URL for accessing a products UI.  
These URLs are typically not public and much of the data is unrelated to anything from the end user and it is used to monitor their infrastructure.

Additionally the other filters tend to block websites affiliated with dynatrace and subdomains for other companies. (i.e. zoom). 
```
||dynatrace.com^$third-party,domain=~dynatracelabs.com
||dynatracesaas.com^$third-party
```

### List Subscriptions you're using:

https://github.com/easylist/easylist/blob/100fced879f76ab0fea89299d10a3e6aaf4becb1/easyprivacy/easyprivacy_trackingservers.txt#L47

### Your settings

- OS/version: Windows 11
- Browser/version:  Chrome:latest
- Adblock Extension/version:  Adblock Version 4.46.2 w/ EasyList protection

### Other details:

What you could block is the URL /ruxitagent and /rb_ and /ruxitagentjs

This will stop dynatrace browser error detection features to prevent modification to the page or data sent which should meet the requirements in this case without the need for the other rules. 

I see ruxitagentjs is already added to the general list 
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt

Please let me know if I can provide more details.  

https://www.dynatrace.com/support/help/how-to-use-dynatrace/real-user-monitoring/setup-and-configuration/web-applications/initial-configuration/firewall-constraints-for-rum#requests

![image](https://user-images.githubusercontent.com/107050109/172393649-131202ad-1f63-40a9-b0b9-87f674206563.png)
![image](https://user-images.githubusercontent.com/107050109/172393730-89d0a874-7d17-4448-a502-20af817fb7f9.png)

**Comment by ryanbr** [comment]
There is little trust in the privacy community and Dynatrace.

**Comment by Yuki2718** [comment]
@thermiteTermite You used vague words:
`typically` => `dynatrace-managed.com` is public at `[NSFW] https://www.dxlive.com/preview/SALApq`. In the request I see the same parameter `type, svrid, rf, sn, app, dbg, flavor, vi, modifiedSince, bp, contentType, crc, v, end` as in your linked document of real-user-monitoring.
`tend to` => provide a full URL to test and precise description of what is *broken*. I haven't experienced any trouble with Zoom app or any of zoom pages.

**Comment by martinus** [comment]
> I haven't experienced any trouble with Zoom app or any of zoom page

I had troubles with https://dynatrace.zoom.us/ until I deactvated UBlock.

**Comment by thermiteTermite** [comment]
@Yuki2718 

If a customer purchases dynatrace they could route traffic back to their environment with these URLs publicly.  I say typically because depending on how somehow routes their traffic it could go to a dynatrace-managed.com URL like in the site you linked or it could go to back to the domain itself or some other endpoint the customer has configured. 

I understand the intent behind what the blocklists are trying to do.  
It is easier to block the javascript that makes the requests than try and manage every single URL in the way that was done here.  

You could block URLs with 

/dynatrace*.js
/ruxitagent*.js

and block specifically URLs with dynatrace in the hostname and URL /bf like this 
https://xxxyyy.dynatrace-managed.com:9999/bf
(Although this is a moot point if the above js is not loaded into the page).  

But what these filters do now is break anything with dynatrace in the URL including things not related to browser monitoring which I don't believe was the intent of the filters. 

I hope this helps clarify.

**Comment by Yuki2718** [comment]
A problem is filters like `/dynatrace*.js` is inefficient. Wildcard, particularly in this case for uBO, should be avoided. IDK if `/dynatrace.js` covers all.

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/commit/fef58cc85393475b8cc5c3427701da3c37ffad89

**Comment by thermiteTermite** [comment]
All you need to block is the following scripts 

1) URL where the resource is javascript and the path includes /ruxitagent*
2) URL where the resource is javascript and the path ends with contains /dynatrace.js

The above 
don't necessarily have to come from dynatrace hostnames

To block the requests back from the browser  

1) URLs where hostname contains dynatrace and the path starts with /rb
2) URLs where the hostname contains dynatrace and the path starts with /bf

You don't need all of these other filters they will only cause you more tickets. 
https://github.com/easylist/easylist/commit/fef58cc85393475b8cc5c3427701da3c37ffad89#diff-b17c8b1c6dcc6a4f4dd2fef00625e42aa5e25ff1850baed7027a2ae59200bdc9

**Comment by thermiteTermite** [comment]
You already did part of this here. 
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt
