### ISSUE TITLE
Recent change in `/dynatrace.` filter breaks API requests

### ISSUE THREAD

**Issue by berkitamas** [easylist/easylist#12256]
### List the website(s) you're having issues:

Unfortunately the URLs are not reachable through internet.
Example: `https://openshift-master.company-intranet.com/apis/dynatrace.com/v1alpha1`

### What happens?

The API request to the mentioned page is blocked by the AdBlocker which causes a redirect loop and eventually a crash in [OpenShift Web Console](https://docs.openshift.com/container-platform/3.11/architecture/infrastructure_components/web_console.html)

### List Subscriptions you're using:

- EasyPrivacy

### Your settings

- OS/version: macOS Monterey 12.4
- Browser/version: Google Chrome Version 102.0.5005.61
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:

The issue is with this recent addition: https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L1688
https://github.com/easylist/easylist/commit/29a2fde09c09eaef5e2631e1660096708d5e13c3
This line also affects valid API calls for https://github.com/Dynatrace/dynatrace-oneagent-operator

**Comment by ryanbr** [comment]
Fine with this. Disable Adblock. Again, `There is little trust in the privacy community and Dynatrace.`

**Comment by joaopgrassi** [comment]
Hi @ryanbr 

Just another case I found: The Dynatrace logo is blocked on the CNCF landscape page https://landscape.cncf.io/?zoom=120

![image](https://user-images.githubusercontent.com/5938087/183864235-92e81a97-3483-4c7f-aaf6-a5d014ca4e77.png)

![image](https://user-images.githubusercontent.com/5938087/183864328-ce89de38-2fff-41e6-af6b-3f5ff9ee4b8a.png)

Other similar monitoring vendors are listed fine in that list.

**Comment by mikopp** [comment]
This is not really and add, no java script and nothing malicious and yet adblock is removing it. I am using adblock myself and I don't think this is ok and I would not expect this. By that logic you would need to remove all Dynatrace competitors as well from a page that is explicitly about listing those competitors. Asking the users to disable adblock is also not ok as they are not even aware of this being removed.
