### ISSUE TITLE
Channel 4 smart-TV and/or phone apps

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#12268]
### List the website(s) you're having issues:

One or more of the various https://en.wikipedia.org/wiki/All_4 apps.

### What happens?

Directly inspired by https://github.com/AdguardTeam/HostlistsRegistry/issues/53, which claims to remove ads from Channel 4 UK and ["All 4"](https://en.wikipedia.org/wiki/All_4) apps, I propose adding [that thread's suggested gist's domains](https://gist.github.com/jcass8695/d766fd65c0240b5c424ed73b17664db6) near-verbatim (except for adding `||` and `^` to them):
```
||2356e.v.fwmrm.net^
||ads-pres.channel4.com^
||cdn.http.anno.channel4.com^
||cdn.ss.anno.channel4.com^
||p.videologygroup.com^
||securecdn.videologygroup.com^
||toots-a.akamaihd.net^
||trk-euwest.tidaltv.com^
||2a7e9.v.fwmrm.net^
```

This would (most likely) ensure the entries are implemented downstream into AdGuard DNS Filter, presuming that `$third-party` is *not* added to the entries.

Other than the above, I have virtually zero context about the involved device setups.

### List Subscriptions you're using:

Unknown (It can be presumed that https://filters.adtidy.org/windows/filters/15.txt is being used, but I lack confirmation on it).

### Your settings

- OS/version: Unknown
- Browser/version: One or more of the various https://en.wikipedia.org/wiki/All_4 apps.
- Adblock Extension/version: AdGuard Home 0.10x.x

### Other details:

My experiences with other streaming services in the past couple years, is that entries that work splendidly on phones and TVs, could work much less well on PCs. It's a coin toss as to whether that would be the case for *All 4*.

**Comment by ryanbr** [comment]
This is for pihole cases, where people using a converted Easylist? @DandelionSprout  Seems to be a lot of filters for one site.

We're also blocking `fwmrm.net` by default

**Comment by ryanbr** [comment]
Given pihole recommends not to use EL, the market for EL as a DNS blocker is limited. We would probably need to create a seperate list to cover dns blocking. We'll leave this be
