### ISSUE TITLE
Easylist breaks GayGo.tv

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#12279]
### List the website(s) you're having issues:
`https://gaygo.tv/view/1015705/`

### What happens?
Rule `/sp/delivery/*` in EasyList blocks request to `fuckandcdn.com`, breaking the video player.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Video plays fine with rule here.

**Comment by yokoffing** [comment]
Apologies. You're correct. I can play if I allow 3rd-party iframes.
