### ISSUE TITLE
Facebook Marketplace

### ISSUE THREAD

**Issue by verhovsky** [easylist/easylist#12272]
### List the website(s) you're having issues: 

`https://www.facebook.com/marketplace/`

`https://www.facebook.com/marketplace/category/vehicles/`
`https://www.facebook.com/marketplace/category/propertyrentals` etc.

### What happens?

There are two main screens, the general one that just shows you random products you might be interested in

<img width="1195" alt="Screen Shot 2022-06-09 at 22 18 34" src="https://user-images.githubusercontent.com/5687998/172995913-7717f5c4-b269-4300-95cc-ae20d0cd2eda.png">

and the one you see when you search for a specific thing (cars, clothes, rentals, etc.) 

<img width="1193" alt="Screen Shot 2022-06-09 at 22 18 09" src="https://user-images.githubusercontent.com/5687998/172995960-e211295b-0057-4f8f-bd81-38d9ebe3d4e9.png">

As you can see, they have different ways of showing you ads. 

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks 
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
AdGuard Tracking Protection
EasyPrivacy
Online Malicious URL Blocklist
AdGuard Annoyances
AdGuard Social Media
Anti-Facebook
EasyList Cookie
Fanboy’s Annoyance
Fanboy’s Social
uBlock filters – Annoyances
Peter Lowe’s Ad and tracking server list
https://gist.githubusercontent.com/quenhus/6bd2c47e5780f726f0c96c0a2ee762a4/raw/09059f05d6c113d58a84b335b2eeea27c1f1f241/uBlock_StackOverflow_copycat.txt

### Your settings

- OS/version: macOS 12.4
- Browser/version: Chrome 102.0.5005.61 (Official Build) (arm64)
- Adblock Extension/version: uBlock Origin 1.42.4

**Comment by ryanbr** [comment]
Won't touch, too many false positives.
