### ISSUE TITLE
tweakers.net - cookiebar blocking prevents users from enabling 3rd-party embeds

### ISSUE THREAD

**Issue by crisp-tweakers** [easylist/easylist#12285]
### List the website(s) you're having issues:
`https://tweakers.net/nieuws/197852/portal-achtige-puzzelgame-the-entropy-centre-komt-in-2022-uit.html`

### What happens?
When I click on 'Open cookievoorkeuren' nothing happens:
![image](https://user-images.githubusercontent.com/32640525/173234335-24a9c519-6875-4028-8fd3-0d14800459d3.png)

What **should** happen is that this should open the cookie-consent bar which will enable the user to give consent for embedding e.g. YouTube:
![image](https://user-images.githubusercontent.com/32640525/173234410-a3aea249-47bb-4ba0-946e-6e1f8e8b78ff.png)

### List Subscriptions you're using:
EasyList
Easylist Cookie List

### Your settings
- OS/version: Windows 7/10/11
- Browser/version: Firefox 101, Chrome 102
- Adblock Extension/version: AdblockPlus 3.14

### Other details:
The culprit is the recent addition of the following rule to the Easylist Cookie List in https://github.com/easylist/easylist/issues/12281:
`tweakers.net##.koekie_bar`

Now obviously I am a representative of the webite in question. I am mainly reporting this issue to raise awareness to the negative consequences that blocking cookie-consent bars have for users. We understand that these cookie-bars (and walls) can be an annoyance to users, but not only are they mandatory for websites because of EU-regulations (GDPR), they also give users the possibility to decide for themselves what they deem acceptable in terms of the trade-off between functionality (e.g. watching YouTube embeds) and privacy.

We are very proud to be able to say that our website is by default completely free of any third-party tracking, and our cookie-consent bar is - in our view - a prime example of an unbiased selection tool. We do hope that you understand that in this case you are taking away this choice from users without giving them any alternative option. This also often results in false bugreports adressed to us.

**Comment by ryanbr** [comment]
Can the website remove the dependancy on the cookie action? Still show it in cases where its not being blocked, but don't break the site ? @crisp-tweakers  Many sites won't break a site just because you didn't press "Accept".

**Comment by crisp-tweakers** [comment]
Our site also doesn't break when you do not press accept. The user is free to disallow non-functional cookies after which the cookie-bar will disappear, but can still be 'summoned' when the user wishes to re-evaluate that decision. We are at this moment planning to also add a trigger for that in the footer of our website instead of only through blocked embeds and the cookie-page (`https://tweakers.net/info/algemene-voorwaarden/cookies/`).

The integration of the choices for the 3rd-party embeds is a logical one; it is tighly coupled to the 'accept all' choice, and we want the user to be able to evaluate what that choice entails (moreover, this is legally mandatory).

We have noticed that other adblocking tools, such as AdGuard, do not simply hide the cookie-bar but go through lengths to automatically accept. Now we don't feel that that is the right course of action, but at least this will give the user a better experience and the user is still able to change the consent afterwards.

**Comment by ryanbr** [comment]
How would you resolve https://github.com/easylist/easylist/issues/12281  We are limited to uBO/ABP filters. Just let 3rdparty content would be easiest fix, while still showing the consent message.

**Comment by crisp-tweakers** [comment]
That is not an easy question to answer without having to look at the broader issue with cookie-consent bars and walls altogether. As for publishers there isn't much of a choice than to implement them, or forgo on things like advertisements (yes, this is somewhat devil-speak here I know, but most publishers *are* financially dependent on ads for their needed revenue) and things that actually benefit users such as being able to embed 3rd-party video's or widgets and other stuff the internet is made of and for.

In an ideal world there would not be any tracking, and lawmakers would not put the onus for this on the publisher, but we don't live in such world unfortunately. We have to give the user a choice (which is in itself a good thing), and with choices come consequences, so users should also be able to re-evaluate earlier choices.

I guess we could offer a secundary means of evaluating consent-choices, for instance on a dedicated page, but that comes with the difficulty of discoverability. And that is exactly why most websites use a popup for this* ;)

So I would rather answer the question with another question: what is is that makes these cookie-bars (and ours in particular) so annoying that it justifies hiding it to the majority of our visitors (we have a rather high adblocking share among our visitors) depriving them of the means to make an actual choice?

Yet I do understand it from a user perspective; there are many annoyances on almost every website, and cookie-bars just add to those. Yet as a developer I also see it as my task to point this out internally, and find other and better solutions for the purposes these 'annoyances' are created. This is always a struggle I can tell you, mostly because of conflicting interests, but I think that overall we are doing a decent job. But some things are hard to improve upon because of all the requirements that come with it, such as these cookie-bars.

If you do however have any suggestions, we are happy to hear them :)

* and now I think of it; what probably would be a better pattern is decreasing the popup-bar to a small floating icon/button just labelled "cookie consent" or something simular after a number of pageviews. The question is if such a pattern would still make you consider blocking this or not?

**Comment by ryanbr** [comment]
Easylist Cookie isn't a default list in uBO/ABP, people use it to remove the amount of consent spam. Keep in mind most people will be using Easylist + Easyprivacy with Easylist Cookie, so accepting or rejecting cookies from these blocked ad/tracking providers is pointless. 

Consent manager scripts have options to whether it'll deny or allow access by default, all I'm saying is still show the message as per ccpa/gdpr, but configure the consent script not to disable 3rd-party by default. Or just use a better consent script that won't do this, so many cookie messaging scripts out there.

**Comment by krystian3w** [comment]
@kiboke check this page to minimise breakage with ABP only (exclusions and exceptions may needed).

**Comment by kiboke** [comment]
@krystian3w Thanks for letting me know! I have fixed the issue in IDCAC recently. Please let me know if something still doesn't work.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/14762

**Comment by Yuki2718** [comment]
Fixed for uBO, unfixable for ABP
