### ISSUE TITLE
gayfor.us "annoyance"

### ISSUE THREAD

**Issue by gototheskinny** [easylist/easylist#12309]
[https://gayfor.us/video_tag/teninchtopx/]()
Annoying blank pop up appears when you click any vid.

Adguard Safari iOS with fanboy annoyance,easylist,Easyprivacy,Adguard Turkish,German filter lists are enabled. No ads in this pop up but still appears.

**Comment by ryanbr** [comment]
No possible in EL. If there is options to add uBO or Adguard specific filters. use that also.
