### ISSUE TITLE
wetransfer.com annoyance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#12321]
### List the website(s) you're having issues:
https://wetransfer.com/

### What happens?
Annoying prompt to upgrade

### List Subscriptions you're using:
All filters offered by uBlock Origin

### Your settings

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 101.0.1
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:
Screenshot:
![Screenshot 2022-06-17 at 10-22-25 WeTransfer - Send Large Files   Share Photos Online - Up to 2GB Free](https://user-images.githubusercontent.com/101707608/174248820-515c98a5-899d-42f4-924c-93988c1fbf9a.png)

**Comment by ryanbr** [comment]
Suggested element?

**Comment by DimitrisKalaboukas** [comment]
splashpage and right sidebar

**Comment by ryanbr** [comment]
I'm not seeing it. I'm asking, suggested element to block, otherwise I'll just close this.
