### ISSUE TITLE
forbes.com cookie

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#12328]
### List the website(s) you're having issues:
`https://www.forbes.com/sites/thomasbrewster/2015/02/19/superfish-need-to-know/`

### What happens?
Cookie notice

### List Subscriptions you're using:
EasyList Cookie

### Your settings

- OS/version: Windows
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin

### Other details:

`forbes.com##[class*="trustarc"]`

![image](https://user-images.githubusercontent.com/17685483/174341116-3e32bd40-9875-4304-9c43-7aa80361bac2.png)

**Comment by Khrin** [comment]
Consent must be given, in order of being able to play videos.
