### ISSUE TITLE
igrus.com

### ISSUE THREAD

**Issue by dcxstq2** [easylist/easylist#12320]
### List the website(s) you're having issues:

`https://www.igrus.com/online-olarak-sigorta-hesaplamalari-nasil-yapilir/ `

### What happens?

`flashnetic.com` is an ad server

<details>
 <summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/104112959/174148530-f86a9da5-b656-49ac-b5f0-f75d642a590f.png)

</details>

### List Subscriptions you're using: 
```
AdGuard Base
AdGuard Annoyances
AdGuard Social
AdGuard Tracking Protection
AdGuard Turkish
```

### Your settings

- OS/version: Win 10 21H2
- Browser/version: Chrome 102
- Adblock Extension/version: AdGuard 4.0.181

### Other details:

Other websites using the same analytics script:

```
http://skam.online/skam-france/5373-skam-francija-10-sezon-7-serija.html
http://fanseries.tv/news/57056-doma-drakona-prodlen-na-vtoroj-sezon-do-premery-pervogo-sezona.html

```

**Comment by Khrin** [comment]
Report it to Adguard Turkish.
