### ISSUE TITLE
[Fanboy's Annoyance/Newsletter/Thridparty] buy.tinypass.com rule breaks our checkout 

### ISSUE THREAD

**Issue by brechr** [easylist/easylist#12338]
Hi everyone, I was wondering if it would be possible to make the rule in fanboys annoyances - newsletter - thirdparty, here:

https://github.com/easylist/easylist/blob/3f560a91b48bdc4197975d5a7ff2d636df2e02e0/fanboy-addon/fanboy_newsletter_thirdparty.txt#L3

somehow a little more specific or remove it. We're a german publisher using tinypass/piano and this rule breaks our checkout.

Further Info: `||buy.tinypass.com/checkout/template/cacheableShow?aid*=fakeOfferId&` while fakeOfferId might sound a bit sketchy, it just indicates that a template is requested to be 'injected' as iframe without an associated offer. I'm sure that in 90%+ of the cases, publishers and other piano customers are using this to inject newsletter popups (we do it, too) but we're also using this as part of our checkout (first steps, user has the choice to login or create a new account). 

It appears that this breaks something deep inside tinypass' scripts (messaging between iframe and website) it's hard for us to catch the error and at least inform our customers that something went wrong and why.

Thanks a lot and have a nice day

**Comment by ryanbr** [comment]
Can you post the full blocked url? @brechr

**Comment by brechr** [comment]
@ryanbr thanks for the quick response, sure: for example, on www.ruhrnachrichten.de it looks like this: https://buy.tinypass.com/checkout/template/cacheableShow?aid=qXvae8iVH6&templateId=OTOYT9ESSW94&offerId=fakeOfferId&iframeId=offer_8802d5ce74ab02cef991-0&displayMode=modal&widget=template&url=https%3A%2F%2Fwww.ruhrnachrichten.de

sadly i have to admit i have no good idea how to discern between a popup/iframe/element injected which is some kind of real annoyance ( i.e. our banners https://buy.tinypass.com/checkout/template/cacheableShow?aid=qXvae8iVH6&templateId=OTLKPMAMNESJ&templateVariantId=OTVO9HRM9N3J6&offerId=fakeOfferId&experienceId=EX91XPFOZ3IZ&iframeId=offer_c5838431520f89278bed-0&displayMode=inline&widget=template&url=https%3A%2F%2Fwww.ruhrnachrichten.de ) and the templates that are required for some kind of core process. 

let me know if i can help in any way

**Comment by ryanbr** [comment]
Okay how about this `||buy-au.piano.io/checkout/template/cacheableShow?*&experienceId=*&widget=template`
