### ISSUE TITLE
www.motorsport-magazin.com

### ISSUE THREAD

**Issue by jbreitbart** [easylist/easylist#12337]
### List the website(s) you're having issues:
https://www.motorsport-magazin.com

### What happens?
Cookie acceptance banner is shown

### List Subscriptions you're using:

EasyList Cookie

### Your settings

- OS/version: MacOS 12.3
- Browser/version: Firefox 101
- Adblock Extension/version: uBlock origin 1.43.0

**Comment by ryanbr** [comment]
Not possible, would break the site unfortantly.

**Comment by jbreitbart** [comment]
Too bad, thanks for checking!
