### ISSUE TITLE
https://pure-sierra-80865.herokuapp.com/

### ISSUE THREAD

**Issue by ransombriggs** [easylist/easylist#1234]
### List the website(s) you're having issues:

`https://pure-sierra-80865.herokuapp.com/`

### What happens?

There should be a navigation bar displayed, but it is blocked.  We have a [project](https://github.com/heroku/boomerang) that provides javascript our partners include in their sites to provide consistent navigation.  The website I provided is just an example I put together because our partner sites are all behind authentication.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Ubuntu
- Browser/version: Firefox
- Adblock Extension/version: uBlock

### Other details:

If the file `https://s3.amazonaws.com/assets.heroku.com/boomerang/boomerang.js` could be whitelisted, that would be the ideal solution.  Right now it matches with the following filter which is causing the blocking.

```
/boomerang.js
```

**Comment by mikehale** [comment]
@ryanbr any thoughts on this issue?
