### ISSUE TITLE
cnn.com

### ISSUE THREAD

**Issue by Zaharos** [easylist/easylist#12356]
Advertising on `https://www.cnn.com/`

If you are trying to encounter it, please:

- make sure you are using a US IP address
- are not on `edition.cnn.com`
- scroll down

---

Advertising on `https://www.cnn.com/2022/06/18/energy/new-jersey-oregon-pump-your-own-gas/index.html`

- More towards the lower side of the web page
- Please ensure you are connected to a US IP address

---

Encountered while using `uBO`, `Brave Browser (without its built-in ad blocker)`, and a VPN.

**Comment by ryanbr** [comment]
What ad? suggested element / inspect element?  Looks fine here.

**Comment by smed79** [comment]
No ads for me https://i.ibb.co/jLb2pD0/edition-cnn-com-2022-06-18-energy-new-jersey-oregon-pump-your-own-gas-index-html.png

**Comment by Zaharos** [comment]
> If you are trying to encounter it, please:
> 
> * make sure you are using a US IP address
> * are not on `edition.cnn.com`


@smed79

**Comment by Zaharos** [comment]
<img width="1512" alt="edited screenshot" src="https://user-images.githubusercontent.com/107955959/175141708-32415d50-4ba1-41ef-83bc-de9554999161.png">
