### ISSUE TITLE
vidiget.com

### ISSUE THREAD

**Issue by Zaharos** [easylist/easylist#12359]
Could you please take a look at `https://vidiget.com/youtube_downloader`?
Could `mucums.com` and `https://argerm.com/` be blocked?

**Comment by Zaharos** [comment]
@Yuki2718 `vidiget.com##+js(nowoif)`

**Comment by Yuki2718** [comment]
> `vidiget.com##+js(nowoif)`

For what?

**Comment by Zaharos** [comment]
uBO, for instance
At the time there seemed to have been some sort of popup or whatever that would've been called
