### ISSUE TITLE
computerbase.de

### ISSUE THREAD

**Issue by timse201** [easylist/easylist#12361]
### List the website(s) you're having issues:

https://www.computerbase.de/

### What happens?

Easylist Cookie list breaks the site. nothing is clickable. unsubscribing cookie list helps.

### List Subscriptions you're using:

easylist cookie list

### Your settings

- Browser/version: brave 1.40

**Comment by steffenweber** [comment]
@Khrin @ryanbr Developer of ComputerBase here. I've fixed our code such that calling `dialog.close()` or `dialog.remove()` or just blocking the dialog element via `display: none` (such that its `offsetWidth` is 0) is all it takes to close the consent dialog and more importantly to reliably undo all side-effects (i.e. unblurring the page and removing the extra margin-right on various page elements). So for example there is no need to manually remove the "consent-dialog-open" body class anymore, we now handle this automatically when the dialog is removed/closed. Maybe this helps you to make your filters more simple / robust again.
