### ISSUE TITLE
Tracking on `dav.edu.vn`

### ISSUE THREAD

**Issue by vhpcdpgl** [easylist/easylist#12379]
### List the website(s) you're having issues:

`https://www.dav.edu.vn/en/signing-ceremony-for-cooperation-and-exchange-agreement-between-dav-and-vietnam-airlines/`

### What happens?

Tracking appears: `https://log.dav.edu.vn/analytics.js?v=0.5.1`

### List Subscriptions you're using:

`EasyList/EasyPrivacy filters`

### Your settings

- OS/version: Windows 10/Android 11
- Browser/version: Firefox/Chromium
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/issues/12380 (same response)
