### ISSUE TITLE
Tracking on `kemlu.go.id`

### ISSUE THREAD

**Issue by vhpcdpgl** [easylist/easylist#12380]
### List the website(s) you're having issues:

`https://kemlu.go.id/hanoi/en`

### What happens?

Tracking subdomain appears: `https://analytics.kemlu.go.id/matomo.js`

### List Subscriptions you're using:

`EasyList/EasyPrivacy filters`

### Your settings

- OS/version: Windows 10/Android 11
- Browser/version: Firefox/Chromium
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
Also blocked `/matomo.js$domain=~github.com`

**Comment by vhpcdpgl** [comment]
> Also blocked `/matomo.js$domain=~github.com`

But many people just use adblock base on DNS blocking, so this rule cannot be used

**Comment by ryanbr** [comment]
We can't block every script here. EL/EP would be infinitely larger if we include every domain. Maybe if we create a seperate pihole list in the future, just requires additional resources
