### ISSUE TITLE
P: https://www.brighteon.tv/Home/

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylist#12410]
### List the website(s) you're having issues:
[Home page](https://www.brighteon.tv/Home/) and [article pages](https://www.brighteon.tv/LiveTV/)

### What happens?
Rule: `||brighteon.tv/Assets/ARF/ `added on commit https://github.com/easylist/easylist/commit/dfeac83 blocks self-promo banners

I have seen banners linking to...
https://donation.brighteon.com/
https://brighteon.social/about
https://organicbrownrice.brighteonstore.com/
https://microalgaesuperfoodpowder.brighteonstore.com/chlorella-spirulina-superfood-powder

**Suggestion:** Remove rule or move it to Fanboy's Annoyance List

### List Subscriptions you're using:

ABP filters + EasyList
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

<img width="1412" alt="bld" src="https://user-images.githubusercontent.com/57706597/175917108-70ed9042-5153-4cba-b8e2-d73513ee26bd.png">

<img width="1366" alt="blv" src="https://user-images.githubusercontent.com/57706597/175917130-976c9e85-07bc-4914-80eb-2931451624ad.png">

**Comment by ryanbr** [comment]
brighteonstore.com is technically a 3rd-party site.

**Comment by Khrin** [comment]
I don't think this is self-promotion.
