### ISSUE TITLE
[Video Breakage] https://www.worldsurfleague.com

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#12419]
### List the website(s) you're having issues:
https://www.worldsurfleague.com/posts/503783/its-on-day-5-of-the-oi-rio-pro-presented-by-corona

### What happens? 
<img width="1146" alt="Screenshot 2022-06-27 at 21 25 29" src="https://user-images.githubusercontent.com/65717387/176020087-098c1458-9bc5-41d2-b549-66b98b5e900d.png">

Video(live) cannot be played 

### List Subscriptions you're using:

Easylist

**Comment by ryanbr** [comment]
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=worldsurfleague.com
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$script,domain=worldsurfleague.com
@@||pubads.g.doubleclick.net/ssai/*$xhr,domain=worldsurfleague.com
```

Does that work?  @felippesantos46

**Comment by felippesantos46** [comment]
> https://www.worldsurfleague.com/posts/503783/its-on-day-5-of-the-oi-rio-pro-presented-by-corona

In ABP xhr is not a valid filter option. The other 2 alone don't seem to work.

**Comment by ryanbr** [comment]
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=worldsurfleague.com
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$script,domain=worldsurfleague.com
@@||pubads.g.doubleclick.net/ssai/*$domain=worldsurfleague.com

```

Then?

**Comment by yokoffing** [comment]
Just to note: I use NextDNS to filter ads/tracking at a DNS level. Even when disabling uBlock Origin in Firefox and disabling Ghostery in Edge, I still cannot get the video to play. Very pesky issue.

**Comment by felippesantos46** [comment]
@ryanbr @yokoffing Seems to work, maybe due to the end of the event the live is off, on the other hand, now i can at least click the play button. 
Other videos in the page seems to be working fine. I'll keep an eye on the next event (July 12)
