### ISSUE TITLE
timesengland.com

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#12415]
### List the website(s) you're having issues:

`https://www.timesengland.com/`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/175973048-71f46644-f627-436a-bde1-1ce657ab8591.png)

### Your settings

- OS/version: Windows 10
- Browser/version:  Firefox 101.0.1
- Adblock Extension/version:  uBlock Origin 1.43.0

**Comment by Khrin** [comment]
That's nothing of unbearable to leave unblocked.
