### ISSUE TITLE
www.webtexts.com

### ISSUE THREAD

**Issue by mamccr** [easylist/easylist#12437]
### List the website(s) you're having issues:

analytics.webtexts.com and www.webtexts.com

### What happens?

As a result of [this recent commit](https://github.com/easylist/easylist/commit/7675ec7ad407dda17ed469c463491c4a8e4a2747), EasyLink users cannot access analytics.webtexts.com (XHRs that the client there fire to www.webtexts.com get blocked), even though the commit seems to be targeting `https://wlo.link`. Perhaps we could just be added to allowlists?

### List Subscriptions you're using:

Not sure. This was reported to us by our users.

### Your settings

N/A

### Other details:

![image](https://user-images.githubusercontent.com/1957158/176536372-27513b2a-9224-4c2e-b536-e4a4e3c1c169.png)

**Comment by Khrin** [comment]
This filter has been removed yesterday.
