### ISSUE TITLE
Typo in `domain=` option

### ISSUE THREAD

**Issue by gorhill** [easylist/easylist#1243]
There are typos in `domain=` option of three filters in <https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt>: Search for `bipartisanreport.combreaking911.com`. Probably meant to be `bipartisanreport.com|breaking911.com`?

**Comment by Khrin** [comment]
I guess so. https://github.com/easylist/easylist/commit/d2c060498940f747ac99ee78702454927c6bfe06 Thank you, is fixed now.
