### ISSUE TITLE
A: nhl.com (specific cookie banner hide)

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#12449]
### List the website(s) you're having issues:

`nhl.com`

### What happens?

Cookie banner not blocked

### List Subscriptions you're using:

EL Cookie

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 102
- Adblock Extension/version: uBO 1.43.1b3

### Other details:

Suggested filter:
`nhl.com###onetrust-consent-sdk`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_general_hide.txt#L6276

**Comment by peace2000** [comment]
Sorry @Khrin , I was careless.

Didn't notice that uBO's internal filters have a generichide for this domain, which is why it's not hid.

It should be added to this list :https://github.com/easylist/easylist/blob/fc3a6798be88b1f2b07d5a593e2142b25e289933/easylist_cookie/easylist_cookie_specific_uBO.txt#L209

**Comment by krystian3w** [comment]
I see space in filters:

```
nl, cocacolaep.com,pock
```

this then works in latest uBO?
