### ISSUE TITLE
tubitv.com

### ISSUE THREAD

**Issue by DoorCar** [easylist/easylist#12446]
- US IP address may be required to access `tubitv.com` as far as I know

there seems to be (to me / on my machine) `https://tubitv.com/oz/performance/event?sendBeacon=true` after clicking on / selection media

**Comment by DoorCar** [comment]
@Yuki2718 Could you please block it in AdGuard?

**Comment by Yuki2718** [comment]
already blocked by `||analytics-ingestion.production-public.tubi.io^`

**Comment by DoorCar** [comment]
@Yuki2718 I know there where more requests which were blocked, but what about



> `https://tubitv.com/oz/performance/event?sendBeacon=true`

?
