### ISSUE TITLE
[EasyPrivacy] piano.io and tinypass.com

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#12463]
### List the website(s) you're having issues:
`https://www.businessinsider.com/`

### What happens?

`piano.io` and `tinypass.com` run on the background of the page. Seems to be an analytics company (visit `piano.io` to see it).

If `tinypass.com` is blocked, `piano.io` doesn't load. Visiting `tinypass.com` alone redirects to `piano.io`.

### List Subscriptions you're using:

uBlock filters
uBlock filters — Badware risks
uBlock filters — Privacy
uBlock filters — Quick fixes
uBlock filters — Resource abuse
uBlock filters — Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe's Ad and tracking server list
spa, por: AdGuard Spanish/Portuguese

### Your settings

- OS/version: Windows 10 Pro 21H2
- Browser/version: Google Chrome 103.0.5060.66 64 bits
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:
None.

**Comment by DoorCar** [comment]
they can't be outright blocked because they are, as far as I know, paywall-related

**Comment by ryanbr** [comment]
Will break the paywall, we address the issues related https://github.com/easylist/easylist/issues/12338 (using FB Annoyances)
