### ISSUE TITLE
pcgamingwiki.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#12469]
### List the website(s) you're having issues:

`https://www.pcgamingwiki.com/wiki/Balan_Wonderworld`

### What happens?

Missing outgoing links to the site's tracking middleman for Microsoft Store links in the "Availability" table, due to https://github.com/easylist/easylist/commit/5d276cbc593846076c1aaa6e9b447900e96de025

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/22780683/177043996-71429619-c9bd-485d-b88d-2c833fff6844.png)

</details>

### Your settings

- OS/version: Windows 11 21H1 x64
- Browser/version: Chrome 103.0.5060.66 x64
- Adblock Extension/version: uBO 1.43.0 + IDCAC 3.4.1

### Other details:

I propose removing `##a[href^="https://click.linksynergy.com/"]` entirely, on the assumption that a lot of sites are using it.

I'm a fairly active contributor to PCGamingWiki, with the rank of Senior Editor (which doesn't come with any mod rights at all), and I've kept telling their team for probably weeks now to stop using so many ad servers. They have yet to listen to me on that.

<details>
<summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/177052032-13d072fa-91d9-4688-a2dc-b3850c4b7b6b.png)

</details>

**Comment by michaelfairley** [comment]
+1

This has also broken the Xbox buy links on dekudeals.com

5d276cbc593846076c1aaa6e9b447900e96de025 seems to have been overzealous and should probably just be scoped to "yumyumnews.com"

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/02924eeb7f71606c960a60d364de4a7e9c955a18

**Comment by Daxy7** [comment]
ad placeholder
```
https://community.pcgamingwiki.com/files/file/897-gedosato/
```
```
pcgamingwiki.com##[data-role="sidebarAd"]
```
https://github.com/easylist/easylist/assets/91396482/8efe9d48-ccfb-4a8d-8011-e261b44475bb
