### ISSUE TITLE
romaniatv.net

### ISSUE THREAD

**Issue by DoorCar** [easylist/easylist#12471]
`https://www.romaniatv.net/` => `
https://sdk.mrf.io/statics/marfeel-sdk.js?id=1535` and `https://ineed2s.ro/romaniatv.net/scar.connect.js` third-party connections

**Comment by ryanbr** [comment]
Not helpful. Whats the issue? are we missing something to block or is it breaking something?

**Comment by DoorCar** [comment]
@ryanbr I thought that `https://sdk.mrf.io/statics/marfeel-sdk.js?id=1535` might be some sort of tracker and/or unwanted third-party connection on `https://www.romaniatv.net/`

**Comment by Khrin** [comment]
It's not.
