### ISSUE TITLE
cosmeticsnow.com

### ISSUE THREAD

**Issue by robryanx** [easylist/easylist#12488]
### List the website(s) you're having issues:
`https://www.cosmeticsnow.com.au/index.php?main_page=klarna`

### What happens?
Marketing widget images are blocked.

### List Subscriptions you're using:
uBO's enabled-by-default filter lists (PC, English)

### Your settings

- OS/version: Ubuntu
- Browser/version: Firefox 102
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:
Specific rule is:
easyprivacy_thirdparty:
klarnaservices.com^$image,third-party
I assume because they also do some tracking from this domain via images.
Specifically oc-assets.klarnaservices.com/images should be fine to allow though for marketing images.

**Comment by robryanx** [comment]
Hi,
Probably should have suggested this originally.
I think a better rule here would be:

@@||oc-assets.klarnaservices.com/images/$image

This standard marketing information embed would probably be on thousands of websites.

Thanks.

**Comment by Yuki2718** [comment]
Yeah, fixing only for .nz doesn't make much sense to say the least - OP reported .au and I see the same issue on `https://jp.cosmeticsnow.com/index.php`. Maybe better to fine-tune the blocking rule.
