### ISSUE TITLE
sentry.dev

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#12503]
### Steps to reproduce

1. Go to sentry.dev
2. See bug

### Expected behavior

Not Blocked

### Actual behavior

Blocked

**Comment by ryanbr** [comment]
![sentry-dev](https://user-images.githubusercontent.com/1659004/177900344-d37651cc-608b-449d-ba7c-c0ecd28b865e.png)

Seems to be a site issue, not adblock.
