### ISSUE TITLE
Foreca.fi - scrolling gets blocked

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#12507]
### List the website(s) you're having issues:

`https://www.foreca.fi/meteorologilta/o0wnyh6r`

### What happens?

Scrolling goes broken suddenly and there are loading circles as if the page tries to load something:

![kuva](https://user-images.githubusercontent.com/17256841/177817031-b772a601-3df8-408c-a9bf-adf93137c7f5.png)

It's a survey that tries to load.

### List Subscriptions you're using:

Easyprivacy

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 102
- Adblock Extension/version: uBO 1.43.1b3

### Other details:

Open the page always in incognito mode, and then refresh the page once and the issue should appear.

This seems to fix it:
`@@||userneeds.com^$domain=foreca.fi`

After the fix, the survey appears:

![kuva](https://user-images.githubusercontent.com/17256841/177817661-111e9197-4019-4319-b1b9-61102a60b10a.png)

And when I close the survey, scrolling restores. (I first thought the issue was caused by blocking cmp scripts but it was an EP issue after all).

**Comment by Nojuuu** [comment]
@peace2000 
```
||digitalfeedback.euro.confirmit.com/api/digitalfeedback/loader/prod/overlay$xmlhttprequest,domain=foreca.fi
```
Does adding that prevent it completely? I'm not 100℅ sure yet.

**Comment by peace2000** [comment]
> Not seeing it here, is there specific scripts needed? http://webstatustest.dk/ for example had `https://cdn.userneeds.com/unt-lite.js` `https://cdn.userneeds.com/int.js?int=f2lKnHvNgQDb` were blocked (though didn't cause issues)

@ryanbr 

Actually, when checking this more carefully, you'll only need to whitelist the frame so that it won't get blocked.

These requests from userneeds are visible in the logger:

![kuva](https://user-images.githubusercontent.com/17256841/178049663-92927125-8f3a-47d6-8aee-ca29ee35c710.png)

So just this rule is enough:

`@@||survey.userneeds.com^$subdocument,domain=foreca.fi`

It's a bit more narrowed than more initial suggestion and seems to be enough.

Another option is to use

`||digitalfeedback.euro.confirmit.com/api/digitalfeedback/loader/prod/overlay$xmlhttprequest,domain=foreca.fi`

As suggested by @Nojuuu. It does work as well. No more scrolling getting blocked.

The sit is bit tricky. You'll always have to load the page first in incognito mode, then refresh the page once using F5. And if you want to test something again with this site, you'll have to close the browser window and then open incognito again and load the page and press F5.

**Comment by peace2000** [comment]
Though @Nojuuu I don't see any issues if that whole domain is blocked:

`||digitalfeedback.euro.confirmit.com^$domain=foreca.fi`

**Comment by Nojuuu** [comment]
Yeah, everything seems to work fine even if whole domain is blocked.

**Comment by Nojuuu** [comment]
`foreca.com` and `forecaweather.com` needs fixing too.

**Comment by peace2000** [comment]
> `foreca.com` and `forecaweather.com` needs fixing too.

True, the same filters work for them as well.

Hopefully ryanbr is able to repro.

But anyway, these are the ways to fix this:

Either whitelist the survey so that it appears:
`@@||survey.userneeds.com^$subdocument,domain=foreca.fi|foreca.com|forecaweather.com`

Or block it completely and properly by using:
`||digitalfeedback.euro.confirmit.com^$domain=foreca.fi|foreca.com|forecaweather.com`


Another option is to whitelist that survey in EP but block it in Fanboy Notifications. It's whether you consider that whitelisting is privacy risk or not and whether you think that survey is important enough function so that it must work with EP :)

**Comment by Nojuuu** [comment]
The problem still exists?

**Comment by peace2000** [comment]
Not fixed.
