### ISSUE TITLE
Concerns with Bright Data

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#12512]
`https://brightdata.com/`

This website is not in any background of another site, but I am concerned about their data collection.

`https://www.reddit.com/r/software/comments/9w70v4/comment/itagty4/` — this is the only place I've actually seen features from the site in question being used for data collection. (In this case, I linked to my comment.)

I think, perhaps, to avoid data collection in the future, it would be better to block `brightdata.com` with `^$third-party.`

I don't know if this issue is valid, as it's not a problem on any specific site. Anyway, here's the report.

**Comment by ryanbr** [comment]
Would need an example, be pointless to add a domain they don't use for tracking. Wouldn't be surprised they use other domains, and not brightdata.
