### ISSUE TITLE
smooth-on.com support unusable with EasyList Cookie list enabled

### ISSUE THREAD

**Issue by DevilishSpirits** [easylist/easylist#12513]
### List the website you're having issues:

https://www.smooth-on.com/support/ticket/add/

### What happens?

To create a Smooth-On ticket, I need to accept the privacy policy and agree that I am 16 years old at least through checkbox. The `.gdpr` element holding these is well hidden and it is not possible to submit a ticket without disabling the "EasyList Cookie" list.

### List Subscriptions you're using:

* EasyList
* EasyPrivacy
* **EasyList Cookie**
* ...

### Your settings

Privacy Badger (no effect)

- OS/version: ArchLinux with official repositories
- Browser/version: Mozilla Firefox 102.0.1 (64 bits) from ArchLinux official repositories
- Adblock Extension/version: uBlockOrigin 1.43.0

**Comment by ryanbr** [comment]
Worked here, I was able to submit, with attachment.

**Comment by ryanbr** [comment]
```
We've Recieved Your Support Request
Support ticket #N9G-MD7-AV65 has been created.

You should be receiving a confirmation from us in the next few minutes with a link to view your support ticket. If you do not see this email, please check your Junk, Bulk, or Spam folders and mark the message as "Not Spam" to avoid problems receiving future correspondence about this ticket. You can also whitelist general@smooth-on.com to ensure these messages get to your inbox.

You will recieve an email when a Smooth-On technician responds to your ticket, typically within 48 hours. If you have not heard from us by then, please contact us at our technical support phone line.
```
