### ISSUE TITLE
Request of Cleverads.vn [https://cleverads.vn/] Domain Removal from Blocklist

### ISSUE THREAD

**Issue by Buithanhhuong** [easylist/easylist#12511]
Hi Easylist,

My name is Huong - a Legal executive from Clever Group Corporation ("Clever Group") - an entity based in Vietnam. Clever Group is the owner of the website domain **"[cleverads.vn](http://cleverads.vn/)".**

It occurred to us that Easylist has put [cleverads.vn](http://cleverads.vn/) into your blocklist, making users with AdBlock settings cannot access to our website (Please check the matter in the attached picture)
By this email, we would like to make a complaint about this status and request Easylist to remove [cleverads.vn](http://cleverads.vn/) from the blocklist.

Cleverads.vn is a website that provides information of Digital Marketing services, it is neither an ad network, nor an ad platform displayed on a third-party website, so we think that Easylist putting [cleverads.vn](http://cleverads.vn/) on your blocklist is incorrect and inappropriate, which is making a direct negative impact on our business.
 
Clever Group respectfully and strongly requests Easylist to respond to this issue for the Parties to work on this matter promptly, and to immediately remove [cleverads.vn](http://cleverads.vn/) from your blocklist.

I have also sent a request with the same content via email **easylist@protonmail.com** but have not received a response, hope you will solve this problem soon so that our company's business is not affected.

You can contact me by email huong.bui@clevergroup.vn or by phone number (+84)988079654
Thank you for your time and look forward to your response soon.
Yours faithfully,

![image (3)](https://user-images.githubusercontent.com/108921563/177939214-36f05eb2-0173-480c-a75f-191cd541ba49.png)

![image (2)](https://user-images.githubusercontent.com/108921563/177939069-5050e320-a5ad-42d5-b599-553a29957e41.png)

**Comment by ryanbr** [comment]
Comes from https://github.com/d3ward/toolz/blob/master/resources/adblock/data.js#L116

Create a ticket for removal on https://github.com/d3ward/toolz/issues and we'll remove it from here

**Comment by ryanbr** [comment]
@d3ward does youtube.cleverads.vn even exist as used domain?

**Comment by d3ward** [comment]
@ryanbr Yes, it should be a domain that serve a specific category of ads on Youtube . I got proof in past months from users that had that domain blocked by various DNS solutions like NextDNS and AdGuard( not sure if was that or another DNS blocker), also other big popular lists like SB and GoodbyeAds have it . So I decided to include in my list too and in the test tool project . 
Again, I'm not blocking the main domain in my list, so I'm not interfering with their business at all, just that part of the service that provides ads for Youtube. You might want to take a look at other fetched blocklists that EasyList uses like maybe GoodbyeAds which have clearly the "cleverads.vn" blocked in the list ( forgive me , i'm just giving an example , not saying that EasyList really include GoodbyeAds )

**Comment by Buithanhhuong** [comment]
Thank you so much for taking the time to check this out!
However, I have a question, when I check the list of Easylist here https://easylist.to/easylist/easylist.txt and here https://github.com/easylist/easylist/search?q=cleverads.vn&fbclid=IwAR0r9jAEgbY2d56Tg0YAj_Ddod0x4nexYWUFawQOk14RQAvi5NTPJiZmo70, I see cleverads.vn in this list. So can you explain it to me?
Currently, we also do not use the subdomain “youtube.cleverads.vn” as you mentioned above.
Thank you very much!

![image](https://user-images.githubusercontent.com/108921563/178178261-4857c7e1-94dc-4f7f-9cb3-1509dfc3bec1.png)
![image](https://user-images.githubusercontent.com/108921563/178178319-060beb6c-702c-4358-9f6c-887e963a7542.png)

**Comment by ryanbr** [comment]
Also from: https://abpvn.com/android/abpvn.txt  Seems no one trusts cleverads.vn. I'll make it a third-party to avoid breakages.

```
#[cleverads.vn]
0.0.0.0 business.cleverads.vn
0.0.0.0 cleverads.vn
0.0.0.0 showcase.cleverads.vn
0.0.0.0 tool.cleverads.vn
0.0.0.0 tracking.cleverads.vn
0.0.0.0 widget.cleverads.vn
0.0.0.0 wifiads.cleverads.vn
0.0.0.0 www.cleverads.vn
0.0.0.0 youtube.cleverads.vn
```

**Comment by Buithanhhuong** [comment]
Thank you for your support!
