### ISSUE TITLE
sapphiretech.com/en

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12525]
### List the website(s) you're having issues:

`https://www.sapphiretech.com/en`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox Nightly 104
- Adblock Extension/version: uBO 1.43.1b3

### Other details:

![sapphiretech](https://user-images.githubusercontent.com/95879668/178132808-57db8912-26ec-48ea-a9d0-954b86a97429.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/85e55c79b9514dcdf59563e8ec780be01ae0d588
