### ISSUE TITLE
telekom.com/en

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12537]
### List the website(s) you're having issues:

`https://www.telekom.com/en`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox Nightly 104
- Adblock Extension/version: uBO 1.43.1b3

### Other details:

![telekom](https://user-images.githubusercontent.com/95879668/178163126-9b387348-c04f-48b5-b058-9ed0c6c2866b.png)

**Comment by ryanbr** [comment]
Can't block, gets errors on the page. `Sorry, we are not allowed to show you this content due to your cookie settings.
Please activate “Services from other Companies” in your [settings](https://www.telekom.com/en/corporate-responsibility#).`
