### ISSUE TITLE
analytically.net tracking

### ISSUE THREAD

**Issue by RiversideRocks** [easylist/easylist#12553]
### List the website(s) you're having issues:
`scammer.info`

### What happens?
Tracking request sent to `analytically.net`

### List Subscriptions you're using:
UBO default

### Your settings
Only ublock origin

- OS/version: Ubuntu Jammy
- Browser/version: Firefox 102
- Adblock Extension/version: 1.43.0

### Other details:
![image](https://user-images.githubusercontent.com/59586759/178312475-0f71c52c-1dd6-43e9-a6b0-c9fee65bf28b.png)

**Comment by AugmentedThunder** [comment]
This tracking barely logs any information, it's made for privacy... idk why you would block it when it's only used on my domains right now and doesn't even log IP addresses.

**Comment by RiversideRocks** [comment]
Tracking is tracking
