### ISSUE TITLE
atresplayer.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12555]
### List the website(s) you're having issues:

`https://www.atresplayer.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox Nightly 104
- Adblock Extension/version: uBO 1.43.1b3

### Other details:

![atresplayer](https://user-images.githubusercontent.com/95879668/178337078-85be5dee-0fe3-4ef5-aa90-00ab595f439a.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/02f38bb969354af94d3921f6163b7215a4e99603
