### ISSUE TITLE
www.natwest.com and www.backcountry.com

### ISSUE THREAD

**Issue by BranchS** [easylist/easylist#12569]
### List the website(s) you're having issues:
`www.natwest.com`
`www.backcountry.com`

### What happens?
Live chat on these sites is blocked with EasyPrivacy.

On backcountry.com, clicking the live chat button in the header does nothing, when it should open the live chat widget (as it does with EasyPrivacy/AdBlocker off).

On NatWest.com, the aqua colored Need Help? chat button is blocked from loading in the bottom left of the screen.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 11
- Browser/version: Edge 103
- Adblock Extension/version: ABP 3.14.1

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c0c0598581d27f22eaa1c609e0b1c7241c81b8d2
https://github.com/easylist/easylist/commit/8af00dfaadeff8f70a8529558b70f2b14aefca85
