### ISSUE TITLE
Ad whitespace on https://www.topspeed.com/

### ISSUE THREAD

**Issue by joebagadonuts188** [easylist/easylist#12571]
### List the website(s) you're having issues:

https://www.topspeed.com/cars/car-news/new-details-about-the-2023-honda-civic-hybrid-ar196655.html

### What happens?

There are two div tags with ad whitespace. `daily-vid-ad` and `mob-ad`.

### List Subscriptions you're using:

    adguard-spyware-url: 666-13, 1d.10h.13m
    curben-phishing: 24790-0, 1d.10h.13m
    fanboy-cookiemonster: 36095-100, 1d.10h.12m
    easylist: 68555-67, 1d.10h.13m
    easyprivacy: 27377-222, 1d.10h.12m
    ublock-abuse: 75-1, 1d.10h.12m
    ublock-badware: 4222-91, 1d.10h.12m
    ublock-filters: 32156-143, 1d.10h.12m
    ublock-privacy: 226-3, 1d.10h.12m
    ublock-quick-fixes: 206-5, 1d.10h.12m
    ublock-unbreak: 1833-47, 1d.10h.12m
    urlhaus-1: 5151-1, 1d.10h.12m

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Chrome Version 103.0.5060.114 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

Just requesting to block or remove the ad whitespace for a cleaner look.

**Comment by ryanbr** [comment]
Not seeing it

**Comment by joebagadonuts188** [comment]
Try going into developer tools and look for `daily-vid-ad` and `mob-ad`. The `daily-vid-ad` space is right after the paragraph that ends `, but here’s what the Civic Hybrid will be like when it arrives in the US.`

**Comment by joebagadonuts188** [comment]
Here is a screenshot:
![topspeed screenshot](https://user-images.githubusercontent.com/100051044/178613987-3207d0f3-075a-482c-84e7-28b2c1d36890.JPG)
