### ISSUE TITLE
[Cookie consent warning] www.google.com

### ISSUE THREAD

**Issue by alestr** [easylist/easylist#12579]
### List the website(s) you're having issues:

`https://www.google.com`

### What happens?

Google Cookie consent popup is back

### List Subscriptions you're using:

uBlock filters https://github.com/uBlockOrigin/uAssets/tree/master/filters
uBlock filters – Badware risks https://github.com/uBlockOrigin/uAssets/tree/master/filters
uBlock filters – Privacy https://github.com/uBlockOrigin/uAssets/tree/master/filters
uBlock filters – Quick fixes https://github.com/uBlockOrigin/uAssets/tree/master/filters
uBlock filters – Resource abuse https://github.com/uBlockOrigin/uAssets/tree/master/filters
uBlock filters – Unbreak https://github.com/uBlockOrigin/uAssets/tree/master/filters
EasyList https://github.com/easylist/easylist/tree/master/easylist
EasyPrivacy https://github.com/easylist/easylist/tree/master/easyprivacy
Online Malicious URL Blocklist https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt
**EasyList Cookie https://github.com/easylist/easylist/tree/master/easylist_cookie**
Peter Lowe’s Ad and tracking server list https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
NOR, DNK, ISL: Dandelion Sprouts nordiske filtre https://github.com/DandelionSprout/adfilt/blob/master/NorwegianList.txt

### Your settings

- OS/version: Windows 10 Version 21H2 (OS Build 19044.1766)
- Browser/version: Chrome Version 103.0.5060.114 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

Hiding the popup will disable the scroll on search results.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/tree/master/easylist_cookie
