### ISSUE TITLE
youtube.com - Other sponsored videos in sidebar

### ISSUE THREAD

**Issue by mchangrh** [easylist/easylist#12584]
### List the website(s) you're having issues:
`https://www.youtube.com/watch?v=_QPPLacWr-4`

### What happens?

Infobox featuring sponsored video is visible in the side panel

### List Subscriptions you're using:

EasyList, uBlock filters, AdGuard Base + Mobile

### Other details:

Suggested filter
```
youtube.com##ytd-engagement-panel-section-list-renderer
```

It also seems to inject the video into the top of the recommendations bar but there is no way to remove it
![image](https://user-images.githubusercontent.com/15132783/178855110-5d958612-6142-4eaa-9ec5-08988ae80193.png)

****

**Comment by LordManhattan** [comment]
Can confirm. I'm suddenly seeing ads on Youtube (sidebar), and on Reddit. I've manually blocked them, but this surely shouldn't happen! 

**uBlock version:** uBlock Origin 1.43.0
**Browser:** Microsoft Edge v.103.0.1264.62
