### ISSUE TITLE
alternativeto.net ad container

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#12583]
### List the website(s) you're having issues:

`https://alternativeto.net/software/microsoft-word`

### What happens?

Ad container

![kuva](https://user-images.githubusercontent.com/17256841/178851815-eccada9e-ac60-4f13-b60c-d5e886f00789.png)

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 102.0.1
- Adblock Extension/version: uBO 1.43.1b3

### Other details:

Maybe a generic filter?

`##[class*="AdsenseAd"]`

Or a specific?

`alternativeto.net##.AdsenseAd_putFood__h0Ah0`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/1d4699d6eca53f7477e90629cb9572f63669a922
