### ISSUE TITLE
EasyList blocks YouTube shorts comments box from showing up

### ISSUE THREAD

**Issue by RCECoder** [easylist/easylist#12603]
### List the website(s) you're having issues:
All YouTube short videos.
for instance, https://www.youtube.com/shorts/kB9NZAdhPSE

### What happens?
Comments box doesn't show up.

### List Subscriptions you're using:
uBlock filters

uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
AdGuard Base
EasyList
AdGuard Tracking Protection
EasyPrivacy
Online Malicious URL Blocklist
AdGuard Annoyances
uBlock filters – Annoyances
Peter Lowe’s Ad and tracking server list

### Your settings

- OS/version: Windows 10 Pro 19H2
- Browser/version: Mozilla Firefox 102.0.1
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:
Unchecking EasyList filters solves this issue and the comment box will then show up.
It was working fine yesterday. Probably a recent update to EasyList caused this.
Disabling cosmetic filters on YouTube seems to also does the trick.

**Comment by ryanbr** [comment]
Update the lists.
