### ISSUE TITLE
jampartizan.com

### ISSUE THREAD

**Issue by bowie0021** [easylist/easylist#12604]
### List the website(s) you're having issues:

`https://jampartizan.com/en/games/review/page=8e35406179c1861b9459f9cddba1c1b2`

### What happens?

This website has an ad server called `zx-adnet.com`

### List Subscriptions you're using: 

EasyList, EasyPrivacy, Fanboy's Annoyance

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

`||zx-adnet.com^$third-party`

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/109369779/179321731-ef74418c-14dc-480f-a77b-aaff8b269a06.png)

</details>

**Comment by ryanbr** [comment]
Not covinced its an adserver. Moved it too EP , also based on homepage origins.
