### ISSUE TITLE
bbc.co.uk

### ISSUE THREAD

**Issue by DesertBear** [easylist/easylist#12643]
### List the website(s) you're having issues:

```
https://www.bbc.co.uk/news
```

### What happens?

After viewing three BBC News pages, it displays a fullscreen sign in page. It may not appear for people with IP addresses that are not in the UK, I don't know. Steps to reproduce:

**A)** Go to https://www.bbc.co.uk/news/business-62226912

**B)** Go to https://www.bbc.co.uk/news/technology-62236778

**C)** Go to https://www.bbc.co.uk/news/science-environment-62234196

**D)** On the third page, it displays a fullscreen sign in page (see screenshot)

**Screenshot A:**

![Screesnshot A](https://user-images.githubusercontent.com/27423064/179998560-49e77380-359d-47c9-a9de-b4b14dcfa113.png)

When manually adding the below rule to uBlock Origin, the sign in dialogue no longer appears, however it's not possible to scroll the page anymore.
```
bbc.co.uk##.e34ixc510.ssrcss-veoawf-Overlay
```
When manually adding either of the below rules as well, it's still not possible to scroll the page.
```
bbc.co.uk##html:style(overflow: visible !important;)
```
```
bbc.co.uk##:root:style(overflow-y: visible !important;)
```

### List Subscriptions you're using:

Fanboy’s Annoyance

### Your settings

```
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 91467
  cosmetic: 157934
  scriptlet: 24377
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55146-76, now
    block-lan: 43-0, 2m
    fanboy-annoyance: 75576-3116, 1m
    ublock-annoyances: 4494-213, 1m
  default: 
    user-filters: 84-0, never
    easylist: 68658-91, 2m
    easyprivacy: 27428-221, 2m
    plowe-0: 3645-781, 1m
    ublock-abuse: 76-0, 1m
    ublock-badware: 4204-92, 1m
    ublock-filters: 32241-487, 1m
    ublock-privacy: 226-12, 1m
    ublock-quick-fixes: 239-9, 1m
    ublock-unbreak: 1834-47, 1m
    urlhaus-1: 5198-0, 1m
filterset (user): [array of 84 redacted]
trustedset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 20 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4147 ms
  maxAssetCacheWait: 601 ms

```

### Other details:
Also reported for "AdGuard Annoyances" list here:
https://github.com/AdguardTeam/AdguardFilters/issues/124932

**Comment by ryanbr** [comment]
I'm not seeing it, suggested filters welcome.

**Comment by DesertBear** [comment]
The below seems to work, however check that it makes sense, as I have no experience writing filter rules…

```
bbc.co.uk##div[class^="ssrcss-veoawf-Overlay"]
bbc.co.uk##html,body:style(overflow: auto !important;)
```

**Comment by ryanbr** [comment]
Looking at it further, we won't block a signup popup. Newsletter/subscription popups, sure. People will complain instantly.

**Comment by DesertBear** [comment]
I'm talking about adding it to the "Fanboy’s Annoyance" list – not Easylist/Easy Privacy lists.
