### ISSUE TITLE
xataka.com - Incorrect blocking breakage

### ISSUE THREAD

**Issue by fernandomora** [easylist/easylist#12656]
### List the website(s) you're having issues:
https://www.xataka.com/accesorios/nuevo-walkie-talkie-xiaomi-tiene-alcance-5-000-kilometros-problema-que-no-solo-walkie-talkie

### List Subscriptions you're using:

Fanboy’s Annoyance 

### Your settings

- OS/version: macOS Monterrey 12.4 (21F79)
- Browser/version: Firefox 102.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:
This filter seems to break the video: https://github.com/easylist/easylist/blob/3623ba0fa60647cafb077e58a768b6bfde1103f5/easylist_cookie/easylist_cookie_thirdparty.txt#L92
When filter is enabled video is not reproducible and only a black box is rendered

<img width="790" alt="image" src="https://user-images.githubusercontent.com/3585704/180300219-bb2434f3-a25a-4115-aa54-9f8d8b2ebeac.png">

**Comment by ryanbr** [comment]
I'm not seeing this @fernandomora 

![xat](https://user-images.githubusercontent.com/1659004/180347967-a0f2909c-a4f5-4b2a-8ae7-ce82e0ae6425.png)

If I wait long enough, it'll just disappear and play the video

**Comment by fernandomora** [comment]
Not sure. I can reproduce it each time I have tested. 🤷 
How much time did you wait?
I have tried to wait around 5minutes and I can see only a black box with no option to reproduce the video.

Let me try to define the steps to reproduce

* uBlock Origin 1.43.0
* Firefox 102.0.1 (64-bit)
* Only uBlock Origin extension enabled (rest of extensions disabled)
* Only `Fanboy’s Annoyance` filter enabled. (rest of filters disabled)
* uBlock Origin of my configuration: [my-ublock-backup_2022-07-23_02.16.32.reproduce.easylist:easylist#12656.txt](https://github.com/easylist/easylist/files/9172755/my-ublock-backup_2022-07-23_02.16.32.reproduce.easylist.easylist.12656.txt)

<img width="680" alt="image" src="https://user-images.githubusercontent.com/3585704/180582275-8ba0c9e7-4d60-43e8-8dd9-c12be9754fdd.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3585704/180582435-974a9f2e-b6ea-46d2-acdb-93ba1655681c.png">

After that, if I disable the filter adding either `!||privacy-center.org^$third-party,badfilter` or `@@||privacy-center.org^$third-party` to my custom filters, the video can reproduce and it autoplay on page load

**Comment by fernandomora** [comment]
In fact, if I test disabling all filters and only adding this single custom filter `||privacy-center.org^$third-party` I can also reproduce the problem:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3585704/180583764-f7a67c86-4af9-4441-b870-5aed7b163456.png">

Disabling it makes it work.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3585704/180584015-815f7569-d27f-4205-9c09-f0493b7bccc1.png">

**Comment by Yuki2718** [comment]
Need EU IP. BTW AG hides the video as annoyance (`xataka.com##.base-asset-video`).

**Comment by fernandomora** [comment]
> Need EU IP. BTW AG hides the video as annoyance (`xataka.com##.base-asset-video`).

Yes I also notified it here https://github.com/AdguardTeam/AdguardFilters/issues/124991

**Comment by krystian3w** [comment]
Kiboke now deleted block `privacy-center.org`, EL :cookie: maybe not.

**Comment by peace2000** [comment]
`sdk.privacy-center.org` was seemingly whitelisted for the page but I don't have any issues even if I block `sdk.privacy-center.org` completely.

**Comment by krystian3w** [comment]
So can be blocked again.
