### ISSUE TITLE
urbandictionary.com upvotes and downvotes not working

### ISSUE THREAD

**Issue by DavidH-2022** [easylist/easylist#12667]
### What happens?

When Easyprivacy and EasyList are enabled upvote or downvotes won't work

### List Subscriptions you're using:
Easylist
EasyPrivacy

### Your settings

- OS/version: macOS 12.5
- Browser/version: 
- Adblock Extension/version: uBlock Origin 1.43.1b7

**Comment by ryanbr** [comment]
Even with uBO disabled, I couldn't upvote @DavidH-2022

**Comment by DavidH-2022** [comment]
Well seems like a site problem. Closing.
