### ISSUE TITLE
ygeiaonline.gr booking ad

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#12660]
### List the website(s) you're having issues:
https://www.ygeiaonline.gr/listing/%CE%B1%CE%B8%CE%AE%CE%BD%CE%B1/%CE%B3%CE%B9%CE%B1%CF%84%CF%81%CE%BF%CE%AF/%CF%83%CE%B2%CE%BF%CE%BB%CE%BF%CF%80%CE%BF%CF%85%CE%BB%CE%BF%CF%85-%CE%B1%CE%B9%CE%BA%CE%B1%CF%84%CE%B5%CF%81%CE%B9%CE%BD%CE%B7/

### What happens?
Booking ad banner

### List Subscriptions you're using:
All filters offered by uBlock Origin

### Your settings

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 102.0.1
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:
Screenshot:
![Screenshot 2022-07-23 at 11-31-50 Σβολοπουλου Αικατερινη Βρες γιατρό](https://user-images.githubusercontent.com/101707608/180598153-9b76adcb-9f94-47ae-b6ff-f838b4a58c3d.png)

**Comment by DimitrisKalaboukas** [comment]
Suggested filter:
ygeiaonline.gr##.booking-sticky-footer

**Comment by ryanbr** [comment]
We only support English sites in EL @DimitrisKalaboukas
