### ISSUE TITLE
Domains that need blocking

### ISSUE THREAD

**Issue by zira** [easylist/easylist#12678]
Block

analyticsengine.s3.amazonaws.com
affiliationjs.s3.amazonaws.com
advertising-api-eu.amazon.com
amazonaax.com
amazonclix.com
advertising.twitter.com
ads-dev.pinterest.com
widgets.pinterest.com
d.reddit.com

Used https://d3ward.github.io/toolz/adblock.html to get this. 

A VPN I am using is using Easylist.

**Comment by ryanbr** [comment]
No. https://github.com/d3ward/toolz/issues/31
