### ISSUE TITLE
Sanoma Corporation video / audio unbreak

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#12681]
### List the website(s) you're having issues:

This concerns Sanoma Corporation `https://en.wikipedia.org/wiki/Sanoma` owned websites that use Sanoma's embedded video/audio content.

`aamulehti.fi`
`embed.sanoma-sndp.fi`
`etlehti.fi`
`gloria.fi`
`hs.fi`
`hyvaterveys.fi`
`is.fi`
`jamsanseutu.fi`
`janakkalansanomat.fi`
`kankaanpaanseutu.fi`
`kmvlehti.fi`
`kodinkuvalehti.fi`
`merikarvialehti.fi`
`nelonen.fi`
`nokianuutiset.fi`
`rakennuslehti.fi`
`rannikkoseutu.fi`
`ruutu.fi`
`sanoma.fi`
`satakunnankansa.fi`
`soppa365.fi`
`supla.fi`
`suurkeuruu.fi`
`sydansatakunta.fi`
`tiede.fi`
`tyrvaansanomat.fi`
`valkeakoskensanomat.fi`
`vauva.fi`

Some samples:
`https://www.is.fi/viihde/art-2000006292715.html`
`https://www.supla.fi/audio/4130855`
`https://www.aamulehti.fi/urheilu/art-2000008921515.html`
`https://www.etlehti.fi/artikkeli/ihmiset/parasta-lapissa-ehottomasti-ihimiset-ja-puhas-luonto-katso-video`
`https://www.soppa365.fi/reseptit/kana/video-taydellinen-broilerinfilee`
`https://www.hs.fi/ulkomaat/art-2000008740885.html` (`embed.sanoma-sndp.fi`)

### What happens?

Video playback takes longer time to start and audio playback is not working.

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 102.0.1
- Adblock Extension/version: uBO 1.43.1b8

### Other details:

I suggest this rule:

`@@||v.fwmrm.net/ad/g/*Nelonen*_HTML5_Live$script,domain=aamulehti.fi,embed.sanoma-sndp.fi,etlehti.fi,gloria.fi,hs.fi,hyvaterveys.fi,is.fi,jamsanseutu.fi,janakkalansanomat.fi,jimtv.fi,kankaanpaanseutu.fi,kmvlehti.fi,kodinkuvalehti.fi,merikarvialehti.fi,nelonen.fi,nokianuutiset.fi,rakennuslehti.fi,rannikkoseutu.fi,ruutu.fi,sanoma.fi,satakunnankansa.fi,soppa365.fi,supla.fi,suurkeuruu.fi,sydansatakunta.fi,tiede.fi,tyrvaansanomat.fi,valkeakoskensanomat.fi,vauva.fi`

Or:

`@@||v.fwmrm.net/ad/g/*Nelonen*_HTML5_Live$script`

It's safe to drop out domains from this rule as text "Nelonen" in the rule makes it unique enough identifier. "Nelonen". Means "Four" in the Finnish language and it refers to the Finnish TV channel 4 `https://en.wikipedia.org/wiki/Nelonen`, which is owned by Sanoma Corporation. (Nelonen is used as a platform for other Sanoma's sites to host videos as well). Generic rule is safe and won't mix with other sites. I think that it's probably better to drop domains because it's easier maintain and futureproof (Sanoma could found new websites for their services).

**Comment by ryanbr** [comment]
Can we block those consents messages without causing issues? @peace2000

**Comment by peace2000** [comment]
@ryanbr Nope, I've had issues with Tweets if cookies haven't been accepted.

**Comment by stephenhawk8054** [comment]
These 2 filters can cause broad ads exceptions for other sites (first one will enable 2nd one)

```adb
@@||fwmrm.net^*/admanager.js$script
@@||v.fwmrm.net/ad/g/1?*_html5_live$from=~gulli.fr|~msn.com
```

Example: `https://www.atresplayer.com/lasexta/programas/al-rojo-vivo/septiembre-2023/18-09-23-calvino-pronostica-un-crecimiento-de-espana-superior-al-de-los-paises-grandes-del-euro-para-finales-de-2023_650843867152b0e4c9cf2eb6/` (needs free account and Spain IP)

I think at least 1 of them can be domain-specific?
