### ISSUE TITLE
edition.cnn.com/sport

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#12698]
### List the website(s) you're having issues:

`https://edition.cnn.com/sport`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/181035468-70ae67c3-b10a-4630-af8a-2bec64544e81.png)

### List Subscriptions you're using:

--

### Your settings

- OS/version: Windows 10
- Browser/version:  Firefox 102.0.1 
- Adblock Extension/version:  uBlock Origin 1.43.0

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/05d98e6639c6d87770018433683b11841039ec37
