### ISSUE TITLE
http://www.nationalreview.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#127]
`http://www.nationalreview.com/`

Multiple Expedia ads on left and right.

`http://www.nationalreview.com/corner/438960/study-vast-majority-gun-crime-isnt-committed-lawful-gun-owners`

Bellroy ad on the right.

`http://www.nationalreview.com/corner/438989/gun-control-research-data-sharing`

Tableau ad at top and on the right (twice).

`http://www.nationalreview.com/article/439024/gun-lobby-political-clout-members-campaign-contributions`

NRA ad at top.

**Comment by monzta** [comment]
They seem to be gone. Can you confirm?

**Comment by terrorist96** [comment]
Gone!
