### ISSUE TITLE
coolors.co

### ISSUE THREAD

**Issue by bri-dahl** [easylist/easylist#12718]
### List the website(s) you're having issues:
`https://coolors.co`

### What happens?
There are ads displayed on coolors, particularly noticeable and annoying in the palette generator.

### List Subscriptions you're using:
built-in ublock filters, adguard base, easylist, easyprivacy, online malicious url blocklist, adguard annoyances, adguard social media, anti-facebook, fanboy's annoyance, ublock filters annoyances, peter lowe's ad and tracking server list

### Your settings

- OS/version: Zorin OS 16.1
- Browser/version: Vivaldi 5.3.2679.70 (Stable channel) stable (64-bit)
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:
![Screenshot from 2022-07-27 09-22-13](https://user-images.githubusercontent.com/86103080/181189520-5f308d98-7dfb-4353-a53a-ab4057a35534.png)

**Comment by bri-dahl** [comment]
That works for me too, thanks so much!

**Comment by itsthejoker** [comment]
This does not work anymore :(

**Comment by BrentWardOx** [comment]
@itsthejoker @bri-dahl 

I found a new filter which works for this! Try this:
```
coolors.co##a:not([href]):has(div)
```

Explanation: I inspected their page and found that Coolor places all of their ads within divs contained within A tags without hrefs. No other elements on their site seem to be structured like this. Thus, the CSS Selector `a:not([href]):has(div)` hides their ads

**Comment by bri-dahl** [comment]
Thanks! This only partially works though, it hides ads in the generator but not everywhere on the site. It also hides the profile button, making that inaccessible unless I navigate to the profile using the URL, which is a bit inconvenient.

**Comment by BrentWardOx** [comment]
Oh, okay! The filter I provided is not a perfect solution then.

I only tested this out on the Color Pallet generator page as a guest. In that specific scenario, the filter appears to work 100%. It probably needs some further tweaking to work across the entire website. Hopefully this gets you closer to your solution!

**Comment by bri-dahl** [comment]
Working for me! Thank you!
