### ISSUE TITLE
qiuwen.wiki

### ISSUE THREAD

**Issue by hyperpxy** [easylist/easylist#12725]
### List the website(s) you're having issues:

``https://www.qiuwen.wiki``
``https://www.qiuwenbaike.cn``

### What happens?
Tracking script is loaded

### List Subscriptions you're using:
- EasyList
- EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 103
- Adblock Extension/version: UBO 1.43.0

### Other details:
``https://audit.qiuwen.wiki/analytics.js``

**Comment by ryanbr** [comment]
Force an update

**Comment by krystian3w** [comment]
Also banned in https://github.com/AdguardTeam/AdguardFilters/commit/bd231225479baf35ebf20d079138ba15ae0c556e
