### ISSUE TITLE
(NSFW) LuxureTV

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#12733]
https://en.luxuretv.com

When opening websites, on bottom right corner there is ads leftovers with X (to close ads)

Filterlists:

Fanboy Ultimate, uBlock filters (filters, privacy, resource abuse, annoyances), adguard filters (base, mobile, tracking protection, annoyances, social, experimental), Peter Lowe’s Ad and tracking server list and Web Annoyances Ultralist.

OS/version: Lubuntu 20.04
Browser/version: Vivaldi 5.3
Adblock Extension/version: uBlock Origin development build 1.43.1b10

**Comment by ryanbr** [comment]
Not seeing it
