### ISSUE TITLE
OpenStreetMap.org

### ISSUE THREAD

**Issue by Firefishy** [easylist/easylist#12736]
### List the website(s) you're having issues:

`https://www.openstreetmap.org/
`
### What happens?

Easylist blocking not-for-profit OpenStreetMap.org conference image because we use `<div id="banner">`

### List Subscriptions you're using:

easylist_specific_hide.txt

### Your settings

- OS/version: Any
- Browser/version: Any 
- Adblock Extension/version: Any

### Other details:

OpenStreetMap.org is a not-for-profit open source project (think wikipedia but 1000x smaller), we run an annual conference but since [2018](https://github.com/easylist/easylist/commit/b5c76ea17e12b95c711ce512c2389795fc853bd0#comments) easylist has blocked the the `div` we use for showing the conference link. 

OK if we change the `<div id="banner">` to `<div id="event">`? [We don't want to start a petty arms war](https://github.com/openstreetmap/openstreetmap-website/pull/1743).

Easylist disallowing our conference image is widely disliked:
- https://twitter.com/OSM_Tech/status/1548767996264550404
- https://github.com/easylist/easylist/commit/b5c76ea17e12b95c711ce512c2389795fc853bd0

**Comment by pnorman** [comment]
The current block rule breaks functionality by blocking the notices when editing is down for maintenance, as well as notifications of upcoming maintenance.

**Comment by ryanbr** [comment]
- We don't judge a website based whether its profit or non-profit.
- If banner is used for ads and announcements, then separate them.
- When linking to a 3rd-party site, then its not considered a self promo. And is considered an Advert.

If we have to update this filter, so be it.

**Comment by pnorman** [comment]
> When linking to a 3rd-party site, then its not considered a self promo. And is considered an Advert.

SOTMs, the conferences the OSM community puts on, are not third party events put on by other people. They're on a different domain name, but it's all run by the OSM community.

**Comment by Firefishy** [comment]
It isn't a 3rd-party website, it is using our project's name for our conference "State of the Map", similar to Debian calling their conference "DebConf".

https://github.com/openstreetmap/stateofthemap-2022

**Comment by Firefishy** [comment]
We have never run any ADs nor do we intend to! We are an Open Source data project, and we are trying to create free map data for an open world.

We have linked to our conference. Using yes, a kludgy image, which you specifically target.

**Comment by krystian3w** [comment]
Perhaps it is also about the rule: once incorrect blocked, a self-promo cannot be unblocked.

**Comment by Firefishy** [comment]
> To avoid cover section maybe needed is use random ID (on any refresh) and base64 images.

Yes, we could do something like that, and this is what I specifically ask about us change the `<div id="banner">` to `<div id="event">` but we do not want to start a petty arm war, see https://github.com/openstreetmap/openstreetmap-website/pull/1743
