### ISSUE TITLE
scmp.com

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#12730]
### List the website(s) you're having issues:

`https://www.scmp.com/lifestyle/health-wellness/article/3186221/climate-anxiety-how-help-young-people-cope-84-cent-are#comments`

### What happens?

Ad placeholders in comments

![image](https://user-images.githubusercontent.com/84513173/181493078-d0d0a25a-16e6-4519-a52a-07499890eb5f.png)

### List Subscriptions you're using:

--

### Your settings

- OS/version: Windows 10
- Browser/version:  Firefox 103
- Adblock Extension/version:  uBlock Origin 1.43.0

**Comment by ryanbr** [comment]
Not seeing it

**Comment by Nojuuu** [comment]
Do you see it here `https://www.scmp.com/scmp_comments/popup/3186765` ?
