### ISSUE TITLE
myaccount.google.com

### ISSUE THREAD

**Issue by kunzajap** [easylist/easylist#12741]
### List the website(s) you're having issues:

`https://www.google.com/intl/en-GB/account/about/privacy-tools/`

<details>
 <summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/109770855/181657927-f91420b7-d6e0-4db4-a2a6-d6adfcdfdc19.png)

</details>

`https://myaccount.google.com/intro/yourdata/search`

<details>
 <summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/109770855/181657899-72306e29-35ad-4bed-9597-2eb6d8b32a02.png)

</details>

### What happens?

Ad personalization page does not open when EasyList is active.

### List Subscriptions you're using:
EasyList

### Your settings

- OS/version: 
- Browser/version: Chrome 103
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

I couldn't find which rule was causing this issue. I tried the below rules but it didn't work.

/googleads.$~script,domain=~github.com|~github.io|~myaccount.google.com
||doubleclick.net^$third-party,domain=~myaccount.google.com
||doubleclick.net^$popup,domain=~myaccount.google.com
@@||doubleclick.net^$popup
@@||doubleclick.net^$third-party
youtube.com#@#.ytp-ad-progress-list

**Comment by ryanbr** [comment]
Need to post more details, see https://forums.lanik.us/viewtopic.php?t=47722-google-com-adsense as an example of what we need (of a similar issue)

**Comment by kunzajap** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14162#issuecomment-1199560431

**Comment by krystian3w** [comment]
Both works fine.
