### ISSUE TITLE
https://fingerprinter-production.herokuapp.com

### ISSUE THREAD

**Issue by hKQwHW** [easylist/easylist#12759]
### List the website(s) you're having issues:
https://bestiefy.com
https://fingerprinter-production.herokuapp.com

### List Subscriptions you're using:
See https://github.com/uBlockOrigin/uAssets/issues/14150, the things I am using are listed there

### Your settings
Disabled all extensions (Privacy Badger, DDG privacy essentials, clean URLs, CSS exfil portection, builtin tracking prevention, etc.) 

- OS/version: Windows 11
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock origin 1.43.0 (purged cache & updated all filters today, EasyPrivacy is on)

### Other details:

https://fingerprinter-production.herokuapp.com/visitors/(long string of lowercase letters and numbers)/audience_segments is requested by https://bestiefy.com on the same settings as above. It is used for fingerprinting "audience segments"

This seems to be caused by `tyche`, however, the `tyche` script needs to not be blocked completely, due to the issues described in https://github.com/uBlockOrigin/uAssets/issues/14150 (stack trace):
```
8599/value/<
[https://cdn.intergi.com/hera/tyche.js:1:80749](https://cdn.intergi.com/hera/tyche.js)
value
[https://cdn.intergi.com/hera/tyche.js:1:80313](https://cdn.intergi.com/hera/tyche.js)
8599/value/<
[https://cdn.intergi.com/hera/tyche.js:1:77857](https://cdn.intergi.com/hera/tyche.js)
(Async: promise callback) value
[https://cdn.intergi.com/hera/tyche.js:1:77832](https://cdn.intergi.com/hera/tyche.js)
value
[https://cdn.intergi.com/hera/tyche.js:1:77508](https://cdn.intergi.com/hera/tyche.js)
e
[https://cdn.intergi.com/hera/tyche.js:1:77365](https://cdn.intergi.com/hera/tyche.js)
mt
[https://cdn.intergi.com/hera/tyche.js:1:92609](https://cdn.intergi.com/hera/tyche.js)
8599/vt/<
[https://cdn.intergi.com/hera/tyche.js:1:96340](https://cdn.intergi.com/hera/tyche.js)
8599/e.emit/i<
[https://cdn.intergi.com/hera/tyche.js:1:1416](https://cdn.intergi.com/hera/tyche.js)
8599/e.emit
[https://cdn.intergi.com/hera/tyche.js:1:1388](https://cdn.intergi.com/hera/tyche.js)
value
[https://cdn.intergi.com/hera/tyche.js:1:63641](https://cdn.intergi.com/hera/tyche.js)
8599/value/</<
[https://cdn.intergi.com/hera/tyche.js:1:64729](https://cdn.intergi.com/hera/tyche.js)
(Async: promise callback) 8599/value/<
[https://cdn.intergi.com/hera/tyche.js:1:64667](https://cdn.intergi.com/hera/tyche.js)
value
[https://cdn.intergi.com/hera/tyche.js:1:63720](https://cdn.intergi.com/hera/tyche.js)
value
[https://cdn.intergi.com/hera/tyche.js:1:62310](https://cdn.intergi.com/hera/tyche.js)
vt
[https://cdn.intergi.com/hera/tyche.js:1:96688](https://cdn.intergi.com/hera/tyche.js)
8599
[https://cdn.intergi.com/hera/tyche.js:1:96854](https://cdn.intergi.com/hera/tyche.js)
n
[https://cdn.intergi.com/hera/tyche.js:1:154178](https://cdn.intergi.com/hera/tyche.js)
<anonymous>
[https://cdn.intergi.com/hera/tyche.js:1:156717](https://cdn.intergi.com/hera/tyche.js)
<anonymous>
[https://cdn.intergi.com/hera/tyche.js:1:156734](https://cdn.intergi.com/hera/tyche.js)
```

**Comment by ryanbr** [comment]
Not seeing (again)

![bestiefy](https://user-images.githubusercontent.com/1659004/182008723-87ed8e34-c1ac-4745-87c3-c082ef3ba9a7.png)

**Comment by hKQwHW** [comment]
That is weird. I'm going to look into it hmm
