### ISSUE TITLE
towersemi.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#12755]
### List the website(s) you're having issues:

`https://towersemi.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO default lists

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox Nightly 105
- Adblock Extension/version: uBO 1.43.1b10

### Other details:

![towersemi](https://user-images.githubusercontent.com/95879668/181924019-c12091b4-001b-4f4b-b647-a0a3ea129719.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/87993df104bf36756a41ad76ba6894b109f31755
