### ISSUE TITLE
iltalehti.fi, suomif1.com

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#12778]
### List the website(s) you're having issues:

`https://www.iltalehti.fi/formulat/a/8184acb6-f3e2-4e78-8a85-4039a5b430d0`

`https://www.suomif1.com/2022/07/missasitko-unkarin-dramaattisen-aika-ajon-katso-kooste/`

`https://www.suomif1.com/2022/07/valtteri-bottas-avasi-surkeaa-kilpailuaan-tehot-vain-havisivat/`

### What happens?

Embedded video not working

"The programme cannot be shown. Check the connections and turn off any adblocker. Click here to try again."

![image](https://user-images.githubusercontent.com/84513173/182030882-b1e32bc9-4eaf-4973-b271-e7a022283408.png)

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

`@@||v.fwmrm.net/crossdomain.xml$xmlhttprequest,domain=embed.viaplay.com`

Seems to fix it. It is up to you whether it should be allowed or not.

**Comment by peace2000** [comment]
Fyi @DandelionSprout if this gets added, you can remove this from your filters:

![kuva](https://user-images.githubusercontent.com/17256841/182042942-6baf8499-a7b7-4621-a56a-b5795c1b4644.png)

You can also remove this one:
![kuva](https://user-images.githubusercontent.com/17256841/182042959-c78fb2fd-5ecf-49c9-aa9d-e1c97e4af89d.png)

As it's already covered by this commit: https://github.com/easylist/easylist/commit/c0b1942d82390ed8798a02642d517fbf1d2e32e4

**Comment by Nojuuu** [comment]
Same issue:
`https://www.suomikiekko.com/2022/03/patrik-laineelta-jalleen-loisto-ottelu-teki-maalin-ja-tarjoili-upean-passin-joukkuekaverilleen-katso-tasta/`

**Comment by peace2000** [comment]
That's not anti adblock, it's a warning that video could not be played, and issue could be related to adblocker.

**Comment by peace2000** [comment]
Translation of that message is not fully accurate. There's a word "mahdollinen" which translates to "possible".

**Comment by Nojuuu** [comment]
crossdomain.xml just tells the data handling permissions across multiple domains.

+ I don't get any ads even if I turn uBO off.
