### ISSUE TITLE
http://hightimes.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#128]
`http://hightimes.com/`

KandyPens/Quartz ad (one at top, one further down the page), buddabox ad on right

`http://hightimes.com/edibles/edibles-101-how-to-maximize-your-experience-without-a-meltdown/`

SourceNail (vapes) ad (one at top, one at bottom)

**Comment by monzta** [comment]
They seem to be gone. Can you confirm?

**Comment by terrorist96** [comment]
Confirmed. :heart:
