### ISSUE TITLE
Header cuts off text on https://www.revolt.tv/

### ISSUE THREAD

**Issue by joebagadonuts188** [easylist/easylist#12826]
### List the website(s) you're having issues:

`https://www.revolt.tv/`

### What happens?

The header is cutting off text.

### List Subscriptions you're using:

adguard-spyware-url: 666-13, 1d.10h.13m
curben-phishing: 26833-0, 5m
fanboy-cookiemonster: 36095-100, 1d.10h.12m
easylist: 68555-67, 1d.10h.13m
easyprivacy: 27377-222, 1d.10h.12m
ublock-abuse: 75-1, 1d.10h.12m
ublock-badware: 4222-91, 1d.10h.12m
ublock-filters: 32156-143, 1d.10h.12m
ublock-privacy: 226-3, 1d.10h.12m
ublock-quick-fixes: 206-5, 1d.10h.12m
ublock-unbreak: 1833-47, 1d.10h.12m
urlhaus-1: 5151-1, 1d.10h.12m

### Your settings

OS/version: Win 10 21H1
Browser/version: Chrome Version 104.0.5112.81 (Official Build) (64-bit)
Adblock Extension/version: uBlock Origin 1.43.0

**Comment by ryanbr** [comment]
Not sure what I'm looking for, `https://www.revolt.tv/article/2022-08-05/184625/pregnant-woman-killed-in-fiery-los-angeles-car-crash-identified-police-make-an-arrest/` looks fine to me @joebagadonuts188

**Comment by joebagadonuts188** [comment]
Thanks for responding. So for me, the problem seems to be the header on the page seems to cut into the text of the headline of the article. It make take a few seconds before you see it happen. I went to the link you suggested and saw it there as well.

![revolt tv screenshot](https://user-images.githubusercontent.com/100051044/183311902-16dd9f74-dd1b-4379-8436-9861ed509609.JPG)

**Comment by ryanbr** [comment]
What I'm seeing, (does seem to auto scroll after a few seconds)

![revolt](https://user-images.githubusercontent.com/1659004/183343032-224877c6-933b-4e1a-af98-30377944be94.png)

**Comment by joebagadonuts188** [comment]
The problem seems to be that after auto scrolling (transitioning), it will cover up the text of the headline. It just seems like a poorly formatted website. I was just looking for a cosmetic solution.
