### ISSUE TITLE
ABP specific section on EL

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#12834]
I noticed that uBO and probably AG as well load these ABP-specific rules (screenshot from uBO):

![kuva](https://user-images.githubusercontent.com/17256841/183244305-2f687aeb-f1f2-4322-81e4-dbedbb0c3bcd.png)

They originate from `adult_specific_hide.txt`.

Shouldn't they be moved to a separate abp-specific file?

Or at least wrap them with:

`!#if ext_abp`
`......`
`!#endif`

That would tell uBO and Adguard to ignore them, but ABP would still load them.

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#if-condition
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#conditions

**Comment by Khrin** [comment]
No reason for this senseless change.

**Comment by peace2000** [comment]
Just a sec, will have to check to if-condition again...

**Comment by peace2000** [comment]
I'm not sure if I was understood correctly.

What I meant, was to add a specific tag, that would tell uBO and Adguard not to load ABP-specific rules.

I meant like this:
```
! Advanced element hiding rules for Adblock Plus
!#if ext_abp
crocotube.com#?#.ct-related-videos-title:-abp-contains(Advertisement)
crocotube.com#?#.ct-related-videos-title:-abp-contains(You may also like)
erofus.com#?#div:-abp-has(> .ad)
pornhub.com,pornhubthbh7ap3u.onion#?#:-abp-properties(height: 300px; width: 315px;)
pornhub.com,pornhubthbh7ap3u.onion,youporn.com#?#:-abp-properties(float: right; margin-top: 30px; width: 50%;)
redtube.com,tube8.com,tube8.es,tube8.fr,xvideos.com,youjizz.com,youporn.com,youporngay.com#?#:-abp-properties(*data:image*)
redtube.com,tube8.com,tube8.es,tube8.fr,xvideos.com,youjizz.com,youporn.com,youporngay.com#?#:-abp-properties(base64)
redtube.com,tube8.com,tube8.es,tube8.fr,xvideos.com,youjizz.com,youporn.com,youporngay.com#?#:-abp-properties(data:)
redtube.com,tube8.com,tube8.es,tube8.fr,xvideos.com,youjizz.com,youporn.com,youporngay.com#?#:-abp-properties(image/)
youporn.com#?#aside:-abp-has(a.ad-remove)
!#endif
```

**Comment by ryanbr** [comment]
Those rules also translated on uBO (and working on), making it pointless adding ext_abp
