### ISSUE TITLE
adlock.com overlapping intrusive ad

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#12847]
### List the website(s) you're having issues:
https://adlock.com/adlock-for-android/

### What happens?
Aggressive promotional ad that cannot be closed.

### List Subscriptions you're using:
All filters offered by uBlock Origin.

### Your settings

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 103.0.1
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:
Screenshot:
![Screenshot 2022-08-07 at 15-52-48 Ad Blocker App for Android Phone Download APK Free AdLock](https://user-images.githubusercontent.com/101707608/183292773-be7343db-37ae-44ed-91d5-5fe22c2b3a76.png)

**Comment by ryanbr** [comment]
Seems fine, just a self promo on their site.

**Comment by DimitrisKalaboukas** [comment]
@ryanbr could you provide me with a custom filter for this annoyance?

**Comment by ryanbr** [comment]
`adlock.com##.adl__spec__disc__content
`
