### ISSUE TITLE
roblox.com

### ISSUE THREAD

**Issue by ThePotato97** [easylist/easylist#12854]
### List the website(s) you're having issues:
``roblox.com/user-sponsorship/``
``ads.roblox.com``
``games.roblox.com/v1/games/list``
``https://www.roblox.com/discover#/``

### What happens?
``roblox.com/home`` still sends a request to ``roblox.com/user-sponsorship/`` as the filter is only cosmetic, and it should also block ``||roblox.com/user-sponsorship/*`` to prevent impressions being recorded.
``games.roblox.com/v1/games/list`` needs the sponsored sort blocking like ``games.roblox.com/v1/games/list?sortToken=*_Sponsored^``
``ads.roblox.com`` seems to be on the allowlist for some reason even though it's probably recording impressions, I personally didn't notice any issues when I overrode the exception.

### Other details:
``roblox.com##.games-list-container:has-text(Sponsored)`` can be used to remove the sort from ``https://www.roblox.com/discover#/``

**Comment by ryanbr** [comment]
No issues here.  Just not enough information that can't be reproduce. Closing
![roblox-t](https://user-images.githubusercontent.com/1659004/184280966-b0646848-9b86-4eb0-b902-71f1f487d360.png)

**Comment by ThePotato97** [comment]
> No issues here. Just not enough information that can't be reproduce. Closing ![roblox-t](https://user-images.githubusercontent.com/1659004/184280966-b0646848-9b86-4eb0-b902-71f1f487d360.png)

![image](https://user-images.githubusercontent.com/10260415/184286848-a78d93f8-9784-4a1d-963f-aa897273f221.png)
![image](https://user-images.githubusercontent.com/10260415/184286937-b22db537-45b8-4f34-9ec6-91b734ec82b5.png)
![image](https://user-images.githubusercontent.com/10260415/184287023-8e5be9b3-84d6-4ba6-907d-de030a6e1fc8.png)

**Comment by ryanbr** [comment]
You need to supply more information than this, "response time" in dev tools doesn't give anyone any ideas. Maybe show some inspect of the ad element?

**Comment by ThePotato97** [comment]
EasyList only hides the skyscraper iframes it doesn't prevent them from sending the requests so roblox is still able to log ad impressions even if the user doesn't see the ads.

Go to https://www.roblox.com/home

Open Network tab in firefox/chrome developer tools

You will notice that the iframes still send the request to get the ads.
![image](https://user-images.githubusercontent.com/10260415/185150744-d298dd72-4257-48d2-98f9-da932632d199.png)

Now add ``||roblox.com/user-sponsorship^`` to my filters and refresh again

You will notice that these requests are now blocked
![image](https://user-images.githubusercontent.com/10260415/185151924-fa69e342-0fc3-448e-831f-d8606040cffc.png)
