### ISSUE TITLE
Amazon Associates Link Builder is getting blocked

### ISSUE THREAD

**Issue by geek-hut** [easylist/easylist#1286]
Please help create a solution to this issue. Products which are added to my website using Amazon Associates Link Builder are being flagged as spam ads by ABP Adblocker.

AdBlockPlus & Adblock’s filtering list named EasyList has added all the CSS & JS of the plugin into their blocking list in Mid-May, 2018. 

My website is loosing all of its product information for anyone using adblock. 

I would like to request Ad-Blocker to remove ‘.aalb-pa-ad-unit, amazon-associates-link- & ProductAd’ from their filtering list.

I don't know if this is the right place to raise the issue. I was pointed to Github from the Amazon Associates Link Builder Support forum.
https://wordpress.org/support/topic/my-products-have-dissappeared-using-associates-link-builder/#post-10364087

**Comment by ryanbr** [comment]
force update

**Comment by geek-hut** [comment]
Hi, are you asking me to force an update on the adblocker list? How do I do that?
