### ISSUE TITLE
vanityfair.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#12879]
### List the website(s) you're having issues:

- `https://www.vanityfair.com/style/2022/06/john-franzese-jr-flipped-on-one-of-historys-most-notorious-mobsters`

### What happens?

- There are leftover whitespaces from ad removal; they can be removed with: `vanityfair.com##.ad`

### List Subscriptions you're using:

- Added
  - adguard-spyware-url
  - block-lan
  - curben-phishing
  - curben-pup
  - adguard-annoyance
  - ublock-annoyances
- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

### Your settings

- OS/version: macOS 12.5
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43

### Other details:

![image](https://user-images.githubusercontent.com/110956608/183982572-6e4acf7f-7014-4e6a-9a8a-ace778ce925b.png)

**Comment by ryanbr** [comment]
Looks fine here.
