### ISSUE TITLE
RyobiTools.eu - Broken functions (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#12871]
### Affected site:
`https://www.ryobitools.eu/` (..and all sub domains)

### Issue:
Broken functions, because of a blocked cookie consent which needs to be accepted!

### Example:
`https://uk.ryobitools.eu/`

Move your mouse cursor over the "SHOP BY" button, in the navigation header..
* Expected result: A menu should appear.
* Actual result: Nothing happens!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
`###onetrust-banner-sdk`
`###onetrust-consent-sdk`

### Possible fix:
`ryobitools.eu#@##onetrust-banner-sdk`
`ryobitools.eu#@##onetrust-consent-sdk`

### Additional fix:
`||ryobitools.eu^*/NewsletterPopup-*$script` (Newsletter popup)

### Other problem filters:
* **AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/126737/
`###onetrust-consent-sdk`
`||cookielaw.org^$third-party`

* **I don't care about cookies** _(@kiboke)_
`###onetrust-consent-sdk`

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: Pale Moon v31.2.0.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by kiboke** [comment]
@THEtomaso Thank you, it will be fixed in IDCAC soon.

**Comment by THEtomaso** [comment]
@Yuki2718:
For '**uBlock filters - Cookie Notices**':
```
ryobitools.eu##+js(trusted-click-element, [id="onetrust-banner-sdk"] [id="onetrust-pc-btn-handler"])
ryobitools.eu##+js(trusted-click-element, [id="onetrust-pc-sdk"] .save-preference-btn-handler, , 1000)
ryobitools.eu##[id="onetrust-consent-sdk"]
```
