### ISSUE TITLE
motherjones.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#12878]
### List the website(s) you're having issues:

- `https://www.motherjones.com/crime-justice/2022/03/gail-ritchey-neonaticide-trial-geauga-county/`

### What happens?

- Ad placeholders are visible. They can be blocked with `motherjones.com##.incontent-promo`

### List Subscriptions you're using:

- Added
  - adguard-spyware-url
  - block-lan
  - curben-phishing
  - curben-pup
  - adguard-annoyance
  - ublock-annoyances
- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

### Your settings

- OS/version: macOS 12.5
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43

### Other details:

![image](https://user-images.githubusercontent.com/110956608/183981758-7d6953f8-cf18-478e-9d08-5583e47e5551.png)

**Comment by ryanbr** [comment]
Looks fine here.
