### ISSUE TITLE
newyorker.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#12881]
### List the website(s) you're having issues:

- `https://www.newyorker.com/`

### What happens?

- There are marketing/subscription ads throughout the home page. They can be blocked with: `newyorker.com##.ticker-view:has(.consumer-marketing-unit)`

### List Subscriptions you're using:

- Added
  - adguard-spyware-url
  - block-lan
  - curben-phishing
  - curben-pup
  - adguard-annoyance
  - ublock-annoyances
- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

### Your settings

- OS/version: macOS 12.5
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43

### Other details:

![image](https://user-images.githubusercontent.com/110956608/183983576-e6bd7559-4240-48ef-8e93-523162251d86.png)

**Comment by ryanbr** [comment]
No htanks.
