### ISSUE TITLE
rollingstone.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#12886]
### List the website(s) you're having issues:

- `https://www.rollingstone.com/feature/black-widower-how-one-man-allegedly-murdered-two-wives-199999/`

### What happens?

- There are empty/whitespace-filled `<p>` elements before and after the inline ads which are creating extra space between some paragraphs in articles. They can be blocked with the following filters (but maybe there's a better way of doing this?)
  ```
  rollingstone.com##p:has-text(/^\s*$/):has(+ .admz)
  rollingstone.com##.admz + p:has-text(/^\s*$/)
  ```

### List Subscriptions you're using:

- Added
  - adguard-spyware-url
  - block-lan
  - curben-phishing
  - curben-pup
  - adguard-annoyance
  - ublock-annoyances
- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

### Your settings

- OS/version: macOS 12.5
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43

### Other details:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/110956608/184026836-b1d9a0a5-b278-416b-880a-591200d2148b.png">

**Comment by ryanbr** [comment]
So much filtering that? No.
