### ISSUE TITLE
rollingstone.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#12880]
### List the website(s) you're having issues:

- `https://www.rollingstone.com/feature/black-widower-how-one-man-allegedly-murdered-two-wives-199999/`

### What happens?

- GotChosen ad carousel, can be blocked with: `rollingstone.com##.gcwp-carousel`

### List Subscriptions you're using:

- Added
  - adguard-spyware-url
  - block-lan
  - curben-phishing
  - curben-pup
  - adguard-annoyance
  - ublock-annoyances
- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

### Your settings

- OS/version: macOS 12.5
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43

### Other details:

![image](https://user-images.githubusercontent.com/110956608/183983074-13176669-0d99-4226-8b82-1e0d2d874ba0.png)

**Comment by ryanbr** [comment]
Blocked in FB Annoyances.
