### ISSUE TITLE
statnews.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#12885]
### List the website(s) you're having issues:

- `https://www.statnews.com/2019/06/25/alzheimers-cabal-thwarted-progress-toward-cure/`

### What happens?

- `statnews.com##[class*="dfp-ad"]` ad placeholder
- `statnews.com##.stat-form-inline` inline newsletter form

### List Subscriptions you're using:

- Added
  - adguard-spyware-url
  - block-lan
  - curben-phishing
  - curben-pup
  - adguard-annoyance
  - ublock-annoyances
- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

### Your settings

- OS/version: macOS 12.5
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43

### Other details:

![image](https://user-images.githubusercontent.com/110956608/184024552-79245bc6-49ea-4c1b-a71f-58ad28d89cef.png)

---

![image](https://user-images.githubusercontent.com/110956608/184024603-e7bd4d02-2581-4c93-8f68-aff3765b1ab9.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5dc23213778ff26b49e0b15bd3d7207db6db79ac
