### ISSUE TITLE
Houseofbruar link blocked on freetree.io

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylist#12891]
### List the website(s) you're having issues:
https://www.freetree.io/en/freetree-shop-search/

### What happens?
Go to https://www.freetree.io/en/freetree-shop-search/ and search for **houseofbruar** 
EL filter: `||srvtrck.com^` seems to be blocking the redirect from: https://r.srvtrck.com/ to: https://www.houseofbruar.com/

<img width="1281" alt="ch1" src="https://user-images.githubusercontent.com/57706597/184181586-1b2d5f96-2532-4ccf-874c-3dc77c79afe2.png">

It seems to be filter issue, not really a proxy issue since when ABP is disabled page loads and it doesn't happen if you search for any other store such as: AliExpress | otto

**Chrome Error:** 
Access to r.srvtrck.com was denied
You don't have authorisation to view this page.
HTTP ERROR 403
<img width="1204" alt="ch2" src="https://user-images.githubusercontent.com/57706597/184181602-eac61de5-3f5d-4960-9a8d-9b44daa0a66d.png">

[Reference Safari error](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/466#issuecomment-475943077)
<img width="1320" alt="s2" src="https://user-images.githubusercontent.com/57706597/184181825-3eadce49-f674-423c-ac8a-53b507806897.png">

<img width="1128" alt="fx2" src="https://user-images.githubusercontent.com/57706597/184197199-09b69bf9-98e8-4f9b-94ca-88546fa4ac31.png">

### List Subscriptions you're using:

ABP filters + EL

### Filter suggestion
`@@||srvtrck.com$domain=freetree.io`
`||srvtrck.com^$third-party`
<img width="1233" alt="srvt" src="https://user-images.githubusercontent.com/57706597/184182831-d0600972-c3ca-465a-961c-bef1a2ad77a1.png">

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6cbb6fbdd477a70408e07887c753c9573f6ac620
