### ISSUE TITLE
theguardian.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#12907]
### List the website(s) you're having issues:

- `https://www.theguardian.com/us`

### What happens?

- Privacy banner; can be blocked with: `||sourcepoint.theguardian.com/unified/*/ccpa.*.bundle.js$script,1p`

### List Subscriptions you're using:

- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

### Your settings

- OS/version: macOS 12.5
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43

### Other details:

![image](https://user-images.githubusercontent.com/110956608/184354380-5c3c0e64-bb95-48d4-b78c-6028e1af9cf0.png)

**Comment by ryanbr** [comment]
you can break the site with `||sourcepoint.theguardian.com^`  and didn't see `||sourcepoint.theguardian.com/unified/*/ccpa.*.bundle.js$script,1p`  Videos will break on https://www.theguardian.com/us-news/2019/mar/22/mueller-report-trump-russia-investigation-completed-latest-news
