### ISSUE TITLE
bloomberg.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#12902]
### List the website(s) you're having issues:

- `https://www.bloomberg.com/news/features/2022-02-18/wall-street-banker-profits-off-phoenix-housing-inflation-and-soaring-rent-prices`

### What happens?

- There are leaderboard, square, and vertical ad containers visible. They can be targeted with `##.page-ad`.

### List Subscriptions you're using:

- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

### Your settings

- OS/version: macOS 12.5
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43

### Other details:

![image](https://user-images.githubusercontent.com/110956608/184282698-a02122f1-bfe9-425b-a94d-8c1796021411.png)

---

![image](https://user-images.githubusercontent.com/110956608/184282729-6579ed37-a247-4cd1-830c-3a2816a76077.png)

---

![image](https://user-images.githubusercontent.com/110956608/184282746-99b4cede-e5e6-4b2f-ab86-681a65bf1ebd.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/pull/12036

**Comment by ryanbr** [comment]
sure, okay

**Comment by Daxy7** [comment]
new homepage leaderboard banner
________________________________________________________________________________________________________________________________
![image](https://user-images.githubusercontent.com/91396482/225621344-7d49aa1e-512c-4e5b-b2c1-a472cc72ad06.png)
________________________________________________________________________________________________________________________________

**Comment by dportvine** [comment]
`https://www.bloomberg.com/profile/company/1774397D:CH`

<details>
<summary>Screen</summary>

![2024-04-22_153947](https://github.com/easylist/easylist/assets/111344219/3faf3aa5-2a61-4aee-ae03-4667fdbaa9d1)
</details>
