### ISSUE TITLE
[NSFW] nutaku.net: breakage (EasyList Cookie)

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#12903]
### List the website(s) you're having issues:
[NSFW] `https://nutaku.net`

### What happens?

`##.js-disclaimer:not(html):not(body)` breaks the page.
### List Subscriptions you're using:

EasyList Cookie
### Your settings

- OS/version: Windows
- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin

### Other details:

https://github.com/uBlockOrigin/uAssets/issues/14357

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e0700796ff6e71a64ac9af218e1a6d434b12c014
