### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#12925]
### List the website(s) you're having issues:
`https://twitter.com/twitter`

### What happens?
annoyances

### List Subscriptions you're using:
uBO ebd + `Fanboy's Annoyances List`

### Your settings

- OS/version: 
- Browser/version: chrome 
- Adblock Extension/version: uBO

### Other details:
![image](https://user-images.githubusercontent.com/111154278/184461315-8c3366eb-7688-49f4-8cbf-54f9ddfac0a8.png)
![image](https://user-images.githubusercontent.com/111154278/184461377-76bd9be5-f392-4383-ac5a-2ca088aa6cdb.png)

**Comment by ryanbr** [comment]
WIll break too much, not worth attempting without probable webcompat issues.

**Comment by Sandvici** [comment]
@ryanbr I think the AdGuard Annoyances filter had some rules that did a great job
