### ISSUE TITLE
ebihoreanul.ro

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#12921]
### List the website(s) you're having issues:
`https://www.ebihoreanul.ro/`

### What happens?
unblocked third-party connection (`https://pahtky.tech/c/ebihoreanul.js`)

### List Subscriptions you're using:
uBO enabled-by-default filter lists + road-block lite filter list

### Your settings

- OS/version: 
- Browser/version: chrome
- Adblock Extension/version: uBO

### Other details:

Could `||pahtky.tech^` be added to EasyPrivacy?

**Comment by LikesCakes** [comment]
I encountered `pahtky.tech` as third-party on `https://ziarulunirea.ro/foto-sicoe-mihai-noul-presedinte-interimar-al-tsd-alba-tinerii-social-democrati-si-au-ales-noul-presedinte-si-un-nou-birou-de-conducere-786090/`

**Comment by LikesCakes** [comment]
I encountered `servg1.net` as a third-party on `https://www.mobilissimo.ro/`

**Comment by LikesCakes** [comment]
`https://sfatulparintilor.ro/` - `pahtef.tech` seemingly after accepting prompt

**Comment by LikesCakes** [comment]
`https://sfatulparintilor.ro/` - `pahtef.tech` seemingly after accepting something on a prompt

**Comment by LikesCakes** [comment]
`https://timponline.ro/` -> `pahtgq.tech` third-party connection

**Comment by LikesCakes** [comment]
`https://sfatulparintilor.ro/` -> third-party connection `pahtef.tech` seemingly after accepting something on a prompt
