### ISSUE TITLE
mezha.media

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#12959]
### List the website(s) you're having issues:

`https://mezha.media/2022/08/16/apple-pohrozhuie-zvilnyty-spivrobitnyka-cherez-virusne-video-na-tiktok-khocha-vono-ne-porushuie-pravyl-kompanii/`

### What happens?

EasyPrivacy breaks tiktok player `||mcs-va.tiktok.com^`

<details>
<summary>Screen</summary>

![2022-08-16_110547](https://user-images.githubusercontent.com/111344219/184830454-798f6253-deb9-4b84-8bcb-2f311157bc79.png)
</details>
 
### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 21H2 x64
- Browser/version:  Google Chrome 104.0.5112.81
- Adblock Extension/version:  uBO 1.43.0

**Comment by ryanbr** [comment]
No issues here @dportvine

**Comment by dportvine** [comment]
@ryanbr 
<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/111344219/184873544-bf6778d0-e0ad-4cf6-b5b1-6ea0c0b44b55.gif)
</details>

**Comment by peace2000** [comment]
@dportvine Does this fix it?

`@@||mcs-va.tiktok.com/v1/user/webid$xmlhttprequest,domain=tiktok.com`

**Comment by dimisa-RUAdList** [comment]
@peace2000 
Yes, this exception solves the problem.
