### ISSUE TITLE
Problems with cookie confirmation dialog on some big czech sites

### ISSUE THREAD

**Issue by vybiral-tomas** [easylist/easylist#12961]
### List the website(s) you're having issues:

* www.super.cz
* www.sport.cz
* www.seznam.cz
* www.garaz.cz
* www.seznamzpravy.cz

### What happens?

If user comes first on any of mentioned pages on newer firefox (101+) and refreshes page (or waits for a little while), they are then redirected to `www.seznam.cz/nastaveni-souhlasu/<some-data>`, where if easylist privacy is used only white screen will be shown instead of normal dialog.

What happens:
![image](https://user-images.githubusercontent.com/109524618/184834059-b1508f64-0c45-4304-8a30-7a377b294df1.png)

What should happen:
![image](https://user-images.githubusercontent.com/109524618/184834957-ce9671a7-d66e-4cf5-81fd-d41476ea45a7.png)

### List Subscriptions you're using:

* uBlock Origin - in default settings

### Your settings

- OS/version: Manjaro Linux
- Browser/version: Firefox v101+
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

* please add exception to blocking rule `h.seznam.cz` if the url is `www.seznam.cz/nastaveni-souhlasu/`

**Comment by ryanbr** [comment]
Sure, lets see how this goes. I couldn't reproduce it.
