### ISSUE TITLE
knowablemagazine.org

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#12999]
### List the website(s) you're having issues:

- `https://knowablemagazine.org/article/living-world/2022/deep-diving-animals-ocean-twilight-zone`

### What happens?

- @ryanbr re: https://github.com/easylist/easylist/commit/fea299dff2594cd22d0736c6e831df80fbde3aa0 the YouTube embed works for me even when `#onetrust-consent-sdk` is blocked. I think this domain can be removed from exception now?

### List Subscriptions you're using:

- Added
  - fanboy-cookiemonster
- Default
  - ublock-filters
  - ublock-badware
  - ublock-privacy
  - ublock-abuse
  - ublock-unbreak
  - ublock-quick-fixes
  - easylist
  - easyprivacy
  - urlhaus-1
  - plowe-0

### Your settings

- OS/version: macOS 12.5
- Browser/version: Firefox 103
- Adblock Extension/version: uBlock Origin 1.43

**Comment by ryanbr** [comment]
sure, okay.
