### ISSUE TITLE
Outside Inc. sites

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13012]
### List the website(s) you're having issues:

- `https://www.backpacker.com/skills/outdoor-first-aid/how-to-hike-during-smoke-season/`

### What happens?

- banner ad: `backpacker.com,betamtb.com,betternutrition.com,cleaneatingmag.com,climbing.com,gymclimber.com,outsideonline.com,oxygenmag.com,pelotonmagazine.com,rockandice.com,skimag.com,trailrunnermag.com,triathlete.com,vegetariantimes.com,velonews.com,womensrunning.com,yogajournal.com##.c-thinbanner`

### Your settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
listset: 
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

### Other details:

<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/110956608/185799337-62ccaf63-664a-4c82-8417-a574a3f229da.png)

</details>

**Comment by Yuki2718** [comment]
@ryanbr @Khrin `##.c-thinbanner` is not ad, should be moved to Annoyances (maybe newsletter).
