### ISSUE TITLE
prospect.org

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13032]
### List the website(s) you're having issues:

- `https://prospect.org/economy/real-inflation-reduction-acts/`

### What happens?

- ad container

### Your settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
listset: 
  added:
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

### Other details:

<details><summary>Screenshot 1</summary>

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110956608/185945129-dca9cfeb-0c83-4f6e-aab9-7df82f7f863e.png">

</details>

**Comment by ryanbr** [comment]
Too minor.
