### ISSUE TITLE
brisbanetimes.com.au

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13036]
### List the website(s) you're having issues:

- `https://www.brisbanetimes.com.au/`
- `https://www.smh.com.au/`
- `https://www.theage.com.au/`
- `https://www.watoday.com.au/`

### What happens?

There's a big ad area at the top of each of these sister sites.

### Your settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
listset: 
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

### Other details:

<details><summary>Screenshot 1</summary>

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110956608/186042288-940c159d-bf47-41a7-8b36-4a3233e844c1.png">

</details>

**Comment by ryanbr** [comment]
Not blockable in standard EL.
