### ISSUE TITLE
XDA Developers new thread title field getting removed

### ISSUE THREAD

**Issue by mica** [easylist/easylist#1303]
If you try to create a new thread on the XDA Developers forum, the title field is missing. Like on this page, for example: https://forum.xda-developers.com/newthread.php?do=newthread&f=2591

**Comment by krystian3w** [comment]
I have title  input:

```html
<table cellpadding="0" cellspacing="0" border="0" class="fieldset" style="width: 100%;'">
   <tbody>
      <tr>
         <td class="smallfont" colspan="4">Title:</td>
      </tr>
      <tr>
         <td>
            <input type="text" class="bginput" id="inputthreadtitle" name="subject" value="" size="40" maxlength="85" tabindex="1">
         </td>
         <td>&nbsp;&nbsp;</td>
         <td><img id="display_posticon" src="clear.gif" alt=""></td>
      </tr>
   </tbody>
</table>
```

![image](https://user-images.githubusercontent.com/35370833/41233616-46046cee-6d8a-11e8-80b8-e03d4f2fa407.png) |
--- |

strange rule if cut `table` or `input`.

**Comment by peace2000** [comment]
I can see that title field. This issue probably isn't relevant anymore. @Khrin
