### ISSUE TITLE
Crux Knowledge trackers

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13031]
### List the website(s) you're having issues:

- `https://prospect.org/environment/can-ocean-shipping-go-green/`

### What happens?

Crux Knowledge trackers:

`||api*.crux.kn^$3p`

### Your settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
listset: 
  added:
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Doesn't seem to be a tracker
