### ISSUE TITLE
https://dogecubex.live/analytics

### ISSUE THREAD

**Issue by BenGochoumo** [easylist/easylist#13043]
### List the website(s) you're having issues:
<code>
https://dogecubex.live
</code>
       
Requests:
```
<code>https://dogecubex.live/api/analytics/summary-v2.json?currency=XRD</code>
<code>https://dogecubex.live/api/analytics/tokens.json?currency=XRD</code>
<code>https://dogecubex.live/api/analytics/swaps.json</code>
```

### What happens?

Adblocker Ultimate and Ublock origin block the above requests.

### List Subscriptions you're using:

I've contacted Adblocker Ultimate and they said that they use EasyList.

### Your settings

Pure Adblocker Ultimate in Firefox.

- OS/version: Win/21H2
- Browser/version: Mozilla Firefox/multiple
- Adblock Extension/version: Adblocker Ultimate/3.7.18  Ublock origin/1.44.0

**Comment by Khrin** [comment]
Those requests are already blocked by `/api/analytics/*` in EasyPrivacy. https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L763

**Comment by BenGochoumo** [comment]
@Khrin what do you mean closed?
Those are not ads, why are they blocked?
