### ISSUE TITLE
csmonitor.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13049]
### URLs

- `https://www.csmonitor.com/USA/Education/2022/0822/More-cash-fewer-requirements-States-scramble-for-teachers`

### Description

- cookie notice

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
listset: 
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/110956608/186208743-13882a6b-700b-4da4-808a-fe69aaebea2f.png)

</details>

**Comment by ryanbr** [comment]
we're blocking this already.
