### ISSUE TITLE
Detect Adblock website detects nano adblock + defender!

### ISSUE THREAD

**Issue by Someguy14201** [easylist/easylist#1304]
https://www.detectadblock.com/

"You're Blocking Ads"

It should be "You're Allowing Ads" But it isn't. How is it detecting?

**Comment by krystian3w** [comment]
Strange on Firefox 61 with uBO 1.16.8 + Self-signed Nano Defender 14.49 I have: You're allowing ads.

![obraz](https://user-images.githubusercontent.com/35370833/41193714-817ed4d8-6c10-11e8-8f9f-9348058ab0c8.png)

**Comment by krystian3w** [comment]
Fixed with Nano Defender 14.50 for Chrome / Edge.
