### ISSUE TITLE
mothership.sg

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#13059]
### List the website(s) you're having issues:

`https://mothership.sg/2022/08/st-andrews-student-threatens-teacher/`

### What happens?

Sponsored links in the "Other stories" section below the article.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/22780683/186411910-38596b3d-6b29-41ee-b7ac-8d129f589209.png)

</details>

### Your settings

- OS/version: Windows 11 21H1 x64
- Browser/version: Chrome 104.0.5112.102 x64
- Adblock Extension/version: uBO 1.43.0 + IDCAC 3.4.2

### Other details:

I propose `mothership.sg#?#div[class*=" _popIn_"]:has(> ._popIn_recommend_art_media)`

Screenshot:

<details>

![image](https://user-images.githubusercontent.com/22780683/186411712-c9d713d1-7443-4417-b659-3585525aaeb1.png)

</details>

**Comment by ryanbr** [comment]
Not seeing "popin" recommendations here
![mothership](https://user-images.githubusercontent.com/1659004/186430533-33ec2317-9dc3-4aa4-8ce6-c9bf92a1ecc4.png)
.

**Comment by DandelionSprout** [comment]
Seems to me that `||googletagmanager.com^` in EasyPrivacy fixes it on your end.

Perhaps that entry, or at least something like `||googletagmanager.com/gtm.js?id=` could be added to EasyList as well.

**Comment by Khrin** [comment]
Can't reproduce also with EasyPrivacy disabled.
