### ISSUE TITLE
js.sentry-cdn.com

### ISSUE THREAD

**Issue by gyCfjSnO** [easylist/easylist#13056]
### List the website(s) you're having issues:

```js.sentry-cdn.com```

### What happens?

When ```js.sentry-cdn.com``` is blocked it breaks ```https://www.pizzahut.com.au/``` can't put store information or address in etc.

Unblocking ```js.sentry-cdn.com``` allows for postcode/address to be put in to set delivery or pickup of pizza.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
I suspect its not the issue. I'm currently getting `Sorry, we could not find a store that delivers to your address. You may be able to pick up from a nearby store.` message regardless of any adblock being enabled or not

**Comment by gyCfjSnO** [comment]
> I suspect its not the issue. I'm currently getting `Sorry, we could not find a store that delivers to your address. You may be able to pick up from a nearby store.` message regardless of any adblock being enabled or not

That's strange, I blocked the domain and tried again and can't replicate it again. But one of the other lists I use was able to replicate it and removed the domain.

https://github.com/hagezi/dns-blocklists/issues/27

**Comment by ryanbr** [comment]
What address should I type in, to get a legit result for delivery?

**Comment by hagezi** [comment]
@ryanbr 
![grafik](https://user-images.githubusercontent.com/104343908/186153441-1989b6b9-4b42-4bc2-8426-56492032cdeb.png)

**Comment by gyCfjSnO** [comment]
> What address should I type in, to get a legit result for delivery?

If you start typing Sydney it should start bring up results for example.

**Comment by ryanbr** [comment]
> If you start typing Sydney it should start bring up results for example.

Sure, and the results come up. (without touching sentry). Is this expected?
