### ISSUE TITLE
www.healthline.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13054]
### URLs

- `https://www.healthline.com/nutrition/turmeric-and-ginger`

### Description

cookie/privacy notice overlay on first visit

![image](https://user-images.githubusercontent.com/110956608/186297517-db0c8f76-68ea-4265-a8d2-803e2848c887.png)

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44
Firefox: 104
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
we're blocking this already

**Comment by wavygecko** [comment]
@ryanbr this is still showing for me and I have easylist, easyprivacy, and fanboy's annoyances enabled

I was able to block it with `healthline.com##^#consent-modal`
