### ISSUE TITLE
Grey block on https://www.infoplease.com/

### ISSUE THREAD

**Issue by joebagadonuts188** [easylist/easylist#13065]
### List the website(s) you're having issues:

`https://www.infoplease.com/features/chemistry-wine-fermentation`

### What happens?

There is a grey block in the middle of the text. This only appears on mobile versions of the site.

### List Subscriptions you're using:

adguard-spyware-url: 666-13, 1d.10h.13m
curben-phishing: 26833-0, 5m
fanboy-cookiemonster: 36095-100, 1d.10h.12m
easylist: 68555-67, 1d.10h.13m
easyprivacy: 27377-222, 1d.10h.12m
ublock-abuse: 75-1, 1d.10h.12m
ublock-badware: 4222-91, 1d.10h.12m
ublock-filters: 32156-143, 1d.10h.12m
ublock-privacy: 226-3, 1d.10h.12m
ublock-quick-fixes: 206-5, 1d.10h.12m
ublock-unbreak: 1833-47, 1d.10h.12m
urlhaus-1: 5151-1, 1d.10h.12m

### Your settings

- OS/version: Win 10 21H1
- Browser/version: Chrome Version 104.0.5112.81 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

The grey block is id "block-ipmiddlewaread".

**Comment by ryanbr** [comment]
What am I missing?
![infoplz](https://user-images.githubusercontent.com/1659004/186580391-1e62b258-2b4f-497f-8680-28ffc7564acb.png)
