### ISSUE TITLE
www.smithsonianmag.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13067]
### URLs

- `https://www.smithsonianmag.com/smart-news/orcas-are-breaking-rudders-off-boats-in-europe-180980627/`

### Description

ad container

![image](https://user-images.githubusercontent.com/110956608/186452830-77b75ac5-fd63-4701-b7fb-0b4c855ad33d.png)

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44
Firefox: 104
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Looks fine. no "empty space" here.
