### ISSUE TITLE
www.chronicle.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13079]
### URLs

- `https://www.chronicle.com/`

### Description

The filter `/dg/default/rest/*` from EasyPrivacy causes header nav to not load immediately. Adding the following exception fixes it: `@@||c950.chronicle.com/DG/DEFAULT/rest/rpc/*$xhr,1p`

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44
Firefox: 104
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Works for me.
