### ISSUE TITLE
newrepublic.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13071]
### URLs

- `https://newrepublic.com/article/167474/joe-biden-fdr-polls-inflation-reduction-act`

### Description

`.ad-container-house`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110956608/186477716-653d1ecb-f5c3-4dcb-bd2b-3af5c757d460.png">

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44
Firefox: 104
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Self promo, add Annoyances list.
