### ISSUE TITLE
wamba.com

### ISSUE THREAD

**Issue by jmjou** [easylist/easylist#13078]
### List the website(s) you're having issues:

`https://wamba.com/en`

### What happens?

`static.wmbcdn.com/uniweb/js/modern/YandexMetric.client.202208231423.js`
`static.wmbcdn.com/uniweb/js/modern/YandexAds.client.202208231423.js`

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/110184059/186566103-2082acb7-f3c4-40fd-bdbe-94e73d8731b4.png)

</details>

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Tracking Protection, uBO filters

### Your settings

- OS/version: 
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin 1.44.0

### Other details:

**Comment by Yuki2718** [comment]
The change broke the website, now you can't proceed from "Indicate your gender".
