### ISSUE TITLE
www.mcsweeneys.net

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13085]
### URLs

- `https://www.mcsweeneys.net/articles/100-hand-of-blackjack-foxwoods-casino`

### Description

ads: `mcsweeneys.net##aside.house-ad-right`

![image](https://user-images.githubusercontent.com/110956608/186731503-72d79004-4f2e-4f29-971a-a99c9ef1453a.png)

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44
Firefox: 104
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Self promo, in Annoyances.
