### ISSUE TITLE
spiegel.de

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13080]
### URLs

- `https://www.spiegel.de/`

### Description

cookie/privacy overlay can be blocked with: `||sp-spiegel-de.spiegel.de/index.html?message_id=692560$subdocument,1p`

![image](https://user-images.githubusercontent.com/110956608/186570470-3c26fa30-77cf-4c52-a935-4808265aeb0a.png)

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44
Firefox: 104
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by Nojuuu** [comment]
Videos do not load.
