### ISSUE TITLE
www.cnn.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13091]
### URLs

- `https://www.cnn.com/travel/article/miniatur-wunderland-worlds-largest-model-railway-airport/index.html`

### Description

ad at bottom of page

![image](https://user-images.githubusercontent.com/110956608/186792615-20fa9451-0a90-40b0-be1e-847b92c77b22.png)

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44
Firefox: 104
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Not seen. Closing again.
