### ISSUE TITLE
genyt.xyz cookie container

### ISSUE THREAD

**Issue by Luro223** [easylist/easylist#13097]
### URLs
`genyt.xyz`
### Description
Overlay + container
`qc-cmp2-container`
![02](https://user-images.githubusercontent.com/42772886/186902935-764e0308-a3a4-4bb3-9353-8659acc0f6da.png)
### Subscriptions you're using:
EasyList Cookie, Fanboy's Annoyance, Nano filters – Annoyance
### Your settings
- OS/version: Win10 1803
- Browser/version: Chrome 96.0.4900.0
- Adblock Extension/version: Nano Adblocker v1.0.0.153
### Other details:
None

**Comment by ryanbr** [comment]
Redirects to `https://www.genytb.net/?e503` is this the correct url? @Luro223

**Comment by ryanbr** [comment]
Closing, no response @Luro223

**Comment by Luro223** [comment]
@ryanbr Nvm they removed this container from their website
Anyway thanks
