### ISSUE TITLE
nybooks.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13103]
### URLs

- `https://www.nybooks.com/`
- `https://www.nybooks.com/politics/`
- `https://www.nybooks.com/daily/2022/08/24/the-italian-proust-svevo/`
- `https://www.nybooks.com/issues/`

### Description

EasyList blocks `.top-ad-wrapper` but this causes the page to jump down when you scroll past the header.

This can be fixed, while still blocking the ad, by doing this:

```
nybooks.com#@#.top-ad-wrapper
nybooks.com##.ad-spacing
```

https://user-images.githubusercontent.com/110956608/186998053-2776dbe8-0048-4ea9-a652-f786042d93ac.mov

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44
Firefox: 104
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Fine here.
