### ISSUE TITLE
albumoftheyear.org

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13105]
### URLs

- `https://www.albumoftheyear.org/2022/releases/july-07.php`

### Description

ad container

re: https://github.com/uBlockOrigin/uAssets/issues/14470#issuecomment-1222365528

![image](https://user-images.githubusercontent.com/110956608/187012128-e3a2f5a7-a503-4f23-b191-8e737175dca6.png)

### Settings

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.44
Firefox: 104
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Not worth the filter to add it.
