### ISSUE TITLE
breezyswimwear.com

### ISSUE THREAD

**Issue by jmjou** [easylist/easylist#13108]
### List the website(s) you're having issues:

`https://breezyswimwear.com/`

### What happens?

Tracking script

`cdn.shopify.com/s/trekkie.`

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/110184059/187021009-af0833f8-3faa-4bed-ac50-b93c9331a5eb.png)

</details>

---

Tracking server

`trk.storyly.io`

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/110184059/187020993-39c820be-696c-4c07-a554-ca624af94021.png)

</details>

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Tracking Protection, uBO filters

### Your settings

- OS/version: 
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin 1.44.0

### Other details:

**Comment by ryanbr** [comment]
Not a tracker.
