### ISSUE TITLE
cookie-law-info-public.js GPPR script (Wordpress)

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#13127]
### List the website(s) you're having issues:

`apotti.fi`

### What happens?

GDPR script not blocked

### List Subscriptions you're using:

Easylist Cookie

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 104
- Adblock Extension/version: uBO 1.44.1b2

### Other details:

I'm not sure whether a specific or a generic would be a better option.

`/wp-content/plugins/cookie-law-info/public/js/cookie-law-info-public.js` is used pretty widely: https://publicwww.com/websites/%22%2Fwp-content%2Fplugins%2Fcookie-law-info%2Fpublic%2Fjs%2Fcookie-law-info-public.js%22/

Despite it's name, the script doesn't seem to be related to `Onetrust` and `cookielaw.org`. It seems to be a wordpress script. I cannot guarantee it's safe to block this script generally though I don't have a reason to suspect it would cause a lot of issues.

There isn't a specific rule for this script on EL Cookie: https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_specific_block.txt

Edit, at least on this page blocking the same script doesn't cause video issues:

`https://www.openculture.com/2013/05/steven_soderbergh_writes_twitter_novella.html`

Tweets work despite blocking that script:
`https://www.macitynet.it/twitter-lavora-sul-tasto-modifica-in-arrivo-per-twitter-blue/`

Edit2.

Though blocking the script on 180k sites individually might be a huge task so maybe better to try with a generic and whitelist individual domains afterwards if needed?

**Comment by ryanbr** [comment]
Does it break scrolls on pages?

**Comment by peace2000** [comment]
> Does it break scrolls on pages?

No, I checked every domain that were listed at the first page of publicwww search. No issues with scrolling at all.

**Comment by Yuki2718** [comment]
Of note AGA has two exception for this. They're all hidden by `###cookie-law-info-bar` and in some cases by `###cookie-law-info-again` too. Usually blocking this alone doesn't remove cookie dialog but move it to bottom by breaking dialog's layout.

**Comment by ryanbr** [comment]
Found ###cookie-law-info-bar would break on some sites @Yuki2718  (scroll breaks)

**Comment by Yuki2718** [comment]
Oh, okay. In that case the rule seems to be useful - the leftover moved to bottom are still hidden by `###cookie-law-info-again`.

**Comment by peace2000** [comment]
But blocking the script also prevents those broken banners from appearing?

**Comment by Yuki2718** [comment]
Yes, apparently no problem as long as `###cookie-law-info-again` is there.
