### ISSUE TITLE
bluesnews.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13134]
### URLs

- `https://www.bluesnews.com/s/251417/10-chambers-planning-co-op-heist-fps`
- `https://www.bluesnews.com/cgi-bin/board.pl?action=viewthread&boardid=1&threadid=251246`

### Description

ad containers

![image](https://user-images.githubusercontent.com/110956608/187104086-de636db6-f65b-4a66-adcf-54a8210eb9cf.png)

![image](https://user-images.githubusercontent.com/110956608/187104063-9c335371-ee86-49ca-bfc1-cdf6bffee540.png)

![image](https://user-images.githubusercontent.com/110956608/187104350-1608f666-73ae-4892-a8d6-991d533d5232.png)

### Settings

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 104.0
listset:
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8a6733fa54645fc83e70659c06a26d92c48579ff
