### ISSUE TITLE
theguardian.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#13139]
### List the website(s) you're having issues:
https://www.theguardian.com/international

### What happens?

Cookie Notice
### List Subscriptions you're using:

Default uBO, EasyList Cookie
### Your settings

 
- OS/version: Windows 11
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin 1.44.0

### Other details:

![image](https://user-images.githubusercontent.com/29574622/187255571-6665d7e7-fbf9-48d2-9df4-9474cab23670.png)

**Comment by ryanbr** [comment]
See https://github.com/easylist/easylist/blob/master/easylist_cookie/README.md
