### ISSUE TITLE
Ads sometimes are blocked but another windows/tabs are opened even if the ads arent displayed

### ISSUE THREAD

**Issue by Felipefpl** [easylist/easylist#13136]
Hi, i' using waterfox and ublock and i'm having the problem described in the title with this site https://www.hinatasoul.com/ - click anywhere in the site and the ads are opened, sometimes the ads display something and sometimes the ad blocker shows an window saying the ad was blocked by easylist.

**Comment by ryanbr** [comment]
```
Access denied Error code 1020
You cannot access www.hinatasoul.com. Refresh the page or contact the site owner to request access.
```

Which country should I VPN from to test from? Seems tthey're blocking access.

**Comment by Felipefpl** [comment]
It's brazil, it's a site with anime with brazilian portuguese subtitles. Strange it blocks you since i didnt ever see something like this.
