### ISSUE TITLE
google restaurant ad not blocked

### ISSUE THREAD

**Issue by theel0ja** [easylist/easylist#1314]
### List the website(s) you're having issues:
`https://www.google.com/search?q=ravintolat%20turku&ie=utf-8&oe=utf-8&client=firefox-b-ab&npsic=0&rflfq=1&rlha=0&rllag=60450229,22265016,595&tbm=lcl&rldimm=12303979716691805122&ved=0ahUKEwiej8vs0MbbAhXiDpoKHZZQAsQQvS4IqgEwAw&rldoc=1&tbs=lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9#rlfi=hd:;si:12303979716691805122;mv:!1m3!1d19996.910661060367!2d22.25197205!3d60.463219699999996!2m3!1f0!2f0!3f0!3m2!1i181!2i122!4f13.1;tbs:lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9`

### What happens?
ad not blocked

### List Subscriptions you're using:
easylist

### Your settings

- OS/version: firefox 60
- Browser/version: windows 10
- Adblock Extension/version: ublock origin

### Other details:
![image](https://user-images.githubusercontent.com/5832930/41191923-37ef649c-6bff-11e8-8895-693751a98578.png)

**Comment by theel0ja** [comment]
@krystian3w Or the ad is targeted to certain countries?

**Comment by theel0ja** [comment]
Try to resubmit the search

**Comment by krystian3w** [comment]
OK, when resumbit I have ads.
