### ISSUE TITLE
marketsmojo.com

### ISSUE THREAD

**Issue by mediumkreation** [easylist/easylist#1315]
### Request Type
 [x] Filter Addition
 [ ] Issue report

### List the website(s) you're having issues:

`https://www.marketsmojo.com/Stocks?StockId=141783&Exchange=0#!#navDashboard`

### What happens?

![marketsmojo com_18-05-06 19 44 12](https://user-images.githubusercontent.com/39060814/41192868-8125fa68-6c22-11e8-816a-1542a93926b3.png)

### List Subscriptions you're using:
[x] EasyList

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Suggested Filter
```
marketsmojo.com###cl-banner-logo
```

**Comment by ryanbr** [comment]
Should use Easylist issues report for Easylist specific filters.
