### ISSUE TITLE
FB Annoyance breaks logitechg.com

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#13158]
### List the website(s) you're having issues:

`https://www.logitechg.com/en-us/products/gaming-mice/g502-x-plus-wireless-lightforce.910-006160.html`

### What happens?

Right side of the page doesn't load, and you can't click on the product thumbnails.

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox
- Adblock Extension/version: uBO

### Other details:

![Screenshot 2022-08-31 222937](https://user-images.githubusercontent.com/11689349/187819646-dc582811-5c52-478b-94e3-4941f4badd8a.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f4d759c775603f4ff7c06ea602ffcf43383ac7bb
