### ISSUE TITLE
moovitapp.com annoyance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#13161]
### List the website(s) you're having issues:
https://moovitapp.com/

### What happens?
Prompt for downloading mobile app

### Your settings
All filters offered by uBlock Origin

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 104.0.1
- Adblock Extension/version: uBlock Origin 1.44.0

### Other details:
Screenshot:
![Screenshot 2022-09-01 at 07-23-17 Moovit Παγκόσμια Εφαρμογή Πραγματικού Χρόνου για τις Δημόσιες Συγκοινωνίες](https://user-images.githubusercontent.com/101707608/187831557-36af6917-7c8f-4749-83b6-476b81d729a4.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a966fb52df284c17c0466f161d5f6608f30b2895
