### ISSUE TITLE
gov.gr cookie warning

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#13174]
### List the website(s) you're having issues:
https://ehealth.gov.gr/p-rv/p

### What happens?
Full screen cookie warning

### List Subscriptions you're using:
All filters offered by uBlock Origin

### Your settings

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 104.0.1
- Adblock Extension/version: uBlock Origin 1.44.0

### Other details:
Screenshot:
![Screenshot 2022-09-02 at 09-27-34 p-rv](https://user-images.githubusercontent.com/101707608/188074114-7ad40d63-eaae-452c-8f91-4ec99746945c.png)

**Comment by ryanbr** [comment]
Suggested filter? unable to load site @DimitrisKalaboukas

**Comment by DimitrisKalaboukas** [comment]
I wasn’t able to create an efficient filter without page breakage. Because indeed this site isn’t accessible outside of Greece, you can find a full copy of it here: https://bit.ly/3Bc5z7g

**Comment by DimitrisKalaboukas** [comment]
@ryanbr did you managed to display the cookie warning in the saved html page that I provided above? The zip archive should be unpacked for the page to load properly.

**Comment by DimitrisKalaboukas** [comment]
@ryanbr the following filters block the message properly:

ehealth.gov.gr###prvp-3449916-overlays > div.v-window-modalitycurtain
ehealth.gov.gr###prvp-3449916-overlays > div.v-window.v-widget.v-readonly.v-has-width.v-has-height:nth-child(2)

**Comment by ryanbr** [comment]
```
ehealth.gov.gr##.v-window-modalitycurtain
ehealth.gov.gr##.v-has-height.v-readonly.v-widget
ehealth.gov.gr##body,html:style(overflow: auto !important; position: initial !important;)
```

Does that work? @DimitrisKalaboukas

**Comment by DimitrisKalaboukas** [comment]
@ryanbr No, they break the page. The filters that I mentioned above work fine:

ehealth.gov.gr##div.v-window-modalitycurtain
ehealth.gov.gr##div.v-window.v-widget.v-readonly.v-has-width.v-has-height:nth-child(2)
ehealth.gov.gr##body,html:style(overflow: auto !important; position: initial !important;)

**Comment by peace2000** [comment]
`ehealth.gov.gr##+js(set-cookie, cookieconsent_status, 1)`

This fixes the dialog safely. @DimitrisKalaboukas That filter works in the current dev build of uBO, will work at stable release later.

Translation of the dialog via Google:

<details>
https://translate.google.com/?sl=auto&tl=en&text=%CE%93%CE%B9%CE%B1%20%CF%84%CE%B7%CE%BD%20%CE%B1%CE%BB%CE%BB%CE%B7%CE%BB%CE%B5%CF%80%CE%AF%CE%B4%CF%81%CE%B1%CF%83%CE%B7%20%CE%BC%CE%B5%20%CF%84%CE%BF%CE%BD%20%CE%B9%CF%83%CF%84%CF%8C%CF%84%CE%BF%CF%80%CE%BF%20%CF%87%CF%81%CE%B7%CF%83%CE%B9%CE%BC%CE%BF%CF%80%CE%BF%CE%B9%CE%BF%CF%8D%CE%BD%CF%84%CE%B1%CE%B9%20cookies%20%CF%80%CE%BF%CF%85%20%CE%B1%CE%BD%CE%AE%CE%BA%CE%BF%CF%85%CE%BD%20%CE%B1%CF%80%CE%BF%CE%BA%CE%BB%CE%B5%CE%B9%CF%83%CF%84%CE%B9%CE%BA%CE%AC%20%CF%83%CF%84%CE%B9%CF%82%20%CE%BA%CE%B1%CF%84%CE%B7%CE%B3%CE%BF%CF%81%CE%AF%CE%B5%CF%82%20%CF%84%CF%89%CE%BD%20%CE%92%CE%B1%CF%83%CE%B9%CE%BA%CF%8E%CE%BD%20%CE%BA%CE%B1%CE%B9%20%CE%9B%CE%B5%CE%B9%CF%84%CE%BF%CF%85%CF%81%CE%B3%CE%B9%CE%BA%CF%8E%CE%BD%20cookies%2C%20%CF%84%CE%B1%20%CE%BF%CF%80%CE%BF%CE%AF%CE%B1%20%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9%20%CE%B1%CE%BD%CE%B1%CE%B3%CE%BA%CE%B1%CE%AF%CE%B1%20%CF%83%CF%84%CE%BF%20%CF%83%CF%8D%CE%BD%CE%BF%CE%BB%CF%8C%20%CF%84%CE%BF%CF%85%CF%82%20%CE%B3%CE%B9%CE%B1%20%CF%84%CE%B7%CE%BD%20%CE%BF%CF%81%CE%B8%CE%AE%20%CE%BB%CE%B5%CE%B9%CF%84%CE%BF%CF%85%CF%81%CE%B3%CE%AF%CE%B1%20%CF%84%CF%89%CE%BD%20%CF%80%CE%B1%CF%81%CE%B5%CF%87%CF%8C%CE%BC%CE%B5%CE%BD%CF%89%CE%BD%20%CF%85%CF%80%CE%B7%CF%81%CE%B5%CF%83%CE%B9%CF%8E%CE%BD%20%CE%BA%CE%B1%CE%B9%20%CF%84%CE%B7%CE%BD%20%CE%B1%CF%80%CF%81%CF%8C%CF%83%CE%BA%CE%BF%CF%80%CF%84%CE%B7%20%CF%80%CE%BB%CE%BF%CE%AE%CE%B3%CE%B7%CF%83%CE%AE%20%CF%83%CE%B1%CF%82.%20%CE%93%CE%B9%CE%B1%20%CF%80%CE%BB%CE%B7%CF%81%CE%BF%CF%86%CE%BF%CF%81%CE%AF%CE%B5%CF%82%20%CF%83%CF%87%CE%B5%CF%84%CE%B9%CE%BA%CE%AC%20%CE%BC%CE%B5%20%CF%84%CE%B1%20cookies%20%CE%BA%CE%B1%CE%B9%20%CF%83%CF%85%CE%BD%CE%B1%CF%86%CE%B5%CE%AF%CF%82%20%CF%81%CF%85%CE%B8%CE%BC%CE%AF%CF%83%CE%B5%CE%B9%CF%82%2C%20%CF%83%CF%85%CE%BC%CE%B2%CE%BF%CF%85%CE%BB%CE%B5%CF%85%CF%84%CE%B5%CE%AF%CF%84%CE%B5%20%CF%84%CE%B7%CE%BD%20%CE%A0%CE%BF%CE%BB%CE%B9%CF%84%CE%B9%CE%BA%CE%AE%20Cookies%2C%20%CE%BB%CE%B1%CE%BC%CE%B2%CE%AC%CE%BD%CE%BF%CE%BD%CF%84%CE%B1%CF%82%20%CF%85%CF%80%CF%8C%CF%88%CE%B7%20%CF%8C%CF%84%CE%B9%20%CF%84%CF%85%CF%87%CF%8C%CE%BD%20%CE%B1%CF%80%CE%B5%CE%BD%CE%B5%CF%81%CE%B3%CE%BF%CF%80%CE%BF%CE%AF%CE%B7%CF%83%CE%AE%20%CF%84%CE%BF%CF%85%CF%82%20%CE%B8%CE%B1%20%CE%BA%CE%B1%CE%B8%CE%B9%CF%83%CF%84%CE%AC%20%CF%84%CE%BF%CE%BD%20%CE%B9%CF%83%CF%84%CF%8C%CF%84%CE%BF%CF%80%CE%BF%20%CE%BC%CE%B7%20%CE%BB%CE%B5%CE%B9%CF%84%CE%BF%CF%85%CF%81%CE%B3%CE%B9%CE%BA%CF%8C%20%CE%BA%CE%B1%CE%B9%20%CE%B1%CF%80%CE%BF%CE%B4%CE%BF%CF%84%CE%B9%CE%BA%CF%8C.%20%CE%93%CE%B9%CE%B1%20%CF%80%CE%BB%CE%B7%CF%81%CE%BF%CF%86%CE%BF%CF%81%CE%AF%CE%B5%CF%82%20%CF%83%CE%B5%20%CF%83%CF%87%CE%AD%CF%83%CE%B7%20%CE%BC%CE%B5%20%CF%84%CE%B1%20%CF%80%CF%81%CE%BF%CF%83%CF%89%CF%80%CE%B9%CE%BA%CE%AC%20%CF%83%CE%B1%CF%82%20%CE%B4%CE%B5%CE%B4%CE%BF%CE%BC%CE%AD%CE%BD%CE%B1%20%CE%B1%CE%BD%CE%B1%CF%84%CF%81%CE%AD%CE%BE%CF%84%CE%B5%20%CF%83%CF%84%CE%B7%CE%BD%20%CE%A0%CE%BF%CE%BB%CE%B9%CF%84%CE%B9%CE%BA%CE%AE%20%CE%A0%CF%81%CE%BF%CF%83%CF%84%CE%B1%CF%83%CE%AF%CE%B1%CF%82%20%CE%94%CE%B5%CE%B4%CE%BF%CE%BC%CE%AD%CE%BD%CF%89%CE%BD%20%CE%A0%CF%81%CE%BF%CF%83%CF%89%CF%80%CE%B9%CE%BA%CE%BF%CF%8D%20%CE%A7%CE%B1%CF%81%CE%B1%CE%BA%CF%84%CE%AE%CF%81%CE%B1.&op=translate
<details>

**Comment by peace2000** [comment]
The proxy I used to access that site stopped to work after I crafted that filter :)
