### ISSUE TITLE
/advert-$domain=~advert-solutions.com

### ISSUE THREAD

**Issue by MiraYHakansson** [easylist/easylist#13217]
### What happens?
Requests are blocked due to parts of the url, probably due to the domain.  `/advert-customfields/`

### List Subscriptions you're using:
free adBlock 

All ad blocking filter lists.

### Your settings

- OS/version: wn10
- Browser/version: chrome latest
- Adblock Extension/version:  adblock 5.1.1

### Other details:

This filter `/advert-$domain=~advert-ai-landing.firebaseapp.com|~advert-ai-landing.web.app|~advert-ai.com|~advert-solutions.com|~advert-technology.com|~advert-technology.ru` block requests.

**Comment by Khrin** [comment]
On which site? @MiraYHakansson

**Comment by MiraYHakansson** [comment]
Hi, thanks for the quick response. It blocks all sites, ex: example.com

**Comment by ryanbr** [comment]
Not really an answer @MiraYHakansson   See the form. we want a workable site. Otherwise we'll close this ticket.

**Comment by MiraYHakansson** [comment]
Those domains with `advert-` are blocked for us by the filter I mentioned

**Comment by ryanbr** [comment]
Closing, not fixing. rename your folder directorys.
