### ISSUE TITLE
https://www.publishedreporter.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#13244]
### List the website(s) you're having issues:
https://www.publishedreporter.com/

### What happens?
Content seems to be blocked

### List Subscriptions you're using:
EL EL

### Other details:
<img width="1408" alt="Screenshot 2022-09-08 at 11 01 51" src="https://user-images.githubusercontent.com/65717387/189081537-6eed29ed-f548-4a27-ab34-7cf27d108850.png">

**Comment by ryanbr** [comment]
It was the best filter for the job, I was aware of it.
