### ISSUE TITLE
https://www.dexerto.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#13243]
### List the website(s) you're having issues:
https://www.dexerto.com/

### What happens?
Seems to be blocking articles (content at the top)

### List Subscriptions you're using:

EL EL

### Other details:
<img width="1510" alt="Screenshot 2022-09-08 at 10 28 08" src="https://user-images.githubusercontent.com/65717387/189075837-43b11f85-f321-49a6-ae2f-58ac379b84b7.png">

**Comment by ryanbr** [comment]
Whats being blocked here, I'm not seeing any issue? @felippesantos46

**Comment by felippesantos46** [comment]
@ryanbr 

With EL enabled:
<img width="1505" alt="Screenshot 2022-09-09 at 18 59 37" src="https://user-images.githubusercontent.com/65717387/189403298-8e551e96-47f7-4b4b-92fb-93117f7fbe45.png">

With EL disabled(Those 4 content banners are being blocked for me):
<img width="1512" alt="Screenshot 2022-09-09 at 19 00 22" src="https://user-images.githubusercontent.com/65717387/189403342-80d99b44-0052-4edc-bb3f-8a4b0b3bbddb.png">

**Comment by Nojuuu** [comment]
@ryanbr 

`dexerto.com##.bg-neutral-grey-4` is causing issues.

Also hides search box etc.

![image](https://user-images.githubusercontent.com/84513173/189497764-e8bcb1e5-014a-4d8a-95f7-6e6bf2f678a9.png)
