### ISSUE TITLE
yts.mx

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#13276]
### List the website(s) you're having issues:
`https://yts.mx/`

### What happens?
Advertisement

### List Subscriptions you're using:

Default uBO, EasyList, EasyPrivacy, Fanboy's Annoyances, Anti-Facebook
### Your settings

- OS/version: Windows 11
- Browser/version: Firefox latest
- Adblock Extension/version: uBlock Origin 1.44.2

### Other details:
![1](https://user-images.githubusercontent.com/29574622/189324119-2f96e0df-b311-4f3f-b7d6-fb375f37a314.png)

**Comment by ryanbr** [comment]
They change so often, on so many pirate sites and then the hundreds of mirrors of pirate sites. I generally avoid them. Would require to hire someone full time to monitor all these.
