### ISSUE TITLE
youtube.com annoying miniplayer widget

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#13275]
### List the website(s) you're having issues:
https://www.youtube.com/playlist?list=PLRs8fqjYD5ILPavP0bC3-xH0i0tDnEYzu

### What happens?
I’m trying to create an effective custom filter to block the miniplayer widget that annoys me by popping up on the right every time I go back from a youtube video to the corresponding playlist, but I haven’t managed to do so. Could anyone help? I’m aware that this annoyance may not bother every user.

### List Subscriptions you're using:
All filters offered by uBlock Origin.

### Your settings

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 104.0.2
- Adblock Extension/version: uBlock Origin 1.44.2

### Other details:
Screenshot:
![Screenshot 2022-09-09 at 10-26-56 The PC Security Channel](https://user-images.githubusercontent.com/101707608/189297532-f436b90a-7ae4-4914-906d-8d0e7eb0a86e.png)

**Comment by THEtomaso** [comment]
Yeah, I've been trying to get rid of this major annoyance myself, for quite some time now!
It can't be blocked with a simple element hiding rule, of course, since the audio will still play in the backround.
Doesn't seem that anyone has been able to come up with a decent solution for this yet.

@lassekongo83:
What do you think..
Can it be done in uBO, with some type of `##+js` rule?

**Comment by lassekongo83** [comment]
This works for me.

```
youtube.com##:matches-path(/^/$/) ytd-miniplayer:remove()
youtube.com##:matches-path(/^/$/) #movie_player video:remove()
youtube.com##:matches-path(/playlist) ytd-miniplayer:remove()
youtube.com##:matches-path(/playlist) #movie_player video:remove()
```

Might want to add a matches-path rule to any path that is not `/watch`. `:not(matches-path(/watch))` won't work. I've tried various regex rules to negate `/watch`  but can't find any that works.

**Comment by THEtomaso** [comment]
Great!
Thanks for looking into this, lk83!! 👍

**Comment by THEtomaso** [comment]
@DandelionSprout:
You might also want to add lk83's rules to one of your YouTube filters.

**Comment by DandelionSprout** [comment]
I'll see if I can take care of it tomorrow.

**Comment by DimitrisKalaboukas** [comment]
@lassekongo83 awesome, these rules seem to work fine! Could you, please, create some corresponding rules for YouTube Music, as the same issue occurs there too?

**Comment by DimitrisKalaboukas** [comment]
@lassekongo83 the problem with this filter is that it removes the video portion completely even when playing in full screen mode.

**Comment by krystian3w** [comment]
Also how reproduce miniplayer in `/watch`?

**Comment by DandelionSprout** [comment]
I must admit that I forgot this thread for some days, mostly because `:matches-path` is something I have no real experience with, and is also something I didn't even know existed. 😅 

However, as there seems to be general agreement about the first two entries working for standard YouTube on PC, I'll finally add them to *Dandelion Sprout's Annoyances List* a bit beyond schedule.

**Comment by DandelionSprout** [comment]
Fairly major update:

Are any of you guys also struggling with embedded videos going blank with the new entries, e.g. by posting `https://www.youtube.com/watch?v=aCyGvGEtOwc` on Discord? Because I certainly am.

**Comment by THEtomaso** [comment]
Damn, you're right!
Embedded videos does indeed go blank (black screen). :(

@lassekongo83:
Further tweaks possible?

**Comment by lassekongo83** [comment]
How about his?

```
youtube.com##:not(:matches-path(/watch)):not(:matches-path(/embed)) ytd-miniplayer:remove()
youtube.com##:not(:matches-path(/watch)):not(:matches-path(/embed)) #movie_player video:remove()
```

**Comment by THEtomaso** [comment]
Wow, that was fast!

Works for me!! :)

**Comment by krystian3w** [comment]
Hide too button on bottom in player due filter break use his.

**Comment by krystian3w** [comment]
Hide too button on bottom in player due filter break use his.

![IMG_20220917_194145](https://user-images.githubusercontent.com/35370833/190869677-61c89b0e-44e1-4d6e-9104-722473e148bf.jpg)

**Comment by THEtomaso** [comment]
Oh.
I'm already hiding that Miniplayer button on purpose.
Don't see lk83's rules breaking them at my end.

**Comment by DimitrisKalaboukas** [comment]
@DandelionSprout please update your filters as follows in order to solve all mentioned problems:

`youtube.com##:not(:matches-path(/watch)):not(:matches-path(/embed)) #movie_player video:remove()`
`youtube.com##:not(:matches-path(/watch)):not(:matches-path(/embed)) ytd-miniplayer:remove()`
`youtube.com##.ytp-miniplayer-button`

**Comment by DandelionSprout** [comment]
Okay, I guess I can try out adding those entries now.

**Comment by krystian3w** [comment]
Maybe `[has-playlist-data]` can repair normal button and no need use `matches-path`.

**Comment by DimitrisKalaboukas** [comment]
@DandelionSprout it seems like the above solution proposed by krystian3w works better.

**Comment by krystian3w** [comment]
The difference is more likely to be seen on weak computers or those with 99% RAM/CPU in use.

It would be cool to see how Discord reacts to embedded videos and playlists with vanilla CSS (remove is only to stop audio and bandwidth limit.

**Comment by DimitrisKalaboukas** [comment]
@krystian3w could you, please, create a corresponding filter for blocking miniplayer on YouTube Music without breaking the video on normal playback?

**Comment by krystian3w** [comment]
So far no, I rarely use the 'music' version.

**Comment by DandelionSprout** [comment]
Thanks for the headsup from both of you. I'll make use of those entries real quick.

**Comment by THEtomaso** [comment]
> ```
> youtube.com##ytd-miniplayer[has-playlist-data] #movie_player video:remove()
> youtube.com##ytd-miniplayer[has-playlist-data][active]
> youtube.com##ytd-miniplayer[has-playlist-data][closed] ~ * .ytp-miniplayer-button
> ```

Great, This also works for uBO Legacy!
Thanks, krystian3w! 👍

**Comment by DimitrisKalaboukas** [comment]
@krystian3w The filter:

music.youtube.com###player[player-ui-state_="MINIPLAYER"]

no longer works. Could you, please, provide me with an updated version?

**Comment by krystian3w** [comment]
Currently, I do not associate, I gave up on hiding it in the video service (the filter began to work incorrectly) and music practically I do not open.

---

You can quickly check whether only the capitalization of the letters has changed:

```adb
music.youtube.com###player[player-ui-state_="MINIPLAYER" i]
!
music.youtube.com###player[player-ui-state_*="MINI" i][player-ui-state_*="PLAYER" i]
```

**Comment by DimitrisKalaboukas** [comment]
@DandelionSprout @krystian3w The filters for YouTube miniplayer need adjustment.

**Comment by krystian3w** [comment]
I decided not to use a "raw" CSS/CSS4 compatible filter in Polish Annoyance Filters anymore (for about a year ago).

Perhaps it is still possible to avoid using procedural/ExtCss filters (I'm the only one who doesn't feel inspired to keep up with Google anymore for PiP).

Maybe the Swedish project is still maintaining the filter, including abandoning CSS compatibility in favor of procedural filters.

**Comment by DimitrisKalaboukas** [comment]
@DandelionSprout It seems that the filters mentioned [above](https://github.com/easylist/easylist/issues/13275#issuecomment-1250768722) are still working fine (at least on uBO).
