### ISSUE TITLE
syoss.net

### ISSUE THREAD

**Issue by jmjou** [easylist/easylist#13273]
### List the website(s) you're having issues:

`https://www.syoss.net/hair-style/product/all-hairsprays/syoss-pure-hold-hairspray.html`

### What happens?

Tracking

`liveux.netcentric.biz/collector`

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/110184059/189266419-43fbcf04-1ebc-4c32-8595-dbc612bc3d3f.png)

</details>

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Tracking Protection, uBO filters

### Your settings

- OS/version: 
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin 1.44.2

### Other details:

**Comment by CDaxi** [comment]
The change done at this issue blocks a whole company website.
To block only the topic of this issue, the specific domain liveux.netcentric.biz should be used.
