### ISSUE TITLE
Ads' spaces arent removed

### ISSUE THREAD

**Issue by Felipefpl** [easylist/easylist#13285]
Hi, i'm using ublock with easylist/easyprivacy and the ads' spaces named "publicidade" (advertising in english) arent removed (but the ads luckly are blocked). I dont use any other blocking extensions. Those ads' spaces can be located in several places on the page.

https://noticias.r7.com/economia/pela-1-vez-na-historia-tempo-medio-de-abertura-de-empresa-fica-abaixo-de-um-dia-diz-secretario-09092022

**Comment by Nojuuu** [comment]
Try enabling `spa, por: AdGuard Spanish/Portuguese` in `Dashboard > Filter lists > Regions, languages`.

Also make sure you haven't accidentally enabled "Ignore generic cosmetic filters".

**Comment by Felipefpl** [comment]
I did as you suggested and the ads' spaces are still there.

**Comment by Nojuuu** [comment]
Hmm... for me EasyList and Spanish/Portuguese list removes all ads.

**Comment by Felipefpl** [comment]
Strange indeed, i even purged the cache and updated the lists and even so it didnt work.

**Comment by Khrin** [comment]
Definitely not an issue with EasyList.
