### ISSUE TITLE
thespruceeats.com: problematic

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13294]
### URLs

- `https://www.thespruceeats.com/spinach-hummus-2355483`

### Description

problematic: scroll down page, page turns blank and becomes unusable

### Settings

<details>

```yaml
uBlock Origin: 1.44
Firefox: 104.0
listset:
  custom:
    adfilt/LegitimateURLShortener
    adfilt/StopAutoplayOnYouTube
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-annoyance
    ublock-annoyances
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Looks fine here, you need to debug more

**Comment by wavygecko** [comment]
@ryanbr I disabled all lists except for EasyList. It appears that it is EasyList that is causing it.


https://user-images.githubusercontent.com/110956608/189534822-177c4605-fd35-40e0-b8e3-0e3056e7af7d.mov

**Comment by wavygecko** [comment]
More specifically it appears to be this filter that causes the issue:

`##[data-ad-width]`

**Comment by wavygecko** [comment]
& only in firefox

**Comment by wavygecko** [comment]
these filters fix the problem:

```
thespruceeats.com#@#[data-ad-width]
thespruceeats.com##.mntl-leaderboard-spacer
```

**Comment by wavygecko** [comment]
related discussion: https://github.com/uBlockOrigin/uAssets/discussions/14823

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/419e378e4367cadec468b31811e03aedc3334af8
