### ISSUE TITLE
Cookie warning on https://www.carawayhome.com/

### ISSUE THREAD

**Issue by joebagadonuts188** [easylist/easylist#13295]
### List the website(s) you're having issues:

`https://www.carawayhome.com/`

### What happens?

Cookie warning banner at the bottom of the page.

### List Subscriptions you're using:

easylist: 64281-72, now
easyprivacy: 30556-1270, now
ublock-abuse: 76-1, now
ublock-badware: 4232-100, now
ublock-filters: 32636-170, now
ublock-privacy: 251-1, now
ublock-quick-fixes: 403-2, now
ublock-unbreak: 1852-43, now
urlhaus-1: 7634-2, now

### Your settings

- OS/version: Win 10 21H1
- Browser/version: Chrome Version 104.0.5112.81 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.43.0

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e8729148fa883ff15df4f99141be86702f4be878
