### ISSUE TITLE
epicurious.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13293]
### URLs

- `https://www.epicurious.com/expert-advice/all-the-berries-ranked-strawberry-blueberry-blackberry-raspberry-gallery`

### Description

sticky banner

![image](https://user-images.githubusercontent.com/110956608/189500983-b6779bc0-999f-4b1d-ab1a-ff593fd275c1.png)

### Settings

<details>

```yaml
uBlock Origin: 1.44
Firefox: 104.0
listset:
  custom:
    adfilt/LegitimateURLShortener
    adfilt/StopAutoplayOnYouTube
  added:
    adguard-spyware-url
    block-lan
    curben-phishing
    curben-pup
    fanboy-annoyance
    ublock-annoyances
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
fine here
