### ISSUE TITLE
Your list is blocking legitimate content on this website

### ISSUE THREAD

**Issue by invalidtask** [easylist/easylist#13306]
### List the website(s) you're having issues:

`https://vaughn.live`

### What happens?
Prevents video player debug info and upcoming layout changes

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome
- Adblock Extension/version: AdblockPlus

### Other details:
The specific rule causing problems is:

`vaughn.live##[class^="vs_v9_"]`

https://github.com/easylist/easylist/blob/a4575412222c86afdfcfae3c38f4dbcca128520b/easylist/easylist_specific_hide.txt#L3182

**Comment by ryanbr** [comment]
Force an update
