### ISSUE TITLE
Ads appearing on Infinix/Tecno devices

### ISSUE THREAD

**Issue by CassiusBETA** [easylist/easylist#13305]
### List the website(s) you're having issues:
apitm.toolmatrix.plus
msg.transacme.com
restart-api.palmplaystore.com
apitm.toolmatrix.plus
api.eagllwin.com
app.transacme.com
mars.gamegamb.com
bizscene.palmplaystore.com
data-api.geniex.com
api.ahagamecenter.com

### What happens?
Ads appearing on Infinix/Tecno devices

### List Subscriptions you're using:
EasyList and EasyPrivacy

### Your settings

- OS/version: Android 11
- Browser/version: Brave Beta 1.44.79
- Adblock Extension/version: NextDNS

### Other details:
![Screenshot_20220911-165410](https://user-images.githubusercontent.com/109208335/189519874-da465f35-de12-44eb-987f-4f936c8e85d9.jpg)
![Screenshot_20220911-165425](https://user-images.githubusercontent.com/109208335/189519880-6c7c37b4-78c8-4491-8764-24ee598b3d6f.jpg)

**Comment by ryanbr** [comment]
Can't reproduce this.
