### ISSUE TITLE
Clickadu.com

### ISSUE THREAD

**Issue by DanClickadu** [easylist/easylist#13315]
Want to report about incorrectly removed content
clickadu.com is a Clickadu s.r.o. company website and doesn't associate with any ads.
The website is using a modal window for social networks, cookie policy, and OneClick push subscription

### List the website(s) you're having issues:
clickadu.com 

### What happens?
My website has problems with the content display with Adblock on 
![image](https://user-images.githubusercontent.com/113350912/189641931-9f88d04d-af3c-41aa-8a62-0d6c4928c1a5.png)

### List Subscriptions you're using:
https://getadblock.com/en/

### Your settings

- OS/version: Windows 10 х64 
- Browser/version: G Chrome 105.0.5195.102
- Adblock Extension/version: https://getadblock.com/en/

**Comment by ryanbr** [comment]
Expected. The service is used for revolving adservers.  Won't be removed.

**Comment by DanClickadu** [comment]
That's a simple company description. What this has to do with ad-blockers?
clickadu.com is a company website and doesn't involve in any advertising
opportunities.
