### ISSUE TITLE
https://www.heavenhr.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#13312]
### List the website(s) you're having issues:
https://www.heavenhr.com/

### What happens?
Cookies consents being blocked in EL EL, shouldn't it be moved to Cookies lists ? 
Commit reference - https://github.com/easylist/easylist/commit/fe74638d97dcc0e3fac99f4f8048efbe65a7526e

### List Subscriptions you're using:
EL

### Other details:
<img width="1511" alt="Screenshot 2022-09-12 at 09 47 57" src="https://user-images.githubusercontent.com/65717387/189600250-1f3704f4-0282-4b09-b91c-b26a1a08315f.png">

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2b49b9e6ec69b932c3f4194ac37365e0062e6677
