### ISSUE TITLE
uploadydl.com

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#13326]
### List the website(s) you're having issues:

`https://uploadydl.com/uj620o7c4996`

### What happens?

fake buttons

<details>
<summary>Screen</summary>

![2022-09-12_204334](https://user-images.githubusercontent.com/111344219/189721108-8710f823-9f33-4c61-9723-bfd14c9557f3.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 21H2 x64
- Browser/version:  Google Chrome 105.0.5195.102
- Adblock Extension/version:  uBO 1.44.2

**Comment by ryanbr** [comment]
Force an update of the lists

**Comment by dportvine** [comment]
fake buttons are still here
<details>
<summary>Screen</summary>

![2022-09-13_122753](https://user-images.githubusercontent.com/111344219/189866256-188c6a15-d913-4352-b1ef-4be5d28aaec0.png)
</details>
