### ISSUE TITLE
imobiliare.ro - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#13346]
### List the website(s) you're having issues:

- `https://www.imobiliare.ro/`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 105
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/190147728-8af25eaa-50b3-4563-a301-4e7090416cca.png">

**Comment by ryanbr** [comment]
Can't be blocked in ABP due to scrollbar
