### ISSUE TITLE
birkenstock.com - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#13344]
### List the website(s) you're having issues:

- `https://www.birkenstock.com/de?Country=DE&Language=de`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 105
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/190145818-f970f23c-8bdb-4bda-9316-b392912e94c5.png">

**Comment by ryanbr** [comment]
Can't be blocked in ABP, due to scrollbar
