### ISSUE TITLE
bloomberg.com - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#13345]
### List the website(s) you're having issues:

- `https://www.bloomberg.com/europe`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 105
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/190146208-2d0e6e6a-2c86-4119-bb26-eabb651b8369.png">

**Comment by ryanbr** [comment]
Couldn't be blocked in ABP due to scrollbar issues.
