### ISSUE TITLE
teufel.de - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#13343]
### List the website(s) you're having issues:

- `https://teufel.de/`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 105
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/190145531-a34ff2a7-8928-43e4-a91f-76b953dde0c0.png">

**Comment by ryanbr** [comment]
Can't be blocked in ABP due to scrollbar
