### ISSUE TITLE
etsy.com - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#13341]
### List the website(s) you're having issues:

- `https://www.etsy.com/`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 105
Adblock Extension/version: AdblockPlus

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/2988929/190144893-49a47260-6621-48cb-9e87-2c054285c2a2.png">

**Comment by ryanbr** [comment]
Can't be blocked properly in ABP due to scrollbar.
