### ISSUE TITLE
logz.io

### ISSUE THREAD

**Issue by SimplesmenteMaria** [easylist/easylist#13350]
`logz.io`/`logz-data.com` are not blocked, while `bugsnag.com` is.

### List the website(s) you're having issues:

`https://www.ifood.com.br/`

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10
- Browser/version: uBlock Origin
- Adblock Extension/version: 1.44.2

**Comment by ryanbr** [comment]
Need another example site, the site isn't reachable. @SimplesmenteMaria

**Comment by sugarfreesweetener** [comment]
@ryanbr encountered with Brazil IP address:
![image](https://user-images.githubusercontent.com/113248817/190345683-f790f486-f1a9-4025-96fd-e8c1711e77cf.png)

**Comment by SimplesmenteMaria** [comment]
iFood is the major food delivery service in South America: https://en.wikipedia.org/wiki/IFood

PizzaHut websites also connect to the reported domain: `https://www.pizzahut.co.uk/` - `https://www.pizzahut.ca/` - `https://www.pizzahut.co.in/`

**Comment by netflash** [comment]
Is there a way to whitelist `app.logz.io`?

**Comment by netflash** [comment]
Thanks!
