### ISSUE TITLE
netcentric.biz -> cnwebperformance.biz [EasyPrivacy]

### ISSUE THREAD

**Issue by verlok** [easylist/easylist#13377]
### List the website(s) you're having issues:

With reference to #13273.

### What happens?

I work at Netcentric and am the product owner of our LiveUX service.

LiveUX is a web performance measuring service, which helps us improve the web performance and thus user experience of a website.

Having `netcentric.biz` added to the EasyPrivacy list has various negative side effects on visitors of our site and users of our services.

In order to clarify this topic, we have moved the LiveUX service to a dedicated domain name.

Our request is to replace the following entry from `easyprivacy/easyprivacy_trackingservers.txt`:

```txt
||netcentric.biz^$third-party
```

With the following:

```txt
||cnwebperformance.biz^$third-party
```

Implementing this change will solve the side effects of the current blocking, while ensuring the EasyPrivacy list remains up to date.

**Comment by ryanbr** [comment]
Have added. Read https://github.com/easylist/easylist/blob/master/README.md#easyprivacy it's covered as policy, we don't have special list for good actors or bad actors. If you collect or track data we will block it.

**Comment by verlok** [comment]
Hey @ryanbr ,
I’m sorry if I didn’t make myself clear in my previous message.

The tracking server was **moved** from `netcentric.biz` to `cnwebperformance.biz`, so there is **no tracking service** left on the domain `netcentric.biz`. 

The subdomain on which this tracker was running, `liveux.netcentric.biz`, initially mentioned in #13273, has been **completely decommissioned** and all services have been **moved to `cnwebperformance.biz`**.

The listing of the Netcentric domain on EasyPrivacy is causing issues with some of our clients which are not able to access some of our services (your lists are used also for DNS filtering/blocking by popular ad-blocking platforms which cannot really distinguish between third-party or first-level blocking).

Please remove `netcentric.biz` from the EasyPrivacy list as there is no longer any service running violating the policies outlined at https://github.com/easylist/easylist#easylist or https://github.com/easylist/easylist#easyprivacy.
