### ISSUE TITLE
easylist.to

### ISSUE THREAD

**Issue by AroKol78** [easylist/easylist#13389]
problems with loading (network error) `https://easylist.to/easylist/easylist.txt` (by analogy with `easyprivacy`,`fanboy-social`) (my second day)
the page itself loads immediately and no problem `https://easylist.to/`
as a result of such a problem, lists take longer to update on uBO - before they regrind and come to the mirror

**Comment by dportvine** [comment]
I thought I was the only one with this problem.

**Comment by krystian3w** [comment]
#13477

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/13409 https://github.com/easylist/easylist/issues/13477

**Comment by ryanbr** [comment]
Can you test using a vpn in different regions? Is it a specific country? @AroKol78 @dportvine

**Comment by dportvine** [comment]
Netherlands, UK, USA & i from Ukraine = same result.

**Comment by The-Compiler** [comment]
Same here in Switzerland, and I know people who see this in the Netherlands (and possibly elsewhere?) too.

Ping/traceroute to easylist.to seems fine, it looks like the webserver simply isn't answering for a long time or something.

**Comment by AroKol78** [comment]
Poland - not vpn

**Comment by krystian3w** [comment]
Maybe for test disable page for India due cloudflare logs about extend qouta by this community or bots.

**Comment by The-Compiler** [comment]
FWIW, here are some mirrors:

- https://secure.fanboy.co.nz/easylist.txt
- https://secure.fanboy.co.nz/easyprivacy.txt

or

- https://easylist-downloads.adblockplus.org/easylist.txt
- https://easylist-downloads.adblockplus.org/easyprivacy.txt

**Comment by krystian3w** [comment]
uBo also started these mirrors:

https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist.txt
https://ublockorigin.pages.dev/thirdparties/easylist.txt
https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist.txt
https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist.txt - 1-2 day(s) delay 😣
https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist.txt

**Comment by dportvine** [comment]
https://adguard.com/en/blog/easylist-filter-problem-help.html

**Comment by AroKol78** [comment]
I have no problem anymore

**Comment by dportvine** [comment]
> I have no problem anymore.

Yes it works fine.
