### ISSUE TITLE
forum.zwame.pt

### ISSUE THREAD

**Issue by virtualwebgit** [easylist/easylist#13386]
### List the website(s) you're having issues:
https://forum.zwame.pt/

### What happens?
At the bottom there is a cookie warning

### List Subscriptions you're using:
EasyList Cookie

### Your settings

- OS/version: Windows 10 x64
- Browser/version: Chrome x64 105.0.5195.127
- Adblock Extension/version: uBlock Origin 1.44.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7e1e79cbeaf9239712cc323c6876dc5c6cadbdb8
