### ISSUE TITLE
nordvpn.com

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#13385]
### List the website(s) you're having issues:

`https://nordvpn.com/uk/`

### What happens?

Cookies

<details>
<summary>Screen</summary>

![2022-09-17_103351](https://user-images.githubusercontent.com/111344219/190846036-aa4ab601-ed9e-4e7c-8998-1cf871187d74.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 21H2 x64
- Browser/version:  Google Chrome 105.0.5195.127
- Adblock Extension/version:  uBO 1.44.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/0dfe49c252035e274b7d2455783fcfd0ee997210
