### ISSUE TITLE
derstandard.at

### ISSUE THREAD

**Issue by wdpi** [easylist/easylist#13391]
### List the website(s) you're having issues:

`https://www.derstandard.at`

### What happens?

Cookie overlay.

`https://www.derstandard.at/consent/tcf/`

![image](https://user-images.githubusercontent.com/100048532/190869047-daf718ad-10aa-46d2-9951-cdd3b68523ba.png)

### List Subscriptions you're using:

"user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "urlhaus-1",
    "adguard-annoyance",
    "fanboy-cookiemonster",
    "fanboy-annoyance",
    "fanboy-social",
    "ublock-annoyances",
    "plowe-0",
    "DEU-0",
    "THA-0"

### Your settings

- OS/version: Ubuntu 20.04.5
- Browser/version: Firefox 104.0
- Adblock Extension/version: 1.44.2

**Comment by Nojuuu** [comment]
https://github.com/easylist/easylist/pull/7741

**Comment by ryanbr** [comment]
No way around it without breaking the site unfortantly.
