### ISSUE TITLE
youtube.com annoyance: context / clarify box

### ISSUE THREAD

**Issue by jonathanstanley** [easylist/easylist#13398]
### List the website(s) you're having issues:
```youtube.com```

### What happens?

Occasionally, youtube adds a prominent ( sometimes very large) blue "context" box .  Examples:

- ```https://www.youtube.com/watch?v=PV4LlOB1OII```
- ```https://www.youtube.com/watch?v=-_7jZhy6xDw``` 

### List Subscriptions you're using:

Fanboy Annoyances List

### Your settings

multiple systems

### Other details:

this can be removed from individual videos with the filter: ```www.youtube.com###clarify-box```
this can be removed from search results with the filter: ```www.youtube.com##ytd-clarification-renderer```

**Comment by ryanbr** [comment]
Its a video? what I'm I looking for? screenshot?

**Comment by jonathanstanley** [comment]
> Its a video? what I'm I looking for? screenshot?

See the blue box.  Here is a screenshot (credit ```https://blog.armware.net/index.php/2020/04/10/youtube-clarification-boxes/```):
![yt-clarification-before-1](https://user-images.githubusercontent.com/2755958/190913398-736091a6-414f-4ef7-a999-e40569f6eed8.jpg)

**Comment by THEtomaso** [comment]
Don't see them from my end, yet.
..but from the look of your screenshot, I'll be adding the rules which you suggested, blindly!

**Comment by ryanbr** [comment]
Leaving this

**Comment by jonathanstanley** [comment]
@ryanbr I see you marked this as completed, but it looks like there isn't any associated commit. Did you intend to close as `not planned`?

**Comment by krystian3w** [comment]
Unplanned button is too hidden to click on.
