### ISSUE TITLE
livescience.com Revokerr K ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#134]
`http://www.livescience.com/28590-bizarre-fish-sported-anal-fins.html`

Sponsored by Revokerr K

**Comment by monzta** [comment]
Should take care of it https://github.com/easylist/easylist/commit/9b4e88479886bc56ff504f909c8593aa97a41a7d

**Comment by terrorist96** [comment]
@monzta Revokerr K ads look to be blocked, but I see other unblocked ads. (advancedpctools.com, amazon.com)

**Comment by monzta** [comment]
This should do it: https://github.com/easylist/easylist/commit/b8ed8fca9cdba9bac06d5ce98baf460966229e81 there will be blank placeholders though
