### ISSUE TITLE
(nsfw) porno365.bingo

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#13407]
### List the website(s) you're having issues:

`https://porno365.bingo/videos/2030/molodaya-blondinka-lyubit-seks-anal-s-dvoynym-proniknoveniem-v-popku/`

### What happens?

I have Adblock Detected with this rule = `/player/stats.php?` **EasyPrivacy**

<details>
<summary>Screen</summary>

![2022-09-19_101822](https://user-images.githubusercontent.com/111344219/190967362-2fd05ac1-8dfe-4989-95ea-34720ed9fc6c.png)
</details>

[Gif](https://imgur.com/a17GGVS)

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 21H2 x64
- Browser/version:  Google Chrome 105.0.5195.127
- Adblock Extension/version:  uBO 1.44.4
<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 100905
  cosmetic: 126524
  scriptlet: 24052
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31411-27, 14m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1511-24, 14m
    fanboy-cookiemonster: 41091-287, 14m
    ublock-annoyances: 4825-52, 14m
  default: 
    user-filters: 10-0, never
    RUS-0: 42160-146, 14m
    easylist: 62963-86, 14m
    easyprivacy: 30632-1570, 14m
    ublock-abuse: 76-1, 14m
    ublock-badware: 4205-103, 14m
    ublock-filters: 32872-171, 14m
    ublock-privacy: 246-8, 14m
    ublock-quick-fixes: 243-9, 14m
    ublock-unbreak: 1859-45, 14m
filterset (user): [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  assetFetchTimeout: 10
  autoUpdateAssetFetchPeriod: 10
  filterAuthorMode: true
  popupFontSize: 13px
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 790 ms (selfie)
  maxAssetCacheWait: 660 ms
```
</details>

**Comment by ryanbr** [comment]
Sure it isn't this rule `_ads.html` @dportvine  ? try badfiltering _ads.html

**Comment by dportvine** [comment]
Yes, i'm sure, only this rule helps `@@/player/stats.php?`

_ads.html in **[RU AdList](chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=RUS-0)**
<details>
<summary>Screen</summary>

![2022-09-19_154107](https://user-images.githubusercontent.com/111344219/191020347-7af2b8e4-c219-4f77-9f38-bed61c29520d.png)
</details>

**Comment by dportvine** [comment]
@ryanbr

**Comment by dportvine** [comment]
@mapx- 
Can you please fix this for uBO users?
