### ISSUE TITLE
https://forums.pcgamer.com/ [Video content being hided]

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#13409]
### List the website(s) you're having issues:
https://forums.pcgamer.com/threads/show-us-your-current-game-character.132320/

### What happens?
Video being hided at https://forums.pcgamer.com/threads/show-us-your-current-game-character.132320/
https://github.com/easylist/easylist/commit/2218b295696955a98c27d6a7981f703b790d5f62

`||gcdn.2mdn.net/*web_video_ads/` (seems to be working to block the "before" ads) 
That being said we could go for something more generic : `/web_video_ads/`

### List Subscriptions you're using:

EL EL

**Comment by ryanbr** [comment]
Aren't we blocking 2mdn.net already?

**Comment by krystian3w** [comment]
See #13389 #13477 - maybe user have less than 99% procent of file loaded.

**Comment by ryanbr** [comment]
Closing, its not really an issue. 2mdn is completely blocked.
