### ISSUE TITLE
www.bing.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#13416]
**cookies notices**

- `<div id="bnp_cookie_banner" class="bnp_cookie_banner StackedView" role="dialog" aria-modal="false" data-position="" data-overlay="false">`

```
###bnp_cookie_banner
##.bnp_cookie_banner
```

- https://imgur.com/a6N3HCD.png

A: `https://www.bing.com/news`

**Comment by ryanbr** [comment]
Scrollbar issues https://github.com/easylist/easylist/pull/9118    is it still current @peace2000  ?

**Comment by peace2000** [comment]
Scrolling works on the first page page load but refresh few times again, and then it gets locked.

**Comment by ryanbr** [comment]
Closing, not fixable to ABP
