### ISSUE TITLE
Typo in EasyPrivacy

### ISSUE THREAD

**Issue by Hebrew-uBO-User** [easylist/easylist#13422]
`/maillist.*/t/$image`
->
`/maillist.*/t/*$image`

**Comment by krystian3w** [comment]
who know, maybe too:

```adb
/maillist*/t/*$image
```

as wildcard without dot

or protected `/`:

```adb
/maillist.*\/t/*$image
```

**Comment by Hebrew-uBO-User** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Its removed in FOP, and still parses from what I see

**Comment by Hebrew-uBO-User** [comment]
fixed
