### ISSUE TITLE
Infinix/Tecno system apps telemetry & "game" ads

### ISSUE THREAD

**Issue by CassiusBETA** [easylist/easylist#13423]
### List the website(s) you're having issues:
toolmatrix.plus (Tracking/Telemetry)
transacme.com (Tracking/Telemetry)
api.eagllwin.com (Tracking/Telemetry)
gamegamb.com (Tracking?)
clog.geniex.com (Tracking/Telemetry)
api.ahagamecenter.com (Tracking/Telemetry)
irl-api.twibida.com (Tracking/Telemetry)
restart-api.palmplaystore.com (Tracking/Telemetry)
hippoobox.com (Ads + Tracking)
minigame.vip (Ads + Tracking)
mini6g.com (Ads + Tracking)

### What happens?
They continue to connect in the background, even when the apps (AHA Games, Palm Store) are disabled. While XOS Launcher, every available option to disable ads, it still continues to connect to these domains.

Install XOS Launcher, and you'll be shown "game ads" on the All Apps drawer
### List Subscriptions you're using:

EasyList
EasyPrivacy
### Your settings

- OS/version: Android 11
- Browser/version: Brave Beta 1.44.86
- Adblock Extension/version: NextDNS

### Other details:
![Screenshot_20220919-173414_1](https://user-images.githubusercontent.com/109208335/191133516-f4f97700-a181-4010-849f-d16b0d6352ba.jpg)
![Screenshot_20220920-065716](https://user-images.githubusercontent.com/109208335/191133615-3dc44a51-4d9b-4ce5-b340-1a7f7da43786.jpg)

**Comment by ryanbr** [comment]
We can't test this, no way to audit it.
