### ISSUE TITLE
https://www.vodafone.pt/ajuda/artigos/business/pacotes-empresariais/tarifarios/os-aditivos-para-empresas-ex-router-proprio-ip-fixo-alojamen.html

### ISSUE THREAD

**Issue by virtualwebgit** [easylist/easylist#13443]
### Your settings

- OS/version: Windows 10 x64
- Browser/version: Chrome x64 105.0.5195.127
- Adblock Extension/version: uBlock Origin 1.44.4

**Comment by ryanbr** [comment]
It's blocked here? Filter blocking `##.ebu-cookies-layer__modal`  Maybe purge and update lists?

**Comment by virtualwebgit** [comment]
Just updated list, and it is not blocked here.

**Comment by krystian3w** [comment]
Check settings and enable use generic filters.
