### ISSUE TITLE
s3-w.us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by bbhtt** [easylist/easylist#13447]
### List the website(s) you're having issues:

https://github.com

### What happens?

Try uploading an image to an issue, Github doesn't upload it says "Try again"

### List Subscriptions you're using:

Fanboy Annoynaces

Adblocker: uBlock origin 

### Your settings

- OS/version: Archlinux
- Browser/version: Firefox Nightly
- Adblock Extension/version: 1.44.4

### Other details:

Not sure what rule is causing this but uBO log says Fanboy's annoynaces and it is blocking file upload in GitHub:

![image](https://user-images.githubusercontent.com/62639087/191519310-1800060d-35cc-4451-b130-ab5f797158d8.png)

**Comment by krystian3w** [comment]
`-1$badfilter`

Also purge cache list twice in Dashboard settings.

**Comment by bbhtt** [comment]
> ```
> -1$badfilter
> ```
> 
> Also purge cache list twice in Dashboard settings.

Yea I fixed it with a personal rule already. Thanks.

**Comment by ryanbr** [comment]
I don't see `-1` filter. ?

**Comment by krystian3w** [comment]
So should be reported into uBlock-issues, maybe possible little fix network filter validator.

**Comment by Khrin** [comment]
@bbhtt Please purge the cache, update all list and see if the faulty filter is still present. https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists
 
I don't see such a entry the filters list.

**Comment by bbhtt** [comment]
> @bbhtt Please purge the cache

Yes, it was cache issue purging and updating seems to have fixed it. Thanks!

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2306
