### ISSUE TITLE
kronikaonline.ro

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#13460]
### List the website(s) you're having issues:
`https://kronikaonline.ro/`

### What happens?
Annoyance

### List Subscriptions you're using:
enabled-by-default lists (PC, english locale), updated

### Your settings

- OS/version: 
- Browser/version: Firefox
- Adblock Extension/version: uBO 1.44.4

### Other details:
I'm guessing it could be classified as a Hungarian site language-wise if such classification would be needed/preferred if this issue will be fixed

https://github.com/AdguardTeam/AdguardFilters/issues/130314

**Comment by ryanbr** [comment]
Resolved in ELC
