### ISSUE TITLE
Adblock Warning Removal List

### ISSUE THREAD

**Issue by largrizzly** [easylist/easylist#13467]
Recently, I've been getting an AdBlock warning at https://www.titantv.com

Win7
Pale Moon 31.2.0.1
uBlock Origin Legacy 1.16.4.30

! Checksum: LJItlYdLn4StAeDrutQkog
! Version: 202209210304
! Title: Adblock Warning Removal List
! Last modified: 21 Sep 2022 03:04 UTC
! Expires: 1 days (update frequency)
! Homepage: https://easylist.to/
! Licence: https://easylist.to/pages/licence.html

Tim Mobley
grizzly@neo.rr.com

**Comment by peace2000** [comment]
Hi, since you are uBlock Origin user I recommend reporting this here: https://github.com/uBlockOrigin/uAssets/issues

uBO's own internal filters are the best for handling anti adblock message.

**Comment by peace2000** [comment]
Btw, not sure if that list is even maintained here (Adblock Warning Removal List) as I didn't find it on this repo.

**Comment by Khrin** [comment]
@largrizzly This isn't the correct place for such requests.

> Btw, not sure if that list is even maintained here (Adblock Warning Removal List) as I didn't find it on this repo.

https://github.com/easylist/antiadblockfilters

**Comment by peace2000** [comment]
@Khrin Aren't admiral domains added to EP?

Like in this commit:
https://github.com/easylist/easylist/commit/d8006326372bfa04d104c2f0a614f327dfd0eddd

**Comment by pgl** [comment]
> Wait, this one goes to Easyprivacy as that warning is generated by an admiral domain.
> 
> `||pointlesshour.com^`
> 
> Fyi @pgl as well.

Added, thanks.
