### ISSUE TITLE
bazilik.media

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#13476]
### List the website(s) you're having issues:

`https://bazilik.media/provajdery-proponuiut-ukrainizuvaty-domenni-imena-lokalnykh-zmi/`

### What happens?

Cookies

<details>
<summary>Screen</summary>

![2022-09-22_213801](https://user-images.githubusercontent.com/111344219/191825878-1fee7133-30d9-4481-88ee-d9dab0282983.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 21H2 x64
- Browser/version:  Google Chrome 105.0.5195.127
- Adblock Extension/version:  uBO 1.44.4

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/cfa9a1fa913dec59739b7f70ce6c63d87aa5efd8
