### ISSUE TITLE
moneypop.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#13474]
### List the website(s) you're having issues:

`https://www.moneypop.com/film/these-are-the-worst-films-of-all-time/`
### What happens?

Ad placeholders
### List Subscriptions you're using:
Default uBO+Fanboy's Annoyance

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox 105
- Adblock Extension/version: uBlock Origin 1.44.4

### Other details:

![1](https://user-images.githubusercontent.com/29574622/191811545-59547aca-88b0-4c85-afd0-351d18140680.png)

**Comment by ryanbr** [comment]
Not seeing this.

**Comment by SeriousHoax** [comment]
> `https://www.moneypop.com/film/these-are-the-worst-films-of-all-time/`



> Not seeing this.

Check in Firefox. The site appears different based on the Chromium/Firefox.

**Comment by Khrin** [comment]
Nowhere to be seen.

**Comment by SeriousHoax** [comment]
> Nowhere to be seen.

I'm still seeing it in Firefox. Adguard Base solves it by `moneypop.com##.pohcontainer`
