### ISSUE TITLE
melmagazine.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13489]
### URLs

- `https://melmagazine.com/en-us/story/the-lost-children-of-runaway-train-2`

### Description

sticky ad container: `.ad__adh-wrapper`

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/110956608/192114790-909f52a9-06bb-4444-a8eb-42f6521df0ca.png">

### Settings

<details>

```yaml
uBlock Origin: 1.44
Firefox: 105.0
listset:
  added:
    adfilt/StopAutoplayOnYouTube
    adguard-spyware-url
    block-lan
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Not seen.

**Comment by wavygecko** [comment]
@ryanbr you have to scroll down the page for it to appear
