### ISSUE TITLE
http://www.spin.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#135]
`http://www.spin.com/`
`http://www.spin.com/2016/09/ann-coulter-was-at-the-roast-of-rob-lowe-because-she-didnt-know-what-a-roast-was/`

Many unblocked ads.

**Comment by monzta** [comment]
This should do it https://github.com/easylist/easylist/commit/9c07bb77949c6df6bdbbd0eb2c0690f2fc8c5998

**Comment by terrorist96** [comment]
@monzta I still see ads everywhere.
