### ISSUE TITLE
inverse.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13525]
### URLs

- `https://www.inverse.com/mind-body/the-strange-psychology-of-rroastme`

### Description

ad wrapper: `##.adWrapper`

<img width="1255" src="https://user-images.githubusercontent.com/110956608/192407724-2be56ce1-1d94-4d8d-b432-273a1416b511.png">

### Settings

<details>

```yaml
uBlock Origin: 1.44
Firefox: 105.0
listset:
  added:
    adfilt/StopAutoplayOnYouTube
    adguard-spyware-url
    block-lan
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
We already blocking this. recheck again.

**Comment by wavygecko** [comment]
Oh, odd. Yeah, I don't see it appearing anymore.
