### ISSUE TITLE
[breakage] https://www.axeptio.eu/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#13529]
### List the website(s) you're having issues:
https://www.axeptio.eu/

### What happens?
Legal links not working - EasyPrivacy related
<img width="881" alt="Screenshot 2022-09-27 at 16 59 00" src="https://user-images.githubusercontent.com/65717387/192562157-0e69f3dc-c3d0-4bfc-869e-81f8bbc2778c.png">

### List Subscriptions you're using:
Easylist Privacy

### Other details:
@@||axept.io^$third-party -> `||axept.io^$third-party,domain=~axeptio.eu`
`@@||googletagmanager.com/gtm.js$domain=axeptio.eu`

**Comment by ryanbr** [comment]
I'm not seeing any issues @felippesantos46
