### ISSUE TITLE
canva.com

### ISSUE THREAD

**Issue by egad13** [easylist/easylist#13538]
### List the website(s) you're having issues:

`https://www.canva.com/`

### What happens?

On **mobile**, the cookie modal shows up while using EasyList Cookie.

### List Subscriptions you're using:

- EasyList Cookie
- EasyList
- EasyPrivacy
- uBlock's built-in filters

### Your settings

- OS/version: Android 11
- Browser/version: Fennec F-droid 105.1.0
- Adblock Extension/version: uBlock Origin 1.44.4

### Other details:

This should be blocked by EasyList Cookie.
It gets blocked on the *desktop* site, but not on mobile.

![Screenshot_20220928-111444-145](https://user-images.githubusercontent.com/32107308/192822442-37c35557-079b-4859-92c7-a92a1164798d.png)

**Comment by ryanbr** [comment]
It should be blocked already? I tested canva on Brave androids = Easylist Cookie. no message here.
