### ISSUE TITLE
`netcentric.biz` no longer violating any policy

### ISSUE THREAD

**Issue by verlok** [easylist/easylist#13550]
Hello,
I'm afraid I didn’t make myself clear in issue #13377, which is related to #13273.

The tracking server was **moved** from `netcentric.biz` to `cnwebperformance.biz`, so there is **no tracking service** left on the domain `netcentric.biz`. 

The subdomain on which this tracker was running, `liveux.netcentric.biz`, initially mentioned in #13273, has been **completely decommissioned** and all services have been **moved to `cnwebperformance.biz`**.

The listing of the Netcentric domain on EasyPrivacy is causing issues with some of our clients which are not able to access some of our services (your lists are used also for DNS filtering/blocking by popular ad-blocking platforms which cannot really distinguish between third-party or first-level blocking).

Please remove `netcentric.biz` from the EasyPrivacy list as there is no longer any service running violating the policies outlined at https://github.com/easylist/easylist#easylist or https://github.com/easylist/easylist#easyprivacy.

**Comment by ryanbr** [comment]
Removed, if anyone reports tracking or suspect behaviour from the domain it'll be readded.
