### ISSUE TITLE
theguardian.com cookie warning

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#13565]
### List the website(s) you're having issues:
https://www.theguardian.com/education/2021/aug/13/why-the-latin-language-is-still-alive

### What happens?
Cookie warning

### List Subscriptions you're using:
All filters offered by uBlock Origin

### Your settings

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 105.0.1
- Adblock Extension/version: uBlock Origin 1.44.4

### Other details:
Screenshot:
![Screenshot 2022-09-30 at 12-15-08 Why the Latin language is still alive Letters](https://user-images.githubusercontent.com/101707608/193238933-f15209c3-b246-4a88-be96-799fe4ba2a78.png)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/tree/master/easylist_cookie#readme
