### ISSUE TITLE
[NSFW] xvideos.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#13594]
### List the website(s) you're having issues:

`https://www.xvideos.com/video72278252/skeptical_model_with_thick_thighs_and_a_big_ass_is_convinced_to_fuck_to_get_into_a_music_video_by_another_model_` - Just as an example (All videos have these).

**NOTE:** You may have to navigate around to a few different videos before both of these will show together.

### What happens?

Ads / Annoyances

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Fanboy’s Annoyance

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 105.0.3
- Adblock Extension/version: uBO 1.44.5b14

### Other details:

Screenshot: `https://user-images.githubusercontent.com/95879668/193492504-6db6a3bb-3021-4c60-a966-7a6e68472973.png`

**Comment by Khrin** [comment]
@q1800 What's the point of closing https://github.com/easylist/easylist/issues/13505 just to open a new one identical?
