### ISSUE TITLE
anker.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#13592]
### List the website(s) you're having issues:

`https://www.anker.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Fanboy’s Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 105.0.1
- Adblock Extension/version: uBO 1.44.5b9

### Other details:

![anker-cookie](https://user-images.githubusercontent.com/95879668/193490519-66dba527-bd0b-46cb-8dd4-020f5ec8cab7.png)

**Comment by notjhoan** [comment]
This breaks the sort by drop down.
![image](https://github.com/user-attachments/assets/2c2db72f-1584-4633-bf73-b9ee13a8d658)
