### ISSUE TITLE
a9droid.com - where is scroll?

### ISSUE THREAD

**Issue by RikoDEV** [easylist/easylist#1361]
### List the website(s) you're having issues:

https://a9droid.com/
https://a9droid.com/sony-xperia-e5-android-nougat-7-0-update/

### What happens?

The EasyList list hides page scroll when you load it.

### List Subscriptions you're using:

- EasyList
- EasyPrivacy

### Your settings

- OS/version: Windows 10 (64 bit)
- Browser/version: Chromium 67.0.3396.79 (64 bit)
- Adblock Extension/version: Nano Adblocker v1.0.0.53

**Comment by hawkeye116477** [comment]
It's caused by antiadblock script. That should help => `a9droid.com#@#div[id^="div-gpt-ad"]` :smile:.
