### ISSUE TITLE
Ads displaying on postimg.cc

### ISSUE THREAD

**Issue by nsuchy** [easylist/easylist#1362]
### List the website(s) you're having issues:
* https://postimg.cc/image/vre7ejgnf/

### What happens?
Advertisements are displaying despite uBlock being enabled.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/8227641/41427609-7b20fe72-6fd5-11e8-9e89-d722b03bb58f.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome Stable Channel
- Adblock Extension/version: uBlock Origin

### Other details:

[my-ublock-backup_2018-06-14_13.19.18.txt](https://github.com/easylist/easylist/files/2103343/my-ublock-backup_2018-06-14_13.19.18.txt)

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/ee1bc08aff99520bf3d54564a4e0df8ade9fd9e1
