### ISSUE TITLE
regionalis.fr

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#13643]
```adblock
##[data-widget-definition="share_page"]
```

A: `https://regionalis.fr/`

**Comment by 0o5rlubm** [comment]
Looks like https://regionalis.fr/ is down :(

**Comment by smed79** [comment]
Is UP and reachable here 
- https://i.imgur.com/faGx1cD.png
- `https://downforeveryoneorjustme.com/regionalis.fr`

**Comment by 0o5rlubm** [comment]
on some others down detector websites, site is down. Ie https://down.com/, https://www.uptrends.com/tools/uptime, 
![image](https://user-images.githubusercontent.com/111613844/194372111-e13ab15d-1285-4fa0-91bd-2bf49e5bfda0.png)

https://pikwy.com/web/633f09b987036e573d36bd6f

it appears ip answer given by dns differs from locations or dns resolvers. 

- 155.133.138.4 website is correctly shown here
- 217.70.184.38 website doesn't work on this one

regarding initial comment, let's wait a couple of days then :)

**Comment by smed79** [comment]
You are right ... (I am behind [UHB dns-server](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#dns-server)).

```
$ dig @8.8.8.8 +short regionalis.fr
217.70.184.38
```

```
$ dig @88.198.70.38 +short regionalis.fr
155.133.138.4
```
Thank you :)

**Comment by 0o5rlubm** [comment]
I know see that forum is temporary closed. "Le forum Regionalis est temporairement fermé."

Perhaps you can close this issue for now, and reopen it when necessary.

**Comment by 0o5rlubm** [comment]
server now sends "Error 404 Vhost unknown." over http and broken certificate over https. May I suggest to close this issue and reopen when site is back? Thanks

**Comment by smed79** [comment]
Ok, done.
