### ISSUE TITLE
atlasvpn.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#13668]
### List the website(s) you're having issues:

`https://atlasvpn.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Fanboy’s Annoyance

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 105.0.3
- Adblock Extension/version: uBO 1.44.5b14

### Other details:

![atlasvpn](https://user-images.githubusercontent.com/95879668/194580561-a83e596f-0be5-4e20-be00-37017dcceffa.png)

**Comment by smed79** [comment]
add
- `##div[class^="cookie-consent__Card"]`

**Comment by spirillen** [comment]
Suggestion for broader reach

`##div[class^="cookie-consent_"]`
