### ISSUE TITLE
digitalocean.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#13669]
**privacy**

- `||tracking.digitalocean.com^`

**annoyance** (sound)

- `||digitalocean.com/_next/static/media/whale-ambience.`

---
`A: https://www.digitalocean.com/community/tutorials/top-best-linux-data-recovery-tools`

**Comment by 0o5rlubm** [comment]
Hello, i don't see "whale-ambience" request for the given sample page. Is it used after a specific action?

**Comment by smed79** [comment]
Hello, 

> i don't see "whale-ambience" request for the given sample page.

- https://i.imgur.com/8iSiToJ.png
- https://i.imgur.com/oN2C06i.png
- `https://www.digitalocean.com/_next/static/media/whale-ambience.aeed5e71.mp3`

> Is it used after a specific action?

Background "**baleine effect**" sound auto start for me when reading/scrolling the article.

**Comment by 0o5rlubm** [comment]
i confirm i don't see any mp3/whale requests while browsing this link or another on this blog on Chrome nor on Firefox, even without any adblocker.
