### ISSUE TITLE
[NSFW] gay4porn.com Popunder + Placeholder needed

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#13675]
### List the website(s) you're having issues:

Example: `https://www.gay4porn.com/videos/3896/alphas-without-a-condom-and-goo-pie-teenies-side-by-side/`

### What happens?

![popups](https://user-images.githubusercontent.com/11689349/194639948-cd829f3a-7b94-43a6-a6c4-bdfe93c67253.png)

***

![Screenshot 2022-10-07 153226](https://user-images.githubusercontent.com/11689349/194639965-b130d17c-5b08-4a78-a025-18fff20f7b66.png)

### List Subscriptions you're using:

`https://github.com/yokoffing/filterlists`

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox 105.0.2
- Adblock Extension/version: uBO 1.44.5b11

**Comment by ryanbr** [comment]
Looks fine now.
