### ISSUE TITLE
afun.com

### ISSUE THREAD

**Issue by Felipefpl** [easylist/easylist#13689]
The site in the tile isnt blocked here https://www.hinatasoul.com/videos/223283

**Comment by ryanbr** [comment]
`You cannot access www.hinatasoul.com. Refresh the page or contact the site owner to request access.`

**Comment by Felipefpl** [comment]
Strange, i can access here without any issues.

**Comment by 0o5rlubm** [comment]
cloudflare geoblocking : i can access with vpn at Sao Paulo

**Comment by Felipefpl** [comment]
i believe adguard has such list
