### ISSUE TITLE
inverse.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#13683]
### List the website(s) you're having issues:
`https://www.inverse.com/science/this-binary-star-system-is-making-gravitational-waves/amp`

### What happens?

Missed ad leftover
### List Subscriptions you're using:

Default uBO + Fanboy’s Annoyance
### Your settings

- OS/version: Windows 11
- Browser/version: Chrome latest stable
- Adblock Extension/version: uBO 1.44.4

### Other details:

![1](https://user-images.githubusercontent.com/29574622/194696775-faff5f20-9dcb-4c83-acf0-ac5b36801e15.png)

**Comment by ryanbr** [comment]
Not seen.

**Comment by SeriousHoax** [comment]
@Yuki2718 @krystian3w Do you see it?

**Comment by Yuki2718** [comment]
Yep.

![inverse](https://user-images.githubusercontent.com/58900598/194706060-d8dbd4c0-1234-43bf-8f04-147d1fd1d64c.png)

Each `.zzk` `.UdU` `.AHH` sufficinetly specifies them, maybe combined `inverse.com##.zzk.UdU.AHH` is okay in this case.

**Comment by SeriousHoax** [comment]
> inverse.com##.zzk.UdU.AHH

Yeah, it works. 
BTW, Adguard Base uses `inverse.com#?#div[class] > amp-ad:upward(1)` to hide it.

**Comment by krystian3w** [comment]
`#?#div > p + div:-abp-has(amp-ad)`
