### ISSUE TITLE
filemoon.sx - broken video

### ISSUE THREAD

**Issue by BlazDT** [easylist/easylist#13691]
### List the website(s) you're having issues:
(https://filemoon.sx/d/alpuh9nn7fnn

### What happens?
Video doesn't load

### List Subscriptions you're using:

EasyList and AdGuard Base

### Your settings
- Browser/version: Chrome
- Adblock Extension/version:  AdGuard for Windows v7.11+Beta+3

### Other details:
This rule fixes it:
$popup,third-party,domain=filemoon.sx,badfilter

https://github.com/AdguardTeam/AdguardFilters/issues/131671

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a64953f6eecbe1b37cc5d9812bfb58924f419edc

**Comment by BlazDT** [comment]
Thank you for the fast fix :)
