### ISSUE TITLE
Grammarly ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#137]
`http://www.citationmachine.net/`

4 unblocked Grammarly ads

**Comment by terrorist96** [comment]
http://www.bibme.org/

**Comment by terrorist96** [comment]
`http://www.freethesaurus.com/test`

**Comment by terrorist96** [comment]
`http://www.merriam-webster.com/`

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/adefab1fc4753f23bc910e8423fe2ece2529b36d https://github.com/easylist/easylist/commit/b6f0a3df04a3a02e99ce5c6783930b341aff5ddc https://github.com/easylist/easylist/commit/5da225aadbf156135a86448a8634b7e08dd99fec
