### ISSUE TITLE
distrowatch.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#13700]
### List the website(s) you're having issues:

`https://distrowatch.com/`

**NOTE:** You may have to refresh the web page several times to get this to appear.

### What happens?

Ad / Annoyance

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Fanboy’s Annoyance

### Your settings

- OS/version: Linux Mint 21
- Browser/version: Firefox 105.0.3
- Adblock Extension/version: uBO 1.44.5b13

### Other details:

![distrowatch](https://user-images.githubusercontent.com/95879668/194792555-0bdc142b-a0bd-4e1e-a0f1-ac5415760bad.png)

**Comment by ryanbr** [comment]
Not seen here
