### ISSUE TITLE
I know i am not following the expectations but i need help on this

### ISSUE THREAD

**Issue by githubissocool** [easylist/easylist#13703]
Ok read the title i know that im suppose to include some url but its more like just asking for a template.

I am creating my ad blocker and i don't know how to make it read the easylist filters. Can you make/give me a template? I only know how to use onbeforerequest to block ads for chrome extension coding.

So can you **please** give me a template or make one? You can also give me an example on how to use it.

Please just show me how to use it

**Comment by ryanbr** [comment]
Not this type of support. If you're reading filters, that is on you
