### ISSUE TITLE
festoolusa.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#13701]
### List the website(s) you're having issues:

`https://www.festoolusa.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Fanboy’s Annoyance

### Your settings

- OS/version: Linux Mint 21
- Browser/version: Firefox 105.0.3
- Adblock Extension/version: uBO 1.44.5b13

### Other details:

![festoolusa](https://user-images.githubusercontent.com/95879668/194791335-bf880409-0209-40e0-b095-eb0867fd082c.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7636e8bac6faa381e705673ae9c0d23e20263ae4
