### ISSUE TITLE
bleepingcomputer.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#13714]
### List the website(s) you're having issues:

`https://www.bleepingcomputer.com/news/security/caffeine-service-lets-anyone-launch-microsoft-365-phishing-attacks/amp/`
### What happens?

Empty ad leftover
### List Subscriptions you're using:

Default uBO + Fanboy’s Annoyance
### Your settings

- OS/version: Android & Windows 11
- Browser/version: Firefox Latest
- Adblock Extension/version: uBO 1.44.4

### Other details:

![2022-10-11_14-28-49](https://user-images.githubusercontent.com/29574622/195041459-bf249c98-210b-476b-9453-3efe76ef612b.PNG)

![image](https://user-images.githubusercontent.com/29574622/195041747-45c1b6a8-b92d-4d94-b11c-d04fc10386b8.png)

**Comment by THEtomaso** [comment]
`amp/` = Accelerated Mobile Page.
IMO, better suited for something like **AdGuard Mobile Ads filter**.

**Comment by SeriousHoax** [comment]
> `amp/` = Accelerated Mobile Page. IMO, better suited for something like **AdGuard Mobile Ads filter**.

Tried enabling AdGuard Mobile Ads filter, but it can't solve it on uBlock Origin.
Adguard Base can solve it in Adguard extension, but not in uBlock Origin.

**Comment by THEtomaso** [comment]
`##amp-connatix-player` ?

**Comment by SeriousHoax** [comment]
> `##amp-connatix-player` ?

Yeah, this one works.
