### ISSUE TITLE
youloveit.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#13726]
### List the website(s) you're having issues:

`https://www.youloveit.com/dolls/2244-unicorn-girls-new-dolls-and-animated-series-form-headstart-toys.html`

### What happens?

1200x280px placeholder above the article.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/22780683/195212858-8f50e944-7a82-44c1-bdf9-7a4aae4c1caf.png)

</details>

### Your settings

- OS/version: Windows 11 22H2 x64
- Browser/version: Chrome 106.0.5249.103 x64
- Adblock Extension/version: uBO 1.44.4 + IDCAC 3.4.3

### Other details:

I propose `youloveit.com##.content > center`

<details>

![image](https://user-images.githubusercontent.com/22780683/195213034-a03f5b8b-1d65-4d62-8bb0-2143f6401d99.png)

</details>

**Comment by ryanbr** [comment]
Does `youloveit.com##.btop` work for you?

**Comment by DandelionSprout** [comment]
I think so, yes.
