### ISSUE TITLE
[NSFW] fancentro.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#13730]
### List the website(s) you're having issues:

`https://fancentro.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Fanboy's Annoyance List

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 108.0.2
- Adblock Extension/version: uBO 1.46.1b6

### Other details:

`https://user-images.githubusercontent.com/95879668/205517616-7aca87d4-0d7c-4cdc-bda4-1924e7724322.png`

**Comment by smed79** [comment]
> Cookie Notice

```adblock
fancentro.com##.jss10.jss17
```
**privacy**

```adblock
/logUsersAction/*
/initialState.get?
||esopoo7e.mooo.com^
```

@q1800 Does not embed screenshots for **NSFW** websites.

**Comment by smed79** [comment]
I was meaning instead of [embed the screenshot](https://www.w3schools.com/html/html_images.asp), just wrap the img url in a code tag 

- \`url\` **not** `![alt](url)`

... as you have already did. Thank you.
