### ISSUE TITLE
[NSFW]gaybeeg.info

### ISSUE THREAD

**Issue by gototheskinny** [easylist/easylist#13743]
Device:i12 with ios15.0
App:Adguard for iOS with easy list+easyprivacy enabled
Link:[link](https://gaybeeg.info/2022/04/01/nextdoortwink-hard-to-hide-max-lorde-nico-coopa-evan-knoxx-bareback/)
Explanation: Easyprivacy list causing the download button stuck at "loading" I've tried almost every list on that app but only EasyPrivacy caused this issue.

**Comment by ryanbr** [comment]
Loads fine here.

**Comment by gototheskinny** [comment]
I just enabled easyprivacy like I said on ios15 safari adguard and still says loading

**Comment by dportvine** [comment]
<details>
<summary>Screen</summary>

![2022-10-14_091027](https://user-images.githubusercontent.com/111344219/195774803-cace9899-9b80-4e5e-af7f-b094b7665bec.png)
</details>

**EasyPrivacy**
```adb
||stats.netdna-storage.com^
```
Works for me.
```adb
@@||stats.netdna-storage.com/api/node?folder=*.mp4$xmlhttprequest,domain=gaybeeg.info
```

**Comment by gototheskinny** [comment]
The 2nd rule fixed the issue for me.
