### ISSUE TITLE
archlinux.org

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#13746]
### List the website(s) you're having issues:

`https://archlinux.org/`

### What happens?

Annoyances

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Fanboy’s Annoyance

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 105.0.3
- Adblock Extension/version: uBO 1.44.5b14

### Other details:

![archlinux](https://user-images.githubusercontent.com/95879668/195667973-986d6dca-1167-49d5-bcd7-e55eee74dcdb.png)

**Comment by smed79** [comment]
add
```adblock
###home-donate-button
```
