### ISSUE TITLE
next-episode.net

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#13741]
### List the website(s) you're having issues:

`https://next-episode.net/`

### What happens?

Cookies

<details>
<summary>Screen</summary>

![2022-10-13_131634](https://user-images.githubusercontent.com/111344219/195570707-77f6fb22-4671-4e7e-83bb-435a1f933e54.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 21H2 x64
- Browser/version:  Google Chrome 106.0.5249.119
- Adblock Extension/version:  uBO 1.44.4

**Comment by ryanbr** [comment]
resolved? @dportvine

**Comment by dportvine** [comment]
@ryanbr 

Not for me, because...
<details>
<summary>Screen</summary>

![2022-10-15_192537](https://user-images.githubusercontent.com/111344219/195997407-93832f7f-b431-47bd-a9e1-4aa0c6d5a32b.png)
</details>
