### ISSUE TITLE
Youtube privacy

### ISSUE THREAD

**Issue by 0o5rlubm** [easylist/easylist#13767]
I've tested since a week to use more aggressive youtube stats endpoint blacklist without any issue (video playback, integration, next video follow-up, all without account).

Could someone try to use them too for some time? Just add following two lines to your own list and see if you encounter any issue for some days. I prefer to avoid blocking the first world website by mistake :)

```
||youtube.com/api/stats
||youtube-nocookie.com/api/stats
```

**Comment by smed79** [comment]
see https://github.com/easylist/easylist/pull/4595
