### ISSUE TITLE
http://www.plagiarism.org/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#138]
`http://www.plagiarism.org/`

Sponsored by WriteCheck

**Comment by monzta** [comment]
Seems to be gone.

**Comment by terrorist96** [comment]
@monzta still there. Bottom left hand corner.

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/3c1783bbf9e0e4c9cc308c18b872c0bbdad8c2db
