### ISSUE TITLE
[nsfw] tube8.com: breakage

### ISSUE THREAD

**Issue by Trouble-bubbles** [easylist/easylist#13826]
EasyList (adult)

### List the website(s) you're having issues:

`[nsfw] https://www.tube8.com/amateur/sweetsinner-milf-cant-stop-fucking-her-best-friends-husband/81281201/`

### What happens?

Video is hidden by:

https://github.com/easylist/easylist/blob/0bcb87b427314da1642d81e9e61d34f603f740ac/easylist_adult/adult_specific_hide.txt#L692

Should help add `:not(video)`.

Page use blob on videos to block easy download and re-upload somewhere.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Android 12
- Browser/version: Firefox 106 
- Adblock Extension/version: uBo 1.44.4

**Comment by Trouble-bubbles** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15328

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3a8cb7aa6c66d8c2336ce4e591b5295aab570282
