### ISSUE TITLE
*.bloodhoundenterprise.io

### ISSUE THREAD

**Issue by rvazarkar** [easylist/easylist#13830]
### List the website(s) you're having issues:
```*.bloodhoundenterprise.io```

### What happens?

The ```bloodhoundenterprise.io``` domain has several subdomains for different customers (example: ```test.bloodhoundenterprise.io```). As part of the product, we ship data collectors to our customers, and the endpoint for grabbing those collectors appears to be blocked by EasyPrivacy (most likely due to name).

![image](https://user-images.githubusercontent.com/5720446/196728084-93c0356b-bc9f-4b44-ac5d-4172236a2312.png)

The filter prevents users from seeing the available collectors for download. 

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/5720446/196728834-468efdfa-e63f-4c7b-9725-ea860e4e681c.png)

### Your settings

- OS/version: Windows 11 22H2
- Browser/version: Firefox 105.0.3
- Adblock Extension/version: uBlock Origin 1.44.4

### Other details:
![image](https://user-images.githubusercontent.com/5720446/196729105-402ee21f-88ab-49de-8a70-efc2ef8f35ac.png)

**Comment by 0o5rlubm** [comment]
@rvazarkar could you post a link to a public website where usage of this resource can be seen?

test.bloodhoundenterprise.io appears to ask login

**Comment by rvazarkar** [comment]
Hi @0o5rlubm this is a production website that contains sensitive information for our customers, so I can't provide a login, but I would be happy to provide any details necessary to triage this.

**Comment by superlinkx** [comment]
Just wanted to chime in here:

> Or is it part of a closed-source product non available publicly?

Correct, it's part of a non-publicly available hosted product

**Comment by Khrin** [comment]
@superlinkx Without even a demo login, it's impossible to even think how to fix it. Goodbye.

**Comment by ddlees** [comment]
New here so forgive me if I'm misunderstanding...

The filter that is affecting the urls in question lives [here](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L804).

For us, it blocks the valid (and not-tracker) urls that match `*.bloodhoundenterprise.io/api/v2/collectors/:collectorId`

Would it be appropriate to change the filter to something similar to what you do for some other domains (facebook.com, wordpress.org, my.leadpages.net, etc)?

E.g.

```
/api/v2/collector$domain=~bloodhoundenterprise.io
```

That said, we may be able to coordinate something if it's a matter of verifying those urls are not privacy violating.

Thanks in advance!
