### ISSUE TITLE
agent.config.contrastsecurity.com

### ISSUE THREAD

**Issue by Silvenga** [easylist/easylist#13846]
### List the website(s) you're having issues:

```
https://agent.config.contrastsecurity.com
```

### What happens?

The web assembly breaks during JS interop - breaking the whole application.

### List Subscriptions you're using:

- easyprivacy

### Your settings

- OS/version: Windows 10/11
- Browser/version: Chrome 106.0.5249.119
- Adblock Extension/version: uBlock Origin 1.44.4

### Other details:

So this one might be a little iffy, but hear me out.

- This site is a offline web-assembly application. 
- The app uses the project [blazor-analytics](https://github.com/isc30/blazor-analytics). 
- The blazor-analytics just acts as a wrapper to Google Analytics (which is already blocked by easyprivacy).
- The `blazor-analytics.js` file is ultimately blocked by easylist, which breaks JS interop (which will break any app using blazor-analytics).

The JS file as of the current version:
```
window.dataLayer = window.dataLayer || [];
window.gtag = window.gtag || function () { dataLayer.push(arguments); };
gtag("js", new Date());
var GoogleAnalyticsInterop;
(function (GoogleAnalyticsInterop) {
    function configure(trackingId, debug) {
        if (debug === void 0) { debug = false; }
        this.debug = debug;
        var script = document.createElement("script");
        script.async = true;
        script.src = "https://www.googletagmanager.com/gtag/js?id=" + trackingId;
        document.head.appendChild(script);
        gtag("config", trackingId, { 'send_page_view': false });
        if (this.debug) {
            console.log("[GTAG][" + trackingId + "] Configured!");
        }
    }
    GoogleAnalyticsInterop.configure = configure;
    function navigate(trackingId, href) {
        gtag("config", trackingId, { page_location: href });
        if (this.debug) {
            console.log("[GTAG][" + trackingId + "] Navigated: '" + href + "'");
        }
    }
    GoogleAnalyticsInterop.navigate = navigate;
    function trackEvent(eventName, eventData) {
        gtag("event", eventName, eventData);
        if (this.debug) {
            console.log("[GTAG][Event triggered]: " + eventName);
        }
    }
    GoogleAnalyticsInterop.trackEvent = trackEvent;
})(GoogleAnalyticsInterop || (GoogleAnalyticsInterop = {}));
```

I would propose this particular file be removed from Easyprivacy as it's inclusion only breaks applications without improving privacy (since Google Analytics is already correctly blocked). I'm guessing this file was accidently added because of the name of the file.

https://github.com/easylist/easylist/blame/master/easyprivacy/easyprivacy_general.txt#L1035

**Comment by Silvenga** [comment]
(and for full disclosure, I am one of the developers who worked on this site)

**Comment by ryanbr** [comment]
Why not just fix the script? so if blocked, it won't break other parts. For privacy, for end user, this would be much better

**Comment by ryanbr** [comment]
Given the google tracking elements, we don't need to fix anything. Don't break a site if its blocked, pretty simple, don't rely on tracking elements always return a value.

**Comment by Silvenga** [comment]
Ultimately I fixed this issue by injecting the script directly into the bundle via the service worker during offline installation, rather than loading them directly. Ironically this hides the script from ublock.

IMO, working with developers on maintaining app functionality is better than developers creating holes/bypasses making the job of easylist harder in the long run.

Not breaking the site non-trivial, given this is an offline app with an installation manifest that verifies downloaded assets (the bootstrapper has no concept of if something is optional). This isn't a JS app, it's a web-assembly app running the .NET runtime in the browser - semantics are different. In JS, if a method doesn't exist, the JS app moves on. In most other languages (C# in this case), a missing method is an app crash (unhandled exception, since the compiler assumes every method linked exists during runtime).
