### ISSUE TITLE
Breakage: clien.net comment section

### ISSUE THREAD

**Issue by seia-soto** [easylist/easylist#13856]
### List the website(s) you're having issues:

https://www.clien.net/service/board/cm_iphonien/16975929#comment_write_point

### What happens?

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/30369714/197273033-b47e5795-d8b3-4f47-9859-603a755afcab.png)

![image](https://user-images.githubusercontent.com/30369714/197273406-128c5e22-d0bf-4a26-b229-c0e4da2d5605.png)

</details>

### List Subscriptions you're using:

<details>
<summary>Details</summary>

```
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 88722
  cosmetic: 45056
  scriptlet: 18198
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://github.com/seia-soto/filter-kr/raw/master/filter.txt: 227-1, 1d.23h.19m
    https://github.com/seia-soto/filter-kr/raw/master/filters-specific/namuwiki.useless.txt: 5-0, 2h.51m
    https://github.com/seia-soto/filter-kr/raw/master/filters-specific/twitter.useless.txt: 2-0, 2h.52m
    https://github.com/yous/YousList/raw/master/youslist.txt: 8327-5, 8h.25m
  default: 
    user-filters: 3-0, never
    easylist: 62053-63, 2m
    easyprivacy: 30725-1176, 5d.8h.27m
    plowe-0: 3671-864, 12d.12h.19m
    ublock-abuse: 76-0, 12d.12h.19m
    ublock-badware: 4394-105, 8h.28m
    ublock-filters: 33147-116, 8h.27m
    ublock-privacy: 250-1, 12d.12h.19m
    ublock-quick-fixes: 420-34, 2h.54m
    ublock-unbreak: 1876-42, 8h.26m
    urlhaus-1: 9364-0, 2h.53m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 193 ms (selfie)
  maxAssetCacheWait: 129 ms
```

</details>

### Your settings

- OS/version: macOS
- Browser/version: Arc 0.73.0
- Adblock Extension/version: uBO

### Other details:

xpath to the el: /html/body/div[2]/div[2]/div[1]/div[2]/div[5]/div[2]

**Comment by Yuki2718** [comment]
Here `https://ssl.pstatic.net/adimg3.search/adpost/js/adpost_show_ads_v2.min.js` looks to be tracker, caught by a now-removed rule `_show_ads_`.
