### ISSUE TITLE
so much global regexp close 18 site to usage ! not advertisements but sites!

### ISSUE THREAD

**Issue by iltaren** [easylist/easylist#1386]
at easylist there is regexp like that, did you try that regexp ? 

/^https?:\/\/([0-9a-z\-]+\.)?(9anime|animeland|animenova|animeplus|animetoon|animewow|gamestorrent|goodanime|gogoanime|igg-games|kimcartoon|mangapanda|mangareader|memecenter|readcomiconline|toonget|toonova|watchcartoononline)\.[a-z]{2,4}\/(?!([Ss]cripts|[Uu]ploads|[Ii]mages|assets|combined|content|cover|img|static|thumbs|wp-content|wp-includes))(.*)/$image,other,script,~third-party,xmlhttprequest

problem is 
that regexp is so much global close these sites completely to usage. 

https://www.mangareader.net/main.js matches to that regexp
https://www.mangapanda.com/logo.png matches to that regexp 
https://s1.mangapanda.com/favicon.ico matches to that regexp 
https://www.readcomiconline.com/favicon.ico matches to that regexp
https://www.readcomiconline.com/index.php matches to that regexp

problem is regexp is so much global.
it completely close 18 site all together. 
Solution is need to remove that regexp and put right conditions for advertisements not for closing sites or closing all their images or javascripts.

**Comment by Khrin** [comment]
I don't see any chances to have this filter removed soon, sorry.
