### ISSUE TITLE
napthe.vn

### ISSUE THREAD

**Issue by bigdargon** [easylist/easylist#13865]
### What happens?

Can't login account

### List Subscriptions you're using:

uBlock filter
EasyList
EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 102.4.0 ESR
- Adblock Extension/version: uBlock Origin 1.44.4

### Other details:

All games logged in with Garena are affected. I tried allowing domains `datadome.co` and `captcha-display.com` and it works fine.

I also have NextDNS which uses Easylist and Easyprivacy filters, please unblock this domain! Thank you!

**Comment by ryanbr** [comment]
Working fine here, Not testing with nextDNS.  Login window opened here.
