### ISSUE TITLE
emathhelp.net formulas are blocked

### ISSUE THREAD

**Issue by proy87** [easylist/easylist#1388]
Page: https://www.emathhelp.net/calculators/calculus-1/derivative-calculator/
Browser: Chrome
Operating System: Windows (and Ubuntu)

Current behaviour: in console I see error for MathJax: Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' * 'unsafe-inline'".

Expected behaviour: should be no errors.

There are no errors when adblock is turned off.

**Comment by monzta** [comment]
Fixed.

**Comment by proy87** [comment]
See no difference. When will be update?

**Comment by proy87** [comment]
Page: https://www.emathhelp.net/calculators/calculus-1/derivative-calculator/
Browser: Firefox
Operating System: Windows (and Ubuntu)

Current behaviour: in console I see error for MathJax: Error: call to eval() blocked by CSP
MathJax.js:19:3524

Expected behaviour: should be no errors.

There are no errors when adblock is turned off.
