### ISSUE TITLE
http://www.biology-online.org/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#139]
`http://www.biology-online.org/`
`http://www.biology-online.org/dictionary/Main_Page`

Unblocked ads.

Also, clicking around on the links will cause popups.

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/737bc8019b20488537a0ac2696cb3c868517904f 

It won't work in Chrome though.

**Comment by terrorist96** [comment]
@monzta So it's not possible to blocks these ads on Chrome with ABP? Could you please explain why? Thanks.
