### ISSUE TITLE
dmagazine.docomo.ne.jp

### ISSUE THREAD

**Issue by dokurocker** [easylist/easylist#13907]
### List the website(s) you're having issues:

https://dmagazine.docomo.ne.jp/info/welcome/
https://dmagazine.docomo.ne.jp/item/*

### What happens?

[.ad-label] was blocked.
easylist/easylist_allowlist_general_hide.txt
`dbook.docomo.ne.jp#@#.ad-label`
↓
`dbook.docomo.ne.jp,dmagazine.docomo.ne.jp#@#.ad-label`
(Use similar settings)

### List Subscriptions you're using:

ublock, adguard
### Your settings

- OS/version: Windows 10 Pro
- Browser/version: Google Chrome 106.0.5249.119
- Adblock Extension/version: uBlock 1.44.4, AdGuard 4.1.37

### Other details:

#13354

**Comment by Yuki2718** [comment]
@ryanbr Now `dbook.docomo.ne.jp,` in the line is redundant.
