### ISSUE TITLE
en.mapy.cz

### ISSUE THREAD

**Issue by DesertBear** [easylist/easylist#13911]
### List the website(s) you're having issues:

```
https://en.mapy.cz/
```

### What happens?

A full-screen cookie dialogue box is displayed when accessing the site.

Using the uBlock Origin element picker, the below rule removes the cookie dialogue box.

```
mapy.cz##.szn-cmp-dialog-container
```

### List Subscriptions you're using:

Default uBlock Origin filters
Fanboy’s Annoyance
uBlock filters – Annoyances

### Your settings

- OS/version:  Windows 10 22H2 (19045.2130)
- Browser/version:  Edge 106.0.1370.52
- Adblock Extension/version:  uBlock Origin 1.44.4

### Other details:

**Screenshot:**
![Screenshot](https://user-images.githubusercontent.com/27423064/197798757-4de96d1a-8206-46d4-84fd-379394ec32db.png)

**Comment by ryanbr** [comment]
`||h.seznam.cz/js/cmp2/scmp-int.js$domain=en.mapy.cz` was added, did this resolve it? @DesertBear

**Comment by DesertBear** [comment]
Refreshed the filter lists and that works.  Thanks.
