### ISSUE TITLE
theatlantic.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#13913]
### URLs

- `https://www.theatlantic.com/technology/archive/2022/10/amazon-tracking-devices-surveillance-state/671772/`

### Description

leaderboard ad box

![image](https://user-images.githubusercontent.com/110956608/197823868-49e160f7-b285-4381-8b60-82aa2741dcad.png)

### Settings

<details>

```yaml
uBlock Origin: 1.44
Firefox: 106.0
listset:
  added:
    adfilt/StopAutoplayOnYouTube
    adguard-spyware-url
    block-lan
    fanboy-cookiemonster
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by Yuki2718** [comment]
Not fixed on my end as not div:

![theatlantic](https://user-images.githubusercontent.com/58900598/198040093-e7ccd05e-639d-4564-b7d3-3f0d3506ce4e.png)
