### ISSUE TITLE
(NSFW) sinparty.com | preroll ads and cookie banner

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#13915]
### List the website(s) you're having issues:

`https://sinparty.com/porn-videos/cum-pounded-eric-videos-video5ed4d54a483f7`

### What happens?
preroll ads and cookie banner

### List Subscriptions you're using:
`https://github.com/yokoffing/filterlists#recommended-filters-for-ublock-origin`

### Your settings

- OS/version: Win 11
- Browser/version: Firefox stable
- Adblock Extension/version: uBO

**Comment by ryanbr** [comment]
Pre-roll unable to stop, maybe something for the uBO guys?

**Comment by dportvine** [comment]
@mapx-

**Comment by dportvine** [comment]
@gorhill
Why is rewrite in ABP faster than redirect in uBO?
[Gif (NSFW)](https://imgur.com/E2B71Yv)
