### ISSUE TITLE
sumotorrent - element hidding

### ISSUE THREAD

**Issue by wmyrda** [easylist/easylist#1395]
[L9851](https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_hide.txt#L9851)
`sumotorrent.sx#a[href^="http://trafficlord.net/"] `- probably needs extra `#` for element hiding.

I use adblock2privoxy converter which translates rules for privoxy format quite well which allowed me to catch several [upstream rule errors](https://github.com/essandess/adblock2privoxy/issues/14) like the one above. Obviously converter could use some improvements. It is also not able to parse those two
```
@@.gif#$domain=
@@.ico#$domain=
```
It likely has problem with `#` and it thinks it should be `##` for element hiding. How should that be parsed? I do not see example of such combination on [filter-cheatsheet](https://adblockplus.org/filter-cheatsheet).

**Comment by monzta** [comment]
You are correct, thanks: https://github.com/easylist/easylist/commit/aadaef9b303a16920dac2818924d9e6273ab9076 

The hash character is actually part of the string of the images. So it's not a (un)hiding filter.
