### ISSUE TITLE
yahoo.com

### ISSUE THREAD

**Issue by virtualwebgit** [easylist/easylist#13967]
### List Subscriptions you're using:

 Easylist Cookie

### Your settings

- OS/version: Windows 10 x64
- Browser/version: Google Chrome x64 107.0.5304.88
- Adblock Extension/version: uBlock Origin 1.44.4

**Comment by 0o5rlubm** [comment]
see the Readme file, cannot be blocked. https://github.com/easylist/easylist/tree/master/easylist_cookie#consent-companys



yahoo consent | popup overlay | Used by some sites like Engadget creates a redirect which cannot be blocked.
-- | -- | --
