### ISSUE TITLE
Cookie warning on https://www.skopenow.com/

### ISSUE THREAD

**Issue by joebagadonuts188** [easylist/easylist#13971]
### List the website(s) you're having issues:

`https://www.skopenow.com/`

### What happens?

Cookie warning banner at the bottom of the page.

### List Subscriptions you're using:

easylist: 62636-70, now
easyprivacy: 30832-1286, now
ublock-abuse: 76-1, now
ublock-badware: 3953-104, now
ublock-filters: 31104-176, now
ublock-privacy: 260-2, now
ublock-quick-fixes: 453-20, now
ublock-unbreak: 1882-45, now
urlhaus-1: 11029-6, now

### Your settings

- OS/version: Win 10 21H1
- Browser/version: Version 106.0.5249.119 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.44.4

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/13972
#13972 opened 6 hours ago by [joebagadonuts188](https://github.com/easylist/easylist/issues?q=is%3Aissue+is%3Aopen+author%3Ajoebagadonuts188)
1
https://github.com/easylist/easylist/issues/13971
#13971 opened 6 hours ago by [joebagadonuts188](https://github.com/easylist/easylist/issues?q=is%3Aissue+is%3Aopen+author%3Ajoebagadonuts188)
https://github.com/easylist/easylist/issues/13970
#13970 opened 6 hours ago by [joebagadonuts188](https://github.com/easylist/easylist/issues?q=is%3Aissue+is%3Aopen+author%3Ajoebagadonuts188)

**Comment by joebagadonuts188** [comment]
I accidentally left off other filters that I have enabled. They are:

added: 
adguard-spyware-url: 793-1, 1d.49m
curben-phishing: 172767-0, 49m
fanboy-cookiemonster: 42365-113, 1d.49m

I still see the cookie banner at the bottom.

**Comment by joebagadonuts188** [comment]
I updated my filter lists and it is still not blocked. Could you kindly add it to EasyList Cookie?

**Comment by joebagadonuts188** [comment]
There is still an issue. I have attached a picture that shows the bar at the bottom.
![skopenow screenshot](https://user-images.githubusercontent.com/100051044/205518541-25f4f0fe-9df8-4b3a-89de-cf92a60ff839.JPG)
