### ISSUE TITLE
xe.com

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#13993]
### List the website(s) you're having issues:

`https://www.xe.com/`

### What happens?

Cookies

<details>
<summary>Screen</summary>

![2022-11-01_144321](https://user-images.githubusercontent.com/111344219/199235061-02004501-59f7-406f-a06e-27a9ae549486.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome 107.0.5304.88
- Adblock Extension/version:  uBO 1.44.4

**Comment by dportvine** [comment]
@ryanbr

**Comment by dportvine** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Not seen here? Does `xe.com##[class^="ConsentBanner"]` help?

**Comment by dportvine** [comment]
It doesn't help me. If I hide the banner, the content of the site disappears. 
@mapx- Can you help?

**Comment by mapx-** [comment]
Test

`xe.com##[class*="ConsentBannerstyles__Banner"]:remove()`

**Comment by dportvine** [comment]
>xe.com##[class*="ConsentBannerstyles__Banner"]:remove()

It works for me.

**Comment by ryanbr** [comment]
Does `xe.com##[class*="ConsentBannerstyles__Banner"]` that not work? (without the :remove)

**Comment by mapx-** [comment]
> the content of the site disappears

**Comment by dportvine** [comment]
> Does `xe.com##[class*="ConsentBannerstyles__Banner"]` that not work? (without the :remove)

only with `:remove()` [Gif](https://imgur.com/7kFXmwR)

**Comment by dportvine** [comment]
@ryanbr

**Comment by dportvine** [comment]
@ryanbr

**Comment by dportvine** [comment]
@ryanbr
