### ISSUE TITLE
lucidchart.com

### ISSUE THREAD

**Issue by mckennapsean** [easylist/easylist#14018]
### Website issues:

`https://cdn-font-service-private.app.lucidchart.com/ad/af/9b/f8/36/4b/31/01/b1/bc/b7/3e/c6/79/4c/5c/fallback/FontNameLetters?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWZvbnQtc2VydmljZS1wcml2YXRlLmFwcC5sdWNpZGNoYXJ0LmNvbS9hZC9hZi85Yi9mOC8zNi80Yi8zMS8wMS9iMS9iYy9iNy8zZS9jNi83OS80Yy81Yy8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjY3NjI4ODMwfX19XX0_&Signature=nOTR8xaMvefpEzWClwqD0yf-qFHJu99IlH~ItEi0NhaAkilpVBALXrShVKlUcgS3Anw5wH73WQ0j2fG72IpgnatINTS~aBAnPnYOvD9cAv4JTRj5l3OrbsRwFmEWSePSooz5fd1gpszWzXt8aEMBrvHCLZyqIzZkRfLGTD-ZWg1CKu8~a6ZF4PFgFB-ZsAT6C9jNKDRu3pxpbzw1mnDzkE8R8MEoc26xEl2t5TvJrL91WYaLum7mapodzwj-eXxdTGHRCFGrh9fI2xN948dHSQjZoMFHBQPzRmc~woQuLrc7IVPKNP01URt-HRpnvjnLqnNMpYvLPWAzPnWkTWhAdA__&Key-Pair-Id=K17YMWRGYL5Q7S&cachebuster=08-11-2021`

_Note:_ this may be a signed S3 URL, so if it fails, then it may have expired. I can generate a new link to send if that occurs, so just let me know if it does!

### What happens?

In Lucid Software's products, users can upload their own fonts or download fonts we provide for them using our fonts CDN.

With ad blocking enabled, some custom user fonts are blocked from loading. When that occurs, the document becomes unreadable. Example below.

Ad Blocking enabled:
![Screenshot from 2022-11-04 12-43-36](https://user-images.githubusercontent.com/1406149/200051956-3386fcd6-f728-435e-9e09-1c6b98b57b01.png)

Ad Blocking disabled:
![Screenshot from 2022-11-04 12-43-51](https://user-images.githubusercontent.com/1406149/200051965-9fd8a112-d8f4-452a-b00b-afefec371ba9.png)

We split apart the font asset's hash into 2 characters each, and this results in possible combinations of `/ad/` that may appear in the custom asset's URL, which appears to be blocked by most ad blockers that we know use EasyList under the hood.

This is trickier to reproduce, since it only happens per-chance for some custom fonts uploaded per site (depends on the hash). These assets have already been uploaded to these URLs, so a fix on our end is non-trivial and requires redesigning. If needed, I can generate & share a public example of a document failing; just let me know if you need one.

### List Subscriptions & Settings

- EasyList from the Brave web browser, v.1.45.118 on Chromium 107, Ubuntu Linux
- also affected a Mac customer using Chrome & the AdBlock extension

**Comment by DandelionSprout** [comment]
Seems to have been fixed at some point in the 9 months that have passed since, since I can't find any sort of mere `/ad/*` entries in EasyList now.

**Comment by mckennapsean** [comment]
I know that I observed this bug just two weeks ago, but it could be that the list used by the Brave browser is different than strictly EasyList (or takes longer to get changes). Not sure.

Thanks for checking! We are actually planning a fix internally for our URLs that we plan to get around this issue anyway.
