### ISSUE TITLE
ziare.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#14023]
### List the website(s) you're having issues:
`https://ziare.com/`

### What happens?
`etop.ro` third-party connections

### List Subscriptions you're using:
uBO Romanian config

### Your settings

- OS/version: 
- Browser/version: chrome
- Adblock Extension/version: uBO

### Other details:
![image](https://user-images.githubusercontent.com/117513128/200115027-b3e0f9fa-b09a-49cc-8247-af86a75a20f7.png)
I believe `ziare.com` is Romanian.

**Comment by AntiAdvert** [comment]
@ryanbr Could it be addressed in `EasyPrivacy`?
