### ISSUE TITLE
Cookie warning on https://www.dailymotion.com/

### ISSUE THREAD

**Issue by joebagadonuts188** [easylist/easylist#14046]
### List the website(s) you're having issues:

`https://www.dailymotion.com/`

### What happens?

Annoying cookie warning at the top of the page.

### List Subscriptions you're using:

easylist: 64358-68, now
easyprivacy: 30783-1283, now
ublock-abuse: 76-1, now
ublock-badware: 3958-108, now
ublock-filters: 31164-154, now
ublock-privacy: 257-2, now
ublock-quick-fixes: 488-34, now
ublock-unbreak: 1890-45, now
urlhaus-1: 10281-7, now
adguard-spyware-url: 795-1, now
curben-phishing: 165722-1, now
fanboy-cookiemonster: 42663-130, now

### Your settings

- OS/version: Win 10 21H1
- Browser/version: Version 107.0.5304.88 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.44.4

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/blob/master/easylist_cookie/README.md

**Comment by joebagadonuts188** [comment]
There is still an issue. I have attached a picture that shows the bar at the bottom.
![dailymotion screenshot](https://user-images.githubusercontent.com/100051044/205518558-7e9fee31-4ca7-4653-8646-2c7b6359cf21.JPG)

**Comment by krystian3w** [comment]
You can't read tables?



dailymotion | Consent overlay shows | Denys video playback
-- | -- | --
