### ISSUE TITLE
akakce.com

### ISSUE THREAD

**Issue by gototheskinny** [easylist/easylist#14056]
Link: [https://www.akakce.com/harddisk.html](https://www.akakce.com/harddisk.html)
On top of the page and every other page has this too

**Comment by gototheskinny** [comment]
> What are we looking for? The page loaded fine here.

On ios 15 w/adguard for ios free(doesn't have advanced protection) with easylist and annoyance lists enabled of course top the page has ads. With advanced protection ads disappear tho. I think it's about the safari browser tho and can't be fixed with a filter rule. Would be nice for adguard free or other apps users tho.

**Comment by ryanbr** [comment]
Will be best to report to Adguard . https://github.com/AdguardTeam/AdguardFilters
