### ISSUE TITLE
notix.io

### ISSUE THREAD

**Issue by notix-push** [easylist/easylist#14062]
### List the website(s) you're having issues:

`kudago.com`, `mid-day.com`, `ticonsiglio.com`, `suara.com`, `bola.com`

### What happens?

NOTIX service domain `notix.io` was added to `easylist_adservers.txt`. It looks like a mistake because it is not serving ads. It's just a cloud-based marketing solution that allows users to manage push notifications through a single platform. Websites owners (mostly news sites) choose on their own what to send, originally they send fresh content recommendations. Like SendPulse & OneSignal, Notix is not an AdServer.

Also these domains appearred in `easylist_adservers.txt`, but they are aliases of `notix.io` and just redirect to it:
`getnotix.co`
`notiks.io`
`notiksio.com`

### List Subscriptions you're using:

Default EasyList subscription in AdBlock Plus.

### Your settings

- OS/version: macOS Monterey 12.6
- Browser/version: Google Chrome 105.0.5195.125 (Official Build) (x86_64)
- Adblock Extension/version: AdBlock Plus 3.14.2

### Other details:

Thank you for reviewing this issue.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5eb58cb174d929d5127865bdd92c2912bde6f557

**Comment by notix-push** [comment]
Thanks a lot for reviewing this issue! Sorry for reopen but `notix.io` still in `easylist_adservers.txt` it's our main domain and all sites mentioned in issue are using code from it.
