### ISSUE TITLE
nexcess.net (cookie notice)

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#14078]
![image](https://user-images.githubusercontent.com/19517680/201026370-d0658b55-ca7d-4faf-993b-4efe419d99b6.png)

https://www.nexcess.net/web-tools/dns-checker/

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7fc7a76f986ad0247feaa74fdf839e40287652db
