### ISSUE TITLE
Query regarding a specific script addition (OtAutoBlock.js) 

### ISSUE THREAD

**Issue by omidantilong** [easylist/easylist#14081]
### List the website(s) you're having issues:

`coop.co.uk`
`drax.com`
`callawaygolfpreowned.com` (the site referenced in the commit below)
and other sites using OneTrust's cdn-hosted cookie banner and auto-blocking script, `OtAutoBlock.js`

### What happens?

This is not a request for a specific addition or removal, but a query as to why a certain script has been added to EasyPrivacy. I'm sure the maintainers of this repo are aware of OneTrust and the off-the-shelf GDPR solution they offer. We've noticed an issue over the last couple of days where the script OneTrust provide which _blocks_ scripts that set cookies until users have consented to cookies, is itself being blocked by browsers running adblockers, including Brave with shields up. 

The functionality of the script is to take the results of a cookie scan from the OneTrust dashboard and check these against the `src` of script tags on the page. It creates a mutation observer which halts the execution of those scripts by setting the script `type` to text/plain, unless/until users accept cookies. 

We've done a bit of sleuthing through the lists in this repo and discovered the blocking script, `OtAutoBlock.js` was added a little over two weeks ago to `easyprivacy_general`  in this commit: https://github.com/easylist/easylist/commit/be99d2d2bdf8154304105db15ab59b1399cea8db

I'm not arguing for its removal, I'd just like to know the rationale behind why it was added :) 

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: MacOS 12.15
- Browser/version: Brave 1.45  / Chrome 107
- Adblock Extension/version: Brave Shields / Any browser running uBlock

Thankyou 😃

**Comment by ryanbr** [comment]
Was a 2 part issue, tracking and we had some reports of images not showing due to  OtAutoBlock.js.

**Comment by omidantilong** [comment]
Thanks for coming back to me on this. Was the images issue specifically related to the `callawaygolfpreowned.com` site? I was able to reproduce the problem on a product page on that site and the images look like they're injected via JS as part of a slider. We've seen similar issues a few times during testing on other websites - eg some navigation menus broke because the file that contained the logic for them also set a cookie. It's a side effect of the heavy handed approach of the blocking script but almost always comes down to scripts being miscategorised when a cookie scan is run. 

The problem with OneTrust is that it removes some of the responsibility from site owners of figuring out what cookies are being set and by which scripts, so I just worry that blocking the OtAutoBlock script entirely has the potential to allow un-vetted scripts to run that _aren't_ part of a filter list but _do_ set cookies... if that makes sense?
