### ISSUE TITLE
za.zdn.vn

### ISSUE THREAD

**Issue by bigdargon** [easylist/easylist#14095]
https://github.com/bigdargon/hostsVN/issues/334

Can't access the app https://play.google.com/store/apps/details?id=vn.com.vng.zalopay&hl=vi&gl=US

Filter: EasyPrivacy

Affected Services: Adguard DNS, NextDNS

**Comment by ryanbr** [comment]
There is a Adguard github. https://github.com/AdguardTeam/AdguardFilters
