### ISSUE TITLE
http://www.livescience.com/ unblocked ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#141]
`http://www.livescience.com/39052-peacock-spider-mating-dance.html`

Sponsored by Revokerr plus Amazon ads.

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/9b4e88479886bc56ff504f909c8593aa97a41a7d

**Comment by terrorist96** [comment]
@monzta same deal as #134
