### ISSUE TITLE
incolumitas.com - Why did you list my blog on easylist_adservers.txt ?

### ISSUE THREAD

**Issue by NikolaiT** [easylist/easylist#14102]
### List the website(s) you're having issues:

`https://incolumitas.com/`

### What happens?

First of all, thanks for the awesome work, I used uBlock Origin for a long time.

I want to counterargue that my blog was listed on easylist/easylist_adservers.txt 

The reason why you probably blocked me, is that I provide a library that allows to detect uBlock Origin and Adblock Plus: https://incolumitas.com/pages/Adblock-Detection/ and also here https://github.com/NikolaiT/adblock-detect-javascript-only

I fully understand why you would want to block this library, since it allows to detect websites whether their clients are using an Adblocker or not.

By blocking my whole blog, the technique used in https://github.com/NikolaiT/adblock-detect-javascript-only **even works better**. The [base technique](https://github.com/NikolaiT/adblock-detect-javascript-only/blob/master/index.js) of the library is to try to load a remote JavaScript file that is usually blocked by adblockers (Such as https://incolumitas.com/data/yzfdmoan.js). If the request goes through, no adblocker is used. If not, an adblocker is used. By blocking my blog entirely, this technique continues to work! Therefore listing my blog is not helping your cause.

Furthermore, I never had advertisements on my blog ever. I am providing high quality content since 2012 for all kinds of people and I am publishing my software as open source. 

Can we find a solution? I am also willed to remove the adblock library from my blog, if that would help getting unblocked from your guys. A lot of people found value in my open source projects, I don't care that much about the adblock detection library.

Thanks!
Nikolai Tschacher

### List Subscriptions you're using:

Using all default subscriptions from uBlock Origin v1.44.4, including easylist

### Your settings

- OS/version: MacOS Monterey 12.6
- Browser/version: Chrome/107.0.0.0
- Adblock Extension/version: uBlock Origin v1.44.4

**Comment by ryanbr** [comment]
Sure, just remove the scripts being used and we'll adjust accordingly.

**Comment by NikolaiT** [comment]
Thanks for the reply.

I removed all baiting JavaScripts from my blog. Furthermore, I removed the link to the Adblock detection library on my blog (https://incolumitas.com/pages/Adblock-Detection/).

Does that look good to you?

**Comment by NikolaiT** [comment]
Is there anything I can do to resolve this?
