### ISSUE TITLE
alphr.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#14100]
### List the website(s) you're having issues:

`https://www.alphr.com/change-font-size-android/`

### What happens?

Some placeholders on article pages measured to 90x750px. Most articles have 2 or more such placeholders; the above example page has 3.

### List Subscriptions you're using:

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/201520844-8c9c9a82-3de9-49e7-94e9-75f33fd9c08c.png)

</details>

### Your settings

- OS/version: Windows 11 22H2 x64
- Browser/version: Chrome 107.0.5304.107 x64
- Adblock Extension/version: uBO 1.44.4 + IDCAC 3.4.4

### Other details:

I propose `alphr.com##.desktop-lazy-ads`, and possibly `alphr.com##.mobile-content-ads` if the placeholders also were to show up on phones (which I hadn't tested at the time of writing).

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/201521277-f6695766-2c91-46e1-ad31-f6a903f920ee.png)

</details>

**Comment by ryanbr** [comment]
easylist/easylist_general_hide.txt:##.desktop-lazy-ads ?

**Comment by DandelionSprout** [comment]
Oh, right. I saw only now that AdGuard Base had `@@||alphr.com^$generichide`. My fault.
