### ISSUE TITLE
vercel.com beacon [EasyPrivacy]

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#14158]
### List the website(s) you're having issues:

`https://vercel.com/`

Loads beacon: `vercel.com/api/jwt`

Note: This page breaks in Firefox with `beacon.enabled` set to `false` ([source](https://gitlab.com/librewolf-community/browser/source/-/issues/83)), which I've tried and confirmed.

**Comment by ryanbr** [comment]
What breaks? homepage loaded, menus works.

![vercell](https://user-images.githubusercontent.com/1659004/202828961-23c0261d-22ac-4e55-8cb3-5f170504b2ae.png)

**Comment by yokoffing** [comment]
That’s a Firefox pref.

But for our purposes: a beacon loads ‘vercel.com/api/jwt’

**Comment by liamengland1** [comment]
That's not tracking... it's just setting a harmless JWT cookie that is likely used for auth/other site functions .
![image](https://user-images.githubusercontent.com/16567977/202830663-670e72a3-9d03-4da1-a7f7-6d4bb276746a.png)
![image](https://user-images.githubusercontent.com/16567977/202830670-9e83b666-7693-4046-8b72-7b6684af9a39.png)
![image](https://user-images.githubusercontent.com/16567977/202830680-d863b109-6e91-457d-9823-411da2dfac11.png)

do not block, will probably break stuff.

**Comment by ryanbr** [comment]
I only test Browsers in their default settings, the moment a user decides to change chrome://flags or Firefox pref it's out of the scope here.

**Comment by yokoffing** [comment]
> a harmless JWT cookie

Thanks for checking
