### ISSUE TITLE
https://stream-us-east-1.getpublica.com

### ISSUE THREAD

**Issue by TKList** [easylist/easylist#14172]
### List the website(s) you're having issues:
`https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=53&live=1`

### What happens?
Stream is blocked

stream is being blocked when trying to play it

### List Subscriptions you're using:

Brave browser
### Your settings
Shields up (standard setting, not aggressive)

- OS/version: Windows 10
- Browser/version: Brave latest
- Adblock Extension/version: Brave browser

**Comment by ryanbr** [comment]
From where? which website source?  not a helpful ticket.

**Comment by TKList** [comment]
Here: https://watch.plex.tv/live-tv/channel/electric-now

**Comment by TKList** [comment]
Many streaming sites seem to using getpublica.com for some of their streams. They are blocked everywhere by Brave.

**Comment by TKList** [comment]
Thanks again @ryanbr
