### ISSUE TITLE
send.firefox.com - Missing elements

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#1417]
### List the website(s) you're having issues: 
https://send.firefox.com

### What happens?
After uploading a file, you are supposed to see a link under the "The link to your file will expire after X downloads or 24 hours.", but that isn't visible. The screenshot below shows what it should look like:

![](https://screenshotscdn.firefoxusercontent.com/images/fc9e6811-6357-4c06-884a-22f09020b07f.png)

And this one below shows what is currently happening:

![](https://screenshotscdn.firefoxusercontent.com/images/b18dc50c-873f-4393-9e86-0cb9039ded1a.png)

### List Subscriptions you're using:
uBlock Filters (all of them except annoyances and experimental)
Adblock Warning Removal List
AdGuard Base Filters
EasyList
AdGuard Spyware Filters
Fanboy’s Enhanced Tracking List
Malvertising filter list by Disconnect​​​​​
Malware domains
Spam404
Fanboy’s Annoyance List
Peter Lowe’s Ad and tracking server list

### Your settings
Default settings for uBlock Origin, except the filters I have enabled.

- OS/version: Windows 10 April Update
- Browser/version: Firefox Beta
- Adblock Extension/version: 1.16.10

### Other details:

I went through the logger and found `##.sharePage` being blocked in both the annoyance and social blocking lists. After looking up some syntax on filters, I found out that `#@#.sharePage` added into my custom filters fixes the issue.

**Comment by peace2000** [comment]
This issue seems not relevant anymore. I uploaded something random and experienced no problem. Logger does not even find an element that goes by name "sharePage" which means that the site has changed. @Khrin 

However it could wise to remove because it might give false positives. Of course specific whitelists could be always added.
