### ISSUE TITLE
adspyglass.com

### ISSUE THREAD

**Issue by Xabibylin** [easylist/easylist#14186]
**adspyglass.com**

### List the website(s) you're having issues:

 https://app.adspyglass.com/      https://adspyglass.com/

### What happens?

 The filter ||adspyglass.com^ blocks requests when accessing the same site.
This block disrupts functioning of the website by blocking all requests to CSS
, JS, fonts, and all XHR-requests required for normal usage.

### List Subscriptions you're using:

 -EasyList / easylist_adservers.txt

### Your settings

- OS/version: OS/version: Windows 10
- Browser/version: Chrome 88.0.4324.182
- Adblock Extension/version: Adblock Extension/version: ABP 4.28.5

### Other details:

 There are no ads from these domain

**Comment by Xabibylin** [comment]
Hello @ryanbr, we received from you earlier on a closed task
https://github.com/easylist/easylist/issues/7237 
 
but we still have questions about this, we believe that we should be excluded from the easylist, we do not have advertising banners on the website. Can you please tell us what evidence is required for the exclusion?

**Comment by barong66** [comment]
adspyglass.com is NOT an ad-serving domain. It's the landing page of our project, blog, knowledge base and etc.

**Comment by soundrussian** [comment]
Yeah, removing ads or annoying stuff is one thing, but completely hiding legit content by blocking the top level HTML tag is completely another. As far as I know, adspyglass.com is **the only** domain that got such treatment. I think it needs explanations.
