### ISSUE TITLE
 `ads3.xumo.com` is being blocked by Brave shields up. It's used on many streams that are used on multiple sites.

### ISSUE THREAD

**Issue by TKList** [easylist/easylist#14195]
### List the website(s) you're having issues:
`xumo.com`
`tklist.us`
`amagi.tv`
`amazonaws.com`
`2vnews.com`
`stingray.com`
`redbox.com`
and many more 
Right now it is only fixed on Redbox 

### What happens?
Streams stops working.

### List Subscriptions you're using:

Brave
### Your settings
regular shields up

- OS/version: Windows 10
- Browser/version: Brave/Latest
- Adblock Extension/version: Brave/Latest

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/14222
