### ISSUE TITLE
ftuapps.dev claims ad blocker installed but none is

### ISSUE THREAD

**Issue by 411621** [easylist/easylist#14193]
### List the website(s) you're having issues:
`ftuapps.dev`

### What happens?
Since over a week (11/09/22none my browser including freshly installed browsers cannot access ftuapps.dev.
I ran several virtual machines, with newly installed browsers, same problem.
the window gets darkened out in the red framed alert message pops up:

**Blocked because of at blocker
it seems that you are using some at blocker software which is preventing the page from fully loading.  Please white list this website or disable ad blocking software**

But I have not ad blocker installed! I uninstalled qBlock origin, same problem. Deleted any cookies, still same
Even if I disable my [ESET] antivirus completely [insane] the same error message occurs.
To me quite evidently it is is a site configuration problem.

### List Subscriptions you're using:

 uBlock Origin. Eeven when uninstalled or disabled, problem persists

### Your settings

- OS/version: Win 10.2311
- Browser/version: FF90 & up (107.0)
- Adblock Extension/version: uBlock Origin Eeven when uninstalled or disabled, problem persists

### Other details:
Screenshot

![FTU apps ad blocker message](https://user-images.githubusercontent.com/29167457/203138449-5c14f527-551b-4236-ac61-9280b11f6d20.jpg)

**Comment by Khrin** [comment]
> To me quite evidently it is is a site configuration problem.

If it's a problem with site itself, then you should get in touch with the site admin for a solution. Why asking here?

**Comment by Khrin** [comment]
Or alternatively, ask to someone from uBlock Origin if they can add a circumvention for this site. I don't really know how we can help you.
