### ISSUE TITLE
jiocinema.com

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#14215]
### List the website(s) you're having issues:

```
https://www.jiocinema.com/sports/football/videos/sad-to-see-cr7-go--rooney/0da669a06a9311ed97053962a14b81a0
```
Geo locked to India

### What happens?

Ad retargetting code & analytics aren't blocked

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/62358249/124452393-41884700-dd7e-11eb-9f76-7820fcee5844.png)

</details>

### Your settings

- OS/version: macOS 12.6
- Browser/version: Firefox 107.0
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:

```
https://collect.media.jio.com/postdata/event
https://mercury.akamaized.net/jioads/websdk/default/stablejc/jioAds.js?version=21.11.2022
https://mercury.akamaized.net/ai/gcp/adcap_25228_1000579_48134.json?ccb=3427829832
https://mercury.akamaized.net/cm/ge.gif?*lot of parameters*
https://mercury.akamaized.net/cm/gvi.gif?*lot of parameters*
https://mercury.akamaized.net/cm/ge.gif?*lot of parameters*
```

**Edit:** Blocking the ad loader script breaks the live stream player as it refused to load. So the workaround is to let the ad script load but block the further JSON payload containing the ad URLs to play. Video on demand player seems to be fine with the whole script blocked.

Suggested filters

```
||collect.media.jio.com^
||mercury.akamaized.net/ai/gcp/adcap_*
||mercury.akamaized.net/cm/*
```

The jio ads thing seems to be used exclusively with Jio/Reliance estates. Also saw it here, another Jio owned company.
```
https://www.ajio.com/
```

**Comment by emlimap** [comment]
```
https://www.jiocinema.com/sports/cricket/tournament/match/live---tata-ipl-2023-player-auction---english/5974a270813111edbfad4fe2f99026d3
```
CC @ghajini

Looks they updated the ad payload JSON url again.

```
https://mercury.akamaized.net/ai/adcap_27754_20917_75364.json?ccb=1863282182
```

Suggested filter.

```
||mercury.akamaized.net/ai/adcap_
```

**Comment by ghajini** [comment]
Hi @emlimap 
i can't reproduce the issue

**Comment by emlimap** [comment]
@ghajini It was for a live-streaming event so it might have finished by the time you took a look at it.

Seeing it on this link as well. It is a music video so should work when you get to look at it

```
https://www.jiocinema.com/watch/music/sarvam-thaala-mayam---full-video-song/2/2/35ea9ef02e0a11e9a5a2af167671d2d7/0/0
```

Also, this could be blocked as well. Seems to be telemetry reporting based on fingerprinting script it loads. Video still works with this being blocked

```
https://mercury.jio.com/delivery/mapi.php?5aed1321
```

```
||mercury.jio.com/delivery/mapi.php
or
||jio.com/delivery/mapi.php

**Comment by ghajini** [comment]
@emlimap 
do you still get ads with updated ublock origin filters?

**Comment by emlimap** [comment]
@ghajini Ublock origin filter seems to have taken care of it. Thanks for checking. Will close this.
