### ISSUE TITLE
https://www.welt.de/ [EasyList Cookie List]

### ISSUE THREAD

**Issue by vitaliemaldur** [easylist/easylist#14227]
### List the website(s) you're having issues:

https://www.welt.de/ 

### What happens?
Cookie popup visible. 

### List Subscriptions you're using:

`EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.6
Browser/version: Chrome 107
Adblock Extension/version: AdblockPlus

**Comment by ryanbr** [comment]
Test `||gdpr-tcfv2.sp-prod.net/wrappermessagingwithoutdetection.js$script,domain=welt.de`  Can be a problematic site.

**Comment by Khrin** [comment]
Videos won't start if the cookie notice is blocked.
