### ISSUE TITLE
usemodify.com

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#14228]
### List the website(s) you're having issues:

`https://usemodify.com/`

### What happens?

Website functionality is broken. `/scripts/cookies.js` ~> **EasyList Cookie**

[Gif](https://imgur.com/VJENF1A)

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome 107.0.5304.107
- Adblock Extension/version:  uBO 1.45.2

**Comment by dportvine** [comment]
@ryanbr

**Comment by dportvine** [comment]
@ryanbr 
you can fix it?

**Comment by dimisa-RUAdList** [comment]
@ryanbr

**Comment by dportvine** [comment]
Someone can solve this problem? Or is it not a problem?
@ryanbr, @Khrin
