### ISSUE TITLE
abema.tv

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#14236]
### List the website(s) you're having issues:

`https://abema.tv/`

### What happens?

Privacy Notice

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Fanboy’s Annoyance

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox Nightly 109
- Adblock Extension/version: uBO 1.45.3b7

### Other details:

![abema](https://user-images.githubusercontent.com/95879668/204057395-2c1da918-2b88-4e1a-97fb-28c34c7bc634.png)

**Comment by ryanbr** [comment]
Doesn't look blockable sorry @q1800
