### ISSUE TITLE
24tv.ua (Mobile UA)

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#14257]
### List the website(s) you're having issues:

`https://24tv.ua/teroristi-gotuyut-novi-udari-zelenskiy-zvernuvsya-do-ukrayintsiv_n2206462`

### What happens?

ads leftover `[id^=mobileBrandingPlace]`
<details>
<summary>Screen</summary>

![2022-11-27_225518](https://user-images.githubusercontent.com/111344219/204159240-71fd0b1e-fa9c-43a1-b164-3dab4a8eeed4.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome 107.0.5304.122
- Adblock Extension/version:  uBO 1.45.2

**Comment by Khrin** [comment]
_The goal of this repository is to block ads on English and International sites._ (From https://github.com/easylist/easylist)

This site doesn't seems to qualify as such.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/24abff30567a820be69ba376d52df3285c712b41
