### ISSUE TITLE
mydealz.de

### ISSUE THREAD

**Issue by terr72** [easylist/easylist#14258]
### List the website(s) you're having issues:

`mydealz.de`

### What happens?

1. Log in as registered user
2. Try using the three buttons on the top right (navDropDown in HTML source)
![mdbuttons](https://user-images.githubusercontent.com/23163919/204164863-c9e83afb-94ef-4bbb-b724-095b5d73c8b8.png)
3. Drop down menus should appear, but doesn't when the lists _Fanboy’s Annoyance_ or _Easylist Cookie_ are enabled.

### List Subscriptions you're using:

Fanboy’s Annoyance
Easylist Cookie

### Your settings

- OS/version: Linux
- Browser/version: FF 107.0
- Adblock Extension/version: uBlock Origin 1.45.2

**Comment by hadrienbecle** [comment]
The problematic line:

https://github.com/easylist/easylist/blob/683fe6db85439a036e4f4af889c5c87c12bf0745/easylist_cookie/easylist_cookie_specific_uBO.txt#L763

Same problem on other Pepper platforms (Pepper, Dealabs, etc.)

**Comment by d-Rickyy-b** [comment]
This issue also affects the "like" functionality.

The filter `mydealz.de##.vue-portal-target.popover-portal` blocks the popup. No idea why it landed in this filter list in the first place.

![grafik](https://user-images.githubusercontent.com/5798157/204663543-95936bff-2758-43b0-9b8a-0d75839d94f1.png)

**Comment by ryanbr** [comment]
Filter was removed.
