### ISSUE TITLE
anwb.nl

### ISSUE THREAD

**Issue by Jasperrr91** [easylist/easylist#14265]
### List the website(s) you're having issues:

`https://www.anwb.nl`

Account creation:
`https://www.anwb.nl/inlogaccount-aanmaken`

Forgotten password:
`https://www.anwb.nl/login-vergeten`

### What happens?
 
We have received a lot of complaints from users that were unable to create a new account, or to trigger the forgotten password dialogue. The webshop had also been down for a fair number of users (yet we managed to patch that). The issue at hand is that all of these applications are (older) Preact/React applications with a root div that has the classname `PONCHO-application`.

This classname is also used on the cookie banner as it is also an individual React application.Due to this cookie banner, the classname has been added to the filter. This causes a lot of these other important applications to also stop working.
 
We will be adding a unique ID to the cookie banner so that it can be individually targeted, but we would like to urgently request the removal of the block on the **generic** `.PONCHO-application` classname as it is causing us a lot of headaches. And we currently do not have the capacity to patch classnames in older applications without completely refactoring them.
 
### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Mac OS X 12.6
- Browser/version: Chrome Version 107.0.5304.110 (Official Build) (arm64)
- Adblock Extension/version: Ghostery 8.9.6

### Other details:

Offending filter is in `easylist_cookie_international_specific_hide:L904`

https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_international_specific_hide.txt#L904

**Comment by krystian3w** [comment]
Invalid link, any commit break possition of lines (also FOP can change position).

https://github.com/easylist/easylist/blob/638b7d3bc687c95edc040fcd0b1920000a0fd767/easylist_cookie/easylist_cookie_international_specific_hide.txt#L904

**Comment by Jasperrr91** [comment]
> Invalid link, any commit break possition of lines (also FOP can change position).
> 
> https://github.com/easylist/easylist/blob/638b7d3bc687c95edc040fcd0b1920000a0fd767/easylist_cookie/easylist_cookie_international_specific_hide.txt#L904

Thanks for linking the blob.

I do hope we do not have to wait for multiple commits before this issue can be resolved. The only reason this class has been banned is because there is a need to block the cookie banner, so we have added a unique identifier to the cookie banner so that can be targeted in isolation: `#TRCO-application`.

**Comment by Jasperrr91** [comment]
I have opened a PR that keeps the blocking of the cookie banner intact while unblocking our normal preact/react applications: https://github.com/easylist/easylist/pull/14270.

**Comment by krystian3w** [comment]
Should be closed in next week due list are frozen by CloudFlare in many localisations:

https://github.com/easylist/easylist/commit/b071be365b998a803a8690b3e1dc8384eae14073

https://github.com/uBlockOrigin/uBlock-issues/discussions/2340#discussioncomment-3971701
