### ISSUE TITLE
imore.com | Easylist, Fanboy Social, Fanboy Annoyance

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#14277]
### List the website(s) you're having issues:

`https://www.imore.com/apps/social-apps/twitters-no-longer-enforcing-its-own-covid-19-misinformation-policy`

### What happens?

- Ad placeholder filters needed (white space) (easylist)
- Newsletter box on right side (fanboy annoyance)
- Social icons on top of page and below subtitle (Fanboy social/annoyance)

![Screenshot 2022-11-30 at 16-07-58 Dummy Page](https://user-images.githubusercontent.com/11689349/204908265-a43266ad-bace-435f-8e5d-c4396f6527ba.png)

**Comment by krystian3w** [comment]
> Ad placeholder filters needed (white space) (easylist)

Not always.

**Comment by ryanbr** [comment]
No issues here.

**Comment by krystian3w** [comment]
@Yuki2718 / @mapx- / @okiehsch:
okiehsch I detected guilty is `uBo - Annoyances`:

![image](https://user-images.githubusercontent.com/35370833/207832333-00d85b1c-c5f7-4e1c-bcb9-764ed9eb50d7.png)

https://github.com/uBlockOrigin/uAssets/blob/099a2a261745b6b6f678546d8a04442a5f452dc6/filters/annoyances.txt#L1334-L1343
