### ISSUE TITLE
Add google analytics into easyprivacy allow list for Surfly's domains.

### ISSUE THREAD

**Issue by ypapouski** [easylist/easylist#14287]
### List the website(s) you're having issues:
app.surfly.com
app.surfly.online

### What happens?
Surfly application proxifies any web applications on the fly. When google.docs or slides app is proxified by Surfly then google analytics is blocked by EasyPrivacy rules.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:
Suggested rule to be added into the easyprivacy allow list is:
 @@||surfly.^*_analytics.js$domain=surfly.com|surfly.online

**Comment by krystian3w** [comment]
How works in uBlock Origin with redirect resources:

- [google-analytics_ga.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#google-analytics_gajs-)
- [google-analytics_analytics.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#google-analytics_analyticsjs-)
- [google-analytics_inpage_linkid.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#google-analytics_inpage_linkidjs-)
- [google-analytics_cx_api.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#google-analytics_cx_apijs-)
- [googletagservices_gpt.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#googletagservices_gptjs-)
- [googletagmanager_gtm.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#googletagmanager_gtmjs-)
- [googlesyndication_adsbygoogle.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#googlesyndication_adsbygooglejs-)

**Comment by ryanbr** [comment]
Seems bad for privacy to allow, it should be done on surfly's end

**Comment by ypapouski** [comment]
@ryanbr, I am sorry, but could you please be more specific and explain why the suggested rule is bad for privacy and the following rule which currently exists in the privacy allow list is good for privacy?
```txt
@@||nettix.fi^*_analytics.js$domain=nettiauto.com|nettikaravaani.com|nettikone.com|nettimokki.com|nettimoto.com|nettivaraosa.com
```
