### ISSUE TITLE
trueachievements.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#14280]
### List the website(s) you're having issues:

`https://www.trueachievements.com/game/McPixel-3/achievements`

### What happens?

Various placeholders in the achievement list measured to 90px tall each; the example page has 8 of them.

### List Subscriptions you're using:

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/204980248-33a2a871-54cc-44c3-9c73-9d8b0213b263.png)

</details>

### Your settings

- OS/version: Windows 11 22H2 x64
- Browser/version: Chrome 107.0.5304.123 x64
- Adblock Extension/version: uBO MV2 1.45.2 + IDCAC 3.4.4

### Other details:

I propose `trueachievements.com##.ad-center`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/204981028-c7c96998-1b53-4ae3-b9f1-3f926060f4c9.png)

</details>

**Comment by ryanbr** [comment]
We have `##.ad-center` already @DandelionSprout

**Comment by DandelionSprout** [comment]
Seems like you're correct, and that AdGuard Base has `@@||trueachievements.com^$generichide`. I thought I'd be better at this at noticing `$generichide` stuff in uBO's logger.
