### ISSUE TITLE
wtop.com slideshow broken

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#143]
http://wtop.com/dc/2016/09/capitol-hill-buzz-judge-merrick-garland-is-back-on-the-hill/

EasyPrivacy and EasyList both break the slideshow. It will let you go from slide 1 to slide 2, but then won't let you get to slide 3.
Seems to be related to Google Publisher Tags

**Comment by Khrin** [comment]
Fixed: https://github.com/easylist/easylist/commit/3c52e8abf92ac94c7aaf8fbc9553ce94afbf8bac

**Comment by terrorist96** [comment]
@Khrin thanks for trying! However, both EasyList and EasyPrivacy still break it for me on Chrome. I tested on a new profile with only ABP installed.

**Comment by terrorist96** [comment]
You whitelisted it under `Google Tag Manager`. That doesn't need to be whitelisted. `Google Publisher Tag` needs to be whitelisted.

**Comment by Khrin** [comment]
Sorry for the misunderstanding, now should be (finally) fixed: https://github.com/easylist/easylist/commit/cc3fabf8c10196a140a2e4782d858fc0c28687d9

**Comment by terrorist96** [comment]
Thanks! Any chance you could take a look at some of the other open issues on here when you have time? :innocent:
