### ISSUE TITLE
belhaber.be

### ISSUE THREAD

**Issue by kmnvq** [easylist/easylist#14308]
### List the website(s) you're having issues:

`https://belhaber.be/`
`https://www.airlinehaber.com/`

### What happens?

```
##.kanews-banner
##div[id^="kanews_widget_ads-"]
```

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/110184059/205479888-e4577609-dffa-4306-bc61-a6eca8f63011.png)

</details>

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/110184059/205479911-2920f8bd-954d-450e-b89e-3cb59f1628ad.png)

</details>

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Tracking Protection, uBO filters

### Your settings

- OS/version: 
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:

**Comment by ryanbr** [comment]
Non english site @kmnvq
