### ISSUE TITLE
instagram.com top bar is hidden

### ISSUE THREAD

**Issue by pierrre** [easylist/easylist#14304]
### List the website(s) you're having issues:

```
https://www.instagram.com/
```

### What happens?

The top menu bar is hidden.

### List Subscriptions you're using:

Fanboy’s Annoyance

If I enable it, it hides the top menu bar.

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome  108.0.5359.72
- Adblock Extension/version: uBlock Origin 1.45.2

**Comment by ryanbr** [comment]
![instagram](https://user-images.githubusercontent.com/1659004/205420879-b4049d72-c49b-4f59-9667-1b927a706d2e.png)

Enabled, and looks okay? Disabling and enabled shows no difference.

**Comment by pierrre** [comment]
That's very strange, because the instagram UI is completely different for me.
Instead of your menu on the left side, I've got a bar at the top.
It has been like that for years on all my computers.
I made sure that no other extension is currently enabled.
![instagram top bar](https://user-images.githubusercontent.com/131535/205440544-6dbf965f-19ef-4a9a-bfca-aa9b0fbd94f3.png)

**Comment by pierrre** [comment]
PS: and if you Google "instagram web", and search for images, you will see that most people have the same menu as me.

**Comment by pierrre** [comment]
Hoooo, it seems to have changed recently, but I don't see the change.
```
https://www.engadget.com/instagram-on-the-web-has-been-redesigned-for-large-screens-074726015.html
```
I cleared the cache, but there is no difference.

**Comment by ryanbr** [comment]
Look at the filters being used and debug, otherwise nothing will be fixed

**Comment by pierrre** [comment]
Sorry, it's my first time debugging an issue with an adblocker, so I don't know exactly what to do.
I opened the logger, and was able to see that a cosmetic rule from the Fanboy's annoyance list is applied.
```
instagram.com##footer[class] + [class]:last-child
```
![Capture d’écran du 2022-12-09 10-24-29](https://user-images.githubusercontent.com/131535/206669478-e3fdab6d-09e2-4985-8f06-bf43241ad972.png)
I don't see any other cosmetic filter/rule applied from the same list, so I assume it's the cause of my issue.
I don't know how to disable a specific rule, so I don't know how to test.

**Comment by krystian3w** [comment]
```adb
#@#footer[class] + [class]:last-child
```
