### ISSUE TITLE
[NSFW]gayporntube.net anti adblock

### ISSUE THREAD

**Issue by gototheskinny** [easylist/easylist#14325]
[https://www.gayporntube.net](https://www.gayporntube.net)
iPhone 12 with iOS 15.0 Safari, AdGuard for ios pro, easylist filters enabled including adblock warning filter.

**Comment by krystian3w** [comment]
Incorrect place to report anti-adblock.

**Comment by gototheskinny** [comment]
> Incorrect place to report anti-adblock.

I reported here bc of this:
![image](https://user-images.githubusercontent.com/51786709/207765520-b3d21fc8-7564-40ef-bba0-b481a2f1d2e3.jpeg)

**Comment by Khrin** [comment]
> Incorrect place to report anti-adblock.

Exactly.

**Comment by gototheskinny** [comment]
> > Incorrect place to report anti-adblock.
> 
> 
> 
> Exactly.

What do you guys exactly meant when you guys said "adult sites is included"?
![image](https://user-images.githubusercontent.com/51786709/208052422-c27e1d6f-d253-4de7-8bbc-4a6c024d0f1c.jpeg)

**Comment by krystian3w** [comment]
For uBo here: https://github.com/uBlockOrigin/uAssets/issue

ABP users have only:

```adb
!
! Please report any unblocked obtrusive anti adblock messages or problems
! in the forums (https://forums.lanik.us/) or via e-mail (easylist.subscription+anti@gmail.com).
! Please check our guidelines before reporting: https://easylist.to/2013/05/10/anti-adblock-guide-for-site-admins
!
```

**Comment by gototheskinny** [comment]
> https://easylist.to/2013/05/10/anti-adblock-guide-for-site-admins

OK thank you for your response.
