### ISSUE TITLE
Ads is still showing at the beginning of youtube videos

### ISSUE THREAD

**Issue by tn1997tn** [easylist/easylist#14330]
### List the website(s) you're having issues:

Youtube.com

### What happens?

Ads is still showing at the beginning of the video in full length just like on TV, have to wait to click to skip it just like on TV. The waiting time is not any shorter than on TV. Very luckily during the video playback there is no ads like on TV.

### List Subscriptions you're using:

Fanboy Ultimate

### Your settings

- OS/version: Windows 10
- Browser/version: Brave latest
- Adblock Extension/version: Brave latest

### Other details:

This wiki not work: https://github.com/easylist/easylist/wiki/Youtube-Issues

**Comment by ryanbr** [comment]
We'll move it too the https://github.com/brave/brave-browser/issues/27228
