### ISSUE TITLE
edeka.de [Easylist Cookie]

### ISSUE THREAD

**Issue by spodermenpls** [easylist/easylist#14333]
### List the website(s) you're having issues:

`https://www.edeka.de/gewinnspiele/aktuelle-gewinnspiele/adventskalender/adventskalender.jsp`
### What happens?
Easylist Cookie makes uBlock hide the otherwise appearing "Datenschutz-Einstellungen" popup (= "Privacy Settings"), whilst keeping the scroll lock intact. Due to the very granular nature of said privacy settings (individual consent switches for Youtube, Captchas, Facebook, Cookies etc, behind the "Einstellungen"/"Settings" button), it should be excluded from getting hidden. The specific site above for example requires the consent to usage of Captchas, which can't be given without this privacy setting popup/panel, making the usage of the subsequent form and submittal of its contents impossible at the current time.

### List Subscriptions you're using:

uBlock filter family
Peter Lowe's list
Adguard Base, Tracking, Annoyances, German
Easylist, Easylist German
Easylist Cookie

### Your settings

- OS/version: Windows 10 Pro
- Browser/version: Firefox 108.0 64-bit
- Adblock Extension/version: uBlock Origin 1.45.2, uMatrix 1.4.4

### Other details:

Easylist Cookie's generic filter rules currently hiding the needed privacy setting popup: `#popin_tc_privacy`, `#tc-privacy-wrapper`, `.tc-privacy-banner`, `.tc-privacy-overlay`.

**Comment by spodermenpls** [comment]
> I have a scrollbar here on `https://www.edeka.de/gewinnspiele/aktuelle-gewinnspiele/adventskalender/adventskalender.jsp` @spodermenpls

The scrollbar is just a side note, the main point is that the site is not fully usable without access to the privacy panel. @ryanbr

**Comment by ryanbr** [comment]
Erm, Whats the exact issue? I don't visit a site to view its privacy settings. Is the actual site broken, the part that is usable.

**Comment by spodermenpls** [comment]
> Erm, Whats the exact issue? I don't visit a site to view its privacy settings. Is the actual site broken?, is there a part that is unusable.

If you visit the URL I mentioned, and click on today's number of day ("12", for instance), you will be seeing this (at least with a German IP address, since it's a German merchant chain's website): 
![Screenshot 2022-12-12 at 16-37-46 EDEKA Adventskalender Tagespreis](https://user-images.githubusercontent.com/23747593/207088629-4545adaf-b907-4871-82b3-c3bd1276780b.png)

Since the "first contact" privacy panel gets hidden by Easylist Cookie, the site requests to confirm the consent for using Recaptcha for the form, and offers "Aktivieren" (="Activate") to open the settings panel manually. On my end, the "Aktivieren" button is clickable, but nothing opens - the form underneath stays locked and unusable. Is it the same on your end? @ryanbr

**Comment by ryanbr** [comment]
`@@||cdn.trustcommander.net/privacy/$script,domain=edeka.de`

Does that help? If you had a step-by-step way to reproduce the issue would've helped. On the face of it, the page loads fine.

**Comment by spodermenpls** [comment]
> `@@||cdn.trustcommander.net/privacy/$script,domain=edeka.de`
> 
> Does that help? If you had a step-by-step way to reproduce the issue would've helped. On the face of it, the page loads fine.

Yeah, I'm sorry, I thought this was a lot more of a slam dunk than it turned out to be. 
From what I could figure out, the "Activate" button only works if `tagcommander.com` is excluded from filtering first, since it is on EasyPrivacy (and therefore Adguard Tracking, which I use) and Peter Lowe's domain list (specifically: @@||cdn.tagcommander.com/5030/tc_DigitalesMarketingAP053028_22.js$script,domain=www.edeka.de` , which only then allows `trustcommander.net` (when @@-ed with the rule you mentioned above) for the privacy settings to load, which are then hidden by Easylist Cookie's generic rules I mentioned under "Other details" in my initial post. @ryanbr

**Comment by ryanbr** [comment]
I'm not seeing this. https://github.com/easylist/easylist/commit/a0b07370ff350583e4583a69e3e41b66dd2dd05a may help. But unless proper troubleshooting/testing I won't address this further.
