### ISSUE TITLE
FedScoop (Easylist)

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#14339]
### List the website(s) you're having issues:

`https://www.fedscoop.com/`

### What happens?
![Screenshot 2022-12-06 at 12-55-27 Homepage - FedScoop](https://user-images.githubusercontent.com/11689349/205986147-c2962703-55c6-4a9c-9208-469d2d3a354d.png)

**Comment by ryanbr** [comment]
No blockable in EL
