### ISSUE TITLE
[EasyPrivacy] cgv.vn

### ISSUE THREAD

**Issue by bigdargon** [easylist/easylist#14338]
### List the website(s) you're having issues:

https://www.cgv.vn

### What happens?

Can't choose seats when booking

Allow domain name `netcoresmartech.com` will work

Steps:
1. Login account
2. Choose to book movie tickets
3. Select date and time
4. Can't choose a seat at the seat selection page

### List Subscriptions you're using:

uBlock filter
Easylist
EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox
- Adblock Extension/version: uBlock

### Other details:

![Screenshot 2022-12-06 at 21-47-51 Booking](https://user-images.githubusercontent.com/10969626/205943677-712017b6-0e11-45c8-b384-1d98f6458518.png)

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +101 |  |  | 20d79263-d71d-40f7-b0e0-20d0f9d5e4aa.moz-extension-scheme | 0,3 | xhr | `https://ublockorigin.github.io/uAssetsCDN/filters/filters-2022.txt` |
| +101 |  |  | 20d79263-d71d-40f7-b0e0-20d0f9d5e4aa.moz-extension-scheme | 0,3 | xhr | `https://ublockorigin.github.io/uAssetsCDN/filters/filters-2021.txt` |
| +101 |  |  | 20d79263-d71d-40f7-b0e0-20d0f9d5e4aa.moz-extension-scheme | 0,3 | xhr | `https://ublockorigin.github.io/uAssetsCDN/filters/filters-2020.txt` |
| +100 |  |  | 20d79263-d71d-40f7-b0e0-20d0f9d5e4aa.moz-extension-scheme | 0,3 | xhr | `https://ublockorigin.github.io/uAssetsCDN/filters/filters.txt` |
| +96 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/favicon/default/cgvcinemas-vietnam-favicon.ico` |
| +95 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/skin/frontend/cgv/default/images/bg-cgv/bg-bottom-seatmap.png` |
| +95 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/skin/frontend/cgv/default/images/bg-cgv/icon-info-combo.png` |
| +95 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/skin/frontend/cgv/default/images/bg-cgv/bg-cgv-button-process.png` |
| +95 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/skin/frontend/cgv/default/images/bg-cgv/bg-top-seatmap.png` |
| +95 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/skin/frontend/cgv/default/images/bg-cgv/bg-screen.png` |
| +94 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/wysiwyg/2019/AUG/kenhcine.gif` |
| +94 | /www/delivery/* | -- | `www.cgv.vn` | 1 | script | `https://advserver.cgv.vn/www/delivery/ajs.php?zoneid=2&cb=66479572231&charset=UTF-8&loc=https%3A//www.cgv.vn/en/cinemas/booking/tickets/site/038/seq/7644587/dy/20221206&referer=https%3A//www.cgv.vn/en/%3F___from_store%3Ddefault` |
| +94 | google-analytics.com/ga.js | << | `www.cgv.vn` | 3 | script | `https://ssl.google-analytics.com/ga.js` |
| +94 | \|\|google-analytics.com/ga.js$script,redirect-rule=google-analytics.com/ga.js:5 | -- | `www.cgv.vn` | 3 | script | `https://ssl.google-analytics.com/ga.js` |
| +94 | \|\|google-analytics.com/ga.js$script,redirect-rule=google-analytics_ga.js,domain=~daj.jp | -- | `www.cgv.vn` | 3 | script | `https://ssl.google-analytics.com/ga.js` |
| +94 | \|\|google-analytics.com^ | -- | `www.cgv.vn` | 3 | script | `https://ssl.google-analytics.com/ga.js` |
| +94 | /120x600_ | -- | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/wysiwyg/2022/112022/120x600_.png` |
| +94 | \|\|netcoresmartech.com^$3p | -- | `www.cgv.vn` | 3 | script | `https://cdnt.netcoresmartech.com/smartechclient.js` |
| +94 | googletagmanager_gtm.js | << | `www.cgv.vn` | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-MSDTZ2C` |
| +94 | \|\|googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | `www.cgv.vn` | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-MSDTZ2C` |
| +94 | \|\|googletagmanager.com^ | -- | `www.cgv.vn` | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-MSDTZ2C` |
| +94 | google-analytics.com/analytics.js | << | `www.cgv.vn` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +94 | \|\|google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js:5 | -- | `www.cgv.vn` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +94 | \|\|google-analytics.com/analytics.js$script,redirect-rule=google-analytics_analytics.js,domain=~banki.ru\|~bigc.co.th\|~olx.* | -- | `www.cgv.vn` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +94 | \|\|google-analytics.com^ | -- | `www.cgv.vn` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +94 | /google/ga.js | -- | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/google/ga.js` |
| +94 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/catalog/product/cache/3/thumbnail/dc33889b0f8b5da88052ef70de32f1cb/t/r/tro_t_n_r_c_r__poster_ch_nh_th_c_1_.jpg` |
| +94 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/concession/web/625f7aace684c_1650424493.png` |
| +94 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/concession/web/625f7a6cbe151_1650424429.png` |
| +94 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/concession/web/63648762bc32b_1667532643.png` |
| +94 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/concession/web/6364866d90d3f_1667532398.png` |
| +93 |  |  | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/concession/web/62fe077bd978b_1660815228.png` |
| +93 | /120x600_ | -- | `www.cgv.vn` | 1 | image | `https://www.cgv.vn/media/wysiwyg/2022/112022/120x600_.png` |
| +93 |  |  | `www.cgv.vn` | 3 | script | `https://www.gstatic.com/firebasejs/8.2.1/firebase-messaging.js` |
| +93 |  |  | `www.cgv.vn` | 3 | script | `https://www.gstatic.com/firebasejs/8.2.1/firebase-app.js` |
| +93 | \|\|netcoresmartech.com^$3p | -- | `www.cgv.vn` | 3 | script | `https://cdnt.netcoresmartech.com/smartechclient.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/enterprise/js/enterprise/wishlist.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/enterprise/js/enterprise/catalogevent.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/jquery.colorbox.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/minicart.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/enterprise/js/scripts.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/lib/imagesloaded.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/slideshow.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/lib/jquery.cycle2.carousel.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/lib/jquery.cycle2.swipe.min.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/lib/jquery.cycle2.min.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/app.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/cgv.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/lib/enquire.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/lib/matchMedia.addListener.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/lib/matchMedia.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/lib/selectivizr.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/skin/frontend/cgv/default/js/lib/modernizr.custom.min.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/varien/weee.js` |
| +93 | /google/ga.js | -- | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/google/ga.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/mage/cookies.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/mage/translate.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/varien/form.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/varien/js.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/scriptaculous/slider.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/scriptaculous/controls.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/scriptaculous/dragdrop.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/scriptaculous/effects.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/scriptaculous/builder.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/prototype/validation.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/lib/ccard.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/lib/jquery/noconflict.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/lib/jquery/jquery-1.10.2.min.js` |
| +93 |  |  | `www.cgv.vn` | 1 | script | `https://www.cgv.vn/js/prototype/prototype.js` |
| +91 |  |  | `www.cgv.vn` | 1 | doc | `https://www.cgv.vn/en/cinemas/booking/tickets/site/038/seq/7644587/dy/20221206` |
</details>

**Comment by ryanbr** [comment]
`This site can’t be reachedwww.cgv.vn took too long to respond.`

**Comment by bigdargon** [comment]
CGV is a big cinema in Vietnam, maybe they block access outside of Vietnam.  I can still access it normally.

![A27F0E60-30EB-4194-9FDE-D67B2F6E84C0](https://user-images.githubusercontent.com/10969626/208213417-2d9ede42-9a17-4872-ab9c-4aee3dad0cb4.png)

**Comment by ryanbr** [comment]
You need to investigate the specific script causing the issue, otherwise it won't be fixed. @bigdargon  Even with my Vietnam vpn, I couldn't get access to the site.

**Comment by bigdargon** [comment]
@ryanbr I will do a screen recording, before and after turning easyprivacy on and off.  And attach log again and screen video!

**Comment by bigdargon** [comment]
@ryanbr Screen recording https://youtu.be/iWaKEKmz8Hw

**Comment by ryanbr** [comment]
Maybe adding as a filter; `@@||netcoresmartech.com/smartechclient.js$domain=cgv.vn` ?

**Comment by bigdargon** [comment]
@ryanbr Rule `@@||netcoresmartech.com/smartechclient.js$domain=cgv.vn` works

![Screenshot 2022-12-20 at 09-18-16 Mua vé](https://user-images.githubusercontent.com/10969626/208565630-2e54967e-3fd9-414b-a833-82f0d3968162.png)
