### ISSUE TITLE
Google analytic request with an additional query parameter is blocked.

### ISSUE THREAD

**Issue by ypapouski** [easylist/easylist#14335]
### List the website(s) you're having issues:
app.surfly.com
app.surfly.online

### What happens?

The following google analytics' request `https://docs.google.com/static/document/client/js/984116395-client_js_prod_kix_analytics.js?SURFLY=S` is blocked. It happens because of the following rule `_Analytics.js?` located in `https://easylist-downloads.adblockplus.org/easyprivacy.txt.`

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

Suggested exemption rule:
`_Analytics.js?SURFLY=`
Can this rule be added into easy privacy allow list?

**Comment by ryanbr** [comment]
Creating a document with generic anaylitics blocks? The link to the actual document?

**Comment by ypapouski** [comment]
Sure, let me provide a few screenshots.
1. Any google document can be used, for example:
![image](https://user-images.githubusercontent.com/6194601/206499184-1af3e807-a0ca-40fc-970f-39098fc36f53.png)
The analytics.js request is not blocked because it was executed w/o any query params.
2. The same google document is executed in Surfly.
![image](https://user-images.githubusercontent.com/6194601/206501073-76832a7c-1373-4c91-9f51-4dc7d153c0b9.png)
![image](https://user-images.githubusercontent.com/6194601/206501288-300d5fc5-d4ea-4ed3-8841-d5203a8f6c5b.png)
...client_js_prod_kix_analytics.js?SURFLY=S requests are blocked
3. If a query param is removed then the request is not blocked.
![image](https://user-images.githubusercontent.com/6194601/206501977-ae48ec88-6bef-4054-adf3-3a881f15eafe.png)

**Comment by ryanbr** [comment]
We're not blocking it. I see it, but you're adding the "SURFLY" bits.

By itself, `https://docs.google.com/static/document/client/js/692441661-client_js_prod_kix_analytics.js`  has nothing after it.

**Comment by ypapouski** [comment]
Yes, the request itself `https://docs.google.com/static/document/client/js/692441661-client_js_prod_kix_analytics.js` is not blocked, but the same request executed from Surfly is blocked and yes, it's because, an additional query parameter is added.
Therefore I suggested to add an exemption rule such as `_Analytics.js?SURFLY=` into the easy privacy allow list.
Can it be done?

**Comment by krystian3w** [comment]
in uBo/AdGuard try add:

```adb
$removepraram=SURFLY
```

**Comment by ryanbr** [comment]
They're inserting the parms, then asking us to fix it. Makes no sense.

**Comment by ypapouski** [comment]
@ryanbr 
> They're inserting the parms, then asking us to fix it. Makes no sense.

Well, the AdBlock Chrome extension uses EasyPrivacy filter. This filter was created by you if I am not mistaken and located in this repository. Also this filter consists of two parts: a white and a black lists. The black list blocks all specified URLs, but the white list has the rules which will override rules from the black list. Am I right on this?

Yes, we add additional parameters into a request, because, well, it's not a crime, it's possible to do and we need to add them and because of that it had a lot of sense to me to come to you and ask you to add a specific rule for us. Wasn't the Easy Privacy Allow List created for?

<img width="912" alt="Screenshot 2022-12-13 at 19 33 25" src="https://user-images.githubusercontent.com/6194601/207417849-58dd31f1-249e-4962-897c-6671d40ecdd4.png">

**Comment by krystian3w** [comment]
I suppose his is not origin of father / grand-grand-father.

**Comment by ryanbr** [comment]
> Yes, we add additional parameters into a request, because, well, it's not a crime,

Not a "crime" but if adding is anything to filters. This should not be addressed in the list. If the addition params is causing the issue, this should be fixed by the scripts changing it. 

We look at the list as a standalone product. If scripts modify anything and create param bugs, it should be fixed in the scripts.

**Comment by ypapouski** [comment]
@ryanbr, may I ask you the following?
The rule `_Analytics.js?` from the easy privacy list, based on which criteria was it constructed? Isn’t this rule too broad? Can we be sure that this rule will block correct URLs in 100%? What happens if Google will add an additional parameter to its analytic request in future?
