### ISSUE TITLE
mygov-portal.me

### ISSUE THREAD

**Issue by matthewbarram** [easylist/easylist#14352]
This site should be added to block list. 

### List the website(s) you're having issues:

'''mygov-portal.me/ret/637ae08b307d8'''

### What happens?

This is a redirect from a spam SMS. 
![26430FE6-8ABC-4236-BAB0-E4F3F6F56458](https://user-images.githubusercontent.com/5846639/206544396-d9deaacb-4a36-413d-a99f-4f41a0fad4b1.png)

**Comment by ryanbr** [comment]
Should be reported to safe search/malware domains? @matthewbarram

**Comment by matthewbarram** [comment]
@ryanbr - I reported it to google as a phishing domain. It may also contain malware for sure.

**Comment by Khrin** [comment]
@matthewbarram EasyList doesn't block malware domains.
