### ISSUE TITLE
filen.io

### ISSUE THREAD

**Issue by jcperil** [easylist/easylist#14356]
### List the website(s) you're having issues:

`https://filen.io`

### What happens?
Cookie consent notice appears

### List Subscriptions you're using:

Easylist-Cookie List - Filter Obtrusive Cookie Notices
### Your settings

- OS/version: 12
- Browser/version: Brave
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Already blocked @jcperil ?

**Comment by jcperil** [comment]
![filen io](https://user-images.githubusercontent.com/89805719/206836232-f4cf430c-fae9-4b87-938a-ddbb0f9fd9a7.jpg)

**Comment by ryanbr** [comment]
Lets check in the 24hrs.
