### ISSUE TITLE
vlcdownloads.com

### ISSUE THREAD

**Issue by User6751** [easylist/easylist#14379]
### List the website(s) you're having issues:
`vlcdownloads.com`

### What happens?
wsbsite contain malware

### List Subscriptions you're using:
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list
CHN: AdGuard Chinese 

### Your settings

- OS/version: Android 10
- Browser/version: Firefox Mobile 107.2.0
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:
https://twitter.com/videolan/status/1595524698351230981
https://twitter.com/fcartegnie/status/1597252461773074434

**Comment by ryanbr** [comment]
Submit to google safe search
