### ISSUE TITLE
Override for /icon-rss- in Fanboy's Annoyances

### ISSUE THREAD

**Issue by v1gnesh** [easylist/easylist#14388]
Hello,

SIncere thanks to the contributors for your efforts to help keep the internet sane.

Can you please show me how I can override the blocking of RSS-related icons/elements from sites.
Ex: In the below site, I want the RSS feed to be visible.

https://www.elastic.co/blog/universal-profiling-frame-pointers-symbols-ebpf

Thanks!

**Comment by krystian3w** [comment]
Need manually many exceptions like:

```adb
#@#.icon-rss
```

but for now I see icon in header, so where also are hidden?

**Comment by krystian3w** [comment]
maybe possible hide whole:

```adb
##.social-media-card-author
```

if print button is use less (Ctrl + P / Command + P).

**Comment by THEtomaso** [comment]
> `@@/icon-rss-$image`

..or if you want the override to be site-specific:
`@@/icon-rss-$domain=elastic.co`

More domains can be added to the same override rule, like this:
`@@/icon-rss-$domain=elastic.co|somesite.example|someothersite.example`

PS:
The `$image` parameter isn't really necessary in this case, but it can be included like this:
`@@/icon-rss-$image,domain=elastic.co|somesite.example|someothersite.example`

**Comment by krystian3w** [comment]
Worse if `/icon-rss-` now cover some unnecessary javascript.

**Comment by THEtomaso** [comment]
Sounds highly improbable.
..but if such a script is indeed "unnecessary", as you say, then why not block it? :)

**Comment by v1gnesh** [comment]
Is it possible to split out RSS-related blocks from annoyances into annoyances-rss, so I can de-select the list altogether?
Don't want to discover a site's RSS is broken/hidden, and then unbreak each type manually.

**Comment by ryanbr** [comment]
nope, not another list.

**Comment by v1gnesh** [comment]
Okay, cheers.
Thanks to everyone who responded here and for your continued work to make the web tolerable for everyone :)
