### ISSUE TITLE
Blocked Content on Homedepot.com

### ISSUE THREAD

**Issue by gammasynchrony2** [easylist/easylist#14398]
### List the website(s) you're having issues:
` https://www.homedepot.com/s/desk%20lamp?NCNI-5`

### What happens?
When a user navigates to this page with an ad blocker utilizing EasyList, the search results for the user's query are suppressed.

### List Subscriptions you're using:
This has been observed using UBlock and Adblock Plus, though it may apply to any ad blockers utilizing EasyList

### Your settings
No abnormal settings were applied other than having the ad blocker active.

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

I wish to contest the designation of the targeted areas as "ads". These product listings are not 3rd-party advertisements, but are actual products in our normal inventory whose vendors have incentivized us to feature them more prominently in our search results. To see that is the case, you can click on one of these products and note that fulfillment is handled through our stores and distributions centers and not a 3rd party. So strictly speaking, they’re no more “ads” than any of the other products on that page. Further, the products in question are products that directly correspond to a user's search query, and are products that a user would reasonably expect to see in their search results. 

If, on reflection, you disagree with my characterization of these product pods as non-ads, I would at least ask that a query selector be used that is more discriminating in its application. Right now, the ad blockers I mentioned above are removing ALL search results on the page and not just the ones with a `sponsored` indication. Given that this page results from a user's search for keyword-matching products, it would not be beneficial (or expected) from a customer's perspective to have all the results of their search removed from the page they requested. 

Than you for your time and consideration, and please let me know if I can offer any further clarifications!

-Stephen Anderson
The Home Depot

**Comment by ryanbr** [comment]
Came from https://github.com/easylist/easylist/pull/14151 cc: @eporubin

**Comment by krystian3w** [comment]
Other stores usually load the item in the list twice for such an occasion.

Unlocking may entail not ticking amazon and ebay (these daily checking ABP Filters).

**Comment by eporubin** [comment]
Hi 
I have looked again into this issue and it seems like the products are loaded twice on the Homedepot too. (For example in the video I have disabled ABP and looked for blower and as we can see in the video when I enabled the ABP back and searched for that exactly product which was first once it was sponsored it was shown to me) 
https://imgur.com/a/MU8JRpD

**Comment by gammasynchrony2** [comment]
@eporubin I agree that this is the case! One of my contentions is that it's counterintuitive to discuss these product pods as "ads" precisely because they are items in our inventory and not products being added to our site externally. However, I do understand that your users are seeking a certain kind of browsing experience, and if you believe that these product pods are inconsistent with that experience, your expertise puts you in a better position to make that determination.

What I am more strongly objecting to (and hope that you also see as undesirable blocking behavior) is the scenario depicted in the link below. Here, turning on the ad blocker is removing ALL of the search results for the user's query and not just the ones with the `Sponsored` designation. This was recorded on a Mac running Google Chrome:
https://imgur.com/a/5P9TM6k

**Comment by krystian3w** [comment]
This can be bug in crap addon:

[BEWARE! uBO is (and has always been) COMPLETELY UNRELATED to the website ublock.org](https://github.com/gorhill/uBlock/wiki/uBlock-Origin-is-completely-unrelated-to-the-web-site-ublock.org).
