### ISSUE TITLE
atelier801.com

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#14396]
Cookie bar:

```adb
atelier801.com###cookie-bar
```

No possible use: `atelier801.com###cookie-bar ~ .modal-backdrop`, because simple hide block pop-ups to:
- change avatar ("invalid file format")
- change nick (13-24 € if we don't have very old account with hashtag "`#0000`")
- remove avatar (need accept removing in pop-up - sic!)

**Comment by ryanbr** [comment]
Not seeing a popup here, `##div#cookie-bar` blocks it.
