### ISSUE TITLE
freewebstore.com

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#14428]
### List the website(s) you're having issues:

`https://freewebstore.com/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Fanboy's Annoyance List

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 108.0.1
- Adblock Extension/version: uBO 1.45.3rc5

### Other details:

![freewebstore](https://user-images.githubusercontent.com/95879668/208270868-554bed5e-f507-4360-b79b-248ef1ba6ad2.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c5e817877cc80e710a4091759788b23e364cb8a9
