### ISSUE TITLE
AdventureGameHotspot.com - Login blocked (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#14455]
### Affected site:
`https://adventuregamehotspot.com/`

### Issue:
Login blocked @ `https://adventuregamehotspot.com/login/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **Fanboy's Annoyance List**

### Problem rule:
`##.et_pb_newsletter`

### Possible fix:
```
- ##.et_pb_newsletter
+ ##.et_pb_newsletter:not(.et_pb_login_0):not(.et_pb_login)
```

### Temp fix:
`adventuregamehotspot.com#@#.et_pb_newsletter`

--

### System info:
* OS/version: Windows 10 Pro 21H2 (x64)
* Browser/version: LibreWolf v108.0.1-1 (x64) (Tracking Protection = Standard)
* Adblock Extension/version: uBlock Origin v1.45.2

**Comment by krystian3w** [comment]
```adb
##.et_pb_newsletter:not(.et_pb_login_0):not(.et_pb_login)
```
