### ISSUE TITLE
blog.avast.com

### ISSUE THREAD

**Issue by User6751** [easylist/easylist#14454]
### List the website(s) you're having issues:
`https://blog.avast.com`

### What happens?
avast one ad

### List Subscriptions you're using:
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
EasyPrivacy
Online Malicious URL Blocklist
Phishing URL Blocklist
PUP Domains Blocklist
Fanboy’s Annoyance
uBlock filters – Annoyances
EasyList China

### Your settings

- OS/version: Android 10
- Browser/version:Firefox Mobile 108.1.0
- Adblock Extension/version: uBlock Origin 1.45.2

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/138070

**Comment by Alex-302** [comment]
@ryanbr This is their own promo. Better to annoyances.

**Comment by krystian3w** [comment]
But mission failed, issue was closed, commits no arrive to public place from "AdGuard" disk drive/github.dev env.

**Comment by Alex-302** [comment]
Added to Annoyances
