### ISSUE TITLE
Roxy sites - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#14467]
### Affected sites:
```
https://www.roxy.fi/
https://www.roxy.fr/
https://www.roxy-denmark.dk/ 
https://www.roxy-ireland.ie/
https://www.roxy-store.se/
https://www.roxy-uk.co.uk/
```

### Issue:
Modal overlay / missing scrollbar

### Screenshots:
Not needed, as the problem is obvious.

### Problem filter:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
`##div.cookie-popup`
`##div#cookie-popup`

### Possible fix:
```
roxy.fi,roxy.fr,roxy-denmark.dk,roxy-ireland.ie,roxy-store.se,roxy-uk.co.uk#@#div.cookie-popup
roxy.fi,roxy.fr,roxy-denmark.dk,roxy-ireland.ie,roxy-store.se,roxy-uk.co.uk#@#div#cookie-popup
```
PS:
Blocking the modal overlay, with an additional stylesheet overflow rule, doesn't seem to work in this case, as it results in broken functions (e.g. the shopping cart can't be opened)!

### Other problem filters:
* **AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/138002/
`###cookie-popup`
`##.cookie-popup:not(body):not(html)`

* **I don't care about cookies** (@kiboke)
`~adtipp.de,~handelsregister.de,~bk.com###cookie-popup`
`~bintercanarias.com##.ui-widget[aria-labelledby*="cookie"]`
`~ejot.de,~ejot.at,~ejot.cn,~ejot.co.uk,~goteborg.com,~openreach.com,~argenta.be##.cookie-popup:not(body):not(html):not(#colorbox):not(.ant-modal-wrap)`

--

### System info:
* OS/version: Windows 10 Pro 21H2 (x64)
* Browser/version: LibreWolf v108.0.1-1 (x64) (Tracking Protection = Standard)
* Adblock Extension/version: uBlock Origin v1.45.2

**Comment by kiboke** [comment]
Thanks for letting me know @THEtomaso 
No need for exceptions. IDCAC will block the `/category-assets/experiences/recurring/cookies` script.

**Comment by THEtomaso** [comment]
Yes, that seems to work!
At least, that cookie path is currently the same at `akamaiedge.net` and `quiksilver.com` (which served it to me just now).
For some reason, trying to completely block those connections didn't occur to me. :)
