### ISSUE TITLE
Filters not working on https://torontosun.com/ because of generichide filter

### ISSUE THREAD

**Issue by joebagadonuts188** [easylist/easylist#14464]
### List the website(s) you're having issues:

`https://torontosun.com/opinion/editorials/editorial-new-year-brings-a-new-carbon-tax`

### What happens?

There is a generichide filter setup for the main site `https://torontosun.com/` that no longer seems necessary. It is preventing generic filters in EasyList and others from running on the site.

### List Subscriptions you're using:

easylist: 64358-68, now
easyprivacy: 30783-1283, now
ublock-abuse: 76-1, now
ublock-badware: 3958-108, now
ublock-filters: 31164-154, now
ublock-privacy: 257-2, now
ublock-quick-fixes: 488-34, now
ublock-unbreak: 1890-45, now
urlhaus-1: 10281-7, now
adguard-spyware-url: 795-1, now
curben-phishing: 165722-1, now
fanboy-cookiemonster: 42663-130, now

### Your settings

- OS/version: Win 10 21H1
- Browser/version: Version 108.0.5359.95 (Official Build) (64-bit)
- Adblock Extension/version: 1.45.2

**Comment by ryanbr** [comment]
Its a uBO filter, not us.
