### ISSUE TITLE
alibaba.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#14479]
**privacy**
```adblock
||s.alicdn.com/@g/retcode/log/log.js
||icbu-fe-log.log-global.aliyuncs.com^
```
```yaml
https://s.alicdn.com/@g/retcode/log/log.js
https://icbu-fe-log.log-global.aliyuncs.com/logstores/performance/track?APIVersion=0.6.0
```
---
A: `https://m.alibaba.com/trade/search?SearchText=pcb`

**Comment by 0o5rlubm** [comment]
there are also POST requests to https://us.ynuf.aliapp.org/service/um.json with encrypted tracking, and also https://de-wum.aliexpress.com/service/um.json when visiting aliexpress
but it may be bot protection system this time
