### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by User6751** [easylist/easylist#14495]
### List the website(s) you're having issues:
`https://www.google.com/`
`https://docs.google.com/spreadsheets/d/1QDiENdg3LYX4Z34JCIru9e_KFhqVhpcJcbkhhU5PiQ0/htmlview#gid=1442597046`

### What happens?
Annoyances

### List Subscriptions you're using:
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
EasyPrivacy
Fanboy’s Annoyance
uBlock filters – Annoyances
EasyList China

### Your settings

- OS/version: Android 10
- Browser/version: Kiwi Browser 107.0.5304.74
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:
![Screenshot_20221225-172803_Kiwi Browser](https://user-images.githubusercontent.com/120245025/209463207-abc010d3-6ef3-4a02-893c-ff4b1607b08e.jpg)
![Screenshot_20221225-173245_Kiwi Browser](https://user-images.githubusercontent.com/120245025/209463208-5c22c073-4273-4687-aeb9-3b41e7f2a1ea.jpg)

google.com##mobile-promo
docs.google.com##.docs-ml-promotion-shown.docs-ml-promotion-off-screen.docs-ml-promotion

**Comment by ryanbr** [comment]
What are we hiding here, translation needed

**Comment by Yuki2718** [comment]
> google sheets app promotion

I can reproduce only this.

**Comment by Yuki2718** [comment]
> different in English, it become trending searches

Not popup and not even an annoyance.
Unable to reproduce the popup even with 简体中文 locale and Honk Kong VPN.
