### ISSUE TITLE
ganjing.com

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#14497]
### List the website(s) you're having issues:

`https://www.ganjing.com/channel/1f8me1ele301Ef0kFS0n9NaZG1e90c`

### What happens?

Cookies

<details>
<summary>Screen</summary>

![2022-12-25_232436](https://user-images.githubusercontent.com/111344219/209482325-cb218373-5ad2-4a82-a869-e68f5599be24.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome 108.0.5359.125
- Adblock Extension/version:  uBO 1.45.2

**Comment by Yuki2718** [comment]
Fixed by https://github.com/easylist/easylist/commit/d016cb97bc79bf053c5169e5aae1a883cb350631
