### ISSUE TITLE
Cannot update Fanboy's Notification List in uBO

### ISSUE THREAD

**Issue by bbhtt** [easylist/easylist#14498]
### List the website(s) you're having issues:

None.

### What happens?

I've added https://easylist-downloads.adblockplus.org/fanboy-notifications.txt to uBO but attempting to update or load the list always results in "A network error prevented the resource from being updated"

While I can reach that URL fine in my browser, it seems that this shows unreachable in Logger `https://easylist-downloads.adblockplus.org/fanboy_notifications_specific_uBO.txt?_=10: 404 Not Found`

![image](https://user-images.githubusercontent.com/62639087/209486975-94d8936e-76f2-4772-b8ee-fd2b6caa59fe.png)

Also it seems to be no longer mentioned in https://easylist.to/. Any idea what's happening?

Thanks!

### List Subscriptions you're using:

Fanboy's Notifications

### Your settings

- OS/version: Arch Linux
- Browser/version: 110.0a1 (2022-12-24)
- Adblock Extension/version:  uBlock origin 1.46.0

### Other details:

None

**Comment by krystian3w** [comment]
Hosting may no longer allow copy suplements for uBo: https://github.com/uBlockOrigin/uBlock-issues/issues/2193 (this tries many workarounds and file is still excluded by "Eyeo").

**Comment by Khrin** [comment]
@bbhtt 
> 
> Also it seems to be no longer mentioned in https://easylist.to/. Any idea what's happening?
> 

The list is cited on the home page, with the correct link. The one you're using is obsolete and not supported anymore.

**Comment by bbhtt** [comment]
> The list is cited on the home page, with the correct link.

Where? I don't see it... 

Anyway I didn't know it was also served from https://fanboy.co.nz/ thanks for that.
