### ISSUE TITLE
hk.news.yahoo.com

### ISSUE THREAD

**Issue by User6751** [easylist/easylist#14493]
### List the website(s) you're having issues:
`https://hk.news.yahoo.com/`
`https://hk.news.yahoo.com/%E5%A4%A7%E5%B6%BC%E5%B1%B1%E6%B0%91%E5%AE%89%E9%9A%8A%E5%B0%8F%E5%B7%B4%E8%88%87%E7%A7%81%E5%AE%B6%E8%BB%8A%E7%9B%B8%E6%92%9E-%E6%9C%80%E5%B0%91-8-%E4%BA%BA%E5%8F%97%E5%82%B7-004410111.html`

### What happens?
Annoyances

### List Subscriptions you're using:
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
EasyPrivacy
Fanboy’s Annoyance
uBlock filters – Annoyances
EasyList China

### Your settings

- OS/version: Android 10
- Browser/version: Firefox 108.1.0
- Adblock Extension/version: uBlock Origin 1.46.0

### Other details:
![20221225_120532](https://user-images.githubusercontent.com/120245025/209456665-6c27db55-3fd7-4a68-b334-1312a0d99a56.jpg)
![Screenshot_20221225-122537_Firefox](https://user-images.githubusercontent.com/120245025/209456969-8d03bca3-0751-401f-a7ba-49bf753194dc.jpg)
![20221225_120555](https://user-images.githubusercontent.com/120245025/209456666-54bc98d8-bed2-4324-95db-7aa13cbdffd5.jpg)
![20221225_120607](https://user-images.githubusercontent.com/120245025/209456667-b173a546-c222-4ef0-9a8a-daa72efadf1d.jpg)

will fix it:
yahoo.com##.Z\(1\).Pos\(r\).Bgc\(\$bg-1\).Py\(8px\).Px\(16px\).GeminiPortalStreamAd_handleViewport
yahoo.com###feature_stream_portal_hk-AlwaysBigGemini
yahoo.com##.Z\(2\).D\(b\).T\(12px\).End\(4px\).Pos\(a\).H\(30px\).Maw\(26\%\).W\(26\%\).app-promo
yahoo.com###module-appPromoBanner
yahoo.com###module-featurebar
||yahoo.com/comments/*$subdocument,domain=yahoo.com
yahoo.com##.Mt\(24px\).Mb\(24px\).Mx\(20px\)

**Comment by Khrin** [comment]
Issue not reproducible, site looks fine as usual.
