### ISSUE TITLE
gartic.io

### ISSUE THREAD

**Issue by kmnvq** [easylist/easylist#14512]
### List the website(s) you're having issues:

`https://gartic.io/`

### What happens?

```
gartic.io###videoContainer
||gartic.io/videos/gtv2.mp4
```

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/110184059/209764658-a835be95-95cf-4576-9e7f-d1c7c0b38a45.png)

![resim](https://user-images.githubusercontent.com/110184059/209763662-11f77d9d-8fe3-4b9d-b33e-ddaacec69dc5.png)

</details>

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Tracking Protection, uBO filters

### Your settings

- OS/version: 
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin 1.46

### Other details:

**Comment by ryanbr** [comment]
This may make a worse user experience, since no way to skip it without viewing the video file. Leaving.
