### ISSUE TITLE
newsweek.com

### ISSUE THREAD

**Issue by SkepticalSnail** [easylist/easylist#14521]
### List the website(s) you're having issues:

`https://www.newsweek.com`

### What happens?

Cookie consent form.

### List Subscriptions you're using:

- AdGuard Annoyances
- AdGuard Social Media
- Anti-Facebook
- EasyList Cookie
- Fanboy’s Annoyance
- Fanboy’s Social
- uBlock filters – Annoyances

### Your settings

- OS/version: Windows 8.1 Pro
- Browser/version: Firefox 108.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin 1.46.0

### Other details:

![Newsweek frontpage screenshot with a cookie consent overlay](https://user-images.githubusercontent.com/121602298/209919522-82cc5594-62ee-4e1b-b45e-62e95ae656c2.png)

**Comment by ryanbr** [comment]
Works here, try disabling other subs to troubleshoot.

**Comment by SkepticalSnail** [comment]
OK, I had www.eff.org/files/cookieblocklist.txt in Custom filters, which I didn't notice because it's all the way down after regional filters, and that's what was causing it.

Just to clarify some things:

- Which ones of all the EasyLists and Fanboy's lists should be selected? All except Fanboy's Annoyance (and alternatively including Fanboy's Annoyance but excluding EasyList Cookie and Fanboy's Social)?
- Are cookie banners handled only by EasyList Cookie List (and through inclusion, by Fanboy's Annoyance List) or also some other lists?
- Can cookie banners and ads on foreign language sites be reported in this repo for inclusion in these filters or do they go in separate, language-specific filters?

**Comment by krystian3w** [comment]
Regional ads report first to regional repositories / forums / e-mail.

Few cookies banners block too EasyPrivacy due marked as tracker.

**Comment by krystian3w** [comment]
On GitHub exist in outdated FAQ: https://github.com/EFForg/privacybadger/wiki#why-does-my-browser-connect-to-fastlycom-on-startup-after-installing-privacy-badger

Also is here: https://filterlists.com/lists/eff-cookie-blocklist

**Comment by SkepticalSnail** [comment]
> Regional ads report first to regional repositories / forums / e-mail.

If there's no regional filter for a particular country, can they be reported here or is this repo strictly for English content?

> Few cookies banners block too EasyPrivacy due marked as tracker.

Sorry, I can't figure out this sentence.

**Comment by krystian3w** [comment]
> If there's no regional filter for a particular country, can they be reported here or is this repo strictly for English content?

I don't know that much.

>> Few cookies banners block too EasyPrivacy due marked as tracker.
>
> Sorry, I can't figure out this sentence.

I meant few cookie banners/pop-ups will be hidden (blocked on network level) by EasyPrivacy too, but this is rare situation.

**Comment by krystian3w** [comment]
AdGuard use visitors stats, so small pages can by closed without address.
