### ISSUE TITLE
update rule for Klaro Consent Manager

### ISSUE THREAD

**Issue by meixger** [easylist/easylist#14522]
### List the website(s) you're having issues:

`https://www.suedtirol.com/`

### What happens?

Background overlay div still remains and blocks everything.

### List Subscriptions you're using:

- EasyList Cookie

### Your settings

- OS/version: Windows 11
- Browser/version: Chrome 108
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:

Proposed changes: replace rule `###klaro .cook-modal` with new rule `###klaro` in `easylist_cookie/easylist_cookie_general_hide.txt`

https://github.com/kiprotect/klaro

**Comment by meixger** [comment]
@ryanbr I was thinking about adapting the existing rule for this particular consent manager:

`###klaro .cook-modal` -> `###klaro`

https://github.com/easylist/easylist/blob/284685dad9198abe5853cfc4db035622859d7bc8/easylist_cookie/easylist_cookie_general_hide.txt#L6132

**Comment by krystian3w** [comment]
this cover both:

```adb
#klaro div[class*="cookie-modal"]
```

?
