### ISSUE TITLE
pcloud.link

### ISSUE THREAD

**Issue by kmnvq** [easylist/easylist#14549]
### List the website(s) you're having issues:

`https://e1.pcloud.link/publink/show?code=kZgV5mZlsevstGJfUbVqq3RdgUNRjVCfa3V`
`https://www.pcloud.com/family.html`

### What happens?

```
||eapi.pcloud.com/loganalyticsevent
pcloud.link##.ad
```

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/110184059/210183351-47499bdc-d8d7-4ee9-a0b0-bb9ffea2136e.png)
![resim](https://user-images.githubusercontent.com/110184059/210183495-0dcdb1a5-ae37-435b-9e30-7b692bfedb57.png)

</details>

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Tracking Protection, uBO filters

### Your settings

- OS/version: 
- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin 1.46

### Other details:

**Comment by ryanbr** [comment]
Self promo, and the analytics already blocked `/loganalyticsevent?`
