### ISSUE TITLE
clubmonaco.com

### ISSUE THREAD

**Issue by Starffirre** [easylist/easylist#14551]
### List the website(s) you're having issues:
https://www.clubmonaco.com/

### What happens?
floating banner is shown on the site

### List Subscriptions you're using:

uBlock filters 
uBlock filters – Badware risks 
uBlock filters – Privacy 
uBlock filters – Quick fixes 
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy

### Your settings

- OS/version: macOS 13.1
- Browser/version: Chrome 108.0.5359.124
- Adblock Extension/version: uBlock Origin 1.45.2

### Other details:

![before-3](https://user-images.githubusercontent.com/121527177/209744475-e65dea26-1c24-4761-88c4-ca72cf79ddad.jpg)
![before-1](https://user-images.githubusercontent.com/121527177/209744049-97c5730b-8231-474a-b7cb-620626b9fb4c.jpg)

Had a PR for this issue: https://github.com/easylist/easylist/pull/14510

**Comment by Khrin** [comment]
It isn't an advertisement, therefore won't be blocked by Easylist.

**Comment by krystian3w** [comment]
So Fanboy Annoyances no longer block self-promo?

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/14551#issuecomment-1368933686
