### ISSUE TITLE
zeno.fm/radio

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#14569]
### List the website(s) you're having issues:

`https://zeno.fm/radio/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Fanboy's Annoyance List

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 108.0.1
- Adblock Extension/version: uBO 1.46.1b4

### Other details:

![zeno](https://user-images.githubusercontent.com/95879668/210297708-f819b8a3-415f-4bf7-a60c-514eb92c0461.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ed7d3d1936e654764230fcd65898661673cf2e2c
