### ISSUE TITLE
konami.com/games/us/en

### ISSUE THREAD

**Issue by q1800** [easylist/easylist#14568]
### List the website(s) you're having issues:

`https://www.konami.com/games/us/en/`

### What happens?

Cookie Notice

### List Subscriptions you're using:

uBO filter lists
EasyList
EasyPrivacy
Fanboy's Annoyance List

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 108.0.1
- Adblock Extension/version: uBO 1.46.1b4

### Other details:

![konami](https://user-images.githubusercontent.com/95879668/210292875-80da303e-f8aa-4bcb-91fc-7fa4d0e9448a.png)

**Comment by ryanbr** [comment]
https://github.com/uBlockOrigin/uAssets/issues/15296
