### ISSUE TITLE
GameSpot.com - Unplayable videos and missing images (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#14563]
### Affected site:
`https://www.gamespot.com/`

### Issue:
Unplayable videos and missing images, due to a blocked cookie consent, which needs to be accepted!

### Examples:
Unplayable video:
`https://www.gamespot.com/videos/payday-3-teaser-trailer/2300-6460303/`

Missing images (scroll down):
`https://www.gamespot.com/gallery/all-fortnite-gaming-legends-series-skins-so-far/2900-4070/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
`###onetrust-banner-sdk`
`###onetrust-consent-sdk`
`/cookieconsentpub/*`
`||onetrust.com^$third-party`

### Possible fix:
```
gamespot.com#@##onetrust-banner-sdk
gamespot.com#@##onetrust-consent-sdk
@@||geolocation.onetrust.com^$domain=gamespot.com
```

### Other problem filters:
* ~~**AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/139004/~~ _(FIXED)_
~~`||onetrust.com^$third-party`~~

* **I don't care about cookies** (@kiboke)
`~msn.com,~eurogamer.net,~rtlxl.nl,~zdf.de,~crfashionbook.com,~rockpapershotgun.com,~zdnet.com,~mensjournal.com,~cbsnews.com,~cbslocal.com,~assetstore.unity.com,~gmx.com,~gmx.es,~gmx.fr,~gmx.co.uk,~mail.com,~kruidvat.nl,~kruidvat.be,~trekpleister.nl,~tvn24.pl,~popsugar.co.uk,~rte.ie,~tunein.com,~oe24.at,~sika.com,~merkurmarkt.at,~boomerang-tv.pl,~cnbc.com,~1001spiele.de,~dhl.de,~sport.pl,~reisetopia.de,~mtvuutiset.fi,~billa.at,~aerztezeitung.de,~okazii.ro,~credit-suisse.com,~avisendanmark.dk,~milwaukeetool.eu,~geizhals.at,~geizhals.de,~geizhals.eu,~ryobitools.eu,~puma.com,~ikea.com,~beko.com,~blaklader.at,~blaklader.be,~blaklader.ca,~blaklader.com,~blaklader.cz,~blaklader.de,~blaklader.dk,~blaklader.ee,~blaklader.es,~blaklader.fi,~blaklader.fr,~blaklader.ie,~blaklader.it,~blaklader.nl,~blaklader.no,~blaklader.pl,~blaklader.se,~blaklader.uk###onetrust-consent-sdk`

* **MVPS HOSTS**
`geolocation.onetrust.com`

### Related issue (when using CNAME uncloaking):
`https://repo.palemoon.org/Moonchild/lunarblocklist/issues/25/`

--

### System info:
* OS/version: Windows 10 Pro 21H2 (x64)
* Browser/version: LibreWolf v108.0.1-1 (x64) (Tracking Protection = Standard)
* Adblock Extension/version: uBlock Origin v1.46.0

**Comment by krystian3w** [comment]
I see Kiboke don't unlocked show pop-up for uBo.

> ![obraz](https://user-images.githubusercontent.com/35370833/210435052-1693e3f9-dcd6-4716-aec7-5a2891f3c8a9.png)

Once filtering was cosmetically removed in its totality for One Trust. Why did it come back?

**Comment by THEtomaso** [comment]
> `###onetrust-consent-sdk`

AFAICT, that particular rule doesn't cause a problem in this case.
At least not from my end.
BTW; there's a few other cosmetical rules in IDCAC too, which also targets OneTrust elements.

**Comment by kiboke** [comment]
@THEtomaso thank you, it will be fixed in IDCAC soon.
