### ISSUE TITLE
[NSFW] Can't block pop-under ads at sextb.net

### ISSUE THREAD

**Issue by nguyenminhkhmt** [easylist/easylist#14573]
### Ads description

Can't block pop-under ads on this site.

### Step to reproduce

- Go to website
- Rewind forward/backward a video
- Pop-under ads show -> Open a new tab with ads.

### List Subscriptions you're using:

https://easylist-downloads.adblockplus.org/abpvn-minified.txt
https://browser.coccoc.com/js/ios_abp_custom_rules.txt
https://easylist-downloads.adblockplus.org/easylist-minified.txt

### Your settings

OS/version: iOS/all version
Browser/version: Cốc Cốc app/ 114.0.134
Adblock Extension/version: latest version
Other details:

**Comment by krystian3w** [comment]
Check with uBlock Origin I see is added to stock list "uBlock Filters".

In ABP may need report to https://github.com/abp-filters/abp-filters-anti-cv if **ryanbr** or **Khrin** don't have idea with standard filters (other than snippets like `abort-on-property-read`).
