### ISSUE TITLE
lbhounslow.sharepoint.com

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#14575]
### List the website(s) you're having issues:

```
https://lbhounslow.sharepoint.com/:b:/s/InternetLinks/pp/EWpjlW_lP7pKuesdw33UJo0BOS5HVbyRcQVaM1eP4B_wRA?e=ghKNIL
```

In case the above link stops workings, just grab a new one from here

```
https://www.hounslow.gov.uk/info/20010/planning_and_building/1868/conservation_area_appraisals_and_maps
```

### What happens?

Analytics endpoint not blocked

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/62358249/124452393-41884700-dd7e-11eb-9f76-7820fcee5844.png)

</details>

### Your settings

- OS/version: Macos 13.1
- Browser/version: Firefox 108.0.1
- Adblock Extension/version: uBlock Origin 1.46.0

### Other details:

Makes multiple post requests to following endpoint

```
https://eu-mobile.events.data.microsoft.com/Collector/3.0?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=ACT-Web-JS-2.9.0&x-apikey=<removed>
```

Suggested filter
```
||eu-mobile.events.data.microsoft.com^
```

**Comment by 0o5rlubm** [comment]
already blocked for me, it's already in the list: https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt#L722

could you try to refresh all filters manually, from the filter list "clean all caches" then "update all now"

**Comment by emlimap** [comment]
My bad. The version I had was from yesterday early morning before the commit with filter was merged https://github.com/easylist/easylist/commit/733a7a3fa8701278eb1efaea172da20ef3d63a4d

It is now blocked after forcing an update. Good spot @0o5rlubm.

Will make a note to check the latest version before reporting

**Comment by 0o5rlubm** [comment]
No worries, I should also be able to look if someone had just added the line :smile: have a good day
