### ISSUE TITLE
snopes.com

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#14589]
### List the website(s) you're having issues:

`https://www.snopes.com/fact-check/1912-article-global-warming/`
`https://www.snopes.com/fact-check/facebook-meta-posts-made-public/`

### What happens?

Ad placeholder

![image](https://user-images.githubusercontent.com/84513173/210659838-e54422ca-a023-4ed8-9ddf-68617380b396.png)

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox 108.0.1
- Adblock Extension/version: uBlock Origin 1.46.0

### Other details:
```adblock
snopes.com##.banner_ad_between_sections
```

**Comment by ryanbr** [comment]
Looks fine here @Nojuuu

**Comment by Nojuuu** [comment]
Hmm, not sure what was happening but now it is hiding everything else except `.banner_ad_between_sections`

**Comment by Nojuuu** [comment]
`.banner_ad_between_sections` also on front page:
![image](https://user-images.githubusercontent.com/84513173/212780554-60379f7c-fa18-464a-afbd-f877e1899a87.png)
