### ISSUE TITLE
de.tommy.com -  Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#14597]
### List the website(s) you're having issues:

- `https://de.tommy.com/`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 108
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/210781674-7c6ab265-0471-44c5-adf9-b0fd4ecadb85.png">

**Comment by ryanbr** [comment]
It disables scroll, can't work around in ABP.
