### ISSUE TITLE
etxt.biz

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#14612]
`https://www.etxt.biz/admin.php`

account required

<details>
<summary>Screenshot(s)</summary>

![etxt biz_sidebar-adv](https://user-images.githubusercontent.com/20126984/211146118-97586b07-4377-4c93-ac05-50da016c0b9b.jpg)
![etxt biz_sidebar-info](https://user-images.githubusercontent.com/20126984/211146125-60c14b5a-fe0a-44e0-bb91-7a05f58ce008.jpg)

</details>

```
etxt.biz##.mod-cabinet__sidebar-adv
etxt.biz##.mod-cabinet__sidebar-info
||etxt.biz/data/rotations/
||etxt.biz/images/b/
```

**Comment by dimisa-RUAdList** [comment]
The first two rules are cosmetic and will hide ads. But advertising images will still continue to load and update, although they will not be visible. Therefore, it is desirable to add all the rules.

And I found another way: `||etxt.biz/data/advers/`

**Comment by ryanbr** [comment]
The less amount of filters to do the job?

**Comment by dimisa-RUAdList** [comment]
If we want to get by with a minimum number of rules, then hiding rules alone are sufficient. But if we set a goal to make content easier and user experience comfortable, then all five rules are needed.
