### ISSUE TITLE
hurriyetdailynews.com

### ISSUE THREAD

**Issue by kmnvq** [easylist/easylist#14617]
### List the website(s) you're having issues:

`https://www.hurriyetdailynews.com/prince-harry-faces-growing-criticism-over-memoir-revelations-179930`

### What happens?

```
hurriyetdailynews.com##div[class*="advertorial"]
hurriyetdailynews.com##.advMasthead
```

<details>
 <summary>Image</summary>

![resim](https://user-images.githubusercontent.com/110184059/211171252-2d815f5f-1dbf-44ce-9c8d-7ba32ddf44cb.png)

</details>

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Tracking Protection, uBO filters

### Your settings

- OS/version: 
- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin 1.46

### Other details:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/80db38e0088d695bb73f2c058a4de5d9a694219b
