### ISSUE TITLE
trust-provider.com is not a tracking domain

### ISSUE THREAD

**Issue by ameshkov** [easylist/easylist#14627]
https://github.com/easylist/easylist/blob/89795153fa6c7ab390b91bc8f9d6ff1af6279587/easyprivacy/easyprivacy_trackingservers.txt#L276

The domain belongs to sectigo.com, a certificate authority.

**Comment by ryanbr** [comment]
Came from https://github.com/easylist/easylist/commit/aeb7bc16fc2cc29b1fe156c08916c87a35123ce8

`https://secure.trust-provider.com/trustlogo/javascript/trustlogo.js` @ameshkov   Seems to be tracking here.

**Comment by ameshkov** [comment]
@ryanbr seems to be a widget that shows something like "The website is secure" or something like that:
https://www.trustlogo.com/ssl-certificate-support/

Tbh, I see no tracking signals there, no cookies or third-party requests. I'd count it as an annoyance.

**Comment by ryanbr** [comment]
https://pastebin.com/raw/qyK9ESzR   (cleaned up). mouse checks, UA checks, screen fingerprinting, @ameshkov

**Comment by ryanbr** [comment]
We also block https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt#L2458

**Comment by ameshkov** [comment]
@ryanbr ah, then I guess it falls under the policy, got it.

However, blocking the whole `trust-provider.com` breaks Sectigo's web panel as well.

**Comment by ryanbr** [comment]
Link to the issue with sectigo?
