### ISSUE TITLE
bad broad filter

### ISSUE THREAD

**Issue by ArabCoders** [easylist/easylist#1463]
Hello

this commit 2e3747e06bc82b19960cffbdb1612774dd8e0714 introduced a broad filter that effect many websites  ``.gif?v=`` thats include discourse forums and many other websites that use ?v=date tag for versioning static content..

**Comment by tisdall** [comment]
Came here to also complain about this one...  It's a very common way to cache-break when including images in a CSS file that are being hosted with an "expires" far in the future.
