### ISSUE TITLE
/api/v2/analytics/* blocking route potentially breaking sites

### ISSUE THREAD

**Issue by wiederin-skew** [easylist/easylist#14634]
### List the website(s) you're having issues:

Login is required for the site.

`https://prime.coinbase.com/`

### What happens?

The recent rule https://github.com/easylist/easylist/commit/6a9a68c6afe989852a25b6ce345bef275d1cd1bc is blocking core API calls within the Prime Analytics site after login. These are legitimate non-tracking API calls, serving market analytics data. More details: https://www.coinbase.com/prime/analytics

### List Subscriptions you're using:

uBlock Origin (with easy privacy enabled)

### Your settings

- OS/version: macOS Ventura
- Browser/version: Chrome 108.0.5359.124
- Adblock Extension/version: uBlock Origin 1.46.0

**Comment by nemanjan00** [comment]
Broke multiple of my websites too...

**Comment by 0o5rlubm** [comment]
@ryanbr @Khrin do you prefer to whitelist specific sites or remove the entire rule?

**Comment by 0o5rlubm** [comment]
Sorry for the inconvenience, a stricter rule for taking only the original target can be used.
