### ISSUE TITLE
Fanboy's Annoyance breaks "answear." sites

### ISSUE THREAD

**Issue by caneleex** [easylist/easylist#14630]
### List the website(s) you're having issues:

all answear sites - for example `https://answear.sk/cart`

### What happens?

the filter completely nukes the website contents.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 108.0.2
- Adblock Extension/version: uBlock Origin 1.46.0

**Comment by THEtomaso** [comment]
### Problem filter:
Fanboy's Annoyance List

### Problem rule:
`/js/newsletter.`

### Possible fix:
```
@@||cdn.ans-media.com^*/js/newsletter.js$domain=answear.bg|answear.com|answear.com.cy|answear.cz|answear.gr|answear.hr|answear.hu|answear.ro|answear.si|answear.sk|answear.ua
```
