### ISSUE TITLE
Easy List breaking `internewsweb.com`

### ISSUE THREAD

**Issue by eporubin** [easylist/easylist#14643]
### List the website(s) you're having issues:
`https://internewsweb.com/`

### What happens?
The EL adservers.txt contains the filter` ||internewsweb.com` and therefore the whole website it’s broken because all requests are being blocked with ABP on. Please set it as Third-party or remove from the list. thank you

### List Subscriptions you're using:
ABP Filters, EasyList English

### Other details:
![image](https://user-images.githubusercontent.com/33602691/211361828-47c67664-6f9f-49eb-97b1-920122edc504.png)

**Comment by eporubin** [comment]
same issue with `topnewsfeeds.net`, please change from `||topnewsfeeds.net^` to `||topnewsfeeds.net^third-party`

**Comment by Yuki2718** [comment]
`https://www.computips.org/remove-topnewsfeeds-net/`

**Comment by krystian3w** [comment]
in uBo and AdGuard possible force strict block:

```adb
||topnewsfeeds.net^$all,to=~risky-even-disabled-javascript
```

**Comment by ryanbr** [comment]
Yeah, these are fake sites. Should be blocked.

**Comment by Yuki2718** [comment]
@ryanbr 

>  `https://www.computips.org/remove-topnewsfeeds-net/` (BTW `computips.org###text-5`)
