### ISSUE TITLE
Fanboy Annoyance breaking upworthy.com

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#14647]
### List the website(s) you're having issues:

Cannot scroll down on homepage with Firefox stable and uBO defaults, https://www.upworthy.com/. 

I can scroll on subpages e.g. https://www.upworthy.com/michael-jackson-oprah-interview

### What happens?

Cannot scroll. I haven't isolated what rule is causing it.

### List Subscriptions you're using:
uBo defaults + FB annoyance

### Your settings

- OS/version: Win 11
- Browser/version: Firefox 108.0.2
- Adblock Extension/version: uBO 1.46.0

### Other details:

![upworhty](https://user-images.githubusercontent.com/11689349/211403922-36db1ddf-9b85-47f6-ae6d-c2efba9abc1c.png)

**Comment by yokoffing** [comment]
I tried with just Easylist Cookie, so it's one of rules in it.

**Comment by ryanbr** [comment]
Scrolling here

**Comment by yokoffing** [comment]
It is working for me now as well... Hmmm. Alright, sorry for the FP.
