### ISSUE TITLE
quartic.pl

### ISSUE THREAD

**Issue by KerbenII** [easylist/easylist#1464]
### List the website(s) you're having issues:
`quartic.pl
cp.quarticon.com
enea.pl`

### What happens?

1. After correct logging into the clients dashboard (cp.quarticon.com), the panel does not work (no javascripts, css styles).

2. Our CDN does not return images and css styles (fl.quartic.pl)

If You want to block our analytics engine, please block:
- rec.quartic.pl/t.php
- rec.quartic.pl//tt

`||rec.quartic.pl/t.php^$third-party
||https://rec.quartic.pl//tt`

### List Subscriptions you're using:

uBlock Origin
EasyPrivacy
### Your settings

no additional lists / extensions

- OS/version:  Windows 10
- Browser/version: Chrome 67
- Adblock Extension/version:  uBlockOrigin 1.16.10

### Other details:

`||quartic.pl^$third-party`

**Comment by KerbenII** [comment]
I created pull request

**Comment by smed79** [comment]
Why not only `||rec.quartic.pl^` ?

@ryanbr fyi.

**Comment by KerbenII** [comment]
IMHO There is no need for this, for 10 years only these urls are collecting tracking information.

Some shops ask rec.quartic.pl for information about, for example, products similar to the currently viewed one (from the same shop). In case of blocking such communication, the whole sections of such shops are not displayed. These queries do not track users.

**Comment by KerbenII** [comment]
@smed79 @ryanbr up

**Comment by ryanbr** [comment]
If you want to actually help, you should actuallly post the site that's causing issues and it can be tested.

**Comment by KerbenII** [comment]
@ryanbr I already did this:
`quartic.pl cp.quarticon.com enea.pl`

Here is screenshot:
![Destroyed Control Panel](https://wegrzynek.org/c15e5d1a-9b45-4b36-91ea-52a5c891ee6e.png)

**Comment by KerbenII** [comment]
For example here you can see our r.php informing Rainbow about "Similar Holidays \ Podobne Oferty":
`https://r.pl/cypr-polnocny-wypoczynek/acapulco-resort?dataWKodzieProduktu=20180711&liczbaDoroslych=2&liczbaDzieci=0&liczbaPokoi=1&wiekDzieci=&wybraneMiastoWyjazdu=Katowice&wybraneWyzywienie=All+Inclusive+Soft`

When You block the request, website will return empty div.

**Comment by ryanbr** [comment]
I visited the site, I didnt see any breakage, seemed fine here

**Comment by KerbenII** [comment]
The whole section "Similar Holidays \ Podobne Oferty" is empty.

Easy privacy turned on:
![easy-privacy-on](https://user-images.githubusercontent.com/15047492/42635087-529df93e-85e5-11e8-9c1d-f0ce414bc853.png)
Easy privacy turned off:
![easy-privacy-turned-off](https://user-images.githubusercontent.com/15047492/42635088-52ba9454-85e5-11e8-89bd-2d677f48c3df.png)

**Comment by KerbenII** [comment]
@ryanbr and our dashboard still looks that:
![quarticon dash](https://user-images.githubusercontent.com/15047492/42635491-7ec3f60c-85e6-11e8-9af4-02137a7e39a4.png)

Instead of:
![dash2](https://user-images.githubusercontent.com/15047492/42635573-af4754fe-85e6-11e8-9b5f-6e88891b4739.png)

**Comment by KerbenII** [comment]
I really appreciate easy-privacy filters, however right now they are unusable for me :/

**Comment by KerbenII** [comment]
@Khrin, can You look at this issue?
I noticed that You are really active person and our whole control panel is blocked for 12 days and counting...

**Comment by ryanbr** [comment]
Its only 12 days because you haven't given enough details for testing.

**Comment by KerbenII** [comment]
Fanboyz, that is untruth. What am I missing?

**Comment by KerbenII** [comment]
Our Dashboard looks like shit because You can not ban one script (or even subdomain), but must block WHOLE wildcard.

I created issue, created pull request, give you list of domains affected and even sceeenshots.

What can I do more??

**Comment by ryanbr** [comment]
We don't have access to the Dashboard, we can't test it.

**Comment by KerbenII** [comment]
You can create new account here:
https://cp.quarticon.com/register/stepone

**Comment by KerbenII** [comment]
Thanks!
And You have forgotten about:
||rec.quartic.pl/t.php^$third-party 

We use that two urls. 
Sorry for lack of MD - I am writting from mobile.

**Comment by KerbenII** [comment]
Thanks Fanboyz :)
