### ISSUE TITLE
Adding a widget with materials from the rbc.ru subproject to EasyList

### ISSUE THREAD

**Issue by apuzikova** [easylist/easylist#14654]
Dear Sir/Madam,
 
My name is Alena Puzikova, I am a project manager, responsible for the web-site [rbc.ru](http://rbc.ru/). We have found out that in the showcase on the main page [rbc.ru](http://rbc.ru/) (swiper-wrapper) the content block of our subproject [pro.rbc.ru](http://pro.rbc.ru/) (swiper-slide) is no longer displayed when Adblock is enabled.  
 
For our part, we have checked our block for the existence of blocking factors. Content output was blocked on December 22, 2022 https://github.com/easylist/ruadlist/commit/7078d34e1f59a94ef59ff4becb708a1d7cbf8a78 on the grounds of the presence of utm-tag "utm_campaign" in the material links. However, we use this tag to track the performance of particular materials of the project under our domain, i.e. our subproject [pro.rbc.ru](http://pro.rbc.ru/) . In this case, all content in the showcase has the same tag utm_campaign=vitrina_main in order to indicate that the [pro.rbc.ru](http://pro.rbc.ru/) showcase with its materials is placed on the main page for more accurate tracking of our traffic source. 
 
Could you please reconsider your decision regarding the presence of this showcase in EasyList, as it does not contain blocking factors for output on the site under Adblock.
 
Thank you in advance!

**Comment by Khrin** [comment]
You're in the wrong repository, ask here: https://github.com/easylist/ruadlist/issues
