### ISSUE TITLE
dit.whatsapp.net

### ISSUE THREAD

**Issue by Theta-Dev** [easylist/easylist#14659]
### List the website(s) you're having issues:

- `https://dit.whatsapp.net`

### What happens?

The Whatsapp Web client (`web.whatsapp.com`) sends telemetry data to this domain. The request payload contains my operating system, my country as well as a bunch of obfuscated stuff.

The domain can be blocked without any negative effects to the client. I'd suggest adding it to EasyPrivacy.

### List Subscriptions you're using:

- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Quick fixes
- uBlock filters – Resource abuse
- uBlock filters – Unbreak
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist

### Your settings

- OS/version: Linux (Debian Testing)
- Browser/version: Firefox 102.6.0esr
- Adblock Extension/version: Ublock Origin 1.46.0

**Comment by ryanbr** [comment]
Would need more proof and other users before adding this.
