### ISSUE TITLE
Dead domains that can be removed from list

### ISSUE THREAD

**Issue by mmrabbani** [easylist/easylist#14657]
Hello

I have checked domains of Easylist and Easyprivacy by Godaddy.com.

The result is:
1. Out of 19834 domains in Easylist, 820 domains have no owner and can be bought. This means that the previous owner of the domains did not renew them. So these domains can be removed from list to make this list lighter.
2. 4 domains from Easyprivacy have similar conditions.

Lists of dead domains of Easylist and Easyprivacy can be downloaded in below:
[easylist dead domains.txt](https://github.com/easylist/easylist/files/10385620/easylist.dead.domains.txt)
[easyprivacy dead domains.txt](https://github.com/easylist/easylist/files/10385619/easyprivacy.dead.domains.txt)

Note that I only checked domains, not other rules.

**Comment by ryanbr** [comment]
Not accurate, we use semi-automated methods to remove dead domains
