### ISSUE TITLE
propellerads.com, joinpropeller.com

### ISSUE THREAD

**Issue by EgorIakovlev** [easylist/easylist#14663]
### List the website(s) you're having issues:

propellerads.com, joinpropeller.com

### What happens?

PropellerAds domains `propellerads.com` and `joinpropeller.com` were added to `easylist_adservers.txt`. It looks like it's a mistake, because they are corporate websites that do not display any advertising banners.

### List Subscriptions you're using:

Default EasyList subscription in AdBlock Plus.

### Your settings

- OS/version: macOS Ventura 13.01
- Browser/version: Chrome Chrome 108.0.5359.124 (Official Build) (arm64)
- Adblock Extension/version: AdBlock Plus 3.15.2

### Other details:

Thanks for reviewing the issue, I'm waiting for your response.

**Comment by 0o5rlubm** [comment]
added in 0bfa9f7ba53afd475d9a85be94fdcce238317c0c, same request and text as #14664

**Comment by ryanbr** [comment]
propeller is a abusive ad provider. its blocked outright for this very reason.

https://github.com/easylist/easylist/blob/master/README.md#easylist
