### ISSUE TITLE
streamerbans.com

### ISSUE THREAD

**Issue by dpthegrey** [easylist/easylist#14665]
### List the website(s) you're having issues:

`https://streamerbans.com/`

### What happens?

Cookie Notice
### List Subscriptions you're using:

Easylist-Cookie List (Brave Shields Filter)
uBlock Annoyances List (Brave Shields Filter)

### Your settings

- OS/version: macOS Monterey
- Browser/version: Brave Version 1.46.153
- Adblock Extension/version: Brave Shields

### Other details:

![image](https://user-images.githubusercontent.com/49444980/211840387-572eb382-6602-4347-b4cb-40fd077631b7.png)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/9ed7206b66c565267c7924cce1c4ab0d2e272e47
