### ISSUE TITLE
monetag.com

### ISSUE THREAD

**Issue by Monetag** [easylist/easylist#14664]
### List the website(s) you're having issues:
monetag.com

### What happens?
Monetag domain monetag.com is added to easylist_adservers.txt. It looks like it's a mistake, because it is a corporate website that does not display any advertising banners.

### List Subscriptions you're using:
Default EasyList subscription in AdBlock Plus.

### Your settings

- OS/vesion: WIndows 10 1809 Build 17763.107
- Browser/version: Google Chrome 109.0.5414.75 (Official Build) (x86_64)
- Adblock Extension/version: AdBlock Plus 3.15.2

### Other details:
Thanks for reviewing the issue. Looking forward to your reply!

**Comment by 0o5rlubm** [comment]
added in 0bfa9f7ba53afd475d9a85be94fdcce238317c0c
