### ISSUE TITLE
Section hidden on site

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#14688]
### List the website(s) you're having issues:
https://huffpost.com

### What happens?
On the top of the page, there is usually a section with the title "What's hot" (Either above or below the header) which is hidden because of the filter `##.top-ad-recirc.` I was able to fix it easily just by adding `huffpost.com#@#.top-ad-recirc` to My Filters in uBlock Origin.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
![huuff](https://user-images.githubusercontent.com/1659004/213139014-fbcb9988-059d-4286-90ff-d2e0be967081.png)

Loading fine here.

**Comment by Sonic5435325** [comment]
Is this at the top of the page?
