### ISSUE TITLE
tweakers.net

### ISSUE THREAD

**Issue by BartLH** [easylist/easylist#14681]
### List the website(s) you're having issues:

`tweakers.net`

### What happens?

Adblock notice appears when visiting certain articles, for example `https://tweakers.net/reviews/9610/raspberry-pi-als-brein-van-je-smarthome-deel-4-beveilig-je-domoticasysteem.html`, even though I'm only blocking tracking, not ads.

This is because the EasyPrivacy list contains `||aa.tweakers.nl^`. This domain does not serve tracking advertisements anymore. It should only be on the adblocking list, not on the privacy list. Please remove it from EasyPrivacy.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 109.0.5414.74
- Adblock Extension/version: Mullvad DNS blocking, Trackers only

### Other details:

In general, the rules in `https://tweakers.net/adblock_allowlist.txt` should only be in EasyList, and not in EasyPrivacy.

**Comment by Khrin** [comment]
@BartLH I think you've misunderstood the purposes of Easylist and Easyprivacy: the first list is devoted to block ads, while the latter to block trackers. For what I can see, `aa.tweakers.nl` only serves trackers (and I couldn't observe any anti-adblocker on this site), therefore filters will stay in this list.

**Comment by BartLH** [comment]
@Khrin `aa.tweakers.net` only serves ads, not trackers. Or at least it should be, https://tweakers.net/plan/3560/tweakers-overstap-naar-advertenties-zonder-thirdpartytracking-is-een-feit.html.
So I don't think that I've misunderstood the purposes of the Easylist and Easyprivacy.

**Comment by Khrin** [comment]
OK then!
