### ISSUE TITLE
imgur.com

### ISSUE THREAD

**Issue by wallrik** [easylist/easylist#14697]
### List the website(s) you're having issues:

`https://imgur.com/`

### What happens?

Ads do get blocked, but an empty placeholder frame is still shown on the front page grid.

### List Subscriptions you're using:

* uBO Built-in (6/6)
* EasyList
* EasyPrivacy
* Malware domains (3/3)
* Fanboy's Annoyance
* uBlock filters - Annoyances

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 108.0.2
- Adblock Extension/version: uBlock Origin 1.46.0

### Other details:

Suggested filter: `imgur.com##div.Post-item.fast-grid-ad:upward(1)`

* [Current frontpage](https://user-images.githubusercontent.com/10890923/212559400-d2f7e7bc-4c9a-41ea-826e-af1885594b46.png) (with current filter lists)
* [With suggested filter](https://user-images.githubusercontent.com/10890923/212559405-7de3323c-1d25-40ff-842d-1bee9a4ddd76.png)

**Comment by ryanbr** [comment]
Seems fine here.

**Comment by wallrik** [comment]
This issue was closed as _completed_ instead of _not planned / can't repro_, without discussion. Please re-open. 🙏😇

I've had the front page set to **uniform view** for so long. I didn't remember I had it until I tried to reproduce on a virtual machine. Toggle view mode in top right corner. Empty ad-blocked boxes appear in the grid.

Without block lists, ads appear in both waterfall and uniform view.

**Comment by dportvine** [comment]
@ryanbr 
<details>
<summary>Screen</summary>

![2023-04-21_165047](https://user-images.githubusercontent.com/111344219/233653448-9385e877-8bf9-4c91-b4b2-0cb1a932be57.png)
</details>
