### ISSUE TITLE
parkers.co.uk

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylist#14696]
### List the website(s) you're having issues:

`https://www.parkers.co.uk/`

### What happens?

Big ad placeholder

### List Subscriptions you're using:

EasyList
EasyPrivacy

### Your settings

- OS/version: Win 7 SP1
- Browser/version: Firefox 108.0.2 & Opera 94
- Adblock Extension/version: uBO 1.46.1b8

### Other details:

![hghgh](https://user-images.githubusercontent.com/72945564/212558673-7faaf042-d381-4ffe-9db3-071ce8f73676.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/cff760de6003be1d608fa735201d0d5cabd116f9
