### ISSUE TITLE
Fanboy annoyance breaks Reddit https://www.reddit.com/r/toxicmasculinity/comments/10ct4rb/real_men_dont_sleep/

### ISSUE THREAD

**Issue by tyw7** [easylist/easylist#14698]
### List the website(s) you're having issues:

https://www.reddit.com/r/toxicmasculinity/comments/10ct4rb/real_men_dont_sleep/

### What happens?

I noticed that Ublock Origin breaks Reddit. With it enabled, on posts with video, I can't click the "..." menu to add a flair after posting.

### Your settings
uBlock Origin: 1.46.0

Chromium: 108

filterset (summary):

network: 85023

cosmetic: 126450

scriptlet: 34589

html: 0

listset (total-discarded, last-updated):

removed:

easylist: null

added:

https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-0, 21h.17m

https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 21h.17m

adguard-generic: 67415-505, 21h.18m

adguard-mobile: 8660-41, 21h.18m

fanboy-annoyance: 85034-467, never

ublock-annoyances: 4747-36, 21h.18m

default:

user-filters: 113-9, never

easyprivacy: 30893-1263, 5d.23h.46m

plowe-0: 3668-714, 4d.8m

ublock-abuse: 77-0, 21h.18m

ublock-badware: 4294-222, 21h.18m

ublock-filters: 31755-3434, 21h.18m

ublock-privacy: 257-1, 21h.18m

ublock-unbreak: 1922-77, 21h.18m

urlhaus-1: 6868-0, 1d.13m

filterset (user): [array of 116 redacted]

trustedset:

added: [array of 488 redacted]

removed:

about-scheme

switchRuleset:

added: [array of 12 redacted]

modifiedUserSettings:

cloudStorageEnabled: true

contextMenuEnabled: false

hyperlinkAuditingDisabled: false

prefetchingDisabled: false

modifiedHiddenSettings:

autoUpdateAssetFetchPeriod: 120

autoUpdateDelayAfterLaunch: 180

autoUpdatePeriod: 7

selfieAfter: 3

supportStats:

allReadyAfter: 9266 ms (selfie)

maxAssetCacheWait: 475 ms

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
just update the lists

**Comment by iam-py-test** [comment]
> https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 21h.17m

Are you sure you want this installed? This list unblocks tons of trackers, ads, etc and is known to cause problems
> https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-0, 21h.17m

This list hasn't been updated since Oct 31, 2022, and only was updated 4 times in 2022. You are free to keep it, but I personally wouldn't rely on it for protection from scams

**Comment by tyw7** [comment]
I had removed the two list you said.

Here's the new troubleshooting:
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 96143
  cosmetic: 166797
  scriptlet: 24283
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62682-94, 2d.15h.12m
    fanboy-annoyance: 85086-4154, 6d.15h.44m
    fanboy-cookiemonster: 44877-44877, 6d.15h.44m
    ublock-annoyances: 4753-213, 2d.15h.8m
    ublock-quick-fixes: 490-20, 3h.20m
  default: 
    user-filters: 55-2, never
    easylist: 62162-102, 3h.24m
    easyprivacy: 30950-1259, 3h.22m
    plowe-0: 3666-900, 6d.15h.44m
    ublock-abuse: 77-0, 2d.15h.10m
    ublock-badware: 4320-114, 2d.15h.6m
    ublock-filters: 31700-516, 2d.15h.4m
    ublock-privacy: 257-9, 6d.15h.44m
    ublock-unbreak: 1923-51, 2d.15h.2m
    urlhaus-1: 6705-0, 3h.18m
filterset (user): [array of 55 redacted]
trustedset: 
  added: [array of 494 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  contextMenuEnabled: false
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdateDelayAfterLaunch: 180
  autoUpdatePeriod: 7
  selfieAfter: 3
supportStats: 
  allReadyAfter: 6926 ms (selfie)
  maxAssetCacheWait: 752 ms

**Comment by iam-py-test** [comment]
Ok, glad it's working for you.
In the future, please update all your filterlists before reporting an issue.

**Comment by tyw7** [comment]
I mean when I reported it, it was broken but an update must have come in the time between then and now.

**Comment by iam-py-test** [comment]
> I mean when I reported it, it was broken, but an update must have come in the time between then and now.

Ok. Sorry for my mistake
