### ISSUE TITLE
hejto.pl

### ISSUE THREAD

**Issue by Jerzy321** [easylist/easylist#14718]
### List the website(s) you're having issues:
`hejto.pl`

### What happens?
`Easylist Cookie List ` and `Fanboy's Annoyance List ` filters break the slide-out panel on the left.
Removing `hejto.pl##.z-1200` fixes the problem.

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox 108.0.2 
- Adblock Extension/version: uBlock Origin 1.46.0

**Comment by krystian3w** [comment]
test:

```adb
hejto.pl##footer ~ .fixed.z-1200[class*="paper"]
```

later:

```adb
hejto.pl##footer ~ .border-primary-main
```

**Comment by ryanbr** [comment]
Should be fixed @Jerzy321 can you retest? (force update lists)

**Comment by krystian3w** [comment]
Also ping me and "kiboke" (https://github.com/kiboke) when `.border-primary-main` down.

**Comment by Jerzy321** [comment]
Ok, fixed

**Comment by krystian3w** [comment]
I guess that page no longer use bottom bar but forced `cmp.quantcast.com` - fyi @peace2000 / @Nojuuu.
