### ISSUE TITLE
jpg.church

### ISSUE THREAD

**Issue by SkyCloudDev** [easylist/easylist#14719]
### List the website(s) you're having issues:

`jpg.church`

### What happens?

`jpg.church` has been incorrectly added to the filter list. 
This site is an adult image host used on multiple other sites such as `simpcity.su` and `https://forums.socialmediagirls.com/`.

### List Subscriptions you're using:

Everything as default

### Your settings

Everything as default

- OS/version: Windows 10
- Browser/version: Chrome 109.0.5414.75 
- Adblock Extension/version: uBlock Origin 1.46.0

**Comment by ryanbr** [comment]
Update your filters.
