### ISSUE TITLE
kaspersky.com.tr

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#14722]
### List the website(s) you're having issues:

`https://www.kaspersky.com.tr/blog/cs-go-two-million-usd-inventory-hack/10796/`

### What happens?

Tracking
`otr.kaspersky.com.tr`

<details>
 <summary>screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/213345236-30b9706e-6690-4f1c-8c6b-5886988892bd.png)

</details>

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Tracking Protection, uBO filters

### Your settings

- OS/version: 
- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin 1.46

### Other details:

**Comment by ryanbr** [comment]
We're already blocking it?
