### ISSUE TITLE
economiapertutti.bancaditalia.it

### ISSUE THREAD

**Issue by albertopasqualetto** [easylist/easylist#14726]
### List the website(s) you're having issues:

`economiapertutti.bancaditalia.it`

### What happens?

Cookie banner is removed by easylist cookie, but website is not navigable.
'pef-no-cookie` class should be removed from body tag.

### List Subscriptions you're using:

- ITA-0: 13350-0
- easylist: 62214-58
- easyprivacy: 30931-1172
- plowe-0: 3668-901
- ublock-abuse: 77-1
- ublock-badware: 4320-114
- ublock-filters: 31693-2826
- ublock-privacy: 258-1
- ublock-quick-fixes: 487-25
- ublock-unbreak: 1923-48
- urlhaus-1: 6307-0
- https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24201-28
- fanboy-cookiemonster: 44890-217
- ublock-annoyances: 4749-74

### Your settings

- OS/version: Windows 11
- Browser/version: Edge 109.0.1518.55
- Adblock Extension/version: uBlock Origin: 1.46.0

**Comment by Khrin** [comment]
Looks fine for me with EasyList Cookie in Ublock Origin, are you sure the problem is in this list?

**Comment by albertopasqualetto** [comment]
Well, ublock says that only easylist cookie and easyPrivacy block are blocking something... I don't know what else could not remove that class.

![image](https://user-images.githubusercontent.com/39854348/213575477-932ede50-3ab9-4028-a93e-21fc5de2fd11.png)

**Comment by krystian3w** [comment]
@brodock I think browser cache may load file:

`https://economiapertutti.bancaditalia.it/application/themes/pef/css/cookiePrivacy.css`

Then needed is clear cache for page or force refresh page.
