### ISSUE TITLE
How to get on the allowlist?

### ISSUE THREAD

**Issue by juanlpz-ml** [easylist/easylist#14733]
Hello, I work for MercadoLibre. I'm writing here because one of our advertising banners was blocked. Upon browsing the repository, we noticed that you have an allowlist, which is why we have a question about the requirements needed to belong to that group. Our advertising banner does not aim to ruin the experience of our users, on the contrary, it seeks not to be invasive, and also does not block the main content of our page, it is located at the end of our product pages and almost at the end on the main page. I would really appreciate it if you could tell me more about your criteria for getting on the allowlist and what possibilities exist

![Captura de Pantalla 2023-01-20 a la(s) 17 55 41](https://user-images.githubusercontent.com/82414671/213809271-95e6897c-6d62-48e5-b737-f275edb43ed5.png)

**Comment by iam-py-test** [comment]
**I do not speak for EasyList. I am not part of EasyList or any of the adblocker teams. You will have to wait for an answer from someone on the EasyList team. This is just my opinion.**
EasyList's "allowlist" is for unbreaking websites, not for allowlisting ads at the request of said ad company. EasyList blocks [any ads which meet the rules](https://github.com/easylist/easylist#easylist), regardless of if the website owner or ad company thinks they are "nice" or "not annoying".
If you want to be allowlisted by the "Acceptable Ads" list (which is **unrelated** to EasyList), then you will need to apply to them separately.

**Comment by juanlpz-ml** [comment]
@iam-py-test Thank you for your opinion, every word that adds knowledge is welcome. My question arises in the same way because it seemed to me that I saw an exception for Google ads in the allowlist. On the other hand, you mention an "Acceptable Ads" list, what do you refer to with that?

**Comment by iam-py-test** [comment]
> I saw an exception for Google ads in the allowlist. 

As I am **not part of the EasyList team**, I can not speak to why that exception was added, but I assume it was due to a broken site
> On the other hand, you mention an "Acceptable Ads" list, what do you refer to with that?

https://adblockplus.org/en/acceptable-ads#what-are-those (the website they link to has an expired cert, but I think the page will give you a good enough idea)

**Comment by juanlpz-ml** [comment]
Thanks again, all the information helps me to better understand how this works. I'll wait to see what the official team says.

**Comment by ryanbr** [comment]
We're not blocking the MercadoLibre banner from what I see (other filter lists may filter it), and unless there is a specific issue we wouldn't just add a filter to a allowlist.

**Comment by Khrin** [comment]
https://github.com/easylist/easylistspanish/issues/294

**Comment by iam-py-test** [comment]
@Khrin curious why you chose to remove the rules?
