### ISSUE TITLE
3 incorrect domains: clickbicom, snortedbincom, webytom

### ISSUE THREAD

**Issue by Ad-Blokker** [easylist/easylist#14740]
### List the website(s) you're having issues:

```
- clickbicom
- snortedbincom
- webytom
```

### What happens?

Parsing error in pihole:

```
  [i] Analyzed 20420 domains, 3 domains invalid!
      Sample of invalid domains:
      - clickbicom
      - snortedbincom
      - webytom
```

### List Subscriptions you're using:

`https://easylist-downloads.adblockplus.org/easylist.txt`

```easylist:easylist/easylist_general_block.txt```

### Your settings

- Adblock Extension/version: 
`Pi-hole v5.15 ~ FTL v5.20.1 ~ Web Interface v5.18.1`

**Comment by Khrin** [comment]
EasyList isn't exactly suitable to be used in Pihole. I suggest you to use a different filter list.

**Comment by Ad-Blokker** [comment]
@Khrin I am using a mirrored parse version of easylist:
`https://v.firebog.net/hosts/Easylist.txt`

But as these domains originate from easylist and are not a parsing error I was reporting it here.

I made a issue on the mirrored parse version to see if it can be filtered on their end then:
https://github.com/WaLLy3K/wally3k.github.io/issues/174

**Comment by Khrin** [comment]
@Ad-Blokker Sorry, evidently forgot to tell you that actually I had removed the filters https://github.com/easylist/easylist/commit/a9e61441602ba82944e8517469cf5de7546d84f0 shortly before closing here.

**Comment by krystian3w** [comment]
Maybe enough add missed dots?

`clickbi.com`
`snortedbin.com`
`webyt.om` https://en.wikipedia.org/wiki/.om (Oman).
