### ISSUE TITLE
https://seb.se/ broken with EasyList Cookie enabled

### ISSUE THREAD

**Issue by MagerValp** [easylist/easylist#14758]
### List the website(s) you're having issues:

`https://seb.se/`

### What happens?

EasyList Cookie blocks the cookie popup, but remnants of overlay blocks any clicks to the page.

### List Subscriptions you're using:

EasyList Cookie

### Your settings

- OS/version: macOS 12.6.2
- Browser/version: Firefox 108.0.2
- Adblock Extension/version: uBlock Origin 1.46.0

**Comment by ryanbr** [comment]
We're not actually blocking it `seb.se#@#.pw-cookie-consent-v2`  Not using another cookie blocker?

**Comment by MagerValp** [comment]
No, no other cookie blocker, and toggling EasyList Cookie in the uBlock Origin settings made the popup reappear for me.

The issue is gone today though after refreshing the lists and clearing the uBO caches, so maybe I was stuck on an old version. I notice 26ec4f3ae7278c392cee0f6eee3d13bce6df27c2 with the fix was pushed 3 weeks ago.
