### ISSUE TITLE
serialomaniak.pl

### ISSUE THREAD

**Issue by lukjan32** [easylist/easylist#1476]
no icons are available for articles under the text, on the site serialomaniak.pl

![1](https://user-images.githubusercontent.com/17565773/42278633-c67d6c36-7f9b-11e8-855a-ebf98ece261d.jpg)

as I add to the exceptions

![2](https://user-images.githubusercontent.com/17565773/42278814-36d1cda6-7f9c-11e8-891b-843851e8d68f.jpg)

opera 54, ublocck origins

**Comment by peace2000** [comment]
This problem is still there. Problem is caused by Easyprivacy.

`@@||v1.addthisedge.com/live/$xhr,domain=serialomaniak.pl`
