### ISSUE TITLE
Canva -  product unusable on mobile web

### ISSUE THREAD

**Issue by jordanf97** [easylist/easylist#14762]
### List the website(s) you're having issues:
* `https://canva.com`

### What happens?

These issues are constrained to mobile usage of the product due to the CSS classnames listed within the block lists

**Without intentional configuration the product is broken out of the box on the Brave mobile browser due to default privacy settings.**

Primary and core functionality broken such as:
* login / signup
* Canva Editor usage
* Off-page sheet menus
* Anything which opens in a dialog or animates in after user interactions
  * This entails the majority of Canva usage and authentication flows

### List Subscriptions you're using:
Forgive me, I am unfamiliar with the usage of these lists or extensions such as uBlock Origin), but here are the offending CSS classnames I have identified.

* fanboy_notifications_specific_uBO.txt
  * nEyXsQ (unsure what the intention to block is here)
* easylist_cookie_specific_hide.txt (these elements are an attempt at blocking the mobile experience version of the cookie consent banner)
  * l7fLgw
  * S_i1pg

### Other details:
I'm an employee of Canva and we are interested in avoiding these widespread breakages of the product. 

At this stage we are unsure of the legal implications of supporting the blocking of these consent banners however I am interested in and open to discussing ways we can avoid misattributing these classnames in the future to avoid similar issues from resurfacing.

**Comment by ryanbr** [comment]
If the class names are not randomised we would probably not have this issue.. Should work better https://github.com/easylist/easylist/commit/14e1e44   The related claases:

```
! Mobile App Nag
! canva.com
canva.com##.BB_TDQ[style="height: auto; max-height: 66vh;"]
canva.com##body:style(overflow: auto !important; position: initial !important;)
```

```
! Cookie message
canva.com##.jv5LaQ
! Black overlay
www.canva.com##.nEyXsQ.aXUJ1A
```

**Comment by jordanf97** [comment]
Hey @ryanbr thanks for the quick response.

Unfortunately the below lines will cause the same issue:
* `www.canva.com##.nEyXsQ.aXUJ1A`
* `canva.com##.BB_TDQ[style="height: auto; max-height: 66vh;"]`

`.nEyXsQ.aXUJ1A` and `BB_TDQ` are reused throughout the product.

> If the class names are not randomised we would probably not have this issue..

It is an unfortunate side effect of maintaining uniqueness through standardised tooling for sure.

**Comment by jordanf97** [comment]
Can confirm that I'm seeing existing and new problems with the updated set of filters. 

I'm keen to discuss a way we can solve this issue without impairing the usability of the product

**Comment by krystian3w** [comment]
So `[style="height: auto; max-height: 66vh;"]` is not unique?

**Comment by jordanf97** [comment]
>So [style="height: auto; max-height: 66vh;"] is not unique?

`.BB_TDQ` is presented alongside the above associated style attributes as a default case across multiple usages. This will cause issues.

>In order for the cookie banner to leak, it would have to be pasted into a different place on the site each time and would not have stable attributes (completely new ones every refresh).

The cookie banner is not being correctly targeted on mobile, neither is the `mobile app nag`. With a correct selection of classnames it would work as expected, without hindering the product. Please keep in mind though that we can make no guarantee to the stability of these css hashes.
