### ISSUE TITLE
Outlook fake mail

### ISSUE THREAD

**Issue by fabi-hub** [easylist/easylist#14799]
> https://outlook.live.com/mail/0/

 (account required)

it's only showing up in Brave, but not Firefox + uBlock Origin

Fix: http://live.com/##.full.jYY8g

OS: Windows 11
Browser: Brave 
Filterlists: Fanboy Annoyances List and EasyList Germany

![Screenshot 2023-01-23 154106](https://user-images.githubusercontent.com/67245084/214969190-a0c589e4-7785-49a3-8f7c-6ddb014f1dd4.png)

**Comment by krystian3w** [comment]
Change Ads settings "layout" and ad will gone:

`https://outlook.live.com/mail/0/options/general/advertisement`

**Comment by krystian3w** [comment]
These maybe still works:

```adb
! one check with long css selector:

outlook.live.com#?#[data-app-section="MessageList"] > div[class]:-abp-has(> div:not([id]):not([class]) > div > div > div > div > div > div > button > span.fbAdCallToAction)

! two checks - children and neighbours:

outlook.live.com#?#[data-app-section="MessageList"] > div[class]:-abp-has(> div:not([id]):not([class]) button > span.fbAdCallToAction):has(~ div div[role="listbox"])
```

If you can drop use "Default Ads ('Recommended')" for ad Layout.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/137637

**Comment by fabi-hub** [comment]
> https://outlook.live.com/mail/0/options/general/advertisement
Looks on the phone like this now:
![757C6904-00D0-4E41-8F97-1AAD110D4CF2](https://user-images.githubusercontent.com/67245084/215477033-a30cf654-99b1-4559-9c5c-171093846113.png)

**Comment by krystian3w** [comment]
Filter was tested only on PC layout, you can move photo to first post to avoid omit cleanup mobile version by someone.

**Comment by fabi-hub** [comment]
On my PC I have no ad because I added http://live.com/##.full.jYY8g to the custom filterlist.
But custom filters are not possible/available on Brave for iOS.

**Comment by krystian3w** [comment]
But your idea for PC can down if MS update any CSS file and rebuilt html template based on React technology.

**Comment by fabi-hub** [comment]
The two filters you posted don't work for me.

**Comment by Khrin** [comment]
Filters works just fine.

**Comment by krystian3w** [comment]
How works fine if newbie have ads on PC and mobile.
