### ISSUE TITLE
nytimes grey placeholder

### ISSUE THREAD

**Issue by fabi-hub** [easylist/easylist#14798]
`https://www.nytimes.com/2023/01/25/science/io-volcano-eruption.html
`
fix: http://nytimes.com/##.css-f6q96b

OS: Windows 11
Browser: Brave 
Filterlists: Fanboy Annoyances List and EasyList Germany

![Screenshot 2023-01-25 211311](https://user-images.githubusercontent.com/67245084/214968865-9f6afcbf-48ca-4fb6-a1a3-2d9dbcf4ad6b.png)

**Comment by Nojuuu** [comment]
Why `nytimes.com##div[id^="story-ad-"]` was removed from the list?

**Comment by fabi-hub** [comment]
For the annoyance list: nytimes.com##.magnoliaDock

![Screenshot 2023-01-28 021605](https://user-images.githubusercontent.com/67245084/215233675-ebd6590b-00c8-4956-ad24-9a30b6f30305.png)

**Comment by ryanbr** [comment]
> Why was `nytimes.com##div[id^="story-ad-"]` removed from the list?

Because its not used? just rechecked various nyt pages. Still not used.

**Comment by Nojuuu** [comment]
Those still show up for me

![image](https://user-images.githubusercontent.com/84513173/215333726-0e699f68-9119-4f06-bebf-bed6af74736e.png)

https://www.nytimes.com/2023/01/29/us/abortion-rights-state-constitutions.html
