### ISSUE TITLE
http://the-watch-series.to/

### ISSUE THREAD

**Issue by Panthere** [easylist/easylist#148]
https://github.com/easylist/easylist/blob/master/easylist/easylist_whitelist.txt#L2569

Why is this whitelisted?
It should not be whitelisted.
The pages work fine with it blacklisted.
Are you being paid by ad companies?

**Comment by monzta** [comment]
Is this exception rule causing any problems? If so, please elaborate.

**Comment by monzta** [comment]
Closing since there hasn't been any reply.
