### ISSUE TITLE
heise.de

### ISSUE THREAD

**Issue by fabi-hub** [easylist/easylist#14800]
> www.heise.de

fix: www.heise.de##.group-open

OS: Windows 11
Browser: Brave 
Filterlists: Fanboy Annoyances List and EasyList Germany

![heise](https://user-images.githubusercontent.com/67245084/214969909-c759b29f-46bd-4fcc-82ff-4266748dca62.png)

**Comment by Khrin** [comment]
This shouldn't be removed.
