### ISSUE TITLE
chargebee.com

### ISSUE THREAD

**Issue by cb-manideep** [easylist/easylist#14802]
### List the website(s) you're having issues:

- **https://app.chargebee.com**

### What happens?

AdBlock is blocking **chargebee.com** domain. Error in chrome - net::ERR_BLOCKED_BY_CLIENT. This is due to [this](https://github.com/easylist/easylist/commit/d7e203a2608920171214f7eda30b28b5efbd320b) commit. We are unsure on why this was added, any description is highly appreciated.

### List Subscriptions you're using:
- AdBlock

### Your settings

- OS/version: MacOS Montery 12.6.1
- Browser/version: 109.0.5414.87
- Adblock Extension/version: 5.3.3

### Other details:

Filter that is blocking it: https://github.com/easylist/easylist/commit/d7e203a2608920171214f7eda30b28b5efbd320b
PR to fix this: https://github.com/easylist/easylist/pull/14801

**Comment by cb-dhananjayavokkaliga** [comment]
@ryanbr - please can you look into this?

**Comment by cb-manideep** [comment]
Marking this as resolved. Ref: https://github.com/easylist/easylist/commit/ddb98c2e8b6177589e494fb26ac3ade113fd0464
