### ISSUE TITLE
finesthotels.net

### ISSUE THREAD

**Issue by kmnvq** [easylist/easylist#14818]
### List the website(s) you're having issues:

`https://www.finesthotels.net/hotel_list.php`

### What happens?

`track.freecallinc.com`

<details>
 <summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/215293103-f9ffde12-88af-4449-8c48-70953932984c.png)

</details>

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Tracking Protection, uBO filters

### Your settings

- OS/version: 
- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin 1.46

### Other details:

**Comment by ryanbr** [comment]
Not a tracker from what I see
