### ISSUE TITLE
game.co.uk

### ISSUE THREAD

**Issue by Lubrsi** [easylist/easylist#14831]
### List the website(s) you're having issues:

`<https://www.game.co.uk>`

### What happens?

Uncaught tracking domain: `<fourtimessmelly.com>`

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/25595356/215362658-9c4d5b5d-c6f0-4f8c-9bb4-8c898095cdde.png)

### Your settings

- OS/version: Ubuntu 22.04 LTS
- Browser/version: Firefox 109.0
- Adblock Extension/version: uBlock Origin 1.46.0

### Other details:

![image](https://user-images.githubusercontent.com/25595356/215362697-caffa47f-8ea0-4c19-b9f6-98d5e94cd28b.png)
Appears to be part of Cheq, see #13209 and #12408

**Comment by DandelionSprout** [comment]
It appears that the owners of `fourtimessmelly.com` currently also runs 52 other suspicious-looking domains across 6 IPs: https://securitytrails.com/list/ip/34.199.234.25
