### ISSUE TITLE
Image hidden on nocookielaw.com because of EasyList Cookie

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#14841]
### List the website(s) you're having issues:

nocookielaw.com

### What happens?

An image saying, simply, "The EU Cookie Law" is hidden because of `###eu-cookie-law` in EasyList Cookie

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by Sonic5435325** [comment]
lol, just realized I put "EasyList Privacy" in the name rather than EasyList Cookie, my bad

**Comment by krystian3w** [comment]
Possible rename title issue as don't locked to collaborators only.

**Comment by Sonic5435325** [comment]
@krystian3w Sorry lmao, I didn't know how to retitle names on here. I don't have much experience with GitHub, but it's fixed now.

**Comment by Sonic5435325** [comment]
Now I can finally close this.
