### ISSUE TITLE
writerscafe.org

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#14853]
Bad rule (?writerscafe.org)~>

 `/^https?:\/\/(.+?\.)?writerscafe\.org[\/]{1,}.*[a-zA-Z0-9]{3,7}\/[a-zA-Z0-9]{6,}\/.*/$image,domain=?writerscafe.org`

**EasyList**

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6e77a190b010f4f5959d756945687a09b89c0bfa
