### ISSUE TITLE
nypost.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#14855]
### What happens?

At the bottom of the page, there is usually a 2nd article link in between.

https://nypost.com/2023/01/10/im-a-real-life-she-hulk-i-love-my-natural-curvy-girl-muscles/ (Random link used to test the problem)

Adding these filters to "My Filters" seems to fix the problem:

`nypost.com#@#.single__outbrain`

`nypost.com#@#.ob-strip-layout`

`@@||images.outbrainimg.com/transform/v3/$image,domain=nypost.com`

Seems like the same thing happens on pagesix.com as well (But I don't think these filters work on that site for the problem)
https://pagesix.com/2023/01/30/shemar-moore-girlfriend-jesiree-dizon-obsessed-with-first-baby-together/

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBOL-issues/issues/7#issuecomment-1276046570

**Comment by krystian3w** [comment]
`#?#.more-stories > div.widget:-abp-has(> [class*="outbrain"])`

**Comment by Sonic5435325** [comment]
@ryanbr 
![Screenshot from 2023-02-02 20-16-19](https://user-images.githubusercontent.com/89158249/216487869-dc7231b4-2d96-409d-a5d5-6afe6698f7e9.png)

**Comment by Sonic5435325** [comment]
![Screenshot from 2023-02-02 20-17-34](https://user-images.githubusercontent.com/89158249/216487949-75299363-8d3f-4d56-b61b-7d773b3de2cf.png)

**Comment by ryanbr** [comment]
I'm fine leaving this, just too minor.
