### ISSUE TITLE
1337x.to

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#14861]
### List the website(s) you're having issues:

'https://www.1337x.to/popular-tv'

### What happens?

Advertise

### List Subscriptions you're using:

Default uBO

### Your settings

- OS/version: Windows 11
- Browser/version: uBO Latest
- Adblock Extension/version: 1.46.0

### Other details:

![image](https://user-images.githubusercontent.com/29574622/216109404-b892f3f0-689a-4265-9284-aa07cabebb31.png)

**Comment by ghajini** [comment]
`1337x.to##.filter-list + center`

**Comment by krystian3w** [comment]
Stable is:

> https://github.com/uBlockOrigin/uAssets/issues/16560#issuecomment-1408491807

`##[href*="/netflixPromo"] img`

But I guess someone maybe paste this on "forum" topics?

**Comment by ghajini** [comment]
not stable, except the filter added in https://github.com/uBlockOrigin/uAssets/commit/9310112ed36d4aa0f76c31e3af59e983de82db55 & you will see ad other than netflix

**Comment by krystian3w** [comment]
My point was that they didn't convert the link to a 301 redirect or graphics from raster to html5 or vector canvas.

**Comment by SeriousHoax** [comment]
Different but similar issue: `https://1337x.to/torrent/5792027/Baldur-s-Gate-3-Update-v4-1-1-3686210-Patch-2/`
![image](https://github.com/easylist/easylist/assets/29574622/368dc252-aac8-4917-9eb4-b4c778b05f29)

@krystian3w @ghajini Can you please check this?
