### ISSUE TITLE
Ad appearing

### ISSUE THREAD

**Issue by d4f5409d** [easylist/easylist#14872]
List the website(s) you're having issues:
'https://myonlineradio.hu/'

What happens?
Advertise

List Subscriptions you're using:
Default uBO

Your settings
OS/version: Android 13
Browser/version: uBO Latest
Adblock Extension/version: 1.46.0

Other details:

**Comment by DandelionSprout** [comment]
Should probably be closed and re-submitted to https://github.com/hufilter/hufilter-dev, if I understand the situation correctly.
