### ISSUE TITLE
canadafreepress.com breakage

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylist#14888]
### List the website(s) you're having issues:
https://canadafreepress.com

### What happens?
Website is broken due to EL filter `||canadafreepress.com/` 
looks like is missing an extra slash (` /`) in the end

### List Subscriptions you're using:
ABP + EL

### Your settings

- OS/version: 
- Browser/version: Opera 95.0.4635.25 
- Adblock Extension/version: ABP 3.16

### Other details:
<img width="1334" alt="cpws" src="https://user-images.githubusercontent.com/57706597/216681352-bd25501a-8801-4f6f-873e-00c97a43814a.png">

**Comment by krystian3w** [comment]
@gwarser/@gorhill this filter generate too strict block "modal" with uBo 1.46.1b18.
