### ISSUE TITLE
Optout urls also blocked

### ISSUE THREAD

**Issue by aardbol** [easylist/easylist#1489]
### List the website(s) you're having issues:

See an example list of many websites:
`https://paste.proxy.sh/?e16178278364d003#yDVUWeHpbYiBBwzKICVGi+2amegnJG5ZgMRvtH1NOWo=`

### What happens?

The Truste preference manager for cookies that many websites use can't apply the optout choices of the user to improve privacy because the Easylist filters based on domain names without excluding these new URLs which provide optout functionality to respect the GDPR law.

See an example of that manager on `spring.io` website

### List Subscriptions you're using:

Standard uBlock which includes Easylist and Easylist Dutch

### Your settings

- OS/version:  Antergos Linux latest
- Browser/version:  Waterfox  latest
- Adblock Extension/version:  ublock latest

**Comment by peace2000** [comment]
Doesn't seem relevant anymore. @Khrin

**Comment by llacb47** [comment]
I agree, not relevant. If you block ads you do not need to opt of out interest-based advertising.
