### ISSUE TITLE
Please consider removing "events.split.io" from the EasyPrivacy list as we offer consent settings now

### ISSUE THREAD

**Issue by patricioe** [easylist/easylist#14903]
### List the website(s) you're having issues:

`events.split.io`

### What happens?

I've spoken with some maintainers of this list before and we were ask to show settings around consent. Many of our customers are now exposing this to their users. We are a third party, so we don't own the UI per se. Here is the link to the privacy consent setting. 
Docs link here: https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#user-consent 

### List Subscriptions you're using:

I don't know if this applies here by it is EasyPrivacy

### Your settings

NA

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

NA

I'm grateful for your consideration.
Thank you.

**Comment by ryanbr** [comment]
Consents can also track, will need proof.

**Comment by patricioe** [comment]
@ryanbr do you care to elaborate what proof do you need? Is it code lines to show that consent don't track? or what is it?
