### ISSUE TITLE
Fanboys Annoyance List Prevents Scrolling on tiktok profile pages

### ISSUE THREAD

**Issue by BugsReporto** [easylist/easylist#14912]
### List the website(s) you're having issues:

Any tiktok profile page  
`https://www.tiktok.com/@USERNAME`

### What happens?

with **Fanboys Annoyance list** turned on, **i can't scroll** up and down using the scroll wheel.  
scrolling seems to work only on **fyp**, but not on **profile pages** (`tiktok.com/@**USERNAME**`).

after disabling it, scrolling works normally. so it seems like **Fanboys Annoyance list** is causing this.

### List Subscriptions you're using:

all ublock default and

-   Fanboy's Annoyance
-   Fanboy's Social
-   uBlock filters - Annoyances

### Your settings

-   OS/version: 10
-   Browser/version: 109.0.5414.120
-   Adblock Extension/version: uBlock Origin

### Other details:

with **Fanboys Annoyance list** turned on, **i can't scroll** up and down using the scroll wheel on **tiktok profile pages**.

**Comment by ryanbr** [comment]
Was fixed, force an update.
