### ISSUE TITLE
maritimeherald.com (video breakage)

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylist#14939]
### List the website(s) you're having issues:

`https://www.maritimeherald.com/`

### What happens?

Videos broken  

- sometimes videos on sites are blocked on purpose because they are video ads, as I see that with `@@||maritimeherald.com^$ghide,badfilter` the videos are hidden, so maybe they are intentionally hidden as ads
- but sometimes they are legitimate videos which are accidentaly broken
- as I'm not sure at 100% which is the case here, thus I've decided to report it anyway, in case it's invalid report, feel free to close it

### List Subscriptions you're using:

EasyList
EasyPrivacy

### Your settings

- OS/version: W
- Browser/version: 109
- Adblock Extension/version: uBO

### Other details:

![sss](https://user-images.githubusercontent.com/72945564/218088983-1f381fd1-9f1d-44d1-ace8-d51baade5c85.png)

**Comment by ryanbr** [comment]
Thats an video advert, it should remain blocked.
