### ISSUE TITLE
www.androidpolice.com Cosmetic Filtering

### ISSUE THREAD

**Issue by LambLeeg** [easylist/easylist#14955]
### List the website(s) you're having issues:

`https://www.androidpolice.com/`

A random article where problem occurs `https://www.androidpolice.com/chrome-custom-share-sheet/`

### What happens?

Ads are blocked, but cosmetic filtering is not done properly. As a result, mobile version has gaps.

### List Subscriptions you're using:

uBlock defaults + URL shorten lists. `EasyList`, `EasyPrivacy` and `Fanboy’s Annoyance` are enabled

### Your settings

I only use uBlock Origin (from an issue template list here)

- OS/version: Android 13 (OxygenOS 13)
- Browser/version: Firefox 109
- Adblock Extension/version: uBlock Origin 1.46 Stable

### Other details:

Here is a solution I am suggesting to include: `androidpolice.com##[id^=ad-]`
And here is a screenshot of a gap: [Photo](https://user-images.githubusercontent.com/59935189/218315862-70345c51-94ff-4c5b-9aa7-928805dd894e.JPG)

**Comment by garry-ut99** [comment]
Hello, most likely same reason: https://github.com/easylist/easylist/issues/14956#issuecomment-1427054061

**Comment by LambLeeg** [comment]
> Hello, most likely same reason: [#14956 (comment)](https://github.com/easylist/easylist/issues/14956#issuecomment-1427054061)

Yeah, lots of thanks!
