### ISSUE TITLE
introvertdear.com AdThrive cosmetic filtering

### ISSUE THREAD

**Issue by LambLeeg** [easylist/easylist#14956]
### List the website(s) you're having issues:

`https://introvertdear.com/`

A random article where problem occurs `https://introvertdear.com/news/how-introverts-can-make-friends-when-they-move-to-a-new-city/`

### What happens?

This site has nearly as much as 21 IDs for ads on Desktop, and the same amount of them for Phones. Desktop div IDs are blocked, but mobile ones are showing up.

### List Subscriptions you're using:

uBlock defaults + URL shorten lists. `EasyList`, `EasyPrivacy` and `Fanboy’s Annoyance` are enabled

- OS/version: Android 13 (OxygenOS 13)
- Browser/version: Firefox 109
- Adblock Extension/version: uBlock Origin 1.46 Stable

### Other details:

The thing is that Easy lists are aiming specifically per ID which is hassle to manage, hence I am suggesting to add this instead:  `introvertdear.com##[id^=AdThrive_]`. It will make site clear with no need to manually add a new ID because they always are started with `AdThrive_`

And here is a screenshot: [Photo](https://user-images.githubusercontent.com/59935189/218317351-2a51d7a5-fb79-4f59-9a61-68c9147714bd.JPG)

**Comment by garry-ut99** [comment]
In uBO this option: https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#ignore-generic-cosmetic-filters
is by default turned OFF on Desktop, however it's by default turned ON on Mobile, which causes gaps appear on Mobile, however once turned back OFF, the gaps are gone:
![rrr](https://user-images.githubusercontent.com/72945564/218318507-3355796b-b769-4884-8a65-8f229f070bbd.png)

**Comment by LambLeeg** [comment]
> In uBO this option: https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#ignore-generic-cosmetic-filters is by default turned OFF on Desktop, however it's by default turned ON on Mobile, which causes gaps appear on Mobile, however once turned back OFF, the gaps are gone: ![rrr](https://user-images.githubusercontent.com/72945564/218318507-3355796b-b769-4884-8a65-8f229f070bbd.png)
> 
> On reasonably Mobile devices the option can be disabled, as in practice it's only for low-end Mobile devices.

Well, that's it! The strangest part is that I made my config on a PC, then synced to the phone, and somehow uBO re-enables it, although config is literally saying not to. Very strange. By the way, I am still suggesting to add this rule because it's easier to maintain. Anyways, it feels odd what uBO does 😅

Thanks!

**Comment by garry-ut99** [comment]
> LambLeeg: The strangest part is that I made my config on a PC, then synced to the phone, and somehow uBO re-enables it, although config is literally saying not to. Very strange. Anyways, it feels odd what uBO does 😅

Hey, I'm not sure, but maybe that isn't an uBO's issue, but a Firefox's:

> https://github.com/uBlockOrigin/uBlock-issues/wiki/Cloud-storage (at the very bottom): 
> It appears Firefox for Android can not sync extension settings. This is tracked in [Bugzilla Report #1625257](https://bugzil.la/1625257).

**Comment by LambLeeg** [comment]
> > LambLeeg: The strangest part is that I made my config on a PC, then synced to the phone, and somehow uBO re-enables it, although config is literally saying not to. Very strange. Anyways, it feels odd what uBO does 😅
> 
> Hey, I'm not sure, but maybe that isn't an uBO's issue, but a Firefox's:
> 
> > https://github.com/uBlockOrigin/uBlock-issues/wiki/Cloud-storage#firefox (at the very bottom):
> > It appears Firefox for Android can not sync extension settings. This is tracked in [Bugzilla Report #1625257](https://bugzil.la/1625257).

Well, default sync is broken there. That's true. I do all sync with the Syncthing which is FOSS alternative to clouds. I used txt config file from my PC. Anyways, I prefer Brave as my daily driver, and it works flawlessly. I suppose, that this, and the second thread may be closed, since the suggestion is made, and the reason is found. Thank you!

**Comment by garry-ut99** [comment]
Hey, ok, GitHub allows to close threads by yourself: 
https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue
<img src="https://user-images.githubusercontent.com/72945564/218324703-ed9261df-e0f4-4f00-af63-ae87e7014ae9.png" height="250" >
