### ISSUE TITLE
[NSFW] Many big ad placeholders in group of porn sites (US)

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylist#14954]
### List the website(s) you're having issues:

`https://www.pornfelix.com/`
`https://www.pornfelix.com/videos/no-cock-is-as-hard-as-her-tits-2256/`
`pornfelix.com,porndrake.com,pornblade.com,porntommy.com,hd-easyporn.com`

### What happens?

Big ad placeholders all over the site, mainpage + subpages.
( For (DE) see here: https://github.com/easylist/easylistgermany/issues/250 )
Solution: add websites to already existing filter:
https://github.com/easylist/easylist/blob/67f87942558db7d225dfab02073d57692e1a0922/easylist/easylist_specific_hide.txt#L3558

or to https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_hide_abp.txt :
`pornfelix.com,porndrake.com,pornblade.com,porntommy.com,hd-easyporn.com#?#aside:-abp-has(>div>.adsbyexoclick)`

### List Subscriptions you're using:

uBlock filters, AG Base, AG Tracking, EasyList, EastPrivacy

### Your settings

- OS/version:
- Browser/version: 
- Adblock Extension/version: 

### Other details:

![SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218305818-e29c9bb9-7f0d-4e5e-ad2d-d148356e8a2a.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b1c42e523e0853804dba84b1074e5ab5b9644b99

**Comment by garry-ut99** [comment]
> https://github.com/easylist/easylist/commit/b1c42e523e0853804dba84b1074e5ab5b9644b99

@ryanbr that removes only ads, but the ad placeholders are still here
