### ISSUE TITLE
Section hidden in privacy policy, caused by EasyList Cookie

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#14992]
### List the website(s) you're having issues:

https://cookieinformation.com/cookie-and-privacy-policy/

### What happens?
A "Cookie Policy" section is caused by the filter `###cookie-policy-section` in EasyList Cookie.
The page with the filter on:
![Screenshot from 2023-02-15 15-24-10](https://user-images.githubusercontent.com/89158249/219146318-e71f112b-8daa-4e7b-98d3-f796663142ed.png)

The page with the filter off:
![Screenshot from 2023-02-15 15-24-19](https://user-images.githubusercontent.com/89158249/219146410-3013e131-c31d-4d44-a7cc-7a75eb10aff2.png)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
I expect some breakages when viewing privacy policys.
