### ISSUE TITLE
washingtonpost.com EasyPrivacy breaks video

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#150]
https://www.washingtonpost.com/local/public-safety/federal-appeals-court-questions-dcs-restrictions-on-concealed-carry-of-firearms/2016/09/20/03a757a0-7f41-11e6-9070-5c4905bf40dc_story.html

EasyPrivacy breaks the video.

**Comment by Khrin** [comment]
Fixed by https://github.com/easylist/easylist/commit/f73568994b9abd30b23f405a6ba743154f531edc
