### ISSUE TITLE
BuzzFeed.com (and a bunch of other sites) - Blocked videos (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#15018]
### Affected sites:
`https://www.buzzfeed.com/`
..and a bunch of other ones, listed by **IosebAlavidze** in this post:
https://github.com/easylist/easylist/issues/15018#issuecomment-1448390666

### Issue:
Blocked videos.

### Example:
`https://www.buzzfeed.com/marycolussi/excellent-book-adaptations/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **EasyList**

### Problem rule:
`||connatix.com^$third-party,domain=~accuweather.com|~elnuevoherald.com|~loot.tv|~miamiherald.com`

### Possible fix:
```
- ||connatix.com^$third-party,domain=~accuweather.com|~elnuevoherald.com|~loot.tv|~miamiherald.com

+ ||connatix.com^$third-party,domain=~accesousa.com|~accuweather.com|~bellinghamherald.com|~bnd.com|~bradenton.com|~buzzfeed.com|~centredaily.com|~charlotteobserver.com|~easternstandardtimes.com|~elnuevoherald.com|~flkeysnews.com|~fresnobee.com|~heraldonline.com|~heraldsun.com|~idahostatesman.com|~islandpacket.com|~kansas.com|~kansascity.com|~kentucky.com|~ledger-enquirer.com|~loot.tv|~macon.com|~mahoningmatters.com|~mcclatchy.com|~mcclatchydc.com|~mercedsunstar.com|~miamiherald.com|~modbee.com|~myrtlebeachonline.com|~newsbreakapp.com|~newsobserver.com|~olivesoftware.com|~riverfronttimes.com|~sacbee.com|~sanluisobispo.com|~schoology.com|~star-telegram.com|~sunherald.com|~thenewstribune.com|~theolympian.com|~thestate.com|~tri-cityherald.com
```

### Temp fix (and some `$important` rules for AdGuard and uBO users):
```
@@||connatix.com^$third-party,domain=buzzfeed.com|accesousa.com|bellinghamherald.com|bnd.com|bradenton.com|buzzfeed.com|centredaily.com|charlotteobserver.com|easternstandardtimes.com|flkeysnews.com|fresnobee.com|heraldonline.com|heraldsun.com|idahostatesman.com|islandpacket.com|kansas.com|kansascity.com|kentucky.com|ledger-enquirer.com|macon.com|mahoningmatters.com|mcclatchy.com|mcclatchydc.com|mercedsunstar.com|modbee.com|myrtlebeachonline.com|newsbreakapp.com|newsobserver.com|olivesoftware.com|riverfronttimes.com|sacbee.com|sanluisobispo.com|schoology.com|star-telegram.com|sunherald.com|thenewstribune.com|theolympian.com|thestate.com|tri-cityherald.com
||connatix.com^*/pixel?$important
||connatix.com/rtb/$important
||connatix.com/tr/$important
||ck.connatix.com^$important
||tr.connatix.com^$important
||trk.connatix.com^$important
```

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v109.0.1-2 (x64) (Tracking Protection = Standard)
* Adblock Extension/version: uBlock Origin v1.47.0

**Comment by IosebAlavidze** [comment]
Similar issues of connatix players being blocked form

```
https://www.easternstandardtimes.com/
https://www.easternstandardtimes.com/episode/docs-monterey-park
```

And all McClatchy Newspaper sites - https://www.mcclatchy.com/

```
charlotteobserver.com
thestate.com
kansascity.com
miamiherald.com
sacbee.com
star-telegram.com
newsobserver.com
sanluisobispo.com
mcclatchydc.com
ledger-enquirer.com
fresnobee.com
macon.com
kansas.com
bnd.com
modbee.com
idahostatesman.com
islandpacket.com
thenewstribune.com
bradenton.com
centredaily.com
heraldonline.com
myrtlebeachonline.com
sunherald.com
kentucky.com
tri-cityherald.com
theolympian.com
elnuevoherald.com
mercedsunstar.com
olivesoftware.com
heraldsun.com
flkeysnews.com
accesousa.com
bellinghamherald.com
mahoningmatters.com
newsbreakapp.com
schoology.com
riverfronttimes.com
```
_Some of the above have already been unblocked as part of this rule_

```
||connatix.com^$third-party,domain=~accuweather.com|~elnuevoherald.com|~loot.tv|~miamiherald.com
```

Important documentaries and award winning videos are unplayable because the domain connatix.com is blocked.

**Comment by THEtomaso** [comment]
OK, first post updated!

**Comment by THEtomaso** [comment]
@Yuki2718:
This might linger for a while..
It might be prudent to put my temp fix _(see first post)_ into **uBlock filters - Unbreak** for now.

**Comment by ryanbr** [comment]
`And all McClatchy Newspaper sites - https://www.mcclatchy.com/`

Literally all video ads.

**Comment by ryanbr** [comment]
https://www.buzzfeed.com/marycolussi/excellent-book-adaptations/

Also a video advert.

**Comment by ryanbr** [comment]
@THEtomaso  Did you even check these? They're nothing like an embedded youtube video. All the they do is video slideshows.

**Comment by IosebAlavidze** [comment]
@ryanbr McClatchy publications use these players at the top of the most article pages, as well as homepages, to provide content associated with the articles:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/97808420/222033862-27d6c581-5cf5-4490-9fda-566392b5dd2d.png">
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/97808420/222034148-effbccec-0e07-4099-abf8-f017c88005a9.png">

There's a secondary slideshow unit seems to drive traffic to other videos as you pointed out,
<img width="615" alt="image" src="https://user-images.githubusercontent.com/97808420/222035639-8a12ed50-a86e-4f35-817b-7e2de5cebe73.png">

These domains use the player as a true video player, granted with ads like youtube, but if ads aren't even coming from connatix.com, by the looks of it it seems to be doubleclick and the like which are already blocked, there shouldn't be issues I don't think.

**Comment by ryanbr** [comment]
They're literally just video ad slide shows, nothing to with the content of the webpage. which is why its blocked. 

https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt#L453

Note the amount of video ad spam around, and connatix is no different and should be treat exactly the same way as the others.

**Comment by THEtomaso** [comment]
> Did you even check these?

I checked the ones at `buzzfeed.com`, which was the site in my original report.
Someone made me aware that something was broken over there, so I looked into it, and confirmed that the blocked videos are related to the articles were they're embedded.

Also, I checked some of the sites that **IosebAlavidze** mentioned yesterday, and confirmed that the videos were related to the articles there as well.
I checked some more of those sites just now, and all of them contains relevant videos.
I agree that they don't excactly contain in-depth type of material, but they're definitiely related to the articles, nevertheless!
A couple more examples:
`https://www.theolympian.com/news/local/article272617070.html`
`https://www.tri-cityherald.com/news/coronavirus/article272566472.html`

**Comment by THEtomaso** [comment]
@MasterKia / @Yuki2718:
This needs to be `$badfilter`'ed too now:
https://github.com/easylist/easylist/commit/6a09712a1874f3e56363f643959da02a691a7316
(to confirm, simply check the first example link in my previous post)

**Comment by THEtomaso** [comment]
If possible, perhaps you could come up with a `##+js` rule to stop Connatix videos from autoplaying too?

**Comment by stephenhawk8054** [comment]
> > Did you even check these?
> 
> I checked the ones at `buzzfeed.com`, which was the site in my original report. Someone made me aware that something was broken over there, so I looked into it, and confirmed that the blocked videos are related to the articles were they're embedded.
> 
> Also, I checked some of the sites that **IosebAlavidze** mentioned yesterday, and confirmed that the videos were related to the articles there as well. I checked some more of those sites just now, and all of them contains relevant videos. I agree that they don't excactly contain in-depth type of material, but they're definitiely related to the articles, nevertheless! A couple more examples: `https://www.theolympian.com/news/local/article272617070.html` `https://www.tri-cityherald.com/news/coronavirus/article272566472.html`

I think we need to distinguish a bit more. The videos are just relevant to the article, but it does not contain any of the main content such as the title or the article.

There's a difference between

```
https://www.buzzfeed.com/marycolussi/excellent-book-adaptations/
```
and
```
https://www.charlotteobserver.com/video/3/11122290/5fb7235690ef3c0a20b7dcfd
https://www.thestate.com/news/local/crime/article272622488.html
```

The video in `buzzfeed` does not have any information of the title or article. On the other hand, the `charlotteobserver` and `thestate` video shows exactly what the title and the article are showing.

**Comment by IosebAlavidze** [comment]
This [Pulitzer finalist investigative series](https://www.pulitzer.org/finalists/miami-herald) from McClatchy for example heavily relies on video to tell the story.

https://www.miamiherald.com/news/special-reports/florida-prisons/article177510156.html
https://www.miamiherald.com/news/special-reports/florida-prisons/article176773291.html#tales
https://www.miamiherald.com/news/special-reports/florida-prisons/article177885221.html
https://www.miamiherald.com/news/special-reports/florida-prisons/article177857061.html

Each one of the article pages could have upwards of 5-10 interviews and important documentary footage.

In this case miamiherald.com is already whitelisted and that's what should happen with other mcclatchy newspapers imo to allow them to tell their stories in similar ways.

https://www.easternstandardtimes.com/ heavily relies on these players for showcasing documentaries.

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/97808420/222185361-622d87dc-354b-4b9c-a6ab-a8bd5ebbd08f.png">
The entire landing page is a the documentary/player covering a very important and tragic event of the Monterey Park shooting.

**Comment by stephenhawk8054** [comment]
That's what I meant. The `buzzfeed` example is not good. You can check they serve their real video content via youtube: `https://www.buzzfeed.com/videos`

> They're literally just video ad slide shows, nothing to with the content of the webpage.

@ryanbr Can you check these links, not just looking at the `buzzfeed` one only. The whole video section is broken. The video is not slideshow and the content of the video is exactly like the description

```
https://www.charlotteobserver.com/video
https://www.thestate.com/video
...
```

I'm not sure why they are different than

```adb
||connatix.com^$third-party,domain=~accuweather.com|~elnuevoherald.com|~loot.tv|~miamiherald.com
@@||connatix.com*/connatix.player.$script,domain=ebaumsworld.com|funker530.com|washingtonexaminer.com
```

**Comment by Yuki2718** [comment]
@Alex-302 I'll remove the rules added to Base and leave this to EL and your decision.

**Comment by Yuki2718** [comment]
Of note, I used badfilter as a temporal solustion expecting EL to take some action. I mostly agree to @stephenhawk8054 's comment.

**Comment by Alex-302** [comment]
@Yuki2718 But why you removed from our filter? Wide blocking rule is still exists.

**Comment by Yuki2718** [comment]
@Alex-302 You know the situation. If you agree on the rules I added, you can revert my last commit.

**Comment by Alex-302** [comment]
@Yuki2718 Restored.

**Comment by IosebAlavidze** [comment]
I believe the conclusion has to be that mcclatchy publications have to be treated equally and given equal opportunity to showcase videos that they produce for users. EL breaks site layout and UX in these cases. 

For [El Nuevo Herald](https://www.elnuevoherald.com/noticias/florida/hialeah/article272614315.html), the existing rule already takes care of the slideshow from appearing but still allows for video to show and not break pages. Unlike on Kansas City for example where the homepage player and [/video](https://kansascity.com/video) pages are outright broken.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/97808420/222210148-14159270-10fc-4ee9-a292-93296c7e1583.png">

Like I mentioned before this is what Eastern Standard Time looks like with and without the filter
![image](https://user-images.githubusercontent.com/97808420/222210668-46b12452-9a8f-490f-b350-4e5fc9cf70cf.png)
vs
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/97808420/222210613-c5381903-b3d0-4d90-ae7e-daeaed714cf5.png">

@THEtomaso mentioned this already but this seems to be a fix.

```
- ||connatix.com^$third-party,domain=~accuweather.com|~elnuevoherald.com|~loot.tv|~miamiherald.com

+ ||connatix.com^$third-party,domain=~accesousa.com|~accuweather.com|~bellinghamherald.com|~bnd.com|~bradenton.com|~centredaily.com|~charlotteobserver.com|~easternstandardtimes.com|~elnuevoherald.com|~flkeysnews.com|~fresnobee.com|~heraldonline.com|~heraldsun.com|~idahostatesman.com|~islandpacket.com|~kansas.com|~kansascity.com|~kentucky.com|~ledger-enquirer.com|~loot.tv|~macon.com|~mahoningmatters.com|~mcclatchy.com|~mcclatchydc.com|~mercedsunstar.com|~miamiherald.com|~modbee.com|~myrtlebeachonline.com|~newsbreakapp.com|~newsobserver.com|~olivesoftware.com|~riverfronttimes.com|~sacbee.com|~sanluisobispo.com|~schoology.com|~star-telegram.com|~sunherald.com|~thenewstribune.com|~theolympian.com|~thestate.com|~tri-cityherald.com
```

**Comment by Yuki2718** [comment]
@Alex-302 Also needs `#@#.wps-player-wrap` now e.g. `https://www.charlotteobserver.com/video/3/11122290/5fb7235690ef3c0a20b7dcfd`

**Comment by IosebAlavidze** [comment]
> @Alex-302 Also needs `#@#.wps-player-wrap` now e.g. `https://www.charlotteobserver.com/video/3/11122290/5fb7235690ef3c0a20b7dcfd`

@Yuki2718 Not sure if this changed anything but now miamiherald, loot.tv and others from the old filter are unplayable too

Example: https://loot.tv/video/671591

**Comment by stephenhawk8054** [comment]
I'll restore Kia's allowing version as `badfilter` is not a good idea in general.

**Comment by Yuki2718** [comment]
> but now miamiherald, loot.tv and others from the old filter are unplayable too

I restored the my rules and disabled Unbreak and Quick, can't reproduce. I don't understand how that happens TBH, unless I had typo in the commit.
