### ISSUE TITLE
tamilblasters.rent

### ISSUE THREAD

**Issue by Tetrax-10** [easylist/easylist#15010]
### List the website(s) you're having issues:

https://tamilblasters.rent/

### What happens?

I see ads

### Your settings

- OS/version: Windows 11 Home - 22H2 - 22621.1105
- Browser/version: Chrome - Version 110.0.5481.104 (Official Build) (64-bit)
- Adblock Extension/version: 1.46.0

### Other details:

![image](https://user-images.githubusercontent.com/75513645/219728608-97e50905-d988-4d2d-9bb3-c6b94f6e1eef.png)

**Comment by DandelionSprout** [comment]
I propose `1tamilblasters.site##.ipsResponsive_hideTablet`
