### ISSUE TITLE
weather.us

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylist#15012]
### List the website(s) you're having issues:

`https://weather.us/model-charts/euro/significant-weather.html`

### What happens?

Big ad placeholder.

### List Subscriptions you're using:

EasyList, EasyPrivacy, AG Base, AG Tracking

### Your settings

- OS/version: Win
- Browser/version: 
- Adblock Extension/version: 

### Other details:

[SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219782049-194a9007-c43b-42e5-8372-6445e89cad6d.png)

**Comment by partingscientist** [comment]
@garry-ut99 I think this issue can be closed, seems to be solved [here](https://github.com/easylist/easylist/blob/53110b7ade5de56d66a0d65e8a3b68a2b3333fb2/easylist/easylist_specific_hide.txt#L1966).
