### ISSUE TITLE
[Fanboy's Social] Add Shareon to the list

### ISSUE THREAD

**Issue by kytta** [easylist/easylist#15037]
### List the website(s) you're having issues:

<https://shareon.js.org/>

### What happens?

I am a developer of the [Shareon](https://github.com/kytta/shareon) share buttons. I envision those to be as ethical as possible, which is why I also would like them to actually be blocked by the ‘social’ ad blockers.

Right now, when I use the Fanboy's Social Blocking List (uBO edition), only some buttons supported by Shareon disappear. Others continue to function. Although my buttons aren't sending any data anywhere, I think it would make sense to block the element as well as the init script for them.

### List Subscriptions you're using:

- uBlock built-in filters
- EasyList
- EasyPrivacy
- Actually Legitimate URL Shortener Tool (by DandelionSprout)
- Online Malicious URL Blocklist (urlhaus)
- Anti-Facebook
- **Fanboy's Social**
- Peter Lowe’s Ad and tracking server list
- EasyList Germany
- StevenBlack/hosts

### Your settings

- OS/version: macOS Monterey version 12.6.2 (21G320)
- Browser/version: LibreWolf 110.0-1 (based on Firefox 110)
- Adblock Extension/version: uBlock Origin 1.47.0

### Other details:

If you want to block Shareon, you'd need to block:

- the `.shareon` CSS selector
- `shareon.*.js` which loads the script to initialize the buttons
- `shareon.min.css` which loads the styles for the buttons

[See the docs](https://shareon.js.org/#install) for more info

**Comment by krystian3w** [comment]
Something was added secretly: https://github.com/easylist/easylist/commit/b7d4259325bd4f1846c2146095c2c12515132a0a

**Comment by ryanbr** [comment]
so secret it was referenced in https://github.com/easylist/easylist/pull/15038
