### ISSUE TITLE
webbikeworld.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#15048]
### List the website(s) you're having issues:

`https://www.webbikeworld.com/motogp-dorna-sues-finnish-kymiring-circuit/`

### What happens?

An ad below the main image for a raffle held by a different company, and a small placeholder below the top "Premium Membership" notice that is also covered by the proposed entry below.

### List Subscriptions you're using:

<details><summary>Screenshot:</summary

![image](https://user-images.githubusercontent.com/22780683/220598814-29bd4c4e-b23d-4e03-b92d-f74479b49499.png)

</details>

### Your settings

- OS/version: Windows 11 22H2 x64
- Browser/version: Chrome 110.0.5481.104 x64
- Adblock Extension/version: uBO 1.46.0 + IDCAC 3.4.6

### Other details:

I propose `webbikeworld.com##div[class*=" block-da-"]`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/220601802-1aa34ea2-bc53-42b7-a2f8-4c3bc65a74b1.png)

</details>

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e98678bbc85a137e2f43807fcf680a2744548bee
