### ISSUE TITLE
guildeducation.com [breakage]

### ISSUE THREAD

**Issue by harpobarpo** [easylist/easylist#15053]
### List the website(s) you're having issues:
<code>https://guildeducation.com</code> (after logging into my student account)
Sub pages like home.guildeducaiton.com and applications.guildeducation.com have errors

### What happens?
Trying to access "Career Accelerator", which just launched for my org, but the section on the home page is blank. I found it in the navigation menu, and when clicking on it the page just redirects to the home page. I cannot access this tool without turning off the extension or the list. 
Similar things happen across other pages, like not being able to use the new school application page. I can't apply for a school right now, but its possible that its broken for other users and so they can't apply to school without the new application page.

### List Subscriptions you're using:
EasyList & EasyPrivacy (EasyPrivacy is the culprit)

### Your settings
- OS/version: MacOS 13.2
- Browser/version: Chrome 110
- Adblock Extension/version: uBlock 1.46.0

### Notes

This site must be using optimizely for new feature releases or at least for enabling features to specific clients. This site does not serve any ads - its a paid membership program. The inaccessible content is valuable and so this breakage is problematic for them.

### Potential solutions

There are two blocked requests when EasyPrivacy is on, which are not blocked when EasyPrivacy is off (which is when the Career Accelerator is visible).
1. optimizely.guildeducation.com is blocked
2. cdn.optimizely.com is blocked

Consider adding this site to the allowlist, similar to what was done for Nike, Starbucks, and others
<code>! easyprivacy_allowlist.txt#L288</code>
<code>- @@||optimizely.com/datafiles/$domain=nike.com|talktalk.co.uk|wallapop.com</code>
<code>+ @@||optimizely.com/datafiles/$domain=guildeducation.com|nike.com|talktalk.co.uk|wallapop.com</code>
<code>+ @@||optimizely.guildeducation.com/$domain=guildeducation.com</code>

### Screen shots

*See the blank "Career Accelerator" section*
<img width="964" alt="Screenshot 2023-02-21 at 10 19 00 AM" src="https://user-images.githubusercontent.com/1881968/220395090-9e53b554-fd6b-40b8-a0ae-3108ac497290.png">

*See "Career Accelerator" in Nav - Clicking on it redirects back to Home*
<img width="964" alt="Screenshot 2023-02-21 at 10 20 58 AM" src="https://user-images.githubusercontent.com/1881968/220395237-ec712012-0a7a-49fe-b135-f4230bcae91b.png">
<img width="964" alt="Screenshot 2023-02-21 at 10 21 18 AM" src="https://user-images.githubusercontent.com/1881968/220395322-11b0fdcb-e509-4602-aed6-83c7810e4028.png">

*When EasyPrivacy off, section is no longer blank and page loads fine*
<img width="1023" alt="Screenshot 2023-02-21 at 10 25 02 AM" src="https://user-images.githubusercontent.com/1881968/220395413-93bb60f4-9ae0-4ac7-955d-d42e125dd153.png">
<img width="1023" alt="Screenshot 2023-02-21 at 10 24 47 AM" src="https://user-images.githubusercontent.com/1881968/220395434-3dfd72dd-7b18-4551-9ee7-76c824f44f07.png">

**Comment by ryanbr** [comment]
What url items are being blocked?

**Comment by jacobmclocklin** [comment]
Thank you @ryanbr - These urls are blocked:
https://optimizely.guildeducation.com/optimizelyjs/15213110278/s/production.js
https://optimizely.guildeducation.com/optimizelydatafile=DtbAqkCj9CcwLzsBL8RiRX.json
https://cdn.optimizely.com/datafiles/DtbAqkCj9CcwLzsBL8RiRX.json

**Comment by harpobarpo** [comment]
Thanks @ryanbr - I found these blocked urls in the ublock logger:

https://optimizely.guildeducation.com/optimizelyjs/15213110278/s/production.js
https://optimizely.guildeducation.com/optimizelydatafile=*.json
https://cdn.optimizely.com/datafiles/*.json

**Comment by ryanbr** [comment]
Any further changes needed should be done on your side.
