### ISSUE TITLE
Burger menu not working on meaww.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15074]
### List the website(s) you're having issues:

https://meaww.com/what-is-daisys-destruction-pervert-josh-duggar-search-dark-web-vile-hurtcore-porn-18-month-infant

### What happens?

The burger menu next to the social items on the top right doesn't work unless you add `@@||m2.ai^$script,domain=meaww.com`

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by THEtomaso** [comment]
The `m2.ai` scripts are already whitelisted through **uBlock filters - Unbreak**.
However, since it also appears to need `@@||googletagservices.com/tag/js/gpt.js$domain=meaww.com`, this might be a better choise in this case:
`meaww.com##.search-and-ham`

**Comment by Sonic5435325** [comment]
@THEtomaso Works fine for me without allowing googletagservices.com, what platform are you on?

**Comment by THEtomaso** [comment]
Desktop.

The cookie consent needs to be whitelisted too now, btw.
..which in turn, requires even more dubious whitelistings!
Think I'll rather steer clear of this one.

**Comment by Sonic5435325** [comment]
m2.ai seems to no longer be required for the menu button to function (Or even load at all) and this issue is sort of old so I think it's best that I close this.
