### ISSUE TITLE
Anti-AdBlock on gemini.yahoo.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15085]
### List the website(s) you're having issues:

https://gemini.yahoo.com/advertiser/home

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

![Screenshot from 2023-02-26 15-26-34](https://user-images.githubusercontent.com/89158249/221435373-36889f34-9082-4293-9252-88f5a0ad7c9f.png)

**Comment by ghajini** [comment]
does this cause any ad to be on page

`gemini.yahoo.com#@#.ads`

**Comment by Sonic5435325** [comment]
no

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/labels/Anti-Adblock = https://github.com/easylist/easylist/labels/Invalid

**Comment by THEtomaso** [comment]
..and if you want those ad examples to be displayed, like they're supposed to:
```
@@||yimg.com^*/carouselads.*$media,domain=gemini.yahoo.com
@@||yimg.com^*/video_ad_*$image,domain=gemini.yahoo.com
@@||yimg.com^*/videoads.*$media,domain=gemini.yahoo.com
```
