### ISSUE TITLE
Request to add filters for https://andscape.com/

### ISSUE THREAD

**Issue by joebagadonuts188** [easylist/easylist#15105]
### List the website(s) you're having issues:

`https://andscape.com/features/on-his-60th-birthday-23-little-known-sneaker-stories-about-michael-jordan/`

### What happens?

There is an issue with the formatting of this site because of the following filter:

`##.ad-prevent-jump`

I wanted to suggest adding an exception for this domain and use the following:

`andscape.com#@#.ad-prevent-jump`

I also wanted to request to add the following filters to EasyList for the website:

```
andscape.com##div[class$="tease--ad"]
andscape.com##div[class="ad-banner"]
andscape.com##div[class="ad-prevent-jump"]
```

### List Subscriptions you're using:

easylist: 61201-60, now
easyprivacy: 30886-1281, now
ublock-abuse: 77-1, now
ublock-badware: 4196-118, now
ublock-filters: 32063-196, now
ublock-privacy: 260-2, now
ublock-quick-fixes: 510-20, now
ublock-unbreak: 1868-49, now
urlhaus-1: 6612-3, now
adguard-spyware-url: 897-2, 1m
curben-phishing: 22544-0, 1m
fanboy-cookiemonster: 45207-198, 1m

### Your settings

- OS/version: Win 10 21H1
- Browser/version: Version 110.0.5481.178 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.47.2

### Other details:

I know it may seem like I am being counterintuitive by suggesting to disable a filter and then want to add one just like it back, but the filter I am suggesting (i.e. `andscape.com##div[class="ad-prevent-jump"]`) will work more effectively and block it on the front page but not on the individual pages of the site where it can cause problems.

**Comment by ryanbr** [comment]
Not seeing these issues.
