### ISSUE TITLE
zdnet.com - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#15107]
### List the website(s) you're having issues:

- `https://www.zdnet.com/`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 110
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/222387329-25717652-de2b-4185-94d1-7c18694bbdae.png">

**Comment by ryanbr** [comment]
Resolved @alexm92  ?

**Comment by alexm92** [comment]
@ryanbr yes, I don't see the dialog anymore. Thank you 🙏
