### ISSUE TITLE
tvtropes.org

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#15123]
### List the website(s) you're having issues:

`https://tvtropes.org/pmwiki/pmwiki.php/Trivia/DisneyFairies`

### What happens?

Placeholders above (Measured to 90px tall) and to the right of pages.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/22780683/223018583-ad8b4fdc-9dc2-4461-a7ca-5c0f5af56060.png)

</details>

### Your settings

- OS/version: Windows 11 22H2 x64
- Browser/version: Chrome 110.0.5481.178 x64
- Adblock Extension/version: uBO 1.47.4 + IDCAC 3.4.6

### Other details:

I propose:
```
tvtropes.org##div[id*=ad-wrapper]
tvtropes.org#?#.sidebar-item:has(> .sidebar-section)
```

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/223018468-000a2166-8a63-4e5b-889a-a5b9d359ba6f.png)

</details>

**Comment by alastortenebris** [comment]
For the sidebar ad frame, `tvtropes.org##div[class^="square_fad"]` should also work.

It seems that the ad frames have `fad` in their class name.

**Comment by DandelionSprout** [comment]
Seems like `tvtropes.org##.fad` has been added in the meantime and is fixing the top banner, at least for now. The sidebar frames still need to be fixed, for which I see multiple possible methods including yours.

**Comment by Daxy7** [comment]
`##.ad` works as standalone but does it break anything else?

[Image (uBlock Origin)](https://user-images.githubusercontent.com/91396482/229954701-cfd19df9-7db9-4bc6-958b-3c39053d666a.png)
