### ISSUE TITLE
genius.com

### ISSUE THREAD

**Issue by alastortenebris** [easylist/easylist#15136]
### List the website(s) you're having issues:

`https://genius.com/Nile-cast-down-the-heretic-lyrics`
### What happens?

On a mobile user agent, giant ad frames are left over.
### List Subscriptions you're using:

Default uBlock + Fanboy's Annoyance
### Your settings

- OS/version: Windows 11
- Browser/version: Firefox 111.0b8
- Adblock Extension/version: uBlock Origin 1.47.5b0

### Other details:

![Screenshot 2023-03-06 at 23-45-36 Nile – Cast Down the Heretic](https://user-images.githubusercontent.com/100882069/223283049-80d7a9a5-b6e3-4851-94be-0d7675f42b46.png)

`genius.com##div[class^="InreadContainer"]` and `genius.com##div[class^="InnerSectionAd__Container"]` seems to fix the issue, though I cannot say for sure if that breaks anything else.

**Comment by alastortenebris** [comment]
The leftover ad frames are still there. I have verified this with two different browsers.

**Comment by Daxy7** [comment]
ryanbr used `genius.com##.cujBpY` which is prob random on page restart so...

**Comment by alastortenebris** [comment]
The class is used on one of the ad frames. Sadly it was the small one at the bottom.

If we're blocking by that method, then `genius.com#.duLgkj` needs to be added as well.

`genius.com##div[class^="InreadContainer"]` also works as well.
