### ISSUE TITLE
razer.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#15143]
Policies notice ...

- https://i.imgur.com/4bRnoon.png

```adblock
/consent_banner.
gold.razer.com##.component-sticky-dialog
```

- `https://gold.razer.com/global/en`
- `https://www.razer.com/gaming-laptops/razer-blade-16`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/078a887f4eb3e54b600be94447684cfccfa8f859
