### ISSUE TITLE
penguinrandomhouse.com cookie banner 

### ISSUE THREAD

**Issue by RayBB** [easylist/easylist#15160]
Seen at: https://www.penguinrandomhouse.com/authors/2274998/madison-van-oort

Apologies for not following the template, reporting from mobile.

![Screenshot_20230308-105041.png](https://user-images.githubusercontent.com/921217/223680614-6fd080bd-2128-43a5-ba2c-d9742e4e5b5f.png)

![Screenshot_20230308-105105.png](https://user-images.githubusercontent.com/921217/223680644-0c5d5616-a5b7-43a4-9949-9f3bc5794391.png)

**Comment by Khrin** [comment]
Hi, I do see the cookie banner correctly blocked. Do you have the options "Parse and enforce cosmetic filters" enabled and "Ignore generic cosmetic filters" disabled?

**Comment by RayBB** [comment]
I didn't change the default settings (that I know of) but it looks like  "Ignore generic cosmetic filters" was enabled? Disabling that fixes the issue.

Thank you!
