### ISSUE TITLE
misteryinternet.com Bottom of page hidden because of EasyList

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15175]
### List the website(s) you're having issues:

https://www.misteryinternet.com

### What happens?
An element is hidden by EasyList which makes a normal element disappear. I fixed it with `misteryinternet.com#@##footer-ads`

Screenshot 1, with element hiding on: 
![Screenshot from 2023-03-09 17-29-26](https://user-images.githubusercontent.com/89158249/224175516-2221fbcd-cefa-43d1-a8fe-6cc32421d7e8.png)

Screenshot 2, with element hiding off: 
![Screenshot from 2023-03-09 17-30-07](https://user-images.githubusercontent.com/89158249/224175600-36d39bbf-b3a3-4f5c-bfb5-8143e0dcac06.png)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by Khrin** [comment]
@Sonic5435325 Open in https://github.com/easylist/easylistspanish/issues
