### ISSUE TITLE
tempr.email: block not hide ##.af-table-wrapper 

### ISSUE THREAD

**Issue by BigGiantHeadsHighCommander** [easylist/easylist#1517]
my uBlock Origin settings
https://gist.github.com/BigGiantHeadsHighCommander/7a95bf46e6f1d1b7dc75849cf9011250

### List the website(s) you're having issues:

`tempr.email`

sneaky content difficult to discern source

### What happens?

load site
create DEA mailbox
cruft after blocking with these

`! 7/9/2018, 1:15:26 AM https://tempr.email/inbox.htm
||images-eu.ssl-images-amazon.com/*$image,domain=tempr.email
||tempr.email/www.amazon.de/*
||www.tempr.email/www.amazon.de/*
||produkte.appfield.net/*
||nur.gratis/*
||tempr.email/inbox.htm$inline-script,first-party
`

### List Subscriptions you're using:

most of them

### Your settings

- OS/version:  windows 10
- Browser/version:  current waterfox and iridium
- Adblock Extension/version:  uBlock Origin v1.16.12, and Nano AdBlock v1.0.0.53, respectively

### Other details:

I do not want to hide the remnant.  I want to prevent its generation

`class="af-table-wrapper"`

![not hide do block generation](https://user-images.githubusercontent.com/40991806/42445788-0f8659e8-8329-11e8-8e1a-a30dafe53a6c.png)

**Comment by peace2000** [comment]
Is this still relevant @BigGiantHeadsHighCommander ?

Some translation to English would be nice as many people don't speak German :)

**Comment by Khrin** [comment]
I don't see any unblocked adveerts...

@peace2000 This website is also available in different languages.
