### ISSUE TITLE
https://improving.duckduckgo.com/t/fb*

### ISSUE THREAD

**Issue by TheGoodsAreOdd** [easylist/easylist#15173]
### List the website(s) you're having issues:

```
https://improving.duckduckgo.com/t/fb*
```

### What happens?

When I explicitly choose to share feedback with DuckDuckGo about their site, easylist appears to be blocking the feedback from being sent. Specifically, all of the `https://improving.duckduckgo.com/t/fb*` requests are blocked, sending my feedback to `/dev/null` instead of to DuckDuckGo.

This can be reproduced by going to `https://duckduckgo.com/?q=easylist` and clicking on the "Share Feedback" button on the bottom right of the page. Select any of the feedback options, positive or negative, and they will all be blocked.

### List Subscriptions you're using:

The defaults with uBlockOrigin. I believe it is `EasyPrivacy` which is resulting in this feedback being blocked. Specifically, [this line](https://github.com/easylist/easylist/blob/23241e4f392542a862784d727dc7ff8629f88e40/easyprivacy/easyprivacy_specific.txt#L318).

### Your settings

- OS/version: macOS Ventura 13.2.1
- Browser/version: Firefox 110.0.1 
- Adblock Extension/version: uBlock Origin 1.47.2

### Other details:

I don't think my explicit attempts to share feedback with a site should result in it being blocked. It looks like `https://improving.duckduckgo.com/t/` is [used to send other pixels by DuckDuckGo](https://help.duckduckgo.com/duckduckgo-help-pages/privacy/atb/), which I'm fine being blocked. I'd like for any of the `https://improving.duckduckgo.com/t/fb*` requests to not be blocked since it appears those are used to submit explicit feedback.

For reference, this sort of feedback is not blocked on any other search engine (Google, Bing, Brave, etc.).

**Comment by TheGoodsAreOdd** [comment]
Ran into this again today with `improving.duckduckgo.com/t/fbp_maps_no...`. Looks like there's a few `fb*` (feedback?) endpoints, not just `fbs`.

**Comment by ryanbr** [comment]
No thanks, nothing seen here:

![ddg](https://github.com/easylist/easylist/assets/1659004/f8854e2b-7d3f-4928-83a7-e4c7a31d7a9d)

**Comment by TheGoodsAreOdd** [comment]
@ryanbr Thank you for taking a look. Did you submit feedback on the DuckDuckGo site using the "Share Feedback" button at the bottom of the page? That is what is being blocked (`improving.duckduckgo.com/t/fb*`) and is being proposed to be unblocked since the user is explicitly trying to provide feedback. I just retested and it is still being blocked by this list; what do you mean by "nothing seen here"? Thank you again.

**Comment by johnnynoone** [comment]
This applies both to the "Share Feedback" button at the bottom of the page and to the thumbs up/down below the "Search Assist" (AI) box. (Both regular and AI feedback buttons are now hidden by the "AdGuard – Popup Overlays" filter in case you happen to use it. Of course "EasyList – AI Widgets" hides the whole "Search Assist" box.)

I want to help DDG improve their search results, Wikipedia links, etc. I have noticed by accident  that the `||duckduckgo.com/t/` line from EasyPrivacy blocks this. I have been sending feedback for years, wanting to help DDG compete with Google and it turns out it was all wasted.

Log snippet of submitting negative feedback using the "Share Feedback" button in the lower right corner of the screen:
<details><summary>Logger output</summary>

After clicking to submit the whole feedback, including text explanation:
```
+70
||duckduckgo.com/t/
--
duckduckgo.com
1
get
image
https://improving.duckduckgo.com/t/fbs_negative_duckchat_incorrectResponse?7842075&rl=us-en&whichad=all&adgood=&adt=&adsrc=&adsnippet=&vertical=web&has_prev_submission=1&feedback_type=negative&prompt_category=generic&category=duckchat&reason=INCORRECT_RESPONSE&q=Under%20the%20Security%20Action%20for%20Europe%2C%20at%20least%20two%20countries%20must%20buy%20the%20same%20product.%20This%20requirement%20is%20initially%20lifted%2C%20but%20until%20when%3F&ct=PL&d=d&adblock_exp=a&aiheaderexp=b&biaexp=b&disableredditmetadataexp=b&duckaiinautocomplete=b&duckchat_alpha=b&externalmapsexp=b&litexp=a&m3adexp=a&msvrtexp=b&searchbarexp=b&toolexp=b&weatherexp=b
```
```
+70
||duckduckgo.com/t/
--
duckduckgo.com
1
get
image
https://improving.duckduckgo.com/t/feedback_request?9506849&ct=PL&d=d&rl=us-en&adblock_exp=a&aiheaderexp=b&biaexp=b&disableredditmetadataexp=b&duckaiinautocomplete=b&duckchat_alpha=b&externalmapsexp=b&litexp=a&m3adexp=a&msvrtexp=b&searchbarexp=b&toolexp=b&weatherexp=b
```
```
+70
||duckduckgo.com/t/
--
duckduckgo.com
1
get
image
https://improving.duckduckgo.com/t/feedback_submission?8776074&rl=us-en&whichad=all&adgood=&adt=&adsrc=&adsnippet=&vertical=web&has_prev_submission=1&feedback_type=negative&prompt_category=generic&category=duckchat&reason=INCORRECT_RESPONSE&comment=The%20real%20answer%20is%20May%2030%2C%202026.%20https%3A%2F%2Feur-lex.europa.eu%2Flegal-content%2FEN%2FTXT%2F%3Furi%3DCELEX%3A32025R1106&q=Under%20the%20Security%20Action%20for%20Europe%2C%20at%20least%20two%20countries%20must%20buy%20the%20same%20product.%20This%20requirement%20is%20initially%20lifted%2C%20but%20until%20when%3F&ct=PL&d=d&adblock_exp=a&aiheaderexp=b&biaexp=b&disableredditmetadataexp=b&duckaiinautocomplete=b&duckchat_alpha=b&externalmapsexp=b&litexp=a&m3adexp=a&msvrtexp=b&searchbarexp=b&toolexp=b&weatherexp=b
```
```
+70
duckduckgo.com
1
post
xhr
https://duckduckgo.com/collect.js?type=feedback
```


After clicking Share Feedback, then thumbs down, then selecting Duck.ai:
```
+5
||duckduckgo.com/t/
--
duckduckgo.com
1
get
image
https://improving.duckduckgo.com/t/feedback_reason_selection?3708785&prompt_category=generic&feedback_type=negative&feedback_reason=duckchat&q=Under%20the%20Security%20Action%20for%20Europe%2C%20at%20least%20two%20countries%20must%20buy%20the%20same%20product.%20This%20requirement%20is%20initially%20lifted%2C%20but%20until%20when%3F&ct=PL&d=d&rl=us-en&adblock_exp=a&aiheaderexp=b&biaexp=b&disableredditmetadataexp=b&duckaiinautocomplete=b&duckchat_alpha=b&externalmapsexp=b&litexp=a&m3adexp=a&msvrtexp=b&searchbarexp=b&toolexp=b&weatherexp=b
```
```
+3
||duckduckgo.com/t/
--
duckduckgo.com
1
get
image
https://improving.duckduckgo.com/t/fbe_negative_generic?778616&rl=us-en&whichad=all&adgood=&adt=&adsrc=&adsnippet=&vertical=web&has_prev_submission=1&adblock_exp=a&aiheaderexp=b&biaexp=b&disableredditmetadataexp=b&duckaiinautocomplete=b&duckchat_alpha=b&externalmapsexp=b&litexp=a&m3adexp=a&msvrtexp=b&searchbarexp=b&toolexp=b&weatherexp=b
```
```
+2
||duckduckgo.com/t/
--
duckduckgo.com
1
get
image
https://improving.duckduckgo.com/t/feedback_prompt_engagement?8653675&rl=us-en&whichad=all&adgood=&adt=&adsrc=&adsnippet=&vertical=web&has_prev_submission=1&feedback_type=negative&prompt_category=generic&prompt_variant=floating-button&q=Under%20the%20Security%20Action%20for%20Europe%2C%20at%20least%20two%20countries%20must%20buy%20the%20same%20product.%20This%20requirement%20is%20initially%20lifted%2C%20but%20until%20when%3F&ct=PL&d=d&adblock_exp=a&aiheaderexp=b&biaexp=b&disableredditmetadataexp=b&duckaiinautocomplete=b&duckchat_alpha=b&externalmapsexp=b&litexp=a&m3adexp=a&msvrtexp=b&searchbarexp=b&toolexp=b&weatherexp=b
```
```
+0
duckduckgo.com
1
get
script
https://duckduckgo.com/dist/wpm.dax-heart-animation.293b80f2dd35035e13c3.js
```
```
+0
duckduckgo.com
1
get
script
https://duckduckgo.com/dist/wpm.feedback-modal.c415c33edf35cb283ca0.js
```
```
+0
duckduckgo.com
1
get
script
https://duckduckgo.com/dist/wpm.thumb-animation.6cca9373db86efb68bc4.js
```
```
+0
duckduckgo.com
1
get
script
https://duckduckgo.com/dist/wpm.3871.81d961f901aebcc1defc.js
```
</details>
