### ISSUE TITLE
[Easylist Cookie] staysafeonline.org

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#15193]
### List the website(s) you're having issues:
`https://staysafeonline.org/resources/manage-your-privacy-settings/`

### What happens?
Cookie banner

### List Subscriptions you're using:
Fanboy annoyance

### Your settings

- OS/version: Windows 11
- Browser/version: Edge
- Adblock Extension/version: uBO

**Comment by Nojuuu** [comment]
Fixed already?

**Comment by yokoffing** [comment]
There's a scroll-to-top button on the page for Annoyances.

**Comment by yokoffing** [comment]
@Nojuuu Appears so now.
