### ISSUE TITLE
Social list blocks image

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#152]
http://www.droid-life.com/2016/09/23/twitter-to-sell/

Social list blocks the image. Though I can see why it wants to block it, it shouldn't be blocked lol

**Comment by terrorist96** [comment]
@ryanbr

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/f336f642dd7a1a6b44ac709a3f1cbdafb19f2bf8
