### ISSUE TITLE
game.granbluefantasy.jp

### ISSUE THREAD

**Issue by alastortenebris** [easylist/easylist#15214]
### List the website(s) you're having issues:

`https://game.granbluefantasy.jp/`
### What happens?

Potential Analytics Domain
### Your settings
Default + Annoyance

- OS/version: Windows 11
- Browser/version: Microsoft Edge 111.0.1661.41 
- Adblock Extension/version: uBlock Origin 111.0.1661.41

### Other details:

`https://event-api.analytics.mbga.jp/nbpf` is loaded when you login to the game. Blocking it seems to have no adverse effects.

**Comment by partingscientist** [comment]
@alastortenebris I cannot reproduce this. Is this still an issue?
