### ISSUE TITLE
Cookie message on dailymotion.com

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#15236]
### List the website(s) you're having issues:
`https://www.dailymotion.com/video/x2hxxet`

### What happens?
![dailymotion cookie notice](https://user-images.githubusercontent.com/11689349/225924787-3398f348-7608-487f-82db-5cb886b4de79.png)

### List Subscriptions you're using:
Fanboy Annoyance

**Comment by ryanbr** [comment]
Breaks too much if we attempt to hide it. @yokoffing
