### ISSUE TITLE
search.brave.com: privacy

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#15235]
### List the website(s) you're having issues:
`https://search.brave.com/search?q=best%20student%20credit%20card`

### What happens?
Telemetry script:
![Screenshot_20230317_170644](https://user-images.githubusercontent.com/17685483/225920279-e0274188-c5c9-40b9-b974-1e794cfad924.png)

Ad-related request:
![Screenshot_20230317_170734](https://user-images.githubusercontent.com/17685483/225920451-1e29e08a-42d4-461a-8054-943b84acb3ae.png)

The div containing that request belongs to an ad:
![Screenshot_20230317_170812](https://user-images.githubusercontent.com/17685483/225920595-ed6f28b3-1ca2-408a-8cfa-156d95f44191.png)

### Your settings

- OS/version: 
- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin

### Other details:

Proposed filters:
```adb
||cdn.search.brave.com/serp/v1/static/serp-js/telemetry^$script,1p
||search.anonymous.ads.brave.com/v1/search/view^$xhr,1p
```

"AdGuard Tracking Protection" already has:
`||cdn.search.brave.com/serp/*/static/serp-js/telemetry/`

**Comment by Khrin** [comment]
Resolved.
