### ISSUE TITLE
https://godbolt.org/  - Blocking sponsors (not advertisements) of an Open Source project isn't very nice.

### ISSUE THREAD

**Issue by pbrubaker** [easylist/easylist#15245]
This commit started blocking the top sponsors of the Open Source and non-commercial project http://godbolt.org.  This small banner links to a sponsor page on the website and not to the sponsor's website.

https://github.com/easylist/easylist/commit/1b067510b37cb38139bf4fd841b6ec0d2c04db53

Since these sponsors enable the site to be free, and help fund the Open Source development of Compiler Explorer, I request that this block be removed.

![image](https://user-images.githubusercontent.com/6944373/226111551-f61ea790-f578-4d87-92c2-fcc8032a2578.png)

**Comment by ryanbr** [comment]
regardless of opensource or not, not playing favourites, this is an advert no? 

As is the link to the shop. @pbrubaker

**Comment by pbrubaker** [comment]
It is not an advertisement.  It links to a sponsor page on the host website.

![image](https://user-images.githubusercontent.com/6944373/226168334-03757a38-8ed3-4f75-94b9-2a5ed406837d.png)

**Comment by pbrubaker** [comment]
Hey @ryanbr, have you given this any thought?

**Comment by pbrubaker** [comment]
Hey @ryanbr, just following up with this.  It seems there's some more positive interest in this issue (based on the reactions) since I last checked it.  Would it be possible to remove this?
