### ISSUE TITLE
babia.to

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#15243]
https://babia.to/threads/axtra-digital-agency-creative-portfolio-theme.81264/

cookies notice

**Comment by Nojuuu** [comment]
https://github.com/easylist/easylist/pull/16225/commits/9ac8c49d67708047e64e28602366baae5c706ccc fixed it.

**Comment by partingscientist** [comment]
@3xploiton3 if you can verify the fix, you can close the issue.

**Comment by 3xploiton3** [comment]
thanks, it work
