### ISSUE TITLE
coincodex.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [easylist/easylist#1525]
![2018 coincodex](https://user-images.githubusercontent.com/5884000/42534778-d4474818-848d-11e8-9433-eab1606a577b.png)
`https://coincodex.com/crypto/bitcoin/`

ad in down bar

https://github.com/uBlockOrigin/uAssets/issues/1795

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.47
 Chr 65.0.3325.181
</details>

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c613c523a1361d996a13d700330bf440a4287987
