### ISSUE TITLE
my.visualstudio.com/Downloads

### ISSUE THREAD

**Issue by Merlin2001** [easylist/easylist#15271]
### List the website(s) you're having issues:

`https://my.visualstudio.com/Downloads`

### What happens?

Instead showing available products to download the page forwards to https://my.visualstudio.com/Errors?e=46 (which shows the following error message):

![image](https://user-images.githubusercontent.com/13134791/226593574-7f134327-2842-4ce6-9ebb-03d192a76c4b.png)

### List Subscriptions you're using

uBlock Origin built-in, EasyList, EasyPrivacy (unchecking EasyPrivacy "fixes" the issue :))

<details>
<summary>List of all checked lists in uBlock Origin</summary>

![image](https://user-images.githubusercontent.com/13134791/226593884-7d495aee-2f3a-48d5-ac0c-ac64c7c2f9c0.png)

</details>

### Your settings

- OS/version: Microsoft Windows 10 Enterprise/10.0.19045 Build 19045
- Browser/version: Microsoft Edge/111.0.1661.44 (Official build) (64-bit)
- Adblock Extension/version: uBlock Origin/1.47.2

Tested also in Chrome/111.0.5563.65 (Official Build) (64-bit) with only uBlock Origin/1.47.4 installed.

### Other details

I disabled EasyPrivacy and manually added all the rules that I could see blocking in the logger.  
**Disabling only the rule `/fp/tags.js` made the site work again**:

```
# /fp/tags.js
||fpt.microsoft.com^
||msecnd.net/scripts/a/ai.
||usabilla.com^$3p
||browser.events.data.microsoft.com^
```

![image](https://user-images.githubusercontent.com/13134791/226598371-8e07d4f9-f5f7-4298-881e-c8509a03fbab.png)

**Comment by ryanbr** [comment]
Fine here. https://github.com/easylist/easylist/commit/c7ec2ee8da0579ab17db7df058ce069067d2aa7f may help in other instances.

**Comment by krystian3w** [comment]
You have bought subscription? Opens `https://my.visualstudio.com/Benefits` IMO is not "solved".
