### ISSUE TITLE
linkdecode.com

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylist#15289]
### List the website(s) you're having issues:

`https://www.linkdecode.com/`

### What happens?

AD banner at right side.

### Other details:

[SCREENSHOOT](https://user-images.githubusercontent.com/72945564/227455634-b323390d-ee01-4296-ae12-bfe123d577b7.png)

**Comment by partingscientist** [comment]
This issue should be fixed with https://github.com/easylist/easylist/commit/66e881aadb3606c0a3b82683eb05e1d3eb36c472. The maintainer decided not to remove the obvious header leftover. If it is satisfactory, the issue can probably be closed.
