### ISSUE TITLE
esi.evetech.net: EVE API Endpoint being blocked

### ISSUE THREAD

**Issue by Robbilie** [easylist/easylist#1529]
### List the website(s) you're having issues:
```https://esi.evetech.net/latest/characters/affiliation/```

### What happens?

JSON API Calls fail.

### List Subscriptions you're using:

I use uBlock Origins default subscriptions and we had to submit a change to another list in the past

### Your settings

uBlock tells me this list is the cause for the blocking and the easylist_general_block.txt file contains the line /affiliation/*

**Comment by Khrin** [comment]
Example page where this element is blocked?

**Comment by Robbilie** [comment]
```https://esi.evetech.net/ui/#/Character/post_characters_affiliation```

**Comment by Robbilie** [comment]
Any API request to the URL mentioned in the issue...

**Comment by Khrin** [comment]
Fixed.

**Comment by Khrin** [comment]
Hi @haggen , it doesn't seems like I'm unable to find any hits for this filter. Do I have to follow any particular procedure to replicate the issue on your site? (Which I presume it is `https://localthreat.xyz/`)

**Comment by haggen** [comment]
@Khrin Use this link https://localthreat.xyz/87k5jY5jO

**Comment by haggen** [comment]
Hi @Khrin. First of all that last commit seem to have fixed the issue, thank you! I'm still a bit confused though. If you have the time, would you mind clearing some things out for me?

1. Why my domain was added to a whitelist? Shouldn't the rule about the term `affiliation` be modified instead?
2. Speaking of which, the rule seemed to have the required exception (the `$domain=~esi.evetech.net` part, although I don't really know the syntax). Why wasn't this working? 
3. Does the whitelist rule extend to subdomains of localthreat.xyz?

Again, thanks for everything!
