### ISSUE TITLE
voicethread.com/myvoice/ Social list

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#153]
voicethread.com/myvoice/

Social list blocks the sharing button on this site. The share button provides critical functionality that is unrelated to facebook or twitter. Please whitelist this site and its subdomains (e.g. XXX.voicethread.com).

@ryanbr

**Comment by terrorist96** [comment]
From the console:
###share-menu

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/55fb0d34fcf813c752c2613094bd008bab50122a
