### ISSUE TITLE
guides.wp-bullet.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#15309]
```adblock
||guides.wp-bullet.com/wp-content/uploads/*banner
```

- `A: https://guides.wp-bullet.com/`

**Comment by DandelionSprout** [comment]
I propose `guides.wp-bullet.com##.widget_custom_html`

**Comment by partingscientist** [comment]
This issue can be closed, fixed in https://github.com/easylist/easylist/commit/e764324946cea45b8ab405553a73376307c66ffd
