### ISSUE TITLE
buffstream.fun

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#15310]
Invalid filter (easylist): `buffstream.fun##[href^="https://s.click.aliexpress.com/“]`

The closing quotes are in an unsupported encoding.

See also: https://github.com/easylist/easylist/commit/027623f771c597a33febd855c73e058ca3e59f7a

**Comment by DandelionSprout** [comment]
The entry appears to been fixed or removed at some point afterwards.
