### ISSUE TITLE
amazon.fr

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#15321]
**social**

```adblock
||amazon.*/stores/slot/share?
```

- https://i.imgur.com/pp3uF55.png

```
https://www.amazon.fr/stores/slot/share?slashargs=&pageId=D6B8B829-11F7-400C-95DA-AE3951490E78
```

- `A: https://www.amazon.fr/stores/page/D6B8B829-11F7-400C-95DA-AE3951490E78`

---

**social**

```adblock
##.ssf-share-trigger
```
- https://i.imgur.com/bD50zRz.png

**privacy**
```adblock
||metrics.media-amazon.com^
||m.media-amazon.com/images/G/01/msa/vowels/metrics.
```

- `https://m.media-amazon.com/images/G/01/msa/vowels/metrics._STID776721-1679881532114_.jpg`
- `https://m.media-amazon.com/images/G/01/msa/vowels/metrics._STID793378-1679886853062_.jpg`

**cookie**

```adblock
-cookieConsent&
```
```
https://m.media-amazon.com/images/I/01C10v4TaxL.css?AUIClients/ShoppingPortalAssets-cookieConsent&+GWn0usX#409907-T2`
https://m.media-amazon.com/images/I/017CuoJsDnL.js?AUIClients/ShoppingPortalAssets-cookieConsent&+GWn0usX#409907-T2`
```
- `A: https://www.amazon.fr//dp/B09J14D2WN/`

**Comment by 0o5rlubm** [comment]
for the privacy one, i don't have any `||m.media-amazon.com/images/G/01/msa/vowels/metrics.` on my browser. On what page are you?

**Comment by smed79** [comment]
> for the privacy one, i don't have any ...

- https://i.imgur.com/yemUphx.png (update)
- https://i.imgur.com/pVRAqUM.png

> On what page are you?

nothing special, the request loads for me if i browse to the home page -> do a search -> navigate to an article
e.g `https://www.amazon.fr/s?k=drone&crid=B3Y6QAW5OHWK&ref=nb_sb_ss_ts-doa-p_1_4`

**Comment by 0o5rlubm** [comment]
I'm sorry I closed the issue with only a part handled. Can you reopen it?

**Comment by smed79** [comment]
@ryanbr
