### ISSUE TITLE
thebaffler.com

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#15330]
Locked scroll at: `https://thebaffler.com/latest/after-the-war-on-cancer-watson`

So a little outdated are: https://github.com/easylist/easylist/pull/13034

https://github.com/easylist/easylist/blob/314062de53c854f1f256b331564c820c7702d400/fanboy-addon/fanboy_annoyance_specific_hide.txt#L3605
https://github.com/easylist/easylist/blob/314062de53c854f1f256b331564c820c7702d400/fanboy-addon/fanboy_annoyance_specific_hide.txt#L3320

**Comment by ryanbr** [comment]
No issues here @krystian3w
