### ISSUE TITLE
(cookies) nordvpn.com

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#15335]
https://nordvpn.com/servers/

![image](https://user-images.githubusercontent.com/19517680/228160859-cf052f21-4a67-4799-be7b-a0b679a7ee5a.png)

**Comment by krystian3w** [comment]
Poland got diffrent:

```adb
##.GDPRConsent--widget.GDPRConsent
```

`https://nordvpn.com/pl/servers/`

![image](https://user-images.githubusercontent.com/35370833/228235015-ceec71f7-a060-4855-915b-8a066eb5f5ea.png)
