### ISSUE TITLE
comick.app ad placeholder

### ISSUE THREAD

**Issue by Uranite** [easylist/easylist#15334]
### List the website(s) you're having issues:
`https://comick.app/comic/my-noble-family-is-headed-for-ruin-so-i-may-as-well-study-magic-in-my-free-time`
`https://comick.app/comic/my-noble-family-is-headed-for-ruin-so-i-may-as-well-study-magic-in-my-free-time/BEG72-chapter-1-en`

### What happens?
Ad placeholder at the top of the page

### List Subscriptions you're using:
uBlock Origin default

### Your settings
uBlock Origin default

- OS/version: Windows 11
- Browser/version: Firefox 111.0.1
- Adblock Extension/version: uBlock Origin 1.47.4

**Comment by ryanbr** [comment]
I must be blind, the site looks fine @Uranite

**Comment by krystian3w** [comment]
Under header exist big gap (without open comic):

```adb
##.items-center.lg\:h-\[251px\].h-\[126px\].w-full.justify-center.flex
```

After disable uBo on 3-rd refresh is loaded graphic ad (maybe ads by Google).

**Comment by Uranite** [comment]
![Screenshot_2023-03-29-21-27-37-769_org mozilla fenix](https://user-images.githubusercontent.com/62639703/228570976-45cffa5e-332a-49e2-a9b7-763816ae84d7.jpg)
![Screenshot_2023-03-29-21-27-47-085_org mozilla fenix](https://user-images.githubusercontent.com/62639703/228571006-c2110460-c1f6-4935-8ba0-cb3c13d0dd08.jpg)
Notice the big gap, seems like the place has changed on the first link, sorry I'm unable to take screenshots on pc right now, but it should be at the same place

**Comment by krystian3w** [comment]
On Firefox **Mobile** enforce enable generic filters:

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#ignore-generic-cosmetic-filters

due exsit weak phones is disabled.

**Comment by Uranite** [comment]
> On Firefox **Mobile** enforce enable generic filters:
> 
> https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#ignore-generic-cosmetic-filters
> 
> due exsit weak phones is disabled.
> 
> > ### Ignore generic cosmetic filters
> > Uncheck this option if you do not want cosmetic filters from various filter lists to be parsed and enforced. This option is mostly of interest for those who want to further reduce uBO's memory and CPU footprint. Cosmetic filtering has no value privacy-wise, its only purpose is to [hide elements](https://github.com/gorhill/uBlock/wiki/Does-uBlock-Origin-block-ads-or-just-hide-them%3F) on a web page that can't be blocked otherwise. An example of this is the ads served with some Google Search results.
> > Note that if you disable this option, your own custom cosmetic filters in `My Filters` (if any) will still be enforced.

The gap is still there on PC, disabling 'Ignore generic cosmetic filters' doesn't help, but thanks anyway

**Comment by Uranite** [comment]
So, on pc it's gone now, but theres still a small ad placeholder in this link (see red arrow)
https://comick.app/comic/00-i-became-the-despised-granddaughter-of-the-powerful-martial-arts-family/EfEs5c3c-chapter-29-en
![Screenshot 2023-04-02 at 19-49-42 Read manhwa I Became the Despised Granddaughter of the Powerful Martial Arts Family Chapter 29 (English)](https://user-images.githubusercontent.com/62639703/229354020-96b380d8-c14d-4d08-a36f-d999f5b0d088.png)

**Comment by krystian3w** [comment]
too small to cut, on pic have less than 30px, EasyList may need +100px of height.

**Comment by Uranite** [comment]
Alright, I will close this issue then.
