### ISSUE TITLE
polygon.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#15339]
### URLs

- `https://www.polygon.com/23658403/john-wick-box-office-success-future-movies`

### Description

`.ad__athena_internal`

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/110956608/228330505-1f65aa98-218f-40ec-9d44-56788306468d.png">

### Settings

<details>

```yaml
uBlock Origin: 1.47
Firefox: 111.0
listset:
  added:
    adguard-spyware-url
    block-lan
    adguard-annoyance
    ublock-annoyances
    dpollock-0
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
Too minor
