### ISSUE TITLE
apartmenttherapy.com, thekitchn.com, cubbyathome.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#15341]
### URLs

- `https://www.cubbyathome.com/kids-room-ideas-80024864`
- `https://www.thekitchn.com/kenji-lopez-alt-scrambled-eggs-review-23143709`
- `https://www.apartmenttherapy.com/arf-pets-smart-wifi-pet-feeder-review-37235813`

### Description

```
apartmenttherapy.com,thekitchn.com,cubbyathome.com##.PostBundle__above
apartmenttherapy.com,thekitchn.com,cubbyathome.com##.PostBundle__below
apartmenttherapy.com,thekitchn.com,cubbyathome.com##.pov_recirc__ad
apartmenttherapy.com,thekitchn.com,cubbyathome.com##.StickyFooter
```

<img width="1440" alt="Screenshot 2023-03-28 at 2 48 32 PM" src="https://user-images.githubusercontent.com/110956608/228340577-5e22d915-562b-4df3-9e0c-393fdefa0745.png">
<img width="1440" alt="Screenshot 2023-03-28 at 2 49 35 PM" src="https://user-images.githubusercontent.com/110956608/228340605-1bd7cb5c-be53-4967-87d9-f3354b3eed04.png">
<img width="1440" alt="Screenshot 2023-03-28 at 2 49 52 PM" src="https://user-images.githubusercontent.com/110956608/228340635-aeab09c4-2977-479f-8528-9604c1ed7c86.png">
<img width="1440" alt="Screenshot 2023-03-28 at 2 50 10 PM" src="https://user-images.githubusercontent.com/110956608/228340660-a9c0c7e3-b4d1-456d-8a58-b61746e136f8.png">

### Settings

<details>

```yaml
uBlock Origin: 1.47
Firefox: 111.0
listset:
  added:
    adguard-spyware-url
    block-lan
    adguard-annoyance
    ublock-annoyances
    dpollock-0
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by ryanbr** [comment]
The rest is too minor.
