### ISSUE TITLE
http://thedashtimes.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#154]
`http://thedashtimes.com/`

scotcoin.com banner ad, nitrogen sports ad on the right.

`http://thedashtimes.com/2016/09/20/liberland-goes-bitcoin-cryptocurrency/`

decent.ch ad on bottom right

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/48cc6021ef4305370d3927f2dcc36bae1043141d
