### ISSUE TITLE
stuff.tv

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#15400]
![image](https://user-images.githubusercontent.com/19517680/229367908-46cf2278-3b99-4cad-b0ce-e4ef6d1d9308.png)

https://www.stuff.tv/review/sony-wf-1000xm4-review/

**Comment by ryanbr** [comment]
Not needed, no empty spaces here.

**Comment by 3xploiton3** [comment]
empty spaces still exist after update filter
https://github.com/uBlockOrigin/uAssets/issues/19223#issue-1827831574
