### ISSUE TITLE
Kissanime.ru anti adblock

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#1541]
http://kissanime.ru/Anime/Persona-5-the-Animation/Episode-015?id=147797&s=default

"Please disable uBlock (or any ads blocking) to watch anime on KissAnime. You have just been banned for a few days because of this."

Using Windows 10 RS4, Opera 54 with uBlock Origin 1.16.13rc0

Fanboy Ultimate list.

Error console show only these appear during event:

`http://kissanime.ru/Scripts/jquery17.min.js:2`

`http://kissanime.ru/Scripts/jquery17.min.js:4`

and also

Uncaught SyntaxError: Unexpected token <

`https://adsterra.com/wp-content/plugins/sitepress-multilingual-cms/res/js/sitepress.js:1`

view-source:kissanime.ru/Anime/Persona-5-the-Animation/Episode-015?id=147797&s=default

Line 1044 has that text about to disable uBlock etc, it's part of some long script.

**Comment by crystalsphynx** [comment]
>  You have just been banned for a few days because of this

That only ups the entertainment of adblock filter crafters.  Foolish [mortals](https://ask.slashdot.org/story/05/10/11/0012220/why-do-you-block-ads). 

unlicensed anime can be licitly fetched via usenet

**Comment by runboy93** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/486#issuecomment-405081410
