### ISSUE TITLE
ansa.it

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#15419]
```adblock
/adv_interstitial.
/irobot_adv.html
```
`/sito/ssi/unit/adv_interstitial.html`
`/native/irobot/ssi/irobot_adv.html`

---

```adblock
_bottom_outbrain.
```
`/sito/ssi/unit/ansa_300x250_bottom_outbrain.html`

---

```adblock
/cookie_wall.
```
---

- `A: https://www.ansa.it/`

**Comment by Khrin** [comment]
@smed79 Where you've seen these elements? Exact url?

**Comment by smed79** [comment]
**Was** on the home page and article pages.

**But**, i get only `/cookie_wall.` now.
