### ISSUE TITLE
[NSFW] amateurporn.me

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#15423]
### List the website(s) you're having issues:

`https://www.amateurporn.me/videos/27906/public-sex-in-the-forest-with-big-ass-in-slow-motion/`

### What happens?

ads

<details>
<summary>Screen</summary>

![2023-04-04_121902](https://user-images.githubusercontent.com/111344219/229748082-d33f5231-b738-44d2-a604-ea7097349cd5.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome 111.0.5563.147
- Adblock Extension/version:  uBO 1.48.0

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9927dc83000d874743e8c50164005a5ea5221d18

**Comment by dportvine** [comment]
> `https://www.amateurporn.me/videos/27906/public-sex-in-the-forest-with-big-ass-in-slow-motion/`

<details>
<summary>Screen</summary>

<img width="1366" height="728" alt="Image" src="https://github.com/user-attachments/assets/b58e8e5a-5fb7-4372-a5ce-dbf10caf8a31" />

<img width="1366" height="728" alt="Image" src="https://github.com/user-attachments/assets/52160426-67fb-4f36-a9c3-b68d0faab241" />

</details>
