### ISSUE TITLE
yelp.com large rectangular ads

### ISSUE THREAD

**Issue by crystalsphynx** [easylist/easylist#1543]
A block solution is greatly preferably to a hiding option.

same setup as https://github.com/easylist/easylist/issues/1542

### List the website(s) you're having issues:

`https://www.yelp.com/biz/exploratorium-after-dark-san-francisco-2`

### What happens?

load [m]any yelp listing see annoying man trying to inflict a carwash.

### Other details:

![yelp upselling test or something more nefarious all third party ads are privacy raping](https://user-images.githubusercontent.com/41244545/42729612-76ffb052-8792-11e8-9053-eb7d16999c4a.png)

**Comment by ryanbr** [comment]
Self promo. seems fine.

**Comment by ryanbr** [comment]
||yelpcdn.com^*/promotions/$image
or
yelp.com##.js-promotion_cta
