### ISSUE TITLE
decrypt.co

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#15435]
### List the website(s) you're having issues:

`https://decrypt.co/124972/midjourney-free-ai-image-generation-stopped-over-deepfakes`
`https://decrypt.co/`

### What happens?

leftovers
`decrypt.co##.hidden > [style^="min-width:"]` covered them all.

<details>
<summary>Screen</summary>

![2023-04-05_100931](https://user-images.githubusercontent.com/111344219/230007078-b6dc82fa-1ec3-4a2c-a4ff-ea96029939d7.png)
![2023-04-05_101008](https://user-images.githubusercontent.com/111344219/230007094-a6543288-85bb-448e-a25d-35b4994414d1.png)
![2023-04-05_101451](https://user-images.githubusercontent.com/111344219/230008287-17db8b33-d557-4793-8857-9ae5db4c69de.png)
![2023-04-05_101559](https://user-images.githubusercontent.com/111344219/230009242-95a5f847-947b-46d5-9287-54ffe2f500a5.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome 112.0.5615.50
- Adblock Extension/version:  uBO 1.48.4

**Comment by Iknaka** [comment]
UPD:
In the same place, on the page https://decrypt.co/124972/midjourney-free-ai-image-generation-stopped-over-deepfakes
This field also remains - https://i.imgur.com/evqRA0u.png  
This remnants of elements from social network icons - https://i.imgur.com/NjoFnHG.png

**Comment by dportvine** [comment]
@ryanbr 
<details>
<summary>Screen</summary>

![2023-04-13_192516](https://user-images.githubusercontent.com/111344219/231824148-3c616a83-ca6a-4c70-91a8-6fd6cd6ca564.png)
![2023-04-13_192523](https://user-images.githubusercontent.com/111344219/231824156-d06f0244-d358-4f4d-b65c-89307ca4f92b.png)
</details>
