### ISSUE TITLE
bing.com rewards ad

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#15440]
### List the website(s) you're having issues:
`https://www.bing.com/search?q=ariana+grande`

### What happens?
![bing ad](https://user-images.githubusercontent.com/11689349/230169817-1f06e6ff-7972-4f7d-969b-6df8db70ba21.png)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: uBO

### Other details:
May only occur if you're signed out of Microsoft account.

**Comment by smed79** [comment]
Try 
```adblock
bing.com#?#.b_ans.b_top.b_topborder:-abp-has(.bte_join)
```

**Comment by yokoffing** [comment]
Yes. Thank you.
