### ISSUE TITLE
[NSFW] Can't load web javtsunami.com when Turn on the Adblock mode on CocCoc Mobile iOS

### ISSUE THREAD

**Issue by nguyenminhkhmt** [easylist/easylist#15486]
### Steps:

Open Coc Coc and check the Adblock mode is turned on
Access [JAV Tsunami](https://javtsunami.com/)  
Actual: Can't load the page, the web just loads the blank page. If turn off the Adblock mode, the web can load pages normally (video attached)

Expected: Can load page normally when turning on the Adblock mode

### Environment

Device: iPhone 13, OS 16.3
CocCoc version: 116.0.530
ABP's latest version

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-04-10 at 13 34 05](https://user-images.githubusercontent.com/16470510/230885674-6449b843-ce00-42ef-ac9b-3cd330164294.png)

**Comment by Khrin** [comment]
Site loads fine here, definitely not a problem with EasyList.
