### ISSUE TITLE
Unhidden ad placeholders on azlyrics.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15488]
### List the website(s) you're having issues:
https://www.azlyrics.com/lyrics/elliegoulding/gunsandhorses.html

### What happens?

At the top of the page, there are two blank spots which have their requests blocked by EasyList. The one on the top is a normal ad placeholder, and the second placeholder is from some music element that leads you to another page.
They can both be hidden with these filters:
`azlyrics.com##.lboard-wrap`
`azlyrics.com##.ringtone`

![Screenshot from 2023-04-10 13-22-00](https://user-images.githubusercontent.com/89158249/230956079-33d115e9-8bb6-40e1-b52a-bc388b775e97.png)

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Seems pretty minor, not worth adding these filters for this.
