### ISSUE TITLE
byside_webcare.js

### ISSUE THREAD

**Issue by lfbn** [easylist/easylist#1550]
List the website(s) you're having issues:

https://www.parfois.com/en/gb/homepage/

### What happens?

When using uBlock the requests to this domain are blocked.

### List Subscriptions you're using:

* Easy Privacy

### Your settings

- OS/version: MacOS High Sierra 10.13.5
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin 1.16.12

Other details:

![Image of log that blocks the request](https://i.imgur.com/mnAxtzU.png)

Can this be removed, or be added to the white list? Thanks.

**Comment by ryanbr** [comment]
Why? whats the issue?

**Comment by lfbn** [comment]
I can't get help via chat or phone to a operator. Can this be removed? Thanks!

**Comment by ryanbr** [comment]
i cant see this. if no reproducible details is given this ticket will be closed
