### ISSUE TITLE
Jolstad.no - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#15519]
### Affected site:
`https://jolstad.no/tjenester/minnesider/`

### Issue:
Page won't load / unclickable items / modal overlay, due to a blocked cookie consent!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rule:
`##.cookie-pop-up`

### Possible fixes:
* Alternative 1 (Properly blocking it):
`jolstad.no##.show-cookie-pop-up`
https://github.com/easylist/easylist/issues/15519#issuecomment-1509442179

* Alternative 2 (Allowing it):
`jolstad.no#@#.cookie-pop-up`

### Note:
Strangely enough, the problem rule didn't show up in uBO's logger, until I'd whitelisted a bunch of other rules.
Still, this turned out to be the only rule that actually needed a whitelisting!
uBO bug, or due to what seems to be a first-party sub-frame perhaps?

### Other problem filters:
* ~~**I don't care about cookies** _(@kiboke)_~~ _(FIXED)_
~~`~openreach.com##.cookie-pop-up:not(body):not(html)`~~

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v112.0-1 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.48.4

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by peace2000** [comment]
For me, everything gets fixed by blocking it's parent element:

`jolstad.no##.show-cookie-pop-up`

**Comment by peace2000** [comment]
The reason why it won't show up in the logger is probably related to the fact that element `.cookie-pop-up` is under shadow dom.

**Comment by THEtomaso** [comment]
Thanks, peace2000.
Ive updated the first post with your fix!

**Comment by kiboke** [comment]
@THEtomaso thanks, it will be fixed in IDCAC.

**Comment by THEtomaso** [comment]
@kiboke:
`jolstad.no##adstate-portal[usecookiepopup]` (which you've added to IDCAC) doesn't work.
In fact, that's just another problem rule, which prevents all listings from appearing!
You need to **remove** that rule, and add this one instead (which peace2000 suggested):
`jolstad.no##.show-cookie-pop-up`

**Comment by kiboke** [comment]
@THEtomaso I'll replace `jolstad.no##adstate-portal[usecookiepopup]` with `jolstad.no##.show-cookie-pop-up`, thanks!

I fail to see though the purpose of whitelisting `.cookie-pop-up:not(body):not(html)` in this case since its parent will get hidden anyway.

**Comment by THEtomaso** [comment]
> I fail to see though the purpose of whitelisting `.cookie-pop-up:not(body):not(html)` in this case since its parent will get hidden anyway.

Yeah, I must have been very tired when I wrote that! :)

**Comment by THEtomaso** [comment]
OK @DandelionSprout, here's your second ping for this issue.
It's been two weeks now, so that 72hrs limit of yours has passed long ago! :)
