### ISSUE TITLE
Ad on Modrinth

### ISSUE THREAD

**Issue by your-mom-spec-ops** [easylist/easylist#15524]
Alright, so there is an ad on [Modrinth](modrinth.com) at
start-filters
modrinth.com##.MYYLVTXBPUVWMLVBPVSDLHADDRYFBF-1
modrinth.com##.MYYLVTXBPUVWMLVBPVSDLHADDRYFBF
end-filters
Feel free to check it out yourself, and then apply these filters after using the default website

**Comment by ryanbr** [comment]
We'll leave it.

**Comment by your-mom-spec-ops** [comment]
no. this is an issue that needs to be resolved

**Comment by your-mom-spec-ops** [comment]
reopen this.
