### ISSUE TITLE
"News Headlines" button hidden by EasyList

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15520]
### List the website(s) you're having issues:

https://www.weatherwx.com/forecast.php?forecast=pass&pass=airports&icao=keet

### What happens?
By default: 
![Screenshot from 2023-04-13 14-15-56](https://user-images.githubusercontent.com/89158249/231848270-13bff13f-cf51-400a-974b-75c209b5ccf9.png)

With cosmetic filtering disabled:
![Screenshot from 2023-04-13 14-16-00](https://user-images.githubusercontent.com/89158249/231848347-87f9ed42-7adf-416b-904f-63b1c302823f.png)

Caused by `##.adbutton`

There's also some unhidden ad placeholders, so it would be nice if that can be fixed too.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by krystian3w** [comment]
Open articles about Korea so can be marked as ad/off-topic.
