### ISSUE TITLE
g1.globo.com video share button

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#15535]
### List the website(s) you're having issues:

`https://g1.globo.com/`

### What happens?

Video share button doesn't work. I suspect the culprit is one of Fanboy Annoyance's generic filters (a filter that is applied to all websites).

### List Subscriptions you're using:

<details><spoiler>

```
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 105143
  cosmetic: 170472
  scriptlet: 25531
  html: 1109
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 710-9, 9h.13m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2154-80, 9h.12m
    adguard-spyware-url: 976-169, 2d.6h.10m
    adguard-annoyance: 67096-5989, 2d.6h.5m
    fanboy-thirdparty_social: 69-0, 1d.7h.8m
    fanboy-annoyance: 80517-489, 1d.7h.6m
    ublock-annoyances: 4887-4, 2d.6h.4m
    spa-1: 5164-11, 2d.6h.3m
  default: 
    user-filters: 67-0, never
    ublock-filters: 34342-106, 2d.8h.20m
    ublock-badware: 6542-0, 2d.6h.13m
    ublock-privacy: 352-2, 6d.9h.57m
    ublock-abuse: 78-0, 6d.9h.56m
    ublock-unbreak: 1980-2, 2d.6h.12m
    ublock-quick-fixes: 382-0, 9h.15m
    easylist: 64250-668, 2d.6h.11m
    easyprivacy: 30808-1785, 2d.6h.9m
    urlhaus-1: 7625-1, 9h.14m
    plowe-0: 3750-3, 6d.9h.55m
filterset (user): [array of 67 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 401 ms (selfie)
  maxAssetCacheWait: 165 ms
```

</spoiler></details>

### Your settings

- OS/version: Windows 11 Pro 64-bit
- Browser/version: Firefox 112.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.48.4

### Other details:

For example, go to `https://g1.globo.com/politica/noticia/2023/04/14/ninguem-vai-proibir-que-o-brasil-aprimore-sua-relacao-com-a-china-diz-lula-em-reuniao-com-xi-jinping.ghtml`, and just at the right top of the article, click to play the video and try to use the share button.

![image](https://user-images.githubusercontent.com/30274161/232111495-76c7b71f-8594-4400-8b95-a89f94a620b1.png)

**Comment by smed79** [comment]
Don't you know that  the annoyance list include the social blocking list ?

> Fanboy's Social Blocking List solely removes Social Media content on web pages such as the Facebook like button and other widgets.

> Fanboy's Annoyance List blocks Social Media content, in-page pop-ups and other annoyances; thereby substantially decreasing web page loading times and uncluttering them. EasyList Cookie List and Fanboy's Social Blocking List are already included, there is no need to subscribe to them if you already have Fanboy's Annoyance List.
