### ISSUE TITLE
Unhidden ad placeholders on gamesadshopper.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15536]
### List the website(s) you're having issues:

https://gamesadshopper.com/news/among_us.html

### What happens?

There are unhidden boxes with the label "Advertisement" on them. I'm currently using these filters to hide them:
`gamesadshopper.com##.ad`
`gamesadshopper.com##.AD`
`gamesadshopper.com##.ads`

![Screenshot from 2023-04-14 16-56-42](https://user-images.githubusercontent.com/89158249/232153710-55aa0b68-0627-4ba4-ade2-ea5cd7ec98a3.png)

![Screenshot from 2023-04-14 16-57-41](https://user-images.githubusercontent.com/89158249/232153723-5136bd56-b436-4917-b338-7b43a83c59b0.png)

![Screenshot from 2023-04-14 16-57-45](https://user-images.githubusercontent.com/89158249/232153742-e5091a6a-1ea1-4ca9-afd8-673f266d055d.png)

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by DandelionSprout** [comment]
I propose `gamesadshopper.com##div[class^="ad" i]`

**Comment by partingscientist** [comment]
@Sonic5435325 This issue can be closed with https://github.com/easylist/easylist/commit/44dd964a9c83369f92136be9fa9ef46fe566c6ad I think.

**Comment by Sonic5435325** [comment]
Already closed.
