### ISSUE TITLE
hotukdeals.com

### ISSUE THREAD

**Issue by dpthegrey** [easylist/easylist#15543]
### List the website(s) you're having issues:
`hotukdeals.com`

### What happens?
Cookie Notice

### List Subscriptions you're using:
Easylist Cookie Annoyance filter on uBlock

### Your settings

- OS/version: macOS Monterey
- Browser/version: Firefox Nightly
- Adblock Extension/version: uBlock 1.48.4

### Other details:

![image](https://user-images.githubusercontent.com/49444980/232225951-0961b83d-0648-411e-b79c-d68567d5555f.png)

**Comment by partingscientist** [comment]
@dpthegrey I can no longer reproduce the issue. Can you still reproduce it? If not, perhaps the issue can be closed.

**Comment by dpthegrey** [comment]
Interesting, cannot reproduce now. Closing this.
