### ISSUE TITLE
lafraguri.ro, admin.ro

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#15552]
### List the website(s) you're having issues:
`https://lafraguri.ro/forum/`

### What happens?
`admin.ro` connectivity; part of IP addressed is shown on `https://www.despretrafic.ro/stats/httpslaf`

### List Subscriptions you're using:
the lists which were enabled by default with uBlock Origin

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: uBlock Origin

### Other details:
For EasyPrivacy: `||admin.ro^$third-party` or `||script.admin.ro^$third-party`

**Comment by pancakeexpert** [comment]
maybe with an exception for `gazduire.net` just in case
