### ISSUE TITLE
icanhazip.com is a troubleshooting website, not a tracker

### ISSUE THREAD

**Issue by lae** [easylist/easylist#15562]
### List the website(s) you're having issues:

`icanhazip.com`

### List Subscriptions you're using:

EasyPrivacy

### Other details:

The rule was introduced 4 days ago in https://github.com/easylist/easylist/commit/8b3bcf869ccbb3c270f13a54ea7669be40ff6a26.

`icanhazip.com` used to run https://github.com/major/icanhaz and just returns the user's IP address as text. It's existed for a very long time to support sysadmins and the like. There are plenty of articles about it on reputable sources, see for example on APNIC: https://blog.apnic.net/2021/06/17/how-a-small-free-ip-tool-survived/

Per @major himself:

> It has always been simple site that returns your external IP address and nothing else. No ads. No trackers. No goofy requirements. Sure, if you looked hard enough, you could spot my attempt at jokes in the HTTP headers. Other than that, the site had a narrow use case and started out mainly as an internal tool.

**Comment by major** [comment]
For what it's worth, Cloudflare runs this site now:

https://major.io/2021/06/06/a-new-future-for-icanhazip/

But yes, it just returns your IPv4/IPv6 address. That's all.

**Comment by ryanbr** [comment]
Returning an IP address is a privacy issue. Can be used to track based on the IP.

**Comment by lae** [comment]
What would make this different from any other website that returns IP address for diagnostic purposes, such as `http://ipinfo.info/`, `https://whatismyipaddress.com/`, and everything else returned at https://duckduckgo.com/?t=ffab&q=ip+address&ia=answer? The only issue with those websites is that they're cluttered/excessive, which this one does not have.

YouTube's media URLs return your IP address in the URLs as well, would that count? e.g. `https://rr5---sn-oguelnzs.googlevideo.com/videoplayback?expire=1681802653&ei=PfE9ZPrsG8SrlQSsho24DA&ip=<IPADDRESS>` (snipped rest of URL)

**Comment by ryanbr** [comment]
ipinfo.io already blocked, and whatismyipaddress.com is just a website. Embedding a 3rd-party into a site that reads your IP address is a privacy issue.

**Comment by lae** [comment]
Oh, that's why I didn't notice. I can access ipinfo.io directly just fine with the EasyPrivacy list, it's just blocked if it's loaded as a third party site.

Can we make that the case for this site, as well, then? Right now, the list blocks icanhazip.com entirely, instead of as a 3rd-party site.

**Comment by megamorf** [comment]
@ryanbr I strongly disagree with your judgement here. As other users have said it is just a troubleshooting service. It does not track the user on its own. I as a user need to actively reach out to that domain to get my own IP v4 or v6 address. I was surprised that this suddenly stopped worked in my home network only to find out that it was erroneously added to the trackingservers list. Please remove it.

**Comment by lae** [comment]
@megamorf this issue is resolved for first party access, per the commit above. statements made in this thread may be questionable, but it doesn't really matter.

refresh your easyprivacy list.

**Comment by zatricky** [comment]
Can anyone show any examples of any websites ever using icanhazip as a 3rd-party tracker?
