### ISSUE TITLE
onlinestream.live

### ISSUE THREAD

**Issue by illerokcob** [easylist/easylist#15587]
### List the website(s) you're having issues:
`https://onlinestream.live`

### What happens?
When clicking on a stream, on the player window a "disable adblock" popup shows up which cannot be closed or dismissed.

### List Subscriptions you're using:

Defaults +
EasyList
EasyPrivacy

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: uBO 1.48.4

### Other details:

These filters will hide the banner:
```
onlinestream.live##.adp
onlinestream.live##.adp-underlay
```

**Comment by Khrin** [comment]
@scripthunter7 I have no idea if you can reproduce it or is it already addressed elsewhere, this stuff is not for EasyList anyway.
