### ISSUE TITLE
support.arcgames.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#15581]
### URLs

- `https://support.arcgames.com/hc/en-us/articles/360033679074-I-forgot-my-Runic-account-password-and-the-recovery-page-does-not-work`

### Description

Cookie modal missing accept / decline buttons, so unclosable

### Settings

<details>

```yaml
uBlock Origin: 1.47
Firefox: 112.0
listset:
  added:
    adguard-spyware-url
    easylist-cookie
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by Nojuuu** [comment]
Can the modal be blocked or is it needed for something?

**Comment by wavygecko** [comment]
I'm not sure. It says:

> Cookies are not required for all aspects of service, but some of our services may not function properly if you choose to disable cookies. When your device allows it, we use these cookies to better understand how you interact with our services, to monitor usage patterns, personalize featured content, and remembering your language selection.

**Comment by Nojuuu** [comment]
Adguards list already blocks it so maybe it's fine.
