### ISSUE TITLE
Color4Care sites - Broken (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#15620]
### Affected sites:
```
https://www.color4care.co.uk/
https://www.color4care.dk/
https://www.color4care.fi/
https://www.color4care.no/
https://www.vardvaskan.se/
```

### Issue:
The sites fails to load!

### How to reproduce:
Choose either "Private" or "Company", to enter the sites.
Result: Empty screen!

### Screenshots:
Not needed, as the problem is obvious.

### Problem filter:
* **Fanboy's Annoyance List**

### Problem rule:
`##.push-wrapper:not(body):not(html)`

### Possible fix:
```
- arabbank.com.au,operon.pl#@#.push-wrapper:not(body):not(html)

+ arabbank.com.au,color4care.co.uk,color4care.dk,color4care.fi,color4care.no,operon.pl,vardvaskan.se#@#.push-wrapper:not(body):not(html)
```

### Temp fix:
`color4care.co.uk,color4care.dk,color4care.fi,color4care.no,vardvaskan.se#@#.push-wrapper:not(body):not(html)`

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v112.0-1 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.48.4

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
(To THEtomaso in particular) I must admit that I'm positively surprised by ryanbr's fix speed for these kinds of cookie stuff, so I've been a bit reserved about adding tempfixes when permafixes get added soon after. Perhaps we can say it can go 72 hours before you can give me a tip to add tempfixes?
