### ISSUE TITLE
[NSFW] Leftover Ad Space on gelbooru.com

### ISSUE THREAD

**Issue by Linxgos** [easylist/easylist#15636]
### List the website(s) you're having issues:

`https://gelbooru.com/index.php?page=post&s=view&id=8467532`

### What happens?

There is a leftover space were an banner ad would be

### List Subscriptions you're using:

UBO all included lists except for regional lists

### Your settings

Issue was confirmed with other extensions off

- OS/version: Windows 11
- Browser/version: Firefox 112.0.1
- Adblock Extension/version: uBlock Origin 1.48.4

### Other details:

There seems to be some anti-adblock going on using the filter `##.mainBodyPadding > div` hides the ad space but also removes the click to expand banner and the suggestions at the bottom of the page using the filter `##.mainBodyPadding > div:nth-of-type(1)` block the ad space but also block the click to expand banner on pages were there is no banner ad space as seen on this page `https://gelbooru.com/index.php?page=post&s=view&id=8467686`

<details>
<summary>Screenshots</summary>

First Link
![Screenshot 2023-04-22 163517](https://user-images.githubusercontent.com/30780867/233805595-17aa4d25-1a3a-4d70-b227-0e9522639fde.png)

Second Link
![Screenshot 2023-04-22 163715](https://user-images.githubusercontent.com/30780867/233805639-bad43450-8f8d-4e3d-a5ac-a378b11d5874.png)

**Comment by Daxy7** [comment]
@ryanbr again ad placeholder
`https://gelbooru.com/index.php?page=post&s=view&id=9730577&tags=sonic_%28series%29+rating%3Aexplicit`
`gelbooru.com##[style="min-height: 250px; text-align: center;"]`
