### ISSUE TITLE
Tracker on website?

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15649]
### List the website(s) you're having issues:

https://forums.dolphin-emu.org/Thread-wiimote-pointer--58758

### What happens?

On the site, there's a small image telling you what your IP is. I was wondering if this should be blocked by EasyPrivacy since it seems to be able to easily detect what your current IP is. Maybe `||spyber.com^$3p` could be fine.
![Screenshot from 2023-04-23 13-29-25](https://user-images.githubusercontent.com/89158249/233855303-4152f8ea-9a35-4318-ad39-0630d0100420.png)

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by iam-py-test** [comment]
In my opinion (not that it matters), this isn't tracking, it's just a weird forum signature. Might fall under "Some unnecessary 3rd-party scripts/images" though.
> it seems to be able to easily detect what your current IP is

Any website can do that.

**Comment by Sonic5435325** [comment]
I guess I'll close this then.
