### ISSUE TITLE
zoom.us cookie options button

### ISSUE THREAD

**Issue by Linxgos** [easylist/easylist#15658]
### List the website(s) you're having issues:

`zoom.us`

### What happens?

There is a cookie settings button in the bottom left corner of the page that shows a cookie options menu when clicked

### List Subscriptions you're using:

ublock origin all included filters excluding regional filters

### Your settings

Issue was confirmed with other extensions off

- OS/version: Windows 11
- Browser/version: Firefox 112.0.1
- Adblock Extension/version: ublock origin 1.48.4

### Other details:

Clicking the button results in a cookie options popup so it seems like the behind the scenes JavaScript that runs the this system is also not blocked

![Screenshot 2023-04-24 140524](https://user-images.githubusercontent.com/30780867/234079539-6668666a-fbd3-4f19-83ce-187cd4f5e357.png)

**Comment by krystian3w** [comment]
But here, too, seemingly, someone should look at how the "EasyList Cookies" list approaches blocking OneTrust - supposedly the script blocks the "stay always logged in" function as incompatible with, for example, GDPR/CCPA (sic!).

fyi @peace2000 @Nojuuu

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/17769

**Comment by peace2000** [comment]
I don't think it's reasonable hide the dialog in this case. Breakages are not good.
