### ISSUE TITLE
similarweb.com cookie warning

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#15668]
### List the website(s) you're having issues:
https://www.similarweb.com/

### What happens?
Cookie warning

### List Subscriptions you're using:
All filters offered by uBlock Origin

### Your settings

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 112.0.2
- Adblock Extension/version: uBlock Origin 1.48.4

### Other details:
Screenshot:
![Screenshot 2023-04-25 at 15-47-44 Website Traffic - Check and Analyze Any Website Similarweb](https://user-images.githubusercontent.com/101707608/234282784-753cc0f8-760a-4892-adce-44b923745be1.png)

**Comment by Linxgos** [comment]
Also open issue in Adguard AdguardTeam/AdguardFilters#149335
