### ISSUE TITLE
agar.io

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15671]
### List the website(s) you're having issues:

https://agar.io/#ffa

### What happens?

Ad placeholder: 
![Untitled](https://user-images.githubusercontent.com/89158249/234391930-75ab040c-5509-4534-8162-9034fa348b52.png)

Cookie privacy settings leftover:
![Untitled (1)](https://user-images.githubusercontent.com/89158249/234391983-792e0948-381e-4f0c-a393-2a62ddc08e42.png)

### List Subscriptions you're using:

EasyList
EasyList Cookie

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by Linxgos** [comment]
`agar.io###agar-io_300x250`
