### ISSUE TITLE
skyscanner.net - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#15677]
### List the website(s) you're having issues:

- `https://www.skyscanner.net/`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 112
Adblock Extension/version: AdblockPlus

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2988929/234594874-07dd7083-11f7-4e8e-994a-9c3aa4af444b.png">

**Comment by ryanbr** [comment]
unable to block in ABP, due to disabled scrollbar @alexm92
