### ISSUE TITLE
pochta.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#15681]
Broken 

`/api/tracking/*` **EasyPrivacy** 

Example: `https://www.pochta.ru/tracking`

Check: `12342382236109`

**Comment by ryanbr** [comment]
Page doesn't load, url being blocked?

**Comment by dimisa-RUAdList** [comment]
The parcel tracking verification function does not work. I have indicated the departure number above.

**Comment by Khrin** [comment]
@dimisa-RUAdList Full url?

**Comment by dimisa-RUAdList** [comment]
`https://www.pochta.ru/api/tracking/api/v1/trackings/by-barcodes?language=ru&track-numbers=12342382236109`

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/easylist/commit/b484dd0c89b98f643774ab47f659a6a661372c35#diff-b17c8b1c6dcc6a4f4dd2fef00625e42aa5e25ff1850baed7027a2ae59200bdc9L631
