### ISSUE TITLE
Blocking browser.events.data.microsoft.com on EasyPrivacy list breaks Microsoft "Secure File Exchange"

### ISSUE THREAD

**Issue by thomasmerz** [easylist/easylist#15697]
### What happens?

When told by Microsoft Enterprise Support to upload logs/data via their "secure file exchange" (https://support.microsoft.com/) **EasyPrivacy** List does block `browser.events.data.microsoft.com` which breaks functionality. When `browser.events.data.microsoft.com` is blocked I'm unable to upload/add files. When disabling uBlockOrigin at all or turn EasyPrivacy list off, it works.

### List Subscriptions you're using:

EasyPrivacy 32,948 used out of 32,985

### Your settings

- OS/version: MacOS 13.3.1
- Browser/version: MS Edge Version 112.0.1722.58 (Official build) (x86_64)
- Adblock Extension/version: uBlock Origin 1.49.2

❓ Is this overblocked by this EasyList or does Microsoft misuse this domain with some real functionality to avoid this trackingsite being blocked…?! 🤔

**Comment by thomasmerz** [comment]
Seems to be corelated with issue #15271

**Comment by MasterInQuestion** [comment]
"does Microsoft misuse this domain with some real functionality to avoid this trackingsite being blocked"?
    Please help ascertain by logging the request URL doing the upload.
    (so probably possible to exempt those specific ones)

**Comment by thomas-merz** [comment]
All I can say is that "when browser.events.data.microsoft.com is blocked I'm unable to upload/add files … via their Secure File Exchange". I really don't use this often; but some other blocklists are also blocking this domain:
```
Found 5 adlists exactly matching 'browser.events.data.microsoft.com'.

  - https://github.com/badmojr/1Hosts/releases/download/latest/1hosts-Lite_domains.txt (block)

    - browser.events.data.microsoft.com


  - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection (block)

    - ||browser.events.data.microsoft.com^


  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.winoffice.txt (block)

    - browser.events.data.microsoft.com


  - https://raw.githubusercontent.com/liamengland1/mischosts/master/microsoft-telemetry (block)

    - browser.events.data.microsoft.com


  - https://raw.githubusercontent.com/thomasmerz/hosts/master/docs/lists/ads-and-tracking-extended.txt (block)

    - browser.events.data.microsoft.com
```

**Comment by MasterInQuestion** [comment]
The feature itself is probably inaccessible for most users after all... (subscription only?)

    Try browser DevTools' Network tab.
    Or uBO: https://github.com/gorhill/uBlock/wiki/The-logger

    The specific traffic must be of certain unique pattern distinguishable.
    (focus on the upload activity)
    I believe this one shall be distinguishable from URL.
