### ISSUE TITLE
prescouter.com newsletter registration prompt

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#15710]
### List the website(s) you're having issues:
https://www.prescouter.com/2014/04/malware-infection-rate-for-android-devices-measured-by-researchers/

### What happens?
Newsletter registration prompt

### List Subscriptions you're using:
All filters offered by uBlock Origin

### Your settings

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 112.0.2
- Adblock Extension/version: uBlock Origin 1.48.4

### Other details:
Screenshot:
![Screenshot 2023-04-28 at 16-18-39 Malware Infection Rate For Android Devices Measured By Researchers - PreScouter - Custom Intelligence from a Global Network of Experts](https://user-images.githubusercontent.com/101707608/235161207-10938d88-462c-407e-8641-44111dbd3c8a.png)

**Comment by ryanbr** [comment]
Not seeing this, suggested filter?

**Comment by DimitrisKalaboukas** [comment]
@ryanbr 

prescouter.com##.sgpb-popup-dialog-main-div-wrapper
