### ISSUE TITLE
resumes.breakdownexpress.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15726]
### List the website(s) you're having issues:

https://resumes.breakdownexpress.com/sararaftery

### What happens?

Tracker loads on the site. 
`breakdownexpress.com/js/analytics.js`
`breakdownexpress.com/global/assets/js/logVideoPlay.js` (Maybe?)

On breakdownexpress.com itself:
`breakdownexpress.com/js/ads/googletagPreLoginLeaderboardRect.js`
`breakdownexpress.com/js/ads/googletagLoadAds.js`
`breakdownexpress.com/js/yahoo-dom-event.js` Maybe this one should be `/yahoo-dom-event.js`
This Yahoo script also appears on `http://forum.pj64-emu.com/showthread.php?t=5542`

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Its fine, not a privacy issue, we're blocking the main 3p script.
