### ISSUE TITLE
KaiUSA.com - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#15720]
### Affected site:
`https://www.kaiusa.com/`

### Issue:
Menus doesn't work!

### Example:
`https://kershaw.kaiusa.com/assisted-opening.html`
(Try using the left sidebar menu)

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rule:
`/cookie-wrapper.js`

### Possible fix:
`@@||kaiusa.com^*/cookie-wrapper.js`

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v112.0.1-2 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.48.4

**Comment by ryanbr** [comment]
Has been fixed on another patch, force an update.

**Comment by THEtomaso** [comment]
👍
