### ISSUE TITLE
emathhelp.net formulas are blocked in Firefox

### ISSUE THREAD

**Issue by proy87** [easylist/easylist#1573]
Page: https://www.emathhelp.net/calculators/calculus-1/derivative-calculator/
Browser: Firefox
Operating System: Windows (and Ubuntu)

Current behaviour: in console I see error for MathJax: Error: call to eval() blocked by CSP
MathJax.js:19:3524

Expected behaviour: should be no errors.

There are no errors when adblock is turned off.

Related to #1388 , but for Firefox.

**Comment by proy87** [comment]
Any news? Chrome has same errors.

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/6825f91f709bfe99b8546d0b639caef3cb9b277f

**Comment by proy87** [comment]
See no difference.
