### ISSUE TITLE
odditycentral.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15747]
### List the website(s) you're having issues:

https://www.odditycentral.com/news/man-inserts-magnets-in-fingertips-to-cheat-at-dice-game.html

### What happens?

Ad placeholders on the right side. Can be fixed with these filters:
odditycentral.com###add_160x600
odditycentral.com##.boxcontent:has([id*="mmt-"])
odditycentral.com##.boxcontent:has(#taboola-right-rail-thumbnails)
odditycentral.com##.padding.boxcontent

![Screenshot from 2023-05-01 16-38-14](https://user-images.githubusercontent.com/89158249/235527202-f0333520-770b-4d3a-b84d-fd42b1e8a008.png)

![Screenshot from 2023-05-01 16-38-59](https://user-images.githubusercontent.com/89158249/235527221-daddea31-4e17-4c67-b472-454da41fdec1.png)

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Will leave the rest.
