### ISSUE TITLE
[NSFW] adultempire.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15765]
### List the website(s) you're having issues:
https://www.adultempire.com/

### What happens?

Tracker loads on the site, it loads by `analytics.adultempire.com`.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by Khrin** [comment]
This doesn't seem to be necessary at this time.

**Comment by Sonic5435325** [comment]
@Khrin May I ask why it isn't necessary? It's pretty much the same as #15848.
