### ISSUE TITLE
gazzetta.it

### ISSUE THREAD

**Issue by marcoclg19** [easylist/easylist#15769]
### List the website(s) you're having issues:
`https://www.gazzetta.it/
`

### What happens?
The cookie popup is not removed.

### List Subscriptions you're using:
EasyList
EasyPrivacy
Easylist Cookie List
EasyList Italy
Adblock Warning Removal List

### Your settings

- OS/version: iOS 16.4.1 (a)
- Browser/version: Safari
- Adblock Extension/version: Wipr

**Comment by marcoclg19** [comment]
@Khrin Ciao, secondo te è possibile aggirare il popup?

**Comment by Khrin** [comment]
@marcoclg19 Onestamente non lo so, non conosco l'applicazione. Prova a mandare un'email allo sviluppatore.

**Comment by marcoclg19** [comment]
> Onestamente non lo so, non conosco l'applicazione. Prova a mandare un'email allo sviluppatore.


A livello di liste quindi non riuscite a trovare una soluzione? L'app si basa esclusivamente sulle vostre liste EasyList.
(https://giorgiocalderolla.com/wipr-acknowledgements.html)

**Comment by Khrin** [comment]
> > Onestamente non lo so, non conosco l'applicazione. Prova a mandare un'email allo sviluppatore.
> 
> A livello di liste quindi non riuscite a trovare una soluzione? L'app si basa esclusivamente sulle vostre liste EasyList. (https://giorgiocalderolla.com/wipr-acknowledgements.html)

Non penso che con EasyList Cookie sia al momento possibile rimuovere quel popup.
