### ISSUE TITLE
Ad bypass on multiple sites

### ISSUE THREAD

**Issue by RobertOrinCharles** [easylist/easylist#1577]
### List the website(s) you're having issues:

`techweez.com`

`owaahh.com`

### What happens?

- All articles on the site `techweez.com` post an ad that bypasses default filters.
- An ad is being loaded on the home page  of `owaahh.com` and all other pages on the site.

### List Subscriptions you're using:

- uBlock Filters
- EasyList
- Easy Privacy
- Peter Lowe’s Ad and tracking server list

### Your settings

- OS/version: Linux Mint 18.3
- Browser/version: Firefox 61.0.1
- Adblock Extension/version: uBlock Origin 1.16.14

### Other details:

The filters below seems to resolve this issue.

`www.techweez.com##.a-63.a-single`

`owaahh.com###text-13 > .textwidget`

**Comment by peace2000** [comment]
I checked both urls and didn't find elements that go by those names. Also didn't see ads. Maybe ads on those sites are blocked / hid by other rules now.

@Khrin

**Comment by Khrin** [comment]
I agree.
