### ISSUE TITLE
[EasyPrivacy] onyyqqojuy.xyz (bestmp3converter.com)

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#15770]
### List the website(s) you're having issues:

`https://www.bestmp3converter.com/`

### What happens?

`onyyqqojuy.xyz` running in the background. I think it's a tracking website (like `eecewaim.xyz`, which also runs in the background, but it is already blocked).

Doesn't seem necessary to provide site functionality. `yt2api.com` is responsible for the MP3 conversion.

### List Subscriptions you're using

<details><spoiler>

```
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 107978
 cosmetic: 167786
 scriptlet: 25465
 html: 1114
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 710-9, 1h.4m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2181-82, 1h.3m
  adguard-spyware-url: 1005-168, 1d.2h.43m
  adguard-annoyance: 67786-773, 1d.2h.43m
  fanboy-thirdparty_social: 68-0, 1d.2h.43m
  fanboy-annoyance: 90507-20563, 1d.2h.43m
  ublock-annoyances: 4930-4, 1d.2h.43m
  spa-1: 5194-11, 1d.2h.42m
 default: 
  user-filters: 84-0, never
  ublock-filters: 34316-93, 1d.2h.43m
  ublock-badware: 6985-0, 1d.2h.43m
  ublock-privacy: 443-2, 1d.2h.43m
  ublock-abuse: 70-70, 1d.2h.43m
  ublock-unbreak: 2017-5, 1d.2h.43m
  ublock-quick-fixes: 215-0, 1h.6m
  easylist: 66392-655, 1d.2h.43m
  easyprivacy: 32218-624, 1d.2h.43m
  urlhaus-1: 6708-1, 1h.5m
  plowe-0: 3742-3, 1d.2h.42m
filterset (user): [array of 84 redacted]
modifiedUserSettings: 
 showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 370 ms (selfie)
 maxAssetCacheWait: 123 ms
```

</spoiler></details>

### Your settings

- OS/version: Windows 10 Pro 64-bit
- Browser/version: Firefox 112.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.49.0

### Other details:

Suggested filter: `||onyyqqojuy.xyz^`

**Comment by Daxy7** [comment]
[They make 10+ domains a day on average](https://user-images.githubusercontent.com/91396482/236157238-71324cc9-e53c-4995-84b0-a2fa0f251d0f.png). 
How well does this filter work at stopping the trackware?

```
||bestmp3converter.com^$csp=default-src 'self' bestmp3converter.com yt2api.com font.googleapis.com 'unsafe-inline' data: blob:
```
