### ISSUE TITLE
onlineocr.net

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#15794]
![image](https://user-images.githubusercontent.com/19517680/236106118-9b0cc7ad-8f44-4de3-bf87-7f993f02f55f.png)

https://www.onlineocr.net/

**Comment by partingscientist** [comment]
This should be fixed with https://github.com/easylist/easylist/commit/ea7adc72dc5f58bca09d80c09f4aa699193026a9. Can you test and confirm it?
