### ISSUE TITLE
Pull Request Closed but Issue Not Fixed

### ISSUE THREAD

**Issue by princesa42** [easylist/easylist#15805]
Hello - a bit confused about what to do here, hoping for some help.

I submitted Pull Request https://github.com/easylist/easylist/pull/15776 to address issue https://github.com/easylist/easylist/issues/15775 and both were closed yesterday without seemingly any code changes going into master.

The comment on the Pull Request says "Not needed, we'll block it" but this isn't what's needed. EasyScript is **currently blocking** a page which should be **unblocked**. 

Is there something I should do to get this fix moving forward again, or am I misunderstanding the process? Thank you for your help.

**Comment by Khrin** [comment]
It's debatable if it should be unblocked. Likely not.
