### ISSUE TITLE
sentry.io

### ISSUE THREAD

**Issue by igorsantos07** [easylist/easylist#15806]
### List the website(s) you're having issues:

- <code>sentry.io</code>
- <code>*.ingest.sentry.io</code>

### What happens?

As discussed in many other issues (this is the 13th on this repo that mentions Sentry-related issues), it makes little sense to block error-reporting tools which are privacy-conscious and open source on what they track (as explained at https://github.com/uBlockOrigin/uAssets/pull/7924), when the end result is destroying the work from thousands of honest developers that have _nothing_ to do with user tracking, fingerprinting.

Our current status is: we're having complicated issues with remote customers and Sentry was the perfect way to track those errors. However, now we're having to explain these customers that they must disable their ad-blocker on an Admin tool...... **Seriously, how are we expected to work on those issues without an error reporting tool?** Having to explain this to customers is embarrassing, to say the least, and in the worst case these naive decisions are effectively demolishing the trust on the work of thousands of developers - like you all are.

You place the blame on being "user-first", but in reality this hinders the user experience exactly by not allowing developers to fix the issues they're facing, even when error reports are anonymized. So... what gives? Why this blind behavior against error reporting tools like Sentry, BugSnag, Raygun, and others?

A thorough discussion including the Sentry CEO happened at [uBlock's repo](https://github.com/uBlockOrigin/uAssets/pull/7924); please read and think carefully about what it means and then, please, allow us to work normally or explain in plain words _why_ Sentry is a developer tool you all think shouldn't exist, and _what_ should be used instead.

### List Subscriptions you're using:

Is it relevant? That would be uBlock Origin.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: uBlock Origin 1.49.2

**Comment by Khrin** [comment]
Thanks for the feedback.
