### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by adbloc** [easylist/easylist#1580]
### List the website(s) you're having issues:
```
https://www.msn.com
```
### What happens?

The page breaks and displays "This page is not available right now" message.

### List Subscriptions you're using:

Easylist
Privacy

### Your settings

- Windows 10
- Google Chrome
- Adblock plus latest

### Other details:

https://github.com/easylist/easylist/commit/5f5978affee17c3e6829b195c77321fc4f8e9ff2 must have caused this.

**Comment by monzta** [comment]
Can you check with latest EasyList again?

**Comment by adbloc** [comment]
Looks much better now. I am not seeing any ads which is great! But almost all of the links are not working on most of the article pages.
```
https://www.msn.com/en-us/foodanddrink/foodnews/a-restaurant-crowd-jeered-lance-armstrong-so-he-bought-everyones-meals/ar-BBL5iuO?li=BBnbfcL
```

**Comment by Hakatitla** [comment]
@adbloc which links are not working?
