### ISSUE TITLE
rechtsanwalt-arbeitsrechts.life

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylist#15815]
### List the website(s) you're having issues:
`https://rechtsanwalt-arbeitsrechts.life/`

### What happens?

Blank white screen

### List Subscriptions you're using:
EasyList
ABP Anti Circumvention filters

### Your settings

- OS/version: MacOs Ventura 13.3.1
- Browser/version: Google Chrome Version 112.0.5615.137
- Adblock Extension/version: Adblock Version 5.6

**Comment by monzta** [comment]
Hey @avanikaein! 

Thanks for reporting! This is a parked domain, so there is no real content on that page. That's why there is a hiding filter in EasyList.
