### ISSUE TITLE
linkz.fun

### ISSUE THREAD

**Issue by partingscientist** [easylist/easylist#15814]
### List the website(s) you're having issues:

`https://linkz.fun/JwOWa`

### What happens?

The site shows 3 ad banners, all loaded from `fullmatchzone.com`.

### List Subscriptions you're using:

uBlock Origin's default list

### Your settings

- OS/version: Windows 10 22H2
- Browser/version: Firefox 112.0.2
- Adblock Extension/version: uBlock Origin 1.49.3b4

### Other details:

https://github.com/uBlockOrigin/uAssets/issues/17924

**Comment by partingscientist** [comment]
Considering it has been a while, I probably should ask. Is there anything I can do to help resolve this issue?

**Comment by partingscientist** [comment]
I wrote a patch for this issue here: #16388.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/c1e3a63d135ab9ccab34d40a8af7ee3b6d48443e
