### ISSUE TITLE
nih.gov

### ISSUE THREAD

**Issue by Linxgos** [easylist/easylist#15844]
### List the website(s) you're having issues:
`www.nih.gov`

### List Subscriptions you're using:
uBO all included subscriptions

### Your settings
Analytics service `foresee.com` should be blocked by easyprivacy but is not (In my case it was actually blocked but that was only because it was blocked by Peter Lowe’s Ad and tracking server list

- OS/version: Windows 11
- Browser/version: Firefox 112.0.2
- Adblock Extension/version: uBO 1.49.2

### Other details:

Should probably be blocked like other analytic services with the filter `||foresee.com^$3p`

**Comment by Khrin** [comment]
Added in 2019: https://github.com/easylist/easylist/commit/c77583ad374f9378859e3365dc51541a6aff16dd
