### ISSUE TITLE
termsfeed.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15850]
### List the website(s) you're having issues:

https://www.termsfeed.com/

### What happens?

Tracker
`||termsfeed.com/track/`

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by Linxgos** [comment]
Can you include the websites were this tracker is being used. It help for observing tracker behaviour.

**Comment by Sonic5435325** [comment]
@Linxgos Just updated the issue. It's on the site itself, sorry. I should've mentioned that originally. Lol
