### ISSUE TITLE
9to5linux.com

### ISSUE THREAD

**Issue by GH-User999** [easylist/easylist#15865]
### List the website(s) you're having issues:

`https://9to5linux.com/`

### What happens?

1. Socials
2. Ad

### List Subscriptions you're using:

EasyList
EasyPrivacy
Fanboy's Annoyance List

### Your settings

- OS/version: Linux
- Browser/version: Firefox 113.0.1
- Adblock Extension/version: uBO 1.49.3b9

### Other details:

`https://github.com/easylist/easylist/assets/124740436/52bf3531-7f24-4ed9-b857-3e6dd8b7a61f`

**Comment by nestormarius** [comment]
I'm the owner of this website. The user submitting these so-called "annoyances" definitely has a grudge against my website, probably competition.
If you were a true Linux user of the website, you would have appreciated the thing that I am slowly replacing Google ads with these sponsored advertisements that are Linux-related and not privacy-invading. Would you prefer to see all sorts of ads that have no meaning to you instead?
These sponsors support the website and they do not track your activity on the website like normal ads do, so I see no reason to block these sponsored adverts.
Why do you visit the website if you don't want to support it in any way?

**Comment by nestormarius** [comment]
Other Linux websites use the same time of sponsored ads (e.g. `distrowatch.com`). Please see the screenshot below. Why don't you submit an issue for them too? It's clear that you have something against me and my website and you are not a reader of the website.
![Screenshot from 2023-05-10 23-25-18](https://github.com/easylist/easylist/assets/69980149/06d55f2b-c746-4548-9f83-93955400c103)

**Comment by nestormarius** [comment]
@GH-User999  Those social buttons I implemwnted by me and do not track you. Why are you keep doing this?

**Comment by nestormarius** [comment]
@GH-User999 To avoid being banned, don't constantly re-open or create new (related) issue reports.

**Comment by ryanbr** [comment]
Closing. Was blocked obviously for ad and social elements. Both EL and FB Annoyances are used for this very reason
