### ISSUE TITLE
indiamike.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15861]
### List the website(s) you're having issues:

https://www.indiamike.com/india/humour-it-only-happens-in-india-f55/joke-for-the-day-part-deux-t17244/#post147036

### What happens?

A "To the Top" button on the bottom bar while viewing posts. Can be hidden with `indiamike.com##.im-go-top-btn`.

![Screenshot from 2023-05-09 18-12-47](https://github.com/easylist/easylist/assets/89158249/4feb0e27-9ba0-4e1f-883e-abd79da7fe53)

### List Subscriptions you're using:

Fanboy's Annoyance

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Just add `||d1qnmu4nrib73p.cloudfront.net^`  instead

**Comment by Sonic5435325** [comment]
> Just add ||d1qnmu4nrib73p.cloudfront.net^ instead

@partingscientist

**Comment by partingscientist** [comment]
Done @ryanbr.
