### ISSUE TITLE
Revolut payment breaks because of get.revolut.com block

### ISSUE THREAD

**Issue by marcel263** [easylist/easylist#15882]
### What happens?

Revolut is a licensed e-bank and provides online payments. For this, payment platforms sometimes redirect to get.revolut.com with a certain request for the launching of the revolut app, where payment can then be approved. Also, when topping up Revolut account from another platform, redirects via get.revolut.com occur.

The mention on the filter list of this domain effectively breaks Revolut web payments. If user is behind a dns level type filter, and/or user has no access or skill to whitelist the domain, Revolut is severely limited in normal function by this list.

### List Subscriptions you're using:
EasyPrivacy

### Your settings

- OS/version: 
- Browser/version:  Firefox Nightly
- Adblock Extension/version: uBlock 1.49.2

### Other details:

![Screenshot](https://github.com/easylist/easylist/assets/76437842/de6f1d64-2dee-441f-8663-5a9deaf97e53)

**Comment by ryanbr** [comment]
`get.revolut.com.        300     IN      CNAME   custom.bnc.lt`

Why use a tracker CNAME @marcel263

**Comment by marcel263** [comment]
> `get.revolut.com. 300 IN CNAME custom.bnc.lt`
> 
> Why use a tracker CNAME @marcel263

No idea what this means. Your list breaks normal usage of daily products. It tracks users? Of course, but for Revolut you are a customer already.

If a network administrator applies this list as a DNS filter, you can't finish transactions. Is that easy, realistic privacy? You block PayPal as well? Github?

If your fanatism takes you this far, perhaps rebrand not as "easylist".

**Comment by krystian3w** [comment]
I suppose they do not use `custom.bnc.lt` for transactions, hence the request to change the content blocker to one that supports CNAME:

- Firefox + uBlock Origin (due Chrome like Lemur/Yandex/Kiwi for Android don't have API for add-ons)
- Brave + his Shields 🛡️  https://brave.com/privacy-updates/6-cname-trickery/ https://github.com/brave/brave-browser/issues/24278 (own idea, rather unavailable for API add-ons)

such blocking makes sense until it is again not tied to transaction verification (which may already be difficult for a webmaster to grasp).
