### ISSUE TITLE
linuxiac.com

### ISSUE THREAD

**Issue by GH-User865** [easylist/easylist#15903]
### List the website(s) you're having issues:

`linuxiac.com`
### What happens?

Socials
### List Subscriptions you're using:

EasyList
EasyPrivacy
Fanboy's Annoyance List
### Your settings

- OS/version: Linux
- Browser/version: Firefox 113.0.1
- Adblock Extension/version: uOB 1.49.2

### Other details:

![Screenshot 2023-05-13 at 00 01 20-mh](https://github.com/easylist/easylist/assets/133057292/2beb594f-ab71-44e6-b8d7-b428681f0414)

**Comment by ryanbr** [comment]
No issues here
