### ISSUE TITLE
Anti-AdBlock: tgd.kr (solution available)

### ISSUE THREAD

**Issue by seia-soto** [easylist/easylist#15904]
### List the website(s) you're having issues:

```
https://tgd.kr/s/jungtaejune/42698562?category=1262916&page=45
```

### What happens?

They're enforcing the connection to `via.placeholder.com/1` (1x1 empty image = pixel) by setting `data-src` property and replacing `data-src` property value into `src` property after the site load.

### Your settings

- OS/version: macOS
- Browser/version: Chromium (ungoogled-chromium v109~)
- Adblock Extension/version: uBO 1.49.2

### Other details:

Two ways are available: 
a) Set the `data-src` property as `src` property
b) Set the filter rule to redirect the pixel to noop image and avoid getting error in browser

The mitigation is available:

- Via **filter rule**

```adblock
||via.placeholder.com/$image,redirect=1x1.gif,domain=tgd.kr
```

- Via userscript

```ts
for (const el of document.querySelectorAll('img[src*="via.placeholder.com"]')) {
  el.setAttribute('src', el.getAttribute('data-src'))
}
```

### Source

Fanboy’s Annoyance

```adblock
||placeholder.com^$3p
```

```
- (3) tgd.kr ⇒ placeholder.com
- image
- https://via.placeholder.com/1
```

**Comment by Khrin** [comment]
@piquark6046 Feel free to add these things to your list if you think they are necessary.

**Comment by piquark6046** [comment]
Already added yesterday.
