### ISSUE TITLE
koreaboo.com placeholder

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#15900]
### List the website(s) you're having issues:

`https://www.koreaboo.com/lists/13-disturbing-stories-sasaeng-fans-went-far-1/`

### What happens?

placeholder

<img width="823" alt="placeholder" src="https://github.com/easylist/easylist/assets/48647394/138bb2fb-0ead-4afb-b2ae-27cd329e3a20">

### List Subscriptions you're using:

uBlock Origin default

### Your settings

- OS/version: Win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin 1.49.3b9

### Other details:

Filter suggestion: `koreaboo.com##.kba-container`

**Comment by Sonic5435325** [comment]
Also a "to top" button annoyance: 
![Screenshot from 2023-05-12 16-52-20](https://github.com/easylist/easylist/assets/89158249/ee28515e-f685-4833-bdff-b70637d0d2c7)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/09ecedceaecee165d48f59f927cffce6f493790c
