### ISSUE TITLE
fckrasnodar.ru

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#15919]
### List the website(s) you're having issues:

`https://fckrasnodar.ru/`

### What happens?

broken site
`/fingerprint2.min.js` ~> **EasyPrivacy**

<details>
<summary>Screen</summary>

![2023-05-15_093040](https://github.com/easylist/easylist/assets/111344219/425326b2-94cf-4d0c-851a-ad82d50c6e2a)
![2023-05-15_093543](https://github.com/easylist/easylist/assets/111344219/64d243a6-9011-438a-b71b-e5e9e4f5fdb2)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome (stable)
- Adblock Extension/version:  uBO (stable)

@ryanbr @Khrin

**Comment by dimisa-RUAdList** [comment]
`@@||cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/*/fingerprint2.min.js$script,domain=fckrasnodar.ru`
