### ISSUE TITLE
bodysize.org

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#15912]
### List the website(s) you're having issues:
`https://bodysize.org/en/dua-lipa/`

### What happens?

Breakage due to advertising service `recoco.it`

### List Subscriptions you're using:

EasyList
RU AdList
ABP filters

### Your settings

- OS/version: Windows 7
- Browser/version: Firefox 113
- Adblock Extension/version: ABP 3.17 

### Possible Solution:
`||bodysize.org^$csp=child-src *`

**Comment by dimisa-RUAdList** [comment]
@ryanbr 
This exception does not solve the problem, the site remains broken.

**Comment by mapx-** [comment]
`@@||mraza2dosa.com^$xhr,image,domain=bodysize.org`

**Comment by dimisa-RUAdList** [comment]
In case of rotation, any adserver can be checked. Why not prevent the problem instead of dealing with its consequences?

As far as I can see, in uBlock Origin it was decided exactly like this:
https://github.com/uBlockOrigin/uAssets/blob/b24d63cf7004ca675a49475eee039dda821dc933/filters/filters.txt#L14868
https://github.com/uBlockOrigin/uAssets/blob/b24d63cf7004ca675a49475eee039dda821dc933/filters/filters.txt#L15018
https://github.com/uBlockOrigin/uAssets/blob/b24d63cf7004ca675a49475eee039dda821dc933/filters/filters.txt#L15023

**Comment by mapx-** [comment]
for uBO test

`bodysize.org##+js(ra, srcdoc, iframe)`

**Comment by dimisa-RUAdList** [comment]
This rule works.

**Comment by mapx-** [comment]
your csp filter working fine too, so it's preferable for EL

**Comment by dimisa-RUAdList** [comment]
Yes, the reason for creating the ticket was to solve a problem inside EasyList. Then it would work for all users, both Adblock Plus and uBlock Origin.

**Comment by dimisa-RUAdList** [comment]
@ryanbr 
@Khrin 
Will this problem be solved in EasyList?

**Comment by dportvine** [comment]
@mapx- 
In **ublock-filters** I see the following:

```adb
! ads (srcdoc)
||porngo.com^$csp=child-src *
!
||heavy-r.com^$csp=child-src *
!
||showbiz.cz^$csp=child-src *
```
 
Perhaps you could add `||bodysize.org^$csp=child-src *` for uBO users?
