### ISSUE TITLE
runescape.com

### ISSUE THREAD

**Issue by Linxgos** [easylist/easylist#15917]
### List the website(s) you're having issues:

`play.runescape.com`
`oldschool.runescape.com`

### What happens?

`googletagmanager.com` a known tracking script is specifically unblocked by easyprivacy on this site yet overriding this filter and force blocking seems to cause no issues

### List Subscriptions you're using:
uBO all included filters

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox 113.0.1
- Adblock Extension/version: ublock Origin 1.49.2

### Other details:

[This filter](https://github.com/easylist/easylist/blob/c4487b15b6b26381f4553508e68a9f69f159c6c2/easyprivacy/easyprivacy_allowlist.txt#LL414C1-L414C3256) seems odd why exactly is unblocking `googletagmanager.com` necessary on these sites is it part of a anti-adblock solution? Does `googletagmanager.com` do more then just collect analytics on some sites or is something more complex going on here.

**Comment by Nojuuu** [comment]
https://github.com/easylist/easylist/commit/7d6dde46d593e94823231b6fcced1c31f0b1de50

**Comment by Linxgos** [comment]
Download button works fine for me when force blocking `googletagmanager.com` I think exempting this site might no longer be necessary
