### ISSUE TITLE
76thz.com

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylist#15921]
### List the website(s) you're having issues:

`http://76thz.com/`
### What happens?
lots of ads present

### List Subscriptions you're using:

EasyList
ABP Anti Circumvention filters
### Your settings

- OS/version: MacOs Ventura 13.3.1
- Browser/version:  Google Chrome Version 112.0.5615.137
- Adblock Extension/version:  Adblock Version 5.6

### Other details:

![Screenshot 2023-05-15 at 9 42 49 AM](https://github.com/easylist/easylist/assets/56893063/ae3cb609-f376-46af-b2b0-1bedd2218e47)

**Comment by Khrin** [comment]
Chinese ads are handled by https://github.com/easylist/easylistchina and relative list: `https://easylist-downloads.adblockplus.org/easylistchina.txt`
