### ISSUE TITLE
news.yahoo.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15923]
### List the website(s) you're having issues:
https://news.yahoo.com/m-korean-people-accept-oli-230907178.html

### What happens?
Ad placeholder
`news.yahoo.com###sda-MON`
![Screenshot from 2023-05-15 13-33-18](https://github.com/easylist/easylist/assets/89158249/6368b1cf-383e-41f7-b84d-ae16aa1e5949)

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by partingscientist** [comment]
The issue seems to have been fixed some time in the past.

https://github.com/easylist/easylist/blob/4ece4259c75feac8932eef766811f18ce4542cda/easylist/easylist_specific_hide.txt#L692

Perhaps the issue can be closed?

**Comment by Sonic5435325** [comment]
The entire sidebar seems to be gone now, so I think I can just close this like you've suggested.
