### ISSUE TITLE
gray overlay on boehringer.net

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylist#15940]
### List the website(s) you're having issues:

`https://www.boehringer.net/`
### What happens?
grey overlay present, scrolling locked

### List Subscriptions you're using:

 ABP filters
EasyList
Easylist Cookie List

### Your settings

- OS/version: MacOs Ventura 13.3.1
- Browser/version: Firefox 13.0.1
- Adblock Extension/version: Adblock Plus 3.17

**Comment by Sonic5435325** [comment]
Have you tried subscribing to EasyList Cookie? These are the only annoyances I see when I have it enabled:
![Screenshot from 2023-05-16 15-58-51](https://github.com/easylist/easylist/assets/89158249/b60e57a8-9f2e-4e81-9e1a-3f38211af1c5)

**Comment by avanikaein** [comment]
Yes, I am subscribed to Easylist Cookies.
I see the filter `##div.cookie-consent` hit which seems to leave a grey overlay and lock scrolling on the page. 
![Screenshot 2023-05-16 at 1 30 43 PM](https://github.com/easylist/easylist/assets/56893063/e9195dd9-3b00-4ff8-9116-e917e5f9e70d)
