### ISSUE TITLE
Reddit.com

### ISSUE THREAD

**Issue by tyw7** [easylist/easylist#15969]
### What happens?

When you browse from Reddit.com main page, the body of the post is missing

See https://imgur.com/a/pqeZ4fx which is a screenshot of https://www.reddit.com/r/LegalAdviceUK/comments/13lboeg/pedestrian_vs_cyclist_collision/

If you click on a post from Reddit.com main page, the body text is missing.  Refreshing the page or turning off Fanboy – Annoyances fixes the issue.

### List Subscriptions you're using:

See below

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 223041
 cosmetic: 108329
 scriptlet: 22792
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt: 40338-129, 39m
  block-lan: 47-0, 39m
  curben-phishing: 96369-2, 39m
  fanboy-annoyance: 90559-15520, 1m
  ublock-annoyances: 5068-78, 39m
 default: 
  user-filters: 54-2, never
  easylist: 65956-90, 39m
  easyprivacy: 31822-13191, 39m
  plowe-0: 3737-1016, 39m
  ublock-abuse: 70-0, 39m
  ublock-badware: 7099-158, 39m
  ublock-filters: 33009-163, 39m
  ublock-privacy: 392-130, 39m
  ublock-quick-fixes: 351-40, 39m
  ublock-unbreak: 2020-63, 39m
  urlhaus-1: 8009-4, 39m
filterset (user): [array of 55 redacted]
trustedset: 
 added: [array of 526 redacted]
 removed: 
  about-scheme
  chrome-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
 contextMenuEnabled: false
 prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1007 ms (selfie)
 maxAssetCacheWait: 377 ms

**Comment by KanchiMoe** [comment]
> Refreshing the page or turning off Fanboy – Annoyances fixes the issue.

I have `Fanboy – Annoyances` (version 202305190020) list enabled and I'm not able to replicate the content being blocked.

**Comment by Sonic5435325** [comment]
Can't reproduce either. This probably isn't an EasyList problem, it's likely a different filter list problem. Try resetting your uBlock Origin settings to default, or try on a new profile, and see if it works.

**Comment by tyw7** [comment]
I had reset and I too can't reproduce it.
