### ISSUE TITLE
ejghgjhhgadcdchjaada.ru. ~ Non domain entry

### ISSUE THREAD

**Issue by Ad-Blokker** [easylist/easylist#15988]
#### List the website(s) you're having issues with:

```ejghgjhhgadcdchjaada.ru.```

#### What happens?

Invalid domain notation

#### Filter lists you're using:

- EasyList

**Comment by krystian3w** [comment]
Entry, possible use:

`http://ejghgjhhgadcdchjaada.ru./#foo-bar`
