### ISSUE TITLE
thesimscatalog.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#15983]
#### List the website(s) you're having issues with:

`https://thesimscatalog.com/sims3/downloads/worlds/create-a-world-download/`

#### What happens?

2 placeholders with text, each measured to 85px tall.

#### Screenshot(s) 

<details>

![image](https://github.com/easylist/easylist/assets/22780683/3d5f560f-9258-40dd-a7e3-87f855a67875)

</details>

#### Filter lists you're using:

<details><summary>Screenshot:</summary>

![image](https://github.com/easylist/easylist/assets/22780683/a63c7b6a-57c7-4e00-8956-09560bfea858)

</details>

#### Your settings:

- OS/version: Windows 11 22H2 x64
- Browser/version: Chrome 113.0.5672.127 x64
- Adblock extension/version: uBO 1.49.2 + IDCAC 3.4.7

#### Other details:

I propose `thesimscatalog.com##.wccc-content-block`

**Comment by Nojuuu** [comment]
`##.wccc-content-block` hides too much here: `https://thesimscatalog.com/sims4/`

**Comment by Khrin** [comment]
Not necessary.

**Comment by Nojuuu** [comment]
Can we at least hide text leftovers with `thesimscatalog.com##p[style="text-align: center;"] > span > span[style="color: #999999;"]` or something?
