### ISSUE TITLE
academickids.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#15985]
#### List the website(s) you're having issues with:
`http://academickids.com/encyclopedia/index.php/Cream_the_Rabbit`

#### What happens?
Ad placeholders

#### Screenshot(s) 

`academickids.com##.spacer150px` (Seems like this gives a lot of room for ads)
![Screenshot from 2023-05-20 16-14-18](https://github.com/easylist/easylist/assets/89158249/350bc34b-b8ce-4a91-b7f5-ec4842771a77)

![Screenshot from 2023-05-20 16-16-29](https://github.com/easylist/easylist/assets/89158249/28f7c303-eed1-4563-b1de-a800d52af5b5)
![Screenshot from 2023-05-20 16-16-56](https://github.com/easylist/easylist/assets/89158249/fadaa811-48da-4acd-a291-da7068faa4b8)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by DandelionSprout** [comment]
I propose `academickids.com###header-logo > table:not([cellpadding="0"])`

It's always I who have to fix old reports like these. No one else ever do.
