### ISSUE TITLE
2 incorrect domains: _.net.asambeauty.com & _tcp.academyofconsciousleadership.net

### ISSUE THREAD

**Issue by Ad-Blokker** [easylist/easylist#15989]
#### List the website(s) you're having issues with:

```
_.net.asambeauty.com
_tcp.academyofconsciousleadership.net
```

#### What happens?

Invalid formatted domain in the adblock filter

#### Filter lists you're using:

EasyPrivacy

**Comment by Yuki2718** [comment]
`_tcp.academyofconsciousleadership.net` exists.
