### ISSUE TITLE
permies.com unblocked ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#160]
`https://permies.com/forums`
`https://permies.com/f/23/homestead`
`https://permies.com/wiki/31762/Book-Review-Grid`

Banner ad at top and some more ads on the left column.
May have to refresh a few times to see the ads. Some appear to be blocked but others aren't.

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/163e231ade1ce452a6af696421af0058731f8e0d
