### ISSUE TITLE
Filter "||microsoft.com/mscc/" on "EasyList – Cookie Notices" breaks Microsoft "Secure File Exchange"

### ISSUE THREAD

**Issue by thomasmerz** [easylist/easylist#16004]
### What happens?

When told by Microsoft Enterprise Support to upload logs/data via their "secure file exchange" (https://support.microsoft.com/files?workspace=…) **EasyList – Cookie Notices** does block/filter `||microsoft.com/mscc/` which breaks functionality. When disabling uBlockOrigin at all or turn "EasyList – Cookie Notices" list plus "EasyPrivacy" list off, it works.

<img width="516" alt="grafik" src="https://github.com/easylist/easylist/assets/18568381/0f831d6c-7c1a-4b77-a2be-53ffad0c974b">

<img width="622" alt="grafik" src="https://github.com/easylist/easylist/assets/18568381/b1ed5a60-43de-47a4-8d97-eef5edeb8f87">

### List Subscriptions you're using:

```
150,584 network filters ＋ 233,840 cosmetic filters from:
My filters 4 used out of 4
Built-in (6/6)
uBlock filters – Ads 33,896 used out of 34,001
uBlock filters – Badware risks 7,154 used out of 7,154
uBlock filters – Privacy 442 used out of 442
uBlock filters – Quick fixes 366 used out of 367
uBlock filters – Resource abuse 0 used out of 70
uBlock filters – Unbreak 2,030 used out of 2,031
Ads (3/3)
AdGuard – Ads 65,139 used out of 71,212
AdGuard – Mobile Ads 8,672 used out of 8,780
EasyList 65,469 used out of 66,211
Privacy (2/4) AdGuard Tracking Protection
27,588 used out of 41,125
EasyPrivacy 31,204 used out of 31,840
Malware domains (1/3)
Online Malicious URL Blocklist 5,659 used out of 5,659
Annoyances (6/7)
AdGuard – Annoyances 62,874 used out of 68,667
AdGuard – Social Media 19,840 used out of 20,516
EasyList – Cookie Notices 37,748 used out of 47,204
EasyList – Social Widgets 16,583 used out of 16,600
Fanboy – Annoyances
Fanboy – Anti-Facebook 68 used out of 68
uBlock filters – Annoyances 5,042 used out of 5,046
Multipurpose (1/2)
Peter Lowe’s Ad and tracking server list 3,732 used out of 3,735
Regions, languages (1/36)
DEU: EasyList Germany 6,857 used out of 6,860
Custom (1/1)
I don't care about cookies 25,704 used out of 25,708
```

### Your settings

- OS/version: MacOS 13.3.1
- Browser/version: Firefox MacOS https://support.microsoft.com/files?workspace
- Adblock Extension/version: uBlock Origin 1.49.2

**Comment by thomasmerz** [comment]
Adding these filters also "helped" and made it work again - but due to specific version in URI this will surely not work forever 😞 
```
! 2023-05-22 https://support.microsoft.com
@@||wcpstatic.microsoft.com/mscc/lib/v2/wcp-consent.js$script,domain=support.microsoft.com
@@||support.microsoft.com/supportformslib/oneds/dist/ms.analytics-web-3.1.7.min.js?v=*$script,domain=support.microsoft.com
```

**Comment by krystian3w** [comment]
You can skip `3.1.7.min.js?v=*` like in https://github.com/uBlockOrigin/uAssets/commit/4e547027e36d4f0f5d208b066626538eb726936b if update unbreak/quick-fixes failed (or you share solution for ABP/AdBlock/AdGuard friends).

A terrible mistake is unlikely to be the insertion of another wildcard:

```adb
@@||support.microsoft.com/supportformslib/oneds/dist/ms.analytics-web-*.min.js?v=*$script,domain=support.microsoft.com
```

if you absolutely must detect the existence of `.min.js?v=`.

---

Very optionally, this can be rewritten as a regex:

```adb
@@/^https:\/\/support\.microsoft\.com\/supportformslib\/oneds\/dist\/ms\.analytics\-web\-\d\.\d\.\d+\\.min\.js\?v=/$script,domain=support.microsoft.com
```

Then it will fall like:

- the first or second number becomes 2 digits
- one of the numbers will disappear

**Comment by thomasmerz** [comment]
@Yuki2718's commit solved it. Great! Thank you! ❤️

**Comment by krystian3w** [comment]
Well, not exactly, because you can reproduce it with ABP/AdBlock/AdGuard and it is unlikely that the cookie filter was removed quietly.

![image](https://github.com/easylist/easylist/assets/35370833/886d3b9d-77aa-4719-a5f7-7550d0e99c12)

![image](https://github.com/easylist/easylist/assets/35370833/f96c8655-3dcd-4d87-93ac-22c96e76c3e2)

![image](https://github.com/easylist/easylist/assets/35370833/6f6d2c73-9b0b-4ada-a2d1-99c3c701f2f9)

**Comment by thomasmerz** [comment]
That's weird - because I now could use "MS secure file exchange" after removing my filters above…
```
! 2023-05-22 https://support.microsoft.com
!@@||wcpstatic.microsoft.com/mscc/lib/v2/wcp-consent.js$script,domain=support.microsoft.com
!@@||support.microsoft.com/supportformslib/oneds/dist/ms.analytics-web-3.1.7.min.js?v=*$script,domain=support.microsoft.com
!fixed: https://github.com/easylist/easylist/issues/16004
```
<img width="351" alt="grafik" src="https://github.com/easylist/easylist/assets/18568381/b42411a3-4dd3-49d6-ab66-2ad01733f0e5">

---

And this is what "logger console" says:

<img width="1292" alt="grafik" src="https://github.com/easylist/easylist/assets/18568381/f0cd4b0f-f654-4fea-bc47-85e87d74e947">


But now I'm able to upload files… 🤷🏼‍♂️

**Comment by krystian3w** [comment]
I would conclude that you incorrectly assumed that blocking the cookie path somehow affects the upload function.

You might consider checking in a clean Chrome/ium or Firefox profile (So that nothing of the current profile would interfere with it).

**Comment by thomasmerz** [comment]
I think that you @krystian3w are right that not "||microsoft.co/mscc/" was my problem but "/ms-analytics-" (from my second screenshot) that has solved "somehow" via EasyPrivacy List…!? 🤔

**Comment by thomasmerz** [comment]
With a new profile and with EasyList added/enabled everything is working fine/as expected with "MS secure file exchange" 👍🏼

**Comment by krystian3w** [comment]
The generic filter continues to exist:
https://github.com/easylist/easylist/blob/e9163631d7c142b1cce00bb34252fdccab6a459d/easyprivacy/easyprivacy_general.txt#L2658

and I doubt that there is already an exception in EP in one of the allow:

https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_allowlist.txt
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_allowlist_international.txt

To eliminate corruption from ABP/AdBlock/AdGuard, and eventually purge in uBo lists as obsolete entries.

**Comment by thomasmerz** [comment]
That's all very strange and weird…

**Comment by krystian3w** [comment]
As for me, it is not strange; not to disable the unbreak list and/or quick fixes you can test and the site should break again:

```adb
@@||support.microsoft.com/supportformslib/oneds/dist/ms.analytics-web-$badfilter
```

Which indicates that no one with permission to modify the EL repo files has tried to address this at the EasyPrivacy level.

**Comment by thomasmerz** [comment]
That's right: with your filter it breaks again. But WHY does it work now for me without any visible changes after I removed my local filters from above? 🤔

**Comment by krystian3w** [comment]
It works because it probably independently or in the background downloaded an update to one of the two uBo lists: quick fixes / unbreak.

![image](https://github.com/easylist/easylist/assets/35370833/c92c6992-4802-4427-9943-254c358e7ffb)
*Translation of the interface into German with the help of Google, hence the English strings do not exist and there are other words than the translators approved.*
