### ISSUE TITLE
Typo - `hallensteins.com`

### ISSUE THREAD

**Issue by uuqqzz** [easylist/easylist#16002]
https://github.com/easylist/easylist/blob/d5f71d45fcf39cb7bd61472df79657ff991d2093/fanboy-addon/fanboy_newsletter_shopping_specific_hide.txt#L29

<details>
 <summary>screeshot</summary>

![screenshot_20230522_114935](https://github.com/easylist/easylist/assets/110184059/1297fdec-19e2-4c18-ae19-9e0f5447e2b5)

</details>

**Comment by krystian3w** [comment]
Fresh: https://github.com/easylist/easylist/commit/c5ec21d0b6f0ef0c9961e498444be66b18455df2#diff-d142dc99e87151299575b5dc3d9335d2fb3c692770d78a454980f8c4050bd795R20
