### ISSUE TITLE
thepiratebay.org

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16026]
#### List the website(s) you're having issues with:
`https://thepiratebay.org/search.php?q=fsdgsh`

#### What happens?

To reproduce: Look up any keyword
The ad images under `torrindex.net/images/epv/` are being allowed by EasyList. These should get blocked instead, since you can see them if you don't use cosmetic filtering. Hopefully there's a way for this to be blocked in EasyList itself.

#### Filter lists you're using:
EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by Daxy7** [comment]
This works
`||torrindex.net/images/epv/$important`
