### ISSUE TITLE
track.lc.quark.cn

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylist#16021]
#### List the website(s) you're having issues with:

`https://b.quark.cn/apps/qknewshours/routes/hot_news`

#### What happens?

Background ping to `track.lc.quark.cn`

#### Your settings:

- OS/version: Android 12
- Browser/version: Firefox v113
- Adblock extension/version: uBlock Origin 1.49.2

**Comment by Khrin** [comment]
Looks like it has already been blocked by `://track.*/collect` https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L4716
