### ISSUE TITLE
shabdkosh.com

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#16028]
https://www.shabdkosh.com/search-dictionary?lc=sa&sl=en&tl=sa&e=charcoal

ads
![image](https://github.com/easylist/easylist/assets/19517680/8c097b0c-be85-494a-a611-85f39eb5145c)

**Comment by DandelionSprout** [comment]
I propose `shabdkosh.com##.text-center.text-muted`

**Comment by Khrin** [comment]
Nothing that's worth including in EasyList.
