### ISSUE TITLE
Blocking suggestions

### ISSUE THREAD

**Issue by Thomas-Schubert** [easylist/easylist#16036]
1bliq.io
adalliance-a.akamaihd.net
adobe.io
akaquill.net
announcekit.app
app.easy-feedback.com
appcenter.ms
atudo.net
baqend.com
beyondwords.io
bing-ads-display-ads-cdn.azureedge.net
chrome.google.com
cleverreach.com
dymatrix.cloud
dynatrace.schwarz
f11-ads.com
financeads.net
flibzee.com
funkedigital.de
glomex.cloud
goyax.de
iheart.com
intercom.io
kameleoon.io
klarnaservices.com
lapippa.com
locationiq.com
ltsapis.goog
measurementlab.net
mqtt-eu.meross.com
powr.io
pulsembed.eu
salesforceliveagent.com
schemaapp.com
shopbop.com
snacks.faz.net
sp-prod.net
statically.io
statikco.com
storylane.io
stroeermediabrands.de
thenewsbox.net
tidio.co
tpv-analytics.com
tracker.growthbuddy.app
ubi.li
unagi.amazon.de
unwf5a.heise.de
wapo.pub
webanalytics.europa.eu
website-files.com
webstatistik.landbw.de
webyze.com
wnyc.org
xgroovy.com
yagiay.com

**Comment by Daxy7** [comment]
first of all, this is not sorted. there's easylist, easyprivacy and fanboy annoyances fused together. and you wanna block `chrome.google.com`? it will cause millions of breakages worldwide when trying to download google chrome. lots of these are false positives leading to real websites. sorry, pal, it won't make it to the finals.

**Comment by Sonic5435325** [comment]
Please edit your issue to be more specific. (Like which one of these are an annoyance, ad, or tracker)
Also I think `website-files.com` is a CDN. That one will likely not be added either.

**Comment by Sonic5435325** [comment]
Also, `webanalytics.europa.eu` is already being blocked by `/webanalytics.$from=~webanalytics.italia.it`.

**Comment by Khrin** [comment]
Closing here before the discussion becomes too heated.

@Thomas-Schubert This looks like more a random list of websites. Probably all the adservers/tracking services listed there are already blocked in EasyList/EasyPrivacy, others looks to be legit websites.
