### ISSUE TITLE
Indeed.com broken due to thirdparty adblock of CDN

### ISSUE THREAD

**Issue by bencripps** [easylist/easylist#16044]
#### List the website(s) you're having issues with:

indeed.com

#### What happens?

All static files will 404, and the page will be broken. 

![image](https://github.com/easylist/easylist/assets/6272507/1f61debe-9726-450e-aad0-12296131d7e3)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 

OSX 
- Browser/version: 

Chrome

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/pull/16045

**Comment by krystian3w** [comment]
9777d69

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/9777d69886b67637a3076a1151ec4b3a08aa10df
