### ISSUE TITLE
Please remove soulgen.net

### ISSUE THREAD

**Issue by xqddas** [easylist/easylist#16054]
#### What happens?

Our website is block by easylist which cause our user can't access normally.

https://github.com/easylist/easylist/blob/862ca10812bcd79739ab921ce9891d084fbadd93/easylist/easylist_adservers_popup.txt#L2360

#### Other details:

Dear easylist Team,

I am the administrator of a website, and I am deeply concerned and frustrated that my domain has been marked as an advertisement by your ad blocking list. After careful investigation, I have discovered that this misjudgment is likely due to the improper advertising practices of a promotional partner associated with my website. I assure you that my website itself does not contain any advertisements, and I have taken measures to address the issue with my promotional partner to ensure that such incidents do not occur again.

Please find below the details regarding this matter:

Website Name: soulgen
Domain: soulgen.net
Website Description: With AI Art generator SoulGen, you can create stunning images of real/anime girls from text description or prompt. Get your free trial and produce your soulmate picture using SoulGen AI art generator.
Target Audience:  those like ai and ai tech
Non-advertising Nature: my website does not contain any advertisements
Violation by Promotional Partner: After careful investigation, it is a promotional partner who engaged in improper advertising practices, may leading to the erroneous labeling of my domain as an advertisement. I have taken the following corrective actions:
Terminated the partnership with the promotional partner in question.
Communicated with them, demanding an immediate cessation of improper advertising practices.
Strengthened the review and monitoring mechanisms for promotional partners to ensure compliance with advertising standards and policies.

I deeply regret and apologize for failing to promptly detect and prevent the improper advertisements from being displayed. I place great importance on user experience and advertising control, and I will exercise greater caution in selecting future partners while enhancing the management of advertising placements to avoid similar issues.

I kindly request your reconsideration and removal of the advertisement label from my domain so that users who utilize your ad blocking software can access and enjoy my website without disruption. I assure you that my website does not contain any advertisements, and I will continue to uphold the balance between user experience and advertising control.

If you require further information or have any questions, please feel free to contact me. I look forward to your positive response and resolution.

Thank you for your understanding and support.

Best regards.

**Comment by partingscientist** [comment]
This seems to have been fixed with https://github.com/easylist/easylist/commit/cf4ba3646fea9ac1948dd99a103d5bb2da2ca413.

Perhaps the issue can be closed?
