### ISSUE TITLE
bleacherreport.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16078]
#### List the website(s) you're having issues with:

`https://bleacherreport.com/articles/10077407-nba-reportedly-opens-investigation-into-twitter-activity-about-referee-eric-lewis`

#### What happens?
Twitter embeds are broken. Caused by `://lightning.*/launch/`

#### Screenshot(s) 

![Screenshot from 2023-05-27 18-14-14](https://github.com/easylist/easylist/assets/89158249/0aa1f541-c6d9-405f-9c0c-8e2caaefa70c)

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
With uBO disabled, this didn't help. `://lightning.*/launch/` is an adobe tracker.

**Comment by Sonic5435325** [comment]
@ryanbr They take a few seconds, but Twitter embeds only load without that filter. It breaks Twitter embeds.

**Comment by Sonic5435325** [comment]
For comparison, by default (With `://lightning.*/launch/` active):
![Screenshot from 2023-06-11 23-24-49](https://github.com/easylist/easylist/assets/89158249/62dd5b64-4178-44e3-8d58-be34c8d2b1ab)

Now, with the filter disabled because of an exception filter:
![Screenshot from 2023-06-11 23-25-07](https://github.com/easylist/easylist/assets/89158249/e2eede06-1d86-4804-937f-8a05fe350de9)

**Comment by ryanbr** [comment]
I waited 30secs, with uBO disables. Still nothing here.

**Comment by Sonic5435325** [comment]
@ryanbr I use Firefox if that's relevant
