### ISSUE TITLE
aliexpress.com

### ISSUE THREAD

**Issue by flyingzebras** [easylist/easylist#161]
www.aliexpress.com##.ui-mask
www.aliexpress.com##.ui-window-content
www.aliexpress.com##.ui-newuser-layer-dialog.ui-window-transition.ui-window-normal.ui-window

![screenshot from 2017-03-15 06 35 08](https://cloud.githubusercontent.com/assets/11916082/23935014/a9f9ff94-0949-11e7-9012-bc42adddbf6b.png)

**Comment by flyingzebras** [comment]
@monzta Can you please add them to EasyList?

They pop-up constantly, its not feasible to accept them for normal browsing.

**Comment by monzta** [comment]
No, this belongs to the Annoyance List: https://github.com/easylist/easylist/commit/b755ed3b096357d708347eee08325dfc7db7c39e

**Comment by flyingzebras** [comment]
@monzta @Khrin 

Can you please add this to Fanboys Annoyance's to block annoying coupons pop-ups that show _every time_ a page is being loaded even if you closed it earlier:
> aliexpress.com##.s-tips-content

![screenshot from 2017-03-30 10 56 07](https://cloud.githubusercontent.com/assets/11916082/24496182/d07797ae-1537-11e7-8d0f-225dc8a6eec0.png)

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by flyingzebras** [comment]
Another annoyance filter

> ##.ui-window-transition.ui-window-normal.ui-window

![screenshot from 2017-03-31 05 48 07](https://cloud.githubusercontent.com/assets/11916082/24535675/d6176d80-15d5-11e7-9247-9fd48664cdd1.png)

**Comment by flyingzebras** [comment]
The added new elements to circumvent our filters. You must add this to block the popup image above:

||ae01.alicdn.com/kf/HTB1.0L9QpXXXXXDXFXX760XFXXXP.png$image
aliexpress.com##.newuser-container
aliexpress.com##.ui-newuser-layer-dialog.ui-window-transition.ui-window-normal.ui-window

**Comment by flyingzebras** [comment]
@monzta @Khrin 
The added new elements to circumvent our filters. You must add this to block the popup image above:

||ae01.alicdn.com/kf/HTB1.0L9QpXXXXXDXFXX760XFXXXP.png$image
aliexpress.com##.newuser-container
aliexpress.com##.ui-newuser-layer-dialog.ui-window-transition.ui-window-normal.ui-window
