### ISSUE TITLE
qwant.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#16102]
**ad**

```adblock
qwant.com##.result--ext
```
- https://i.imgur.com/FNQQIGH.png

**annoyance**
```adblock
qwant.com##._1ZfhW > a
```
- https://i.imgur.com/9piCZYY.png

---
- `https://www.qwant.com?q=samsung&locale=fr_FR&theme=1&hc=1&hti=1&vt=0&b=0&s=1&l=en&home=brand&si=1&c=blue&ch=random&eco_suggest=1`

**Comment by DandelionSprout** [comment]
Qwant appear to have changed their adservers to a Microsoft-based one in the following 7 months, which `qwant.com##div[data-testid="pam.container"]` in EL seem to have fixed.
