### ISSUE TITLE
leboncoin.fr

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#16109]
**annoyance** (footer)
```adblock
||api.leboncoin.fr/api/trustpilot-proxy-api/*
```
or
```adblock
/trustpilot-proxy-
```
`A: https://www.leboncoin.fr/`

**Comment by Khrin** [comment]
`https://api.leboncoin.fr/api/trustpilot-proxy-api/v1/lbc`

Doesn't seem to be tracking, though.
