### ISSUE TITLE
fllwrs.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16112]
#### List the website(s) you're having issues with:
`
http://fllwrs.com/`

#### What happens?

Ad placeholder
`fllwrs.com##.ads`

#### Screenshot(s) 
![Screenshot from 2023-05-29 00-27-54](https://github.com/easylist/easylist/assets/89158249/d755efff-a913-4b28-a717-4be5329e98a0)

#### Filter lists you're using:
EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Not worth
