### ISSUE TITLE
steamanalyst.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16161]
#### What happens?
Ad images
`||steamanalyst.com/steeem/images/`

Tracker
`steamanalyst.com/steeem/delivery/`

#### Filter lists you're using:

EasyList
EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by DandelionSprout** [comment]
I propose `/delivery/ajss.php?` for the ad on the left on `https://csgo.steamanalyst.com/id/290756037/Glove%20Case`
