### ISSUE TITLE
exactlywhatistime.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16184]
#### List the website(s) you're having issues with:
`https://www.exactlywhatistime.com/days-until/summer`

#### What happens?

Ad placeholders
`##.adthrive-placeholder-header`
`##.adthrive-placeholder-static-sidebar`

#### Screenshot(s) 

![Screenshot from 2023-06-02 18-29-20](https://github.com/easylist/easylist/assets/89158249/ca5d7caf-625c-4738-9fe2-4611e3c66aaa)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b13d9a5ee3c717b60a1fca32d90ba0200732c396
