### ISSUE TITLE
Amazon

### ISSUE THREAD

**Issue by flyingzebras** [easylist/easylist#162]
! 2016-08-16 20:10:25 https://www.amazon.co.uk/s/ref=sr_pg_2?rh=i%3Aaps%2Ck%3Aboot+usb+linux&page=2&keywords=boot+usb+linux&ie=UTF8&qid=1471370558
! Sponsored
||amazon.co.uk,amazon.com###centerPlus

! 2016-08-16 20:12:00 https://www.amazon.co.uk/s/ref=sr_pg_2?rh=i%3Aaps%2Ck%3Aboot+usb+linux&page=2&keywords=boot+usb+linux&ie=UTF8&qid=1471370558
! Self-promotion
||amazon.co.uk,amazon.com###navSwmHoliday

**Comment by monzta** [comment]
Already taken care of.
