### ISSUE TITLE
yagpdb.xyz

### ISSUE THREAD

**Issue by hawkeye116477** [easylist/easylist#1620]
`https://yagpdb.xyz/manage`

### What happens?

Advertisement on bottom left corner.

### List Subscriptions you're using:

EasyList, uBO Default, Polish lists

### Your settings

- OS/version: Manjaro 17.1.11 Hakoila
- Browser/version: Waterfox 56.2.2
- Adblock Extension/version: uBO 1.16.14

### Other details:

![screenshot_20180730_212423](https://user-images.githubusercontent.com/19818572/43418677-f669c716-943e-11e8-95b1-623b0aea8977.png)

**Comment by ryanbr** [comment]
Just a link to their discord? seems fine.
