### ISSUE TITLE
npr.org

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#16219]
`https://www.npr.org/sections/goatsandsoda/2023/06/02/1179434534/a-lullaby-really-can-work-magic-science-tells-us-why-and-how`

ad placeholder 25% down the article.[[1]](https://github.com/easylist/easylist/assets/91396482/0ccf653e-63f8-4a9e-b363-47af80bd62de) Available filters:

```
npr.org###ad-secondary-Music
npr.org###ad-secondary-wrap
npr.org##.ad-config
npr.org##.ad-secondary

```

**Comment by Khrin** [comment]
Looks like it has already been fixed.
