### ISSUE TITLE
real-fix.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16227]
#### List the website(s) you're having issues with:

`https://www.real-fix.com/health/mum-whose-daughter-fought-rare-leukaemia-has-thanked-the-forty-blood-donors-who-saved-her-life/`

#### What happens?
There's a small X button at the bottom of the screen which seems to be an ad leftover.
One of these filters could possibly work:
`real-fix.com##[id^="afc_sidebar_"]`
`real-fix.com###afc_sidebar_81456`

#### Screenshot(s) 

![Screenshot from 2023-06-07 18-32-20](https://github.com/easylist/easylist/assets/89158249/234bedf1-436b-4f8b-a957-20f1c8efc6b1)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by DandelionSprout** [comment]
I propose `real-fix.com##.afc_popup`

**Comment by Sonic5435325** [comment]
Thanks once again! Seems to work just as well as my original proposed filters.
