### ISSUE TITLE
antena3.ro: ads

### ISSUE THREAD

**Issue by claudiu64** [easylist/easylist#16230]
#### List the website(s) you're having issues with:
https://www.antena3.ro/externe/inceput-contraofensiva-ucraineana-razboi-ucraina-8-iunie-2023-676695.html

#### What happens?
Table from the ad, also shows the X button. Remnants of advertisements.

#### Screenshot(s) 
![Screenshot_20230608-150246_Firefox Beta](https://github.com/easylist/easylist/assets/114283947/9071b167-a9e0-4e1c-8736-6bc29a29fdb8)

#### Filter lists you're using: 
Easylist 

#### Your settings:

- OS/version: Android 11
- Browser/version: Firefox Android 114 
- Adblock extension/version: Ublock Origin and Adguard

#### Other details:
Filters are updated daily.

**Comment by Khrin** [comment]
I see that this has been taken care of in more appropriate places.
