### ISSUE TITLE
affiliates.r2net.com

### ISSUE THREAD

**Issue by princesa42** [easylist/easylist#16247]
#### List the website(s) you're having issues with:

jamesallen.com and bluenile.com

#### The problem:
Javascript is blocked because it is hosted on a different subdomain and starts with "affiliates." (which easylist blocks).

However, this code is *not* an advert or third-party affiliate tracker. It just happens to be hosted on the parent company's domain (a recent change) with an unfortunate subdomain choice. Since this does not violate the advert and link exchange policy, please consider adding an "allow" rule.

#### What happens?

If you load either of the below pages with the a_aid parameter set, you will see the request to affiliates.r2net.com fails.
https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-i-color-si1-clarity-very-good-cut-sku-17349217?a_aid=XXX
https://www.bluenile.com/diamond-details/LD21504876?a_aid=XXX

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/132415580/654016ad-b397-40ae-b7e3-000518180c49)

#### Filter lists you're using:

The default list that comes with Adblock Plus: ABP filters and EasyList

#### Your settings:

- OS/version: MacOS Big Sur
- Browser/version: Google Chrome - Version 112.0.5615.137 (Official Build) (x86_64)
- Adblock extension/version: Adblock Plus - 3.17

#### Other details:

Potential fix to be added to `easylist_allowlist.txt`:

`@@||affiliates.r2net.com^$domain=jamesallen.com|bluenile.com`

**Comment by Sonic5435325** [comment]
Is there any specific problem this domain causes by being blocked?
I really don't think the JS listed for that domain causes anything notable to load. Correct me if I'm wrong though. `https://affiliates.r2net.com/scripts/0gvjgz`

**Comment by princesa42** [comment]
It prohibits the referrer (which is that a_aid parameter in the URL) from being logged on the backend database, so the partner channel business really isn’t running because of this.

Again, this is not an advert, link farm, or external affiliate marketing click-out business. It’s just a piece of code that’s used to run this site but which does not affect the customer who happens to be shopping. Rather it affects the business itself.

**Comment by ryanbr** [comment]
Too much privacy issues with https://affiliates.r2net.com/scripts/0gvjgz  Safer to block.
