### ISSUE TITLE
livescience social icons [Fanboy Social / Annoyance]

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#16243]
#### List the website(s) you're having issues with:
`https://www.livescience.com/animals/orcas/orcas-rip-rudder-off-boat-and-follow-it-all-the-way-to-port-in-1st-known-attack-of-its-kind`

#### Screenshot(s) 
![livescience social](https://github.com/easylist/easylist/assets/11689349/b3cbc092-cc47-4489-8b1e-51832217ba24)

#### Other details:
These work (can also drop `circle-icon`):
```
##.facebook-icon.circle-icon
##.flipboard-icon.circle-icon
```

**Comment by Sonic5435325** [comment]
I think `livescience.com##.buttons-social` is a better filter for this sort of thing.

**Comment by yokoffing** [comment]
Twitter and YouTube buttons are also showing now.

@Sonic5435325 filter hides all of them.
