### ISSUE TITLE
The share button is blocked at https://www.bilibili.com

### ISSUE THREAD

**Issue by ohycr** [easylist/easylist#16249]
List the website(s) you're having issues:
https://www.bilibili.com/video/BV1Mu4y1Z7RP

What happens?
The share button is missing.It's important.

List Subscriptions you're using: EasyList – Social Widgets

Before use:

![image](https://github.com/easylist/easylist/assets/128911245/7eed9aa8-3249-419b-a84a-faeb8b633adf)

After use:

![image](https://github.com/easylist/easylist/assets/128911245/24d971c7-ee31-4e82-a9c8-43fd834bd95c)

Your settings
OS/version: Windows 11 build 23475
Browser/version: Microsoft Edge 114.0.1823.43 (64-bits)
Adblock Extension/version: uBlock Origin 1.50.0

**Comment by ryanbr** [comment]
Expected? Share/social elements should be blocked. If you want to share it just copy the url
