### ISSUE TITLE
inherentlyfunny.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16257]
#### List the website(s) you're having issues with:

`https://www.inherentlyfunny.com/`

#### What happens?
Ad placeholder
`inherentlyfunny.com##.break`

#### Screenshot(s) 
![Screenshot from 2023-06-10 16-48-28](https://github.com/easylist/easylist/assets/89158249/038fcf5d-eeaa-4629-9278-504999b3c24c)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/056b8ada278df8be63748944b29ac30f411b2cb5
