### ISSUE TITLE
django-cookie-consent.readthedocs.io

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16252]
#### List the website(s) you're having issues with:
`https://django-cookie-consent.readthedocs.io/en/latest/`

#### What happens?
EasyList Cookie causes tracker scripts to be allowed on this site.
`django-cookie-consent.readthedocs.io/_/api/v2/analytics/`
`django-cookie-consent.readthedocs.io/_/static/javascript/readthedocs-analytics.js`

Also, a lot of GitHub badges and general requests are being blocked.
![Screenshot from 2023-06-10 14-06-13](https://github.com/easylist/easylist/assets/89158249/3c57ab8b-d6a6-4188-9c44-6d07ec76e1ab)

#### Filter lists you're using:

EasyList Cookie
EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by Daxy7** [comment]
for the breakage

```
-cookie-consent.~=django-cookie-consent.readthedocs.io
-cookie-consent./~=django-cookie-consent.readthedocs.io
```

do these work or is it more complicated

**Comment by Sonic5435325** [comment]
That seems to be fine, thanks

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2411668b00d590ed420906952697831e48cf043c

**Comment by Daxy7** [comment]
> [2411668](https://github.com/easylist/easylist/commit/2411668b00d590ed420906952697831e48cf043c)

[434cca6](https://github.com/easylist/easylist/commit/434cca6de451fda9ab0c566b739c121434d54aed)
