### ISSUE TITLE
embed.reddit.com

### ISSUE THREAD

**Issue by MasterKia** [easylist/easylist#16261]
`https://embed.reddit.com/r/oddlyterrifying/comments/1463lck/what_is_happening_here_will_it_go_in_2_pieces_in/`

POST requests containing tracking parameters like `action`, `referrer`, `uuid` and `user_agent`:
`https://embed.reddit.com/svc/shreddit/[Number]`

Proposed rule:
`||embed.reddit.com/svc/shreddit^$xhr,1p`

**Comment by ryanbr** [comment]
I'll check later, not going to break reddit before heading off to bed.
