### ISSUE TITLE
Treating People with Dignity, Especially Women

### ISSUE THREAD

**Issue by princesa42** [easylist/easylist#16265]
Hello @ryanbr,

I find it very insulting and hostile that you are swooping in and closing issues between users and moderators who are engaging in productive conversation, as you have done in https://github.com/easylist/easylist/issues/16247 with myself and [Sonic5435325](https://github.com/Sonic5435325). And furthermore, as a young woman who is not a very good programmer, this is exactly why more women, minorities, and historically marginalized groups are fearful to participate in open source; because their opinions are harshly cast aside and they are left confused and emotionally hurt.

Now, with regards to the specific issue that I raised, I'll attempt to post additional context here:

1. The exception that I raised conforms with EasyList's policy, I believe. It is not an advert or link exchange, and it does not seek to profit by showing ads or selling the user anything. Rather it's just third-party software which is [paid for](https://www.postaffiliatepro.com/pricing/) with a license fee by the domain owner, and it includes a client-side piece of code. If this does not conform to the policy, can you quote which specific part of the policy it violates?

2.  In PR https://github.com/easylist/easylist/issues/16247, you simply state "too much privacy issues". Again I ask, which part of your policy are you referring to? Based on what I can see, this script is simply saving the URL and the referrer to a cookie, which you can see at line 654 of the non-minified version here:
https://gist.github.com/princesa42/ba569efdadb709ba021d32922367fdf7#file-script-js-L654

3. This issue is affecting people's economic livelihood. I obviously realize that installing Ad Block is a choice end users make, and by doing so the parties whom this project seeks to block, and does block, lose money. But based on the project's terms, end users are **not** choosing to block all third-party cookies on the Internet just because they save some piece of data about the user's visit.

Casting possibly legitimate exceptions aside because of non-descriptive privacy concerns is dishonest to your end users because this is not a criteria in the project's stated policy. Given the prevalence of this software, not fairly applying the rules and even worse, not allowing important discussion to take place, is immoral. It hurts people and their families and their communities. So yes, this project is very powerful, and you and your team have done something good for the world by making this software. I commend you all for it. But the power you've accumulated by virtue of your success carries with it a great responsibility which has been shirked. I ask only that a fair determination be made based on the specific policy as it is written, and that useful dialogue be allowed to develop without premature closing of issues.

I look forward to a re-evaluation of my submission and/or a chance to speak with you on this thread without it being abruptly closed.

Thank you,
Elizabeth Prince

**Comment by ryanbr** [comment]
I will evaluate the request, and what a user is asking and whether its in the best interest of the end user and not the company or website. Too many website owners/employees or companys try to justify make an "exception for us.." or "remove rule", makes us suspect on their motivations.

Sex of the person submitting the Github request plays no part. No way to tell from a user name without looking through a profile  (even then people can hide it).  Each Github ticket is based purely on the merits of the request and not the submitter (unless the submitter is abusing the abusing the process or has a histor of).

Maybe closing the ticket was abrupt, my apologies. Why it was rejected as stated it is a privacy issue, the following:

```
Set/check cookies/session/storage
Tracking/visitor ID
```

Making an exception for this script would compromise Easyprivacy based on users with Easylist. The filter isn't new affecting this url, is from _2011_. Don't take offense to a rejection its not based on the person, just the request.

**Comment by ryanbr** [comment]
I'm closing this.
