### ISSUE TITLE
anothersadtrombone.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16272]
#### List the website(s) you're having issues with:
`https://www.anothersadtrombone.com/`

#### What happens?

Ad placeholder
`anothersadtrombone.com###ad`

#### Screenshot(s) 
![Screenshot from 2023-06-11 13-20-35](https://github.com/easylist/easylist/assets/89158249/806c6239-3e64-47d9-8086-f0db8fa64ae6)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Not worth blocking
