### ISSUE TITLE
wsj.com recommended videos

### ISSUE THREAD

**Issue by rpodric** [easylist/easylist#16273]
#### List the website(s) you're having issues with:

 Example article:
`https://www.wsj.com/sports/golf/liv-pga-golf-merger-money-75623873`

#### What happens?

The "Recommended videos" block in articles is not visible when "EasyList – Cookie Notices" is enabled.

#### Screenshot(s) 

`https://i.imgur.com/wjO5Vmr.png`

#### Filter lists you're using:

In addition to defaults:

 added:
`  https://secure.fanboy.co.nz/fanboy-problematic-sites.txt:` 1955-7, 4h.24m
  easylist-annoyances: 3846-38, 13m
  easylist-chat: 126-0, 14m
  easylist-newsletters: 6089-20, 13m
  easylist-notifications: 2629-77, 13m
  fanboy-cookiemonster: 47418-279, never
  fanboy-social: 16070-13, 13m
  ublock-annoyances: 5064-42, 4h.24m

#### Your settings:

- OS/version: Windows 11, 22H2
- Browser/version: Chrome 115.0.5790.24
- Adblock extension/version: uBO 1.50.0

**Comment by ryanbr** [comment]
I think the Recommended videos not showing is a small trade off, than showing the offensive cookie message. Not all sites are like this, but in the case of wsj its better not to show the cookie message

`@@||cdn.privacy-mgmt.com^$domain=wsj.com`

**Comment by rpodric** [comment]
That's reasonable, thanks. I think it's more or less a fluke of the site that the recommended videos list is caught up in this.
