### ISSUE TITLE
wayfair.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16274]
#### List the website(s) you're having issues with:

`https://www.wayfair.com/outdoor/pdp/kidkraft-cranbrook-wooden-outdoor-backyard-swing-set-playset-with-monkey-bars-glider-kk10353.html`

#### What happens?

Tracker
`s.wayfair.com/events/`
`webcollage.net/site/wayfair/tag.js` (Possible but unsure)

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
I didn't see the first item and the 2nd seems safe.

**Comment by Sonic5435325** [comment]
The first one loads after about 20 seconds I think
