### ISSUE TITLE
connatix.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16298]
#### List the website(s) you're having issues with:

`https://connatix.com/`

#### What happens?

I found possible trackers loaded when you visit the site directly. Not sure if these should be added or if connatix.com should be blocked even when visiting it directly.
`||connatix.com/scripts/facebook-pixel-script.js`
`||connatix.com/scripts/gaconnector.js`
`||connatix.com/scripts/microsoft-ad-script.js`
`||connatix.com/scripts/munchkin-script.js`
`||connatix.com/scripts/hotjar.js`

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by yokoffing** [comment]
Also `websights-script.js` and `mkt-cke-script.js`.

**Comment by Sonic5435325** [comment]
Thanks for the updates!

**Comment by ryanbr** [comment]
More of placeholder, than actual trackers, they'll load the other scripts which are blocked.
