### ISSUE TITLE
geometrydash.io

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16294]
#### List the website(s) you're having issues with:
`https://geometrydash.io/`

#### What happens?

Ad placeholder
`geometrydash.io##.RowAdv`
![Screenshot from 2023-06-13 17-13-50](https://github.com/easylist/easylist/assets/89158249/9a92606d-d2ac-4078-8292-d8a86faaf2c2)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by DandelionSprout** [comment]
There doesn't seem to be any other sites that use the same GUI, so the suggested specific entry would be the best option indeed.
