### ISSUE TITLE
accessibility is blocked and shouldn't be blocked

### ISSUE THREAD

**Issue by SmoothPassionLLC** [easylist/easylist#16292]
unblock https://acsbapp.com/apps/app/dist/js/app.js that for screenreaders and glitches brave browsers for people that require that tool

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Also tracks/logs. So unless that changes, it'll remain blocked.

**Comment by bloudermilk** [comment]
@ryanbr do you have a source for that claim? This is a widely used a11y tool for supporting users with disabilities.
