### ISSUE TITLE
Swedish pirate movie sites

### ISSUE THREAD

**Issue by flyingzebras** [easylist/easylist#163]
! Banner ad
||swefilm.tv/partner/_._$image

! Banner ad hosted on dreamfilmhd.bz and most likely on a other sites too.
||dreamvtt.com/imagehost/data/uploads/users/c8bd9154-1306-4733-9432-a0cb0a88b4f4/2110187740.jpg$image

**Comment by monzta** [comment]
What are the URLs of the pages?

**Comment by flyingzebras** [comment]
@monzta
* swefilm.tv - main page -  ||swefilm.tv/partner/.$image
* dreamfilmhd.bz - main page -  ||dreamvtt.com/imagehost/data/uploads/users/c8bd9154-1306-4733-9432-a0cb0a88b4f4/2110187740.jpg$image

**Comment by flyingzebras** [comment]
It doesn't really matter though. Popcorn-Time is ad free.
