### ISSUE TITLE
udemy.com

### ISSUE THREAD

**Issue by ozgeozgur** [easylist/easylist#16309]
#### List the website(s) you're having issues with:
`udemy.com and subdomains of it`

#### What happens?
I am writing to address an issue we are currently facing with event blocking on our learning platform, udemy.com. Our platform serves as an online learning resource, offering a wide variety of courses to our users. However, we have recently discovered that our user events are being blocked when users have EasyPrivacy enabled with the uBlock Chrome extension.

Our website relies on these user events to maintain basic functionality for people learning on our platform, to ensure fast and stable performance of course videos to users, and provides users with more personalized and useful web experiences. Udemy does not share any of our first-party event tracking with any third parties or ad networks.

Regrettably, we have found that user events related to Udemy are now being blocked when users have EasyPrivacy enabled through the uBlock Chrome extension. It appears that Udemy has been added to the EasyPrivacy list, which uBlock utilizes. This change took place on May 9th.
> easyprivacy.txt: [EasyPrivacy List](https://easylist.to/easylist/easyprivacy.txt)
> GitHub pull request: [GitHub Pull Request](https://github.com/easylist/easylist/pull/15847/files)

Udemy’s website does not serve any ads to users, nor do we engage in any attempts to bypass ad-blockers. We believe that the blocking of our events is an unintended side effect arising from the inclusion of our site on the EasyPrivacy list, possibly due to misunderstandings regarding our internal tracking practices. We want to emphasize: We strictly adhere to all user privacy regulations and we prioritize the protection of user data, including data from user events that we collect to help operate basic functionality of our learning platform.

We like to please request that our site (Udemy.com) be added as an exclusion for this list. We would like our customers to be able to have EasyPrivacy enabled in their browsers, but also have the learning tools at Udemy.com’s website be fully functional for them.

#### Filter lists you're using:
uBlock with EasyPrivacy enabled.

#### Your settings:

- OS/version: macOs Ventura 13.3.1
- Browser/version: Google Chrome - Version 113.0.5672.126 (Official Build) (x86_64)
- Adblock Extension/version: uBlock Origin 1.49.2 + EasyPrivacy option turned on.

**Comment by ryanbr** [comment]
Event logs should be blocked as per https://github.com/easylist/easylist/blob/master/README.md#easyprivacy
