### ISSUE TITLE
ticketmaster.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16308]
#### List the website(s) you're having issues with:
`https://www.ticketmaster.com/`

#### What happens?
Top links brings you to `doubleclick.net`, a blocked site

#### Screenshot(s) 
![Screenshot from 2023-06-14 23-03-00](https://github.com/easylist/easylist/assets/89158249/b029cf6d-2ff1-44a4-9f0c-968287306222)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by Daxy7** [comment]
where exactly? found sidebar ad placeholder
```
https://www.ticketmaster.com/search?q=test
```

```
ticketmaster.com##.jeMIud
```
