### ISSUE TITLE
adf.ly

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16319]
#### What happens?

Adf.ly seems to be dead now. The website and any other subdomain seems to redirect to `https://migrate-adfly.linkvertise.com`.

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Are adf.ly links changed also or are they still the same?

**Comment by Sonic5435325** [comment]
@ryanbr Using `http://adf.ly/1mAmwB`, it seems like it also just redirects to Linkvertise.
