### ISSUE TITLE
baidu.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16338]
#### List the website(s) you're having issues with:

`https://www.baidu.com/s?wd=test`

#### What happens?

Possible tracker
`||baidu.com/*/ps_default.gif?`

#### Filter lists you're using:
EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
How do we know its a tracker?

**Comment by Sonic5435325** [comment]
Well, from what I remember, it made more than one request when searching.

**Comment by Sonic5435325** [comment]
I should've clarified what I meant a bit more in my other comment, but when making a search directly from the homepage, the request will usually load around 4 times.
![Screenshot from 2023-06-18 14-36-50](https://github.com/easylist/easylist/assets/89158249/8aa0a182-6734-48b9-8073-39b1b2aee30e)
