### ISSUE TITLE
lasopabowl158.weebly.com (misleading)(malware)(phishing)

### ISSUE THREAD

**Issue by gkhull** [easylist/easylist#16334]
Link is potentially malicious if file is downloaded. The page displays a fake mediafire download if browsing outside of a VM, browsing inside of a VM causes the site to display "normal" content and evade detection

https://lasopabowl158.weebly.com/calyx-point-for-mac-download.html

URL
`https://lasopabowl158.weebly.com/calyx-point-for-mac-download.html`

#### What happens?
This is displayed when viewed in a VM
![vm-view](https://github.com/easylist/easylist/assets/26993576/720bc2af-62a0-4e12-a39e-ea3f7f0db643)

This is displayed when viewed outside of a VM 
![non-vm](https://github.com/easylist/easylist/assets/26993576/c018370e-7aa1-4364-8364-a3d76658b364)

#### Filter lists you're using:
OISD, Adguard base, adguard annoyances, adguard annoyances other, adguard cookies, adguard popups, adguard mobile banner warning, adguard unbreak
#### Your settings:
- OS/version: Windows 11 x64
- Browser/version: Brave 1.52.126

**Comment by Sonic5435325** [comment]
Probably best to report it to URLhaus.
https://urlhaus.abuse.ch/
