### ISSUE TITLE
warringtonguardian.co.uk

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16331]
#### List the website(s) you're having issues with:

`https://www.warringtonguardian.co.uk/`

#### What happens?
Ad placeholder
`warringtonguardian.co.uk##.top-dfp-wrapper`

#### Screenshot(s) 

![Screenshot from 2023-06-16 18-02-26](https://github.com/easylist/easylist/assets/89158249/4461de55-51d9-4002-a3f5-fe6bdeed0137)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
`###DFP_top_leaderboard` already have this blocked?
