### ISSUE TITLE
20minutos.es

### ISSUE THREAD

**Issue by samueldiethelm** [easylist/easylist#16330]
#### List the website(s) you're having issues with:

`20minutos.es`

#### What happens?

Cookie policy popup is displayed. Scrolling is also blocked.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/1754569/ea99ba5a-d8ef-4430-a9ba-eb54c04e7814)

#### Filter lists you're using:

EasyList Cookie, EasyList Spanish

**Comment by ryanbr** [comment]
Can't counter without breaking site sorry.
