### ISSUE TITLE
herz-fuer-tiere.de

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16339]
#### List the website(s) you're having issues with:

`https://herz-fuer-tiere.de/`

#### What happens?

Trackers
`||herz-fuer-tiere.de/assets/themes/default/images/ad.gif?$image,1p`
`||herz-fuer-tiere.de/assets/themes/default/images/sunshine.gif?$image,1p`

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
How do we know its a tracker?

**Comment by Sonic5435325** [comment]
I assumed it was since it was a 1x1 pixel. Maybe it could be an inage placeholder, but blocking them doesn't seem to cause breakage.

**Comment by Sonic5435325** [comment]
While this issue is open, I'll also report this newsletter thing I found at the bottom of the page.
`herz-fuer-tiere.de##.campaign__item--newsletter`
![Screenshot from 2023-06-18 21-07-49](https://github.com/easylist/easylist/assets/89158249/561f6046-31aa-4f69-bdfe-72a88e1fc6c3)

**Comment by Sonic5435325** [comment]
@Khrin Thanks. Can you also add the other 2 annoyances I mentioned in these comments?
