### ISSUE TITLE
kiplinger.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16337]
#### List the website(s) you're having issues with:

`https://www.kiplinger.com/`

#### What happens?

Ad placeholder
`kiplinger.com###top-leaderboard`

#### Screenshot(s) 

![Screenshot from 2023-06-17 19-28-52](https://github.com/easylist/easylist/assets/89158249/eb88791c-13c0-40f2-96b4-0a9b23db95ed)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
No blank space here

**Comment by Sonic5435325** [comment]
@ryanbr I can see it even on default uBlock Origin settings.

**Comment by Sonic5435325** [comment]
Oh, I can see why.
#@#.ad-unit in uBlock filters - Ads causes this placeholder to appear. My bad.
