### ISSUE TITLE
nationalworld.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16347]
#### List the website(s) you're having issues with:

`https://www.nationalworld.com/news/politics/partygate-video-tory-staff-drinking-dancing-during-covid-lockdown-4187036`

#### What happens?

Ad placeholder
`nationalworld.com##.banner`

#### Screenshot(s) 

![Screenshot from 2023-06-18 14-30-02](https://github.com/easylist/easylist/assets/89158249/da17f31d-699c-43f2-a440-61b7f8965463)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by DandelionSprout** [comment]
There also seems to be various "Ad loading…" boxes in that article, for which I propose `nationalworld.com##div[class^="helper__AdContainer-sc-"]`
