### ISSUE TITLE
lndo.site

### ISSUE THREAD

**Issue by millnut** [easylist/easylist#16343]
#### List the website(s) you're having issues with:

`*.lndo.site`

#### What happens?

When working on a project using Lando (https://lando.dev/) all local development domains `*.lndo.site` are blocked. `*.lndo.site` should not be blocked.

#### Filter lists you're using:

EasyPrivacy

**Comment by almunnings** [comment]
Looks like a poor addition, it's a developer tool. 
It's intended to be local traffic 🤷‍♂️ 

Please consider removing.

**Comment by simesy** [comment]
Some additional context

> Specifically, *.lndo.site is an actual ON THE INTERNET wildcard DNS entry that points all *.lndo.site subdomains to localhost/127.0.0.1. This means that if you lose your internet connection, you will not be able to visit your app at these addresses. However, you can [take steps](https://docs.lando.dev/core/v3/proxy.html#working-offline-or-using-custom-domains) to work around this restriction or use your own [custom domain](https://docs.lando.dev/core/v3/proxy.html#configuration) and handle the DNS yourself with dnsmasq or some other solution.

https://docs.lando.dev/core/v3/proxy.html

**Comment by millnut** [comment]
This also causes the website to be blocked by ad blockers such as uBlock Origin that use the EasyPrivacy list by default. Every time this local development domain is visited it is blocked and needs to be whitelisted.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/issues/16372#issuecomment-1598066747
