### ISSUE TITLE
verywellmind.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16366]
#### List the website(s) you're having issues with:

`https://www.verywellmind.com/signs-you-may-be-demiromantic-7482879`

#### What happens?

Ad gap
`verywellmind.com##.mntl-leaderboard-spacer`

#### Screenshot(s) 
![Screenshot from 2023-06-19 15-46-43](https://github.com/easylist/easylist/assets/89158249/0a17c5ae-9eea-4d38-b169-5332611916ee)

#### Filter lists you're using:
EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by DandelionSprout** [comment]
A generic `##.mntl-leaderboard-spacer` would've likely fixed both this and #16038.

**Comment by Sonic5435325** [comment]
@DandelionSprout Thanks for the pull request, Imre!

**Comment by Daxy7** [comment]
ad placeholder ceiling is back
the removed cosmetic filter in pull request is now viable
`verywellmind.com###mntl-leaderboard-header_1-0`
https://github.com/easylist/easylist/assets/91396482/b95a01a9-ee46-4b63-bea0-3a256d001a86
