### ISSUE TITLE
False positive blocking asyncjs. without any reference to ads or sponsoring related JavaScript?

### ISSUE THREAD

**Issue by mtelgkamp** [easylist/easylist#16360]
#### What happens?

File names containing `asyncJs.` are generally blocked. Also `asyncJs.html` or `asyncjs.mp4` which could be names for tutorials on async JavaScript would be blocked.

The filename part does not contain anything giving a relation to ads, sponsoring or similar and using JavaScript that is loaded async is quite common, so I assume there might be more false positives than real hits. Additionally, I do not see files with his name commonly used for ad related content.

I know that https://github.com/easylist/easylist/issues/2321 already had some statements that the filter might be too greedy, but the comments were rejected without any comment on why `asyncjs` is related to ads. It was said that the rule could be changed to ` /asyncjs.$domain=~asyncjs.com|~martinfowler.com` in that specific case, but I do not see the advantage or the need for everyone using asyncjs as a filename to rename the file - especially as it is hard to figure out this is the problem, when the page developer(s) are not using an ad list on their own.

Later in https://github.com/easylist/easylist/issues/4884 a change was done by adding an exception in https://github.com/easylist/easylist/commit/d8e254c40a13b6ad29f5772d7cef3863312eca42 this had a similar effect as the change requested above, but only for a `css` file used on this site.

https://github.com/easylist/easylist/issues/15375 also requests another exception.

If there are examples in the wild for ads using this filename, the rule should be more specific otherwise I suggest the rule should be removed.

#### Filter lists you're using:

EasyList

#### Other details:

The corresponding filter entry https://github.com/easylist/easylist/blob/b754e22657f17885176a1a0f718324fa5e3349d7/easylist/easylist_general_block.txt#L1730

In case it is removed, also the exception https://github.com/easylist/easylist/blob/b754e22657f17885176a1a0f718324fa5e3349d7/easylist/easylist_allowlist.txt#L160 can be removed

**Comment by Khrin** [comment]
Thanks for your opinion.
