### ISSUE TITLE
plagiarismdetector.net

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#16364]
![image](https://github.com/easylist/easylist/assets/19517680/300ba61a-1d26-4252-aaef-e997f8b8c722)

https://plagiarismdetector.net/

**Comment by Khrin** [comment]
Looks like it is already blocked.

**Comment by Sonic5435325** [comment]
This might be caused by `@@*$generichide,from=plagiarismdetector.net` in uBlock filters - Ads.

**Comment by Sonic5435325** [comment]
This problem has also been reported here: https://github.com/uBlockOrigin/uAssets/issues/18607
