### ISSUE TITLE
https://github.com/managed-components/google-ads

### ISSUE THREAD

**Issue by scamiv** [easylist/easylist#16396]
#### List the website(s) you're having issues with:
`https://github.com/managed-components/google-ads`

#### What happens?

Partially blocked by rule /google-ads/*

#### Filter lists you're using:

EasyList

#### Other details:

XHR requests being blocked, unable to view commit history and source files.

**Comment by DandelionSprout** [comment]
`/google-ads/*` seems to have been removed from EasyList sometime in the past 6 months, so this report can presumably considered solved.
