### ISSUE TITLE
aleteia.org

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16401]
#### List the website(s) you're having issues with:

`https://aleteia.org/2023/06/21/aleteia-2023-summer-book-list-adult-fiction-and-nonfiction/`

#### What happens?
Ad placeholders
`aleteia.org##.css-y2cft7`
![Screenshot from 2023-06-21 19-36-42](https://github.com/easylist/easylist/assets/89158249/475f7c4c-9056-4af4-893d-f6b01f6456bb)

`aleteia.org##.css-12zi9k6 > div:has([id*="-ad_"])` (This one could probably be improved, but it's just a suggestion)
![Screenshot from 2023-06-21 19-36-44](https://github.com/easylist/easylist/assets/89158249/6de3016d-15bb-4637-bf96-d60d339541a2)

Newsletter
`aleteia.org##.eiz4mud3`
![Screenshot from 2023-06-21 19-39-37](https://github.com/easylist/easylist/assets/89158249/9eb247cf-fb32-462d-81fc-14a3d4219e96)

`aleteia.org##.e1xa1zfx12`
![Screenshot from 2023-06-21 19-40-33](https://github.com/easylist/easylist/assets/89158249/0f4b6690-4400-4ae2-b08d-fa26c3ec986a)

#### Filter lists you're using:

EasyList
Fanboy's Annoyance/Newsletter

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by DandelionSprout** [comment]
`aleteia.org#?##root > div[class]:has(>.adslot)` seems like it'd work for the first one. The other two are outside of my speciality fields.
