### ISSUE TITLE
tweakers.net

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16405]
#### List the website(s) you're having issues with:

`https://tweakers.net/`

#### What happens?

Tracker
`||tweakers.net/i/*/1280x400/`
Has two requests, one in an image, and one in XHR
Also `||tweakers.nl/track/`
#### Filter lists you're using:
EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by Khrin** [comment]
Not necessary.
