### ISSUE TITLE
thetoyinsider.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#16445]
#### List the website(s) you're having issues with:

`https://thetoyinsider.com/my-little-pony-bridlewoodstock-news/`

#### What happens?

A large ad on top, and a placeholder in the right aside feed.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/22780683/046aabfe-79fc-4c8d-9f60-d9a497bc7204)

#### Filter lists you're using:

<details>

![image](https://github.com/easylist/easylist/assets/22780683/5f0122c0-87da-4422-a0aa-6ad53f9e6992)

</details>

#### Your settings:

- OS/version: Windows 11 22H2 x64
- Browser/version: Chrome 114.0.5735.134 x64
- Adblock extension/version: uBO 1.50.0 + IDCAC 3.4.7

#### Other details:

I propose:
```
thetoyinsider.com##.header-drop-zone
##div.apb-adblock
! Optional
-Banner-970-x-250.gif^
```

**Comment by Sonic5435325** [comment]
Some more filters:
Annoyance

Social
`thetoyinsider.com##.social-icons`

Newsletter and ad placeholder
`thetoyinsider.com###h-the-playlist-newsletter`
`thetoyinsider.com##.gform_wrapper`
`thetoyinsider.com##.wds-block-newsletter`

`thetoyinsider.com##.apb-adblock`

![Screenshot from 2023-06-24 17-56-44](https://github.com/easylist/easylist/assets/89158249/8e4b022d-766b-4365-a4ab-eb4633e919bd)
![Screenshot from 2023-06-24 17-58-12](https://github.com/easylist/easylist/assets/89158249/f4b91dff-3d90-476f-b1b3-f82d003702db)
