### ISSUE TITLE
emojipedia.org

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16453]
#### List the website(s) you're having issues with:

`https://emojipedia.org/independence-day`

#### What happens?
Ad placeholder
`emojipedia.org[class^="AdContainer_ad__"]`

#### Screenshot(s) 
![Screenshot from 2023-06-24 20-23-15](https://github.com/easylist/easylist/assets/89158249/4ea1c87a-66c9-46d4-b7f4-63924cba19fd)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by Yuki2718** [comment]
I don't see. @pgl Admiral `pocketfaucet.com`

**Comment by pgl** [comment]
> I don't see. @pgl Admiral `pocketfaucet.com`

Added, thanks.
