### ISSUE TITLE
new google fonts url to block (fanboy anti third-party fonts)

### ISSUE THREAD

**Issue by jordanswrld94** [easylist/easylist#16467]
![Untitled](https://github.com/easylist/easylist/assets/118186787/658b4336-ac7e-4921-86d4-beb95bc5de08)

https://www.nexusmods.com/ (for css2) ||fonts.googleapis.com/css2?

**Comment by Sonic5435325** [comment]
Wouldn't it be easier to just block the entire domain `||fonts.googleapis.com^` or `||fonts.googleapis.com^$3p` since it's only a CDN for fonts anyways?

**Comment by Khrin** [comment]
@jordanswrld94 Please ask here: https://github.com/ryanbr/fanboy-adblock/issues
