### ISSUE TITLE
history.co.uk

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16462]
#### List the website(s) you're having issues with:

`https://www.history.co.uk/articles/the-history-of-the-ashes`

#### What happens?

Ad script
`history.co.uk/themes/custom/sky_history/js/taboolaEnd.js`

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Seems fine, really minor
