### ISSUE TITLE
natgeotv.com - Video player broken

### ISSUE THREAD

**Issue by tetku** [easylist/easylist#16468]
#### List the website(s) you're having issues with:

`https://www.natgeotv.com/uk/shows/natgeo/europe-from-above/videos/europe-from-above-season-5-sundays`

#### What happens?

Video player broken

#### Screenshot(s) 

<details><summary>Screenshot</summary>

![resim](https://github.com/easylist/easylist/assets/135356201/66c9542a-4f36-43bf-8948-9d72bce854ff)
![resim](https://github.com/easylist/easylist/assets/135356201/af490d04-6bf1-409a-a736-d31119a4cabe)

</details>

#### Filter lists you're using:

EasyList, EasyPrivacy, All uBO filters

#### Your settings:

- OS/version: Win10
- Browser/version: Chrome 114
- Adblock extension/version: uBlock Origin 1.50

#### Other details:

These two rules cause breakage.

```
/visitorapi.js
/appmeasurement.js
```

**Comment by stephenhawk8054** [comment]
@Yuki2718 These look works for me, does it work on your side?

```adb
natgeotv.com##+js(no-xhr-if, /VisitorAPI|AppMeasurement/)
natgeotv.com##+js(set, Visitor, {})
```

**Comment by Yuki2718** [comment]
> does it work on your side?
> 

![natgeotv](https://github.com/easylist/easylist/assets/58900598/f6fcc114-a73a-44d3-9da1-c3487e885628)
