### ISSUE TITLE
joinonelove.org

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16475]
#### List the website(s) you're having issues with:
`https://www.joinonelove.org/`

#### What happens?
Newsletter
`joinonelove.org##.footer-form`

#### Screenshot(s) 
![Screenshot from 2023-06-26 23-27-39](https://github.com/easylist/easylist/assets/89158249/fdbcd8c5-ce69-4fd7-9a9d-a71da994fb1a)

#### Filter lists you're using:

Fanboy's Annoyance/Newsletter

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Its fine, leaving
