### ISSUE TITLE
kat.rip

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16476]
#### List the website(s) you're having issues with:
`https://kat.rip/usearch/test/`

#### What happens?
Sponsor section
Filter suggestion: `kat.rip##.pusher` (Hides the section under the header, but the element is still "there". Seems to break other pages on the site like `https://kat.rip/music/` though.)

#### Screenshot(s) 

![Screenshot from 2023-06-27 00-22-01](https://github.com/easylist/easylist/assets/89158249/40d75355-a444-44c5-bf72-cedf7481ab25)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Happy to leave
