### ISSUE TITLE
lefigaro.fr

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#16487]
### List the website(s) you're having issues:

```
https://video.lefigaro.fr/figaro/video/les-gestes-damour-prennent-plusieurs-formes-dans-une-video-humoristique-lukraine-demande-plus-de-caesar-a-la-france/
```

### What happens?

The video does not work. `||static.lefigaro.fr/figconsent/` ~> **EasyList – Cookie Notices**

<details>
<summary>Screen</summary>

![2023-06-27_205557](https://github.com/easylist/easylist/assets/111344219/36bac6f4-2cf5-49bf-8d28-ce25216211bb)
![2023-06-27_205454](https://github.com/easylist/easylist/assets/111344219/cf3a2c2e-b57a-4523-9009-24040444e254)
![2023-06-27_205608](https://github.com/easylist/easylist/assets/111344219/a5dfccf7-fb68-4ce6-a355-d2782724c45f)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome (stable)
- Adblock Extension/version:  uBO (stable)

@ryanbr, @Yuki2718

**Comment by dportvine** [comment]
@peace2000 
Can you fix this?

<details>
<summary>Screen</summary>

![2023-06-27_205454](https://github.com/easylist/easylist/assets/111344219/cf3a2c2e-b57a-4523-9009-24040444e254)
</details>

**Comment by peace2000** [comment]
@dportvine Yeah, fixed in uAssets: https://github.com/uBlockOrigin/uAssets/commit/be7f265a713310888204fdd0902c7d4b8fffda6c

**Comment by garry-ut99** [comment]
Video broken again.
