### ISSUE TITLE
daiichi-kamotsu.co.jp

### ISSUE THREAD

**Issue by SKEIDs** [easylist/easylist#16482]
#### List the website(s) you're having issues with:
 https://www.daiichi-kamotsu.co.jp/service/cooler/

#### What happens? 

 Analytics 
`https://www.daiichi-kamotsu.co.jp/js/google_analytics.js`

#### Screenshot(s) 

<details><summary>screenshot</summary>

![](https://i.ibb.co/JmB498W/image.png)
</details><br/>

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: Windows 11 22H2
- Browser/version: Google Chrome 114.0.5735.90
- Adblock extension/version:  uBlock Origin 1.50.0

#### Other details:

This is my first issue on Easylist. 
Sorry if there is any problem.

**Comment by Sonic5435325** [comment]
For annoyance:
`daiichi-kamotsu.co.jp###pagetop`
![Screenshot from 2023-06-28 03-32-55](https://github.com/easylist/easylist/assets/89158249/368c7055-2104-4e85-8c1d-413afa958c00)
