### ISSUE TITLE
lyingshayride.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16495]
#### What happens?

http://lyingshayride.com/ is a dead domain and is no longer needed.

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
```
  Updated Date: 2023-06-24T22:07:00Z
   Creation Date: 2023-06-24T22:07:00Z
```

Check whois.
