### ISSUE TITLE
zoechip.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16497]
#### List the website(s) you're having issues with:
`https://www3.zoechip.com/`

#### What happens?

Ad domains
`||eqkjmvkkmvrvw.top^`
`||zumrieth.com^`

Popups
`||tiffanypinworm.tech^`
`||deadlyrelationship.com^`

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Can you just ease up submitting requests, flooding the reports isn't good. @Sonic5435325

**Comment by Sonic5435325** [comment]
@ryanbr Sorry about that, I'll try to post a little less.
