### ISSUE TITLE
[NSFW] pornbox.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16492]
#### List the website(s) you're having issues with:

`https://pornbox.com/application/watch-page/432018`

#### What happens?
Tracker
`analytics.gtflixtv.com`

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by Khrin** [comment]
Not needed.

**Comment by Sonic5435325** [comment]
I'll close this then.
