### ISSUE TITLE
Blank page on kombi.de

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylist#16504]
#### List the website(s) you're having issues with:

`https://www.kombi.de/`

#### What happens?

Blank screen appears instead of website content

#### Screenshot(s) 

![Screenshot 2023-06-28 at 5 05 57 PM](https://github.com/easylist/easylist/assets/56893063/56fc08de-f459-440c-8d84-83e01c42e313)

#### Filter lists you're using:
ABP filters, EasyList

#### Your settings:

- OS/version: MacOs Ventura 13.4
- Browser/version: Firefox Version 114.0.2 (64-bit)
- Adblock extension/version: Adblock Plus 3.17.1

**Comment by Khrin** [comment]
https://github.com/easylist/easylistgermany/blob/master/easylistgermany/easylistgermany_allowlist_general_hide.txt#L8
