### ISSUE TITLE
refinery29.com - Cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#16514]
### List the website(s) you're having issues:

- `https://www.refinery29.com/en-us`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 114
Adblock Extension/version: AdblockPlus 3.17.1

<img width="1680" alt="image" src="https://github.com/easylist/easylist/assets/2988929/bbe7df6e-0b6d-4e1e-b711-f938f971896e">

**Comment by ryanbr** [comment]
Can't block in ABP, due to lack of scrollbar.

**Comment by Sonic5435325** [comment]
Can be fixed in AdGuard/uBlock annoyances.
