### ISSUE TITLE
refinery29.com - cookie notice visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#16513]
### List the website(s) you're having issues:

- `https://www.adidas.de/`

### What happens?

The CMP/Cookie modal is visible.

### List Subscriptions you're using:

- `EasyList Cookie List`

### Your settings

OS/version: macOS Monterey 12.5
Browser/version: Chrome 105
Adblock Extension/version: AdblockPlus

**Comment by krystian3w** [comment]
Bad title.

**Comment by alexm92** [comment]
sry, updated it

**Comment by krystian3w** [comment]
Still bad, you link to adidas.de in "16513".
