### ISSUE TITLE
thesun.co.uk, the-sun.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16517]
#### List the website(s) you're having issues with:

`https://www.the-sun.com`
`https://www.thesun.co.uk`

#### What happens?

Seems like there's a tracker on both sites.
`https://www.thesun.co.uk/assets/client/web-vitals~31ecd969.bd62a58d596e657a5677.1.js`
`/assets/client/web-vitals~$domain=the-sun.com|thesun.co.uk`

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
We'll leave this
