### ISSUE TITLE
ip2location.com not an ad service (false-positive)

### ISSUE THREAD

**Issue by ip2location** [easylist/easylist#1652]
Hi,

The URL ip2location.com should not be on the list of blocked URLs. The site provides geolocation service but it does not serves any ads and contents.

Please review and remove it from the easy list.

Thank You.

**Comment by THEtomaso** [comment]
The following rule is NOT in '**EasyList**', but in '**EasyPrivacy**' (and other ones, like **AdGuard's Spyware filter**):
`||ip2location.com^$third-party`
This is a correct blocking.
People that wants to get tracked via geolocation services shouldn't be using privacy filters.
