### ISSUE TITLE
publico.pt

### ISSUE THREAD

**Issue by gabrielvicenteYT** [easylist/easylist#16536]
#### List the website(s) you're having issues with:

``https://publico.pt``

#### What happens?

Just some empty ad banners

#### Screenshot(s) 

![imagem](https://github.com/easylist/easylist/assets/68158102/b22a5f7c-dabc-441a-a2e0-b2f7013b745b)

#### Filter lists you're using:

All uBO Filters, EasyList, EasyPrivacy, Online Malicious URL Blocklist, Pete Lowe's Ad and tracking server list

#### Your settings:

Slightly softened Arkenfox (RFP off, some minor tweaks)
No extensions can possibly affect this, since I'm only using uBO for Privacy, and some extensions such as Proton Pass, User Agent Switcher to access paywalled articles, etc.

- OS/version: 
- Browser/version: Firefox (Latest version as of 1st July 2023) 
- Adblock extension/version: uBO (Latest version as of 1st July 2023)

#### Other details:

I might have found an uBO self-made fix below:

```
www.publico.pt##.aside--ads.aside

```

**Comment by Khrin** [comment]
Please enable the appropriate filter list for your language in your adblocker.

**Comment by gabrielvicenteYT** [comment]
@Khrin I had it on, just forgot to add it to the list here, my bad.
