### ISSUE TITLE
lemino.docomo.ne.jp

### ISSUE THREAD

**Issue by Aki13579** [easylist/easylist#16535]
#### List the website(s) you're having issues with:
https://lemino.docomo.ne.jp/home/recommend/genre/2-1-111?crid=Y3JpZDovL3BsYWxhLmlwdHZmLmpwL3ZvZC8wMDAwMDAwMDAwXzAwbGJnYXMxMzA%3D

#### What happens?
Video/Live streaming didnot start.

#### Screenshot(s) 
<img src="https://raw.githubusercontent.com/Aki13579/personal-public-area/main/screenshot%202023-07-01%20200405.jpg" />

#### Filter lists you're using:
EasyList (Last modified: Sat, 01 Jul 2023 08:55:28 +0000)

#### Your settings:

- OS/version: Windows 10
- Browser/version: Chrome/114
- Adblock Extension/version: uBlock Origin 1.50.0 （turned off default blocklists）

#### Other details:

fix the issue
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=lemino.docomo.ne.jp
`

**Comment by Sonic5435325** [comment]
@Yuki2718 Annoyance "back to top" script: breedingmoms.com/js/top.js
