### ISSUE TITLE
clxgaming.com (easyprivacy)

### ISSUE THREAD

**Issue by jordanswrld94** [easylist/easylist#16555]
https://e.fomo.com/api/v1/js-obj/56ZfbiNBANI0VViO0RI8Xg/events/events.js?lng=en

||fomo.com/*/events/events.js?

source: https://www.clxgaming.com/

**Comment by Sonic5435325** [comment]
For annoyance:
`clxgaming.com##.scroll-top`
`||www.clxgaming.com/img/global-images/topup.png`
![Screenshot from 2023-07-07 01-42-03](https://github.com/easylist/easylist/assets/89158249/bc3d935f-0582-44cf-b949-fb54993a9b83)
