### ISSUE TITLE
easylist blocks almost entire TLDs

### ISSUE THREAD

**Issue by jomo** [easylist/easylist#16552]
https://github.com/easylist/easylist/blob/1785749a281f6824f714bdad170ad80051a62840/easylist/easylist_specific_block.txt#L478

This blocks almost any third party requests to .digital, .website, .life, .guru, and .space TLDs. It doesn't seem rational to block only these specific TLDs, but no others, and this is obviously results in a lot of false positives.

The common approach to fix false positives (e.g. https://github.com/easylist/easylist/commit/c9c80356b3901d6a64317dcaaf56bf3a007e76fe) is adding single, affected domains as exceptions (~bitrix24.life, ~ccc.ac, ~localhost, ~mempool.space, ~scribble.ninja, ~scribble.website, ~traineast.co.uk), which seems like a bad fix, as it only compensates single symptoms, but not the actual cause of the problem.

I recommend replacing this line with something that only blocks whatever was supposed to actually be blocked instead of blocking entire TLDs.

**Comment by cryptoquick** [comment]
Agreed, this is not a great solution, it blocks legitimate traffic and causes headaches for our users. This is even worse as browsers start building in blocklists and enabling them by default. I would recommend also notifying browser vendors like Chrome, Vivaldi, Brave, and others who do this to not blindly trust things like EasyList. One such URL to test is: `https://mempool.space/testnet/api`

**Comment by cryptoquick** [comment]
Related: #16042

**Comment by krystian3w** [comment]
Recheck: https://github.com/easylist/easylist/commit/bb52acaf24a8ceffae666e416d57239b2842fa58
