### ISSUE TITLE
kimcartoon.li

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16557]
#### List the website(s) you're having issues with:

`https://kimcartoon.li/Cartoon/Nimona/Movie?id=108718`

#### What happens?
A "back to top" annoyance.
Suggested filter: `kimcartoon.li##[href="#"]`

#### Screenshot(s) 

![Screenshot from 2023-07-02 18-19-38](https://github.com/easylist/easylist/assets/89158249/71f04260-9962-467f-a2c3-142631082688)

#### Filter lists you're using:

Fanboy's Annoyance

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by jordanswrld94** [comment]
also looks like an ad script: https://lmwn.ljlmzblvrvrz.top/kwmbqjbnqvbwy/ezkjw

**Comment by Sonic5435325** [comment]
Thanks for reporting.
