### ISSUE TITLE
https://ads.ttpl.vn/

### ISSUE THREAD

**Issue by HoangHaiDang02** [easylist/easylist#16566]
#### List the website(s) you're having issues with:
https://ads.ttpl.vn/

#### What happens?
abp block css in site

#### Screenshot(s) 
![image](https://github.com/easylist/easylist/assets/91521634/482fcccb-f964-4049-bec8-c3e0bdf58c01)

#### Filter lists you're using:
Easy list + abvn list

#### Your settings:

- OS/version: 
- Browser/version: Coc Coc last version
- Adblock extension/version: 3.17

**Comment by ryanbr** [comment]
```
403
Forbidden
Access to this resource on the server is denied!
```
