### ISSUE TITLE
fileconverto.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16579]
#### List the website(s) you're having issues with:
`https://www.fileconverto.com/resize-video-for-instagram/`

#### What happens?
There's some text on the right sidebar which says "Advertisement".
![Screenshot from 2023-07-04 20-29-18](https://github.com/easylist/easylist/assets/89158249/d3f2dc69-6c47-4f14-b3cd-a5c88e1335b2)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Not worth it
