### ISSUE TITLE
techbeacon.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16578]
#### List the website(s) you're having issues with:

`https://ip-api.com/`

#### What happens?

Tracker domain loads on the site.
`ip-api.com`
Maybe `||ip-api.com^$3p`, and/or `||ip-api.com/json`.

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by davidosmarinez** [comment]
I guess this is not a tracker. check out the reports below
https://github.com/easylist/easylist/issues/2942
https://github.com/easylist/easylist/issues/2890

**Comment by Sonic5435325** [comment]
If the 2nd linked issue is correct, then I guess you're right. I'll close this.
