### ISSUE TITLE
kick.com

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#16599]
tracking likely
```
https://kick.com
```
```
||fptls3.com^
! virustotal finding, prob tracker
||fptls4.com^
```
the rest found in virustotal 
`https://www.virustotal.com/gui/ip-address/75.2.10.96/relations`

**Comment by Sonic5435325** [comment]
There's also a FingerprintJS code on the site, currently under this URL:
`https://kick.com/GnBme2AEMeEWet78/mRpHqITlCMkZevXY?apiKey=YYrqGEa5NkC1NrvsiKAT&version=3&loaderVersion=3.8.3`
