### ISSUE TITLE
Cookie notice on reuters.com

### ISSUE THREAD

**Issue by GeorgeGR21** [easylist/easylist#16598]
#### List the website(s) you're having issues with:

`https://www.reuters.com/`

#### What happens?

When you enter https://www.reuters.com/ there is a cookie notice at the bottom of the screen.

#### Screenshot(s) 

![Screenshot from 2023-07-06 15-21-31](https://github.com/easylist/easylist/assets/123986260/6452e467-5899-4977-8c18-2725b53ff266)

#### Filter lists you're using:

EasyList – Cookie Notices

#### Your settings:

- OS/version: Fedora Silverblue 38
- Browser/version: Firefox 115
- Adblock extension/version: uBlock Origin 1.50.0

**Comment by ryanbr** [comment]
Unless there is another list or extension allowing it, it should be blocked by ELC

**Comment by GeorgeGR21** [comment]
> Unless there is another list or extension allowing it, it should be blocked by ELC

It didn't work when I posted this issue, but now that I checked again it works fine.
