### ISSUE TITLE
[EasyPrivacy] the whole domain worldgravity.com is blocked (Gravity R&D recommendations)

### ISSUE THREAD

**Issue by torzsmokus** [easylist/easylist#166]
Hi EasyList!

You are currently blocking _all_ 3rd party content from Gravity R&D with the EasyPrivacy filter `||worldgravity.com^$third-party`
Many of our clients are using our recommendation systems for internal item recommendation, and your rule breaks these sites.
(Example: [ORIGO](http://www.origo.hu/itthon/20160921-granat-kiurites-tuzszereszek.html?gravity), a Hungarian news site. This URL triggers test mode: if you turn off your adblocker, you should see our recommendation box labeled _EZ ÉRDEKELNI FOGJA GRAVITY_ at the end of the page; if you turn it on, it shows the fallback recommender labeled _EZ ÉRDEKELNI FOGJA_.)

Please remove the whole domain from your filters, and find a more granular pattern to block what you consider unwanted.

One remark: while we _are_ tracking what the user does on the site, we are not sharing this data with anyone else, only the very customer that runs the site that we are tracking.

**Comment by monzta** [comment]
Removed https://github.com/easylist/easylist/commit/86bda3ec68582a9700a3383144d2195b23fad9db

**Comment by scream314** [comment]
@torzsmokus Ty for the explanation about the domain, adding it to my blacklist indeed nukes the recommendation box, this is exactly what I was looking for.
