### ISSUE TITLE
portalvirtualreality.ru [Fanboy's Annoyance List]

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#16610]
#### List the website(s) you're having issues with:

`https://portalvirtualreality.ru/kak-besplatno-poluchit-zolotye-orly-v-war-thunder/`

#### What happens?

The page is completely hidden (`###go-to-top` - Fanboy's Annoyance List)

<details>
<summary>Screenshot(s)</summary>

![go-to-top](https://github.com/easylist/easylist/assets/20126984/5f0b7573-789c-4057-9d8c-d6a82bb04894)

</details>

#### Filter lists you're using:

ABP filters, EasyList, Fanboy's Annoyance List, RU AdList

#### Your settings:

- Browser/version: Firefox 115.0
- Adblock extension/version: Adblock Plus 3.17.1

#### Possible solution

- `###go-to-top` ~> `###go-to-top:not(body)`

@ryanbr

**Comment by Daxy7** [comment]
and an ad block
```
https://portalvirtualreality.ru/en/
```
```
##.ad_block_widget
```

**Comment by dimisa-RUAdList** [comment]
@Daxy7 
This rule is already in the regional filter (RU AdList): https://github.com/easylist/ruadlist/blob/master/advblock/specific_hide.txt#L1404
