### ISSUE TITLE
lite.qwant.com

### ISSUE THREAD

**Issue by flux77** [easylist/easylist#16628]
#### List the website(s) you're having issues with:

`https://lite.qwant.com/?q=example.com`

#### What happens?

In the search results, all links are "redirection links" instead of direct links. This probably allows lite.qwant.com to know which links the user clicked on.

For example, instead of `http://example.com`, the links are of the form `https://lite.qwant.com/redirect/ZTFjMjE1NGMzN2RmYjNlYWUxN2JjODJkYjQ0MWQyNjIwMzEwOWM1MzMyNmQ4NmJhMzY1OGMzYWY3ZjBhNzg2YQ==/aHR0cCUzQSUyRiUyRnd3dy5leGFtcGxlLmNvbSUyRg==?serp_position=8&position=8&t=web&tgp=100&locale=de_de&query=example.com&ad=serp&uri=%2F%3Fq%3Dexample.com&cacheKey=z97306d484370f451c605c96e7a4496d9`.

Note that `aHR0cCUzQSUyRiUyRnd3dy5leGFtcGxlLmNvbSUyRg==` is the base64 encoding of `http%3A%2F%2Fwww.example.com%2F`.

#### Filter lists you're using:

* EasyList
* EasyPrivacy

#### Your settings:

- OS/version: Ubuntu 20.04
- Browser/version: Firefox 102.12.0esr
- Adblock extension/version: uBlock Origin 1.50.0

**Comment by DandelionSprout** [comment]
I haven't heard of EasyList or EasyPrivacy being able to skip past search results' tracker links like those, sadly.

**Comment by flux77** [comment]
@DandelionSprout 
Is EasyList or EasyPrivacy able to do something similar to what uBlock Origin did for DuckDuckGo Lite tracker links in https://github.com/uBlockOrigin/uAssets/commit/93b4832f7415912359a539007175bfb0cddfd277?
