### ISSUE TITLE
connect.mozilla.org: cookie notice

### ISSUE THREAD

**Issue by flux77** [easylist/easylist#16634]
#### List the website(s) you're having issues with:

`https://connect.mozilla.org`

#### What happens?

Cookie notice is shown.

#### Screenshot(s)

![connect.mozilla.org cookie notice](https://github.com/easylist/easylist/assets/44834611/b8275b25-a848-4341-bd65-2d57407b57dd)

#### Filter lists you're using:

* uBlock filters
* EasyList
* EasyPrivacy
* EasyList - Cookie Notices

#### Your settings:

- OS/version: Ubuntu 20.04
- Browser/version: Firefox 102.12.0esr
- Adblock extension/version: uBlock Origin 1.50.0

**Comment by Nojuuu** [comment]
There is already filter for that:
https://github.com/easylist/easylist/blob/da94894a80b1260250c6f1236102e66c0f6bda4d/easylist_cookie/easylist_cookie_general_hide.txt#L14177

Check if you have "Ignore generic cosmetic filters" enabled.

**Comment by Khrin** [comment]
Closing here.
