### ISSUE TITLE
qz.com

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#16647]
invisible placeholder sidebar but distracting lining
```
https://qz.com/elon-musk-is-suing-the-law-firm-that-helped-force-him-t-1850616483
```
```
qz.com##.eDQyzB
```

**Comment by Daxy7** [comment]
also breakage with generic filter `##.js_related-stories-inset` which is not ads but related to the article itself,

```
qz.com#@#.js_related-stories-inset
```

**Comment by ryanbr** [comment]
Links to invideo advertising.
