### ISSUE TITLE
adguard.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16646]
#### List the website(s) you're having issues with:

`https://adguard.com/kb/adguard-for-ios/overview`/

#### What happens?
"Back to top" button.
`adguard.com##.theme-back-to-top-button`
![Screenshot from 2023-07-10 01-06-14](https://github.com/easylist/easylist/assets/89158249/30c1adcf-9684-4544-973a-c9d0fd5163e0)

#### Filter lists you're using:

Fanboy's Annoyance

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by hspzfsc** [comment]
On Sale Banner also not removed.
`https://adguard.com/en/adguard-windows/overview.html`
![20230711_221505](https://github.com/easylist/easylist/assets/138294540/a0642bb8-7605-4636-8481-cf3624ccb17e)
`adguard.com##.flash-wrapper-wrap`
