### ISSUE TITLE
www.bostonglobe.com

### ISSUE THREAD

**Issue by hspzfsc** [easylist/easylist#16669]
#### List the website(s) you're having issues with:
`https://www.bostonglobe.com/`

#### What happens?
A Easylist rule break the website

#### Screenshot(s) 
![20230711_224926](https://github.com/easylist/easylist/assets/138294540/5af37454-5e93-4f2e-be92-d216af70e884)
![20230711_225223](https://github.com/easylist/easylist/assets/138294540/181da92e-687f-46ee-a073-770554220470)
![20230711_225233](https://github.com/easylist/easylist/assets/138294540/63b71a2b-a4c9-4240-9e5f-f9d09190f7f1)
![20230711_225245](https://github.com/easylist/easylist/assets/138294540/2d665cf8-6789-4e64-b0da-e0c065b9be23)

#### Filter lists you're using:
uBlock filters (all)
EasyList
Block Outsider Intrusion into LAN
EasyPrivacy
EasyList – Annoyances (all)
uBlock filters – Annoyances
[Bypass Paywalls Clean filter](https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt)
EasyList China
[ClearURLs for uBo (unofficial)](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt)
Fanboy's Anti-thirdparty Fonts

#### Your settings:
```
uBlock Origin 1.50.0:
 since: 3d.7h.52m
Chromium: 112
filterset (summary):
 network: 106177
 cosmetic: 119442
 scriptlet: 24324
 html: 0
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
  plowe-0: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 21676-13, 2h.51m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 961-0, 2h.52m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 712-8, 2h.51m
  https://secure.fanboy.co.nz/fanboy-antifonts.txt: 58-0, 2h.52m
  block-lan: 47-0, 2h.52m
  easylist-annoyances: 3887-32, 2h.52m
  easylist-chat: 129-0, 2h.52m
  easylist-newsletters: 6267-15, 2h.52m
  easylist-notifications: 2632-79, 2h.52m
  fanboy-cookiemonster: 47709-221, 2h.52m
  fanboy-social: 16098-12, 2h.52m
  ublock-annoyances: 5293-84, 2h.52m
 default:
  user-filters: 3-0, never
  easylist: 68121-63, 3m
  easyprivacy: 33422-165, 2h.52m
  ublock-badware: 7536-139, 4m
  ublock-filters: 33767-191, 4m
  ublock-privacy: 425-5, 4m
  ublock-quick-fixes: 356-84, 4m
  ublock-unbreak: 2070-35, 4m
filterset (user): [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5985 ms (selfie)
 maxAssetCacheWait: 1677 ms

```

- OS/version: Android 10
- Browser/version: Kiwi Browser 112.0.5615.137
- Adblock extension/version: uBlock Origin 1.50.0

#### Other details:
`pubmatic.com` , The website only show normally after I whitelist it.

**Comment by Sonic5435325** [comment]
After 1 refresh, the site appears normal for me on uBlock Origin default settings.

**Comment by Daxy7** [comment]
> After 1 refresh, the site appears normal for me on uBlock Origin default settings.

not for me on firefox. must be browser related i guess. 
edit: it only stopped after waiting 30secs to 1min, idk maybe 'invisible' IP security measure on website for bots/tor users…?
never happens again even after blocking everything possible and ctrl+f5[nocache] the page
https://github.com/easylist/easylist/assets/91396482/90f7f5de-2758-4828-b3a5-bf3f9a5b5fe1

**Comment by Sonic5435325** [comment]
Seems like it's caused by blueconic.net in Peter Lowe's.
Try: `@@||cdn.blueconic.net/bostonglobemedia.js$script,domain=bostonglobe.com`

**Comment by hspzfsc** [comment]
>@@||cdn.blueconic.net/bostonglobemedia.js$script,domain=bostonglobe.com

The rule work, it fixed the website.

**Comment by Daxy7** [comment]
experience some similar in `https://www.adobe.com` but that was just the janky website code.
with used no blockers/browser shields. probably all the svgs animations encrypted code/images the cpu has to unpack idk

`https://github.com/easylist/easylist/assets/91396482/6dda5ab9-6bdc-41c7-95e7-d3e2c0be67d3`
