### ISSUE TITLE
www.editpad.org

### ISSUE THREAD

**Issue by hspzfsc** [easylist/easylist#16666]
#### List the website(s) you're having issues with:
`https://www.editpad.org/`

#### What happens?
Ad leftovers not removed.

#### Screenshot(s) 
![20230711_193506](https://github.com/easylist/easylist/assets/138294540/d49ae3a9-1c4a-4059-84e6-89c86c0a2da1)

#### Filter lists you're using:
uBlock filters (all)
EasyList
Block Outsider Intrusion into LAN
EasyPrivacy
EasyList – Annoyances (all)
uBlock filters – Annoyances
[Bypass Paywalls Clean filter](https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt)
EasyList China
[ClearURLs for uBo (unofficial)](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt)
Fanboy's Anti-thirdparty Fonts

#### Your settings:
```
uBlock Origin 1.50.0:
 since: 3d.4h.37m
Chromium: 112
filterset (summary):
 network: 106215
 cosmetic: 119461
 scriptlet: 24373
 html: 0
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
  plowe-0: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 21672-13, 2h.51m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 961-0, 2h.51m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 712-8, 2h.51m
  https://secure.fanboy.co.nz/fanboy-antifonts.txt: 58-0, 2h.51m
  block-lan: 47-0, 2h.51m
  easylist-annoyances: 3887-32, 2h.51m
  easylist-chat: 129-0, 2h.51m
  easylist-newsletters: 6267-15, 2h.51m
  easylist-notifications: 2632-79, 2h.51m
  fanboy-cookiemonster: 47661-218, 2h.51m
  fanboy-social: 16098-12, 2h.51m
  ublock-annoyances: 5319-84, 2h.51m
 default:
  user-filters: 2-0, never
  easylist: 68120-63, 2h.51m
  easyprivacy: 33422-165, 2h.51m
  ublock-badware: 7536-139, 2h.51m
  ublock-filters: 33903-191, 2h.51m
  ublock-privacy: 428-5, 2h.51m
  ublock-quick-fixes: 349-84, 2h.51m
  ublock-unbreak: 2070-35, 2h.51m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5653 ms
 maxAssetCacheWait: 41 ms

```

- OS/version: Android 10
- Browser/version: Kiwi Browser 112.0.5615.137
- Adblock extension/version: uBlock Origin 1.50.0

#### Other details:
`www.editpad.org##.edsec.leftbar`
`www.editpad.org##div.edsec.sidebarinfo > p`

**Comment by Sonic5435325** [comment]
Probably `editpad.org##.edsec` like in AdGuard - Ads.
