### ISSUE TITLE
ec.ltn.com.tw

### ISSUE THREAD

**Issue by hspzfsc** [easylist/easylist#16677]
#### List the website(s) you're having issues with:
`https://ec.ltn.com.tw/article/breakingnews/4357973`

#### What happens?
Annoyance not removed, need to scroll down to see it.

#### Screenshot(s) 
![20230712_112231](https://github.com/easylist/easylist/assets/138294540/185f2f6e-0d2e-4580-889a-f6aed31ba025)

#### Filter lists you're using:
uBlock filters 
- uBlock filters – Ads
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Quick fixes
- uBlock filters – Unbreak

EasyList
Block Outsider Intrusion into LAN
EasyPrivacy

EasyList – Annoyances
- EasyList – Chat Widgets
- EasyList – Cookie Notices
- EasyList – Newsletter Notices
- EasyList – Notifications
- EasyList – Other Annoyances
- EasyList – Social Widgets

uBlock filters – Annoyances
[Bypass Paywalls Clean filter](https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt)
EasyList China
[ClearURLs for uBo (unofficial)](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt)
Fanboy's Anti-thirdparty Fonts

#### Your settings:
```
uBlock Origin 1.50.0:
 since: 3d.20h.27m
Chromium: 112
filterset (summary):
 network: 106212
 cosmetic: 119416
 scriptlet: 24342
 html: 0
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
  plowe-0: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 21687-13, 15m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 961-0, 15m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 712-8, 15m
  https://secure.fanboy.co.nz/fanboy-antifonts.txt: 58-0, 15m
  block-lan: 47-0, 16m
  easylist-annoyances: 3887-32, 15m
  easylist-chat: 129-0, 15m
  easylist-newsletters: 6267-15, 15m
  easylist-notifications: 2632-79, 15m
  fanboy-cookiemonster: 47709-221, 15m
  fanboy-social: 16099-12, 15m
  ublock-annoyances: 5294-84, 15m
 default:
  user-filters: 2-0, never
  easylist: 68147-63, 15m
  easyprivacy: 33424-165, 15m
  ublock-badware: 7539-139, 15m
  ublock-filters: 33754-193, 15m
  ublock-privacy: 425-5, 15m
  ublock-quick-fixes: 363-91, 15m
  ublock-unbreak: 2070-35, 15m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1742 ms (selfie)
 maxAssetCacheWait: 1148 ms

```

- OS/version: Android 10
- Browser/version: Kiwi Browser 112.0.5615.137
- Adblock extension/version: uBlock Origin 1.50.0

**Comment by Sonic5435325** [comment]
Report to the appropriate regional list: https://github.com/easylist/easylistchina
