### ISSUE TITLE
tw.news.yahoo.com

### ISSUE THREAD

**Issue by hspzfsc** [easylist/easylist#16681]
#### List the website(s) you're having issues with:
`https://tw.news.yahoo.com/%E5%98%89%E7%BE%A9%E4%BB%A5%E5%8C%9712%E7%B8%A3%E5%B8%82%E5%A4%A7%E9%9B%A8%E7%89%B9%E5%A0%B1-%E6%A1%83%E5%9C%92%E6%96%B0%E7%AB%B9%E6%B3%A8%E6%84%8F%E5%A4%A7%E9%9B%B7%E9%9B%A8-061557095.html`

 

#### What happens? 
Annoyances not removed.

 

#### Screenshot(s) 
![20230712_144254](https://github.com/easylist/easylist/assets/138294540/322a8e3f-c38f-4d1e-909f-a018b7a20f97)
![20230712_144315](https://github.com/easylist/easylist/assets/138294540/af56b618-7a6d-469f-b41d-cc7324b897e9)
![20230712_144304](https://github.com/easylist/easylist/assets/138294540/cea490f6-2181-4903-ba47-02188f550e7f)

 

#### Filter lists you're using:
uBlock filters 
- uBlock filters – Ads
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Quick fixes
- uBlock filters – Unbreak 

EasyList
Block Outsider Intrusion into LAN
EasyPrivacy 

EasyList – Annoyances
- EasyList – Chat Widgets
- EasyList – Cookie Notices
- EasyList – Newsletter Notices
- EasyList – Notifications
- EasyList – Other Annoyances
- EasyList – Social Widgets 

uBlock filters – Annoyances
[Bypass Paywalls Clean filter](https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt)
EasyList China
[ClearURLs for uBo (unofficial)](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt)
Fanboy's Anti-thirdparty Fonts

 

#### Your settings:
```yaml
uBlock Origin 1.50.0:
 since: 2h.59m
Chromium: 112
filterset (summary):
 network: 106209
 cosmetic: 119420
 scriptlet: 24343
 html: 0
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
  plowe-0: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 21687-13, 2h.59m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 961-0, 2h.59m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 712-8, 2h.59m
  https://secure.fanboy.co.nz/fanboy-antifonts.txt: 58-0, 2h.59m
  block-lan: 47-0, 2h.59m
  easylist-annoyances: 3889-32, 2h.59m
  easylist-chat: 129-0, 2h.59m
  easylist-newsletters: 6268-15, 2h.59m
  easylist-notifications: 2632-79, 2h.59m
  fanboy-cookiemonster: 47711-221, 2h.59m
  fanboy-social: 16099-12, 2h.59m
  ublock-annoyances: 5294-84, 2h.59m
 default:
  user-filters: 2-0, never
  easylist: 68147-63, 2h.59m
  easyprivacy: 33424-165, 2h.59m
  ublock-badware: 7536-139, 2h.58m
  ublock-filters: 33754-193, 2h.58m
  ublock-privacy: 425-5, 2h.58m
  ublock-quick-fixes: 363-91, 2h.58m
  ublock-unbreak: 2070-35, 2h.58m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3563 ms (selfie)
 maxAssetCacheWait: 1599 ms
```
 

- OS/version: Android 10
- Browser/version: Kiwi Browser 112.0.5615.137
- Adblock extension/version: uBlock Origin 1.50.0 

#### Other details: 
`news.yahoo.com###module-appPromoBanner`
`news.yahoo.com###postArticle`
`news.yahoo.com###community-bar` The first news already have a 'view comment' button, so it don't need the comment bar, but other news (scroll down to see them) don't. This rule won't block their comment bars because it have different element names.
![20230712_144329](https://github.com/easylist/easylist/assets/138294540/23dfb6a4-01e2-4458-80fa-b441494ca2ce)

**Comment by ryanbr** [comment]
I think these should be addressed in a regional list.
