### ISSUE TITLE
techwiser.com uses gifs.com ads, not blocked

### ISSUE THREAD

**Issue by ripdog** [easylist/easylist#1669]
### List the website(s) you're having issues:

`https://techwiser.com/5-apps-to-remote-control-android-phone-from-pc-usb-and-wifi/`

### What happens?

"Ads by gifs.com" appears in above article.

### List Subscriptions you're using:

All uBlock lists, EasyList, Malware lists, Fanboy lists.

### Your settings
No other adblockers, none of the addons listed in the comment. I did have HTTPS everywhere, but disabled and no change.

- OS/version: Win10 latest.
- Browser/version: Firefox Nightly 20180803220259.
- Adblock Extension/version: uBlock Origin 1.16.14

### Other details:

https://screenshots.firefox.com/Owsd6Z3AapfeBuGz/techwiser.com

**Comment by ryanbr** [comment]
Didn't see it, but this may help.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5b541a78627bce1b3007963dfea7cf86e39ad5da

**Comment by ripdog** [comment]
Thanks for that, @ryanbr . That rule has blocked the image on the ad, but the text remains.

![image](https://user-images.githubusercontent.com/174944/43989277-0d8902ee-9d9b-11e8-9bda-62b0f087d8ea.png)

Hmm, after refreshing, the ad no longer appears. Perhaps it has a cooldown before it appears again?
