### ISSUE TITLE
[NSFW] dictionary.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16698]
#### List the website(s) you're having issues with:
`
https://www.dictionary.com/e/slang/slut-shaming/`

#### What happens?

A CSS file on the site, which causes it's own elements to load, associated with the tracking service Parsely.
`dictionary.com/e/wp-content/plugins/wp-parsely/wp-parsely.css`

Also, a newsletter/social media button box...
![Screenshot from 2023-08-31 15-07-51](https://github.com/easylist/easylist/assets/89158249/38d4091c-8e76-4d7a-aa0a-225702e8d126)

#### Filter lists you're using:

EasyList/EasyPrivacy
Fanboy's Newsletter/Social

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by yokoffing** [comment]
There's also a social icon not block (facebook)
`##.fa-facebook`

**Comment by Sonic5435325** [comment]
`##.atw-socials` would probably be a better filter for that.

**Comment by Daxy7** [comment]
1897 bytes css on page load when we got [10-25](https://github.com/easylist/easylist/assets/91396482/855d47cc-c138-4b54-a909-e68542f87b4f) mbps and [1tb data cap](https://github.com/easylist/easylist/assets/91396482/347707e2-f42a-40f6-a64f-43506fb575a8) on regular wifi nowadays. meh
