### ISSUE TITLE
https://html5.gamedistribution.com/d2b4c36f20d846b0b227da8eff9610ea/ : breakage

### ISSUE THREAD

**Issue by punisher018** [easylist/easylist#16734]
https://html5.gamedistribution.com/d2b4c36f20d846b0b227da8eff9610ea/

when the game is loading it's giving error.
Because of that filter 
_advertisement_$from=~media.ccc.de

URL
https://html5.gamedistribution.com/rvvASMiM/d2b4c36f20d846b0b227da8eff9610ea/res/map_1/scene_v2/Assets/models/barrier2-SM_Prop_**Advertisement**_Pillar_01.lm

**Comment by Yuki2718** [comment]
The rule is 5-years old and also is a bait. Will remove.
