### ISSUE TITLE
Externally viewing videos from a PeerTube instance on .space does not work

### ISSUE THREAD

**Issue by JacksonChen666** [easylist/easylist#16745]
#### List the website(s) you're having issues with:

`https://spacepub.space/w/pjgvVL74xtFwqnaKuoCXZj` but when viewed on an external PeerTube instance (e.g. `https://videos.jacksonchen666.com/w/pjgvVL74xtFwqnaKuoCXZj`)

#### What happens?

When a PeerTube video from a .space domain is viewed on an external PeerTube instance, it won't work. The video simply does not play. It will load forever.

#### Screenshot(s) 

<img width="1920" alt="PeerTube video is loading, uBlock Origin Logger shows details on a request." src="https://github.com/easylist/easylist/assets/50755746/066c60d6-926a-4093-8862-82a56d48a5c6">

#### Filter lists you're using:

- uBlock filters
- uBlock filters – Ads
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Quick fixes
- uBlock filters – Unbreak
- **EasyList**
- ➗ Actually Legitimate URL Shortener Tool
- AdGuard URL Tracking Protection
- EasyPrivacy
- Malware protection, security
- Online Malicious URL Blocklist
- Phishing URL Blocklist
- Peter Lowe’s Ad and tracking server list

#### Your settings:

- OS/version: macOS 13.4.1
- Browser/version: LibreWolf 115.0.1-1
- Adblock extension/version: uBlock Origin (default settings) 1.50.0

#### Other details:

```
/^https?:\/\/[0-9a-z]{5,}\.(digital|website|life|guru|space)\/[a-z0-9]{6,}\//$script,third-party,xmlhttprequest,domain=~127.0.0.1|~bitrix24.life|~ccc.ac|~localhost|~mempool.space|~scribble.ninja|~scribble.website|~traineast.co.uk
```

That seems to be the one responsible for breaking things.

**Comment by Daxy7** [comment]
it's suppose to filter 3p script xml requests as advertising/tracking, why can't we do it on a site by site basis?

instead of allowlisting individual websites likely years on end, depending on how many with popularity these domain tlds are

**Comment by Daxy7** [comment]
why you confused? 

it is what this maintainers do, it's tiresome. probably wasteful this filter syntax, breakages with digital/website/life/guru/and/space...

**Comment by Daxy7** [comment]
it's the filter you're looking at it a syntax, ever heard of it? you should look it up, maybe make it better, more optimized somehow

**Comment by Daxy7** [comment]
anywho, here's the appropriate filter to apply if they wanna keep it like this: 
```
/^https?:\/\/[0-9a-z]{5,}\.(digital|website|life|guru|space)\/[a-z0-9]{6,}\//$script,third-party,xmlhttprequest,domain=~127.0.0.1|~bitrix24.life|~ccc.ac|~localhost|~mempool.space|~scribble.ninja|~scribble.website|~traineast.co.uk|spacepub.space
```
try it out, test it for me, i'll test your knowledge for free.

**Comment by Nojuuu** [comment]
Same filter also causes issues on Lemmy

e.g.
`https://lemmy.world/c/startrek@startrek.website`
`https://lemm.ee/c/startrek@startrek.website`

![image](https://github.com/easylist/easylist/assets/84513173/dfcd38c1-ffdc-4dc3-8815-2be0ef1e7143)
![image](https://github.com/easylist/easylist/assets/84513173/1be35b64-f69a-4a13-9fce-d96eafe80ff2)

**Comment by Daxy7** [comment]
just add a +1 right here like this:

look at the end of the line of the filters, it has exceptions, you're excluding a website from being filtered, no `https`, no `www`,
i'll show you:

`|lemmy.world`

DIY, do it yourself. you're welcome.

**Comment by Daxy7** [comment]
post message: they rearrange it alphabetically, so if you wanna submit it as a pull request, gotta make it in that order, ok?

**Comment by Daxy7** [comment]
![image](https://github.com/easylist/easylist/assets/91396482/ff8fbf54-6b40-47fd-98e9-f89078894cfd)
here's the short description of syntax if you're too lazy to learn more

**Comment by Daxy7** [comment]
nice troll. ain't fooling me, tool.
