### ISSUE TITLE
newyorker.com 

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#16749]
4, no 7 newsletter notices (specific, clearer filter)

```
https://www.newyorker.com/culture
```

```
newyorker.com##.Failsafe__tny-failsafe___3NxXj
```
https://github.com/easylist/easylist/assets/91396482/3a2f59c4-a1ed-4641-97b4-915d32713292

**Comment by Daxy7** [comment]
but we needa exclude this one: main 1 that at least looks good and not outstanding

```
##.Navigation__subscribe___3OCs_
```

**Comment by ryanbr** [comment]
Not targeting the paywall..

**Comment by Daxy7** [comment]
not a paywall when the whole page is visible it's category culture page and nothing is hidden/removed
just seems spammed everywhere on there
