### ISSUE TITLE
spectator.co.uk

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#16761]
nuisance sub animation banner loop
```
https://www.spectator.co.uk/article/youtube-and-the-final-state-of-total-kippleization/
```

```
spectator.co.uk##.subscription-banner
```

https://github.com/easylist/easylist/assets/91396482/d307a663-ee19-4f3c-88c0-2f9967b39513

**Comment by ryanbr** [comment]
Not touching paywall subscriptions.

**Comment by Daxy7** [comment]
these do the same thing, just without svg playing: UNLOCK ACCESS button
![image](https://github.com/easylist/easylist/assets/91396482/9b3f01f4-f336-42cb-b8cb-2e1506d104a5)

**Comment by Daxy7** [comment]
![image](https://github.com/easylist/easylist/assets/91396482/16511caf-176c-4370-aff4-e1206cd7c1da)
if this is considered paywall then aight
