### ISSUE TITLE
9to5linux (Fanboy Social)

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#16769]
#### List the website(s) you're having issues with:
`https://9to5linux.com/firefox-116-beta-brings-quick-actions-in-address-bar-improves-wayland-support`

#### What happens?
Mastodon social icon

#### Screenshot(s) 
![Screenshot 2023-07-19 at 4 49 43 PM](https://github.com/easylist/easylist/assets/11689349/3d1815a9-19e7-4d90-917b-39f7d50caaf3)

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by Daxy7** [comment]
for generic html div
```
##.bm-share-mastodon
```

**Comment by Sonic5435325** [comment]
`9to5linux.com##.bm-social-top`
