### ISSUE TITLE
mensjournal.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#16770]
#### List the website(s) you're having issues with:
`https://www.mensjournal.com/entertainment/tom-cruise-mission-impossible-dead-reckoning-part-one-stunt`

#### What happens?
cookie notice + ad in right sidebar

#### Filter lists you're using:
uBlock Origin default + road-block lite + EasyList Cookie

---

for the ad:

```
mensjournal.com##.ssg-scm
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/93b44c0cdb9ff2af3ed21846c012ded417cda30e
