### ISSUE TITLE
afront.io

### ISSUE THREAD

**Issue by denisarenko** [easylist/easylist#16795]
**List the website(s) you're having issues with:**
https://afront.io/

**What happens?**
Whole website blocked. Is there any reason why website blocked? and is it possible to remove afront.io from blocked list?

Screenshot(s)
<img width="1060" alt src="https://github.com/easylist/easylist/assets/5065593/66360a59-57a4-46a9-8593-bacd345c53cf">

**Filter lists you're using:**
EasyList
EasyPrivacy

**Your settings:**
OS/version: MacOS Ventura 13.4.1
Browser/version: Chrome 114.0
Adblock extension/version: ADBlock 5.8.1

**Line in commit**
https://github.com/easylist/easylist/blame/edd673b969a047ffa7d991da8d9d138b3cff4613/easylist/easylist_adservers_popup.txt#L225

**Comment by dimisa-RUAdList** [comment]
https://forums.lanik.us/viewtopic.php?t=48205-afront-io
