### ISSUE TITLE
False positive on `gumtree.com.au`

### ISSUE THREAD

**Issue by eporubin** [easylist/easylist#16823]
#### List the website(s) you're having issues with:
`www.gumtree.com.au`

#### What happens?
The filter `##[data-ad-name]` from  `easylist_general_hide.txt` hides the DELETE button on the page as it does match wrongly the case, could you please remove the filter? or should I submit an exception for this domain only?

#### Screenshot(s) 
![image](https://github.com/easylist/easylist/assets/33602691/4bc660fa-aa85-4d03-97aa-8ae938e0a85c)

#### Filter lists you're using:
ABP Filters
Easy List

#### Your settings:

- OS/version: macOS
- Browser/version:  Google Chrome
- Adblock extension/version: AdBlock Plus

#### Other details:
The issue occurs because once you are logged in you can sell your items (which are called "ads").

**Comment by Sonic5435325** [comment]
Or we could just do a generic specific allow on the site.
