### ISSUE TITLE
"googletagmanager"

### ISSUE THREAD

**Issue by HoangHaiDang02** [easylist/easylist#16820]
#### What happens?
this is problem of me pls help me delete rule

#### Filter lists you're using:
easyprivacy

#### Your settings:

- OS/version: window
- Browser/version: coc coc last version
- Adblock extension/version: 3.18

**Comment by HoangHaiDang02** [comment]
it commonly used to identify users. It will affect us. pls help us

**Comment by Sonic5435325** [comment]
So?
The entire point of EasyPrivacy is, you know, blocking requests that are mainly just meant for tracking. Your issue is invalid. A tracker won't be allowed just because someone made an issue and said "it affects us!!".

**Comment by ryanbr** [comment]
Closing, Its a tracker. So "used to identify users." I expect this.
