### ISSUE TITLE
weatherwx.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#16834]
#### List the website(s) you're having issues with:

`https://www.weatherwx.com/`
#### What happens?

Back to top button:
`weatherwx.com###back-to-top`

#### Screenshot(s) 

![Screenshot from 2023-07-24 21-25-14](https://github.com/easylist/easylist/assets/89158249/26dfbe52-4ce1-43d4-9f7e-3a58fe73fb58)

#### Filter lists you're using:

Fanboy's Annoyance

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/pull/17005

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/ea55d6e5daf5270adc4d588312dfc76e60f66607

**Comment by Sonic5435325** [comment]
I'll close this.
