### ISSUE TITLE
HarpersBazaar.com - Required user action blocked (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#1683]
### Affected site:
`https://www.harpersbazaar.com/`

### Issue:
Required user action (cookie consent) is blocked, preventing some elements from being displayed.

### Example:
`https://www.harpersbazaar.com/celebrity/latest/a22664885/kendall-jenner-topless-magazine-cover/`

Scroll down a bit..
None of the Instagram images will be displayed, until the cookie warning has been accepted!

### Problem filter:
EasyPrivacy

### Problem rule:
`||evidon.com/geo/`
(Again!)

### Blocked script:
`https://c.evidon.com/geo/country.js`

### Possible fix:
`@@||evidon.com/geo/$domain=harpersbazaar.com`

But the rule should probably be removed all together, since it causes way too many problems.
In some cases, Evidon's GDPR warnings are highly location-dependent, which makes the issues extremely difficult for filter authors to reproduce.
One example is this script, which is used by `PopSugar.co.uk`:
`https://c.evidon.com/sitenotice/4134/popsugar/settings.js`
The numbers at the end of each line appears to be country codes, and depending on your location, users can be redirected to different scripts, which in turn serves completely different types of cookie warnings.
It doesn't only serve one type of warning for European countries, and one type for non-European countries, but it also differentiates between various European countries.
More info here:
https://github.com/ryanbr/fanboy-adblock/issues/512/ 
And here:
https://github.com/AdguardTeam/AdguardFilters/issues/20596/

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.4 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/bf047abd7a5d4564fecb0963d64f2efee38c3a88
