### ISSUE TITLE
EasyPrivacy. `||gateway.reddit.com^` and async loading on reddit 

### ISSUE THREAD

**Issue by 3F** [easylist/easylist#1684]
latest changes f80e516b61d50 destroys async loading on reddit:

> Something went wrong while loading.
> [Try again]

![2018-08-10_19-54-16_firefox](https://user-images.githubusercontent.com/3246589/43971203-e317573a-9cd8-11e8-886b-25bb523a1f6f.png)

Failed when `||gateway.reddit.com^` is added. 

**EasyPrivacy** list (https://easylist-downloads.adblockplus.org/easyprivacy.txt)
/Firefox 61.0.2 x64

**Comment by ryanbr** [comment]
wheres you site you're testing from?

**Comment by alienth** [comment]
Was able to reproduce this myself. `gateway.reddit.com` is a generic API endpoint, so I'm pretty sure blocking all of it was done in error.

Here's an example request which is used for async loading, that does get blocked by this rule:

```https://gateway.reddit.com/desktopapi/v1/frontpage?rtj=debug&redditWebClient=web2x&app=web2x-client-production&sort=hot&layout=card&useMockData=false&recentPostIds=&allow_over18=&include=```

**Comment by ryanbr** [comment]
i see no reason to remove this block, I've tested on the main site. and given the constant changing of tracking domains on reddit.com I don't trust non-testable complaints.

**Comment by Katharsas** [comment]
@ryanbr 
Please reopen this. This can be reproduced by not using the old design (which it allows you to go back to), and it is a problem on pretty much any subreddit, for example:
https://www.reddit.com/r/Planetside/

Scroll down. Content does not load in dynamically as it should, instead error is displayed.

**Comment by ryanbr** [comment]
I've adjusted the filter, to all the other users. If you have an issue with a filter, have a testable example of what should/shouldn't happen is needed. Its not helpful when people report issues but supply enough info.
