### ISSUE TITLE
FoxNews.com - Blocked videos (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#1685]
### Affected site:
`http://www.foxnews.com/`

### Issue:
Videos are blocked.

### Example:
`http://insider.foxnews.com/2018/08/10/chicago-pastor-rips-emanuel-calls-trumps-help-gun-violence-send-guard-troops/`

### Screenshot:

![filterissue-foxnews2](https://user-images.githubusercontent.com/9382674/43985225-3fc7a270-9cf5-11e8-8402-9cf66421decc.jpg)

### Problem filter:
EasyPrivacy

### Problem rule:
`/id?d_visid_ver=`

### Possible fix:
`@@/id?d_visid_ver=$domain=foxnews.com`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.4 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/38499353cfb2150bf74b4c650079eba9eed2783a

**Comment by THEtomaso** [comment]
Apparently, it's also being blocked by this rule, In EasyPrivacy:
`||demdex.net^$third-party`
..so this exception is needed too:
`@@||demdex.net^$third-party,domain=foxnews.com`

**Comment by Khrin** [comment]
Video is now working correctly for me.

**Comment by THEtomaso** [comment]
> Video is now working correctly for me.

Perhaps you're using Adguard's filters, which already contains the necessary exceptions?

**Comment by Khrin** [comment]
> Perhaps you're using Adguard's filters, which already contains the necessary exception?+

Of course I don't.

**Comment by THEtomaso** [comment]
> `@@||dpm.demdex.net/id?$xmlhttprequest,domain=foxnews.com` (# 2d7382e)

The "xmlhttprequest" exception method doesn't quite seem to fix it..
The videos are still blocked by the `||demdex.net^$third-party` rule.
However, now I'm able to make them play by refreshing the page once.
