### ISSUE TITLE
recettesetcabas.com Hiding cookie consent prevents scrolling (Easylist Cookie)

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#16850]
#### List the website(s) you're having issues with:
`https://www.recettesetcabas.com/`

#### What happens?
`###cookies_content` breaks page due to hiding cookie consent.

#### Screenshot(s) 
![Screenshot 2023-07-25 at 12 29 58 PM](https://github.com/easylist/easylist/assets/11689349/7c905916-4537-4649-8625-e4a82b1d1636)

#### Filter lists you're using:
Fanboy Annoyance or Easylist Cookie

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a61a59d5733f1127fbfeb2f0e7c28aef405f6379
