### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by OrderedShrub** [easylist/easylist#1687]
### List the website(s) you're having issues:

```
reddit.com
https://gateway.reddit.com/desktopapi/v1/frontpage?rtj=debug&redditWebClient=web2x&app=web2x-client-production&sort=best&layout=classic&useMockData=false&recentPostIds=t3_96eloo%2Ct3_93tx2k%2Ct3_96fuxm&allow_over18=&include=
```

### What happens?

reddit's redesign currently doesn't work properly when EasyPrivacy is enabled. It uses async loading through the `gateway.reddit.com` domain, which is blocked by EasyPrivacy. 

uBlock has fixed this in their 'Unbreak' list. As such, you won't be able to reproduce unless you disablew `Unbreak`: https://github.com/uBlockOrigin/uAssets/commit/0390479ddee79154b38801223b8dc788c169f5f0#diff-597a9408879bda0da942803b82285184

### List Subscriptions you're using:

EasyPrivacy

![gifrecord_2018-08-11_113647](https://user-images.githubusercontent.com/42303874/43995532-70a57fc8-9d5b-11e8-879c-0c9e4090288e.gif)

**Comment by ryanbr** [comment]
fixed

**Comment by 3F** [comment]
> i see no reason to remove this block ...
> +locked as resolved and limited conversation to collaborators

v

d128de0dd2918d1d4c3fbfc209bde8c2c985ae91

v

```
||gateway.reddit.com|
```

nice solution :)) something like reddit or nothing.

I will never trust this repo anymore.

**Comment by ryanbr** [comment]
If you wish to pretend this fault still exists, thats your problem. reddit was fixed, so this issue report is redundant.  What else is there to discuss? Nothing.

**Comment by 3F** [comment]
You're right. An empty rule/string fully fixes problem. This was just a note about trust to the easylist between specific issues, their methods and specific commits. 

And **you're right again,** it's only my problems. I will try to solve them myself ! Thanks,
