### ISSUE TITLE
metager.org, metager.de: ads

### ISSUE THREAD

**Issue by flux77** [easylist/easylist#16875]
#### List the website(s) you're having issues with:

`https://metager.org/meta/meta.ger3?eingabe=java%20programming%20books`

#### What happens?

Ads are still shown despite #16856.

#### Screenshot(s) 
* The first and second ads have URL of the form `https://metager.org/r/metager/...`
* The third ad has URL `https://metager.org/spende`

![metager org](https://github.com/easylist/easylist/assets/44834611/0678dc05-5845-4bdf-9832-fe4cbd7c1f9e)

#### Filter lists you're using:
* EasyList

#### Your settings:

- OS/version: Ubuntu 20.04
- Browser/version: Firefox 102.13.0esr
- Adblock extension/version: uBlock Origin 1.51.0

#### Other details:

Related: https://github.com/uBlockOrigin/uAssets/issues/19193

Suggested filters:

```
metager.org,metager.de##.result:has(.result-open-key)
metager.org,metager.de##.result:has(img[alt="Mark"])

metager.org##.result:has(a[href="https://metager.org/keys"])
metager.org##.result:has(a[href="https://metager.org/partnershops"])
metager.org##.result:has(a:has-text(REMOVE ADVERTISING))

metager.de##.result:has(a[href="https://metager.de/keys"])
metager.de##.result:has(a[href="https://metager.de/partnershops"])
metager.de##.result:has(a:has-text(WERBUNG ENTFERNEN))
```

**Comment by flux77** [comment]
The issue appears to be intermittent. Try to make a few more searches in a new tab. Sometimes the URL of the advertisement will be either of these:

* `https://metager.org/r/metager/...`
* `https://metager.org/spende`

EasyList does not seem to have filters to deal with the URLs above.

**Comment by dportvine** [comment]
>Try to make a few more searches in a new tab.

<details>
<summary>Screen</summary>

![2023-07-30_085932](https://github.com/easylist/easylist/assets/111344219/f8271940-8a7f-4924-ab28-42cb431a083f)
</details>

**Comment by Khrin** [comment]
> EasyList does not seem to have filters to deal with the URLs above.

I can assure you that our filters are working correctly and are blocking also the links you have mentioned here. I can only suggest again that you should check that your filter lists are correctly updated.
