### ISSUE TITLE
levi.com: Missing OneTrust links

### ISSUE THREAD

**Issue by philipp-classen** [easylist/easylist#16873]
#### List the website(s) you're having issues with:

```
https://www.levi.com/
```

#### What happens?

Two links (on the buttom) are hidden:
* "Do Not Sell Or Share My Personal Information"
* "Privacy Policy" (depending on the setup, but I think sometimes `###teconsent` hides it)

#### Screenshot(s) 

![256543932-a73c1577-e0cf-4802-8603-6bebf19e89e9](https://github.com/easylist/easylist/assets/1616509/a4e6c667-0d50-4a5c-afe7-200982448dcc)

#### Filter lists you're using:

EasyList – Cookie Notices

#### Your settings:

In Ghostery, we added the following exclusion rules now (see https://github.com/ghostery/broken-page-reports/issues/336):

```
#@##ot-sdk-btn:not(button)
#@#.ot-sdk-show-settings
#@##teconsent
```

But it should be reproducible with uBlock Origin.

#### Other details:

From user reports, the missing links may affect more pages, but unfortunately I do not have concrete example. levi.com is currently the only test page that I'm aware of.

**Comment by ryanbr** [comment]
Not really worth it, functionality of site isn't affected here
