### ISSUE TITLE
mandsopticians.com (EasyPrivacy)

### ISSUE THREAD

**Issue by delkant03** [easylist/easylist#16884]
### URL address of the web page

`https://www.gadecosmetics.com/collections/for-men`

### Category

privacy

### Description

Privacy issue

Please block the requests by adding it to the Easyprivacy filter. `https://app.avada.io/scripttag/tracking/avada-track.min.js?`

Thank you

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 100151
 cosmetic: 44144
 scriptlet: 18126
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7003-0, 8m
  easylist: 69075-15, 7m
  easyprivacy: 33350-71, 7m
  plowe-0: 3717-1072, 7m
  ublock-badware: 7586-142, 7m
  ublock-filters: 34155-233, 7m
  ublock-privacy: 445-7, 7m
  ublock-quick-fixes: 282-88, 7m
  ublock-unbreak: 2102-36, 7m
  urlhaus-1: 6521-0, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 575 ms
 maxAssetCacheWait: 228 ms
popupPanel:
 blocked: 5
 network:
  gadecosmetics.com: 1
  google.com: 2
  googleoptimize.com: 1
  googletagmanager.com: 1
```
</details>

https://github.com/uBlockOrigin/uAssets/issues/19203

**Comment by ryanbr** [comment]
not seen
