### ISSUE TITLE
https://www.check24.de (Easylist Cookie)

### ISSUE THREAD

**Issue by SamsonNosmas** [easylist/easylist#16893]
#### List the website(s) you're having issues with:

https://www.check24.de/

#### What happens?

Cookie warning is displayed

#### Filter lists you're using:

Easylist Cookie

#### Your settings:

- OS/version: 
- Browser/version: 
- Adblock extension/version:

**Comment by ryanbr** [comment]
Should be fixed? @SamsonNosmas
