### ISSUE TITLE
wpnrtnmrewunrtok.xyz

### ISSUE THREAD

**Issue by Eow2022yia** [easylist/easylist#16891]
Video streams at camwhores.tv are being blocked:

This is due to the following domains being blocked:

wpnrtnmrewunrtok.xyz
camvideo.wpnrtnmrewunrtok.xyz
camvideo12.wpnrtnmrewunrtok.xyz

Steps to reproduce:
Tried to load videos with wpnrtnmrewunrtok.xyz and sub-domains whitelisted, videos load successfully.

This is a false positive as if you do some deeper analysis you will see some videos do require this domain to be whitelisted,
There also could be a potential possibility that this issue could also affect any other sites that utilizes that video providers playback.

Thank you.

**Comment by Khrin** [comment]
This seems to have been resolved already.
