### ISSUE TITLE
http://www.baltimoresun.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#169]
`http://www.baltimoresun.com/`

unblocked ads.

**Comment by monzta** [comment]
Done https://github.com/easylist/easylist/commit/3970a74ec41ceb6972c13b23ee34e12682b78c6e

**Comment by terrorist96** [comment]
@monzta Still see ads on Chrome.

**Comment by terrorist96** [comment]
@monzta

**Comment by mapx-** [comment]
try
```
@@||baltimoresun.com^$generichide
@@|https:$script,other,domain=baltimoresun.com
@@|https:*=|$image,domain=baltimoresun.com
```

**Comment by terrorist96** [comment]
@mapx- Doesn't work for me.

**Comment by mapx-** [comment]
it's working for me, did you disable all other blocking extensions ?

**Comment by terrorist96** [comment]
Yep
![image](https://cloud.githubusercontent.com/assets/12802056/23318723/8d48a208-faa1-11e6-9d12-865b0caabfe7.png)
