### ISSUE TITLE
aeon.co Social icons

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#16916]
#### List the website(s) you're having issues with:
`https://aeon.co/essays/privacy-matters-because-it-empowers-us-all`

#### What happens?
Social icons at the top of page

![aeon](https://github.com/easylist/easylist/assets/11689349/ae98fba9-ef9b-483d-95e4-49ad99f2e075)

And bottom-left side of article.

![aeon2](https://github.com/easylist/easylist/assets/11689349/83b6cb52-3d05-48b8-8789-bcb91367ffc4)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/227d8384a1dbea6d4aa62b27b2b5c74cf90a36d4
