### ISSUE TITLE
canva.com: cookies

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#16921]
![image](https://github.com/easylist/easylist/assets/19517680/3ea29410-5d77-45fe-a1c7-624652e60be9)

https://www.canva.com/download/windows/

**Comment by apricotbucket28** [comment]
@ryanbr not sure if I should be reporting this here (apologies if it's the wrong place), but the same cookie banner is back. Looks like the id is randomly generated when they build the site.
