### ISSUE TITLE
thestar.com.my: breakage

### ISSUE THREAD

**Issue by pubct** [easylist/easylist#16939]
#### List the website(s) you're having issues with:

`https://www.thestar.com.my/news/world/2023/08/02/torture-sexual-violence-commonly-used-by-russian-forces-in-ukraine-say-experts`

#### What happens?

Scroll down a little bit, the timestamp to the left of the article will disappear.
The timestamp shouldn't be block-worthy I think?

#### Filter lists you're using:

uBO defaults + EasyList Other Annoyances

- OS/version: Windows 10
- Browser/version: Chrome 115.0.5790.111
- Adblock extension/version: uBO 1.51.0

#### Other details:

Very likely due to EasyList Other Annoyances.
I opened the link in incognito with uBO defaults and then with uBO defaults + EasyList Other Annoyances.
The timestamp doesn't disappear when on uBO defaults only.

Thank you.

**Comment by ryanbr** [comment]
Seems fine here, If you can nail down the filter list then report on the filter causing it.

**Comment by pubct** [comment]
By my testing, **EasyList - Other Annoyances** is still the culprit.
