### ISSUE TITLE
sheglam.com — `/ba_tracking.js`

### ISSUE THREAD

**Issue by davidosmarinez** [easylist/easylist#16948]
`https://www.sheglam.com/collections/lips/products/sunday-picnic-layer-cake-lip-oil-set-sb2202255184955155`

#### What happens?

this is a pretty common script.

`/ba_tracking.js`

#### Screenshot(s) 

-

#### Filter lists you're using:

uBlock Origin default settings and filters

#### Your settings:

- OS/version: Windows 10
- Browser/version: 
- Adblock extension/version: uBlock Origin 1.51.0

#### Other details:

`https://publicwww.com/websites/%22%2Fba_tracking.js%22/`

**Comment by Sonic5435325** [comment]
Maybe also `_tracking.js`, if that isn't too aggressive.
