### ISSUE TITLE
genius.com

### ISSUE THREAD

**Issue by alastortenebris** [easylist/easylist#16945]
#### List the website(s) you're having issues with:

`https://genius.com/Archspire-involuntary-doppelganger-lyrics`
#### What happens?

Giant Ad frames when using a mobile user agent
#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/100882069/301c2c51-6cff-4fbe-a196-0aa815a298f3)

#### Filter lists you're using:

Default Mobile Lists
#### Your settings:

- OS/version: Windows 11 (Also appears on Android)
- Browser/version: Firefox 117.0b1
- Adblock extension/version: uBlock Origin 1.51.1b7

#### Other details:

Screenshot was taken on Windows, but I have reproduced this on Android.

AdGuard's list takes care of this with the `genius.com##div[class^="InreadContainer__Container-"]` filter.

**Comment by ryanbr** [comment]
Looks good here.
