### ISSUE TITLE
Block segment.beeper.com

### ISSUE THREAD

**Issue by 9p4** [easylist/easylist#16947]
Tracking endpoint for [Beeper](https://www.beeper.com).

**Comment by ryanbr** [comment]
Not seeing this.

**Comment by 9p4** [comment]
What do you mean?

**Comment by ryanbr** [comment]
Closing. not seen.

**Comment by 9p4** [comment]
It's an API endpoint using Twilio Segment. I can offer a snapshot of some network requests being sent that show analytics and tracking data.

**Comment by 9p4** [comment]
Beeper is loading `https://segment.beeper.com/analytics.js/v1/q2NxnGDBDOKchoBEXloE7e6son8FkuvS/analytics.min.js`.
