### ISSUE TITLE
Whitelist Help Scout Beacon URLs

### ISSUE THREAD

**Issue by dswindle** [easylist/easylist#1695]
### List the website(s) you're having issues:
https://www.helpscout.net/live-chat/

### What happens?
There should be an icon on the bottom right of the page, that let's one try out the Help Scout beacon feature

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Mac OSX 10.13.6
- Browser/version: Chrome 68.0.3440.106
- Adblock Extension/version: NA

### Other details:
Recently, a customer reported that our CloudFront domain was getting blocked. It looks like that block has now been removed.  See:
https://github.com/easylist/easylist/issues/1587 and https://github.com/easylist/easylist/commit/11f482b9f581ead1a037783db522f378a84fe13d

The URL unblocked above is our Beacon v1 domain. However, we've recently launched Beacon v2 and it uses a different domain.

Beacon v1: djtflbt20bdde.cloudfront.net
Beacon v2: beacon-v2.helpscout.net

I was inquiring about the possibilities to have both whitelisted?

**Comment by llacb47** [comment]
https://github.com/AdAway/adaway.github.io/issues/70

**Comment by HugoQuiroga** [comment]
unsubscribe

De: LE <notifications@github.com>
Responder a: easylist/easylist <reply@reply.github.com>
Fecha: viernes, 10 de abril de 2020, 9:54
Para: easylist/easylist <easylist@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [easylist/easylist] Whitelist Help Scout Beacon URLs (#1695)


AdAway/adaway.github.io#70<https://github.com/AdAway/adaway.github.io/issues/70>
