### ISSUE TITLE
https://savpieces.envienord.fr/nous-contacter

### ISSUE THREAD

**Issue by guillaume-uH57J9** [easylist/easylist#16959]
#### List the website(s) you're having issues with:

`https://savpieces.envienord.fr/nous-contacter`

#### What happens?

The consent checkbox in the contact form is removed, breaking the form. 

#### Screenshot(s) 

![envienord-contact](https://github.com/easylist/easylist/assets/4953748/e8453d8c-595c-4c3e-a53a-bc1df159df37)

#### Filter lists you're using:

EasyList – Cookie Notices

#### Your settings:

- OS/version: Debian GNU/Linux
- Browser/version:  Firefox 102.13.0esr
- Adblock extension/version: ublock origin

#### Other details:

Based on diagnostic with ublock, this DOM rule appear to cause the issue:  
`###gdpr_consent `

**Comment by ryanbr** [comment]
Should be fixed now
