### ISSUE TITLE
Suggestions to add cosmetic filtering for `meteum.ai` and `introvertdear.com`

### ISSUE THREAD

**Issue by LambLeeg** [easylist/easylist#16971]
#### List the website(s) you're having issues with:

https://meteum.ai
https://introvertdear.com

#### What happens?

Meteum.ai by default has ubiquitous ads. However, ads are removed with no `style()` changes. I am suggesting to fix that.

Intovertdear.com by default has a ton of annoyances. I am suggesting to fix that. Also, Firefox blocks it per se, but there is a very annoying flying button of likes that I also block via uBO.

#### Screenshot(s) 

[Before meteum](https://github.com/easylist/easylist/assets/59935189/6f5eb497-2dd4-4001-907d-7a4d6c0fe1ab)
[After meteum](https://github.com/easylist/easylist/assets/59935189/7f6c2078-7a9a-4861-bbee-814fa68ea5e1)

[Before intovertdear](https://github.com/easylist/easylist/assets/59935189/66224e21-ee97-4dfe-966a-c53f1f724330)
[After intovertdear](https://github.com/easylist/easylist/assets/59935189/dd73a915-7d90-4872-9cf6-afbee4ea6432)

#### Filter lists you're using:

```
! meteum.ai

meteum.ai##a[class*="header-meteum"][href="https://b2b.meteum.ai/platform?utm_source=from_meteum_menu"]:remove()

meteum.ai##div[class^="alerts alerts_cols_"]:style(margin: 0 0 0 0 !important)
meteum.ai##div[class="content__top"]:style(margin: 12px 0 8px 0 !important)
meteum.ai##div[class*=forecast-briefly][role="region"]:style(margin: 0 0 8px 0 !important)
meteum.ai##div[class*="pro-entry-points"]:style(margin: 0 0 8px 0 !important)

meteum.ai##a[class*="-promo"][href="https://meteum.ai/meteum"]:remove()

! introvertdear.com

introvertdear.com##^[class*=has-text-align-center]
introvertdear.com##^[class*="social-wrap"]
introvertdear.com##[class^="wp-block-group"]:remove()

introvertdear.com##slick-search-panel:remove()
introvertdear.com##slick-heartbeat:remove()

introvertdear.com##aside[id="secondary"][role="complementary"]:remove()
introvertdear.com##div[class="content-container site-container"]:style(grid-template-columns: auto auto !important)
introvertdear.com##div[id^="disqus_"]:remove()

introvertdear.com##[class="sidebar-inner-wrap"]:remove()
introvertdear.com##[id^=AdThrive_]:remove()
introvertdear.com##[id*=AdThrive_]:remove()
introvertdear.com##.slick-inline-search-panel:remove()
```

#### Your settings:

- OS/version: Windows 11 Pro 22H2
- Browser/version: Firefox 116.0.1
- Adblock extension/version: uBlock Origin 1.51.0

#### Other details:

BEWARE, I am using the uBlock Origin that has unique options for filtering, so it may not be fully compatible. As far as I am concerned, only `:remove()` is questionable here, and HTML prefetching aka `site##^stopit`. The first one may just be deleted, the second one may be made into a common filter by changing `##^` symbol into `##`.

**Comment by ryanbr** [comment]
Not seeing anything here, but any uBO specific filters should suggested in https://github.com/uBlockOrigin/uAssets
