### ISSUE TITLE
planningportal.co.uk

### ISSUE THREAD

**Issue by lol768** [easylist/easylist#16986]
List: [`easylist_cookie_specific_uBO.txt`](https://github.com/easylist/easylist/blob/76ab738e50fe2bd6f61b6f46f4acdcf40bd8bfd0/easylist_cookie/easylist_cookie_specific_uBO.txt#L1943)

Collateral damage from this filter rule:

```
planningportal.co.uk##body,html:style(height: auto !important; overflow: auto !important)
```

Can you exclude subdomain `rail.planningportal.co.uk` from this filter rule please? The rule is currently indiscriminate, and breaks layout on that subdomain (which is provided by a third-party).

The original rule doesn't achieve its goal of blocking the cookie notice on the root domain, in any case - it's impossible to scroll down with the scroll wheel if the cookie notice hasn't been properly dismissed - I think there's some sort of `scroll` event listener on the root element.

**Comment by ryanbr** [comment]
`planningportal.co.uk##body:style(height: auto !important; overflow: auto !important)`

How about limiting to body?

**Comment by lol768** [comment]
@ryanbr I've tested the change, but it would still break the layout on the login page. The rail booking site's login page is designed to have a 100% height body, it's a flex container with `align-items: center; justify-content: center`, so it needs to span the full height of the page in order to be able to centre its children vertically.

**Comment by ryanbr** [comment]
www.planningportal.co.uk
