### ISSUE TITLE
largus.fr

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#16987]
```
##.social-menu > .social-link
```

A: `https://occasion.largus.fr/auto/annonce-fed14063664addea_toyota-c-hr-122h-graphic-2wd-e-cvt-73500-km.html`

```
/adUnitsData.
/googleAdsManager.
/adUnitsBreakpoints.
```
A: `https://www.largus.fr/`

**Comment by Yuki2718** [comment]
I [removed](https://github.com/easylist/easylist/commit/8fa4765299361f394bd5a5c7f288b9fb0f5786ae#diff-466ed2d80c7d258f05a46cf98b323d6c01de494e5805cb8a8a0ae6c4d0ab9ec6L363) as now used for bait and I see they're covered by Liste FR with `||largus.fr/*/includes/javascript/advertising/`
