### ISSUE TITLE
ip2location.com: cookies

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#17019]
![image](https://github.com/easylist/easylist/assets/19517680/1487db29-49d9-491d-8252-6582b38acead)

https://www.ip2location.com/database/ip2location

**Comment by Sonic5435325** [comment]
I don't see this with EasyList - Cookie Notices on, but I do see this newsletter box on the footer:
`ip2location.com##.pre-footer-subscribe-box`
![Screenshot from 2023-08-11 21-50-34](https://github.com/easylist/easylist/assets/89158249/d33fe0dc-6457-4c99-b05d-2fb6ac6619ae)

**Comment by 3xploiton3** [comment]
> uBlock Origin: 1.51.0
> Chromium: 115
> filterset (summary):
>  network: 130063
>  cosmetic: 143286
>  scriptlet: 27099
>  html: 0
> listset (total-discarded, last-updated):
>  added:
>   https://adblockid.pages.dev/adblockid.adfl.txt: 10427-10, now
>   https://adblockid.pages.dev/adblockid_plus.adfl.txt: 524-4, now
>   DEU-0: 7033-0, now
>   IDN-0: 9664-372, now
>   RUS-0: 39688-50, now
>   ara-0: 2321-6, now
>   easylist-annoyances: 3893-47, now
>   easylist-chat: 132-0, now
>   easylist-notifications: 2642-103, now
>   fanboy-cookiemonster: 48045-229, now
>   fanboy-social: 16136-10, now
>   ublock-annoyances: 5351-80, now
>   [1 lists not shown]: [too many]
>  default:
>   user-filters: 13-0, never
>   easylist: 69914-60, now
>   easyprivacy: 33276-246, now
>   plowe-0: 3710-1068, now
>   ublock-badware: 7677-148, now
>   ublock-filters: 34200-391, now
>   ublock-privacy: 453-9, now
>   ublock-quick-fixes: 275-34, 2m
>   ublock-unbreak: 2105-40, now
>   urlhaus-1: 6040-0, now
> filterset (user): [array of 13 redacted]
> trustedset:
>  added: [array of 18 redacted]
> switchRuleset:
>  added: [array of 4 redacted]
> hostRuleset:
>  added: [array of 6 redacted]
> userSettings:
>  advancedUserEnabled: true
>  cloudStorageEnabled: true
>  suspendUntilListsAreLoaded: true
> hiddenSettings: [none]
> supportStats:
>  allReadyAfter: 1034 ms (selfie)
>  maxAssetCacheWait: 466 ms
> popupPanel:
>  blocked: 6
>  network:
>   amazon-adsystem.com: 1
>   google-analytics.com: 1
>   media.net: 1
>   quantserve.com: 1
>   steadfastsystem.com: 1
>   wp.com: 1
>  extended:
>   ##.infolinks-ad
>   ###ai-adb-ads
>   ###ai-adb-sponsors

**Comment by ryanbr** [comment]
We're blocking `​https://cdn.ip2location.com/assets/js/cookie-notice.js` with the filter `/cookie-notice.` which blocks this. So no changes needed here.

**Comment by 3xploiton3** [comment]
sorry, my ublock-origin malfunction, now filter its working
