### ISSUE TITLE
sharespark.net

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#1701]
### List the website(s) you're having issues:

https://sharespark.net/

### What happens?

When you open this website https://sharespark.net/index.php then you see amazon ads on every page of the site and blank space, here is the screenshot:

https://i.imgur.com/G4jQoD3.jpg

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Fanboy’s Cookiemonster List
Fanboy’s Social Blocking List
Peter Lowe’s Ad and tracking server list

### Your settings

- OS/version:  Windows XP SP3 
- Browser/version:  Firefox version 52.92.0 (32 bit)
- Adblock Extension/version: uBlock Origin v1.16.4.4

### Possible fix::

To block the ads and blank space please add these rules:

images-eu.ssl-images-amazon.com/images/*$domain=sharespark.net
sharespark.net###sp_header

The above rules are simple filters, but these filters are necessary to block the ads on the website, which is not blocked yet

**Comment by Khrin** [comment]
Website looks long gone now.
