### ISSUE TITLE
ad placeholder on uol.com.br

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylist#17016]
#### List the website(s) you're having issues with:

`https://www.uol.com.br/tilt/noticias/redacao/2023/06/22/a-crise-de-semicondutores-poderia-ter-custado-a-democracia-brasileira.htm`
#### What happens?

empty ad placeholder as sticky footer

#### Screenshot(s) 

<img width="1552" alt="Screenshot 2023-08-11 at 11 18 35 AM" src="https://github.com/easylist/easylist/assets/56893063/c763b9b4-5d0d-497f-9971-2f0699812fe3">

#### Filter lists you're using:

EasyList
ABP Filters
AA

#### Your settings:

- OS/version: macOS Ventura 13.4.1
- Browser/version: Chrome, Version 115.0.5790.170 
- Ad block extension/version: Adblock 5.9

**Comment by Khrin** [comment]
https://github.com/easylist/easylistportuguese/blob/master/easylistportuguese/easylistportuguese_specific_hide.txt#L318
