### ISSUE TITLE
jj203.equitablebank.ca / EQ Banking App

### ISSUE THREAD

**Issue by KnownStormChaser** [easylist/easylist#17038]
#### Your settings:

- OS/version: iOS 16.6
- Browser/version: N/A
- Ad block extension/version: NextDNS

**Comment by KnownStormChaser** [comment]
Forgot to mention that the link actually redirects to h-equitablebank.online-metrix.net, which in turn is blocked by EasyPrivacy.

**Comment by ryanbr** [comment]
online-metrix.net is a tracker. so nope.
