### ISSUE TITLE
logs.betterstack.com dashboard broken

### ISSUE THREAD

**Issue by JanPokorny** [easylist/easylist#17042]
#### List the website(s) you're having issues with:

logs.betterstack.com

#### What happens?

The "Live Tail" view shows "Sorry, something went wrong" (sometimes takes about a minute to happen, since the blocked request happens periodically)

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/4580066/20bab050-5262-4a1a-9cf1-10a48a6877ae)

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: PopOS 22.04
- Browser/version: Firefox 116.0
- Ad block extension/version: uBlock Origin 1.51.0

#### Other details:

This is caused by this filter: https://github.com/easylist/easylist/blob/5e5d80e2a13cf13bd7f51dee2289c0cb79c7d303/easyprivacy/easyprivacy_trackingservers.txt#L191

This can be fixed by allowing the domain on betterstack.com (logtail.com belongs to betterstack.com):

```diff
- ||logtail.com^
+ ||logtail.com^$third-party,domain=~betterstack.com
```

This is similar to how Sentry (a similar service) is handled: https://github.com/easylist/easylist/blob/5e5d80e2a13cf13bd7f51dee2289c0cb79c7d303/easyprivacy/easyprivacy_trackingservers.txt#L1264

#### Disclaimer

I work at [Better Stack](https://betterstack.com/). We are not an advertising or user tracking company, we do uptime monitoring and server logs collection. I presume some of our users collect logs from browsers client-side, which got our logs collection domain (`logtail.com`) on the blocklist. (It's not the originally intended usage, the service is primarily for machine logs, but there is nothing really stopping users from collecting any type of logs they want.)

Some of our users use EasyPrivacy (in fact, I'm a long time user myself), so it would be super helpful if we could make this change to the blocklist to allow the dashboard to function, while still preserving the blocking on other sites. Thank you!

**Comment by Yuki2718** [comment]
Please upload screenshot(s) of uBO logger.

**Comment by JanPokorny** [comment]
This has now been fixed server-side, so no further action is necessary.
