### ISSUE TITLE
PUP ads

### ISSUE THREAD

**Issue by iam-py-test** [easylist/easylist#17065]
#### List the website(s) you're having issues with:
```
https://cfoc.org/xvideos-virus-how-to-remove-it/
https://cfoc.org/taqw-virus-taqw-file-extension-removal/
```

#### What happens?

Large ads for Combo Cleaner and SpyHunter. This was originally reported to me in https://github.com/iam-py-test/my_filters_001/issues/119.
uBo troubleshooting info:
```
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98234
 cosmetic: 39471
 scriptlet: 18182
 html: 1020
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35107-86, now
  ublock-badware: 7693-1, now
  ublock-privacy: 495-0, now
  ublock-unbreak: 2157-0, now
  ublock-quick-fixes: 281-0, now
  easylist: 69863-703, now
  easyprivacy: 33281-756, now
  urlhaus-1: 6009-0, now
  plowe-0: 3719-1, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2030 ms (selfie)
 maxAssetCacheWait: 235 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
```

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/84232764/9eaae2ca-72e5-4729-b150-f236134d4e2a)
![image](https://github.com/easylist/easylist/assets/84232764/e868dae6-7928-4137-baef-d5ddd29992d6)
![image](https://github.com/easylist/easylist/assets/84232764/34d9f891-6fbb-4e8a-ab8e-f36cdb21a3ec)
![image](https://github.com/easylist/easylist/assets/84232764/718df226-7bf3-43be-a75f-97d1f14752ca)

#### Your settings:

- OS/version: Windows 10 22H2
- Browser/version: Mozilla Firefox 116.0.3 (64-bit)
- Ad block extension/version: uBlock Origin 1.51.0 (but can reproduce with uBlock Origin 1.51.1b19)

#### Other details:

These filters appear to hide the ads in uBo:
```adblock
cfoc.org###top_custom_banner
cfoc.org##.custom_banner_top_btn
cfoc.org##tr:has([href="https://cfoc.org/go-to-spyhunter/"])
cfoc.org##a[href="https://cfoc.org/spyhunter-download-and-install-instructions/"]:upward(2)
cfoc.org##.su-button[href^="https://link.safecart.com/"]:upward(3)
cfoc.org##.widget_text.widget:has([href^="https://cfoc.org/spyhunter-"])
cfoc.org##tr:has([href="https://cfoc.org/combocleaner-download-mac/"])
cfoc.org##p:has(font:has-text( could remain on your Mac if you are not careful during removal. We recommend that you download and run a scan with Combo Cleaner now to professionally clean up your Mac in ))
cfoc.org##font:has(center:has([href="https://cfoc.org/combocleaner-download-mac/"]))
cfoc.org##.widget_text.widget:has([href^="https://cfoc.org/spyhunter-"])
```

**Comment by Sonic5435325** [comment]
**>These filters appear to hide the ads in uBo:**
Could the ":has" be replaced with ":abp-contains"?

**Comment by iam-py-test** [comment]
Not sure. I don't think uBo supports that.
[:has is supported natively by everything but Firefox](https://caniuse.com/?search=%3Ahas)

**Comment by Sonic5435325** [comment]
>:has is supported natively by everything but Firefox, and uBo has a fix for that.
Isn't :has unsupported by ABP?

**Comment by iam-py-test** [comment]
No idea. Doesn't matter in Chromium, as they support it natively.
There probably is a better solution - those were just the rules I came up with.

**Comment by Daxy7** [comment]
edit: found out that `SpyHunter promo` is embedded as images too
https://github.com/easylist/easylist/assets/91396482/e37311bd-7093-48ec-8745-0dfd8518a5b2

now irrelevant:

> "cfoc.org##p:has(font:has-text( could remain on your Mac if you are not careful during removal. We recommend that you download and run a scan with Combo Cleaner now to professionally clean up your Mac in ))"
> 
> to shorten:
> ```
> cfoc.org##p:has(font:has-text( scan with Combo Cleaner ))
> ```
> `detection+removal` disclaimer on spyhunter still there.

**Comment by ryanbr** [comment]
```
cfoc.org###top_custom_banner
cfoc.org##.custom_banner_top_btn
cfoc.org##tr:has([href="https://cfoc.org/go-to-spyhunter/"])
cfoc.org##a[href="https://cfoc.org/spyhunter-download-and-install-instructions/"]:upward(2)
cfoc.org##.su-button[href^="https://link.safecart.com/"]:upward(3)
cfoc.org##.widget_text.widget:has([href^="https://cfoc.org/spyhunter-"])
cfoc.org##tr:has([href="https://cfoc.org/combocleaner-download-mac/"])
cfoc.org##p:has(font:has-text( could remain on your Mac if you are not careful during removal. We recommend that you download and run a scan with Combo Cleaner now to professionally clean up your Mac in ))
cfoc.org##font:has(center:has([href="https://cfoc.org/combocleaner-download-mac/"]))
cfoc.org##.widget_text.widget:has([href^="https://cfoc.org/spyhunter-"])
```
so so ugly

**Comment by iam-py-test** [comment]
I will test later today, but probably.

**Comment by Daxy7** [comment]
> so so ugly

i also see its not in alphabetical and has duplicates. still too much anywho
```
cfoc.org###top_custom_banner
cfoc.org##.custom_banner_top_btn
cfoc.org##.su-button[href^="https://link.safecart.com/"]:upward(3)
cfoc.org##.widget_text.widget:has([href^="https://cfoc.org/spyhunter-"])
cfoc.org##a[href="https://cfoc.org/spyhunter-download-and-install-instructions/"]:upward(2)
cfoc.org##font:has(center:has([href="https://cfoc.org/combocleaner-download-mac/"]))
cfoc.org##p:has(font:has-text( scan with Combo Cleaner ))
cfoc.org##tr:has([href="https://cfoc.org/combocleaner-download-mac/"])
cfoc.org##tr:has([href="https://cfoc.org/go-to-spyhunter/"])
```

**Comment by iam-py-test** [comment]
> Should be enough?

Leaves some leftovers:
![image](https://github.com/easylist/easylist/assets/84232764/ab81ccad-b643-4b29-9062-e170c536a2f8)
> i also see its not in alphabetical and has duplicates. still too much anywho

You have a point.
