### ISSUE TITLE
forum.xda-developers.com

### ISSUE THREAD

**Issue by hawkeye116477** [easylist/easylist#1708]
### List the website(s) you're having issues:
`https://forum.xda-developers.com/meizu-m2-note/development/rom-lineageos-14-1-meizu-m2-note-t3692279`

### What happens?

Advertisement leftovers

### List Subscriptions you're using:

![screenshot_20180816_142634](https://user-images.githubusercontent.com/19818572/44208354-677d5700-a160-11e8-8d71-5fc34a799ced.png)

### Your settings

- OS/version: Manjaro 17.1.11 Hakoila
- Browser/version: Waterfox 56.2.2
- Adblock Extension/version: uBlock Origin 1.16.16

### Other details:

Solution => `forum.xda-developers.com##.purchad`
![screenshot_20180816_141903](https://user-images.githubusercontent.com/19818572/44208090-ad85eb00-a15f-11e8-9c06-f2e9309ea651.png)

**Comment by Hakatitla** [comment]
@hawkeye116477 cannot reproduce, pls close

**Comment by hawkeye116477** [comment]
Ok, I see that they added it recently.
