### ISSUE TITLE
crunchyroll.com

### ISSUE THREAD

**Issue by marcostudios** [easylist/easylist#17104]
#### List the website(s) you're having issues with:

`https://www.crunchyroll.com/it/`
#### What happens?

Video Player shows an error with the EasyList list enabled
#### Screenshot(s) 

![Immagine 2023-08-19 013017](https://github.com/easylist/easylist/assets/5209299/e7f660ce-6bb2-46c8-8ce8-d1e7dd7e46ac)

#### Filter lists you're using:

uBlock filters, EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe’s Ad and tracking server list, [it]  it: EasyList Italy, ➗ Actually Legitimate URL Shortener Tool
#### Your settings:

- OS/version: Windows 10 19045.3324
- Browser/version: Firefox 116.0.3
- Ad block extension/version: uBlock Origin 1.51.0, DuckDuckGo and Firefox built-in antitracking

#### Other details:

The one that stopped the video player error was the EasyList inside the Ads category. I tried disabling all the ad block extensions and then disabling this specific list and then reenabling this list and it seems to be the issue.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a3054c1b5f258951557e556006af8741f332ebb0

Lets see if this helps.

**Comment by marcostudios** [comment]
It solved it, thank you
