### ISSUE TITLE
[EasyPrivacy] chargebee.com

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#17119]
`https://www.chargebee.com/`
`https://www.chargebee.com/integrations/google-analytics/`

Runs in the background of `https://paladins.guru/builds`. Seems to be a sort-of tracking company. Doesn't seem to be required to provide site functionality.

Blocking the entire domain isn't viable (because of https://github.com/easylist/easylist/issues/14802); however, I would suggest the following filter:

`||chargebee.com^$third-party`

**Comment by ryanbr** [comment]
Only saw one on another site. 
https://github.com/easylist/easylist/commit/02c55836563893465635e0fd3f34b2749ecc030d
