### ISSUE TITLE
chess.com ads

### ISSUE THREAD

**Issue by n8x0b7T** [easylist/easylist#17118]
#### List the website(s) you're having issues with:
chess.com
https://www.chess.com/game/live/86372889039

#### What happens?
Currently, easylist includes the following line:
```
chess.com##.game-over-ad-component
```
By using this line instead, It will fix the formatting issue. This issue only shows up when logged in for a given users own games. The styles in this filter rule are for UBO.
```
chess.com##.game-over-ad-component:style(min-height: 0 !important)
```

Additionally, there should be some other elements hidden, that currently are not. These are on the home page when logged in.

```
chess.com##.leaderboard-atf-ad-wrapper
chess.com##.medium-rectangle-atf-ad-wrapper
chess.com##.medium-rectangle-btf-ad-wrapper
``` 

#### Screenshot(s) 
Before:
![image](https://github.com/easylist/easylist/assets/25648252/d0584792-2e57-4885-84b8-ae6b1770032d)
After:
![image](https://github.com/easylist/easylist/assets/25648252/f36ea983-9e1f-4ea5-9a75-88ead1a6b596)

#### Your settings:

I have checked that it is easylist causing the issue. I am using UBO.

**Comment by ryanbr** [comment]
Erm, what ads, the site is clean.

![cheesss](https://github.com/easylist/easylist/assets/1659004/c3dbd919-9068-4360-8a48-020fda962034)

**Comment by n8x0b7T** [comment]
The ads on the end screen for a game are hidden by the filter list, but it causes a formatting issue as demonstrated by the screenshots. This issue only shows up when logged in and looking at one's own games. This is the filter I used to fix it:
```
chess.com##.game-over-ad-component:style(min-height: 0 !important)
```

The other three rules address an issue on the home page when logged in.

**Comment by n8x0b7T** [comment]
These ads are blocked, but could use cosmetic filtering.

![image](https://github.com/easylist/easylist/assets/25648252/9797ee03-5194-413f-a555-e70822ed95b7)
![image](https://github.com/easylist/easylist/assets/25648252/1587669d-c332-48ab-b9cd-72f04ff07ce3)

**Comment by ryanbr** [comment]
Those filter will be needed in uBO, we don't use :style in Easylist.
