### ISSUE TITLE
*.zohoshowtime.com and other custom domains

### ISSUE THREAD

**Issue by GnaniSankaran** [easylist/easylist#17133]
List the website(s) you're having issues with:
https://*.zohoshowtime.com and other custom domains

What happens?
Functionality fails. 

Screenshot(s)
![image](https://github.com/easylist/easylist/assets/137393911/1c4447d2-9ee3-4be5-8965-c275893717b5)

Filter lists you're using:
uBlock Origin

Your settings:
Default with EasyList annoyance enabled

OS/version: macOS Ventura
Browser/version: Chrome latest
Ad block extension/version: uBlock Origin latest

**Comment by GnaniSankaran** [comment]
https://github.com/easylist/easylist/issues/17110#issuecomment-1686127087

**Comment by ryanbr** [comment]
Maybe not use the anti-chat list? Its not a default list. Seems you're opening tickets every other day with a new domain.

**Comment by ryanbr** [comment]
No more zoho exceptions, disable the chat list if you don't like it.
