### ISSUE TITLE
VarageSale ads getting through

### ISSUE THREAD

**Issue by mica** [easylist/easylist#17136]
Ads sometimes gets through on e.g. this page: https://www.varagesale.com/victoria-bc-swap-shop/c/sports-fitness/cycling

uBlock is suggesting filters such as these would take care of them:
`||shopper.flipp.com/static/1.2.14/latest`
`##.flippxp-frame`

**Comment by nima-flipp** [comment]
@ryanbr This filter breaks all network traffic between Flipp's mobile applications and it's backend services. We are seeing a massive spike of unhappy users who think our services are broken! 

please revert

**Comment by mica** [comment]
These ads are still showing up. Here's another another suggestion from ublock:
`||brandmedia.flipp.com/page/20EACOdMjk8.html`

These are very obnoxious full page ads.. have a look: https://i.imgur.com/C6IIQOZ.png

**Comment by ryanbr** [comment]
Will break too much @mica

**Comment by mica** [comment]
How about the other option above? 

`##.flippxp-frame`

**Comment by mica** [comment]
Did you see my last comment @ryanbr? Can we do something about the ads on this site?
