### ISSUE TITLE
Potential adservers

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#17145]
I think it would be interesting to go to `https://optout.aboutads.info/`, opt-out of all and block relevant sites that aren't already blocked. Most of the sites are already blocked (opt-out fails for most of them), but some aren't. (For example: `https://www.branch.io/` is not blocked.)

**Comment by ryanbr** [comment]
Use both Easylist + Easyprivacy. Branch is a tracking company not adserver.
