### ISSUE TITLE
imgur.com

### ISSUE THREAD

**Issue by D4niloMR** [easylist/easylist#17176]
#### List the website(s) you're having issues with:
`imgur.com`

#### What happens?
leftover ads

#### Screenshot(s) 
![image](https://github.com/easylist/easylist/assets/70459964/00922dfe-f648-458d-bed7-9aa4e4b5315d)

#### Filter lists you're using:

Default uBO
#### Your settings:

- OS/version: W10
- Browser/version: Opera GX
- Ad block extension/version: uBO v1.51.0

#### Other details:
 Existing filter: `imgur.com#?#.Post-item:-abp-has(.AdHomeContainer)` 
 should be `div[style]` instead of `.Post-item`

**Comment by ryanbr** [comment]
`imgur.com#?#div[style]:-abp-has(.AdHomeContainer)`  Just blanks out the page.

**Comment by dportvine** [comment]
Works for me `imgur.com#?#.Grid-column > div[style^="height:"]:-abp-has(.AdHomeContainer)`
