### ISSUE TITLE
https://ovyerus.com/

### ISSUE THREAD

**Issue by kotx** [easylist/easylist#17187]
#### List the website(s) you're having issues with:

`https://ovyerus.com/*`

#### What happens?

Sends a request to `https://ovyerus.com/api/event` on page load.
![image](https://github.com/easylist/easylist/assets/33439542/b8fd8744-1fea-4792-887e-4cad22d42a51)

#### Filter lists you're using:

EasyList, EasyPrivacy. EasyList Annoyances

#### Your settings:

- OS/version: Windows Version 22H2
- Browser/version: 118.0.5979.0 (Official Build) canary (64-bit) (cohort: Clang-64) 
- Ad block extension/version: uBlock Origin 1.51.0

**Comment by Ovyerus** [comment]
💀
