### ISSUE TITLE
https://outreach.crossref.org/acton/fs/blocks/showLandingPage/a/16781/p/p-0073/t/page/fm/0

### ISSUE THREAD

**Issue by rclark1** [easylist/easylist#17190]
#### List the website(s) you're having issues with:
`https://outreach.crossref.org/acton/fs/blocks/showLandingPage/a/16781/p/p-0073/t/page/fm/0`

#### What happens?
We were informed by a user on Mastodon that our page is blocked and they can’t access our landing page. 

#### Screenshot(s) 
Here is a screenshot of the landing page. 
<img width="1100" alt="Screenshot 2023-08-30 at 9 09 39 PM" src="https://github.com/easylist/easylist/assets/16803267/9db96504-002c-43e1-a2a0-10487da6832e">

<img width="676" alt="Screenshot 2023-08-30 at 9 09 51 PM" src="https://github.com/easylist/easylist/assets/16803267/ed81130d-e0d9-4dd7-920b-ec8cfcfb0413">

#### Filter lists you're using:

We are not filtering; one of our followers on Mastodon informed us. 

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version: 

#### Other details:

We’ve since disabled the landing page.  We will have to put something up on our own site because we have a call for abstracts for our upcoming annual meeting and board election.  This may have been done in error and kindly request its removal. We must use this domain as it supports functionalities within our email system;

1. Hosting landing pages for our campaigns.
2. Offering a 'read in browser' feature for recipients of our emails.
3. Including links in our newsletters.
4. Enabling form submissions.

We want to emphasize that Crossref adheres to the standards of privacy, security, and ethical practices. All the content served through **outreach.crossref.org** aims to provide information and support to our community involved in the scholarly publishing industry. 

Thank you for your help.

**Comment by ryanbr** [comment]
Remove the CNAME tracker;

```
;; ANSWER SECTION:
outreach.crossref.org.  300     IN      CNAME   a16781.actonservice.com.
a16781.actonservice.com. 86400  IN      CNAME   ci93.actonsoftware.com.
ci93.actonsoftware.com. 65886   IN      CNAME   forpci93.actonsoftware.com.
forpci93.actonsoftware.com. 65886 IN    A       207.189.124.23
```
