### ISSUE TITLE
src* data and base64 filters breaking pornhub thumbnails

### ISSUE THREAD

**Issue by Squall-Leonhart** [easylist/easylist#1719]
The following filters break related videos and playlist thumbnails on Pornhub

extremetube.com,pornhub.com,redtube.com,tube8.com,tube8.es,tube8.fr,xtube.com,youjizz.com,youporn.com,youporngay.com##[src*="data:"]

and

extremetube.com,pornhub.com,redtube.com,tube8.com,tube8.es,tube8.fr,xtube.com,youjizz.com,youporn.com,youporngay.com##[src*="base64"]

**Comment by BlazDT** [comment]
Following rule is breaking pictures, scripts:

`|https://$image,xmlhttprequest,domain=pornhub.com|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com`

**Comment by Alex-302** [comment]
@BlazDT better open new issue. This issue is not relevant.
