### ISSUE TITLE
newstarget.com unblocked ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#172]
`http://www.newstarget.com/2016-10-10-the-power-of-self-defense-texan-stops-4-armed-robbers-with-an-ak-47.html`

Mesosilver ad on the right, Fix your fatigue ad in the middle of article, Belly fat ad on the lower right column.

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/bb0ef63052596047b3065e5d148f83867124d33e
