### ISSUE TITLE
itsfoss.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#17204]
#### List the website(s) you're having issues with:

`https://itsfoss.com/`

#### What happens?

`itsfoss.com##.hero`
`itsfoss.com##.subscribe-form`

#### Screenshot(s) 
![Screenshot from 2023-08-31 14-55-34](https://github.com/easylist/easylist/assets/89158249/afab792d-18e8-43e1-a8fd-e1aece42df13)
![Screenshot from 2023-08-31 14-55-38](https://github.com/easylist/easylist/assets/89158249/2f4d0660-1f8e-4114-978b-0d35656dc019)

#### Filter lists you're using:

Fanboy's Newsletter

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by ryanbr** [comment]
Breaks too much on the site.
