### ISSUE TITLE
thehealthyjournal.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#17205]
#### List the website(s) you're having issues with:
`
https://www.thehealthyjournal.com/baked-cauliflower-with-vegetarian-tzatziki-salad-1558`

#### What happens?

Newsletter form at the footer.

#### Screenshot(s) 

![Screenshot from 2023-08-31 14-59-20](https://github.com/easylist/easylist/assets/89158249/01f16b85-05b7-4c8d-8c54-85efe4e3694e)

#### Filter lists you're using:
Fanboy's Newsletter

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by ryanbr** [comment]
A bit too minor
