### ISSUE TITLE
International cookie notice requests

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#17210]
#### List the website(s) you're having issues with:

`http://www.arabickeyboard.io/`
`http://www.i2arabic.com/`

#### What happens?

There are unblocked cookie related requests.
Possible filters:
`||arabickeyboard.io/*/cookie.min.`
`||i2arabic.com/js/cookie.min.js`

easylist_cookie_international_specific_block.txt doesn't contain an Arabic section.
#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by ryanbr** [comment]
Do we need them? are the cookie messages showing?

**Comment by Sonic5435325** [comment]
The elements are hidden, but these scripts still cause the messages to load

**Comment by ryanbr** [comment]
Not worth it, if they were high profile sites and/or caused other issues showing messages. Have learnt that not every "cookie" network item is related to actual cookie messages either, and can break sites.

**Comment by Sonic5435325** [comment]
> Have learnt that not every "cookie" network item is related to actual cookie messages either, and can break sites.

These cookie scripts cause cookie consent messages to show up in the background.
