### ISSUE TITLE
loudwire.com

### ISSUE THREAD

**Issue by Am4hisa** [easylist/easylist#17237]
#### List the website(s) you're having issues with:

https://loudwire.com/clutch-we-strive-for-excellence-song-lyrics-tour-helmet-quicksand-jd-pinkus/

#### What happens?

Ad leftover

#### Screenshot(s) 

https://img1.imageride.net/images/2023/09/04/image.png

#### Filter lists you're using:

AdGuard Base

#### Your settings:

- OS/version: Windows 10
- Browser/version:  Chrome 116
- Adblock extension/version: AdGuard Browser extension v4.1.57

**Comment by ryanbr** [comment]
Breaks too much
