### ISSUE TITLE
wikihow.com

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#17248]
Breakage: Quiz doesn't go next after clicking an option
```
https://www.wikihow.com/Relationships/Am-I-a-Narcissist-or-an-Empath-Quiz
```
Something in EasyList blocking it
```
unknown
```

**Comment by ryanbr** [comment]
Working for me.

**Comment by Daxy7** [comment]
It was an issue on firefox. I will report to webcompat

**Comment by dportvine** [comment]
Leftovers.

`https://www.wikihow.com/Grow-Your-Own-Christmas-Tree`

<details>
<summary>Screen</summary>

![2023-10-02_164459](https://github.com/easylist/easylist/assets/111344219/c694ebbc-def4-4be4-8ac2-353925cdca21)
</details>
