### ISSUE TITLE
cybermania.ws

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#17240]
#### List the website(s) you're having issues with:

`https://www.cybermania.ws/apps/adobe-genp`
#### What happens?

Anti-adblock
#### Screenshot(s) 

![Screenshot 2023-09-04 at 15-47-22 Adobe CC 2019_2020_2021_2022_2023 GenP Universal Patch 3 2 0 CyberMania](https://github.com/easylist/easylist/assets/52135169/efc19e8a-b741-4aa3-9285-348e8556d4c8)
#### Filter lists you're using:

All uBlock filters, EasyList, Easy Privacy, Online Malicious URL Blocklist, Pete Lowe's, EasyList Annoyances, uBlock filters - Annoyances, Liste AR
#### Your settings:

- OS/version: Windows 11
- Browser/version: Firefox 117.0
- Ad block extension/version: uBlock Origin 1.51.0

**Comment by FanOfRootBeer** [comment]
https://github.com/uBlockOrigin/uAssets/issues
