### ISSUE TITLE
livescores.biz

### ISSUE THREAD

**Issue by xqtp** [easylist/easylist#17253]
#### List the website(s) you're having issues with:

`https://livescores.biz/`

#### What happens?

Ad servers

```
||bescore.com^$third-party
||adtarget.market^

```
#### Filter lists you're using:

<details>
  <summary>Filters</summary>

```  

uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98380
 cosmetic: 117316
 scriptlet: 25306
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  adguard-cookies: 27412-29, 40m
  adguard-popup-overlays: 23517-43, 40m
  adguard-social: 21261-779, 40m
  adguard-spyware-url: 1192-3, 40m
  adguard-widgets: 2288-3, 40m
  ublock-annoyances: 5429-120, 40m
 default:
  user-filters: 67-0, never
  TUR-0: 13726-11, 40m
  easylist: 69511-69, 40m
  easyprivacy: 33324-135, 40m
  ublock-badware: 7786-145, 40m
  ublock-filters: 34353-201, 39m
  ublock-privacy: 539-71, 39m
  ublock-quick-fixes: 248-40, 39m
  ublock-unbreak: 2116-37, 39m
filterset (user): [array of 75 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7322 ms (selfie)
 maxAssetCacheWait: 841 ms
popupPanel:
 blocked: 14
 network:
  adimo.co: 8
  amazonaws.com: 1
  gbqofs.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  newrelic.com: 2

```

</details>

#### Your settings:

- OS/version: Win10 22H2
- Browser/version: Chrome 116
- Ad block extension/version: uBO 1.51

**Comment by FanOfRootBeer** [comment]
please be more detailed? ads? third-party exposure (privacy-related)?

**Comment by ryanbr** [comment]
What is bescore.com?

**Comment by dportvine** [comment]
Bocked for me in **RU AdList** `||cdn.bescore.com/libs/e.js$3p`

<details>
<summary>Screen</summary>

![2023-09-07_142038](https://github.com/easylist/easylist/assets/111344219/8fb93436-83f8-4b8c-a097-b8b38e0e925e)
</details>

I see leftovers only

<details>
<summary>Screen</summary>

![2023-09-07_142038](https://github.com/easylist/easylist/assets/111344219/ff8d8a11-1d1f-4d00-a724-c748395eb989)
</details>
