### ISSUE TITLE
pac.elkhart.lib.in.us - 3 images blocked

### ISSUE THREAD

**Issue by bbgpl** [easylist/easylist#17254]
#### List the website(s) you're having issues with:
https://pac.elkhart.lib.in.us/Polaris/

#### What happens?

Three images are missing on our right sidebar.
The URLs of these missing images are:
https://pac.elkhart.lib.in.us/Polaris/themes/shared/ad2.png
https://pac.elkhart.lib.in.us/Polaris/themes/shared/ad3.png
https://pac.elkhart.lib.in.us/Polaris/themes/shared/ad4.png

EasyList Filters blocking these images:
`/ad2.$~xhr,from=~shoplinker.co.kr|~vereinslinie.de`
`/ad3.$from=~ad3.eu|~vereinslinie.de`
`/ad4.$domain=~ad4.fr|~ad4.wpengine.com|~vereinslinie.de`

#### Screenshot(s) 
Three arrows indicate where the images should be:
![Three missing images](https://i.imgur.com/X8uxcXa.png)

uBlock Origin logger indicates which blocklist and filters are causing the issue:
![blocked images](https://i.imgur.com/MdDUQxT.png)

#### Filter lists you're using:
EasyList

#### Your settings:
Tested in Edge and Firefox on 2 computers. 

- OS/version: Windows 10
- Browser/version: Firefox 117.0
- Ad block extension/version: uBlock Origin 1.51.0

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5400b35b90163e99b6353734692b6fdc7ada43c1
