### ISSUE TITLE
emall.by[Easylist Cookies]

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#17273]
### List the website(s) you're having issues:

`https://emall.by/`

### What happens?

Cookies

<details>
<summary>Screen</summary>

![2023-09-07_161032](https://github.com/easylist/easylist/assets/111344219/166dda54-9f39-4c48-bae3-235789d62f16)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome (stable)
- Adblock Extension/version:  uBO (stable)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d61ef5b559e8547915f0959f4dba2713391dd92b
