### ISSUE TITLE
www.xda-developers.com

### ISSUE THREAD

**Issue by sivajipro** [easylist/easylist#17274]
#### List the website(s) you're having issues with:

[www.xda-developers.com](https://www.xda-developers.com/) 

#### What happens?

adblock blocker

#### Screenshot(s) 

![2023-09-07 21 58 15 www xda-developers com 3a0b7466-3944-41f3-8c67-8a8a2b814bbd](https://github.com/easylist/easylist/assets/46227270/1d7621af-5b91-450d-bf83-609db4d13870)

#### Filter lists you're using:

EasyList, EasyPrivacy, Fanboy's Annoyance List

#### Your settings:

- OS/version: android 13
- Browser/version: Vivaldi 6.2
- Adblock extension/version: Vivaldi Internal adblock

**Comment by FanOfRootBeer** [comment]
handled in uBlock Origin and AdGuard
