### ISSUE TITLE
deezer.com - page gets squished 

### ISSUE THREAD

**Issue by nebrr23** [easylist/easylist#1727]
### List the website(s) you're having issues:

`https://www.deezer.com`

### What happens?

The page gets squished to smaller than half of the monitor. (1080p)
Looks like mobile version of the page (or when you resize the browser window).

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Peter Lowe’s Ad and tracking server list​
CZE, SVK: EasyList Czech and Slovak

### Your settings

- OS/version: Win 10 x64 1803
- Browser/version: Opera 55.0.2994.37
- Adblock Extension/version: uBlock Origin 1.16.14

### Other details:

![opera_2018-08-21_15-41-55](https://user-images.githubusercontent.com/42577061/44405155-e1468380-a558-11e8-9d8c-1ef95f8b3ebe.png)
![opera_2018-08-21_15-42-30](https://user-images.githubusercontent.com/42577061/44405156-e1df1a00-a558-11e8-8301-fede1e79f359.png)

**Comment by nebrr23** [comment]
very recent issue, there was no problem on Sunday

**Comment by Khrin** [comment]
I don't think this is still applicable anymore.
