### ISSUE TITLE
speechify.com mobile app banner

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#17286]
#### List the website(s) you're having issues with:
https://speechify.com/blog/phonetic-transcription/?landing_url=https%3A%2F%2Fspeechify.com%2Fblog%2Fphonetic-transcription%2F

#### What happens?
Prompt to download mobile app

#### Screenshot(s) 
![Screenshot 2023-09-08 at 11-14-09 Phonetic Transcription Understanding The Sounds Of Language 🚀 Speechify](https://github.com/easylist/easylist/assets/101707608/74dfe440-13f6-4c1a-bf6e-84258b09119f)

#### Filter lists you're using:
All filters offered by uBlock Origin

#### Your settings:

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 115.2.0esr
- Ad block extension/version: uBlock Origin 1.51.0

**Comment by DimitrisKalaboukas** [comment]
Suggested filter:

speechify.com##.footer-cta.footer-cta-show

**Comment by ryanbr** [comment]
No.
