### ISSUE TITLE
ad.serv1for.pro and ad.kubiserves.icu

### ISSUE THREAD

**Issue by pog5** [easylist/easylist#17282]
#### List the website(s) you're having issues with:
`https://vsi4kifilmi.com/`

#### What happens?

There is a banner ad bellow the navigation bar served by `ad.serv1for.pro` as a .gif image and then hyperlinked
The element containing the javascript that loads the ad is `/html/body/div[1]/div/div/div/center`
It looks like this `<script type="text/javascript" src="https://ad.serv1for.pro/deliver/js/dac31c2e8c6c50c" async=""></script>`
It then creates a div element with a random id and embeds several iframes from `https://ad.kubiserves.icu/`

#### Screenshot(s) 
<img width="949" alt="image" src="https://github.com/easylist/easylist/assets/62222436/c2198981-fe3d-4adb-aca9-e2945370e0bf">

#### Filter lists you're using:

Look in the section bellow

#### Your settings:

- OS/version: Windows 11 Pro
- Browser/version: Chrome Canary 119
- Ad block extension/version: uBlock Origin 

```
uBlock Origin: 1.51.0
Chromium: 119
filterset (summary):
 network: 109776
 cosmetic: 187112
 scriptlet: 28610
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27511-30, 18m
  adguard-mobile-app-banners: 4598-8, 18m
  adguard-other-annoyances: 13353-7, 18m
  adguard-popup-overlays: 23800-57, 18m
  adguard-social: 21370-907, 18m
  adguard-widgets: 2301-3, 18m
  easylist-annoyances: 3961-200, 18m
  easylist-chat: 134-9, 18m
  easylist-newsletters: 6444-390, 18m
  easylist-notifications: 2658-1437, 18m
  fanboy-cookiemonster: 48413-3918, 18m
  fanboy-social: 16125-715, 18m
  [4 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  BGR-0: 1067-11, 18m
  easylist: 70302-71, 18m
  easyprivacy: 33219-177, 18m
  plowe-0: 3725-1068, 18m
  ublock-badware: 7955-146, 18m
  ublock-filters: 34527-517, 18m
  ublock-privacy: 545-9, 18m
  ublock-quick-fixes: 254-52, 18m
  ublock-unbreak: 2129-36, 18m
  urlhaus-1: 5761-0, 18m
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 383 ms
 maxAssetCacheWait: 174 ms
 ```

**Comment by ryanbr** [comment]
Sure, added.
