### ISSUE TITLE
goanimes.net

### ISSUE THREAD

**Issue by D4niloMR** [easylist/easylist#17284]
#### List the website(s) you're having issues with:
`goanimes.net`

#### What happens?
tracker: `https://fenix.walkerllaw.org/js/script.js`

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by ryanbr** [comment]
```
Sorry, you have been blocked
You are unable to access goanimes.net
```

**Comment by D4niloMR** [comment]
> ```
> Sorry, you have been blocked
> You are unable to access goanimes.net
> ```

Try with Brazil IP

**Comment by D4niloMR** [comment]
Another tracker in the same domain: `https://gronnessegaard.walkerllaw.org/js/script.js`

In the video player on this site:
`https://animeshouse.net/episodio/otome-game-sekai-wa-mob-ni-kibishii-sekai-desu-s1-episodio-1-legendado-hd/`
