### ISSUE TITLE
AliExpress search broken with EasyList

### ISSUE THREAD

**Issue by wefalltomorrow** [easylist/easylist#17285]
With EasyList disabled:

![Untitled](https://github.com/easylist/easylist/assets/45746576/58b1e818-cc7e-431f-b630-ec0960baaf86)

With EasyList enabled:

![Unt1itled](https://github.com/easylist/easylist/assets/45746576/23e19d51-60a4-4b70-ae8c-5f67515ed496)

**Comment by ryanbr** [comment]
Looks fine here:
![aliexp](https://github.com/easylist/easylist/assets/1659004/cef6a362-c4e0-49be-b247-fa6c68e9dc8e)
