### ISSUE TITLE
Ads on varagesale.com

### ISSUE THREAD

**Issue by mica** [easylist/easylist#17290]
On this page, for example: https://www.varagesale.com/victoria-bc-swap-shop/i/cjz649em-line-6-spider-v-2x12

Could you add this filter to EasyList please?: `varagesale.com##.flippxp-frame`

As mentioned [earlier](https://github.com/easylist/easylist/issues/17136), a network filter would break too much, but this should be fine, right?

**Comment by ryanbr** [comment]
Not seen.

**Comment by mica** [comment]
You keep marking this as completed, but the ads persist: https://i.imgur.com/C6IIQOZ.png

Are you able to check the page from a VPN? I'm in Canada, possibly the only country where this site is used.
