### ISSUE TITLE
Recent changes break TinyMCE editor on diablofans.com

### ISSUE THREAD

**Issue by cpaul747** [easylist/easylist#173]
The following rules are breaking the TinyMCE editor on this site.

diablofans.com,jpost.com,technobuffalo.com,tweaktown.com##[style] > [scrolling]
diablofans.com,jpost.com,technobuffalo.com,tweaktown.com##[style] > iframe
diablofans.com,jpost.com,technobuffalo.com,tweaktown.com##iframe[id][style]
diablofans.com,jpost.com,technobuffalo.com,tweaktown.com##iframe[marginheight]
diablofans.com,jpost.com,technobuffalo.com,tweaktown.com##iframe[marginwidth]
diablofans.com,jpost.com,technobuffalo.com,tweaktown.com##iframe[name][style]
diablofans.com,jpost.com,technobuffalo.com,tweaktown.com##iframe[style][scrolling]
diablofans.com,jpost.com,technobuffalo.com,tweaktown.com##iframe[style][src]

**Comment by monzta** [comment]
Closed since these rules no longer exists for diablofans.com.
