### ISSUE TITLE
moovitapp.com annoying popups

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#17307]
#### List the website(s) you're having issues with:
https://moovitapp.com/

#### What happens?
Prompts to give location permission and download mobile app

#### Screenshot(s) 
![Screenshot 2023-09-08 at 08-47-13 Η Πιο Δημοφιλής Εφαρμογή Αστικής Κινητικότητας στη πόλη Αθήνα](https://github.com/easylist/easylist/assets/101707608/919a9bf4-7578-463a-963b-f9224361f766)

![Screenshot 2023-09-11 at 09-36-59 Η Πιο Δημοφιλής Εφαρμογή Αστικής Κινητικότητας στη πόλη Αθήνα](https://github.com/easylist/easylist/assets/101707608/4b296c49-33ad-4bd7-82ed-bf817d9e9eaf)

#### Filter lists you're using:
All filters offered by uBlock Origin

#### Your settings:

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 115.2.0esr
- Ad block extension/version: uBlock Origin 1.51.0

**Comment by DimitrisKalaboukas** [comment]
Suggested filters:

moovitapp.com##.btn-container
moovitapp.com##.mapboxgl-canvas
moovitapp.com##.top.scroll-images-wrapper
moovitapp.com##.useapp-container
moovitapp.com##mv-location-permission
moovitapp.com##style:has-text(.app-container):remove()

**Comment by ryanbr** [comment]
![moov](https://github.com/easylist/easylist/assets/1659004/29394467-e09f-408f-bbd9-a14ef947fe19)

With no changes, it looks fine here.

**Comment by DimitrisKalaboukas** [comment]
@ryanbr The issue is geo-dependent: popups appear from Greece.

Also, issues #15260, #15710, #15756, and #17286 are still pending.
