### ISSUE TITLE
logtail.com blocked

### ISSUE THREAD

**Issue by JanPokorny** [easylist/easylist#17316]
#### List the website(s) you're having issues with:

`https://logtail.com`

#### What happens?

The domain is blocked (eg. uBlock Origin shows the full page warning).

#### Screenshot(s)

![image](https://github.com/easylist/easylist/assets/4580066/7002b938-9fde-419a-99e6-8e45dab52eb2)

#### Filter lists you're using:

- EasyPrivacy

This is caused by this filter: https://github.com/easylist/easylist/blob/5e5d80e2a13cf13bd7f51dee2289c0cb79c7d303/easyprivacy/easyprivacy_trackingservers.txt#L191

#### Other details:

This is an old domain for a service that rebranded from "Logtail" to "BetterStack Logs", and the domain now redirects to `logs.betterstack.com`. The old domain is still used around the web, in discussion forums, StackOverflow, blogs etc., so users clicking this link might be confused by the blocked warning.

#### Disclaimer

I work at [Better Stack](https://betterstack.com/). We are not an advertising or user tracking company, we do uptime monitoring and server logs collection. I presume some of our users collect logs from browsers client-side, which got our domain on the blocklist. (It's not the originally intended usage, the service is primarily for machine logs, but there is nothing really stopping users from collecting any type of logs they want.)

**Comment by JanPokorny** [comment]
@ryanbr I think it's fair to block it as a third party domain using `$third-party`, but accessing the service itself should not be dirupted -- eg. [this forum post](https://community.render.com/t/logtail-contexts-usable-with-the-render-logtail-integration/4097/3) has an old link https://docs.logtail.com/integrations/ruby#context that gets blocked, even though it's a perfectly fine link to documentation.

A similar solution to Sentry would work: https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt#L1279

Eg.

```diff
- ||logtail.com^
+ ||logtail.com^$third-party,domain=~betterstack.com
```

**Comment by ryanbr** [comment]
Reason why a third-party option isn't given, no legit website attached to the domain.

**Comment by JanPokorny** [comment]
@ryanbr Would it be possible to add the third-party option, please? Legit links get blocked, like this one: https://docs.logtail.com/integrations/ruby

**Comment by Khrin** [comment]
> Would it be possible to add the third-party option, please?

No.
