### ISSUE TITLE
1337x.to

### ISSUE THREAD

**Issue by gototheskinny** [easylist/easylist#17315]
#### List the website(s) you're having issues with:

  
 [https://www.1337x.to/torrent/5806288/Barbie-2023-REPACK-1080p-AMZN-WEBRip-DDP5-1-x265-10bit-GalaxyRG265/](https://www.1337x.to/torrent/5806288/Barbie-2023-REPACK-1080p-AMZN-WEBRip-DDP5-1-x265-10bit-GalaxyRG265/)

 

`https://www.1337x.to/torrent/5806288/Barbie-2023-REPACK-1080p-AMZN-WEBRip-DDP5-1-x265-10bit-GalaxyRG265/ `

#### What happens?

 just ads WITH "easylist" ONLY. just reporting bc easylist is being used on every adblocker.

#### Screenshot(s) 

<details>
  <summary>Screenshot</summary>
  
  ![SharedScdfsdfgsdgeZsww3reenshot](https://github.com/easylist/easylist/assets/51786709/6b8f5fa0-f764-4924-bea0-c1112171efb3)
  
  ```javascript
  console.log("I'm a code block!");
  ```
  
</details>

#### Filter lists you're using:

 EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe’s Ad and tracking server list, AdGuard Turkish

#### Your settings:

- OS/version: win10 22h2
- Browser/version: ungoogled chromium 116
- Ad block extension/version: ublock origin 1.52.0

#### Other details:

fixed on:[https://github.com/uBlockOrigin/uAssets/commit/0447584984ecd97b8f99adfc8e943cb31fc47590](https://github.com/uBlockOrigin/uAssets/commit/0447584984ecd97b8f99adfc8e943cb31fc47590)

**Comment by SubZero5** [comment]
The reported ads are back...
