### ISSUE TITLE
www.service-public.fr breakage

### ISSUE THREAD

**Issue by guillaume-uH57J9** [easylist/easylist#17325]
#### List the website(s) you're having issues with:

`https://www.service-public.fr/particuliers/vosdroits/F1420`

#### What happens?

An important interactive portion of the webpage is broken. A loading message persist indefinitely (ie "Veuillez patienter pendant le chargement de la page"). This loading message should disappear and be replaced with an interactive form. 
I suspect this rely on JavaScript, and blocking some script cause might cause a JS error that break the interactive form. 

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/4953748/13150aaa-3135-49ea-a474-949882a6e2e5)

#### Filter lists you're using:

uBlock Filters, EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe’s Ad and tracking server list, AdGuard Annoyances filter, Fanboy's Annoyance List

#### Your settings:

- OS/version: Debian
- Browser/version: Firefox 115.2.0esr (64 bits)
- Ad block extension/version: uBlock Origin 1.51.0

#### Other details:

I suspect this **easyprivacy** filter triggers the issue, since adding an exception for this rule resolve the issue: 
`/eulerian.js`

**Comment by ryanbr** [comment]
Update lists.

**Comment by guillaume-uH57J9** [comment]
Thanks for the fix!
