### ISSUE TITLE
okcaller has a new detection script

### ISSUE THREAD

**Issue by alanzer1** [easylist/easylist#1732]
Thanks for all of the hard work!

### List the website(s) you're having issues:
<http://www.okcaller.com/3142993892>

### What happens?
It appears that the home page works fine, but once you try to search for a phone number it redirects to <http://www.okcaller.com/adblock.php>.

### List Subscriptions you're using:
Ads (2/4)
Adblock Warning Removal List
EasyList
Privacy (1/3)
EasyPrivacy​​​​​
Malware domains (2/4)
Malware Domain List​​​​​
Malware domains​​​​​
Annoyances (0/5)
Multipurpose (1/4)
Peter Lowe’s Ad and tracking server list
Regions, languages (0/36)
Custom (4/5)
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​​​​0 used out of 0​​​​
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters - Whitelist​​​​​

These are all defaults with uBlock Origin with the exception of the Custom section, which are necessary for NanoDefender.

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome Version 68.0.3440.106
- Adblock Extension/version: uBlock Origin Version 1.16.16

### Other details:
I am also using NanoDefender

**Comment by Khrin** [comment]
It seems they don't have an anti adblock system in place anymore.
