### ISSUE TITLE
tappedout.net has some anti-adblock javascript

### ISSUE THREAD

**Issue by reaper527** [easylist/easylist#1734]
### List the website(s) you're having issues:

`http://tappedout.net/`

### What happens?

the screen dims and the site is unusable

### List Subscriptions you're using:

- easylist
- adblock warning removal list
- aaklist (anti-adblock killer)
- fanboy's annoyance list

### Your settings

- OS/version:  windows 10
- Browser/version:  firefox 54 (64 bit)
- Adblock Extension/version:  adblock plus 2.9.1

### Other details:

the anti-adblock code seems to be some jquery embedded directly into the page's document ready. view source is showing this:

```
function adBlockDetected() {
                    ga('set', 'dimension1', 1);
                    if(window.getCookie('adblocker') != "1"){
                        window.setCookie('adblocker', 1, 1);
                    }
                }
                function adBlockNotDetected() {
                    ga('set', 'dimension1', 0);
                    if(window.getCookie('adblocker') == "1"){
                        window.setCookie('adblocker', 0, 1);
                    }
                }
                if(typeof fuckAdBlock === 'undefined') {
                    adBlockDetected();
                } else {
                    fuckAdBlock.onDetected(adBlockDetected);
                    fuckAdBlock.onNotDetected(adBlockNotDetected);
                }
```

**Comment by Khrin** [comment]
Anti-adblock scripts won't be blocked by EasyList.
