### ISSUE TITLE
www.reddit.com - double scroll bars

### ISSUE THREAD

**Issue by ElhemEnohpi** [easylist/easylist#17354]
#### List the website(s) you're having issues with:

`https://www.reddit.com/r/*/comments/*`

i.e., going to any specific Reddit post, linked from a subreddit index.

#### What happens?

On a desktop browser, when logged in to Reddit, with "User Settings - Feed Settings - Open posts in new tab" disabled:

When you're scrolling a subreddit list/index of posts, and then you click on an individual post to see it, it's implemented as a kind of overlay on top of the index page, which is hidden behind the post. (Note this doesn't happen if you go directly to a post URL, or if you reload a post page - only when navigating to a post from a subreddit list or feed).

With the EasyList - Notifications or Fanboy's Annoyance List  active, the hidden index page becomes scrollable and partially visible. There are two scrollbars or thumbs. When you're scrolling the post, and you get to the top or bottom, a second scrollbar becomes active and you start to scroll the hidden page behind. When you use the Back button to go back to the index (which actually closes the overlay) you are not in the same place. Also, if you have it set to autoplay videos from the subreddit index page, they can be triggered by scrolling it while it's hidden behind the post.

The problem is caused by the following filters in Easylist - Notifications, I think it was added recently:

```
reddit.com##body:style(overflow: auto !important;)
reddit.com##body.scroll-disabled:style(overflow: visible!important; position: static!important;)
```
and these, in Fanboy's Annoyance List, which have been there for a while already:

```
reddit.com##body,html.scroll-is-blocked:style(overflow: auto !important;)
reddit.com##body.scroll-disabled:style(overflow: visible!important; position: static!important;)
```

They may have something to do with unlocking scrolling after hiding a popup/popover on mobile. For reference, see these similar filters in uBlock filters – Annoyances, https://github.com/uBlockOrigin/uAssets/issues/6826

```
! https://github.com/uBlockOrigin/uAssets/issues/6826
reddit.com##.XPromoPopup
reddit.com##body.scroll-disabled:style(overflow: visible!important; position: static!important;)
reddit.com##.XPromoInFeed
amp.reddit.com##.AppSelectorModal__body
amp.reddit.com##.upsell_banner
reddit.com##body[style$="overflow: hidden;"]:style(overflow: auto !important;)
```

With those three lists active in uBlock Origin for example, adding the following custom filters resolves the issue:

```
reddit.com#@#body[style$="overflow: hidden;"]:style(overflow: auto !important;)
reddit.com#@#body.scroll-disabled:style(overflow: visible!important; position: static!important;)
reddit.com#@#body,html.scroll-is-blocked:style(overflow: auto !important;)
reddit.com#@#body:style(overflow: auto !important;)
```

#### Screenshot(s) 

Expected: only one scroll bar, and the index page behind is not visible. Note "Close" button indicating the post is overlaid over the index page:

<img width="1126" alt="screenshot_06" src="https://github.com/easylist/easylist/assets/23618559/ddd446a4-6c05-4d35-a3bb-82cd2f45678b">

Acutal: two scrollbars, and the index page behind is slightly visible - note the blue banner etc. showing through on the sides:

<img width="1124" alt="screenshot_07" src="https://github.com/easylist/easylist/assets/23618559/da58a2f6-8a5f-4b5f-b858-64d217e0f5ba">

#### Filter lists you're using:

EasyList - Notifications, Fanboy's Annoyances List (also uBlock Annoyances)

#### Your settings:

Tested in a new, clean Firefox profile with only uBlock Origin installed

- OS/version: macOS 13.5.2
- Browser/version: Firefox 117.0.1
- Ad block extension/version: uBlock Origin 1.52.0

**Comment by ryanbr** [comment]
I test without uBO annoyances, but will ask for them to be removed. Seems redundant

**Comment by ElhemEnohpi** [comment]
@ryanbr The offending lines have now been removed from "uBlock filters – Annoyances".

 No, those filters don't work. It seems now that only this one is required to fix it:

```
! unbreak Reddit scrolling - found in EasyList – Notifications and in Fanboy's Annoyance List:
reddit.com#@#body:style(overflow: auto !important;)
```

**Comment by ryanbr** [comment]
How? I'm not seeing any issues with it. At all. Also tested reddit mobile.

![reddit-scroll](https://github.com/easylist/easylist/assets/1659004/166c41b0-2f6f-4d11-a4ff-0288080d82d2)

**Comment by D4niloMR** [comment]
I'm only able to reproduce while logged

https://files.catbox.moe/aa5rpj.mp4

whitelisting `reddit.com##body:style(overflow: auto !important;)` solved for me.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3f247c89 May help.

**Comment by D4niloMR** [comment]
I added these rules to my filters, it's fixed now

**Comment by D4niloMR** [comment]
@Yuki2718, Can you please take a look on this? `AdGuard – Mobile App Banners` causes the same issue.

Specifically, these two: 
`reddit.com,reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion#$#body:not(.with-listing-chooser) { overflow: visible !important; position: static !important; }`
`reddit.com,reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion#$#body { pointer-events: auto !important; overflow: auto !important; }`

**Comment by ElhemEnohpi** [comment]
It only happens as noted, on a desktop browser, when logged in to Reddit, with "User Settings - Feed Settings - Open posts in new tab" disabled. The commit fixes the issue with "Easylist - Notifications" and "Fanboy's Annoyance List" for me, thanks.

@D4niloMR I can confirm that "AdGuard – Mobile App Banners" also causes the same issue. You can report that at:

[Report an issue | AdGuard](https://reports.adguard.com/en/new_issue.html) or maybe at [Issues · AdguardTeam/AdguardFilters](https://github.com/AdguardTeam/AdguardFilters/issues)

**Comment by Yuki2718** [comment]
@ryanbr `!#if !env_mobile` means apply to desktop-only. I guess was mistake?
