### ISSUE TITLE
Superfluous 'n' in filter list breaking sites

### ISSUE THREAD

**Issue by dvdckl** [easylist/easylist#1736]
### List the website(s) you're having issues:
`https://blizzard.com/`
`https://www.microsoft.com/`
`https://www.nytimes.com/`
`https://bitly.com/`
`https://www.bbc.co.uk/`
`https://www.nih.gov/`
...

### What happens?

Resources from hosts with 'n' in the name fail to load.  Some sites are completely unusable.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 61.0.2
- Adblock Extension/version: 3.2

### Other details:

`https://easylist-downloads.adblockplus.org/easylist.txt` contains the line `||n`, so it appears all URLs that include the letter 'n' are being blocked.

**Comment by MrShemek** [comment]
Same here, I noticed this error on Facebook (it uses `fbcnd` and images ends with `_n`), Stackoverflow and many other websites.

**Comment by dvdckl** [comment]
Confirmed things look good now.

**Comment by dvdckl** [comment]
@mapx- @ryanbr do you have any context on how this issue occurred and how it can be prevented in the future?
