### ISSUE TITLE
swan.io: easylist cookie breaks usability

### ISSUE THREAD

**Issue by bloodyowl** [easylist/easylist#17369]
#### List the website(s) you're having issues with:

- identity.swan.io

#### What happens?

- go to `https://partner.banking.swan.io/auth/login`
- click on the phone prefix button
- `div.r-1xcajam.css-175oi2r` selector is hidden

#### Screenshot(s) 

https://github.com/easylist/easylist/assets/1688645/d8649072-d338-4f56-b162-c9c204af8f45

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: macOS Ventura 13.5.2
- Browser/version: Brave [Version 1.58.124 Chromium: 117.0.5938.62 (Official Build) (arm64)](https://brave.com/latest/)
- Ad block extension/version: —

**Comment by bloodyowl** [comment]
Digging a bit, this commit seems to be the one responsible, these selectors are generic as they're generated by a CSS-in-JS solution, they're just a hash of the applied style.

https://github.com/easylist/easylist/commit/e12c9704fd06087dca5c67edf345ac1aa88a3706

**Comment by zoontek** [comment]
Can confirm that too.

Any element that use react native web `View` in `position: fixed` is impacted. You can see that this rule also breaks a lot of things on [Twitter](https://twitter.com/home)  (using react-native-web too)
