### ISSUE TITLE
A page of team.lidl.gr is being completely blocked

### ISSUE THREAD

**Issue by GeorgeGR21** [easylist/easylist#17362]
#### List the website(s) you're having issues with:

`https://team.lidl.gr/anazitisi-ergasias-lidl-ellas`

#### What happens?

When someone visits the link, **all content** (except the header and footer) is being **blocked** by Easylist's Cookie filter. When the filter is disabled, it loads completely fine.

#### Screenshot(s) 

Screenshot with **Easylist Cookie filter turned OFF**:
![Screenshot from 2023-09-18 20-49-23](https://github.com/easylist/easylist/assets/123986260/7d507fd3-098c-49fd-9817-a3985220c446)
Screenshot with **Easylist Cookie filter turned ON**:
![Screenshot from 2023-09-18 20-49-13](https://github.com/easylist/easylist/assets/123986260/34d3b565-5d66-497d-a870-c19c2c6f2cf9)

#### Filter lists you're using:

EasyList – Cookie Notices

#### Your settings:

- OS/version: Fedora Silverblue 38
- Browser/version: Mozilla Firefox 117.0.1
- Ad block extension/version: uBlock Origin 1.52.0

**Comment by Nojuuu** [comment]
Try 
```adblock
@@||cookiebot.com/uc.js$domain=lidl.gr
```

**Comment by Nojuuu** [comment]
@peace2000 maybe all need this?

https://github.com/uBlockOrigin/uAssets/blob/3392c8c085a2c83d2bffac967cc7fee10af1b331/filters/annoyances-cookies.txt#L84-L85

**Comment by GeorgeGR21** [comment]
> Try
> 
> ```
> @@||cookiebot.com/uc.js$domain=lidl.gr
> ```

This works but it fails to block the cookie notice. It's like disabling uBlock Origin altogether.

**Comment by Nojuuu** [comment]
I'm not seeing cookie notice if I only allow that script.

**Comment by GeorgeGR21** [comment]
This is what I see after adding it. You can see at the top right that uBlock Origin is enabled.
![Screenshot from 2023-09-19 03-45-28](https://github.com/easylist/easylist/assets/123986260/e18a708b-4a23-40fe-b8fe-561c92ac34c2)

**Comment by dportvine** [comment]
@GeorgeGR21 
Have **uBlock filters – Cookie Notices** enabled?

**Comment by GeorgeGR21** [comment]
> @GeorgeGR21 Have **uBlock filters – Cookie Notices** enabled?

Yes, both uBlock Cookie and Easylist Cookie are enabled. I have updated the filters just now and the website works, but there is still this cookie banner in the middle, as shown in the screenshot I attached in my previous reply.

**Comment by dportvine** [comment]
@GeorgeGR21 
Can you test this rule?

```adb
lidl.gr##+js(trusted-set-cookie, CookieConsent, {necessary:true%2Cpreferences:false%2Cstatistics:false%2Cmarketing:false}, 1year)
```

**Comment by GeorgeGR21** [comment]
> @GeorgeGR21 Can you test this rule?
> 
> ```
> lidl.gr##+js(trusted-set-cookie, CookieConsent, {necessary:true%2Cpreferences:false%2Cstatistics:false%2Cmarketing:false}, 1year)
> ```

This works perfectly, thank you. Contribute this to the filter please.

**Comment by peace2000** [comment]
@GeorgeGR21

Just to confirm - how does having these two filters:

||cookiebot.com^$3p
@@||cookiebot.com/uc.js$domain=lidl.gr

Affect the dialog in your end? I can't reproduce the dialog either with those two filters.

**Comment by peace2000** [comment]
Forget the previous message. I tested other lidl websites of other countries and noticed that I can't save a favorite store selection - the same issue as with the Finnish site. Adjusted the filter to match all lidl websites.

https://github.com/uBlockOrigin/uAssets/commit/6f7b7acc8ef9c2621128c0b1391b269df01d5476
