### ISSUE TITLE
spaceref.com

### ISSUE THREAD

**Issue by Am4hisa** [easylist/easylist#17378]
#### List the website(s) you're having issues with:

https://spaceref.com/newspace-and-tech/elon-musk-says-spacex-completed-all-corrective-actions-for-next-starship-launch/

#### What happens?

Ads 

#### Screenshot(s) 

 https://img1.imageride.net/images/2023/09/20/image.png

#### Filter lists you're using:

AdGuard Base

#### Your settings:

- OS/version: Windows 10
- Browser/version:  Chrome 118
- Adblock extension/version: AdGuard Browser extension Ver4.2.168

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7a5d0107
