### ISSUE TITLE
investmentweek.co.uk

### ISSUE THREAD

**Issue by Am4hisa** [easylist/easylist#17379]
#### List the website(s) you're having issues with:

https://www.investmentweek.co.uk/news/4122829/investors-vote-thomaslloyd-energy-impact-continuation

#### What happens?

Ads 

#### Screenshot(s) 

 https://img.imageride.net/images/2023/09/20/image836cbb2872546fca.png

#### Filter lists you're using:

AdGuard Base

#### Your settings:

- OS/version: Windows 10
- Browser/version:  Chrome 118
- Adblock extension/version: AdGuard Browser extension Ver4.2.168

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/725ce5235a6b41cbafa69ebb925b2b4fec561b47
