### ISSUE TITLE
miuiflash.com

### ISSUE THREAD

**Issue by dpthegrey** [easylist/easylist#17372]
#### List the website(s) you're having issues with:
`https://dev.miuiflash.com`

#### What happens?
Adblock Detected

#### Screenshot(s) 
![image](https://github.com/easylist/easylist/assets/49444980/30e715cd-ce1e-4bfb-9bad-6c993870f3b7)

#### Filter lists you're using:
EasyList Ads filter on uBlock Origin

#### Your settings:

- OS/version: macOS 12.6.9
- Browser/version: Firefox 118.0b9
- Ad block extension/version: uBlock Origin 1.52.0

**Comment by ryanbr** [comment]
Submit to uBO Github.
