### ISSUE TITLE
Use GitHub Issue Forms

### ISSUE THREAD

**Issue by RayBB** [easylist/easylist#17388]
Hello,

Have you considered using GitHub issue forms? https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

They provide a quite nice experience [like this](https://github.com/LemmyNet/lemmy/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml&title=%5BBug%5D%3A+) so that it's very clear what sections to fill in etc.

I am thinking of it because I was trying to create #17387 on mobile and it was kinda hard to put it all in the one text box. I think issue forms are much more mobile friendly.

Anyway, just small suggestion that might improve the experience for people reporting :)

**Comment by DandelionSprout** [comment]
It would've helped partially in auto-tagging reports, so I vote in favour of this just for that reason.

**Comment by Khrin** [comment]
@RayBB Very interesting, thanks for your feedback.

**Comment by RayBB** [comment]
@Khrin if you want me to create a PR for it please let me know.
