### ISSUE TITLE
Blocks CDN for stackoverflow.com and arstechnica.com

### ISSUE THREAD

**Issue by Nossnevs** [easylist/easylist#1739]
### List the website(s) you're having issues:

stackoverflow.com
arstechnica.com
### What happens?

Both sites have thier cdn blocked. No css or js is loaded. 

### List Subscriptions you're using:

Easylist English

### Your settings

Only using Adblock Plus

- OS/version: Ubuntu 18.04
- Browser/version: Chrome Version 68.0.3440.84 (Official Build) (64-bit)
- Adblock Extension/version: Adblock plus 3.2

**Comment by Khrin** [comment]
Update EasyList.
