### ISSUE TITLE
uva.nl

### ISSUE THREAD

**Issue by RayBB** [easylist/easylist#17390]
#### List the website(s) you're having issues with:
https://uva.nl/
https://www.uva.nl/en/education/master-s/master-s-programmes/masters-programmes.html

#### What happens?

I see a cookie banner (but only on Mobile)

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/921217/8a2fde9e-d29e-42d3-9500-1a4a7c83612c)

#### Filter lists you're using:

Ublock Origin Defaults + EasyList Cookie List
But it only happens when EasyList Cookie List is enabled.

#### Your settings:

- OS/version: Android 13
- Browser/version: FF 118
- Ad block extension/version: UBO 1.52.0

#### Other details:

Thanks so much for all your work keeping this list working :)
Possibly related to #17387

**Comment by ryanbr** [comment]
I breifly see it, but it disapears for me.

**Comment by RayBB** [comment]
I am not experience this behavior too. Not sure what changed.
Thanks for looking into it!
