### ISSUE TITLE
cursorinfo.co.il[Easylist Cookies]

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#17405]
### List the website(s) you're having issues:

`https://cursorinfo.co.il/`

### What happens?

Scrolling is locked ~> **EasyList – Cookie Notices**.

<details>
<summary>Screen</summary>

![2023-09-26_095519](https://github.com/easylist/easylist/assets/111344219/6cc18986-2f80-445d-8b05-99ead556e1c2)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome (stable)
- Adblock Extension/version:  uBO (stable)

**Comment by dimisa-RUAdList** [comment]
`cursorinfo.co.il##body:style(overflow: auto !important)` or `cursorinfo.co.il##+js(nosiif, blockScrolling)`
