### ISSUE TITLE
numerama.com cookie notice

### ISSUE THREAD

**Issue by mavdl2117** [easylist/easylist#17414]
#### List the website(s) you're having issues with:

`https://www.numerama.com/`

#### What happens?

Cookie warning

#### Screenshot(s) 

![1](https://github.com/easylist/easylist/assets/33755812/bb1bf222-11c1-4a08-8e3d-02c89522c0e4)

#### Filter lists you're using:

Brave's defaults (aggressive) + Fanboy's Annoyances + uBlock Annoyances + Adguard Français

#### Your settings:

- OS/version: Windows 10 / 22H2
- Browser/version: 1.58.131
- Ad block extension/version: 

#### Other details:

Filter suggestion : `numerama.com###didomi-host`

**Comment by Khrin** [comment]
This filter is known to have caused false positives in the past, so there is no need for further problems.
