### ISSUE TITLE
suggestion for `youtube` video ads

### ISSUE THREAD

**Issue by Aslatiel** [easylist/easylist#17413]
#### List the website(s) you're having issues with:

`youtube.com`

#### Description:

As you know, Easylist is used in combination with several other Adblockers.

In regards to `youtube` all of them (the adblockers) apply a different solution to tackle in-video ads for `youtube`. In ABP, we have found that some users do not have the ABP-filters (antiCV list) enabled, hence they are able to reproduce a black screen before/during when a video is being played which contains the ads, but only the audio can be heard. On the ABP-filters list, we have some blocking filters that handle video ads that we use as a backup in case our snippets don't work as expected.

#### Screenshot(s) 

<details>
<summary> see here </summary>

![yt_BLACKscreen](https://github.com/easylist/easylist/assets/121164166/6b4cabf3-dfe8-4670-9f56-8956356f7ae8)

</details>

#### Suggestion:

Why not add the following rules to Easylist (see below), the following filters we use them as fallback in case the main snippets do not work.

If you only run these blocking filters (without ABP-filters enabled), there would still be a black screen but no audio will be heard, and I believe that would at least not confuse users that decide to solely rely on Easylist.

```
||googlevideo.com/videoplayback?*&ctier=L&$xmlhttprequest,domain=www.youtube.com|m.youtube.com|music.youtube.com
@@||googlevideo.com/videoplayback?*&pfa=*$xmlhttprequest,domain=www.youtube.com|m.youtube.com|music.youtube.com
@@||googlevideo.com/videoplayback?*yt_live_broadcast&$xmlhttprequest,domain=www.youtube.com|m.youtube.com|music.youtube.com
@@||googlevideo.com/videoplayback?*yt_premiere_broadcast&$xmlhttprequest,domain=www.youtube.com|m.youtube.com|music.youtube.com
```

**Comment by Khrin** [comment]
Added, thanks.

**Comment by ryanbr** [comment]
Will this cause any issues @Aslatiel ?

**Comment by Aslatiel** [comment]
thanks for accepting the suggestion!...

@ryanbr , we've had these filters on our list for while and it does not cause FPs for users. So I honestly don't expect much issues at all, filters were always meant as a backup/fallback in case snippets don't run.

**Comment by ryanbr** [comment]
Being used as bait now @Aslatiel Had to be reversed
