### ISSUE TITLE
iphone.apkpure.com

### ISSUE THREAD

**Issue by Am4hisa** [easylist/easylist#17417]
#### List the website(s) you're having issues with:

1. https://iphone.apkpure.com/app/high-jump-climb-parkour-3d/com.mss.uponly.climb3d
2. https://iphone.apkpure.com/category/game/action

#### What happens?

Ad slots

#### Screenshot(s) 
 
1.1 https://img1.imageride.net/images/2023/09/26/image.png
1.2 https://img.imageride.net/images/2023/09/26/image.png
2.1 https://img1.imageride.net/images/2023/09/26/imagef3708f9a55389ad2.png

#### Filter lists you're using:

AdGuard Base

#### Your settings:

- OS/version: Windows 10
- Browser/version:  Chrome 118
- Adblock extension/version: AdGuard Browser extension Ver4.2.168

**Comment by dportvine** [comment]
>Filter lists you're using:
>AdGuard Base

Add `EasyList`
