### ISSUE TITLE
znsrc.com

### ISSUE THREAD

**Issue by ajpaon** [easylist/easylist#17428]
EasyPrivacy: please block znsrc.com

This site is used for email tracking in recruitment emails. There is not much information about this site online, but I can forward some sample emails if necessary.

**Comment by ryanbr** [comment]
Which email newsletters? full urls needed also

**Comment by ajpaon** [comment]
I'm not seeing them in newsletters - they're in 1:1 cold outreach emails sent by recruiting teams at many different companies.

The URLs I've seen so far are of the form

```
https://znsrc.com/c/<random ASCII ID>
https://znsrc.com/o/<random ASCII ID>
```

**Comment by ryanbr** [comment]
```
/znsrc.com/c/*$image
/znsrc.com/o/*$image
```

This?

**Comment by ajpaon** [comment]
I'm not clear on the syntax here, but to clarify, based on my observations:

`znsrc.com/o/` URLs are tracking pixel images
`znsrc.com/c/` URLs are redirects

**Comment by ryanbr** [comment]
We'll just block the pixel here then

**Comment by ajpaon** [comment]
Thanks @ryanbr! Could you explain the rationale for skipping the redirect endpoint, though? I just want to understand if this kind of thing could be in scope for easyprivacy.

In these emails, all links in the message are being routed through znsrc so that their prospect tracking platform can tell which links each of their recipients have opened.

To me, it seems like this would be covered by several of the bullets under https://github.com/easylist/easylist#easyprivacy: `Email tracking`, `Linking, loading or initialising to known tracking servers, or scripts`, `Hit counters`

**Comment by ryanbr** [comment]
People complain when they cant open links in emails, tracking pixels more of a concern since it tracks you when just viewing the email. Debouncing (in Brave, https://github.com/brave/adblock-lists/blob/master/brave-lists/debounce.json) is a better solution

**Comment by ajpaon** [comment]
Makes sense.

Debouncing sounds great. I hadn't heard of it yet - thanks for sharing.

I don't think it's a perfect fit, though, since

1. the destination URLs are not guessable from the bouncer URL
2. i suspect there is no re-use of tracking URLs between users

Sounds like the [bouncer warning interstitial](https://github.com/easylist/easylist/issues/17428) in brave is a good fit for this kind of thing.
