### ISSUE TITLE
EasyList Cookie filter is causing pizzafan.gr to be unusable

### ISSUE THREAD

**Issue by GeorgeGR21** [easylist/easylist#17441]
#### List the website(s) you're having issues with:

`https://www.pizzafan.gr/el`

#### What happens?

When a user visits the website, they cannot click anything on the website because a cookie notice blocks the user from doing so. EasyList Cookie blocks the cookie notice, but the blocking thing of that cookie notice is still left there. This prevents the user from accessing anything on the entire website, unless they disable uBlock Origin or the EasyList Cookie filter.

#### Screenshot(s) 

EasyList Cookie disabled. The cookie notice is showing up, and scrolling is blocked.
![Screenshot from 2023-10-01 17-10-18](https://github.com/easylist/easylist/assets/123986260/1fda5d21-ee64-4307-8705-f82111953752)
EasyList Cookie enabled. The cookie notice is not showing up, but the website is still blocked.
![Screenshot from 2023-10-01 17-06-58](https://github.com/easylist/easylist/assets/123986260/31b1a144-8146-4bec-a037-51e03c348a0d)

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: Fedora Silverblue 38
- Browser/version: Firefox 118.0.1
- Ad block extension/version: uBlock Origin 1.52.2

**Comment by Khrin** [comment]
I can't reproduce it, does it still happen to you? @GeorgeGR21

**Comment by GeorgeGR21** [comment]
> I can't reproduce it, does it still happen to you? @GeorgeGR21

Yes, I can still reproduce it. I can send you the logs if you want to.

**Comment by ryanbr** [comment]
Not seeing the issue here, we're not actually blocking the cookie notice on the site. Unless there is an extension or another cookie list being used?

**Comment by GeorgeGR21** [comment]
You're right, it was AdGuard – Cookie Notices that was causing the issue. My bad.
