### ISSUE TITLE
www.bestcrazygames.com

### ISSUE THREAD

**Issue by HoangHaiDang02** [easylist/easylist#17455]
#### What happens?
appear detect adblock when play games, pls help me test

#### Screenshot(s) 
![image](https://github.com/easylist/easylist/assets/91521634/22c675e2-a6a5-4f62-9be7-3a36e2c7583f)

#### Filter lists you're using:
Easy List+ ABPVN List

#### Your settings:

- OS/version: window 11
- Browser/version: Cốc Cốc browser 121
- Ad block extension/version: adblock plus 3.19

**Comment by Sonic5435325** [comment]
Unhidden ad placeholders
`bestcrazygames.com##.ads160600bopt2`
`bestcrazygames.com##.ads160600opt2`
![Screenshot from 2023-12-25 17-06-27](https://github.com/easylist/easylist/assets/89158249/13c01318-18a2-426a-9d98-047133017fdf)
