### ISSUE TITLE
Cookie notice not being blocked at thegreencity.gr

### ISSUE THREAD

**Issue by GeorgeGR21** [easylist/easylist#17464]
#### List the website(s) you're having issues with:

`https://www.thegreencity.gr/`

#### What happens?

When the website is opened, there is a large cookie notice that pops up and it is not being blocked.

#### Screenshot(s) 

![Screenshot from 2023-10-05 13-36-34](https://github.com/easylist/easylist/assets/123986260/bc27c001-0027-4c29-a03d-0e0a780939c8)

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: Fedora Silverblue 38
- Browser/version: Firefox 118.0.1
- Ad block extension/version: uBlock Origin 1.52.2

**Comment by ryanbr** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f1f779fedaf8cc358c3813e59d754587e43fb024
