### ISSUE TITLE
apoteket.se

### ISSUE THREAD

**Issue by ruihildt** [easylist/easylist#17462]
#### List the website(s) you're having issues with:

`apoteket.se`

#### What happens?

Website doesn't load correctly due to a cookie warning hidden

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/13787166/84db6705-1cd8-4cb4-957d-42eb7e41a7f6)

#### Filter lists you're using:

- EasyList/uBO – Cookie Notices

#### Your settings:

- OS/version: Fedora 38
- Browser/version: Firefox 119
- Ad block extension/version: uBO 1.52.2

#### Other details:

Disabling EasyList/uBO – Cookie Notices makes the page load correctly.

**Comment by THEtomaso** [comment]
### Problem filter:
* **EasyList - Cookie Notices**

### Problem rule:
`||cookiebot.com^$third-party `

### Possible fix:
`@@||consent.cookiebot.com/uc.js$domain=apoteket.se`

--

### Other problem filters:
* **AdGuard Cookie Notices filter** (@Yuki2718)
`||cookiebot.com^$domain=~cookiebot.com`

* **I don't care about cookies** (@kiboke)
`consent.cookiebot.com$domain=~deutschesapothekenportal.de|~storyhouseegmont.dk|~storyhouseegmont.no|~storyhouseegmont.se|~egmont.com|~plaion.com|~runescape.com|~jyllands-posten.dk|~tme.eu|~stadtmobil.de|~wwf.fi|~login.nos.pt|~asambeauty.com|~cineplex.de|~berlingske.dk|~digimon.kochfilms.de|~kino.dk|~hoyavision.com|~koeln.de|~cliente.nos.pt|~parkerlebnis.de|~deadwalk.io|~linak.es|~linak.de|~cajamar.es|~digitaltrends.com|~mein-grundeinkommen.de|~werder.de|~finanzmarktwelt.de|~danbolig.dk|~bt.dk|~scubadiving.com|~biomarkt.de|~harzwasserwerke.de|~stern.de|~dasinvestment.com|~derivate.bnpparibas.com|~werkenbijlidl.nl|~swspremberg.de|~nngroup.com|~bankia.es|~bergbauernmilch.de|~ekstrabladet.dk|~epochtimes.de`

**Comment by kiboke** [comment]
@THEtomaso thank you, it will be fixed in IDCAC soon.
