### ISSUE TITLE
Cookie notice blocks Medium articles from fully loading

### ISSUE THREAD

**Issue by GeorgeGR21** [easylist/easylist#17463]
#### List the website(s) you're having issues with:

Main website: `https://betterprogramming.pub/`
Example article: `https://betterprogramming.pub/whats-new-in-http-3-10c2455a4f8c`

#### What happens?

When an article is opened in this website, if you scroll down a bit there will be a cookie notice at the top and you'll notice that articles don't expand. Instead, only a portion of the article is showing. You need to accept cookies for the rest of the website to load. There is also some red text at the top left, as seen in the screenshots I attached.

#### Screenshot(s) 

![Screenshot from 2023-10-05 11-00-54](https://github.com/easylist/easylist/assets/123986260/22477a23-8d5a-4e47-9d0b-4b8e4edf99f7)
![Screenshot from 2023-10-05 11-01-01](https://github.com/easylist/easylist/assets/123986260/48bc717d-b572-4074-9f5e-42fce0818f7d)

#### Filter lists you're using:

All lists uBlock Origin offers + Greek regional filter

#### Your settings:

- OS/version: Fedora Silverblue 38
- Browser/version: Firefox 118.0.1
- Ad block extension/version: uBlock Origin 1.52.2

**Comment by Nojuuu** [comment]
For me it shows this:
![image](https://github.com/easylist/easylist/assets/84513173/33c5b8b5-6d9a-4b72-ba08-444f0404c348)

**Comment by GeorgeGR21** [comment]
You're right. I guess it's just the cookie notice that's not being blocked.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/08e7fce5335ff61bcb7acdca876ab1e13f7c0178
