### ISSUE TITLE
[NSFW] kemono.su

### ISSUE THREAD

**Issue by Linxgos** [easylist/easylist#17477]
#### List the website(s) you're having issues with:

`kemono.su`
`coomer.party`
`coomer.su`

#### What happens?

`kemono.su` uses first party analytics which reports back at `kemono.su/api/event` `kemono.su` is a mirror site of `kemono.party` that already has `||kemono.party/api/event` in easyprivacy to block first party analytics reporting at `kemono.party/api/event` `||kemono.su/api/event` should also be added to easyprivacy.

`coomer.party` is the sister site to `kemono.party` focusing on onlyfans scraping it to also uses first party analytics that reports back at `coomer.party/api/event`
`coomer.party` similar to `kemono.party` also has a mirror site `coomer.su` that uses first party analytics in the same way reporting back at `coomer.su/api/event` as such `||coomer.party/api/event` and `||coomer.su/api/event` should also be added to easyprivacy

#### Filter lists you're using:

uBO all default filters

#### Your settings:

- OS/version: Windows 11
- Browser/version: Firefox 118.0.1
- Ad block extension/version: uBO 1.52.2

**Comment by Daxy7** [comment]
> kemono.su uses first party analytics which reports back at 

1p analytics for mirror and sister site. EasyPrivacy

```
kemono.su
coomer.party
coomer.su
```

```
||kemono.su/api/event
||coomer.party/api/event
||coomer.su/api/event
```
