### ISSUE TITLE
[NSFW] some issue appear "disable adblock"

### ISSUE THREAD

**Issue by HoangHaiDang02** [easylist/easylist#17471]
#### List the website(s) you're having issues with:
"igay69.com",
"netfuck.net"
"camcam.cc"
"phimchill1.net"
"poapan.xyz"
"fullboys.com"
"app.trangchu.news"
"doods.pro"
"download-new.apkmody.fun"
"gaysex.tv"

#### What happens?
appear notification must disable adblock then site load 

#### Filter lists you're using:
EasyList + ABPVN list

#### Your settings:

- OS/version: window 11
- Browser/version: cốc cốc 121
- Ad block extension/version: adblock plus 3.19

#### Other details:
pls help me close issue and comment at here

**Comment by GeorgeGR21** [comment]
Some of these websites (if not all of them) are malicious according to VirusTotal. Please take caution.

**Comment by HoangHaiDang02** [comment]
but it appear a lot of ads to me. And it so uncomfortable. Can you help me block it @GeorgeGR21 . I have report some issue to Easy but don't response, pls help me check it https://github.com/easylist/easylist/issues/17470 https://github.com/easylist/easylist/issues/17485 https://github.com/easylist/easylist/issues/17455

**Comment by GeorgeGR21** [comment]
> but it appear a lot of ads to me. And it so uncomfortable. Can you help me block it @GeorgeGR21 . I have report some issue to Easy but don't response, pls help me check it #17470 #17485 #17455

Replace your ad blocker with [uBlock Origin](https://ublockorigin.com/) and enable all filters + your regional/language filter.

**Comment by HoangHaiDang02** [comment]
but i using adblock plus in my product, i can't change it.Can help me ?

**Comment by HoangHaiDang02** [comment]
@Khrin can you help me ?

**Comment by HoangHaiDang02** [comment]
help me check it i need delete notice

**Comment by GeorgeGR21** [comment]
Why can't you replace Adblock Plus with uBlock Origin? Just click on Remove Extension and then install uBlock Origin. After doing that, enable all filters + your regional/language filter.
