### ISSUE TITLE
acs4-static.privatbank.ua

### ISSUE THREAD

**Issue by lortonx** [easylist/easylist#17472]
#### List the website(s) you're having issues with:

when i sign-up into Hetzner, and enter my card info
https://accounts.hetzner.com/signUp/confirm
script blocked by EasyPrivacy
https://acs4-static.privatbank.ua/content/1.20.2/js/fp2.min.js

How to check without bank account:
const s = document.createElement('script')
s.src = 'https://acs4-static.privatbank.ua/content/1.20.2/js/fp2.min.js'
document.head.appendChild(s)

#### What happens?
False positive block for my bank.

#### Screenshot(s) 
none

#### Filter lists you're using:
EasyPrivacy
rule `/fp2.min.js`

#### Your settings:

- OS/version: Vivaldi
- Browser/version: Latest
- Ad block extension/version: uBlockOrigin latest

**Comment by ryanbr** [comment]
Should be resolved https://github.com/easylist/easylist/commit/fb4b1d8dd791a460ee5dad23b152c1879e0c22ea ?

**Comment by lortonx** [comment]
@ryanbr yes, its solved! issue can be closed, thank you ❤
