### ISSUE TITLE
sainsburys.co.uk

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#17529]
promo 3p nectar ad

```
https://www.sainsburys.co.uk/gol-ui/SearchResults/123123
```

```
sainsburys.co.uk##.CitrusBannerTrio
```
https://github.com/easylist/easylist/assets/91396482/fd656d07-55b5-423a-ab9d-5d957dbf030b

**Comment by Khrin** [comment]
Nothing to block here.
