### ISSUE TITLE
hellawealth.com

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#17565]
ad 20% down the article

```
https://www.hellawealth.com/blog/money/can-you-stop-your-social-security-and-restart-later/
```

```
hellawealth.com##.ad-hh-wrapper
```

**Comment by DandelionSprout** [comment]
For reasons that surprise even me, the fairly large Medicare banner in fact leads to HellaWealth's own frontpage.

**Comment by Daxy7** [comment]
`##.ad-hh-wrapper` doesn't exist anymore, now `##.ad-f1-block` which is self-promo
