### ISSUE TITLE
rswebsols.com 

### ISSUE THREAD

**Issue by Am4hisa** [easylist/easylist#17564]
#### List the website(s) you're having issues with:

 https://www.rswebsols.com/reasons-tablets-better-smartphones/

#### What happens?

Ads 

#### Screenshot(s) 
  
https://img1.imageride.net/images/2023/10/16/image.png

#### Filter lists you're using:

Easylist

#### Your settings:

- OS/version: Windows 10
- Browser/version:  Chrome 118
- Adblock extension/version: AdGuard Browser extension Ver4.2.168

**Comment by DandelionSprout** [comment]
I propose `/rsws-banners^`
