### ISSUE TITLE
False positive on media.ccc.de

### ISSUE THREAD

**Issue by fhd** [easylist/easylist#1757]
### List the website(s) you're having issues:

`https://media.ccc.de/v/content18-52-berlin-werbefrei-no-advertisement-in-public-spaces-`

### What happens?

The video doesn't play, some resources are being blocked by a generic filter matching for `_advertisement_`.

### List Subscriptions you're using:

- EasyList
- ABP filters
- Acceptable Ads whitelist

### Your settings

- OS/version: macOS 10.13.4
- Browser/version: Firefox 61.0.2
- Adblock Extension/version: ABP 3.2.0.2107

**Comment by THEtomaso** [comment]
Fix:
`@@_advertisement_$domain=media.ccc.de`
