### ISSUE TITLE
https://www.soundproofcow.com/how-soundproof-chicken-coop/

### ISSUE THREAD

**Issue by rthfhgyhy567** [easylist/easylist#17593]
https://www.soundproofcow.com/how-soundproof-chicken-coop/

**Comment by iam-py-test** [comment]
What problems have you encountered with this website?
What issue needs to be addressed?
Thanks

**Comment by rthfhgyhy567** [comment]
||www.soundproofcow.com/wp-content/themes/fx-soundproof/assets/img/left-bubble-2.png

**Comment by rthfhgyhy567** [comment]
![image](https://github.com/easylist/easylist/assets/104237805/e4f3ec31-7093-4e5d-858c-298ca92e692a)

**Comment by rthfhgyhy567** [comment]
![image](https://github.com/easylist/easylist/assets/104237805/cc77ed67-5c9c-4230-a800-58ac7c9d1a7b)

Pop up is still not blocked.  Below is the filter that needs created and added to the list.

||www.soundproofcow.com/wp-content/themes/fx-soundproof/assets/img/left-bubble-2.png
