### ISSUE TITLE
indeed.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#1760]
### List the website(s) you're having issues:

```
https://www.indeed.com/viewjob?jk=331367a9e8fe820f&tk=1clsfb9e51ek86tm&from=recommendedjobs&vjs=3
```

### What happens?

Generic filters for easyprivacy.

### Filters:

```
/gnav/log?
/rpc/*?logType=
/thirdpartytag.js
/frontendlogging?
/analytics.js?model=
/tracking/*&sponsored=
```

**Comment by brian-indeed** [comment]
The company pages website on Indeed is blocked:
www.indeed.com/cmp

This is preventing proper styling to be loaded for salaries page as well.

**Comment by smed79** [comment]
https://forums.lanik.us/viewtopic.php?p=147755#p147755
