### ISSUE TITLE
jpg2.su

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#17605]
Adserver: `bulserv.com`

Example: `https://jpg2.su/img/b1082532-100b-4c09-82a6-9f09cb5928b2.YeTDDoi`

@mapx- 
popMagic
see also: https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv/-/issues/84

**Comment by dportvine** [comment]
Redirect to  `https://jpg3.su/img/b1082532-100b-4c09-82a6-9f09cb5928b2.YeTDDoi`
