### ISSUE TITLE
Idea: Reviews for all EasyList changes

### ISSUE THREAD

**Issue by fhd** [easylist/easylist#1761]
(Not a filter issue, I know. Let me know if this should rather go to the forum or elsewhere.)

Last week, a [problematic filter (`||n`) was pushed upstream](https://github.com/easylist/easylist/commit/41eb1d2) by accident. It was fixed fast enough, but since it can take up to 24 hours for users to get the fix (something we're working on reducing in ABP, but we're not there yet), I was wondering if it'd make sense for you guys to try doing reviews (i.e. pull requests) for all changes. It'll probably slow things down somewhat, but it should help avoid such incidents.

**Comment by ryanbr** [comment]
The script has additional checks now
