### ISSUE TITLE
aldi.pt

### ISSUE THREAD

**Issue by virtualwebgit** [easylist/easylist#17643]
#### Your settings:

- OS/version: Windows 11
- Browser/version: Google Chrome x64 118.0.5993.118
- Ad block extension/version: uBlock Origin 1.52.2

**Comment by TotalImportance8529** [comment]
The rule `||usercentrics.eu^$third-party` in Easylist Cookie should already blocked it ? 

But a in-page pop up isn't removed.
![Screenshot_20231029-113851_Kiwi Browser](https://github.com/easylist/easylist/assets/146954135/19d160db-15ea-4ac6-af11-d537b6471cda)

**Comment by virtualwebgit** [comment]
![Untitled](https://github.com/easylist/easylist/assets/113773245/210aa71b-b8d7-42a8-aca2-d8fd50e28873)

Not blocked for me

**Comment by TotalImportance8529** [comment]
Do you used other filterlists ?

**Comment by virtualwebgit** [comment]
I have fixed the issue just by deleting cookies for that site, and now I am not getting the cookie warning anymore.
