### ISSUE TITLE
Whitelist blog.logrocket.com

### ISSUE THREAD

**Issue by griffi-gh** [easylist/easylist#17661]
#### List the website(s) you're having issues with:

blog.logrocket.com is completely inaccessible; their blog contains tons of useful information, mostly about Rust and Javascript, and they have an article almost about everything.    
while logrocket is a tracking platform and `logrocket.com` should remain blocked, the `blog.logrocket.com` subdomain specifically should be safe to whitelist.

#### What happens?

website completely inaccessible

#### Screenshot(s) 

N/A

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: Win11
- Browser/version: Firefox
- Ad block extension/version: uBlock Origin 1.52.2

**Comment by Khrin** [comment]
@griffi-gh That's false.

The website is functioning properly with no apparent issues.
