### ISSUE TITLE
Easylist Cookie breaks reglomobile.fr

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#17682]
#### List the website(s) you're having issues with:
`https://www.reglomobile.fr/recharger-mon-forfait`

#### What happens?
The rule `##.consent-container` in Easylist Cookie breaks hides the checkbox needed.

#### Screenshot(s) 
<img width="960" alt="RackMultipart20231103-37-dkwyb8" src="https://github.com/easylist/easylist/assets/11689349/34ccff05-68bc-4b5c-88af-6c006c2481b6">

#### Filter lists you're using:
Easytlist Cookie

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version: uBO

**Comment by Gaspartame** [comment]
Wow that was fast, thank you !
