### ISSUE TITLE
www.spaste.com

### ISSUE THREAD

**Issue by callmenemo491** [easylist/easylist#1769]
URL:
`http://www.spaste.com/p/?c=bxdcov9520`

Get Text:
"Please disable your ads blocker. And click here to reload Or know more"

Seems they have "fuckadblock.js" which is doing the detection.
seems that this is a generic script, which is used on other sites....

**Comment by THEtomaso** [comment]
Fix:
`@@||spaste.com^$generichide`

**Comment by callmenemo491** [comment]
@THEtomaso , cheers!
