### ISSUE TITLE
pullandbear.com: Notice not blocked

### ISSUE THREAD

**Issue by GeorgeGR21** [easylist/easylist#17702]
#### List the website(s) you're having issues with:

`https://www.pullandbear.com/gr/`

#### What happens?

There is a small notice at the bottom right of the screen when someone opens the website.

#### Screenshot(s) 

![Screenshot from 2023-11-05 03-49-48](https://github.com/easylist/easylist/assets/123986260/68542bf5-35cb-4dc4-a074-511daa913c84)

#### Filter lists you're using:

All EasyList filters

#### Your settings:

- OS/version: Fedora Silverblue 38
- Browser/version: Mozilla Firefox 119.0
- Ad block extension/version: uBlock Origin 1.53.0

**Comment by Khrin** [comment]
No need to block it.
