### ISSUE TITLE
nike.com: Notice not blocked

### ISSUE THREAD

**Issue by GeorgeGR21** [easylist/easylist#17703]
#### List the website(s) you're having issues with:

`https://www.nike.com/nike-by-you`

#### What happens?

There is a small notice at the bottom right of the screen when someone opens the website.

#### Screenshot(s) 
![Screenshot from 2023-11-05 03-49-56](https://github.com/easylist/easylist/assets/123986260/b2c56485-419f-498d-bb5f-dff8da506d84)

#### Filter lists you're using:

All EasyList filters

#### Your settings:

- OS/version: Fedora Silverblue 38
- Browser/version: Mozilla Firefox 119.0
- Ad block extension/version: uBlock Origin 1.53.0

**Comment by Khrin** [comment]
No reason to block it.
