### ISSUE TITLE
mediafire.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#1771]
### List the website(s) you're having issues:

`http://www.mediafire.com/file/abc123/`
`http://www.mediafire.com/error.php?errno=320`

### What happens?

Ads banner / fake download boutton

### Your settings

- Browser/version: FF 61
- Adblock Extension/version: Adblock Plus 3.3

### Filters:

```
||fast.io^$third-party
||imfast.io^$third-party
##a[href^=".mftracking.com/"]
mediafire.com##a[href^=".mftracking.com/"]
```

**Comment by easylistbrasil** [comment]
$csp=script-src 'self',domain=mediafire.com

good luck

**Comment by Khrin** [comment]
It doesn't seems to be valid anymore...

**Comment by smed79** [comment]
@Khrin 

> It doesn't seems to be valid anymore...

https://imgur.com/ETUXrNa.png

```
##a[href^=".mfroute.com/"]
```

**Comment by uBlock-user** [comment]
@ryanbr some unblocked ads on `https://www.mediafire.com/file/nq3nxkucd3pctdl/LiquidMod_5.0_PUBLIC.7z/file`

```
mediafire.com##div.apps
mediafire.com##[id^="div-gpt-ad"]
```

**Comment by llacb47** [comment]
instead of `mediafire.com##[id^="div-gpt-ad"]`: `mediafire.com###adwrapper`

**Comment by uBlock-user** [comment]
Updated
