### ISSUE TITLE
findmcserver.com: Cookie notice

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#17723]
#### List the website(s) you're having issues with:

`https://findmcserver.com/`

#### What happens?

There is a cookie notice at the bottom right of the screen that is not being blocked.

#### Screenshot(s) 
![Screenshot from 2023-11-07 19-50-33](https://github.com/easylist/easylist/assets/123986260/aedf40e5-59c0-4cbc-aa9d-c206edfcf430)

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: Fedora Silverblue 38
- Browser/version: Firefox 119
- Ad block extension/version: uBlock Origin 1.53.0

**Comment by lsomm** [comment]
Try `findmcserver.com##.ant-notification-notice-wrapper`

**Comment by GeorgeGR21** [comment]
> Try `findmcserver.com##.ant-notification-notice-wrapper`

This works but this should be added to the main filter so everyone is benefited.

**Comment by Daxy7** [comment]
https://github.com/easylist/easylist/commit/1771e9bd80e27d274f7a07f06b9c2216e265d579
did this commit fix it?
