### ISSUE TITLE
filhub.gr newsletter notice

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#17729]
#### List the website(s) you're having issues with:
https://filhub.gr/

#### What happens?
Newsletter registration prompt

#### Screenshot(s) 
![Screenshot 2023-11-08 at 15-23-56 Καλώς ήρθατε στον κόσμο του Filhub!](https://github.com/easylist/easylist/assets/101707608/f4f94e45-5122-41df-ba10-4179a3e587b0)

#### Filter lists you're using:
All filters offered by uBO

#### Your settings:

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 115.4.0esr
- Ad block extension/version: uBlock Origin 1.53.0

**Comment by lsomm** [comment]
@DimitrisKalaboukas Funny, my first try was: `filhub.gr##.off-canvas-content`, but tthat might be a bit too harsh(?)

**Comment by DimitrisKalaboukas** [comment]
@AdamWr ?

**Comment by DimitrisKalaboukas** [comment]
@jellizaveta ?
