### ISSUE TITLE
fandom.com [Fanboy Newsletter, Fanboy Annoyance]

### ISSUE THREAD

**Issue by TotalImportance8529** [easylist/easylist#17735]
#### List the website(s) you're having issues with:
`https://marvelcinematicuniverse.fandom.com/wiki/Marvel_Cinematic_Universe_Wiki`
`https://marvelcinematicuniverse.fandom.com/f/p/4400000000003523435`
`https://marvelcinematicuniverse.fandom.com/wiki/Nick_Fury`
`https://gravityfalls.fandom.com/wiki/Natural_Law_of_Weirdness_Magnetism`

#### What happens?
First screenshot :Fandom's social media page self-promotion
Second : Affiliate link to other Fandom wiki
Third : A pop up, clicking it will redirect you to Fandom sign up page
Fourth : Promotion about other Fandom wiki, need to click the view mobile site at the bottom of the website to view it.
Last : Fandom newsletter email subscribe form

#### Screenshot(s) 
![Screenshot_20231109-221649_Kiwi Browser](https://github.com/community/community/assets/146954135/72fa28b4-cc72-4f88-bca0-df5d47f6f5c1)
![Screenshot_20231109-221703_Kiwi Browser](https://github.com/community/community/assets/146954135/58307290-e2b8-413a-bff8-21350345f505)
![Screenshot_20231109-221908_Kiwi Browser](https://github.com/community/community/assets/146954135/03fa1af3-4bef-4f02-bcee-a527fab50aa8)
![Screenshot_20231109-222401_Kiwi Browser](https://github.com/community/community/assets/146954135/e27767df-53ac-4b96-bc76-1f8aa229e8c6)
![Screenshot_20231109-222727_Kiwi Browser](https://github.com/community/community/assets/146954135/d7f513c0-8749-4646-8f29-fc69e78a2129)

#### Your settings:
``` yaml 
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 198837
 cosmetic: 124994
 scriptlet: 25813
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  CHN-0: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 22552-12, 20m
  adguard-spyware-url: 1310-5, 21m
  block-lan: 54-0, 21m
  curben-phishing: 77836-20, 21m
  easylist-annoyances: 4168-32, 21m
  easylist-chat: 150-0, 21m
  easylist-newsletters: 6633-15, 21m
  easylist-notifications: 2872-83, 21m
  fanboy-cookiemonster: 48819-223, 21m
  fanboy-social: 16189-13, 20m
  ublock-annoyances: 5774-81, 20m
  ublock-cookies-easylist: 493-493, 20m
 default:
  easylist: 75165-21, 21m
  easyprivacy: 32854-163, 21m
  ublock-badware: 7435-144, 20m
  ublock-filters: 35229-182, 20m
  ublock-privacy: 663-88, 20m
  ublock-quick-fixes: 152-93, 20m
  ublock-unbreak: 2135-37, 20m
  urlhaus-1: 10950-2, 20m
filterset (user): [array of 13 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoCommentFilterTemplate: none
supportStats:
 allReadyAfter: 6075 ms (selfie)
 maxAssetCacheWait: 2152 ms
```
 

- OS/version: Android 10; Build/QP1A.190711.020
- Browser/version: Kiwi Browser 116.0.5845.240
- Ad block extension/version: uBlock Origin 1.52.2

**Comment by ryanbr** [comment]
Not worth filtering, maybe for personal filters. But the moment we try this, someone will complain we're doing too much.

**Comment by TotalImportance8529** [comment]
ok
