### ISSUE TITLE
independent.co.uk

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#17749]
taboola placeholder
```
https://www.independent.co.uk/news/world/americas/trump-trial-news-today-rally-ivanka-latest-b2445070.html
```
```
###taboola-mid-article-thumbnails-ii
```

**Comment by Daxy7** [comment]
now
```
https://www.independent.co.uk/tech/samsung-galaxy-ring-health-new-b2493007.html
```
```
###taboola-mid-article-thumbnails-iii
```
maybe use something like `##[id^="taboola-mid-article-thumbnails-"]` ?

**Comment by Daxy7** [comment]
@Yuki2718 ad placeholder -ɅɅɅɅɅɅɅɅɅɅɅɅɅɅɅɅɅɅɅ-
https://github.com/easylist/easylist/assets/91396482/20499858-81a4-40b1-a49a-3b804630ab7d

**Comment by Yuki2718** [comment]
Coincidently EL authors are discussing about taboola rules now.

**Comment by Daxy7** [comment]
So if moved to area https://github.com/easylist/easylist/blob/d3949b9e81006ab08cd374e5c161d8f315c7bc4d/easylist/easylist_general_hide.txt#L15722 it's considered too rare to add?

**Comment by Yuki2718** [comment]
We won't add generic hiding rules for Taboola until consensus is made in coming June.
