### ISSUE TITLE
dicebreaker.com

### ISSUE THREAD

**Issue by wavygecko** [easylist/easylist#17751]
### URLs

- `https://www.dicebreaker.com/`

### Description

sticky leaderboard ad at bottom of page `#sticky_leaderboard`

<img width="1192" alt="image" src="https://github.com/easylist/easylist/assets/110956608/dd2cd091-6bb5-4c6b-8ddb-7749e5ab8f8b">

### Settings

<details>

```yaml
uBlock Origin: 1.53
Firefox: 119.0
listset:
  added:
    adguard-spyware-url
    block-lan
    fanboy-cookiemonster
    ublock-cookies-easylist
  default:
    user-filters
    ublock-filters
    ublock-badware
    ublock-privacy
    ublock-abuse
    ublock-unbreak
    ublock-quick-fixes
    easylist
    easyprivacy
    urlhaus-1
    plowe-0
```
</details>

**Comment by Yuki2718** [comment]
> The element proposed to be filtered is there, but it's invisible. Should it still be added?

If it prevents e.g. clicking links, but apparently not.
