### ISSUE TITLE
Youtube.com tracker

### ISSUE THREAD

**Issue by jordanswrld94** [easylist/easylist#17753]
||youtube.com/generate_204 appears on videos. Similar 204 filters exist in list.

https://youtube.com/watch?v=5tBBQGkmn_0&pp=ygUPYWRibG9jayB5b3V0dWJl

**Comment by Yuki2718** [comment]
We used to block this but unblocked by a problem.

**Comment by Daxy7** [comment]
@Yuki2718 New placeholders being hidden on homepage, when previously was not the case with single ads, prev case: https://github.com/uBlockOrigin/uAssets/issues/16848 [……Old Screenshot……](https://github.com/easylist/easylist/assets/91396482/062890b0-4337-429e-9fbc-606829ee5e3f) 


Current ad placeholders. YT maybe A/B Testing more ad slots. The recommendations are messy, removing anti-placeholder fixes this.
[……New Screenshot……](https://github.com/easylist/easylist/assets/91396482/f0aff2e5-1aad-40fb-bdc2-b29ec9ab707e)


Cause of filter:
`www.youtube.com##body > ytd-app > #content.ytd-app.style-scope > tp-yt-app-drawer#guide.ytd-app.style-scope[align="start"][role="navigation"][style^="transition-duration:"][position] + ytd-mini-guide-renderer.ytd-app.style-scope + ytd-page-manager#page-manager.ytd-app.style-scope > ytd-browse.ytd-page-manager.style-scope[page-subtype="home"][role="main"] > ytd-settings-sidebar-renderer.ytd-browse.style-scope + dom-if.ytd-browse.style-scope + ytd-two-column-browse-results-renderer.grid-disabled.grid.ytd-browse.style-scope[page-subtype="home"][style] > #primary.ytd-two-column-browse-results-renderer.style-scope > ytd-rich-grid-renderer.ytd-two-column-browse-results-renderer.style-scope[style^="--ytd-rich-grid-item-max-width:"] > #spinner-container.ytd-rich-grid-renderer.style-scope + #contents.ytd-rich-grid-renderer.style-scope > ytd-rich-grid-row.ytd-rich-grid-renderer.style-scope > #contents.ytd-rich-grid-row.style-scope > ytd-rich-item-renderer.ytd-rich-grid-row.style-scope[items-per-row]:has(> #content.ytd-rich-item-renderer.style-scope > ytd-ad-slot-renderer.ytd-rich-item-renderer.style-scope:not(:empty))`

**Comment by Daxy7** [comment]
Yeah, the rule is in easylist already but the ad gaps shift the video feed. I was using `#@#` on it to demonstrate.
It looks unprofessional to have it as 4-5 videos randomly and not all 5 videos in sequence with gaps.
https://github.com/easylist/easylist/assets/91396482/9cb8e19c-5b01-4168-a7f2-87b0e242114f

**Comment by Yuki2718** [comment]
Maybe this was asked? Wonder how @stephenhawk8054 thinks.

**Comment by Daxy7** [comment]
div was upd [smaller path]
```
youtube.com##body > ytd-app > #content.ytd-app.style-scope > ytd-page-manager#page-manager.ytd-app.style-scope > ytd-browse.ytd-page-manager.style-scope > ytd-two-column-browse-results-renderer.grid-disabled.grid.ytd-browse.style-scope > #primary.ytd-two-column-browse-results-renderer.style-scope > ytd-rich-grid-renderer.ytd-two-column-browse-results-renderer.style-scope > #contents.ytd-rich-grid-renderer.style-scope > ytd-rich-grid-row.ytd-rich-grid-renderer.style-scope > #contents.ytd-rich-grid-row.style-scope > ytd-rich-item-renderer.ytd-rich-grid-row.style-scope:has(> #content.ytd-rich-item-renderer.style-scope > ytd-ad-slot-renderer.ytd-rich-item-renderer.style-scope)
```

**Comment by stephenhawk8054** [comment]
> Maybe this was asked? Wonder how @stephenhawk8054 thinks.

Oh I didn't realize there's this thread. If it's potentially safe, I think it's good to be in annoyance list?

**Comment by Yuki2718** [comment]
Looks the rule works except when yt put single sponsored ad on top of all other videos.

**Comment by Yuki2718** [comment]
Disabled for https://github.com/uBlockOrigin/uAssets/issues/20586#issuecomment-2007034008
