### ISSUE TITLE
slimjet.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#1777]
### List the website(s) you're having issues:

`https://www.slimjet.com/en/ad-blocker.php`

### What happens?

False positive blocking of images.

### List Subscriptions you're using:

Default uBO filters

### Your settings

- OS/version: Windows 7
- Browser/version: Chrome 68
- Adblock Extension/version:  uBO 1.16.18

### Other details:

EasyList filter `/images/ad-` needs an exception for this domain.

**Comment by THEtomaso** [comment]
> `/images/ad-` needs an exception for this domain.

The rule is rather aggressive, so I think that the exception should be generic.
Something like this perhaps?:
```
@@/images/ad-block$image
@@/images/ad-blocker$image
```
