### ISSUE TITLE
https://star-history.com

### ISSUE THREAD

**Issue by ave9858** [easylist/easylist#17774]
#### List the website(s) you're having issues with:

`https://star-history.com/#easylist/easylist&Date`

#### What happens?

Ads shown at the right of the screen

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/112294121/0080f5a9-f415-49b3-98f1-6d66419148b2)

#### Filter lists you're using:

Tested with default uBO filters and just EasyList.

#### Your settings:

- OS/version: Windows 10
- Browser/version: Firefox 119.0.1
- Ad block extension/version: uBlock Origin 1.53.0

#### Other details:

Suggested filters at https://github.com/uBlockOrigin/uAssets/issues/20106 were 
```
||star-history.com/sponsors/$image,1p
star-history.com##.fixed.right-0
```

I tested those filters and they hide the ads.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/38feaa76928cb5a7348cd5029d94c591999ae26b
