### ISSUE TITLE
panobi.com first-party API blocked

### ISSUE THREAD

**Issue by ssandler-panobi** [easylist/easylist#17772]
#### List the website(s) you're having issues with:

`https://app.panobi.com`

#### What happens?

First party API requests matching `/api/v1/metrics` are blocked by ad blockers using easylist. These are not tracking or advertising related and are core functionality of the Panobi product.

Observed in Ghostery (see https://github.com/ghostery/ghostery-extension/issues/1381#issuecomment-1808918422)

#### Screenshot(s) 

<img width="538" alt="Screenshot 2023-11-13 at 9 16 59 AM" src="https://github.com/easylist/easylist/assets/131009835/d33516d0-1552-4c34-8ffc-de32510f2e39">

#### Filter lists you're using:

Ghostery using https://github.com/easylist/easylist/blob/a1a600d0a3043f8f7080135f222e7dc70f8b2b0a/easyprivacy/easyprivacy_general.txt#L310

#### Your settings:

- OS/version: Mac OS 13.5.1
- Browser/version:  Chrome 119
- Ad block extension/version: Ghostery 8.12.4

**Comment by Khrin** [comment]
The filter will not be removed.

**Comment by chrmod** [comment]
@Khrin how about we change it to a `$third-party`?

**Comment by chrmod** [comment]
FYI at Ghostery we've applied such exception:
```
@@/api/v1/metrics$1p
/api/v1/metrics$3p
```

**Comment by Khrin** [comment]
> @Khrin how about we change it to a `$third-party`?

This is not possible, as it would be contrary to the purpose of the filter.
