### ISSUE TITLE
YouTube Gaming - Ad markers

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#1778]
### Affected site:
`https://gaming.youtube.com/`

### Issue:
Ad markers are visible.

### Example:
`https://gaming.youtube.com/watch?v=ePI6USOMHec`

### Screenshot:

![filterissue-youtubegaming](https://user-images.githubusercontent.com/9382674/44959727-65065580-aef3-11e8-8fac-592569d0ab1e.jpg)

### Possible fix:
`youtube.com##.ytp-ad-progress`

### Note:
For some reason, this existing rule (found in **EasyList**) doesn't seem to work for `gaming.youtube.com`:
`##.ytp-ad-progress`
You need to add `youtube.com` in front of it.

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.0.1 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

--

**EDIT:**
### Explanation of what's happening:
The issue has been explained by gorhill here:
https://github.com/uBlockOrigin/uAssets/issues/3389#issuecomment-417960686
and here:
https://github.com/uBlockOrigin/uAssets/issues/3389#issuecomment-417961433

> The proper workaround is to create `youtube.com##.ytp-ad-progress`.

**Comment by THEtomaso** [comment]
A similar rule is needed for **DramaFever.com**.

Example:
`https://www.dramafever.com/drama/5193/18/are-you-human-too/`

Possible fix:
`dramafever.com##.vjs-admarker`

**Comment by hawkeye116477** [comment]
It's not needed, it works correctly. Probably you have some list that adds generichide exclude for youtube.

**Comment by THEtomaso** [comment]
No, there IS an issue.
Follow the discussion in the report that has been refered to above.

**Comment by THEtomaso** [comment]
The issue has now been explained by gorhill here:
https://github.com/uBlockOrigin/uAssets/issues/3389#issuecomment-417960686
and here:
https://github.com/uBlockOrigin/uAssets/issues/3389#issuecomment-417960686

**Comment by THEtomaso** [comment]
@ryanbr:

Why did you close this issue report?
This is still a problem in '**EasyList**', and I've provided links in my previous post, where the issue is explained!

The fix is simple..
Make a site-specific rule:
` youtube.com##.ytp-ad-progress`

**Comment by ryanbr** [comment]
Because it won't work and we already have that rule ^

**Comment by THEtomaso** [comment]
@ryanbr:

The rule in '**EasyList**' is generic, like this:
`#.ytp-ad-progress`

If you follow the links that I posted, you'll see how gorhill explains why this doesn't always work for all browsers.
It's a timing issue.

I've confirmed that this issue exists for some browsers @ `https://gaming.youtube.com/`
..and that this rule fixes it!:
`youtube.com##.ytp-ad-progress`
