### ISSUE TITLE
[Missing Filters] TV4-Group [SE]

### ISSUE THREAD

**Issue by WildS0ft** [easylist/easylist#178]
Video-ads are showing on the TV4-Group websites (Swedish).

The filter: `||videoplaza1.tv^$third-party`  blocks them.

http://www.tv4.se/gilla-tv/
http://www.tv4play.se/program/nyhetsmorgon (scroll down to "_Senaste klippen_" and choose any)
http://www.fotbollskanalen.se/video/
http://www.koket.se/video

These all belong to the same concern (The TV4-Group) and uses the same advertisements and videoplayer. To see any of these clips on either site **requires no account**.

https://github.com/reek/anti-adblock-killer/issues/1464

**Comment by flyingzebras** [comment]
https://github.com/reek/anti-adblock-killer/issues/1464

**Comment by flyingzebras** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/20

**Comment by monzta** [comment]
EasyList doesn't cover non-English speaking sites.

**Comment by flyingzebras** [comment]
I updated the issue to https://github.com/reek/anti-adblock-killer/issues/1464 @WildS0ft

**Comment by flyingzebras** [comment]
I updated the issue to https://github.com/ryanbr/fanboy-adblock/issues/59 @WildS0ft
