### ISSUE TITLE
canva.com: cookies

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#17809]
![image](https://github.com/easylist/easylist/assets/19517680/d32a81e0-ad03-42b4-a357-5be2c88dd34d)

https://www.canva.com/design/DAFxVfLMbMA/LlVjYLPSN4VJVIu4oGWFvA/view?utm_content=DAFxVfLMbMA&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by ryanbr** [comment]
Fixed in uBO Cookie list
