### ISSUE TITLE
data.gov.hk [Breakage]

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#17801]
#### List the website(s) you're having issues with:
`https://data.gov.hk/tc/application`

#### What happens?
Website not working normally.

#### Screenshot(s) 
![Screenshot_20231115-201417_Firefox Beta](https://github.com/community/community/assets/146954135/eb61d614-61e6-4cce-84eb-896e02d518e3)
![Screenshot_20231115-201606_Firefox Beta](https://github.com/community/community/assets/146954135/24350cbf-ffdb-4d24-9129-322c36227eb4)

#### Your settings:
``` yaml 
uBlock Origin: 1.53.0
Firefox Mobile: 120
filterset (summary):
 network: 201186
 cosmetic: 125416
 scriptlet: 25606
 html: 1293
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  adguard-mobile: null
  plowe-0: null
  CHN-0: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 22601-12, 2d.22h.46m
  adguard-spyware-url: 1310-88, 2d.22h.46m
  block-lan: 54-0, 2d.22h.46m
  curben-phishing: 80250-27, 2m
  easylist-annoyances: 4175-94, 2d.22h.46m
  easylist-chat: 153-0, 2d.22h.46m
  fanboy-cookiemonster: 48865-289, 2d.22h.46m
  ublock-cookies-easylist: 566-0, 2d.22h.46m
  easylist-newsletters: 6649-13, 2d.22h.46m
  easylist-notifications: 2873-4, 2d.22h.46m
  fanboy-social: 16194-7, 2d.22h.46m
  ublock-annoyances: 5832-602, 2d.22h.46m
 default:
  ublock-filters: 36475-127, 2d.22h.46m
  ublock-badware: 7456-5, 2d.22h.46m
  ublock-privacy: 662-0, 2d.22h.46m
  ublock-unbreak: 2199-2, 2d.22h.46m
  ublock-quick-fixes: 154-1, 2m
  easylist: 75265-369, 2d.22h.46m
  easyprivacy: 32873-125, 2d.22h.45m
  urlhaus-1: 10745-0, 2m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings:
 autoCommentFilterTemplate: none
 trustedListPrefixes: ublock- user- https://get.letsblock.it/list/10ed17c7-db36-40f6-86d0-00cad74ab372.txt
supportStats:
 allReadyAfter: 6151 ms
 maxAssetCacheWait: 3150 ms
popupPanel:
 blocked: 3
 network:
  data.gov.hk: 2
  baidu.com: 1
 extended:
  ###dropdown-share
  ##.social__list
  ##.social__link
```
 

- OS/version: Android 10; Build/QP1A.190711.020
- Browser/version: Firefox Beta 120.0b9 (Build #2015985088)
- Ad block extension/version: uBlock Origin 1.53.0 

#### Other details: 
<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +5 |  |  | data.gov.hk | 1 | get | web_manifest | `https://data.gov.hk/assets/shared/img/favicon/site.webmanifest` |
| +4 | ##.social__list |  | data.gov.hk |  | get | dom | `https://data.gov.hk/tc/application` |
| +4 | ##.social__link |  | data.gov.hk |  | get | dom | `https://data.gov.hk/tc/application` |
| +4 | ###dropdown-share |  | data.gov.hk |  | get | dom | `https://data.gov.hk/tc/application` |
| +4 | /cookiealert.js | -- | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/cookieAlert.js` |
| +4 |  |  | data.gov.hk | 3 | get | script | `https://service2.mtcaptcha.com/mtcv1/client/mtcaptcha2.min.js` |
| +4 |  |  | data.gov.hk | 3 | get | script | `https://service.mtcaptcha.com/mtcv1/client/mtcaptcha.min.js` |
| +3 | \|\|hm.baidu.com^$3p | -- | data.gov.hk | 3 | get | script | `https://hm.baidu.com/hm.js?93dfb0b39d8d1a88201994a517b67956` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/themes/main/js/init.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/feedbackForm.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/historicalDataRes.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/historicalData.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/resourceDetails.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/datasetDetails.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/datasetListing.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/annualOpenDataPlan.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/providerListing.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/datasetAnnouncement.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/applicationsPage.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/community.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/aboutOpenData.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/cityDashboard.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/otherResources.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/homePage.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/pages/downloadQueue.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/dateRangePicker.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/skipToMain.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/stickyHeader.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/print.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/filterAndSort.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/touchHover.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/animateOnScroll.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/eventCalendar.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/responsiveVideo.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/responsiveTable.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/responsiveImg.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/backToTop.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/loadMore.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/bsModal.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/bsDropdown.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/jumpToForm.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/bsSelect.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/tooltip.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/collapse.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/tab.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/lightbox.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/videoPlayer.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/slick.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/menu.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/socialShare.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/announcement.js` |
| +2 | /cookiealert.js | -- | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/cookieAlert.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/enableJS.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/queryTest.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/commonFn.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/var.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/browserInfo.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/scripts/lang.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/list.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/jquery.validate.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/mtcaptcha-integration.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/shuffle.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/addToCalendar.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/daterangepicker.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/moment.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/aos.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/jquery.magnific-popup.custom.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/slick.custom.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/jquery.izilla.touchMenuHover.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/bootstrap/bootstrap-multiselect.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/bootstrap/bootstrap-select.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/bootstrap/bootstrap.bundle.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/jquery-ui.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/what-input.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/jquery-3.6.1.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/picturefill.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/hongkong-logo.svg` |
| +2 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/wacg-logo.svg` |
| +2 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/no-result.svg` |
| +2 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/cartoons/applications-cartoon.svg` |
| +2 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/social/social-weibo.svg` |
| +2 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/social/social-twitter.svg` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/shared/js/lib/default.min.js` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/client/js/baidu-analytics.js` |
| +2 |  |  | data.gov.hk | 1 | get | font | `https://data.gov.hk/assets/shared/fonts/icomoon/fonts/wico.woff2` |
| +2 |  |  | data.gov.hk | 1 | get | font | `https://data.gov.hk/assets/shared/fonts/Poppins-Bold.woff2` |
| +2 |  |  | data.gov.hk | 1 | get | font | `https://data.gov.hk/assets/shared/fonts/Poppins-Regular.woff2` |
| +2 |  |  | data.gov.hk | 1 | get | font | `https://data.gov.hk/assets/shared/fonts/Poppins-Light.woff2` |
| +2 |  |  | data.gov.hk | 1 | get | font | `https://data.gov.hk/assets/shared/fonts/OpenSans-SemiBold.woff2` |
| +2 |  |  | data.gov.hk | 1 | get | font | `https://data.gov.hk/assets/shared/fonts/OpenSans-Regular.woff2` |
| +2 |  |  | data.gov.hk | 1 | get | script | `https://data.gov.hk/assets/constant.js` |
| +1 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/logo_psi-portal-2x.png` |
| +1 |  |  | data.gov.hk | 1 | get | doc | `https://data.gov.hk/tc/application` |
| +0 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/decor-d-white-gradient.svg` |
| +0 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/decor-o.svg` |
| +0 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/decor-cube.svg` |
| +0 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/svg/decor-circle.svg` |
| +0 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/menu-4_1x.png` |
| +0 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/menu-3_1x.png` |
| +0 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/menu-2_1x.png` |
| +0 |  |  | data.gov.hk | 1 | get | image | `https://data.gov.hk/assets/shared/img/menu-1_1x.png` |
| +0 | \|\|hm.baidu.com^$3p | -- | data.gov.hk | 3 | get | script | `https://hm.baidu.com/hm.js?93dfb0b39d8d1a88201994a517b67956` |
</details>

**Comment by Linxgos** [comment]
`@@/cookiealert.$domain=data.gov.hk`
