### ISSUE TITLE
eurovisionworld.com: Cookie notice not blocked

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#17800]
#### List the website(s) you're having issues with:

`https://eurovisionworld.com/`

#### What happens?

There is a cookie notice in the middle of the screen that blocks the whole website from being used, if there is no interaction with the notice.

#### Screenshot(s) 
![Screenshot from 2023-11-14 22-35-29](https://github.com/easylist/easylist/assets/123986260/ea89675f-b688-462c-a3ad-f037a399c6a6)

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: Fedora Silverblue 39
- Browser/version: Firefox 119.0.1
- Ad block extension/version: uBlock Origin 1.53.0

**Comment by Khrin** [comment]
Surely there was never a problem there to begin with.
