### ISSUE TITLE
Please remove 8 Bitcoin DNS seed domains from EasyPrivacy

### ISSUE THREAD

**Issue by freerko** [easylist/easylist#17813]
Thank you very much for your work, I use EasyPrivacy since more than 15 years, when it was still the ABP Tracking Filter.

Now for the first time I ran into overblocking/false positives: in easyprivacy_trackingservers.txt, the following 8 Bitcoin DNS seed domains are currently blocked:

> ||dnsseed.bitcoin.dashjr.org^
> ||dnsseed.bluematt.me^
> ||dnsseed.emzy.de^
> ||seed.bitcoin.sipa.be^
> ||seed.bitcoin.sprovoost.nl^
> ||seed.bitcoin.wiz.biz^
> ||seed.bitcoinstats.com^
> ||seed.btc.petertodd.org^

In the [Bitcoin source code there are 9 DNS servers hard-coded](https://github.com/bitcoin/bitcoin/blob/master/src/kernel/chainparams.cpp#L129-L142), the domain seed.bitcoin.jonasschnelli.ch is the only one currently not blocked in EasyPrivacy (although that domain is used since at least 8 years, longer than some of the other blocked domains).

Bitcoin DNS seeds return IPs of random Bitcoin nodes as DNS A or AAAA records, are run by individual volunteers and are only used for initial peer discovery, see [this description](https://developer.bitcoin.org/devguide/p2p_network.html). Tor for example uses a similar system with hardcoded fallback directories.

The [Bitcoin DNS seed policy](https://github.com/bitcoin/bitcoin/blob/master/doc/dnsseed-policy.md) states:

> 4. Any logging of DNS queries should be only that which is necessary for the operation of the service or urgent health of the Bitcoin network and must not be retained longer than necessary nor disclosed to any third party.

I am not aware of any case of tracking, fingerprinting, geo checks, telemetry or otherwise any behavior that would justify blocking of any of those domains according to the EasyPrivacy goals. All domains are [constantly monitored for anomalies](https://www.21.ninja/dns-seeds/). The operator of the blocked seed.bitcoin.wiz.biz for example [explains the architecture behind his DNS seed](https://wiz.biz/bitcoin/seed)  - with explicitly stating "the DNS resolvers do not log queries from users". According to the Easylist readme, servers added to the trackingservers.txt are "Where the server has only one purpose to track/analyze user, will be blocked at the url level." - this is clearly not the case here.

The blocked domains cause issues when running for example a PiHole with activated EasyPrivacy together with a Bitcoin full node (such as the RaspberryPi Bitcoin distributions [RaspiBlitz](https://github.com/raspiblitz/raspiblitz), [Umbrel](https://github.com/getumbrel/umbrel) or [MyNode](https://github.com/mynodebtc/mynode)) in the same network.

Can you please remove the above mentioned 8 filters from the EasyPrivacy list?

Thanks!

**Comment by ryanbr** [comment]
came from https://github.com/hoshsadiq/adblock-nocoin-list (commit https://github.com/easylist/easylist/commit/6105c44a214a2e69a78e70d3810ae70b17aef336) We block coin miners

**Comment by Yuki2718** [comment]
They're not miner. https://github.com/hoshsadiq/adblock-nocoin-list/issues/416#issuecomment-816262729
