### ISSUE TITLE
mo8it.com

### ISSUE THREAD

**Issue by mo8it** [easylist/easylist#17826]
#### List the website(s) you're having issues with:

- `mo8it.com`
- `hyteck.de`

#### What happens?

The `count.js` script is blocked.

This is caused by the following commit: https://github.com/easylist/easylist/commit/4e86e2f57ec86c9867cb367562740f71488ae06f

I am the author of the software [OxiTraffic](https://codeberg.org/mo8it/oxitraffic/) behind this script. `mo8it.com` is also my personal website.

OxiTraffic shouldn't be blocked because I designed it from the ground up to be privacy preserving. This means that it **doesn't collect ANY personal data**. No IP, no cookies, no `User-Agent`, no fingerprinting, nothing is touched that could be used to identify a user on the web, not even indirectly.

All what OxiTraffic collects is:
- The time of the visit.
- The amount of time spent on the page.
- The referrer origin (no query parameters, no path, only the origin).

Please, I always use uBlock Origin on all my devices to preserve my privacy. I would never develop something that would hurt the privacy of others. OxiTraffic is self-hosted and completely free and open source. You can verify my claims by taking a look at the [commented source code of the tiny blocked script](https://codeberg.org/mo8it/oxitraffic/src/commit/ccec7edfde8a9800678942879f7f85fec06f7285/templates/count.js).

I am open to any questions and hope that the linked commit is reverted soon. I can also submit a PR.

Thank you for protecting our privacy ❤️

**Comment by moan0s** [comment]
As my personal website is also affected I also wanted to add that I specifically used OxiTraffic so that I can turn of any web-logging on my server (which previously logged IP addresses). There is not even a GDPR disclaimer needed. Therefore I'd argue that adding my domain to privacy-list is wrong as there is no privacy issue here. As @mo8it said, there is no personal data collected which can be verified. As the ID changes with each page load no tracking is possible.

Another question that I was just curious about (but feel free to ignore): Why is one domain on `easyprivacy/easyprivacy_specific.txt` and `easyprivacy/easyprivacy_thirdparty_international.txt`?

**Comment by Linxgos** [comment]
I think that `count.js` should remain blocked. Any client side analytics software open source or not allows for the collection of additional information that server side analytics alone can not. Any client side analytics software open source or not will increase memory usage and cpu usage. I'm also skeptical about how privacy respecting Oxitraffic really is. The source code of `count.js` shows that Oxitraffic tracks visitor time spent on site using `document.visibilityState` js property what combined with ip logging server side could be a pretty privacy invasive. I'm glad to see alternatives to the privacy nightmare of `google-analytics.com/analytics.js` finally start to come out the woodworks but any analytics software by definition is privacy invasive and should continue to be blocked by adblockers like uBO.

**Comment by mo8it** [comment]
@Linxgos Let me explain the usage of `document.visibilityState`. The script sends in total 2-3 requests to the backend.

1. The first request is sent at the beginning to tell the backend that a visitor arrived so it fetches a temporary ID (which is deleted when the page is left, no privacy issue).
2. The second request is sent after spending at least 20 seconds on the page in the foreground (not when the tab is hidden). This request leads to counting the visit. The 20 seconds of delay is required to filter out bot traffic and only count valuable visits.
3. The third and last request is sent when the tab is closed or the page is changed. This is not reliable because of the many ways a user could close the browser. This is why I said 2-3 requests. But when this request is actually sent, it tells the backend how much time the user spent on the page in seconds.

`document.visibilityState` is used to start and stop the time measurement. No requests are sent on switching tabs. Therefore, a possible IP logging (I don't log any) on the server side would not help identifying the user.

What the backend sees from these three requests:

1. The first request tells the backend that a random client called a page on the website. It can be a bot, it can be a human, the backend knows nothing about that client. But it sends him a **temporary** ID for the next two requests.
2. The second request tells the backend that the client spent at least 20 seconds on the page in the foreground. The backend verifies that claim by checking the temporary ID. If this claim of the minimum time spent is fulfilled, the backend counts the visit in the hope that this was a human. The request also sends the referrer [**origin**](https://developer.mozilla.org/en-US/docs/Web/API/URL/origin) (basically the domain with the scheme `http`/`https`). This means that if I click on the link to that page from `https://github.com/easylist/easylist/issues/17826?example=value`, only `https://github.com` is sent. This helps knowing where the page was shared. It tells me for example that I should promote my blog posts more on Twitter because I get many visitors with the referrer domain `t.co`.
3. The third request tells the backend that the client left the page and claims to have spent a specified amount of time on the page in the foreground. The backend doesn't know when this time in the foreground was spent. It doesn't know when the tab was in the background. It doesn't know to which page the client possibly went afterwards. The temporary ID is deleted on the change of the page because it is a simple variable in the script. It is not stored in a cookie or something. In fact, if the user just reloads the page, the backend can't differentiate him from a completely new user.

I am open to be corrected about how this could be privacy invasive.

That being said, you mention resource usage and I see why someone would still like to opt out of this anonymous, lightweight statistics. Although the script only sends 2-3 requests as explained and uses almost no resources, I would agree with giving an option to opt out. That option can be an opt-in list in uBO.

My main problem is that the script is blocked in a list that is enabled by default in uBO and this list is designed for blocking _privacy invasive_ requests (EasyPrivacy) although the script does **nothing that could harm privacy**.

**Comment by Linxgos** [comment]
> The request also sends the referrer [origin](https://developer.mozilla.org/en-US/docs/Web/API/URL/origin) (basically the domain with the scheme http/https). This means that if I click on the link to that page from https://github.com/easylist/easylist/issues/17826?example=value, only https://github.com is sent.

This is privacy invasive.
For example lets say you click on a link to a site that uses OxiTraffic from a site that is very small, for instance the website of a small regional school in northern Ontario, only a couple 100 people would probably use said site. From the origin data sent back you would be able to see that site the user originated from. Just based off of context you would be able to figured out that user probably either goes to that school or knows someone that goes to that school. You have also figured out that person approximate location as that person probably lives in said area.

**Comment by mo8it** [comment]
[`Referer`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) is an HTTP header that often sends the whole referrer URL anyway. So if the website of that school in your example doesn't use the [`no-referrer`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) policy, then the server behind the visited website would know anyway more information than the origin that the script sends if this header is logged. If you combine this header with the IP, you get a privacy problem.
It is important to highlight that OxiTraffic respects the `no-referrer` policy. It doesn't even touch the `Referer` header because it might contain even more information than just the origin. This means that OxiTraffic collects less information about the referrer than what browsers send anyway.

**Comment by Linxgos** [comment]
Let's just say that school website does use `no-referrer` by the website linked using OxiTraffic it disregards the parent website intention to not be revealed

**Comment by mo8it** [comment]
The script uses the `document.referrer` property. The value of it is empty when the referrer policy is `no-referrer`. To let you verify my claim, I built two tiny test websites:

You go to https://test1.mo8it.com and click on the first link which will show you the content of `document.referrer`. When you click on the second link that has `rel="noreferrer"`, you will see that the value of `document.referrer` is empty which means OxiTraffic respects the referrer policy.

**Comment by Khrin** [comment]
I think that it can be left blocked.

**Comment by mo8it** [comment]
@Khrin Just out of interest: Would you remove the block if I make OxiTraffic opt-in? Because [the EasyPrivacy policy](https://github.com/easylist/easylist/#easyprivacy) doesn't seems to differentiate between opt-in / opt-out or whether personal data is touched or not.

Tagging @ryanbr because he added the entries to the list.

I don't want to spam. I won't reply again if you say that the block would not be removed even if I make it opt-in.

You might be interested in the post that I published about this blocking: https://mo8it.com/blog/privacy

**Comment by ryanbr** [comment]
We added it, opt in or out doesn't matter. 

- We block plausible and matomo also, aka 'privacy friendly' etc. 
- Privacy policy don't matter, they can change at any stage. Just ignored.

For the end user, why would I want his script to run? No benefit. Only benefits the server wanting to track clicks/referrers.

https://hyteck.de/post/oxitraffic-setup/

**Comment by Yuki2718** [comment]
Here is a rare case that EL authors and uBO team couldn't reach agreement. We will consider unblocking on uBO side if it is indeed made opt-in, as with already the case for resource-miner. We will still block in Annoyance list which user have to explicitly enable.

**Comment by ryanbr** [comment]
I've yet too see arguements from uBO here.

**Comment by Yuki2718** [comment]
I told shortly in Slack.

**Comment by ryanbr** [comment]
If they cut most of that script, no referrer checks, then it would work better. Make it truely opt in.  @mo8it

**Comment by gorhill** [comment]
> Here is a rare case that EL authors and uBO team

I am against. If people want to opt-in to tracking, they can disable EasyPrivacy. There is no way for us to start to audit that analytics providers do exactly what they say they do, and having to this such auditing on a regular basis. It's simple, EasyPrivacy being enable means the users do not want analytics-related code being executed in their browsers. If you start to make one exception, then except incessant requests to make more to the point where this will be unmanageable.

We can't block server logs, so those webmaster interested in analytics can use this.
