### ISSUE TITLE
yahoo.com, engadget.com, techcrunch.com

### ISSUE THREAD

**Issue by metametapod** [easylist/easylist#17834]
#### List the website(s) you're having issues with:

- `https://www.yahoo.com`
- `https://www.engadget.com`
- `https://techcrunch.com`

#### What happens?

These sites show a blocking modal when using Global Privacy Control (GPC) that still appears with the EasyList Cookie and Fanboy's Annoyances lists enabled.

Steps to reproduce:

1. Download clean build of latest Firefox stable or Firefox nightly.
2. Install uBlock Origin.
3. Enable all EasyList filters.
4. Disable all other filters.
5. Set `privacy.globalprivacycontrol.enabled` and `privacy.globalprivacycontrol.functionality.enabled` to `true` in `about:config`.
4. Navigate to `yahoo.com`, `engadget.com`, or `techcrunch.com`.

#### Screenshot(s) 

<img width="798" alt="Screenshot 2023-11-21 at 13 25 58" src="https://github.com/easylist/easylist/assets/80652640/f06aed2e-3156-4fc3-8b4a-49b2464a28b9">

#### Filter lists you're using:

EasyList, EasyPrivacy, and all of EasyList — Annoyances on uBlock Origin.

#### Your settings:

- Browser/version: Firefox 121.0b1 (latest nightly), 120.0 (latest stable).
- Ad block extension/version: uBlock Origin 1.53.0

#### Other details:

Suggested filter rule:

```
engadget.com,techcrunch.com,yahoo.com###consent-gpc-popUp
```

**Comment by ryanbr** [comment]
Did this help? https://github.com/easylist/easylist/commit/321b3626ceca1e10c3c428faef6a352616f39aa2

**Comment by metametapod** [comment]
Yes, that fixed it on all three sites. Thank you!

**Comment by metametapod** [comment]
These seem to have resurfaced. Screenshot with EasyList/uBO — Cookie Notices enabled:

![Screenshot 2024-12-30 at 19 34 48](https://github.com/user-attachments/assets/bd76298b-3700-4cb1-814c-d271f56d5c7c)

Also visible on other two sites.
