### ISSUE TITLE
https://www.milwaukeetool.com/Products/2649-20 Newsletter pop up

### ISSUE THREAD

**Issue by rthfhgyhy567** [easylist/easylist#17848]
![image](https://github.com/easylist/easylist/assets/104237805/f2d3f95d-e2b1-4859-bd62-3b7db15faba1)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/17c9dbf604f0f806ad4fdd5a7dd8c64b7ad19303
