### ISSUE TITLE
Tracking message on https://kolik.cz 

### ISSUE THREAD

**Issue by QSHXBW** [easylist/easylist#17853]
#### List the website(s) you're having issues with:
<code>https://kolik.cz</code>

#### What happens?
This request seems to be contain sensitive information and blocking it does not seem to have an impact on the page
https://sa.kolik.cz/simple.gif?version=custom_latest_11&hostname=www.kolik.cz&ua=Mozilla%2F5.0%20(X11%3B%20Linux%20x86_64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F111.0.0.0%20Safari%2F537.36&https=true&timezone=America%2FNew_York&page_id=3c804d27-dcd5-40e9-bf28-f24ba1eef22a&session_id=d8ea4baa-b4af-4302-9f14-0870f99c41b9&sri=false&mobile=false&brands=%5B%7B%22brand%22%3A%22Chromium%22%2C%22version%22%3A%22111%22%7D%2C%7B%22brand%22%3A%22Not(A%3ABrand%22%2C%22version%22%3A%228%22%7D%5D&os_name=Linux&os_version=5.15.0&path=%2F&viewport_width=780&viewport_height=476&language=en-US&screen_width=800&screen_height=600&unique=true&id=3c804d27-dcd5-40e9-bf28-f24ba1eef22a&type=pageview&time=1700164073950](https://sa.kolik.cz/simple.gif?version=custom_latest_11&hostname=www.kolik.cz&ua=Mozilla%2F5.0%20(X11%3B%20Linux%20x86_64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F111.0.0.0%20Safari%2F537.36&https=true&timezone=America%2FNew_York&page_id=3c804d27-dcd5-40e9-bf28-f24ba1eef22a&session_id=d8ea4baa-b4af-4302-9f14-0870f99c41b9&sri=false&mobile=false&brands=%5B%7B%22brand%22%3A%22Chromium%22%2C%22version%22%3A%22111%22%7D%2C%7B%22brand%22%3A%22Not(A%3ABrand%22%2C%22version%22%3A%228%22%7D%5D&os_name=Linux&os_version=5.15.0&path=%2F&viewport_width=780&viewport_height=476&language=en-US&screen_width=800&screen_height=600&unique=true&id=3c804d27-dcd5-40e9-bf28-f24ba1eef22a&type=pageview&time=1700164073950%27)

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by Yuki2718** [comment]
> Fixed with [3b6951a](https://github.com/easylist/easylist/commit/3b6951a98174fd3552de2ca98e4d20e2ec97a2eb).

I don't even see `simpleanalyticsexternal.com` on the page.

**Comment by Khrin** [comment]
> 
> I don't even see `simpleanalyticsexternal.com` on the page.

`simpleanalyticsexternal.com` is a CNAME of `sa.kolik.cz`, but obvs that's not enough to resolve the problem completely.
