### ISSUE TITLE
www.google.*

### ISSUE THREAD

**Issue by AroKol78** [easylist/easylist#17862]
- does not block the first occurrence of `adservice.google.pl/adsid/google/ui$image` on `www.google.pl`
solution: `||adservice.google.*^`
- search on `www.google.*` for the words "translator" appears "ads/measurement/t$image"
solution: `||www.google.com/ads/measurement/t`
- sometimes it will appear `id.google.pl/verify/` on `www.google.pl`
 solution: `||id.google.com/verify/` replace with `||id.google.*/verify/`

**Comment by monzta** [comment]
Was not able to find `/ads/measurement/` tho.

**Comment by AroKol78** [comment]
![jawidze01](https://github.com/easylist/easylist/assets/70756447/cebfe53c-c6a6-4340-8401-473be66f6b06)

**Comment by AroKol78** [comment]
why don't you block `clients5.google.com/pagead/drt/dn/` on `www.google.com/maps/...`?

**Comment by monzta** [comment]
@AroKol78 I cannot find this request there.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/bb6709aa73b30667016b1c795de08cf186f531e8

**Comment by AroKol78** [comment]
this top `pagead/` is not blocked by anything

![newadgo00](https://github.com/easylist/easylist/assets/70756447/ee0abe78-15e9-48b2-970a-f8ff34680688)

**Comment by Khrin** [comment]
Any steps on how to reproduce this, please?

**Comment by AroKol78** [comment]
> Any steps on how to reproduce this, please?

I go to the main G website and search for something, maybe I'm participating in some AB tests if you don't see it, these things appeared a few days ago

**Comment by Yuki2718** [comment]
@AroKol78 Can you provide the full url of the unblocked request?

**Comment by AroKol78** [comment]
```
www.google.com/pagead/1p-conversion/1[.1.]0/?gad_source=1&adview_type=4&adview_query_id=C[.2.]A
www.googleadservices.com/pagead/conversion/1[.1.]0/?gad_source=1&adview_type=1&adview_query_id=C[.2.]A
```
`[.1.]` - the same long numbers in both request 
`[.2.]` - the same long random string in both requests

> And your enabled filter lists?

I checked the default lists and the same effect

**Comment by Yuki2718** [comment]
> ```
> www.google.com/pagead/1p-conversion/1[.1.]0/?gad_source=1&adview_type=4&adview_query_id=C[.2.]A
> www.googleadservices.com/pagead/conversion/1[.1.]0/?gad_source=1&adview_type=1&adview_query_id=C[.2.]A
> ```
> 

We want to check the url but can't with these substitution.

**Comment by AroKol78** [comment]
```
https://www.googleadservices.com/pagead/conversion/16521530460/?gad_source=1&adview_type=1&adview_query_id=CNXm0-i5i4cDFde1aAkdIAcFgg
https://www.google.com/pagead/1p-conversion/16521530460/?gad_source=1&adview_type=4&adview_query_id=CNXm0-i5i4cDFde1aAkdIAcFgg
```

`adview_query_id=` it is different each time, e.g. after reloading the page

**Comment by Yuki2718** [comment]
Both of them are empty on my end.

**Comment by Yuki2718** [comment]
Reproduced and fixed
