### ISSUE TITLE
bezpiecznedane.gov.pl

### ISSUE THREAD

**Issue by xfix** [easylist/easylist#17874]
#### List the website(s) you're having issues with:

`https://bezpiecznedane.gov.pl/`

#### What happens?

When visiting the website with EasyList Cookie Notices list, the cookie banner doesn't show, but nothing could be interacted with. Body element has `overflow: hidden` set, and there are `ngb-modal-backdrop` and `ngb-modal-window` elements for what is supposed to be a cookie banner.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/1297598/f7acd91e-029e-435c-8b74-991dd0d5311a)

The cursor doesn't show that a link can be interacted with.

#### Filter lists you're using:

uBlock filters, EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe’s Ad and tracking server list, EasyList – Cookie Notices,  pl: Oficjalne Polskie Filtry do uBlocka Origin

#### Your settings:

- OS/version: NixOS 23.05
- Browser/version: 120.0
- Ad block extension/version: uBlock Origin 1.53.0

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20955

**Comment by gwarser** [comment]
Page was in news, will be lovely if you fix it ASAP.

**Comment by krystian3w** [comment]
Same bug may have IDCaC /FYI @kiboke
