### ISSUE TITLE
thewire.in

### ISSUE THREAD

**Issue by anxiouslelimo** [easylist/easylist#17894]
#### List the website(s) you're having issues with:
`thewire.in`

#### What happens?
If easyprivacy is enabled, on scrolling, the webpage becomes blank  for a few seconds.

Easylist, Easyprivacy

#### Your settings:
Built in adblocker - vivaldi
built in adblocker - cromite

Disabling easyprivacy_trackingservers.txt resolves the issue.

**Comment by ryanbr** [comment]
Can you test in ABP , uBO or Brave instead of the builtin adblockers  here

**Comment by Khrin** [comment]
Impossible to reproduce then.
