### ISSUE TITLE
Samsung.com

### ISSUE THREAD

**Issue by jordanswrld94** [easylist/easylist#17901]
https://samsung.com/us/web/internal/logger
https://www.samsung.com/us/api/v1/bridge/bridge-data/log
https://configurator.ecom-mobile-samsung.com/api/logger

Source:
https://www.samsung.com/us/watches/galaxy-watch6/buy/?modelCode=SM-R950NZKDXAA

**Comment by Daxy7** [comment]
found similar fingerprinter on `waitrose.com`
using regex on it pretty unlikely then
```
https://www.waitrose.com/ecom/shop/browse/groceries
```
```
​https://www.waitrose.com/gDaVC7/4lZvy/mOi9h/SQ/1rbOSLJcDktY/TkcnSwE/K1/d4VQIzA3UB
```
