### ISSUE TITLE
phpbb.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#17907]
#### List the website(s) you're having issues with:
`https://www.phpbb.com/`

#### What happens?
ads for webhosting companies right above the footer (links)

#### Filter lists you're using:
uBO default

#### Your settings:

- OS/version: Windows 11
- Browser/version: Brave
- Ad block extension/version: uBlock Origin 1.53.0

**Comment by azgaresncf** [comment]
on the right:
![image](https://github.com/easylist/easylist/assets/50982832/6c7379b6-2971-422e-af1f-67c88ad55381)
`##.mini-panel` or `##.sidebar` if you want to get rid of all the things in the sidebar

on the footer:
![image](https://github.com/easylist/easylist/assets/50982832/c2dc60e9-d55b-43e6-aa84-31e1fb7f4f47)
`###page-footer > h3 `and `##.lynkorama`
