### ISSUE TITLE
betterhelp.com: cookie notice

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#17914]
#### List the website(s) you're having issues with:

`https://www.betterhelp.com/advice`

#### What happens?

Cookie notice

#### Screenshot(s) 

![Screenshot 2023-12-02 at 02-07-12 BetterHelp Editorial Team Bio(1)](https://github.com/easylist/easylist/assets/52135169/62e80d91-a7d4-4587-a877-ba7e32c6ef24)

#### Filter lists you're using:

uBlock filters, EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe's Ad and tracking server list, EasyList Annoyances, uBlock Annoyances, Liste AR

#### Your settings:

- OS/version: macOS Ventura 13.0
- Browser/version: Firefox 120.0.1
- Ad block extension/version: uBlock Origin 1.54.0

**Comment by Yuki2718** [comment]
No.

**Comment by Yuki2718** [comment]
Probably
