### ISSUE TITLE
grupoemidia.com.br

### ISSUE THREAD

**Issue by adranger** [easylist/easylist#1791]
### List the website(s) you're having issues:

The `grupoemidia.com.br` ad network is not blocked.

Example page: `https://tribunademinas.com.br/noticias/politica/06-09-2018/fotografo-da-tribuna-e-agredido-no-atentado-a-bolsonaro.html`

### List Subscriptions you're using:

EasyList+EasyPrivacy

### Your settings

- Browser/version: Firefox 62.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.16.20

**Comment by Khrin** [comment]
EasyList blocks ads only from websites in English-language.
