### ISSUE TITLE
www.thespruce.com

### ISSUE THREAD

**Issue by timur-davletshin** [easylist/easylist#17915]
`https://www.thespruce.com/grow-bamboo-inside-1902611`

Easylist filter from Ublock Origin hides almost all header of all articles on `www.thespruce.com`. Disabling Easylist and enabling Adguard fixes the issue which makes me believe that the issue is in Easylist filter.

OS: Debian, Firefox 120 + Ublock Origin 1.54 (Easylist + EasyPrivacy filters enabled).

**Comment by Omega-6** [comment]
```
thespurce.com#@#.mntl-leaderboard-spacer
thespruce.com##.mntl-leaderboard-spacer:style(min-height: 0px !important;)
```

**Comment by timur-davletshin** [comment]
> For uBlock Origin: enable EasyList & update your filter lists in 5-10 minutes

Works for me now. Thank you for this quick fix!

**Comment by Omega-6** [comment]
@Yuki2718 @timur-davletshin @ryanbr reopen if not fixed
