### ISSUE TITLE
aida cookie

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#17935]
<details>
<summary>Screenshot(s)</summary>

![aida](https://github.com/easylist/easylist/assets/20126984/bfe62db4-3cff-4255-b89e-ac2b9e87cb00)

</details>

Example: `https://aida64.hu/`, `https://aida64.co.uk/`, `https://aida64.it/`, `https://aida64russia.com/`, `https://aida64.de/`, `https://aida64.com.ua/`

See also: https://github.com/easylist/ruadlist/commit/42f34d5011e136e160a0dad56d51dcb2bd3e0b55
And for the touchpad: https://github.com/easylist/ruadlist/commit/4559c6ce14e35c8a88891c7e259d947a1fbefc03

**Comment by dportvine** [comment]
Or you can add:
```Adblock
aida64.co.uk,aida64.com.ua,aida64.de,aida64.hu,aida64.it,aida64russia.com##+js(set-local-storage-item, set_cookie_stat, false)
aida64.co.uk,aida64.com.ua,aida64.de,aida64.hu,aida64.it,aida64russia.com##+js(set-local-storage-item, set_cookie_tracking, false)
```

**Comment by dportvine** [comment]
Fixed https://github.com/easylist/easylist/commit/cec0a17cc69b4487386a0c9647f9dc8d5f9ee61d
