### ISSUE TITLE
edition.cnn.com: detection (EasyList Cookie)

### ISSUE THREAD

**Issue by Omega-6** [easylist/easylist#17937]
![image](https://github.com/easylist/easylist/assets/152656980/d3deec12-1145-4d0c-8555-8bcf6ce118cf)

```
edition.cnn.com#@##onetrust-consent-sdk
```

**Comment by Omega-6** [comment]
`https://edition.cnn.com/`

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/commit/29ccd48dbed9b603547e00ec0d42ea856e8f6f81

**Comment by Omega-6** [comment]
https://github.com/easylist/easylist/commit/5a64edc0789aa9db02a65d6875b404f0785141ce
