### ISSUE TITLE
Awarding the best AdGuard contributors in 2023

### ISSUE THREAD

**Issue by SeverAnna** [easylist/easylist#17951]
Hello, @peace2000!

My name is Anna, I’m a content manager at AdGuard. We are contacting contributors so that we can send gifts to those who help a lot. Could you contact me to discuss the details? My email is [a.koroleva@adguard.com](mailto:a.koroleva@adguard.com).

**Comment by peace2000** [comment]
Hello, I sent you a email just a moment ago. I put this code into my email:

`8KAHNR4E`
