### ISSUE TITLE
https://itsfoss.com

### ISSUE THREAD

**Issue by sivajipro** [easylist/easylist#17971]
#### List the website(s) you're having issues with:

[https://itsfoss.com](https://itsfoss.com)

#### What happens?

Membership button. Annoyances

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/46227270/06d2d384-1253-4d4e-a79d-81d0cb981c9f)

![image](https://github.com/easylist/easylist/assets/46227270/6bd79d9b-745d-44be-a5e9-55e353906ea7)

#### Filter lists you're using:

EasyList, EasyPrivacy, Fanboy's Annoyance List

#### Your settings:

- OS/version: Solus Linux
- Browser/version: Vivaldi 6.4
- Ad block extension/version: Ublock Origin

**Comment by azgaresncf** [comment]
###ghost-portal-root

**Comment by Linxgos** [comment]
Already blocked for me by `itsfoss.com##.gh-portal-triggerbtn-iframe` in [Adguard filterlist](https://github.com/AdguardTeam/AdguardFilters/blob/3c1ff55e6c0ce214e3aa1f7f0b4028f4b6ed88a6/AnnoyancesFilter/Other/sections/self-promo.txt#L1950)
