### ISSUE TITLE
[EasyPrivacy] amiunique.org

### ISSUE THREAD

**Issue by ehyoitsdavid** [easylist/easylist#17978]
#### List the website(s) you're having issues with:
`https://amiunique.org`

#### What happens?
Tracking scripts load regardless of user action 
Even if the users don't click anything they still track you anyway.
Using various obfuscated Javascript to evade Easylist detection.

#### Screenshot(s) 
![Screenshot 2023-12-10 at 1 40 46 PM](https://github.com/easylist/easylist/assets/106898439/9a148181-5cb6-4bfb-880e-cda0b53fa240)

#### Filter lists you're using:
Easylist
EasyPrivacy
All uBlock filters

#### Your settings:

- OS/version: MacOS Sonoma 14.1.2 
- Browser/version: Firefox Nightly 122.0a1 (2023-12-10)
- Ad block extension/version: uBlock Origin 1.54.1b9

#### Other details:

Suggestions:
~~`||amiunique.org/advert.js`~~

`||amiunique.org/PluginDetectAll.js`
`||amiunique.org/fingerprint`

or even `||amiunqiue.org^doc`

They state that they will store the fingerprint collected on their servers and will put a cookie on the browser for a period of 4 months, and have very vague privacy policy.

They have also split the tracking scripts into several scripts as shown in the screenshot. This is completely malicious and intentional

**Comment by Sonic5435325** [comment]
I think `amiunique.org/advert.js` is just anti-AdBlock bait

**Comment by Khrin** [comment]
@ehyoitsdavid https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_specific.txt#L79
