### ISSUE TITLE
amoledo.com

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#17987]
### List the website(s) you're having issues:

`https://amoledo.com/en/news/2995-us-dollar-rises-against-yen-stable-against-euro-and-pound-central-bank-meeting`

### What happens?

Ad banner

<details>
<summary>Screen</summary>

![2023-12-11_173442](https://github.com/easylist/easylist/assets/111344219/f74baf74-1d82-44b7-8e9a-2eac9f7f7995)
![2023-12-11_173457](https://github.com/easylist/easylist/assets/111344219/6530fbb6-1ab2-498a-b109-7bbcf17774c4)
![2023-12-11_173520](https://github.com/easylist/easylist/assets/111344219/001aeae2-9680-4526-b16e-ae735ca8be56)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome (stable)
- Adblock Extension/version:  uBO (stable)

**Comment by azgaresncf** [comment]
just get rid of ```##.header-up```
