### ISSUE TITLE
fdownloader.net

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#17988]
### List the website(s) you're having issues:

`https://fdownloader.net/`

### What happens?

Leftover. Go to `https://fdownloader.net/` paste `https://www.facebook.com/NASA/videos/this-week-nasa/711678027593724/` & click download twice

<details>
<summary>Screen</summary>

![2023-12-11_180440](https://github.com/easylist/easylist/assets/111344219/ff5f2929-eb41-4a23-b863-fbfadf6d4d1f)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome (stable)
- Adblock Extension/version:  uBO (stable)

**Comment by azgaresncf** [comment]
get rid of the ```##.modal```

**Comment by dportvine** [comment]
Up!

**Comment by dportvine** [comment]
Fixed https://github.com/uBlockOrigin/uAssets/commit/2e26ca41c7e4862f1aa25a7674cbb2ce45ca9235
