### ISSUE TITLE
can't scroll on rowevetgroup.com (Easylist Cookie)

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#17995]
#### List the website(s) you're having issues with:
`https://www.rowevetgroup.com/pet-health-club`

#### What happens?
Hiding the cookie banner prevents scrolling on the page.

**Comment by azgaresncf** [comment]
![image](https://github.com/easylist/easylist/assets/50982832/789296c7-a262-4d8c-b142-19b22e193368)
either remove the class property (replace noscroll with scroll for example) or remove the property entirely or
modify the body.noscroll
![image](https://github.com/easylist/easylist/assets/50982832/845b0714-3ee5-4daa-8ac6-d8349349bc1a)

**Comment by yokoffing** [comment]
@partingscientist I am not on the same computer, but I am using uBO with the same filter lists on Firefox, and I am able to scroll now.
