### ISSUE TITLE
g2.com chat widget

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#17993]
#### List the website(s) you're having issues with:
https://www.g2.com/products/foxyproxy/reviews

#### What happens?
Chat widget

#### Screenshot(s) 
![Screenshot 2023-12-12 at 14-21-39 The G2 on FoxyProxy](https://github.com/easylist/easylist/assets/101707608/475411db-4278-48e8-a924-20bea024a8f4)

#### Filter lists you're using:
All filters offered by uBO

#### Your settings:

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 115.5.0esr
- Ad block extension/version: uBlock Origin 1.54.0

**Comment by DimitrisKalaboukas** [comment]
Suggested filter:

g2.com##.g2-ai-chat-initial

**Comment by DimitrisKalaboukas** [comment]
@jellizaveta ?

**Comment by jellizaveta** [comment]
@DimitrisKalaboukas added a rule to the AdGuard Annoyances filter, the chat icon in the menu will not be hidden, as the chat function should not be blocked completely
