### ISSUE TITLE
https://malighting.com

### ISSUE THREAD

**Issue by MicaelJarniac** [easylist/easylist#17991]
#### List the website(s) you're having issues with:

`https://www.malighting.com/special/grandma3-software/`

#### What happens?

Can't scroll or properly interact with the web page.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/19514231/13248d33-1020-4101-9c13-bfab07f4b070)

This cookie notice has to be accepted but is only visible upon disabling the filters.

#### Filter lists you're using:

EasyList Cookie Notices

#### Your settings:

- OS/version: Ubuntu 23.10
- Browser/version: Firefox 120.0.1 (64-bit)
- Ad block extension/version: uBlock Origin 1.54.0

#### Other details:

This issue is likely caused because of not being able to accept the cookies notice. The filter hides the notice but doesn't accept it. By disabling this filter and accepting the notice, the website works normally again. I can then re-enable the filter and keep using the website normally.

**Comment by azgaresncf** [comment]
for me, the window doesn't show up (but i've got other filters enabled), but I can not scroll in the page
so either remove the .cs_cookie-open div or modify it (change from hidden to visible !important;)
![image](https://github.com/easylist/easylist/assets/50982832/d0af9de8-79a3-4714-bc4b-3ba709c34ec0)

**Comment by MicaelJarniac** [comment]
> for me, the window doesn't show up (but i've got other filters enabled), but I can not scroll in the page so either remove the .cs_cookie-open div or modify it (change from hidden to visible !important;) ![image](https://private-user-images.githubusercontent.com/50982832/289981060-d0af9de8-79a3-4714-bc4b-3ba709c34ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MTI1OTIsIm5iZiI6MTcwMjQxMjI5MiwicGF0aCI6Ii81MDk4MjgzMi8yODk5ODEwNjAtZDBhZjlkZTgtNzlhMy00NzE0LWJjNGItM2JhNzA5YzM0ZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDIwMTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZWMyYzI5MWRhMTFjMzZkODEzZDJlOTI1OThhYzE0ZTdlOGYzZmJhOGI4M2MzMTJhMzA3MmUwMzlkZmQyNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WoZ7XbSaCEaApDna0IcfsXmt7rDSTcH8psB2gy-zcfE)

That's also what happens for me. The notice does not show up with the filter enabled, so I have to disable the filter to see and accept the notice so that the website works.

**Comment by Sonic5435325** [comment]
Also a "Scroll to top" annoyance
`malighting.com##.scroll-to-top`
![Screenshot from 2023-12-25 20-37-16](https://github.com/easylist/easylist/assets/89158249/cde09d6c-82a1-4d27-b434-d19a06bce42d)
