### ISSUE TITLE
skroutz.gr: Chat feature blocked by EasyList Other Annoyances

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#18010]
#### List the website(s) you're having issues with:

`https://www.skroutz.gr/`

#### What happens?

When you try to contact Skroutz via live chat, it is being blocked completely by EasyList's Other Annoyances filter.

#### Screenshot(s) 

![Screenshot from 2023-12-14 18-08-11](https://github.com/easylist/easylist/assets/123986260/44c12d0d-5735-414f-bc0c-f5f25c65004c)

#### Filter lists you're using:

EasyList - Other Annoyances

#### Your settings:

- OS/version: Fedora Silverblue 39
- Browser/version: Firefox 120.0.1
- Ad block extension/version: uBlock Origin 1.54

#### Other details:

According to the uBlock Origin's logger, this is what is being blocked: `https://static.zdassets.com/ekr/snippet.js?key=`

**Comment by Sonic5435325** [comment]
EasyList blocks live chat annoyances, it's intentional.

**Comment by Khrin** [comment]
> Yes, but this isn't an annoyance. You navigate to the support page and access a specific hidden menu. From there, you tap the chat feature, and then, it's ready for use. It's not a pop-up or anything intrusive.

@PhoenixFossGR Feel free to ignore what he says: "EasyList" has never intentionally blocked chat widgets.
