### ISSUE TITLE
Google Play Games: Cookie banner

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#18012]
#### List the website(s) you're having issues with:

`https://play.google.com/googleplaygames`

#### What happens?

There is a cookie notice at the bottom of the website, and it's not being blocked.

#### Screenshot(s) 

![Screenshot from 2023-12-14 22-07-43](https://github.com/easylist/easylist/assets/123986260/0389c1ea-8128-4498-888a-e5b710d716a3)

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: Fedora Silverblue 39
- Browser/version: Firefox 120.0.1
- Ad block extension/version: uBlock Origin 1.54

**Comment by Linxgos** [comment]
Does `||www.gstatic.com/glue/cookienotificationbar/*` fix it?
