### ISSUE TITLE
cnet.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18024]
**Annoyance**

- https://i.imgur.com/OI5AlIN.png

```adblock
cnet.com##.c-adShoppingExit_modal
```
- A: `https://download.cnet.com/audio-music-management/windows/`

**Comment by azgaresncf** [comment]
also checking `##.c-adSkyBox`
![image](https://github.com/easylist/easylist/assets/50982832/72920566-f277-4537-80fc-2ea2c3cedf12)
