### ISSUE TITLE
blacksim.de (Easylist Cookie)

### ISSUE THREAD

**Issue by SamsonNosmas** [easylist/easylist#18049]
#### List the website(s) you're having issues with:

https://www.blacksim.de/

#### What happens?

Cookie consent needs blocking

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by azgaresncf** [comment]
`||https://tags.tiqcdn.com/utag/drillisch/cybersim.de/prod/utag.js$script,important`
