### ISSUE TITLE
legifrance.gouv.fr

### ISSUE THREAD

**Issue by louisroyer** [easylist/easylist#18058]
#### List the website(s) you're having issues with:
`https://www.legifrance.gouv.fr/cnil/id/CNILTEXT000048580096`

#### What happens?
1. Visit the given link with "EasyList – Cookie Notices" disabled: the document "Délibération SAN-2023-018 du 12 décembre 2023" is well displayed.
2. Enable "EasyList – Cookie Notices" and reload: the document is no longer displayed

#### Screenshot(s) 
"EasyList – Cookie Notices" disabled:
!["EasyList – Cookie Notices" disabled](https://github.com/easylist/easylist/assets/55180044/62e6c7a2-f9cb-4a16-ac1c-ff7a106369fd)
"EasyList – Cookie Notices" enabled:
!["EasyList – Cookie Notices" enabled](https://github.com/easylist/easylist/assets/55180044/84cfeca2-2115-49b0-9263-4d3dc3b974e8)

#### Filter lists you're using:
None except "EasyList – Cookie Notices", and including custom filters.

#### Your settings:

- OS/version:  Debian 12.4
- Browser/version: Firefox 115.5.0esr
- Ad block extension/version:  uBlock Origin 1.54.0

**Comment by Sonic5435325** [comment]
Read https://github.com/easylist/easylist/issues/14992

**Comment by louisroyer** [comment]
oh, I see… this is because this text is a CNIL decision and the div has a `cnil` class. But legifrance is the official website of the french gouvernement where CNIL decisions are published.
The blocked content is the main content of the website. This is not a cookie/GDPR warning/notice or a privacy policy, and is out of the scope of the list. Could we consider adding this to the allowlist?
