### ISSUE TITLE
Infowars.com

### ISSUE THREAD

**Issue by DominionDefense** [easylist/easylist#1805]
Please do not use easylist as a weapon against political opposition.  It discredits it's legitimacy and ruin it's reputation.

**Comment by ryanbr** [comment]
You can discuss your conspiracy theories with others on another planet.

**Comment by DominionDefense** [comment]
So you have no arguments for your decision, and I am correct in my assumptions?  Hence the emotional child like insults because you feel shame when confronted with the truth.

**Comment by DominionDefense** [comment]
The only people who censor (or use violence) are those without arguments.  If you and others like you had valid arguments for your beliefs you would simply engage in the court of public opinion, make your arguments, and people would stop supporting Infowars to the point they could not stay in operation.  A basic principal of a functioning healthy democracy, which you and others like you are mocking and laughing at.
