### ISSUE TITLE
teksavvy.com cookie

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#18057]
`https://www.teksavvy.com/`

<details>
<summary>Screenshot(s)</summary>

![tcavi](https://github.com/easylist/easylist/assets/20126984/2bebe0a5-a25f-4a33-805c-640fac112085)

</details>

`teksavvy.com###cc--main`

**Comment by Sonic5435325** [comment]
Newsletter:
`teksavvy.com##.btn-newsletter`
`teksavvy.com###newsletter-desc`
![Screenshot from 2023-12-25 17-02-38](https://github.com/easylist/easylist/assets/89158249/5bd51f64-8b48-4d06-9dab-178784040065)
