### ISSUE TITLE
videoconverterfactory.com ads

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#18059]
#### List the website(s) you're having issues with:
https://www.videoconverterfactory.com/tips/vlc-normalize-volume.html

#### What happens?
Interfering promo notices

#### Screenshot(s) 
![Screenshot 2023-12-19 at 14-23-17 How to Normalize Volume in VLC Media Player](https://github.com/easylist/easylist/assets/101707608/32b4fd87-9976-42ae-aaed-ceadc07e68b8)

![Screenshot 2023-12-19 at 14-23-43 How to Normalize Volume in VLC Media Player](https://github.com/easylist/easylist/assets/101707608/b01b24c3-1983-48f3-9511-7c7eb03c8f9e)

![Screenshot 2023-12-19 at 14-24-07 How to Normalize Volume in VLC Media Player](https://github.com/easylist/easylist/assets/101707608/c15edbcb-f722-4b64-af5b-c3cf4134dff2)

#### Filter lists you're using:
All filters offered by uBO

#### Your settings:

- OS/version: Windows 7 32bit SP1
- Browser/version: Mozilla Firefox 115.5.0esr
- Ad block extension/version: uBlock Origin 1.54.0

**Comment by DimitrisKalaboukas** [comment]
@mapx- ?

**Comment by Khrin** [comment]
seems to be just self-promotion, nothing worth blocking in easylist
