### ISSUE TITLE
cybersim.de (Easylist Cookie)

### ISSUE THREAD

**Issue by SamsonNosmas** [easylist/easylist#18050]
#### List the website(s) you're having issues with:

https://www.cybersim.de/

#### What happens?

Cookie consent needs blocking

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by azgaresncf** [comment]
||https://tags.tiqcdn.com/utag/drillisch/cybersim.de/prod/utag.js$script,important
