### ISSUE TITLE
Breakage: Some Korean websites

### ISSUE THREAD

**Issue by thonfive4** [easylist/easylist#18064]
#### List the website(s) you're having issues with:

https://m.ygosu.com
https://m.inven.co.kr
https://dogdrip.net

#### What happens?

Website's loaded well at first, but after 10~20s passed, it suddenly broken.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/151705669/45816a75-12df-4a42-99fc-970302ff3966)

#### Filter lists you're using:

EasyList
EasyPrivacy

I read that AdGuard Base Filter is including the EasyList, so I assume that I'm using EasyList filter.

#### Your settings:

- OS/version: iOS 17.1.2
- Browser/version: Mobile Safari 17
- Ad block extension/version: AdGuard

#### Other details:

https://github.com/easylist/easylist/blob/93244159fa3b95b7faeee81a4cfe6219ae2dcd12/easylist/easylist_adservers_popup.txt#L742

I tried debugging my Safari browser, and found that `$popup` filter works differently in Mobile Safari browser.
https://adguard.com/kb/general/ad-filtering/create-own-filters/#popup-modifier

I think they can detect whether their domains have blocked, so it would be better to use other methods to block the popup window with those domain.

**Comment by piquark6046** [comment]
Please install https://github.com/List-KR/microShield.
For its installation guide written in Korean language, please refer https://community.list-kr.com/docs/AdGuard/Userscripts/microShield.
