### ISSUE TITLE
paste.fo Filters Destructive

### ISSUE THREAD

**Issue by verybigwave** [easylist/easylist#18063]
#### List the website(s) you're having issues with:
paste.fo

#### What happens?
The easylist filter added by https://github.com/easylist/easylist/commit/442c0b64dc9c5ffa9d468810b70c41225c47a96f is destructive by completely removing external links. It for example removes some of the users contacts linked on their profiles, and not just the ads it should remove.

#### Screenshot(s)
The destructive behavior includes breaking these contact fields among other links not really working when being clicked:
<img src="https://i.ibb.co/nkB4sJw/img.png">

#### Filter lists you're using:
UBO with EasyList

#### Your settings:

- OS/version: Windows 11
- Browser/version:  Firefox Latest
- Ad block extension/version:  UBO Latest

#### Other details:
The filter for all target="_blank" anchor tags added in https://github.com/easylist/easylist/commit/442c0b64dc9c5ffa9d468810b70c41225c47a96f

**Comment by Daxy7** [comment]
For the ads:
```
paste.fo##.easylist_is_shit_fuck_huyszn
! invalid
paste.fo##.texta
paste.fo##.wrapper a[href][target="_blank"] 
```
