### ISSUE TITLE
linuxliteos.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#18076]
#### List the website(s) you're having issues with:

`https://www.linuxliteos.com/index.html`

#### What happens?
Ad leftover

#### Screenshot(s) 

![Screenshot from 2023-12-20 21-03-53](https://github.com/easylist/easylist/assets/89158249/2ecc0cf2-c182-4a03-88d1-3b0b96f9e135)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by ryanbr** [comment]
Probably not worth
