### ISSUE TITLE
(NSFW) xHamster.com: Cookie notice

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#18091]
#### List the website(s) you're having issues with:

(NSFW) `https://xhamster.com/`

#### What happens?

There is a large cookie notice at the bottom of the screen

#### Screenshot(s) 

![Screenshot from 2023-12-23 19-52-40](https://github.com/easylist/easylist/assets/123986260/f337ae56-e977-4b2d-ad1a-9c5d2a234472)

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: Fedora Silverblue 39
- Browser/version: Firefox 121
- Ad block extension/version: uBlock Origin 1.54

**Comment by Khrin** [comment]
@PhoenixFossGR Please check your filter lists. It is correctly blocked.
