### ISSUE TITLE
Website broken: thephoblographer.com

### ISSUE THREAD

**Issue by Cannoli13** [easylist/easylist#18123]
#### List the website(s) you're having issues with:

https://www.thephoblographer.com/

#### What happens?

Website stops loading when AdGuard with EasyList filter activated and then it's broken after a few seconds

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/155059613/631b3c63-b249-440e-ba77-4b7329b8fb3d)

#### Filter lists you're using:

EasyList
EasyPrivacy

#### Your settings:

- OS/version: iOS 17.1.2
- Browser/version: Mobile Safari 17
- Ad block extension/version: AdGuard

#### Other details:

It only occurs in iOS Safari browsers.

**Comment by piquark6046** [comment]
Please install https://github.com/List-KR/microShield.
