### ISSUE TITLE
honkailab.com breakage (ios / safari / adguard)

### ISSUE THREAD

**Issue by ads-cutter** [easylist/easylist#18125]
#### List the website(s) you're having issues with:
 - https://honkailab.com/

#### What happens?
I am building an adblock project by adding easylist to the project. But for some reason, the website only appears broken on iOS Safari. After looking into it, it seems to be happening because a specific domain is blocked. When I look at the site's network request, I suspect that it is because a certain domain is being blocked. Please update the ios safari filter.

#### Screenshot(s) 
![image](https://github.com/easylist/easylist/assets/151490209/489ab09d-d168-4b82-8bb1-ee83100a2b35)

#### Your settings:

- OS/version: ios / 17.2.1
- Browser/version: safari
- Ad block extension/version: adguard

#### Other details:

I think easylist's pop up block filter so that is problem. in ios safari pop up block filter is block ads the iframe.

**Comment by Daxy7** [comment]
If you're using adguard and easylist filters together, disable at least one of them.

**Comment by max-adblock** [comment]
simillar issue: #18126

**Comment by max-adblock** [comment]
i have reproduced same issue when i only activate easylist filter. find out details at https://github.com/easylist/easylist/issues/18127

@Daxy7

**Comment by Daxy7** [comment]
add this in 'my filters':
```
@@||content-loader.com^$domain=honkailab.com|loawa.com
@@||html-load.com^$domain=honkaliab.com|loawa.com
```

**Comment by max-adblock** [comment]
I have already excluded it from my filters. However, since we and other adblocks use easylist as the base filter, it's cumbersome to manually search and exclude one by one each time. Wouldn't it be more appropriate to remove the problematic filter from the base filter? @Daxy7

**Comment by max-adblock** [comment]
I have created pull-request with some other improvements. @Daxy7 
https://github.com/easylist/easylist/pull/18130

**Comment by Khrin** [comment]
> add this in 'my filters': edit: faster method
> 
> ```
> ||07c225f3.online^badfilter
> ||content-loader.com^$badfilter
> ||html-load.com^$badfilter
> ```

These filters do not come from EasyList.
