### ISSUE TITLE
loawa.com - website loading failed

### ISSUE THREAD

**Issue by max-adblock** [easylist/easylist#18127]
#### List the website(s) you're having issues with:
- https://loawa.com/

#### What happens?
- website is broken after 15~20 seconds

#### Screenshot(s) 
![KakaoTalk_Photo_2023-12-28-18-20-10](https://github.com/easylist/easylist/assets/155061453/7686b8a2-856c-4927-816f-2c876e1bb72a)

#### Filter lists you're using:
- i have disabled all other filters
- i have activated only adblock

#### Your settings:
- It happens on iOS and macOS Safari browser

#### Other details:
- this issue is resolved when i remove following line
    - https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers_popup.txt#L2
- i can see similar issues on other website. i need to remove other lines to resolve similar issues from other websites.
    - https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers_popup.txt#L1508
    - https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers_popup.txt#L745
- considering that many adblock users are experiencing this problems. it would be greate if someone fix it quicly.

**Comment by Khrin** [comment]
With EL enabled, site loads fine.
