### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by kappa6969** [easylist/easylist#1813]
example:
https://shinden.pl/external-video/34898-yowamushi-pedal-grande-road/view/128643#column-one-inner
replacing "pokaż" (show) button by "Jak odblokować" (how to unlock) button, im using nanodefender + antiadblock killer and still not working

**Comment by krystian3w** [comment]
No fixed in MajkiIT list?

**Comment by krystian3w** [comment]
No fixed in [MajkiIT](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt&title=Official%20Polish%20filters%20for%20AdBlock,%20uBlock%20Origin%20and%20AdGuard) list?

```
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
```

**Comment by kappa6969** [comment]
fixed

**Comment by Castiell1986** [comment]
Hi there, from few days i got error on Shnden.pl

### List the website(s) you're having issues:
https://shinden.pl/epek/49615-one-punch-man-season-2/view/161242#column-one-inner



### What happens?
Player not working, there is error about  using adblock "jak odblokowować" ( how to unlock)


### List Subscriptions you're using:

uBlock filters​​​​​
uBlock filters – Badware risks​
uBlock filters – Privacy​​​​​
​​uBlock filters – Resource abuse​​​​​
​uBlock filters – Unbreak

EasyList
EasyPrivacy


### Your settings



- OS/version:  Win7 pro x64
- Browser/version:  Mozilla Firefiox 66.03
- Adblock Extension/version:  Ublock Origin 1.18.16
