### ISSUE TITLE
Atatus main site is being blocked

### ISSUE THREAD

**Issue by fizerkhan** [easylist/easylist#1814]
**List the website(s) you're having issues:**
www.atatus.com
app.atatus.com

**What happens?**
The main www.atatus.com and app.atatus.com is not rendered correctly because it is being blocked from the [easyprivacy_trackingservers.txt](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt)

**List Subscriptions you're using:**
easy privacy

**Your settings:**
Mac OS
Safari latest
uBlock Origin

**Other details:**
`atatus.com/*` is being blocked in [easyprivacy_trackingservers.txt](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt). This has issues with the main Atatus site. Could this be removed from [easyprivacy_trackingservers.txt](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt) in privacy and block just the domain `br-rx.atatus.com` which collect the privacy related payload. Without this, the main site is being blocked and one will not be able to use the service.

**Comment by sundarv85** [comment]
+1 Any update on this?

**Comment by Khrin** [comment]
Site just loads fine for me, what isn't loading correctly for you?

**Comment by sundarv85** [comment]
@Khrin When I open the site directly, then interestingly it doesn't seem to be an issue. However, when I open an error alert that I receive via email and when atatus.com is opening, it fails. See the attached images.

This is the screenshot of the uBlock Origin blocked elements
![screenshot 2018-10-11 at 08 12 29](https://user-images.githubusercontent.com/11090193/46784345-09b75680-cd2e-11e8-88c4-f386f8e50ec5.png)

This is the screenshot of the uBlock Origin Logger when I refresh that tab where Atatus is being blocked.
![screenshot 2018-10-11 at 08 15 20](https://user-images.githubusercontent.com/11090193/46784348-0d4add80-cd2e-11e8-87d8-00c649444f9d.png)

**Comment by sundarv85** [comment]
@Khrin did you get a chance to check this

**Comment by ryanbr** [comment]
Is there an actual site we can test?
