### ISSUE TITLE
[Social] Allow ##.social-media-link on twitch.tv

### ISSUE THREAD

**Issue by Freso** [easylist/easylist#18151]
#### List the website(s) you're having issues with:

`https://twitch.tv/`

Specifically on profiles, like `https://twitch.tv/freso`

#### What happens?

Profiles on Twitch have a section/box dedicated to social (or whatever, really) links to find them outside of Twitch. This box gets hidden by the generic [`##.social-media-link` rule in `fanboy_social_general_hide.txt`](https://github.com/easylist/easylist/blob/7f99fd081fc8c0bf449bb17764032c44553dc619/fanboy-addon/fanboy_social_general_hide.txt#L9264).

As I understand the description/purpose of this blocking list, it is for “the Facebook like button and other widgets”, not for genuine links to find someone on one site on other sites. (E.g., the profile links on Instagram, Twitter, etc. are not hidden by this block list which seem analogous to these.)

#### Screenshot(s) 

Compare hidden
![twitch-blocked](https://github.com/easylist/easylist/assets/177659/6f11ab88-7181-4761-89cb-a1f09cad888a)
with unhidden
![twitch-unblocked](https://github.com/easylist/easylist/assets/177659/88a2e5fd-e4d4-41df-ad6c-1c378181a33a)

#### Filter lists you're using:

Oh god, a lot. 😅 But I isolated this issue to “EasyList – Social Widgets” (Fanboy's Social Blocking List) both by disabling the specific rule mentioned above, but also by disabling the specific list in uBO.

<details><summary>Full list</summary>
<p>
But: all of uBO’s "built-in", "ads", "privacy", "malware protection, security" filters; "Dan Pollock’s hosts file"; all of the "AdGuard – Annoyances" and "EasyList – Annoyances" filters + "uBlock filters – Annoyances"; "Dandelion Sprouts nordiske filtre" and "Frellwit's Swedish Filter" and `https://pgl.yoyo.org/as/serverlist.php?hostformat=adblockplus&mimetype=plaintext`; and a few custom filter rules as well.
</p>
</details> 

#### Your settings:

- OS/version: Arch Linux latest
- Browser/version: Firefox 121.0
- Ad block extension/version: uBlock Origin 1.54.0

#### Other details:

It is caused by [`##.social-media-link` rule in `fanboy_social_general_hide.txt`](https://github.com/easylist/easylist/blob/7f99fd081fc8c0bf449bb17764032c44553dc619/fanboy-addon/fanboy_social_general_hide.txt#L9264). It would be alleviated/fixed by `twitch.tv#@#.social-media-link`, but I don’t know which file that would go in. [`fanboy_social_allowlist_general_hide.txt`](https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_social_allowlist_general_hide.txt) maybe?

**Comment by Freso** [comment]
Seems like it was fixed (by removing the `##.social-media-link` rule), so not sure why it was closed as invalid, but eh. Thanks. :)

**Comment by Lahe** [comment]
Seems like this was added back in `fanboy_social_specific_hide.txt` in 9dce8dd.

For anyone else ending up here, add `www.twitch.tv#@#.social-media-link` to your custom filters list to fix it.

More info:
https://github.com/gorhill/uBlock/wiki/DOM-inspector#creating-cosmetic-filter-exception
https://linkedlist.ch/overwrite_css_filters_in_ublock_origin_8/
