### ISSUE TITLE
lightnovelworld.com: popups

### ISSUE THREAD

**Issue by big-cat-loaf** [easylist/easylist#18153]
#### List the website(s) you're having issues with: https://www.lightnovelworld.com/

 https://www.lightnovelworld.com/

 

#### What happens?

 just open the website 
 #21703 (uBlockOrigin/uAssets/issues/21703) 

#### Screenshot(s) 

 
![Screenshot 2023-12-31 232001](https://github.com/easylist/easylist/assets/100969549/20ba2c2a-ab06-428e-a196-19899e75f72c)

#### Filter lists you're using:

 uBO
 all uBlock filters, all AdGuard filters, all EasyLists filters, (EasyPrivacy, EasyList... )

#### Your settings:

- OS/version: Windows 10, 22H2 
- Browser/version: Version 120.0.6099.129 (Official Build, ungoogled-chromium) (64-Bit)
- Ad block extension/version: uBlock Origin 1.54.0

#### Other details: The selfadvertise about the new app, and open a popup, every time you want to visite there website.

 
lightnovelworld.com##+js(nostif, lockWindow) or
lightnovelworld.com###lnwappmsg
lightnovelworld.com##html:style(overflow: auto !important;)

**Comment by BlazeFTL** [comment]
Just A Suggestions..Dont Use All Filters You See...Try To Use Default Filters+Annoyance Only...

**Comment by big-cat-loaf** [comment]
Thank you for your suggestion. I don't understand why I should not use many filters. I am advanced enough to know when a problem is with a filter using the Dom logger in uBO. The issue was only opened to make the filters public for other users. The filter that I suggested already works.

**Comment by BlazeFTL** [comment]
> understand why I should not use many filters

Its Known To Cause Breakage,Anti Adblock...

**Comment by big-cat-loaf** [comment]
Yes, I am well aware of this. I tested everything on a clean Google Chrome browser before with default filters before creating an issue, and I had never had any trouble with any filters except Adgard, which had the same dumm solution to problems, and I just figured the problem out and fixed it myself, but thanks for your concern.
