### ISSUE TITLE
content.dictionary.com

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#18165]
ad placeholders
```
https://content.dictionary.com/word-of-the-year-2023/
```
```
content.dictionary.com##.lp-code
```
https://github.com/easylist/easylist/assets/91396482/9061ce91-257d-4149-979d-0340d9a93753

**Comment by Daxy7** [comment]
still ad placeholders
```
content.dictionary.com##.lp-code
```
https://github.com/easylist/easylist/assets/91396482/cfb39a9b-88d2-4a04-81eb-a4fcad9ace5c

**Comment by Yuki2718** [comment]
EL or EP doesn't block anyclip video, it's something on your end blocking this.
