### ISSUE TITLE
teamplayergaming.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylist#18167]
#### List the website(s) you're having issues with:

`http://www.teamplayergaming.com/forum.php`

#### What happens?

Unhidden "advertisement" section on the site.

#### Screenshot(s) 

![Screenshot from 2024-01-02 16-53-20](https://github.com/easylist/easylist/assets/89158249/8e1d509a-a053-44d4-9439-dd203c96c5c1)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by Dani-1-2** [comment]
This works for me:
www.teamplayergaming.com##li:nth-of-type(2) > .smaller.block > .blocksubhead
www.teamplayergaming.com##li:nth-of-type(5) > .smaller.block > .blocksubhead
www.teamplayergaming.com##li:nth-of-type(5) > .smaller.block > .floatcontainer.blockbody.widget_content
www.teamplayergaming.com##li:nth-of-type(2) > .smaller.block > .floatcontainer.blockbody.widget_content

**Comment by Sonic5435325** [comment]
At the moment it seems like the website is gone, dunno if that'll change in the future or if it's gone for good
