### ISSUE TITLE
www.facebook.com overreach

### ISSUE THREAD

**Issue by filbo** [easylist/easylist#1818]
Expression:

`facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href*="utm_campaign"])`

from commit 7a3885f35f94921ed8767bb2a39db98d4ed27d49 is catching various sorts of posts bridged from other services, but which are not ads.

Here are two examples (FB login not required; there is a 'not now' dismiss button on the 'sign up for FB' splash page):

### List the website(s) you're having issues:

`https://www.facebook.com/estadao/posts/2766556760026035`
`https://www.facebook.com/Canyoncreekshibasrule/posts/2242347332660572`

### What happens?

These posts are vanished from the user's News Feed.  They are non-ad posts by 'pages' (FB non-personal account entities), using some sort of crossposting software from Twitter and/or Instagram.  (I assume it affects other crossposts as well.)

### List Subscriptions you're using:

This is in main Easylist

### Your settings

(none relevant to this issue)

- OS/version: Windows 7 Ultimate Edition
- Browser/version: Chrome 69.0.3497.92
- Adblock Extension/version: AdBlockPlus, current

### Other details:

commit 7a3885f35f94921ed8767bb2a39db98d4ed27d49

VERIFIED by turning off Easylist, noting that the posts do not vanish; pasting the single expression into Options > Advanced > My Filters List, noting that posts once again vanish.

**Comment by monzta** [comment]
The filter has been removed.
