### ISSUE TITLE
awswaf.com rules breaking web experience

### ISSUE THREAD

**Issue by xjhonny** [easylist/easylist#18186]
Hello. AWS SDK uses this URL to load some JS SDK functionality for CAPTCHA integration. The current rules are breaking this CAPTCHA widget so I have to turn off ublock when solving CAPTCHA. Is it possible to remove this rule?

Rules:
```
||awswaf.com^*/report
and maybe ||awswaf.com^*/telemetry
```

**Comment by Daxy7** [comment]
try this, add in 'my filters', also report the domain[s] in which the issue in occuring
```
||awswaf.com^*/report$badfilter
||awswaf.com^*/telemetry$badfilter
```
