### ISSUE TITLE
[Allow] community.ipinfo.io

### ISSUE THREAD

**Issue by abdullahdevrel** [easylist/easylist#18194]
#### List the website(s) you're having issues with:

`community.ipinfo.io`

#### What happens?

`ipinfo.io` service is blocked as a third-party API service by Easylist and this has been discussed in #2865.

This forum URL (`community.ipinfo.io`) in question is outside of IPinfo's services as a third-party service API service and is related to community and documentation of using the service.  The adblock mechanism itself entirely blocks access to the website. The forum is hosted using Discourse.

Considering this, I am requesting to allow `community.ipinfo.io` in the EasyPrivacy list.

#### Reproduction of the issue

This happens only during **redirection**, particularly from social media shares. It can also be replicated through URL expansion when the links to `community.ipinfo.io` are shared through a shortened URL, especially from social media.

Consider the shortened URL `https://t.co/JJ0ETzNHSu` which comes from Twitter and expands to `https://community.ipinfo.io/t/preventing-credential-stuffing-attacks-with-ipinfo/1201`. When you visit the link, the following might happen.

https://github.com/easylist/easylist/assets/111275753/d28b431a-a5ee-4710-9f89-2f22149ca629

The behavior is peculiar because the redirection is getting blocked on `3p` (Third Party) ruleset, even though `3p`  should not affect subdomains of the same URL.

![image](https://github.com/easylist/easylist/assets/111275753/07685075-30bc-4b59-942a-2e5cc3281ce9)

![msedge_gfN2cGYzQC](https://github.com/easylist/easylist/assets/111275753/c3deef17-9b52-4131-ae7b-e382a67604bb)

Another interesting aspect to note even though redirection is being blocked (which it shouldn't be), subsequent background requests to the platform are going through, which indicates that adblocking mechanism could not be able to filter these background requests.

AdGuard themselves addressed a similar issue, so this could be an issue on the adblocking software level.

https://github.com/AdguardTeam/CoreLibs/issues/1637

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/111275753/d0359825-9422-4460-99ec-4ffecb28d543)

![image](https://github.com/easylist/easylist/assets/111275753/cc173c04-7ceb-41ea-bc8a-02addd066842)

#### Filter lists you're using:

EasyPrivacy via uBlock Origin

#### Your settings:

- OS/version:  Windows 11
- Browser/version:  Microsoft Edge Version 120.0.2210.91 
- Ad block extension/version: uBlock Origin 1.54.0

**Comment by Yuki2718** [comment]
What? The rule is applied only to 3p and thus there's no blocking on `community.ipinfo.io`. Your screenshots it is blocked on `t.co`, which I don't see at all and you didn't provide steps to reproduce.

**Comment by abdullahdevrel** [comment]
@Yuki2718 I am sorry. I have provided the issue reproduction steps on the ticket.

>  The rule is applied only to 3p and thus there's no blocking on community.ipinfo.io

However, thanks to your comment, I think I have a hunch of what's going on. This might be an issue at the adblock software level.

uBlock Origin could be filtering `3p` requests, even when they are directed to the same subdomain, during URL redirection. This is quite interesting, and you might notice more things in the video.

If you can let me know what you think, that would be awesome. I will move forward with opening tickets with uBlock Origin.

**Comment by Yuki2718** [comment]
I can't reproduce with `https://t.co/JJ0ETzNHSu`. The linked AG issue was very old and seems already fixed.

**Comment by abdullahdevrel** [comment]
@Yuki2718 Reproduction of this issue is quite unpredictable. I am not sure what variables impact this issue

Check this out:

https://github.com/easylist/easylist/assets/111275753/dbc5c401-7148-4dd2-a428-79ac8f053012

On the left, I have a standard browser session. On the right, I have incognito mode session. In both instances, the uBlock origin is activated. In the standard browsing session, the request gets blocked, but in incognito, the request passes through.

Log output from the standard browsing operation (latest to oldest up to 4 events):

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | community.ipinfo.io | 0,3 | get | script | `https://global.discourse-cdn.com/standard17/assets/workbox-9b5674ca0ecb89bae1fa6f4b09a18f12/workbox-cacheable-response.prod.js` |
| +2 |  |  | community.ipinfo.io | 0,1 | get | script | `https://community.ipinfo.io/service-worker.js` |
| +1 | \|\|ipinfo.io^$3p | -- | t.co | 0,3 | get | xhr | `https://community.ipinfo.io/t/preventing-credential-stuffing-attacks-with-ipinfo/1201` |
| +0 | \|\|ipinfo.io^$3p | -- | t.co | 0,3 | get | xhr | `https://community.ipinfo.io/t/preventing-credential-stuffing-attacks-with-ipinfo/1201` |
| +0 |  |  | t.co | 1 | get | doc | `https://t.co/JJ0ETzNHSu` |
</details>


Log output from the incognito browsing operation (latest to oldest up to 4 events):

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | community.ipinfo.io | 1 | get | script | `https://community.ipinfo.io/plugins/discourse-client-performance/javascripts/discourse-client-performance.js?v=a5516f42f069cc08ed87ab2eb67fdc84e564d687a11b22972a24b0911180c320` |
| +2 |  |  | community.ipinfo.io | 3 | get | script | `https://global.discourse-cdn.com/standard17/assets/start-discourse-7c0f5f4daf3c942b7b6ecfe8e62e2e5a0f6555924859cf055314c0df3d617353.br.js` |
| +0 |  |  | community.ipinfo.io | 1 | get | doc | `https://community.ipinfo.io/t/preventing-credential-stuffing-attacks-with-ipinfo/1201` |
| +0 |  |  | t.co | 1 | get | doc | `https://t.co/JJ0ETzNHSu` |
</details>


Comparing this two browsing traffic, in the incognito session, the second request is labeled as `doc`, while in the standard session, the first request is labeled as `xhr`. 

However, in the standard browsing sessions, according to the network information in devtools the request are not `xhr` but rather `doc`.

![image](https://github.com/easylist/easylist/assets/111275753/c582d9be-78e4-4c06-8888-2288c8d7704f)


For identical parameters, I am not sure how uBlock Origin acts differently. The filtering mechanism on the `3p` level does not make sense, but what is even more confusing is its seemingly unpredictable nature across non-incognito vs incognito. I wish I could provide clear context around this issue, but I am quite confused.

**Comment by abdullahdevrel** [comment]
Thank you, @Yuki2718. I appreciate your help in clarifying the issue further.
