### ISSUE TITLE
abema.tv: breakage

### ISSUE THREAD

**Issue by chimaha** [easylist/easylist#18198]
#### List the website(s) you're having issues with:

`https://abema.tv/now-on-air/abema-anime`

#### What happens?

When watching videos, the memory usage increases, causing the website to become unresponsive.
Approximately 1GB is consumed in about 30 minutes, and after about an hour, the website freezes.

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: Windows10 Home 22H2
- Browser/version: Firefox 121.0
- Ad block extension/version: uBlock Origin 1.54.0

#### Other details:

```
||newrelic.com^$third-party
||nr-data.net^$third-party
```
The above two rules increase memory usage.

The following exclusion rules now work properly.
```
@@||js-agent.newrelic.com^$domain=abema.tv
@@||bam.nr-data.net^$xhr,domain=abema.tv
```

**Comment by Yuki2718** [comment]
I can't rerpdocue with a short test (and not seeing `nr-data.net` request), how long it takes to see obvious abnormality? Did you test
```
||js-agent.newrelic.com^$script,redirect=noop.js,domain=abema.tv

```
? Please also attach screenshot(s) of task manager.

**Comment by chimaha** [comment]
Memory usage exceeds 1GB in about 20 minutes and reaches 3GB in 40 minutes.
![E5hLQMG6H8](https://github.com/easylist/easylist/assets/107383950/219117de-fc7b-433d-be87-52cf630f0570)

When I excluded the rule for`||newrelic.com`, I saw`||nr-data.net`.
![dIVVRAv0en](https://github.com/easylist/easylist/assets/107383950/8d82dab3-2f63-4249-8676-50fe2cac2f0c)


If these two rules are excluded, memory usage seems to keep 200MB.

**Comment by Yuki2718** [comment]
Okay, reproduced though less degree. Will check the fixes lator.

**Comment by Yuki2718** [comment]
Will add the exception only for ABP as not needed for AG or uBO with better fixes.

**Comment by chimaha** [comment]
Are you referring to live broadcast ads (CM)?
I added that rule, but it doesn't seem to make any difference. Since it is a live broadcast, it would be difficult to avoid commercials.

**Comment by Yuki2718** [comment]
Ah, understood. Even if blocked, I only get blank screen while ads are playing so it doesn't make sense.

**Comment by chimaha** [comment]
Not related to the issue, but is it possible to block CM with uBO?
It doesn't matter if the screen goes blank.

**Comment by chimaha** [comment]
Thank you!
