### ISSUE TITLE
webflow.com

### ISSUE THREAD

**Issue by mattgawarecki** [easylist/easylist#18207]
#### List the website(s) you're having issues with:

`https://webflow.com/dashboard/login`
`https://webflow.com/dashboard/signup`

#### What happens?

The site fails to load -- blank white page.

#### Screenshot(s) 

<img width="1273" alt="image" src="https://github.com/easylist/easylist/assets/670067/50a174dd-f008-4106-9df4-d607ac7533e8">

<img width="1153" alt="image" src="https://github.com/easylist/easylist/assets/670067/b4e64e9f-8691-41df-8eab-b8e0747f0e22">

#### Filter lists you're using:

Firefox: EasyList (checkbox in uBlock Origin)
Brave: ??? (default install, shields up)

#### Your settings:

- OS/version: macOS Sonoma 14.2.1
- Browser/version: Firefox 121.0 / Brave 1.61.114
- Ad block extension/version: uBlock Origin 1.54.0

#### Other details:

Brave seems to interpret the subdomain `d3e54v103j8qbb.cloudfront.net` as an ad or a tracker, which blocks the main JS payload from loading the site's React app. This domain was added to EasyList in commit 5c699b538b00a25c64c7a1be32165768e454cd80.

<img width="396" alt="image" src="https://github.com/easylist/easylist/assets/670067/fc2b5bce-8c01-4208-bd4d-c3052a366164">

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/fe3a6bd400a97923ce737f6b2d50b932ff14aed2
