### ISSUE TITLE
Incorrect formatted domain names in hosts file

### ISSUE THREAD

**Issue by Wiggum127** [easylist/easylist#18218]
#### List the website(s) you're having issues with:

No specific website or domain, rather incorrect entries in the hosts file.

#### What happens?

When loading the hosts file into pi-hole, the incorrectly formatted domain name entries are reported back.

#### Screenshot(s) 

 [i] Target: https://v.firebog.net/hosts/Easyprivacy.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 32269 exact domains and 0 ABP-style domains (ignored 4 non-domain entries)
      Sample of non-domain entries:
        - "emam"
        - "smcom"
        - "smetriccom"
        - "smetrics.previcox.d"

#### Filter lists you're using:

https://v.firebog.net/hosts/Easyprivacy.txt

#### Your settings:

pi-hole

**Comment by Khrin** [comment]
From the top of the list that you're currently using:
`# This is sourced from an "adblock" style list which may contain mistakes in how it is parsed`
`# Please bring any such issues up at https://github.com/WaLLy3K/wally3k.github.io/issues`

EasyPrivacy is not designed for use in Pi-hole.
