### ISSUE TITLE
europeangaming.eu: ads

### ISSUE THREAD

**Issue by huyszn** [easylist/easylist#18231]
`https://europeangaming.eu/portal/`

```
europeangaming.eu##[href^="https://www.softswiss.com/order-turnkey-casino/"] > .loaded.lazy
europeangaming.eu##center
```

<img width="1440" src="https://github.com/easylist/easylist/assets/46979193/2739aec5-47e9-469d-b5a9-95739a14c1bf">

**Comment by K-mikaZ** [comment]
I personnaly use:

##### ! ---Hide top banner---
```
europeangaming.eu#?##mvp-site-main:style(top:0!important;margin-top:0!important;)
europeangaming.eu#?##mvp-leader-wrap:style(display:none!important;visibility:hidden!important;)
```
##### ! ---Prevent create banner on the fly---
> europeangaming.eu##center "OR" ##[class^="acc_banner_link"][target][rel^="no"]

`acc_get_banners$from=europeangaming.eu,redirect=noop.js`
