### ISSUE TITLE
Script (https://script1.kakaku.k-img.com/script/history/js.cookie.min.js) on kakaku.com is setting tracking cookies and is not blocked

### ISSUE THREAD

**Issue by hadiamjad** [easylist/easylist#18242]
Script (https://script1.kakaku.k-img.com/script/history/js.cookie.min.js) on kakaku.com is setting tracking cookies as mentioned in the website's privacy policy https://corporate.kakaku.com/privacy/about
![image](https://github.com/easylist/easylist/assets/46374292/1f52cf2b-2c90-466d-862c-ddff7e5182cb)
This is again not blocked by lists

#### List the website(s) you're having issues with:
kakaku.com

#### Filter lists you're using:

![image](https://github.com/easylist/easylist/assets/46374292/65d50e25-231b-4a51-90d4-77a82f5e8e31)

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by Yuki2718** [comment]
As naturally expected, blocking this totally breaks history on `kakaku.com` sites. You can block in your My filters if you don't care. Not for public lists.

**Comment by hadiamjad** [comment]
> As expected, blocking this totally breaks [history](https://history.kakaku.com/history/) on `kakaku.com` sites. Not for public lists.

Just to confirm this is also setting some tracking cookies but can not be blocked because it causes breakage. @Yuki2718  Right?

**Comment by Yuki2718** [comment]
Yes, right.
