### ISSUE TITLE
Script (https://www.npttech.com/advertising.js) on oe24.at is detecting ad-blockers and taking alternative approach and is not blocked

### ISSUE THREAD

**Issue by hadiamjad** [easylist/easylist#18243]
Script (https://www.npttech.com/advertising.js) on oe24.at is detecting the presence of ad-blockers in a user's browser and take actions based on whether an ad blocker is detected or not. It has functions which contains specific conditions for certain domains (like 'businessinsider.com' and 'therealdeal.com'), suggesting customized behaviors or checks for these sites.
This script is also not blocked.

#### List the website(s) you're having issues with:
oe24.at

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version: 
![image](https://github.com/easylist/easylist/assets/46374292/b28afa11-4e1c-4af8-a026-a798a3ea4010)

**Comment by Yuki2718** [comment]
EL does not block anti-adb on usual sites as described in README. Besides, blocking this rather triggers anti-adb if without redirect. See https://github.com/uBlockOrigin/uAssets/commit/0ed4fd57909f1dd6a570614a23a57e3e54f358c7
