### ISSUE TITLE
VG.no - Blocked videos (EasyList - Cookie Notices) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#18245]
### Affected site:
`https://www.vg.no/`

### Issue:
Some videos won't load, due to a blocked cookie consent, which needs to be accepted first.

### Examples:
`https://tv.vg.no/` (probably geo restricted)

`https://vg.no/i/762Qv8/`

### Screenshots:
* **With blocked cookie consent:**

![filterissue-vg3](https://github.com/easylist/easylist/assets/9382674/6789847f-3b9f-406e-8229-fe4f33e35a7a)

* **After the cookie consent has been accepted:**

![filterissue-vg4](https://github.com/easylist/easylist/assets/9382674/cde055a1-3424-4015-94dc-a24059337ba8)

### Problem filter:
* **EasyList - Cookie Notices**

### Problem rule:
`||cmp.vg.no^`

### Possible fix:
```
- ||cmp.vg.no^

+ ||cmp.vg.no^*/metrics/ (for 'EasyPrivacy')
```

### Other problem filters:
* **AdGuard Cookie Notices filter** https://github.com/AdguardTeam/AdguardFilters/issues/170285/
```
speisekarte.de,businessinsider.com,historyextra.com,finn.no,vg.no,aftenposten.no,tek.no,vglive.no,bt.no,telegraph.co.uk##div[id^="sp_message_container_"]
```

* **I don't care about cookies** _(@kiboke)_
```
/wrapperMessagingWithoutDetection.js$domain=vg.no|boerse.de|bt.no|liberation.fr

cmp.$domain=telerama.fr|courrierinternational.com|vodkaster.com|svd.se|histoire-et-civilisations.com|malservice.aftonbladet.se|vg.no|tv.nu|tek.no|finn.no|pent.no|godt.no|aftenposten.no|omni.se|e24.no|helthjem.no|minmote.no|aftenbladet.no|klart.se
```

### Temp fix:
```
vg.no#@#div[id^="sp_message_container_"]
@@||cmp.vg.no^
||cmp.vg.no^*/metrics/$important
```

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v121.0-1 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.55.0

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
Surprisingly, not only was the problem also affecting IDCAC, but pressing Tilpass → Avvis alle ("Adjust → Reject All") makes the video play correctly.

**Comment by THEtomaso** [comment]
Hopefully, it can be fixed with some sort of `##+js` rule, instead of the ones that I provided.

**Comment by THEtomaso** [comment]
> Reject All") makes the video play correctly.

Same as YouTube :)
