### ISSUE TITLE
GitHub Copilot: Cookie notice

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#18258]
#### List the website(s) you're having issues with:

`https://github.com/features/copilot`

#### What happens?

There is a cookie notice at the bottom of the website that is not being blocked.

#### Screenshot(s) 

![Screenshot from 2024-01-11 09-45-53](https://github.com/easylist/easylist/assets/123986260/11ff606b-9db6-4c2c-b0f1-43e4914514a8)

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: Fedora Silverblue 39
- Browser/version: Firefox 121
- Ad block extension/version: uBlock Origin 1.55

**Comment by Yuki2718** [comment]
Due to `$generichide` in EL. Will add a specific rule.
