### ISSUE TITLE
[Breakage] imasdk.googleapis.com 

### ISSUE THREAD

**Issue by simplyinquisitive** [easylist/easylist#18264]
Blocking `imasdk.googleapis.com` breaks livestreams that contains in-video ads eg. during sports streaming. The video stream never loads. Tested on Pihole with Easylist. Domain match found in no other popular lists except GoodByeAds which seems like it has been abandoned.

**Comment by liamengland1** [comment]
There are exceptions for imasdk for many domains in easylist. Pihole cannot support this. Don't use easylist with pihole. 

https://github.com/easylist/easylist/issues/14740#issuecomment-1399348431
