### ISSUE TITLE
finder.com.au & finder.com redirects to doubleclick.net

### ISSUE THREAD

**Issue by fmrk** [easylist/easylist#18277]
#### List the website(s) you're having issues with:

- finder.com
- finder.com.au
#### What happens?

Intentionally clicking a redirect button on any of `finder.com.au` / `finder.com` / `creditcard.com.au` pages that opens a new tab with `ad.doubleclick.net` in the redirect path causes ad blockers to immediately shut down the newly opened tab.
E.g. by clicking `Go to site` for `Unloan Variable Home Loan` on https://www.finder.com.au/home-loans/best-home-loans

Checking logs shows it's related to `||doubleclick.net^$popup` filter rule

This issue has been first discussed with uBlock Origin team here: https://github.com/uBlockOrigin/uAssets/issues/21939

I have tested extending the existing EasyList [exception rule](https://github.com/easylist/easylist/blob/master/easylist/easylist_allowlist_popup.txt#L5C32-L5C32) by adding our domains
like that:
```
@@||ad.doubleclick.net/ddm/$popup,domain=billiger.de|guide-epargne.be|legacy.com|mail.yahoo.com|nytimes.com|spaargids.be|finder.com.au|finder.com|creditcard.com.au
```
It did the job well enough (the tab wasn't shut down).

#### Screenshot(s) 

<img width="1255" alt="image" src="https://github.com/easylist/easylist/assets/12071815/0a8027b8-c03e-4608-a126-3e970e1ee025">

<img width="1237" alt="image" src="https://github.com/easylist/easylist/assets/12071815/0c492e31-cea2-4499-8064-511a57f237d6">

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: Mac OS Ventura 13.6.3 (22G436)
- Browser/version: Google Chrome Version 120.0.6099.199 (Official Build) (x86_64)
- Ad block extension/version: uBlock Origin 1.54.0

#### Other details:

Here's my pull request: https://github.com/easylist/easylist/pull/18276

**Comment by fmrk** [comment]
thank you @monzta! 🎉

**Comment by monzta** [comment]
@fmrk you are welcome :)
