### ISSUE TITLE
dev.motiv.fm

### ISSUE THREAD

**Issue by qkveri** [easylist/easylist#18271]
#### List the website(s) you're having issues with:

[https://dev.motiv.fm/](https://dev.motiv.fm/)

#### What happens?

Queries hang for a long time in the Queuing state when the EasyList filter is enabled.
If EasyList disabled, there are no problems.

Reproduction steps:
1. Open the main page [https://dev.motiv.fm/](https://dev.motiv.fm/)
2. Switch between sidebar tabs: "Главная" (Home), "Топ-100" (Top-100), "Статьи" (Articles).

#### Screenshot(s) 

![network](https://github.com/easylist/easylist/assets/26967934/ffe5bc0d-b9d4-4a6b-98d1-270fa1922268)

#### Filter lists you're using:

- EasyList

![filters](https://github.com/easylist/easylist/assets/26967934/d2e1fb28-ffed-4aa9-bf6f-1c436a5c158c)

#### Your settings:

- OS/version: Windows 11 Home
- Browser/version: Google Chrome/120.0.6099.217
- Ad block extension/version: 3.22

**Comment by dportvine** [comment]
https://gitlab.com/adblockinc/ext/adblockplus/adblockplusui/-/issues/1576

**Comment by qkveri** [comment]
After updating Adblock Plus to version 3.22.1 there are no problems.
