### ISSUE TITLE
licensing.bitmovin.com/impression

### ISSUE THREAD

**Issue by felix-hoc** [easylist/easylist#18272]
#### List the website(s) you're having issues with:

Any page using Bitmovin Player, e.g. https://bitmovin.com/demos/stream-test

#### What happens?

Hi, I'm posting this on behalf of Bitmovin. I would like to kindly request the removal of `licensing.bitmovin.com/impression` from the list:

https://github.com/easylist/easylist/blob/67e1a5f70b539d0dd334ce9717b0b95226a70884/easyprivacy/easyprivacy_thirdparty.txt#L1233

A colleague of mine already opened [an issue](https://github.com/easylist/easylist/issues/7999) a while back (for `licensing.bitmovin.com`), and the points he made still remain true:

_It is not in any way a tracking url (ie. we do none of "tracking or monitoring, UA/IP/Geo checks, browser detection, analytics, telemetry, linking to third-partys, pixels, referrers, fingerprinting, event/perf logging etc."), but simply allows us to charge our customers for their usage. Having this url on this list is costing Bitmovin money at no benefit to your users._

#### Filter lists you're using:

EasyPrivacy

#### Other details:

The `/impression` endpoint allows us to count the number of plays per customer, which is part of our revenue model. Feel free to inspect the payload on any page using the Bitmovin Player, e.g. https://bitmovin.com/demos/stream-test

At the moment, no pages are breaking because of it, but in the long run it may force us to change our approach to be more strict (but as an easylist/adblock user myself I would like to prevent that :) )

I'm happy to open a PR.

Thank you!

**Comment by ryanbr** [comment]
This filter isn't new: impressions are still tracking users or user clicks.

 https://github.com/easylist/easylist/commit/916f6008f0dd75e3bfbf7e6480047b105e86e9ea
https://github.com/easylist/easylist/commit/5e5338fe8bf59cd10884f1dcc3023172b88387b0

**Comment by ryanbr** [comment]
Not sure why suddendly after 7 years its suddenly different?

**Comment by Khrin** [comment]
> At the moment, no pages are breaking because of it, but in the long run it may force us to change our approach to be more strict (but as an easylist/adblock user myself I would like to prevent that :) )

This speaks volumes about you and the "company" you work for.
