### ISSUE TITLE
[NSFW] ten.ggvaj

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18270]
**NSFW** ==> `javgg . net`
```
||1a65658575.com^
||395b8c2123.com^
||sheegiwo.com^
javgg.net##.home_iframead
```

**Comment by Yuki2718** [comment]
See https://github.com/AdguardTeam/AdguardFilters/issues/137631#issuecomment-1359891563

**Comment by Yuki2718** [comment]
Doesn't the rule work on ABP as well? I already changed some `:-abp-has()` rules to `:has()` in agreement with @monzta . EL maintainers decided not to wait for Firefox ESR to support native `:has()`.
