### ISSUE TITLE
Youtube ad element under video

### ISSUE THREAD

**Issue by Dwedit** [easylist/easylist#18292]
#### List the website(s) you're having issues with:

youtube.com

#### What happens?

There is an ad element below the video.

#### Screenshot(s) 

![](https://i.imgur.com/QIGwWFH.png)

Text boxes say `##.sparkles-light-cta.ytd-in-feed-ad-layout-renderer.style-scope` then multiline box says

```
    ##.sparkles-light-cta.ytd-in-feed-ad-layout-renderer.style-scope
    ###rendering-content.ytd-in-feed-ad-layout-renderer.style-scope
    ##.ytd-ad-slot-renderer.style-scope
    ###fulfilled-layout.ytd-ad-slot-renderer.style-scope
    ##ytd-ad-slot-renderer.ytd-watch-next-secondary-results-renderer.style-scope
    ###items.ytd-watch-next-secondary-results-renderer.style-scope
    ##ytd-watch-next-secondary-results-renderer.ytd-watch-flexy.style-scope
    ###related.ytd-watch-flexy.style-scope
    ###below.ytd-watch-flexy.style-scope
    ###primary-inner.ytd-watch-flexy.style-scope
    ###primary.ytd-watch-flexy.style-scope
    ###columns.ytd-watch-flexy.style-scope
    ##.hide-skeleton.ytd-page-manager.style-scope
    ###page-manager.ytd-app.style-scope
    ###content.ytd-app.style-scope
    ##ytd-app
```

#### Filter lists you're using:

EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe’s Ad and tracking server list

#### Your settings:

- OS/version: Windows 10
- Browser/version: Firefox 121.0
- Ad block extension/version: Running "Enhancer for Youtube", but its "block ads" feature is disabled.

**Comment by Yuki2718** [comment]
You seem to forgot filling in `Ad block extension/version`, though the screenshot is obviously uBO's.

**Comment by RoyalOughtness** [comment]
@Yuki2718 FYI, it appears this is broken again.

classes in question:

```
ytd-in-feed-ad-layout-renderer
ytd-player-legacy-desktop-watch-ads-renderer
```

**Comment by Yuki2718** [comment]
@RoyalOughtness What do you mean by broken? Can you provide an url to test?
