### ISSUE TITLE
Block OneTrust Privacy Annoyances

### ISSUE THREAD

**Issue by riei2922jww** [easylist/easylist#18302]
Please add:
my.onetrust.com
geolocation.onetrust.com
mobile-data.onetrust.io

To the blocklist to prevent these annoying cookie pop-ups on 70% of applications.

![image](https://github.com/easylist/easylist/assets/154846714/94cf17ae-f1d9-4f93-a79c-f71b032b9cc4)

**Comment by Yuki2718** [comment]
See @THEtomaso 's comment. If you want consent banners fixed, report them one by one with all the necessary info (in particular blocker and filter lists you use).

**Comment by Yuki2718** [comment]
> in order to prevent various types of breakage (e.g. frozen pages, unplayable videos, non-working buttons, etc.).

Breakage >> cookie banner
