### ISSUE TITLE
windy.com consent dialog

### ISSUE THREAD

**Issue by gwarser** [easylist/easylist#18301]
#### List the website(s) you're having issues with:

https://www.windy.com/

#### What happens?

Consent dialog 

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/886325/3c0f998a-f34c-45ce-899c-a6244b39cc7d)

#### Filter lists you're using:

EasyList – Cookie Notices  
EasyList – Annoyances

#### Your settings:

- OS/version: Linux
- Browser/version: Nightly
- Ad block extension/version: uBO 1.55.1b5

**Comment by Yuki2718** [comment]
Hm, I can't reproduce even with Eurpean VPN.

**Comment by Yuki2718** [comment]
I see the code but the element never appears. Maybe @Khrin or @monzta can reproduce.
