### ISSUE TITLE
Video hidden on cars.com

### ISSUE THREAD

**Issue by delta9A** [easylist/easylist#18314]
#### List the website(s) you're having issues with:
https://www.cars.com/articles/what-to-know-before-purchasing-an-electric-vehicle-a-buying-guide-448149/
https://www.cars.com/articles/2024-chevrolet-trailblazer-review-in-the-shadow-of-its-sibling-475977/

#### What happens?
EL Filter `##.vjs-ima3-ad-container` hides content video on the page

May you please add an exception for the videos? 

#### Screenshot(s) 
<img width="1059" alt="cars" src="https://github.com/easylist/easylist/assets/121119167/60e03efe-9fce-4ffc-a850-0bbcf900442d">

#### Filter lists you're using:
EL + ABP Filters

#### Your settings:

- OS/version: MacOS
- Browser/version: Opera
- Ad block extension/version: ABP 3.22

**Comment by Khrin** [comment]
apparently this is no longer reproducible, and the video player there works correctly. closing here.
