### ISSUE TITLE
metager.org - "Support MetaGer" ad shown in search results

### ISSUE THREAD

**Issue by flux77** [easylist/easylist#18320]
#### List the website(s) you're having issues with:
`https://metager.org/meta/meta.ger3?eingabe=hawaii%20ferry%20service`

#### What happens?
The "Support MetaGer" ad is shown in the search results.

#### Screenshot(s) 
![support-metager-ad](https://github.com/easylist/easylist/assets/44834611/eda0f94c-964e-44c1-96b4-cce95bd2af13)

#### Filter lists you're using:
* EasyList

#### Your settings:
- OS/version: Debian 12
- Browser/version: Firefox 115.6.0esr
- Ad block extension/version: uBlock Origin 1.55.0

#### Other details:
Proposed filter:

```
metager.org##.result:has(a[href^="https://metager.org/spende"])
```

**Comment by Daxy7** [comment]
Self-promotion.
