### ISSUE TITLE
https://wizzair.com/FR-FR/newsletterunsubscribe

### ISSUE THREAD

**Issue by Tr4sK** [easylist/easylist#18339]
#### List the website(s) you're having issues with:

`https://wizzair.com/FR-FR/newsletterunsubscribe`

#### What happens?

Missing unsubscribe form in the page

#### Screenshot(s) 

Without Easylist – Newsletter notices
![image](https://github.com/easylist/easylist/assets/1238195/5a877c1b-491b-4e22-bb84-3642b0a3b42f)

With Easylist – Newsletter notices
![wizzair unsubscribe](https://github.com/easylist/easylist/assets/1238195/b6778beb-7acd-4e0d-96fd-8877b9621da4)

The concern module in Ublock Origin
![image](https://github.com/easylist/easylist/assets/1238195/e0205e41-7bc6-4cb3-bd67-2e6500316130)

#### Filter lists you're using:

![image](https://github.com/easylist/easylist/assets/1238195/c35426e9-5906-4d47-bf31-fb3c860ff90a)

![image](https://github.com/easylist/easylist/assets/1238195/26859c2a-d49f-49d3-a5f3-160dcdb03bb2)

#### Your settings:

- OS/version: Ubuntu 20.04
- Browser/version: Firefox 122.0 (64-bit)
- Ad block extension/version: Ublock origin 1.55.0

**Comment by Dani-1-2** [comment]
These filters fix the issue:
wizzair.com#@#.newsletter__title
wizzair.com#@#.newsletter.box
wizzair.com#@#.newsletter__cta
