### ISSUE TITLE
techwalla.com images blocked

### ISSUE THREAD

**Issue by theel0ja** [easylist/easylist#1834]
### List the website(s) you're having issues:
```
https://www.techwalla.com/articles/how-to-add-new-fonts-to-a-mac
```

### What happens?
images are blocked

### List Subscriptions you're using:
easylist

### Your settings

- OS/version: macos
- Browser/version: firefox
- Adblock Extension/version: ublock origin

### Other details:

<img width="243" alt="screen shot 2018-09-15 at 15 14 20" src="https://user-images.githubusercontent.com/5832930/45586123-09c46200-b8fa-11e8-9aa7-fc159c6aed05.png">

**Comment by bogachenko** [comment]
so? 
`@@||img.techwallacdn.com^$image,domain=www.techwalla.com`
