### ISSUE TITLE
1337x.to

### ISSUE THREAD

**Issue by punisher018** [easylist/easylist#18352]
Because of this filter in Easylist, the site does not open from time to time. It gives an error that your browser version is outdated.

`||1337x.to^$document,csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' data:`

![aaa](https://github.com/easylist/easylist/assets/51531027/bac90d27-1ffe-4964-ad63-035489f6f982)

**Comment by Daxy7** [comment]
https://github.com/easylist/easylist/commit/142ea0ccba88d472f1513400c219181d511d07d0
