### ISSUE TITLE
lefigaro.fr

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18415]
**annoyance**
- https://i.imgur.com/0EQpaag.png
```
lefigaro.fr##.video-sticky-limit
```
`A: https://www.lefigaro.fr/automobile/lexus-rx-elegance-et-sobriete-20220601`

**Comment by garry-ut99** [comment]
Another annoyance:
- https://github.com/uBlockOrigin/uAssets/discussions/25030

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/e76c4497461015b2551194124cc3980755b8e76a
