### ISSUE TITLE
bot-hosting.net

### ISSUE THREAD

**Issue by MathiasDPX** [easylist/easylist#18430]
![ad](https://github.com/easylist/easylist/assets/56231137/76ba87e6-25ec-40f8-97cf-b38f6ff6ca4a)

Ad popup
[https://bot-hosting.net/panel/earn](https://bot-hosting.net/panel/earn)

Solution: bot-hosting.net##div#adModal
I put this in "My filter" in UBO and it work

**Comment by Yuki2718** [comment]
I can't reproduce with logged in.
