### ISSUE TITLE
sevio.com

### ISSUE THREAD

**Issue by BogdanSevio** [easylist/easylist#18431]
#### List the website(s) you're having issues with:
`https://sevio.com/admanager/`
`https://sevio.com/admanager/features/`
`https://admanager.sevio.com/`

#### What happens?
EasyList blocks resources and messes up the page. The issue might not be reproducible as we're changing our URLs to fix the issue ASAP. It's affecting our business quite a lot. 

#### Screenshot(s) 
![Screenshot 2024-02-01 at 12 00 33](https://github.com/easylist/easylist/assets/158458330/17646402-3c6e-48a2-a157-9cd082d22c18)
![Screenshot 2024-02-01 at 12 00 47](https://github.com/easylist/easylist/assets/158458330/c2cd4440-a5fe-49ac-ae6b-d3315775cb0b)

#### Filter lists you're using:

Acceptable Ads, Anti-Circumvention filters, EasyList

#### Your settings:

- OS/version: Sonoma 14.2.1
- Browser/version: Google Chrome Version 121.0.6167.85 (Official Build) (arm64)
- Ad block extension/version: AdBlock 5.18.0

#### Other details:

The problem is with the easylist filter. Turning it off will solve the issue.

**Comment by BogdanSevio** [comment]
@ryanbr @tangible-idea @EasyListHebrew @monzta @Khrin @EasyListHebrew

**Comment by EasyListHebrew** [comment]
it's not part of EasyListHebrew

**Comment by BogdanSevio** [comment]
Ok, so how should we proceed to fix this? Or is there any reason in particular while we won't be added on the filter list?

**Comment by monzta** [comment]
@BogdanSevio the issue was fixed in EasyList.
