### ISSUE TITLE
expresso.pt

### ISSUE THREAD

**Issue by virtualwebgit** [easylist/easylist#18456]
#### Your settings:

- OS/version: Windows 11
- Browser/version: Google Chrome x64 121.0.6167.140
- Ad block extension/version: uBlock Origin 1.55.0

**Comment by Dani-1-2** [comment]
Can remove with expresso.pt##.didomi-popup__backdrop.didomi-notice-popup.didomi-popup-backdrop

**Comment by virtualwebgit** [comment]
> Can remove with expresso.pt##.didomi-popup__backdrop.didomi-notice-popup.didomi-popup-backdrop

Does remove the poup but you can't scroll page

**Comment by Dani-1-2** [comment]
@virtualwebgit 
If you add this too it works but it is uBlock Origin specific:
expresso.pt##body:remove-class(didomi-popup-open)
If you want to have it added to the uBlock Origin lists you should report to the uBlock Origin filter lists maintainers using the build in report feature in uBO.

**Comment by Dani-1-2** [comment]
@virtualwebgit This works as well:
expresso.pt##body:style(overflow: auto !important;)

**Comment by Dani-1-2** [comment]
@virtualwebgit 
This works as well and I think it is standart easylist:
expresso.pt##body:style(overflow: auto !important;)

**Comment by virtualwebgit** [comment]
> @virtualwebgit This works as well: expresso.pt##body:style(overflow: auto !important;)

Not working, still having the popup

**Comment by Daxy7** [comment]
do that for now, report any issues
```
||privacy-center.org^$domain=expresso.pt
```
…
tracker in `https://expresso.pt/`
```
https://statics.impresa.pt/js/analytics/active/analytics-bundle.min.js
```

**Comment by Dani-1-2** [comment]
> > @virtualwebgit This works as well: expresso.pt##body:style(overflow: auto !important;)
> 
> Not working, still having the popup
Works if you use it along with:
 expresso.pt##.didomi-popup__backdrop.didomi-notice-popup.didomi-popup-backdrop

**Comment by Daxy7** [comment]
@virtualwebgit 
### if you are getting a soft paywall. add this to uBlock Origin and install tampermonkey for the userscript in `bpc.es`:
https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters

**Comment by virtualwebgit** [comment]
> @virtualwebgit
> 
> ### if you are getting a soft paywall. add this to uBlock Origin and install tampermonkey for the userscript in `bpc.es`:
> https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters

It is not paywall, but rather a cookie warning. I know there is also a paywall to read the complete news, but that it is not what I was complaining about
