### ISSUE TITLE
fjallraven.com

### ISSUE THREAD

**Issue by metametapod** [easylist/easylist#18465]
#### List the website(s) you're having issues with:
- `https://www.fjallraven.com`

#### What happens?

Cookie notice still visible with EasyList Cookie List enabled.

1. Download clean build of latest Firefox stable or Firefox nightly.
2. Install uBlock Origin.
3. Enable all EasyList filters.
4. Disable all other filters.
5. Navigate to above URL.

#### Screenshot(s) 

<img width="924" alt="Screenshot 2024-02-04 at 16 31 30" src="https://github.com/easylist/easylist/assets/80652640/db65085e-f973-4a34-83a0-339c6f923784">

#### Filter lists you're using:

EasyList, EasyPrivacy, and all of EasyList — Annoyances on uBlock Origin.

#### Your settings:

Using uBlock Origin 1.55.0 on latest Firefox 122.0 and 123.0b6.

#### Other details:

Suggested filter rule:

```
fjallraven.com##.cookies--root
```

**Comment by Khrin** [comment]
@metametapod The cookie notice should already be blocked. Do you still have the problem?

**Comment by metametapod** [comment]
Looks like it's fixed now. Thank you!
