### ISSUE TITLE
[NSFW] rule34.paheal.net

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#18467]
ad placeholder
```
https://rule34.paheal.net/post/list/404440/1
```
```
rule34.paheal.net##[id*="main"]:has-text(Selector)
```
https://github.com/easylist/easylist/assets/91396482/b1fc6f63-beb7-4413-993b-9787175f5389

**Comment by Daxy7** [comment]
@Yuki2718 nothing happens
https://github.com/easylist/easylist/assets/91396482/00a1b0ce-ce72-4041-aa76-3c04d58aa2ed

**Comment by Yuki2718** [comment]
Your screenshot is correctly showing 1 hit. The white rectangle you see is empty even if you disabled blocker.

**Comment by Daxy7** [comment]
there are zero results no image results or even ads when disabling the blocker. it's a site issue. [NSFW]
https://github.com/easylist/easylist/assets/91396482/e56ef5be-466b-4bd1-96ca-80521ea799a6

**Comment by Daxy7** [comment]
ah, my bad. it was the blockbody for the announcement(s). the new server has it disabled for some reason

https://github.com/easylist/easylist/assets/91396482/b1b7278c-c480-4ff6-bed0-e43a548683c9
