### ISSUE TITLE
tld-list.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#18472]
#### List the website(s) you're having issues with:
`https://tld-list.com/`

#### What happens?
Ad

#### Filter lists you're using:
uBlock Origin default

#### Your settings:

- OS/version: macOS
- Browser/version: Brave (built-in ad blocker disabled)
- Ad block extension/version: uBlock Origin 1.55.0

#### Other details:
```
||tld-list.com/img/a/
```

**Comment by ButterVsMargarine** [comment]
Fixed
