### ISSUE TITLE
devuploads.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18503]
**Website**

* `https://devuploads.com/p8hfsvfynn5j`

random redirect to 

```
dev.miuiflash.com
jytechs.in
thecubexguide.com
djxmaza.in
```

Then you get ads on that page.

**Comment by Daxy7** [comment]
may be out of scope for EL. is it network filters or first party scripts?
https://github.com/easylist/easylist/assets/91396482/a28a0a8d-4c3c-4701-a105-97bc58da53c8
