### ISSUE TITLE
torrentgalaxy.to

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18506]
ads banners

- https://i.imgur.com/RnwuvDu.png

`A: https://torrentgalaxy.to/`

**Comment by Daxy7** [comment]
uBO used a bunch of image urls for this but it's `picturedent.org` and invalid
```
torrentgalaxy.to##[href^="/hux"]
! or
||torrentgalaxy.to/images/224/01/18/*.jpg
! url changes detected so perhaps
||torrentgalaxy.to/images/$image
```
https://github.com/easylist/easylist/assets/91396482/8fc5a199-b9cc-4612-86aa-04d79527acbe

**Comment by Daxy7** [comment]
🤔📝🖇️🖇️🖇️➕🚫📎📎📎📎✅  💬❔

https://github.com/easylist/easylist/assets/91396482/72676c2e-f83b-43cd-8933-46e6fbf9c2eb
