### ISSUE TITLE
https://github.com/openedx/event-tracking/pull/246

### ISSUE THREAD

**Issue by timmc-edx** [easylist/easylist#18500]
#### List the website(s) you're having issues with:

`https://github.com/openedx/event-tracking/pull/246` and many other pages for this repository.

#### What happens?

Various GitHub features don't work -- I can't add a comment, PR checks don't load, etc.

The problematic filter seems to be `/event-tracking/*` in EasyPrivacy.

#### Screenshot(s) 

Checks failing to load on `https://github.com/openedx/event-tracking/pull/246`:
![image](https://github.com/easylist/easylist/assets/59623490/dcf868ac-662f-41b3-bd3c-63ff57ba1f46)

Files failing to load on `https://github.com/openedx/event-tracking/pull/246/files` where I've marked them as Viewed:
![image](https://github.com/easylist/easylist/assets/59623490/1d3ba622-2c8c-4c5d-813c-a142c0a4e854)

#### Filter lists you're using:

EasyPrivacy and all of the others that come by default with uBlock Origin.

#### Your settings:

- OS/version: Ubuntu 22.04
- Browser/version: Firefox 122.0
- Ad block extension/version: uBlock Origin 1.55.0, with all filter lists updated.

#### Other details:

- Disabling uBlock Origin fixes the issue
- uBlock Origin's event logger identifies this rule as being the one blocking requests
- Disabling the EasyPrivacy filter list fixes the issue

**Comment by Daxy7** [comment]
add this for now until one of the maintainers fixes the issue
```
/event-tracking/*$domain=~github.com
```

**Comment by Daxy7** [comment]
scrap the first filter I provided and use the modified rule I added above. tested and works

**Comment by Daxy7** [comment]
@ryanbr still broken. check logs
https://github.com/easylist/easylist/assets/91396482/f6b6e154-23b6-4494-af74-07fa631840b9

**Comment by ryanbr** [comment]
WFM no hits on https://github.com/openedx/event-tracking/pull/246

```
/event-tracking/*$badfilter
/event-tracking/*$domain=~github.com
```
