### ISSUE TITLE
4chan.org JSON-fetching blocked

### ISSUE THREAD

**Issue by user1user** [easylist/easylist#1852]
### List the website(s) you're having issues:

```
4chan.org
```

### What happens?

Go to some board like `http://boards.4chan.org/a/.`  
Click on Settings.  
Go to Monitoring.  
Enable "Thread Watcher".  
Scroll down and Save Settings.  
Go to `http://boards.4chan.org/a/catalog` .  
Open some thread.  
Notice that `http://a.4cdn.org/a/threads.json` is blocked (Also applies to other json-files on 4cdn.org domain).  
See also (related external extension): https://github.com/ccd0/4chan-x/issues/2057

### List Subscriptions you're using:

EasyList Germany+EasyList

### Other details:
Problem is that internal site-features (internal extension) need XMLHTTPREQUEST to the 4cdn.org domain, to fetch JSON-Endpoints located there.

Offending Rule is:
|http://$third-party,xmlhttprequest,domain=4chan.org|alfonzorachel.com|americanewshub.com|americasfreedomfighters.com|beforeitsnews.com|boredomtherapy.com|breakingnews.ie|bugout.news|cheapism.com|chicksonright.com|clashdaily.com|conservativeintel.com|conservativetribune.com|creepybasement.com|dccrimestories.com|eaglerising.com|freedomdaily.com|freewarefiles.com|funnyand.com|gamerant.com|godfatherpolitics.com|headcramp.com|healthstatus.com|hngn.com|honesttopaws.com|instigatornews.com|intellectualconservative.com|janmorganmedia.com|jobsnhire.com|joeforamerica.com|kdramastars.com|knowledgedish.com|kpopstarz.com|lastresistance.com|latinpost.com|legalinsurrection.com|libertyalliance.com|libertyunyielding.com|lifebuzz.com|madworldnews.com|makeagif.com|mentalflare.com|musictimes.com|natureworldnews.com|newser.com|parentherald.com|patriotnewswire.com|patriottribune.com|pickthebrain.com|realtytoday.com|rpnewswire.com|sarahpalin.com|supercheats.com|survivalnation.com|terezowens.com|theblacksphere.net|thefreethoughtproject.com|thehayride.com|thelibertydaily.com|themattwalshblog.com|thepolitistick.com|therealside.com|therightscoop.com|universityherald.com|urbantabloid.com|usherald.com|vgpie.com|wakingtimes.com|westernjournalism.com|xtribune.com|youthhealthmag.com

From:
EasyList Germany+EasyList

**Comment by TheDong** [comment]
I opened a PR which should fix this: https://github.com/easylist/easylist/pull/1851

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/505cd3d3f498b5ca8f03952607885d04e70ddd02
