### ISSUE TITLE
katfile,frdl.to,skyve.io :Ads

### ISSUE THREAD

**Issue by BlazeFTL** [easylist/easylist#18548]
`https://skyve.io/9mdn4s64n63f`
`https://frdl.to/wcnhgzyc4x12/Telegram_Plus_v10.6.4.0_Modded.apk.html`
`https://katfile.com/lny1dxazsgww`

There is Ads/Placeholders
```
skyve.io##.ads_space
frdl.to##.img-fluid
katfile.com##[href^="https://ngineet.cfd/"]
```

**Comment by Khrin** [comment]
- https://github.com/easylist/easylist/commit/9db9adfc2e31e8e62ad26e3e1c556f537ec23269
- https://github.com/easylist/easylist/commit/96de94b46e5a3ec6243887643639688133abb7c6
- https://github.com/easylist/easylist/commit/4160dd43336402e04b75c5d29b3a913b65304d98

**Comment by Khrin** [comment]
- https://github.com/easylist/easylist/commit/9db9adfc2e31e8e62ad26e3e1c556f537ec23269
- https://github.com/easylist/easylist/commit/96de94b46e5a3ec6243887643639688133abb7c6
- https://github.com/easylist/easylist/commit/4160dd43336402e04b75c5d29b3a913b65304d98
