### ISSUE TITLE
medlemskap.fagforbundet.no was added to list

### ISSUE THREAD

**Issue by erichjsonfosse** [easylist/easylist#18542]
#### List the website(s) you're having issues with:

- medlemskap.fagforbundet.no

#### What happens?

The address is in use for campaigns run by Fagforbundet (one of the largest workers unions in Norway). I know that they are using an Oracle tool for the campaigns, and I would assume that this is why the address has been added to the list.
The problem with this is that the workers union also has an API that has nothing to do with the campaign, and the address for the API is api.medlemskap.fagforbundet.no. All requests to the API are being blocked as a consequence.

My request is for an exception for the API specifically, not for the removal of the address that was added.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/3193085/785cf43e-0bf3-4401-a8b1-97720d4b2fda)

#### Filter lists you're using:

Address was added to easyprivacy/easyprivacy_specific_cname_oracle.txt [5 days ago](https://github.com/easylist/easylist/commit/ba01dd86a6f6879f50fc79a4b057d9d008b3d786)

#### Your settings:

- OS/version: ManjaroLinux 23.1.3
- Browser/version: Google Chrome 121.0.6167.139
- Ad block extension/version: uBlock Origin 1.55.0

#### Other details:

The API is in use by one of the largest workers unions in Norway, and has nothing to do with neither ads, campaigns nor tracking of any kind.

**Comment by THEtomaso** [comment]
Changing `||medlemskap.fagforbundet.no^` into `||medlemskap.fagforbundet.no^$third-party` would probably solve it.

Until then, @DandelionSprout could adress this Nordic list, with `@@||medlemskap.fagforbundet.no^$first-party`, since there's no telling how long this report will linger here.

**Comment by erichjsonfosse** [comment]
Thanks @THEtomaso and @DandelionSprout .
It seemed like the update to [NorwegianList.txt](https://github.com/DandelionSprout/adfilt/commit/0fc854f4c141e7bbb1abf22ff27cbea1c1e28958) helped for a short while, but now it seems like we're getting blocked again.

Any suggestions?

**Comment by DandelionSprout** [comment]
Do you have a screenshot of the new blocking, so I can take a look at it tonight?

**Comment by erichjsonfosse** [comment]
@DandelionSprout 
Thanks for the quick response!

Is this what you're looking for?
![image](https://github.com/easylist/easylist/assets/3193085/6a1f49fc-7f64-4a9e-8650-eb0d88165983)

**Comment by DandelionSprout** [comment]
Fixing it for users whose browser languages are set to Norwegian, Nynorsk, or Danish, should have it fixed already, though I can do some extra big fixes just to be sure.

Fixing it for users whose browser languages are set to English, and therefore doesn't have Nordic Filters turned on by default? I'd need to get some help from other parties to do so. *uAssets* and their "Unbreak" list in particular. Can take anywhere from 12 hours to 1 week.

**Comment by Alex-302** [comment]
It is loaded from https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/microsites/oracle-eloqua.txt
Will be fixed in our repo.

**Comment by erichjsonfosse** [comment]
@DandelionSprout @Alex-302 this sounds great! Thank you!

Is there anything I should do, other than wait?
Also, am I correct in understanding that the ETA is one week?

**Comment by DandelionSprout** [comment]
I am holding on to which extent EasyPrivacy uses AdGuard Filters' exclusion system as an upsource, as what I understood that Team AdGuard believes it does.

**Comment by DandelionSprout** [comment]
So… EasyPrivacy still contains the false positive entry, despite Alex-302's explanation. I have a couple options left.

Among the remaining options, @-ing @Khrin seems to be worth a try, to see how it goes.

**Comment by ameshkov** [comment]
I don't see any automatic sync with cname-trackers here in the repo, it seems the files are synced manually from time to time? Then probably the false positive should be simply removed from https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_specific_cname_oracle.txt

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b400ab2adc6e7e1a0824876558bc9b5b48031327

> I don't see any automatic sync with cname-trackers here in the repo, it seems the files are synced manually from time to time?

Can't be sync'd due to the amount of dubes in each of the cname lists provided. Just load https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/microsites/oracle-eloqua.txt into 
 https://abpvn.com/ruleChecker/redundantRuleChecker.html

If ADGuard could optimise the CNAME lists (remove the redudant rules), it would be easier to sync @ameshkov @Alex-302

**Comment by erichjsonfosse** [comment]
Looks like we're back on track here. Amazing! Tanks to everyone involved! :raised_hands:
