### ISSUE TITLE
EasyList hide search result from AliExpress

### ISSUE THREAD

**Issue by JaggerDrSpec** [easylist/easylist#18543]
#### List the website(s) you're having issues with:
https://www.aliexpress.com/w/wholesale-ilife-robot-vacuum-cleaner.html

#### What happens?
When EasyList is enabled, ABP hides the search results.

#### Screenshot(s) 
![AliExpress with EasyList Off screenshot_20240213_134716](https://github.com/easylist/easylist/assets/104420507/f316da45-b6a3-4a14-9545-b90090021743)
![AliExpress with EasyList On screenshot_20240213_134716](https://github.com/easylist/easylist/assets/104420507/a0e96920-9108-40bf-8b7e-377f73fe73f6)

#### Filter lists you're using:
EasyList

#### Your settings:
Windows 10
Chrome 121.0.6167.161 (Official Build) (64-bit)
Adblock Plus - free ad blocker 3.24

**Comment by Yuki2718** [comment]
Does adding `aliexpress.com#@?##card-list > .search-item-card-wrapper-gallery:-abp-has(a.search-card-item[href*="&aem_p4p_detail="] div[class*="cards--image--"] > div[class*="multi--ax--"]:-abp-contains(/^(?:AD|An[uú]ncio|광고|広告)$/))` to My filter list fixes the issue?

**Comment by JaggerDrSpec** [comment]
It is much better, i.e. it shows most of it (~80+%).. But there are more results that it hides.. Thanks

**Comment by MarkSpizu** [comment]
Contrary to what the user above says, searches are shown 100%. (60 pages). I disabled uBlock completely and the search results are the same. (60 pages)

I had the same problem 2 days ago. After adding Yuki2718's filter, search results are working again. Thanks!

**Comment by MarkSpizu** [comment]
Contrary to what the user above says, searches are shown 100% (60 pages). I disabled Ublock completely and the search results are the same (60 pages).

I had the same problem 2 days ago. After adding Yuki2718's filter, search results are working again. Thanks!

**Comment by Yuki2718** [comment]
Does `aliexpress.com#?##card-list > .search-item-card-wrapper-gallery a.search-card-item[href*="&aem_p4p_detail="]:has(div[class*="cards--image--"] > div[class*="multi--ax--"]:-abp-contains(/^(?:AD|An[uú]ncio|광고|広告)$/))` in conjuction with already posted `aliexpress.com#@?##card-list > .search-item-card-wrapper-gallery:-abp-has(a.search-card-item[href*="&aem_p4p_detail="] div[class*="cards--image--"] > div[class*="multi--ax--"]:-abp-contains(/^(?:AD|An[uú]ncio|광고|広告)$/))` still hides everything?

**Comment by MarkSpizu** [comment]
I added them both, it doesn't hide anything.

**Comment by MarkSpizu** [comment]
JaggerDrSpec, should provide some screenshots to see results that it hides.

**Comment by Yuki2718** [comment]
> I added them both, it doesn't hide anything.

That's strange. If the rules don't hide anything, the original rule should be safe.

**Comment by JaggerDrSpec** [comment]
Now I think 96-99% is solved.. If less than 1% is hidden, that's fine..
Thank you Yuki2718 and  others
![2024-02-15_01h46_55](https://github.com/easylist/easylist/assets/104420507/077c7bd5-ec1b-4d67-8f9b-10af9f83e32d)
![2024-02-15_01h47_36](https://github.com/easylist/easylist/assets/104420507/284f3df4-a6e2-4dc0-b7d1-0cb1e239a092)
I don't think it should be ideal, because about 90% is more than an excellent search result.
Thank you..

**Comment by Yuki2718** [comment]
> Now I think 96-99% is solved.. If less than 1% is hidden, that's fine..

These hidden items must be ads.
