### ISSUE TITLE
correos.es

### ISSUE THREAD

**Issue by virtualwebgit** [easylist/easylist#18552]
#### Your settings:

- OS/version: Windows 11
- Browser/version: Google Chrome x64 121.0.6167.185
- Ad block extension/version: uBlock Origin 1.55.0

**Comment by Khrin** [comment]
Appears to be blocked correctly with uBlock Origin.

**Comment by virtualwebgit** [comment]
No it is not. Check screenshot
![Untitled](https://github.com/easylist/easylist/assets/113773245/d395b7d6-55d8-4869-a229-68b0c0edd5cb)

**Comment by Khrin** [comment]
Make sure you have "uBlock filters – Cookie Notices" enabled and up to date, along with EasyList Cookies.
