### ISSUE TITLE
igg-games.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18591]
**ad banner**

- https://i.imgur.com/AAO2GJS.png

`A: https://igg-games.com/`

**Comment by dportvine** [comment]
https://github.com/easylist/easylist/issues/17514

<details>
<summary>Screen</summary>

![2024-02-20_220759](https://github.com/easylist/easylist/assets/111344219/e1375b39-754d-4d22-9397-8b5bbce0020e)
</details>

Does EasyList support such rules?

```adblock
igg-games.com,pcgamestorrents.com##a[href][aria-label=""], [width="300"][height^="25"], [width="660"][height^="8"]
```

**Comment by ButterVsMargarine** [comment]
they've been circumventing for a while. it's been addressed multiple times in uBlock Origin's quick-fixes filter list, report there if you see ads
