### ISSUE TITLE
report the anti-adblock (https://www.b2.ai/)

### ISSUE THREAD

**Issue by rnixs** [easylist/easylist#18604]
#### What happens?
It's the new anti-adblock.
Adding a line of script to the website allows you to bypass adblock.
I tested it, but I don't know the exact test method, so I would appreciate it if the Easyist could respond.

If you add that script Snippet to the code like the picture at the bottom, it becomes an anti-adblock function. Please look into it.

#### Screenshot(s) 
<img width="1624" alt="image" src="https://github.com/easylist/easylist/assets/81290656/6b469edc-3991-4f12-bb0a-c5ea1828f6b6">
<img width="946" alt="image" src="https://github.com/easylist/easylist/assets/81290656/edb1c888-338f-455f-8d48-45fa5c2aca51">

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by Yuki2718** [comment]
I wonder if you read README
> For legal reasons, Anti-adblock this will only cover:
>  - Adult websites
> - File or Link hosting/sharing
>  - Streaming/Torrent/Comic sites
 > - Any historical anti-adblock rules

The code actually doesn't cause detection for uBO or AG as we redirect bait requests.

**Comment by Yuki2718** [comment]
Or is this rather ad-injection? I can't reproduce warning or reinjection with some sites using this script.

**Comment by zloyden** [comment]
@Yuki2718 I removed it https://github.com/AdguardTeam/AdguardFilters/commit/e2835b02a2714830c96c2b5922a553bba16189a4 as we need a real example of this.

**Comment by rnixs** [comment]
I will research and comment again.
Even if I put in a script, only the statistics will work normally if the ad is blocked by adblock, and the ability to restore the ad doesn't seem to work yet.

**Comment by Yuki2718** [comment]
As this seems to be ad resinsertion script based on a few examples in publicwww, I guess we can block in EL. But we prefer actual examples as long as possible.
