### ISSUE TITLE
Opened email tracking

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18609]
**privacy**

`<p style=3D"text-align: center;"><a href=3D"https://airlogak.com/track/unsu=
bscribe/v2-123456789" target=3D"_blank" rel=3D"noopener">unsubscribe if you=
 are not interested</a></p><div class=3D"tracking"><img src=3D"https://airl=
ogak.com/track/open/v2-123456789" border=3D"0" width=3D"0" height=3D"0" sty=
le=3D"border:0;width:0px;height:0px;" `

```
/track/open/*
||airlogak.com^$third-party
 ```

**Comment by Daxy7** [comment]
what are these glitches in the text from: `unsu= bscribe` `airl= ogak` `sty= le=3D` ?
