### ISSUE TITLE
seher.no - Blocked images (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#1861]
### Affected site:
`https://www.seher.no/`

### Issue:
Images for recommended/related articles are blocked.

### How to reproduce:
1) Click on one of the articles.
2) Scroll down to the bottom, where there's a list of recommended/related articles.

### Screenshot:

![filterissue-seher1](https://user-images.githubusercontent.com/9382674/45826027-dc115b80-bcf3-11e8-91cf-8251a2e57fc5.jpg)

### Problem filter:
EasyList

### Problem rule:
`_prebid_`

### Possible fix:
`@@_prebid_$domain=seher.no`

### Note:
Sometimes, the images are actually shown, despite the above blocking rule.
But most of the time, the rule completely blocks them!

**UPDATE:**
Apparently, the site switches back and forth between using "prebid" and "lazyload".
That's why the issue is hard to reproduce sometimes.

### Reference;
The issue has been discussed here:
`https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-430295336`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by ryanbr** [comment]
Seems fine here.

**Comment by THEtomaso** [comment]
No, like I pointed out in the first post:

> switches back and forth between using "prebid" and "lazyload".
That's why the issue is hard to reproduce sometimes.
