### ISSUE TITLE
oregonlive.com

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#18633]
false positive. icon flagged.
```
https://www.oregonlive.com/portland/2011/04/portland_schools_makes_claims.html
```
```
@@/ad-choices-$domain=oregonlive.com
```
https://github.com/easylist/easylist/assets/91396482/16791aa7-edc5-4f30-abb2-79e39b1e4ef6

**Comment by Daxy7** [comment]
I only see the image file being allowed, maybe in other sites it allows ads if the full rule is removed?
![image](https://github.com/easylist/easylist/assets/91396482/4647102e-6c02-42fc-b499-9c6be1506fbd)

**Comment by Daxy7** [comment]
This is what the image file in main issue is targeting `9×10 img`
![image](https://github.com/easylist/easylist/assets/91396482/b2d215a7-2bc8-4f23-8722-45bbdb3feebf)
For the Google ad icons too it's meant to hide

**Comment by ryanbr** [comment]
Its fine, minor
