### ISSUE TITLE
www.ouedkniss.com: breakage

### ISSUE THREAD

**Issue by heiwiper** [easylist/easylist#18630]
#### List the website(s) you're having issues with:

`https://www.ouedkniss.com/`

#### What happens?

Website is broken. The page appears for a few seconds then complains about internet access.

#### Screenshot(s) 
![image](https://github.com/easylist/easylist/assets/12894695/cc24ee3d-aad3-46c2-93fc-0f0821cb5dc3)

#### Filter lists you're using:
- Peter Lowe’s Ad and tracking server list
- Online Malicious URL Blocklist
- EasyPrivacy
- EasyList
- uBlock filters

#### Your settings:

- OS/version: Debian GNU/Linux trixie
- Browser/version: Firefox 123.0
- Ad block extension/version: uBlockOrigin 1.56.0

#### Other details:
Apparently the api health check requests are blocked. The website seems to be using this to ensure the user has access to the internet, which explains why the content loads before displaying the error page.
![image](https://github.com/easylist/easylist/assets/12894695/111abba4-c93e-4846-9da5-5a9bea598549)

**Comment by Khrin** [comment]
The site is broken anyway, even with the adblocker turned off.

**Comment by cipher450** [comment]
> The site is broken anyway, even with the adblocker turned off.

That is simply not true. I tried OP setup, and yes, the site does break down after enabling uBlock. But it works if we allow these endpoints, which seem to be essential to the website:

https://api.ouedkniss.com/health/ready
https://api.ouedkniss.com/health
https://api.ouedkniss.com/

In fact, I'm not sure at which point blocking an endpoint named 'health' could help with privacy..., here is a screenshot of the website after disabling the filter for those endpoints:
![Capture d'écran 2024-02-25 031102](https://github.com/easylist/easylist/assets/102109601/6c23b81d-7593-4079-9e56-611dd9809474)

**Comment by Daxy7** [comment]
it's unblocked now?
![image](https://github.com/easylist/easylist/assets/91396482/0c4437f3-24bc-40c3-8407-ffd749f9ce8a)

**Comment by heiwiper** [comment]
> it's unblocked now?
> ![image](https://github.com/easylist/easylist/assets/91396482/0c4437f3-24bc-40c3-8407-ffd749f9ce8a)
> 

Yes it works fine since [this commit](https://github.com/easylist/easylist/commit/b6abfd713b8a5b16408f055ca551194a534ac832) from 2 days ago.

Thanks for the fix ☺️
