### ISSUE TITLE
All domains related to sas.com from SAS Institute Inc. are blocked

### ISSUE THREAD

**Issue by ChitranshuV** [easylist/easylist#18677]
#### List the website(s) you're having issues with:

sas.com
support.sas.com
documentation.sas.com

#### What happens?

These sites are entirely blocked from being accessed. Can't even open them

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/51050888/e38ee8d0-60c1-4825-9f25-492497a17316)

![image](https://github.com/easylist/easylist/assets/51050888/28e087bc-635c-4824-b0e9-3873d7d0b564)

#### Filter lists you're using:

EasyPrivacy on NextDNS and uBlock Origin

https://easylist.to/easylist/easyprivacy.txt

#### Your settings:

- OS/version: Windows 11
- Browser/version: Chromium: 122.0.6261.94 (Official Build) beta (64-bit) and Firefox 115.0.0 ESR
- Ad block extension/version: uBlock Origin 1.56.0

#### Other details:

 SAS is a statistical software suite developed by SAS Institute for data management, advanced analytics, multivariate analysis, business intelligence, criminal investigation, and predictive analytics.

Please check this: https://en.wikipedia.org/wiki/SAS_(software)

**Comment by liamengland1** [comment]
It's a third-party block in easyprivacy. But NextDNS cannot support that as they just read all the domains in EP and unconditionally block them all, ignoring any modifiers. The filter is correct in EP and people using EP as it is intended (as a filterlist for an adblocker browser extension like AdGuard or uBlock Origin) can access those sites without issue.

**Comment by Khrin** [comment]
I guess @ChitranshuV didn't get the answer he was hoping for. I'm closing this issue.
