### ISSUE TITLE
EasyPrivacy is now over 50K entries - causes problems with AdGuard for Safari

### ISSUE THREAD

**Issue by OBgoneSouth** [easylist/easylist#18680]
AdGuard for Safari says:

_Too many filters enabled. Safari cannot use more than 50000 rules in one group._

![Screen Shot 2024-03-04 at 12 51 30](https://github.com/easylist/easylist/assets/110607524/6f669b0a-d009-4066-9172-830a1e14078d)
![Screen Shot 2024-03-04 at 12 52 04](https://github.com/easylist/easylist/assets/110607524/1fdb7c30-07cf-41a2-baca-213c0129f495)

No other lists are active in that group. EasyPrivacy by itself now appears to be too big in AdGuard for Safari.

**Comment by Yuki2718** [comment]
Doesn't AdGuard offer optimized version of EP? Complain to Apple who's been putting unnecessary burden on filter community.
