### ISSUE TITLE
EasyList – Cookie Notices breaks researchgate.net

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#18702]
#### List the website(s) you're having issues with:
`https://www.researchgate.net`

#### What happens?
On the posted website, there is a cookie banner that pop-up after I open the page but cannot be seen with "EasyList – Cookie Notices" filter enabled and then on the page will be a grey wall which will block access to the page.

#### Filter lists you're using:
EasyList/uBO – Cookie Notices - both enabled.

#### Your settings:

- OS/version: Windows 10 
- Browser/version: Firefox 123
- Ad block extension/version: Ublock 1.56

**Comment by Khrin** [comment]
The "cookie banner" is correctly blocked by EasyList Cookie List.
