### ISSUE TITLE
fidelity.com

### ISSUE THREAD

**Issue by tfvlrue** [easylist/easylist#18759]
#### List the website(s) you're having issues with:

`[http](https://digital.fidelity.com/prgw/digital/login/full-page)`

#### What happens?

After logging into Fidelity, it prompts for a 2FA code. Enter the code, select "remember this device", login, and logout. Login again, and it prompts for a 2FA code again. If I disable the `cfa.fidelity.com` filter, it works as expected.

#### Screenshot(s) 

N/A

#### Filter lists you're using:

Default uBlockOrigin lists (which includes EasyPrivacy)

#### Your settings:

- OS/version: Windows 10
- Browser/version: Firefox 123.0.1 (64-bit)
- Ad block extension/version: uBlock Origin 1.56.0

#### Other details:

The `||cfa.fidelity.com^` rule in EasyPrivacy seems to be causing this. If I add a custom rule `digital.fidelity.com https://cfa.fidelity.com script allow` and login again, it works correctly (the 2FA is remembered instead of prompting on every login).

**Comment by ryanbr** [comment]
Used for threatmetrix tracking;

```
https://cfa.fidelity.com/pllrif2dlpyvtmse.js?x0m9cgsdwj9ayy02=5h8i3ud8&s2r58c2n8uasxcuj=D21D761C29143304D6AA769900C9E5B0
https://cfa.fidelity.com/g62lnra2s3b0nseg.js?4dye6megaoiiietp=5h8i3ud8&s6bb569j9361xxsj=742e460a66124f65ac8c88a46792bc76&vatarxl99r6n69if=2
```
