### ISSUE TITLE
indiatoday.in

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18772]
**annoyance**
```
indiatoday.in##.story__recommended__chunk
```

- https://i.imgur.com/YZJGk7u.png

```
||tosshub.com/sites/player/media/sana-widget/
```

- https://i.imgur.com/vLnMRqD.png

**privacy**
```
||feeds.intoday.in/geocheck
```

`https://www.indiatoday.in/technology/news/story/editing-text-on-google-gemini-just-became-easier-thanks-to-a-new-feature-here-is-how-it-works-2511844-2024-03-07`

**Comment by Khrin** [comment]
@smed79  I think only one of them should really be blocked.
