### ISSUE TITLE
Update curalate.com domain wide EasyPrivacyList block

### ISSUE THREAD

**Issue by theclarkroberts** [easylist/easylist#188]
curalate.com was blocked on a domain level on the EasyPrivacyList
```
||curalate.com^$third-party
```

This is disrupting valid non-tracking functionality on clients sites where we are a 3rd party. This was added here: https://forums.lanik.us/viewtopic.php?f=62&t=27199&p=82574

Then an appeal was discussed in some detail here, but we never heard back: https://forums.lanik.us/viewtopic.php?f=64&t=30064&p=95579

Here are two examples of a page that breaks with the current EasyPrivacy rules:
http://www.urbanoutfitters.com/urban/uo-community?cm_re=UOONYOU
http://like2b.uy/nordstrom/

As you can see in the network trace all Curalate tracking happens as part of the api.curalate.com/v1/events.jsonp calls. Can we update the privacy list to specifically block this call pattern instead of a domain wide block? 

```
||curalate.com/*events*$third-party
```

If not, can you recommended a better practice to differentiate our primary functionality from our tracking functionality on 3rd party sites?

**Comment by monzta** [comment]
This should do it: https://github.com/easylist/easylist/commit/8e4276a49e06d3fd47cdb0d3d10c210365282358 

Sorry for the late update!

**Comment by theclarkroberts** [comment]
@monzta Thank you. We validated on our end that the core functionality is unblocked and tracking events are blocked.
