### ISSUE TITLE
sportskeeda.com

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#18813]
inline ad
`https://www.sportskeeda.com/minecraft/how-change-resolution-minecraft`
`! NOT OPTIMIZED`
`||staticg.sportskeeda.com/skm/assets/promotional-content/2023/Fortnite-item-shop/Desktop/fortnite-d-banner-02.png`
`sportskeeda.com##.promoted-img`
`sportskeeda.com###fortnite-promotional-banner`

**Comment by Khrin** [comment]
There is no real reason for it to be blocked in EasyList.
