### ISSUE TITLE
https://notthebee.com/takes/

### ISSUE THREAD

**Issue by allanonmage** [easylist/easylist#18857]
#### List the website(s) you're having issues with:

```
https://notthebee.com/takes
```
Specifically, the section of their website with /takes/.  The rest of the site loads fine.  Example here:
https://notthebee.com/takes/how-much-cannibalism-is-too-much-cannibalism-nbc

#### What happens?

With the EasyList - Newsletter Annoyances list enabled in uBlock Origin (in multiple versions of Waterfox on desktop, firefox on mobile), all I get is header and a blank page (image below).  If you disable that specific list, and run first party scripts, the page loads fine.  I took a look in F12, and the article content simply isn't there, so that's as far as I got troubleshooting.  Sometimes the page will load without first party scripts, sometimes it won't.  Not sure if that will help you diagnose anything.

I didn't see the newsletter popup when I saw the article, which could be due to "I still don't care about cookies", which is a single-purpose extension that tends to block those sorts of things.  I am running NoScript and several other extensions, but the behavior tracks down to this one list in uBlock.  I was unable to find anything else that affected it.

#### Screenshot(s) 

![easylist white page](https://github.com/easylist/easylist/assets/3002722/60e4448c-0468-4a07-adb9-769e3d9da4a4)

#### Filter lists you're using:

uBlock Origin default lists, plus all of the EasyList Annoyances list(s).

#### Your settings:

Yes, I have settings.

- OS/version: Windows 10 22h2 (x2), Android
- Browser/version: waterfox (1 version old) x2, firefox for android (old AF so that I can run extensions)
- Ad block extension/version: 1.56

#### Other details:

See above.

**Comment by Khrin** [comment]
No issues seen here.
