### ISSUE TITLE
Request to remove move social media follow buttons.

### ISSUE THREAD

**Issue by linlinxza** [easylist/easylist#18854]
Just add this to Fanboy's Social Blocking list:

`##.followus`

Also, is there a chance that somehow some kind of expression could be used to remove buttons like these?

`##[href="https://twitter.com/DeviantArt"]`

`##[href="https://facebook.com/DeviantArt"]`

`##[href="https://instagram.com/DeviantArt"]`

**Comment by Khrin** [comment]
Too generic.

**Comment by linlinxza** [comment]
> Too generic.

What the Hell does that mean? lol
