### ISSUE TITLE
eu-teams.events.data.microsoft.com

### ISSUE THREAD

**Issue by sertonix** [easylist/easylist#18851]
#### List the website(s) you're having issues with:

`teams.microsoft.com` (logged in) send a POST request to `https://eu-teams.events.data.microsoft.com/OneCollector/1.0/?cors=true&content-type=application/x-json-stream&content-encoding=gzip`

#### What happens?

I saw these tracking requests every minute or so while logged in.

**Comment by Khrin** [comment]
Blocking this domain is known to have caused false positives in the past.
