### ISSUE TITLE
hubcloud.day [Ads]

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#18878]
banner ads on `https://hubcloud.day/video/eyyi1pboiiv17eo`

ublock origin default filters+ firefox android
![Screenshot_20240329-092028-717.png](https://github.com/easylist/easylist/assets/20338483/a28ae455-0b03-4803-a0a0-742aba8e527d)

**Note** = domain changes frequently

**Comment by Daxy7** [comment]
> Note = domain changes frequently

for ubo quick fixes/filters?
