### ISSUE TITLE
sberbank.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#18901]
Please add (EasyList – Cookie Notices): `sberbank.com##+js(set-cookie, sbrf.pers_notice, 1)`

Example: `https://www.sberbank.com/sberprime/plus`

<details>
<summary>Screenshot(s)</summary>

![Sber](https://github.com/easylist/easylist/assets/20126984/c9461a41-ca93-42b9-b03d-43056a1841ca)

</details>

**Comment by dimisa-RUAdList** [comment]
@ryanbr

**Comment by dimisa-RUAdList** [comment]
@ryanbr

**Comment by zhhhh-dev** [comment]
Please add (EasyList – Cookie Notices)
https://online.sberbank.ru/CSAFront/index.do

<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/afc85200-86b7-4b8b-a340-3d2831f1d225" />

**Comment by dimisa-RUAdList** [comment]
`online.sberbank.ru##[data-testid="cookie-policy"]`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/251e5c4ad6cb79ed062ba7a5cf0eaf17587de377
