### ISSUE TITLE
free-icon-rainbow.com

### ISSUE THREAD

**Issue by Am4hisa** [easylist/easylist#18906]
#### List the website(s) you're having issues with:

https://free-icon-rainbow.com/dustpan-icon-5/

#### What happens?

Ads 

#### Screenshot(s) 
  
https://i.ibb.co/vHy39Qk/image.png

#### Filter lists you're using:

Easylist

#### Your settings:

- OS/version: Windows 10
- Browser/version:  Chrome 125.0.6382.3
- Adblock extension/version: AdGuard Browser extension Ver4.3.35

**Comment by 3kh0** [comment]
```
free-icon-rainbow.com###ad_responsive
```
