### ISSUE TITLE
nordicmag.info

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18912]
**annoyance**

big gif animated banner images.

- `https://www.nordicmag.info/wp-content/uploads/2023/03/Boutique.gif`
- `https://www.nordicmag.info/wp-content/uploads/2024/02/BD_Mondiaux-Biathlon.gif`

A: `https://www.nordicmag.info/`

**Comment by Khrin** [comment]
The site seems to be in French only?

**Comment by Khrin** [comment]
Sorry for the misunderstanding.
