### ISSUE TITLE
fileditch.com 

### ISSUE THREAD

**Issue by Am4hisa** [easylist/easylist#18910]
#### List the website(s) you're having issues with:

https://fileditch.com 

#### What happens?

Ad 

#### Screenshot(s) 
  
 https://img.imageride.net/images/2024/04/03/chrome_v8wtGQoFM9.png

#### Filter lists you're using:

Easylist

#### Your settings:

- OS/version: Windows 10
- Browser/version:  Chrome 125.0.6382.3
- Adblock extension/version: AdGuard Browser extension Ver4.3.35

**Comment by 3kh0** [comment]
```
##[href^="https://hostslick.com/clients/link.php"]
```
Works for me
