### ISSUE TITLE
freepik.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#18947]
```
freepik.com##._1286nb18b
freepik.com##._1286nb1rx
freepik.com##.spr-adblock
||stock.adobe.com/*&as_content=popup&$popup
```

- https://i.imgur.com/N5VOjQW.png
- https://i.imgur.com/rE6gWJs.png

`A: https://www.freepik.com/search?format=search&query=wave`

**Comment by Khrin** [comment]
@smed79 Could not reproduce the popup.
