### ISSUE TITLE
block https://lms.roblox.com/recipe?iteration=0 for pixel trackers

### ISSUE THREAD

**Issue by loadstring1** [easylist/easylist#18967]
#### List the website(s) you're having issues with:

```
https://www.roblox.com/home
```

#### What happens?

```
https://lms.roblox.com/recipe?iteration=0
```

This URL returns all 1 pixel trackers related to roblox and ublock origin default lists fail to block all of them. I want easyprivacy to block that URL and that would solve this issue of roblox's pixel trackers bypassing ublock's filters.

#### Screenshot(s) 

![Zrzut ekranu 2024-04-11 191013](https://github.com/easylist/easylist/assets/156520308/db8242be-02f4-4f7f-8ebf-73877a9b1a59)
![Zrzut ekranu 2024-04-11 191205](https://github.com/easylist/easylist/assets/156520308/6f50342f-fae7-41e8-9c80-eb9dcc679dce)

#### Your settings and filter lists included:

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 133276
 cosmetic: 54217
 scriptlet: 19203
 html: 1766
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37545-108, 3h.58m Δ
  ublock-badware: 8072-0, 3h.58m Δ
  ublock-privacy: 789-1, 3h.58m Δ
  ublock-unbreak: 2301-2, 3h.58m Δ
  ublock-quick-fixes: 152-45, 3h.58m Δ
  easylist: 85256-148, 3h.58m Δ
  easyprivacy: 50480-60, 6m
  urlhaus-1: 11875-5, 8h.1m
  plowe-0: 3766-1189, 8d.5h.44m
  POL-0: 8740-38, 8h.1m
  POL-2: 1283-48, 8m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 224 ms (selfie)
 maxAssetCacheWait: 61 ms
 cacheBackend: indexedDB
```
- OS/version: Windows 11 home 22h2
- Browser/version: Firefox nightly 126
- Ad block extension/version: Ublock Origin 1.57.2

#### Other details:

You need to have a roblox account to repro this

**Comment by loadstring1** [comment]
silly me it took only one issue in uAssets repo.
https://github.com/easylist/easylist/commit/9af379c60467ef3824b30330585d40c203171051

**Comment by Daxy7** [comment]
Do report here aswell to get better coverage of the issue.
