### ISSUE TITLE
francetvinfo.fr Hiding cookie consent prevents scrolling 

### ISSUE THREAD

**Issue by mavdl2117** [easylist/easylist#18963]
#### List the website(s) you're having issues with:

`https://www.francetvinfo.fr/replay-radio/un-monde-d-avance/pekin-a-profite-de-la-derniere-election-a-taiwan-pour-tester-ses-nouveaux-outils-de-desinformation-a-base-d-intelligence-artificielle_6449332.html`

#### What happens?

Hiding cookie consent prevents scrolling **ON MOBILE**

#### Filter lists you're using:

Brave's defaults (aggressive) + Fanboy's Annoyances + uBlock Annoyances + Adguard Français

#### Your settings:

- OS/version: iOS 
- Browser/version: 1.63.2
- Ad block extension/version:

**Comment by Khrin** [comment]
No issues with EasyList Cookie.
