### ISSUE TITLE
flip.gr: Blocked cookie notice causes website to be unusable

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#18978]
#### List the website(s) you're having issues with:

`https://flip.gr`

#### What happens?

The website has a cookie notice that's being blocked by EasyList, but there's a grayish blue background that isn't blocked. This situation renders the website unusable unless the adblocker is turned off, allowing the user to click on "accept," and then reload the website with the adblocker turned back on.

#### Screenshot(s) 

EasyList/Adblock on:
<img width="1544" alt="image" src="https://github.com/easylist/easylist/assets/123986260/74447025-0e06-4b05-9959-61725b8a5679">
EasyList/Adblock off:
<img width="1551" alt="image" src="https://github.com/easylist/easylist/assets/123986260/22d0de2c-6cd3-4f79-95c7-956251c2d8dc">

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: macOS Sonoma 14.4
- Browser/version: Safari
- Ad block extension/version: AdGuard

**Comment by Khrin** [comment]
The cookie warning appears to be blocked correctly.
