### ISSUE TITLE
Quark Browser scareware/adware ads

### ISSUE THREAD

**Issue by CatMe0w** [easylist/easylist#18981]
#### List the website(s) you're having issues with:

https://181ue.com and more. Read below for details.

#### What happens?

Over the past few years, "Quark Browser" developed by UC Mobile Ltd. (优视科技, "you shi ke ji"), has been promoting their product in a way that malware and phishing sites typically use: registering a large number of random domain names, as well as grabbing expired domain names from others, and placing threatening advertisements as shown in the screenshot.

Translation of the ads:

```
EMERGENCY NOTICE
This site is only accessible with Quark/dedicated browsers!

[Open with Quark]

Quark to access the site.
No ads
No lag in movie playback
Save the video to the net disk and watch it anytime
```

The number of domains hijacked for the purpose of placing this ad is so high that it is impossible to block them all, especially since some of them were originally normal websites.

All sites containing this ad are displaying it using fixed js from the Quark Browser developer's website:

```
https://image.uc.cn/s/uae/g/3o/berg/static/archer_index.[random hash or unique identifier].js
https://image.uc.cn/s/uae/g/3o/berg/static/index.[random hash or unique identifier].css
```

Suggested rules:
```
||image.uc.cn/s/uae/g/3o/berg/static/^
```

#### Screenshot(s) 

![quark_scareware](https://github.com/easylist/easylist/assets/7774491/5dd12d0f-6f93-46c6-8177-35c98478d51f)

#### Filter lists you're using:

uBlock Origin built-in filters, EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe’s Ad and tracking server list

#### Your settings:

- OS/version: Any desktop OS
- Browser/version: Chromium 123
- Ad block extension/version: uBlock Origin 1.57.0

#### Other details:

N/A

**Comment by Khrin** [comment]
EasyList does not block malware.

**Comment by CatMe0w** [comment]
Sorry, but thsi is not malware, just intrusive ads.

These ad pages download legitimate software.
