### ISSUE TITLE
Allow direct link: logtail.com 

### ISSUE THREAD

**Issue by curusarn** [easylist/easylist#18997]
Hi! 👋 
`logtail.com` is a domain with a legit associated website.
It should be using `^$third-party` instead of being blocked completely.

#### List the website(s) you're having issues with:

`logtail.com`

#### What happens?

`logtail.com` link should show me homepage for Better Stack Logs
It's the same product just now under a different name.
<img width="888" alt="image" src="https://github.com/easylist/easylist/assets/10132717/69b3bb24-db2f-4cc2-8436-10ce281024cf">

There are a lot of links all over the internet leading to `logtail.com` e.g. from HackerNews or DigitalOcean:
- `https://news.ycombinator.com/item?id=28628515`
- `https://marketplace.digitalocean.com/add-ons/logtail`

For all of these links I now get a warning instead of seeing the page:
<img width="1041" alt="image" src="https://github.com/easylist/easylist/assets/10132717/c638779c-93de-4093-be4d-d66edb90c296">
I should see the homepage:
<img width="1161" alt="image" src="https://github.com/easylist/easylist/assets/10132717/3c882068-1df4-4bc0-bd19-602221336d42">

#### Filter lists you're using:

EasyPrivacy

Thank you!

**Comment by ryanbr** [comment]
This only redirecting to a legit site? logtail isn't a legit site

**Comment by curusarn** [comment]
> This only redirecting to a legit site? logtail isn't a legit site

`logs.betterstack.com` is a homepage of logtail.

What do please mean by "logtail isn't a legit site"?

**Comment by Daxy7** [comment]
I can read more details about issue without these large appended images.
opening `https://logtails.com/` without credentials, the average user is redirected to `https://betterstack.com/logs`
<details>

```

Hi! 👋
logtail.com is a domain with a legit associated website.
It should be using ^$third-party instead of being blocked completely.
List the website(s) you're having issues with:

logtail.com

What happens?

logtail.com link should show me homepage for Better Stack Logs
It's the same product just now under a different name.
(image)

There are a lot of links all over the internet leading to logtail.com e.g. from HackerNews or DigitalOcean:

    https://news.ycombinator.com/item?id=28628515
    https://marketplace.digitalocean.com/add-ons/logtail

For all of these links I now get a warning instead of seeing the page:
(image)
I should see the homepage:
(image)
Filter lists you're using:
EasyPrivacy

Thank you!

```

</details>

**Comment by ryanbr** [comment]
Just link to the ACTUAL site, betterstack.com
