### ISSUE TITLE
Creative Commons Licensing Icons are blocked

### ISSUE THREAD

**Issue by ExperiBass** [easylist/easylist#19017]
#### List the website(s) you're having issues with:
`experibassmusic.eth.limo`, but happens anywhere the CC icons are loaded, including localhost.

#### What happens?
The Fanboy annoyances list [seems to block images from creativecommons.org (link to line)](https://github.com/easylist/easylist/blob/6f83921f3c62dcd895673a682aa9619cbe33476d/fanboy-addon/fanboy_annoyance_thirdparty.txt#L56), but this has the side effect of blocking their license icons hosted at `mirrors.creativecommons.org`.

To Reproduce:
- Add the CC icons to a html page, like
```html
<img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" />
<img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" />
```
- Open the page in your browser.
- Watch as none of the images load.

#### Screenshot(s) 
working, with `EasyList – Other Annoyances` **dis**abled:
![working](https://github.com/easylist/easylist/assets/33764485/b0d8262f-054e-49d6-989b-65c2aeb32347)  
not working, with `EasyList – Other Annoyances` **en**abled: 
![not working](https://github.com/easylist/easylist/assets/33764485/e7930b35-dd08-46ee-b807-01ab5ceed9dd)

#### Filter lists you're using:
Most of UBlocks offerings except `Dan Pollock’s hosts file`, `Cookie Notices`, and `uBlock filters – Annoyances`.

#### Your settings:

- OS/version: Linux (Rolling)
- Browser/version: Firefox v124.0.1
- Ad block extension/version: UBlock Origin v1.57.2

**Comment by ryanbr** [comment]
We don't need more icons, the license still remains. Just create a personal exception
