### ISSUE TITLE
WebMD shows banner ads

### ISSUE THREAD

**Issue by edgan** [easylist/easylist#1901]
### What happens?
I see a top and left side banner for things like CVS.

URL:
`https://www.webmd.com/vitamins/ai/ingredientmono-805/gamma-linolenic-acid`

Elements like:
<code>###-muccuzs_org_wtfoas_\/8756878\/qcbgiasf\/kspar_4</code>

### List Subscriptions you're using:
EasyList

### Versions
Fedora 28 Linux
Chromium 68
uBlock origin 1.16.18
HTTP Everywhere 2018.9.19

**Comment by peace2000** [comment]
I don't see any ads on that page anymore. Not relevant. @Khrin
