### ISSUE TITLE
please remove 'dingxiang-inc.com/ctu-group/constid-js/index.js'

### ISSUE THREAD

**Issue by gonenoob** [easylist/easylist#19011]
i am developer of dingxiang-inc.com/ctu-group/constid-js/index.js， it  is not ad， it is used for security，please remove from the list

**Comment by ryanbr** [comment]
Stop fingerprinting users. I came from 2020. 

https://github.com/easylist/easylist/commit/858040059d8a9b5fa952c76eaa2ffd3d827c0b26
