### ISSUE TITLE
Forbes video player blocked www.forbes.com/video/

### ISSUE THREAD

**Issue by ignisfire** [easylist/easylist#19015]
#### List the website(s) you're having issues with:

```
https://www.forbes.com/video/6320603187112/
https://www.forbes.com/video/cb4e4961-14cd-43c1-90a8-13e3086c5cdc/
```

#### What happens?

The video player is blocked. Ads should be blocked, correct, but the video player itself plays video content, that is part of the forbes.com content itself, and the actual viewer has intent to watch it when visiting the page.

#### Filter lists you're using:

Blocked by uBlock origin, using easylist.

#### Your settings:

- OS/version: MacOs 14.2.1 (but repeatable also on Win)
- Browser/version: Chrome 123.0.6312.124 (but repeatable on any other, that QA tested with)
- Ad block extension/version: uBlock origin

#### Other details:

Filter rule in question `||elements.video^$third-party`: https://github.com/easylist/easylist/blob/e293e977be06ef82aa7c5753b58fe52dcfe3f26e/easylist/easylist_specific_block.txt#L671
Possible fix: `||elements.video^$third-party,domain=~forbes.com`

The `elements.video` domain loads video assets only (player/mp4s/thumbs), while ads requests are done via adx and can remain blocked that way.

Thanks!

**Comment by Daxy7** [comment]
`https://www.forbes.com/sites/daveywinder/2024/04/13/gmail-and-youtube-hackers-bypass-googles-2fa-account-security/`
Best place it can go is Fanboy's annoyance list as [the content is unrelated to article](https://github.com/easylist/easylist/assets/91396482/701e0a06-a9d9-4a60-afaf-e7f44e8ac0e7) and the logger of uBO is [spammed 6 times every 6 seconds for no good reason](https://github.com/easylist/easylist/assets/91396482/757799fb-7581-40e2-b022-54477d36ef7a)
