### ISSUE TITLE
khanacademy.org - important URLs removal request

### ISSUE THREAD

**Issue by lizfaubell** [easylist/easylist#19033]
#### List the website(s) you're having issues with:

```
khanacademy.org/api/internal/_bb/
khanacademy.org/api/internal/_analytics/
```

#### What happens?

Hello, I'm reaching out from the Khan Academy team on behalf of complaints from our users. There was a recent change introduced that blocks some of our important endpoints which we use to measure student learning time: ```https://github.com/easylist/easylist/pull/18896```

Learning time is a metric displayed in our in-product dashboards for students, teachers, parents, and school administrators. When the time is blocked, then educators, parents and students are not able to see critical data in their dashboards that are used for insights. In this case the word "analytics" refers to our ability to show this data to our learners and teachers. This information is in NO way sold to external partners.

Could we please get these removed from easylist? In particular, the `khanacademy.org/api/internal/_analytics` and `khanacademy.org/api/internal/_bb` endpoints.

Please reach out for any other information needed.

Thank you.

#### Screenshot(s) 

<img width="1265" alt="Screenshot 2024-04-19 at 3 59 37 PM" src="https://github.com/easylist/easylist/assets/50882112/c29c5a21-9175-40eb-968d-735e1827069e">

**Comment by dat-boris** [comment]
Hi there, also want to clarify that Khan Academy is a non-profit, and we are using these endpoints to provide important site features related to Learning Time.

As explained in https://support.khanacademy.org/hc/en-us/articles/202487520-What-are-Khan-Academy-s-privacy-principles

> We do not sell your personal information to third parties. We established Khan Academy as a not-for-profit organization so that our mission of education and your trust will not be in conflict with a for-profit motive.

**Comment by ryanbr** [comment]
Okay, how about we reach a middle ground, just remove `khanacademy.org/api/internal/_bb`
