### ISSUE TITLE
comss.ru

### ISSUE THREAD

**Issue by dportvine** [easylist/easylist#19034]
### List the website(s) you're having issues:

`https://www.comss.ru/disqus/page.php?id=13433`

### What happens?

Chat is blocked `||talk.hyvor.com/embed/` ~> **EasyList**

<details>
<summary>Screen</summary>

![2024-04-21_093606](https://github.com/easylist/easylist/assets/111344219/3a8626f7-c58a-45fd-a9ac-6505c5a1a935)
![2024-04-21_093620](https://github.com/easylist/easylist/assets/111344219/8416268e-1ab7-4669-a8d2-9e0e9edefa8f)
![2024-04-21_093642](https://github.com/easylist/easylist/assets/111344219/cb05dd53-9088-4f33-b360-f9373845d395)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome (stable)
- Adblock Extension/version:  uBO (stable)

**Comment by dportvine** [comment]
@ryanbr

**Comment by dimisa-RUAdList** [comment]
Temporary fix: https://github.com/easylist/ruadlist/commit/c0c10db3f72bbf73ed14defeadb9de30d2ba3bae
