### ISSUE TITLE
dnoticias.pt

### ISSUE THREAD

**Issue by holdit** [easylist/easylist#19031]
#### List the website(s) you're having issues with:

dnoticias.pt

#### What happens?

1. Some ads are displayed.
2. Annoying "popups" about a podcast.
3. Recommended articles in the middle of the news.

#### Screenshot(s) 

For 1):
<img width="698" alt="Screenshot 2024-04-19 at 21 48 20" src="https://github.com/easylist/easylist/assets/23439751/23fcbab8-11f1-4bc2-9e26-406433799337">

For 2):
<img width="456" alt="Screenshot 2024-04-19 at 21 48 11" src="https://github.com/easylist/easylist/assets/23439751/f27f87a5-674d-4e66-a64e-dbc9114d8364">

For 3):
<img width="698" alt="Screenshot 2024-04-19 at 21 48 28" src="https://github.com/easylist/easylist/assets/23439751/ef9b57d4-6e87-46eb-a552-5f27771b105a">

#### Fixes:

To fix 1), the ads, files are loaded from: `ad.dnoticias.pt`. This can be blocked without breaking the site.

Cosmetic rules:
`dnoticias.pt##.pub--wrapper`
`dnoticias.pt##div.comercial`

To fix 2), hide the "popup" annoyance advertising the podcast:
`dnoticias.pt##.podcasts-home`

To fix 3), hide the multiple article suggestions inside the articles:
`dnoticias.pt##.editor-reference`

**Comment by Khrin** [comment]
@holdit Ads from Portuguese-language websites are blocked in EasyList Portuguese. `https://easylist-downloads.adblockplus.org/easylistportuguese.txt`
