### ISSUE TITLE
Why is 0.0.0.1 blocked?

### ISSUE THREAD

**Issue by ChiefArug** [easylist/easylist#19041]
The ip address 0.0.0.1 is blocked according to this line: https://github.com/easylist/easylist/blob/7f894946737009e7cd27679c91f1b40d12484605/easyprivacy/easyprivacy_trackingservers.txt#L5-L6
However 0.0.0.1 is an internal ip address (as said [on superuser](https://superuser.com/questions/1436913/what-is-ip-address-0-0-0-1-for-and-how-to-use-it), [quora](https://www.quora.com/Is-0-0-0-1-a-valid-public-IP-address) and the [who is page](https://who.is/whois-ip/ip-address/0.0.0.1)) so it seems like it shouldn't belong on a list of trackers, as any abuse coming from it would be coming from something on your local network and to simply put it be a 'you problem'. In theory blocking local addresses like this could prevent some things from working properly, although I have no examples of that happening.

Why is it on the list?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ad1add01845ce345b0d351bec7af0dec2ee6e38a

`23:57:03   ||0.0.0.1^   --   www.firstpersonalinjury.co.uk     get      image        https://0.0.0.1/`

**Comment by ryanbr** [comment]
Just use git to search for the addition?

**Comment by ChiefArug** [comment]
I saw that, but it didn't really provide an answer.
How/why would a site be trying to fetch from a local ip address? Why does that need blocking?

**Comment by ChiefArug** [comment]
Huh, thank you. Im suprised something like this isn't seen of more of an issue and protected by web browsers by default.
