### ISSUE TITLE
adcreative.*

### ISSUE THREAD

**Issue by incetarik** [easylist/easylist#19059]
#### List the website(s) you're having issues with:
adcreative.chargebee.com

#### What happens?

Our payment processor link is adcreative.chargebee.com and we do not want to get it blocked on your list as it starts with `adcreative` although we are a startup based in Paris who generates ad visuals, we do not do any ads and or anything similar.

Currently the urgent part is removing our payment processors link: [adcreative.chargebee.com](http://adcreative.chargebee.com/) from your ad blocker list and if possible, any domains matching `*.adcreative.ai`

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: Windows and MacOS
- Browser/version: Chrome/124.0.6367.60 and Firefox 125.0.1 and Safari
- Ad block extension/version: AdGuard / uBlock / AdBlocker

#### Other details:

Thank you.

**Comment by Yuki2718** [comment]
Please provide a testable link for an actual issue.

**Comment by incetarik** [comment]
Hi @Yuki2718 

You can go here to sign up to do the first step: https://suite.adyouneed.com/authentication/register but this error happens across all our domains such as: [app.adcreative.ai](http://app.adcreative.ai/)

On the next step where we ask the payment method, you can write any card detail, and you will see that the JS is blocked because of the ad blockers.

We believe that this is because `/adcreative.$domain` in the `easylist` blocks our payment processor link: “adcreative.chargebee.com” screenshots are attached.

![telegram-cloud-photo-size-4-5859457778823840313-y](https://github.com/easylist/easylist/assets/14037316/69396fa5-8860-4c0d-98d5-43195a4793a6)

and


![telegram-cloud-photo-size-4-5861539635371556738-y](https://github.com/easylist/easylist/assets/14037316/9b4c9c24-a38a-479b-ab77-a01b876e8bb3)

**Comment by incetarik** [comment]
@Yuki2718

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/4ad1c09c87b3bf71cd30d5bdc84be44e0f404637
