### ISSUE TITLE
ab.gr: Cookie notice

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#19076]
#### List the website(s) you're having issues with:

https://www.ab.gr

#### What happens?

There is a cookie notice in the middle of the website.

#### Screenshot(s) 

<img width="1633" alt="image" src="https://github.com/easylist/easylist/assets/123986260/7c52b4ea-3936-460d-8410-413485f0b4fe">

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: macOS Sonoma 14.4
- Browser/version: Safari
- Ad block extension/version: AdGuard

**Comment by ryanbr** [comment]
Part of uBO Cookies, enabled Annoyances-Cookies from uBO
