### ISSUE TITLE
#19104 For the same reason, additional modifications are required

### ISSUE THREAD

**Issue by loana2918** [easylist/easylist#19105]
@piquark6046

Refer this [#19104](https://github.com/easylist/easylist/issues/19104)
This domain needs to be removed from that filter for the same reason.
```
||bamgosu.com^$document, popup
```

**Comment by loana2918** [comment]
<img width="960" alt="image" src="https://github.com/easylist/easylist/assets/164298716/a2661563-23e8-4ecd-81f5-804f7f3e636e">

**Comment by loana2918** [comment]
![image](https://github.com/easylist/easylist/assets/164298716/0f83d7b7-ac10-464e-9c77-f77404fd001f)

**Comment by piquark6046** [comment]
The filter does not exist. Please reload the file viewer.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/f755a14d1f8334c90f033aea83f7155eec705b5f
