### ISSUE TITLE
blaze1.space

### ISSUE THREAD

**Issue by aiin431** [easylist/easylist#19115]
#### List the website(s) you're having issues with:

`https://blaze1.space/en/sports`

#### What happens?

Sportsbook is not loading

#### Screenshot(s) 

![Screenshot_2024-05-05_16-02-39](https://github.com/easylist/easylist/assets/7754272/18ac388d-b539-4892-974e-fd7e145b2072)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: Windows 11
- Browser/version: Chromium 123
- Ad block extension/version: AdBlockPlus 3.25.1

#### Other details:

Issue with loading `https://blaze.sptpub.com/bt-renderer.min.js`

**Comment by andr83** [comment]
There is a related PR: https://github.com/easylist/easylist/pull/19113
