### ISSUE TITLE
pornhub.com

### ISSUE THREAD

**Issue by BlazDT** [easylist/easylist#1912]
Following rule is breaking pictures, scripts:

|https://$image,xmlhttprequest,domain=pornhub.com|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com

**Comment by krystian3w** [comment]
Temporarily repaired in uBo, by completely turning off the filter (,badfilter).

https://github.com/uBlockOrigin/uAssets/commit/1c854563f696926c2ba2cc34893d92f6dd54e6dd

**Comment by ryanbr** [comment]
Works fine now.

**Comment by krystian3w** [comment]
@okiehsch
