### ISSUE TITLE
www.catalannews.com

### ISSUE THREAD

**Issue by brad2014** [easylist/easylist#19151]
#### List the website(s) you're having issues with:

`www.catalannews.com`

#### What happens?

cookie div is blocked, but underlying page-overlay remains, locking up web page.

#### Filter lists you're using:

EasyList - Cookie Notices

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version: 

#### Other details:

Easylist-Cookie Notices contains
```
##div.cookie-consent
```

In order to make the page work, I had to add
```
www.catalannews.com##div:has(> div.cookie-consent)
```

Additionally, I believe one could set the cookie cookie on load:
```
document.cookie="cookieConsent-2022-11=false" 
```

The HTML of the raw home page contains:

```
<div style="position:fixed;left:0;top:0;width:100%;height:100%;z-index:999;background-color:rgba(0,0,0,0.3)" class="">
	<div class="cookie-consent" style="align-items:baseline;background:#353535;color:white;display:flex;flex-wrap:wrap;justify-content:space-between;left:0;position:fixed;width:100%;z-index:999;bottom:0">
		<div style="flex:1 0 300px;margin:15px" class="">
			<p>This website uses third-party cookies to analyze our traffic.</p>
		</div>
	<div class="">
		<button style="background:#ffd42d;border:0;border-radius:0px;box-shadow:none;color:black;cursor:pointer;flex:0 0 auto;padding:5px 10px;margin:15px" class="" id="rcc-confirm-button" aria-label="Accept all cookies">Accept all</button><button style="background:gray;border:0;border-radius:0px;box-shadow:none;color:#e5e5e5;cursor:pointer;flex:0 0 auto;padding:5px 10px;margin:15px" class="" id="rcc-decline-button" aria-label="Read more about the cookies policy">Read More</button>
	</div>
</div>
```

**Comment by Khrin** [comment]
@brad2014 is it still broken for you?

**Comment by brad2014** [comment]
It is now working.  I am closing this.

I see cookieyes.com/client_data has been blocked for two years, so I'm not sure why that wasn't working.  Perhaps some bad interaction with native browser blocking.

https://github.com/easylist/easylist/blame/9e15e40f1a9f3697e6a3738aff4cc15b0cf28951/easylist_cookie/easylist_cookie_thirdparty.txt#L26

**Comment by Khrin** [comment]
possibly related to https://github.com/easylist/easylist/commit/e224a5243418b174b208b0fe0b2529d381c401e0 which apparently have a similar issue as described for `catalannews.com` (and hopefully is resolved too)
