### ISSUE TITLE
gaiaonline.com Flash embed script blocked

### ISSUE THREAD

**Issue by n0samu** [easylist/easylist#19166]
#### List the website(s) you're having issues with:
http://www.gaiaonline.com/tank/3644166/

#### What happens?
The page appears blank because this Flash embed script is blocked by EasyList:
`https://cdn1.gaiaonline.com/src/_/e143bb5df5304ae98988a03a4dabca2e-1483-401/src/js/flash/AC_OETags.js`

With EasyList disabled, the Flash embed (orange play button) appears as expected.

#### Screenshot(s) 
**Expected** - orange play button appears:
![image](https://github.com/easylist/easylist/assets/71368227/3ee57ab8-b72b-4e6a-aba0-92c9b2cd607f)

**Actual** - the page appears blank:
![image](https://github.com/easylist/easylist/assets/71368227/899264fa-b318-499c-ac7b-1eb87692f0ab)

#### Filter lists you're using:

The filter list responsible for the problem is EasyList:
![image](https://github.com/easylist/easylist/assets/71368227/63185c46-a35f-4196-9cf1-17c313318f1a)

#### Your settings:

- OS/version: Windows 10
- Browser/version: Firefox 125
- Ad block extension/version: uBlock Origin 1.57.2

**Comment by danielhjacobs** [comment]
This blocking rule was added in https://github.com/easylist/easylist/commit/a6e4fc049ee09fb878bba91143602bec2b515573 as part of a commit called "M: Cleanup". Not sure what the reasoning was behind it.

**Comment by danielhjacobs** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
Tried to replace `/pagepeel/*` e.g. on `http://metal-integral.com/` but yeah `/AC_OETags.js` is not an adscript.
