### ISSUE TITLE
myonlineradio.hu ads

### ISSUE THREAD

**Issue by karolyi** [easylist/easylist#19164]
Hey,

there is this site. If you start any radio, after it started playing, it replaces the radio logo to an ad loaded in an iframe. Adding this rule to my ublock origin filters it:

! May 13, 2024 https://myonlineradio.hu
||cfusionsys.com/$subdocument

Feel free to convert this to any rule that is consumable by other adblockers.

**Comment by Khrin** [comment]
please enable https://github.com/hufilter/hufilter throught your adblocker, to block ads on hungarian sites

**Comment by karolyi** [comment]
What makes you think I haven't? One of the first task to do when I install ublock origin at a new browser is to enable hufilter. Yet, these ads still come through without my custom rule.

**Comment by karolyi** [comment]
Please reopen this issue, it's not fixed.

**Comment by Khrin** [comment]
if you're using hufilter, then report this issue to him

**Comment by karolyi** [comment]
Thanks, will do.
