### ISSUE TITLE
Fanboys Social doesn't actually work on uBO

### ISSUE THREAD

**Issue by Squall-Leonhart** [easylist/easylist#19162]
Despite having uBO includes configured, the list isn't properly parsed resulting in 0 out of 0 filters used notice.

this goes back a couple of years https://github.com/uBlockOrigin/uBlock-issues/issues/2191

This is due to an erroneous space in the preparser

`! #include fanboy_social_specific_uBO.txt` should be `!#include fanboy_social_specific_uBO.txt` at line 12954 of fanboy-social.txt

**Comment by Yuki2718** [comment]
What? `!#include fanboy_social_specific_uBO.txt` is at L1123 of ` fanboy_social_specific_hide.txt` and `fanboy_social_specific_uBO.txt is correctly included in EasyList – Social Widgets.

**Comment by Khrin** [comment]
not reproducible

**Comment by Squall-Leonhart** [comment]
> What? `!#include fanboy_social_specific_uBO.txt` is at L1123 of ` fanboy_social_specific_hide.txt` and `fanboy_social_specific_uBO.txt is correctly included in EasyList – Social Widgets.

It is correct in this file, it is incorrect in fanboy-socials.txt because the python copies the line wrong.

Khrin, try harder.
