### ISSUE TITLE
Deezer Podcast

### ISSUE THREAD

**Issue by fabi-hub** [easylist/easylist#19183]
#### List the website(s) you're having issues with:

(https://www.deezer.com/de/show/359962) 

#### What happens?

I can't play a podcast. 

#### Filter lists you're using:

Standard Brave lists and EasyList Germany

#### Your settings:

With shield down I can play the podcast
With shield aggressiv and normal not

- OS/version: Windows 11
- Browser/version: Brave

**Comment by ryanbr** [comment]
Fix will be out in the next 2-3hrs @fabi-hub
