### ISSUE TITLE
telekomunikace.cz

### ISSUE THREAD

**Issue by x-rated** [easylist/easylist#19207]
#### List the website(s) you're having issues with:

https://telekomunikace.cz/

#### What happens?

top adds are not blocked

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/16560025/5de73988-d1d4-43a5-a4f3-4b99458625ef)

#### Filter lists you're using:

![332533844-b26fb79e-d83d-4730-ab8f-164ae4cd7436](https://github.com/easylist/easylist/assets/16560025/40ffe707-dc7b-4e59-a008-69077f16422a)

#### Your settings:

- OS/version: Windows 26120.670
- Browser/version: Chrome 126.0.6478.8
- Ad block extension/version: uBlock Origin Lite 2024.5.17.961

**Comment by Khrin** [comment]
Please report it to https://github.com/tomasko126/easylistczechandslovak
