### ISSUE TITLE
buyertrade.taobao.com can't search

### ISSUE THREAD

**Issue by 4ft35t** [easylist/easylist#19238]
[easyprivacy]

Rule :
||tbskip.taobao.com^$script

blocked:
https://tbskip.taobao.com/json/show_buddy_biz_order.do?bizOrderId=

Order search and next page not work.

Add `@@||tbskip.taobao.com^$script`, everything works fine.

**Comment by 4ft35t** [comment]
As known as #7277

**Comment by ryanbr** [comment]
Closing, no steps to reproduce and its not a recent rule.

**Comment by 4ft35t** [comment]
### steps to reproduce 
1. login to www.taobao.com
2.  open https://trade.taobao.com/trade/itemlist/list_bought_items.htm
3. do like the image, order search stuck
![image](https://github.com/easylist/easylist/assets/2051049/f8a0c18d-c44d-4f95-b59f-8f2c8e5b7649)
4. add `@@||tbskip.taobao.com^$script`, order search works fine.


### its not a recent rule
Because www.taobao.com can keep login now. Before this change, you need use mobile app to scan QR code to login, why just use mobile app?  With this change, more and more people use  website.
