### ISSUE TITLE
SI.com - Blocked videos again (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#19263]
### Affected site:
`https://www.si.com/`

### Issue:
Blocked videos.

### Example:
`https://www.si.com/more-sports/video/2012/02/02/izabel-goulart-outtakes/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **EasyList**

### Problem rules:
```
###mplayer-embed
||minutemediaservices.com^$third-party
```
### Possible fix:
```
si.com#@##mplayer-embed
@@||vms-*.minutemediaservices.com^$domain=si.com
```
### Note:
In LibreWolf (Firefox), some videos throws an error (displayed in an overlay).
It can be removed with `si.com##[id^="mplayer-error-page-"]` (the player's control bar will still be missing though, so use the right-click menu instead).

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v126.0.1-1 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.58.0

**Comment by THEtomaso** [comment]
@Yuki2718:
For '**uBlock filters - Unbreak**', perhaps?

**Comment by Yuki2718** [comment]
I don't see cookie notice or `.didomi-popup__dialog` with European IP.

**Comment by THEtomaso** [comment]
Ah, sorry, it's whitelisted in '**Bypass Paywalls Clean filter**' :)
