### ISSUE TITLE
The `/web-vitals/*` filter breaks API requests on GitHub in select repositories

### ISSUE THREAD

**Issue by iamakulov** [easylist/easylist#19271]
#### List the website(s) you're having issues with:

https://github.com/GoogleChrome/web-vitals

#### What happens?

- Enable the “Easy Privacy” filter
- Navigate to the URL above
- Observe none of commit/branch information loading because the filter blocks API requests to `https://github.com/GoogleChrome/web-vitals/branch-count` and similar

#### Screenshot(s) 

<img width="2416" alt="image" src="https://github.com/easylist/easylist/assets/2953267/e8748822-b71e-4c66-842c-e60153f7dcd3">

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: macOS 14.5 (23F79)
- Browser/version: Arc Version 1.44.3 (50502)
- Ad block extension/version: uBlock Origin 1.58.0

#### Other details:

Somewhat related: #17905

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/commit/af1d67a588362b15dd9d5023500eed411b76c553
https://github.com/easylist/easylist/commit/327ab1131d496fb10e1d973dd500ab44200ed28a
I no longer see any of `/web-vitals/*` request.
