### ISSUE TITLE
busuanzi.ibruce.info:break

### ISSUE THREAD

**Issue by SharwOrange** [easylist/easylist#19273]
#### List the website(s) you're having issues with:   

`http://busuanzi.ibruce.info/`

#### What happens?

This website provides a JavaScript for counting blog visits, but when I use uBlock Origin with EasyList, it intercepts the JavaScript

#### Screenshot(s) 
![图片](https://github.com/easylist/easylist/assets/65716524/93e76f2d-bef3-4a06-afd2-359f45e590c1)
![图片](https://github.com/easylist/easylist/assets/65716524/51cecc96-a5e8-4649-85d6-f504b9beb244)
![图片](https://github.com/easylist/easylist/assets/65716524/84a8ce8f-b617-4a35-80e2-be9f0b890dda)

#### Filter lists you're using:
uBlock Origin Default filter list+EasyList

#### Your settings:
uBlock Origin , Firefox

- OS/version:  Arch Linux 6.9.2-arch1-1
- Browser/version:  Firefox standard 126.0.1
- Ad block extension/version: uBlock Origin 1.58.0

#### Other details:

||busuanzi.ibruce.info^$3p blocks
![图片](https://github.com/easylist/easylist/assets/65716524/84a8ce8f-b617-4a35-80e2-be9f0b890dda)
(Screenshot of using JavaScript to calculate blog traffic in my blog)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/issues/17213

**Comment by SharwOrange** [comment]
But it is just a statistical service used to count the number of visitors. From the source code, it does not collect user privacy data. Also, it is not an advertisement, and in principle, easylist should not break it.

**Comment by Khrin** [comment]
It's in EasyPrivacy: https://easylist.to/pages/policy.html
