### ISSUE TITLE
cmoa.pro

### ISSUE THREAD

**Issue by macosupdate** [easylist/easylist#19278]
#### What happens?

cmoa.pro is a Japanese manga site that I often read, but these days it's been blocked by easylist. I don't know what is the cause, please fix this error

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/65846907/feb19a36-7486-4232-bb7e-3422069b4971)

#### Your settings:

- OS/version: windows 11
- Browser/version: firefox 126.0.1
- Ad block extension/version: ublock 1.58.0

**Comment by Yuki2718** [comment]
Fixed, `js.cmoa.pro` is an AdSpyglass adserver used also in `manga1001.win` (have to disable `||corsproxy.io^$domain=manga1001.win` to see the request) but I missed checking legitimate sites.
