### ISSUE TITLE
link.springer.com/journal/222 partly unusable with cookies bloked

### ISSUE THREAD

**Issue by ColourGrey** [easylist/easylist#19288]
#### List the website(s) you're having issues with:

<code>link.springer.com/journal/222</code>

#### What happens?

Scroll down a bit and try to click on the "View all volumes and issues ->" button; it will have no effect.
Under "Latest articles" try to click on the title of any article; it will have no effect.
Disable cookie blocking (i.e. EasyList Cookie) and you will be able to click on these links in order to follow them, at the price of having to deal with the GDPR cookies.
#### Filter lists you're using:

EasyList Cookie
Fanboy's Annoyances + uBO Annoyances
Fanboy's Mobile Notifications

#### Your settings:

- OS/version: Windows 10
- Browser/version: Brave 1.66.118
- Ad block extension/version: (Brave built-in blocker with the "EasyList Cookie" list selected)

#### Other details:

The same behaviour is exhibited by Firefox 126.0.1 with the "I don't care about cookies" extension v. 3.5.0. This makes me believe that it is indeed a GDPR cookie problem.

Other academic journals in the Springer portfolio might be affected by this.

**Comment by ColourGrey** [comment]
Also affecting the "I still don't care about cookies" extension: OhMyGuus/I-Still-Dont-Care-About-Cookies#13839.

**Comment by Khrin** [comment]
Unable to confirm the reported issue. links and pages are displayed correctly.
