### ISSUE TITLE
indeed.com: Sign in box

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#19285]
#### List the website(s) you're having issues with:

`https://gr.indeed.com/cmp/Kotsovolos/reviews`

#### What happens?

A sign in box appears and it blocks you from browsing the website.

#### Screenshot(s) 

<img width="1799" alt="image" src="https://github.com/easylist/easylist/assets/123986260/26d5f9e4-2a10-46f4-b74e-ddbca82015a8">

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: macOS Sonoma
- Browser/version: Safari
- Ad block extension/version: AdGuard

**Comment by ryanbr** [comment]
Unable to reproduce here
