### ISSUE TITLE
bbvms.com, bluebillywig.com

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#19280]
```
bbvms.com

bluebillywig.com
```

these two sites seems to be related, both seem to be about ads regarding dental care, and also have some kind of analytics system

first site has link to the second in its footer

both found on `https://www.rockpapershotgun.com/`

currently, `stats.bluebillywig.com` is blocked

**Comment by Khrin** [comment]
There aren't unblocked ads and this domain shouldn't be blocked.
