### ISSUE TITLE
Chrome (using Adblock Plus) not allowing EasyList to be updated - synchronize_too_many_filters

### ISSUE THREAD

**Issue by Danpamio** [easylist/easylist#19308]
While trying to update the list using Adblock Plus, a problem is returned:

There are one or more issues with this filter list: synchronize_too_many_filters

Screenshots:
![image](https://github.com/easylist/easylist/assets/34628554/ce5da8a7-fe2f-4c97-bb4e-33ba72753e94)
![image](https://github.com/easylist/easylist/assets/34628554/354017a4-81c2-4205-be6e-489fcbff7522)

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by monzta** [comment]
- Which lists are you using in ABP?
- Do you use any custom filters?
- What other extensions are you using?

**Comment by Danpamio** [comment]
Hi,

I have uninstalled and reinstalled AdBlockPlus extension and it fixed the synchronize_too_many_filters issue with EasyList.

But answering your questions:
 - I tried adding from both ways, either the URL and from Add Built-in filter list
 - I have no other extensions in Chrome, not even disabled.

But the issue #19309 still happens (https://github.com/easylist/easylist/issues/19309)
