### ISSUE TITLE
EasyList Cookie hides a "Do Not Sell" button for OneTrust CMP, e.g. https://www.dictionary.com/

### ISSUE THREAD

**Issue by muodov** [easylist/easylist#19305]
#### List the website(s) you're having issues with:

When visiting from a **US IP**: `https://www.dictionary.com/`, `https://www.thesaurus.com/`, but it's probably widespread because OneTrust is a popular CMP.

#### What happens?

When applying EasyList Cookie list, in some cases the opt-out button would be hidden, taking away user's possibility to reject tracking. This is mostly relevant for California and similar jurisdictions, where legislation allows tracking by default (e.g. CCPA).

#### Screenshot(s) 

Without Easylist Cookie:
<img width="694" alt="image" src="https://github.com/easylist/easylist/assets/2726132/e5d27826-bd4b-4a62-8e51-99c8e8f12163">

With Easylist Cookie:
<img width="872" alt="image" src="https://github.com/easylist/easylist/assets/2726132/e52acce5-70f2-485b-b7d6-632a3bb8fc70">

#### Filter lists you're using:

EasyList Cookie (Fanboy cookiemonster)

#### Your settings:

- OS/version: macOS
- Browser/version: Firefox
- Ad block extension/version: Adblock Plus with no other lists and acceptable ads disabled

#### Other details:

[This is](https://github.com/easylist/easylist/blob/bdd6a6f8bbaa6c967edbc8e7432b850d0f783318/easylist_cookie/easylist_cookie_general_hide.txt#L14879) the cosmetic rule in question. I believe it can hide actual pop-ups on other sites, but not in this case.

**Comment by Khrin** [comment]
It can remain there.

**Comment by muodov** [comment]
@Khrin I wonder if you can provide the reasoning here? For the CCPA and similar regions, hiding the button reduces the privacy of the user because they cannot opt-out of tracking anymore.

**Comment by tagawa** [comment]
I’m getting the same issue on dictionary.com and thesaurus.com (I’m not affiliated with either of them, nor OneTrust).

It seems to be a false positive in EasyList Cookie List.

**Expected behaviour:**
The "Cookies, terms, & privacy” and “Do not sell my info” links in the footer should be visible.

**Actual behaviour:**
The "Cookies, terms, & privacy” link is visible but the “Do not sell my info” link is hidden.
