### ISSUE TITLE
Chrome (using Adblock Plus) not allowing Easylist Cookie List to be imported - synchronize_dnr_error

### ISSUE THREAD

**Issue by Danpamio** [easylist/easylist#19309]
Chrome extension, Adblock Plus, is not able to download Easylist Cookie List.

There are one or more issues with this filter list: synchronize_dnr_error

Screenshot:
![image](https://github.com/easylist/easylist/assets/34628554/1303e610-0707-455f-9445-eead7c355eb0)

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by krystian3w** [comment]
If the add-in does not generate information about the line with which the problem occurs, you can try to split the component files into separate sublists by adding a header and title: https://github.com/easylist/easylist/tree/master/easylist_cookie (directory).

**Comment by Khrin** [comment]
Resolved in ABP 4.5 @Danpamio If you haven't already done so, please update the extension to the latest version.
