### ISSUE TITLE
Malicious/phishing links

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#19315]
#### List the website(s) you're having issues with:

```
sweet-bonanza-demo.gr

hfr67jhqrw8.com

tbao684tryo.com

5wzgtq8dpk.com

65spy7rgcu.com
```

#### What happens?

There is an ongoing scam in Greece, mostly on Facebook, involving video deepfakes of popular journalists advertising a fraudulent app, similar to the Tesla scams. While I couldn't find all the websites involved, I did discover this link that contains numerous instances of malware and phishing buttons. I have listed a few URL examples above, but there are many more malicious and phishing domains accessible through this link: sweet-bonanza-demo.gr. I recommend blocking this URL to prevent users from accessing it and catching malware or becoming victims to phishing or worse.

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version:
- Browser/version: 
- Ad block extension/version:

**Comment by JobcenterTycoon** [comment]
Related issue: https://github.com/uBlockOrigin/uAssets/issues/24043

**Comment by Yuki2718** [comment]
I missed
> accessible through this link: sweet-bonanza-demo.gr

at the first glance. Added those already in badware as confirmed. Will later remove from badware after 6 days past.
