### ISSUE TITLE
Grey overlay from cookie notice remains on remixshop.com

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylist#19322]
#### List the website(s) you're having issues with:

`https://remixshop.com/de`
#### What happens?

grey overlay appears over page
#### Screenshot(s) 

![Screenshot 2024-06-11 at 2 54 49 PM](https://github.com/easylist/easylist/assets/56893063/f4d96491-c343-4642-940f-4ed5bb04ed15)

#### Filter lists you're using:

ABP filters, EasyList, Easylist Cookies

#### Your settings:

- OS/version: macOS Ventura 13.5.2
- Browser/version: Firefox 127.0
- Ad block extension/version: Adblock Plus 4.1

**Comment by THEtomaso** [comment]
`remixshop.com###cboxOverlay`
