### ISSUE TITLE
techmaniacs.gr breakage of social media links

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#19327]
#### List the website(s) you're having issues with:
https://techmaniacs.gr/category/science/

#### What happens?
Breakage of social media links at the bottom of the page caused by Easy List – Social  Widgets list

#### Screenshot(s) 
Actual:
![Screenshot 2024-06-12 at 12-03-51 Science Archives - Techmaniacs](https://github.com/easylist/easylist/assets/101707608/0655d2ac-2244-4ab8-81e4-257fa9a21e03)
Breaked:
![Screenshot 2024-06-12 at 12-05-35 Science Archives - Techmaniacs](https://github.com/easylist/easylist/assets/101707608/7295e9e0-780b-47b6-b48d-48b6a91bcb6c)

#### Filter lists you're using:
All filters offered by uBO

#### Your settings:

- OS/version: Windows 7 Pro 32bit SP1
- Browser/version: Mozilla Firefox 115.11.0esr
- Ad block extension/version: uBlock Origin 1.58.0

**Comment by DimitrisKalaboukas** [comment]
@ryanbr ?

**Comment by Khrin** [comment]
The purpose of the list is to block (also) social media buttons.

**Comment by DimitrisKalaboukas** [comment]
@Khrin These are simply links to their social media profiles. Their header “ΑΚΟΛΟΥΘΗΣΤΕ ΜΑΣ” = “FOLLOW US” is left behind.
