### ISSUE TITLE
EasyPrivacy - Why Telemetry?

### ISSUE THREAD

**Issue by zackman0010** [easylist/easylist#19321]
I was just wanting to ask why telemetry data is considered to be a violation of privacy? To be specific: By telemetry, I mean data such as WebVitals, time to load, error reports, and other data of that sort. I do not mean telemetry as anything used to identify a user or track them across multiple websites. To me, this kind of telemetry data is for monitoring the website's performance rather than a specific user. 

The question came to me because we were evaluating Grafana Faro as a way to track our website's performance. During testing, we happened to notice that EasyPrivacy was blocking our data. On the one hand, I can see that Faro is a form of session tracking, watching which pages you visit. On the other hand, though, it's only watching you travel across a single website and only sending data related to that website's health. For me, this is an acceptable use of tracking, as your travel across a website is data they already have from IP logs.

I'm not trying to be a troll or asking this in bad faith, and I also don't expect Faro to be removed from EasyPrivacy because of this. I would just genuinely like to hear other opinions on this. I like using EasyPrivacy because it blocks all the Google Analytics and other much more invasive trackers. it's just my own personal opinion that website health monitoring tools like Faro aren't the same.

**Comment by Khrin** [comment]
@zackman0010 Read the policy: `https://easylist.to/pages/policy.html`
