### ISSUE TITLE
EasyList should not block first party assets

### ISSUE THREAD

**Issue by bluesmoon** [easylist/easylist#19320]
This issue was first detected when using Ghostery which uses EasyList: https://github.com/ghostery/ghostery-extension/issues/1652

#### List the website(s) you're having issues with:

URLs are all behind auth, so you cannot see it unless you pay for an account.
`https://mpulse.soasta.com/`

#### What happens?

Our application running on `mpulse.soasta.com` uses a JavaScript file called `mpulse.js` and a spacer gif called `spacer.gif`. It appears that both of these assets are blocked by EasyList.

The JavaScript file is the core functionality of the page, ie, it renders all the single page app content on the page. The page and the JavaScript are only served to users who have paid for an account.

Our request is that the assets be blocked only if the asset domain does not match the page domain.

#### Screenshot(s) 

<img width="1277" alt="image" src="https://github.com/ghostery/ghostery-extension/assets/35098/116e3bc5-0af9-4dab-8aea-feac29d8b7c5">

#### Filter lists you're using:

Easylist Privacy (via Ghostery)

#### Your settings:

- OS/version: Mac OS 14.4.1
- Browser/version: Chrome 125
- Ad block extension/version: Ghostery

The site works when Ghostery disabled, or if the specific URLs are explicitly allowed.

#### Other details:

The Ghostery team has done some investigation described at https://github.com/ghostery/ghostery-extension/issues/1652

**Comment by Khrin** [comment]
Thank you for your feedback.
