### ISSUE TITLE
Youtube.com - unskippable video (one or two in line sometime) before the real video you want.

### ISSUE THREAD

**Issue by DjDiabolik** [easylist/easylist#19326]
#### What happens?

Unskippable video (sometime also two or three video) it's played before the REAL video you want....

#### Screenshot(s) 

![immagine](https://github.com/easylist/easylist/assets/9040397/70814385-5b1a-4f7d-91dd-a13e3c67a7e8)

#### Filter lists you're using:

Easylist, EasyPrivacy, 'Peter Lowe’s Ad and tracking server list' and 'it: EasyList Italy'

#### Your settings:

- OS/version: Windows 10 22H2 build 19045.4474
- Browser/version: Firefox x64 version 127.0
- Ad block extension/version: uBlock Origin 1.58.0

#### Other details:

Never noticed anything like this until today.

**Comment by Yuki2718** [comment]
Now fixed by uBO side
