### ISSUE TITLE
Grey overlay from cookie notice remains on redring.co.uk

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylist#19323]
#### List the website(s) you're having issues with:
`https://redring.co.uk/`

#### What happens?
grey overlay appears over page

#### Screenshot(s) 

![Screenshot 2024-06-11 at 2 58 25 PM](https://github.com/easylist/easylist/assets/56893063/4d6c4e5b-c117-47f5-9d87-278e251ebf0e)

#### Filter lists you're using:

ABP filters, EasyList, Easylist Cookies
#### Your settings:

- OS/version: macOS Ventura 13.5.2
- Browser/version: Firefox 127.0
- Ad block extension/version: Adblock Plus 4.1

**Comment by THEtomaso** [comment]
`redring.co.uk##.cookie-pop-up-wrapper`
