### ISSUE TITLE
Document commit message prefixes?

### ISSUE THREAD

**Issue by muodov** [easylist/easylist#19336]
It took me some time to figure out what the commit prefixes mean (A, P, and M). My current understanding is:
- "A" = "Addition", a new rule added, increasing coverage
- "P" = "Problem", fixing breakage on one or more sites
- "M" = "Modification", any other change

FOP.py [requires a URL](https://github.com/easylist/easylist/blob/master/FOP.py#L408-L430) in A and P commits.

Is this a correct interpretation, and is it still being followed? If so, I think it's really useful for tracking down changes, and it's worth documenting somewhere.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/discussions/16755
