### ISSUE TITLE
Gritter Notifications Broken

### ISSUE THREAD

**Issue by kueblc** [easylist/easylist#19331]
#### List the website(s) you're having issues with:

N/A: internal web application

Any application using Gritter is impacted

#### What happens?

Notifications are not visible. They are a necessary part of the web app.

#### Screenshot(s) 

N/A

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version:
- Browser/version: Brave v1.66.115
- Ad block extension/version: Brave built in

#### Other details:

[Gritter](https://github.com/jboesch/Gritter) is an established jQuery plugin providing notification like functionality for web apps. It has been around for over a decade.

While debugging why an internally used tool was not providing user feedback in Brave, I discovered that EasyList Cookie is visually blocking all notifications from this plugin.

I am guessing that some website had used the plugin to deliver a cookie consent notification, and an overly broad rule was applied to rid it. The plugin itself is not intended to deliver ads or cookie consent notifications, but rather serve core functionality of web applications.

The blunt rule is found here:

https://github.com/easylist/easylist/blob/8bf71aa452216c983fec96786d7baa237f1b5d63/easylist_cookie/easylist_cookie_general_hide.txt#L5686

This rule should be removed. If possible to locate the original offending website, it could be replaced with a more specific filter.

Thank you EasyList maintainers and contributors.

**Comment by Khrin** [comment]
As you seem to have solved the "problem" yourself, there's no need to keep this issue open.

**Comment by kueblc** [comment]
While I may have provided a work around for our own internal application, the "problem" still exists for any number of web applications using Gritter. I do not own or maintain Gritter.

**Comment by kueblc** [comment]
soundcloud.com for example, is still impacted by this bug. See https://github.com/ryanbr/fanboy-adblock/issues/1533

**Comment by kueblc** [comment]
I just did a cursory search for gritter-notice-wrapper and noted many relatively recent development resources on using Gritter in web applications. Please reopen, this is definitely not completed.
