### ISSUE TITLE
Grey overlay from cookie notice remains on intersport.ro

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylist#19342]
#### List the website(s) you're having issues with:
`https://www.intersport.ro/`

#### What happens?
scrolling locked, grey overlay covers page content

#### Screenshot(s) 
![Screenshot 2024-06-13 at 9 41 55 AM](https://github.com/easylist/easylist/assets/56893063/367090b7-310b-4942-ba61-e22d26499ddd)

#### Filter lists you're using:

ABP filters, EasyList, Easylist Cookies

#### Your settings:

- OS/version: macOS Ventura 13.5.2
- Browser/version:  Firefox 127.0
- Ad block extension/version:  Adblock Plus 4.1

**Comment by K-mikaZ** [comment]
Try this:
```js
!#if cap_html_filtering
intersport.ro##^div.x-cookies-modal
!#else
intersport.ro#?#div.x-cookies-modal:remove()
!#endif
``` 
Tested at home and working.
