### ISSUE TITLE
Standard uk video won't load

### ISSUE THREAD

**Issue by M1Aston** [easylist/easylist#19346]
#### List the website(s) you're having issues with:
https://www.standard.co.uk/news/politics/general-election-penny-mordaunt-nigel-farage-itv-debate-labour-b1164354.html

#### What happens?
Video won't load when ublock is enabled. Disabling it makes it load normally.

#### Screenshot(s) 
Just a black window where the video should be.

#### Filter lists you're using:
Easylist, EasyPrivacy, both Cookie lists, Dutch filters, malicious URLs

#### Your settings:

- OS/version:  Windows 11
- Browser/version: Latest Firefox
- Ad block extension/version: ublock 1.58.0

**Comment by THEtomaso** [comment]
### Problem filter:
* **EasyList**

### Problem rule:
`/prebid8.$script`

### Possible fix :
`@@||standard.co.uk/js/third-party/prebid*.$script`

### Note:
'**AdGuard Base filter**' already includes a fix.
