### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by blue-lightning** [easylist/easylist#1934]
### List the website(s) you're having issues:

`https://kotaku.com/japanese-crime-recreated-with-cg-hilarity-ensues-1829384584`

### What happens?

Twitter embedded media gets cut off.

### List Subscriptions you're using:

Easy List

### Your settings

- OS/version: Windows 10 x64 version 1803
- Browser/version: Firefox 62.0.2 x64
- Adblock Extension/version: uBlockOrigin 1.17.0

### Other details:

Seems like there's a fix [here.](https://www.reddit.com/r/uBlockOrigin/comments/8el66d/cosmetic_filter_shrinks_embedded_tweets_in_io9/)

**Comment by blue-lightning** [comment]
My uBlockOrigin didn't update that filter when I click "Update now", I have to force it and then the problem went away. Thanks @krystian3w !

**Comment by blue-lightning** [comment]
Turns out the filter only works after the resources have been loaded before. Clearing the browser cache makes embedded media cut off again.

**Comment by ryanbr** [comment]
No issues here. closing.
