### ISSUE TITLE
geotastic.net: Adblock notice

### ISSUE THREAD

**Issue by PhoenixFossGR** [easylist/easylist#19345]
#### List the website(s) you're having issues with:

`https://geotastic.net/`

#### What happens?

There is a notice on the Geotastic website requesting users to disable their adblocker. I attached two screenshots below.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/123986260/f322e81d-af3e-401e-a1f2-0d960291f623)
![image](https://github.com/easylist/easylist/assets/123986260/7fbb6535-510f-4b8a-9df9-9383f2aba6f7)

#### Filter lists you're using:

EasyList, among others

#### Your settings:

- OS/version: macOS Sonoma 14.5
- Browser/version: Safari
- Ad block extension/version: AdGuard

**Comment by Khrin** [comment]
Report it to Adguard.
