### ISSUE TITLE
aldi.nl cookie not blocked

### ISSUE THREAD

**Issue by M1Aston** [easylist/easylist#19361]
With two cookie lists active, this cookie message is not blocked:

![ccc](https://github.com/easylist/easylist/assets/43113612/7f18c017-2200-482e-9249-1dccf18cd62d)

**Comment by M1Aston** [comment]
Issue closed as completed, but I still get the same cookie message as the screenshot above.

**Comment by Khrin** [comment]
You may need to update your filter lists

**Comment by M1Aston** [comment]
I don't know. That cookie message is still not blocked here.

**Comment by Khrin** [comment]
@M1Aston With EasyList Cookies is correctly blocked. Maybe you're using Adguard Cookies, and not EasyList?

**Comment by Khrin** [comment]
The issue in EasyList Cookies has been fixed correctly. So please keep Adguard Cookies disabled and if the problem persists, please report it to Adguard.

This is definitely not an EasyList Cookies problem.
