### ISSUE TITLE
curseforge.com

### ISSUE THREAD

**Issue by RambIing** [easylist/easylist#19393]
#### List the website(s) you're having issues with:

`https://www.curseforge.com/`

#### What happens?

Banner at the top still visible.

#### Screenshot(s) 
![image](https://github.com/easylist/easylist/assets/16966523/079db9e2-574f-43fc-a35e-453281434466)

#### Filter lists you're using:

uBlock Origin

#### Your settings:

- OS/version: Windows 10
- Browser/version: Chrome 126.0.6478.62 (64bit)
- Ad block extension/version: 1.58.0

#### Other details:

pretty easy to block:
![image](https://github.com/easylist/easylist/assets/16966523/5b8712ca-d150-456c-beb6-2f706586b8bf)

**Comment by RambIing** [comment]
![image](https://github.com/easylist/easylist/assets/16966523/e84846cd-0bf6-4905-9c8d-3b8c5ee70eac)

also appears in carousel, unsure if able to block that as well

**Comment by Yuki2718** [comment]
Self-promotion
