### ISSUE TITLE
www.mirror.co.uk cookie message

### ISSUE THREAD

**Issue by M1Aston** [easylist/easylist#19399]
The cookie lists don't block the bar at he bottom of the page:

https://www.mirror.co.uk

**Comment by THEtomaso** [comment]
It's been whitelisted on purpose, in order to avoid video playback issues:
https://github.com/easylist/easylist/issues/19259/

**Comment by Yuki2718** [comment]
Can't be fixed in ELC as needing trusted scriptlet.
