### ISSUE TITLE
Dont Block PopUp in gofirstrow.eu

### ISSUE THREAD

**Issue by jpBenfica** [easylist/easylist#194]
Problem

`<a style="width: 100%; height: 100%; position: fixed; top: 0px; left: 0px; cursor: pointer; display: block !important; background-color: transparent;" onclick="mainWidget_globalTm.adsjudo_openNT_adsjudo('PGh0bWw+PGhlYWQ+PC9oZWFkPjxib2R5PjxzY3JpcHQ+ZG9jdW1lbnQubG9jYXRpb24uaHJlZj0naHR0cDovL3Jla292ZXJyLmFkazJ4LmNvbS9pbXA/cD03MDU1MzAwMSZjdD1odG1sJmFwPTEzMDMmaXNzPTAmZj0wJmFiPTUwMDMmcHNpZD1yZWtvdmVycic8L3NjcmlwdD48L2JvZHk+PC9odG1sPg==');mainWidget_globalTm.close_all();"></a>`

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/0913515a7bb8811aa096dcb921745e6bc8917e7b
