### ISSUE TITLE
coveteur.com article images hidden

### ISSUE THREAD

**Issue by n0samu** [easylist/easylist#19410]
#### List the website(s) you're having issues with:

`https://coveteur.com/faerybabyy-lucky-star`

#### What happens?

Images within the body of the article are hidden by this filter: `##.share-trigger`
The images are part of the article content and should not be blocked.
With an exception added for this filter, the images appear as expected.

#### Screenshot(s) 

**Expected** - images appear:
![image](https://github.com/easylist/easylist/assets/71368227/77633a56-82fc-495f-890f-9755a3955f9c)

**Actual** - images are hidden:
![image](https://github.com/easylist/easylist/assets/71368227/87f62a8a-55a5-401c-8734-2e2a6b75edb6)

#### Filter lists you're using:

The filter responsible for the problem `##.share-trigger` is part of Fanboy's Annoyance List and EasyList – Social Widgets.
![image](https://github.com/easylist/easylist/assets/71368227/e4525064-ff15-4221-a3f3-1214335b1cc2)

#### Your settings:

- OS/version: Windows 10
- Browser/version: Firefox 127
- Ad block extension/version: uBlock Origin 1.58.0

**Comment by Khrin** [comment]
the filter has already been removed
