### ISSUE TITLE
Rako HUB activity

### ISSUE THREAD

**Issue by bentech** [easylist/easylist#19444]
#### List the website(s) you're having issues with:

`http://192.168.10.10/securehome/activities`

#### What happens?

The Rako HUB is a hardware device on the users local network. It has an activity feature allowing Mappings, Events and Macros. The /api/v1/activity endpoint is used to provide a list of activities.

#### The Rule
`/api/v1/activity|$xhr`

#### Logger output
```
Filter
/api/v1/activity|$xhr
Filter list
[EasyPrivacy](chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=easyprivacy)
 
Context
192.168.10.10
Partyness
(1) 192.168.10.10 ⇒ 192.168.10.10
Type
xhr
URL
http://192.168.10.10/api/v1/activity
```

#### Screenshot(s) 

<img width="1063" alt="Screenshot 2024-07-01 at 10 37 30" src="https://github.com/easylist/easylist/assets/567690/1d9f0e99-7e49-4e78-90d8-b1fd09758878">

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: MacOS 14.3
- Browser/version: Chrome 126.0.6478.127
- Ad block extension/version: uBlock Origin 1.58.0

**Comment by Khrin** [comment]
Disable adblocking when using this site. Filter cannot be edited.
