### ISSUE TITLE
Cookie Notice – allocine.fr

### ISSUE THREAD

**Issue by HarmfulBreeze** [easylist/easylist#19447]
#### List the website(s) you're having issues with:

`https://www.allocine.fr/film/fichefilm_gen_cfilm=43574.html`

#### What happens?

The cookie notice shows up, even with the "EasyList/uBO – Cookie Notices" list enabled.

#### Screenshot(s) 

![image](https://github.com/easylist/easylist/assets/6281092/8a5fc1a6-275d-482a-bdf1-12c6286f9232)

#### Filter lists you're using:

![image](https://github.com/easylist/easylist/assets/6281092/10f86734-82ef-4cec-a3d6-fce33f050aca)

#### Your settings:

- OS/version: Windows 11
- Browser/version: Edge 126.0.2592.81
- Ad block extension/version: uBO 1.57.2

**Comment by ryanbr** [comment]
Should be resolved now
