### ISSUE TITLE
dropbox.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#19498]
```
||dropboxstatic.com/*/privacy_consent
```
```
||dropboxstatic.com/*/fingerprintjs_
||dropboxstatic.com/*/c_fingerprintjs_
```

`A: https://www.dropbox.com/login`

```
||dropbox.com/*/ux_analytics%
```
```
||dropbox.com/*/privacy_consent
```

`A: https://sign.dropbox.com/`

**Comment by Khrin** [comment]
@smed79 I think the privacy consents are already handled (haven't seen anything unblocked)

**Comment by smed79** [comment]
@Khrin Adblock Plus reports
https://reports.adblockplus.org/6fec99e2-c31f-4b7f-b598-89d6432ab437
https://reports.adblockplus.org/a479a5c5-20bc-457c-abc5-a616c796912c
