### ISSUE TITLE
Pornhub Network (PHN)

### ISSUE THREAD

**Issue by flyingzebras** [easylist/easylist#195]
! To fix the global layout bug, add this to EasyList:
@@||static.images-gaytube.com/js/dist/main.min.js$script,domain=gaytube.com

! To display the category images on the main page
@@||static.images-gaytube.com/js/categories.js$script,domain=gaytube.com

! Alll video pages are broken (example Hentai video: http://www.gaytube.com/media/1085712/gianni_pelo/), EasyList fix:
@@||static.images-gaytube.com/js/dist/videopage.min.js$script,domain=gaytube.com

! sextube.com before video play
embeds.sunporno.com###videoContainer_pop
! Sextube.com video pause
||embeds.sunporno.com/top/234/?o=straight$xmlhttprequest,domain=sextube.com

**Comment by flyingzebras** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/56

**Comment by flyingzebras** [comment]
@ryanbr Can you please add this?

**Comment by ryanbr** [comment]
"Broken for months". No it hasn't, we haven't actually gaytube.com. Tested a video, and it works.

**Comment by flyingzebras** [comment]
@monzta Can you please have a look?

**Comment by Khrin** [comment]
Annoying someone else for a non-existent issue will not help you. Apparently this problem has already been fixed, but likely you didn't even bothered to look.

**Comment by flyingzebras** [comment]
@Khrin Shut the fuck up! I waited looked if this issue was solved for weeks.

**Comment by flyingzebras** [comment]
@Khrin The issue has been **fixed** so your label doesn't make any sense.

**Comment by flyingzebras** [comment]
@Khrin Also, it didn't make sense to leave this open when it **was fixed**.
