### ISSUE TITLE
overture.doremus.org

### ISSUE THREAD

**Issue by LeoVerto** [easylist/easylist#1950]
### List the website(s) you're having issues:
``http://overture.doremus.org/``
### What happens?

All pages on the domain are broken as CSS and JS is not loaded, the site shows a message to disable ad blockers as a workaround.

### List Subscriptions you're using:

EasyList

### Other details:

The ``/overture.$script`` and ``/overture.$stylesheet`` filters match the last slash of the ``http://`` and the subdomain and block the loading of any scripts or stylesheets thus completely breaking the website

**Comment by bogachenko** [comment]
```
@@||overture.doremus.org^$script,domain=overture.doremus.org
@@||overture.doremus.org^$stylesheet,domain=overture.doremus.org
```
it's easier than it seems
