### ISSUE TITLE
knmoloko.ru - cookie message

### ISSUE THREAD

**Issue by trup** [easylist/easylist#19526]
`https://knmoloko.ru/produktsiya`

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/easylist/ruadlist/assets/3046716/ca884e02-4d9f-400a-86f7-8a6e7eed54b1)

</details>

please add `##div[data-storage-item^="t887cookiename_"]`

**Comment by dimisa-RUAdList** [comment]
@Khrin 
**EasyList Cookies** already contains a general rule `##div[data-storage-item^="t886cookiename_"]`. It might make sense to make a rule `##div[data-storage-item^="t887cookiename_"]` also general?
