### ISSUE TITLE
Schibsted - Cookie Notices - Site breakage

### ISSUE THREAD

**Issue by AdblockReporters** [easylist/easylist#19603]
#### List the website(s) you're having issues with:

Any Schibsted newspaper sites.
https://www.aftenposten.no/
https://www.bt.no/
https://www.vg.no/

#### What happens?

The cookie notices list blocks the API call Schibsted sites uses to look for consent settings the user does on their account settings page. (No popup is shown)

This causes issues where users opt out of personalised news, or "do not track" to not be respected. As the opt out call is failing, they default to consented state.

Whitelist these:
- `https://user-permissions.privacy.schibsted.com/privacy/v2/schacc/<site>/user/sdrn:spid.no:user:<UserID>/permissions`
- `https://user-permissions.privacy.schibsted.com/privacy/v2/anonymous/<site>/user/sdrn:schibsted:environment:<UserID>/permissions`

The `<site>` and <UserID>` are placeholders and would be replaced with unique value

Or; Tbh, the `privacy.schibsted.com^` rule could just be removed. Schibsted have moved to using sourcepoint, so no Schibsted brand seems to use it for their built in cookie popup anymore
Only some image assets seems to be loaded from there to show the logo

#### Screenshot(s) 

Blocked request:
<img width="1472" alt="Screenshot 2024-07-20 at 19 04 23" src="https://github.com/user-attachments/assets/8baff141-9f9a-4223-95d6-69a0ac343267">

What the API response contains (what the user have consented to)
<img width="621" alt="Screenshot 2024-07-20 at 19 06 14" src="https://github.com/user-attachments/assets/1570b4f8-aca6-460b-a7ee-8d2eba384213">

Their consent dashboard where you change the response (https://privacysettings.schibsted.no/?client_id=4ef1cfb0e962dd2e0d8d0000):
<img width="611" alt="Screenshot 2024-07-20 at 19 17 09" src="https://github.com/user-attachments/assets/cd54bafd-1770-4e5e-a5b8-efa2408d9f59">

#### Filter lists you're using:

EasyList - Cookie Notices

#### Your settings:

- OS/version: MacOS
- Browser/version: Firefox (Developer Beta)
- Ad block extension/version: Ublock Origin - Beta

**Comment by THEtomaso** [comment]
Post it here:
https://github.com/uBlockOrigin/uAssets/issues/22295/

**Comment by AdblockReporters** [comment]
Hei! Mhm, the issue with the cookie consent popup is another thing to solve yeah. Not gotten around to look at that 

But this issue is more around the fact at some point Schibsted used to serve cookie consents from https://privacy.schibsted.com/
However, now they use sourcepoint, so its on another domain (cmp.<ScibstedSite>.no/se)

There is now another issue where they allow users to opt out of personalisation, and other tracking on their Schibsted account.
The issue is the frontend then calls an API endpoint on privacy.schibsted.com, but since it is blocked they default to "allowed" consent :/ Kinda weird default, but thats what it seems like it does
