### ISSUE TITLE
ad  domains 

### ISSUE THREAD

**Issue by detyso** [easylist/easylist#19618]
this domains are just to host ads riskware  
thuckautiru.com
cqoncpshasebcfg.com
fyxgeddaet.com
isybxiclldsd.com
jpfxouow.com
jvypcwnokvyftjd.com
thubanoa.com
mellow-weird.com
eatcells.com
palecount.com
spotlesscomplaint.com
betteradsystem.com
tkdsotirrfb.com
yonhelioliskor.com
d2kk0o3fr7ed01.cloudfront.net
pelecount.com
taboola.com
xjlitqxmhmlyueq.com
sqoepjflq.com
djqvpqvgfe.com
qjaamgaup.com
raikijausa.net
courewaup.com
#### Your settings:

- OS/version: Windows 11
- Browser/version: Floorp
- Ad block extension/version: Ublock Origin

**Comment by Khrin** [comment]
Some are already blocked, others will be in due course.
