### ISSUE TITLE
bergans.com - Cookie banner

### ISSUE THREAD

**Issue by AdblockReporters** [easylist/easylist#19630]
#### List the website(s) you're having issues with:

EasyList cookie

#### What happens?

Fixed with:
`bergans.com###brgn-ckbar`

Or if one wants to be fancy and reject:
`bergans.com##+js(set-cookie, cc, 2)`

#### Screenshot(s) 

<img width="562" alt="Screenshot 2024-07-23 at 13 14 46" src="https://github.com/user-attachments/assets/0b60a185-f6e6-4842-8413-10083cb6366c">

<img width="772" alt="Screenshot 2024-07-23 at 13 15 12" src="https://github.com/user-attachments/assets/835f99d1-b658-4d00-8b0f-69da2052e2f1">

#### Filter lists you're using:

Ubo filters and all EasyList filters

#### Your settings:

- OS/version: macos
- Browser/version: firefox
- Ad block extension/version: ubo latest dev build

**Comment by Yuki2718** [comment]
On my end it's `2:f`

**Comment by THEtomaso** [comment]
It was `2:f `at my end too.
..but since `bergans.com##+js(set-cookie, cc, 2:f)` completely failed, I tried `bergans.com##+js(set-cookie, cc, f)` instead, which actually works just fine for me!
Weird that it doesn't work for you.
Which syntax do you use in the `##+js` rule, in order to actually set the correct 2:f value?

**Comment by Yuki2718** [comment]
Since `2:f` is not one of default values for `set-cookie`, you have to use `trusted-set-cookie`. @AdblockReporters Does `bergans.com##+js(trusted-set-cookie, cc, 2:f)` (with `Allow custom filters requiring trust` checked) work for you?

**Comment by THEtomaso** [comment]
Ahh, I see.
That does indeed work! :)

**Comment by AdblockReporters** [comment]
Yep, that also works!

**Comment by THEtomaso** [comment]
> https://github.com/uBlockOrigin/uAssets/commit/b71bf7572f98fd393a9b74223a7d213c8f07c73a

@Yuki2718:
You forgot to include `bergans.com###brgn-ckbar`

**Comment by Yuki2718** [comment]
Well, almost unnoticeble but will add for uBO (for AG it can be problematic for platforms not supporting scriptlet).

**Comment by THEtomaso** [comment]
> almost unnoticeble

That must be a regional thing.
Take a look at the screenshot in the first post..
That's what I get too!

**Comment by Yuki2718** [comment]
Oh, yeah, I now see. Don't know what happned previously.
