### ISSUE TITLE
unlocky.net

### ISSUE THREAD

**Issue by NeverBehave** [easylist/easylist#19643]
Redirected From: https://github.com/uBlockOrigin/uAssets/pull/24608

#### List the website(s) you're having issues with:

```
unlocky.org
unlocky.xyz
```

#### What happens?

This website claims to provide unlock codes for Android phone but it tricks people to finish various "offers" which involves providing personal information. The actual information needed for unlock was never sent. For example, you can bypass the animation of unlocky.xyz with the following code in console.

```js
xfContentLocker.completedLeads = ["a"] * 100
xfContentLocker.completedPoints = 100
xfContentLocker.checkComplete()
```

After this it will jump to `unlocky.org/get-code` and continue similar flow.

#### Screenshot(s) 

<img width="617" alt="image" src="https://github.com/user-attachments/assets/613b5079-bd6c-4a10-859b-673e179711be">

**Comment by JobcenterTycoon** [comment]
Fixed https://github.com/easylist/easylist/commit/92525fa74db16dc9f76267a55e9814187a8796de
