### ISSUE TITLE
site

### ISSUE THREAD

**Issue by NikiWebs** [easylist/easylist#19648]
#### What happens?

Site breaks, button doesn't work, and chrome web store icon dissapears.

#### Filter lists you're using:

Adblock and uBlock, first removes button and pictures, second one blocks everything
#### Your settings:

- OS/version: Windows
- Browser/version: Chrome
- Ad block extension/version: uBlock and AdBlock

**Comment by Khrin** [comment]
Come back when your mind is clearer, I have no idea what you were trying to do here.
