### ISSUE TITLE
weather.com

### ISSUE THREAD

**Issue by Erikk26** [easylist/easylist#19650]
#### List the website(s) you're having issues with: 
weather.com

#### What happens? 
Website keeps refreshing endlessly when "EasyList/uBO – Cookie Notices" filter(s) enabled, no matter if before i reject/accept all while uBO was temporarily disabled.

#### Filter lists you're using: 
defaults + EasyList/uBO – Cookie Notices

#### Your settings:

- OS/version: Windows 11 Pro 23H2 (Build: 22631.3880)
- Browser/version: Firefox 128.0.2
- Ad block extension/version: uBlock Origin 1.58.0

**Comment by Jaitsu** [comment]
This should be reopened, as the issue is still happening with the current list.

**Comment by Khrin** [comment]
> This should be reopened, as the issue is still happening with the current list.

Does this still happen to you after updating filters lists?

**Comment by Erikk26** [comment]
> This should be reopened, as the issue is still happening with the current list.

Same here after deleting site cookie settings. Even before that radar and rain-forecast couldn't open.

**Comment by Erikk26** [comment]
And now it works without filter updating... i don't understand. Last filter update was about 30 minutes ago.

**Comment by Jaitsu** [comment]
> > This should be reopened, as the issue is still happening with the current list.
> 
> Does this still happen to you after updating filters lists?

Yes, the list is up-to-date, I double-checked just now and it's still going on, and only when I have the EasyList - Cookie Notices list enabled. Sometimes it takes a few page loads/clicks for it to start happening, but the page fails to load, displays white and starts refreshing itself constantly.
