### ISSUE TITLE
downlon.com

### ISSUE THREAD

**Issue by NikiWebs** [easylist/easylist#19668]
#### What happens?

Site breaks, buttons doesn't work and it removes CWS logo which is mandatory.

#### Filter lists you're using:

Adblock and uBlock

#### Your settings:

- OS/version: Windows/Mac
- Browser/version: Chrome 126.0.6478.183 
- Ad block extension/version: AdBlock 6.6.0

**Comment by Khrin** [comment]
no need for further editing.
