### ISSUE TITLE
tmail.la

### ISSUE THREAD

**Issue by Am4hisa** [easylist/easylist#19691]
#### List the website(s) you're having issues with:
 
 https://tmail.la/

#### What happens?

Ads placeholder 

#### Screenshot(s) 
  
 https://img1.imageride.net/images/2024/07/29/image.png

#### Filter lists you're using:

Easylist

#### Your settings:

- OS/version: Windows 10
- Browser/version:  Chrome 125.0.6422.113
- Adblock extension/version: AdGuard Browser extension Ver4.3.53

**Comment by Khrin** [comment]
There is no need to add filters for this at the moment.
