### ISSUE TITLE
https://psmag.com/ blocked ads counter never stops

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#197]
https://psmag.com/
Left a tab open with this site, came back the next day and it was showing over 14,000 ads blocked in the ABP ad counter.

Cause:
`||collector-medium.lightstep.com^`
EasyPrivacy

![capture](https://cloud.githubusercontent.com/assets/12802056/20318546/a920e048-ab38-11e6-9170-e76001c60309.PNG)

**Comment by monzta** [comment]
Cannot reproduce. Is it still happening?

**Comment by terrorist96** [comment]
Looks fixed.
