### ISSUE TITLE
Darkibox

### ISSUE THREAD

**Issue by MrGoraj** [easylist/easylist#19719]
#### List the website(s) you're having issues with:

`https://darkibox.com/embed-b0f78xmxtl25.html`

#### What happens?

The page displays the message "Disable console!"

#### Filter lists you're using:

I use uBlock Origin, the problem occurs only when I have the filter active:  EasyList – Annoyances

#### Your settings:

- OS/version: Windows 11
- Browser/version: Chrome/Edge 127
- Ad block extension/version: uBlock Origin

**Comment by anka-213** [comment]
I believe adding this exception fixes the issue:

```
@@||darkibox.com/js/devtools-detector.js$script,1p
```

There is already a similar exception for the same script on another site: https://github.com/easylist/easylist/blob/2d0388a9e3b9ab1cbce749c0d1c2ca1727855e44/fanboy-addon/fanboy_annoyance_allowlist.txt#L3

**Comment by anka-213** [comment]
If you want to actually disable the devtools-detector instead of just not triggering it, you can add this uBO specific rule instead of the exception:

```
darkibox.com##^script:has-text(stoppp)
```

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/50962e25b184a60941fe289ec58685e3eb4da701
