### ISSUE TITLE
info.medtronicdiabetes.com

### ISSUE THREAD

**Issue by Dwedit** [easylist/easylist#19723]
I know a person who received a letter telling them to visit a website hosted on the domain "info.medtronicdiabetes.com" to confirm they received a part.  However, EasyPrivacy has that domain on the block list.  This person is not a techie, and would be unable to figure out how to proceed to the website despite the block.

Since this website is used as a website for people to visit rather than a third-party script hosting site, I would suggest removing that domain from the block list.

For now, I must turn off EasyPrivacy on their computer.

**Comment by Khrin** [comment]
Instead of criticising us (for which, by the way, this and other filters are imported from a third party list), think about the reasons why this site is on a privacy list.
