### ISSUE TITLE
https://www.menulog.com.au/restaurants-mcdonalds-bourke-st-west/reviews

### ISSUE THREAD

**Issue by Banaanae** [easylist/easylist#19738]
#### List the website(s) you're having issues with:

https://www.menulog.com.au/restaurants-mcdonalds-bourke-st-west/reviews

#### What happens?

Reviews don't load, no star count

#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/875452f4-b204-480f-a7f5-4887b9800df9)
^ uBo disabled
![image](https://github.com/user-attachments/assets/65cb73d5-ea28-4c3e-8389-e29b83656a5a)
^ uBo enabled

#### Filter lists you're using:

Issue is in EasyList – Cookie Notices
If you need full list let me know

#### Your settings:

- OS/version: Windows 11
- Browser/version: Firefox 128.0
- Ad block extension/version: uBlock Origin 1.59

**Comment by Khrin** [comment]
> #### Filter lists you're using:
> Issue is in EasyList – Cookie Notices If you need full list let me know

It would be more helpful to see a full list of active filters on this site.

(https://github.com/gorhill/uBlock/wiki/The-logger)

**Comment by Banaanae** [comment]
![image](https://github.com/user-attachments/assets/467c1f1b-5c1e-4a03-aefc-97745f6c8cb7)

**Comment by Khrin** [comment]
@Banaanae Hopefully this should solve your problem after updating your filter lists.
