### ISSUE TITLE
https://www.vbb.de/fahrinfo

### ISSUE THREAD

**Issue by zedd-0** [easylist/easylist#19744]
#### List the website(s) you're having issues with:
https://www.vbb.de/fahrinfo

#### What happens?
side loading error

#### Filter lists you're using:
[EasyList – Cookie Notices]
Filter: ||cookiebot.com^$3p

#### Your settings:

- OS/version: Win11
- Browser/version:  Firefox (last)
- Ad block extension/version: ublock origin (last)

#### Other details:
Filterlist: "EasyList – Cookie Notices" cause the problem
filter is set too wide or website needs an exception.

**Comment by Khrin** [comment]
site works fine with easylist cookies. problem must be elsewhere
