### ISSUE TITLE
Frandroid.com & Numerama.com - Can't scroll on iOS w/ cookie banner hide

### ISSUE THREAD

**Issue by neokura** [easylist/easylist#19751]
**List the website(s) you're having issues with:**
frandroid.com
numerama.com

**What happens?**
The scroll is blocked on the website with the cookie banner blocked on smartphone.

**Filter lists you're using:**
EasyList Cookie List, EasyPrivacy, Fanboy's Annoyance

**Your settings:**
OS/version: iOS 17.6
Browser/version: Ark Search
Ad block extension/version: native on ark search with EasyPrivacy & Fanboy's Annoyance
Other details: Also have this issue on Safari with adblock pro extension on & hide cookies option.

**Comment by ryanbr** [comment]
I have Arc browser installed, is this the same thing? what extension are you using?
