### ISSUE TITLE
Aliexpress not loading due to e11956.x.akamaiedge.net

### ISSUE THREAD

**Issue by nazar-pc** [easylist/easylist#19755]
#### List the website(s) you're having issues with:

`aliexpress.com`

#### What happens?

Page is not loading fully due to `e11956.x.akamaiedge.net` being blocked by easylist

#### Filter lists you're using:

uBlock Origin with EasyList enabled

#### Your settings:

- OS/version: Ubuntu 24.04
- Browser/version: Firefox Nightly
- Ad block extension/version: uBlock Origin 1.59.0

**Comment by Khrin** [comment]
Fixed in https://github.com/easylist/easylist/commit/bd9565ae5a90162d40dcaebaa3e3a947ff1a9b16
