### ISSUE TITLE
Cookies: builderius.io

### ISSUE THREAD

**Issue by 3xploiton3** [easylist/easylist#19760]
![image](https://github.com/user-attachments/assets/f128897c-f21c-4c86-8b86-7a3433e3ffbe)

**Comment by Khrin** [comment]
Looks like it's already blocked.

**Comment by 3xploiton3** [comment]
did you mean blocked by[ Adguard - cookies filter](https://github.com/AdguardTeam/AdguardFilters#adguard-filters) ?

because its still show up when i did not select adguard filter
