### ISSUE TITLE
streamruby.com breaks because of EasyList Other Annoyances

### ISSUE THREAD

**Issue by MEtICaRT** [easylist/easylist#19761]
#### List the website(s) you're having issues with:

https://streamruby.com/dyue1dlzbxvq

#### What happens?

When EasyList Other Annoyances is enabled, a 'Disable console!' message pops up, and then I'm redirected to google.com. If I try to click the back button, the message keeps spamming indefinitely until I close the tab. This issue started occurring with both uBO and AdGuard a few days ago.

#### Screenshot(s) 

<img width="517" alt="image" src="https://github.com/user-attachments/assets/bbf74464-9b5e-4158-b8e2-256fb53c1bca">

#### Filter lists you're using:

EasyList - Other Annoyances

#### Your settings:

- OS/version: All
- Browser/version: All
- Ad block extension/version: All

**Comment by Khrin** [comment]
Fixed in https://github.com/easylist/easylist/commit/50962e25b184a60941fe289ec58685e3eb4da701
