### ISSUE TITLE
euronews.com: ads

### ISSUE THREAD

**Issue by punisher018** [easylist/easylist#19778]
#### List the website(s) you're having issues with:

 https://www.euronews.com/my-europe/2024/08/10/russia-reinforces-kursk-region-with-troops-and-tanks

#### What happens?

For every news story on the site, there is a large gap at the top of the story from blocked ads.

#### Filter lists you're using:

 uBlock Origin 1.59

#### Your settings:

- OS/version: Win 10
- Browser/version: Chrome
- Ad block extension/version: uBlock Origin 1.59

#### Other details:
Adguard takes care of the problem with this filter in its extension.

euronews.com#$?##o-site-hr__leaderboard-wallpaper.u-show-for-xlarge { remove: true; }

**Comment by ryanbr** [comment]
Take it up with uBO
