### ISSUE TITLE
adnkronos.com 

### ISSUE THREAD

**Issue by Tony2k** [easylist/easylist#19770]
Could you add this site please?

**Comment by Khrin** [comment]
Add it where? And for what reason?

**Comment by Tony2k** [comment]
I'm talking about adding the site to Easylist.

**Comment by Khrin** [comment]
You mean `www.adnkronos.com`? Is that right? It is the website of a news agency and publisher, why should it be blocked in EasyList?

**Comment by Tony2k** [comment]
Yes you are right. It need to be added in EasyList cookies because there is a banner for every page.

**Comment by Khrin** [comment]
It is not possible to block it again at the moment, sorry.
