### ISSUE TITLE
Social list breaks thekitchn.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#198]
http://www.thekitchn.com/how-to-make-hummus-from-scratch-cooking-lessons-from-the-kitchn-107560

Social list causes text and first image to overlap (probably due to pinterest). Especially noticeable if your window is narrow (not maximized)

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/4a439d0647a044bf19d57108df9463d7ace5bf52
