### ISSUE TITLE
generic "sign in with google" popup blocker

### ISSUE THREAD

**Issue by bughit** [easylist/easylist#19808]
#### List the website(s) you're having issues with:

https://www.reddit.com/

This is just an example, there are many sites that support google sign in and are infested with this popup.
#### What happens?

This obnoxious dialog pops up on its own on page load and covers page content.
#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/ad07ed5e-b117-4187-9357-6921e27c0b03)

#### Filter lists you're using:

None of the "EasyList – Annoyances" filters in ublock origin, block this.

![image](https://github.com/user-attachments/assets/0a031ca6-4d10-4d5c-8d8a-0111d9446d44)

#### Your settings:

- OS/version: win10
- Browser/version: firefox 129.0.1
- Ad block extension/version: uBlock Origin 1.59.0

**Comment by ryanbr** [comment]
It is block via the annoyances list,

**Comment by bughit** [comment]
@ryanbr it's currently not blocked, please reopen

- win10, Firefox 130.0.0, uBlock Origin 1.59.0
- start Firefox with a new profile
- install uBlock Origin 1.59.0
- enable easylist annoyances
  ![image](https://github.com/user-attachments/assets/0696a63f-cae9-4f82-b6c8-15d9d8d9eec8)
- load https://www.reddit.com/
  ![image](https://github.com/user-attachments/assets/9cf0e7c1-08ae-4472-8fbc-99771234f849)

**Comment by bughit** [comment]
@ryanbr I posted precise repro directions. Is there anything wrong with them? If not, they demonstrate that this is not currently blocked, and if the intent is to block, please reopen.

**Comment by bughit** [comment]
@ryanbr reddit is now handled, thanks.

Saw it on https://x.com/
