### ISSUE TITLE
false positive validate.perfdrive.com

### ISSUE THREAD

**Issue by hyskylord** [easylist/easylist#19834]
#### List the website(s) you're having issues with:
```
https://iopscience.iop.org/article/10.1070/IM2013v077n03ABEH002645
```

#### What happens?
Easylist block me from downloading scientific articles from ```https://iopscience.iop.org/``` because the download is passed to a validation from
 ```validate.perfdrive.com/something```

#### Filter lists you're using:
EasyList

#### Your settings:

- OS/version: Windows 11 version 22631.4037
- Browser/version: Chrome version 127.0.6533.120
- Ad block extension/version: uBlock Origin 1.59.0

**Comment by ryanbr** [comment]
```
https://cdn.perfdrive.com/aperture/aperture.js
https://cdn.perfdrive.com/advanced/stormcaster.js
```
