### ISSUE TITLE
r-ulybka.ru - cookie message

### ISSUE THREAD

**Issue by trup** [easylist/easylist#19831]
the problem is not solved.

additional: the button stopped working
`https://www.r-ulybka.ru/catalog/goods/bumazhnye-salfetki-floom-odnosloinye-belye-24-24sm-100sht-3066443/`
![изображение](https://github.com/user-attachments/assets/03eba60e-c1cf-4504-b9f5-d51f44d41da7)

_Originally posted by @trup in https://github.com/easylist/easylist/issues/19561#issuecomment-2292279863_

**Comment by Khrin** [comment]
@trup  No need to open duplicates. Please continue to follow https://github.com/easylist/easylist/issues/19561
