### ISSUE TITLE
gemini.google.com

### ISSUE THREAD

**Issue by Rudxain** [easylist/easylist#19842]
#### List the website(s) you're having issues with:
`https://gemini.google.com/app`

#### What happens?
0. Install Firefox on Android
1. Login to some Google account
2. Visit Gemini
3. A full-screen overlay prompts the user to install the native app
4. Even after clicking "Not now" a banner on the top takes screen space

I added the following:
```abp
gemini.google.com##.get-app-banner
```
to "My Filters" on uBO. It does remove the banner. IDK how to get rid of the full-screen overlay.

BTW, the web app sends requests to `maps.googleapis.com` for seemingly no reason, even if the Maps plugin is disabled

#### Filter lists you're using:

All uBO lists (including non-default), except for the "Notifications" ones and "Other Annoyances"

#### Your settings:

- OS/version: Android 12
- Browser/version: Firefox 129.0
- Ad block extension/version: uBlock-Origin 1.59.0

**Comment by Yuki2718** [comment]
> BTW, the web app sends requests to `maps.googleapis.com` for seemingly no reason, even if the Maps plugin is disabled

IDK why and don't want to potentially break any functionality by blocking.
