### ISSUE TITLE
[Cookie Notice] Dailymotion

### ISSUE THREAD

**Issue by Meladoom** [easylist/easylist#19852]
#### List the website(s) you're having issues with:

Entire site.
https://www.dailymotion.com

Possible NSFW on some videos

#### What happens?

"We respect your privacy"

#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/a29075c2-559d-4ab2-9c01-c73928d6d28e)

#### Filter lists you're using:

![image](https://github.com/user-attachments/assets/09dbfcf5-184c-41a5-80bb-94a18a2a8ec4)

#### Your settings:

    OS/version: Windows 10
    Browser/version: Firefox 129.0.1
    Ad block extension/version: uBlock Origin 1.59.0

**Comment by Yuki2718** [comment]
I can't reproduce, where do you access from? This can't be fixed in ELC due to https://github.com/easylist/easylist/pull/13122 but uBlock filters – Cookie Notices is working for me.
cc: @peace2000

**Comment by peace2000** [comment]
@Yuki2718 I see that dialog as well. The current filter needs an update.

https://github.com/uBlockOrigin/uAssets/commit/f33407717a129384a8f6f06a9a15060f96cc05f3

That works fine to me.
