### ISSUE TITLE
fiberatlantic.com: Cookie notice

### ISSUE THREAD

**Issue by MEtICaRT** [easylist/easylist#19873]
#### List the website(s) you're having issues with:

`https://www.fiberatlantic.com`

#### What happens?

There is a cookie notice at the bottom of the website.

#### Screenshot(s) 

<img width="1976" alt="image" src="https://github.com/user-attachments/assets/f2507f8d-485c-4acc-97b7-8a917734b8a2">

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by Khrin** [comment]
It's already blocked by a generic rule: https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_general_hide.txt#L2682

Are you sure you have EasyList Cookies enabled?
