### ISSUE TITLE
www.gov.pl [breakage - by EasyPrivacy]

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylist#19874]
#### List the website(s) you're having issues with:

`https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2`

#### What happens?

Breakage, map doesn't load.

#### Screenshot(s) 

EasyPrivacy enabled:
![ss_20](https://github.com/user-attachments/assets/7154dd01-f8c7-4465-a6a8-ab1cfdb22d3a)

EasyPrivacy disabled:
![ss_21](https://github.com/user-attachments/assets/026211ee-d31d-4245-bc49-c230a2039762)

#### Your settings:

- OS/version: W
- Browser/version: Firefox/Chromium
- Ad block extension/version: uBO dev - default

**Comment by garry-ut99** [comment]
The map still doesn't load, until EasyPrivacy disabled.

(and not due to EasyPrivacy not updated yet, as the map doesn't load even with manually added this filter:  
`@@||googletagmanager.com/gtm.js$domain=www.gov.pl`)

**Comment by Khrin** [comment]
The map is slow to load, but it works. Try to see it with EasyPrivacy correctly updated.
