### ISSUE TITLE
Cookie notice - tf1info.fr

### ISSUE THREAD

**Issue by MoustaphaElPsyCongroo** [easylist/easylist#19876]
#### Website I'm having issues with:

`https://tf1info.fr/`

#### What happens?

Full page cookie notice appears.

#### Screenshot(s)

![screenshot (2)](https://github.com/user-attachments/assets/27e6d592-a1ff-4b73-86cc-8ff39bb1335e)

#### Filter lists you're using:

EasyList - Cookie Notices
uBlock filters - Cookie Notices

#### Your settings:

- OS/version: Windows 11
- Browser/version: Chrome 127.0.6533.120
- Ad block extension/version: uBlock Origin 1.59.0

**Comment by stephenhawk8054** [comment]
Addressed here: https://github.com/uBlockOrigin/uAssets/commit/faa4bb0b5021e1e93f18f7099412160a5a6157c7
