### ISSUE TITLE
GeeksForGeeks still shows cookie-notice

### ISSUE THREAD

**Issue by Rudxain** [easylist/easylist#19895]
#### List the website(s) you're having issues with:

```
https://www.geeksforgeeks.org/problems/frequency-of-array-elements-1587115620/0
```

#### What happens?

uBlockOrigin/uAssets#25046

#### Filter lists you're using:

All shown in uBO "Filter Lists" tab

#### Your settings:

- OS/version: Android 12
- Browser/version: Firefox 129
- Ad block extension/version: uBO 1.59

**Comment by Rudxain** [comment]
https://github.com/easylist/easylist/commit/848b86bb54c7108356cada8fdbe1800a20ac5963#commitcomment-145843275

**Comment by krystian3w** [comment]
Added to wrong line/typo, due consent is from small letter in HTML at that page.

Also possible start testing:

`##div[class*="CookieConsent" i]` on these domains

**Comment by Rudxain** [comment]
> `##div[class*="CookieConsent" i]`

Tested on Android, it works
