### ISSUE TITLE
html-load.com: incorrect blocking

### ISSUE THREAD

**Issue by trevor1112** [easylist/easylist#19896]
#### List the website(s) you're having issues with:
`https://www.chinatimes.com`

#### What happens?
Blocking html-load.com will cause some websites to not load properly.

#### Screenshot(s)
![Screenshot_20240828-060034.png](https://github.com/user-attachments/assets/29872478-9f51-4e14-85b0-da245c25dc60)

#### Filter lists you're using:
EasyList on NextDNS

#### Your settings:
- OS/version: Android 14
- Browser/version: Chrome 128
- Ad block extension/version: NextDNS

#### Other details:

**Comment by Khrin** [comment]
It is better not to use EasyList for DNS blocking.
