### ISSUE TITLE
mollie.com: broken cookie banner

### ISSUE THREAD

**Issue by qwerty287** [easylist/easylist#19900]
#### List the website(s) you're having issues with:

```
https://www.mollie.com
```

#### What happens?

The darkener overlay is not removed.

#### Filter lists you're using:

This is caused by EasyList Cookie, disabling makes it working.

#### Your settings:

- Ad block extension: uBlock Origin

#### Other details:

Can be solved with:
```
www.mollie.com##body > div:nth-child(11)
```

**Comment by krystian3w** [comment]
That filter is bad, we can do better.

**Comment by krystian3w** [comment]
My proposition is:
```adb
mollie.com##body > div[style*="fixed"]:not([id]):not([class])
```
