### ISSUE TITLE
trycloudflare.com - all free Cloudflare tunnels are filtered

### ISSUE THREAD

**Issue by hourianto** [easylist/easylist#19913]
#### List the website(s) you're having issues with:

Any website using free Cloudflare reverse tunnels: all subdomains on trycloudflare.com

#### What happens?

The link gets filtered.

#### Filter lists you're using:

EasyList. Offending entry in the list:
```
||trycloudflare.com^
```

#### Other details:

Temporary Cloudflare tunnels are a reputable service run by Cloudflare, similar to e.g. ngrok and other services. They give you free temporary reverse proxy tunnels, good for development or quick testing. See https://try.cloudflare.com/ for more info. I do not think a blanket ban on trycloudflare is ever a good idea, since anyone can host anything in those tunnels, there's no reason to block the whole domain.

**Comment by hourianto** [comment]
The commit that added it is https://github.com/easylist/easylist/commit/53c0d2da1490ba122a8aa68523bc86975b9986fc

**Comment by alixTal** [comment]
I use Cloudflare tunnels every day, a lot of people use this to share their local development without the need to register a Cloudflare account. This is really bad, please reverse it.

**Comment by papersplease** [comment]
Clearly a mistake, but the curious thing is that at absolutely the same time trycloudflare.com made it into Brave's safe browsing database somehow. Now it warns that the trycloudflare.com might be tracking you, on every domain. I think it uses Google's DB, does any other browser give that warning? What's the connection with EasyList? Two events are too close to be unrelated.

**Comment by henk717** [comment]
This is effecting all AI related notebooks on multiple different services that make use of trycloudflare links to expose their UI's.
An example of such a legitimate use case is https://koboldai.org/colabcpp which will generate a random trycloudflare link after loading. With this rule in place the initial page loads, but all API requests are blocked making it appear like an error in the software.
