### ISSUE TITLE
[NSFW] (*.)cams.com (video breakage by EasyList)

### ISSUE THREAD

**Issue by garry-ut99** [easylist/easylist#19925]
#### List the website(s) you're having issues with:

(NSFW): 
```
https://cams.com/
https://classic.cams.com/
https://models.cams.com/
https://mobile.cams.com/
https://old.cams.com/
```
#### What happens?

Breakage, videos don't load, caused by: https://github.com/easylist/easylist/blob/f7ad94b973037a5e6541d411fbb6817b822391b0/easylist/easylist_thirdparty.txt#L236

#### Screenshot(s) 

BROKEN: [SCREENSHOOT 1](https://github.com/user-attachments/assets/2951140d-7b0e-44e8-b01b-c37f56aa44bd)
WORKING: [SCREENSHOOT 2](https://github.com/user-attachments/assets/e42721f3-8d3b-4966-8adf-78ea006e33b8)
uBO logger: [SCREENSHOOT 3](https://github.com/user-attachments/assets/659c8d3d-2fca-4183-ac0c-d4dc9f01871a)

#### Your settings:

- OS/version: W
- Browser/version: Firefox/Chromium
- Ad block extension/version: uBO dev - default

**Comment by Yuki2718** [comment]
Where do you access from? I don't see that request and video plays fine.

**Comment by garry-ut99** [comment]
> I don't see that request and video plays fine.

On all the listed subdomains or just `cams.com`? I can agree that currently there is no breakage at `cams.com`, but still breakage occurs on all other the listed subdomains (even when connecting both as `PL` and as `UK`).

And as for `cams.com` there is currenlty no breakage because site switched from: `fp27ee.wac.systemcdn.net` to `fp318b.wac.systemcdn.net` but given a fact yesterday there was a breakage, it might be back again at any time, it seems that sometimes the site uses different subdomains of `wac.systemcdn.net`.

**Comment by Yuki2718** [comment]
Tested some pages of `classic` and `old`, still no `systemcdn.net` request at all. It's possible they're region- or DNS-dependent.

**Comment by garry-ut99** [comment]
I still can reproduce, even from several different locations, including JAP, HONG KONG, UK, PL, and several more.
Curious what location you are connecting from (perhaps JAP) and which domain do tumbnail images load for you from.

**Comment by Yuki2718** [comment]
Okay, it's a CNAME issue and now I can reproduce. IDK why I didn't test on Firefox.

**Comment by Yuki2718** [comment]
@Khrin Is the rule still needed?
