### ISSUE TITLE
block spam website asap

### ISSUE THREAD

**Issue by olumolu** [easylist/easylist#19948]
1000fapvids.online
ddbca.localmeets.link

They do dns rebinding attack did not able to research more on that if anyone can do let me know.

**Comment by Yuki2718** [comment]
I only get 404 error or a message `Unknown`. We don't add domain just because someone said we should without detailed information, not to mention it is not a main job of EL to block spams.

**Comment by olumolu** [comment]
You can open the website your self and check by your self. I have seen this as i have opened this website and see what it is doing sheddy

**Comment by Yuki2718** [comment]
> You can open the website your self and check by your self.

> I only get 404 error or a message `Unknown`.
