### ISSUE TITLE
https://m.blog.naver.com/PostView.naver?blogId=potoi&logNo=223567874407&navType=by - Screen Flickering

### ISSUE THREAD

**Issue by mpccelon** [easylist/easylist#19952]
#### List the website(s) you're having issues with:

https://m.blog.naver.com/PostView.naver?blogId=potoi&logNo=223567874407&navType=by

#### What happens?

Scrolling to a specific part of the page (certain image) causes massive flickering

#### Screenshot(s) 

https://github.com/user-attachments/assets/fbe43483-9a06-40f4-9d2a-55eae8704101

#### Filter lists you're using:

ABP for Samsung Internet with Language Filters:
- English
- Korean

#### Your settings:

- OS/version: Android 14
- Browser/version: Samsung Internet
- Ad block extension/version:  Adblock Plus for Samsung Internet

#### Other details:

Also reported to KoreanList https://github.com/easylist/KoreanList/issues/1399

**Comment by ryanbr** [comment]
Would take it up with Korean lists. I couldn't repo.
