### ISSUE TITLE
https://grsecurity.net/ sponsors

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#2]
Hope it's ok to post reports here. If not, let me know. Using GitHub's issue tracker to report issues is a lot better than posting on a forum.

`https://grsecurity.net/`
Unblocked sponsors at the bottom.

**Comment by monzta** [comment]
We can give it a try. 

https://github.com/easylist/easylist/commit/f2181267e6e839e370f2ef0f1c73917f4b9e3bec
