### ISSUE TITLE
bk.com

### ISSUE THREAD

**Issue by Reggie521** [easylist/easylist#20009]
#### List the website(s) you're having issues with: 
https://www.bk.com/

#### What happens?
Site does not load

#### Filter lists you're using:
uBlock Origin default + EasyList/uBO – Cookie Notices

#### Your settings:

- OS/version:  Windows 11
- Browser/version:  Firefox 130
- Ad block extension/version: uBlock Origin 1.59.0

#### Other details:
Site seems to be broken with EasyList Cookie List enabled

**Comment by ryanbr** [comment]
Loading here? @Reggie521

**Comment by Reggie521** [comment]
Still a blank page for me. Unchecking that one filter list and reloading the page, it works. Checking it again and reloading the page, it's blank again.

**Comment by THEtomaso** [comment]
Loads here too.
Could be a regional thing though.

@Reggie521:
Does adding this rule make any difference at your end?:
`||geolocation.onetrust.com^$important,domain=bk.com`

**Comment by Reggie521** [comment]
This doesn't seem to be an issue anymore, so I'll close it for now.
