### ISSUE TITLE
Twitter full-screen sign-in wall/overlay

### ISSUE THREAD

**Issue by Rudxain** [easylist/easylist#20035]
#### List the website(s) you're having issues with:

Any Twitter (`x.com`) profile URL

#### What happens?

Visiting any profile while not logged-in causes Twitter to display a "Sign in to X" "paywall-like"

#### Filter lists you're using:

Everything in uBO "Filter lists" tab, except "Notifications"

#### Your settings:

- OS/version: Android 12
- Browser/version: Firefox 130
- Ad block extension/version: uBlock-Origin 1.59

#### Other details:
_None_

**Comment by Yuki2718** [comment]
Not fixable
