### ISSUE TITLE
https://manganato.com/bookmark breakage

### ISSUE THREAD

**Issue by UtkucanBaris** [easylist/easylist#20041]
#### List the website(s) you're having issues with:
**`https://manganato.com/bookmark`**

#### What happens?
**`https://user.mngusr.com/bookmark_get_list_full`** mngusr gets blocked because of EasyPrivacy and because mngusr is a database where bookmarks are it doesn't work

#### Filter lists you're using:

uBlock Origin , EasyList , EasyPrivacy

#### Other details:

EasyPrivacy Line:3336 ||mngusr.com^

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/7fb069803376e04158cbf8c87295beef59c23a6b
