### ISSUE TITLE
www.rtlplusz.hu

### ISSUE THREAD

**Issue by mpeter50** [easylist/easylist#20049]
#### List the website(s) you're having issues with:

- `https://www.rtlplusz.hu/`
- `https://www.rtlplusz.hu/bejelentkezes`

#### What happens?

The website is a TV channel's online content platform, login is required for access to content.

On the first URL, the person icon a the top right corner cannot be clicked. This icon otherwise leads to the login page, which is the second URL.
When you click the link, the following appears in the dev console:
```
Loading failed for the <script> with source “https://www.rtlplusz.hu/oneTrust-32cfdea5bb.bundle.js”.

ChunkLoadError: Loading chunk 3970 failed.
(error: https://www.rtlplusz.hu/oneTrust-32cfdea5bb.bundle.js)
    j https://www.rtlplusz.hu/client-af323d5e9e.bundle.js:294
    e https://www.rtlplusz.hu/client-af323d5e9e.bundle.js:294
    e https://www.rtlplusz.hu/client-af323d5e9e.bundle.js:294
    Ds https://www.rtlplusz.hu/client-af323d5e9e.bundle.js:294
```

The second URL does not load when manually entered.

#### Screenshot(s) 

There are no visible visual issues.

#### Filter lists you're using:

I'm using a lot, however I was able to determine the lists leading to this issue, which is "EasyList – Cookie Notices" and "Fanboy's Annoyance List". Please see the "other details" section.

#### Your settings:

- OS/version: Windows 10 and 11
- Browser/version: Firefox 129 and Librewolf 128
- Ad block extension/version: uBlock Origin 1.59.0

#### Other details:

With uBO's logger, I determined that unblocking `https://www.rtlplusz.hu/oneTrust-32cfdea5bb.bundle.js` fixes the site.

![image](https://github.com/user-attachments/assets/b124dea7-8b00-44d3-bdf0-b54edad8d9c4)

Possibly there is a better solution with a scriptlet, if there is a stub for onetrust.

I need your advice. I'll report this to Fanboy's list too, but should I instead report these to uBO in the future? Asking because multiple lists are affected, there may be an uBO specific unbreak list suitable for this, and there may even be a stub scriptlet for onetrust that you may not be able to utilize.

**Comment by Kami-prog** [comment]
try this
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by mpeter50** [comment]
I'll not report to Fanboy's list separately, because it turns out its hosted in this report too.

**Comment by mpeter50** [comment]
Confirmed as working ater update.
