### ISSUE TITLE
finance.yahoo.com (mobile)

### ISSUE THREAD

**Issue by Hebrew-uBO-User** [easylist/easylist#20065]
URLs:
`https://finance.yahoo.com/`
`https://finance.yahoo.com/quote/NVDA`

Please add
`finance.yahoo.com##[id$="Ad-Proxy"]`

or
`finance.yahoo.com###Col1-2-Ad-Proxy`
`finance.yahoo.com###Col1-0-Ad-Proxy`

or
`finance.yahoo.com###mrt-node-Col1-2-Ad`
`finance.yahoo.com###mrt-node-Col1-0-Ad`

**Comment by Yuki2718** [comment]
I don't see them. Can you screenshot them?

**Comment by Khrin** [comment]
@Yuki2718 I can see it, https://github.com/easylist/easylist/commit/f5498ed4666907b7ff87ba3c9ec7708eaba226ae
