### ISSUE TITLE
clanto.cloud false positive

### ISSUE THREAD

**Issue by clanto007** [easylist/easylist#20062]
Currently clanto.cloud is in easyprivacy_trackingservers_general . should be removed as it is a provider of multiple services.

The subdomains that do analytics are:
matomo.clanto.cloud
mato.clanto.cloud

**Comment by Yuki2718** [comment]
Please provide actual and testable cases of breakage or other troubles.

**Comment by clanto007** [comment]
https://file.clanto.cloud is a nextcloud instance
https://jitsi.clanto.cloud a jitsi meet instance
https://pdf.clanto.cloud/ a Stirling PDF instance
An NTP server time.clanto.cloud
A DNS server dns.clanto.cloud
An other services that use a subdomain of clanto.cloud

**Comment by Yuki2718** [comment]
Okay
