### ISSUE TITLE
player.ex.co, cdn.ex.co removal of domains & replace the element class name

### ISSUE THREAD

**Issue by meir-amar-ex-co** [easylist/easylist#20091]
Hi,
My name is Oren Regev, Chief Product Officer for [EX.CO](http://ex.co/) ([www.ex.co](http://www.ex.co/)) - We are a company providing end to end video platform for publishers.

Our clients, Tier 1 publishers in categories of news, finance, sports, entertainment and more are using [EX.CO](http://ex.co/) as their main video player and video CMS delivering video content to their articles and stories. In addition, [EX.CO](http://ex.co/) is also delivering video advertisements which are typically served before or after the video content has been served.

Here are 2 live examples of [ex.co](http://ex.co/) player in action on:
USA Today (owned by Gannett): https://www.usatoday.com/elections/?gnt-ub=100
Page Six (owned by NewsCorp): https://pagesix.com/2024/09/28/royal-family/inside-prince-harrys-bid-to-become-a-global-statesman/

I'm reaching out since it seems like you are blocking our entire player activity (both content and ads) effectively blocking legitimate video content (such as news and business stories) instead of ads only and I would like to ask you to make the following changes:
[EX.CO](http://ex.co/)'s content player is not loading any ads in case AdBlock is detected in the user session. As a result we ask you to remove [player.ex.co](http://player.ex.co/) from your list (as it's the main domain to serve our content player)
In addition, we ask for you to remove the [cdn.ex.co](http://cdn.ex.co/) domain since this is used to pull video content files and has no connection to video advertisements.

As you are currently detecting our entire player instead of ads only - please replace your detection of pbs__player (which is our content player) with __exco_ad_container (which is [EX.CO](http://ex.co/)'s ad container)
I'll be happy to provide more information if needed or hop on a call to speak through the details.

#### Removal domains
player.ex.co
cdn.ex.co

#### Replace element detection
pbs__player  to  __exco_ad_container

Thank you in advance,
Oren Regev

**Comment by ryanbr** [comment]
`"effectively blocking legitimate video content"`

Lets be honest ex.co just spams endless auto play video ads, and you're wanting special treatment. I see no reason why to remove this.
