### ISSUE TITLE
OPTIMUS FRAMEWORK : false positive with our calendar api

### ISSUE THREAD

**Issue by MetallianFR68** [easylist/easylist#20102]
Hi,

I'm the developper of an opensource project called OPTIMUS which is an alternative to GOOGLE MAIL, GOOGLE DRIVE, GOOGLE CALENDAR and GOOGLE CONTACTS.

A demo is available at https://demo.optimus-avocats.fr and our code is published [here ](https://git.cybertron.fr)

Many users informed us that their Calendar module isn't working anymore
I identified the problem : they are all using UBLOCK browser extension which relies on [Easy](https://easylist.to/easylist/easylist.txt)

Our calendar api calls are formatted like that : 
![image](https://github.com/user-attachments/assets/0f7b6b66-249b-4dc7-903c-77de5a6c5579)
"vestoptimus.ovh" is variable. Every user has their own domain.

the "/events?data=" filter is triggering the EasyFilter

That is a false positive

Could you please improve to avoid these false positives ?
We receive many support request because of that

Thanks in advance

**Comment by Yuki2718** [comment]
Need steps to reproduce, as just visiting the demo page doesn't trigger the request or the alledged issue.

**Comment by MetallianFR68** [comment]
Hi,

You can reproduce by going on our demo website : https://optimus.demoptimus5.ovh
Then login with the prefilled credentials
And click on "Agendas" in the left menu
You'll see that it triggers many "TypeError : failed to fetch" errors

Thanks in advance

**Comment by Yuki2718** [comment]
Removed the rule as I can't reproduce https://github.com/easylist/easylist/commit/ccb788e13cb6f089bbf0e6a74ace8bdeec6a4df0 any more.
