### ISSUE TITLE
old.reddit.com

### ISSUE THREAD

**Issue by qoijjj** [easylist/easylist#20132]
#### List the website(s) you're having issues with:

`https://old.reddit.com/r/linux/`

#### What happens?

Multiple image ad banners appear.

#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/ccd5fff7-de41-442f-9255-ead7e4bf04ea)
![image](https://github.com/user-attachments/assets/5e3a0042-ea9f-41e0-9be6-dd299543b7b6)

#### Filter lists you're using:

EasyList, EasyPrivacy

#### Your settings:

- OS/version: Fedora 40
- Browser/version: Vanadium/Chromium 129.0.6668.89
- Ad block extension/version: None, chromium subresource filter

#### Other details:

the div classes:

![image](https://github.com/user-attachments/assets/f90bb409-2894-4a65-949f-45c98fe01ee3)

Looking at easylist, it looks like many classes are checked for, including the `native-ad-container` class on `old.reddit.com` and all of the following generic classes:

However, none of them appear to include the plain `ad-container`:

![image](https://github.com/user-attachments/assets/78b9ef9a-8a17-49f8-8d3d-ed54a2411e3e)
![image](https://github.com/user-attachments/assets/d786f2dc-5c6d-4e39-b842-9cf151418efd)

**Comment by ryanbr** [comment]
`easylist/easylist_specific_hide.txt:reddit.com,reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion##.promotedlink:not([style^="height: 1px;"])`

Already in list.
