### ISSUE TITLE
Request to stop blocking iframes from `https://plausible.io/share/`, as these are used to load shared

### ISSUE THREAD

**Issue by maximepvrt** [easylist/easylist#20148]
Plausible Analytics allows users to embed public, shareable dashboards via URLs such as https://plausible.io/share/{dashboard-id}. These iframes, which provide useful site analytics results to visitors, are currently blocked by uBlock Origin.

#### List the website(s) you're having issues with:

`https://plausible.io/share/{dashboard-id}`

#### What happens?

Embed an iframe from https://plausible.io/share/ on a webpage.
Enable uBlock Origin.
Notice that the iframe displaying shared statistics is blocked.
Expected behavior:

uBlock Origin should allow iframes from https://plausible.io/share/ to load, as these serve public analytics data, not ads or tracking scripts.

More details about Plausible’s privacy-friendly approach and the embedded dashboard feature can be found here: https://plausible.io/docs/embed-dashboard.

Allowing these iframes would ensure users can access shared statistics reports without them being wrongly classified as ads or trackers.

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: MacOS 15.0
- Browser/version: Arc 1.63.0 
- Ad block extension/version: uBlock Origin v1.60.0

**Comment by maximepvrt** [comment]
linked to https://github.com/uBlockOrigin/uAssets/issues/25607

**Comment by ryanbr** [comment]
we're not blocking https://plausible.io/share/  Not supplying more details doesn't help.

**Comment by maximepvrt** [comment]
@ryanbr I’ve tested this again, and it appears that uBlock Origin is indeed blocking the iframe from loading. When I disable uBlock Origin, the iframe loads correctly. Additionally, the iframe itself indicates that an extension is preventing it from displaying.
<img width="713" alt="Capture d’écran 2024-10-12 à 15 11 55" src="https://github.com/user-attachments/assets/cc4070c2-5e24-4c4e-87fa-8431d6c8bcd4">
"Cette page a été bloquée par une extension" = "This page has been blocked by an extension"


Could this issue be related to the rule in the EasyPrivacy list found here:
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers_thirdparty.txt#L1595
This line seems to block the entire plausible.io domain. Could this be causing the iframe to be blocked?

Thank you for your help.

**Comment by ryanbr** [comment]
No exceptions. plausible.io rule is third-party, so unless plausible is using a different domain url?
