### ISSUE TITLE
*.ct.sendgrid.net

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [easylist/easylist#20158]
#### List the website(s) you're having issues with:
`https://u21880139.ct.sendgrid.net/wf/open?upn=u001.0CgNwsCDU5TM48M0bFI1PSPOmOJAXiqOKTxpEKPV1wdDhUF-2FanA7h7IxVKS9prrpM1Ylq1KwV22qceAQGxt8RvLARhh9-2FLtdrVmAvrs805ChAr5oW1u1itervyX6hNID1BjcJ4lgbtXXSwfx1L-2F5f3RfZa8hHmT-2FPbwTiF9zUp7Ycg1eb0EBHlyWON6D-2FLNz7DpqInTa3jcYJw1-2FxM-2FSI22ZECBjcWbIUyjp9H3N-2FTq3TjCqMzODqYf-2F0dndAoD2wpBzzfnVOW4Ej71laPERSnv9H9mJVs-2F8wYlhYDZ4pFmn1qCvwF3NODuQyFgxM0yhTdLR8Pj8BKBSknIxb54GFg7TgVEClsDXWGWA1M1SmAherUlhmfEVaYMknd6q6usu0yIg8x1vcKSmpZpVtuNiuvI4-2F7btNPgucEUrM19Rfse2Vk9orwCfCuuiMMTLN-2BA84UStXT6yE9mw16m-2Bf8nivcZHqxIWYWOy3PIcyfE-2FpaI-3D`

#### What happens?
Email Tracking Pixel

#### Your settings:

- OS/version: Arch Linux
- Browser/version: Firefox 131.0
- Ad block extension/version: uBlock Origin 1.59.0

**Comment by monzta** [comment]
Isn't this covered by this filter? https://github.com/easylist/easylist/blob/bd890bf17cea4d839e88d0d8b132bd0d6936348f/easyprivacy/easyprivacy_general_emailtrackers.txt#L26

**Comment by ryanbr** [comment]
`easyprivacy_general_emailtrackers.txt:/wf/open?upn=$image`

Also
