### ISSUE TITLE
How to contribute my filters and rules? I can give a PR if guided

### ISSUE THREAD

**Issue by dheerajbhaskar** [easylist/easylist#202]
## Summary

I want to contribute a few filters and rules I've made. Please tell me:
1. if they're useful or not
2. if they're useful How do I contribute, as in, to which file do I give a PR?

## My filters:
```
! 8/19/2016, 12:57:41 PM https://extratorrent.cc/torrent/4948428/Acronis+True+Image+2016+19.0.6571+%2B+BootCD.html
extratorrent.cc##table > tbody > tr:nth-of-type(3) > td > table > tbody > tr > td:nth-of-type(2) > div:nth-of-type(1)

! 8/19/2016, 12:58:10 PM https://extratorrent.cc/torrent/4948428/Acronis+True+Image+2016+19.0.6571+%2B+BootCD.html
extratorrent.cc##table > tbody > tr:nth-of-type(3) > td > table > tbody > tr > td:nth-of-type(2) > div:nth-of-type(3) > table > tbody > tr > .tabledata1

! 9/18/2016, 5:09:59 AM http://www.saavn.com/s/featured/english/Weekly_Top_Songs
www.saavn.com###idle-unit-curtain

! 9/18/2016, 5:10:21 AM http://www.saavn.com/s/featured/english/Weekly_Top_Songs
www.saavn.com###searchhalfpage_adiframe

! 9/18/2016, 5:13:21 AM http://www.saavn.com/s/featured/english/Weekly_Top_Songs
www.saavn.com###ad-drawer

! 10/1/2016, 2:38:01 AM http://www.saavn.com/
www.saavn.com###vid-promo-fill

! 10/6/2016, 11:47:37 PM http://www.businessinsider.com/ingvar-kamprad-lost-17-billion-2011-3?IR=T
www.businessinsider.com##.tp-modal

! 10/6/2016, 11:47:50 PM http://www.businessinsider.com/ingvar-kamprad-lost-17-billion-2011-3?IR=T
www.businessinsider.com##.tp-active.tp-backdrop

! 11/16/2016, 4:35:24 PM http://www.techtimes.com/articles/166242/20160622/amazon-cloud-drive-offers-free-unlimited-cloud-storage-for-three-months-on-mobile.htm
www.techtimes.com###player_container

```

### My rules
```
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
www.pcworld.com http://www.pcworld.com/www/js/init_device.js script block
www.saavn.com accountkit.com * allow
www.saavn.com doubleclick.net * allow
www.saavn.com facebook.com * allow
www.saavn.com googleadservices.com * allow
www.saavn.com googletagservices.com * allow
www.saavn.com jwpltx.com * allow
www.saavn.com mookie1.com * noop
www.saavn.com saavn.com * allow
www.saavn.com scorecardresearch.com * allow
www.saavn.com sokrati.com * allow
www.techtimes.com http://prod.cdn.n.bsvideos.com media block
www.thedailymeal.com http://www.thedailymeal.com/sites/all/modules/custom/dam/modules/dam_jwplayer object block

```

**Comment by dheerajbhaskar** [comment]
I use ublock origin

I think dynamic rules makes sense only when one enables them, not sure there is any point contributing them since they're not on by default and there are no lists for dynamic rules. Please let me know if I'm mistaken

**Comment by IDKwhattoputhere** [comment]
Dynamic filtering rules are only being applied when advanced user mode is enabled which is not the default. Futhermore they're not compatible with Adblock Plus so won't be added to EasyList. They can't be added through filter lists by design anyways.

Best way to contribute is to post URLs where the filters apply and describe what the filters do or post a screenshot.
Usually there's more activity on [forums.lanik.us](https://forums.lanik.us/) so you might want to post there instead.

**Comment by dheerajbhaskar** [comment]
@IDKwhattoputhere thanks for the general guidance and the specific example, will check it out

**Comment by ddraws** [comment]
Dynamic filters are best created and applied by the users. 
And your other filters are just cosmetic filters and does not improve security at all. (Content is still loaded, just not displayed)

**Comment by waailasif3** [comment]
OMG these rules and filters enable constant playback of the playlists on saavn without ads. Thanks alot!
Definitely helpful. Keep it up!
