### ISSUE TITLE
izatcloud shouldnt be blocked

### ISSUE THREAD

**Issue by jordansworld** [easylist/easylist#20202]
izatcloud.net shouldnt be blocked.says this on website: The Qualcomm Location XTRA Service generates and provides accurate Satellite positions for extended periods of time to a mobile device

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8a818d533683495cbe734a605a9746c059d36cc0

https://blog.brixit.nl/nitrokey-dissapoints-me/ 

No harm of this so far
