### ISSUE TITLE
Unconfined rule for uni-leipzig.de breaks webapp core functionality

### ISSUE THREAD

**Issue by dgerhardt** [easylist/easylist#20238]
#### List the website(s) you're having issues with:

* https://particify.uni-leipzig.de

#### What happens?

Webapp core functionality (SPA) is broken because XHR API requests to a URL containing `/stats/` are blocked.

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

- OS/version: Ubuntu 24.04
- Browser/version: Firefox 131
- Ad block extension/version: uBlock Origin 1.60

#### Other details:

The affected endpoint is providing stats for the end user and is not tracking related.

Blocked URL pattern: `/api/room/<ID>/contentgroup/<ID>/stats/user/<ID>`
Problematic rule: `||uni-leipzig.de^*/stats/` (https://github.com/easylist/easylist/blob/cba8051a27dbbf2cfb8ed7982a8afb68855d09d6/easyprivacy/easyprivacy_thirdparty_international.txt#L157)

This rule is very vague and not limited to a specific subdomain. Furthermore, the regex is not anchored. It is unclear to me what this filter is intended to block since Matomo is used for tracking which is detected without a site specific rule.

**Comment by monzta** [comment]
This was a very old filter. I just removed it.
