### ISSUE TITLE
ads.atmosphere.copernicus.eu

### ISSUE THREAD

**Issue by keul** [easylist/easylist#20230]
#### List the website(s) you're having issues with:

`https://ads.atmosphere.copernicus.eu/`

#### What happens?

We suspect this portal is in this list just because of the (unfortunate) "ads" acronym in its domain. But the portal is just the Atmosphere Data Store, from Copernicus Project. There is a full ecosystem on portals made in the same way, but only "ads." is blocked. Other like "cds." are not!

See https://github.com/easylist/easylist/blob/f310bd5ff1729d060cf5761f17a737ff98ba2965/easylist/easylist_general_block.txt#L827C126-L827C155

This settings makes impossible to perform AJAX call to some REST APIs hosted on that portal.

#### Your settings:

- OS/version: macOS 14.7
- Browser/version: Firefox 131.0.2
- Ad block extension/version:  uBlock Origin 1.60.0

#### Other details:

See https://github.com/easylist/easylist/blob/f310bd5ff1729d060cf5761f17a737ff98ba2965/easylist/easylist_general_block.txt#L827C126-L827C155

**Comment by keul** [comment]
Sorry, I'll try to detail a little better. Maybe I misunderstood the meaning on this file? I believed that "list_general_block" was a blocking list, not a white list.

With uBlockOrigin activated, I replicate in this way:

- I go to https://cds-dev-bopen.copernicus-climate.eu/datasets?kw=Product+type%3A+Reanalysis
- this triggers a fetch call to ads.atmosphere.copernicus.eu
- checking the console, I see that call to https://ads.atmosphere.copernicus.eu/api/catalogue/v1/datasets?kw=Product+type%3A+Reanalysis has been "blocked by uBlock Origin"
- opening the extension panel, then the network monitor in the extention, I see that the rule blocking the request is the following (which is the same in the file reported above):

```
://ads.$~image,from=~ads.8designers.com|~ads.ac.uk|~ads.adstream.com.ro|~ads.allegro.pl|~ads.am|~ads.amazon|~ads.apple.com|~ads.atmosphere.copernicus.eu|~ads.band|~ads.bestprints.biz|~ads.bikepump.com|~ads.brave.com|~ads.buscaempresas.co|~ads.business.bell.ca|~ads.cafebazaar.ir|~ads.colombiaonline.com|~ads.comeon.com|~ads.cvut.cz|~ads.doordash.com|~ads.dosocial.ge|~ads.dosocial.me|~ads.elevateplatform.co.uk|~ads.finance|~ads.google.cn|~ads.google.com|~ads.gree.net|~ads.gurkerl.at|~ads.harvard.edu|~ads.instacart.com|~ads.jiosaavn.com|~ads.kaipoke.biz|~ads.kazakh-zerno.net|~ads.kifli.hu|~ads.knuspr.de|~ads.listonic.com|~ads.luarmor.net|~ads.magalu.com|~ads.mercadolivre.com.br|~ads.mgid.com|~ads.microsoft.com|~ads.midwayusa.com|~ads.mobilebet.com|~ads.mojagazetka.com|~ads.msstate.edu|~ads.mst.dk|~ads.mt|~ads.nc|~ads.nipr.ac.jp|~ads.olx.pl|~ads.pinterest.com|~ads.red|~ads.rohlik.cz|~ads.rohlik.group|~ads.route.cc|~ads.safi-gmbh.ch|~ads.scotiabank.com|~ads.selfip.com|~ads.shopee.cn|~ads.shopee.co.th|~ads.shopee.com.br|~ads.shopee.com.mx|~ads.shopee.com.my|~ads.shopee.kr|~ads.shopee.ph|~ads.shopee.pl|~ads.shopee.sg|~ads.shopee.tw|~ads.shopee.vn|~ads.smartnews.com|~ads.snapchat.com|~ads.socialtheater.com|~ads.spotify.com|~ads.studyplus.co.jp|~ads.taboola.com|~ads.tiktok.com|~ads.typepad.jp|~ads.us.tiktok.com|~ads.viksaffiliates.com|~ads.vk.com|~ads.watson.ch|~ads.x.com|~ads.yandex|~badassembly.com|~caravansforsale.co.uk|~fusac.fr|~memo2.nl|~reempresa.org|~satmetrix.com|~seriouswheels.com,to=~ads.remix.es
```

**Comment by Yuki2718** [comment]
Okay, I can reproduce on that site. `~` means exclusion, but this for `$from` works only if directly visit `ads.atmosphere.copernicus.eu`. `to=~` is needed to fix the issue but this is uBO-specific syntax.

**Comment by keul** [comment]
@Yuki2718 colleague using a different Ads-blocker (https://chromewebstore.google.com/detail/adblock-bloquea-anuncios/gighmmpiobklfepjocnamgkkbiglidom?hl=es) reported that part of the issue is still there.

AJAX calls (which is used to change the text inside a link on bottom-left of the page) now works (thanks for that)! But: using this ad-blocker, click on link itself is not working: the page "flash" but site will not be opened.

![Screenshot 2024-10-24 alle 12 26 17](https://github.com/user-attachments/assets/374685c1-6ffa-4111-adcc-4af7963bbd1f)

This still seems EasyList, because if I disabled that list on this extension, link start working

**Comment by Yuki2718** [comment]
Will be fixed once his filters get updated.
