### ISSUE TITLE
licensebuttons.net - improperly filtered as "annoyances" despite domain move by Creative Commons

### ISSUE THREAD

**Issue by pivotman319-owo** [easylist/easylist#20253]
#### List the website(s) you're having issues with:
Any MediaWiki instance making use of `https://licensebuttons.net` resources via the copyright footer option. The domain in question is the new hosting resource for Creative Commons license button images (previously hosted as `https://i.creativecommons.org`), and should not be erroneously classified as under the "fanboy-related annoyance" umbrella.

See footer of https://betawiki.net/wiki/Special:Version#footer-copyrightico for an example.

#### What happens?
The license button image is blocked by uBO.

#### Screenshot(s) 
![uBO blocking CC-BY-SA 4.0 license button image](https://github.com/user-attachments/assets/d0d4d534-0c96-46fe-b6e3-8a7a1842ead9)
![Ditto](https://github.com/user-attachments/assets/f840048e-77c7-4098-9b1b-07d468ba10dd)

#### Filter lists you're using:
All uBO filter lists enabled sans regional filters:
![all uBO filter lists enabled](https://github.com/user-attachments/assets/1e25ba71-fdaf-4962-a182-11b66f3290d7)

#### Your settings:
- OS/version: Windows 11 v24H2 Dev Channel - `10.0.26100.2130 (ge_release_svc_betaflt_prod1.241009-1717)` amd64fre
- Browser/version: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
- Ad block extension/version: uBlock Origin v1.60.0

#### Other details:
Failing filter: https://github.com/easylist/easylist/blob/298ca33498e813fd0f4ba973e4a077eda61a2932/fanboy-addon/fanboy_annoyance_thirdparty.txt#L152

**Comment by Khrin** [comment]
Filter won't be removed
