### ISSUE TITLE
embed.ly is broken with EasyPrivacy

### ISSUE THREAD

**Issue by theel0ja** [easylist/easylist#2037]
### List the website(s) you're having issues:

`https://embed.ly/code`

### What happens?

Broken code generator.

![](https://storage.theel0ja.info/misc/broken-site.png)

### List Subscriptions you're using:

![screenshot from 2018-10-13 08-54-01](https://user-images.githubusercontent.com/5832930/46901972-9fd1b500-cec5-11e8-8189-c6714a0c64a9.png)

### Your settings

- OS/version: solus
- Browser/version: firefox nightly
- Adblock Extension/version: ublock origin

### Other details:

```
@@embed.ly/static/scripts/tracking.js
```

fixes it for me.

**Comment by krystian3w** [comment]
Works without fix:

![image](https://user-images.githubusercontent.com/35370833/46863838-ca196900-ce18-11e8-858a-bc5b1ca77372.png) | ![image](https://user-images.githubusercontent.com/35370833/46863874-e3221a00-ce18-11e8-9df8-a9fe31fc8755.png)
--- | ---

**Comment by theel0ja** [comment]
Seems to work for me too.
