### ISSUE TITLE
finnair.com: breakage

### ISSUE THREAD

**Issue by ntoskrnl11** [easylist/easylist#20485]
#### List the website(s) you're having issues with:

`finnair.com`

#### What happens?

When trying to pay for flights, the process fails at the end, just after selecting the payment method (nothing happens when you click the button to proceed). I suppose it's possible to reproduce without actually paying, but I also identified the problematic rule below.

#### Screenshot(s) 

Sorry, didn't get screenshots.

#### Filter lists you're using:

EasyList – Cookie Notices

#### Your settings:

N/A

#### Other details:

Problematic rule that probably needs to be removed:
```
||cms.finnair.com^*?view=fin-fragment-json$xmlhttprequest,domain=finnair.com
```
Added in #20024

**Comment by peace2000** [comment]
I can reproduce.
