### ISSUE TITLE
l.ms.starbucks.co.jp

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [easylist/easylist#20609]
#### List the website(s) you're having issues with:
`https://l.ms.starbucks.co.jp/rts/open.aspx?tp=i-1NGB-75-8TY-280wxU-1n-vwmU-1c-27bOII-lB3tVPD4lo-25TAv8&pi=9a1QDZWQMh-3rCCYaJttABqvprGK_Mre4aGlaNCKAvU`

#### What happens?
Email tracking pixel

#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by Yuki2718** [comment]
Already blocked by `/open.aspx?`. Please report only unblocked pixels.
