### ISSUE TITLE
www.amazon.co.jp

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#20611]
#### List the website(s) you're having issues with:
`https://www.amazon.co.jp/gp/r.html?C=3S2VX7V1JYE6D&K=2YVB5SSIBI3Q2&M=urn:rtn:msg:202410300729039912d4d8caa7425e8fcb078c72e0p0fe&R=1YTLIO5RVGSQV&T=E&U=https%3A%2F%2Fimages-fe.ssl-images-amazon.com%2Fimages%2FG%2F01%2Fnav%2Ftransp.gif&H=TFR9TU97IGOWB4D8YHSRUUPP73UA&ref_=pe_24402962_429589722_open`

#### What happens?
Email tracking pixel from `auto-confirm@amazon.co.jp`

#### Your settings:

- OS/version: Arch Linux
- Browser/version: Firefox 132.0 
- Ad block extension/version: uBlock Origin 1.60.0

**Comment by Yuki2718** [comment]
Already blocked by `/gp/r.html?$image`
