### ISSUE TITLE
character.ai

### ISSUE THREAD

**Issue by bkeeper180** [easylist/easylist#20673]
#### List the website(s) you're having issues with:

`character.ai`

#### What happens?

Telemetry, tracks almost every site interaction

`events.character.ai`

Additional third party telemetry

`prodregistryv2.org`

Possible fingerprinter, same POST data as `featuregates.org` which is already blocked.

`featureassets.org`

#### Screenshot(s) 

<img width="788" alt="character ai" src="https://github.com/user-attachments/assets/b8cdca88-1424-4cc7-92e7-bc4fb4e4b4b7">

#### Filter lists you're using:

EasyList
EasyPrivacy

#### Your settings:

- OS/version: Windows 10 22H2
- Browser/version: Firefox 132.0.2
- Ad block extension/version: uBlock Origin 1.61.0

#### Other details:

featureassets org won't appear when the page first loads. You have to click the character ai logo at top left, then the domain should appear. Sometimes it won't appear anyway.

**Comment by Yuki2718** [comment]
I'm not entirely sure if generically blocking the last two is safe: `https://support.atlassian.com/organization-administration/docs/ip-addresses-and-domains-for-atlassian-cloud-products/`

**Comment by Yuki2718** [comment]
It turned out `prodregistryv2.org` is in fact used for the initial registration as blocking it causes failure, while once registared there seems to be no problem any longer. I'll unblock this.
