### ISSUE TITLE
4chan: Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error

### ISSUE THREAD

**Issue by boogiepop** [easylist/easylist#2067]
### List the website(s) you're having issues:
`https://boards.4chan.org/g/`

### What happens?
 the 4chan X userscript displays this error: 
> Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error

### List Subscriptions you're using:
EasyList

### Your settings
- OS/version:  Windows 10 x64
- Browser/version: Firefox 62.0.3 x64
- Adblock Extension/version: uBlock Origin 1.17.0

### Other details:
If I cancel my subscription to EasyList I stopp getting the error.

**Comment by ryanbr** [comment]
Seems fine here? didnt see it. re-test.
