### ISSUE TITLE
Action button not working + Blocked ULR other the ads

### ISSUE THREAD

**Issue by jawad53** [easylist/easylist#20683]
#### List the website(s) you're having issues with:
https://smallseotools.com/plagiarism-checker/
https://smallseotools.com/
https://smallseotools.com/grammar-checker/

#### What happens?
Tools stopped working on whole website as buttons are not clickable
Google Tag Manager and related analytics scripts are being blocked on our website, smallseotools.com, causing some problems with our analytics tracking.

#### Screenshot(s) 
![image](https://github.com/user-attachments/assets/1129ce96-3575-4cc1-87a5-40b2a438bd41)
![image](https://github.com/user-attachments/assets/1d1030cc-753a-4c14-90ac-8705f4d28e91)
![image](https://github.com/user-attachments/assets/79afc730-0778-4c6a-b38b-ca796c1df451)

#### Your settings:

- OS/version: Microsoft Windows
Version 23H2 (OS Build 22631.4460)
- Browser/version:  Version 131.0.6778.70 (Official Build) (64-bit)
- Ad block extension/version:   Version 6.11.0

#### Other details:
Hello team

I hope this message finds you well. I wanted to bring to your attention an issue we've encountered after the recent Adblocker update. It seems that Tools stopped working and, Google Tag Manager and related analytics scripts are being blocked on our website, smallseotools.com, causing some problems with our analytics tracking.

The specific URLs being blocked are:
https://www.googletagmanager.com/gtag/js?id=UA-39540269-1
https://www.googletagmanager.com/gtag/js?id=G-ZVFQ50NB89
https://www.googletagmanager.com/gtag/js?id=G-ZVFQ50NB89&l=dataLayer&cx=c&gtm=45He4be0v810312730za200
https://www.googletagmanager.com/gtag/js?id=UA-39540269-1&l=dataLayer&cx=c&gtm=45He4be0v810312730za200

Because of this, we're seeing incomplete and inaccurate data in Google Analytics, which impacts our ability to track and improve our website's performance.
The tools button on the whole website is also not working.

We understand the tools button and, these URLs aren't typically associated with ads or intrusive scripts, so this might be an unintentional glitch in the update. Please look into this and let us know if there's a fix or workaround.

We'd appreciate your help in resolving this as soon as possible. If you need any additional information from us, please feel free to reach out.

**Comment by jordansworld** [comment]
it looks like whole site is blocked. @ryanbr

**Comment by jawad53** [comment]
YES @ryanbr it impacts millions of users and does not allow users to interact with the site.

**Comment by ryanbr** [comment]
Remove the tracking scripts tied to the button. This block on googletagmanager server isn't new, if there is conscious decision to tie google analytics to the button, then don't do it. Or just don't break the site intentionally if the gtm script isn't loaded.

No other response is needed here.

Thanks for understanding.

**Comment by ryanbr** [comment]
My absolute distain, you willingly break a site by 

1. Adding analytics to buttons
2. And then break the site if said script is block
3. Then complain here expecting us to undo your shitty code.

Fix your site.
