### ISSUE TITLE
CDN www.googletagmanager.com Block

### ISSUE THREAD

**Issue by mohsinali1065** [easylist/easylist#20682]
#### List the website(s) you're having issues with:

`https://www.duplichecker.com/`

#### What happens?

As user browsing website with adblocker enable, it block googletagmanager cdn to load causing glitch in google analytics data.

#### Screenshot(s) 

![image](https://github.com/user-attachments/assets/d4cee230-dc84-43d8-9135-213fdf0bed3b)

#### Filter lists you're using:

![image](https://github.com/user-attachments/assets/3a28c78e-a4fd-42a9-a9d5-0c85693aa95d)

#### Your settings:

Browser:
Version 131.0.6778.70 (Official Build) (64-bit)

AdBlock:
Version 6.11.0

Windows :
Microsoft Windows
Version 23H2 (OS Build 22631.4460)
© Microsoft Corporation. All rights reserved.

#### Other details:

It should not block googletagmanager.com it should only browser advertisment.

**Comment by monzta** [comment]
The purpose of EasyPrivacy is to block tracking: https://github.com/easylist/easylist?tab=readme-ov-file#easyprivacy 

Don't enable it if you want trackers to load.
