### ISSUE TITLE
Adguar off

### ISSUE THREAD

**Issue by SAdasds12331** [easylist/easylist#20718]
#### What happens?

Not working site 

#### Screenshot(s) 
![Screenshot_5](https://github.com/user-attachments/assets/b24043c5-c189-473d-be31-c7f7069898e5)
![Screenshot_6](https://github.com/user-attachments/assets/23502a89-4b1d-46c5-870a-8e1fa327ab2c)

#### Filter lists you're using:

IDK

#### Your settings:

LAzzyyyyy

#### Other details:

just help already

**Comment by Haru-Imirk** [comment]
I have had this error for more than 6 hours, only the status changes, for me it is 503.

![image](https://github.com/user-attachments/assets/cee4bf70-8fb2-477a-b6c3-be81c212de86)

**Comment by QionghuaGit** [comment]
I had this error without adguard, maybe its because of the website itself?

**Comment by 123anonnn** [comment]
It is the website. It started working for few minutes and now it's down again. I bet devs team is sweating rn

**Comment by valdearg** [comment]
Please do not report issues with Kemono/Coomer here. The Easylist list is only responsible for the issues with authenticating. This is specifically the line on https://github.com/easylist/easylist/blob/dffb31c609c6962bd081a16480d78ebe2555208d/easyprivacy/easyprivacy_specific_uBO.txt#L37 

Which causes issues with the new authentication system, you can resolve this with the following custom filter:

@@||kemono.su/api/v1/authentication/login$xhr,1p

DO NOT REPORT ANY 500 ERRORS IN HERE. The developers at Kemono ARE AWARE and are resolving these issues now.
