### ISSUE TITLE
Kemono site is acting weird

### ISSUE THREAD

**Issue by CrunchyGears13** [easylist/easylist#20723]
Kemono

#### List the website(s) you're having issues with:
https://kemono.su/artists/updated

 NSFW

#### What happens?
The site is simply acting weird for some reason, but I don't know what. The importing froze yesterday, but it is back up and running. However, it's not loading anything when I click on "artists" and it shows an error.

#### Screenshot(s) 
![Screenshot 2024-11-26 9 10 26 AM](https://github.com/user-attachments/assets/76f815c1-3eaa-448c-8f5b-105e08b028e8)

#### Filter lists you're using:
Recent imports/artists

 Adblock Plus

#### Your settings:
I don't know if there are any issues or conflicts going on.

- Browser/version: Chrome
- Ad block extension/version: Adblock Plus

#### Other details:
The site is just acting weird, and it can't show load any new imports.

**Comment by PatreonOfficial** [comment]
AdBlock does not seem to affect the site, turning it off does not change anything, exept displaying ads.

**Comment by m300m** [comment]
i have that issue too is there a fix for it?

**Comment by SyX332** [comment]
Same happening for me...  was fine like 1 hour ago

**Comment by TranGGrGB129** [comment]
Is it normal to still have this problem? Am I the only one having this problem now?

**Comment by PatreonOfficial** [comment]
> Is it normal to still have this problem? Am I the only one having this problem now?

Yes

**Comment by kingstonporn** [comment]
+1

**Comment by SamuNuAm** [comment]
Its a server problem so everyone will have problems when opening the site. just wait until they fix it

**Comment by gameturkey99** [comment]
Does kemono broken? If I want search artists it will tell me off Adblock? But I never use this(sry my English is not good)

**Comment by GhostHunter94R** [comment]
Websites, In my opinion, Have absolutely no right or reason to be Anti-adblock OR use ads.
I don't care if they're like 'Without ads, we WILL NOT survive.', Which will be a lie.

**Comment by 123anonnn** [comment]
Devsss fix it quick before they took down their mega files down!!!

**Comment by lunatic-gh** [comment]
This thread just shows how lazy people are...

Take your 10 seconds, click on the "Status" page, and see that literally all of their servers are down. This has absolutely nothing to do with any adblock, rather that Header is just there because tons of such issues do arise from adblocks/filterlists.

**Comment by PatreonOfficial** [comment]
All fine ^^

**Comment by PatreonOfficial** [comment]
> This thread just shows how lazy people are...
> 
> Take your 10 seconds, click on the "Status" page, and see that literally all of their servers are down. This has absolutely nothing to do with any adblock, rather that Header is just there because tons of such issues do arise from adblocks/filterlists.

They said on thaor own page, with an yellow banner essentially 'Our page does not work properly with an AdBlocker'
No wonder they first suspect what the page tells them is an issue.

**Comment by valdearg** [comment]
Please do not report issues with Kemono/Coomer here. The Easylist list is only responsible for the issues with authenticating. This is specifically the line on https://github.com/easylist/easylist/blob/dffb31c609c6962bd081a16480d78ebe2555208d/easyprivacy/easyprivacy_specific_uBO.txt#L37 

Which causes issues with the new authentication system, you can resolve this with the following custom filter:

@@||kemono.su/api/v1/authentication/login$xhr,1p

DO NOT REPORT ANY 500 ERRORS IN HERE. The developers at Kemono ARE AWARE and are resolving these issues now.

**Comment by WebDumy** [comment]
So that was a lie

**Comment by shinji257** [comment]
Nah it is just people assumed the heading at the top was for all issues.  There are some parts that broke due to a rule in the filter set.

There is a note about it in their importer.  I just added this to my set to fix that issue.

`@@||kemono.su/*$xhr,1p`

**Comment by lunatic-gh** [comment]
> They said on their own page, with a yellow banner essentially _'Our page does not work properly with an AdBlocker'_ No wonder they first suspect what the page tells them is an issue. Edit: Spelling

again, those banners exist only because about 90% of reported issues are due to the reporter using an ad-blocker. So the website (in this case kemono) just puts it there in advance, because they expect it to be true in most cases.

You would be surprised about how many people use totally broken adblockers that nobody even remotely knows about...
