### ISSUE TITLE
adblock is off yet the site doesnt display artists nor show any search results and keeps telling me to turn off adblock while displaying a page full of ads.

### ISSUE THREAD

**Issue by kirubel47** [easylist/easylist#20727]
#### Your settings:

- OS/version: 
- Browser/version: 
- Ad block extension/version:

**Comment by 1434015845** [comment]
now showing the favorite list and the adblock notification at the same time,try to clean your cookies?

**Comment by ironman5-tech** [comment]
https://kemono.su/
win10
chrome and edge

Route:
/patreon/user/93991672
Name:
Error
Message:
API is in maintenance or not available.
Request:
URL:
https://kemono.su/api/v1/patreon/user/93991672/posts-legacy
Method:
GET
Response:
URL:
https://kemono.su/api/v1/patreon/user/93991672/posts-legacy
Is okay?:
No
Status:
503
Status text:
Type:
basic

![image](https://github.com/user-attachments/assets/9ee33c41-2120-404f-bd62-c1cf292b63bd)

**Comment by ironman5-tech** [comment]
> #### List the website(s) you're having issues with:
> #### What happens?
> #### Screenshot(s)
> #### Filter lists you're using:
> #### Your settings:
> * OS/version:
> * Browser/version:
> * Ad block extension/version:
> 
> #### Other details:

https://kemono.su/

win10

chrome and edge

Route:
/patreon/user/93991672
Name:
Error
Message:
API is in maintenance or not available.
Request:
URL:
https://kemono.su/api/v1/patreon/user/93991672/posts-legacy
Method:
GET
Response:
URL:
https://kemono.su/api/v1/patreon/user/93991672/posts-legacy
Is okay?:
No
Status:
503
Status text:
Type:
basic

![image](https://github.com/user-attachments/assets/2c4193e9-c066-40c7-b779-0cd60c84da42)

**Comment by trucdanh112** [comment]
adblock is off yet the site doesnt display artists nor show any search results and keeps telling me to turn off adblock while displaying a page full of ads.

**Comment by trucdanh112** [comment]
adblock is off yet the site doesnt display artists nor show any search results and keeps telling me to turn off adblock while displaying a page full of ads.

**Comment by Eyad-K** [comment]
> adblock is off yet the site doesnt display artists nor show any search results and keeps telling me to turn off adblock while displaying a page full of ads.

same

**Comment by valdearg** [comment]
Please do not report issues with Kemono/Coomer here. The Easylist list is only responsible for the issues with authenticating. This is specifically the line on https://github.com/easylist/easylist/blob/dffb31c609c6962bd081a16480d78ebe2555208d/easyprivacy/easyprivacy_specific_uBO.txt#L37 

Which causes issues with the new authentication system, you can resolve this with the following custom filter:

@@||kemono.su/api/v1/authentication/login$xhr,1p

DO NOT REPORT ANY 500 ERRORS IN HERE. The developers at Kemono ARE AWARE and are resolving these issues now.
