### ISSUE TITLE
Cant do a search

### ISSUE THREAD

**Issue by zizfiq** [easylist/easylist#20726]
Kemono
List the website(s) you're having issues with:
https://kemono.su/artists

NSFW
What happens?
On the artists tab you can't do a search. 

Screenshot(s)
![Screenshot_2024-11-26-22-45-56-957_com.brave.browser-edit.jpg](https://github.com/user-attachments/assets/ad63b2ca-c6e9-4ea5-ae97-1333df7bd8ed)

Filter lists you're using:
None

Your settings:
None

Browser/version: Brave/1.73.89

**Comment by ADOFalah** [comment]
same

**Comment by CynicalPlatapus** [comment]
Most likely a site issue, it's still not working on browsers with no adblockers installed, it briefly loaded for a few minutes but then stopped again

**Comment by valdearg** [comment]
Please do not report issues with Kemono/Coomer here. The Easylist list is only responsible for the issues with authenticating. This is specifically the line on https://github.com/easylist/easylist/blob/dffb31c609c6962bd081a16480d78ebe2555208d/easyprivacy/easyprivacy_specific_uBO.txt#L37 

Which causes issues with the new authentication system, you can resolve this with the following custom filter:

@@||kemono.su/api/v1/authentication/login$xhr,1p

DO NOT REPORT ANY 500 ERRORS IN HERE. The developers at Kemono ARE AWARE and are resolving these issues now.
