### ISSUE TITLE
Failed to fetch from API due to server error.

### ISSUE THREAD

**Issue by ludreficur** [easylist/easylist#20733]
List the website(s) you're having issues with: https://kemono.su/patreon/user/11321390
What happens?
Failed to fetch from API due to server error.
Screenshot(s)
![Screenshot_1](https://github.com/user-attachments/assets/cb12d111-ae34-41de-9026-ed46bcc69255)
Filter lists you're using: No
Your settings: No
OS/version: Windows 10 22H2
Browser/version: Opera 114.0.5282.222
Ad block extension/version: Ad Guard 5.0.171
Other details:

**Comment by valdearg** [comment]
Please do not report issues with Kemono/Coomer here. The Easylist list is only responsible for the issues with authenticating. This is specifically the line on https://github.com/easylist/easylist/blob/dffb31c609c6962bd081a16480d78ebe2555208d/easyprivacy/easyprivacy_specific_uBO.txt#L37 

Which causes issues with the new authentication system, you can resolve this with the following custom filter:

@@||kemono.su/api/v1/authentication/login$xhr,1p

DO NOT REPORT ANY 500 ERRORS IN HERE. The developers at Kemono ARE AWARE and are resolving these issues now. 

Please close this issue to not cause any further issues with the Easylist team.
