### ISSUE TITLE
Unable to search

### ISSUE THREAD

**Issue by Oscar0901** [easylist/easylist#20734]
#### Screenshot(s) 

see details

#### Your settings:

- OS/version:  Android 
- Browser/version: Brave 
- Ad block extension/version: NONE

#### Other details:

Unable to search

Nothing is on, yet fail to load artists.
It's said to turn off the adblock.
![Screenshot_20241127_000755_com brave browser](https://github.com/user-attachments/assets/28be016e-f20d-4562-afd9-dd32772d008a)

**Comment by valdearg** [comment]
Please do not report issues with Kemono/Coomer here. The Easylist list is only responsible for the issues with authenticating. This is specifically the line on https://github.com/easylist/easylist/blob/dffb31c609c6962bd081a16480d78ebe2555208d/easyprivacy/easyprivacy_specific_uBO.txt#L37 

Which causes issues with the new authentication system, you can resolve this with the following custom filter:

@@||kemono.su/api/v1/authentication/login$xhr,1p

DO NOT REPORT ANY 500 ERRORS IN HERE. The developers at Kemono ARE AWARE and are resolving these issues now. 

Please close this issue to not cause any further issues with the Easylist team.
