### ISSUE TITLE
I can't load the artist

### ISSUE THREAD

**Issue by Psa7845** [easylist/easylist#20736]
![Screenshot_20241127_015227_Chrome](https://github.com/user-attachments/assets/8470254b-2d61-4588-bbac-ed7f8b163fd6)

**Comment by KenSakuraba** [comment]
Yeah, me neither

**Comment by gitmage** [comment]
I'm having the same issue

**Comment by ntk0618** [comment]
私も同じです

**Comment by Yuki2718** [comment]
Update filters
