### ISSUE TITLE
sentry still blocked

### ISSUE THREAD

**Issue by gustawdaniel** [easylist/easylist#20767]
Please reconsider issue: https://github.com/easylist/easylist/issues/6963

Or at least provide option that allow to unblock error trackers.

I need all filters you created but not this one. Can you provide instruction, how to use your plugin but without blocking sentry?

**Comment by gustawdaniel** [comment]
I found that in "My rules" i have to add line

```
* o4504655637577728.ingest.sentry.io * allow
```

on the rights, but imo sentry should not be blocked by default.

**Comment by jordansworld** [comment]
i agree bug trackers should not be blocked. but thats not my choice its the maintainers of easylist/easyprivacy. all you can do is whitelist it on yout own. add @@||sentry.io^$important and it will never be blocked again

**Comment by Khrin** [comment]
@gustawdaniel feel free to disable your adblocker. the filter will remain in place.
