### ISSUE TITLE
filhub.gr newsletter notice

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [easylist/easylist#20863]
#### List the website(s) you're having issues with:
https://filhub.gr/

#### What happens?
Newsletter popup

#### Screenshot(s) 
![Screenshot 2024-12-19 at 07-16-08 Καλώς ήρθατε στον κόσμο του Filhub!](https://github.com/user-attachments/assets/d618b4f1-f968-4305-9ec1-da8fcdff2aa0)

#### Filter lists you're using:
All filters offered by uBO + Greek AdBlock Filter

#### Your settings:

- OS/version: Windows 11 23h2
- Browser/version: Mozilla Firefox 133.0.3
- Ad block extension/version: uBlock Origin 1.61.2

#### Other details:
Suggested filter:
filhub.gr##+js(abort-on-property-read, pum_popups)

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/9cc26f5f3b3be020b71252a11b0c07cd68d03f53
