### ISSUE TITLE
https://poe2db.tw/us/

### ISSUE THREAD

**Issue by koeliga** [easylist/easylist#20915]
#### List the website(s) you're having issues with:

Home page has ad
`https://poe2db.tw/us/`

#### What happens?

Visit home page see ad

![image](https://github.com/user-attachments/assets/fbb1cfbd-b0cd-4d0c-9a88-e320c52f1ee6)

**Comment by Yuki2718** [comment]
Fixed by https://github.com/easylist/easylist/commit/bfbd753fe1b0a8d47a6ed9deb70ccae8ac42ed7c
