### ISSUE TITLE
Adds Displaying on SpanishDict.com and RockingSoccer.com

### ISSUE THREAD

**Issue by AlphaT3ch** [easylist/easylist#21]
Adds are still displayed.
This code effectively blocks the ads
```spanishdict.com##div[class^="ad"]
spanishdict.com##div[class^="whitelist"]
spanishdict.com##div[data-target^="ad"]
rockingsoccer.com##h3[class="pwadh"]```

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/7eca2dc46c586b3c3ea7d883a16d2d8577425c2e 

Not seeing any ads on spanishdict.com.

**Comment by AlphaT3ch** [comment]
@monzta 

![IMG](http://i.imgur.com/G5wqHnF.png)
![IMG](http://i.imgur.com/A0qNYPq.png)

**Comment by monzta** [comment]
@AlphaT3ch Do you have [Acceptable Ads](https://adblockplus.org/acceptable-ads) enabled?
