### ISSUE TITLE
ad.atown.jp

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#210]
https://ad.atown.jp/adserver/jsp/affitown/affitown_top.jsp

Easylist breaks page layout

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/afedcfd383a879be6cf511081203ecfcef29eb82

**Comment by terrorist96** [comment]
Thanks. You forgot to close. =)

**Comment by monzta** [comment]
True, thanks!
