### ISSUE TITLE
toledoblade.com easylist false positive - doubleclick

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#211]
http://www.toledoblade.com/State/2016/11/30/Calls-renewed-for-concealed-carry-on-campuses-after-Ohio-State-attack.html

Easylist breaks slideshow image at top.
`@@||securepubads.g.doubleclick.net/gpt/pubads_impl_105.js?v=105`

**Comment by monzta** [comment]
Seems the issue no longer occurs.
