### ISSUE TITLE
http://www.patheos.com/ slideshow broken by EasyList

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#212]
http://www.patheos.com/

EasyList breaks slideshow image.
`@@||ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js`
@monzta

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/e496b6a48b9da6c54392400ec1c1a340f2e0a1e4
