### ISSUE TITLE
VG.no - Unclickable article links (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#2130]
### Affected site:
`https://www.vg.no/`

### Issue:
Some native articles can't be opened from the front page, by the method of left-clicking on them.

### Example:
Not that easy to post, since the articles change all the time.

### Problem filter:
EasyPrivacy

### Problem rule:
`||schibsted.com/autoTracker`

### Possible fix:
`@@||schibsted.com/autoTracker$domain=vg.no`

### Note:
Obviously, this will allow some cross-tracking.
But I guess that it doesn't really qualify as "third-party" tracking, since VG is owned by the Schibsted Media Group.

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by ryanbr** [comment]
https://jssdk.pulse.schibsted.com/autoTrackerVg.with-engage.min.js is full of tracking.

**Comment by THEtomaso** [comment]
We're aware of this.
But read what I wrote in the first post, under "**Note**".
