### ISSUE TITLE
Domain rfksrv.com blocked as a tracking server, but is part of an commerce platform

### ISSUE THREAD

**Issue by KevinRailsback-Reflektion** [easylist/easylist#2133]
https://github.com/easylist/easylist/blob/70d44bd53f8d1c0a2a57deb67fbf471156923dbf/easyprivacy/easyprivacy_trackingservers.txt#L1720

`: easyprivacy$ git blame easyprivacy_trackingservers.txt | grep rfksrv.com
ecc69fff76f (Khrin    2018-04-06 03:37:15 +0200 1711) ||rfksrv.com^$third-party
: easyprivacy$ git log ecc69fff76f
commit ecc69fff76ff063f656768e0be556e4774cf2ae4
Author: Khrin <khrin.vark@gmail.com>
Date:   Fri Apr 6 03:37:15 2018 +0200

    A: https://www.bloomingdales.com/
`
One of our customers noticed that our service domain, rfksrv.com, was being blocked in his browser, which impacted the functionality on their website.  I see in the PR where this domain was added to the EasyPrivacy list that it was flagged as part of the Bloomingdales.com website.

We provide Search and Recommendation for their site and many other ecommerce platforms, and our service is hosted in this domain.

What is the process for having the inclusion on this list reviewed (and hopefully removed)?  We are working on a better solution where our services are hosted within the customer's domain itself, but that is not yet completed.

Thanks,

Kevin Railsback
Senior Director, Security & Technical Operations
Reflektion, Inc.

**Comment by ryanbr** [comment]
Its tracking.  looking at the specific javasctipt, "geo:" has my locoation, ip, country. I expect things like this to be blocked in Easyprivacy.
