### ISSUE TITLE
Takealot.com broadly blocked, can this please be rectified

### ISSUE THREAD

**Issue by richardwooding** [easylist/easylist#2152]
For some context Takealot.com is South Africa's largest e-commerce platform.

In this commit:
https://github.com/easylist/easylist/commit/861d6e21c9438cfed32b363c35da42b4eb6a8610#diff-99072d56e3758452bd7b56578fcdd5ac

Our RESTful API was blocked very broadly rendering our site unusable for legitimate users, e.g. searching, viewing, adding productss, and checking out.

We do have a PR prepared for you:
https://github.com/easylist/easylist/pull/2151

We are happy to investigate and address any concerns, in the interim can you please remove us from the list as it is impacting a lot of legitimate customers.

I refer to the following https://www.takealot.com/help/terms-and-conditions and our about https://www.takealot.com/about/who-we-are

**Comment by Khrin** [comment]
I apologize for the issue. I hope that the @ryanbr  fix (https://github.com/easylist/easylist/commit/0f3122ca2874cdbc986797565b4e5e0a97a92cdd) is enough...
