### ISSUE TITLE
domain img.lifeselector.com blocked (^$third-party rule incorrectly used)

### ISSUE THREAD

**Issue by csabyka** [easylist/easylist#2169]
Hey
we're developing an interactive adult game and offering whitelabel solution for our partners.

An example whitelabel for example (NSFW):

http://idesires.com/

For a few days our white labels are not displaying correctly because of the ^$third-party rule.
It seems on these white labels the https://img.lifeselector.com requests are blocked.
This is not an advertising network. 

Could you remove us?

**Comment by ryanbr** [comment]
fixed
