### ISSUE TITLE
Wikia.com - Blocked videos (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#2183]
### Affected site:
`http://www.wikia.com/`

### Issue:
Videos are blocked.

### Example:
`http://fandom.wikia.com/video/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
EasyList

### Problem rule:
`||wikia.com^$csp=script-src 'self' * 'unsafe-inline' 'unsafe-eval'`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by bogachenko** [comment]
I confirm

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/0265dca7fbae79db520c843ed05ef6faa44ee689  may help, do test.

**Comment by THEtomaso** [comment]
No, the new rule also blocks the videos.

**Comment by ryanbr** [comment]
I don't think you understand how $csp works.

**Comment by THEtomaso** [comment]
@lassekongo83:

Sorry for calling you out on non-Swedish related stuff, but would you mind taking a look at this?

**Comment by THEtomaso** [comment]
Thanks, lassekongo83.
I can confirm that your rule works! :)

@ryanbr:
Can you please replace the rule in EasyList, with the one that lassekongo83 has provided in the post above?
