### ISSUE TITLE
bixel.io tracking blocked

### ISSUE THREAD

**Issue by Bbouley** [easylist/easylist#2192]
bixel.io

### List the website(s) you're having issues:

```
https://bb.bixel.io
```

### What happens?

We have a service that allows users to send video through email. On 26th Oct 2018 we began to receive reports that the links we embedded into our users emails were being blocked from being opened, and customers could no longer view the videos they were being sent if they had an adblocker using easylist turned on. The expected behaviour is that clicking the link in the email opens a new chrome tab with the video in it. Now the tab flashes open and is then shut. 
Our video urls contain `/track/click` as part of their url, as we report back to senders when their video has been viewed.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: MacOS High Sierra 10.13.6
- Browser/version: Google Chrome  69.0.3497.100
- Adblock Extension/version: AdBlock 3.34.0

### Other details:

`@@|*/track/click/*$popup` set as a filter rule seems to prevent this behaviour. Is it possible to whitelist our site with this specific rule?

**Comment by smed79** [comment]
https://github.com/easylist/easylist/commit/2040db96d6ad1a761a430901c54312a2912559e7
