### ISSUE TITLE
http://www.thedailysheeple.com/ unblocked ad

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#223]
`http://www.thedailysheeple.com/`

Gas mask ad at the top

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/f54df9a835b227f664ebc2637125e5ee46372332

**Comment by terrorist96** [comment]
@monzta There is also FEATURED PARTNER/SPONSORED CONTENT articles on the homepage.

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/a4c0af1427330fc3ab77b5aa909a774881f9deda
