### ISSUE TITLE
m.xhamster.com download ads NSFW

### ISSUE THREAD

**Issue by ZaphodBeebblebrox** [easylist/easylist#2231]
### List the website(s) you're having issues:
 `https://m.xhamster.com/videos/deutsche-domina-fistet-typen-hart-in-arsch-mit-dirty-talk-10427825`

### What happens?
 On mobile, when you click the download button, a modal appears that asks you to download aloha browser

### List Subscriptions you're using:
uBlock lists + Easylist + EasyPrivacy + Peter Lowe's Hosts

### Your settings

- OS/version: Windows
- Browser/version: Firefox 63.0
- Adblock Extension/version: uBlock Origin 1.17.2

### Other details:
Perhaps `m.xhamster.com##.aloha-download-popup > .popup`

**Comment by Khrin** [comment]
This filter should solve the problem.
