### ISSUE TITLE
Episerver Find broken

### ISSUE THREAD

**Issue by StefanoChiodino** [easylist/easylist#2239]
### List the website(s) you're having issues:

Any website using Episerver CMS with Find plugin

Unfortunately I can't provide URLs for this, as you would need access to a backend. I'm not even sure how/if I would be able to run a demo site for you.

### What happens?

GET https://az416426.vo.msecnd.net/scripts/a/ai.0.js net::ERR_BLOCKED_BY_CLIENT

This make the Find plugin not load, and the page redirects to an error page for find.

![image](https://user-images.githubusercontent.com/1428893/48125402-79a9f580-e276-11e8-803d-a8b025522891.png)

### List Subscriptions you're using:

This is specifically easylist, I'm running uBlock.

### Your settings

- OS/version: Win 10
- Browser/version: Chrome 70
- Adblock Extension/version: uBlock Origin v1.17.0

### Other details:

This is specifically the rule blocking the request, that is in turn causing the error.
https://github.com/easylist/easylist/blob/c00c00e98911680b2dc8c2b300d42e47049fa326/easyprivacy/easyprivacy_thirdparty.txt#L1207

**Comment by ryanbr** [comment]
Its blocked because of the tracking/telemetry. Use another script.
