### ISSUE TITLE
TheVerge.com - Blocked cookie consent = blocked videos (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#2256]
### Affected site:
`https://www.theverge.com/`

### Issue:
Cookie consent can't be accepted, so embeded videos are blocked.

### Example:
`https://www.theverge.com/2018/8/21/17761424/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
EasyPrivacy

### Problem rules:
```
||voxmedia.com/needle?
||voxmedia.com/pickup.js
```

### Possible fix:
```
@@||voxmedia.com/needle?$domain=theverge.com
@@||voxmedia.com/pickup.js$domain=theverge.com
```

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by Khrin** [comment]
Issue is still present?

**Comment by THEtomaso** [comment]
> Issue is still present?

Nope, this doesn't seem to be an issue anymore.
At least not from my end.
The cookie consent appears, it can be accepted, and the videos play just fine afterwards.

@krystian3w:
How about from your location?

**Comment by krystian3w** [comment]
Works fine, I no need expecitons `/needle` and `/pickup.js`.

**Comment by krystian3w** [comment]
I cannot accept cookies without exception added to `uBlock filters – Unbreak​​​​​​​​​`.

@Khrin  For my we need this still exceptions.

@THEtomaso  You disabled `uBlock filters – Unbreak​​​​​​​​​` or tested with Adblock Plus?

**Comment by THEtomaso** [comment]
Of course, I tested with '**EasyPrivacy**' only, and an empty cache.
This GDPR stuff can be really weird sometimes.

**Comment by krystian3w** [comment]
For my side - video does not require an exception.

I cannot accept cookies without exception added to `uBlock filters – Unbreak​​​​​​​​​`.

@Khrin  That it would close shortly after accepting and not refresh the page.

**Comment by THEtomaso** [comment]
I restested this just now, and this time, the exceptions were needed!
There could be some type of timing issue involved.

**Comment by krystian3w** [comment]
For 4-5 attempts I only picked up the problem that the cookie itself does not refresh the page after the acceptance so that the video will load.

**Comment by THEtomaso** [comment]
@Khrin:
It seems that in order for this problem to be properly fixed, you indeed need to add the exceptions that I pointed out in the first post.
