### ISSUE TITLE
Advertising in https://yanex.ru

### ISSUE THREAD

**Issue by bogachenko** [easylist/easylist#2282]
Advertising in https://yanex.ru
![2](https://user-images.githubusercontent.com/8535285/48383198-b180c500-e6dc-11e8-864c-9841f8ea4de9.png)
![default](https://user-images.githubusercontent.com/8535285/48383200-b180c500-e6dc-11e8-9128-153bc5a11775.png)

**Comment by smed79** [comment]
report here https://forums.lanik.us/viewforum.php?f=102

**Comment by bogachenko** [comment]
good help. rather "good"

**Comment by smed79** [comment]
No ads here, (Adblock Plus + Firefox or Chrome)

![yandex.ru](https://user-images.githubusercontent.com/1873139/48595361-9e782a00-e954-11e8-9f22-d976f3b8be83.png)

**Comment by bogachenko** [comment]
i use ublock :cry:

**Comment by smed79** [comment]
@okiehsch Can you reproduce?

**Comment by okiehsch** [comment]
No.

**Comment by bogachenko** [comment]
:disappointed:
