### ISSUE TITLE
fmovies.se unblocked ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#229]
`http://fmovies.se/film/life.0n95/z1z4zp`

unblocked ads

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/a3c7dbdbba523676600b52b42f437bbb14907d05

**Comment by terrorist96** [comment]
@monzta Thanks! However, there's also an unblocked popup ad when you try to click the play button (the second play button, not the first one)
