### ISSUE TITLE
pixel.facebook.com

### ISSUE THREAD

**Issue by mcartoixa** [easylist/easylist#2296]
We are using Workplace (by facebook), and it appears that blocking `pixel.facebook.com` prevents any message to show for some users (which defeats the purpose of the platform). This must be due to an update that is being rolled out by facebook...

### List the website(s) you're having issues:
`https://*.facebook.com/`

Sorry, this is a corporate site. but I suspect it will happen on other facebook sites sooner rather than later...

### What happens?
The feed is empty : 
![2018-11-15 17_06_44-air indemnite - workplace](https://user-images.githubusercontent.com/1251985/48567783-37c82180-e8fe-11e8-83d9-54ae5537cef9.png)

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 70
- Adblock Extension/version: uBlock Origin

### Other details:

In the console log, only `pixel.facebook.com` calls are blocked. Whitelisting `facebook.com` solves the problem.

**Comment by ryanbr** [comment]
Given no issues i've seen, or else been reported by other users. I'd say its probably unlikely an issue.

Pretty sure if broke facebook, we'd hear about it.
