### ISSUE TITLE
All Wix.com websites get blocked

### ISSUE THREAD

**Issue by Uricorn** [easylist/easylist#230]
Opening an issue since it's likely you are too swamped to see my comment.

`parastorage.com^*/rssButton.min.js$domain=cupidsthemovie.com|ilovesmj.com`
Please apply this whitelist to all websites instead of just cupidsthemovie.com and ilovesmj.com or remove the filter.

Currently that filter is blocking all of the millions of websites built with Wix.com to load. (Wix.com owns the parastorage.com domain)

Here is an example: http://www.ageofbeard.com

See commit here: https://github.com/easylist/easylist/commit/7f16b3c7ed546ee2067feaa3a2a8e49a23c913dd

**Comment by monzta** [comment]
Looks like this has been resolved.
