### ISSUE TITLE
GettyImages.* - A couple of problems (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#2318]
### Affected sites:
`https://www.gettyimages.*`

### Issues:
* Modal overlay
* Broken image expand function

### Problem filter:
* EasyPrivacy

### Problem rule:
`/tracking/getty/*`

### How to reproduce:
**Issue A**: Modal overlay:
1) Go to this page: `https://www.gettyimages.com/photos/winona-ryder-october-15-1999/`
2) Click on the search button (in the search bar).
Effect: A modal overlay covers the search results.

**Issue B**: Broken image expand function:
1) Go to this page: `https://www.gettyimages.com/detail/news-photo/actress-winona-ryder-poses-for-a-portrait-shoot-on-october-news-photo/102888803/`
2) Put the mouse cursor over the image (to make the expand button appear).
3) Click on the expand button.
Effect: The expand button doesn't work.

### Screenshots:
Not needed, as the problems should be obvious when following the instructions above.

### Possible fixes:
**Alternative 1**: Delete the problem rule (this will probably allow some tracking).

**Alternative 2**: Ignore the problem with the image expand button (the images can be expanded by right-clicking on them, and choosing "View Image" instead)
..and simply block the modal overlay, using the following rule:
`gettyimages.*##.gallery-spinner-overlay`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.2.1 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by Khrin** [comment]
Thank you, I've removed the offending filter.
