### ISSUE TITLE
https://martinfowler.com/articles/asyncJS.html

### ISSUE THREAD

**Issue by code-sur** [easylist/easylist#2321]
### List the website(s) you're having issues:
`https://martinfowler.com/articles/asyncJS.html`

### What happens?
Styles are being blocked.

Just enter the URL above and you'll see a site without styles applied.

### List Subscriptions you're using:

- Ads
  - EasyList​
- Privacy
  - EasyPrivacy​
- Malware domains
  - Malware Domain List
  - Malware domains​
- Multipurpose
  - Peter Lowe’s Ad and tracking server list​

### Your settings

- OS/version:
  - Linux Mint 19
- Browser/version:
  - Firefox Quantum 63.0 (64bit)
  - Google Chrome 70.0.3538.110 (Official Build) (64-bit)
- Adblock Extension/version:
  - uBlock Origin v1.17.2 (Firefox)
  - AdBlock 3.34.0 (Chrome)

### Other details:

The resource being blocked is `https://martinfowler.com/articles/asyncJS.css` because matches with rule `/asyncjs.$domain=~asyncjs.com` from EasyList

Thanks!

**Comment by ryanbr** [comment]
Just rename the filename, rather creating a one-off for one webpage.

**Comment by code-sur** [comment]
I agree that it's easier to rename that file than change the rule but I also think that `/asyncjs.$domain=~asyncjs.com` is being too gready.

Does it makes sense to filter out things like `asyncjs.css`, `asyncjs.html` or `asyncjs.whatever`?

Wouldn't be more appropriate to only filter out `asyncjs.js`??

Thanks for doings this. Great work!

**Comment by Khrin** [comment]
I don't see the necessity to modify our filter.

**Comment by ryanbr** [comment]
asyncjs.com was a domain excemption. not a filename. allows a user who visits the entire domain its not completely broken

**Comment by THEtomaso** [comment]
I just encountered this issue too.
Don't think that it would be that much trouble to simply change the existing rule into this:
`/asyncjs.$domain=~asyncjs.com|~martinfowler.com`

**Comment by Khrin** [comment]
Again, I don't see why we should modify our filter.

**Comment by THEtomaso** [comment]
@okiehsch:
Could you add `@@||martinfowler.com/articles/asyncJS.css` to '**uBlock filters - Unbreak**'?
