### ISSUE TITLE
exception for userengage.com/* and user.com/*

### ISSUE THREAD

**Issue by KarolMilewski** [easylist/easylist#2326]
https://easylist-downloads.adblockplus.org/easyprivacy.txt

rules `/api/ping/*` block our widget.
Make an exception for `user.com/*` and `userengage.com/*`.

**Comment by Khrin** [comment]
Exactly where is causing false positives?

**Comment by KarolMilewski** [comment]
@Khrin If our client has our widget in the web, uBlock blocking the connection with our API (/api/ping/*) causes errors to appear in the console. You can see this problem with our web. 
This problem is terrible, our clients have a problem with contact with they support.
uBlock use this list in default in filters.

**Comment by ryanbr** [comment]
Workable example?

**Comment by KarolMilewski** [comment]
go to user.com with enable uBlock and look on the console.
