### ISSUE TITLE
black friday popup on flightradar24

### ISSUE THREAD

**Issue by theel0ja** [easylist/easylist#2327]
### List the website(s) you're having issues:
`https://www.flightradar24.com/`

### What happens?
black friday popup

### List Subscriptions you're using:
easylist
fanboy annoyance

### Your settings

- OS/version: macos
- Browser/version: ff
- Adblock Extension/version: ubo

**Comment by THEtomaso** [comment]
`flightradar24.com##[id^="black-friday-"]`

**Comment by Khrin** [comment]
I'm sorry, I guess that I'm too late...

**Comment by THEtomaso** [comment]
The rule that I posted in my previous post worked just fine, without any ill effects.
It blocked both the popup and the modal backdrop, which both had an ID starting with "**black-friday-2018**".
Most likely, they'll simply put a "**2019**" at the end next year, in which case, my blocking rule will still catch it! :)
