### ISSUE TITLE
latimes.com anti-adblock

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#233]
`http://www.latimes.com/local/lanow/la-me-mt-baldy-hiker-20161129-story.html`

Advertising revenue helps support our journalism
To read today's stories, please turn off your ad blocker or subscribe

**Comment by Khrin** [comment]
I guess this has been fixed with https://github.com/easylist/easylist/commit/329c981b80f69e77225ab1eaecee34a24f90ba20
