### ISSUE TITLE
buliba.pl [EasyList] [Breakage - page won't load]

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#2340]
As per https://github.com/MajkiIT/polish-ads-filter/issues/10259

### List the website(s) you're having issues:

`https://www.buliba.pl/`

### What happens?

Breakage - infinite page loading, never loads.

### List Subscriptions you're using:

uBO default

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- Adblock Extension/version: uBO 1.17.2

### Other details:

<details not-open>
<summary>Screenshoot 1 - page infinite loading</summary>

![](https://user-images.githubusercontent.com/44813765/49037145-c7e94f00-f1b9-11e8-84dc-b5ac86c3cb18.png)

</details>
.

<details not-open>
<summary>Screenshoot 2 - with the fix applied</summary>

![](https://user-images.githubusercontent.com/44813765/49037223-f2d3a300-f1b9-11e8-8534-2402145a8eb2.png)

</details>
.

Problem rule: `/overlayad.` which blocks `https://www.buliba.pl/css/overlayad.css`
Example fix: `@@||www.buliba.pl/css/overlayad.css$stylesheet,domain=www.buliba.pl`

**Comment by Khrin** [comment]
Page loads fine for me, does still happen for you?

**Comment by kulfoon** [comment]
It loads fine in Opera now but not in Firefox, does the page loads fine for you in Firefox?

**Comment by Khrin** [comment]
Yes, I'm using Firefox. Ok then, anyway I've added this exception, which should solve the issue.
