### ISSUE TITLE
icy-veins.com / ads

### ISSUE THREAD

**Issue by cherdho** [easylist/easylist#2350]
### List the website(s) you're having issues:

`https://www.icy-veins.com/`

### What happens?

Don't understand why I see so many advertising while abp is update and activated

### List Subscriptions you're using:

ABP default

### Your settings

- OS/version: macos mojave
- Browser/version: chrome
- Adblock Extension/version: adblock plus 3.4.1

**Comment by THEtomaso** [comment]
Does this take care of the remaining "advertising" elements that you refered to?:
```
icy-veins.com##.podcastbanner
icy-veins.com###premium_information
asterianalytics.com$domain=icy-veins.com
```

**Comment by ryanbr** [comment]
Closing, no ads seen.
