### ISSUE TITLE
anti-adblock and unblocked ad on hollaforums.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#237]
`http://hollaforums.com/`

Forum blocked by pop up instructing you to disable ABP. Also, unblocked V2 ad.

Side note: the anti-adblock message can be bypassed if you load the https version of the site.

**Comment by felix-22** [comment]
@ryanbr ad placeholder

![k](https://user-images.githubusercontent.com/75935068/140516844-2de864f0-399c-4d8c-b06c-3876369617a6.png)
