### ISSUE TITLE
thedailybeast.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#2373]
### List the website(s) you're having issues:

`https://www.thedailybeast.com/judge-napolitano-patiently-explains-michael-cohens-plea-to-dismissive-fox-news-hosts
`
### What happens?

Unblocked sponsored content at end of article.

### List Subscriptions you're using:

uBlock Origin default

### Your settings

- OS/version: Win7
- Browser/version: Chrome 70
- Adblock Extension/version: uBO 1.17.0

### Other details:

![image](https://user-images.githubusercontent.com/12802056/49332650-e024e980-f57e-11e8-8b4b-40a72620d73b.png)

`||embed.actionbutton.co/widget/widget-iframe.html`

**Comment by smed79** [comment]
Source : `https://actionbutton.org/`

add
```
||actionbutton.co^$third-party
```
