### ISSUE TITLE
EasyPrivacy breaks several buttons on gofundme.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#238]
https://www.gofundme.com/nepal-youth-foundation

"+Read More", "Recent Donations", "+See More" etc buttons are broken by EasyPrivacy.

`@@||funds.gofundme.com/js/5.0/components/visitorCookie.js`

**Comment by monzta** [comment]
Works fine for me. Can you confirm?

**Comment by terrorist96** [comment]
Confirmed.
