### ISSUE TITLE
RedTube.com: Site completely broken

### ISSUE THREAD

**Issue by RedTuber** [easylist/easylist#2414]
### List the website(s) you're having issues:

https://www.redtube.com - all pages and subdomains

### What happens?

Page is completely broken and shows no content

### List Subscriptions you're using:

easylist

### Your settings

- OS/version: ALL
- Browser/version: ALL
- Adblock Extension/version:  Ublock, Adblock AdblockPlus

### Other details:

Unable to view any content.  Only shows header nav and footer nav.
NSFW content

**Comment by ryanbr** [comment]
Stop sabotaging your own site by breaking the site if someone blocks; media.trafficjunky.net/js/holiday-promo.js

https://github.com/easylist/easylist/commit/43394783993d3346524c2bdc909a2144113b74dd

I won't whitelist trafficjunky.
