### ISSUE TITLE
thedailybeast.com using piano.io tracker via tinypass.com for newsletter subscribe box

### ISSUE THREAD

**Issue by yourduskquibbles** [easylist/easylist#2415]
### List the website(s) you're having issues:

`https://www.thedailybeast.com/trump-attacks-mueller-team-conflicts-of-interest-as-manafort-cohen-filings-loom`

### What happens?

Scroll down to the bottom of the article and load a new article (should load automatically with the site's infitinite scroll) then scroll back up in the page. A newslettter box comes floating in. This is connected to ad/tracking network piano

![dailybeast](https://user-images.githubusercontent.com/22258847/49672730-17414200-fa3a-11e8-82c9-34bca3d55076.PNG)

### List Subscriptions you're using:

default uBO lists on test profile

### Versions

- Browser/version: Chrome Version 71.0.3578.80 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin 1.17.5b1 (Latest Dev Build)
- uBlock Origin Extra 2.79

### Settings

- Test profile with default settings and lists.

**Comment by ryanbr** [comment]
Use

**Comment by yourduskquibbles** [comment]
FYI @ryanbr this is still being loaded on thedailybeast.com, think you need to add something like `||cdn.tinypass.com^$script`

**Comment by Khrin** [comment]
That's not possible, because would also block the paywall.
