### ISSUE TITLE
Crucial.com

### ISSUE THREAD

**Issue by injust** [easylist/easylist#2416]
### List the website(s) you're having issues:
`https://www.crucial.com/`

### What happens?
Blank page

### List Subscriptions you're using:
Fanboy's Annoyance List

### Other details:

https://github.com/easylist/easylist/blob/8419d50b4adf9c2025c94800ee730430a444b988/fanboy-addon/fanboy_cookie_general_hide.txt#L7945 is causing the issue.

**Comment by THEtomaso** [comment]
Confirmed, I've filed a new report for you, in the correct issue tracker, here:
https://github.com/ryanbr/fanboy-adblock/issues/788/

**Comment by THEtomaso** [comment]
This issue report can be closed now, as the problem has been fixed:
https://github.com/ryanbr/fanboy-adblock/issues/788#issuecomment-445501818
