### ISSUE TITLE
unblocked ads sun-sentinel.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#242]
`http://www.sun-sentinel.com/`
`http://www.sun-sentinel.com/news/weather/`

Unblocked ads.

**Comment by mapx-** [comment]
```
@@||sun-sentinel.com^$generichide
@@*.ico$domain=sun-sentinel.com
@@*.gif$domain=sun-sentinel.com
@@*.png$domain=sun-sentinel.com
@@*.jpg$domain=sun-sentinel.com
```

**Comment by terrorist96** [comment]
@mapx- still see ads on Chrome with those rules.

**Comment by mapx-** [comment]
working for me, are you sure your other blocking extensions are not interfering ?

**Comment by terrorist96** [comment]
Privacy Badger causes the ads to show; otherwise, your custom filters do work.
Thanks.
