### ISSUE TITLE
Easylist false positive in http://www.cinemark.com.ar/

### ISSUE THREAD

**Issue by AndreaMdq** [easylist/easylist#243]
Easylist is blocking some images in http://www.cinemark.com.ar/

![image](https://cloud.githubusercontent.com/assets/22546652/21941156/2ca2ef10-d9a6-11e6-81ba-6e1af141df83.png)

**Comment by SMed79** [comment]
Are you the site webmaster?

**Comment by AndreaMdq** [comment]
No, I'm not de webmaster but I work for the company. 

We actualize constantly the site (especially this images) and will be more easy for us if you include the exception.

**Comment by mapx-** [comment]
the best solution is to rename the pics
don't use in the names _300x250_

otherwise easylist authors could say easylist is only for english sites and your pics will be still blocked

**Comment by AndreaMdq** [comment]
Ok, thanks for the help!
