### ISSUE TITLE
Comments section not load at consequenceofsound.net

### ISSUE THREAD

**Issue by MDawg957** [easylist/easylist#244]
https://reports.adblockplus.org/67fe423f-15a6-4c9d-8370-91b95ebead53

http://consequenceofsound.net/2017/01/the-13-scariest-cover-songs/

**Comment by SMed79** [comment]
try
`@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=consequenceofsound.net`

**Comment by MDawg957** [comment]
@SMed79 Yeah, that fixes it.  Will it be added to the subscription?

**Comment by SMed79** [comment]
Wait the easylist author see y'r message and decide what to do.

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/d7f8a3b1c0620450f417b5bf3bfa7396c24e0cad
