### ISSUE TITLE
heatmap.*? is too broad and blocks pages

### ISSUE THREAD

**Issue by flying-sheep** [easylist/easylist#2443]
In data science, heatmaps are commonly used for visualization.

I think heatmap.js is already too broad, but blocking any file called [`heatmap.*?`](https://github.com/easylist/easylist/blob/2be9741ad32f779f10ac3ba2179c48eacf1fb6f3/easyprivacy/easyprivacy_general.txt#L1722) definitely is. See

- https://github.com/jupyter/notebook/issues/1957
- https://github.com/hypothesis/h/issues/1236
- https://steamcommunity.com/groups/csgostats-gg/discussions/0/358415103478908372/
- http://old-support.getadblock.com/discussions/problems/93487-highcharts-heat-map-is-blocked-by-adblocker

**Comment by theferrit32** [comment]
I agree that `/heatmap.*?` is much too broad.  I run into this all the time with Jupyter notebooks.  It is a fairly common use case to create heatmaps and files that match that rule.

**Comment by Khrin** [comment]
The filter will not be removed.

**Comment by flying-sheep** [comment]
Why? This is clearly a common URL part for science-based applications.

I ran into it with jupyter and with a data science visualization server.

Please reconsider this. As one of the more techy members of the science community, I might be one of the few who found their way here, but I assure you there’s a lot of people going to be cut by this.

**Comment by theferrit32** [comment]
I strongly disagree with the decision to close this issue.  Blocking any request path that contains `/heatmap.*?` is too broad and can cause inexplicable errors on valid sites.  Having heatmap files is common, especially in data science, computer science, and other science contexts.

**Comment by flying-sheep** [comment]
@Khrin: please reopen, this is clearly an issue in many web frontends for data analysis.

**Comment by Semigradsky** [comment]
@Khrin please reopen

**Comment by flying-sheep** [comment]
@ryanbr @Khrin why is this closed? There was no reason given.

**Comment by ryanbr** [comment]
[Heatmap is a analytics method of tracking the mouse](https://www.google.com/search?q=heatmap+analytics), atkeast one example you list have been fixed by the site.  `https://csgostats.gg/match/6886366` -> `https://csgostats.gg/js/heat-maps.js`   also mixing 2 different filters `/heatmap.js` with `/heatmap.*?` doesn't help your cause.

**Comment by flying-sheep** [comment]
Not exactly: Heatmaps are a really common scientific visualization that is used for many kinds of data, most of them obviously without privacy impact. That it’s used for mouse tracking as well doesn’t change the fact that there’s loads of heatmap components and pages and scripts in the wild that we don’t want to break.

While refining `/heatmap.*?`→`/heatmap.js` wouldn’t help the pages I listed, it would certainly be more sensible. The former also blocks stuff link https://internal-microservice.local/heatmap.png?id=a4d75e

**Comment by ryanbr** [comment]
I've removed one filter, the other heapmap filters others will stay. Also locking this. No further changes

https://github.com/easylist/easylist/commit/da9090bf546b92b1d591766fb66d54a80e98482b
