### ISSUE TITLE
https://hacktivis.me/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#2453]
### List the website(s) you're having issues:

`https://hacktivis.me/`

### What happens?

Unblocked banner ad

### List Subscriptions you're using:

uBO default

### Your settings

- OS/version: Win7
- Browser/version: Chrome 71
- Adblock Extension/version:  uBO 1.17.4

### Other details:

![image](https://user-images.githubusercontent.com/12802056/49893048-86db7680-fe18-11e8-97ab-18fd5b91a216.png)

`||hacktivis.me/images/support_lqdn_728_*.gif$image`
`hacktivis.me##body > header`

**Comment by ariasuni** [comment]
I’m not sure this can be qualified as ad because it doesn’t generate money. It’s a banner for an association the author supports, and that can be considered as content.

**Comment by ariasuni** [comment]
Thanks!

**Comment by Khrin** [comment]
Thanks for what? I haven't delved into more just because the site isn't in English.

**Comment by ariasuni** [comment]
I’m used to thanks people so they know I noticed and am grateful for their work — I know that even bug triaging takes time.
