### ISSUE TITLE
Audio ads served from *.adswizz.com not being blocked

### ISSUE THREAD

**Issue by DavidBuchanan314** [easylist/easylist#248]
This network is used to serve ads on Soundcloud, and probably many other sites. An example URL: `https://delivery-cdn-cf.adswizz.com/thisisglobal_newEnco/ad_0_6d584348d1bd35b037900e25dbc02b5e_fbf4f9ab-228c-44f0-962d-8c446e9632c2.mp3`

This seems to fix it:

```
||adswizz.com
```

There are some existing rules for this domain, but they are too specific, and let through the ads.

**Comment by Khrin** [comment]
Have you heard this advert on a specific page, or you've just randomly encountered this?

**Comment by DavidBuchanan314** [comment]
They play periodically on soundcloud.com, between songs.

**Comment by DavidBuchanan314** [comment]
It would appear that they have a fallback method in place. I'll update this when I've found a reliable blocking method.

**Comment by Khrin** [comment]
Is this still happening again? If possible, through Firefox and Adblock Plus, please can you send us an issue report?
