### ISSUE TITLE
techpowerup.com ads

### ISSUE THREAD

**Issue by theel0ja** [easylist/easylist#2489]
### List the website(s) you're having issues:

```
https://www.techpowerup.com/250624/logitech-options-software-vulnerability-disclosed-users-should-uninstall-until-fix-is-available
```

### What happens?
unblocked ads

### List Subscriptions you're using:
easylist

### Your settings

- OS/version: linux
- Browser/version: ff
- Adblock Extension/version: ubo

**Comment by llacb47** [comment]
Add `techpowerup.com##figure:has(img)` for placeholders, if that's in scope.

**Comment by IanKemp** [comment]
This change breaks techPowerUp!'s forums: https://www.techpowerup.com/forums/threads/latest-adblock-update-breaks-images-on-tpu.258911/
