### ISSUE TITLE
thefreedictionary.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#249]
`http://www.thefreedictionary.com/understudy`

Amazon and grammarly ads

**Comment by mapx-** [comment]
```
@@||thefreedictionary.com^$generichide
thefreedictionary.com##div[style="padding:10px 10px;font-size:1.1rem"]
```

**Comment by terrorist96** [comment]
Should be merged.

**Comment by terrorist96** [comment]
EasyList is now completely blocking definitions on TFD.

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/3d10af1e5a917aa827e64b498c1b8e2266e01412

**Comment by terrorist96** [comment]
@monzta I still see grammarly ads.

**Comment by mapx-** [comment]
Did you update easylist ?

Only for chrome there is still some ugly placeholder, add:
`thefreedictionary.com##[id*=aswift]`

**Comment by terrorist96** [comment]
Ah, I see now. Privacy Badger and Ghostery both trigger the Grammarly ads. Disabling both them will show the ads as being blocked but with the placeholder you mentioned.
