### ISSUE TITLE
ads.bigbom.com

### ISSUE THREAD

**Issue by onimsha** [easylist/easylist#2490]
### List the website(s) you're having issues:

`https://ads.bigbom.com`

### What happens?

My website is a utility for optimizing ads running on platform like Facebook. Currently it's showing a landing page for countdown to release. AdBlock is blocking this domain and it renders a blank page.
### List Subscriptions you're using:

Easylist
### Your settings

- OS/version: Mac OS
- Browser/version: Chrome/70
- Adblock Extension/version: 3.36.0

**Comment by LanikSJ** [comment]
This was fixed in https://github.com/easylist/easylist/pull/2494

**Comment by onimsha** [comment]
Thanks !
