### ISSUE TITLE
cbs.com - blocked videos (EasyList)

### ISSUE THREAD

**Issue by jessekirk** [easylist/easylist#2500]
### List the website(s) you're having issues:

https://www.cbs.com/

### What happens?

Clicking on any video results in the spinning circle trying to play but does not go past trying to load
https://www.cbs.com/shows/happy-together/video/OhPlvKf08feeKxFEIeWbR89uTjsnP_li/happy-together-a-claire-free-lifestyle/

### List Subscriptions you're using:

all out of the box filters:
ublock filters
ublock filters - badware risks
ublock filters - privacy
ublock filters - resource abuse
ublock filters - unbreak
easylist
easyprivacy
fanboy's enhanced tracking list
malware domain list
malware domains
peter lowe's ad and tracking server list

### Your settings

- OS/version: macOS Mojave 10.14.2
- Browser/version: firefox quantum 64.0 (64-bit)
- Adblock Extension/version: ublock origin v1.17.4

### Other details:
I suspect it is one of the advert filters in EasyList

I can get the videos at cbs.com to play if I go to cbs.com, turn off the ublock origin addon, click on a video I want to watch, and within 3-5 seconds turn back on ublock origin. seems to bypass the filter that is blocking the video from playing and will play all the way through without ads.

**Comment by ryanbr** [comment]
`@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=cbs.com`
