### ISSUE TITLE
jawor24h.pl [EasyList] [broken message]

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#2521]
### List the website(s) you're having issues:

`https://jawor24h.pl/`

### What happens?

Breakage - broken message.

### List Subscriptions you're using:

uBO default

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 64 64bit / Opera 57 64bit
- Adblock Extension/version: uBO 1.17.4

### Other details:

<details not-open>
<summary>Screenshoot 1 - with EasyList enabled</summary>

![ss_345](https://user-images.githubusercontent.com/43844449/50383311-55cd3280-06b1-11e9-89c9-227d8e536f8f.png)

</details>
.

<details not-open>
<summary>Screenshoot 2 - with EasyList disabled</summary>

![ss_343](https://user-images.githubusercontent.com/43844449/50383314-5d8cd700-06b1-11e9-8257-b75078564a2a.png)

</details>
.
<details not-open>
<summary>Screenshoot 3 - after the message accepted</summary>

![ss_344](https://user-images.githubusercontent.com/43844449/50383321-785f4b80-06b1-11e9-96d7-3680319e2267.png)

</details>

**Comment by Khrin** [comment]
I don't know Polish, but it looks like containing adverts.
