### ISSUE TITLE
galilu.pl [EasyList] [shadow overlay]

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#2533]
### List the website(s) you're having issues:

`https://www.galilu.pl/`

### What happens?

Breakage - broken message - shadow overlay

### List Subscriptions you're using:

uBO default

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 64 64bit / Opera 57 64bit
- Adblock Extension/version: uBO 1.17.4

### Other details:

<details not-open>
<summary>Screenshoot 1 - with EasyList enabled</summary>

![ss_376](https://user-images.githubusercontent.com/43844449/50447696-4baf6c00-091d-11e9-890f-542c27a62ee1.png)

</details>
.

<details not-open>
<summary>Screenshoot 2 - with EasyList disabled</summary>

![ss_377](https://user-images.githubusercontent.com/43844449/50447699-4f42f300-091d-11e9-8498-7721e93cdd0b.png)

</details>
.
<details not-open>
<summary>Screenshoot 3 - after the message accepted</summary>

![ss_378](https://user-images.githubusercontent.com/43844449/50447702-536f1080-091d-11e9-8d40-05d4f061ddd1.png)

</details>

**Comment by Khrin** [comment]
I guess this isn't happening anymore...
