### ISSUE TITLE
NYTimes.com - Blocked cookie consent = blocked videos (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#2535]
### Affected site:
`https://www.nytimes.com/`

### Issue:
Blocked cookie consent = blocked videos

### Example:
`https://www.nytimes.com/video/magazine/100000006246697/olivia-colman-emma-stone-and-rachel-weisz-coffee-to-go.html`

### Screenshot:
Not needed, as the problem should be obvious.

### Problem filter:
* EasyPrivacy

### Problem rule:
`||optimizely.com^$third-party`

### Possible fix:
`@@||cdn.optimizely.com/public/$script,domain=www.nytimes.com`

### Note:
Issue confirmed by okiehsch here:
https://github.com/uBlockOrigin/uAssets/issues/4418/#issuecomment-450040741

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.2.2 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.6 (XUL)

**Comment by monzta** [comment]
Fixed: https://github.com/easylist/easylist/commit/f91b76ccf542b03494a6f869fe407f0a9653972c

**Comment by Procyon-b** [comment]
OK, I see the difference in my browsing behavior.
If I don't visit the nytimes homepage, the video won't play. But after a visit to `https://www.nytimes.com/` all is OK.

**Comment by THEtomaso** [comment]
@Procyon-b:
Blocking Optimizely at NYTimes.com causes unexpected bahaviour, as explained here:
`https://github.com/AdguardTeam/AdguardFilters/issues/25957/#issuecomment-452771984`
