### ISSUE TITLE
Misspelled regex in popup filters

### ISSUE THREAD

**Issue by gwarser** [easylist/easylist#2550]
Filters starting with `/http*.:\/\/.*`.
This means:`htt`, any amount of `p` (or none), any character (one)...

![image](https://user-images.githubusercontent.com/886325/50539651-edd08d80-0b83-11e9-85b8-2241248a687c.png)
https://regexper.com/#%2Fhttp*.%3A%5C%2F%5C%2F.*%2F

https://github.com/easylist/easylist/blob/fe9be7a447523ff54de8bb4a04150a6888c52bee/easylist_adult/adult_specific_block_popup.txt#L36
https://github.com/easylist/easylist/blob/fe9be7a447523ff54de8bb4a04150a6888c52bee/easylist/easylist_specific_block_popup.txt#L175
Commented out:
https://github.com/easylist/easylist/blob/fe9be7a447523ff54de8bb4a04150a6888c52bee/easylist/easylist_specific_block_popup.txt#L180
I don't believe this one even requires regular expression:
https://github.com/easylist/easylist/blob/fe9be7a447523ff54de8bb4a04150a6888c52bee/easylist/easylist_specific_block_popup.txt#L182

They should be also anchored to start of string `/^htt`...

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/98bc26bdf4189415fc49a44f5ec475c9940ea0f4

**Comment by gwarser** [comment]
So: `htt`, any amount of `p` (or none), any character (one)... 
is deliberate? (Swapped `*.` -> `.*`)

**Comment by IsraeliUser** [comment]
@ryanbr 

Unless you want to block also invalid protocols like **htta**, **httppppppp** or **httpppb**...

`/^http*.:` -> `/^https?:`  (2 filters)
`/http://` -> `/^https?:\/\/` (or `/^http:\/\/` if you want to block only http) (1 filter)
`/http*.:` -> `/^https?:` (1 filter used as a comment)

You can omit the `.*` of `(.*)` at the end of all of the regular expressions, filters are equivalent without it.

`(accountant|bid|click|club|com|cricket|date|download|faith|link|loan|lol|men|online|party|racing|review|science|site|space|stream|top|trade|webcam|website|win|xyz|com)` - `com` appears twice.
 
`/^https?:\/\/.*\.(info|pro|icu|app|xyz|app|pet|win|live|me|io|cc|pw|is|zone|bid|cf|ovh|site|review|ml|xyz)\.*/$image,script,stylesheet,xmlhttprequest,domain=kimcartoon.to|thepiratebay.org`
I think you mean:
`/^https?:\/\/.*\.(info|pro|icu|app|xyz|app|pet|win|live|me|io|cc|pw|is|zone|bid|cf|ovh|site|review|ml|xyz)\//$image,script,stylesheet,xmlhttprequest,domain=kimcartoon.to|thepiratebay.org`
