### ISSUE TITLE
foxcarolina.com

### ISSUE THREAD

**Issue by georgiaconnor** [easylist/easylist#2582]
### List the website(s) you're having issues:

https://www.foxcarolina.com/weather/lane-continues-to-impact-hawaii/article_b36c6b32-4128-5f81-ab45-0fe5c87261af.html

### What happens?

Unblocked sponsored content at end of article.

### List Subscriptions you're using:

AdBlock Defaults

### Your settings

- OS/version: OSX 10.14.1
- Browser/version: Chrome 71
- Adblock Extension/version: AdBlock 3.36.0

### Other details:

<img width="640" alt="vaseline_fox_ad" src="https://user-images.githubusercontent.com/46033562/50606920-6772bf00-0e95-11e9-8b90-dc5db88301fb.png">

**Comment by georgiaconnor** [comment]
Source : `https://publicgood.com/`

add

`||assets.publicgood.com^$third-party`

**Comment by ryanbr** [comment]
No need to add now :)
