### ISSUE TITLE
thoptv.icu

### ISSUE THREAD

**Issue by k0chir0** [easylist/easylist#2585]
**List the website(s) you're having issues:**

http://thoptv.icu/

**What happens?**

Detect adblocker, popups even with nondetectable popup blocking script.

**List Subscriptions you're using:**

Ublock default with nano defender filters

**Your settings**

    OS/version: Windows 10
    Browser/version: Mozilla Firefox 64
    Adblock Extension/version: Ublock Origin 1.17.4

**Other details:**

Site require to install additional addon/extension to use the site which is reasonable as they are trying to protect their steam links but the popups are annoying.

**Comment by ryanbr** [comment]
Dead site
