### ISSUE TITLE
exs.pl

### ISSUE THREAD

**Issue by Hakatitla** [easylist/easylist#2587]
### List the website(s) you're having issues:

nitra.dnes24.sk

### What happens?

Enormeous requests to exs.pl - advert provider onnetwork.tv

### List Subscriptions you're using:
ublock all
EasyList
EasyPrivacy​​​​​
Fanboy's Cookie List​​​​​
Fanboy’s Annoyance List
Fanboy’s Social Blocking List​​​​​
EasyListCZSK

### Your settings

- OS/version: win7
- Browser/version: chrome latest 
- Adblock Extension/version: ublock origin latest

### Other details:

Even thought it is Polish url used on Slovak site, I think it should be blocked in generall.

**Comment by ryanbr** [comment]
Note; Easylist is an English list. so it can't be added

**Comment by Hakatitla** [comment]
@ryanbr i thought it is international list, because this is not only PL ad., but is present in other countries.
