### ISSUE TITLE
ninja-copy.com

### ISSUE THREAD

**Issue by PentagramTr** [easylist/easylist#2599]
### List the website(s) you're having issues: 
https://ninja-copy.com/

### What happens?
Could it be a tracker?Does it need to be blocked?
`https://ninja-copy.com/js/track.js?ver=3.06`

### List Subscriptions you're using: 
English - Annoyance filter - Social Media filter - EasyList Privacy - NoCoin filter list

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 71
- Adblock Extension/version: AdGuard 2.10.14

### Other details:
<details><summary>Screenshot:</summary>

![trck](https://user-images.githubusercontent.com/34379403/50728432-b0976d00-113a-11e9-84d6-3f7be84050fe.png)

</details>

**Comment by Khrin** [comment]
Yes, it is.
