### ISSUE TITLE
False positive domain (Queryly.com, a search cloud vendor)

### ISSUE THREAD

**Issue by searchcloud** [easylist/easylist#260]
Hi,

My name is Xin with Queryly, which is a search cloud (SaaS vendor) for publishers. We provide instant "search as you type" on our clients' sites,. It appears that Adblock (with Easylist) started blocking our js code yesterday.

For example, the search function on http://www.thegazette.com stopped working today. Adblock (with Easylist) blocks our domain (queryly.com) and our JS/API code (according to Chrome Inspector).

Can you please advise on how we can remove our domain from the Easylist?  Please let me know what additional information you need in order to de-list us from the Easylist.

Thank you.

-Xin

**Comment by monzta** [comment]
This seems to be working fine. Is the issue still happening for you?

**Comment by searchcloud** [comment]
Hi Monzta,

Thank you for reaching out.  This issue has been resolved a couple of
months ago.

Thanks.

--
Xin Chen
201-699-7522
