### ISSUE TITLE
My friend's domain was wrongly added list

### ISSUE THREAD

**Issue by AmouxTechnerd** [easylist/easylist#261]
We would appreciate if the website was removed from the list, it's blocking disqus comments on the website.
We do not serve ads directly from this domain.

Domain: 9anime.to
Commit: 3b97b16

![Proof](http://i.imgur.com/cThhrjm.png)

**Comment by SMed79** [comment]
Sure blocked due to the revolving adscripts/popups.

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/9dbf3dd777c03bf78e291087e5afe36dea28f401
