### ISSUE TITLE
https://www.nimiq.com and other related URLs being blocked

### ISSUE THREAD

**Issue by MatthewDLudwig** [easylist/easylist#2618]
### List the website(s) you're having issues:

`||nimiq.com^$third-party`
`||nimiq.watch^$third-party`
`||nimiqchain.info^$third-party`
`||nimiqpool.com^$third-party`
`||nimiqtest.net^$third-party`
`||nimpool.io^$third-party`
`||sushipool.com^$third-party`

### What happens?

The above rules, as well as a few I probably missed, are blocking critical components necessary for the Nimiq blockchain to function.  It's a blockchain written in JS that allows mining in the browser, and both the team and community are dedicated to preventing abuse such as botnets and secret background mining.  All of the reports we've heard thus far are from users who legitimately wanted to mine Nimiq either on the main site "miner.nimiq.com" or on their own site (with some way of notifying their users) by trying to load the code from "cdn.nimiq.com".

If you could consider unblocking these URLs completely (preferred), or possibly creating a blockchain category of URLs so users could easily opt out of having them blocked without turning off the blocker altogether that'd be amazing.  Right now the only advice we can give users in the community is that they need to turn off all adblockers and that's both unfortunate (as ad blockers are quite useful) and a new development (as these URLs weren't blocked 6 months ago).

### List Subscriptions you're using:

I personally use Brave and that's where most of the reports we receive come from.  According to https://brave.com/blog/the-mounting-cost-of-stale-ad-blocking-rules/ easylist is one of the lists used to check for ads, and of the 3 included in that blog post only easylist blocks Nimiq URLs.

### Your settings

Brave includes a neat UI showing separately which ads, cookies, scripts, and trackers were blocked.  The blocked Nimiq related URLs always show up in the ads section of the list, and turning off Brave Shields stops the URLs from being blocked.

- OS/version: Windows 10
- Browser/version:  Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
- Adblock Extension/version: Same as above

### Other details:

https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt is the list responsible for the URLs being blocked as I understand it.

**Comment by Khrin** [comment]
I don't see why our rules should be removed.

**Comment by MatthewDLudwig** [comment]
Thanks for considering my proposal, however I expected a completely different response whether the answer was yes or no.  You were dismissive, didn't explain your points, and immediately closed the issue after commenting.  

I'll respect the rules laid out and not create further issues (or even push this one further) but I will be discontinuing my usage of easylist and easyprivacy, alongside recommending anyone who'll listen to do the same.  My decision has nothing to do with your refusal to unblock the URLs (as I expected it due to the connotation surrounding browser miners), but instead with how you dealt with my request.

**Comment by moracha** [comment]
As an outsider, and fan of NIMIQ, this was an appalling response by Easylist. Goes to show the power wielded by adblockers may not be in the right hands if requests like this one concerning a legitimate website are dismissed as easily as this. Users like myself are fully aware NIMIQ doesn't belong in "advertising" or "spam" classifications. Disappointing.

**Comment by Bettelstab** [comment]
@Khrin Could you please elaborate on why you think legitimate use of Nimiq should be prohibited?

**Comment by brantje** [comment]
@Khrin Any explanation why you won't remove it would be nice.

**Comment by alecthomas28** [comment]
Google brought me here to see why nimiq ended up on a blocklist. Thoroughly unprofessional response by @Khrin  . How does nimiq end up on a privacy focused blocklist? I am failing to make the connection based on the description of this list.

EasyPrivacy
EasyPrivacy is an optional supplementary filter list that completely removes all forms of tracking from the internet, including web bugs, tracking scripts and information collectors, thereby protecting your personal data.

**Comment by xRuffKez** [comment]
https://github.com/hagezi/dns-blocklists/issues/5269
