### ISSUE TITLE
Art19 telemetry

### ISSUE THREAD

**Issue by theel0ja** [easylist/easylist#2620]
### List the website(s) you're having issues:

`https://www.theverge.com/2019/1/7/18172397/airplay-2-homekit-vizio-tv-bill-baxter-interview-vergecast-ces-2019`

### What happens?

Stuff is sent to `telemetry.art19.com`

![](https://user-images.githubusercontent.com/5832930/50818786-07aa6700-1320-11e9-9007-09bbc2b9541e.png)

### List Subscriptions you're using:

easyprivacy

### Your settings

- OS/version: linux
- Browser/version: ff 
- Adblock Extension/version:  ubo

**Comment by TotoDude21903** [comment]
make a pull request or something

**Comment by ryanbr** [comment]
Don't think its tracking, but if you wanna search and show me another page. 

https://publicwww.com/websites/art19.com/
