### ISSUE TITLE
seedpeer.unblocked.app

### ISSUE THREAD

**Issue by adranger** [easylist/easylist#2623]
### List the website(s) you're having issues:

`https://seedpeer.unblocked.app/`

### What happens?

Search blocked by:

    ||unblocked.app^$csp=script-src 'self' * 'unsafe-inline'

After disabling that rule, there are also fake "recommended" links at the top of the  search results:

`https://seedpeer.unblocked.app/search/example`

### List Subscriptions you're using:
EasyList.

### Your settings

uBlock Origin 1.17.4
Firefox 64

**Comment by mapx-** [comment]
fixed in `unbreak list` (`seedpeer.me` too)

**Comment by adranger** [comment]
@mapx- it now redirects to another domain.

**Comment by mapx-** [comment]
update unbreak list and test again
