### ISSUE TITLE
performancetimer.js rule breaking applications

### ISSUE THREAD

**Issue by ycabon** [easylist/easylist#2631]
This [commit](https://github.com/easylist/easylist/blame/953c021f8716dbbedecae1fee79dbc4f83bfa328/easyprivacy/easyprivacy_general.txt#L2547) added `performancetimer.js` as filename to be filtered. Would you consider specifying the rule?

### List the website(s) you're having issues:

Example application breaking with uBlock Origin on https://www.arcgis.com/apps/Styler/index.html?appid=49b3145e36b1406fa5c0bd3cbfce7165

### What happens?

The application doesn't load.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/1074239/50923299-82977e80-1401-11e9-8f61-f7912fe9373a.png)

### Your settings

- OS/version: W10
- Browser/version: Version 71.0.3578.98 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.17.4

**Comment by mapx-** [comment]
fixed in unbreak list (uBo) ... waiting here for a fix

**Comment by Khrin** [comment]
I have to remove the filter, but no explaination of why should I reconsider my decision. That filter will stay for now.

@mapx- I'm not happy of what you've done.

**Comment by mapx-** [comment]
@Khrin  why did you add that filter ? I see no privacy concern (only `collecting page load metrics` - performance).

```
/**
 * JS to help with collecting page load metrics
 */
jQuery(document).ready(function () {
    if (typeof performance !== "undefined" &&
        typeof performance.timing !== "undefined" &&
        typeof performance.navigation !== "undefined" &&
        typeof performance.navigation.type !== "undefined" &&
        typeof performance.timing.navigationStart !== "undefined" &&
        typeof performance.timing.domainLookupEnd !== "undefined" &&
        typeof performance.timing.domainLookupStart !== "undefined" &&
        typeof performance.timing.responseEnd !== "undefined" &&
        typeof performance.timing.requestStart !== "undefined" &&
        typeof performance.timing.domComplete !== "undefined") {
        
        /* calculate performance metrics based on the spec: https://www.w3.org/TR/navigation-timing/#dom-performancenavigation-typenavigate */
        var now = new Date().getTime();
        var pageLoadTime = now - performance.timing.navigationStart;
        var domainLookupTime = performance.timing.domainLookupEnd - performance.timing.domainLookupStart;
        var connectTime = performance.timing.connectEnd - performance.timing.connectStart;
        var responseTime = performance.timing.responseEnd - performance.timing.requestStart;
        var navigationType = performance.navigation.type;
        var domComplete = performance.timing.domComplete - performance.timing.responseEnd;
        var pathname = document.location.pathname;
        var pageName = "";
        if (pathname === "/") {
            pageName = pathname;
        } else {
            var pathNameMatch = document.location.pathname.match(/[^\/]+$/);
            if (pathNameMatch) {
                pageName = pathNameMatch[0];
            }
        }

        jQuery.ajax({
            url: "/API/Lytics/RegisterPageLoaded?tk=" + encodeURIComponent(anlayticToken) + "&plT=" + pageLoadTime + "&dlT=" + domainLookupTime + "&ctT=" + connectTime + "&rpT=" + responseTime + "&ngT=" + navigationType + "&domT=" + domComplete + "&pname=" + pageName,
            type: "GET"
        });
    }
    
});

```

**Comment by Khrin** [comment]
You don't, I do.

**Comment by mapx-** [comment]
Obviously, you added the filter. Could you clear the reason you added the filter ?

**Comment by Khrin** [comment]
Well, using your words, because I see a privacy concern for the user?

**Comment by ycabon** [comment]
Hi, will there be any fix for this issue?

We fixed the next production code on our end to not include a file named `PerformanceTimer`.

But I would like to stress out that uBlock is blocking legit, non-malicious code with this broad filter. This happened to us twice so far, and it's always reported by users that can't figure out what happens, and how to tweak uBlock to not kick in. The first time was with a file named `worker.js`, in easylist FR. 

In general I would like to better understand how to avoid uBlock to mess with production application, if there is any way. Sorry if that's a dumb question. To my understanding, at any given time a completely legit user application could break because we as developers chose some intelligible module naming convention. In this case, `PerformanceTimer` is used to perform measurement at runtime to tweak the amount and complexity of 3D data to display, nothing to do with privacy.

It seems that just renaming the file fixes the issue, it doesn't seem to me that efficient, one could just put some malicious code in a `vendor.js` to be as generic as possible. Anyway, the real issue to me, even if we sanitize that each ad blocker with all regional lists at release time, is that an application could break tomorrow because of some decision happening on Easylist, or similar.

It would be helpful to have some general guidance about how to handle block and to communicate with users and application developers.
 - is the "best" practice to make the filenames not intelligible?
 - or to discourage using uBlock or Easylist, us now looking suspicious.
 - Teach users how to troubleshoot, which is more complicated if the application is embedded.

Thanks for listening!

**Comment by mapx-** [comment]
@ycabon  that filter was neutered in ublock origin 8 days ago
https://github.com/uBlockOrigin/uAssets/commit/0966aa6f95a17466f41cfd40ff32f0add6882392

**Comment by ycabon** [comment]
Ok, I understand better how it works. Sorry mixing up the 2 projects. Thanks @mapx-
