### ISSUE TITLE
EasyList broke custom filter rules

### ISSUE THREAD

**Issue by darkmorpher** [easylist/easylist#264]
**[EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) version 201701311910** suddenly breaks custom filter rules and un-hides them. It also interferes with Element Hiding Helper Firefox extension and doesn't let you select page elements to add them as custom filter rules.

Disabling **[EasyList](https://easylist-downloads.adblockplus.org/easylist.txt)** filter solves the issue and everything goes back to normal.

Note: Issue only started after Jan 28

Similar old bug [[Link](https://adblockplus.org/forum/viewtopic.php?f=1&t=28431&start=15)]

**Comment by monzta** [comment]
Does it still happen with the latest version? I was able to add a custom hiding filter with Element Hiding Helper now.

**Comment by darkmorpher** [comment]
@monzta **[EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) version  201702031750**

I can also add a custom filter rules via Element Hiding Helper Firefox extension again, _but still those rules aren't obeyed and ads are not hidden/blocked_.

**Comment by monzta** [comment]
Thanks. Please try updating EasyList and check again.

**Comment by darkmorpher** [comment]
**[EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) version 201702040350**

No problem so far. Everything seems to be working just as before.

**Comment by darkmorpher** [comment]
Same issue as of **[EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) version 201804130450**

**Comment by Khrin** [comment]
Sorry for the issue, now should be fixed: https://github.com/easylist/easylist/commit/b5d73e17af49bf129b707ce3b1bf8ec835d0d878

**Comment by darkmorpher** [comment]
Same issue as of **[EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) version 201808242020**

**Comment by darkmorpher** [comment]
@Khrin 
Same issue as of **[EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) version 201911150230**

**Comment by darkmorpher** [comment]
@Khrin 
Plz fix, same issue as of **[EasyList](https://easylist-downloads.adblockplus.org/easylist.txt) version 201911241610**
