### ISSUE TITLE
webad.io

### ISSUE THREAD

**Issue by apetrichkovich** [easylist/easylist#2642]
### List the website(s) you're having issues:

**http://webad.io**

### What happens?

All sources are blocking cause line **"/webad."**
Just open our website with turned on adblock or adblockplus.

### List Subscriptions you're using:

**https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt**

### Your settings

- OS/version: Ubuntu 16.04 LTS
- Browser/version: Google Chrome 71.0.3578.98
- Adblock Extension/version: latest AdBlock and AdBlockPlus.

**Comment by monzta** [comment]
Fixed: https://github.com/easylist/easylist/commit/b3e2dc77cd0da37bf6eef8946eaab6832e434b61
