### ISSUE TITLE
An invalid rule for a-ads.com II

### ISSUE THREAD

**Issue by artem-aads** [easylist/easylist#2643]
This is the second time I'm opening this bug report because the previous issue #2513 has been closed without any resolution and I'm unable to reopen it.

Hello,

A recent EasyList update has added the rule `/a-ads.$domain=~a-ads.com` however it makes impossible to use parked a-ads.com subdomains, like

https://a-ads.slack.com/
and
https://a-ads.zendesk.com/

Example:

> uBlock Origin has prevented the following page from loading:
> 
> https://a-ads.zendesk.com/XXXXXXXXXXXXXXXXXXXx
> 
> Because of the following filter
> 
> /a-ads.$domain=~a-ads.com
> Found in: EasyList 

Please, fix.

**Comment by ryanbr** [comment]
artem-aads you could stop creating those a-ads domains easier than us whitelisting them. call it something else?
