### ISSUE TITLE
=stats&action=

### ISSUE THREAD

**Issue by nanexcool** [easylist/easylist#2652]
### List the website(s) you're having issues:
```
https://api.etherscan.io/api?module=stats&action=ethprice
https://blockscout.com/eth/mainnet/api?module=stats&action=ethprice
```

### What happens?
Those addresses work fine when called directly, but when called via Javascript, such as `fetch` or `request`, they are blocked because the string `=stats&action=` is listed here https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L4129

### List Subscriptions you're using:

Using latest uBlock Origin, default settings.

### Your settings

Ubuntu 18.04
Chrome Version 71.0.3578.98 (Official Build) (64-bit)
uBlock Origin 1.17.4

### Other details:

I tried looking at why the `=stats&action=` string is blacklisted but couldn't find any info.

**Comment by ryanbr** [comment]
Could these be changed instead?

**Comment by ryanbr** [comment]
Closing, no folllowup.
