### ISSUE TITLE
delfi.lv

### ISSUE THREAD

**Issue by anonymous74100** [easylist/easylist#2653]
### List the website(s) you're having issues:

https://www.delfi.lv/aculiecinieks/news/witness/foto-izsalkusi-gulbji-kengaraga-aizskerso-promenadi.d?id=50737769&com=1&reg=1&no=0&s=1

### What happens?

The comment section is not shown.

### List Subscriptions you're using:

- EasyList
- EasyPrivacy
- Fanboy’s Annoyance List
- Latvian List

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 64.0.2
- Adblock Extension/version: uBlock Origin v1.17.4

### Other details:

Problematic filter `||delphi.lv/t/t.js` from EasyPrivacy.
Please remove it.

**Comment by ryanbr** [comment]
Seem fine here, I can see comments. Is its still an issue?
