### ISSUE TITLE
technobuffalo.com - everything is broken

### ISSUE THREAD

**Issue by TimValu** [easylist/easylist#266]
Everything is broken on technobuffalo.com
huge white spaces on the new design.
Facebook comments are blocked.
multiple iframes and forms all over the site are hidden too.

Pages:
https://www.technobuffalo.com/2017/02/01/phantom-dust-remaster-should-be-out-before-e3-says-phil-spencer/
https://www.technobuffalo.com/?q=ghh

Screenshot:
http://imgur.com/a/X6C7k

**Comment by SMed79** [comment]
No issue http://i.imgur.com/4ingKAH.png
