### ISSUE TITLE
cnn.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#2669]
See https://github.com/uBlockOrigin/uAssets/issues/4648

Please add:

`cnn.com##.PartnerLinks__component, .PromoBestBeaches__component`

**Comment by Khrin** [comment]
are these still present?

**Comment by mapx-** [comment]
at least `.PromoBestBeaches__component` is still there even using an italian ip

**Comment by Khrin** [comment]
though doesnt look like an advert or a promotion at all

**Comment by terrorist96** [comment]
> are these still present?

Yes. Looks like ads to me. "From our partners"' "content by lending tree" and the beach ads which have the word promo in them.

**Comment by terrorist96** [comment]
What I currently see:
![image](https://user-images.githubusercontent.com/12802056/54281260-b876f180-456f-11e9-8767-759c5ec9ad44.png)

**Comment by ryanbr** [comment]
Self promo, leaving.
