### ISSUE TITLE
mediafire upload breaks

### ISSUE THREAD

**Issue by toshiya44** [easylist/easylist#270]
`|https://$script,third-party,xmlhttprequest,domain=mediafire.com` filter breaks mediafire upload, because it blocks request to `https://ul.mediafireuserupload.com`

Actually I haven't noticed `mediafireuserupload.com` being used by mediafire before. Is it new?

**Comment by SMed79** [comment]
I'v no issue to upload (or download) a file http://i.imgur.com/OC2ttrb.png

**Comment by toshiya44** [comment]
Yup. I just checked again, now they're using `https://www.mediafire.com/douploadtoapi/` instead. 
That was probably some new thing they were testing at the time.

**Comment by toshiya44** [comment]
They're using it again it seems, but this time they fall back to using the old system if connection to `mediafireuserupload.com` fails. Download doesn't break though.

![image](https://cloud.githubusercontent.com/assets/20046789/22830220/ae686cf4-ef73-11e6-8227-0fb50ab62628.png)

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=113044#p113044
