### ISSUE TITLE
rt.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#2705]
See https://github.com/uBlockOrigin/uAssets/issues/4710

Add:
`rt.com##div.columns__content:has-text(/partners/i)`
or
`||mixi.media^$script,domain=rt.com`

**Comment by Khrin** [comment]
Looks like a service similar to Outbrain and Taboola, and it is already blocked by the Annoyances list

**Comment by terrorist96** [comment]
@Khrin aren't Outbrain and Taboola blocked in EasyList though, not Annoyances? So shouldn't this be added to EasyList as well?

**Comment by Khrin** [comment]
We do block only advertised, 3rd party, links in EasyList, while internal links to articles aren't. We do block their domains in Annoyances.

**Comment by terrorist96** [comment]
Those are 3rd party links though. e.g. `https://mixi.media/newdata/news?ad=5852331&bl=92026&ct=adpreview&st=37&ab=jsapi&bvuuid=f46ec8f5-f98d-4736-91d3-5b9a033491b0&ag=25&ev=H4sIAAAAAAAAAOPiWT3zKdOOFQ-YPl27zwQAeBwjnQ4AAAA&rnd=963028`

**Comment by smed79** [comment]
For me, it's a 3rd party advertising.

screenshot https://vgy.me/iXa8gk.png

mixi.media links 
```
https://mixi.media/newdata/news?ad=5761906&bl=92026&ag=25&st=37&ct=adpreview&out=1&ab=b&body_id=781

https://news.grabien.com/making-rich-kid-communism-fidel-castros-model-grandson-flashes-his?utm_medium=referral&utm_source=mixi&utm_campaign=grabien
```
```
https://mixi.media/newdata/news?ad=5857630&bl=92026&ag=25&st=37&ct=adpreview&out=1&ab=a&body_id=781

https://news.grabien.com/story-17-times-nathan-phillips-attacked-nick-sandmann-nbc-intervie?utm_medium=referral&utm_source=mixi&utm_campaign=grabien
```
```
https://mixi.media/newdata/news?ad=5772344&bl=92026&ag=25&st=37&ct=adpreview&out=1&ab=a&body_id=781

https://news.grabien.com/story-pelosi-i-wish-my-members-had-not-leaked-what-i-said-about-tr?utm_medium=referral&utm_source=mixi&utm_campaign=grabien
```
these are not 1st party recomondations as outbrain or taboola.

**Comment by Khrin** [comment]
I looked into and personally all I've seen were links to `mixi.media` itself, and anyway,  I wouldn't block such links in EasyList.

**Comment by terrorist96** [comment]
I don't understand. `mixi.media` is a 3rd party, right? And it's an ad. So why doesn't the policy apply here, but it applies for Outbrain, Taboola, etc.? Is this a case where the policy does not cover it, or there is some unspoken exception to the policy for `mixi.media`? Here's another example of unblocked `mixi.media` links (right column): `https://www.theblaze.com/news/trump-shirt-triggers-gym-members`

**Comment by terrorist96** [comment]
@Khrin could you please explain the reasoning so I know for the future what to report?

**Comment by terrorist96** [comment]
@ryanbr do you understand the reasoning here? Because I don't.
