### ISSUE TITLE
KLP.no - Login options are blocked (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#2710]
### Affected site:
`https://www.klp.no/`

### Issue:
All login options are blocked @ `https://www.klp.no/minside/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyPrivacy

### Problem rule:
`/tracking/tracking.`

### Blocked script:
`https://klpinteraktiv.klp.no/person/plugins/komponentbiblioteket/utils/tracking/Tracking.js`

### Possible fix:
`@@||klp.no/person/plugins/komponentbiblioteket/utils/tracking/Tracking.js$script`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.3.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.7 (XUL)

**Comment by Khrin** [comment]
Yes, nothing we should worry about, the filter was immediately alive and working.
