### ISSUE TITLE
Facebook comments blocked on animeyt.tv

### ISSUE THREAD

**Issue by LPatamon** [easylist/easylist#2713]
### What happens?

When I open a video on animeyt.tv, the facebook comments won't load. A message saying that due to unknown causes, adblock is blocking facebook comments. If I disable easylist, the facebook comments load correctly.

### List Subscriptions you're using:
easylist
easylist spanish
easyprivacy
adbfilters
Adblock Warning Removal List

### Your settings

- OS/version: Windows 7 Ultimate 32 bits
- Browser/version:  Firefox v65
- Adblock Extension/version:  Adblock plus 3.4.1

### Other details:

I'm attaching an image of the message.

![image](https://user-images.githubusercontent.com/6118529/51733880-7be74900-2048-11e9-80ab-c552120fa7e0.png)

**Comment by Khrin** [comment]
site looks dead by now?

**Comment by LPatamon** [comment]
> 
> 
> site looks dead by now?

Yeah. around a week or two later that site closed =/

I posted this back on January 25, I even forgot I posted this lol
