### ISSUE TITLE
https://www.cryptocoinsnews.com/ unblocked ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#272]
`https://www.cryptocoinsnews.com/`

Unblocked ads

**Comment by mapx-** [comment]
`||cdn4.cryptocoinsnews.com/*.gif`

**Comment by terrorist96** [comment]
Should be merged.

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/f022b49b22d4aff68bc5658a12714a97c0c8159a
