### ISSUE TITLE
EasyList blocks search results on infowars.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#273]
http://www.infowars.com/search-page/?test

`Please disable ad blocking services to see your results.`
EasyList is the culprit

**Comment by mapx-** [comment]
`@@||infowars.com^$generichide`

**Comment by terrorist96** [comment]
That gets rid of the prompt to disable adblock, but the search results are still blocked by EasyList.

**Comment by Khrin** [comment]
Fixed: https://github.com/easylist/easylist/commit/0d0ca45e95bf81a970300e75b4f051cd73c95ebc
