### ISSUE TITLE
speedtest.net not working

### ISSUE THREAD

**Issue by WalrusInAnus** [easylist/easylist#276]
It doesn't fully load with Easylist active. The map doesn't show up and the site is partially blank.

**Comment by SMed79** [comment]
Seemed to work fine here (firefox/chrome + adblock plus / easylist + easyprivacy).

**Comment by WalrusInAnus** [comment]
That's puzzling.
Doesn't work for me at all :(
![capture](https://cloud.githubusercontent.com/assets/17233430/22707865/75d2d20e-ed74-11e6-83b3-74804835b829.JPG)

**Comment by WalrusInAnus** [comment]
Oh, I found the reason.
I was using https://easylist-downloads.adblockplus.org/easylist.txt for some reason. I had no idea there were different EasyLists.

**Comment by SMed79** [comment]
There is only one [Easylist](https://easylist.to/) !!

https://easylist.to/easylist/easylist.txt
or
https://easylist-downloads.adblockplus.org/easylist.txt

Are the same one.

**Comment by WalrusInAnus** [comment]
How do you explain that Speedtest loads fine with the first one but not the other one then?

**Comment by SMed79** [comment]
https://www.google.com/search?q=how+to+compare+two+text+files

**Comment by WalrusInAnus** [comment]
I guess the problem lies elsewhere.
But this is wrong and makes Speedtest not load.
![capture](https://cloud.githubusercontent.com/assets/17233430/22742418/f7f9be30-ee16-11e6-9c1d-39ba0cbc8405.JPG)

**Comment by SMed79** [comment]
Use one of these alternative: 

https://fast.com/
http://testmy.net/
http://speedof.me/
http://updowntest.com/
https://www.nperf.com/
http://rottenwifi.com/
http://openspeedtest.com/
http://www.dslreports.com/speedtest

**Comment by WalrusInAnus** [comment]
But that doesn't solve the problem of Easylist errornously blocking Speedtest. This needs to be fixed.

**Comment by SMed79** [comment]
Disable all installed extensions, keep only adblock plus and test again (or test in [firefox portable](http://portableapps.com/apps/internet/firefox_portable) + [ABP](https://adblockplus.org/)).

Submit an [ABP issue report](https://adblockplus.org/en/getting_started#false-positives) and post the link here.

**Comment by WalrusInAnus** [comment]
I already did before.
This has nothing to do with Adblock itself, I am trying to make you acknowledge errornous filter setting! Just look at the screenshot. I can't make it any more clearer than that.

**Comment by LanikSJ** [comment]
Your screenshot doesn't show what's not being blocked.  So if you think your screenshot helps you're sadly mistaken.

**Comment by WalrusInAnus** [comment]
![capture](https://cloud.githubusercontent.com/assets/17233430/22772460/1633b8f2-ee9d-11e6-8d17-c81952e66cbe.JPG)

**Comment by dimisa-RUAdList** [comment]
https://www.speedtest.net/

This rule: `/prebid.$domain=~prebid.org` (EasyList) - breaks the page layout.

Screen: https://i.imgur.com/AvN4RWL.jpg
