### ISSUE TITLE
`-ad2_` prevents an avatar on twitter from loading

### ISSUE THREAD

**Issue by xPaw** [easylist/easylist#2768]
### List the website(s) you're having issues:

```
https://twitter.com/SkeleMann
https://pbs.twimg.com/profile_images/1079396761523892224/ah74-Ad2_400x400.jpg
```

### What happens?

Users avatar doesn't load due to `Ad2` in the url.

Static filter `-ad2_` found in: EasyList 

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Win10
- Browser/version: Chrome 71
- Adblock Extension/version: uBlock Origin 1.17.4

**Comment by THEtomaso** [comment]
'**Fanboy's Annoyance List**' and '**Fanboy's Social Blocking List**' already contains a proper exception rule:
`@@||twimg.com/profile_images/$image,domain=twitter.com`

**Comment by ryanbr** [comment]
Looks like its been resolved
