### ISSUE TITLE
Forum messages and registration not working

### ISSUE THREAD

**Issue by mpavel** [easylist/easylist#277]
Hi,

I wanted to submit a forum entry (https://forums.lanik.us/) and the page failed with the following error:

Fatal error: Cannot redeclare user_get_id_name() (previously declared in /home/lanik/forums/includes/functions_user.php:30) in /home/lanik/forums/includes/functions_user.php on line 85

I then wanted to create an account, but that also failed:

[phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 68: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 68: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: no suitable wrapper could be found
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3257)

And the error shown to me was: The solution you provided was incorrect. (I think this is to do with the Captcha)

The reason I wanted to post in the forums is because that's the instructions on the EasyList.to website, on the "About" page: https://easylist.to/pages/about.html

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=112728#p112728
https://forums.lanik.us/viewtopic.php?f=9&t=34073

**Comment by laniksj** [comment]
Please try to register again in the forum.  I had to have my host enable something they turned off.

**Comment by mpavel** [comment]
Thanks @SMed79 for posting on the forum with the subdomain I mentioned in my other issue! <3
(https://forums.lanik.us/viewtopic.php?f=64&t=35344 and https://github.com/easylist/easylist/issues/278)

I will not post again then, so there are no duplicates.
