### ISSUE TITLE
Wrong blocking on advertising.shpock.com

### ISSUE THREAD

**Issue by mpavel** [easylist/easylist#278]
Hi,

We just launched a website for businesses that *want to advertise with us*. The website is under "advertising.shpock.com". There are no ads on this website.

Unfortunately, the main Adblocking extensions (which of course use EasyList) block background JS requests on the website. This leads to the contact form being broken, for example.

uBlock goes beyond this and blocks the page completely. When the user ads a temporary or even permanent permission in uBlock, the page loads, however, the background JS requests fail. 

In the case of uBlock we see the following:

```
Page blocked because of the following filter
/advertising.$domain=~advertising.bulurum.com|~advertising.byhoxby.com|~advertising.dailymotion.com|~advertising.theguardian.com
Found in: EasyList
```

Can you please ad this URL to the exception list so that we can use the appropriate domain name for the content we display?

Thank you

**Comment by SMed79** [comment]
Fixed https://github.com/easylist/easylist/commit/ebd21a786ebe302e5c5ef9cfdb849bba7b4a4991
