### ISSUE TITLE
EasyList is blocking my website (adx.wowfi.com)

### ISSUE THREAD

**Issue by marzsv** [easylist/easylist#279]
We are a company who developed a software to do marketing over wifi networks, we do not include any type of advertisement in our website, unfortunately the subdomian starts with *adx* so an ad-blocking software (adblock in this case) is blocking all my assets (css, images, javascript) files.

**Comment by SMed79** [comment]
Reported at EasyList Spanish subforum https://forums.lanik.us/viewtopic.php?f=103&t=35343

**Comment by CNMan** [comment]
plz add:)
<img class="inlineimg" alt="" src="http://www.cnprint.org/bbs/images/gg/lzy.gif" border="0">

**Comment by SMed79** [comment]
@CNMan I are you spamming this issue ?...

**Comment by CNMan** [comment]
no, it is a ad url need add to block list.

**Comment by Khrin** [comment]
@marzsv Fixed: http://adx.wowfi.com/en/

**Comment by Khrin** [comment]
@CNMan You're in the wrong place and definitely it's the wrong manner for asking help.

Ask here: http://abpchina.org/forum/

**Comment by marzsv** [comment]
Thank you very much @Khrin ! I really appreciate your help.
