### ISSUE TITLE
http://thejointblog.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#28]
`http://thejointblog.com/`

Some unblocked ads on the right.

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/1c02c8415c811403107679bcdc5ae3be2006ecc8

**Comment by terrorist96** [comment]
@monzta there's still a cropkingseeds.com ad at the bottom right.

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/d8e42c0b63667201bedbc56b0536458db8af0e90
