### ISSUE TITLE
Easylist breaks video

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#280]
http://dailycaller.com/2017/02/08/sen-tim-scott-reads-his-hate-mail-on-the-senate-floor-i-left-out-all-the-ones-that-used-the-n-word-video/

EasyList breaks video.

**Comment by mapx-** [comment]
No issue for me in chrome + ABP + easylist
In firefox + ABP + easylist you have to disable the blob filter to see the video.

**Comment by terrorist96** [comment]
Just tested again on a test profile with only ABP active and only EasyList active. Loading indicator continuously loops and eventually throws an error.
![image](https://cloud.githubusercontent.com/assets/12802056/22804831/d888869e-eee8-11e6-80ac-b06efdc8a68e.png)

**Comment by mapx-** [comment]
see the indications here
https://adblockplus.org/forum/viewtopic.php?f=10&t=43791

and see which are the blocked requests, post them here (select only the blocked items)

**Comment by terrorist96** [comment]
Only the last 5 (starting with the highlighted one) appear when I try to play the video.
![image](https://cloud.githubusercontent.com/assets/12802056/22805121/0f5422ea-eeea-11e6-9692-555dfbb141e1.png)

**Comment by mapx-** [comment]
weird, I get the same blocked xmlhttprequest but it works for me, try:

`@@||pubads.g.doubleclick.net/gampad/ads$xmlhttprequest,domain=imasdk.googleapis.com`

**Comment by terrorist96** [comment]
Yep, that fixes it. Should be merged. Thanks!
