### ISSUE TITLE
Reuters.com - Images are blocked (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#2808]
### Affected site:
`https://www.reuters.com/`

### Issue:
Images are blocked.

### Example:
`https://www.reuters.com/article/us-verizon-yahoo/u-s-judge-rejects-yahoo-data-breach-settlement-idUSKCN1PN20F/`

### Screenshot:

![filterissue-reuters](https://user-images.githubusercontent.com/9382674/52178426-ad8dac00-27ce-11e9-9e0a-c1b39124d748.jpg)

### Problem filter:
* EasyList

### Problem rule:
`||reutersmedia.net/resources/r/?m=$image,subdocument`

### Possible fix:
Delete the problem rule.

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.3.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.8 (XUL)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/78746b8460d0ffc2bd8be4ee97388bcf2155609f
