### ISSUE TITLE
ipify.org

### ISSUE THREAD

**Issue by notDavid** [easylist/easylist#2810]
### List the website(s) you're having issues:
`ipify.org`

### What happens?
it's blocked

### List Subscriptions you're using:
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt

### Other details:
ipify.org is currently blocked, it has nothing to do with spyware or analytics... please consider removing.
It just returns your public ip.

**Comment by ryanbr** [comment]
getting an ip address is considered tracking.

**Comment by brainkim** [comment]
All ipify.org does is send the IP address back to the user. The source code for ipify is available here https://github.com/rdegges/ipify-api. In my use-case, I’m writing a component library and I wanted to use a free API to demonstrate an async call without having to host my own IP address service. Can ipify be reconsidered?

https://github.com/rdegges/ipify-api/issues/18
