### ISSUE TITLE
stripe.network [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#2811]
### List the website(s) you're having issues:

stripe.network / apple pay

### What happens?

Payment service is blocked. It is not a tracker.

### List Subscriptions you're using:

Easylist, Easyprivacy

### Your settings

- OS/version: Win10
- Browser/version: Chrome 
- Adblock Extension/version: ABP

**Comment by tzeejay** [comment]
Hey we're still seeing requests still being blocked because of this.
Stripe has multiple domains and ApplePay is currently broken on our site (adblocking provided via pi-hole-net)

**Comment by tzeejay** [comment]
Okay so after talking to Stripe themselves and testing a bit we've noticed that this doesn't impact payments. We saw another issue.
