### ISSUE TITLE
more www.facebook.com overreach

### ISSUE THREAD

**Issue by filbo** [easylist/easylist#2812]
Expression:

`facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(span:-abp-contains(/Suggested Post|Vorgeschlagener Beitrag/))`

from commit 89438f64bc2e12fb9e179f7bd7dfeb3760894260 catches any post which **discusses** 'Suggested Posts'.  The expression should be anchored and probably restricted to a subset of the entire post.

As an admin on an FB group which discusses things like blocking 'Suggested Post' posts, having these blocked is problematic for both me and my users!

There is an expression of similar intent in my Sponsored post filter set, which looks for this:

`.userContentWrapper>div div>span>span:contains(^Suggested Post$)`

-- which would need to be appropriately wrapped for ad blocker use, _something_ like this, but this is untested:

`facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(.userContentWrapper>div div>span>span:-abp-contains(/^(Suggested Post|Vorgeschlagener Beitrag)$/))`

However, I don't think my expression has been catching anything for months, FB having made such things less easily detected.  So my real recommendation is to just delete the expression.

**Comment by ryanbr** [comment]
Probably now updated. If there any issues with facebook, i'd recommend to re-submit a new issue report.

**Comment by filbo** [comment]
Wow.  The exact problem line is still in the code, 'probably' (== 100%).  Line 9427 of the file, at this moment.

I guess I should submit a new identical bug which can then be closed as 'probably fixed' another 6 months later without actually checking the code?
