### ISSUE TITLE
Proposal to merge smed79/LanikSJ list into EasyList

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#2819]
[See here](https://github.com/uBlockOrigin/uAssets/issues/4201#issuecomment-458371163)
Full list: https://smed79.surge.sh/up/adb.txt
Itemized: https://github.com/LanikSJ/ubo-filters/tree/master/filters

Would be nice if this was integrated with EasyList but it isn't for whatever reason. Why not?

**Comment by ryanbr** [comment]
Probably a bad idea to include some many wholesale domain changes. Ideally we address them as people see them, so atleast we can see how current each domain is (and its not unused or a dead domain)
