### ISSUE TITLE
lifewire.com [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#2827]
### List the website(s) you're having issues:
[https://www.lifewire.com/top-greasemonkey-tampermonkey-user-scripts-4134335](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.lifewire.com%2Ftop-greasemonkey-tampermonkey-user-scripts-4134335)

### List Subscriptions you're using:

EasyList,
Fanboy's Annoyances,

Caused by `lifewire.com##.loc`
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/52487314-0b066c00-2bc6-11e9-9b20-1c594df35910.png)

</details>

**Comment by THEtomaso** [comment]
The problem rule is found in the following filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

I've filed a new report here:
https://github.com/ryanbr/fanboy-adblock/issues/933/
