### ISSUE TITLE
EasyPrivacy: /WRb.js rule blocks different resource because of partial match

### ISSUE THREAD

**Issue by stijnherreman** [easylist/easylist#2830]
### List the website(s) you're having issues:

JSON resource on Azure CDN requested by a non-public website: https://redacted.azureedge.net/redacted/features/wrb.json?sv=redacted

### What happens?

The following EasyPrivacy rule blocks the request to `/wrb.json` because of a partial match

https://github.com/easylist/easylist/blob/cc3c4ab2fdb3c02ea5962c96a29f053578a30127/easyprivacy/easyprivacy_general.txt#L4095

### List Subscriptions you're using:

Default uBlock Origin installation on Firefox, relevant subscription is EasyPrivacy (version 201902080731).

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 65
- Adblock Extension/version: uBlock Origin 1.18.4

### Other details:

![screenshot of uBlock Origin logger showing the blocked URL and applied filter rule](https://user-images.githubusercontent.com/1618054/52489805-80247200-2bc3-11e9-88b3-df3217fac1d9.png)

**Comment by Khrin** [comment]
Totally useless report, not even worthwhile to be taken in consideration.

Goodbye.

**Comment by stijnherreman** [comment]
I beg you pardon? I attempted to fill in the template as good as possible. What exactly is so useless about this?
