### ISSUE TITLE
Wrong blocked on AdEspresso.com page

### ISSUE THREAD

**Issue by antoscarface** [easylist/easylist#286]
This is a page I worked on https://adespresso.com/facebook-ads-quiz/
With AdBlocker activated, you can see the entire website adespresso.com without any problem, but if you try to make the survey of the link above and click to start, you can see after the page without style (that is the same CSS contents of the entire website), but if I refresh again with CMD+R, the style is good, but again if I continue on next submit the style is broken and again if I refresh everything is good.

Furthermore, if I try to keep open the inspector of Chrome and I try to submit, everything is good. So, I can't understand why the contents are blocked.

There isn't any ad to block, it's a simply quiz survey for facebook ads knowledge :)
Could you please help me? Thanks.

**Comment by antoscarface** [comment]
I see the domain in this file https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers.txt so for this reaso I write also here, I don't know if you can help me and if you could be the solution for me. Thanks.

**Comment by mapx-** [comment]
if it happens only in chrome + ABP, it's a bug (a patch is under review):
https://issues.adblockplus.org/ticket/4599

test your page in firefox too, see if happens

**Comment by antoscarface** [comment]
The page is blocked only on Chrome. Firefox and Opera display the page good, without blocked elements. Isn't there any way to fix without wait the bug fix? It's blocking for me. I can't see neither what cause the block, because if I open the chrome inspector the problem is fixed and I see the page good.

**Comment by monzta** [comment]
Closing since this has been fixed in Adblock Plus for Chrome.
