### ISSUE TITLE
[Incorrect blocking] https://ipinfo.io/

### ISSUE THREAD

**Issue by mdsyslab** [easylist/easylist#2865]
### List the website(s) you're having issues:

`https://ipinfo.io/`

### What happens?

Site is blocked
`Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`

### List Subscriptions you're using:

easyprivacy_trackingservers.txt
https://github.com/easylist/easylist/commit/afb614087c0848e648f25054e189796513cdc1d5#diff-dbc51871bdd5cf7971a65ef9684d2248R2781
### Your settings

- OS/version: Win 10 1803
- Browser/version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.18.4

### Other details:

`https://ipinfo.io/` is an API service that when queried returns the IP address of the host making the query (or a specified IP), along with some information regarding that IP (what ASN it belongs to, rdns hostname, geolocation data, etc). 

This is a generic service which I do not believe does any user tracking per se, it just provides details for a given IP address. These details are public domain and not tied to a specific user/browser session/etc. 

Example:

`https://ipinfo.io/json`

**Comment by Khrin** [comment]
An example site where this service is used?

**Comment by mdsyslab** [comment]
I've found it useful for IT work, we run a small site with a page that uses this API. 

- Confirming proxies for web traffic are operating correctly (returned IP should match proxy WAN)
- Confirming routing/NAT configurations are correct (different VLANs should route/nat out via different WAN addresses or different ISP)
- Easy way for non-technical customers to provide their WAN IP
- Quickly identifying what ISP a customer is on if I'm onsite (via ASN)

**Comment by ryanbr** [comment]
Still has to pull details, any form of ip/geo checks will have some form of tracking involved.

**Comment by wesinator** [comment]
> An example site where this service is used?

the IPinfo service is used on robtex - https://www.robtex.com/ip-lookup/1.1.1.1 
the geolocation map doesn't show up with uBlock Origin blocking

**Comment by spirillen** [comment]
If I should cast a cent or two....

https://gitlab.com/my-privacy-dns/matrix/matrix/issues/26

> ## Short Description
> ipinfo.io is tracking you down violating you're privacy. takes geolocation details of the user (still tracking the user)

```
/**/ typeof getIpData === 'function' && getIpData({

  "ip": "xxx.xxx.xxx.xxx",

  "hostname": "No Hostname",

  "city": "Some city",

  "region": " ",

  "country": "NZ",

  "loc": "-99.1555,99.1113",

  "org": " ",

  "postal": "0000"

});

```

**Comment by wesinator** [comment]
> If I should cast a cent or two....
> 
> https://gitlab.com/my-privacy-dns/matrix/matrix/issues/26
> 
> > ## Short Description
> > ipinfo.io is tracking you down violating you're privacy. takes geolocation details of the user (still tracking the user)
> 
> ```
> /**/ typeof getIpData === 'function' && getIpData({
> 
>   "ip": "xxx.xxx.xxx.xxx",
> 
>   "hostname": "No Hostname",
> 
>   "city": "Some city",
> 
>   "region": " ",
> 
>   "country": "NZ",
> 
>   "loc": "-99.1555,99.1113",
> 
>   "org": " ",
> 
>   "postal": "0000"
> 
> });
> ```

that doesn't mean it's actually _tracking_ users.
It _is_ a service that provides IP geolocation and info , that is used by other sites legitimately.

**Comment by spirillen** [comment]
Hi @wesinator I _**recalls**_ it as this is the reason why it get blocked by a various number of lists, as someone had followed the entire .js flow, and that this is the data it collects about you to optimize the tracking precision of IPs geo-location.

Remember this is _as i recalls it_, as i clearly haven't kept enough info in my records and unfortunately haven't added a link to the issue it comes from...

But the verdict was block, , otherwise I haven't added it to my list. If one could find that thread, we could follow up on it from there. I believes it's originates here from GH.

**Comment by wesinator** [comment]
I understand, well it also breaks services that actually use the IPinfo data for information on IP addresses not the client IP

**Comment by adcar** [comment]
> If I should cast a cent or two....
> 
> https://gitlab.com/my-privacy-dns/matrix/matrix/issues/26
> 
> > ## Short Description
> > ipinfo.io is tracking you down violating you're privacy. takes geolocation details of the user (still tracking the user)
> 
> ```
> /**/ typeof getIpData === 'function' && getIpData({
> 
>   "ip": "xxx.xxx.xxx.xxx",
> 
>   "hostname": "No Hostname",
> 
>   "city": "Some city",
> 
>   "region": " ",
> 
>   "country": "NZ",
> 
>   "loc": "-99.1555,99.1113",
> 
>   "org": " ",
> 
>   "postal": "0000"
> 
> });
> 
> ```

Might as well block every website in existence since they can log your IP and perform geo lookups on you...

**Comment by Gowee** [comment]
Hi, there.

@ryanbr 

> Still has to pull details, any form of ip/geo checks will have some form of tracking involved.

I do not think there is any distinct difference between this API with any other functional API all over the world. The scenario is as simple as: one submit an IP and get the geo as the response. Just like: one submit a city name and get its latitude, longitude, and zip code as the response.

Yes, it is ok to say some tracking might be involved. But then **this assumption hold for any kinds of APIs, certainly not limited to it.**

[In my scenario](https://github.com/Gowee/traceroute-map-panel), I need it (or any other equivalent API) for getting the geolocation of IPs to fill a map accordingly. 

@spirillen

How could its API collect "collects about you to optimize the tracking precision of IPs geo-location" at all?

When requested on a third-party website, all it can know is the queried target (IP address), as well as IPs and User-Agents which are available to any websites one visits, just like every other third-party API. 

The geolocation data might be collected in an unethical or privacy-invading way. But anyway it has nothing to do with making a simple API request to the website.

**Comment by spirillen** [comment]
Hey @Gowee 

can only reply with the same answer as in https://github.com/easylist/easylist/issues/2865#issuecomment-555988725 :arrow_double_up: 

> Such kind of geolocation data might be collected in an unethical or privacy-invading way. But anyway it has nothing to do with making a simple API request to the website.

Absolutely, and when they are spotted they are added :smirk: 

> How could its API "collects about you to optimize the tracking precision of IPs geo-location" at all?
The API can, IF, it is storing the queries. Second to this is, it is less the API, for API's sake you should be blocking it, but for the abuse of it, where example.org are abusing the API to target/collect data about it's visitors.

So yes, it's a grey area.

**Comment by Gowee** [comment]
Hi, @spirillen .

Thanks for your reply. I did read your previous comment.

> The API can, IF, it is storing the queries. 

Yes. But **any** API can store queries. Certainly, this reason won't contribute to blocking requests to Google Maps entirely. Instead, people choose to block third-party cookies for improving privacy. Even a public CDN such as https://cdnjs.com/libraries/jquery has the ability to store queries and use that a few bits of entropy to track users somehow. 

> but for the abuse of it, where example.org are abusing the API to target/collect data about it's visitors.
Now that example.org has stored users' IP addresses, it can geo-locate that IP in the website backend somehow. It is trivial, transparent, and the common way that almost every tracking service follows.

**Comment by foxt** [comment]
Most websites that may be violating your privacy wont even be making the calls to ipinfo.io on your client in the first place. Makes no sense to have it blocked for the people who need to use it when blocking it doesnt affect your privacy.

**Comment by PearlDragon** [comment]
this issue needs to be reopened. ipinfo.io is still blocked by this list. Since users can no longer whitelist urls in uBlockOrigin due to Google's Manifest v3 migration, the erroneous assumptions made in the previous comments should be addressed.

I can answer any questions about privacy wit regard to this site as needed
