### ISSUE TITLE
Blocking too much: afcdn.com/relen/concat

### ISSUE THREAD

**Issue by FlorentPalomares** [easylist/easylist#287]
Hello,

I'm running the website http://www.sofeminine.co.uk

Since a few days, a rule has been added to https://easylist-downloads.adblockplus.org/easylist.txt:
||afcdn.com/relen/concat.

Unfortunatly, this pattern targets the global CSS & JS code used by my website...
So website becomes impossible to use (try it!)

How can I process to remove this rule from easylist?

Thanks
Florent

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/ead7a1d232a5ccdd8ec37b3330099e27ad90990d
