### ISSUE TITLE
Missed ad-exchanges in list: mediamonetizer.com & plaimedia.com

### ISSUE THREAD

**Issue by aels** [easylist/easylist#288]
This two domains serve low-quality ads and seems missed from blacklist:

- mediamonetizer.com/*
- plaimedia.com/*

Thanks.

**Comment by SMed79** [comment]
Provide example page where we can see the ads.
[rules#participation](https://forums.lanik.us/rules#participation)

**Comment by aels** [comment]
sorry for the delay. Found a few:
https://plaimedia.com/pmc/c/772/?type=js&PMC_zone_id=1863230182&PMC_domain={DOMAIN}&PMC_publisher={PUBLISHER_ID}&PMC_click_url={CLICK_URL_ENCODED} - js
https://plaimedia.com/pmc/b/58aabcd1ac142e1a50b48131.jpg - img.
Not sure about examples pages, bcuz ad itself is in rare rotation, and it's unclear to me how it gets loaded into the browser

**Comment by SMed79** [comment]
An examples pages where we can see plaimedia & mediamonetizer NOT the URL to the ad.

**Comment by venediktov** [comment]
Perhaps you find our repo interesting for your projects ?
https://github.com/abushev/vanilla-rtb
Thanks,
Vlad.
