### ISSUE TITLE
disneynow.go.com - [Incorrect Blocking]

### ISSUE THREAD

**Issue by shirtjs** [easylist/easylist#2891]
### List the website(s) you're having issues:
disneynow.go.com

Example URLs without required authentication:
https://disneynow.go.com/shows/pokemon-the-series-sun-moon2/season-21/episode-21-turning-heads-and-training-hard/vdka4716991?pid=PL553044961
https://disneynow.go.com/shows/beyblade/season-10/episode-06-winter-knight-battle-royale/vdka7051532?pid=PL553044961

### What happens?

No video appears due to cdn1.edgedatg.com/aws/assets/cp/web/assets/js/VisitorAPI.js being blocked.

### List Subscriptions you're using:
EasyList
EasyPrivacy
uBlock Origin Assets

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 72
- Adblock Extension/version: Nano Adblocker 1.0.0.88

### Other details:
I suspect EasyPrivacy for being the issue here.

![chrome_regwjpg68p](https://user-images.githubusercontent.com/2660574/53208639-84aa4b00-3605-11e9-9102-89bdc484b00b.png)

**Comment by THEtomaso** [comment]
Confirmed.
Allowing **VisitorAPI.js** seems to fix it.
