### ISSUE TITLE
justanswer.com: Intrusive and deceiving pseudo-popup

### ISSUE THREAD

**Issue by Zenexer** [easylist/easylist#2897]
### List the website(s) you're having issues:

```
https://whatismyipaddress.com/ip/8.8.8.8
```

### What happens?

This annoying thing from `justanswer.com` popped up:

![image](https://user-images.githubusercontent.com/504130/53219167-f649bf80-362c-11e9-9064-8f5c0460d2b1.png)

### List Subscriptions you're using:

Intrinsic uBlock Origin lists:

- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse​​​​​
- uBlock filters – Unbreak​​​​​
- EasyList
- EasyPrivacy
- Malware Domain List
- Malware domains
- Peter Lowe's Ad and tracking server list

### Your settings

- OS/version: Windows 10 Pro x64, latest version, up-to-date
- Browser/version: 72.0.3626.109 (Official Build) (64-bit) (cohort: Stable)
- Adblock Extension/version: uBlock Origin v1.18.4 (cjpalhdlnbpafiamejdnhcphjbkeiagm)

**Comment by ryanbr** [comment]
Not seen here, possibly fixed already.

**Comment by Zenexer** [comment]
@ryanbr Thanks for taking a look at this.  whatsmyipaddress.com no longer shows the popup, but the ad is probably still visible on other sites, since justanswer.com isn't blocked.

**Comment by ryanbr** [comment]
just submit a new request if you come across it, and it'll just need to be reviewed
