### ISSUE TITLE
Outlook.com -- Outlook on the web

### ISSUE THREAD

**Issue by shmu26** [easylist/easylist#2898]
After Chrome update, outlook.com is now showing "it looks like you are using an adblocker"
I am using nano adblocker and nano defender. 
This issue applies to the free version of Outlook on the Web, as the paid version does not show ads.
Platform: Linux Mint 19.1 x64 Cinnamon
Chrome version: Version 72.0.3626.119 (Official Build) (64-bit)

Edit: I tested on Windows 10 with Chrome, and after Chrome update, there is the same issue.

**Comment by ryanbr** [comment]
Won't be fixed in Easylist.
