### ISSUE TITLE
Bootstrap social login button - False positive

### ISSUE THREAD

**Issue by vvzen** [easylist/easylist#290]
As described [here on the forum](https://adblockplus.org/forum/viewtopic.php?f=18&t=51457),
I'm developing a website using bootstrap v4 and I noticed that adblockplus hides a social login button.
The code for the button is this one:
```
<button class="btn btn-block btn-social btn-linkedin btn-low-shadow" type="submit" name="platform" value="linkedin">
    <span class="fa fa-linkedin"></span> Sign in with Linkedin
</button>
```

Thanks

**Comment by Khrin** [comment]
This website is already live? I don't think it's possible to remove this filter, so if you can't change the button name, only possibility is to whitelist the domain.

**Comment by VVZen** [comment]
The website is live but without a domain name (only IP address).
Unfortunately I can't change the button class! Is it possible to whitelist the domain (when there will be one) so that all the users will regularly see the button?

**Comment by Khrin** [comment]
Sure, of course that's possible. But I need the domain name for that... You've already one reserved?

**Comment by VVZen** [comment]
Not yet! Can I update the issue as soon as the company chooses one?

**Comment by Khrin** [comment]
Yes, when you're ready, no problem.
