### ISSUE TITLE
Dropbox.com

### ISSUE THREAD

**Issue by benwaffle** [easylist/easylist#2901]
### List the website(s) you're having issues:

`dropbox.com`

### What happens?

Front page doesn't load unless I whitelist `dropboxstatic.com`

`www.dropbox.com dropboxstatic.com * allow`

### List Subscriptions you're using:

Fanboy's Annoyance List

### Your settings

- OS/version: MacOS 10.14.2
- Browser/version: Firefox 65.0.1 (stable)
- Adblock Extension/version: uBlock Origin v1.18.4

**Comment by Khrin** [comment]
i can load images correctly. must be ubo's problem
