### ISSUE TITLE
FoodNetwork.com annoying "please turn off adblock" message"

### ISSUE THREAD

**Issue by Smittyvb** [easylist/easylist#2919]
### List the website(s) you're having issues:
``https://www.foodnetwork.com/recipes/articles/50-pie-recipes``

### What happens?
![image](https://user-images.githubusercontent.com/10530973/53447696-bc3d3c80-39e3-11e9-8837-5589b12e5944.png)

### List Subscriptions you're using

- uBlock filters 
- Adblock Warning Removal List
- EasyList
- EasyPrivacy
- Malware Domain List
- Malware domains
- Peter Lowe’s Ad and tracking server list

### Your settings

- OS/version: Chrome OS 71.0.3578.127 (Official Build) (64-bit)
- Browser/version: ^^^
- Adblock Extension/version: uBlock Origin v1.18.4

### Other details:

``##.o-AdhesionNotifier`` seems to resolve the issue.

**Comment by Khrin** [comment]
Sorry, but can't be added...
