### ISSUE TITLE
EasyPrivacy blocks some POST requests on the MyAnimeList forum

### ISSUE THREAD

**Issue by MathiasSpanhove** [easylist/easylist#292]
Some forum functionality on [MyAnimeList](https://myanimelist.net) broke because of the `.inc.php?` rule in [easyprivacy_general.txt](easylist/easyprivacy/easyprivacy_general.txt) since MAL uses `myanimelist.net/includes/ajax.inc.php?`.

Relevant forum topic on MyAnimeList: https://myanimelist.net/forum/?topicid=1594588

I'm currently using this whitelist rule to solve the problem: `@@||myanimelist.net/includes/ajax.inc.php?*`

**Comment by Khrin** [comment]
I've modified our filter to be less generic, so should work for us and doesn't cause anymore false positives. In a few minutes you should update EasyPrivacy and you can also remove your custom filter. Sorry for the issue.
