### ISSUE TITLE
validate domains with nslookup/whois

### ISSUE THREAD

**Issue by jawz101** [easylist/easylist#2925]
Request that the current list and any additional entries be verified not only for syntax but also by validating that the domains pass nslookup/whois verification.  If the domains are dead the lists just grow.

[Preliminary testing](https://github.com/easylist/easylist/issues/2374) shows that approx. 29% of Easylist domains are dead and 11% of Easy Privacy domains are dead.  It seems reasonable to represent a list that is fairly up-to-date- not only on catching new stuff but pruning stale records.  Many professional products reference the EasyLists and if many domains are dead then it portrays a skewed stance of the privacy/advert/analytic landscape.  It also might reduce system requirements on low-powered devices.

**Comment by ryanbr** [comment]
Lets keep it there, no need for another ticket.
