### ISSUE TITLE
www.pega.com

### ISSUE THREAD

**Issue by angelboy65** [easylist/easylist#2926]
### List the website(s) you're having issues:

<code>www.pege.com</code>
### What happens?

above mentioned website is being blocked when using adguard.
### List Subscriptions you're using:

dns.adguard.com
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by Khrin** [comment]
Why are you reporting here then? Report it to https://github.com/AdguardTeam/AdguardFilters

**Comment by angelboy65** [comment]
@Khrin originally I reported to adguard team at your mentioned URL they said that its the EasyList that is causing the block. They asked me to contact easylist to have it unblock from the easylist. here is the reference URL to adguard for your reference https://github.com/AdguardTeam/AdguardFilters/issues/29746#issuecomment-464765699

**Comment by ryanbr** [comment]
the page loads fine here, unless you have more info on the filter that is causing it, cant help.
