### ISSUE TITLE
https://src.fedoraproject.org/rpms/firefox/stats

### ISSUE THREAD

**Issue by nbeaver** [easylist/easylist#2935]
### List the website(s) you're having issues:

`https://src.fedoraproject.org/rpms/firefox/stats#authors`

### What happens?

Expected result: Author stats load

Actual result: Spinner gif loops endlessly

Logger reports:

    +1	_stats.js?	--	src.fedoraproject.org	1	script	https://src.fedoraproject.org/static/issues_stats.js?version=5.3.1
    +0	_stats.js?	--	src.fedoraproject.org	1	script	https://src.fedoraproject.org/static/issues_stats.js?version=5.3.1
    +0	https://src.fedoraproject.org/rpms/firefox/stats#authors

### List Subscriptions you're using:

- uBlock filters
- EasyList
- EasyPrivacy

Seems to be caused by this line:

    _stats.js?

https://github.com/easylist/easylist/blob/88dcd9901f20469df76ef51da3f3530b9148216e/easyprivacy/easyprivacy_general.txt#L4379

### Your settings

Reproduced in a clean profile with only uBlock Origin installed.

- OS/version: Ubuntu 18.04
- Browser/version: Firefox 65.0.1
- Adblock Extension/version: 

### Other details:

Screenshot:

![screenshot_20190302_150649](https://user-images.githubusercontent.com/3036798/53687659-e3a24b00-3cfc-11e9-8045-6569b4bcf4cf.png)

**Comment by THEtomaso** [comment]
Confirmed.

Possible fixes:
`@@_stats.js?$domain=fedoraproject.org`
or
`@@||fedoraproject.org/static/issues_stats.js`
