### ISSUE TITLE
www.pega.com

### ISSUE THREAD

**Issue by angelboy65** [easylist/easylist#2936]
### List the website(s) you're having issues:
www.pega.com

### What happens?
I am unable to visit www.pega.com website. I get this page cannot be displayed. I am also not able to ping to this website. However this website is accessible if I don't use dns.adguard.com. 

I have already raised this issue with adguard.com here is the issue# 29746. here is the link [https://github.com/AdguardTeam/AdguardFilters/issues/29746#issuecomment-464765699](url)
to the issue that is raised with adguard. They told me that its the easylist filter that is blocking the access and I need to contact easylist to get it resolved. 

I have existing issue #2926 but it is closed now. I did reply to the closed issue but since I did not receive any response to the closed issue I am raising again. 

Thanks 

### List Subscriptions you're using:
dns.adguard.com

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
responded to previous closed issue report. see there.
