### ISSUE TITLE
a few syntax errors on lists

### ISSUE THREAD

**Issue by stream009** [easylist/easylist#2938]
- '$' is not an option delimiter.
https://github.com/easylist/easylist/blob/c95236b057373e9b0334c9d34e9822ccd71a2627/easylist/easylist_general_block_popup.txt#L122

- option is broken
https://github.com/easylist/easylist/blob/c95236b057373e9b0334c9d34e9822ccd71a2627/easylist/easylist_specific_block.txt#L4738

**Comment by Khrin** [comment]
thank you
