### ISSUE TITLE
telegraph.co.uk

### ISSUE THREAD

**Issue by carlbennett** [easylist/easylist#294]
Url: http://www.telegraph.co.uk/news/2017/03/01/new-drivers-caught-using-phone-wheel-will-lose-licence-new-laws/

Problem: Can't scroll or dismiss adblock message, blocking the `.adblocker-message` class removes dialog but scrolling is still prevented

Need a rule for this that allows scrolling still, please!

**Comment by Khrin** [comment]
Now should work correctly, you can update EasyList in a few minutes.

**Comment by carlbennett** [comment]
The rules from 770842b don't appear to be working. I even tried adding them as manual filters.

**Comment by Khrin** [comment]
It's working for me on Firefox, are you sure to have updated the EasyList subscription? If yes, what browser are you using?

**Comment by carlbennett** [comment]
```
×   Enabled Adblock Warning Removal List Last updated at 12:30:44 PM today
×   Enabled EasyList Last updated at 12:30:45 PM today
×   Enabled Malware Domains Last updated at 12:30:45 PM today
×   Enabled EasyPrivacy Last updated at 12:30:45 PM today
```
(Timestamps are in Central Standard Time.)

I also tried adding them manually via 'Add your own filters', copying them directly from the commit. That didn't work either.

- Chromium Opera: `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991`
- [Adblock Plus Version 1.12.4](https://addons.opera.com/en/extensions/details/opera-adblock/?display=en-US)

**Comment by Khrin** [comment]
Does adding this as custom filter `@@||telegraph.co.uk^$generichide` makes any difference to you?

**Comment by carlbennett** [comment]
Nope :(
