### ISSUE TITLE
Pippio duplicate in EasyPrivacy

### ISSUE THREAD

**Issue by Gitoffthelawn** [easylist/easylist#2944]
EasyPrivacy contains both:

`||pippio.com^$domain=disqus.com`
and
`||pippio.com^$third-party`

Does it need them both for some reason, or just the latter?

**Comment by Khrin** [comment]
yes is done on purpose

**Comment by Gitoffthelawn** [comment]
@Khrin Could I ask why?  What situation does the first filter block that the second filter does not?  TIA
