### ISSUE TITLE
yahoo.com articles

### ISSUE THREAD

**Issue by vinodc** [easylist/easylist#2945]
### List the website(s) you're having issues:

Yahoo.com articles: https://www.yahoo.com/sports/why-the-nfl-combine-is-buzzing-over-a-hardthrowing-qb-whos-messing-up-peoples-money-224434463.html

The right sidebar contains ads mixed in with articles.

### What happens?

`[data-ad-story-beacon]` elements need to be blocked. Adding this via uBO resolves the issue.

### Your settings

- OS/version: Mac OS X
- Browser/version: Chrome
- Adblock Extension/version: uBO default.

**Comment by ryanbr** [comment]
Leaving, saw no ads. would need more reports.
