### ISSUE TITLE
autorrents.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#3]
`http://autorrents.com/Veertu-1-0-4-%5bK%20%20039%20ed-from-Mac-App-Store%5d-Run-Windows-%20-Linux-on-Mac-OS-X-torrent-7357662.html` and `https://www.limetorrents.cc/Veertu-1-0-4-[K%20%20039%20ed-from-Mac-App-Store]-Run-Windows-%20-Linux-on-Mac-OS-X-torrent-7357662.html`

Fast and direct ad

`http://autorrents.com/search/all/linux/` and `https://www.limetorrents.cc/search/all/linux/`

3 ads at the top.

Original report: https://forums.lanik.us/viewtopic.php?f=62&t=28432

**Comment by monzta** [comment]
Added 
https://github.com/easylist/easylist/commit/ac9f7d0651997968e8cbe5f655656347c6fdbe32 
https://github.com/easylist/easylist/commit/c5513f2e4c98aa17d1a80af09b38fecf6782a6d8 
https://github.com/easylist/easylist/commit/01894d1b2ef1ca98eb57d17910fa2c2594fc2c65 
https://github.com/easylist/easylist/commit/303a19e393a25856bf69774a92b0891e66058303

**Comment by terrorist96** [comment]
@monzta `http://autorrents.com/Veertu-1-0-4-%5bK%20%20039%20ed-from-Mac-App-Store%5d-Run-Windows-%20-Linux-on-Mac-OS-X-torrent-7357662.html`
Fast and direct still visible on that link. All others look fixed. Thanks.

**Comment by monzta** [comment]
Thanks, added https://github.com/easylist/easylist/commit/8005fb069bb53ef2e54c5371d9bba5c4c6df1dad
