### ISSUE TITLE
http://www.wearebaked.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#30]
`http://www.wearebaked.com/`

Stoner advertising on left

**Comment by monzta** [comment]
Site seems to be offline.

**Comment by terrorist96** [comment]
Works for me. Please reopen/fix.

**Comment by terrorist96** [comment]
@monzta Also, you can use http://downforeveryoneorjustme.com to see if the site really is down.

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/7f55abba298c2ceb46a59d3e64f29ba50818aa32
