### ISSUE TITLE
Unblocked ad on Youtube

### ISSUE THREAD

**Issue by OmgImAlexis** [easylist/easylist#300]
I tried reporting this on your forum but I just get this when clicking preview before I post.

```
Fatal error: Cannot redeclare user_get_id_name() (previously declared in /home/lanik/forums/includes/functions_user.php:30) in /home/lanik/forums/includes/functions_user.php on line 85
```

Using Youtube in Australia I get this 
`###contents > .ytd-search-pyv-renderer.style-scope`

The URL for the page is https://www.youtube.com/results?search_query=ethoslab

![screen shot 2017-03-07 at 9 18 39 pm](https://cloud.githubusercontent.com/assets/6525926/23653366/2d330384-037c-11e7-98a5-7b6141bef8e3.png)

**Comment by IsraeliAdblocker** [comment]
Reported also here https://forums.lanik.us/viewtopic.php?p=112014&hilit=youtube#p112210

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/9aefd90efbd52210f4fa2c82bcaa745a49b3d8a0
