### ISSUE TITLE
Pornhub streaming broken

### ISSUE THREAD

**Issue by brettph** [easylist/easylist#3020]
### List the website(s) you're having issues:
pornhub.com

### What happens?
Streaming doesn't work. We are moving to dash/hls streaming, the files need to be whitelisted by easylist. We're currently at 5% of users seeing dash/hls.
Need these added:
@@||phncdn.com/dash/videos/$media,object,object-subrequest,other,domain=pornhub.com|redtube.com|tube8.com|youporn.com|youporngay.com
@@||phncdn.com/hls/videos/$media,object,object-subrequest,other,domain=pornhub.com|redtube.com|tube8.com|youporn.com|youporngay.com

**Comment by LiveChief** [comment]
PULL REQUEST

**Comment by ryanbr** [comment]
It works fine. Closing.

**Comment by brettph** [comment]
@ryanbr did you whitelist those files? Pushing it to 100% this week so it will be broken.
