### ISSUE TITLE
Pulldown menus broken on AT&T report robocalls page

### ISSUE THREAD

**Issue by phillipremaker** [easylist/easylist#3029]
### URL(s) where the issue occurs

`https://www.att.com/esupport/report-call-or-text.html`

### Describe the issue

Pulldown menus for timezone and type of contact broken; am/pm radio button suppressed.

### Screenshot(s)

ublock on

<img width="699" alt="Screen Shot 2019-03-11 at 3 09 50 PM" src="https://user-images.githubusercontent.com/8801492/54161577-d4fc1800-440f-11e9-9fa5-fd09817d945a.png">

ublock off

<img width="747" alt="Screen Shot 2019-03-11 at 3 10 16 PM" src="https://user-images.githubusercontent.com/8801492/54161617-f1985000-440f-11e9-96be-60b5c3fe185b.png">

### Versions

- Browser/version: macOS  Chrome 72.0.3626.121 (Official Build) (64-bit)
- uBlock Origin version: 1.18.4

### Settings

- Default settings

### Notes

(This is a copy of 'https://github.com/uBlockOrigin/uAssets/issues/5114' which I submitted to the wrong project)

**Comment by Khrin** [comment]
Hi, EasyPrivacy has been fixed and your should be able to see it in a few minutes or so. If you may encounter further issues about this page, please report them here.
