### ISSUE TITLE
WordCamp Sponsors

### ISSUE THREAD

**Issue by sbrinley** [easylist/easylist#303]
Problem: Sponsor Logos are being blocked on WordCamp sites.

Request: WordCamps are non-profit events. We keep tickets at or below $40 for a 2-day conference that often includes lunch and dozens of educational sessions put on by some of the best in the WordPress industry. We keep these prices low due to the generosity of sponsors.

Although these logos have a promotional aspect, I do not believe they are what one would consider a traditional advertisement. It's also detrimental to the conference because it appears they can't even get the backing of a single sponsor.

I have used ad blocking software for years and it never even crossed my mind that something like this would be marked as an ad.

Here's just one site where it's happening, although I know it's not the only one because it's a "stock" WordCamp template: https://2017.jacksonville.wordcamp.org/

**Comment by Khrin** [comment]
I'm sorry, but I haven't understood what you expect to do from us. Beside that, I think that this specific case can be covered by our policy: https://easylist.to/pages/policy.html

**Comment by sbrinley** [comment]
I was asking how this logo list can either be whitelisted, or what can be done so blocking doesn't affect functionality.

I'm reading your policy description and I don't see how these fall under the definition of an advert.

"The promotion of third party content in return for goods or services."

"**Promotion:** Specifying that an advert must promote means that a factual link (e.g. "Adblock Plus is a Firefox add-on.") cannot be an advert as it lacks a marketing aspect."

-- These logos link to another page on the website that give a factual description of the company or product. That sure sounds like a factual link to me.

"Third-party: The aim of a website is to entice people to read more of its content, which visitors presumably desire to do, as indicated by their presence on the domain; they should therefore not be hindered in doing so by a filter subscription. Whether websites are third-party or first-party (what happens if one person owns two domains?) is a question for the EasyList authors to consider."

-- These logo links are designed to entice people to read more of the content on the same website. So I don't see how they would fall under the category of "third party content."

Is the issue just that they are logos instead of plain-text links? If so, do you have a suggestion on how to revise our code so that when EasyList blocks the logos there are at least text-links available?
