### ISSUE TITLE
rt.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#3039]
### List the website(s) you're having issues:

`https://www.rt.com/news/449530-newsguard-edge-browser-media-integrated/`

### What happens?

Unblocked ads. These are similar to Outbrain and Taboola and should be blocked in EasyList because they are 3rd party ads.
e.g. `https://mixi.media/newdata/news?ad=6084141&bl=92026&ct=adpreview&st=37&ab=jsapi&bvuuid=597f2c96-6eba-4bed-9a50-1ad656c8c4a8&ag=25&ev=H4sIAAAAAAAAAOPiWbvmM9OqNV-Ynm3_zAQA0Pda_A4AAAA&rnd=683402`

To fix, add:
`rt.com##div.columns__content:has-text(/partners/i)`
or
`||mixi.media^$script,domain=rt.com`

### List Subscriptions you're using:

uBO default

### Your settings

- OS/version: Win 7
- Browser/version: Chrome 72
- Adblock Extension/version: uBO 1.18.4

### Other details:

![image](https://user-images.githubusercontent.com/12802056/54252724-39a79780-4522-11e9-9812-ec620ed9c337.png)

**Comment by terrorist96** [comment]
Also here: `https://www.theblaze.com/news/trump-shirt-triggers-gym-members`

**Comment by terrorist96** [comment]
@Khrin instead of giving a thumbs down, maybe explain how this is different from blocking outbrain and taboola? It's indistinguishable.

**Comment by krystian3w** [comment]
`rt.com#?#div.columns__content:-abp-contains(/partners/i)`

Adblock Plus 3.5 support simple regex.
