### ISSUE TITLE
api.coinmarketcap.com

### ISSUE THREAD

**Issue by rkbhochalya** [easylist/easylist#3040]
### List the website(s) you're having issues:

- `https://unblock.net/coins/`

### What happens?

Coin price chart doesn't load when using AdBlock. This is because EasyList blocks requests to CoinMarketCap API. In our case it's blocking a URL (`https://api.coinmarketcap.com/v1/ticker/?start=0&limit=100`) we use to fetch list of coins with data like price etc.

### List Subscriptions you're using:

- Acceptable Ads
- AdBlock custom filters
- Anti-Circumvention filters
- EasyList

### Your settings

- OS/version: macOS Mojave v10.14.3
- Browser/version: Chrome v72
- Adblock Extension/version: AdBlock v3.41.0

### Other details:

I think `||coinmarketcap.com^$third-party` line in the list is blocking the API requests and whitelisting `api.coinmarketcap.com` will fix the issue.

**Comment by rkbhochalya** [comment]
@ryanbr I'm curious to know why you closed the issue or better if you can help me understand why the pull request was closed initially?

**Comment by dukei** [comment]
Hey, really, why are you closing it? I doubt api.coinmarketcap.com does anything with ads. It is developer api. Blocking it breaks a lot of legitimate functionality.

It should be unblocked!
