### ISSUE TITLE
www.lnk.lt [Video Ads] Nano Defender+Adblock

### ISSUE THREAD

**Issue by Kissel2** [easylist/easylist#3045]
### List the website(s) you're having issues:

Pre-roll and mid-roll ads on all videos (for example: https://lnk.lt/video/daugiau-skerso-5-serija/59191)
### What happens?

Doesn't block ads
### List Subscriptions you're using:

Used latest AAK, however deleted and now using Nano Defender+Adblock, tried both not working. Blocks ads on other sites well
### Your settings

- OS/version: Windows 10
- Browser/version: Chrome
- Adblock Extension/version:  Nano Adblock with Nano Defender

**Comment by ryanbr** [comment]
Not English, but this generic filter might help.
