### ISSUE TITLE
prestigedigital.net

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#3087]
`https://www.prestigedigital.net/`

Unblocked doubleclick banner ad.

![image](https://user-images.githubusercontent.com/12802056/54480694-fee37f00-4801-11e9-8d58-f83f88e02b2f.png)

add
`prestigedigital.net##[href^="http://googleads.g.doubleclick.net/pcs/click"]`

https://github.com/uBlockOrigin/uAssets/issues/5143

**Comment by LiveChief** [comment]
create a pull request instead of a issue.

**Comment by terrorist96** [comment]
I don't know where in the list it should be added.

**Comment by LiveChief** [comment]
anywhere in the list.
