### ISSUE TITLE
Spotify web player

### ISSUE THREAD

**Issue by Paviluf** [easylist/easylist#309]
Hello,

Spotify have updated their web player and now the ads are not blocked.
https://open.spotify.com

It seem that we need something like that 
https://forums.lanik.us/viewtopic.php?p=113074#p113074
https://forums.lanik.us/viewtopic.php?f=62&t=34344

Thanks !

**Comment by SMed79** [comment]
Hi, 
If you want to help, [submit an adblock plus](https://adblockplus.org/getting_started#false-negatives) report and post here the link.

**Comment by Paviluf** [comment]
It has been added https://github.com/easylist/easylist/commit/28d2bc4010b5db124187cade260cd5f8de5a2177
Thanks !
