### ISSUE TITLE
https://app.intercom.io

### ISSUE THREAD

**Issue by Landsil** [easylist/easylist#3096]
### List the website(s) you're having issues:
`https://app.intercom.io`

### What happens?
Both intercom chat on websites and intercom backend get blocked.
eg. my company is using uBlock Origin and most people had to manually whitelist page to be able to log in to the system and work.

### List Subscriptions you're using:

uBlock Origin with default settings
EasyPrivacy filter in ON by default.

## System
Issue present on multiple devices on ChromeOS
72.0.3626.122
73.0.3683.32
71.0.3578.127

MacOS
10.14.3

## Ad Blocker
uBlock Origin
1.18.8

**Comment by smed79** [comment]
@ryanbr @okiehsch fyi.

**Comment by okiehsch** [comment]
`https://app.intercom.io` is not broken because of `EasyPrivacy`. 
`Peter Lowe’s` list was causing the issue updating `uBO-unbreak` should work.

**Comment by Landsil** [comment]
FYI
When issue was present it required both allowing links to work (info on ublock page about `Peter Lowe’s list`) and after that whitelisting URL (info on warning page about `EasyPrivacy`)
I can find screenshots I was send if you wish.

anyway
No longer an issue for me as we moved to custom managed setup and are controlling whitelist globaliy. Most companies probably won't be able to do that tho.

**Comment by pgl** [comment]
`intercom.io` has been removed from my list, after an enquiry on Twitter.
