### ISSUE TITLE
Line starts with comma and adds empty domain rule

### ISSUE THREAD

**Issue by laura-barluzzi** [easylist/easylist#3104]
### List the website(s) you're having issues:

N/A

### What happens?

Syntax error found in one of the latest (last week?) release changes.

In `easylist/easylist_specific_hide.txt` line 3904 the list of domains starts with a comma `,` instead of a domain.

How it is =                   `,1047.com.au, etc.`
How it should be =     `1047.com.au, etc.`

### List Subscriptions you're using:

N/A

### Your settings

N/A

### Other details:

N/A

**Comment by Khrin** [comment]
Thank you, fixed.
