### ISSUE TITLE
rambler.ru - Breaks the page [Fanboy's Social]

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#311]
http://weekend.rambler.ru/read/kak-pyut-i-ne-pyaneyut-razvedchiki-glavnye-sekrety-2017-03-12/

Breaks the page at the top due to the rule:
##.share__list

Add
May be? >
rambler.ru#@#.share__list
rambler.ru##.share__list > *

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/9c568667a5ac9bc980e0a1fd3ba610336cc49547
