### ISSUE TITLE
https://www.twitch.tv/dreamleague

### ISSUE THREAD

**Issue by Trance2000** [easylist/easylist#3113]
### List the website(s) you're having issues:

https://www.twitch.tv/dreamleague

### What happens?

Some video ads are getting loaded on twitch and the extension doesn't block them.

### Your settings

- OS/version: win7
- Browser/version: latest mozilla as of 3/20
- Adblock Extension/version: I am using nano adblocker and nano defender

**Comment by LiveChief** [comment]
hey u need to find out what website the ad is coming from and block the list, its literally next to impossible cause the ads are targeted to u, we have no idea what ad it is that u saw.

also try ublock origin and just block the ad domain.

**Comment by Trance2000** [comment]
Hey! Thanks!
