### ISSUE TITLE
destructoid.com is broken

### ISSUE THREAD

**Issue by destructoid1** [easylist/easylist#313]
Hello,
we have some broken features on our website with Adblock, all of our iframes and text boxes are been blocked.
broken pages:
`https://www.destructoid.com/userblog_edit_one_post.phtml `- can't edit
`https://www.destructoid.com/userblog_edit_one_post.phtml?pk=424866` - can't edit
`https://www.destructoid.com/` - click on any video link on any article
`https://www.destructoid.com/?chaos=ok` - upload photo icon is broken
`https://www.destructoid.com/quickpost_edit_one_post.phtml?pk=424867` - photo upload is broken

demouser:
Omitted

Thank you.

**Comment by Khrin** [comment]
You've already opened a thread in the forums, please stick to that one, no need to double post.

I've also modified your message and removed the credentials to prevent misuse.
