### ISSUE TITLE
(NSFW) youporngay.com

### ISSUE THREAD

**Issue by flyingzebras** [easylist/easylist#314]
These domains must be whitelisted to use the main page of `youporngay.com` (the layout is broken):

>fi1.ypncdn.com
>fi2.ypncdn.com

These EasyList filters should be extended:
>@@||ypncdn.com/cb/assets/js/$script,domain=youporn.com
>@@||ypncdn.com^$image,media,other,domain=youporn.com

to

>@@||ypncdn.com/cb/assets/js/$script,domain=youporn.com,youporngay.com
>@@||ypncdn.com^$image,media,other,domain=youporn.com,youporngay.com

**Comment by Khrin** [comment]
Should be fixed, please update EasyList.

**Comment by flyingzebras** [comment]
@Khrin Thank you.
