### ISSUE TITLE
?utm_content=*&utm_source=*&utm_$popup and opening reddit pages in new tab

### ISSUE THREAD

**Issue by eyalzek** [easylist/easylist#315]
Using `Chrome Version 52.0.2743.82 (64-bit)` on Ubuntu 16.04
uBlock origin 1.11.4

and the following version of `EasyList`:

```
[Adblock Plus 1.1]
! Version: 201703131809
! Title: EasyPrivacy
! Last modified: 13 Mar 2017 18:09 UTC
! Expires: 4 days (update frequency)
! Homepage: https://easylist.to/
! Licence: https://easylist.to/pages/licence.html
```

A problem I started seeing recently is that I can't use my middle mouse button to open new tabs on reddit anymore. The tab attempts to open and is then immediately closed.
I'm using uBlock and checked the log while I was trying to open a new tab, and saw the following:

![image](https://cloud.githubusercontent.com/assets/6243438/23946765/04294e34-097c-11e7-8e1a-31c064131993.png)

```
Static filter ?utm_content=*&utm_source=*&utm_$popup found in:
EasyList
```

Is there a way to disable a single entry in the filter list instead of disabling it altogether?

BTW, this behavior is specific to using the middle mouse button, right clicking and `open in a new tab` still works well.

**Comment by ahjorth** [comment]
This was fixed I believe. Try refreshing your lists

**Comment by eyalzek** [comment]
Indeed, thanks !
