### ISSUE TITLE
kfc.pl - tracker

### ISSUE THREAD

**Issue by trackerless** [easylist/easylist#3159]
### List the website(s) you're having issues:
https://kfc.pl/main/home/news

### What happens?

Website uses *api.useinsider.com* to track user's data.

Rule:
`||api.useinsider.com`

Checked with newest lists.

**Comment by 3xploiton3** [comment]
use fanboy filter

![image](https://user-images.githubusercontent.com/19517680/55122573-02e09c80-5132-11e9-8804-514938253133.png)
