### ISSUE TITLE
Unblock clarity-*.js

### ISSUE THREAD

**Issue by youdz** [easylist/easylist#316]
Commit https://github.com/easylist/easylist/commit/cda0b2d61012d01f5d5ad7250376bfdda0645313 blocked `clarity-*.js` 8 days ago.

We have a UI library called [Clarity](https://vmware.github.io/clarity/) that has absolutely nothing to do with ads, and we've been open source for months now. Our library is now being blocked on professional web applications and completely prevents them from loading. Could you either unblock us, or at least use a stricter match that would not impact us?

Thank you.

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=35937

**Comment by jaffoneh** [comment]
@SMed79 thanks for the quick response.

Changing the name does not actually help considering the fact many applications already use our library in production applications already. Anyway we can make a change to unblock clarity-*.js? We're happy to help and collaborate on this but considering the name change could break applications and would not solve the issues for already production-ready applications, is there anything we can work on together here?

**Comment by SMed79** [comment]
> Not much can be changed to fix this

https://forums.lanik.us/viewtopic.php?p=114914#p114914
