### ISSUE TITLE
Dagbladet.no - Blocked videos (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3175]
### Affected site:
`https://www.dagbladet.no/`

### Issue:
Blocked script results in broken video playback (black video window).

### Example:
`https://www.dagbladet.no/video/apen-tar-sats-fra-50-meters-hoyde/RpTk8PKW`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyList

### Problem rules:
```
/prebid-
/prebid.$script,domain=~prebid.org
```

### Blocked script:
`https://www.dagbladet.no/_next/static/prebid-2.6.0/prebid.js`

### Possible fix:
`@@||dagbladet.no/_next/static/prebid-$script`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by ryanbr** [comment]
Works fine here.

**Comment by THEtomaso** [comment]
Indeed, **prebid.js** is no longer required.
