### ISSUE TITLE
masn.com unblocked ad box

### ISSUE THREAD

**Issue by yourduskquibbles** [easylist/easylist#3178]
### List the website(s) you're having issues:

`http://www.masnsports.com/shows-and-programming/`

### What happens?

Unblocked ad frame. 

Adding `masnsports.com##.sidebar-advert` fixes the issue

See screenshot below.
![masn](https://user-images.githubusercontent.com/22258847/55495949-febdee80-560b-11e9-95e7-ebc0f6a02e08.png)

### List Subscriptions you're using:

- Default uBlock Origin lists + uBlock filters - Annoyances & uBlock filters Experimental.

### Your settings

- Chrome test profile with default uBlock Origin settings and lists + uBlock Annoyances & uBlock Experimental Lists.
- OS/version: Windows 10 64bit
- Browser/version: Chrome Version 74.0.3729.40 (Official Build) beta (64-bit)
- Adblock Extension/version: uBlock Origin 1.18.17b0 (Latest Dev Build)

**Comment by LiveChief** [comment]
PULL REQUEST.
