### ISSUE TITLE
misuse of document option

### ISSUE THREAD

**Issue by stream009** [easylist/easylist#3183]
Although [description on website](https://adblockplus.org/filters#options) is little vague, document option can only be used for disabling other blocking filter.

But recently there are increasing number of filters that use document option in ordinal blocking filter (not in exception filter).

For example this [commit](https://github.com/easylist/easylist/commit/15276076f144a2cfcbd817f6d6984b921dae0741).
`||abbp1.com^$document`
If this filter's intention is blocking top-level document which domain is abbp1.com, it won't work at least on Adblock Plus.

I can identify 29 filters that match this description.
Are there any other intention that I am not aware of?

**Comment by monzta** [comment]
I think it works in uBlock Origin: https://github.com/gorhill/uBlock/wiki/Strict-blocking

**Comment by stream009** [comment]
Yes, but uBlock block whole web page without "document" option.

**Comment by ryanbr** [comment]
Why are you complaining of blocking an adserver?
