### ISSUE TITLE
https://en.wiktionary.org/wiki/ads

### ISSUE THREAD

**Issue by mk-pmb** [easylist/easylist#3188]
### List the website(s) you're having issues:

```text
https://en.wiktionary.org/wiki/ads
https://en.wiktionary.org/wiki/advert
https://de.wiktionary.org/wiki/advert
```

### What happens?

The main content area of the dictionary seems missing.

Since the rule is `##.page-ads`, it likely affects lots of other wiki pages that happen to use a CSS class based on the page name.

### List Subscriptions you're using:

`easylist/easylist_general_hide.txt` affected since b34682f617ec02b3365aedd237452dfd9cc9da2d

### Your settings

skipped because the rule is obviously overly general.

### Other details:

Reporting on behalf of the affected user. [Original IRC log](https://wm-bot.wmflabs.org/logs/%23wikimedia-tech/20190404.txt)

**Comment by RhinosF1** [comment]
Hi, I'm part of the team on IRC that reported it

https://help.getadblock.com/support/tickets/62765 was filed at first during investagations and is now closed.

https://en.wiktionary.org/w/index.php?title=Wiktionary:Information_desk/2019/April is also a discussion on it

**Comment by mk-pmb** [comment]
Adjusted title because the other pages are blanked by similar but different rules. Unfortunately, Github blame seems to not work for me atm.

**Comment by Khrin** [comment]
This will fix the issue.

**Comment by RhinosF1** [comment]
@Khrin  Thanks!!!

**Comment by RhinosF1** [comment]
How long for adblockers to start pushing this @Khrin ?

**Comment by Khrin** [comment]
Change is already live. All adblockers should get the update in a few days.

**Comment by RhinosF1** [comment]
Thanks, Fix live for me
