### ISSUE TITLE
EpicGames.com - Unable to shop at store (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3189]
### Affected site:
`https://www.epicgames.com/store/`

### Issue:
Unable to shop at store.
Gets stuck at "Loading your order...".

### Screenshots:
* **Screenshot 1 (stuck page):**

![filterissue-epicgames1](https://user-images.githubusercontent.com/9382674/55572634-50e43a00-5708-11e9-8b3f-69a8fd183a6e.jpg)

* **Screenshot 2 (uBO logger):**

![filterissue-epicgames2](https://user-images.githubusercontent.com/9382674/55572651-59d50b80-5708-11e9-9112-3538fb671048.jpg)

### Problem filter:
* EasyPrivacy

### Problem rule:
`||tracking.epicgames.com^`

### Blocked script:
`https://tracking.epicgames.com/tracking.js`

### Possible fixes (confirmed working):
* Alternative 1:
Delete the problem rule (since it's probably not used for any third party tracking anyway).

* Alternative 2:
Make an exception rule:
`@@||tracking.epicgames.com/tracking.js$~third-party`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by krystian3w** [comment]
`~third-party`

**Comment by THEtomaso** [comment]
Why?

**Comment by krystian3w** [comment]
Alternative 4 = Alternative 5 (I used only syntax property with Adblock Plus 3.5).

Also 2 = 3 (only syntax changed).

**Comment by THEtomaso** [comment]
Oh, so you mean that the `first-party` syntax isn't compatible with ABP 3.5, but `third-party` is?

**Comment by krystian3w** [comment]
Yes, this is syntax added to AdGuard / uBO.

**Comment by THEtomaso** [comment]
'**uBlock filters**', '**uBlock filters - Annoyances**' and '**uBlock filters - Unbreak**' uses both the `first-party` and `third-party` syntaxes.
Just look inside the filters yourself.

But indeed, the `first-party` syntax doesn't seem to be used in most other filters.
This is something that I was unaware of.

_**first post edited**_

**Comment by krystian3w** [comment]
Now used shortest syntax:

> `1p` /  `3p`



1p - first-party - in Adblock Plus syntax `~third-party` for Adblock Plus company is no needed add `first-party`.

3p - third-party

**Comment by THEtomaso** [comment]
> `1p` / `3p`

Yeah, I'm aware of those, but I like the long versions better, as they're easier to understand for newbies. :)
And except for the different uBO filters, I really don't see any other filters using those short versions either.

**Comment by Yuki2718** [comment]
@THEtomaso I readded the rule without noticint this issue, is it still the case?

**Comment by THEtomaso** [comment]
At least, I can confirm that it doesn't get stuck at "Loading your order...", like before. :)

Anyway, to properly block it in uBO, you need to add `$important` to your blocking rule, since **uBlock filters - Unbreak** has this:
`@@||tracking.epicgames.com/tracking.js$1p`

**Comment by Yuki2718** [comment]
I'll revert the change. https://www.reddit.com/r/uBlockOrigin/comments/b9ns52/cant_purchase_games_on_epic_game_store_while_this/ says a problem in purchase which I can't check although it is 5 years ago.
