### ISSUE TITLE
Opening bravesouls.fyi pages in new tab

### ISSUE THREAD

**Issue by Brazuca87** [easylist/easylist#319]
Starting earlier this week, opening links as new tabs (middle click, ctrl+click, right click+new tab) on bravesouls.fyi started to close the new tab after load.

Is there any way to find out what is causing it? And if so, could it be fixed without having to whitelist the whole domain?

[Adblock Plus 2.0]
! Version: 201703161753
! Title: EasyList
! Last modified: 16 Mar 2017 17:53 UTC
! Expires: 4 days (update frequency)
! Homepage: https://easylist.to/
! Licence: https://easylist.to/pages/licence.html

**Comment by Brazuca87** [comment]
Ok, finally managed to figure out whats causing it...

    ||googleads.g.doubleclick.net^$popup,third-party

Is this supposed to cause this behavior for new tabs?

**Comment by SMed79** [comment]
It's a bug... fixed in the last dev build https://chrome.google.com/webstore/detail/adblock-plus-development/ldcecbkkoecffmfljeihcmifjjdoepkn

source: https://adblockplus.org/forum/viewtopic.php?p=167133#p167133
