### ISSUE TITLE
medicalnewstoday.com unblocked ad frames

### ISSUE THREAD

**Issue by yourduskquibbles** [easylist/easylist#3192]
### List the website(s) you're having issues:

`https://www.medicalnewstoday.com/articles/324852.php`

### What happens?

Unblocked ad frames all over page

Adding the following filters fix the issue for me

```
medicalnewstoday.com##[id^="dlb"]
medicalnewstoday.com##[id^="dmr"]
medicalnewstoday.com##.css_h1ksn
```

See screenshot below.
![medicalnewstoday](https://user-images.githubusercontent.com/22258847/55629617-a0b31780-5781-11e9-801e-ce449d8cbc45.png)

### List Subscriptions you're using:

- Default uBlock Origin lists + uBlock filters - Annoyances & uBlock filters Experimental.

### Your settings

- Chrome test profile with default uBlock Origin settings and lists + uBlock Annoyances & uBlock Experimental Lists.
- OS/version: Windows 10 64bit
- Browser/version: Chrome Version 74.0.3729.61 (Official Build) beta (64-bit)
- Adblock Extension/version: uBlock Origin 1.18.17b1 (Latest Dev Build)

### Other details:

```
medicalnewstoday.com##[id^="dlb"]
medicalnewstoday.com##[id^="dmr"]
medicalnewstoday.com##.css_h1ksn
```

**Comment by krystian3w** [comment]
`.css_h1ksn` how long stable class?

**Comment by yourduskquibbles** [comment]
> 
> 
> `.css_h1ksn` how long stable class?

Good question.. but I didn't see an immediately better option besides `##hr` which could break the site somewhere else or using uBO extended syntax that EasyList doesn't support.

**Comment by krystian3w** [comment]
IMO maybe scriplet add into maybe help? https://github.com/abp-filters/abp-filters-anti-cv

**Comment by Khrin** [comment]
I don't see any possible solution to hide these blank spaces.

**Comment by yourduskquibbles** [comment]
@Khrin the two `##[id^=""]` filters below at least hides the sidebar ad and "Advertisement" text in sidebar and header - how about at least adding those? The empty page header can be killed in uBO extended filters without using a random class name that is likely to change.


`medicalnewstoday.com##[id^="dlb"]` - Hides header advertisement text
`medicalnewstoday.com##[id^="dmr"]` - hides sidebar advertisement block completely

**Comment by krystian3w** [comment]
Too generic? Or now works for **Khrin**.

Try report to uAsset and anti-cv repositories.

**Comment by yourduskquibbles** [comment]
> 
> 
> Too generic? Or now no works for **Khrin**.
> 
> Try report to uAsset and anti-cv repositories.

I can add these to uAsset but they only cover uBlock users.

```
medicalnewstoday.com##div:matches-css-before(content: "advertisement")
medicalnewstoday.com##hr:matches-css(height: 125px)
```
