### ISSUE TITLE
http://cannabisjobs.us/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#32]
`http://cannabisjobs.us/`

Our Sponsors section

`http://cannabisjobs.us/cannabis-news/`

Check out our friends

`http://cannabisjobs.us/jobs/`

Lawyer ads under the "friends" ads

**Comment by monzta** [comment]
> Our Sponsors section

Would rather consider this as part of the page since it's linked at the top right. 

Added https://github.com/easylist/easylist/commit/7551a63e232135a921bc269fc58a1a2ea0f8b356 & https://github.com/easylist/easylist/commit/a67212e0ed06cd6284603673432ddd6f37cfc264

**Comment by terrorist96** [comment]
@monzta I see "OC Weed Review" ad on the right
`http://cannabisjobs.us/cannabis-news/`

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/192a38079b824f836fc4bfd3006c537088fca58d
