### ISSUE TITLE
Broken Advertising Guidelines page on WeTransfer.com

### ISSUE THREAD

**Issue by manpreetssethi** [easylist/easylist#320]
Navigating to Advertising Guidelines from this [page](https://manpreet.wetransfer.com/advertise) using the button below, results in the page being blocked. Is there a way to whitelist https://wetransfer.com/advertise/guidelines ?

<img width="302" alt="screen shot 2017-03-17 at 10 15 36" src="https://cloud.githubusercontent.com/assets/2006753/24036639/b1c1fdc8-0afa-11e7-9ba4-379a034963b4.png">

My browser details;
[browser_details.pdf](https://github.com/easylist/easylist/files/850092/export.pdf)

**Comment by manpreetssethi** [comment]
uBlock Origin's logger;
<img width="1437" alt="screen shot 2017-03-17 at 10 21 54" src="https://cloud.githubusercontent.com/assets/2006753/24036806/9442045e-0afb-11e7-8617-c4c899089057.png">

**Comment by SMed79** [comment]
add
`@@||manpreet.wetransfer.com/advertise/guidelines$xmlhttprequest`

**Comment by manpreetssethi** [comment]
@SMed79 https://github.com/easylist/easylist/pull/332

**Comment by manpreetssethi** [comment]
@SMed79 Sorry about being naive, but when you mean "add ...", where exactly did you want me to add the rule?
I did open a PR https://github.com/easylist/easylist/pull/332, but doesn't look like it's acceptable.

Please let me know, thanks!

**Comment by SMed79** [comment]
Wait an easylist author see this issue (& commit) and decide what to do.

**Comment by manpreetssethi** [comment]
@SMed79 thanks for the update.
