### ISSUE TITLE
jewishreviewofbooks.com unblocked ad frames

### ISSUE THREAD

**Issue by yourduskquibbles** [easylist/easylist#3229]
### List the website(s) you're having issues:

`https://jewishreviewofbooks.com/`

### What happens?

Unblocked header ad frame & ad frame in homepage

`jewishreviewofbooks.com###banner-classified` removes header ad box
`jewishreviewofbooks.com###sidebar-classified` removes ad box in main page

See screenshot below.

Header ad box
![jewishreview](https://user-images.githubusercontent.com/22258847/55902177-efedb380-5b98-11e9-8707-aca560eefe9f.png)

Homepage ad box
![jewishreview2](https://user-images.githubusercontent.com/22258847/55902625-f29cd880-5b99-11e9-9c7f-395753293aad.png)

### List Subscriptions you're using:

- Default uBlock Origin lists + uBlock filters - Annoyances & uBlock filters Experimental.

### Your settings

- Chrome test profile with default uBlock Origin settings and lists + uBlock Annoyances & uBlock Experimental Lists.
- OS/version: Windows 10 64bit
- Browser/version: Chrome Version 74.0.3729.61 (Official Build) beta (64-bit)
- Adblock Extension/version: uBlock Origin 1.18.17b1 (Latest Dev Build)

### Other details:

`jewishreviewofbooks.com###banner-classified`
`jewishreviewofbooks.com###sidebar-classified`

**Comment by ryanbr** [comment]
only saw this; https://github.com/easylist/easylist/commit/75880bbb393e528a7d27fe0eba93c3fe7e102aa7
