### ISSUE TITLE
AnimeFever.tv detects the adblocker and stops video

### ISSUE THREAD

**Issue by Vadyy** [easylist/easylist#3230]
### List the website(s) you're having issues:

`https://www.animefever.tv/anime/2224/one-punch-man-2/episode/42622 `

placed the link to the video instead because that is where the anti-adblocking thing starts

### What happens?

1. Visit Site
2. Click an Anime and choose an episode
3. Instead of player starting the episode, it stops and tells you to disable adblock.

### List Subscriptions you're using:

default from uorigin and default lists from nano defender

### Your settings

- Windows 10 Home / version 1803
- Google Chrome 73.0.3683.103
- uBlock Origin v1.18.16

**Comment by THEtomaso** [comment]
Possible fix:
`@@||animefever.tv/themes/app/static/js/adsbygoogle.js$xmlhttprequest`

**Comment by THEtomaso** [comment]
Adding the fix to **Fanboy's Enhanced Tracking List** leaves it unavailable for a lot of people.

@okiehsch:
Perhaps you could add it to **uBlock filters – Unbreak** too?

PS:
`$xmlhttprequest` (which I used for the suggested fix in my previous post) doesn't seem to work anymore in this case.
It now needs to be `@@||animefever.tv/themes/app/static/js/adsbygoogle.js`

**Comment by ryanbr** [comment]
Easylist hasn't added Anti-adblock for a while.
