### ISSUE TITLE
https://www.vvvvid.it

### ISSUE THREAD

**Issue by Mautriz** [easylist/easylist#3234]
### What happens? 

ads working anyways

### List Subscriptions you're using: 

just got nano adblocker + nano defender

### Your settings

didnt touch anything o_O

- OS/version: Windows 10
- Browser/version:  Chrome
- Adblock Extension/version:  the last one, i downloaded it like 10 mins ago
1.0.0.103
nano defend 15.0.0.125

**Comment by simoneconfalonieri** [comment]
Same on FF with uBlock Origin

**Comment by simoconfa** [comment]
Same on FF with uBlock Origin

**Comment by simoconfa** [comment]
Actually to remove vvvvid ads you have to add these filters:
```
flashondemand.top-ix.org/*
or01.top-ix.org/*
```

**Comment by peace2000** [comment]
This site is only available to Italy. Maybe better to report this to the upkeepers of the Italian list?

@Khrin ?

**Comment by Khrin** [comment]
Videos are behind an Anti Adblock wall, I guess they have disabled/whitelist something, thus allowing ads.

`top-ix.org` is a content delivery network service.
