### ISSUE TITLE
http://www.arkansasmatters.com/ social list false positive

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#324]
http://www.arkansasmatters.com/news/local-news/arkansas-college-plans-to-opt-out-of-controversial-campus-carry-bill/673347079

Social list blocks the info at the top of the article:
By: Jessi Turnure 
Posted: Mar 16, 2017 10:50 PM CDT
Updated: Mar 16, 2017 10:54 PM CDT

**Comment by THEtomaso** [comment]
### Confirmed problem filters:
* AdGuard Social Media filter
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

### Problem rule:
`##.meta-share`

### Possible fixes:
```
arkansasmatters.com#@#.meta-share
kark.com#@#.meta-share
```

### Note:
This is not the right place to report this issue.
Report here instead:
https://github.com/AdguardTeam/AdguardFilters/issues/
..and here:
https://github.com/ryanbr/fanboy-adblock/issues/

**Comment by terrorist96** [comment]
I don't care anymore. I stopped using Social list. Too many false positives. Not worth it.

**Comment by ryanbr** [comment]
With the social list, it'll touch many parts of site. in a good or bad way. I can't please everyone.
