### ISSUE TITLE
NPR podcasts hosted at adswizz.com being blocked

### ISSUE THREAD

**Issue by mica** [easylist/easylist#3261]
Planet Money apparently hosts their podcast at the URL of an ad company, and Easylist won't allow the mp3s to play. Trying from here: https://player.fm/series/series-1324387

**Comment by THEtomaso** [comment]
Summary:

### Problem filter:
* EasyPrivacy

### Problem rule:
`||adswizz.com^$third-party`

### Possible fix:
`@@||adswizz.com^$third-party,domain=player.fm`

### Note:
The above exception rule will also allow a short commercial to play before the actual audio tracks, so a more sophisticated fix would be preferable.

### Other problem filters:
* hpHosts' Ad and tracking servers
* Peter Lowe's Ad and tracking server list
(Blocking rule: `adswizz.com`)

**Comment by pgl** [comment]
I'm afraid I won't be removing `adswizz.com`, as it doesn't contain any non-ad-related content.

**Comment by THEtomaso** [comment]
That's not correct, as they're clearly hosting the audio streams for `player.fm`.

**Comment by pgl** [comment]
No, they're just preventing the audio streams from actually loading first.

**Comment by THEtomaso** [comment]
Some examples (from the link provided by the OP):
```
https://play.podtrac.com/npr-510289/npr.streaming.adswizz.com/anon.npr-mp3/npr/pmoney/2019/04/20190412_pmoney_pmpod906v2.mp3
https://npr.streaming.adswizz.com/anon.npr-mp3/npr/pmoney/2019/04/20190412_pmoney_pmpod906v2.mp3
https://cf-npr.streaming.adswizz.com/anon.npr-mp3/npr/pmoney/2019/04/20190412_pmoney_pmpod906v2.mp3
```

The first one is hosted @ `podtrac.com`, while the other two are hosted @ `adswizz.com`.
The two hosted @ `adswizz.com` are the same streams, only the first one comes WITH a pre-roll ad, and the last one comes WITHOUT!
..so I guess it should be possible to create a rule which avoids those things?

**Comment by Khrin** [comment]
let's just say that's another dishonest trick to forcing adblocking disabled on their sites . main filter is there to stay and will not be removed

**Comment by THEtomaso** [comment]
@Khrin:

You've put the exception rule in the wrong filter.
As you can see in my first post, it belongs in '**EasyPrivacy**', not in '**EasyList**'!

Also, your rule doesn't work for all streams.
You only made an exception for `streaming.adswizz.com/anon.npr-mp3/npr/`, but many streams are hosted at different locations.
This can be tested by clicking on the different streams, at the page which the OP linked to.
Some of them are hosted under `streaming.adswizz.com/anon.npr-podcasts/`.
But even if you include an exception for this address too, it will only cover streams from "npr".
`player.fm` provides streams from many others!
Use the exception rule which I provided in my first post instead!

**Comment by Khrin** [comment]
I won't, because it's too much broad. This is a known Ads server.

**Comment by THEtomaso** [comment]
@okiehsch:
Something for '**uBlock filters - Unbreak**' then perhaps?
In case you're wondering; there doesn't seem to be any connections to `adswizz.com`, unless you actively choose to play the streams, by clicking on the Play buttons (in which case the connection is absolutely necessary)!

**Comment by okiehsch** [comment]
@THEtomaso do you have links to non-npr podcasts with the same issue?

@Khrin you could add the same filter for `podbay.fm` because it has the same issue
Example link: `http://podbay.fm/show/121493675/e/1555369200?autostart=1`

`@@||adswizz.com/anon.npr-mp3/*$media,domain=podbay.fm` works on my end.

**Comment by THEtomaso** [comment]
> do you have links to non-npr podcasts with the same issue?

No, but if NPR is hosting their streams at `adswizz.com`, other probably does too.

--

> `@@||adswizz.com/anon.npr-mp3/*$media,domain=podbay.fm` works on my end.

Doesn't work at my end, because like I pointed out earlier; the streams are located at different sub-addresses.

Example:
`http://podbay.fm/show/121493675/e/1555376400?autostart=1`
In this case, the request is directed @ `https://npr.streaming.adswizz.com/anon.npr-mp3/npr/newscasts/2019/04/15/newscast200802.mp3`
So again; the exception rule should rather be `@@||adswizz.com^$third-party,domain=podbay.fm`, to cover all possibillities.
(PS: I don't know why, but the $media syntax can't be used in this case)

**Comment by okiehsch** [comment]
> Doesn't work at my end, because like I pointed out earlier; the streams are located at different sub-addresses.
Example:
http://podbay.fm/show/121493675/e/1555376400?autostart=1

Works fine on my end

![image](https://user-images.githubusercontent.com/16838044/56175669-82a6ac00-5ff8-11e9-8152-c398e01bfb88.png)

**Comment by THEtomaso** [comment]
I can confirm that it works for Chromium browsers, but not for Pale Moon.
Perhaps it's a uBO Legacy issue?
What's even more weird, is that the `$media` syntax works just fine in Pale Moon too @ `player.fm`, but NOT @ `podbay.fm`!

**Comment by okiehsch** [comment]
Works with Firefox too, so this is a PaleMoon issue, can you post a screenshot of the blocked request.

**Comment by THEtomaso** [comment]
![filterissue-podbayfm1](https://user-images.githubusercontent.com/9382674/56176511-9ef81800-5ffb-11e9-864c-20946a7e73a7.jpg)

![filterissue-podbayfm2](https://user-images.githubusercontent.com/9382674/56176512-9ef81800-5ffb-11e9-9ea2-440e603c987c.jpg)

**Comment by okiehsch** [comment]
Well, there is the reason for your problem PaleMoon does not see the request as a media request at all.

`@@||adswizz.com/anon.npr-mp3/*$object,domain=podbay.fm`
should work for you.

**Comment by THEtomaso** [comment]
> `@@||adswizz.com/anon.npr-mp3/*$object,domain=podbay.fm`
> should work for you.

Yes, that works,
But why does `$media` work for `player.fm`, but not for `podbay.fm`?

**Comment by okiehsch** [comment]
I don't know there is no difference with Chromium or Firefox.
Anyway I added the filter to the legacy list.

**Comment by THEtomaso** [comment]
Look at the examples that I posted here:
https://github.com/easylist/easylist/issues/3261#issuecomment-483278077
This demonstrates what I've been trying to point out about different sub-addresses!

One rule to fix all!:
`@@||adswizz.com^$third-party,domain=player.fm|podbay.fm`
Like I said; there are no connection requets to `adswizz.com`, unsless they're actually needed for audio playback, so I don't see any downsides of formulating the rule in this manner.

**Comment by okiehsch** [comment]
> Look at the examples that I posted here:
#3261 (comment)

I don't understand your point
````
@@||adswizz.com^$third-party,domain=player.fm|podbay.fm
````
will not work with the posted links.

**Comment by THEtomaso** [comment]
Khrin's fix won't work for all streams, as the rule is too specific.
..so you should include an exception for `player.fm` too.

**Comment by THEtomaso** [comment]
> `@@||adswizz.com^$third-party,domain=player.fm|podbay.fm`
> will not work with the posted links.

What do you mean?
This fixes the issue for every single stream, for all browsers, both at `player.fm` and `podbay.fm`!
Since Khrin has refused to properly fix the issue, this exception rule should be added to 'uBlock filters - Unbreak', IMO.

**Comment by okiehsch** [comment]
You linked to this comment https://github.com/easylist/easylist/issues/3261#issuecomment-483278077
The links included in that comment are not working.

> Since Khrin has refused to properly fix the issue,

I will add a filter if anybody can provide a `player.fm` link that is broken

**Comment by pgl** [comment]
For the record, NPR are apparently not aware of this issue (well, they should be now because I've updated them). Response from Khalon at NPR:

> We have recently switched server platforms for some podcasts but this will have no effect whatsoever on videos on npr.org.

**Comment by THEtomaso** [comment]
> I will add a filter if anybody can provide a `player.fm` link that is broken

This won't work without an exception rule:
`http://podbay.fm/show/121493675/e/1555405200?autostart=1`
..but the fix is in uBOs **Legacy** filter, although it easely could cover all browsers from the **Unbreak** filter!

**Comment by THEtomaso** [comment]
> I will add a filter if anybody can provide a player.fm link that is broken

Simply go to the page which the OP linked to..
Khrin's fix only covers some of the streams.
Amongst the ones that are broken are number 4, 7, 11, as they're hosted at a slightly different location.

**Comment by pgl** [comment]
Update from NPR:

> We are reaching back out to let you know that we've issued a fix and you should no longer be experiencing this issue.

> Please let us know if you know if you continue to experience this issue so that we may investigate further.
