### ISSUE TITLE
classicreload.com

### ISSUE THREAD

**Issue by PoRtvine** [easylist/easylist#3264]
### List the website(s) you're having issues:

`https://classicreload.com/win3x-windows-31.html`

### What happens?

AdBlock detected
![Безымянный](https://user-images.githubusercontent.com/28482376/56111910-209b6780-5f62-11e9-8929-9e9b6670a78f.png)

### List Subscriptions you're using:

![55939052-78c22900-5c45-11e9-82f9-7928c96b9bdd](https://user-images.githubusercontent.com/28482376/56111859-fb0e5e00-5f61-11e9-9ae5-bb41affbcfde.png)

OS/version: Windows 7x64
Browser/version: Opera|Beta x64
Adblock Extension/version: uBO 1.18.17b1

### 
`@@||classicreload.com^$generichide 
 @@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=classicreload.com`

**Comment by ryanbr** [comment]
Easylist won't fix anti-adblocks.
