### ISSUE TITLE
bibme.org

### ISSUE THREAD

**Issue by ssood-chegg** [easylist/easylist#3274]
### List the website(s) you're having issues:
`https://writing.bibme.org/`

### What happens?
We are not able to establish websocket connections on `https://writing.bibme.org/` because it gets blocked by the adblocker. This will interfere with out core paper checking flows which rely on websockets. Since we do not serve ads over websockets on the site, and need it for our core flows, we just need to remove the site from the websocket filter.

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Mac OSX High Sierra 10.13.6
- Browser/version: Firefox 66.03
- Adblock Extension/version: Adblock Plus v3.5.1

### Other details:

Suspected Filter is
https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt#L5769
I've created a Pull Request to fix this, and tested this out locally.
https://github.com/easylist/easylist/pull/3256

**Comment by ryanbr** [comment]
**I don't serve ads**, but whats "https://epu.sh/ntfc.php?p=2528536&r=sw"

**Comment by ryanbr** [comment]
Closing, you need to fix your site.

**Comment by ryanbr** [comment]
Okay upon review, its been removed.
