### ISSUE TITLE
does'nt work on https://www.firstonetv.live

### ISSUE THREAD

**Issue by bladych** [easylist/easylist#3283]
https://www.firstonetv.live/Live/France/beIN-Sports-1-46

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Goodbye, finally.

FirstOne TV has discontinued his service.
It wasn't possible to offer you this service in a legal way without to disrupt copyright holders. Therefore this service is now closed finally.
