### ISSUE TITLE
Article text removed from arstechnica[dot]com

### ISSUE THREAD

**Issue by gatoraitor** [easylist/easylist#3284]
### List the website(s) you're having issues:

`arstechnica[dot]com`

### What happens?

Simple article text is removed when it's a link to amazon.com.  Depending on the size of the text in the link this can either be minimal or make a section of text difficult to read and understand.

### List Subscriptions you're using:

Easylist English

### Your settings

Only using Adblock Plus

- OS/version: macOS Mojave 10.14.4
- Browser/version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- Adblock Extension/version: Adblock Plus 3.5.1

### Other details:

Looks like it's coming from this filter specifically:

```
9to5google.com,9to5mac.com,9to5toys.com,ancient-origins.net,aol.co.uk,arstechnica.com,catholicculture.org,electrek.co,gamenguide.com,ign.com,indianexpress.com,lewrockwell.com,livescience.com,macworld.co.uk,marineelectronics.com,marinelink.com,marinetechnologynews.com,maritimejobs.com,maritimeprofessional.com,maritimepropulsion.com,myanimelist.net,oneangrygamer.net,parentherald.com,segmentnext.com,ssbcrack.com,yachtingjournal.com##a[href^="https://www.amazon."][href*="tag="]
```

**Comment by ryanbr** [comment]
Its fine here, and no ads seen or missing articles. you need to actually include a webpage,.

**Comment by gatoraitor** [comment]
Sorry, I guess I thought with the rule it would be clear that it's going to remove an entire tag if it's a match.  Here's a couple that I found.  I can grab some more if needed, can be difficult to track them down, I usually just notice it when I'm reading or someone points it out in the comments.

__URL:__
https://arstechnica.com/science/2019/05/no-someone-hasnt-cracked-the-code-of-the-mysterious-voynich-manuscript/

__Result:__
_Full sentence:_ 
"Given that Gibbs' main claim to fame before this article was a series of books about [how to write and sell television screenplays](https://www.amazon.com/dp/1444167596/?tag=arstech20-20), it seems that his goal in this research was probably to sell a television screenplay of his own."

_Truncated Sentence:_  
"Given that Gibbs' main claim to fame before this article was a series of books about , it seems that his goal in this research was probably to sell a television screenplay of his own."

__URL:__
https://arstechnica.com/science/2019/04/who-had-the-most-merciful-death-on-game-of-thrones-science-has-an-answer/

__Result:__
_Full sentence:_ 
These and other scintillating topics are discussed in a forthcoming book by physicist (and uber-fan) Rebecca Thompson, [Fire, Ice, and Physics: The Science of Game of Thrones](https://www.amazon.com/dp/0262043076/?tag=arstech20-20). 

_Truncated Sentence:_  
These and other scintillating topics are discussed in a forthcoming book by physicist (and uber-fan) Rebecca Thompson, .

The amount of text used in the link is what makes the difference between when it isn't really a problem and when something won't even make sense.
