### ISSUE TITLE
www.americanexpress.com

### ISSUE THREAD

**Issue by ndaesik** [easylist/easylist#3286]
Issued on; https://www.americanexpress.com/en-us/business/trends-and-insights/articles/7-tricks-to-help-you-remember-anything/

Issue : unblocked element in middle of article. ( #btiInlineBanner )

![image](https://user-images.githubusercontent.com/41130831/56333715-3f9f3100-61d0-11e9-8558-73ea86d1de40.png)

my setting : Windows 10 / latest version of Chrome / ublock origin

**Comment by Khrin** [comment]
I'm not sure what you meant with this issue report. Can you explain more what's the problem?

**Comment by ndaesik** [comment]
@Khrin sorry for being a newb, I just didn't wanted to spend much time for report one issue. 
I just edited the original post to give more detail, hope you tell me if it's not enough yet.

**Comment by Khrin** [comment]
Hi, first of all I want to apologize for my late reply. Having looked at the page, I don't think this link deserve to be blocked, because looks really like to be some kind of self-promotion, which usually isn't blocked by EasyList, even as in this case it's labelled as "Advertisement".
