### ISSUE TITLE
https://www.conservativereview.com/

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#33]
`https://www.conservativereview.com/`
`https://www.conservativereview.com/commentary/2016/06/hillary-hits-trumps-temperament-he-attacks-her-looks`

Levin ad on homepage three times (once in the banner at the top, two times in the body) and two times on article page (one in banner, one on right).

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/45f4bb830a3a1eaf010c75629d01879ce406a25b
