### ISSUE TITLE
ravenjs.com

### ISSUE THREAD

**Issue by davidhedlund** [easylist/easylist#334]
I think we should white list [https://github.com/getsentry/raven-js](raven-js).

https://cdn.ravenjs.com/3.12.1/raven.min.js is used by [viafree.se](https://www.viafree.se/program/reality/unga-mammor/sasong-1/avsnitt-16).

**Comment by monzta** [comment]
Why do you think it's being blocked? As far as I can see it's not.

**Comment by davidhedlund** [comment]
@monzta Its not blocked, but it's a CDN so having it white listed would be a good thing, because there are plenty of blocked CDN's.

**Comment by monzta** [comment]
There is no point in whitelisting it if it's not blocked.

**Comment by davidhedlund** [comment]
@monzta IMO there should be exceptions for this, like with CDN's, as they are widely used.

**Comment by Khrin** [comment]
But if it's not blocked, why we should whitelist this element? It's a nonsense.

Given that there isn't a real issue here, this conversation can be considered closed.
