### ISSUE TITLE
Pornhub streaming broken

### ISSUE THREAD

**Issue by brettph** [easylist/easylist#3343]
pornhub.com

Streaming doesn't work. We are moving to dash/hls streaming, the files need to be whitelisted by easylist. We're currently at 40% of users seeing dash/hls. If you press "Auto" in the quality control it won't be selectable. 

Need these added:
@@||phncdn.com/dash/videos/$media,object,object-subrequest,other,domain=pornhub.com|redtube.com|tube8.com|youporn.com|youporngay.com
@@||phncdn.com/hls/videos/$media,object,object-subrequest,other,domain=pornhub.com|redtube.com|tube8.com|youporn.com|youporngay.com

**Comment by monzta** [comment]
I tried to reproduce this (also with a US VPN) but it's playing fine. Any tips to reproduce this?

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/9efcc830fbb35277e6f25f1bb1b9bf52b63967ef
