### ISSUE TITLE
https://www.crunchyroll.com/

### ISSUE THREAD

**Issue by fuckyouadblockkiller** [easylist/easylist#3351]
### List the website(s) you're having issues:

`https://crunchyroll.com/domestic-girlfriend/episode-1-will-you-do-it-with-me-here-782110`

### What happens?

Ads still play despite adblock being enabled.

### Your settings

- OS/version: Windows 10.0.17134
- Browser/version: Google Chrome 73.0.3683.103
- Adblock Extension/version: Nano Adblocker 1.0.0.105, Nano Defender 15.0.0.139

**Comment by ryanbr** [comment]
No ads here, update and retest.
