### ISSUE TITLE
NO Image in article on hngn.com

### ISSUE THREAD

**Issue by TheYellowDog** [easylist/easylist#3352]
http://www.hngn.com/articles/227377/20190422/rurality-social-identity-is-driving-polarization-in-iowa.htm

### What happens?
No image in article

### List Subscriptions you're using:

EASYLIST

### Your settings

- OS/version: chrome
- Browser/version: 73.0
- Adblock Extension/version: ? last

**Comment by THEtomaso** [comment]
Summary:

### Problem filter:
* EasyList

### Problem rule:
`||stackpathdns.com^$image,domain=boomsbeat.com|dramastars.com|enstarz.com|foreverymom.com|hngn.com|itechpost.com|kpopstarz.com|latinpost.com|natureworldnews.com|parentherald.com|readysethealth.com|realtytoday.com|sciencetimes.com|sportsworldreport.com|universityherald.com|vcpost.com|youthhealthmag.com`

### Possible fix:
```
- ||stackpathdns.com^$image,domain=boomsbeat.com|dramastars.com|enstarz.com|foreverymom.com|hngn.com|itechpost.com|kpopstarz.com|latinpost.com|natureworldnews.com|parentherald.com|readysethealth.com|realtytoday.com|sciencetimes.com|sportsworldreport.com|universityherald.com|vcpost.com|youthhealthmag.com

+ ||stackpathdns.com^$image,domain=boomsbeat.com|dramastars.com|enstarz.com|foreverymom.com|itechpost.com|kpopstarz.com|latinpost.com|natureworldnews.com|parentherald.com|readysethealth.com|realtytoday.com|sciencetimes.com|sportsworldreport.com|universityherald.com|vcpost.com|youthhealthmag.com
```

### Temporary fix:
`@@||stackpathdns.com^$image,domain=hngn.com`

**Comment by TheYellowDog** [comment]
Each of our articles and the images and or videos they contain belong to us and you do not have the right to modify them as you wish.

Respond to users (YOUR users) who do not see an image because you do not respect our content and you do not tell them to have blocked the images of the article at a non-negligible cost, cost that we can not absorb free (already that you think that our articles are free ... while they are initially financed by advertising, our journalists do not live of pure air).

Who should I send the bill to?

**Comment by THEtomaso** [comment]
I checked some of the other sites which the **EasyList** rule covers..
It seems to break non-ad-related images at those sites too.

*updated my previous post*

**Comment by ryanbr** [comment]
We can only blame these sites for allowing Yavli to host on there stackpath. I've made a whitelist, but if they use the whitelists, I'll remove it.
