### ISSUE TITLE
redtube.com (NSFW)

### ISSUE THREAD

**Issue by dumbusernameidk** [easylist/easylist#3358]
### What happens?

This filter `redtube.com##[style*="height: 320px;"]` prevents the download buttons from appearing if you press "Download" under a video.

### List Subscriptions you're using:

uBO filters + EasyList.

- OS/version: Windows 10
- Browser/version: Chrome V74
- Adblock Extension/version: uBO v1.18.16

**Comment by THEtomaso** [comment]
Issue confirmed!
However, the problem rule seems to vary, from session to session.

### Problem filter:
* EasyList

### Problem rules (varies):
```
extremetube.com,pornhub.com,redtube.com,tube8.com,tube8.es,tube8.fr,xtube.com,xvideos.com,youjizz.com,youporn.com,youporngay.com##[style*="height: 300px;"]
extremetube.com,pornhub.com,redtube.com,tube8.com,tube8.es,tube8.fr,xtube.com,xvideos.com,youjizz.com,youporn.com,youporngay.com##[style*="height: 310px;"]
extremetube.com,pornhub.com,redtube.com,tube8.com,tube8.es,tube8.fr,xtube.com,xvideos.com,youjizz.com,youporn.com,youporngay.com##[style*="height: 320px;"]
extremetube.com,pornhub.com,redtube.com,tube8.com,tube8.es,tube8.fr,xtube.com,xvideos.com,youjizz.com,youporn.com,youporngay.com##[style*="height: 330px;"]
```

### Working fix:
```
redtube.com#@#[style*="height: 300px;"]
redtube.com#@#[style*="height: 310px;"]
redtube.com#@#[style*="height: 320px;"]
redtube.com#@#[style*="height: 330px;"]
```

--

### Additional issue:
After having added the above exception rules, the download window will appear every time.
However, when clicking on one of the download options, the actual download is now blocked by yet another rule..

### Problem filter:
* EasyList

### Problem rule:
`|http*://*?$popup,third-party,domain=avgle.com|camwhorestv.org|extremetube.com|pornflip.com|pornhub.com|redtube.com|spankwire.com|streamjav.net|theync.com|tube8.com|vidz7.com|xxxkingtube.com|youporn.com|youporngay.com`

### Working fix:
`@@||rdtcdn.com/media/videos$popup,domain=redtube.com`

**Comment by THEtomaso** [comment]
@ryanbr:

`redtube.com##div > iframe` doesn't fix anyting.
The issue reported by the OP still remains!

**Comment by Khrin** [comment]
Not for me, the download button works for me. Can you please check again after updating?

**Comment by dumbusernameidk** [comment]
can confirm the filter `
redtube.com##[style*="height: 310px;"]` prevents the buttons from loading.

**Comment by THEtomaso** [comment]
> Can you please check again after updating?

I updated, and confirmed that ryanbr's commits were present, before I submitted my previous post.

--

> `redtube.com##[style*="height: 310px;"]` prevents the buttons from loading

Yes, and in your first post, you refered to `redtube.com##[style*="height: 320px;"]`
Because, like I pointed out before; the actual blocking rule varies.

**Comment by ryanbr** [comment]
I just removed them, based on them not being hit. somewhat pointless to have them.
