### ISSUE TITLE
yesplz.coffee subscriptions list blocked

### ISSUE THREAD

**Issue by wjordan** [easylist/easylist#3359]
### List the website(s) you're having issues:

`https://www.yesplz.coffee/my-account/subscriptions/`

### What happens?

Requires an account with an active subscription to view (so may not be possible to reproduce). It's a "My Subscriptions" page that should show a list of subscriptions associated with the account. Each subscription is contained in a `<div class="subscription-box">` element which gets hidden, resulting in an empty page.

### List Subscriptions you're using:

Fanboy's Annoyance List​​​​​

### Your settings

- OS/version: ChromeOS (Chromebook)
- Browser/version: Chrome 73.0.3683.88
- Adblock Extension/version: uBlock Origin v1.18.16

### Other details:

This filter seems to be the trigger: https://github.com/easylist/easylist/blob/f69054eb59c514b73a8f892c58520dd43b96ca67/fanboy-addon/fanboy_annoyance_general_hide.txt#L2099

Adding the following exception filter fixed the issue for me:

```
yesplz.coffee#@#.subscription-box
```

**Comment by wjordan** [comment]
Since the page requires an account with a subscription to view here are some screenshots showing the page:

Normal page (div highlighted in Chrome developer tools):
![image](https://user-images.githubusercontent.com/56541/57207524-314c6580-6f83-11e9-84ce-b506d084550c.png)

Page with div incorrectly hidden by filter:
![image](https://user-images.githubusercontent.com/56541/57207462-c0a54900-6f82-11e9-97eb-0b1b3f3c8ef8.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6c26134c36ffb07c8fd7188f897e5e9a8fb8ce7a
