### ISSUE TITLE
investing.com detects the adblocker

### ISSUE THREAD

**Issue by SubZero5** [easylist/easylist#3364]
### List the website(s) you're having issues:
`https://tr.investing.com`
`https://www.investing.com`

### What happens?
Whole page gets dimmed, an overlay is put, and on top of those a div is put up

### List Subscriptions you're using:
Easylist

### Your settings

- OS/version: Windows 10
- Browser/version: Opera v58.0.3135.132
- Adblock Extension/version: Native
- Browser User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.132

### Other details:
I see 3 lines in the code like:

`<div class="topBarOverlay"></div>`
`<div class="generalOverlay js-general-overlay displayNone darker" style="display: block;"></div>`
`<div id="abPopup" class="genPopup ab" style="position: fixed; top: 169.5px; left: 322.5px;">[...]</div>`

And as I remove them manually, the issue goes away! ;)

**Comment by ryanbr** [comment]
Easylist won't address this.
