### ISSUE TITLE
youjizz.com (NSFW)

### ISSUE THREAD

**Issue by dumbusernameidk** [easylist/easylist#3369]
### What happens?

The filter `/^https?:\/\/.*\/.*[(php|?|=)].*/$first-party,image,domain=4tube.com|anysex.com|badjojo.com|extremetube.com|hotpornfile.org|keezmovies.com|mofosex.com|motherless.com|pornobae.com|pornoreino.com|pussyspace.com|shameless.com|spankwire.com|xnxx-sexfilme.com|youjizz.com|yourlust.com` prevents thumbnails from loading.

Also breaks thumbnails on 4tube and possibly every site.

Solution:
`/^https?:\/\/.*\/.*[(php|?|=)].*/$first-party,image,domain=4tube.com|anysex.com|badjojo.com|extremetube.com|hotpornfile.org|keezmovies.com|mofosex.com|motherless.com|pornobae.com|pornoreino.com|pussyspace.com|shameless.com|spankwire.com|xnxx-sexfilme.com|youjizz.com|yourlust.com,badfilter` or whitelist all image domains on the sites.

### List Subscriptions you're using:

uBO default list.

- OS/version: Windows 10
- Browser/version: Chrome V74
- Adblock Extension/version: Ublock Origin 1.18.16

**Comment by ryanbr** [comment]
fixed
