### ISSUE TITLE
[incorrect wildcard blocking] ad1.*

### ISSUE THREAD

**Issue by whop** [easylist/easylist#3378]
### List the website(s) you're having issues:

`ad1.com, ad1.net, ad1.org, ad1.int, ad1.edu, ad1.gov, ad1.mil`, etc.

### What happens?

All top level domains with an ad1.tld structure are incorrectly blocked because of this rule: `/ad1.$domain=~ad1.de|~ad1.in|~vereinslinie.de`.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10 build 1809 (for example)
- Browser/version: Google Chrome 74.0.3729.131 (for example)
- Adblock Extension/version: uBlock Origin 1.18.16 (for example)

### Other details:

I believe it is wrong approach to do wildcard block on all top level domains because some of them are serving ads, it is more acceptable to just ban offending domains.

**Comment by Khrin** [comment]
I disagree, I believe that our filter is more effective and immediate, and if a domain is incorrectly blocked we always added an exception for it. Also, you've cited a long list of supposed false positives, of which none is valid though. (I guess that this issue report had a second, real purpose...)

**Comment by whop** [comment]
I couldn't disagree more with your answer. So what you are telling me is this: we will block any domain unless it is proven innocent. I have domain with my initials (A.D. and number 1 - I will not specify the extension) and I would like to host personal developer blog on it. It is blank right now and I guess I will have to abandon it until Chrome pushes new extension API which will make this dumb list obsolete. I will live for that day, I promise. Thanks for wasting my money.

**Comment by whop** [comment]
Do you ever feel guilty about the censorship you have made with this list?

**Comment by Khrin** [comment]
So there was a second and real purpose! If you own an active domain which is incorrectly blocked, why you don't have told it before? (And why you withhold to tell the url even now?) Feel free to post the link here and we'll see what's possible to do. (Likely could be swiftly added to the exceptions list, or not, who can tell?)

**Comment by whop** [comment]
Hello internet cop. Thank you for not censoring me here. I am deeply sorry for not letting internet regulating bodies from eyeo know about the domain. I respect something called privacy on the internet. I would never sacrifice it, even for the price of block. Stay proud of your list because you seriously pissed off some developers. Those people are going to dedicate their life to making adblock bypass solutions.

**Comment by Khrin** [comment]
I'm saddened that we couldn't reach an agreement. If you will change your mind, feel free to send us an email (our addresses are publicly available), I want of course to respect your privacy but well it's hard to ask us to reconsider our choices and to accept your proposal without even knowing exactly why we should do that (or why we couldn't take a different approach).

Goodbye.

**Comment by whop** [comment]
Just out of curiosity - why do you ban ad1.com and not ad.com?
