### ISSUE TITLE
www.ftlf.dk + sslproxy.dk succesfully parsing to analytics.js

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#3396]
### List the website(s) you're having issues:
```
https://www.ftlf.dk/
```

```
19:48:03 |   |   |   | script | https://sslproxy.dk/c:86400/www.google-analytics.com/analytics.js
```

### What happens?
As noticed in https://github.com/spirillen/rpz-block-list/issues/120 `sslproxy.dk` maneged to parse requests to `www.google-analytics.com/analytics.js`

I think there should be a rule that kan handle all this kind of requests to `google-analytics.com/analytics.js` despite origin

### List Subscriptions you're using:
Defaults

### Your settings
Default

- OS/version:  ParrotSec 4.6
- Browser/version:  FF 65.0.1 (64-bit)
- Adblock Extension/version: Ublock Origin 1.14.18

**Comment by Khrin** [comment]
Unfortunately I don't think there's an easy and unique solution, beyond adding a new filter for each cases.
