### ISSUE TITLE
CelebJihad.com - Blocked videos (EasyList) [NSFW]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3408]
### Affected site:
`https://www.celebjihad.com/`

### Issue:
Video playback is broken, due to a blocked script.

### Example:
`https://www.celebjihad.com/celeb-jihad/natalie-portman-stripper-scene-closer/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyList

### Problem rule:
`/ads12.`

### Blocked script:
`https://www.celebjihad.com/video-js/ads12.js`

### Possible fix:
`@@||celebjihad.com/video-js/ads12.js`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.5.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by ryanbr** [comment]
was renamed by site, closed.
