### ISSUE TITLE
aliexpress.com: "Please slide to verify" verification fail

### ISSUE THREAD

**Issue by flyingzebras** [easylist/easylist#342]
It's not possible to login to aliexpress.com in Firefox due to some filters in EasyPrivacy that block alicdn javascripts.

Can you please have a look and white list them?

Here's what happen

"Please slide to verify" verification fail

![screenshot from 2017-03-21 19 17 42](https://cloud.githubusercontent.com/assets/6416073/24163666/81d5857a-0e6b-11e7-8c5c-0c706100c3be.png)

![screenshot from 2017-03-21 18 30 16](https://cloud.githubusercontent.com/assets/6416073/24162973/82e79d56-0e69-11e7-8e0c-b922d127ab64.png)

![screenshot from 2017-03-21 18 30 29](https://cloud.githubusercontent.com/assets/6416073/24162972/82e6b292-0e69-11e7-8544-60200a893d10.png)

**Comment by Khrin** [comment]
Hi, I apologize for the problem arisen. Can you confirm for me if this fix solve the issue?

**Comment by davidhedlund** [comment]
EasyPrivacy filter
> ||alicdn.com/js/aplus_*.js

blocks
> https://u.alicdn.com/js/aplus_ae.js

**Comment by flyingzebras** [comment]
EasyPrivacy filter
> ||alicdn.com/js/aplus_*.js

blocks
> https://u.alicdn.com/js/aplus_ae.js

**Comment by flyingzebras** [comment]
Static filter /analyze.js found in EasyPrivacy blocks https://cfus.aliyun.com/nocaptcha/analyze.jsonp

**Comment by Khrin** [comment]
Added https://github.com/easylist/easylist/commit/95275148443dbd326dc49f8996946467c0dd5d42

**Comment by davidhedlund** [comment]
@Khrin Thank you.

**Comment by davidhedlund** [comment]
@Khrin You also need to whitelist this to get the [Aliexpress Live Chat](https://helppage.aliexpress.com/buyercenter/index.htm) working:

> Static filter ||alicdn.com/alilog/ found in: EasyPrivacy
> https://g.alicdn.com/alilog/mlog/aplus_b2b2.js

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)
