### ISSUE TITLE
Yavli filters issues 

### ISSUE THREAD

**Issue by ephraimju** [easylist/easylist#343]
The sites that we maintain look being block by adblock because of Yavli issue.

christianpost.com 
christiantoday.com
christianexaminer.com

We had Yavli almost 1 years ago but are not running for long time. Could you able to remove us from the block list so we can solve the many complains of unusable issue.

Thank you very much.

**Comment by Khrin** [comment]
While I haven't found the domain christianexaminer.com in our Yavli filters list, I've removed the other two domains.
