### ISSUE TITLE
www.italiansubs.net/forum/

### ISSUE THREAD

**Issue by Gittyperson** [easylist/easylist#3431]
Example: https://www.italiansubs.net/forum/game-of-thrones/commenti-game-of-thrones-805/msg6106143/#msg6106143

### What happens?

The 'like' button at the top of each message is removed, and turned into an unclickable horizontal line. Forum log-in is required for the button to appear. Button is not related to FB etc., just an internal forum 'like'.

### List Subscriptions you're using:

Caused by Fanboy’s Social Blocking List

- OS/version: Windows 10 1809
- Browser/version: Pale Moon 28.5.0 / Firefox 66.0.5
- Extension/version: uBO 1.16.4.10   /  uBO 1.19.2

![like button issue](https://user-images.githubusercontent.com/7165208/57691989-4d6c9880-764e-11e9-8702-fd4175bc6b6b.png)

**Comment by Khrin** [comment]
Login is required to see this issue?

**Comment by Gittyperson** [comment]
Yes.

**Comment by ryanbr** [comment]
Given the amount of requests, unless we get logins dets or suggested filters thats breaking it, Closing this.

**Comment by Gittyperson** [comment]
If you want login data, then let me know where to send it. Issue is still present.
