### ISSUE TITLE
Citationsy - ad shows

### ISSUE THREAD

**Issue by Smittyvb** [easylist/easylist#3441]
### List the website(s) you're having issues:

https://citationsy.com/ (logged in)

### What happens?

An ad:
![image](https://user-images.githubusercontent.com/10530973/57798164-1bc10380-771a-11e9-8e33-b0abda3c362b.png)

### List Subscriptions you're using:

uBlock Origin default

### Your settings

- OS/version: 74.0.3729.125 (Official Build) (64-bit)
- Browser/version: Chrome OS, see above for versiont
- Adblock Extension/version: uBlock Origin v1.19.2

**Comment by ryanbr** [comment]
Got a temp login?

**Comment by Smittyvb** [comment]
@ryanbr 
throwaway@example.com, abc123

**Comment by Citationsy** [comment]
How unfortunate. This is exactly the kind of ad that you should not be blocking. It contains no tracking, doesn’t set any cookies, uses no JavaScript, and is not loaded from a third party ad network. There are no graphics, or images, or annoying animations — it even uses the system default font. It loads instantly and only changes to a new ad on page reload. It’s an ad put there by me to to help pay for Citationsy’s servers, and you can very easily disable it by upgrading your Citationsy account.  If you don’t want to see the ad upgrade to Pro, or don’t use Citationsy. 

I am disappointed that you requested this tiny unobtrusive ad be blocked, @Smittyvb.

**Comment by llacb47** [comment]
It's an ad. It gets blocked. If you want it to be considered for ABP's "Acceptable Ads" program you can apply here: `https://acceptableads.com/en/get-whitelisted/`

**Comment by Citationsy** [comment]
@llacb47  🙄
