### ISSUE TITLE
mail.google.com view=ad

### ISSUE THREAD

**Issue by WaleedMortaja** [easylist/easylist#3442]
### List the website(s) you're having issues:
<code>mail.google.com</code>

### What happens?
I happened to find this filter <code>@@||mail.google.com^*&view=ad&$xmlhttprequest</code> and I just wonder, why is it allowed?
The name implies that it is an advertisement.
Can you please explain what is this filter and why is it allowed?

### List Subscriptions you're using:
EasyList is one the subscriptions I use and it is the subscription that allowed <code>@@||mail.google.com^*&view=ad&$xmlhttprequest</code>

**Comment by ryanbr** [comment]
Its used elsewhere on the site, will cause false positives on gmail (specifically on the side bar features)

**Comment by WaleedMortaja** [comment]
> 
> 
> Its used elsewhere on the site, will cause false positives on gmail (specifically on the side bar features)
@ryanbr 
Can you explain that more? an image would be helpful.
Thanks!

**Comment by ryanbr** [comment]
It'll block additional features used by (like calander etc) in the side bar. Sure the filter will block ads, but also blocks other things. we have element filters that that renders view=ad pointless and also doesn't cause issues. you're free to add to your personal list.

**Comment by WaleedMortaja** [comment]
Thanks! 👍
