### ISSUE TITLE
EasyPrivacy Curalate false positive

### ISSUE THREAD

**Issue by ewandennis** [easylist/easylist#3482]
### List the website(s) you're having issues:

 - `app.sparkpost.com` and numerous customer domains

### What happens?

Our app includes a set of API endpoints which begin `/api/v1/metrics`. The app does not function without those endpoints. You can signup for a test account at `https://app.sparkpost.com/join` and visit any section under "Reports" to reproduce the issue.

### List Subscriptions you're using:

 - EasyPrivacy

### Your settings

- OS/version: OS X 10.14
- Browser/version: Chrome 74.0.3729.169
- Adblock Extension/version: ABP 3.5.2 / uBlock Origin 1.19.2

### Other details:

The filter in question is `/api/v1/metrics`. It was added in [this commit](https://github.com/easylist/easylist/commit/59ab990d0890062c2ad8869ed4de3a0a45956a4a#diff-6b54c84f883288b1582a40f4174525e0) to filter Curalate tracking for #3348 .

How about something like `e.curalate.com/api/v1/metrics` as an alternative filter?

Thanks and please let me know how I can help.

**Comment by smed79** [comment]
(https://forums.lanik.us/viewtopic.php?f=64&t=43042)

**Comment by Khrin** [comment]
Not sure why a tracker should be whitelisted.

**Comment by ewandennis** [comment]
@Khrin I'm not suggesting whitelisting the curalate tracker. I'm suggesting tightening the filter definition to include the domain `e.curalate.com` to avoid impacting other services which use `/api/v1/metrics` in their API names.

[The forum thread](https://forums.lanik.us/viewtopic.php?f=64&t=43042) includes details of 2 cases where that string appears in unrelated APIs.

**Comment by ryanbr** [comment]
whitelisting "/metrics" api doesn't seem legit.

**Comment by ewandennis** [comment]
@ryanbr There seem to be hundreds of chunks of code with `/api/v1/metrics` in their URL, including ours. ([GitHub search here](https://github.com/search?q=%22%2Fapi%2Fv1%2Fmetrics%22&type=Code)).

Ours is not a tracker. Its a reporting service - part of our own web app. Its not embedded in 3rd party web sites.

This rule stops the front end of our app contacting its own backend. It also presumably filters all other services in that GitHub search.

I suggest updating this rule to filter its intended target without the collateral impact; something like `e.curalate.com/api/v1/metrics`.

What can I do to help explain this issue more clearly?
