### ISSUE TITLE
https://www.viafree.se [Detects Adblocker]

### ISSUE THREAD

**Issue by ue4116** [easylist/easylist#3490]
### List the website(s) you're having issues:
Example: `https://www.viafree.se/program/humor/how-i-met-your-mother/sasong-5/avsnitt-1`

### What happens?
When the player _runs into_ an add, I get the adblocker message. If i skip past the commercial on the player, it jumps right over it.

### Your settings
- OS/version: Windows 10 Pro 64 bit. 10.0.17134 Build 171134
- Browser/version: Google Chrome Version 74.0.3729.157
- Adblock Extension/version: Nano Defender 15.0.0.147 with Nano Adblocker 1.0.0.110

### Other details:
Screenshot: `https://i.gyazo.com/ce443459633fca0d5c690eacbe58cedb.png`

**Comment by THEtomaso** [comment]
I can't log in to verify, but I suspect that '**Frellwit's Swedish Filter**' contains a fix:
`https://github.com/lassekongo83/Frellwits-filter-lists#available-lists`
