### ISSUE TITLE
https://www.opensubtitles.org Detects adblock and displays popup asking to install adware plugin when trying to download subtitles

### ISSUE THREAD

**Issue by mikeloeven** [easylist/easylist#3495]
### List the website(s) you're having issues:

`https://www.opensubtitles.org`

### What happens?

When trying to download subtitle files a pop window opens asking user to install an adware firefox extension even openly states its adware.
Does not require extension in order to download files however the popup is not properly blocked 

`https://addons.mozilla.org/en-GB/firefox/addon/opensubtitles-pro/`

### List Subscriptions you're using:
Nano filters​
Nano filters – Whitelist​
uBlock filters – Badware risks​
uBlock filters – Privacy​
uBlock filters – Resource abuse​​​​
uBlock filters – Unbreak​
Adblock Warning Removal List​
EasyList​
EasyPrivacy

### Your settings

- OS/version: Windows 7 X64
- Browser/version: Waterfox 56.2.10
- Adblock Extension/version: Nano Adblocker (1.0.0.110) with Nano Defender(15.0.0.147)

**Comment by ryanbr** [comment]
Seems fine here
