### ISSUE TITLE
https://pilot.wp.pl/tv

### ISSUE THREAD

**Issue by radzi143** [easylist/easylist#3497]
What happens?
Please, turn off AdBlock / uBlock

List Subscriptions you're using:
 nano adblocker + nano defender

Your settings
didnt touch anything 

OS/version: Windows 10
Browser/version: Mozilla 67.0
nano adblocker  1.0.0.111
nano defend 15.0.0.125

**Comment by krystian3w** [comment]
Radek wyłączyłeś mechanizm ochrony prywatności wbudowany w Firefox?

On drażni WP i generuje takie komunikaty u nich.

**Comment by radzi143** [comment]
O dobrze wiedzieć ale jzi chyba chyba defender sobie z tą stroną radzi więc luz ale na przyszłość będę pamiętał dziena! 
            
          
     
      
       
        Dnia 12 czerwca 2019 18:21 krystian3w &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Radek wyłączyłeś mechanizm ochrony prywatności wbudowany w Firefox? 
 On drażni WP i generuje takie komunikaty u nich.

**Comment by krystian3w** [comment]
Nie defender a poprawka w filtrach polskich przeciwko alertom anty-adblock.

**Comment by radzi143** [comment]
A przy okazji zapytam gdzie znajdę opcje wyłączenia tego mechanizmu prywatności ? 
            
          
     
      
       
        Dnia 24 czerwca 2019 10:47 krystian3w &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Nie defender a poprawka w filtrach polskich przeciwko alertom anty-adblock.

**Comment by krystian3w** [comment]
W opcjach przeglądarki, tam prywatność, ustawić na np. własną i odznaczyć "**elementy śledzące**".

pomocny link - otworzy ustawienia na module do ochrony prywatności:
```
about:preferences#privacy
```

**Comment by radzi143** [comment]
Dzięki za pomoc!! 😀 
            
          
     
      
       
        Dnia 24 czerwca 2019 21:49 krystian3w &lt;notifications@github.com&gt; napisał(a):
       
    
       
         W opcjach przeglądarki, tam prywatność, ustawić na np. własną i odznaczyć &#34; elementy śledzące &#34;. 
 pomocny link - otworzy ustawienia na module do ochrony prywatności: 
 about:preferences#privacy

**Comment by Khrin** [comment]
We don't block anti-adblock messages.

**Comment by krystian3w** [comment]
And no generate on this site 👍.
