### ISSUE TITLE
https://aternos.org/server/

### ISSUE THREAD

**Issue by mahaer-mahmud** [easylist/easylist#3506]
### List the website(s) you're having issues:

`https://aternos.org/server`

### What happens?

When a user tries to enter the site signed in with an adblocker, the adblocker is detected and the entire webpage is replaced with a red screen explaining how their owners have to rely on advertising. There is a white button to continue with your adblocker. When you click it, you have to wait three seconds before you can continue browsing the site. All the banner ads on the website are replaced with red boxes saying 'We finance our project with ads. Please turn off your adblocker.' The same process occurs when the user selects a page.

### List Subscriptions you're using:

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
Adblock Warning Removal List
EasyList (of course :P)
EasyPrivacy
Malware Domain List
Malware domains
Peter Lowe’s Ad and tracking server list
Fanboy's Enhanced Tracking List
Nano Defender Integration
Nano Filters
Nano Filters - Whitelist

And my own filter list `https://paste.ee/p/7JJX7`

### Your settings

- OS/version: Antergos Linux x86_64, kernel version 5.1.4-arch1-1-ARCH
- Browser/version: Waterfox 59.2.9 (64-bit)
- Adblock Extension/version: uBlock Origin v1.19.6 + Nano Defender 15.0.0.147

### Other details:

This video `https://webm.red/hMnn`

**Comment by smed79** [comment]
Classic Adblock Plus filters https://forums.lanik.us/viewtopic.php?f=62&p=132088

For uBlock specific filters, report directly at https://github.com/uBlockOrigin/uAssets/issues

**Comment by mahaer-mahmud** [comment]
Thank you!
