### ISSUE TITLE
RE-happening: AnimeFever.tv detects the adblocker and stops video 

### ISSUE THREAD

**Issue by Sagesheep** [easylist/easylist#3535]
List the website(s) you're having issues:

https://www.animefever.tv/anime/14881/the-helpful-fox-senko-san/episode/43034

placed the link to the video instead because that is where the anti-adblocking thing starts
What happens?

    Visit Site
    Click an Anime and choose an episode
    Instead of player starting the episode, it stops and tells you to disable adblock. It will said 
    An error has occurred
    AF-AB119: Please Disable Your AdBlock

List Subscriptions you're using:

default from UBOrigin and default lists from nano defender

Your settings

    Windows 10 Pro
    Firefox Quantum 67
    uBlock Origin v1.18.16

Reoccuring. Last ticket
https://github.com/easylist/easylist/issues/3230

The fixes from last ticket has been applied but it has been redundant now

**Comment by ryanbr** [comment]
`Easylist hasn't added Anti-adblock for a while.`

```
@@||animefever.tv^$generichide
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$xmlhttprequest,domain=animefever.tv
```
