### ISSUE TITLE
https://www.computerbase.de/forum/threads/google-analytics-und-dsgvo.1874439/

### ISSUE THREAD

**Issue by steffenweber** [easylist/easylist#3537]
### List the website(s) you're having issues:

1. Using a clean Google Chrome profile, open `https://www.computerbase.de/` to initialize the service worker
2. Install AdBlock Plus (don't do this before step 1, otherwise the service worker initialization currently fails, I'll fix that in a few days)
3. Add the EasyPrivacy list to AdBlock Plus
4. Open `https://www.computerbase.de/forum/threads/google-analytics-und-dsgvo.1874439/`

Screencast to help you reproduce the issue: `https://www.youtube.com/watch?v=k0vop09vc5Y`

### What happens?

Loading the page fails (an "offline" error page is displayed by the website's service worker) because AdBlock Plus blocks the service worker [Navigation Preload](https://developers.google.com/web/updates/2017/02/navigation-preload) request. The root cause of this issue is that Chrome reports a wrong request type `other` instead of `main_frame` for navigation preload requests, see [Chrome Issue 965960](https://bugs.chromium.org/p/chromium/issues/detail?id=965960). This causes the EasyPrivacy rule `/google-analytics-$~image` to match the mentioned URL.

I've asked the uBlock developers to apply a workaround to uBlock ([uBlock Issue #608](https://github.com/uBlockOrigin/uBlock-issues/issues/608), contains some more technical details) until the Chrome bug gets fixed but they claim that this is a "filterlist issue" and caused by "a terrible filter". They have effectively disabled/replaced the rule `/google-analytics-$~image` for uBlock users now: [Commit 446ac96](https://github.com/uBlockOrigin/uAssets/commit/446ac96fbb8d25ac57b053912c6cd3e68c100f18). I don't know whether they are right but wanted to bring this potentially problematic rule to your attention such that you can fix it for AdBlock Plus users, too, if you agree with their judgement.

### List Subscriptions you're using:

AdBlock Plus defaults + EasyPrivacy

### Your settings

- OS/version: Linux, Windows (but probably all)
- Browser/version: Chrome 74, 75, 76
- Adblock Extension/version: 3.5.2

### Other details:

Please have a look at the screencast if you cannot immediately reproduce the issue: `https://www.youtube.com/watch?v=k0vop09vc5Y`

**Comment by Khrin** [comment]
I don't know why our filter must be changed, I don't even see any hits for this filter in that page.

**Comment by steffenweber** [comment]
The screencast shows the hit for the mentioned rule at the very end.
