### ISSUE TITLE
Incorrect popup filter for NSFW sites

### ISSUE THREAD

**Issue by dumbusernameidk** [easylist/easylist#3539]
### What happens?

The filter `|http*://*?$third-party,popup,domain=avgle.com|camwhorestv.org|extremetube.com|pornflip.com|pornhub.com|redtube.com|spankwire.com|streamjav.net|theync.com|tube8.com|vidz7.com|xxxkingtube.com|youporn.com|youporngay.com|` causes incorrect blocking. ie,. go to pornhub, find some text, "search google for ...", clicking images/videos/etc closes the tab.

### List Subscriptions you're using:
ubo default lists.

### Your settings:
- OS/version: Windows 10 64-bit
- Browser/version: Chrome v74
- Adblock Extension/version: Ublock Origin v1.19.6

**Comment by ryanbr** [comment]
I don't think you'll ever fix these issues. any use of $popup blocking will cause issues elsewhere. Its specifically aim at those sites that generate popups.

**Comment by dumbusernameidk** [comment]
These sites don't have popups though? Also you can actually fix the issue `@@||google.com/search?$popup,third-party` works fine for me.
