### ISSUE TITLE
Archive.org - Major breakage (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3545]
Under certain circumstances, **EasyList** is causing severe breakage @ `archive.org`.

See report here:
https://github.com/AdguardTeam/AdguardFilters/issues/34520/
(Troubleshooted in second post)

**Comment by ryanbr** [comment]
Not cover the anti-adblock stuff, but I can see valid reasons to use $generichide on web.archive.org.
