### ISSUE TITLE
http://www.washingtonexaminer.com/ EasyPrivacy false positive

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#355]
http://www.washingtonexaminer.com/nra-gorsuch-will-be-on-supreme-court-one-way-or-another/article/2619048

EasyPrivacy breaks article image

**Comment by Khrin** [comment]
Fixed https://github.com/easylist/easylist/commit/8801f0d9e57af8aeab88c6428264e8a77f6cdf77
