### ISSUE TITLE
prawo.money.pl blank page besides main page

### ISSUE THREAD

**Issue by p0358** [easylist/easylist#3557]
### List the website(s) you're having issues:

`https://prawo.money.pl/kodeks/karny/czesc-ogolna/rozdzial-ii-formy-popelnienia-przestepstwa/art-18`
But this works: `https://prawo.money.pl/`

### What happens?

You see a white page visiting the first link. It seems to be a div element of `<div class="pub_300x250 text_ads ad_container" style="display: block;visibility: visible;display: none;"></div>` right after <body> causing this, removing it in the inspector causes page content to display properly. Interestingly the element is covered by blocking lists, and its `display` is overriden by `none !important`. Nothing else seems to cause it to display, but removing the element altogether does fix it indeed.

### List Subscriptions you're using:

Default of uBlock Origin

### Your settings

- OS/version: Windows 10
- Browser/version: **Google Chrome 73**
Actually this seems to be likely cause. I also tested this in Microsoft Edge Chromium edition and the page does display there. I also tested this in the same Chrome in private mode where I had only uBlock Origin, HTTPS Everywhere and my password manager enabled there, and it worked. GDPR screen welcomed me on the very same page. However disabling other extensions in regular mode, so that I had the same configuration as in private mode, didn't change anything. It still doesn't work there. And works after manually removing said element.
- Adblock Extension/version: uBlock Origin v1.19.6

### Other details:

As avove next to browser version.

**Comment by krystian3w** [comment]
Hello, I have same problem.

**Comment by krystian3w** [comment]
@olegwukr proszę dodaj takie coś do filtrów Anty-Adblockowych:

`prawo.money.pl#@#body > div[class="pub_300x250 text_ads ad_container"][style] + div[class]:not([id])`
