### ISSUE TITLE
Remove prism.js (syntax highlighting library) from list

### ISSUE THREAD

**Issue by Rob--W** [easylist/easylist#3567]
### List the website(s) you're having issues:

`https://prismjs.com/` and any other site that uses prism.js for syntax highlighting.

### What happens?

Syntax highlighting does not work. This is because `prism.js` is blocked by this change: https://github.com/easylist/easylist/commit/e7f657a9b55adabaf44404b549c4edd92f4276a4

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: any
- Browser/version: any
- Adblock Extension/version: uBlock Origin

### Other details:
This change is responsible for the breakage: https://github.com/easylist/easylist/commit/e7f657a9b55adabaf44404b549c4edd92f4276a4
prism.js is a popular syntax highlighting library (https://github.com/PrismJS/prism). Please take "prism.js" off the list.

**Comment by ryanbr** [comment]
Commited from https://github.com/easylist/easylist/commit/e7f657a9b55a 

From https://prism.app-us1.com/prism.js
Beautified; https://pastebin.com/5Wui0nDy

Has tracking in it, is this the same script used?

**Comment by nexsja** [comment]
@ryanbr no, that script is not the same as https://prismjs.com/ hence the pull request to block that specific one.
