### ISSUE TITLE
investigationdiscovery.com

### ISSUE THREAD

**Issue by BlazDT** [easylist/easylist#3583]
https://www.investigationdiscovery.com/tv-shows/true-crime-with-aphrodite-jones/full-episodes/scott-peterson-aphrodite-jones-investigates

Site requires US IP and EasyPrivacy list:

Video will not play unless these two requests are whitelisted:

```
@@||src.litix.io/core/*/mux.js$domain=investigationdiscovery.com
@@||fusion.ddmcdn.com/app/eos-usnets^$domain=investigationdiscovery.com
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/03643a2b1d482ea45500ae276a651f97711939c2
