### ISSUE TITLE
quartic.pl

### ISSUE THREAD

**Issue by KerbenII** [easylist/easylist#3646]
@ryanbr 
@Khrin 

### List the website(s) you're having issues:
`quartic.pl
cp.quarticon.com
enea.pl`

### What happens?

1. After correct logging into the clients dashboard (cp.quarticon.com), the panel does not work (no javascripts, css styles).

2. Our CDN does not return images and css styles (fl.quartic.pl)

If You want to block our analytics engine, please block:
- rec.quartic.pl/t.php
- rec.quartic.pl//tt

`||rec.quartic.pl/t.php^$third-party
||https://rec.quartic.pl//tt`

And the weirdest thing is that our domain was block with following commit message:
"A: https://www.tvokazje.pl/":
`https://github.com/easylist/easylist/commit/5421f47ebee4d5e7fa91644201b95508f79743bd?diff=split`
but... no request at this domain is hitting quartic.pl

### List Subscriptions you're using:

uBlock Origin
EasyPrivacy
### Your settings

no additional lists / extensions

- OS/version:  Ubuntu 18.04
- Browser/version: Chrome 75.0.3770.90
- Adblock Extension/version:  uBlockOrigin 1.19.6

### Other details:

`||quartic.pl^$third-party`

**Comment by KerbenII** [comment]
@smed79 @ryanbr @Khrin sorry for mentioning, but we are down for approx. 7 days for some customers!!!

**Comment by KerbenII** [comment]
@smed79 @ryanbr @Khrin any progress?

**Comment by smed79** [comment]
Try reporting the issue via email to `easylist.subscription @ gmail.com`

**Comment by KerbenII** [comment]
Thanks! Reported via email
Date: Mon, 1 Jul 2019 21:58:12 +0200

**Comment by ryanbr** [comment]
Resolved ^. Closing. Given the constant requests, no further changes will be done
