### ISSUE TITLE
www.cadeaubox.be breakage

### ISSUE THREAD

**Issue by GoGoris** [easylist/easylist#3651]
### List the website(s) you're having issues:

`https://www.cadeaubox.be`

### What happens?

A blank page is shown when visiting the website with easyprivacy enabled

### List Subscriptions you're using:

EasyPrivacy
...

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 68
- Adblock Extension/version: Nano Adblocker 1.0.0.117

### Other details:

Breaking rule:
||visualwebsiteoptimizer.com^$third-party

**Comment by Khrin** [comment]
Hi, I have no problems viewing this website with Easyprivacy enabled. Does this issue still happens for you?

**Comment by GoGoris** [comment]
No, I cannot reproduce it anymore. Maybe they changed something?

**Comment by Khrin** [comment]
Ok, if this issue should arise again, feel free to report it here.
