### ISSUE TITLE
https://trust.zone

### ISSUE THREAD

**Issue by Wdavery** [easylist/easylist#3652]
This is site is blocked via this list, but appears to be fine.

Ublock Origin blocks nothing on the site by default.

**Comment by zoreu** [comment]
This happens when you enable social media icon tracking lock or use Fanboy's Social Blocking List

**Comment by krystian3w** [comment]
`##.tweets`
`##.social-share`

are broke / block site?

**Comment by Khrin** [comment]
Problem lies elsewhere, site loads correctly.

**Comment by adRn-s** [comment]
Anyone using EasyList can go to https://trust.zone that the issue reappeared. I wonder if competition to this VPN provider is trolling with adding it to the list or what. Judging by the aesthetics, the site looks edgy but I'm confident that torrentfreak [article](https://torrentfreak.com/best-vpn-anonymous-no-logging/) wouldn't have listed the site if it were malware/ scam/ or bad service at all.

Could you reopen the issue? I lack permissions.
