### ISSUE TITLE
Trying to open links in a new window on fandom.com results in the new window being closed

### ISSUE THREAD

**Issue by pcjtulsa** [easylist/easylist#3653]
### List the website(s) you're having issues:
<code>https://community.fandom.com</code>

### What happens?
I try to open a link in a new window and the new window is immediately closed.

### List Subscriptions you're using:

EasyList, EasyPrivacy
### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 67
- Adblock Extension/version: uBlock Origin 1.20 

### Other details:
I believe this is a result of [this commit](https://github.com/easylist/easylist/commit/d1ad366a7418742790f4aa160f5523eac8447dc9).

**Comment by mapx-** [comment]
already fixed in uBo (update unbreak list)
https://github.com/uBlockOrigin/uAssets/commit/fc7f38ac72d0e24daca72c03a93b9c42980fd9e9

**Comment by pcjtulsa** [comment]
Fixed with https://github.com/easylist/easylist/commit/cf31803da52108554fb9b16a2f531ec0c5f557ab
