### ISSUE TITLE
amazon api images blocked by Easylist

### ISSUE THREAD

**Issue by Hennes79** [easylist/easylist#3660]
### List the website(s) you're having issues:

`e.g.: https://survivalmesserguide.de/friendly-swede-feuerstahl/`

### What happens?

Images generated via the amazon.de API like the one below are blocked:

`<a href="https://www.amazon.de/gp/product/B004LLZP3Q/ref=as_li_ss_il?pf_rd_p=671e72bc-8864-4ab6-8ef7-60da5d6ead8c&pf_rd_r=S40ER19XY2P8XF7EJ84E&linkCode=li2&tag=tag-21&linkId=6394a23c4b0e4d0d56e4007d8326b445&language=de_DE" target="_blank"><img border="0" src="//ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B004LLZP3Q&Format=_SL160_&ID=AsinImage&MarketPlace=DE&ServiceVersion=20070822&WS=1&tag=tag-21&language=de_DE" ></a><img src="https://ir-de.amazon-adsystem.com/e/ir?t=tag-21&language=de_DE&l=li2&o=3&a=B004LLZP3Q" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />`

It used to work just fine for years. Starting a couple of days ago these types of images are gone, strapping the site of important visuals and creating a bad user experience - as there are no images where the user would expect some.

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Windows 10, Version 10.0.18362 Build 18362
- Browser/version: Firefox 67.0.4 (64-Bit),
- Adblock Extension/version: Adblock Plus Versionsnummer 3.5.2

Same on Chrome:
- Browser/version: Google Chrome Version 75.0.3770.100 (Offizieller Build) (64-Bit)
- Adblock Extension/version: AdBlock Version 3.48.0 (getadblock.com)

### Other details:

works if excluded from the list:
`@@||amazon-adsystem.com/widgets/$image,domain=survivalmesserguide.de`

**Comment by SimonD23** [comment]
I have the same issue here in the US. Here's my site:
[https://thewatchsnob.com/watch-winder-reviews/](https://thewatchsnob.com/watch-winder-reviews/)

The Amazon images are only shown when EasyList is disabled

**Comment by itruemper** [comment]
Same here in the US. Here's an example page:
https://www.secondhalftravels.com/books-mexico-expats/

**Comment by CharlieKirby** [comment]
I am also experience the same behaviour on a selection of sites when trying to use an image source generated by Amazon Site Stripe . Example URLs from each of the effected sites:
https://drumhelper.com/electronic-drums/best-electronic-drum-pad/
https://diygarden.co.uk/best-childrens-playhouse/
https://hobbyhelp.com/astronomy/best-astrophotography-telescope/
https://pillowpicker.com/best-knee-pillows/

**Comment by gayathri7066** [comment]
Hi, my website is http://outdoorily.com and I don't see the images on my site when the EasyList filter is enabled. An example URL is http://outdoorily.com/best-sleeping-bag-liner/.

Kindly whitelist my domain.

**Comment by monzta** [comment]
This should fix it: https://github.com/easylist/easylist/commit/a6d88f2

**Comment by SimonD23** [comment]
No this issue is absolutely NOT fixed. 

Did you check any of the links in the ticket? None of the images are displayed when the EasyList filter is enabled. Please reopen this ticket and provide a fix ASAP!
This has been going on for several weeks now, and this issue affects thousands of Amazon affiliate sites!

Thanks!

**Comment by Khrin** [comment]
Better to calm down yourself. It's not our fault if you use a known ad server to deliver "images".

**Comment by SimonD23** [comment]
Sure I am calm. Will this issue be fixed or not?

**Comment by SimonD23** [comment]
It just started working for me. I appreciate the fix thanks!

**Comment by monzta** [comment]
It takes a bit until you can get this fix via manual filter list update and a couple of days until it is rolled out to all users using EasyList. Thanks for confirming!

**Comment by itruemper** [comment]
Working for me too now... yay!

P.S. Amazon doesn't allow us to use their product images unless they're sourced from their servers, so this was a really critical fix. Thanks so much!

**Comment by Hennes79** [comment]
It seems to be working on Google Chrome browser, but the issue is **still sthere on Firefox**. Please fix.

**Comment by llacb47** [comment]
Purge your filters and update them. Easylist has been updated and the issue should no longer be there.

**Comment by Hennes79** [comment]
It works now. Well done.

**Comment by Belle177** [comment]
still having issues with mine over here [](https://hobbyfinder.io/)

**Comment by Belle177** [comment]
Is this still operational? and how can i add it to my website on [this](https://hobbyfinder.io/hobbies/) page on the left banner
