### ISSUE TITLE
Yahoo comments

### ISSUE THREAD

**Issue by tw-e** [easylist/easylist#3661]
@ryanbr 
@Khrin 

### List the website(s) you're having issues:
https://hk.mobi.yahoo.com/news/mvpjjonak-233037686.html

### What happens?
His comment plugin and other page features are not loaded properly.

### List Subscriptions you're using:
Easylist

### Your settings

- OS/version: Android
- Browser/version: Firefox 68
- Adblock Extension/version: Adblock Plus Mobile

### Other details:
![Screenshot_20190622-104709_Chrome Dev](https://user-images.githubusercontent.com/51475468/59958575-61bc7480-94db-11e9-9cbf-71dff0a85853.jpg)
PS.This is the picture of the full normal version.
But after opening "easylist", all blanks, I hope you can fix it.

**Comment by ryanbr** [comment]
```
@@||s.yimg.com/ud/fp/js/ADPositions.69f5e406408a8741d2c9.min.js$script,domain=hk.mobi.yahoo.com
@@||s.yimg.com/ud/fp/js/GoldenGate.a27aa422bc753d881c25.min.js$script,domain=hk.mobi.yahoo.com
@@||s.yimg.com/ud/fp/js/SocialBar.46650a70ae25ab6ee2a1.min.js$script,domain=hk.mobi.yahoo.com
```

Seems to be affecting the site. Other wise it'll get endless loading.

**Comment by ryanbr** [comment]
#alsozenyattamain

fixed.
