### ISSUE TITLE
Adblock detection cheatsquad gg

### ISSUE THREAD

**Issue by Janmm14** [easylist/easylist#3662]
Not sure if its too specific. Someone please add this where it belongs to.
```
@@||beta.cheatsquad.gg/js/ads.js$script,domain=beta.cheatsquad.gg
```

**Comment by krystian3w** [comment]
No fixed with: `Fanboy’s Enhanced Tracking List​​​​​​​​​`?

https://fanboy.co.nz/filters.html

**Comment by THEtomaso** [comment]
@okiehsch:
The fix in uBlock filters needs to be updated, cuz it doesn't work anymore.
PS: If you come up with a new one, could you please add it to the uBO's Legacy filter too?

**Comment by krystian3w** [comment]
```
cheatsquad.gg##^style:has-text(top:expression)
cheatsquad.gg##^div[id]:has-text(Please enable)
cheatsquad.gg##^script:has-text(/\"\)\.parentNode\.removeChild\(window\.document\.getElementById\(\"/)
```

**Comment by Khrin** [comment]
Anti Adblock systems cannot be blocked by EasyList.

**Comment by krystian3w** [comment]
so delete report or limit comments for `collaborators` only...

**Comment by xDsquare** [comment]
snitches get various stitches @Janmm14
