### ISSUE TITLE
https://hanime.tv

### ISSUE THREAD

**Issue by TsukikagamiTooya** [easylist/easylist#3663]
This is site is blocked via this list, but appears to be fine.
Ublock Origin blocks nothing on the site by default.

https://hanime.tv/hentai-videos/sakuramiya-shimai-no-netorare-kiroku-1
![video-player-fail-bg-v3](https://user-images.githubusercontent.com/43428424/59969999-64c86b00-9596-11e9-94a9-a8c75d0f28dc.jpg)

**Comment by mahaer-mahmud** [comment]
Maybe this'll work, I'm not sure though.
``https://forums.lanik.us/viewtopic.php?f=62&t=33563&p=105756&hilit=hanime#p105756``

**Comment by TsukikagamiTooya** [comment]
Not work

**Comment by bogachenko** [comment]
@TsukikagamiTooya which browser, which subscriptions, which country is your ip

**Comment by smed79** [comment]
@TsukikagamiTooya warn when it is about NSFW content and don't post clickable link.

```
@@||hanime.tv^$generichide
```
