### ISSUE TITLE
AP News Topics blocked

### ISSUE THREAD

**Issue by siffegh** [easylist/easylist#3673]
### List the website(s) you're having issues: AP News
`https://www.apnews.com/apf-entertainment` and all the rest under 'Topics'.

### What happens?
Spinning 'loading' icon; the page never loads.  The AP News home page loads OK.

### Other details: 
Disabling EasyPrivacy fixes the problem.

- OS/version: Win7 Pro SP1
- Browser/version: FF 67.0.4 (64-bit)
- Adblock Extension/version: uBlock Origin 1.20.0

### Settings:
{
  "timeStamp": 1561428140874,
  "version": "1.20.0",
  "userSettings": {
    "advancedUserEnabled": true,
    "alwaysDetachLogger": true,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": true,
    "externalLists": "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt\nhttps://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt",
    "firewallPaneMinimized": false,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": true,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": false,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
    "plowe-0",
    "hphosts",
    "fanboy-annoyance",
    "easyprivacy",
    "easylist",
    "awrl-0",
    "ublock-filters",
    "user-filters"
  ],
  "hiddenSettings": {
    "allowGenericProceduralFilters": false,
    "assetFetchTimeout": 30,
    "autoCommentFilterTemplate": "{{date}} {{origin}}",
    "autoUpdateAssetFetchPeriod": 120,
    "autoUpdateDelayAfterLaunch": 180,
    "autoUpdatePeriod": 7,
    "cacheStorageAPI": "unset",
    "cacheStorageCompression": true,
    "cacheControlForFirefox1376932": "no-cache, no-store, must-revalidate",
    "consoleLogLevel": "unset",
    "debugScriptlets": false,
    "disableWebAssembly": false,
    "ignoreRedirectFilters": false,
    "ignoreScriptInjectFilters": false,
    "manualUpdateAssetFetchPeriod": 500,
    "popupFontSize": "unset",
    "requestJournalProcessPeriod": 1000,
    "selfieAfter": 3,
    "strictBlockingBypassDuration": 120,
    "suspendTabsUntilReady": "unset",
    "userResourcesLocation": "unset"
  },
  "netWhitelist": "about-scheme\napp.starbucks.com\nchrome-extension-scheme\nchrome-scheme\nfilext.com\nmoz-extension-scheme\nopera-scheme\notc.tax.ny.gov\npayments.ncdot.gov\nsecure.bankofamerica.com\nshop.mercola.com\nshopsafe.bankofamerica.com\ntierrafarmstore.com\nvivaldi-scheme\nws04.nyenet.state.ny.us\nwww.cpuid.com\nwww.freefilefillableforms.com\nwww.vitacost.com\nwww7b.tax.ny.gov\nwyciwyg-scheme",
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false\nno-scripting: behind-the-scene false\nno-cosmetic-filtering: * true",
  "userFilters": ""
}

**Comment by Khrin** [comment]
Hi, I've added a fix to EasyPrivacy. Please can you confirm if it work also for you, after forcing an update?

**Comment by siffegh** [comment]
Thanks @Khrin, it appears to be fixed.
