### ISSUE TITLE
Amazon Affiliate images are not being displayed with the EasyList filter

### ISSUE THREAD

**Issue by gayathri7066** [easylist/easylist#3686]
### List the website(s) you're having issues:
http://outdoorily.com/
http://outdoorily.com/best-sleeping-bag-liner/

### What happens?
With the Easylist filter enabled, I do not see the images from my Amazon Affiliate account being displayed. 

### Your settings

- OS/version: 10.14.5 
- Browser/version: Version 75.0.3770.100
- Adblock Extension/version: Version number 3.5.2

**Comment by them1212** [comment]
Здравствуйте помогите пожалуйста не блокируется реклама на сайтах в браузере опера.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/0e6fd82f03227fbfe021e6bbfd3805057d5c2e8d
