### ISSUE TITLE
YtMp3.cc - Blocked download button (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3708]
### Affected site:
`https://ytmp3.cc/`

### Issue:
The "**Download**" button is blocked.

### How to reproduce:
Paste a link for a YouTube video into the address field, then click on the "**Convert**" button.

* **Expected result**: When converted, the Download button should appear.
* **Actual result**: The Download button is blocked!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyList

### Problem rule:
`ytmp3.cc###download`

### Fix:
Remove the problem rule!

### Note (Additional issue):
The "**Dropbox**" download option is also blocked, by the following rules (found in '**EasyList**'):
```
|http://$image,script,subdocument,third-party,xmlhttprequest,domain=ytmp3.cc
|https://$image,script,subdocument,third-party,xmlhttprequest,domain=ytmp3.cc
```
**Blocked script**: `https://www.dropbox.com/static/api/2/dropins.js`
**Possible fix**: `@@||dropbox.com/static/api/2/dropins.js$domain=ytmp3.cc`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by Alex-302** [comment]
and `ytmp3.cc#@##download`

**Comment by mojamm11** [comment]
not sure how to edit the rules, how do i do that?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/58cf6a51f9f83769ebac720527d17688f432c85b

**Comment by THEtomaso** [comment]
The issue with the main Download button seems to have been fixed server-side.
They probably changed it because EasyList broke it.
