### ISSUE TITLE
Easyprivacy breaks lastampa.it

### ISSUE THREAD

**Issue by ermescs** [easylist/easylist#3709]
### List the website(s) you're having issues:

`https://www.lastampa.it`

### What happens?

If I try to play a video (any video) it doesn't start and if I open an article (any article) it is empty (no content is displayed).

### List Subscriptions you're using:

Easyprivacy

### Your settings

OS/version: Windows 10
Browser/version: Chrome 75.0.3770.100
Adblock Extension/version: uBlock Origin 1.20.0
Please note that the same happens with other OS/Browser/Extension configurations.

### Other details:
The rules breaking the website are the following
Video
`/wt.js?http`
Article
`/pw.js?deskurl=`

**Comment by Khrin** [comment]
Grazie mille per la segnalazione, aggiornando EasyPrivacy ora il sito dovrebbe funzionare correttamente.

**Comment by ermescs** [comment]
Ciao,
ci siamo accorti appena ora che la regola 
`/wt.js?http`
rompe anche i video sul sito del Secolo XIX (https://www.ilsecoloxix.it/).
Se ritieni creiamo un'altra issue ad hoc.

**Comment by Khrin** [comment]
Va benissimo chiederlo qui, modificato nuovamente la regola. https://github.com/easylist/easylist/commit/6eae4e6d29f1fec5e26429a05a7820e0a3413149

Sei uno dei webmaster? Provo a chiederlo, non sarebbe proprio possibile "correggere" da parte vostra? Penso che sarebbe la soluzione migliore per entrambi...

**Comment by ermescs** [comment]
No, siamo degli sviluppatori di un'estensione di ad e tracker blocking, un utente ci ha segnalato il problema sul sito della stampa ed, essendo quest'ultima dello stesso gruppo - GEDI - del Secolo XIX abbiamo verificato anch'esso.

**Comment by Khrin** [comment]
Ok lo stesso...

**Comment by Khrin** [comment]
@superlex An example link, please? Even if behind paywall.

**Comment by superlex** [comment]
@Khrin 
Sure:
`https://rep.repubblica.it/pwa/intervista/2020/02/05/news/lamorgese_non_si_puo_essere_indifferenti_l_odio_e_un_emergenza_-247722094/`
You'll find the audio at the end of the article.
