### ISSUE TITLE
Remove github.io wasm block

### ISSUE THREAD

**Issue by KnicKnic** [easylist/easylist#3713]
I know this has been discussed earlier but I want to bring it up again. Previous issues https://github.com/easylist/easylist/issues/1158 https://github.com/easylist/easylist/issues/1034 
Reasons why
1. Coin miners now just embed wasm in their javascript
    1. https://www.reddit.com/r/Monero/comments/83orlm/pure_js_nonwebassembly_browser_mining/dvkf4fu?utm_source=share&utm_medium=web2x
1. ublock still seems to work if I create an iframe to the github.io site and load the webassembly in the iframe. So all a miner has to do is create an iframe.
1. Miners could fallback to asm.js.
1. they could just upload their wasm file to a CDN via NPM and it wouldn't be blocked. As it is not in the list.

The last issue is what I am trying to accomplish however since I want to reference it from a github page it is blocked. Anyways since their exists multiple workarounds for this block that are rather trivial I would recommend removing the block.

problem: https://github.com/easylist/easylist/blob/27b64cefb9237601e8e248d906cb3bc7d3323b32/easyprivacy/easyprivacy_specific.txt#L2438

It seems weird for me to have to obfuscate my scenario to load on a CDN, and will hurt streaming wasm compilation (loading speed) for normal use cases.

My site that is impacted is https://knicknic.github.io/imagemagick/ currently you see it loads fine as I am referencing the wasm file on the github page itself rather than through a CDN. I recompiled imagemagick to webassembly so that people can use imagemagick from their browser.

Currently tracked via https://github.com/KnicKnic/WASM-ImageMagick/issues/44

Thanks!

**Comment by ryanbr** [comment]
I haven't any in a while, I guess its safe to remove.
