### ISSUE TITLE
theverge.com

### ISSUE THREAD

**Issue by FadeMind** [easylist/easylist#3729]
**Site Sample** | 
----------------|
https://www.theverge.com/

Information			| Value
---					| ---
Operating system:	| Windows 10 1903 x64
Browser:			| Google Chrome Stable x64 (lastest)
Adblocker:			| nanoDefender + nanoAdblocker

| **Filters enabled**
|:--------------------------
| **SECTION :: Main**
| Nano Defender Integration​​​​​
| Nano filters​​​​​
| Nano filters – Annoyance​​​​​
| Nano filters – Whitelist​​​​​
| uBlock filters​​​​​
| uBlock filters – Annoyances​​​​​
| uBlock filters – Badware risks​​​​​
| uBlock filters – Privacy​​​​​
| uBlock filters – Resource abuse
| uBlock filters – Unbreak​​​​​
| **SECTION :: Ads**
| Adblock Warning Removal List
| Adguard Base List
| EasyList
| **SECTION :: Privacy**
| AdGuard Tracking Protection
| EasyPrivacy
| Fanboy’s Enhanced Tracking List
| **SECTION :: Malware**
| Malvertising filter list by Disconnect​​​​​
| Malware Domain List​​​​​
| Malware domains​
| Spam404​
| **SECTION :: Annoyances**
| AdGuard Annoyances filter​​​​​
| AdGuard Social Media filter​
| Anti-Facebook List​​​​​
| Fanboy’s Annoyance List​
| Fanboy's Cookie List​
| Fanboy’s Social Blocking List​
| **SECTION :: External**
| NoCoin Filter List​​​​​
| Peter Lowe’s Ad and tracking server list
| **SECTION :: Languages**
| Polish Adblock Warning Removal List
| Polish Main
| **SECTION :: Customs**
| AlleBlock​​​​​
| CoinBlockerLists by ZeroDot1 uBlock
| EasyList Polish​​​​​
| facebook annoyances blocker​​​​​
| KAD - Przekręty​​​​​
| Polish Privacy Filters​​​​​
| Polskie Filtry Elementów Irytujących​​​​​
| Polskie Filtry Społecznościowe​​​​​
| FuckFuck Adblock
| Youtube: Pure Video Experience

# ISSUE

Cookie notice

![scr-1562499961-001](https://user-images.githubusercontent.com/9846948/60767835-94f72a00-a0bd-11e9-90da-c585bf618bd2.png)

**Comment by THEtomaso** [comment]
Can't be blocked, because it breaks video playback:
https://github.com/easylist/easylist/issues/2256/

**Comment by graememeyer** [comment]
I think this may have changed and can be blocked now:

###privacy-consent

**Comment by THEtomaso** [comment]
No, blocking it still prevents video playback!
To confirm, simply follow the link in my previous post, and open the example link, which I provided there.

**Comment by graememeyer** [comment]
Ah I see, understood. Cheers
