### ISSUE TITLE
Mercado Libre analytics servers

### ISSUE THREAD

**Issue by SnwMds** [easylist/easylist#3748]
### List the website(s) you're having issues:

`mercadolibre.com.ve, mercadolibre.com.uy, mercadolibre.com.pe, mercadolibre.com.py, mercadolibre.com.pa, mercadolibre.com.ni, mercadolibre.com.mx, mercadolibre.com.hn, mercadolibre.com.gt, mercadolibre.com.ec, mercadolibre.com.do, mercadolibre.com.cr, mercadolibre.com.co, mercadolibre.com.cl, mercadolibre.com.bo, mercadolibre.com.ar, mercadolivre.com.br.`

### What happens?

Mercado Libre has its own way of collecting user data (analytics). By accessing the website, user data is collected and transmitted to the following servers:

`analytics.mercadolibre.com.ve, analytics.mercadolibre.com.uy, analytics.mercadolibre.com.pe, analytics.mercadolibre.com.py, analytics.mercadolibre.com.pa, analytics.mercadolibre.com.ni, analytics.mercadolibre.com.mx, analytics.mercadolibre.com.hn, analytics.mercadolibre.com.gt, analytics.mercadolibre.com.ec, analytics.mercadolibre.com.do, analytics.mercadolibre.com.cr, analytics.mercadolibre.com.co, analytics.mercadolibre.com.cl, analytics.mercadolibre.com.bo, analytics.mercadolibre.com.ar, analytics.mercadolivre.com.br, analytics.mercadolivre.com, analytics.mercadolibre.com.`

### List Subscriptions you're using:

EasyList and EasyPrivacy.

### Your settings

- OS/version: Android 8.1.0
- Browser/version: Firefox 67.0.3 (Stable)
- Adblock Extension/version:  Nano Adblocker v1.0.0.120

### Other details:

Block access to these servers by adding the following rule:
`||analytics.mercadoli*re.com*^`

**Comment by Khrin** [comment]
For what I can see, should be already blocked by the filter ```/analytics/ga/*```.
