### ISSUE TITLE
[EasyPrivacy] pcmonitors.info - table load loop

### ISSUE THREAD

**Issue by ArmynC** [easylist/easylist#3749]
### List the website(s) you're having issues:

`https://pcmonitors.info/reviews/archive/
`

### What happens?

The comparison tables are stuck in a load loop. 

### List Subscriptions you're using:

`https://github.com/ArmynC/ArminC-uBlock-Settings/blob/master/arminc-ublock-backup.txt`

### Your settings

See above

- OS/version: Win7
- Browser/version: Chrome Version 76.0.3809.46 (Official Build) beta (64-bit)
- Adblock Extension/version: 1.20.3rc2

### Other details:

I think EasyPrivacy (+someonewhocares) is blocking the script via `||geni.us^$third-party`

Possible fix(?): `||cdn.geni.us/snippet.min.js$script`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/26fbe8cc6a5b52fc31ff8f241b2a75629bb5905e
