### ISSUE TITLE
techrrival.com detects adblocker

### ISSUE THREAD

**Issue by gmcouto** [easylist/easylist#3763]
### List the website(s) you're having issues:
`https://www.techrrival.com/best-download-managers-windows/`

### What happens?
```
Hey there.
So... you use an ad blocker. That's cool. Sometimes we do to.
But without ad revenue, we wouldn't even be here. And we might not be here much longer.

Please disable your ad blocker and click to continue.
```

### List Subscriptions you're using:
Nano Defender, default configuration

### Your settings
Default configuration for Nano Adblocker and Nano Defender

- OS/version: W10
- Browser/version: Chrome 75
- Adblock Extension/version: Latest

**Comment by zoreu** [comment]
add:

@@||techrrival.com^$generichide
techrrival.com##div[id^="google_ads_iframe_"]
techrrival.com##.td-a-rec-id-custom_ad_1
techrrival.com##.td-a-rec-id-custom_ad_2
techrrival.com##.ezoic-floating-bottom
techrrival.com##.ezoic-ad
techrrival.com##.ezo_ad
techrrival.com##.ezmob-footer
techrrival.com##.adtester-container

**Comment by llacb47** [comment]
First of all, those cosmetic filters are inefficient. And second of all, please put your filters in a code block.

**Comment by zoreu** [comment]
nobody is obliged to like, I present the solution and that's it

**Comment by ryanbr** [comment]
There are other lists that can counter anti-adblock, Easylist isn't one of them.
