### ISSUE TITLE
Wera.de - Blocked pages (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3788]
### Affected site:
`https://www.wera.de/`

### Issue:
Some pages are prevented from loading!

### Examples:
`https://products.wera.de/en/screwdrivers_kraftform_plus__series_300.html`

`https://products.wera.de/en/tools_for_the_aerospace_segment_screwdrivers_screwdrivers_kraftform_plus__series_300.html`

(All language versions of the same pages are affected)

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyList

### Problem rule:
`_300.htm`

### Possible fix:
`@@_300.htm$domain=wera.de`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.0.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by zoreu** [comment]
add:

`@@||products.wera.de^$xmlhttprequest`

**Comment by llacb47** [comment]
Stop telling maintainers to add existing filters. https://github.com/uBlockOrigin/uAssets/commit/eea75769dc2516c07629279a3dce56af59537090

**Comment by THEtomaso** [comment]
@ryanbr:

Removing `/300.html$subdocument` doesn't help.
Look at my initial report..
This is the rule that is causing the problem!: `_300.htm`

Screenshot from uBO's logger:
![filterissue-wera](https://user-images.githubusercontent.com/9382674/62831823-21e55400-bc25-11e9-84e8-4eede782f4d8.jpg)

**Comment by zoreu** [comment]
PR: #3915

**Comment by krystian3w** [comment]
PR name should be: `P: wera.de` for better readability?

https://github.com/easylist/easylist/pull/2280

**Comment by zoreu** [comment]
@krystian3w thanks for reminding me
Khrin solved the problem

https://github.com/easylist/easylist/commit/e6d73534bb1ed2030a14ba8a33b23bd9d3cbd1b1

**Comment by THEtomaso** [comment]
@okiehsch:
> https://github.com/uBlockOrigin/uAssets/commit/1aad10970154d813df9e48f0e16388dfdb2b820d

I was wondering if you'd notice this, before I made you aware of it. :)
Anyway, guess you can delete it now.
