### ISSUE TITLE
aternos.org detects adblocker

### ISSUE THREAD

**Issue by Mikkendaal** [easylist/easylist#3789]
### What happens?

You are using an adblocker!
Our service is 100% free, we pay the servers only with advertisments. This project could not exist without the earnings from this advertisments.

We would really appreciate if you could turn off your adblocker. We promise you that our advertisments will not appear in annoying popups or similar.

### List Subscriptions you're using:

 
- all uBlock filters except experimental
- Nano filters
- Nano filters - Whitelist

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome 75
- Adblock Extension/version: Latest

**Comment by llacb47** [comment]
Requires account to reproduce. Also discussed [here](https://github.com/NanoAdblocker/NanoFilters/issues/272).
Try these filters:
`aternos.org##+js(abort-on-property-read.js,Intl)
aternos.org##div[id]:has(div[style]:has(.fa-frown))
aternos.org##aside:has(.ad)
aternos.org##div.ad-detect.ad-dfp.mobile-full-width.responsive-leaderboard.ad`
The tutorial videos are broken, I'm working on seeing if that can be fixed.

**Comment by Mikkendaal** [comment]
> Requires account to reproduce. Also discussed [here](https://github.com/NanoAdblocker/NanoFilters/issues/272).
> Try these filters:
> 
> ```
> aternos.org##+js(abort-on-property-read.js,Intl)
> aternos.org##div[id]:has(div[style]:has(.fa-frown))
> aternos.org##aside:has(.ad)
> aternos.org##div.ad-detect.ad-dfp.mobile-full-width.responsive-leaderboard.ad
> ```
> 
> The tutorial videos are broken, I'm working on seeing if that can be fixed.

Stupid question but how do I apply these filters?

**Comment by llacb47** [comment]
You're using uBlock, right? Click on it in your extension toolbar and click on the dashboard button. It looks like [this](https://user-images.githubusercontent.com/886325/49340318-7d932280-f63e-11e8-9db9-96aa84d00f3b.png). Then, click on the my filters tab and copy and paste those filters into the textbox in that tab. Apply the changes and see if the site works.

**Comment by Mikkendaal** [comment]
> You're using uBlock, right? Click on it in your extension toolbar and click on the dashboard button. It looks like [this](https://user-images.githubusercontent.com/886325/49340318-7d932280-f63e-11e8-9db9-96aa84d00f3b.png). Then, click on the my filters tab and copy and paste those filters into the textbox in that tab. Apply the changes and see if the site works.

Ok. Thanks for help.
