### ISSUE TITLE
rp5.ru detects Nano ADBlocker with Defender

### ISSUE THREAD

**Issue by UnclWish** [easylist/easylist#3790]
### List the website(s) you're having issues:
```
rp5.ru
```
### What happens?

Site detects Nano ADBlocker and hides info (weather data).

### List Subscriptions you're using:

Nano Defender Integration​​​​​
Nano filters
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Experimental​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak

Adblock Warning Removal List
AdGuard Base List
AdGuard Mobile Ads​​​​​
EasyList​​​​​
Nano contrib filter – Placeholder buster​​​​​

AdGuard Tracking Protection​​​​​
EasyPrivacy​​​​​
Fanboy's Enhanced Tracking List​​​​​

Malware Domain List​​​​​
Malware domains​​​​​

Peter Lowe's Ad and tracking server list​​​​​

RUS: AdGuard Russian
RUS: RU AdList

### Your settings

- OS/version: Windows 10 x64 Pro 1903
- Browser/version: SRWare Iron 74.0.3850.0 (Chromium 74 based)
- Adblock Extension/version: 1.0.0.120

### Other details:

**Comment by zoreu** [comment]
add:

`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js^$domain=rp5.ru`
`rp5.ru#@#.adsbygoogle`

**Comment by UnclWish** [comment]
Thanks! Works! Does it will be added into some rules list?
