### ISSUE TITLE
uktvplay.uktv.co.uk

### ISSUE THREAD

**Issue by Sniper296** [easylist/easylist#3796]
### List the website(s) you're having issues:

`https://uktvplay.uktv.co.uk/shows/taskmaster/watch-online` (requires free account)

### What happens?

> Please remove or disable your ad blocking software to view this content.

### List Subscriptions you're using:

uBlock Origin defaults
Also tested with EasyList alone.

### Your settings

- OS/version: Windows 10 1809 17763.615
- Browser/version: Firefox 68
- Adblock Extension/version: uBlock 1.20.2

### Other details:

The detection code is in `https://s3-eu-west-1.amazonaws.com/uktv-static/prod/play/ae298bf9bf05a319436d.js` via web service worker. Blocking it breaks the site.

**Comment by llacb47** [comment]
It doesn't require an account to reproduce for me.

**Comment by zoreu** [comment]
add:

`@@||fwmrm.net/ad/*$xmlhttprequest,domain=uktvplay.uktv.co.uk`

**Comment by llacb47** [comment]
Already in uAssets... https://github.com/uBlockOrigin/uAssets/commit/bcfad48325cf409443129fa4d060d8870cfd3fe1
