### ISSUE TITLE
bitcoinmagazine.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#38]
`https://bitcoinmagazine.com/articles/bip-the-end-to-end-encryption-bitcoin-never-had-but-soon-will-1465401187`
`https://bitcoinmagazine.com/articles/jaxx-wallet-integrates-shapeshift-for-in-wallet-conversion-between-bitcoin-ether-and-dao-tokens-1465587726`

Distributed trade ad.

And distributed trade also has sponsors on its own site:

`https://godistributed.com/trade/`

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/1036605243a094abddc82534f86df1cbdf4146fb 

When I try to remove them, it also removed other content.
