### ISSUE TITLE
Webike sites - Blocked elements (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3802]
### Affected sites:
All of Webike's domains!

### Issue:
Blocked elements.

### Screenshot (from `webike.no`):
![filterissue-webike](https://user-images.githubusercontent.com/9382674/61499017-e9f04580-a9c5-11e9-9011-553bbd990145.jpg)

### Problem filter:
* EasyList

### Problem rule:
`##.ad_box`

### Possible fix (which covers all of Webike's domains):
`japan-webike.be,japan-webike.ca,japan-webike.ch,japan-webike.dk,japan-webike.ie,japan-webike.it,japan-webike.nl,japan-webike.kr,japan-webike.se,webike.ae,webike.co.at,webike.co.hu,webike.co.il,webike.co.uk,webike.com.ar,webike.com.bd,webike.com.gr,webike.com.kh,webike.com.mm,webike.com.ru,webike.com.tr,webike.com.ua,webike.cz,webike.de,webike.es,webike.fi,webike.fr,webike.hk,webike.id,webike.in,webike.la,webike.mt,webike.mx,webike.my,webike.net,webike.net.br,webike.net.pl,webike.ng,webike.no,webike.nz,webike.ph,webike.pk,webike.pt,webike.sg,webike.tw,webike.vn,webike-china.cn#@#.ad_box`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.0.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by zoreu** [comment]
PR: #3821

**Comment by THEtomaso** [comment]
@zoreu:
I see in your pull request that you've added an extra entry for `webike.net.br`, so that it is now listed twice.
The one at the end should be removed.

**Comment by THEtomaso** [comment]
@ryanbr:

I didn't spot it at first, but the exception rule for `##.ad_title` (which added okiehsch added to 'uBlock filters - Unbreak') is also needed!

Screenshot:
![filterissue-webike2](https://user-images.githubusercontent.com/9382674/62831982-fadc5180-bc27-11e9-842c-671499fb09ae.jpg)

Fix:
`japan-webike.be,japan-webike.ca,japan-webike.ch,japan-webike.dk,japan-webike.ie,japan-webike.it,japan-webike.nl,japan-webike.kr,japan-webike.se,webike.ae,webike.co.at,webike.co.hu,webike.co.il,webike.co.uk,webike.com.ar,webike.com.bd,webike.com.gr,webike.com.kh,webike.com.mm,webike.com.ru,webike.com.tr,webike.com.ua,webike.cz,webike.de,webike.es,webike.fi,webike.fr,webike.hk,webike.id,webike.in,webike.la,webike.mt,webike.mx,webike.my,webike.net,webike.net.br,webike.net.pl,webike.ng,webike.no,webike.nz,webike.ph,webike.pk,webike.pt,webike.sg,webike.tw,webike.vn,webike-china.cn#@#.ad_title`
