### ISSUE TITLE
Can't post new comments on thepiratebay.org

### ISSUE THREAD

**Issue by wodim** [easylist/easylist#3803]
EasyList makes it impossible to post new comments on torrents, since they are posted using AJAX. I think it may be because of this line.

    $webrtc,websocket,xmlhttprequest,domain=ahoypirate.in|bayception.pw|cruzing.xyz|mirror.superproxy.biz|mypirate.cc|noobnoob.rocks|piratebay.tel|piratebay.town|piratebay1.top|piratebayblocked.com|pirateproxy.ch|pirateproxy.live|pirateproxy.rocks|prox1.info|proxyfrom.asia|proxyindia.net|superbay.link|superproxy.biz|thehiddenbay.com|thepiratebay.kiwi|thepiratebay.org|thepiratebay.vip|thepiratebay10.org|thepirateproxy.win|theproxybay.net|tpb.crushus.com|tpb.hid.li|tpb6.ukpass.co|tpbproxyone.org|tpbrun.win|tpproxy.website|ukpirate.org|unblockpirate.uk|unblocktheship.org

**Comment by zoreu** [comment]
don't have commenting option

**Comment by wodim** [comment]
You have to register and log in first.

**Comment by ryanbr** [comment]
Last time we attempted to fix this they used our whitelist to serve ads. I'm happy to leave it, thepiratebay is ad-infested mess not worth my time.
