### ISSUE TITLE
Videos won't play on thechive.com

### ISSUE THREAD

**Issue by mica** [easylist/easylist#3809]
For example: https://thechive.com/2019/07/19/guy

**Comment by THEtomaso** [comment]
There are plenty of filters blocking it.

Summary:

### Problem filters:
* AdGuard Base filter
* Dan Pollock's hosts file
* EasyList
* Malvertising list by Disconnect
* MVPS HOSTS
* Peter Lowe's Ad and tracking server list
* Schacks Adblock Plus liste

### Problem rules:
```
||acdn.adnxs.com^
||adnxs.com^
||adnxs.com^$third-party
```

### Blocked script:
`https://acdn.adnxs.com/video/mediation/apn_overlay_integration.js`

### Possible fix:
`@@||adnxs.com/video/mediation/apn_overlay_integration.js$domain=thechive.com`

--

@okiehsch:
One for '**uBlock filters - Unbreak**' perhaps?

**Comment by mica** [comment]
It did play after I disabled EasyList. Didn't have to disable any others.

**Comment by THEtomaso** [comment]
Well, are you actually using any of those other ones?

**Comment by mica** [comment]
Oh, no, I guess I'm not. Just using the uBlock Origin defaults.

**Comment by THEtomaso** [comment]
Simply paste the fix that I posted into uBO's "My filters" window..
Then you can enable EasyList again.

**Comment by mica** [comment]
I can wait for this to end up in EasyList, assuming it will?

**Comment by THEtomaso** [comment]
Yeah, and/or in '**uBlock filters - Unbreak**'.
