### ISSUE TITLE
cuntwars.com [incorrect blocking]

### ISSUE THREAD

**Issue by NicoletteCW** [easylist/easylist#3831]
### List the website(s) you're having issues:

`https://cuntwars.com`

### What happens?

Only a blank gray page shows:
![image](https://user-images.githubusercontent.com/53336031/61942602-6e346100-afa2-11e9-9dc3-2388f7626128.png)

A page with the game should be showing:
![image](https://user-images.githubusercontent.com/53336031/61942776-c1a6af00-afa2-11e9-8a75-3a9aa939cd1e.png)

### List Subscriptions you're using:

EasyList only.

### Your settings

- OS/version: Windows 10 64-bit.
- Browser/version: Tested on Chrome 75 and Firefox 68 
- Adblock Extension/version:  uBlock Origin extension v1.21.6 and no other extensions.

### Other details:

Not only I have the issue; a lot of other players have the same issue; this is happening since approximately 24.07.2019 or 25.07.2019

This line in `easylist/easylist.txt` might be the root of this issue:
`||cuntwars.com^$third-party`

**Comment by NicoletteCW** [comment]
This was fixed in the uBo unbreak list with the `@@||storage.googleapis.com/xxx-mightyparty.appspot.com/$frame` line

**Comment by Khrin** [comment]
They have whitelisted ads? This baffles me!

**Comment by bomfunksn** [comment]
Lol, you just closed it without explanation of this issue?)
This incident affects several thousand people, despite the fact that not a single advertisement is displayed at the screenshot.

**Comment by bomfunksn** [comment]
@Khrin Could you, please, point, where is the ad, that you block? We could tell to devs delete it from the page.
