### ISSUE TITLE
jmail.ovh

### ISSUE THREAD

**Issue by bug-rules** [easylist/easylist#3843]
ads in emails [](https://github.com/uBlockOrigin/uAssets/issues/6014)

> ![obraz](https://user-images.githubusercontent.com/43518394/62012280-89f75d00-b184-11e9-8cd8-e4661348647e.png) |
> --- |

```
/img/banners/*$third-party,image,domain=www.jmail.ovh
```

![obraz](https://user-images.githubusercontent.com/43518394/62012287-9d0a2d00-b184-11e9-93d0-14bd1de09410.png) |
--- |
![obraz](https://user-images.githubusercontent.com/43518394/62012293-b14e2a00-b184-11e9-9eae-679e05513c30.png) |

**Comment by easylistbrasil** [comment]
jmail.ovh##a[href="http://www.bateseyeexercises.com"]

**Comment by ryanbr** [comment]
Can reproduce here, seems okay.

**Comment by bug-rules** [comment]
So legit ad?
