### ISSUE TITLE
[incorrect blocking] cuntwars.com

### ISSUE THREAD

**Issue by Uwnokt** [easylist/easylist#3861]
### List the website(s) you're having issues:

cuntwars.com

### What happens?

Hi! I can't access the game with adblock turned on for some reason.
Only see a gray page instead of the game and chat.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: win10 64-bit
- Browser/version: Chrome 75
- Adblock Extension/version: AdBlock Plus 3.6

### Other details:

I've seen that there already was an issue regarding this from another player, but you closed it, please reconsider, as we can't access the game at all

**Comment by NicoletteCW** [comment]
As already said in the previous issue, this incident affects several thousand people
You closed the previous issue without doing anything despite the fact that not a single advertisement is displayed at the screenshot.
There is only a link to another game, a chat and the game frame on the page; you could tell us what do you consider to be an ad so we can remove it from the page, why does this block the access to the game completely?

**Comment by Khrin** [comment]
Stuff from the blocked domain was displayed on another unrelated website; added an exception for the above mentioned site.
