### ISSUE TITLE
Easy Privacy in Ublock origin does not allow crunchyroll to load videos

### ISSUE THREAD

**Issue by ahmedmsoliman96** [easylist/easylist#3864]
i am using firefox version 68.0.1 and uBlock Origin v1.21.2 and i cant load any videos on crunchyroll while easy privacy is enabled 

`https://www.crunchyroll.com/yu-gi-oh-gx/episode-1-yugis-heir-684069
`
but after disabling easy privacy i can load the videos. is there a fix to this problem ?

**Comment by ryanbr** [comment]
Seems fine here, video plays.

**Comment by shirtjs** [comment]
I am also encountering this issue.
