### ISSUE TITLE
Pirate Bay mirrors - Blocked assets (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3877]
### Affected sites:
```
https://mypirate.cc/
http://proxyfrom.asia/
http://mirror.superproxy.biz/
https://unblockpirate.uk/
```

### Issue:
Blocked assets results in broken page layouts.

### Screenshots:
Not needed, as the problem is obvious.

### Problem filter:
* EasyList

### Problem rule:
`|https://$image,script,stylesheet,subdocument,third-party,xmlhttprequest,domain=ahoypirate.in|bayception.pw|cruzing.xyz|mirror.superproxy.biz|mypirate.cc|noobnoob.rocks|piratebay.tel|piratebay.town|piratebay1.top|piratebayblocked.com|pirateproxy.ch|pirateproxy.live|pirateproxy.rocks|prox1.info|proxyfrom.asia|proxyindia.net|superbay.link|superproxy.biz|thehiddenbay.com|thepiratebay.kiwi|thepiratebay.org|thepiratebay.vip|thepiratebay10.org|thepirateproxy.win|theproxybay.net|tpb.crushus.com|tpb.hid.li|tpb6.ukpass.co|tpbproxyone.org|tpbrun.win|tpproxy.website|unblockpirate.uk|unblocktheship.org`

### Possible fix:
```
@@||b-cdn.net/static$image,stylesheet,domain=mypirate.cc|unblockpirate.uk
@@||thepiratebay.vip^$third-party,domain=proxyfrom.asia|mirror.superproxy.biz
```

### Note:
`https://tpb.hid.li/` is broken too, but there seems to be some nasty stuff going on over there, so I'm not so sure that the required assets should be whitelisted in this case.
Perhaps someone else could take a closer look at it?

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by Khrin** [comment]
Was able to only fix two domains, sorry.

**Comment by THEtomaso** [comment]
@Khrin:
I took a closer look at it..
This takes care of the page layouts (including the ones for search results) @ `proxyfrom.asia`, `superproxy.biz`, `mirror.superproxy.biz` and `thepiratebay.vip`:
```
@@||thepiratebay.vip^$frame,image,stylesheet,domain=proxyfrom.asia|superproxy.biz
@@||tpbprox.com/static/css/$stylesheet,domain=proxyfrom.asia|superproxy.biz|thepiratebay.vip
@@||tpbprox.com/static/img/$image,domain=proxyfrom.asia|superproxy.biz|thepiratebay.vip
```

**Comment by Khrin** [comment]
First filter is simply unacceptable, it's too much broad and open to abuses. I'll never add something like that, sorry.
