### ISSUE TITLE
[incorrect blocking] https://www.nutaku.net/games/cunt-wars/play/

### ISSUE THREAD

**Issue by NicoletteCW** [easylist/easylist#3881]
### List the website(s) you're having issues:

`https://www.nutaku.net/games/cunt-wars/play/`

### What happens?

Infinite loading screen.

### List Subscriptions you're using:

Easylist only.

### Your settings

- OS/version: Windows 10 64-bit
- Browser/version: Chrome 75
- Adblock Extension/version: uBlock Origin v1.21.6

### Other details:

Hello and thanks for unbreaking the Cunt Wars website.
Unfortunately, our game also can be played through our partner website Nutaku and on their site the game still doesn't load.

Here's a screenshot of the uBo logger with blocked requests.
![image](https://user-images.githubusercontent.com/53336031/62454978-0d650f80-b77e-11e9-8292-170d49f11eb1.png)

> Stuff from the blocked domain was displayed on another unrelated website; added an exception for the above mentioned site.

_Originally posted by @Khrin in https://github.com/easylist/easylist/issues/3861#issuecomment-517802121_

Could this be related to the issue?

**Comment by zoreu** [comment]
add:

`@@||storage.googleapis.com/xxx-mightyparty.appspot.com/release_builds^$third-party`
`@@||storage.googleapis.com/xxx-mightyparty.appspot.com/builds^$third-party`

**Comment by llacb47** [comment]
They're not asking for help. They are asking for Easylist or uAssets maintainers to fix the problematic rule.

**Comment by Khrin** [comment]
@llacb47 Stop being so annoying immediately.

**Comment by llacb47** [comment]
As you wish

**Comment by NicoletteCW** [comment]
> add:
> 
> `@@||storage.googleapis.com/xxx-mightyparty.appspot.com/release_builds^$third-party`
> `@@||storage.googleapis.com/xxx-mightyparty.appspot.com/builds^$third-party`

with those lines added the game works, yes, we just need those to be added to easylist.

**Comment by NicoletteCW** [comment]
@Khrin

**Comment by llacb47** [comment]
File an issue in https://github.com/uBlockOrigin/uAssets, maybe this rules can be added/updated in the unbreak list. 

`||googleapis.com/xxx-mightyparty.appspot.com/$third-party,domain=~cuntwars.com|~nutaku.com|~nutaku.net`

**Comment by NicoletteCW** [comment]
As far as I know, with uBo unbreak, the game is already working fine; however, what we want is for it to get fixed with other adblock extensions that rely on easylist.

**Comment by Khrin** [comment]
People at ubo shouldn't even had added that rule in first place. Best fix is up to you (if you're really an admin, which I doubt it). Avoid to have your stuff spammed in other sites and everyone will be happy.

Goodbye.

**Comment by zoreu** [comment]
PR: #3920
