### ISSUE TITLE
Live chat wrongly blocked on EasyPrivacy

### ISSUE THREAD

**Issue by nimasaj** [easylist/easylist#3883]
### List the website(s) you're having issues:

`https://www.digikey.com/ordering/shoppingcart`

### What happens?

Live chat is blocked due to this filter: `||analytics-egain.com^$third-party` that could be found in EasyPrivacy list.

### List Subscriptions you're using:

EasyPrivacy on uBo

### Your settings

- OS/version: Win8-x64
- Browser/version: Version 75.0.3770.142 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin v1.21.6

### Other details:

Temporarily fixed by `@@||analytics-egain.com^$third-party`
Image: `https://pasteboard.co/IrjJfzc.png`
@smed79

**Comment by smed79** [comment]
If the tracking script from `analytics-egain.com` is blocked for privacy reasons, the rest of the page (including the chat) should still works.

The issue should be fixed by `digikey.com`, removing the dependency to tracking script.

**Comment by nimasaj** [comment]
The filter that is used in this filter list is broad and is making the issue. This is obvious that the website (`Digikey.com`) does not make changes for such issues. It's the list maintainer(s) who is(are) responsible for making the list compatible for all the websites, not the website owners. Moreover, `digikey.com` is not a personal website to ignore. It's a very big retailer website that is used by many people.

**Comment by smed79** [comment]
Above is my own point of view (_i am not an "EasyList Author"_).

Just wait a time @ryanbr or @Khrin  see your request and decide what to do.

**Comment by ryanbr** [comment]
From a test site; `https://www.wiggle.co.uk/` 
`https://analytics.analytics-egain.com/onetag/EG17998064`

https://pastebin.com/H8dzRcp4

I mean, it looks like a tracker to me.

**Comment by ryanbr** [comment]
basically egain is trading user privacy and tracking off as a "helpful live chat". Egain needs to change, really not acceptable.

**Comment by nimasaj** [comment]
You can narrow down the filter in this way:
```
||analytics-egain.com/tracker?aId^$third-party
||analytics.analytics-egain.com/onetag/^$third-party
```
This one will be allowed: `https://analytics.analytics-egain.com/iframe/EG86992109`

Also, in your test site, `https://www.wiggle.co.uk/` "Live Chat" on bottom-right corner of the page is not working. But with aforementioned filters, it will be working.

**Comment by ryanbr** [comment]
I only see `https://analytics.analytics-egain.com/onetag/...` being loaded I don't more than one script being loaded. If egain.com seperated the tracking from the livechat script stuff, then it'll be more palatable.

If the main tracking script `https://analytics.analytics-egain.com/onetag/...` needs to load, its a No from me. The filter also has been in the list since 2017.

**Comment by ryanbr** [comment]
Reaching out, but user privacy should always come first. https://twitter.com/fanboynz/status/1158650547815120897

**Comment by okiehsch** [comment]
> Also, in your test site, https://www.wiggle.co.uk/ "Live Chat" on bottom-right corner of the page is not working with EasyPrivacy and ||analytics-egain.com^$third-party. But with aforementioned filters, it will be working.

???
`||analytics-egain.com/onetag^$third-party` alone will break the Live Chat.
`https://analytics.analytics-egain.com/iframe/EG86992109` depends on that script running first.

**Comment by nimasaj** [comment]
@okiehsch ,
Yes. I tested it again and it doesn't work without loading that script first.

**Comment by ryanbr** [comment]
If egain separated the tracking/monitoring script from the live chat scripts, then we can make the filter more specific. (That is the preferred outcome) And be applicable to all the sites use its services.

**Comment by zoreu** [comment]
this specific rule solves the problem

`@@||analytics.analytics-egain.com/onetag/$domain=digikey.com`

**Comment by Khrin** [comment]
This doesn't solves anything.

**Comment by zoreu** [comment]
this script only uses a tracker, the rest is from the domain itself

Web sniffer (Chrome)
https://imgur.com/a/mldgUbS

`||analytics.analytics-egain.com^`
`||cloud-us.analytics-egain.com/tracker`

**Comment by ryanbr** [comment]
Closing this. The issue needs to be resolved at egain before its reviewed again.
