### ISSUE TITLE
agilecrm.com - webforms

### ISSUE THREAD

**Issue by mmjjb** [easylist/easylist#3892]
### Issue example site:
```
https://codepen.io/mmjjb/pen/BXYbZe
```

### What happens?

When the filter list is enabled it blocks the embedded webforms.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 10 - 17763.615
- Browser/version: Firefox 69.0b11 (64-bit)
- Adblock Extension/version: uBlock Origin v1.21.2

**Comment by ryanbr** [comment]
Well, expected if you include a script that is blocked? Would be easier to just to turn off adblocking on the site. Basically anyone could include any script used by Easylist/Easyprivacy/Fanboy Lists.. and we would be whitelisting everything.
