### ISSUE TITLE
dailymail.co.uk empty ad boxes

### ISSUE THREAD

**Issue by yourduskquibbles** [easylist/easylist#3895]
### List the website(s) you're having issues:

`https://www.dailymail.co.uk/ushome/index.html`

### What happens?

Empty ad boxes - fixed with `dailymail.co.uk##.adHolder`

Screenshot:
![dailymail](https://user-images.githubusercontent.com/22258847/62707508-7c7d7680-b9bf-11e9-81cc-b7ee61441c82.png)

### List Subscriptions you're using:

- Default uBlock Origin lists + uBlock filters - Annoyances & uBlock filters Experimental.

### Your settings

- Chrome test profile with default uBlock Origin settings and lists + uBlock Annoyances & uBlock Experimental Lists.
- OS/version: Windows 10 64bit
- Browser/version: Chrome Version 76.0.3809.100 (Official Build) beta (64-bit)
- Adblock Extension/version: uBlock Origin 1.21.7b4 (Latest Dev Build)

### Other details:

Fixed with `dailymail.co.uk##.adHolder`

**Comment by ryanbr** [comment]
Taken care of.

https://github.com/easylist/easylist/commit/c6a07611abe65ef321036f446e836ea03e8594f1
