### ISSUE TITLE
http://utahgunexchange.com/ unblocked ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#390]
`http://utahgunexchange.com/`

Unblocked ads.

**Comment by zero77** [comment]
Most of these are blocked by checking the default uBlock filter lists.

**Comment by terrorist96** [comment]
Perhaps, but not by EasyList.

**Comment by terrorist96** [comment]
@Khrin ads still there.

**Comment by terrorist96** [comment]
@mapx- this was never fixed in EL. Can it be fixed in uBO?

**Comment by mapx-** [comment]
We cannot add such filters in uBO

add
```
utahgunexchange.com##[href*="/click.track"]
utahgunexchange.com###rev_slider_1_1_wrapper
||utahgunexchange.com/*.gif$image
```

**Comment by terrorist96** [comment]
@mapx- I was more interested in having it fixed globally, not just for me. But thanks anyway.
