### ISSUE TITLE
LaunchDarkly in privacy list breaks applications that use their service

### ISSUE THREAD

**Issue by dcousineau** [easylist/easylist#391]
Recently launchdarkly was added to the EasyPrivacy list (see [commit here](https://github.com/easylist/easylist/commit/c858d871d2fa0d38ce0ea0db75fec89845d67ee0)).

LaunchDarkly is a third-party service the application authors (such as myself) opt-in to and pay for. It uses the concept of a user-id and attributes to return whether or not certain flags are enabled or not. We use it to roll out access to beta features in a controlled fashion before removal.

As it stands to use my own application I have to turn off EasyPrivacy and recommend all users turn off EasyPrivacy until either (a) we write and deploy a proxy to bypass this rule or (b) this rule is removed from the list. I would prefer not to instruct users to turn off the privacy list and frankly do not like turning it off for myself.

**Comment by adamlaunchingdarkly** [comment]
This issue can now be closed based on a commit that restricts the scope of the listing (https://github.com/easylist/easylist/commit/0356394b6210143110e2226018aafbabb5acc3b7)
