### ISSUE TITLE
Wera.de - Blocked pages (EasyList) [Issue #3788 reopen]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#3912]
The issue hasn't been fixed!

Details here:
https://github.com/easylist/easylist/issues/3788#issuecomment-520211267

**Comment by zoreu** [comment]
Got ublock right?
click update now
![ublock origin](https://i.imgur.com/VJooPnj.jpg)

**Comment by THEtomaso** [comment]
You're missing the point, zoreu.
Take a look at ryanbr's commit, and read my post (which I refered to above).

**Comment by zoreu** [comment]
I do not understand, should work

https://github.com/uBlockOrigin/uAssets/commit/eea75769dc2516c07629279a3dce56af59537090

https://imgur.com/3JdiFYQ

**Comment by THEtomaso** [comment]
> `https://imgur.com/3JdiFYQ`

That exception rule was added to '**uBlock Filters**'.
The issue still needs to be addressed at the source of the problem, which is in '**EasyList**'!
Currently, only people that use '**uBlock Filters**' is able to take advantage of the fix.
The great majority of adblock users only use '**EasyList**'!
Hope this makes things clear.

**Comment by zoreu** [comment]
PR: #3915
