### ISSUE TITLE
this script is evil

### ISSUE THREAD

**Issue by EslamGamalEssa** [easylist/easylist#3914]
https://vidstream.top/assets/jquery-3.3.1.min.js?v=2

**Comment by zoreu** [comment]
jquery? do you have a screenshot?

**Comment by krystian3w** [comment]
Diff check with any version on CDN?

**Comment by ryanbr** [comment]
I would never assume a self-host "jquery" or other popular scripts. Sites will hide dodgy scripts under various file names to avoid being blocked or being detected

**Comment by ryanbr** [comment]
Checked the script in http://jsnice.org/ looks pretty clean, not to say you can't use a jquery function to generate popups (crude). but it looks like a jquery script (atleast part of it).
