### ISSUE TITLE
Wrong regex for third-party popup blocking

### ISSUE THREAD

**Issue by jvandonsel** [easylist/easylist#3917]
I think the intention of [this commit](https://github.com/easylist/easylist/commit/bac8ee555c7accaab9746d4d9bd82ca6dcc63a11#diff-65418a6ce5b3de0fbcbf12a31c3bf8b2) was to block popups on 104.x.x.x but the regex matches any two-digit combination of [104] on the first octet, so it affects 10.x.x.x as well.

**Comment by jvandonsel** [comment]
Also the [35\.] regex is also incorrect.

**Comment by krystian3w** [comment]
Maybe wrong implement regex in ABP? uBO block local networks as you wrote.

**Comment by krystian3w** [comment]
Maybe wrong implement regex in ABP? uBO block local networks as you wrote.

---

###### Fast repair (maybe still bad):

```
/^https?:\/\/(35|104)\.(\d){1,3}\.(\d){1,3}\.(\d){1,3}\//$popup,third-party
```

I suppose all pop-ups should have `/` after IP... :thinking:?

**Comment by ChengbingLiu** [comment]
Both AdBlock and uBlock Origin block local network 10.x.x.x. I suggest a quick fix for this.

**Comment by tatref** [comment]
Also hinting this issue...
Is blocking a whole /8 a good idea, though?

**Comment by ryanbr** [comment]
Yeah that'll work.
https://github.com/easylist/easylist/commit/200587cf318a1d222164cc8b77682890acbab422

I've only seen only non-legit uses of these IP's. these ranges seem to be targeted by hackers / compromised servers. Playing cat-mouse with a new IP range was getting old.
