### ISSUE TITLE
[incorrect blocking] https://www.nutaku.net/games/cunt-wars/play/

### ISSUE THREAD

**Issue by NicoletteCW** [easylist/easylist#3918]
### List the website(s) you're having issues:

`https://www.nutaku.net/games/cunt-wars/play/`

### What happens?

Continuing the discussion of a previous [issue](https://github.com/easylist/easylist/issues/3881) that you've closed.

> People at ubo shouldn't even had added that rule in first place. Best fix is up to you (if you're really an admin, which I doubt it). Avoid to have your stuff spammed in other sites and everyone will be happy.
>
> Goodbye.

_Originally posted by @Khrin in https://github.com/easylist/easylist/issues/3881#issuecomment-520232989_

We're not spamming Nutaku with our game, they distribute the game as our partner.
It would be great if anyone could give us a single example of the game being spammed on other unrelated sites so we could change that and remove those ads. We've already told you that we're willing to cooperate and remove malicious ads if there are any.

**Comment by zoreu** [comment]
PR: #3920
