### ISSUE TITLE
[incorrect blocking] [NSFW]https://mydirtyhobby.to/

### ISSUE THREAD

**Issue by zloyden** [easylist/easylist#3919]
### List the website(s) you're having issues:
Main page: `https://mydirtyhobby.to/`

### What happens?
Site doesn't load correctly. it is broken due to this rule `/mydirtyhobby.$domain=~mydirtyhobby.com|~mydirtyhobby.de`.
I temporarily added exception for our Filters.

### List Subscriptions you're using:
EasyList

### Your settings

- OS/version: macOS Mojave 10.14.6
- Browser/version: Chrome 76.0.3809.100 (64-bit)
- Adblock Extension/version: Adblock 3.51.1

### Other details:
Original issue starts here https://github.com/AdguardTeam/AdguardFilters/issues/37784
<details><summary>Screenshot with default settings:</summary>

![Снимок экрана 2019-08-13 в 17 31 22](https://user-images.githubusercontent.com/33488229/62950191-404b7b00-bdf0-11e9-8de6-a15a0b5bd056.png)
</details><br/>
<details><summary>Screenshot with exception:</summary>

![Снимок экрана 2019-08-13 в 17 33 02](https://user-images.githubusercontent.com/33488229/62950307-6e30bf80-bdf0-11e9-9d75-8556825228cb.png)
</details><br/>

**Comment by zoreu** [comment]
PR: #3921
