### ISSUE TITLE
[incorrect blocking] www.custojusto.pt

### ISSUE THREAD

**Issue by bpic** [easylist/easylist#3922]
### List the website(s) you're having issues:
`www.custojusto.pt`

### What happens?
To reproduce:
- log into the site
- it is necessary to have more than 10 classified ads
- go to "Meus anúncios" in the top left menu "Olá YourName"
- scroll down to the bottom, click on the "Ver mais" button
- the rest of the classified ads do not load: the call to `www.custojusto.pt/user/myads/page` is blocked by the filter `myads/*`

### List Subscriptions you're using:

- Acceptable Ads
- AdBlock custom filters
- Anti-Circumvention filters
- EasyList

### Your settings

- OS/version: GNU/Linux Archlinux
- Browser/version: Version 76.0.3809.100 (Official Build) Arch Linux (64-bit)
- Adblock Extension/version: Version 3.51.1

### Other details:
Until this commit https://github.com/easylist/easylist/commit/b45cc7ba009f61b42029686f52493c12b50d5f01, the page `custojusto.pt/user/myads/` used to be whitelisted.

**Comment by Khrin** [comment]
Sorry about that, the filter has been re-added now.
