### ISSUE TITLE
googleads.github.io, github.com

### ISSUE THREAD

**Issue by llacb47** [easylist/easylist#3926]
### List the website(s) you're having issues:

`https://googleads.github.io/googleads-ima-html5/`
`https://github.com/googleads/googleads-ima-html5`
`https://github.com/googleads/googleads-ima-html5/graphs/commit-activity`

### What happens?

Breakage on `https://googleads.github.io/googleads-ima-html5/` due to Easylist filter `/googleads.$domain=~googleads.blog|~googleads.media`

Breakage on `https://github.com/googleads/googleads-ima-html5` due to Easylist filter `/googleads/*`

### List Subscriptions you're using:

Easylist

### Other details:

Suggested fix: change `/googleads.$domain=~googleads.blog|~googleads.media` to `/googleads.$domain=~googleads.blog|~googleads.media|~googleads.github.io`

The github issue happens with any similar filter in Easylist, for example `https://github.com/reclame/cn.vuejs.org` is also broken due to `/reclame/*`.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f5e8ea41112c8b6b56d5ed78ec4344139fc3dd6a
https://github.com/easylist/easylist/commit/dcc9c6136ffcde7b8e55707c12df3403948ccc8c

**Comment by llacb47** [comment]
Still broken, change `/googleads-$domain=~github.com` to `/googleads-$domain=~github.com|googleads.github.io`
