### ISSUE TITLE
DeviantArt Ad

### ISSUE THREAD

**Issue by DRSDavidSoft** [easylist/easylist#3927]
### List the website(s) you're having issues:

```
https://www.deviantart.com/
```

### What happens?

Inline ads on the main page are displayed.

### List Subscriptions you're using:

- uBlock Filters
- EasyList

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 75
- Adblock Extension/version: uBlock Origin 1.21.6

### Other details:

This is the class name for the newly displayed ads:
```
.browse-inline-ad
```

**Comment by ryanbr** [comment]
Not seeing this, where is this seen? url and screenshot?

**Comment by DRSDavidSoft** [comment]
@ryanbr It's often rendered on the main page (`https://www.deviantart.com`) in browse mode, when Eclipse is off.

I have seen it multiple times, but I'm not able to reproduce it atm for whatever reason.

I'll try to dig in to find out what exactly triggers it so I can attach a screenshot.

**Comment by ryanbr** [comment]
I guess its generic and harmless enough to add.
