### ISSUE TITLE
White list of bankofamerica.com

### ISSUE THREAD

**Issue by ligyxy** [easylist/easylist#3928]
### List the website(s) you're having issues:

secure.bankofamerica.com

### What happens?

There is a white list record for BOA, @@||bankofamerica.com^*?adx=$xmlhttprequest
while it's not working, thus the "Make payment" window is blocked. The domain should be secure.bankofamerica.com instead.

**Comment by ssb511** [comment]
Hello,
Can i know when will the easylist filter will be updated? Also is there a way to whitelist all .bankofamerica.com domains?

**Comment by ssb511** [comment]
any idea on how to escalate this to GitHub team to fix this faster

**Comment by ryanbr** [comment]
Can the user post the full url that they're trying to whitelist. @@||bankofamerica.com^*?adx= isn't that helpful.

**Comment by ssb511** [comment]
Issue raised in easylist forum. https://forums.lanik.us/viewtopic.php?f=64&t=43441

Fix for easylist is being worked. Hope it is closed soon.

**Comment by ssb511** [comment]
@ryanbr
You are showing as one of the author for easylist. Will you be able to add the whitelist for bankofamerica.com?

**Comment by Khrin** [comment]
@ssb511 or @ligyxy Please can you confirm me if the newly added filter works for you, after forcing an update of EasyList?

**Comment by ligyxy** [comment]
@Khrin Yes, I can confirm that the latest rule works correctly for me.

**Comment by ssb511** [comment]
@Khrin 
We have other make payment links are not working. Can you please add this generic filter to the whitelist. 
@@||bankofamerica.com^*?adx=$xmlhttprequest

**Comment by jwin4740** [comment]
Hello @Khrin. I work with ssb511 at bank of america.
We have made a PR "added bank of america adx for whitelist #3943".
