### ISSUE TITLE
wegner.tech bug bad request

### ISSUE THREAD

**Issue by falfan2018** [easylist/easylist#3929]
List the website(s) you're having issues:
https://wegner.tech/gZwiSDsj

What happens?
after boosting countdown get bad request and stuck

List Subscriptions you're using:
Easylist

Your settings
Browser/version: Version 76.0.3809.100 (Official Build) (64-bit)
Adblock Extension/version: uBlock Origin version: 1.21.6

Screenshot
![Annotation 2019-08-21 154035](https://user-images.githubusercontent.com/9379770/63416715-25998780-c42a-11e9-969d-e852d537c1da.png)

**Comment by ryanbr** [comment]
Anti-adblock; won't be handled by Easylist. 

Add this to your personal list:

`@@||wegner.tech^$generichide`
`@@||wegner.tech/js/ads.js`
