### ISSUE TITLE
EasyPrivacy breaks bitbucket code editor if filename is log.jsp

### ISSUE THREAD

**Issue by lol768** [easylist/easylist#3930]
![image](https://user-images.githubusercontent.com/2552726/63446669-8927b300-c432-11e9-9a1f-919f90652845.png)

This rule is way too overzealous - the `log.jsp` file here is used for accessing audit logs in an admin interface. Suggest that this rule should be confined to domains that use a `log.jsp` to actually track

**Comment by ryanbr** [comment]
If you add any number of filenames from EL or EP it'll break, If the filter was recently added, there maybe a case to remove it, but its been in EP since 2017 (at least). I'd need a better reason to change it.
