### ISSUE TITLE
datpiff.com - broken download/stream

### ISSUE THREAD

**Issue by BlazDT** [easylist/easylist#3931]
`https://www.datpiff.com/LIL-BOOSIE-Welcome-Home-Boosie-mixtape.588449.html`

Download/stream button not opening popup, also captcha iframe not showing when opening the popup then.

Temporarily fix until rule/domain is removed:

datpiff.com#@#div > iframe
@@||datpiff.com^$csp=script-src 'self' * blob: data:

`https://old.reddit.com/r/Adguard/comments/ctrzij/unblock_script_for_specific_website/`

**Comment by ryanbr** [comment]
OKay, temporarily removed. But given they are are source of ads, it'll be re-added the moment we get new reports of ads.

https://github.com/easylist/easylist/commit/bc61171cbf7577f2989a694bfc2d860602582e67
