### ISSUE TITLE
Pandora still broken with Easylist enabled.

### ISSUE THREAD

**Issue by DarkAlchy** [easylist/easylist#3934]
I use Ublock origin and if I remove Easylist and refresh then shutdown and restart the browser Pandora is fine but with Easylist enabled Pandora knows I have an adblocker running.  Been chilling waiting for a fix for almost two months and finally found this to post a ticket on.

I am not sure which item(s) in the Easylist's list is doing it but something in Easylist Pandora has latched onto.

**Comment by ryanbr** [comment]
Last time I looked at Pandora, if we "fix" it, it'll play ads if we leave it be, then it'll just complain. It still plays music. Pandora made a change, not us.

**Comment by DarkAlchy** [comment]
@ryanbr Yeah, they got better and wiser than you and figured out how to shove you into the dirt and made you useless.  All of this is a game, if you didn't know that already, where the people you block figures out how to detect you and make your stuff no longer work and you have to find a new way.  Like viruses and anti virus makers because you can't just sit back on your laurels unless you are retarded or just lazy.

I block their ads with my own rules and without Easylist they don't detect me using an adblocker and I have full usage of their service BUT when I go to Youtube, etc.... the ads are all over the place.

You seriously can't be taken as serious that you don't even look at it.  Something in your list they now detect so your list (of damn near 90k things) has to be weeded out but I have no idea which thing in it is the culprit.   As I said it is your list causing the issue and needs to be updated now for the new Pandora without forcing the end user to disable your list to listen to Pandora and reenable it for everything else.

**Comment by ryanbr** [comment]
Just whitelist pandora if you have too. But the it's either warning or ads. If we fixed, no doubt we'd get even more complaints to fix the ads instead. We can't win either way.

**Comment by DarkAlchy** [comment]
Then your listen is stupid or rather you are.

**Comment by DarkAlchy** [comment]
I had heard how lazy and stupid the easylist people were and now I know.

**Comment by llacb47** [comment]
Not constructive, you're welcome to make a pull request instead of griping.

**Comment by DarkAlchy** [comment]
Who needs to be constructive when the list holder is lazy as confirmed?  There is no reason.

**Comment by ryanbr** [comment]
See if this helps;

`@@||pandora.com^*/ads.js`
