### ISSUE TITLE
idropnews.com [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#3935]
### List the website(s) you're having issues:

`https://www.idropnews.com/giveaways/iphone-xs-max-giveaway/83175/`

### What happens?

Widget is blocked as advert.

<details>

![image](https://user-images.githubusercontent.com/8361299/63696954-91ae2e00-c824-11e9-8864-0f1aa1228cc1.png)

</details>

### List Subscriptions you're using:

Easylist

### Your settings

ABP

- OS/version: Win7
- Browser/version: Chrome 76
- Adblock Extension/version: 3.6.2

### Other details:

This widget is not ad. At least, it should not be blocked my the main Easylist filter. More likely this widget is annoying element and/or thacker.

**Comment by AnthonyBe** [comment]
These widgets are generally the primary, or one of the primary pieces of content of the page being visited.

Definitely should not be blocked!
