### ISSUE TITLE
Akamai now appears to be serving from /akam/11 not just /akam/10

### ISSUE THREAD

**Issue by birdsarah** [easylist/easylist#3936]
e.g. https://www.adidas.ca/akam/11/1b80d1ac

Ref:
https://github.com/easylist/easylist/blob/5966cb98ba726c29e6cc3847375838082f5b2636/easyprivacy/easyprivacy_general.txt#L515

**Comment by birdsarah** [comment]
Thanks @Khrin

**Comment by llacb47** [comment]
@ryanbr @Khrin they changed their urls again, see `https://publicwww.com/websites/%22%27_setAu%27%2C+%27%2Fpublic%2F%22/`
