### ISSUE TITLE
-advertisement. false detection on API requests containing IPv6 /router-advertisement/

### ISSUE THREAD

**Issue by nickhuber** [easylist/easylist#3941]
I keep running into some router management systems showing misc errors when fetching data about router advertisements. Is there a way to adjust this match to allow the word advertisement if it comes after router?

see https://en.wikipedia.org/wiki/Neighbor_Discovery_Protocol for information on this protocol.

**Comment by ryanbr** [comment]
Not sure how we could fix it here, Maybe refer to your hardware vendor?

**Comment by llacb47** [comment]
`@@||*/router-advertisement/`

**Comment by Khrin** [comment]
Since there's no possible solution on our side, this report can be closed.

**Comment by llacb47** [comment]
`Is there a way to adjust this match to allow the word advertisement if it comes after router?`

Maintainers are lying through their teeth if they say they can't write a filter that does this.
