### ISSUE TITLE
www.programme-tv.net broken

### ISSUE THREAD

**Issue by downwater** [easylist/easylist#3942]
### List the website(s) you're having issues:
www.programme-tv.net

### What happens?
The site is broken since a rule blocks non-ad content from `pmdstatic.net`:

```
||pmdstatic.net^$third-party
```

### Your settings

- OS/version: Linux Slackware64 14.2
- Browser/version: Mozilla Firefox 60.7.0esr (64 bits)
- Adblock Extension/version: uBlock Origin v1.21.2

**Comment by downwater** [comment]
Found the commit ([link](https://github.com/easylist/easylist/commit/6c64958858d0d24dbb280ef7bda700368bab4e66)). The line was added for a website www.businessinsider.fr.

The rule breaks www.programme-tv.net, without breaking www.businessinsider.fr. Both are related to pmdstatic.net, they seem belong to Prisma Media, a french group.

**Comment by okiehsch** [comment]
Other sites broken by that filter
````
http://www.voici.fr
http://www.gala.fr
https://www.capital.fr
````
