### ISSUE TITLE
White list of bankofamerica.com still not working

### ISSUE THREAD

**Issue by jwin4740** [easylist/easylist#3944]
**List the website(s) you're having issues:**
secure.bankofamerica.com

**What happens?**
We opened an issue (White list of bankofamerica.com #3928) which is now closed, but our "Make payment" window is still blocked.

I have been working with @Khrin on this issue and also work with ssb511 at bank of america.
We have made a pull request "added bank of america adx for whitelist #3943". Would you be able to approve it? It just changes one line in the white list file to the correct filter string?

**Comment by ssb511** [comment]
Thanks @jwin4740  for raising this issue again

**Comment by ssb511** [comment]
Please check this @ryanbr and @khrin. Thanks for your help!!!

**Comment by ryanbr** [comment]
Closing. Dont creating new issue reports.

**Comment by ssb511** [comment]
This is not fixed yet. We need to add a generic whitelist.

**Comment by ssb511** [comment]
@ryanbr

**Comment by Khrin** [comment]
@ssb511 Please follow #3943 .
