### ISSUE TITLE
topernews.me

### ISSUE THREAD

**Issue by Nemo64** [easylist/easylist#3946]
### List the website(s) you're having issues:

I was googleing something and was redirected to:
https://0.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds
and then to:
https://1.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds
etc
https://2.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds
https://3.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds
https://4.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds
https://5.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds
https://6.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds
https://7.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds
https://8.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds
https://9.topernews.me/?p=gq4tqmdfgu5gi3bpha3ds

### What happens?

I got this:
![Bildschirmfoto 2019-08-30 um 18 13 19](https://user-images.githubusercontent.com/1749936/64038379-30ee6080-cb58-11e9-93d9-5ad58c74fc88.png)

It says: "Click on *Allow* to prove you are not a robot.".
You normally get a query from your browser. If you block it, it'll redirect you to the next sub domain.

Looking at the source, it seems to be multilingual so even though the banner is in german, it is written via JS in ru, en, it, id, vi, ar, pl, pt, fr, de, es, th.

### List Subscriptions you're using:

uBlock-eigene Filterlisten (4/7)
uBlock filters – Annoyances​​​​​ 1.700 benutzt aus 1.700​​​​
uBlock filters – Badware risks​​​​​ 294 benutzt aus 295​​​​
uBlock filters – Resource abuse ​​​​​112 benutzt aus 112​​​​
uBlock filters – Unbreak ​​​​​1.063 benutzt aus 1.065​​​​
Werbung (2/4)
Adblock Warning Removal List​​​​​ 691 benutzt aus 700​​​​
EasyList​​​​​ 88.506 benutzt aus 88.625​​​​
Domains mit Schadsoftware (2/4)
Malware Domain List​​​​​ 1.090 benutzt aus 1.105​​​​
Malware domains ​​​​​26.888 benutzt aus 26.888​​​​
Belästigungen (6/6)
AdGuard Annoyances​​​​​ 18.463 benutzt aus 21.123​​​​
AdGuard Social Media​​​​​ 8.028 benutzt aus 8.888​​​​
Anti-Facebook List ​​​​​68 benutzt aus 68​​​​
Fanboy's Cookie List​​​​​ 15.689 benutzt aus 15.692​​​​
Fanboy’s Annoyance List​​​​​ 12.972 benutzt aus 54.673​​​​
Fanboy’s Social Blocking List​​​​​ 25.961 benutzt aus 25.981​​​​
Regionen, Sprachen (1/36)
DEU: EasyList Germany ​​​​​9.371 benutzt aus 9.390​​​​

### Your settings

- OS/version: Mac OSX 10.14.6 (18G87)
- Browser/version: Google Chrome Version 76.0.3809.100 (Offizieller Build) (64-Bit)
- Adblock Extension/version: uBlock Origin v1.21.6

### Other details:

I 'm not totally sure if this is in the easylist territory, but if it isn't i'm also not entirely sure where this is supposed to go. I definitely should be blocked.
There are also guides how to disable this already: https://malwaretips.com/blogs/remove-topernews-me/

**Comment by ryanbr** [comment]
Yeah, not easylist.

**Comment by Nemo64** [comment]
Can you give me a hint where to report this? I mean this is definitely something that must not exist.
I just reported it to googles safe browsing project ~ maybe they agree with me an mark it as malicious.

**Comment by Khrin** [comment]
Try to report it at Malware Domain List: `https://www.malwaredomainlist.com/`.
