### ISSUE TITLE
programme-tv.net [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#3947]
### List the website(s) you're having issues:

`https://www.programme-tv.net/programme/programme-tnt.html`

### What happens?

The site is broken by EasyPrivacy rule `||pmdstatic.net^$third-party`

pmdstatic.net is a CDN, an cannot be blocked completely.
`||tra.pmdstatic.net^` does not cause any issues.

Screenshot:
<details>

![image](https://user-images.githubusercontent.com/8361299/64051087-9a836480-cb82-11e9-87dc-f972e6246306.png)

</details>

### List Subscriptions you're using:

Easylist, EasyPrivacy

### Your settings

- OS/version: Win7
- Browser/version: Chrome 76
- Adblock Extension/version: 3.6.3

**Comment by downwater** [comment]
Hi,
I already raised this issue marked as #3942.
Regards.

**Comment by ryanbr** [comment]
resolved.
