### ISSUE TITLE
False positive on /videoAnalytics.

### ISSUE THREAD

**Issue by fongwh1** [easylist/easylist#3948]
### List the website(s) you're having issues:

using Synology surveillance station package

### What happens?

apps in surveillance station cannot be open due to a new javascript file "videoAnalytics.js" introduced

### Your settings

- OS/version: Windows 7
- Browser/version: Firefox 67.0
- Adblock Extension/version: 

### Other details:
Since the update of Surveillance Station 8.2.6

**Comment by Khrin** [comment]
The filter is used across multiple websites, so it can't be modified or removed. I really don't think that we can do something about.
