### ISSUE TITLE
mybluemix.net third party block

### ISSUE THREAD

**Issue by alyandon** [easylist/easylist#3952]
### List the website(s) you're having issues:

Internal hosts for IBM training/learning - would rather not disclose full URL publicly.
`*.w3bmix.ibm.com`

### What happens?

It appears that the default rule for mybluemix.net in easyprivacy_trackingservers.txt might be too broad as it appears to block necessary communication with SSO/w3id functionality hosted on mybluemix.net.  Disabling the rule in uBO for the specific site fixes the issue on my end.

I'm not really sure there is a way to narrow the scope of the rule and have it still function for its intended purpose.  I thought I'd make you aware of the issue regardless.

From uBO logs:
`
​||mybluemix.net^$third-party,​lpb-pa.w3bmix.ibm.com​,xhr​,https://lpb-security.w3ibm.mybluemix.net/api/v1/profile
`

### List Subscriptions you're using:

Whatever the defauls in uBO are.

### Your settings

- OS/version: Linux
- Browser/version: FF Developer 70.0
- Adblock Extension/version: uBO - 1.22.0

**Comment by llacb47** [comment]
For right now, you can whitelist.

Do other IBM systems with SSO (test links below) work properly?

```
https://outlook.com/ibm.com
https://wd5.myworkday.com/ibm/d/home.htmld
```

**Comment by alyandon** [comment]
I can't verify the outlook.com link as not all teams have access to Office 365.  The workday link appears to work correctly.

**Comment by Khrin** [comment]
Without a viewable example url, I really don't know how somebody is supposed to help you.

**Comment by llacb47** [comment]
@khrin how about changing the filter to `​||mybluemix.net^$third-party,domain=~ibm.com`

**Comment by alyandon** [comment]
@llacb47 Allowing `ibm.com` would certainly fix things but wouldn't that also mean that any analytic/data-collection subdomain on `mybluemix.net` would be able to collect data from public the public `ibm.com` sites?  In my mind, that kind of runs contrary to the purpose of the rule in the first place.

Now, if I understand the syntax correctly then I think if you restricted the interaction to only be allowed from origin sites matching `*.w3.ibm.com` and `*.w3bmix.ibm.com` that would open it up sufficiently for internal IBM sites to reasonably guard against breakage.

@Khrin I only opened this issue for awareness since IBM is a large company and others might have been running into the same issue.  I wasn't asking for or expecting assistance.
