### ISSUE TITLE
Unblock/Remove `CaaS` entry from the easylist_specific_block.txt

### ISSUE THREAD

**Issue by chsanthosh** [easylist/easylist#3969]
### List the website(s) you're having issues:
news.yahoo.com click on any article URL and observe the JS & CSS URL's are blocked due to this https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt#L3073 , please help remove/whitelist.

### What happens?

Styles and JS functionality is broken since the JS/CSS are blocked.
<img width="1130" alt="Screen Shot 2019-09-05 at 6 46 16 PM" src="https://user-images.githubusercontent.com/81070/64394983-7655d680-d00d-11e9-8e71-c8c5fa35a1e3.png">

URL to try : https://news.yahoo.com/conceptions-surviving-crew-members-describe-harrowing-escape-burning-225702526--abc-news-topstories.html

### Your settings

- OS/version: MAC
- Browser/version: Chrome 
- Adblock Extension/version:  3.54.0

**Comment by mundo03** [comment]
@monzta Confirmed with Yahoo the filter `||yimg.com/aaq/caas/$domain=yahoo.com` blocked some of their JS and CSS resurces, sample: 

https://s.yimg.com/aaq/caas/f5a5f3c.caas-y20_desktop.min.css 

They changed it to  https://s.yimg.com/aaq/c/f5a5f3c.caas-y20_desktop.min.css url to fix this on their end.

There are many other js/css assets under https://s.yimg.com/aaq/c/* path which are valid assets and required for page experience.

We are also looking of the rationale begind the filter `||yimg.com/aaq/caas/$domain=yahoo.com`, if you are so kind to let us now.
Thanks!

**Comment by ryanbr** [comment]
Yahoo has some funky ad scripts, so its probably a misunderstanding. I've removed the filter.
