### ISSUE TITLE
techradar.com

### ISSUE THREAD

**Issue by swindjam** [easylist/easylist#3977]
### List the website(s) you're having issues:

`https://www.techradar.com/news/mobile-computing/laptops/best-laptops-1304361`

### What happens?

We've noticed a change made on EasyList that hides our dynamic prices for Amazon on TechRadar.com.

This is the blocking rule hiding all Amazon affiliate links:
https://github.com/easylist/easylist/co ... 3ea471e463

The Amazon prices served in our widgets are up to date and link our readers to the products that they want to buy. These prices are part of our content and our content is often informed by these prices. Without them the pages don't make sense and are less beneficial to our audiences. We endeavor to show the best prices from multiple retailers to offer our audiences choice when wanting to buy a product we recommend. Amazon are a core part of this user experience, and them missing from widgets making our content less valuable to our audiences. An example can be seen here:
https://www.techradar.com/news/mobile-computing/laptops/best-laptops-1304361

We completely appreciate what easylist does and how it improves the experience of users by removing invasive or obstructive ad like elements. We hope you agree that our price comparison widgets benefit the user and do not fall into this bucket. We also understand that importance of no tracking to users who use EasyPrivacy, and to clarify we are not asking for removal from this list, only easylist

For transparency we disclose up front to our readers that we earn affiliate commissions on some product links in every page that features them. We also maintain an open and transparent dialogue with our readers, allowing them to vote on their usefulness or contact us by email if they find a better price.

Please let me know what other information I can provide to help resolve this issue.

### List Subscriptions you're using:

EasyList

### Your settings

- macOS/Mojave: 
- Chrome/76: 
- Adblock Extension/version: 

### Other details:

We have raised the issue on the EasyList forums and this rule has been removed for uBlock Origin. We were advised to also report it on the easylist repository.
https://forums.lanik.us/viewtopic.php?f=64&t=43469

**Comment by Khrin** [comment]
It's an advert and is blocked as such.
