### ISSUE TITLE
techpowerup.com broken due to a recent commit

### ISSUE THREAD

**Issue by birdie-github** [easylist/easylist#3978]
This commit https://github.com/easylist/easylist/commit/bd822135c65eea7e82d3f92d437777fbf9f771f6 has rendered many pages on TPU broken.

Example: https://www.techpowerup.com/forums/threads/engineering-sample.259054/

As you can see many images don't load.

Please revert or fix.

**Comment by Khrin** [comment]
The filter was removed yesterday. https://github.com/easylist/easylist/commit/18afbed7402ec79913bba617a3fe75240f007f2e
