### ISSUE TITLE
Google ads not blocked when searching through a mobile browser

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#4004]
### List the website(s) you're having issues:

`www.google.fi`, `google.com` (not just those, all language variants are affected)

### What happens?

Google ads are not blocked

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Android 8
- Browser/version: Firefox 68.1
- Adblock Extension/version: Ublock Origin 1.22.2

### Other details:

This rule seems to block ads whichever language variant is being used: `##div#main > div.ZINbbc.xpd.O9g5cc.uUPGi`

You can also reproduce this problem on desktop by using an user agent switcher. More comfortable than using a cell phone to investigate this. :D

This user agent can used, for example:

Mozilla/5.0 (Android 9.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0

**Comment by ryanbr** [comment]
Is still applicable? Url to test? and from which region to test from?

**Comment by peace2000** [comment]
Yes the problem is still there. For me, using Google of any region produced this problem when I tried. I'm in Finland so I use `google.fi`, try that for a sample. Search by using a word "**tietokone**" (computer) and you will se Google ads (Mainos) concerning computer sales.

And these ads are only for mobile.

![Näyttökuva (5)](https://user-images.githubusercontent.com/17256841/65819492-d6fbbc00-e225-11e9-8a89-12e37a8e68d3.png)

**Comment by peace2000** [comment]
@ryanbr @Khrin This is still relevant and the blocking rule I gave, still works.

**Comment by krystian3w** [comment]
`AdGuard Mobile Ads` does not help?

**Comment by peace2000** [comment]
No it doesn't.
