### ISSUE TITLE
rufilmtv.club [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#4014]
### List the website(s) you're having issues:

`http://rufilmtv.club/serials/zhuki-1-2-3-4-5-6-7-seriya-2-09-2019-smotret-onlajn.html`

### What happens?

Video player is blocked by EasyPrivacy. `||pladform.ru^$third-party` is bad rule and should be removed.

<details><summary>Screenshot WITH EasyPrivacy:</summary> 

![image](https://user-images.githubusercontent.com/8361299/64846456-59c12c00-d615-11e9-8501-d57008eb8792.png)

 </details>

<details><summary>Screenshot WITHOUT EasyPrivacy :</summary> 

![image](https://user-images.githubusercontent.com/8361299/64846606-b45a8800-d615-11e9-958e-a0a9813cb9b5.png)

 </details>

### List Subscriptions you're using:

Easylist, EasyPrivacy

### Your settings

- OS/version: Win7
- Browser/version: Chrome 76
- Adblock Extension/version: 3.6.3

**Comment by Alex-302** [comment]
*ping*

**Comment by ryanbr** [comment]
Fixed, but was added on request; https://github.com/easylist/easylist/commit/f5999d087e36

It seems a legit request.
