### ISSUE TITLE
sqweb.com mistakenly added to adservers list

### ISSUE THREAD

**Issue by PierreLvx** [easylist/easylist#402]
Hi,

I am working for SQweb.com. We provide two services to publishers :

- An analytics service, making calls to `edge.sqweb.com`, which is [blocked by the easyprivacy list](https://github.com/easylist/easylist/search?utf8=%E2%9C%93&q=edge.sqweb.com&type=) - we don't mind and absolutely understand.
- A subscription service named "Multipass", making calls to `cdn.sqweb.com`, which has been [recently added to the adservers list](https://github.com/easylist/easylist/commit/3a4f67c04dac014418fa657066ba140e14004507#diff-4903e7590de76df1abe1703921a2c88b).

Unfortunately because of this recent list addition, a number of legit subscribers are now unable to use the service, and have to temporarily disable their blockers/filters so that they can authenticate (client side), which is obviously not an option. Instructing them to whitelist our domain is also unpractical and unwarranted.

Since 2013, SQweb never served ads and has no interest in doing so. Instead, our mission is to encourage publishers to give their audience a paid option, for an ad-free experience.

Could you please reconsider ?

Many thanks!

**Comment by PierreLvx** [comment]
@Khrin Mentioning you, because you authored the commit (https://github.com/easylist/easylist/commit/3a4f67c04dac014418fa657066ba140e14004507#diff-4903e7590de76df1abe1703921a2c88b). Many thanks!

**Comment by ryanbr** [comment]
You're injecting ad-related content. Have you even looked at http://cdn.sqweb.com/sqweb-beta.js ? https://pastebin.com/FKtY9hvU   Looking at that script, i find nothing useful for the adblock community.

If you're going to serve legit content, don't mix Adblock in your scripts.

**Comment by PierreLvx** [comment]
Hi @ryanbr,

I do not understand what you mean by "ad-releated content". This script does two things:

1. Detect whether adblock is in use or not (using common advertising selectors, see line 780 of your pastebin), and send that information back.
2. Inject the Multipass button, and login modal in a placeholder defined by the publisher.

That's it.

**Comment by ryanbr** [comment]
Does it disable content or annoy the user (popups/css popups) in any way? ie, if you use Adblock as a standard user does it interfere with the browsing experience?

**Comment by PierreLvx** [comment]
Negative. Adblock users may only see a thin banner at the bottom of the page (akin to a cookie message), that can be dismissed or blocked. Publishers may implement their own popups, but we strongly advise against any measures that interfere with browsing on sites that offer Multipass.

**Comment by ryanbr** [comment]
It'll be discussed, for a start, remove all the adblock element checks (except one).  

http://i.imgur.com/79I7TzB.png  really unnecessary.

**Comment by ryanbr** [comment]
hmm Pierre?

**Comment by PierreLvx** [comment]
Sorry, I wasn't in the office yesterday. It'll be done in the next few hours :)

**Comment by PierreLvx** [comment]
@ryanbr We have updated the script to only attempt detection using a single ID.

**Comment by Khrin** [comment]
The filter has been removed from EasyList.

**Comment by PierreLvx** [comment]
Many thanks to you two, guys. Have a kicking weekend!
