### ISSUE TITLE
travis fail in building new EasyList version because cloning whole repo takes more than 10 minutes

### ISSUE THREAD

**Issue by gwarser** [easylist/easylist#4027]
Last good version of EasyList was created September 14, 2019 16:48:18,
and clonig repo [took 597.78s](https://travis-ci.org/easylist/easylist/builds/584973913)

Doc says: [Build Timeouts #When a job produces no log output for 10 minutes.](https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts)

**Comment by gwarser** [comment]
Just add `--depth=50` (or any sane number) to `- git clone...` line in `.travis.yml`. This should work for some time now: https://stackoverflow.com/questions/6941889/is-it-safe-to-shallow-clone-with-depth-1-create-commits-and-pull-updates-aga/21217267#21217267

**Comment by gorhill** [comment]
Even `--depth=1` should work fine, that's what I use when cloning uAssets.

**Comment by ryanbr** [comment]
Has this been resolved? or is how is it fixable?

**Comment by gwarser** [comment]
Not resolved. There are still less than one build a day: https://travis-ci.org/easylist/easylist/builds

**Comment by gorhill** [comment]
In <https://github.com/easylist/easylist/blob/master/.travis.yml>, try:

    git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylist" output

With:

    git clone --depth=1 -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylist" output

**Comment by gwarser** [comment]
All green: https://travis-ci.org/easylist/easylist/builds

Thanks @spirillen

**Comment by spirillen** [comment]
Your welcome @gwarser :+1:   I'm actually trying to see if I can get it to run a bit faster; As even a few secs counts on the number of submissions you got... and running a PR test before merge would be smart.., but more about that later...  

Now it's family time
