### ISSUE TITLE
List blocked avtc paramter on startpage 

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylist#4033]
Why do you include this line to block on startpage? What makes the parameter /avtc so "dangerous"? I've problems to connect with startpage proxy on forbes.com.

||ixquick.*/avtc?
||ixquick.*/do/avt?$image

**Comment by Khrin** [comment]
Albeit a bit slow, the Startpage inbrowsing page is working correctly for me.

**Comment by crazyyzarc** [comment]
What does the parameter avtc?

**Comment by ryanbr** [comment]
Both filters are just trackers, not sure what the question is. Not "dangerous"
