### ISSUE TITLE
adtunes.com

### ISSUE THREAD

**Issue by bug-rules** [easylist/easylist#4034]
### List the website(s) you're having issues:

`http://adtunes.com/`

### What happens?

<ul> <li>

#### Unblocked leftovers on home-page:

`http://adtunes.com/`

![obraz](https://user-images.githubusercontent.com/43518394/64993856-65dc1080-d8d7-11e9-9316-4247893f5551.png) |
---|

```
adtunes.com#?#h5:-abp-contains(Sponsors)
adtunes.com##div[id^="div-inline-"][id$="-336x280"]
```

---

 <li>

#### Incorrect blocked ads:

`http://adtunes.com/forums/showthread.php?t=91183`

No possible read start of topic. So no possible help people on this forum.

badfilter:
`###ad_thread_first_post_content`

fix: 
`adtunes.com#@##ad_thread_first_post_content`

better alternative, if ads back:
`adtunes.com##.ad_content_wrapper`

</ul>

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 69
- Adblock Extension/version: 3.6.2 

### Other details:

No worth =/= solution of remove ads.

**Comment by ryanbr** [comment]
This should clean it up better.

**Comment by bug-rules** [comment]
Realy, you no unlocked first post in topics...

`http://adtunes.com/forums/showthread.php?t=91183`

First post have embeded **only**, no all used for serve ads... text on left is SAFE.
