### ISSUE TITLE
Removing ###adhesion rules ?

### ISSUE THREAD

**Issue by sbernard31** [easylist/easylist#4035]
I suspect the rule **###adhesion** prevent this web site to work correctly : https://inscription.vbqf.fr/

Mainly because the main form is identified by "adhesion" :
```html
<form class="form-horizontal" name="adhesion" id="adhesion" method="post" enctype="multipart/form-data">
```

**Comment by Khrin** [comment]
@smed79 Please can you add something like `vbqf.fr#@##adhesion` in Liste FR? Thank you.

**Comment by sbernard31** [comment]
When this will be deployed approximately ? (I ask to check if this fix it on my side)

**Comment by llacb47** [comment]
Add `vbqf.fr#@##adhesion` to your filters

**Comment by smed79** [comment]
Fixed in **Liste_FR** https://hg.adblockplus.org/listefr/rev/1c1c078ec173

**Comment by jeanbaptistevilain** [comment]
Hi, we just faced the exact same issue as above (and actually spent quite some time to figure it out). Links with attribute `id="adhesion"` are very common in french-speaking websites (forms, tabs...). Could this very broad rule be narrowed to something more specific maybe ? (as mentioned in https://github.com/easylist/easylist/issues/3932)
