### ISSUE TITLE
sfchronicle.com empty ad boxes

### ISSUE THREAD

**Issue by yourduskquibbles** [easylist/easylist#4036]
### List the website(s) you're having issues:

`https://www.sfchronicle.com/`

### What happens?

Empty ad boxes - fixed with `sfchronicle.com##.adModule-outer`

Screenshot:
![sfchronicle](https://user-images.githubusercontent.com/22258847/65153098-2dcbef00-d9f7-11e9-940e-aa3dc0cfde31.png)

### List Subscriptions you're using:

- Default uBlock Origin lists + uBlock filters - Annoyances & uBlock filters Experimental.

### Your settings

- Chrome test profile with default uBlock Origin settings and lists + uBlock Annoyances & uBlock Experimental Lists.
- OS/version: Windows 10 64bit
- Browser/version: Chrome Version 77.0.3865.75 (Official Build) beta (64-bit)
- Adblock Extension/version: uBlock Origin 1.22.3b8 (Latest Dev Build)

### Other details:

Fixed with `sfchronicle.com##.adModule-outer`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b4717921ae1023583aae17ef3f5b5f36eececd5b
