### ISSUE TITLE
https://github.com/ADLINK-IST

### ISSUE THREAD

**Issue by rotu** [easylist/easylist#4037]
### List the website(s) you're having issues:

`https://github.com/ADLINK-IST`
`https://github.com/ADLINK-IST/opensplice`
`https://www.electronicdesign.com/industrial-automation/adlink-delivers-open-source-dds-platform`
`https://www.crunchbase.com/organization/adlink-technology`
`https://www.mouser.com/manufacturer/adlink/`

### What happens?

The entire page is blocked.

### List Subscriptions you're using:

EasyList 2.0.38.72

### Your settings

AdGuard for Safari on iOS

- OS/version: iOS 13
- Browser/version: Safari
- Adblock Extension/version: AdGuard Pro 2.1.2

**Comment by rotu** [comment]
@joespeed, maybe you should consider renaming the company? :-p

**Comment by ryanbr** [comment]
I'm fine with a domain issue, where a domain will have exemption. but every page using the name seems a bit unreasonable.

**Comment by rotu** [comment]
@ryanbr at the very least, easylist shouldn’t blacklist by string matching in github.com/<username>

How often is “adlink” blocking true positives? AdGuard and other filter lists don’t block this string in URLs
