### ISSUE TITLE
EasyList wrongfully blocking an API call to /v1/events

### ISSUE THREAD

**Issue by sontek** [easylist/easylist#4039]
### List the website(s) you're having issues:

```
http://api.eventapp.local/v1/events/?event.include=permissions&org_id=f587dbd0-5fc0-4b12-b8e0-32d24bb09d69&limit=100&offset=0
```

### What happens?
For some reason, the EasyList plugin on adblock is catching the API request to `/v1/events`.  We are an online registration provider that helps event organizers plan and run events.   The API call is to get their list of events.

All other API calls work, so it seems specific to the name "events" in the API, which I think is way to generic to be blocked.

To reproduce it you can just create an account, create an organization, and then add your first event.  You'll see listing the events in the event list API call will fail.

### List Subscriptions you're using:

<img width="839" alt="Screenshot 2019-09-19 23 52 47" src="https://user-images.githubusercontent.com/151924/65298210-a090b380-db38-11e9-8503-bffe631a7f8e.png">

### Your settings
- OS/version:  OSX 10.14
- Browser/version: Chrome v77
- Adblock Extension/version: Version 3.55.1

### Other details:

<img width="866" alt="Screenshot 2019-09-19 23 55 27" src="https://user-images.githubusercontent.com/151924/65298293-f82f1f00-db38-11e9-8f43-157993b9194f.png">

**Comment by rauchg** [comment]
We were just impacted by the same on https://zeit.co – This rule is too broad and will break too many legitimate sites.

We tracked it to this commit:
https://github.com/easylist/easylist/commit/c543fd6edb3774c1bf301c63b1d47c7459e42654

https://twitter.com/zeit_status/status/1175125729631096832

**Comment by sontek** [comment]
@rauchg Thanks for tracking it down to the specific commit!  We've also sent a message to all our customers letting them know of the issue

**Comment by ryanbr** [comment]
Site looks fine, doesn't break. And Event checks are considered monitoring/tracking.

**Comment by llacb47** [comment]
It's a company that helps plan events, I think. Not event tracking

**Comment by sontek** [comment]
@ryanbr Yeah, our site doesn't do "event checks".   Our site plans and organizes events, conferences, expos, etc.    We have nothing to do with the type of event you're trying to block, we just got caught in the crossfire

**Comment by llacb47** [comment]
Looks like it was fixed here https://github.com/easylist/easylist/commit/51f4486adafaa89fed55981605c5b1808f7e345d
