### ISSUE TITLE
[ADS] sailboatdata.com

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#4045]
### List the website(s) you're having issues:

`https://sailboatdata.com/sailboat/larsen-28`

### What happens?

Plenty of banners

### List Subscriptions you're using:

![Screenshot_20190920_222150](https://user-images.githubusercontent.com/44526987/65356581-15c1be80-dbf5-11e9-9b68-c7a709e38077.png)

### Your settings

- OS/version: Ubuntu Disco (19)
- Browser/version: FF 69.0 (64-bit)
- Adblock Extension/version: v1.22.2

### Other details:

Nope

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1414aa5ee38f4f30bd9bf036baea81f8edb2b4f4
