### ISSUE TITLE
https://anime-update4.site/view/1567835758/

### ISSUE THREAD

**Issue by Blueluelueluelue** [easylist/easylist#4046]
### List the website(s) you're having issues:

`https://anime-update4.site/view/1567835758/`
### What happens?

The anti-adblock script does not get blocked
### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/26768301/65378240-63145d80-dcd3-11e9-94f5-c4fca2cf062e.png)

### Your settings
![image](https://user-images.githubusercontent.com/26768301/65378321-49274a80-dcd4-11e9-8999-e1466690d3c3.png)
ADVANCED SETTINGS:
![image](https://user-images.githubusercontent.com/26768301/65378275-b4245180-dcd3-11e9-96ea-31491b93b49c.png)

- OS/version: Windows 10
- Browser/version: Mozilla Firefox / 69.0
- Adblock Extension/version: uBlock Origin / v1.22.2

### Other details:

Adblock detection notification:
![image](https://user-images.githubusercontent.com/26768301/65378342-b2a75900-dcd4-11e9-94b0-5c6391a18abe.png)

**Comment by ryanbr** [comment]
"This anime-update3.site page can’t be found"

**Comment by Blueluelueluelue** [comment]
Edited the issue

**Comment by ryanbr** [comment]
`@@||anime-update4.site/js/ads.js`

wont be added to Easylist,  but added some adservers
