### ISSUE TITLE
https://catchconnect.com.au/home

### ISSUE THREAD

**Issue by nobelharvards** [easylist/easylist#4047]
### List the website(s) you're having issues:
https://catchconnect.com.au/home
https://catchconnect.com.au/login

### What happens?

The page is blank apart from the top banner.

### List Subscriptions you're using:
![Subscriptions](https://user-images.githubusercontent.com/9457934/65387458-e9d84180-dd8a-11e9-886d-3d64751d4069.png)

### Your settings

- OS/version: Windows 10 1903 18362.356
- Browser/version: Brave (Version 0.67.124 Chromium: 76.0.3809.100 64 bit)
- Adblock Extension/version: Nano Adblocker v1.0.0.126 (Based on uBlock Origin Version/1.22.2)

### Other details:

When I'm subscribed to Fanboy's Annoyance List (version 201909221211), the rest of the page does not load. When I unsubscribe from it, the page loads correctly.

With Fanboy's Annoyance List (for all pages):
![Blank page](https://user-images.githubusercontent.com/9457934/65387414-7e8e6f80-dd8a-11e9-98e8-2ef9a7a77ec4.png)

What the home page is supposed to look like:
![Home page](https://user-images.githubusercontent.com/9457934/65387424-98c84d80-dd8a-11e9-88ba-466bde83ddcd.png)

What the login page is supposed to look like:
![Login page](https://user-images.githubusercontent.com/9457934/65387392-4a1ab380-dd8a-11e9-8aec-35330faaff47.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8189d27884ff6e3f1ac3b3ee3141e25359f7e790

Update in the next 20mins or so.
