### ISSUE TITLE
ngenix.net [Bad rule, EasyPrivacy]

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#4055]
EasyPrivacy contains a rule `||ngenix.net^$third-party` which blocks popular Russian CDN/DDoS protection service. Details here: https://ngenix.net/en

**Comment by Khrin** [comment]
Already removed 12 hours ago: https://github.com/easylist/easylist/commit/728db361b2af2393f007dcb8006f39ced88289a5
