### ISSUE TITLE
Remove /v1/events and /v2/events

### ISSUE THREAD

**Issue by dmmat** [easylist/easylist#4056]
Remove this rules.

https://github.com/easylist/easylist/blob/da6284246be78e71e3e7e6b4a16f209b482a102e/easyprivacy/easyprivacy_general.txt#L4838
https://github.com/easylist/easylist/blob/da6284246be78e71e3e7e6b4a16f209b482a102e/easyprivacy/easyprivacy_general.txt#L4839

Our customers have a problem with theirs calendar events.

**Comment by dmmat** [comment]
https://github.com/easylist/easylist/issues/4039

**Comment by iMarv** [comment]
Same issue for us, customers having issues connecting to live-updates.
This rule is way too broad and is probably breaking half the internet.

**Comment by spetex** [comment]
Can confirm, it breaks our API calls for stuff like:

`/v1/eventsCountsByTime` or `/v1/eventsCountsByVenue`

It is way too generic.

**Comment by llacb47** [comment]
It should not be blocking XMLHTTPRequests anymore. Tell your customers to update their filter lists and test again.

**Comment by spetex** [comment]
Verified, thanks!
