### ISSUE TITLE
Request to unblock GeoJS.io

### ISSUE THREAD

**Issue by jloh** [easylist/easylist#4057]
### Specific block

The block in question was added as part of #4044 in commit 52fb8d49ba5954e27925d48fd712460414dbf113 which blocks geojs.io as a third-party domain.

### How is it broken

This blocks the use of GeoJS as a service on websites.

### Description of why it should be removed

GeoJS is used to assist users in navigating to content more suited for their geographical location. As an example a lot of Shopify websites use this service to redirect users to a Australian store when browsing from Australia.

It does not expose information about a users IP that is not already publicly available through other means. GeoJS as a service does not track users around the web. It uses the publicly available MaxMind DBs as the source of information and has [open and transparent](https://www.geojs.io/open/) stats.

Thanks for taking the time to review and runing this list.

**Comment by ryanbr** [comment]
I'm happy to leave it.
