### ISSUE TITLE
Request to unblock: ozon.ru [🇷🇺]

### ISSUE THREAD

**Issue by TemaSM** [easylist/easylist#4058]
### List the website(s) you're having issues:

```
https://card.ozon.ru/
```

### What happens?

OZON, is probably the largest internet retailer in Russia.
This summer they launched bank card and internet-banking system for it.
I'm facing issues with their internet-banking system, while EasyList enabled.
Problem is with this rule:
https://github.com/easylist/easylist/blob/ef1564aef9aa8685b8b831919ccf611ddb5d1cb2/easylist_adult/adult_adservers.txt#L706
It blocks internet-banking system's assets.
For example:
```
https://card.ozon.ru/assets/ozon/bundle.css?f71e6166871020b5c3550df0562f34c3
```
That's why I can't simply top up my banking card via card2card via their internet-banking website.

#### EasyList
>! Checksum: gkNhvQcz+MtJ+sbGyaLEgA
>! Version: 201909231320
>! Title: EasyList
>! Last modified: 23 Sep 2019 13:20 UTC

### Your settings

- OS/version: `Windows 10 x64 (1903) Build 18362.356`
- Browser/version: `Google Chrome 76.0.3809.132 (x64)`
- Adblock Extension/version:  `Nano Adblocker 1.0.0.126 (fork of uBlock Origin)`

### Other details:

Also, this issue related to #1740
@ryanbr, please make some changes to rule or simply remove it from list (OZON is not adult at all) as soon as possible.

Thanks in advance, and huge thanks for all of your & contributors work 👍

**Comment by Khrin** [comment]
Okay, removed.
