### ISSUE TITLE
sentry.io

### ISSUE THREAD

**Issue by untitaker** [easylist/easylist#4060]
### List the website(s) you're having issues:

The issue is occuring on sentry.io. I cannot give you the URL directly because the subpage I am having issues with is not public-facing.

The XHR requests that break functionality have the following form:

```
https://sentry.io/api/0/projects/<anyorg>/relay/events/<uuid>/committers/
https://sentry.io/api/0/projects/<anyorg>/relay/events/<uuid>/attachments/
https://sentry.io/api/0/projects/<anyorg>/relay/events/<uuid>/grouping-info/
...
```

This is only reproducible by signing up to Sentry (we have free tiers) and creating a project called "relay". Then ingesting some sort of crash report. Then viewing it (where the actual blocking happens).

### What happens?

Depending on your plan, some functionality may fail to load (at least one does for sure). The rest of the site is still usable.

Note I am an employee of sentry.io. If you want to have an account where you can reproduce this issue for sure feel free to contact me at markus@sentry.io

### List Subscriptions you're using:

* easyprivacy_general, linked below in commit. UBlock tells me that it is using the rule introduced by the commit to block the requests that are failing.

(I certainly use more, but can repro with this alone)

### Your settings

- OS/version: OS X Mojave, 10.14.6
- Browser/version: Firefox 69 (nice)
- Adblock Extension/version: UBlock 1.22.2

### Other details:

The site uses several XHRs that likewise contain `relay/events`. This is caused by this commit: https://github.com/easylist/easylist/commit/ed501f5395ff33132c0b38f2495fb87080bb9509

![Screenshot 2019-09-23 at 20 19 25](https://user-images.githubusercontent.com/837573/65451446-77756900-de3f-11e9-898f-62db594d976f.png)

As seen on the screenshot we have adblock detection, but for debugging purposes for the user, not because we serve ads. Otherwise easylist does block a zendesk widget which I am not trying to argue against.

In any case the commit that introduces this problematic rule seems to target an entirely different site.

**Comment by ryanbr** [comment]
Note, Easyprivacy is a subscription for privacy, anti-monitoring and anti-logging, anti-tracking (you get the point). this commit seems to fit.

**Comment by untitaker** [comment]
@ryanbr If I use EasyPrivacy I would still expect to be able to use Google Analytics' UI to look at tracking data. This is what this is about.

The commit seems to be intended to block something on kleiderkreisel.de, and I don't know enough about that site to comment on that. The collateral damage it does to Sentry's UI seems unintended.

**Comment by untitaker** [comment]
@ryanbr our server is open source so people can self-host. I don't know the language of blocklists well enough. Can you define a whitelist?

**Comment by ryanbr** [comment]
That should be better, based on your urls.

**Comment by untitaker** [comment]
I don't know what `|` does but that seems to work, thanks

**Comment by ryanbr** [comment]
Its a delimiter. It'll stop processing

**Comment by untitaker** [comment]
Thanks for the quick response overall on this issue, I have one last question: Do you prefer to get issues on GitHub or on the forum?
