### ISSUE TITLE
Request to unblock: online.flippingbook.com

### ISSUE THREAD

**Issue by killwort** [easylist/easylist#4063]
### List the website(s) you're having issues:

`https://online.flippingbook.com/`
specifically
`https://online.flippingbook.com/view/895578/`

### What happens?

Some parts of website content is generated programmatically and deployed to AWS cloudfront with paths containing GUID split byte-by-byte. Sometimes first GUID bytes are 0xAD thus content gets blocked by generic rule
https://github.com/easylist/easylist/blob/49cb6cd62510e8c24875825b49cd471a2c1dfff2/easylist/easylist_general_block.txt#L692

So there's 1/256 probability that newly created publication will be automatically blocked.

### List Subscriptions you're using:

adblock/ublock with EasyList

### Your settings

- OS/version: windows 10/unrelated
- Browser/version: confirmed in latest FF and chrome
- Adblock Extension/version: uBlock Origin 1.22.2

### Other details:

https://github.com/easylist/easylist/blob/49cb6cd62510e8c24875825b49cd471a2c1dfff2/easylist/easylist_general_block.txt#L692

**Comment by killwort** [comment]
Thanks for the exclusion!
Though we offer custom domains for our customers so ~online.flippingbook.com will not always work. Maybe you could exclude target AWS CF distribution domain d17lvj5xn8sco6.cloudfront.net?

**Comment by Khrin** [comment]
Could you give me another example of such customized link?

**Comment by killwort** [comment]
`https://nastia.relfbo.qapubl.club/view/895578/`
That's the same publication, i've transferred it to test user with custom domain. Domain may contain anything, so it couldn't be used as exclusion literally. Could be better to exclude domain with content files  `d17lvj5xn8sco6.cloudfront.net`

**Comment by Khrin** [comment]
Ok, this should help to solve definitely.
