### ISSUE TITLE
Amazon sponsored items

### ISSUE THREAD

**Issue by siffegh** [easylist/easylist#4066]
### List the website(s) you're having issues:
Amazon. Example: `https://www.amazon.com/s?k=48+round+shoe+laces&ref=nb_sb_noss_1`

### What happens?
Sponsored items do not fully appear at/near the top of the search hits list; there is no link to open them. 

### List Subscriptions you're using:
ABP/Cash Back Shopping/Easylist/Easyprivacy/Fanboy's Annoyance List

### Your settings
- Browser/version: FF 69
- Adblock Extension/version: 3.6.3

- OS/version: 
Win7 Pro SP1

### Other details:
This does not happen with Easylist disabled.

Easylist enabled:
![Amz1](https://user-images.githubusercontent.com/18728013/65566744-cabfe800-df21-11e9-98e5-7196a82ca4e6.jpg)

Easylist disabled:
![Amz2](https://user-images.githubusercontent.com/18728013/65566791-e3c89900-df21-11e9-8e51-e8815f78b885.jpg)

**Comment by Khrin** [comment]
EasyList blocks ads. These are blocked by purpose.
