### ISSUE TITLE
Adblock detector being whitelisted by easylist

### ISSUE THREAD

**Issue by naoliv** [easylist/easylist#408]
In https://www.uol.com.br/ we can see this:

![](https://cloud.githubusercontent.com/assets/982338/26111138/ad5fcd5a-3a2a-11e7-9269-4b3f07f9d6fe.png)

It's an adblock detector, saying that we are using an adblock, and trying to explain on how to disable it.

While trying to understand why my rules for blocking this wasn't working, I saw this exception rule in easylist:

`@@||uol.com.br^*/detectadblock/$script`

Which basically is allowing the browser to load https://www.uol.com.br/camaleao/assets/web/javascript/detectadblock/adframe.js and https://www.uol.com.br/camaleao/assets/web/javascript/detectadblock/detectadblock.js (I can confirm in ublock's event log that these scripts are being loaded due to this exception rule).

Also, unless I completely misunderstand this, there are more exceptions which should really be blocking content (and not allowing them):

`@@||folha.uol.com.br/paywall/js/1/publicidade.ads.js`
`@@||jsuol.com.br/c/detectadblock/$script,domain=uol.com.br`

Edit: this rule was inserted in https://github.com/easylist/easylist/commit/0fdf86c848e0f1f5c9de1925c1a31d7577faa833

**Comment by leite** [comment]
:+1:
