### ISSUE TITLE
Github repository lytics getting blocked by the list

### ISSUE THREAD

**Issue by louim** [easylist/easylist#4080]
### List the website(s) you're having issues:
All Github repositories from the `lytics` organisation, for example: https://github.com/lytics/lytics seems to be affected by this line: https://github.com/easylist/easylist/blob/7f665ff00d4bd031f9cf0610b21a2a187ba0cc8f/easyprivacy/easyprivacy_general.txt#L2418

### What happens?
Javascripts and requests required by Github to work are blocked:
![Capture d’écran 2019-09-26 à 19 44 30](https://user-images.githubusercontent.com/923718/65732063-24492380-e096-11e9-84bf-7aea20f7240f.png)

### List Subscriptions you're using:
uBlock Origin defaults.

### Your settings
uBlock Origin defaults.

- OS/version: MacOS 10.13.6 (17G8030)
- Browser/version: Google Chrome 77.0.3865.90
- Adblock Extension/version: uBlock Origin 1.22.4

**Comment by MrBlaise** [comment]
Very much related to the arguments we make in #4067. These kind of rules doing more damage than good.

**Comment by Khrin** [comment]
"Very much related" only in your mind.

**Comment by MrBlaise** [comment]
@Khrin I mean I might be imagining things but seems like in this scenario the problem was that you guys blocked and endpoint without specifying the domain. Very much like in the /v1/events issue.

Correct me if I am wrong.

**Comment by Khrin** [comment]
I mean you have a very colourful imagination and are totally wrong. It's not the first time we add generic filters and won't be the last just because you told us so. Please don't bother to write a reply elsewhere, I'm not interested.
