### ISSUE TITLE
xda-developers.com unblocked ad

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#409]
`https://www.xda-developers.com/`
`https://www.xda-developers.com/sultanxda-bypasses-new-safetynet-unlocked-bootloader-check-on-latest-cm13-builds-for-op3/`

Unblocked ad above the `Remove All Ads from XDA` line

**Comment by zero77** [comment]
Most of these are blocked by checking the default uBlock filter lists.

**Comment by terrorist96** [comment]
Not by EasyList, though.

**Comment by terrorist96** [comment]
`https://forum.xda-developers.com/showthread.php?t=1672281`

After the initial post on a forum thread:

![image](https://user-images.githubusercontent.com/12802056/27604910-d8d09232-5b48-11e7-8545-d13e5d422a7b.png)
