### ISSUE TITLE
No-op `csp=`-based exception filters in Easylist

### ISSUE THREAD

**Issue by gorhill** [easylist/easylist#4094]
I found five `csp=`-based exception filters which do not match any blocking filters in Easylist, hence they are useless:

    @@||freebeacon.com/?s=$csp=script-src 'self' * 'unsafe-inline' 'unsafe-eval'
    @@||healthline.com/search?$csp=script-src 'self' * 'unsafe-inline' 'unsafe-eval'
    @@||kiplinger.com/search/$csp=script-src 'self' * 'unsafe-inline' 'unsafe-eval'
    @@||pocketnow.com/?s=$csp=script-src 'self' * 'unsafe-inline' 'unsafe-eval'
    @@||talkwithstranger.com/custom-search^$csp=script-src 'self' * 'unsafe-inline' 'unsafe-eval'

The `csp=` value in a `csp=`-based exception _must_ match the `csp=` value of the blocking filter it's meant to override. I could find no instance of `script-src 'self' * 'unsafe-inline' 'unsafe-eval'` in Easylist.

As a result of these exceptions never being applied, the search feature of the sites are broken:

- `https://freebeacon.com/?s=green`
- `https://www.healthline.com/search?q1=green`
- `https://www.kiplinger.com/search/index2.php?q=green`
- `https://pocketnow.com/?s=green`

I couldn't test the `talkwithstranger.com` one, I have no idea where the search feature is supposed to be.

In any case, the correct exception filters should be -- I verified they unbreak the sites:

    @@||freebeacon.com/?s=$csp=script-src 'self' * blob: data:
    @@||healthline.com/search?$csp=script-src 'self' * 'unsafe-inline'
    @@||kiplinger.com/search/$csp=script-src 'self' * 'unsafe-inline'
    @@||pocketnow.com/?s=$csp=script-src 'self' * 'unsafe-inline'
    @@||talkwithstranger.com/custom-search^$csp=script-src 'self' * 'unsafe-inline'

If ABP supports generic `csp` exception, they could be simply be rewritten as below since no other `csp` filters are applied to them:

    @@||freebeacon.com/?s=$csp
    @@||healthline.com/search?$csp
    @@||kiplinger.com/search/$csp
    @@||pocketnow.com/?s=$csp
    @@||talkwithstranger.com/custom-search^$csp

This way no need to track changes in the corresponding `csp=` block filter to ensure the exception filters still work.

**Comment by ryanbr** [comment]
I just removed them, no longer needed. But sure, I do agree but I have no say in the ABP development.

https://github.com/easylist/easylist/commit/0a7a5952a33df3bb5e5759fcbc78b95a26fb9f78
