### ISSUE TITLE
http://heromaza.in/

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#41]
`http://heromaza.in/fileDownload/43683/the_love_mashup_2016_-_dj_danish.html`

Ads showing on mobile

`https://forums.lanik.us/viewtopic.php?f=62&t=30941`

Filters That worked, Add them in EasyList

` ##a[href*=":80/key/"]`
` heromaza.in##a[href*=":80/key/"]`

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/ebd3e59bea8022426415b171b0a86dc26e5b76e4

**Comment by rajatmathurs** [comment]
Hi,

"Click Here" ads are still showing, to block them the filter that is working is listed below

`##a[href*=":80/key/"]`

Please Update the above filter in EasyList
