### ISSUE TITLE
https://flattr.com/

### ISSUE THREAD

**Issue by ThomasGreiner** [easylist/easylist#4104]
### List the website(s) you're having issues:

```
https://flattr.com/
```

### What happens?

- The cookie message is hidden if "I don't care about cookies" filter list is enabled.
- The cookie message is shown if both "I don't care about cookies" filter list and "Fanboy's Social Blocking List" are enabled.

### List Subscriptions you're using:

- Fanboy's Social Blocking List
- I don't care about cookies

### Your settings

- OS/version: Ubuntu 16.04
- Browser/version: Chrome 76
- Adblock Extension/version: Adblock Plus 3.6.3

### Other details:

This issue appears to be caused by the filter `@@||flattr.com^$generichide` in Fanboy's Social Blocking List which prevents the filters `##.cc_banner-wrapper:not(body):not(html)` and `##.cc_banner.cc_container--open:not(body):not(html)` from being applied.

See also [related Adblock Plus UI issue](https://gitlab.com/eyeo/adblockplus/abpui/adblockplusui/issues/596).

**Comment by ryanbr** [comment]
Sorted. Was originally committed here; https://github.com/easylist/easylist/commit/1f9a0d1c0d4f

**Comment by monzta** [comment]
@kiboke fyi
