### ISSUE TITLE
pop.js Block Overly Broad

### ISSUE THREAD

**Issue by zschutt** [easylist/easylist#4105]
### List the website(s) you're having issues:

Affected sites are behind authentication and not publically accessible.

### What happens?

We use a script named `POP.js` that is completely unrelated to any sort of advertisements on our site (we have no ads on it at all). The addition of `/pop.js` to `easylist_general_block.txt` is blocking the script and as a side effect everything else on the page.

In my opinion blocking `pop.js` for all sites everywhere is overly broad and has a high potential to block far more than intended considering how short and generic the script name is, as demonstrated in our case.

https://github.com/easylist/easylist/blob/master/easylist/easylist_general_block.txt#L5933

### List Subscriptions you're using:

EasyList

**Comment by Khrin** [comment]
Removed: https://github.com/easylist/easylist/commit/3961adf3c5bd3e7594021161cd30b4f0f610e53a
