### ISSUE TITLE
Easyprivacy blocks product images and background images on www.omo.com and on it's sister sites

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#4108]
### List the website(s) you're having issues:

`https://www.omo.com/fi/home.html` and almost every other it's regional sub site (there are many). Language and region selection here: `https://www.omo.com/fi/location-selector.html`

### What happens?

Product images and header background images on the top are blocked

### List Subscriptions you're using:

Easyprivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 69.0.1
- Adblock Extension/version: Ublock Origin 1.22.4

### Other details:

Here is a rule that fixes everything:
`@@||unileversolutions.com/*analytics.js$script,domain=www.omo.com|www.persil.com|www.skip.com|www.via.se|www.biotex.dk|www.breeze.com.ph|www.breeze.co.th|www.surfexcel.lk|www.surfexcel.in|www.rinso.com|www.surfexcel.pk|www.surfexcel.com.bd|www.deja.com.ec|www.fab.com.co|www.ala.com.ar|breeze.com.my|www.breeze.sg`

A couple of all the regions under the language selector were not affected (they did not use the analytics script of unileversolutions). Also the last two domains did not work but I'm not sure if they are down temporarily or for good so I added them also to be sure.

However maybe it would be better to make a general whitelist rule such as `@@||unileversolutions.com/*analytics.js$script` instead of a big list of domain based exceptions? Maybe blocking that script could cause breakages on other different domains also?

**Comment by Khrin** [comment]
@okiehsch You can remove that filter now.

**Comment by okiehsch** [comment]
Thanks for the heads up but I actually did not allow the request with my filter.
I used a redirection filter, the tracking script remains blocked without any breakage.
