### ISSUE TITLE
Blocking /thermostat. is too broad and breaks legitimate sites

### ISSUE THREAD

**Issue by jgeiger** [easylist/easylist#4114]
### List the website(s) you're having issues:

www.mynexia.com

### What happens?

A thermostat UI element fails to render because /thermostat.js is being blocked.

### List Subscriptions you're using:

easylist -> easyprivacy

### Your settings

I'm using uBlock origin in Chrome on Linux Mint. The uBlock log shows the specific rule that the file is being blocked because of. This issue only appeared yesterday after the block list was updated.

### Other details:

This seems to have been added by https://github.com/easylist/easylist/commit/73eca1f6d7aeb46bf7527591d378977a8f819044

I argue that blocking all "/thermostat." is far too broad since it may cause other online IoT/Home automation websites to break.

**Comment by gorhill** [comment]
"thermostat" is a generic word, unrelated to tracking -- why is this filter not narrowed to `royle.com`. On top of this the code in that `thermostat.js` file sure look like custom code, not that of a library, so highly unlikely this will be found elsewhere than on that one `royle.com` site.

After the discussion I thought the bar on adding generic filters would be put higher.
