### ISSUE TITLE
Generic host `blob.core.windows.net` should not be blocked

### ISSUE THREAD

**Issue by justdmitry** [easylist/easylist#412]
Hi,

List `RU AdList` (version `201705180800`) contain listing for `||blob.core.windows.net^$third-party,script`

But this host (*blob.core.windows.net*) is well-known parent hostname for all storage accounts, offered by Microsoft Azure (with their Azure Blob Storage feature). It should not be blocked.  Specific subdomains (like something.blob.core.windows.net) should be blocked, not common parent host.

**Comment by Khrin** [comment]
This list is not under our comtrol, you can contact them via https://forums.lanik.us/viewforum.php?f=102
