### ISSUE TITLE
justanswer.com: Intrusive and deceiving pseudo-popup

### ISSUE THREAD

**Issue by Zenexer** [easylist/easylist#4128]
This is a follow-up to https://github.com/easylist/easylist/issues/2897, as the pop-up has returned:

![image](https://user-images.githubusercontent.com/504130/66326955-f1a1f500-e8f7-11e9-8739-86b8a702a6de.png)

The pop-up doesn't always appear on that site; I've been browsing that site for about an hour or two and it has only just appeared.  It is clearly deceptive as it wouldn't be clear to the average user that the prompt is an advertisement for a third-party service.

I'd like to suggest that attempts to load scripts and stylesheets from `*.justanswer.com` be blocked on third-party sites.

**Comment by llacb47** [comment]
`||justanswer.com$third-party` Fanboy annoyances?

**Comment by Zenexer** [comment]
It's an ad, so does it make sense for it to be in annoyances?

**Comment by peace2000** [comment]
Is this still valid?

**Comment by llacb47** [comment]
On up to/over 600 sites, yes. `https://publicwww.com/websites/%22justanswer.com%22/`

Example: `https://www.healthhype.com/` Some sites seem like low-quality affiliate spam promoting the site `justanswer.com`.
