### ISSUE TITLE
tracing server, but which list

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#4130]
### Other details:

I've found this `||cdn.polyfill.io/v2/*$script` from various site, eg. NSFW so not listed here

According to polyfill.io  "lack of" [privacy-policy](https://polyfill.io/v3/privacy-policy/) we'll see there are tracking way too much to be acceptable 

![Screenshot_20191007_223927](https://user-images.githubusercontent.com/44526987/66346865-60606c00-e953-11e9-885c-e27a0066b486.png)

But which list should this be added too??

Internal related: [#249](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/249)

**Comment by llacb47** [comment]
Polyfill is not tracking, if you block that by your logic you must block jquery and any other third-party JS library.

**Comment by spirillen** [comment]
A snippet of there "Privacy Policy"

```
In order to provide the polyfills, the Service receives from your browser certain technical information including:
* browser details;
* connection details (such as your IP address which can identify your approximate location and/or name of your ISP);
* the URL of the web page which has made the request to the Service. 

We use that information to determine which polyfills are required by your browser. We then retain only the following information:

* the domain of the web page which has made the request to the Service;
* the user agent string for your browser;
* the set of polyfills that were requested by the web page

The website which uses the polyfills is not subject to this privacy policy. We are not responsible for third party websites’ content, use of personal information, or security practices.
```
< They say.... where is it they differ from google??

I find it hard not calling then Tracing/Spying...

@llacb47 I would like to here your arguments why you `polyfills` with this information NOT should be considered as tracing/spring

**Comment by llacb47** [comment]
That is the purpose of their service, they use your user agent to determine which browser features are not supported and need to be "polyfilled".

```
Polyfill Service provides snippets of code, called “polyfills”, that allows websites operated by FT and by others to provide a consistent experience across different browsers. When you load a web page which uses Polyfill Service, your browser will download any polyfills required in order to present the web page successfully in your browser.

In order to provide the polyfills, the Service receives from your browser certain technical information including:

browser details;
connection details (such as your IP address which can identify your approximate location and/or name of your ISP);
the URL of the web page which has made the request to the Service.
We use that information to determine which polyfills are required by your browser. We then retain only the following information:

the domain of the web page which has made the request to the Service;
the user agent string for your browser;
the set of polyfills that were requested by the web page.
The information we retain cannot identify you. We retain it in order to identify which websites are using the Service and whether any websites are abusing the Service.
```

**Comment by spirillen** [comment]
But they don't eg. need any IP for that..., they don't need to log which IP that comes from where going to where.....

```
connection details (such as your IP address which can identify your approximate location and/or name of your ISP);
the URL of the web page which has made the request to the Service.
-----
**_We then retain only the following information:_**
the domain of the web page which has made the request to the Service;
the user agent string for your browser;
the set of polyfills that were requested by the web page.
```

This one demand more than ordinary trust...

```
The information we retain cannot identify you. We retain it in order to identify which websites are using the Service and whether any websites are abusing the Service.
```
^ They have your IP, They have the site you visited...

Personally, it's on my list of mistrust, for data collecting

**Comment by spirillen** [comment]
> Every single service and website you ever use receives your IP address, it's a basic fact of TCP/IP networking.

Is it... Thanks good for the information, I never knew that......

This is third party and It have no use in practice, I have had them block for month and never had any issues NOT SHARING my information with this "service"

**Comment by llacb47** [comment]
OK, if you don't use an older browser then you can probably safely block, probably not a good fit for EasyPrivacy however.

**Comment by costpermille** [comment]
> ^ They have your IP, They have the site you visited...

They claim to explicitly not retain it. I don't believe it is identifying data to have a user-agent by itself. 

That being said, it is /v3/ now.

**Comment by Khrin** [comment]
I don't think it's a tracker.
