### ISSUE TITLE
[ad network] gelirartisi - app.gelirartisi.com

### ISSUE THREAD

**Issue by ahmedtds** [easylist/easylist#4139]
it's an ad network: http://www.gelirartisi.com/index.php?lang=eng

makes this request which slows pages a little:
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 |  |  | eksisozluk.com | 3 | script | `https://app.gelirartisi.com/withdfp.js?sid=6` |
</details>

not sure if this fits into adblocking or privacy filters but app.gelirartisi.com should be blocked

originally reported here https://github.com/uBlockOrigin/uAssets/issues/6418 but they advised to report to easylist

**Comment by Khrin** [comment]
I believe this shouldn't be blocked by EasyList, but by a Turkish Adblocking list, of which I'm afraid but I don't know if one exists...

**Comment by llacb47** [comment]
Isn't it still an ad network nonetheless?

There is a Turkish list here `https://filters.adtidy.org/extension/chromium/filters/13.txt` `https://github.com/AdguardTeam/AdguardFilters/tree/master/TurkishFilter`

**Comment by Khrin** [comment]
Could well be, but honestly I can't see any unblocked adverts on the references website, and anyway looks like completely in Turkish. `gelirartisi.com` is geo-blocked for EU users.
