### ISSUE TITLE
autoreview.ru [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#4150]
### List the website(s) you're having issues:

`https://autoreview.ru/articles/krash-testy/arkana`

### What happens?

Useful image is blocked.

<details><summary>Screenshot with EasyList:</summary> 

![image](https://user-images.githubusercontent.com/8361299/66575702-1065ed00-eb7f-11e9-8565-a6994400ca9a.png)
 </details>

<details><summary>Screenshot without EasyList:</summary> 

![image](https://user-images.githubusercontent.com/8361299/66575879-663a9500-eb7f-11e9-9339-ebcdc36df392.png)

 </details>

Caused by `/reklama/*`

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Win7
- Browser/version: Chrome 77
- Adblock Extension/version: 3.6.3

**Comment by Khrin** [comment]
Perhaps is better to have this issue fixed by the Ruadlist? (If it isn't already fixed there?) @dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@Khrin 
This has already been fixed: https://hg.adblockplus.org/ruadlist/rev/27ca9b49f95b

**Comment by Khrin** [comment]
Ok, then. I guess this is fine enough as it is.

**Comment by Alex-302** [comment]
@Khrin No. The issue is caused by EasyList, so should be fixed in the filter, wheck causes it.

**Comment by Khrin** [comment]
No, EasyList has never fixed false positives for websites in any other languages than English, if a relevant subscription list already existed.

**Comment by Alex-302** [comment]
@Khrin even if bad rile is in EasyList? Ok then.
