### ISSUE TITLE
https://neel.egybest.site/ (incorrect blocking)

### ISSUE THREAD

**Issue by unistinger** [easylist/easylist#4155]
### List the website(s) you're having issues:
`https://neel.egybest.site/`

### What happens?
This wbsite is able to detect ad blocking

### List Subscriptions you're using:

Nano Adblocker
### Your settings

- OS/version: Windows 10 Pro for Workstations
- Browser/version: Firefox 69.0.3 (64 bit)
- Adblock Extension/version: 
Version: 1.0.0.127

**Comment by llacb47** [comment]
Try AdGuard if you really need to use this website.

https://github.com/NanoAdblocker/NanoFilters/issues/376

**Comment by Khrin** [comment]
Anti Adblocking messages aren't blocked by EasyList.
