### ISSUE TITLE
Easyprivacy breaks https://apps.asendiausa.com/tracking/

### ISSUE THREAD

**Issue by monterrr** [easylist/easylist#4156]
### List the website(s) you're having issues:

`https://apps.asendiausa.com/tracking/`

### What happens?

Easyprivacy breaks the site

### List Subscriptions you're using:

Easyprivacy

### Your settings

- OS/version: Fedora 30 workstation
- Browser/version: Firefox 69
- Adblock Extension/version: Ublock origin 1.22.4

**Comment by Khrin** [comment]
Fixed, you'll need to wait some minutes before updating EasyPrivacy.
