### ISSUE TITLE
[AdWare, Tracking?, Url-Redirector] 22pixx.xyz

### ISSUE THREAD

**Issue by yspmedia** [easylist/easylist#4177]
### List the website(s) you're having issues:

`22pixx.xyz`

`https://22pixx.xyz/ia-o/2019/10/18/5da9baa5e4393.jpeg.html`

### What happens?

See attachement in this [thread](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/262) as GH won't allow me to attach here "Something went really wrong, and we can't process that file"

### List Subscriptions you're using:
Ublock/Easylist + https://anonymousposter.gitlab.io/ublockorigin-rules/blockrules.txt

### Your settings

- OS/version:  Linux
- Browser/version:  FF 69.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin v1.22.4

**Comment by krystian3w** [comment]
Yeah fake, no possible upload photo their.

**Comment by spirillen** [comment]
Hi @Khrin nice finding `jads.com` :smiley: The world is now a better place :medal_military:
