### ISSUE TITLE
Easy privacy breaks www.techrepublic.com

### ISSUE THREAD

**Issue by monterrr** [easylist/easylist#4185]
### List the website(s) you're having issues:

`https://www.techrepublic.com/`

### What happens?

Images break.

### List Subscriptions you're using:

Easy List
Easy privacy

### Your settings

    OS/version: Fedora 30 workstation
    Browser/version: Firefox 69
    Adblock Extension/version: Ublock origin 1.22.4

### Other details:

Easy privacy

**Comment by THEtomaso** [comment]
@okiehsch:

> `||cbsistatic.com/*/dw-tracking$script,important,redirect=noopjs,domain=techrepublic.com`
This rule breaks all of the images @ `techrepublic.com`, when using Pale Moon with uBO Legacy!

Possible fix (for '**uBlock filters - Legacy**'):
`||cbsistatic.com/*/dw-tracking$script,important,redirect=noopjs,domain=techrepublic.com,badfilter`
