### ISSUE TITLE
Updated: No Images at all on survivalmesserguide.de with EasyList activated (Desktop Chrome, Firefox)

### ISSUE THREAD

**Issue by Hennes79** [easylist/easylist#4194]
### List the website(s) you're having issues:
`https://survivalmesserguide.de/fahrradlampe-was-ist-erlaubt/`

### What happens?
When using Firefox or Chrome on desktop computer with EasyList active, images on the site aren't showing: title image, sidebar image, images within the article.

Page looks fine on Firefox and Chrome with EasyList off. 

See side by side comparison on the screenshot attached.

It seems to be an issue with my ad provider's "Lazy load images" feature. With "Lazy load images" activated, all images are blocked by the EasyList adblocker.

When right-clicking on where the image is supposed to be and try to open it, I get redirected to a new tab with the following address:
`data:image/svg+xml,%3Csvg xmlns%3D"http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg" width%3D"1024" height%3D"536"%3E%3C%2Fsvg%3E`

### List Subscriptions you're using:
EasyList

### Your settings

- OS/version: Windows 10 Pro Version 1903, Build 18362.418
- Browser/AdBlock/:
              - Firefox 69.0.3 (64-Bit) with uBlock Origin v1.18.6, 
              - Chrome Version 77.0.3865.120 (Offizieller Build) (64-Bit) with AdBock Version 3.60.0

### Other details:

![adblock](https://user-images.githubusercontent.com/52085472/67474064-1b774d80-f654-11e9-8a26-31a11208f00a.png)

**Comment by Hennes79** [comment]
Edit: Same issue on Chrome with EasyList activated

**Comment by krystian3w** [comment]
`uBlock Origin v1.18.6, AdBock Version 3.60.0`

choice one and disable second.

**Comment by Hennes79** [comment]
> 
> 
> `uBlock Origin v1.18.6, AdBock Version 3.60.0`
> 
> choice one and disable second.

Hi krystian3w,

Thank you for the input.

These adblocks are for different browsers. FIxed teh description to make it more clear. 

I am using Firefox 69.0.3 (64-Bit) with uBlock Origin v1.18.6, as well as Chrome Version 77.0.3865.120 (Offizieller Build) (64-Bit) with AdBock Version 3.60.0.

One Adblock per Browser.

**Comment by peace2000** [comment]
This seems to be ok now, fixed by other modifications. @Khrin
