### ISSUE TITLE
Websites Still Show Ads

### ISSUE THREAD

**Issue by GKid94** [easylist/easylist#4196]
`https://www.vesti-online.com/`
`http://www.rts.rs`
`https://pcpress.rs`
`https://www.blic.rs`
`https://www.happytv.tv/`
`https://idjtv.com`
`https://dnevnik.hr/`
`https://novosadska.tv/`
`http://www.rtvpink.com/`
`http://www.pink.rs/`
`https://www.danas.rs`

**Comment by smed79** [comment]
@monzta @wizmak

**Comment by peace2000** [comment]
Better to make one issue per website. Also it's harder to distinguish ads that are not in English (at least for me). Can you post screenshots where you have marked ads clearly?
