### ISSUE TITLE
http://songmix.in/

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#42]
`http://songmix.in/filelist/251/7_hours_to_go_2016_movie_mp3_songs/new2old/1.html`

Ads showing on mobile

`https://forums.lanik.us/viewtopic.php?f=62&t=30942`

Filters That worked, Add them in EasyList

` ##a[href*=":80/key/"]`
` songmix.in##a[href*=":80/key/"]`

**Comment by monzta** [comment]
Added https://github.com/easylist/easylist/commit/ce0031411bafbfaf30b32fb355092d4a4964e829
