### ISSUE TITLE
Github User Tracking

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#4204]
### List the website(s) you're having issues:

`gitlab.com`

### What happens?

As I'm ready trough the "new"  `accept of further privacy invasive tracking` I stubled on the following scripts, that comes with the use of the above product, Hosted and self hosted.

### Other details:

The scripts in question is the following
* https://gitlab.com/gitlab-org/gitlab/blob/master/app/views/layouts/_google_analytics.html.haml
* https://gitlab.com/gitlab-org/gitlab/blob/master/app/views/layouts/_piwik.html.haml
* https://gitlab.com/gitlab-org/gitlab/blob/master/app/views/layouts/_snowplow.html.haml (EasyPrivacy)

I'll assume you already aware of all three scripts and have added the right code, but just for "Better safe than sorry" 

I ask for a check as the only one I've ever seen my self is `snowplow`

PS: Thanks for you good work :smiling_imp:

**Comment by Khrin** [comment]
I don't see any unblocked trackers on GitLab, for the time being.
