### ISSUE TITLE
Can't log in to coastcapitalsavings.com

### ISSUE THREAD

**Issue by mica** [easylist/easylist#4205]
Some filter or another in uBlock Origin is breaking the ability to log in to: https://banking.coastcapitalsavings.com

**Comment by llacb47** [comment]
Post your logger output. Also disable every list but easylist and easyprivacy to make sure that they are the culprit

**Comment by mica** [comment]
It's EasyPrivacy. Here's what's being blocked:
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | \|\|googletagmanager.com/gtm.js?$third-party | -- | banking.coastcapitalsavings.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-MKTXSV9` |
| +2 | /fingerprint2.min.js | -- | banking.coastcapitalsavings.com | 1 | script | `https://banking.coastcapitalsavings.com/Scripts/services/fingerprint2.min.js?0.14.38` |
| +1 | /fp/tags.js? | -- | banking.coastcapitalsavings.com | 1 | script | `https://cdn.coastcapitalsavings.com/fp/tags.js?org_id=70u4utao&session_id=842ae791-2b31-4fda-bf33-f40581dc25e7` |
| +1 | /ruxitagentjs_ | -- | banking.coastcapitalsavings.com | 1 | script | `https://banking.coastcapitalsavings.com/ruxitagentjs_ICA2SVfhjqru_10177191024092634.js` |
</details>

**Comment by peace2000** [comment]
@mica Many might not have an account there so it's not easy to test. You managed to post requests that are blocked by Easyprivacy. Can you whitelist them one by one and test which one of those is the culprit to your login problems?

Imo, that fingerprint script sounds like something that shouldn't be blocked. Can you test with this filter?

`@@||banking.coastcapitalsavings.com/Scripts/services/fingerprint2.min.js`

**Comment by mica** [comment]
Looks like they fixed it on their end. I can log in fine now. Thanks
