### ISSUE TITLE
Video cannot play at https://replay.lsm.lv

### ISSUE THREAD

**Issue by soshial** [easylist/easylist#4206]
### List the website(s) you're having issues:
`https://replay.lsm.lv/lv/tiesraide/ltv1`

### What happens?
Still image instead of video.

### List Subscriptions you're using:
Only EasyList

### Your settings
- OS/version: MacOS Mojave 10.14.6 (18G103)
- Browser/version: Firefox 70.0.0 (64-bit)
- Adblock Extension/version: uBlock Origin v1.23.0

**Comment by THEtomaso** [comment]
Try using **Latvian List**:
`https://notabug.org/latvian-list/adblock-latvian/`

**Comment by THEtomaso** [comment]
Then report the issue here:
`https://notabug.org/latvian-list/adblock-latvian/issues/`

**Comment by soshial** [comment]
But rules, that block playing video are only inside EasyList, not in Latvian EasyList.
Please, please explain to me, why should I write to them, if Standard EasyList does block playing.
I can't figure out the logic.

**Comment by THEtomaso** [comment]
Video issues often requires rather advanced fixes.
Therefore, site-specific rules, required for non-English pages, are usually handled by regional filters.

Like stated @ `https://notabug.org/latvian-list/adblock-latvian#latvian-list`:

> The Latvian List is for use with EasyList and EasyPrivacy.

..But of course, you can wait and see if someone adds a fix in EasyList too. :)

**Comment by soshial** [comment]
Created a bug: https://notabug.org/latvian-list/adblock-latvian/issues/9
