### ISSUE TITLE
bitly.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#4214]
https://bitly.com/

ABP 3.7, EasyList, Fanboy's Cookie List

Screen: https://imgur.com/a/GkNz7Rn

May be `bitly.com###banner-spacer`?

**Comment by krystian3w** [comment]
IMO no enough, CSS is needed to move up header navigation after scroll:

![obraz](https://user-images.githubusercontent.com/35370833/68411739-4cdf3580-018b-11ea-82bf-3d0746850c9c.png) |
--- |

uBO / AdGuard:

`bitly.com##header.sticky.gdrp-on.is-stuck:style(margin-top: 0 !important;)`


---

@BlazDT / @mapx- "`gdrp-on`" so in Annoyance section.

@kiboke - add accept cookies bar in Addon?

**Comment by kiboke** [comment]
No need, just block gdpr.js

**Comment by BlazDT** [comment]
Blocked gdpr.js in AdGuard Annoyances filter.

**Comment by Khrin** [comment]
`/gdpr.js` is already present in Fanboy's cookie list.
