### ISSUE TITLE
Ads and tracking 

### ISSUE THREAD

**Issue by raptorjeosos** [easylist/easylist#4224]
https://v1.mrpiracy.top

**Comment by FabioPeixeiro** [comment]
Same problem here

**Comment by Khrin** [comment]
More (if any) details about will be warmly welcomed.

**Comment by spirillen** [comment]
I don't speak Spanish/Portuguese but this looks like there <re some text banners in the blue field

Also in the top, right below the menu.

`Ùltimas Noticlas`

<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/68534714-e51a1d80-0337-11ea-8edd-ad16e2209d8f.png)

</details>

Just a two cent if this was any help...

**Comment by FabioPeixeiro** [comment]
Yes, currently it appears to be working now, we can see the movies with AdBlock turned ON, the blue field says that you must login to watch the movies/series.
It is working now and no need to fix.

**Comment by raptorjeosos** [comment]
Can confirm. All working right now.
