### ISSUE TITLE
video.vice.com [Incorrect Blocking]

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#4230]
### List the website(s) you're having issues:

`https://video.vice.com/de/video/vice-barcelonas-drug-squats/5c6a9a97be407732c50091b3`

### What happens?

I can’t play the video until i accept cookies but the cookie banner is blocked by EasyPrivacy

### List Subscriptions you're using:

uBlock Origin default settings

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 70
- Adblock Extension/version: uBlock Origin v1.23.0

### Other details:

When i whitelist `sourcepoint.vice.com` the cookie banner appear (i need the banner to accept cookies).

**Comment by krystian3w** [comment]
Pop-up is broken also, after clear cookies and local-storage newer comeback and video again broken.

**Comment by krystian3w** [comment]
https://github.com/NanoMeow/QuickReports/issues/2255

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishCookieConsent/issues/33 https://github.com/easylist/easylist/issues/14059 https://github.com/AdguardTeam/AdguardFilters/issues/43779
