### ISSUE TITLE
hartziv.org

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#4231]
### List the website(s) you're having issues:

`https://www.hartziv.org/news/20191025-licht-aus-stromsperren-fuer-hartz-iv-empfaenger.html`

### What happens?
Ad picture at the middle of the page

### List Subscriptions you're using:

uBlock Origin default settings

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 70
- Adblock Extension/version: uBlock Origin v1.23.0

### Other details:

The ad is coming from `a.partner-versicherung.de`

**Comment by Khrin** [comment]
Please re-open this in https://github.com/easylist/easylistgermany
