### ISSUE TITLE
Think Mobiles Still Showing Ads

### ISSUE THREAD

**Issue by GKid94** [easylist/easylist#4236]
This website is still showing ads `https://thinkmobiles.com/blog/best-tank-games/`

**Comment by GKid94** [comment]
Why did you close the issue

**Comment by llacb47** [comment]
Because it was fixed in commit https://github.com/easylist/easylist/commit/5abaaefc63f76d2fa03e29112f52905e6bcd0f35

**Comment by GKid94** [comment]
Oh ok, thx
