### ISSUE TITLE
lanik.us down?

### ISSUE THREAD

**Issue by gotitbro** [easylist/easylist#424]
I don't know where else to ask this question. I just visited https://forums.lanik.us and it looks like its redirecting me to https://forums.lanik.us/cgi-sys/defaultwebpage.cgi.

Am I the only one facing this issue? I think there might be a configuration problem with the website.

@mapx- @smed79 Please clarify this problem.

Thank You

**Comment by mapx-** [comment]
it's ok as I can see. If still in trouble just delete cookies + storage for lanik and try again.

**Comment by SMed79** [comment]
No problem here.

**Comment by gotitbro** [comment]
@mapx- @SMed79 Thanks for the confirmation. I was able to access the site after completely erasing the browser data (deleting the data for lanik.us only did not work).
