### ISSUE TITLE
volstqkwmth.com should be blocked

### ISSUE THREAD

**Issue by timmc** [easylist/easylist#4248]
### List the website(s) you're having issues:

Example page: `https://www.fluentu.com/blog/spanish/spanish-podcasts/`

### What happens?

Many ads appear on the page.

### List Subscriptions you're using:

- uBlock Origin built-ins
- EasyList
- EasyPrivacy
- Malware domain list
- Malware Domains
- Peter Lowe’s Ad and tracking server list

as well as some of my own filters.

### Your settings

- OS/version: Debian Linux 10
- Browser/version: Firefox 68.2.0esr
- Adblock Extension/version: uBlock Origin 1.23.0

### Other details:

- Adding the filter `volstqkwmth.com` prevents these ads. (They're coming from a subdomain.)
- I don't know what that domain is, but a different subdomain shows up on an Adblock anti-circumvention list: https://github.com/abp-filters/abp-filters-anti-cv/blob/master/english.txt#L231

**Comment by spirillen** [comment]
Thanks for [sharing](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/491) :smiley:

**Comment by ryanbr** [comment]
If its still an issue, report in the anti-cv list https://github.com/abp-filters/abp-filters-anti-cv/

**Comment by llacb47** [comment]
@timmc it was already fixed in uBo, don't bother https://github.com/uBlockOrigin/uAssets/commit/f50613ff43a6deb313a267641652881ec0537c34

**Comment by timmc** [comment]
@ryanbr I'm confused about what, exactly, the relationship between all these things is, or why this ad domain shouldn't be in EasyList. But if you say so!
