### ISSUE TITLE
pixlee.com [Incorrect Blocking]

### ISSUE THREAD

**Issue by jchen123** [easylist/easylist#4250]
### List the website(s) you're having issues:

`https://www.article.com/`

### What happens?

We (Pixlee) are a SaaS platform for brands to showcase their customers UGC on their own sites. Article as an example is a customer.

This commit

`https://github.com/easylist/easylist/commit/52b7ee5bcd79caa0e3475cd33b8753b704e4285d` blocks our entire domain, which includes images.

With adblock:

`https://cl.ly/4ec279ec184e/Image%202019-11-05%20at%204.23.00%20PM.png`

Without adblock:

`https://cl.ly/edd8e102665e/Image%202019-11-05%20at%204.23.15%20PM.png`

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Mac OS Catalina
- Browser/version: Chrome 78.0.3904.70
- Adblock Extension/version: uBlock Origin 1.23.0

### Other details:

We'd like to replace the `pixlee.com` block with a block for `tinyrick.pixlee.com` and `inbound-analytics.pixlee.com` which are the only endpoints that receive our anonymous, non PII events for tracking the number of clicks that occur on our widgets.

Thank you!

**Comment by spirillen** [comment]
Ain't you missing one?

`instafeed-api.pixlee.com.inscname.net`

As this appears in our RPZ unfortunately without record for origin, which means it have been imported from an external source at one point

**Comment by jchen123** [comment]
@spirillen great catch, but that's actually a subdomain for our free tool but we actually don't track those events at all.  instafeed-api.pixlee.com is just our API, so I think we're okay there?

**Comment by spirillen** [comment]
Hi @jchen123 

First, thanks for a fast reply :smiley: 
Second, damned, this is a really rare thing that one who do some tracking, actually seems to be open about how and which domains is used for this bad habbit :+1: 

Third, would it be possible that you check up on that domain, just to be sure that I don't delete something that should have been deleted. The reason is, it is still resolving to 
```
instafeed-api.pixlee.com.inscname.net. 600 IN CNAME ins-082.inscname.net.
ins-082.inscname.net.   3600    IN      CNAME   a-sg07sl05.insnw.net.
a-sg07sl05.insnw.net.   3600    IN      A       192.33.31.166
```
If you have a gitlab account you can response directly to this [thread](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/495)

**Comment by jchen123** [comment]
@spirillen I'm a uBlock user myself so I understand the value of the service and want to make sure we're compliant :)

TBH you can block that if you want since it's totally dead: `http://instafeed-api.pixlee.com.inscname.net/`

Our new fastly route:

```
~> dig instafeed-api.pixlee.com

; <<>> DiG 9.10.6 <<>> instafeed-api.pixlee.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43365
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;instafeed-api.pixlee.com.	IN	A

;; ANSWER SECTION:
instafeed-api.pixlee.com. 67	IN	CNAME	q2.shared.global.fastly.net.
q2.shared.global.fastly.net. 29	IN	A	151.101.2.49
q2.shared.global.fastly.net. 29	IN	A	151.101.66.49
q2.shared.global.fastly.net. 29	IN	A	151.101.130.49
q2.shared.global.fastly.net. 29	IN	A	151.101.194.49

;; Query time: 230 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Nov 06 12:57:06 PST 2019
;; MSG SIZE  rcvd: 158

```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/bf7c9f52853564bc0c01da29a6003598e709f0a3

**Comment by jchen123** [comment]
thanks @ryanbr !
