### ISSUE TITLE
evestment.com [Incorrect blocking]

### ISSUE THREAD

**Issue by Jordan-McMillan** [easylist/easylist#4251]
### List the website(s) you're having issues:

`https://app.evestment.com/api/analytics/v1/products/selection/all/search`

This commit removed our previous whitelist rule:
https://github.com/easylist/easylist/commit/e95ef2da029ef7c648d60b5bdac1cacb7b4a5d5c#diff-57814f66f7ce561ca9320be995443b1fL165

### What happens?

Api calls fail because the paths are like "/api/analytics"

### List Subscriptions you're using:

Clients are reporting issues using uBlock extensions

### Other details:

These api calls have "analytics" in the path because that is the name of the product line:
`https://www.evestment.com/products/analytics/`

**Comment by spirillen** [comment]
You are number 1 according to who?

What is it actually you are delivering?

This look honestly most like a hoax site

<details><summary>Screenshot of hoax site</summary>

![image](https://user-images.githubusercontent.com/44526987/68394988-227f7f00-016f-11ea-9590-ff9ff57c6c8c.png)

</details>

**Comment by llacb47** [comment]
So polite... this is how easylist gets a bad rep @spirillen

**Comment by Jordan-McMillan** [comment]
Thanks for the replies.

I'm not sure what makes this look like a hoax. A quick google search of the company name should clear up any confusion on if this is real or not.

We provide a web app that clients subscribe to, which runs under "app.evestment.com".
I included the "www.evestment.com" link as a reference for why "analytics" is in the URL path (name of the product").

I'm not so concerned about whitelist rules that would apply to the "www.evestment.com" site since it is primarily a marketing resource. The "app.evestment.com" site should not be getting blocked though as this is a site that clients subscribe to and is even behind a login.

I reached out 2 years ago to get the original whitelist rule added, which was removed recently in the commit that I linked to.

**Comment by Jordan-McMillan** [comment]
@monzta 
for reference, the original rule was added way back here:
https://github.com/easylist/easylist/commit/62f09532389ec205ffdf7cc37fbf6574e3d61a07

**Comment by spirillen** [comment]
> So polite... this is how easylist gets a bad rep @spirillen

I know, but sometime you need to shake things :smile: and honestly I still don't know what it is they are trying to make people install.

@Jordan-McMillan an that does what? posting all contents of a users phone for you to resell?

Jordan, you have used a lots of words, and I'm still no wiser.....

PS: Is there really someone who still use that privacy violating harvest my live site Google??

**Comment by ryanbr** [comment]
Has been fixed.
