### ISSUE TITLE
Polygon Website Still Showing Ads

### ISSUE THREAD

**Issue by GKid94** [easylist/easylist#4255]
`https://www.polygon.com/2019/11/7/20952369/red-dead-redemption-2-rdr2-pc-gameplay-freeze-crash`

![53453453](https://user-images.githubusercontent.com/18757054/68459584-14307200-0206-11ea-9f42-6da914f203f8.jpg)

**Comment by ryanbr** [comment]
Install the "Enhanced trackers list" from https://secure.fanboy.co.nz/ It'll remove it.
