### ISSUE TITLE
easyprivacy analysis.js rule breaking geospatial applications at https://www.arcgis.com/

### ISSUE THREAD

**Issue by ceddc** [easylist/easylist#4256]
Hello,

Thanks a lot for your work and consideration of this topic.

### List the website(s) you're having issues:

https://www.arcgis.com/home/webmap/viewer.html as a logged in user : potential users impacted in hundreds of thousands.

Specific CDN URL in my case :
https://cdn-a.arcgis.com/cdn/18F6FCA/js/arcgisonline/analysis.js net::ERR_BLOCKED_BY_CLIENT

In general  : 
https://\*.arcgis.com/\*/js/arcgisonline/analysis.js

### What happens?
This specific rule /analysis.js (that seems a bit too broad)
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L565

When you click on the analysis button, it should load analysis functions, in the menu, it does not 
![image](https://user-images.githubusercontent.com/2477896/68471460-8ca32d00-021e-11ea-855a-7037153d1e7c.png)

Analysis is just what our users want to do with geospatial data : https://doc.arcgis.com/en/arcgis-online/analyze/perform-analysis.htm and it does not relate to user privacy.

![image](https://user-images.githubusercontent.com/2477896/68471690-fde2e000-021e-11ea-92fd-4a4864daa063.png)

### List Subscriptions you're using:
uBlock filters​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

EasyList​​​​​

EasyPrivacy​​​​​

Malware Domain List​​​​​
Malware domains

Peter Lowe’s Ad and tracking server list​​​​​

### Your settings

- OS/version: Windows 10
- Browser/version:  Chrome 78.0.3904.70
- Adblock Extension/version: uBlock Origin v1.23.0

### Other details:

This specific rule /analysis.js (that seems a bit too broad)
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L565

Thanks a lot,

**Comment by ryanbr** [comment]
/analysis.js was too generic. Removing it. Came from commit; https://github.com/easylist/easylist/pull/3626
