### ISSUE TITLE
adspace.pro Incorrect Blocking

### ISSUE THREAD

**Issue by vyacheslavtyurikov** [easylist/easylist#4257]
My site is an advertising Agency in Krasnodar. Domain name adspace.pro most likely falls under your filters. I spend a lot of money on advertising my site, and it is blocked by many users. I ask you to exclude my site from the filters so that AdGuard users do not have problems with viewing my site.

parent request - https://github.com/AdguardTeam/AdguardFilters/issues/43680

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/433da04a802b055c395edfbb39985e11e19e5f7d
