### ISSUE TITLE
https://www.goindigo.in/  Cookie warning

### ISSUE THREAD

**Issue by s-ankur** [easylist/easylist#4260]
### What happens?
Theres a cookie accept warning on the goindigo homepage

### List Subscriptions you're using:
Fanboys Cookie List

### Your settings

- OS/version: Android 9
- Browser/version: Firefox 68.2.0
- Adblock Extension/version: UBlock Origin v1.23.0

**Comment by ryanbr** [comment]
We're blocking this already? This filter being used on the site

`##.accept-cookies:not(html)`

**Comment by s-ankur** [comment]
Sorry, It does work I was not enabling it on mobile..
