### ISSUE TITLE
Videos on website 'Sonyliv.com ' not playing .

### ISSUE THREAD

**Issue by Techguyprivate** [easylist/easylist#4265]
sonyliv.com 

### List the website(s) you're having issues: sonyliv.com
  
Click on any videos on sonyliv.com . 

`https://www.sonyliv.com/`

To open a video directly and test the issue , below is a direct link .

" `https://www.sonyliv.com/details/episodes/6101918901001/Ep.-2858---Madhvi-Clarifies-The-Doubt---Taarak-Mehta-Ka-Ooltah-Chashmah---8-November-2019` "

 ( without quotation mark of course )

or click on any videos on sonyliv.com .

Important Note : Sonyliv.com  is accessible only from India and Indian IP address. So please test it from India or from an Indian IP address by any vpn .

 https://www.sonyliv.com/details/episodes/6101918901001/Ep.-2858---Madhvi-Clarifies-The-Doubt---Taarak-Mehta-Ka-Ooltah-Chashmah---8-November-2019

### What happens?

Videos don't play . The video player doesn't start.

![Screenshot from 2019-11-10 18-10-16](https://user-images.githubusercontent.com/43615747/68544122-b80d4f80-03b7-11ea-9eb1-ee402d64d0cf.png)

### List Subscriptions you're using:
Only and only one  easylist .

![Screenshot from 2019-11-10 18-14-58](https://user-images.githubusercontent.com/43615747/68544137-f571dd00-03b7-11ea-8001-85d1410a207e.png)
![Screenshot from 2019-11-10 18-14-54](https://user-images.githubusercontent.com/43615747/68544139-f571dd00-03b7-11ea-9b07-c91bc4ce28d9.png)
![Screenshot from 2019-11-10 18-14-47](https://user-images.githubusercontent.com/43615747/68544140-f60a7380-03b7-11ea-8286-b5a9e5f8b852.png)
![Screenshot from 2019-11-10 18-13-21](https://user-images.githubusercontent.com/43615747/68544141-f60a7380-03b7-11ea-856e-86b491433d31.png)

![Screenshot from 2019-11-10 18-13-21](https://user-images.githubusercontent.com/43615747/68544131-d5421e00-03b7-11ea-905d-3f56a8670045.png)

Only one and only one . Easylist.
### Your settings
Take any setting . Default too. Doesn't matter. Still some screenshots.

![Screenshot from 2019-11-10 18-37-13](https://user-images.githubusercontent.com/43615747/68544441-243d8280-03bb-11ea-8351-ada850a9fbd5.png)
![Screenshot from 2019-11-10 18-37-00](https://user-images.githubusercontent.com/43615747/68544442-243d8280-03bb-11ea-809f-1ee35d460e9e.png)

 Yes.

- OS/version:  Tested with Linux Mint 19.2
- Browser/version:  Firefox Nightly 72 , firefox stable , Chrome stable 78 latest , brave browser stable latest . All most all browsers . 
- Adblock Extension/version: Ublock origin 1.23.0 , nano adblocker v1.0.0.127, adblock , adblock plus

**Comment by llacb47** [comment]
You should be using default filters for ublock origin, so reset ublock origin to default settings.  Then maybe try a regional list like this one: `https://easylist-downloads.adblockplus.org/indianlist.txt`

**Comment by Techguyprivate** [comment]
Using default filters too causes the problem too. 

Create a clean profile.

Install ublock origin.

Most important steps .  Disable all the lists  except easylist and Update the easylist only.

Do a purge all cache  and update again if needed .

Videos don't load. 

Easylist is causing the problem.

There is no problem till just few days ago. So a recent addition or modification is causing the problem.

Why am I sure ? I watch videos every day on the website . so.

**Comment by Techguyprivate** [comment]
Or just install ublock origin .

Important step is update the lists.  Wait for some time. The problem should appear. 

Ublock default lists.

**Comment by Khrin** [comment]
Hi @Techguyprivate , sorry but I was struggling to replicate your issue. Now should be fixed.

**Comment by Techguyprivate** [comment]
Yes. Resolved now. 

Purge the cache and update the filter again. Solved.
