### ISSUE TITLE
wcostream.com [Incorrect Blocking]

### ISSUE THREAD

**Issue by AdamWr** [easylist/easylist#4285]
### List the website(s) you're having issues:

https://www.wcostream.com/hinamatsuri-episode-10-english-dubbed
### What happens?

Video player doesn't work.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows
- Browser/version: Chrome 78
- Adblock Extension/version: Adblock Plus 3.7

### Other details:

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/68878094-6d693b80-0707-11ea-9ecc-9d527babc604.png)

</details>

<details><summary>Screenshot with Adblock disabled</summary>

![image](https://user-images.githubusercontent.com/29142494/68878185-8c67cd80-0707-11ea-9306-13044911f44f.png)

</details>

It's caused by:
`||wcostream.com/inc/$image,script`

**Comment by Khrin** [comment]
Video plays just fine.

**Comment by AdamWr** [comment]
Yes, it has been fixed in this commit - https://github.com/easylist/easylist/commit/c149555cde19dea11605f35ac3cb6df65ace7126#diff-ce6ade6e52352499cfb347f46c329f9fL505
