### ISSUE TITLE
hotstar.com [Incorrect Blocking]

### ISSUE THREAD

**Issue by zloyden** [easylist/easylist#4300]
### List the website(s) you're having issues:
`https://www.hotstar.com/in`

### What happens?
The site is broken by this rule `||gravityrd-services.com^$third-party`
<details><summary>Screenshot:</summary>

![fanboy](https://user-images.githubusercontent.com/33488229/69062632-4626ad00-0a2c-11ea-9455-772d1046e101.png)
</details><br/>

### List Subscriptions you're using:
Fanboy's Annoyance List

### Your settings

- OS/version: macOS 10.15.1
- Browser/version: Chrome 78
- Adblock Extension/version: AdBlock 3.61.1

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/79052c5b76b95b2f9fe52af1c96edf8c83a9df68
