### ISSUE TITLE
egghead.io

### ISSUE THREAD

**Issue by rmmu-forge** [easylist/easylist#4301]
### List the website(s) you're having issues:

`https://egghead.io/courses/start-learning-react` and others

### What happens?

`||tag.rightmessage.com^` and `||rightmessage.com^$third-party` were added in response to https://github.com/easylist/easylist/issues/3971 - where the site owner was displaying an optional questionnaire to visitors, but it was popping up repeatedly, even after being dismissed.

This behavior would indeed be annoying and is most regrettable. It wasn't intended behavior, however. It was the result of a temporary bug in RightMessage that would cause dismisses to be ignored for some users/browsers.

The bug has since been resolved: answering will now cause the question to be dismissed forever, and clicking just once to minimize will minimize forever.

The addition of these blanket rules is causing a lot of sites' embedded forms and legitimate in-page content to be entirely removed (much the same as if `*.wufoo.com` were added to the block list). To be clear, RightMessage does not support third-party advertising, data sharing, or anything of the sort.

Can the two rules be removed (or can we discuss the most appropriate way to soften them so as not to degrade visitor experience)?

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/37077553/69078567-0bbf0f00-0a30-11ea-8249-05ab812d0d6b.png)

### Your settings

OS/version: macOS Mojave 10.14.6
Browser/version: Chrome 76.0.3809.132
Adblock Extension/version: uBlock Origin 1.21.6

**Comment by Khrin** [comment]
Filter is just fine as it is.
