### ISSUE TITLE
NSFW: porn99.net adblocker detected

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#4305]
### List the website(s) you're having issues:

`porn99.net` redirected => `lauxanh.org`

### List Subscriptions you're using:

Standard + one of my own

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/69109532-595f6a00-0a78-11ea-988a-5e84884fe133.png)

</details>

### Other details:

Looks like working
```
! 11/19/2019 https://lauxanh.org
lauxanh.org##.HpgqPJrgEhSs-default
lauxanh.org##.HpgqPJrgEhSs-bg
```

**Comment by Khrin** [comment]
Anti-adblocking systems aren't blocked by EasyList.

**Comment by chirag127** [comment]
please add anti AdBlock tag
