### ISSUE TITLE
Bug: Kijiji page blank

### ISSUE THREAD

**Issue by ale5000-git** [easylist/easylist#431]
uBlock Origin 1.12.4 on Google Chrome 59.0.3071.86.

When EasyList is enabled I cannot use the page `https://www.kijiji.it/pubblica-annuncio`, it is all blank.
Disable the filter make it working.

**Comment by Khrin** [comment]
Tra 10-15 minuti aggiorna EasyList Italy.

**Comment by ale5000-git** [comment]
@Khrin: Thanks, it works.

PS: Just a question, should the fix be in the same file that break it?
If I visit pages in languages other than mine (I do it often), will I get a lot of broken sites because I haven't enabled the filter for any possible language?

**Comment by Khrin** [comment]
- No, manteniamo i vari separati per tipologia in diversi files. 

- Sì, è possibile.
