### ISSUE TITLE
Add https://go.clickr.xyz/ to block list

### ISSUE THREAD

**Issue by Esokrates** [easylist/easylist#4310]
I googled for something, clicked a google result and landed here:
`
https://go.clickr.xyz/?utm_medium=971d375bea7084fe2f51954d47f872dbb7e0a8d9&utm_campaign=Auto`

Way to reproduce: Search for "sncollegeqadian.com/pixelbook-go-hands-on-googles-cheapest-chromebook-yet/" in Google and click the first match. Tested in Chromium with ublock origin.

Navigating directly to the link without Google does not lead to the ad site, but clicking the website from google search results completely hijacks the navigation and spams the history so the back button does not work.

**Comment by spirillen** [comment]
That I would classify as a tracker and redirection script.... but I'm missing the master :unamused: 

master = where the urls are formed/owner/generated...  any one who could help there?

**Comment by smed79** [comment]
@Esokrates `sncollegeqadian.com` Seems to be a scam/spam site for me.
