### ISSUE TITLE
GlobalNews.ca - Video playback broken (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#4328]
### Affected site:
`https://globalnews.ca/`

### Issue:
Video playback broken is broken.

### Example:
`https://globalnews.ca/news/6200843/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyPrivacy

### Problem rule:
`||wordpress.com/geo/`

### Possible fix:
`@@||wordpress.com/geo/$domain=globalnews.ca`

### Note:
The site is also in dire need of some filtering!

Examples (stuff not caught by any of my current filters):

```
Ad boxes:
globalnews.ca##.ad-choices
globalnews.ca##.c-ad
globalnews.ca##.c-ad--bigbox
globalnews.ca##.l-article__ad
globalnews.ca##.sidebar-ad
globalnews.ca##.stream-ad
globalnews.ca###headerAd

Annoyances:
globalnews.ca##.c-flyers
globalnews.ca##.c-stickyRail
globalnews.ca###content-redesign-survey

Social:
globalnews.ca##.c-social
globalnews.ca##.c-social--footer
globalnews.ca##.c-social__link
globalnews.ca##.c-socialShare
globalnews.ca##.c-socialShare--article
globalnews.ca##.c-socialShare--rounded
globalnews.ca##.c-socialShare__item
globalnews.ca##.c-socialShare__item--comments
globalnews.ca##.c-socialShare__link
globalnews.ca##.c-socialShare__list
globalnews.ca##[aria-label="facebook"]
globalnews.ca##[aria-label="twitter"]
globalnews.ca###footer-social
```

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by Khrin** [comment]
Hi, I've looked into a few videos and all are starting fine. Is this issue still happening for you?

**Comment by THEtomaso** [comment]
No, it looks like `wordpress.com/geo` can be blocked without any ill effects now, so they must have changed something server-side.
