### ISSUE TITLE
Thank you @smed79 for your contributions

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#4339]
Not a bug, but a big **_THANK YOU_** to @smed79 for all his work, helping us all to see a more clean internet with all his contributions.

As a user of this repo for several reasons, I'm a big fan of all these contributions.

Unfortunally, I have óne but.....
@smed79 would it be possible to have parsing a short note about why you add a record, just as simple as track, ads, spyware, malicious. Small why's 

A big thank you from a happy user

**Comment by smed79** [comment]
Thank you, happy to know that my contribution can be useful.

> would it be possible to have parsing a short note about why you add a record

You can guess it yourself depanding to which file the change is added.

e.g
- easylist_adservers.txt => **ads**
- easyprivacy_trackingservers.txt => **tracking**

**Comment by spirillen** [comment]
Hi @smed79 that only tells if it is tracking, ads. and let's face it, my eyes are not 25 any more, they closer to that times 2 :older_man: The snip of "cat" in tittle are bigger than the file names :eyeglasses:

Anyway, I did ask, I had a reply, and thanks for that, but i still :pray: for the little :spiral_notepad:

**Comment by peace2000** [comment]
I'm sure Smed is happy to receive gratitude but this isn't an Easylist issue ;)

@Khrin
