### ISSUE TITLE
ec.europa.eu - Statistics page is blank

### ISSUE THREAD

**Issue by alcayaga** [easylist/easylist#4340]
### List the website(s) you're having issues:
`https://ec.europa.eu/eurostat/databrowser/view/ten00118/default/table?lang=en`

### What happens?
The webpage stays blank

### List Subscriptions you're using:
EasyList
EasyPrivacy

### Your settings
- OS/version: Windows 10, 
- Browser/version: Firefox 70.0.1
- Adblock Extension/version: uBlock Origin v1.23.0

### Other details:
Filter `/piwik.$script,domain=~matomo.org|~piwik.org` from EasyPrivacy filters script `https://ec.europa.eu/eurostat/databrowser/assets/analytics/piwik.js`

**Comment by spirillen** [comment]
Have you looked up the `matomo.org`? I seen what they are doing against you?

For my understanding, they are hosting malicious spyware tracking code <= confirm via wiki if you like

So if you would like to see any `piwik/matomo` badware you would have to whitelist them manually, or tempoarely disable your uBlock/nanoBlock what-ever you use. I doubt (and hope not) there will be any whitelisting on this...

**Comment by alcayaga** [comment]
Since it's a first party tracker, the webpage is owned by the European Union and they offer a clear Privacy Policy (`https://ec.europa.eu/info/privacy-policy_en`), I believe it should be enough to whitelist this domain for everyone

**Comment by spirillen** [comment]
Hi Pablo @alcayaga  I'm not going into that political debate, but all the above is from the most un-trusted source after google and facebook.

Modern politics is not above serving the people, but pretent serving the people to get re-elected....

I end my political comment with this.....
