### ISSUE TITLE
OK-Magazine.ru - Image viewer broken (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#4341]
### Affected site:
`http://www.ok-magazine.ru/`

### Issue:
Image viewer is broken.

### How to reproduce:
1 - Open this page:
`http://www.ok-magazine.ru/style/gurman/92203-idealnoe-sochetanie-podbiraem-edu-pod-serialy/`

2- Scroll down, and click on one of the images, which shows a magnifying glass on them, upon mouse hover.

**Expected result:** A large version of the image should be shown in the image viewer.

**Actual result:** The image is not shown!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyList

### Problem rule:
`/adfox/*`

### Blocked script:
`https://yastatic.net/pcode/adfox/loader.js`

### Possible fix:
`@@||yastatic.net/pcode/adfox/loader.js$domain=ok-magazine.ru`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by Khrin** [comment]
I believe this issue should addressed by RUadlist, if it's not already fixed there. ( @dimisa-RUAdList )

**Comment by dimisa-RUAdList** [comment]
Fix: https://hg.adblockplus.org/ruadlist/rev/a219cdfa5d19

**Comment by THEtomaso** [comment]
@dimisa-RUAdList:

This script needs to be whitelisted for `ok-magazine.ru` too (blocked by many filters):
`https://an.yandex.ru/system/adfox.js`

### Example:
`https://www.ok-magazine.ru/stars/report/59077-anna-feris-porazila-paparacci-svoey-hudoboy-na-semkah-remeyka-za-bortom-foto/`

(Try to click on image 1/9, to bring up the image viewer)

### Possible fix:
`@@||yandex.ru/system/adfox.js$domain=ok-magazine.ru`

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/7ea7aed81bd0941da71cca611c3072708879e55e
