### ISSUE TITLE
amazonaws.com/promotions rule too broad

### ISSUE THREAD

**Issue by joekohlsdorf** [easylist/easylist#4371]
https://github.com/easylist/easylist/blob/978a2c460f34821dd2b78a4d8c9143eb17ec73d1/easylist/easylist_thirdparty.txt#L188

I have seen this rule break legitimate images of an online store which hosts images on S3.

The exception for the brewstore.com domain was added in 2017 but whitelisting false positives in this case is probably a fight against windmills.

**Comment by peace2000** [comment]
Are there more examples to demonstrate that the rule you are speaking of is too broad?

**Comment by smed79** [comment]
@joekohlsdorf from the **issue template**

```
### List the website(s) you're having issues:

<!-- URL(s) for issue on a specific site are **mandatory** -->
```

**Comment by Khrin** [comment]
Since no one has replied in almost two months, I'm closing here.
