### ISSUE TITLE
www.autoblog.nl filter too strict

### ISSUE THREAD

**Issue by bnbaz** [easylist/easylist#4372]
### List the website(s) you're having issues:
`www.autoblog.nl`

### What happens?

None of the content is showing. I think this is caused by either
`##div[id^="div-gpt-ad"]` or `##.category-advertorial`

### List Subscriptions you're using:

- uBlock0 built-in filters
- EasyList (disabling EasyList solves the issue)
- EasyPrivacy
- Malware Domain list
- Malware domains
- Anti-Facebook list
- Fanboy's Cookie List
- Fanboy's Social Blocking List
- Peter Lowe’s Ad and tracking server list
- NLD: EasyList Dutch

### Your settings

- OS/version: Windows 10 x64 (latest)
- Browser/version: Firefox 70.0.1 (64-bit)
- Adblock Extension/version: uBlock Origin v1.24.2

### Other details:

I suspect EasyList. Currently, the first post is an advertorial, it seems this is contributing to the issue. This is not the case on the second page. The second page works fine with EasyList enabled. `https://www.autoblog.nl/page/2`

**Comment by ryanbr** [comment]
I'm not seeing much difference here

**Comment by bnbaz** [comment]
New articles were posted, the top one is no longer an advertorial. When
this was the case, 0 articles were visible on autoblog

**Comment by ryanbr** [comment]
Given I can't see a difference, I won't add either filter. Articles show on both pages. a filter suggestion will be fine, but not whitelisting 2 cosmetics.
