### ISSUE TITLE
mixdrop.co - Blocked incorrectly

### ISSUE THREAD

**Issue by vwxiqum02** [easylist/easylist#4381]
Filter affected:
	mixdrop.co^$third-party

1st/3rd-party sites affected:
	mixdrop.co / any

How is it broken?
	Breaking video embeds in third party websites

Description why it should be removed:
	Mixdrop is a cloud hosting service not a ad server and this rule is breaking video embeds in users websites.

**Comment by ryanbr** [comment]
resolved.
