### ISSUE TITLE
mappy.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#439]
annoyance

`||accengage.net^$third-party`

privacy
```
/log/error/*
||log.mappy.net^
```
blank ad space (4 years ago [#12468](https://forums.lanik.us/viewtopic.php?f=62&t=12468))

```
###AdvertisingBL
###AdvertisingInlineRectangle
```

- http://i.imgur.com/48dGw33.png
- http://i.imgur.com/WsviNMr.png

`https://mappy.com/`

**Comment by OpenBSD-Neurotik** [comment]
I can not find the cosmetic filters you are reporting, not even in firefox developer edition without any addons. It seems the site has changed since last year.

The site only has 
`###ScrollableLeftView`
for me with everything disabled.

I've blocked the advertisement and cookie consent.

**Comment by Khrin** [comment]
@SMed79 I'm unable to find some of the elements you've referenced, are still present?

**Comment by SMed79** [comment]
"bi_multipath": "//**log.mappy.net**/log/1.0/multipath/",
"buc": "//**log.mappy.net**/log/1.0/log/buc/?",
"audience": "//**log.mappy.net**/log/1.0/audience/categorie/?",
"ravenjs": "//**log.mappy.net**/log/1.1**/log/error/**js/report",

https://pastebin.com/raw/CtreF47c
