### ISSUE TITLE
Fanboy cookie list is not being updated, something is wrong

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#4396]
What has happened as the cookie list is not really getting updates anymore?

https://www.fanboy.co.nz/fanboy-cookiemonster.txt

"Last modified: 15 Nov 2019 10:51 UTC"

Even though updates are made in the Github? https://github.com/easylist/easylist/tree/master/easylist_cookie

@ryanbr

**Comment by hawkeye116477** [comment]
Seems that name got changed 16 days ago and no updates from 16 days. Maybe link to lsit als changed, but I can't find new link.
https://github.com/easylist/easylist/commit/f479000932294df083fd5bde832bd03b7fd7176a

**Comment by peace2000** [comment]
@hawkeye116477 Thanks. But the problem is that the new link won't automatically be updated to all users of this list...

**Comment by Khrin** [comment]
@ryanbr has fixed the issue and now the list is up to date.
