### ISSUE TITLE
styl.pl / interia.pl / pomopnik.pl / esporter.pl [EasyPrivacy] [Breakage]

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#4397]
### List the website(s) you're having issues:

```
https://www.styl.pl/zdrowie/news,nId,3357751
```
```
https://www.pomponik.pl/plotki/news,nId,3324311
```
```
https://motoryzacja.interia.pl/samochody-nowe/testy/news,nId,2914439
```
```
https://www.esporter.pl/newsy/news,nId,3371995
```

Before open subscribe EasyPrivacy - **otherwise you need to clean your cookies / local storage for the domain "`iplsc.com`"**.

### What happens?

Cannot vote up/down comments under article. 

**The counter does not increase the number of votes after clicking.**

### List Subscriptions you're using:

[](https://github.com/MajkiIT/polish-ads-filter/issues/15209)

`EasyPrivacy`

Problematic:
https://github.com/easylist/easylist/blob/e96bd57259c723ba809f1fef8bfb8e9ea02907b5/easyprivacy/easyprivacy_general.txt#L2220

### Your settings

- OS/version: `Windows 10`
- Browser/version: `Firefox 71`
- Adblock Extension/version: `3.7.0`

### Other details:

Possible fix:

`@@||iwa.iplsc.com/iwa.js$script,domain=pl`

**Comment by hawkeye116477** [comment]
Sometimes even comments disappears after refreshing of page.

**Comment by ryanbr** [comment]
There is a few trackers under /plugins/ ;

Does this work?

```
||iwa.iplsc.com/plugins/$script
@@||iwa.iplsc.com/iwa.js$script
```

**Comment by krystian3w** [comment]
Yes this is works.
