### ISSUE TITLE
tv.kakao.com videos not playing due to daumcdn.net block & missed tracking

### ISSUE THREAD

**Issue by Infinitay** [easylist/easylist#4402]
**I would like to preference that I have also posted an issue over on uBlock Origin's uAsset issue tracker: https://github.com/uBlockOrigin/uAssets/issues/6638**. I am posting this here in case I miss anything on this issue that I mentioned on the issue I created in uAssets.

### List the website(s) you're having issues:

Whole site: `https://tv.kakao.com`
Particular video on the site: `https://tv.kakao.com/channel/3049413/cliplink/404295898`

### What happens?

Videos are failing to get loaded and played which seems to be because of EasyPrivacy according to uBlock Origin's logger. `https://t1.daumcdn.net/tiara/js/v1/tiara.min.js` is being blocked by the filter and highlighted as a tracking URL. However when you allow that URL, videos can be played on the site with no issue.

### List Subscriptions you're using:

uBlock Origin tells me the issue is because of EasyPrivacy filter, but here's a list of all my filters: https://i.imgur.com/5cEl6wH.png

### Your settings

- OS/version: Windows 10 Build 1903
- Browser/version: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin v1.23.0

### Other details:

As I said, by allowing tiara.min.js via `@@||t1.daumcdn.net/tiara/js/v1/tiara.min.js$script,domain=tv.kakao.com` filter or [clicking allow under the URL rule tab](https://user-images.githubusercontent.com/6964154/69906179-6e4bcf80-138d-11ea-9c8b-f54906f62395.png) the video loads properly. As for screen shots, they are over on the issue I posted as the beginning of this issue.

Also, while I'm making this post, after allowing tiara.min.js through the filter, 2 more URL's are loaded as a result. The first is an image via `https://stat.tiara.kakao.com/track` which you can tell by its URL that it's tracking, fortunately this is blocked by EasyPrivacy. The second is another image for tracking under the URL `https://track.tiara.kakao.com/queen/footsteps`, but unfortunately EasyPrivacy **does not** filter this URL. So, I manually blocked it via `||track.tiara.kakao.com/queen/footsteps$image,domain=tv.kakao.com`

**Comment by krystian3w** [comment]
[](https://github.com/uBlockOrigin/uAssets/issues/6638)
