### ISSUE TITLE
Nettavisen.no - Videos are blocked (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#4413]
### Affected site:
`https://www.nettavisen.no/`

### Issue:
Videos are blocked.

### Example:
`https://www.nettavisen.no/3423887035.html`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyList

### Problem rules:
```
/ads.min.js
/ima3.js
||imasdk.googleapis.com^$third-party
```

### Blocked scripts:
```
https://cdn.flowplayer.com/releases/native/stable/plugins/ads.min.js
https://imasdk.googleapis.com/js/sdkloader/ima3.js
```

### Possible fix:
```
@@||flowplayer.com/releases/native/stable/plugins/ads.min.js$domain=nettavisen.no
@@||googleapis.com/js/sdkloader/ima3.js$domain=nettavisen.no
```

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by THEtomaso** [comment]
> https://github.com/DandelionSprout/adfilt/commit/99ced82005b3a8b76811527b47b6b7762b078acc/

Ah, I missed the issue with **ima3.js**, since I've got it whitelisted by default.

*first post edited*

**Comment by DandelionSprout** [comment]
It's okay. `||imasdk.googleapis.com^` was only blocked on my end through *AdGuard Mobile Ads* anyway, and I'm just seconds away from posting an issue report for that entry on their issue tracker.

**Comment by THEtomaso** [comment]
> ||imasdk.googleapis.com^ was seemingly only blocked on my end through AdGuard Mobile Ads

That's weird.
**EasyList** blocks it too, with two rules no less (as noted in my first post now).

**Comment by DandelionSprout** [comment]
I can confirm you're right. I guess Nano's logger only showed me the relevant entry that was triggered first.

**Comment by THEtomaso** [comment]
Are you using **AdGuard Mobile Ads** on a desktop setup?

**Comment by DandelionSprout** [comment]
Yes. 😅 

It's an anti-ad list, and I love to use anti-ad lists in general.
