### ISSUE TITLE
Wordpress wp-admin: Posts with certain tag are incorrectly removed

### ISSUE THREAD

**Issue by catearcher** [easylist/easylist#4423]
Commit 834f59a109ee1405002774233c39075ce0616f4f introduced a new filter that is incorrectly blocking elements in the **admin area** (i.e. `/wp-admin`) of all Wordpress blogs. The issue is specific to posts that have the tag "sponsored".

### List the website(s) you're having issues:

- `https://ANY-WORDPRESS-BLOG/wp-admin/edit.php`

### What happens?

When a Wordpress admin visits the post list in the wp-admin section (i.e. the administrative backend) then all posts that have the tag "sponsored" are completely missing.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 78.0.3904.108
- Adblock Extension/version: uBlock Origin 1.23.0
- Wordpress version: 5.3

### Other details:

- Filter: `##.tag-sponsored` in `/easylist/easylist_general_hide.txt`

**Comment by ryanbr** [comment]
removed, site no longer using it.
