### ISSUE TITLE
Hiding '.ytp-ad-module' on YouTube also hides the 'Skip Ad' button

### ISSUE THREAD

**Issue by x0a** [easylist/easylist#4441]
### List the website(s) you're having issues:
YouTube

### What happens?
EasyList contains the rule `##.ytp-ad-module` which I believe is meant to hide ad overlays, but also hides the 'Skip Ad(s)' button when a video ad does get through https://github.com/x0a/uBO-YouTube/issues/8

### List Subscriptions you're using:
EasyList

### Your settings

- OS/version: Windows 10 18362
- Browser/version: Chrome 78.0.3904.108 
- Adblock Extension/version: uBlock Origin v1.23.0

### Other details:

I think it might make sense to switch to an overlay-specific rule like: `.ytp-ad-overlay-container`

**Comment by ryanbr** [comment]
But if you're blocking the ads already, there would be no skip button

**Comment by x0a** [comment]
Right. Net filtering makes this rule redundant because ads aren't going to play anyway. 

But without net filtering this rule becomes intrusive because it gets rid of the skip button while ads continue to play.

When video ads are playing, the HTML tree looks like this:
```
div.ytp-ad-module
|-- div.ytp-ad-player-overlay
|   |   |-- div.ytp-ad-player-overlay-flyout-cta
|   |   |-- div.ytp-ad-player-overlay-instream-info
|   |   |-- div.ytp-ad-player-overlay-skip-or-preview
|   |   |-- div.ytp-ad-player-overlay-progress-bar
|   |   |-- div.ytp-ad-player-overlay-instream-user-sentiment
|   |   |-- div.ytp-ad-info-dialog-background
```

When overlay ads are showing, the tree looks like this:
```
div.ytp-ad-module
|-- div.ytp-ad-overlay-ad-info-dialog-container
|-- div.ytp-ad-overlay-slot
```

It would be nice if `div.ytp-ad-player-overlay-skip-or-preview` was excluded from hiding, which would mean something more specific than just `##.ytp-ad-module`

For reference, this is all that the `##.ytp-ad-module` rule affects (just the bottom part).

![nohide](https://user-images.githubusercontent.com/13019784/70390057-e8cbaf00-198c-11ea-891a-7fc71c90cda4.png)
![hide](https://user-images.githubusercontent.com/13019784/70390056-e8cbaf00-198c-11ea-9296-1332ab06c865.png)

**Comment by Khrin** [comment]
Your bug, your fix. I'm not sure why we should change our filters, which are perfectly fine.

**Comment by llacb47** [comment]
@x0a Since easylist is historically uncooperative, you will have better luck making a custom filter list and asking your users to add it to their ublock origin.

**Comment by x0a** [comment]
@llacb47 Understood. Thanks for the heads up
