### ISSUE TITLE
EasyList to Proxy Auto Configuration File repo

### ISSUE THREAD

**Issue by essandess** [easylist/easylist#449]
I've created an EasyList to filtering [proxy.pac](https://raw.githubusercontent.com/essandess/easylist-pac-privoxy/master/easylist_pac.py) file in the repo [easylist-pac-privoxy](../../../../essandess/easylist-pac-privoxy).

The provides front-end tracker and adblocks on any client that uses proxy auto network configuration, especially mobile devices over VPN.

The filtering PAC is quite efficient and capable, and runs on mobile devices. Comments welcome.

**Comment by peace2000** [comment]
@ryanbr @Khrin This can be closed as it's not an issue.
