### ISSUE TITLE
@@||exoclick.com/ad_track.js ????????

### ISSUE THREAD

**Issue by AnonymousPoster** [easylist/easylist#4497]
Excuse me but

```
@@||exoclick.com/ad_track.js
```

??? I choose to read this as an mis-commit to the easylist

**Comment by ryanbr** [comment]
Note, it was used to track adblock users (not every whitelist is bad), seems safe to remove

**Comment by AnonymousPoster** [comment]
Sure, but the naming :smiley: That leads the toughs in one direction :thought_balloon:
