### ISSUE TITLE
bossmp3.in using similar ad strings to other sites

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#45]
`http://bossmp3.in/category/3844/Tere_Bina_(Shorgul)_Arijit_Singh.html`

using similar ad strings to other sites.
`https://forums.lanik.us/viewtopic.php?f=62&t=31072`

add this general filter 
`##a[href*=":80/key/"] `

which blocks ads and banners for all below mentioned sites and many more which is not mentioned.

`heromaza.in`
`songmix.in`

Thank you for your time and support

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/f7c0fc26c712b269c8adaca32d58cdf7eeec0386
