### ISSUE TITLE
Amazon Video playback blocked

### ISSUE THREAD

**Issue by chrislongo** [easylist/easylist#450]
I see the pattern:

/ad24/* 

Is blocking manifest downloads of some non-ad video content on Amazon Video:

Example URL:

https://a153avoddashs3us-a.akamaihd.net/d/2$_gew...pI~/ondemand/ce5e/ad24/3f7e/47a3-9321-...ad_corrected.mpd

**Comment by peace2000** [comment]
Is this problem still in effect?

**Comment by Khrin** [comment]
A new issue report can be started, if necessary.
