### ISSUE TITLE
c.datado.me rule too strict

### ISSUE THREAD

**Issue by antoinevastel** [easylist/easylist#4509]
Hi, I'm Antoine, R&D engineer at Datadome. A recent PR (https://github.com/easylist/easylist/commit/e1758abb15ca9fbe2c0a61ae4264426bea30a2e4) added one of our domains (||datado.me^$third-party) in easyprivacy_trackingservers_international.txt.
You can find an example of it by setting your user-agent as "HeadlessChrome" or using one from another bot and going to a domain such as:
- https://www.blablacar.fr/
- http://www.leparisien.fr/.
Nevertheless, this domain is only used to show CAPTCHAs once a user has been detected as a bot and does not collect any information (it only displays a CAPTCHA).
Because of this, we have to request users to whitelist the domain in order to be able to pass a CAPTCHA.
Would it be possible to remove the specific rule blocking this domain?
Feel free to ask further details if required.

Best,

Antoine

**Comment by spirillen** [comment]
> Because of this, we have to request users to whitelist the domain in order to be able to pass a CAPTCHA.

If you have to request as user to whitelist, how can they then be a bot that should resolve some sort of google reversed-peroxided tracking captcha?

Should you upgrade you code to be working?

**Comment by antoinevastel** [comment]
Just to clarify the situation, similarly to humans, bots can also block any kinds of requests, including our script. Thus, the absence of a request doesn't imply that you're a human with an adblocker.
Concerning your remark, bot developers may also decide to block some scripts but to whitelist ours when we ask them to, so once again, interacting with the page in such as simple way is not a proof you're human, that's why we still require to solve a CAPTCHA.
The consequence of this domain in the list can result in the hardblocking of easy list users on some of the major websites in case one of our rules has a false positive.

**Comment by spirillen** [comment]
As a personal note to:

> The consequence of this domain in the list can result in the hardblocking of easy list users on some of the major websites in case one of our rules has a false positive.

I would actually prefer this :smiley: then we would know where **_NOT_** to trust any contents and it would be you who runs out of business as your costumers would flee as they loose visitors :rofl: 

All kind of tracking is evil. period, finite and ("Don't be evil") Google tops the list

**Comment by antoinevastel** [comment]
Once again, our detection script is blocked (||datadome.co^$third-party), which I can understand given your definition of tracking. Nevertheless, why block our CAPTCHA domain even though it does not collect anything and the code is not obfuscated? What could we do in order to have our CAPTCHA domain whitelisted? We are willing to modify our code to be "compliant".

**Comment by spirillen** [comment]
For that I'll bow on my knees into the dust, sincerely.

Why not add something like a math question? `what is 1 + 4` these can be obfuscated above bot levels as well as tracking captchas (This is actually what google does (in which order do you solve, click etc) and why you are meat by dislikes by default).

I've been using the math on several of my previous sites, and they have worked perfectly for over 15 years with no bots breaking any of them (except 1 day, and that was from a other domain on a shared hosting).

This will add trust to your site, can be used on all submit forms, served from same domain, and can only provide a IP log... just as your web-server log does.

You are back in the trust zone :smiley: 

Would that be something you could work with @antoinevastel :question:

**Comment by antoinevastel** [comment]
Just to clarify the situation, the problem seems to be  mostly that we use a 3rd party captcha ?
If it's the case, with our current approach, Google cannot really track users since we use a generic domain to show CAPTCHAs. Let me illustrate this with an example.

We are present on siteA, siteB, siteC, ... sitesWhen we block someone, we show a CAPTCHA using the following strategy:

siteA > iframe(c.datado.me) > iframe (recaptcha)

Since the captcha is inside an iframe, Google cannot know on which website the user is. It could do it using the CAPTCHA key. Nevertheless, since we share the same key among all customers, the only thing that can be inferred is that an IP visited one of the 1000s of websites we protect. Although it is not perfect anonymity, I agree, it pretty much makes the data useless as we protect a wide range of websites ranging from news, sport to dating.

**Comment by ryanbr** [comment]
Where is a valid example where it breaks a captcha?

**Comment by ryanbr** [comment]
This script is a tracker and should remain blocked.
`https://js.datadome.co/tags.js`  (Decoded) `https://pastebin.com/bHCPUVN3`

My vote is No. Keep this blocked. Its a tracker.

**Comment by llacb47** [comment]
Block it, if perimeterx is blocked, block this too. https://github.com/easylist/easylist/commit/6489947a49ea29002534a1c064c695e2fb0eee5f

**Comment by antoinevastel** [comment]
@ryanbr we are not asking to whitelist this script https://js.datadome.co/tags.js, we were discussing the domain served to deliver CAPTCHAs: |datado.me^$third-party

**Comment by spirillen** [comment]
@antoinevastel How would one like me be able to solve these, in worse case very very evil) obfuscated trackers? the entire Cyber Criminals at Goggle is block on my network? And with the latest Apomaya Adgain code https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1444 trust is not to be given.

And just because you claims you are the man in the middle for "that an IP visited one of the 1000s of websites we protect" you should really read up on how evil you can make a reverse-proxy for what it is sharing.

And best practice have always been and will always be to host own code, the msec you call an external script you lost the visitors trust and suspicion is rising.

Everything you write, and what we other knows about evil setups, you keeping running up hill ny trying to leave things as is. The only way out of this "hell hole" is as I wrote earlier, small js script that are server "locally" from own domain path is the only way to get some trust, and as simpler this script is, the more trust is gain.  `2+2 = 5` The quick once will always remember the tax :stuck_out_tongue_closed_eyes:

**Comment by ChiefMikeK** [comment]
### ``¯\_(ツ)_/¯`` a simple and friendly 1st party Capcha from a highly trusted website!   
[Tor Blog \#comments](https://blog.torproject.org/new-release-0425-also-0417-0406-and-0359#comments) though they also review posts prior to displaying them.   
 ![simple capcha.png](https://github.com/ChiefMikeK/feedback/raw/master/img/capcha.png)

**Comment by ryanbr** [comment]
Closing this. No real world examples provided, filter is staying
