### ISSUE TITLE
[EasyPrivacy] [Syntax] Is "$~popup" a correctly formatted entry?

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#4510]
It's been mentioned in https://github.com/DandelionSprout/adfilt/issues/7 (e.g. https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-564162067) that `||google.com/log?$~popup` was added to `easyprivacy_specific.txt` pretty recently, wherein `$~popup` is confusing uBO and Nano Adblocker, as those extensions consider `popup` to be non-negateable, as well as unnecessary because `popup` is by default excluded by them when not using any `$` values at all (which in fact led to their creation of `$all` to also cover `popup`).

Does this mean that there's some new syntaxes in ABP or AdGuard that we should be made aware of, or was it simply a spelling typo on you guys' end?

### List the website(s) you're having issues:

N/A

### What happens?

https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-563350814 claims that uBO treats it as invalid, and the entry is shown in Nano Adblocker's list viewer with a red tilde (which means its `$` value is broken).

### List Subscriptions you're using:

N/A

### Your settings

- OS/version: Windows 10 November 2019 Update
- Browser/version: Chrome 78.0.3904.108 64-bit for Windows
- Adblock Extension/version: Nano Adblocker 1.0.0.130 + Nano Defender 15.0.0.170

### Other details:

None that I'm currently aware of.

**Comment by ryanbr** [comment]
Okay removed.
