### ISSUE TITLE
Curalate.com EasyPrivacy List rules

### ISSUE THREAD

**Issue by bvellek** [easylist/easylist#4512]
### List the website(s) you're having issues:
There are thousands of websites utilize our javascript experiences that have this issue. Here are some examples:
- `https://www.oakandfort.com/`
- `https://www.macys.com/ce/splash/macyslove/`
- `https://www.bestbuy.com/site/electronics/idea-center/pcmcat345300050032.c?id=pcmcat345300050032`

### What happens?
Curalate develops embeddable javascript experiences for ecommerce sites. These experiences are mistakenly being blocked by EasyPrivacy. These experiences emit events via a jsonp and png (pixel) for metrics aggregation. In the past we've provided the specific routes that can be blocked, but we need to remove the wholesale `*.curalate.com` third party block (from this [commit](https://github.com/bvellek/easylist/commit/8732578dd8342d28edaa9fb484ceafd949e54f70#diff-dbc51871bdd5cf7971a65ef9684d2248R585)) as it prevents not only the metrics event calls, but the entire experience from rendering on the page. 

![image (5)](https://user-images.githubusercontent.com/18407299/70672575-8f85a900-1c34-11ea-8b91-e0b333bc63d6.png)

Here is an example with uBlock disabled:
![Screen Shot 2019-12-11 at 4 48 08 PM](https://user-images.githubusercontent.com/18407299/70673082-2f900200-1c36-11ea-9351-00e4252bbb5e.png)

Here is an example with uBlock enabled: 
![Screen Shot 2019-12-11 at 4 48 39 PM](https://user-images.githubusercontent.com/18407299/70673095-3880d380-1c36-11ea-9660-e9840dc454c7.png)

### List Subscriptions you're using:
EasyPrivacy

### Your settings
- OS/version: MacOS Sierra
- Browser/version: Chrome (73.0), Brave (1.1.20)
- Adblock Extension/version: uBlock Origin (1.18.16)

### Other details:
We'd like to replace the `curalate.com` block with a block for `curalate.com/*/events.png` and `curalate.com/*/events.jsonp` which are the only endpoints that receive our anonymous, non PII events for tracking the number of clicks that occur on our widgets.

**Comment by ryanbr** [comment]
There is a few pixel/metics bits in `https://cdn.curalate.com/sites/century21stores-nzvwxr/site/latest/site.min.js` could this be seperated off?

**Comment by bvellek** [comment]
Hey @ryanbr thanks for taking a look!

We unfortunately aren't able to pull these bits out into their own files. We consolidate the JS for performance reasons. As a third-party embed provider we've found that modern ecommerce sites will not tolerate extra JS roundtrips. This would also be a substantial change to our architecture.

The metrics related code in this file is simply in charge of generating the `jsonp`/`png` calls that actually would record the metrics. We've made this fix on EasyPrivacy in the past, so we're hoping to stick with that approach to blocking our metrics `jsonp`/`png` calls and not blocking a specific JS component. 

Please let me know if I can provide any additional information to assist in this process

**Comment by ryanbr** [comment]
There is impression/referrer/pageview checks, the need to seperate the tracking and impression stuff from the main script is still needed. As a privacy oriented list, It would look bad to let that go through unchanged. Once adjusted/reviewed, i'll just revert the change, this won't be needed. https://github.com/easylist/easylist/pull/4513

**Comment by ryanbr** [comment]
before closing this, I rechecked the scripts. Still having metrics tracking. Closing.
