### ISSUE TITLE
https://www.dplay.no/

### ISSUE THREAD

**Issue by adijanbekkijan** [easylist/easylist#4515]
https://www.dplay.no/

### What happens?
pop up, asking to deactivate adblock. 

- OS/version: MAC 10.14.16
- Browser/version: Chrome 79.0.3945.79
- Adblock Extension/version: Nano adblock 1.0.0.130

**Comment by llacb47** [comment]
Easylist doesn't deal with anti-adblock, close the issue, and report to Nano Adblocker/uBlock origin.

**Comment by Khrin** [comment]
Anti Adblocking messages aren't blocked by EasyList.
