### ISSUE TITLE
Lots of pull requests, any change to give more people a write access?

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#4522]
For example, smed79 has shown a great deal of activity in my opinion.

@ryanbr

**Comment by spirillen** [comment]
Maybe in combination with code-review or CODEOWNERS in this way you would ensure double check up submissions

**Comment by peace2000** [comment]
@spirillen But sending a pull request is already filling that function you are describing. There is lots of pull requests which means that more people with an actual write access are needed.

**Comment by ryanbr** [comment]
we don't conduct internal stuffs in GH

**Comment by spirillen** [comment]
> @spirillen But making a pull request is already filling that function you are describing. There are lots of pull requests which means that more people with an actual write access are needed.

Bit late, but revisiting the issue cos you comment in https://github.com/easylist/easylist/issues/8430#issuecomment-886114156

What I meant was you could at least at that time set a forced minimum of users who should have reviewed and approved any PR's as a extra layer of protection. With the extra layer of protection it would be easier to add more users with write (merge) access to the repo.

**Comment by peace2000** [comment]
@spirillen OK!
