### ISSUE TITLE
'/assets/*discord.png' filter too strict; breaks Discord logo image (hosted locally)

### ISSUE THREAD

**Issue by ranolfi** [easylist/easylist#4525]
### List the website(s) you're having issues:

`https://codidact.org/envs/demo-easylist/` _(edited!)_

### What happens?

We have an image (Discord logo) with an invitation link to our Discord server, but the image is blocked. The "offending" HTML code is the following:

```
<a href="https://discord.gg/WZ7aTst" class="btn-link" title="Discord (chat)">
    <img src="assets/img/3rd-party/logo-discord.png" alt="Discord logo" />
</a>
```

The rule in effect is: https://github.com/easylist/easylist/blob/607a6d2b67fb17e9d215b21bb4e59abc47fb7e3f/fanboy-addon/fanboy_social_general_block.txt#L318.

### List Subscriptions you're using:

Relevant one is [Fanboy’s Annoyance List](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt), according to the uBlock Origin logger.

### Your settings

(Issue is easily reproducible across a wide range of browsers and extensions)

### Other details:

Expected: 
![image](https://user-images.githubusercontent.com/8507649/70860983-fc37c680-1f06-11ea-8ce6-cbef31583ce7.png)

Current output: 
![image](https://user-images.githubusercontent.com/8507649/70860988-08238880-1f07-11ea-954e-1d0ecb6415b9.png)

Notice the Discord link (second from the left) is broken.

**Comment by krystian3w** [comment]
I suspect that this is a deliberate action related to the great popularisation of discord.

---

Possible only add exception discord domains:

 `/assets/*discord.png$domain=~discordapp.com`

**Comment by ranolfi** [comment]
> I suspect that this is a deliberate action related to the great popularisation of discord as "**social media element**".

It might be. But I'm having some difficulty figuring how the blocking of images with a name that ends in `discord`, within any directory hierarchy inside an `assets` dir and with the `.png` extension, no matter where it's hosted/served from, is as well-thought and really 'deliberate' as it is effective in achieving that effect.

> `/assets/*discord.png$domain=~discordapp.com`

What exactly does this syntax do? Will it block the image *except* if it's served by that domain, or *only* if it's so?

**Comment by llacb47** [comment]
except

**Comment by krystian3w** [comment]
When filter can't block any file/request `/assets/*discord.png` on `discordapp.com` (still block on `github.io`).

**Comment by ranolfi** [comment]
But we are hosting the image ourselves: `https://codidact.github.io/landing-page/assets/img/3rd-party/logo-discord.png`

**Comment by ranolfi** [comment]
> still block on `github.io`

And anywhere else other than local: `https://codidact.org/staging/` also fails.

**Comment by krystian3w** [comment]
`/assets/*discord.png$badfilter`
`/assets/*discord.png$third-party`

**Comment by ranolfi** [comment]
@krystian3w: In case you are proposing changing the filter rule definition in this repository - what difference is there between appending `$badfilter` and simply removing the rule entirely, if any?

Also an important question, maybe @ryanbr can answer this one: Given the purpose of the 'Fanboy Social List' is to "_**Hide and block** social content, social widgets, social scripts **and social icons**_"<sup>[\[1\]](https://www.fanboy.co.nz/filters.html)</sup> (emphasis mine), is it even possible to patch the rule definition here to fix the problem we're having without affecting the intended use case of the filter?

**Comment by krystian3w** [comment]
Badfilter works better as allow:


 `@@/assets/*discord.png`

Something like remove filter without edit files on Internet.

**Comment by ranolfi** [comment]
I don't quite follow. Which file(s) you refer to?

**Comment by krystian3w** [comment]
`easylist/fanboy-addon/fanboy_social_general_block.txt` or `/fanboy-addon/fanboy_social_whitelist.txt`

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#badfilter-modifier
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#badfilter

---

There's no basis for me to undo this filter - The button will probably refer to a dedicated channel, not the homepage.

**Comment by ranolfi** [comment]
You appear to be suggesting this shouldn't be fixed at the main filter subscription level, and instead I should advise our users to add a custom rule to their blockers. Is that correct?

FWIW, the problem started when I renamed the image from `discord-logo.png` to `logo-discord.png` (see [codidact/landing-page/b3246d37)](https://github.com/codidact/landing-page/commit/b3246d37), and was fixed by renaming the image yet again (in [260ff94f](https://github.com/codidact/landing-page/commit/260ff94f)). If it didn't reside in an `assets` folder we wouldn't be getting this.
If you ask me, there was little basis to accept PR #908 in its current form.

I politely request if we can get an actual project maintainer to weigh in here on how we shall proceed.

**Comment by llacb47** [comment]
@krystian3w is not an easylist author and does not represent the opinions of easylist (neither am I).

@ryanbr @Khrin

**Comment by ryanbr** [comment]
I'll happy whitelist the filter for discord-hosted users, I just checked via the discord web app, Not much being blocked. Its blocked like any other social element, why treat discord differently to facebook or twitter?

**Comment by ranolfi** [comment]
I don't know, can't give an authoritative answer; but speaking as someone who is both a member of the Codidact project *and* a subscriber to the Annoyances filter, it makes much more sense to me to have Facebook and Twitter icons blocked at large than the Discord icon. The former two strike me as much more "social without practical purpose" than the latter.

In our use case, Discord is as important as the Discourse Forum and GitHub, it's not there as a "_hey, check us on social media if you have time to waste!_", but rather as a "_we're coordinating our development efforts here, here and here_". So, as far as I'm concerned, all of [these](https://user-images.githubusercontent.com/8507649/70860988-08238880-1f07-11ea-954e-1d0ecb6415b9.png) could be blocked, not just one (in a manner that looks a bit arbitrary - and of course can be easily [bypassed](https://github.com/codidact/landing-page/commit/260ff94f#diff-f3c8e37dd0a73713fe739364dd4bcd98)).

But this might be due to the fact that I was entirely new to Discord until about two months ago, and don't actually use it for anything else, so it might be just me.

Anyway, it would make much more sense from my POV to block the Discord \*Widget\* at the EasyList level instead, which looks something like this:

    <iframe src="https://discordapp.com/widget?id=<server_id_numeric>&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0"></iframe>

Or, alternatively, block any Discord logo image that is nested in an `<a target="_blank" ...` element (is this possible? - and in fact, maybe block the entire `<a>` element, not just the image ) or block the Discord logo if and only if it's served from the Discord domain.

I might have other suggestions, but first if you'd let me know what you think so far...

Thanks :)
