### ISSUE TITLE
Howto? block whitlisted spyware

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#4529]
I have tried to make a rule that should overrule `uBlock filters` whitelisting of spyware

What I have tried is
```
||google.com^*recaptcha/$subdocument^$important
||google.com/recaptcha/$script,subdocument
||google.com/recaptcha/$important,script
```
https://gitlab.com/AnonymousPoster/ublockorigin-rules/blob/master/rules/blockrules.txt#L2

But it is not overruling the shit rule from uBlock
```
@@||google.com^*recaptcha/$subdocument
```

So how do I actually write this rule so it will block the spyware?

**Comment by THEtomaso** [comment]
I think the rule that you're refering to is this one?:
`@@||google.com^*recaptcha/$frame`
`$frame` will probably only show as `$subdocument` in uBO's logger.

So..
`||google.com^*recaptcha/$frame,badfilter`
or
`||google.com^*recaptcha/$frame,important`

This will most likely prevent you from accessing certain sites though.

**Comment by spirillen** [comment]
> This will most likely prevent you from accessing certain sites though.

Nope actually not :smile: It is badly written sites that prevent users from accessing them, as they spread spyware/track-ware and other risk-ware  :wink: 

```
dig google.com

; <<>> DiG 9.14.8 <<>> +nocookie google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 45061
;; flags: qr rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1500
;; QUESTION SECTION:
;google.com.                    IN      A

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Mon Dec 16 16:38:54 CET 2019
;; MSG SIZE  rcvd: 39
```

But as I'm not always have all my devices on my home network I preferring to have a "backup" solution to this.

But it is this rule

![image](https://user-images.githubusercontent.com/44526987/70920427-e0294780-2022-11ea-931e-fa556730a431.png)

![image](https://user-images.githubusercontent.com/44526987/70920481-f6370800-2022-11ea-9012-8f8ff0216bde.png)

After adding the rules to "my filters" The screen cap is looking the same :unamused: 

![image](https://user-images.githubusercontent.com/44526987/70920826-79f0f480-2023-11ea-8f32-269022de84c0.png)

**Comment by THEtomaso** [comment]
Where did that comma come from?
*first post edited*

**Comment by THEtomaso** [comment]
btw; I don't even see that whitelisting, when accessing the site shown in your screenshot.

**Comment by spirillen** [comment]
@THEtomaso I have the idea that could be lead to the fact I'm collecting data about those site to my [list](https://gitlab.com/my-privacy-dns/matrix/matrix/issues?label_name%5B%5D=NSFW+Adult+Material) and that Cloundfront started to dislike me as a bot :rofl: 

![image](https://user-images.githubusercontent.com/44526987/70924319-9728c180-2029-11ea-9d9e-4c8f81c9af7a.png)

But your right
> btw; I don't even see that whitelisting, when accessing the site shown in your screenshot.

I don't see that rule either on this computer (I have switched in the meantime :yum: ), so maybe and outdated rule?

**Comment by THEtomaso** [comment]
It's not outdated.
As you've seen yourself, it kicks in when there is suspection of a bot.

**Comment by spirillen** [comment]
Thx for the help @THEtomaso :+1: now it is working :smiley:
