### ISSUE TITLE
pornhub.com: ##.nonesuch

### ISSUE THREAD

**Issue by stanlane** [easylist/easylist#453]
Add this filters to remove the empty ad frames ("Ads by trafficjunky" on the screenshot) on the video pages that take up significant space where video thumbs will be listed instead when the filter is used.

pornhub.com##.nonesuch

![screenshot from 2017-08-23 00 39 15](https://user-images.githubusercontent.com/25944158/29590853-3573bd5a-879c-11e7-8311-8fd1fb2230ec.png)

**Comment by stanlane** [comment]
Can you please apply the filter?

**Comment by Khrin** [comment]
It's already present https://github.com/easylist/easylist/commit/3aa25f33c9c0bfa68eb0c122bf15b743be7e290a

**Comment by stanlane** [comment]
@Khrin They changed it to onesuch. So you must add this filter:
> pornhub.com##.onesuch

**Comment by stanlane** [comment]
@Khrin Note the difference between "nonesuch" and "onesuch".

**Comment by stanlane** [comment]
@Khrin Can you please fix it?
