### ISSUE TITLE
EasyPrivacy won't allow ibanez.com to load

### ISSUE THREAD

**Issue by mica** [easylist/easylist#4530]
The front page redirect is being blocked, preventing the site from loading: `https://www.ibanez.com/`

**Comment by THEtomaso** [comment]
Summary:

### Problem filter:
* EasyPrivacy

### Problem rules:
```
||maxmind.com^*/geoip2.js
||maxmind.com/geoip/$third-party
```

### Blocked script:
`https://js.maxmind.com/js/apis/geoip2/v2.1/geoip2.js`

### Possible fix:
`@@||maxmind.com^*/geoip2.js$domain=ibanez.com`

--

### Other problem filters:
* hpHosts' Ad and tracking servers (rule: `js.maxmind.com`)

**Comment by spirillen** [comment]
interesting `js.maxmind.com` :+1:  thanks for the side note it solved one for me :smiley:

**Comment by THEtomaso** [comment]
No reply yet, but I'll keep you posted.
Those hosts file guys aren't always too compliant though, because for them, in many cases, it's either block, or not block!

**Comment by THEtomaso** [comment]
@Khrin:
There is no request for `geoip.js`, so the first part of your fix is useless!

**Comment by Khrin** [comment]
My bad, now it's corrected.

**Comment by spirillen** [comment]
> because for them, in many cases, it's either block, or not block!

Yeah @THEtomaso  that's because you can block on subfolder levels with DNS (or rather outdated hosts) like you can with ex. uBlock

And you could, but doesn't always find the the real source to a problem with third party software, but adding a lot of unnecessary records vs blocking a domain :yum:  it's a HYDRA :smiling_imp:

**Comment by mica** [comment]
This problem has returned. Could someone reopen this issue?

**Comment by THEtomaso** [comment]
> This problem has returned.

Summary:

### Problem filter:
* EasyPrivacy

### Problem rule:
`||geoip-js.com^$third-party`

### Possible fix:
`@@||geoip-js.com/geoip/*/country/me?referrer=$domain=ibanez.com`
