### ISSUE TITLE
Signin with Apple broken

### ISSUE THREAD

**Issue by Christilut** [easylist/easylist#4531]
### List the website(s) you're having issues:

`https://fir-ui-demo-84a6c.firebaseapp.com/`

### What happens?

Logging in with "Sign in with Apple" with the [FirebaseUI](https://github.com/firebase/firebaseui-web) is broken. The popup after logging in display a white screen and doesn't continue. 

To reproduce:
1. Click "Sign in with Apple"
2. Log into Apple and continue
3. Then normally it will ask if you want to continue to login to this app. For me it shows a white screen

Whitelisting the FirebaseUI demo site doesn't help. Only disabling the uBlock extension works. Disabling EasyList also works.

![image](https://user-images.githubusercontent.com/3471363/71002516-b71abc80-20df-11ea-8b27-95afc788b1c5.png)

### Your settings

- OS/version: Windows 10
- Browser/version:  Chrome 79
- Adblock Extension/version: ublock origin 1.23.0

### Other details:

The FirebaseUI is used in a lot of websites and Apple support was only added recently.

**Comment by Khrin** [comment]
I can correctly open the popup, using either Abp or Ubo.

**Comment by Christilut** [comment]
The problem happens after logging into Apple. Normally it asks if you want to continue but for me it shows a white screen.

**Comment by monzta** [comment]
I was unable to reproduce it. Testes with recent default lists in uBlock Origin.
