### ISSUE TITLE
Unblock - cws.conviva.com^ and pings.conviva.com^

### ISSUE THREAD

**Issue by aniruddhav21** [easylist/easylist#4534]
### What happens?

Hi, i am an escalation manager at Conviva Inc and need help to unblock these domains i see listed under: easylist:easyprivacy/easyprivacy_thirdparty.txt

cws.conviva.com^ and pings.conviva.com^
We don't track any user level pii data and in the past we had these domains unblocked but they are blocked again.

### List Subscriptions you're using:

easylist:easyprivacy/easyprivacy_thirdparty.txt

### Your settings

- OS/version: Mac Mojave , Ver 10.14.6 (18G1012)
- Browser/version: [Google Chrome, Version 78.0.3904.108 (Official Build) (64-bit)]
- uBlock Origin version: [uBlock Origin v1.23.0]

### Other details:

I can unblock these domains by removing the filtering but this blocks our end users as well or anyone trying to request those urls.

![Screen Shot 2019-12-17 at 4 30 24 PM](https://user-images.githubusercontent.com/58999017/71053375-1807bc00-2103-11ea-8aa8-64c6b8378480.png)

**Comment by ryanbr** [comment]
I wonder if @aniruddhav21 actually visited his own site https://www.conviva.com/

```
One Platform. One Sensor.
Integrated analytics for your entire streaming video business.
```

**Comment by ryanbr** [comment]
I would prefer block the entire site with `||conviva.com^$third-party` but blocking `cws.conviva.com` and `pings.conviva.com` is least disruptive.

**Comment by gwarser** [comment]
> this blocks our end users as well or anyone trying to request those urls.

None of them complains.

**Comment by uBlock-user** [comment]
He probably meant his company's customers.

**Comment by spirillen** [comment]
> He probably meant his company's customers.

Who? :rofl:

**Comment by uBlock-user** [comment]
Conviva's clients if that question was not rhetorical.

**Comment by spirillen** [comment]
That was rather rhetorical :smiling_imp:

**Comment by tmastersmart** [comment]
This is not stopping Hulo from working. If they are asking to unblock it I think they should have to explain what its doing. Its clearly not blocking ads I still see ads, it must be tracking the videos played? Before I unblock it does anyone know what its doing?
