### ISSUE TITLE
Unclear License on antiadblockfilters.txt

### ISSUE THREAD

**Issue by g4jc** [easylist/easylist#4535]
**Filter List:** https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

> *Licence: https://easylist.to/pages/licence.html*

So, possibly:
> Unless otherwise noted, the contents of the EasyList repository (https://github.com/easylist) is dual licensed under the GNU General Public License version 3 of the License, or (at your option) any later version, and Creative Commons Attribution-ShareAlike 3.0 Unported, or (at your option) any later version.

However, I was unable to find this exact file in the github repo here. Could you confirm that this is a GPL3 licensed file and possibly update the `antiadblockfilters.txt` to specify the license as such?

Thank you.

**Comment by krystian3w** [comment]
here:

https://hg.adblockplus.org/antiadblockfilters/

**Comment by g4jc** [comment]
Thank you, but the there appears to be no license in that repository as well.

**Comment by FrostKnight** [comment]
I am actually curious of the license as well, can you give me a definitive answer?

**Comment by krystian3w** [comment]
IMO via e-mail only.

**Comment by Khrin** [comment]
Adblock Warning Removal List isn't managed by EasyList.

**Comment by FrostKnight** [comment]
> Adblock Warning Removal List isn't managed by EasyList.

I never did say this before, but thank you for your honest answer.  This was so strange to me...
