### ISSUE TITLE
EasyList blocks first 13 seconds of videos on independent.co.uk

### ISSUE THREAD

**Issue by mica** [easylist/easylist#4536]
Videos will start playing, but there's no picture for the first 13 seconds or so: https://www.independent.co.uk/environment/australia-heatwave-record-temperatures-pork-roast-car-stu-pengelly-a9249981.html

**Comment by peace2000** [comment]
Got no problems. What's your browser, lists being used, adblocking software?

**Comment by THEtomaso** [comment]
Problem confirmed.

Summary:

### Problem filter:
* EasyList

### Problem rule:
`||imasdk.googleapis.com^$third-party`

### Blocked script:
`https://imasdk.googleapis.com/js/sdkloader/ima3_debug.js`

### Possible fix:
`@@||imasdk.googleapis.com/js/sdkloader/ima3_debug.js$domain=brightcove.net`

**Comment by peace2000** [comment]
Deleted my previous comment. I partly missread the description. I confirm the error also and comfirm @THEtomaso fix.
