### ISSUE TITLE
pornhub.com: reCAPTCHA doesn't work

### ISSUE THREAD

**Issue by stanlane** [easylist/easylist#454]
On https://www.pornhub.com/support, the reCAPTCHA doesn't open with EasyList and/or EasyPrivacy enabled. I've disabled all other filter lists.

**Comment by stanlane** [comment]
https://www.pornhub.com/support now reads this with uBO enabled:

> Adblock or Easylist tends to break Pornhub functionality, including this form. Please try disabling Adblock before reporting any bugs.

**Comment by stanlane** [comment]
@Khrin Can you please try to unblock the reCAPTCHA?

**Comment by Khrin** [comment]
I can normally see and use the captcha provided in the page. If you are using Ublock Origin I have to guess that another subscription list beyond EasyList is hindering you the captcha in that page.

**Comment by stanlane** [comment]
> I can normally see and use the captcha provided in the page.

I stand corrected.


I asked the support to remove this message:

> Adblock or Easylist tends to break Pornhub functionality, including this form. Please try disabling Adblock before reporting any bugs.

**Comment by stanlane** [comment]
test

**Comment by stanlane** [comment]
https://github.com/uBlockOrigin/uAssets/issues/642

**Comment by stanlane** [comment]
@Khrin This filter:

> ###adblockMessage

will remove this text:



> Adblock or Easylist tends to break Pornhub functionality, including this form. Please try disabling Adblock before reporting any bugs.

Will you add it?

**Comment by Khrin** [comment]
No, I don't see why I should do that.

**Comment by stanlane** [comment]
@Khrin Do you think this is suitable for Fanboy's Annoyances?
