### ISSUE TITLE
MobyGames.com - Blocked images (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#4542]
### Affected site:
`https://www.mobygames.com/`

### Issue:
Each game has a section called "Promo Art".
In this section, some image files have the word "advertisement" in their names, and are therefore blocked!

### Random examples:
```
https://www.mobygames.com/game/lotus-esprit-turbo-challenge/promo/
https://www.mobygames.com/game/secret-of-monkey-island/promo/
https://www.mobygames.com/game/unreal-/promo/
https://www.mobygames.com/game/windows/bersoldier/promo/
```

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyList

### Problem rule (for the example pages above):
`-advertisement.`

### Possible fix:
`@@||mobygames.com/images/promo/$image`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.12 (XUL)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/19414f121e3cd82bc08131de39f442252ab5f935
