### ISSUE TITLE
r.orange.fr

### ISSUE THREAD

**Issue by otyugh** [easylist/easylist#4548]
#3529 # What happens?

Most people using orange.fr go in there to get to their webmail pass through "r.orange.fr" (to be exact : https://r.orange.fr/r/OGwebmail_inbox) and therefore using ublock origin or adblock (with easyprivacy as default), it get blocked with a compelling warning sign. 

Knowing that is this policy still justified ?

I'm merely asking because I get a lot of worried people asking about this behaviour after I'd installed ublock origin for them. If this is an intended behaviour, what should I tell them ? This website is regarded as a threat because ... ?

Thanks ! :)

**Comment by ryanbr** [comment]
removed
