### ISSUE TITLE
EasyList Forum Nightmare

### ISSUE THREAD

**Issue by Tiffys** [easylist/easylist#4550]
https://forums.lanik.us/ucp.php?mode=register - EasyList's website has decided to first tell me "No soup for you! It looks like you have been flagged as a spammer." while trying to register. Then:

> You have been banned from this board until Sun Jan 19, 2020 12:38 am.
> 
> Please contact the [Board Administrator](mailto:no-reply@lanik.us) for more information.
> 
> Reason given for ban: Found in the Stop Forum Spam database
> 
> A ban has been issued on your IP address.

It's not helpful that the only way to contact a forum administrator is a no-reply e-mail address that will inevitably never be read.

The information on that ban is clearly a lie because on https://www.stopforumspam.com/removal when entering my e-mail address and it autofilling my IP it states...

>  Sorry, errors were found in the information provided
> 
>     Neither your IP or email address is listed in our database. We suggest you use a different username, and/or contact the forum admin where you were denied and request that they allow you to register.

As aforementioned, contacting the forum administrator seems impossible.

I used the username Tiffany and a mixed case with numbers & symbols 22 character password.

**Comment by llacb47** [comment]
@LanikSJ

**Comment by LanikSJ** [comment]
>It's not helpful that the only way to contact a forum administrator is a no-reply e-mail address that will inevitably never be read.

These posts are extremely helpful. I have nothing better to do honestly.  And I've had to resort to no reply emails due to all the spam.  Isn't this how we got here to begin with? 🙄

First of all you've only tried to register once according to my logs.  Second I have no control what stopforumspam.com does or doesn't do.  If your information got on that list, yeah guess what ... anyway take it up with them and try again after you get that sorted out.

**Comment by Tiffys** [comment]
> > It's not helpful that the only way to contact a forum administrator is a no-reply e-mail address that will inevitably never be read.
> 
> These posts are extremely helpful. I have nothing better to do honestly. And I've had to resort to no reply emails due to all the spam. Isn't this how we got here to begin with? 
> 
> First of all you've only tried to register once according to my logs. Second I have no control what stopforumspam.com does or doesn't do. If your information got on that list, yeah guess what ... anyway take it up with them and try again after you get that sorted out.

@LanikSJ [It _isn't_ on **their** list.](https://i.imgur.com/YXsmEZL.png)

The only solution listed is "contact the forum admin where you were denied and request that they allow you to register".

I, too, have nothing better to do honestly than try to deal with this when already going out of my way to be a good samaritan on the internet to try to report an issue with a project.

**Comment by LanikSJ** [comment]
And what do you purpose I do about that? Like I said before:

> ... I have no control what stopforumspam.com does or doesn't do.

Take it up with the owners of that site I have no control what gets on their block list.

**Comment by Tiffys** [comment]
> And what do you purpose I do about that? Like I said before:
> 
> > ... I have no control what stopforumspam.com does or doesn't do.
> 
> Take it up with the owners of that site I have no control what gets on their block list.

I literally showed you a screenshot of their website telling me my email and IP isn't on any of their lists.

What you _should_ do is just approve the registration and remove the ban. It's not hard to do on phpBB. Then we can both stop worrying about this.

**Comment by LanikSJ** [comment]
Your registration never goes through there's nothing to approve. What do you propose I do about that exactly? 🍿

**Comment by Tiffys** [comment]
...are you seriously suggesting I download your current phpBB version, upload it to a test server, add your Stop Forum Spam add-on and troubleshoot for you, the forum administrator?

Back about 15 years ago even when someone failed during registration it'd still list their details and list it as not approved. One could go into the user list & find them and approve it. There was also a ban list, which you could remove someone (and/or an IP) from.

It doesn't even seem to be something that's never happened before... `https://www.phpbb.com/customise/db/extension/phpbb_3.1_stop_forum_spam/support/topic/190811` and before `https://www.phpbb.com/customise/db/extension/phpbb_3.1_stop_forum_spam/support/topic/153736`

...seems like a pretty shoddy add-on given prevailing events.

[This](https://www.phpbb.com/customise/db/extension/phpbb_3.1_stop_forum_spam/support/topic/204836) for instance mentions 

> the log file under Maintenance > User logs shows entries, Stop Forum Spam triggered: with user name IP and email, but if I search for these on the stopforumspam website it says Found 0 entries

It also seems there's [a solution](https://www.phpbb.com/customise/db/extension/phpbb_3.1_stop_forum_spam/support/topic/150986) for you.

**Comment by LanikSJ** [comment]
> Back about 15 years ago even when someone failed during registration it'd still list their details and list it as not approved. One could go into the user list & find them and approve it. There was also a ban list, which you could remove someone (and/or an IP) from.

Apparently you didn't read what I said so I'll say it again. Until your registration goes through there's nothing I can do. There's nothing wrong with the add-on as you're the only person who has issues with it in over 10 years of me using it.

**Comment by Tiffys** [comment]
> You have been banned from this board until Sun Jan 19, 2020 12:38 am.
> 
> Please contact the Board Administrator for more information.
> 
> Reason given for ban: Found in the Stop Forum Spam database
> 
> A ban has been issued on your IP address.

**Comment by Khrin** [comment]
Closing here because isn't related to EasyList subscriptions, but discussion can continue here if necessary.

**Comment by spirillen** [comment]
> > Back about 15 years ago even when someone failed during registration it'd still list their details and list it as not approved. One could go into the user list & find them and approve it. There was also a ban list, which you could remove someone (and/or an IP) from.
> 
> Apparently you didn't read what I said so I'll say it again. **Until your registration goes through there's nothing I can do.** There's nothing wrong with the add-on as you're the only person who has issues with it in over 10 years of me using it.
> 
> Your IP is not on any ban list.

Well, that's not entirely true...

I have also tried over the years to register from several networks.

But simply gave up from all the reasons @Tiffys gave above...
