### ISSUE TITLE
Fanboy's Annoyance list breaks gfycat.com

### ISSUE THREAD

**Issue by Tiffys** [easylist/easylist#4551]
### List the website(s) you're having issues:

Here's an example URL, it's probably NSFW.

`https://gfycat.com/unimportantbrokenglassfrog`

### What happens?

After about half a second after loading, the entire website just turns white. Essentially rendered inoperable. If I disable Fanboy's Annoyance list then the website loads normally.

### List Subscriptions you're using:

I have an entire list however I've narrowed down the problem filter as Fanboy's Annoyance. You can see the entire list along with some other information here: `https://old.reddit.com/r/uBlockOrigin/comments/edx8q2/gfycat_page_turns_white_after_half_a_second/`

### Your settings

- Adblock Extension/version: uBlock Origin 1.13.8

### Other details:

In uBlock's logger the following are listed in yellow from Fanboy's Annoyance:

```
##.share-page

##.follow-button

##.share-button

gfycat.com##.signup-call-to-action
```

The issue therefore logically applies to one of these filters which must be a badfilter.

I would have reported this on EasyList's forum but reference issue #4550.

**Comment by llacb47** [comment]
Wrong repo, already reported here https://github.com/ryanbr/fanboy-adblock/issues/1271
