### ISSUE TITLE
Problematic rule

### ISSUE THREAD

**Issue by PentagramTr** [easylist/easylist#4553]
### List the website(s) you're having issues:

```
https://saniyeanneyemekleri.com/tavuk-iskender-nasil-yapilir/
https://gorselpencere.com/salon-tasarimlari-ahsaba-sarilan-beton-sutunlar/
https://akillisebekeler.com/2018/10/10/elektrikte-uc-zamanli-tarife-karmasasi/
https://www.bebekodam.net/
https://ilkrehber.net/teknoloji/uzay/aya-gonderilen-tohumlar-filizlendi/
https://www.gebelikhesaplama.com/sezaryen-dogum-nasil-yapilir/
```

### What happens?
Font breaks the layout, icons and social buttons of many sites.
Could you completely remove the rule?
(I didn't see ads when I disabled rule.)

### List Subscriptions you're using: 

AdGuard Base-AdGuard Annoyances-AdGuard Social Media-AdGuard Tracking Protection-NoCoin Filter

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 71
- Adblock Extension/version: AdGuard 3.3.4

### Other details:

`-adsmanager/`
https://github.com/easylist/easylist/blob/59536325f09b4be230f9100aae2fe6583b57b12c/easylist/easylist_general_block.txt#L258

<details><summary>Screenshot:</summary>

![fontpng](https://user-images.githubusercontent.com/34379403/71325407-58997800-24fd-11ea-96cb-92139e6bbeeb.png)

</details>

---

<details><summary>saniyeanneyemekleri.com</summary>

![saniyeanne](https://user-images.githubusercontent.com/34379403/71324960-91821e80-24f6-11ea-91ca-f594ad0a5e88.png)

</details>
<details><summary>gorselpencere.com</summary>

![gorselpencere](https://user-images.githubusercontent.com/34379403/71324976-d9a14100-24f6-11ea-92c7-432a9f6702f1.png)

</details>
<details><summary>akillisebekeler.com</summary>

![akillisebekeler com](https://user-images.githubusercontent.com/34379403/71325374-ddd05d00-24fc-11ea-8ab3-76b6a155378f.png)

</details>
<details><summary>bebekodam.net</summary>

![www bebekodam net](https://user-images.githubusercontent.com/34379403/71325377-e759c500-24fc-11ea-9b34-8a8121a72163.png)

</details>
<details><summary>ilkrehber.net</summary>

![ilkrehber net](https://user-images.githubusercontent.com/34379403/71325386-02c4d000-24fd-11ea-8f56-e57a0a8f0695.png)

</details>
<details><summary>gebelikhesaplama.com</summary>

![www gebelikhesaplama com](https://user-images.githubusercontent.com/34379403/71325394-2b4cca00-24fd-11ea-9a5a-04300f29168c.png)

</details>
<details><summary>gebelikhesaplama.com-2</summary>

![gebelikhesaplama2](https://user-images.githubusercontent.com/34379403/71325398-330c6e80-24fd-11ea-95f8-1136bb8a9fad.png)

</details>

**Comment by THEtomaso** [comment]
Possible fix:
```
- -adsmanager/
+ -adsmanager/$~font
```
