### ISSUE TITLE
@@||ced.sascdn.com/tag/*/smart.js$domain=dr.dk

### ISSUE THREAD

**Issue by yspmedia** [easylist/easylist#4558]
### List the website(s) you're having issues:

`https://www.dr.dk/drtv/episode/bonderoeven_-kajsas-julegave_158483`

### What happens?

I find the whitelisting of `ced.sascdn.com` in `easylist/easylist_whitelist.txt`

However a local test to block this, doesn't show any difference to me on the above site, from where it origin

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +177 |  |  | `www.dr.dk` | 3 | xhr | `https://www.dr-massive.com/api/page?device=web_browser&ff=idp%2Cldp&isDeviceAbroad=false&item_detail_expand=all&lang=da&list_page_size=24&max_list_prefetch=3&path=%2Fepisode%2Fbonderoeven_-kajsas-julegave_158483&segments=DRTV&sub=Anonymous&text_entry_format=html` |
| +171 |  |  | `www.dr.dk` | 3 | xhr | `https://www.dr-massive.com/api/page?device=web_browser&ff=idp%2Cldp&isDeviceAbroad=false&item_detail_expand=all&lang=da&list_page_size=24&max_list_prefetch=3&path=%2Fse%2Fbonderoeven_-kajsas-julegave_158483&segments=DRTV&sub=Anonymous&text_entry_format=html` |
| +170 | @@\|\|ced.sascdn.com/tag/*/smart.js$domain=dr.dk | ++ | `www.dr.dk` | 3 | script | `https://ced.sascdn.com/tag/3310/smart.js` |
| +170 |  |  | `www.dr.dk` | 1 | doc | `https://www.dr.dk/drtv/se/bonderoeven_-kajsas-julegave_158483` |
| +111 |  |  | `www.dr.dk` | 3 | xhr | `https://www.dr-massive.com/api/page?device=web_browser&ff=idp%2Cldp&isDeviceAbroad=false&item_detail_expand=all&lang=da&list_page_size=24&max_list_prefetch=3&path=%2Fse%2Fbonderoeven_-kajsas-julegave_158483&segments=DRTV&sub=Anonymous&text_entry_format=html` |
| +110 | @@\|\|ced.sascdn.com/tag/*/smart.js$domain=dr.dk | ++ | `www.dr.dk` | 3 | script | `https://ced.sascdn.com/tag/3310/smart.js` |
| +110 |  |  | `www.dr.dk` | 1 | doc | `https://www.dr.dk/drtv/se/bonderoeven_-kajsas-julegave_158483` |
| +105 |  |  | `www.dr.dk` | 3 | xhr | `https://www.dr-massive.com/api/page?device=web_browser&ff=idp%2Cldp&isDeviceAbroad=false&item_detail_expand=all&lang=da&list_page_size=24&max_list_prefetch=3&path=%2Fse%2Fbonderoeven_-kajsas-julegave_158483&segments=DRTV&sub=Anonymous&text_entry_format=html` |
| +104 | @@\|\|ced.sascdn.com/tag/*/smart.js$domain=dr.dk | ++ | `www.dr.dk` | 3 | script | `https://ced.sascdn.com/tag/3310/smart.js` |
| +104 |  |  | `www.dr.dk` | 1 | doc | `https://www.dr.dk/drtv/se/bonderoeven_-kajsas-julegave_158483` |
| +21 |  |  | `www.dr.dk` | 3 | xhr | `https://www.dr-massive.com/api/page?device=web_browser&ff=idp%2Cldp&isDeviceAbroad=false&item_detail_expand=all&lang=da&list_page_size=24&max_list_prefetch=3&path=%2Fse%2Fbonderoeven_-kajsas-julegave_158483&segments=DRTV&sub=Anonymous&text_entry_format=html` |
| +20 | @@\|\|ced.sascdn.com/tag/*/smart.js$domain=dr.dk | ++ | `www.dr.dk` | 3 | script | `https://ced.sascdn.com/tag/3310/smart.js` |
| +20 |  |  | `www.dr.dk` | 1 | doc | `https://www.dr.dk/drtv/se/bonderoeven_-kajsas-julegave_158483` |
| +0 |  |  | `www.dr.dk` | 3 | xhr | `https://www.dr-massive.com/api/page?device=web_browser&ff=idp%2Cldp&isDeviceAbroad=false&item_detail_expand=all&lang=da&list_page_size=24&max_list_prefetch=3&path=%2Fepisode%2Fbonderoeven_-kajsas-julegave_158483&segments=DRTV&sub=Anonymous&text_entry_format=html` |
</details>

<details><summary>Screen dumps</summary>

![image](https://user-images.githubusercontent.com/22850042/71367202-acab6780-25a4-11ea-83df-218b3169f322.png)

Same view, with and without the blocking of `sascdn.com`
![image](https://user-images.githubusercontent.com/22850042/71367223-b6cd6600-25a4-11ea-8e2d-702936035c04.png)

![image](https://user-images.githubusercontent.com/22850042/71367253-cb116300-25a4-11ea-86a0-207aa6e94eb8.png)

</details>

### List Subscriptions you're using:

See dump

### Your settings

- OS/version: Ubuntu 19
- Browser/version: FF 
![image](https://user-images.githubusercontent.com/22850042/71367346-0e6bd180-25a5-11ea-99ff-18c7cde764c0.png)

- Adblock Extension/version: 
![image](https://user-images.githubusercontent.com/22850042/71367367-22173800-25a5-11ea-85e2-87b749e7592b.png)

### Other details:

First of I've unsuccessfully tried to overrule this whitelisting by:
```
||sascdn.com^$third-party^$important
```

Second I don't believe this rule should be whitelisted, but before submitting a MR I would like this confirmed by other users with danish IP-addresses. The reason is if other have a different experiences, as the rule is rather new), I wouldn't like to suggest a change that would brake things.

Ping @THEtomaso and @monzta I have a feeling of you are located in DK

## Other similar rules
```
grep -Ri "sascdn.com" easylist/ easylist_cookie/ easyprivacy/
easylist/easylist_adservers.txt:||sascdn.com^$third-party
easylist/easylist_whitelist.txt:@@||ced.sascdn.com/tag/*/smart.js$domain=dr.dk
easylist/easylist_whitelist.txt:@@||sascdn.com/diff/templates/ts/dist/banner/sas-banner-$script,domain=dr.dk
easyprivacy/easyprivacy_thirdparty_international.txt:||ced-ns.sascdn.com/diff/js/smart.js
```

## Blame (History)
```
git blame easylist/easylist_whitelist.txt | grep "sascdn.com"
55db70324f8 easylist/easylist_whitelist.txt (monzta    2019-10-29 21:43:34 +0100 664) @@||ced.sascdn.com/tag/*/smart.js$domain=dr.dk
55db70324f8 easylist/easylist_whitelist.txt (monzta    2019-10-29 21:43:34 +0100 698) @@||sascdn.com/diff/templates/ts/dist/banner/sas-banner-$script,domain=dr.dk
```

**Comment by THEtomaso** [comment]
I'm located in Norway, but at least, I can confirm that the site's videos and radio broadcasts play just fine, even when `ced.sascdn.com` is blocked.
Perhaps monzta can recall why the whitelisting was added.

**Comment by llacb47** [comment]
If you want to override the whitelisting you could add `,badfilter` to each filter or add `sascdn.com$third-party,important`.

**Comment by spirillen** [comment]
I sees no error on `dr.dk` by blocking `*.sascdn.com`

**Comment by monzta** [comment]
On the main page the items on the right page don't appear if this script is blocked.

**Comment by spirillen** [comment]
Hi @Khrin and @monzta I can reproduce that.

1. I'm living in DK
2. I block the domain in question in my DNS
```
dig ced.sascdn.com

;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;ced.sascdn.com.                        IN      A

;; Query time: 2 msec
```
3. <details></summary>Screen shot with ced.sascdn.com blocked</summary>

![image](https://user-images.githubusercontent.com/44526987/72173003-d5ba5d80-33d6-11ea-9ce4-d4b871bd7449.png)

![image](https://user-images.githubusercontent.com/44526987/72172660-fdf58c80-33d5-11ea-93d5-53c0e8b504ff.png)

</details>

4 <details></summary>Screen shot from Tor-Browser</summary>

![image](https://user-images.githubusercontent.com/44526987/72172991-c9ce9b80-33d6-11ea-8e1e-c7c941a4a38c.png)

![image](https://user-images.githubusercontent.com/44526987/72172793-5cbb0600-33d6-11ea-8aa8-6c6b6439fb8d.png)

</details>

@monzta Could you please post a dump of your issue

@Khrin could you please re open this issue to we have solved what the real issue is?

**Comment by monzta** [comment]
Are you saying you can or cannot reproduce the issue? 

Can you check in Firefox options if you have any sort of tracking protection enabled, try disabling it and see if that works?

**Comment by spirillen** [comment]
> Are you saying you can or cannot reproduce the issue?

can**'t**, fixed in update

`dr.dk` is running equally in both FF and Tor-browser.

> tracking protection enabled

Hmm = I'm pretty sure I have https://gitlab.com/my-privacy-dns/matrix/matrix :rofl: but that isn't inflicting on Tor Network :yum:

**Comment by monzta** [comment]
In Tor it's workig for me. That's with without ABP and default tracker blocking setting in Tor. 

![tor](https://user-images.githubusercontent.com/8057368/72504569-585f7480-383e-11ea-9d55-26781a0b60b4.png)

**Comment by spirillen** [comment]
That's weird... I use a very standard tor and I don't see chose spams in the right column...

![image](https://user-images.githubusercontent.com/44526987/72505363-13d4d880-3840-11ea-9f55-28bbe7e9014b.png)

**Comment by spirillen** [comment]
![image](https://user-images.githubusercontent.com/44526987/72505506-5c8c9180-3840-11ea-8b55-c3da01d93da7.png)

**Comment by monzta** [comment]
Are you using any other extensions like NoScript?

**Comment by spirillen** [comment]
Yeah, but noscript isn't blocking anything, it say 0 of 4 blocked

![image](https://user-images.githubusercontent.com/44526987/72619453-98595100-393d-11ea-853f-0f58b1dcf728.png)

![image](https://user-images.githubusercontent.com/44526987/72619627-fede6f00-393d-11ea-85a3-ae956930e530.png)

![image](https://user-images.githubusercontent.com/44526987/72619635-06057d00-393e-11ea-9a55-5d6bec06700e.png)

![image](https://user-images.githubusercontent.com/44526987/72619737-3cdb9300-393e-11ea-8a50-d92daa6e5260.png)

AS you can see, no difference if they are enabled or not.

So I can't reproduce your screenshot

**Comment by monzta** [comment]
Well then I don't know. I just see that these exception rules are necessary for the content on the right to appear.
