### ISSUE TITLE
Facebook Pixel Being Proxied by Shogun/Getshogun/Shopify Sites

### ISSUE THREAD

**Issue by ilikenwf** [easylist/easylist#4559]
The typical rules don't seem to remove it...

I visited pedalcommander.com, and later had a facebook ad for the device.

I have EasyPrivacy and Fanboy's stuff enabled, and since I'm using container tabs I find it very disturbing that I'm seeing ads for this site when I haven't even entered any info on it.

Unfortunately, blocking the cdn, cloudfront server, and getshogun.com domains break pedal commander's site.

Any suggestions/ideas?

**Comment by spirillen** [comment]
Hi @ilikenwf You got my attention, but not the solution :unamused: 

Do you have any records from the calls to that FB pixels? or links to where it might be possible to reproduce?

**Reason**:
I would like to see if I would be able to block this on DNS/hosts level in my matrix.

**Comment by ilikenwf** [comment]
It's not calling facebook at all, which is what is disturbing.

Looking at their javascript, the facebook tracking pixel id is included
but it appears that things are going through the shgcdn.com,
getshogun.com, and the odd cloudfront server, unless shopify is doing
the proxying as well.

https://gist.github.com/ilikenwf/55eb455edbfb08b282e7ee521e7d1fea

**Comment by ilikenwf** [comment]
...actually it looks to be shopify's code that's potentially doing this. There may be no way out if shopify is just in the backend sharing visitor IP addresses with advertisers.

```
trekkie.load = function(config) {
    trekkie.config = config;
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.onerror = function(e) {
      (new Image()).src = '//v.shopify.com/internal_errors/track?error=trekkie_load';
    };
    script.async = true;
    script.src = 'https://cdn.shopify.com/s/javascripts/tricorder/trekkie.storefront.min.js?v=2019.11.04.1';
    var first = document.getElementsByTagName('script')[0];
    first.parentNode.insertBefore(script, first);
  };
  trekkie.load(
    {"Trekkie":{"appName":"storefront","development":false,"defaultAttributes":{"shopId":5010686042,"isMerchantRequest":null,"themeId":68206624858,"themeCityHash":"11404290786758808590","contentLanguage":"en","currency":"USD"}},"Performance":{"navigationTimingApiMeasurementsEnabled":true,"navigationTimingApiMeasurementsSampleRate":1},"Google Analytics":{"trackingId":"UA-73766386-1","domain":"auto","siteSpeedSampleRate":"10","enhancedEcommerce":true,"doubleClick":true,"includeSearch":true},"Facebook Pixel":{"pixelIds":["933838300027829"],"agent":"plshopify1.2"},"Google Gtag Pixel":{"conversionId":"AW-940109594","eventLabels":[{"type":"page_view","action_label":"AW-940109594\/57psCMqVrqsBEJreo8AD"},{"type":"purchase","action_label":"AW-940109594\/o4YvCM2VrqsBEJreo8AD"},{"type":"view_item","action_label":"AW-940109594\/mrpGCNCVrqsBEJreo8AD"},{"type":"add_to_cart","action_label":"AW-940109594\/9OxQCNOVrqsBEJreo8AD"},{"type":"begin_checkout","action_label":"AW-940109594\/-mvFCNaVrqsBEJreo8AD"},{"type":"search","action_label":"AW-940109594\/KxqyCNmVrqsBEJreo8AD"},{"type":"add_payment_info","action_label":"AW-940109594\/vG10CNyVrqsBEJreo8AD"}],"targetCountry":"US"},"Session Attribution":{}}
  );```

**Comment by ilikenwf** [comment]
Blocking these may work?

cdn.shopify.com/s/javascripts/tricorder/*
v.shopify.com/internal_errors/*

**Comment by spirillen** [comment]
It is this part that load a image
https://gist.github.com/ilikenwf/55eb455edbfb08b282e7ee521e7d1fea#file-pedalcommander_shogun_shopify-html-L58-L63

and the domain from where it is loaded is the `v.shopify.com` but that is only tricked if the script got an error

The facebookPixel is load in this script call https://gist.github.com/ilikenwf/55eb455edbfb08b282e7ee521e7d1fea#file-pedalcommander_shogun_shopify-html-L66

```js
e.enabledIntegrations.push(["Facebook Pixel",o.FacebookPixel]);var i=r(17);e.enabledIntegrations.push(["Google Analytics",i.GoogleAnalytics]);var a=r(18);e.enabledIntegrations.push(["Clickstream",a.Clickstream]);
```

so the true call seems to me as loaded here
```
{this.loadFacebookScript();for(var e=this.options,r=e.pixelIds.concat([e.pixelId]),n=0,o=r;n<o.length;n++){var i=o[n];null!==i&&""!==i&&(window.fbq("init",i),""!==e.agent&&window.fbq("set","agent",e.agent,i))}t()},e.prototype.loadFacebookScript=function(){if(!window.fbq){window.fbq=function(){window.fbq.callMethod?window.fbq.callMethod.apply(window.fbq,arguments):window.fbq.queue.push(arguments)},window._fbq||(window._fbq=window.fbq),window.fbq.push=window.fbq,window.fbq.loaded=!0,window.fbq.version="2.0",window.fbq.queue=[];var t=i.virtualDocument().createElement("script");t.async=!0,t.src="https://connect.facebook.net/en_US/fbevents.js"
```

Which leads us to the real sinner

`https://connect.facebook.net/en_US/fbevents.js`

So again, `connect.facebook.net` is the real call.

Can you try to block this domain ex. in your hosts file for verification?

And as always, please school us if you find other/better knowledge

**Comment by ilikenwf** [comment]
Hm, guess I wasn't already blocking that domain. Neither umatrix nor
ublock show it, and so that freaks me out a bit.

In the event I am blocking it already, I wonder if some other cancerous
system is in place to correlate my visit.

**Comment by THEtomaso** [comment]
How about `||recart.com/tracking`?
I don't see it being blocked by any of my filters, and doing so doesn't seem to break anything.

**Comment by spirillen** [comment]
Hi @THEtomaso 

So you can still access that scary FB site if you block `connect.facebook.net` I'm asking as, somewhere in my mind I recall something about a discussion about this in the past... 

And yes, I don't have any FB and will never get it :smiling_imp:

**Comment by THEtomaso** [comment]
It's a very nasty page.
In uBO's logger, I see a lot of conntections blocked to `affirm.com, cloudfront.net, doubleclick.net, facebook.net, getshogun.com, google-analytics.com, hs-analytics.net, hsadspixel.net, hscollectedforms.net, powr.io, privy.com, refersion.com, rollbar.com, shopify.com and youtube.com`
..but the page still seems to load just fine!

**Comment by THEtomaso** [comment]
Blocking `connect.facebook.net` by default might cause issues on other sites though.
Fanboy's Anti-Facebook List contains several whitelistings for it:
https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/fanboy-antifacebook.txt

**Comment by spirillen** [comment]
That's what I always has said, FB is broken :smiling_imp:

**Comment by THEtomaso** [comment]
Should be `||facebook.*^`, for all I care!

**Comment by ryanbr** [comment]
Haven't blocked facebook (because that would be bad for many people) I have blocked:
`/shopify-boomerang-` https://github.com/easylist/easylist/commit/4941867c77be344f2760a71a5f327f02aee7c281
`||v.shopify.com^` https://github.com/easylist/easylist/commit/2191b911dae
`||recart.com/tracking/` https://github.com/easylist/easylist/commit/67efda33ec08407a997e1c101f025bbb906cd41c

And as others said, there is an Anti-Facebook list. Or alternatively use Brave which blocks Facebook by default.
