### ISSUE TITLE
proxy.php by powr.io | yvoschaap.com to www.producthunt.com

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#4563]
### List the website(s) you're having issues:

`www.powr.io`

### What happens?

I found this in the logger:

```
https://yvoschaap.com/producthunt/proxy.php?url=https%3A%2F%2Fwww.producthunt.com%2Fr%2F1e976c4ea8917c&per_page=1&key=c178e3cfaf64e664b1f9b403a7e275849a4c96fb&callback=phShare
```

### Other details:

As the url indicates, there is the `/proxy.php` for redirecting/proxiing to `www.producthunt.com`.

What I think, haven't been digging deeper, is this something we endorse or like? 

From DNS/hosts point of view, it's looks wrong to block these domains

```
producthunt.com
yvoschaap.com
```

As they in them self doesn't seems harmful, but on the other hand they leads to cross-site tracking.

<details><summary>Dump from the logger</summary>

![image](https://user-images.githubusercontent.com/44526987/71417715-18ee9f80-2667-11ea-9830-5b6906c1db5a.png)

</details>

What do you think? Speak freely and polite.

**Comment by ryanbr** [comment]
Not sure what the issue is, but some sites do this.. most are fine. Unless its actually doing something harmful  or going through an adserver/tracker then its okay.
