### ISSUE TITLE
justwatch.com [ads]

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#4589]
### List the website(s) you're having issues:

`https://www.justwatch.com/pl/nowe`

### What happens?

`Fanboy's Social Blocking List` recover ads "leftover".

Guilty:

https://github.com/easylist/easylist/blob/cd976095e3d8fe62b2e5808240ac99086680baf1/fanboy-addon/fanboy_social_whitelist.txt#L325

### List Subscriptions you're using:

`EasyList`
`Fanboy's Social Blocking List`

### Your settings

- OS/version:  Windows 10 Pro
- Browser/version: Firefox 71
- Adblock Extension/version:  3.7.0

### Other details:

Screen:

![obraz](https://user-images.githubusercontent.com/35370833/71448778-f2049c00-2740-11ea-8578-c3c413eab98a.png)

`justwatch.com##.ad-unit`

**Comment by ryanbr** [comment]
resolved
