### ISSUE TITLE
dehn.de: Cookie overlay is still visible

### ISSUE THREAD

**Issue by gralpli** [easylist/easylist#4592]
### List the website(s) you're having issues:

`https://www.dehn.de/`

### What happens?

The cookie warning itself is blocked, but the overlay in the background is still visible (and the website is not usable).

### Other details:

`dehn.de##div.dehn-cookieconsent-overlay`

does remove it.

**Comment by gralpli** [comment]
I just noticed that scrolling is not possible after the overlay has been removed. So my rule is not sufficient.

**Comment by THEtomaso** [comment]
Summary:

### Problem filters:
* AdGuard Annoyances filter (@BlazDT)
* Fanboy's Annoyance List / EasyList Cookie List (a.k.a. Fanboy's Cookie List) (@ryanbr)
* I don't care about cookies (@kiboke)

### Problem rule:
`###cookieConsent`

### Possible/Temporary fix (allowing the cookie consent popup):
`dehn.de#@##cookieConsent`

**Comment by BlazDT** [comment]
Fixed for AdGuard.

**Comment by peace2000** [comment]
`www.dehn.de##body:style(overflow: auto !important;)` This fixes the scrolling issue.
