### ISSUE TITLE
#4493 blocks all usages of ua-parser.js

### ISSUE THREAD

**Issue by LordAro** [easylist/easylist#4602]
easyprivacy list

#4493 blocked [ua-parser.js](https://github.com/faisalman/ua-parser-js), a common (purely client side) user agent detection library.

This has happened before: https://github.com/faisalman/ua-parser-js/issues/356 and was quickly reverted.

Can this be reverted again (and some protection against it happening again?)

**Comment by ryanbr** [comment]
Investigating, but UA detection should be considered tracking.

**Comment by llacb47** [comment]
No... It's only tracking when the user agent is sent to the server. As LordAro said, this library is client-side, so it should not be blocked.

**Comment by ryanbr** [comment]
has been removed
