### ISSUE TITLE
EasyPrivacy blocking insight.rapid7.com

### ISSUE THREAD

**Issue by bturner-r7** [easylist/easylist#4608]
### List the website(s) you're having issues:

`https://insight.rapid7.com/`

### What happens?

EasyPrivacy appears to be incorrectly blocking access.  Page displays but cannot log in.  Requests to `insight.rapid7.com/api/*` are blocked.

### List Subscriptions you're using:

* EasyList
* EasyPrivacy

### Your settings

- OS/version: OSX 10.14.6
- Browser/version: Chrome 79.0.3945.88
- Adblock Extension/version: 3.7

### Other details:

Block originally added here: https://github.com/easylist/easylist/commit/32b6089c4e21948f10bb00fb50e1ae0e8ea61a74

insight.rapid7.com isn't a tracking domain, it is the location where Rapid7 hosts its SaaS products.

**Comment by jfrantz1-r7** [comment]
@ryanbr @Khrin Any update on this?

**Comment by ryanbr** [comment]
Adjusted.
