### ISSUE TITLE
easylist cookie breaks sourceforge

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#4629]
### List the website(s) you're having issues:

`https://sourceforge.net/projects/mpcbe/files/latest/download`

### What happens?

download doesn't start, timer doesn't count down

### List Subscriptions you're using:

easylist fr + easylist cookie

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by Khrin** [comment]
Downloads starts for me. What browser/adblocker are you using?

**Comment by momala454** [comment]
firefox
ublock origin

i think this filter is causing the problem 
||consentmanager.mgr.consensu.org^$3p

**Comment by momala454** [comment]
i also have list uBlock filters and uBlock filters - unbreak active

**Comment by spirillen** [comment]
`consensu.org` is a godaddy hijacked domain...

https://gitlab.com/my-privacy-dns/matrix/matrix/issues/271#note_267825322

**Comment by momala454** [comment]
`https://consentmanager.mgr.consensu.org/`
is not displaying godaddy website

**Comment by spirillen** [comment]
> `https://consentmanager.mgr.consensu.org/`
> is not displaying godaddy website

Weird, it does to me in the tor-browser as the screenshot shows

But your right, this is what I sees today:

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/71919084-166e6880-3184-11ea-9dc2-fcc068f3cd85.png)

</details>

**Comment by momala454** [comment]
back to the topic, are you able to reproduce the problem on sourceforge ?

**Comment by spirillen** [comment]
Hi @momala454 

I can confirm the counter ain't working, when consensu is blocked

<details><summary>ScreenShot</summary>

![image](https://user-images.githubusercontent.com/44526987/71926778-5d645a00-3194-11ea-9f8b-3a02b11c5736.png)

```
dig consentmanager.mgr.consensu.org

;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;consentmanager.mgr.consensu.org. IN    A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jan 07 21:26:52 CET 2020
;; MSG SIZE  rcvd: 60
```

</details>

**Comment by okiehsch** [comment]
> Downloads starts for me.
@Khrin you need to try with a EU IP to reproduce the breakage.
It works fine with a US IP on my end.

**Comment by Khrin** [comment]
Ok, found it, thank you. Beforehand I thought to be behind EU IP. Now should be working.

**Comment by peace2000** [comment]
https://sourceforge.net/projects/megui/files/latest/download I can download now (the counter starts) even if I block consensu.org.

**Comment by krystian3w** [comment]
AdGuard made:

```
!##+js(no-setTimeout-if, window.cmpmngr.loadSettings, 30)
sourceforge.net##+js(set-constant, window.cmpmngr.setConsentViaBtn, noopFunc)
```
