### ISSUE TITLE
Block Sovrn Anti-Adblock Scripts  [Pull Request #483]

### ISSUE THREAD

**Issue by PowerAccess** [easylist/easylist#463]
Please add the following filters for Sovrn's anti-adblock scripts & popups:

They seem fairly popular commercial anti-adblock solutions and those are just the script hosting domains (as opposed to the sovrn.com corporate site), so I would suggest adding without a domain anchor:

```
||lijit.com^$third-party
||sovrnlabs.net^$third-party

###sovrn_container
###sovrn_beacon
```

You can see this anti-adblock script in action at:
http://westeros.org

**Comment by xeonx1** [comment]
Please approve my Pull Request #483 to add block and hide rules for Sovrn's commercial anti-adblock and ad scripts, with commits adding what I had described above.

**Comment by PowerAccess** [comment]
Can Pull Request #483 be approved? 
It's for a commercial anti-adblock script that prevents adblock usage on many sites.
