### ISSUE TITLE
staticcache.org

### ISSUE THREAD

**Issue by nickperry** [easylist/easylist#4630]
### List the website(s) you're having issues:

`https://www.williamhill.com`
`https://sports.williamhill.com`

### What happens?

staticcache.org is a domain owned and operated by William Hill for serving static assets. With staticcache.org blocked, it is not possible for customers to use Willam Hill's services.

### List Subscriptions you're using:

Easylist Privacy

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome
- Adblock Extension/version: uBlock Origin

### Other details:

This is the entry on the list: https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt#L2166
added in this commit - https://github.com/easylist/easylist/commit/292bbaa78dbd0e41589be7d43ede262d474e1b7b

**Comment by spirillen** [comment]
Hmm from duckduckgo.com

![image](https://user-images.githubusercontent.com/44526987/71848781-be2a5e80-30d0-11ea-9041-a22a4aed40df.png)

I can't remember, but is there a gambling list where this one should be submitted along site with the `williamhill.com`
