### ISSUE TITLE
netblock.js block rule too broad

### ISSUE THREAD

**Issue by zschutt** [easylist/easylist#4636]
### List the website(s) you're having issues:

Affected sites are behind authentication and not publically accessible.

### What happens?

We use a script named `netblock.js` that is completely unrelated to any sort of advertisements on our site (we have no ads on it at all). The addition of `/netblock.js$script` to `easylist_general_block.txt` is blocking the script and as a side effect everything else on the page. Looking at the commit message it appears that it was for a specific site, would it be possible to remove or domain-limit this filter rule so it's not blocking things on sites it shouldn't?

### List Subscriptions you're using:

EasyList

### Other details:

https://github.com/easylist/easylist/commit/a977979ea1485513362350236617aea3f36e4c06
https://github.com/easylist/easylist/blob/master/easylist/easylist_general_block.txt#L8084

**Comment by Khrin** [comment]
What site?

**Comment by zschutt** [comment]
It's several sites running a closed source network management database we develop. Since they're all behind authentication I'm unable to provide a live link. The URL that is being blocked looks similar to this (I've removed sections that are irrelevant).

`https://example.hostname/glue/index.cgi?method=get_files&path=GRNOC/widget/Netblock/1/Netblock.js`

**Comment by spirillen** [comment]
A thought on this:

> We use a script named netblock.js that is completely unrelated to any sort of advertisements on our site (we have no ads on it at all).

What is the script actually doing? What is it's intention and how can it be abused. (I think any kind of fingerprinting and tracking here)

**Comment by zschutt** [comment]
It's part of the frontend of the web app that sets up how netblocks are displayed, adding a widget and enabling sorting/pagination. Nothing to do with fingerprinting or tracking.

**Comment by Khrin** [comment]
Hope this change may helps. https://github.com/easylist/easylist/commit/39e471b45330674651f96753369a1c8a319182eb
