### ISSUE TITLE
/smartserve- blocked incorrectly

### ISSUE THREAD

**Issue by oliverwoodings** [easylist/easylist#4638]
### List the website(s) you're having issues:

All clients of Qubit - `https://qubit.com`
Examples include:
- `https://www.kurtgeiger.com/`
- `https://www.unjourailleurs.com/fr/`
- `https://www.topshop.com/`

### What happens?

I work for Qubit, an A/B testing and personalisation provider. We only deal with first-party client data and first-party cookies. We do track data, so we should be on the easyprivacy list, however our product has no connection to advertising, does not serve ads, and does not integrate with third party advertising companies (we do not share data). 4 days ago the filter `/smartserve-` was added to the general easylist, which has blocked our script on all our clients websites.

Our clients primarily use us to power features on their sites such as:
- Product recommendation carousels
- Back in stock notifications
- Campaign banners
- Social proof messaging
- Cart abandonment messaging

Currently, all of these features will not be working for our clients for users that have easylist, which could in certain cases be removing user functionality.

### List Subscriptions you're using:

https://github.com/easylist/easylist/blob/master/easylist/easylist_general_block.txt

### Other details:

This issue is caused by this rule: `/smartserve-` in this commit: https://github.com/easylist/easylist/commit/0e1778804b379103bd28899013dfc7f044ad5234

It is not clear from this commit why it was added. `https://www.unjourailleurs.com/fr/` is a client of ours, however they do not serve ads through us.

**Comment by TheStinkySkunk** [comment]
@ryanbr : Look https://github.com/easylist/easylist/commit/32388179c976b697463cb6896479da2dccfcb163

**Comment by oliverwoodings** [comment]
@TheStinkySkunk sorry I'm not sure how that commit is connected to this issue?

**Comment by spirillen** [comment]
Hi @oliverwoodings would it be possible that you would reveile all the domains from which you are hosting this/these scripts?

I found these `goqubit.com` and `qubit.com` so far.

In case you would like to contribute to the list of unwanted dtracking domains, this is the repo-file to add to: https://gitlab.com/my-privacy-dns/matrix/matrix/blob/master/source/tracking/wildcard.list

Alternatively you are of curse also welcome to "only" open and [ticket](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/new)

Crossing my fingers as you have been rather open so far :smile:

**Comment by oliverwoodings** [comment]
@spirillen can I ask the purpose of that list you are maintaining on my-private-dns? 

If your goal is to prevent cross site tracking and data collection then we should not be in this list, because qubit does not share data or track users across websites.

However, if your goal is to prevent all data collection of all kinds, then you are missing a ridiculous amount of stuff in this list, including the majority of our competitors in the space of A/B Testing, Optimization and Personalisation.

**Comment by spirillen** [comment]
Hi @oliverwoodings It's a mix of both. The main goal is to prevent any kind of tracking. The mix begins as many things would have to be in to many subgroups to be able to maintain it in a fair manor.

> including the majority of our competitors in the space of A/B Testing, Optimization and Personalisation.

Much of it still comes from hosts-file project and EasyList. And I would claim it is a 100% correctness within the lists.

The tracking list therefore contain anything you can relate to tracking as a topic, the same goes for the other lists.

**Comment by oliverwoodings** [comment]
@spirillen under your definition of tracking, I would suggest blocking all providers that appear in these lists:

https://www.gartner.com/en/documents/3945648/magic-quadrant-for-personalization-engines
https://conversion-rate-experts.com/split-testing-software/

Because they all collect first party data from their clients sites.

**Comment by oliverwoodings** [comment]
@ryanbr sorry to tag you in this directly, is there any chance we could get this removed ASAP please? More and more clients are complaining to us that parts of their website are no longer functioning correctly. For example, glasses direct.co.uk rely on us to build their entire navigation bar, which currently does not work for people with adblock.

**Comment by oliverwoodings** [comment]
@Khrin would you have time to take a look at this please if possible? We are getting increased pressure from our clients to come up with a solution for this. Here are some screenshots of the degraded user experience being observed on https://www.glassesdirect.co.uk/

### With Qubit

![Screenshot 2020-01-14 at 09 48 59](https://user-images.githubusercontent.com/621323/72333246-6208a100-36b3-11ea-806f-2ce0189fa82d.png)

### Without Qubit

![Screenshot 2020-01-14 at 09 49 57](https://user-images.githubusercontent.com/621323/72333254-6765eb80-36b3-11ea-8b6b-56ae17c9c649.png)

For this client, our product is providing a customisable navigation bar for the client that delivers a drastically improved user experience over the site's original functionality.

**Comment by ryanbr** [comment]
This is a privacy issue, and you need to fix it, not us.

**Comment by oliverwoodings** [comment]
@ryanbr sorry I'm not sure you've interpreted my messages correctly. I am not complaining about qubit being on the easyprivacy list. That is 100% correct.

What I am requesting is that we be removed from the general easylist, i.e the one that is meant to remove ads only, because we are not an ad server.

I have looked over previous issues in this repo and can see many other cases where companies have appealed situations like this and have been removed from the list. Here is an example where a personalisation provider like us was added and then removed from the general easylist: https://forums.lanik.us/viewtopic.php?f=64&t=30015&p=92375&hilit=optimizely#p92375

Could you please explain what is different about ours? I feel that you have misunderstood what Qubit does. When you say it is a privacy jssue and we need to 'fix it', I don't quite understand what you are expecting us to 'fix'?

**Comment by oliverwoodings** [comment]
@ryanbr here is another example where optimizely (who is another provider in our industry) in our industry, was also removed from the general easylist: https://forums.lanik.us/viewtopic.php?f=64&t=21217&p=67386&hilit=optimizely#p67386

**Comment by oliverwoodings** [comment]
@ryanbr I believe that mixpanel is also a similar case to us. They are on the easyprivacy list but not on the general one: https://github.com/easylist/easylist/search?q=mixpanel&type=Code

Like mixpanel, Qubit does not do cross site tracking of any kind. Any data collection is kept within the context of the site it was generated on. We do not use **any** third party cookies in our tech, nor do we use **any** kind of link decoration.

**Comment by ryanbr** [comment]
Moved to EP.

**Comment by oliverwoodings** [comment]
Thank you, much appreciated
