### ISSUE TITLE
EasyList Cookie not filtering overlay on UGC.fr

### ISSUE THREAD

**Issue by SylvainBigonneau** [easylist/easylist#4649]
### List the website(s) you're having issues:

`https://www.ugc.fr/`

### What happens?

The cookie banner on the bottom is hidden correctly, but the overlay stays.

Filtering the overlay with:

```
www.ugc.fr##.ui-widget-overlay.ui-front.ui-widget-overlay-grey.ui-widget-overlay-noevents
```
fixes the issue.

### List Subscriptions you're using:

EasyList Cookie

### Your settings

- OS/version: Ubuntu 19.10
- Browser/version: Firefox 71.0
- Adblock Extension/version: uBlock Origin 1.24.2

**Comment by krystian3w** [comment]
`##.ui-dialog[aria-describedby*="gdpr"] ~ .ui-widget-overlay`
