### ISSUE TITLE
No readme or readily visible documentation

### ISSUE THREAD

**Issue by atimholt** [easylist/easylist#4658]
I see that issue #668 was about this issue, but it was closed without being resolved or rejected. It is impossible for anyone to know anything about this project at all, aside from context. At the very least, lists have to have more description than an ambiguous name. If there is some kind of de facto standard for various blocking lists’ names, I have no way to know: there’s no readme.

**Comment by ryanbr** [comment]
Its on the site, no need for a readme. https://easylist.to/
