### ISSUE TITLE
.online^$third-party,xmlhttprequest

### ISSUE THREAD

**Issue by zmikolaj** [easylist/easylist#466]
Hello,
why this list block .online requests? Im using api third party with this domain and i need to disable adblock to use it.

**Comment by G-Rath** [comment]
We're in the same boat - We have a legitimate platform running on a `.online` domain, that is now having *all* its requests blocked, which breaks the entire site. 

Am very interested to know why such a broad rule has been added, and what we can do about getting our legitimate domains whitelisted.

**Comment by G-Rath** [comment]
It seems this line came from a51a989a8159756333b8d1eb8b5ba65f257bb4c8, committed three days ago with the message 'M: Add more propellar blocks'.

I'm assuming this is meant to target ads from Propeller Ads?
