### ISSUE TITLE
Popunders on torrent.tm

### ISSUE THREAD

**Issue by mimmiepower** [easylist/easylist#4662]
### List the website(s) you're having issues:

Though the landing page does not have any issues I do not want to link to any subpage on this website, since it could contain pirated or malicious content:
`https://torrent.tm/
`The problem occurs when clicking on links. Just about any link, even those that lead to first party pages, though not the search button.

### What happens?

Popunders when clicking on links, including links to first party pages.

### List Subscriptions you're using:

A lot. But this is obviously not caused by any other filters nor content blocking extensions.

### Your settings

Default uBlock Origin except cloud support and additional filters.

- OS/version: Windows 10 64-bit
- Browser/version: Firefox latest
- Adblock Extension/version: Ublock Origin

### Other details:

None.

**EDIT:** `||35.238.205.163^$popup` automatically closes the popups. Still pretty annoying. I have tried disabling all scrips but that does not help.

**Comment by llacb47** [comment]
I don't get any popups.

**Comment by mimmiepower** [comment]
> 
> 
> I don't get any popups.

Really? Could you try again? Sometimes you get lucky and no popups appear, but I would say that popups (maybe not the right term, but a new tab opens with ads or malvertising/scareware) appear more than 50% of the times when clicking on links. This is the only site, plus `torrentdownloads.me` that I just discovered which seems to be a clone, so I am not concerned about my computer being infected with malware.

After your comment I tried disabling all my "Custom" filter lists in uBlock as well as "My filters", tried a few different settings in uBlockO, tried deactivating Decentraleyes and Tampermonkey and I tried blocking everything that appeared in Privacy Badger, but the issue remains.

**Comment by spirillen** [comment]
Hmm I can't reproduce this, but I also added the first rule of OP to my own list

But here is what is blocked by Ublock Origin from my location

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +156 | \|\|uptimecdn.com^ | -- | torrent.tm | 3 | script | `https://uptimecdn.com/script/compatibility.js` |
| +156 | \|\|fbcdn2.com^$3p | -- | torrent.tm | 3 | script | `https://fbcdn2.com/script/compatibility.js` |
| +154 | \|\|histats.com^$3p | -- | torrent.tm | 3 | script | `https://s10.histats.com/js15_as.js` |
| +124 | \|\|uptimecdn.com^ | -- | torrent.tm | 3 | script | `https://uptimecdn.com/script/compatibility.js` |
| +124 | \|\|fbcdn2.com^$3p | -- | torrent.tm | 3 | script | `https://fbcdn2.com/script/compatibility.js` |
| +124 | \|\|histats.com^$3p | -- | torrent.tm | 3 | script | `https://s10.histats.com/js15_as.js` |
| +1 | \|\|uptimecdn.com^ | -- | torrent.tm | 3 | script | `https://uptimecdn.com/script/compatibility.js` |
| +1 | \|\|fbcdn2.com^$3p | -- | torrent.tm | 3 | script | `https://fbcdn2.com/script/compatibility.js` |
| +0 | \|\|histats.com^$3p | -- | torrent.tm | 3 | script | `https://s10.histats.com/js15_as.js` |
</details>

**Comment by peace2000** [comment]
I can reproduce. Search for something, such as "Ubuntu". Then click a search result open... At this point my browser opened a new tab. I can see this address `35.238.205.163` in my logger as well.

![kuva](https://user-images.githubusercontent.com/17256841/72558458-5da6d880-38ab-11ea-880e-903c77fbe601.png)

![kuva](https://user-images.githubusercontent.com/17256841/72558485-6c8d8b00-38ab-11ea-83fe-e4023529eed2.png)

**Comment by llacb47** [comment]
@okiehsch @mapx- can you test?

**Comment by mapx-** [comment]
working for me => `torrent.tm##+js(nowebrtc)`

**Comment by okiehsch** [comment]
I don't get any popups, I can see that the site uses webrtc.
![image](https://user-images.githubusercontent.com/16838044/72559657-9c399480-38a5-11ea-8987-c005e16a6f77.png)
