### ISSUE TITLE
Listing content missing on saltspringexchange.com

### ISSUE THREAD

**Issue by mica** [easylist/easylist#4664]
Photos and descriptions are missing from classified listings. There's also an anti adblock popup that would be nice to have removed. Here's an example page: https://saltspringexchange.com/list/beautiful-funky-mirror/

**Comment by ryanbr** [comment]
Won't be fixed in Easylist sorry

**Comment by mica** [comment]
> Won't be fixed in Easylist sorry

Ok, maybe not the popup, but what about the missing photos and descriptions?
