### ISSUE TITLE
Oracle SQL Developer pages blocked

### ISSUE THREAD

**Issue by krisrice** [easylist/easylist#4672]
The login pages for sqldeveloper are blocked due to multiple resources being block. We use a wildcard DNS

1 example is The following
`GET https://kustiudmg51w7mm-ad1.adb.eu-frankfurt-1.oraclecloudapps.com/ords/admin/jet/css/libs/oj/v6.2.0/alta/oj-alta-min.css net::ERR_BLOCKED_BY_CLIENT
`
The wildcard would be
`GET https://*.adb.*.oraclecloudapps.com/ords/admin/jet/css/libs/oj/v6.2.0/alta/oj-alta-min.css net::ERR_BLOCKED_BY_CLIENT
`

![image](https://user-images.githubusercontent.com/1444397/72075369-9a7a3a80-32c1-11ea-8d44-af8627fb329a.png)

Thanks for looking
-kris

**Comment by peace2000** [comment]
What is the exact link to log in?

**Comment by krisrice** [comment]
This only seems to be happening in the `eu-frankfurt-1` data center the one in ashburn works fine if that helps narrow it down.

Here's a URL for the broken login page `https://kustiudmg51w7mm-ad1.adb.eu-frankfurt-1.oraclecloudapps.com/ords/admin/_sdw/`

This one works in Ashburn
`https://dkedqbjwmvbga0l-dbtoolsash.adb.us-ashburn-1.oraclecloudapps.com/ords/klrice/_sdw/`

**Comment by peace2000** [comment]
`@@||oraclecloudapps.com/ords/admin/$domain=oraclecloudapps.com`
`@@||oraclecloudapps.com/$image,domain=oraclecloudapps.com`

These fix the issue.

The reason why the first url is blocked because part of it's name has "-ad1". That triggers the blocking filter.

**Comment by krisrice** [comment]
This domain is for Oracle Cloud customer application development using our tools ( I'm at oracle ) . However these tools allow a  customers to build an app on this domain and that app could have  ads but Oracle has no ads there in our base cloud tooling.
