### ISSUE TITLE
https://katcr.co/torrent/[redacted]/[redacted].html

### ISSUE THREAD

**Issue by mimmiepower** [easylist/easylist#4674]
### List the website(s) you're having issues:
Due to the possibility of pirated or malicious content I will not link directly to any torrent page. Just search for something or click a category and then click on a torrent page link. Here is the landing page:
`https://katcr.co/`

### What happens?

Under "Description" on torrent pages there is an animated loading symbol which never disappears and the torrent description does not show up.

### List Subscriptions you're using:

A lot but I have narrowed the issue down to Easylist.

### Your settings

- OS/version: Windows 10 64-bit
- Browser/version: Firefox 72.0.1 64-bit
- Adblock Extension/version: uBlock Origin 1.20.2

### Other details:

The problem disappears if you add an exclusion for the Easylist filter line:
`||katcr.co^$csp=script-src 'self' 'unsafe-inline'`

**Comment by peace2000** [comment]
https://katcr.co/torrent/79225/ubuntu-14-04-5-server-64-bit-lts.html Ubuntu should be ok :) And no one needs to download anything.

I confirm the issue.

**Comment by krystian3w** [comment]
I suppose no glitched with ABP (other implementation CPS... realy?)...
