### ISSUE TITLE
.club^$third-party,xmlhttprequest

### ISSUE THREAD

**Issue by krisdaniels** [easylist/easylist#468]
Hi,
  A couple of days ago my script that uses an API on a .club stopped working,
  turned out that easylist is blocking several TLD including .club..
  Is it possible to remove this and go for specific domains only ?
regards,
Kris

**Comment by krisdaniels** [comment]
see commit a51a989

**Comment by duboff** [comment]
We are seeing the same for `.xyz`

**Comment by bortevik** [comment]
+

**Comment by bortevik** [comment]
We have this issue again for `.xyz`
