### ISSUE TITLE
||facebook.com/widgets/like.php?href=$subdocument

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#4690]
### List the website(s) you're having issues:

`gok.gminadobrcz.pl`

### What happens?

No blocked like social button in footer:

![obraz](https://user-images.githubusercontent.com/35370833/72207716-e08af600-349b-11ea-8d69-d30729dd1948.png) |
--- |

### List Subscriptions you're using:

`EasyList`,
`Fanboy's Social Blocking List`

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 72 
- Adblock Extension/version: 3.7.0

### Other details:

```
||facebook.com/widgets/like.php?href=$subdocument
```

**Comment by Khrin** [comment]
I don't see this button, which is alread blocked by a different filter. Is still present for you?

**Comment by krystian3w** [comment]
Yes.

**Comment by krystian3w** [comment]
Also visible here:

`http://wklejto.pl/798966`

![obraz](https://user-images.githubusercontent.com/35370833/72210014-9f074480-34b5-11ea-9d65-6b6ac185cabe.png) |
--- |

**Comment by Khrin** [comment]
Still I can't see it, but added anyways.
