### ISSUE TITLE
wapking.site

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#47]
http://wapking.site/categorylist/3670/default/1.html

Ads showing on this mobiile site 

Filters That worked, Add them in EasyList

##a[href*=":80/key/"]
wapking.site##A[href^="http://bit.ly/"]

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/cca157c2dbecb1c2ab34351cb066e933f2bec3f9
