### ISSUE TITLE
infowars.com easylist false positive

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#470]
`https://www.infowars.com/contact/`

In the CONTACT OUR CONTRIBUTORS section, trying to click on an email icon next to a person's name will not display the text fields if EasyList is active.

**Comment by mapx-** [comment]
try
`infowars.com#@#div > span + * > [id][class] > :first-child > :first-child > *`

if does not work provide the list of the blocked elements on that page

**Comment by terrorist96** [comment]
That works. Should be merged.
Thanks.

**Comment by Khrin** [comment]
Fixed: https://github.com/easylist/easylist/commit/dcc619b8c3c4874c1bf1e9ac46d8d3bd52d76340
