### ISSUE TITLE
promo.* rule too broad

### ISSUE THREAD

**Issue by Kryniol** [easylist/easylist#4703]
### List the website(s) you're having issues:

All the Shopify stores using our app and embedding videos with iframe. Example:
`https://promo-prod.myshopify.com/products/yellow-sofa`

### What happens?

I'm a backend dev in a team which builds and maintains a Promo.com Shopify app, allowing users to create promotional videos of their Shopify store products. Recently we've introduced an iframe generator as a way to embed videos created by our users in their stores. After they create a video in the app they can copy an iframe HTML tag and manually paste it in their product pages. The iframe is being blocked by AdBlock due to the [rule](https://github.com/easylist/easylist/blob/2a91edb554d7ab208ca0ac2aa5195080456c46b2/easylist/easylist_general_block.txt#L7222):

`://promo.$third-party`

which for some reason blocks everything from any domain having the word "promo" in its name. Promo.com, though, is a perfectly legal startup providing tools for creating promotional videos and is not involved in any kind of unwanted advertising.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Ubuntu 19.04
- Browser/version: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- Adblock Extension/version: Adblock 4.1.0

### Other details:

It's already a 2nd time we're experiencing issues with releasing new features in our apps because of the EasyList rule.
The rule has been added in [this commit](https://github.com/easylist/easylist/commit/d070b277931be2f642fea92badd622cb0b022e4d) and it was not related to any of the promo.com sites.

**Comment by Kryniol** [comment]
The rule has been added in [this commit](https://github.com/easylist/easylist/commit/d070b277931be2f642fea92badd622cb0b022e4d) and it was not related to any of the promo.com sites.

**Comment by Khrin** [comment]
`https://promo.local/` is already abandoned?

**Comment by Kryniol** [comment]
`promo.local` points to our development environments, we don't mind it being blocked.

**Comment by Khrin** [comment]
So, what's incorrectly blocked then? Any real examples?

**Comment by Kryniol** [comment]
Requests, javascripts and iframes which come from `promo.com` are being blocked. Sorry if my description was not clear enough.

**Comment by Khrin** [comment]
Where is blocked? You posted here a showcase link, which is quite useless.

**Comment by Kryniol** [comment]
@Khrin I updated the issue, the link is correct now.
