### ISSUE TITLE
Bring.no / Posten.no - Mail tracking blocked (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#4710]
### Affected sites:
```
https://www.bring.no/
https://www.posten.no/
```

### Issue:
Mail tracking is blocked!

### Examples:
```
https://sporing.bring.no/sporing/?lang=en
https://sporing.posten.no/sporing/?lang=en
```

### Screenshots (from uBO's logger):
![filterissue-bring-posten-1](https://user-images.githubusercontent.com/9382674/72378586-fa357300-3711-11ea-86ca-c3800cb1a502.jpg)

![filterissue-bring-posten-2](https://user-images.githubusercontent.com/9382674/72378587-fa357300-3711-11ea-9a00-844dd789fb0b.jpg)

### Problem filter:
* EasyPrivacy

### Problem rule:
`/tracking/stat`

### Possible fix:
`@@/tracking/stat$domain=bring.no|posten.no`

### Note:
At the moment, only `bring.no` seems to be affected, if you're using Chromium.
In Pale Moon however, `posten.no` is affected in the same way (as shown in the screenshots above)!
Site updates might be rolled out incrementally, and could be both browser and/or region dependent, at the moment.
The problem only first occured today.

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.14 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
I am only able to replicate this on `sporing.bring.no`, and I'll add a `@@/tracking/static/$domain=bring.no` right away.

**Comment by peace2000** [comment]
@THEtomaso Can you give a test code to test with?

**Comment by THEtomaso** [comment]
> Can you give codes to test with?

No problem.
This is extremely easy to reproduce, as the whole serivices are blocked (blank/white pages)!:
```
https://sporing.bring.no/sporing/0000000000/
https://sporing.posten.no/sporing/0000000000/
```

**Comment by THEtomaso** [comment]
> I am only able to replicate this on `sporing.bring.no`

At the moment, only bring.no seems to be affected, if you're using Chromium.
In Pale Moon however, posten.no is affected in the same way!
Site updates might be rolled out incrementally.

**Comment by peace2000** [comment]
On Firefox, only `posten.no` is blocked. (I tested only the first link before I wrote my previous comment.) But anyway, Pale Moon is developed by Mozilla just like Firefox.

On Google Chrome, both work fine to me.

Strange. It seems that the site is blanked when the script for tracking is in this form:

`sporing.posten.no/tracking/static/js/xxxxxxxxxxxx.js`

But the site works when it's in this form:

`sporing.bring.no/tracking/precache-manifest.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.js`

So when `static` is there, it's blocked. When it's not, the site works. Strange that the usage of that script that has word "static" is based on browser. I think it's best to whitelist both addresses.

**Comment by THEtomaso** [comment]
There might be several factors at work here.
If they're indeed rolling out site updates incrementally, the issue might be both browser and/or region dependent.

Here are screenshots from uBO's logger (using Pale Moon from my location):

![filterissue-bring-posten-1](https://user-images.githubusercontent.com/9382674/72378586-fa357300-3711-11ea-86ca-c3800cb1a502.jpg)

![filterissue-bring-posten-2](https://user-images.githubusercontent.com/9382674/72378587-fa357300-3711-11ea-9a00-844dd789fb0b.jpg)

**Comment by THEtomaso** [comment]
For quick testing in Pale Moon, you can download the portable builds here:
```
For Win7+, 32-bit:
https://www.palemoon.org/download.php?mirror=eu&bits=32&type=portable
For Win7+, 64-bit:
https://www.palemoon.org/download.php?mirror=eu&bits=64&type=portable
```

**Comment by THEtomaso** [comment]
@peace2000:
Your PR only whitelist the scripts, what abot the stylesheets?

**Comment by peace2000** [comment]
I updated my request just a moment ago, noticed my mistake by myself also.
