### ISSUE TITLE
App updates don't download in Google Play Store

### ISSUE THREAD

**Issue by auipga** [easylist/easylist#4714]
### List the website(s) you're having issues:

Android Play Store (within app)

### What happens?

App updates wont download 

### List Subscriptions you're using:

reg_de -> https://easylist-downloads.adblockplus.org/easylistgermany+easylist.txt

### Your settings

- OS/version: (most likely) not relevant
- Browser/version: not applicable
- Adblock version: 3.5.5-2
- OpenWrt 18.06.2 r7676

### Other details:

Adblock runs on my OpenWrt router

**Comment by llacb47** [comment]
What? You can't use easylist on a router...

**Comment by krystian3w** [comment]
https://openwrt.org/docs/guide-user/services/ad-blocking

Possible generate hosts from:

`||example.domain^`

**Comment by monzta** [comment]
@auipga Can you whitelist domains? I had a report that blocking `gvt1.com` and mabe `gvt2.com` is causing this issue. Could you allow them and check again?

**Comment by auipga** [comment]
@monzta Whitelisting `gvt1.com` is the solution. Thank you so much!

**Comment by monzta** [comment]
@ryanbr Should we remove it?
