### ISSUE TITLE
https://www.shouldiremoveit.com/Web-Companion-128861-program.aspx

### ISSUE THREAD

**Issue by mimmiepower** [easylist/easylist#4718]
## List the website(s) you're having issues:

`https://www.shouldiremoveit.com/Web-Companion-128861-program.aspx`

### What happens?

Distracting "Sponsored topics" links to search query pages on `search.yahoo.com`. At a glance it looks a bit like it is a part of the website's UI, but it's just misleading sponsored links.

### List Subscriptions you're using:

The ones that are active on the page are:
Malvertising filter list by Disconnect 
Peter Lowe’s Ad and tracking server list
SWE: Frellwit's Swedish Filter
Dan Pollock’s hosts file 
EasyPrivacy 
Something redirects `https://ssl.google-analytics.com/ga.js` to a neutered source.

I also use Privacy Badger, Privacy Possum, Decentraleyes, HTTPS Everywhere, AdsBypasser and Anti-Adblock Killer.

### Your settings

If only I have this problem then I will dig deeper.

- OS/version: W10 64bit
- Browser/version: FF 72.0.1
- Adblock Extension/version: uBO

**Comment by llacb47** [comment]
https://github.com/reek/anti-adblock-killer has been dead for a while, you should remove it
