### ISSUE TITLE
uuu.cam [Incorrect Blocking]

### ISSUE THREAD

**Issue by zloyden** [easylist/easylist#4719]
### List the website(s) you're having issues:
`https://uuu.cam/chat/lucycums`

### What happens?
The site is broken
<details><summary>Screenshot:</summary>

</details><br/>

### List Subscriptions you're using:
EasyList

### Your settings

- OS/version: macOS 10.15.2
- Browser/version: Chrome 79
- Adblock Extension/version: AdBlock 4.1.0

**Comment by krystian3w** [comment]
`@@||chaturbate.com/affiliates/in/?tour=$subdocument,domain=uuu.cam`

**Comment by spirillen** [comment]
Hi @krystian3w That whitelist rule is fine in this specific case, but that would have to be rather long if you would like to whitelist any site relaying on `chaturbate.com` 

If you takes a quick peek on this list https://gitlab.com/my-privacy-dns/matrix/matrix/issues?scope=all&utf8=%E2%9C%93&state=all&label_name[]=NSFW%20Adult%20Material
You'll find that approximately 40 - 50% of these submission is replying on `chaturbate` with "iframe" pop-ups, banners etc. and they all comes from `//chaturbate.com/affiliates/`

So my best bid to help on this would properly be to whitelist something like the part of the link containing the `&room=`

Just a two cent from me.

PS: A link to a more narrow search string where the domain in question have been added insite the ticket
https://gitlab.com/my-privacy-dns/matrix/matrix/issues?scope=all&utf8=%E2%9C%93&state=all&label_name[]=NSFW%20Adult%20Material&search=chaturbate
