### ISSUE TITLE
easyprivacy causes accordions on passport country pages on travel.state.gov to not work

### ISSUE THREAD

**Issue by yoasif** [easylist/easylist#472]
Steps to reproduce:

1. Ensure that EasyPrivacy is enabled
2. Navigate to: https://travel.state.gov/content/passports/en/country/canada.html
3. Click any of "Expand All" or any of the accordions below it: "Embassies and Consulates", "Destination Description", etc. 

What happens:

Accordions do not expand. 

Expected result:

Accordions expand.

**Comment by Khrin** [comment]
Fixed: https://github.com/easylist/easylist/commit/2913899eb85092680a0e2e172cfebe5e7ef31b3c
Update EasyPrivacy in a few minutes.
