### ISSUE TITLE
All websockets in *.ru domains are blocked

### ISSUE THREAD

**Issue by reznikartem** [easylist/easylist#4721]
### List the website(s) you're having issues:

wss://operator.me-talk.ru/WS_cometListen 

### What happens?

All websockets in *.ru domains are blocking because of filter

/^(https?|wss?):\/\/([0-9a-z\-]+\.)?([0-9a-z\-]+\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|ovh|party|pro|pw|racing|review|rocks|ru|science|site|space|stream|tk|top|trade|webcam|win|xyz|zone)\/(.*)/$websocket,3p,domain=~file.pizza|~instant.io|~kiedywakacje.pl|~mellivora.pro|~mellivora.trade|~myinterview.com|~webtorrent.io

You can see it with regexp editor: https://regex101.com/r/HFtngn/1

### List Subscriptions you're using:

Version: 202001140707
Title: EasyPrivacy

### Your settings

- OS/version: Windows 10, version 10.0.18363
- Browser/version: Chrome 79.0.3945.117 
- Adblock Extension/version:  uBlock Origin 1.24.2

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/issues/4721
