### ISSUE TITLE
dell.com [Incorrect blocking]

### ISSUE THREAD

**Issue by slavaleleka** [easylist/easylist#4722]
### Issue URL (Incorrect Blocking)
[https://www.dell.com/it-it/shop/notebook-dell/sc/laptops](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.dell.com%2Fit-it%2Fshop%2Fnotebook-dell%2Fsc%2Flaptops)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/zb5AGZ7.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/QMFs0j2.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | AdGuard extension 3.3.8
Browser: | Chrome
Filters: | <b>Privacy:</b><br/> EasyPrivacy

**Comment by THEtomaso** [comment]
Summary:

### Problem filter:
* EasyPrivacy

### Problem rule:
`||afcs.dellcdn.com^$domain=dell.com`

### Possible fix:
Delete the problem rule!

### Temporary fix:
`||afcs.dellcdn.com^$domain=dell.com,badfilter`
