### ISSUE TITLE
nyafilmer.lol

### ISSUE THREAD

**Issue by Flameshocker** [easylist/easylist#4727]
### List the website(s) you're having issues:

**nyafilmer.lol**

### What happens?

- Well it got an anti-adblock that you can ser egen u get on the site

### List Subscriptions you're using:

https://prnt.sc/qpkc71

### Your settings

- OS/version:  Windows 10 - latest version
- Browser/version: Chrome - latest version
- Adblock Extension/version: Nano adblocker - latest version

**Comment by krystian3w** [comment]
No worth for EasyList, @mapx- / @jspenguin2017

**Comment by jspenguin2017** [comment]
@krystian3w See: https://github.com/NanoMeow/QuickReports/issues/2762
