### ISSUE TITLE
bing.com search

### ISSUE THREAD

**Issue by simoconfa** [easylist/easylist#4729]
### List the website(s) you're having issues:

`https://www.bing.com/search?q=something` 

### What happens?

Ads displayed when searching.

### List Subscriptions you're using:

EasyList + Easylist Italy

### Your settings

- OS/version: windows 10
- Browser/version:  FF latest
- Adblock Extension/version:  Ublock Origin latest

### Other details:

It should be fixed by firefox users with this filter:
`bing.com##^#b_results > .b_ad`
Don' t know if it is the correct place to report it, or it is a ublock origin only problem, in that case feel free to close this.

**Comment by llacb47** [comment]
`bing.com##.b_ad` works fine.

**Comment by simoconfa** [comment]
> 
> 
> `bing.com##.b_ad` works fine.

not working with ublock origin, for more explanation see this thread:
`https://www.reddit.com/r/uBlockOrigin/comments/e6mt2z/block_bing_ads/`

**Comment by krystian3w** [comment]
EasyList no use html filtering:

`domain.example##^uBO-HTML-FILTERING`
`domain.example$$AdGuard-HTML-FILTERING`

https://adblockplus.org/blog/filtering-html-code-in-adblock-plus - They tried 11 years ago, but something didn't work out...

**Comment by llacb47** [comment]
> > `bing.com##.b_ad` works fine.
> 
> not working with ublock origin, for more explanation see this thread:
> `https://www.reddit.com/r/uBlockOrigin/comments/e6mt2z/block_bing_ads/`
> Edit: With UBO It works only on right side ads, not with ads between searched results.

Nope, in uBO works fine for me... ?

**Comment by ryanbr** [comment]
Not much we can do, but `##.b_ad` seems to be okay.
