### ISSUE TITLE
EasyList is Broken

### ISSUE THREAD

**Issue by LucianAndries** [easylist/easylist#4732]
Hello.

From 24 hours ago, or more, every EasyList is broken. It blocks Disqus on some websites.
I have done all I could to make the ad blocker extension, to bypass/exclude Disqus from its filter lists, but it just DOES NOT WORK. I don't know why...  :cry:  :cry: 

I want to tell that I am new at working with ad blocks. I'm currently using uBlock Origin btw.

I reported this here, because I see this is where the "EasyList" originates from?

So, like I said, ALL the filter lists that have "EasyList" in the name, are broken. It does not work just by disabling 1 specifically, I have to disable all of them. :|
The lists are:
- EasyList;
- EasyList without element hiding rules;
- Fanboy+Easylist-Merged Ultimate List.

Cleared site cookies, updated lists, nothing. It's not like it loads for a second then goes away, it doesn't want to load at all.
How I figure it out? By disabling each filter, one by one.

Link to one of the websites having the issue:
https://aniwatcher.com/fate-grand-order-zettai-majuu-sensen-babylonia-episode-14

- OS/version: Windows 10 64bit
- Browser/version: Chrome v79.0.3945.130 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin v1.24.2

I hope it will get fixed, as I'm one of those that actually like Disqus...

Thank you!

**Comment by LucianAndries** [comment]
Seems adding these 2 code lines, fixes the issue.

My Filters:
@@||disqus.com^$script,domain=aniwatcher.com
@@||disqus.com/embed.js$script

But, while this fixed Disqus, I think the filters should still be rechecked and updated, coz who knows what other important stuff they might be blocking...

**Comment by peace2000** [comment]
These kind of things should be fixed for wider audience and for many domains, not just for one ;)

I'll make a pull req...
