### ISSUE TITLE
Twitter ads

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#4733]
I was wondering what would be a policy in how to implement twitter.com ads blocking, as Twitter is international site but it's translated into many languages.

Blocking Twitter ads is not that easy as they use element name randomizing. Also those ads don't appear on every page, they seemingly appear randomly. It makes this harder.

Here is one sample I managed to "grab" (edit, my rule is partly cut out in the screenshot):

![kuva](https://user-images.githubusercontent.com/17256841/72679485-4557d900-3ab8-11ea-8abc-c57da48abddd.png)

The blocking rule I made, was this:

`twitter.com##div#react-root > div > div > div > main > div > div > div > div > div > div > div > div > div > section > div > div > div > div > div > div:has-text(Mainostettu twiitti)` ("Mainostettu twiitti" means "Advertised tweet")

I don't know if there is a better working way to hide those ad tweets than to use has-text syntax (or :-abp-contains).

But anyway, if this is the case, should those ads be blocked by the main Easylist or it's language based variants? It might be a tough job to write that rule to each and every language variant. That's why I was wondering that should that be done by the main list or it's language based variants.

**Comment by monzta** [comment]
There is a rule for Twitter already covering a bunch of languages with :-abp-contains. Probably yours isn't covered yet.

**Comment by peace2000** [comment]
> 
> 
> There is a rule for Twitter already covering a bunch of languages with :-abp-contains. Probably yours isn't covered yet.

Oh. Yes it seems so.

I'll make a pull req then. I assumed that all languages would be covered if blocking rules are made. But anyway, maybe sometimes it's better that people from different countries active by themselves. :D
