### ISSUE TITLE
EasyPrivacy blocking some games in airmash.online

### ISSUE THREAD

**Issue by BlackCrawler** [easylist/easylist#4736]
### List the website(s) you're having issues:
wss://lags.win/ctf

### What happens?

Go to https://airmash.online/
Choose region Europe and Game - `CTF #1`
Connection to the game endpoint wss://lags.win/ctf will be blocked by this rule:
https://github.com/easylist/easylist/blob/145a038833079e883fc74079ce27d5ffe7196765/easyprivacy/easyprivacy_trackingservers.txt#L2541

### List Subscriptions you're using:

Version: 202001140707
Title: EasyPrivacy

### Your settings

OS/version: Windows 10, version 10.0.18363
Browser/version: Chrome 79.0.3945.117
Adblock Extension/version: uBlock Origin 1.24.2

**Comment by peace2000** [comment]
Clearly not an adserver :D made a pull req to fix this.

**Comment by BlackCrawler** [comment]
Thank you, for a pull req. We have another clients for this game, like https://starma.sh . Maybe its better to whitelist the game server `wss://lags.win/ctf`  not urls to frontends?

**Comment by peace2000** [comment]
That could be the best option.

**Comment by BlackCrawler** [comment]
> How many frontends you have?

There are currently the two main clients https://starma.sh/ https://airmash.online/. Also there are bunch of test frontends: https://spatiebot.github.io/ (this url will be changed in the future) https://test.airmash.online/ https://starmash.test.airmash.online/

> Is is enough to whitelist just lags.win/ctf or should lags.win be whitelisted?

I think its enough.

**Comment by peace2000** [comment]
All right, new pull req made to whitelist `lags.win/ctf`. Now let's wait for the authors to approve it.

**Comment by THEtomaso** [comment]
@LanikSJ:

The one at `starma.sh` is also prevented from loading because of the following filter (found in '**Crypto Mining Domains Filter List**' / '**Ad Domains Filter List**'):
`||github.io^$third-party,xmlhttprequest,domain=~facebook.com|~github.com|~github.io|~tumblr.com|~wottactic.com`

Posible fix:
```
- ||github.io^$third-party,xmlhttprequest,domain=~facebook.com|~github.com|~github.io|~tumblr.com|~wottactic.com
+ ||github.io^$third-party,xmlhttprequest,domain=~facebook.com|~github.com|~github.io|~starma.sh|~tumblr.com|~wottactic.com
```

**Comment by BlackCrawler** [comment]
Hi, I still have this issue. I updated filters ( EasyPrivacy Version: 202001240640 )
Go to https://airmash.online/ or  https://starma.sh/ 
Choose region Europe and Game - CTF #1
According to uBlock `wss://lags.win/ctf` is blocked by 

```

/^(https?|wss?):\/\/([0-9a-z\-]+\.)?([0-9a-z\-]+\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|ovh|party|pro|pw|racing|review|rocks|ru|science|site|space|stream|tk|top|trade|webcam|win|xyz|zone)\/(.*)/$websocket,3p,domain=~file.pizza|~instant.io|~kiedywakacje.pl|~lags.win|~me-talk.ru|~mellivora.pro|~mellivora.trade|~myinterview.com|~webtorrent.io
``` 

If I add this rule `@@||lags.win/ctf$websocket`  (#4740) then everything works.
