### ISSUE TITLE
.xyz^$third-party,xmlhttprequest

### ISSUE THREAD

**Issue by duboff** [easylist/easylist#474]
This rule https://github.com/easylist/easylist/blob/master/easylist/easylist_general_block.txt#L7120 seems to be unnecessarily strict, blocking all AJAX requests to any domain in the `.xyz` TLD.

This was introduced in a51a989a8159756333b8d1eb8b5ba65f257bb4c8.

We have a domain on `.xyz` and so do a lot of reputable organizations. I would think the rule should be removed altogether.

**Comment by Gollam** [comment]
I'm having the same issue.

**Comment by Khrin** [comment]
What's the affected domain? Can you give an example page?

**Comment by duboff** [comment]
Hi, this has been resolved in 33e14bdc5f0a20e28a24e9e4a46f160908d4e371
