### ISSUE TITLE
easylist cookie prevent country selecting on newegg

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#4743]
### List the website(s) you're having issues:
https://www.newegg.com/sparkle-power-fsp400-60ghs-400w/p/N82E16817103113
Click on "us" on the top right

### What happens?
Nothing happens.
A selection of country should display

### List Subscriptions you're using:
easylist cookie prevent the window to show, while disabling it, the window works

### Your settings

- OS/version: windows10
- Browser/version: firefox
- Adblock Extension/version: ublock origin

**Comment by krystian3w** [comment]
`newegg.com#@#.centerPopup`
`newegg.com#@##popup_overlay`
