### ISSUE TITLE
kab.co.il

### ISSUE THREAD

**Issue by alexmbb** [easylist/easylist#475]
We have a jwplayer on our website that loads hls stream from a different domain of ours.
http://edge1.il.kab.tv/

I  see it's being blocked by this filter:
.stream^$third-party,xmlhttprequest

in addition, we have a few other sites besides kab.co.il that work in the same way.
moreover, we have "cdn" like servers besides edge1.il all are subdomains of kab.tv

What can we do to solve it?

Thanks

**Comment by mapx-** [comment]
could you update (again) easylist and test again ?

**Comment by alexmbb** [comment]
Works ok now

Thanks a lot
