### ISSUE TITLE
cp.rackspace.com

### ISSUE THREAD

**Issue by stautrooslu** [easylist/easylist#4750]
### List the website(s) you're having issues:

(When logged-in:)
```
https://cp.rackspace.com/
https://cp.rackspace.com/EmailHosting/Mail/Mailboxes/List.aspx
```

### What happens?

- The account dropdown at the upper right does not open when you click it (e.g., can't log-out).
- Mailboxes are not viewable or editable (see screen capture below)

### List Subscriptions you're using:

This issue occurs with all subscriptions turned off except EasyPrivacy. The issue no longer applies if EasyPrivacy is disabled.

### Your settings

- OS/version: Fedora/30
- Browser/version: Firefox/72
- Adblock Extension/version: ABP/3.7

### Other details:

Here's what shows up in 'Adblock Plus' panel in developer tools (censored part that looks like it could be a session id):
```
https://cp.rackspace.com/javascript/services/analytics.js?v=________________________________________
cp.rackspace.com

SCRIPT

/analytics.js?
EasyPrivacy
```
![screen-capture](https://user-images.githubusercontent.com/60080975/72692710-6ee62400-3afb-11ea-8607-6c641bd24dd4.png)

**Comment by Khrin** [comment]
@stautrooslu Hi, please can confirm you if after updating EasyPrivacy the issue is resolved (or not?).

**Comment by stautrooslu** [comment]
@Khrin confirmed fixed - thanks! :-)
