### ISSUE TITLE
zippyshare.com

### ISSUE THREAD

**Issue by Barticf** [easylist/easylist#4753]
### List the website(s) you're having issues:

`https://www.zippyshare.com/`

### What happens?

Browse button not working

### List Subscriptions you're using:

EasyList + AdGuard

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 72
- Adblock Extension/version: uBlock 1.24

**Comment by krystian3w** [comment]
Unable reproduce on Windows 7 (old and modern uploader).

Maybe other filters list break site.

**Comment by Barticf** [comment]
@krystian3w now it's ok
