### ISSUE TITLE
Nginx/Apache Pagespeed URLs blocked

### ISSUE THREAD

**Issue by muralikg** [easylist/easylist#4768]
### List the website(s) you're having issues:
smergers.com

Our site Javascript is blocked
```https://www.smergers.com/static/js/smergers_all.min.js,qrev=b,27d452a180ab,27.pagespeed.ce._jhzbKIdXp.js```
### What happens?
All websites which use nginx pagespeed module(run time webpage optimization) will be facing this issue.
The urls are generated by nginx pagespeed on the fly and are of the pattern
`filename.pagespeed.<2letter-prefix>.<hash-of-file>.(css|js|jpeg)`

In our case the website javascript is blocked and breaks our site.

### List Subscriptions you're using:
EasyPrivacy​​​​​

### Your settings

- OS/version:  Ubuntu 18.04
- Browser/version: Chrome / 79
- Adblock Extension/version: uBlock Origin 1.24.2

### Other details:

Rule which is causing the issue is 
```
.pagespeed.ce.
```

![image](https://user-images.githubusercontent.com/795230/72822858-cff72e80-3c98-11ea-97c9-cee430255b90.png)

![image](https://user-images.githubusercontent.com/795230/72822972-fb7a1900-3c98-11ea-89d5-1064bb262880.png)

**Comment by muralikg** [comment]
This is the [commit](https://github.com/easylist/easylist/commit/9c13d89b24738854c2b7f0e667114c462c9529d4#diff-6b54c84f883288b1582a40f4174525e0) which seems to have introduced the new rule.

Can you please add a much more specific rule as pagespeed is a very popular nginx/apache module used by a lot of websites.

**Comment by nisaoirse** [comment]
Worst ... commit ... ever

**Comment by TomasRiker** [comment]
Please undo this as quickly as possible. It's breaking tens, hundreds of thousands of innocent websites.

**Comment by poldixd** [comment]
Same issue here... Nginx Pagespeed generates a optimized css file with `pagespeed.ce`. The CSS File is now blocked:

```
<link href="/css/app.css,qid=4c564221eb69d6871ebd.pagespeed.ce.TFZCIetp1o.css" rel="stylesheet">
```

This commit destroyed the internet 😐

**Comment by llacb47** [comment]
@ryanbr @khrin @monzta

**Comment by mapx-** [comment]
for uBo
https://github.com/uBlockOrigin/uAssets/commit/78675df1a38c25690295bc305938061f99248c83

**Comment by muralikg** [comment]
Updating uBO filters fixed the issue for me. But will leave this open till  `easyprivacy_general.txt` list is fixed as that could be used by other ad block softwares or browsers.

**Comment by muralikg** [comment]
I see the rule was [removed from easyprivacy](https://github.com/easylist/easylist/commit/3823574b77ef23b4ec0aa7647d7122a1637d1019#diff-6b54c84f883288b1582a40f4174525e0). Thanks @ryanbr
