### ISSUE TITLE
 TimParty Incorrect Blocking [EasyPrivacy]

### ISSUE THREAD

**Issue by superlex** [easylist/easylist#4779]
### List the website(s) you're having issues:

`https://www.timparty.tim.it/`

### What happens?

Blank (white) page.

### List Subscriptions you're using:

- EasyList
- EasyPrivacy
- EasyList Italy

### Your settings

- OS/version: macOS
- Browser/version: Firefox
- Adblock Extension/version: uBlock0 - AdGuard Ext

### Problematic rule: 
`||adobedtm.com^$3p`

### Possible fix:
`@@||assets.adobedtm.com^$script,domain=timparty.tim.it`
or edit the rule
`@@||adobedtm.com/launch-$script`
as (e.g.) 
`@@||adobedtm.com^*/launch-$script`

**Comment by spirillen** [comment]
Abetter fix would be to tell the webmaster they have broken code in there player..... `adobedtm.com` is all about tracking and data harvesting to draw a personal identifying profile about the $user for brainwashing

**Comment by Khrin** [comment]
@superlex Grazie mille.

**Comment by superlex** [comment]
@Khrin 
You're welcome :)

@spirillen 
I agree with you but unfortunately there are a lot of website that don't work if it is blocked. In fact, for example, it's whitelisted in [StevenBlack's hosts](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts).

**Comment by spirillen** [comment]
@superlex I know...

But to clarify for others, this is my stand on that https://gitlab.com/my-privacy-dns/matrix/matrix/tree/master#faq

>  it's whitelisted in StevenBlack's hosts.
Exactly why it have been taken out of the equation https://gitlab.com/my-privacy-dns/external-sources/hosts-sources/commit/3f4f1dd2b110f89a753fac54c843455b8d1e0097#cdbf48ebcd9c0ed350517ad88f8f2494c13b5491_37_35
