### ISSUE TITLE
EasyPrivacy blocked Dominos.com pizza - make exception/whitelist

### ISSUE THREAD

**Issue by darkmorpher** [easylist/easylist#479]
https://easylist-downloads.adblockplus.org/easyprivacy.txt

`omtrdc.net^$third-party` rule blocked script loading from `https://dominos.tt.omtrdc.net/m2/dominos/mbox/*`, which broke page loading on **[Dominos.com/en](https://www.dominos.com/en/)** Pizza site, and displays a blank page.
Make an exception for that domain.

**Comment by SMed79** [comment]
`https://www.dominos.com/` seems to load fine here !!
