### ISSUE TITLE
Empty box next to the movie on youtube.

### ISSUE THREAD

**Issue by RikoDEV** [easylist/easylist#481]
For a few weeks I see an empty box after the ad next to the movie on youtube, I use the new black youtube look. The empty box redirects to googleads.g.doubleclick.net

Browser: Vivaldi 1.11.904.3

![screen](https://user-images.githubusercontent.com/18230443/28309559-07a98610-6baa-11e7-863b-67e7e2807546.PNG)

![ss3](https://user-images.githubusercontent.com/18230443/28309693-6c50c3f8-6baa-11e7-9a95-ae998aba8efc.PNG)

**Comment by LanikSJ** [comment]
Try: `youtube.com#google_image_div`
