### ISSUE TITLE
https://thedesigninspiration.com/

### ISSUE THREAD

**Issue by M4xBill** [easylist/easylist#4814]
### List the website(s) you're having issues:

https://thedesigninspiration.com/

### What happens?

Hi, we saw that one of your rules is currently blocking access to our Jquery library, hosted through cdn.thedesigninspiration.com.

Could you adjust the following rule to let us access our subdomain?

Regards,

Max

### Other details:
	||thedesigninspiration.com^$csp=script-src 'self' *.leadpages.net *.gstatic.com *.google.com *.googleapis.com *.playwire.com *.facebook.com *.bootstrapcdn.com *.twitter.com *.spot.im

**Comment by spirillen** [comment]
That rule would open up for all the cyber crime trackers....

**Comment by M4xBill** [comment]
Hi,
Could you please add a fix to our issue ? 

Regards, 

Max

**Comment by ryanbr** [comment]
Okay @M4xBill filter has been removed. Was added because Yavli, if we get reports of any revolving adservers it'll be re-added.
