### ISSUE TITLE
the filter /perimeterx/ is too broad

### ISSUE THREAD

**Issue by safruti** [easylist/easylist#4819]
This filter in the privacy list is blocking our images that we serve on our site (https://www.perimeterx.com).
we are using cloudinary to host our images, and it is hosted on the following path: https://res.cloudinary.com/perimeterx/, but because of this filter the images don't load.
can you remove the filter, or narrow it to cover the specific sites the original PR came from?
our customers don't use this folder on their end to serve the PerimeterX product/javascript. 

https://github.com/easylist/easylist/blob/169895b4b2bff2c33c8781689ae58702dfda60ea/easyprivacy/easyprivacy_general.txt#L3020

**Comment by THEtomaso** [comment]
`@@||cloudinary.com/perimeterx/$image,domain=perimeterx.com`

**Comment by safruti** [comment]
that should work. when can this be pushed live? our site is currently broken for users.

**Comment by llacb47** [comment]
THEtomaso is a community member, they have no control over the easylist repo.
