### ISSUE TITLE
whois

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#482]
`https://who.is/`
`https://who.is/whois/google.com`

name.com ad

**Comment by LanikSJ** [comment]
`who.is##.container > .row:nth-of-type(5) > .col-md-4`

Will break if they decide to rename their DIVs.

**Comment by terrorist96** [comment]
`||who.is/images/Prologue-WhoIs.jpg` needed to block the one on the homepage.
`##.col-md-4 > center:nth-of-type(1)` result page, top ad
`##center:nth-of-type(2)` result page, bottom ad

`who.is##.container > .row:nth-of-type(5) > .col-md-4` this will block too much (site status and suggested domain boxes).

**Comment by LanikSJ** [comment]
`who.is##center:nth-of-type(2)` for the link to name.com.

**Comment by terrorist96** [comment]
@Khrin the ad is still there.
