### ISSUE TITLE
RemoveURL

### ISSUE THREAD

**Issue by edentc** [easylist/easylist#4837]
### What happens?
@@||imp.appledaily.com/js/nxm_tr_v20s.js
Please delete this entry to avoid unnecessary errors.

### List Subscriptions you're using:
EasyPrivacy

### Your settings

- OS/version: android 9
- Browser/version: adblock browser 
- Adblock Extension/version: 2.1.0

**Comment by peace2000** [comment]
What erros? Where?

**Comment by edentc** [comment]
Excuse me ...
What was the reason you originally added this?

**Comment by peace2000** [comment]
I noticed now (didn't look carefully at first) that your rule is a whitelist rule so how it could cause issues?

I'm not one of the owners of this list but I can say on their behalf that rules won't be removed without a clear reason. You have not yet provided any valid reason why it should be removed.

(I don't know why that list is there).

**Comment by THEtomaso** [comment]
> I don't know why that rule is there

Origin:
https://github.com/easylist/easylist/issues/3632/

Could probably be changed to this:
`@@||imp.appledaily.com/js/nxm_tr_v20s.js$~third-party`

**Comment by edentc** [comment]
@ryanbr @Khrin

Since he still has the reason for the existence of this entry, I wonder if it can be directly replaced by this entry?
||imp.appledaily.com^

**Comment by THEtomaso** [comment]
That would definitely break the page, which the whitelisting was supposed to fix, in the first place.
Although the page looks nasty to me (most Asian sites does, to be honest), it seems to be somewhat popular.

**Comment by peace2000** [comment]
For non-chinese people it might be very hard to understand what should be blocked and what should not. That's why there are supplementary lists. There is a Easylist Chine listed here: https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html

Here is their forum: http://abpchina.org/forum/forum.php

**Comment by ryanbr** [comment]
It came from this request; https://github.com/easylist/easylist/issues/3632

I would recommend @edentc read through the request first ^

**Comment by edentc** [comment]
@ryanbr 
Hello there:

Could you please remove these two entries directly?
In order to save all problems and troubles.
Sorry! Because his website has been revised too many times, it is very difficult to cope.
@@||imp.appledaily.com/js/nxm_tr_v20s.js
||imp.appledaily.com^

**Comment by ryanbr** [comment]
What are you trying to resolve, what is the issue?

**Comment by edentc** [comment]
@ryanbr 
I want to know what caused your seal?

**Comment by ryanbr** [comment]
If there is no details about this issue, I'll close this ticket.

**Comment by edentc** [comment]
Hi,
@ryanbr 
Can you please add these?
Compare to # 3632.
Because they are all of the same nature and problem.

@@||imp.appledaily.com/nxtu_v20.html
@@||imp.appledaily.com/nxtu_v20_dev.html
@@||imp.appledaily.com/js/nxm_tr_v20s_dev.js

@@||dev-imp.appledaily.com/js/nxm_tr_v20s.js
@@||dev-imp.appledaily.com/nxtu_v20.html
@@||dev-imp.appledaily.com/nxtu_v20_dev.html

@@||imp.appledaily.com/js/nxm_tr_v20s.min.js
@@||dev-imp.appledaily.com/js/nxm_tr_v20s.min.js

**Comment by THEtomaso** [comment]
So, first you want to have a whitelisting removed, but now you want to keep it, and have a bunch of new ones added as well?
Listen to what ryanbr told you, and explain the excact nature of the issue(s) which needs to be fixed, so that he's able to understand WHY those rules needs to be added!

**Comment by edentc** [comment]
@THEtomaso 
ryanbr does not seem to be willing to answer the reason positively,
So I will sort out other relevant places to avoid the same problems as before.

**Comment by ryanbr** [comment]
I've removed the filter, your request wasn't helpful @edentc . If you look at other requests, we'll have examples websites and exact issues what is causing it. So I just removed it. Not worth trying to go through this again.
