### ISSUE TITLE
Connection to server blocked, airmash.online, starma.sh

### ISSUE THREAD

**Issue by BlackCrawler** [easylist/easylist#4844]
### List the website(s) you're having issues:
airmash.online, starma.sh
websocket server that is blocked: wss://lags.win/ctf

### What happens?

Go to https://airmash.online/ or  https://starma.sh/ 
Choose region Europe and Game - CTF #1
According to uBlock `wss://lags.win/ctf` is blocked by this rule

```
/^(https?|wss?):\/\/([0-9a-z\-]+\.)?([0-9a-z\-]+\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|ovh|party|pro|pw|racing|review|rocks|ru|science|site|space|stream|tk|top|trade|webcam|win|xyz|zone)\/(.*)/$websocket,3p,domain=~file.pizza|~instant.io|~kiedywakacje.pl|~lags.win|~me-talk.ru|~mellivora.pro|~mellivora.trade|~myinterview.com|~webtorrent.io
``` 

If I add this rule `@@||lags.win/ctf$websocket`  (#4740) then everything works.
The commit 3f61f37ec94757c33099192dbd0360241786d0cd didn't solve the issue.

### List Subscriptions you're using:

Version: 202001301822
Title: EasyPrivacy

### Your settings

OS/version: Windows 10, version 10.0.18363
Browser/version: Chrome 79.0.3945.117
Adblock Extension/version: uBlock Origin 1.24.2

**Comment by peace2000** [comment]
Did you update your lists?

That is blocked also by Nocoin filterlist. Easyprivacy doesn't block it anymore, now it's the Nocoin filterlist.

This rule:
`@@||lags.win/ctf$websocket`

is a whitelist rule that is applied what ever filterlist is blocking it.

This commit https://github.com/easylist/easylist/commit/3f61f37ec94757c33099192dbd0360241786d0cd fixes the issue, caused by Easyprivacy, but not by Nocoin filterlist.

There could be other lists as well that block it but at least for me, Nocoin is to blame.

**Comment by peace2000** [comment]
Also US server needs whitelisting... This was blocked when tried Capture the flag on the US server:

`wss://www.airmash.xyz/ctf1`

**Comment by ryanbr** [comment]
Both sites seems to be fixed? (or they just changed the domains..) can you confirm @peace2000 @BlackCrawler

**Comment by peace2000** [comment]
It's still blocked, not fixed. I can see the intended whitelist rule there but it doesn't work.

**Comment by peace2000** [comment]
This rule ~lags.win is the intended fix rule but it doesn't have affect.

**Comment by peace2000** [comment]
Took a new screenshot, that shows how it's still blocked even though there is an intended fix made:

![kuva](https://user-images.githubusercontent.com/17256841/75091579-8f305500-5577-11ea-8ef3-4fa28e3d6ec7.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/97c48a529d353a966b96c54c687c395bdb052694

**Comment by peace2000** [comment]
> 
> 
> [97c48a5](https://github.com/easylist/easylist/commit/97c48a529d353a966b96c54c687c395bdb052694)

That commit will definetely fix this. :D
