### ISSUE TITLE
Streamplay.to 

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#4853]
@ryanbr 

### List the website(s) you're having issues:

URL=

`steamplay.me/2zxmb7cg665v`

### What happens?

3rd party tracking,3rd party xhr's, images.....
Revolving ad servers

### List Subscriptions you're using:

Ublock origin default lists

### Your settings

- OS/version: win 10
- Browser/version: opera browser stable
- Adblock Extension/version: ublock origin 1.24.2

### Other details:

Site changes domain frequently. ....
You can find all video player changes at `megashare.li`

**Comment by ryanbr** [comment]
Yeah, been aware of this. I'll close this ticket, but its on going unfortantely.

**Comment by ghajini** [comment]
`https://streamplay.to/7izs4p10yqwn`

@ryanbr 
This filter from easylist
 
`||streamplay.*/jquery-`

Prevents video from loading
