### ISSUE TITLE
vidtodo.com(main domain)

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#4854]
@ryanbr 

### List the website(s) you're having issues:

URL=

`vidtopo.com/5d1bnyd7viqb`

### What happens?

3rd party tracking,3rd party xhr's, images.....
Revolving ad servers

### List Subscriptions you're using:

Ublock origin default lists

### Your settings

- OS/version: win 10
- Browser/version: opera browser stable
- Adblock Extension/version: ublock origin 1.24.2

### Other details:

Site changes domain frequently. ....
You can find all video player changes at `megashare.li`

**Comment by ghajini** [comment]
New domains
`https://viddoto.com/embed-5vywop2palqd.html`
`https://vidtoup.com/5vywop2palqd`

Popup ads

**Comment by Khrin** [comment]
Looks like all domains are dead now..

**Comment by llacb47** [comment]
@Khrin working: `https://vldtodo.com/embed-pnsxivizuusn.html`

check here for a list of domains: `https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L747`

**Comment by Khrin** [comment]
@llacb47 I've not seen a single domain from there still working. A few are parked, other simply are unable to connect.

**Comment by llacb47** [comment]
I linked a working player above.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/1f30920512332ab920382c14235177cef2712f9a

But it was the only one working.

**Comment by ghajini** [comment]
@Khrin 
Popup ads
Past Domains now active `https://viddoto.com/jn6fu90lexu0`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/c5c2cceada2eb49b11f41e4f50b98fdb8a430620

**Comment by ghajini** [comment]
`https://viitodo.com/ce2ooyncfh6p`
Popup ads

**Comment by ghajini** [comment]
`vidtood.com/sz46bp8ph1vn`
Popup ads

Filter=

`||d36zfztxfflmqo.cloudfront.net^`
