### ISSUE TITLE
mako.co.il

### ISSUE THREAD

**Issue by meirroth** [easylist/easylist#4855]
### List the website(s) you're having issues:
`https://www.mako.co.il/` (Hebrew site)

### What happens?
Cookies consent message banner showing

### List Subscriptions you're using:

All the lists in uBlock Origin are active
### Your settings

- OS/version: W10 64bit
- Browser/version: FF 72.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.24.2

### Other details:

[screenshot](https://cdn3.imggmi.com/uploads/2020/2/2/b27d54cb8556aa4e91dea9f0ac85f3b2-full.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/79d65ed37c5adb19cd8c6a138a69794e418ca651
