### ISSUE TITLE
tabletka.by [Incorrect Blocking]

### ISSUE THREAD

**Issue by zloyden** [easylist/easylist#4857]
### List the website(s) you're having issues:
`tabletka.by `

### What happens?
The site is broken (images) by this rule `/reclame/*$domain=~github.com`
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/73658042-94029700-46a4-11ea-927f-330a7c0b2d1e.png)
</details><br/>

### List Subscriptions you're using:
EasyList

### Your settings

- OS/version: macOS 10.15.2
- Browser/version: Chrome 79
- Adblock Extension/version: AdBlock 4.4.0

**Comment by ryanbr** [comment]
Not seeing any breakage currently, I see some ads being blocked because of this filter.. But the site seems to be working well.

**Comment by zloyden** [comment]
I guess they changed their paths to images, now it's fine. You can close the task.
