### ISSUE TITLE
cad-comic.com

### ISSUE THREAD

**Issue by DawEdhel** [easylist/easylist#4858]
### List the website(s) you're having issues:

`https://cad-comic.com/comic/analog-and-d-pad-06-24/`
`https://cad-comic.com/comic/*`

### What happens?

Local disqus panel buttons at the bottom do not working, such as read more, sort by.

### List Subscriptions you're using:

Version: 202002021426
! Title: EasyPrivacy
! Last modified: 02 Feb 2020 14:26 UTC

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome/Version 79.0.3945.130, Firefox/72.0.2
- Adblock Extension/version: uBlock Origin/1.24.2

### Other details:

Logger URL: `https://cad-comic.com/wp-content/plugins/wpdiscuz/assets/third-party/wpdcookiejs/customcookie.x76493.js?ver=5.3.2`, which is currently blocked by next rule `/wpdcookiejs/*`. Making static filter rule in uBlock to allow the url fixes the problem.

Maybe its worth adding custom rule for that particular plugin url,
since there are several examples included in the list which share same behaviour.

**Comment by ryanbr** [comment]
Filter is removed.
