### ISSUE TITLE
New akamai urls?

### ISSUE THREAD

**Issue by birdsarah** [easylist/easylist#4862]
From #3936 comment from @llacb47

@ryanbr @Khrin they changed their urls again, see https://publicwww.com/websites/%22%27_setAu%27%2C+%27%2Fpublic%2F%22/

Maybe regex: `/\/public\/([A-Za-z0-9]){29}$/$script`

**Comment by ryanbr** [comment]
I've only seen  `/akam/11/*`  is there more @birdsarah

**Comment by llacb47** [comment]
Did you look at the publicwww search? That is akamai!

**Comment by ryanbr** [comment]
I did, no url's other than /akam/11/*

**Comment by krystian3w** [comment]
Regex can slow down ABP / AdBlock (Beta Fish inc.), maybe better report to AdGuard and uAssets only?

**Comment by ryanbr** [comment]
regex in general will be slower, if we come across more, then we'll just add it.
