### ISSUE TITLE
gigaho.com

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#4863]
### List the website(s) you're having issues:

`https://www.gigaho.com/2018/11/a00107.html`

### What happens?

Blank articles

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10 Pro
- Browser/version: Firefox 72
- Adblock Extension/version: uBO 1.24.2 

### Other details:

```
gigaho.com#@#.pub_300x250
gigaho.com#@#.adsbygoogle
gigaho.com#@#.blog-ad
gigaho.com#@#.blog_ad
gigaho.com#@#.text-ad-links
gigaho.com#@#.text-ads
gigaho.com#@#.text_ads
gigaho.com#@#.text_ad
gigaho.com#@#.textAd
gigaho.com#@#.text-ad
gigaho.com#@#.pub_728x90
gigaho.com#@#.pub_300x250m
```

**Comment by mapx-** [comment]
`@@||gigaho.com^$generichide`
