### ISSUE TITLE
solution for businessinsider.com

### ISSUE THREAD

**Issue by andzi** [easylist/easylist#487]
> "Business Insider is an advertising supported site and we noticed you have ad-blocking enabled." 
> and 
> blablabla...
> 

Working custom filter: 
`businessinsider.com##div.showTemplate`

**Comment by darkmorpher** [comment]
Thanks. I solved it by blocking `tinypass.com^`

**Comment by Khrin** [comment]
Tinypass is used by various publishers to work as paywall, it's not advertisements and for this reason will not be blocked by EasyList.
