### ISSUE TITLE
prokerala.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#4875]
### List the website(s) you're having issues:

`https://www.prokerala.com/`

### What happens?

A push notification prompt is not removed, even when using both Fanboy's Notifications Blocking List and https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/push-notifications.txt. Note that the prompt only shows up after around 12~15sec.

![image](https://user-images.githubusercontent.com/22780683/74130280-019d4e80-4be2-11ea-8bf1-4a58b1eb4a1a.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/74130312-111c9780-4be2-11ea-85df-91b679fa0930.png)

### Your settings

- OS/version: Windows 10 November 2019 Update
- Browser/version: Chrome 80.0.3987.87 64-bit
- Adblock Extension/version: Nano Adblocker 1.0.0.135 + Nano Defender 15.0.0.181

### Other details:

`##.push-subscription-prompt` seems to me to remove the prompt entirely.

**Comment by spirillen** [comment]
I can confirm that I don't get any popup spam after 30 - 40 seconds with @DandelionSprout rule applied
