### ISSUE TITLE
http://10.0.4.107/csp/umdb/modules/operationalManagement/requestResult.csp?type=PING&ids=

### ISSUE THREAD

**Issue by jDizzleFoShizzle** [easylist/easylist#4877]
URL: `http://10.0.4.107/csp/umdb/modules/operationalManagement/requestResult.csp?type=PING&ids=`

### What happens?
A screen in a `[Sintrex](https://www.sintrex.com/)` business application is being blocked.

### List Subscriptions you're using:
- EasyList
- EasyPrivacy

### Your settings

Only extension is uBlock Origin, with default settings on browsers and extension

- OS/version: Debian 9.10
- Browser/version: Firefox 72.0.2 + Google Chrome 80.0.3987.87
- Adblock Extension/version: uBlock Origin v1.24.4

### Other details:
Rule `?type=ping&` of the EasyPrivacy list is blocking the request.
![Screenshot from 2020-02-03 11-36-54](https://user-images.githubusercontent.com/60874392/74137511-a2970400-4bf8-11ea-9d3c-4f1e1844f6a1.png)

The IP/domain changes with each of our clients.
The request from the business application will always contain `requestResult.csp?type=PING&`

**Comment by Khrin** [comment]
Does the last change help to fix the issue?

**Comment by jDizzleFoShizzle** [comment]
That works perfectly! Thanks!

**Comment by jDizzleFoShizzle** [comment]
I assume the resolve is on your end ':D
