### ISSUE TITLE
padsabz.com

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#4881]
### List the website(s) you're having issues:

`https://www.porndaa.com/porn/phoebe-cates-gif-porn.html`

### What happens?

OverLay js that redirects via adware domains

### Other details:

Found that this domains (js) is used for the jscript that generate the overlay

`https://padsabz.com/5b/11/ec/5b11ec577f7ab76d9e3bf5af286eda00.js`

See ref for more info

**Comment by ghajini** [comment]
Add this to easylist 
`/^https?:\/\/([a-z0-9]{8,10}\.)?[a-z0-9]{5,14}\.(com|bid|online|top|club)\/([a-z0-9]{2}\/){3}[a-f0-9]{32}\.js$/$script,third-party`
`/^https?:\/\/[a-z0-9]{5,14}\.(com|bid|online|top|club)\/[0-9a-f]{32}\/invoke.js$/$script,third-party`

**Comment by spirillen** [comment]
Hmm :unamused: 

still get a popunder -> redirects -> open new window :disappointed: 

It happens if you press on any of the Blue "Download" redirecting url = `https://www.porndaa.com/?d=https%3A%2F%2Fi.pinimg.com%2Foriginals%2F49%2Fca%2F6e%2F49ca6e047e29d8ccf2b3d1aec24f706a.gif`
