### ISSUE TITLE
Remove vilynx.com from easyprivacy_trackingservers.txt

### ISSUE THREAD

**Issue by VJordi** [easylist/easylist#4885]
Hello!

on this commit https://github.com/easylist/easylist/commit/adb5283c1b206226fb47807470e3a30422b10ff4 done by @ryanbr vilynx.com was added to the easyprivacy_trackingservers.txt list.

Vilynx does user tracking, based on the customer setting (we are a third party) but all the tracking is done under dagda.vilynx.com (which is blocked, and personally I think that is ok)

However, blocking the whole domain of vilynx.com is blocking all the services that we provide to the media industry like video previews (that are user agnostic, and is not using any user information).

There is no reason to block vilynx.com since, it is not tracking user data. 

### List Subscriptions you're using:
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt

Thanks.

**Comment by THEtomaso** [comment]
I'd advice you to provide an example link, demontrating breakage of the so-called features that you refer to.
Otherwise, your request will probably be denied on principle.

**Comment by ryanbr** [comment]
Looking at the script https://pastebin.com/ydd4FpEk (https://static.vilynx.com/gallery/vpg.5.2.0.min.js) So much logging, mouse event checks. Your scripts need to be cleaned up first. 

If you place your tracking in a specific domain, that is fine. but in this case, its not.

**Comment by spirillen** [comment]
HAHAHA

I've found quit a history of this domain from external sources..

(Not varified, pure early import history)

|id|name|
|--|----|
|3016660|test.vilynx.com.rpz.mypdns.cloud|
|3016661|dev.vilynx.com.rpz.mypdns.cloud|
|3496256|www2.vilynx.com.rpz.mypdns.cloud|
|3496257|public.vilynx.com.rpz.mypdns.cloud|
|3496258|static.vilynx.com.rpz.mypdns.cloud|
|3496259|blog.vilynx.com.rpz.mypdns.cloud|
|3496260|www.blog.vilynx.com.rpz.mypdns.cloud|
|3496261|research.vilynx.com.rpz.mypdns.cloud|
|3496262|personal.vilynx.com.rpz.mypdns.cloud|
|3496263|developer.vilynx.com.rpz.mypdns.cloud|
|3496264|public.test.vilynx.com.rpz.mypdns.cloud|
|3496265|static.test.vilynx.com.rpz.mypdns.cloud|
|3496266|personal.test.vilynx.com.rpz.mypdns.cloud|
|3496267|developer.test.vilynx.com.rpz.mypdns.cloud|
|3496268|www.test.vilynx.com.rpz.mypdns.cloud|
|3496269|static.dev.vilynx.com.rpz.mypdns.cloud|
|3496270|www.static.dev.vilynx.com.rpz.mypdns.cloud|
|3496271|www.vilynx.com.rpz.mypdns.cloud|


Blocking this at second level seems right to me :100:
