### ISSUE TITLE
EasyPrivacy breaks vSphere HTML5 UI

### ISSUE THREAD

**Issue by TobiX** [easylist/easylist#489]
VMWare vSphere 6.5 comes with a new HTML5 UI (vSphere Client-Version 6.5.0.5300), its main theme is called "Clarity", one of its JavaScript files is called `clarity-angular1.min.js`:

    https://vcenter.COMPANY/ui/resources/libs/clarity-angular1.min.js

This is unfortunately blocked by the following EasyPrivacy filter:

    /clarity-*.js

This destroys the whole UI :(

**Comment by SMed79** [comment]
Hi, 

Related to https://forums.lanik.us/viewtopic.php?f=64&t=35937
Report your issue at https://github.com/vmware/clarity/issues

**Comment by TobiX** [comment]
Is seems already fixed: https://github.com/vmware/clarity/issues/850 - Thanks!
