### ISSUE TITLE
AdReclaim on dailycaller/thefreethoughtproject/ETC

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#49]
`http://dailycaller.com/2016/06/20/sotomayor-dissent-reads-like-a-black-lives-matter-manifesto/`

Trending Now/From Around The Web (AdReclaim)

**Comment by terrorist96** [comment]
`http://dailycaller.com/2016/06/22/rangel-no-guns-for-americans-but-i-need-police-protection-audio/`

**Comment by IsraeliAdblocker** [comment]
domains: ws-gateway.com,internalredirect.site
rule:
dailycaller.com##a[style*="visibility: visible !important"]

**Comment by terrorist96** [comment]
http://thefreethoughtproject.com/concealed-carrier-stops-mass-shooting/

**Comment by terrorist96** [comment]
`http://dailycaller.com/2016/07/26/dem-delegate-admits-common-sense-gun-control-is-just-code-for-repealing-second-amendment-video/`

**Comment by terrorist96** [comment]
`http://www.itechpost.com/articles/32830/20160924/pokemon-go-news-and-update-extra-bonus-candies-on-buddy-pokemon-is-it-possible.htm`

Trending now, ad reclaim

**Comment by terrorist96** [comment]
`http://www.blacklistednews.com/`
