### ISSUE TITLE
blank site https://bigleaguepolitics.com/ 

### ISSUE THREAD

**Issue by zoey965** [easylist/easylist#4901]
### List the website(s) you're having issues:
https://bigleaguepolitics.com/

### What happens?
We're experiencing full blank page on our website, nothing can be access ...

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by THEtomaso** [comment]
### Problem filter:
* EasyList

### Problem rule:
`||bigleaguepolitics.com^$csp=script-src 'self' *.leadpages.net *.gstatic.com *.google.com *.googleapis.com *.playwire.com *.facebook.com *.bootstrapcdn.com *.twitter.com *.spot.im`

### Note:
**AdGuard Base filter** has had a fix in place for half a year, which overrides EasyList's problem rule, by whitelisting it:
https://github.com/AdguardTeam/AdguardFilters/blob/20a38abfc9468620d05ab184321ca7687a954358/EnglishFilter/sections/whitelist.txt#L609

**Comment by ryanbr** [comment]
Removed filter, the reason we blocked was due to revolving ads servers and Yavli. If we get notified again, we'll need to take action again against this. @zoey965
