### ISSUE TITLE
https://www.mediasetplay.mediaset.it/

### ISSUE THREAD

**Issue by Danieleeee** [easylist/easylist#4918]
### List the website(s) you're having issues:
https://www.mediasetplay.mediaset.it/

### What happens?
Movies don't start:
![mediasetPlay](https://user-images.githubusercontent.com/22749175/74602430-aae3b900-50a8-11ea-90bc-e40064a7bb83.png)

### List Subscriptions you're using:
[nano-backup_2020-02-16_10.43.13.txt](https://github.com/easylist/easylist/files/4209599/nano-backup_2020-02-16_10.43.13.txt)

### Your settings

- OS/version: Ubuntu
- Browser/version: Chrome and Firefox (latest)
- Adblock Extension/version: Nano Adblocker v1.0.0.135

**Comment by ryanbr** [comment]
Which filtersets are you using?
