### ISSUE TITLE
airship.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#4919]
### List the website(s) you're having issues:

`https://www.airship.com/resources/explainer/web-push-notifications-explained/` (ironically enough)

### What happens?

A push notification prompt is not removed, even when using both Fanboy's Notifications Blocking List and https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/push-notifications.txt. The prompt shows up immediately, but can only be triggered once without clearing cookies.

![image](https://user-images.githubusercontent.com/22780683/74603411-8ccf8600-50b3-11ea-9ba7-48a800574069.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/74596327-1482a980-504e-11ea-899e-09772a5d1a02.png)

### Your settings

- OS/version: Windows 10 November 2019 Update
- Browser/version: Chrome 80.0.3987.106 64-bit
- Adblock Extension/version: Nano Adblocker 1.0.0.135 + Nano Defender 15.0.0.185

### Other details:

`airship.com##.Page > div > .PushNotification` seems to me to remove the prompt entirely, but leaves behind a grey background behind it.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ea19af2bea98eb29cdeba883154e8ab7ee49a834
