### ISSUE TITLE
problem from facebook

### ISSUE THREAD

**Issue by lukjan32** [easylist/easylist#492]
Please correct because, sometimes it crashes facebook, you can not scroll with the arrows.

**Comment by darkmorpher** [comment]
Can't reproduce it.

**Comment by lukjan32** [comment]
good :(

**Comment by mapx-** [comment]
It's your setup / system I guess.
Try using only 1 adblocker, disable all othe extensions / addons.

If still does not work, reset your browser, install only the actual adblocker, test again.
If ABP/ uBo does not work, try uBo/ ABP.

**Comment by lukjan32** [comment]
I have one extension, even cleaned up the opera browser, facebook cookies and cache, did not help :(

**Comment by mapx-** [comment]
You have to reset opera or if has not this feature, uninstall it, delete all the remaining opera folders, reinstall it + adblocker.

Or, do a test using other browser, better if chrome / chromium.

**Comment by lukjan32** [comment]
I did so too.

Opera is chrome.

I only have a firewall and defender system.

**Comment by peace2000** [comment]
This probably isn't relevant anymore. @ryanbr
