### ISSUE TITLE
Request to unblock: https://demo-ftp.flippingbook.com/public/jeroen/QSG/

### ISSUE THREAD

**Issue by R0ma-D** [easylist/easylist#4936]
### List the website(s) you're having issues:

For example: `https://demo-ftp.flippingbook.com/public/jeroen/QSG/`

### What happens?

We are developing software that transform PDFs into HTML5 documents (`https://flippingbook.com/digital-publishing-software`). And over the years, our customers have created a huge number of publications with dependency like `customer.web.site/<some-server-path>/html/static/analytics.js?uni=...`. Now when you turn on the ad blocker, all these publications completely do not work. 
Could you please unblock this path? 

### List Subscriptions you're using:

ublock/opera with EasyPrivacy

### Your settings

- OS/version: Windows 10 / unrelated
- Browser/version: Chrome 80, Opera 66
- Adblock Extension/version: uBlock Origin 1.24.4

### Other details:

https://github.com/easylist/easylist/blob/68e3d2827bd33de9c94c1cdf3e9048d2b2d5a7bb/easyprivacy/easyprivacy_general.txt#L3756

**Comment by ryanbr** [comment]
I would recommend not using `static/analytics.js ` to avoid issues.

**Comment by R0ma-D** [comment]
@ryanbr thanks for the recommendation). 
The problem is that we can only change the path in future in new versions of our desktop application. But over the past few years, when the path "static/analytics.js" was completely legal, thousands of our customers have already created their "publications". Publications are located on customers' own servers, we don’t even know where and naturally we do not have any access to them. In fact, all we can do is ask to upgrade to the latest version and redo all the work over the past few years, which seems completely impossible. 
Please exclude `html/static/analytics.js` from blocking.

**Comment by ryanbr** [comment]
Due to privacy, we can't remove the filter, but we can't whitelist it either (privacy is really important). The filter is around 6 months old and I'm happy to leave it. The filter is decent.

Original commit: https://github.com/easylist/easylist/commit/bb6930b3537
