### ISSUE TITLE
False Positive adcore.ch

### ISSUE THREAD

**Issue by slartibartfass** [easylist/easylist#495]
The Domain **adcore.ch** (Website still in development) from one of our customers is not related to adcore.com (SEM, Adwords) and needs a whitelisting like **adcore.com.au** in easylist.

Otherwise visitors have problems with missing graphics, css and js

**Comment by Khrin** [comment]
So this mean that the site is not live yet? Is there a chance to check if there's really a false positive?

**Comment by slartibartfass** [comment]
Site is not live yet. If you are not logged in as an administrative account, you just see the maintenance page.
Included a screenshot from the development of the site.
![adcore-ch-screenshot](https://user-images.githubusercontent.com/1481796/28916762-99c6dfd4-7843-11e7-835e-5738df9ce8e5.jpg)

Following Rules are triggered because of "adcore":
/adcore.$domain=~adcore.com.au|~adcore.ua
/adcore_$domain=~adcore.com.au
