### ISSUE TITLE
gocomics.com

### ISSUE THREAD

**Issue by in4u** [easylist/easylist#4952]
### List the website(s) you're having issues:

`https://www.gocomics.com`

### What happens?

There's this `###cookieconsent-container` just below the navigation menu on top of the page.

### List Subscriptions you're using:

`Easylist Cookie`

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 73.0.1
- Adblock Extension/version: uBO 1.24.4

**Comment by ryanbr** [comment]
We are blocking `###cookieconsent-container` already?

**Comment by in4u** [comment]
Oh. I see `@@||gocomics.com^$ghide` rule in uBO's default filter [here](https://github.com/uBlockOrigin/uAssets/issues/1136#issuecomment-354499405). @okiehsch @mapx- Can you guys please help fix this?

**Comment by mapx-** [comment]
fixed

**Comment by in4u** [comment]
Thanks!
