### ISSUE TITLE
motocombo.pl

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#4953]
### List the website(s) you're having issues:

`motocombo.pl`

### What happens?

incorrect hidden footer:

`motocombo.pl#@#.footer-social`

### List Subscriptions you're using:

Fanboy Social Blocking List

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 73
- Adblock Extension/version: uBo 1.24.2 

### Other details:

`motocombo.pl#@#.footer-social`

maybe:

`motocombo.pl###widget_shop7`
`motocombo.pl##.social-conteiner`

![obraz](https://user-images.githubusercontent.com/35370833/75094839-0d4c2600-558f-11ea-8c77-4654804233b0.png) |
--- |
`###widget_shop7` |

![obraz](https://user-images.githubusercontent.com/35370833/75094844-1b01ab80-558f-11ea-8951-e531849c0af6.png)
--- |
`##.social-conteiner` |

**Comment by Khrin** [comment]
I don't see anything of incorrectly blocked.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/81926496-5043f580-95e2-11ea-8148-5187dba999bb.png)

on right in footer.

this is not a social and will no blocked - say "no worth" is bad solution

**Comment by krystian3w** [comment]
Also you omitted block social slider on left:

`###widget_shop7`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/92d440ff098d0f9f3c56cb5aeb6fc6bc5dcc94f0
