### ISSUE TITLE
www.duellinksmeta.com

### ISSUE THREAD

**Issue by azlum0** [easylist/easylist#4969]
### List the website(s) you're having issues:

https://www.duellinksmeta.com/

### What happens?

A large pop-up saying adblock was detected and asking for a membership to "DLM Pro"

### List Subscriptions you're using:

Nano Defender Integration
Nano filters​
Nano filters – Whitelist​
uBlock filters​
uBlock filters – Badware risks​
uBlock filters – Privacy​
uBlock filters – Resource abuse​
uBlock filters – Unbreak​
Adblock Warning Removal​​​​​
EasyList​
EasyPrivacy
Malware Domain List
Malware domains​
Peter Lowe's Ad and tracking server list​​​​​

### Your settings

Pretty much defaults.

- OS/version: Windows 10
- Browser/version: Firefox 73.0.1
- Adblock Extension/version: Nano Adblocker + Nano Defender

**Comment by ryanbr** [comment]
Easylist won't touch the Anti-adblock sorry.
