### ISSUE TITLE
Google Analytics is blocked on apkmaniafull.com

### ISSUE THREAD

**Issue by waqarts** [easylist/easylist#497]
Google Analytics is blocked on  Domain apkmaniafull.com , i think easylist is for blocking ads not google analytics please fix this 

thanks and regards,

developer apkmaniafull.com
![screenshot_2 1358 x 693](https://user-images.githubusercontent.com/30706949/28948062-c1db639e-78cc-11e7-9cac-32419ffdec44.jpg)

**Comment by LanikSJ** [comment]
Google Analytics is blocked in EasyPrivacy.  It's only default on uBlock, rest of the Adblockers it's optional.

**Comment by waqarts** [comment]
dear thanks for reply but i think google analytical is blocked due to this filter of Easylist please fix this thanks

$script,third-party,domain=apkmaniafull.com|...

**Comment by Khrin** [comment]
All scripts on your domain are blacklisted because of the revolving adservers present on your site. And anyway as said above, Google Analytics is blocked in EasyPrivacy.

**Comment by Khrin** [comment]
All scripts on your domain are blacklisted because of the revolving adservers present on your site. And anyway as said above, Google Analytics is blocked in EasyPrivacy.

**Comment by waqarts** [comment]
Dear block adservers but unblock google analytical & histats script its not block by easypiracy as u can see by screenshot

![screenshot_3](https://user-images.githubusercontent.com/30706949/28984695-a9cc126a-7978-11e7-9431-74ea4e8a83ef.png)
![screenshot_4](https://user-images.githubusercontent.com/30706949/28984696-a9cf8c24-7978-11e7-9683-2978f527c04a.png)

**Comment by waqarts** [comment]
Please Dear,

white list my domain i have fixed the revolving adservers problem i will be thankfull to you i am relying on my website to earn some cash for my family.. waiting for your kind response

Regards
