### ISSUE TITLE
Will Admiral anti-adblock be blocked?

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#4984]
Hi! I'm not sure if this is in the scope of Easylist so that's why I'm asking.

![kuva](https://user-images.githubusercontent.com/17256841/75353896-caeb5780-58b4-11ea-8960-2a7b7656bee6.png)

Domain: https://www.winhelponline.com/

Rule to block that nag:

`||absorbingcorn.com^$third-party`

**Comment by llacb47** [comment]
No.

**Comment by llacb47** [comment]
😲

**Comment by peace2000** [comment]
@llacb47 interestingly it was added to Easyprivacy. Well, those kinda track you if they check your adblocker status. :D
