### ISSUE TITLE
space.com amazon ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#50]
`http://www.space.com/`
`http://www.space.com/33185-earth-quasi-moon-asteroid-2016-ho3.html`

Amazon ads

**Comment by monzta** [comment]
Seems they are already removed.

**Comment by terrorist96** [comment]
@monzta I still see it.
![capture](https://cloud.githubusercontent.com/assets/12802056/16594121/cd80dd7a-42b6-11e6-8dff-a7140bc0d3b0.PNG)

**Comment by terrorist96** [comment]
![a](https://cloud.githubusercontent.com/assets/12802056/16594139/e7962300-42b6-11e6-9ab3-519fc1b3fd2a.PNG)

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/36d44397a3d644c1c1cc823a35ce42198f2f0ba7

**Comment by terrorist96** [comment]
@monzta 
I see the same ads again. See OP for links^
