### ISSUE TITLE
forum.matomo.org doesn't load due to CNAME

### ISSUE THREAD

**Issue by Findus23** [easylist/easylist#5013]
I can reproduce this in a clean firefox profile with uBlock origin without any changes.

### List the website(s) you're having issues:
`https://forum.matomo.org` doesn't load as all requests are blocked

### What happens?

`forum.matomo.org` is a CNAME to `piwik.discoursehosting.net` our host. The site has nothing to do with tracking, but is the discussion forum of `matomo.org` (formerly piwik) which is a self-hosted, FOSS web analytics software.

There is a rule in EasyPrivacy `://piwik.$third-party` that is supposed to block tracking from people who installed Matomo to `piwik.example.com`, but as uBlock origin now checks CNAMEs and apparently matches `$third-party` in this case.

https://github.com/easylist/easylist/blob/8f97039cd420e381281a953993c6a6818a3c8d7d/easyprivacy/easyprivacy_general.txt#L4904

### List Subscriptions you're using:

default uBlock origin, but specifically caused by EasyPrivacy

### Your settings

- OS/version: Debian bullseye
- Browser/version: Firefox 73.0.1
- Adblock Extension/version: uBlock origin 1.25.0

**Comment by gorhill** [comment]
Force an update of "uBlock filters -- Unbreak".

**Comment by krystian3w** [comment]
Need wait 10 minutes after PR - glitched `raw.github.com`

**Comment by Findus23** [comment]
@gorhill Thanks for fixing this, in the future I will try to test beta versions before major changes like this one for breaking things.
