### ISSUE TITLE
Businessinsider popup

### ISSUE THREAD

**Issue by balping** [easylist/easylist#504]
http://www.npttech.com/advertising.js

**Comment by mirague** [comment]
What are you trying to say with this? That the URL should be blacklisted? I actually landed on Business Insider's page today and was faced with their version of an anti adblocker. I've turned off javascript for their domain as a short-term solution. Would be nice to see this addressed through EasyList - would we just blacklist `npttech.com`?

Related:
- https://github.com/uBlockOrigin/uAssets/issues/157

**Comment by balping** [comment]
Yes, I meant that should be blacklisted. Having that manually blacklisted, the ant-adblocker disappears.

I checked now, and what you linked here is actually a *white list*. It should be blacklisted I think, I don't really understand that.
