### ISSUE TITLE
marketcall.net

### ISSUE THREAD

**Issue by Korovikov** [easylist/easylist#5040]
### List the website(s) you're having issues:

https://www.marketcall.net/

### What happens?

Most of our URLs contain an 'affiliate' string. And rule 'net/affiliate' block all our ajax requests (tables, selects, etc...).
![screen](https://user-images.githubusercontent.com/18149446/75656803-d1dbe680-5c75-11ea-9bb5-bb0c0f1504c5.png)

### List Subscriptions you're using:

ABP filters
Adblock Warning Removal List
EasyPrivacy
RuAdList+EasyList
Allow nonintrusive advertising

### Your settings

- OS/version: 79.0.3945.130
- Browser/version: 79.0.3945.130
- Adblock Extension/version: 3.8

### Other details:

![screen2](https://user-images.githubusercontent.com/18149446/75656985-46af2080-5c76-11ea-9e88-d76c237d3f02.png)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/a8c9b93d737c13b7062e094e5c6b6e39dffc96ec Added a change which should exclude your domain from our filter. Update you filters list.

**Comment by Korovikov** [comment]
@Khrin Thanks!
