### ISSUE TITLE
nanda.to

### ISSUE THREAD

**Issue by ZaphodBeebblebrox** [easylist/easylist#5052]
### List the website(s) you're having issues:
`nanda.to`

### What happens?

There is an annoying dropdown that advertises brave.

### List Subscriptions you're using:
Tested with uBO defaults + annoyance lists.

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 80.0.3987.122 (Official Build) (64-bit) (cohort: Stable)
- Adblock Extension/version: uBlock Origin 1.24.4

### Other details:

Possible Filter: `nanda.to##.cAnnouncementPageTop > a[href*="brave.com"]`

I understand if you are unwilling to do anything about this because of your connection to brave.

**Comment by Khrin** [comment]
Hi @ZaphodBeebblebrox , is this element still present?

**Comment by ZaphodBeebblebrox** [comment]
No, it was removed after around a day.
