### ISSUE TITLE
marketwatch.com breaking news bulletin on homepage [Incorrect blocking]

### ISSUE THREAD

**Issue by yourduskquibbles** [easylist/easylist#5053]
### List the website(s) you're having issues:

`https://www.marketwatch.com/`

### What happens?

News Bulletin (may only appear when there is breaking news) at the top of homepage under the site header is not showing because of easylist filter `##.has-ad`

Fixed with `marketwatch.com#@#.has-ad`

Screenshot:
![marketwatch](https://user-images.githubusercontent.com/22258847/75895527-c9b1b180-5e03-11ea-93f9-f5f909b0ec63.png)

### List Subscriptions you're using:

- Default uBlock Origin lists + uBlock filters - Annoyances

### Your settings

- Chrome test profile with default uBlock Origin settings and lists + uBlock Annoyances & uBlock Experimental Lists.
- OS/version: Windows 10 64bit
- Browser/version: Chrome Version 81.0.4044.34 (Official Build) beta (64-bit)
- Adblock Extension/version: uBlock Origin 1.24.5b4 (Latest Dev Build available on Chrome Web Store)

**Comment by ryanbr** [comment]
Breaking ad sure, but is it a selfpromo?

**Comment by yourduskquibbles** [comment]
it's a breaking news item that they only deploy semi-frequently. Yes it is a self-promo for a link that would go to an article on the same domain if that is the question.
