### ISSUE TITLE
False positive: audible.com

### ISSUE THREAD

**Issue by eseverson** [easylist/easylist#506]
https://samples.audible.com/bk/adbl/030461/bk_adbl_030461_sample.mp3
Matches: /adbl/

page: https://www.audible.com/pd/Fiction/The-Handmaids-Tale-Special-Edition-Audiobook/B06XFW9YZ5/ref=t2_asin_pd_anonhp?ie=UTF8&pf_rd_r=072P9GWRZ0T4KJ195BJ6&pf_rd_m=A2ZO8JX97D5MN9&pf_rd_t=101&pf_rd_i=anonhp&pf_rd_p=3177013222&pf_rd_s=center-3

Cannot play sample

**Comment by SMed79** [comment]
Test the filters you find here https://forums.lanik.us/viewtopic.php?f=64&t=30381

**Comment by peace2000** [comment]
Is this problem still in effect? (I can play the sample).

**Comment by Khrin** [comment]
Matching filter has been removed long ago.
