### ISSUE TITLE
.org and .net mirrors of pornhub.com [NSFW]

### ISSUE THREAD

**Issue by in4u** [easylist/easylist#5065]
Please update filters for `pornhub.com` to include `pornhub.org` and `pornhub.net` mirror domains as well.

**Comment by ryanbr** [comment]
Its just re-directing? If they started to use it then sure.

**Comment by DandelionSprout** [comment]
`https://www.pornhub.org/video/search?search=vacbed` and `https://www.pornhub.net/video/search?search=vacbed` both insta-redirected themselves to `https://www.pornhub.com/video/search?search=vacbed` on my end, so I'm going to side with Ryan Brown on this one.

**Comment by in4u** [comment]
No, it's location based. In countries where .com version is banned, the other mirror is served by default. For example, test using an Indian proxy IP then even the .com version will be redirected to .org only.

**Comment by DandelionSprout** [comment]
Ah, that explains everything. Thanks so much for the explanation and clarification! 🤗

**Comment by neer9** [comment]
> No, it's location based. In countries where .com version is banned, the other mirror is served by default. For example, test using an Indian proxy IP then even the .com version will be redirected to .org only.

This have to be explained to everyone  😂  https://github.com/AdguardTeam/AdguardFilters/issues/86179#issuecomment-867589409

**Comment by DandelionSprout** [comment]
Using *AdGuard VPN*'s Indian server, both `pornhub.com` and `pornhub.org` seem to be blocked. So I apologise for the general difficulty I have in accessing the latter site.

**Comment by ryanbr** [comment]
Closing. as with Adguard, and Easylist. it just redirects.
