### ISSUE TITLE
gouvernement.fr [URGENT - COVID-19]

### ISSUE THREAD

**Issue by ivanosevitch** [easylist/easylist#5067]
### List the website(s) you're having issues:

`https://www.gouvernement.fr/info-coronavirus`

This page lists the official recommendations of the French government for COVID-19. The number of cases is currently exploding in France, but these recommendations are not accessible to someone using EasyList Cookie.

### What happens?

1. Subscribe to EasyList Cookie
1. Click on any red arrow such as these:
![image](https://user-images.githubusercontent.com/15523557/76617255-358fca80-6526-11ea-959a-e6c69b1a69f0.png)
1. Expected behavior: section is uncollapsed
1. Actual behavior: nothing happens

### List Subscriptions you're using:

EasyList Cookie

### Your settings

- OS/version: macOS 10.15
- Browser/version: Chrome 80.0
- Adblock Extension/version: uBlock Origin 1.24.4

### Other details:

Filter blocking the request: `/tarteaucitron.`

This kind of exception can circumvent the issue:
```
@@||www.gouvernement.fr/sites/all/modules/custom/*_tarteaucitron/js/tarteaucitron/$~third-party
```

**Comment by ivanosevitch** [comment]
Thanks @ryanbr but the exception is not working, the red arrows still don't uncollapse the sections. The `/tarteaucitron.` filter is still blocking additional resources: 

```
https://www.gouvernement.fr/sites/all/modules/custom/pmv6_tarteaucitron/js/tarteaucitron/css/tarteaucitron.css?v=325
https://www.gouvernement.fr/sites/all/modules/custom/pmv6_tarteaucitron/js/tarteaucitron/lang/tarteaucitron.fr.js?v=325
```

**Comment by Khrin** [comment]
Removed the filter.
