### ISSUE TITLE
tampermonkey.net

### ISSUE THREAD

**Issue by bershan2** [easylist/easylist#507]
`tampermonkey.net` shows ads hosted on its own domain and not blocked by EasyList.

Problematic URLs include:
   - `tampermonkey.net/wikibuy/1/001.jpg` and alike `tampermonkey.net/wikibuy/2/{3 digits}.jpg`
   - `tampermonkey.net/ecosia/Side_simple.png`
   - possibly more?

All ads are inside of blocks with class `adventing`, so rule `tampermonkey.net##.adventing` hides them, but does not fix the layout of the page (leaves some empty space).

The old rules do not seem to be active on the site
```
||tampermonkey.net/bner/
||tampermonkey.net^*.*.$subdocument
```

**Comment by SMed79** [comment]
test these filters https://forums.lanik.us/viewtopic.php?p=122147#p122147
