### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by alexkoala** [easylist/easylist#5085]
### List the website(s) you're having issues:
[youtube.com](https://www.youtube.com/)

### What happens?
EasyList blocks [10-second "Includes paid promotion" text disclosure](https://support.google.com/youtube/answer/154235) in video player.

e.g. "Includes paid promotion" enabled [Youtube video](https://www.youtube.com/watch?v=-VuYCLelIO8)

### List Subscriptions you're using:
* EasyList

### Your settings

- OS/version: macOS 10.15.3
- Browser/version: Chrome 80.0.3987.132
- Adblock Extension/version: uBlock Origin 1.24.4

**Comment by ryanbr** [comment]
Need details on this @alexkoala

**Comment by alexkoala** [comment]
> Need details on this @alexkoala

@ryanbr "Includes paid promotion" means this video is "sponsored" video. (not ad)
For example, [this](https://www.youtube.com/watch?v=-VuYCLelIO8) game developer paid money to video uploader to upload and make this video. US, UK, FR, DE, KR uploaders must need to notify viewers if video is paid promotion.
You can check [US FTC](https://www.ftc.gov/tips-advice/business-center/guidance/ftcs-endorsement-guides-what-people-are-asking) or [YouTube Help](https://support.google.com/youtube/answer/154235) about more information.
