### ISSUE TITLE
Not correct blocking https://cdn.alfacrm.pro/* by commit

### ISSUE THREAD

**Issue by vvolynets** [easylist/easylist#5086]
Commit https://github.com/easylist/easylist/commit/d6e6a848f1aff9921e90ffcb1299a103dedaa6ee

This blocks our CDN, and thousands of our customers are angry.

Please, validate this code again ASAP.

**Comment by llacb47** [comment]
https://github.com/easylist/easylist/commit/c0f5b38df2bf2fed8d0b5faa9b7b1a66325e9e3b
