### ISSUE TITLE
https://api.chayns-static.space

### ISSUE THREAD

**Issue by sebkortenbrede** [easylist/easylist#5087]
All our urls containing "space" getting blocked! A lot of sites can't be used with this list enabled after the last update.

### List the website(s) you're having issues:
I can't list every site here becouse there are too much of them.
This is a good example:
https://chayns.de

### What happens?
Scripts, CSS and some HTML files getting blocked. A lot of our sites aren't useable anymore.

### List Subscriptions you're using:
EasyList

### Your settings
- OS/version: 
 Windows 10
- Browser/version: 
Chrome 80
- Adblock Extension/version: 
4.7.3

### Other details:
Following RegEx:
^https?:\/\/.*\.(xyz|site|pro|best|club|space|info|bid)\/.*
commit: https://github.com/easylist/easylist/commit/d6e6a848f1aff9921e90ffcb1299a103dedaa6ee

**Comment by vvolynets** [comment]
+

**Comment by vvolynets** [comment]
and https://cian.ru (https://cdn.cian.site)

**Comment by AlexandreLepretre** [comment]
Images, CSS, and scripts from https://images1.sportpursuit.info are also all blocked, this is the domain of our production CDN.

**Comment by llacb47** [comment]
https://github.com/easylist/easylist/commit/c0f5b38df2bf2fed8d0b5faa9b7b1a66325e9e3b
