### ISSUE TITLE
fandom.com: one ad piece and an annoyance

### ISSUE THREAD

**Issue by gakada** [easylist/easylist#5088]
### List the website(s) you're having issues:

```
https://kancolle.fandom.com/wiki/KanColle_Wiki
```
or most other pages on most FANDOM wikis.

### What happens?

There is already a filter for `.aff-unit__wrapper`, but since https://github.com/Wikia/app/commit/36ecbb6fcab1db5548d4bd5a68ad4034579c4c2b#diff-a52778eae3e0efd0892a65bd1e9ed30e there is also `.aff-unit__disclaimer-message`.

Additionally, there is "Fan Feed" at the bottom (`#mixed-content-footer`), which maybe should be added in annoyances?

![1584541399](https://user-images.githubusercontent.com/13043588/76971289-5ade6780-6970-11ea-9530-141afb647567.png)

![1584541884](https://user-images.githubusercontent.com/13043588/76971521-a42eb700-6970-11ea-9482-94fefdc7524c.png)

![1584541817](https://user-images.githubusercontent.com/13043588/76971538-a85ad480-6970-11ea-8282-930932c074c3.png)

**Comment by ryanbr** [comment]
Seems to be part of the site?  not sure about `.aff-unit__disclaimer-message` Need more details

**Comment by Alex-302** [comment]
> not sure about `.aff-unit__disclaimer-message` Need more details

this is a comment for ad, so can be hidden
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/77083151-b4dd3c80-6a05-11ea-934e-861c7a25fdbd.png)

</details>

**Comment by gakada** [comment]
Another example
![1584640681](https://user-images.githubusercontent.com/13043588/77099174-dc102a00-6a56-11ea-9011-a30ef56ab071.png)
uBlock Origin blocks `.aff-unit__wrapper` thanks to EasyList/AdGuard lists, but `.aff-unit__disclaimer-message` rule is missing.
