### ISSUE TITLE
All *.info domains are blocked.

### ISSUE THREAD

**Issue by xytoki** [easylist/easylist#5089]
### List the website(s) you're having issues:
Maybe not important. I will provide it if needed.

### What happens?
I have an api server on a `.info` domain , and it's blocked by this rule, which applies for all `.info` domains.
https://github.com/easylist/easylist/blob/f4ed1461e95b2b86870e550e3d651e311e422472/easylist/easylist_specific_block.txt#L713
Is it necessary to block all `.info` domains?

### List Subscriptions you're using:

`uBlock origin`
`Easylist`
### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome 79.0
- Adblock Extension/version: uBlock Origin v1.24.4

**Comment by llacb47** [comment]
https://github.com/easylist/easylist/commit/c0f5b38df2bf2fed8d0b5faa9b7b1a66325e9e3b

**Comment by xytoki** [comment]
Thanks. But after I renew the rules it remains blocked, maybe there is something cached somewhere.
