### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5100]
Going there
https://www.facebook.com/settings?tab=account&view
clicking on "ad contact address" (don't know the exact name in english) is blocked by easylist, filter :
/advertising_$domain=~advertising.scoop.co.nz

url : 
https://www.facebook.com/ajax/settings/account/advertising_email.php?fb_dtsg_ag=.....

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/bc403c7a1e7b00cff4c132d48c5f1cae01ae913e
