### ISSUE TITLE
kobieta.onet.pl [EasyPrivacy]

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#5101]
### List the website(s) you're having issues:

`https://kobieta.onet.pl/kobiety-dodatkowe-zalecenia-higieniczne/ewcm7q7` [](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1799)

### What happens?

Broken embeded video:

![obraz](https://user-images.githubusercontent.com/35370833/77083267-852a3680-69fd-11ea-930b-ef6d4b4fbb1f.png) | ![obraz](https://user-images.githubusercontent.com/35370833/77082905-00d7b380-69fd-11ea-89f4-08528c97f1f5.png)
--- | --- 
`\|\|sgqcvfjvr.onet.pl^` | `@@\|\|sgqcvfjvr.onet.pl^$script,domain=kobieta.onet.pl`

### List Subscriptions you're using:

EasyList
**EasyPrivacy**

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 74.0.0
- Adblock Extension/version: 3.8

### Other details:

`@@||sgqcvfjvr.onet.pl^$script,domain=kobieta.onet.pl`

@easylistpolish / @adblock-filters

**Comment by ryanbr** [comment]
Came from my commit. https://github.com/easylist/easylist/commit/3e3379adc65

Looks like a tracker, no issues on `https://plejada.pl/`

https://github.com/easylist/easylist/commit/09d11f48c142ea8f5a2c6a4836bff2270e581c99

Happy for another party to review it.

**Comment by krystian3w** [comment]
`https://wiadomosci.onet.pl/kraj/w-polsce-czy-przestrzegamy-kwarantanne/75dfd5n`

Also no visible embeded player:

![obraz](https://user-images.githubusercontent.com/35370833/77164879-77ce8400-6ab1-11ea-946c-37a804c17387.png) | ![obraz](https://user-images.githubusercontent.com/35370833/77164815-52da1100-6ab1-11ea-8bf9-78669ebdfba8.png) 
--- | --- 

I understand that now every embeded video user must have to open in a new card/tab/window (excluding the value of the embedded video against the article).

**Comment by easylistpolish** [comment]
Hey, looks like after ryanbr fix it works. Anyway thanks for pinging me!:)

**Comment by krystian3w** [comment]
But other subdomains (e.g.: `wiadomosci.onet.pl`) also is affacted https://github.com/easylist/easylist/issues/5101#issuecomment-601684366

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/53042
