### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by cjx82630** [easylist/easylist#5105]
### List the website(s) you're having issues:
https://www.facebook.com/

### What happens?
Please add the following Chinese characters in the filters to remove ads on facebook.
`贊助|赞助内容`

### List Subscriptions you're using:
Easylist + Easylist china

### Your settings

- OS/version: win10
- Browser/version: chrome 80
- Adblock Extension/version: 3.8

### Other details:
`facebook.com#?#div[role="article"]:-abp-has(span:-abp-contains(/贊助|赞助内容|Sponsorlu|Sponsored|Gesponsert|Publicidad|Patrocinado|Sponsorisé|Sponsorizzato|Gesponsord|Sponsorowane|Реклама|Sponsa|Sponset|ממומן|Bersponsor|Ditaja|ได้รับการสนับสนุน|प्रायोजित|সৌজন্যে/))`

`www.facebook.com#$#hide-if-contains-visible-text /贊助|赞助内容|Sponsorlu|Sponsored|Gesponsert|Publicidad|Patrocinado|Sponsorisé|Sponsorizzato|Gesponsord|Sponsorowane|Реклама|Sponsa|Sponset|ממומן|Bersponsor|Ditaja|ได้รับการสนับสนุน|प्रायोजित|সৌজন্যে/ 'div[id^="topnews_main_stream"] div[data-testid^="fbfeed_story"]' 'div[id^="topnews_main_stream"] div[data-testid^="fbfeed_story"] div[id*="feed"][id*="sub"] a'; hide-if-contains /.*/ .ego_section 'a[href^="/ad__campaign/landing.php?"]'; hide-if-contains /.*/ .ego_section 'a[href^="/ad_campaign/landing.php?"]'; hide-if-contains /.*/ .ego_section 'a[href^="/ad___campaign/landing.php?"]'`

**Comment by krystian3w** [comment]
https://github.com/abp-filters/abp-filters-anti-cv/commit/d0ff2bd7e5e9c8d5730f7c69cc702f757c1cbdbd
