### ISSUE TITLE
freecoursesonline.me

### ISSUE THREAD

**Issue by reypryma** [easylist/easylist#5108]
### List the website(s) you're having issues:
freecoursesonline

`https://www.freecoursesonline.me`
### What happens?

failed to bypass adblok blocker
### List Subscriptions you're using:

nano adblocker
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by llacb47** [comment]
This is the Easylist repo, not the Nano Adblocker repo, stop reporting issues here.

```
freecoursesonline.me##+js(set, atob, trueFunc)
||styleui.ru^$3p
```

@mapx-

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/21e8f087c997ccec6aa101584837dd703da518e7
