### ISSUE TITLE
ABCNyheter.no - Blocked videos (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#5110]
### Affected site:
`https://www.abcnyheter.no/`

### Issue:
Videos are blocked!

### Examples:
`https://www.abcnyheter.no/abctv/`
(Try to play any one of the videos)

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyPrivacy

### Problem rule:
`||spklw.com^$third-party`

### Possible fix:
`@@||widgets.spklw.com^$domain=abcnyheter.no`

### Other problem filters:
* Schacks Adblock Plus liste (`||spklw.com`) ***Discontinued***

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.4 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
Can confirm both the problem entry and the fix, though only once a video link has been clicked on.

Notably, `widgets.spklw.com` seems to me to be pretty rarely used by any other sites. Normally it's `bonfire.spklw.com` that are used by e.g. `tv2.no` and `langrenn.no`.

Also notably, `abcnyheter.no` falsely claims it couldn't find the video/link content when `spklw.com` is blocked.

**Comment by THEtomaso** [comment]
> Normally it's `bonfire.spklw.com` that is used

`abcnyheter.no` uses it too, although it can be blocked, semingly without any ill effects!

**Comment by Khrin** [comment]
I can play videos correctly, does this issue still happen for you? @THEtomaso @DandelionSprout

**Comment by THEtomaso** [comment]
> does this issue still happen for you?

Nope, issue gone!
_Report closed! :)_

**Comment by THEtomaso** [comment]
@DandelionSprout:
Could you please remove the whitelisting from your Nordic filters?
No need to whitelist any more nasties than absolutely necessary.
