### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#5112]
### List the website(s) you're having issues:

`https://www.lydogbilde.no/test/hi-fi/hegel-h120` (and also all other sites with any `YouTube` embeds of any kind.)

### What happens?

`||youtube.com/get_video_info?$domain=youtube.com` in EasyList causes **all** YouTube embeds of all kinds on all third-party sites to fail to load, and therefore that entry should be removed ASAP.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/77250662-cadb3f00-6c49-11ea-8e37-8a2cb557fc73.png)

### Your settings

- OS/version: Windows 10 November 2019 Update
- Browser/version: Chrome 80.0.3987.149 64-bit
- Adblock Extension/version: Nano Adblocker 1.0.0.140 + Nano Defender 15.0.0.194

### Other details:

From the example page on Vivaldi with en-US locale: 
![image](https://user-images.githubusercontent.com/22780683/77250722-11c93480-6c4a-11ea-838f-02b17a428aa9.png)

From a Discord server I'm in on Chrome with nb-NO locale: 
![image](https://user-images.githubusercontent.com/22780683/77250746-3cb38880-6c4a-11ea-8391-dbcd379836df.png)

**Comment by THEtomaso** [comment]
I was just going to report this issue myself, but you beat me to it! :)

**Comment by sailerinteractive** [comment]
I can confirm this. Seems to break YT embeds on many websites.

**Comment by THEtomaso** [comment]
@mapx- / @okiehsch

Considering the severity of this breakage, perhaps this fix could be added to '**uBlock filters - Unbreak**​​​​​', for now?:
`||youtube.com/get_video_info?$domain=youtube.com,badfilter`

**Comment by mapx-** [comment]
unbreak list has this filter: `@@||youtube.com/get_video_info?$xmlhttprequest,badfilter`
(ads on YT)

killing the filter above could bring again the ads but not breaking the embeds?

**Comment by THEtomaso** [comment]
I've ben using `||youtube.com/get_video_info?$domain=youtube.com,badfilter` for over an hour now.
Haven't seen any ads.

**Comment by gwarser** [comment]
`youtube.com/get_video_info` was blocked only when requested with `=adunit&` parameter ([old fix for ads on UK YT](https://github.com/easylist/easylist/commit/f2fe916a6db90cba73c59583a5e7688c00842063)) ryanbr attempted to fix "error occurred" issues by whitelisting it:
https://www.reddit.com/r/uBlockOrigin/comments/fco9lr/ublock_origin_preventing_youtube_videos_from/fjcxbm0/

This caused surge of reports about ads, I called him on Reddit and he changed it to blocking filter. ([Misunderstanding?](https://www.reddit.com/r/uBlockOrigin/comments/fmerf2/ads_on_youtube/fl4x94b/?context=10000))

**Comment by ryanbr** [comment]
Okay, removed filter.

**Comment by ryanbr** [comment]
Can't win when a whitelist to attempt fix the YT errors, causing ads. then the same filter also has issues if blocked.  Sorry

**Comment by mapx-** [comment]
Could this work ?
```
||youtube.com/get_video_info?$domain=youtube.com
@@||youtube.com/get_video_info?*embedded$xmlhttprequest,~third-party
```

**Comment by judge2020** [comment]
Also seems to break loading any music on music.youtube.com
![image](https://user-images.githubusercontent.com/8601934/77261970-c5412180-6c68-11ea-8abb-58b8ccdb9066.png)

**Comment by mapx-** [comment]
fixed

**Comment by Alex-302** [comment]
Player at editor page is broken by recently added rules:
https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&v=jv543Nk5s18&lang=ru&bl=watch&ui=hd&ref=wt&tab=captions&ar=1584985005082&o=U
Checked with ABP.

**Comment by mapx-** [comment]
test
`@@||youtube.com/get_video_info?html5*editpage$xhr,domain=youtube.com`

**Comment by Alex-302** [comment]
@mapx- in this way all `/get_video_info?` requests will be unblocked:)

**Comment by okiehsch** [comment]
How about 
`@@||youtube.com/get_video_info?*timedtext_editor$xhr,1p`

**Comment by Alex-302** [comment]
> How about

I don't know. With old rules only I had no issues.

**Comment by patricknelson** [comment]
For folks landing here from Google and using uBlock Origin, go to the extension options, then click "Filter Lists" and then purge + update to fix the problem. For me even though EasyList was updated, it wasn't reflected since it was still caching the old list 😄 

Thanks for fixing this!

![image](https://user-images.githubusercontent.com/4269377/77476088-24bd3f80-6dd7-11ea-9115-e8c8c11f1b2e.png)

**Comment by DandelionSprout** [comment]
It's normally also possible to click on the clock icon to the right of the individual lists you want to update, but your method works too.

**Comment by bumsenbrenner** [comment]
No the problem still persists

**Comment by StructByLightning** [comment]
Disabling "Disable HTML5 Autoplay" extension made it work for me. I think it was interacting badly with UBO since disabling UBO also made it work, but I'm not really sure what's going on beyond that.

**Comment by patricknelson** [comment]
@StructByLightning if it helps, I actually have a similar extension which seems to not interfere called [AutoplayStopper](https://chrome.google.com/webstore/detail/autoplaystopper/ejddcgojdblidajhngkogefpkknnebdh) which might work as an alternative in case you still want that functionality without interfering with the embedded `<iframe>` problem.

**Comment by llacb47** [comment]
You don't even need a separate extension.

**Comment by Squall-Leonhart** [comment]
||youtube.com/get_video_info?$~third-party is also breaking embeds
