### ISSUE TITLE
TV.YOUTUBE.COM VIDEO PROBLEM

### ISSUE THREAD

**Issue by JasonConners** [easylist/easylist#5113]
### List the website(s) you're having issues:
https://tv.youtube.com
YOUTUBE.COM VIDEOS WORK FINE, ISSUE IS WITH TV.YOUTUBE.COM

### What happens?
When you click a video or live TV to watch, it tries to load and then shows an 
ERROR :  "An error occurred. Please try again later."

### List Subscriptions you're using:
The error is the EasyList and it just started happening. Everything was fine yesterday.

### Your settings
The error is the EasyList and it just started happening. Everything was fine yesterday. Disabling just the easylist in the adblock settings fixes the issue.

- OS/version: WINDOWS 10
- Browser/version: FIREFOX 74.0 64-BIT
- Adblock Extension/version: ADBLOCK PLUS 3.8

**Comment by THEtomaso** [comment]
Didn't you notice this report?:
https://github.com/easylist/easylist/issues/5112/

**Comment by JasonConners** [comment]
> Didn't you notice this report?:
> #5112

Yes in fact I did and they are not the same issues so what are you talking about hm??? My YouTube works fantastically unlike the post your are referring to. However, my tv.youtube has issues due to the easylist.

Thanks micropoliceofficer.

**Comment by THEtomaso** [comment]
So, this rule doesn't fix the playback issue at `tv.youtube.com`?:
`||youtube.com/get_video_info?$domain=youtube.com,badfilter`

**Comment by JasonConners** [comment]
I'll try it out when I get back home. If it works then I don't understand why everything works fine on regular YouTube.com and only TV is affected. I'll be home in about an hour.

**Comment by THEtomaso** [comment]
Read the report which I refered to in my first post.
`youtube.com` is unaffected, but all embedded videos are broken!
Even though `tv.youtube.com` is the same domain as `youtube.com`, it's a subscription service, and is most likely broken by the same problem rule.

**Comment by ryanbr** [comment]
Have removed filter.
