### ISSUE TITLE
tv.youtube.com (YouTube TV) broken after latest easylist update

### ISSUE THREAD

**Issue by GitYukari** [easylist/easylist#5114]
Continuation of the issue here, but new issue: https://github.com/easylist/easylist/issues/5112

### List the website(s) you're having issues:

tv.youtube.com

### What happens?

Attempting to load any channel results in the following error:
An error occurred. Please try again later.

![image](https://user-images.githubusercontent.com/8529616/77275726-693dc380-6c8f-11ea-889e-d5a5139efd46.png)

This was not an issue prior to updating the easylist filter tonight, and it is a direct result of the latest update in the prior mentioned closed issue. When the list is removed, YouTube TV loads successfully.

### List Subscriptions you're using:

Easylist

### Your settings

OS/version: Windows 10 November 2019 Update
Browser/version: Chrome 80.0.3987.149 64-bit
Adblock Extension/version: Nano Adblocker 1.0.0.140

### Other details:

![image](https://user-images.githubusercontent.com/8529616/77275913-c9346a00-6c8f-11ea-91df-b5e358c67c91.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a621dca8b2
