### ISSUE TITLE
*.onet.pl (wiadomosci, facet, sport, kultura, podroze) + plejada.pl [EasyPrivacy] [breakage]

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#5117]
As an appendix to https://github.com/easylist/easylist/issues/5109 and https://github.com/easylist/easylist/issues/5101 (can't comment in his issues coz he banned me in the past): 
- affected subdomains: `wiadomosci.onet.pl` `facet.onet.pl` `kultura.onet.pl` `sport.onet.pl` `podroze.onet.pl` + `plejada.pl` 
- this domain: `pulsembed.eu` can be added (moved from https://github.com/uBlockOrigin/uAssets/commit/a43b37b55ec2e615d94e4b7fbc1fcdde1e2334b3) into the whitelist filter as well, so the temporary whitlelist filter from uAssets can be removed then later.

**Comment by 646e5stdessd** [comment]
`auto-swiat.pl` also have broken player and images.
