### ISSUE TITLE
wordpress jetpack-social-navigation

### ISSUE THREAD

**Issue by PredatorCZ** [easylist/easylist#5138]
### List the website(s) you're having issues:
Some themes for wordpress in general.
This as example: lukascone.wordpress.com

### What happens?
fanboy_social_general_hide.txt includes hiding rule for jetpack-social-navigation class.
This class is used for social links only, put by the author of the site/blog. In example site, they are stored in the right top corner. The wordpress staff has confirmed (in this post [https://en.forums.wordpress.com/topic/jetpack-social-navigation-problems-with-hiding/#post-3455976](https://en.forums.wordpress.com/topic/jetpack-social-navigation-problems-with-hiding/#post-3455976)), that such class is used only for this purpose.

Please consider adding exception.

### List Subscriptions you're using:
fanboy_social_general_hide

### Your settings

- OS/version: Ubuntu, Win7
- Browser/version: Firefox, latest
- Adblock Extension/version:  Adblock Plus, latest

**Comment by krystian3w** [comment]
IMO no worth, use other plugin for nor social links?
