### ISSUE TITLE
EasyPrivacy breaks lenovo.com product browsing

### ISSUE THREAD

**Issue by franglais125** [easylist/easylist#5139]
https://www.lenovo.com/ca/en/laptops/thinkpad/thinkpad-t-series/T495/p/22TP2TTT495

Using the EasyPrivacy list cripples this website, it is not possible to browse products, see descriptions or buying online.

This started happening in the last week.

I use uBlock Origin on Firefox, with:
- Built-in filters
- EasyList
- EasyPrivacy

Deactivating EasyPrivacy solves the issue.

**Comment by llacb47** [comment]
`@@||lenovo.com/_ui/desktop/common/js/AdobeAnalyticsEvent.js$script,~3p`

**Comment by krystian3w** [comment]
why not `1p`? ABP don't support short `~3p`
