### ISSUE TITLE
EasyList blocks the updates

### ISSUE THREAD

**Issue by ArmynC** [easylist/easylist#5168]
### List the website(s) you're having issues:

uBlock's dashboard:

`https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/antiadblock.txt`
`https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/antiadblock.txt`
`https://raw.githubusercontent.com/Yhonay/antipopads/master/popads.txt`

### What happens?

EasyList is blocking the update of these specific filters via:

```
/antiadblock.
/popads.
```

### List Subscriptions you're using:

[My Filters](https://github.com/ArmynC/ArminC-uBlock-Settings)

### Your settings

- OS/version: Windows 7
- Browser/version: Chrome Version 80.0.3987.149
- Adblock Extension/version: uBlock Origin 1.24.5b4

### Other details:
![Capture](https://user-images.githubusercontent.com/16375271/77820823-e1701300-70ed-11ea-9fc5-4d2c275ca4dc.PNG)

**Comment by krystian3w** [comment]
You broke uBO setup in `My whitelist` / `my rules` ...

default disable these troubles.

---

Whitelist:

```
about-scheme
chrome-extension-scheme
chrome-scheme
edge-extension-scheme
edge-scheme
moz-extension-scheme
ms-browser-extension-scheme
opera-scheme
vivaldi-scheme
wyciwyg-scheme
```

My rules:

```
no-large-media: behind-the-scene false
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop
```

**Comment by krystian3w** [comment]
Also no recommend load  template files:

```
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/antiadblock.txt
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/antiadblock.txt
```

AdGuard sometime use no supported exeptions:

`!+PLATFORM(ext_ublock)`

`!+ NOT_PLATFORM(ext_ublock)`

**Comment by ArmynC** [comment]
Right, I hadn't even noticed the `#`.

About that Filters, I know. These are just temporary. I had a problem with a website and these are updated faster than the main one.

Thanks!

**Comment by krystian3w** [comment]
> these are updated faster than the main one.

3 hours is not a lot, it's no worth to wait than to push on a mine with "+Platform / + Not_Platform".

**Comment by ArmynC** [comment]
Yes, I understand. From yesterday I tried to analyse them, firstly it was a better choice, select the prefered filters, slimmer outcome, but, I saw some inconsistency in the filters too (and also your reasons). So I pushed a commit with the main filters instead & fixed the settings. Thanks!
