### ISSUE TITLE
False postivie: clarity-labs.kaminario.com

### ISSUE THREAD

**Issue by haizaar** [easylist/easylist#517]
Good day,

`clarity-labs.kaminario.com` domain matches `clarity-*.js` pattern and it's not possible to load any scripts from it. This is our storage analytics platform. Is it possible to unblock the domain? Or even better the whole `clarity-*.kaminario.com` domain?

**Comment by haizaar** [comment]
Can you please elaborate on a reason closing? The problem still exists.

**Comment by Khrin** [comment]
Sorry, at first this website didn't loaded at all and I thought that by now was dead for good. https://github.com/easylist/easylist/commit/78538123239bc1c8a9576d8e58a820974cc17635

**Comment by haizaar** [comment]
Perfect. Thank you!
