### ISSUE TITLE
topads.me

### ISSUE THREAD

**Issue by davidevaliante** [easylist/easylist#5170]
### List the website(s) you're having issues:
URL : `www.topads.me`

### What happens?

Due to the domain name (that is the name of the company so it's impossible to change) JS and images are being blocked

### List Subscriptions you're using:

AdBlock default list

### Your settings

- OS/version: Windows 10 
- Browser/version: chrome 80
- Adblock Extension/version: AdBlock 4.8.0

### Other details:

those are the resources being blocked : 
![Cattura](https://user-images.githubusercontent.com/22818612/77821204-9a335380-70e8-11ea-81ae-379fabb5d3ce.PNG)

**Comment by spirillen** [comment]
@krystian3w why did you give him a :-1: ? you should give him a :+1: for [warning](https://www.mypdns.org/T480) us about him self :rofl:

**Comment by krystian3w** [comment]
Possible use CDN or base64 to encode all resources.

**Comment by davidevaliante** [comment]
> @krystian3w why did you give him a 👎 ? you should give him a 👍 for [warning](https://www.mypdns.org/T480) us about him self 🤣

do you realize that this is a landing page of legally registered society in malta and not an adware right ?

**Comment by spirillen** [comment]
![image](https://user-images.githubusercontent.com/44526987/77858618-de1b7b00-7204-11ea-903b-165d7a4e3c04.png)

**Comment by davidevaliante** [comment]
> ![image](https://user-images.githubusercontent.com/44526987/77858618-de1b7b00-7204-11ea-903b-165d7a4e3c04.png)
> 
> So basically you also support tax evasion!!

are you out of you mind ???? what the hell are you even talking about ???

**Comment by krystian3w** [comment]
Then let them fire me for insult / slander.

Github doesn't have my personal data, and my ISP doesn't have my data either...

**Comment by Khrin** [comment]
@spirillen / @krystian3w I don 't like your messages, I ask both of you please refrain to attack other users.

@davidevaliante I appreciate you've already found a fix for your site, anyway I've added an exception for it.
