### ISSUE TITLE
snrcdn.net 

### ISSUE THREAD

**Issue by trackerless** [easylist/easylist#5172]
### List the website(s) you're having issues:
```
https://www.ikea.bg/
https://born2be.pl/register
https://www.cobone.com/en/deals/dubai
https://tipanddonation.com/
https://www.epantofi.ro/
https://www.avans.pl/
https://www.eobuv.sk/
https://www.ikea.bg/
https://www.orange.pl/
```

### What happens?
Synerise Tracker is not blocked.

### List Subscriptions you're using:
EasyPrivacy

### Your settings
uBlock

- OS/version: Ubuntu 18.04
- Browser/version: Chrome, Latest
- Adblock Extension/version: uBlock 1.24.4

### Other details:
Following rule should resolve issue
||snrcdn.net

**Comment by Khrin** [comment]
This looks like more a CDN-related domain.

**Comment by llacb47** [comment]
Yeah, a CDN for Synerise, a tracking company. https://synerise.com/

**Comment by Khrin** [comment]
Of course, it could well be. `https://upload.snrcdn.net/bb35597c84532c975318390cd7ba2d9bb631233c/default/origin/1423dec5616737285fbc37203578f02e.pdf`

**Comment by llacb47** [comment]
`https://bgp.he.net/dns/snrcdn.net`

![image](https://user-images.githubusercontent.com/16567977/77972905-b12c9e00-72c0-11ea-8576-ae390619a391.png)

**Comment by trackerless** [comment]
Can we block instead:
`snrcdn.net/sdk/` ?
