### ISSUE TITLE
ekskluzywna.pl tracking

### ISSUE THREAD

**Issue by trackerless** [easylist/easylist#5173]
### List the website(s) you're having issues:
```
https://ekskluzywna.pl/
https://botland.com.pl/pl/
```

### What happens?
Latest gemius script is unblocked, because it is not gemius.js but gemius.3.15.js
My proposition is to block /gemius path globally.

### List Subscriptions you're using:
Easy Privacy

### Your settings
uBlock

- OS/version: Ubuntu 18.04
- Browser/version:  Chrome latest
- Adblock Extension/version: uBlock latest

### Other details:
/gemius

**Comment by krystian3w** [comment]
> Other details:
> 
> `/gemius`

too generic, down many players used gemius for someting (embeded ads?)...

**Comment by trackerless** [comment]
Well, keep in mind that lots of filters provided by EasyList are generic. For example:
```
/wwwad.
/wwwads.
/adnexus-
```

Gemius is trademark and does not exists in any dictionary. If asking me it is as generic as "adnexus".

That script is just another tracker owned by data-mining company: 
```
http://www.gemius.pl/dzial-analiz.html
http://www.gemius.pl/dzial-it.html
```

**Comment by Khrin** [comment]
Better not to be too much generic, in my opinion.
