### ISSUE TITLE
swogo.net

### ISSUE THREAD

**Issue by trackerless** [easylist/easylist#5175]
### List the website(s) you're having issues:
```
https://www.kotsovolos.gr/BasketDisplay?catalogId=10551&langId=-24&storeId=10151&krypto=WRKnJCx7ZphDzt95jSxqPRu4KJaOSVth16ytHiLP9VcrzacGtBFC20NlzvDDtACDgSoeVY3zygCfoqpKI11UaHD0mafDQCS%2B7VHGMmy3ZyKiYcBwjmIEjx1BWJLGR2qumTXVPQ9CGyrofZGt2dqsxtfLhYPJ2aY3iuHflJaW6YP8hzXQKrSW7fEeqLjMPnpCmdleVISX0soYhLB9tMxM%2Bzzk42qfbZOdS3zO6OJjUjQjbRffRyAwilduB10Q2lyxnZboUALJ%2BslSakSBf351iw%3D%3D
```

### What happens?
Swogo Tracker is not blocked.

### List Subscriptions you're using:
EasyPrivacy

### Your settings
uBlock

- OS/version: Ubuntu 18.04
- Browser/version: Chrome, Latest
- Adblock Extension/version: uBlock 1.24.4

### Other details:
Following rule should resolve issue
||ui.swogo.net
||tracking.swogo.net

**Comment by ryanbr** [comment]
`https://ui.swogo.net/bundles/v4/kotsovolosGr/A/basket.js`  Does seem that trackerish

**Comment by trackerless** [comment]
That is tracker main script:
`https://ui.swogo.net/bundles/v4/kotsovolosGr/swogo.js`
and that is request, which that script is firing:
`https://tracking.swogo.net/?Y2xpZW50JTNEa290c292b2xvc2dyXzE0NCUyNnZhcmlhbnQlM0RBJTI2b3JpZ2luJTNEYmFza2V0JTI2dXNlciUzRGFub24uQ0VOU09SRUQlMjZ0eXBlJTNEYmFza2V0TGlzdCUyNmJ1bmRsZURhdGElM0QlMjU1QiUyNTdCJTI1MjJpZCUyNTIyJTI1M0ElMjUyMjE1NDM5MSUyNTIyJTI1MkMlMjUyMnByaWNlJTI1MjIlMjUzQTc5JTI1MkMlMjUyMnRpdGxlJTI1MjIlMjUzQSUyNTIySFAlMjUyMERlc2tqZXQlMjUyMEluayUyNTIwQWR2YW50YWdlJTI1MjAzODM1JTI1MjIlMjU3RCUyNTVE`

which after decoding means:
`client=kotsovolosgr_144&variant=A&origin=basket&user=anon.CENSORED&type=basketList&bundleData=%5B%7B%22id%22%3A%22154391%22%2C%22price%22%3A79%2C%22title%22%3A%22HP%20Deskjet%20Ink%20Advantage%203835%22%7D%5D`

And yes, it is tracker.

If asking me, blocking main script (and preferably the entire subdomain) used for loading main script is the only block acting in the long run.

It is much harder to force clients to change the script than to change the flag.
