### ISSUE TITLE
freepik.com

### ISSUE THREAD

**Issue by meirroth** [easylist/easylist#5177]
### List the website(s) you're having issues:
`https://www.freepik.com/`

### What happens?
Keep getting banners pop-ups and ads on this site.

### List Subscriptions you're using:

All the lists in uBlock Origin are active
### Your settings

- OS/version: W10 64bit
- Browser/version: Microsoft Edge. Version 80.0.361.69 (64-bit)
- Adblock Extension/version: uBlock Origin 1.23.0

### Other details:
[screenshot](https://cdn1.imggmi.com/uploads/2020/3/30/a6b4d6b066a2d7ff119590a4f473d9f6-full.png)
[screenshot](https://cdn1.imggmi.com/uploads/2020/3/30/535f67d0689e70608427d0a4e38a3e6e-full.png)
[screenshot](https://cdn1.imggmi.com/uploads/2020/3/30/13c5cfd3e56b691fc27752ad2e7af006-full.png)

**Comment by ryanbr** [comment]
Those are self promos.
