### ISSUE TITLE
[NSFW]narcovip.com

### ISSUE THREAD

**Issue by PentagramTr** [easylist/easylist#5178]
### List the website(s) you're having issues:

**NSFW**   `http://narcovip.com/citir-sut-beyazi-karisini-izlemekten-zevk-aliyor/`

### What happens?

Video player is not visible.

### List Subscriptions you're using:

AdGuard Base-AdGuard Social Media-AdGuard Tracking Protection-AdGuard Annoyances-NoCoin Filter

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 74.0 (64 bit)
- Adblock Extension/version: AdGuard extension 3.4.11

### Other details:

Problematic rule : `|https://$image,script,subdocument,third-party,domain=vidoza.co|vidoza.net`
PR : https://github.com/easylist/easylist/pull/3438

<details><summary>Enable:</summary>

![Screenshot_2020-03-31 Çıtır Süt Beyazı Karısını İzlemekten Zevk Alıyor Narcovip - Türk Porno, Türk ifşa, Türkçe altyazılı p (1)](https://user-images.githubusercontent.com/34379403/77963646-67ef4500-72e6-11ea-99e4-a834c92d4696.png)

</details>
<details><summary>Disable:</summary>

![Screenshot_2020-03-31 Çıtır Süt Beyazı Karısını İzlemekten Zevk Alıyor Narcovip - Türk Porno, Türk ifşa, Türkçe altyazılı p](https://user-images.githubusercontent.com/34379403/77963664-70e01680-72e6-11ea-9c1a-310580ebb4f3.png)

</details>

**Comment by ryanbr** [comment]
I can see the video @PentagramTr

**Comment by PentagramTr** [comment]
@ryanbr 
Thanks, but I still can't see the video. Can you try again with VPN, please? Because I can only access this site with a VPN.

Video
https://streamable.com/rmqou

**Comment by PentagramTr** [comment]
This is an unimportant website and has low daily visitor. So I closed the report.
