### ISSUE TITLE
A: symbolab.com (again)

### ISSUE THREAD

**Issue by Crystal-RainSlide** [easylist/easylist#5179]
### List the website(s) you're having issues:

`https://www.symbolab.com/`
`https://www.symbolab.com/solver/functions-calculator`

### What happens?

Elements and tracker found on this website.

See https://github.com/uBlockOrigin/uAssets/issues/5124#issuecomment-606555121

Also, search `AdBlock` or anything in `https://www.symbolab.com/public/auto/solutions.min.js` with tool like [Online JavaScript Beautifier](https://beautifier.io/), if anyone would like to check it out by themselves.

Related:
https://github.com/easylist/easylist/issues/4967
https://github.com/easylist/easylist/pull/4974
https://github.com/uBlockOrigin/uAssets/issues/5124

### List Subscriptions you're using:

uBlock Origin with:
- all the uBlock filters
- Fanboy Complete List ([Fanboy+Easylist-Merged Complete List](https://secure.fanboy.co.nz/r/fanboy-complete.txt))

### Your settings

- OS/version: Desktop
- Browser/version: Firefox last release
- Adblock Extension/version: uBlock Origin

#### Related lists:

- [uBlock filters](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt) (main)
- [Problematic websites List](https://fanboy.co.nz/fanboy-problematic-sites.txt)

#### Rules:

To EasyList:

```
symbolab.com###googleAdSenseHomepage
symbolab.com##.googleAdsense
symbolab.com##.googleAdsenseMiddle
symbolab.com##.googleLeftSkyScrapper
symbolab.com#?#.tooltipster-show:-abp-has(.abmsg)
```

To EasyPrivacy:

```
||symbolab.com/detailedLog$xmlhttprequest
```

#### Note

There are `zs.symbolab.com` and so on, just use `symbolab.com` but not `www.symbolab.com`.

**Comment by ryanbr** [comment]
Seems fine? Only saw `symbolab.com##.googleLeftSkyScrapper`  I've seen far worse ad-ridden sites 

![sym](https://user-images.githubusercontent.com/1659004/79040469-c00a3d80-7c3c-11ea-860e-2f92dc7a39ed.png)

**Comment by Crystal-RainSlide** [comment]
#googleAdSenseHomepage is at `https://www.symbolab.com`, and just add the rules you think are appropriate, as the overall status is truly fine. I just digged every rule I can reach for block.

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5124#issuecomment-606693820
