### ISSUE TITLE
stihl.fr

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5180]
### List the website(s) you're having issues:

`https://www.stihl.fr/un-bon-equipement-de-protection-pour-utiliser-une-tronconneuse-stihl.aspx`

### What happens?

The easylist cookie subscription is causing a grey overlay on the whole website

### List Subscriptions you're using:

easylist cookie + fr
### Your settings

- OS/version: 
- Browser/version: ff 74
- Adblock Extension/version:  ublock origin

**Comment by ryanbr** [comment]
Can you see this @smed79 ? I'm not seeing any cookie notices here

**Comment by momala454** [comment]
![image](https://user-images.githubusercontent.com/83005/79225254-bf4ff200-7e5c-11ea-84bc-f7f8edd61251.png)

**Comment by smed79** [comment]
@ryanbr I am unable to reproduce.

@momala454 Submit an **Adblock Plus** [issue report](https://help.eyeo.com/en/adblockplus/report-an-issue) an past the link here, so that we can investigate.

**Comment by momala454** [comment]
why adblock plus ? i'm using ublock origin

**Comment by smed79** [comment]
@okiehsch Could you investigate please.

**Comment by kulfoon** [comment]
I basically can't reprodce as well.

> ### List Subscriptions you're using:
> 
> easylist cookie + fr

However I can reproduce if following strictly what is written above, which means having enabled easylist cookie + fr only (or at least these 3 disabled: EasyList, EasyPrivacy, uBlock Privacy or alternativiely an exception added: `@@||www.googletagmanager.com/gtm.js$script,domain=www.stihl.fr`), which basically means it can be reproduced if `www.googletagmanager.com/gtm.js` request is allowed. Which is related to 

<details not-open>
<summary>this code:</summary>


```
<!-- Google Tag Manager -->
<
script >
    if (allowGTMCookies === true) {
        (function(w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s),
                dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src = '//www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-NV7MKV');
    } <
    /script> <
    !-- End Google Tag Manager -->
```

</details>

Hence I wonder whether the OP meant that he has enabled easylist cookie + fr **only** or together with other default uBO lists  (EasyList, EasyPrivacy, uBlock Privacy etc.). 

If the first case, that's strange, coz nobody disables main lists like EasyList, coz EasyList Regional (for. ex. FR) are to be used as a supplement to the main EasyList, and not as a replacement, thus one should still have EasyList enabled when using together with a regional EasyList list.

If the second case, also strange, coz the issue can't be reproduced having EasyList and/or EasyPrivacy and/or uBlock Privacy enabled.

There is also a third case possibility, perhaps the OP has accidentally an exception filter (allowing
`www.googletagmanager.com/gtm.js` request) enabled somewhere in his "My Filters".

A fourth case possibility would be that something in the webpage has changed meanwhile and the issue can't be reproduced anymore.

**Comment by momala454** [comment]
![image](https://user-images.githubusercontent.com/83005/79898418-88a14b00-840b-11ea-9eca-55121990c382.png)


i don't have "googletagmanager" on my filters

**Comment by okiehsch** [comment]
With that rather unique setup I can reproduce.
If you wnat to keep it add
`stihl.fr##.optin`
to your filter list.

**Comment by kulfoon** [comment]
A correction from my side, yes, indeed, have checked again and don't need to disable EasyList to reproduce, as it doesn't block GTM requests, so only need to disable EasyPrivacy and uBlock Privacy to reproduce the issue.

**Comment by momala454** [comment]
so your solution is to block tracking on list that shouldn't block tracking ?
