### ISSUE TITLE
investors.com promoted content

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#52]
`http://www.investors.com/`
`http://www.investors.com/politics/editorials/clinton-e-mail-scandal-hillary-could-face-a-10-year-prison-stint-if-her-server-was-hacked/`

Promoted content by Jensen Investment Management/Williams, Williams & Mckissick

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/be470b0cf30e7d6eaf6363f280512e5bdfd92a6b
