### ISSUE TITLE
Easylist breaking gazzetta.it

### ISSUE THREAD

**Issue by ermescs** [easylist/easylist#5201]
List the website(s) you're having issues:
https://www.gazzetta.it

What happens?
When I ask for the homepage an anti ad blocker shows up.

List Subscriptions you're using:
Easylist

Your settings
OS/version: Windows 10
Browser/version: Chrome 80.0.3987.149
Adblock Extension/version: uBlock Origin 1.24.4
Please note that the same happens with other OS/Browser/Extension configurations.

Other details:
The rules breaking the website is the following one
/openx/*

**Comment by llacb47** [comment]
Easylist doesn't fix anti-adblock, update your filter lists and make sure you are subscribed to italian regional lists.
