### ISSUE TITLE
clubic.com

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5202]
### List the website(s) you're having issues:

`https://www.clubic.com/pro/entreprises/amazon/actualite-890664-association-doigt-amazon-livre-produits-hors-hygiene-alimentaire.html`

### What happens?

the twitter integration is half broken, the images from twitter are not shown and it's displayed differently

### List Subscriptions you're using:

easylist fr, easylist cookie

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Is this still happening @momala454  ? I can't reproduce in Easylist / Easylist Cookie

**Comment by momala454** [comment]
yes i cleared the browser cache, and i'm using firefox, and the embed twitter only show raw text instead of having the frame + the embedded image

i see that the easylist fr list have the filter 

> ://syndication.$3p

which block `https://syndication.twitter.com/i/jot?l=%7B%22widget_origin%22%3A%22https%3A%2F................`

**Comment by momala454** [comment]
it works now after  disabling/reenabling ublock, but not if i open a private browsing window. it's strange

**Comment by momala454** [comment]
could be caused by firefox built in tracking protection

**Comment by momala454** [comment]
another example

https://www.clubic.com/aeronautique/actualite-892097-coronavirus-avions-bondes-controle-aeroports-mauvais-exemple-secteur-aerien.html

on firefox, ublock origin

![image](https://user-images.githubusercontent.com/83005/79692665-bdc06880-8266-11ea-9d7e-f9dabf7279b4.png)

i think the request is blocked to https://platform.twitter.map.fastly.net/ due to the following filter on easylist fr : 

`/^((?!(^https?):\/\/(([0-9a-z\.\-]+)\.(20mn\.fr|axept\.io|axeptio\.eu|beop\.io|beopinion\.com|coralproject\.net|disquscdn\.com|doyoudreamup\.com|jokerly\.com|netdna-ssl\.com|nexcesscdn\.net|og4\.me|qualifio\.com|qualifioapp\.com|wp\.com)|([0-9a-z]+\.)?disqus\.com|(ajax|cdnjs)\.cloudflare\.com|(ajax|maps|storage)\.googleapis\.com|api\.(viafoura\.co|viafoura\.com)|(apis|plus|www)\.google\.com|(api|assets|cdn)\.poool\.fr|(api|de|en|fr|www)\.tipeee\.com|(api|assets)\.pinterest\.com|(api|cdn|cdn1|cdn2|cdn3|cdn4)\.wibbitz\.com|(api|static1)\.dmcdn\.net|(assets|secure\.assets)\.tumblr\.com|(beta|www)\.qiota\.com|(cdn-us|embed)\.air\.tv|(cdn\.digitrust|quantcast|static\.quantcast)\.mgr\.consensu\.org|art19\.com|builder-assets\.unbounce\.com|castbox\.fm|cdn-files\.prsmedia\.fr|(cdns|cdns2|cdns\.eu1)\.gigya\.com|sdk-gcp\.privacy-center\.org|(embedr|widgets)\.flickr\.com|(i|s)\.po\.st|(maxcdn|stackpath)\.bootstrapcdn\.com|(odb|storage|widgets)\.outbrain\.com|(platform|www)\.instagram\.com|(secure|www)\.ultimedia\.com|(staticxx|www)\.facebook\.com|(tel\.cdn|tra\.scds)\.pmdstatic\.net|api\.matchchat\.co\.uk|app\.viewdeos\.com|assets\.(afcdn\.com|reach5\.co)|build\.suggestv\.io|cdn\.([0-9a-z]+)\.nicematin\.com|cdn\.(polyfill\.io|syndication\.twimg\.com|viafoura\.net)|(cdn|trc)\.taboola\.com|code\.jquery\.com|(staticxx|www)\.facebook\.com|connect\.facebook\.net|content\.jwplatform\.com|e\.infogr\.am|embed\.waze\.com|graphcomment\.com|hap\.h-cdn\.com|images\.marmitoncdn\.org|js\.stripe\.com|jwpsrv\.com|mb\.pixel\.swello\.com|p\.monetico-services\.com|paiement\.creditmutuel\.fr|platform\.twitter\.com|player\.(acast\.com|pippa\.io|vimeo\.com)|players\.brightcove\.net|po\.st|rcijeux\.fr|ressources\.regionsjob\.com|s\.pinimg\.com|s\.ytimg\.com|sadmin\.brightcove\.com|scontent-rtl\.akamaized\.net|sdk\.privacy-center\.org|snapwidget\.com|ssl\.p\.jwpcdn\.com|static\.(afcdn\.com|allovoisins\.com|bfmtv\.com|lephoceen\.net|mmzstatic\.com)|twitter\.com|use\.edgefonts\.net|vjs\.zencdn\.net|widget\.(ausha\.co|beopinion\.com|crowdleap\.com)|widgets\.snack-projects\.co\.uk|www\.(bloglovin\.com|dailymotion\.com|httpcs\.com|radioking\.com|rtl\.be|stanza\.co|youtube\.com|zap-tele\.com))\/).*)$/$script,3p,domain=alfemminile.com|alsumaria.tv|americanlisted.com|arcinfo.ch|astucesexpress.com|audiofanzine.com|aufeminin.com|aujourdhui.com|autojournal.fr|autoplus.fr|basketusa.com|betaseries.com|bibamagazine.fr|blog-rct.com|butfootballclub.fr|cabaneaidees.com|caradisiac.com|chezasite.com|clubic.com|collegehumor.com|cuisineaz.com|direct-radio.fr|eclypsia.com|enfemenino.com|enfermeriahoy.com|familyhandyman.com|focus-numerique.com|football365.fr|fourchette-et-bikini.fr|gofeminin.de|grands-meres.net|hommedumatch.fr|journaldugeek.com|ketoconnect.net|lacote.ch|ladepeche.fr|ledauphine.com|lenouvelliste.ch|lephoceen.fr|leprogres.fr|lequipe.fr|lesoir.be|letribunaldunet.fr|lippycorn.com|livepeople.fr|madmoizelle.com|maison-et-domotique.com|marmiton.org|mcetv.fr|mercato365.com|mjsbigblog.com|monacomatin.mc|netmums.com|nicematin.com|nrj-play.fr|obsev.com|ofeminin.pl|olhardigital.com.br|paroles-musique.com|passeportsante.net|planificacionmedios.com|portail.free.fr|recreatisse.com|republicain-lorrain.fr|rugby365.fr|science-et-vie.com|sofeminine.co.uk|sofoot.com|sport365.fr|sportauto.fr|supertoinette.com|taofeminino.com.br|telechargerunevideo.com|thecelticblog.com|thelovenerds.com|tuttogusto.it|ultimate-catch.eu|universfreebox.com|varmatin.com|viedemerde.fr|weather-wherever.co.uk|wewomen.be|worldfreeware.com`

**Comment by Khrin** [comment]
@smed79

**Comment by momala454** [comment]
which commit did fixed it ?

**Comment by smed79** [comment]
No issue here with Liste FR enabled https://imgur.com/6ogKFGN.png

**Comment by momala454** [comment]
yes it works now i don't know what fixed it
