### ISSUE TITLE
[NSFW] anyporn.com

### ISSUE THREAD

**Issue by easylistuser** [easylist/easylist#5212]
### List the website(s) you're having issues:
`https://anyporn.com/search/searchword`

### What happens?
When you search for a word of your choosing (like the placeholder "searchword" in the link above), the thumbnails on the results page won't be shown. This happens exclusively with searches, otherwise the thumbnails on this site appear as intended.

### List Subscriptions you're using:
Easylist
Easylist Germany
Peter Lowe's list
Adguard Base
Adguard Tracking
Adguard Annoyances
uAssets/uBlock filter family
Adblock Warning Removal

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 75.0
- Adblock Extension/version: uBlock Origin 1.26.0

### Other details:
The filter causing the false positives is this one:
`||anyporn.com^$image,script,subdocument,xmlhttprequest`

Screenshot of `https://anyporn.com/search/searchword` with Easylist being active:
https://user-images.githubusercontent.com/63377345/78908719-c81e7d80-7a82-11ea-84a1-bc4b99079ba1.png
The uBlock logger:
https://user-images.githubusercontent.com/63377345/78908779-e4221f00-7a82-11ea-93d5-5a18905b3aa9.JPG

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/78857848-8c3ed600-79f8-11ea-88b2-ba75fafd9055.png)

**Comment by easylistuser** [comment]
@llacb47 I've renewed the links.
