### ISSUE TITLE
Blocked blob URL popups break HTML5 features on all sites

### ISSUE THREAD

**Issue by chr15m** [easylist/easylist#5213]
### List the website(s) you're having issues:

Any website where windows are opened with `blob:...` URLs.

### What happens?

The window is instantly closed.

![adblocked2](https://user-images.githubusercontent.com/67130/78955615-555ce300-7b12-11ea-81b4-e073fb449707.gif)

### List Subscriptions you're using:

uBock Origin with the default settings:

* uBlock filters​
* uBlock filters – Badware risks​
* uBlock filters – Privacy​
* uBlock filters – Resource abuse​​​​​
* uBlock filters – Unbreak
* AdGuard Base​
* AdGuard Mobile Ads
* EasyList
* EasyPrivacy​    ​​ 
* Malware Domain List
* Peter Lowe’s Ad and tracking server list​

### Your settings

- OS/version: Ubuntu 14.04
- Browser/version: Firefox and Chrome
- Adblock Extension/version: uBlock Origin on Firefox, Ad Block Plus on Chrome. Both use Easylist.

### Other details:

On Firefox with uBlock Origin they open ok if they are plain `hrefs` and you ctrl-click to open a new window, not with `window.open` though. On Chrome with Ad Block Plus they don't open at all.

I see EasyList as the culprit in the uBlock logs:

![image](https://user-images.githubusercontent.com/67130/78955412-ca7be880-7b11-11ea-9e32-bf1fdb4c6263.png)

And I found the line which caused the block in the easylist source here:

https://github.com/easylist/easylist/blob/7f01c6031cc379d3f3ee48b33c58c0965f0f03b2/easylist/easylist_general_block_popup.txt#L131

### Some context for why I think this broad-based `blob` URL popup blocker is harmful.

Browsers block popups that are not triggered by a user action. This is sensible - you don't want a site to be able to open windows any time they like with no user action. Blocking blob URLs when a user triggers them, I think is a mistake. It shuts down a class of innovative new web apps from being built - any app where the content is stored primarily in the browser itself and served from there rather than a domain.

I am building an open source tool which has nothing to do with advertising. It is a simple web based IDE that people can host on their own domain. It is intended to help beginner programmers (such as my own kids) to build their first web pages without requiring them to upload HTML to a server etc. It requires the opening of blob URLs because all of the coding is done inside a CodeMirror editor inside the browser itself. When the person changes their file and hits "save" the alternative window shows a live-reloaded version of their app updated. I am making this to help people and it's frustrating that they will have to fight with the ad blocker in order to get the core functionality working. To give you an idea of the functionality I am enabling, here is the live reloading of code working with EasyList disabled:

![slingcode-live-reloading](https://user-images.githubusercontent.com/67130/78956950-82ab9000-7b16-11ea-8b12-b857c3e03e2e.gif)

The browser window on the left is the web app which is self-hosted by the user, and the window on the right is the blob URL opened window which is updated when they edit and then "save" the code.

Thank you very much for maintaining EasyList, I appreciate all of your hard work keeping people on the internet safe. I hope we can figure out a way to let real non-abusive uses of the blob URL to flourish without being blocked. :pray:

**Comment by ryanbr** [comment]
I'll review this filter later, this is a temp fix.
