### ISSUE TITLE
downloadhub.life 

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#5214]
### List the website(s) you're having issues:

 URL(s)=

`https://downloadhub.life/asteroid-final-impact-2015-hindi-dual-audio-720p-webrip-esubs/`

### What happens?

Download functionality(click on single download links) is broken on website due to easylist filter `||onlineshopping.website^$popup,3p`

### Your settings

- OS/version: win 10
- Browser/version: opera browser
- Adblock Extension/version: ublock origin 1.25.2

**Comment by ryanbr** [comment]
Funny how this "Shopping site" turned up on another site when it was committed. https://github.com/easylist/easylist/commit/c79d783d00d   This seems to be dodgy.

**Comment by spirillen** [comment]
I would say the `onlineshopping.website` looks mostly like a "faked" frontend for the real AdWare  and/or TrackWare domain, trying to keep us from blocking them, but as I recall this domain from several issues around git(lab|hub) I simply going to [block](https://www.mypdns.org/T573) them entirely, as I can't see they are contributing/distributing any real useful bits...

But it's not up to me, what happens on EasyList, but it's my opinion about this domain, and if it breaking sites, it's not any important site as the OP's links proves, and the impact would therefore be insignificant.

**Comment by Khrin** [comment]
I haven't seen any hits for this filter, nor I've seen any real "download" links there.

**Comment by llacb47** [comment]
`https://downloadhub.life/operation-gold-fish-2019-hindi-dual-audio-350mb-uncut-hdrip-480p-esubs/` Gdrive download blocked by this filter

**Comment by Khrin** [comment]
Not for me, still is redirecting to random sites.

**Comment by llacb47** [comment]
@Khrin Watch this screen recording: https://streamable.com/moxl39

The site seems to have worked around the breakage with an alternate server.

**Comment by ghajini** [comment]
> Not for me, still is redirecting to random sites.

You mean popups on site,use ubo, browse site click single download links & there you go

**Comment by ghajini** [comment]
Well time to ping @mapx-

**Comment by ikramms212** [comment]
download.life is an expired domain. this was owned by downloadhub.ws this is a pirated content website if you don't know that downloadhub is an illegal website so if you want to know more about please visit [downloadhub 2020](https://watchmoviesonline.in/downloadhub/)
