### ISSUE TITLE
Please consider removing stat-track.com as a Fingerprinter

### ISSUE THREAD

**Issue by yannnis** [easylist/easylist#5215]
Hi all,

It has come to our attention that stat-track.com was classified as a Fingerprinter because it was referencing a redundant library that we were using.

The script was used to create a unique user id so that no other personal information was stored and captured. However, that beacon and the data it produces was never used. In fact, we have disabled that beacon and it should no longer get deployed on any traffic. Overall, that domain is part of Moosend.com and implements various types of subscription forms for websites (https://moosend.com/subscription-forms/).

Could you re-consider your classification please?

Disconnect me has also removed the domain from their list of fingerprinters: 

https://github.com/disconnectme/disconnect-tracking-protection/commit/5e0cedd7bc5c700528a2c393febcc389544c6684

Thanks

**Comment by ryanbr** [comment]
This is currently a No here.

https://github.com/easylist/easylist/issues/5102
