### ISSUE TITLE
polfan.pl [EasyPrivacy] [breakage]

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#5218]
### List the website(s) you're having issues:
`https://applet.polfan.pl/`

### What happens?

EasyPrivacy blocks ​`https://applet.polfan.pl/vendor/fingerprint2.min.js` request which results in chat broken (unable to login and enter chat).

<details not-open>
<summary>screenshoot 1</summary>

![3](https://user-images.githubusercontent.com/43844449/79002365-983dab80-7b50-11ea-8ec8-3e11742128fd.gif)

</details>

After allowing the script (eg. `@@||applet.polfan.pl/vendor/fingerprint2.min.js$script,domain=applet.polfan.pl`) chat is fixed and can login to chat.

<details not-open>
<summary>screenshoot 2</summary>

![4](https://user-images.githubusercontent.com/43844449/79002512-eeaaea00-7b50-11ea-860c-bf4c022509cb.gif)

</details>

### List Subscriptions you're using:

uBO default

### Your settings

- OS/version: Windows 7 SP1 64bit
- Browser/version: Firefox 75 64bit / Opera 67 64bit
- Adblock Extension/version: uBlock Origin version:  1.26.1b3

**Comment by szado** [comment]
Dzięki za wyłapanie i zgłoszenie błędu do autorów Easylist, po zaktualizowaniu filtrów problem rzeczywiście ustąpił. 

Jednak sposób w jaki o tym nam zakomunikowałeś był co najmniej niewłaściwy, a ktoś złośliwy mógłby stwierdzić nawet, że była to dziwna próba prowokacji i zwrócenia na siebie uwagi. Wszedłeś do głównego pokoju czatowego portalu i nie próbując wcześniej rozeznać się do kogo i jakim kanałem najwłaściwiej byłoby taką informację przekazać, oznajmiłeś publicznie, że wykryłeś i naprawiłeś błąd natury czysto technicznej. Na początkowy, naturalny sceptycyzm operatora który **nie odpowiada za techniczne utrzymanie portalu**, zareagowałeś agresją słowną i obraziłeś cały zespół Polfanu (na który składa się przecież kilkanaście osób). To pozwala mi domniemywać, że przyszedłeś na Polfan z oczekiwaniem natychmiastowej chwały i poklasku, a gdy spotkałeś się z innym odbiorem (który był podyktowany jedynie rozsądkiem - każde takie zgłoszenie najpierw analizujemy pod względem technicznym, co praktycznie zrobiłem od razu po dostaniu cynku od czteryem) - szambo wylało i powstał ten potworek - czyli post powyżej oraz Twój dość nieuprzejmy monolog na czacie.

> Przez takich pajaców jak ten, niektórzy dobrzy ludzie (jak ja), zastanawiają się czy jest sens komukolwiek pomagać. Żeby ci ten twój czat szlag trafił ponownie, wtedy już go nie naprawię i nie zgłoszę, bo świniom nie pomagam.

Zachęcam Cię do dalszej pomocy innym, jestem przekonany, że ma to sens. :) Myślę też, że z odrobiną pokory i cierpliwości z Twojej strony, sprawa mogłaby wyglądać zupełnie inaczej. Działamy dzięki uprzejmości oraz aktywności Użytkowników. Umiemy też odwdzięczyć się tym osobom, które pomagają nam portal ulepszać i rozwijać - nie jest w naszym interesie zniechęcać ich do siebie, ale nie damy się też obrażać i wejść sobie na głowę. Myślę, że to dobry i zrozumiały układ. 

Dobrych Świąt.
Shado
administrator techniczny Polfanu.

**Comment by kulfoon** [comment]
Nie tłumacz się tyle i nie troluj, bo na chamstwo admina `czteryem` nie ma usprawiedliwienia, chamstwo jest albo go nie ma, a że było co sam potwierdził swoją błyskotliwą odpowiedzią, to nazwałem po imieniu i ozdobilem wiązanką, bo z chamami się jedzie, proste i tyle w temacie, tłumaczysz się i tłumaczysz, a i tak się nie wytłumaczyłeś z niczego, bo jedyne co, to bystrze trolujesz, manipulujesz i próbujesz odwrócić kota ogonem, żeby wybronić kolegę, i na mnie coś nawypisywać, każdy to zauważy czytając twój komentarz.

> Dzięki za wyłapanie i zgłoszenie błędu do autorów Easylist, po zaktualizowaniu filtrów problem rzeczywiście ustąpił.

Doceniam, choć nie wiem na ile te podziękowania prawdziwe, a na ile po prostu chesz wyjść jaki to ty niby kulturalny jesteś (i pewnie wszyscy z polfan.pl tak samo)...

> Jednak sposób w jaki o tym nam zakomunikowałeś był co najmniej niewłaściwy, a ktoś złośliwy mógłby stwierdzić nawet, że była to dziwna próba prowokacji i zwrócenia na siebie uwagi. Wszedłeś do głównego pokoju czatowego portalu i nie próbując wcześniej rozeznać się do kogo i jakim kanałem najwłaściwiej byłoby taką informację przekazać, oznajmiłeś publicznie, że wykryłeś i naprawiłeś błąd natury czysto technicznej. 

Może byś przestał kłamać, bo nieładnie, po wejściu na czat napisałem adminowi że mam bardzo ważną sprawę i czy mogę wkleić link na czat (publicznie), zgodził się, więc o co ci chodzi? Skoro wiedział, że sprawa jest bardzo ważna, to mógł powiedzieć żebym wkleił mu link w rozmowie prywatnej. Poza tym po pierwsze ten błąd techniczny nie był po stronie polfan.pl tylko po stronie dodatku adblock, a po drugie nie był to błąd zagrażający jakiemuś bezpieczeństwu czy coś, ma się wrażenie, że zwyczajnie trolujesz i usiłujesz wmówić, że publicznie zdradziłem jakąś lukę bezpieczeństwa przez którą na czat polfan.pl mógł się włamać jakiś haker i wykraść tajne dokumenty dotyczące budowy broni nuklearnej albo tajemnicy państwowej itp. Na bajkopisarza to się nadajesz.

> Na początkowy, naturalny sceptycyzm operatora który nie odpowiada za techniczne utrzymanie portalu, zareagowałeś agresją słowną i obraziłeś cały zespół Polfanu (na który składa się przecież kilkanaście osób). 

Odpowiada czy nie, zachował się jak niewdzięczny cham to z nim pojechałem, o czym już pisałem, proste. "Agresja" w odwecie na chamstwo to nie agresja, tylko obrona i "wdzięczność", prawdziwą agresją było właśnie chamstwo ze strony `czteryem`. Widzę, że jedyne co próbujesz to odwrócić kota ogonem.

> To pozwala mi domniemywać, że przyszedłeś na Polfan z oczekiwaniem natychmiastowej chwały i poklasku, a gdy spotkałeś się z innym odbiorem 

Więc twoje domniemanie jest błędne, bo jak już pisałem, nie oczekiwałem zapłaty pieniężnej ani nagrody, ani niczego innego w tym stylu typu: chwały,  poklasku i czegokolwiek co tam jeszcze nie wymyślisz (100 synonimów), a jedynie zwykłej życzliwości i prostego "dzięki"  - symbolicznego doceniania czyjegoś bezinteresownego trudu i wkładu pracy.

> (który był podyktowany jedynie rozsądkiem - każde takie zgłoszenie najpierw analizujemy pod względem technicznym, co praktycznie zrobiłem od razu po dostaniu cynku od czteryem) - 

No tłumacz sobie chamstwo `czteryem` rozsądkiem, a może od razu nazwij jego zachowanie jeszcze bohaterstwem.

> szambo wylało i powstał ten potworek - czyli post powyżej oraz Twój dość nieuprzejmy monolog na czacie.

Z mojej strony wylała się bezinteresowna pomoc i chęć **symbolicznego** (zwykłe dzięki albo thx by wystarczyło) docenenia czyjegoś trudu i wkładu pracy, niestety ale szambo to wylało się od `czteryem`, a z mojej strony była to tylko "wdzięczność" za to szambo, zwyczajnie z chamem się jedzie jak z psem i tyle stąd poszły wiązanki i tyle, proste, chamstwo się tępi.

Tak jak już pisałem na początku, prpóbujesz wybronić kolegę za wszelką ceną i odrwócić kota ogonem jacy to wy jesteście wspaniali i kulturalni, i że to ja jestem chamem a nie `czteryem`. Dalsza dyskusja z tobą raczej nie ma sensu, bo będziesz ciągle to robił, a ja będe musiał to odkręcać, więc może zakończmy tę dyskusję, bo trolli przerabiałem dziesiątki, ale jeśli dalej będziesz coś na mnie wymyślał i manipulował to będę zmuszony się bronić i odpisywać, a przeabiałem już wyjątkowo agresywnych trolli i wiem do czego są zdolni.

**Comment by keczuppp** [comment]
- znowy popsuty czat polfan, polfan nie zasłużył żeby to zgłaszać do naprawienia, i wtedy polfan byłby znowu uwalony nie wiadomo jak długo, tak jak za pierwszym razem, ale życzliwy człowiek postanowił tak jak wcześniej zgłosił błąd, to i teraz też, pomimo że polfan nie zasłużył, ani za pierwszym razem, ani teraz
