### ISSUE TITLE
Fanboy’s Annoyance blocking Google ReCaptcha

### ISSUE THREAD

**Issue by SonOfDiablo** [easylist/easylist#5219]
### List the website(s) you're having issues:

Pretty much any website using Google ReCaptcha

### What happens?

The rule `##.grecaptcha-badge` seems to not only remove the badge, but also block ReCaptcha completely.

### List Subscriptions you're using:

```
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak​​​​​
AdGuard Base​​​​​
EasyList
AdGuard Tracking Protection​​​​​
EasyPrivacy
Fanboy’s Enhanced Tracking List
Malvertising filter list by Disconnect
Malware Domain List
Malware domains
Spam404
AdGuard Annoyances
AdGuard Social Media​​​​​
Fanboy’s Annoyance​​​​​
uBlock filters – Annoyances
Dan Pollock’s hosts file​​​​​
MVPS HOSTS​​​​​
Peter Lowe’s Ad and tracking server list
DEU: EasyList Germany​​​​​
NOR, DNK, ISL: Dandelion Sprouts nordiske filtre
SWE: Frellwit's Swedish Filter​​​​
Adblock Warning Removal List​​​​​
```

### Your settings

- OS/version: Windows 10 Pro Version 1909 Build 18363
- Browser/version: Vivaldi | 2.11.1811.52 (Stable channel) (64-bit)
- Adblock Extension/version: uBlock Origin v1.24.4

**Comment by Khrin** [comment]
I don't think that's the case...
