### ISSUE TITLE
facebook game

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5226]
### List the website(s) you're having issues:
https://www.facebook.com/

### What happens?
start "words with friends" game with your friends, put some letters and submit. An ad will be shown

### Your settings

- OS/version:  windows 10
- Browser/version: firefox
- Adblock Extension/version:  ublock origin, easylist fr

**Comment by ryanbr** [comment]
Will more details here, it just forwards me to `https://www.zynga.com/games/words-with-friends-2/`

Just not a helpful post.

**Comment by momala454** [comment]
what do you mean by "not a helpful post" ?
i'm not talking about mobile game but browser integrated games, into facebook.

Open a messenger tab, click on the joypad icon, search the game "words with friends" (not words with friends 2).
Start a game by entering a word. An ad will show.

How do i reopen this issue ?

**Comment by momala454** [comment]
![image](https://user-images.githubusercontent.com/83005/79676651-84491800-81e8-11ea-87fd-d9778d52216e.png)

**Comment by llacb47** [comment]
that looks like an app,, not a website.

**Comment by momala454** [comment]
yes

**Comment by momala454** [comment]
https://www.facebook.com/instantgames/play/383041995381848/

**Comment by momala454** [comment]
How do i reopen this issue ?

**Comment by momala454** [comment]
How do i reopen this issue ? @ryanbr
