### ISSUE TITLE
bledina.com

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5227]
### List the website(s) you're having issues:
`https://www.bledina.com/`

### What happens?
easylist cookie prevent the site to display properly. A grey overlay is on the whole screen

### List Subscriptions you're using:
easylist fr + easylist cookie

### Your settings

- OS/version: 
- Browser/version: firefox
- Adblock Extension/version:  ublock origin

**Comment by smege1001** [comment]
Doesn't appear for me.
![sc](https://user-images.githubusercontent.com/59537482/79090228-dbf70780-7d40-11ea-9a60-cad53895a7dc.png)

**Comment by momala454** [comment]
@smege1001 it's probably for EU only

**Comment by spirillen** [comment]
My visit to that site gives.....

![image](https://user-images.githubusercontent.com/44526987/79221614-709f5980-7e56-11ea-94c7-aed065a60509.png)

Clicking the cross in upper right corner

![image](https://user-images.githubusercontent.com/44526987/79221703-9593cc80-7e56-11ea-9261-147f43f9a2e1.png)

Sidenote: as I have no clue of what is written, but from the images and setup, it looks mostly like a spam site.... trying to sell "happiness" to _sensitive_ females

**Comment by momala454** [comment]
without easylist cookie :
![image](https://user-images.githubusercontent.com/83005/79223390-87937b00-7e59-11ea-976d-e66cc672f2c1.png)

with easylist cookie : 
![image](https://user-images.githubusercontent.com/83005/79223451-a6920d00-7e59-11ea-982d-9fd05b07ce3b.png)


that's not a spam site, it's a brand that sells baby stuff

**Comment by spirillen** [comment]
> that's not a spam site, it's a brand that sells baby stuff

ok :smiley:

**Comment by ryanbr** [comment]
I get the popup, but (which is a info-warning about breast feeding)  but no dark overlay. If its still an issue submit the dark overlay element here. (not www.bledina.com##.show.fade.modal-backdrop btw)

**Comment by momala454** [comment]
the html of the grey overlay  is
`<div id="tc_priv_CustomOverlay" style="position:fixed; background-color:rgba(0,0,0,0.8); top:0; left:0; bottom:0; right:0;z-index:999997"></div>`

**Comment by krystian3w** [comment]
IMO this is fixed in EasyPrivacy:

`||cdn.tagcommander.com/privacy/*$script,domain=www.bledina.com`

See:

https://github.com/easylist/easylist/blob/35984bb1198623580234b4bbc8ca83caeb92a1c7/easyprivacy/easyprivacy_trackingservers.txt#L2178

**Comment by krystian3w** [comment]
From IDCAC:

`||tagcommander.com/privacy$script,domain=~labanquepostale.fr`

I do not know who is broken on `labanquepostale.fr`.

**Comment by momala454** [comment]
i don't use easyprivacy

**Comment by krystian3w** [comment]
So you should copy filters to "my filters" pane, Khrin closed without pin commit.
