### ISSUE TITLE
||cloudfront.net^$script,3p,domain=site is WAY too general

### ISSUE THREAD

**Issue by tmikaeld** [easylist/easylist#5228]
The recently added filter makes a shit ton of ordinary services and even eCommerce like Ecwid stop working on ALL .site domains. Please make this more specific!

**Comment by jbenguira** [comment]
+1 this is breaking millions of sites hosted by AWS Cloudfront

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/1a91af8659472d7281cfd6f75ccc996a4c3788fd
