### ISSUE TITLE
ghacks.net

### ISSUE THREAD

**Issue by uBlock-user** [easylist/easylist#5240]
### List the website(s) you're having issues:

`https://www.ghacks.net/`

### What happens?

Left over ADVERTISEMENT placeholder div node is not blocked in the header section of the website

### List Subscriptions you're using:

uBlock Origin lists and Easylist.

### Your settings

uBlock Origin only.

- OS/version: Win 10
- Browser/version: Firefox 77
- Adblock Extension/version: uBlock Origin 

### Other details:

Filter -- `ghacks.net##.ghacks-ad`

![Capture](https://user-images.githubusercontent.com/21290713/79438899-c6f4cf80-7ff1-11ea-8fbd-9694307a33c4.PNG)

**Comment by Khrin** [comment]
`ghacks.net##.ghacks-ad-loaded` isn't enough of?

**Comment by uBlock-user** [comment]
Apparently not.
