### ISSUE TITLE
totalcar.hu

### ISSUE THREAD

**Issue by b1b2b3b4b5b6b7** [easylist/easylist#5241]
### List the website(s) you're having issues:

```
totalcar.hu
https://totalcar.hu/tv/2020/04/16/opel_vetra_totalcar_teszt_tv_2002/
```

### What happens?
totalcar.hu, the main site opens without any issues, but if you click on any article (for example https://totalcar.hu/tv/2020/04/16/opel_vetra_totalcar_teszt_tv_2002/ , the site detects the adblocker and blocks the content. I've attached a screenshot as well.

### List Subscriptions you're using:

the standard ones added by default (and the extras needed for ublock to function properly with nano defender)

### Your settings

Tried running ublock with nano defender, the site detected the addon (every other addon was disabled), then tried nano adblocker with nano defender, just to be sure that I'm not experiencing a compatibility issue of some sort, but the end result was the same.
![Capture](https://user-images.githubusercontent.com/63799495/79469803-ed6e3700-8000-11ea-9b9e-4d7f9cba6bfe.PNG)

- OS/version: win10, latest
- Browser/version: chrome, latest
- Adblock Extension/version: ublock origin with nano defender. (also tried nano adblocker + nano defender), latest version installed from chrome store

**Comment by Khrin** [comment]
EasyList doesn't deal with anti-Adblock systems.
