### ISSUE TITLE
https://www.escapistmagazine.com/v2/resident-evil-3-zero-punctuation/

### ISSUE THREAD

**Issue by thinkpad4** [easylist/easylist#5246]
### List the website(s) you're having issues:

`https://www.escapistmagazine.com/v2/resident-evil-3-zero-punctuation/`
### What happens?

The video player tries to load a ad and if you are using a adblock it just shows a spinning circle
### Your settings

- OS/version: Win7 64
- Browser/version: Chrome 81
- Adblock Extension/version: 
Ublock origin 1.26.something

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4fc56150ed4a98a3f04a626164a4cd93f3d02a28

**Comment by thinkpad4** [comment]
Thank you very much
