### ISSUE TITLE
https://coolsoft.altervista.org/en/virtualmidisynth

### ISSUE THREAD

**Issue by Mavromatis** [easylist/easylist#5248]
### List the website(s) you're having issues:

`https://coolsoft.altervista.org/en/virtualmidisynth`
### What happens?

I get " It seems you're using an AdBlocker or JavaScript is disabled! " popup replacing the page.
### List Subscriptions you're using:

EasyList & EasyPrivacy
### Your settings

- OS/version: Windows 10
- Browser/version: Brave 1.7.92
- Adblock Extension/version: Nano Adblocker v1.0.0.142 & Nano Defender 15.0.0.197

**Comment by THEtomaso** [comment]
`@@||coolsoft.altervista.org^$generichide`

**Comment by llacb47** [comment]
Easylist doesn't fix antiadblock. Close the issue please :)
