### ISSUE TITLE
knowyourmeme.com

### ISSUE THREAD

**Issue by kah0922** [easylist/easylist#5249]
### List the website(s) you're having issues:
`knowyourmeme.com`

### What happens?
There are several social media elements not blocked via Fanboy's Social on KYM
![image](https://user-images.githubusercontent.com/9474213/79680176-566dce80-81fc-11ea-8296-f79a4fff6968.png)
![image](https://user-images.githubusercontent.com/9474213/79680182-5f5ea000-81fc-11ea-9d00-2ce4ad8c11f4.png)
![image](https://user-images.githubusercontent.com/9474213/79680184-65ed1780-81fc-11ea-878b-30a26960c6ad.png)
![image](https://user-images.githubusercontent.com/9474213/79680185-6a193500-81fc-11ea-87c7-c5f139dc3176.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/9474213/79680159-27575d00-81fc-11ea-9308-d0f575331f45.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly
- Adblock Extension/version: uBlock Origin 1.26.1b13

**Comment by THEtomaso** [comment]
Report here instead:
https://github.com/ryanbr/fanboy-adblock/issues/

**Comment by kah0922** [comment]
People have reported social widgets here before, so reopening this for now.

I have reported this in the Fanboy Adblock issues.

**Comment by Khrin** [comment]
I don't see any unblocked social elements.
