### ISSUE TITLE
zone-annuaire.com

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5250]
### What happens?
this filter on easylist fr is blocking all javascript : *$subdocument,3p,domain=zone-annuaire.com
but cloudflare use hcaptcha so the request to
`https://assets.hcaptcha.com/captcha/v1/f....`
is blocked

### List Subscriptions you're using:
easylist, easylist fr

### Your settings

- OS/version: 
- Browser/version:  firefox
- Adblock Extension/version:  ublock origin

### Other details:
![image](https://user-images.githubusercontent.com/83005/79691431-bc3f7200-825f-11ea-8287-0e38a0aea3e3.png)

**Comment by Khrin** [comment]
@smed79

**Comment by smed79** [comment]
already fixed...
