### ISSUE TITLE
live video stream not working when ABP enabled

### ISSUE THREAD

**Issue by mediumkreation** [easylist/easylist#5251]
### List the website(s) you're having issues:

https://www.zeebiz.com/live-tv

### What happens?
The video stream is not working when ABP is enabled.

### List Subscriptions you're using:
EasyList 
IndianLIst 

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6049d21366e6d4d268969829e0fa30496deecfac
