### ISSUE TITLE
facebook game - words with friends

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5252]
note: i don't have the rights to reopen an issue closed by "error", so i recreate this issue 

https://github.com/easylist/easylist/issues/5226

### List the website(s) you're having issues:
https://www.facebook.com/

### What happens?
start "words with friends" game with your friends, put some letters and submit. An ad will be shown.

i'm not talking about mobile game but browser integrated games, into facebook.

Open a messenger tab, click on the joypad icon, search the game "words with friends" (not words with friends 2). I think you can quickly open the game by going there https://www.facebook.com/instantgames/play/383041995381848/
Start a game by entering a word. An ad will show.

### Your settings

- OS/version:  windows 10
- Browser/version: firefox
- Adblock Extension/version:  ublock origin, easylist fr

### Other details:

![image](https://user-images.githubusercontent.com/83005/79676651-84491800-81e8-11ea-87fd-d9778d52216e.png)

**Comment by ryanbr** [comment]
Fine here, noticed 2 scripts that should be blocked.

https://github.com/easylist/easylist/commit/096eca892591059ab373a5afe31eb452ac254ff8
