### ISSUE TITLE
neoseeker.com

### ISSUE THREAD

**Issue by kah0922** [easylist/easylist#5262]
### List the website(s) you're having issues:
`https://www.neoseeker.com/the-legend-of-heroes-trails-of-cold-steel-iii/Character_Profiles`

### What happens?

Multiple Empty ad frames (the grey rectangles) are left behind. These can be removed by the filter `www.neoseeker.com##div.ad-placeholder-leaderboard`
### Your settings
![image](https://user-images.githubusercontent.com/9474213/79994195-2a28ab00-84a5-11ea-9850-32f5a5d37274.png)

- OS/version:  Windows 10
- Browser/version: Firefox Nightly
- Adblock Extension/version: uBlock Origin 1.26.3b2

### Other details:
![image](https://user-images.githubusercontent.com/9474213/79994312-504e4b00-84a5-11ea-96cf-ba821b160dc8.png)

**Comment by ryanbr** [comment]
Filter added
