### ISSUE TITLE
marmiton.org

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5263]
### List the website(s) you're having issues:
`https://www.marmiton.org/recettes/recette_veloute-de-potiron-et-carottes_19009.aspx`

### What happens?
images and videos can't be clicked

### List Subscriptions you're using:
easylist, easylist fr, easylist cookie, ublock unbreak

### Your settings

- OS/version: 
- Browser/version: firefox
- Adblock Extension/version:  ublock origin

**Comment by Khrin** [comment]
@smed79 Do you encounter any issue with this website?

**Comment by momala454** [comment]
the issue still occurs, why did you closed it ?

**Comment by momala454** [comment]
@Khrin the issue still occurs, why did you closed it ?

**Comment by smed79** [comment]
No issue here.

**Comment by momala454** [comment]
this have fixed it
https://github.com/uBlockOrigin/uAssets/commit/f6a4d8258019258d8b22e2089192b1f55856dc2b

**Comment by smed79** [comment]
The issue is specific to ubo ?

**Comment by momala454** [comment]
i think so

**Comment by llacb47** [comment]
Yes, CNAME issue due to your regexes https://github.com/easylist/easylist/issues/5039#issuecomment-628660976
