### ISSUE TITLE
adguard.$domain

### ISSUE THREAD

**Issue by thomasvt1** [easylist/easylist#5286]
### List the website(s) you're having issues:

`adguard.mydomain.com`

### What happens?

When accessing my domain `adguard.mydomain.com` is blocked, by the rule;
```javascript
/adguard.$domain=~adguard-com.cdn.ampproject.org|~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com|~marketplace.visualstudio.com
```

This rule seems wrong since blocking any domain that starts with `adguard` seems way to strict.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Windows 10
- Browser/version:  Chrome 81.0.4044.122
- Adblock Extension/version: uBlock Origin

### Other details:

The blocking of `adguard.*` seems too strict, since it's not even sure than an ad would be served from there. 
https://github.com/easylist/easylist/blob/ebffdb65ae542eab1e23151cf8460f9671990078/easylist/easylist_general_block.txt#L1950

**Comment by ryanbr** [comment]
Interesting you're trying to create this domain in the first place, and using it as a prerequisite

**Comment by ryanbr** [comment]
Maybe, Don't use generic blocks in Easylist as a domain? Seems pretty suspect that you chose "adguard' as a subdomain.

**Comment by thomasvt1** [comment]
But I'm sure generic blocks aren't meant to block legitimate domains.

And I'm also not sure aggressive blocking like that would be beneficial to adblocking, but if you have examples of bad domains using adguard.anydomain.com I'd love to see them.

**Comment by zejar** [comment]
I'm in the same boat as well, I set up a local AdGuard Home server with the local domain name adguard.int.domain.com. I don't think it is beneficial to block every adguard subdomain, especially since AdGuard is an ad blocker itself.
Yes I could change the domain to something else, but there are probably others that will run into the same issue.

**Comment by ryanbr** [comment]
Not sure if this fixes it. But the most i'll do.
