### ISSUE TITLE
lookmovie.ag

### ISSUE THREAD

**Issue by firemuppets2** [easylist/easylist#5288]
### List the website(s) you're having issues:
lookmovie.ag

### What happens?
Firstly I click to a movie, then when I press "WATCH TRAILER" it doesn't show the youtube video.
When I checked the log I spotted that the (line 29070) "##.ytp-ad-progress-list" filter doesn't let me see that video.

### List Subscriptions you're using:
uBlock Origin -> EasyList

### Your settings
Accessed without any other extension.
- OS/version: Windows 10 x64
- Browser/version: Google Chrome (latest version)
- Adblock Extension/version: uBlock Origin 1.26.0

### Other details:

**Comment by ryanbr** [comment]
Shouldn't matter? https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L14427

uBO has a `$generichide` on this site

**Comment by krystian3w** [comment]
No visible / available for AdGuard / AdBlock / ABP.

**Comment by ryanbr** [comment]
Happy to close, need more proof. Maybe a different site example.
