### ISSUE TITLE
metrika.yandex.ru

### ISSUE THREAD

**Issue by rifler** [easylist/easylist#5295]
### List the website(s) you're having issues:
https://metrika.yandex.ru

### What happens?
this commit breaks yandex.metrica's **interface** (ajax requests)

https://github.com/easylist/easylist/commit/bc6b5c2f4022176151bd5770de60aa1fd675c189#diff-6b54c84f883288b1582a40f4174525e0

### List Subscriptions you're using:
https://easylist.to/easylist/easyprivacy.txt

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:
I don't understand relation between some old movie and metrica interface

**Comment by monzta** [comment]
I excluded the filter from running on `metrika.yandex.ru` instead of removing the whole filter: https://github.com/easylist/easylist/commit/c4a9f5f

**Comment by Erelen-Laiquendi** [comment]
Bad solution :(
I have problems with Grafana on https://metrika.melda.ru/

"://metrika." - it's very common wildcard with many side-effects.

**Comment by ryanbr** [comment]
Fixed

https://github.com/easylist/easylist/commit/7f0cf769cdd7bb499698ec85f4a849b763bcdffe
