### ISSUE TITLE
tf1.fr

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5298]
### List the website(s) you're having issues:
`https://www.tf1.fr/tf1/qui-veut-gagner-des-millions/videos/qui-veut-gagner-des-millions-a-la-maison-du-27-avril-2020-08937288.html`

### What happens?
The videos doesn't work (black screen) and the login button doesn't work (top right)

### Your settings

- OS/version: 
- Browser/version: windows 10 /firefox
- Adblock Extension/version:  ublock origin

### Other details:
with ublock  : 
![image](https://user-images.githubusercontent.com/83005/80427672-8dbd3900-88e8-11ea-8be3-3e9e08012694.png)

without ublock: 
![image](https://user-images.githubusercontent.com/83005/80427722-a7f71700-88e8-11ea-8c85-8a3b5f2d27cc.png)

![image](https://user-images.githubusercontent.com/83005/80427651-85fd9480-88e8-11ea-8f06-318baf4a59da.png)

**Comment by TheStinkySkunk** [comment]
Because you don't respect website CGU : https://www.tf1.fr/conditions-generales-utilisation#chapter4

**Comment by momala454** [comment]
> 
> 
> Because you don't respect website CGU : https://www.tf1.fr/conditions-generales-utilisation#chapter4

lol the whole easylist is against cgu of each website :)

**Comment by krystian3w** [comment]
No, EasyList do not repair anti-adblock walls.

**Comment by momala454** [comment]
> 
> 
> No, EasyList do not repair anti-adblock walls.

sorry, is this a joke or a real comment for the issue a mention ?

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues?q=is%3Aissue+label%3AAnti-Adblock+is%3Aclosed+label%3AInvalid

**Comment by krystian3w** [comment]
[https://github.com/easylist/easylist/issues?q=is issue+label <kbd>Anti-Adblock</kbd>+is closed+label <kbd>Invalid</kbd>](https://github.com/easylist/easylist/issues?q=is%3Aissue+label%3AAnti-Adblock+is%3Aclosed+label%3AInvalid)

**Comment by momala454** [comment]
so you are sure that the website not working at all is an "anti adblock wall" ?

**Comment by mapx-** [comment]
add
```
@@||cloudfront.net^$domain=tf1.fr
@@||g.akamaiedge.net^$script,domain=tf1.fr
```

**Comment by momala454** [comment]
you should also whitelist
`@@||tagcommander.com^*/tc_$script`

**Comment by llacb47** [comment]
That is whitelisted in EasyPrivacy, a list you refuse to use.

**Comment by momala454** [comment]
> 
> 
> That is whitelisted in EasyPrivacy, a list you refuse to use.

and ? tagcommander is blocked in easylist fr which prevent the videos to be played, then it must be fixed in easylist fr

**Comment by smed79** [comment]
Removed https://hg.adblockplus.org/listefr/rev/018aee6228bd

@mapx- Thank you.
