### ISSUE TITLE
ap.org video blocked easyprivacy

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#53]
http://bigstory.ap.org/article/7006105d422740f0b4b8675c90f9a154/emails-key-security-features-disabled-clintons-server

EasyPrivacy breaks video.

**Comment by terrorist96** [comment]
http://hosted.ap.org/dynamic/stories/U/US_SUPREME_COURT_IMMIGRATION?SITE=AP&SECTION=HOME&TEMPLATE=DEFAULT

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/5380087a124603947be8198fbdb392cb724e97dc
