### ISSUE TITLE
zeit.de 

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#5301]
### List the website(s) you're having issues:

`https://www.zeit.de`

### What happens?

unblocked WebTrekk tracking
<img width="664" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/80544192-cb859480-89b0-11ea-9271-4b410d9491da.PNG">

### List Subscriptions you're using:

Easylist, EasyList Germany and EasyPrivacy

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 75
- Adblock Extension/version: uBlock Origin v1.26.2

**Comment by Khrin** [comment]
Unfortunately Webtrekk elements are too much problematic to be blocked.
