### ISSUE TITLE
track.mailerlite.com false positive

### ISSUE THREAD

**Issue by arnoldasb** [easylist/easylist#531]
Hey,
I'm with Mailerlite.com it's a tool for small businesses to send their email campaigns.
This link is for application to track clients who open, click on some links.

Can you please remove the link from the list, as it can drive possible clients from continueing to visit the link and poor statistics drives clients away.

**Comment by SMed79** [comment]
Hi,
https://forums.lanik.us/viewtopic.php?p=123390#p123390

**Comment by ryanbr** [comment]
> No issue with Adblock plus, the Strict-blocking is specific for uBlock.
> if you do not agree its best to report your issue at https://github.com/gorhill/uBlock/issues

Agreed, lodge an issue with uBo.
