### ISSUE TITLE
search not working (various websites)

### ISSUE THREAD

**Issue by IsraeliUser** [easylist/easylist#5313]
For example:
`sport5.co.il`
`globes.co.il`
`israelhayom.co.il`
`makorrishon.co.il`
In addition to https://github.com/easylist/easylist/issues/5303

Same problematic filter: `/zoomd.widget.logger.`
Temporarily fixed in EasyList Hebrew: https://github.com/easylist/EasyListHebrew/commit/b3fe136be9ba5a3da79c6cc744d451455f54419c
(By adding `@@||bitsngo.net/widget-scripts/zoomd.widget.logger.$script`)

I think you should remove the problematic filter (added to EasyPrivacy about 3 months ago).
If you do so, don't forget to remove the whitelist rule for `13tv.co.il`/`13news.co.il`.

**Comment by Khrin** [comment]
Ok, I've removed the filter. thank you.

**Comment by IsraeliUser** [comment]
re-added... https://github.com/easylist/easylist/commit/caa30b8ab89e9e9af6ae49b4747e837f56624e27
@ryanbr @Khrin @monzta
