### ISSUE TITLE
https://www.quora.com/

### ISSUE THREAD

**Issue by Zenexer** [easylist/easylist#5314]
### List the website(s) you're having issues:

* `https://www.quora.com/`

### What happens?

Lots of unblocked ads in the feed:

![image](https://user-images.githubusercontent.com/504130/80819646-57f7a900-8ba3-11ea-8a31-52c57194becf.png)

### List Subscriptions you're using:

* EasyList
* EasyPrivacy
* uBlock filters (incl. Badware risks, Privacy, Resource abuse, Unbreak)
* Malware Domain List
* Malware domains
* Peter Lowe’s Ad and tracking server list

### Your settings

- OS/version: Microsoft Windows 10 Pro 10.0.18363 N/A Build 18363
- Browser/version: Firefox Nightly 77.0a1 (2020-05-01) (64-bit)
- Adblock Extension/version: uBlock Origin 1.26.2

**Comment by Zenexer** [comment]
The following works in uBlock Origin, but I assume `:has` and `:has-text` aren't universal.  I haven't optimized them; there's probably a way to combine the two filters.

```
www.quora.com##.q-box.qu-borderTop:has(:scope > div > div > .q-box > .Box > .q-box > .q-box > .q-text > div:has-text(Sponsored))
www.quora.com##.q-box.qu-borderAll:has(:scope > .q-box > div > div > div > .q-box > div > .q-box > .q-flex > .q-box > .q-text > div:has-text(Sponsored))
```

**Comment by llacb47** [comment]
How's this?

`quora.com##div.qu-borderAll.q-box:-abp-has(.qu-pb--tiny>.qu-mb--tiny)`

**Comment by Zenexer** [comment]
That causes questions to be "deleted" from my feed when I click `(More)`, unfortunately.  That's why my two rules were so specific.  `.qu-borderAll` can be an ad itself, or it can contain ads at the bottom within a `.qu-borderTop`.

**Comment by llacb47** [comment]
When you click more? Where is "more"? The feed is infinite scroll.

**Comment by Zenexer** [comment]
It's in individual answers.  You click to expand the answer.

**Comment by Zenexer** [comment]
```
www.quora.com##.qu-borderTop:has(.qu-color--gray_light:has-text(Sponsored))
www.quora.com##.qu-borderAll:not(:has(.qu-borderTop)):has(.qu-color--gray_light:has-text(Sponsored))
```

That seems to work fairly well.

**Comment by llacb47** [comment]
Ok, try this: `quora.com##div.q-box:-abp-has(.qu-pb--tiny>.qu-mb--tiny):not(:-abp-has(.qu-borderTop))`

**Comment by Zenexer** [comment]
That seems to do the trick.

**Comment by Zenexer** [comment]
Actually, now my entire feed is hidden when I refresh the page.

**Comment by llacb47** [comment]
Try this one: `quora.com##div.q-box:-abp-has(.qu-pb--tiny>.qu-mb--tiny):not(:-abp-has(.qu-borderTop)):not(:-abp-has(:scope > div:only-child))`

**Comment by krystian3w** [comment]
ABP/AdBlock  IMO still no support `:not(:-abp-has(` and EasyList (main / en) newer use `#include` for uBO / AdGuard.
