### ISSUE TITLE
thewirecutter.com

### ISSUE THREAD

**Issue by dividedby** [easylist/easylist#5319]
### List the website(s) you're having issues: 

`thewirecutter.com`

### What happens?

A filter from the Annoyances list effectively breaks the homepage of thewirecutter.com by blocking the site search and navigation.

### List Subscriptions you're using:

Fanboy's Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 81
- Adblock Extension/version: uBlock Orign 1.26

### Other details:

What it looks like with the rule enabled: 
`thewirecutter.com###site_header_wrapper > div:first-child`
![image](https://user-images.githubusercontent.com/64715420/80896337-d0995b00-8cb2-11ea-9e5e-35790c1f930c.png)

What it looks like with the rule disabled:
`thewirecutter.com#@##site_header_wrapper > div:first-child`
![image (1)](https://user-images.githubusercontent.com/64715420/80896326-b8294080-8cb2-11ea-889e-b0c53ec624bb.png)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/f89fe9f10b4500eb55a2b19d4ae7e068655612f5
