### ISSUE TITLE
EasyPrivacy breaks jd.com

### ISSUE THREAD

**Issue by xxmmllqqqqccqq** [easylist/easylist#533]
https://www.jd.com/
It's one of the most popular online shopping sites in China. 
When I disable EasyPrivacy, the webpage is normally displayed. See https://imgly.net/img/CJW.jpg. But when I enable EasyPrivacy, several items in the left navigation bar are gone, and the corresponding elements in the page are also gone. See https://imgly.net/img/CJV.jpg.

**Comment by peace2000** [comment]
@xxmmllqqqqccqq can you update this issue? This is an old issue report so things might have changed. Those imgly links don't even work anymore. Easyprivacy blocks indeed some elements on that site but if you don't speak chinese it's hard to know what those elements are, should they be blocked or not?

It's best to upload pictures here as Github supports uploading pictures here directly (at least today).
