### ISSUE TITLE
NewRepublic.com - Unable to log in (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#5331]
### Affected site:
`https://newrepublic.com/`

### Issue:
Unable to log in.

### How to reproduce:
Click on the "**SIGN IN**" button (in the top right corner).

Expected result: The log in page should appear.
Actual result: Nothing happens!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyPrivacy

### Problem rule:
`||onecount.net^$third-party`

### Blocked script:
`https://validate.onecount.net/js/all.min.js`

### Possible fix:
Remove the problem rule, and use **AdGuard Tracking Protection filter**'s rules instead?:
https://github.com/AdguardTeam/AdguardFilters/search?q=onecount.net&unscoped_q=onecount.net

### Temporary fix:
`@@||validate.onecount.net/js/all.min.js$domain=newrepublic.com`

### Other problem filters:
* Browse websites without logging in (`||validate.onecount.net^$third-party`) @DandelionSprout

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.9.3 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout:
Your new rule still breaks the login.
Try using this one instead:
`||validate.onecount.net/onecount/api/public/`

**Comment by DandelionSprout** [comment]
Okay, sure thing. Admittedly I never really changed my entry anyway... until today in about a minute. 😅
