### ISSUE TITLE
Pictures from Amazon Associate blocked again.

### ISSUE THREAD

**Issue by Nyl000** [easylist/easylist#5344]
### List the website(s) you're having issues:

`https://maperruche.com/calopsitte/quels-sont-les-meilleurs-perchoirs-pour-ma-calopsitte/`
### What happens?

Images provided by amazon API are blocked. This is not the first time and this is VERY CRITICAL since Amazon doesn't allow to copy pictures to display products. That images are the only way to let users visualize products !

### List Subscriptions you're using:
EasyList

### Your settings

- OS/version:  OSX 10.15
- Browser/version: Chrome 81.0.4044.138 
- Adblock Extension/version: AdBlock 4.10.0

### Other details:

Here is the filter: 
`||amazon-adsystem.com^$third-party`

And an exemple blocked: 
`https://ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B07M98YPML&Format=_SL250_&ID=AsinImage&MarketPlace=FR&ServiceVersion=20070822&WS=1&tag=nyl000-21&language=fr_FR`

Thanks for your help !

**Comment by Nyl000** [comment]
I guess it's because of that.. https://github.com/easylist/easylist/commit/17576f11a85396cb0004e1ade545f49c246ba0f2

**Comment by ragn99** [comment]
Same problem on my websites.. Thank you for your help.

**Comment by Nyl000** [comment]
Its OK now, Thank you very much :)
