### ISSUE TITLE
Web page ask about turn off ad or script blocking software.

### ISSUE THREAD

**Issue by PowerShot-x** [easylist/easylist#5346]
Not sure if this is the right place, but it giving massage that script is interfering, like the massage bellow. This has been working fine until recently, then this message below starting showing up. 

Massage that appear:
"You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.

Its this web page that gives this warning that its seeing the script.
<https://www.startsiden.no/>

Ublock origin, ublock origin extra, Nano defender, I dont care about cockies. I only use does.

### Your settings

- OS/version: Windows 10 64bit
- Browser/version: Google Chrome
- Adblock Extension/version: 1.26

### Other details:

![abs](https://user-images.githubusercontent.com/12992064/81820866-6e055200-9531-11ea-9e44-88e7759116f3.jpg)

**Comment by llacb47** [comment]
`https://www.startsiden.no/v%C3%A6r/Norge/Oslo/Oslo/Oslo` @mapx-

**Comment by krystian3w** [comment]
[https://github.com/easylist/easylist/issues?q=is issue+label <kbd>Anti-Adblock</kbd>+is closed+label <kbd>Invalid</kbd>](https://github.com/easylist/easylist/issues?q=is%3Aissue+label%3AAnti-Adblock+is%3Aclosed+label%3AInvalid)
