### ISSUE TITLE
https://deno.land/std/log has GitHub API request incorrectly blocked

### ISSUE THREAD

**Issue by lucacasonato** [easylist/easylist#5353]
### List the website(s) you're having issues:

`https://deno.land/std/log`

### What happens?

The third party request to `https://api.github.com/repos/denoland/deno/contents/std/log?ref=master` is being blocked, but it is not a tracker but a CORS API request.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: FF 78.0a1
- Adblock Extension/version: uBlock Origin v1.26.2

**Comment by ryanbr** [comment]
fixed
https://github.com/easylist/easylist/commit/90b9ac4b5d23dcdb215636a64d4cdd5edd1a9259
