### ISSUE TITLE
https://arponag.xyz/

### ISSUE THREAD

**Issue by kal0p2-12u** [easylist/easylist#5372]
[https://arponag.xyz/](https://arponag.xyz/)

I'm using:

uBlock Origin 1.26.0
Nano Defender 15.0.0.198

![Screenshot_86](https://user-images.githubusercontent.com/64157624/82233413-facb5980-98fd-11ea-903f-f5bdef58f18f.png)

**Comment by llacb47** [comment]
Easylist doesn't fix antiadblock, file issue here instead: https://github.com/uBlockOrigin/uAssets
