### ISSUE TITLE
megapornx.com NSFW

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#5373]
### List the website(s) you're having issues:

`http://megapornx.com/`

### What happens?

Big white blank popup.

### List Subscriptions you're using:

<details not-open>

<summary>spoiler</summary>

`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`
</details>

### Your settings

- OS/version: Win 7 64 Pro SP1
- Browser/version: FF 76.0.1 / O 68
- Adblock Extension/version: uBO 1.27.2

### Other details:

![capture_082_18-05-2020_18-11-03](https://user-images.githubusercontent.com/43844449/82235685-55cb7380-9933-11ea-8d8d-1e37693ca674.gif)

**Comment by spirillen** [comment]
Hey @Khrin I can actually replicate this today...

The picker those this solution

```
! 2020-10-22 https://megapornx.com
megapornx.com##.ex_pu_iframe
```
