### ISSUE TITLE
www.hoy.es not usable with Adblock Plus

### ISSUE THREAD

**Issue by Jellby** [easylist/easylist#5378]
### List the website(s) you're having issues:

`https://www.hoy.es`  
`https://www.elnortedecastilla.es`

### What happens?

Anti-adblock popup or message that prevents reading the articles.

### List Subscriptions you're using:

EasyList

Enabling "Adblock Warning Removal List" does not help.

### Your settings

- OS/version: Kubuntu 18.04
- Browser/version: Firefox 76.0.1
- Adblock Extension/version: 3.8.4

**Comment by llacb47** [comment]
Easylist does not fix anti-adblock.

Try with uBlock origin with regional filterlists enabled, it is better.
