### ISSUE TITLE
Premium ADS/BANNERS on almost 700 pornsites NSFW

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#5391]
### Premium ADS/BANNERS on almost 300 link farm pornsites ##.space, .content, .contentrow NSFW

NSFW 292 pornsites `https://publicwww.com/websites/%22%3Cdiv+class%3Dcontentrow%3E%3Ch2+class%3Dblock_header%3Epremium+websites%3C%2Fh2%3E%22/`

### List the website(s) you're having issues:

(There is 292 pornsites as shown in the publicwww link, and I posted 299 links, which means I accidentaly unnecessarily bookmarked 7 pornsites which contains different ads/banners, if you want you can look for them and exclude them - have fun)

<details not-open>
<summary>NSFW Almost 300 pornsites (220 domains):</summary>

```
adultlingeriepics.com
adultspankingtgp.com
allgfpics.com
allhairysex.com
allhotgayporn.com
allrealvoyeur.com
allswinger.com
allvoyeurxxx.com
amateursexypics.com
asianhotxxx.com
asianpicturesporn.com
asianshotporn.com
asshotfuck.com
bdsmfemdomtraining.com
bdsmsextgp.com
bestasianpics.com
bestfemdomporn.com
bestlingerieporn.com
bestnylonpics.com
bestpainporn.com
bestpornblack.com
bestspankingpics.com
bigboobsgrab.com
blackxxxgalleries.com
classicpornpost.com
doubleanalfucking.com
eroticchubby.com
eroticfootgallery.com
eroticspankinginternet.com
eroticvoyeurporn.com
fatpussysluts.com
femdomhard.com
femdompicstgp.com
flashersporn.com
forcedfemdomtgp.com
freebondagehardcore.com
freefemdomart.com
freegallerybdsm.com
freegftgp.com
freelesbiantgp.com
freenylonfetish.com
freenylontgp.com
freepantyhosefetish.com
freepicsamateur.com
freeupskirttgp.com
freevoyeurnude.com
girlfriendstgp.com
hardanalpics.com
hardasian.com
hardbdsmpics.com
hardbondageart.com
hardcoreblackfuck.com
hardspankingsex.com
hiddenvoyeurporn.com
hotbbwgalleries.com
hotbbwgallery.com
hotbdsmthumbs.com
hotfemdomgallery.com
hotlesbianlicking.com
hotlesbiansorgy.com
hotmaturegalleries.com
hotmaturetgp.com
hotpornebony.com
hotpublicporn.com
hotswingerspictures.com
hotswingersporn.com
hotupskirtshots.com
hotvintagepictures.com
hotvoyeurporn.com
inpublicflashing.com
latexerotic.com
legsthumbs.com
lingeriepornfree.com
lingeriepornguide.com
lingeriethumbs.com
matureswingercouples.com
mybdsmlibrary.com
nastyebonyporn.com
nastymilfsex.com
nudelingeriepics.com
nylonstockingsex.org
oldandyoungxxx.com
perfectassporn.com
perfectbuttfuck.com
perfectfemdom.com
perfecttitsfuck.com
pornnylons.com
privatevoyeurweb.net
publicerotic.com
publicflashinggalleries.com
publicporntgp.com
realfemdomsex.com
realvoyeurpost.com
retropornarchives.com
retrothumbs.com
sexyboobsporn.com
sexychubbyporn.com
sexylesbiangalleries.com
spicyass.com
spyvoyeurs.com
straponhot.com
swingersbest.com
swingerspornparties.com
swingersxxxpics.com
titssuper.com
titsthumbnails.com
trannyfreefuck.com
upskirtviewers.com
vintagehotporn.com
www.adultlingeriepics.com
www.allfeetporn.com
www.allfemdompics.com
www.allrealvoyeur.com
www.allsexylegs.com
www.allswinger.com
www.allvoyeurxxx.com
www.amateurbbwpussy.com
www.asianfuckthumbs.com
www.asianhotxxx.com
www.asianpicturesporn.com
www.asianshotporn.com
www.asshotfuck.com
www.barefeetsex.com
www.bbwhardporn.com
www.bbwhotxxx.com
www.bdsmfemdomtraining.com
www.bdsmsextgp.com
www.bestasianpics.com
www.bestassparade.com
www.bestbbwsex.com
www.bestfemdomporn.com
www.bestfemdomtgp.com
www.bestlegsporn.com
www.bestlingerieporn.com
www.bestnylonpics.com
www.bestpainporn.com
www.bestpublicporn.com
www.bestupskirtporn.com
www.bestvoyeurpictures.com
www.bestvoyeurporn.com
www.bigboobsgrab.com
www.buttstgp.com
www.classicpornpost.com
www.classicretrosex.com
www.clubfemdomfetish.com
www.dailyfemdomporn.com
www.dailyfootporn.com
www.dailyhairyporn.com
www.dailylatexporn.com
www.dailynylongalleries.com
www.dailyvintageporn.com
www.eroticchubby.com
www.eroticfootgallery.com
www.eroticlatexporn.com
www.eroticlingeriephotos.com
www.eroticnylonpics.com
www.eroticspankinginternet.com
www.eroticvoyeurporn.com
www.extremebondagepictures.com
www.extremelatexsex.com
www.extremestraponsex.com
www.faterotic.com
www.femalepublicflashers.com
www.femdombest.com
www.femdomhard.com
www.femdomlove.com
www.femdompicstgp.com
www.fetishfootporn.com
www.fetishlatexporn.com
www.fetishstraponsex.com
www.flashersporn.com
www.footfetishcollection.com
www.footfreeporn.com
www.forcedfemdomtgp.com
www.freeasiantgp.com
www.freebdsmarchive.com
www.freebondagehardcore.com
www.freebondagetorture.com
www.freefemdomart.com
www.freegallerybdsm.com
www.freelesbiantgp.com
www.freelingeriegalleries.com
www.freelingerietgp.com
www.freenylonfetish.com
www.freenylontgp.com
www.freepantyhosefetish.com
www.freeretropics.com
www.freeswingersthumbs.com
www.freetitsporn.com
www.freeupskirttgp.com
www.freevintagegallery.com
www.galleriesswingers.com
www.girlspublic.com
www.hairyfuckingcunt.com
www.hardasian.com
www.hardbdsmpics.com
www.hardbdsmsex.com
www.hardbondageart.com
www.hardspankingsex.com
www.hardupskirt.com
www.hotasiangallery.com
www.hotasiantgp.com
www.hotassgallery.com
www.hotbbwgalleries.com
www.hotbbwgallery.com
www.hotbdsmtgp.com
www.hotbdsmthumbs.com
www.hotchubbyporn.com
www.hotfemdomgallery.com
www.hotlatexporn.com
www.hotlegsporn.com
www.hotlesbianlicking.com
www.hotlesbiansorgy.com
www.hotnylontgp.com
www.hotpainsex.com
www.hotpornretro.com
www.hotpublicporn.com
www.hotpublicsex.com
www.hotsluttybutts.com
www.hotstraponporn.com
www.hotswingerspictures.com
www.hotswingersporn.com
www.hotupskirtshots.com
www.hotvintagepictures.com
www.hotvoyeurporn.com
www.hotvoyeursex.com
www.hotxxxass.com
www.hqcfnm.com
www.inpublicflashing.com
www.juicyassporn.com
www.latexbest.com
www.latexerotic.com
www.latexfetishpics.com
www.latexleatherporn.com
www.latexporngirls.com
www.legsthumbs.com
www.lingeriepornfree.com
www.lingeriepornguide.com
www.lingeriethumbs.com
www.mybdsmlibrary.com
www.nudelingeriepics.com
www.nudenylon.com
www.nudepublicporn.com
www.nudevoyeurgalleries.com
www.nylonstockingsex.org
www.onpublicporn.com
www.paintgp.com
www.perfectassporn.com
www.perfectbuttfuck.com
www.perfectfemdom.com
www.pornbbwpics.com
www.pornbondagegalleries.com
www.pornnylons.com
www.privatevoyeurweb.net
www.publicerotic.com
www.publicfuckspy.com
www.publicporntgp.com
www.realfemdomsex.com
www.realstraponporn.com
www.retropornarchives.com
www.retroporngallery.com
www.retrothumbs.com
www.ropebondageporn.com
www.sexcfnm.com
www.sexyboobsporn.com
www.sexychubbyporn.com
www.sexylatexfetish.com
www.sexylatexpics.com
www.sexylesbiangalleries.com
www.sexylingerietgp.com
www.sexynylongalleries.com
www.sexyupskirtporn.com
www.spankinghotporn.com
www.spicyasianporn.com
www.spicyass.com
www.straponhot.com
www.straponit.com
www.straponlive.com
www.straponsextgp.com
www.superbdsm.com
www.swingerfreeporn.com
www.swingerlust.com
www.swingerspornparties.com
www.swingersxxxpics.com
www.swingerthumbnails.com
www.thefemdomporn.com
www.thefemdomsex.com
www.titssuper.com
www.titsthumbnails.com
www.truevoyeurphotos.com
www.upskirtpussyspy.com
www.upskirtviewers.com
www.vintagehotporn.com
www.vintagehunterporn.com
www.vintagethumbnails.com
www.xxxbdsmtgp.com
www.xxxbondagegalleries.com
www.xxxlatexladies.com
www.xxxnylonpics.com
```
</details>

### What happens?

Premium ADS / BANNERS all over the page.
By the way all the websites are [LINK FARMS](https://en.wikipedia.org/wiki/Link_farm).

Mainpages like `http://hotmaturetgp.com/`  contains 3 blocks of banners, each block contains 3 big banners and 16 smaller banners:
They are basically placed between thumbnails.
The 1st block is located  in the middle of the page.
The 2nd block is located again further in the middle of the page.
The 3rd block is located at the bottom, it also contains 16 additional smaller banners.
All of them can be easily hidden by `pornsite1.com,pornsite2.com,...##.contentrow` filter.

Subpages like `http://hotmaturetgp.com/horny-matures-t7l/` contains 7 premium banners: 1 alone banner + 2 blocks of 3 banners.
They are basically placed between thumbnails.
The 1st alone banner is placed at the top-right.
The 2nd block of 3 banners is located  in the middle of the page.
The 3nd block of 3 banners is located at the bottom.
The 1st and the 3rd can be easily hidden by `pornsite1.com,pornsite2.com,...##.content` filter.
The 2nd can be easily hidden by `pornsite1.com,pornsite2.com,...##.space` filter.

So the final solution combines 3 cosmetic filters into a single one easy filter: 
`pornsite1.com,pornsite2.com,...##.space, .content, .contentrow`. 
Just don't try to add it as a generic filter, because it will break many legitimate porn unrelated websites.

### List Subscriptions you're using:

<details>
<summary>spoiler</summary>

`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`
</details>

### Your settings

- OS/version: Win 7 64 Pro SP1
- Browser/version: FF 76.0.1
- Adblock Extension/version: uBO 1.27.6

### Other details / screenshoots:

Example screenhoots NSFW: 

Main page: `http://hotmaturetgp.com/` ==> 
`https://user-images.githubusercontent.com/43844449/82732109-761c7900-9d0b-11ea-9ec4-8131fe6e02bf.jpg`

Subpage: `http://hotmaturetgp.com/horny-matures-t7l/` ==> 
`https://user-images.githubusercontent.com/43844449/82732354-060ef280-9d0d-11ea-91c8-6e16b39595cd.jpg`

**Comment by kulfoon** [comment]
### Premium ADS/BANNERS on 41 pornsites ###reclama NSFW

### List the website(s) you're having issues:

NSFW 38  `https://publicwww.com/websites/%22%3Cdiv+class%3D%5C%22one_rec%5C%22%3E%22/`


<details not-open>
<summary>NSFW 41 pornsites (33 domains):</summary>

```
allshemalemodels.com
alltrannypics.com
alltrannystars.com
asianladyboypictures.com
asianladyboyspics.com
asianladyboyssex.com
asianshemalesex.com
freshshemalepics.com
justshemalepics.com
justshemaletube.com
ladyboypornpictures.com
myladyboys.com
onlyshemalepics.com
shemalecollection.com
shemaledatabase.com
shemaledb.net
shemalefreepictures.com
shemalemodeldb.com
shemalemodellist.com
shemalepornstartube.com
shemalexxxpictures.com
shemalexxxstars.com
thailadyboysex.com
thailandshemale.com
thaishemalesex.com
topladyboy.com
trannysuperstar.com
transsexpics.com
www.allshemalemodels.com
www.alltrannypics.com
www.alltrannystars.com
www.asianladyboyssex.com
www.hqladyboys.com
www.ourladyboy.com
www.shemaledb.net
www.shemalexxxstars.com
www.teenladyboy.net
www.thailadyboyporn.com
www.thailadyboysex.com
www.transsexpics.com
xladyboys.com
```

</details>


### What happens?

Premium ADS BANNERS on mainpage, 3 blocks x 3 banners,
Basically they are placed between thumbnails
Solution: `pornsite1.com,pornsite2.com,...###reclama`

### List Subscriptions you're using:

<details>
<summary>spoiler</summary>


`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`
</details>

### Your settings

- OS/version: Win 7 64 Pro SP1
- Browser/version: FF 76.0.1
- Adblock Extension/version: uBO 1.27.6

### Other details / screenshoots:

NSFW : mainpage `http://shemaledb.net/` : `https://user-images.githubusercontent.com/43844449/82747784-e6bfa600-9d9c-11ea-866a-c07e99f90029.jpg`

**Comment by kulfoon** [comment]
### Premium ADS/BANNERS on about 17 pornsites ##.screens NSFW

### List the website(s) you're having issues:

NSFW 17  pornsites `https://publicwww.com/websites/%22%3Ctable+class%3D%5C%22screens%5C%22%22/`


<details not-open>
<summary>NSFW Found so far 13 pornsites (10 domains):</summary>

```
ahtranny.com
bestfatclips.com
bigwomenvideo.com
maturebrothel.com
megafat.com
oldpoon.com
totallyshemales.com
trannypower.com
unrealshemales.com
www.ahtranny.com
www.totallyshemales.com
www.trannybeat.com
www.trannypower.com
```

</details>


### What happens?

Premium ADS BANNERS on mainpage, 4 blocks x 3 banners,
Basically they are placed between thumbnails
Solution: `pornsite1.com,pornsite2.com,...##.screens`

### List Subscriptions you're using:

<details>
<summary>spoiler</summary>


`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`
</details>

### Your settings

- OS/version: Win 7 64 Pro SP1
- Browser/version: FF 76.0.1
- Adblock Extension/version: uBO 1.27.6

### Other details / screenshoots:

NSFW : mainpage `http://ahtranny.com/` : 
`https://user-images.githubusercontent.com/43844449/82749984-605f9000-9dad-11ea-93b7-739439ec1b6d.jpg`

**Comment by kulfoon** [comment]
### Ads on pornsites - EXADS Anti-AdBlock solution - 121 webpages [NSFW]

https://github.com/uBlockOrigin/uAssets/issues/6151#issuecomment-629804631 
(https://github.com/uBlockOrigin/uAssets/issues/6151#issuecomment-629851873)

**Comment by kulfoon** [comment]
### "Latest updates on other shemale porn tubes" BANNERS - 154 pornsites NSFW

### List the website(s) you're having issues:

NSFW 154  pornsites `https://publicwww.com/websites/%22iie8.com%2Fa%2Fthumbtoplist%22/`
Example site: `http://trannylovertube.com/`

</details>


### What happens?

"Latest updates on other shemale porn tubes" BANNERS on mainpage, 3 blocks x 12 banners,
Basically they are placed between thumbnails
Solution: 
```
!||d.z5o.net/i/*/*.com.jpg$third-party,image
!||d.z5o.net/a/thumbtoplist/*/*/*.jpg$third-party,image
! d.z5o.net now redirects to iie8.com
||iie8.com/i/*/*.com.jpg$third-party,image
||iie8.com/a/thumbtoplist/*/*/*.jpg$third-party,image
```
or you can try to find a cosmetic filter solution.

### Other details / screenshoots:

NSFW : mainpage `http://trannylovertube.com/` : 
`https://user-images.githubusercontent.com/43844449/82803423-c8cb7180-9e80-11ea-8ca6-7145427d5636.jpg`

**Comment by spirillen** [comment]
Hey @kulfoon That is a impressive list you have collected there.

Is these domains, those that covers all the above ads?

```
d.z5o.net
iie8.com
```
