### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by IsraeliUser** [easylist/easylist#5398]
Please replace
``/http://[a-zA-Z0-9]+\.[a-z]+\/.*(?:[!"#$%&'()*+,:;<=>?@/\^_`{|}~-]).*[a-zA-Z0-9]+/$script,third-party,domain=...``

`/^http*.:\/\/.*[?|=|&|%|#|+].*/$popup,domain=femefun.com`

with
``/^https?:\/\/[a-zA-Z0-9]+\.[a-z]+\/.*(?:[!"#$%&'()*+,:;<=>?@/\^_`{|}~-]).*[a-zA-Z0-9]+/$script,third-party,domain=...``

`/^https?:\/\/.*[?|=|&|%|#|+]/$popup,domain=femefun.com`

( explanation: https://github.com/easylist/easylist/issues/2550#issuecomment-526589525 ) 

----

Any reason not to use
`|about:blank|`
instead of
`/about:blank.*/$popup,domain=...`
`/about:blank.*/$popup,domain=katestube.com`
(two different filters)
?
It's supposed to be more efficient.
(anyway you can omit the `.*`)

**Comment by kulfoon** [comment]
Also `|` pipes (**OR** operator) is to be used in round brackets `()`, and not in square brackets `[]`, square brackets don't need **OR** operator so `[?|=|&|%|#|+]` ==> `[?=&%#+]`

**Comment by kulfoon** [comment]
> IsraeliUser  : `https?`

You're my boss, I was always using `http(|s)` and thought it was the shortest and simplest, until now...

**Comment by DandelionSprout** [comment]
Is it even necessary to use `|` inside square brackets? My experience is that IsraeliUser's 2nd suggestion could be further compressed into `/^https?:\/\/.*[?=&%#+]/$popup,domain=femefun.com`.

Pretty much the *only* character one has to be careful with in square brackets, is the regular dash.

**Comment by kulfoon** [comment]
> DandelionSprout : Pretty much the only character one has to be careful with in square brackets, is the regular dash,

Pretty much not.

**Comment by IsraeliUser** [comment]
You are right:
`[?|=|&|%|#|+]` -> `[?=&%#+]`

also found in another filter:
`/^https?:\/\/.*[&|%|+|=]/$popup,domain=...` -> `/^https?:\/\/.*[&%+=]/$popup,domain=...`

---
`/^https?:\/\/.*\.(info|pro|icu|app|xyz|app|pet|win|live|me|io|cc|pw|is|zone|bid|cf|ovh|site|review|ml|xyz)\.?(\/|:|$)/$popup,domain=...`

`/^https?:\/\/.*\.(info|pro|icu|app|xyz|app|pet|win|live|me|io|cc|pw|is|zone|bid|cf|ovh|site|review|ml|xyz)\.?(\/|:|$)/$image,script,stylesheet,xmlhttprequest,domain=kimcartoon.to|thepiratebay.org`

There are 2 `xyz`'s in each filter. You can remove one of them.

**Comment by gwarser** [comment]
> * the first bug is the major one found already by IsraeliUser: an unescaped pair of forwardslashes `//` ==> `\/\/` such bug makes the whole regex broken

This isn't that bad. It's only important in regex literals - when you type this directly in JavaScript source code. Blockers parse these filters and compile in RegExp constructors where it does not matter. 

```javascript
var r = new RegExp('exam\/ple');
r.test('exam/ple')
true
var r = new RegExp('exam/ple');
r.test('exam/ple')
true
/exam\/ple/.test('exam/ple')
true
/exam/ple/.test('exam/ple')
Uncaught SyntaxError: invalid regular expression flag p
```

Still good to have if you copy them to testers / from creators.

**Comment by IsraeliUser** [comment]
@DandelionSprout 

Suffixes: 
`.*/$` -> `/$`   (8 filters or 6 if you replace `/about:blank.*/` with ``|about:blank|`` as I suggested)
`(.*)/$` -> `/$`   (1 filter)
(the `$` is not part of the regex)
You can use _Search and Replace_.

Can you make a pull request?

**Comment by IsraeliUser** [comment]
@ryanbr 

`/http://[a-zA-Z0-9]+\.[a-z]+\/.*(?:[\W_]).*[a-zA-Z0-9]+/$script,third-party,domain=keezmovies.com|redtube.com|tube8.com|tube8.es|tube8.fr|www.pornhub.com|www.pornhubthbh7ap3u.onion|youporn.com`
->
`/^http:\/\/[a-zA-Z0-9]+\.[a-z]+\/.*(?:[\W_]).*[a-zA-Z0-9]+/$script,third-party,domain=keezmovies.com|redtube.com|tube8.com|tube8.es|tube8.fr|www.pornhub.com|www.pornhubthbh7ap3u.onion|youporn.com` (blocks http only)
**OR**
`/^https?:\/\/[a-zA-Z0-9]+\.[a-z]+\/.*(?:[\W_]).*[a-zA-Z0-9]+/$script,third-party,domain=keezmovies.com|redtube.com|tube8.com|tube8.es|tube8.fr|www.pornhub.com|www.pornhubthbh7ap3u.onion|youporn.com` (blocks both http and https)




`/^http*.:\/\/.*[?=&%#+].*/$popup,domain=femefun.com`
->
`/^https?:\/\/.*[?=&%#+]/$popup,domain=femefun.com`
