### ISSUE TITLE
theguardian social list

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#54]
https://www.theguardian.com/science/2016/jun/13/new-jupiter-like-planet-is-largest-yet-discovered-orbiting-two-stars-kepler-1647b

Social list causes `Save For Later` and `Comments` to overlap the article when your browser window is narrow (not maximized).

**Comment by monzta** [comment]
I cannot reproduce this. Could you post a screenshot?

**Comment by terrorist96** [comment]
Looks to be fixed.

**Comment by terrorist96** [comment]
@monzta actually it's still broken on this article:

https://www.theguardian.com/technology/2016/aug/02/apple-replaces-gun-emoji-water-pistol-revolver-violence-debate
