### ISSUE TITLE
drtuber.com + iceporn.com [breakage] [EasyList] NSFW

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#5400]
### List the website(s) you're having issues:

Example broken video subpage: 
`https://www.drtuber.com/video/4706145/private-casting-x-vegas-teeny-fake-casting-fuck#`
`https://www.iceporn.com/video/4315144/amateur-swinger-cuckold-threesome`

### What happens?

A breakage - video won't play.
A filter causing it is: `||cdn13.com^$script,third-party,domain=~leafy.pro` from EasyList
Solution: add an exclusion: `|~drtuber.com|~iceporn.com`
### List Subscriptions you're using:

<details not-open>

<summary>spoiler</summary>

`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`
</details>

### Your settings

- OS/version: Win 7 64 Pro SP1
- Browser/version: FF 76.0.1
- Adblock Extension/version: uBO 1.27.6

**Comment by ryanbr** [comment]
Is this an issue? video playbacked fine

**Comment by Khrin** [comment]
Possibly another CNAME issue with ubo?

**Comment by kulfoon** [comment]
Weird

Still an issue, on the both websites, on both Firefox and Opera, the websites send requests to `cdn13.com` script, which are blocked by EasyList and video won't load.

<details not-open>
<summary>screenshoot Firefox</summary>

![2](https://user-images.githubusercontent.com/43844449/83349157-e1c99c00-a332-11ea-925f-5a5f03a3004b.gif)

</details>

However on another Firefox profile with same lists, there is no issue, because the websites don't make requests to `cdn13.com` script and videos play fine.

**Comment by ryanbr** [comment]
Loaded fine here, a fix is in uBO unbreak
