### ISSUE TITLE
annoyance: theverge.com

### ISSUE THREAD

**Issue by B0pol** [easylist/easylist#5403]
### List the website(s) you're having issues:

https://www.theverge.com/2019/7/11/20690020/google-assistant-home-human-contractors-listening-recordings-vrt-nws
### What happens?

The cookie notice is shown. It shouldn't, I enabled annoyance list.
### List Subscriptions you're using:
Easylist cookie and default ublock origin lists.

### Your settings

- OS/version: android 9, fedora 32
- Browser/version: firefox preview 5.0, firefox 77 (Developer edition).
- Adblock Extension/version: ublock origin 1.27.6

### Other details:

![Screenshot_20200525-211843_Firefox_Preview](https://user-images.githubusercontent.com/58657617/82838910-f8ed3180-9ecd-11ea-80be-4a2ab6cd706c.png)
On this screenshot, I was on android with several other lists and extensions (you can see darkreader here).

Here, I ran Firefox Developer edition with only one extension: ublock origin, with only one list: easylist cookie (+ the default ublock origin lists).
![fanboy's_annoyance](https://user-images.githubusercontent.com/58657617/82839161-bed05f80-9ece-11ea-90a8-d4a0ac10e250.png)

**Comment by krystian3w** [comment]
Can't blocked, break embeded players (other than YouTube).

**Comment by krystian3w** [comment]
Also **Fenix** no have support for Adblock Plus extension or legacy proxy version.

**Comment by B0pol** [comment]
Fenix has support for Ublock origin, which provides easylist cookie in filter lists section.
BTW why are you downvoting?

**Comment by soshial** [comment]
Maybe there is a way to hide it? I succeeded with this rule:
`www.theverge.com##.m-privacy-consent__inner`

**Comment by krystian3w** [comment]
Nope, page analyze "backed" cookies/localstorage not what element is hidden.

**Comment by soshial** [comment]
Do you mind elaborating your answer. I really didn't any of it.

**Comment by llacb47** [comment]
Basically you need to consent to cookies or you can't play any videos on vox media sites.
