### ISSUE TITLE
Consider adding tiqcdn.com as fingerprinting 

### ISSUE THREAD

**Issue by UmarIqbal** [easylist/easylist#5405]
Fingerprinting scripts from tiqcdn.com are embedded on several websites. The live version of the script is available here: `https://tags.tiqcdn.com/utag/mediaset/med.wittytv.it/prod/utag.71.js?utv=ut4.42.201911270923`
It was found on `https://www.wittytv.it/`

Canvas fingerprinting code from the script:

```
 getCanvasFingerprint: function() {
                    var a = document.createElement("canvas"),
                        b = a.getContext("2d"),
                        c = "Mr. Jock, TV quiz Ph-D, bags few lynx!",
                        d = "Ù©(Í¡à¹Ì¯Í¡à¹)Û¶Ù©(-Ì®Ì®Ìƒâ€¢Ìƒ)Û¶Ù©(Ì¾â—Ì®Ì®ÌƒÌ¾â€¢ÌƒÌ¾)Û¶Ù©(-Ì®Ì®Ìƒ-Ìƒ)Û¶(Í¡Â°ÍœÊ–Í¡Â°)";
                    return b.textBaseline = "top", b.font = "14px 'Arial'", b.textBaseline = "alphabetic", b.fillStyle = "#f60", b.fillRect(125, 1, 62, 20), b.fillStyle = "#069", b.fillText(c, 2, 15), b.font = "18pt 'BKNOFONT'", b.fillStyle = "rgba(102, 204, 0, 0.7)", b.fillText(c, 4, 17), b.font = "11pt Arial", b.fillStyle = "rgba(204, 0, 102, 0.6)", b.fillText(d, 1, 11), b.font = "15pt 'BKNOFONT'", b.fillStyle = "rgba(204, 126, 0, 0.3)", b.fillText(d, 3, 13), a.toDataURL();
                }
```

The script URL seems to vary for each website. 
For example: `https://tags.tiqcdn.com/utag/mediaset/med.virginradio.mediaset.it/prod/utag.104.js?utv=ut4.44.202003120755` is embedded on `https://www.virginradio.it/`

Some other websites on which it is embedded:

```
http://www.huanyuju.com/
http://www.wittytv.it/
https://gaffa.dk/
https://meraki.cisco.com/
https://www.105.net/
https://www.barrons.com/
https://www.chotot.com/
https://www.dsw.com/en/us/
https://www.lenscrafters.com/
https://www.lfg.com/public/individual
https://www.mazdausa.com/
https://www.meteo.it/
https://www.orange.es/
https://www.sling.com/
https://www.sunglasshut.com/
https://www.virginradio.it/
https://www.wsj.com/
https://yousee.dk/
```

**Comment by Khrin** [comment]
I think it will be a little complicated to block it. We have listed it a few years ago in EasyPrivacy but if I remember correctly the rule was removed due to the many false postives.

**Comment by UmarIqbal** [comment]
Yeah that's understandable since tiqcdn appears to be CDN. It shouldn't get an easy way out but not sure what's the best thing to do here.

**Comment by llacb47** [comment]
I don't think tiqcdn actually collects any data. It's just scripts (tag manager) calling/invoking other trackers/pixels etc.

**Comment by ryanbr** [comment]
Ideally we polyfill tiqcdn with a custom snippet, because as @Khrin indicated it causes many false positives

**Comment by spirillen** [comment]
Well I can supply with a bit of shared knowledge, I have been blocking the following third level domains for years, without any comments.

|id|name|
|--|----|
|3349227|tags.tiqcdn.com.rpz.mypdns.cloud|
|3349228|akamai.tags.tiqcdn.com.rpz.mypdns.cloud|
|3349229|edgecast.tags.tiqcdn.com.rpz.mypdns.cloud|
|3349230|tags-eu.tiqcdn.com.rpz.mypdns.cloud|

The id 3.xxx.xxx indicates it have been imported from external sources almost two years ago)

So why shouldn't it be possible to at `tags.tiqcdn.com` to the list? What FP is it you should have seen?

**Comment by Yuki2718** [comment]
IIRC Peter Lowe's added this several months (or possibly a year+) back and uBlock filters has been redirecting them to noop.js, while at the time AdGuard Spyware blocked them very selectively with a warning comment. I haven't experienced any noticeable trouble but it may be due to uBlock filters.
