### ISSUE TITLE
foreignaffairs.com

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#5406]
### List the website(s) you're having issues:

`https://www.foreignaffairs.com/articles/united-kingdom/2020-04-13/britain-adrift`

### What happens?

Annoyances: cookie warning and subscription popup

![foreignaffairs2](https://user-images.githubusercontent.com/58900598/82878962-3bb71400-9f77-11ea-8d30-13c4178f4305.png)

### List Subscriptions you're using:

uBO's default ones + Fanboy Annoyances + uBlock Annoyances

### Your settings

- OS/version: Windows 10
- Browser/version: Brave 1.9.72 (its blocker turned off)
- Adblock Extension/version: uBO 1.26.0

### Other details:

Related: https://github.com/uBlockOrigin/uAssets/pull/7461

**Comment by ryanbr** [comment]
I don't normally target non-cookie messages, but since they're sharing the same div. and he its not breaking the site. Its fine.
