### ISSUE TITLE
indishare.org

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#5408]
### List the website(s) you're having issues:

`https://www.indishare.org/qdnmmyming8a`

### What happens?
Popup ads

### List Subscriptions you're using:

Ublock origin default lists

### Your settings

- OS/version: android
- Browser/version: firefox 68
- Adblock Extension/version: ublock origin 1.27.7.3

**Comment by ryanbr** [comment]
Seems fine? can you confirm @ghajini

**Comment by ghajini** [comment]
@ryanbr 

Platform= firefox android, ublock origin stable

Click **create download link**
in next page when you click anywhere in page popup ads appears

This filter fixes on my end
`||joyvowdig.com^`

**Comment by ghajini** [comment]
`||joyvowdig.com^`

@ ryanbr please tell whether it will be included in easylist?

![IMG_20200623_132853](https://user-images.githubusercontent.com/20338483/85376665-a434e900-b555-11ea-8ee2-79651912b76e.jpg)

**Comment by ghajini** [comment]
`https://www.indishare.org/a4v3a9vcp4rk`
`https://www.indishare.org/j7a8a80clfbg`
Popups 

@mapx-

**Comment by ghajini** [comment]
Fixed in ublock origin, don't know Easylist want to fix for other adblockers
cc @Khrin
