### ISSUE TITLE
Consider adding poool.fr as fingerprinting 

### ISSUE THREAD

**Issue by UmarIqbal** [easylist/easylist#5416]
Fingerprinting scripts from poool.fr are embedded on several websites. The live version of the script is available here: https://assets.poool.fr/cdn-cgi/bm/cv/1284585713/api.js

It was found on https://actu.fr/

Canvas fingerprinting code from the script:

```
try {
    var D = document.createElement("canvas");
    D.width = g.width;
    D.height = g.height;
    D.style.display = "none";
    var A = D.getContext("2d"),
        P = Array.from(h, function() {
            return 0
        });
    P[1] = 1;
    for (var da = Math.floor(2 * l / h.length), F = l - 1, p = 0; p < F; p++) {
        e(A, g);
        for (var m = d(h.length); P[m] >= da;) m = (m + 1) % h.length;
        (0, h[m])(A, g, p) && A.fill();
        A.shadowBlur = 0;
        P[m]++
    }
    return h[1](A, g, F), D.toDataURL()
} catch (t) {}
```

Reading other device properties:

```
function g(a) {
    return {
        r: h(function() {
            return [a.screen.width, a.screen.height]
        }),
        ar: h(function() {
            return [a.screen.availHeight, a.screen.availWidth]
        }),
        pr: a.devicePixelRatio,
        cd: a.screen.colorDepth,
        wb: !(!a.navigator || !a.navigator.webdriver),
        wp: !(!a.callPhantom && !a._phantom),
        wn: !!a.__nightmare,
        ch: !!a.chrome,
        ws: !!(a.document.__selenium_unwrapped || a.document.__webdriver_evaluate || a.document.__driver_evaluate),
        wd: !(!a.domAutomation && !a.domAutomationController)
    }
}
```

Some other websites on which it was embedded:

```
https://actu.fr/
https://www.centrepresseaveyron.fr/
https://www.challenges.fr/
https://www.charentelibre.fr/
https://www.ladepeche.fr/
https://www.lagazettedescommunes.com/
https://www.lamontagne.fr/
https://www.lavenir.net/
https://www.lechorepublicain.fr/
https://www.letelegramme.fr/
https://www.lindependant.fr/
https://www.midilibre.fr/
https://www.paris-normandie.fr/
https://www.sciencesetavenir.fr/
https://www.usinenouvelle.com/
https://www.valeursactuelles.com/
```

**Comment by llacb47** [comment]
_Supposedly_ no more fingerprinting is taking place. https://github.com/disconnectme/disconnect-tracking-protection/issues/152

This script is used for paywalls, easylist/easyprivacy doesn't block that to my knowledge.
See: `https://poool.tech/about`

**Comment by UmarIqbal** [comment]
pool.fr used to embed fingerprinting from: https://assets.poool.fr/poool-identity.min.js but looks like they have moved their fingerprinting code to : https://assets.poool.fr/cdn-cgi/bm/cv/1284585713/api.js 

Also, https://assets.poool.fr/cdn-cgi/bm/cv/1284585713/api.js appears to send XHR requests with collected identifiers. I just debugged the script and found that several of the collected identifiers are shared back to the server with request https://assets.poool.fr/cdn-cgi/bm/cv/result?req_id=599b3fe949400368

**Comment by llacb47** [comment]
I only see one POST request, nothing too bad.
![image](https://user-images.githubusercontent.com/16567977/82966827-c446ac00-9f99-11ea-9213-1af61edd83a7.png)

**Comment by UmarIqbal** [comment]
Check this (You can find it by observing this request: https://assets.poool.fr/cdn-cgi/bm/cv/result?req_id=599b3fe949400368). When you debug the script (https://assets.poool.fr/cdn-cgi/bm/cv/1284585713/api.js)
<img width="1125" alt="Screen Shot 2020-05-26 at 8 44 16 PM" src="https://user-images.githubusercontent.com/5169133/82966988-b725bf00-9f91-11ea-8aa9-ffde3ad21efa.png">

**Comment by llacb47** [comment]
Yes, but how can I reproduce this request?

**Comment by UmarIqbal** [comment]
I am not doing anything unique. It just appears in the network tab, when I load the page. If you see this script https://assets.poool.fr/cdn-cgi/bm/cv/1284585713/api.js in source try putting a break point on last line `b.send(JSON.stringify(e));`

**Comment by ryanbr** [comment]
Related
https://forums.lanik.us/viewtopic.php?f=64&t=41269&p=139088

**Comment by ryanbr** [comment]
ddg:
https://github.com/duckduckgo/tracker-radar/blob/994048d76165c7bf669e375ea62f0b150482eb10/domains/poool.fr.json

**Comment by UmarIqbal** [comment]
From ddg:
```
"HTMLCanvasElement.prototype.toDataURL": 12,
"Screen.prototype.width": 14,
"Screen.prototype.height": 14,
"Screen.prototype.availHeight": 14,
"Screen.prototype.availWidth": 14,
"window.devicePixelRatio": 22,
"Screen.prototype.colorDepth": 14
```
Reading a lot of unique values. If you see my screenshot above #you can see these values being shared.

**Comment by ryanbr** [comment]
Reaching out via twitter, but if I get no response. We'll re-add it.

https://twitter.com/fanboynz/status/1266541355838263296

**Comment by llacb47** [comment]
@dackmin @p3ol

**Comment by dackmin** [comment]
I don’t even know what that url is. Our script is located at https://assets.poool.fr/poool.min.js and everything is loaded from the root path. We removed every bit of fingerprinting code and our API doesn’t even use the header we used to pass identifier into anymore. I think this is a cache artifact coming from the cdn or something similar. It’s the middle of the night here so will investigate in a few hours. Thanks!

**Comment by dackmin** [comment]
30sec google search and I can confirm that definitely doesn't belong to us: https://community.cloudflare.com/t/strange-code-showing-on-my-site/159896/2

That's the bot protection from Cloudflare.

**Comment by dackmin** [comment]
I was able to replicate this: https://jsfiddle.net/2vrhsp5b/, even with a random subdomain.
This thing is looking for `window.__CF$cv$params` before being triggered, which, it appears, should be an object with an `s` property and a `Symbol.iterator`. It seems to be trying to polyfill something like `URLSearchParams`.

**Comment by dackmin** [comment]
@ryanbr maybe you can reach out to Cloudflare about their FP piece of code, or try to block something like `*/cgi-bin/bm/cv/*` (I'm not really familiar with easylist patterns)

**Comment by ryanbr** [comment]
Okay, done. thanks for confirming and feedback @dackmin
