### ISSUE TITLE
kaspersky.com

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#5420]
### List the website(s) you're having issues:

`https://www.kaspersky.com/blog/category/news/`

### What happens?

Page breakage; `@@||assets.kasperskydaily.com^*/jquery.smartbanner.css` is included in Annoyances but `/jquery.smartbanner.` is now also in Notifications list which can be subscribed as a stand-alone list yet doesn't have the whitelist. Anyway the whitelist is not enough, script is also need to be allowed to load images like `@@||assets.kasperskydaily.com/blog/wp-content/plugins/bwp-minify/min/?f=wp-content/plugins/kaspersky-app-banners/lib/smartbanner/jquery.smartbanner.$domain=kaspersky.com`

![kaspersky1](https://user-images.githubusercontent.com/58900598/83129071-3db7d900-a117-11ea-950d-1f04659ac111.png)

![kaspersky2](https://user-images.githubusercontent.com/58900598/83129082-40b2c980-a117-11ea-9c3e-753d6c79fa12.png)

### List Subscriptions you're using:

uBO default + Fanboy's Notifications Blocking

### Your settings

- OS/version: Windows 10
- Browser/version: Brave 1.9.72 with its blocker turned off
- Adblock Extension/version: uBO 1.26.0

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/137d375f7e8f646addfbf87d117832ec8d43a5db

**Comment by Yuki2718** [comment]
@ryanbr Can you add $stylesheet too for those who subscribe Notifications list alone?

**Comment by ryanbr** [comment]
Is $stylesheet needed? and Notifications list is part of Annoyances

**Comment by Yuki2718** [comment]
> 
> Is $stylesheet needed? 

Without $stylesheet the layout is broken.

![kaspersky](https://user-images.githubusercontent.com/58900598/83402769-53444000-a442-11ea-8db5-60912c20cda6.png)

> and Notifications list is part of Annoyances
I know, however, the list is also provided as a stand-alone list just like Social Blocking List.
https://adblockplus.org/subscriptions
So I guess the existing whitelist `@@||assets.kasperskydaily.com^*/jquery.smartbanner.css` in Annoyances can be moved to Notifications list.
