### ISSUE TITLE
wix.com [breakage] [EasyList and AdGuard Tracking Protection] 

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#5438]
### List the website(s) you're having issues:

`https://pl.wix.com/`

### What happens?

Breakage - while trying to register or after registering, while trying to setup the hosting / choose options, several pages get's broken / some elements don't appear, and because of that, it's not possible to use hosting service, it's caused by two filters:
`||frog.wix.com^` from EasyList and
`||frog.wix.com^$third-party` from AdGuard Tracking Protection
### List Subscriptions you're using:

<details>
<summary>spoiler</summary>

`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`
</details>

### Your settings

- OS/version: Win 7 64 Pro SP1
- Browser/version: FF 76.0.1
- Adblock Extension/version: uBO 1.27.6

### Other details / screenshoots:

**Comment by ryanbr** [comment]
Does this help?

https://github.com/easylist/easylist/commit/06b134496db9279bd7063d2f3f57d3f1f2243650

**Comment by kulfoon** [comment]
Yes, it does.
