### ISSUE TITLE
proglib.io

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/easylist#5449]
`https://proglib.io/`

### What happens?

proglib.io##.basis__h-content ~> **EasyList Cookie **

Blocked content
https://imgur.com/gVTsN0D
https://imgur.com/vvIu8ei

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/57287308/83351757-67f3db80-a34f-11ea-878a-b6ec9952207f.png)

- OS/version:  Win 10
- Browser/version:  Opera x64
- Adblock Extension/version:  uBO: 1.27.10

**Comment by krystian3w** [comment]
Better link to reproduce? 

Version:

```
[Adblock Plus 2.0]
! Checksum: uzNWiwKyPx37GcCwyDSDdw
! Version: 202006010621
! Title: EasyList
! Last modified: 01 Jun 2020 06:21 UTC
```

may no have filter.

**Comment by krystian3w** [comment]
Now possible use for cookies:

`proglib.io###cookie`

**Comment by P0Rtvine** [comment]
Fixed
https://github.com/easylist/easylist/commit/e346b6f3023ee2dc146806b786ed4147e16d09cc
