### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5451]
### List the website(s) you're having issues:
twitter

### What happens?
the profile pictures are missing with easylist cookie

### List Subscriptions you're using:
easylist, easylist fr, easylist cookie, ublock annoyances

### Your settings

- OS/version: 
- Browser/version: ff
- Adblock Extension/version: ublock origin

**Comment by thetawave** [comment]
EasyList Cookie specifically at fault

**Comment by Cigaes** [comment]
I confirm. Twitter became unusable a few hours ago, with most icons and a lot of necessary fields missing. Disabling EasyList Cookie makes it work.

**Comment by gorhill** [comment]
This was fixed in <https://github.com/easylist/easylist/commit/401a523e66c8190dc87b90d4196e4c2f0c389900>, force an update of EasyList Cookie (or one of the list containing it, i.e. Fanboy Annoyance)

**Comment by Technetium1** [comment]
I can confirm a forced update fixes this issue. Thank you!
