### ISSUE TITLE
24tv.ua

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/easylist#5453]
### List the website(s) you're having issues:

`https://24tv.ua/techno/`
`https://24tv.ua/`

### What happens?

Images are blocked

`/transparent-pixel.` ~> **Fanboy’s Annoyance**

![2020-06-01_175114](https://user-images.githubusercontent.com/57287308/83421274-81208900-a430-11ea-8177-7adc3172760b.png)
![2020-06-01_175511](https://user-images.githubusercontent.com/57287308/83421616-0f950a80-a431-11ea-8562-08bcd725eff5.png)

### List Subscriptions you're using:

![2020-06-01_175153](https://user-images.githubusercontent.com/57287308/83421333-972e4980-a430-11ea-8a9e-876d8577a47c.png)

### Your settings

- OS/version:  Win10
- Browser/version:  Opera x64
- Adblock Extension/version:  uBO 1.27.10

**Comment by krystian3w** [comment]
Unable reporduce on Firefox without ru  filters.

**Comment by krystian3w** [comment]
need exception

**Comment by P0Rtvine** [comment]
Can someone help?
![2020-06-04_130826](https://user-images.githubusercontent.com/57287308/83744256-8534ec80-a664-11ea-805a-654c92dc4921.png)

**Comment by krystian3w** [comment]
Only tested option with rewrite, but website no accept fake image.

https://help.eyeo.com/adblockplus/how-to-write-filters#rewrite

`Khrin` / `ryanbr` will decide which fix they'll use:

* `/transparent-pixel.$~image`
* `/transparent-pixel.$domain=~24tv.ua`
* `@@/transparent-pixel.$image,domain=24tv.ua`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/c78ece425de2661e222c7499ac4fad8736fc3c8b
