### ISSUE TITLE
linksbay.xyz

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#5455]
### List the website(s) you're having issues:

`https://linksbay.xyz/view/8MKjrPL8AO`

### What happens?

Popup ads

### List Subscriptions you're using:

Ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: opera stable
- Adblock Extension/version: ublock origin 1.27.10

### Other details:
Working filters in ublock origin 

`||ofttanmob.site^`
`||offgashah.club^`
`||thealterforce.com^`
`linksbay.xyz##[href^="https://bit.ly/"]`

**Comment by ryanbr** [comment]
Should be resolved, added related adservers.
