### ISSUE TITLE
mtgarena.pro

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#5467]
### List the website(s) you're having issues:
`https://mtgarena.pro/`

### What happens?
There is a empty placeholder for an ad on the bottom, and a "close" button.

the classname of the ad may change, it can be different depending on the current page

### Your settings

- OS/version: 
- Browser/version: firefox
- Adblock Extension/version:  ublock origin

**Comment by krystian3w** [comment]
Generic class, I suppose there won't be a filter more complicated than that:
```
mtgarena.pro##.sc-fznyYp.diPTFg
```

The problem will be how the name changes once a day or any refreshment...

**Comment by momala454** [comment]
i think the class name will change as in the past i already tried but the class name have changed

**Comment by krystian3w** [comment]
For my is stable, picker use other sort class as I used.

`##.sc-fznyYp.diPTFg` - my
`##.diPTFg.sc-fznyYp` - uBO

```html
<div class="sc-fznyYp diPTFg">
    <div class="vm-placement" data-id="5d7b5751d6864139e1ce8062"></div>
    <div title="Close" class="sc-fznLxA gQRraV">Close ×</div>
</div>

**Comment by momala454** [comment]
actually on the home page it's the same, but on some pages accessible when logged in it's different

`<div class="sc-fznYue jUeRsJ"><div class="vm-placement" data-id="5d7b5751d6864139e1ce8062"></div><div title="Close" class="sc-fzonjX hIMiPJ">Close ×</div></div>`

**Comment by krystian3w** [comment]
> but on some pages accessible when logged in it's different

The best way to describe it the fact that the logging changes class in `What happend section`.

If EasyList no add various version with `:-abp-has()`, version with `:-abp-properties(position: fixed)` won't work in uBO.

**Comment by momala454** [comment]
`mtgarena.pro#?#div[class^=sc-"]:-abp-has(> div.vm-placement)`

this filter doesn't work but this works
`mtgarena.pro#?#div[class^="sc-"]:-abp-has(> div.vm-placement)
`

**Comment by momala454** [comment]
what's the difference between #?#  and ## ?

**Comment by krystian3w** [comment]
ABP need `#?#` for filters with `:-abp-`. When omit they filter no works in ABP or AdBlock.

**Comment by DandelionSprout** [comment]
I propose:
```
mtgarena.pro#?##root > div > div:-abp-has(> .vm-placement)
mtgarena.pro#?##root > div:-abp-has(a[href*=casino])
```
