### ISSUE TITLE
telepolis.pl/logowanie

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#5471]
`https://www.telepolis.pl/logowanie`

Hidden logon with Facebook or Steam account.

![obraz](https://user-images.githubusercontent.com/35370833/83769884-b0c5d000-a680-11ea-8d8c-7a1f89ad2e58.png) |
--- |

bad filter:

```
##.social-media-icons
```

fix:

`telepolis.pl#@#.social-media-icons`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b99a733ce638eed4afe67ddc9988cba2ce9863bd
