### ISSUE TITLE
www9.fmovies.ag

### ISSUE THREAD

**Issue by jabonsolo** [easylist/easylist#5474]
### List the website(s) you're having issues:
`http://www9.fmovies.ag/watch/greys-anatomy-s16-2005-online-fmovies.html`

### What happens?
Popup ads

### List Subscriptions you're using:
EasyList

### Your settings
- OS/version: OSX / Windows
- Browser/version: Safari 13.0.4 / Google Chrome 83.0.4103.61 
- Adblock Extension/version:  ABP 3.8.4

### Other details:
- Site is blocking devtools
- Saw `estoopsi.com` throwing some popups but it's not the only server.

**Comment by llacb47** [comment]
Use ublock origin and test again

**Comment by jabonsolo** [comment]
@llacb47, sorry, I'm asking to solve this issue on EasyList not in ublock specifically. So everybody using the list can have the issue fixed.

**Comment by llacb47** [comment]
How noble of you, but it would be helpful to confirm if the issue persists in ublock origin.

**Comment by monzta** [comment]
@llacb47 Not sure I can follow. In what way would that be helpful?

**Comment by llacb47** [comment]
Never mind, sorry.
