### ISSUE TITLE
ga-beacon - githubusercontent being used for tracking

### ISSUE THREAD

**Issue by birdsarah** [easylist/easylist#5476]
At the bottom of https://github.com/GoogleChrome/chromium-dashboard

```html
<a href="https://github.com/igrigorik/ga-beacon">
    <img src="https://camo.githubusercontent.com/b1e431ec5f9c0cffdf00f71d5d958fe2122d6dfc/68747470733a2f2f67612d626561636f6e2e61707073706f742e636f6d2f55412d33393034383134332d322f476f6f676c654368726f6d652f6368726f6d69756d2d64617368626f6172642f524541444d45" alt="Analytics" data-canonical-src="https://ga-beacon.appspot.com/UA-39048143-2/GoogleChrome/chromium-dashboard/README" style="max-width:100%;">
</a>

**Comment by krystian3w** [comment]
uBO / Nano  with html filtering:

`github.com##^a[href*="ga-beacon"]`

---

AdGuard with html filtering:

`github.com$$a[href="https://github.com/igrigorik/ga-beacon"]`

AdGuard HTML filtering still no support `[href*="..."]` for any attribs maybe more generic:

`github.com$$a[tag-content="alt=\"Analytics\""]`

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#tag-content-attribute
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#wildcard-attribute

**Comment by birdsarah** [comment]
Thanks @krystian3w, I added to this to my custom filters. 

Would easylist be interested in this as a PR?

Not sure what the thumb down from @llacb47 is about? Can you clarify @llacb47?

**Comment by llacb47** [comment]
I'm not sure if this is actually doing any tracking, seems broken. Looking in network requests in devtools I don't see any going to `ga-beacon.appspot.com`. The `camo.githubusercontent.com` request is static (not tracking) and is just loading the badge image.

**Comment by krystian3w** [comment]
Maybe SVG graphic can count how many people viewed repo after parse HTML?

I don't think the Github downloaded this SVG once every decade.

---

Locking each url separately from `camo.githubusercontent.com` as it is pointless for me, will make such a dump as in "`EasyList Macedonia`" filtering base64 graphics to reduce the data limit (bandwidth) by several kilobytes.

**Comment by birdsarah** [comment]
Agreed @llacb47, thanks. More info here: https://github.com/igrigorik/ga-beacon/commit/6acd8627bb7be36f24f5516e9873c92719a50e55

**Comment by krystian3w** [comment]
> Would easylist be interested in this as a PR?

I suppose nope, Eeyo / ABP servers don't download files for uBO/AdGuard:

`https://easylist-downloads.adblockplus.org/easylistczechslovak+easylist.txt`
```
!
! ---------- uBlock Extended filters ---------- !
!
!#include filters_ublock.txt
! *** easylist.txt ***
! Licence: https://easylist.to/pages/licence.html
```
`https://easylist-downloads.adblockplus.org/filters_ublock.txt` - error 404...

**Comment by krystian3w** [comment]
Also Chrome don't support HTML Filtering without use AdGuard app with paid license:

`https://adguard.com/pl/adguard-windows/overview.html`
`https://adguard.com/pl/adguard-mac/overview.html`

For android license is no needed for browsers to work:

`https://adguard.com/pl/adguard-android/overview.html`
