### ISSUE TITLE
Blocking too restrictive

### ISSUE THREAD

**Issue by fiddlerwoaroof** [easylist/easylist#548]
If I'm reading this right, the rule

```
/\:\/\/[a-z0-9]{5,}\.com\/[A-Za-z0-9]{3,}\/$/$script,stylesheet,third-party,xmlhttprequest
```

Blocks all indirect requests to all third-party domains who's domain name is longer than 5 alphanumeric characters with only one alphanumeric path segment with more than 3 alphanumeric characters.  This seems like it is much too sweeping and will produce a whole bunch of false positives.  This is currently breaking an application I've been developing that loads data from json stored at `https://somedomain.com/current/`

https://github.com/easylist/easylist/blob/9c8fe1a55e8fbba8cf303efb73a33a2d8ba96df1/easylist/easylist_general_block.txt#L7188

**Comment by SMed79** [comment]
https://forums.lanik.us/rules#participation
> Provide an example link.
Failure to provide the necessary information will delay the resolution of your issue.

**Comment by fiddlerwoaroof** [comment]
Executing `fetch('http://example.com/feed')` in the Chrome console produces the following output:

```
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}

GET http://example.com/feed/ net::ERR_BLOCKED_BY_CLIENT roachnotes.com/:1

Uncaught (in promise) TypeError: Failed to fetch

Fetch failed loading: GET "http://example.com/feed/".
```

**Comment by SMed79** [comment]
**EasyList Authors** need a **real** testable **online** example site.

good luck.

**Comment by ryanbr** [comment]
While an overly generic filter, it hasn't caused much reported issues from what I've seen.
