### ISSUE TITLE
thehill.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#5489]
### List the website(s) you're having issues:

`https://thehill.com/`

### What happens?

Most articles on the frontpage timeline are incorrectly blocked by `thehill.com##.top`. It also seems to cause the "More News" section header to overlap with other elements.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/83945200-658af900-a809-11ea-9c0d-43bcdd22ece6.png)

### Your settings

- OS/version: Windows 10 May 2020 Update
- Browser/version: Chrome 83.0.4103.97 x64
- Adblock Extension/version: Nano Adblocker 1.0.0.148 + Nano Defender 15.0.0.199

### Other details:

Without whitelisting: 
![image](https://user-images.githubusercontent.com/22780683/83945212-7b98b980-a809-11ea-8c81-021ad9828033.png)

With `thehill.com##.top`: 
![image](https://user-images.githubusercontent.com/22780683/83945226-966b2e00-a809-11ea-88ad-4d132575501d.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9f81117ca58701d82c2f74c909e8d5ce86ed61d9
