### ISSUE TITLE
techradar.com/amp

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5499]
### List the website(s) you're having issues:
`https://www.techradar.com/amp/news/is-windows-defender-good-enough-for-your-pc`

### What happens?

Empty ads placeholders because of Fanboy’s Enhanced Tracking List's generic hiding rule.
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/83967182-0c8e9400-a8e1-11ea-937e-bc2481afa1d4.png)

</details><br/>
### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List
### Your settings

uBlock Origin

- OS/version: Windows 10 2004
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: 1.27.10

### Other details:

This is the rule causing this `@@||techradar.com^$generichide`

**Comment by krystian3w** [comment]
3-party iframe from github?

**Comment by SeriousHoax** [comment]
> 3-party iframe from github?

Sorry, I'm not sure sure what do you mean!

**Comment by krystian3w** [comment]
>> This is the rule causing this `@@||github.com^$generichide`
>
> origin page `https://www.techradar.com/amp/news/is-windows-defender-good-enough-for-your-pc`

so ads is embeded on github.com with:

* https://www.w3schools.com/tags/tag_iframe.asp,
* https://www.w3schools.com/tags/tag_object.asp or
* https://www.w3schools.com/tags/tag_embed.asp

**Comment by llacb47** [comment]
Why is github rule causing issue?

**Comment by SeriousHoax** [comment]
> > > This is the rule causing this `@@||github.com^$generichide`
> > 
> > 
> > origin page `https://www.techradar.com/amp/news/is-windows-defender-good-enough-for-your-pc`
> 
> so ads is embeded on github.com with:
> 
> * https://www.w3schools.com/tags/tag_iframe.asp,
> * https://www.w3schools.com/tags/tag_object.asp or
> * https://www.w3schools.com/tags/tag_embed.asp

Oops! sorry, that's a typo. The rule is `@@||techradar.com^$generichide`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/issues/5558#issuecomment-646612278
