### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#5501]
### List the website(s) you're having issues:

`https://1jalshamoviez.cc/movie/The-Rhythm-Section-(2020)-720p-BluRay-x264-ESubs-ORG.-[Dual-Audio]-[Hindi-(Original)-or-English]-[900MB]-Full-Hollywood-Movie-Hindi.html`

`https://13x4.com/view/Ts60Dqp7Dg`

### What happens?

Popup ads

### List Subscriptions you're using:

Ublock origin default  lists

### Your settings

- OS/version: win 10
- Browser/version: firefox 77
- Adblock Extension/version: ublock origin 1.27.10

### Other details:

With default ublock origin lists following filters help

`||cadfixbig.site^`
`||burbibape.com^`
`||peedtzaregg.casa^`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/557b49141b1cf5ec32444934f50ab4f56ec39ec0 https://github.com/easylist/easylist/commit/5e70ebd173d6b96446d759e5f8a79b42503f2e73
