### ISSUE TITLE
westwingnow.pl

### ISSUE THREAD

**Issue by hawkeye116477** [easylist/easylist#5502]
### What happens?

Broken site, pictures of products not loading.

### List Subscriptions you're using:

Fanboy's Social

### Your settings

- OS/version: Manjaro 20.0.2 Lysia
- Browser/version:  Vivaldi 3.0.1874.38
- Adblock Extension/version: Nano Adblocker v1.0.0.148

### Other details:

![2020-06-07_16-59](https://user-images.githubusercontent.com/19818572/83972514-d51fe780-a8e0-11ea-88e3-feadfc84000c.png)

Fix => `@@||static.westwingnow.pl/bella/Svgs-Pinterest.bundle.*.js`

**Comment by Khrin** [comment]
I can't find any hits for this element and the pages loads correctly for me, is this site still broken for you?

**Comment by hawkeye116477** [comment]
Yes, there are new products now, but still it's broken, just scroll a little and you will see the problem.

![2020-06-09_11-12](https://user-images.githubusercontent.com/19818572/84129302-18de3280-aa42-11ea-962b-51099ce435de.png)

**Comment by Khrin** [comment]
Found it, thank you.

**Comment by spirillen** [comment]
Let me suggest you amend this rule to

```
! 6/19/2020 https://www.westwingnow.pl
www.westwingnow.pl##.dnpHZh.StyledWrapper___default-et98ta-0
```

I recommend some cleanup but this one kills the, whatever signup/signin(newsletter crap from the frontpage

![image](https://user-images.githubusercontent.com/44526987/85181665-cba26200-b286-11ea-82ba-2d48592e5364.png)

**Comment by hawkeye116477** [comment]
@spirillen It also brokes scroll. Anyway, there is better rule for this on [Polish Annoyance Filters](https://polishannoyancefilters.netlify.app/).

**Comment by spirillen** [comment]
Well it didn't brake anything in my tor-browser :smiley: but as i wrote, might need enhancement :+1: 

Would you might clean it from https://github.com/spirillen/ublockorigin-rules/blob/2c6cf931557391325e8a2e18a03360803258679c/rules/blockrules.txt#L2 and put comment to your own rule, letting users know where to find it... you get the credit the users wins :medal_sports:
