### ISSUE TITLE
Dead domain and obsolete/no-more-needed rules

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#5517]
### Dead domains:
- EasyList
```
animalist.com
commercialplanet.eu
hevans.com
mongoporn.com
player.abacast.net
thegamer.tv
```

- EasyPrivacy
```
s.youtube.com
```

### Probably obsolete (not in use) or no-more-needed (in use but no need) rules: better to double check
```
- EasyList
@@||candystand.com/assets/images/ads/$image
@@||dmm.com^*/display_ad.js$~third-party
@@||drakulastream.tv^*/flash_popunder.js
@@||fux.com/assets/ads-$script
@@||ikea.com^*/img/ad_
@@||ikea.com^*/img/ads/
@@||jquery.com^$script,domain=adultdouga.biz
@@||jwpcdn.com/player/plugins/googima/$script,domain=video.vice.com
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=thefreedictionary.com
@@||phncdn.com/js/ad_form_header/ad_form_header-min.js?$script
@@||townhall.com/resources/dist/js/prebid-pjmedia.js$script,domain=pjmedia.com
@@||vidgyor.com/live/dai/js/videojs.ads.min.js$script,domain=zeebiz.com
@@||clients*.google.com/adsense/*?key=$domain=~calcalist.co.il|~gaytube.com|~mako.co.il|~pornhub.com|~pornhubthbh7ap3u.onion|~redtube.com|~redtube.com.br|~tube8.com|~tube8.es|~tube8.fr|~walla.co.il|~xtu
```
The last one was for a Chrome extension (https://github.com/easylist/easylist/commit/b4997c167a090289d525a4881b9cf1fc6a809ed6#diff-3273f30ed059f45393695f577a121718) but the extension is no more available.

- EasyPrivacy
```
@@||bootcamp.mit.edu/js/angulartics-google-analytics.min.js
@@||centprod.com/nd/assets/js/analytics.js$script,domain=centprod.com
@@||dplay.com^*/google_analytics.js
@@||dpm.demdex.net/id?$xmlhttprequest,domain=foxnews.com
@@||googletagmanager.com/gtm.js$domain=foxnews.com
@@||sanspo.com/parts/chartbeat/$xmlhttprequest
```

**Comment by kulfoon** [comment]
There is already an open thread: https://github.com/easylist/easylist/issues/2374

**Comment by krystian3w** [comment]
But `PyFunceble` can detect redicrect 30X or parking domain (e.g. `aftermarket.pl`)?

```
Result

CONGRATULATION. Everything seems to be fine.

http://candystand.com
301 Moved Permanently
https://www.pch.com/games?source=candystand
200 OK
```

**Comment by Khrin** [comment]
Removed some of them https://github.com/easylist/easylist/commit/edde31694a0718aee094ccfbad1a12827c81d002

**Comment by Yuki2718** [comment]
@kulfoon This issue is not for discussion, just thought it's good to report some but not too many dead rules. There are also many redundant rules I haven't reported but that's no big issue.

@krystian3w Except for those under Dead domains section I just visited the site in question and took various action to see if a rule is in use, and if in use I badfiltered the rule and checked if anything looks broken. In some cases I tracked Github commits to understand why the rule was added.

**Comment by kulfoon** [comment]
https://github.com/easylist/easylist/issues/2925#issuecomment-491584768

And as for:

> This issue is not for discussion

Despite the fact that the previous issue turned into a discussion, the purpose for which it was created, was to remove dead domains.
