### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by Othonknd** [easylist/easylist#5518]
### List the website(s) you're having issues:

https://www.crunchyroll.com/pt-br
### What happens?

The ads in the videos just start to appear
### List Subscriptions you're using:

Nanoadblocker origin default lists
### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: Nano Adblocker 10.0.149

### Other details:

You will need to choose a video to see the ads

**Comment by llacb47** [comment]
Clear your cookies

**Comment by Othonknd** [comment]
Ok. That solved my problemes. Thanks
