### ISSUE TITLE
Easylist Cookie blocks access to 4G router settings

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#5530]
### List the website(s) you're having issues:

`192.168.100.1`

### What happens?

When trying to access 4G router settings, settings cannot be accessed because 4G router shows privacy policy prompt with overlay, that is partly broken due to Easylist Cookie.

4G Router model: ZTE MF286D

### List Subscriptions you're using:

Easylist Cookie

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: Ublock Origin v1.27.10

### Other details:

Problem filter: 

`/privacy_policy.js`

Blocked request in Ubo's logger

![Modeemi](https://user-images.githubusercontent.com/17256841/84387420-a1540300-abfb-11ea-8c24-482724c0273b.PNG)

Broken consent window:

![modeemi 2 Censored](https://user-images.githubusercontent.com/17256841/84387532-d2ccce80-abfb-11ea-90ff-fb11249d8d0b.png)

After whitelist `@@||192.168.100.1/js/privacy_policy.js$script` or disabling adblocker:

![modeemi 3](https://user-images.githubusercontent.com/17256841/84388402-34416d00-abfd-11ea-9c09-229d2c7407ec.PNG)

4G router settings couldn't be accessed before accepting that prompt.

I didn't do a pull req because I'm not sure what could be a good, general fix for this (modem configuration ip's could be different).

**Comment by krystian3w** [comment]
IMO this can use all range for private network (LAN).

**Comment by krystian3w** [comment]
Possible this hide with cosmetic filters? And script no block use panel after stronger hide?

**Comment by krystian3w** [comment]
No fixed LAN "A" & "B"

<table class="wikitable">
<tbody><tr>
<th>RFC1918 name</th>
<th>IP address range</th>
<th>Number of addresses
</th>
<th>Largest <a href="/wiki/Classless_Inter-Domain_Routing" title="Classless Inter-Domain Routing">CIDR</a> block (subnet mask)</th>
<th>Host ID size</th>
<th>Mask bits
</th>
<th><i><a href="/wiki/Classful_network" title="Classful network">Classful</a></i> description<sup id="cite_ref-4" class="reference"><a href="#cite_note-4">[Note 1]</a></sup>
</th></tr>
<tr>
<td>24-bit block</td>
<td>10.0.0.0 – 10.255.255.255</td>
<td><span style="white-space:nowrap">16<span style="margin-left:0.25em">777</span><span style="margin-left:0.25em">216</span></span></td>
<td>10.0.0.0/8 (255.0.0.0)</td>
<td>24 bits</td>
<td>8 bits</td>
<td>single class A network
</td></tr>
<tr>
<td>20-bit block</td>
<td>172.16.0.0 – 172.31.255.255</td>
<td><span style="white-space:nowrap">1<span style="margin-left:0.25em">048</span><span style="margin-left:0.25em">576</span></span></td>
<td>172.16.0.0/12 (255.240.0.0)</td>
<td>20 bits</td>
<td>12 bits</td>
<td>16 contiguous class B networks
</td></tr>
<tr>
<td>16-bit block</td>
<td>192.168.0.0 – 192.168.255.255</td>
<td><span style="white-space:nowrap">65<span style="margin-left:0.25em">536</span></span></td>
<td>192.168.0.0/16 (255.255.0.0)</td>
<td>16 bits</td>
<td>16 bits</td>
<td>256 contiguous class C networks
</td></tr></tbody></table>

**Comment by peace2000** [comment]
@krystian3w cosmetic filters didn't work as I could not click anything after removing that overlay.

**Comment by peace2000** [comment]
@ryanbr those other ranges would be good to integrate as well?
