### ISSUE TITLE
topplant.pl

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#5540]
URL:

`http://topplant.pl/`

## what happend:

Empty pop-up with **locked scroll** after use Fanboy Social Blocking List

### Please test without list "EasyList Cookie" becasue have a generic network filters:

> https://github.com/easylist/easylist/blob/f42fa496daf70a505c26230a882a4bd131219faf/easylist_cookie/easylist_cookie_general_block.txt#L824-L825

## screen:

![obraz](https://user-images.githubusercontent.com/35370833/84534816-e9058800-acea-11ea-9a31-8e93fed90c12.png) |
--- |

## what we can to do...:

If we must unlock scroll that needed is duplicate that lines https://github.com/easylist/easylist/blob/f42fa496daf70a505c26230a882a4bd131219faf/easylist_cookie/easylist_cookie_general_block.txt#L824-L825 in  Fanboy Social Blocking List project.

**Comment by DandelionSprout** [comment]
Why not simply remove the overlay completely with `##.popmake-overlay` instead?

**Comment by krystian3w** [comment]
Locked scroll, simple `##.popmake-overlay` no recover scroll:

**Comment by krystian3w** [comment]
We with this recover scrolling:

```adb
topplant.pl##.pum-open:style(overflow: auto !important;)
topplant.pl##html.pum-open body > [aria-hidden]:style(padding-right: 0 !important;)
```

---

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/pull/7468
