### ISSUE TITLE
youtube ads

### ISSUE THREAD

**Issue by M1cha** [easylist/easylist#5542]
Can you explain the rationale behind this commit?
https://github.com/easylist/easylist/commit/aaea4da003163f7d02303b299a51d937ef9eb643

Due to this there's now an ad before every single video. Is there a way to disable that?

**Comment by krystian3w** [comment]
Try something like that:

`##.ytp-ad-module.ytp-ad-module`
`youtube.com##.video-ads.video-ads`

**Comment by M1cha** [comment]
thx, if I do that it shows `An error occurred. Please try again later.` for the duration of the ad and the continues with the video as usual.
That's much better than having to see an ad, but obviously not ideal. Is that the reason why the filter got removed?

**Comment by Alex-302** [comment]
@M1cha That error message is a dummy under video ad layer.

**Comment by gwarser** [comment]
@M1cha some people see video ad, and this filter is hiding "skip" button.

**Comment by M1cha** [comment]
@gwarser thanks for the explanation. That answers my question and I guess there's nothing you can do about that with just filter lists and without userscripts.

**Comment by k79e** [comment]
https://www.reddit.com/r/Adblock/comments/hkagt6/adblock_plus_remove_youtube_new_persist_annoying/

**Comment by krystian3w** [comment]
maybe better:

youtube.com###panels#panels if EasyList used:

`youtube.com#@##panels` instead remove filter or commit with `!`.
