### ISSUE TITLE
Fabulous-Emma.com - Blocked images (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#5544]
### Affected site:
`https://www.fabulous-emma.com/`

### Issue:
Blocked images.

### Example:
`https://www.fabulous-emma.com/photos/displayimage.php?album=3315&pid=179337#top_display_media`

### Screenshot (blocked image marked in red):
![filterissue-fabulousemma](https://user-images.githubusercontent.com/9382674/84589747-0a708c00-ae31-11ea-8d0b-ae5a35a555f2.jpg)

### Problem filter:
* EasyList

### Problem rule:
`_ad01.`

### Possible fix:
`@@||fabulous-emma.com/photos/albums/*ad*$image`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.10.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by spirillen** [comment]
Just as a :thought_balloon: thought!!!!

How often are banners named anything `_ad01.`? isn't that mostly in CSS name name appears?

`if = true` then rewrite the rule to something matching the css or is it something like `_ad01.$css` I'm not a rule-writer but take it as initial thought for suggestion...
