### ISSUE TITLE
tv.rakuten.co.jp

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#5545]
### List the website(s) you're having issues:

`https://tv.rakuten.co.jp/content/339547/?l-id=469_el_54301`

### What happens?

Video doesn't work.

![rakuten](https://user-images.githubusercontent.com/58900598/84598266-822bce80-aea4-11ea-844d-80f82391de93.png)

### List Subscriptions you're using:

uBO default lists + AdGuard Japanese

### Your settings

- OS/version: Windows 10
- Browser/version: Brave 1.9.80 with its blocker turned off
- Adblock Extension/version: uBO 1.27.10 + uBO Extra 2.88

### Other details:

Geo locked, use Japanese VPN. These fix the issue:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=tv.rakuten.co.jp`
`@@||pubads.g.doubleclick.net/gampad/ads*tv.rakuten.co.jp$xhr,domain=imasdk.googleapis.com`

**Comment by Yuki2718** [comment]
The second rule suggested was too permissive, corrected.

**Comment by Khrin** [comment]
Unfortunately I can't open the page, a login is required. Can I ask you the full url of the second element?

**Comment by Yuki2718** [comment]
On my end an account is not mandatory but it's possible they require for outside Japan and possibly VPN IPs, there's a similar case in past in AdGuard. Here:

![rakuten](https://user-images.githubusercontent.com/58900598/88415242-1cbeec00-ce19-11ea-8ac1-65b04864273c.png)

In case the SS is hard to read: `https://pubads.g.doubleclick.net/gampad/ads?sz=640x360&iu=%2F7727%2FRakutenShowtime%2FVideoAll%2FEagles%2FLivePreRoll&gAdManager_req=1&env=vp&output=xml_vmap1&ad_rule=1&cmsid=2525931&vid=5290706354&gdfp_req=1&unviewed_position_start=1&description_url=https%3A%2F%2Ftv.rakuten.co.jp%2F&correlator=835463484707439&vpa=auto&vpmute=0&sdkv=h.3.398.1&osd=2&frm=0&vis=1&sdr=1&hl=en&afvsz=200x200%2C450x50%2C468x60%2C480x70&is_amp=0&u_so=l&sdki=44d&adk=2385488000&sdk_apis=2%2C8&url=https%3A%2F%2Ftv.rakuten.co.jp%2Fcontent%2F339547%2F%3Fl-id%3D469_el_54301&dt=1595609189713&cookie_enabled=1&scor=2025918093712975&ged=ve4_td10_er169.73.439.553_vi0.0.601.1123_vp100_eb24168`

**Comment by Yuki2718** [comment]
@Khrin `@@||g.doubleclick.net/gampad/ads$xmlhttprequest,domain=imasdk.googleapis.com` is what I initially did and [turned out to be a mistake](https://github.com/easylist/easylist/issues/5545#issuecomment-650672455), it allowed video ads in other sites - I thought it was US version of Cnet or Zdnet but not sure. So more specification is necessary.

**Comment by llacb47** [comment]
change it to:

```
@@||pubads.g.doubleclick.net/gampad/ads?*RakutenShowtime$xmlhttprequest,domain=imasdk.googleapis.com 
```
