### ISSUE TITLE
kakaku.com

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#5546]
### List the website(s) you're having issues:

`https://kakaku.com/item/K0001219355/`

### What happens?

When you click on links to a shop, popup will be blocked. I see its working as expected, however, `kakaku.com` is a very popular site in Japan comparing prices of various products and those users are seeking the best price. Then once they find the best shop they need to intentionally click links to go to the shop, though being tracked by advertisers will not be their intention. At least on uBO they still get strict blocking so can choose to continue or not. I think the trouble not being able to go to the shop outweighs the tracking matter.

![kakaku](https://user-images.githubusercontent.com/58900598/84598633-2d3d8780-aea7-11ea-9a89-21583e214487.png)

### List Subscriptions you're using:

uBO default lists + AdGuard Japanese

### Your settings

- OS/version: Windows 10
- Browser/version: Brave 1.9.80 with its blocker turned off
- Adblock Extension/version: uBO 1.27.10 + uBO Extra 2.88

### Other details:

`@@||ad.doubleclick.net/ddm/trackclk/$popup,domain=kakaku.com`

BTW though the site is a Japanese site, I found the ad below only when accessed from US. I don't think this should be addressed in Japanese filter.

![kakaku1](https://user-images.githubusercontent.com/58900598/84598622-19922100-aea7-11ea-85db-ddb6b94f4169.png)

**Comment by DandelionSprout** [comment]
I can confirm the problem to an extent, although in my case it claims the item is unavailable for international shipping.

If this is indeed supposed to be treated as an ad, and not as a global shipping advisor (which is what I actually suspect it is), `kakaku.com###global_bnr_wrap` would've removed the banner.

**Comment by Yuki2718** [comment]
> If this is indeed supposed to be treated as an ad, and not as a global shipping advisor (which is what I actually suspect it is), .

Probably you're right and no need to remove that, I guess.
