### ISSUE TITLE
PayPal.com - Unable to change account settings (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#5548]
### Affected site:
`https://www.paypal.com/`

### Issue:
Unable to change account settings.

### How to reproduce:
1 - Log in to your PayPal account @ `paypal.com`.
2 - Click on 'Settings' (cogwheel in the page header / nav bar). 
3 - Click on the 'Security' tab.
4 - Try changing your 'Cookie preferences'..
* **Expected result**: You should be able to change your preferences.
* **Actual result**: "PayPal: Internal error"!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* EasyPrivacy

### Problem rule:
`/gtag.js`

### Blocked script:
`https://www.paypalobjects.com/pa/mi/3p/gtag/gtag.js
`
### Possible fix:
`@@||paypalobjects.com/*/gtag/gtag.js$domain=paypal.com`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.10.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by DandelionSprout** [comment]
Looking into the issue myself, I was unable to reproduce it on Chrome, at the very least.

**Comment by THEtomaso** [comment]
I can confirm that this issue appears to have been fixed server-side now.
_Closing the report_

**Comment by THEtomaso** [comment]
On a side note; changing those settings doesn't really work anyway.
If you empty your cache and log in again, you'll notice that the default settings have been restored.
For the settings to be stored, you'll probably have to keep one of their cookies permanently, which is ironic!
