### ISSUE TITLE
online-convert.com

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/easylist#5549]
### List the website(s) you're having issues:

`https://www.online-convert.com/`

### What happens?

![2020-06-15_192916](https://user-images.githubusercontent.com/57287308/84682571-8278a800-af3e-11ea-9176-d0a59633b50c.png)

### List Subscriptions you're using:

![2020-06-15_192956](https://user-images.githubusercontent.com/57287308/84682646-9a502c00-af3e-11ea-8176-60455555ccc8.png)

### Your settings

- OS/version:  Win 10 x64
- Browser/version:  Opera|Stable
- Adblock Extension/version:  uBO 1.27.10

**Comment by peace2000** [comment]
What is the issue you are having? The cookie banner?

**Comment by P0Rtvine** [comment]
@peace2000 
Yes. 
I use EasyList Cookie and it does not block this banner.

**Comment by peace2000** [comment]
Made a pull request. Let's wait until it's accepted.
