### ISSUE TITLE
physicsworld.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5552]
### List the website(s) you're having issues:
`https://physicsworld.com/a/hubbles-best-shots-eta-carinae/`

### What happens?

Ads + Annoyances + Empty ads placeholders
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/80155663-fdc77880-85e3-11ea-8691-2d2e023e91a4.png)

</details><br/>
### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List
### Your settings

- OS/version: Windows 10 2004
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin 1.27.10

**Comment by Khrin** [comment]
I haven't seen that much stuff left unblocked.
