### ISSUE TITLE
faulty blocking of disqus comments on wccftech.com

### ISSUE THREAD

**Issue by beholder4096** [easylist/easylist#5553]
### List the website(s) you're having issues:

`https://wccftech.com`
`https://wccftech.com/amd-allegedly-delaying-ryzen-4000-series-zen-3-cpus-to-2021/`

### What happens?

disqus on the above site has text of individual user entries hidden

### List Subscriptions you're using:

https://downloads.vivaldi.com/easylist/easylist-current.txt

### Your settings

- OS/version: Win7
- Browser/version: Vivaldi 3.1.1929.34 (Stable channel) (32-bit)
- Adblock Extension/version: Vivaldi native blocking using Easylist filters

### Other details:
I was able to fix the issue using direct blocking of that filter in a my own user filters file, like this:
wccftech.com#@#header + div[class] > div[class]
.. so obviously the disqus issue on the wccftech website is caused by your filter rule in easylist.

**Comment by Khrin** [comment]
You mean the comments, right? All of them loads fine for me.

**Comment by beholder4096** [comment]
> You mean the comments, right? All of them loads fine for me.

Yes, comments. Names show but comment content does not. Did u try in latest Vivaldi, using EasyList in ad blocking sources?
This is tested, btw, the filter definition DOES cause the issue.

![2020-06-16 17 40 40 wccftech com cf20af3c8cc3](https://user-images.githubusercontent.com/49083543/84795691-1bb7c500-aff8-11ea-85b4-ed95b78c120d.jpg)
