### ISSUE TITLE
sematext.com

### ISSUE THREAD

**Issue by otisg** [easylist/easylist#5557]
### List the website(s) you're having issues:

`https://sematext.com/blog/journald-logging-tutorial/`
### What happens?

Pihole users reporting they cannot open the site.  After digging around I managed to track things to https://github.com/easylist/easylist/search?q=sematext.com&unscoped_q=sematext.com

I'm not sure why we are listed there.  The only thing I can think of is that at some point we served the real user monitoring JS beacon off of apps.sematext.com and somebody added our domain to that list.  We now serve the JS beacon off of cdn.sematext.com.  If we have to be blocked can we at least get sematext.com entry changed to cdn.sematext.com ?

That said, I see some other companies in our space, e.g., Datadog, are not in that trackingservers.txt.  They are whitelisted, as seen here: https://github.com/easylist/easylist/search?q=datadog&unscoped_q=datadog

Could/should sematext.com then be whitelisted, too?

### List Subscriptions you're using:

Pihole (but reported by several users, I'm not using it)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by llacb47** [comment]
Easylist is not a supported format for pihole. So no one is using easylist as a domain source, they are using some sort of converted version.

```
 Exact matches for sematext.com found in:
  - https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/Tracking/trackingblocklist.txt 
  - https://v.firebog.net/hosts/AdguardDNS.txt 
  - https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt 
  - https://raw.githubusercontent.com/pengelana/blocklist/master/domain.txt 
  - https://block.energized.pro/ultimate/formats/hosts 
  - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/all_ads_filters.txt 
  - https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt 
  - https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/hosts.txt 
  - https://any.andryou.com/oisddbl.txt 
```

**Comment by llacb47** [comment]
Also you're not getting whitelisted, datadog is rightfully blocked:

https://github.com/easylist/easylist/search?q=datadoghq&unscoped_q=datadoghq

**Comment by otisg** [comment]
@llacb47 Thanks for the pointer re Pihole.  Re Datadog, the thing is that they don't have their domain - datadoghq.com blocked.  Only logs.datadoghq.com from what I can tell.
And then there is datadoghq-browser-agent.com^$third-party , but it looks like it's also whitelisted: @@\|\|datadoghq-browser-agent.com/datadog-rum-us.js$script,domain=usa.experian.com

I'm new to these files and formats, so I could be misinterpreting what I'm seeing.

> you're not getting totally whitelisted - the filter could be changed though

A change would be great.  I don't think the whole domain needs to be blocked.  Maybe cdn.sematext.com because it serves the real user monitoring beacon, much like that datadoghq-browser-agent.com/datadog-rum-us.js which seems both blocked and whitelisted.

**Comment by llacb47** [comment]
> And then there is datadoghq-browser-agent.com^$third-party , but it looks like it's also whitelisted: @@||datadoghq-browser-agent.com/datadog-rum-us.js$script,domain=usa.experian.com

It's only whitelisted on `usa.experian.com` because the page won't load without it.

**Comment by otisg** [comment]
Thanks for clarifying that!  Should I submit a PR for sematext.com => cdn.sematext.com change then?

**Comment by ryanbr** [comment]
Why not remove this third-party server? Don't you see value @otisg in removing less 3rd-party content, not just this `datadoghq-browser-agent.com`  but all others.

**Comment by otisg** [comment]
@ryanbr is that a question for me or @llacb47?
I personally prefer to remove `sematext.com` and this stop blocking it, if that is what you are asking.  But if there is some reason to block something under `sematext.com` then, IIUC, the entry should be more specific, so it doesn't block the whole `sematext.com` domain.

That `datadoghq-browser-agent.com` is another company's site that I was just using as an example of a more specific domain/correct host/domain being blocked.

**Comment by otisg** [comment]
@llacb47 or @spirillen any chance we could stop blocking the whole `sematext.com` domain?

**Comment by llacb47** [comment]
> @llacb47 or @spirillen any chance we could stop blocking the whole `sematext.com` domain?

I'm not affliated with easylist. Neither is spirillen.

**Comment by spirillen** [comment]
Hi @otisg I'm not sure which project you refer too, is it the <https://www.mypdns.org/T910> or <https://github.com/spirillen/ublockorigin-rules/commit/67233b04afeda27e69a00811873405e675b705b5>

In either cases, it would preferable for all parties, you raises the question in the proper fora, as @llacb47 said, we are not in the judgement board of easylist, we spread our opinions are share our founds

**Comment by ryanbr** [comment]
Pihole treats every $third-party block as a first party which is a limitation of the software, Visiting `https://sematext.com/blog/journald-logging-tutorial/` within the browser works fine here.
