### ISSUE TITLE
pcgamer.com/amp

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5558]
### List the website(s) you're having issues:
`https://www.pcgamer.com/amp/ubisoft-will-rebuild-how-sound-works-in-rainbow-six-siege/`

### What happens?
Empty ads placeholders because of Fanboy’s Enhanced Tracking List's generic hiding rule.
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/84861431-d98f9180-b092-11ea-80d9-679333e49943.png)

</details><br/>

### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List
### Your settings

- OS/version: Windows 10 2004 & Android
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin 1.27.10

**Comment by THEtomaso** [comment]
Possible fix:
`pcgamer.com#?#.i-amphtml-element:-abp-has(.placeholderampad)`

**Comment by SeriousHoax** [comment]
@THEtomaso Btw, there's another issue opened which has the same problem as this one because of generic hiding rule present in Enhanced tracking list. Hope both of this get the fix at the same time: 

https://github.com/easylist/easylist/issues/5499

**Comment by THEtomaso** [comment]
> there's another issue opened which has the same problem

Yeah, same thing.
_Previous post edited_

**Comment by SeriousHoax** [comment]
> > there's another issue opened which has the same problem
> 
> Yeah, same thing.
> _Previous post edited_

It still leaves an empty space at the bottom of the page. 

`https://ibb.co/cxSfh7M`

**Comment by THEtomaso** [comment]
> It still leaves an empty space at the bottom of the page.

I've edited my first post again.
How about now?

**Comment by Khrin** [comment]
For the fanboy's enhanced tracking list, ask here: https://github.com/ryanbr/fanboy-adblock
