### ISSUE TITLE
duckduckgo.com ads passing through 

### ISSUE THREAD

**Issue by LeCommonMan** [easylist/easylist#5572]
### List the website(s) you're having issues:
`https://duckduckgo.com/?q=`
`https://duckduckgo.com/?q=+laptop&atb=v214-4__&ia=shopping`

### What happens?

Ads appearing in ddg search

### List Subscriptions you're using:

Easylist
EasyPrivacy
Fanboy's Annoyance
RUS: Ru Adlist

### Your settings

- OS/version:  Lubuntu 18.04
- Browser/version:   Firefox & Chrome ( both latest versions)
- Adblock Extension/version:  uBlock Origin v1.27.10 

### Other details:

screenshot: https://image.prntscr.com/image/fpHPLaRrRYuPi8GAP9P7yw.jpg

**Comment by monzta** [comment]
Let me know if this helps https://github.com/easylist/easylist/commit/4c057c6

**Comment by spirillen** [comment]
Hmm, I can't reproduce this in my FF 77.0.1 from above string, even if I disable my own rule-set

<details><Summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/44526987/85200731-4193e100-b2fa-11ea-8279-3b71e0475915.png)

![image](https://user-images.githubusercontent.com/44526987/85200789-7ef86e80-b2fa-11ea-9aaf-81d42c0f92de.png)
![image](https://user-images.githubusercontent.com/44526987/85200800-8fa8e480-b2fa-11ea-945f-eb7d8ab6d436.png)

</details>
