### ISSUE TITLE
tomshardware.com/amp

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5573]
### List the website(s) you're having issues:

`https://www.tomshardware.com/amp/news/watch-amd-threadripper-3990x-128-threads-render-video-task-manager`
### What happens?

Empty ad placeholders
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/85223310-079f0980-b3e4-11ea-923e-3247f2d80c65.jpg)

</details><br/>
### List Subscriptions you're using:
Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List

### Your settings

- OS/version: Windows 10, Android
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin 1.27.10

**Comment by SeriousHoax** [comment]
Instead of creating a new issue here's another site with the exact same issue. Because of generichide rule present in EasyList: 

`https://arstechnica.com/information-technology/2020/06/intel-will-soon-bake-anti-malware-defenses-directly-into-its-cpus/?amp=1`
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/85224009-150ac280-b3e9-11ea-9249-1783fd4983a3.png)


</details><br/>

**Comment by SeriousHoax** [comment]
@Yuki2718 Hi Yuki! Can you do something about this? It's been 4 months :/

**Comment by llacb47** [comment]
`tomshardware.com,arstechnica.com##amp-ad`

**Comment by Yuki2718** [comment]
@ryanbr
