### ISSUE TITLE
telegraph.co.uk  amp

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5576]
### List the website(s) you're having issues:

`https://www.telegraph.co.uk/technology/2020/06/14/microsoft-owned-coding-site-github-replace-term-master-push/amp/`
### What happens?

Empty placeholders, one possible leftover annoyance
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/85223878-0f60ad00-b3e8-11ea-9f3d-097cac394b56.png)

</details><br/>
### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List

### Your settings

- OS/version: Windows 10, Android
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin 1.27.10

**Comment by THEtomaso** [comment]
@SeriousHoax:
Regarding all these AMP-issues that you've been reporting..

AMP = Accelerated Mobile Pages

All of those empty placeholders are easely removed, but perhaps you could try enabling **AdGuard Mobile Ads filter**, which is included in uBO?
Then you can report any further AMP-related issues for it here:
https://github.com/AdguardTeam/AdguardFilters/issues/

**Comment by SeriousHoax** [comment]
> @SeriousHoax:
> Regarding all these AMP-issues that you've been reporting..
> 
> AMP = Accelerated Mobile Pages
> 
> All of those empty placeholders are easely removed, but perhaps you could try enabling **AdGuard Mobile Ads filter**, which is included in uBO?
> Then you can report any further AMP-related issues for it here:
> https://github.com/AdguardTeam/AdguardFilters/issues/

Hi, I know about that list and even created issues there a few times in the last couple of months but I want EasyList to have these solutions as well since this is the one I usually use on all my devices. This should benefit everyone using EasyList. Maybe even EasyList can think about creating a separate filter list called "EasyList Mobile" if required. AMP is becoming very popular nowadays you know even for non mobile sites.

**Comment by THEtomaso** [comment]
> AMP is becoming very popular nowadays you know even for non mobile sites.

Personally, I'd never even heard of them before, until you started linking to them.
And to be honest, they look like crap on a desktop setup! :)

**Comment by SeriousHoax** [comment]
> > AMP is becoming very popular nowadays you know even for non mobile sites.
> 
> Personally, I'd never even heard of them before, until you started linking to them.
> And to be honest, they look like crap on a desktop setup! :)

Haha, yeah they do look crap on desktop as they're designed for mobiles. But occasionally there's few that looks good on desktops also.
I'm guessing you don't use google as a search engine, not on mobile at least. Otherwise you would have seen some amp pages now and then by now. It's by google and google search on mobile devices prioritize amp pages over regular webpages in search results. This is why many websites kind of forced to create an amp version of their websites. Amp pages are a lot faster compared to regular but it has few drawbacks specially google and privacy related. So it's controversial. You'll find articles about it online. 
Since Kiwi browser became open source, now you would see many Android browsers coming out with extension support. There's one or two already out and Brave is working on it too. Fanboy works for Brave now, right? So he should know about this better than me. With uBlock Origin becoming popular on Android, amp sites reporting would become more common here. So, it's better for EasyList to become more active fixing these sites.

**Comment by Khrin** [comment]
I can't open the pages at the moment, but I don't think these are some unblocked leftovers.

Anyway, we also always added such elements from mobile pages, including amp pages, directly to EasyList.

**Comment by SeriousHoax** [comment]
> I can't open the page at the moment, but I don't think these are some unblocked leftovers.
> 
> Anyway, we also always added such elements from mobile pages, including amp pages, directly to EasyList.

Hi, check this page instead then. Open in a private/incognito mood if you can't access. There are still empty placeholders on my end. 
`https://www.telegraph.co.uk/news/2020/07/17/coronavirus-forces-british-airways-retireentire-fleet-boeings/amp/`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29574622/87779933-78084180-c84f-11ea-8b54-c5ba356a14d0.png)


</details><br/>
