### ISSUE TITLE
southpark.de

### ISSUE THREAD

**Issue by YugiFanGX** [easylist/easylist#5588]
### List the website(s) you're having issues:
`https://www.southpark.de/alle-episoden/s23e09-basic-cable`

### What happens?
Cookie notification is hidden, but Web player doesn't work anymore.

### List Subscriptions you're using:
Easylist Cookie

### Your settings
Clean installed Firefox with Ublock origin

- OS/version: Linux
- Browser/version: Firefox
- Adblock Extension/version: Ublock Origin

**Comment by ryanbr** [comment]
Force an update of subs? I had no issues with video playback (via de vpn)

**Comment by YugiFanGX** [comment]
subs? I've tried updating Easylist Cookie in uBlock Origin. Video playback is working only, if Easylist Cookie is unchecked.

I use Firefox 68.9.0 ESR and uBlock Origin 1.27.10

**Comment by peace2000** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/1373

**Comment by krystian3w** [comment]
Yes, evidon need accept / load.

I do not see player:

![obraz](https://user-images.githubusercontent.com/35370833/88338155-3ccaae80-cd38-11ea-9a01-00706724c1eb.png)

Bad:

https://github.com/easylist/easylist/blob/47f74c7003a7cdd713a38c582bf94a73dc7f7854/easylist_cookie/easylist_cookie_general_block.txt#L546

Similar was approved:

https://github.com/easylist/easylist/blob/567290cf114d4f3763c346614d0d63ee02cee6af/easylist_cookie/easylist_cookie_allowlist.txt#L20
