### ISSUE TITLE
openx.solar

### ISSUE THREAD

**Issue by Varunram** [easylist/easylist#5589]
### List the website(s) you're having issues:
`www.openx.solar`
### What happens?
openx.solar is blocked by EasyList because its domain matches with openx.com
### List Subscriptions you're using:
ABP filters
EasyList
### Your settings
- OS/version: macOS 10.15.2
- Browser/version: Chrome 83.0.4103.106
- Adblock Extension/version: 3.8.4

### Other details:
Matching rule: `.openx.$domain=~openx.com`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6bd170eb1ac79047294635248c84dc1e55538a61

**Comment by Varunram** [comment]
Thank you!
