### ISSUE TITLE
neowin.net

### ISSUE THREAD

**Issue by jenabaivab** [easylist/easylist#5594]
### List Subscriptions you're using:
Adguard Base
EasylistPrivacy
Adblock Warning Removal
Fanboy's Annoyances

Adguard

### Your settings

- OS/version: Windows 10
- Browser/version:  Edge Chromium Dev v85
- Adblock Extension/version: Adguard 7.4.2

### Other details:

![image](https://user-images.githubusercontent.com/60446763/85660370-2e568c00-b6d3-11ea-88bf-84399fbd199c.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/504664ec248199fee5cc05c25b10b67870b6f75b
