### ISSUE TITLE
Typo in EasyList

### ISSUE THREAD

**Issue by gorhill** [easylist/easylist#5598]
There is a filter with a typo in EasyList -- double `~~` used in `domain=` option:

    /advertising/*$~xmlhttprequest,domain=~advertising.org.il|~~kloterfarms.com|~temple.edu|~themarker.com

This prevents the filter from working in uBO 1.27.10 (works fine in uBO dev build).

**Comment by krystian3w** [comment]
line 3512

https://github.com/easylist/easylist/blob/6bd170eb1ac79047294635248c84dc1e55538a61/easylist/easylist_general_block.txt#L3512

**Comment by Khrin** [comment]
Thank you.

**Comment by krystian3w** [comment]
`EasyList` watch on used `genericblock` in EasyList Germany? Because I found a few duplicates and once for german site moved to main instead add in regional.
