### ISSUE TITLE
ads and banners showing on mobile site

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#56]
Fanboy,

ads and banners showing on mobile site

`http://bossmp3.in/category/3844/Tere_Bina_(Shorgul)_Arijit_Singh.html`

add this general filter in EasyList
##a[href*=":80/key/"]
##.ad1

The above general filter blocks ads and banners for the above site as well as for below mentioned sites and many more which is not mentioned.

`heromaza.in`
`songmix.in`

Please check and update the filter in EasyList

thanks

**Comment by monzta** [comment]
Duplicate https://github.com/easylist/easylist/issues/45
