### ISSUE TITLE
EasyList breaks thisismoney.co.uk

### ISSUE THREAD

**Issue by sumyungguy** [easylist/easylist#560]
In some older articles, for example:
http://www.thisismoney.co.uk/money/markets/article-2135786/More-criticism-pipeline-Shell-handling-Niger-Delta-spillages.html
The main content is blocked by `##.article-advert`, which is a div that contains both the article and some adverts. The adverts are already blocked by other rules.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/72f19249f910ebfdb6dafe9eb5fc80e2a9d862a9
Thank you, fixed.

**Comment by krystian3w** [comment]
Bad filter - hide all headings:

https://github.com/easylist/easylist/blob/7351765335a1c4246c482b0bf350bb8b7faefa8c/easylist/easylist_specific_hide.txt#L2986

https://github.com/AdguardTeam/AdguardFilters/issues/66811
