### ISSUE TITLE
ewatchseries.to pops and ads

### ISSUE THREAD

**Issue by adReporter1** [easylist/easylist#561]
pops coming from:  `http://www.shglegle.com/ads?key=9bb8eeabc1baacaaf7a4079133fa2fe4&ch=&width=0&height=0&cp.refcode=5105922`

and ads on series pages:
here `http://ewatchseries.to/episode/difficult_people_s3_e7.html`

**Comment by SMed79** [comment]
see https://forums.lanik.us/viewtopic.php?p=123625#p123625

**Comment by adReporter1** [comment]
new domain @SMed79 @ryanbr 
`http://xwatchseries.to`
