### ISSUE TITLE
youav.com NSFW

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#5613]
### List the website(s) you're having issues:

`https://www.youav.com/video/15601/myba-003-%E4%BA%BA%E5%A6%BB%E3%81%AE%E8%8A%B1%E3%81%B3%E3%82%89%E3%82%81%E3%81%8F%E3%82%8A-%E6%A1%91%E7%94%B0%E3%81%BF%E3%81%AE%E3%82%8A`

(just an example, any video on youav.com have the issue)

### What happens?

An EasyList rule `$script,third-party,domain=youav.com` causes significant delay for video to start, if it ever starts - often it's never. This is only on Firefox.

### List Subscriptions you're using:

uBlock Origin default lists

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBO 1.27.10

### Other details:

The rule is causing endless blockage of "undefined".

![youav](https://user-images.githubusercontent.com/58900598/85908804-ad71ce80-b851-11ea-83fd-da28e496854f.png)

Though uBlock has redirect rule for it, it appears that's irrelevant.

**Comment by ryanbr** [comment]
The site should fix it, Not much we can do.

**Comment by llacb47** [comment]
This is actually popads, can you report to uassets @Yuki2718 ?

**Comment by Yuki2718** [comment]
@llacb47 Sure.
