### ISSUE TITLE
phys.org

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5615]
### List the website(s) you're having issues:

`https://phys.org/news/2019-07-einstein-relativity-theory.html`
### What happens?
Empty ad placeholder
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/85943694-75eb4b00-b953-11ea-9aa9-c46108791a89.png)

</details><br/>

### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin 1.27.10

**Comment by DandelionSprout** [comment]
I recommend that the EasyList team adds `phys.org##.ads-336x280` to get rid of two placeholders.

Additionally I seem to be getting an adblock warning of some sort on that page (Screenshot below). I'd recommend adding `phys.org##.show.bg-danger.alert` to *Adblock Warning Removal List* and/or uAssets.
