### ISSUE TITLE
amp.theguardian.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5616]
### List the website(s) you're having issues:

`https://amp.theguardian.com/science/2020/jun/25/black-holes-may-merge-with-light-of-a-trillion-suns-scientists-say`
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/85943982-7ab0fe80-b955-11ea-9ad1-80419f98e58d.png)

</details><br/>
### What happens?

Empty ad placeholders (and some optional leftover annoyance)
### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List

### Your settings

- OS/version: Windows 10, Android
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin 1.27.10

**Comment by DandelionSprout** [comment]
Appears to me to have been fixed in *AdGuard Mobile Ads* through `amp.theguardian.com##amp-list` and `amp.theguardian.com###ad-undefined`.

**Comment by ryanbr** [comment]
@SeriousHoax can you force an update, is it fixed?

**Comment by SeriousHoax** [comment]
> @SeriousHoax can you force an update, is it fixed?

Hi, one part of the placeholder has been fixed when @Khrin made a commit but there's another one at the bottom area of the page. Another commit needs to be done. 
I posted a comment regarding that here in the pull request. 

https://github.com/easylist/easylist/pull/5708

**Comment by Yuki2718** [comment]
> 
> Also there's one social media annoyance on the page but that's not part of EasyList though rather for your Fanboy's annoyance list.

You mean `a[href^="mailto:"]`? I don't see other social elements if Fanboy Social is enabled. Blocking their parents reliably would require `:upward` or `:has` which I believe is beyond the scope of Fanboy Social.

**Comment by SeriousHoax** [comment]
> > Also there's one social media annoyance on the page but that's not part of EasyList though rather for your Fanboy's annoyance list.
> 
> You mean `##a[href^="mailto:"]`? I don't see other social elements if Fanboy Social is enabled. Blocking their parents reliably would require `:upward` or `:has` which I believe is beyond the scope of Fanboy Social.

Yes that one but didn't know about the later part. So, there isn't going to be any solution for this I guess.

**Comment by Yuki2718** [comment]
Sorry for confusing words, I meant if you want cleaner looking without using the random-looking class names. I guess `##a[href^="mailto:"]` of kind will be enough, or if there's an evidence that these classes are always the same they can be addressed within standard syntax. On my end they're
```
##.css-1dh1kqk
##.css-1hx2chv
```
but a question is if they never changes.

**Comment by SeriousHoax** [comment]
> Sorry for confusing words, I meant if you want cleaner looking without using the random-looking class names. I guess `##a[href^="mailto:"]` of kind will be enough, or if there's an evidence that these classes are always the same they can be addressed within standard syntax. On my end they're
> ```
> ##.css-1dh1kqk
> ##.css-1hx2chv
> ```
> but a question is if they never changes.

Ow I see. Maybe I should create an issue there and see what fanboy thinks.

**Comment by Khrin** [comment]
For what I can see, `amp.theguardian.com##amp-list` would hide too much, including the "_Related Stories_" box.
