### ISSUE TITLE
About a script named "Bilibili-Evolved"

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylist#5618]
### List the website(s) you're having issues:
www.bilibili.com (about a script named "Bilibili-Evolved")

### What happens?

[Translate]

This question is about a script named "Bilibili-Evolved", whose homepage is at https://github.com/the1812/Bilibili-Evolved . The script has a function called "display placeholder text", which is used to "display the "blocked ads" instead of blank areas after deleting the ads of the homepage promotion module." The script will create the following code:

`<div class="blocked-ads new">🚫blocked ads</div>`

However, this class will be blocked by this filter rule:

##.blocked-ads

Therefore, the placeholder text cannot be displayed normally.

Please handle it, thanks.

[original]

该问题是关于一个名为“Bilibili-Evolved”的脚本，其主页是在https://github.com/the1812/Bilibili-Evolved 上。该脚本有一个名为“显示占位文本”的功能，其作用是“删除首页推广模块的广告后显示‘已屏蔽广告’来替代空白区域”。该脚本会创建如下的代码：

`<div class="blocked-ads new">🚫已屏蔽广告</div>`

但是，这个类会被这个过滤规则屏蔽：

##.blocked-ads

从而无法正常显示该占位文本。

请处理一下，谢谢。

### List Subscriptions you're using:

Only EasyList

### Your settings

- OS/version: Windows 10 2004
- Browser/version: Microsoft Edge 83.0.478.56
- Adblock Extension/version: uBlock Origin v1.27.10

### Other details:
![8c751a43ca15cc2069971d6a4d0eff48](https://user-images.githubusercontent.com/66902050/85949296-84078e80-b988-11ea-9eaf-b90e3a750534.jpg)

**Comment by DandelionSprout** [comment]
It is (to the best of my knowledge) *very* unusual for EasyList to fix problems caused by Tampermonkey userscripts, so sadly I think the maintainer of Bilibili-Evolved would've had to change the class name (s)he's using instead.

**Comment by ryanbr** [comment]
Does the bug occur without tampermonkey? I saw no hits on `bilibili.com#@#.blocked-ads`

**Comment by shenzhiming88** [comment]
> Does the bug occur without tampermonkey? I saw no hits on `bilibili.com#@#.blocked-ads`

Hello, it doesn't occur without tampermonkey

**Comment by ryanbr** [comment]
Can't fix a non-ad block extension. should take it up with the author. (reference this ticket)
