### ISSUE TITLE
Invalid Rules by uBo logger

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#5621]
Hey guys, as I was updating my rules I found a lot of `Invalid network filter in easylist`

The full list is below

<details></summary>The list, check it twice :santa: </summary>

+11
0d016f39-4c89-44b2-9997-95e4a93aaa7d.moz-extension-scheme
0,3
xhr
https://fanboy.co.nz/fanboy-antifacebook.txt?_=8

+8
0d016f39-4c89-44b2-9997-95e4a93aaa7d.moz-extension-scheme
0,3
xhr
https://www.fanboy.co.nz/enhancedstats.txt?_=8

+8
Invalid network filter in easyprivacy: ||d1z2jf7jlzjs58.cloudfront.net^$rewrite=abp-resource:blank-js,domain=voici.fr

+8
0d016f39-4c89-44b2-9997-95e4a93aaa7d.moz-extension-scheme
0,3
xhr
https://easylist.to/easylist/easyprivacy.txt?_=8

+7
Invalid network filter in adguard-spyware: @@||auto.cz/*/foto$jsinject

+7
Invalid network filter in adguard-spyware: @@||google.*/edu/cs/$genericblock

+7
Invalid redirect rule in adguard-spyware: .demdex.net/id^$empty,important

+7
0d016f39-4c89-44b2-9997-95e4a93aaa7d.moz-extension-scheme
0,3
xhr
https://filters.adtidy.org/extension/ublock/filters/3.txt?_=8

+6
Invalid network filter in easylist: @@||lemon-ads.com^$~document,~third-party

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(float: right; margin-top: 30px; width: 50%;)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(float: right; margin-top: 30px; width: 50%;)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(float: right; margin-top: 30px; width: 50%;)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(height: 300px; width: 315px;)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(height: 300px; width: 315px;)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(image/)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(data:)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(*data:image*)

+6
Invalid cosmetic filter in easylist: ##.b_algo:-abp-has(p:-abp-properties(content: "Ad"))

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(text-align: center;) > img

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(position: relative; width: 728px)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(cursor: pointer; margin-left: *px;)

+6
Invalid cosmetic filter in easylist: ##.page-content-rightcol :-abp-properties(height: 600px;*width: 300px;)

+6
Invalid cosmetic filter in easylist: ###subheader + :-abp-properties(text-align: center;)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(height: 250px;*width: 300px;)

+6
Invalid cosmetic filter in easylist: ##.widget + :-abp-properties(height: 265px; width: 300px;)

+6
Invalid cosmetic filter in easylist: ##article[data-sponsored]:-abp-properties(content: attr(data-sponsored);)

+6
Invalid cosmetic filter in easylist: ###aside > :-abp-properties(cursor: pointer;)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid cosmetic filter in easylist: ##:-abp-properties(base64)

+6
Invalid network filter in easylist: ||slacker.com^*/getspot/?spotid=$media,rewrite=abp-resource:blank-mp3,domain=slacker.com

+6
Invalid network filter in easylist: $webrtc,domain=101greatgoals.com|123movies.net|9anime.to|9anime.vip|ack.net|allkpop.com|allthetests.com|alltube.tv|audioholics.com|azvideo.net|barnstablepatriot.com|blacklistednews.com|boards2go.com|bolde.com|britannica.com|businessnewsdaily.com|buzzfil.net|cantonrep.com|capecodtimes.com|champion.gg|cheeseheadtv.com|clicknupload.link|clicknupload.org|closerweekly.com|collegehumor.com|colourlovers.com|columbiatribune.com|convertcase.net|crackberry.com|csgolounge.com|ddlvalley.me|destructoid.com|diffen.com|dispatch.com|dorkly.com|dota2lounge.com|enterprisenews.com|eztv.io|eztv.tf|eztv.yt|fastplay.to|fayobserver.com|fhm.com|firstforwomen.com|flexonline.com|freewarefiles.com|gastongazette.com|geekzone.co.nz|genfb.com|ghacks.net|go4up.com|goerie.com|gounlimited.to|goupstate.com|grammarist.com|gsmarena.com|hdvid.tv|healthline.com|heraldtribune.com|houmatoday.com|icefilms.info|igg-games.com|intouchweekly.com|investopedia.com|j-14.com|janjua.pw|janjua.tv|jpost.com|kinos.to|kinox.ai|kinox.am|kinox.cloud|kinox.club|kinox.digital|kinox.direct|kinox.express|kinox.fun|kinox.fyi|kinox.gratis|kinox.io|kinox.lol|kinox.mobi|kinox.nu|kinox.party|kinox.pub|kinox.sg|kinox.sh|kinox.si|kinox.space|kinox.sx|kinox.to|kinox.tube|kinox.wtf|kiplinger.com|kshowonline.com|laptopmag.com|lifeandstylemag.com|lolcounter.com|m-magazine.com|mac-torrents.com|madamenoire.com|maketecheasier.com|megaup.net|mensfitness.com|merriam-webster.com|metrowestdailynews.com|muscleandfitness.com|myfeed4u.me|netdna-storage.com|news-journalonline.com|newsarama.com|nintendoeverything.com|nowvideo.club|nwfdailynews.com|nydailynews.com|ouo.io|ouo.press|ourl.io|pelispedia.tv|phonearena.com|pjstar.com|playbill.com|probuilds.net|providencejournal.com|radaronline.com|recordonline.com|salefiles.com|sj-r.com|skidrowreloaded.com|soapoperadigest.com|solomid.net|sourceforge.net|space.com|spanishdict.com|streamfilmzzz.com|streamzzz.online|tazmovies.com|telegram.com|teslacentral.com|the4thofficial.net|theberry.com|thechive.com|thepoliticalinsider.com|thevideobee.to|tmn.today|topix.com|uploading.site|uptobox.com|uticaod.com|vidtodo.com|vidzi.online|vidzi.tv|vrheads.com|vvdailypress.com|womansworld.com|yts.gs|zimabdko.com

+6
Invalid network filter in easylist: $webrtc,domain=m4ufree.com|m4ufree.tv

+6
Invalid network filter in easylist: $webrtc,domain=uptobox.com

+6
Invalid network filter in easylist: $webrtc,domain=blacklistednews.com

+6
Invalid network filter in easylist: $webrtc,domain=itdmusic.com|itdmusic.in

+6
Invalid network filter in easylist: $webrtc,domain=ibit.to

+6
Invalid network filter in easylist: :35.224.227.218^$webrtc

+5
Invalid network filter in easylist: /adguard.$~document,domain=~adguard-com.cdn.ampproject.org|~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com|~marketplace.visualstudio.com

</details>

**Comment by krystian3w** [comment]
uBO no support `$webrtc` and still no translate `rewrite:`

`##:-abp-properties(` - excluded deliberately in uBO and AdGuard, besides it is visible that it is not often used and probably scripting kill of ads is faster.

**Comment by krystian3w** [comment]
for these bug I do not have any idea:

`Invalid network filter in easylist: /adguard.$~document,domain=~adguard-com.cdn.ampproject.org|~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com|~marketplace.visualstudio.com`

@gwarser 🧀  IMO this "disable" is good and imo no need change `doc` as valid type of option (e.g. `image` / `css` / `xhr`).

**Comment by gwarser** [comment]
@krystian3w https://github.com/gorhill/uBlock/issues/2385, but `$all,~document` should work.

**Comment by krystian3w** [comment]
but EasyList no like `all` - no compatible with ABP / AdBlock - Since the last gorhill has been omitted (as he hasn't missed https://github.com/easylist/easylist/issues/5598), this is a minor mistake.

**Comment by ryanbr** [comment]
No further fixes needed, re-open ticket if there is a filter we need to change.
