### ISSUE TITLE
modd.io

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#5622]
### List the website(s) you're having issues:

`https://www.modd.io/play/two-houses`

### What happens?

different scripts are coming from `enjoy.modd.io`. It looks like ad and tracking because the scripts contains stuff from `cpmstar.com`. Please take a look
<img width="589" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/86003278-d9d44900-ba11-11ea-9b0f-6ea561719c3e.PNG">

### List Subscriptions you're using:

EasyList, EasyPrivacy and EasyList Germany

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 77.0.1
- Adblock Extension/version: uBlock Origin v1.27.10

**Comment by ndmgzpmg** [comment]
It appears that they're ads by giving a quick look at the js codes.
Ex: `https://enjoy.modd.io/gobtlrkyjI9ix7sgkstZieX5/in4y/bv8hsjqsx/ez8y5xX.js?rnd=182388`
Which contains:
`  "requests": {
    "hb": {
      "kind": "hb",
      "pbjsfile": "prebid.js",
      "PREBID_TIMEOUT": 850,
      "adUnits": [`
The others scripts have same mentions to ads and appears to be banners ads, apparently too, the other scripts don't get loaded if the first one is blocked (as fair as I saw the logs correctly)

Guess just a simple block could work:
`||enjoy.modd.io`
Worked out here (uBlock Origin v1.27.10 with Firefox 68.10.0 on Android 9) without any breakages.
