### ISSUE TITLE
Conversion pixel mistakenly blocked

### ISSUE THREAD

**Issue by CPMStar** [easylist/easylist#563]
Hi There,
we are a network for gaming sites that works on non-Adblock traffic.
recently sites discovered that our websites has a large Adblock rates and they have started to give a notice to those users asking them to disable Adblock because the site revenues depends on it.
some of the users do actually disable the Adblock on the website and we do present ads for them, but most of our offers are CPA offers and when those users are clicking the relevant ad and registering for the advertiser's game, the conversion pixel is been blocked.

That means that the site owner is losing money, and we lose too, and we can't report how many conversions happened.

this is how our conversion pixel looks like:
`https://server.cpmstar.com/action.aspx?advertiserid={advid}&gif=1&rbxcb={rand}`

You can see this full process live here:
`https://www.mmobomb.com/review/world-of-warships`

website is asking to disable Adblock -> user disables the Adblock -> user is clicking the ad -> user is filling the registration form -> pixel is been fired and blocked.

we don't care that you are blocking our ads and you can still block us under the privacy lists but please allow us to count conversions on regular users.

Thank you in advance.

**Comment by SMed79** [comment]
Hi,

> EasyList filters must remove adverts, although it is acceptable for them to incidentally remove tracking ==> https://easylist.to/pages/policy.html

**Comment by CPMStar** [comment]
We are not suing anyone, we just want you to fix this so we can avoid this conflict in the future.
you can whitelist only this pixel or you can block only our ad request, we don't see any reason to continue to block this "incidentally" pixel.

**Comment by SMed79** [comment]
Not sure if EasyList will accept to whitelist a tracker if it is blocked by an advert filter.

You have to provide more details (pixel url / blocked by which filter) and wait an EasyList author see this topic and decide what to do.

**Comment by CPMStar** [comment]
This is the problematic rule I think (at least by the chrome Dev tools):
`||cpmstar.com^$third-party`

Something that will block  requests to `cpmstar.com/view.aspx` file only will block the ads but not the conversion.

I've seen other rules doing so, and other companies are indeed working.

**Comment by CPMStar** [comment]
Dear authors, please if someone can take a quick look over this one @ryanbr @monzta @Khrin @nitrox @Hubird-au

**Comment by CPMStar** [comment]
anyone?

**Comment by ryanbr** [comment]
cpmstar has been considered an adserver since 2009 (according to our commit records), why should this change all of sudden? Don't cc: the entire list and users again.

**Comment by CPMStar** [comment]
We've noticed the issue after the publishers have complained about it.
We did tried to avoid asking here and working with our Advertisers on S2S tracking, but it's too much work to go all over them at once.
It's a simple change from your side and it means a lot from ours, why are you ignoring our requests?

**Comment by CPMStar** [comment]
Are there any news about this issue?

**Comment by ryanbr** [comment]
So it blocks people from making money via ads/ad clicks? Isn't that what an Adblock list does? Why should cpmstar be treated any differently.

**Comment by CPMStar** [comment]
you can't hold the stick from both ends, you are asking publishers to pledge users to remove the Adblocker in a nice way instead of using content blockers (that you are blocking afterwards).
so our publishers are doing so, and they are asking the users to support them because there is a cost in managing a website (CDN,Server cost, content cost, development etc).
And 10-15% of the users are white-listing the website in order to help them to earn money from their ads.
I can't see any reason to refuse this request, those users whitelisted the website in order to support it.
I can see that all the other conversion pixels of all the other companies are not been blocked. so you've blocked us by mistake, and you are refusing to help us to fix this issue, and then when the publishers will implement content blocking instead, you'll block it too.

this sounds reasonable for you? why are you doing this?

**Comment by SMed79** [comment]
https://github.com/easylist/easylist/commit/4022994303606dfaa3174b2fea69d010411e95ae
