### ISSUE TITLE
es.bongacams.com

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [easylist/easylist#5641]
### List the website(s) you're having issues:

```https://es.bongacams.com```

### What happens?

A fingerprinter tracker is not blocked by EasyPrivacy ( not this particular domain ). The tracker in question is ```https://i.bcicdn.com/js-min/1JQk0v/chunks/8.0b1e93e4802f9a8144e9.js``` Identified by Privacy Possum. 

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: macOS (up to date)
- Browser/version: Chrome (up to date)
- Adblock Extension/version: It does not make any difference. The problem is with EasyPrivacy list which is used by many adblockers/tracker blockers

### Other details:

This tracker has also been reported on the AdGuard GitHub page here: https://github.com/AdguardTeam/AdguardFilters/issues/58369

**Comment by Khrin** [comment]
For what I can see, if blocked will also break the website (video player won't work...)

**Comment by a-privacy-conscious-user** [comment]
This rule apparently worked for adguard https://github.com/AdguardTeam/AdguardFilters/commit/f888a1127ef496e0353078fcb855cd90fd14010c

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/57719b448b9fb1590d270041c5d3aa0c90646253 That's true, sorry (although their filter is apparently now obsolete) Let's try to be less specific...
