### ISSUE TITLE
es.stripchat.com

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [easylist/easylist#5642]
### List the website(s) you're having issues:

```https://es.stripchat.com```

### What happens?

A fingerprinter tracker is not blocked by EasyPrivacy. The tracker in question is ```https://cdn.stripst.com/assets/vendors.20200630125802.js```

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: macOS (up to date)
- Browser/version: Chrome (up to date)
- Adblock Extension/version: It does not make any difference. The problem is with EasyPrivacy list which is used by many adblockers/tracker blockers

### Other details:

This tracker has also been reported on the AdGuard GitHub page here: https://github.com/AdguardTeam/AdguardFilters/issues/58370

**Comment by Khrin** [comment]
Blocking such element also breaks the website...

**Comment by a-privacy-conscious-user** [comment]
AdGuard decided to fix this by blocking another element. In my tests, it worked

![Screen Shot 2020-07-06 at 20 15 35](https://user-images.githubusercontent.com/67610240/86664953-935c8c80-bfc5-11ea-92c3-7663b7dfcb51.png)

**Comment by llacb47** [comment]
You know you can just link the commit right? 😆

**Comment by a-privacy-conscious-user** [comment]
My bad, sorry https://github.com/AdguardTeam/AdguardFilters/commit/de3915ceb1905fb6abcaa2a6f9275073e631f133

**Comment by Khrin** [comment]
We already have a filter which should take care of it: https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers.txt#L4112

**Comment by ryanbr** [comment]
We block exoclick outright, so changes needed. closing ticket.

**Comment by ATTARAMADAN** [comment]
Jvha,

**Comment by ATTARAMADAN** [comment]
https://es.stripchat.com/https://es.stripchat.com/> 
> 
> 
> 
> 
> 
> ### List the website(s) you're having issues:
> 
> 
> 
> 
> ```https://es.stripchat.com```
> 
> ### What happens?
> 
> 
> 
> A fingerprinter tracker is not blocked by EasyPrivacy. The tracker in question is ```https://cdn.stripst.com/assets/vendors.20200630125802.js```
> 
> ### List Subscriptions you're using:
> 
> 
> 
> EasyPrivacy
> 
> ### Your settings
> 
> 
> 
> - OS/version: macOS (up to date)
> - Browser/version: Chrome (up to date)
> - Adblock Extension/version: It does not make any difference. The problem is with EasyPrivacy list which is used by many adblockers/tracker blockers
> 
> ### Other details:
> 
> 
> 
> This tracker has also been reported on the AdGuard GitHub page here: https://github.com/AdguardTeam/AdguardFilters/issues/58370
