### ISSUE TITLE
Feature request: Consider using DuckDuckGo tracker radar data to add more trackers to EasyList

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [easylist/easylist#5646]
### What happens?

DuckDuckGo has a new web crawler that lets it find new trackers automatically and at scale. There are some that are there but not on EasyList ( I have reported some of them ). So I suggested to both AdGuard and Disconnect to use that data to see if they are missing more trackers on their lists 

https://github.com/AdguardTeam/AdguardFilters/issues/58396 

https://github.com/disconnectme/disconnect-tracking-protection/issues/199 

### Your settings

- OS/version: N/A
- Browser/version: N/A
- Adblock Extension/version: N/A

### Other details:

This data crawler has been chosen by Apple for its latest Safari privacy report so it is quite reliable 

https://twitter.com/DuckDuckGo/status/1275473734397317120

**Comment by a-privacy-conscious-user** [comment]
This screenshots shows some of the fingerprinters that were not blocked by other lists (EasyList and AdGuard did not block some of them) but that appeared on DuckDuckGo tracker radar data sets. Maybe there are more that could be added to more lists

![Captura de Pantalla 2020-07-01 a la(s) 11 09 41](https://user-images.githubusercontent.com/67610240/86254022-a7e6f200-bb8b-11ea-81e6-5c377f849efb.png)

**Comment by ryanbr** [comment]
We actually have more trackers than DDG, but if we're missing any., Submit a report for each site,
