### ISSUE TITLE
adblocker detection

### ISSUE THREAD

**Issue by RicoHeat** [easylist/easylist#5653]
https://unblocktheship.org/

**Comment by krystian3w** [comment]
[https://github.com/easylist/easylist/issues?q=is issue+label <kbd>Anti-Adblock</kbd>+is closed+label <kbd>Invalid</kbd>](https://github.com/easylist/easylist/issues?q=is%3Aissue+label%3AAnti-Adblock+is%3Aclosed+label%3AInvalid)

**Comment by Jose1971AB** [comment]
Hello, @RicoHeat  

For adblocker detection cases, please formulate your problem at **-->** **https://github.com/uBlockOrigin/uAssets/issues**

I hope it serves you well.

Greetings.

**Comment by krystian3w** [comment]
@Jose1971AB fixed in uBO / Nano Adblocker but subscribe `adblock-nocoin-list` block all JS loaded from files and mirror proxy down.
