### ISSUE TITLE
mercadolibre.com.ar: Adblock is blocking products images.

### ISSUE THREAD

**Issue by pazguille** [easylist/easylist#5665]
### List the website(s) you're having issues:
- Mercado Libre: https://listado.mercadolibre.com.ar/herramientas-manuales/120x600_DisplayType_G

### What happens?

Adblock is blocking images that its url contains dimension sizes, but it is the product dimension. 

### List Subscriptions you're using:

- EasyList
- EasyList Spanish
- Acceptable Ads
- AdBlock custom filters
- Anti-Circumvention filters

### Your settings

- OS/version: macOS Version 10.14.6 (Build 18G103)
- Browser/version: Google Chrome | 83.0.4103.97 (Official Build) (64-bit) 
- Adblock Extension/version: AdBlock v4.14.0

### Other details:

Images urls examples :
- https://http2.mlstatic.com/mezclador-en-espiral-crossmaster-para-rotomartillos-sds-plus-pintura-liquidos-yeso-enduido-120x600-mm-D_NQ_NP_817942-MLA31934227597_082019-W.webp
- https://http2.mlstatic.com/prensa-metalica-para-carpinteria-mango-grip-120x600-mm-D_NQ_NP_869689-MLA41608178252_052020-W.webp

**Comment by ndmgzpmg** [comment]
`@@||http2.mlstatic.com^$image,domain=listado.mercadolibre.com.ar`
This worked out here.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7527c7ad04e4a7d62b181f7c3b4bb8d2f5be7085
