### ISSUE TITLE
simpleanalyticsbadge.com

### ISSUE THREAD

**Issue by ndmgzpmg** [easylist/easylist#5666]
### List the website(s) you're having issues:

`manga-raw.club`

### What happens?

A badge (ad) linked to a third party who also is a tracker.

### List Subscriptions you're using:

Ublock Default Filters
Easylist
Easyprivacy
Malware domain list
Malware domains

### Your settings

Ublock origin, default settings

- OS/version: Android 9
- Browser/version: Firefox v68.10.0
- Adblock Extension/version: uBlock Origin v1.27.10

### Other details:
`||simpleanalyticsbadge.com` may block it just fine, without any breakage.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/8aa6dc4579ccd50e71f2dc065845d09fd50d1fd6

**Comment by stephenhawk8054** [comment]
Ads placeholders.

URL:
`https://www.manga-raw.club/manga/nekoppoi-kanojo-tte-kawaii-yo-ne-tte-iitai-dake-no-manga/`
`https://www.manga-raw.club/reader/en/nekoppoi-kanojo-tte-kawaii-yo-ne-tte-iitai-dake-no-chapter-oneshoty-eng-li/`

<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/66517106/147376809-a834c05a-9703-45dd-8922-410bd81821c4.png)

</details>

<details><summary>Screenshot 2</summary>

![2](https://user-images.githubusercontent.com/66517106/147376923-95ead25c-e5fe-4b40-b81d-f041c7d6a03f.png)

</details>

Firefox 95.0.2, ublock 1.40.0 default

Proposed filters:

```
manga-raw.club##.adsbox
manga-raw.club##section > div:has(.adsbygoogle)
manga-raw.club##center > div:has(.adsbygoogle)
manga-raw.club##center > div:has(.OUTBRAIN)
manga-raw.club##.page-in > div
```

**Comment by spirillen** [comment]
Why did you post this report here @stephenhawk8054 ?? I can't see the relation and there are already rules you can add the `manga-raw.club` to

```bash
easylist$ git grep '.adsbygoogle'
easylist/easylist_allowlist.txt:@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=knowfacts.info|real-sports.jp|slideplayer.com|smallseotools.com|soranews24.com|tampermonkey.net|thefreedictionary.com
easylist/easylist_allowlist.txt:@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xmlhttprequest,domain=nullpress.net
easylist/easylist_allowlist.txt:@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=cpu-world.com|megaleech.us
easylist/easylist_allowlist_general_hide.txt:advancedrenamer.com,epicbundle.com,hs-exp.jp,korail.pe.kr,phcorner.net,willyoupressthebutton.com#@#.adsbygoogle
easylist/easylist_allowlist_general_hide.txt:androidrepublic.org,anonymousemail.me,apkmirror.com,demos.krajee.com,kadinlarkulubu.com,pixiz.com,spoilertv.com#@#.adsbygoogle
easylist/easylist_general_hide.txt:##.adsbygoogle
easylist/easylist_general_hide.txt:##.adsbygoogle-box
easylist/easylist_general_hide.txt:##.adsbygoogle-responsive-fix
easylist/easylist_general_hide.txt:##.adsbygoogle-wrapper
easylist/easylist_general_hide.txt:##.adsbygoogle2
easylist/easylist_general_hide.txt:##.google-adsbygoogle
easylist/easylist_general_hide.txt:##.m4-adsbygoogle
easylist/easylist_specific_hide.txt:informer.com##.adsbygoogle
easylist/easylist_specific_hide.txt:geekzone.co.nz##.adsbygoogle
easylist/easylist_specific_hide.txt:gankrin.org#?#.code-block:-abp-has(.adsbygoogle)
easylist/easylist_specific_hide.txt:gankrin.org#?#.widget_custom_html:-abp-has(.adsbygoogle)
easylist/easylist_specific_hide.txt:geekzone.co.nz#?#.container:-abp-has(.adsbygoogle)
```

**Comment by stephenhawk8054** [comment]
> Why did you post this report here @stephenhawk8054 ?? I can't see the relation and there are already rules you can add the `manga-raw.club` to
> 
> ```shell
> easylist$ git grep '.adsbygoogle'
> easylist/easylist_allowlist.txt:@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=knowfacts.info|real-sports.jp|slideplayer.com|smallseotools.com|soranews24.com|tampermonkey.net|thefreedictionary.com
> easylist/easylist_allowlist.txt:@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xmlhttprequest,domain=nullpress.net
> easylist/easylist_allowlist.txt:@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=cpu-world.com|megaleech.us
> easylist/easylist_allowlist_general_hide.txt:advancedrenamer.com,epicbundle.com,hs-exp.jp,korail.pe.kr,phcorner.net,willyoupressthebutton.com#@#.adsbygoogle
> easylist/easylist_allowlist_general_hide.txt:androidrepublic.org,anonymousemail.me,apkmirror.com,demos.krajee.com,kadinlarkulubu.com,pixiz.com,spoilertv.com#@#.adsbygoogle
> easylist/easylist_general_hide.txt:##.adsbygoogle
> easylist/easylist_general_hide.txt:##.adsbygoogle-box
> easylist/easylist_general_hide.txt:##.adsbygoogle-responsive-fix
> easylist/easylist_general_hide.txt:##.adsbygoogle-wrapper
> easylist/easylist_general_hide.txt:##.adsbygoogle2
> easylist/easylist_general_hide.txt:##.google-adsbygoogle
> easylist/easylist_general_hide.txt:##.m4-adsbygoogle
> easylist/easylist_specific_hide.txt:informer.com##.adsbygoogle
> easylist/easylist_specific_hide.txt:geekzone.co.nz##.adsbygoogle
> easylist/easylist_specific_hide.txt:gankrin.org#?#.code-block:-abp-has(.adsbygoogle)
> easylist/easylist_specific_hide.txt:gankrin.org#?#.widget_custom_html:-abp-has(.adsbygoogle)
> easylist/easylist_specific_hide.txt:geekzone.co.nz#?#.container:-abp-has(.adsbygoogle)
> ```

I was not sure if I should create a new issue or continued the old thread with the same site here.

**Comment by spirillen** [comment]
> I was not sure if I should create a new issue or continue the old thread with the same site here.

Answers:

Easylist = new issue(s)
