### ISSUE TITLE
Hiding the .m-warning CSS class causes issues on sites using the m.css framework

### ISSUE THREAD

**Issue by mosra** [easylist/easylist#5667]
### List the website(s) you're having issues:

- https://magnum.graphics/is-magnum-what-i-am-looking-for/ -- there should be five blocks, not four
- https://mcss.mosra.cz/ -- there should be three blocks, not two
- https://aihabitat.org/docs/habitat-sim/index.html -- there should be a warning note
- ...

### What happens?

Anything with a `m-warning` CSS class (which colors elements yellow) disappears. The framework prefixes all CSS classes with `m-` to avoid conflicts, from everything else on the lists this is the only unfortunate clash that's happening.

### List Subscriptions you're using:

Boils down to the "Fanboy's Annoyance list", the [`##.m-warning`](https://github.com/easylist/easylist/blob/0e5710050b8713adfd33f4e3b2e92037c687bb7f/easylist_cookie/easylist_cookie_general_hide.txt#L9718) entry there.

### Your settings

I don't use these filters myself, had this reported by multiple users running uBlock Origin with this list enabled.

### Other details:

I tried to discover the reason behind this particular CSS class being on the list, but the originating commit https://github.com/easylist/easylist/commit/abeaf2668971f33c70387f4da7a1c8cef7110d9e doesn't say anything specific so I hope this particular line could get removed. 

Thank you.

**Comment by Khrin** [comment]
Removed the filter.
