### ISSUE TITLE
web.archive.org

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#5676]
### List the website(s) you're having issues:

`https://web.archive.org/web/20170707174355/https://mac.gov.pl/aktualnosci/koniec-z-drobnym-druczkiem-od-dzis-obowiazuje-nowe-prawo-telekomunikacyjne`

### What happens?

Cookie bar at bottom of screen are visible.

### List Subscriptions you're using:

* EasyList
* EasyList Cookies

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 78.0.1
- Adblock Extension/version: ABP 3.8.5

### Other details:

remove these `generichide`: https://github.com/easylist/easylist/blob/8fca0d8b898d5fa2366ea7a3f1c2c2422445f422/easylist/easylist_allowlist.txt#L327

Or add in the feature many filters like:

`web.archive.org###popup-cookies`

**Comment by THEtomaso** [comment]
The rule is there for a good reason:
https://github.com/easylist/easylist/issues/3545/

**Comment by krystian3w** [comment]
But no fixed at all old issue.

**Comment by Khrin** [comment]
No reason to add the proposed filter.

**Comment by krystian3w** [comment]
> https://github.com/easylist/easylist/blob/8fca0d8b898d5fa2366ea7a3f1c2c2422445f422/easylist/easylist_allowlist.txt#L327

However, someone removed this filter from the file:

https://github.com/easylist/easylist/blob/master/easylist/easylist_allowlist.txt (0 match)

**Comment by THEtomaso** [comment]
It should be added to '**uBlock filters - Unbreak**', to avoid any further fuss.
@Yuki2718: Perhaps you could add it?
