### ISSUE TITLE
electrolux.* + aeg.* + zanussi.*  + other [breakage] [over 100 domains broken by ##.CookieConsent] [all cookie lists]

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#5684]
Orginally reported on PL tracker: https://github.com/MajkiIT/polish-ads-filter/issues/16792, it turned out that all cookie lists are affected by this nasty breakage, so funny, hahaha.

### List the website(s) you're having issues:

`electrolux.*` 59 domains
`aeg.*` 18 domains
`zanussi.*` 12 domains
`faure.com`

### What happens?

Brreakage:
- with EasyList Cookie - no scroll
- with other cookie lists - dark shadow/ overlay / modal backdrop

### List Subscriptions you're using:

- EasyList Cookie
- I don't Care About Cookies
- Adguard Cookies
- Polskie Filtry RODO-Ciasteczkowe

### Your settings

- OS/version: Win 7 64 Pro SP1
- Browser/version: FF 78.0.1
- Adblock Extension/version: uBO 1.27.10

### 1 no scroll with EasyList Cookie:

![capture_007_06-07-2020_22-44-35](https://user-images.githubusercontent.com/63287518/86641100-2c49d280-bfdb-11ea-9345-6047f857cea9.gif)

### 2 dark shadow/ overlay / modal backdrop with:
- I don't Care About Cookies and/or 
- Adguard Cookies and/or 
- Polskie Filtry RODO-Ciasteczkowe:

![capture_008_06-07-2020_22-46-00](https://user-images.githubusercontent.com/63287518/86641118-2fdd5980-bfdb-11ea-9491-9c87a363c81c.gif)

**Comment by gargul2** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/16792

**Comment by THEtomaso** [comment]
This effects more of Elextrolux's domains, than just the Polish one.

### Problem filters:
* **AdGuard Annoyances filter** (`##.CookieConsent`) @BlazDT
* **EasyList Cookie List** / **Fanboy's Annoyance List** (`##.CookieConsent` / `##div[class*="CookieConsent"]`)

### Possible fix (Simply blocking the cookie scripts):
`/*component-CookieConsent.*.js$domain=electrolux.al|electrolux.at|electrolux.be|electrolux.com.ar|electrolux.com.au|electrolux.bg|electrolux.ca|electrolux.cl|electrolux.de|electrolux.ch|electrolux.co.id|electrolux.co.il|electrolux.co.jp|electrolux.co.kr|electrolux.co.nz|electrolux.co.th|electrolux.co.uk|electrolux.co.za|electrolux.com.br|electrolux.com.cn|electrolux.com.co|electrolux.com.ec|electrolux.com.hk|electrolux.com.my|electrolux.com.pe|electrolux.com.ph|electrolux.com.sg|electrolux.com.tr|electrolux.com.tw|electrolux.com.ve|electrolux.cz|electrolux.dk|electrolux.dz|electrolux.ee|electrolux.es|electrolux.fi|electrolux.fr|electrolux.gr|electrolux.hr|electrolux.hu|electrolux.it|electrolux.lt|electrolux.lu|electrolux.lv|electrolux.ma|electrolux.nl|electrolux.no|electrolux.pl|electrolux.pt|electrolux.ro|electrolux.rs|electrolux.ru|electrolux.se|electrolux.si|electrolux.sk|electrolux.ua|electrolux.vn|electroluxarabia.com|electroluxusa.com`

**Comment by kiboke** [comment]
@THEtomaso Thank you very much for this comment. I wonder why I didn't block the script myself... Perhaps blocking it used to break something in the past. Anyway, I'll simplify it further and block `/javascript/component-CookieConsent` pattern globally for now.

**Comment by BlazDT** [comment]
Thank you. Modified rules and added your block rule. If no issue happens with @kiboke's rule, I will likely modify it.

**Comment by THEtomaso** [comment]
> https://github.com/AdguardTeam/AdguardFilters/commit/18d4feef466a977c93cda5013e3b93323e5e95a4

@BlazDT:
With the script blocking rule in place, the exceptions that you added for `##.CookieConsent:not(body):not(html)` aren't needed.

**Comment by kulfoon** [comment]
By the way the Electrolux issue is an example wherein uBO has an advantage over other adblockers https://github.com/uBlockOrigin/uBlock-issues/issues/1008, just `electrolux.*`

**Comment by THEtomaso** [comment]
> `~electrolux.*##` or `domain=electrolux.*`

The latter one doesn't work for uBO Legacy yet though:
https://github.com/gorhill/uBlock-for-firefox-legacy/issues/236/

**Comment by BlazDT** [comment]
> > [AdguardTeam/AdguardFilters@18d4fee](https://github.com/AdguardTeam/AdguardFilters/commit/18d4feef466a977c93cda5013e3b93323e5e95a4)
> 
> @BlazDT:
> With the script blocking rule in place, the exceptions that you added for `##.CookieConsent:not(body):not(html)` aren't needed.

I am aware. But when they add the script location and leave the class name the same, it will not break.

**Comment by THEtomaso** [comment]
Guess we could add `electrolux.com` too, for good measure.
But I haven't found any evidence of it being used for anything besides redirecting.

**Comment by THEtomaso** [comment]
> `electrolux.*` 59 domains
> `aeg.*` 18 domains
> `zanussi.*` 12 domains
> `faure.com`

@BlazDT:
kiboke's generic approach suddenly looks far more attractive now.

**Comment by kulfoon** [comment]
I've found more `aeg.*` and  `zanussi.*` domains: 

aeg.at   aeg.be   aeg.ch   aeg.com.es   aeg.com.pt   aeg.cz   aeg.de   aeg.fi   aeg.fr   aeg.gr   aeg.it   aeg.nl   aeg.pl   aeg.ro   aeg.ru   aeg.se   aeg.uk   aeg.za   h***.de   h***.se   k***.com      p***.de   z***.de   

zanussi.be   zanussi.ch   zanussi.co.uk   zanussi.cz   zanussi.es   zanussi.hu      zanussi.nl   zanussi.pl   zanussi.pt   zanussi.ro   zanussi.ru

@BlazDT did you forgot to add `aeg.*` and `zanussi.*` domains, these are still broken with Adguard Cookies list.

**Comment by kulfoon** [comment]
Found one more broken website: `conclude.com` but this time it's broken by ID filter: `###cookieConsent`, now I wonder how many other websites are broken by the ID filter, I guess the issue is going to escalate like:
- this one https://github.com/ryanbr/fanboy-adblock/issues/976 or
- this one: https://github.com/AdguardTeam/AdguardFilters/issues/55680

**Comment by THEtomaso** [comment]
> Found one more broken website: `conclude.com`

Yeah, that's a different issue.
This seems to fix it:
`||conclude.com/assets/build/combined.*.js`

For all of the other sites which you've mentioned, simply use kiboke's rule (which basically is a generic version of the monster-rule that I posted yesterday):
`/javascript/component-CookieConsent`

**Comment by BlazDT** [comment]
> `||conclude.com/assets/build/combined.*.js`

Added alongside generic rule.

**Comment by kulfoon** [comment]
And why these excludes: https://github.com/AdguardTeam/AdguardFilters/commit/18d4feef466a977c93cda5013e3b93323e5e95a4#diff-50074f528e86c1ba59eccd991f0f54efR933 have been added? 
I'm asking twice already: https://github.com/easylist/easylist/issues/5684#issuecomment-656219165
I'm asking because no excludes have been added in EasyList commit, while such excludes have been added in AdGuard commits.
Hence what is the reason of the difference between EasyList / AdGuard commits?
Anyway logical seems to be either add missing domains `aeg.*` and `zanussi.*` to Adguard commit like I already mentioned in https://github.com/easylist/easylist/issues/5684#issuecomment-656219165 or remove all excludes.

**Comment by THEtomaso** [comment]
> why these excludes

BlazDT explained why he choose to still include the exceptions, in his post here:
https://github.com/easylist/easylist/issues/5684#issuecomment-655748323
There is no reason to expect that filter moderators should share the same reasoning, at all times.

**Comment by kulfoon** [comment]
Indeed, I read his comment before, and then I just forgot about it.

> There is no reason to expect that filter moderators should share the same reasoning, at all times.

But it's a bit silly to see different reasoning in exactly the same technical cases.
- one developers chooses to add excludes (Adguard Cookies), the other not (EasyList Cookie).
- one developers chooses to add `:not(html):not(body)` (I don't Care About Cookies, Polish GDPR-Cookies Filters DEV) , the others not (EasyList Cookie, AdGuard Cookies).

Complete anarchy and chaos, such technical cases (how to fix the issue) are not presidential elections, so it should not be a democracy festival, instead, there should be one best way to fix a technical issue.  Fanboy should prove his performance speculations / claims: https://github.com/ryanbr/fanboy-adblock/issues/711#issuecomment-443634111 with a profiling data as per https://github.com/uBlockOrigin/uBlock-issues#ublock-issues: 

> **Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/devtools/docs/profiles) + fully substantiated analysis supporting the claim.**

Not long time ago I was speculating about similiar performance issue, that adding too many generic filters might decerase performance, see: https://github.com/uBlockOrigin/uBlock-issues/issues/738#issuecomment-619426299, it turned out there is no performance issue, as proven by the BIG GUYS, also it turned out as well I was:

> https://github.com/uBlockOrigin/uBlock-issues/issues/738#issuecomment-619450820 : wanting to argue for the sake of arguing.

Fine, but is now, the same way, Fanboy wanting to argue for the sake of arguing with his performance speculations / claims?

**Comment by jspenguin2017** [comment]
@kulfoon 

Often time, there is not one right way to solve a technical problem, usually there are multiple ways with different tradeoffs. 

Each repository has its own rules, just because `uBlock-issues` asks for profiler tracing does not enable you to impose that rule on repositories that you do not own. 

The `not` operator definitely will make the rule more expensive, but I cannot comment on whether that is a problem as I am not too familiar with the inner workings of the cosmetic filtering engine works. The best way is to as `gorhill`.

**Comment by kulfoon** [comment]
> Often time, there is not one right way to solve a technical problem, usually there are multiple ways with different tradeoffs.

...which unfortunately for your statement, was not true in case of my issue https://github.com/uBlockOrigin/uBlock-issues/issues/738#issuecomment-619426299, because it was very quickly technicaly solved one way: no performance drop.

So why even this generic crap talking...

> Each repository has its own rules, just because `uBlock-issues` asks for profiler tracings does not enable you to impose that rule on repositories that you do not own.

I do not impose anything on anybody, so if you could watch your pesonal allegations and avoid using political tone, it would be good, unless you want to impose your politic on repositories that you do not own... The link I provided was just an example, that technical issues should be solved rather by technical analysis, than by unproven speculations. 

And again, generic politcal crap talking.

Have you come here to defend Fanboy with your generic crap talking or what...

> The best way is to ask `gorhill`.

Yeah, I am aware of it, but I don't talk to this rude monkey anymore, so someone else have to ask him. Bye.

**Comment by jspenguin2017** [comment]
@kulfoon 

I do not have enough knowledge on the matter to give more specific comments, if you are not willing to see generic comments, you should consider not pinging me next time. 

I want to remind you that you should not bring things out of context. Rules of other repositories and comments in unrelated issues likely have nothing to do with this discussion. 

I am not here to defend any technical decisions, but I do want to point out that you should try to avoid insulting others and try to keep the conversation civil.
