### ISSUE TITLE
http://memytutaj.pl/top [false positive]

### ISSUE THREAD

**Issue by adblock-filters** [easylist/easylist#5686]
### List the website(s) you're having issues:
`http://memytutaj.pl/top`

### What happens?
Website blocked with filter `###top-ad`

### List Subscriptions you're using:

- Easylist

### Your settings

- OS/version: Windows 10 64-bit / Ubuntu 18.04
- Browser/version:  Opera 69.0 
- Adblock Extension/version: Adblock Plus 3.9

### Other details:
report from ABP Issue Reporter on EL Polish

to fix:
`memytutaj.pl#@##top-ad`

PR: #5687

**Comment by krystian3w** [comment]
bad filter hide all content.
