### ISSUE TITLE
https://www.polska-ie.com/ [false positive]

### ISSUE THREAD

**Issue by adblock-filters** [easylist/easylist#5688]
### List the website(s) you're having issues:
`https://www.polska-ie.com/`

### What happens?
Website blocked with filter `###adsense`

### List Subscriptions you're using:

- Easylist

### Your settings

- OS/version: Windows 10 64-bit / Ubuntu 18.04
- Browser/version:  Opera 69.0 
- Adblock Extension/version: Adblock Plus 3.9

### Other details:
report from ABP Issue Reporter on EL Polish

to fix:
`polska-ie.com#@##adsense`

PR: #5689

**Comment by krystian3w** [comment]
Website have anti-adblock pop-up - Doesn't that prevent you from continuing to block ads out there or unlock something that could be considered a anti-adblock bait?

**Comment by adblock-filters** [comment]
Can't reproduce this anti-adblock popup. I only have 'normal' pop-up each time I enter the site (Opera/Chrome with or without VPN), don't know why.

![Screenshot from 2020-07-07 18-49-48](https://user-images.githubusercontent.com/52950278/86815735-4939e080-c083-11ea-9cba-1977124980ee.png)

**Comment by krystian3w** [comment]
Oh, I see, you try delete glitch like:

![obraz](https://user-images.githubusercontent.com/35370833/86818814-21e51280-c087-11ea-818d-e06ff8b15d34.png) |
--- |

but this is bug in Anti-adblock pop-up code, because also  should works:

`polska-ie.com#$#abort-on-property-read anOptions`

or

`polska-ie.com#$#abort-current-inline-script anOptions`

❓

**Comment by adblock-filters** [comment]
> Oh, I see, you try delete glitch like

exactly

`polska-ie.com#$#abort-on-property-read anOptions`
seems work

**Comment by krystian3w** [comment]
So no in EasyList, @dimisa-RUAdList possible fix this in `Adblock Warning Removal List` by:

`polska-ie.com#@##adsense`

or 

`@@||polska-ie.com^$generichide`

but I no see file `antiadblockfilters:antiadblockfilters/antiadblock_polish.txt`

**Comment by Khrin** [comment]
I don't see any problem (nor Anti adblock popups) on this domain.

**Comment by krystian3w** [comment]
So should see html source (x2 JS  with `<strong>AdBlock detected!<\/strong>`):

`<div id="PHDhEDnhfyqR" class="SzWIdrmFauhP" style="background:#288730;z-index:9999999; "></div>   <script type="text/javascript">/* <![CDATA[ */var anOptions ={"anOptionChoice":"2","anOptionStats":"1","anOptionAdsSelectors":"","anOptionCookie":"1","anOptionCookieLife":"30","anPageRedirect":"","anPermalink":"undefined","anOptionModalEffect":"fadeAndPop","anOptionModalspeed":"350","anOptionModalclose":true,"anOptionModalOverlay":"rgba( 21,153,32,1 )","anAlternativeActivation":false,"anAlternativeElement":"","anAlternativeText":"<p><strong>AdBlock detected!<\/strong><\/p>\n<p>Please add <a href=\"http:\/\/www.polska-ie.com\">www.polska-ie.com<\/a> to your adblocking whitelist or disable your adblocking software.<\/p>\n","anAlternativeClone":"2","anAlternativeProperties":"","anOptionModalShowAfter":0,"anPageMD5":"","anSiteID":0,"modalHTML":"<div class=\"SzWIdrmFauhP-default\">\n\t<h1 style=\"\">Adblocker detected! Please consider reading this notice.<\/h1>\n\t<p><span style=\"color: #ccffff;\">We've detected that you are using AdBlock Plus or some other adblocking software which is preventing the page from fully loading.<\/span><\/p>\n<p><span style=\"color: #ccffff;\">We don't have any banner, Flash, animation, obnoxious sound, or popup ad. We do not implement these annoying types of ads!<\/span><\/p>\n<p><span style=\"color: #ccffff;\">We need money to operate the site, and almost all of it comes from our online advertising.<\/span><\/p>\n<p><span style=\"color: #ccffff;\"><strong>Please add <a style=\"color: #ccffff;\" title=\"&quot;Polska-IE najbardziej politycznie - spo\u0142eczno - gospodarczy portal informacyjny w Irlandii\" href=\"https:\/\/www.polska-ie.com\" target=\"_blank\" rel=\"noopener\">www.polska-ie.com<\/a> to your ad blocking whitelist or disable your adblocking software.<\/strong><\/span><\/p>\n<\/div>\n<a class=\"close-modal close-SzWIdrmFauhP\">&#215;<\/a>"}/* ]]> */</script><div id="adsense" class="an-sponsored" style="position:absolute; z-index:-1; height:1px; width:1px; visibility: hidden; top: -1px; left: 0;"><img class="an-advert-banner" alt="sponsored" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"></div>`

`<div id="PHDhEDnhfyqR" class="SzWIdrmFauhP" style="background:#288730;z-index:9999999; "></div>   <script type="text/javascript">/* <![CDATA[ */var anOptions ={"anOptionChoice":"2","anOptionStats":"1","anOptionAdsSelectors":"","anOptionCookie":"1","anOptionCookieLife":"30","anPageRedirect":"","anPermalink":"undefined","anOptionModalEffect":"fadeAndPop","anOptionModalspeed":"350","anOptionModalclose":true,"anOptionModalOverlay":"rgba( 21,153,32,1 )","anAlternativeActivation":false,"anAlternativeElement":"","anAlternativeText":"<p><strong>AdBlock detected!<\/strong><\/p>\n<p>Please add <a href=\"http:\/\/www.polska-ie.com\">www.polska-ie.com<\/a> to your adblocking whitelist or disable your adblocking software.<\/p>\n","anAlternativeClone":"2","anAlternativeProperties":"","anOptionModalShowAfter":0,"anPageMD5":"","anSiteID":0,"modalHTML":""}/* ]]> */</script><div id="adsense" class="an-sponsored" style="position:absolute; z-index:-1; height:1px; width:1px; visibility: hidden; top: -1px; left: 0;"><img class="an-advert-banner" alt="sponsored" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"></div>`

**Comment by dimisa-RUAdList** [comment]
I think this problem should be fixed in EasyList Polish.

**Comment by krystian3w** [comment]
EasyList Polish / Global cannot fix anti-adblock pop-up and glitch after bug in anti-adblock code.

**Comment by dimisa-RUAdList** [comment]
Ok: https://hg.adblockplus.org/antiadblockfilters/rev/acae12d18d11

**Comment by dimisa-RUAdList** [comment]
**update**
I created a new filter for the Polish language, but it turned out that I did not have enough rights to register this list in the catalog. Temporarily duplicated the rule in the Russian filter, where it will be located until someone with the necessary rights registers the Polish filter.
