### ISSUE TITLE
marriott.com

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [easylist/easylist#5691]
### List the website(s) you're having issues:

```https://marriott.com```

### What happens?

2 fingerprinters not blocked (see here for more info https://github.com/AdguardTeam/AdguardFilters/issues/58798)

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: macos (up to date)
- Browser/version: chrome (up to date)
- Adblock Extension/version: N/A

**Comment by llacb47** [comment]
To add on, `p11.techlab-cdn.com` should be blocked. Obviously a tracker/fingerprinter. Seen on `https://www.ikea.com/us/en/` as well.

Add `||techlab-cdn.com^$third-party` to EasyPrivacy. 

According to `https://bgp.he.net/dns/p11.techlab-cdn.com#_dns` it is operated by ChameleonX which was acquired by Akamai.

**Comment by llacb47** [comment]
Also unblocked akamai fingerprinting script: `https://www.marriott.com/resources/10f06272ff406f938b23f5e9f0ee55b0f0aafa2feb045`

**Comment by llacb47** [comment]
Blocking `marriott.com/common/js/marriottCommon.js` makes it impossible to choose a hotel room on this page: `https://www.marriott.com/reservation/rateListMenu.mi?transaction=rates&defaultTab=standard`. The buttons just refresh the page. So don't block that

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/5beb19ec16a685447c9ff7a75fca61941b623974
