### ISSUE TITLE
securitytrails.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#5696]
### List the website(s) you're having issues:

```
https://securitytrails.com/domain/openad.visir.is/dns
https://securitytrails.com/domain/adstream.no/dns
https://securitytrails.com/domain/admob.no/dns
```

### What happens?

On occasions, when searching for info on various domains on `SecurityTrails`, the page fails to load with the error *"Something went wrong while connecting to server, please try again later."*, due to various different entries in Easylist beginning with `/`. When it comes to the example pages above, the exact entries are:
```
/openad.$domain=~openad.lv
/adstream.
/admob.$domain=~google.com
```

I propose the following entries to fix them. The whitelistings may seem pretty broad, but I found no other valid working fix:
```
@@||securitytrails.com^
@@||logo.clearbit.com^$domain=securitytrails.com
```

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/86955614-275e5d80-c158-11ea-832a-668f65ab2576.png)

### Your settings

- OS/version: Windows 10 May 2020 Update
- Browser/version: Chrome 83.0.4103.116 x64
- Adblock Extension/version: Nano Adblocker 1.0.0.150 + Nano Defender 15.0.0.201

### Other details:

In the past few months, I've actively used `SecurityTrails` as a research tool for my lists, because it shows the IP addresses of ~75% of the sites, and if so, it also shows a free-of-charge and easy-to-access list of other domains hosted on the same IP address.

Due to the versatility of that site, I feel that it's a good idea to ensure that it works properly.

Without the fix: 
![image](https://user-images.githubusercontent.com/22780683/86955880-963bb680-c158-11ea-92d3-f0de33d68b62.png)

With the fix: 
![image](https://user-images.githubusercontent.com/22780683/86956084-d69b3480-c158-11ea-9fcf-909a472153d3.png)

**Comment by llacb47** [comment]
I'd say this is better: `@@||securitytrails.com/app/api/domain/info/`
