### ISSUE TITLE
Whiteops - Reddit and Others

### ISSUE THREAD

**Issue by ilikenwf** [easylist/easylist#5699]
Seems they use a lot of random domains (CNAME?) - I found out here:

https://smitop.com/post/reddit-whiteops/

I'd paste more here but don't want to rip off the author/researcher.

In a nutshell, I'm thinking something like this:

```
||minkatu.com
||vprza.com
||s.udkcrj.com
||udkcrj.com
```

at the least, but there may be more domains.

**Comment by ilikenwf** [comment]
I'd guess that this is one of their servers..or they're using a CDN. Either way most of these domains look suspect.

https://otx.alienvault.com/indicator/ip/52.27.83.225
https://otx.alienvault.com/indicator/domain/vprza.com
https://otx.alienvault.com/indicator/domain/minkatu.com

**Comment by ilikenwf** [comment]
Data they collect: https://smitop.com/post/whiteops-data/

**Comment by llacb47** [comment]
https://github.com/easylist/easylist/commit/c6a46d680f82b7a9b050766c470803614043f143
https://github.com/easylist/easylist/commit/492f24a937f57b019cdf4f87f22e1e62328adfe6

**Comment by ilikenwf** [comment]
> [c6a46d6](https://github.com/easylist/easylist/commit/c6a46d680f82b7a9b050766c470803614043f143)
> [492f24a](https://github.com/easylist/easylist/commit/492f24a937f57b019cdf4f87f22e1e62328adfe6)

Nice!
