### ISSUE TITLE
thefreedictionary.com (yes, again)

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#57]
`http://www.thefreedictionary.com/iniquity`

Something went wrong!
The page has not loaded completely and some content and functionality are corrupted. Please reload the page or if you are running ad blocking disable it. More info.

Grammarly ads.

**Comment by monzta** [comment]
Seems to look fine now?

**Comment by terrorist96** [comment]
Yes, looks fine now. Though if you wait like 10 seconds after the site finishes loading, the "Something went wrong!" error will still appear, but grammarly is blocked.

**Comment by monzta** [comment]
The broken features they are mentioning [here](http://www.thefreedictionary.com/_/help/ad-block.aspx) seem to work fine for me. I'll leave that message.
