### ISSUE TITLE
indianexpress.com ad placeholders

### ISSUE THREAD

**Issue by BlitW0** [easylist/easylist#5705]
### List the website(s) you're having issues:

`https://indianexpress.com/article/entertainment/web-series/robert-pattinson-the-batman-to-get-a-tv-spinoff-series-6499803/`

### What happens?

Ad placeholders are not removed completely, and there is also an annoying floating read in app button on the right and an e-paper banner too.

### List Subscriptions you're using:

All filters available in uBlock Origin mobile addon on Firefox Android, except Fanboy's Social.

### Your settings

Regular settings on uBlock Origin, with all filters enabled. Only uBlock Origin installed, no other addons.

- OS/version: Android 8.1
- Browser/version: Firefox Beta on Android
- Adblock Extension/version: uBlock Origin 1.27.10

### Other details:

Figured out the below filters on my own:
```
indianexpress.com##.epaper-banner
indianexpress.com##.app-btn
indianexpress.com##.top-ads-mobile
indianexpress.com##.adboxtop
```

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7651

**Comment by ghajini** [comment]
What is wrong with epaper banner, its not ad(just 1st party asking for e-paper subscription)?

@ryanbr 
@mapx- = what do you think about this?

If want to hide epaper banner just do it in annoyance list

**Comment by krystian3w** [comment]
mapx- only recommend report in other repository than `/uAssets`.

**Comment by Khrin** [comment]
@ghajini https://github.com/easylist/easylist/commit/643c22c388be2c8f66c33d964ffa38e493dfdcfc
