### ISSUE TITLE
infoplease.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5706]
### List the website(s) you're having issues:

`https://www.infoplease.com/world/geography/large-islands-world#:~:text=Greenland%20is%20the%20world's%20largest%20island%20covering%202%2C175%2C597%20square%20kilometers.`
### What happens?

Turn off adblocker notice
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/87219772-08daab00-c380-11ea-9952-90d6b39f207c.png)

</details><br/>
### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 78.0.2
- Adblock Extension/version: uBlock Origin 1.28.0

**Comment by krystian3w** [comment]
No worth for EasyList: [https://github.com/easylist/easylist/issues?q=is issue+label <kbd>Anti-Adblock</kbd>+is closed+label <kbd>Invalid</kbd>](https://github.com/easylist/easylist/issues?q=is%3Aissue+label%3AAnti-Adblock+is%3Aclosed+label%3AInvalid)

Anti-Adblock with uBO report here: https://github.com/uBlockOrigin/uAssets/issues/new

**Comment by SeriousHoax** [comment]
Ok thanks. Closing the issue then.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7652

**Comment by SeriousHoax** [comment]
@krystian3w Btw, just noticed this on the same site. Maybe this is something you should check. 
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/87232335-e7a9a700-c3df-11ea-855f-057bfa726b68.png)



</details><br/>

**Comment by krystian3w** [comment]
I have both elements:

`infoplease.com###block-arcamaxemailsubscriptionwidgetschoolopeningpoll`
`infoplease.com###block-ipmiddlewaread`
