### ISSUE TITLE
refoweb.nl [anti-adblock] [EasyList Dutch]

### ISSUE THREAD

**Issue by kulfoon** [easylist/easylist#5707]
Not sure whether anti-adblocks are still handled by regional EasyLists but I see some anti-adblock entries in EasyList Dutch, so in case: `@@||refoweb.nl^$generichide` or `refoweb.nl#@#.adsbox` (but from what I see `generichide` is preferred for anti-adblocks in the list). In case EasyList Dutch doesn't handle anti-adblocks anymore, one can report it to uAssets because I don't contribute to it anymore.

### What happens?

Anti-adblock

### List Subscriptions you're using:

Default + NLD: EasyList Dutch

### Your settings

- OS/version: Win7 Pro SP1 64
- Browser/version: FF 78.0.2
- Adblock Extension/version:  uBO 1.28.0

### Other details:

![capture_005_11-07-2020_15-12-56](https://user-images.githubusercontent.com/43844449/87224902-5d365880-c389-11ea-924f-58c8f340839e.gif)

**Comment by ghooster3** [comment]
```
! Alleen voor advertenties op Nederlandstalige sites!
! Rapporteer gevonden advertenties of fouten hier:
! https://forums.lanik.us/viewforum.php?f=100
! of stuur een email naar fam.lam [at] live.nl
```

https://github.com/easylist/easylist/issues?q=is%3Aissue+is%3Aclosed+label%3AAnti-Adblock
https://github.com/easylist/easylist/issues?q=is%3Aissue+is%3Aclosed+label%3AInvalid

**Comment by kulfoon** [comment]
ghost I'm not blind, moron
- I don't have an account in `https://forums.lanik.us/viewforum.php?f=100` and I'm not interested registering in 20 different websites to report a single fuking issue, moreover I tried to register in the past in the forum and had troubles, it didn't want let me to register, and was throwing weird errors
- I don't contribute to uAssets anymore, due to many trolls, so I'll not report it there
- so I just wanted to report it somewhere for the fuking damn

so let anybody do whatever he wants with this issue: either add `Invalid` label or put this issue in your ass, bye morons.

**Comment by kulfoon** [comment]
By the way another moron DandelionSprout: https://github.com/AdguardTeam/AdguardFilters/issues/59147#issuecomment-657234957 Bye morons.

**Comment by ryanbr** [comment]
We don't support Anti-adblock in Easylist. Which is why it's marked as invalid.

**Comment by kulfoon** [comment]
Then go and the same way mark as invalid these invalid stupid misleading confusing outdated:
- `! anti-adblock` sections in EasyLists 
- and [>> EasyList policy <<](https://easylist.to/pages/policy.html) which still says that it covers AA messages 

There is nothing more annoying than confuse someone with invalid infos in various places, and then blame / mark his issue as invalid and make him look likea fool. Watch where you stick your stupid invalid labels, go and stick them to the invalid confusing infos in the first place.

Another thing is that, despite the above, I was aware that the issue might not be accepted in general, but I still decided to create the issue anyway, with a hope someone will report it to uAssets, because I don't contribute to uAssets anymore.

But instead, I'm being made looking like a fool by stupid comments, labels, and emojis, so for fuking damn, once again, you all, enjoy your moronic comments, labels and emojis. I must think if I still want to contribute to this repository. Bye.

**Comment by kulfoon** [comment]
@jspenguin2017

> https://github.com/easylist/easylist/issues/5684#issuecomment-657251607 : I want to remind you that you should not bring things out of context. Rules of other repositories and comments in unrelated issues likely have nothing to do with this discussion.

I don't need to be reminded, because I'm not stupid like you and I understood it the first time, and I want to remind you that I already replied to it https://github.com/easylist/easylist/issues/5684#issuecomment-657242098, so it seems you  either missed my reply or are too stupid to understand it.

> but I do want to point out that you should try to avoid insulting others and try to keep the conversation civil.

Stop pointing / reminding others, and start to look at yourseff, I behave fine until some moron starts first...want a civil conversation? Then provide a civil conversation yourself at first and don't insult me with your personal allegations and stupid generic crap talking, what you did in your first comment and what you arerepeating in another comment. Now you coming and turning things upside down, the encyclopedia defines it as [Hypocrisy](https://en.wikipedia.org/wiki/Hypocrisy) and a person who indulges in hypocrisy as [Hypocrite](https://en.wikipedia.org/wiki/Hypocrite_(disambiguation)) or as [Internet troll](https://en.wikipedia.org/wiki/Internet_troll). 

And this ugly troll @llacb47 must always stick his stupid thumb up emoji to my "opponent"'s comments, he sticked it already there: https://github.com/easylist/easylist/issues/5707#issuecomment-657303893 and there https://github.com/easylist/easylist/issues/5684#issuecomment-657251607 and in many other place, like an insect, like he confused github with facebook. Now you both GTFO trolls, and go troll elsewhere.
