### ISSUE TITLE
quora.com

### ISSUE THREAD

**Issue by einstein95** [easylist/easylist#5710]
### List the website(s) you're having issues:

```
https://www.quora.com/
```

### What happens?

Posts to `https://www.quora.com/ajax/batched_log_POST` aren't blocked, however posts to `https://log.quora.com/ajax/batched_log_POST` are, via https://github.com/easylist/easylist/blob/e9f02d95cafa3d431a8d8120094b3a1bed39fd7d/easyprivacy/easyprivacy_specific.txt#L1148

### Your settings

- OS/version: Windows 8.1 with Bing
- Browser/version: Firefox 78.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin v1.27.10

**Comment by krystian3w** [comment]
so this need another filter:

`||quora.com/ajax/batched_log_POST`
