### ISSUE TITLE
n1.ru

### ISSUE THREAD

**Issue by vladostman** [easylist/easylist#5716]
### List the website(s) you're having issues:

https://ekaterinburg.n1.ru/

### What happens?

There is a menu at the top of the page, the last element in that menu is an ad. They seem to be custom crafted/native ads.

![image](https://user-images.githubusercontent.com/66869331/87306248-f60fd400-c541-11ea-849d-a7b5c4630825.png)

### List Subscriptions you're using:

AdNauseam default: AdNauseam lists, EasyList, uBlock lists.

### Your settings

- OS/version: Windows 7
- Browser/version: 78
- Adblock Extension/version: AdNauseam 3.9.109

### Other details:

`n1.ru##._banner` should do it for all cities (first part of the domain)

**Comment by DandelionSprout** [comment]
Appears to me to have been fixed in RU AdList through `n1.ru##._banner`.
