### ISSUE TITLE
flipkart.com

### ISSUE THREAD

**Issue by BlitW0** [easylist/easylist#5719]
### List the website(s) you're having issues:

`www.flipkart.com`

### What happens?

Login popup appears immediatly after site is loaded.

### List Subscriptions you're using:

All filters lists in uBlock Origin except Fanboy's Social.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Firefox 78.0.2
- Adblock Extension/version: uBlock Origin 1.28.0

### Other details:

Login popup has randomized class.

**Comment by DandelionSprout** [comment]
I for one sadly can't come up with any entries that wouldn't also have blocked intentional logins resulting from clicking the login button in the top bar.

**Comment by ryanbr** [comment]
I can't replicate this @BlitW0   is it still happening?

**Comment by BlitW0** [comment]
Yeah, happens on chrome on windows and on firefox nightly android too.

**Comment by SeriousHoax** [comment]
This can be regarded as an annoyance perhaps but not an ad so this is something for: https://github.com/ryanbr/fanboy-adblock

**Comment by smed79** [comment]
for [Adblock Plus](https://adblockplus.org/), add de below filter
```
flipkart.com##.mCRfo9
```
in addition you need to install [_ this _](https://greasyfork.org/fr-CA/scripts/377696-enable-vertical-and-horizontal-scrollbar-everywhere) userscript in a userscript manager as [Violentmonkey](https://violentmonkey.github.io/) or [Tampermonkey](https://www.tampermonkey.net/) to enable the vertical page scroll bar.

for ubo, try
```
flipkart.com##.mCRfo9
flipkart.com##body:style(overflow: auto !important;)
```

**Comment by BlitW0** [comment]
Working with the above filters for now. For mobile, I found `flipkart.com##._3d0cnb`. Closing the issue sinced it is solved for now.
