### ISSUE TITLE
dfiles.ru

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/easylist#5723]
`https://dfiles.ru/`

### What happens?

files don't load

`|https://$xmlhttprequest,domain=dfiles.ru ~> EasyList`

**registration required**

![1](https://user-images.githubusercontent.com/57287308/87422457-56a21e00-c5e1-11ea-8f84-1abb21db41ed.gif)

### List Subscriptions you're using:

![2020-07-14_144521](https://user-images.githubusercontent.com/57287308/87422118-bcda7100-c5e0-11ea-9ab3-e2609fe71113.png)

### Your settings

- OS/version:  Win10
- Browser/version:  Opera|Stable
- Adblock Extension/version:  uBO 1.28.2

**Comment by ryanbr** [comment]
Force an update, it should be fixed.
