### ISSUE TITLE
eu.wargaming.net/registration/

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#5724]
### List the website(s) you're having issues:

`https://eu.wargaming.net/registration/en/`

### What happens?

Hidden logo login with "social" platform account:

![obraz](https://user-images.githubusercontent.com/35370833/87435749-7428b500-c5ec-11ea-83fa-450572a9c0d3.png) | ![obraz](https://user-images.githubusercontent.com/35370833/87435794-7f7be080-c5ec-11ea-8ab6-b99e6f456ee4.png)
--- | ---
now | what should be

### List Subscriptions you're using:

Fanboy's Social Blocking List

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 78
- Adblock Extension/version: ABP 3.9 

### Other details:

`@@||eu.wargaming.net/registration/static/*/img/social/icon_$image,domain=eu.wargaming.net`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/082e22f31df3fdb6c50ced9ce3f651a8694343f4
