### ISSUE TITLE
youtube shows ad-videos before the actual videos

### ISSUE THREAD

**Issue by calestyo** [easylist/easylist#5725]
### List the website(s) you're having issues:
`https://www.youtube.com/`

### What happens?
Since a few days, youtube shows ad-videos, AFAICS only before the actual videos, but not during them.
Other websites seem to have their ads blocked just fine.

### List Subscriptions you're using:

easylist
easylist germany

### Your settings

- OS/version: Linux, Debian sid
- Browser/version: Firefox 78.0.2
- Adblock Extension/version: ublock-origin 1.22.2

**Comment by ryanbr** [comment]
Link to video? geo location?

**Comment by an94baller** [comment]
> 
> 
> Link to video? geo location?

example video: https://www.youtube.com/watch?v=sqmQcGwiXWg

ctrl + f5 if not loaded

**Comment by calestyo** [comment]
> Link to video? geo location?

Germany... whether an ad-video is shown or not seems to be at least partially random... so it doesn't always happen for the same video.

For @an94baller ’s first link I don't get an ad-video, for the second one I get one, though the video isn’t actually shown and I just see the Skip-Ads button and some timeout animation.
Actually that behaviour seems to happen now for all cases, where I see such an ad-video.

**Comment by patrickhgb** [comment]
> 
> 
> > Link to video? geo location?
> 
> Germany... whether an ad-video is shown or not seems to be at least partially random... so it doesn't always happen for the same video.
> 
> For @an94baller ’s first link I don't get an ad-video, for the second one I get one, though the video isn’t actually shown and I just see the Skip-Ads button and some timeout animation.
> Actually that behaviour seems to happen now for all cases, where I see such an ad-video.

Every single viewer gets different ad type, it's normal with youtube.

Major entertainment channels will have them most likely, so you can try to view those videos.



Interestingly, after I purge + force update list a few times, I still get the ad spot but can instantly skip them.

There are multiple reports scattered on the easylist forum and ublock subreddit.

**Comment by ryanbr** [comment]
disabling uBO and enabling ABP (as a test), does it fix the ads?

**Comment by patrickhgb** [comment]
> 
> 
> disabling uBO and enabling ABP (as a test), does it fix the ads?

i don't have ABP installed, is it absolutely necessary to test?

**Comment by ryanbr** [comment]
Just trying to rule out changes done in uBO

**Comment by P0Rtvine** [comment]
@patrickhgb
> i don't have ABP installed, is it absolutely necessary to test?

In ABP, you can send a report when you see an ad, which can help more than just a report here.

**Comment by monzta** [comment]
@calestyo 1.22.2 is an outdated version of uBlock Origin. Please update to the latest 1.28.2 and try again.

**Comment by monzta** [comment]
Closing as there was no follow up from the reporter.

**Comment by an94baller** [comment]
> 
> 
> Closing as there was no follow up from the reporter.

it still happens fyi @monzta 

we just don't know how to actually block this since it's a JS element, still learning ways around messing with the element picker
