### ISSUE TITLE
*

### ISSUE THREAD

**Issue by python273** [easylist/easylist#5740]
<img width="362" alt="Screenshot 2020-07-17 at 13 55 06" src="https://user-images.githubusercontent.com/3097956/87779635-c872a580-c835-11ea-9698-4c742e1a220c.png">

- OS/version: macos
- Browser/version: Firefox 78.0.2
- Adblock Extension/version: uBlock Origin 1.28.2

**Comment by clst** [comment]
Same here. Not on all sites but on most. Wikipedia looks very "clean". I haven't found the typo yet by just scrolling through the list.

**Comment by peace2000** [comment]
I noticed the same. Easylist Cookie breaks countless of websites.

![kuva](https://user-images.githubusercontent.com/17256841/87779921-4c2c9200-c836-11ea-8526-87bddb07f5ad.png)

**Comment by clst** [comment]
The Problem is in:

```
! Version: 202007171100
! Title: EasyList Cookie List
! Last modified: 17 Jul 2020 11:00 UTC
```

**Comment by peace2000** [comment]
This is critical, @ryanbr @Khrin @monzta

**Comment by arch-btw** [comment]
The internet looks like it's 2001 again. I've been waiting for this moment.

**Comment by nevivurn** [comment]
https://github.com/easylist/easylist/blob/f73a055634c5a4a7b554e6cc998abf11f427741b/easylist_cookie/easylist_cookie_international_specific_hide.txt#L1253

Maybe this? I'm not too familiar with the filter syntax.

**Comment by peace2000** [comment]
I think it's this commit: https://github.com/easylist/easylist/commit/f73a055634c5a4a7b554e6cc998abf11f427741b#diff-f17bf5813971b33368b2bcf55bc934a5

| is being used as ! in thai list...

**Comment by Khrin** [comment]
Sorry, I apologize for my error, now the typo has been corrected.

**Comment by python273** [comment]
```
[Adblock Plus 2.0]
! Checksum: qMnHWchsxYzZCYJzOqrzGQ
! Version: 202007171111
! Title: EasyList Cookie List
! Last modified: 17 Jul 2020 11:11 UTC
```
the rule is still there? how fast will it be updated?

**Comment by python273** [comment]
```
[Adblock Plus 2.0]
! Checksum: R/Ip4rKCSjtD0Te6omQ27g
! Version: 202007171120
! Title: EasyList Cookie List
! Last modified: 17 Jul 2020 11:20 UTC
! Expires: 1 days (update frequency)
```
ok, fixed

> `! Expires: 1 days (update frequency)`

I hope adblockers refresh the lists more often 😬

**Comment by nevivurn** [comment]
`https://fanboy.co.nz/fanboy-annoyance.txt` as of writing, this URL seems to be serving the version with the issue, and ublock seems to use it.

**Comment by gargul2** [comment]
uBO users can add temporarily `|$badfilter` to "My Filters".

**Comment by gargul2** [comment]
Fanboy Annoyance has been fixed right now:

```
[Adblock Plus 2.0]
! Checksum: HinBH060bS1hm6KTjWYAGQ
! Version: 202007171141
! Title: Fanboy's Annoyance List
! Last modified: 17 Jul 2020 11:41 UTC
```
