### ISSUE TITLE
kissanime.monster

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#5773]
All the details here: https://github.com/uBlockOrigin/uAssets/issues/7611
Confirmed nothing has changed with up-to-date uBO default filters + Fanboy Annoyances.

**Comment by Khrin** [comment]
I've got redirected to a similar domain, unsure of if is geo-locked or what else.

**Comment by Yuki2718** [comment]
You're right, sorry I missed the redirect. However, it seems geo-location really affects, as I don't see any connection to cloudflare and somehow none of your rules matches on my end (maybe because outside the EU?):

![kissanime1](https://user-images.githubusercontent.com/58900598/88195884-7f7a8100-cc7b-11ea-9ae6-2f85c517bb3c.png)

![kissanime3](https://user-images.githubusercontent.com/58900598/88195900-8608f880-cc7b-11ea-807f-4393cc5ceef7.png)

![kissanime4](https://user-images.githubusercontent.com/58900598/88196035-b2247980-cc7b-11ea-8842-61d250167cc6.png)

What @mapx- proposed for .monster still match, but I found `##[href="/user/profile/premium-membership"]` hides bit too many. I propose:
```
||kissanime.digital/addons/*.gif$image,~third-party
kissanime.digital##.aattention
kissanime.digital##.hhotnews
kissanime.digital##.ico.close
kissanime.digital##.ico.close + [href="/user/profile/premium-membership"]
kissanime.digital###tecssEnRaY + div[style="display: block;"]
```
