### ISSUE TITLE
onesignal.com

### ISSUE THREAD

**Issue by gdeglin** [easylist/easylist#5776]
### List the website(s) you're having issues:

https://app.onesignal.com/login (fails to load due to JS and CSS resources being blocked)
https://cdn.onesignal.com/sdks/OneSignalSDK.js

### What happens?

Resources are blocked by adblock (in the case of any JS or CSS resource), or fail to load due to including these resources.

### List Subscriptions you're using:

Default easylist subscription in AdBlock. We believe the block is from easylist/easylist_adservers.txt.

### Your settings

- OS/version: macOS Catalina 10.15.5
- Browser/version: Chrome 84.0.4147.85
- Adblock Extension/version: Version 4.16.0

### Other details:

I work at OneSignal. I believe we have been incorrectly classified as an adserver. We provide a software library and API that helps website developers implement push notifications on their website.

We provide a critical messaging service for major news providers, government agencies, entertainment and media companies. 

We encourage all customers to ask for permission in UX-friendly and user-friendly ways. For example, only in response to a user action. In fact, new versions of Chrome are starting to block websites that ask for permission in ways that are annoying or deceptive. (We blogged about these changes and how to design for a better UX here: https://onesignal.com/blog/chrome-is-banning-abusive-notifications/). We have recently doubled down on education efforts on this front.

We also respect user privacy; No user data is used for advertising or cross-site tracking purposes. We are Privacy Shield certified and GDPR compliant.

Thank you for reviewing this issue.

**Comment by Yuki2718** [comment]
Indeed included in all EasyList, EasyPrivacy & Fanboy Annoyances - the last one is valid as it's for push notification, not sure about the former two.

**Comment by gdeglin** [comment]
Thanks. Yes, it looks like Fanboy Annoyances does block us and other providers for notifications. But based on my understanding and this thread, it's an error that we are included on the other lists: https://forums.lanik.us/viewtopic.php?f=64&t=44340

**Comment by gdeglin** [comment]
@ryanbr can you help? Our website and service are broken for people who have Adblock and we have a lot of users asking us about it.

**Comment by ryanbr** [comment]
We have taken a more proactive approach to notification servers using tracking (user agent checks, referrer checks, fingerprinting etc), onesignal is no different.

**Comment by gdeglin** [comment]
Thank you.

**Comment by UjuiUjuMandan** [comment]
<img width="1080" height="2283" alt="Image" src="https://github.com/user-attachments/assets/ee756ff4-142c-45b1-8928-07944063a466" />

(*Subscribe to our latest technically information - Later / Subscribe*)

I'm a notification hater and I decided to block `onesignal.com` in dnsmasq level anyway.
