### ISSUE TITLE
karriere.de

### ISSUE THREAD

**Issue by spodermenpls** [easylist/easylist#5777]
### List the website(s) you're having issues:

`www.karriere.de`
### What happens?

The site displays a big cookie consent banner at the top, which seems not to be covered by Easylist Cookie yet.
### List Subscriptions you're using:
uBlock filter family
Peter Lowe's list
Adblock Warning Removal List
Adguard Tracking, Annoyances, German + Easylist German, Base + Easylist
Easylist Cookie

### Your settings

- OS/version: Windows 10 Pro
- Browser/version: Firefox 78.0.2 64-bit
- Adblock Extension/version: uBlock Origin 1.28.4

### Other details:

![Screenshot_2020-07-23 Karriere de – Mein Erfolgsportal Wertvolle Tipps für Karriere Job](https://user-images.githubusercontent.com/23747593/88246309-6208df80-cc9a-11ea-961d-fc4dec83e42c.png)

**Comment by krystian3w** [comment]
`##.c-notification`
