### ISSUE TITLE
wtk.pl - video blocked 

### ISSUE THREAD

**Issue by adblock-filters** [easylist/easylist#5778]
### List the website(s) you're having issues:
`https://wtk.pl`
`https://wtk.pl/news/60806-jesli-wykladac-milion-euro-to-tylko-na-sprawdzonego-w-polsce-pilkarza`

### What happens?
Video player doesn't start when opening some videos.

### List Subscriptions you're using:

- Easylist

### Your settings

- OS/version: Windows 10 64-bit / Ubuntu 18.04
- Browser/version:  Opera 69.0 
- Adblock Extension/version: Adblock Plus 3.9

### Other details:
Video is blocked by:
`||imasdk.googleapis.com^$third-party`
`-contrib-ads.`
so to resolve it, I'd suggest something like:
`@@||cloudflare.com/ajax/libs/videojs-contrib-ads/$domain=wtk.pl`
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=wtk.pl`
(ads on this website remain blocked anyway)

**Comment by krystian3w** [comment]
In: `! Title: uBlock filters -- Unbreak`

```
@@||cdnjs.cloudflare.com/ajax/libs/*/videojs-contrib-ads.js$script,domain=wtk.pl
```
