### ISSUE TITLE
oemepc.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#5810]
### List the website(s) you're having issues:

`http://oemepc.com/`

### What happens?

Two fairly large `Yandex`-hosted ads show up.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/88482330-d674a480-cf60-11ea-9a62-ea6935905ae8.png)

### Your settings

- OS/version: Windows 10 May 2020 Update
- Browser/version: Chrome 84.0.4147.89 x64
- Adblock Extension/version: Nano Adblocker 1.0.0.152 + Nano Defender 15.0.0.201

### Other details:

I propose moving `||an.yandex.ru^$domain=~e.mail.ru` from RU AdList to EasyList.

Screenshot: 
![image](https://user-images.githubusercontent.com/22780683/88482282-931a3600-cf60-11ea-91bf-737d20cae063.png)

**Comment by krystian3w** [comment]
fyi @dimisa-RUAdList

**Comment by krystian3w** [comment]
On Firefox I no see that ad. 

https://github.com/easylist/easylist/blob/951cb820f215a981649bc53d29898133f6a1dffd/easyprivacy/easyprivacy_thirdparty.txt#L158

**Comment by DandelionSprout** [comment]
I do not use EasyPrivacy or RU AdList in my everyday life. But now it looks like that entry should be moved from EasyPrivacy to EasyList as well.

**Comment by krystian3w** [comment]
moved with exclusion for Russian "Gmail"? ("`~e.mail.ru`")

**Comment by THEtomaso** [comment]
At my end, the ads are already blocked by five different filters:

* **Dan Pollock's hosts file**:
`an.yandex.ru`

* **EasyPrivacy**:
`||an.yandex.ru^`

* **hpHosts - Ad and Tracking servers only**:
`an.yandex.ru`

* **Lunar Blocklist by Moonchild**:
`||yandex.ru^$third-party`

* **MVPS HOSTS**:
`an.yandex.ru`

**Comment by krystian3w** [comment]
I trust Dimisa as script needed at mail.ru so hosts files alywas break site, "`Lunar`" have issues on github?

**Comment by THEtomaso** [comment]
> "`Lunar`" have issues on github?

Not that I'm aware of.
I'm sure Moonchild would have noticed that himself.

**Comment by krystian3w** [comment]
We're now waiting to see if he thinks the domain is too unpopular (or a famous spam bot) or a "celebrity" fanpage to send emails.

**Comment by dimisa-RUAdList** [comment]
Rule `||yandex.ru^$third-party` will break many Russian sites. As for the `an.yandex.ru` adserver, its use outside the Runet is an extremely rare case, and I do not think that the rule for blocking it should be added to the EasyList. However, it will be decided by its authors.

**Comment by DandelionSprout** [comment]
Blocking ads on English-language websites should *not* have to hinge on the use of EasyPrivacy, is my simple stance on what was discussed while I slept.

**Comment by DandelionSprout** [comment]
Other affected non-Russosphere websites that I could dig up after ~90min:
```
! English
https://koreanrandom.com/forum/topic/57422-na-a-solid-bargain/
https://flexberry.github.io/en/
https://autoprefixer.github.io/

! Arabic
https://newpal.ps/post/53531

! Romanian
https://conspecte.ro/

! Uzbek
https://ismlar.com/
```

**Comment by DandelionSprout** [comment]
EasyList is for ads. EasyPrivacy is for trackers. These are ads. So they should be in EasyList.

It literally is as simple as that, from what I'm aware of.

**Comment by THEtomaso** [comment]
I suspect `an.yandex.ru` of being a mixed bag, so it should probably be in both filters.

**Comment by DandelionSprout** [comment]
I've usually thought of EasyList as being *the* main list, and that EasyPrivacy would've only dealt with entries that weren't in EasyList at all. I may be wrong on this particular assumption, however.

**Comment by krystian3w** [comment]
Exceptions should then be on these 3 - After all, ABP does not support `badfilte`r and probably won't want to use `@@` instead of `~`.
