### ISSUE TITLE
xhamster.com [NSFW]

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#5842]
### List the website(s) you're having issues:

`https://xhamster.com/videos/japanese-taboo-threesome-mother-daughter-first-time-xhI6nd0`

### What happens?

Ads
<details>

![xhamster](https://user-images.githubusercontent.com/58900598/88916184-9aaf4700-d2a0-11ea-835d-a20e00493851.png)
</details>

### List Subscriptions you're using:

uBlock default + AdGuard JPN

### Your settings

- OS/version: Windows 10
- Browser/version: Brave 1.11.101
- Adblock Extension/version: uBO 1.28.4

### Other details:

Maybe
```
||thumb-v-lv.xhcdn.com/site/*.gif.$image
xhamster.com##.wih-spa
```

**Comment by spirillen** [comment]
You forgot to mention a popup in new window when clicking on thumb in front page

And poped up windows stays blank

```
https://tsyndicate.com/api/v1/direct/9e57aeece02545ceaafab3a235f150e5?domain=xhamster.com&rnd=0.18322956550667535&x=489&y=523&w=1000&h=450&adb=1&categories=Watch%20%20%20download%20more%20than%20million%20Porn%20Videos%20xHamster%20for%20free%20%20Stream%20new%20XXX%20tube%20movies%20online%20%20browse%20sex%20photos%20%20date%20girls%20fuck%20xHamster

    without parameters = https://tsyndicate.com/api/v1/direct/9e57aeece02545ceaafab3a235f150e5
    domain = xhamster.com
    rnd = 0.18322956550667535
    x = 489
    y = 523
    w = 1000
    h = 450
    adb = 1
    categories = Watch download more than million Porn Videos xHamster for free Stream new XXX tube movies online browse sex photos date girls fuck xHamster
```

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +101 |  |  | xhamster.com | 3 | media | `https://thumb-v2.xhcdn.com/a/8Q-njBcVBHFv9DMr1zOL2A/016/237/582/240x135.t.mp4` |
| +98 |  |  | xhamster.com | 3 | media | `https://thumb-v8.xhcdn.com/a/jRs0U_Oj8fM5ZFXqA-6Dmw/016/523/448/240x135.t.mp4` |
| +97 |  |  | xhamster.com | 3 | media | `https://thumb-v7.xhcdn.com/a/yj0rHXUTw00MEIuAIu7TFw/016/293/737/240x135.t.mp4` |
| +97 | `##[href^="https://twitter.com"]` |  | xhamster.com |  | dom | `https://xhamster.com/` |
| +97 | ##[class*="-cams-widget"] |  | xhamster.com |  | dom | `https://xhamster.com/` |
| +97 | ##.wig-cams-widget |  | xhamster.com |  | dom | `https://xhamster.com/` |
| +97 | ##.up-arrow |  | xhamster.com |  | dom | `https://xhamster.com/` |
| +97 | ##.socials |  | xhamster.com |  | dom | `https://xhamster.com/` |
| +97 | ##.cookie-announce |  | xhamster.com |  | dom | `https://xhamster.com/` |
| +97 |  |  | xhamster.com | 3 | image | `https://static-lvlt.xhcdn.com/xh-tpl3/images/favicon/favicon-16x16.png?1` |
| +97 |  |  | xhamster.com | 3 | image | `https://static-lvlt.xhcdn.com/xh-tpl3/images/favicon/apple-touch-icon.png?1` |
| +96 | \|\|collector.xhamster.com^ | -- | xhamster.com | 1 | xhr | `https://collector.xhamster.com/?log=experiment&stats_tkn=1%3A1%3A1603323312%3A03ccd8f48135c8e10484b8285e65c87bd1609e11` |
| +96 |  |  | xhamster.com | 3 | image | `https://widgets.stripst.com/us4/previews/1603322306/36541572` |
| +96 |  |  | xhamster.com | 3 | image | `https://static-lvlt.xhcdn.com/xh-tpl3/images/flags_2.png` |
| +96 | \|\|collector.xhamster.com^ | -- | xhamster.com | 1 | image | `https://collector.xhamster.com/?log=stats-beta&ref=&v=3.1&_=1603323314400&site=desktop&http_code=200&language=en&stats_tkn=1%3A1%3A1603323312%3A03ccd8f48135c8e10484b8285e65c87bd1609e11` |
| +96 | googletagmanager.com/gtm.js | << | xhamster.com |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-TLDPV3J` |
| +96 | \|\|googletagmanager.com/gtm.js$script | -- | xhamster.com | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-TLDPV3J` |
| +96 | \|\|tsyndicate.com^ | -- | xhamster.com | 3 | css | `https://lcdn.tsyndicate.com/sdk/v1/interstitial.ts.css` |
| +96 | no-remote-fonts: * true | -- | xhamster.com | 3 | font | `https://static-lvlt.xhcdn.com/xh-tpl3/fonts/64ff4210.xh-icons.ttf` |
| +96 | \|\|tsyndicate.com^ | -- | xhamster.com | 3 | script | `https://lcdn.tsyndicate.com/sdk/v1/interstitial.ts.js` |
| +96 | \|\|tsyndicate.com^ | -- | xhamster.com | 3 | css | `https://lcdn.tsyndicate.com/sdk/v1/interstitial.ts.css` |
| +96 | no-remote-fonts: * true | -- | xhamster.com | 3 | font | `https://static-lvlt.xhcdn.com/xh-tpl3/fonts/bb949b2f.xh-icons.woff` |
| +96 | no-remote-fonts: * true | -- | xhamster.com | 3 | font | `https://static-lvlt.xhcdn.com/xh-tpl3/fonts/fde1319c.xh-icons.woff2` |
| +96 |  |  | xhamster.com | 3 | image | `https://static-lvlt.xhcdn.com/xh-tpl3/images/rta.png` |
| +96 | \|\|tsyndicate.com^ | -- | xhamster.com | 3 | script | `https://lcdn.tsyndicate.com/sdk/v1/interstitial.ts.js` |
| +96 | \|\|tsyndicate.com^ | -- | xhamster.com | 3 | css | `https://lcdn.tsyndicate.com/sdk/v1/interstitial.ts.css` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/_-epLF3QT62dYXipWmRaUw/016/520/073/240x135.7.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/QbGL3CQ9gTFS9mGuDu28Rw/016/520/020/240x135.2.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/MPsEmlteO1dWY7L01_JUow/016/532/369/240x135.8.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/x74q2iWqBSWuBInmxj4XhA/016/530/475/240x135.7.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/7-dDVmnVbqy44YQpl4UFhQ/016/534/555/240x135.3.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/gsJvY1PQ9PeWXETCITKl6g/016/527/873/240x135.7.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/lEB4qjKoUFihP-upFUdhqQ/016/527/659/240x135.2.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/VDlZRwLZEeA7f2DB7Tgxcg/013/882/810/240x135.1.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/Pt0q3v2ZcC9tXHNxnW6jqQ/007/669/688/240x135.6.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/jW8i6uUoEPe17wOpKsk_TA/016/278/704/240x135.1.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/v27vekRYyGOeOOZA7VIoZw/016/527/469/240x135.4.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/Y6y8H6tFrC7XpsigKKiHAg/016/531/447/240x135.9.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/7M3LbECgrYZdgdbfa2BThg/016/527/804/240x135.8.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/NIj01oZ0clxMw5-I3ld7GQ/014/838/293/240x135.4.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/7_YL7BRwPgsdYYOF9PAotQ/016/540/772/240x135.9.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/Njyk5UuGLtHIsM2z3nsvtg/012/912/383/240x135.8.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/cNhBEEOwyHyhfRyY78viXA/012/910/222/240x135.9.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/5hBfd0nLP8--YtXeRfXPKQ/015/606/310/240x135.c.jpg.v1596648540` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/LbMLHIbPPJvK7F2PUofvwQ/016/104/319/240x135.1.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/g-k6o2WTZSZPaUBbi9ySyA/016/530/716/240x135.10.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/MKmVvuh5cjQFNtXV68Jk-g/016/528/734/240x135.5.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/KRo2GOFxJSNNjSdXnUWamw/015/383/872/240x135.c.jpg.v1595202780` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/lQSp5RLjOVfQN_MH9tUsUQ/005/823/064/240x135.1.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/vGSnttLXqbVakBft0m3Q1Q/015/050/922/240x135.6.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/X4TwAXr9yWWm4RhQbDuxzQ/015/429/714/240x135.5.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/m09kCtp_7zANk2cMCCbDUg/016/024/365/240x135.4.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/Gf3dC4p2vxgPANARSkcp2g/016/079/107/240x135.5.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/nG_pSBB0BhEEji5QrqYWQQ/016/534/340/240x135.10.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/0FQVi6uO-KYutPp8JEvPNA/016/521/338/240x135.6.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/HuKzxaDruqTuxpOSp_tIYQ/016/528/092/240x135.3.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/0nDievXFzsChuwZ4AICCmQ/016/527/616/240x135.3.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/IOsVUSV8YMzLHwv2BQlY1w/016/534/052/240x135.10.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/g1rx9HWu8E5-2-nddCMp0g/002/672/103/240x135.4.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/24QXfto4K4Y7uycKNYpA_g/016/034/750/240x135.4.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/grKub8poozMXQiq4JowuJw/012/439/849/240x135.2.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/J-iZz0ZBBV9AWqfzZyjroA/015/709/577/240x135.6.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/jft32DNBffQ8s5Y9_m21KA/006/425/363/240x135.7.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/bj6P07S2MHLmCCvkqI4Y0g/015/861/408/240x135.4.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/Cd2fcSmFTRvjMjz4oxOzHg/015/725/201/240x135.5.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/i46yUmAzI7o9Csnx6ujR5A/016/534/051/240x135.10.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/H4bf8c6DLcJJz4dyeqEYMg/005/058/704/240x135.5.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/jxtiZvRM5DJBMvxMrVI1Lw/016/527/793/240x135.1.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/2KkNq17x-zBVeuCippDaaw/016/508/740/240x135.9.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/tmWOovN3pbbJHBohHz3Pjw/016/529/187/240x135.1.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/8m3KuoIqMt9hCfHlvjSwIg/016/531/433/240x135.1.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/cYKM7I9NsdefcXgOtjOvtQ/016/533/733/240x135.4.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/O0gqGTzcee-f2mgzznqZog/016/531/344/240x135.6.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/n9si7J47IcMjPZXRMo0Sfg/016/081/488/240x135.7.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/LLH9_z3sFHc0LjmQKQYHhw/016/531/228/240x135.5.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/cQTq73bipUg4_zhzg2mRcg/016/536/574/240x135.c.jpg.v1603240200` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/m9l88ybOlhHXTD1kZ0IzOA/016/536/736/240x135.9.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/kxsKoC_Upk1FRZQsnHA1eQ/016/461/554/240x135.7.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/zjxMdk7HKCVtMogNPF-n6w/016/522/126/240x135.3.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/X_HK0twcUA64XjN3az7G-g/015/688/731/240x135.4.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/c4rcLm6fuLzrTwF0VVrv-g/016/488/584/240x135.7.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/F8pdaEcOnu4FBIW_ppIJZQ/016/479/560/240x135.6.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/t07nim-DybPM7jc3W5el3g/016/520/917/240x135.3.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/SLqdL0bhGBrdcROw_dYsyQ/016/514/110/240x135.5.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/CWmC8IFcLIauKN4NtqJKuQ/016/522/401/240x135.2.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/ZvO0haz7dZCHxLCWn2V5XQ/016/533/216/240x135.c.jpg.v1603217940` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/BxakLtGgmpvCJpuPWHuF9w/016/522/062/240x135.6.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/9VHyEs2DKiiiAd-o3Z2_Sg/016/315/286/240x135.c.jpg.v1601636520` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/5d_jYz2BQLF4JNj8X10-GA/016/382/200/240x135.7.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/bRkUpDu9xaeiGjsw75znhQ/016/455/655/240x135.9.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/PzOwBC1iX9AFiGvwtKmUhA/016/290/345/240x135.1.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/RnJt0yix0FhOHjrMA_iqyg/016/237/582/240x135.5.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/gfkUFyu8qpE65LQwLf1qzQ/016/293/737/240x135.7.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/VZZeFeotHpU2jsleiV4BFg/016/236/969/240x135.2.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/jjXGlqxL1yBOq2eXAp80Pg/016/481/043/240x135.2.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/9-4yMXbkJ8Hc_46QWJYy6w/016/354/060/240x135.c.jpg.v1601918940` |
| +96 |  |  | xhamster.com | 3 | image | `https://thumb-lvlt.xhcdn.com/a/OxuQ7ZvDP0qmn4JPpg_D_A/016/523/448/240x135.8.jpg` |
| +96 |  |  | xhamster.com | 3 | image | `https://static-lvlt.xhcdn.com/xh-tpl3/images/google-g-logo.svg` |
| +96 |  |  | xhamster.com | 3 | image | `https://static-lvlt.xhcdn.com/xh-tpl3/images/logo.svg` |
| +96 |  |  | xhamster.com | 3 | script | `https://static-lvlt.xhcdn.com/xh-tpl3/js/68907aaa.index.js` |
| +96 |  |  | xhamster.com | 3 | script | `https://static-lvlt.xhcdn.com/xh-tpl3/js/locales/en/a7c2817b.index.js` |
| +96 |  |  | xhamster.com | 3 | script | `https://static-lvlt.xhcdn.com/xh-tpl3/js/5348eff9.header.js` |
| +96 |  |  | xhamster.com | 3 | script | `https://static-lvlt.xhcdn.com/xh-tpl3/js/locales/en/a71da0ae.header.js` |
| +96 |  |  | xhamster.com | 3 | script | `https://static-lvlt.xhcdn.com/xh-tpl3/js/cf7db730.common.js` |
| +96 |  |  | xhamster.com | 3 | script | `https://static-lvlt.xhcdn.com/xh-tpl3/js/locales/en/e2cb94c4.common.js` |
| +96 |  |  | xhamster.com | 3 | css | `https://static-lvlt.xhcdn.com/xh-tpl3/css/67d10981.index.css` |
| +96 |  |  | xhamster.com | 3 | css | `https://static-lvlt.xhcdn.com/xh-tpl3/css/e55496e9.critical-index.css` |
| +96 | ##+js(addEventListener-defuser, , pop) |  | xhamster.com |  | dom | `https://xhamster.com/` |
| +96 | ##+js(abort-on-property-read, wih-popunder) |  | xhamster.com |  | dom | `https://xhamster.com/` |
| +95 | no-remote-fonts: * true | -- | xhamster.com | 1 | inline-font | `https://xhamster.com/` |
| +0 |  |  | xhamster.com | 1 | doc | `https://xhamster.com/videos/cute-young-skinny-petite-blonde-teen-first-ever-porno-pov-xhEBlc3` |
</details>

**Comment by spirillen** [comment]
Appendix (T2271)

Haven't checked if it is added, but at least a note about this tracking domain `collector.xhamster.com`
`https://collector.xhamster.com/?log=stats-beta&ref=https%3A%2F%2Fxhamster.com%2F&v=3.1&_=1603323532000&tag=is_sponsored&username=SkeetSites&videoId=16376647&site=desktop&http_code=200&language=en&isAdblock=1&stats_tkn=1%3A1%3A1603323529%3Acf49decd205684705789846685b1344857d4ce65`

**Comment by Yuki2718** [comment]
This was 3 months ago, but yeah I get popup now. @mapx- 
EP has `||collector*.xhamster.`.

**Comment by spirillen** [comment]
> This was 3 months ago, but yeah I get popunder now. @mapx-

Yeah but only about to reach the end of my notifications for EasyList now :smile: started with about 500 unread messages a couple of days ago, but 18 left to deal with :eyeglasses:

**Comment by LoreJon** [comment]
i get a popunder too.
if you use `||collector*.xhamster` something is broken.

`https://xhamster.com/videos/adam-zkt-eva-s01-e06-full-episode-2014-xh80t4W`

now press next will not work.

![pic](https://user-images.githubusercontent.com/16089271/96866845-95633200-1474-11eb-9a09-d8849db8eae0.png)

**Comment by spirillen** [comment]
> if you use `||collector*.xhamster` something is broken.
> 
> now press next will not work.

:thought_balloon: Is the actually anyone who use that?? I would have thought it would be the viewer who should decide what's next, and if they already know what **_YOU WANT_** next.... :thinking: ain't they holding to much information about you?

**Comment by Yuki2718** [comment]
@LoreJon Looks to be mobile device, can you make a new issue for that with all the details?

**Comment by LoreJon** [comment]
it's not mobile.
https://github.com/uBlockOrigin/uAssets/issues/8067

**Comment by LoreJon** [comment]
try in private mode.
