### ISSUE TITLE
https://www.youmath.it/

### ISSUE THREAD

**Issue by amivaleo** [easylist/easylist#5844]
### List the website(s) you're having issues:

`https://www.youmath.it/`

### What happens?

The entire website's content is hidden after a few seconds.

### List Subscriptions you're using:

https://easylist-downloads.adblockplus.org/easylist_min_content_blocker.json

### Your settings

- OS/version: GNU/Linux
- Browser/version: GNOME Web (a.k.a. Epiphany) version 3.36.3
- Adblock Extension/version: n/a

**Comment by llacb47** [comment]
What browser and what adblock extension?

**Comment by amivaleo** [comment]
> What browser and what adblock extension?

This one: Browser/version: GNOME Web (a.k.a. Epiphany) version 3.36.3

I have no info about the adblocker. It's coded in the browser.

**Comment by Yuki2718** [comment]
Not reproduced with Brave on Windows + uBO default lists (with or without ABP X Files) so I doubt it's an EasyList issue.

But I got this anti-adb IF Brave shield is turned on:

![youmath](https://user-images.githubusercontent.com/58900598/88935586-df48db80-d2bc-11ea-87ba-14f3671f6ebe.png)

On my end  `youmath.it##+js(noeval)` worked. @ryanbr

**Comment by mcatanzaro** [comment]
Jimmy, is the anti-adblock banner the only problem on this website? That's the only issue I see here. I don't think EasyList includes any anti-adblock blocking.

**Comment by amivaleo** [comment]
> Jimmy, is the anti-adblock banner the only problem on this website? That's the only issue I see here. I don't think EasyList includes any anti-adblock blocking.

If I load the same website on chrome or any other browser in which I disable the adblocker, I can normally visit any page in it.

The same happens if I disable epiphany's adblocker.

So yes, I believe the issue is related to that only.

**Comment by llacb47** [comment]
Easylist doesn't fix anti-adb (legal reasons).

https://github.com/easylist/easylist/issues?q=label%3AAnti-Adblock+label%3AInvalid+is%3Aclosed+

You should use uBlock Origin or Adguard and a browser which supports those.
