### ISSUE TITLE
androidheadlines.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5859]
### List the website(s) you're having issues:

`https://www.androidheadlines.com/2020/07/bluemail-app-removed-from-play-store-without-notice-from-google.html`

### What happens?

Social bar
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/89098232-75891880-d407-11ea-947d-73fc06b0522a.png)

</details><br/>
### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List
### Your settings

- OS/version: Windows 10 2004
- Browser/version: Firefox 79
- Adblock Extension/version: uBlock Origin 1.28.4

**Comment by krystian3w** [comment]
##.widget-ahsocial`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/936e5dd64e8da19e1df4ba734bfbd9dce3b23665
