### ISSUE TITLE
pastebin.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5904]
### List the website(s) you're having issues:
`https://pastebin.com/`

### What happens?

Cookie notice, signup notice
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/89510871-fd4d9900-d7f2-11ea-87a5-3c127a8ee92e.png)

</details><br/>
### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 79
- Adblock Extension/version: uBlock Origin 1.28.4

### Other details:

Maybe a generic rule can be made for the cookie notice: `##.-cookies.popup-box`

**Comment by SeriousHoax** [comment]
@Yuki2718 Hello Yuki. I wonder why this issue hasn't been touched by anyone yet for over a month considering how popular this site is. Can you check and if possible also create a pull request maybe?

**Comment by Yuki2718** [comment]
@SeriousHoax Will be fixed soon!

**Comment by P0Rtvine** [comment]
@ryanbr 
Cookies again

`https://pastebin.com/gf3UYWFc`
<details>
<summary>Screenshot</summary>

![2020-11-26_212800](https://user-images.githubusercontent.com/57287308/100386617-8d2b8300-302e-11eb-89fd-522ad68e4fa2.png)
</details>

**Comment by Yuki2718** [comment]
@P0Rtvine From your SS it should be covered by the current filter `##.-cookies` and actually I don't see the popup.
