### ISSUE TITLE
ytmp3.cc

### ISSUE THREAD

**Issue by Greg0rus** [easylist/easylist#5905]
To whom it may concern,

The website ytmp3.cc is not longer working. They've changed a few days ago the backend domains. So the old rules are not longer working and need to be updated with the new domain. 

old rules:
`@@||fjrifj.frl/check.php$script,domain=ytmp3.cc`
`@@||fjrifj.frl/progress.php$script,domain=ytmp3.cc`

new rules (with new domain):
`@@||ijjiii.is/check.php$script,domain=ytmp3.cc`
`@@||ijjiii.is/progress.php$script,domain=ytmp3.cc`

Thank you for your help!

**Comment by Khrin** [comment]
Already fixed https://github.com/easylist/easylist/commit/74ab185303a3c24fd9bb55b6ef037028f3733098
