### ISSUE TITLE
Reciteme Accessibility tools blocked

### ISSUE THREAD

**Issue by isaacsgraphic** [easylist/easylist#5912]
### List the website(s) you're having issues:
`https://www.strathunion.com/`
`https://kentunion.co.uk/`
There are many more sites which all use this tool but I don't have urls.

### What happens?

I was looking on `https://www.strathunion.com/` and noticed that the red "accessibility tools" button on the top left gets blocked in uBlock Origin, I checked `https://kentunion.co.uk/` too and it is the same. This is not an advert, just a useful toolbar for people with bad eyesight.

I'm not involved with ReciteMe, but their tools are useful & they are being blocked via uBlock and easyprivacy_trackingservers.txt

### List Subscriptions you're using:

Just uBlock on default settings

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox, Chrome
- Adblock Extension/version: uBlock 1.28.4

**Comment by THEtomaso** [comment]
> they are being blocked via uBlock and easyprivacy_trackingservers.txt

..and rightfully so, AFAICT.
Perhaps the buttons should be blocked too, to avoid confusion?:
`##.reciteme`
