### ISSUE TITLE
thehungersite.greatergood.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#5913]
### List the website(s) you're having issues:

`https://thehungersite.greatergood.com/clicktogive/ths/home`

### What happens?

Various placeholders spread around on the page.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/89627287-e8c4db80-d89a-11ea-9b0e-5873db14480a.png)

### Your settings

- OS/version: Windows 10 May 2020 Update
- Browser/version: Chrome 84.0.4147.105 x64
- Adblock Extension/version: Nano Adblocker 1.0.0.152 + Nano Defender 15.0.0.201

### Other details:

I propose adding `##.ctg-ad` and arguably also `##.banner-ad-large`, possibly as generic entries.

Without those entries: 
![image](https://user-images.githubusercontent.com/22780683/89627143-b0250200-d89a-11ea-8176-7939acaec47d.png)

With those entries: 
![image](https://user-images.githubusercontent.com/22780683/89627205-c92db300-d89a-11ea-8e37-3f5e3e572ddb.png)

**Comment by monzta** [comment]
`greatergood.com` seems unreachable at the moment. Will check later.
