### ISSUE TITLE
veranime.top

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [easylist/easylist#5920]
### List the website(s) you're having issues:

```https://veranime.top/```

### What happens?

Ads not blocked

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS (up to date)
- Browser/version: Chrome (up to date)
- Adblock Extension/version: AdBlock Plus

### Other details:

Screenshot

Ads on top right corner

![Captura de Pantalla 2020-08-07 a la(s) 10 00 37](https://user-images.githubusercontent.com/67610240/89648333-73a2d780-d895-11ea-8dec-44f403d73709.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d206893c2a3fc1c7855431c033c1cfd29c1f2119
