### ISSUE TITLE
verhentai.top

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [easylist/easylist#5921]
### List the website(s) you're having issues:

```https://verhentai.top/```

### What happens?

Ads not being blocked

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS (up to date)
- Browser/version: Chrome (up to date)
- Adblock Extension/version: AdBlock Plus

### Other details:

See issue https://github.com/easylist/easylist/issues/5920

Screenshot

Ads top right corner

![Captura de Pantalla 2020-08-07 a la(s) 10 13 34](https://user-images.githubusercontent.com/67610240/89649733-9fbf5800-d897-11ea-8e72-d3a3abaf4828.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d206893c2a3fc1c7855431c033c1cfd29c1f2119
