### ISSUE TITLE
solarmovie.ink

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [easylist/easylist#5922]
### List the website(s) you're having issues:

```https://www.solarmovie.ink/movie/filter/series```

### What happens?

Ads not blocked

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS (up to date)
- Browser/version: Chrome (up to date)
- Adblock Extension/version: AdBlock Plus

### Other details:

Screenshot

![Captura de Pantalla 2020-08-07 a la(s) 12 34 44](https://user-images.githubusercontent.com/67610240/89662506-912e6c00-d8aa-11ea-8aa8-9793b817e8da.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d206893c2a3fc1c7855431c033c1cfd29c1f2119
