### ISSUE TITLE
Twitch.tv pre-roll/pre-video ads (video ads)

### ISSUE THREAD

**Issue by an94baller** [easylist/easylist#5925]
List the website(s) you're having issues:

    https://www.twitch.tv/ (you can try big streamers, etc)
    https://www.twitch.tv/rainbow6 (example)

What happens?

    Preroll ads / Prevideo ads
    https://www.reddit.com/r/uBlockOrigin/comments/i57w8s/suddenly_getting_preroll_ads_on_twitch/

List Subscriptions you're using:

    https://i.imgur.com/D9XEqFr.png

Your settings

    OS/version: Windows 10
    Browser/version: Ublock Origin / Firefox v79 (latest)
    Adblock Extension/version: uBlock Origin v1.28.4

**Comment by an94baller** [comment]
Issue not fixed yet

**Comment by ryanbr** [comment]
Can't be fixed in EL @an94baller
