### ISSUE TITLE
(Brave Adblock) pureinfotech.com

### ISSUE THREAD

**Issue by TheAresjej** [easylist/easylist#5928]
### List the website(s) you're having issues:

https://pureinfotech.com

### What happens?

![image](https://user-images.githubusercontent.com/19390797/89737047-5d03a880-da6e-11ea-983e-368815c61c8f.png)

### List Subscriptions you're using:

Default settings

### Your settings

- OS/version: Windows 10 2004
- Browser/version: Brave 1.11.104
- Adblock Extension/version: https://github.com/brave/adblock-rust

**Comment by ryanbr** [comment]
Closing ticket, when this lands: https://github.com/brave/adblock-lists/issues/438  will be fixed @TheAresjej
