### ISSUE TITLE
Generic rule

### ISSUE THREAD

**Issue by Miyaav** [easylist/easylist#5930]
### List the website(s) you're having issues:

`https://dinleradyo.web.tr/stations/pop-90`

### What happens?

I don't know what the script is for, but can you create a general rule?
`https://adsense.analys.live/adsbygoogle/ads.js`

### List Subscriptions you're using: 
EasyList/AdGuard Tracking Protection/AdGuard Turkish

### Your settings

- OS/version: Win10
- Browser/version: Chrome 84
- Adblock Extension/version: uBlock Origin 1.28.4

### Other details:

<details> <summary>Screenshot</summary>

![ub](https://user-images.githubusercontent.com/69408732/89723786-5be96180-da03-11ea-97f9-4354f631d715.png)

</details>

**Comment by DandelionSprout** [comment]
The script appears to be dead or empty. If that hadn't been the case, I'd have supported this request quite a lot. 
![image](https://user-images.githubusercontent.com/22780683/89739314-f7201c80-da7f-11ea-915b-ae5e049fd446.png)

**Comment by THEtomaso** [comment]
AdSense is probably constantly shifting their nasty "services" between those new, free, and unholy TLDs.
The `.live` domain (which I personally block by default) seems to be gone, but once `dinleradyo.web.tr` has updated their site, the same script will most likely return, hosted at a new TLD.

Nevertheless, **Lunar Blocklist by Moonchild** already successfully blocks that script, based on its URL path, with the following generic rule:
`/adsense.`

**Comment by llacb47** [comment]
Um no. 

>Lunar Blocklist by Moonchild already successfully blocks it, based on its URL path, with the following generic rule

Naming a script `adsbygoogle` or `adsense` is a common anti-adblock mechanism, that's why those rules were removed from easylist. 

> AdSense is probably constantly shifting their nasty "services" between those new, free, and unholy TLDs.

I have never seen someone self-host Google ad scripts, it's probably against TOS/AuP. It's still a mystery why this script 404s though.

**Comment by Miyaav** [comment]
Thanks for respond
