### ISSUE TITLE
/epsilon. rule blocking all /epsilon subdomains across the internet

### ISSUE THREAD

**Issue by hectorakemp** [easylist/easylist#5940]
### List the website(s) you're having issues:
aeon.co
psyche.co

### What happens?

Hi there, I'm a developer working at https://aeon.co/ and https://psyche.co/. We publish high quality, long-form articles about science, technology, culture and history. Our asset CDNs `epsilon.psyche.co` and `epsilon.aeon.co` have been accidentally blocked by the new `/epsilon.` filter rule on https://easylist.to/easylist/easyprivacy.txt. 

We never have, and never will put advertising on either of our websites. 

I'm assuming `/epsilon.` is targeting https://us.epsilon.com/, but `/epsilon.` will target ALL `epsilon` subdomains across the internet, no matter what the top-level domain is. 

### List Subscriptions you're using:

https://easylist.to/easylist/easyprivacy.txt

### Your settings
<img width="643" alt="image" src="https://user-images.githubusercontent.com/28124379/89858321-b5a78280-dbe1-11ea-82ee-7af699d377aa.png">

- Browser/version: 
Mozilla Firefox (latest).
- Adblock Extension/version: 
uBlock origin (latest).

**Comment by ryanbr** [comment]
Has been adjusted, thanks
