### ISSUE TITLE
9to5mac.com

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [easylist/easylist#5950]
### List the website(s) you're having issues:

```https://9to5mac.com/2020/08/11/apple-online-store-adds-new-one-click-payment-option-for-apple-card-users/```

### What happens?

Website dark mode is broken and I cant scroll past the article to either read the comments or see more articles below

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS (up to date)
- Browser/version: Chrome (up to date)
- Adblock Extension/version: AdBlock

### Other details:

To be fair, ads are being blocked, but the experience on the website is broken/degraded

**Comment by THEtomaso** [comment]
AdGuard Base filter already contains the necessary fix:
https://github.com/AdguardTeam/AdguardFilters/blob/b38d01c66667add62299bab6f783618c3d6c8081/EnglishFilter/sections/whitelist.txt#L700

**Comment by a-privacy-conscious-user** [comment]
I can confirm, on my end, this rule ```@@||9to5mac.com^$csp``` fixes the issue
Thanks @THEtomaso

**Comment by THEtomaso** [comment]
The same fix is needed for the following sites, which appears to be using the same template:
```
9to5google.com
9to5toys.com
dronedj.com
electrek.co
```
