### ISSUE TITLE
epicgames.com

### ISSUE THREAD

**Issue by hawkeye116477** [easylist/easylist#5951]
### List the website(s) you're having issues:

`https://www.epicgames.com/id/login`

### What happens?

Hidden social login methods images.

### List Subscriptions you're using:

Fanboy's Social

### Your settings

- OS/version: Manjaro 20.0.3 Lysia
- Browser/version: Vivaldi 3.2.1967.41
- Adblock Extension/version: Nano Adblocker v1.0.0.152

### Other details:

Fix:
```
epicgames.com#@#.SocialIcon
```

**Comment by Khrin** [comment]
Fixed.
