### ISSUE TITLE
admedia.agency

### ISSUE THREAD

**Issue by herormo** [easylist/easylist#5953]
### List the website(s) you're having issues:
admedia.agency

### What happens?
Our clients' business website domain contains 'ad'. Anyone with ad blocker software installed on their browser see the site in a very jumbled fashion.

They're a legit business, not scamming or spamming anyone and not an ad serving website. They are a service-based agency that specializes in media buying and video production with over 10 years of experience.

We appreciate it if someone could help us with this!

### Other details:
![admedia_blocked](https://user-images.githubusercontent.com/13970238/90024686-d513dd80-dcbd-11ea-9a28-e28a2078ad66.png)

**Comment by Khrin** [comment]
Fixed.

**Comment by herormo** [comment]
Thank you @Khrin! how long does it take for ad blockers to update their lists?

**Comment by Khrin** [comment]
@herormo In a few days everyone should have the filter list updated and anyway it's possible to force an update in any moment.
