### ISSUE TITLE
indianexpress.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#5962]
### List the website(s) you're having issues:

`https://indianexpress.com/article/india/coronavirus-live-updates-corona-cases-india-worldwide-covid-19-vaccine-tracker-latest-news-update-6550785/`

### What happens?

1. Go to the above mentioned site 
2. Scroll down a bit
3. See the floating element at the right bottom of the screen 

### List Subscriptions you're using:

AdGuard Base
AdGuard Mobile Ads
EasyList
EasyPrivacy 
AdGuard Annoyances
Fanboy’s Annoyance
uBlock filters – Annoyances

### Your settings

- OS/version: Android 10
- Browser/version:  Browser: Firefox on Android (Fenix): 79.0.3.

- Adblock Extension/version: uBO 1.29.0

### Other details:

![Screenshot_20200813-144346(1)](https://user-images.githubusercontent.com/69183387/90118133-6d20ce00-dd75-11ea-8891-e4d687b19fec.png)

**Comment by Bluedot449** [comment]
There seems to be a `x` mark still floating at the right side. Scroll down the page till the end on mobile to see it.


![Screenshot_20200815-084059](https://user-images.githubusercontent.com/69662619/90304262-9c4d5180-ded3-11ea-9949-2c7b846bd13c.png)

**Comment by Khrin** [comment]
Thank you.
