### ISSUE TITLE
es.xhamster.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#5966]
### List the website(s) you're having issues:

```https://es.xhamster.com/```

### What happens?

Popunder (I click on something and it opens on a new tab meanwhile the tab I was on, is on the background loading an ad) not being blocked

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS (up to date)
- Browser/version: Firefox (up to date)
- Adblock Extension/version: AdBlock

### Other details:

Important: I only being able to reproduce this issue on Firefox (Chrome is fine). I think Firefox adblocking quality has always being inferior to Chrome (at least thats has been my experience so far)

**Comment by a-privacy-conscious-user** [comment]
Same happens on ```https://es.pornhub.com/```

**Comment by ryanbr** [comment]
Probably occurs, needs a snippet to counter it.
