### ISSUE TITLE
hothardware.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#5968]
### List the website(s) you're having issues:

`https://hothardware.com/news/spacex-starlink-satellite-internet-beta-users-hitting-downloads-of-up-to-60-mbps`

### What happens?

Placeholder above the article, as well as a very thin placeholder at the very bottom of the page.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/90292018-5f586f00-de81-11ea-8cf9-6b2465b69a25.png)

### Your settings

- OS/version: Windows 10 May 2020 Update
- Browser/version: Chrome 84.0.4147.125 x64
- Adblock Extension/version: Nano Adblocker 1.0.0.152 + Nano Defender 15.0.0.201

### Other details:

I propose adding `##.ad-top-billboard` and `###ad-sticky-footer-container` to EasyList as generic entries to remove the placeholders.

The above-article placeholder without the fix: ![image](https://user-images.githubusercontent.com/22780683/90291777-ea853500-de80-11ea-818e-ad2f7e08d201.png)

With the fix: 
![image](https://user-images.githubusercontent.com/22780683/90291832-ff61c880-de80-11ea-8927-25a55177c180.png)

**Comment by krystian3w** [comment]
It's with at least 90 px, small ones tend to have ~20px and not everyone is sensitive to it.
