### ISSUE TITLE
www.space.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#5974]
### List the website(s) you're having issues:

 `https://www.space.com/15994-carl-sagan.html`
   
 ### What happens?
 
   * Pop-up video player
   * scroll a bit further down to see the video player
 
 
 ### List Subscriptions you're using:

 AdGuard Base
 AdGuard Mobile Ads
 EasyList
 EasyPrivacy
 AdGuard Annoyances
 Fanboy’s Annoyance
 uBlock filters – Annoyances
 ### Your settings

     * OS/version: Windows 10
 
     * Browser/version:  Firefox 79.0 desktop
 
     * Adblock Extension/version: uBO 1.29.0

 ### Other details:
![Screenshot (10)](https://user-images.githubusercontent.com/69662619/90306412-92831880-deea-11ea-89c2-ac47b2515067.png)

**Comment by krystian3w** [comment]
`##.sticky-player-background`

**Comment by krystian3w** [comment]
Still no fixed:

https://github.com/easylist/easylist/commit/b537f7ef166b176731944104692b1227616d3595

Player visible, but logo "SPACE:" and :x: gone...

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/b537f7ef166b176731944104692b1227616d3595#commitcomment-41506729
