### ISSUE TITLE
tiktok.com

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#5975]
### List the website(s) you're having issues:

`https://www.tiktok.com/ja/`

<strong>Account required</strong>

### What happens?

Unblocked analytics `||t.tiktok.com/api/impression/$xmlhttprequest`

![tiktok1](https://user-images.githubusercontent.com/58900598/90311715-0d732000-df39-11ea-9a4b-bb9a622e08b5.png)

This `t.tiktok.com` staff is sending various info such as screen resolution, however, <strong>blocking this domain causes problems</strong> such as never loaded pages even if redirected to neutered resources. But apparently this "impression" path can safely be blocked.

### List Subscriptions you're using:

uBO default + AGJPN

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 79.0
- Adblock Extension/version: 1.29.0

**Comment by llacb47** [comment]
You beat me to reporting :) It happens from various subdomains so `||tiktok.com/api/impression/write/` is OK I think.

`t.tiktok.com` is used in japan and other non-english places.

**Comment by Yuki2718** [comment]
> You beat me to reporting :) 

Haha, actually it's you who drove me to report some tracker ;)
