### ISSUE TITLE
telegram.hr

### ISSUE THREAD

**Issue by Marko-HR** [easylist/easylist#5978]
### List the website(s) you're having issues:

`https://www.telegram.hr/`

### What happens?

When website is loaded, cookie notification is shown.

### List Subscriptions you're using:

https://imgur.com/a/6d0UI2h

### Your settings

- OS/version: Windows 10 version 2004
- Browser/version:  Chrome v84.0.4147.125
- Adblock Extension/version:  uBlock Origin v1.28.4

### Other details:

Screenshot: https://imgur.com/a/EEzfMgt

**Comment by ryanbr** [comment]
Will only apply to Easylist Cookie List

https://github.com/easylist/easylist/commit/86403d856ea28c4d1f593c1e2f2d2baeaa3b9877

**Comment by Marko-HR** [comment]
@ryanbr This pop-up notification cannot be effectively hidden?
