### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by M1cha** [easylist/easylist#5997]
### List the website(s) you're having issues:
https://youtube.com

### What happens?
normal-popus like "save to playlist" are incorrectly being blocked.
This is due to `youtube.com##ytd-popup-container` added by commit https://github.com/easylist/easylist/commit/37908e6126489cb2cdf1d66787e1fb78e34b3421

### List Subscriptions you're using:
Fanboy’s Annoyance

### Your settings
- OS/version: Arch Linux
- Browser/version: Chromium 84.0.4147.125
- Adblock Extension/version: uBlock Origin

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/commit/6aa17e9642d2088dae3b29a63931f93da6219fc4
