### ISSUE TITLE
https://igg-games.com

### ISSUE THREAD

**Issue by blim94** [easylist/easylist#5998]
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
@blim94  site looks fine? not enough details supplied. closing ticket.

**Comment by stephenhawk8054** [comment]
I think there's a suspicious 3rd party xhr link in download links.

URL: `https://igg-games.com/motorcycle-mechanic-simulator-2021-free-download.html`

Scroll down to the download links, click on any link, a new tab with `bluemediafiles.com` domain appears. There's a suspicious `xhr` link with domain `echnolog.club` that I'm not sure if it's used for tracking or not:

`https://echnolog.club/utx?tid=930395&top=bluemediafiles.com&cb=RHRthoMPFCoL`

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/142348830-0b9183f1-0ed6-44f5-af61-5ce22e0f7df7.png)

</details>

Firefox 94.0.1, ublock 1.38.6 default.

Proposed filter:

`||echnolog.club^`
