### ISSUE TITLE
docs.axway.com - easylist cookie

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#6005]
### List the website(s) you're having issues:
`https://docs.axway.com/bundle/AMPLIFY_Integration_Builder_allOS_en/page/magento_soap_v1_9_querying.html`

### What happens?
The list easylist cookie make the site display a white page, when it ask if we allow the cookies. So if you're not in the UE it may not be blank.

### List Subscriptions you're using:
easylist, easylist fr, easylist cookie

### Your settings

- OS/version: win10
- Browser/version:  ff
- Adblock Extension/version:  ublock orogin

### Other details:
removing the class "cookieVisible" to the body solve the problem

**Comment by krystian3w** [comment]
So need add `:not(body)`.

```diff
-##.cookieVisible
+##.cookieVisible:not(body)
```

**Comment by momala454** [comment]
thanks, do you need some confirmation before publishing it ?

**Comment by krystian3w** [comment]
It probably has to wait until someone finds time for a simple test.

> So if you're not in the UE it may not be blank.

As much as I could, the whole world probably has a blank site - I tested with VPN:

- New Zealand 🇳🇿 
- South Korea 🇰🇷 
- Moldova 🇲🇩 
- Norway 🇳🇴

**Comment by krystian3w** [comment]
https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/361
