### ISSUE TITLE
Consider to change the popin rule in EasyPrivacy

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#6009]
### List the website(s) you're having issues:

`https://www.sanspo.com/`

### What happens?

I noticed
`||popin.cc^$third-party`
was added to EP by this commit: https://github.com/easylist/easylist/commit/d428616c9cde9b70dcf2eb40fe1372454bbcb332 and frankly suggest either to revert the change back or to replace with
`||popin.cc/searchbox`.
I understand recent EP's approach to those behavior-based AI staff, but in this case it will cause lots of problems. An example I can show now is `https://www.sanspo.com/`. Test in-page search as in the SS below:

![sanspo1](https://user-images.githubusercontent.com/58900598/91546346-4362cc00-e95d-11ea-9625-5e7873066da9.png)

![sanspo2](https://user-images.githubusercontent.com/58900598/91546356-452c8f80-e95d-11ea-88c9-927c7463afcf.png)

### List Subscriptions you're using:

uBO default + AGJPN

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 79.0
- Adblock Extension/version: uBO 1.29.2

### Other details:

If one example is not enough to convince you, give me a month and I'll probably find a dozen of cases. The suggested rule completely blocks popin recommend while leaving other vital function intact - 280blocker and I have been with this rule for more than a year and only had one FP which no more exists. It misses some tracker but they are covered by generic rules in EP such as `/log.gif?`.

BTW, I found
`||cnobi.jp^*/js/imp.`
in EP which is called from / a child of
`||rcm.shinobi.jp^`
so the first rule can safely be removed. Unlike popin, I fully support blocking this recommendation staff.

**Comment by Yuki2718** [comment]
Found AG Japanese also has the rule. I'll make the same suggestion there, and probably look for another example to support my arguments but not soon.

**Comment by Yuki2718** [comment]
Although related sites:
`https://www.sankei.com/`
`https://www.iza.ne.jp/`

<details>

![sankei](https://user-images.githubusercontent.com/58900598/92003854-743b6a80-ed7c-11ea-8373-8b0a7f36d99c.png)

![iza](https://user-images.githubusercontent.com/58900598/92003910-84534a00-ed7c-11ea-9446-3bc6aeea6f71.png)

</details>

(AG JPN's `/popin.js` is also causing the issue at iza, will report back.)

If you wanna fix them by exception, all these will be needed:
```
@@||popin.cc/popIn_custom_search-min.js
@@||popin.cc/partner/$script
@@||search.popin.cc^*/select/$script
``

**Comment by Yuki2718** [comment]
Found a different case which my suggestion of `||popin.cc/searchbox` doesn't work.
`https://www.mikihouse.jp/store/item/40-2379-95100080500`
"Search by image" doesn't work if you block popin.

<details>

![mikihouse](https://user-images.githubusercontent.com/58900598/92006051-35f37a80-ed7f-11ea-9abb-992560ae6440.png)

</details>

`@@||popin.cc/searchbox/action_$script` required

**Comment by ryanbr** [comment]
Has removed.
https://github.com/easylist/easylist/commit/f5454f43fe82f77984f7025024360feb4a3b9e8f

**Comment by Yuki2718** [comment]
Thx!
