### ISSUE TITLE
Annoyance filter submission: Facebook's new excessive notifications

### ISSUE THREAD

**Issue by cjrobe** [easylist/easylist#6010]
The new Facebook has a really annoying new top bar with redundant and out of control notifications with no way to disable them. While it is already on the left side of the screen with tasteful blue notification text, there is now Video, Group, and Page notifications that will constantly fill up and have red numbers on the top of the your screen just like your standard notification center. Since you can already know if you have Page or new Group posts from your left side notification center, you can filter out just the red numbers and keep the buttons for navigation purposes.

`facebook.com##[aria-label*="Pages"] span span`
`facebook.com##[aria-label*="Groups"] span span`
`facebook.com##[aria-label*="Watch"] span span`

Before and after:
![O8VeSK8](https://user-images.githubusercontent.com/5606066/91624757-0fdd6d00-e970-11ea-9b0b-61a68ed1d2e4.jpg)

**Comment by krystian3w** [comment]
No everyone have `aria-label` on FB. Also this generate language limits (no worth for German / French / Italian).

Try someting like:
```
facebook.com##[href^="/pages/"][role="link"] span span
facebook.com##[href^="/groups/"][role="link"] span span
facebook.com##[href^="/watch/"][role="link"] span span
```

PS. I don't have pages buttons, so may have other url.

**Comment by ryanbr** [comment]
Might cause too many issues to include in this list tbh.
