### ISSUE TITLE
Uploadraja.com

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6011]
### List the website(s) you're having issues:

`https://uploadraja.com/tv3k28ryx1jx`

### What happens?

Taboola ads/banner

### Which adblock lists are you're using?

Ublock default lists

### Your settings

- OS/version: windows
- Browser/version: firefox stable 80.0
- Adblock Extension/version: ublock origin 1.29

### Other details:

Fixable with generic  `*/taboola.php`
Or
Small filters specific to site
`||home4loans.info^`

**Comment by spirillen** [comment]
Can't reproduce...

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/44526987/92384287-1b6b2980-f110-11ea-992f-8143035faf07.png)

![image](https://user-images.githubusercontent.com/44526987/92384314-2625be80-f110-11ea-80ca-9ce33e9ad140.png)

</details>
