### ISSUE TITLE
Easylist cookie - didomi

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#6014]
### List the website(s) you're having issues:
```
https://www.generation-nt.com/ovhcloud-serveurs-dediees-noms-domaines-promotions-actualite-1979446.html
http://www.allocine.fr/
```

### What happens?
They now show cookie popup

![image](https://user-images.githubusercontent.com/83005/91731099-d9d5fe00-eba6-11ea-9c24-26e065c15f49.png)

### List Subscriptions you're using:
easylist,
easylist fr
easylist cookie

### Your settings

- OS/version: 
- Browser/version:  firefox
- Adblock Extension/version:  ublock origin

**Comment by krystian3w** [comment]
I suppose blocked inccorect with EasyPrivacy.

`allocine.fr` block scroll on site or load videos if pop-up is hidden?

**Comment by momala454** [comment]
i don't have easyprivacy, if i enable it it remove the cookie poup, but i don't have easyprivacy

**Comment by krystian3w** [comment]
So no worth for EasyList Cookie - list is no specialize with repair broken scroll after hide pop-up.

**Comment by momala454** [comment]
the popup is not hidden as shown in the screenshot

**Comment by momala454** [comment]
another one on allocine

![image](https://user-images.githubusercontent.com/83005/92310275-f01bf980-efac-11ea-89b5-11e428832338.png)

**Comment by krystian3w** [comment]
But 1 of 2 is no blockable by networks filter/rule.

**Comment by momala454** [comment]
i don't think that i've understood your question about not working scroll

**Comment by spirillen** [comment]
Well I can somewhat concur to the last suggestion of blocking `privacy.center.org` as both links from OP is working without any issues in my test. And I have them blocked completely

|id (Below 6mill is more than 2 years old) |name|type|content|
|--|----|----|-------|
|3114085|privacy-center.org.rpz.mypdns.cloud|CNAME|.|
|3114086|staging.privacy-center.org.rpz.mypdns.cloud|CNAME|.|
|3114087|api.staging.privacy-center.org.rpz.mypdns.cloud|CNAME|.|
|3114088|api.privacy-center.org.rpz.mypdns.cloud|CNAME|.|
|3114089|sdk.privacy-center.org.rpz.mypdns.cloud|CNAME|.|
|3114090|sdk-cl.privacy-center.org.rpz.mypdns.cloud|CNAME|.|
|3114091|cojecom.privacy-center.org.rpz.mypdns.cloud|CNAME|.|
|3114092|www.privacy-center.org.rpz.mypdns.cloud|CNAME|.|
|6398834|privacy-center.org.tracking.mypdns.cloud|CNAME|.|
|6398835|*.privacy-center.org.tracking.mypdns.cloud|CNAME|.|


![image](https://user-images.githubusercontent.com/44526987/92312741-11d4ab00-efc4-11ea-9d20-09dbb0c6ac09.png)

**Comment by momala454** [comment]
hello, it looks like blocking https://sdk.privacy-center.org now prevents videos from allocine to be playing @spirillen  can you test ?

**Comment by krystian3w** [comment]
Yes, block this domain break play video on many German and Polish sites.

**Comment by spirillen** [comment]
I can not confirm it should be related to any of `privacy-center.org` contents....

I have tested with this rule in the Pale Moon, FF & Tor browser...

```
! 2020-12-21 https://www.allocine.fr
@@||privacy-center.org^
```

And nothing is playing on `https://www.allocine.fr/`, there is a single hit within the DNS logs and that is it.

**Comment by momala454** [comment]
easylistcookie contains now ||privacy-center.org^$3p

which breaks allocine and others ...
