### ISSUE TITLE
Challange: fuck8.us

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#6015]
### List the website(s) you're having issues:

`fuck8.us`

### What happens?

As soon as you arrives to the site, a background counter is starting counting down for:

  1. Redirect you to `pornhub`
  1. Open a popup/under

The outgoing url is `http://fuck8.us/?p=digits` ex `http://fuck8.us/?p=1234`

I haven't been able to locate the script that does this :unamused: However I can conclude  that a lot of sites/users/webmasters etc are extremely tired of this domain.

from `cjwebmasters.com` blocking list:
![image](https://user-images.githubusercontent.com/44526987/91896117-9fe52480-ec98-11ea-8e60-962e3e10cae5.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/44526987/91896209-c3a86a80-ec98-11ea-9492-77bc775f9d9e.png)
![image](https://user-images.githubusercontent.com/44526987/91896227-ca36e200-ec98-11ea-8be7-5272f25bcd3e.png)
![image](https://user-images.githubusercontent.com/44526987/91896248-cefb9600-ec98-11ea-92be-ec61589634a3.png)
![image](https://user-images.githubusercontent.com/44526987/91896270-d622a400-ec98-11ea-90fd-2b335d879c26.png)

### Your settings

- OS/version: 5.4.0-45-generic
- Browser/version:  Tor
- Adblock Extension/version: uBlock origin 1.29.2

### Other details:

Some rules I have been playing with, with no luck
```
! 2020-09-01 fuck8.us
||fuck8.us/?p=*^$important
||fuck8.us/wp-content/themes/retrotube/assets/js/skip-link-focus-fix.js?ver=1.0.0$script,important
||fuck8.us/?p=$document,important
```

**Comment by krystian3w** [comment]
try:

`fuck8.us###direct, #gohub:remove()`
`fuck8.us##^#direct, #gohub`
`fuck8.us##+js(nostif, click, 5000)`
`fuck8.us##+js(acis, click, gohub)`

AdGuard addon Firefox / AdGuard for Windows 7.5.1, macOS 2.X.X, Android 3.4:

`fuck8.us$$#direct`
`fuck8.us$$gohub`

---



sources:

```html
<a id="direct" href="http://fuck8.us/?p=972"></a>



<script>		

setTimeout(function(){	
	
document.getElementById('direct').click(); 
 }, 5000);
		
</script>	
```

```html
<a id="gohub" href=" https://jp.pornhub.com/view_video.php?viewkey=ph5ec628858ee03"></a><script >

document.getElementById('gohub').click();

</script>
```

**Comment by spirillen** [comment]
Hey @krystian3w You don't need to be :confused: When I say I didn't find, you should think 2 to 3 minutes, tops and from the uBlock Origin logger :hourglass: 

When I find something on my domain hunts, I'll pass them here, you guys are the specialist in this kind of scouting :smiley:  and by that able to locate these kind of things faster than me, and even writing the rules for easylist :smiling_imp: 

Beside of this, you rules seems to work in Tor, and I even found a new domain :smiley: which you actually already have :1st_place_medal:

**Comment by krystian3w** [comment]
This is invisible with uBO / AdGuard logger, need use old `view-source:`.
