### ISSUE TITLE
m.facebook.com

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#6018]
### List the website(s) you're having issues:

`https://m.facebook.com`

### What happens?

Facebook Lite app promotion banner not blocked.

### List Subscriptions you're using:

Default uBlock Origin lists + AdGuard Base + AdGuard Mobile Ads + AdGuard Tracking Protection + Fanboy’s Enhanced Tracking List + Spam404 + AdGuard Annoyances + Fanboy’s Annoyance + uBlock filters – Annoyances + Nano Defender Integration + Nano Filters

### Your settings

- OS/version: Windows 10 2004
- Browser/version: Chrome 85.0.4183.83
- Adblock Extension/version: uBlock Origin 1.29.2

### Other details:

Checked uBlock Origin logger in responsive mode in chrome debugger with Moto G4 as target device. Found some filters:
```
m.facebook.com###login_top_banner
```

**Comment by krystian3w** [comment]
May break login forms on all places.

**Comment by cantunborn** [comment]
Is there another solution that does not break anything?

**Comment by spirillen** [comment]
I know one :smirk: `||facebook.*^` :rofl: 

Best regards
  Monty Python's Flying Circus :circus_tent:

**Comment by DandelionSprout** [comment]
Presuming you (cantunborn) is on [Tier 3 of Facebook sites](https://github.com/DandelionSprout/adfilt/blob/master/Wiki/Facebook%20domain%20functionality%20tiers.md#tier-3-old-phones) and want to block the app button below the channel header, I propose the following entry:

`m.facebook.com,b-m.facebook.com,mobile.facebook.com,mbasic.facebook.com,d.facebook.com,free.facebook.com,0.facebook.com,m.facebookcorewwwi.onion,b-m.facebookcorewwwi.onion,mobile.facebookcorewwwi.onion,mbasic.facebookcorewwwi.onion,d.facebookcorewwwi.onion,free.facebookcorewwwi.onion,0.facebookcorewwwi.onion###pages_call_to_action`
