### ISSUE TITLE
Filter breaks mail.yahoo.com contacts list

### ISSUE THREAD

**Issue by BTx123** [easylist/easylist#6023]
### List the website(s) you're having issues:

* `https://mail.yahoo.com`
* `https://mail.yahoo.com/d/folders/1`

### What happens?

When logged in to Yahoo, contacts list appears empty (see screenshot below). Also, contacts are not suggested when composing new emails and I cannot create new contacts.

### List Subscriptions you're using:

* ublock-filters
* ublock-badware
* ublock-privacy
* ublock-abuse
* ublock-unbreak
* adguard-generic
* adguard-mobile
* easylist
* adguard-spyware
* easyprivacy
* fanboy-enhanced
* urlhaus-1
* spam404-0
* adguard-annoyance
* fanboy-annoyance
* ublock-annoyances
* plowe-0
* https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

### Your settings

- OS/version: Windows 10 Home Version 2004
- Browser/version: Firefox 80.0.1
- Adblock Extension/version: uBlock Origin v1.29.2

### Other details

* Screenshot of empty contacts list 
  * Normally lists my contacts, but now all I see is a brief flash when the contacts try to load, then it says "No contacts available"
![image](https://user-images.githubusercontent.com/11324822/92207510-2c7d1780-ee3e-11ea-9c9d-629856f69538.png)

* Filter [data.mail.yahoo.com](data.mail.yahoo.com) was added in commit 83a23ca, disabling it with `@@||data.mail.yahoo.com^$domain=mail.yahoo.com` seems to mitigate the issue.

**Comment by krystian3w** [comment]
check on:

`https://mail.yahoo.com/b/folders/1`

I suppose EasyList test account no have new layout `/d/` (my account support both).

**Comment by BTx123** [comment]
Contacts still appear on `https://mail.yahoo.com/b/folders/1`, so it looks like the filter only breaks the newest layout.

**Comment by krystian3w** [comment]
try:

```
||data.mail.yahoo.com^$all
@@||data.mail.yahoo.com/xobni/v*/contacts/*$xmlhttprequest,domain=mail.yahoo.com
```

IDK, but maybe uAssets disabled with `badfilter`  moddifier the bad "`||data.mail.yahoo.com^`"` filter like:

`||data.mail.yahoo.com^$badfilter`

so problem no exist with with uBO.

**Comment by krystian3w** [comment]
I found revert: https://github.com/easylist/easylist/commit/6f807ea8c87f7602e57119d29eb7efbb2a5cbd65

**Comment by ryanbr** [comment]
It was a badfilter, and was removed.   Just force an update of the filters.

**Comment by BTx123** [comment]
Thanks! All good now.
