### ISSUE TITLE
weedmp3.com

### ISSUE THREAD

**Issue by wch01849585** [easylist/easylist#6025]
### List the website(s) you're having issues:

https://weedmp3.com/eminem-on-fire/

### What happens?

Sometimes i can use website no problem

Sometimes button open new browser to advertising, sometimes redirect to advertisement during click on button (i circle red in picture down)

![aaaaaaaaa](https://user-images.githubusercontent.com/70817922/92311479-f086b580-efe9-11ea-8382-651d85ef1238.jpg)

Thank you

### List Subscriptions you're using:

ABP filters
EasyList

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome 85.0.4183.83
- Adblock Extension/version: 3.9.4

**Comment by ryanbr** [comment]
Fixed.  Btw, use the other "Download Audio"
