### ISSUE TITLE
google.de cookie permission 

### ISSUE THREAD

**Issue by Speciesx** [easylist/easylist#6027]
Is it possible to remove or at least to hide this?

### List the website(s) you're having issues:

https://www.google.de/
### What happens?

![google1](https://user-images.githubusercontent.com/1196375/92415179-10d48280-f158-11ea-89ea-cad1d1e14e02.png)
![google2](https://user-images.githubusercontent.com/1196375/92415186-1336dc80-f158-11ea-9fa4-bafdf71a6144.png)

### List Subscriptions you're using:

![ublock](https://user-images.githubusercontent.com/1196375/92415176-0adea180-f158-11ea-921b-cd4b3b1b21d4.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox nightly
- Adblock Extension/version: uBlock Origin 1.29.2 + Cookie AutoDelete

**Comment by krystian3w** [comment]
EasyList cannot repair scrolling without more breakage as frozen scroll.

---

Poland solution by `CSS` / `:remove()`:

> * by `CSS`:
> 
>    > 
>    >     www.google.*##body.QVCmK:style(position: static !important; overflow-y: visible !important;)
>    >     www.google.*##html.QVCmK:style(overflow-y: visible !important;)
>    >     www.google.*###main #lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7)
>    >     www.google.*###main #lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"])
> > 

 > ---

> * by `:remove()`:
> 
>    > 
>    >     www.google.*###main #lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7):remove()
>    >     www.google.*###main #lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"]):remove()
>    >

---

IMO nobody risk break Google after hide pop-up.

**Comment by Speciesx** [comment]
This work fine.
