### ISSUE TITLE
gnula.nu

### ISSUE THREAD

**Issue by TheFilterGuy** [easylist/easylist#6029]
### List the website(s) you're having issues:

```http://gnula.nu/```

### What happens?

Popups not blocked

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS
- Browser/version: Chrome
- Adblock Extension/version: AdBlock Plus

### Other details:

![Captura de Pantalla 2020-09-07 a la(s) 20 27 33](https://user-images.githubusercontent.com/70922433/92420263-b8e24f80-f148-11ea-9926-4c573f98bea3.png)
![Captura de Pantalla 2020-09-07 a la(s) 20 27 31](https://user-images.githubusercontent.com/70922433/92420264-ba137c80-f148-11ea-9b1e-eee08c356293.png)

**Comment by TheFilterGuy** [comment]
Not fixed. Took these screenshots just now

![Captura de Pantalla 2020-09-08 a la(s) 17 33 17](https://user-images.githubusercontent.com/70922433/92525320-0074e400-f1fa-11ea-906b-6308592ca407.png)
![Captura de Pantalla 2020-09-08 a la(s) 17 33 13](https://user-images.githubusercontent.com/70922433/92525325-023ea780-f1fa-11ea-8215-7dcd19584dd7.png)
![Captura de Pantalla 2020-09-08 a la(s) 17 33 11](https://user-images.githubusercontent.com/70922433/92525328-02d73e00-f1fa-11ea-8a65-360cc1a00e5d.png)

**Comment by llacb47** [comment]
> * Adblock Extension/version: AdBlock Plus

I think I see the problem
