### ISSUE TITLE
nhentai.com

### ISSUE THREAD

**Issue by TheFilterGuy** [easylist/easylist#6038]
### List the website(s) you're having issues:

```https://nhentai.com/```

### What happens?

Popunders not blocked

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS
- Browser/version: Chrome
- Adblock Extension/version: AdBlock Plus

**Comment by ryanbr** [comment]
Won't stop popunders completely.

**Comment by Yuki2718** [comment]
@ryanbr `##.pb-0.w-100` hides too many, it hides tags to narrow down contents:

![nhentai](https://user-images.githubusercontent.com/58900598/92471573-2195fe80-f213-11ea-9891-6417cf4726fd.png)

Just adding [style] will be enough to fix this, i.e. `nhentai.com##.pb-0.w-100[style]`
