### ISSUE TITLE
nhentai.net

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#6043]
### List the website(s) you're having issues:

```https://nhentai.net/```

### What happens?

popup not blocked

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS
- Browser/version: Safari
- Adblock Extension/version: AdBlock Plus

### Other details:

![Captura de Pantalla 2020-09-09 a la(s) 07 44 02](https://user-images.githubusercontent.com/70922433/92589240-a9f6bc80-f270-11ea-95a6-b21272a6ee57.png)

**Comment by ryanbr** [comment]
seems fine here
