### ISSUE TITLE
pornhub.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#6044]
### List the website(s) you're having issues:

```https://es.pornhub.com/```

### What happens?

Mix of popup/popunder not blocked (when you click on a link, it opens in new tab but the original tab redirects to ad)

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS
- Browser/version: Safari
- Adblock Extension/version: AdBlock Plus

### Other details:

![Captura de Pantalla 2020-09-09 a la(s) 07 48 15](https://user-images.githubusercontent.com/70922433/92589508-035eeb80-f271-11ea-9c34-995e5e0ea0bb.png)
![Captura de Pantalla 2020-09-09 a la(s) 07 48 11](https://user-images.githubusercontent.com/70922433/92589515-0528af00-f271-11ea-9422-241c820fd2e6.png)

**Comment by ryanbr** [comment]
Can't fix properly, on going countering.
