### ISSUE TITLE
jkanime.net

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#6045]
### List the website(s) you're having issues:

```https://jkanime.net```

### What happens?

1) Ads not blocked
2) Content not showing (slideshow and video players). 

This only happens on Safari (both issues). Chrome is fine

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS
- Browser/version: Safari
- Adblock Extension/version: AdBlock Plus

### Other details:

![Captura de Pantalla 2020-09-09 a la(s) 07 55 03](https://user-images.githubusercontent.com/70922433/92590150-1cb46780-f272-11ea-8244-d8c6d19aac67.png)
![Captura de Pantalla 2020-09-09 a la(s) 07 54 17](https://user-images.githubusercontent.com/70922433/92590158-1faf5800-f272-11ea-915a-effeda20c75d.png)

**Comment by ryanbr** [comment]
Site is fine now.
