### ISSUE TITLE
nhentai.net

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#6046]
### List the website(s) you're having issues:

```https://nhentai.net/```

### What happens?

Popups not blocked

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS
- Browser/version: Safari
- Adblock Extension/version: AdBlock Plus

### Other details:

![Captura de Pantalla 2020-09-09 a la(s) 10 13 37](https://user-images.githubusercontent.com/70922433/92603217-6b1f3180-f285-11ea-8b4d-c49b49a6f5e5.png)
![Captura de Pantalla 2020-09-09 a la(s) 10 13 35](https://user-images.githubusercontent.com/70922433/92603223-6ce8f500-f285-11ea-9dbb-4dc238675a83.png)

**Comment by llacb47** [comment]
Are you trying to waste time with these reports? You are using ABP on safari macOS. 

ABP - least powerful adblocker

Safari - least powerful browser for adblocking https://www.zdnet.com/article/apple-neutered-ad-blockers-in-safari-but-unlike-chrome-users-didnt-say-a-thing/

**Comment by DandelionSprout** [comment]
That was pretty harshly said, although I too don't really enjoy the newest versions of Safari either.
