### ISSUE TITLE
gnula.nu

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#6047]
### List the website(s) you're having issues:

```http://gnula.nu```

### What happens?

Ads not blocked. Only on Safari

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS
- Browser/version: Safari
- Adblock Extension/version: AdBlock Plus

### Other details:

![Captura de Pantalla 2020-09-09 a la(s) 10 20 06](https://user-images.githubusercontent.com/70922433/92603845-2ba51500-f286-11ea-92e6-5d24046d00c5.png)

**Comment by ryanbr** [comment]
no longer needed
