### ISSUE TITLE
hanime.tv

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#6048]
### List the website(s) you're having issues:

```https://hanime.tv/videos/hentai/kanojo-ga-yatsu-ni-dakareta-hi-1```

### What happens?

Message that prevents videos from being watched when adblocker is used

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS
- Browser/version: Chrome and Safari, and every other browser
- Adblock Extension/version: AdBlock Plus

### Other details:

At first I was hesitant as to whether report it or not but then I noticed that the video is being played in the background. This message is just an overlay on the video player, like a picture. So blocking it should be fairly easy

![Captura de Pantalla 2020-09-09 a la(s) 10 22 34](https://user-images.githubusercontent.com/70922433/92604471-f0efac80-f286-11ea-8610-ba160ea5bed6.png)
![Captura de Pantalla 2020-09-09 a la(s) 10 22 12](https://user-images.githubusercontent.com/70922433/92604486-f3ea9d00-f286-11ea-8589-b70ca7022041.png)

**Comment by spirillen** [comment]
Hmm can't reproduce it, but found another "annoying" Adblock blocker

![image](https://user-images.githubusercontent.com/44526987/93004873-89b64e80-f54b-11ea-8393-8c90d9cb9c3f.png)

Seems like these rules causes it

```
||adtng.com^$3p
hanime.tv##iframe[src^="https://a.adtng.com/"]
```

**Comment by ryanbr** [comment]
Has been fixed, atleast not reproducable.
