### ISSUE TITLE
EasyList's "semi-generic popup block" breaks opening links in new foreground tabs in Firefox

### ISSUE THREAD

**Issue by zevelorgani** [easylist/easylist#6055]
Edited from the original submission as new information was found.

### List the website(s) you're having issues:

```
For example:
https://thepiratebay.org/search.php?q=category:100
```

### What happens?

Trying to open any link in a new tab immediately closes the opened tab.
If I disable EasyList, opening links in new tabs works as intended.

A similar issue happens when I go to `https://rarbg.to/index80.php` and try to open one of the links on the left (Music,, Games, etc.) in a new tab.  It only works if I uncheck EasyList in uBlock Origin.

### Analysis

**note:** uBO may be internally disabling that filter now (see comment below), so a different blocker may be needed to reproduce.

The problem is with the "semi-generic popup block" entry in the easylist_specific_block_popup.txt file.

According to https://github.com/uBlockOrigin/uAssets/issues/8123:
> The problem happens when browser.tabs.loadInBackground is set to false.
>
> Go to about:preferences#general
> Under "Tabs" check "When you open a link in a new tab, switch to it immediately"

### List Subscriptions you're using:

EasyList in uBlock Origin

### Your settings

- OS/version: Windows 10 1903
- Browser/version: FF 81.0b9 (64-bit)
- Adblock Extension/version: uBlock Origin v1.29.2

**Comment by DandelionSprout** [comment]
Sounds like a problem related to `$popup` entries, since auto-closing sudden tabs is what they usually do. Which of those entries that cause it, would be more difficult to figure out, however.

**Comment by zevelorgani** [comment]
> Which of those entries that cause it, would be more difficult to figure out, however.

easylist_specific_block_popup.txt line 22
```
/^https?:\/\/.*[&%+=]/$popup,domain=dood.to|dood.video|dood.watch|fcdn.stream|jawcloud.co|mixdrop.co|powvideo.net|powvldeo.cc|putlocker.fyi|putlocker.ninja|putlocker.style|putlockers.fm|putlockers.mn|putlockers.movie|rarbg.to|rarbgaccess.org|rarbgmirror.com|rarbgmirror.org|rarbgmirrored.org|rarbgproxy.org|rarbgprx.org|rarbgunblock.org|rarbgway.org|repelis.net|sbplay.one|seehd.pl|sendit.cloud|sendspace.com|sendvid.com|sportp2p.com|steamplay.cc|streamani.net|streamplay.to|streamtape.com|thepiratebay.org|thepiratebay10.org|torlock.com|torrentdownloads.me|torrentfunk2.com|uiz.io|up-load.io|upload.ac|uploadproper.com|uploadproper.net|upstream.to|uptobox.com|userscloud.com|vidbull.tv|videobin.co|vidlox.me|vidoza.co|vidoza.net|vidtomp3.com|vipbox.live|vipstand.se|vshare.eu|y2mate.com|yify-movies.net|youwatch.org|zippyshare.com
```

**Comment by zevelorgani** [comment]
Note: uBO currently disables this filter in https://github.com/uBlockOrigin/uAssets/commit/580a4e793c68599dd10899900583c7ba6c35c990

**Comment by zevelorgani** [comment]
Any news?

**Comment by ryanbr** [comment]
The filter was removed a while ago?
