### ISSUE TITLE
chip.de, focus.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#6067]
### List the website(s) you're having issues:

`https://www.chip.de/news/Smarter-Assistent-fuer-Ihr-Handy-Smart-Touch-Pro-wird-verschenkt_182982517.html`

`https://www.focus.de/politik/deutschland/in-tv-debatte-am-mittwochabend-publizistin-spottet-bei-maischberger-ueber-laschet-dann-bricht-gelaechter-aus_id_12440384.html`

### What happens?

i can’t play the video because the cookie banner is blocked. Its not possible to play the video without cookie accept.

### List Subscriptions you're using:

uBlock default with EasyList, EasyGermany and EasyList cookie

### Your settings

- OS/version: Win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin v1.29.2

**Comment by THEtomaso** [comment]
### Problem filters:
* EasyList Cookie List
* Fanboy's Annoyance List

### Problem rules:
`/gdpr/native-`
`/v1/gdpr/*`

### Possible fix:
`@@/gdpr/native-$domain=chip.de|focus.de`

### Other problem filters:
* **I don't care about cookies** (@kiboke)
`privacy-mgmt.com$domain=~ekstrabladet.dk|~manager-magazin.de|~spiegel.de|~vtm.be`

### Note:
**AdGuard Annoyances filter**, **AdGuard Base filter** and **Fanboy's Enhanced Tracking List** also contains several other whitelisting rules for these sites.

**Comment by BlazDT** [comment]
Fixed vtm.be for AdGuard. On ekstrabladet.dk the video works for me. Please check @AdamWr

**Comment by AdamWr** [comment]
I can't reproduce it, video works fine on `ekstrabladet.dk` on my end.
Also I can't find `||consent.dk^$third-party` in AdGuard Annoyances filter.

**Comment by THEtomaso** [comment]
> I can't find `||consent.dk^$third-party` in AdGuard Annoyances filter.

No, that one exists is in **EasyList Cookie List** / **Fanboy's Annoyance List**.
I simply listed them all together. Sorry 'bout that.
Like with so many other GDPR issues, reproducing the issue often depends on your location though.
**Frellwit's Swedish Filter** contains the same rule, but with an exception for `ekstrabladet.dk`.
..as you might recall, AdamWr:
https://github.com/AdguardTeam/AdguardFilters/issues/63408#issuecomment-688823713

Anyway, ryanbr has already closed this report, so perhaps you could fix the remaining issues @Khrin?

**Comment by AdamWr** [comment]
I checked it with Danish and Norwegian IP address and I couldn't reproduce it. I can't even find `.qc-cmp-ui-container` on these websites, so I guess that these rules can be removed anyway.

**Comment by THEtomaso** [comment]
Well, I connect from Norway, and it does pop up in uBO's logger at my end, whenever I visit the site!
Perhaps DandelionSprout: can confirm it, if he drops by soon.

**Comment by DandelionSprout** [comment]
I seem to be able to confirm that `||consent.dk^$third-party` breaks the video. The other two entries for `Ekstra Bladet` don't seem to be utilised according to the uBO logger.

**Comment by THEtomaso** [comment]
> The other two entries for `Ekstra Bladet` don't seem to be utilised according to the uBO logger.

That's weird.
Must somehow be browser-dependent then.
I use Pale Moon.

**Comment by THEtomaso** [comment]
I assume that the ramining issue(s) in this thread now have fallen deep into EasyList's abyss of unfixed problems.
Therefore, I've filed a new report for the issue @ `ekstrabladet.dk` here:
https://github.com/ryanbr/fanboy-adblock/issues/1410/

@DandelionSprout:
Meanwhile, could you add `@@||consent.dk^$third-party,domain=ekstrabladet.dk` to your Nordic filter, along with `dagbladet.no,elbil24.no#@#.subscription-box`, which I previously mentioned here?:
https://github.com/DandelionSprout/adfilt/issues/63/#issuecomment-691945929

**Comment by kiboke** [comment]
Thank you @THEtomaso both sites will work fine in the next IDCAC version.
