### ISSUE TITLE
vpn-anbieter-vergleich-test.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#6068]
### List the website(s) you're having issues:

`https://vpn-anbieter-vergleich-test.de/`

### What happens?

NordVPN ad overlay. When i close this a small popup open.
<img width="926" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/93482268-d27d5700-f8ff-11ea-9148-efc5cbd9d7c8.PNG">

Also a bunch of iframes get loaded
<img width="615" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/93486793-e24b6a00-f904-11ea-8b0c-89b14e54e6cf.PNG">

### List Subscriptions you're using:

uBlock default with EasyList, EasyGermany and EasyList cookie

### Your settings

- OS/version: Win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin v1.29.2

**Comment by spirillen** [comment]
what happens if you block `tawk.to` entirely??
```
||tawk.to$important
```

Cos this is what i see as they are completely blocked in [my dns](https://www.mypdns.org/T1233)

![image](https://user-images.githubusercontent.com/44526987/96387198-92302380-11a0-11eb-8203-64fd6e60d851.png)
