### ISSUE TITLE
cookpad.com

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/easylist#6069]
### List the website(s) you're having issues:

`https://cookpad.com/uk`

### What happens?

Cookie
![2020-09-17_192207](https://user-images.githubusercontent.com/57287308/93499502-c0a9ad00-f91b-11ea-8cc3-0c83deed9ae3.png)

### List Subscriptions you're using:

![2020-09-17_192514](https://user-images.githubusercontent.com/57287308/93499408-9f48c100-f91b-11ea-9203-1256707317fa.png)

- OS/version:  Win 8.1 x64
- Browser/version:  Opera|Stable
- Adblock Extension/version:  uBO 1.29.2

**Comment by krystian3w** [comment]
@DandelionSprout  second chance to fix with block some `xhr` / `script`.

**Comment by DandelionSprout** [comment]
The cookie banner seems to be loaded into any of the bottom 3 scripts, all of which break the site heavily if they're blocked. So I can only really recommend `cookpad.com##.webview__hidden[data-banner-cookie]` instead.

**Comment by krystian3w** [comment]
Maybe kiboke ban by generic:

`##div[data-id="cookie_dialog"]`

**Comment by P0Rtvine** [comment]
@ryanbr

**Comment by P0Rtvine** [comment]
@Khrin
