### ISSUE TITLE
[WEBSITE] Unable to log-in

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#607]
Hi, i recently registered on the website and i was messing around looking through all the themes. I selected the third one on the list and now i can't log-in to my account again. This is the CSS error: 

![](https://i.imgur.com/trzuquG.png)

**Comment by LanikSJ** [comment]
Depends on many things:

Adblocker?
Browser?
OS? 

For starters. Are you're blocking CloudFlare? I can go on ...

**Comment by FlaggedBrad** [comment]
I'm using adblock and ublock origin. It's not really an ad-blocking issue, more like an issue on the website. If you log into the website and try to edit your theme to the third one, you can't log-in anymore after that.

**Comment by LanikSJ** [comment]
You'd have to give me more info then that.  What theme?

**Comment by FlaggedBrad** [comment]
I don't know. I can't check...
