### ISSUE TITLE
Golem

### ISSUE THREAD

**Issue by Speciesx** [easylist/easylist#6070]
### List the website(s) you're having issues:

www.Golem.de
### What happens?

![golem de](https://user-images.githubusercontent.com/1196375/93513368-09666380-f926-11ea-9132-9a3f92d6fb42.png)

After clicking on this button nothing happens.

### List Subscriptions you're using:

![22](https://user-images.githubusercontent.com/1196375/93513332-fce20b00-f925-11ea-9ef3-4bdad220b789.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox nightly
- Adblock Extension/version: uBlock Origin 1.29.2 + Cookie AutoDelete

**Comment by THEtomaso** [comment]
The necessary fix was added to **AdGuard Annoyances filter** a few hours ago:
https://github.com/AdguardTeam/AdguardFilters/commit/0b21abd794c16a16a3084bea6ca0e293d3a1a283/

**Comment by krystian3w** [comment]
Whitelist no generate click in "Accept".

AdGuard in the past added clicker in blue button or cookie baked?
