### ISSUE TITLE
tube8.com [NSFW]

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#6078]
### List the website(s) you're having issues:

`https://www.tube8.com/`

### What happens?

Unblocked ads and placeholders

<details>

![tube8](https://user-images.githubusercontent.com/58900598/93795745-c8978300-fc74-11ea-86fb-26db837842a1.png)

</details>

### List Subscriptions you're using:

uBO default + AGJPN

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 80.0.1
- Adblock Extension/version: 1.29.2

**Comment by DandelionSprout** [comment]
My recommended entries to add to EasyList (along with example pages):
```
! https://www.tube8.com/amateur/12-hours-in-vacuum-bed-punishment-with-vibrator-epic-video/53129971/
tube8.com###pb_template
! https://www.tube8.com/searches.html?q=vacuum+bed
tube8.com###result_container_fake
tube8.com###result_container > div
tube8.com##div[data-esp-node="footer_ads_banner"]
```

**Comment by Yuki2718** [comment]
```
tube8.com###category_video_list > .gridList > div
tube8.com##div[data-esp-node=catfish]
```
for my SS. The first one may only appear if you move to the second or third page.

**Comment by Yuki2718** [comment]
The same rules are needed to `tube8.net` too.

**Comment by lain566** [comment]
I have updated the filters https://github.com/uBlockOrigin/uAssets/commit/a88df41c74a940efbd9b96cc56d88330fd2ec92f the site has changed, and the filters you added are no longer working @Yuki2718 
so these filters will not work either https://github.com/easylist/easylist/issues/6078#issuecomment-696346151

**Comment by Yuki2718** [comment]
@lain566 Yeah, confirmed. I hope this is not because they responded to the fix. Also `###footer-text` was kinda FP. Thx for fixing all :D

**Comment by lain566** [comment]
I had to remove this filter `tube8.*###footer-text` because it causes breakage.

If you add that filter and go to `https://www.tube8.com/categories.html`
the background turns black.

**Comment by Yuki2718** [comment]
I see, FP = false positive.
