### ISSUE TITLE
tvtropes.com

### ISSUE THREAD

**Issue by Drillimation** [easylist/easylist#6079]
### List the website(s) you're having issues:
`https://tvtropes.com/`

### What happens?
There are reports that TVTropes is blocking adblock again after ways to circumvent it worked for several months. It appears to be they started using a very aggressive form of anti-adblock that is extremely difficult to block. The site nags you to whitelist or "buy an ad removal pass" at a cost of $4/month or $20/year. Many users choose not to purchase one.

### List Subscriptions you're using:
ABP Filters + EasyList

### Your settings

- OS/version: Windows 10 64-Bit
- Browser/version: Version 85.0.4183.102
- Adblock Extension/version: AdBlock Plus 3.9.5

### Other details:
These filters below were the way to bypass the message:
`tvtropes.org##div:has(div:has(h2:has-text(without ads)))`

**Comment by llacb47** [comment]
https://github.com/easylist/easylist/issues?q=is%3Aissue+label%3AAnti-Adblock+is%3Aclosed

**Comment by Drflash55** [comment]
TVTropes still has a small issue even today.

I'm using Nano Adblocker + Nano Defender with EasyList, and it can detect that I am using an adblocker.
![image](https://user-images.githubusercontent.com/13694448/94375992-9c9d5700-00e5-11eb-8199-cd6416ff10c4.png)

**Comment by spirillen** [comment]
> "buy an ad removal pass" at a cost of $4/month or $20/year. 

That's actually not unfair prices for avoiding adware, it ain't free to hosts websites, and if you are a frequent user, I believe it's a fair tradeoff... and yep, fair usage of scam(ad)ware
