### ISSUE TITLE
http://www.actualtech.io/2017-acutaltech-media-audience-survey/

### ISSUE THREAD

**Issue by Myer** [easylist/easylist#608]
The static filter `##.gform_widget` in the Fanboy+Easylist-Merged Ultimate List blocks the download form on the right here: `http://www.actualtech.io/2017-acutaltech-media-audience-survey/`

**Comment by Myer** [comment]
Same here: `http://www.hyperconverged.org/2016-hci-report/`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4ca521dc082fb83d2d7cb38d67b1ff3a5e05653f
