### ISSUE TITLE
cricbeamer.com

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#6080]
### List the website(s) you're having issues:
```
https://cricbeamer.com/
https://cricbeamer.com/videos/watch-leg-stump-stands-upright-after-bowler-uproots-it-with/cid1307824.htm
```

### What happens?
Ads not blocked.

### List Subscriptions you're using:
Default uBlock Origin lists + AdGuard Base + AdGuard Tracking Protection + Fanboy’s Enhanced Tracking List + Spam404 + AdGuard Annoyances + Fanboy’s Annoyance + uBlock filters – Annoyances + Nano Defender Integration + Nano Filters

### Your settings
- OS/version: Windows 10 1909
- Browser/version: Chrome 85.0.4183.121
- Adblock Extension/version: uBlock Origin 1.29.2

### Other details:
Below filters block ads but layout of website becomes weird.
```
cricbeamer.com###btm-widget
cricbeamer.com##.colombiatracked
cricbeamer.com##div[data-section="home"] > div:has(span[name="adchoicehtml"])
```

**Comment by THEtomaso** [comment]
Unfortunately, `:upward` is not a ABP-compatible syntax.

Is this a viable alternative solution?:
`cricbeamer.com##.colombiatracked`
`cricbeamer.com#?#div:-abp-has(>a:-abp-contains(Gamezop))`

**Comment by cantunborn** [comment]
`cricbeamer.com#?#div:-abp-has(>a:-abp-contains(Gamezop))` does not work, but I have updated original comment with working filters.

**Comment by THEtomaso** [comment]
> `cricbeamer.com#?#div:-abp-has(>a:-abp-contains(Gamezop))` does not work,

It worked just fine for me.
..but AIUI, `-abp-` rules should be avoided, whenever possible, as they require slightly more resources.
So, your updated rules are indeed a better solution! :+1:
