### ISSUE TITLE
portaloswiatowy.pl

### ISSUE THREAD

**Issue by Barticf** [easylist/easylist#6084]
### List the website(s) you're having issues:
`portaloswiatowy.pl`

### What happens?
can't scroll

### List Subscriptions you're using:
Problem is with EasyList Cookie & AdGuard Annoyances

### Your settings

- OS/version: Win 10
- Browser/version: Firefox
- Adblock Extension/version: uBlock v1.29.2

**Comment by THEtomaso** [comment]
### Problem filters:
* **AdGuard Annoyances filter** (@BlazDT)
`##.overlay-cookie`
`##.popup-cookie`

* **EasyList Cookie List** / **Fanboy's Annoyance List** (@Khrin)
`##.container-cookie`
`##.cookie-btn`
`##.cookie-text`
`##.overlay-cookie`
`##.popup-cookie:not(body)`

* **I don't care about cookies** (@kiboke)
`##.container-cookie:not(body):not(html)`
`##.overlay-cookie:not(body):not(html)`
`##.popup-cookie:not(body):not(html)`

### Possible fix (for uBO):
`portaloswiatowy.pl##body:style(overflow: auto !important;)`

**Comment by BlazDT** [comment]
Fixed for AdGuard.

**Comment by kiboke** [comment]
A much more elegant fix is to just block the related cookie script (probably used on other websites as well).
`||wip.pl/js/cookie.js$script`

**Comment by BlazDT** [comment]
Some sites can get broken by url block rules ( talking in eneral). E.g. in some sites videos do not work when a cookie script is blocked.

**Comment by THEtomaso** [comment]
Yeah, but this particular site doesn't seem to have any videos.
But BlazDT has a point, @kiboke..
Perhaps you should at least make that blocking rule site-specific, like this?:
`||wip.pl/js/cookie.js$script,domain=portaloswiatowy.pl`

**Comment by kiboke** [comment]
I found the same script on wip.pl, portaloswiatowy.pl, agrodoradca24.pl, portalzp.pl, epedagogika.pl, portalbhp.pl - nothing broken on any of them because of it. I think it's safe to keep it as a general rule.
