### ISSUE TITLE
UltimateBundles.com

### ISSUE THREAD

**Issue by ubadmin** [easylist/easylist#6093]
### List the website(s) you're having issues:

```
https://click.convertkit-mail4.com/o8u67qdzd5aqhx568rcv/g3hnh5hzv48rqzfr/aHR0cHM6Ly91bHRpbWF0ZWJ1bmRsZXMuY29tL3NhbGUvdGdidGsyMDIwLW1haW4_YV9haWQ9NWI5MDM1NDBkNzIxMyZhX2JpZD1lMDUxZGQ4MA==

https://ultimatebundles.com/sale/tgbtk2020-main/?a_aid=5b903540d7213&a_bid=e051dd80
```

### What happens?

when using adblock plus and trying to click the links in gmail it opens the tab and immediately closes the tab

### List Subscriptions you're using:

adblock plus

### Your settings

- OS/version: OSX catalina (also happens on windows/linux)
- Browser/version: Firefox 80.0.1
- Adblock Extension/version: Adblock Plus 3.9.5

### Other details:

I noticed that if the link does not have the second query parameter it doesn't always trigger
This triggers:
`http://ultimatebundles.com/sale/tgbtk2020-main/?a_aid=2309&b_bid=dskweoicn`
This doesn't:
`http://ultimatebundles.com/sale/tgbtk2020-main/?a_aid=2309`

We have thousands of legitimate affiliates that promote using this style of link, so it has become a real issue on our end - Thank you!

**Comment by DandelionSprout** [comment]
Although I can't seem to find the source entries in EasyList that cause the auto-closing behaviour, I know that it's very typical of list entries that have `$popup` in them.
