### ISSUE TITLE
easylist blocks pusherjs unnecessarily

### ISSUE THREAD

**Issue by shash7** [easylist/easylist#6097]
https://pusher.com

### List the website(s) you're having issues:
app.underlineme.com
(I work on this site)

### What happens?
I use a service called pusher to serve realtime push notifications to my dashboard. This service is used for business critical stuff such as updating application state when it changes on connected devices. Since this morning, uBlock has been blocking pusher and therefore my service doesn't run properly when my users have uBlock installed(I've installed it too)

This is due to the `||pusher.com^$third-party` inside easyprivacy_trackingservers.txt

### List Subscriptions you're using:
I'm using uBlock Origin

### Your settings
All default settings. I even refreshed the cache and the issue persists.

- OS/version: Windows 10
- Browser/version: Chrome 85.0.4183.121
- Adblock Extension/version:  uBlock Origin 1.29.2

### Other details:
N/A

Let me know if you need anything from me(screenshots, console logs, etc)

**Comment by ryanbr** [comment]
Due to privacy issues related to `pusher.com` it was blocked.

https://github.com/easylist/easylist/commit/991daf48638f9b38aa3ef6eaed074a919a20fccf

> Blocked due to useragent checks/localstorage/polling.

**Comment by shash7** [comment]
But why block the enter domain? As I understand, you only block specific domains which track users. But blocking an entire domain seems very heavy handed.

Not to mention it breaks every service dependent on that website.

**Comment by ryanbr** [comment]
> But why block the enter domain? As I understand, you only block specific domains which track users. But blocking an entire domain seems very heavy handed

Because its the same code shared on all sites. Making it site-specific makes no sense if its tracking on all domains.

If you value privacy, there is no reason to use 3rd-party notification servers.

**Comment by EntropyAu** [comment]
Similar concern here - we operate an online meeting app that uses Pusher Channels for real-time data sync between users. I hope Pusher can address the concerns raised here (I've filed a ticket with them). I'm aware stats.pusher.com has been blocked for a while, that seems reasonable.

**Comment by shash7** [comment]
> > But why block the enter domain? As I understand, you only block specific domains which track users. But blocking an entire domain seems very heavy handed
> 
> Because its the same code shared on all sites. Making it site-specific makes no sense if its tracking on all domains.

I mean selective block domains. For instance, before your commit stats.pusher.com was blocked.

> If you value privacy, there is no reason to use 3rd-party notification servers.

This isn't a notification system. This service is used in business critical stuff. When people pay to use my service because real-time sync was advertised as a feature and it doesn't work as advertised, all blame is on me. Tell me what alternatives should I pursue?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/47299e9  adjusted. But from what I've seen stats.pusher.com isn't active used

https://publicwww.com/websites/%22stats.pusher.com%22/

**Comment by shash7** [comment]
Sweet, its working now.

Moving forwards, please consider that blocking full domains disable services that rely on that domain and they will in turn  disable other services resulting in a jenga effect. The last 24 hours have been hectic to say the least.

**Comment by ben-pusher** [comment]
The change made only resolves the issue for certain installations, and there are still some users impacted. See the linked issue for further details.

**Comment by joadr** [comment]
We are an exchange and we are having massive complaints. We use pusher for updating trading information such as trades, orderbook changes and market data. This block is blocking legit businesses, please remove it!

**Comment by spirillen** [comment]
> We are an exchange and we are having massive complaints. We use pusher for updating trading information such as trades, orderbook changes and market data. This block is blocking legit businesses, please remove it!

Legit business doesn't relay on third-partys, they serve there own code.

**Comment by joadr** [comment]
> Legit business doesn't relay on third-partys, they serve there own code.

New rule for the internet? So... We cannot rely on third-party CDN? we cannot rely on libraries hosted by our service providers? We cannot rely on third-party servers? so no cloud for legit businesses. We should have our system on a PC in the corner of the room? Stop being a clown, we are having a serious discussion here. If you are not going to add value, give us a favor and don't comment.

**Comment by llacb47** [comment]
Ignore @spirillen he is a troll who doesn't understand how the internet works.

**Comment by gileswells** [comment]
> Ignore @spirillen he is a troll who doesn't understand how the internet works.

@llacb47 Troll or not, he's a contributor to this repository and has authority on what gets accepted/fixed or not. You get more with honey than vinegar and the fastest way to get an issue closed and locked is to insult the person you're hoping to reason with. 

All that being said @spirillen I don't believe that your argument is a valid one and I'd like to have a discussion about it. There are loads of businesses that just don't have the capital to invest to create a platform such as this one. It's the same reason someone might start with an html/css template for their website and customize from there. The base cost of the template plus the time to modify it to fit your needs is much lower in most cases than creating something from the ground up. Its the exact same premise with something like Pusher or other real time service providers. They have the infrastructure and code libraries to handle this sort of thing for fractions of a percent of what it would cost for a new business to build it on their own.

Please reconsider removing pusher and others for that matter from the below file.

https://github.com/easylist/easylist/blob/991daf48638f9b38aa3ef6eaed074a919a20fccf/fanboy-addon/fanboy_notifications_thirdparty.txt#L134

**Comment by llacb47** [comment]
spirillen is not a member of easylist and has no say regarding the content of easylist/easyprivacy.

**Comment by gileswells** [comment]
Sorry. I saw the contributor tag on his name and forgot that can literally mean he's contributed 1 line of code at some point. That always trips me up.

**Comment by spirillen** [comment]
I like it when people don't know what they are talking about...


![image](https://user-images.githubusercontent.com/44526987/96325619-76eed800-1029-11eb-84f9-60669bb06f8a.png)

There are only 4 people in this project who decides what is going into the list, everybody else are free to give there opinion and suggestions.

Troll?? hmm nope, I'm only 6'1'' high. Are you a troll if you use your democratic right to spread your opinion? versus a certain person in this thread, I never say anything bad about any one, I only speaks of the topic in question from _my_ point of view. Because I happens to disagree with someone i don't troll them :arrow_double_up: But trust me, you are getting very close to a complain to GH for your behavior.

> who doesn't understand how the internet works.

Oh yes i do, I also happens to remember what the idea was with it from the beginning and how it should suppose to be working... Free open democratic information sharing for spreading democracy and knowledge without any user tracking / spamming. Yes I'm very much against the anti-democratic way the internet have turned out.

<details></summary>The long list</summary>

![image](https://user-images.githubusercontent.com/44526987/96325608-6a6a7f80-1029-11eb-9b37-b25cb1ca4e4e.png)

</details>

Without to start a discussion, as I at the end don't care...

`pusher` is it used for pushing information's like needed information's from a reservation, yes that is a legit purpose
`pusher` Pushing spam/scam aka "message" = INVALID usage and most die.
