### ISSUE TITLE
uptomega.me

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6100]
### List the website(s) you're having issues:

`https://uptomega.me/j3jf8krrtn4l`

### What happens?

Ads in bottom of page

![IMG_20200930_094533](https://user-images.githubusercontent.com/20338483/94642449-c0d57f80-0301-11eb-9736-c973274ac148.jpg)

### List Subscriptions you're using:

Ublock origin default lists

### Your settings

- OS/version: android
- Browser/version: firefox 80
- Adblock Extension/version: ublock origin 1.30

### Other details:

Add this

`||kkzzmljoaloc.com^`
`||unskilledsqueakjunk.com^`
`||ninecovetous.com^`
`||socialbars-web2.com^`

**Comment by ryanbr** [comment]
Is fixed in Easylist, just force an update.
