### ISSUE TITLE
nationalpost.com

### ISSUE THREAD

**Issue by tisdall** [easylist/easylist#6103]
### List the website(s) you're having issues:
```
https://nationalpost.com/ https://financialpost.com/ https://torontosun.com/ etc 

All Postmedia sites load a JS module from https://d395dw5zk780j2.cloudfront.net/v17.0/fem.js that is being blocked
```

### What happens?
All Postmedia sites fail to load the `fem.js` file which is responsible for incorporating multiple third-party functionalities.  This includes things already blocked such as ad calls and analytics, but also calls to single sign-on and commenting on stories.  This prevents regular users from commenting on stories (ex `https://www.reddit.com/r/uBlockOrigin/comments/hpbft5/national_post_yet_again/`) or accessing subscriptions.

### List Subscriptions you're using:

I came here due to this line: https://github.com/easylist/easylist/blob/164b0c4541a24a5432439fd3a886f687d25a90f5/easylist/easylist_thirdparty.txt#L1772

It seems that the same rule was already removed from EasyPrivacy here: https://github.com/easylist/easylist/commit/af05b3a735e83b75657885fb31d3b01c51289d60

I'm not currently using an ad blocker.

### Your settings

I'm not using an ad blocker.

### Other details:

I work for Postmedia.  I believe `fem.js` is safe to unblock as any functionality that a blocker would want to block is already blocked by blocking the third-party JS (ie Google Ad Manager, Google Analytics, MParticle, Google Tag Manager, etc.).  With `fem.js` blocked, the comments and sign in are broken.

**Comment by ryanbr** [comment]
Removed, though every picture on the site was blurred even with adblock disabled.. Is this intentional?

![blurred](https://user-images.githubusercontent.com/1659004/94761251-0af15a80-0401-11eb-9673-1fec40bec72b.png)

**Comment by tisdall** [comment]
hmm.. the images are lazy-loaded via JavaScript so I'm guessing something else is also broken.  There seems to be a CORS issue that's intermittent when loading the JavaScript so it may be that. Thanks for pointing it out.

Thanks for removing the listing from Easylist!
