### ISSUE TITLE
mabanque.bnpparibas is unusable with the EasyList cookie filter

### ISSUE THREAD

**Issue by Sosthene-Guedon** [easylist/easylist#6110]
### Website of the issue

`https://mabanque.bnpparibas/`

### What happens?

There is a modal that requires the user to accept cookies, the list blocks the modal, however, however the whole page is dimmed and the user can't click anywhere.

After some testing by disabling various filter lists, I managed to pinpoint the issue to the `EasyList cookie` list I use in uBlock Origin.

### List Subscriptions you're using:

EasyList Cookie

#### The webstie without the EasyList cookie filter list:
uBlock Origin with cosmetic filters enabled

- OS/version: Arch Linux
- Browser/version: firefox-develloper-edition v82
- Adblock Extension/version:  uBlock Origin v1.30.0

### Other details:

The issue was present on a clean profile with no other extensions installed.

#### The webstie without the EasyList cookie filter list:

![ModalShown](https://user-images.githubusercontent.com/51865119/94925287-418daa80-04bf-11eb-85e8-83bc76aac96a.png)

After accepting the cookies (notice that the website isn't dimmed anymore):

![ModalAccepted](https://user-images.githubusercontent.com/51865119/94925468-8dd8ea80-04bf-11eb-89ed-77d81df60fa2.png)

#### The webstie with the EasyList cookie filter list:

![ModalHidden](https://user-images.githubusercontent.com/51865119/94925290-42264100-04bf-11eb-84e4-4905b7549542.png)

**Comment by krystian3w** [comment]
`###nextoutils_gestionCookies`
`###cookiesPopin`
`###nextoutils_gestionCookies ~ .popin-cache`
