### ISSUE TITLE
Make this repo Hacktoberfest-compatible according to its new rules

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6114]
### List the website(s) you're having issues:

`https://hacktoberfest.digitalocean.com/profile`

### What happens?

In the past 3-ish years, the Hacktoberfest has been an event where GitHub and DigitalOcean got together to nominally celebrate open-source and its contributors from all walks of life, though in practice it has been a giveaway of free T-shirts and stickers to the ~75,000 first GitHub users to submit 4 PRs to almost any repo.

However, Hacktoberfest in 2020 has been a colossal mess of proportions, with its rules being changed *twice* mid-event in the past 4 days, the most recent of which stipulated that PRs did not count towards the user's tally unless 1) the GitHub repo was tagged with `hacktoberfest`, or 2) every single pull request until mid-November that did not seem like spam was labelled by the repo owners with `hacktoberfest-approved`, as per https://hacktoberfest.digitalocean.com/hacktoberfest-update

So if we as an adblocker community were to want to give contributors the chance to win free T-shirts, either of the 2 approaches above would have to be implemented by you guys. №1 would take ~20sec, presuming we find it to be worth the effort to continue to support Hacktoberfest after these very huge changes they've done now.

### List Subscriptions you're using:

N/A

### Your settings

- OS/version: Windows 10 May 2020 Update
- Browser/version: Chrome 85.0.4183.121 x64
- Adblock Extension/version: uBlock Origin 1.30.1b5 + uBlock Origin Extra 2.88 + IDCAC 3.2.2

### Other details:

I mostly only need the T-shirt reward so I can give it as an annual holiday gift to one of my siblings. I've never wanted to use branded T-shits with words on them myself.

**Comment by ryanbr** [comment]
So other than tshirts..   Also https://blog.domenic.me/hacktoberfest/

**Comment by DandelionSprout** [comment]
Okay, so in the past couple days I have indeed realised *why* Hacktoberfest 2020 had such abrupt rule changes. It took a Twitter comedy account for me to realise it (`https://twitter.com/shitoberfest`).

Considering [my own list repo](https://github.com/DandelionSprout/adfilt) is pretty much permanently desiring new contributors and list entries, and would've welcomed Hacktoberfest with open arms, it took me by surprise around the 7th how many PRs that were made to various repos out there that'd fail to reach the very low quality requirements for even *my* repo.

**Comment by ryanbr** [comment]
We'll skip this
