### ISSUE TITLE
Fanboy_Notifications Pusher.com Block

### ISSUE THREAD

**Issue by ben-pusher** [easylist/easylist#6115]
### List the website(s) you're having issues:

`Pusher.com`

### What happens?

The entire `pusher.com` domain is blocked in the fanboy_notifications_thirdparty list. Could this be updated to `*pushnotifications.pusher.com`? This is the subdomain that publishes notifications, blocking the entire domain causes issues with the Pusher Channels product which is separate and doesn't use Push Notifications

### List Subscriptions you're using:

fanboy_notifications_thirdparty

### Other details:
As my name suggests, I work for Pusher - however we have had customers report issues with sites that don't use Push Notifications due to this filter policy.

**Comment by spirillen** [comment]
When we are at it it might be useful to apply this whitelist rule as well for travis

```
@@||pusher.com^$xhr,domain=travis-ci.com
```

https://github.com/spirillen/ublockorigin-rules/commit/e924a762f38078ec14571d93c4531814aaeaff82#diff-c1d24de01658dabfae30f7626f1cd03bR24

**Comment by ben-pusher** [comment]
The whitelist wouldn't be required if the suggested change from `pusher.com` to `pushnotifications.pusher.com` is implemented.
