### ISSUE TITLE
EasyPrivacy: False positive `/api/metrics`

### ISSUE THREAD

**Issue by joschi** [easylist/easylist#6120]
### List the website(s) you're having issues:

Internal business website (non-public URL), let's call it https://example.com

### What happens?

Our business portal is displaying internal metrics on dashboards.

The data for these metrics is being fetched from an HTTP resource via HTTP POST, but since cdc25d57e443f54706a37e57480720d4e1396cfa the requests to the backend at https://example.com/api/metrics are being blocked when using the EasyPrivacy list.

```
# curl -s https://easylist.to/easylist/easyprivacy.txt | grep -E 'Version:|api.metrics'
! Version: 202010080915
/api/metrics$other
/api/metrics|
||google.com/support/webmasters/api/metrics?$script
||healthline.com/api/metrics
```

### List Subscriptions you're using:

EasyPrivacy - https://easylist.to/easylist/easyprivacy.txt

Version: 202010080915

### Other details:

URL path `/api/metrics` was introduced in cdc25d57e443f54706a37e57480720d4e1396cfa.
This issue is similar to the closed issue #3482.

**Comment by ryanbr** [comment]
Okay, made specific

**Comment by markussen145** [comment]
Since a moment ago, more or less the time gone since this issue was closed, many websites stopped working for me withh EasyPrivacy enabled (ie: youtube).
