### ISSUE TITLE
EasyPrivacy breaking nearly every website

### ISSUE THREAD

**Issue by RashadAhmed1** [easylist/easylist#6123]
### List the website(s) you're having issues:

`youtube.com`
`twitter.com`
`reddit.com`

### What happens?

When the EasyPrivacy filter list is enabled, nearly every website is broken with various issues, such as missing CSS, certain content not loading, some sites not loading at all. Disabling the EasyPrivacy list fixes this issue immediately. 

### List Subscriptions you're using:

EasyList
EasyPrivacy
Fanboy's Social Blocking List
ABP Filters

### Your settings

- Windows 10
- Chrome 86
- I have tested this on a clean browser install with only the ABP extension installed and EasyPrivacy enabled and the issue still occurs.

**Comment by vjanssens** [comment]
I can confirm this is the case, once EasyPrivacy is disabled they all start working again.

**Comment by ryanbr** [comment]
Which filter is shown to cause it?

**Comment by dimisa-RUAdList** [comment]
@Khrin 
The consequences of this error are dire and will haunt users for hours. This could have been avoided if [this](https://gitlab.com/eyeo/adblockplus/adblockpluscore/-/issues/238) had been implemented. Then it would be enough to add `n$badfilter` to abp-filters-anti-cv and in an hour the correction would reach users.

**Comment by hfiguiere** [comment]
> @Khrin
> The consequences of this error are dire and will haunt users for hours. This could have been avoided if [this](https://gitlab.com/eyeo/adblockplus/adblockpluscore/-/issues/238) had been implemented. Then it would be enough to add `n$badfilter` to abp-filters-anti-cv and in an hour the correction would reach users.

How would it have been avoided with `$badfilter`? It merely would have provided an override mechanism.

**Comment by dimisa-RUAdList** [comment]
And there is. But this cancellation would have worked almost immediately. Now we are waiting for the current changes to reach users - `EasyPrivacy ... ! Expires: 4 days (update frequency)`

**Comment by krystian3w** [comment]
What **default** have `Expires: 1 hour` or `Expires: 10 minutes`?

Besides, will you add the denial of the entire human alphabet as a one-character character to each list?

**Comment by dimisa-RUAdList** [comment]
I see no reason for sarcasm here. We are talking only about the prompt correction of this particular error. Obviously, `n$badfilter` would only override `n` rule. And if placed in abp-filters-anti-cv (temporarily), it would reach users not in 4 days, but in one hour. Yes, it would only help ABP-users, but this is not a little.

**Comment by hfiguiere** [comment]
The problem here is that `u` is a valid filter and wreaked havoc.

**Comment by dimisa-RUAdList** [comment]
The problem can be created by absolutely any, absolutely valid (in all respects) filter that worked properly before. For example, when there are changes on the resource itself. In this case, adding such a filter, with the badfilter option, in abp-filters-anti-cv, will allow neutralizing user breakdowns within an hour.

**Comment by vjanssens** [comment]
I'm not involved in this project, but I did have the same issue. I can't imagine this change has been properly tested, nearly every website I visited stopped working. Would it be possible to create a test-suite that opens the top 20 websites in the world to see if they still work with latest changes?

**Comment by Dragodraki** [comment]
I would like to report that lots of issues with EasyPrivacy still exists - see issue nr. #2376
Would be great if developers can debug this list one more time to eliminate them
