### ISSUE TITLE
analytics.amplitude.com

### ISSUE THREAD

**Issue by rctbusk** [easylist/easylist#6128]
### List the website(s) you're having issues:
`analytics.amplitude.com`

### What happens?

Our site, analytics.amplitude.com, is having our APIs blocked because of a [rule in the EasyPrivacy list](https://github.com/easylist/easylist/blob/9d3e363c992d945013407fb6c001e1a581a497bf/easyprivacy/easyprivacy_general.txt#L645). This rule was updated 7 days ago so our apis such as `https://analytics.amplitude.com/event` are now getting blocked when users have EasyPrivacy enabled with their ad-blocker. 

This site does not serve any ads. It does not try to get around any ad-blockers either. I think this is an erroneous side affect of trying to block other sites. Could our site be added as an exclusion for this rule. We want our customers to still be able to have EasyPrivacy turned on and also have our site be fully functional. 

### List Subscriptions you're using:
Adblock with EasyPrivacy enabled.

### Your settings

- OS/version: macOs Catalina 10.15.7
- Browser/version: Google Chrome - Version 85.0.4183.121
- Adblock Extension/version: Adblock Version 4.22.1 + EasyPrivacy option turned on.

### Other details:
I suspect these apis are now being blocked from the [`://analytics.*/event`](https://github.com/easylist/easylist/blob/9d3e363c992d945013407fb6c001e1a581a497bf/easyprivacy/easyprivacy_general.txt#L645) filter in the EasyPrivacy list. Everything works fine with EasyPrivacy turned off.

**Comment by ryanbr** [comment]
We're not implying you're serving ads, we're just blocking analytics requests. Easyprivacy is a anti-tracking list, which seems fine in this case? @rctbusk

**Comment by rctbusk** [comment]
We are not using this api's for tracking our users either. These are all get requests trying to load data to populate the users charts and tables.

**Comment by ryanbr** [comment]
The most we'll do is this:

`@@||analytics.amplitude.com^$~third-party`

**Comment by rctbusk** [comment]
And this will allow our APIs to run on our own web app?

Sorry not completely familiar with how these lists work.

**Comment by ryanbr** [comment]
It'll allow this on your own site, but no third party sites

**Comment by rctbusk** [comment]
Perfect. That's great. Thanks
