### ISSUE TITLE
Facebook scrolling not possible

### ISSUE THREAD

**Issue by johastl** [easylist/easylist#6129]
### List the website(s) you're having issues:

Basically all Facebook pages, for example:
`https://www.facebook.com/cnnpolitics`
`https://www.facebook.com/bbcnews`

### What happens?

Scrolling not possible!

### List Subscriptions you're using:

- EasyList Cookie
- Adguard Annoyances
(and others ...)

### Your settings

No settings issue as removing the mentioned lines works fine.

- OS/version: Win7 (patch level 2020-09)
- Browser/version: Firefox latest version
- Adblock Extension/version: uBlock Origin v1.30.2

### Other details:

Narrowed it down to:
'EasyList Cookie':
`##div[data-testid="cookie-policy-banner"]`
`facebook.com##[data-testid="cookie-policy-banner"]`
but also:
'Adguard Annoyances'
`facebook.com#$#div[data-testid="cookie-policy-banner"] { display: none !important; }`

**Comment by krystian3w** [comment]
@THEtomaso

**Comment by krystian3w** [comment]
https://github.com/DandelionSprout/adfilt/issues/63#

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/63062

**Comment by flesti** [comment]
Until it gets fixed I added 2 exemptions in my filters tab  as a workaround 

```
facebook.com#@#div[data-testid="cookie-policy-banner"]
facebook.com#@#[data-testid="cookie-policy-banner"]
```

**Comment by krystian3w** [comment]
Nope, also needed is:

```
facebook.com#@$#div[data-testid="cookie-policy-banner"] { display: none !important; }
```

for AdGuard apps/extensions

**Comment by johastl** [comment]
I added these lines to my 'My filters' list because I have them in more than one filter
and it works fine so far!
Thanks flesti and krystian3w!

**Comment by peace2000** [comment]
I use Ubo and Firefox but I don't have any issues with this filter.

**Comment by krystian3w** [comment]
Need logout and try scroll fanpages

**Comment by peace2000** [comment]
I don't have that addon.

I cleared everything and tried with and without private browsing mode and logged in both times without any issues and scroll works perfectly on those pages.

I use:
uBlock Origin v1.33.2
Firefox 85.0

**Comment by peace2000** [comment]
![kuva](https://user-images.githubusercontent.com/17256841/106899901-9572ff00-66fe-11eb-88a4-66d986bcbe08.png)

![kuva](https://user-images.githubusercontent.com/17256841/106899938-9f94fd80-66fe-11eb-8cf5-ad501ebd565c.png)

**Comment by krystian3w** [comment]
Strange, really I must record MP4/GIF?

**Comment by peace2000** [comment]
Now I can reproduce this if I'm using the page as a guest.

If I log in, then it works fine.

**Comment by krystian3w** [comment]
Logged users no  have loaded cookies pop-up (something like logged = you accepted cookies policy).

**Comment by peace2000** [comment]
I would go by using this rule:

_facebook.com##body.fbIndex.UIPage_LoggedOut.hasBanner div[data-testid="cookie-policy-banner"]_

This rule blocks the banner in the login page but does not block the banner if fan pages are being browsed.

**Comment by johastl** [comment]
@peace2000:
Unfortunately, this doesn't work for me.
I don't have a Facebook account, so I do not log in.

And for example I open pages like this:
https://www.facebook.com/pg/Motorhead-Fan-Page-188921241129818/posts/
but I have the same issue on official pages like
https://www.facebook.com/cnn

What works best for me so far is to use these two lines in my filters (both!):
'facebook.com#@#div[data-testid="cookie-policy-banner"]'
'facebook.com#@#[data-testid="cookie-policy-banner"]'
(I have to accept the cookie banner, but it blocks the other crap on FB and still it's what works best for me ...)

**Comment by peace2000** [comment]
@johastl Yeah my point was to provide a solution that would fit to Easylist (to block that banner at least on the login page). There isn't afaik a way to block that banner on fan pages without breaking scroll function by using standard cosmetic filter rules.

Though it's possible to fix this in Ubo.

`facebook.com##^script:has-text(cookie-policy-banner)`

That will remove the banner without breaking scrolling. Works at least to me. :D

**Comment by krystian3w** [comment]
CSS for uBO - Chromium:

```css
facebook.com##.hasCookieBanner > div[class][style]:nth-child(2):nth-of-type(1):style(position: static !important;)
```

**Comment by krystian3w** [comment]
I suppose fixed by these combinations:

https://github.com/easylist/easylist/commit/38402b35fdddf611171881d6bd1c0e4cd77bdd7a
https://github.com/easylist/easylist/commit/12ea5f4ecad4c067a71c97015121e70de459f0f7

**Comment by peace2000** [comment]
I noticed realized now that my previous script rule causes issues sometimes, you'll have to login twice.

Also it seems that Easylist Cookie doesn't hide that banner anymore.

Anyway, I found now a good rule:

`facebook.com##body:not([style^="margin-bottom"]) div[data-testid="cookie-policy-banner"]`

This rule hides the banner on login page and on the checkpoint page during login process but does not hide the banner on fan pages. I reopened my pull request with little modifications. https://github.com/easylist/easylist/pull/7158

**Comment by johastl** [comment]
Works fine for me.
And I can tell no difference to using these two:
´facebook.com#@#div[data-testid="cookie-policy-banner"]´
´facebook.com#@#[data-testid="cookie-policy-banner"]´

Even comments are visible (which was not the case for one of the previous suggestions here.)
So, I think I go with this one and test.

Thanks!

**Comment by bug-rules** [comment]
New ID `data-testid="cookie-policy-dialog"` for guests.

After logon classes is randomized / compressed.

**Comment by johastl** [comment]
Thanks bug-rules!
`facebook.com#@#div[data-testid="cookie-policy-dialog"]` currently does the trick for me.
