### ISSUE TITLE
Block coin-hive.com script - CPU miner

### ISSUE THREAD

**Issue by RikoDEV** [easylist/easylist#613]
Some sites have implemented a script for digging bitcoins using cpu. 

**Script**: http://coin-hive.com/lib/coinhive.min.js

**Comment by ryh** [comment]
Please use `coin-hive.com/lib/*` 
becasue `https`  protocol and `captcha.js` is also mining

**Comment by Khrin** [comment]
I don't think that can be considered as "advertisement"...
