### ISSUE TITLE
imgur.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#6142]
Google Chrome 86.0.4240.75
ABP 3.9.5
ABP filters
EasyList
EasyPrivacy

`https://imgur.com/upload`

`/px.js?ch=$script` **EasyPrivacy**  > adblock detected

[screen](https://i.imgur.com/YtPVbdB.jpg)

Also: https://forums.lanik.us/viewtopic.php?f=64&t=45239

**Comment by ryanbr** [comment]
Has been fixed, closing.
