### ISSUE TITLE
wangdalao.com(fanboy social list)

### ISSUE THREAD

**Issue by cjx82630** [easylist/easylist#6152]
### List the website(s) you're having issues:
https://diaoge.cn/sslv2v3-tlsv1
https://www.iqshv.com/
https://www.tiaomaren.com/
https://wangdalao.com/3592.html
https://www.wc1234.cn/
https://ygodl.com/

### What happens?
It seems that these websites all use the same website template. The body of the template is named `.social-top`  which was hidden by fanboy social list

### List Subscriptions you're using:
fanboy social list
EL china +EL

### Your settings

- OS/version: win 10
- Browser/version:  chrome 80
- Adblock Extension/version:  ABP

**Comment by Khrin** [comment]
It's an exhaustive list or do you know other sites where this filter is causing issues?

**Comment by ryanbr** [comment]
This should help

https://github.com/easylist/easylist/commit/7370491ccb37a13c3674463e8346e5b9658e9712
