### ISSUE TITLE
eBay "Sponsored" listings are not hidden anymore

### ISSUE THREAD

**Issue by starbuck93** [easylist/easylist#6157]
https://github.com/easylist/easylist/blob/04c564a2e7aa3b87aeca32313d978f4342c10108/easylist/easylist_specific_hide.txt#L5437

need to replace this line with
`ebay.com##li.s-item:has(span[class^="s-item__title--tagblock__SPONSORED"])`

**Comment by starbuck93** [comment]
#6158

**Comment by tinychimp** [comment]
These are not ads, but sellers promoting their items at a fee. I think that is a major distinction.

**Comment by ryanbr** [comment]
Okay added

**Comment by starbuck93** [comment]
Following up on this... It appears eBay has changed things again. Here's a regex filter for removing sponsored listings.

`##li.s-item:has(span:has-text(/(?!Sponsored)[Ss].*[Pp].*[Oo].*[Nn].*[Ss].*[Oo].*[Rr].*[Ee].*[Dd]/))`

The current method of removing sponsored listings does not appear to work (again):
 https://github.com/easylist/easylist/blob/04c564a2e7aa3b87aeca32313d978f4342c10108/easylist/easylist_specific_hide.txt#L5437

They've added the hidden text "Sponsored" to every listing now, so first you have to ignore all of those with `(?!Sponsored)`

Then, the actual Sponsored listings have random hidden characters in-between the word Sponsored, [like this](https://regex101.com/r/ii5WsW/1).

If a PR is welcome on this issue, I'll happily do that.
