### ISSUE TITLE
shofda.com is not an ad agency or serves anti block ads

### ISSUE THREAD

**Issue by thatMohamed** [easylist/easylist#6161]
Hi
I think shofda.com in the easylist is on the list by mistake, we don't serve any anti block ads or anything, we are working with propellerads, like many others, for years and they are very reputable ad agency that don't serve any malicious content.

please reveiw shofda.com and remove it

**Comment by spirillen** [comment]
all scam/ads are malicious

**Comment by thatMohamed** [comment]
Even if, you don't block a domain, you just block the ads, I can give you 10 domains on the top of my mind right now that are displaying malicious ads and your easylist is doing a great job of blocking these ads, but you don't block the domain itself
guys, we are NOT an ad agency, we are NOT intermediary, we are just another ad publisher like other million website out there.

We are using Propellerads which is again, very reputable, they don't disrepute any malicious ads as far as we know
We don't use any kind of anti ad-block scripts, we don't force any visitors to see the ads

@ryanbr please review it again and if you suspected that we are using any harmful tactic or script, or any harmful ad agency we are fine with the our domain being in the list, but if not, please remove it.
