### ISSUE TITLE
https://www.ebay.com/ listing images not loading

### ISSUE THREAD

**Issue by tinychimp** [easylist/easylist#6165]
### List the website(s) you're having issues: 
`https://www.ebay.com/sch/tayst58/m.html`

### What happens?

Images after the first 20 do not load when using ad blockers. See similar complaints here - https://github.com/uBlockOrigin/uAssets/issues/8029

### Your settings

- OS/version: Mac OSX
- Browser/version: uBlockOrigin
- Adblock Extension/version: 1.29.2

### Other details:

This recent addition seems to be the root cause: https://github.com/easylist/easylist/commit/b1e583eec67a6349de560680d6f78812115883e9#diff-cb9a06d53e4d1d30a958e88af6e35c9b4b49fde823cc47dc2c151ca381ca2f0a

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7c4479ae5cb5d43003ab07b1b76f04689c2221b2
