### ISSUE TITLE
http://coin-hive.com

### ISSUE THREAD

**Issue by lukanz** [easylist/easylist#618]
coin-hive.com "A Crypto Miner for your Website" used by flashx.tv should be added to the list!!!

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=38219
https://forums.lanik.us/viewtopic.php?f=88&t=38230

**Comment by SMed79** [comment]
@lukanz 

Subscribe to **NoCoin** filters list from https://adblockplus.org/subscriptions#type_other

![Adblock plus](http://i.imgur.com/JnVAK9m.png)

**Comment by Khrin** [comment]
Has been added to EasyPrivacy: https://github.com/easylist/easylist/commit/7c36bbe9c8aad4ce037a1c4559b978ef2e7eba5c

**Comment by DatDraggy** [comment]
@lukanz but why?
