### ISSUE TITLE
Eurogamer.net - easylist cookie

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#6182]
### List the website(s) you're having issues:

`https://www.eurogamer.net/articles/digitalfoundry-2020-dlss-ultra-performance-analysis`

### What happens?
The video can't be played as cookies have not been allowed and easylist cookie hide the cookie popup. Clicking on "cookie settings" does nothing
![image](https://user-images.githubusercontent.com/83005/96098362-5102ef80-0ed2-11eb-9a31-114e7b2e4e77.png)

### List Subscriptions you're using:
easylist, easylist fr, easylist cookie, ublock annoyance

### Your settings

- OS/version: 
- Browser/version: firefox
- Adblock Extension/version: ublock origin

**Comment by krystian3w** [comment]
Try this:

```
@@||cdn.cookielaw.org^$domain=comicbook.com|metabomb.net|usgamer.net|eurogamer.net|eurogamer.it|eurogamer.pl|eurogamer.pt|rtlnieuws.nl metabomb.net,usgamer.net,eurogamer.it,eurogamer.net,eurogamer.pl,eurogamer.pt,rtlnieuws.nl#@##onetrust-consent-sdk
##.onetrust-pc-dark-filter, #onetrust-banner-sdk
```

**Comment by spirillen** [comment]
@krystian3w isn't there a space to much between ?

`##.onetrust-pc-dark-filter, #onetrust-banner-sdk`

**Comment by krystian3w** [comment]
If you ask for approvals `@@` / `#@#`, you can add their negations to your project again.

Space in "`##.onetrust-pc-dark-filter, #onetrust-banner-sdk`" is recommend for very old ABP/AdBlock (have bug with property read `,` without space).

---
The number three filter that I "recommend" hides the main pop-up without spoiling the advanced settings under the green button 🟢.

**Comment by keczuppp** [comment]
- related: https://github.com/AdguardTeam/AdguardFilters/issues/68007, the issue fixed in AdGuard but still persits in EasyList Cookie.

**Comment by peace2000** [comment]
I don't see any issues anymore with this site. Videos on that link work fine.
