### ISSUE TITLE
Facebook ads banner sponsored contents

### ISSUE THREAD

**Issue by Axel57000** [easylist/easylist#6196]
Hello everyone.

It's been a few days now that ad banners have appeared on Facebook, above my discussion thread, regardless of the browser I use (Edge, Firefox or Chrome). I've done some tests with only uBlock installed without any additional lists, but nothing helps, they're still there.
Do you have an idea? 

Thanks in advance.

- OS/version: Windows 10 Professionnal x64 (19041.508)
- Browser/version: Firefox 81.0.2 (64 bits)
- Adblock Extension/version: uBlock Origin 1.30.5b1

**Comment by krystian3w** [comment]
For France region needed is add:

`##a[aria-label="Lien de l’annonceur"]`

English translation completely no match.
