### ISSUE TITLE
Domain name exception request

### ISSUE THREAD

**Issue by johnaps94** [easylist/easylist#6199]
Hello!

I am sending you because i am facing a problem on a site i am about to publish that gets broken by adblock.

After reading this article ( https://help.getadblock.com/support/solutions/articles/6000111830-adblock-is-blocking-something-or-has-broken-a-website-for-site-owners- )
i found out that i need to find the list that was causing the problem and i found out that it was your list and i should contact you for making an exception!

My current staging url that gets broken is : http://adsec.kinsta.cloud/
which will become when goes live  : https://adsec.gr/

Its a business site of a customer which is on a deadline!

I need your help as fast as possible!

Please get back to me with any update, or if you need anything from me!

Thank you for your time!

Sincerely

**Comment by krystian3w** [comment]
need chage: https://github.com/easylist/easylist/blob/58d4852bea3da4396a87092d40294e95e8fc6a48/easylist/easylist_general_block.txt#L2948

`/adsec.`

to:

```
/adsec.$domain=~adsec.kinsta.cloud
```

**Comment by johnaps94** [comment]
I need to do anything or you did make the exception??

Στις Παρ, 16 Οκτ 2020, 16:52 ο χρήστης krystian3w <notifications@github.com>
έγραψε:

**Comment by krystian3w** [comment]
I did not do it, I leave it to the willing, the project is mainly developed by 4 people:

- `ryanbr` (Australia and Ocenia)
- `Khrin` (Italy)
- `monzta` (Germany)
- `smed79` (France and Arabic pages)

They can always remove the rule in its entirety, as they know about the poor effectiveness of blocking by means of advertising.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/8971c8b0844be12b0ad2be4a62bf1a6143ebde4e
