### ISSUE TITLE
wichspornos.com [NSFW]

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#6201]
### List the website(s) you're having issues:
[T1862: `wichspornos.com`](https://www.mypdns.org/T1862)

### What happens?

Overlay video ad

### List Subscriptions you're using:

Plenty

### Your settings

- OS/version: 5.4.0-51-generic
- Browser/version: FF 81.0.0
- Adblock Extension/version:

**Comment by THEtomaso** [comment]
`movie.momo-net.com###overlay`
