### ISSUE TITLE
brbushare.me | uplinkto.top

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6224]
### List the website(s) you're having issues:

`https://uplinkto.top/view/NAWrLFWtCc`

`https://brbushare.me/view/2wNsbRN9K0`

### What happens?

popup ads in new tab

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: firefox 81
- Adblock Extension/version: ublock origin 1.30.4 

### Other details:

This works for me

`||discourteousrecitalparole.com^`
`||courtroomprobe.com^`
`||agrarianeruption.com^`

**Comment by ryanbr** [comment]
Update the lists, should be fixed.
