### ISSUE TITLE
go.extra-drive.com

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6225]
### List the website(s) you're having issues:

`https://go.extra-drive.com/WTzQ7j`

### What happens?

fake `get link` buttons after captcha verification page ,puzzled which to click because all look same to user

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: opera browser stable/firefox android 81
- Adblock Extension/version: ublock origin 1.30.4

### Other details:

screenshot
![image](https://user-images.githubusercontent.com/20338483/96362200-4736f180-1149-11eb-9e30-675aba8777bc.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e7cfa131bd87002496fdab7f78d9befbd5c39998

**Comment by ghajini** [comment]
There are still fake buttons in page once you pass captcha page and move to next page

Filter working 

`go.extra-drive.com##.box-main > a.btn-lg.btn-success.btn`
![IMG_20201018_171304](https://user-images.githubusercontent.com/20338483/96366474-62aff580-1165-11eb-9166-e780eb426b3e.jpg)
![IMG_20201018_171230](https://user-images.githubusercontent.com/20338483/96366476-6479b900-1165-11eb-9132-94e7fd2c1129.jpg)

**Comment by ghajini** [comment]
@Khrin

**Comment by ghajini** [comment]
@mapx- add pls in ublock
go.extra-drive.com##.box-main > a.btn-lg.btn-success.btn

Test link is unavailable now,but I will repost when found

**Comment by ghajini** [comment]
@mapx- 

check this link `https://go.extra-drive.com/cFpO01Id`

**Comment by mapx-** [comment]
`go.extra-drive.com##[target="blank"]`
