### ISSUE TITLE
oppo.com, vivo.vom, games2gether.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#6226]
### What happens?

 Cookie notice at the bottom 
<details><summary>Screenshot:</summary>

![3](https://user-images.githubusercontent.com/29574622/96362454-37221080-114f-11eb-8206-28d08a2b889c.png)

![2](https://user-images.githubusercontent.com/29574622/96362459-40ab7880-114f-11eb-9f73-9fd94fb114ae.png)

![1](https://user-images.githubusercontent.com/29574622/96362464-4b660d80-114f-11eb-9efb-3c77204b2a69.png)

</details><br/>

### Your settings

- OS/version: Windows 10 2004
- Browser/version: Chromium Edge 86
- Adblock Extension/version: uBlock Origin 1.30.4

**Comment by ryanbr** [comment]
Has been fixed, updated your lists.
