### ISSUE TITLE
Admiral ad-blocker blocker

### ISSUE THREAD

**Issue by LissieTilbrook** [easylist/easylist#623]
This garbage is on certain websites, http://www.thewindowsclub.com is one of them.

![fuck you dan rua](https://user-images.githubusercontent.com/32066229/30630136-37f6940e-9dad-11e7-8912-aac3690ac28d.png)

This is impassable by many means. I don't want to selectively whitelist sites. 

The owner of Admiral, Dan Rua, is a copyright troll. Is there any way a filter can be used?

Thanks.

**Comment by mapx-** [comment]
Use uBo, is better equipped to remove such crap.

**Comment by LissieTilbrook** [comment]
Thanks. I'm not at my computer right now, so I'll look into it later.

Closing this issue.
