### ISSUE TITLE
dailymotion.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6230]
### List the website(s) you're having issues:

`https://www.dailymotion.com/video/x46yl1e`

### What happens?

Placeholder in the "Browse more videos" section.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/96386127-d4556700-1198-11eb-87b6-745606984c0a.png)

### Your settings

- OS/version: Windows 10 May 2020 Update
- Browser/version: Chrome 86.0.4240.75 x64
- Adblock Extension/version: uBO 1.30.4 + uBO Extra 2.88 + IDCAC 3.2.3

### Other details:

I propose adding `dailymotion.com##div[class*=AdCard__adCell__]`.

**Comment by stephenhawk8054** [comment]
Another placeholder in the page.

URL: `https://www.dailymotion.com/video/x6hneys`

![image](https://user-images.githubusercontent.com/66517106/140852101-d7890c3f-d34b-43f9-976a-864e3444cc5d.png)

Firefox 94.0.1, ublock 1.38.6 default.

Proposed filter:

`dailymotion.com##[class^="VideoInfo__videoInfoAdContainer"]`
