### ISSUE TITLE
ateli.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6234]
### List the website(s) you're having issues:

`https://ateli.com/`

### What happens?

Small placeholder near the top.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/96386127-d4556700-1198-11eb-87b6-745606984c0a.png)

### Your settings

- OS/version: Windows 10 May 2020 Update
- Browser/version: Chrome 86.0.4240.75 x64
- Adblock Extension/version: uBO 1.30.4 + uBO Extra 2.88 + IDCAC 3.2.3

### Other details:

The site has an opt-in partial English UI translation, thus why I'm submitting it here.

I propose adding `ateli.com##.o-hidden.mw-xl`

Highlighting the placeholder: 
![image](https://user-images.githubusercontent.com/22780683/96386861-6875fd00-119e-11eb-9d31-ff662c62443f.png)

**Comment by ryanbr** [comment]
Just a "Ads are blocked" so, not in Easylist.
