### ISSUE TITLE
ytmp3.cc

### ISSUE THREAD

**Issue by Greg0rus** [easylist/easylist#6243]
Since a few days i'm longer able to use the website ytmp3.cc. The site is not working properly and freeze. The developer console is showing that the required js file is not loaded. Error: ERR_BLOCKED_BY_CLIENT. Without adblock everything is working fine. 

I'm using Windows 10 with chrome version Chrome/86.0.4240.75.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/433cea388580da473002bad78b410ecb858b5781
