### ISSUE TITLE
search.yahoo.com

### ISSUE THREAD

**Issue by PIZZA90** [easylist/easylist#6246]
### List the website(s) you're having issues:

`https://es.search.yahoo.com/search?fr=mcafee&type=E214ES0G0&p=decathlon`

### What happens?

ad unit

![Captura](https://user-images.githubusercontent.com/33556647/96649317-31842080-1331-11eb-98bc-756f961ce5d2.PNG)

### List Subscriptions you're using:

uBlock Origin Default Lists

### Your settings

- OS/version:  **Windows 10**
- Browser/version: **Chrome**
- Adblock Extension/version:  **uBlock Origin 1.30.6**

### Other details:

possible fix:

`search.yahoo.com##.sys_shopleguide
`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/d282c8441a2ec386fc08e9310047a5298e2ec14c
