### ISSUE TITLE
arabiaweather.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6250]
### List the website(s) you're having issues:

`https://www.arabiaweather.com/en/weather-forecast/beirut/3/lb`

### What happens?

Two placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/96671573-63fa4180-1362-11eb-8a98-a8290c809c56.png)

### Your settings

- OS/version: Windows 10 May 2020 Update
- Browser/version: Chrome 86.0.4240.75 x64
- Adblock Extension/version: uBO 1.30.7.0 + uBO Extra 2.88 + IDCAC 3.2.3

### Other details:

I propose adding:
```
arabiaweather.com##.leaderboard-container
arabiaweather.com##.mpu-card
```

![image](https://user-images.githubusercontent.com/22780683/96673250-6068b980-1366-11eb-85ec-450410999005.png)

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/1dc13082c4fe2c38f97197db17195d74bb63b05b
