### ISSUE TITLE
caltat.com

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#6256]
### List the website(s) you're having issues:
`caltat.com` (T2157)

### What happens?
As I was on the run for badware I found a call to this domain from `uniondht.org` (T2100) When I looked it up in your list I see you have classified it as adult adware

```
git grep 'caltat.com'
easylist_adult/adult_adservers.txt:||caltat.com^$third-party
```

But when you looks up the purpose of the domain, I would rather classify it as scam/spam/tracking

![image](https://user-images.githubusercontent.com/44526987/96729535-89646b00-13b5-11eb-9d69-fb5317e4fc02.png)

![image](https://user-images.githubusercontent.com/44526987/96729598-9c773b00-13b5-11eb-8417-8498cfcd7be5.png)

![image](https://user-images.githubusercontent.com/44526987/96729642-a8fb9380-13b5-11eb-8bee-28738ffdd84b.png)

![image](https://user-images.githubusercontent.com/44526987/96730022-0ee81b00-13b6-11eb-97aa-487183ed34c2.png)

**Comment by spirillen** [comment]
PS: They uses tracking pixels

`https://cdn3.caltat.com/78784f16-8571-4898-9a7e-2b816ea84f37/pixel.php?u=`

**Comment by ryanbr** [comment]
Probably fine where it is, unless they complain.
