### ISSUE TITLE
rei9jc56oyqux0rcpcquqmm7jc5freirpsquqkope3n3axrjacg8ipolxvbm.codes (AdWare?)

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#6271]
### List the website(s) you're having issues:
`https://mangahentai.me/`

### What happens?
![image](https://user-images.githubusercontent.com/44526987/96894421-f21e1700-148b-11eb-8157-9228d071aa9a.png)

Suspect it is a adware....
`https://rei9jc56oyqux0rcpcquqmm7jc5freirpsquqkope3n3axrjacg8ipolxvbm.codes/lcgkwnosci5pbikod2luzg93wyquyw9dtyqucl0pyodgklnosci5jbikobmv3ierhdguokszsqsbueiuzw.js`

### List Subscriptions you're using:

A lot

### Your settings

- OS/version: 
- Browser/version: Tor
- Adblock Extension/version: 

### Other details:

T2325

**Comment by THEtomaso** [comment]
The monsterous, auto-generated URL is a dead giveaway.
..and to be honest, I don't even like the sound of that TLD.
`https://www.spamhaus.org/statistics/tlds/` only reports it as being 1.4% bad, but I think I'll just add it to my TLD blocklist regardlessly.

_There; problem solved!_ :)

**Comment by spirillen** [comment]
> The monsterous, auto-generated URL is a dead giveaway.
> ..and to be honest, I don't even like the sound of that TLD.

I had the same way.... the domain it self tricked my attention :)

But would like the JS gurus to confirm the scripts purpose.
