### ISSUE TITLE
animetake.tv

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#6274]
On default video player (Video):
`http://animetake26.stream/view/8227160913/
`
Unblocked ads.js script is seen on logger (need to use animetake*.* rule as page changes URL daily basis)
https://animetake26.stream/js/ads.js

Using Fanboy Ultimate list, along with Adguard lists (base, trackers, social, mobile, annoyances)

- OS/version: Lubuntu 20.04
- Browser/version: Firefox 82
- Adblock Extension/version: uBlock Origin v1.30.7b2

**Comment by ryanbr** [comment]
Thats is good, it should remain unblocked. its a check.
