### ISSUE TITLE
howtogeek.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6292]
### List the website(s) you're having issues:

`https://www.howtogeek.com/697152/where-did-the-system-control-panel-go-on-windows-10/`

### What happens?

Placeholder below the article.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97099820-a3d86600-168d-11eb-985b-d2077e1068dd.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose `howtogeek.com##.article-bottom`

Without the entry: 
![image](https://user-images.githubusercontent.com/22780683/97100061-15b1af00-1690-11eb-985e-628030d69382.png)

**Comment by DandelionSprout** [comment]
Seems to not be a noteworthy problem anymore.

**Comment by stephenhawk8054** [comment]
There are ads placeholders on the website.

URL: `https://www.howtogeek.com/333484/how-to-set-up-multiple-user-profiles-on-android/`

<details><summary>Screenshot</summary>

![Screenshot 2021-11-18 at 11-47-42 How to Set Up Multiple User Profiles on Android](https://user-images.githubusercontent.com/66517106/142353760-3406c3fe-b622-41dc-9bf9-68dbce66f244.png)

</details>

Firefox 94.0.1, ublock 1.38.6 default

Proposed filter:

`howtogeek.com##.e-content.entry-content > [data-nosnippet]`
