### ISSUE TITLE
joshuawright.net

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6296]
### List the website(s) you're having issues:

`http://joshuawright.net/slack-wyrm-678.html`

### What happens?

Placeholder on the far top.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97099820-a3d86600-168d-11eb-985b-d2077e1068dd.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose `joshuawright.net##.position_content > .colelem:first-of-type`

Without the entry: 
![image](https://user-images.githubusercontent.com/22780683/97100352-c7ea7600-1692-11eb-8a6b-57141af6d639.png)

**Comment by ryanbr** [comment]
Again, no worth adding.
