### ISSUE TITLE
downforeveryoneorjustme.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6297]
### List the website(s) you're having issues:

`https://downforeveryoneorjustme.com/`

### What happens?

Placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97099820-a3d86600-168d-11eb-985b-d2077e1068dd.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose `downforeveryoneorjustme.com##.is-hidden-mobile.large-pad` to remove the top one. I'm not 100% sure about the best way to remove the one that is immediately below the search bar (if at all).

Without the entry: 
![image](https://user-images.githubusercontent.com/22780683/97100462-18ae9e80-1694-11eb-837e-7118b391ed95.png)

**Comment by THEtomaso** [comment]
> I'm not 100% sure about the best way to remove the one that is immediately below the search bar (if at all).

Isn't xpath supported by ABP-blockers?:
`downforeveryoneorjustme.com##.native-carbon:xpath(../../../..)`

**Comment by DandelionSprout** [comment]
They don't seem to do so.

They have very recently added `#$#hide-if-matches-xpath`, but only for ABP Anti-Circumvention Filters.

**Comment by DandelionSprout** [comment]
It appears the `##.is-hidden-mobile.large-pad` placeholder is gone by now, whereas the "To the left below the search bar" one would not free up any space unless `:style` is used. So I can probably close this report now. 😅
