### ISSUE TITLE
out-of-scope bloat added to tracking list

### ISSUE THREAD

**Issue by funkydude** [easylist/easylist#630]
https://github.com/easylist/easylist/commit/7c36bbe9c8aad4ce037a1c4559b978ef2e7eba5c

This commit blocks the bitcoin miner in the tracking list. This isn't a tracker, this is bloat that I do not want forced on me in my anti-tracking lists.

Jumping on the bandwagon of blocking this is moronic. It should be a toggle-able feature as it is literally the only future prospect of killing internet ads.

Please revert and put this up for discussion.

**Comment by ryanbr** [comment]
It is what it is. Using cpu cycles and sending to a third-party has privacy implications.
