### ISSUE TITLE
thehardtimes.net

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6301]
### List the website(s) you're having issues:

`https://thehardtimes.net/harddrive/kids-with-two-living-parents-demand-representation-in-disney-films/`

### What happens?

Some thin placeholders spread around.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97099820-a3d86600-168d-11eb-985b-d2077e1068dd.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose `thehardtimes.net#?#.code-block:-abp-has(script:-abp-contains(googletag))`

Highlighting the placeholders: 
![image](https://user-images.githubusercontent.com/22780683/97102128-4b13c800-16a3-11eb-827d-47c1266f15c4.png)

**Comment by Khrin** [comment]
I don't think that's necessary to have it listed.
