### ISSUE TITLE
thedailybeast.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6302]
### List the website(s) you're having issues:

`https://www.thedailybeast.com/trumpworld-wraps-up-the-campaign-by-going-full-qanon-conspiracy-theory`

### What happens?

Placeholder on the bottom.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97099820-a3d86600-168d-11eb-985b-d2077e1068dd.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose adding `thedailybeast.com##.StoryFooter`

Without the entry: 
![image](https://user-images.githubusercontent.com/22780683/97102385-47814080-16a5-11eb-9687-35a710f5e5a2.png)

**Comment by THEtomaso** [comment]
Also, the site's login function is broken by **AdGuard Annoyances filter** and **Fanboy's Enhanced Tracking List**:
https://github.com/AdguardTeam/AdguardFilters/issues/66358/
https://github.com/ryanbr/fanboy-adblock/issues/1423/
