### ISSUE TITLE
cycling.today

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6305]
### List the website(s) you're having issues:

`https://cycling.today/2020-giro-ditalia-live-stream/`

### What happens?

Placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97099820-a3d86600-168d-11eb-985b-d2077e1068dd.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose adding:
```
cycling.today##.td-banner-bg
cycling.today#?#p:-abp-has(> .adsbygoogle)
```

Without the entries: 
![image](https://user-images.githubusercontent.com/22780683/97104554-0db83600-16b5-11eb-87bd-c7c806c23e62.png)

**Comment by ryanbr** [comment]
Which placeholders @DandelionSprout  ? Site looks pretty clean

**Comment by DandelionSprout** [comment]
If I remember correctly (Highlighted in orange): 
![image](https://user-images.githubusercontent.com/22780683/97262057-6b1cc600-1820-11eb-8465-45a5550bee3a.png)
