### ISSUE TITLE
fileinfo.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6309]
### List the website(s) you're having issues:

`https://fileinfo.com/extension/gbx`

### What happens?

Placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97099820-a3d86600-168d-11eb-985b-d2077e1068dd.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

The placeholders are only really noticeable on very narrow windows and on phones.

I propose adding:
```
fileinfo.com##.linkAds
fileinfo.com##.adRightSky
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/issues/6310
