### ISSUE TITLE
bestforandroid.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6310]
### List the website(s) you're having issues:

`https://bestforandroid.com/thesis-writing-apps/`

### What happens?

Placeholders in the upper part of the article.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97106456-0a777700-16c2-11eb-8ca9-35a00cc94985.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose `bestforandroid.com##.adv-ads-selfstyle`

Without the entry:
![image](https://user-images.githubusercontent.com/22780683/97106497-47dc0480-16c2-11eb-891b-19d1e3388571.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/cac3590793aa1972021bc5b86be37e2517386e12
