### ISSUE TITLE
androidexplained.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6311]
### List the website(s) you're having issues:

`https://www.androidexplained.com/battery-charge-limit/`

### What happens?

Placeholder below the article.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97106456-0a777700-16c2-11eb-8ca9-35a00cc94985.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose `androidexplained.com##article + div[class^=astra-advanced-hook-]`

Without the entry: 
![image](https://user-images.githubusercontent.com/22780683/97106605-11eb5000-16c3-11eb-8187-75660db76349.png)

**Comment by ryanbr** [comment]
Probably not worth blocking this.
