### ISSUE TITLE
getdroidtips.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6312]
### List the website(s) you're having issues:

`https://www.getdroidtips.com/fire-tv-stick-vs-fire-tv-stick-lite/`

### What happens?

A lot of placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97106456-0a777700-16c2-11eb-8ca9-35a00cc94985.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose `getdroidtips.com##.code-block`

Some of the placeholders without the entry: 
![image](https://user-images.githubusercontent.com/22780683/97106766-c7b69e80-16c3-11eb-82d6-2a589e7728e1.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e6dfd5ad563a5984390497c708ea83820905fe1b
