### ISSUE TITLE
droidwin.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6313]
### List the website(s) you're having issues:

`https://www.droidwin.com/`

### What happens?

Two placeholders in the rightside bar.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97106456-0a777700-16c2-11eb-8ca9-35a00cc94985.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.7b3 + IDCAC 3.2.3

### Other details:

I propose `droidwin.com##.widget_custom_html`

Without the entry: 
![image](https://user-images.githubusercontent.com/22780683/97106839-2bd96280-16c4-11eb-998b-aca713dc2f02.png)

**Comment by Khrin** [comment]
I'm not sure if it's worthwhile to add such a "generic" filter just for two empty placeholders...

**Comment by krystian3w** [comment]
IMO cut any content on that page in the future.

**Comment by ryanbr** [comment]
Yeah, agreed. Closing.
