### ISSUE TITLE
mediafire.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6320]
### List the website(s) you're having issues:

`https://www.mediafire.com/file/z08pydghqqjdjpo/macOS_Catalina.7z/file`

### What happens?

As a result of `@@||mediafire.com^$generichide` in EasyList, roughly half the page now consists of placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97276426-729b9980-1837-11eb-9bf3-118b6eee5b39.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: 
- Adblock Extension/version: uBO 1.30.7b4 + IDCAC 3.2.3

### Other details:

I propose `mediafire.com##div[id^=div-gpt-ad-]`

Highlighting: 
![image](https://user-images.githubusercontent.com/22780683/97276347-5992e880-1837-11eb-80b3-b98e2ebe128f.png)

**Comment by ryanbr** [comment]
It won't collapse the blank space here @DandelionSprout

**Comment by ryanbr** [comment]
Closing.
