### ISSUE TITLE
EasyCookie: all search results hidden on https://docs.microsoft.com/en-us/search/ by filter 

### ISSUE THREAD

**Issue by slippycheeze** [easylist/easylist#6327]
### List the website(s) you're having issues:

* <code>https://docs.microsoft.com/en-us/search/?terms=windows%2010%20virtualization</code>

### What happens?

All search results are hidden by a cosmetic filter.  uBlock Origin reports the details follow.  This is reproduced by performing any search on https://docs.microsoft.com/en-us/search/

Details | <span></span>
---- | ----
Filter | `docs.microsoft.com##.has-padding-top-medium`
Filter list | Fanboy’s Annoyance, EasyList Cookie 
Context | docs.microsoft.com
Type | dom
URL | <code>https://docs.microsoft.com/en-us/search/?terms=windows%2010%20virtualization</code>

Since this is present on another filter list, as well as this one, I've also reported this here: https://github.com/ryanbr/fanboy-adblock/issues/1429

### List Subscriptions you're using:

I have manually verified that the cosmetic filter `docs.microsoft.com##.has-padding-top-medium` is present in the EasyCookie list.

### Your settings

- OS/version: macOS 10.15.7
- Browser/version: Chrome 86.0.4240.111 x86_64
- Adblock Extension/version: uBlock Origin 1.30.6 (official extension store)

### Other details:

I can provide the relevant details, but I verified the DOM content by hand, that an override for the rule fixes the problem, and that the filter reported by the uBlock Origin occurs in both the lists given.  Let me know if you need anything more.

I have not tried to figure out what changes are required to make the cookie blocking work on the site once the override is in place.  I don't get any notification, but I have likely accepted the configured cookie policy before.

**Comment by THEtomaso** [comment]
> I have not tried to figure out what changes are required to make the cookie blocking work on the site

**EasyList Cookie List** also contains this rule, which seems to block the cookie message just fine:
`||microsoft.com/mscc/`
So, the problem rule might actually be completely redundant.

Alternatively, the message can be blocked on a cosmetic level by this rule (already present in **I don't care about cookies**):
`microsoft.com###cookie-consent-holder`
