### ISSUE TITLE
[NSFW] animal-porno.xyz

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#6328]
### List the website(s) you're having issues:

`animal-porno.xyz` (T2415)

### What happens?

Exit popup

**Comment by runboy93** [comment]
https://www.virustotal.com/gui/url/5239b09ac7fe6e7c92030273d1f979e95bec45d9dd79d498172a0c354c08acc5/links

Outgoing Links
http://animal-porn-videos.icu

It seem to lead different website, no idea I didn't check actual page out, just virustotal checked.

**Comment by spirillen** [comment]
it is a CJ script that do this, so your destination will differ

**Comment by ryanbr** [comment]
Added the adserver.
