### ISSUE TITLE
adultasianporn.com NSFW

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#6331]
### List the website(s) you're having issues:

`http://adultasianporn.com/`

### What happens?

1. Unblocked ads

<details>
<summary>Screenshot</summary>

![adultasianporn](https://user-images.githubusercontent.com/58900598/97769499-e3f88680-1b6e-11eb-83c2-f38c1c1b7262.png)

</details>

2. Fake player overlay which causes popunder

<details>
<summary>Screenshot</summary>

![adultasianporn1](https://user-images.githubusercontent.com/58900598/97769501-e78c0d80-1b6e-11eb-8052-c27c8aa68691.png)

</details>

3. If you middle click a thumbnail, or sometimes even normal click, the page redirects to random porn sites. It may not happen at the first visit, repeat (middle-)clicking thumbnails.

### List Subscriptions you're using:

uBO default + AGJPN

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 82.0.2
- Adblock Extension/version: 1.30.6

### Other details:

1. `||adultasianporn.com/*.php`
`adultasianporn.com###abra_all`

2. `||adultasianporn.com/css/youtube.png`

If you search for `"ahacdn.me"` in publicwww, you'll find many porn sites with similar issues not addressed.

**Comment by Yuki2718** [comment]
@mapx- @uBlock-user @okiehsch I don't think the problem 3. can be addressed within standard ABP syntax. Please take a look.

**Comment by mapx-** [comment]
@Yuki2718  test:

`hclips.com,txxx.com##+js(aeld, , _0x)`

**Comment by Yuki2718** [comment]
@mapx- Still got redirect to `muchfuck.com` (nsfw):

<details>
<summary>Screenshot</summary>

![adultasianporn](https://user-images.githubusercontent.com/58900598/97774540-0bb21380-1b9c-11eb-8f13-52f7968d637e.png)

</details>

(I won't be able to respond for a while.)

**Comment by mapx-** [comment]
test

`adultasianporn.com##+js(cookie-remover, /^/)`

**Comment by Yuki2718** [comment]
@mapx- Thx, working fine with up-to-date lists and that filter alone!
