### ISSUE TITLE
the Adblock Warning Removal List working on yahoo mail (new mail not the basic mail)

### ISSUE THREAD

**Issue by yuanshdn** [easylist/easylist#6332]
Hi
if you switch yahoo mail to new maili pops up like this and [the list](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt) does not work
![image](https://user-images.githubusercontent.com/61946187/97777368-faa9d800-1b84-11eb-940b-e7b9f82e3826.png)

**Comment by krystian3w** [comment]
Maybe no possible fix without use:

https://help.eyeo.com/en/adblockplus/how-to-write-filters#snippets

---

Or `smed79` and `dimisa-RUAdList` newer use Yahoo.

**Comment by yasershadan** [comment]
> Maybe no possible fix without use:
> 
> https://help.eyeo.com/en/adblockplus/how-to-write-filters#snippets
> 
> Or `smed79` and `dimisa-RUAdList` newer use Yahoo.

can you guide me on more details? I need a step by step guide or how to solve this problem
thanks

**Comment by krystian3w** [comment]
Try add this into custom filters in Adblock Plus (ABP):

`||s.yimg.com/*/bundle_basic_mail_affiliate_partner_$domain=mail.yahoo.com`
`@@||s.yimg.com/rq/darla/boot.js$domain=mail.yahoo.com`
`mail.yahoo.com##div[aria-describedby="adblock-unblock-cue"]`

**Comment by yasershadan** [comment]
> Try add this into custom filters in Adblock Plus (ABP):
> 
> `||s.yimg.com/*/bundle_basic_mail_affiliate_partner_$domain=mail.yahoo.com`
> `@@||s.yimg.com/rq/darla/boot.js$domain=mail.yahoo.com`
> `mail.yahoo.com##div[aria-describedby="adblock-unblock-cue"]`

It didn't work
