### ISSUE TITLE
Streamtape.com (NSFW video)

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#6334]
`https://streamtape.com/e/vWQb6yeBAvcY36
`
Click video player, popup will appear (blocked elements inside popup):

`https://lowtyroguer.com/4/3647548
`
Using Fanboy Ultimate list, along with Adguard lists (base, trackers, social, mobile, annoyances)

OS/version: Android 10
Browser/version: Vivaldi 3.4
Adblock Extension/version: built-in

**Comment by spirillen** [comment]
Can you test with these rules in your local filter??

```
! 2020-11-02 streamtape.com
! https://www.mypdns.org/T2511
||streamtape.com/adult2.js$script,important
||streamtape.com/ad.js$script,important
```

**Comment by runboy93** [comment]
`||streamtape.com/adult2.js$script,important`

This one seem to done something, other one were already on list (Adguard Base)

**Comment by spirillen** [comment]
> something js check or what?

I'll doubt, it more like a user committed setting.

But a think there could be a potential of adding the `/adult2.js` at a more global value as I've seen it before

**Comment by runboy93** [comment]
You put:
`||streamtape.cc/adult2.js`

but shouldn't it be?
`||streamtape.com/adult2.js`
