### ISSUE TITLE
MixDrop (NSFW video)

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#6335]
`https://mixdrop.co/f/4ndxojmltm3zx9
`
Click video player (play, volume settings...), popup appear (randomly):

`https://foodprogrammesdiscreet.com/i620q2muu?key=0f22c1fd609f13cb7947c8cabfe1a90d&submetric=15149947
`
`https://www.casinoroom.com/fi/?btag=cxd-36187_415238_wvup31au5qvi1o132h5p6v6m
`
`https://wellgiftstore.com/?__cf_chl_jschl_tk__=b5f94665aa54bb736657acabaa11a2f200ef77ff-1604189258-0-ATr9RNTU6MfHbGekw_foZB98YaJkvGZLoxfyNsN4TMTI2QvCqQ2t74nAWOJSAt8V1cfBIpmmSTNshLvmc_9xDM0JGx16JMV3ag4rnF_P-kOHnh4OigeLnP6fYGlqzsQA8hPeDXXNU9BOblJaCkzLMw0WDJ84Emz7zBTKrRcXAMsz_Z_gJqBE4Ht32uPvg5tuMGHHVdnGGLEz6kkHPa7772CfiP2ZLX6czrUKR7hQPwtEL9VfzuWTDjpC4C8eKoBmFevEyZ-RObM5FqdsaFZLTW4`

Using Fanboy Ultimate list, along with Adguard lists (base, trackers, social, mobile, annoyances)

OS/version: Android 10
Browser/version: Vivaldi 3.4
Adblock Extension/version: built-in

**Comment by ryanbr** [comment]
Looks fine, just for an update @runboy93
