### ISSUE TITLE
animalcrossingworld.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6336]
### List the website(s) you're having issues:

`https://animalcrossingworld.com/2020/09/the-final-10-years-of-animal-crossing-for-gamecube-happy-18th-birthday/`

### What happens?

Two placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/97804411-0f06d700-1c50-11eb-9cfc-003c2184e042.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.111 x64
- Adblock Extension/version: uBO 1.30.9b3 + IDCAC 3.2.3

### Other details:

I propose:
```
##.at-header-ad
animalcrossingworld.com##.at-sidebar-1
```

Without the entry: 
![image](https://user-images.githubusercontent.com/22780683/97804383-c818e180-1c4f-11eb-9a06-fedf204599aa.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/23c0aa78a2ca956cddbb06ae4871976aa9d88e04
