### ISSUE TITLE
cdn.shortpixel.ai false positive

### ISSUE THREAD

**Issue by skapytek** [easylist/easylist#6340]
### List the website(s) you're having issues:
cdn.shortpixel.ai
https://cyberpanel.net/ (for example this site tries to be loaded on cyberpanel website: https://cdn.shortpixel.ai/spai/w_800+q_lossy+ret_img+to_webp/https://cyberpanel.net/wp-content/uploads/2018/07/cyberpanel-banner-graphics-6.png)

### What happens?
false positive-its not a tracker, neither its an ad site, malware,...

### List Subscriptions you're using:
Adguard Base List & Easylist

### Your settings
im using Easylist in NextDNS
no plugins/extensions activated in Firefox

- OS/version: Win 10 Pro 64bit 2004
- Browser/version: Firefox 83 64bit

[https://i.ibb.co/9rP5NJx/2020-11-02-21h24-51.png](Cyberpanel website)
[https://i.ibb.co/7zR8m8R/2020-11-02-21h26-48.png](cdn.shortpixel.ai)

**Comment by krystian3w** [comment]
For me, it is still a translation `third-party` bug in NextDNS.

Rather changing to `domain=~shortpixel.ai` is a bad idea.

**Comment by ryanbr** [comment]
I would filter it out via NextDNS devs, the conversion from Easylist->DNS shouldn't process $popup.

**Comment by skapytek** [comment]
Just a notice from me: nextdns still not answered my mails ive send to them 8 days ago so i think they dont care about their customers who have paid for their service.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/8749
