### ISSUE TITLE
cliphunter.com NSFW

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#6341]
`https://www.cliphunter.com/
`
Advertisement placeholders:

`Advertisement:`

`Please checkout our sponsors:`

Using Fanboy Ultimate list, along with Adguard lists (base, trackers, social, mobile, annoyances)

OS/version: Lubuntu 20.04
Browser/version: Firefox 82
Adblock Extension/version: uBlock Origin v1.30.9b5

**Comment by spirillen** [comment]
Not that I've retested, but found this one in the archives of mine (T611)

`creatives.cliphunter.com` for serving ads

**Comment by ryanbr** [comment]
Blocked here @runboy93  Force an update.
