### ISSUE TITLE
enter.javhd.com NSFW

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#6360]
### List the website(s) you're having issues:

URL: `https://enter.javhd.com/signup/signup.php?step=2&nats=NzAzLjIuMi4yLjAuMC4wLjAuMA&_language=en`
Or visit `https://javhd.com/en/` and click any thumbnails.

### What happens?

CNAME issue: layout broken and impossible to login:

<details>
<summary>Screenshots</summary>

![javhd](https://user-images.githubusercontent.com/58900598/98234723-2d4c3a00-1fa4-11eb-9cb7-eb2ed778923b.png)

![javhd1](https://user-images.githubusercontent.com/58900598/98234728-2f15fd80-1fa4-11eb-916b-cedea6474472.png)

</details>

### List Subscriptions you're using:

uBO default + AGJPN

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 82.0.2
- Adblock Extension/version: uBO 1.30.6

### Other details:

Reproduced with Cloudflare DNS
`@@||javbucks.com^$domain=javhd.com`
No idea which file to add as currently adult_allowlist.txt doesn't have CNAME section.

**Comment by mapx-** [comment]
not enough css ?
`@@||javbucks.com^$css,domain=javhd.com`

**Comment by Yuki2718** [comment]
@mapx- Yeah, probably enough.
