### ISSUE TITLE
/advertising-* too broad, blocks "friendly" URLs from user-generated titles

### ISSUE THREAD

**Issue by Zenexer** [easylist/easylist#6365]
### List the website(s) you're having issues:

```
https://xenforo.com/community/threads/advertising-location-post-below-message-container-for-article-threads.187370/
```

There have been plenty of others on forums and such over the years, but I've never bothered to report it until now.  This particular example is a bug report with a title chosen by the user.

### What happens?

![image](https://user-images.githubusercontent.com/504130/98282652-8ac49480-1f6c-11eb-82a1-cae471fd9c09.png)

### List Subscriptions you're using:

* EasyList, version 202011022337, Last modified: 02 Nov 2020 23:37 UTC

### Your settings

- OS/version: Windows 10 Pro x64 build 18363
- Browser/version: 86.0.4240.183 (Official Build) (64-bit) (cohort: Stable)
- Adblock Extension/version: uBlock Origin (cjpalhdlnbpafiamejdnhcphjbkeiagm) version 1.30.6

### Other details:

This is really only an issue when visiting a URL directly.  Is there a flag that can be added to the rule to prevent it from matching when the URL is visited directly?

**Comment by DandelionSprout** [comment]
There's already a lot of whitelistings in `/advertising-$domain=~abramarketing.com|~advertising-direct.com|~advertising-excellence.com|~advertising-factory.de|~advertising.amazon.com|~deals-italy.com|~microsoft.com|~outbrain.com|~yellowimages.com`, so the big question is whether Khrin or Fanboy will think it's a good idea to add more whitelistings or to remove the entry entirely.
