### ISSUE TITLE
computerbase.de

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#6381]
### List the website(s) you're having issues:
`https://www.computerbase.de/2020-11/amd-ryzen-5000-test/2/`

### What happens?
Cookie notice 
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/98395666-ca7f9f00-2086-11eb-9786-23a273ba002c.png)

</details><br/>

### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List
### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Firefox 82.0.2
- Adblock Extension/version: uBlock Origin 1.30.6

**Comment by ryanbr** [comment]
No way to fix unfortunately
