### ISSUE TITLE
Reddit Premium/new reddit prompts (annoyances)

### ISSUE THREAD

**Issue by yoasif** [easylist/easylist#6382]
### List the website(s) you're having issues:

`https://old.reddit.com/r/firefox/comments/jowxkj/why_is_ublock_origin_better_than_other_adblockers/`

### What happens?

Two prompts - a sidebar banner and a red image in the top header prompting users to try new reddit/reddit premium

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

Fixed by 

reddit.com##.premium-banner
reddit.com###redesign-beta-optin-btn

You need to use reddit.com instead of old.reddit.com because if you are a logged in user opted out of the redesign, you get the old reddit UI without needing to use old.reddit.com.

**Comment by krystian3w** [comment]
New layout have randomized classes.
