### ISSUE TITLE
ctgpratidin.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#6402]
### List the website(s) you're having issues:
`https://ctgpratidin.com/%E0%A6%AC%E0%A6%BF%E0%A6%B6%E0%A7%8D%E0%A6%AC%E0%A7%87%E0%A6%B0-%E0%A6%AC%E0%A7%81%E0%A6%95%E0%A7%87-%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE%E0%A6%A6%E0%A7%87%E0%A6%B6%E0%A7%87%E0%A6%B0/`

### What happens?

Multiple ads
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/98462562-5a386100-21df-11eb-81f5-81b83d325a40.png)
![2](https://user-images.githubusercontent.com/29574622/98462567-63c1c900-21df-11eb-9e41-f389dde83ccc.png)

</details><br/>

### List Subscriptions you're using:
uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances

### Your settings

- OS/version: Android 9
- Browser/version: Firefox Nightly on Android
- Adblock Extension/version: uBlock Origin 1.30.6

**Comment by ryanbr** [comment]
Note, Easylist is an english list. Unless there is a common adserver  or generic element.
