### ISSUE TITLE
hqporner.com (NSFW) stat collection / ads js?

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#6407]
https://hqporner.com/hdporn/99379-MILF_next_door.html

I noticed these on logger (ublocked):
`https://stat.mydaddy.cc/e.php`
`https://mydaddy.cc/js/ads.js`

Atleast that stat sounds more suspious, ads.js might be needed to use video players work (someone might test more?)

Using Fanboy Ultimate list + Adguard lists (base, trackers, social, mobile, annoyances) + Spam404 + Online Malicious URL Blocklist

OS/version: Lubuntu 20.04
Browser/version: Vivaldi 3.4.2066.94
Adblock Extension/version: uBlock Origin v1.30.9b7

**Comment by Yuki2718** [comment]
`https://mydaddy.cc/js/ads.js` is a check or bait: a probe to detect adblocker so should not be blocked.

**Comment by spirillen** [comment]
@Yuki2718 
> a probe to detect adblocker so should not be blocked

Depending on how it's done, it might be considered as fingerprinting/SpyWare.

However I haven't analyzed the method used.

**Comment by runboy93** [comment]
Still there.
