### ISSUE TITLE
brazzers3x.me (NSFW) ads xhr / scripts?

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#6408]
http://brazzers3x.me/movies/my-friend-s-hot-mom-naughtyamerica-syren-de-mer-gets-young-cock-23-10-2020

Noticed these on logger (ublocked):
`http://brazzers3x.me/video-ads.ejs?_=20151218`
`http://javstream.to/api-ads?callback=movies_ads`

Someone might test more if these are really needed for video player / website to work correctly or can be disabled?

Using Fanboy Ultimate list + Adguard lists (base, trackers, social, mobile, annoyances) + Spam404 + Online Malicious URL Blocklist

OS/version: Lubuntu 20.04
Browser/version: Vivaldi 3.4.2066.94
Adblock Extension/version: uBlock Origin v1.30.9b7

**Comment by spirillen** [comment]
![image](https://user-images.githubusercontent.com/44526987/98737212-2f4c3980-23a6-11eb-95a7-fce6b9c9ea42.png)

**Comment by runboy93** [comment]
Still there.

**Comment by spirillen** [comment]
```
###invideo_wrapper
```
