### ISSUE TITLE
pornwild.to (NSFW) popup

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#6411]
https://pornwild.to

Click anything on websites, empty popup will appear (blocked stuff inside):
`https://syndication.realsrv.com/splash.php?cat=&idzone=4054624&type=8&p=https%3A%2F%2Fpornwild.to%2F&sub=&block=1&el=&tags=&scr_info=aW5saW5lfHBvcE1hZ2ljfDEuMC4w`

Using Fanboy Ultimate list + Adguard lists (base, trackers, social, mobile, annoyances) + Spam404 + Online Malicious URL Blocklist

OS/version: Lubuntu 20.04
Browser/version: Vivaldi 3.4.2066.94
Adblock Extension/version: uBlock Origin v1.30.9b7

**Comment by runboy93** [comment]
Still there.

**Comment by spirillen** [comment]
Why are you closing your issues if you believe there are something that need attention for enhancements?
