### ISSUE TITLE
thehealthy.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6421]
### List the website(s) you're having issues:

`https://www.thehealthy.com/food/heres-why-you-should-never-wash-chicken-before-cooking-it/`

### What happens?

Very, very large placeholders, especially below and above the article.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/98555708-8d8ff400-22a2-11eb-9894-bccd1a694668.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.183 x64
- Adblock Extension/version: uBO 1.30.9b12 + IDCAC 3.2.4

### Other details:

I propose adding:
```
##.ad-container-wrapper
##.pre-article-ad
```

The top part of the page without the entries: 
![image](https://user-images.githubusercontent.com/22780683/98555801-a698a500-22a2-11eb-9ca7-6a1ff343d396.png)

**Comment by THEtomaso** [comment]
### Additional issue:
Blocked videos.

### Examples:
`https://www.thehealthy.com/videos/`

### Problem filter:
* **EasyList**

### Problem rules:
`/apstag.js`
`||amazon-adsystem.com^$third-party`

### Blocked script:
`https://c.amazon-adsystem.com/aax2/apstag.js`

### Possible fix:
```
- @@||amazon-adsystem.com/aax2/apstag.js$domain=rd.com

+ @@||amazon-adsystem.com/aax2/apstag.js$domain=rd.com|thehealthy.com
```

--

### Other problem filters:
* **Dan Pollock's hosts file**
`amazon-adsystem.com`
`c.amazon-adsystem.com`

* **hpHosts - Ad and Tracking servers only** _(DISCONTINUED)_ and **MVPS HOSTS**
`c.amazon-adsystem.com`

* **Lunar Blocklist by Moonchild** https://repo.palemoon.org/Moonchild/lunarblocklist/issues/12/
`-adsystem.`

* **Malvertising list by Disconnect** and **Peter Lowe's Ad and tracking server list**
`amazon-adsystem.com`

--

### Possible fix (for **uBlock filters - Unbreak**):
(@okiehsch)
```
- @@||amazon-adsystem.com/*/apstag.js$script,domain=rd.com|tasteofhome.com

+ @@||amazon-adsystem.com/*/apstag.js$script,domain=rd.com|tasteofhome.com|thehealthy.com
```

### Note:
If you follow the link to my issue report for **Lunar Blocklist by Moonchild** above, you'll find a monster rule, which also includes all whitelistings for **apstag.js**, currently found in **AdGuard Base filter**, **EasyList** and **uBlock filters - Unbreak**

**Comment by THEtomaso** [comment]
Between **EasyList** and **uBlock filters - Unbreak**, whitelistings for `apstag.js` are now in place for all of the sites that uses `rd.com`'s page template (except for `birdsandblooms.com`, which doesn't seem to host affected videos).
However, people that only use **EasyList** will still experience broken videos at `tasteofhome.com`.
Examples:
`https://www.tasteofhome.com/videos/`
Therefore, it would make sense to whitelist `apstag.js` for that site to, in **EasyList**.

Alternatively, this monster rule (which I refered to in my previous post), could be added instead, to cover many more sites, which also are affected by the same issue:
`@@||amazon-adsystem.com^*/apstag.js$domain=player.watch.aetnd.com|baltimoresun.com|bemad.es|blastingnews.com|boing.es|ccuweather.com|go.cnn.com|cuatro.com|divinity.es|energytv.es|exomashomepage.com|factoriadeficcion.com|familyhandyman.com|fandom.com|fox21news.com|foxbusiness.com|foxnews.com|history.com|kark.com|keloland.com|radio.com|rd.com|spox.com|tasteofhome.com|telecinco.es|thehealthy.com|twitch.tv|webmd.com|wivb.com|wkrn.com|wlns.com|wvnstv.com`
Like I pointed out, this includes all whitelistings for `apstag.js`, currently found in **AdGuard Base filter**, **EasyList** and **uBlock filters - Unbreak**).
