### ISSUE TITLE
rd.com / thehealthy.com / tasteofhome.com / birdsandblooms.com / familyhandyman.com (All sites use the same UI)

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6422]
### List the website(s) you're having issues:

`https://www.rd.com/`

### What happens?

Uncloseable placeholder sticky on bottom that takes up ⅒ of a typical phone screen.

Note that the placeholder only appears on extremely narrow screens/windows. On Windows desktop PCs with 100% element scaling in the Windows 10 settings, the browser window must be ≤460px in order for the placeholder to appear. On phones, it appears if the physical phone screen is ≤~8cm wide in portrait mode.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/98555708-8d8ff400-22a2-11eb-9894-bccd1a694668.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 86.0.4240.183 x64
- Adblock Extension/version: uBO 1.30.9b12 + IDCAC 3.2.4

### Other details:

I propose `##.sticky-bottom-ad`

Without the entry: 
![image](https://user-images.githubusercontent.com/22780683/98557280-4c98df00-22a4-11eb-8b69-90c8720eed85.png)

**Comment by THEtomaso** [comment]
Also:
`rd.com##[data-ad-slot-name]`

Without the entry:

![filterissue-rd](https://user-images.githubusercontent.com/9382674/98574460-3dbc2780-22b8-11eb-8aac-57663a762e35.jpg)

**Comment by DandelionSprout** [comment]
Ah, right. I wasn't entirely sure if `RD` and `The Healthy` (The latter of which is in #6421) used the same publisher and same element names, but now it seems they do.

**Comment by THEtomaso** [comment]
> I wasn't entirely sure if RD and The Healthy used the same publisher and same element names, but now it seems they do.

You can add `tasteofhome.com` to that collection too.

**Comment by THEtomaso** [comment]
`birdsandblooms.com`
`familyhandyman.com`

**Comment by THEtomaso** [comment]
> https://github.com/easylist/easylist/commit/d4df793b59a35c1af59a126faebb4c9fe4f9b43b

You forgot to include these:
`##[data-ad-slot-name]` (alternatively `##.ad`)
and
`familyhandyman.com##.advertisement`
