### ISSUE TITLE
winaero.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#6423]
### List the website(s) you're having issues:
`https://winaero.com/download-winaero-tweaker/`

### What happens?
Advertisement placeholder and Social icons 
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/98580250-dfa83800-22e9-11eb-893a-44f1f33ffa45.png)

</details><br/>

### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List
### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 82.0.2
- Adblock Extension/version: uBlock Origin 1.30.6

**Comment by DandelionSprout** [comment]
I propose `winaero.com###main > div[style^="padding:"]` for the placeholder.
