### ISSUE TITLE
Pi-Hole

### ISSUE THREAD

**Issue by STUKguy** [easylist/easylist#6424]
Hi,

So i am currently using Adblock on my chorme browser, just wondering if there is away to ad the Easylist to my pi-Hole adblocker?

**Comment by DandelionSprout** [comment]
There's no official raw-domains or Hosts-file version of EasyList that could be imported straight into Pi-hole, but there's a few third-party conversions of it:

https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/easylist.txt by Austin Heap is probably the easiest one to add.

**Comment by STUKguy** [comment]
> There's no official raw-domains or Hosts-file version of EasyList that could be imported straight into Pi-hole, but there's a few third-party conversions of it:
> 
> https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/easylist.txt by Austin Heap is probably the easiest one to add.

Thank you I will try this now, the last list I tried broke comment sections on everything Facebook, YouTube etc

**Comment by STUKguy** [comment]
Wish there was someway to block YouTube ads

**Comment by krystian3w** [comment]
You can block some ~80,000 subdomains to avoid seeing ads on TV or smartphone with the official YouTube app.

The disadvantage is that someone has to keep expanding this list when they discover that some adverts have leaked again or that watching some films has accidentally broken down.

**Comment by STUKguy** [comment]
> You can block some ~80,000 subdomains to avoid seeing ads on TV or smartphone with the official YouTube app.
> 
> The disadvantage is that someone has to keep expanding this list when they discover that some adverts have leaked again or that watching some films has accidentally broken down.

I have been using the official Youtube App which is full of ads unless you pay to have them removed via Youtube subscription
