### ISSUE TITLE
Wrongly blacklisted: amazonaws.com/production

### ISSUE THREAD

**Issue by Vluf** [easylist/easylist#6427]
### List the website(s) you're having issues:

Rather wouldn't disclose this

### What happens?

The EasyPrivacy list is blocking our API endpoints, which is using AWS API Gateway under the hood. Due to this filter:
 ```
||amazonaws.com/production
```
See https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt#L105
and
https://github.com/easylist/easylist/commit/b7d89d6417166c6a247fdb782903db40781e2732

This very general filter blocks all APIs hosted on AWS API Gateway that use a very common, general "production" stage name.

### List Subscriptions you're using:

EasyPrivacy through uBlock Origin.

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 86.0.4240.193
- Adblock Extension/version: uBlock Origin 1.30.6

**Comment by eressler** [comment]
Our website is having this same issue. This is a big deal. I can't believe such a general and arbitrary url pattern would be included in a list that is used by so many.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/cb2323df12440a1403328f69cafa2bb2f68b64ef (and further changes)
