### ISSUE TITLE
saturn.de

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylist#6430]
I've found a (new) tracker for saturn.de

https://pvn.saturn.de/trck/eclick/e055856713020b10eb33c073a4aae6f8?url=http://www.saturn.de/de/shop/angebote/singles-day.html

My current filter rule to block this redirect:

`||pvn.saturn.de/trck/eclick/*$document`

or an aggressive way:

```
||*/eclick/*$document
||*/trck/*$document
```

**Comment by spirillen** [comment]
Wondering where you found this...  Do you happens to have a url to a page within the `saturn.de` where the tracker arise??

![image](https://user-images.githubusercontent.com/44526987/98837031-bc44d080-2442-11eb-8b9b-690fc9ab0a0a.png)

**Comment by crazyyzarc** [comment]
> 
> 
> Wondering where you found this... Do you happens to have a url to a page within the `saturn.de` where the tracker arise??
> 
> ![image](https://user-images.githubusercontent.com/44526987/98837031-bc44d080-2442-11eb-8b9b-690fc9ab0a0a.png)

Yeah here: https://stadt-bremerhaven.de/amazon-passt-teilweise-preise-an-singles-day-aktion-von-media-markt-und-saturn-an/

**Comment by crazyyzarc** [comment]
or: https://www.mydealz.de/deals/western-digital-black-sn750-nvme-1tb-m2-ssd-tlc-34703000-rw-1gbslc-cache-600tbw-5-jahre-garantie-media-saturn-1694762 -> https://urlex.org/https://www.mydealz.de/visit/thread/1694762 -> https://pvn.mediamarkt.de/trck/eclick/14f409770701ce2059f7dad29e68e337?subid=1150461999&url=https%3A%2F%2Fwww.mediamarkt.de%2Fde%2Fproduct%2F_wd-black%252525252525E2%25252525252584%252525252525A2-sn750-nvme%252525252525E2%25252525252584%252525252525A2-2519309.html

**Comment by spirillen** [comment]
Hey @crazyyzarc I most admit I can't get the ticker the rules unless I visit the last committed urls directly, Now I have been monitoring both my home DNSdist and the Squid proxy log and I have no logging of the `pvn.$domain` unless directly accessed. It is [AdWare](https://www.mypdns.org/w/adware/) and [TrackWare](https://www.mypdns.org/w/trackware/) as well but from my logs the crap from these seems to be served over the `static.$domain` while the `pvn.$domain` solely seems to be the management interface by `easy-m.de`

I have been scouting the source code of the sites as well, Can't find anything that can confirm you findings.

I'm starting to think this might be IP(country) related. Maybe someone else from Germany can help confirm this.

Personally I like to thanks you for your contribution, as it opened no less than 4 issues in my own project :smiling_face_with_three_hearts:
