### ISSUE TITLE
New Facebook Tracking Scripts?

### ISSUE THREAD

**Issue by throwaway282630101** [easylist/easylist#6431]
[NSFW] https://thereallisaann.com/2020/09/10/botcoin-bovada/

Seeing a script connecting and given an ID to Facebook is this tracking?
Even with Anti-Facebook filter on it still connects.

https://graph.facebook.com/?callback=WPCOMSharing.update_facebook_count&ids

Edit: Also "Possible trackers?" AdguardTeam/AdguardFilters#67708

**Comment by throwaway282630101** [comment]
@DandelionSprout Hi, sorry to bother you but are these new Facebook trackers?
Also "Possible trackers?" https://github.com/AdguardTeam/AdguardFilters/issues/67708

**Comment by DandelionSprout** [comment]
I do not specialise in trackers. Literally every other major adblock list contributor seem to know more about trackers than what I do.

**Comment by throwaway282630101** [comment]
Oh, sorry. Maybe @ryanbr can you help us?
