### ISSUE TITLE
Filter prevents links to some sites from opening in new tab

### ISSUE THREAD

**Issue by LurkerHub** [easylist/easylist#6445]
**Edit:** uBlock Origin worked around this issue in https://github.com/uBlockOrigin/uAssets/commit/d54cba58260938bf4d6945697cde2eae1cb6d9c5 so it may no longer be reproducible with the default settings

Originally reported on https://github.com/uBlockOrigin/uAssets/issues/8123

### Steps to reproduce

1. Create a new Firefox profile

2. install uBlock Origin

3. Go to `about:preferences#general`
Under "Tabs" check "When you open a link in a new tab, switch to it immediately"

### URL(s) where the issue occurs

4. Put the following into a file:
```
<a href="https://rarbg.to/torrents.php?search=tt0082398">rarbg</a><br>
<a href="https://thepiratebay.org/search/For%20Your%20Eyes%20Only%201981/0/99/200">the pirate bay</a><br>
<a href="https://www.torlock.com/all/torrents/For%20Your%20Eyes%20Only.html">torlock</a><br>
<a href="https://www.torrentdownloads.me/search/?search=For%20Your%20Eyes%20Only+1981">torrent downloads</a><br>
```
5. Load the file in Firefox.

6. Middle-click on the links to open them in a new tab.

### Describe the issue

When trying to open the links above in a new tab, the tab opens and immediately closes.
(opening in the same tab or in a new window works)

### List Subscriptions you're using:

The default subscriptions that come with uBlock Origin.

### Versions

- OS/version: Windows 10 version 1093
- Browser/version: Firefox developer edition 83.0b5 (64-bit)
- uBlock Origin version: v1.30.6

### Other details:

The same behaviour occurs when trying to open links to these and other sites from web pages, search engines, etc. in a new tab.
Using a local file is just for convenience of reproducing.

The problem only happens when `browser.tabs.loadInBackground` is set to `false` in step 3 above.

### Filter causing the issue
`/^https?:\/\/.*[&%+=]/$popup,domain=mixdrop.co|powvideo.net|powvldeo.cc|prox4you.xyz|putlocker.fyi|putlocker.ninja|putlocker.style|putlockers.fm|putlockers.mn|putlockers.movie|rarbg.to|rarbgaccess.org|rarbgmirror.com|rarbgmirror.org|rarbgmirrored.org|rarbgproxy.org|rarbgprx.org|rarbgunblock.org|rarbgway.org|readcomiconline.to|repelis.net|seehd.pl|sendit.cloud|sendspace.com|sendvid.com|sportp2p.com|steamplay.cc|streamplay.life|streamplay.to|thepiratebay.org|thepiratebay10.org|torlock.com|torrentdownloads.me|torrentfunk2.com|uiz.io|ukpirate.org|unblockall.org|unblocker.cc|up-load.io|upload.ac|uploadproper.com|uploadproper.net|upstream.to|uptobox.com|userscloud.com|vev.io|vidbull.tv|videobin.co|vidlox.me|vidoza.co|vidoza.net|vidtomp3.com|vidup.io|vipbox.live|vipstand.se|vshare.eu|y2mate.com|yify-movies.net|youwatch.org|youzik.com|zippyshare.com`

### Screenshot

![image](https://user-images.githubusercontent.com/20542915/98418958-09473200-2052-11eb-86c1-1441b4e5604f.png)

**Comment by LurkerHub** [comment]
uBlock Origin worked around this issue in https://github.com/uBlockOrigin/uAssets/commit/d54cba58260938bf4d6945697cde2eae1cb6d9c5 so it may no longer be reproducible with the default settings

**Comment by alexolog** [comment]
The problem is happening again.
