### ISSUE TITLE
huffpost.com

### ISSUE THREAD

**Issue by keithx2** [easylist/easylist#6446]
### List the website(s) you're having issues:

`https://www.huffpost.com/entry/big-brands-betting-on-silver-bullet-solution-plastic-crisis_n_5f9c74d4c5b6cfec2f6d8f6a`

### What happens?

Can't read comments on `huffpost.com` articles.  Clicking the comment icon on the left side of a page opens a side panel on the right that is blank.

### List Subscriptions you're using:

uBlock default

### Your settings

- OS/version:  Windows 8.1
- Browser/version: Firefox 83
- uBlock Extension/version: 1.30.6

### Other details:

Removing the following from EasyList allowed comments to appear in the side panel on `huffpost.com` articles:

`huffpost.com###spotim-specific`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/7482f71715c6a329203f16a491a16cc9ee02feb4
