### ISSUE TITLE
edge.curalate.com/v1/img & edge.curalate.com/v1/vid

### ISSUE THREAD

**Issue by tkmcc** [easylist/easylist#6460]
### List the website(s) you're having issues:

```
https://edge.curalate.com/v1/img/KfuZr1anjZG0nLWSBdldANXTZt1W2AYerfr1rqfH8ug=
https://edge.curalate.com/v1/vid/EHo_1HLwB7yHxlkI3E7qCpEzFBcSxk5qo2azZIAHmfQ=
```

### What happens?

Emails that embed images and videos hosted on our CDN (edge.curalate.com) fail to render because they are caught by this easyprivacy rule `||curalate.com^$third-party`: https://github.com/easylist/easylist/blob/7575e8082c101e2a6e3db701b9206c6b40e8321f/easyprivacy/easyprivacy_trackingservers.txt#L622

### Other details:

Existing rule: https://github.com/easylist/easylist/blob/7575e8082c101e2a6e3db701b9206c6b40e8321f/easyprivacy/easyprivacy_trackingservers.txt#L622

We suggest to add these rule exceptions so that static media can be served while still leaving JS hosted by the same domain blocked. Please confirm these work as anticipated and will allow third-party site embeds:

```
@@||edge.curalate.com/v1/img^
@@||edge.curalate.com/v1/vid^
```

Thank you!

**Comment by spirillen** [comment]
Those are tracking url's... 

Personally I don't like the idea of letting you get away with that. Myy personal vote goes to keeps you blocked, and if any addicted user would like your spyware, then that individual user should whitelist your domain.

There are plenty of reports saying you are to be on any blacklist:

<https://www.mypdns.org/T2547>

<https://github.com/disconnectme/disconnect-tracking-protection/issues/145>

<https://github.com/easylist/easylist/issues/4512>

<https://github.com/easylist/easylist/pull/4513>

My 2 cent

**Comment by tkmcc** [comment]
Hi spirillen,

Thanks for the response. The URLs in the links you shared are referencing minified Javascript and event tracking endpoints, while the exclusion paths I provided in this issue are strictly for static image and video content hosted under the same top-level domain. This change would support a different use-case than the Javascript galleries the linked issues reference, and are for directly embedding images and videos in static HTML.

I understand your concern for user privacy, as I use uBlock Origin with the easyprivacy list myself, which is how I noticed this block. With that in mind, we tried to follow best practices to scope the exclusion paths to be as specific as possible and not to just request removing our domain from the list entirely. Can you help us understand what a sufficient approach would be in this case?

Thank you

**Comment by spirillen** [comment]
Well there are at least two scenarios.

1. Regarding this repo, you'll await @ryanbr or who else comes around from the admin group :wave: .
2. Regarding the RPZ zones at <https://www.mypdns.org/T2547>, you specify all your domains and purposes, then We will review them and see if they can be listed individually rather than the current wildcard. But the [rule](https://www.mypdns.org/Q12) is clear.... and rather square as the DNS system it self.
    When this is said, I would welcome more in-depth knowledge from your side, and do my best to allow what is to be allowed. We are not as square headed as some believes and tells other :wink: :smirk:

**Comment by ryanbr** [comment]
@tkmcc 

I may revert this block, but you need to remove the tracking pixels/events off the main domain.  Looking at `https://cdn.curalate.com/sites/wswestelm-i5hqoo/site/latest/site.min.js`

See my previous post: https://github.com/easylist/easylist/issues/4512

**Comment by ryanbr** [comment]
re-open ticket when this changes @tkmcc
