### ISSUE TITLE
Add X-Mode Social to blocklists

### ISSUE THREAD

**Issue by corbindavenport** [easylist/easylist#6467]
Vice wrote a story recently about how data broker X-Mode Social pays mobile apps to include its SDK, which then gives it location data that it sells to third parties: https://www.vice.com/en/article/jgqm5x/us-military-location-data-xmode-locate-x

I found this tweet from earlier this year, which seems to indicate X-Mode is using api.myendpoint.io, and was previously using bin5y4muil.execute-api.us-east-1.amazonaws.com: https://twitter.com/craiu/status/1244355903111016448

I downloaded one of the affected apps from the Vice article, [Global Storms](https://play.google.com/store/apps/details?id=com.kellytechnology.NOAA_Now), and my DNS logs show it is sending data to myendpoint.io. I think that domain should be added to EasyPrivacy and any other applicable lists.

![image](https://user-images.githubusercontent.com/3879063/99422207-4ec6f300-28cd-11eb-8c83-d4236b783d8a.png)

**Comment by ryanbr** [comment]
Example sites are needed

https://publicwww.com/websites/%22sense360eng.com%22/  (0 results, no websites)
https://publicwww.com/websites/%22myendpoint.io%22/       (0 results, no websites)
https://publicwww.com/websites/%22crashlytics.com%22/      (Many results, no scripts loaded, nothing active)
https://publicwww.com/websites/%22app-measurement.com%22/  (2 results, nothing active)

**Comment by corbindavenport** [comment]
I believe it's only a native mobile app SDK (all the documentation is invite-only), so there won't be any websites with it. You can see network requests from it by installing an app with the SDK, like Global Storms: https://play.google.com/store/apps/details?id=com.kellytechnology.NOAA_Now
