### ISSUE TITLE
bitreporter.de

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylist#6468]
### List the website(s) you're having issues:
`https://bitreporter.de/amazon-devices/windows-10-bildschirm-auf-amazon-firetv-spiegeln/`

### What happens?
It shows me still advertizing for Amazon. How do I remove embedded href advertizing?

### List Subscriptions you're using:
EasyList, uBlock default lists, AdGuard etc.

### Your settings

- OS/version: W10x64 RB 20H1
- Browser/version: Firefox Browser 83.0
- Adblock Extension/version: uBlock Origin 1.30.11rc0

### Other details:

![2020-11-18 07_36_44-](https://user-images.githubusercontent.com/4954535/99495108-6d32fa00-2972-11eb-8a26-f888c6930878.png)
![2020-11-18 07_48_22-Window](https://user-images.githubusercontent.com/4954535/99495147-7fad3380-2972-11eb-9e9c-9424f33d8a6b.png)

**Comment by Khrin** [comment]
hi @crazyyzarc , recently some filters were added and i do not see banners anymore. (https://github.com/easylist/easylistgermany/commit/90dd14edac0a9d97b3cf7dfcc72449fb7c7fe4d1)
please update your filters lists. (and next time, for german sites please report to https://github.com/easylist/easylistgermany)
