### ISSUE TITLE
AVforums.com still detects UBlock

### ISSUE THREAD

**Issue by cns2020** [easylist/easylist#6469]
AVforums still produces the stroppy notice when using UBlock Origin:

"{username}, because we have detected that you are, or have recently been blocking adverts, your account has been limited. Click here to find out how and why your account has been limited. Learn how to whitelist AVForums and then clear the flag on your account.
Thank you."

**Comment by Yuki2718** [comment]
@cns2020 Please do not skip filling in the template.

**Comment by krystian3w** [comment]
EasyList no fix anti-adblock mechanisms.
