### ISSUE TITLE
Add a regex to block genieesspv CNAME tracker

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#6471]
### List the website(s) you're having issues:

```
http://deliciousicecoffee.jp/
https://www.minkou.jp/university/school/20722/
http://news-select.net/
```
and many more

### What happens?

Unblocked tracker like:

```
http://js.rush-member.com/t/267/834/a1267834.js
https://js.mediams.mb.softbank.jp/t/129/052/a1129052.js
http://js.passaro-de-fogo.biz/t/113/747/a1113747.js

```

### List Subscriptions you're using:

uBO default

### Your settings

- OS/version: Windows 10
- Browser/version: Brave 1.16.76
- Adblock Extension/version: 1.30.6

### Other details:

Here's a bit old list of genieesspv CNAME tracker:
`https://ln2.sync.com/dl/37297af50/view/text/10550679950008#qm9yf8hs-vk8m52pe-5ruzkqn9-ssa6cv2b`
Not all of them are actually in use and some are blocked by domain rules, others can't be caught by the regex even if its domain part is expanded. But most common ones will be caught by the regex. The rationale for regex is apparently they've been adding domains but the pattern is mostly the same (so far adjusted only once after added to AdGuard Tracking list: https://github.com/AdguardTeam/AdguardFilters/issues/58587#issuecomment-656098019).

**Comment by ryanbr** [comment]
Okay, does this help? @Yuki2718 

`/^https?:\/\/js.*\/t\/[0-9]{3}\/[0-9]{3}\/[a-z0-9]{7,8}\.js/$script,third-party`

**Comment by Yuki2718** [comment]
@ryanbr The last part needs to be `[a-z0-9]{8,10}` or `a[0-9]{7,9}`, I couldn't find my adjustment commit yesterday but have now found: https://github.com/AdguardTeam/AdguardFilters/commit/8fd0f28cf5672958e57df039073dbeadebcf7d67
This was a previously unseen domain and pattern: `https://js.boost-next.co.jp/t/004/243/a100004243.js`

Also I think `\.[-.0-9a-z]+` will be enough instead of `.*` as this is domain part. At `https://regex101.com/`, `\.[-.0-9a-z]+` version is 26 steps for `https://js.boost-next.co.jp/t/004/243/a100004243.js` (match case) while `.*` one 51 steps and for `https://js.driftt.com/include/1605765900000/a6yri4b82zv7.js` (no match) 15 vs. 65 steps. I'm following arguments here: https://github.com/uBlockOrigin/uAssets/commit/f9e6631233df876c08bf17f82c3f20a2008f176c#commitcomment-43910835

So my proposal is
`/^https?:\/\/js\.[-.0-9a-z]+\/t\/[0-9]{3}\/[0-9]{3}\/a[0-9]{7,9}\.js$/$script,third-party`
or
`/^https?:\/\/js\.[-.0-9a-z]+\/t\/[0-9]{3}\/[0-9]{3}\/[a-z0-9]{8,10}\.js$/$script,third-party`
