### ISSUE TITLE
Request to add Marketo email tracking domains

### ISSUE THREAD

**Issue by pgl** [easylist/easylist#6475]
Request to add rule to block Marketo tracking domains.

These domains are created for each customer, hidden behind CNAMEs from the customer domains.

Searching on https://dnpedia.com/tlds/search.php shows that there are currently over 25,000 of them.

The format is in `mkto-<something>.com` (usually <something> is letters followed by numbers).

Details and example here: https://docs.marketo.com/display/public/DOCS/Configure+Protocols+for+Marketo

2. Add CNAME for Email Tracking Links
Add the email CNAME marketing sent you, so that [YourEmailCNAME] points to [MktoTrackingLink], the default tracking link that Marketo assigned, in the format:
[YourEmailCNAME].[YourDomain].com IN CNAME [MktoTrackingLink]
For example:
pages.abc.com IN CNAME mkto-a0244.com

It's been suggested to avoid a regex filter rule as they're expensive, and stick with something like:

`||mkto-*.com^$third-party`

This covers all the entries and as far as I know will not match any false positives.

**Comment by krystian3w** [comment]
Possible add to own project?

https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=0&mimetype=plaintext

Maybe few people use translated file.

**Comment by pgl** [comment]
@krystian3w I mean, I considered it - but it would be 25,000 new entries to my list, which only has ~3.5k entries at the moment, versus 1 rule in EasyList.

**Comment by krystian3w** [comment]
Just write script to add in only:

`hostformat=adblockplus`

one ABP rule.

**Comment by pgl** [comment]
"Just"

**Comment by spirillen** [comment]
Hey Peter @pgl In case you find more of this kind in the future, I'll be more than happy to receive a copy :smiley: 

And yeah, hmm 3500 lines vs 3 (1) :rofl: but I do the the backside of this coin... not all devices can be using the @EasyList but would have to stick to a I/O expensive hosts file.

PS: Your project would actually be within the target group of what @funilrys and I are building on. Would it be possible to hit you up on keybase or somewhere else for a small talk?

**Comment by pgl** [comment]
@spirillen Sure: https://keybase.io/pgl
