### ISSUE TITLE
ghacks.net

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#6478]
### List the website(s) you're having issues:

`https://www.ghacks.net/2020/11/18/thunderbird-78-5-0-is-now-available/`
### What happens?

Advertisement placeholder 
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/99711058-80a5a880-2acb-11eb-86f8-69df33e3127e.png)

</details><br/>
### List Subscriptions you're using:
Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 83.0
- Adblock Extension/version: uBlock Origin 1.30.6

**Comment by ryanbr** [comment]
I'm not seeing this @SeriousHoax

**Comment by SeriousHoax** [comment]
> 
> 
> I'm not seeing this @SeriousHoax

I'm not seeing it anymore either. Sorry about, not sure what happened. Closing it.
