### ISSUE TITLE
Would you consider preventing cf rocket loader side loading scripts? 

### ISSUE THREAD

**Issue by kasper93** [easylist/easylist#649]
Hi,

Rocket Loader load scripts from page cache. It can load multiple scripts in one request, sound good, but it bypass whole filter list by doing so. 

Let's consider this request as example:
```
https://naekranie.pl/cdn-cgi/pe/bag2?r[]=https%3A%2F%2Ftvn.adocean.pl%2Ffiles%2Fjs%2Fado.js&r[]=https%3A%2F%2Fcont2.naekranie.pl%2Fwp-content%2Fthemes%2Fnaekranie%2Fbower_components%2Fjquery%2Fdist%2Fjquery.min.js&r[]=https%3A%2F%2Fcont2.naekranie.pl%2Fwp-content%2Fplugins%2Fsocialfans-counter%2Fassets%2Fjs%2Fsocialfans-script.js&r[]=https%3A%2F%2Fcont2.naekranie.pl%2Fwp-content%2Fplugins%2Fduracelltomi-google-tag-manager%2Fjs%2Fgtm4wp-outbound-click-tracker.js&r[]=https%3A%2F%2Fcont2.naekranie.pl%2Fwp-content%2Fplugins%2Fduracelltomi-google-tag-manager%2Fjs%2Fgtm4wp-download-tracker.js&r[]=https%3A%2F%2Fcont2.naekranie.pl%2Fwp-content%2Fplugins%2Fduracelltomi-google-tag-manager%2Fjs%2Fgtm4wp-email-link-tracker.js&r[]=https%3A%2F%2Fcont2.naekranie.pl%2Fwp-content%2Fplugins%2Fduracelltomi-google-tag-manager%2Fjs%2Fgtm4wp-form-move-tracker.js&r[]=https%3A%2F%2Fcont2.naekranie.pl%2Fwp-content%2Fplugins%2Fduracelltomi-google-tag-manager%2Fjs%2Fgtm4wp-social-tracker.js&r[]=https%3A%2F%2Fcont2.naekranie.pl%2Fwp-content%2Fplugins%2Fduracelltomi-google-tag-manager%2Fjs%2Fgtm4wp-youtube.js&r[]=https%3A%2F%2Fcont2.naekranie.pl%2Fwp-content%2Fplugins%2Fduracelltomi-google-tag-manager%2Fjs%2Fanalytics-talk-content-tracking.js
```
It will load all those scripts regardless if they would be blocked otherwise. Some of them are ads, some tracking and the rest normal page scripts. But there is easy fix
```
/cdn-cgi/pe/bag2^$xmlhttprequest,first-party
```
We can just block all those requests, rocket loader will then fallback to normal request which will be processed and filtered as expected by the blocker. I suggest doing it globally, because fixing sites one by one is basically reinventing the wheel. It is impossible to do proper rules for each site using rocket loader. And since the scripts are mixed, we will end up blocking whole requests anyway.

I tested it with few sites and it works great, bringing back ability to block scripts according to the filters.

I see that easylist have some `bag2` filters, but I feel like it is just a small subset of things that should actually be blocked. We cannot let side loading scripts like that.

**Comment by ryanbr** [comment]
WIll cause issues if blocked outright, websites will break.
