### ISSUE TITLE
news.hiphopearly.com

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#65]
https://forums.lanik.us/viewtopic.php?f=62&t=30493

**Comment by monzta** [comment]
I don't see how that would fit into the social list. Custom filter: `||carambo.la^$third-party`

**Comment by terrorist96** [comment]
@monzta it seems to me that it's an ad, not something for social or annoyance list.
http://carambo.la/

"Incremental revenue through engaging content"
