### ISSUE TITLE
marketscreener.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6500]
### List the website(s) you're having issues:

`https://www.marketscreener.com/quote/currency/EURO-BRITISH-POUND-EUR-4593/news/BREXIT-UK-S-SUNAK-SAYS-WE-SHOULD-NOT-BE-GOING-FOR-A-DEAL-AT-ANY-PRICE-31843170/`

### What happens?

Placeholder near the bottom.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/99901273-ba3a0780-2cb5-11eb-8a35-1b4197ab1416.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 87.0.4280.66 x64
- Adblock Extension/version: uBO 1.31.1b2 + IDCAC 3.2.5

### Other details:

I propose `marketscreener.com##.myFooter`

**Comment by THEtomaso** [comment]
There is `###sticky-Left1`/ `###sticky-Left1-anchor` too (on the right side, despite their names).
This should cover both:
`marketscreener.com##[id^="sticky-Left"]`

**Comment by DandelionSprout** [comment]
Appears to have been fixed in AdGuard Base by now, from what I can determine.
