### ISSUE TITLE
fxempire.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6501]
### List the website(s) you're having issues:

`https://www.fxempire.com/news/article/covid-19-vaccine-update-pfizer-inc-submits-an-eua-684447`

### What happens?

Various placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/99901273-ba3a0780-2cb5-11eb-8a35-1b4197ab1416.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 87.0.4280.66 x64
- Adblock Extension/version: uBO 1.31.1b2 + IDCAC 3.2.5

### Other details:

![image](https://user-images.githubusercontent.com/22780683/99901354-7abfeb00-2cb6-11eb-85d6-e15094d47a03.png)

I'll be honest and say that I have no idea which entries to suggest (apart from `fxempire.com##[class*=TopButtonAd__AdDesktopBox-]` for the topmost one), because that site is using some very tricky class-names.

**Comment by THEtomaso** [comment]
> that site is using some very tricky class-names.

An `-abp-` fix would be justifiable in this case.
`fxempire.com#?#[class^="Card-sc-"]:-abp-contains(Advertisement)` seems safe.
..whilst `fxempire.com#?#[class^="Card-sc-"]:-abp-contains(Sponsored)` is debatable, I guess.
