### ISSUE TITLE
EasyList Cookie List [Question]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#6506]
Is it still OK to post issues for **EasyList Cookie List** @ the **fanboy-adblock** repo?:
https://github.com/ryanbr/fanboy-adblock/issues/

I only ask because I've got a rather large amount of unsolved reports there.
It shouldn't take too long to fix those issues, since all of my reports includes suggestions for fixes, thereby making them more or less copy/paste jobs.

Would you prefer if I closed those reports, and reposted them here @ the **easylist** repo?

**Comment by ryanbr** [comment]
Here is fine
