### ISSUE TITLE
grammarly.com

### ISSUE THREAD

**Issue by revohri** [easylist/easylist#6508]
### List the website(s) you're having issues:
`https://www.grammarly.com/`

### What happens?
I am a site owner for Grammarly. On the Brave browser, some of our internal event tracking and frontend metrics / error logging endpoints are being blocked.

![image](https://user-images.githubusercontent.com/747888/99999533-2596de80-2d75-11eb-9c45-347443d4a462.png)

These are essential for our business to be able to run A/B tests, track performance data and errors across our site.

Currently, all of these are blocked in the Brave browser, which uses easylist to make this determination. The brave team recommended opening an issue here to get these endpoints unblocked.

The endpoints are:
`https://gnar.grammarly.com/events`
`https://f-log-at.grammarly.io/log`

### Your settings

- OS/version: MacOS + Windows
- Browser/version: Brave
- Adblock Extension/version: N/A

**Comment by spirillen** [comment]
Do you have the slightest clue what this list is about @revohri ?

**Comment by THEtomaso** [comment]
Hang on for the "we don't collect any personal data" reply, spirillen. :)

**Comment by llacb47** [comment]
LOL. Take your keylogger extension somewhere else.

**Comment by spirillen** [comment]
> Hang on for the "we don't collect any personal data" reply, spirillen. :)

@Thetomaso Didn't say anything even close to that :wink:

**Comment by THEtomaso** [comment]
I was simply predicting the OP's answer.

**Comment by ryanbr** [comment]
We should all remain professional, @revohri is querying these filters

Easyprivacy by default will block event/performance trackers, Can you make these domain urls not publicly facing? @revohri

**Comment by spirillen** [comment]
> I was simply predicting the OP's answer.

I know, was just following along on the internal joke, I did understand it :smile:

**Comment by revohri** [comment]
@spirillen 

> Do you have the slightest clue what this list is about @revohri ?

We were referred here by the Brave browser team that said this:
"Brave blocks Grammarly analytics through EasyPrivacy so we would like you to petition to get it off through them."

> On the other hand, it's a bit hard to verify...
504 Gateway Time-out

Yes, our website went down this morning due to an outage of cloudwatch on the amazon side. Apologies for the inconvenience! We should be back up now.

@ryanbr - thanks for pushing for professionalism - much appreciated!
> Easyprivacy by default will block event/performance trackers

Makes sense. Is there a provision for adding overrides or guidelines for what is required to make that possible?

> Can you make these domain urls not publicly facing?

Can you elaborate a bit more on what would be required here?

**Comment by ryanbr** [comment]
> Can you elaborate a bit more on what would be required here?

Use different event tracking urls, not seen by users on the website. Maybe only applicable if the user is auth'd on the website

**Comment by revohri** [comment]
@ryanbr - I'm still not sure I understand why we would be required to log our tracking events in a way that would be invisible in the network logs and to the end-user if they open up the network tab. Is the goal here to bypass easylist from being able to block these requests?
Are you referring to a solution similar to GTM here? 

Further, is this the only option wrt unblocking these URLs?
You raised an interesting point around auth'd users vs non-auth'd users. Is there any way to unblock the current tracking solution for users that have auth'd and agreed to our TOS?

**Comment by DRSDavidSoft** [comment]
@revohri Hi, and thanks for the great extension.

As a user, I really don't want my extensions to communicate with the servers in order to transfer analytics, metrics, or any other kind of logs.  I would like the extension to only transfer authentication, documents data and misspelling, etc back to the server.

Is this kind of logging really necessary?  I love the fact that uBlock Origin is blocking this kind of communication when Grammarly is installed.

I don't want this behavior to be removed from the EasyList, as the end-user.

**Comment by revohri** [comment]
@DRSDavidSoft - thanks for the appreciation!

A couple of points of explanation:

- I created this issue to discuss the tracking of analytics and metrics on our website - `grammarly.com` and not for our extension or other products.
- On our website, we use this tracking to better understand and optimize our purchase and authentication flows, and collect data on web performance.

**Comment by chirag127** [comment]
> > Do you have the slightest clue what this list is about @revohri ?
> 
> We were referred here by the Brave browser team that said this:
> "Brave blocks Grammarly analytics through EasyPrivacy so we would like you to petition to get it off through them."
> 
> >

I think we should create an issue on brave, so that they stop referring these kinds of issues here.

**Comment by ryanbr** [comment]
Closing this issue. But I was able to login into https://app.grammarly.com/ in Brave Beta, but sure log a report if you have issues.
