### ISSUE TITLE
Issue with AdBlock extension and Astra Pro plugin.

### ISSUE THREAD

**Issue by shubhw12** [easylist/easylist#6509]
Hello,

Greetings for the day!

I am Shubham from the Astra theme development team.

[Astra](https://wordpress.org/themes/astra/) is a WordPress theme and has more than 1 million active installations.

Astra Pro is our addon plugin which provides premium features to our pro customers.

We have been receiving queries from the users regarding the modules/functionality that we provide. These features do not work at all in case if the AdBlock is active.

This is because to implement these features we use Javascript. In one of your recent changes, you have included our script in one of your ad-block list.

Reference commit: https://github.com/easylist/easylist/commit/eee9924

Could you please let us know why the script is being included in the AdBlock list?

This change is affecting a lot of Astra users and we are receiving queries for the same.

Let us know if we can assist you to resolve this as soon as possible.

Looking forward to hearing back from you soon.

**Comment by ryanbr** [comment]
Has been removed, update your lists.
