### ISSUE TITLE
https://www.takealot.com

### ISSUE THREAD

**Issue by jwatkyns** [easylist/easylist#6512]
### List the website(s) you're having issues:
https://www.takealot.com

### What happens?
The blocking of collect breaks their pickup points on checkout.

Add anything to cart and choose pickup points on checkout
### List Subscriptions you're using:

EasyList

### Your settings

- OS/version:  Windows 10
- Browser/version: Chrome 87
- Adblock Extension/version: Adblock 4.24.0

### Other details:

![image](https://user-images.githubusercontent.com/22814453/100200444-4abb5680-2f07-11eb-902f-050c803e387b.png)

That is the line that is causing it. Maybe if it can be narrowed down to ensure it only blocks the user tracking stuff

**Comment by DandelionSprout** [comment]
Seems to me to be a problem with EasyPrivacy instead of EasyList.

The only tracker file that seems to be affected by `||takealot.com^*/collect` is `https://api.takealot.com/rest/v-1-9-1/collect`, so narrowing it down wouldn't be easy either.
