### ISSUE TITLE
thepigeonexpress.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6513]
### List the website(s) you're having issues:

`https://www.thepigeonexpress.com/donald-duck-mickey-mouse-accidentally-summoned-by-uk-court/`

### What happens?

Various placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/100222730-cf63a000-2f1a-11eb-9154-e09fa5d053f9.png)
![image](https://user-images.githubusercontent.com/22780683/100222887-0639b600-2f1b-11eb-9d42-9bba8ed9d1b9.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 87.0.4280.66 x64
- Adblock Extension/version: uBO 1.31.1b4 + AdGuard for Windows 7.5.3 + IDCAC 3.2.5

### Other details:

I propose:
```
thepigeonexpress.com##div[class^=thepi-mobile-]
thepigeonexpress.com##body > p
thepigeonexpress.com##.thepi-after-content > p
```

Without the entries: 
![image](https://user-images.githubusercontent.com/22780683/100222954-24071b00-2f1b-11eb-92cf-4e57ccbf52e4.png)

**Comment by ryanbr** [comment]
Too minor to consider tbh.
