### ISSUE TITLE
betterworldbooks.com - Missing Menu/toolbar when Easylist Cookie filter list is active

### ISSUE THREAD

**Issue by warp16** [easylist/easylist#6516]
### List the website(s) you're having issues:

`https://www.betterworldbooks.com/`

### What happens?

Top toolbar of the site, including it's search bar, are missing, *specifically when the "Easylist Cookie" filter list is enabled in uBlock Origin*

### Your settings

No other privacy related extensions

- OS/version: Windows 10 x64 2004
- Browser/version: Issue affects both FF 83 & Chrome 87.0.4280.66
- Adblock Extension/version: uBlock Origin 1.31.0

### Other details:

Easylist Cookie filter list enabled:

![image](https://user-images.githubusercontent.com/12633352/100319566-d4ae0280-2f8d-11eb-86cc-97f6c729f21f.png)

Easylist Cookie filter list disabled:

![image](https://user-images.githubusercontent.com/12633352/100319644-f7d8b200-2f8d-11eb-93f2-9cb3d3904027.png)

**Comment by THEtomaso** [comment]
### Problem filters:
* **EasyList Cookie List**
* **Fanboy's Annoyance List**

### Problem rule:
`/cookienotice.`

### Blocked script:
`https://www.betterworldbooks.com/app/components/cookieNotice.js`

### Possible fix (already present in **AdGuard Annoyances** filter):
`@@||betterworldbooks.com/app/components/cookienotice.js`

### Other problem filters:
* **I don't care about cookies** (@kiboke)
`/cookienotice.js`

**Comment by kiboke** [comment]
@THEtomaso thank you, it will be fixed!
