### ISSUE TITLE
https://www.google.com/

### ISSUE THREAD

**Issue by JaapJoris** [easylist/easylist#6532]
### List the website(s) you're having issues:

`https://www.google.com/`

### What happens?

The filter lists under "Annoyances" fail to block the cookie popup banner on all Google domains. This is the popup I'm getting:

![google](https://user-images.githubusercontent.com/9511578/100408229-be29a900-306a-11eb-83b7-df972a252ae5.png)

### List Subscriptions you're using:

All of them, in particular all Annoyances, including `EasyList Cookie`:

![filters](https://user-images.githubusercontent.com/9511578/100408339-0a74e900-306b-11eb-8002-cf3ba876aeb8.png)

### Your settings

- OS/version: Linux 5.6.0-2-amd64 #1 SMP Debian 5.6.14-1 (2020-05-23)
- Browser/version: Chromium Version 83.0.4103.116 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)
- Adblock Extension/version: uBlock Origin v1.30.0

### Other details:

I suspect the filter list `EasyList Cookie` is failing to block Google cookie popup. This is the version I'm using:

```
[Adblock Plus 2.0]
! Checksum: e8ceYCgllJL4zqQrhh59qw
! Title: Easylist Cookie List
! Updated: 25 Nov 2020
```

**Comment by krystian3w** [comment]
Locked scroll, so out of Scope for `Easylist Cookie List`.

Poland use these for uBlock Origin:

```
! older uBO
www.google.com,www.google.pl##body.QVCmK:style(position: static !important; overflow-y: visible !important;)
www.google.com,www.google.pl###lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7)
www.google.com,www.google.pl###lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"])
```

```
! uBO 1.26.0+
www.google.com,www.google.pl###lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7):remove()
www.google.com,www.google.pl###lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"]):remove()
```

**Comment by ryanbr** [comment]
Yeah, closing. Would break scrollbar
