### ISSUE TITLE
pricerunner.dk

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6535]
### List the website(s) you're having issues:

`https://www.pricerunner.dk/pl/94-4675606/Hoeretelefoner/Sony-WH-1000XM3-Sammenlign-Priser`

### What happens?

After around 5secs and slightly scrolling down, what seems to be a notification prompt shows up in the lower right, even when Fanboy's Notifications Blocking List is turned on.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/100462957-5d7e8880-30cb-11eb-8154-229c91791525.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 87.0.4280.66 x64
- Adblock Extension/version: uBO 1.31.1b6 + IDCAC 3.2.5

### Other details:

I'm not entirely sure if their prompt actually works or not, since it doesn't make the browser itself ask whether to receive notifications.

I propose `pricerunner.dk,pricerunner.se#?#div[aria-describedby=dialogText]:-abp-has(img[src*="/illustration-signup-"])`

![image](https://user-images.githubusercontent.com/22780683/100462824-1e503780-30cb-11eb-91cb-98c4605c5d71.png)

**Comment by ryanbr** [comment]
What are we blocking on this site?

**Comment by DandelionSprout** [comment]
The "Må vi holde dig opdateret?" prompt in the lower right.

**Comment by DandelionSprout** [comment]
@ryanbr @Khrin Is it possible to get this report out of limbo if I told you guys there's now also a UK English site version that should avoid any kind of language confusion?

Example page: `https://www.pricerunner.com/pl/1583-4969879/Nintendo-Switch-Games/Animal-Crossing-New-Horizons-Compare-Prices`

![torsk](https://user-images.githubusercontent.com/22780683/136220576-f05898cf-0463-48ab-aa49-85782a372985.png)

**Comment by DandelionSprout** [comment]
It's a pretty tricky one to block, so `pricerunner.com,pricerunner.dk,pricerunner.se##div[class*=" "][aria-labelledby="dialogHeading"]` is the best I can come up this morning.

**Comment by ryanbr** [comment]
Maybe we can review this later, with a better filter.
