### ISSUE TITLE
MapQuest API not an ad service

### ISSUE THREAD

**Issue by shoesCodeFor** [easylist/easylist#654]
Hi, the URL mapquestapi.com/logger/ should not be on the list of blocked URLs.  This is a transaction counter for map tiles used by the MapQuest API.  This API does not have advertising on it.  This endpoint does not log user interaction or location without expressed permissions for mapping purposes.  It only logs the amount of tile transactions used (served) under a specific API key.

**Comment by peace2000** [comment]
This entry seems to be on the Easyprivacy list. Can you give more detailed steps to reproduce this issue? What pages uses that api? Do they need an account?

**Comment by Khrin** [comment]
A new issue report can be opened, if necessary.
