### ISSUE TITLE
[breakage] [fanboy social] joemonster.org

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#6541]
### List the website(s) you're having issues:

 

[](https://github.com/AdguardTeam/AdguardFilters/issues/68648)

```
https://joemonster.org/mg/lastup/list#pic-259944
```

### What happens?

Hidden is not social related vote up button "daj głos" and button to load comments:

![obraz](https://user-images.githubusercontent.com/35370833/100485045-f5499a00-30fe-11eb-90e5-326cd8c08b01.png) |
--- |

### List Subscriptions you're using:

Fanboy's Social Blocking List

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 83
- Adblock Extension/version: ABP 3.10

### Other details:

bad: https://github.com/easylist/easylist/blob/d18eb08f24d614a959659edab9c213a2400c4636/fanboy-addon/fanboy_social_general_hide.txt#L11204

fix:

```
joemonster.org#@#.socialcontainer
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/447b344723ba21dfba20cb2e9221f13f00479364

**Comment by krystian3w** [comment]
@ryanbr I mistake size of letters, this use `C`:

```diff
-joemonster.org#@#.socialcontainer 
+joemonster.org#@#.socialContainer
```
