### ISSUE TITLE
animepornxxx.com [NSFW]

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#6543]
### List the website(s) you're having issues:

`animepornxxx.com`

### What happens?

Exit pup(up|under)

### List Subscriptions you're using:

Plenty

### Your settings

- OS/version: Tor
- Browser/version: Tor
- Adblock Extension/version:

**Comment by spirillen** [comment]
PS, this is also a [cdngangsta](https://www.mypdns.org/T2355) driven site....

**Comment by ryanbr** [comment]
Like the other issue report, but pulled some adservers.
