### ISSUE TITLE
[NSFW] Exit scripts

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#6553]
### List the website(s) you're having issues:

```
japansporno.com
analwithteens.sexy
analxxxvideo.com
sexmomsex.com
shinyjapaneseporn.com
drivepornvideos.com
animepornfilm.com
sexmomsex.com
shinyjapaneseporn.com
japansporno.com
freerealvideo.com
indianpornvideo.online
amateursolution.com
amazingvintagesex.com
japanxxx.asia
asiansex.sexy
```

### What happens?

Exit scripts redirects to other CJ sites

### Your settings

- OS/version: Tor
- Browser/version: 
- Adblock Extension/version: 

### Other details:
See also:

https://github.com/easylist/easylist/issues/6543

https://github.com/easylist/easylist/issues/6449

https://github.com/easylist/easylist/issues/6200

https://github.com/easylist/easylist/issues/6041

https://github.com/easylist/easylist/issues/6015

**Comment by ryanbr** [comment]
I don't think its fixable, its basically porn ad sites, linking to more ad sites.

**Comment by THEtomaso** [comment]
Yeah, the best solution would be to simply block all of those sites!

**Comment by spirillen** [comment]
> Yeah, the best solution would be to simply block all of those sites!

Then you just subscribe to the [adult.mypdns.cloud](https://www.mypdns.org/w/rpzlist/#adult-mypdns-cloud) RPZ zone :rofl: But I can see @Yuki2718 have been cooking on something :100:

**Comment by Yuki2718** [comment]
I actually wondered a bit to totally block some of them, but some pages have contents and it's impossible to distinguish which have and which not.

**Comment by spirillen** [comment]
Well they are all [cdngangsta.com](https://www.mypdns.org/T2355) sites, linking to each other in a never ending circle and from the way the behave, I can only say, I'm happy I only had to visit them once and the content is the same, just a different logo and CSS.

PS: I think you have forgotten to add something similar to:
```
! 2020-11-14 animeporn.xyz
/out.php$document,domain=animeporn.xyz|hot-animal-porn.biz|horse-sex.xyz|freeanimalporn.xyz|hentaisexuality.com|3dsextales.icu|greentoons.club|dirtynudeteens.net,important

! 13/04/2020 animal-sex-movie.biz, https://www.mypdns.org/T2743
/tp/out.php
```

This is the "clickjail" script by ScriptPulse <http://www.scriptpulse.com/tp/manual/outgoing-links.php>

**Comment by Yuki2718** [comment]
@spirillen That only adds strict-blocking. I already addressed automatic redirect for some domains, but TBH not much wanna spend more time for those gar*a*e. Will add only a few domain later.
