### ISSUE TITLE
Netgear CM1000 event log broken

### ISSUE THREAD

**Issue by edmonds** [easylist/easylist#656]
Hi,

Commit https://github.com/easylist/easylist/commit/36429cb61012c080e765317ff22defd83f0f005d breaks the web interface of the Netgear CM1000 cable modem, and probably some other Netgear devices that have similar web interfaces. The web interface of this device attempts to load the cable modem's event log in an IFRAME from the path `/EventLog.asp`, which is blocked by https://github.com/easylist/easylist/commit/36429cb61012c080e765317ff22defd83f0f005d#diff-6b54c84f883288b1582a40f4174525e0R1162.

![screenshot_2017-10-06_22-07-23](https://user-images.githubusercontent.com/202839/31303871-619d886a-aae3-11e7-89a7-199bdd741be3.png)

**Comment by Khrin** [comment]
Sorry, this filter is undoubtedly too much generic. I've modified it to make more specific, so shouldn't cause such false positives anymore. You'll have to force a filters update or wait for the automatic one to see the issue fixed.
