### ISSUE TITLE
propeller-tracking.com

### ISSUE THREAD

**Issue by galaxydriver** [easylist/easylist#6575]
### List the website(s) you're having issues:

`animepahe.com` (as an example)

### What happens?

Tracking URL `propeller-tracking.com` was added to `easylist_adservers.txt`. It looks like a mistake because it is not serving any ads, it only tracks users. Its okay just for `easyprivacy` I think.

### List Subscriptions you're using:

Default EasyList subscription in AdBlock. 

### Your settings

- OS/version: macOS Catalina 10.15.7
- Browser/version: Chrome 86.0.4240.198
- Adblock Extension/version: 4.24.1

### Other details:

Related issue https://github.com/easylist/easylist/issues/6273.

Thank you for reviewing this issue.

**Comment by ryanbr** [comment]
Okay, moved.
