### ISSUE TITLE
myanimelist.net

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6580]
### List the website(s) you're having issues:

`https://myanimelist.net/anime/6211/Tokyo_Magnitude_80`

### What happens?

Placeholders between `Background` and `Related Anime`.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/100866863-933fba80-3499-11eb-94f7-34085c9688b6.png)

### Your settings

- OS/version: Windows 10 October 2020 Update
- Browser/version: Chrome 87.0.4280.66 x64
- Adblock Extension/version: uBO 1.31.1b12 + IDCAC 3.2.5

### Other details:

I propose `myanimelist.net##.border_top`

![image](https://user-images.githubusercontent.com/22780683/100866904-a2bf0380-3499-11eb-8813-61dc64eb462c.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6f9f295319a6c570c8043dbba0344981160be5ba
