### ISSUE TITLE
quantamagazine.org

### ISSUE THREAD

**Issue by lijunkang12** [easylist/easylist#6588]
### List the website(s) you're having issues:

```
https://www.quantamagazine.org/
```

### What happens?

Sidebar that shows the author and the date of publication of an article is blocked.

### List Subscriptions you're using:

Fanboy Annoyances List

### Your settings

- OS/version: macOS Big Sur Version 11.0.1
- Browser/version: Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Adblock Extension/version: uBlock Origin 1.31.0

### Other details:
Change the filter `quantamagazine.org##.post__sidebar` into `quantamagazine.org##.post__sidebar hide flex flex-justify-center theme__anchors--solid`. The latter is the dom element that contains social media content and should be blocked.

**Comment by ryanbr** [comment]
Removed

https://github.com/easylist/easylist/commit/727e8a95ec9d687c413a3172d808c9baa7614234
