### ISSUE TITLE
uMatrix supported?

### ISSUE THREAD

**Issue by zappe** [easylist/easylist#659]
I have issues with blocks for google.com and apple.com.
Maybe uMatrix is not supported?

**Comment by SMed79** [comment]
Can you describe exactly your issue and how i can reproduce?

**Comment by zappe** [comment]
Use the list in uMatrix, surf to sites above, blocked.

**Comment by SMed79** [comment]
I don't comfortable and not familiarized with uMatrix.

@gorhill Can you help here?

- http://i.imgur.com/CaL0BVh.png
- http://i.imgur.com/AJZbkKb.png

**Comment by Blutgang** [comment]
The answer to this question is **no**.

- uMatrix only supports hostname compatible lists (Example: HOSTS file). 

Supported:
```
www.wikipedia.org
wikipedia.org
en.wikipedia.org
127.0.0.1 wikipedia.org
0.0.0.0 wikipedia.org
```

- uMatrix does not support filter lists with paths, patterns or regex (Example: EasyList, EasyPrivacy, adblock list).

Not supported:

```
||wikipedia.org^
||en.wikipedia.org^
||upload.wikimedia.org/wikipedia/commons/thumb/*.jpg$image,domain=en.wikipedia.org
```

Gorhill's comment from the old uBlock repository:
https://github.com/chrisaljoudi/uBlock/issues/1524#issuecomment-133831208
> EasyList is not a HOSTS file, and trying to load this in uMatrix will give undefined results.
