### ISSUE TITLE
||cdn13.com^$script,3p,domain=~leafy.pro triggering no matter the site.

### ISSUE THREAD

**Issue by pmuybae** [easylist/easylist#6596]
When trying to upload on https://thisvid.com/my_video_upload/ the script is blocked.

**Comment by keczuppp** [comment]
Related / similiar: https://github.com/easylist/easylist/issues/5400

**Comment by Yuki2718** [comment]
Fixed in uBlock Unbreak.
@ryanbr There're some placehoder left.
