### ISSUE TITLE
Yavli promoted content

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#66]
https://forums.lanik.us/viewtopic.php?f=62&t=24544

**Comment by terrorist96** [comment]
`http://dailycaller.com/2016/07/26/dem-delegate-admits-common-sense-gun-control-is-just-code-for-repealing-second-amendment-video/`

**Comment by terrorist96** [comment]
`http://www.cheatsheet.com/money-career/?ref=TN`

**Comment by terrorist96** [comment]
`http://www.activistpost.com/`

**Comment by mapx-** [comment]
##[class*="mdeyheadline_"]
##DIV[cls$="_simule"]
##SPAN[cls$="_box"]

**Comment by terrorist96** [comment]
Should be merged.

**Comment by terrorist96** [comment]
`http://dennismichaellynch.com/`
