### ISSUE TITLE
Spotify Web ADS blocking the musics

### ISSUE THREAD

**Issue by igormaozao** [easylist/easylist#660]
Hello, some months ago it was happening too, but was fixed, but in like 1~2 weeks ago it started to "play" the advertising sounds again.

It is not playing the sound itself, but you can see this in the "playing song bar" on the bottom:  https://gyazo.com/175c9d5ce4dcba42fbad34023b222a89

It just stay like that until I refresh the page.

Ps: I'm using ADBlock Plus, and they said I should report this to you (not sure tho).

Thank you.

**Comment by peace2000** [comment]
This probably isn't relevant anymore @ryanbr @Khrin
