### ISSUE TITLE
xhamster.com (NSFW)

### ISSUE THREAD

**Issue by StrictHorse8799** [easylist/easylist#6617]
### List the website(s) you're having issues:
```
[NSFW] https://xhamster.com/videos/vixen-beautiful-redhead-bree-daniels-fucked-by-sugar-daddy-6494377
[NSFW] https://xhamster.com/videos/blacked-red-head-model-amarna-miller-interracial-creampie-4205964
[NSFW] https://xhamster.com/videos/mylf-nostalgic-ryan-keely-wants-her-stepsons-dick-11675263
[NSFW] https://xhamster.com/videos/brazzers-dirty-milf-ava-addams-fucks-chef-6437739
[NSFW] https://xhamster.com/videos/a-blouse-full-of-goodies-7598169)
```

### What happens?

Hi and thanks for your work with Easylist!

Ad banner below the video, each video has a different banner.

All channels have banners: `https://xhamster.com/channels`

And I'm not sure if you can reproduce this, when on the site click a video below then hit your browsers back-button, it will referrer you to xhamsterlive.com on every back-button click.

### Your settings
uBlock Origin

**Comment by ryanbr** [comment]
I would've left it alone, considered a self promo. The moment xhamster included animated gifs, was considered an ad.
