### ISSUE TITLE
Discussion: Consider removing pingback.issuu.com from blacklist

### ISSUE THREAD

**Issue by mattmattmatt** [easylist/easylist#663]
I speak for issuu, a publishing platform offering readers millions of magazines, books and catalogs to read for free.

Currently, `pingback.issuu.com` is blocked on [EasyList Privacy](https://github.com/easylist/easylist/blob/3ef91c1515ea2490da5d5022a85ef473a25394fc/easyprivacy/easyprivacy_specific.txt#L1364). This is negatively impacting user functionality and experience. We would therefore like to propose to remove `pingback.issuu.com` from the list.

### What our pingbacks do
"Pingbacks" are short messages that inform our systems about actions a user has taken. They are used e.g. 
 - to keep a user's place in a given publication, so they can pick up where they left off
 - to enable users to track what they have read, so they can find it again. Users can delete this information if they like.
 - to _anonymously_ send statistics about how long a page or feature took to load, so we can focus our improvements efforts on where they are needed most
 - to _anonymously_ inform our business about what publications are being read and for how long, so we can make educated business decisions and keep providing our service.

### What our pingbacks don't do
 - Pingbacks do not collect or send personally identifiable information (PII).
 - Pingbacks do not track user behavior on a per-user basis.
 - Pingbacks do not have anything to do with advertising, nor is the information they collect passed on to advertisers or being used for advertising. In fact, pingback information is only ever stored in aggregate and never made available to third parties, whether individually or in aggregate.

We appreciate the function of ad blockers, privacy helpers and similar lists. We believe to be acting in good conscience when proposing this entry removal.

We can provide a PR that takes care of the removal if that makes things easier.

**Comment by mattmattmatt** [comment]
@SMed79 What is the correct way to get this proposal discussed or approved?

**Comment by SMed79** [comment]
Only the easylist authors can help you here.
Try reporting your issue via e-mail: **easylist.subscription** <span>:email:</span> **gmail.com**

**Comment by monzta** [comment]
Removed https://github.com/easylist/easylist/commit/bc281bced587afadf378c3b5293420c3c29b9d26
