### ISSUE TITLE
Adlibris.com - Images fails to load (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#6633]
### Affected site:
`https://www.adlibris.com/`

### Issue:
Many product images randomly fails to load.

### Example:
`https://www.adlibris.com/no/avdeling/hjemmeelektronikk-a1020/`

(Page might need to be refreshed a couple of times)

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **EasyPrivacy**

### Problem rule:
`||adlibris.com/pixel.gif`

### Possible fix:
Remove the problem rule!

### Temporary fix:
`@@||adlibris.com/pixel.gif`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.16.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.27b2 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by peace2000** [comment]
Well... That was unexpected. Pretty low quality website to be honest. :D
