### ISSUE TITLE
kpcen-torun.edu.pl [EasyList Cookie, I don't care about cookies, AdGuard Annoyances] [breakage]

### ISSUE THREAD

**Issue by keczuppp** [easylist/easylist#6652]
### List the website(s) you're having issues:

https://www.kpcen-torun.edu.pl/

### What happens?

- another nasty breakage affecting many cookie filter lists:
(`EasyList Cookie` list, `I don't care about cookies` addon, `AdGuard Annoyances` list)
- bad cut GDPR message, the popup's backgorund blocking page

### List Subscriptions you're using:

- `EasyList Cookie` list, 
- `I don't care about cookies` addon, 
- `AdGuard Annoyances` list

### Your settings

- OS/version: Win7 SP1 64
- Browser/version: Firefox
- Adblock Extension/version: uBO 1.31.3b4

### Screenshoot

<details not-open>
<summary>screenshoot 1</summary>

![capture_220_07-12-2020_20-55-50](https://user-images.githubusercontent.com/74409207/101402948-c38dbb80-38d4-11eb-8266-04da607d884f.png)

</details>
<details not-open>
<summary>screenshoot 2</summary>

![capture_221_07-12-2020_20-56-58](https://user-images.githubusercontent.com/74409207/101402985-d1dbd780-38d4-11eb-9baa-4e6a9de0a8af.png)
</details>

<details not-open>
<summary>screenshoot 3</summary>

![capture_222_07-12-2020_20-57-09](https://user-images.githubusercontent.com/74409207/101403010-dc966c80-38d4-11eb-93ec-a4c4aaee359c.png)
</details>

**Comment by bug-rules** [comment]
GDPR, no possible fix in uBlock Annoyances be like: https://github.com/uBlockOrigin/uAssets/pull/8320
