### ISSUE TITLE
push.bdnewsx.com [urlshortx.com]

### ISSUE THREAD

**Issue by Barticf** [easylist/easylist#6654]
### List the website(s) you're having issues:

**`https://push.bdnewsx.com/Finhz0C`**
### What happens?

A lot of ads

### List Subscriptions you're using:
Easylist
Adguard

uBlock
### Your settings

- OS/version: Win 10
- Browser/version: Firefox
- Adblock Extension/version: uBlock

### Other details:

![obraz](https://user-images.githubusercontent.com/32641928/101491223-ca174400-3963-11eb-9f12-8751da79af7c.png)
Blinking in browser
![obraz](https://user-images.githubusercontent.com/32641928/101491376-f3d06b00-3963-11eb-9f7c-d3cc95e71531.png)
-->
![obraz](https://user-images.githubusercontent.com/32641928/101491419-ffbc2d00-3963-11eb-934a-7314cc6343b9.png)

**Comment by ryanbr** [comment]
Looks fine @Barticf Link to the "urlshortx" url if you want it fixed.
