### ISSUE TITLE
www.savjee.be

### ISSUE THREAD

**Issue by Savjee** [easylist/easylist#6658]
### List the website(s) you're having issues:

```
https://savjee.be
https://savjee.be/2020/10/impact-adblockers-on-google-analytics-vs-plausible/
```

### What happens?

The thumbnail and all images for this blog post are blocked by EasyList.

Images are hosted on the following path:
```
https://www.savjee.be/uploads/2020-10-27-effect-adblockers-on-google-analytics-vs-plausible/

Example (thumbnail):
https://www.savjee.be/uploads/2020-10-27-effect-adblockers-on-google-analytics-vs-plausible/thumb_timeline.jpg
```

Blocked by this filter: `-google-analytics-$domain=~wordpress.org`

### List Subscriptions you're using:

* EasyList
* EasyPrivacy
* uBlock filters (all built-in filters)

### Your settings

- OS/version: macOS 11.0.1
- Browser/version: Chrome 87.0.4280.88
- Adblock Extension/version: uBlock Origin v1.31.2

### Other details:

uBlock Origin is pointing towards this filter:
```
`-google-analytics-$domain=~wordpress.org`
```

I'm unfamiliar with the syntax, but seems like the domain match is not working correctly?

Screenshot of the Logger:
![image](https://user-images.githubusercontent.com/817109/101646110-652d1e00-3a37-11eb-8650-668ec28040b9.png)

(Note: I'm fine with the Google Analytics JS being blocked. This bug report is for the blocked image uploads)

**Comment by krystian3w** [comment]
Match correct, just wait for hotifx:

`-google-analytics-$domain=~savjee.be|~wordpress.org`
