### ISSUE TITLE
medium.com [EasyPrivacy]

### ISSUE THREAD

**Issue by makeworld-the-better-one** [easylist/easylist#6661]
### List the website(s) you're having issues:

`https://medium.com/` and any of its articles.

### What happens?

A "Sign into medium.com with Google" popup appears on the right side, displaying the logged-in Google account(s) I have. This makes a connection to `accounts.google.com`, tracking the articles I read. The same popup is blocked on a non-Medium page like [this one](https://venturebeat.com/2020/06/03/google-faces-5-billion-lawsuit-for-tracking-users-in-incognito-mode/), thanks to the `||google.com^*/log?` filter from EasyPrivacy.

### List Subscriptions you're using:

- All built-in uBlock Origin ones
- EasyList
- EasyPrivacy
- [Online Malicious URL Blocklist](https://gitlab.com/curben/urlhaus-filter#urlhaus-malicious-url-blocklist)
- EasyList Cookie
- Peter Lowe's List

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 83.0
- Adblock Extension/version: uBlock Origin v1.31.0

### Other details:

This was originally reported at uBlockOrigin/uAssets#8351. A Contributor there suggested the filter `||accounts.google.com/gsi/*$xhr,script,3p` which worked for me.

**Comment by gwarser** [comment]
Recurring question on uBO subreddit is how to block this.

**Comment by makeworld-the-better-one** [comment]
Well, feel free to tell to use `||accounts.google.com/gsi/*$xhr,script,3p`. If it gets added to EasyPrivacy you can tell them to just enable that.

**Comment by yourduskquibbles** [comment]
FYI other sites besides `medium.com` use this which is why I suggested 3p vs specific to domain `medium.com`, some other example sites for testing from: https://github.com/yourduskquibbles/webannoyances/issues/228#issuecomment-658540038

```
http://www.redfin.com/
http://www.medium.com/
http://www.quora.com/
https://fsastore.com/
http://www.pinterest.com/
http://www.ebay.com/
http://www.linkedin.com/
https://quizlet.com/
```

and although it can be blocked with just script block on `medium.com`, [`linkedin.com` fetches the request via xhr](https://github.com/yourduskquibbles/webannoyances/issues/228#issuecomment-678419176).

**Comment by makeworld-the-better-one** [comment]
Yep I was hoping to block it on other sites too, I just used `medium.com` as an example. Thanks for suggesting a fix that works across sites.

**Comment by ryanbr** [comment]
This is included in Enhanced Trackers, but we would cause too many issues to include in Easyprivacy

**Comment by makeworld-the-better-one** [comment]
What issues would this cause?

**Comment by paulverbeke** [comment]
The filter to remove this annoying Google pop-up is still working correctly on `redfin.com` and `medium.com`, but not on `quizlet.com` and neither on `tech.hindustantimes.com`. All the other websites listed in this issue are apparently not integrating this pop-up anymore. Using this filter here is working for both `||accounts.google.com/gsi/iframe/select`. Do you think the list can be updated ?
