### ISSUE TITLE
Could the repository get a README file?

### ISSUE THREAD

**Issue by ePaul** [easylist/easylist#668]
When coming to the repository without knowing what this is about (I just followed some link), it is really confusing (you just see some text files).

Could we have a README (or README.md or whatever format you prefer) with one paragraph explaining what this is, and then pointing to https://easylist.to/ (and maybe [to the Forum](https://forums.lanik.us/)) for additional information?

You could also add the URL directly as the repository website (maintainers should see an edit button at the main page).

**Comment by Khrin** [comment]
We can evaluate the possibility of adding a README file in the near future.
