### ISSUE TITLE
New miner domain(s)

### ISSUE THREAD

**Issue by thrwat** [easylist/easylist#669]
authedmine.com
https://authedmine.com/lib/authedmine.min.js
https://authedmine.com/lib/miner.min.js
https://authedmine.com/lib/captcha.min.js

**Comment by Varbin** [comment]
Please note that authedmine only mines with the appvorval of users (they have to explicitly click on the widget).

**Comment by dmytro-ielkin** [comment]
@thrwat and others like you stop being dirt bags. authedmine was created specifically for cases when user explicitly gives permission to mind and understands what's going on. Do you understand that you're making it worse for everyone? You want everything for free and than you do everything to make life harder for people who create things on the internet.

Have you ever created anything for other people to use? Have you supported anyone who did? Of course not. You only think about yourself you leech.

All you do is whine on the internet about how ads are annoying and intrusive.
