### ISSUE TITLE
torrenthound ad

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#67]
`http://www.torrenthound.com/hash/10b0592b429b1392925c66a935031e058d17365f/torrent-info/linux-lite-2.4-64bit.iso`

Anonymous download ad

Old reports:
https://adblockplus.org/forum/viewtopic.php?f=10&t=44688
https://forums.lanik.us/viewtopic.php?f=62&t=23134
https://forums.lanik.us/viewtopic.php?f=62&t=29088

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/b1b621ff7926b9c7054b228ff26d6d1f3a649629
