### ISSUE TITLE
False positive: .tag-sponsored-post on androidpolice.com

### ISSUE THREAD

**Issue by archon810** [easylist/easylist#671]
Originally posted here https://forums.lanik.us/viewtopic.php?f=64&t=38595, now filing a ticket for visibility.

This commit https://github.com/easylist/easylist/commit/c260b128 adds a hide filter for .tag-sponsored-post. Except it ends up breaking other aspects than intended in 3 ways I discovered and described in the comments to that commit.

Please revert this change or finetune it to only apply to list pages, and in a way that fixes https://github.com/easylist/easylist/commit/c260b128#commitcomment-25022103.

Thank you.

**Comment by archon810** [comment]
https://github.com/easylist/easylist/commit/cf950c3a77a1d6540c5e3e6d7ccc4cda1f755ac8 fixes this for AP, but @monzta is looking for a better solution, or eliminating this altogether as it affects all Wordpress-based sites.

**Comment by Khrin** [comment]
Already fixed 5 hrs ago https://github.com/easylist/easylist/commit/0634953b9d40e98ef40acd631a5143fdd0b1dda5
