### ISSUE TITLE
unilad.co.uk

### ISSUE THREAD

**Issue by Barticf** [easylist/easylist#6710]
### List the website(s) you're having issues:

`https://www.unilad.co.uk/life/woman-jumps-into-ocean-to-rescue-beer-kegs-during-dramatic-flooding-in-australia/`
### What happens?
![obraz](https://user-images.githubusercontent.com/32641928/102210197-28977180-3ed2-11eb-9cc2-d829b630a9f7.png)

### List Subscriptions you're using:

1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances, Base, Mobile Ads
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List
11. AdGuard Tracking Protection
12. AdGuard Base, Mobile Ads
13. AdGuard Mobile Ads

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 83
- Adblock Extension/version: uBlock 1.31

**Comment by THEtomaso** [comment]
### Problem filters (at my end):
* **Dan Pollock's hosts file**
`static.adsafeprotected.com`

* **EasyList**
`##.dfp-ad-unit`
`##div[class*="margin-Advert"]`
`||adsafeprotected.com^$third-party`

* **hpHosts - Ad and Tracking servers only** _(DISCONTINUED)_
`adsafeprotected.com`
`static.adsafeprotected.com`

* **Lunar Blocklist by Moonchild** (@wolfbeast)
`||adsafeprotected.com^$popup,image,media,object,object-subrequest,other,ping,script,stylesheet,subdocument,websocket,xmlhttprequest`

* **MVPS HOSTS** _(Pointless to report)_
`static.adsafeprotected.com`

* **Peter Lowe's Ad and tracking server list** (@pgl)
`adsafeprotected.com`

### Possible fix:
```
@@||unilad.co.uk^$generichide
unilad.co.uk##.dfp-ad-unit:upward(1)
@@||adsafeprotected.com/vans-adapter-google-ima.js
```
The "upward" syntax bypasses their detection scheme, but is not supported by ABP-based blockers.
@okiehsch: Something for uBO Filters?
