### ISSUE TITLE
skk.moe

### ISSUE THREAD

**Issue by M-i-k-o-t-o** [easylist/easylist#6724]
The commit in https://github.com/easylist/easylist/commit/2ce2444193f5d479fb131e9dc89bbde9c82c8ad1 does not work anymore. The author boasted about it at https://github.com/SukkaW/cloudflare-workers-async-google-analytics#say-hello-to-easylist. The site is `skk.moe`

At the end of the body it contains an inline script tag (which gets auto-emptied after a while) and a script tag which loads https://cdn.jsdelivr.net/npm/skx@0.2.4/js/optical.js

I suggest blocking the site entirely as well as providing an updated way to deal with cfga.js. There is already a list which tries to handle it here https://abp.tt.codes/rules.txt (search for https://github.com/SukkaW/cloudflare-workers-async-google-analytics)

**Comment by JobcenterTycoon** [comment]
Tracking is back

Tracking image `https://skk.moe/react.js?5qdoi9=f3l35bode&callback=perf&foxtail=122669675-2&dt=Sukka%20(%40SukkaW)&de=UTF-8&dr=&ul=de&sd=24-bit&sr=2560x1440&vp=1272x985&z=1638117444900&plt=524&dns=123&pdt=7&rrt=0&tcp=36&srt=90&dit=386&clt=523`

tracking coming from `https://cdn.jsdelivr.net/npm/sks@0.4.2/lazyload.js`

**Comment by M-i-k-o-t-o** [comment]
CC @ryanbr @spirillen @Yuki2718 you might want to check out @JobcenterTycoon 's post. My suggestions:
- Block cdn.jsdelivr.net/npm/sks@* and cdn.jsdelivr.net/npm/skx@*
- Block skk.moe in its entirety as they are trying to play the cat and mouse game. It is just a personal blog without any useful content.

**Comment by JobcenterTycoon** [comment]
> Block skk.moe in its entirety as they are trying to play the cat and mouse game. It is just a personal blog without any useful content.

"Just" a personal Blog why not blocking facebook and twitch too because they play the cat and mouse play? 😂

**Comment by M-i-k-o-t-o** [comment]
> > Block skk.moe in its entirety as they are trying to play the cat and mouse game. It is just a personal blog without any useful content.
> 
> "Just" a personal Blog why not blocking facebook and twitch too because they play the cat and mouse play? joy

I do have them blocked personally, but I do not think that easylist's usebase would want that. The point is that facebook being blocked might stop a few people from using the list but this being blocked won't.
Although I do not think that anyone would complain if facebook was "softblocked" - as in, show a warning once and never display it again if the user chooses to bypass it, the same functionality could be used for this site. I am pretty sure that ublock supports something like that but idk if any of the other blockers that easylist aims to support have it.

**Comment by spirillen** [comment]
> CC @ryanbr @spirillen @Yuki2718 you might want to check out @JobcenterTycoon 's post. My suggestions:
> 
>     * Block cdn.jsdelivr.net/npm/sks@* and cdn.jsdelivr.net/npm/skx@*
> 
>     * Block skk.moe in its entirety as they are trying to play the cat and mouse game. It is just a personal blog without any useful content.

`jsdelivr.net` is blacklisted in my filters they they only serve unwanted bad code, and third party hosted code .... not something a good side does. and jsdel is only serving "`free`" hosting, to collect userdata (https://mypdns.org/my-privacy-dns/matrix/-/issues/1805)

**Comment by Yuki2718** [comment]
I don't see `https://cdn.jsdelivr.net/npm/sks@0.4.2/lazyload.js` but instead the pixel comes from `​https://skk.moe/index.8170b77b.js`.  Blocking a website except for malware/scam is nothing other than abuse of our power.

**Comment by JobcenterTycoon** [comment]
@Yuki2718 
Tracking is still here on `https://blog.skk.moe/`

Track script: `https://unpkg.zhimg.com/skx@0.5.9/js/lazyload.js`

Track img: `https://blog.skk.moe/js/vue.js?zj26f=4ei7xaqa5&callback=perf&foxtail=122669675-1&dt=Sukka%27s%20Blog&de=UTF-8&dr=&ul=de&sd=24-bit&sr=2560x1440&vp=1302x911&z=1640896191900&plt=377&dns=0&pdt=2&rrt=0&tcp=0&srt=103&dit=332&clt=356`

**Comment by Yuki2718** [comment]
Rather than trying cat-and-mouse with the blog author, blocked tracker actually used in the wild.

**Comment by spirillen** [comment]
> Rather than trying cat-and-mouse with the blog author, blocked tracker actually used in the wild.

That is what I believe @JobcenterTycoon have done with this comment

> Track script: https://unpkg.zhimg.com/skx@0.5.9/js/lazyload.js

As I can remember the `zhimg.com` from the past.

Or is it something else you have in mind @Yuki2718

**Comment by Yuki2718** [comment]
IDK if that script is used elsewhere, but `/cfga/jquery.js?` is used by some sites e.g. `nekomio.com`. They may quickly respond, but it will take longer time for actual user (webmaster) of the tracking library to update.

**Comment by NeverBehave** [comment]
Right now the tracking seems to be posting data to url such as `https://blog.skk.moe/_next/data/*/post/*.json`

Return will always be 

```json
{"success":false,"message":"Data decode failed"}
```

**Comment by JobcenterTycoon** [comment]
> Blocking all xhr does not affects loading webpages

It does. Clicking on a link throws a error

**Comment by NeverBehave** [comment]
> > Blocking all xhr does not affects loading webpages
> 
> 
> 
> It does. Clicking on a link throws a error

Interesting. I saw that once but after refresh it is gone.

**Comment by NeverBehave** [comment]
Okey I think there is a bug with [uAssets](https://github.com/uBlockOrigin/uAssets/blob/6da72d807e1ee240175df027e1d663d7b663fedc/filters/privacy.txt#LL335-L335C39). It has the following rules:

```
skk.moe##+js(no-fetch-if, method:POST)
```

This won't block the POST request as expected. However, if we use the following:

```
skk.moe##+js(no-fetch-if, method: post)
```

It does block the POST fetch.

**Comment by NeverBehave** [comment]
The root cause is uBlock scriptlet regex does not support case insensitive when matching properties: https://github.com/uBlockOrigin/uAssets/pull/15692
