### ISSUE TITLE
dailydot twitter posts broken by fanboy annoyance list

### ISSUE THREAD

**Issue by jordanelliott23** [easylist/easylist#6729]
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.dailydot.com/unclick/baby-yoda-christmas-tree-topper/)

filter on: 
![8703C839-62D3-4B35-A341-A56E1777DFA5](https://user-images.githubusercontent.com/71462072/103107213-bcb7b600-4601-11eb-9864-f1c655f74c2a.png)

filter off: 
![B78AF31C-C4D4-462C-BBD9-CA3DFD375108](https://user-images.githubusercontent.com/71462072/103107217-c4775a80-4601-11eb-8d82-adcf06f91650.png)

**Comment by jordanelliott23** [comment]
also on this site:  https://www.dailydot.com/unclick/baby-yoda-christmas-tree-topper/

**Comment by THEtomaso** [comment]
Works for me.
Whitelisted by the following rule (found in **Fanboy's Annoyance List** / **Fanboy's Social Blocking List**):
`@@||platform.twitter.com/widgets/widget_iframe.$subdocument`

**Comment by jordanelliott23** [comment]
would it make a difference if im using mobile safari? @THEtomaso cuz i tried that rule and still broken on both sites

**Comment by THEtomaso** [comment]
> would it make a difference if im using mobile safari?

Probably.
You should include that info in the first post.

**Comment by jordanelliott23** [comment]
@THEtomaso this is how it appears with and without fanboy annoyance turned on for daily dot.

filter on: 
![8703C839-62D3-4B35-A341-A56E1777DFA5](https://user-images.githubusercontent.com/71462072/103107213-bcb7b600-4601-11eb-9864-f1c655f74c2a.png)


filter off: 
![B78AF31C-C4D4-462C-BBD9-CA3DFD375108](https://user-images.githubusercontent.com/71462072/103107217-c4775a80-4601-11eb-8d82-adcf06f91650.png)

**Comment by jordanelliott23** [comment]
@ryanbr

**Comment by THEtomaso** [comment]
> this is how it appears with and without fanboy annoyance turned on for daily dot.

I understand, but I'm not administrating that filter.
You'll hve to wait for ryanbr or Khrin to look into it.
And btw; ryanbr never responds to pings.

**Comment by ryanbr** [comment]
Closing, works for me. If it's a browser/extension issue, take it up with them. `@@||platform.twitter.com/widgets/widget_iframe.$subdocument`  is already implemented.
