### ISSUE TITLE
engageya.com ads isn't blocked

### ISSUE THREAD

**Issue by adReporter1** [easylist/easylist#674]
engageya.com is an ad company with disgusting feet lags ads.
their widget is coming from this url: http://widget.engageya.com/engageya_loader.js
and they sometimes load ads and sometime content recommendations (like taboola).

example site:
http://www.haberuygar.com/milliyet-gazetesi-muhabiri-nevzat-dindarla-ilk-roportajimizi-gerceklestirdik-2679h.htm

looks like ads are always coming from:
 `http://widget.engageya.com/eng_crt_loader2.js`

screenshot attached https://i.imgur.com/JGEX7Nn.png.

@ryanbr please if you can.

**Comment by adReporter1** [comment]
more ads http://basketfaul.com/haber?haber=67258

**Comment by Khrin** [comment]
It's included in EasyPrivacy.

**Comment by adReporter1** [comment]
but it's ads... not content recommendation! real ads! of feet and erection and other shit.
please see here - https://i.imgur.com/JGEX7Nn.png

Maybe you don't see ads from your GEO, I am getting erection ads, I can share my network.
