### ISSUE TITLE
Preview images blocked in facebook stream

### ISSUE THREAD

**Issue by black-snow** [easylist/easylist#676]
https://github.com/easylist/easylist/blob/8cc6e871b5d9aa493b50bf8d1856149355bd621e/easyprivacy/easyprivacy_thirdparty.txt#L754

This seems to block some but not all preview images in my stream.

E.g. https://external-frt3-2.xx.fbcdn.net/safe_image.php?w=476&h=249&url=https%3A%2F%2Fbuffer-media-uploads.s3.amazonaws.com%2F59e7acd0efda0c6c470291a1%2Fa7bc70a823f786b9fb7f51aa9078e3dd48e4506b_fb1ebade335b2e5630c75a40a4189a3c96c53ea9_facebook&cfs=1&upscale=1&_nc_hash=AQCrHOAXDt2jjYO4 gets blocked which is not what I'd expect.

I end up with some articles not having images.

**Comment by Khrin** [comment]
Removed https://github.com/easylist/easylist/commit/d73437c7fe62bbc4f9d37794d2a0e2dcb7075d61
