### ISSUE TITLE
myanimelist.net

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6778]
### List the website(s) you're having issues:

`https://myanimelist.net/anime/17265/Log_Horizon/episode/25`

### What happens?

A placeholder below the episode description, seemingly a different one than the one in #6580.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/102788396-db6c4180-43a2-11eb-831e-c6b7a19e183a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.31.3rc4 + IDCAC 3.2.6

### Other details:

I propose `myanimelist.net##td[valign=top] > div[style^="padding:16px 0px "]`

![image](https://user-images.githubusercontent.com/22780683/102789512-8af5e380-43a4-11eb-8c16-1e5289c5d9f5.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b1eded586f77e434bf22b0a741999947304421f6
