### ISSUE TITLE
kongregate.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6779]
### List the website(s) you're having issues:

```
https://www.kongregate.com/unity-games
https://www.kongregate.com/games/KekGames/unpuzzlex
```

### What happens?

On the 1st example page: Placeholder in the upper right of the game list.
On the 2nd: Placeholder boxes in the "Recommended Games" box.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/102788396-db6c4180-43a2-11eb-831e-c6b7a19e183a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.31.3rc4 + IDCAC 3.2.6

### Other details:

I propose:
```
! https://www.kongregate.com/unity-games
##.adcontainer
! https://www.kongregate.com/games/KekGames/unpuzzlex
##div[id^=rec_spot_ad]
```

![image](https://user-images.githubusercontent.com/22780683/102790409-af05f480-43a5-11eb-8f3e-fcd752929bf1.png)

![image](https://user-images.githubusercontent.com/22780683/102790379-a31a3280-43a5-11eb-9fb9-578d5f95c913.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/fc0b89ec7e71b71172a5eac27070510a4fa9fb85

Didn't see the other one. Looks fine here.
