### ISSUE TITLE
issuu.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6780]
### List the website(s) you're having issues:

`https://issuu.com/upstatehouse/docs/upstate-house-spring-2018/26`

### What happens?

Two placeholder boxes.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/102788396-db6c4180-43a2-11eb-831e-c6b7a19e183a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.31.3rc4 + IDCAC 3.2.6

### Other details:

I propose:
```
issuu.com##div[class*=adLeaderboardContainer]
issuu.com##div[class*=adPlacementContainer]
```

![image](https://user-images.githubusercontent.com/22780683/102791432-491a6c80-43a7-11eb-8853-c3229a0c75bc.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c884e51b1ec7e3694755793df78d042ce8f7e1d7

**Comment by stephenhawk8054** [comment]
Ads placeholders in website.

URL 1: `https://issuu.com/catalogi/docs/m_feeling_fs21`
<details>
<summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/66517106/141717899-ec9b2143-7410-4288-b1d3-1e6fc8c25fbc.png)

</details>

Proposed filters;

```
issuu.com##[itemscope] > div > [height]
issuu.com###ad-primis-wide
issuu.com##aside > div > div > div[height]
issuu.com##[data-testid="card-list-similar-to"] > div > div[height]
issuu.com##[data-testid="card-list-just-for-you"] > div > div[height]
issuu.com#?#[data-testid="card-list-popular-now"] > div:-abp-has(div[height])
issuu.com##[data-testid^="card"] > div > p
issuu.com##section
```

URL 2: `https://issuu.com/explore`
<details>
<summary> Screenshot 2 </summary>

![image](https://user-images.githubusercontent.com/66517106/141718103-45d50440-8be7-4ba5-9e79-cb0616284722.png)

</details>

Proposed filter:

`issuu.com##.adShelf`

Firefox 94.0.1, ublock 1.38.6 default
