### ISSUE TITLE
supercheats.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6782]
### List the website(s) you're having issues:

`https://www.supercheats.com/`

### What happens?

Various placeholders spread throughout the page.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/102788396-db6c4180-43a2-11eb-831e-c6b7a19e183a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.31.3rc4 + IDCAC 3.2.6

### Other details:

I propose:
```
###bottom_ad_728
supercheats.com##.a300
supercheats.com##.cboth_sm
```

The placeholders are spread too far apart for conventional screenshots.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/012ed130e1577754c8d4d86355b77898fc0eaeb7
