### ISSUE TITLE
dummies.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6783]
### List the website(s) you're having issues:

`https://www.dummies.com/computers/pcs/printers/how-to-find-printers-in-windows-on-your-pc/`

### What happens?

Various placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/102788396-db6c4180-43a2-11eb-831e-c6b7a19e183a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.31.3rc4 + IDCAC 3.2.6

### Other details:

I propose `dummies.com##.ads`

![image](https://user-images.githubusercontent.com/22780683/102794368-91d42480-43ab-11eb-813d-1b9f24e39e91.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b22d68a62667cd69d32c9f8866b5db133769e3a5
