### ISSUE TITLE
indiatimes.com

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6822]
### List the website(s) you're having issues:

`https://www.indiatimes.com/news/india/people-who-have-recovered-from-covid-remain-immune-to-virus-for-at-least-8-months-study-530325.html`

### What happens?

3rd party ads

### Screenshots

![Opera Snapshot_2020-12-24_133756_www indiatimes com](https://user-images.githubusercontent.com/20338483/103074905-8f164100-45f0-11eb-9caf-ae94485dd03d.png)
![Opera Snapshot_2020-12-24_133840_www indiatimes com](https://user-images.githubusercontent.com/20338483/103074911-90e00480-45f0-11eb-9f9b-c6a7c32c5109.png)

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: opera /firefox
- Adblock Extension/version: ublock origin 1.31

### Other details:

these filters works
```
||mensxp.com^$3p
/coupondunai/best-offers$xhr,domain=www.indiatimes.com
www.indiatimes.com##div.mb-36.container:nth-of-type(4)
www.indiatimes.com##div.mb-36.container > .top-trending.mb-30
```

**Comment by ryanbr** [comment]
Only saw:
```
indiatimes.com##.slick-slider
indiatimes.com##.top-trending
```

**Comment by ghajini** [comment]
> 
> ```
> indiatimes.com##.slick-slider
> indiatimes.com##.top-trending

> ```

1.
with that sort of filters you will be hiding so much of legitimate articles
like `Stories In Focus`/`Latest Stories`/`Trending Now`/`Big Image` tested at 

`indiatimes.com`

2.
also at `https://www.indiatimes.com/news/india/people-who-have-recovered-from-covid-remain-immune-to-virus-for-at-least-8-months-study-530325.html`

some sections are hidden like `people reading now`

i admit ads are gone but at expense of legitimate articles
@ryanbr

**Comment by ryanbr** [comment]
Sure, this will be safest
