### ISSUE TITLE
thequint.com

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6826]
### List the website(s) you're having issues:

`https://www.thequint.com/coronavirus/karnataka-imposes-night-curfew-from-10-pm-to-6-am-in-state-till-2-january`

### What happens?

Horrible empty ads placeholders

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: opera browser
- Adblock Extension/version: ublock origin 1.31

**Comment by THEtomaso** [comment]
@okiehsch: For **uBO Filters**?:
`thequint.com##.adunitContainer:upward(4)`
