### ISSUE TITLE
cointiply.com

### ISSUE THREAD

**Issue by stanislav-atr** [easylist/easylist#6827]
Original issue [here](https://github.com/AdguardTeam/AdguardFilters/issues/70393
).

Hello! It seems that EasyList blocks `||cointiply.com$` wich shares some scripts to other crypto-sharing domains and _is crypto-sharing domain by itself._

Login and register forms doesn't work, main page won't load correctly.

@ryanbr

**Comment by ryanbr** [comment]
Has been resolved, force an update.
