### ISSUE TITLE
kothamovies.link

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6828]
### List the website(s) you're having issues:

`http://www.kothamovies.link/hdmovies/telugu-2020-movies-download.html?page=0`

### What happens?

Fake download buttons

![Screenshot_2020-12-25-00-21-25-758_org mozilla fenix](https://user-images.githubusercontent.com/20338483/103103530-a7fe1100-4647-11eb-8141-00de05b170eb.png)

### List Subscriptions you're using:

Ublock origin default  lists

### Your settings

- OS/version: android
- Browser/version: firefox84
- Adblock Extension/version: ublock origin 1.31

### Other details:

This work
`||scurewall.co^$3p`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4cb105c755aeb54c76905449ffc45e4a7c113f77
