### ISSUE TITLE
cbsnews.com videos broke

### ISSUE THREAD

**Issue by jordanelliott23** [easylist/easylist#6829]
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.cbsnews.com/video/trump-issues-pardons-as-millions-wait-for-covid-19-financial-aid/)

if i disable easyprivacy it fixes it. so it is a filter in that list

**Comment by ryanbr** [comment]
Not enough details, works fine. Playback of video is fine.
