### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by ducng99** [easylist/easylist#6832]
### List the website(s) you're having issues:
```
youtube.com
```

### What happens?
In homepage, when clicking on any videos, the page will hang for 10 seconds then continue normally. 

### List Subscriptions you're using:
All uBlock filters
EasyPrivacy
EasyList

### Your settings

- OS/version: Windows 10 2004
- Browser/version: Firefox 84
- Adblock Extension/version: uBlock 1.31.0

### Other details:
~~Removing `www.youtube.com/api/stats/qoe` from EasyPrivacy fixes this.~~
Disabling EasyPrivacy fixed this, I haven't found out which exact rule.

**Comment by ryanbr** [comment]
Works fine for me.
