### ISSUE TITLE
c-api-bit.shopeemobile.com seller.shopee.sg

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#6837]
`https://c-api-bit.shopeemobile.com/tw/tr`
![圖片](https://user-images.githubusercontent.com/75058881/103146643-8d32b600-4787-11eb-9a72-ca4fe4c06f2e.png)

`https://seller.shopee.sg/api/pap/report`
![圖片](https://user-images.githubusercontent.com/75058881/103146661-bfdcae80-4787-11eb-86d7-2c355aca13a5.png)

**Comment by c2xusnpq6** [comment]
`https://c-api-bit.shopeemobile.com/tw/tr`
![圖片](https://user-images.githubusercontent.com/75058881/103157308-75d9e400-47ec-11eb-9517-96e5a3d6208a.png)

**Comment by ryanbr** [comment]
Not enough details, and no website/directions. closing.
