### ISSUE TITLE
About inwemo.com

### ISSUE THREAD

**Issue by Vetm** [easylist/easylist#684]
I'm the Co-Founder and main developer of Inwemo. It's really sad for us to see that we ended up on your list. We understand that in-browser mining hasn't had the best start with miners secretly running in the background without the user knowing. With Inwemo we wanted to try a different approach. We have a mandatory opt-in for every website that uses Inwemo to ensure that our miner only runs when the user explicitly allows it – **the mining will never happen without the user's consent**.

With your current solution our consent will be shown to the user but the mining wont start even if he hits the "I agree"-button.

Our goal is to offer a user-friendly and non-intrusive alternative to ads. We do everything we can to be as transparent and fair as possible to everyone.

We'd be very grateful for any suggestions for changes on our product that might get us removed from your list. If there's nothing we can do, we'll of course accept your decision and won't try stuff like domain rotation etc.

We're happy to hear your thoughts!

**Comment by SMed79** [comment]
Inwemo is blocked in Easyprivacy list, which is not the default adblock list.
