### ISSUE TITLE
seithy.com

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6857]
### List the website(s) you're having issues:

`https://www.seithy.com`
`https://www.seithy.com/breifNews.php?newsID=258161&category=TamilNews&language=tamil`

### What happens?
3rd party promotion banners ads

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win 10
- Browser/version: opera stable
- Adblock Extension/version: 1.31

**Comment by ghajini** [comment]
some missed ads/promotions
`https://www.seithy.com/index.php`
like
![Screenshot (42)](https://user-images.githubusercontent.com/20338483/103452683-ff5f4980-4cf7-11eb-9979-e738cfbbb21a.png)
![Screenshot (44)](https://user-images.githubusercontent.com/20338483/103452685-0b4b0b80-4cf8-11eb-9cd0-a1f4dfd9f657.png)

filters=
```
www.seithy.com##.slick-slider.slick-initialized.toppageadsindexheader
www.seithy.com###ads400px
```

**Comment by THEtomaso** [comment]
> ```
> www.seithy.com##.slick-slider.slick-initialized.toppageadsindexheader
> www.seithy.com###ads400px
> ```

That seems to cause some unwanted breakage (e.g. videos in the sidebar).

@ghajini:
How about these rules..
Do they break anything?
```
seithy.com##.ads400pxinner
seithy.com##.briefNewsAd
seithy.com##[src^="siteadmin/bannerads/"]:upward(3)
seithy.com#?#div:-abp-contains(ிறப்பு விளம்பரம்)
seithy.com#?#td:-abp-has(.toppageadsindexheader)
```
PS: The third rule contains a uBO-only syntax.
It gets rid of a small ad box, at the top of the article sidebar.

**Comment by ghajini** [comment]
After ubo added 
`##.slick-track`

This is only required then
`www.seithy.com##div.ads400pxinner`
Which is abp compatible (no needed ubo syntax)

**Comment by THEtomaso** [comment]
> This is only required then
> `www.seithy.com##div.ads400pxinner`

Not at my end:

![filterissue-seithy-1](https://user-images.githubusercontent.com/9382674/103482034-b8984f00-4dde-11eb-972e-04d2b8c93917.jpg)

![filterissue-seithy-2](https://user-images.githubusercontent.com/9382674/103482036-b9c97c00-4dde-11eb-9cd8-8309859b619b.jpg)

**Comment by ghajini** [comment]
Whatever you referring is ads placeholders,original ads issue will be taken care by `www.seithy.com##div.ads400pxinner`

Having to add another cosmetic filters for ads placeholders is already overhead on small mobile devices....
There are many news sites where you will such minor issues (ads placeholders)
