### ISSUE TITLE
wplift.com

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#686]
```
-social-icons/
```
```
-click-tracking/
```
<span>https://</span>wplift.com/customer-loyalty-woocommerce

**Comment by peace2000** [comment]
@smed79 is this still relevant?

**Comment by smed79** [comment]
https://github.com/easylist/easylist/blob/d3c858d6f78f4f9ce03c93e9a6d2864b316241e1/fanboy-addon/fanboy_social_general_block.txt#L161
