### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6861]
### List the website(s) you're having issues:
```
https://uqqn.giampaolocorona.it/zte-z851m-unlock-done.html
https://zsi.mumat.it/communication-unit-4-lop-8-vietjack.html
http://ep.circee.it/web-series-download-website.html
http://cd.medicalfisiocenter.it/original-web-series-download.html
http://el.quattrucanti.it/web-series-download-website.html
http://ubiy.volcam.it/9xbuddy-zee5-download.html
http://dg.millerighesrl.it/original-web-series-download.html
https://www.asiantoko.nl/varmilo-keyboard-flqnt/bengali-web-series-download-telegram-channel.html
http://dh.onoranzefunebrisgambelluri.it/web-series-mod-apk.html
http://cj.highschoolnotes.it/ullu-originals-web-series.html
http://du.gsvillafranca.it/ghapa-ghap-web-series-cast.html
https://klavierlehrerkoeln.de/cat-3116-dbq5y/web-series-download.html
http://dt.chiaradp.it/all-web-series-list.html
http://cm.elfo-srl.it/web-series-cast.html
http://er.fratievangelo.it/hoichoi-tv-series-list.html
http://ca.associazioneisalotti.it/all-web-series-list-2019.html
```

### What happens?

Some `.it` clearly serves redirecting ads/trackers
I searched on google `hoichoi movie free download`
[`https://www.google.com/search?q=hoichoi+movie+free+download&oq=hoichoi+movie+free+download&gs_l=mobile-heirloom-hp.12...0.0.1.1124.0.0.0.0.0.0.0.0..0.0....0...1c..34.mobile-heirloom-hp..0.4.136.-HRr2nltCV0`]
To my surprise first 13 pages of google search( crap .it/.de domains) serves mainly ads

### List Subscriptions you're using:

Ublock origin default  lists

### Your settings

- OS/version: win10/android 
- Browser/version: opera browser stable/firefox
- Adblock Extension/version: 1.31

### Other details:

These domains need to block (attached virustotal reports)
```
||bnmjjwinf292.com^
||h8bjfdcu.com^

||37.1.209.213^ 
{https://www.virustotal.com/gui/url/b425ba3db91e69ad81a95411e9e325c921bd0ee6bbd79761eb8c9a00f817f6ee/detection}

||bestprizeday.life^

||watch-video.net^
{https://www.virustotal.com/gui/domain/watch-video.net/detection}

||findmedia.biz^

||polimer.xyz^ {https://www.virustotal.com/gui/domain/polimer.xyz/detection}

||bingstyle.com^
{https://www.virustotal.com/gui/url/d0195df0a7c8c7a3dfc8f061b977d8014544902624fb7347eb2aa7b6180bea11/detection}

||zctrack.com^
{https://www.virustotal.com/gui/domain/zctrack.com/detection}

||macotuqa.xyz^
```

**Comment by ryanbr** [comment]
Since the end domains change so often.

The best way to defeat these fake sites is to target the clickthrough servers, so all the urls each popup goes through (normally 2-4).

**Comment by ghajini** [comment]
Please add meanwhile
```
||h8bjfdcu.com^
||37.1.209.213^ 
||bestprizeday.life^
||watch-video.net^
||findmedia.biz^
||polimer.xyz^
||bingstyle.com^
||zctrack.com^
||macotuqa.xyz^
```

It will benefit all users on all adblockers

**Comment by ryanbr** [comment]
See my first post, targeting the end sites will be pointless. targeting the clickthrough servers.

**Comment by ghajini** [comment]
Okay
