### ISSUE TITLE
imdb.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6864]
### List the website(s) you're having issues:

`https://www.imdb.com/name/nm0661200/`

### What happens?

Placeholder on the right.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/103352161-badc6f80-4aa5-11eb-8b10-f4b509bb066a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.32.5b0 + IDCAC 3.2.6

### Other details:

I propose `imdb.com#?#.aux-content-widget-2:-abp-has(.ab_zergnet)`

![image](https://user-images.githubusercontent.com/22780683/103352473-98972180-4aa6-11eb-80b3-9eb976931b2f.png)

**Comment by ryanbr** [comment]
Too minor to add
