### ISSUE TITLE
apnews.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6866]
### List the website(s) you're having issues:

```
https://apnews.com/
https://apnews.com/article/international-news-hong-kong-china-beijing-cb9bdfc5dd1db875d42203f2e018de8a
```

### What happens?

Some placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/103352161-badc6f80-4aa5-11eb-8b10-f4b509bb066a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.32.5b0 + IDCAC 3.2.6

### Other details:

I propose:
```
! https://apnews.com/
apnews.com##.FeedAd
! https://apnews.com/article/international-news-hong-kong-china-beijing-cb9bdfc5dd1db875d42203f2e018de8a
apnews.com##div[class^=Component-dfp-]
```
![image](https://user-images.githubusercontent.com/22780683/103353295-c5e4cf00-4aa8-11eb-8a45-fb416de0a36b.png)

![image](https://user-images.githubusercontent.com/22780683/103353245-a8b00080-4aa8-11eb-9917-f5c90e719c06.png)

**Comment by ryanbr** [comment]
Was fixed earlier, closing
