### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6868]
### List the website(s) you're having issues:

`https://timesofindia.indiatimes.com/life-style/relationships/work`

### What happens?

Many placeholders in the feeds.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/103352161-badc6f80-4aa5-11eb-8b10-f4b509bb066a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.32.5b0 + IDCAC 3.2.6

### Other details:

I propose:
```
indiatimes.com#?#.md_news_box:-abp-has(> div[data-ad-id])
indiatimes.com##li[data-native-tmpl]
||timesofindia.indiatimes.com/photo/62210981.cms^$image
```

![image](https://user-images.githubusercontent.com/22780683/103353987-a0f15b80-4aaa-11eb-875c-7b54f2211339.png)

![image](https://user-images.githubusercontent.com/22780683/103353997-acdd1d80-4aaa-11eb-99f4-1e8fa003a4db.png)

**Comment by ghajini** [comment]
**Toi network sites**=

Ads/ads placeholders

**Platform=*

Google chrome stable, firefox android/firefox stable 

**URLs =**
```
Maharashtratimes.com
timesofindia.indiatimes.com
m.timesofindia.com
navbharattimes.indiatimes.com
vijaykarnataka.com
malayalam.samayam.com
telugu.samayam.com
tamil.samayam.com
eisamay.indiatimes.com
www.iamgujarat.com
```
**Filters=**

```
timesofindia.indiatimes.com##[href="https://timesofindia.indiatimes.com/amazon-bestsellers"]
m.timesofindia.com##[href="https://timesofindia.indiatimes.com/amazon-bestsellers"]
||timesofindia.indiatimes.com/amazonslider.cms$subdocument
maharashtratimes.com##[href^="https://maharashtratimes.com/best-deals-online"]
navbharattimes.indiatimes.com##.ad1
navbharattimes.indiatimes.com##[href^="https://navbharattimes.indiatimes.com/best-deals-online"]
vijaykarnataka.com##.colombia
vijaykarnataka.com##.ad1
malayalam.samayam.com##.colombia
malayalam.samayam.com##.ad1
telugu.samayam.com##[href^="https://telugu.samayam.com/best-deals-online"]
telugu.samayam.com##.colombia
tamil.samayam.com##.colombia
tamil.samayam.com##.ad1
eisamay.indiatimes.com##.ad1
www.iamgujarat.com##.colombia
www.iamgujarat.com##.ad1
```

I have not generalised filters, left to you all
