### ISSUE TITLE
mywindowshub.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6872]
### List the website(s) you're having issues:

```
https://mywindowshub.com/
https://mywindowshub.com/windows-and-education-how-microsoft-windows-make-students-life-easier/
```

### What happens?

Various placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/103352161-badc6f80-4aa5-11eb-8b10-f4b509bb066a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.32.5b0 + IDCAC 3.2.6

### Other details:

I propose:
```
! https://mywindowshub.com/
mywindowshub.com##.td-g-rec
mywindowshub.com#?#.td-pb-span12:-abp-has(.adsbygoogle)
! https://mywindowshub.com/windows-and-education-how-microsoft-windows-make-students-life-easier/
mywindowshub.com#?#.textwidget:-abp-has(script[src*="adsbygoogle.js"])
```

![image](https://user-images.githubusercontent.com/22780683/103355109-bae06d80-4aad-11eb-9656-f829025f97ae.png)

![image](https://user-images.githubusercontent.com/22780683/103355144-d186c480-4aad-11eb-8f6f-405a17fbac36.png)

**Comment by ryanbr** [comment]
Such a minor white space issue, for 3 filters, I'll leave it
