### ISSUE TITLE
fla.de

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6878]
### List the website(s) you're having issues:

`https://www.fla.de/`

### What happens?

A first-party crossword banner is incorrectly blocked by `/adnetwork/*` in EasyList.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/103409618-ecb60a80-4b67-11eb-88ef-9e5aeba55715.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.32.5b0 + IDCAC 3.2.6

### Other details:

I propose adding `@@/adnetwork/*$domain=fla.de` to EasyList, so that the exception rule doesn't need to be in Dandelion Sprout's Nordic Filters anymore.

Without the fix: 
![image](https://user-images.githubusercontent.com/22780683/103411262-51c12e80-4b6f-11eb-940e-7d3c122a7ae6.png)

With the fix: 
![image](https://user-images.githubusercontent.com/22780683/103411244-3ce49b00-4b6f-11eb-94ab-4c6f9dfa2211.png)

**Comment by ryanbr** [comment]
Easylist will fix faults, but an incorrectly blocked first-party banner, no @Yuki2718

**Comment by Yuki2718** [comment]
@ryanbr You mean it should be fixed in Unbreak?

**Comment by Khrin** [comment]
> 
> 
> @ryanbr You mean it should be fixed in Unbreak?

I think should be fixed by Nordic Filters, if it's really necessary.

**Comment by DandelionSprout** [comment]
Seems a bit strange for Fanboy to @ Yuki about it, then.

**Comment by Yuki2718** [comment]
> Seems a bit strange for Fanboy to @ Yuki about it, then.

I guess he actually meant you.

**Comment by ryanbr** [comment]
hmm error
