### ISSUE TITLE
canariajournalen.no

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6880]
### List the website(s) you're having issues:

`https://canariajournalen.no/Nyheter/Melder-fuktig-nyttaarshelg-paa-Kanarioeyene`

### What happens?

A first-party donation banner is (presumably) incorrectly blocked by `/images/ads-$domain=~ads.com` in EasyList.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/103409618-ecb60a80-4b67-11eb-88ef-9e5aeba55715.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.32.5b0 + IDCAC 3.2.6

### Other details:

I propose adding `@@/images/ads-db/right-tower/vipps-sponsor-$domain=canariajournalen.no` to EasyList, so that the exception rule doesn't need to be in Dandelion Sprout's Nordic Filters anymore.

Without the fix: 
![image](https://user-images.githubusercontent.com/22780683/103411501-a3b68400-4b70-11eb-81b0-138c9c6741ec.png)

With the fix: 
![image](https://user-images.githubusercontent.com/22780683/103411518-bb8e0800-4b70-11eb-9af6-84d3a59cd987.png)

**Comment by ryanbr** [comment]
Is it really that important to fix this? I'd recommend the site adjust it
