### ISSUE TITLE
microsoft.com/security/blog

### ISSUE THREAD

**Issue by kevinoid** [easylist/easylist#6882]
### List the website(s) you're having issues:

https://www.microsoft.com/security/blog/

### What happens?

The page appears empty except for a gray background.

### List Subscriptions you're using:

EasyList Cookie

### Your settings

uBlock Origin default settings + EasyList Cookie

- OS/version: Linux 5.11.0-rc1
- Browser/version: Firefox Nightly 86.0a1 (2020-12-30) (64-bit)
- Adblock Extension/version: uBlock Origin v1.32.2

### Other details:

It appears that the topmost div on the page has `id="ms-cookie-banner"`, which is hidden by https://github.com/easylist/easylist/blob/ec7c8bc5d24812e5a1c2d89293f7b1bda35142b1/easylist_cookie/easylist_cookie_general_hide.txt#L5105

Thanks,
Kevin

**Comment by kevinoid** [comment]
Note: I'm currently using

    microsoft.com#@##ms-cookie-banner

as a workaround, which solves the issue for me.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/fc1a4015f29a3cd0f0e8a2da9356730974d06ed4
