### ISSUE TITLE
tvline.com

### ISSUE THREAD

**Issue by PlaceboPRS** [easylist/easylist#6907]
### List the website(s) you're having issues:

`https://tvline.com/`

### What happens?

Side panels get moved to the bottom of the page instead of being on the side.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/23120453/103742286-db06b400-4ffa-11eb-81cc-fe950d506cff.png)

### Your settings

- OS/version: Windows 10 x64 20H2
- Browser/version: Waterfox Classic 2020.10 (64-bit)
- Adblock Extension/version: uBlock Origin 1.32.4

### Other details:

Without Easylist:

![image](https://user-images.githubusercontent.com/23120453/103742181-b3175080-4ffa-11eb-82a2-d5d3cb8870e8.png)

With Easylist:

![image](https://user-images.githubusercontent.com/23120453/103742223-c32f3000-4ffa-11eb-8524-b42af697e320.png)
![image](https://user-images.githubusercontent.com/23120453/103742238-c9bda780-4ffa-11eb-9f59-361b3b2c05bf.png)

**Comment by ryanbr** [comment]
Seems to be fine now? force an update of the lists.

**Comment by PlaceboPRS** [comment]
Yep all good now thanks :)
