### ISSUE TITLE
Does Easylist have these or other lists in it?

### ISSUE THREAD

**Issue by EC-O-DE** [easylist/easylist#691]
**Dan Pollock’s** hosts file?

**hpHosts’ Ad and tracking** servers?

**MVPS HOSTS**?

**Peter Lowe’s Ad and tracking** server list?

I use Opera's internal ad-blocker with Easylist (I dunno is it with element rules...) and uMatrix which has ^ those other lists. I'm thinking if I could perhaps use less lists <_<    ^_^

**Comment by IDKwhattoputhere** [comment]
No, it doesn't contain these lists but there's some similarities in what these lists block. The way I see it it's your choice to make:

Keep lists: Potentially more gets blocked but slightly more ressources are used.

Less lists: Potentially less gets blocked but slightly less ressources are used.

I personally would keep the lists.
