### ISSUE TITLE
spreadshirt.fr

### ISSUE THREAD

**Issue by momala454** [easylist/easylist#6918]
### List the website(s) you're having issues:
`https://www.spreadshirt.fr/`

### What happens?
Easylist cookie hide the cookie acceptance popup, but it prevent any clicking on the website

### List Subscriptions you're using:
easylist fr + easylist cookie

### Your settings

- OS/version: windows
- Browser/version: firefox
- Adblock Extension/version: ublock origin

### Other details:

![image](https://user-images.githubusercontent.com/83005/103879293-f3003580-50d7-11eb-8e6a-eb39606fc3d8.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/452b23d7eaee59920670065f9517c8673ebc4399
