### ISSUE TITLE
riverbender.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6919]
### List the website(s) you're having issues:

```
https://www.riverbender.com/sports-news/details.cfm?id=327873
https://www.riverbender.com/articles/details/two-charged-in-connection-of-the-stallon-drug-raid-in-wood-river-46877.cfm
https://www.riverbender.com/index.cfm
```

### What happens?

Quite a few placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/103886806-5727f700-50e2-11eb-9be7-5f57cbdd4698.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.88 x64
- Adblock Extension/version: uBO 1.32.5b7 + IDCAC 3.2.6

### Other details:

I propose:
```
! https://www.riverbender.com/sports-news/details.cfm?id=327873
###ap-300-600
###ap-300-250
! https://www.riverbender.com/articles/details/two-charged-in-connection-of-the-stallon-drug-raid-in-wood-river-46877.cfm
###injected-300x250
###article-banner
! https://www.riverbender.com/index.cfm
riverbender.com##div[id^=ros-]
```

![image](https://user-images.githubusercontent.com/22780683/103886686-2c3da300-50e2-11eb-86d0-daf5b15f1fea.png)

![image](https://user-images.githubusercontent.com/22780683/103886642-192ad300-50e2-11eb-93c5-29ef3c138e16.png)

![image](https://user-images.githubusercontent.com/22780683/103886779-4b3c3500-50e2-11eb-9715-d5d14fdbf626.png)

**Comment by ryanbr** [comment]
Has been fixed
