### ISSUE TITLE
Ad-blocking to the cloud? By DNS!

### ISSUE THREAD

**Issue by EC-O-DE** [easylist/easylist#692]
Easylist and uBlock Origin and others - it would be great to have ad-blocking done at server side.

**OpenNIC** might be interested to setup DNS servers where ads could be filtered by common lists such as Easylist and Easyprivacy etc.

https://www.opennic.org/

**Comment by lewisje** [comment]
It's a nice layer of protection, but this sort of thing can only be done domain-by-domain, and most of the filter patterns are based on more granular URL patterns.

I haven't seen many efforts to set up free public ad-blocking DNS servers, but I remember that FoolDNS tried (and works poorly at resolving legitimate DNS requests) and Comodo Secure DNS and Norton DNS work fine (but don't actually block many advertising domains, preferring to focus specifically on malware and, at the higher free tiers of Norton DNS, on potentially objectionable content).

**Comment by EC-O-DE** [comment]
Cisco's OpenDNS has opt-in ad-blocking but it's Cisco.. ;)
Plus they let through Google's unintrusive ads (small text adds) but other than that they're blocking seems effective.

I'd of course set up Easylist on my router if I would have proper access to it.

**Comment by ryanbr** [comment]
Nothing stopping OpenNIC using Easylist/Easyprivacy, or converting it with their tools.
