### ISSUE TITLE
imgur.com (anti-adb)

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#6923]
`https://imgur.com/upload`

`/floaty_rotator` **EasyList**

Test request, example: `https://s.imgur.com/desktop-assets/js/floaty_rotator.1ad17bdeab12edae204b.bundle.js`

**Comment by ryanbr** [comment]
Which anti-adblock is this?  @dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@ryanbr 
[Gif](https://imgur.com/vPTUFzP)

**Comment by THEtomaso** [comment]
FYI; If you're using uBO, you'll have to disable uBO filters first, in order to reproduce the issue, since that filter already has a fix in place (not ABP-compatible):
https://github.com/uBlockOrigin/uAssets/blob/2820c06e2c40fa0836c926407795e5d27fb86284/filters/filters-2021.txt#L294

**Comment by krystian3w** [comment]
Why not mp4?


https://user-images.githubusercontent.com/35370833/104112656-d9d2d100-52f1-11eb-84f6-ea02c5c52960.mp4

![obraz](https://user-images.githubusercontent.com/35370833/104112662-e5be9300-52f1-11eb-8f1b-dda8e377198d.png)

**Comment by krystian3w** [comment]
Possible whitelist for small group (AdBlock/ABP/Brave) in "adblock removal warning".

**Comment by ryanbr** [comment]
Has been fixed. force an update

**Comment by okiehsch** [comment]
> Since the script, mentioned in the first post, probably will have to be whitelisted in EasyList, you might want to add something like this to UBO filters:

Why do you think I should block that request?

**Comment by THEtomaso** [comment]
I'm thinking more like why not?
..since it's a anti-adblock script, which doesn't have to be allowed, when using uBO.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/104121231-f6e0c180-533c-11eb-9445-7ca875542489.png)

I don't see the need to block it.

>  which doesn't have to be allowed

It is not specifically allowed, the blocking filter was removed from EasyList.
Assuming that https://github.com/uBlockOrigin/uAssets/blob/2820c06e2c40fa0836c926407795e5d27fb86284/filters/filters-2021.txt#L294 had not occured yet and  you would have opened the anti-adblock issue today I would have added the script-injection and not bothered about the first party script.
The script injection makes that script irrelevant imo.
