### ISSUE TITLE
interest.co.nz

### ISSUE THREAD

**Issue by dddlr** [easylist/easylist#6930]
### List the website(s) you're having issues:

Virtually all pages under `interest.co.nz`, e.g.:

`https://www.interest.co.nz/privacy`
`https://www.interest.co.nz/personal-finance/108553/gold-and-other-precious-metals-are-out-favour-asset-bubbles-mushroom`
`https://www.interest.co.nz/economic-calendar`

### What happens?

An anti-adblock modal blocks the entire page, preventing the page contents from being viewed.

### List Subscriptions you're using:

Only EasyList

### Your settings

- OS/version: Linux
- Browser/version: Chromium latest
- Adblock Extension/version: uBlock Origin 1.31.2. I also have uBlock Origin Extra but it doesn't seem to affect it.

### Other details:

`https://www.interest.co.nz/sites/all/modules/custom/press_patron/js/pp-ablock-banner.js?qlilqj` sets `ad_block_test_pass` to true, while `https://www.interest.co.nz/sites/all/modules/custom/press_patron/js/pp-ablock-banner.js?qlilqj` checks the value of `ad_block_test_pass` (not sure if there are other scripts involved).

![2021-01-09-192921_1113x373_grim](https://user-images.githubusercontent.com/2908767/104084992-fe5a8900-52b0-11eb-86bb-b8b9c6e4b8d8.png)

EasyList currently blocks only `pp-ablock-banner.js` so `ad_block_test_pass` is undefined, causing the anti-adblock modal to display.

**Comment by ryanbr** [comment]
resolved
