### ISSUE TITLE
resetera.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6931]
### List the website(s) you're having issues:

`https://www.resetera.com/threads/former-gamexplain-members-talk-about-troubles-with-the-company-heavy-crunch-low-pay.357772/`

### What happens?

Some placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/104091632-dbaf7c80-527e-11eb-90fe-50f70edefeab.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.141 x64
- Adblock Extension/version: uBO 1.32.5b9 + IDCAC 3.2.6

### Other details:

I propose `resetera.com##.samCodeUnit`

![image](https://user-images.githubusercontent.com/22780683/104091579-81aeb700-527e-11eb-8689-dfd1e71af5fc.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c128ced9bcd0937dd93afee81483a88d76ca9fa6
