### ISSUE TITLE
coingolive.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6955]
### List the website(s) you're having issues:

`https://coingolive.com/en/`

### What happens?

Some ad banners for `bitPreço`, `BPDex` and/or `Coinext`.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/104125961-4a153d00-535a-11eb-93ff-7af9913ab657.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.141 x64
- Adblock Extension/version: uBO 1.32.5b9 + IDCAC 3.2.6

### Other details:

The site's English-language translation seems to be sufficiently completed, that the ads should be reported here instead of to EasyList Portuguese.

I propose `||coingolive.com/assets/img/partners^`

![image](https://user-images.githubusercontent.com/22780683/104126036-9e202180-535a-11eb-8735-6257269dcb22.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e3e198d29810af85c0d921c995d537395b743151
