### ISSUE TITLE
is this line in the file "easyprivacy_trackingservers_international.txt" wrong?

### ISSUE THREAD

**Issue by Jumeo7** [easylist/easylist#696]
https://github.com/easylist/easylist/blob/a95f0c0066b283a878c0bf63e62186e3259f119a/easyprivacy/easyprivacy_trackingservers_international.txt#L390

**Comment by Jumeo7** [comment]
Maybe it should be `||irs01.com^$third-party`, like the other lines.

**Comment by ryanbr** [comment]
Would most likely be added to cover various domain changes. Some domains will have multiple regional suffix's
