### ISSUE TITLE
darknetdaily.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#6965]
### List the website(s) you're having issues:

`https://darknetdaily.com/?p=990`

### What happens?

An ad for `Ledger Nano X`.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/104133529-78a80d80-5384-11eb-986e-d171eca9b40c.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.141 x64
- Adblock Extension/version: uBO 1.32.5b9 + IDCAC 3.2.6

### Other details:

I propose `3-0-0x2-5-0`

![image](https://user-images.githubusercontent.com/22780683/104133519-64fca700-5384-11eb-845d-2fa24469fae3.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9a9698a19eb63fdf986759360b78795701683b47
