### ISSUE TITLE
EasyPrivacy breaks AuthedMine captcha

### ISSUE THREAD

**Issue by coinhive-com** [easylist/easylist#697]
`||authedmine.com^$third-party` is blocked by EasyPrivacy which breaks the Captcha, making signup and contact forms unusable.

There is no need to block AuthedMine. The scripts hosted on AuthedMine.com NEVER start mining without an explicit opt-in. Also, AuthedMine doesn't track users in any way.

More info about AuthedMine: https://authedmine.com

More info about privacy: https://coinhive.com/info/privacy

Please remove authedmine.com from the EasyPrivacy list.

**Comment by Khrin** [comment]
Please can you give a valid example on where this script is used?

**Comment by coinhive-com** [comment]
The contact form on our Website uses the AuthedMine Captcha:

https://coinhive.com/contact

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/bd754db077e1fb35fae13b491920e61f35b0d2e0

**Comment by coinhive-com** [comment]
Pardon my ignorance, but just whitelisting the captcha.min.js doesn't seem to work.

The captcha itself still loads the `https://authedmine.com/lib/authedmine.min.js` and needs to connect to the websocket servers at `ws://ws001.authedmine.com`.

What the reason to block the whole authedmine.com domain in the first place?
