### ISSUE TITLE
NSFW desipron.xyz

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6980]
### List the website(s) you're having issues:

**NSFW**
`https://desipron.xyz/mov-52487545`

### What happens?

popup ads

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: opera stable
- Adblock Extension/version: _ublock origin_ stable

### Other details:
can be added 
`||bulletprofitpop.com^`

**Comment by spirillen** [comment]
`desipron.xyz` seems dead, I can't get any info beside WHOIS
