### ISSUE TITLE
adultgamestop.bigtopsites.com (NSFW)

### ISSUE THREAD

**Issue by throwaway282630101** [easylist/easylist#6983]
### List the website(s) you're having issues:

`adultgamestop.bigtopsites.com`

### What happens?

Hello, and thank you for your work with Easylist!

Scroll down and there should be gif banners even at the bottom of the page.

- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin

**Comment by spirillen** [comment]
To complete this domain there is actually a rather long list with anoying banners, But personally, It shouldn't matter, as it is a link site (commercial links)

But the current full list is:
```
adultgamestop.bigtopsites.com
arterotic.bigtopsites.com
bigtopsites.com
bikinicabana.bigtopsites.com
bikinicabana.bigtopsites.com 
hentaisexsites.bigtopsites.com
infantasy.bigtopsites.com
pin-upvixens.bigtopsites.com
pinupgirlstop100.bigtopsites.com
top50freikorperkultur.bigtopsites.com
topfigure.bigtopsites.com
www.adultgamestop.bigtopsites.com
www.arterotic.bigtopsites.com
www.bigtopsites.com
www.bikinicabana.bigtopsites.com
www.bikinicabana.bigtopsites.com 
www.hentaisexsites.bigtopsites.com
www.infantasy.bigtopsites.com
www.pin-upvixens.bigtopsites.com
www.pinupgirlstop100.bigtopsites.com
www.top50freikorperkultur.bigtopsites.com
www.topfigure.bigtopsites.com
```

List copied from <https://www.mypdns.org/T3929> and that list was generated based on this issue :smiley: so thanks for spreading the word @throwaway282630101
