### ISSUE TITLE
Cookies: owasp.org

### ISSUE THREAD

**Issue by DRSDavidSoft** [easylist/easylist#6984]
### List the website(s) you're having issues:

```
https://owasp.org/www-project-modsecurity-core-rule-set/
```

### What happens?

The `.disclaimer-container` is shown at the bottom of the page with the following message:

> This website uses cookies to analyze our traffic and only share that information with our analytics partners.

### List Subscriptions you're using:

**EasyList Cookie**

### Your settings

- OS/version: Win 10
- Browser/version: Chrome latest
- Adblock Extension/version: uBlock Origin 1.31.2

### Other details:

n/a

**Comment by krystian3w** [comment]
try:

`###disclaimer-container`
