### ISSUE TITLE
BugSnag CDN (inadvertently?) blocked

### ISSUE THREAD

**Issue by cagerton** [easylist/easylist#6986]
The official BugSnag CDN was blocked by a commit which, given that the commit message, was likely meant for a different target: https://github.com/easylist/easylist/commit/ce1f0e32b6863ad37485efb81f1248e0585a041b 

Specifically, `d2wy8f7a9ursnm.cloudfront.net` is a CloudFront CDN deployment which hosts widely used error reporting software and is described here: https://docs.bugsnag.com/platforms/javascript/cdn-guide/

**Comment by krystian3w** [comment]
Maybe due serve ads.

We can block serve ads on BugSang level privileges?

**Comment by ryanbr** [comment]
We're already blocking bugsnag, due to tracking/privacy.
`easyprivacy/easyprivacy_trackingservers.txt:||bugsnag.com^$third-party`
