### ISSUE TITLE
https://twitter.com/compose/tweet/unsent/scheduled

### ISSUE THREAD

**Issue by 0xbadfca11** [easylist/easylist#6995]
### List the website(s) you're having issues:
`https://twitter.com/compose/tweet/unsent/scheduled`

### What happens?
I can't see the stock of scheduled tweets.

### List Subscriptions you're using:
Unchecked all filters other than easylist cookie, still happens.

### Your settings
I haven't used any of the extensions in the comments here.

- OS/version: Windows 8.1
- Browser/version: Firefox 84.0.2
- Adblock Extension/version: uBlock origin 1.32.4

### Other details:
`twitter.com##.r-13qz1uu.r-1w50u8q` cause this.

**Comment by ZacharyTalis** [comment]
I'm having an issue with the same rule (which was also just added to Fanboy's Annoyance).

`twitter.com##.r-13qz1uu.r-1w50u8q` blocks the alt-text input box on `https://twitter.com/compose/tweet/media`.

**Comment by ryanbr** [comment]
Filter was removed a while back, thanks for the report @ZacharyTalis
