### ISSUE TITLE
msn.com (cookies)

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/easylist#6996]
### List the website(s) you're having issues:

`https://www.msn.com/en-xl/lifestyle/health/coronavirus`

### What happens?

Microsoft and our third-party vendors use cookies

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-01-14_134940](https://user-images.githubusercontent.com/57287308/104587266-5e657c80-566f-11eb-824f-b6688a7a0a65.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/104311922-8ffb0e00-54de-11eb-9ba9-c9217d860aa3.png)
</details>

### Your settings

- OS/version:  Windows 8.1 embedded industry enterprise
- Browser/version:  Google Chrome
- Adblock Extension/version:  uBO 1.32.4

**Comment by krystian3w** [comment]
Should need exclude broken 3p videos libs (e.g. embeded YouTube on MSN).

**Comment by ryanbr** [comment]
$generichide causing an issue.

https://github.com/easylist/easylist/commit/4345956040a341d87e98cce5812ed87d997ed715
