### ISSUE TITLE
NSFW sortporn.com

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6998]
### List the website(s) you're having issues:

NSFW

`https://www.sortporn.com/videos/81811/super-cute-n-hot-banged-in-doggy-style/`

### What happens?

unblocked ads
popup ads

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: firefox stable
- Adblock Extension/version: 1.32.4

**Comment by spirillen** [comment]
```
sortporn.com###player_add
sortporn.com##.sponsor
sortporn.com##.table
sortporn.com##.footer-margin
sortporn.com###lotal
```
