### ISSUE TITLE
NSFW 4kporn.xxx

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#6999]
### List the website(s) you're having issues:
NSFW
`https://4kporn.xxx/videos/27032/sauteli-maa-k-saath-chodai-fucked-with-step-milf/`

### What happens?

unblocked ads
banner ads

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: firefox stable
- Adblock Extension/version: 1.32.4

**Comment by spirillen** [comment]
```
4kporn.xxx##.table
4kporn.xxx##.footer-margin
```
