### ISSUE TITLE
(NSFW) motherless.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7002]
### List the website(s) you're having issues:

`https://motherless.com/8195207`

### What happens?

Some placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/104638940-1cf0c380-56a7-11eb-9645-d940f1a0f1f2.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.141 x64
- Adblock Extension/version: uBO 1.32.5b10 + IDCAC 3.2.7

### Other details:

I propose:
```
! Desktop mode
motherless.com##.col-md-12 > div[class="content-wrapper "]
motherless.com##.above-footer-banners
! Mobile mode
motherless.com###content > .text-center
motherless.com##.control-box > .text-center
```

Note that desktop and mobile mode refer to two buttons on the far bottom of the page.

**Comment by spirillen** [comment]
I'll suggest to add this as well

```
/view/popup$important
```

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +440 | /view/popup$important | -- | motherless.com | 1 | xhr | `https://motherless.com/view/popup?codename=0DF9099&nostat=1` |
| +246 |  |  | motherless.com | 1 | xhr | `https://motherless.com/view/popup?codename=A35782E&nostat=1` |

`?codename=A35782E` = URI

```
https://motherless.com/A6924B2
/view/popup$important | -- | motherless.com | 1 | xhr | `https://motherless.com/view/popup?codename=A6924B2&nostat=1` |
```

**Comment by ryanbr** [comment]
Seems fine here, happy to leave it.
