### ISSUE TITLE
zombooru.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7003]
### List the website(s) you're having issues:

`http://www.zombooru.com/post/view/80650`

### What happens?

Placeholder near the top.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/104638940-1cf0c380-56a7-11eb-9645-d940f1a0f1f2.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.141 x64
- Adblock Extension/version: uBO 1.32.5b10 + IDCAC 3.2.7

### Other details:

I propose `zombooru.com##.banner_hor`

![image](https://user-images.githubusercontent.com/22780683/104640702-20854a00-56a9-11eb-8c9e-1546d7e9d89f.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/529987b88f0d432e83df77629c38db5a4adcc972
