### ISSUE TITLE
(NSFW) asian-teens.co

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7007]
### List the website(s) you're having issues:

`https://asian-teens.co/videos/48193/vacme-vacbed-solo-with-vibrator-struggle/`

### What happens?

Ads in the lower left.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/104667194-cfd81600-56d5-11eb-93b6-078758607d99.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 87.0.4280.141 x64
- Adblock Extension/version: uBO 1.32.5b10 + IDCAC 3.2.7

### Other details:

I propose `||parkurl.com^`

![image](https://user-images.githubusercontent.com/22780683/104667160-b8992880-56d5-11eb-8892-c561a20b006f.png)

**Comment by spirillen** [comment]
`parkurl.com` is ownen and driven by [0i0i0i0.com](https://www.mypdns.org/T534) So I'm second that suggestion

**Comment by ryanbr** [comment]
Done
