### ISSUE TITLE
twitter.com (cookies)

### ISSUE THREAD

**Issue by soshial** [easylist/easylist#7014]
### List the website(s) you're having issues:
`https://twitter.com/home`

### What happens?

![image](https://user-images.githubusercontent.com/100644/104798676-1a46b900-57e2-11eb-9195-d72a030ed494.png)

### List Subscriptions you're using:

Easylist Cookies

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: uBlock

**Comment by ryanbr** [comment]
Should be fixed now @soshial
