### ISSUE TITLE
eurogamer.net

### ISSUE THREAD

**Issue by kuro68k** [easylist/easylist#7015]
### List the website(s) you're having issues:

https://www.eurogamer.net

### What happens?

GDPR cookie permission overlay displayed.

### List Subscriptions you're using:

EasyList
EasyPrivacy
EasyList Cookie

AdGuard Tracking Protection
AdGuard Annoyances

Fanboy’s Annoyance

uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 87.0.4280.141
- Adblock Extension/version: uBlock Origin v1.31.2

**Comment by THEtomaso** [comment]
It has been whitelisted by several filters, because blocking it will result in broken video playback!

**Comment by THEtomaso** [comment]
..so, you should close this issue report.
