### ISSUE TITLE
lvmgeo.lv (cookies)

### ISSUE THREAD

**Issue by soshial** [easylist/easylist#7020]
`https://www.lvmgeo.lv/en/maps`

### List the website(s) you're having issues:
`https://www.lvmgeo.lv/en/maps`

### What happens?
`PRIVACY_POLICY_COOKIE_NOTIFICATION` in the bottom of the page

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
No issues here @soshial cookie message is blocked

**Comment by spirillen** [comment]
Good here to, no :cookie: :fortune_cookie:

**Comment by soshial** [comment]
I guess, you have fixed it. With easylist turned off it looks like this:
![image](https://user-images.githubusercontent.com/100644/106020053-c6d74380-60dc-11eb-975b-0a5cd6241210.png)

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/blob/1aad4860a533af8644a0c91dc6f3e68983ef206b/easylist_cookie/easylist_cookie_general_hide.txt#L8145

@soshial thest what list use generichide for `lvmgeo.lv`?

**Comment by soshial** [comment]
> @soshial test what list use generichide for `lvmgeo.lv`?

How do I do it? How can I help you?

PS. Today it looked like this:
![image](https://user-images.githubusercontent.com/100644/118354952-9ed1fa00-b57e-11eb-9f7d-104f8b71600f.png)

**Comment by krystian3w** [comment]
In uBo logger try found green `@@*$generichide`:

https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by krystian3w** [comment]
Workaround is use in My filters panel:

`||lvmgeo.lv^$ghide,important` # - this disable @@*$generichide for one domain.
