### ISSUE TITLE
imore.com

### ISSUE THREAD

**Issue by GeQi** [easylist/easylist#7028]
### List the website(s) you're having issues:

https://www.imore.com/editors-desk-another-ces-has-come-and-gone

### What happens?

When blocking 3-rd party script and frames, this ad seems to get spawn.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

![image](https://user-images.githubusercontent.com/4011632/104975728-b3c7c380-59b8-11eb-818b-ee2958f3a79e.png)

I propose `##.no-amazon`

**Comment by ryanbr** [comment]
UbO issue
