### ISSUE TITLE
AuthedMine Captcha still broken by EasyPrivacy

### ISSUE THREAD

**Issue by coinhive-com** [easylist/easylist#703]
Relating to https://github.com/easylist/easylist/issues/697 - the AuthedMine captcha is still broken by the block of `authedmine.com` in EasyPrivacy.

Adding an exception for the `captcha.min.js` doesn't help. The captcha itself still needs to load the `https://authedmine.com/lib/authedmine.min.js` and to connect to the websocket servers at `ws://ws001.authedmine.com`.

Again, there is no need to block the Cryptominer on AuthedMine. The scripts hosted on AuthedMine.com NEVER start mining without an explicit opt-in from the user. Also, AuthedMine doesn't track users in any way.

More info about AuthedMine: https://authedmine.com

More info about privacy: https://coinhive.com/info/privacy

Please remove `authedmine.com` from the EasyPrivacy list.

**Comment by ryanbr** [comment]
We're happy to leave it. And the filter was modified to not apply to your domain, and I've tested it, and it works. Stop complaining.
