### ISSUE TITLE
AuthedMine is blocked for no reason

### ISSUE THREAD

**Issue by Leseratte10** [easylist/easylist#704]
I am sorry for opening a third issue about AuthedMine. I am not the operator of coinhive.com / authedmine.com, I just plan to use the AuthedMine captcha on my web sites. 

I have read the last two issues ( #697 and #703 ) but I still don't understand why this is blocked. 
Authedmine.com offers a captcha-like variant, where the user has to explicitly allow mining before the scripts do anything. As you can see on the web page itself ( https://authedmine.com ), nothing happens without the user agreeing to it. You can also verify this by checking the scripts yourself - they are not that long. 

Is there a specific reason why this is blocked? Sure, there have been miner scripts in the past which ran in the background without the user noticing, but this is something different. This is an alternative to captcha and / or website funding, *only if the visitor agrees*. 

While I absolutely agree with blocking miner scripts not asking for consent, I don't see how these scripts harm anyone and why they are blocked ...

**Comment by trank2012** [comment]
This is in general absurd. But this is their right, it will take a long time, until the level of trust to us grows in users. Now people look at such an option as if the red banners look bulls.

**Comment by pogsn3t** [comment]
**It should not be blocked** since it will ask user approval before doing anything, some websites use it instead of Ads, but even ads are not there for no purpose. You carry services and does pay bills too, it is deserving to get something in return.

**Comment by kikoncuo** [comment]
It makes sense to block every stealth miner, but I wanted to try mining as a way to give currency for people using my game, now it's not only enough with asking them for permission but I have to tell them to disable adblock??? I'm sure they will even ask for a compensation in order to unblock them.
