### ISSUE TITLE
exoclick.com

### ISSUE THREAD

**Issue by isacurad** [easylist/easylist#7041]
### List the website(s) you're having issues:

`https://www.exoclick.com/`

### What happens?

The filter `||exoclick.com^` blocks requests when accessing the same site. I suggest changing it to `||exoclick.com^$third-party`

### List Subscriptions you're using:

-EasyList
-ABP Filters

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 87.0.4280.141
- Adblock Extension/version: ABP 3.10.1

### Other details:

Reported from https://forums.lanik.us/viewtopic.php?f=109&t=45437

**Comment by ryanbr** [comment]
It's blocked outright because its used as a clickthrough, which is why the $third-party was removed.
