### ISSUE TITLE
XHR/image requests to Promo.com

### ISSUE THREAD

**Issue by Kryniol** [easylist/easylist#7042]
### List the website(s) you're having issues:

Any Wordpress instance with [Promo Video Maker](https://wordpress.org/plugins/promo-video-maker/) plugin installed

### What happens?

In July last year [we've requested to whitelist promo.com domain](https://github.com/easylist/easylist/issues/5717) as the `://promo.$third-party` rule was too broad and was blocking our iframes. Now we've released new promo.com product - a Wordpress plugin which can be installed on any Wordpress instance. From within Wordpress admin dashboard we're making XHR calls to our API endpoints in promo.com domain and for some reason the updated rule `://promo.$third-party,domain=~myshopify.com|~promo.com|~shopifycloud.com` still blocks those requests. Also the Promo icon is being blocked, see attached screenshot.
![Screenshot from 2021-01-22 15-21-26](https://user-images.githubusercontent.com/1271328/105503713-39a08300-5cc7-11eb-9e31-71d80e03625f.png)
Could you please change the rule so that promo.com would be whitelisted also for images and XHRs?

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Ubuntu 20.04.1 LTS
- Browser/version: 88.0.4324.96 (Official Build) (64-bit)
- Adblock Extension/version: 4.27.0

### Other details:

The rule which is blocking the requests:
https://github.com/easylist/easylist/blob/c404db05f3dcf4ef9b15309d662adac4dfe36564/easylist/easylist_general_block.txt#L7299

**Comment by ryanbr** [comment]
This filter is old, 8 years without issue. 

https://github.com/easylist/easylist/commit/d070b277931be2f642fea92badd622cb0b022e4d

**Comment by Kryniol** [comment]
Hi @ryanbr ! Thanks for this attempt to resolve it :slightly_smiling_face: Unfortunately, as stated in the description of this issue, the problem isn't to access the promo.com endpoints and images **from slidely.com domain** (it was just an example from our testing environment), it's about accessing them from **any domain** because it's a [Promo.com Wordpress plugin](https://wordpress.org/plugins/promo-video-maker/) which can be installed anywhere. I'm a developer of the plugin and because of the 8 years old change you've mentioned we can't release it to the public. Is it possible to just exclude promo.com domain entirelly from this filter?

**Comment by ryanbr** [comment]
` ://promo.$third-party,domain=~myshopify.com|~promo.com|~shopifycloud.com` we're already exempted. 

We won't allow a general whitelist of the entire promo domain, this is not privacy friendly.

But have fixed a promo embedded from `https://ketamineinstitute.com/` https://github.com/easylist/easylist/commit/0bed840da76719504dd85428aef8d936762f3ca0

**Comment by Kryniol** [comment]
@ryanbr what about whitelisting XHRs sent to https://promo.com/services/* ? Most of our public microservices are available under such URLs, I could also change the routing for the endpoints called from the Wordpress plugin so we'd have a solution which resolves the original issue and at the same time prevents potential problems from happening in the future.

BTW I don't quite get why can't we just whitelist promo.com domain? The change which was done 8 years ago wasn't related to our company, now because someone has decided to blacklist everything which has _promo_ in its name instead of maintaining a long list of fraudlent websites, any legal business like us which happens to have promo in the domain name will encounter similar bugs.

**Comment by ryanbr** [comment]
Show an example of public-facing websites using https://promo.com/services/
