### ISSUE TITLE
cerezzine.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#7046]
### List the website(s) you're having issues:

`https://cerezzine.com/slayer-1998-istanbul-konser-videosu-ortaya-cikti/`

### What happens?

Remains

### List Subscriptions you're using:

EasyList
### Your settings

- OS/version: Win10
- Browser/version: Chrome 88
- Adblock Extension/version: uBlock Origin 1.32.4

### Other details:

`widget_epcl_ads_fluid`

<details><summary>Screenshot</summary>
 
![cerezzine](https://user-images.githubusercontent.com/77894040/105608966-384e8380-5db7-11eb-896d-fe092ae7fb3a.png)

</details>

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/baf92b9d6bf2769fb8fc596f64e68ea543b89129
