### ISSUE TITLE
sportsmole.co.uk blocked for no reason (that I know of)

### ISSUE THREAD

**Issue by QES** [easylist/easylist#705]
Noticed that SportsMole.co.uk is blocked why is this?

This completely breaks amp.sportsmole.co.uk

Alan

**Comment by Khrin** [comment]
Maybe because your website was using Yavli ads scripts?

**Comment by QES** [comment]
So as it “was” using it can it be removed as it isn’t now.

By the way the amp version never used any of these things.

**Comment by Khrin** [comment]
Removed: https://github.com/easylist/easylist/commit/17b94e31d79069e1e192dc7dc20801a983155b94
