### ISSUE TITLE
academy.yandex.ru (cookies)

### ISSUE THREAD

**Issue by soshial** [easylist/easylist#7057]
### List the website(s) you're having issues:
`https://academy.yandex.ru/schools`

### What happens?
See a cookies notice in the left-bottom corner of the screen

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1131aa76f1d52c57a683a558f57d7474b498922f
