### ISSUE TITLE
tracker on www.sbv.gov.vn/sotc.dienbien.gov.vn...

### ISSUE THREAD

**Issue by vhpcdpgl** [easylist/easylist#7062]
### List the website(s) you're having issues:
https://www.sbv.gov.vn/
http://sotc.dienbien.gov.vn/
https://www.quangninh.gov.vn/

### What happens?
Tracker: `f-emc.ngsp.gov.vn`
Script:
`<script type="text/javascript" language="javascript">// begin emc
 var _govaq = window._govaq || [];
    _govaq.push(['trackPageView']);
    _govaq.push(['enableLinkTracking']);
    (function () {
        _govaq.push(['setTrackerUrl', 'https://f-emc.ngsp.gov.vn/tracking']);
        _govaq.push(['setSiteId', '30']);
        var d = document,
            g = d.createElement('script'),
            s = d.getElementsByTagName('script')[0];
        g.type = 'text/javascript';
        g.async = true;
        g.defer = true;
        g.src = 'https://f-emc.ngsp.gov.vn/embed/gov-tracking.min.js';
        s.parentNode.insertBefore(g, s);
    })();
        //end emc</script`

`<script type="text/javascript">
        var _govaq = window._govaq || [];
    _govaq.push(['trackPageView']);
    _govaq.push(['enableLinkTracking']);
    (function () {
        _govaq.push(['setTrackerUrl', 'https://f-emc.ngsp.gov.vn/tracking']);
        _govaq.push(['setSiteId', '87']);
        var d = document,
            g = d.createElement('script'),
            s = d.getElementsByTagName('script')[0];
        g.type = 'text/javascript';
        g.async = true;
        g.defer = true;
        g.src = 'https://f-emc.ngsp.gov.vn/embed/gov-tracking.min.js';
        s.parentNode.insertBefore(g, s);
    })();
    </script>`

`<script type="text/javascript">
	var _govaq = window._govaq || [];
	_govaq.push(['trackPageView']);
	_govaq.push(['enableLinkTracking']);
	(function () {
	_govaq.push(['setTrackerUrl', 'https://f-emc.ngsp.gov.vn/tracking']);
	_govaq.push(['setSiteId', '223']);
	var d = document,
	g = d.createElement('script'),
	s = d.getElementsByTagName('script')[0];
	g.type = 'text/javascript';
	g.async = true;
	g.defer = true;
	g.src = 'https://f-emc.ngsp.gov.vn/embed/gov-tracking.min.js';
	s.parentNode.insertBefore(g, s);
	})();
</script>`

### Your settings

- OS/version: Windows/Android
- Browser/version: Chrome/Firefox
- Adblock Extension/version:

**Comment by ryanbr** [comment]
We're already blocking `https://f-emc.ngsp.gov.vn/embed/gov-tracking.min.js` we don't need to do anything? @vhpcdpgl

**Comment by vhpcdpgl** [comment]
> We're already blocking `https://f-emc.ngsp.gov.vn/embed/gov-tracking.min.js` we don't need to do anything?

Can you block the subdomain `f-emc.ngsp.gov.vn` ? @ryanbr

**Comment by ryanbr** [comment]
`easyprivacy/easyprivacy_general.txt:/gov-tracking.min.js`

Fill me in on why we need to block a domain, is there more tracking coming from this domain not already covered? Or is it some browser/extension limitation? @vhpcdpgl

**Comment by vhpcdpgl** [comment]
> Fill me in on why we need to block a domain, is there more tracking coming from this domain not already covered? Or is it some browser/extension limitation? 

Many people use the NextDNS service, which works on many domain-blocking filters (including EasyPrivacy), not script blockers.
