### ISSUE TITLE
SeDirekte.com - Partially covered search bar (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#7070]
### Affected site:
`https://www.sedirekte.com/`

### Issue:
The site has a Google search bar in the header, which is half-covered by a partially blocked cookie warning.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **EasyList Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
`###cookietext`
`###cookiewarning
`
### Possible fix:
`sedirekte.com###cookiewarningcontainer`

### Other problem filters (with the same blocking rules):
* **AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/73281/

* **I don't care about cookies** (@kiboke)

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.17.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by kiboke** [comment]
@THEtomaso Thanks! It will be fixed in IDCAC.
