### ISSUE TITLE
winaero.com

### ISSUE THREAD

**Issue by sethazazel** [easylist/easylist#7080]
### List the website(s) you're having issues:

`winaero.com`

### What happens?

blog posts are no longer visible 

### List Subscriptions you're using:

Disabling easylist solves the problem.

### Your settings

- OS/version: Windows 10 2004
- Browser/version: Firefox 86.0b2 / Edge Chromium 88.0.705.53
- Adblock Extension/version: ublock origin 1.32.4

### Other details:
`https://winaero.com/about-the-adblocker-message-on-winaero/`
[https://github.com/easylist/easylist/commit/661506616cd15be7ca01a12accbc26e2ad183a06](https://github.com/easylist/easylist/commit/661506616cd15be7ca01a12accbc26e2ad183a06)

**Comment by mooseyaka** [comment]
Owner of winaero, Sergey Tkachenko is manipulate us.
In last article DIV they got an AD link, and this is why remove all block of last article.
And moderate all comments.
------------------------------------------
just remove “RECOMMENDED: Click here to fix Windows issues and optimize system performance” link,
bacause it’s ad’s, and in that case all block will be deleted by ublocker.

Also, it’s a good site with good content, but without ablocker they can’t be usable as usual, like – i want to click github link by middle key – an i didn’t get opened new tab with github, i got AD in middle of screen.

It’s wery bad behaviour.

and quantity of ads…. Well, ok, do whatewer you want, but now site now useless.

**Comment by sethazazel** [comment]
I am not a web developer and not familiar with this type discuss (sorry for my ignorance) but adding this to my filter list removes “RECOMMENDED: Click here to fix Windows issues and optimize system performance” without breaking the website.
! 2021-01-27 https://winaero.com
winaero.com##.entry-content > div > div > div

**Comment by tkaserg** [comment]
@mooseyaka 
Offensive speech is not allowed on my website.
Spreading wrong information is not welcomed too.
You should calm down and learn how to be polite to other people.
![ksnip_20210127-122940](https://user-images.githubusercontent.com/1557252/105971332-7390d100-609b-11eb-9482-0324f1e53ac4.png)

**Comment by ryanbr** [comment]
Changing divs elements to ensure a site is broken seems very anti-consumer. removed.
