### ISSUE TITLE
usefathom.com [EasyPrivacy]

### ISSUE THREAD

**Issue by slavaleleka** [easylist/easylist#7105]
`||usefathom.com^$third-party` from **EasyPrivacy** is too wide and blocks [their main website](https://usefathom.com/) (while AdGuard DNS is used)

could you pleasy specify it as `||collect.usefathom.com^$third-party`?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/66e53ef8c72493d72556d0fc792914ba2f800ba3

Was adjusted because they changed the url to track

**Comment by ryanbr** [comment]
Has been fixed, closing.
