### ISSUE TITLE
Airam.fi - Missing scroll bar (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#7107]
### Affected site:
`https://www.airam.fi/`

### Issue:
Broken page (missing scroll bar), because of a blocked cookie consent message.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **EasyList Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
```
##.cookie-consent:not(body):not(html)
###cookie-consent
```

### Possible fix:
```
airam.fi#@#.cookie-consent:not(body):not(html)
airam.fi#@##cookie-consent
```

### Other problem filters:
* ~~**AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/73587/~~ _(FIXED)_
~~`~raiba-ke-oa.de##.cookie-consent:not(body):not(html)`
`~yellowbrick.nl###cookie-consent`~~

* ~~**Frellwit's Swedish Filter** https://github.com/lassekongo83/Frellwits-filter-lists/issues/99/~~ _(FIXED)_
~~`##.cookie-consent:not(body):not(html)`~~

* ~~**I don't care about cookies** (@kiboke)~~ _(FIXED)_
~~`~abconcerts.be##.footer + .cookie-consent`
`##.main .cookie-consent:not(.btn)`
`###__nuxt .cookie-consent`
`~telesec.de,~o2.fr,~qwic.de,~vu.nl,~indiearenabooth.com,~hscollective.org,~geefvoorzorgverleners.nl,~conradconnect.com,~biotechusa.hu,~biotechusa.fr,~officiallondontheatre.com,~nieuwspoort.nl,~atro-provita.de###cookie-consent:not(.content):not([class*="fancybox"])`~~

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.17.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by kiboke** [comment]
Thanks you, @THEtomaso. I'll fix it in IDCAC.
