### ISSUE TITLE
pocketgamer.biz

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7110]
### List the website(s) you're having issues:

```
https://www.pocketgamer.biz/news/71620/all-apple-arcade-games/
https://www.pcgamesinsider.biz/
https://www.influencerupdate.biz/
https://www.blockchaingamer.biz/
```

### What happens?

Large ad banner in the top area.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/106352724-b514bc80-62e5-11eb-853f-5bbf35c9362d.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 88.0.4324.104 x64
- Adblock Extension/version: uBO 1.32.5rc4 + IDCAC 3.2.7

### Other details:

I propose `||resource.steelmedia.co.uk/skins^`

![image](https://user-images.githubusercontent.com/22780683/106352699-80086a00-62e5-11eb-8567-df5feca2b0ed.png)

**Comment by THEtomaso** [comment]
> I propose `||resource.steelmedia.co.uk/skins^`

Why not `||steelmedia.co.uk/promos/` too?

The above rules are good for starters, but those are very nasty pages, so additional cleaning is necessary.

After adding a bunch of new rules to my own filter, this adjustment was needed as well:
`##.show-skin:style(margin-bottom: 0px !important;)`
@okiehsch: Something for uBO Filters perhaps?

**Comment by DandelionSprout** [comment]
As for `||steelmedia.co.uk/promos/`, I only sparingly target job search widgets on websites. But thanks for the suggestion nevertheless.

**Comment by okiehsch** [comment]
How about
````
pcgamesinsider.biz,pocketgamer.biz###skin
pcgamesinsider.biz,pocketgamer.biz##.show-skin:style(margin-bottom: 0px !important;)
````

**Comment by DandelionSprout** [comment]
Seeing as none of those four sites are using those banners for ad purposes anymore, I suppose it's time for me to close this report.
