### ISSUE TITLE
techjunkie.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7117]
### List the website(s) you're having issues:

`https://www.techjunkie.com/change-install-location-windows-10-apps/`

### What happens?

Placeholder sticky on top.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/106358904-5106ee00-630f-11eb-86b2-3b6b17410fdf.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 88.0.4324.104 x64
- Adblock Extension/version: uBO 1.32.5rc4 + IDCAC 3.2.7

### Other details:

I propose `###qualdgr-hd-cont`

![image](https://user-images.githubusercontent.com/22780683/106359417-f66f9100-6312-11eb-9efa-67d21e4fc6e0.png)

**Comment by ryanbr** [comment]
Not seeing this.

**Comment by THEtomaso** [comment]
> `###qualdgr-hd-cont`

I see the placeholder, and the selector.
..but blocking it doesn't do anything.
Some type of css injector is probably needed, but I was unable to come up with one.

**Comment by THEtomaso** [comment]
OK, I figured it out:
`techjunkie.com##html > body:style(margin-top: 0px !important;)`

@okiehsch: For **uBO Filters**?

**Comment by krystian3w** [comment]
@THEtomaso Also see these glitch of ad **if I disable many tires block** `/gtm.js`:

```
||googletagmanager.com^$badfilter                     # Peter Lowe
||googletagmanager.com/gtm.js$script,badfilter        # uBlock - Privacy
/gtm.js$badfilter                                     # EasyPrivacy
```

**Raynbr** suppose tested with Enabled EP or other list - problem generated by **Dandelion**.

(Discus on slack whether you have the right to require update EasyList  into new filters when EasyPrivacy is blocking something... or use preambule **must tested with disabled EasyPrivacy / Peter Lowe Project / uBlock - Privacy**")

---

As for CSS filters maybe is worth for uAssets and AdGuard Base.

**Comment by THEtomaso** [comment]
> `/gtm.js`

Allowing `gtm.js` was only neccessary in order to locate the selector, which DandelionSprout refered to.
With the CSS rule(s) in place, that script, and selector,  is irrelevant.

--

> Also possible split into one (instead of 2)

That works too.
:)

**Comment by okiehsch** [comment]
The only issue is the placeholder at the top?

I don't view that as a uAssets issue.

**Comment by krystian3w** [comment]
But no possible reduce letfover by network or legacy ABP filter.

**Comment by THEtomaso** [comment]
> I don't view that as a uAssets issue.

For **AdGuard Base filter** then, perhaps (@BlazDT)?:
```
techjunkie.com#$#.home-page.main-section { margin-top: 0px !important; }
techjunkie.com#$#html > body { margin-top: 0px !important; }
```

..or possibly:
`techjunkie.com#$#.home-page.main-section, html > body { margin-top: 0px !important; }`
(Not sure if AdGuard supports the merging of rules, like that)

**Comment by okiehsch** [comment]
I asked internally, if a majority disagrees with my view we can add your filter.

**Comment by okiehsch** [comment]
We actually already added filters for issues of this nature, i.e. placeholders caused by blocked ads that can only be removed by extended syntax.
I was not aware of that, sorry about the confusion.
I added your suggesed filter.

**Comment by krystian3w** [comment]
> (Not sure if AdGuard supports merging rules, like this)

Technically their way of injecting CSS allows you to use `media queries` and animation `@keyframes` CSS (compressed into 1 line):

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries
https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes

> uBO reject use these technology, because simple check selectors like other cosmetic/procedural filters - no have additional test to mark as valid syntax media queries / `@keyframes`.
> (I guess in the past it was also an excuse to use Stylus for such games and in uBO to do only the necessary repairs with CSS.)
> 
> _For this to change this situation would probably take more than 100 sites where someone with Media Queries makes it difficult to hide ads (overwriting `@keyframes` probably won't even get on the `uBlock - Annoyance` list so maybe still marked as invalid after add alow use media queries CSS)._

But when it comes to combining two simple selectors into one, they AG are unlikely never to do so.
