### ISSUE TITLE
spreadshirt.com, wolt.com

### ISSUE THREAD

**Issue by Jammie1143** [easylist/easylist#7127]
### List the website(s) you're having issues:

`https://www.spreadshirt.com/`
`https://wolt.com/`

### What happens?

Cookie notice popup.

### List Subscriptions you're using:

AdGuard Base, EasyList, EasyPrivacy and EasyList Cookie.

### Your settings

- OS/version:  Windows 10 20H2
- Browser/version: Chrome 88
- Adblock Extension/version: AdGuard 7.5.3

**Comment by ryanbr** [comment]
`wolt.com` Unfortantly can't be blocked since it relys on the scrollbar also.

Fixed `https://www.spreadshirt.com/`

@Jammie1143
