### ISSUE TITLE
whitelist cdn.ampproject.org

### ISSUE THREAD

**Issue by QES** [easylist/easylist#713]
This is the site / cdn used to load the AMP toolkits which are designed to limit the potential for bad adverts and much more in the way of bad JS.

https://www.ampproject.org/

Is all about making the web faster and getting rid of the bloat that requires ad blockers to exist so it might be good to whitelist the domain all their JS is loaded form.

**Comment by Khrin** [comment]
Please see https://github.com/easylist/easylist/issues/705

**Comment by QES** [comment]
Thanks for sorting out #705 the reason for the comment about cdn.ampproject.org was a more general one, there may be other sites whose AMP elements will be effected even though the AMP part of the site is sitting in a world where you can't do many of the objections advert things that we all hate.  

By creating a more generic solution you incentivise people to switch more of their users to AMP based pages (assuming you agree this is a benefit for mobile users).
