### ISSUE TITLE
genpassword.top

### ISSUE THREAD

**Issue by Jammie1143** [easylist/easylist#7149]
### List the website(s) you're having issues:

`http://genpassword.top/flUl78`

### What happens?

There is a fake button above 'Click Here to Continue'.
![image](https://user-images.githubusercontent.com/77138531/106741059-2e017480-6656-11eb-82b1-205cc2545a8b.png)

### List Subscriptions you're using:

AdGuard Base + AdGuard Tracking Protection + EasyList + EasyPrivacy + EasyList Cookie.

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 88
- Adblock Extension/version: AdGuard 7.5.3

**Comment by ryanbr** [comment]
done
