### ISSUE TITLE
[whitelist] imasdk.googleapis.com

### ISSUE THREAD

**Issue by scafroglia93** [easylist/easylist#7154]
the following domain is used in most of the national ondemand television services ->

RAI -> Italy
YLE -> Finland
NRK -> Norway
SVT -> Sweden
NPO -> Netherlands

I hope that this request was legit

**Comment by Khrin** [comment]
Hi, please can you more specific about what's the issue?

For example, here `https://www.raiplay.it/video/2021/01/sciencexplosion-s1e1-il-segreto-della-densita-3c285ecd-0925-4a3c-9edc-d95047b97797.html` the filter is active, but I can also play the video without problems.

**Comment by scafroglia93** [comment]
the problem is present in the applications distributed via app (android /
ios)

Il giorno gio 4 feb 2021 alle ore 12:19 Khrin <notifications@github.com> ha
scritto:

**Comment by Khrin** [comment]
See https://github.com/easylist/easylistitaly/issues/4#issuecomment-773328708
