### ISSUE TITLE
Breakage due to rule: /jquery.dfp.js$script

### ISSUE THREAD

**Issue by crssi** [easylist/easylist#7155]
Visit site `https://myrgv.com/featured/2021/02/03/faa-to-probe-sn9-crash-second-starship-destroyed-in-landing/`
In the middle, there are pictures. Swipe over those.
The first two are shown, but the others are not due to rule `/jquery.dfp.js$script`

Cheers

**Comment by ryanbr** [comment]
Working fine here @crssi

**Comment by crssi** [comment]
Crap... that is true.
Now I feel stupid.
It might be that there was something with a site and my timing of testing was inline with [Murphy](https://en.wikipedia.org/wiki/Murphy's_law).

I am really sorry for "nothing" and thank you @ryanbr for fast response,
Cheers
