### ISSUE TITLE
upload.ee

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/easylist#7157]
### List the website(s) you're having issues:

`https://www.upload.ee/files/12839313/b90f60019962e302bf6fa8478c602aa6.gif.html`

### What happens?

Ads

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-02-04_193940](https://user-images.githubusercontent.com/57287308/106932844-e4319080-6720-11eb-886a-d329f76e1eda.png)
![2021-02-04_194003](https://user-images.githubusercontent.com/57287308/106932848-e693ea80-6720-11eb-9d05-b96338f64c61.png)
</details>

### List Subscriptions you're using:

ABP filters
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy's Social Blocking List

### Your settings

- OS/version:  Windows 8.1
- Browser/version:  Google Chrome
- Adblock Extension/version: Adblock Plus 3.10.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2d2fbd3ba22bd9f2daf6ea815e0f372687513995

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2d2fbd3ba22bd9f2daf6ea815e0f372687513995

**Comment by dimisa-RUAdList** [comment]
@ryanbr 
`upload.ee##[href^="https://www.upload.ee/click.php"]` ~> `upload.ee##[href^="https://www.upload.ee/home.php"]`
