### ISSUE TITLE
knowyourmeme.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7159]
### List the website(s) you're having issues:

`https://knowyourmeme.com/memes/queen-of-england-death-predictions`

### What happens?

Apparently they're rolling out a new look for their pages for specific memes, with many placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/106955604-be62b680-6735-11eb-9438-9550b9729bbf.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 88.0.4324.146 x64
- Adblock Extension/version: uBO 1.33.3b0 + IDCAC 3.2.7

### Other details:

I propose `knowyourmeme.com##.ads`

![image](https://user-images.githubusercontent.com/22780683/106955481-96735300-6735-11eb-8d8d-5739b91fea2c.png)

**Comment by DandelionSprout** [comment]
There's also placeholders at `https://knowyourmeme.com/editorials/collections/20-images-from-comedy-heaven-that-can-rival-any-dad-jokes`. I propose `knowyourmeme.com##.bodycopy > div[style]:not([class])`
 
![image](https://user-images.githubusercontent.com/22780683/106957890-dee04000-6738-11eb-9e4c-9c21a94f4bd6.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/13f27c8d7bb8c88cd89bdee6998e0eef7446706a

**Comment by THEtomaso** [comment]
@okiehsch:
Perhaps you could add the rule that DandelionSprout suggested in his second post to **uBO Filters**?

**Comment by wout-codes** [comment]
> [13f27c8](https://github.com/easylist/easylist/commit/13f27c8d7bb8c88cd89bdee6998e0eef7446706a)

@ryanbr It is still there. This works `knowyourmeme.com##.bodycopy > div[style]:not([class])

`
