### ISSUE TITLE
d2j1fszo1axgmp.cloudfront.net

### ISSUE THREAD

**Issue by hueto902** [easylist/easylist#7175]
### List the website(s) you're having issues:

`kitsu.io`
`the-dots.com`

### What happens?

Analytics script not blocked by Easyprivacy.

### List Subscriptions you're using:

uBlock filters
Easylist
Easyprivacy

### Your settings

Default Settings from uBlock Origin

- OS/version: Windows 7
- Browser/version: Pale Moon Browser v29.0.1
- Adblock Extension/version: uBlock Origin v1.16.4.28

### Other details:

`||d2j1fszo1axgmp.cloudfront.net^` seems to do the trick just fine without any breakages at all.

**Comment by JobcenterTycoon** [comment]
`https://m.stripe.network/inner.html#url=https%3A%2F%2Fthe-dots.com%2F&title=The%20Dots%20%7C%20The%20future%20of%20work&referrer=&muid=ff001630-9839-4725-8e6e-8cf046a7c0fa24274e&sid=1ad5052a-4b19-4f69-abff-df84d231ed66f358be&version=6&preview=false&metaReferrerPolicy=always`

looks more like tracking (fingerprinting)

**Comment by JobcenterTycoon** [comment]
More coming from `https://js.stripe.com/v3/fingerprinted/js/m-outer*.js`

With uBlock Origin its enough to block `stripecdn.map.fastly.net` but i not checked for breakage because i don’t use the site

**Comment by hueto902** [comment]
> 
> 
> More coming from `https://js.stripe.com/v3/fingerprinted/js/m-outer*.js` and `d1tcqh4bio8cty.cloudfront.net`
> 
> With uBlock Origin its enough to block `stripecdn.map.fastly.net` but i not checked for breakage because i don’t use the site

Didn't caused any breakage for me, thanks for helping btw!

**Comment by JobcenterTycoon** [comment]
@ryanbr why no fix for the fingerprint stuff? it is to risky?

**Comment by llacb47** [comment]
Yes, that will break stripe.
