### ISSUE TITLE
xrea.com

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#7181]
### List the website(s) you're having issues:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +620 |  |  | wmarron.sakura.ne.jp | 3 | script | `http://wj.ax.xrea.com/l76.f?&x=705205819&id=300402337&url=http://wmarron.sakura.ne.jp/intro.html&rf=http://wmarron.sakura.ne.jp/&sw=1000&sh=800&cd=24&je=&pf=0&cc=&bt=%E3%81%84%E3%82%89%E3%81%A3%E3%81%97%E3%82%83%E3%81%84%E3%81%BE%E3%81%9B%E3%80%8C%E3%83%9E%E3%83%AD%E3%83%B3%E3%81%AE%E3%82%8D%E3%81%BE%E3%82%93%EF%BC%81%EF%BC%81%EF%BC%81%E3%80%8D&ln=en&ct=us&ce=1&osec=45&tm=1612800060&prt=2&pvf=0&pvl=0&pvt=0&drt=2&dvf=0&dvl=0&dvt=0&pname=enter&chk=%E3%81%82` |
| +620 |  |  | wmarron.sakura.ne.jp | 3 | image | `http://j1.ax.xrea.com/x.gif` |
| +620 |  |  | wmarron.sakura.ne.jp | 3 | script | `http://j1.ax.xrea.com/l.j?id=300402337` |
| +575 |  |  | wmarron.sakura.ne.jp | 3 | script | `http://wj.ax.xrea.com/l76.f?&x=705205819&id=300402337&url=http://wmarron.sakura.ne.jp/&rf=&sw=1000&sh=800&cd=24&je=&pf=0&cc=&bt=%E3%83%9E%E3%83%AD%E3%83%B3%E3%81%AE%E3%82%8D%E3%81%BE%E3%82%93%EF%BC%81%EF%BC%81%EF%BC%81&ln=en&ct=us&ce=1&osec=0&tm=&prt=&pvf=0&pvl=0&pvt=0&drt=&dvf=0&dvl=0&dvt=0&pname=index&chk=%E3%81%82` |
| +575 |  |  | wmarron.sakura.ne.jp | 3 | image | `http://j1.ax.xrea.com/ts.gif` |
| +575 |  |  | wmarron.sakura.ne.jp | 3 | image | `http://j1.ax.xrea.com/x.gif` |
| +572 |  |  | wmarron.sakura.ne.jp | 3 | script | `http://j1.ax.xrea.com/l.j?id=300402337` |
| +524 |  |  | pulse2.sakura.ne.jp | 3 | image | `http://counter.xrea.com/cgi-bin/pngcount.fcg?site=87654321&img=02005&ovlp=1&max=4&day=1` |
| +524 |  |  | pulse2.sakura.ne.jp | 3 | image | `http://counter.xrea.com/cgi-bin/pngcount.fcg?site=87654321&img=02005&ovlp=1&max=4&day=2` |
| +524 |  |  | pulse2.sakura.ne.jp | 3 | image | `http://counter.xrea.com/cgi-bin/pngcount.fcg?site=87654321&img=02005&ovlp=1&max=7&day=0` |
</details>

### What happens?

Suspect tracking @Yuki2718 maybe you can help translate the main site?

### List Subscriptions you're using:

Not relevant

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

Drive by dropoff as working on NSFW domains

**Comment by Yuki2718** [comment]
Why translation is needed to block tracker?

**Comment by spirillen** [comment]
if you take a look at `xrea.com` you'll see it good look like a hosting site

**Comment by Yuki2718** [comment]
> if you take a look at `xrea.com` you'll see it good look like a hosting site

Right.

> Hence a bit difficult to block it by wildcard 😭

?? Aren't
```
||ax.xrea.com^
||counter.xrea.com^

```
enough?

**Comment by spirillen** [comment]
> ?? Aren't
> 
> ```
> ||ax.xrea.com^
> ||counter.xrea.com^
> ```
> 
> enough?

I would like `*.xrea.com    CNAME .` better :smile: :laughing: that's easier to maintain in the DB :stuck_out_tongue_winking_eye:

**Comment by ryanbr** [comment]
I'm not seeing any of these.  Follow the issue report, submit url's. Because:

`https://www.xrea.com/spec/` and `https://www.xrea.com/` shows no issues.

**Comment by Yuki2718** [comment]
`ax.xrea.com` is here: `http://phpspot.net/php/`

**Comment by spirillen** [comment]
Also on some of fc2.com's sites, I believe it was there I found it.... (<https://www.mypdns.org/T3474>)

**Comment by spirillen** [comment]
This might need a translation, but I suspect adware

![image](https://user-images.githubusercontent.com/44526987/107535760-57278500-6bc1-11eb-83d9-b549929fe6ff.png)


Let me also add these to the original suggestions as I found them in the DB

ct1.xrea.com    CNAME . ; AdWare??
ad.xrea.com    CNAME . ; AdWare
ad2.xrea.com    CNAME . ; AdWare
ad3.xrea.com    CNAME . ; AdWare

**Comment by Yuki2718** [comment]
What filter author need is actual URLs where tracker is found.

**Comment by spirillen** [comment]
> What filter author need is actual URLs where tracker is found.

Sure, But for the last ones, I don't have then, but they do have there A/AAAA records, but I haven't seen them anywhere but in my old import.

So they can add them, keep them to bee searched later if a match comes up, it's open sharing of information, no more no less.

@Yuki2718 could you categories the latest screenshot for `ct1.xrea.com`?

**Comment by Yuki2718** [comment]
@spirillen Since this is your report, you have to provide what author need - filter author generally don't add any entry without confirming an actual case by their eyes. Use publicwww to find out the cases. Sorry but I'm busy to make commits or to solve issues in uAssets and AG.
