### ISSUE TITLE
wikimetal.com.br

### ISSUE THREAD

**Issue by isacurad** [easylist/easylist#7191]
### List the website(s) you're having issues:
`https://www.wikimetal.com.br/jason-momoa-tool-amor-pelo-baixo/`

### What happens?
The filter ##.side-share from FB Social hides the body, that has that class on article pages

### List Subscriptions you're using:
- EasyList
- EasyList Portuguese
- Fanboy Social

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 88.0.4324.146
- Adblock Extension/version: ABP 3.10.2

### Other details:
Suggest exception `wikimetal.com.br#@#.side-share`

**Comment by wout-codes** [comment]
@ryanbr EasyPrivacy breaks PizzaHut's Add to cart function.
