### ISSUE TITLE
rp-online.de

### ISSUE THREAD

**Issue by rponline1** [easylist/easylist#7199]
### List the website(s) you're having issues:
`https://rp-online.de` ->
`https://rp-online.de/info/consent/`

### What happens?

homepage redirects to consent page.
Consent page cannot be clicked away because of `cdn.cookielaw.org` being blocked.

### List Subscriptions you're using:
EasyList, EasyPrivacy, EasyList Cookie

### Your settings

- OS/version: Firefox 85
- Browser/version: Windows 10
- Adblock Extension/version: uBlock Origin

### Other details:

![grafik](https://user-images.githubusercontent.com/78941652/107720877-32bbcd80-6cd3-11eb-8567-aaa3d643d915.png)

**Comment by EricRa** [comment]
I was able to reproduce the issue in Firefox and can confirm that I was not able to click the dialog away.  This only happens when the EasyList Cookie list is enabled, as it contains the relevant text OP mentions.
