### ISSUE TITLE
stats.computecmedia.de

### ISSUE THREAD

**Issue by Ratcreamsoup** [easylist/easylist#721]
Hi,

We're using an internal tracking system on our own websites (pcgames.de, pcgameshardware.de, buffed.de, gamesaktuell.de, gamezone.de, videogameszone.de) via a separate host stats.computecmedia.de. This system is in use since around 2012. We had noticed in 2014 that it had been added to easyprivacy and had contacted MonztA, explaining the purpose and what data was collected (and which data explicitly wasn't), which resulted in MonztA removing it from easyprivacy (see https://github.com/easylist/easylist/commit/693db117978a3c60a071c014c0fb918b9fc7133b).

We're making sure to avoid collecting any personally identifyable data. We have in fact even customized the webserver configuration for this host so that there is no logging at all, therefore preventing IP addresses and user agent strings from being logged. We're not logging these anywhere else, the system is used exclusively to measure aggregated audience performance metrics (i.e. overall impressions, visits) of articles, videos, sections and other segments of our websites, we're not using it to do any individual user profiling. This is specifically the reason why we're using a separate domain here, so the tracking has no direct access to the Cookie scope of our primary websites, therefore no access to any user-id or other personal identifiable information. Non-atomic metrics (visits, unique visits) are aquired by using random ids stored in a cookie, but these have no connection to individual user profiles and and any such temporarily collected data is immediately discarded after aggregation and never accessed individually. As there is no connection between any kind of personal identifyable information anywhere in our system (such as user ids or IP addresses), it is not possibly to de-anonymize that data and there is no "feedback loop" for individual users's browsing experience - it's really just fully anonymous aggregation.

In setting up this system we have strictly observed the guidelines explained here: https://easylist.to/2011/08/31/what-is-acceptable-first-party-tracking.html

We have noticed however, that our tracking as been nevertheless re-added to easyprivacy with this commit from June 2016: https://github.com/easylist/easylist/commit/5318ddff9b2256d32992f06b5c6bb1d0ea5745db

We're kindly asking you to revert this commit again, as we strongly believe that we're adhering to all the rules of acceptable first party tracking. The aggregated data is quite important for our editorial teams to get feedback for their day to day work. It is therefore unfortunate, that a certain fraction of our generally quite tech-savvy audience is excluded from this feedback. We assume that it may be a statistically not necessarily relevant portion of our audience, but with uBlock origin and probably a couple more addons enabling easyprivacy as a default, it may become even more relevant over time.

Kind regards

Markus

**Comment by ryanbr** [comment]
Thanks for the notification, We'll look into it.

**Comment by ryanbr** [comment]
Has been removed.
