### ISSUE TITLE
GameSpot.com - Modal overlay / Blocked videos (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#7216]
### Affected site:
`https://www.gamespot.com/`

### Issue:
Videos won't play / grey modal overlay.

### Example:
`https://www.gamespot.com/videos/this-little-nightmares-ii-gameplay-will-give-you-anxiety/2300-6454627/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **EasyList Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
```
###onetrust-banner-sdk
@@||geolocation.onetrust.com/cookieconsentpub/$script
```
(The first rule causes the issue because of the second rule, and vice versa)

### Related issue:
A similar problem uccurs @ **CBSNews.com**:
https://github.com/easylist/easylist/issues/7318/

### Possible fix:
```
- @@||geolocation.onetrust.com/cookieconsentpub/$script

+ ||geolocation.onetrust.com/cookieconsentpub/$script,domain=cbsnews.com|gamespot.com
+ @@||geolocation.onetrust.com/cookieconsentpub/$script,domain=~cbsnews.com|~gamespot.com
```

### Temporary fixes:
For ABP (allowing the cookie consent popup):
`gamespot.com#@##onetrust-banner-sdk`

For uBO (blocking the geolocation script):
`||geolocation.onetrust.com/cookieconsentpub/$script,important,domain=gamespot.com`
(@okiehsch: I guess this falls outside of scope, for any of the uBO Filters?)

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.0.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by okiehsch** [comment]
@THEtomaso Yes, that script is needed for GDPR and we don't block that.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/ea98c1c676e35a7e79a26e30c45d6fe4ddc0c59f
