### ISSUE TITLE
fakestube.com (NSFW)

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#7218]
### List the website(s) you're having issues:
`https://www.fakestube.com/`

### What happens?
I see 3 ads, one is the banner "STRIPCHAT" you'll see when you open the page, the other two are at the bottom of the page.

### Your settings

- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin

**Comment by spirillen** [comment]
Got these with my "picker" some of them absolutely needs more work

! 2021-02-15 https://www.fakestube.com
www.fakestube.com##p:nth-of-type(1)
www.fakestube.com##p:nth-of-type(2)
www.fakestube.com##[href^="https://go.stripchat.com/"]
www.fakestube.com##p:nth-of-type(4)
www.fakestube.com##p:nth-of-type(3)
www.fakestube.com###footer > .container > .row
www.fakestube.com###custom_html-2 > .custom-html-widget.textwidget > [href]

<details><summary>Own ref: </summary>

https://www.mypdns.org/T3619

</details>
