### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7220]
### List the website(s) you're having issues:

`https://socket.io/`

### What happens?

A whole lot of ads on the project's homepage, most of them for casinos.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/107908020-63ab3500-6f55-11eb-8354-486b2133c094.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 88.0.4324.150 x64
- Adblock Extension/version: uBO 1.33.3b0 + IDCAC 3.2.7

### Other details:

I propose:
```
||images.opencollective.com^$domain=socket.io
||socket.io/images/sponsors^$image
socket.io###sponsors
```

![image](https://user-images.githubusercontent.com/22780683/107907901-20e95d00-6f55-11eb-869f-07ad4624dfd4.png)

**Comment by llacb47** [comment]
Those are sponsors of an open source project, not ads.

**Comment by DandelionSprout** [comment]
I *never* trust no-name online casinos. If they're on any site, it's never because they felt a need to support the open-source community.

**Comment by ryanbr** [comment]
Yeah, I'm more inclined leaving it
