### ISSUE TITLE
https://winiso.pl/

### ISSUE THREAD

**Issue by ticotaco72** [easylist/easylist#7221]
### List the website(s) you're having issues:

 ```https://winiso.pl/ ```

### What happens?

There's an ad banner on top of the sites.

### List Subscriptions you're using:

![obraz](https://user-images.githubusercontent.com/32620809/107965099-61bf9100-6faa-11eb-8cdf-5856ac1d1ab3.png)

### Your settings

- OS/version: Fedora 33
- Browser/version: Firefox 85.0.1
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

![obraz](https://user-images.githubusercontent.com/32620809/107965287-a3e8d280-6faa-11eb-8c18-87e441131dff.png)

**Comment by ryanbr** [comment]
Not an Easylist issue @ticotaco72  I'd report to the Polish list authors
