### ISSUE TITLE
ksl.com

### ISSUE THREAD

**Issue by chris122380** [easylist/easylist#7223]
Easyprivacy requests: N/A

### List the website(s) you're having issues:
ksl.com

### What happens?
With the ads removed on Mobile it leaves a gap above the first news article.
![Screenshot_20210215-224145](https://user-images.githubusercontent.com/2205798/108024904-b7179480-6fe2-11eb-99cc-310792b1e541.png)

### List Subscriptions you're using:
EasyList
EasyPrivacy
Fanboy's Annoyance List
Ublock default lists

### Your settings
Default settings

- OS/version: Android 10
- Browser/version: Brave Beta 1.21.51 and Vivaldi
- Adblock Extension/version: N/A

### Other details:
Can't add to Mobile browsers where they use EasyList. Brave recommended I report the issue hear so it can be fixed down stream. I was able to add custom filters using Firefox and ublock origin to test it on Mobile (only a mobile issue doesn't happen on desktop view of the webpage) but doesn't resolve it for browsers that use the built in adblocking filters. 

Custom filters:
www.ksl.com##.mobile_wrap_top
www.ksl.com###market-ticker

**Comment by ryanbr** [comment]
Should be fixed in Brave Nightly (in google playstore), cosmetics will be applied in this version and upcoming release.
