### ISSUE TITLE
adspyglass.com

### ISSUE THREAD

**Issue by stufently** [easylist/easylist#7237]
### List the website(s) you're having issues:
`https://app.adspyglass.com/
https://adspyglass.com/
`

### What happens?
The filter ||adspyglass.com^ blocks requests when accessing the same site. 
This block disrupts functioning of the website by blocking all requests to CSS
, JS, fonts, and all XHR-requests required for normal usage.

### List Subscriptions you're using:
-EasyList / easylist_adservers.txt

### Your settings
* OS/version: Windows 10
* Browser/version: Chrome 88.0.4324.182
* Adblock Extension/version: ABP 4.28.5

### Other details 
There are no ads from these domain

![Screenshot_4](https://user-images.githubusercontent.com/1324096/108506257-13ccc500-72eb-11eb-95c7-404bdebb6a2b.png)

**Comment by ryanbr** [comment]
Is blocked because it's used as a clickthrough, so leaving.

**Comment by stufently** [comment]
We never use our site for clickthrough. Can you give any example or case clickthrough on our domain?

**Comment by Xabibylin** [comment]
@ryanbr Hello, a lot of time has passed, but we are still on the list, please tell me what evidence we need to present in order to exclude us

**Comment by Xabibylin** [comment]
@ryanbr Hello, give us any feedback, please

**Comment by Xabibylin** [comment]
@ryanbr Hello, give us any feedback, please
