### ISSUE TITLE
[EasyPrivacy] Bing Image Search Breakage

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#7240]
### List the website(s) you're having issues:
Bing.com

### What happens?

If you use Bing's image search (doesn't matter what query), after clicking through a few images, the page goes completely blank. This has happened for months now, but I wasn't sure what filter was responsible.

So far what works for me is adding `www.bing.com/fd/ls/lsp.aspx` to my allowlist in uBlock Origin. Specifically my makeshift filter has been `@@||www.bing.com/fd/ls/lsp.aspx$xhr,domain=www.bing.com`.

**Comment by llacb47** [comment]
Can't reproduce this issue, I use bing often (very lame) and never have this issue.

**Comment by yokoffing** [comment]
> Can't reproduce this issue, I use bing often (very lame) and never have this issue.

I use Bing all the time, too! What's up, fam 😉

Let me see what other filters show up when I perform a search.

**Comment by yokoffing** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +27 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx` |
| +27 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx` |
| +26 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx` |
| +25 | /ls.gif? | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/ls.gif?IG=D9C66DB41A4F46DCB202843A4F26525A&Type=Event.ClientInst&DATA=%7B%22T%22%3A%22CI.Error%22%2C%22TS%22%3A1613794165202%2C%22Name%22%3A%22ReactError%22%2C%22Text%22%3A%22A%20network%20error%20occurred.%22%2C%22Stack%22%3A%22%0A%20%20%20%20in%20e%0A%20%20%20%20in%20ImageDetailInstrumentationHelper%0A%20%20%20%20in%20div%0A%20%20%20%20in%20e%0A%20%20%20%20in%20Connect(e)%0A%20%20%20%20in%20o%22%7D&log=UserEvent` |
| +25 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx` |
| +25 | /ls.gif? | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/ls.gif?IG=F38F52925A134B708C5934745BD50F1F&Type=Event.ClientInst&DATA={%22T%22:%22CI.Show%22,%22Name%22:%22BopBlock%22,%22TS%22:1613794164803}&log=UserEvent` |
| +24 | /ls.gif? | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/ls.gif?IG=F38F52925A134B708C5934745BD50F1F&Type=Event.ClientInst&DATA={%22T%22:%22CI.Scroll%22,%22Name%22:%22ExpandControl%22,%22ComponentId%22:%22mmComponent_images_2_exp%22,%22TS%22:1613794164287}&log=UserEvent` |
| +20 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx` |
| +16 | /ls.gif? | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/ls.gif?IG=D9C66DB41A4F46DCB202843A4F26525A&Type=Event.ClientInst&DATA=%7B%22T%22%3A%22CI.Info%22%2C%22TS%22%3A1613794156341%2C%22AppNS%22%3A%22idpfs_1.LB.1_1%22%2C%22K%22%3A%225148.1%22%2C%22Name%22%3A%22ImageViewer%22%2C%22Component%22%3A%22currentimg%22%2C%22url%22%3A%22https%3A%2F%2Fwww.herinterest.com%2Fwp-content%2Fuploads%2F2014%2F10%2Fcorgi.jpg%22%2C%22page%22%3A%22ImageDetailMainImage%22%2C%22ViewType%22%3A%22Default%22%2C%22Scenario%22%3A%22Default%22%2C%22Mid%22%3A%221E67D03AEB0E6473BE4AA271F73CD9BA5ABF6BC6%22%7D&log=UserEvent` |
| +16 | ##.share |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?view=detailV2&ccid=9d6Vx%2fqt&id=1E67D03AEB0E6473BE4AA271F73CD9BA5ABF6BC6&thid=OIP.9d6Vx_qtBNAeje6oAgd77AHaE7&mediaurl=https%3a%2f%2fcdn.omlet.co.uk%2fimages%2foriginals%2fDog-Dog_Guide-A_Pembroke_Welsh_Corgi_with_a_beautiful_well_groomed_coat.jpg&exph=565&expw=850&q=corgi&simid=608028607953243050&ck=C46C3AA78016CCD7946E90CFE01A5E26&selectedIndex=48&mode=overlay` |
| +15 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx` |
| +15 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx?` |
| +15 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=D9C66DB41A4F46DCB202843A4F26525A&Type=Event.CPT&DATA={%22pp%22:{%22S%22:%22L%22,%22FC%22:176,%22BC%22:176,%22SE%22:-1,%22TC%22:-1,%22H%22:278,%22BP%22:384,%22CT%22:386,%22IL%22:3},%22ad%22:[-1,-1,1577,997,1577,997,1]}&P=images&DA=BN2B` |
| +15 | ##+js(set-constant, SVGForeignObjectElement, undefined) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?view=detailV2&ccid=9d6Vx%2fqt&id=1E67D03AEB0E6473BE4AA271F73CD9BA5ABF6BC6&thid=OIP.9d6Vx_qtBNAeje6oAgd77AHaE7&mediaurl=https%3a%2f%2fcdn.omlet.co.uk%2fimages%2foriginals%2fDog-Dog_Guide-A_Pembroke_Welsh_Corgi_with_a_beautiful_well_groomed_coat.jpg&exph=565&expw=850&q=corgi&simid=608028607953243050&ck=C46C3AA78016CCD7946E90CFE01A5E26&selectedIndex=48&mode=overlay` |
| +15 | ##+js(set-constant, AdBTrack.AdbMon.isBlocked, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?view=detailV2&ccid=9d6Vx%2fqt&id=1E67D03AEB0E6473BE4AA271F73CD9BA5ABF6BC6&thid=OIP.9d6Vx_qtBNAeje6oAgd77AHaE7&mediaurl=https%3a%2f%2fcdn.omlet.co.uk%2fimages%2foriginals%2fDog-Dog_Guide-A_Pembroke_Welsh_Corgi_with_a_beautiful_well_groomed_coat.jpg&exph=565&expw=850&q=corgi&simid=608028607953243050&ck=C46C3AA78016CCD7946E90CFE01A5E26&selectedIndex=48&mode=overlay` |
| +15 | ##+js(set-constant, AdBlockerTracking.AdBlockMonitor, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?view=detailV2&ccid=9d6Vx%2fqt&id=1E67D03AEB0E6473BE4AA271F73CD9BA5ABF6BC6&thid=OIP.9d6Vx_qtBNAeje6oAgd77AHaE7&mediaurl=https%3a%2f%2fcdn.omlet.co.uk%2fimages%2foriginals%2fDog-Dog_Guide-A_Pembroke_Welsh_Corgi_with_a_beautiful_well_groomed_coat.jpg&exph=565&expw=850&q=corgi&simid=608028607953243050&ck=C46C3AA78016CCD7946E90CFE01A5E26&selectedIndex=48&mode=overlay` |
| +15 | ##+js(set-constant, Blob, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?view=detailV2&ccid=9d6Vx%2fqt&id=1E67D03AEB0E6473BE4AA271F73CD9BA5ABF6BC6&thid=OIP.9d6Vx_qtBNAeje6oAgd77AHaE7&mediaurl=https%3a%2f%2fcdn.omlet.co.uk%2fimages%2foriginals%2fDog-Dog_Guide-A_Pembroke_Welsh_Corgi_with_a_beautiful_well_groomed_coat.jpg&exph=565&expw=850&q=corgi&simid=608028607953243050&ck=C46C3AA78016CCD7946E90CFE01A5E26&selectedIndex=48&mode=overlay` |
| +14 | ##html[style="overflow: hidden;"]:style(overflow: visible !important;) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?view=detailV2&ccid=9d6Vx%2fqt&id=1E67D03AEB0E6473BE4AA271F73CD9BA5ABF6BC6&thid=OIP.9d6Vx_qtBNAeje6oAgd77AHaE7&mediaurl=https%3a%2f%2fcdn.omlet.co.uk%2fimages%2foriginals%2fDog-Dog_Guide-A_Pembroke_Welsh_Corgi_with_a_beautiful_well_groomed_coat.jpg&exph=565&expw=850&q=corgi&simid=608028607953243050&ck=C46C3AA78016CCD7946E90CFE01A5E26&selectedIndex=48&ajaxhist=0` |
| +14 | /ls.gif? | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/ls.gif?IG=F38F52925A134B708C5934745BD50F1F&Type=Event.ClientInst&DATA={%22T%22:%22CI.Scroll%22,%22Name%22:%22ExpandControl%22,%22ComponentId%22:%22mmComponent_images_2_exp%22,%22TS%22:1613794153845}&log=UserEvent` |
| +11 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=F38F52925A134B708C5934745BD50F1F&TYPE=Event.ClientInst&DATA=%5B%7B%22T%22%3A%22CI.Init%22%2C%22TS%22%3A1613794148856%2C%22Name%22%3A%22Base%22%2C%22FID%22%3A%22CI%22%7D%2C%7B%22T%22%3A%22CI.ClientInst%22%2C%22TS%22%3A1613794148856%2C%22Name%22%3A%22OrgId%22%2C%22FID%22%3A%22NoSignInAttempt%22%7D%2C%7B%22UNCount%22%3A%220%22%2C%22UINCount%22%3A%220%22%2C%22TraceId%22%3A%22D9CCC1149FF94ECD8496618B9A09BB01%22%2C%22WasBellIconShown%22%3A%22true%22%2C%22IsEligibleForBellIcon%22%3A%22true%22%2C%22TimeSincePageLoad%22%3A%221139%22%2C%22Latency%22%3A%22136%22%2C%22T%22%3A%22CI.ContentStatistics%22%2C%22TS%22%3A1613794149228%2C%22Name%22%3A%22NotificationCount%22%2C%22FID%22%3A%22BNCenter%22%7D%2C%7B%22T%22%3A%22CI.CI.Info%22%2C%22TS%22%3A1613794150033%2C%22Name%22%3A%22ScaleAnim%22%2C%22FID%22%3A%22RewardsReportActivity%22%7D%2C%7B%22T%22%3A%22CI.CI.Info%22%2C%22TS%22%3A1613794150334%2C%22Name%22%3A%22ScaleAnim%22%2C%22FID%22%3A%22RewardsReportActivity%22%7D%5D` |
| +10 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx` |
| +9 | ##+js(set-constant, SVGForeignObjectElement, undefined) |  | `www.bing.com` |  | dom | `https://www.bing.com/orgid/idtoken/nosignin` |
| +9 | ##+js(set-constant, AdBTrack.AdbMon.isBlocked, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/orgid/idtoken/nosignin` |
| +9 | ##+js(set-constant, AdBlockerTracking.AdBlockMonitor, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/orgid/idtoken/nosignin` |
| +9 | ##+js(set-constant, Blob, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/orgid/idtoken/nosignin` |
| +8 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx?` |
| +8 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=F38F52925A134B708C5934745BD50F1F&Type=Event.CPT&DATA={%22pp%22:{%22S%22:%22L%22,%22FC%22:21,%22BC%22:335,%22SE%22:-1,%22TC%22:-1,%22H%22:958,%22BP%22:1044,%22CT%22:1047,%22IL%22:243},%22ad%22:[-1,-1,1577,997,1577,2638,0]}&P=images&DA=BN2B` |
| +8 | ##+js(set-constant, SVGForeignObjectElement, undefined) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +8 | ##+js(set-constant, AdBTrack.AdbMon.isBlocked, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +8 | ##+js(set-constant, AdBlockerTracking.AdBlockMonitor, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +8 | ##+js(set-constant, Blob, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +8 | ##+js(set-constant, SVGForeignObjectElement, undefined) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +8 | ##+js(set-constant, AdBTrack.AdbMon.isBlocked, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +8 | ##+js(set-constant, AdBlockerTracking.AdBlockMonitor, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +8 | ##+js(set-constant, Blob, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +7 | ##+js(set-constant, SVGForeignObjectElement, undefined) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +7 | ##+js(set-constant, AdBTrack.AdbMon.isBlocked, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +7 | ##+js(set-constant, AdBlockerTracking.AdBlockMonitor, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +7 | ##+js(set-constant, Blob, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/images/search?q=corgi` |
| +6 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=ADD142803DA94A5DB0BF464262158F0B&Type=Event.PPT&DATA={%22S%22:566,%22E%22:2784,%22T%22:0,%22I%22:0,%22N%22:{},%22M%22:{}}&P=SERP&DA=BN2B` |
| +6 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=ADD142803DA94A5DB0BF464262158F0B&TYPE=Event.ClientInst&DATA=%5B%7B%22T%22%3A%22CI.DevLoc%22%2C%22TS%22%3A1613794146559%2C%22Name%22%3A%22Perm_NotGranted_NoTryGet%22%2C%22FID%22%3A%22AutoPrompt%22%7D%5D` |
| +6 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=ADD142803DA94A5DB0BF464262158F0B&TYPE=Event.ClientInst&DATA=%5B%7B%22T%22%3A%22CI.DevLoc%22%2C%22TS%22%3A1613794146558%2C%22Name%22%3A%22Perm_Prompt%22%2C%22FID%22%3A%22AutoPrompt%22%7D%5D` |
| +6 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=ADD142803DA94A5DB0BF464262158F0B&TYPE=Event.ClientInst&DATA=%5B%7B%22T%22%3A%22CI.DevLoc%22%2C%22TS%22%3A1613794146519%2C%22Name%22%3A%22Perm_Available%22%2C%22FID%22%3A%22AutoPrompt%22%7D%5D` |
| +6 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=ADD142803DA94A5DB0BF464262158F0B&TYPE=Event.ClientInst&DATA=%5B%7B%22T%22%3A%22CI.ClientInst%22%2C%22TS%22%3A1613794145241%2C%22Name%22%3A%22OrgId%22%2C%22FID%22%3A%22NoSignInAttempt%22%7D%2C%7B%22UNCount%22%3A%220%22%2C%22UINCount%22%3A%220%22%2C%22TraceId%22%3A%223548EF90ED7A4F3893E08A3838A93126%22%2C%22WasBellIconShown%22%3A%22true%22%2C%22IsEligibleForBellIcon%22%3A%22true%22%2C%22TimeSincePageLoad%22%3A%221285%22%2C%22Latency%22%3A%22145%22%2C%22T%22%3A%22CI.ContentStatistics%22%2C%22TS%22%3A1613794145516%2C%22Name%22%3A%22NotificationCount%22%2C%22FID%22%3A%22BNCenter%22%7D%2C%7B%22T%22%3A%22CI.CI.Info%22%2C%22TS%22%3A1613794146293%2C%22Name%22%3A%22ScaleAnim%22%2C%22FID%22%3A%22RewardsReportActivity%22%7D%2C%7B%22T%22%3A%22CI.DevLoc%22%2C%22TS%22%3A1613794146518%2C%22Name%22%3A%22PromptDevLoc%22%2C%22FID%22%3A%22AutoPrompt%22%7D%5D` |
| +6 | ##+js(set-constant, SVGForeignObjectElement, undefined) |  | `www.bing.com` |  | dom | `https://www.bing.com/orgid/idtoken/conditional` |
| +6 | ##+js(set-constant, AdBTrack.AdbMon.isBlocked, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/orgid/idtoken/conditional` |
| +6 | ##+js(set-constant, AdBlockerTracking.AdBlockMonitor, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/orgid/idtoken/conditional` |
| +6 | ##+js(set-constant, Blob, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/orgid/idtoken/conditional` |
| +5 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=ADD142803DA94A5DB0BF464262158F0B&TYPE=Event.ClientInst&DATA=%5B%7B%22T%22%3A%22CI.Init%22%2C%22TS%22%3A1613794144345%2C%22Name%22%3A%22Base%22%2C%22FID%22%3A%22CI%22%7D%2C%7B%22T%22%3A%22CI.Info%22%2C%22TS%22%3A1613794144345%2C%22Name%22%3A%22XW%22%2C%22FID%22%3A%22BRW%22%7D%2C%7B%22T%22%3A%22CI.Info%22%2C%22TS%22%3A1613794144345%2C%22Name%22%3A%22T%22%2C%22FID%22%3A%22BRH%22%7D%2C%7B%22T%22%3A%22CI.Info%22%2C%22TS%22%3A1613794144347%2C%22Name%22%3A%221%22%2C%22FID%22%3A%22DM%22%7D%2C%7B%22comp%22%3A%22loaded%22%2C%22time%22%3A1510%2C%22T%22%3A%22CI.Data%22%2C%22TS%22%3A1613794145111%2C%22Name%22%3A%22speech%22%2C%22FID%22%3A%22HP%22%7D%5D` |
| +4 | ##.b_ad:remove() |  | `www.bing.com` |  | dom | `https://www.bing.com/search?q=corgi&pq=` |
| +4 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx?` |
| +4 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=ADD142803DA94A5DB0BF464262158F0B&Type=Event.CPT&DATA={%22pp%22:{%22S%22:%22L%22,%22FC%22:28,%22BC%22:354,%22SE%22:-1,%22TC%22:-1,%22H%22:400,%22BP%22:443,%22CT%22:446,%22IL%22:26},%22ad%22:[-1,-1,1577,1014,1577,3744,0]}&P=SERP&DA=BN2B&MN=SERP` |
| +4 | ##+js(set-constant, SVGForeignObjectElement, undefined) |  | `www.bing.com` |  | dom | `https://www.bing.com/search?q=corgi&pq=` |
| +4 | ##+js(set-constant, AdBTrack.AdbMon.isBlocked, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/search?q=corgi&pq=` |
| +4 | ##+js(set-constant, AdBlockerTracking.AdBlockMonitor, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/search?q=corgi&pq=` |
| +4 | ##+js(set-constant, Blob, noopFunc) |  | `www.bing.com` |  | dom | `https://www.bing.com/search?q=corgi&pq=` |
| +3 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=6F541406ACBF4C9DB5094A1CDD9A8F73&TYPE=Event.ClientInst&DATA=%5B%7B%22nodeName%22%3A%22Searchform%22%2C%22parentNodeName%22%3A%22Searchbox%22%2C%22click_type%22%3A%22form%22%2C%22T%22%3A%22CI.Click%22%2C%22TS%22%3A1613794143599%2C%22Name%22%3A%22Searchform%22%2C%22FID%22%3A%22HP%22%7D%5D` |
| +3 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=6F541406ACBF4C9DB5094A1CDD9A8F73&TYPE=Event.ClientInst&DATA=%5B%7B%22nodeName%22%3A%22Searchform%22%2C%22parentNodeName%22%3A%22Searchbox%22%2C%22click_type%22%3A%22form%22%2C%22T%22%3A%22CI.Click%22%2C%22TS%22%3A1613794143598%2C%22Name%22%3A%22Searchform%22%2C%22FID%22%3A%22HP%22%7D%5D` |
| +2 | \|\|bing.com/fd/ls/l?ig= | -- | `www.bing.com` | 1 | image | `https://www.bing.com/fd/ls/l?IG=6F541406ACBF4C9DB5094A1CDD9A8F73&TYPE=Event.ClientInst&DATA=%5B%7B%22sbox%22%3A%22typing%22%2C%22time%22%3A130739%2C%22T%22%3A%22CI.Data%22%2C%22TS%22%3A1613794142714%2C%22Name%22%3A%22speech%22%2C%22FID%22%3A%22HP%22%7D%5D` |
| +0 | \|\|bing.com/fd/ls/lsp.aspx | -- | `www.bing.com` | 1 | xhr | `https://www.bing.com/fd/ls/lsp.aspx` |
</details>

**Comment by yokoffing** [comment]
![Screenshot 2021-02-19 232023](https://user-images.githubusercontent.com/11689349/108583664-13432700-7309-11eb-9c8f-c4c286d2ff50.jpg)

**Comment by llacb47** [comment]
Any errors in the console?

**Comment by yokoffing** [comment]
> 
> 
> Any errors in the console?

Actually, yes! This `DOMException` pop ups right before my page blanks out.


![Screenshot 2021-02-22 222444](https://user-images.githubusercontent.com/11689349/108798878-d5d6d780-755c-11eb-80b1-bc46bdfd9874.jpg)

**Comment by llacb47** [comment]
How easily does it reproduce? For example, on this page, if you click the right arrow, does it happen? What are the steps to reproduce from this page specifically (just asking so I can try to repro/debug)

`https://www.bing.com/images/search?q=visual+field+defect&view=detailv2&id=D6E069DBFC397D8CFD583410BA2C276126A55C3A&selectedindex=710&ccid=xu4wQcMQ&simid=608008615014302849&thid=OIP.xu4wQcMQvxAKlFtynoURdgHaDk&mode=overlay&ck=D54995F90648556188D376930959C5BB&mediaurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FRc6ee3041c310bf100a945b729e851176%3Frik%3DOlylJmEnLLoQNA%26riu%3Dhttp%253a%252f%252fwww.mult-sclerosis.org%252foptic_neuritis.jpg%26ehk%3DEzLetdKZzoulWXLakkQ9sNY%252fVh5GVNTDwOzlL2QxqIA%253d%26risl%3D%26pid%3DImgRaw&exph=299&expw=620&vt=0&sim=11`

**Comment by yokoffing** [comment]
It reproduces every time I use Bing Images and use the gallery view. It's been happening for months now.

![sample](https://user-images.githubusercontent.com/11689349/108801600-2e5da300-7564-11eb-94b0-7c820146a87d.gif)

**Comment by Yuki2718** [comment]
I too use bing often and haven't ever be able to reproduce, but we get the same reports again and again both here and on AG repo:
https://github.com/AdguardTeam/AdguardFilters/issues/76248
https://github.com/AdguardTeam/AdguardFilters/issues/76395
Where there's smoke there's fire. @yokoffing Does
`||bing.com/fd/ls/lsp.aspx$xhr,redirect=noop.txt`
instead of the allow rule help?

**Comment by yokoffing** [comment]
> Does `||bing.com/fd/ls/lsp.aspx$xhr,redirect=noop.txt` instead of the allow rule help?

No. I removed my allow rule and added your rule. The issue still occurs with your rule.

**Comment by Yuki2718** [comment]
@yokoffing Okay, thx.

**Comment by llacb47** [comment]
@yokoffing I'm trying to debug this but having trouble. Can you reproduce in Chrome? If so, after the error occurs, can you open the console, go to the console tab, and click this icon?
![image](https://user-images.githubusercontent.com/16567977/109877394-f7ad1a00-7c40-11eb-88ba-f2952b7f0ccb.png)
Then reload the page and take a screenshot of the console when the script throws the error. (Use the pretty-print button in the bottom left corner to make the script look nice before screenshotting) Also, type `console.trace()` in the console and take a screenshot of that. 

Example of what the screenshots should like:
![image](https://user-images.githubusercontent.com/16567977/109877715-596d8400-7c41-11eb-89c0-65ff1836ad21.png)
![image](https://user-images.githubusercontent.com/16567977/109877819-7b670680-7c41-11eb-8617-39444788552d.png)

**Comment by yokoffing** [comment]
@llacb47 - I cannot reproduce my issue in Chrome; Chrome is unaffected for me. Also tried Edge and couldn't reproduce there. Tried Firefox again: issue is still there.

I am using the same version of uBlock Origin. I'm also using the same extensions that I use in Firefox.

Are there any other complaints besides the two you've listed above? I thought for sure this was Firefox doing something funky, but I see one of the reporters said they're using Edge.

**Comment by llacb47** [comment]
@yokoffing  I made a screen recording. Basically, open the dev console and check the two checkboxes seen in the video right before you know the error will reliably reproduce.

`https://streamable.com/x9jawb`

**Comment by yokoffing** [comment]
@llacb47 Here's the image in Bing's image gallery view I was using:
`https://www.bing.com/images/search?view=detailV2&ccid=VEz85IJ5&id=4629512B374E34CDEAA402F835A1AAC4DA75A3EA&thid=OIP.VEz85IJ5Yfb8mQFU2tiPggHaLH&mediaurl=https%3a%2f%2fcelebmafia.com%2fwp-content%2fuploads%2f2018%2f08%2fhilary-duff-muse-x-hilary-duff-glasses-photoshoot-19.jpg&exph=1920&expw=1280&q=hilary+duff&simid=608051886795129612&ck=8BBF47F09F6419AA26EE831FB2E1F3B6&selectedIndex=1&ajaxhist=0`

Here's the code from console.trace(). I tested to confirm that the debugger was catching the error I was experiencing: `https://bin.nixnet.services/?8ad574df5363d4ea#CNSe4QQwXCUKLruvz9b5tKHWeHDBSU8HTW1hs2K4pwMm`

**Comment by llacb47** [comment]
You didn't screenshot the code that threw the error, like I showed in the video.

**Comment by yokoffing** [comment]
It logs it as a Network Error, and the code it references is quite monstrous:

`https://bin.nixnet.services/?eaabb6e756f1c10a#GDnaRSrLXUwXtBu47zdbLpmAjZeKypPik3nV7tzsemYh`

**Comment by Yuki2718** [comment]
Now reproduced on Firefox but only one profile (uBO default + AG Social + AG Annoyances), I mimicked with another profile but can't reproduce. I get the same error as @yokoffing ( olk8MD1olCNVxsH05EHDleKtqDI.br.js:145:381) on the reproducible profile and #b_content is empty.

**Comment by Yuki2718** [comment]
@llacb47 My console layout seems to be quite different form your SS even on Chrome, you meant to set break point by the icon?

**Comment by Yuki2718** [comment]
Workaround: `bing.com##+js(nosiif, logQueue, 10000)`

**Comment by yokoffing** [comment]
> Workaround: `bing.com##+js(nosiif, logQueue, 10000)`

This works for me!
