### ISSUE TITLE
hentainexus.com

### ISSUE THREAD

**Issue by ZaphodBeebblebrox** [easylist/easylist#7249]
### List the website(s) you're having issues:

`https://hentainexus.com/view/8897`

### What happens?
There is an ad on the top of the website.

### List Subscriptions you're using:
µBlock Origin defaults.

### Your settings

- OS/version: Win 10
- Browser/version: Chrome 88.0.4324.182
- Adblock Extension/version: µBlock Origin 1.33.2

### Other details:
```
||hentainexus.com/unit/dt_ban/*.gif$image,1p
hentainexus.com##.unit-main > a:nth-of-type(1)
```
First removes the ad, second removes the placeholder.

**Comment by Yuki2718** [comment]
Now dead?
