### ISSUE TITLE
https://yieldlab.science/ erroneously blocked 

### ISSUE THREAD

**Issue by d0gf4rt** [easylist/easylist#7271]
### List the website(s) you're having issues:

`https://yieldlab.science/`

### What happens?

the site is blocked by easylist when it should not be.

### List Subscriptions you're using:

ublock origin

### Your settings

- OS/version: any
- Browser/version: any
- Adblock Extension/version: any

**Comment by Khrin** [comment]
This has been already fixed: https://github.com/easylist/easylist/commit/6296dd38439cb5b674f3f616a7e6ca10842ab824
