### ISSUE TITLE
distractify.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7273]
### List the website(s) you're having issues:

`https://www.distractify.com/p/texas-fake-snow-conspiracy-tiktok`

### What happens?

Many huge placeholders pretty much everywhere.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/108927178-18251500-7640-11eb-8915-f65bb0640ece.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 88.0.4324.182 x64
- Adblock Extension/version: uBO 1.33.3b8 + IDCAC 3.2.7

### Other details:

I propose:
```
distractify.com#?#div:-abp-has(> .ad-vertical)
distractify.com##main + aside
```

![image](https://user-images.githubusercontent.com/22780683/108927112-f4fa6580-763f-11eb-9b42-352afc6d0b4c.png)

**Comment by THEtomaso** [comment]
> https://github.com/easylist/easylist/commit/842ff152ee3e506a6dd130b1fc4ee06dd0ec9cc0

**Issue:**
This rule breaks the header, on some subpages:
`distractify.com##.obIeh`

**Examples:**
`https://www.distractify.com/p/is-mckenna-grace-related-to-kiernan-shipka/`
`https://www.distractify.com/p/teal-swan-husband/`

**Possible fix** (for '**uBlock filters**' / '**uBlock filters - Unbreak**') _(@mapx-)_:
`distractify.com##.ad-title:upward(1)`
`distractify.com##[id^="div-gpt-ad-"]:upward(2)`
`distractify.com#@#.obIeh`
