### ISSUE TITLE
timesnownews.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7274]
### List the website(s) you're having issues:

`https://www.timesnownews.com/the-buzz/article/tiktok-conspiracy-theorists-are-trying-to-prove-texas-snow-is-fake-generated-by-govt-watch/724007`

### What happens?

Various placeholders. They may be small, but they're plentiful.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/108927178-18251500-7640-11eb-8915-f65bb0640ece.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 88.0.4324.182 x64
- Adblock Extension/version: uBO 1.33.3b8 + IDCAC 3.2.7

### Other details:

I propose:
```
timesnownews.com##.uniqe-add
timesnownews.com#?#.content-block:-abp-has(> .ad-panel-wrap)
timesnownews.com##.ad-section-one
```

![image](https://user-images.githubusercontent.com/22780683/108927551-c7fa8280-7640-11eb-955d-296a2c20b175.png)

**Comment by ryanbr** [comment]
Not easy to fix top, but this will clean up the site more.
