### ISSUE TITLE
Tracker from .gov.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [easylist/easylist#7282]
### List the website(s) you're having issues:
`ca.gov.vn`

### What happens?

When running the program `vSignPDF_3.1.8` from `https://ca.gov.vn/documents/20182/6768590/vSignPDF_3.1.8.zip/6a5ed276-21ef-49f1-93fd-7558ec918294`
The tracker appears: `log.ca.gov.vn`
### List Subscriptions you're using:

`Adguard DNS, Easylist Privacy, StevenBlack...`
### Your settings

- OS/version: `Windows`
- Browser/version: `Chromium`
- Adblock Extension/version: `Adguard/NextDNS`

**Comment by spirillen** [comment]
Thanks you for reporting all these trackers @vhpcdpgl 

Is there by any change, that you in the future also would help your other fellow country men by adding them to our lists as well?? <https://www.mypdns.org/T3329>

The reason I'm asking is we are going to co-operate with ChongLuaDao.vn project within the next few days, and your findings would be a big aid to these projects, You can read more about the co-operation in here: <https://www.mypdns.org/T3681>

If, you agree to help our projects, you are simply using your GH profile to signup, and then you should go to the <https://www.mypdns.org/settings/user/Spirillen/page/emaildelivery/> to disable the e-mails (Sorry, but haven't been able to disable this globally :unamused: ) and then in <https://www.mypdns.org/settings/user/Spirillen/page/emailpreferences/> you can specify what and how to receive notifications.
