### ISSUE TITLE
[EasyList] bbc.com/portuguese

### ISSUE THREAD

**Issue by Tiagoquix** [easylist/easylist#7288]
### List the website(s) you're having issues:

```
https://www.bbc.com/portuguese
https://www.bbc.com/portuguese/brasil-56188291 (and other articles too)
```

### What happens?

There is some leftover banners from blocked ads. In the main website (`https://www.bbc.com/portuguese`), there is one on the top:

![image](https://user-images.githubusercontent.com/30274161/109228824-2fc7df00-77a1-11eb-8a60-7cbd8a31e1d0.png)

And also there is one on the middle:

![image](https://user-images.githubusercontent.com/30274161/109228946-66055e80-77a1-11eb-86bf-3c4cd8233aaf.png)

**On articles, there is one blocked ad banner on the top:**

![image](https://user-images.githubusercontent.com/30274161/109229088-96e59380-77a1-11eb-8e09-8a48ba9e0320.png)

And on the middle of the articles, there is also one too:

![image](https://user-images.githubusercontent.com/30274161/109229151-a8c73680-77a1-11eb-9d1e-e876c0324e45.png)

### List Subscriptions you're using:

I am using uBlock Origin with their default lists. About "easy" listings, I'm using EasyList and EasyPrivacy.

### Your settings

- OS/version: Windows 10 Pro 20H2
- Browser/version: Google Chrome Version 88.0.4324.190 (Official version) 64 bits
- Adblock Extension/version: uBlock Origin - Version 1.33.2

### Other details:

No additional notes.

**Comment by DandelionSprout** [comment]
AdGuard Base has `bbc.com##section[data-e2e="advertisement"]`, which could presumably be copied over to EasyList, especially since it also occurs on the French site version: `https://www.bbc.com/afrique`

**Comment by Khrin** [comment]
OK, added.
