### ISSUE TITLE
sankakucomplex.com

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#7289]
`https://www.sankakucomplex.com/`

clickunder (clearing cookies required)

```
||kiynew.com^
||mxuiso.com^
```

**Comment by stephenhawk8054** [comment]
There are ads placeholders.

URL (NSFW): `https://chan.sankakucomplex.com/`

Screenshot:

[https://i.ibb.co/60M8DNM/image.png](https://i.ibb.co/60M8DNM/image.png)

Firefox 95.0, ublock 1.39.2 default filters.

Proposed filter:

`sankakucomplex.com##.scad-i`
