### ISSUE TITLE
majorgeeks.com

### ISSUE THREAD

**Issue by Pentaphon** [easylist/easylist#7307]
### List the website(s) you're having issues:

`https://www.majorgeeks.com/`

### What happens?

Banner ad by restoro on left hand side. 

### List Subscriptions you're using:

Easylist, Easyprivacy, Easylist Cookie

### Your settings

- OS/version: WIndows 10 64bit
- Browser/version: Firefox 86
- Adblock Extension/version: uBlock Origin v1.33.2

### Other details:

![Screenshot_2021-02-28 MajorGeeks Com - MajorGeeks](https://user-images.githubusercontent.com/49374058/109415837-e7aae700-796f-11eb-81cf-21bc9fb9b052.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/523d9dd6366c75812410cdb92862d62207585e68
