### ISSUE TITLE
sourcepointcmp.bloomberg.com/ccpa.js

### ISSUE THREAD

**Issue by arlogilbert** [easylist/easylist#7308]
This script is in the allow list and includes tracking, sets cookies, does browser detection, geo targets, and links to third parties.

Based upon the criteria for easyprivacy, this script should not be allowed. 

https://sourcepointcmp.bloomberg.com/ccpa.js

**Comment by Khrin** [comment]
This script cannot be blocked, otherwise could cause issues.

**Comment by arlogilbert** [comment]
> This script cannot be blocked, otherwise could cause issues.

Thats the same problem we raised when we pointed out that Easylist is blocking consent dialogs on sites like metlife, expedia, harley davidson and thousands of others. Why is the bloomberg consent management tool which is created by sourcepoint (and does include tracking) permitted to be whitelisted but other cosent managers are not whitelisted?
