### ISSUE TITLE
(NSFW) viptube.pro

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#7313]
### List the website(s) you're having issues:

`https://www.viptube.com/video/4680318/blondes-love-dick-taylor-tilden-pov`

### What happens?

Video overlay

### List Subscriptions you're using:

Irrelevant

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

This rule does it, which file should I submit it too ??

```
! 2021-03-01 https://www.viptube.com
viptube.com##.drt-sponsor-block
viptube.com##.partner_text_link
viptube.com###spot_video_partner_banner
viptube.com##.footer_adv
```

And one that might need some assistants

`viptube.com##div.stem_related.stem:nth-of-type(4)`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/blob/master/easylist_adult/adult_specific_hide.txt

**Comment by spirillen** [comment]
Thanks, Is there any kind of sort order in that file? at first clans it looks rather messy!!
