### ISSUE TITLE
CBSNews.com - Modal overlay (EasyList Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#7318]
### Affected site:
`https://www.cbsnews.com/`

### Issue:
Grey modal overlay.
(**IMPORTANT**: See **NOTE** below!)

### Problem filters:
* **EasyList Cookie List**
* **Fanboy's Annoyance List**

### NOTE:
The issue uccurs when one of the above filters are used in combination with one of these:
* **AdGuard Annoyances filter**
* **I don't care about cookies**

(Although, for some reason, I was unable to pinpoint the exact rules that are in conflict)

### Problem rule:
`@@||geolocation.onetrust.com/cookieconsentpub/$script`

### Related issue:
A similar problem uccurs @ **GameSpot.com**:
https://github.com/easylist/easylist/issues/7216

### Possible fix:
```
- @@||geolocation.onetrust.com/cookieconsentpub/$script

+ ||geolocation.onetrust.com/cookieconsentpub/$script,domain=cbsnews.com|gamespot.com
+ @@||geolocation.onetrust.com/cookieconsentpub/$script,domain=~cbsnews.com|~gamespot.com
```

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.1.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by spirillen** [comment]
|name|type|content|
|----|----|-------|
|onetrust.com.tracking.mypdns.cloud|CNAME|.|
|*.onetrust.com.tracking.mypdns.cloud|CNAME|.|

I don't have any issues with `Grey modal overlay`(EU).... That said, Videos are not playing. But that is related to another domain.

<details><summary>screenshot, no ISSUE's blocking onetrust.com</summary>

![image](https://user-images.githubusercontent.com/44526987/109696226-19e56000-7b8d-11eb-82b3-1d6d09b680b5.png)

</details>

**Comment by THEtomaso** [comment]
Read my report again, spirillen.
The issue uccurs if you use **EasyList Cookie List** / **Fanboy's Annoyance List** in combination with **AdGuard Annoyances filter** and/or **I don't care about cookies** !

**Comment by spirillen** [comment]
Ups, your right. I have miss read the 3 liner and didn't notice you actually would append

**Comment by THEtomaso** [comment]
> What am I missing?

**EasyList Cookie List** / **Fanboy's Annoyance List** already blocks `onetrust.com` on a third-party basis.
However, the filters also contains whitelisting rules, to avoid various breakage (blocked videos etc.).
But in the case of `cbsnews.com` and `gamespot.com`, the generic geolocation whitlisting (which is supposed to FIX issues) actually CAUSES issues, in combination with certain blocking rules.

Of the two rules that I suggested, the first one is a blocking rule, which specifically blocks OneTrust's geolocation script @ `cbsnews.com` and `gamespot.com`.
The second rule is a modification of the existing whitelisting rule, which simply adds `cbsnews.com` and `gamespot.com` as exceptions, excluding them from the whitelisting (which otherwise would take priority over the blocking rule).
Both rules are necessary, since `$important` isn't supported in ABP-based blockers.

Hope this helps explain things.

**Comment by spirillen** [comment]
Thanks for your reply... Took on my glasses an found the one I missed when reading. `~` (not)
