### ISSUE TITLE
thevideo.me have moved domain to thevideo.io

### ISSUE THREAD

**Issue by grufwub** [easylist/easylist#732]
Thevideo.me have moved domain to thevideo.io, as such nothing seems to be catching their popups that open everytime you click anywhere on the page or the video player.

Adding these filters to uBlock Origin's custom filters seems to fix the issue, though I'm sure this could probably be optimized better than how I've managed it:

||thevideo.io/js/jspc.js?ab
thevideo.io#$#div[id*="Composite"] { position: absolute!important; top: -2000px!important; }
||thevideo.io/zone
thevideo.io##.player-options-section > div[class="col-md-4 p-l-0"]
thevideo.io##.sponsored-content thevideo.io###vplayer > .vjs-overlay-banner300x
thevideo.io###player_code > .col-sm-3
/pfz.swf|$domain=thevideo.io
||thevideo.io/mpaabpu/$popup
||thevideo.io/cgi-bin/get_creatives.cgi?
||thevideo.io/creatives/
||thevideo.io/js/jsmpc.js
||thevideo.io/js/jspc.js
||thevideo.io/js/popup.min.js
||thevideo.io/mba/cds.js
||thevideo.io/player/offers.js
||thevideo.io/*.php$popup
||thevideo.io/*:$popup
||thevideo.io/*_$popup
||thevideo.io/mpaabp/$popup
||thevideo.io^$popup,domain=thevideo.io
||ajax.googleapis.com^$script,domain=thevideo.io
||connect.facebook.net^$script,domain=thevideo.io
||tawk.to^$script,xmlhttprequest,domain=thevideo.io
|http://$script,third-party,xmlhttprequest,domain=thevideo.io
|https://$script,third-party,xmlhttprequest,domain=thevideo.io
thevideo.io###boxly-container
thevideo.io###closeA
thevideo.io###overlayA
thevideo.io###pre_counter
thevideo.io###secondaryto
thevideo.io###vplayer_offers
thevideo.io##.vid_a8
thevideo.io##.video_a800
thevideo.io##[id][class][style] > [class][onclick]
thevideo.io##div[class][style*="height:100%;"]:last-child
thevideo.io##div[class][style] > a[style]:last-child
thevideo.io##div[id^="vpn_notice"]
thevideo.io##div[onclick] > a
thevideo.io##div[style*="height: 300px;width: 300px"]
thevideo.io##script[src^="data:text/"] + div[id][style]
thevideo.io##script[type="text/javascript"] + [style="display: block;"]
||thevideo.io/js/ad*.js
||pc.thevideo.io^$popup,third-party

**Comment by darkmorpher** [comment]
It's `thevideo.ch` now
