### ISSUE TITLE
mrjatt.fun

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#7326]
### List the website(s) you're having issues:

`https://mrjatt.fun/file/N_T7_MAs2jI.html`

### What happens?

Popup ads

### List Subscriptions you're using:

Ublock origin default  lists

### Your settings

- OS/version: windows
- Browser/version: Firefox stable
- Adblock Extension/version: ublock origin 1.33.2

### Other details:

`||e702fa7de9d35c37.com^`

**Comment by spirillen** [comment]
`||e702fa7de9d35c37.com^` doesn't solve the problem, but certainly an adserver

**Comment by ghajini** [comment]
Ubo specific solution

`mrjatt.fun##+js(acis, decodeURI, decodeURIComponent)`
