### ISSUE TITLE
lastampa.it > Video Issues 

### ISSUE THREAD

**Issue by FabioEight** [easylist/easylist#7327]
### List the website(s) you're having issues:

https://www.lastampa.it 

Caused by blocking:
oasjs.kataweb.it

### What happens?

Home page videos not loaded.

### List Subscriptions you're using:

Easy List

### Your settings
- OS/version: Windows 10
- Browser/version: Edge 88
- Adblock Extension/version:  uBlock

### Other details:

Bypassing the host "oasjs.kataweb.it" fixes the issue.

**Comment by Khrin** [comment]
Hi, have you subscribed EasyList Italy? It already have the necessary filters to fix this issue.

**Comment by FabioEight** [comment]
> Hi, have you subscribed EasyList Italy? It already have the necessary filters to fix this issue.

Apologies, yes it’s listed in EasyList Italy.
