### ISSUE TITLE
best-hindishayari.in

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#7329]
### List the website(s) you're having issues:

`https://best-hindishayari.in`

### What happens?

Ads by adshares
![image](https://user-images.githubusercontent.com/20338483/110082000-c94f4c00-7db2-11eb-86d0-58b1d0458c92.png)

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: opera stable
- Adblock Extension/version: ubo1.33.2

### Other details:

`||fuqypaqu.xyz^`

**Comment by spirillen** [comment]
>> `best-hindishayari.in###custom_html-14` works for me on Tor
