### ISSUE TITLE
speedostream.com

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#7331]
### List the website(s) you're having issues:

`https://speedostream.com/embed-f8kj1y6wwciw.html`

Embed link came from
`https://yomovies.mx/asli-rakhwala-natakam-2021-hindi-dubbed-Watch-online-full-movie/`

### What happens?

Push notification ads
![Screenshot_2021-03-05-16-09-10-618_org mozilla fenix](https://user-images.githubusercontent.com/20338483/110108564-5ce44500-7dd2-11eb-9cb0-76bcaf7723cc.png)

### List Subscriptions you're using:

Ublock origin default lists

### Your settings

- OS/version: android
- Browser/version: Firefox 88
- Adblock Extension/version: ubo 1.33.2

### Other details:

 certain filters help
```
||edxlewni.com^
||tgvbwjbnxz.com^
||adactioner.com^
||achilles-ena.com^
||coderformylife.info^
||notifypicture.info^
||a.speedostream.com/api/spots/*$script,first-party
```

**Comment by spirillen** [comment]
Tested in FF and no hits on any of the OP's domains

<details><summary>Logger output FireFox</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +44 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca253iute5kipszthdbg3q/seg-3-v1-a1.ts` |
| +39 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca2sviwte5kip4styzpmaq/seg-2-v1-a1.ts` |
| +31 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca253iute5kipszthdbg3q/seg-2-v1-a1.ts` |
| +31 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca253iute5kipszthdbg3q/index-v1-a1.m3u8` |
| +24 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca2sviwte5kip4styzpmaq/seg-1-v1-a1.ts` |
| +24 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca2sviwte5kip4styzpmaq/index-v1-a1.m3u8` |
| +24 | #@#.afs_ads |  | speedostream.com |  | dom | `https://speedostream.com/embed-f8kj1y6wwciw.html` |
| +24 | ##.jw-settings-sharing |  | speedostream.com |  | dom | `https://speedostream.com/embed-f8kj1y6wwciw.html` |
| +24 | ##div[button="share"] |  | speedostream.com |  | dom | `https://speedostream.com/embed-f8kj1y6wwciw.html` |
| +24 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca2,sviwte5kip4styzpmaq,53iute5kipszthdbg3q,.urlset/master.m3u8?xxx=123` |
| +24 |  |  | speedostream.com | 3 | frame | `https://g.jwpsrv.com/g/gcid-0.1.2.html?notrack` |
| +24 |  |  | speedostream.com | 1 | image | `https://speedostream.com/favicon.ico` |
| +23 |  |  | speedostream.com | 3 | script | `https://jwplayer-dualstack.map.fastly.net/` | `aliasURL=https://ssl.p.jwpcdn.com/player/v/8.9.5/provider.hlsjs.js` |
| +23 |  |  | speedostream.com | 3 | script | `https://jwplayer-dualstack.map.fastly.net/` | `aliasURL=https://ssl.p.jwpcdn.com/player/v/8.9.5/jwplayer.core.controls.js` |
| +23 |  |  | speedostream.com | 3 | script | `https://jwplayer-dualstack.map.fastly.net/` | `aliasURL=https://ssl.p.jwpcdn.com/player/v/8.9.5/jwpsrv.js` |
| +23 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/oapxVQ9.js` |
| +23 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.9.5/provider.hlsjs.js` |
| +23 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.9.5/jwplayer.core.controls.js` |
| +23 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.9.5/jwpsrv.js` |
| +23 | \|\|p.jwpcdn.com/player/plugins/vast/ | -- | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/plugins/vast/v/8.6.2/vast.js` |
| +23 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/EhsS6g2.js` |
| +23 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/oapxVQ9.js` |
| +23 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/pop.js` |
| +23 |  |  | speedostream.com | 1 | image | `https://s9.speedostream.com/i/01/00001/f8kj1y6wwciw.jpg` |
| +23 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/googima.js` |
| +23 |  |  | speedostream.com | 1 | script | `https://speedostream.com/player8/jwplayer.js` |
| +23 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/EhsS6g2.js` |
| +23 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/jquery.cookie.js` |
| +23 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/xupload.js` |
| +23 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/jquery.min.js` |
| +23 |  |  | speedostream.com | 1 | css | `https://speedostream.com/css/main.css` |
| +23 | no-remote-fonts: * true | -- | speedostream.com | 1 | inline-font | `https://speedostream.com/embed-f8kj1y6wwciw.html` |
| +23 |  |  | speedostream.com | 1 | doc | `https://speedostream.com/embed-f8kj1y6wwciw.html` |
| +1 |  |  | speedostream.com | 1 | image | `https://speedostream.com/images/hr3.gif` |
| +1 |  |  | speedostream.com | 1 | image | `https://speedostream.com/images/flags.png` |
| +1 |  |  | speedostream.com | 1 | image | `https://speedostream.com/images/home.cur` |
| +1 |  |  | speedostream.com | 1 | image | `https://speedostream.com/images/head_bg.jpg` |
| +1 |  |  | speedostream.com | 1 | image | `https://speedostream.com/favicon.ico` |
| +1 |  |  | speedostream.com | 3 | image | `https://imagetot.com/images/2021/02/19/3cdbf71b1bb2525bb79711f377029254.png` |
| +1 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/xupload.js?v=3` |
| +1 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/jquery.min.js` |
| +1 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/modernizr.custom.04022.js` |
| +1 |  |  | speedostream.com | 1 | css | `https://speedostream.com/css/main.css?v=1` |
| +0 | no-remote-fonts: * true | -- | speedostream.com | 1 | inline-font | `https://speedostream.com/` |
| +0 |  |  | speedostream.com | 1 | doc | `https://speedostream.com/` |
| +0 | no-remote-fonts: * true | -- | speedostream.com | 1 | inline-font | `http://speedostream.com/` |
| +0 |  |  | speedostream.com | 1 | doc | `http://speedostream.com/` |
</details>


<details><summary>Logger output Tor-Browser</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +36 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca2svix4lgrpkfo6rzpabq/seg-3-v1-a1.ts` |
| +30 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca2svix4lgrpkfo6rzpabq/seg-2-v1-a1.ts` |
| +22 |  |  | speedostream.com | 1 | image | `https://a.speedostream.com/api/click/9410085905658301079?c=60&data[error]=301` |
| +22 |  |  | speedostream.com | 3 | image | `https://kts.visitstats.com/in/vtcevents/?e_type=Error&source=481355440&tcid=3311&cap=2&other=301%20https://syndication.realsrv.com/splash.php?idzone=3447985&sub=481355440&uid=9e385d34a5b5995b3269b4923302f1ff&ccid=` |
| +17 |  |  | speedostream.com | 3 | xhr | `https://syndication.realsrv.com/splash.php?idzone=3447985&sub=481355440` |
| +16 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca2svix4lgrpkfo6rzpabq/seg-1-v1-a1.ts` |
| +15 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca2svix4lgrpkfo6rzpabq/index-v1-a1.m3u8` |
| +14 |  |  | speedostream.com | 3 | xhr | `https://vast.yomeno.xyz/?tcid=3311` |
| +13 |  |  | speedostream.com | 3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-1333132649&e=ar&n=6601713697123448&abc=0&aid=eGDB2EujEeKZwiIACp8kUw&amp=0&at=1&c=0&ccp=0&cp=0&d=0&eb=0&ed=6&emi=11seea0frhey&gfb=0&gifr=0&gios=0&i=0&lid=khvd971s785t&lsa=read&mt=0&pbd=1&pbr=1&pgi=175ifaz3wkaz&ph=0&pii=0&pl=449&plc=1&pli=oei1331kkf5r&pp=hlsjs&ppm=VOD&prc=1&ps=3&pss=1&pt=&pu=https%3A%2F%2Fspeedostream.com%2Fembed-f8kj1y6wwciw.html&pv=8.9.5&pyc=0&s=1&sdk=0&stc=1&stpe=0&tv=3.26.1&vb=1&vi=1&vl=90&wd=1000&ab=1&abid=z92l9n1oup1c&abo=pre&adi=1ngk3ne1c8np&apid=z92l9n1oup1c&awi=1&awc=1&p=0&pc=0&pi=1&pr=0&vu=&apr=1&rtp=%7B%7D&sa=1614971805200` |
| +13 |  |  | speedostream.com | 1 | xhr | `https://a.speedostream.com/api/spots/288567?s1=%subid1%&kw=` |
| +13 |  |  | speedostream.com | 1 | xhr | `https://s9.speedostream.com/hls/i7dmpqarqxb7o2nqgcsflp44ombvv44cpx4nvqca2,svix4lgrpkfo6rzpabq,53iv4lgrpkeg4ppv5ka,.urlset/master.m3u8?xxx=123` |
| +13 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/api/spots/288568?host=speedostream.com&ev=174&wh=450&ww=1000&s1=%25subid1%25` |
| +12 |  |  | speedostream.com | 3 | xhr | `https://entitlements.jwplayer.com/eGDB2EujEeKZwiIACp8kUw.json` |
| +12 |  |  | speedostream.com | 1 | image | `https://speedostream.com/favicon.ico` |
| +11 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.9.5/provider.hlsjs.js` |
| +11 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.9.5/jwplayer.core.controls.js` |
| +11 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.9.5/jwpsrv.js` |
| +11 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/plugins/vast/v/8.6.2/vast.js` |
| +11 |  |  | speedostream.com | 1 | image | `https://s9.speedostream.com/i/01/00001/f8kj1y6wwciw.jpg` |
| +11 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/api/spots/288569?s1=%25subid1%25` |
| +11 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/oapxVQ9.js` |
| +11 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/pop.js` |
| +11 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/googima.js` |
| +11 |  |  | speedostream.com | 1 | script | `https://speedostream.com/player8/jwplayer.js` |
| +11 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/EhsS6g2.js` |
| +11 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/jquery.cookie.js` |
| +11 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/xupload.js` |
| +11 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/jquery.min.js` |
| +11 |  |  | speedostream.com | 1 | css | `https://speedostream.com/css/main.css` |
| +9 | whitelisted | ++ | speedostream.com | 1 | doc | `https://speedostream.com/embed-f8kj1y6wwciw.html` |
| +8 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/api/spots/288568?host=speedostream.com&ev=174&wh=450&ww=1000&ab=1&s1=%25subid1%25` |
| +7 | ##.adsBox |  | speedostream.com |  | dom | `https://speedostream.com/embed-f8kj1y6wwciw.html` |
| +7 |  |  | speedostream.com | 1 | image | `https://speedostream.com/favicon.ico` |
| +6 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.9.5/provider.hlsjs.js` |
| +6 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.9.5/jwplayer.core.controls.js` |
| +6 |  |  | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/v/8.9.5/jwpsrv.js` |
| +6 | \|\|p.jwpcdn.com/player/plugins/vast/ | -- | speedostream.com | 3 | script | `https://ssl.p.jwpcdn.com/player/plugins/vast/v/8.6.2/vast.js` |
| +6 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/api/spots/288569?s1=%25subid1%25` |
| +2 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/oapxVQ9.js` |
| +2 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/pop.js` |
| +2 |  |  | speedostream.com | 1 | image | `https://s9.speedostream.com/i/01/00001/f8kj1y6wwciw.jpg` |
| +2 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/googima.js` |
| +2 |  |  | speedostream.com | 1 | script | `https://speedostream.com/player8/jwplayer.js` |
| +2 |  |  | speedostream.com | 1 | script | `https://a.speedostream.com/EhsS6g2.js` |
| +2 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/jquery.cookie.js` |
| +2 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/xupload.js` |
| +2 |  |  | speedostream.com | 1 | script | `https://speedostream.com/js/jquery.min.js` |
| +2 |  |  | speedostream.com | 1 | css | `https://speedostream.com/css/main.css` |
| +2 | no-remote-fonts: * true | -- | speedostream.com | 1 | inline-font | `https://speedostream.com/embed-f8kj1y6wwciw.html` |
| +0 |  |  | speedostream.com | 1 | doc | `https://speedostream.com/embed-f8kj1y6wwciw.html` |
</details>

**Comment by ghajini** [comment]
you also test
`https://yomovies.mx/asli-rakhwala-natakam-2021-hindi-dubbed-Watch-online-full-movie/`

**Comment by ghajini** [comment]
@mapx- 
link to test `https://speedostream.com/embed-f8kj1y6wwciw.html`

there's existing rule in ublock list `/api/spots/*&ev$script`
would you modify that rule to address this issue (request to block `https://a.speedostream.com/api/spots/288569?s1=%25subid1%25`)

**Comment by spirillen** [comment]
> you also test
> `https://yomovies.mx/asli-rakhwala-natakam-2021-hindi-dubbed-Watch-online-full-movie/`

Now I have, and found some of those you reffed in first message :+1: 

PS: Thanks for the fix @mapx- :+1:

**Comment by wout-codes** [comment]
@ryanbr Please add this: `/api/spots/*`, as soon as possible, there are a lot of sites using this to display fake notifications and popups.
