### ISSUE TITLE
Elements on psypost.org for Fanboy Social/Annoyance + Cookie

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#7348]
### List the website(s) you're having issues:

`https://www.psypost.org/2021/03/facial-recognition-technology-can-predict-a-persons-political-orientation-with-72-accuracy-59888`

### What happens?

![Screenshot 2021-03-07 141338](https://user-images.githubusercontent.com/11689349/110251650-78288f00-7f4f-11eb-93e1-cd344cbbc9ad.jpg)

![Screenshot 2021-03-07 141430](https://user-images.githubusercontent.com/11689349/110251653-7a8ae900-7f4f-11eb-9ae8-6a52c7d9e22b.jpg)

### List Subscriptions you're using:

Fanboy's Annoyance
uBlock filters - Annoyances
AdGuard Annoyances
AdGuard Social Media

**Comment by ryanbr** [comment]
Install Easylist/Easyprivacy, because I'm not seeing this..

**Comment by yokoffing** [comment]
> 
> 
> Install Easylist/Easyprivacy, because I'm not seeing this..

Of course I use those two lists lol. But since I was seeking these social media widgets and cookie notice, I thought they needed to be added to the Annoyance/Social Media/Cookie lists.

What's weird is that they aren't hiding on Firefox with uBlock Origin. However, I just visited the site in Brave with Fanboy's Annoyance list on using their native blocker, and they're hidden.

Apologies for not testing in another browser first D:
