### ISSUE TITLE
dailymotion.com

### ISSUE THREAD

**Issue by mat41997** [easylist/easylist#735]
![2017-11-26 12_03_03-anime dragon ball super - odcinek 117 - kreskoweczki pl](https://user-images.githubusercontent.com/5884000/33239423-2041b86e-d2a2-11e7-8742-ca909c58c835.png)
`https://www.kreskoweczki.pl/kreskowka/100431/dragon-ball-super_odcinek-117`

https://github.com/jspenguin2017/uBlockProtector/issues/727#issuecomment-347006401

steps to reproduce
- play the video

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.112
chrome 62.0.3202.94

**Comment by SMed79** [comment]
test
```
||dailymotion.com/cdn/$script
```
or
```
||dailymotion.com/cdn/$media,script
```

**Comment by SMed79** [comment]
@mat41997 Did you test the filter above? If so, take the time to share your feedback !!

**Comment by mat41997** [comment]
sorry i don't have easylist.

it's be fixed
works fine on my ubo without easylist.
thanks for the support.
