### ISSUE TITLE
imagefap.com

### ISSUE THREAD

**Issue by thaliel** [easylist/easylist#736]
the "block user" button is being hidden by easylist. 
easylist on [https://screenshots.firefox.com/YuVuxKNZbtDIQaIR/www.imagefap.com](url)

easylist off [https://screenshots.firefox.com/OHQ4PxiiQJCZlUKm/www.imagefap.com](url)

if |http://$script,xmlhttprequest,domain=imagefap.com

ist still part of easylist, it needs to be removed

**Comment by mapx-** [comment]
`@@||imagefap.com/jscripts/blockwidget.js`
