### ISSUE TITLE
boat-lifestyle.com tracking

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7369]
### List the website(s) you're having issues:

`www.boat-lifestyle.com`

### What happens?

Popup, possible tracking not blocked.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.82
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

One tracking script:
```
https://cdn.shopify.com/shopifycloud/media-analytics/v0.1/analytics.js
```

**Comment by ryanbr** [comment]
Looks fine
