### ISSUE TITLE
litebit.eu - Easylist Cookie breaks scrolling

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#7371]
### List the website(s) you're having issues:

`https://www.litebit.eu/`

### What happens?

Easylist Cookie breaks scrolling

### List Subscriptions you're using:

EasyList Cookie

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 86
- Adblock Extension/version: uBlock Origin v1.33.2

### Other details:

I'm not sure what fixing rule would be best so I'm not making a pull req this time.

Possible fixes:
`@@||litebit.eu^$generichide`

or:

`litebit.eu#@#div[class^="cookie-consent_"]`
`litebit.eu#@#.cookie-consent:not(body):not(html)`

I don't know if you are willing to use a generichide rule for Easylist Cookie (probably it's more suitable to ad blocking Easylist?)

If generichide is not being used, then those two rules are needed but the problem is that rules in the Easylist Cookie allowlist are in alphabetical order by the rule part, not by the domain part. So those two rules would have to be pretty far away from each other that would be odd as they are related to same domain.

**Comment by wout-codes** [comment]
@peace2000 Add these:

```
litebit.eu##.modal
litebit.eu#$#body { overflow: visible !important; }
```

**Comment by krystian3w** [comment]
FOP sort list on almost any update in branch: https://github.com/easylist/easylist/tree/gh-pages

**Comment by ryanbr** [comment]
Has been resolved, closing
