### ISSUE TITLE
[NSFW] fucd.pro

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7372]
### List the website(s) you're having issues:

```
https://fucd.pro/category/amateur/
https://fucd.pro/watch/195722/hardcore-sex-in-office-with-big-round-boobs-horny-girl-alexa-pierce-vid-02/
```

### What happens?

Ads placeholders.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.82
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

Proposed filters:
```
fucd.pro##.thumbspot
fucd.pro##.player-place-wide-bn-ob
```

**Comment by yokoffing** [comment]
If you resize the browser window to make it smaller, there's a black box that pops up for me.

![Screenshot 2021-03-21 at 9 24 26 PM](https://user-images.githubusercontent.com/11689349/111929146-ed39af80-8a8b-11eb-80ba-8824c68f1373.jpg)
