### ISSUE TITLE
Fanboy's Annoyance/Social Blocking List latest version broke custom filter rules

### ISSUE THREAD

**Issue by darkmorpher** [easylist/easylist#738]
@Khrin @ryanbr 

like #264, latest **[Fanboy's Annoyance List](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt)** (fanboy-addon lists) suddenly breaks custom filter rules and un-hides them. Also, filters added using Element Hiding Helper Firefox extension doesn't go into effect.
Same problem for [Fanboy's Social Blocking List](https://easylist-downloads.adblockplus.org/fanboy-social.txt)

Disabling this filter solves the issue and everything goes back to normal.

Note: Issue started after sometime after Nov 25

**Comment by ryanbr** [comment]
is there an example test page where it breaks?

**Comment by darkmorpher** [comment]
You can test it on any domain. Fanboy's Annoyance List + add a custom rule/block a page element with Element Hiding Helper Firefox extension and reload page.

ex: http://www.paste.org/p/home

**Comment by ryanbr** [comment]
Can you update the filters/re-test? Does it still happen?

**Comment by darkmorpher** [comment]
Fixed as of version 201712052215

**Comment by darkmorpher** [comment]
Issue reappeared as of [Fanboy's Annoyance List version](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt) **201806032051**

**Comment by ryanbr** [comment]
I couldn't see any issues, I enabled Annoyances, I was able to block/hide afterwards. You need to explain the issue, and a reproducible method, else nothing will be fixed.

**Comment by darkmorpher** [comment]
Fixed as of Fanboy's Annoyance List version **201806042001**

**Comment by darkmorpher** [comment]
This is a weird bug

* Install Fanboy's Annoyance List
* add custom rules/block page elements (ex: http://www.paste.org/p/home) with Element Hiding Helper Firefox extension
* Restart browser
* Hidden elements should now reappear. Disable Fanboy's Annoyance List and reload page. Hidden elements should now be hidden again.
* Re-enable Fanboy's Annoyance List. You won't see any issues with custom rules/hidden page elements anymore. Restarting browser will bring back the bug.
