### ISSUE TITLE
www.youtube.com/watch?v=CnbNXBaPkLc EasyList Annoyances

### ISSUE THREAD

**Issue by romulasry** [easylist/easylist#7381]
### List the website(s) you're having issues:

https://www.droptica.com/

### What happens?

 Cookie settings css popup.

### List Subscriptions you're using:

uBlock filters
28,506 used out of 28,539
uBlock filters – Badware risks
1,326 used out of 1,327
uBlock filters – Privacy
126 used out of 126
uBlock filters – Resource abuse
72 used out of 72
uBlock filters – Unbreak 1,508 used out of 1,508
EasyList 64,964 used out of 65,181
EasyPrivacy 21,936 used out of 22,062
Online Malicious URL Blocklist 8,610 used out of 8,610
Fanboy’s Annoyance 57,436 used out of 57,585
Peter Lowe’s Ad and tracking server list 3,561 used out of 3,562

### Your settings

- OS/version: Linux fedora 5.12.0-0.rc2.165.fc35.x86_64
- Browser/version: Firefox/85.0
- Adblock Extension/version:  Ublock Orgin/1.33.2

**Comment by ryanbr** [comment]
Can't be blocked, as the text behind it will remain blurred still
