### ISSUE TITLE
Adblock nictie on girlscene.nl [EasyList Dutch]

### ISSUE THREAD

**Issue by BPower0036** [easylist/easylist#7383]
### List the website(s) you're having issues:

girlscene.nl

### What happens?

When you open an article on the site, you get on top an adblock notice.

### List Subscriptions you're using:

- EasyList Dutch
- EasyPrivacy,
- AdGuard Base

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

girlscene.nl detects if you use an adblocker.
If you add the following filter to your own filters:
@@||girlscene.nl/templates/base/js/adbanner-dummy.js?$script,domain=girlscene.nl
It is solved

**Comment by ryanbr** [comment]
We wouldn't include it into EL, just add it to you personal list.
