### ISSUE TITLE
YouTube banner ads and video ad placeholders starting to slip through

### ISSUE THREAD

**Issue by enlightenedliberal1** [easylist/easylist#7388]
Using GNOME Web 3.38.2, using filter list `https://easylist-downloads.adblockplus.org/easylist_min_content_blocker.json`

Recently, YouTube seems to have updated so that I am now seeing the banner ads display over videos. I am also repeatedly shown the ad countdown and taken to the video ad (which simply shows a blank white screen with no audio) with a button to skip the ad.

**Comment by ryanbr** [comment]
The youtube video ads are fixed via snippets, so not fixable via json sorry @enlightenedliberal1

**Comment by mcatanzaro** [comment]
It's no longer blocking any ads on youtube.com, see https://gitlab.gnome.org/GNOME/epiphany/-/issues/1534. I'm particularly impressed that it inserts ads at seemingly-random points in the *middle* of videos.

> The youtube video ads are fixed via snippets, so not fixable via json sorry

Hi, can you point me to where the snippets live please? I assume that's just some custom JS? We can add that easily enough, I'm just having trouble finding it.

**Comment by theolice** [comment]
![image](https://user-images.githubusercontent.com/4408879/119709461-8656bf00-be5d-11eb-8ab8-1cf23a6f166e.png)
 Here is an example of it currently blocking my ads, mostly at the start of videos.

**Comment by mcatanzaro** [comment]
@ryanbr if you know where these "snippets" live, that would be *very* helpful. I have failed to find them anywhere in easylist git repo. Thanks.

**Comment by ryanbr** [comment]
Snippets are in https://github.com/abp-filters/abp-filters-anti-cv/blob/master/english.txt#L354

We don't include snippets in EL directly.

**Comment by llacb47** [comment]
> @ryanbr if you know where these "snippets" live, that would be _very_ helpful. I have failed to find them anywhere in easylist git repo. Thanks.

https://gitlab.com/eyeo/adblockplus/adblockpluscore/-/blob/master/lib/content/snippets.js#L1325
https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js#L375

**Comment by mcatanzaro** [comment]
Thanks!
