### ISSUE TITLE
[NSFW] freeuseporn.com

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7395]
### List the website(s) you're having issues:

```
https://www.freeuseporn.com
https://www.freeuseporn.com/video/3954/mind-control-bimbos
```

### What happens?

Sponsored videos.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.82
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

Proposed filters:
```
freeuseporn.com##.col-md-2:has(.quality:has-text(/SPONSOR/))
freeuseporn.com##.col-md-2:first-child:has(.embed)
```

**Comment by Yuki2718** [comment]
Click the video and you'll get popup.
`||freeuseporn.com/templates/frontend/fulltheme/js/backdrop.js`

**Comment by cantunborn** [comment]
Update:
```
www.freeuseporn.com##.player-ad-bottom
```
