### ISSUE TITLE
in.mashable.com

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7398]
### List the website(s) you're having issues:

```
https://in.mashable.com/
https://in.mashable.com/entertainment/20829/wandavision-creator-jac-schaeffer-on-grief-fietro-and-everything-else-that-isnt-mephisto
```

### What happens?

Ad placeholders.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.82
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

Proposed filters:
```
mashable.com##.zad
```

OR

```
mashable.com##.zad.halfpage
mashable.com##.zad.mrec
```

**Comment by stephenhawk8054** [comment]
There're ads placeholders.

URL: `https://mashable.com/`

Firefox 94.0.1, ublock 1.38.6 default

Proposed filter:

`mashable.com##[data-pogo]`

**Comment by stephenhawk8054** [comment]
<details>
<summary>Screenshot</summary>

![Screenshot 2021-11-16 at 08-57-49 Mashable](https://user-images.githubusercontent.com/66517106/141881916-a4d9b7a3-3c3e-44b1-9a08-50761c4c1635.png)

</details>
