### ISSUE TITLE
ifunny.co mobile app promo

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7401]
### List the website(s) you're having issues:

```
https://ifunny.co/picture/hows-it-hangin-OWoo0ICR8?gallery=featured
```

### What happens?

Mobile app promo.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.82 (Responsive mode developer tools)
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

Proposed filters:
```
ifunny.co##.promo-popup
ifunny.co##body:style(overflow: auto !important)
```

**Comment by ryanbr** [comment]
This will need to be submited too https://github.com/uBlockOrigin/uAssets/issues   (in annoyances). @cantunborn
