### ISSUE TITLE
theverge.com - Cookie notice is visible

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#7402]
### List the website(s) you're having issues:
- `https://www.theverge.com/`

### What happens?
On visiting the website, the cookie notice popup is not blocked

### List Subscriptions you're using:
- Easylist Cookie List (Updated: 2021-03-12 10:00 UTC)

### Your settings

- OS/version: MacOS/10.15.7
- Browser/version: Chrome/88.0.4324.182
- Adblock Extension/version: 3.10.2

### Other details:

![image](https://user-images.githubusercontent.com/2988929/110922515-72082900-8328-11eb-9748-8a0f4c695896.png)

**Comment by ryanbr** [comment]
Can't be blocked without breaking the site. https://github.com/easylist/easylist/issues/3729

@alexm92
