### ISSUE TITLE
nexusradio.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7412]
### List the website(s) you're having issues:

`http://www.nexusradio.com/download.php`

### What happens?

Placeholder box.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/111044849-4598fd80-844b-11eb-93b4-dfe9777b858a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 89.0.4389.90 x64
- Adblock Extension/version: uBO 1.34.1b1 + IDCAC 3.2.9

### Other details:

I propose `nexusradio.com##div[align=center]`

![image](https://user-images.githubusercontent.com/22780683/111045076-7cbbde80-844c-11eb-88c9-b5952c5839ba.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/2baf27d2dda908bbdc7c454f3e3753bf8875ddbd
