### ISSUE TITLE
pureinfotech.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7413]
### List the website(s) you're having issues:

`https://pureinfotech.com/windows-10-21h1-new-features/`

### What happens?

Various medium-size placeholders (3~4 in the example link).

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/111044849-4598fd80-844b-11eb-93b4-dfe9777b858a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 89.0.4389.90 x64
- Adblock Extension/version: uBO 1.34.1b1 + IDCAC 3.2.9

### Other details:

I propose `pureinfotech.com##.code-block`

![image](https://user-images.githubusercontent.com/22780683/111047080-35821d80-844d-11eb-8cd5-2ef1977f1090.png)

**Comment by ryanbr** [comment]
Too minor.
