### ISSUE TITLE
tecadmin.net

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7418]
### List the website(s) you're having issues:

`https://tecadmin.net/setup-x11vnc-server-on-ubuntu-linuxmint/`

### What happens?

Two placeholder bars on the right.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/111044849-4598fd80-844b-11eb-93b4-dfe9777b858a.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 89.0.4389.90 x64
- Adblock Extension/version: uBO 1.34.1b1 + IDCAC 3.2.9

### Other details:

I propose `tecadmin.net##.widget_custom_html`

![image](https://user-images.githubusercontent.com/22780683/111051218-b6dbaf00-8451-11eb-8e9c-b92972302f02.png)

**Comment by ryanbr** [comment]
I'm fine leaving this.
