### ISSUE TITLE
howsecureismypassword.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#7422]
### List the website(s) you're having issues:

`https://howsecureismypassword.net/`

### What happens?

Ad picture
<img width="725" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/111066959-107bc200-84c2-11eb-8fed-f321339b2b6d.PNG">

### List Subscriptions you're using:

EasyList, EasyList Germany, EasyPrivacy

### Your settings

- OS/version: Win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin v1.33.2

**Comment by spirillen** [comment]
I'll suggest the following rules:

```
! 2021-03-14 https://howsecureismypassword.net
||howsecureismypassword.net/general-*.png$image,important
howsecureismypassword.net##.top-banner
```

The first rule will prevent a call to `xvbelink.com` ([T4347](https://www.mypdns.org/T4347))
The second rule will prevent the ad zone from appering.
