### ISSUE TITLE
[NSFW] totsantcugat.info

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7429]
### List the website(s) you're having issues:

```
http://totsantcugat.info
http://totsantcugat.info/reality/sexy-college-girls-blog.html
```

### What happens?

Ads

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.90
- Adblock Extension/version: uBlock Origin 1.33.2

**Comment by Yuki2718** [comment]
Indeed very excessive.

**Comment by ryanbr** [comment]
The best I can do. its bascially an Advert site. I'm sure there are better porn sites than this.
