### ISSUE TITLE
Consider adding the Adguard CNAME tracker list (if not already added)

### ISSUE THREAD

**Issue by Noexpert** [easylist/easylist#7432]
As above, would be great if this https://github.com/AdguardTeam/cname-trackers could be incorporated, assuming it's not already part of easylist.

**Comment by Yuki2718** [comment]
All necessary filters are already added, actually EL author was the first one contacted by AdGuard.

**Comment by Khrin** [comment]
It's already included in EasyPrivacy: https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_specific_cname.txt
