### ISSUE TITLE
timesnownews.com mobile site

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7439]
### List the website(s) you're having issues:

```
https://www.timesnownews.com/
https://www.timesnownews.com/sports/cricket/article/indias-remaining-t20is-against-england-to-be-played-behind-closed-doors-gca-to-refund-spectators/732828
```

### What happens?

- Ad placeholders
- Bottom sticky leftover

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.90 (Responsive mode developer tools)
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

Proposed filters:
```
! Ad placeoholders
timesnownews.com##.tncls_ad_250, .tncls_ad_300, .tncls_taboola

! Bottom sticky
timesnownews.com##.adparent
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/14e7a8cdf664352b3f0a358305ad27390b441c02
