### ISSUE TITLE
businessinsider.in mobile site

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7450]
### List the website(s) you're having issues:

```
https://www.businessinsider.in/
https://www.businessinsider.in/tech/news/tesla-failed-to-appoint-a-lawyer-who-could-stop-elon-musks-erratic-tweets-a-lawsuit-filed-by-an-investor-alleges/articleshow/81570522.cms
```

### What happens?

Ad placeholders.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.90 (Responsive mode developer tools)
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

Proposed filters:
```
businessinsider.in##.ad-brdr-btm, .article-ad-container
businessinsider.in##.leaderboard-scrollable-cont, .leaderboard-scrollable-btf-cont
businessinsider.in##.mrec-atf-sticky, .mrec-btf-cont, .mrec-scrollable-cont, .mrec-hp-scrollable-cont
```

**Comment by ghajini** [comment]
adguard mobile ads filters are part of default setup, why exclude that by the way?

**Comment by cantunborn** [comment]
> `adguard mobile ads filters` are part of default setup in ubo, why exclude that by the way?

Yeah, makes sense for mobile. I'll recheck with the filter enabled.
