### ISSUE TITLE
tuasaude.com

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7453]
### List the website(s) you're having issues:

```
https://www.tuasaude.com/
```

### What happens?

Ad placeholder.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.90
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

Proposed filters:
```
tuasaude.com###footerWidgets:has(#adContainer)
```

**Comment by ryanbr** [comment]
Added to Easylist Cookie, but non-english site won't be added.
