### ISSUE TITLE
AdGuard Icon not shown @ oisd blocklist download page

### ISSUE THREAD

**Issue by sjhgvr** [easylist/easylist#7460]
Icon: https://oisd.nl/icons/adguard.gif
Not displayed on page: https://oisd.nl/?p=dl
Because of rule: /adguard.$domain=~adguard-com.cdn.ampproject.org|~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com|~marketplace.visualstudio.com

**Comment by ryanbr** [comment]
Removed filter.
