### ISSUE TITLE
[NSFW] oldies.name

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7461]
### List the website(s) you're having issues:

```
https://www.oldies.name
https://www.oldies.name/vids/young-amp-beautiful-95945.html
```

### What happens?

Ads.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.90
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

Proposed filters:
```
||oldies.name/ok/ok.js$script,domain=oldies.name
oldies.name##.im_adv, .spots_right, .pl_adv
```

**Comment by Yuki2718** [comment]
I see `oldies.name/ok/ok.js` but not `.php`.

**Comment by cantunborn** [comment]
Fixed. Filter changed as I added long time ago.
