### ISSUE TITLE
[NSFW] milkporntube.com mobile site

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7462]
### List the website(s) you're having issues:

```
https://milkporntube.com
https://milkporntube.com/gorgeous-lactating-lesbian-adult-breastfeeding/
```

### What happens?

Ads.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.90 (Responsive mode developer tools)
- Adblock Extension/version: uBlock Origin 1.33.2

### Other details:

Proposed filters:
```
milkporntube.com##.happy-header-mobile, .happy-under-player, .happy-related-videos-mobile
```

**Comment by Yuki2718** [comment]
Also is another case of optscript popup.

**Comment by Yuki2718** [comment]
@ryanbr `||milkygoodness.xyz^` breaks the video, it needs to be reverted.
