### ISSUE TITLE
[s.to / voe.sx] Popups on mousedown event.

### ISSUE THREAD

**Issue by gettysburg** [easylist/easylist#7475]
### List the website(s) you're having issues:

```
https://s.to/serie/stream/the-wire/staffel-1/episode-1
https://voe.sx/q9w9546rfkq6
```

### What happens?

After completing the ReCaptcha verification on s.to, clicking the play button from the voe.sx player opens one of the following sites - the same happens if visiting voe.sx directly:

```
3r1kwxcd.top
onlinetopchoice.com
```

If not blocked, they tend redirect to this page but I'm unsure if etoro is the only company they are distributing ads for:

`etoro.com`

This repeats for 2 more times, so on initial page load, you have to click the play/pause button 3 times in order to be able to play and pause the video without getting any more popups - they also have a JavaScript timer somewhere which re-enables the "open popup on play/pause button click" functionality every once in a while, but only for one mousedown event, not 3 like before.

_I noticed this also sometimes happens when just clicking anywhere on the s.to page, so they both run the same ad code / use the same ad distribution network, it seems._

### List Subscriptions you're using:

Every single one available in the latest developer build of uBlock Origin, except for the region-related ones, where I only enable EasyList Germany.

![image](https://user-images.githubusercontent.com/2256003/111997609-20735180-8b13-11eb-845e-362d2981e291.png)

### Your settings

- OS/version: Windows Server 2019 LTSC / 1809 17763.1817
- Browser/version: Firefox 86.0.1
- Adblock Extension/version: uBlock Origin 1.34.1b2
- Additional Extensions: HTTPS Everywhere in _blocking_ mode

Noteworthy browser settings:

```
javascript.options.asmjs = false
javascript.options.baselinejit = false
javascript.options.ion = false
javascript.options.native_regexp = false
javascript.options.warp = false
javascript.options.wasm = false

privacy.resistFingerprinting = true
privacy.firstparty.isolate = true
privacy.firstparty.isolate.block_post_message = true
```

.. and many more security / hardening related changes, Firefox' built in "Enhanced Tracking Protection" is set to 'Strict' as well.

### Other details:

I just manually blocked the two popup domains and etoro, but I suppose the more elegant way would be to prevent the relevant ad code from running at all.

```
! 2021-03-12 http://3r1kwxcd.top
3r1kwxcd.top

! 2021-03-12 http://onlinetopchoice.com
onlinetopchoice.com

! 2021-03-12 http://etoro.com
etoro.com
```

**Comment by ghajini** [comment]
test on default settings & after that ,force update all default filters,it is fixed today only

**Comment by gettysburg** [comment]
@ghajini:

Hi,

I've removed all my custom filters, purged caches and ran an update for all enabled filters.

Embedded voe.sx streams now play _without_ pop-ups or advertisements, clicking "Beschreibung anzeigen" (German for "Show description") or blank spots on the site _no longer_ triggers them as well.

However, pop-ups still occasionally happen on their alternative domains, one of them being serien.sx - they own a bunch of domains in order to offer users a way to circumvent DNS censorship in use by German ISP's (and those foolish enough to use their ISP's DNS servers..).

Here is a complete list:

```
Serien.sx
S.to
SerienStream.sx
SerienStream.to
```

Kudos to those involved, seems like we are making some progress :-)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/deee5680b654336bbe11ea5127e35f23421208ac
