### ISSUE TITLE
maharashtratimes.com

### ISSUE THREAD

**Issue by ghajini** [easylist/easylist#7478]
### List the website(s) you're having issues:

`maharashtratimes.com`

### What happens?

A) videos don't load

B) a samsung ad rather promotion(just like amazon does on other websites) on every toi/indiatimes network sites (reported here https://github.com/AdguardTeam/AdguardFilters/issues/75125#issuecomment-780435644) 

### How to reproduce=
A)
1. visit `maharashtratimes.com`

2. then scroll down until you see this
![Screenshot (253)](https://user-images.githubusercontent.com/20338483/112024994-bd0d1200-8b5a-11eb-82a7-64d676d7ac45.png)

3.click on any video eg 1st one

4.them in next ,video doesn't load ,never ending loading
![Screenshot (252)](https://user-images.githubusercontent.com/20338483/112025237-fc3b6300-8b5a-11eb-95a1-8e135ec22272.png)

B)
a samsung video ad 
![Screenshot (251)](https://user-images.githubusercontent.com/20338483/112026195-f2fec600-8b5b-11eb-865f-1f8cbecf3df6.png)

### List Subscriptions you're using:

ublock origin default lists

### Your settings

- OS/version: win10
- Browser/version: opera browser stable
- Adblock Extension/version: 1.34.1b2

### Other details:

These work
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=maharashtratimes.com
||static.*.indiatimes.com/32.0f3fba09f3e524f8c072.js$script,domain=maharashtratimes.com
```

**Comment by ryanbr** [comment]
Won't fix the advert (non-english site)

But will fix the playback.

**Comment by ghajini** [comment]
A) Regarding video blockage these are also affected domains(belonging to same indiatimes/toi group)
```
navbharattimes.indiatimes.com
eisamay.indiatimes.com
www.iamgujarat.com
vijaykarnataka.com
tamil.samayam.com
telugu.samayam.com
malayalam.samayam.com
```
so exception filter is required 
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=navbharattimes.indiatimes.com|eisamay.indiatimes.com|iamgujarat.com|vijaykarnataka.com|tamil.samayam.com|telugu.samayam.com|malayalam.samayam.com`

B) regarding ad /promotion

this is present on 
```
https://vijaykarnataka.com/
https://telugu.samayam.com/
https://malayalam.samayam.com/
https://tamil.samayam.com/
https://eisamay.indiatimes.com
https://navbharattimes.indiatimes.com/
https://maharashtratimes.com
```
This work

`vijaykarnataka.com,telugu.samayam.com,malayalam.samayam.com,tamil.samayam.com,eisamay.indiatimes.com,navbharattimes.indiatimes.com,maharashtratimes.com##.minitv-container`

so whoever wants to address @ uassets or @ adguard

**Comment by whyiswhen** [comment]
> Won't fix the advert (non-english site)

@ryanbr  this is an indian site . please make indian list .

**Comment by whyiswhen** [comment]
> > Won't fix the advert (non-english site)
> 
> @ryanbr this is an indian site . please make indian language specific filter list .
