### ISSUE TITLE
elvenar.com

### ISSUE THREAD

**Issue by sol23** [easylist/easylist#7480]
Hello everyone,
the website `elvenar.com` is the main landing page of the browser game "Elvenar" and is currently listed on easylist.
As a result, the page cannot be opened in a pop-up anymore.

### List the website(s) you're having issues:
`||elvenar.com^*?ref=$popup`

### What happens?
The `||elvenar.com^*?ref=$popup` entry is blocking our game to be able to open in a popup. 
We use this on our other game pages to give players the possibility to find an enjoy more gaming opportunities from Innogames. This entry point to the game for new and existing players is designed to provide a positive user experience/journey. 

Since this entry has been on easylist already quite some time (https://github.com/easylist/easylist/pull/3633), 
and during this time we took measures to remove advertising partners which are misusing this, 
we ask you kindly to reconsider and remove the entry again from easylist.

Thank you very much in advance.

**Comment by ryanbr** [comment]
Filter has been removed, if we find any use of popups it'll be re-added to the list (and not removed).

**Comment by sol23** [comment]
Thank you so much for this fast action. And I appreciate the warning ;) 
I hope as well that we identified all of our marketing partners that caused this to show up here in the first place.
