### ISSUE TITLE
[NSFW] watchmygf.tv

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7488]
### List the website(s) you're having issues:

```
https://watchmygf.tv/videos_25670.html
```

### What happens?

Ads and popunder.

### List Subscriptions you're using:

All uBO lists except regional.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.90
- Adblock Extension/version: uBlock Origin 1.34.0

### Other details:

Proposed filters:
```
||watchmygf.tv/js/v.js
watchmygf.tv##.video-aside-spot, .bottoms-spots-section
```

**Comment by stephenhawk8054** [comment]
There's a placeholder at the right.

URL: `https://www.watchmygf.me/video/stunning-candy-sonam-and-alice.html`

[NSFW screenshot](https://i.imgur.com/kqoRuci.png)

Firefox 94.0.1, ublock 1.38.6

Proposed filter:

`watchmygf.me##.second.col-video`
