### ISSUE TITLE
file-converter-online.com

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7491]
### List the website(s) you're having issues:

```
https://file-converter-online.com/
```

### What happens?

Ad placeholder and analytics.

### List Subscriptions you're using:

All uBO lists except regional.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.90
- Adblock Extension/version: uBlock Origin 1.34.0

### Other details:

Proposed filters:
```
||online-umwandeln.de/analytics.js$script
file-converter-online.com##.alignright:has(.adsbygoogle)
```

**Comment by spirillen** [comment]
Do to my currently limited connection, I'll post it here.

I believe we should add this rules in the cookie hide list.

`file-converter-online.com##.cc_banner-wrapper`
