### ISSUE TITLE
advertising.boardgamegeek.com

### ISSUE THREAD

**Issue by karptonite** [easylist/easylist#7494]
### List the website(s) you're having issues:
`advertising.boardgamegeek.com`

### What happens?
All of the CSS is blocked. Probably other resources as well.

### List Subscriptions you're using:

Only Easylist

### Your settings

- OS/version: MacOS 10.15.7
- Browser/version: Chrome  89.0.4389.90
- Adblock Extension/version: 4.30.0

### Other details:

Obviously the problem here is the name of the domain. This is a Wordpress site that board game publishers use to learn about advertising option and to create ads for BoardGameGeek. There are no actual ads on `advertising.boardgamegeek.com`.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8f80d69b7f5f3d27766545bdce56fdf75d35fb9d
