### ISSUE TITLE
ww2.fmovies.cab needs cosmetic filters (Annoyance)

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#7495]
### List the website(s) you're having issues:

Example: `https://ww2.fmovies.cab/tv-series/real-time-with-bill-maher-season-19/hspI6Dlv/OAFZWtHR/5cGSHZjD-watching.html`

**Annoyances:**

- Two banners at the top
- The left and right pop-ups
- Feedback button in the bottom-left corner (AdGuard Annoyances manages to hide this by using `fmovies.cab##.feedback-icon`, but I'd rather not rely on this list and incorporate the filter into Fanboy)

### What happens?

Before:

![Screenshot 2021-03-24 163608](https://user-images.githubusercontent.com/11689349/112380113-5e14dd80-8cbf-11eb-9632-84b104f26c17.jpg)

After:

![Screenshot 2021-03-24 163942](https://user-images.githubusercontent.com/11689349/112380258-91576c80-8cbf-11eb-879f-0cb76356437e.jpg)

### List Subscriptions you're using:

![Screenshot 2021-03-24 164710](https://user-images.githubusercontent.com/11689349/112381137-9bc63600-8cc0-11eb-9063-dc4a3be1e642.jpg)

### Your settings

Proposed filters:

```
ww2.fmovies.cab##div.hotMsg.notice.alert-special.alert:nth-of-type(1)
ww2.fmovies.cab##div.hotMsg.notice.alert-special.alert:nth-of-type(3)
ww2.fmovies.cab##.bs-popover-bottom.show.fade.popover
ww2.fmovies.cab##.show.bs-popover-top.fade.popover
fmovies.cab##.feedback-icon
```

**Comment by krystian3w** [comment]
Can be possible omit `:nth-of-type(1)` / `:nth-of-type(3)` and classes `.show`?

**Comment by yokoffing** [comment]
> Can be possible omit `:nth-of-type(1)` / `:nth-of-type(3)` and classes `.show`?

These are just what work using uBlock Origin’s element picker. I’m sure there are more technical/polished filters to use.

**Comment by spirillen** [comment]
Replace them with

`fmovies.cab##.alert-special` it's working for me

Complete suggestion for rules

```
fmovies.cab##.alert-special
fmovies.cab##.popover
fmovies.cab##.feedback-icon
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/112556193-f0090d00-8dc9-11eb-8544-0e5212dc3845.png)

</details>

**Comment by yokoffing** [comment]
Looks good to me

**Comment by yokoffing** [comment]
Is there a reason we're waiting to add to Fanboy Annoyance?

**Comment by krystian3w** [comment]
Private life of maintainers or EasyPrivacy / EasyList need more time to updating so no enough to fastly close issues about "Fanoby's Annoyances".
