### ISSUE TITLE
imgur.com

### ISSUE THREAD

**Issue by Vitalik93** [easylist/easylist#7496]
### List the website(s) you're having issues:

https://imgur.com/

### What happens?

2 ads at this site - "imgur emerald" and privacy notification.

### List Subscriptions you're using:

all uBlock filters, EasyList, Ru Adlist, RU AdList: BitBlock + Fanboy's General, RU AdList: Counters

### Your settings: 

- OS/version: Windows 10 20H2
- Browser/version: Firefox 87.0
- Adblock Extension/version: uBlock Origin 1.34.0

### Other details:

![изображение](https://user-images.githubusercontent.com/34383288/112385729-a13f7280-8cf8-11eb-9974-802dcde1d12c.png)
![изображение](https://user-images.githubusercontent.com/34383288/112385787-b1575200-8cf8-11eb-9f43-6d519cda92c3.png)

**Comment by mahathu** [comment]
I'm using easylist Ads/easylist Cookies and easylist privacies. I get the imgur Emerald banner but no privacy popup (tested in incognito). `.EmeraldBanner` is a possible CSS selector for the banner.

**Comment by Vitalik93** [comment]
> 
> 
> I'm using easylists ads, cookies and privacy. I get the imgur Emerald banner but no privacy popup (tested in incognito). `imgur.com##.EmeraldBanner` is a filter for the banner.

Could these filters (for both ads) be added to Fanboy's or EasyList?

**Comment by mahathu** [comment]
Added a [pull request](https://github.com/easylist/easylist/pull/7497/commits/c69b91b9ee91e70be92061489aa75695da6210ed)

**Comment by ryanbr** [comment]
I didn't see it, Install Fanboy Annoyances and report back @Vitalik93
