### ISSUE TITLE
[NSFW] cliphunter.com mobile site

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7505]
### List the website(s) you're having issues:

```
https://cliphunter.com
```

### What happens?

Popup.

### List Subscriptions you're using:

All uBO lists except regional.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.90 (Responsive mode developer tools)
- Adblock Extension/version: uBlock Origin 1.34.0

### Other details:

Proposed filters:
```
/mobilepop?
```

**Comment by ryanbr** [comment]
Not used, no popup seen and no url posted.

**Comment by cantunborn** [comment]
@ryanbr 

Click on any video on homepage, if using mobile site `/mobilepop?` request is made. Popup does NOT appear on desktop.
