### ISSUE TITLE
gjensidige.lv

### ISSUE THREAD

**Issue by anonymous74100** [easylist/easylist#752]
`https://www.gjensidige.lv/atlidzibas`

 Insurance claim reporting doesn't work. The form to input data doesn't load.

The script filename has changed:
`https://www.gjensidige.lv/Content/dev/scripts/analytics.min.js`

Change current whitelist in **EasyPrivacy** from:
```
@@||gjensidige.lv/Content/dev/scripts/analytics.js
```
to
```
@@||gjensidige.lv/Content/dev/scripts/analytics$script
```

**Comment by Khrin** [comment]
Fixed https://github.com/easylist/easylist/commit/5b8f66ae790fa8405d949a3d5c26d597dc8c90ce
