### ISSUE TITLE
ciiima.com is not an ad agency or serves anti block ads

### ISSUE THREAD

**Issue by thatMohamed** [easylist/easylist#7521]
Hi
I think ciiima.com in the easylist by mistake, this is the second time one of my domains find its way to the easylist.
Ciiima.com is NOT an ad agency, we DO NOT serve anti block ads or cods
Again, we don't serve any anti block ads or anything, we are working with propellerads, like many others, for years and they are very reputable ad agency that don't serve any malicious content.

please review ciiima.com and remove it.

**Comment by spirillen** [comment]
Rather difficult to check the domain as it is blocked by it's spyware

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | ##.cookie-warning |  | `www.ciiima.com` |  | dom | `https://www.ciiima.com/` |
| +2 | /cdn-cgi/images/trace/*$important | -- | `www.ciiima.com` | 1 | image | `https://www.ciiima.com/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=636ae21faf0c4c0d` |
| +2 | /cdn-cgi/challenge-platform/*$script,important | -- | `www.ciiima.com` | 1 | script | `https://www.ciiima.com/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1` |
| +2 | /cdn-cgi/images/trace/*$important | -- | `www.ciiima.com` | 1 | image | `https://www.ciiima.com/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=636ae21faf0c4c0d` |
| +1 | no-remote-fonts: * true | -- | `www.ciiima.com` | 1 | inline-font | `https://www.ciiima.com/` |
| +1 | no-remote-fonts: * true | -- | ciiima.com | 1 | inline-font | `http://ciiima.com/` |
</details>

**Comment by thatMohamed** [comment]
Thank you for replying. these files are attributed to Cloudflare DDoS protection/Anti DDoS, its NOT a spyware I assure you, Please take a good lock at: this [repository](https://github.com/scaredos/cfresearch#js-challenge)

**Comment by thatMohamed** [comment]
Also let me analysis the logger output:

`##.cookie-warning` is a an under developing attempt to be GDPR complaint, read about it [here](https://www.cookiebot.com/en/cookie-banner/)
`no-remote-fonts: * true` this is to gain some speed and lower the page load time a bit: please read about it [here](https://collinmbarrett.com/block-web-fonts/)
`/cdn-cgi/images/trace/*$important` file: `cdn-cgi/images/trace/jschal/nojs/transparent.gif` is mentioned is this [issue](https://github.com/mikf/gallery-dl/issues/868) and caused a prolem and here is the [explanation](https://github.com/mikf/gallery-dl/issues/868#issuecomment-656354345)
as for `/cdn-cgi/challenge-platform/*$script,important` please check my previous comment

**Comment by thatMohamed** [comment]
Last thing to be crystal clear, aside from google analytics and displaying ads from propellerads, we DO NOT track our visitors by any means, we DO NOT use any malicious code/content/js scripts.

**Comment by thatMohamed** [comment]
Still waiting for a verdict guys.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/69d02274caa355f01cf94c2800b725df841f6ec6
