### ISSUE TITLE
[s.to / voe.sx] Popups on mousedown event (#2).

### ISSUE THREAD

**Issue by gettysburg** [easylist/easylist#7527]
### List the website(s) you're having issues:

`https://s.to/serie/stream/the-walking-dead/staffel-10/episode-21`

### What happens?

After completing the ReCaptcha verification on s.to, clicking the play button from the voe.sx player opens one of the following sites - the same happens if visiting voe.sx directly, however this is not possible to recreate right now as the video was uploaded with the "play-as-embed-only" flag set.
```
https://med.etoro.com/B13971_A96040_TClick_SSTER_DREGW_15806805.aspx
https://www.onlinetopchoice.com/p500_webtrader_real_de.html?zoneid=ster-de-15806805
https://comfortlessweave.com/bcbmixj4p3?key=0f22c1fd609f13cb7947c8cabfe1a90d&submetric=15806805
https://comfortlessweave.com/bcbmixj4p3?ad_c_ref=8441ea559a163ee8436b05&publisher_code=b06a36929e81&c_id=ead237d5252f2939e52a447&ad_code=fa21e3e69507&key=5690c2107417876c302ab06a36929e81&mode=m
https://comfortlessweave.com/bcbmixj4p3?ad_c_ref=2a87c3103ec820b254b07070c9113c1d&publisher_code=b4cf4afe739e52092&c_id=d9446be4c9047fccc9218e85039&ad_code=b057b9e921f35&key=5690c2107417876c302ab06a36929e81&mode=m
```

On initial page load, you have to click the play/pause button 3 times in order to be able to play and pause the video without getting any more popups - they also have a JavaScript timer somewhere which re-enables the "open popup on play/pause button click" functionality every once in a while, but only for one mousedown event, not 3 like before.

### List Subscriptions you're using:

Every single one available in the latest developer build of uBlock Origin, except for the region-related ones, where I only enable EasyList Germany.

![subscriptions](https://user-images.githubusercontent.com/2256003/112754869-af79e100-8fcd-11eb-9e85-012c76336e44.png)

### Your settings

- OS/version: Windows Server 2019 LTSC / 1809 17763.1817
- Browser/version: Firefox 87.0 (64-bit)
- Adblock Extension/version: uBlock Origin 1.34.1b2
- Additional Extensions: HTTPS Everywhere in blocking mode

Noteworthy browser settings:

```
javascript.options.asmjs = false
javascript.options.baselinejit = false
javascript.options.ion = false
javascript.options.native_regexp = false
javascript.options.warp = false
javascript.options.wasm = false

privacy.resistFingerprinting = true
privacy.firstparty.isolate = true
privacy.firstparty.isolate.block_post_message = true
```

.. and many more security / hardening related changes, Firefox' built in "Enhanced Tracking Protection" is set to 'Strict' as well.

### Other details:

This would be the second time they are trying to get around filter lists, looks like they are pretty upset but I will not stop until all ads are removed from that website.

**Comment by cantunborn** [comment]
Fixed here https://github.com/uBlockOrigin/uAssets/commit/2aee5bc892bb8e1d8e8023c07ce12876b0cc3349

**Comment by gettysburg** [comment]
Seems like it's fixed for now, but knowing s.to / voe.sx, they will add a bypass soon.. :-(
