### ISSUE TITLE
wrong block #7271699

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#7531]
https://github.com/easylist/easylist/issues/7457#issuecomment-808916011

It seems that it might break the webpage. @ryanbr

pls undo https://github.com/easylist/easylist/commit/727169936c931b41ef451172b6c4fa5afe13d267 and add:
`/mooc/controllers/course_ajax.php?actype=end`, `/mooc/controllers/course_ajax.php?actype=start`

and also block this too?:
`/mooc/controllers/course_ajax.php` and it must be from here(referer): `/learn/path/download_preview.php`

@easylist @Khrin

**Comment by ryanbr** [comment]
Removed, and not taking these suggestions.

**Comment by c2xusnpq6** [comment]
> Removed, and not taking these suggestions.

why not? =3=

**Comment by c2xusnpq6** [comment]
`/mooc/controllers/course_ajax.php?actype=end`, `/mooc/controllers/course_ajax.php?actype=start` ?
