### ISSUE TITLE
easylist cookie can't be updated

### ISSUE THREAD

**Issue by exodius48** [easylist/easylist#7543]
### What happens?

![2021-03-31_073258](https://user-images.githubusercontent.com/9832875/113073539-77ec7e00-91f3-11eb-9cbe-0efa2a864208.png)

### Your settings

- OS/version: Windows 10 20H2 X64
- Browser/version: FF 87.0
- Adblock Extension/version: uBlock Origin 1.34.0

**Comment by ryanbr** [comment]
Thanks, its a cloudflare issue, have logged an issue. hopefully it should return back to normal soon.
