### ISSUE TITLE
Q - What is the recommended way to block items in HTML email?

### ISSUE THREAD

**Issue by MarkSRobinson** [easylist/easylist#7546]
You might have heard of gem.com, which is some recruiting tooling.  What they do is embed tracking pixels in email and use tracking links in their emails.

I've got some filters that will block the pixel and strip the links out but I'm not sure they're correct for inclusion into EasyPrivacy.  Is this acceptable or is there a better way to do this?

```
##[href*="gem.com/api/click/"]
##[src*="gem.com/api/o/"]

```

**Comment by krystian3w** [comment]
Better block load domain:

`||gem.com^$image,third-party`
