### ISSUE TITLE
creately.com

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7548]
### List the website(s) you're having issues:

`https://creately.com/`

### What happens?

Analytics.

### List Subscriptions you're using:

All uBO lists except regional and adguard mobile ads.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Chrome 89.0.4389.114
- Adblock Extension/version: uBlock Origin 1.34.0

### Other details:

Tracking script:
```
​https://creately.com/static/js/creately-analytics-2.7.2.js
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c347702369b9ebda80b58140908a19081702537b
