### ISSUE TITLE
www.att.com

### ISSUE THREAD

**Issue by siffegh** [easylist/easylist#7554]
### List the website(s) you're having issues:

`https://www.att.com`

### What happens?

After submitting log in credentials, page loading won't progress

### List Subscriptions you're using:

Easylist/EasyPrivacy

### Your settings

- OS/version: Win7 Pro SP1
- Browser/version: FF 87.0, Vivaldi 3.7.2218.49
- Adblock Extension/version: UBO 1.34.0

### Other details:

Disabling EasyPrivacy on both browsers fixes the problem.

**Comment by ryanbr** [comment]
Has been fixed, force an update.

**Comment by siffegh** [comment]
Done - thanks.
