### ISSUE TITLE
https://www.iloveimg.com needs cosmetic filters (Easylist, Annoyance)

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#7555]
### List the website(s) you're having issues:

Example: https://www.iloveimg.com/

### What happens?

It's one banner on the left side of the page.
https://imgur.com/a/ivrRhpC

### List Subscriptions you're using:
https://imgur.com/a/DK044xC

### Your settings
I used element picker and these are the cosmetic filters found:
    ##.toast-accept.toast-info.toast
    ###toast-container.toast-bottom-left

**Comment by andreewmat** [comment]
Anyone?

**Comment by spirillen** [comment]
Nope, try update your filters....
