### ISSUE TITLE
 https://www.thequint.com/ have social widgets(fanboy annoyance) 

### ISSUE THREAD

**Issue by whyiswhen** [easylist/easylist#7556]
https://www.thequint.com/news/law/muzaffarnagar-riots-and-the-politics-of-withdrawing-prosecutions

### What happens?
social widgets
![image_13](https://user-images.githubusercontent.com/76880977/113394616-2e985c00-93b6-11eb-8f76-103acda076ea.png)
![image_14](https://user-images.githubusercontent.com/76880977/113394626-335d1000-93b6-11eb-9c2c-3f29397a911c.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/76880977/113394521-07da2580-93b6-11eb-9d92-d76095f25403.png)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/95a48a49c96a4b817280b717f6cb505c0e5ff230
