### ISSUE TITLE
shopee ads

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#7567]
shopee.tw
shopee.ph
shopee.**
```
data-sqe="ad"
```
![image](https://user-images.githubusercontent.com/75058881/113520973-18161e80-95c9-11eb-8440-20c6f7921804.png)
![image](https://user-images.githubusercontent.com/75058881/113521052-9b377480-95c9-11eb-8eb4-6369fbcc7bc0.png)

**Comment by ryanbr** [comment]
Maybe it should be covered by a regional list? But I can understand blocking the tracking.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/340b01e132ec56b3ebb1f1b0ad633741a616ea0a

**Comment by c2xusnpq6** [comment]
> Maybe it should be covered by a regional list?

covered by a regional list? No..... Shopee has operations in multiple countries (google translate

**Comment by c2xusnpq6** [comment]
@ryanbr @Khrin ping?

**Comment by c2xusnpq6** [comment]
ping???

**Comment by ryanbr** [comment]
non english, leaving.
