### ISSUE TITLE
Adding of some new rules to EasyPrivacy

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7568]
I found the following rules in uBlock Privacy and I think EasyPrivacy should add them to their list: 

||adnotbad.com^
||copyhomework.com^
||coursecopy.com^
||icontent.us^$document
||jsfuel.com^
||lnkr.us^$document
||ratexchange.net^
||qip.ng^$document
||qip.ru^$document
||quiztoolbox.com^
||quizlookup.com^
||serverads.net^
||silkenthreadiness.info^
||studyeffect.com^
||takethatad.com^
||testbooksolutions.com^
||tradeadsexchange.com^

###List Subscriptions you're using: I am using EasyList, EasyPrivacy and Easylist Dutch

- OS/version: Windows 10 Home, 20H2, build 19042.867
- Browser/version: Edge, version 89.0.774.63 (Official build) (64-bits)
- Adblock Extension/version: uBlock Origin, version 1.34.0

**Comment by ryanbr** [comment]
Most are harmless.  These domain change so often.
