### ISSUE TITLE
Adding some rules to EasyList

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7570]
I found some rules (that are still in use) in Adguard Spyware. But Easylist don't have those rules and the could be added. 
Note: those rules don't contain redirects and other stuff Adblock Plus can't handle. 
[extra rules for EL or EP.txt](https://github.com/easylist/easylist/files/6257443/extra.rules.for.EL.or.EP.txt)

### List Subscriptions you're using: EasyList, EasyPrivacy and Easylist Dutch

- OS/version: Windows 10 Home, 20H2, build 19042.867
- Browser/version: Edge, version 89.0.774.63 (Official build) (64-bits)
- Adblock Extension/version: uBlock Origin, version 1.34.0

**Comment by Yuki2718** [comment]
Better to post one by one with actual URLs where the trackers used. EP doesn't add cosmetic filters and some are obviously covered by other rules in EP. You have to confirm each is actually in use, the target is not dead, and is missed by EP.

**Comment by JohnyP36** [comment]
But does rules can be added to EasyList, right?

**Comment by Yuki2718** [comment]
> But does rules can be added to EasyList, right?

Rather to EP, IF necessity/usefulness is confirmed for each rule.

**Comment by JohnyP36** [comment]
Thank you. I will close this issue and make new issues (if necessary) for each rule/domain.
