### ISSUE TITLE
archivebay.com

### ISSUE THREAD

**Issue by strict-block** [easylist/easylist#7578]
### List the website(s) you're having issues:

`https://www.archivebay.com/site/e-gym.pl--2020-11-24__18-38-51--923548`

### What happens?

Main content of site is hidden due: `##.social-wrapper` https://github.com/easylist/easylist/blob/95a48a49c96a4b817280b717f6cb505c0e5ff230/fanboy-addon/fanboy_social_general_hide.txt#L10733

### List Subscriptions you're using:

Fanboy's Social

### Your settings

- OS/version: Windows 10 Pro 20H2
- Browser/version: Firefox 87
- Adblock Extension/version: ABP 3.10.2 

### Other details:

may need add exception in line:

https://github.com/easylist/easylist/blob/784b7f3de43d7221bfb09bf182851cf1dd634f1e/fanboy-addon/fanboy_social_allowlist_general_hide.txt#L413

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a590c0d4fc5ef7c28708297387f19afb42e9e46c
