### ISSUE TITLE
New rule for instagram.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7581]
### List the website(s) you're having issues: 
www.instagram.com

### What happens?
The following should be blocked on Instagram. It seems a first party tracker. 
||graph.instagram.com/logging_client_events

### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by ryanbr** [comment]
Already blocked: `easyprivacy/easyprivacy_thirdparty.txt:||instagram.com/logging_client_events`
