### ISSUE TITLE
Third party tracking by taboola.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7582]
### List the website(s) you're having issues: 
taboola.com

### What happens?
taboola.com is a third party tracker. Sites should never use a third party for their first party recommendations. So,...
||taboola.com^$third-party

### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by ryanbr** [comment]
We block most of taboola, if you need outright blocking Include Fanboy Annoyances.
