### ISSUE TITLE
Tracking by jwplayer.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7583]
### List the website(s) you're having issues: 
instagram.com

### What happens?
When sites uses JW Player to play their videos. JW Player (jwplayer.com) it uses jwpltx.com. So I should block this: 
||jwpltx.com^$3p

### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by ryanbr** [comment]
Blocking that would cause false positives with videos.
