### ISSUE TITLE
Tracking on bbc.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7585]
### List the website(s) you're having issues: 
bbc.com

### What happens?
BBC.com tracks you in various ways. So I should add the rule: 
||mybbc-analytics.files.bbci.co.uk^

### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by ryanbr** [comment]
In Easyprivacy already:

`easyprivacy/easyprivacy_general.txt:/mybbc-analytics.`
