### ISSUE TITLE
Ads on reddit.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7586]
### List the website(s) you're having issues: 
reddit.com

### What happens?
Because advertisements are or could be shown on reddit.com apply the following rule: 
||gateway.reddit.com/desktopapi/v1/sidebar_ads$xmlhttprequest,important,domain=www.reddit.com

### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by ryanbr** [comment]
Filter: `_ads?`
Covers: `https://gateway.reddit.com/desktopapi/v1/sidebar_ads?allow_over18=1&include=identity`

So already fixed in EL.
