### ISSUE TITLE
Tracking via Gigya.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7588]
### List the website(s) you're having issues: 
every site that uses gigya.com
### What happens?
When gigya.com is used in other sites gigya can track you. Adding the following rules can stop that: 
||cdns.gigya.com/js/gigyaGAIntegration.js
||gscounters.*.gigya.com^$third-party
||gscounters.gigya.com^$third-party

### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by ryanbr** [comment]
```
easyprivacy/easyprivacy_general.txt:/gscounters.
easyprivacy/easyprivacy_general.txt:/gigyaGAIntegration.
```

In Easyprivacy already.
