### ISSUE TITLE
Tracking by quantserve.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7589]
### List the website(s) you're having issues: 
Any site that uses quantserve.com (example: gfcnieuws.nl, but there are a lot more)

### What happens?
You will be tracked on a site if that site uses quantserve.com 
By adding the following rules it is solved: 
||quantserve.com^$script,3p
||quantserve.com/pixel$third-party

### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by Khrin** [comment]
It's already blocked by EasyPrivacy.

**Comment by JohnyP36** [comment]
> It's already blocked by EasyPrivacy.

||quantserve.com^$script,3p
is not in EasyPrivacy. It has only ||quantserve.com$~third-party
But it has to block the third-party script, which isn't done.
