### ISSUE TITLE
Tracking by analytics.webads.eu

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7590]
### List the website(s) you're having issues: 
Every site that uses analytics.webads.eu
### What happens?
When sites uses "analytics.webads.eu" this this will track you (example: klusidee.nl but there are more). 
 Add the following rule will stop this: 
||analytics.webads.eu^
### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch
- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by Khrin** [comment]
It's already blocked by EasyPrivacy. https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers_international.txt#L580

**Comment by JohnyP36** [comment]
> It's already blocked by EasyPrivacy. https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers_international.txt#L580

But this rule is only third party. Should analytics.webads.eu not be blocked totally?
