### ISSUE TITLE
Third party tracking on businessinsider.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7592]
### List the website(s) you're having issues: 
businessinsider.com
### What happens?
In Adguard Spyware (Tracking Protection) on businessinsider.com the general rule is applied "||ccpa.sp-prod.net/ccpa.js" 
I think this rule should be added to EasyPrivacy to prevent tracking.
### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by ryanbr** [comment]
`easyprivacy/easyprivacy_general.txt:/ccpa.js`

Already in Easyprivacy
