### ISSUE TITLE
Tracking via disqus.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7593]
### List the website(s) you're having issues: 
All sites that are using disqus.com (example: vidmax.com but there are more)

### What happens?
If sites uses disqus.com disqus.com will track you. Add the following rule: 
||links.services.disqus.com/api/ping
### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by Khrin** [comment]
It's already blocked by EasyPrivacy. https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt#L745
