### ISSUE TITLE
Easylist Cookie blocks all Patreon banners

### ISSUE THREAD

**Issue by georgebonnr** [easylist/easylist#7595]
### List the website(s) you're having issues:
`https://patreon.com`

### What happens?
All banners are blocked, including important banners in the logged-in user experience.
Fix is proposed here: https://github.com/easylist/easylist/pull/7594

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Sure, merged.
