### ISSUE TITLE
Tracking via fundingchoicesmessages.google.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7596]
### List the website(s) you're having issues: 
Sites that uses fundingchoicesmessages.google.com (like bbc.com / bbc.co.uk)
### What happens?
When I contacted uBlock about this domain they said it should be blocked because of unnecessary tracking of Google. 
But I'm not using their filterlist. So could you add the following filter: 
||fundingchoicesmessages.google.com^$3p
### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch
- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by Yuki2718** [comment]
Blocking this causes troublesome popups/anti-adblock on some sites. uBO can block this thx to its advanced capability (not compatible to EasyList which supports broader range of blocker) implemented into uBlock filters. Seriously, if you use uBlock **Origin** you should use uBlock filters - without it you loose the best part of it.

**Comment by JohnyP36** [comment]
In uBlock Filters this is blocked without further ado. 
So, EL or EP could add this rule and made exceptions if necessary. 

||fundingchoicesmessages.google.com^$3p,domain=~bbc.com

**Comment by Yuki2718** [comment]
@JohnyP36 What allows uBO to block this is `*##.div-gpt-ad:style(width:1px!important;height:1px!important;min-height:1px!important;)`, not the blocking filter itself. Of note, all the relevant parties (EL, AG, uBO, ABP) are very familiar with this - we had discussion in past on Slack.

**Comment by JohnyP36** [comment]
Oke, thank you.
