### ISSUE TITLE
 Blocking s.pinimg.com/ct/core.js

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7598]
### What happens?
I think s.pinimg.com/ct/core.js should be blocked with the following rule: 
`||s.pinimg.com/ct/core.js`
You can test this on the site https://www.dimehouse.nl/
### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch
- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by JohnyP36** [comment]
@ryanbr Can you look at this?

**Comment by llacb47** [comment]
He's busy, plus you are not known for opening useful issues. This one is a good issue though, the entire script load can be blocked instead of just the tracker.

**Comment by ryanbr** [comment]
blocking the pinterest script could cause issues, why should it be blocked? @JohnyP36

**Comment by JohnyP36** [comment]
@ryanbr I thought this has to do with tracking. (Partly because Adguard Spyware blocks this script.) 

So I thought EasyPrivacy should also block this. But if I'm wrong, tell me.

**Comment by ryanbr** [comment]
sure, have consulted this change.
