### ISSUE TITLE
Tracking by jwlayer.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7599]
### What happens?
When sites uses JW Player to play their videos. JW Player (jwplayer.com) it uses jwpltx.com. So I should block this:
||jwpltx.com^$3p
This rule don't cause problems with videos. Example: https://www.eurosport.nl/wielrennen/ronde-van-vlaanderen/2021/annemiek-van-vleuten-wint-ronde-van-vlaanderen-2021_sto8205943/story.shtml
### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch
- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by Khrin** [comment]
It's already blocked by `/ping.gif?` in EasyPrivacy.
