### ISSUE TITLE
addition of a very broad filter related to amazon s3

### ISSUE THREAD

**Issue by mrburns** [easylist/easylist#760]
One of our client website is currently having issues due to a filter that was introduced mid november (4b1a05a9c70d78a2b939d4831c49f13e548c5705)

Our client's website is a classified ads much like craiglist in a way where members can publish goods or services they would like to monetize.

It appears that the classifieds pictures are stored on a path that matches the one I mentionned previously (4b1a05a9c70d78a2b939d4831c49f13e548c5705).

I don't know how to proceed now as I'm not too familiar with your way to deal with whitelisting. Should I send you proofs or anything ?

Any help would be welcome :)

**Comment by Khrin** [comment]
Yes, can you post here an example link?

**Comment by mrburns** [comment]
Sure, here is a public link. With ublock origin enabled almost no picture is displayed, with it disabled I can see the pictures.

I hope it helps.

**Comment by Khrin** [comment]
I've modified our filter. https://github.com/easylist/easylist/commit/021491aaeffcd396c17076859946f17f63326edf

**Comment by mrburns** [comment]
awesome @Khrin thank you so much 👍
