### ISSUE TITLE
Tracking via an Amazon domain

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7605]
Belong to Amazon.com. The GET request is full of tracker-looking data.

||silkenthreadiness.info^

So, I think EasyPrivacy (or EasyList) should add this rule to their list

**Comment by JohnyP36** [comment]
@ryanbr Can you look at this?

**Comment by llacb47** [comment]
This is a useless issue. Where did you see this? What is the payload? What is the url? 

Stop opening stupid issues.
