### ISSUE TITLE
adblockanalystics.com

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7606]
As copied from uBlock Privacy: 

> ! https://news.ycombinator.com/item?id=10662793
> ! Each client site has a specific id: this means the following information
> ! becomes available to adblockanalytics.com:
> ! - IP address (user)
> ! - web site ID (allows to uniquely identify a web site)
> ! - Whether a blocker is used
> ! - Screen size/browser viewport size
> ||adblockanalytics.com^$3p

Can you add this rule to EasyList or EasyPrivacy?

**Comment by JohnyP36** [comment]
@ryanbr Can you look at this?

**Comment by ryanbr** [comment]
No need to block, since we block the trackers already
![adanna](https://user-images.githubusercontent.com/1659004/125943609-6908f87a-7220-4100-80bb-afea9ebab3b8.png)
