### ISSUE TITLE
Blocking the "Switch to Chrome" popup on google.com

### ISSUE THREAD

**Issue by cbwee** [easylist/easylist#7607]
### List the website(s) you're having issues:
`google.com`

### What happens?
In Microsoft Edge, when I go to `google.com`, this popup message appears and tells me to "Switch to Chrome".

It needs to be blocked, since I want to keep using Edge without seeing it.

I already have Fanboy's Annoyance and uBlock Annoyances filters enabled, it's still not blocked.
<img width="250" alt="螢幕擷取畫面 2021-04-08 154506" src="https://user-images.githubusercontent.com/34395942/113988761-4f8e0080-983f-11eb-87c4-951417971a1e.png">

### List Subscriptions you're using:
uBlock filters (including Annoyances), EasyList, EasyList China, EasyPrivacy and Fanboy's Annoyances.

### Your settings

- OS/version: Windows 10 1909
- Browser/version: Microsoft Edge 89.0.774.68
- Adblock Extension/version: uBlock Origin v1.34.0

**Comment by JohnyP36** [comment]
I use my self-made rule: 
||ogs.google.*/widget/callout$domain=google.*

**Comment by cbwee** [comment]
> `||ogs.google.*/widget/callout$domain=google.*`

@JohnyP36 Thank you, it works.

I hope @ryanbr can add it to the Annoyance list.

**Comment by Yuki2718** [comment]
> 
> I hope @ryanbr can add it to the Annoyance list.

This is known but the rule won't be added, the iframe is used for other purposes too: https://github.com/AdguardTeam/AdguardFilters/issues/62534
