### ISSUE TITLE
/beacon.*  blocking

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7608]
EL is blocking: 
```
/beacon.cgi?
/beacon.gif?
/beacon.html?
/beacon.js
/beacon.min.js
```

Why not block: 
```
/beacon.php?
/beacon.php3?
```

**Comment by ryanbr** [comment]
Submit sites that use these for tracking.

**Comment by JohnyP36** [comment]
> Submit sites that use these for tracking.

You mean that you added those 2 rules?
