### ISSUE TITLE
Backdrop visible after cookie popup blocked - management30.com

### ISSUE THREAD

**Issue by alexm92** [easylist/easylist#7609]
### List the website(s) you're having issues:
```
https://management30.com/practice/value-stories/
```

### What happens?

The backdrop is still visible and the website is not functional 

### List Subscriptions you're using:

EasyCookie List

### Your settings

- OS/version: macOs/10.15.7
- Browser/version:  Chrome/89.0.4389.114
- Adblock Extension/version: 3.10.2

### Other details:
![image](https://user-images.githubusercontent.com/2988929/114004005-ea4e0580-9866-11eb-959a-a9e6dd0b8d08.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b5d7768e0493e62b059b642a0c7a7d9db9e85e30
