### ISSUE TITLE
Tumblr: "takeover" ad

### ISSUE THREAD

**Issue by marcustyphoon** [easylist/easylist#7612]
### List the website(s) you're having issues:

`https://www.tumblr.com/dashboard`

### What happens?

"Takeover" style ads (a custom graphic at the top of the dashboard) are not cosmetically filtered.

This can be implemented via `tumblr.com##._18O6M`.

**Comment by ryanbr** [comment]
If you inspect the source, it may give us better filter options

**Comment by marcustyphoon** [comment]
This can now be fixed via `tumblr.com##.kHo0b` after a change to the Tumblr css map.

**Comment by ryanbr** [comment]
Should be covered now
