### ISSUE TITLE
Tumblr: sidebar ad container shown

### ISSUE THREAD

**Issue by marcustyphoon** [easylist/easylist#7618]
### List the website(s) you're having issues:

`https://www.tumblr.com/dashboard`

### What happens?

Easylist blocks the ad in Tumblr's sidebar, leaving an empty "sponsored" container even with cosmetic filtering turned on.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/8336245/114168590-4fe0d700-98e5-11eb-986a-486a02fabe1d.png">

### List Subscriptions you're using:

- easylist 202104060939

### Your settings

- OS/version: MacOS 10.14
- Browser/version: Firefox 87
- Adblock Extension/version: uBlock Origin v1.34.0

### Other details:

I personally implement this by cosmetic filtering `._3v4BC ._3bMU2`, or `sidebarContent mrecContainer` in tumblr's CSS map.

I imagine it would be possible, if more expensive, to make a human readable rule not dependent on the current state of the CSS map (`tumblr.com#?#aside > div:-abp-contains(Sponsored)`?)

Here's the HTML structure annotated with the CSS map translations.

```html
<aside>
	<div class="_149RG (sidebarItem)">non-ad sidebar item content</div>
	<div class="_149RG (sidebarItem)">non-ad sidebar item content</div>
	<div class="_3v4BC (sidebarContent)" style="top:69px">
		<div class="_3bMU2 (mrecContainer)">
			<div class="_1Bwz3 (impressionLoggingWrapper; used elsewhere)">
				<div class="_2cnt0 (hiddenObserver; used elsewhere)"></div>
				<div class="_149RG (sidebarItem)">
					<h1 class="_2biQz (sidebarTitle)">Sponsored</h1>
					<div class="Z0V46 (innerContent)">
						ad content
					</div>
				</div>
			</div>
		</div>
	</div>
</aside>

**Comment by manuel-martinez-dev** [comment]
for me the following filters work:
```
tumblr.com##div[style="top:69px"]
tumblr.com##a[href^="https://www.tumblr.com/docs/en/relevantads"]
tumblr.com##iframe[src*="https://assets.tumblr.com/pop/monetization/html/iab-safeframe/sf-"]
```
but as mentioned by the op, maybe these might not be consistent enough.

**Comment by marcustyphoon** [comment]
The iframe and the relevant ads link are inside the `sidebarContent` div, so only the first of those would be necessary (preferably with an `aside` parent selector to only hit the sidebar). That works too, assuming Tumblr doesn't introduce another sticky sidebar section, which seems unlikely.

**Comment by Yuki2718** [comment]
AG solution: `tumblr.com###base-container aside > div[class^="_"] > div[class^="_"] > div[class^="_"] > div[class^="_"] > h1 + div[class] > div[class^="_"] div.iab_sf:upward(4)` but `:upward()` is not compatible to ABP so instead `:-abp-has()` should be used, which will be less efficient for the number of nodes to evaluate.
