### ISSUE TITLE
superbet.pl

### ISSUE THREAD

**Issue by strict-block** [easylist/easylist#7619]
### List the website(s) you're having issues:

[](https://github.com/AdguardTeam/AdguardFilters/issues/79919)

`https://www.superbet.pl/intro`
`https://www.superbet.pl/`

### What happens?

Page is blank due block `||zdassets.com/ekr/snippet.js` https://github.com/easylist/easylist/blob/5842851d916e3601674bc951d0c7da280a58cea1/fanboy-addon/fanboy_annoyance_thirdparty.txt#L388

### List Subscriptions you're using:

Fanboy's Annoyance

### Your settings

- OS/version: Windows 10 Pro 20H2
- Browser/version: Firefox 87
- Adblock Extension/version: ABP 3.10.2

### Other details:

May need allow load file:

`@@||static.zdassets.com/ekr/snippet.js$script,domain=superbet.pl`

**Comment by krystian3w** [comment]
Breakage: uBlockOrigin/uAssets/issues/16856
