### ISSUE TITLE
epoliklinika.lv

### ISSUE THREAD

**Issue by anonymous74100** [easylist/easylist#762]
`https://epoliklinika.lv/pieraksts.html`

Click on _"Veselības centru apvienība (visas poliklīnikas)"_, it will show an error:

```
Error: Message: ReferenceError: Fingerprint2 is not defined - URL: https://www.eveselibaspunkts.lv/js/global/global.min.js?v=2.2.7.1 - Line: 1 - Column: 2880 - Error object: {}
```

Problematic filter from **EasyPrivacy**:
```
/fingerprint2.min.js
```

Fix:
```
@@||eveselibaspunkts.lv/js/global/fingerprint2.min.js
```

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/4970bfbe549fc86a1e8d58cc0c0efbea9dca3fa4
