### ISSUE TITLE
chefkoch.de tracking

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#7622]
### List the website(s) you're having issues:

`https://www.chefkoch.de`

### What happens?

Ublocked tracking script `https://www.chefkoch.de/tracking/tracking-72011a17fe.min.js`

### List Subscriptions you're using:

uBlock Origin default with EasyList, EasyList germany and EasyPrivacy

### Your settings

- OS/version: win 10
- Browser/version: firefox developer
- Adblock Extension/version: uBlock Origin

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/418957ce84984e48936aca352c873f606c627855
