### ISSUE TITLE
forumotion.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7631]
### List the website(s) you're having issues:

`https://myst.forumotion.com/t368-wifi-on-a-nintendo-ds`

### What happens?

Large placeholder near the top, and a "Sponsored content" placeholder near the bottom.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/114254719-50df3a80-99b1-11eb-9cbd-1fa3295830a9.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 89.0.4389.114 x64
- Adblock Extension/version: uBO 1.34.1b3 + IDCAC 3.2.9

### Other details:

I propose:
```
forumotion.com##td[width] > .forumline:first-of-type
forumotion.com#?#.post:-abp-contains(/^Sponsored content/)
forumotion.com#?#.post:-abp-contains(/^Sponsored content/) + tr
```

![image](https://user-images.githubusercontent.com/22780683/114255970-30b27a00-99b7-11eb-9c11-d9d600c274bf.png)

**Comment by ryanbr** [comment]
Not worth blocking this
