### ISSUE TITLE
techjunkie.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7633]
### List the website(s) you're having issues:

`https://www.techjunkie.com/`

### What happens?

Transparent overlay placeholder on bottom that can't be crossed out; as well as one placeholder near the top.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/114254719-50df3a80-99b1-11eb-9cbd-1fa3295830a9.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 89.0.4389.114 x64
- Adblock Extension/version: uBO 1.34.1b3 + IDCAC 3.2.9

### Other details:

I propose:
```
techjunkie.com##.qualcont
techjunkie.com##.japm-ad
```

The overlay continues to be present even after accepting cookies.

![image](https://user-images.githubusercontent.com/22780683/114256671-3ad67780-99bb-11eb-86d8-afdc1e56ed80.png)

**Comment by ryanbr** [comment]
Getting no hits from the suggested filters.
