### ISSUE TITLE
ancient.eu

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7634]
### List the website(s) you're having issues:

`https://www.ancient.eu/Rome/`

### What happens?

Various placeholders on the right and below the article.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/114254719-50df3a80-99b1-11eb-9cbd-1fa3295830a9.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 89.0.4389.114 x64
- Adblock Extension/version: uBO 1.34.1b3 + IDCAC 3.2.9

### Other details:

I propose:
```
ancient.eu##.ahe-ad
ancient.eu##.pubexchange_module
```

![image](https://user-images.githubusercontent.com/22780683/114256905-d1efff00-99bc-11eb-80da-824dde0d9a44.png)

**Comment by ryanbr** [comment]
`ancient.eu##.ahe-ad`  not an Advert, will cover the donation box.
