### ISSUE TITLE
CNBC.com - Modal overlay (Easylist Cookie List / Fanboy's Annoyance List) [GDPR / Geo]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#7650]
### Affected site:
`https://www.cnbc.com/`

### Issue:
When used in conjunction with **AdGuard Annoyances filter**, **Easylist Cookie List** / **Fanboy's Annoyance List** triggers a modal overlay @ `cnbc.com`, because OneTrust's geolocation scripts are whitelisted on a generic level!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **EasyList Cookie List**
* **Fanboy's Annoyance List**

### Problem rule:
`@@||geolocation.onetrust.com/cookieconsentpub/$script`

### Possible fix:
```
- @@||geolocation.onetrust.com/cookieconsentpub/$script

+ @@||geolocation.onetrust.com/cookieconsentpub/$script,domain=~cnbc.com
```

### Temporary fix (for uBO / AdGuard):
`||geolocation.onetrust.com/cookieconsentpub/$script,important,domain=cnbc.com`

(@BlazDT)

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.1.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by ryanbr** [comment]
I could add this, but what if a user didn't have Adguard Annoyances enabled? @THEtomaso

**Comment by THEtomaso** [comment]
> what if a user didn't have Adguard Annoyances enabled?

AFAICT, blocking their geo script doesn't break anything, regardlessly.

**Comment by ryanbr** [comment]
Okay, lets see. I'll remove the exception if there are any issues.
