### ISSUE TITLE
jamobil.de [Easylist Cookie]

### ISSUE THREAD

**Issue by spodermenpls** [easylist/easylist#7651]
### List the website(s) you're having issues:
`www.jamobil.de`

### What happens?
At this website, Easylist Cookie's only active `##.cookie__footer` rule removes the bottom row of this "cookie agreeance" pop-up, which in this case results only in the removal of the "Accept" button, making the pop-up not closable. I'd be pleased to see Easylist Cookie cover the entirety of the pop-up and the dark overlay the background.

### List Subscriptions you're using:

uBlock filter family
Peter Lowe's list
Adguard Base, Tracking, Annoyances, German + Easylist German
Easylist
Easylist Cookie

### Your settings

- OS/version: Windows 10 Pro
- Browser/version: Firefox 87.0 64-bit
- Adblock Extension/version: uBlock Origin 1.34.0

### Other details:
![Screenshot](https://user-images.githubusercontent.com/23747593/114476092-e8cf6500-9bf9-11eb-8923-72c6828b5ee1.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f193569d4c1f3abc07946f861dc8dbdecc7e445e
