### ISSUE TITLE
digitaltrends.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#7653]
### List the website(s) you're having issues:
`https://digitaltrends.com`

### What happens?

an annoyance
### List Subscriptions you're using:
![Screenshot 2021-04-13 211355](https://user-images.githubusercontent.com/81419637/114600599-35b84780-9c9d-11eb-9808-63d7e10eedf3.png)

### Your settings

- OS/version: Microsoft Windows 10 Home Version 10.0.19042 Build 19042
- Browser/version: Firefox Version 87.0
- Adblock Extension/version: uBlock Origin 1.34.0

**Comment by IThinkIAmCool** [comment]
`||consent.cookiebot.com^$third-party` fixed it for me.

**Comment by IThinkIAmCool** [comment]
I haven't found a fix.

**Comment by IThinkIAmCool** [comment]
Is the annoyance not being dealt with on purpose in order to avoid breakage?

**Comment by ryanbr** [comment]
I loaded the site, seems fine here.  Screenshot of the issue?

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/81419637/114903372-6b853980-9e1f-11eb-93ee-1bcfd98ce043.png)

**Comment by ryanbr** [comment]
I would need more info, I can't see it. I tested from UK IP and couldn't see it. I know blocking some cookie scripts will break the site.

Maybe `@@||consent.cookiebot.com^$script,domain=digitaltrends.com|fidelityhouse.eu|refinery29.com|sportdiver.com|warscrap.io,badfilter`

Test that filter, does it cause issues with videos, comments etc.

**Comment by IThinkIAmCool** [comment]
I got the annoyance while having a Romanian IP address.

**Comment by IThinkIAmCool** [comment]
> Maybe `@@||consent.cookiebot.com^$script,domain=digitaltrends.com|fidelityhouse.eu|refinery29.com|sportdiver.com|warscrap.io,badfilter`
I added the filter to 'My filters' and I didn't encounter the annoyance. I will look further to find out if it causes any issues.
