### ISSUE TITLE
www.autocarindia.com

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#7656]
### List the website(s) you're having issues:
https://www.autocarindia.com/car-news/toyota-land-cruiser-vaccine-transporter-gets-who-prequalification-420470 

### What happens?
1. go to the link.
2. there are follow us on social widgets
3. 
![image](https://user-images.githubusercontent.com/76880977/114705240-255ba780-9d45-11eb-81b3-7b1636ec2ad4.png)
![image](https://user-images.githubusercontent.com/76880977/114705258-2b518880-9d45-11eb-8276-f75463310d76.png)

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/76880977/114705158-0e1cba00-9d45-11eb-8791-775aa3527fb2.png)

**Comment by ryanbr** [comment]
Leaving the top social, but catching the rest.

**Comment by chirag127** [comment]
any reason for leaving the social widget?
