### ISSUE TITLE
app.hey.com

### ISSUE THREAD

**Issue by rosa** [easylist/easylist#7659]
### List the website(s) you're having issues:
```
https://app.hey.com/
```

### What happens?

`app.hey.com` is a mail service app with no ads or tracking of any kind. We happen to use `about:blank` as the src for dynamically-generated iframes where we load emails. The addition of this rule:
```
##iframe[src="about:blank"]
```
in https://github.com/easylist/easylist/commit/e37303d9cc82be7b1064b9e2220fa232d84a8d7f is breaking our app completely, and I'm sure it's happening for other apps since this is a common idiom. 

### List Subscriptions you're using:

```
https://easylist.to/easylist/easylist.txt
```
### Your settings

- OS/version: macOS 11.2.3
- Browser/version: Chrome Version 89.0.4389.114 (Official Build) (x86_64)
- Adblock Extension/version: AdBlock Plus Version number 3.10.2

**Comment by packagethief** [comment]
It seems this rule also created a problem for Google Docs, which was reported in https://forums.lanik.us/viewtopic.php?f=64&t=46045&p=159550 and fixed in https://github.com/easylist/easylist/commit/9bbd801

**Comment by packagethief** [comment]
It looks like this was reverted in 44ab3df, so feel free to close.

**Comment by rosa** [comment]
Yes! Thanks @packagethief.
