### ISSUE TITLE
kocham.wielun.pl

### ISSUE THREAD

**Issue by kitor** [easylist/easylist#7660]
### List the website(s) you're having issues:

Example:
https://kocham.wielun.pl/infrastruktura/2021/04/01/w-patnowie-trwaja-prace-budowlane-na-stadionie/

Almost every page is affected

### What happens?

This rule is broken: `kocham.wielun.pl##.module-article`. Articles content is gone, just "similar articles" links are left on the page.

Class module-article is used for multiple webpage elements. Someone tried to remove static banner which also use this class and failed task successfully.

### List Subscriptions you're using:

https://easylist-downloads.adblockplus.org/easylistpolish+easylist.txt

### Your settings

Doesn't matter. ABP + list from the link above.

### Other details:
None

**Comment by ryanbr** [comment]
Should be reported in https://forums.lanik.us/viewforum.php?f=107&sid=49f2378126ad0a3e07fc8a08e8080969

**Comment by kitor** [comment]
Forum seems inactive, only moderator in group responsible for that section was active 4 years ago. Oh, and I can't even post there without moderator approval.

Is this really an only way? This rule is literally blocking all the context on local journal, which can be viewed as censorship, and not an accident.

**Comment by Khrin** [comment]
Try to report here: https://github.com/easylistpolish/easylistpolish/issues We don't manage EasyList Polish.

**Comment by kitor** [comment]
Thank you, finally something concrete.

Since those "regional" lists are using "Easylist" in name and forums  - I think it is worth to point to those repositories directly on both website and in main repo readme. 

It is confusing, as from what I see - some regional lists have "official" repository under https://github.com/easylist, while other not.
