### ISSUE TITLE
www.newseveryday.com

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#7662]
### List the website(s) you're having issues:
https://www.newseveryday.com/

### What happens?
newsletter + social button 
![image](https://user-images.githubusercontent.com/76880977/114821629-7c618b00-9dde-11eb-90fe-4f0a81082d93.png)
![image](https://user-images.githubusercontent.com/76880977/114821637-7e2b4e80-9dde-11eb-80ea-2e53a1ccf280.png)

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/76880977/114821649-81263f00-9dde-11eb-937a-1b4e2b48e309.png)

**Comment by ryanbr** [comment]
Not seeing the social bits. But covering the native video ad
