### ISSUE TITLE
delet.jhi.pl

### ISSUE THREAD

**Issue by strict-block** [easylist/easylist#7663]
### List the website(s) you're having issues:

`https://delet.jhi.pl/pl/` [](https://github.com/AdguardTeam/AdguardFilters/issues/80484)

### What happens?

Main content is not loaded due block file `angular-google-analytics.min.js`

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 10 Pro 20H2
- Browser/version: Firefox 88
- Adblock Extension/version: ABP 3.10.2 

### Other details:

This filter block too much: https://github.com/easylist/easylist/blob/00786a043a84a5f154e22c3fcfa0a80296ff042f/easyprivacy/easyprivacy_general.txt#L61

`@@||delet.jhi.pl/bower_components/angular-google-analytics/dist/angular-google-analytics.min.js$script,domain=delet.jhi.pl`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a72ea510a16212bcde1c6dcb85ef76fbc8b36626
