### ISSUE TITLE
Tracking on cat-care.nl

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7664]
### URL(s) where the issue occurs
cat-care.nl
### Describe the issue
on cat-care.nl there is tracking. With the following rule this will be stopped: --> `||smetrics.cat-care.nl^`
### Versions
- Windows 10, version 20H2
- Browser/version: **Edge** _latest version_
- uBlock Origin version: **1.34.0**

### Filters in use
- uBlock Filter
- EasyPrivacy
- EasyList
- EasyList Dutch

**Comment by JohnyP36** [comment]
@ryanbr Can you look at this?

**Comment by ryanbr** [comment]
Already blocked with `/smetrics.*/id?`
