### ISSUE TITLE
Tracking on ad.nl [EasyPrivacy]

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7665]
### URL(s) where the issue occurs
ad.nl
### Describe the issue
ad.nl tracks you via "temptation.ad.nl" 
If you add the following rule it is solved: `||temptation.ad.nl^`
### Versions
- Windows 10, version 20H2
- Browser/version: **Edge** _latest version_
- uBlock Origin version: **1.34.0**

### Filters in use
- EasyPrivacy
- EasyList
- EasyList Dutch

### Notes
This tracking is relative new.

**Comment by JohnyP36** [comment]
@ryanbr Can you look at this?

**Comment by ryanbr** [comment]
I'm closing your requests, these are already blocked. and wasting my time checking blocked items.
