### ISSUE TITLE
Tracking on blgwonen.nl [EasyPrivacy]

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7666]
### URL(s) where the issue occurs
blgwonen.nl
### Describe the issue
blgwonen.nl tracks you via "swa.blgwonen.nl"
By adding the rule `||swa.blgwonen.nl^` this will stop.
### Versions
- Windows 10, version 20H2
- Browser/version: **Edge** _latest version_
- uBlock Origin version: **1.34.0**
### Filters in use
- EasyPrivacy
- EasyList
- EasyList Dutch

**Comment by JohnyP36** [comment]
@ryanbr Can you look at this?

**Comment by ryanbr** [comment]
I'm closing your requests, these are already blocked. and wasting my time checking blocked items.
