### ISSUE TITLE
Tracking on asadventure.nl [EasyPrivacy]

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7667]
### URL(s) where the issue occurs
asadventure.nl
### Describe the issue
asadventure.nl tracks you via "sstats.asadventure.nl" 
If this could be blocked by the rule `||sstats.asadventure.nl^` that would be fine.
### Versions
- Windows 10, version 20H2
- Browser/version: **Edge** _latest version_
- uBlock Origin version: **1.34.0**
### Filters in use
- EasyPrivacy
- EasyList
- EasyList Dutch

**Comment by JohnyP36** [comment]
@ryanbr Can you look at this?

**Comment by ryanbr** [comment]
Already blocked with `/id?d_visid_`
