### ISSUE TITLE
Tracking on mtv.nl [EasyPrivacy]

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7668]
### URL(s) where the issue occurs
mtv.nl
### Describe the issue
mtv.nl tracks you with **ssc.mtv.nl** when you add the filter `||ssc.mtv.nl^` this will be solved.
### Versions
- Windows 10, version 20H2
- Browser/version: **Edge** _latest version_
- uBlock Origin version: **1.34.0**
### Filters in use
- EasyPrivacy
- EasyList
- EasyList Dutch

**Comment by JohnyP36** [comment]
@ryanbr Can you look at this?

**Comment by ryanbr** [comment]
I'm closing your requests, these are already blocked. and wasting my time checking blocked items.
