### ISSUE TITLE
Tracking on esri.nl [EasyPrivacy]

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#7669]
### URL(s) where the issue occurs
 esri.nl 
### Describe the issue
esri.nl tracks you with **securetags.esri.nl**
Can you add the following rule to prevent this? `||securetags.esri.nl^`
### Versions
- Window 10, version 20H2
- Browser/version: **Edge** _latest version_
- uBlock Origin version: **1.34.0**
### Filters in use
- EasyPrivacy
- EasyList
- EasyList Dutch

**Comment by JohnyP36** [comment]
@ryanbr Can you look at this?

**Comment by ryanbr** [comment]
It's already blocked with `/id?d_visid_`  are you actually using Easyprivacy?

**Comment by JohnyP36** [comment]
Yes, but I looked in Adguard and did show such a rule in EasyPrivacy. Next time I will look better what is behind the domain.
