### ISSUE TITLE
EasyList Cookie breaks aten.com

### ISSUE THREAD

**Issue by Genda1ph** [easylist/easylist#7672]
### List the website(s) you're having issues:

Every page of `https://www.aten.com/`

### What happens?

Rule `/jquery.cookieBar.$~script` prevents site from loading its main CSS from URL listed below.

`https://www.aten.com/vendor/mrclay/minify/?f=file/template/1/css/bootstrap.css,file/template/1/style.css,file/template/1/css/dark.css,file/template/1/css/font-icons.css,file/template/1/css/animate.css,file/template/1/css/magnific-popup.css,file/template/1/css/responsive.css,file/template/1/include/rs-plugin/css/settings.css,file/template/1/css/font-awesome.min.css,file/template/1/css/owl.carousel.min.css,file/template/1/css/jquery.cookiebar.css,file/template/1/css/owl.theme.default.min.css,file/template/1/css/font-awesome5.7.min.css,file/template/1/js/video-js/video-js.css`

### List Subscriptions you're using:

EasyList and EasyPrivacy in uBlock Origin.

### Your settings

I have not re-tested with everything but uBO disabled, since I managed to trace issue through its Logger directly to aforementioned rule.

- Windows 10 Pro v2004 (Build 19041.867): 
- Brave/v 1.22.71
- uBlock Origin v1.34.0

### Other details:

Disabling uBlock solves the issue, tracing what resources got blocked results in only one relevant result, details in the screenshot below.

![image](https://user-images.githubusercontent.com/3673402/114884225-450ad280-9e0e-11eb-8edd-87c1bb4529dc.png)

**Comment by strict-block** [comment]
@kiboke you also break site with:

`/jquery.cookiebar$domain=~kvv.de|~vileda.de|~vileda.fr|~vileda.pt|~vileda.be|~vileda.nl|~vileda.fi|~vileda.se|~vileda.it|~vileda.co.uk|~germany.ru`

**Comment by kiboke** [comment]
@strict-block Thank you, it will be fixed!
