### ISSUE TITLE
shopee tracker ( shopee.* & shopee.com.* )

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#7677]
seller.shopee.ph --> `seller.shopee.*/api/collection/csp_report`

`shopee.*`:
seller.shopee.tw
seller.shopee.ph
seller.shopee.sg

`shopee.com.*`
seller.shopee.com.my
seller.shopee.co.id

```
seller.shopee.*/api/collection/csp_report
or
seller.shopee.*/api/collection/* ?
```

![image](https://user-images.githubusercontent.com/75058881/115001232-11937b00-9ed6-11eb-87b0-588921256c73.png)

![image](https://user-images.githubusercontent.com/75058881/115001535-50c1cc00-9ed6-11eb-88d8-91f6d89d2854.png)

**Comment by ryanbr** [comment]
Didn't see it, blocked another tracker.
