### ISSUE TITLE
news18.com (AMP)

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7678]
### List the website(s) you're having issues:

```
https://www.news18.com/amp/news/buzz/bengal-woman-changes-name-to-supreme-imperium-viral-newspaper-ad-has-internet-in-splits-3510020.html
https://www.google.com/amp/s/www.news18.com/amp/news/buzz/bengal-woman-changes-name-to-supreme-imperium-viral-newspaper-ad-has-internet-in-splits-3510020.html
```

### What happens?

Some placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/115022760-1f3d0680-9ebe-11eb-8417-afabd699a8eb.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 89.0.4389.128 x64
- Adblock Extension/version: uBO 1.34.1rc0 + IDCAC 3.3.0

### Other details:

I propose:
```
##.ampFlyAdd
news18.com,google.com,google.co.uk,google.co.in,google.com.pk,google.com.bd##div[style="margin-bottom:15px"][class^=jsx-]
```

![image](https://user-images.githubusercontent.com/22780683/115022994-780c9f00-9ebe-11eb-894a-9a122b5efdce.png)

**Comment by ryanbr** [comment]
Suggested filters don't remove the grey box, needs further work.

**Comment by DandelionSprout** [comment]
If you are browsing the AMP version(s), the entries still seem to work for me.

If you are browsing the non-AMP phone version, those entries seem to still be working, adding a `^` to the 2nd entry seems to make it work: `news18.com##div[style^="margin-bottom:15px"][class^=jsx-]`
