### ISSUE TITLE
Suggestion related to issue handling

### ISSUE THREAD

**Issue by cantunborn** [easylist/easylist#7679]
Old issues get burried because new issues are solved first. Ex. some site breakage issue may remain unresolved for long time and may not be trivial for every person to solve. Oldest unresolved site issue is from around start of 2020, almost 1.5 years ago.

So, I would suggest list maintainers please solve older issues first.
(May also apply to pull requests)

**Comment by Jammie1143** [comment]
The maintainer doesn't solve any issues. Only sometimes, one to two.
