### ISSUE TITLE
[Incorrect blocking] live.russia.tv [EasyPrivacy]

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylist#768]
Player is broken:

<details>

![image](https://user-images.githubusercontent.com/8361299/34007590-fcd6e7a6-e10a-11e7-8490-1477c9bf1ec7.png)

</details>

URL: http://live.russia.tv/index/index/channel_id/1

Caused by: `||vgtrk.com/js/stat.js`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/070459486b4ce373d8fa6664f44af0262b943138 Hi, can you confirm if it works now?

**Comment by Alex-302** [comment]
Sure:) Thanks.
