### ISSUE TITLE
xvideos.com

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#77]
Hello,

With ublock on, then i open xvideos then the video player streches like below in the screenshot: 

https://s31.postimg.org/lmnxcdy2z/2_with_adblock.jpg

With ublock off, then i open xvideos and stop the page from loading fully
then the default video player opens like below in the screenshot:

https://s31.postimg.org/n18381igr/1_without_adblock.jpg

Please could you provide a filter so that xvideos plays videos with default video player size which is shown in above screenshot.

Thanks a lot

**Comment by gorhill** [comment]
What version of uBO are you using? Looks fine here with 1.7.7b9.

**Comment by rajatmathurs** [comment]
I am using the latest version of ublock which i updated and then posted the
screenshot of my computer.

Please check once again on pc and then you will see that xvideo player is
streched once unlock is on then turn off unlock to see the default player
of  xvideo size, which I want with the ads blocked in the side.

Let me know

Thank you

**Comment by gorhill** [comment]
> I am using the latest version of ublock which i updated and then posted the
screenshot of my computer.

Version number please.

**Comment by rajatmathurs** [comment]
i have just updated ublock now and the uBlock Origin v1.7.6 where is 1.7.7b9 that you have mentioned

**Comment by gorhill** [comment]
xvideos.com#@##video-ad

**Comment by rajatmathurs** [comment]
Yes this filter is working great
Thanks a lot

**Comment by rajatmathurs** [comment]
Please update the filter in early list

Thanks a lot

**Comment by gorhill** [comment]
That won't be added to EasyList, it's only you who want that look. The whitespace aside is where an ad is supposed to appear, and EasyList does its job of blocking it just like it should.

**Comment by rajatmathurs** [comment]
Ok no problem
Once again thanks
