### ISSUE TITLE
Tumblr: all cosmetic filtering broken

### ISSUE THREAD

**Issue by marcustyphoon** [easylist/easylist#7700]
### List the website(s) you're having issues:

`tumblr.com/dashboard`

### What happens?

All cosmetic filtering is nonfunctional due to an update to the site's React CSS map.

### List Subscriptions you're using:

Easylist 202104191755

**Comment by ryanbr** [comment]
If this looks okay, more simplified 
```
tumblr.com##._3L_Fb
tumblr.com##._3x1ep
tumblr.com##.vd2CF
```

! Possible tracker
`||tspmagic.tumblr.com^`

**Comment by marcustyphoon** [comment]
`._3L_Fb` removes the square ad area under the "sponsored" header but leaves the header itself and the "about tumblr ads" text.

![image](https://user-images.githubusercontent.com/8336245/115973055-1cb65e80-a507-11eb-8f9c-e270d7ac3664.png)
