### ISSUE TITLE
https://byjus.com/

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#7707]
https://byjus.com/govt-exams/logical-reasoning/ have a chat pop up + go up button.
![image](https://user-images.githubusercontent.com/76880977/115545693-b8568d80-a2c1-11eb-8897-e603cf110681.png)
![image](https://user-images.githubusercontent.com/76880977/115545691-b7bdf700-a2c1-11eb-8d78-248742356c2f.png)
![image](https://user-images.githubusercontent.com/76880977/115545714-bf7d9b80-a2c1-11eb-9d5b-f3f5fed119f6.png)
![image](https://user-images.githubusercontent.com/76880977/115545722-c4424f80-a2c1-11eb-930d-e529abde4351.png)

**Comment by ryanbr** [comment]
Self promos, and we don't touch chat popups

**Comment by chirag127** [comment]
But they are third party and against privacy
