### ISSUE TITLE
sh.st

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#7712]
`http://sh.st/4XsNw` has a Prestitial Ad with Countdown

![image](https://user-images.githubusercontent.com/76880977/115595672-d8ec0b00-a2f4-11eb-9375-5866d9eba43d.png)
![image](https://user-images.githubusercontent.com/76880977/115595676-d984a180-a2f4-11eb-9e65-4cab90055445.png)

**Comment by ryanbr** [comment]
Can't be prevented unfortunately. If you need too, open an issue in Adguard repo.
