### ISSUE TITLE
windowslatest.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#7714]
### List the website(s) you're having issues:
`https://www.windowslatest.com/2021/04/21/windows-10-task-manager-is-getting-eco-mode-edge-integration/`

### What happens?

Empty advertisement placeholder
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/115611308-b9141180-a30b-11eb-8590-dd984f0fe45a.PNG)

</details><br/>
### List Subscriptions you're using:

Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List

### Your settings

- OS/version: Windows 10
- Browser/version: Edge 90, Firefox 88
- Adblock Extension/version: uBlock Origin 1.34.0

### Other details:

Adgaurd Base has this filter for it: 
"windowslatest.com##.td-ss-main-sidebar > aside.widget:has(:scope > h4 > span:has-text(/Advertisement|Deal/))"

**Comment by ryanbr** [comment]
Not really worth it tbh. 108 Characters for that..

**Comment by Yuki2718** [comment]
@ryanbr Please think again, `windowslatest.com##.ai_widget` is enough. The AG filter is too verbose.
