### ISSUE TITLE
es.listerine.com

### ISSUE THREAD

**Issue by 3dyd** [easylist/easylist#7721]
### List the website(s) you're having issues:

```
https://es.listerine.com
```

### What happens?

Browser loads only main page from that domain. All sub-requests to page assets, residing on the same domain, are blocked.

### Your settings

Brave 1.23.71 with no extra extensions.

Firefox 88.0 with uBlock Origin v1.35.0.

Both with default settings and up to date.

### List Subscriptions you're using:

Default subscriptions from Brave and uBO. I believe issue comes from EasyPrivacy.

### Other details:

Both Brave and uBO use CNAME uncloaking by default. Here is uncloaked CNAME for the subject:
```
% dig +short es.listerine.com | grep -E '[a-z]' | tail -1
nva-as-cluster10-1.lb.onelink-translations.com.
```

So, when, for example, page contains `<img src="logo.png">`, they translate this request to `https://nva-as-cluster10-1.lb.onelink-translations.com/logo.png` and treat it as third-party request. Therefore it becomes blocked by [the following rule](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt#L1691):
```
||onelink-translations.com^$third-party
```

Unfortunately all info I have found about it is this commit message (ec6f3778 in 2015):
```
A: http://it.delta.com/
```
But the thing is that Italian version of Delta is also powered by onelink-translations.com:
```
% dig +short it.delta.com | grep -E '[a-z]' | tail -1
nva-pci-as-delta01.lb.onelink-translations.com.
```
As I see, even now, in 2021, this page sends some requests directly to onelink-translations.com, not using the cloaked CNAME.

So, could it be that somebody spotted suspicious requests on Delta site to seemingly unrelated onelink-translations.com domain and it was blocked by mistake? I.e. that time it was not noticed that it.delta.com is actually served by this solution.

Ironically, this rule [was disabled](https://github.com/easylist/easylist/issues/5039#issuecomment-615717845) for Delta in uBO once CNAME uncloaking revealed a problem there. But it still remains to be relevant for all other sites powered by onelink-translations.com.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/9bd98fa9849b52ab2b0f8551fe47cb5796e4772f
