### ISSUE TITLE
Fragrantica.com

### ISSUE THREAD

**Issue by problem01** [easylist/easylist#7724]
### List the website(s) you're having issues:

https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Le-Male-430.html

### What happens?

Ads.

### List Subscriptions you're using:

uBlock default (includes easylist and easylist spanish)

### Your settings

- OS/version: Windows 10
- Browser/version: Edge 90.0.818.42
- Adblock Extension/version: uBlock Origin 1.34.0

**Comment by ryanbr** [comment]
I'm fine with this tbh
