### ISSUE TITLE
https://analyticsindiamag.com

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#7736]
### What happens?
`https://analyticsindiamag.com/the-role-of-statistics-in-the-era-of-big-data/` has ads
![image](https://user-images.githubusercontent.com/76880977/116010270-98192c80-a63b-11eb-9dca-9ae874181e32.png)
![image](https://user-images.githubusercontent.com/76880977/116010274-9ea7a400-a63b-11eb-8ab2-c03714af3b79.png)

**Comment by stephenhawk8054** [comment]
There's an ad at the top again
![image](https://user-images.githubusercontent.com/66517106/136884769-b1d4550c-5ea8-4481-8c86-71a5a7274e12.png)

Proposed filter:
`analyticsindiamag.com##a[target="_blank"][data-wpel-link="external"] > img`

**Comment by stephenhawk8054** [comment]
Update proposed filter:

```
||pressablecdn.com/wp-content/uploads/*/Praxis-GIF-AIM.gif$image,domain=analyticsindiamag.com
analyticsindiamag.com##[data-element_type="widget"]:-abp-has(a[href*="praxis.ac.in"])
```
