### ISSUE TITLE
Lot of dead records...

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#7743]
I have for some while now been running and testing the records within EasyList with PyFunceble with GHA in this repohttps://github.com/dns-test/EasyList And you can always see what it dead and what is alive by looking in the output/${lists-name}/{INACTIVE,INVALID}/list

Just be aware that the lists name probably will change to get a `.txt` extension in the future. See https://github.com/funilrys/PyFunceble/issues/235 by @DandelionSprout.

Just to mention óne list that need attention, then there is 5329 dead domains in 

https://github.com/dns-test/EasyList/blob/e4c40e229857de1b80c44bc3426d2abfb3215dce/output/easylist_adservers.txt/domains/INACTIVE/list#L5333

Hoping you will find this little work helpfull as I do.

**Comment by ryanbr** [comment]
That list shows it was generated on the 29th Jan

**Comment by spirillen** [comment]
Then they appears to have been dead since $DATE  :wink: and nothing new how been found dead in easylist_adservers.txt.

The GHA is running Every hour, so any newly found dead records should be automatically updated when found.

But each list are in separated folders under https://github.com/dns-test/EasyList/tree/master/output

Another example could be
https://github.com/dns-test/EasyList/tree/master/output/adult_adservers.txt/domains

![image](https://user-images.githubusercontent.com/44526987/116286528-9c565e80-a78f-11eb-8428-0ee6035676b3.png)

Commit https://github.com/dns-test/EasyList/commit/4fc099e41ffc27596914fcc8577bab4864c15f51

Here you'll see four new dead records
https://github.com/dns-test/EasyList/commit/4fc099e41ffc27596914fcc8577bab4864c15f51#diff-f5b8c45c4b16b6fb413db5e4b01d0444f240aa1d5d0e5b1f05286be5a0d06a40R60-R63

**Comment by ryanbr** [comment]
https://github.com/dns-test/EasyList/blob/master/output/easylist_adservers.txt/domains/INACTIVE/list#L20

Example, `344dea1d6d130a7e8e.com` or `3878896c72ed218.com` are not in Easylist. please review the list generation.

Saying we have dead domains, that dont actually exist in Easylist makes this issue report point less.

**Comment by spirillen** [comment]
Could they have been there within the past 180 days?

Because Any of these lists have never ever touched any other input sources than from this repo

If that isn't the case we will need to make a issue to @funilrys about a major error.

**Comment by ryanbr** [comment]
As stated, re-run the list generation. We do use PyFunceble and run it regularly.

**Comment by spirillen** [comment]
> As stated, re-run the list generation. We do use PyFunceble and run it regularly.

Will take a peak at it tomorrow, it ways past bedtime here now. But I have taken a note.

**Comment by ryanbr** [comment]
Closing @spirillen  re-open if you find issues.

**Comment by spirillen** [comment]
> Closing @spirillen re-open if you find issues.

That's fine, I'll take a deeper look into it, probably at the weekend as I should be able to test the script from my own (new fiber vs shitty adsl) then.

**Comment by spirillen** [comment]
Hey @ryanbr do the "dead" lists looks better now?

I have lowered the threshold to a couple of days.  Alternatively, what test string are you using for the current test you say you do? it is as easy as just plundering it into a PR :smirk: :wink:
