### ISSUE TITLE
False positive Wikipedia daily pageviews graph

### ISSUE THREAD

**Issue by NovemLinguae** [easylist/easylist#7744]
### List the website(s) you're having issues:

https://en.wikipedia.org/wiki/Talk:Big_lie

![image](https://user-images.githubusercontent.com/79697282/116235241-76d73f80-a712-11eb-9ad8-8d39646b00ec.png)

### What happens?

Graph does not load.

### List Subscriptions you're using:

EasyPrivacy, `
/pageviews/*$domain=~pageviews.toolforge.org|~stats.wikimedia.org|~tools.wmflabs.org`

### Your settings

- OS/version: Windows 7
- Browser/version: Chrome
- Adblock Extension/version: ubo dev

### Other details:

URL that is being blocked incorrectly is `
https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia.org/all-access/user/Big%20lie/daily/2020042500/2021042500`. The filter I mentioned above probably needs to be updated to include an exception for this URL pattern.

![image](https://user-images.githubusercontent.com/79697282/116236318-c36f4a80-a713-11eb-93fe-8cc517f7caf6.png)

**Comment by johnbeard** [comment]
This is still being blocked for me:

![2021-05-01_220209_850x283_screenshot](https://user-images.githubusercontent.com/5386578/116794935-f1181300-aac8-11eb-96ef-f35cb030f599.png)


@NovemLinguae is it working for you now? For example: https://www.mediawiki.org/wiki/Template:Graph:PageViews

**Comment by NovemLinguae** [comment]
> @NovemLinguae is it working for you now? For example: https://www.mediawiki.org/wiki/Template:Graph:PageViews

Both pages are working now. Looks like Khrin fixed MediaWiki for us. Thanks Krhin.

We'll have to keep reporting domains to whitelist in this thread as we run across them.

**Comment by inductiveload** [comment]
@Khrin, @NovemLinguae still being blocked for me (but I'm not sure why, because I see the whitelist as expected in the rule)

![2021-05-03_201749_839x309_screenshot](https://user-images.githubusercontent.com/466649/116922124-cf479900-ac4c-11eb-85a0-1c3c14148449.png)

**Comment by llacb47** [comment]
@inductiveload read `https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#domain-modifier`

**Comment by inductiveload** [comment]
Ah right, it's the domain the request is sent from. In that case we should whitelist every WMF site:
* wikibooks.org
* wikisource.org
* wikiversity.org
* wikispecies.org
* wikidata.prg
* wikinews.org
* wikiquote.org
* wikivoyage.org
* wiktionary.org
Might be easier just to whitelist the entire wikimedia.org REST API?
