### ISSUE TITLE
addoor.net

### ISSUE THREAD

**Issue by SMed79** [easylist/easylist#776]
https://github.com/easylist/easylist/blob/a733eb240d2ecf9f502a3a7edbaab509ddd2d97a/fanboy-addon/fanboy_annoyance_international.txt#L581

I suggest to move `addoor.net` to easylist adservers.

* https://i.imgur.com/dBQjpcxr.png
* https://forums.lanik.us/viewtopic.php?p=129504#p129504

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/de8c52d88e50ab74d3dacbc4a1bab21f044e7aca
