### ISSUE TITLE
nakanohito.jp is not a pure tracking server, and blocking it will break comment systems and chatbots.

### ISSUE THREAD

**Issue by hirorpt** [easylist/easylist#7760]
#### Example of the comment system
URL: `https://iphone-mania.jp/news-87019/`

EasyPrivacy on

<details><summary>Screenshot:</summary>

![block comment](https://user-images.githubusercontent.com/82331005/116772407-cfe40200-aa89-11eb-8f3c-6c2fed7bfd3c.png)
Unblock the coment system
</details>

Unblock the coment system
<details><summary>Screenshot:</summary>

![unblock comment](https://user-images.githubusercontent.com/82331005/116772511-8647e700-aa8a-11eb-8847-d45004578b88.png)

</details>

#### Example of the chatbot
URL: `https://www.inpit.go.jp/ `

EasyPrivacy on

<details><summary>Screenshot:</summary>

![block chat](https://user-images.githubusercontent.com/82331005/116772723-d3788880-aa8b-11eb-9fe3-d7ab3edeea7f.png)
</details>

Unblock the chatbot
<details><summary>Screenshot:</summary>

![unblock chat](https://user-images.githubusercontent.com/82331005/116772712-d07d9800-aa8b-11eb-92ca-7b7c0be6f3fd.png)
</details>

### List Subscriptions you're using:
uBO default + AGJPN

#### Other examples of websites which use the system:
Comment system: See below
Chatbot: `https://www.city.uji.kyoto.jp/`, `https://www.city.miyakonojo.miyazaki.jp/`, `https://jpdirect.jp/`
~~~
! Unblock comment system
! https://iphone-mania.jp/news-87019/
@@||cm-beacon.nakanohito.jp/cm/comment_list$xmlhttprequest
@@||cm-widget.nakanohito.jp/cm/$stylesheet,script
@@||cm-widget.nakanohito.jp/img/$image

! https://qoly.jp/
@@||cm-beacon.nakanohito.jp/at/ranking/$script

! https://www.itmedia.co.jp/business/articles/2104/28/news029.html
@@||cm-beacon.nakanohito.jp/cm/comment_count/$xmlhttprequest

! Unblock chatbot
@@||support-widget.nakanohito.jp/chatbot$stylesheet,script
@@||support-beacon.nakanohito.jp/widget/$xmlhttprequest
~~~

**Comment by ryanbr** [comment]
Sure. tried to review nakanohito.jp, but just too many trackers.
