### ISSUE TITLE
codefresh | Subscribe Box

### ISSUE THREAD

**Issue by Dentrax** [easylist/easylist#7763]
### List the website(s) you're having issues:

https://codefresh.io/kubernetes-tutorial/local-kubernetes-development-tilt-dev/

### What happens?

<img width="435" alt="Screen Shot 2021-05-02 at 11 57 18" src="https://user-images.githubusercontent.com/16493751/116807755-8ce36680-ab3d-11eb-937c-a98b9ef631cc.png">

(Bottom left corner)

### List Subscriptions you're using:

Easylist

### Your settings

<img width="452" alt="Screen Shot 2021-05-02 at 11 58 35" src="https://user-images.githubusercontent.com/16493751/116807783-bac8ab00-ab3d-11eb-84a4-6173f5e36f66.png">

- OS/version: `macOS 11`
- Browser/version: `Firefox 88`
- Adblock Extension/version: `uBlock Origin v1.35.0`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4a3fc6531a1ce86fdcbba1c3c9c4e0a075a9ec92
