### ISSUE TITLE
justonecookbook.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7765]
### List the website(s) you're having issues:

`https://www.justonecookbook.com/chicken-katsu-don/`

### What happens?

Large placeholder(s) partway into the article.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/116840050-d03ce400-abd4-11eb-90c1-97a4bc8103b9.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 90.0.4430.93 x64
- Adblock Extension/version: uBO 1.35.1b2 + IDCAC 3.3.0

### Other details:

I propose `##.adthrive`

![image](https://user-images.githubusercontent.com/22780683/116840090-f1053980-abd4-11eb-8ef2-f4652921dde8.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c6c7d59735a1954fe49f29ba1203c93f134f76d7
