### ISSUE TITLE
igorslab.de

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7766]
### List the website(s) you're having issues:

`https://www.igorslab.de/en/battleye-and-easy-anti-cheat-rgb-control-software-causes-anew-bans-and-accounts-blocks-that-make-games-worthless/`

### What happens?

The entire rightside bar consists of ads.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/116840050-d03ce400-abd4-11eb-90c1-97a4bc8103b9.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 90.0.4430.93 x64
- Adblock Extension/version: uBO 1.35.1b2 + IDCAC 3.3.0

### Other details:

I propose `igorslab.de##.herald-sidebar`

![image](https://user-images.githubusercontent.com/22780683/116840242-683acd80-abd5-11eb-856c-70a9a2915fc3.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e2e24879391925146a19f7e60c63258287cffabe
