### ISSUE TITLE
website.informer.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7767]
### List the website(s) you're having issues:

`https://website.informer.com/openadex.dk`

### What happens?

Placeholder bar with text.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/116840050-d03ce400-abd4-11eb-90c1-97a4bc8103b9.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 90.0.4430.93 x64
- Adblock Extension/version: uBO 1.35.1b2 + IDCAC 3.3.0

### Other details:

I propose `website.informer.com##div[align="center"]`

![image](https://user-images.githubusercontent.com/22780683/116841731-590a4e80-abda-11eb-9d63-b281102e3bc5.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/34e012d960440e35fea0c0e630c6c7a9dcb646e9
