### ISSUE TITLE
typing-speed.net

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7768]
### What happens?

Two placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/116840050-d03ce400-abd4-11eb-90c1-97a4bc8103b9.png)

### Your settings

- OS/version: Windows 10 20H2 x64
- Browser/version: Chrome 90.0.4430.93 x64
- Adblock Extension/version: uBO 1.35.1b2 + IDCAC 3.3.0

### Other details:

I propose:
```
##.advertising_horizontal_title
typing-speed.net##td + td[style="vertical-align: top"]
```

![image](https://user-images.githubusercontent.com/22780683/116842378-aa1b4200-abdc-11eb-837e-5aa1a1bfdaab.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/03fa7ccb546ec8f613bc21d333a2665504417f33
