### ISSUE TITLE
govtech.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7769]
### List the website(s) you're having issues:

`https://www.govtech.com/`

### What happens?

Very big placeholder on top.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/116840050-d03ce400-abd4-11eb-90c1-97a4bc8103b9.png)

### Your settings

- OS/version: Windows 10 20H2 x64
- Browser/version: Chrome 90.0.4430.93 x64
- Adblock Extension/version: uBO 1.35.1b2 + IDCAC 3.3.0

### Other details:

I propose `govtech.com##.Page-billboard`

![image](https://user-images.githubusercontent.com/22780683/116842591-47767600-abdd-11eb-982e-3e7e0732f4a7.png)

**Comment by ryanbr** [comment]
Doesn't stop the whitespace, would be pointless @DandelionSprout
