### ISSUE TITLE
happymag.tv

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7770]
### List the website(s) you're having issues:

`https://happymag.tv/cancel-culture-wins-macquarie-dictionarys-2019-word-of-the-year/`

### What happens?

Quite a few placeholders in their articles, incl. 4 on the example page.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/116840050-d03ce400-abd4-11eb-90c1-97a4bc8103b9.png)

### Your settings

- OS/version: Windows 10 20H2 x64
- Browser/version: Chrome 90.0.4430.93 x64
- Adblock Extension/version: uBO 1.35.1b2 + IDCAC 3.3.0

### Other details:

I propose `##.happy-inline-ad`, or alternately `##div[class$=-inline-ad]`

![image](https://user-images.githubusercontent.com/22780683/116842753-ea2ef480-abdd-11eb-9db0-c09a588205a0.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e616055317fe2ed54481801dbd07c79d568fd347
