### ISSUE TITLE
nascar.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7771]
### List the website(s) you're having issues:

`https://www.nascar.com/`

### What happens?

Various small but plentiful placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/116840050-d03ce400-abd4-11eb-90c1-97a4bc8103b9.png)

### Your settings

- OS/version: Windows 10 20H2 x64
- Browser/version: Chrome 90.0.4430.93 x64
- Adblock Extension/version: uBO 1.35.1b2 + IDCAC 3.3.0

### Other details:

I propose `##.nascar-ad-container`

![image](https://user-images.githubusercontent.com/22780683/116842865-5a3d7a80-abde-11eb-9c25-63a8cceea772.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/tree/72d63667531d9e5cd3f2f66f2381d954de348e4c
