### ISSUE TITLE
EasyPrivacy blocks all Nextjs pages named `/analytics`

### ISSUE THREAD

**Issue by mcornella** [easylist/easylist#7787]
### List the website(s) you're having issues:

Dummy site: https://analytics-demo-two.vercel.app/analytics

### What happens?

The EasyPrivacy list blocks requests to `/pages/analytics-$script`. Next.js makes requests to `/_next/static/chunks/pages/analytics-<hash>.js` when visiting a page at the `/analytics` route. In the dummy site this only blocks showing the Vercel logo at the bottom of the page, but on a real site with more complexity this breaks a big part of the page.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Ubuntu 20.04
- Browser/version: Chrome 90
- Adblock Extension/version: uBlock Origin / 1.34.0

### Other details:

![image](https://user-images.githubusercontent.com/1441704/117025277-0ffdeb80-acfb-11eb-9c30-d0637c405b90.png)

This rule was introduced in https://github.com/easylist/easylist/commit/33f0200a14f228e9463918b13fd05dd13c131f12.

**Comment by ryanbr** [comment]
It's not a recent commit, create a different file name? Basically any generic block in easyprivacy could possibly cause any issue. @mcornella
