### ISSUE TITLE
craveonline.com easylist false positive

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#78]
http://www.craveonline.com/music/514661-interview-getting-real-with-vinnie-paz-of-jedi-mind-tricks
http://www.craveonline.com/

Easylist causes top to be cut off. Probably there used to be a banner ad and it was hiding the element. But now, it cuts off the article title, etc.

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/1d1866979de64b95aec456dd49636ebe2d5e43ec
