### ISSUE TITLE
Bid window on hattrick.org not showing

### ISSUE THREAD

**Issue by d2n1w** [easylist/easylist#7801]
### List the website(s) you're having issues:

`hattrick.org`

### What happens?

If you want to buy or sell a player in hattrick.org the following bid window is not showing. 
![image](https://user-images.githubusercontent.com/79805812/117105308-06699780-ad7e-11eb-9cf8-aad5257c9d78.png)

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/79805812/117104947-53993980-ad7d-11eb-957f-7011403fafd5.png)

### Your settings

- OS/version: Windows 10 Home / 20H2 / 19042.928
- Browser/version: Mozilla Firefox / 88.0 (64 bit)
- Adblock Extension/version: uBlock Origin / 1.35.0

### Other details:

The frame works fine if I disable the option "EasyList Cookie" on the uBlock Origin Filter lists page

**Comment by ryanbr** [comment]
Still an issue @d2n1w ?

**Comment by dnsv** [comment]
@ryanbr This is still an issue. Let me know if you need additional delations on how to reproduce it.
