### ISSUE TITLE
Altibox.no - Broken functions (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#7805]
### Affected site:
`https://www.altibox.no/`

### Issue:
Various functions, like confirming your TV and/or internet subscription contents, doesn't work, due to a blocked cookie consent, which needs to be accepted!

(To reproduce, you need to be logged in to an account)

### Blocked assets:
```
https://policy.app.cookieinformation.com/*/altibox.no/*.js
https://policy.app.cookieinformation.com/uc.js
```
(+ one cosmetical)

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
```
###coiOverlay[role="banner"][style*="flex"]
||cookieinformation.com/*/*.js
```

### Possible fix:
```
- @@||policy.app.cookieinformation.com^$script,domain=eniro.se

+ altibox.no#@##coiOverlay[role="banner"][style*="flex"]
+ @@||policy.app.cookieinformation.com^$script,domain=altibox.no|eniro.se
```

### Temp fix:
```
altibox.no#@##coiOverlay[role="banner"][style*="flex"]
@@||policy.app.cookieinformation.com^$script,domain=altibox.no
```

### Other problem filters:
* ~~**AdGuard Annoyances filter** ( https://github.com/AdguardTeam/AdguardFilters/issues/82370/ )~~ _(FIXED)_
~~`||policy*.cookieinformation.com^$third-party`~~

* ~~**I don't care about cookies** (@kiboke)~~ _(FIXED)_
~~`policy.app.cookieinformation.com$domain=~kartor.eniro.se|~kart.gulesider.no|~kort.degulesider.dk|~map.krak.dk|~babysam.dk|~minaftale.dk`~~

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.2.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by kiboke** [comment]
Which cookie categories need to be accepted so that these functionalities can work properly?

**Comment by THEtomaso** [comment]
@kiboke:
Simply add `~altibox.no` to the existing rule, which I listed in the first post.

**Comment by ryanbr** [comment]
Still an issue @THEtomaso ?

**Comment by THEtomaso** [comment]
I don't know, because as I recall, the cookie consent only appears at the very last step, when you need to change certain aspects of your subscription.
..and I don't actually intend to change anything at this point.

However, since I see that `policy.app.cookieinformation.com/uc.js` is still present, I would assume that the rest remains too.

**Comment by THEtomaso** [comment]
@Khrin:
A new fix is need for '**EasyList - Cookie Notices**'.
Read my report here: https://github.com/uBlockOrigin/uAssets/issues/27748/

**Comment by Khrin** [comment]
@THEtomaso What's the issue? Is this still happening?

**Comment by THEtomaso** [comment]
It's been fixed in both '**AdGuard Cookie Notices filter**' and '**uBlock filters - Cookie Notices**' now, so I guess that will suffice:
https://github.com/AdguardTeam/AdguardFilters/commit/0f27a8d2263784bad18b785a7b5a10e0f7e45f14/
https://github.com/uBlockOrigin/uAssets/commit/70e944329730c6c0764fa7ef504357cb33545546/
