### ISSUE TITLE
Santander Empresas bank interface is broken with Easy Privacy

### ISSUE THREAD

**Issue by xfix** [easylist/easylist#781]
The website doesn't load with EasyPrivacy.

Reproducing doesn't require an account as bank interface is a JavaScript application which doesn't require authentication to download itself, it's sufficient to visit https://empresas3.gruposantander.es/www-empresas/, if it redirects it works as it should.

**Comment by Khrin** [comment]
Fixed https://github.com/easylist/easylist/commit/2853cd4f898b3234eb8b2a19bc8bfa02638f95a0
