### ISSUE TITLE
merriam-webster.com

### ISSUE THREAD

**Issue by kah0922** [easylist/easylist#7825]
### List the website(s) you're having issues:
`https://www.merriam-webster.com/word-games/up-and-down-words`

### What happens?
The game does not load.

### List Subscriptions you're using:

default lists
### Your settings

- OS/version: Windows 10
- Browser/version: FF Nightly 5/07
- Adblock Extension/version: uBlock Origin 1.351b2 

### Other details:

`||merriam-webster.com^$document,csp=script-src 'self' '*' 'unsafe-inline'` causes the game to not load and also completely breaks most functionality on the site.

**Comment by ryanbr** [comment]
Filter was removed. update lists.
