### ISSUE TITLE
filecr.com can detect ublock

### ISSUE THREAD

**Issue by panprc** [easylist/easylist#7829]
### List the website(s) you're having issues:
when you click the download button it will show "please disable adblocker"

### Your settings

- OS/version:  win 10
- Browser/version:  firefox nightly
- Adblock Extension/version:  ublock 1.35.1b2

**Comment by mendhak** [comment]
Please show the filter lists your uBlock is using.  I'm not seeing this problem when downloading Flickr images - a screenshot would be good here too.

**Comment by DandelionSprout** [comment]
I can't seem to reproduce this in uBO 1.37.3b2, be it with or without AdGuard Base turned on.
