### ISSUE TITLE
aksam.com.tr

### ISSUE THREAD

**Issue by SMed79** [easylist/easylist#783]
```
###reklam_buton
###reklam_center
###masthead
aksam.com.tr##a[href^="https://goo.gl/"]
aksam.com.tr##a[href^="https://ciftlikbank.com/"]
```
http\://www.aksam.com.tr/

**Comment by ryanbr** [comment]
Should these filters apply to Easylist?

**Comment by SMed79** [comment]
Perhaps the first 3 generic filters.

**Comment by ryanbr** [comment]
masthead seems too generic.

https://github.com/easylist/easylist/commit/8752131d7a0cfd1d931c5aa7a4acf9a8c5d59394
