### ISSUE TITLE
www.postoffice.co.uk

### ISSUE THREAD

**Issue by DesertBear** [easylist/easylist#7831]
### List the website(s) you're having issues:

`www.postoffice.co.uk`

### What happens?

Webpage has a tinted overlay over the page when Easylist Cookie filters are enabled.

Screenshot:
![Screenshot A](https://user-images.githubusercontent.com/27423064/117554703-2f757b00-b051-11eb-8e8d-ff2523a1174e.png)

### List Subscriptions you're using:

"ublock-filters",
"ublock-badware",
"ublock-privacy",
"ublock-abuse",
"ublock-unbreak",
"easylist",
"easyprivacy",
"fanboy-cookiemonster",
"ublock-annoyances",
"plowe-0"

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Microsoft Edge 90.0.818.56
- Adblock Extension/version: uBlock Origin v1.35.0

### Other details:

Problematic rules:
```
Filter         ###ensNotifyBanner
Filter list    EasyList Cookie 
Context        www.postoffice.co.uk
Type           dom
URL            https://www.postoffice.co.uk/
```
```
Filter         ##.ensNotifyBanner
Filter list    EasyList Cookie 
Context        www.postoffice.co.uk
Type           dom
URL            https://www.postoffice.co.uk/
```

Adding the below rule appears to get rid of the tinted overlay:
`postoffice.co.uk###ensBannerBG`

**Comment by ryanbr** [comment]
Looks fine now
