### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#7834]
![image](https://user-images.githubusercontent.com/83162792/117569489-9a18cc00-b0ce-11eb-8564-52c438d48161.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/251629e5fa6da80ee43910cf74e794efc98b7b60

**Comment by dportvine** [comment]
@ryanbr 

### List the website(s) you're having issues:

`https://www.investing.com/equities/teqnion`

### What happens?

<details>
<summary>Screen</summary>

![2023-05-30_205314](https://github.com/easylist/easylist/assets/111344219/dce7386a-080d-4741-8dc3-05b3447967bf)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![Glq29P1](https://user-images.githubusercontent.com/111344219/184830911-8739fa01-d9e9-436d-a4bb-a85257bba485.png)
</details>

### Your settings

- OS/version:  Windows 10 Pro 22H2 x64
- Browser/version:  Google Chrome (stable)
- Adblock Extension/version:  uBO (stable)
