### ISSUE TITLE
what3words.com

### ISSUE THREAD

**Issue by DesertBear** [easylist/easylist#7837]
### List the website(s) you're having issues:

`https://what3words.com/how-to-use-the-what3words-app`

### What happens?

It is not possible to scroll the webpage when Easylist Cookie filters are enabled.

### List Subscriptions you're using:

"ublock-filters",
"ublock-badware",
"ublock-privacy",
"ublock-abuse",
"ublock-unbreak",
"easylist",
"easyprivacy",
"fanboy-cookiemonster",
"ublock-annoyances",
"plowe-0"

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Microsoft Edge 90.0.818.56
- Adblock Extension/version: uBlock Origin v1.35.0

### Other details:

Problematic Rules:
```
Filter        ##.CookieNotice-Drawer
Filter list   EasyList Cookie 
Context       what3words.com
Type          dom
URL           https://what3words.com/how-to-use-the-what3words-app
```
```
Filter        ##div[class^="CookieNotice"]
Filter list   EasyList Cookie 
Context       what3words.com
Type          dom
URL           https://what3words.com/how-to-use-the-what3words-app
```

**Comment by ryanbr** [comment]
Re-check this @DesertBear
