### ISSUE TITLE
chinese "Growing" tracker 

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#7851]
growingio.com  gio.ren  datayi.cn growingio.cn giocdn.com growin.cn

![image](https://user-images.githubusercontent.com/75058881/117937740-e8310800-b338-11eb-9065-0ba7763505c9.png)
![image](https://user-images.githubusercontent.com/75058881/117937837-fbdc6e80-b338-11eb-83a5-fbbf8c8ef1c1.png)
![image](https://user-images.githubusercontent.com/75058881/117938364-891fc300-b339-11eb-907b-a714e858b4ca.png)

**Comment by ryanbr** [comment]
I think we're covered now.

**Comment by c2xusnpq6** [comment]
> I think we're covered now.

All domains of the same company:

![image](https://user-images.githubusercontent.com/75058881/118143577-16e4d680-b43e-11eb-8040-ad668743ecca.png)
