### ISSUE TITLE
up.timipc.com tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#7855]
`up.timipc.com` appears in my NextDNS log multiple times

i'm using mi gaming laptop btw

xiaomi laptop = mi laptop --> linked to --> timipc.com

xiaomi timi != tencent timi

I'm not sure, but you may be able to find what you need here:

https://c.mi.com/thread-2167081-1-0.html

https://www.mi.com/service/bijiben/drivers

https://www.mi.com/service/bijiben/drivers/game-2019

![image](https://user-images.githubusercontent.com/75058881/118154671-eb67e900-b449-11eb-839c-f9ee0c952b81.png)

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/118494046-4fddbd80-b754-11eb-8a32-bc5ba966a14e.png)

**Comment by spirillen** [comment]
Translation please...

Btw it's only drivers you link to and I doubt anyone would decompres them and translate the HEX code into domain name I what they are used for. I sugegst you provide more data about the domains IE use wireshark to inspect packects

**Comment by c2xusnpq6** [comment]
> Translation please...
> 
> Btw it's only drivers you link to and I doubt anyone would decompres them and translate the HEX code into domain name I what they are used for. I sugegst you provide more data about the domains IE use wireshark to inspect packects

The above link includes the Mi software that will be built into the Mi Notebook

I think if you analyze the above drivers and other software that comes with the Mi Notebook, you will find out whether it is really a tracker...😅
