### ISSUE TITLE
&advertorial= Rule blocks xmlhttprequest used in table filtering 

### ISSUE THREAD

**Issue by arjanpronk-kizitos** [easylist/easylist#786]
On https://linkpizza.com/marketplace?assignment_type=ADVERTORIAL&gender=MALE selecting any filter ( which fires a xmlhttprequest)  is blocked by the following rule =advertorial&

This occurs on other pages across the website as well, but this specific scenario is easily verified when logged out.

I've tried to find a good way to exclude it myself but a simple domain exclusion seems to be ignored.
The following filters have already been tried

`=advertorial&.$domain=~linkpizza.com`
`=advertorial&$domain=~linkpizza.com`

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/4983828a43ecc7c7596ae269ca1743ce2926ab59 Please verify if this fix works for you.

**Comment by arjanpronk-kizitos** [comment]
Works like a charm, thank you for your help.
