### ISSUE TITLE
[NSFW] cockmeter.com

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#7860]
### List the website(s) you're having issues:

`https://www.cockmeter.com/video/convincing-a-guy-from-the-street-to-let-his-cock-suck-for-money-6213.html`

### What happens?

Ad and ads placeholder to the right of the video

### List Subscriptions you're using:

![112381137-9bc63600-8cc0-11eb-9063-dc4a3be1e642](https://user-images.githubusercontent.com/11689349/118305431-f5273600-b4b5-11eb-9bff-b7f8531153d2.jpg)

### Your settings

- OS/version: Windows 10 
- Browser/version: Firefox Dev; Edge Dev
- Adblock Extension/version: uBlock Origin v1.35.2

**Comment by yokoffing** [comment]
- Ads still appearing: https://postimg.cc/KkYTzyqc
- There's also a pop-under ad when you click play on videos.

@Khrin @spirillen

**Comment by spirillen** [comment]
Ad 1 See 02ab9cf It's still to be merged

  - https://github.com/easylist/easylist/pull/8285

Ad 2 I leave the popup/under to the js guys, the spend less time than me to locate such troubled scripts
