### ISSUE TITLE
view.ricohtours.com

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#7863]
### List the website(s) you're having issues:

```
https://view.ricohtours.com/ea5de24e-352b-46ef-a4e7-d4c92c164624
```

### What happens?

On visiting the website, it triggers a request which reports some sort of fingerprint ID.

```
https://bbomwcm27nhalfwjvwzy6qbrim.appsync-api.us-west-2.amazonaws.com/graphql
```

Suggested filter

```
||bbomwcm27nhalfwjvwzy6qbrim.appsync-api.us-west-2.amazonaws.com^
```
### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/62358249/117891721-5204cf80-b2af-11eb-81f0-a35f8fd1d0ea.png)
![image](https://user-images.githubusercontent.com/62358249/117891766-68ab2680-b2af-11eb-8eab-e1228c03c65a.png)

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 89.0b12
- Adblock Extension/version: Ublock Origin 1.35.3b1

**Comment by ryanbr** [comment]
Not a tracker
