### ISSUE TITLE
gamersnexus.net

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7870]
### List the website(s) you're having issues:

`https://www.gamersnexus.net/guides/3494-amd-ryzen-3000-undervolting-offset-override`

### What happens?

Placeholder on the left, which continues to stay in the upper left when scrolling down the page.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/118347370-141fd980-b543-11eb-98f5-e7a261970db0.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 90.0.4430.212 x64
- Adblock Extension/version: uBO 1.35.3b1 + IDCAC 3.3.0

### Other details:

I propose `gamersnexus.net###notification`

![image](https://user-images.githubusercontent.com/22780683/118347883-a9709d00-b546-11eb-82ba-6148222125c1.png)

**Comment by Khrin** [comment]
I don't see it worthwhile to be added...
