### ISSUE TITLE
allmusic.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7871]
### List the website(s) you're having issues:

`https://www.allmusic.com/album/the-best-of-keane-mw0002584040`

### What happens?

Thin placeholder bar near the bottom.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/118347370-141fd980-b543-11eb-98f5-e7a261970db0.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 90.0.4430.212 x64
- Adblock Extension/version: uBO 1.35.3b1 + IDCAC 3.3.0

### Other details:

I propose `allmusic.com,allmovie.com##.footer-leaderboard`

![image](https://user-images.githubusercontent.com/22780683/118348001-9d390f80-b547-11eb-81f5-de162044e911.png)

**Comment by Khrin** [comment]
I couldn't find it, but I hope that's resolved in https://github.com/easylist/easylist/commit/e477966a79ec5fa848de07183218e17c485a7b44
