### ISSUE TITLE
tranzystor.pl

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#7876]
Plugin block use right click (most on images), maybe worth for "Fanboy's Annoyance"

```
/wp-content/plugins/image-watermark/js/no-right-click.js$script
```

I see a few filters very similar added in https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_annoyance_general_block.txt

**Comment by krystian3w** [comment]
Also maybe for EasyList Cookie:

`###tranzystorcookies`

**Comment by ryanbr** [comment]
`/no-right-click.$script` already in Fanboy Annoyances
