### ISSUE TITLE
imdb.com trackers

### ISSUE THREAD

**Issue by jordanelliott23** [easylist/easylist#7877]
url where tracker is found: 

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.imdb.com/)

tracker: https://www.imdb.com/api/_ajax/metrics/ops/

url where tracker is found: 
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.imdb.com/title/tt0293429/?ref_=hm_inth_tt_i_3)

tracker: https://m.media-amazon.com/images/G/01/imdbads/custom/test/index/js/ad-plugins/showadv2.js

**Comment by llacb47** [comment]
This is not a tracker. Read the script before reporting.

`https://m.media-amazon.com/images/G/01/imdbads/custom/test/index/js/ad-plugins/showadv2.js`

**Comment by jordanelliott23** [comment]
@llacb47 its a ad script same same difference.

**Comment by llacb47** [comment]
No it's not.

**Comment by ryanbr** [comment]
`https://m.media-amazon.com/images/G/01/imdbads/custom/test/index/js/ad-plugins/showadv2.js` is an anti-adblock check
