### ISSUE TITLE
youtube tracker

### ISSUE THREAD

**Issue by jordanelliott23** [easylist/easylist#7878]
url where tracker is found: 
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.youtube.com/)

(clear all browsing data then reload youtube to see it)

tracker: https://i.ytimg.com/generate_204

suggested filter: ||ytimg.com/generate_204 

i tried /generate_204$media and that doesn't work so the above has to be used.

**Comment by llacb47** [comment]
It's not a tracker. it returns no content and it's placed near the top of the page to make the browser get the IP address of that domain earlier during loading, so that the page's images load without waiting on DNS.

**Comment by jordanelliott23** [comment]
@llacb47 /generate_204 is a tracker if you look in the easyprivacy list. it just isnt blocked because its a media file. which isn't included in that filter

**Comment by llacb47** [comment]
IMO it shouldn't be in easyprivacy either.

**Comment by ryanbr** [comment]
We block the follow already, which seems to be related.

```
/csp_204?
/fp_204?
/gen204/*
/gen204?
/client_204?$image,other,ping,script
/csi_204?$image,other,ping,script
/gen_204?$image,other,ping,script
/generate_204$image,other,ping,script
```

**Comment by jordanelliott23** [comment]
> We block the follow already, which seems to be related.
> 
> ```
> /csp_204?
> /fp_204?
> /gen204/*
> /gen204?
> /client_204?$image,other,ping,script
> /csi_204?$image,other,ping,script
> /gen_204?$image,other,ping,script
> /generate_204$image,other,ping,script
> ```

yeah it wouldn't block with the $media filter modifier. it shows its a media file.
