### ISSUE TITLE
EasyPrivacy: USPS.com store broken

### ISSUE THREAD

**Issue by darkmorpher** [easylist/easylist#789]
Test link: https://store.usps.com/store/product/buy-stamps/lunar-new-year-year-of-the-dog-S_564804

Information for item order is blocked in `/metrics/metrics` ruleset, make an exception for `https://store.usps.com/media/js/metrics/metrics.js`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/23663e791e3b124e625ecc81ffc4ee4978d9c959
