### ISSUE TITLE
Britannica.com

### ISSUE THREAD

**Issue by admiral-pubhelp** [easylist/easylist#7890]
### List the website(s) you're having issues:
`britannica.com`

### What happens?
`britannica.com` copyright access control, donations and more broken by old CSP filter

### List Subscriptions you're using:

ABP filters: 202105171650
Easylist: 202105171650
AA: 202105171642

### Your settings

- OS/version: macOS 11.2.3
- Browser/version: Chrome Version 90.0.4430.212 (Official Build) (x86_64)
- Adblock Extension/version: ABP 3.10.2

### Other details:

Current CSP filter is likely breaking more stuff, but in particular it is breaking copyright access control and donations.  Problematic filter is here and should be removed: https://github.com/easylist/easylist/blob/665a27e237a737cbbe313bd6f90fc7f281e34ddb/easylist/easylist_specific_block.txt#L728

Same issue was previously caused by old CSP filter, reported and fixed on `merriam-webster.com` (sister site of `britannica.com`) on May 8, 2021. See below:
- Issue: https://github.com/easylist/easylist/issues/7825
- Fix: https://github.com/easylist/easylist/commit/8d274d23dd61ec08cf78038c0d8fbd7090783cbc

**Comment by ryanbr** [comment]
Sure removed. Was added due to adserver abuse. Would be readded if it occurs again.

**Comment by admiral-pubhelp** [comment]
Thx for fixing with https://github.com/easylist/easylist/commit/9df57034d460366694f235212252a935b136161b & the filter background.  Not sure if past CSP rule was added due to Yavli, Pagefair or another vendor; but will advise publisher and help them avoid in the future.

BTW, noticed an old webrtc block for Britannica & Merriam-webster too, just above the old CSP filters.  Guessing that was from past Pagefair abuse and may be ripe for some filter reduction/cleanup.
