### ISSUE TITLE
the-record.captivate.fm

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#7898]
### List the website(s) you're having issues:

```
https://the-record.captivate.fm/episode/when-pipelines-run-dry
```

### What happens?

When you play the podcast, it perdiocally does a POST with various paramaters such as listener id, player id, etc.

```
||stats.podcastwebsites.com^
```

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/62358249/117891721-5204cf80-b2af-11eb-81f0-a35f8fd1d0ea.png)
![image](https://user-images.githubusercontent.com/62358249/117891766-68ab2680-b2af-11eb-8eab-e1228c03c65a.png)

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 89.0b13
- Adblock Extension/version: Ublock Origin 1.35.3b3

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/161addd2b9edfd6325420434cdbc1d6ba693cd68
