### ISSUE TITLE
Why are generic rules with dimensions included?!?

### ISSUE THREAD

**Issue by benboit** [easylist/easylist#79]
Hello,

i was wondering why there are generic rules like "_300x600." included. This will break every Shop based on Shopware, since thumbnails having this size will always match this pattern.

No offense, i like easylist, but this seems like a lazy sledgehammer-method :D

**Comment by monzta** [comment]
> This will break every Shop based on Shopware, since thumbnails having this size will always match this pattern. 

Do you have some example sites maybe?

**Comment by benboit** [comment]
https://www.base.de/handys/apple/iphone-6s?farbe=spacegrau&speicher=64-gb&tarif=base-pur
https://onlineshop.haribo.com/haribo/fruchtgummi/56/goldbaeren

These are just 2 sites which show the pattern for the main picture on the detail page. In theory every combination of pixels is possible xxxXxxx because its configureable.

**Comment by febsn** [comment]
This is an issue for me as well, thumbnails of this size are hidden on one of my sites because their filename contains "_300x600_".

**Comment by felixfontein** [comment]
I have the same problem with at least one image on one of my sites. These dimension rules are really way too generic.

**Comment by Khrin** [comment]
Is there any actual example page where we can reproduce the issue?

**Comment by felixfontein** [comment]
Here's an example page: https://felix.fontein.de/t/

**Comment by febsn** [comment]
Another example: https://fian.at/de/artikel/fian-sommerakademie/

Django-Filer (used on that site) uses the _(width)x(height)_  syntax in its file naming.

**Comment by danielscsc** [comment]
This breaks copying files inside the AWS S3 console.
