### ISSUE TITLE
gamevicio.com

### ISSUE THREAD

**Issue by User0050** [easylist/easylist#7920]
### List the website(s) you're having issues:
`gamevicio.com`

### What happens?
Some ads that have not been blocked

gamevicio.com##.header-logo-extra
gamevicio.com##.hasBgApb:style(margin-top: 0px !important;)
gamevicio.com##[class^="bgApbContent"]
gamevicio.com##.slice-ad-footer

### List Subscriptions you're using:
Default uBlock Origin list

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome 90.0.4430.212
- Adblock Extension/version: uBlock Origin 1.35.2

**Comment by ryanbr** [comment]
We only support English sites in Easylist

**Comment by User0050** [comment]
Okay, thanks anyway for your work
