### ISSUE TITLE
ebay.com

### ISSUE THREAD

**Issue by jordanelliott23** [easylist/easylist#7922]
url: 
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.ebay.com/itm/223478964823?_trkparms=%26rpp_cid%3D608708408742f3a698213c81%26rpp_icid%3D608708408742f3a698213c80&_trkparms=pageci%3Ace7f76a7-bb36-11eb-90a3-f6ad3695ce1f%7Cparentrq%3A95a0064d1790a768d544370cfff68a90%7Ciid%3A1)

tracking and ad scripts:
https://ir.ebaystatic.com/rs/c/9527tracking/configuration.js?ts=5405710
https://p.ebaystatic.com/aw/pics/s.gif
https://ir.ebaystatic.com/pictures/aw/pics/s.gif
https://backstory.ebay.com/customer/v1/customer_image_service?pld=%5B%7B%22guid%22%3A%2295a006541790a768d5403679ffe5a19f%22%2C%22eventFamily%22%3A%22AUTO_TRACKING%22%2C%22agentVersion%22%3A%222.0.1%22%2C%22trackable%22%3A%7B%22trackableId%22%3A%2286361bb3-c1ac-4494-bf1e-d775b70e14fd%22%2C%22instanceId%22%3A%22https%3A%2F%2Fwww.ebay.com%2Fsignin%2Fid%22%2C%22description%22%3A%22Sign%20in%20or%20Register%20%7C%20eBay%22%2C%22entityId%22%3A%222547031%22%2C%22entityType%22%3A%22Page%22%7D%2C%22activity%22%3A%7B%22timestamp%22%3A1621713709181%2C%22category%22%3A%22Impression%22%2C%22type%22%3A%22VIEW.PAGE_LOAD%22%2C%22referer%22%3A%22https%3A%2F%2Fwww.ebay.com%2Fitm%2F223478964823%3F_trkparms%3D%2526rpp_cid%253D608708408742f3a698213c81%2526rpp_icid%253D608708408742f3a698213c80%26_trkparms%3Dpageci%253Ace7f76a7-bb36-11eb-90a3-f6ad3695ce1f%257Cparentrq%253A95a0064d1790a768d544370cfff68a90%257Ciid%253A1%22%2C%22details%22%3A%7B%22source%22%3A%22IFRAME%22%2C%22ePageId%22%3A%222547031%22%2C%22nPageId%22%3A%222547031%22%7D%2C%22viewportWidth%22%3A0%2C%22viewportHeight%22%3A0%7D%2C%22context%22%3A%7B%22utcOffset%22%3A7%2C%22userLang%22%3A%22en-US%22%2C%22userAgent%22%3A%22Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F90.0.4430.212%20Safari%2F537.36%20Edg%2F90.0.818.62%22%2C%22screenWidth%22%3A1280%2C%22screenHeight%22%3A1024%2C%22others%22%3A%7B%7D%7D%7D%5D&ct=1621713709183
https://www.ebay.com/gh/useracquisition?_trkparms=aid%253D1110006%2526algo%253DHOMESPLICE.SIM%2526ao%253D1%2526asc%253D20201210111314%2526meid%253Dccf9ef776415472c94c8ba713dfd9b29%2526pid%253D101195%2526rk%253D5%2526rkt%253D12%2526sd%253D223478964823%2526itm%253D264891758882%2526pmt%253D1%2526noa%253D0%2526pg%253D2047675%2526algv%253DSimplAMLv9PairwiseUnbiasedWeb&_trksid=p2047675.c101195.m1851&amdata=cksum%253A264891758882ccf9ef776415472c94c8ba713dfd9b29%257Cenc%253AAQAFAAACAG6Mhbm4EFyV6mjJosqVXeDuaGtayOzzCQyw5S9ZMj6qGfdgEGvc1tzS%25252FoXqr0fwZ3reMGcbYp7OAWJWxKJkrvbngvvTHabVy%25252BWnzjEOUKMYNMF25PqgnEfPjTEgSU%25252Bb6vhPc6q1sBX63hpx9fyGydVFmSB0zrNaFjmGy1fI7WgBhLCX1vRJOHih2wbqfemz9JmkKYoxB13Syb2M2OclxPFZwK4kTpDMrP2oe%25252F1ks1XlKR80fFKETa4RhuGW9hQQQ3TxsQ%25252BF62QrZE2FwGZtbZLxtppJSZDhxJWKojQw6zb61bgEyksAn6ukC%25252FVVPDDDT2ek2rg%25252F2c2WaA9z9hzHHFtTHq%25252BFSk1rPTyr8XA7ZoMZegjj7%25252FDHd0xCuVY4jsrF%25252FYyTm580auDGA1V%25252FlSdtzo2%25252B%25252BhjZFraQk0VJstLnygkmHwkQ1SFD4D04sALrpKKt47UNAjQg7xQFw2NqcSXc7YZMKjczHENOENVlsfpI55JsSHqWrvNi69hi2bK5a2o5%25252BFFxIk2JYcUtcb%25252FoYayCeIj2xyXDyLOauJk3dPdzjrb7lJZ%25252B18bH2t9ucLt8yqJRR3DgLdeT8TPebgi4jktztphLCO8Q7T5wuAHTvQyVJF8uN5kh2Dcs7Cy54DxxOtYXfExkTSb1ZgqrAShPc6csVKuwmj1I%25252F64I9tmQ562bgoTv%257Campid%253APL_CLK%257Cclp%253A2047675&correlation=operationId%3D2047675&show_optin_banner=true&v=2
https://secureir.ebaystatic.com/cr/v/c1/gh_show_ads.js

recommended filters:

||ebaystatic.com/rs/c/9527tracking/configuration.js
||ebaystatic.com/aw/pics/s.gif
||ebaystatic.com/cr/v/c1/gh_show_ads.js
||backstory.ebay.com/customer/v1/customer_image_service?pld=*AUTO_TRACKING
||ebaystatic.com/pictures/aw/pics/s.gif
||ebay.com/gh/useracquisition?_trkparms=aid

**Comment by llacb47** [comment]
Stop suggesting baits to be added. It's not helpful. Also those 1x1 images are not trackers and are needed for lazyloading.
