### ISSUE TITLE
atozmath.com

### ISSUE THREAD

**Issue by IThinkIAmCool** [easylist/easylist#7926]
It has an annoyance.

**Comment by IThinkIAmCool** [comment]
@ryanbr I can still see it.

**Comment by ryanbr** [comment]
What annoyance? not the most descriptive message. tl;dr follow the guidelines.

**Comment by krystian3w** [comment]
please look: https://github.com/uBlockOrigin/uAssets/issues/15338#issuecomment-1451835048

may needed unlock "`quantcast.mgr.consensu.org`" if banner means = big modal instead top small bar.
