### ISSUE TITLE
monzo.com (cookies)

### ISSUE THREAD

**Issue by soshial** [easylist/easylist#7929]
### List the website(s) you're having issues:
`https://monzo.com/i/current-account/`

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by krystian3w** [comment]
try:

```css
##div[class^="CookieAlert-module__container_"]
```

**Comment by soshial** [comment]
Cool, it worked! Will you be able to commit the changes?
