### ISSUE TITLE
monese.com (cookies)

### ISSUE THREAD

**Issue by soshial** [easylist/easylist#7930]
### List the website(s) you're having issues:
`https://monese.com/gb/en`

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by krystian3w** [comment]
Need move to supplement: https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_specific_uBO.txt

```css
monese.com##.cookie-banner__wrapper
monese.com##body.fixed:style(overflow: auto !important;)
```

**Comment by soshial** [comment]
Is this a list which is specific to uBlock Origin?
This code is supported only by uBO?

**Comment by krystian3w** [comment]
> "only uBO"

And a little for AdGuard  as long to block cookie/GDPR not used:
- `denyallow=`
- hard to translate `json-prune` scriptlet (AG use `[]`, but uBO use `*` for "wildcards")
- `redirect-rule=`
- `:upward(3)` used other place than at end of filter (due limitation in AdGuard in "Sizzle" https://github.com/AdguardTeam/ExtendedCss/issues/102)
-  hard to translate html filters: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#html-filtering-rules
-  more lack of support uBO syntax in AG I don't remember.

Maybe some help hide cookies/GDPR in Brave Adblock too (if property convert `+js(` or `:style(` filters.





As

**Comment by soshial** [comment]
After applying your changes, it worked. Thanks!
Can we add this code to uBO list?
