### ISSUE TITLE
allsmo.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#7937]
![image](https://user-images.githubusercontent.com/84580704/119852249-cc705900-bf17-11eb-8f2a-455d3bf1a69a.png)

Not caused do to uBO filters, I cancelled `@@||allsmo.com^$ghide` on my side.

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84580704/119852438-f6c21680-bf17-11eb-94c5-d420a959e31d.png)
