### ISSUE TITLE
Opensource Authedminer ^^

### ISSUE THREAD

**Issue by TriMoon** [easylist/easylist#794]
To those that use and/or develop Authedminer:
> As [stated by ShiningBomb](https://github.com/easylist/easylist/issues/710#issuecomment-345116490)
Listen, if you succeed too kill coinhive, they might abandon and release them as open source and now everyone can run their own 'coinhive' with their own custom domain. No way adblock can stop this. This is different than ads that have to be centralized, coin mining is a decentralized game. The end game is on us doesn't matter how hard your efforts will be. So why not do yourself a favor by unblocking it?

Maybe that's the **ONLY** way for it to be unblocked, and imho indeed only way it should be...
Because as now afaikt it's currently a [wasm](http://webassembly.org/) file, with **no-way** to check what it actually does...

**Comment by ryanbr** [comment]
Using threats won't get action, stop harvesting people's cpus. 

And if it comes down to it, we'll just block it on per site basis. I have no issues here.
