### ISSUE TITLE
Novinky.cz being broken

### ISSUE THREAD

**Issue by WalrusInAnus** [easylist/easylist#797]
Can you check what makes the above mentioned site display broken with Easylist active please?
![capture](https://user-images.githubusercontent.com/17233430/34391364-6a6ecdbc-eb45-11e7-9092-87ede853091a.PNG)

**Comment by doktornotor** [comment]
Not just novinky.cz, the evil `||dopc.cz^$third-party` part of the above-referenced commit breaks much more.

**Comment by ryanbr** [comment]
has been fixed

**Comment by WalrusInAnus** [comment]
Not fixed at all. How did you figure it was?
[Novinky.cz  – nejčtenější zprávy na českém internetu.zip](https://github.com/easylist/easylist/files/1631210/Novinky.cz.nejctenejsi.zpravy.na.ceskem.internetu.zip)

**Comment by ryanbr** [comment]
The filter in question was removed. unless there is another issue.

**Comment by WalrusInAnus** [comment]
There most probably is, but I have no idea how to find out :(
