### ISSUE TITLE
Sendbird.com being marked as tracker

### ISSUE THREAD

**Issue by tylerhammer** [easylist/easylist#7986]
### List the website(s) you're having issues:
```
sendbird.com
```

### What happens?

Websocket to chat is blocked due to being flagged as tracker.

### Your settings

- OS/version: Windows 10, Mac OSX 11.3
- Browser/version: Chrome Version 90.0.4430.212 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin v1.35.2

### Other details:

It looks like Sendbird was flagged as a tracker for Patreon when in reality, Sendbird powers Patreon's chat service. 
https://github.com/easylist/easylist/commit/6bb305cb40e4569a90ca6fdb6eaf94f50ad5cc10#diff-660ac35bad3047b69417687a0169bea3b9f93ff1710509c7c0fa63deea7f109e

**Comment by Stevoni** [comment]
+1 

This caused a production outage this morning since my company uses uBlock Origin for all OS installations and we were unable to respond to customer communication.
