### ISSUE TITLE
Pearson login false positive

### ISSUE THREAD

**Issue by Mr-Dead** [easylist/easylist#799]
Hello and thank you for your service towards a better internet!  The following rule prevents a pop up ( I know, pop ups are ridiculous in this day/age) allowing students to log in.

@@\|\|e2e-comms.pearson.com/osbrowserchecker/prd/thirdPartyCookie.html?mode=getuser-defined
--

Thanks for your consideration in this manner.

**Comment by Khrin** [comment]
Hi, how can I reproduce the issue?

**Comment by Mr-Dead** [comment]
Hello, Khrin!  Thank you for the expedient reply to my query.  I apologize for not being more detailed in my  original post.

Go to url "https://www.pearsonmylabandmastering.com/northamerica/myitlab/"

![mylab login](https://user-images.githubusercontent.com/2031616/34399993-6095ef7a-eb52-11e7-9ac2-3ef0e45454e3.jpg)

Open your favorite DOM inspector and then select "Sign In"

![mylab login adlock error](https://user-images.githubusercontent.com/2031616/34400033-c830cbbe-eb52-11e7-81a0-9840c4658d11.jpg)


Verify my original post when the request
 "https://e2e-comms.pearson.com/osbrowserchecker/prd/thirdPartyCookie.html?mode=get" 
by domain "www.pearsonmylabandmastering.com" 
is blocked by filter "/thirdpartyCookie."
 within the origin list ""EasyPrivacy""

Be advised that your browsers popup blocker may initially prevent the request altogether.  Thank you for considering my query!

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/dfdd9ca75cc52a19121f9338aa7b61782b6b8b67 Should be fixed now. Please update Easyprivacy.
