### ISSUE TITLE
licensing.bitmovin.com

### ISSUE THREAD

**Issue by ravloony** [easylist/easylist#7999]
Hello,

I'm writing on behalf of Bitmovin to enquire about the possibility of removing `licensing.bitmovin.com` from this list (https://github.com/easylist/easylist/blob/5c8aa50651f431a64cb79f72f714714292dfe6bb/easyprivacy/easyprivacy_thirdparty.txt#L1176).  It is not in any way a tracking url (ie. we do none of "tracking or monitoring, UA/IP/Geo checks, browser detection, analytics, telemetry, linking to third-partys, pixels, referrers, fingerprinting, event/perf logging etc."), but simply allows us to charge our customers for their usage. Having this url on this list is costing Bitmovin money at no benefit to your users, and may force Bitmovin to move to a more complex off-by-default model, which would cause playback breakage on every site where an adblocker using this list is enabled.

Feel free to get in touch with Bitmovin directly around this issue.

Best regards,
Tom Macdonald

**Comment by spirillen** [comment]
I would second this IF you in exchange would publish all domains used for analytics/tracking/spying (Choose the right word for your self :smiley: )

![image](https://user-images.githubusercontent.com/44526987/120523959-d17d4e80-c3d6-11eb-9b65-bd23d9786b69.png)


Currently known is
```python
analytics-ingress-global.bitmovin.com   CNAME . ; Tracking
```

![image](https://user-images.githubusercontent.com/44526987/120524141-02f61a00-c3d7-11eb-8777-b64f4426b933.png)
![image](https://user-images.githubusercontent.com/44526987/120524158-0b4e5500-c3d7-11eb-922c-0985f1a6b2b4.png)

**Comment by ryanbr** [comment]
Looking from the orginal [commit](https://github.com/easylist/easylist/commit/5369b67d41e5ef6a01421ad6e4a261d8d0fa7146): and sample `https://www.americanprogress.org/issues/disability/news/2021/05/27/500030/recognizing-addressing-housing-insecurity-disabled-renters/`

It doesn't break the page from what I see, I would need to see where this breaks for the enduser.

**Comment by ravloony** [comment]
> I would second this IF you in exchange would publish all domains used for analytics/tracking/spying (Choose the right word for your self  )
> 
> ![image](https://user-images.githubusercontent.com/44526987/120523959-d17d4e80-c3d6-11eb-9b65-bd23d9786b69.png)
> 
> Currently known is
> 
> ```python
> analytics-ingress-global.bitmovin.com   CNAME . ; Tracking
> ```
> 
> ![image](https://user-images.githubusercontent.com/44526987/120524141-02f61a00-c3d7-11eb-8777-b64f4426b933.png)
> ![image](https://user-images.githubusercontent.com/44526987/120524158-0b4e5500-c3d7-11eb-922c-0985f1a6b2b4.png)

Hi,

TBH I'm not aware of any others :sweat_smile: . Maybe some internal testing urls, but I would not publish those anyway.

However, it doesn't change anything to my argument that the URL I originally referred to is not a tracking link, only a licensing endpoint, and therefore has no place on this list in the first place. Also, we don't want to have to break pages for adblock users.

I can make a PR if you like.

Best regards,
Tom

**Comment by ravloony** [comment]
> Looking from the orginal [commit](https://github.com/easylist/easylist/commit/5369b67d41e5ef6a01421ad6e4a261d8d0fa7146): and sample `https://www.americanprogress.org/issues/disability/news/2021/05/27/500030/recognizing-addressing-housing-insecurity-disabled-renters/`
> 
> It doesn't break the page from what I see, I would need to see where this breaks for the enduser.

That commit has nothing to do with Bitmovin, and that page doesn't load our player. Wrong issue maybe?

**Comment by ravloony** [comment]
> > Looking from the orginal [commit](https://github.com/easylist/easylist/commit/5369b67d41e5ef6a01421ad6e4a261d8d0fa7146): and sample `https://www.americanprogress.org/issues/disability/news/2021/05/27/500030/recognizing-addressing-housing-insecurity-disabled-renters/`
> > It doesn't break the page from what I see, I would need to see where this breaks for the enduser.
> 
> That commit has nothing to do with Bitmovin, and that page doesn't load our player. Wrong issue maybe?

@ryanbr I've updated the link in my original message to a permalink. Apologies for the confusion.

**Comment by ryanbr** [comment]
@ravloony   A few questions.

1. The [original commit](https://github.com/easylist/easylist/commit/916f6008f0dd75e3bfbf7e6480047b105e86e9ea)   is from 2017, why now? its been 4 years. 
2. Found another url using it `https://era-global.org/`  wasn't able to see what broke when we blocked `licensing.bitmovin.com`
3. Website example of actual breakage?

**Comment by ravloony** [comment]
Hi,

> @ravloony A few questions.
> 
> 1. The [original commit](https://github.com/easylist/easylist/commit/916f6008f0dd75e3bfbf7e6480047b105e86e9ea)   is from 2017, why now? its been 4 years.
Two reasons:
- We are growing
- Adblocker usage is growing

Due to these dynamics, the opportunity cost has got to a point where we can no longer ignore it.
> 2. Found another url using it `https://era-global.org/`  wasn't able to see what broke when we blocked `licensing.bitmovin.com`
Right now, nothing breaks. But in future versions of the player we will be more strict about licensing, so those customers who upgrade (so especially the large ones) will see breakage.
> 3. Website example of actual breakage?
None yet. I am giving you advance warning of it potentially happening, should we need to go this route.

Best regards,
Tom

**Comment by ryanbr** [comment]
@ravloony  as long as bitmovin keeps the impressions/analytics scripts separate, then this is fine.

Removed `||licensing.bitmovin.com` and target on the the impressions tracking script.

https://github.com/easylist/easylist/commit/5e5338fe8bf59cd10884f1dcc3023172b88387b0

**Comment by ravloony** [comment]
Thanks!

**Comment by ravloony** [comment]
@ryanbr I missed this before, but the call to `/impressions` is what allows us to count the number of plays, and is also directly related to our revenue. It is not tracking either - we do not and will not gather any client-side data. This should also be removed from the list.
