### ISSUE TITLE
songmix.in - New Issue

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#80]
Hi,

When i open this site on mobile then "Download Now" " Download Song" is showing, when you click it then it is downloading a .apk file.

`http://songmix.in/download/2417/resham_ka_rumaal_dj_remix_-_dj_rahul_and_dj_vikas.html`

To Block "Download Now" " Download Song" the working filter are:

`songmix.in###mainDiv > .fshow > .fInfo > .bestsss:nth-of-type(1) > .best > b > a[href="http://down3.ucweb.com//down1/chenyf/nicehd/com.nineapps_v2.1.7.1_android_(Build16012010).apk"]`

`songmix.in###mainDiv > .fshow > .fInfo > .bestsss:nth-of-type(4) > .best > b > a[href="http://bit.ly/1F4745T"]`

Please update the above filter in EasyList

Thanks a lot for your time and support

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/d4bdfec101f3cdbfbeaf8a1c5c83ecd403a34d28
