### ISSUE TITLE
foodpanda tracking order page ads

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8006]
```
https://tw.fd-api.com/api/v5/partnerships-ads-api/ads?language_id=6&page=postorder

||fd-api.com/api/v5/partnerships-ads-api^

tw.fd-api.com --> tw = taiwan
```

`贊助` = `sponsor`

![image](https://user-images.githubusercontent.com/75058881/120556445-17660100-c42f-11eb-954a-c7152fe49714.png)

![image](https://user-images.githubusercontent.com/75058881/120556452-192fc480-c42f-11eb-98af-407b6f2c3260.png)

**Comment by c2xusnpq6** [comment]
You can see from the image above that the request URL contains the keyword `partnerships-ads`

**Comment by ryanbr** [comment]
Need better directions to replicate issues, otherwise any further suggestions will be ignored and closed.

**Comment by c2xusnpq6** [comment]
```
https://tw.fd-api.com/api/v5/partnerships-ads-api/ads?page=postorder&next_gen_version=v2&language_id=6
```

![Screenshot_20210709-063117_Trebuchet.png](https://user-images.githubusercontent.com/75058881/124998705-7565b400-e07f-11eb-877d-44f1ddd9cc09.png)
