### ISSUE TITLE
Buycheaprdp.com

### ISSUE THREAD

**Issue by chandrakantkr91** [easylist/easylist#8008]
### List the website(s) you're having issues:
`https://buycheaprdp.com/`

### What happens?
The website subdomains are getting blocked on the website. We are not displaying a single ad on our website.
Our subdomain links are not working. Support links, order buttons, contact forms, and knowledge base links are not working.
```
https://buycheaprdp.com/billing/
https://buycheaprdp.com//support/
```
Screenshot of the broken webpage:
[http://prntscr.com/13tobla](url)

### List Subscriptions you're using:
EasyList

### Your settings

- OS/version:   Windows 10 Pro 20H2
- Browser/version: Version 91.0.4472.77 (Official Build) (64-bit)
- Adblock Extension/version: Version number 3.11

### Other details:
Screenshot of the broken webpage:
[http://prntscr.com/13tobla](url)

The website URL is listed below list.
[https://easylist.to/easylist/easylist.txt](url)

**Comment by ryanbr** [comment]
Has been resolved. Closing.
