### ISSUE TITLE
[NSFW] rule34.xxx

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8021]
### List the website(s) you're having issues:

`https://rule34.xxx/index.php?page=post&s=list&tags=kim_possible+-shego&pid=126`

### What happens?

Ads on top and often also on bottom.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/120867739-d4bd3980-c592-11eb-9d43-9e2f565fc503.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.77 x64
- Adblock Extension/version: uBO 1.35.3b7 + IDCAC 3.3.0

### Other details:

I propose:
```
rule34.xxx###post-list > .content > a
rule34.xxx##.content > .horizontalFlexWithMargins
```

Screenshot: `https://thumbs2.imgbox.com/70/cd/e9EU9gKD_t.png`

**Comment by slayerduck** [comment]
kanako.store is rule34's official store, selling its own t-shirts/stickers/etc. This counts as self promotion and should not be blocked. The ad is only 90 pixels high, and shows mostly on the footer. This ad also follows the anti-adblock easylist policies.

**Comment by DandelionSprout** [comment]
Speaking as a non-team-member, I thought `https://buymyshit.moneygrubbingwhore.com/index.php?page=products&s=list` was their official store that sold T-shirts? As evidenced by this self-promo that isn't blocked: 
![image](https://user-images.githubusercontent.com/22780683/126048688-e06c7a37-c151-4774-a9b1-13e13ad5ed00.png)

In comparison, I had to dig considerably deeper before seeing any mention of `rule34.xxx` on `kanako.store`, namely at `https://kanako.store/pages/about-us`. I'll ask the EasyList team on Slack about what they think about this matter.

**Comment by slayerduck** [comment]
> 
> 
> Speaking as a non-team-member, I thought `https://buymyshit.moneygrubbingwhore.com/index.php?page=products&s=list` was their official store that sold T-shirts? As evidenced by this self-promo that isn't blocked:
> ![image](https://user-images.githubusercontent.com/22780683/126048688-e06c7a37-c151-4774-a9b1-13e13ad5ed00.png)
> 
> In comparison, I had to dig considerably deeper before seeing any mention of `rule34.xxx` on `kanako.store`, namely at `https://kanako.store/pages/about-us`. I'll ask the EasyList team on Slack about what they think about this matter.

We got two vendors, the footer ad you're mentioning rotates between one store that just sells one t-shirt and kanako store that sells more rule34 goodies `https://kanako.store/collections/sfw-collection` and other adult toys. To give additional clarity we have adjusted our about page on kanako store just now to mention its our official store if it wasn't clear enough already.

I'll just tag ryanbr since he committed it 
@ryanbr
