### ISSUE TITLE
gayemagazine.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8028]
### List the website(s) you're having issues:

```
https://www.gayemagazine.com/post/photographer-launches-boys-can-be-princesses-too-campaign-social-media-reacts
https://www.gayemagazine.com/
```

### What happens?

Various placeholders; most noticeably some broken ad embeds on top of the pages after ~8sec.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/120867739-d4bd3980-c592-11eb-9d43-9e2f565fc503.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.77 x64
- Adblock Extension/version: uBO 1.35.3b7 + IDCAC 3.3.0

### Other details:

I propose:
```
gayemagazine.com#?#div[id^=comp-][class^=_]:not([style]):-abp-has(g, iframe[title*=adsense i])
gayemagazine.com#?#div[id^=viewer-]:-abp-has(iframe[title^=remote])
```

(Yes, such complicated-looking entries really are necessary for that site.)

![image](https://user-images.githubusercontent.com/22780683/120870776-17cedb00-c59a-11eb-90f2-76b968a9ecdc.png)

**Comment by spirillen** [comment]
Would also add these rules (On freshly updated rules sets)

```
gayemagazine.com###POPUPS_ROOT
gayemagazine.com##.blog-header-background-color
gayemagazine.com###viewer-e0jv3
gayemagazine.com###viewer-9qjpf
gayemagazine.com###viewer-1un8i
gayemagazine.com###viewer-fdbou
```

![image](https://user-images.githubusercontent.com/44526987/120939091-833db780-c716-11eb-97de-f39db9e2947a.png)


Browser = tor
