### ISSUE TITLE
loom.com

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#8055]
### List the website(s) you're having issues:

```https://www.loom.com/share/55aa104db8d649f1aa622b137ed01cfa```

### What happens?

Loom seems to be proxying `segment.io` requests view their own domain to circumvent blocking by ad blockers.

```https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/custom-proxy/```

They also seem to have an option to selfhost

```https://github.com/segmentio/segment-proxy```

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/62358249/119989341-f9c41200-bfbe-11eb-9b99-b716402ca812.png)

### Your settings

- OS/version: Arch Linux
- Browser/version:  Firefox 89.0
- Adblock Extension/version: Ublock Origin 1.35.3rc1

### Other details:

Endpoints
```
https://evs.sgmt.loom.com/yhPeelcEJD/eejxbDiFfK.min.js
https://api.sgmt.loom.com/v1/i
https://api.sgmt.loom.com/v1/m
```

Suggested filters

```
||evs.sgmt.loom.com^
||api.sgmt.loom.com^
```
or
`sgmt.loom.com^`

Also view count tracking endpoint call. Not sure if they are considered tracking

```
||loom.com/v1/videos/*/view
```

**Comment by ryanbr** [comment]
Blocking the first script, prevents the others from loading. But yes event/perf tracking.
