### ISSUE TITLE
interads.pl

### ISSUE THREAD

**Issue by mateo10009992** [easylist/easylist#8056]
Hello,

I realised that AdBlock is blocking my website because ,,ads" in domain name. How can I solve this problem?

This is how look like my website where I turned off adblock:

<img width="1196" alt="Zrzut ekranu 2021-06-7 o 18 01 26" src="https://user-images.githubusercontent.com/85509019/121053008-33fd9280-c7bb-11eb-8e94-15628fab6809.png">

And when I turned on:

<img width="1284" alt="Zrzut ekranu 2021-06-7 o 18 02 03" src="https://user-images.githubusercontent.com/85509019/121053059-411a8180-c7bb-11eb-8fb3-f3b4ef3dbe3a.png">

**Comment by mateo10009992** [comment]
Can you remove: /interads. from the block list?

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/017cff4c1beab223f0fa895386b6f0d1adc43cd2
