### ISSUE TITLE
mylead.global/sl

### ISSUE THREAD

**Issue by myleadd** [easylist/easylist#8058]
Hello,
filters: Easylist
entry: MyLead.Global/sl

Using:
Google Chrome/Opera
AdBlock/Adblock Plus

MyLead.Global/sl/ is used only for analytical purposes. The presence of a domain on the list creates huge problems for MyLead.

For example, materials on subpages are blocked, which are not advertising - they are information. For example, https://www.businessofapps.com/affiliate/mylead/.

No filters: https://i.postimg.cc/kMcC0kW3/Screenshot-1743.png
With filter: https://i.postimg.cc/mk8G7HT2/Screenshot-1744.png
The logo disappears, the link will disappear on the right and the large artwork is redirected after clicking.

I would be very grateful for the possibility of unlocking the domain and removing an entry from EasyList.

**Comment by spirillen** [comment]
```css
||mylead.global^$third-party
```

```shell
printf 'mylead.global^$third-party' >> easylist/easylist_adservers.txt
printf 'mylead.global^$third-party' >> easyprivacy/easyprivacy_trackingservers.txt
```

https://mypdns.org/my-privacy-dns/matrix/-/issues/2456 (AdWare, Tracking)

**Comment by ryanbr** [comment]
Looks fine here.
