### ISSUE TITLE
simplyhired.com

### ISSUE THREAD

**Issue by jamesdwilson** [easylist/easylist#8066]
### List the website(s) you're having issues:
`https://simplyhired.com`

### What happens?

The site is completely blocked.  I was hoping for the site to load and any privacy-invading scripts or ads would be blocked instead of the whole site.
### List Subscriptions you're using:

EasyList
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by spirillen** [comment]
Try update your filter as I can't reproduce the issue

![image](https://user-images.githubusercontent.com/44526987/128776869-bbb2e881-009c-4638-89b0-339e38c8bbee.png)

**Comment by ryanbr** [comment]
Looks good now
