### ISSUE TITLE
rapidtables.com (cookies)

### ISSUE THREAD

**Issue by Gitoffthelawn** [easylist/easylist#8068]
### List the website(s) you're having issues:

https://www.rapidtables.com/web/color/red-color.html  (cookies)

**Comment by Gitoffthelawn** [comment]
I submitted this issue report and others nearly 4 months ago.  None of the issues I reported have received any response.  Is this the correct place to submit issue reports?

**Comment by ryanbr** [comment]
Not seeing it, unless you can suggest an element?

**Comment by ryanbr** [comment]
Closing, still not seen. Only a link.
