### ISSUE TITLE
adguard tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8073]
adguard webpage (https://adguard.com/en/license.html) --> linked to --> https://adguard.com/-/event/

```
||adguard.com/-/event^
or
||adguard.com/-/event/
```

![image](https://user-images.githubusercontent.com/75058881/121598313-49e9ac80-ca74-11eb-8098-66a4c74f6012.png)

![image](https://user-images.githubusercontent.com/75058881/121598447-684fa800-ca74-11eb-84a0-420f5d9ee0b2.png)

**Comment by martinez-spa** [comment]
@ryanbr 

AdGuard's official "Account Confirmation" e-mail has a tracker. Please block it. It should be handled in EasyPrivacy.

```
Full URLs
https://email-opn.adguard.com/open/*.gif
https://adguard.com/open/*.gif
```

To reproduce, go to `https://auth.adguard.com/registration.html` and create an AdGuard account. Then open the account confirmation email.

<details>
 <summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/106003406/169678708-57b96808-004e-4c0e-ae34-4120aef2b7ea.png)


</details>
