### ISSUE TITLE
redventures.io [easylist] [breakage]

### ISSUE THREAD

**Issue by Manderson566** [easylist/easylist#8077]
Dispute resolution.

### Filter affected: easylist ->` redventures.io^$third-party`
https://github.com/easylist/easylist/blob/3249974eb85dde7bfb274b7539edf3ad1aefc9b1/easylist/easylist_adservers.txt#L13616

### 1st/3rd-party sites affected:
`app.coverage.com`, `bankrate.com`
Core functionality is broken on these sites, but **RedVentures owns many properties including these that could be greatly impacted by this**.

 
### How is it broken?
If you visit `app.coverage.com` the entire flow is broken due to the backend API being behind a `redventures.io` domain.
To see the breakage go to `app.coverage.com/#/complete-profile` Click "Get Started" and proceed to the end of the flow. Once you finish the last question and click `View Policy Assessment` the site will attempt to `POST` to a `redventures.io` domain and be blocked. All other Http requests to redventures.io are also blocked. 

Something similar is happening on `bankrate.com` as well as other RedVentures properties.

### Description why it should be removed:
RedVentures owns the properties mentioned above as well as many other properties where `redventures.io` is critical to the core infrastructure. It is paramount for us to get this resolved as quickly as possible. If you need any other information please don't hesitate to reach out.

**Comment by devmandew** [comment]
Hello has this pull request been completed?

**Comment by devmandew** [comment]
Do we have a current update on this?

**Comment by ryanbr** [comment]
Closing.
