### ISSUE TITLE
NSFW: gigapornmovies.com

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#8078]
### List the website(s) you're having issues:
`http://gigapornmovies.com/step-sister-will-get-a-creampie-and-facial-whereas-enjoying-a-sport-eva-elfie/`

### What happens?
Videos not playing, but the issue is non-persistence as ie `http://gigapornmovies.com/teencurves-large-booty-blonde-barely-legal-teen-will-get-oiled-and-banged/` is playing. 

Both url relay on `https://www.youporn.com/embed/*`

![image](https://user-images.githubusercontent.com/44526987/121715178-dd57c780-cade-11eb-885e-6880f1c8269b.png)

![image](https://user-images.githubusercontent.com/44526987/121715226-e8aaf300-cade-11eb-85de-4f440acfc3b4.png)

### List Subscriptions you're using:
STD + https://github.com/spirillen/ublockorigin-rules

### Your settings
- OS/version: Tor Browser
- Browser/version: 
- Adblock Extension/version: uBlock Origin v1.35.2

### Other details:
![image](https://user-images.githubusercontent.com/44526987/121714752-720df580-cade-11eb-8772-77c9f62f92d0.png)

![image](https://user-images.githubusercontent.com/44526987/121714806-7df9b780-cade-11eb-9367-eee8a65b0a0a.png)

A few rules I found that should be added, probably, as global rules

```
##.happy-under-player
##.happy-footer
```

<details><summary>Sreenshots</summary>

![image](https://user-images.githubusercontent.com/44526987/121715354-0ed09300-cadf-11eb-8986-c699599f6456.png)

![image](https://user-images.githubusercontent.com/44526987/121715414-24de5380-cadf-11eb-96b9-e2e02a31b23e.png)

</details>

From Porn-Record submission <https://www.mypdns.org/T4697> (<https://github.com/mypdns/porn-records/commit/b8ebaa0c0399c43573fb1db1a91305192e9a32c2>)

**Comment by Yuki2718** [comment]
Doesn't work even with blocker disabled.

**Comment by spirillen** [comment]
> Doesn't work even with blocker disabled.

What doesn't work?
