### ISSUE TITLE
xtcore.js disables preview at blocket.se

### ISSUE THREAD

**Issue by davidhedlund** [easylist/easylist#8082]
### List the website(s) you're having issues:
```blocket.se```

### What happens?

blocket.se is a web service that allows private persons and companies to sell and buy physical goods, and services. However, the preview pop-up window is blocked. This is the HTML:
```<div class="col-sm-3">  <input id="preview_link" data-trackable="preview_ad_clicked" class="btn btn-secondary btn-block" value="Förhandsgranska annons" type="button" onclick="blocket.apps.ai.preview.open_preview()"> </div>```

See the text __Förhandsgranska annons__ on both the HTML above and on the button on the screenshot below for the button that triggers the pop-up windows.

![Screenshot at 2021-06-11 21-08-10](https://user-images.githubusercontent.com/6416073/121737644-6c71d900-caf9-11eb-89e6-d3a97cb44860.png)

The preview pop-up window appears only when I've whitelisted xtcore.js that is blacklisted in EasyPrivacy (```-xtcore.js```):

![Screenshot at 2021-06-11 21-09-52](https://user-images.githubusercontent.com/6416073/121737646-6d0a6f80-caf9-11eb-9185-034aa4e74c17.png)

### List Subscriptions you're using:

Only EasyPrivacy

### Your settings

- OS/version: Ubuntu-based distros
- Browser/version: Firefox 89.0
- Adblock Extension/version: uBlock Origin 1.35.2

**Comment by ryanbr** [comment]
Is this still an issue @davidhedlund ?
