### ISSUE TITLE
www.tokopedia.com [breakage sign in]

### ISSUE THREAD

**Issue by What-Zit-Tooya** [easylist/easylist#8083]
### List the website(s) you're having issues:

`https://www.tokopedia.com/find/fiio-m11-pro`

### What happens?

I can not sign in using QR code or OTP code. QR code not showing and after enter OTP code, there is an error.

### List Subscriptions you're using:

Default uBO settings

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Firefox 89.0 x64
- Adblock Extension/version: 1.35.2

### Other details:
![1](https://user-images.githubusercontent.com/9832875/121770940-8e6d6900-cb96-11eb-95ad-85685191ed1d.png)

This filter might the culprit:
`||tokopedia.com^*/pixel$xmlhttprequest`
Whitelist that , and i can sign in

**Comment by gmarcher** [comment]
> @gmarcher Using easyprivacy and OTP? no issues? Does it work in Chrome also?
> 
> Thanks!

my setup 
firefox+ublock (easylist+easyprivacy) >> can login with QR and OTP

chrome+ABP (easylist+easyprivacy) >> can't login with QR error, but i can login with OTP
chrome+ublock0 (easylist+easyprivacy) >> can't login with QR error, but i can login with OTP
![image](https://user-images.githubusercontent.com/12405001/155826792-20ed2679-1d7d-41cc-8613-f984c8b04009.png)

**Comment by ryanbr** [comment]
Does making an exception that specific rule help in Chrome?

**Comment by gmarcher** [comment]
> Does making an exception that specific rule help in Chrome?

chrome+ublock (Easylist+easyprivacy)
yes, i can log in with exception
