### ISSUE TITLE
kompas.com [mobile spesific]

### ISSUE THREAD

**Issue by What-Zit-Tooya** [easylist/easylist#8084]
### List the website(s) you're having issues:

`https://tekno.kompas.com/read/2021/06/04/12320017/samsung-galaxy-m62-masuk-indonesia-baterai-7.000-mah-harga-rp-6-juta`

### What happens?

ads placeholder

![1](https://user-images.githubusercontent.com/9832875/121771346-02a90c00-cb99-11eb-8ec2-7406961122c8.jpg)
![3](https://user-images.githubusercontent.com/9832875/121771361-1fddda80-cb99-11eb-9021-59b70e846870.jpg)
![4](https://user-images.githubusercontent.com/9832875/121771363-22403480-cb99-11eb-98c9-da05c3535d36.jpg)

### List Subscriptions you're using:

Default uBO settings
Adguard settings

### Your settings

- OS/version: Android 11
- Browser/version: Firefox Nightly 91.0a1 / Google Discover Built in Browser 12.22.8.23.arm64
- Adblock Extension/version: uBO 1.35.2 / Adguad Mobile 3.6.2

### Other details:

Have been tried with disable adguard and only use uBO on firefox, still there is ads placeholder. Then i use asguard to block that while using Google Discover, but no luck.

**Comment by gmarcher** [comment]
resolved at regional list
https://github.com/ABPindo/indonesianadblockrules/issues/209
