### ISSUE TITLE
What is purpose of this rule: /$file/analytics.

### ISSUE THREAD

**Issue by cretz** [easylist/easylist#809]
Is `$file` an option in `/$file/analytics.` according to Adblock syntax? The commit is at https://github.com/easylist/easylist/commit/1bcf25d782de073764bf122a8dffec785434d8cc and it broke my admittedly immature Adblock rule parser.

**Comment by ryanbr** [comment]
Okay, changed it; since it probably wont be hit as a generic on other sites.

https://github.com/easylist/easylist/commit/92bd0c3851f4ee089c4a7d4f2bf789169526fd7f
