### ISSUE TITLE
hashiconf.com

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#8102]
### List the website(s) you're having issues:

```
https://live.hashiconf.com/on-demand-videos
```

Requires login to view this page. Registration is free. The events tracker is only triggered after you login and access on demand videos

### What happens?

Events are posted as you watch on demand videos. Below is the data it posts. It seems to be partly broken as first & last name are reported as unknown at the moment.

```json
{"userID":"auth0|<removed>","projectID":"hashicorp-2021","function":"online","page":"/on-demand-videos","firstName":"unknown","lastName":"unknown","additionalInfo":{"firstName":"unknown","lastName":"unknown"},"error":"false","timestamp":"2021-06-14T15:19:31.265Z"}
```

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/62358249/119989341-f9c41200-bfbe-11eb-9b99-b716402ca812.png)

### Your settings

- OS/version: macOS 10.15.7
- Browser/version: Firefox 89.0
- Adblock Extension/version: Ublock Origin 1.35.3rc3

### Other details:

The event track code is in this script but can't be blocked as it break the web page

`https://live.hashiconf.com/static/js/main.bdd4b558.chunk.js`

It does a OPTIONS call followed by a POST with 
`
https://analytics-prod-m6tmapkf3q-uc.a.run.app/createEvent
`

Suggested filter
`||analytics-prod-m6tmapkf3q-uc.a.run.app^`

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/2085

</details>

**Comment by ryanbr** [comment]
Should be resolved now.
