### ISSUE TITLE
kifarunix.com ##.ezoic-ad

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#8105]
### List the website(s) you're having issues:

`https://kifarunix.com/autostart-virtualbox-vms-on-system-boot-on-linux/`

### What happens?

Lots of ezoic-ad

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/44526987/121966503-13ab7600-cd6f-11eb-856f-93a2e33dae33.png)

![image](https://user-images.githubusercontent.com/44526987/121966533-1dcd7480-cd6f-11eb-9f97-2813dfdb5da3.png)

### Your settings

- OS/version: Ubuntu 20.04
- Browser/version:  FF 89.0 (64-bit)
- Adblock Extension/version: uBlock Origin v1.35.2

### Other details:

See PR

**Comment by spirillen** [comment]
Same rules for `https://vitux.com/how-to-configure-networking-with-netplan-on-ubuntu/`

**Comment by krystian3w** [comment]
Pages have anti-adblock?

**Comment by spirillen** [comment]
> Pages have anti-adblock?

Didn't noticed :smirk: just ordinary bulks of ads loads
