### ISSUE TITLE
simplestream.com

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#8109]
### List the website(s) you're having issues:

```
https://www.simplestream.com/
```

### What happens?

It loads a tracker

### Your settings

![image](https://user-images.githubusercontent.com/62358249/119989341-f9c41200-bfbe-11eb-9b99-b716402ca812.png)

- OS/version: macOS 10.15.7
- Browser/version: Firefox 89.0
- Adblock Extension/version: Ublock Origin 1.35.3rc3

### Other details:

```
https://a.visitorqueue.com/open
https://t.visitorqueue.com/p/tracking.min.js?id=a077519b-15d7-49a8-9789-cb17a60fd93e
https://a.visitorqueue.com/close
https://a.visitorqueue.com/close?l=5&q=
```

Blocking the javascript takes care of other requests

```
||t.visitorqueue.com^
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6a03767ef50a97f606f476cf8a75316c0c1ee896
