### ISSUE TITLE
chinese bytedance's pstatp.com ads

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8119]
```
sf3-ttcdn-tos.pstatp.com

https://sf3-ttcdn-tos.pstatp.com/obj/ad-pattern/renderer/package.json

||pstatp.com/*ad-pattern^
```

![Screenshot_20210616-231057_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122245290-30bf8080-cef8-11eb-811b-5b3531a14343.png)

![Screenshot_20210616-231043_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122245293-31f0ad80-cef8-11eb-8a64-fad2c21397d3.png)

**Comment by krystian3w** [comment]
try also here:

```
! Please report any unblocked adverts or problems
! in the forums (http://abpchina.org/forum/)
! or via e-mail (easylist.china@gmail.com).
```

https://github.com/easylist/easylistchina/issues

**Comment by c2xusnpq6** [comment]
This is a tracker from a Chinese company, and that company's services include but are not limited to China, so...

**Comment by krystian3w** [comment]
It does not hurt to assess whether the `/easylist/easylistchina/` project is open to add privacy filters or whether they refer to EasyPrivacy.

If they do refer, you have to wait even 2 months until EasyPrivacy gets interested.

**Comment by krystian3w** [comment]
Conscientious people fled as musical.ly was "shut down".

**Comment by c2xusnpq6** [comment]
> This is a tracker from a Chinese company, and that company's services include but are not limited to China, so...

So I think it would be great if it can be added to `easylist` instead of `easylist china`

**Comment by krystian3w** [comment]
IMO trackers should be banned in optional "EasyPrivacy".

**Comment by c2xusnpq6** [comment]
![Screenshot_20210617-002606_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122257498-a7617b80-cf02-11eb-9e99-56f3cbd640e2.png)

![Screenshot_20210617-002611_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122257518-acbec600-cf02-11eb-8cc1-352f116c31ab.png)
