### ISSUE TITLE
unsplash.com

### ISSUE THREAD

**Issue by crazyyzarc** [easylist/easylist#8120]
Site
https://unsplash.com/s/photos/phishing

Could you remove the advertizing block?
![2021-06-17 11_17_53-Phishing Pictures _ Download Free Images on Unsplash](https://user-images.githubusercontent.com/4954535/122368855-fb4d7e00-cf5d-11eb-99a4-dc1125103f63.png)

**Comment by spirillen** [comment]
Here is a few suggestions you can try

```
! 2021-07-07 https://unsplash.com
unsplash.com##._30ce3
unsplash.com##._1VL0A

```
