### ISSUE TITLE
iqbroker.co

### ISSUE THREAD

**Issue by Qwiz** [easylist/easylist#8124]
### List the website(s) you're having issues:

* `iqbroker.co`
* `iqbroker.com`
* `iqoption.co.th`
* `tr-iqoption.com`

and a lot of other our sites

### What happens?

All styles are broken  
Scripts are not loading

### List Subscriptions you're using:

EasyList and EasyList Privacy

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 90.0b6
- Adblock Extension/version: ublock origin 1.35.2

### Other details:

Please, remove `cdnpub.info` from your list. Blocking it breaks a lot of our sites.

It was blocked here:
https://github.com/easylist/easylist/commit/295c0c021a39a874dee39cb1816715d8cbea5ee1

`iqbroker.co`
![изображение](https://user-images.githubusercontent.com/2022895/122585296-08549500-d064-11eb-9493-043f75464a7a.png)

`iqoption.co.th`
![изображение](https://user-images.githubusercontent.com/2022895/122582669-1359f600-d061-11eb-8948-c1873e797889.png)

**Comment by Qwiz** [comment]
Thanks, but adding some domains to whitelist is not an option.
A lot of of our sites still broken, because they are using `cdnpub.info` as a cdn to deliver scripts and styles.
I am sorry but I have to ask you to completely remove it from list.

Moreover, the original page stated in PR title do not have any links from `cdnpub.info`.
`https://paladins.it/grow-song-of-the-evertree-annunciato-un-nuovo-titolo-di-avventura-sandbox/`

**Comment by Khrin** [comment]
I apologize for the issue, but I believe the filter cannot be removed at this moment. I am sorry for the bad choice of an example link in my original commit, but this domain is still used to deliver ads:
![immagine](https://user-images.githubusercontent.com/15983921/122758338-f871c680-d298-11eb-9710-37146a59cd70.png)

**Comment by Qwiz** [comment]
Ok, thanks for explaining. Now I see the problem.

Could you change the filter to block only `$subdocument` for `cdnpub.info` or at least allow `$~script,~image,~stylesheet,~font` for it?
It will prevent loading html file with banner on page you provided and also it will fix all broken elements on our pages.

**Comment by Qwiz** [comment]
@Khrin sorry for mention, but this is important to us.
Could you answer to my question above?

Thanks

**Comment by Khrin** [comment]
Ok, I have corrected the filter as requested.
