### ISSUE TITLE
plotly.com

### ISSUE THREAD

**Issue by jxu** [easylist/easylist#8128]
plotly.com###campaign-zero-banner

**Comment by spirillen** [comment]
Not seing it in tor

![image](https://user-images.githubusercontent.com/44526987/124762474-3aef0080-df33-11eb-874f-4f8fa84e1882.png)

**Comment by jxu** [comment]
Yeah I think the campaign ended already

**Comment by jxu** [comment]
Actually it's for community.plotly.com, ex. https://community.plotly.com/t/disable-scrolling-even-though-there-are-two-many-legends/12223
