### ISSUE TITLE
ilanganews.co.za

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8135]
### List the website(s) you're having issues:

```
https://ilanganews.co.za/
https://ilanganews.co.za/ichiefs-ibona-amathuba-omlando-kwicaf/
```

### What happens?

Various ads, mostly near the bottom.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/122645077-b752a880-d118-11eb-9713-41b8a1df5516.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.114 x64
- Adblock Extension/version: uBO 1.35.3rc5 + IDCAC 3.3.0

### Other details:

There are currently no regional lists in the world that specifically cover Zulu-language websites; not even AdGuard Base's regional categories.

I propose:
```
! https://ilanganews.co.za/
||ilanganews.co.za/wp-content/uploads/*-323x323
||ilanganews.co.za/wp-content/uploads/*-Ad-*.png^
||ilanganews.co.za/wp-content/uploads/*/Umbele-weLanga2.jpg^
##.error.rocket-lazyload
! https://ilanganews.co.za/ichiefs-ibona-amathuba-omlando-kwicaf/
||ilanganews.co.za/wp-content/uploads/*-Online-Ads*.
```

![image](https://user-images.githubusercontent.com/22780683/122645146-2defa600-d119-11eb-8c97-4f849abb380f.png)

**Comment by ryanbr** [comment]
No english so no go.
