### ISSUE TITLE
gtaforums.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8137]
### List the website(s) you're having issues:

`https://gtaforums.com/topic/962897-grand-theft-auto-ifruit-app-lsc-not-working/`

### What happens?

Several wide placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/122645077-b752a880-d118-11eb-9713-41b8a1df5516.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.114 x64
- Adblock Extension/version: uBO 1.35.3rc5 + IDCAC 3.3.0

### Other details:

I propose `gtaforums.com##div[style^="text-align: center; margin: 0px"]`

![image](https://user-images.githubusercontent.com/22780683/122645324-4f04c680-d11a-11eb-81b6-743d051598d3.png)

**Comment by Khrin** [comment]
Seems to be already resolved.
