### ISSUE TITLE
transworld.net

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8139]
### List the website(s) you're having issues:

`https://skateboarding.transworld.net/videos/transworlds-endless-skater-app/`

### What happens?

Ad for a security cam, in the upper right, below the video.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/122645077-b752a880-d118-11eb-9713-41b8a1df5516.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.114 x64
- Adblock Extension/version: uBO 1.35.3rc5 + IDCAC 3.3.0

### Other details:

I propose `||i0.heartyhosting.com/*transworld.net/wp-content/uploads/*_1000x1000-$image`

![image](https://user-images.githubusercontent.com/22780683/122645430-dbaf8480-d11a-11eb-8f69-a1bb40949e92.png)

**Comment by THEtomaso** [comment]
More importantly, the article video is blocked, because of the following filter/rule:
**AdGuard Annoyances filter**
`||cookielaw.org^$third-party`

Possible fix @Yuki2718:
`@@||cdn.cookielaw.org/scripttemplates/otSDKStub.js$domain=transworld.net`

**Comment by ryanbr** [comment]
Looks fine here. Just picked up the newsletter div

https://github.com/easylist/easylist/commit/2993e84b28422a0f19c9cfab1516c17657fbde95
