### ISSUE TITLE
thefocus.news

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8140]
### List the website(s) you're having issues:

`https://www.thefocus.news/tech/why-is-notepad-banned-in-china/`

### What happens?

Two large placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/122645077-b752a880-d118-11eb-9713-41b8a1df5516.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.114 x64
- Adblock Extension/version: uBO 1.35.3rc5 + IDCAC 3.3.0

### Other details:

I propose:
```
thefocus.news##.GRVMpuWrapper
thefocus.news##amp-embed[type=taboola]
```

![image](https://user-images.githubusercontent.com/22780683/122645568-45c82980-d11b-11eb-897d-6cad7ef52d15.png)

**Comment by spirillen** [comment]
Hey @DandelionSprout thanks for your many contributions, however I have a small prayer to you.

Could you please consider using 

```
<details><summary>some image</summary>


</details>
```

surrounding your images :pray: in would minimize the need of scrolling
