### ISSUE TITLE
republicmonitor.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8143]
### List the website(s) you're having issues:

`https://republicmonitor.com/`

### What happens?

Various placeholders, intertwined between sections, and in the lower left.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/122645077-b752a880-d118-11eb-9713-41b8a1df5516.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.114 x64
- Adblock Extension/version: uBO 1.35.3rc5 + IDCAC 3.3.0

### Other details:

I am not entirely sure how to remove them.

![image](https://user-images.githubusercontent.com/22780683/122646384-23d0a600-d11f-11eb-8e84-7f4a0074caf2.png)

**Comment by Khrin** [comment]
I don't think that these are worthwhile to be blocked.
