### ISSUE TITLE
EasyPrivacy

### ISSUE THREAD

**Issue by teala12** [easylist/easylist#815]
the rule

||dopc.cz^$third-party

seems to break many czech websites - 
[www.novinky.cz](https://www.novinky.cz)
[www.aktualne.cz](http://www.aktualne.cz)
[games.tiscali.cz](http://games.tiscali.cz)
[www.super.cz](https://www.super.cz)
[isport.blesk.cz](http://isport.blesk.cz)
[www.reflex.cz](http://www.reflex.cz)
 - their css gets broken.

This makes the EasyPrivacy almost useless, could you please investigate / remove the rule?

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=130164#p130164

**Comment by ryanbr** [comment]
Sure, removed.

https://github.com/easylist/easylist/commit/8dcb19ff691d4018768f98ca7fc0d0e7512bf9b5
