### ISSUE TITLE
namepros.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8151]
### List the website(s) you're having issues:

`https://www.namepros.com/threads/show-me-your-idn-domain-names.1165927/`

### What happens?

Numerous ads, with varying degrees of obnoxiousnes and relevance.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/122645077-b752a880-d118-11eb-9713-41b8a1df5516.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.114 x64
- Adblock Extension/version: uBO 1.35.3rc5 + IDCAC 3.3.0

### Other details:

I propose:
```
namepros.com##[href^="/bevt/click/"]
(Optional) ||namepros.com/*?action=*&label=$xmlhttprequest
```

![image](https://user-images.githubusercontent.com/22780683/122647400-5e890d00-d124-11eb-84de-d6127551fb54.png)

**Comment by Daxy7** [comment]
Multiple ads are back. Fixable with filter:
`||nameproscdn.com/images/backers*/`
or
`namepros.com##.np-ghwe78`
