### ISSUE TITLE
hubspot.com & hscta.com blocked broadly

### ISSUE THREAD

**Issue by marcob** [easylist/easylist#817]
The content blocked with https://github.com/easylist/easylist/commit/0d9c42b7ab516b4939f8a1cab3e3f6e0760f340a is too generic and is affecting every HubSpot user.

Would it be possible to block content only from the one user that was identified in https://github.com/easylist/easylist/commit/0d9c42b7ab516b4939f8a1cab3e3f6e0760f340a? (`cta/default/189007`)

This issue is similar to what happened on the French list and was discussed here: https://forums.lanik.us/viewtopic.php?f=91&t=39290&p=129157

**Comment by Interactive** [comment]
This is currently affecting over 100 websites we manage right now. Navigation elements, buttons and content are not showing, page elements are being broken. This is majorly affecting many businesses. Please help.

**Comment by gswahhab** [comment]
This is currently affecting over 100 websites we manage right now. Navigation elements, buttons and content are not showing, page elements are being broken. This is majorly affecting many businesses. Please help.

**Comment by ThomasBeuls** [comment]
This is affecting our business too, we do not push any advertisements to our sites users, but merely use the CTA to optimize our websites user experience. Please have this resolved as I can image it's causing other companies even more loss of money.

**Comment by mapx-** [comment]
unbroken in uBo (ublock origin)

```
||hubspot.com/cta/$third-party,badfilter
||hscta.net/cta/$third-party,badfilter
#@#.hs-cta-wrapper
||no-cache.hubspot.com/cta/default/189007/
||cta-service-cms2.hubspot.com/ctas/*pid=189007
||cta-service-cms2.hubspot.com^$third-party,badfilter
```

**Comment by remingtonbegg** [comment]
This is effecting about 60 sites that we manage that have zero advertisements on it. calls to actions and even some slideshows.

Here's an example where it's removing navigation from impulsecreative.com
![image](https://user-images.githubusercontent.com/12864147/34533166-0cb52828-f087-11e7-929f-8cc3608c49e1.png)

**Comment by MarkLRyba** [comment]
All our managed websites are being effected as well. We use Calls to Action (CTAs) as primary navigations points, and have received a number of complaints from users. Our CTAs are almost always styled as buttons, or not even styled at all, much less displaying as ads. Please fix this quickly.

**Comment by RegD8** [comment]
We currently have over 40 clients being affected by this issue. None of the items being blocked are ads.

**Comment by mapx-** [comment]
You could recommend your users to use ublock origin (where the issue is fixed).

**Comment by SMJ0724** [comment]
Our website ([www.PresbyterianSeniorLiving.org](https://www.presbyterianseniorliving.org/)) is on the HubSpot platform, and is being affected as well. CTAs are used as primary navigation elements, linking to downloaded filed, etc. Never used to serve advertisements. We have received many reports from website visitors inquiring as to why our site now appears broken. Please fix this ASAP!

**Comment by chrism-granify** [comment]
https://www.granify.com/ is on Hubspot and we are currently missing many key buttons, including the primary means for prospective employees to view our Job Openings and prospective clients to access Resources and request consultations. This is having a strong negative impact on our users' web experience.

Examples of the content (buttons) being blocked:
![image](https://user-images.githubusercontent.com/15875282/34589778-d010b9c0-f16f-11e7-9c01-96593f88d53a.png)

![image](https://user-images.githubusercontent.com/15875282/34589784-d9937b22-f16f-11e7-882c-45d68f8b6bcd.png)

**Comment by shayredmond** [comment]
@SMed79 @monzta @mapx- @ryanbr relevant to this thread, working with the customer referenced in the original commit (https://github.com/easylist/easylist/commit/0d9c42b7ab516b4939f8a1cab3e3f6e0760f340a) that caused this issue, we have been able to remove the offending CTA, it has been completely deleted. Is there any information you can provide before the weekend so that we can set reasonable expectations with our customers around a resolution to this issue?

**Comment by monzta** [comment]
Removed: https://github.com/easylist/easylist/commit/3a214774c105522cbd966d9681800a8ac0ca9a5b
