### ISSUE TITLE
Chinese Bilibili tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8173]
```
https://data.biliintl.com/log
https://data.bilibili.com/log/mobile?android
dataflow.biliapi.com

||data.biliintl.com/log
||dataflow.biliapi.com^
||app.biliintl.com/intl/gateway/*/app/data/report^
```

![Screenshot_20210623-005701_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122969042-ca86a200-d3be-11eb-9f53-fa50f96239e6.png)

![Screenshot_20210623-005808_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122969055-ce1a2900-d3be-11eb-908f-39d5533d4f42.png)

![Screenshot_20210623-005813_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122969070-d2dedd00-d3be-11eb-8659-142f54bec260.png)

**Comment by c2xusnpq6** [comment]
```
https://www.bilibilicomics.com/twirp/log.v1.Neuron/Log
```

![Screenshot_20210623-011244_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122970353-5f3dcf80-d3c0-11eb-82d2-c439883a625e.png)

**Comment by c2xusnpq6** [comment]
```
https://api.bilibili.com/open/monitor/apm/report
```

![Screenshot_20210623-011749_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122970753-dbd0ae00-d3c0-11eb-899a-5f3bb5746611.png)

**Comment by c2xusnpq6** [comment]
```
https://grpc.biliapi.net/bilibili.app.playurl.v1.PlayURL/PlayView

https://api.bilibili.com/x/v2/history/report
```
![Screenshot_20210623-012544_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122971755-fbb4a180-d3c1-11eb-801e-b584159593b1.png)

![Screenshot_20210623-012528_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122971765-fe16fb80-d3c1-11eb-86aa-625182ece909.png)

**Comment by c2xusnpq6** [comment]
```
https://grpc.biliapi.net/bilibili.app.view.v1.View/View
```

![Screenshot_20210623-012725_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122971950-328ab780-d3c2-11eb-8091-10511aa3913c.png)

**Comment by shenzhiming88** [comment]
@c2xusnpq6 What about `||live-trace.bilibili.com^`
#9291

**Comment by felix-22** [comment]
Report to [EasyList China tracker](https://github.com/easylist/easylistchina/issues) like advised [here](https://github.com/easylist/easylist/issues/9381#issuecomment-942322155).

**Comment by lvzhenbo** [comment]
||live-trace.bilibili.com^
这个规则导致拿不到小心心，请求撤回PR
This rule results in not getting the little heart gift, please withdraw the PR
This rule is designed to track how long a user is on the air in order to obtain live gifts, not malicious tracking

**Comment by c2xusnpq6** [comment]
> ||live-trace.bilibili.com^
> 这个规则导致拿不到小心心，请求撤回PR
> This rule results in not getting the little heart gift, please withdraw the PR
> This rule is designed to track how long a user is on the air in order to obtain live gifts, not malicious tracking

我等一下看看

**Comment by c2xusnpq6** [comment]
> @c2xusnpq6 What about `||live-trace.bilibili.com^`
> #9291 

他說這個會令他無法得到app裏面靠使用時數獲得的虛擬物品。

He said this would prevent him from getting the virtual items in the app that he gets by using hours.

**Comment by shenzhiming88** [comment]
> > @c2xusnpq6 What about `||live-trace.bilibili.com^`
> > #9291
> 
> 他說這個會令他無法得到app裏面靠使用時數獲得的虛擬物品。
> 
> 你怎麼看？
> 
> He said this would prevent him from getting the virtual items in the app that he gets by using hours.
> 
> What do you think? @shenzhiming88

是在App里面吗？我用网页端测试好像可以送礼物。

![image](https://user-images.githubusercontent.com/66902050/143894508-7b7666dd-5ea7-41bf-a5d8-39d3cc35eaa1.png)

**Comment by lvzhenbo** [comment]
不是送礼物，而是获取不了每5分钟能够获得的小心心

**Comment by lvzhenbo** [comment]
这个域名是用来追踪观看时长的，每一分钟发一次

**Comment by lvzhenbo** [comment]
![image](https://user-images.githubusercontent.com/32427677/143894943-a817ae54-41e1-4f92-a65e-4a5aadb1f95d.png)

**Comment by c2xusnpq6** [comment]
I don't care about this, but I don't rule out other people wanting it. If it's a (mainland) Chinese app, then I'd rather have privacy. HA!

**Comment by shenzhiming88** [comment]
我只是经过了粗略的测试，并且这个域名被一些中文屏蔽列表拦截了，因此我觉得这个是跟踪域名。既然会破坏正常功能，那就移除了吧。抱歉。

I just went through a rough test and the domain was blocked by some Chinese block list, so I think this is a tracking domain. Since it will break the normal function, let's remove it. Sorry.

**Comment by shenzhiming88** [comment]
> I don't care about that, but I don't rule out other people wanting it. If it's a **(mainland)** Chinese app, then I'd rather have privacy. HA!

但是这个域名的确也是用来跟踪的。因此，我自己还是拦截它吧。

But this domain is indeed also used for tracking. Therefore, I'd better block it myself.

**Comment by c2xusnpq6** [comment]
> 是的，中国大陆的应用程序的确喜欢搜集用户隐私。
> 
> Yes, apps in mainland China do like to collect user privacy.

對的對的 我以前就深受其害... 不要誤會 只是那麼剛好中國大陸的互聯網環境比較惡劣😑

希望可以越來越好吧😗👍
