### ISSUE TITLE
Chinese Huawei tracker datacollector-dra.dt.hicloud.com

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8175]
```
https://datacollector-dra.dt.hicloud.com

||datacollector-dra.dt.hicloud.com^
or
||datacollector*.hicloud.com^
```

![Screenshot_20210623-030933_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122985830-36720600-d3d1-11eb-954f-b8c2b2f774ef.png)

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/1876

</details>

**Comment by Yuki2718** [comment]
There must be many examples to justify use of wildcard. Here only `datacollector-dra.dt.hicloud.com` is shown.
