### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by RikoDEV** [easylist/easylist#819]
Advertising is visible only in articles and its css selector is generated randomly.

![ad](https://user-images.githubusercontent.com/18230443/34568160-39f29274-f165-11e7-8939-73101c3edd23.PNG)

Firefox 58.0b13
uBlock: 1.14.23b12

**Comment by userOperaFF** [comment]
I see too on home page.

**Comment by ryanbr** [comment]
More applicable for https://github.com/MajkiIT/polish-ads-filter ?

**Comment by mapx-** [comment]
https://github.com/NanoAdblocker/NanoFilters/issues/3#issuecomment-357333491

(last filter for ABP will be:
`@@||static.criteo.net/js/ld/publishertag.js$script,domain=dobreprogramy.pl`
)
