### ISSUE TITLE
pocket-lint.com

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#82]
Hi,

When you open below site on your mobile phone then at the top of page there is "Cookie Privacy Policy" notice

`http://www.pocket-lint.com/`

https://s32.postimg.org/z4faom6x1/Screenshot_2016_07_05_16_31_20.png

The working filter to block "Cookie Privacy Policy" notice

`www.pocket-lint.com###cookie-notice > div`

Please add the above filter in EasyList

when you scroll down then after "More news" there is a big blank space. I would like to request you please check and block the blank space too.

Thanks a lot

**Comment by monzta** [comment]
Such messages [aren't covered by EasyList](https://easylist.to/pages/policy.html).
