### ISSUE TITLE
Innocuous images being blocked by 'media' rule across the web

### ISSUE THREAD

**Issue by epicalex** [easylist/easylist#8209]
### List the website(s) you're having issues:

- `https://www.habitat.co.uk/browse/sofas-and-armchairs/armchairs/c:809185/`
- `https://www.coxandcox.co.uk/the-scandi-loveseat/`
- `https://www.sofa.com/gb/armchairs/mid-century/holly-armchair/p/FSHOL115HBWPUM`
- `https://www.swooneditions.com/lunalove#lunaloveevelvetpetrolbluedark`
- `https://www.nngroup.com/articles/ux-maturity-model/`
- `https://76ltd.com/`

### What happens?

Images are blocked on any site that uses a `media` directory or sudbdomain for those images. This is happening on many many sites, just a few of them that I've encountered in the last hour are above.

Also included one example of a CSS file being blocked because it loads on a media subdomain.

### List Subscriptions you're using:

- EasyList via AdBlock

### Your settings

Only one adblocker running

- OS/version: MacOS 10.15.7
- Browser/version: Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- Adblock Extension/version: AdBlock Version 4.34.0

### Other details:

`media` rule as per the below screenshots. This only started for me today.

<img width="976" alt="Screenshot 2021-06-27 at 22 32 13" src="https://user-images.githubusercontent.com/1392061/123560003-879a4500-d797-11eb-8f3b-bd5befc10f7f.png">
<img width="1440" alt="Screenshot 2021-06-27 at 22 50 33" src="https://user-images.githubusercontent.com/1392061/123560448-17d98980-d79a-11eb-9696-50facb732f81.png">
<img width="1440" alt="Screenshot 2021-06-27 at 22 50 52" src="https://user-images.githubusercontent.com/1392061/123560458-232cb500-d79a-11eb-89bb-8967913e07a6.png">
<img width="1078" alt="Screenshot 2021-06-27 at 22 52 12" src="https://user-images.githubusercontent.com/1392061/123560484-52432680-d79a-11eb-985f-e3f0a3ec4231.png">

**Comment by epicalex** [comment]
Additionally, on our product `slateapp.com` some internal admin links that load via ajax are also being blocked by this. For example, `/admin/media/list` and `/javascripts/slate.media.library.js`. We're a tool for the film production industry to literally manage their library of media, so renaming these links to avoid the filters is not an option.

**Comment by epicalex** [comment]
https://twitter.com/home is also completely broken because the xhr to load tweets includes `media` in the query string: `https://twitter.com/i/api/2/timeline/home.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&earned=1&count=20&lca=true&ext=mediaStats%2ChighlightedLabel`

<img width="1440" alt="Screenshot 2021-06-27 at 23 01 40" src="https://user-images.githubusercontent.com/1392061/123560675-a39fe580-d79b-11eb-9cb5-01f08e610c39.png">

**Comment by llacb47** [comment]
already removed https://github.com/easylist/easylist/commit/9a35decd7429737af9c814bf16cf30caed8f9399

**Comment by epicalex** [comment]
Thanks @llacb47. I tried to find a commit relating to it, but github search wasn't yielding anything obvious.

**Comment by krystian3w** [comment]
AG also feel this glitch:

[#86981](https://github.com/AdguardTeam/AdguardFilters/issues/86981)
[#86987](https://github.com/AdguardTeam/AdguardFilters/issues/86987)
[#87006](https://github.com/AdguardTeam/AdguardFilters/issues/87006)
[#87020](https://github.com/AdguardTeam/AdguardFilters/issues/87020)
[#87031](https://github.com/AdguardTeam/AdguardFilters/issues/87031)
