### ISSUE TITLE
converti.se

### ISSUE THREAD

**Issue by KonoromiHimaries** [easylist/easylist#822]
EasyPrivacy

```
pl##a[href*="://converti.se/click/"]
||converti.se/comparison/$xmlhttprequest
||converti.se/convertext.js$script
||converti.se/recommendations.js$script
```

https://github.com/MajkiIT/polish-ads-filter/issues/4852

**Comment by KonoromiHimaries** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/5734#issuecomment-361015473

**Comment by peace2000** [comment]
`converti.se` seems to be an old domain that is not being used anymore.

![kuva](https://user-images.githubusercontent.com/17256841/70391756-4e498b00-19e1-11ea-884a-52a799c4dd9a.png)

That link leads to `https://convertiser.com/pl` which seems to be completely new website.
