### ISSUE TITLE
manualslib.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8226]
### List the website(s) you're having issues:

`https://www.manualslib.com/products/Micro-Flex-200-4180922.html`

### What happens?

Some placeholders, one of them really big.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/123864666-505c9d00-d92b-11eb-9a07-d7284294632f.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.124 x64
- Adblock Extension/version: uBO 1.36.1b1 + IDCAC 3.3.1

### Other details:

I propose:
```
###banner_productSideAd
##.pr_adv_ban
```

![image](https://user-images.githubusercontent.com/22780683/123864818-797d2d80-d92b-11eb-8e2a-9855fd26c525.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/66f34944a99df499e53425886488053b59d75a95
