### ISSUE TITLE
thestreet.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8227]
### List the website(s) you're having issues:

`https://www.thestreet.com/`

### What happens?

Placeholder banner near the top. 

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/123864666-505c9d00-d92b-11eb-9a07-d7284294632f.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.124 x64
- Adblock Extension/version: uBO 1.36.1b1 + IDCAC 3.3.1

### Other details:

I propose `thestreet.com##.m-balloon-header`

![image](https://user-images.githubusercontent.com/22780683/123865030-b812e800-d92b-11eb-9453-ee653eb9e920.png)

**Comment by ryanbr** [comment]
Should be resolved.
