### ISSUE TITLE
independent.co.uk

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8229]
### List the website(s) you're having issues:

`https://www.independent.co.uk/news/uk/home-news/gb-news-india-willoughby-quits-b1871248.html`

### What happens?

Placeholder early on in the article. Most noticeable if the window width is less than 950px.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/123864666-505c9d00-d92b-11eb-9a07-d7284294632f.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.124 x64
- Adblock Extension/version: uBO 1.36.1b1 + IDCAC 3.3.1

### Other details:

I propose `independent.co.uk#?##main > div[class^=sc-]:-abp-has(div[data-mpu])`

![image](https://user-images.githubusercontent.com/22780683/123865734-949c6d00-d92c-11eb-820f-404db12a9957.png)

**Comment by chirag127** [comment]
I can't reproduce with Adguard base filter considering you are also using it.

**Comment by DandelionSprout** [comment]
Are you using a small and narrow window, since the placeholder is only noticeable then?

**Comment by chirag127** [comment]
Well, I can reproduce it by turning off the Adguard extension.

**Comment by ryanbr** [comment]
Filter does work here, side by side seeing no difference.

**Comment by DandelionSprout** [comment]
Have you tried on a phone? That approach would've ruled out any confusion about window sizes.
