### ISSUE TITLE
osbot.org

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8244]
### List the website(s) you're having issues:

`https://osbot.org/forum/`

### What happens?

Extraordinarily fast (or framerate-tied) animated ads near the top.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/123864666-505c9d00-d92b-11eb-9a07-d7284294632f.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.124 x64
- Adblock Extension/version: uBO 1.36.1b1 + IDCAC 3.3.1

### Other details:

I propose:
```
||i.imgur.com/*.gif^$domain=osbot.org
||i.ibb.co/*.gif^$domain=osbot.org
```

![image](https://user-images.githubusercontent.com/22780683/123873015-2197f400-d936-11eb-9574-74c4db262328.png)

**Comment by IThinkIAmCool** [comment]
How about
```
##[href^="https://www.runebet.com/landing?aid="]
##[href^="https://www.partypeteshop.com/?ref"]
##[href^="https://www.aribagold.com/ref/"]
##[href^="https://alch.com/?referral"]
```
