### ISSUE TITLE
afternerd.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8247]
### List the website(s) you're having issues:

`https://www.afternerd.com/blog/sort-vs-sorted/`

### What happens?

Green placeholder on the right.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/123864666-505c9d00-d92b-11eb-9a07-d7284294632f.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.124 x64
- Adblock Extension/version: uBO 1.36.1b1 + IDCAC 3.3.1

### Other details:

I propose `afternerd.com##.widget_search + .widget`

![image](https://user-images.githubusercontent.com/22780683/123873916-90298180-d937-11eb-9950-05b30fa11ad3.png)

**Comment by ryanbr** [comment]
Too minor.
