### ISSUE TITLE
m.youtube.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8252]
### List the website(s) you're having issues:

`https://m.youtube.com/watch?v=aTtcgB5w5Q8`

### What happens?

Ads occasionally (but not always) appear under extremely specific circumstances that are very hard to reproduce and keep logs of on command:

1) Use uBlock Origin with 'Firefox on Android', with EasyList, uBlock Filters, AdGuard Base, and whichever other lists turned on.
2) The phone must either have recently rebooted, or not have opened up Firefox for a few hours.
3) A phone user agent doesn't seem to be sufficient. It only occurs on physical phones.
4) Specific YouTube videos (In my case `https://www.youtube.com/watch?v=aTtcgB5w5Q8`) must be linked to on Discord, then the link must be clicked on.
5) The uBO logger must not be open (I swear on my guts that `YouTube` have found a way to detect the logger being open).

At this point, there's a circa 50% chance that a preroll ad will be played. After around 5 attempts on the same IP address, the chance drops to pretty much 0%, to the point where I'm unable to provide a screenshot of the preroll at the time of writing.

### List Subscriptions you're using:

<details><summary>Screenshots</summary>

![Screenshot_20210630-220740](https://user-images.githubusercontent.com/22780683/124026454-fecb1580-d9f1-11eb-9b21-36101c4edbdc.png)
![Screenshot_20210630-220750](https://user-images.githubusercontent.com/22780683/124026463-01c60600-d9f2-11eb-9640-1cea57dab776.png)

</details>

### Your settings

- OS/version: Android 10 QPHS30.29-Q3-28-13-10-7 aarch64
- Browser/version: Firefox Nightly for Android 91.0a1 (Build `#`2015819019) aarch64
- Adblock Extension/version: uBO 1.36.0 + IDCAC 3.3.1

### Other details:

I seem to be having luck with `||googlevideo.com/*&aitag=`, but I'm having major problems confirming it 100%. Blocking `||ade.googlesyndication.com^` doesn't seem to fix it.

I'm also having problems confirming that setting `suspendTabsUntilReady true` in uBO's advanced-user status (on the assumption that the problem is caused by uBO not being loaded into Firefox fast enough; which'd be surprising for a 400€ Motorola One Zoom) fixes it on its own or not.

I've had problems in the past where uBO in Firefox for Android would occasionally and randomly fail to sync (or even load) individual lists if the browser was in idle mode, but it doesn't seem to have been the case here.

**Comment by ryanbr** [comment]
What url is the full url we're blocking here? from `||googlevideo.com/*&aitag=` @DandelionSprout

**Comment by DandelionSprout** [comment]
`https://r9---sn-uxaxovg-vnaee.googlevideo.com/videoplayback?expire=1627209905&ei=Uez8YM7UNI2HgAfnzILoDQ&ip=2a02%3A2121%3A341%3A8a0e%3A2ef%3A2826%3A7920%3Aec4f&id=o-AMB8mclGST5_YxLxEjA_SO5YkNo-u1g_FPw-kAV5Xlk5&itag=243&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=At&mm=31%2C29&mn=sn-uxaxovg-vnaee%2Csn-5goeen7y&ms=au%2Crdu&mv=m&mvi=9&pl=47&gcr=no&initcwndbps=1496250&vprv=1&mime=video%2Fwebm&ns=AXpOeUXwGhYT7khZK7OuPPgG&gir=yes&clen=1088691&dur=207.000&lmt=1573702655891445&mt=1627187840&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=MWEB&txp=2301222&n=C5LIcdyz8jG46Q&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKF1s1pMBwHWqD3VXSqE3C6rqp1yDAyuiZzJ4w-jAnEDAiEA0TOG1EjsU6z7rE7wbSMUekE8YDM0OM8mjeX2YccG75o%3D&alr=yes&sig=AOq0QJ8wRgIhAK3I_2bntkjUakBHro-gq1FRWAt44hddE4xEVgt12-_dAiEAg4JYtWixS_0h7s3Hg3cDZZx486poDQQ8X5S8TTCVSfo%3D&cpn=H5ny9MZDoZ61MrwO&cver=2.20210721.07.00&range=66422-186752&rn=5&rbuf=12656` (An `xmlhttprequest` file)

**Comment by DandelionSprout** [comment]
No, wait, disregard the above, as that was `aitags` with an S.

Given I was only ever able to reproduce this for 2 hours while waiting on the bus home from a beach village, I suppose I have to close this for now.
