### ISSUE TITLE
overmind.datatheorem.com

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8253]
```
https://overmind.datatheorem.com/trustkit/report

||datatheorem.com^ ?
```

> Data Theorem is a leading provider of modern application security. Its core mission is to analyze and secure any modern application anytime, anywhere. The Data ...

![Screenshot_20210622-022719_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122810144-97caa400-d301-11eb-9f53-85d7e10bbf44.png)

**Comment by ryanbr** [comment]
Couldn't replicate on othersite via publicwww
