### ISSUE TITLE
/v4/metrics

### ISSUE THREAD

**Issue by paulo-santos-kelvin** [easylist/easylist#8265]
### List the website(s) you're having issues:

`https://<customer domain>/api/v4/metrics/list?page_size=20&sort_by=metric.title&sort_asc=true
`

It's the administration interface of a system that's installed on-premises.

### What happens?

The endpoint is blocked, so the administration of the affected section is not possible.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Linux/Arch
- Browser/version: Firefox/89.0.2
- Adblock Extension/version: uBlock Origin/1.36.0

### Other details:

The filter causing the issue is: https://github.com/easylist/easylist/blob/18c06bd764a8765e6f4598126d4308860cd02627/easyprivacy/easyprivacy_general.txt#L4914

Introduced in commit: 57ea3ee0f57d2a99cad6f73529d33e77087dc89c

**Comment by spirillen** [comment]
My 2 cents points toward leaving the rule as is. Because:

You "administrative" interface is install in own domain, I would therefor suggest you naturally added full trust to your own domain... or is there some reasons you do not have trust in your own software?

```
@@||<customer domain>^$important
```

**Comment by paulo-santos-kelvin** [comment]
On Thu Jul 1, 2021 at 9:32 PM WEST, spirillen wrote:
> My 2 cents points toward leaving the rule as is. Because:
>
> You "administrative" interface is install in own domain, I would
> therefor suggest you naturally added full trust to your own domain... or
> is there some reasons you do not have trust in your own software?

I understand not wanting to change the rule because of a non-public facing
page, but I was wondering if it's possible to tweak the rule to still be
safe.

Something like "block unless the domain is the same" would still be
safe? Although I don't know if such rule is possible to write.

The reason for it is that otherwise, every user of every installation
needs to add that rule.

**Comment by spirillen** [comment]
```
/v4/metrics$domain~=<customer domain>
```


Beware of eventually typos, I'm not on my best right now :vomiting_face:

**Comment by paulo-santos-kelvin** [comment]
Is there any way to make that <customer domain> be the actual "current
domain" so that it's possibly accepted in easylist itself?

**Comment by spirillen** [comment]
```bash
if  [ "<customer domain>" == "example.com" ]
then
    '/v4/metrics$domain=~example.com'
fi
```

**Comment by llacb47** [comment]
@paulo-santos-kelvin, yes, the addition of `third-party` to the rule would allow those requests to succeed if on the same domain as the current page. however, without an actual example page, @ryanbr will not make any changes

**Comment by ryanbr** [comment]
@paulo-santos-kelvin can you modify the url to avoid the block?

**Comment by paulo-santos-kelvin** [comment]
On Fri Jul 2, 2021 at 4:34 AM WEST, Fanboynz wrote:
> @paulo-santos-kelvin can you modify the url to avoid the block?

I just got the information that that's what will indeed be done.

My particular use case is solved, so I'll close the ticket.

Thank you all for your help!
