### ISSUE TITLE
Uber Eats tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8268]
https://www.ubereats.com/ --> https://www.ubereats.com/ramendca/events/ack?seq=0 tracker?
https://www.ubereats.com/ --> https://www.ubereats.com/_events

```
https://www.ubereats.com/ramendca/events/ack?seq=0

||ubereats.com/ramendca/events^
||ubereats.com/*_events^
||uber.com/*_events^
```

**Comment by ryanbr** [comment]
Resolved.
