### ISSUE TITLE
freegames.org

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8269]
### List the website(s) you're having issues:
`https://freegames.org`

### What happens?
space / ad leftover / ad placeholder

### List Subscriptions you're using:
uBO's default

### Your settings

Opera with VPN | uBO

### Other details:
![image](https://user-images.githubusercontent.com/86536735/124299481-24792b80-db66-11eb-9dde-0575a09370e4.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/526580ad3fb4e2aee11d5a40e02bd303abd53f60
