### ISSUE TITLE
Targeting " .vertical-ads" class is too generic and causes false positives

### ISSUE THREAD

**Issue by EboMike** [easylist/easylist#827]
Removing all content with .vertical-ads ends up removing DIV blocks that should actually be visible. blogspot.com for example doesn't work with some of the modern responsive templates and end up hiding the entire post. That forces people to turn off adblockers, which ends up resulting in MORE ads being served than if vertical-ads had been left untouched.

The ads themselves are already blocked, so removing vertical-ads is overkill.

**Comment by Khrin** [comment]
Have you any example for this issue?

**Comment by EboMike** [comment]
Here's an example: http://newsletterdepot.blogspot.com.au/

I'm not affiliated with this site, I just randomly came across it. My own blogspot page had the same problem, I worked around it by patching the CSS and HTML.

**Comment by ryanbr** [comment]
The filter is fine, and not a blogspot issue (I checked random blogspot sites). Its the webpage designer using the an obviously bad class element.

**Comment by EboMike** [comment]
Which ones did you check? This is part of the modern templates. Any blog on blogspot using modern templates and ads will be affected by this (modern templates are the default options for recently created blogs). My own blog had the problem, and I had to tweak the HTML and CSS to fix it. Prior to that, I used the template out of the box with zero modifications, and the entire page was blank when viewed with AdBlock.

**Comment by ryanbr** [comment]
Just a quick google, these loaded and rendered fine.

`http://ipkitten.blogspot.com/`
`http://mikehadlow.blogspot.com/`
`https://anemoslinux.blogspot.com/`

**Comment by EboMike** [comment]
These are all old blogs. Google has introduced the modern templates ~1 year ago or so, so you'll need to check newer blogs (either those created recently, or those that have been updated with a newer template) that have ads.

Here's a quick Google check from my end:

https://naturalcreature.blogspot.com/ (redicts to http://www.wingsbirdpro.com/)
http://karamazupasa.blogspot.com/
http://www.digitalsignagecreativo.com/

The majority of blogs work because they use older templates or have been customized. Since new blogs default to the modern templates, more and more blogs will break over time.

**Comment by ryanbr** [comment]
Only was seen on one site; 
https://github.com/easylist/easylist/commit/87ea61c98ae1a167a92cbdf9b90acbd9bc13b648

Also going by my commit, its the only vertical-ads, if it was a major issue the site owners should stop using wrapping their homepages in a generic ad element.
