### ISSUE TITLE
[NSFW] porndish.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8276]
anti adblock

**Comment by spirillen** [comment]
Can't confirm

<details><summary>note to self (@spirillen)</summary>

Added in https://mypdns.org/my-privacy-dns/porn-records/-/issues/78

</details>

**Comment by IThinkIAmCool** [comment]
> Can't confirm
>
Did you visit with uBO and uBlock filters enabled?

**Comment by spirillen** [comment]
@ryanbr or @Khrin Just close this one, @ghost have taken this "issue" which isn't an issue

**Comment by IThinkIAmCool** [comment]
@spirillen it is. uBO's 'uBlock filters' has already addresses the anti adblock.

**Comment by spirillen** [comment]
What `anti adblock`?? where, when?? there are no such thing on that site for what i can see in weather ff or tor

**Comment by IThinkIAmCool** [comment]
> 
> 
> What `anti adblock`?? where, when?? there are no such thing on that site for what i can see in weather ff or tor

Did you visit the website with uBO and its enabled-by-default filter lists?

**Comment by IThinkIAmCool** [comment]
Because if so:
> uBO's 'uBlock filters' has already addresses the anti adblock.
>

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1c3267b1a94925ddd8f2642fed662977db9530a3

Will help with adservers.
