### ISSUE TITLE
www.foodkick.com false positive

### ISSUE THREAD

**Issue by freshdir** [easylist/easylist#830]
The homepage main header content (hero image and headline) on https://www.foodkick.com is being blocked. The content is being served by Google DoubleClick For Publishers, but are never adverts. They are always 1) editorial content or 2)messaging that informs customers of products that are for sale on our own site.

See #826 for more details on the use. 

Of note, the blocked items on FreshDirect use OAS (Open AdStream), while Foodkick uses Google DFP, but FreshDirect will also be migrating to Google DFP soon. So if any whitelist of domain foodkick.com can also apply to freshdirect.com, it would be much appreciated.

Thanks for committing a fix for #826 so quickly.

**Comment by ryanbr** [comment]
Screenshot of the issue?

**Comment by ryanbr** [comment]
Okay, I see what you mean, its advert. The title is wrapped in a quite few adscripts, it doesn't break the site. I'd recommend changing the header on the server side.

**Comment by freshdir** [comment]
Hi,
Attached are screenshots of the website blocked and unblocked.  We are using Google DFP in order to serve our own first-party content to our users. These are never adverts by the definition found here, because they aren't third party (and also aren't displayed in return for goods or services): https://easylist.to/2011/07/11/the-definition-of-advert-and-link-exchange-policy.html

The currently blocked content isn't even a link, although in the future it may link to a page of our own site (for example directing users to a curated list of groceries that we sell, e.g. "In-Season Produce".)


Is there a technical limitation because we cannot whitelist these without whitelisting all content served by Google DFP? Or can it be restricted to our domains (foodkick.com and freshdirect.com)?

The blocking on Foodkick doesn't currently break the entire site, but it limits our ability to create a visual experience and display our own first-party products in the way we think is best for our users.


<img width="410" alt="foodkickhomepage" src="https://user-images.githubusercontent.com/35238378/34998559-67eaa238-faad-11e7-8fb2-7aa1e5ec7cbf.PNG">
<img width="398" alt="foodkickhomeblocked" src="https://user-images.githubusercontent.com/35238378/34998564-683a5b16-faad-11e7-8281-f69e50f43352.PNG">
<img width="360" alt="foodkickblocked" src="https://user-images.githubusercontent.com/35238378/34998560-680194a2-faad-11e7-8b99-60e8a17c22bc.PNG">
<img width="430" alt="foodkickblocked2" src="https://user-images.githubusercontent.com/35238378/34998561-6809dce8-faad-11e7-8d0a-4f606c995be9.PNG">
<img width="376" alt="foodkickblocked3" src="https://user-images.githubusercontent.com/35238378/34998562-681c8492-faad-11e7-9d4f-b54459aa36b7.PNG">
<img width="424" alt="foodkickblocked4" src="https://user-images.githubusercontent.com/35238378/34998563-682e8fde-faad-11e7-8fab-acb2b1877cf8.PNG">

**Comment by freshdir** [comment]
@monzta this is similar to the freshdirect.com issue here #826 , the only difference is which system we are using to display content to our users.  We are moving to Google DFP in order to display more relevant content (still first party, non-paid, non-intrusive messaging for products that we sell on our own site that is part of the design aesthetic).

Is there a technical limitation or a question about whether our content in an advert?

The other solution from our end is to implement overlay messaging asking each user to whitelist our site, which is considerably worse experience for the user.
