### ISSUE TITLE
libhunt.com

### ISSUE THREAD

**Issue by kah0922** [easylist/easylist#8309]
### List the website(s) you're having issues:
`https://www.libhunt.com/r/audacity`

### What happens?

Sponsored listing adverts
### List Subscriptions you're using:
Default uBlock + Fanboy's Annoyance + uBlock Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox Nightly
- Adblock Extension/version: uBlock Origin 1.36.1b3

### Other details:

![image](https://user-images.githubusercontent.com/9474213/124676578-506e1700-deae-11eb-9ab1-512bde854827.png)
All listings can be blocked via `libhunt.com##li.sponsored`

**Comment by spirillen** [comment]
Try this one
```
chicagobusiness.com,chronicle.co.zw,duckduckgo.com,fifplay.com,herald.co.zw,msn.com,timeslive.co.za,libhunt.com##.sponsored
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/500d72d5bff40bf2ae541d96b9f404ec229c26d2
