### ISSUE TITLE
diki.pl/

### ISSUE THREAD

**Issue by kolor33** [easylist/easylist#8313]
hi they is any way to put some filter for diki.pl website .

https://www.diki.pl/

**Comment by krystian3w** [comment]
Blank margin left-over, need use `:style()` but EasyList for ads no implemented uBO supplementation.

**Comment by krystian3w** [comment]
@TrollZbozowy / @adblock-filters / @easylistpolish

**Comment by adblock-filters** [comment]
Hi @kolor33 , could you attach the screen showing the problem (can't reproduce it right now), so we can try to fix it on easylistpolish list?

**Comment by krystian3w** [comment]
Ads is blue bar at top about sale for learn English by pro Teachers.

**Comment by adblock-filters** [comment]
ok thanks

**Comment by krystian3w** [comment]
![Screenshot_20210712-085005_Firefox](https://user-images.githubusercontent.com/35370833/125243354-46a14500-e2ee-11eb-80ba-b54d4f55c164.jpg)
