### ISSUE TITLE
spiegel.de [Easylist Cookie]

### ISSUE THREAD

**Issue by spodermenpls** [easylist/easylist#8319]
### List the website(s) you're having issues:

`www.spiegel.de`

### What happens?

Easylist Cookie's rules that are deployed on this site lead to an unusable "faux-pay-wall" (after a recent change), that one has to pass before one can use the site. When one clicks the left hand "Akzeptieren und weiter" (= Accept and continue) button, it triggers an error message, saying that the needed cookies can't be deployed. The pay-wall works however while "Easylist Cookie" is being deactivated.

### List Subscriptions you're using:

uBlock filter family
Peter Lowe's list
Adguard Base, Tracking, Annoyances, German
Easylist, Easylist German
Easylist Cookie

### Your settings

- OS/version: Windows 10
- Browser/version: FF 89.0.2 64-bit
- Adblock Extension/version: uBlock Origin 1.36.2

**Comment by krystian3w** [comment]
@monzta

**Comment by ryanbr** [comment]
Can't be blocked sorry @spodermenpls

**Comment by spodermenpls** [comment]
> Can't be blocked sorry @spodermenpls

@ryanbr I am not requesting the (faux-)paywall to be removed as a whole, I know this would have legal ramifications. I inspected the site a bit closer, and know now exactly what changed, the used "privacy-mgmt.com" URL, that provides the resources for this paywall, is now wrapped in a First-party "spiegel.de" domain, which uBlock uncloaks back to "privacy-mgmt.com". Easylist Cookie blocks this domain, which is needed for the faux-paywall to work.

![cname](https://user-images.githubusercontent.com/23747593/125162927-f1005780-e18a-11eb-9e66-bf8e01c3fac7.JPG)

**Comment by krystian3w** [comment]
He use VPN because live in Australia 🇦🇺 / New Zeland 🇳🇿  (🇳🇨),

**Comment by spodermenpls** [comment]
@ryanbr I noticed that there is a "remove-spieg" branch from May, 27th that deletes most `spiegel.de` rules. Is a mere whitelisting of `privacy-mgmt.com` in context with this site out of question too, or what's the issue?
