### ISSUE TITLE
stromnetz-hamburg.de [Easylist Cookie]

### ISSUE THREAD

**Issue by spodermenpls** [easylist/easylist#8320]
### List the website(s) you're having issues:

`www.stromnetz-hamburg.de`

### What happens?

The Easylist Cookie rules that get triggered by this site cause the whole website to be blanked out. It's the same problem as reported over here: https://github.com/AdguardTeam/AdguardFilters/issues/87280#issue-935100524

### List Subscriptions you're using:

uBlock filter family
Peter Lowe's list
Adguard Base, Tracking, Annoyances, German
Easylist, Easylist German
Easylist Cookie

### Your settings

- OS/version: Windows 10
- Browser/version: FF 89.0.2 64-bit
- Adblock Extension/version: uBlock Origin 1.36.2

**Comment by krystian3w** [comment]
@monzta

**Comment by ryanbr** [comment]
Or just use Easyprivacy?
