### ISSUE TITLE
Reconsider ##.category-ad and ##.category-ads

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#8321]
### List the website(s) you're having issues:

`##.category-ad`
```
https://8field.net/ad
http://blog.affi-bank.com/category/ad
https://www.hira2.jp/category/ad
https://kotan.link/ad/adnetwork/
https://markekaizen.jp/ad/ad_c02/
https://netafull.net/ad
```

`##.category-ads`
```
https://azkk.co.jp/ads/
https://business-hack.net/category/ads/
https://clip.m-boso.net/ads/
https://www.freedom-shift.net/ad/aichaku/
https://iine-tachikawa.net/ad/
https://kt-life.net/category/ads/
```

![category-ad](https://user-images.githubusercontent.com/58900598/124938032-e63aab00-e042-11eb-8c95-216633267cd7.png)

### What happens?

Whole or nearly whole contents hidden by these rules on Japanese blogs having category "ad". I can give you more examples if given time. Note not all of them mean "advertising" - e.g. on `www.freedom-shift.net` "ad" is used to represent "attachment disorder". 

### List Subscriptions you're using:

uBO default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 89.0.2
- Adblock Extension/version: uBO 1.36.2

### Other details:

Pls consider to change them to specific rules like `##.ad`.

**Comment by krystian3w** [comment]
Worse if project lost all domains where filers work great and possible only add exceptions for Asia regions.

**Comment by Yuki2718** [comment]
I see but in the end these are cosmetic filtering - not -blocking - and EL already does the individual approach with huge domain list in e.g. `##.ad`, `##.advertisement`. The amount of FP here is way beyond the limitation of individual whitelist.

**Comment by Yuki2718** [comment]
@ryanbr Still hidden on e.g. `https://8field.net/ad` `https://kotan.link/ad/adnetwork/`
Can you also exclude article? i.e.g 

```
##.category-ad:not(article):not(html):not(body)
##.category-ads:not(article):not(html):not(body)
```

**Comment by krystian3w** [comment]
Try report to ABP Japanese too? Maybe once add exceptions in own project.

I no mean you CO-OP in AG Japanese.

**Comment by Yuki2718** [comment]
Since this FP is by EL, the best I can do is to open PR to whitelist them. There'll be many more but I won't try to fix them in uAssets/AG - too much work.
