### ISSUE TITLE
Animetake adblocker alert

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#834]
`https://animetake1.pro/watch/detective-conan-episode-888/`

Easylist + EasyPrivacy and EasyList Adblock Warning Removal

"<script>
	adblockDetect(function(adblockDetected) {

	    if (adblockDetected) {
	        document.getElementById("videocontent").innerHTML = '<img src="/img/warning.jpg"/>'
	    } 

	}, {
	    testInterval: 40,
	    testRuns: 5
	});
</script>"

**Comment by ryanbr** [comment]
`@@||animetake1.pro^$generichide`

Or Install the enhanced trackers list,
