### ISSUE TITLE
[EasyPrivacy]: Whitelist workplace.com

### ISSUE THREAD

**Issue by maletor** [easylist/easylist#8346]
Please consider to add workplace.com as excluded:

```
/referer_frame.$domain=~developers.facebook.com|~workplace.com
```

This is similar to what [Brave added in May](https://github.com/brave/brave-browser/issues/15629)

Workplace third party integration developers [can whitelist domains](https://developers.facebook.com/docs/messenger-platform/reference/messenger-profile-api/domain-whitelisting) for improved user experiences. This should not be a privacy concern.

**Comment by ryanbr** [comment]
@maletor   would need actual proof it's needed

**Comment by maletor** [comment]
These two photos should prove that the rule is too broad and blocks legitimate features.

<img width="745" alt="Screen Shot 2021-07-13 at 8 57 38 AM" src="https://user-images.githubusercontent.com/138785/125485328-9400bd6b-277c-441a-a8d2-9836cba9bb15.png">
<img width="651" alt="Screen Shot 2021-07-13 at 8 58 16 AM" src="https://user-images.githubusercontent.com/138785/125485338-cfab0c80-0088-4f01-aa91-53a53d3cf5c2.png">

**Comment by spirillen** [comment]
Don't forget to append this rules to get rid of there creepy cookie-trackers

`workplace.com##.uiLayer`

**Comment by ryanbr** [comment]
Won't be fixed, screenshot aren't enough.
