### ISSUE TITLE
Now.sh is not a "tracking server"

### ISSUE THREAD

**Issue by rauchg** [easylist/easylist#835]
Refs:

https://github.com/easylist/easylist/commit/9bfbcea9af619f3fb4af084c0efc000bc918e535
https://github.com/easylist/easylist/commit/38998f3ccb84c5fca500eb9cc39d454d6d1be60e

This is breaking a lot of production websites. We have been systematically and manually removing cryptocurrency proxies and miners from our services.

*Please* revert those entries. Our business is in enabling seamless deployment (https://zeit.co/now), not tracking people.

We have made a lot of improvements to our filters to prevent misuse, and continue to do so.

**Comment by rauchg** [comment]
@ryanbr have you had a change to review this? 🙏

**Comment by ryanbr** [comment]
Was removed a day ago

https://github.com/easylist/easylist/commit/5bf980e372671feea37f580e91f75e24277379eb

**Comment by rauchg** [comment]
Thank you so much. We'll continue actively monitoring and blocking traffic to Coin Hive!
