### ISSUE TITLE
Request to remove boxthislap.org from easylist

### ISSUE THREAD

**Issue by marcgenou** [easylist/easylist#8351]
### List the website(s) you're having issues:

boxthislap.org

### What happens?

I'm the owner of the site. Small site, getting thousand of readers per month... 
A picture with a link is at the bottom side of the page, another one in the top of the footer. Non invasive, respecting users, helping us to keep writing and pay server expenses.
Unfortunately on of the readers is collaborating with these project and putting us in same list of sites of multimillion companies and other companies with hundreds of employees.

That's not the spirit of what we think internet should be, where it remains free and with many people supporting each others.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
`Join` on https://acceptableads.com/ and submit the site there, would be source on Non-invasive adverts
