### ISSUE TITLE
producthunt.com

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#8356]
### List the website(s) you're having issues:

```https://www.producthunt.com/```

### What happens?

Segment tracker disguised as first party not being blocked

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/62358249/124452393-41884700-dd7e-11eb-9f76-7820fcee5844.png)

</details>

### Your settings

- OS/version:  Arch Linux
- Browser/version: Firefox 91.0b2
- Adblock Extension/version: Ublock Origin 1.36.3b3

### Other details:

```
https://segment-cdn.producthunt.com/
https://segment-api.producthunt.com/v1/p
https://segment-api.producthunt.com/v1/t
https://segment-api.producthunt.com/v1/t
https://segment-api.producthunt.com/v1/m
```

Suggested filters. Blocking the JavaScript does take care of API calls.

```
||segment-cdn.producthunt.com^
||segment-api.producthunt.com^
```

**Comment by spirillen** [comment]
This rule will get rid of the cookie + Sign-(up|in) overlay

`producthunt.com##.styles_container__3MbyP`
