### ISSUE TITLE
blackwot.ru

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/easylist#8358]
### List the website(s) you're having issues:

`https://blackwot.ru/`

### What happens?

Adblock detect  `||google-analytics.com/analytics.js` ~> **EasyPrivacy**

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-07-14_174550](https://user-images.githubusercontent.com/57287308/125642667-c08e4546-79f9-43d1-9d9d-6869d06dd541.png)
![2021-07-14_174544](https://user-images.githubusercontent.com/57287308/125642676-f924bef2-3ef0-4b9e-94f0-6192bee6ea29.png)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version: 1.36.2

### Settings
<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/125642825-ce4d0058-fd48-4cdb-8bf2-d92a8617f298.png)
</details>

**Comment by ryanbr** [comment]
We don't stop the anti-adblock in this case @P0Rtvine
