### ISSUE TITLE
sonichits.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8362]
### List the website(s) you're having issues:

`https://sonichits.com/video/Agapio_Racing_Team/Miss'_ovat_yksisarviset`

### What happens?

Various placeholders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/125946955-704ff30e-518d-4ac7-9529-7fd57335cc4b.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 91.0.4472.124 x64
- Adblock Extension/version: uBO 1.36.3b4 + IDCAC 3.3.1

### Other details:

I propose:
```
sonichits.com###right-ad
||sonichits.com/tf.php^$subdocument
sonichits.com###bottom_ad
```

![image](https://user-images.githubusercontent.com/22780683/125947403-3af87b8e-be9d-4429-80e4-b2a40b27f091.png)

**Comment by stephenhawk8054** [comment]
There are ads placeholders.

URL: `https://sonichits.com/`

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/141892350-87bc7d01-aa08-4ee7-83fb-d85c82545279.png)

</details>

Firefox 94.0.1, ublock 1.38.6 default

Proposed filters:

```
sonichits.com###lyrics-ad
sonichits.com###divStickyRightOuter
sonichits.com###div-insticator-ad-1
```
