### ISSUE TITLE
Easylist Cookie (and Annoyance lists generally) body and button issues on many websites

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#8367]
It is a somewhat common thing that there is a need to add `:not` exceptions to generic cosmetic filters in the Easylist Cookie list in order to unbreak websites. A sample rule from the list:

`###gdpr:not(body):not(html):not(input):not(button)`

I see here and there cosmetic rules that have `:not(body)` or `html` or `input `or `button` or `.checkbox` exceptions added to them... Easylist Cookie either
- Blanks out websites
- Removes accept buttons / checkboxes

When it matches to those elements.

I have couple of active pull requests and some non-actives as well, concerning these kind of issues.

I suggest using `:not` exceptions as a common practice for generic hiding rules in Easylist cookie. This would preemptively unbreak countless websites and reduce repetitive maintenance work in applying exceptions and whitelist entries. Imo it's pointless to add `:not` one after another for Easylist Cookie's generic rules. Why not to apply them to all entries? I wonder how many unreported broken websites there are...

So what I suggest, is that after each generic cosmetic entry, this exception would be added:

`:not(body):not(html):not(input):not(button):not(.checkbox)`

It might not look elegant mut it would unbreak a lot and reduce maintenance work. Body and html elements should never be blocked, for obvious reasons. Input, button and checkbox elements should not be blocked either.

**Comment by DandelionSprout** [comment]
Universally whitelisting `#@#button`, would cause problems for lists that block social media sharing buttons.

Whitelisting `#@#html` is actually a rather good idea, to the point I'll add it to https://github.com/DandelionSprout/adfilt/blob/master/FalukorvList.txt. I also see no real problems with `#@#body`.

I lack deep enough experience with `input` element to make any statements on that one.

**Comment by peace2000** [comment]
> 
> 
> Universally whitelisting `#@#button`, would cause problems for lists that block social media sharing buttons.
> 
> Whitelisting `#@#html` is actually a rather good idea, to the point I'll add it to https://github.com/DandelionSprout/adfilt/blob/master/FalukorvList.txt. I also see no real problems with `#@#body`.
> 
> I lack deep enough experience with `input` element to make any statements on that one.

`#@#html` or `#@#body` would just whitelist rules like ##html` or `##body`. They cannot be, unfortunately, used to whitelist html and body elements generally, if they are matched by for e.g. `##.cookie-banner` when `##.cookie-banner` is a value in a body or html element. (I whish they could be easily whitelisted in that way).

Well, buttons don't need to be universally whitelisted, if you just add `:not(button)` after each generic on Easylist Cookie list, it just tells to that entry not to match this element if it's a button. It doesn't whitelist anything so it wouldn't cause issues to social media button blockings. :)

`intput` elements are used for checkboxes. Sometimes when you are making an order on a website, you might have to tick a checkbox in order to proceed, but sometimes Easylist Cookie removes checkboxes, thus making it impossible to proceed on a specific function. Sample case: https://github.com/easylist/easylist/pull/6597

**Comment by DandelionSprout** [comment]
Some additional testing has led me to the following entries (for uBO and AdGuard):
```
*##+js(ra, class, html)
*##+js(ra, class, body)
```

It may seem like a pretty risky approach to simply remove all `class` values from all websites' `html` and `body` elements, but still.

**Comment by DandelionSprout** [comment]
Disregard my comment above. Turns it was an unbelievably bad idea to remove all `class` elements from such elements.

**Comment by peace2000** [comment]
This practice would make Easylist Cookie much more reliable https://github.com/uBlockOrigin/uBlock-issues/issues/1573 thus making it more safe to use as a Ubo stocklist. (Ofc I don't have power to decide which lists can get to Ubo's stocklists but I think that this would help and increase changes).

**Comment by ryanbr** [comment]
Removed ###gdpr

**Comment by peace2000** [comment]
> 
> 
> Removed ###gdpr

Ok, though these generic filters can still break many websites.

What about adding at least exception `:not(body):not(html)` after each generic entry? This would not clutter filterlist that much and would prevent these rules from at least blanking out any websites.

@ryanbr

**Comment by krystian3w** [comment]
Modern browsers started support:

`:not(body, html, input, button, .checkbox)`

https://caniuse.com/css-not-sel-list


Re-test need PaleMoon/Basilisk as not popular browsers.

**Comment by krystian3w** [comment]
https://codepen.io/css4-selectors-com/pen/PjrgXL
