### ISSUE TITLE
healthline.com cookie consent

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8378]
### List the website(s) you're having issues:
https://www.healthline.com/

### What happens?
When I try to open the website a cookie consent appear.

### List Subscriptions you're using:
Easylist cookie
Fanboy Annoyances

### Your settings

- OS/version:  Windows 10 Pro 
- Browser/version: Firefox 90
- Adblock Extension/version: Ublock 1.36.2

### Other details:
Here is a screenshot of consent: https://imgur.com/a/tU3RZ2X

**Comment by thinksheiscool** [comment]
Do
```
healthline.com##.window.css-yya393
healthline.com##.backdrop.css-1yj6vcu, .window.css-yya393, body:style(overflow: auto !important)
```
work well?

Also, I encountered newsletter thing at the lower side of the webpage.

**Comment by andreewmat** [comment]
> Do
> 
> ```
> healthline.com##.window.css-yya393
> healthline.com##.backdrop.css-1yj6vcu, .window.css-yya393, body:style(overflow: auto !important)
> ```
> 
> work well in uBlock Origin?
Yes, this is working fine, thank you! Hope will be added to easylist.

> Also, I encountered a newsletter thing at the lower side of the webpage.
If you talk about the wellness newsletter at the back of the page, then yes I see it. If you get some pop-up with "subscribe now"
as I saw on other websites, I don't see it on my end.

**Comment by andreewmat** [comment]
`
> healthline.com##.window.css-yya393
> healthline.com##.backdrop.css-1yj6vcu, .window.css-yya393, body:style(overflow: auto !important)

@ryanbr is this good for adding it to filter lists? for me, is workng fine, no issues.
