### ISSUE TITLE
waiting for pr to be merged for sentry cdn

### ISSUE THREAD

**Issue by adarsh0d** [easylist/easylist#8384]
https://github.com/easylist/easylist/pull/8302

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by chirag127** [comment]
By the way, I don't really understand why you want to whitelist browser.sentry-cdn.com ? What does it break ?

**Comment by adarsh0d** [comment]
if website come under ublock, it blocks the script from loading in the website, so app doesn't load

**Comment by chirag127** [comment]
> so app doesn't load

Which app?

**Comment by adarsh0d** [comment]
https://docs.sentry.io/platforms/javascript/guides/angular/angular1/, we follow these test on risepeople.com, there is a screenshot attached in the pr

**Comment by chirag127** [comment]
> we follow these test on risepeople.com,

you mean you are owner of risepeople.com and want of get the tracking unblocked on the app or site?

**Comment by spirillen** [comment]
Yes he is: https://github.com/easylist/easylist/pull/8302#issuecomment-876582545

**Comment by ryanbr** [comment]
Closing PR. 20 days later, and no details to reproduce this.
