### ISSUE TITLE
BTDB pop-up/pop-under ads

### ISSUE THREAD

**Issue by Mirellanmawl** [easylist/easylist#839]
I made a [pull request to change BTDB's old domain, btdb.in, to the current one, btdb.to](https://github.com/easylist/easylist/pull/838), in the easylist. However, even with that patch, pop-up/pop-under (not sure which one, or if both) are still present on the site. They come up upon clicking basically anything on the site, though not every single time.

**Comment by mapx-** [comment]
`*$script,domain=btdb.to,third-party`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/28e942c0a40def5cbf11fcf3bc6b0a980fe92f46
