### ISSUE TITLE
mp3rule.com Ads Still Showing

### ISSUE THREAD

**Issue by rajatmathurs** [easylist/easylist#84]
Hi,

When you open the below website on mobile

`http://mp3rule.com/download/11598/tere-sang-yaara-atif-aslam.html`

still showing ads "Download File In 4G Speed" & "Share on Facebook"  is also showing

https://s32.postimg.org/ulx2vkn4l/Screenshot_2016_07_07_19_21_33.png

The working filter to block them are

`mp3rule.com###mainDiv > .fshow > .fInfo > center:nth-of-type(2) > .fb-share-button-22.fb-share-button > span > b`
`mp3rule.com###mainDiv > .fshow > .fInfo > center:nth-of-type(1) > a[href^="http://click.union.ucweb.com/index.php"]`

Please add the above filters in EasyList

Thank you

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/50a8c687040537530048fe735d3ed31efe8aea84
