### ISSUE TITLE
https://www.myabandonware.com/ 4 ads' spaces not removed

### ISSUE THREAD

**Issue by Felipefpl** [easylist/easylist#8402]
Ads' spaces in the right side arent removed.

Plus this one in the middle of the page https://www.myabandonware.com/browse/genre/role-playing-rpg-5/

**Comment by DandelionSprout** [comment]
I propose:
```
myabandonware.com##div[class=menu]
myabandonware.com##.x725
```

**Comment by Felipefpl** [comment]
@DandelionSprout - thank you very much for the link, i hope your thread gets stickied on top, btw, did you see the oldest issues here from several months ago? It's a good idea to check on them since some may be fixed (or not).

**Comment by DandelionSprout** [comment]
I went through a lot of issue reports from the summer and autumn of 2020 in that thread, though only ones related to the main EasyList (e.g. not Cookie List).

In the next batch planned for Thursday-ish, I'm planning to go through PRs from 2019 and early 2020.

**Comment by Felipefpl** [comment]
That's great, i hope more ppl like you will join easylist in the future.
