### ISSUE TITLE
elitepvpers.com completely broken

### ISSUE THREAD

**Issue by Zerebokep** [easylist/easylist#8409]
### List the website(s) you're having issues:

`https://www.elitepvpers.com`

### What happens?

https://imgur.com/a/U4hnJB8

The screenshot should be self explanatory, everything seems to be broken, it's currently not possible to create new threads, replies, trades and so on.

### List Subscriptions you're using:

uBlock defaults (easylist)

### Your settings

ublock only

- OS/version: Mac OS Catalina
- Browser/version: Chrome 91.0.4472.77
- Adblock Extension/version: ublock v1.36.2

**Comment by ryanbr** [comment]
Looks fine here.
