### ISSUE TITLE
Webmail composing broken in ProtonMail

### ISSUE THREAD

**Issue by jasonstockman** [easylist/easylist#841]
This commit:
https://github.com/easylist/easylist/commit/eeb41188faf38c94f159ede3674b816cd23aa98c#comments

Breaks composing of email messages in the webmail service ProtonMail because the iframe CSS selector is too general.

**Comment by SMed79** [comment]
Fixed https://github.com/easylist/easylist/commit/9557d7664adabb11016ea252c61b28d26847d838
