### ISSUE TITLE
some websites need cosmetic filtering

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8415]
### List the website(s) you're having issues:
https://www.ultimatespecs.com/ with https://imgur.com/a/Eo8J3dN
https://www.ultimatespecs.com/car-specs/Volvo/127572/Volvo-V60-Restyling-D6-Plugin-Hybrid-AWD-Summum.html with https://imgur.com/a/AsfGUZY
https://www.automobile-catalog.com/ with https://imgur.com/a/IV11vN4
https://www.automobile-catalog.com/model/bentley/mulsanne.html with https://imgur.com/a/BV4ItKl

### What happens?
I see some placeholders on the specified websites as you can see on the imgur uploads.

### List Subscriptions you're using:
-Easylist Cookie
-Fanboy Annoyance

### Your settings
I'm using ony Ubllock origin as extension.

- OS/version: Windows 10 Pro
- Browser/version: Firefox 90.0.1
- Adblock Extension/version: Ublock 1.36.2

**Comment by ryanbr** [comment]
Should be resolved, force an update of the lists.
