### ISSUE TITLE
https://www.mysmth.net/nForum/#!article/ADAgent_TG/1257849 Can't be visited

### ISSUE THREAD

**Issue by GoldSunMonkey** [easylist/easylist#8426]
### List the website(s) you're having issues:

https://www.mysmth.net/nForum/#!article/ADAgent_TG/1257849

### What happens?

I can't visit the link

### List Subscriptions you're using:

EasyList

### Other details:
I have given you a mail to add the link to white list:
https://www.mysmth.net/nForum/#!board/ADAgent_TG
you have added a line in the EasyList
line55877：
@@||mysmth.net/nForum/board/ADAgent_$~third-party
But the link as below isn't still visited
https://www.mysmth.net/nForum/#!article/ADAgent_TG/1257849

Can you help to change the line to :
@@||mysmth.net/nForum/*/ADAgent_$~third-party

Thank you.

**Comment by ryanbr** [comment]
Did you even update the list? I guess not.

**Comment by GoldSunMonkey** [comment]
@ryanbr 
I have updated the newest list.
but we can't visit https://www.mysmth.net/nForum/#!article/ADAgent_TG/1257849
because the two links are different.

**Comment by GoldSunMonkey** [comment]
@@||mysmth.net/nForum/board/ADAgent_$~third-party doesn’t work for https://www.mysmth.net/nForum/#!article/ADAgent_TG/1257849.
it just works for another link.

**Comment by GoldSunMonkey** [comment]
it works,
Thank you.
