### ISSUE TITLE
Elektroskandia.no - Overlay modal (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#8429]
### Affected site:
`https://webshop.elektroskandia.no/`

### Issue:
Grey overlay modal.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filters:
* **Easylist Cookie List**
* **Fanboy's Annoyance List**

### Problem rules:
Various cookie blocking rules.

### Possible fix:
`elektroskandia.no##.modal-backdrop`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.3.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by peace2000** [comment]
https://github.com/easylist/easylist/pull/8431 This pull request should be accepted in order to avoid such issues again with this filter.

**Comment by peace2000** [comment]
This is a very common issue that Easylist breaks sites because filters match the body element.

https://github.com/easylist/easylist/issues/8367

**Comment by THEtomaso** [comment]
> https://github.com/easylist/easylist/pull/8431

That's good.
`elektroskandia.no##.modal-backdrop` is still needed though, in order to remove the remaining overlay modal!

_First post updated_
