### ISSUE TITLE
I hereby wish to officially join the EasyList team

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8430]
### List the website(s) you're having issues:

```
https://github.com/easylist/easylist/issues
https://github.com/easylist/easylist/pulls
```

### What happens?

At the time of writing, the EasyList repo has a backlog of 351 issues and 576 pull requests, with increasingly more of them having become a year old or older.

I wish to officially join the EasyList team, with file write access on GitHub.

Presuming that 60% of the backlog is about EasyList, I promise to resolve 150 reports or more within the first 10 days of team membership. Moreover, I would also be able to assist IndianList, Fanboy's Notifications Blocking List, and plausibly EasyList Germany.

I have all the qualifications needed, and a long-standing history of good listmaking work with virtually no blunders.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/126881437-d671153c-bd47-4ca1-936f-b8a6cee982d6.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 92.0.4515.107 x64
- Adblock Extension/version: uBO 1.37.1b0

### Other details:

![image](https://user-images.githubusercontent.com/22780683/126881450-7e6793c9-70e0-423c-9a2e-8afd7c5ced0b.png)

**Comment by peace2000** [comment]
In 2019, I actually asked about this matter: https://github.com/easylist/easylist/issues/4522 The situation is still the same. I don't know will this be closed as well but seriously, this situation looks bad. Old issues and pull requests shouldn't just rot there.

**Comment by ryanbr** [comment]
Because we don't accept every issue or PR request, or take our time doing so. isn't Bad. EL/EP can easily unnecessarily bloat, create potential False positives from every request. 

My original statement stands https://github.com/easylist/easylist/issues/4522

**Comment by DandelionSprout** [comment]
Reports like https://github.com/easylist/easylist/issues/5969 from August 2020, indicate that not all reports are handled within due time.

**Comment by ryanbr** [comment]
Sure, but it's not used a premise "I want to join..." not really how things operate. If it's important enough people get prodded.

**Comment by DandelionSprout** [comment]
Good point. I've decided to apply that principle now at #8432.

**Comment by peace2000** [comment]
@ryanbr You guys of course decide who should have write access but currently there aren't enough people who have it as many issues and pull requests have piled up. There are currently 48 active pull reqs I have opened: https://github.com/easylist/easylist/pulls/peace2000?page=1&q=is%3Aopen+is%3Apr+author%3Apeace2000 oldest are one year old and most of them are over 1 month old. Those feel pretty long periods of time... I'm not saying everything should be merged if they are not good enough but I hope they would at least be dealt with.

**Comment by hirorpt** [comment]
> EL/EP can easily unnecessarily bloat, create potential False positives from every request.

If you really wanted to reduce false positives, you would more quickly address the issues/PRs that report them.

**Comment by felix-22** [comment]
I agree with peace2000 and DandelionSprout

This repository has been too slow for a long time, it needs more people with write access, if something is open sourced and created for the community, it should also be created by the community, not appropriated by a small group of people who don't allow others, otherwise it's called dictatorship and autocracy, not democracy... then you might as well rename the list from EasyList to MyPirvateList. Why prevent community from helping?

**Comment by peace2000** [comment]
I don't know if GH makes this possible, but I have an idea: allow a pull request to me automatically merged if 2 or 3 trusted contributors approve it?

**Comment by felix-22** [comment]
> ryanbr : https://github.com/easylist/easylist/issues/4522#issuecomment-567375815 : we don't conduct internal stuffs in GH

If something is done by the community and for the community, it should be clear and transparent, not secret and concealed, what do you want to hide and why?

**Comment by spirillen** [comment]
> I don't know if GH makes this possible, but I have an idea: allow a pull request to me automatically merged if 2 or 3 trusted contributors approve it?

In some degree you can, it's not as powerful as gitlab, but it might be possible to setup something

<details><summary>Screenshot of setup of number of approvals for merge</summary>

![image](https://user-images.githubusercontent.com/44526987/132966505-07391e01-bbce-45e1-9473-f4d9682bef02.png)

</details>

**Comment by peace2000** [comment]
Lol, typo... was going to say "to be", not "to me" :D

**Comment by spirillen** [comment]
ok Hamlet :laughing:
