### ISSUE TITLE
Went through various reports from last year/winter

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8432]
### List the website(s) you're having issues:

`https://github.com/easylist/easylist/issues`

### What happens?

Provided that I understand the current outcome of #8430 correctly, the intended goal is to use @'s to make existing EasyList members aware of somewhat important reports to take care of. So I decided to apply it on a large scale and see if the approach is successful (i.e. can be repeated later).

@'ings: @ryanbr @monzta

! Should be accepted:
* https://github.com/easylist/easylist/issues/5467
* https://github.com/easylist/easylist/issues/6013
* https://github.com/easylist/easylist/issues/6248
* https://github.com/easylist/easylist/issues/6251
* https://github.com/easylist/easylist/issues/6271
* https://github.com/easylist/easylist/issues/6275
* https://github.com/easylist/easylist/issues/6288
* https://github.com/easylist/easylist/issues/6289
* https://github.com/easylist/easylist/issues/6290
* https://github.com/easylist/easylist/issues/6291
* https://github.com/easylist/easylist/issues/6293
* https://github.com/easylist/easylist/issues/6296
* https://github.com/easylist/easylist/issues/7213
* https://github.com/easylist/easylist/issues/8402 (Expands on https://github.com/easylist/easylist/issues/8162)
* https://github.com/easylist/easylist/pull/6908

! Fixed in AdGuard Base (Their fixes can be copied over):
* https://github.com/easylist/easylist/issues/5964
* https://github.com/easylist/easylist/issues/6078

! Fixed in uBlock Filters (Their fixes can be copied over):
* https://github.com/easylist/easylist/issues/6278

——————————————————————————

! Unable to reproduce:
* https://github.com/easylist/easylist/issues/5966
* https://github.com/easylist/easylist/issues/6082

! Too old (Should be closed): 
* https://github.com/easylist/easylist/issues/5398
* https://github.com/easylist/easylist/issues/6068
* https://github.com/easylist/easylist/issues/6093
* https://github.com/easylist/easylist/pull/5644
* https://github.com/easylist/easylist/pull/5645
* https://github.com/easylist/easylist/pull/5647

! Sites doesn't seem to be alive (Should be closed):
* https://github.com/easylist/easylist/issues/7249
* https://github.com/easylist/easylist/issues/6015

! Aren't ads (Should be closed):
* https://github.com/easylist/easylist/issues/6028
* https://github.com/easylist/easylist/issues/6256

! AAB (Should seemingly be closed):
* https://github.com/easylist/easylist/issues/5844

! Impossible to fix with ABP syntax
* https://github.com/easylist/easylist/issues/5925

! Unclear how to access abroad, even with VPNs
* https://github.com/easylist/easylist/issues/5065

——————————————————————————

! Safari-based (Unclear if these should be delegated to AdGuard Filters or not):
* https://github.com/easylist/easylist/issues/6043
* https://github.com/easylist/easylist/issues/6044
* https://github.com/easylist/easylist/issues/6045
* https://github.com/easylist/easylist/issues/6046
* https://github.com/easylist/easylist/issues/6047
* https://github.com/easylist/easylist/issues/6048

! Pale Moon-specific (I refuse to test on that browser for community reasons):
* https://github.com/easylist/easylist/issues/5808

! Requires accounts that I don't have
* https://github.com/easylist/easylist/issues/5252

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/126883545-24b5dbc9-801f-4f41-94bc-798b285e428f.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 92.0.4515.107 x64
- Adblock Extension/version: uBO 1.37.1b0 + IDCAC 3.3.1

### Other details:

None at the time of writing.

**Comment by neer9** [comment]
> ! Sites doesn't seem to be alive (Should be closed):
> 
> * [.org and .net mirrors of pornhub.com [NSFW] #5065](https://github.com/easylist/easylist/issues/5065)

pornhub.org is indeed alive if you can't access it that doesn't mean no one can access. This have even been discussed there.

**Comment by ryanbr** [comment]
Closing ticket.
