### ISSUE TITLE
okazii.ro

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8441]
### List the website(s) you're having issues:
`https://www.okazii.ro/`

### What happens?
The website is broken by EasyList Cookie.

### List Subscriptions you're using:
The filter lists which are enabled by default in uBlock Origin + EasyList cookie.

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin Version 1.37.0

### Other details:
```
okazii.ro#@##onetrust-consent-sdk
okazii.ro#@##onetrust-banner-sdk
@@/otbannersdk.$domain=okazii.ro
```
have made the overlay appear but at least the website becomes usable. There may be a way to have the cookie consent thing hidden and/or blocked in uBO.

**Comment by thinksheiscool** [comment]
After looking further for a fix a found that `okazii.ro##body:style(overflow: auto !important;)` without 
``` 
okazii.ro#@##onetrust-consent-sdk
okazii.ro#@##onetrust-banner-sdk
@@/otbannersdk.$domain=okazii.ro
```
fixes the issue on `https://www.okazii.ro/`
