### ISSUE TITLE
jazzradio.com

### ISSUE THREAD

**Issue by P0Rtvine** [easylist/easylist#8442]
### List the website(s) you're having issues:

`https://www.jazzradio.com/pariscafe`

### What happens?

Fingerprint.
<details>
<summary>Screen</summary>

![2021-07-26_110213](https://user-images.githubusercontent.com/57287308/126954892-ea67bda0-bf9e-4bf7-bae3-15f2eabaedc3.png)
</details>

### List Subscriptions you're using:
<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/126954771-2fc88eda-412e-450f-b328-2b9f20468df3.png)
</details>

### Your settings

- OS/version:  Windows 10 x64
- Browser/version:  Google Chrome 92.0.4515.107
- Adblock Extension/version:  uBO 1.37.0

**Comment by ryanbr** [comment]
Its fine, not suspect and will break other stripe services
