### ISSUE TITLE
`https://agar.io/#ffa`

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8445]
### What happens?
Ad placeholder on the left. I also encountered a banner and I'm not sure if EasyList should address it.

### List Subscriptions you're using:
The filter lists which are enabled by default in uBlock Origin + EasyList cookie.

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin Version 1.37.0

**Comment by ryanbr** [comment]
Should look fine now.
