### ISSUE TITLE
otakustream.tv

### ISSUE THREAD

**Issue by KonoromiHimaries** [easylist/easylist#845]
![2018-01-16 21_47_19-otakustream - watch anime online english subbed hd](https://user-images.githubusercontent.com/5884000/35011561-df6a24f6-fb06-11e7-8c08-56cc76ea950e.png)

i don't see any illustrations

my filters
easylist + polskie filtry

Nano Adblocker 1.0.0.27
Nano Defender 13.21
Chrome 63.0.3239.132

**Comment by BlazDT** [comment]
@Filter dev remove otakustream.tv from this rule:

`desi-tashan.org,mp3red.cc,mp3red.me,otakustream.tv##a[style]`

**Comment by ryanbr** [comment]
Resolved.
