### ISSUE TITLE
Novinky.cz is still broken

### ISSUE THREAD

**Issue by WalrusInAnus** [easylist/easylist#846]
As per https://github.com/easylist/easylist/issues/797#issuecomment-357638372
The site is still broken.
It's something in Easylist. I use both Easylist and Easyprivacy, but the latter doesn't break the layout.

**Comment by ryanbr** [comment]
Unless you can pinpoint the filter, I cant help.

**Comment by WalrusInAnus** [comment]
I don't know how to tell which one :(

**Comment by mapx-** [comment]
go into the logger of your adblocker, refresh the page, see what's blocked and post here what you see

**Comment by WalrusInAnus** [comment]
I switched to uBlock and the site works now.
