### ISSUE TITLE
game-state.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8469]
### List the website(s) you're having issues:
`https://www.game-state.com/`

### What happens?
Ad leftover(s) on the lower side of the page.

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/87933966/127485562-e85d901a-d774-4450-bda7-f3da1e73b52c.png)

- OS: Windows 10 (...)
- Browser/version: Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin Version 1.37.0

**Comment by ryanbr** [comment]
I'll leave this, not an easy fix.
