### ISSUE TITLE
pcgamesn.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8470]
### List the website(s) you're having issues:
`https://www.pcgamesn.com/`

### What happens?
ad placeholder/leftover

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/87933966/127486410-aaf6ec7f-7407-4f1e-a0f4-760324b5aa1f.png)

- OS: Windows 10 (...)
- Browser/version: Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin Version 1.37.0

### Other details:
![forpcgamesnelissuereportongithub](https://user-images.githubusercontent.com/87933966/127486515-514c91ae-d3f6-456a-892e-04163a813ef3.png)

**Comment by THEtomaso** [comment]
Fixed in **AdGuard Base filter**, 6 days ago:
https://github.com/AdguardTeam/AdguardFilters/blob/1c093655cc82c302dd319ab4469935a5efd10c48/EnglishFilter/sections/general_extensions.txt#L3289
