### ISSUE TITLE
cnnsofake.news

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8471]
**I did not intend to make a political statement by submitting this. I am not reponsable for the content of the website on which I identified something that may addressed under the EasyList umbrella.**
### List the website(s) you're having issues:
`https://cnnsofake.news/`

### What happens?

- Cookie-related annoyance
- Newsletter-related annoyance

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/87933966/127487283-1927e0fb-dd20-4f5a-acb0-975907ae6066.png)

**Comment by spirillen** [comment]
Didn't see the :cookie: issue but did find the spam box

```
! 2021-07-29 https://cnnsofake.news
cnnsofake.news###Widget15
```

**Comment by peace2000** [comment]
Cookie banner:

`cnnsofake.news##.bottompopup`
