### ISSUE TITLE
tiermaker.com

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8479]
### List the website(s) you're having issues:
`https://tiermaker.com/`

### What happens?
Ad placeholder

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/87933966/127497813-df355d82-b999-419f-931d-604d13186185.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin Version 1.37.0

### Other details:
![image](https://user-images.githubusercontent.com/87933966/127497720-ed359427-35de-4657-ac52-91dc78a29d42.png)

**Comment by DandelionSprout** [comment]
I propose:
```
tiermaker.com##.desktop-sticky
tiermaker.com##.np-slot
```
