### ISSUE TITLE
movieslegacy.com

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8480]
### List the website(s) you're having issues:
`https://movieslegacy.com/`

### What happens?
ad placeholder/leftover

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/87933966/127499168-033354fd-c80d-487e-a74d-6701e5a57bcb.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin Version 1.37.0

### Other details:
![image](https://user-images.githubusercontent.com/87933966/127498949-58decc31-3c89-42c3-97fa-d1553970280d.png)

**Comment by thinksheiscool** [comment]
Related with https://github.com/AdguardTeam/AdguardFilters/issues/89462

**Comment by ryanbr** [comment]
Too minor
