### ISSUE TITLE
Batch №2 of ancient EasyList issue reports

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8493]
### What happens List the website(s) you're having issues:

`https://github.com/easylist/easylist/pulls`

### What happens?

Considering the general success of #8432, here's batch №2 of the same approach, this time covering every single EasyList PR (e.g. not Privacy or Annoyances) from November 2020 or earlier.

@-ings: @ryanbr @khrin

—————————————————————————————

! Should be merged/accepted
* https://github.com/easylist/easylist/pull/6026
* https://github.com/easylist/easylist/pull/6148
* https://github.com/easylist/easylist/pull/6159
* https://github.com/easylist/easylist/pull/6164
* https://github.com/easylist/easylist/pull/6167
* https://github.com/easylist/easylist/pull/6171
* https://github.com/easylist/easylist/pull/6265
* https://github.com/easylist/easylist/pull/6283
* https://github.com/easylist/easylist/pull/6345
* https://github.com/easylist/easylist/pull/6346
* https://github.com/easylist/easylist/pull/6348
* https://github.com/easylist/easylist/pull/6354
* https://github.com/easylist/easylist/pull/6355
* https://github.com/easylist/easylist/pull/6361
* https://github.com/easylist/easylist/pull/6519
* https://github.com/easylist/easylist/pull/6520
* https://github.com/easylist/easylist/pull/6521

! Fixed in uBlock Filters (Their fix can be copied over)
* https://github.com/easylist/easylist/pull/6347

! Fixed in AdGuard Base (Their fix can be copied over)
* https://github.com/easylist/easylist/pull/3005
* https://github.com/easylist/easylist/pull/6558

! Fixed in uBlock Filters (Their fix can't be easily copied over)
* https://github.com/easylist/easylist/pull/3050

! Fixed in ABP Anti-Circumvention (Their fix can't be easily copied over)
* https://github.com/easylist/easylist/pull/5757

—————————————————————————————

! Rebase errors (Could potentially be treated as issue reports, since the PR's intended entries are valid on my end)
* https://github.com/easylist/easylist/pull/2909
* https://github.com/easylist/easylist/pull/3004
* https://github.com/easylist/easylist/pull/3015
* https://github.com/easylist/easylist/pull/3065
* https://github.com/easylist/easylist/pull/5756
* https://github.com/easylist/easylist/pull/6185
* https://github.com/easylist/easylist/pull/6264
* https://github.com/easylist/easylist/pull/6266
* https://github.com/easylist/easylist/pull/6282
* https://github.com/easylist/easylist/pull/6353
* https://github.com/easylist/easylist/pull/6518
* https://github.com/easylist/easylist/pull/6540
* https://github.com/easylist/easylist/pull/6549
* https://github.com/easylist/easylist/pull/6550
* https://github.com/easylist/easylist/pull/6561

—————————————————————————————

! Too old / Seem to no longer apply (Should be closed)
* https://github.com/easylist/easylist/pull/1864
* https://github.com/easylist/easylist/pull/2280
* https://github.com/easylist/easylist/pull/2794
* https://github.com/easylist/easylist/pull/2795
* https://github.com/easylist/easylist/pull/2803
* https://github.com/easylist/easylist/pull/2869
* https://github.com/easylist/easylist/pull/2877
* https://github.com/easylist/easylist/pull/2915
* https://github.com/easylist/easylist/pull/2917
* https://github.com/easylist/easylist/pull/2967
* https://github.com/easylist/easylist/pull/3016
* https://github.com/easylist/easylist/pull/3032
* https://github.com/easylist/easylist/pull/3049
* https://github.com/easylist/easylist/pull/3058
* https://github.com/easylist/easylist/pull/3079
* https://github.com/easylist/easylist/pull/3091
* https://github.com/easylist/easylist/pull/5677
* https://github.com/easylist/easylist/pull/5733
* https://github.com/easylist/easylist/pull/5752
* https://github.com/easylist/easylist/pull/5755
* https://github.com/easylist/easylist/pull/6170
* https://github.com/easylist/easylist/pull/6173
* https://github.com/easylist/easylist/pull/6174
* https://github.com/easylist/easylist/pull/6285
* https://github.com/easylist/easylist/pull/6286
* https://github.com/easylist/easylist/pull/6337
* https://github.com/easylist/easylist/pull/6351
* https://github.com/easylist/easylist/pull/6522
* https://github.com/easylist/easylist/pull/6525
* https://github.com/easylist/easylist/pull/6528
* https://github.com/easylist/easylist/pull/6552
* https://github.com/easylist/easylist/pull/6562
* https://github.com/easylist/easylist/pull/6563
* https://github.com/easylist/easylist/pull/6564
* https://github.com/easylist/easylist/pull/6565
* https://github.com/easylist/easylist/pull/6566

! Not ads (Should be closed)
* https://github.com/easylist/easylist/pull/3078

! Already fixed on the example page (Should probably be closed)
* https://github.com/easylist/easylist/pull/6486

! Lacks example pages (Should probably be closed)
* https://github.com/easylist/easylist/pull/2873
* https://github.com/easylist/easylist/pull/3019
* https://github.com/easylist/easylist/pull/5753
* https://github.com/easylist/easylist/pull/6124
* https://github.com/easylist/easylist/pull/6172
* https://github.com/easylist/easylist/pull/6546
* https://github.com/easylist/easylist/pull/6555
* https://github.com/easylist/easylist/pull/6556
* https://github.com/easylist/easylist/pull/6567

! Most likely too minor to meet EasyList's 2021 criteria
* https://github.com/easylist/easylist/pull/6524

—————————————————————————————

! Unable to test (Site is likely illegal to visit in most countries)
* https://github.com/easylist/easylist/pull/5730

! Too scared of viruses to test while turning off uBlock Filters and AdGuard Base
* https://github.com/easylist/easylist/pull/6547
* https://github.com/easylist/easylist/pull/6548

! 50:50 call
* https://github.com/easylist/easylist/pull/6517

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/127610847-40c17fec-de5d-4eb0-8f6b-4bb463e4e38e.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 92.0.4515.107 x64
- Adblock Extension/version: uBO 

### Other details:

None at the time of writing.

**Comment by hirorpt** [comment]
- https://github.com/easylist/easylist/pull/6337 is not obsolete and should be merged. 
I checked if Yuki2718's issues/PRs that report Japanese websites (https://github.com/easylist/easylist/pull/7103#issuecomment-825298158)

**Comment by krystian3w** [comment]
letters is sitll used #2280 please recover as own draft/pr.

**Comment by peace2000** [comment]
I don't understand why not to accept #2280, new users who are not aware of those letter, would definetely benefit.

**Comment by DandelionSprout** [comment]
The report was so old (Nov 2018), that it'd be better to make a Readme or ruleset from scratch instead. I have plans for it early next week.

**Comment by ryanbr** [comment]
A few of these can't be merged, need to be rebased.

**Comment by ryanbr** [comment]
Can you update this, or create a new report with actual mergable requests. @DandelionSprout

**Comment by DandelionSprout** [comment]
I didn't know it'd be mandatory for the requests to not require rebases. Give me some hours.

**Comment by DandelionSprout** [comment]
Okay, I've updated this now.
