### ISSUE TITLE
gomokuworld.com [EasyPrivacy - breakage]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#8498]
### List the website(s) you're having issues:

`http://gomokuworld.com/tournaments/205`

### What happens?

Breakage - games not loading, can't play games, the board is empty - stones, controls / buttons are missing.
This is caused by this filter `/analyze.js^`

### List Subscriptions you're using:

EasyPrivacy

### Other details:

Screenshoot 1: broken (empty board, stones and controls missing):

![capture_014_30-07-2021_18-10-57](https://user-images.githubusercontent.com/75935068/127681742-d6ddfec1-15eb-4823-8c4a-1667a07e12a2.png)

Screenshoot 2: fixed (the board contains stones and controls):

![capture_015_30-07-2021_18-11-13](https://user-images.githubusercontent.com/75935068/127681850-62efc7e6-ccb2-472a-a242-e91b25e42917.png)

**Comment by felix-22** [comment]
@ryanbr ok so after you closed it without fixing it I was wondering why, and I realised the issue happens only in Firefox, it's one of those stupid cases where the bug is on one browser and not the other...

**Comment by Khrin** [comment]
I'm on Firefox, I've got no hits for `/analyze.js^` and I didn't see any issue on the page.

**Comment by felix-22** [comment]
I guess because it has been fixed meanwhile https://github.com/easylist/easylist/commit/76973f8a3bc726ed66b198c60653c24c0430d8ca.
