### ISSUE TITLE
foodpanda tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8499]
```
https://perseus-productanalytics.deliveryhero.net/v1/insert/pandora/hits

||perseus-productanalytics.deliveryhero.net^
```

![Screenshot_20210731-001807_Trebuchet.png](https://user-images.githubusercontent.com/75058881/127682714-157a97f0-73e6-4b64-9cf1-29e682b49542.png)

**Comment by ryanbr** [comment]
not seen.
