### ISSUE TITLE
All domain with .club tld have their scripts blocked by a recently added rule

### ISSUE THREAD

**Issue by Maelstrom96** [easylist/easylist#850]
Hi,

This particular block seems really overkill and is targeting scripts on a whole top level domain. We're currently hosting front-end scripts on a .club domain and it's being blocked by this particular filter. 

Any reason? 

Example : https://pbs.fpimg.club/js/fpc-hls.min.js 

Commit : https://github.com/easylist/easylist/commit/8954e1071408e93c38371a6e0ccbde24e272a003#diff-4903e7590de76df1abe1703921a2c88b

**Comment by azizghuloum** [comment]
My single-page-app on https://jumla.club is completely broken by this!

**Comment by ryanbr** [comment]
Has been fixed.
