### ISSUE TITLE
Everything blocked?

### ISSUE THREAD

**Issue by ghs** [easylist/easylist#851]
Till past Friday everything worked as it should but Saturday morning all pages started to be blank. No matter if there are ads or not on them, they are blocked/wiped/no HTML. If ABP is disabled or Easy list is unchecked, content is shown back again.

Chrome Canary 66.0.3328.0. Easy list last updated 22.01.2018 ABP: 1.13.4

**Comment by seliver** [comment]
I can confirm this.
Chrome Canary 66.0.3328.0. 
Easy list  Last updated at 14:52:26 today
Here's a gist with the injected stylesheet I see on the developers console on a supposedly ad-free page: https://gist.github.com/seliver/9be919ebaecb62e509704781cc492e83

**Comment by mjethani** [comment]
See my comment on [Chromium bug 804179](https://bugs.chromium.org/p/chromium/issues/detail?id=804179).

This may be a bug in Chromium's user style sheet implementation, but in any case we need to identify the filter that's triggering it.

**Comment by mjethani** [comment]
This is [fixed](https://chromium.googlesource.com/chromium/src.git/+/5814e68d9cf56da28568855881c3d3944ada159e) in Chromium now.
