### ISSUE TITLE
Request to remove cfeucdn.com from easylist  

### ISSUE THREAD

**Issue by slthelion** [easylist/easylist#8512]
### What happens List the website(s) you're having issues:

http://netu.io/view_page.php?pid=4

### What happens?

Videos are loading from the domain cfeucdn.com and blocking that specific domain, it will break the player and it's forbidden to ban videos.

Image exemple : https://prnt.sc/1hzzgcc

### List Subscriptions you're using:

Ublock Origin

### Your settings

There are no conflicts with other extensions.

- OS/version: Windows 8.1 Pro
- Browser/version: Chrome 92..415.107
- Adblock Extension/version: Ublock Origin 1.37.2

### Other details:

||cfeucdn.com^

**Comment by THEtomaso** [comment]
Looks kinda nasty.
The video player itself is hosted @ `hqq.to`.
When accessing that domain, you're automatically redirected to `56.com` (blocked by **Dan Pollock's hosts file**), which in turn, results in a bunch of other dubious connection attempts!

**Comment by slthelion** [comment]
This domain is used for video delivery, not for AD Delivery. 
Dubios or not, it should be in that list.

**Comment by spirillen** [comment]
The sting is, this is a to headed one. If you are trying to access the $domain directly you will be redirected to some random porn

if the domain is used right, it serves porn...  

`037jav.com`: https://mypdns.org/my-privacy-dns/porn-records/-/issues/35
Uses:
  - cdn-s6.cfeucdn.com
  - h4ahsm.cfeucdn.com

While `hentaibros.com`: https://mypdns.org/my-privacy-dns/porn-records/-/issues/181
Uses:
  - cdn-s3.cfeucdn.com
  - dt53fg.cfeucdn.com
