### ISSUE TITLE
move anti-mining filters to easylist

### ISSUE THREAD

**Issue by mapx-** [easylist/easylist#852]
An idea: move the anti-mining filters to easylist.

ABP does not include easyprivacy by default (and there are no signs in the future something will change), so the users are exposed to all these threats. 

see https://issues.adblockplus.org/ticket/5910

@ryanbr

**Comment by ryanbr** [comment]
I support the move, but it'll require consensus among authors.

**Comment by Khrin** [comment]
For the time being, mining filters will remain in EasyPrivacy.
