### ISSUE TITLE
mail.163.com

### ISSUE THREAD

**Issue by cjx82630** [easylist/easylist#8548]
### List the website(s) you're having issues:
https://mail.163.com/ (privite site)
[The issue report](https://reports.adblockplus.org/4f0fff03-05c3-4b5d-8901-3397f0109739#tab=filters)

### What happens?

`||nos.netease.com^` in Easyprivacy blocked user's icon, [for example](https://nos.netease.com/mail-online/c257167c07acac21fcc8983cd4b8ac1c/mail180x180.jpg?imageView&thumbnail=100x100&timestamp=1628119737316) 
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/98b895bc04e1101f87cfaaef489e1265c3bb714c
