### ISSUE TITLE
player.tubia.com on spel.nl

### ISSUE THREAD

**Issue by JohnyP36** [easylist/easylist#8549]
### List the website(s) you're having issues:
`spel.nl`

### What happens?
Because of the filter `##.companion-ads` videos of player.tubia.com give a black screen on spel.nl  
(see screenshot)  

So I suggest this filter `player.tubia.com#@#.companion-ads`  
using `spel.nl` instead of `player.tubia.com` doesn't solve the problem, because this element is block as a dom of `player.tubia.com` (see screenshot)  

Maybe you can use this rule `@@||adservice.google.*/adsid/integrator.js$domain=player.tubia.com` as done in Adguard Base.

### List Subscriptions you're using:
- easylist
- easy privacy
- uBlock filters
- easylist dutch

### Your settings
I'm only running uBlock

- OS/version: Windows 10 21H2
- Browser/version: MS Edge v92
- Adblock Extension/version: uBlock 1.37.0

### Other details:
![image](https://user-images.githubusercontent.com/81161435/128315617-1500c455-6c3f-4981-8569-fab0c6f9e860.png)
![image](https://user-images.githubusercontent.com/81161435/128315891-8cd36cfc-5a36-4279-aa91-490bfd3a35ad.png)

**Comment by Khrin** [comment]
> Maybe you can use this rule `@@||adservice.google.*/adsid/integrator.js$domain=player.tubia.com` as done in Adguard Base.

Maybe not. It is used for anti adblocking and cannot be added to EasyList.
