### ISSUE TITLE
mobafire.com

### ISSUE THREAD

**Issue by RikoDEV** [easylist/easylist#857]
![mobafire](https://user-images.githubusercontent.com/18230443/35350091-1ac0a444-013d-11e8-879b-e69af59a8cfa.PNG)

my filters:
easylist + polish ublock filters

link: `https://www.mobafire.com/league-of-legends/build/paws-claws-amp-jaws-509971`

Firefox: 59.0b3
uBlock 1.14.25rc1
Nano Defender 13.24

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b7a46fe952fd09e5a163992ff0ebb79ee06ef65c
