### ISSUE TITLE
hallo-minden.de ad

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#8574]
### List the website(s) you're having issues:

`https://www.hallo-minden.de/nachrichten/dreiste-diebe-stehlen-kreissaege-und-abdeckplanen-35370.html`

### What happens?

Ad picture
![Unbenannt](https://user-images.githubusercontent.com/48647394/128573788-84df8e12-8d5a-4efa-a8ec-51562ec3e10b.PNG)

### List Subscriptions you're using:

uBlock Origin default with EasyList, EasyList germany and EasyPrivacy

### Your settings

- OS/version: Win 10
- Browser/version: Firefox
- Adblock Extension/version: uBlock Origin 1.37.2

**Comment by ryanbr** [comment]
Not Easylist, english only list.
