### ISSUE TITLE
taiwanese 104.com.tw ads

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8579]
```
104.com.tw###board-27
or
104.com.tw##.advert-type21, .d-flex ?
```

![image](https://user-images.githubusercontent.com/75058881/128623112-6ccb95d1-c513-4bec-b8f9-afa94c8d3676.png)

**Comment by ryanbr** [comment]
Easylist = English only, submit any international commits to the appropriate  regional lists
