### ISSUE TITLE
9anime

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#858]
I have Fanboy's Complete list, yet I see pop-ups from time to time when click anything on 9anime.ch

Some are blocked, but some not.

Links like this:
`https://3ba87e4828c5a95.com/1308557.html`

**Comment by ryanbr** [comment]
Is this still an issue? they changed the domain since.

**Comment by runboy93** [comment]
Yup, same with 9anime.is

Links like this appear almost each time you press something on webpage:
https://3ba87e4828c5a95.com/1/1407888/?var=1308557

**Comment by ryanbr** [comment]
Should cover most of it.

https://github.com/easylist/easylist/commit/98aa4c2ba084ff481466f6df82cf8ca6079806e9
