### ISSUE TITLE
Remove Google Plus Rules From Filter Lists

### ISSUE THREAD

**Issue by kah0922** [easylist/easylist#8587]
### List the website(s) you're having issues:

N/A
### What happens?
N/A

### List Subscriptions you're using:
Default lists + fanboy's social

### Your settings

- OS/version: Windows 11
- Browser/version: Firefox Nightly
- Adblock Extension/version: uBlock Origin Beta

### Other details:
Google Plus is dead and has been dead for years now. We really don't need filters removing Google Plus links anymore.

**Comment by DandelionSprout** [comment]
There have been instances of websites seemingly having forgot to actually remove their G+ embed buttons, leading to https://raw.githubusercontent.com/DandelionSprout/adfilt/master/SocialShareList.txt (whose work began in 2019) containing these entries:
```
##.btn-google-plus
##.googleplusshare
##a[class*=google_plus_share]
##a[href*="://plus.google.com/share?url="]
##a[href*="plusone.google.com"]
##a[onclick*="plus.google.com/share?"]
##div[href*="plus.google.com/share?url="]
||apis.google.com/*/+1/*button$subdocument
||apis.google.com/js/plusone.js^
```

**Comment by Yuki2718** [comment]
+1 for DandelionSprout , service shut down does not mean the filters became useless. E.g. At `knowyourmeme.com` `https://apis.google.com/js/plusone.js` is still running.

**Comment by ryanbr** [comment]
Leaving, will be eventually removed but too soon for some sites with old icons/divs.
