### ISSUE TITLE
techpowerup.com - too broad regex filters

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#8605]
### List the website(s) you're having issues:

`https://www.techpowerup.com/`

### What happens?

Some icons are blocked due to too broad regex.

`/^https?:\/\/.*tpucdn\.com\/(?!.*images\/|img\/|review\/|forums\/).*/$image,domain=techpowerup.com`

`/^https?:\/\/.*techpowerup\.com\/(?!.*img\/|review\/|forums\/).*/$image,domain=techpowerup.com`

![kuva](https://user-images.githubusercontent.com/17256841/128755393-7df1abdd-cc05-4251-9706-7171822477fe.png)

The site also knows that, lol:

![kuva](https://user-images.githubusercontent.com/17256841/128755600-446c44cc-ee91-427e-b926-1ef6d3c59e78.png)

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 90.0.02
- Adblock Extension/version: Ubo 1.37.3b7

**Comment by ryanbr** [comment]
Closing, aware of it.
