### ISSUE TITLE
Miner (web + mobile?)

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#861]
http://www.tubettajat.net/

Found about this:
https://murobbs.muropaketti.com/threads/mainaako-tubettajat-net-sivusto-kaeyttaejaen-koneella.1388542/

Picture about miner code on source:
https://i.imgur.com/ZLL6Yux.png

**Comment by SMed79** [comment]
https://github.com/hoshsadiq/adblock-nocoin-list/pull/113/commits/beeb8f456fd7ce56983746c39d1fe3d2be692c5d

@ryanbr @okiehsch fyi.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e0e7cb74310dda5c1bc1a4ec50748fdf5360ac34
