### ISSUE TITLE
DailyFX needs filters

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#8623]
### List the website(s) you're having issues:

`https://www.dailyfx.com/sentiment-report`

### What happens?

`https://www.reddit.com/r/uBlockOrigin/comments/p1wrei/dailyfx_needs_filters/`

### List Subscriptions you're using:

![ublock lists](https://user-images.githubusercontent.com/11689349/128931559-13b1760c-e3aa-491f-b857-3d3743587601.jpg)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by stephenhawk8054** [comment]
Ads placeholders in `dailyfx.com`.

URL:
`https://www.dailyfx.com/eur-usd`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/150271288-007f079d-b0b1-4c2b-acd6-3c3fc991bdd1.png)

</details>

Firefox 96.0.1, ublock 1.40.8 default

Proposed filter:

`dailyfx.com##.dfx-ad`
