### ISSUE TITLE
https://github.com/dynatrace-oss/ and others

### ISSUE THREAD

**Issue by pirgeo** [easylist/easylist#8634]
### List the website(s) you're having issues:

```
https://github.com/dynatrace-oss/
https://github.com/dynatrace-oss-contrib/
```

### What happens?

I have a bunch of problems with `/dynatrace-` being blocked in the EasyPrivacy list. Especially GitHub seems to be affected. We have a bunch of repositories in our company GitHub organizations, all of which have names starting with `dynatrace-` . This leads to URLs with the `/dynatrace-` string in them, and many of the GitHub pages being broken (see screenshots below). Furthermore, some internal sites are also affected. Is there any way of getting the rule refined in such a way that this does not happen anymore?
Thanks a lot!

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/78350108/129167321-03077425-a417-4424-a8f9-1d61d3f7370a.png)

### Your settings

- OS/version: Ubuntu 20.04
- Browser/version: Firefox 90.0.2
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

I assume all these problems are caused by the `/dynatrace-` entry in the EasyPrivacy list.

Commit information cannot be retrieved
![image](https://user-images.githubusercontent.com/78350108/129167641-3c145f9c-6a0f-4fe9-9cc5-df544ad2cce5.png)

Pull requests are not loading more than a few files:
![image](https://user-images.githubusercontent.com/78350108/129167717-75ded56f-6a75-4573-83b4-d5c936a68cb0.png)

Jump to file not working:
![image](https://user-images.githubusercontent.com/78350108/129168198-2240989b-daf0-498b-a686-e7deca54ca60.png)

**Comment by pirgeo** [comment]
Code search also seems to be broken.

**Comment by ghaydtner** [comment]
I have similar issues with a SaaS vendor (Salesforce) where the domain name starts with "dynatrace--p...." in the URL (and ends with "force.com").
