### ISSUE TITLE
rockstar.com cookie banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8639]
### List the website(s) you're having issues:
`https://www.rockstargames.com/`

### What happens?
There is a banner on the bottom of the screen.

### List Subscriptions you're using:
-Easylist Cookie
-Fanboy Annoyance

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ecff2ea0ee1a551d1b52b4b028100f0f4fd6bbfe
