### ISSUE TITLE
drive2.com cosmetic filtering

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8651]
### List the website(s) you're having issues:
`https://www.drive2.com/l/596116722746918036/`

### What happens?
There is a white banner on the bottom of the page, above the comments section.

### List Subscriptions you're using:
-easylist cookies
-fanboy annoyance

### Your settings
Im using only Ublock Origin.

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:
![screen03](https://user-images.githubusercontent.com/79897301/129438367-666f1706-b112-482f-9ced-68a91fce1902.jpg)

**Comment by THEtomaso** [comment]
`drive2.com#?#[class*="-block"]:-abp-has([id^="adfox_"])`

**Comment by andreewmat** [comment]
> `drive2.com#?#[class*="-block"]:-abp-has([id^="adfox_"])`

Thanks, this works well. Can be added to filter lists @ryanbr

**Comment by ryanbr** [comment]
Not an english site, shouldn't this be in an RU list
