### ISSUE TITLE
archiwum.allegro.pl adversite consent banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8652]
`https://archiwum.allegro.pl/`
### What happens?
There is a advertisment banner when I open the website.

### List Subscriptions you're using:
-easylist cookie
-fanboy annoyance

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by krystian3w** [comment]
test these:

`||allegrolokalnie.pl/assets/cookies-info.js$script,domain=allegrolokalnie.pl`

```
||assets.allegrostatic.com/opbox-gdpr-consent$script,stylesheet,domain=allegro.pl
||assets.allegrostatic.com/opbox-rodo-consent$script,stylesheet,domain=allegro.pl
```

**Comment by andreewmat** [comment]
> ||assets.allegrostatic.com/opbox-gdpr-consent$script,stylesheet,domain=allegro.pl
> ||assets.allegrostatic.com/opbox-rodo-consent$script,stylesheet,domain=allegro.pl

These 2 works good, the consent is gone. @ryanbr

**Comment by krystian3w** [comment]
First not work on `allegrolokalnie.pl`?

and why is used to block GDRP on `https://allegro.pl`?
