### ISSUE TITLE
tiktok.com

### ISSUE THREAD

**Issue by gemoshi07** [easylist/easylist#8654]
### List the website(s) you're having issues:
`https://www.tiktok.com/`

### What happens?
There is a banner cookie.

### List Subscriptions you're using:
Default ublock filter lists and fanboy annoyance.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 91
- Adblock Extension/version: Ublock 1.37.2

**Comment by krystian3w** [comment]
generic classes?

**Comment by andreewmat** [comment]
> generic classes?

Can you please ebalorate? Should I provide other info?

**Comment by krystian3w** [comment]
Not stable Html5 template.
