### ISSUE TITLE
some websites has cookie banner 

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8656]
### List the website(s) you're having issues:
`https://www.bravosport.ro`
`https://pantofsport.ro`

### What happens?
There is a cookie banner on both websites.

### List Subscriptions you're using:
-Easylsit Cookies
-Fanboy Annoyance.

### Your settings

- OS/version: Windows 10 Pro
- Browser/version: Firefox 91
- Adblock Extension/version: Ublock 1.37.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/54d79878906f2932a46ad2eb3be1baaef2c172bd
