### ISSUE TITLE
swissfon.pl

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#8657]
Page is broken due generic:

`/sme-facebook-`

blocked is mechanism to join many files into one:

`http://www.swissfon.pl/app/plugins/bwp-minify/min/?f=app/plugins/sme-facebook-likebox-sidebar/assets/style.css,app/themes/divi-ptr/style.css,app/themes/swissfon/css/bootstrap.css,app/themes/swissfon/style.css`

I suppose needed is:

`app/themes/swissfon/style.css`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/baa59250c003576aa04b6839a8e226ff1293cf07
