### ISSUE TITLE
Gif ad [hon3yhd.com]

### ISSUE THREAD

**Issue by The-Commissioner** [easylist/easylist#866]
https://www.hon3yhd.com/login.php

On the above site, there is a gif ad from cyber-planet.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f6bd93e2765de03803f1787d92a0335d73f7935e

**Comment by The-Commissioner** [comment]
@ryanbr I don't understand why you would just hide the ad and let it load in the background instead of blocking it altogether.
