### ISSUE TITLE
collegehumor.com [video ads]

### ISSUE THREAD

**Issue by adReporter1** [easylist/easylist#869]
video ads on collegehumor.com, can't block, domain is changing every time.

link:
`http://www.collegehumor.com/post/7055058/6-truths-about-being-obsessed-with-reality-tv`

screenshot:
`https://i.imgur.com/kejTnkc.png`

**Comment by peace2000** [comment]
That site does not exist as a standalone domain anymore, it's now being redirected to a Youtube channel. This issue can be closed. @Khrin
