### ISSUE TITLE
NSFW: txxx.asia

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#8703]
### List the website(s) you're having issues:
```
txxx.asia
```

## External relations?
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/274

### What happens?

 - [X] Exit popup -under redirecting to new site
 - [ ] AdWare 
 - [ ] Tracking

### List Subscriptions you're using:

- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist
- Peter Lowe’s Ad and tracking server list
- Spirillen's – Adblock Rules (https://mypdns.org/my-external-stuff/ublockorigin-rules/)

### Your settings

- OS/version: Ubuntu 20.04.2
- Browser/version: Tor-Browser & FF latest stable from Ubuntu repo
- Adblock Extension/version: uBlock Origin 1.37.2

**Comment by Yuki2718** [comment]
These exit prevention are done by inline-script and requires scriptlet to fix. It'll be better to report in uAssets (better all URLs listed in an issue).

**Comment by spirillen** [comment]
> These exit prevention are done by inline-script and requires scriptlet to fix. It'll be better to report in uAssets (better all URLs listed in an issue).

Better do one domain per issue :smirk: easier to keep disquission about one domain in one place :wink: 

Didn't check all of the changes you made in 7b1f737 butI'll recommend adding all domains from https://mypdns.org/my-privacy-dns/porn-records/-/issues/433 to https://mypdns.org/my-privacy-dns/porn-records/-/issues/476 which is closed, they all come from the same exit pool circus

PS: Thanks for breaking it down

**Comment by Yuki2718** [comment]
These crap sites can be categorized into a few clusters and within a cluster all domain share the same structure and thus the same fix can be applied, basically the same sites with different domain name. There's no reason to open individual issue, which is simply burden for us. I really don't wanna spend too much time on these craps.

**Comment by felix-22** [comment]
There was already an identical discussion not so long time ago: https://github.com/ryanbr/fanboy-adblock/issues/655, have fun reading before continuing your discussion! And I advice you guys to read carefully the whole discussion including visiting and reading links contained in it.

**Comment by felix-22** [comment]
@

**Comment by felix-22** [comment]
@spirillen could you close your issues, many of them have already been fixed in uBO almost 2-3 weeks ago: https://github.com/uBlockOrigin/uAssets/commit/7999ecaee35faa04151840587a78774f5e1bee24

@Yuki2718 keep in mind there is many more of them to fix (~8000), although I'm not sure whether you are interested...

**Comment by Yuki2718** [comment]
@felix-22 I'm not trying to fix all of them of course. My aim was freeing up non-techie user from the infinite redirect-loop by fixing some. They're most likely trapped by similar name of major porn sites (like `txxx.com`).

**Comment by spirillen** [comment]
> many of them have already been fixed in uBO almost 2-3 weeks ago:  

Ping me in chose of which the issue have been fixed and I'll close it.

**Comment by felix-22** [comment]
@spirillen  I've already provided you which ones are fixed, just take a look at the commit:

> felix-22 : https://github.com/easylist/easylist/issues/8703#issuecomment-914228253 : https://github.com/uBlockOrigin/uAssets/commit/7999ecaee35faa04151840587a78774f5e1bee24

**Comment by felix-22** [comment]
Who is responsible for closing fixed issues, the reporter or the repairer?
