### ISSUE TITLE
familyhandyman.com

### ISSUE THREAD

**Issue by adReporter1** [easylist/easylist#871]
ads stuck the page and the website is loaded after around 30 secs.
domain rotating.

link:
`https://www.familyhandyman.com/`

screenshot:
`https://i.imgur.com/wJOCAXa.png`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c0fdea6308f07b4bd4d4f9c358a4915f823fb1b0

Not as bad as you're showing.
