### ISSUE TITLE
wp-monero-miner

### ISSUE THREAD

**Issue by webmasterslava** [easylist/easylist#872]
Rules:
/wp-monero-miner/*
/wp-monero-miner.js
||wp-monero-miner.com^$third-party

Description:
Crypto mining plugin for WordPress, has a feature to start the miner automatically after page is loaded:
https://www.wp-monero-miner.com

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e1baad320c1ea27750fa7f7ceee28b2d25cd4d8c
