### ISSUE TITLE
hotflick.net - blocked images (Fanboy's Annoyance and Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#873]
The following rule (found in '**Fanboy’s Annoyance List**' and '**Fanboy’s Social Blocking List**') blocks some images at hotflick.net:
**-social-media-$image**

Example:
http://www.hotflick.net/u/g/?d=4934857

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a7b7b2be55f2985678f4048987f48d5f797da92d
