### ISSUE TITLE
NSFW: teensex.world

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#8736]
### List the website(s) you're having issues:
```
teensex.world
```

## External relations?
  - https://mypdns.org/my-privacy-dns/porn-records/-/issues/450

### What happens?

 - [ ] Exit popup -under
 - [X] Exit script redirecting to other porno sites
 - [ ] AdWare 
 - [ ] Tracking

### List Subscriptions you're using:

- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist
- Peter Lowe’s Ad and tracking server list
- Spirillen's – Adblock Rules (https://mypdns.org/my-external-stuff/ublockorigin-rules/)

### Your settings

- OS/version: Ubuntu 20.04.2
- Browser/version: Tor-Browser & FF latest stable from Ubuntu repo
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

**Comment by Yuki2718** [comment]
Forgot to mention but fixed by https://github.com/uBlockOrigin/uAssets/commit/7999ecaee35faa04151840587a78774f5e1bee24

**Comment by spirillen** [comment]
If you are bored, then cdn17tube.pro (cdngangsta.com) have updated/changed there exit popup/redirecting script

https://mypdns.org/search?scope=issues&search=cdngangsta.com

**Comment by Yuki2718** [comment]
> If you are bored, then cdn17tube.pro (cdngangsta.com) have updated/changed there exit popup/redirecting script
> 

I can't access either of domain, getting 404.

**Comment by spirillen** [comment]
> > If you are bored, then cdn17tube.pro (cdngangsta.com) have updated/changed there exit popup/redirecting script
> 
> I can't access either of domain, getting 404.

Hey @Yuki2718 

Was updating the server about that time, if it is mypdns you are referring to.

**Comment by Yuki2718** [comment]
I just can't access either `cdn17tube.pro` or `cdngangsta.com`.

**Comment by spirillen** [comment]
> I just can't access either `cdn17tube.pro` or `cdngangsta.com`.

Ahh that because they are CDN's :smirk: 

The reason I mentioned them is, as you said elsewhere, same CDN, same templates, same code. That why I left the search link above to find some to pick from :wink: 

My matrix project at work, who is related

<details><summary>First page from the search link above</summary>

![image](https://user-images.githubusercontent.com/44526987/130349571-8d1ce9f7-9a43-42f6-9c7d-796e6af5f079.png)

</details>
