### ISSUE TITLE
False positive - shortpixel.ai

### ISSUE THREAD

**Issue by pdobrescu** [easylist/easylist#8749]
### List the website(s) you're having issues:

```shortpixel.ai```
### What happens?

This domain is on your list and we don't consider it's in any of the cases when it should be listed here.
### List Subscriptions you're using:

Easylist Adservers Popup
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

ShortPixel is an [image optimization service](https://shortpixel.com) which uses a [WordPress plugin](https://wordpress.org/plugins/shortpixel-adaptive-images/) to optimize images on the fly and serve them from a CDN (we work with BunnyCDN as the CDN provider) using mainly the domain `cdn.shortpixel.ai`. For some reason this domain was blocked in [this commit](https://github.com/easylist/easylist/commit/dc4e8dd38c4ad8118a0e48662917ad0fdef963c2), maybe because that site was using at that time our services. 

As this is a domain only used to serve static content (such as images, CSS and JS files), we don't consider it should be blocked and I assure you of our full cooperation to do what is necessary for this domain to be removed from your list.

Thank you!

**Comment by pdobrescu** [comment]
Hello to all and thanks for all the work done around maintaining this list!

I just want to check what do we need to do in order to be removed. I can assure you there is no pop-up ever showing up from `cdn.shortpixel.ai`, because over 95% of the content from this domain are images (the rest are some PDF, CSS, JS and TXT files). Indeed we do have a presentation site on the root of the domain, but there is no pop-up or other banners present there (maybe this was happening back in 2019 when the domain was added, I can't say for sure). 

Since I opened this issue, our domain has been removed from other lists as well:
- https://github.com/StevenBlack/hosts/issues/1743
- https://github.com/jerryn70/GoodbyeAds/issues/231
- https://github.com/EnergizedProtection/block/issues/787

I would really appreciate your feedback on this and again I assure you that we'll fully cooperate to make sure whatever made us show up on this list won't happen again.

Thanks and have a great weekend!

**Comment by THEtomaso** [comment]
> I just want to check what do we need to do in order to be removed.

It would probably help if you could post a link to a page, where something is actually broken, when `shortpixel.ai` is blocked.

**Comment by pdobrescu** [comment]
hello @THEtomaso and thanks for getting back to me! Here's just one of the many sites that are using our services and where all images (and CSS files) are delivered from cdn.shortpxiel.ai:

https://gokid.ro/

If this site is viewed from a browser where easylist is active, you'd practically see a completely broken site with no images and no CSS files at all. 

Please let me know if you need other examples too.

**Comment by spirillen** [comment]
@pdobrescu 

I'm lost about your claim, the site seems pretty annoying and scammy with the filters on...

![image](https://user-images.githubusercontent.com/44526987/133937237-87e60a59-1a66-4426-acdb-8731ca876d85.png)

**Comment by krystian3w** [comment]
I see images and RWD template without obvious breakage.

**Comment by krystian3w** [comment]
> pretty annoying and scammy with the filters on...

Maybe this newsletter was added by local webmaster without use shortpixel.ai / BunnyCDN

**Comment by THEtomaso** [comment]
The page does indeed look broken at first, but after refreshing it once, all images from `shortpxiel.ai` loads just fine!
Don't see how this is related to the `$popup` rule in EasyList.

**Comment by krystian3w** [comment]
By nextdns?


https://github.com/easylist/easylist/issues?q=nextdns

**Comment by ryanbr** [comment]
Its fine here, closing ticket.
