### ISSUE TITLE
Recently update with problems with .club domains

### ISSUE THREAD

**Issue by matheusgnreis** [easylist/easylist#875]
The problem is that i have an ecommerce plataform and all uses our scripts and json with domain with .club. Our website is
CODE: SELECT ALL
http://www.e-com.club

, but our shops use our js files that have also .club js file. So we change the url of our plugins. But, when a client try to buy we have a script json with .club, and then also blocked and our client lost an order because of this adblock of his client. I will send a client'shop
CODE: SELECT ALL
https://www.doppelstore.com.br

We are trying to solve here, but I want know how adblock decided that domains .club is an ad?

https://cdn.ecvol.com/s/amoarte.e-com.club/uploads/block.png
https://cdn.ecvol.com/s/amoarte.e-com.club/uploads/block1.png
https://cdn.ecvol.com/s/amoarte.e-com.club/uploads/block2.png

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/f15bccffa2232a8c55ad3fd828a8df86ed788a33
