### ISSUE TITLE
unionlakepetservices.com

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#8752]
**Issue URL (Social Widget)** :
 https://unionlakepetservices.com/blog/why-your-dog-barks-at-nothing

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130137660-89da7831-8012-4746-91af-879c684f5b48.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by ryanbr** [comment]
too minor
