### ISSUE TITLE
earnzlink.blogspot.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8753]
### List the website(s) you're having issues:
`https://earnzlink.blogspot.com/`

### What happens?
Something that may be an ad (if it is an ad it does not look like it would be included in Acceptable Ads).

### List Subscriptions you're using:
The filter lists which are enabled by default upon installing Adblock Plus on Google Chrome.

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: Adblock Plus

**Comment by IMayKnow** [comment]
@ryanbr @Khrin 
![image](https://user-images.githubusercontent.com/89752791/131580598-16097fea-4df2-48e8-85d8-4fab9879ab93.png)

**Comment by ryanbr** [comment]
resolved
