### ISSUE TITLE
bestbuy.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8755]
### List the website(s) you're having issues:
`https://www.bestbuy.com/`

### What happens?
Annoyance leftover on the lower side of the page.

### List Subscriptions you're using:
uBO's enabled-by-default + Fanboy's Annoyance + uBlock filters -- Annoyances.

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin 1.37.2

**Comment by ryanbr** [comment]
Not seen
