### ISSUE TITLE
mediagalaxy.ro

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8757]
### List the website(s) you're having issues:
`https://mediagalaxy.ro`

### What happens?
Annoyance on the lower the side of the webpage.

### List Subscriptions you're using:
uBO's enabled-by-default + Fanboy's Annoyance + uBlock filters -- Annoyances.

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

**Comment by andreewmat** [comment]
Could you share an image with the annoyance found by you?

**Comment by ryanbr** [comment]
Looks fine, closed
