### ISSUE TITLE
igeeksblog.com

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8762]
### List the website(s) you're having issues:
`https://www.igeeksblog.com/`

### What happens?
Annoyance on the lower side of the page.

### List Subscriptions you're using:
uBO's enabled-by-default + Fanboy's Annoyance + uBlock filters -- Annoyances.

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
Looks fine, not sure what I'm looking for.
