### ISSUE TITLE
staples.com

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8768]
### List the website(s) you're having issues:
`https://www.staples.com/`

### What happens?
Annoyance (leftover)

### List Subscriptions you're using:
uBO's ebd + Fanboy's Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
Which annoyance? I'm not seeing issues here

**Comment by krystian3w** [comment]
Geolocked, need NE proxy/VPN 🇳🇱 .

**Comment by krystian3w** [comment]
```
Access Denied
You don't have permission to access "http://www.staples.com/" on this server.

Reference #............................................
````=

**Comment by thinksheiscool** [comment]
Have you tried with a US IP?

**Comment by krystian3w** [comment]
Faboyz live in New Zeland, so may also blocked page so see only small 3 lines instad CMS shop.

**Comment by ryanbr** [comment]
Maybe this? https://github.com/easylist/easylist/commit/d4a029b92613806695ff53ed52bf4b96f169c809

No others on the site. Closing ticket.
