### ISSUE TITLE
pb.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [easylist/easylist#877]
![2018-02-03-rowery na miare naszych czasow - puls biznesu - pb pl](https://user-images.githubusercontent.com/5884000/35761582-75af200c-088a-11e8-9875-bb7f7919b2f9.png)
`https://www.pb.pl/rowery-na-miare-naszych-czasow-833742`

empty sections

EasyPrivacy

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.30
Chrome 64.0.3282.140

</details>

**Comment by ryanbr** [comment]
Not seeing this, is it still an issue?

**Comment by KonoromiHimaries** [comment]
@ryanbr yes

**Comment by hawkeye116477** [comment]
For me is fine, no empty sections.
