### ISSUE TITLE
https://play.google.com/store cookie banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8777]
### List the website(s) you're having issues:
`https://play.google.com/store`

### What happens?
There is a cookie banner on the right side of the page.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by krystian3w** [comment]
Generate blank letfover at top.

for uBO may help then:

```
##.srp #searchform[style^="top: 50px"]:style(top: 20px !important;)
```

**Comment by andreewmat** [comment]
> Generate blank letfover at top.
> 
> for uBO may help then:
> 
> ```css
> ##[style^="top: 50px"]:style(top: 0 !important;)
> ```

So I should post my issue on ubo thread? 
This is my issue:
![screen](https://user-images.githubusercontent.com/79897301/130330534-64167502-0d5b-4bc3-9edb-2eaf6345d5d8.jpg)

**Comment by krystian3w** [comment]
You hide are addon you using - so your family tracking github to found illegal saw pages by on family rules.

**Comment by andreewmat** [comment]
Ublock is the only extension I use if this help.

**Comment by peace2000** [comment]
`||ogs.google.com/widget/callout?$subdocument,domain=play.google.com` ?

**Comment by andreewmat** [comment]
> `||ogs.google.com/widget/callout?$subdocument,domain=play.google.com` ?

Is working fine. The consent is gone.
