### ISSUE TITLE
gmod.facepunch.com

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8779]
### List the website(s) you're having issues:
`https://gmod.facepunch.com/`

### What happens?
Annoyance

### List Subscriptions you're using:
uBO's ebd + Fanboy's Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
Looks fine.

**Comment by thinksheiscool** [comment]
@ryanbr ![image](https://user-images.githubusercontent.com/89113298/130362098-731a241e-66d8-42e2-8b2d-0369ed2ad649.png)
