### ISSUE TITLE
fandom.com

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8781]
### List the website(s) you're having issues:
`https://www.fandom.com/`

### What happens?
Annoyance (leftover)

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/89113298/130339131-6e6b9168-923b-4f52-b40a-4041d3da6f45.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin 1.37.2

**Comment by ryanbr** [comment]
Looks fine.

**Comment by thinksheiscool** [comment]
@ryanbr 
![image](https://user-images.githubusercontent.com/89113298/130362134-7666d7c9-a991-4814-8e84-72565333dc5c.png)
![image](https://user-images.githubusercontent.com/89113298/130362142-0e1fe944-b41f-45ad-a621-e31dc33ad562.png)
