### ISSUE TITLE
socialblade.com

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8782]
### List the website(s) you're having issues:
`https://socialblade.com/`

### What happens?
Annoyance on the webpage

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/89113298/130339131-6e6b9168-923b-4f52-b40a-4041d3da6f45.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock origin 1.37.2

**Comment by ryanbr** [comment]
Looks fine.

**Comment by thinksheiscool** [comment]
@ryanbr
![image](https://user-images.githubusercontent.com/89113298/130362166-241d9170-7c72-43e0-b3fd-b04c7342ec8f.png)

**Comment by ryanbr** [comment]
Not an easy fix, not really worth
