### ISSUE TITLE
techxplore.com

### ISSUE THREAD

**Issue by thinksheiscool** [easylist/easylist#8783]
### List the website(s) you're having issues:
`https://techxplore.com/computer-sciences-news/`

### What happens?
annoyance

### List Subscriptions you're using:
![image](https://user-images.githubusercontent.com/89113298/130339131-6e6b9168-923b-4f52-b40a-4041d3da6f45.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

### Other details:
![image](https://user-images.githubusercontent.com/89113298/130339393-6ac922f9-4bb8-468a-a0cb-c3dc0aecba0f.png)

**Comment by ryanbr** [comment]
The others are fine.
