### ISSUE TITLE
sweetskendamas.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8792]
### List the website(s) you're having issues:
`https://sweetskendamas.com/`

### What happens?
Annoyance

### List Subscriptions you're using:
uBO's ebd + Fanboy's Annoyance + uBlock filters -- Annoyances

### Your settings

- OS/version: Windws 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
Looks fine
