### ISSUE TITLE
autokarma.ro cookie banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8796]
### List the website(s) you're having issues:
`https://www.autokarma.ro/`

### What happens?
There is a cookie consent banner on the bottom of the screen.

### List Subscriptions you're using:
Easylist Cookie
Fanboy Annoyance

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3b9a6ff24d234900bfc1a3b3d284f7ae40122408
