### ISSUE TITLE
guranco.ro banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8797]
### List the website(s) you're having issues:
`https://www.guranco.ro/`

### What happens?
On the bottom of the screen is a gdpr banner.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6947656b12803f4108ae48509bc4a6939098e69d
