### ISSUE TITLE
vest-auto.ro banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8799]
### List the website(s) you're having issues:
`www.vest-auto.ro`

### What happens?
There is a cookie banner on the bottom of the screen.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f9b1dad865bfb4cb87e36a243c95853e11f619e8
