### ISSUE TITLE
publicidade class is breaking site

### ISSUE THREAD

**Issue by ottonascarella** [easylist/easylist#88]
Hi there,

I developed a site for a film company, featuring their films.
They make films for advertising. 
I used the class "publicidade" for their movies,which are getting blocked because of the easylist.
Can I not add this domain as a whitelist for that specific class, since its clear that is NOT an ad?

**Comment by Khrin** [comment]
It's not possible for you to modify your site?

**Comment by ottonascarella** [comment]
Not not. And even if I could, it would not be only a simples CSS change, I
am afraid.

Thing is...to ban the word publicidade it's a bit too generic....wherereas
my change in the list would not affect anyone, anyway....would it?
Em 09/07/2016 09:44, "Khrin" <notifications@github.com> escreveu:

**Comment by Khrin** [comment]
Fixed https://github.com/easylist/easylist/commit/ea7ab8bead711eebc73c46e592b2aed84db5143b
