### ISSUE TITLE
masterani.me

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#880]
https://www.masterani.me/anime/watch/64-one-piece/824

Click on the video, you will notice popup flash. Didn't manage get URL, but maybe something to do with these:

`anime-watch-c9987d44ea.js`

`//c1.popads.net/pop.js`

`//c2.popads.net/pop.js`

**Comment by ryanbr** [comment]
Popups hard to stop, but we can be limit some of the damage. Force an update

**Comment by NexPB** [comment]
Way to aggressively block any link I want to open in a new tab now. Which people often do.

**Comment by NexPB** [comment]
Any update on this @ryanbr ?

Would love for users to be able to open links in new tabs from our comment sections...

**Comment by ryanbr** [comment]
From the page the comments work fine. the video works fine. Remove the popads is the best solution.  

You can do ads the right way, and the wrong way.

**Comment by NexPB** [comment]
@ryanbr  I know the comments and video loads well. 

It's about opening a link from a disqus comment in a new tab which is common browsing behaviour (the link won't open, you can only click it and navigate away from the page).

For these kind of sites this is the only way possible to sustain server costs, most ads are from the video hosts which I don't have control over either.

**Comment by ryanbr** [comment]
Okay, tweaked the filter; https://github.com/easylist/easylist/commit/c917b8ab061bea55ba211f01c025b16e368c0c8d

**Comment by ZaphodBeebblebrox** [comment]
Ads on pages such as `https://www.masterani.me/anime/watch/2514-boruto-naruto-next-generations/1`

Perhaps something like `masterani.me##a[href^="https://www.masterani.me/out/"]`
