### ISSUE TITLE
www.autopitonline.ro

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8803]
### List the website(s) you're having issues:
`https://www.autopitonline.ro/`

### What happens?
There is a cookie banner on the bottom of the screen.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/03e00203b513c425e510cccd06ea3ca032ecdd93
