### ISSUE TITLE
ricardo.ch

### ISSUE THREAD

**Issue by GuyXY** [easylist/easylist#881]
The rule `||stackpathdns.com^$third-party` breaks the images of the items that are for sale on ricardo.ch.
![image](https://user-images.githubusercontent.com/5495060/35780394-f22a45d4-09da-11e8-8b71-23b5a4101bdc.png)

**Comment by SMed79** [comment]
@GuyXY Don't submit **PR** without knowledge.

add
```
@@||imaginary-*.stackpathdns.com/resize?$image,domain=ricardo.ch
```
or
```
@@||imaginary-*.stackpathdns.com/resize?$image
```

https\://www.ricardo.ch/fr/a/969493790

@ryanbr @Khrin fyi.

**Comment by ryanbr** [comment]
Came from; https://github.com/keraf/NoCoin/pull/135

Made it a bit more specific.

https://github.com/easylist/easylist/commit/7d28b73e3ce165e23856ae6ec1d8687070e3a6f0
