### ISSUE TITLE
https://www.instagram.com/

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8824]
### List the website(s) you're having issues:
`https://www.instagram.com/`

### What happens?
Cookie consent banner.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by krystian3w** [comment]
test this:

`||graphql.instagram.com/graphql/`

based on https://github.com/easylist/easylist/issues/10567

**Comment by krystian3w** [comment]
see too: https://github.com/easylist/easylist/commit/1a9b8a7879274af00a1e111f49704c1473367680
