### ISSUE TITLE
www.bestkids.ro cookie banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8826]
### List the website(s) you're having issues:
`https://www.bestkids.ro/`

### What happens?
Cookie banner on the bottom of the screen.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9341fc0330704426fafe2229867c2c34cbb25f40
