### ISSUE TITLE
www.dailymotion.com

### ISSUE THREAD

**Issue by johansatge** [easylist/easylist#8833]
### List the website(s) you're having issues:

```
https://jsfiddle.net/61kz8g04/1/
```

### What happens?

When embedding a [Dailymotion](https://www.dailymotion.com/) player on a webpage, the whole player is blocked if `?ads_params=` is included in its URL.

Example:

```
https://www.dailymotion.com/embed/video/x82dy9e?ads_params=myAdsParams
```

<img width="200px" src="https://user-images.githubusercontent.com/5699295/130743784-72182b1b-250e-4203-a851-0eb128ae028c.png">

### List Subscriptions you're using:

<img width="200px" src="https://user-images.githubusercontent.com/5699295/130743420-13cb672e-cd8a-4e4a-b9eb-b48e0db3ecca.png">

### Your settings

- OS/version: macOS 11.4
- Browser/version: Firefox 91.0
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

Suggested solution: allow usage of the `ads_params` query string with the Dailymotion player, as detailed in the PR #8387.

Thanks!

**Comment by ryanbr** [comment]
Other than a testcase, is there working example 

This could apply to any other filter?  

`https://www.dailymotion.com/embed/video/x82dy9e?ad_size=myAdsParams`
`https://www.dailymotion.com/embed/video/x82dy9e?ad_width=myAdsParams`
`https://www.dailymotion.com/embed/video/x82dy9e?ad_ids=myAdsParams`

**Comment by johansatge** [comment]
Hey @ryanbr,
`ads_params` is the only concerned filter in my opinion, as it's the only query string we officially support in the Dailymotion player.

The other query strings listed in `easylist_general_block.txt` are not supported in the player, as far as I can tell (so having `https://www.dailymotion.com/embed/video/x82dy9e?ad_size=myAdsParams` for instance, would be an integration error)

**Comment by ryanbr** [comment]
Is there an example where it's broken? and (other than the url pasted) where it states `ads_params` is needed, like docs?

**Comment by johansatge** [comment]
Here is an example: https://www.leparisien.fr/video/video-30-kmh-a-paris-les-conducteurs-mitiges-sur-la-mesure-30-08-2021-NOYMC2VTBJCO3M4VLOTJE6Z2KY.php

<img width="200px" src="https://user-images.githubusercontent.com/5699295/131456429-3ae416ab-39fe-4a8c-938d-8e49cbfe54bf.png">

> and (other than the url pasted) where it states `ads_params` is needed, like docs?

We have an article that covers it: [How to customize request with the "ads_params” parameter](https://developer.dailymotion.com/data-api/customize-ad-tracking-ads-params-parameter/)

**Comment by jabonsolo** [comment]
@ryanbr this issue is due to rule removed here [9f00d0](https://github.com/easylist/easylist/commit/9f00d05e95e1b06293499858271fa4e6c17a9923).

I see some user issues coming from:
www.vidaextra.com
live.lequipe.fr 
www.xataka.com

i think it could be added back.

**Comment by johansatge** [comment]
Hello, good catch indeed 👍 

I'm not sure if reverting this rule will fix completely the issue though. If my understanding is correct, having `@@||dailymotion.com/embed/$subdocument` only allows the URL of the Dailymotion embed itself to be loaded (and only through an iframe)

Yet, not only `ads_params` is a valid query string to be passed to the Dailymotion iframe, but it may also be forwarded to other internal XHR calls during the lifecycle of the player; when loading a new video programmatically, for instance, as shown in the example below.

```html
<!-- Can be reproduced on https://jsfiddle.net/2xb7nv5y/ -->
<script src="https://api.dmcdn.net/all.js"></script>
<div id="player"></div>
<script>
  // 1. Inject a player iframe on the page (without "ads_params")
  var player = DM.player(document.getElementById('player'), {})
  // 2. Wait for the player iframe to be ready
  player.addEventListener('apiready', function() {
    // 3. Load a video through the JS API, with a specific "ads_params"
    //    Its value will then be forwarded to an internal XHR call,
    //    triggered by the player iframe to load said video
    player.load('x3rdtfy', {
      ads_params: 'someValue',
    })
  })
</script>
```

In this scenario, as visible in the capture below, the XHR call is blocked, preventing the video from playing.

<img src="https://user-images.githubusercontent.com/5699295/131545424-0aa7cecc-3aba-4b6d-b430-98ec7b398aab.png" width="500px">

With that use case in mind, would it be more efficient to allow `ads_params` on `dailymotion.com`, as suggested in #8387? (In addition or instead of reverting the rule removal mentionned in the previous comment)

**Comment by ryanbr** [comment]
Okay.

**Comment by jabonsolo** [comment]
This adjustment doesn't seem to be working, videos are still being blocked.
