### ISSUE TITLE
www.elitepvpers.com

### ISSUE THREAD

**Issue by Zerebokep** [easylist/easylist#8834]
### List the website(s) you're having issues:

`https://www.elitepvpers.com`

`https://www.elitepvpers.com/forum/sro-pserver-advertising/4940075-athens-online-l-cap-100-l-eu-ch-l-job-system-l-100-play2win-l-go-28-8-a.html`
`https://www.elitepvpers.com/forum/apex-legends-trading/4940118-apex-aplse-undetected-safe-cheap.html`
`https://www.elitepvpers.com/forum/valorant-trading/4940086-eu-valorant-immortal-account-immortal-badge-skins-cheap-valorant-points.html`
`https://www.elitepvpers.com/forum/escape-tarkov-trading/4940085-new-eft-cheat-esp-loot-esp.html`
`https://www.elitepvpers.com/forum/escape-tarkov-trading/4939819-zcheats-eft-developer-post-esp-aimbot-loot-price-more.html` <- just a few that I've found after browsing 1-2 minutes through the forums.

### What happens?

bit.ly links and discord attachments are getting removed inside users posts, we (traders and private server administrators) use them all the time, which makes most of threads unusable without disabling ublock.

### List Subscriptions you're using:

uBlock defaults (easylist)

### Your settings

ublock only

OS/version: Mac OS Catalina
Browser/version: Chrome 91.0.4472.77
Adblock Extension/version: ublock v1.36.2

### Other details:

easylist rules should be added in a way that it doesn't affect the post contents, legit projects are harmed by the way easylist implements their rules (censoring content instead of removing ads).

**Comment by ryanbr** [comment]
Link directly do the sites then and not use bit.ly, Only implemented because the site is using ads from embedded discord images.

I've temporarily removed the filters.  But even right now, it's being abused `​https://cdn.discordapp.com/attachments/797068819561447444/867676174217379890/proofcore2.abc`  to serve ads. Will be readdressed if the admin continues to serve ads from discord.

**Comment by Zerebokep** [comment]
@ryanbr I already do that, but I've used bit.ly mainly for the statistics, still most other threads are broken. To be honest, I have never checked what the procedures are for ad-block lists (is there even any Q&A?), it really baffles me that you are fine with censoring content in favour of removing ads, even if you could use negative lookaheads to exclude the post content area. You guys punish us for something we cannot control.

**Comment by Zerebokep** [comment]
By the way, your last update breaks the site again, creating new threads are not possible anymore (buttons are missing) and most navigation links are stripped (even the logout link).
