### ISSUE TITLE
petapixel.com [multiple big grey ad placeholders everywhere]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#8835]
### List the website(s) you're having issues:

Main site: `https://petapixel.com/`
Article subsites: `https://petapixel.com/2015/09/12/jpeg-2000-the-better-alternative-to-jpeg-that-never-made-it-big/`

### What happens?

Multiple big empty grey ad placeholders with "advertisement" text.

### Your settings

- OS/version: Windows
- Browser/version: Firefox & Opera
- Adblock Extension/version: uBO

### Other details:

Solution:
```
! (main site + partially subsites):
##.instream_ad
! (additional subsites):
###ppvideoadvertisement
```

Screenshoots:

Main site:
![capture_003_25-08-2021_12-56-53](https://user-images.githubusercontent.com/75935068/130779458-a62cc0b4-9bc9-40e2-8140-37e84e83a85d.png)
![capture_004_25-08-2021_12-56-56](https://user-images.githubusercontent.com/75935068/130779451-98dedb04-b9c1-4be6-ad14-e683c5800df8.png)
![capture_005_25-08-2021_12-56-59](https://user-images.githubusercontent.com/75935068/130779453-c22d1e05-34c0-4676-b3f7-09d6a45c59ed.png)
![capture_006_25-08-2021_12-57-02](https://user-images.githubusercontent.com/75935068/130779442-75ea3501-699e-4e99-97d2-5b4b9e7d4c7c.png)
![capture_007_25-08-2021_12-57-05](https://user-images.githubusercontent.com/75935068/130779446-616dda08-fbdb-4096-bc6d-30b4d6d4f4b2.png)

Artice subsites:
![capture_001_25-08-2021_12-55-35](https://user-images.githubusercontent.com/75935068/130779593-927f7488-83aa-4e8c-a5a8-c7d8f02c5a82.png)
![capture_002_25-08-2021_12-55-39](https://user-images.githubusercontent.com/75935068/130779601-2483a16a-7cf0-494e-a728-efc28eed47cf.png)

**Comment by stephenhawk8054** [comment]
Ads placeholder again

![image](https://user-images.githubusercontent.com/66517106/140499183-f5c9e889-aedc-42ce-8b7e-43e6188a0d2e.png)

Firefox 94.0.1, ublock 1.38.6 default

Proposed filter:

`petapixel.com##.video-aspect-wrapper`
