### ISSUE TITLE
https://aina.lt/skelbimai/ and setupad.com filtering

### ISSUE THREAD

**Issue by dimention** [easylist/easylist#8852]
### List the website(s) you're having issues:

`https://aina.lt/skelbimai/`

### What happens?

Iframe with source https://td.setupad.com/posting-list is marked as ad by Chrome browser and usually removed as HeavyAd.

### List Subscriptions you're using:

Chrome browser

### Your settings

- OS/version: MacOS
- Browser/version: Chrome 92
- Adblock Extension/version: none

### Other details:

I've submitted an Issue on the Chromium project: https://bugs.chromium.org/p/chromium/issues/detail?id=1242845

As you can see the issue lies in your filter list: https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers.txt#L14198

I'm a representative of SIA Setupad and would like to kindly ask you to remove setupad.com from the filter list completely, as we have moved all ad related scripts to stpd.cloud (which is already on the list). We use setupad.com as a business domain only now.

If you think removing whole setupad.com domain is not possible at this moment here are some alternatives:
1. change setupad.com to cloud.setupad.com - all ad related scripts were served from this subdomain
2. whitelist td.setupad.com - this is a classified ad SaaS platform, that is embedded into clients websites in a dedicated site path with a separate menu link.

**Comment by DandelionSprout** [comment]
I can add a temporary fix to https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt for `aina.lt` fairly quickly now, though I do agree that it'd be preferable if this international EasyList does eventually take care of this.
