### ISSUE TITLE
gogoanime.io

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#886]
`https://ww5.gogoanime.io/kokkoku-episode-5`

Click player and you notice new tab / popup flash, and then disappear, try both default player and CDN player.

Checked source and there seem to be many lines about ads / popups:

`https://ww4.gogoanime.io/js/ads_prebid.js`
`//jsc.mgid.com/g/o/gogoanime.io.180495.js?t=`
`//jsc.mgid.com/g/o/gogoanime.io.180497.js?t=`

**Comment by ryanbr** [comment]
Expected. working as intended.
