### ISSUE TITLE
hanime.tv (NSFW)

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#887]
`https://hanime.tv/`

Click anything on website, you notice popup:

`http://tds-01.atas.io/57ead26673b4db571a8b4583?cv1=%7Bpublisher_ID%7D&cv2=%7Bxuid%7D&banner=pops`

**Comment by ryanbr** [comment]
I cant stop redirects, but this might help on other issues;
https://github.com/easylist/easylist/commit/7b9e7b3b2c7e31b908009a58d8f164a334111dda
