### ISSUE TITLE
*.anilist.co

### ISSUE THREAD

**Issue by vzcatus13** [easylist/easylist#8871]
### List the website(s) you're having issues:  
`*.anilist.co`

### What happens?

Images on website with `/banner/468` in URL are blocked. Full URL to image `s4.anilist.co/file/anilistcdn/media/anime/banner/468-V8L7r2QZaNeS.jpg`

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Windows 10 19042
- Browser/version: Chrome 92.0.4515.159
- Adblock Extension/version: AdBlock 4.35.0

### Other details:

Rule is here: `easylist > easylist_general_block > "/banner/468"`

### Screenshot

![Imgur](https://i.imgur.com/EUXPKmR.png)

**Comment by vzcatus13** [comment]
As I don't see any activity, I will propose my **fix**.
`@@||*.anilist.co/file/anilistcdn/media/anime/banner/468`. 
Less strict, more unsafe `@@||*.anilist.co/file/anilistcdn/media/anime/banner/$image`

**Comment by Yuki2718** [comment]
First of all provide the *exact* URL to visit and test, I visited some `anilist.co` pages and see no such blockage. BTW `||*.domain.com` is one of the often seen wrong syntax, it works 'cause it's interpreted as a generic pattern-based filter but makes domain-anchor useless. `||domain.com` covers all its subdomain.

**Comment by vzcatus13** [comment]
> First of all provide the _exact_ URL to visit and test, I visited some `anilist.co` pages and see no such blockage.

I wrote that any image with `/banner/468` in the URL is blocked on any website, which means `example.com/api/article/666/banner/468jQKL.jpeg` would be blocked.
For example, image (`s4.anilist.co/file/anilistcdn/media/anime/banner/468-V8L7r2QZaNeS.jpg`) which is false positive is used here `anilist.co/anime/468` (_exact_ URL).
BTW, `anilist.co` has an open API, so images can and will be used anywhere, on any website or application.

> BTW ||*.domain.com is one of the often seen wrong syntax, it works 'cause it's interpreted as a generic pattern-based filter but makes domain-anchor useless.

Noticed. Proposed fix above edited. Thank u.

**Comment by Yuki2718** [comment]
Okay, I got it and confirmed. I personally think `/banner/468` can be removed since often actual targets are covered by other dimension rules, but it's EL maintainer's decision.
