### ISSUE TITLE
My abandonware resists

### ISSUE THREAD

**Issue by Felipefpl** [easylist/easylist#8879]
I'm using ublock and for some reason the site has its ads removed for a time then later they come back, i dont know why, there are ads in the middle and in the right side there are several spaces not removed, when using the picker from ublock you can see their spaces:

https://www.myabandonware.com/game/

**Comment by DandelionSprout** [comment]
I can reproduce this with ease. It looks like the site has begun to use supershort alphabetic class names to make it as impractical as possible to try to block them, but I know (to some extent) how to work my way around that too. As such, I propose:
```
myabandonware.com##div[class=menu]
myabandonware.com##.games > div[class*=" item "]
myabandonware.com##div[class*="itemListGame "]:not([class$=" "])
```

**Comment by Felipefpl** [comment]
> I can reproduce this with ease. It looks like the site has begun to use supershort alphabetic class names to make it as impractical as possible to try to block them, but I know (to some extent) how to work my way around that too. As such, I propose:
> 
> ```
> myabandonware.com##div[class=menu]
> myabandonware.com##.games > div[class*=" item "]
> myabandonware.com##div[class*="itemListGame "]:not([class$=" "])
> ```

Cool, this erases the 3, 4, 5 or whatever many ads are in the right side? Those are the most numerous and most likely to come back.

**Comment by Felipefpl** [comment]
Sorry but this was partially successfull, 2 ads spaces in the right side werent removed, only the one in the middle of the site.
