### ISSUE TITLE
apptrigger.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#8885]
### List the website(s) you're having issues:

`https://apptrigger.com/2015/06/16/get-10-disney-windows-apps-for-free-for-limited-time/`

### What happens?

Placeholder in the upper right, measured to 300x200px.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/131217904-1185598c-d085-4b5c-b205-15767a5a3504.png)

### Your settings

- OS/version: Windows 10 21H1 x64
- Browser/version: Chrome 92.0.4515.159 x64
- Adblock Extension/version: uBO 1.37.3b14 + IDCAC 3.3.2

### Other details:

![image](https://user-images.githubusercontent.com/22780683/131218674-eac8fe13-2b48-4461-9c83-da695033306f.png)

**Comment by Khrin** [comment]
I don't think it's blockable.
