### ISSUE TITLE
www.bursa.ro cookie banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8899]
### List the website(s) you're having issues:
`https://www.bursa.ro/`

### What happens?
There is a cookie banner on the bottom of the page.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4e4ca1a6187e3ae6272e2c84f4178000fe2510ae
