### ISSUE TITLE
history.com - broken video playback (Fanboy's Annoyance and Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#890]
The following rule (found in '**Fanboy’s Annoyance List**' and '**Fanboy’s Social Blocking List**') breaks video playback for some "preview" videos at history.com:
`_socialmedia_`

Example:
http://www.history.com/shows/the-curse-of-oak-island/season-5/episode-13/preview-unhinged/

--

**EDIT:**
The video in my example above has been removed now, and there doesn't seem to be any other previews available at the moment.
..but I'm sure that the rule in question was the perp, because after adding the following exception, the video played just fine:
`@@_socialmedia_$domain=history.com`

**Comment by ryanbr** [comment]
whats the full url thats being blocked?

**Comment by THEtomaso** [comment]
No way to find it now, and current previews seems to be unaffected.

**Comment by THEtomaso** [comment]
You can test the issue here now:
http://www.history.com/shows/the-curse-of-oak-island/season-5/episode-15/preview-steel-trapped/
Hurry up, before they remove this video too! :)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d4d78b1264811429d8e08efd317ad37f76bef64c
