### ISSUE TITLE
www.g2g.com cookie banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8901]
### List the website(s) you're having issues:
`https://www.g2g.com/`

### What happens?
There is a cookie banner.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/fd96dd0485cbdd741c9b9a82fd68cace9b1282c7
