### ISSUE TITLE
hp.com

### ISSUE THREAD

**Issue by IMayKnow** [easylist/easylist#8907]
### List the website(s) you're having issues:
`https://www.hp.com/us-en/shop/tech-takes/best-minecraft-mods`

### What happens?
Ad placeholders

### List Subscriptions you're using:
The ones which are enabled by default on PC in the latest version of uBlock Origin.

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome 92.0.4515.159 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

**Comment by ryanbr** [comment]
It looks fine here. I need more info.

**Comment by IMayKnow** [comment]
@ryanbr 
![image](https://user-images.githubusercontent.com/89752791/131421052-e30837ac-84e5-43e4-b101-8ee1063a5c6b.png)
![image](https://user-images.githubusercontent.com/89752791/131421087-21e6e674-9eeb-4a09-b3a5-1460c9931cf7.png)
![image](https://user-images.githubusercontent.com/89752791/131421112-b43ecf04-65f1-4e3a-bf1c-69cc8a82edf5.png)
![image](https://user-images.githubusercontent.com/89752791/131421129-c23f02c0-aa39-455f-bf84-33193e87691a.png)

**Comment by ryanbr** [comment]
Okay.
