### ISSUE TITLE
latelete.tv

### ISSUE THREAD

**Issue by smed79** [easylist/easylist#891]
```
.pw/ads/
/adss.htm
/ezban.
/newadsscript.
://pop.$script,subdocument,xmlhttprequest,third-party
```
```
###adb-enabled
```
```
$webrtc,domain=latelete.tv
```
```
cinestrenostv.tv##a[onclick]
cinestrenostv.tv##div[id][style*="z-index:"]
@@||cinestrenostv.tv^$generichide
```
```
livesports.pw###publi300
livesports.pw###divpubli
livesports.pw###adb-enabled
||pop.verplusonline.com^
```
```
playerfs.com##a[style]
```

http\://latelete.tv/fox-espana-online-en-directo-gratis-24h/
http\://latelete.tv/national-geographic-en-directo-en-castellano-por-internet/

http\://cinestrenostv.tv/canales/nacionales/fox.php
http\://cinestrenostv.tv/canales/documentales/nationalgeo.php

**Comment by peace2000** [comment]
Is this still relevant @smed79 ?

**Comment by Khrin** [comment]
Most of domains are apparently dead and some of proposed generic filters are already added.
