### ISSUE TITLE
twinfinite.net

### ISSUE THREAD

**Issue by IMayKnow** [easylist/easylist#8913]
### List the website(s) you're having issues:
`https://twinfinite.net/2021/05/best-euro-truck-simulator-2-ets2-mods/10/`

### What happens?
space

### List Subscriptions you're using:
The filter lists which are enabled by default in uBlock Origin on PC.

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b38d9825d3ec0dc42e1f70f05f063d19cd3d6f25
