### ISSUE TITLE
NSFW: 520cc.cc

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#8916]
### List the website(s) you're having issues:
```
520cc.cc
```

## External relations?
  - https://mypdns.org/my-privacy-dns/porn-records/-/issues/569

### What happens?

 - [ ] Exit popup -under
 - [ ] Exit script redirecting to other porno sites
 - [X] AdWare 
 - [ ] Tracking

## Screenshot
<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/44526987/131568783-5cb1f863-762f-4d81-8392-7cb17f1c6409.png)

</details>

### List Subscriptions you're using:

- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist
- Peter Lowe’s Ad and tracking server list
- Spirillen's – Adblock Rules (https://mypdns.org/my-external-stuff/ublockorigin-rules/)

### Your settings

- OS/version: Ubuntu 20.04.2
- Browser/version: Tor-Browser & FF latest stable from Ubuntu repo
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:
Thinking @Yuki2718 could help catching the textual links so not only the banners got blocked.

**Comment by ryanbr** [comment]
What exactly am I looking for? What is the suggested filters? @spirillen

**Comment by spirillen** [comment]
I did not suggest any filters because there are lot of banners (see screenshot above), and then I think there are a bunch of text ads. As I'm unsure about the text ads I pinged Yuki2718 in hope he can understand the letters

**Comment by Yuki2718** [comment]
This is a Chinese site and I don't see ads with AdGuard Chinese, default Chinese list for uBO/AG, enabled. So I think this issue can be closed.

**Comment by spirillen** [comment]
Super, we do that. 

thanks for your time @Yuki2718
