### ISSUE TITLE
[NSFW]pornhub.com

### ISSUE THREAD

**Issue by IMayKnow** [easylist/easylist#8917]
### List the website(s) you're having issues:
(NSFW)`https://www.pornhub.com/`

### What happens?
ad

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/89752791/131579148-1f483674-8aa9-4340-9e89-c354a429ff50.png)

</details>

### List Subscriptions you're using:
uBO's ebd

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

### Other details:
You may need to have a US IP in order to encounter the ad.

**Comment by IMayKnow** [comment]
@ryanbr was the filter removed?

**Comment by ryanbr** [comment]
no longer in use, also cause issues

**Comment by PizzaCalda** [comment]
could `pornhub.com##[href^="https://weedmaps.com/"]` be added?

**Comment by S0dV** [comment]
`pornhub.com##[href^="https://weedmaps.com/"`
