### ISSUE TITLE
bajafresh.com

### ISSUE THREAD

**Issue by IMayKnow** [easylist/easylist#8919]
### List the website(s) you're having issues:
`https://www.bajafresh.com/`

### What happens?
Annoyance

### List Subscriptions you're using:
uBO ebd (PC) + Fanboy's Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
Happy to leave this
