### ISSUE TITLE
Excesive blocking https://adrobot.io full blocked. new domain I bought

### ISSUE THREAD

**Issue by luishdez** [easylist/easylist#892]
I've got this domain that I bought: https://adrobot.io/ to create a sowftare. 
Adblock blocks all the assets directly It's a new domain

Other pages like https://adpage.io/ ( the service page ) are being blocked, and they don't use their base domain to serve Ads or anything like that.   ( Don't know them btw )

That is the same as block all the assets for https://adwords.google.com the service page.

Can we please fix that.  I think the culprit is `/adrobot.$domain=~adrobot.com.au`

Can I send a PR ?  

Thanks a lot.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/ed25a48a288171aad05e146e8834684aa8559b98

**Comment by luishdez** [comment]
/adrobot.$domain=~adrobot.io|~adrobot.com.au
I think you mixed the domains in the PR. You put adpage in the adrobot line.

Thanks for the PR
