### ISSUE TITLE
gamepur.com

### ISSUE THREAD

**Issue by IMayKnow** [easylist/easylist#8920]
### List the website(s) you're having issues:
`https://www.gamepur.com/guides/gta-rp-servers-best-servers-how-join`

### What happens?
space

### List Subscriptions you're using:
uBO's ebd on PC

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f1bc21cafd255b5f971f6bf35d4e849a724d32e3
