### ISSUE TITLE
cnn.com Paid Partner Content

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#8934]
### List the website(s) you're having issues: 

`https://cnn.com`

### What happens? 
- Paid Partner Content sections

<details><summary>Screenshot:</summary>

![Untitled](https://user-images.githubusercontent.com/52135169/131775474-ff753b52-77bf-486f-9491-0d431cf67dbc.jpg)

</details><br/>

### List Subscriptions you're using:

EasyList

### Your settings
![image](https://user-images.githubusercontent.com/52135169/131621897-bba5da86-2408-43be-a2cf-ebd01f8e2343.png)

- OS/version: Windows 10
- Browser/version: Firefox 91.0.2
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

I can see two sections, both highlighted in yellow the long screenshot above. One is roughly halfway through the page at the right side, the other before the page's footer.

**Comment by agam3r** [comment]
@ryanbr could you take a look at `https://www.cnn.com/`?

**Comment by Mennaruuk** [comment]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/52135169/140090541-7640bbe9-7273-4e1d-a6dd-753017437c36.png)

</details><br/>
