### ISSUE TITLE
kompas.com ad placeholders

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#8937]
### List the website(s) you're having issues: 

`https://money.kompas.com/read/2021/09/02/094400926/menteri-ppn--pembangunan-ibu-kota-butuh-waktu-sampai-20-tahun`

### What happens? 
- Many ad placeholders
- Video that keeps moving while scrolling

<details><summary>Screenshot:</summary>

![Screenshot 2021-09-01 at 23-24-36 Menteri PPN Pembangunan Ibu Kota Butuh Waktu Sampai 20 Tahun](https://user-images.githubusercontent.com/52135169/131776815-af5993cd-6ecc-4903-bbf9-901b49d0ee50.jpg)

</details><br/>

### List Subscriptions you're using:

EasyList

### Your settings
![image](https://user-images.githubusercontent.com/52135169/131621897-bba5da86-2408-43be-a2cf-ebd01f8e2343.png)

- OS/version: Windows 10
- Browser/version: Firefox 91.0.2
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

This is not restricted to the Money section. All sections of the website suffer from this.

**Comment by Khrin** [comment]
EasyList is for English-language sites only.
