### ISSUE TITLE
gadsdentimes.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#8955]
https://github.com/yourduskquibbles/webannoyances/issues/347
I encountered the annoyance while having Fanboy's Annoyance enabled.

**Comment by ryanbr** [comment]
Have looked at this in the past, they own many US local sites. (over a 100). I gave up

**Comment by yourduskquibbles** [comment]
@ryanbr here is string of domains for this publisher I put together and use if you want to get back in the game :P 

`ack.net,adelnews.com,advocatepress.com,aledotimesrecord.com,alicetx.com,amarillo.com,amestrib.com,amtrib.com,apalachtimes.com,ardmoreite.com,augustachronicle.com,auroraadvertiser.net,barnesville-enterprise.com,barnstablepatriot.com,bastropenterprise.com,bcdemocratonline.com,beauregarddailynews.net,blueridgenow.com,blufftontoday.com,boonevilledemocrat.com,boonvilledailynews.com,brownwoodtx.com,buckscountycouriertimes.com,burlingtoncountytimes.com,butlercountytimesgazette.com,cambridgechron.com,cantondailyledger.com,cantonrep.com,capecodtimes.com,carmitimes.com,carthagepress.com,charlestonexpress.com,cheboygannews.com,chillicothenews.com,chillicothetimesbulletin.com,chipleypaper.com,chronicle-express.com,cjonline.com,columbiadailyherald.com,columbiatribune.com,courier-tribune.com,crestviewbulletin.com,crookstontimes.com,daily-jeff.com,dailycomet.com,dailycommercial.com,dansvilleonline.com,devilslakejournal.com,dispatch.com,dodgeglobe.com,donaldsonvillechief.com,doverpost.com,eastpeoriatimescourier.com,echo-pilot.com,edinburgreview.com,ellwoodcityledger.com,enterprisenews.com,eveningtribune.com,examiner-enterprise.com,examiner.net,fayobserver.com,fosters.com,fowlertribune.com,gadsdentimes.com,gainesville.com,galesburg.com,galvanews.com,gastongazette.com,gctelegram.com,geneseorepublic.com,goerie.com,goupstate.com,grandlakenews.com,granitefallsnews.com,greenwooddemocrat.com,gridleyherald.com,hamburgreporter.com,hannibal.net,havenews.com,hdnews.net,helena-arkansas.com,heralddemocrat.com,heraldnews.com,heraldtribune.com,hillsdale.net,hockessincommunitynews.com,hollandsentinel.com,hopestar.com,houmatoday.com,hsvvoice.com,hutchnews.com,indeonline.com,jacksonnewspapers.com,jacksonville.com,jdnews.com,journaldemocrat.com,journalstandard.com,kinston.com,kiowacountysignal.com,kirksvilledailyexpress.com,lajuntatribunedemocrat.com,lakenewsonline.com,leavenworthtimes.com,leesvilledailyleader.com,lenconnect.com,lincolncourier.com,linkbostonhomes.com,linncountyleader.com,lonokenews.net,lubbockonline.com,mcdonoughvoice.com,mcphersonsentinel.com,metrowestdailynews.com,mexicoledger.com,miamiok.com,middletowntranscript.com,midlothianmirror.com,milfordbeacon.com,milforddailynews.com,moberlymonitor.com,monroecopost.com,monroenews.com,montenews.com,morningsun.net,mortontimesnews.com,moscowvillager.com,mpnnow.com,mtshastanews.com,mytownneo.com,ncnewspress.com,neagle.com,neoshodailynews.com,nevadaiowajournal.com,newbernsj.com,newcomerstown-news.com,newportindependent.com,newportri.com,news-journalonline.com,news-star.com,newschief.com,newsherald.com,newsrepublican.com,newstribune.info,northneighbornews.com,norwichbulletin.com,nwfdailynews.com,oakridger.com,ocala.com,ohio.com,olneydailymail.com,onlineathens.com,oriongazette.com,ottawaherald.com,palmbeachpost.com,paris-express.com,patriotledger.com,pawhuskajournalcapital.com,pbcommercial.com,pekintimes.com,picayune-times.com,pjstar.com,poconorecord.com,pontiacdailyleader.com,postsouth.com,pratttribune.com,pressargus.com,pressmentor.com,progress-index.com,prosperpressnews.com,providencejournal.com,pulaskinews.net,record-courier.com,recordnet.com,recordonline.com,recordstar.com,redwoodfallsgazette.com,registerguard.com,reviewatlas.com,ridgecrestca.com,rrstar.com,runnelscountyregister.com,salina.com,savannahnow.com,scsuntimes.com,seacoastonline.com,sekvoice.com,sentinel-standard.com,shelbystar.com,siftingsherald.com,siskiyoudaily.com,sj-r.com,sjnewsonline.com,sleepyeyenews.com,sooeveningnews.com,southcoasttoday.com,srpressgazette.com,starcourier.com,starfl.com,starnewsonline.com,statesman.com,staugustine.com,steubencourier.com,stjamesnews.com,sturgisjournal.com,stuttgartdailyleader.com,sussexcountian.com,swtimes.com,taftmidwaydriller.com,tauntongazette.com,telegram.com,teutopolispress.com,the-daily-record.com,the-dispatch.com,the-leader.com,the-review.com,thecabin.net,thecarbondalenews.com,thedailyreporter.com,thedestinlog.com,thegurdontimes.com,thehawkeye.com,theintell.com,thekansan.com,theledger.com,theperrychief.com,therecordherald.com,therolladailynews.com,thesuburbanite.com,thesuntimes.com,thetimesnews.com,thisweeknews.com,times-gazette.com,timesonline.com,timesreporter.com,timestelegram.com,topsailadvertiser.com,tuscaloosanews.com,uticaod.com,vanalstyneleader.com,vanburencountydem.com,vvdailypress.com,waltonsun.com,washingtontimesreporter.com,waxahachietx.com,wayneindependent.com,waynepost.com,waynesvilledailyguide.com,weeklycitizen.com,wellingtondailynews.com,wellsvilledaily.com,whitehalljournal.com,wickedlocal.com,woodfordtimes.com,yourglenrosetx.com,yourstephenvilletx.com,yourvalleyvoice.com`

**Comment by yourduskquibbles** [comment]
FYI @ryanbr I think a lot, if not most of these sites/publications have been purchased by usa today / gannett since I first put this string of domains together. From the sampling of sites I opened they all seem to use the `usatoday.com` site template.
