### ISSUE TITLE
www.g2g.com sort issue on firefox mobile 

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8960]
### List the website(s) you're having issues:
`https://www.g2g.com/categories/apb-reloaded-item`

### What happens?
When I try to sort the search, I can't reach the sort option, a grey screen appear. If I disable cosmetic filtering, the sort option is working fine.

### Your settings

- OS/version: Android 11
- Browser/version: Firefox 91.2
- Adblock Extension/version: Ublock Origin 1.37.2

**Comment by ryanbr** [comment]
Works for me.

**Comment by andreewmat** [comment]
> Works for me.

Even with Fanoby Annoyance enabled? Sorry that I forgot to mention my filter lists.

**Comment by ryanbr** [comment]
Closing. Re-checked. I only run annoyances btw.
