### ISSUE TITLE
Is it possible to trick EasyList into blocking non-ad?

### ISSUE THREAD

**Issue by SurDno** [easylist/easylist#8961]
Hey there!

I am a Fandom wiki editor and I want to add a banner to some pages that says something among the lines of: "Install an ad blocker for better browsing experience", since by default pages are infested with ads.

But I want for that message to disappear when the user **already uses an adblocker**. So I need to somehow trick it into thinking that this is an ad, when it is, in fact, not an ad.

Can someone guide me how to do this or at least point me to the right direction?

**Comment by DandelionSprout** [comment]
The easiest way from an adblocker point of view, is to give the element a `class` name that match a `class`-hiding entry in EasyList that'd be likely to be in that list for many years.

For instance, based on these 4 entries:
```
##.ad-big
##.ad-carousel
##.ad-push
##.adChoice
```
Then one could give the banner ≥1 of the following class names: `<div class="ad-big ad-carousel ad-push adChoice" (…)>`

The same can be done with `id` names; in that case it's entries that start with `###` (3 `#`'s) that should be matched.

The approach has only one downside: If any of the big 3 Anglosphere adblock lists (EasyList, AdGuard Base List, uBlock Filters) one day in the future decide to add `||fandom.com^$generichide`, then my solution would become useless overnight for that site.

**Comment by SurDno** [comment]
Seems to work. Thank you!
