### ISSUE TITLE
wapo.st (ad placeholder)

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#8969]
### List the website(s) you're having issues: 

`https://www.washingtonpost.com/politics/courts_law/texas-abortion-ban-jonathan-mitchell/2021/09/02/ecbd1124-0c17-11ec-aea1-42a8138f132a_story.html`

`https://www.washingtonpost.com/politics/2021/09/03/prepare-longest-presidential-campaign`

### What happens? 
- Ad placeholder

<details><summary>Screenshot:</summary>

![Screenshot 2021-09-03 at 11-10-59 Abortion opponents watch for violations of Texas ban as providers weigh legal options_censored(1)](https://user-images.githubusercontent.com/52135169/132028330-c79e3f19-c6ca-49ca-b617-d1c69c73c73a.jpg)

</details><br/>

### List Subscriptions you're using:

EasyList

### Your settings
![image](https://user-images.githubusercontent.com/52135169/131621897-bba5da86-2408-43be-a2cf-ebd01f8e2343.png)

- OS/version: Windows 10
- Browser/version: Firefox 91.0.2
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

This is what uBlock Origin gives me when I pick on the placeholder element:

`##div.bb.b.mb-lg-mod.db-ns.dn:nth-of-type(4)`

**Comment by ryanbr** [comment]
The most that can be done.
