### ISSUE TITLE
onlineradiobox.com cookie banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#8974]
### List the website(s) you're having issues:
`https://onlineradiobox.com/`

### What happens?
There is a cookie consent banner.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
We're already blocking this? @andreewmat 

```
##.alert--cookies
###alert_cookies
```

**Comment by andreewmat** [comment]
> We're already blocking this? @andreewmat
> 
> ```
> ##.alert--cookies
> ###alert_cookies
> ```

I get this window:
![screen](https://user-images.githubusercontent.com/79897301/132085490-7aa63878-3479-4465-8ba2-963b41eb7ce2.jpg)
