### ISSUE TITLE
netlify.com blocked

### ISSUE THREAD

**Issue by jayvdb** [easylist/easylist#898]
@ryanbr added http://netlify.com in https://github.com/easylist/easylist/commit/1da0345a2ce with intention to block http://alltube.tv/ , however this affects many more sites , such as https://github.com/coala/gci-leaders/issues/144 , https://gitlab.com/ciptamedia/ciptamedia-dev.gitlab.io/issues/78 , and countless others.

**Comment by jayvdb** [comment]
There is already  https://github.com/easylist/easylist/pull/894 closed, and open https://github.com/easylist/easylist/pull/895

**Comment by jayvdb** [comment]
Discussion at https://forums.lanik.us/viewtopic.php?p=131964

**Comment by jayvdb** [comment]
I've posted a note in that forum, pending moderation.

**Comment by ryanbr** [comment]
Maybe Netlify should maintain their site better;

https://info.greatis.com/howto/remove-cryptown-netlify-com.htm

Which is why its blocked.

**Comment by jayvdb** [comment]
It isnt their site.  http://netlify.com host websites created by other people on a subdomain.  One of those sites had bad code on it.  Netlify terminated that site.

How should they improve?

**Comment by jayvdb** [comment]
thx for https://github.com/easylist/easylist/commit/c8e6e46e179ba7e1721b4d2275b2a478671e82d3
