### ISSUE TITLE
Trying to jump to TSUKUMO's store is blocked by Easylist's  `://ads.$popup `

### ISSUE THREAD

**Issue by stm-x** [easylist/easylist#8990]
### List the website(s) you're having issues:
`https://kakaku.com/item/K0001279186/?lid=kmag_pc_pc_10099_item_mid`

### What happens?
Look at the title and the screenshot.
![無題](https://user-images.githubusercontent.com/86018494/132130918-49aaaba6-3d2e-4de1-93a9-7b6d60f5a78b.png)
![無題1](https://user-images.githubusercontent.com/86018494/132130924-bc21228e-2be1-40ce-a1f3-e051b0017c2e.png)

### List Subscriptions you're using:
Easylist only

### Your settings

- OS/version: Windows 10
- Browser/version: Microsoft Edge 93.0.961.38
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:
EDIT:Added settings

**Comment by Yuki2718** [comment]
On my end happens only if middle-clicked.

**Comment by stm-x** [comment]
It seems to be blocked by microsoft edge + ublock origin, but not by firefox + ublock origin.
<details><summary>on FireFox:</summary>

https://user-images.githubusercontent.com/86018494/132223740-cf0611f9-4615-46c9-994d-8422b8cc3346.mp4


</details>

<details><summary>on Microsoft Edge:</summary>

https://user-images.githubusercontent.com/86018494/132223893-cf4e0a43-2898-4f00-80aa-2c663e00391d.mp4


</details>
