### ISSUE TITLE
EasyPrivacy - growthhero.io

### ISSUE THREAD

**Issue by FireMasterK** [easylist/easylist#8999]
### List the website(s) you're having issues:

https://noahsbox.com/products/the-student-box

### What happens?

https://cdn.growthhero.io/sites/pixel.js isn't blocked

### List Subscriptions you're using:

uBlock Origin

### Your settings

- OS/version: Linux
- Browser/version: Brave
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

There's also a request to `https://master-shopify-tracker.s3.amazonaws.com/segmentTracker.js` that's not blocked.

Something like `||cdn.growthhero.io^$script` can block it.

**Comment by spirillen** [comment]
You probably forgot

```css
||shopifycloud.com^$ping,important
```

**Comment by ryanbr** [comment]
I'm fine with this script.
