### ISSUE TITLE
yahoo search ads

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#9]
https://search.yahoo.com/search;_ylc=X3oDMTFiN25laTRvBF9TAzIwMjM1MzgwNzUEaXRjAzEEc2VjA3NyY2hfcWEEc2xrA3NyY2h3ZWI-?p=popcorn+time&fr=yfp-t&fp=1&toggle=1&cop=mss&ei=UTF-8

Ads on the right (using Chrome)

**Comment by AlphaT3ch** [comment]
Using the latest version of the list, with no other lists active in Chrome, the ads are blocked and the AdBlock extension icon does reflect that result by displaying a ```1``` to show it has blocked that 1 advert.

**Comment by terrorist96** [comment]
Just tested again on a clean profile with no customizations. Only ABP installed and Easy List active. Still see ads on yahoo search.

**Comment by AlphaT3ch** [comment]
This is weird. I was using a sort of outdated version, worked fine. I updated it to take a screenshot and the ads appeared...

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/16dc0246a593047bdf59eccb18f009c6d61607f5
