### ISSUE TITLE
[NSFW] imagebam.com

### ISSUE THREAD

**Issue by HP-N550** [easylist/easylist#9000]
### List the website(s) you're having issues:

`https://www.imagebam.com/view/ME3EO8V`

### What happens?

crazysh*t msg on bottom image

### List Subscriptions you're using:

default uBO + fanboy annoyance + uBO annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 92.0
- Adblock Extension/version: uBO 1.37.2

**Comment by spirillen** [comment]
What exactly is it your are referring to?

![image](https://user-images.githubusercontent.com/44526987/132785531-46052054-56c2-448f-92d5-b5025ef79dce.png)

**Comment by ryanbr** [comment]
Has been resolved.
