### ISSUE TITLE
EasyPrivacy - vpro.nl

### ISSUE THREAD

**Issue by notDavid** [easylist/easylist#9001]
Images are not loaded when visiting for example https://www.vpro.nl/vproleden/lidmaatschap.html

Unloading EasyPrivacy solves the issue. See attached screenshots.

iPad, Safari, Adguard.

Thank you.

![image](https://user-images.githubusercontent.com/1530401/132236154-f435d44e-ae5f-4109-ad48-ffcfa74b393f.png)

![image](https://user-images.githubusercontent.com/1530401/132236197-57c6ae9e-f406-4ea9-9876-c8a027c9053f.png)

**Comment by notDavid** [comment]
If i see correctly, this is caused by:

`-analytics/analytics.` in https://github.com/easylist/easylist/blob/715a5e07024862415b373126cc9dd49047ed271d/easyprivacy/easyprivacy_general.txt#L30

which blocks `https://www.vpro.nl/.resources/vpro/themes/vpronl/js/jspm_packages/npm/vpro-frontend-module@1.0.2/vpro-analytics/Analytics.js`

Unblocking that seems to solve the issue, and does load all the images correctly.

**Comment by notDavid** [comment]
So this allow filter works in uBlock Origin in Firefox, but does not work in Adguard on iOS:

`@@||www.vpro.nl/.resources/vpro/themes/vpronl/js/jspm_packages/npm/vpro-frontend-module@1.0.2/vpro-analytics/Analytics.js$xhr,domain=www.vpro.nl`

**Comment by ryanbr** [comment]
Seems fine now, images loaded
