### ISSUE TITLE
rozblog.com

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#9009]
**Issue URL (Ads)** :http://nulldownload.rozblog.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/130938117-1403e66a-9d28-44e2-b3bb-2d7e99b7076b.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by spirillen** [comment]
I can see you have closed this topic, is that because you get time outs as I do?

![image](https://user-images.githubusercontent.com/44526987/144748272-0d477f31-30c4-4bb6-986e-74a47cdce7fb.png)

**Comment by chirag127** [comment]
> I can see you have closed this topic, is that because you get time outs as I do?
> 
> ![image](https://user-images.githubusercontent.com/44526987/144748272-0d477f31-30c4-4bb6-986e-74a47cdce7fb.png)

No, it's because it's fixed in Persian list.
