### ISSUE TITLE
MarieClaire.fr - blocked videos (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#901]
Problem rules:
```
/ima3.js
/videojs.ads.
```

Example:
http://www.marieclaire.fr/idees/diy-mariage-un-faire-part-personnalise-facile-et-raffine,1252662.asp

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/693fed59bed6be583c4d33e9bacc0cb293e13146
