### ISSUE TITLE
itworld.com/video - Broken page (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#902]
A rather strange issue this one, because I can't figure out which rule(s) to blame.
..but something in EasyList breaks this page:
https://www.itworld.com/video/

**Comment by okiehsch** [comment]
`itworld.com#@#.module`
fixes the issue.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/11a2c4fc99d75fd33985179e30b362d09749038b
