### ISSUE TITLE
www.imobiliare.ro pictures issue 

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#9020]
### List the website(s) you're having issues:
`https://www.imobiliare.ro/vanzare-garsoniere/bucuresti/lujerului/garsoniera-de-vanzare-XC0R00043`

### What happens?
I can't open the images from the link above. If I disable cosmetic filtering, is working fine.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by ryanbr** [comment]
Unfortantly the cookie message will show, but it'll fix the site.
