### ISSUE TITLE
hotflick.net - blocked images again (Fanboy's Annoyance and Social Blocking List)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#903]
The following rule (found in '**Fanboy’s Annoyance List**' and '**Fanboy’s Social Blocking List**') blocks some images at hotflick.net:
`-social-media-$~script,~stylesheet,~xmlhttprequest`

Example:
http://www.hotflick.net/u/g/?d=4823857

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/263bc8ed703eaa48c1d302bc0183cf0af58060bf
