### ISSUE TITLE
tayarijeetki.com

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#9033]
**Issue URL (Annoyance)**:https://www.tayarijeetki.com/communication-skills-2-pdf-notes/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/131225864-a7b8c2e6-fb43-424e-8d64-301d73a1267e.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by ryanbr** [comment]
Not seeing this.

**Comment by chirag127** [comment]
> Not seeing this.

Try to double click

**Comment by JobcenterTycoon** [comment]
@chirag127 its protected with javascript it can be fixed in https://github.com/uBlockOrigin/uAssets

**Comment by chirag127** [comment]
> @chirag127 its protected with javascript it can be fixed in https://github.com/uBlockOrigin/uAssets

Well I got that there syntaxes for scriptlets are specified but I can't understand how to use those that scriptlets . Does it have any other documentation for that? Or it need me to have knowledge of javascript?

**Comment by JobcenterTycoon** [comment]
Javascript knowlege is needed to know how it works but i not have much knowlege. Thats why i often not provide filters
