### ISSUE TITLE
2 sites with ads' spaces not removed.

### ISSUE THREAD

**Issue by Felipefpl** [easylist/easylist#9044]
spaces on top/bottom

https://co8.org/community/#post98810

my abandonware again escaped the added rules since the ads' spaces are still all around there in the middle/3 on the right side.

https://www.myabandonware.com/browse/theme/action-rpg-3a/

**Comment by stephenhawk8054** [comment]
Ads placeholders in `myabandonware.com`.

URL:
`https://www.myabandonware.com/browse/genre/sports-8/`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/147078144-bffd27ef-04ed-4562-a6c3-b768ddee5eed.png)

</details>

Firefox 95.0.2, ublock 1.39.2 default

Proposed filter:

`myabandonware.com##[id^="a1222"]`

**Comment by Felipefpl** [comment]
all ads' spaces are back now, before they were all removed, the ads are still blocked though.

**Comment by AroKol78** [comment]
I have been using it for many months
`myabandonware.com` = `zzz.xxx`
```
zzz.xxx##div[id$="ST"]
zzz.xxx##div[id$="SB"]
zzz.xxx##div[id$="CT"]
zzz.xxx##div[id$="CB"]
zzz.xxx##div[id$="STD"]
zzz.xxx##div[id$="CLX"]
zzz.xxx##div[id$="CBM"]
zzz.xxx##div[id$="CBM2"]
||zzz.xxx/media/img/wgm/
||zzz.xxx/media/img/gog/
```

**Comment by Felipefpl** [comment]
The Amiga/Atari ST sections below have ads spaces that arent removed by the existing rules:

https://www.myabandonware.com/game/prince-of-persia-pd

**Comment by AroKol78** [comment]
can be added to "My filters" https://github.com/uBlockOrigin/uAssets/issues/11153#issuecomment-1112507474

repairs of this type are short-lived (`n429` - https://github.com/easylist/easylist/commit/3a63c580d93308b6baf22aa36e9f679d4863d42e)

---
`https://www.myabandonware.com/game/elvira-ii-the-jaws-of-cerberus-2md` - empty space on the right
can be added to "My filters" (for the test)
`myabandonware.com##div[id$="ST"]`
`myabandonware.com##div[id$="SB"]`
`myabandonware.com##div[id$="STD"]`

**Comment by Felipefpl** [comment]
Well, since the devs at uassets didnt answer i thought posting here could be different. ;)

**Comment by AroKol78** [comment]
> repairs of this type are short-lived (`n429` - [3a63c58](https://github.com/easylist/easylist/commit/3a63c580d93308b6baf22aa36e9f679d4863d42e))

they will never fix it with this method - just checked and now there is `j503` instead of `n429`

**Comment by Felipefpl** [comment]
New ads were put recently in the page that arent blocked:

https://www.myabandonware.com/game/requiem-final-ihx

**Comment by Felipefpl** [comment]
New ads' spaces in the site showed up, adguard's list blocks them all without any exception, i dont know what they did for this.
