### ISSUE TITLE
(NSFW) winx-club-hentai.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#9046]
### List the website(s) you're having issues:

`https://winx-club-hentai.com/tag/tecna-porn/page/2/`

### What happens?

A dozen-ish ad banners for `whentai.com` through `r34.info`

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/132732832-75e8a551-a064-4767-8d8d-c04753eaeb24.png)

### Your settings

- OS/version: Windows 10 21H1
- Browser/version: Chrome 93.0.4577.63 x64
- Adblock Extension/version: uBO 1.37.3b21 + IDCAC 3.3.2

### Other details:

I propose `||ssl.hwcdn.net/rule34hentaitube.com^`, alternately `winx-club-hentai.com##.shr34`

Screenshot: https://images2.imgbox.com/60/1e/3wCNzMhJ_o.png

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d3dc1adfccae52eb13857a7fd25c5625d889fcb0
