### ISSUE TITLE
quora.com

### ISSUE THREAD

**Issue by ashurbainipal** [easylist/easylist#9048]
### List the website(s) you're having issues:

`https://marketingtipsstrategies.quora.com/`

### What happens?

When I enable EasyList in uBlock, I can't see stories anymore.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS BigSur 11.4 (20F71)
- Browser/version: Chrome 92.0.4515.159 
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

Suspected filter: `quora.com##.qu-pb--medium.q-box .qu-pt--medium`

### Without that filter

![image](https://user-images.githubusercontent.com/63620678/132741190-09da8939-a8ae-4393-980c-94bd3244df60.png)

### With the filter

![image](https://user-images.githubusercontent.com/63620678/132741245-294c521d-669b-4eae-8d0e-8f57a8256dd9.png)

**Comment by uBlock-user** [comment]
https://github.com/easylist/easylist/commit/2f231d7a1ec31e375bb53a0e922f310125583b14#diff-d95e1ad0368a5fb3bacb89fc7f209b9fa33a9974d9d2cf4b9a98903b7aa356a2

force update ublock filters lists
