### ISSUE TITLE
data.beop.io

### ISSUE THREAD

**Issue by bloodyowl** [easylist/easylist#9051]
Following up https://forums.lanik.us/viewtopic.php?f=91&t=46665

We (BeOp) provide two kinds of service to publishers on the web:

- an editorial one, so that publishers can animate their pages by collecting feedback, provide quizzes & personality tests
- a sponsored one, so that publishers can generate revenue

We previously came forward to the EasyList org so that two of our domains are blocked from EasyList:

- s.beop.io: our ad server
- ads-tracking.beop.io: our sponsored analytics events server

This allows us to fallback to another domain (contents.beop.io, only capable of returning **non-sponsored contents**) when blocked, so that we can still provide value to publishers in those cases (animating their pages with quizzes for instance).

The issue today is that recently data.beop.io was added to EasyPrivacy (https://github.com/easylist/easylist/commit/11f1aff994c6519abbee1ea7f699efcc4765da52) which breaks our editorial quizzes & personality tests. data.beop.io is our **REST API**, that is a huge issue because many of our publishers create dedicated pages for these quizzes, and it breaks those pages.

![AZzgaIj](https://user-images.githubusercontent.com/1688645/132815214-2372315a-18eb-47ad-a856-b3daa0f217ed.png)

Can you explain to me the reason why data.beop.io was blocked recently? Is there a way to go back to the previous state of things, where all of our ads were blocked and the editorial widgets delivered?

**Comment by ryanbr** [comment]
Example of a broken page would help here @bloodyowl

**Comment by bloodyowl** [comment]
https://www.legorafi.fr/2021/08/19/test-etes-vous-un-gouvernement-taliban-inclusif/

**Comment by spirillen** [comment]
You mean this ad place holder that I'm going to add??

```css
legorafi.fr##.akcelo-placeholder
legorafi.fr##.theiaStickySidebar
```


![image](https://user-images.githubusercontent.com/44526987/133004523-a3e0b197-9857-4c0d-ba45-848b0f80a824.png)
