### ISSUE TITLE
desidime.com

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#9060]
```
https://www.desidime.com/
```
### What happens?

Tracker not blocked. Although it doesn't seem to be firing at the moment. Guess it is limited to bot user agents at present.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/62358249/124452393-41884700-dd7e-11eb-9f76-7820fcee5844.png)

</details>

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 93.0b3
- Adblock Extension/version: Ublock Origin 1.37.3rc0

### Other details:

```
https://sunlightmetrics.b-cdn.net/sunlight.min.js
```

Suggested filter
```
||sunlightmetrics.b-cdn.net^
```

**Comment by spirillen** [comment]
For what I understand and can read from the script, then this script and service is all about measuring google search bot not users.

Specially this part of the script tells me it searching for search engines bots.

I can be wrong...

```js
window.addEventListener("load",function(){(/googlebot/.test(useragent)||/bingbot/.test(useragent)||/msnbot/.test(useragent))&&pingSunlight()},!1);
```

`sunlight.min.js`

```js
var useragent=window.navigator.userAgent.toLowerCase();function sunlight_checksum(t){var n,e=0,i=t.length;if(0===i)return e;for(n=0;n<i;n++)e=(e<<5)-e+t.charCodeAt(n),e&=e;return e}function pingSunlight(){_sping.unshift({visit:{protocol:window.location.protocol,domain:window.location.host,page:window.location.pathname+window.location.search,title:document.title,load_time:window.performance.timing.domComplete-window.performance.timing.navigationStart,checksum:sunlight_checksum(document.body.innerText)}});var t=new XMLHttpRequest;return t.open("POST","https://sunlightmetrics.com/api/v1/visits?capi="+sunlightCapi,!0),t.setRequestHeader("Content-Type","application/json"),t.send(JSON.stringify(_sping)),!1}window.addEventListener("load",function(){(/googlebot/.test(useragent)||/bingbot/.test(useragent)||/msnbot/.test(useragent))&&pingSunlight()},!1);
```
