### ISSUE TITLE
https://rokmangear.com

### ISSUE THREAD

**Issue by sww1235** [easylist/easylist#9068]
### List the website(s) you're having issues:

`https://rokmangear.com`

### What happens?

Site loads but just to a spinner. When looking at the logs, I see 2 domains blocked, ` googletagmanager.com` and `https://d1zgderxoe1a.cloudfront.net/`. I believe the cloudfront url is the one that is causing the issues. 

### List Subscriptions you're using:

default uBlock Origin settings.

### Your settings

Default uBlock Origin settings

Checked with HTTPS Everywhere and Privacy Badger disabled.

- OS/version: `Linux 5.11.22_1 #1 SMP 1621481187 x86_64 GNU/Linux`
- Browser/version: `Firefox 91.0.1 (64-bit)`
- Adblock Extension/version: `uBlock Origin 1.37.2`

### Other details:

Suspect the easylist-3rdparty blocklist with the above cloudfront URL. It appears to redirect to a surveymonkey link, but something in the page is blocking all content from loading until that url is accessed.

I couldn't figure out the filter syntax in order to temporarily allow just that one domain, but it is only 1 of 2 being blocked on the site.

Thank you

**Comment by sww1235** [comment]
I also had the same issue on firefox for Android with uBlock Origin and same settings.

**Comment by ryanbr** [comment]
Works for me.
