### ISSUE TITLE
[NFSW] tangomature.com [empty ad placeholders] 

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#9081]
### List the website(s) you're having issues:

`http://www.tangomature.com/pl/`

### What happens?

multiple big empty ads placholders, 
example solution: `tangomature.com##.bottom-bn, .gallery-bn`

### List Subscriptions you're using:

EasyList
AdGuard Base Filter

### Your settings

- OS/version: W7SP164
- Browser/version: FF 92 / O 78
- Adblock Extension/version: uBO 1.37.3rc1

### Other details:

![capture_029_12-09-2021_14-23-46](https://user-images.githubusercontent.com/75935068/132987476-85318e69-494c-49b0-a8c3-9ec9907b649e.png)

**Comment by ryanbr** [comment]
Seems to a dummy site, "Image not found". Not worth.
