### ISSUE TITLE
[NSFW] nushemale.com [ADS & big multple empty ad placeholders]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#9084]
### List the website(s) you're having issues:

`http://nushemale.com/`

### What happens?

ADS & big multple empty ad placeholders, 
example solution: 
`||nushemale.com/newpaper.html$subdocument,~third-party`
`||nushemale.com/tc-rotation-banners/tc-rotation-banners/tcrb.php$subdocument,~third-party`

### List Subscriptions you're using:

EasyList
AdGuard Base Filter

### Your settings

- OS/version: W7SP164
- Browser/version: FF 92 / O 78
- Adblock Extension/version: uBO 1.37.3rc1

### Other details:

![capture_037_12-09-2021_14-54-29](https://user-images.githubusercontent.com/75935068/132988510-a636ba3c-93b0-4e4d-bcda-66d71538d74e.png)
![capture_038_12-09-2021_14-54-43](https://user-images.githubusercontent.com/75935068/132988515-9db21f39-4399-46b8-8ce9-a8296985873a.png)
![capture_039_12-09-2021_14-54-46](https://user-images.githubusercontent.com/75935068/132988517-2023e6e9-10b2-45b6-8518-92d52500ca85.png)

**Comment by ryanbr** [comment]
Not really a major porn site.
