### ISSUE TITLE
afreesms.com

### ISSUE THREAD

**Issue by ExtremelyCool** [easylist/easylist#9088]
### List the website(s) you're having issues:
`https://www.afreesms.com/`

### What happens?
Ad

### List Subscriptions you're using:
uBlock Origin's ebd (version 1.37.2, on PC).

### Your settings

- OS/version: Windows 10
- Browser/version: Tor
- Adblock Extension/version: uBlock Origin 1.37.2

**Comment by ryanbr** [comment]
No ads seen

**Comment by ExtremelyCool** [comment]
@Khrin @ryanbr 
![image](https://user-images.githubusercontent.com/90566652/133326140-ad9ce7ec-dc4c-42df-bf04-f823be54f26b.png)

**Comment by ryanbr** [comment]
`afreesms.com/images/tbg.png`   its use a small white line. seems safe.
