### ISSUE TITLE
https://adpage.io is blocked

### ISSUE THREAD

**Issue by jeroenfrenken** [easylist/easylist#909]
I've got this domain that I bought: https://adpage.io/ to create a software tool for building campaign landing pages. Adblock blocks all the assets directly It's a new domain

There is already a commit made for adpage but I think it is not right because it is on the same line as adrobot which is a different service and not owned or connected with adpage

link to the commit
https://github.com/easylist/easylist/commit/ed25a48a288171aad05e146e8834684aa8559b98

Thanks for your time.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/67d38658ca37d43db7fdf1f9ff5bc1c8ffd29a34
