### ISSUE TITLE
topminecraftservers.org

### ISSUE THREAD

**Issue by ExtremelyCool** [easylist/easylist#9091]
### List the website(s) you're having issues:
`https://topminecraftservers.org/`

### What happens?
Space

### List Subscriptions you're using:
uBlock Origin's ebd (PC, version 1.37.2)

### Your settings

- OS/version: 
- Browser/version: Tor
- Adblock Extension/version:

**Comment by spirillen** [comment]
This is the only empty spaces I see and thoses are youtube vido ads (first line)

```css
!topminecraftservers.org###video-sponsored

! 2021-09-12 https://topminecraftservers.org
topminecraftservers.org##.embed-responsive
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/b4f2e05d6f8fcea388af26415e13de11e2509c48
