### ISSUE TITLE
www.tumblr.com

### ISSUE THREAD

**Issue by AprilSylph** [easylist/easylist#9095]
### List the website(s) you're having issues:

`https://www.tumblr.com/dashboard`

### What happens?

No meaningful cosmetic filtering; basically a repeat of #7700

### List Subscriptions you're using:

- EasyList 202109130439

### Your settings

- OS/version: macOS 11.5.2 (20G95)
- Browser/version: Firefox 93.0b4 (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

Classnames need to be updated to target the elements; previous cosmetic filters can be assumed to be entirely broken unless they avoid targeting via classnames entirely. I've written a script [here](https://gist.github.com/AprilSylph/275bf9ba829fd5f3bdfb632f549b81da) for producing up-to-date rules. Current output:

```
www.tumblr.com##.j3_kY
www.tumblr.com##.JD7Cz
www.tumblr.com##.VdRef
www.tumblr.com##.WFhoV
```

I'm not completely sure if there's any performance improvement for any blocker to use `www.tumblr.com` rather than `tumblr.com` but I would imagine so. (Any cosmetic filtering targeting `www.tumblr.com` can be assumed to be useless for all other subdomains, since they are exclusively either internal domains which serve only raw files or individual Tumblr blogs which do not use the same web app as the main site.)

**Comment by ryanbr** [comment]
Should we just remove the elements then? @AprilSylph

**Comment by AprilSylph** [comment]
Yeah, sorry for not opening a PR but the issue I referenced and the linked PR was closed via commit, so I figured it was easier to just report what needed to be added.
