### ISSUE TITLE
MakeWarNotLove.com - Page won't load (Fanboy's Annoyance List)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#910]
Problem rule (found in '**Fanboy's Annoyance List**'):
`/downloads.mailchimp.com/*`

Affected URL (SEGA giveaway site):
http://www.makewarnotlove.com/

Issue:
The page won't load.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/0100f75b56e84d702be22ee94e8e8d109f131e0c
