### ISSUE TITLE
coursesbyvivekbindra.com

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#9105]
**Issue URL (Annoyance)**:
https://coursesbyvivekbindra.com/

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132102095-61c097b1-3bd9-4c9c-80a8-953f1bc277b1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by ryanbr** [comment]
Its fine, we don't target these. would really bloat the list if we did. @chirag127

**Comment by chirag127** [comment]
> Its fine, we don't target these. would really bloat the list if we did. 

@ryanbr it's okay that you are not targeting these but what do you mean by these? Atleast tell me what is different in this pop-up than others so that I will not report these popup in future.
