### ISSUE TITLE
AdBlock detected on https://tf2-servers.com

### ISSUE THREAD

**Issue by SonicPlushBros** [easylist/easylist#9108]
### What happens?
AdBlock warning at the top of the page when using EasyList Cookie.

### List Subscriptions you're using:

EasyList Cookie
EasyList
EasyPrivacy

### Your settings

- OS/version: Linux Mint 20.2 Cinnamon
![Screenshot from 2021-09-14 12-56-38](https://user-images.githubusercontent.com/89158249/133301184-05ff0e5b-cc69-40b8-b30c-664a1fa9dd25.png)

- Browser/version: Ungoogled Chromium 87.0.4280.141
- Adblock Extension/version: uBlock Origin 1.33.3rc1

### Other details:
The filter **@@||cookie-script.com^$script,domain=tf2-servers.com** got rid of the warning for me, but not sure if It's better to use any other filter.

**Comment by ryanbr** [comment]
Not seeing this

**Comment by SonicPlushBros** [comment]
What about just EasyList Cookie?

**Comment by Khrin** [comment]
Impossible to verify also for me.

**Comment by SonicPlushBros** [comment]
Even with just EasyList Cookie?
