### ISSUE TITLE
NSFW: movieclassic.net

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#9113]
### List the website(s) you're having issues:
```
movieclassic.net
```

## External relations?
  - https://github.com/easylist/easylist/commit/9efef25582cd1d00584fa9a63e8e8d81e2162404
  - https://mypdns.org/my-privacy-dns/porn-records/-/issues/746
  - https://github.com/easylist/easylist/pull/8663

### What happens?

 - [ ] Exit popup -under
 - [ ] Exit script redirecting to other porno sites
 - [x] AdWare 
 - [ ] Tracking

## Screenshot
<details><summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/44526987/133443203-66575346-dac7-4e80-adc6-38c013658fae.png)

</details>

### List Subscriptions you're using:

- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist
- Peter Lowe’s Ad and tracking server list
- Spirillen's – Adblock Rules (https://mypdns.org/my-external-stuff/ublockorigin-rules/)

### Your settings

- OS/version: Ubuntu 20.04.2
- Browser/version: Tor-Browser & FF latest stable from Ubuntu repo
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:
First line handles the overlay
Second line need a review from one whom speaks the language, My guess is banner ads.... @Yuki2718, @c2xusnpq6
Third line is a asocial overlay, sharing thing.
Fourth line = Some popup, didn't understand the text, so assume ads

```
movieclassic.net###billboard-modal
movieclassic.net##.partialViewSlider-outerwrapper
movieclassic.net##.float-right-image
movieclassic.net###shunt-modal
```

**Comment by Yuki2718** [comment]
This was almost declined: https://github.com/easylist/easylist/pull/8663

**Comment by spirillen** [comment]
yeah, can see that, but nicely spotting of the .js scrips :+1:
