### ISSUE TITLE
https://ptable.com/

### ISSUE THREAD

**Issue by nathanielcwm** [easylist/easylist#9121]
### List the website(s) you're having issues:

`https://ptable.com/`

### What happens?

Anti adblock banner at the top of the page.

### List Subscriptions you're using:

All Ublock & ublock annoyances, Easylist, Easyprivacy, Spam404, Adguard annoyances, easycookie, fanboy's annoyances, peter lowes.

### Your settings

- OS/version: Win 10
- Browser/version: FF 92
- Adblock Extension/version: Ublock 1.37.2

### Other details:

`##.Notice` using ublock picker tool removes the notice.

**Comment by ryanbr** [comment]
Pretty minor, at least it's not taking over the page.  Free to submit to the uBO guys.
