### ISSUE TITLE
Filters blocking bet365 and 1Xbet popups

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#9133]
### List the website(s) you're having issues:

https://www.onlinebettingacademy.com/
https://www.bettingacademy.co.uk/
https://www.bettingacademyus.com/

### What happens?

EL filters: `||bet365.com^*affiliate=$popup` and `||refpa.top^$popup` prevent bet365 and 1Xbet popups links from opening on: below websites, including subpages and they seem to be part of the content.

Possible solution: 
`||bet365.com^*affiliate=$popup,domain=~onlinebettingacademy.com|~bettingacademy.co.uk|~bettingacademyus.com`

### List Subscriptions you're using:

EL and ABP

### Your settings

- OS/version: IOS
- Browser/version: Chrome and Firefox
- Adblock Extension/version: 3.11.2

### Other details:
<img width="1116" alt="betting" src="https://user-images.githubusercontent.com/65717387/133621207-2429fa64-c6e8-4ee4-84c4-086bbfe9d140.png">
<img width="1091" alt="bt2" src="https://user-images.githubusercontent.com/65717387/133621401-5fb6fff3-9ec7-44c4-a79f-0ac4d1f8589d.png">

**Comment by ryanbr** [comment]
Its unfortunate. but `bet365.com` and others heavily use adservers to promote their gambling platforms.   Not making exceptions for every gambling site here.
