### ISSUE TITLE
Multi Domain Removal Request 

### ISSUE THREAD

**Issue by mattyEyes** [easylist/easylist#9135]
I am reaching out in order to get our company domains removed from EasyList and any associated lists. I have provided reasons and a list of the domains to remove. Please let me know if there is anything else I can provide to get this completed as soon as possible. 

CJ is a participant in the Coalition for Better Ads. We do not track and store user specific data. 

Coalition for Better Ads
•	About: Leading international trade associations and companies involved in online media formed the Coalition for Better Ads to improve consumers’ experience with online advertising. The Coalition for Better Ads has leveraged consumer insights and cross-industry expertise to develop and implement new global standards, the Better Ad Standards, for online advertising that address consumer expectations.

List of domains to be removed (please reach out for list of domains to be removed).

**Comment by ryanbr** [comment]
We've already commented on this.

`Thanks for the request, I'd recommend submitting the request to https://acceptableads.com/
`
