### ISSUE TITLE
Fanatical.com - Game giveaways won't load (Fanboy's Enhanced Tracking List)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#914]
Problem rule (found in '**Fanboy's Enhanced Tracking List**'):
`||gleam.io^$third-party`

Example:
https://www.fanatical.com/en/blog/lethal-league-10000-steam-key-giveaway/

Issue:
gleam.io's game giveway widget is blocked.

**Comment by ryanbr** [comment]
Best to submit to my issue report if related to non-Easylist stuff.

https://github.com/ryanbr/fanboy-adblock/commit/4a698cf6204c504abe3001ec2be1e872edea0067
