### ISSUE TITLE
easeus.com self-promos

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#9142]
### List the website(s) you're having issues: 

`https://www.easeus.com/ios-tips/mac-keeps-restarting.html`

### What happens? 
- Self promos

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/52135169/133662357-42d67ef5-93a1-4772-87aa-82de06b34aa6.png)

</details><br/>

### List Subscriptions you're using:

EasyList

### Your settings
![image](https://user-images.githubusercontent.com/52135169/131621897-bba5da86-2408-43be-a2cf-ebd01f8e2343.png)

- OS/version: Windows 10
- Browser/version: Firefox 92.0
- Adblock Extension/version: uBlock Origin 1.37.2

### Other details:

The wonderful people at uAssets [provided filters](https://github.com/uBlockOrigin/uAssets/issues/10019#issuecomment-921166890) for this!

**Comment by ryanbr** [comment]
Fine leaving this to be honest.
