### ISSUE TITLE
highstream.tv [EasyList] [can't play video]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#9151]
### List the website(s) you're having issues:

Example video: `https://highstream.tv/9fp6q77anu81`

### What happens?

Can't play video, error.
Using these filters can play video, but with Ads:
`@@||fiorenetwork.com/aparatvast/anavast.php$xmlhttprequest,domain=highstream.tv`
`@@||fiorenetwork.com/aparatvast/*$script,domain=highstream.tv`

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Win7SP164
- Browser/version: FF 92 / O 78
- Adblock Extension/version: uBO 1.37.3rc3

### Other details:

Broken:
![capture_006_17-09-2021_20-06-01](https://user-images.githubusercontent.com/75935068/133834703-e03c4f8e-9c05-44ad-b180-b28d7e4a794b.png)

With ads:
![capture_005_17-09-2021_20-04-55](https://user-images.githubusercontent.com/75935068/133834949-e69e85af-db1b-4f49-8725-4cf8d5b35749.png)

**Comment by felix-22** [comment]
I see: https://github.com/easylist/easylist/commit/296dbcf1e9382595ef41b8e58382202c642df4c7 - I'm not sure if this is supposed to be fixed, there is some improvement, because youtube video plays now, but after pressing Skip Ad the same error reappears.

**Comment by Yuki2718** [comment]
> * after pressing `Skip Ad` the same error reappears (in frame)

That's irrelevant to `fiorenetwork.com`. Not playing the video is a site issue and has nothing to do with contents blocking. The commit is simply wrong, @uBlock-user spotted it and already told to @ryanbr

**Comment by uBlock-user** [comment]
> but when click Watch in YouTube - the ads dissappear and video plays fine (in YouTube)

That's Youtube video you're watching on youtube(irelevant to the issue at hand, the video from highstream.tv is still broken due to error 232011 caused in the JW player. Anyway this case is site-issue and should be closed.

**Comment by felix-22** [comment]
Ok.
