### ISSUE TITLE
www.bloomberg.com

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#9153]
**Issue URL (Ads/Annoyance)**:https://www.bloomberg.com/news/features/2021-09-16/india-taps-amazon-microsoft-for-farm-tech-as-modi-eyes-reforms

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/133883390-c81fe797-f0a4-4167-aed5-55cad16d9b41.png)
![image](https://user-images.githubusercontent.com/76880977/133883391-54a7126c-fce2-4b87-82f4-f59ba24e03b8.png)
![image](https://user-images.githubusercontent.com/76880977/133883392-9952b02b-27d9-40d9-8f73-9de3ecf36b0a.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>

**Comment by Nojuuu** [comment]
I'm unable to reproduce this.
