### ISSUE TITLE
www.rockpapershotgun.com cookie banner

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#9156]
### List the website(s) you're having issues:
`https://www.rockpapershotgun.com/`

### What happens?
There is a cookie consent banner.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by peace2000** [comment]
It seems this site has whitelisting that had been added in the past. I don't now at least now see any issues with this site. Videos work: https://www.rockpapershotgun.com/videos (they are embedded Youtube videos). Accepting cookies seems to be only necessary if an article has a quiz: https://www.rockpapershotgun.com/mystery-steam-reviews-spiritual-successors but even in that case, it says that cookies must be accepted and gives a button to open Cookie settings:

![kuva](https://user-images.githubusercontent.com/17256841/133911228-8e182679-9d3b-4694-8756-0533b289bf10.png)

**Comment by spirillen** [comment]
Just to add a little to the pot.

This how the site looks like when all tracking is disabled (DNS firewall) (`https://www.rockpapershotgun.com/mystery-steam-reviews-spiritual-successors`)

That makes me believe that people who are feeling compelled to be spied on should leave this rule

```css
:@@||cdn.cookielaw.org^$script,stylesheet,xmlhttprequest,domain=cnn.com|comicbook.com|crfashionbook.com|crunchyroll.com|doctoroz.com|eurogamer.net|gamespot.com|gmx.com|gq-magazine.co.uk|mail.com|popculture.com|reuters.com|rockpapershotgun.com|rp-online.de|rte.ie|trustpilot.com|tvn24.pl|uefa.com|vimeo.com|wargaming.net|worldsurfleague.com
```

![image](https://user-images.githubusercontent.com/44526987/133930405-923315f4-68c8-4056-9aca-e766cc9d7e35.png)

```shell
drill cookielaw.org.tracking.mypdns.cloud @188.176.49.219 -p 53
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 20817
;; flags: qr aa rd ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; cookielaw.org.tracking.mypdns.cloud. IN      A

;; ANSWER SECTION:
cookielaw.org.tracking.mypdns.cloud.    86400   IN      CNAME   .
```

**Comment by krystian3w** [comment]
Looks like eurogamer.

@THEtomaso are you have here bugged player from `Blue Billywig`?

**Comment by THEtomaso** [comment]
Yeah, same thing.
The cookie banner is whitelisted, in order to avoid breakage.

**Comment by krystian3w** [comment]
@spirillen you put `:` into code block.

**Comment by spirillen** [comment]
> @spirillen you put `:` into code block.

Hmm it was a copy/paste from where ever it was I found it... so it could be a divider from `git grep`

**Comment by krystian3w** [comment]
Nope - fix this glitch:

`:@@||`

**Comment by spirillen** [comment]
Whatever you say @krystian3w but I do not understand you here, it's a comment not a PR and it came from this shell command

```shell
easylist$ git grep 'cdn.cookielaw.org'
easylist_cookie/easylist_cookie_allowlist.txt:@@||cdn.cookielaw.org^$script,stylesheet,xmlhttprequest,domain=cnn.com|comicbook.com|crfashionbook.com|crunchyroll.com|doctoroz.com|eurogamer.net|gamespot.com|gmx.com|gq-magazine.co.uk|mail.com|popculture.com|reuters.com|rockpapershotgun.com|rp-online.de|rte.ie|trustpilot.com|tvn24.pl|uefa.com|vimeo.com|wargaming.net|worldsurfleague.com
```

So I don't follow your comment here :confused:

**Comment by krystian3w** [comment]
I mean why you put `:` in block code with allow network filter:

**Comment by spirillen** [comment]
I don't add `:` to any code, as I tried to tell you, it was a simple copy paste mistake... I really doesn't follow your reactions with thumb_down and all; for a simple copy paste mistake. I'm really lost here... :confused: :question:

**Comment by felix-22** [comment]
> spirillen : I really doesn't follow your reactions with thumb_down and all; for a simple copy paste mistake.

He is known for his thumb down emojis: https://github.com/uBlockOrigin/uAssets/issues/7332#issuecomment-626233811

**Comment by felix-22** [comment]
Up.

**Comment by ryanbr** [comment]
Should be resolved now, unfortantly.
