### ISSUE TITLE
WebTorrent peer introduction servers blocked

### ISSUE THREAD

**Issue by feross** [easylist/easylist#916]
### URL(s) where the issue occurs

`https://instant.io/#https://webtorrent.io/torrents/sintel.torrent`
`https://webtorrent.io`

### Description of the issue

WebTorrent is a library that allows a user to use BitTorrent in the web browser. It uses WebRTC to help peers connect to each other. There are a few WebSocket servers that users connect to in order to find peers to download files from. In BitTorrent parlance, these introduction servers are known as "trackers", but they have nothing to do with ad trackers.

It seems that a few rules from the EasyPrivacy list are blocking WebTorrent tracker servers, preventing WebTorrent from working. Specifically, these rules:

```
.xyz^$third-party,websocket
||fastcast.nz^$third-party
||tracker.openwebtorrent.com^$third-party
```

These servers are "BitTorrent trackers" (i.e. peer introduction servers) that help users register their interest in particular torrents and connect to other peers who have the files they are looking for. Blocking them totally breaks WebTorrent.

**Can we remove these rules?**

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6cabf987a9e84d583c44fdc934b55f98e1448b7f
