### ISSUE TITLE
www.conso.ro

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#9168]
### List the website(s) you're having issues:
`https://www.conso.ro/`

### What happens?
With cosmetic filtering enabled, I see a grey wall and can't acces the page.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by DandelionSprout** [comment]
There's a general lack of information in the OP about which lists and adblockers that were being used at the time the issue report was written.

**Comment by ryanbr** [comment]
@andreewmat  what issue, is it still happening? Seems fine so far.
