### ISSUE TITLE
lacerta . space Why are you blocking my site?

### ISSUE THREAD

**Issue by Aleksandr-om** [easylist/easylist#9171]
### List the website(s) you're having issues:

lacerta . space (remove spaces)

### What happens?

My site stopped opening today. As it turns out, you've added it to your filters. This is a private site with no ads.

Today you added my site to filters in this commit
https://github.com/easylist/easylist/commit/9c1686082583caaa22641b0f2579c1aad6e0e8c7#diff-1298f15fc987f32c8ee53ef08b4582d0861e6fecced9888537d7929b781c9ed2

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by krystian3w** [comment]
Maybe you have outdated WordPress so your hosting was infected and now use to serve zombie ads.

Check all files on SSH/FTPs to exclude infection.

**Comment by Aleksandr-om** [comment]
It’s not Wordpress. I checked the files right away, no problem.

**Comment by krystian3w** [comment]
Maybe you lost history in whois and EasyList honeypot marked your domain as new and empty homepage marked as suspicious.

**Comment by Aleksandr-om** [comment]
@krystian3w Do you mean that this domain was once used and that had a lot of advertising on it? When we bought the domain two years ago, did we automatically become suspicious?

**Comment by ryanbr** [comment]
Filter was added here: https://github.com/easylist/easylist/commit/d8ca1687b717a6b180e75a96dd1dcf4f135ade96

Though if it's used for Ads and/or Tracking, it'll be reblocked.

**Comment by Aleksandr-om** [comment]
I.e. before buying a domain you should always first check if the domain is in your filters? Especially in the history of filters, because for two years the site was not blocked.
