### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by prodan1234** [easylist/easylist#9172]
### List the website(s) you're having issues:

`twitter.com`
### What happens?

Promoted tweets appear in the timeline. 

### List Subscriptions you're using:

uBlock defaults, Adguard Base, Annoyances filters,  

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by krystian3w** [comment]
In what languages?

**Comment by krystian3w** [comment]
fyi @peace2000 / @Yuki2718

**Comment by prodan1234** [comment]
English.

**Comment by peace2000** [comment]
Easylist handles them at least for me. These two rules include English:

`twitter.com##div[data-testid="placementTracking"]:has(svg + div[dir="auto"] > span:has-text(/Promoted|Gesponsert|Promocionado|Sponsorisé|Sponsorizzato|Promowane|Promovido|Реклама|Uitgelicht|Sponsorlu|Promotert|Promoveret|Sponsrad|Mainostettu|Sponzorováno|Promovat|Ajánlott|Προωθημένο|Dipromosikan|Được quảng bá|推廣|推广|推薦|推荐|プロモーション|프로모션|ประชาสัมพันธ์|प्रचारित|বিজ্ঞাপিত|تشہیر شدہ|مُروَّج|تبلیغی|מקודם/))`

`twitter.com##div[data-testid="UserCell"]:has(svg + div[dir="auto"] > span:has-text(/Promoted|Gesponsert|Promocionado|Sponsorisé|Sponsorizzato|Promowane|Promovido|Реклама|Uitgelicht|Sponsorlu|Promotert|Promoveret|Sponsrad|Mainostettu|Sponzorováno|Promovat|Ajánlott|Προωθημένο|Dipromosikan|Được quảng bá|推廣|推广|推薦|推荐|プロモーション|프로모션|ประชาสัมพันธ์|प्रचारित|বিজ্ঞাপিত|تشہیر شدہ|مُروَّج|تبلیغی|מקודם/))`

**Comment by krystian3w** [comment]
try found FP if use `i` for attribs:

https://css4-selectors.com/selector/css4/attribute-case-sensitivity/
https://caniuse.com/css-case-insensitive

**Comment by ryanbr** [comment]
Closing, no issues seen
