### ISSUE TITLE
Videos on `zdnet.com` won't play

### ISSUE THREAD

**Issue by stm-x** [easylist/easylist#9177]
### List the website(s) you're having issues:

`https://www.zdnet.com/video/no-ads-no-trackers-former-google-executives-launch-alternative-search-engine/`
### What happens?
When Fanboy Annoyance is enabled, the video will not play.

### List Subscriptions you're using:
uBO Default + AdGuard Japanese + Fanboy's Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: MS Edge 93
- Adblock Extension/version: uBlock origin 1.37.2

### Other details:
Rules that may be the cause
`/privacy/optanon/*`

**Comment by THEtomaso** [comment]
I reported it 15 months ago, here:
https://github.com/ryanbr/fanboy-adblock/issues/1375/
_*post updated with yet another problem rule*_

**Comment by ryanbr** [comment]
Okay, removed

**Comment by THEtomaso** [comment]
Not fixed.
The two problem rules, which I originally posted 15 months ago here, still prevents some videos fom being played:
https://github.com/ryanbr/fanboy-adblock/issues/1375/
