### ISSUE TITLE
[NSFW] [AD] hairy-ocean.com

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#9193]
### List the website(s) you're having issues:

`http://hairy-ocean.com/`

### What happens?

ADS

### List Subscriptions you're using:

EasyList filters
uBlock filters
AdGuard filters

### Your settings

- OS/version: W7SP164
- Browser/version: FF 92 / O 78
- Adblock Extension/version: uBO 1.37.3rc3

### Other details:

![2222](https://user-images.githubusercontent.com/75935068/134322732-9c4c8241-a4b8-4e8f-b0b7-abf89db7abe7.png)

![capture_015_22-09-2021_11-49-24](https://user-images.githubusercontent.com/75935068/134322780-285de24e-d454-40f2-8f1a-68718e480b11.png)

**Comment by felix-22** [comment]
@ryanbr , still nasty AD placeholder: `hairy-ocean.com##.bannerlisst`

![t](https://user-images.githubusercontent.com/75935068/134473010-2037ab62-5f91-4e19-b47f-7218f43a2e16.png)

**Comment by ryanbr** [comment]
fine with it

**Comment by felix-22** [comment]
@ryanbr What do you mean? Why not to remove this nasty annoying AD placeholder?
