### ISSUE TITLE
||spanglefish.com^$third-party

### ISSUE THREAD

**Issue by GarveScott-Lodge** [easylist/easylist#920]
I run a server which has thousands of small websites all using CSS stored externally in an Amazon S3 bucket.

Many of the static images on these sites are also stored on S3.

When 'Block additional tracking' is ticked in Adblock these stylesheets and images are not loading.

For example on the site

    http://www.skyecottageglendale.co.uk/

this stylesheet is being blocked from loading

    http://s3.spanglefish.com/2/css/sp2.css?rev=8

as is this image

    http://s3.spanglefish.com/s/33586/pictures/outside-for-web-2.jpg

I'm informed this is due to this filter

||spanglefish.com^$third-party

Can this behaviour be stopped please?

cheers

Garve

**Comment by ryanbr** [comment]
Okay, looked at the original commit, it'll be removed.

https://github.com/easylist/easylist/commit/d105e933e85491bdc0610fddfe9c24d5bb7a1256
