### ISSUE TITLE
remove promo.stormgain.com

### ISSUE THREAD

**Issue by want2stayhere** [easylist/easylist#9202]
### List the website(s) you're having issues:

https://promo.stormgain.com/lp/en-en/bonus25
https://promo.stormgain.com/lp/en-en/bonus50/
https://promo.stormgain.com/lp/en-en/bonus100/
https://promo.stormgain.com/lp/en-en/bonus300/
https://promo.stormgain.com/lp/en-en/bonus500/
etc.

### What happens?

Added to easylist.

this rule blocks opening any landing page on the domain promo.stormgain.com
promo.stormgain.com^$popup

### List Subscriptions you're using:

AdGuard

### Your settings

- OS/version: Any
- Browser/version: Any
- Adblock Extension/version: Any

### Other details:

This host is used by many landing pages and no one is opening due to this filter. While there is no unwanted popup

**Comment by Khrin** [comment]
Unsure why you thought that opening a second request and ignoring the reply you've got via email would had help you more.
