### ISSUE TITLE
ebay.com

### ISSUE THREAD

**Issue by ExtremelyCool** [easylist/easylist#9211]
### List the website(s) you're having issues:
`https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2047675.m570.l1313&_nkw=xbox&_sacat=0`

### What happens?
ad

### List Subscriptions you're using:
uBO's ebd on PC

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBO 1.38.0

**Comment by ryanbr** [comment]
It's fine, selfpromos.

**Comment by ExtremelyCool** [comment]
> It's fine, selfpromos.

Does Microsoft own Ebay?
