### ISSUE TITLE
subhd.tv ads

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#9214]
```
subhd.tv##div.bg-dark:first-child
or
subhd.tv##.bg-dark
```
https://subhd.tv/

**Comment by c2xusnpq6** [comment]
before:
![image](https://user-images.githubusercontent.com/75058881/134777899-e0f0c1d6-e720-49ae-aac5-ef46028f692a.png)

after:
![image](https://user-images.githubusercontent.com/75058881/134777908-f1296553-1c12-4fb1-95ab-8dd4c611e6ae.png)

**Comment by ryanbr** [comment]
Should contribute to the Easylist China list.
