### ISSUE TITLE
sbb.ch

### ISSUE THREAD

**Issue by GuyXY** [easylist/easylist#922]
Whenever I set a route and want to take a look at it on the map, it looks like this: 
![image](https://user-images.githubusercontent.com/5495060/36481193-5ed1678a-170f-11e8-8ce1-401b60876ae9.png)
After I've taken a look at uBlock Origins Logger I've found out that it's because of the `||adobedtm.com^$third-party` filter from the EasyPrivacy list. sbb.ch tried to access `https://assets.adobedtm.com/ab1bdbe8e40fa1ba96e6071c7822b344297c9ed2/satelliteLib-924b92fd9b5b13eb48c703dc13f8c4e6d58d62cd.js` in case that helps.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3c48b148daf110a254b1259c672b48e67f01ce41
