### ISSUE TITLE
mic.com

### ISSUE THREAD

**Issue by ExtremelyCool** [easylist/easylist#9227]
### List the website(s) you're having issues:
`https://www.mic.com/p/is-recycling-worth-it-67097705`

### What happens?
Annoyance / leftover

### List Subscriptions you're using:
uBO ebd (PC) + Fanboy's Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin 1.38.0

### Other details:
![image](https://user-images.githubusercontent.com/90566652/134827132-689aa3da-3e29-4600-952b-5a006b6d165c.png)

**Comment by ExtremelyCool** [comment]
Also,
![image](https://user-images.githubusercontent.com/90566652/134828632-60bcd667-e064-45f5-9c9f-290cb43f8c22.png)

@ryanbr could you take a look?

**Comment by ryanbr** [comment]
What am I looking at or for, the site looks fine.

**Comment by ExtremelyCool** [comment]
@ryanbr 
![image](https://user-images.githubusercontent.com/90566652/134831350-894836aa-1556-4ae5-8bda-81149d38e4e3.png)

**Comment by ryanbr** [comment]
Its fine, too minor.
