### ISSUE TITLE
New tracker: quickanalytics.ca

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#9232]
### List the website(s) you're having issues:

`https://www.freetoattach.com/`

### What happens?

unblocked tracker: `quickanalytics.ca`

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

add `||quickanalytics.ca^$3p` to EasyPrivacy

**Comment by spirillen** [comment]
Where did you find this one?

**Comment by yokoffing** [comment]
> Where did you find this one?

I listed the website above: `https://www.freetoattach.com/`

It's a resource we use in counseling for people with avoidant attachment styles.
