### ISSUE TITLE
nymag.com

### ISSUE THREAD

**Issue by ExtremelyCool** [easylist/easylist#9237]
### List the website(s) you're having issues:
`https://nymag.com/strategist/article/curtains-for-windows.html`

### What happens?
ads

### List Subscriptions you're using:
uBO's ebd on PC + Fanboy's Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin 1.38.0

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/971ba8f09c6e6ae4c8e244293618feea6b66fb9d
