### ISSUE TITLE
10minutemail.net

### ISSUE THREAD

**Issue by hawkeye116477** [easylist/easylist#924]
Leftover after ad.
Browser: Vivaldi 1.14.1077.45 (based on Chromium 64.0.3282.143)
Solution -> `10minutemail.net###leftover`

![screenshot_20180222_171759](https://user-images.githubusercontent.com/19818572/36550028-83d09f98-17f4-11e8-96e8-dcc72bbf5baf.png)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8ec1bc891b52186a8f1e6593edccf6d4a9872cff
