### ISSUE TITLE
Google's Ad Manager API Documentation page is getting blocked.

### ISSUE THREAD

**Issue by mundo03** [easylist/easylist#9259]
### List the website(s) you're having issues:
https://developers.google.com/ad-manager/api/intro

### What happens?

Web site blocked by rule `/ad-manager/*`

### List Subscriptions you're using:

ABP filters, Easylist,  Easy Privacy, Fanboy's Social Blocking List, 
### Your settings

- OS/version:  Manjaro 21.1.4
- Browser/version: Edge 95.0.1020.5 (Official build) dev (64-bit)
- Adblock Extension/version:  ABP  3.11.2

### Other details:
The website describes Google's Ad Manager API, It should not be blocked
Maybe a filter like `/ad-manager/*$~document` or `/ad-manager/*$script` would be better, not sure if any ad tech is actually served from an URL containing `ad-manager` since most google ads come from other sub domains, which are already blocked anyway.
Or maybe allow developers.google.com? 
Let me know what you think.

**Comment by spirillen** [comment]
Cool, I love it :heart:
