### ISSUE TITLE
/reporting/metrics blocked - too generic

### ISSUE THREAD

**Issue by samfitz66** [easylist/easylist#9274]
A core part of my teams SAAS product (not available to the public as it's a B2B product) is broken for any users with ublock origin enabled due to the blocking of the /reporting/metrics path (https://github.com/easylist/easylist/blame/642655f94666745692f6ecc693b0391e66cb3677/easyprivacy/easyprivacy_general.txt#L3540) as part of this recent change - https://github.com/easylist/easylist/issues/9233.

Please consider a more specific URL path to block for the citi.com issue, as /reporting/metrics is too generic and is likely going to block other key functionality of other sites in addition to our own.

**Comment by lcaille** [comment]
Hi,

We also got this issue in one of our B2B products as well.

**Comment by ryanbr** [comment]
Closing, filter is still good. Nothing has broken. If we had any replicated issues maybe would be reviewed.

**Comment by samfitz66** [comment]
> ng has broken. If we had any replicated issues maybe would be reviewed.

@ryanbr We have issues in our B2B app as a result of this, it's not in the open web as its a SaaS product, how do you suggested we fix it? I've tried to help fix it by raising https://github.com/easylist/easylist/pull/9333. Happy to do a call and screenshare to show you the issue if you would like evidence.

**Comment by Khrin** [comment]
If it's really an issue, I believe you can whitelist yourself your domain.
