### ISSUE TITLE
kit.co - Easylist Cookie hides everything except the navbar

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#9280]
### List the website(s) you're having issues:

`https://kit.co/`

### What happens?

Just a white page with Easylist Cookie enabled.

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/84513173/134036803-06d9d94f-7f3f-47d8-b6e1-413f8feaee3a.png)

</details>

### Your settings

<details>

- OS/version: Windows 10 21H1
- Browser/version: Firefox 92.0  (64-bit)
- Adblock Extension/version: uBlock Origin 1.37.2

</details>

### Other details:

Problematic filter `/cookiecontrol-`

"I don't care about cookies" filter list uses these filters on this site without issues:
```
###ccc > #ccc-overlay ~ div[id^="ccc"]
###ccc > #ccc-overlay
```

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/bc865f65a9e777b603311e24492e3ad2c3582c56
