### ISSUE TITLE
yahoo.com cookie consent

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#9281]
### List the website(s) you're having issues:
`https://consent.yahoo.com/v2/collectConsent?sessionId=3_cc-session_68600cbe-0f19-4929-b8f7-d9cddcb6f399`

### What happens?
There is a data consent.

### List Subscriptions you're using:
Easylist Privacy, Fanboy Annoyance

### Your settings

- OS/version: Windows 10 Pro
- Browser/version: Firefox 91.0.2
- Adblock Extension/version: Ublock 1.38

**Comment by ryanbr** [comment]
Can't be blocked unfortantly @andreewmat
