### ISSUE TITLE
[NSFW] gaybeeg.info

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#9282]
### List the website(s) you're having issues:

`https://gaybeeg.info/`

### What happens?

After you click in almost all of the content on the page, we have requests to another pages.

### List Subscriptions you're using:

EL PT, ABP and AA (reproducing the user config)

- OS/version: macOS 10.15.7
- Browser/version: Chrome
- Adblock Extension/version: 3.11.2

### Other details:

To reproduce, you can simply click in any of the images, after you open one of the presented content, as well as the header of the webpage.

I don't know if snippets would be the best solution, but i could end this popup pages with the following blocking filters:

```
||romepoptahul.com$script
||ployea.com$script
||www.lghdoxzulv.com$script
```

**Comment by ryanbr** [comment]
Update the lists.
