### ISSUE TITLE
[NSFW] skymanga.co

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylist#9283]
### List the website(s) you're having issues:

`https://skymanga.co/` `https://skymanga.co/manga/sister-neighbors/148/`

### What happens?

How to Reproduce:
https://vimeo.com/619811261/c9b828f82a 

### List Subscriptions you're using:

EL PT, ABP, AA (to reproduce the user issue)

### Your settings

- OS/version: macOS 10.15.7
- Browser/version: Chrome
- Adblock Extension/version: 3.11.2

### Other details:

I believe the following filter is the responsible for blocking that : 
`||tiltgardenheadlight.com$script`

**Comment by ryanbr** [comment]
Force an update of the lists.
