### ISSUE TITLE
beinganddoing.online

### ISSUE THREAD

**Issue by Gitoffthelawn** [easylist/easylist#9286]
### List the website(s) you're having issues:

`beinganddoing.online`

### What happens?

Global DOM filter in Easylist Cookies breaks viewing videos in `beinganddoing.online`.

### List Subscriptions you're using:

Even when *only* using Easylist Cookies, and no other filtering lists, videos on that site will not work.

### Your settings

- OS/version:  Linux, macOS, Windows
- Browser/version: Firefox 92.0.1
- Adblock Extension/version: uBO 1.37.2

### Other details:

The offending global filter is:  
`##.elementor-popup-modal.dialog-widget`

**Comment by ryanbr** [comment]
CLosing, issue was fixed
