### ISSUE TITLE
wavepc.pl

### ISSUE THREAD

**Issue by RikoDEV** [easylist/easylist#929]
Easylist blocks the https://wavepc.pl website logo in header.

URL: https://wavepc.pl/

EasyList list enabled:
![s2](https://user-images.githubusercontent.com/18230443/36609929-dcedf99c-18ce-11e8-9a73-ccffbbc5ac85.PNG)

EasyList list disabled:
![s3](https://user-images.githubusercontent.com/18230443/36609968-f3b1003e-18ce-11e8-91a1-ca20e69ba2d4.PNG)

uBlock 1.15.11b0
Easylist 201802231158
Firefox Quantium 59.0b11

**Comment by ryanbr** [comment]
Done.
https://github.com/easylist/easylist/commit/5ea16d2216828abf3f74aa8f16deb083ddb5a4cc
