### ISSUE TITLE
lowcygier.pl

### ISSUE THREAD

**Issue by hawkeye116477** [easylist/easylist#930]
EasyList blocks links on this site.
Example page -> https://lowcygier.pl/promocje-pudelkowe/call-of-duty-infinite-warfare-legacy-edition-na-ps4-za-7999-zl-w-empiku/
Fix -> `@@||go2cloud.org^$popup,domain=lowcygier.pl`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/697f27d9b5c0f2727f6dc5150cb3e5202dca5691
