### ISSUE TITLE
poweradblocker.com?

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#9322]
Thanks to @Titomrock21 in https://github.com/blocklistproject/Lists/issues/508 I started to look up the domain and why it should be on the `easylist/easylist_adservers.txt`

When I review the domain and the addon page it comes to me, that it appears more like a scam or SpyWare addon that adware, I for sure suspect (without reading the source) it to inject own ads but that scam in my universe.

Anyone who can remember or even know why this was added to the adserver list?

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/df7841db8bc1e748a6454d6d1e05ee2275a956d6

**Comment by spirillen** [comment]
That only tell when it was added, nothing about why and why it was added to the specific lists
