### ISSUE TITLE
xvideos issue

### ISSUE THREAD

**Issue by xevidencex** [easylist/easylist#934]
This isn't helpfull:

https://github.com/easylist/easylist/commit/2880f3c049d14d647e32a26c0bea9da413de7d1d

I can hide the stupid warning on all videos of xvideos.com
but if it's not clicked, the suggested videos below do not appear clearly,
they remain encrypted. result:
on each time i go to the site, i must click on that stupid warning..

because i don't have a filter to prevent that stupid blurring of suggested videos.

**Comment by ryanbr** [comment]
No warning seen, video played fine. Tested on other videos, looks good.

**Comment by xevidencex** [comment]
Could you then please send me an adapted filters version, just mod them a
bit, because i can't upgade from firefox 44.0.2 whichis "the only up to
date version" that supports "all my addons",
i can't get rid of decades of addons ceations/contributions because mozilla
decided to review addon compatibility, i also use: ublock origin 1.11.4

**Comment by ryanbr** [comment]
We all went through the pain of web-extensions transition, supporting older versions of FF can't always be done.

**Comment by xevidencex** [comment]
please try for that particular site because trust me, i have many
extensions active that are necessary, & not every's made the transition,
for the simple reason that:

-coders died
-coders abandoned support & moved to something else & don't respond to
requests
-coders moved to other browsers & stopped supporting firefox

a few addons still don't work with the latest firefox & they're vital for
everyday needs ((

**Comment by ryanbr** [comment]
I'm not going to start reverting my setup to older versions of firefox, if you have a filter suggestion or fix, then show it. Otherwise keeping an older version of the browser is just a security issue.

**Comment by xevidencex** [comment]
sleep well
