### ISSUE TITLE
yorknewstimes.com

### ISSUE THREAD

**Issue by ThinksHeIsCool** [easylist/easylist#9351]
### List the website(s) you're having issues:
`https://yorknewstimes.com/`

### What happens?
advertising

### List Subscriptions you're using:
uBO's enabled-by-default filter lists on PC

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin 1.38.2

**Comment by ryanbr** [comment]
Which advert @ThinksHeIsCool  I'm not seeing a lot of blocked items.

**Comment by krystian3w** [comment]
`##.tnt-dmp-reactive.block`

?
