### ISSUE TITLE
Filter blocking voting/verification and autocomplete function at torrentz2.eu

### ISSUE THREAD

**Issue by billyjeanis** [easylist/easylist#936]
the filter is :
`||torrentz2.eu^$xmlhttprequest`

Is blocking all xmlhttprequest requests !
example of url
https://torrentz2.eu/930854178824ef9a19222fb82dc919810feb2fd1
You cannot verify torrent by  pressing the 
> "Verify as a good torrent" 

button or any other button that has to do with verification.
This filter is also blocking the "autocomplete" function in search box!
Cannot find any logical reason why you are blocking all xmlhttprequest functions in this page. Please advice.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a77dd675c5b445b5e8384e84c68babca4abf4cb4

**Comment by billyjeanis** [comment]
The autocomplete search function is still not working.
Try to write something in the search box and "autocomplete" will not work.
