### ISSUE TITLE
maaseuduntulevaisuus.fi

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#9369]
### List the website(s) you're having issues:

`https://www.maaseuduntulevaisuus.fi/`

### What happens?

Centered notification prompt. I first learned about this from https://github.com/AdguardTeam/AdguardFilters/issues/96905, and was able to reproduce it soon after learning about it.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/136942168-c7310bb7-dd44-4cee-b307-e0ee9cc78647.png)

### Your settings

- OS/version: Windows 11 x64
- Browser/version: Chrome 94.0.4606.81 x64
- Adblock Extension/version: uBO 1.38.3b2 + IDCAC 3.3.2

### Other details:

I propose adding to Fanboy's Notifications Blocking List:
```
/notification-handler-app^
##.nav-link--notification-handler
! Optional:
/notification-sw.js
```

![image](https://cdn.discordapp.com/attachments/580744777340026900/897447990069964810/unknown.png)

**Comment by DandelionSprout** [comment]
Indeed I did.

**Comment by ThinksHeIsCool** [comment]
and did you ask for the free AdGuard VPN subscription?
