### ISSUE TITLE
chinese 微店 (weidian) tracker

### ISSUE THREAD

**Issue by wft44maqb** [easylist/easylist#9381]
https://shop1713695592.v.weidian.com/?userid=1713695592&distributorid=799204524&wfr=pbj_shop_3006_wxph5&ifr=pbj_shop_3006&share_relation=bc900a77887ace43_799204524_1

![image](https://user-images.githubusercontent.com/86122516/137106009-b9285596-641d-4d95-bd2b-5614d2761493.png)

![image](https://user-images.githubusercontent.com/86122516/137106388-db5dd711-e4ab-4681-8b7d-659cf0a7e10a.png)

`$removeparam` / `$queryprune`: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#removeparam

```
||logtake.weidian.com^
||weidian.com^$removeparam=distributorid
||weidian.com^$removeparam=wfr
||weidian.com^$removeparam=ifr
||weidian.com^$removeparam=share_relation
```

https://github.com/search?q=%22logtake.weidian.com%22&type=code

**Comment by felix-22** [comment]
OK.

**Comment by ryanbr** [comment]
Which site is covering `||logtake.weidian.com^` ? 

https://publicwww.com/websites/%22logtake.weidian.com%22/  Shows nothing @wft44maqb

**Comment by llacb47** [comment]
> Which site is covering `||logtake.weidian.com^` ?
> 
> [publicwww.com/websites/%22logtake.weidian.com%22](https://publicwww.com/websites/%22logtake.weidian.com%22/) Shows nothing @wft44maqb

I see requests to it on the first link in the original post
