### ISSUE TITLE
First party cname tracker

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#9383]
### List the website(s) you're having issues:
<details>
<summary> Tracker domain List partially nsfw</summary>

```
11jboxuvhdn.www.jeddd.com
1asr0l6zjb1.franchiseplus.nl
kfuf06i7g8qn.www.earthclassmail.com
dzoytx9uvr2h.www.cybernetman.com
1op1je6zs97.www.emanualonline.com
1q6ck0lrhrr.www.newsinside.org
1zzs6w25i8n.tube.inflatevids.xyz
fp84rw0jinz7.blanc.ru
25voj20abod.honeyswap.org
ok2691lw4w3g.www.word.com.au
2829i2p88jx.www.csaladinet.hu
vpm4dla7q83q.fjlaboratories.com
y1d2jmz1ousj.www.logology.co
5n2y9omclb.panprices.com
8p0kiyq5mq1d.flex.team
9upp9h74lf50.www.botcomics.com
c5ai4b502b.www.chandlerorchards.com
cihnqp6p65.koinly.io
pcjhd5yuwpup.www.nookgaming.com
p9jhxqlkmn.miniso.com.gr
9a7dv7p21r7m.furucombo.app
qt5jl7r111h7.allesvoormijnvakantie.nl
xlvvy4msxr.coolinastore.com
qt5jl7r111h7.allesvoormijnvakantie.nl
164fi5kesvt.www.usa-corporate.com
ros3d4dbs3px.salud-masculina.info
x2l5lsn8rvsq.li.finance
3wn3w3skxpym.round.t3.gg
1bw7etm93lf.www.woodbrass.com
s2whyufxmzam.chatpay.com.br
qwcp5tza48tt.xpollinate.io
dfq0o3v099r9.nofluffjobs.com
2qqfxz5kecr4.www.eldorado.gg
```
</details>

### What happens?

Tracking coming from these first party domains
<img width="542" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/137146605-345b5d6c-760b-4016-af4a-252d52459ba0.PNG">

### List Subscriptions you're using:

uBlock Origin default with EasyList, EasyPrivacy and EasyList germany

### Your settings

- OS/version: win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin 1.38.4

### Other details:

**Comment by Yuki2718** [comment]
> there is already a open issue

Okay, missed that.

**Comment by JobcenterTycoon** [comment]
@ryanbr i have new data:

`bj5gprgxq6y7.franchiseplus.nl`
`8n8rarw7yjvy.www.cybernetman.com`
`gbg22hfdkdip.www.logology.co`
`ooyk93cxdqv8.www.usa-corporate.com`

New:

`grxkwphx0yk5.stoic.ai`
`h5nmx7qrncrp.mailfloss.com`

**Comment by JobcenterTycoon** [comment]
@ryanbr i have new fresh data

`lis39l95rq1s.furucombo.app`
`4tiz3b7uvzv5.app.polymersearch.com`
`0c0l6l9v72hq.mailfloss.com`

New:
`1iy4gu0lpkp.my.gloryleague.basketball`

**Comment by JobcenterTycoon** [comment]
@ryanbr tracking is back

CNAME: `delightful-development.ml`

`https://franchiseplus.nl/themes/jacket/scripts/dataunlocker.js`

```
lrkd5qph0yt6.franchiseplus.nl
77mxl6z40n3u.www.cybernetman.com
ekpnog9km4am.www.word.com.au
wy886nacmkg2.fjlaboratories.com
zv7sm29ebr0i.www.logology.co
8rqwuq2dtrki.www.botcomics.com
5jr6laiorl0y.www.chandlerorchards.com
lis39l95rq1s.furucombo.app
4tiz3b7uvzv5.app.polymersearch.com
0c0l6l9v72hq.mailfloss.com

1iy4gu0lpkp.my.gloryleague.basketball
88bs5dlqb6m5.npm-explorer.tk
```

**Comment by JobcenterTycoon** [comment]
@ryanbr new tracking data

CNAME: `reckoning-internet.tk` (changed today, was stable for 24 days)

```
f5q72e2o8r5f.www.word.com.au
t7znchd8ql3w.fjlaboratories.com
0z1gq54yn38l.www.botcomics.com
eb6p0q0rtcjh.www.chandlerorchards.com
uj1sfw9w9bsm.stoic.ai
ym1kiez6wc40.mailfloss.com
z24rhhuv7esb.www.logology.co

din1j0su0u99.artwallstreet.io
```

**Comment by JobcenterTycoon** [comment]
@ryanbr  They changed again

CNAME: `fantastic-diamond.cf`

```
j5qtzhvpaq6t.stoic.ai
moahcor6ifhk.app.stoic.ai
dc19qtc6mkm6.www.cefirates.com
4giuy4ieobjb.fjlaboratories.com
```

```
8ehhtsv9bo7i.monkeylearn.com
jzbzvk10u32f.adria.gg
```

I also get many requests from `anti-adblock.herokuapp.com` on `https://stoic.ai` looks like tracking

**Comment by spirillen** [comment]
Hey @JobcenterTycoon 

How much are you getting paid for your commits??

![image](https://user-images.githubusercontent.com/44526987/145450145-0df3baca-ed52-4b12-8d56-1703b7d72070.png)

**Comment by JobcenterTycoon** [comment]
Actually 0,5€ per reported dataunlocker subdomain, 0,5€ per CNAME domain and for high traffic sites i get up to 5€ per domain.

<details><summary> Spoiler: Reality</summary>
Its a joke i do it for free. Not even Dataunlocker give me money to get rid of my reports 😂.
</details>

At least a good chunk of their tracking is blocked. Most of the unblocked domains are low traffic sites as far i know but i not know how many domains are hidden (i mean many domains not appear in the Adguard CNAME https://github.com/AdguardTeam/cname-trackers/issues/15#issuecomment-976436810)

**Comment by spirillen** [comment]
For my self I can't help my self from thinking why I should keep do it for free, when it is clear other are paid for less.

> https://github.com/AdguardTeam/cname-trackers/issues/15#issuecomment-976436810

Have shared my thought on that one now.

**Comment by JobcenterTycoon** [comment]
The cloudfront script from https://github.com/easylist/easylist/issues/9383#issuecomment-989774720 seems to be stable

**Comment by JobcenterTycoon** [comment]
@ryanbr 

dataunlocker Tracking coming from `https://www.tragonesymazmorras.com/prox_data_g.js`

```
km9kyssc7r72.www.tragonesymazmorras.com
targ2i21km4b.kvest.ee
2rwglsoxbjds.www.marketdata.app
yxbh3a53nv.adaptive.marketing
8ehhtsv9bo7i.monkeylearn.com
```
