### ISSUE TITLE
seoab.io

### ISSUE THREAD

**Issue by nashvilletrain** [easylist/easylist#9395]
### List the website(s) you're having issues:

`seoab.io` script on `https://drizly.com`

### What happens?

`seoab.io` script enables users to change HTML on the websites. So blocking `seoab.io` on `https://drizly.com` potentially can lead to showing invalid content for clients with adblock.

Thank you.

**Comment by ryanbr** [comment]
I would need proof this is causing issues, pages loaded fine here.  Tested on https://www.revivalanimal.com/

**Comment by ryanbr** [comment]
Closing, not enough details supplied. Website is fine.
