### ISSUE TITLE
azcentral.com EasyList false positive

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#94]
http://yourbusiness.azcentral.com/implied-vs-implicit-interest-rate-29500.html

EasyList breaks the banner links, and causes the `Driven by Demand Media` footer item to overlap with the article's first paragraph.

**Comment by monzta** [comment]
Does that help? https://github.com/easylist/easylist/commit/014342f3a1568cd12fc682533fbf37cdca9a73f8

**Comment by terrorist96** [comment]
Looks like it. Thanks!
