### ISSUE TITLE
[NSFW] jetztlive.com [breakage, thumbnails not loading, EasyList + Peter Lowe's (uBO)]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#9412]
### List the website(s) you're having issues:

`https://jetztlive.com`
`https://jetztlive.com/shows/all-shows`

### What happens?

Breakage, thumbnails not loading
Filter lists causing the breakage:
- EasyList 
- Peter Lowe’s Ad and tracking server list

### List Subscriptions you're using:

- EasyList 
- Peter Lowe’s Ad and tracking server list

### Your settings

- OS/version: W764SP1
- Browser/version: FF 93 (the issue doesn't occur on Opera)
- Adblock Extension/version: uBO 1.38.7b2

### Other details:

![1](https://user-images.githubusercontent.com/75935068/137586302-4c06ada4-2c78-412c-b108-42c6c2e7ae27.png)

**Comment by Khrin** [comment]
Site is working correctly for me with EasyList only. Does it also for you?

Meanwhile, @pgl dunno if you're aware of this potential issue? I can't check atm also with your list.

**Comment by felix-22** [comment]
FIlter causing the breakage:

EasyList `||777partner.com^$third-party`
Peters Loves `||777partner.com^`

![2](https://user-images.githubusercontent.com/75935068/137595825-6edd7915-47a1-4195-8f53-9efeb190febc.png)

**Comment by pgl** [comment]
@Khrin `777partner.com` is an ad server, so I'm leaving it in the list I'm afraid.
