### ISSUE TITLE
ee.co.uk

### ISSUE THREAD

**Issue by MER-C** [easylist/easylist#943]
https://ee.co.uk/

Unblocked trackers:
* https://tags.tiqcdn.com/utag/ee/detica/prod/utag.sync.js
* https://tags.tiqcdn.com/utag/ee/detica/prod/utag.\d{5}.js
* https://ee-tagging.s3.amazonaws.com is suspicious.

https://ee.co.uk/ee-and-me/top-up-pay-as-you-go

Unblocked trackers (in addition to the above):
* https://pixelg.adswizz.com/one.png

https://shop.ee.co.uk/mobile-phones/pay-monthly/gallery?search=:best-sellers

Unblocked trackers (in addition to the above):
* https://tags.tiqcdn.com/utag/ee/detica/prod/utag.js

References:
* https://community.tealiumiq.com/t5/iQ-Tag-Management/tkb-p/tealium-iq-documentation 
* https://community.tealiumiq.com/t5/Getting-Started/Multi-CDN-for-Tag-Delivery/ta-p/13701
* https://www.adswizz.com/ 

```
$ whois tiqcdn.com
Registrant Organization: Tealium Inc
```
Adswizz and tiqcdn may be worth blocking entirely.

**Comment by Khrin** [comment]
I havent found any hit for Adswizz, what you've posted is the exact full url?

About Tiqcdn, in the past we had some issue with blocking entirely this domain...

**Comment by MER-C** [comment]
The URL is correct -- replicated in safe mode (not sure what NoScript is doing there, this was definitely safe mode):

https://www.dropbox.com/s/01ik9ylhkn1bif6/ee.png?dl=0

I don't mind if the entire domain isn't flushed, it was just a suggestion.

**Comment by Khrin** [comment]
Added a filter for Adswizz.
