### ISSUE TITLE
chinese `weibo` tracker?

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#9432]
https://weibo.com/hot/topic --> https://weibo.com/ajax/log/action?type=pic&uicode=20000405&fid=232184&act_code=4288&ext=module%3A01&luicode=&t=(hidden)

```
https://weibo.com/ajax/log/action?type=pic&uicode=20000405&fid=232184&act_code=4288&ext=module%3A01&luicode=&t=

||weibo.com/ajax/log^
```

**Comment by ryanbr** [comment]
Not seen.

**Comment by c2xusnpq6** [comment]
> Not seen.

Try again.

**Comment by c2xusnpq6** [comment]
> Not seen.

You can stay on that page longer, or try scrolling and clicking on the page.

**Comment by c2xusnpq6** [comment]
> Not seen.

reopen pls!

**Comment by c2xusnpq6** [comment]
> Not seen.

Oh! Looks like they don't allow users outside of mainland China to use the new interface anymore. @ryanbr
