### ISSUE TITLE
topwindata.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#9434]
### List the website(s) you're having issues:

```
https://www.topwindata.com/windowsapps/publisher.html?id=290794
https://www.topwindata.com/windowsapps.html
```

### What happens?

Placeholders in various categories and lists.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/137883075-5748d914-a5d1-4fee-8c79-5cb5ff7e67b2.png)

### Your settings

- OS/version: Windows 11 x64
- Browser/version: Chrome 94.0.4606.81 x64
- Adblock Extension/version: uBO 1.38.5b3 + IDCAC 3.3.3

### Other details:

I propose:
```
topwindata.com#?#.search-item:-abp-has(.adsbygoogle)
topwindata.com##div[style^="width:98%;"]:not([class])
```

![image](https://user-images.githubusercontent.com/22780683/137882836-b2c14442-3e25-4c4a-b238-9c3f3748ceab.png)

**Comment by ryanbr** [comment]
Too minor.
