### ISSUE TITLE
PSN Login issue

### ISSUE THREAD

**Issue by kefaji** [easylist/easylist#9473]
https://my.account.sony.com/central/signin/?duid=00000007000901009865eb95bb727083bd815a276bc1e38be2031fdc0ef369cd88ec835f8b583a16&response_type=code&client_id=e4a62faf-4b87-4fea-8565-caaabb3ac918&scope=web%3Acore&access_type=offline&state=53e0d38e4d552faecf83286855e7a50f8adb4cc2a90c95c0374603dafd55c45f&service_entity=urn%3Aservice-entity%3Apsn&ui=pr&smcid=web%3Astore&redirect_uri=https%3A%2F%2Fweb.np.playstation.com%2Fapi%2Fsession%2Fv1%2Fsession%3Fredirect_uri%3Dhttps%253A%252F%252Fstore.playstation.com%252Fit-it%252Fpages%252Flatest%252F%26x-psn-app-ver%3D%2540sie-ppr-web-session%252Fsession%252Fv5.12.0&auth_ver=v3&error=login_required&error_code=4165&error_description=User+is+not+authenticated&no_captcha=false&cid=5df7cc82-015d-414e-9042-159de9c613df#/signin/ca?entry=ca

It seems as though Easyprivacy is breaking something up on my side. Tested with both ublock and adguard browser extension, I disabled every list currently on except easyprivacy. Turned out, right after I enter my password, an error displays, and I cannot get to login in my account unless I turn off easyprivacy list.

[https://imgur.com/a/sBRyS3N](url)

**Comment by mokide** [comment]
I can confirm this issue is unfortunately still happening. I'm running adguard browser extension and the only filter blocked by easyprivacy in the registry is  /smetrics.*/b/ss/*  @ryanbr @Yuki2718

**Comment by daniel46111** [comment]
> I can confirm this issue is unfortunately still happening. I'm running adguard browser extension and the only filter blocked by easyprivacy in the registry is /smetrics._/b/ss/_ @ryanbr @Yuki2718

I believe it's related to adguard tracking filter, nuff said

**Comment by Yuki2718** [comment]
Both  EP and TPF block `||smetrics.aem.playstation.com^` but I have no login issue. Probably is geo-dependent.

**Comment by ryanbr** [comment]
Closing ticket, we've done what we needed to do.
