### ISSUE TITLE
EasyPrivacy - Invalid rule for WordPress plugin, WPMU Domain Mapping

### ISSUE THREAD

**Issue by r-a-y** [easylist/easylist#948]
### List the website(s) you're having issues:

Any self-hosted WordPress site using the WPMU Domain Mapping plugin.
`https://wordpress.org/plugins/wordpress-mu-domain-mapping/`

### What happens?

The WPMU Domain Mapping plugin has a feature to allow for login to mapped domains.  It requires the use of a javascript file that is blocked by EasyPrivacy, which breaks this functionality.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 58.0.2
- Adblock Extension/version: uBlock Origin 1.5.10

### Other details:

The specific rule that is breaking this functionality is:

`/?dm=*&blogid=$script`

https://github.com/easylist/easylist/blob/9cc74312a9934f5abeb523220b64afa2886b8b6c/easyprivacy/easyprivacy_general.txt#L266

The javascript file that this rule is blocking has nothing to do with tracking or privacy.

View the source code of the plugin that this rule is blocking:
`https://plugins.trac.wordpress.org/browser/wordpress-mu-domain-mapping/trunk/domain_mapping.php?marks=720#L712`
`https://plugins.trac.wordpress.org/browser/wordpress-mu-domain-mapping/trunk/domain_mapping.php?marks=816#L808`

Let me know if you have any questions. Happy to provide a pull request, just let me know.

**Comment by ryanbr** [comment]
not that comfortable removing the filter, made it not applicable to wordpress.org, only.
https://github.com/easylist/easylist/commit/2495675635f61423bc1148382bfe9a7b2730a899

**Comment by r-a-y** [comment]
What are you not comfortable with? I've directly linked to the plugin source. I'm not even the plugin author, so my viewpoint is unbiased.

WordPress is a script that can run on any server, so your restriction to wordpress.org doesn't do anything.  The plugin doesn't even run on wordpress.org, so commit 2495675 doesn't apply to anything.
