### ISSUE TITLE
BBC videos are broken due to blocking

### ISSUE THREAD

**Issue by markturner** [easylist/easylist#950]
### List the website(s) you're having issues:

`https://www.bbc.co.uk/cbbc/watch/cbbc-hq-pie-shop-on-a-hill` (for example, there are others)

### What happens?

Video does not load

### List Subscriptions you're using:

`https://easylist.to/easylist/easyprivacy.txt`

### Your settings

- OS/version:  Mac OS 10.12.6
- Browser/version: Safari 11.0.3
- Adblock Extension/version: uBlock Origin 1.11.3.1

(this will happen in other environments also)

### Other details:

It is worth mentioning that the JS file that is blocked by this only sends data to endpoints that are already blocked elsewhere in the list (eg scorecardresearch.com, sa.bbc.co.uk, 2cnt.net).

This change seems to have caused this issue: https://github.com/easylist/easylist/commit/311a438217d0da237bcdc33efb0ad2bec3a5457f#diff-6b54c84f883288b1582a40f4174525e0

Screenshots below:

<img width="1059" alt="screen shot 2018-03-06 at 19 05 46" src="https://user-images.githubusercontent.com/11614/37090443-4e567fd8-21fc-11e8-929b-919ee360c562.png">

<img width="1439" alt="screen shot 2018-03-06 at 19 06 00" src="https://user-images.githubusercontent.com/11614/37090479-74d0aae4-21fc-11e8-9e5d-1f2974578986.png">

**Comment by ryanbr** [comment]
sure, https://github.com/easylist/easylist/commit/f2e6b4f96bf84cb5b7ad73786689dcf30860ac47
