### ISSUE TITLE
cryptoviet.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9530]
### List the website(s) you're having issues:
`https://cryptoviet.com/smart-contract-la-gi`

### What happens?
Ads/affiliate link

![image](https://user-images.githubusercontent.com/66517106/139516830-37bee070-189e-4033-836f-31b2212224a4.png)

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 93
- Adblock Extension/version: ublock 1.38.6

### Other details:
Proposed filter:

`cryptoviet.com##.widget-wrap.widget_text`

**Comment by ryanbr** [comment]
Non english site,
