### ISSUE TITLE
geeksforgeeks | Sign-In Popup

### ISSUE THREAD

**Issue by Dentrax** [easylist/easylist#9533]
### List the website(s) you're having issues:

https://www.geeksforgeeks.org/python-pil-putpixel-method/

### What happens?

<img width="1277" alt="Screen Shot 2021-10-30 at 19 52 08" src="https://user-images.githubusercontent.com/16493751/139542020-377f5c2c-726e-4961-bd80-0cc1b3438d50.png">

### List Subscriptions you're using:

<img width="342" alt="Screen Shot 2021-10-30 at 19 54 43" src="https://user-images.githubusercontent.com/16493751/139542103-c333c21c-c84f-4fb6-8d85-38db69862955.png">

### Your settings

Default

- OS/version: `macOS 11`
- Browser/version: `Firefox 93.0`
- Adblock Extension/version: `uBlock Origin 1.38.6`

**Comment by ryanbr** [comment]
Blocking this would stop the signin completely, be a bad idea.

**Comment by ahnafnafee** [comment]
> Blocking this would stop the signin completely, be a bad idea.

It is not possible to close this pop-up or scroll anywhere in Chrome. The only alternative is to not use the site. Users can still click on the top right button to sign in/sign up.
