### ISSUE TITLE
New tracker: tracker.hotanime.xyz [EasyPrivacy]

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#9535]
### List the website(s) you're having issues:

`https://watchcartoononline.bz/episode/rick-and-morty-season-5-episode-1/`

### List Subscriptions you're using:

![ublock 5 oct](https://user-images.githubusercontent.com/11689349/139547433-a9e0b57f-83d2-4d59-a909-2022f4378c61.jpg)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version: 

### Other details:

Proposed fix: `||tracker.hotanime.xyz^`

**Comment by Yuki2718** [comment]
Looks to be p2p "tracker" and not to be tracking domain.

**Comment by ryanbr** [comment]
Should this be blocked, without causing issues? @Yuki2718

**Comment by Yuki2718** [comment]
This is not a user-tracking server but a tracker of [this](https://en.wikipedia.org/wiki/BitTorrent_tracker) sense. I don't do p2p so no idea if blocking this is problematic for Torrent user, but think there's no reason to block non-tracker.

**Comment by ryanbr** [comment]
Leaving.

**Comment by spirillen** [comment]
> This is not a user-tracking server but a tracker of [this](https://en.wikipedia.org/wiki/BitTorrent_tracker) sense. I don't do p2p so no idea if blocking this is problematic for Torrent user, but think there's no reason to block non-tracker.

Blocking these kind of trackers can be a problem, mostly for new and older (few) peers. For the OP I can say there are repos who welcomes to blacklist this kind of trackers.
