### ISSUE TITLE
linkvertise.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#9543]
### List the website(s) you're having issues:

`https://linkvertise.com/8062/TS3StoreMagnet?o=sharing`

### What happens?

Presumably fake download buttons. I'm too scared to click on them to tell for sure.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/139587793-4efea11a-c7b7-4226-b010-e67d5160ae3c.png)

### Your settings

- OS/version: Windows 11 RTM x64
- Browser/version: Chrome 95.0.4638.69 x64
- Adblock Extension/version: uBO 1.38.7b10 + IDCAC 3.3.3

### Other details:

I propose:
```
linkvertise.com##.keyword-bullet-points-wrapper
linkvertise.com##.heading-wrapper > .pointer
(Optional?) linkvertise.com##.faq-list
```

![image](https://user-images.githubusercontent.com/22780683/139587697-3530daf0-0344-4481-aa87-336ca6440779.png)

**Comment by JobcenterTycoon** [comment]
No fake download buttons on my end it only open search results like `https://linkvertise.com/search/checkpoint%201/`

**Comment by DandelionSprout** [comment]
I applaud you for doing the necessary research, and thus I stand corrected. 🧡
