### ISSUE TITLE
Steam China `steamchina.com` tracker (2)

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#9555]
https://store.steamchina.com/ --> `POST` https://store.steamchina.com/default/usabilitytracking/

```
https://store.steamchina.com/default/usabilitytracking/

||steamchina.com/default/usabilitytracking
```

https://github.com/search?q=org%3AAdguardTeam+%7C%7Csteampowered.com%2Fdefault%2Fusabilitytracking&type=code
```
||steampowered.com/default/usabilitytracking
```

**Comment by c2xusnpq6** [comment]
https://github.com/easylist/easylist/issues/9554#issuecomment-955980426

**Comment by ryanbr** [comment]
intentionally closed. not seen, thus not commited.
