### ISSUE TITLE
Demdex & Adobedtm (Easy Privacy)

### ISSUE THREAD

**Issue by bachiary** [easylist/easylist#956]
Hi,

Domain block : *demdex.net & *.adobedtm.com
List : Easy Privacy
Example : https://www.adobe.com/

Could you please whitelist the following domain that are use to deploy Adobe solutions ?
- demdex.net (Adobe Marketing Cloud domain)
- adobedtm.com (Adobe Dynamic Tag Manager)

Your solution is breaking the Adobe mechanism and break the Adobe processes within the page when the Easy Privacy is activated (at least using the French language)
See below an example:
https://www.adobe.com/

![image](https://user-images.githubusercontent.com/33873718/37276989-b39e25ea-25e3-11e8-98af-eec993cbf58b.png)

**Comment by Khrin** [comment]
What's exactly the issue and where's located? I can't see any evident issue when visiting the provided link.

**Comment by bachiary** [comment]
Let me clarify the request - our solution (Adobe solutions) are using two domains name to operate Adobe Experience Cloud solution : demdex.net & adobedtm.com. It appears that Adblock EasyPrivacy list is blocking those 2 domains and as a result creates JS errors in all our pages (and client pages). I 
would like to know the best way to whitelist those 2 domains in the Adblock Privacy list ?

Thanks

**Comment by SMed79** [comment]
@bachiary Do you know what is the purpose of "EasyPrivacy"?

**Comment by bachiary** [comment]
@SMed79 Thanks for your feedback.
Here is the definition I've found from the your website:

"EasyPrivacy is an optional supplementary filter list that completely removes all forms of tracking from the internet, including web bugs, tracking scripts and information collectors, thereby protecting your personal data."

I understand that the list objective is to protect personal data mainly. However none of the domain I'm referring to are collecting or using personal data. All Adobe Saas solution does not use or include personal data. However our solution collect non PII information to improve end user experience, as a result website personalisation is completely broken for end-user.

On top of that, I do not understand why the Easyprivacy whitelist is including our solutions script for some domains and not all of them. I believe that we have been whitelisted in the past because we do respect end-user privacy rules.

I hope you do better understand the request now with these additional details.
I'm happy to exchange on this if needed.
Regards

**Comment by ryanbr** [comment]
Demdex.net forwards me to https://www.adobe.com/data-analytics-cloud/audience-manager.html

which certainly looks like a tracking related site.

**Comment by bachiary** [comment]
This is correct - some our solutions does collect non pii data.
Could you please get back to me regarding the whitelist rules and conditions for the EasyPrivacy list ?

Thanks

**Comment by bachiary** [comment]
@ryanbr @SMed79  - Could you please provide a comment regarding my latest comment ? Thank you

**Comment by SMed79** [comment]
@bachiary Not need to cc me, i am not an maintainer on this repo.

uBo is already opened a black hole for you here https://github.com/uBlockOrigin/uAssets/commit/0e11ba84b922ff3bef1f2c944d989e23b4a18ac7

**Comment by bachiary** [comment]
Thanks.

Would it be possible to unlock demdex requests the same way ?

**Comment by ryanbr** [comment]
Trustworthiness of adobe is question;

https://www.neowin.net/news/adobe-is-helping-some-60-companies-track-people-across-devices

Closing this ticket
