### ISSUE TITLE
XL-Bygg.no - Broken functionality (EasyPrivacy)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#9561]
### Affected site:
`https://www.xl-bygg.no/`

### Issue:
Unable to view products.

### Example:
`https://www.xl-bygg.no/category/produkter/verktoy-og-jernvare/handverktoy/`
(When clicking on a product, nothing happens)

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **EasyPrivacy**

### Problem rules:
`/gtag/js?`
`||googletagmanager.com^`

### Possible fix:
`@@||googletagmanager.com/gtag/js$script,domain=xl-bygg.no`

### Other problem filters:
* ~~**AdGuard Tracking Protection filter**~~ _(FIXED)_
~~`||googletagmanager.com/gtag/$third-party`
https://github.com/AdguardTeam/AdguardFilters/issues/98724/~~

* **hpHosts - Ad and Tracking servers only** _(DISCONTINUED)_
`googletagmanager.com`
`www.googletagmanager.com`

* **Peter Lowe's Ad and tracking server list**
`googletagmanager.com`
@okiehsch: Something to address in **uBlock filters - Unbreak** ?

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.4.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by okiehsch** [comment]
> Something to address in uBlock filters - Unbreak ?

You reported it everywhere. 😁 
If it's fixed in the regional list or EasyPrivacy nothing to do for me.
