### ISSUE TITLE
nytimes.com - Overly broad rule has hidden content of entire pages

### ISSUE THREAD

**Issue by sconaghan-nyt** [easylist/easylist#9563]
### List the website(s) you're having issues:

`/live` routes on the New York Times website. Examples:
- https://www.nytimes.com/live/2021/11/01/world/cop26-climate-change-summit
- https://www.nytimes.com/live/2021/11/01/world/covid-vaccine-boosters

### What happens?

"Live" routes on the NYT website have been affected by a fix for this [recent issue](https://github.com/easylist/easylist/issues/9490) with the homepage placeholder ad. The [HTML selector](https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_hide.txt#L2605) added is overly greedy and is basically targeting the entire rendered tree for these `/live` routes, making the page render a blank white screen.

### Other details:

If the previous fix was to just target the homepage ad placeholder, I would add the additional qualifier `html.nytapp-vi-homepage` to the query so that is doesn't unnecessarily hide these `/live` routes.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/ab90252399325fe7fc33e1015c727275837fe8ce

**Comment by Nojuuu** [comment]
@Khrin 

```
nytimes.com#?#html.nytapp-vi-homepage > body > div#app > div[class] > div[class]:-abp-has(div[class][data-testid="StandardAd"])
```

Is that specific enough?
