### ISSUE TITLE
https://care.cvs.com/care-navigation/#/authhome/consent

### ISSUE THREAD

**Issue by Sduibek** [easylist/easylist#9564]
### List the website(s) you're having issues:

`https://care.cvs.com/care-navigation/#/authhome/consent`

### What happens?

The following prompt is supposed to appear, but it doesn't appear at all, making it impossible to continue:

"Welcome! Please choose where you’d like to see your info from.
With your permission, we can bring your info together. Then we can make your health care, records and recommendations more about you."

### List Subscriptions you're using:

EasyList Cookie

### Your settings

- I've removed all other lists in my adblock extension except for EasyList Cookie
- OS/version: MacOS 11.6.1
- Browser/version: Firefox Version 93.0 - BuildID 20210927210923
- Adblock Extension/version: uBlock Origin 1.38.6

### Other details:

Screenshots: `https://imgur.com/a/EeDb1Hk`

**Comment by ryanbr** [comment]
What items are showing? @Sduibek

**Comment by Sduibek** [comment]
Just the header and footer .

**Comment by ryanbr** [comment]
Is this still an issue @Sduibek ? btw, items I'm refering to uBO blocked items.

**Comment by ryanbr** [comment]
Closing, no response.
