### ISSUE TITLE
ign.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9582]
### List the website(s) you're having issues:
`https://www.ign.com/wikis/super-mario-land-2/GB_Cheats`

### What happens?
Ads placeholders in the content of the page

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94
- Adblock Extension/version: ublock 1.38.6

### Other details:
![image](https://user-images.githubusercontent.com/66517106/140010564-23e838d5-b192-4c2b-b0d1-b811a9834d35.png)

Proposed filter:

`ign.com##section.narrow-view.wiki-bobble`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/436f67fe603e75f704437b4e3a10b43f0dedbf57
