### ISSUE TITLE
realpython.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9587]
### List the website(s) you're having issues:
`https://realpython.com/python-speech-recognition/`

### What happens?
Ads placeholders at the content, bottom and right side

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94
- Adblock Extension/version: ublock 1.38.6

### Other details:
Proposed filters:

```
realpython.com##section > div:-abp-has(.rounded)
realpython.com##.p-0.sidebar-module-inset
realpython.com##footer > .container > div
```

**Comment by Mennaruuk** [comment]
![image](https://user-images.githubusercontent.com/52135169/140362477-fee8a6e4-928d-4a75-9e2e-1ed0a1f1a548.png)

**Comment by stephenhawk8054** [comment]
Added screenshot

<details>

![image](https://user-images.githubusercontent.com/66517106/146700357-89476620-b421-4315-bc91-aeaeccf3de59.png)

</details
