### ISSUE TITLE
www.adstream.com.ro / ads.adstream.com.ro

### ISSUE THREAD

**Issue by laurlau** [easylist/easylist#959]
### List the website(s) you're having issues:

`www.adstream.com.ro / ads.adstream.com.ro`

### What happens?

When using an adblock extension, the pages are displaying incorrectly. Disabling the extension, fixes the problem.

### List Subscriptions you're using:

uBlock Origin

### Your settings

- OS/version:  Windows 10
- Browser/version:   Chrome / 65.0.3325.146 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin 1.15.2

### Other details:

![image](https://user-images.githubusercontent.com/36441600/37346292-a0ad3ac6-26d7-11e8-8856-efbcf6c5c500.png)

**Comment by SMed79** [comment]
Link for reference https://github.com/uBlockOrigin/uAssets/issues/1535

**Comment by OpenBSD-Neurotik** [comment]
Your website is a ad publisher & user tracker, it should be blocked by default, entirely! The irony is laughable, an ad publisher owner using a adblocker.

Add this to your own 'my filters' rule to not have a block.

@@||www.adstream.com.ro^
