### ISSUE TITLE
Incorrect content hidden https://www.pcgamesn.com/sable/misogyny-world

### ISSUE THREAD

**Issue by bloodyowl** [easylist/easylist#9590]
### List the website(s) you're having issues:

- https://www.pcgamesn.com/sable/misogyny-world
- https://www.legorafi.fr/2021/08/19/test-etes-vous-un-gouvernement-taliban-inclusif/

(+ 350 other websites)

### What happens?

In https://github.com/easylist/easylist/commit/5d194da657e0c4f240920a773651b8854db646c8#diff-ffb6ddda6ff333afce3b529e39bc0ce6ebebf81db67ff3ed19ee0b2b0caf3f0dR22933, `.BeOpWidget` has been marked as advertising where it's an editorial content from the publisher itself. This leads to empty articles on publisher pages.

### List Subscriptions you're using:

`easylist_general_hide`

### Your settings

Bug seen in Adblock, any OS.

### Other details:

We've already made sure that no ad can go through EasyList (by making the only BeOp domains capable of serving ads blocked), so that we're able to fallback to editorial content in that case.

Summaries here:

- https://github.com/easylist/easylist/issues/9051
- https://forums.lanik.us/viewtopic.php?f=91&t=46665

**Comment by ryanbr** [comment]
No other complaints from any one else, Seems fine here.
