### ISSUE TITLE
rateyourmusic.com leftover ad elements

### ISSUE THREAD

**Issue by 07416** [easylist/easylist#9593]
### List the website(s) you're having issues:

`https://rateyourmusic.com/release/album/pat-martino/el-hombre/`

### What happens?

Six elements with the `ADVERTISEMENT` text banner on the example page; a partial screenshot:

![image](https://user-images.githubusercontent.com/14923168/140385854-0a8db68e-19bb-47d4-8687-f665cc8c576a.png)

### List Subscriptions you're using:

The current uBlock Origin default lists.

**Comment by kah0922** [comment]
`rateyourmusic.com##.page_creative_frame` should fix most of it.
`rateyourmusic.com##.page_creative_frame:upward(td)` fixes the invisible table placeholder in the release page.
