### ISSUE TITLE
webtools.fineaty.com

### ISSUE THREAD

**Issue by krystian3w** [easylist/easylist#9595]
Ad lefovers:

`https://webtools.fineaty.com/ColorInfo/FFFFFFF6/en/Information-about-the-FFFFFFF6-color.html`

```css
webtools.fineaty.com#?#div.colorInfo-color-details:-abp-has(script[src*="adsbygoogles"], .adsbygoogle)
```

**Comment by DandelionSprout** [comment]
`webtools.fineaty.com##div[class*=" hidden-"]:-abp-has(.adsbygoogle)` also looks like it would work.
