### ISSUE TITLE
[NSFW] xxxdl.net

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9597]
### List the website(s) you're having issues:
`https://xxxdl.net/`

### What happens?
Ads placeholders

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
Proposed filter:

`xxxdl.net##div.in_thumb.thumb`

**Comment by spirillen** [comment]
`xxxdl.net##div.in_thumb.thumb` is working for me :smiley:
