### ISSUE TITLE
whittard.co.uk

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9598]
### List the website(s) you're having issues:
`https://www.whittard.co.uk/tea/tea-type/oolong`

### What happens?
Incorrect images blocking

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
Proposed filter:

`@@||bc0a.com^$image,domain=whittard.co.uk`

**Comment by ryanbr** [comment]
Should be resolved already, just force an update @stephenhawk8054

**Comment by stephenhawk8054** [comment]
Yup, I confirm it works normally now.
