### ISSUE TITLE
RapidVideo

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#960]
kissanime.ru/Anime/Kindaichi-Case-Files/Episode-113?id=141810&s=rapidvideo

Play video and you notice new tab opening with ads.

`/ads/madads300.aspx`
`/ads/madads300-2.aspx`
`/ads/madads.aspx`

Extra?

`var _0xdbfd = ["\x6E\x6E\x73\x64\x66\x62\x32\x33\x6E\x6D\x61\x73\x64\x6C\x30\x34\x37\x73\x6D", "\x70\x61\x72\x73\x65", "\x48\x65\x78", "\x65\x6E\x63"]; skH = _0xdbfd[0]; iv = CryptoJS[_0xdbfd[3]][_0xdbfd[2]][_0xdbfd[1]](bkZ); key = CryptoJS.SHA256(skH)`

**Comment by ryanbr** [comment]
Its fine, nothing to worry about. Everything is blocked
