### ISSUE TITLE
bbc.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9600]
### List the website(s) you're having issues:
`https://www.bbc.com/news/business-59129472`

### What happens?
Ads placeholder at the top

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
Proposed filter:

`bbc.com##.dotcom-ad`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f0560c11f5fcc4151c474a21b99871159f6e359c
