### ISSUE TITLE
onhax.me

### ISSUE THREAD

**Issue by BlazDT** [easylist/easylist#961]
`https://onhax.me/ccleaner-v5-31-6105-crack-all-edition`

Screenshot block is hidden due to this rule:

onhax.me##div p + div[id][class]

Please fix this rule in EasyList, thank you.

**Comment by OpenBSD-Neurotik** [comment]
Malware domain, should be permanently blocked. Cracks are often embedded with RAT's.

I downloaded one of the popular downloads and checked it and there's a RAT:
![screenshot_2018-03-25_04-15-30](https://user-images.githubusercontent.com/37639237/37870966-9f559f52-2fd2-11e8-887b-73a5946bcff3.png)

**Comment by ryanbr** [comment]
Fixed.
