### ISSUE TITLE
scotsman.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9623]
### List the website(s) you're having issues:
`https://www.scotsman.com/`

### What happens?
Ads placeholders.

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
Proposed filters:

```
scotsman.com##.ad-wrap
scotsman.com##.sc-igwadP
```

**Comment by ryanbr** [comment]
`scotsman.com##.ad-wrap` needs to be done via uBO

https://github.com/easylist/easylist/commit/5e3db483541185f1ce34c1d91ccb433c64bb5e3e
