### ISSUE TITLE
tdn.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9633]
### List the website(s) you're having issues:
`https://tdn.com/news/local/business/lower-columbia-funeral-homes-see-waves-of-requests-during-pandemic/article_32f3315b-4d36-55c2-b0d7-8b63499276c1.html`

### What happens?
Ads placeholders

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
Proposed filter:

`tdn.com##.container-breakout`

**Comment by ryanbr** [comment]
Which Ad placeholders? page looks fine here

**Comment by stephenhawk8054** [comment]
Oh, they are those break spaces like this

![image](https://user-images.githubusercontent.com/66517106/140842393-bbce930a-9451-46d4-9e1c-59ac37c2097a.png)

With no ublock, it looks like this

![image](https://user-images.githubusercontent.com/66517106/140842514-4d8260e4-0040-4c24-93eb-7d04c1649646.png)

Is it the same for you?

**Comment by ryanbr** [comment]
Okay, its a uBO issue due to $ghide @

**Comment by mapx-** [comment]
@stephenhawk8054 
`ghide` filter seems to be obsolete, could you confirm ?

`@@||tdn.com^$generichide,badfilter`

**Comment by stephenhawk8054** [comment]
> @@||tdn.com^$generichide,badfilter

Ah yeah, looks like there's nothing abnormal after disabling `ghide` on my side.

**Comment by mapx-** [comment]
removed

maybe we could remove all these filters (all of them "part of Lee Enterprises" ?!)

```
@@||auburnpub.com^$ghide
@@||billingsgazette.com^$ghide
@@||bismarcktribune.com^$ghide
@@||chippewa.com^$ghide
@@||cumberlink.com^$ghide
@@||dailyjournalonline.com^$ghide
@@||democratherald.com^$ghide
@@||elkodaily.com^$ghide
@@||fremonttribune.com^$ghide
@@||gazettetimes.com^$ghide
@@||globegazette.com^$ghide
@@||hanfordsentinel.com^$ghide
@@||herald-review.com^$ghide
@@||journaltimes.com^$ghide
@@||lacrossetribune.com^$ghide
@@||lompocrecord.com^$ghide
@@||missoulian.com^$ghide
@@||mtstandard.com^$ghide
@@||muscatinejournal.com^$ghide
@@||napavalleyregister.com^$ghide
@@||qconline.com^$ghide
@@||rapidcityjournal.com^$ghide
@@||ravallirepublic.com^$ghide
@@||santamariatimes.com^$ghide
@@||thesouthern.com^$ghide
@@||thetandd.com^$ghide
@@||theworldlink.com^$ghide
@@||tucson.com^$ghide
@@||winonadailynews.com^$ghide
@@||wiscnews.com^$ghide
```

**Comment by uBlock-user** [comment]
No more anti-adblock on those domains ?

**Comment by ryanbr** [comment]
was it used because of googlefunding maybe?

**Comment by mapx-** [comment]
or just obsolete, there is another generation of anti adb filters

```
@@||townnews.com^*/tncms/*/ads/*/tnt.ads.advertisements.$script
@@||townnews.com^*/tncms/*/ads/*/tnt.ads.adverts.$script
```

idk if these are needed too

**Comment by ryanbr** [comment]
This seemed okay https://townnews.com/news_room/new-celebrate-the-class-of-2021-with-a-revenue-generating-special-section/article_604c4a3c-986a-11eb-bd01-0b39c5d562e7.html

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a8729a1c58bd61887d59b3b9e463453e38c39375

**Comment by ryanbr** [comment]
Resolved.

**Comment by stephenhawk8054** [comment]
I'm not sure if I should continue in here or open a new issue in ublock repo, but there's another site with the same situation.

URL: `https://journalstar.com/news/local/education/voices-of-change-from-small-town-to-big-school-kaylee-denker-making-her-mark/article_6c00a804-47cb-53d9-99a9-885ee6073942.html`

![image](https://user-images.githubusercontent.com/66517106/143730408-e0cbd5e5-34e5-454c-a2de-7e280b1dafde.png)

Firefox 94.0.2, ublock 1.39.0 default

Looks like `ghide` is obsolete too and I don't see any anti-adblock with it disabled.

**Comment by mapx-** [comment]
removed
