### ISSUE TITLE
soranews24.com [breakage, some images/photos sometimes not loading]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#9637]
### List the website(s) you're having issues:

`https://soranews24.com/`

### What happens?

- breakage, some images/photos sometimes not loading
- like in:

> https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-963064099 :
> AdguardTeam/AdguardFilters/issues/79989

- the issue found in the course of a lengthy discussion:
https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-962569037
https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-962949246
https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-963059772

### List Subscriptions you're using:

Filters causing the breakage:

> https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-962949246 :
> 
> EasyList:
> ```
> ||pagead2.googlesyndication.com^
> ||googlesyndication.com/pagead/
> /pagead/osd.
> ```
> 
> Peter Lowe’s Ad and tracking server list:
> ```
> ||googlesyndication.com^
> ```

### Your settings

- OS/version: W7SP164
- Browser/version:  FF 94 / O 80
- Adblock Extension/version: uBlock Origin 1.38.7b15

### Other details:

**Solution:**
- a broader exception filter: `@@||pagead2.googlesyndication.com/pagead/*$script,domain=soranews24.com`
- or additional specific exceptions as the current one present in EasyList are not sufficient: 
> https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-963059772 :
> EasyList already has the exception filters for this site, report to them if it still doesn't work for you.
> ```
> @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=soranews24.com
> @@||pagead2.googlesyndication.com/pagead/js/google_top_exp.js$domain=soranews24.com
> @@||pagead2.googlesyndication.com/pagead/js/rum.js$domain=soranews24.com
> ```
> ^^^ Those are present in EasyList fyi.
- what exceptions can be added: 

> https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-963021327 :
> https://github.com/AdguardTeam/AdguardFilters/commit/e2c2e2ec05d6f5fa2f6bd4fa980c56505d127853/

**Screenshoot**
![k](https://user-images.githubusercontent.com/75935068/140637270-86c75da6-18b6-4226-8c02-68e754610039.png)

**Screenshoot (full)**

<details>
  <summary>Spoiler</summary>
  
![SoraNews24 -Japan News-](https://user-images.githubusercontent.com/75935068/140637486-0079da84-67fb-4da5-b35d-5f2e03889585.png)

</details>

**Comment by ryanbr** [comment]
Given the amount of fixes for this site. Its not worth it.

**Comment by felix-22** [comment]
> Given the amount of fixes for this site. Its not worth it.

Your answer is a bit ignoring, could you elaborate on it? 
1. For you, but not for AdGuard...
2. Is it worth to keep the site partially broken, because not willing to fix it?
3. Why the old exception filters are being kept then?
4. What about the alternative single solution I proposed?

> felix-22 : a broader exception filter: `@@||pagead2.googlesyndication.com/pagead/*$script,domain=soranews24.com`

@ryanbr

**Comment by ryanbr** [comment]
From https://github.com/AdguardTeam/AdguardFilters/commit/e2c2e2ec05d6f5fa2f6bd4fa980c56505d127853/

We don't have `redirect=nooptext` in EL, basically the site is checking each block item and wanting it disabled. Its more than one filter. Happy to just leave it.  Not worth it.
