### ISSUE TITLE
Wordpress header on 9to5mac

### ISSUE THREAD

**Issue by SpineEyE** [easylist/easylist#964]
### List the website(s) you're having issues:

`9to5google.com,9to5mac.com,9to5toys.com,electrek.co`

### What happens?

When logged into Wordpress, there should be a wordpress header. However it's blocked because of the rule:

```
9to5google.com,9to5mac.com,9to5toys.com,electrek.co##noscript + [class]
```

### List Subscriptions you're using:

easylist

### Your settings

- OS/version: I use Arch Linux
- Browser/version: Firefox, Chrome
- Adblock Extension/version: uBlock Origin 1.15.2

### Other details:

See the black bar here:

![wpadmin-header](https://user-images.githubusercontent.com/837230/37452670-8f99a77e-2835-11e8-8480-4334c2f17e05.png)

**Comment by ryanbr** [comment]
removed.
