### ISSUE TITLE
nydailynews.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9645]
### List the website(s) you're having issues:
`https://www.nydailynews.com/opinion/ny-oped-the-measure-of-bill-de-blasio-20211023-bizns6jhvbajrng7tnbkua6sba-story.html`

### What happens?
Ads placeholders.

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:

![image](https://user-images.githubusercontent.com/66517106/140859653-11260f6f-9e9b-4a30-8a8c-520dd728deba.png)

Proposed filters:

```
nydailynews.com##.pb-f-utilities-lead-art
nydailynews.com##.pb-container:not(> [data-pb-id^="rr-recs"])
nydailynews.com##[id^="pb-"] > [class^="spc-"]
```

**Comment by ryanbr** [comment]
Should be resolved
