### ISSUE TITLE
jyllands-posten.dk (ad placeholders)

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#9656]
### URL(s) where the issue occurs

`https://jyllands-posten.dk`

### Describe the issue

Several ad placeholders. A huge one right at the top. The others have the word ANNONCE above them.

### Screenshot(s)

![Screenshot 2021-11-09 at 13-59-17 Jyllands-Posten - Nyheder til dig, der vil vide mere](https://user-images.githubusercontent.com/52135169/140987980-5b2b257e-5f5d-4ead-a5c3-f39794ecf887.jpg)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by ryanbr** [comment]
We only block english sites in EL @Mennaruuk
