### ISSUE TITLE
MSN.com - Blocked elements (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#966]
### List the website(s) you're having issues:
`MSN.com`

### What happens?:
Some elements are blocked

### Screenshot:
![msn](https://user-images.githubusercontent.com/9382674/37489978-3fc994be-2891-11e8-9bbc-c155528988f1.jpg)

### Problem filter:
EasyList

### Problem rules:
```
||adnxs.com^$third-party
##.outeradcontainer
##.showcasead
```

### Possible fix:
```
@@acdn.adnxs.com/ast/ast.js$domain=msn.com
msn.com#@#.outeradcontainer
msn.com#@#.showcasead
```
### Note:
The script in the fix above is probably used for third party tracking, so a different approach would be preferable (if possible).

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.1 (x64)
- Adblock Extension/version: uBlock Origin v1.15.10

**Comment by THEtomaso** [comment]
The MSN site changes continously.
At the moment, you should be able to reproduce the issue here:
`https://www.msn.com/nb-no/helse/`

**Comment by THEtomaso** [comment]
OK, here's how to reproduce properly!
Instead of directly opening the subpages that I posted links to before, go to the main page instead, then click on the navigation bar button shown in this screenshot:

![msn2](https://user-images.githubusercontent.com/9382674/37496313-ad1282e8-28a9-11e8-9c83-40aaf2579b55.jpg)

**Comment by peace2000** [comment]
Pages look different now compared to the past. There is now a blocked "check also these news" panel on the right side `https://www.msn.com/nb-no/underholdning/nyheter/jason-aldean-tilbake-p%c3%a5-scenen-i-las-vegas-etter-massakren/ar-BBXVEmR` Which changes and shows different articles but the second article pattern on it has ads. Those can be blocked but plain empty pattern looks strange as those other patterns have articles...

**Comment by THEtomaso** [comment]
I really don't care anymore, since I'm using this rule now:
`||msn.com^`

**Comment by peace2000** [comment]
Well then this issue is not relevant probably :D
