### ISSUE TITLE
standard.co.uk (ad placeholder)

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#9660]
### URL(s) where the issue occurs

`https://www.standard.co.uk/news/london/lady-gaga-house-of-gucci-world-premiere-london-b965268.html`

### Describe the issue

Ad placeholder.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/140994274-af30400e-5b8f-4a7f-87ce-39a54346ccd3.png)

### Versions

- Browser & Version: Firefox 94.0.1
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.38.6

### Settings

N/A

### Notes

Thanks a lot!

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/dd570f194e10e9c1ec77e6fb401248923b8fd2d4
