### ISSUE TITLE
Current version of EasyPrivacy blocks Foxnews.com videos from playing

### ISSUE THREAD

**Issue by lakrsrool** [easylist/easylist#967]
Example URL (among all videos on Foxnews.com): http://www.foxnews.com/politics/2018/03/17/trumps-lawyer-calls-for-russia-probe-to-be-shut-down.html#

Video will fail to play with EasyPrivacy version 201803171328 (updated 3-17-18) and prior versions as well ENABLED in uBlock Origin.

Video will play successfully with EasyPrivacy version 201803171328 and prior versions as well DISABLED in uBlock Origin.

Nothing else is a factor since whether the Foxnew.com video will play or not play is solely dependent upon whether the current version of EasyPrivacy is enable or not enabled.

**Comment by THEtomaso** [comment]
Which other filters are you using?
At my end, 'EasyPrivacy' isn't causing the issue, but rather 'AdGuard English filter' (a.k.a. 'Adguard Base Filters').
I've filed a report (and a possible fix) here:
https://github.com/AdguardTeam/AdguardFilters/issues/13344/

**Comment by lakrsrool** [comment]
I'm able to get the initial video to work with EasyPrivacy enabled by changing from HTML + MSE to just using HTML for some reason but still having problems going to the next video (not a problem regarding this in another browser using EasyPrivacy however) -- so since the initial video now works with EasyPrivacy enabled (other factors changed) I'm going to assume my continuing issues are other factors and not an EasyPrivacy issue.

The fact that EasyPrivacy is working for others suggests the problem is elsewhere as well --- so many thanks for taking the time to provide all your helpful feedback --- I'll consider the matter closed specific to EasyPrivacy.

**Comment by THEtomaso** [comment]
@lakrsrool:
It seems like there's a lot of different stuff that may cause issues for FoxNews videos (which makes troubleshooting it a bit difficult).
With the latest additions of exception rules to **AdGuard Spyware filter** and **EasyPrivacy** though, the videos should play just fine.
However, if you're only using **EasyPrivacy** amongst those two filters, you'll have to refresh the page once, before the videos will play.
As an alternative to using **AdGuard Spyware filter**, you can add the following exception rule to your personal filter:
`@@||demdex.net^$third-party,domain=foxnews.com`
After you've done this, the videos will play on the first try, even if you're only using EasyPrivacy.
Hope this helps. :)

PS: The exception rule above may still be added to EasyPrivacy.
Keep an eye on this report, to find out:
https://github.com/easylist/easylist/issues/1685/
