### ISSUE TITLE
physicsandmathstutor.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9673]
### List the website(s) you're having issues:
`https://www.physicsandmathstutor.com/physics-revision/`

### What happens?
Ads placeholder at the top

### List Subscriptions you're using:

ublock default
### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
![image](https://user-images.githubusercontent.com/66517106/141223708-f8bbc2d7-ae73-4f19-9a56-ccf8da7e169f.png)

Proposed filter:

`physicsandmathstutor.com###PMT_Top`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3d2b141555caf0ebb696efe00d2ce3bb73460048
