### ISSUE TITLE
appvn.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9676]
### List the website(s) you're having issues:
`https://appvn.com/android/pubg-mobile/1-6-0/detail?id=com.tencent.ig`

### What happens?
Ads placeholder at the top

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
![image](https://user-images.githubusercontent.com/66517106/141231512-48cba3c3-5a3d-4738-a8f0-5a532c64af5d.png)

Proposed filter:

`appvn.com##.ads`

**Comment by ryanbr** [comment]
uBlock issue. $ghide

**Comment by ryanbr** [comment]
https://github.com/uBlockOrigin/uAssets/commit/6ad7764e535d2b4f7de1ccaf9daecd4df66925dd
