### ISSUE TITLE
tutorialrepublic.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9685]
### List the website(s) you're having issues:
`https://www.tutorialrepublic.com/faq/how-to-create-fixed-header-or-footer-using-css.php`

### What happens?
Ads placeholder at the top

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
![image](https://user-images.githubusercontent.com/66517106/141393209-98533b76-373f-44b5-a2da-c6fd601b3d4d.png)

Proposed filter:

`tutorialrepublic.com##.leaderboard`

**Comment by DandelionSprout** [comment]
Seems to have been fixed in AdGuard Base with `tutorialrepublic.com##.leaderboard`, at least.
