### ISSUE TITLE
ancient-origins.net

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9686]
### List the website(s) you're having issues:
`https://www.ancient-origins.net/history/ancient-history-chocolate-gift-gods-002770`

### What happens?
Ads placeholders

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
<details>
<summary> Long screenshot </summary>

![Screenshot 2021-11-12 at 09-32-42 The Ancient History of Chocolate, Gift of the Gods](https://user-images.githubusercontent.com/66517106/141399481-53e1fb4f-5a22-4ad9-aaa2-41a6e08b5746.jpg)

</details>

Proposed filters:

```
ancient-origins.net##[id^="block-block-"]:-abp-has([data-aa-adunit])
ancient-origins.net##[id$="-outbrain"]
ancient-origins.net##.top-add-block-wrapper
ancient-origins.net##.content_add_block
```

**Comment by DandelionSprout** [comment]
Seems to have been mostly fixed in AdGuard Base with `ancient-origins.net#?#.region > div.block:-abp-has(> div.block-inner div[id^="ad-unit"])`, but they could've added `ancient-origins.net##[id$="-outbrain"]` as well.
