### ISSUE TITLE
boston.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9688]
### List the website(s) you're having issues:
`https://www.boston.com/`

### What happens?
Ads placeholders at the top and page content

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock origin 1.38.6

### Other details:
![image](https://user-images.githubusercontent.com/66517106/141412028-67d28de7-5b32-4726-b561-d33936434be8.png)

Proposed filters:

```
boston.com##.o-site-header__advert
boston.com##.m-content-advert
```

**Comment by ryanbr** [comment]
Blocked already, resolved.
