### ISSUE TITLE
searchcommander.com

### ISSUE THREAD

**Issue by chirag127** [easylist/easylist#9696]
**Issue URL (Ads/Annoyance)**:
https://www.searchcommander.com/seo-tools/bulk-url-checker/

<details><summary>Screenshots:</summary>

https://www.searchcommander.com/seo-tools/bulk-url-checker/
![image](https://user-images.githubusercontent.com/76880977/140646279-95fd48cb-de31-48d4-9010-fdbf75c1b75d.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/126797496-0434116b-fc94-42c9-8139-fba02a985cf2.png)
</details><br/>https://www.searchcommander.com/seo-tools/bulk-url-checker/

**Comment by spirillen** [comment]
See https://mypdns.org/my-external-stuff/ublockorigin-rules/-/commit/2153e86438fa5420c1e72072e3636083a3826db8 + https://mypdns.org/my-external-stuff/ublockorigin-rules/-/commit/cc03982f74533aa3f8ca53ae9ab2a83cf6e0fae0 as I forgot the `###footer-widgets`
