### ISSUE TITLE
www.petitieonline.com

### ISSUE THREAD

**Issue by andreewmat** [easylist/easylist#9698]
### List the website(s) you're having issues:
`https://www.petitieonline.com/`

### What happens?
Cookie consent banner.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by iam-py-test** [comment]
I can not reproduce the issue in Firefox.
What Filterlists, Browser and Adblocker are you using?

**Comment by andreewmat** [comment]
> I can not reproduce the issue in Firefox. What Filterlists, Browser and Adblocker are you using?

Hello! I'am using Firefox 94 on WIndows 10 Pro with those filters: Easylist Privacy, Fanboy Annoyance and all default ublock origin filters. I tested the issue again and like you I can't reproduce it anymore. Maybe my filters got updated.

**Comment by iam-py-test** [comment]
> > I can not reproduce the issue in Firefox. What Filterlists, Browser and Adblocker are you using?
> 
> Hello! I'am using Firefox 94 on WIndows 10 Pro with those filters: Easylist Privacy, Fanboy Annoyance and all default ublock origin filters. I tested the issue again and like you I can't reproduce it anymore. Maybe my filters got updated.

Interesting. Can you reproduce with Fanboy Annoyances disabled?

**Comment by andreewmat** [comment]
> > > I can not reproduce the issue in Firefox. What Filterlists, Browser and Adblocker are you using?
> > 
> > 
> > Hello! I'am using Firefox 94 on WIndows 10 Pro with those filters: Easylist Privacy, Fanboy Annoyance and all default ublock origin filters. I tested the issue again and like you I can't reproduce it anymore. Maybe my filters got updated.
> 
> Interesting. Can you reproduce with Fanboy Annoyances disabled?

Yes, even with Fanboy Annoyance disabled, the consent pop-up is gone. Thanks for your time!
