### ISSUE TITLE
historycollection.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9702]
### List the website(s) you're having issues:
`https://historycollection.com/daring-escapes-from-concentrations-camps-enemies-and-crashed-planes/`

### What happens?
Ads placeholders

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
![image](https://user-images.githubusercontent.com/66517106/141606447-5a98c91e-36f5-476e-aef2-8f0e6868474d.png)

Proposed filter:

`historycollection.com##div[class^="cis_add_block"]`

**Comment by DandelionSprout** [comment]
For comparison, it seems to have been fixed in AdGuard Base with `historycollection.com##div[class^="cis_add_block"]`
