### ISSUE TITLE
pastemytxt.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9706]
### List the website(s) you're having issues:
`https://www.pastemytxt.com/OEwX7qlhVq`

### What happens?
Ads

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
![image](https://user-images.githubusercontent.com/66517106/141643158-8f7359f7-3eb5-4b80-bced-5b481830c881.png)

Proposed filters;

```
pastemytxt.com##[href*="bit.ly"]
pastemytxt.com##[href$="/ads"]
```

**Comment by DandelionSprout** [comment]
My alternate proposals are:
* `pastemytxt.com##.row .text-center` for the fake download banners.
* AdGuard Base seems to have `||imgur.com/*.gif$domain=himovies.to|pastemytxt.com` for the upper right one, which could be copied over to EasyList.
* Doublechecking with `https://redirectdetective.com/`, it surprisingly enough doesn't seem like the "How to Download" button is an ad.
