### ISSUE TITLE
duplichecker.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9715]
### List the website(s) you're having issues:
`https://www.duplichecker.com/reverse-image-search.php`

### What happens?
Ads placeholders

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
![image](https://user-images.githubusercontent.com/66517106/141664342-fb6f3be3-7416-40b5-9b95-5b4038e5621e.png)

Proposed filters:

```
duplichecker.com##div[style^="min-height:"]
duplichecker.com##.search_bar_area.container-fluid
```

**Comment by Daxy7** [comment]
@Yuki2718 filters invalid in EL for smallseotools group (fixed in uBlock Filters - Ads)
```
@@||smallseotools.com^$generichide
duplichecker.com##a[href^="https://www.duplichecker.com/"][target*="blank"][rel*="nofollow"] > img
duplichecker.com##img[src*="data:image"]
plagiarismdetector.net###bio_ep
plagiarismdetector.net###bio_ep_bg
plagiarismdetector.net##a[href^="https://www.grammarly.com/"]
smallseotools.com##.b
smallseotools.com##.px304
smallseotools.com##[class*="gram"]
smallseotools.com##[id*="gram"]
||plagiarismdetector.net/img-pop/
||smallseotools.com/webimages/*.gif
```

**Comment by Yuki2718** [comment]
I think `@@||smallseotools.com^$generichide` is worth being kept given the history.

**Comment by Daxy7** [comment]
@Yuki2718 for rotating divs `lala` now `kaka`, invalid
```
https://www.plagiarismchecker.co/
```
```
plagiarismchecker.co##[style*="display: block;"]
```

**Comment by Yuki2718** [comment]
TBH I don't have motivation now to do cat-and-mouse game with them. Maybe other maintainers can take care.

**Comment by Daxy7** [comment]
https://github.com/easylist/easylist/commit/999c3aba089e94b89ca4af0c359e29397724943a

**Comment by Daxy7** [comment]
`https://searchenginereports.net/` placeholders
`searchenginereports.net##.theMsy`

**Comment by Daxy7** [comment]
@Yuki2718 
smallseotools group, ads are hard recurring re-insertion on `plague` sites [EasyList as default filter list]

<details>

```
https://duplichecker.com/
https://duplichecker.com/reverse-image-search.php
https://plagiarismchecker.co/
https://plagiarismdetector.net/
https://searchenginereports.net/
```
```
duplichecker.com##.plkane
duplichecker.com##.qwert
duplichecker.com##spavn
plagiarismchecker.co##.mama
plagiarismdetector.net##.img09365
searchenginereports.net##.theMsy
||duplichecker.com/a6c2/tkkk.
||plagiarismchecker.co/js/ep.
||plagiarismdetector.net/js/miomp.
||plagiarismdetector.net/pd-imgs/aur.
||plagiarismdetector.net/pd-imgs/tukhan.
||searchenginereports.net/js/bioep.
! placeholder [excess perhaps]
duplichecker.com##ccc
duplichecker.com##vvv
duplichecker.com##.moiid
```
```
! invalid
duplichecker.com##[href="https://www.duplichecker.com/gcl"]
plagiarismchecker.co###afterbox
plagiarismchecker.co###topbox
plagiarismchecker.co##.kaka
searchenginereports.net##.grammarly-overall
searchenginereports.net##div[id^="theBdsy_"]
||duplichecker.com/csds/
||searchenginereports.net/theAdGMC/$image
```

</details>
