### ISSUE TITLE
[NSFW] Same pre-roll ad on multiple sites

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#9716]
### List the website(s) you're having issues:
[NSFW]
`https://www.nuvid.com/video/6613316/explode-in-mouth`
`https://www.tubeon.com/video/854233/close-up-of-guy-taking-the-cumshot-in-his-mouth`
`https://www.drtuber.com/video/7748097/hot-bus-sex-and-gay-shower-russian-xxx-this-buzzcut-bear`

### What happens?

Unskipable pre-roll ads

![ublock 31 Oct](https://user-images.githubusercontent.com/11689349/141665995-896c555f-b5f2-482c-ad30-56c4e1691d52.jpg)
### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by Yuki2718** [comment]
Generic fix is possible but IIRC there was a playback issue by such a filter on mobile (can't reproduce now though).

**Comment by spirillen** [comment]
Well I [made](https://mypdns.org/my-external-stuff/ublockorigin-rules/-/commit/1f666658#504c1634a41356618ecec41535741b31c9eed8dc_1428_1407) this rule, not sure if it is to generic yet

```css
/?spot_id=$script
```
