### ISSUE TITLE
anime-planet.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9717]
### List the website(s) you're having issues:
`https://www.anime-planet.com/anime/mushoku-tensei-jobless-reincarnation-part-ii`

### What happens?
Ads placeholders

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
<details>
<summary>Screenshot</summary>

![Screenshot 2021-11-14 at 10-21-05 Mushoku Tensei Jobless Reincarnation - Part II](https://user-images.githubusercontent.com/66517106/141666186-f76bf006-5681-4820-8acc-3e321703a823.png)

</details>
Proposed filter:

`anime-planet.com##.halo`

**Comment by plmok4** [comment]
Hhggh

**Comment by stephenhawk8054** [comment]
Another ads banner under video player

URL:
`https://www.anime-planet.com/anime/jojos-bizarre-adventure-stardust-crusaders-battle-in-egypt/videos/219743`

![image](https://i.imgur.com/nu8ilQs.png)

Firefox 95.0.2, ublock 1.40.0 default

Proposed filter:

`anime-planet.com##.video-banner`
