### ISSUE TITLE
Anti-Adblock notice when using Paraphraser.io

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#9724]
### List the website(s) you're having issues:
`https://www.paraphraser.io/`

### What happens?

![paraphraser](https://user-images.githubusercontent.com/11689349/141700360-f2f12cab-28ee-4f42-93ed-5fb5f0bc1f6d.jpg)

### List Subscriptions you're using:
![ublock lists 14 Nov](https://user-images.githubusercontent.com/11689349/141700490-f7bbeaf1-f23c-4586-8f02-e1750d67a9f7.jpg)

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by yokoffing** [comment]
Also happens with `https://paraphrasetool.com/`

**Comment by yokoffing** [comment]
Also `https://www.prepostseo.com/paraphrasing-tool`

**Comment by ryanbr** [comment]
Submit anti-adblock too https://github.com/uBlockOrigin/uBlock-issues
