### ISSUE TITLE
mirror.co.uk

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9726]
### List the website(s) you're having issues:
`https://www.mirror.co.uk/tech/you-could-secretly-mining-bitcoins-11693723`
`https://www.mirror.co.uk/`

### What happens?
Ads banners and placeholders. The `Most read` and `Recommended` sections are also blocked.

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
<details>
<summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/66517106/141745242-aced777a-59ae-477a-af6f-35d4b6dcde5b.png)

</details>
Proposed filters:

```
mirror.co.uk##.partner
mirror.co.uk##.shopwindow-advertorial
@@||i.viafoura.co/v*/www.mirror.co.uk/ingest$ping,domain=mirror.co.uk
@@||felix.data.tm-awx.com/felix.min.js$script,domain=mirror.co.uk
```

<details>
<summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/66517106/141745116-8005ae22-bad7-4f94-a655-d892c689965e.png)

</details>
Proposed filters:

`mirror.co.uk##.shopwindow-adslot`

**Comment by stephenhawk8054** [comment]
Another placeholder.

URL:
`https://www.mirror.co.uk/sport/football/news/liverpool-covid-man-utd-tottenham-25730128`

![image](https://user-images.githubusercontent.com/66517106/146629413-bc9086ab-7aa3-4a75-97ff-7b63733f15c0.png)

Proposed filter:

`mirror.co.uk##.recirculation--embedded`

**Comment by Daxy7** [comment]
ad placeholders in comments
```
https://www.mirror.co.uk/news/royals/king-charles-sleeps-oxygen-tent-32126368
```
```
mirror.co.uk##.vf3-conversations-list__promo
```
https://github.com/easylist/easylist/assets/91396482/fb37876c-fd11-4611-8ee3-7dc4cc146e58
