### ISSUE TITLE
rateyourmusic.com

### ISSUE THREAD

**Issue by sonemic** [easylist/easylist#9731]
### List the website(s) you're having issues:

Any URL on `rateyourmusic.com` which contains a link to stream music.

Example URL: `https://rateyourmusic.com/release/album/pat-martino/el-hombre/`

### What happens?

We have received complaints from our users that it's no longer possible to see which streaming services are available for albums on our site. We traced this problem to this EasyList filter:

```
||partner.linkfire.com^
```

Which was connected to https://github.com/easylist/easylist/issues/9593 even though the issue in question did not mention the Linkfire UI and only focused on ADVERTISEMENT labels.

This change breaks essential functionality of our site. The Linkfire button allows users to open links to stream/listen to an album directly from the site. The individual links contained within are compiled by our own users through a voting system.

It's true that an ad can appear within the unit, but that ad is already blocked by other EasyList filters since it uses DFP. It's also true that it can contain affiliate links, but those would presumably already be blocked by EasyList filters related to affiliate links. Thus, there's no reason to block the partner.linkfire.com domain itself as it effectively does nothing but break site functionality.

### List Subscriptions you're using:

EasyList default

### Your settings

- OS/version: Mac OS
- Browser/version: Chrome 96.0
- Adblock Extension/version: uBlock Origin

**Comment by spirillen** [comment]
Like this one

> Your computer may be infected with malware or spyware that makes automated requests

While the fact is it is your servers that is infected whit Spyware and malicious code which is designed to collect any data on any visitors devices to collect personal identifying data.

Most admit i makes it hard personally see your request is immediately issue as you obviously have bigger issues on you servers spreading malicious code. 

![image](https://user-images.githubusercontent.com/44526987/141840385-d7dd39fa-ce9a-498a-8989-d536ba3edb91.png)

**Comment by ryanbr** [comment]
Cleaned up from https://partner.linkfire.com/channel_partners/script.js; https://pastiebin.com/6192cb5b46e9d

Cleanup/Remove the adcode, which why its in EL.
