### ISSUE TITLE
nationalpost.com [nasty video breakage by multiple (5) filters lists]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#9738]
### List the website(s) you're having issues:

`https://nationalpost.com/news/canada/visit-by-indias-counterterror-agency-stirs-up-tension-over-sikh-separatists-in-canada`

### What happens?

Nasty video breakage by many filters lists, not sure whether it's related to:
- https://github.com/easylist/easylist/issues/6103
- https://github.com/easylist/easylist/issues/6651

### List Subscriptions you're using:

The following lists causing the breakage:
- EasyList
- EasyPrivacy
- AdGuard Tracking Protection
- Peter Lowe’s Ad and tracking server list 
- uBlock filters – Privacy (can be fixed with: `@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=nationalpost.com`)

### Your settings

- OS/version: Win
- Browser/version: FF 94 / O 80
- Adblock Extension/version: uBO dev

### Other details:

Broken:
![1 (1)](https://user-images.githubusercontent.com/75935068/141990962-43aab25a-88dd-4a91-810f-bdb034ba1a03.png)

Fixed:
![1 (2)](https://user-images.githubusercontent.com/75935068/141990969-b9ce761b-3ab4-4d08-b7a4-55f568758c2e.png)

**Comment by ryanbr** [comment]
Considered invideo advert.
