### ISSUE TITLE
digg.com

### ISSUE THREAD

**Issue by prodan1234** [easylist/easylist#974]
```
digg.com
```

Sponsored posts not blocked. 

**List Subscriptions you're using:**
easylist

[screenshot](https://i.imgur.com/Ir3JYID.png)

OS/version: macOS 10.13.3
Browser/version: Chrome 66.0.3359.45
Adblock Extension/version: uBlock 1.15.18

**Comment by OpenBSD-Neurotik** [comment]
Somebody was very lazy and did a simple block element on digg by using the element picker, while that generally may work, once the site changes the ID you're back to square one, secondly all the other real content also published under the same class.
```
digg.com##.grid-col-1.digg-story--homepage.js--story-2qnzdEf.js--digg-story.digg-story
digg.com##.grid-col-1.digg-story--homepage.js--story-2CJlpc6.js--digg-story.digg-story
```

You can tell there's a unique java script generated ID (2qnzdEf.js) in there so whenever new sponsored content is introduced the block becomes useless. While we could write a if:has cosmetic block we would block all content instead.

Instead, we use the browser built in element inspector (f12) and check what else the element is identified as:

In this case the following identifiers are found:
```
data-primary-tag-slug="apps-we-digg"
data-primary-tag-display="Sponsored"
```
The solution to semi-permanently block it becomes:
```
digg.com##[data-primary-tag-slug="apps-we-digg"]
digg.com##[data-primary-tag-display="Sponsored"]
```

We also find a need to block this referral lead generation cancer so if digg decides to use different data tags the user is still prevented from seeing the new website pop-up click with potential harmful scripts.
```
||go.radiusbank.com/radius_hybrid/?utm_source=*$popup,important
```

Spread the joy.

**Comment by prodan1234** [comment]
Thanks for the help. Is this going to be implemented?
