### ISSUE TITLE
nowtolove.com.au [big nasty ad placeholder at the top]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#9742]
### List the website(s) you're having issues:

Example subpage: `https://www.nowtolove.com.au/`

### What happens?

Big nasty ad placeholder at the top.

### List Subscriptions you're using:

- uBO default filter lists
- enabling AdGuard Base does not help either
### Your settings

- OS/version: Win
- Browser/version: FF 93 / O 80
- Adblock Extension/version: uBO dev
### Other details:

![u](https://user-images.githubusercontent.com/75935068/142022959-6f0efa19-72df-46ef-9e5c-fb5a04e0902e.png)

**Comment by mapx-** [comment]
test
