### ISSUE TITLE
insider.co.uk [nasty search field breakage by multiple (4) filters lists]

### ISSUE THREAD

**Issue by felix-22** [easylist/easylist#9743]
### List the website(s) you're having issues:

`https://www.insider.co.uk/`

### What happens?

Nasty search field breakage by multiple (4) filters lists.

### List Subscriptions you're using:

The following lists causing the breakage:
- EasyPrivacy
- AdGuard Tracking Protection
- Peter Lowe’s Ad and tracking server list 
- uBlock filters – Privacy

### Your settings

- OS/version: Win
- Browser/version: FF 94 / O 80
- Adblock Extension/version: uBO dev

### Other details:

Broken:
<img src="https://user-images.githubusercontent.com/75935068/142027951-ad7e4e67-eac4-45dd-a71b-eaa539e51f70.gif" width="500">

Fixed:
<img src="https://user-images.githubusercontent.com/75935068/142027960-16f761e8-a492-46ca-b12e-14b2e0c5bf0b.gif" width="500">

**Comment by THEtomaso** [comment]
This should be considered "as intended", IMO.
It's not a proper site search function.
They've just embedded Google search instead.
Same thing as using the `site:insider.co.uk` parameter @ `google.com`.

**Comment by mapx-** [comment]
test

**Comment by Yuki2718** [comment]
`*##[id^="div-gpt-ad"]` is too common, I think it's better to add `##div[id^="div-gpt-ad"]` (to circumvent `#@#[id^="div-gpt-ad"]` - 99% use cases are div) to uBlock filters - Legacy and specific fix for where GFC matters.
