### ISSUE TITLE
Incorrect blocking of playback end signal on telekomtvgo.hu

### ISSUE THREAD

**Issue by nyuszika7h** [easylist/easylist#9748]
### List the website(s) you're having issues:

```
https://player.telekomtvgo.hu/
```
(Requires account and EU IP)

### What happens?

This is a Hungarian streaming service that uses the following request to signal that you have stopped playing a video, because the number of simultaneous playback devices is limited.
```
https://ottapp-appgw-amp-a.proda.dtp.tv3cloud.com/amc/beacon?owner_uid=hu001&media_uid=XXX&user_token=XXX&session_uid=XXX&primary=XXX
```

As far as I can see, there isn't any sensitive data sent in the request, just this:
```xml
<beacon><complete>true</complete><inhome>yes</inhome><inhome_changed>false</inhome_changed><type></type><live>false</live><inhome3pp>true</inhome3pp></beacon>
```

If this request is blocked, it breaks site functionality because eventually you will be unable to watch any videos and get an error saying you have too many simultaneous streaming sessions.

### List Subscriptions you're using:

EasyList, EasyPrivacy

### Your settings

- OS/version: Ubuntu 21.10
- Browser/version: Chrome 95
- Adblock Extension/version: uBlock Origin 1.38.6

### Other details:

![Screenshot of uBlock filter log](https://user-images.githubusercontent.com/482367/142183426-a22a48a4-729a-49a9-a411-b37a06f35c6b.png)
![Screenshot of website error](https://user-images.githubusercontent.com/482367/142182756-60ada446-61da-41de-88ec-6c35d013ffcc.png)

**Comment by okiehsch** [comment]
Test.
