### ISSUE TITLE
[NSFW] fetishshrine.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9752]
### List the website(s) you're having issues:
`https://www.fetishshrine.com/videos/4074767/busting-her-pass/`

### What happens?
Ads under video player and at the bottom

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
[NSFW screenshot](https://i.ibb.co/HqRTCGJ/image.png)

Proposed filters:

```
||fetishshrine.com/jsb/js_lo.php$script,1p
fetishshrine.com##.video-options
fetishshrine.com##.native-holder
```

**Comment by spirillen** [comment]
I can't replicate this

### List Subscriptions you're using:

- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist
- Peter Lowe’s Ad and tracking server list
- Spirillen's – Adblock Rules (https://mypdns.org/my-external-stuff/ublockorigin-rules/)

**Comment by stephenhawk8054** [comment]
I used default settings of ublock, already purged and forced update the filters, but the ads are still there

![image](https://user-images.githubusercontent.com/66517106/142419373-f6e5908a-ebc3-465e-9ab2-90b4d9a07a28.png)

**Comment by spirillen** [comment]
Found them with whonix...

It is a rule I have in my set that blacklist your suggestion.

Let's make a diff here
```shell
diff std.text extd.text 
1a2
> ##+js(abort-on-property-read, customScript)
3c4,5
< ##+js(abort-on-property-read, decodeURI)
---
> ##+js(addEventListener-defuser, getexoloader)
> ##+js(no-floc)
6d7
< ##.adsBox
8a10,14
> ##.advertising
> ##.banner
> ##.btn-share
> ##.nav > li > a[target="_blank"]
> ##.pinterest
9a16,18
> ##.share-link
> ##.socials
> ##.text_adv
10a20,23
> ##[href*="pinterest.com/pin/create/button/"]
> ##[href*="reddit.com/submit?url="]
> ##[href*="twitter.com/share"]
> ##a[href^="//twitter.com/share"]
13,14c26,28
< ads.exoclick.com/ads.js$script,redirect-rule=noop.js
< exoclick.com^$3p
---
> `##a[href^="//www.reddit.com/submit"]`
> `##a[href^="https://claring-loccelkin.com/"]`
> `##a[href^="https://pinterest.com/pin/create/"]`
19a34,38
> fetishshrine.com/js/customscript.js
> fetishshrine.com/js/customscript.js
> fetishshrine.com/jsb/js_script.js
> fetishshrine.com/jsb/js_script.js
> fonts.googleapis.com^$stylesheet
21a41
> google-analytics.com/ga.js$script,redirect-rule=google-analytics_ga.js,domain=~daj.jp
23d42
< noop.js
```

Meaning I have hits on the following:

```
##.advertising
##.banner
##.btn-share
##.nav li a[target="_blank"]
##.pinterest
##.share-link
##.socials
##.text_adv
##[href*="pinterest.com/pin/create/button/"]
##[href*="reddit.com/submit?url="]
##[href*="twitter.com/share"]
##+js(addEventListener-defuser, getexoloader)
##+js(no-floc)
##a[href^="//twitter.com/share"]
##a[href^="//www.reddit.com/submit"]
##a[href^="https://claring-loccelkin.com/"]
##a[href^="https://pinterest.com/pin/create/"]
fetishshrine.com/js/customscript.js
fetishshrine.com/jsb/js_script.js
fonts.googleapis.com^$stylesheet
google-analytics.com/ga.js$script,redirect-rule=google-analytics_ga.js,domain=~daj.jp
```

our differences is found :smile: 

Notice these 2 rules

```css
fetishshrine.com/js/customscript.js
fetishshrine.com/jsb/js_script.js
```

**Comment by ryanbr** [comment]
I couldn't see it either.

**Comment by stephenhawk8054** [comment]
Yup, I've just updated the filter and I see that new filter is added and the ads are gone now.

![image](https://user-images.githubusercontent.com/66517106/142551775-a7a42cea-3a91-4339-aa65-3058cd917871.png)
