### ISSUE TITLE
temp-mail.org

### ISSUE THREAD

**Issue by theel0ja** [easylist/easylist#976]
### List the website(s) you're having issues:

* `https://temp-mail.org/`

### What happens?

Unblocked ads

### List Subscriptions you're using:

Easylist

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 60 Beta
- Adblock Extension/version: uBlock Origin

**Comment by OpenBSD-Neurotik** [comment]
```
!User tracking:
||https://sb.scorecardresearch.com/beacon.js
||static.criteo.net^
||googletagmanager.com/gtm.js
||secure.quantserve.com^
/greenoaks.gif?
/imp.gif?


!Anti-adblocker
||temp-mail.org/js/antiblock.js^
!General rule:
/antiblock.js

!ad publishers:
||pagead2.googlesyndication.com^
||temp-mail.org/js/google.js$script       (ezoic banger ad popup script)


!Cookieconsent general rule:
/cookieconsent.

```

**Comment by ryanbr** [comment]
Most of those are already blocked.

https://github.com/easylist/easylist/commit/c06e30bcd1d4604b1290e7a2664c6805b6a6d2c9
