### ISSUE TITLE
gmailnator.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#9766]
### List the website(s) you're having issues:

`https://www.gmailnator.com/inbox/#dotatmp+labyu@gmail.com`

### What happens?

NordVPN ad

<img width="613" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/142435538-8e2e54d6-5ab1-4358-befc-895b191da54c.PNG">

### Your settings

- OS/version: Win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin 1.38.6

### Other details:

Possible filter: `gmailnator.com##a[href^="https://go.nordvpn.net/aff_c?offer_id="]`

**Comment by spirillen** [comment]
Let's make the spam generic, I don't see why we should be able to do it something like this!
Is there any desirable reasons not to hide this kind url?

```css
##a[href*="nordvpn.net/aff_c"]
```

**Comment by JobcenterTycoon** [comment]
i get a new vpn ad now
<img width="546" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/164689642-5c12b743-4138-4ad8-a5a5-af5b9ea6d669.PNG">

`##a[href^="https://fastestvpn.com/lifetime-special-deal?a_aid="]` will hide it
