### ISSUE TITLE
Etsy's First Party Ads blocked by EasyList

### ISSUE THREAD

**Issue by newsomc** [easylist/easylist#9783]
This was sent to easylist@protonmail.com:

Hello EasyList,

Over the past 3 days we've noticed an increased amount of activity in the EasyList GitHub repository adding new rules to block content on our site. All of the advertising on our website is First Party ads for seller listings on the Etsy site itself, and according to the policies listed in your GitHub repo, should not be blocked. 

We are referring to the policies listed here: https://github.com/easylist/easylist/blob/master/README.md 

Specifically this line:
“The goal of this repository is to block ads on English and International sites. First-party ads (that don't link, or passthrough to 3rd-party sites) won't be targeted directly.”

Here are the most recent commits:
https://github.com/easylist/easylist/commit/cda7025bebd9742ed93ad4742ee577a3fc16a48e
https://github.com/easylist/easylist/commit/a7cd96c3efa53479320d647206c80284264744d1
https://github.com/easylist/easylist/commit/4779ab1f448e45a2da0377bfd03af6b004d77dde
https://github.com/easylist/easylist/commit/4014e5be26e736897fc07aaa18ddfd1327d55d0a
https://github.com/easylist/easylist/commit/e6a331dfff9af69bfc780b01505cd1ba95834a1f

We’d appreciate your removal of all rules targeting content on our site as we do not link to external content nor do we embed external content on our website. Our sellers would appreciate this as well.

Thank you

**Comment by ryanbr** [comment]
CC'ing the etsy lawyer, and only expecting one outcome huh. Basically a remove or else ? We block Ebay Ads, Amazon ads, what makes blocking Etsy any different?

**Comment by spirillen** [comment]
> ... Basically a remove or else ? ...

makes me thinks of another Hollywood thing

![Shoot first and stay dumb](http://filmfanatic.org/reviews/wp-content/uploads/2008/03/dirty-harry-do-you-feel-lucky.jpg "Do you feel lucky? Well do you punk?")

**Comment by newsomc** [comment]
Sorry, I really didn't reach out with any expectations. I copied others on my email for transparency internally, but I work on Etsy Ads and am just trying to ensure that our sellers have stability through the holidays. They make a lot of their sales during this time of year, and ads are a key part of that.

You're probably already aware of this, but our ads help keep base fees low for all Etsy sellers. It's true that Etsy makes money from these ads, but we believe having them is the best business model for helping more successful sellers grow while giving all sellers a chance. I'm honestly not familiar enough with eBay and Amazon, but their fees are much higher on average in addition to having ads (a 15%+ base fee compared to our 5%). 

Is it safe to say that you actually are trying to block first-party ads? I wasn't sure if you were, which is why I thought I should try reaching out. I’m sure you know that first-party ads don’t have the privacy concerns of third-party ads. If you’re concerned about the user experience, we regularly survey our buyers to make sure they’re happy supporting sellers that are promoting themselves.

**Comment by monzta** [comment]
Maybe the "first-party ads" part is a bit misleading. I think it means self-promotion where e.g. a website promotes their own shop, newsletter, subscription service or sites that belong to the same company/group/owner. That's what I take from our policy on our website: https://easylist.to/pages/policy.html

I think those ads should stay removed as they are seprated from regular listings as a result of payment.

**Comment by krystian3w** [comment]
Once block selfprome newer will be removed.
