### ISSUE TITLE
[easylist] Videos won't play on theguardian.com

### ISSUE THREAD

**Issue by mica** [easylist/easylist#9786]
E.g. the video on this page: https://www.theguardian.com/world/2021/nov/19/the-netherlands-rotterdam-police-open-fire-as-covid-protest-turns-violent

**Comment by Yuki2718** [comment]
Fixed very recently, force update filter lists.

**Comment by krystian3w** [comment]
So no possible fix once but for years?

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/87e2415174af7201be934410e64b5a96295f59d4
