### ISSUE TITLE
Chinese `Xiaohongshu` (`RED`) tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#9792]
- https://www.xiaohongshu.com/error?code=423
--> `POST` https://t2.xiaohongshu.com/api/v2/collect
--> `POST` https://lng.xiaohongshu.com/api/collect
--> `GET` https://fe-static.xhscdn.com/formula-static/@xhs/error-tracker@0.7.3/dist/ErrorTracker.js
--> `GET` https://fe-static.xhscdn.com/formula-static/@xhs/error-tracker@0.7.0/dist/ErrorTracker.js
--> `Set-Cookie` xhsTrackerId
--> `Set-Cookie` timestamp2.sig  (not sure)
--> `Set-Cookie` timestamp2  (not sure)

```
https://t2.xiaohongshu.com/api/v2/collect
https://lng.xiaohongshu.com/api/collect
https://fe-static.xhscdn.com/formula-static/@xhs/error-tracker@0.7.3/dist/ErrorTracker.js
https://fe-static.xhscdn.com/formula-static/@xhs/error-tracker@0.7.0/dist/ErrorTracker.js
cookie: xhsTrackerId=426644aa-782a-4264-c2f5-97a3d52c82c8

||fe-static.xhscdn.com/formula-static/@xhs/error-tracker
$cookie=xhsTrackerId
||xiaohongshu.com^$cookie=timestamp2.sig (not sure)
||xiaohongshu.com^$cookie=timestamp2 (not sure)
||t2.xiaohongshu.com/api/v2/collect
||lng.xiaohongshu.com/api/collect
```

**Comment by iam-py-test** [comment]
> $cookie=xhsTrackerId

Only works in AdGuard, not ABP or uBo. `##+js(cookie-remover,xhsTrackerId)` works for uBo though.
