### ISSUE TITLE
Solanart.io

### ISSUE THREAD

**Issue by Valleriani** [easylist/easylist#9796]
### List the website(s) you're having issues:
solanart.io

https://solanart.io/collections/solchicks
https://solanart.io/collections/genopeteggs
etc, any collection on the website

### What happens?
The image assets do not load due to a block. 

### List Subscriptions you're using:
uBlock Origin
Brave Shield (maybe you guys too?)

### Your settings

- OS/version: Windows 10
- Browser/version:  95.0.4638.69
- Adblock Extension/version: 1.38.6

### Other details:
I've already debugged it and the filter 

||workers.dev^$3p

is causing the issue, as our link for the assets is at 
https://silent-smoke-181a.solanart.workers.dev/

**Comment by Khrin** [comment]
This filter has been removed a little while ago. https://github.com/easylist/easylist/commit/12e623ddceef43f0c8b711b92d3c0fd9dc32c524
