### ISSUE TITLE
Why did you move all your files to easylist.to(Cloudflared)?

### ISSUE THREAD

**Issue by fastcopy** [easylist/easylist#98]
https://github.com/easylist/easylist/issues

Looks like you really hate Tor users. Too bad.
Not all of them are black crackers/attackers/criminals who use Tor badly, you know.

**Comment by fastcopy** [comment]
https://github.com/gorhill/uBlock/issues/1824

**Comment by monzta** [comment]
Tor users should be whitelisted now.

**Comment by fastcopy** [comment]
As a Tor user, I thank your kind heart!
Now I can access to https://easylist.to/easylist/easylist.txt without problem! ... for now.
Not sure about future.

This means you add "T1" to Cloudflare's whitelist?

Posting a public notice on easylist blog/forums will get more attention.

**Comment by IDKwhattoputhere** [comment]
I'm using Private Internet Access (largest VPN provider) and many of their IPs are regularly captcha-blocked by CloudFlare. Especially the European servers. Reconnecting doesn't help and all countries I've tried (the ones with decent ping, Italy, Netherlands, Sweden, Ireland and so on) are blocked too. This makes it impossible to download/update EasyList/EasyPrivacy.
