### ISSUE TITLE
google.*/display-ads-frontend-publisher-center/

### ISSUE THREAD

**Issue by malcolmr** [easylist/easylist#9800]
### List the website(s) you're having issues:

google.*/display-ads-frontend-publisher-center/
(e.g. https://www.google.com/display-ads-frontend-publisher-center/ and paths beneath that.)

### What happens?

Blocked by rule `/display-ads-` in https://github.com/easylist/easylist/blob/950fa48/easylist/easylist_general_block.txt#L3973.

### List Subscriptions you're using:

n/a (user reports)

### Your settings

n/a (user reports)

### Other details:

The URL space `/display-ads-frontend-publisher-center/*` (on all Google TLDs) is used to serve parts of the UI that's used by some of the publisher-facing frontends: AdSense, AdMob, Ad Manager, YouTube, etc. It's not used by ad serving.

However, (I believe) it's being blocked by the rule above, which breaks our frontends.

See e.g. these user reports:
- https://www.reddit.com/r/youtubers/comments/pnz9fl/question_error_when_trying_to_set_up_adsense/
- https://twitter.com/LegionGames2076/status/1444125910924468224
- https://twitter.com/iQamarAmin/status/1447453953755688969

**Comment by ryanbr** [comment]
`The server cannot process the request because it is malformed. It should not be retried. That’s all we know.`   @malcolmr   is the url still current?

**Comment by malcolmr** [comment]
Yes. The service is responding with a 400 because real-world requests require authentication credentials (in cookies) and particular paths/query parameters. This is part of a UI server, but it's not a path that users go to directly.

If you want to, you can see an example (if you have an AdSense account) by opening the AdSense UI and going to Account > Access and Authorization > User management in the sidebar. This will trigger a load of https://www.google.com/display-ads-frontend-publisher-center/user-management/loader?host=adsense&authuser=0&pid=pub-... (lots more parameters).

(Note that that example uses `www.google.com`, but this particular service can also server on bare domains like `google.com` and also any Google TLD, like `www.google.co.uk`.)

**Comment by ryanbr** [comment]
Maybe adjust the url, doing an exception for google.com possible, but not every google domain.

**Comment by malcolmr** [comment]
Thanks, just doing this for `google.com` will be a big help.
