### ISSUE TITLE
usersdrive.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9802]
### List the website(s) you're having issues:
`https://usersdrive.com/a7lwdh8v14zq.html`

### What happens?
There are suspicious 3rd party tracking domains appear in the site: `teeseparists.xyz` and `jistenbefor.space`

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.1
- Adblock Extension/version: ublock 1.38.6

### Other details:
Proposed filters:

```
||teeseparists.xyz^
||jistenbefor.space^
```

**Comment by spirillen** [comment]
Hmm I didn't see any of these domain on the site..

**Comment by stephenhawk8054** [comment]
I'm using default filters, have purged the cache and forced update but they're still there

![image](https://user-images.githubusercontent.com/66517106/142876951-e7364813-8d77-465b-9522-06c737798d12.png)

**Comment by spirillen** [comment]
most be country specific I didn't see any calls to them, you do an therefore it is correct to report them :+1: 

could you share the full queries you see there?

**Comment by stephenhawk8054** [comment]
Yeah, here's my full log

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +6 |  |  | `www.google.com` | 3,3 | script | `https://www.gstatic.com/recaptcha/releases/_7Co1fh8iT2hcjvquYJ_3zSP/recaptcha__en.js` |
| +6 |  |  | usersdrive.com | 3 | script | `https://www.gstatic.com/recaptcha/releases/_7Co1fh8iT2hcjvquYJ_3zSP/recaptcha__en.js` |
| +6 |  |  | usersdrive.com | 3 | frame | `https://www.google.com/recaptcha/api2/bframe?hl=en&v=_7Co1fh8iT2hcjvquYJ_3zSP&k=6Ldj8kAUAAAAAL-3PKwy2YG1JUy82daaNjgM9AyC` |
| +6 |  |  | usersdrive.com | 3 | xhr | `https://nelmonopo.xyz/utx?tid=874236&top=usersdrive.com&cb=Mtx12NtGV44M` |
| +6 |  |  | `www.google.com` | 3,1 | script | `https://www.google.com/recaptcha/api2/webworker.js?hl=en&v=_7Co1fh8iT2hcjvquYJ_3zSP` |
| +6 |  |  | `www.google.com` | 3,1 | font | `https://gstaticadssl.l.google.com/` | `aliasURL=https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2` |
| +6 |  |  | `www.google.com` | 3,3 | font | `https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2` |
| +6 |  |  | `www.google.com` | 3,3 | image | `https://www.gstatic.com/recaptcha/api2/logo_48.png` |
| +6 |  |  | `www.google.com` | 3,3 | script | `https://www.gstatic.com/recaptcha/releases/_7Co1fh8iT2hcjvquYJ_3zSP/recaptcha__en.js` |
| +6 |  |  | `www.google.com` | 3,3 | css | `https://www.gstatic.com/recaptcha/releases/_7Co1fh8iT2hcjvquYJ_3zSP/styles__ltr.css` |
| +6 |  |  | usersdrive.com | 3 | frame | `https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Ldj8kAUAAAAAL-3PKwy2YG1JUy82daaNjgM9AyC&co=aHR0cHM6Ly91c2Vyc2RyaXZlLmNvbTo0NDM.&hl=en&v=_7Co1fh8iT2hcjvquYJ_3zSP&size=normal&cb=elpfqpjhai97` |
| +5 |  |  | usersdrive.com | 1 | image | `https://usersdrive.com/favicon.ico` |
| +4 |  |  | usersdrive.com | 3 | script | `https://www.gstatic.com/recaptcha/releases/_7Co1fh8iT2hcjvquYJ_3zSP/recaptcha__en.js` |
| +4 |  |  | usersdrive.com | 3 | font | `https://gstaticadssl.l.google.com/` | `aliasURL=https://fonts.gstatic.com/s/ubuntu/v15/4iCv6KVjbNBYlgoCxCvjsGyN.woff2` |
| +4 |  |  | usersdrive.com | 3 | font | `https://fonts.gstatic.com/s/ubuntu/v15/4iCv6KVjbNBYlgoCxCvjsGyN.woff2` |
| +4 |  |  | usersdrive.com | 3 | font | `https://gstaticadssl.l.google.com/` | `aliasURL=https://fonts.gstatic.com/s/ubuntu/v15/4iCv6KVjbNBYlgoCjC3jsGyN.woff2` |
| +4 |  |  | usersdrive.com | 3 | font | `https://fonts.gstatic.com/s/ubuntu/v15/4iCv6KVjbNBYlgoCjC3jsGyN.woff2` |
| +4 |  |  | usersdrive.com | 3 | font | `https://gstaticadssl.l.google.com/` | `aliasURL=https://fonts.gstatic.com/s/ubuntu/v15/4iCs6KVjbNBYlgoKfw72.woff2` |
| +4 |  |  | usersdrive.com | 1 | font | `https://usersdrive.com/userdrive/assets/line-awesome/fonts/line-awesome.woff2?v=1.1.` |
| +4 |  |  | usersdrive.com | 3 | font | `https://fonts.gstatic.com/s/ubuntu/v15/4iCs6KVjbNBYlgoKfw72.woff2` |
| +4 | \|\|acscdn.com^ | -- | usersdrive.com | 3 | script | `https://acscdn.com/script/suv4.js` |
| +4 | google-analytics.com/ga.js | << | usersdrive.com | 3 | script | `https://ssl.google-analytics.com/ga.js` |
| +4 | \|\|google-analytics.com/ga.js$script,redirect-rule=google-analytics.com/ga.js | -- | usersdrive.com | 3 | script | `https://ssl.google-analytics.com/ga.js` |
| +4 | \|\|google-analytics.com^ | -- | usersdrive.com | 3 | script | `https://ssl.google-analytics.com/ga.js` |
| +4 | /^https?:\/\/(?:www\.\|[a-z0-9]{7,10}\.)?[-a-z0-9]{5,}\.(?:com?\|bid\|cl(?:ick\|ub)\|li(?:nk\|ve)\|net\|online\|top)\/(?:[a-z0-9]{2}\/){2,3}[a-f0-9]{32}\.js/$script,3p | -- | usersdrive.com | 3 | script | `https://buildsintellecttweak.com/ea/b5/4a/eab54a02a1accd17a90f000459b37384.js` |
| +4 | \|\|d3v3bqdndm4erx.cloudfront.net^ | -- | usersdrive.com | 3 | script | `https://d3v3bqdndm4erx.cloudfront.net/?dqbvd=874238` |
| +4 |  |  | usersdrive.com | 3 | script | `https://jistenbefor.space/SkpkUXkxaBcmJj84CHNDaCIQJQk5cEt%2BDDkvFiIdOCMSNFcpJQl%2BCj1kDiJbZmgXPB9ocFV9WzknEnNDaHlKZVtmaBAwHhUjAHNDaHJTZUt5fEZ9Wzk%2FBg4QLnhGa1t5c1NjSil8VHwffn4HfE1yfQV8QSt6UXwaenxcZBpzeVAwHCloGQ` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/select/js/jquery.nice-select.min.js` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/js/ie10-viewport-bug-workaround.js` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/js/bootstrap.js?v=12` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/js/vendor/popper.min.js?v=1` |
| +2 |  |  | usersdrive.com | 3 | script | `https://www.google.com/recaptcha/api.js` |
| +2 | \|\|acscdn.com^ | -- | usersdrive.com | 3 | script | `https://acscdn.com/script/suv4.js` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/js/progress.js` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/js/countdown.js` |
| +2 |  |  | usersdrive.com | 1 | image | `https://usersdrive.com/userdrive/assets/img/userdrive.png` |
| +2 |  |  | usersdrive.com | 1 | css | `https://usersdrive.com/userdrive/assets/select/css/nice-select.css` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/js/paging.js` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/js/jquery.cookie.js` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/js/jquery.paging.js` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/userdrive/assets/js/jquery-1.9.1.min.js?v=1` |
| +2 |  |  | usersdrive.com | 3 | css | `https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css` |
| +2 |  |  | usersdrive.com | 1 | css | `https://usersdrive.com/userdrive/assets/line-awesome/css/line-awesome.min.css` |
| +2 |  |  | usersdrive.com | 1 | css | `https://usersdrive.com/userdrive/assets/css/dashboard.css?v=1000` |
| +2 |  |  | usersdrive.com | 1 | css | `https://usersdrive.com/userdrive/assets/css/bootstrap.min.css?v=1` |
| +2 |  |  | usersdrive.com | 3 | css | `https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700` |
| +2 | /^https?:\/\/(?:www\.\|[a-z0-9]{7,10}\.)?[-a-z0-9]{5,}\.(?:com?\|bid\|cl(?:ick\|ub)\|li(?:nk\|ve)\|net\|online\|top)\/(?:[a-z0-9]{2}\/){2,3}[a-f0-9]{32}\.js/$script,3p | -- | usersdrive.com | 3 | script | `https://buildsintellecttweak.com/ea/b5/4a/eab54a02a1accd17a90f000459b37384.js` |
| +2 | \|\|d3v3bqdndm4erx.cloudfront.net^ | -- | usersdrive.com | 3 | script | `https://d3v3bqdndm4erx.cloudfront.net/?dqbvd=874238` |
| +2 |  |  | usersdrive.com | 1 | script | `https://usersdrive.com/sw.js` |
| +0 |  |  | usersdrive.com | 1 | doc | `https://usersdrive.com/a7lwdh8v14zq.html` |
</details>

**Comment by spirillen** [comment]
Thanks for your sharing, however I only see `jistenbefor.space`, which I have blacklisted in my own project. and will make a PR for here.

```
https://jistenbefor.space/SkpkUXkxaBcmJj84CHNDaCIQJQk5cEt%2BDDkvFiIdOCMSNFcpJQl%2BCj1kDiJbZmgXPB9ocFV9WzknEnNDaHlKZVtmaBAwHhUjAHNDaHJTZUt5fEZ9Wzk%2FBg4QLnhGa1t5c1NjSil8VHwffn4HfE1yfQV8QSt6UXwaenxcZBpzeVAwHCloGQ
```
