### ISSUE TITLE
techpowerup.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#9809]
### List the website(s) you're having issues:

`https://www.techpowerup.com/gpu-specs/geforce-gt-1010.c3762`

### What happens?

Various ads on the right.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/142954343-f2f7e9df-b1e8-4522-81f0-1e699e31d15c.png)

### Your settings

- OS/version: Windows 11 stable x64
- Browser/version: Chrome 96.0.4664.45 x64
- Adblock Extension/version: uBO 1.38.7rc1 + IDCAC 3.3.4

### Other details:

I propose:
```
||techpowerup.com/review^$image
||tpucdn.com/review^
```

![image](https://user-images.githubusercontent.com/22780683/142955273-74f34b1b-7aae-44db-b77d-73f971fe818b.png)

**Comment by ryanbr** [comment]
They'll counter this quickly, leaving.
