### ISSUE TITLE
(mobile) myanimelist antiadblock?

### ISSUE THREAD

**Issue by runboy93** [easylist/easylist#9811]
Since today, myanimelist.net mobile website is using antiadblock very likely.

Open website and wait while, whole screen turns "gray" and prevent using website, it's trying to show something but cannot be shown.

Using Fanboy Ultimate list, along with Adguard lists (base, trackers, social, mobile, annoyances), uBlock filters (Filters, Filters 2020, Filters 2021, Annoyances, Privacy, Resource-abuse) Spam404, urlhaus filter + phishing filter.

OS/version: Android 11
Browser/version: Vivaldi 4.3
Adblock Extension/version: Vivaldi adblocker

**Comment by krystian3w** [comment]
Bad place to report anti-adblock

**Comment by spirillen** [comment]
@krystian3w that thumb down is just hush,  (s)he is clearly in doubt indicating whether this is a antiadblock or something else by appending the question mark to it...

**Comment by krystian3w** [comment]
99% of anti-abp in this repo have label invalid.

**Comment by spirillen** [comment]
Maybe, but should we assume common users know all this; can we?

**Comment by runboy93** [comment]
https://github.com/reek/anti-adblock-killer/issues/4506
