### ISSUE TITLE
Bing Popular Now Carousel Hidden - bing.com###b_pole

### ISSUE THREAD

**Issue by xceptionunhandled** [easylist/easylist#9827]
### List the website(s) you're having issues:
bing.com

### What happens?

Hides popular now carousel. Open bing homepage and scroll down to see popular now section. Click on any item in that list. New page will not show the carousel.

ElemHide rule added to Easylist 2 days back. Commit: 06efcf3cb8fdecb70eeedda9c8f32cb1106222b9

Rule: bing.com###b_pole

### List Subscriptions you're using:

Easylist

### Your settings

Adblock Plus

### Other details:

ElemHide rule added to Easylist 2 days back. Commit: 06efcf3cb8fdecb70eeedda9c8f32cb1106222b9

Rule: bing.com###b_pole

![image](https://user-images.githubusercontent.com/94994206/143303599-6a1f7dc5-b27c-4a46-b34d-134c40464156.png)

**Comment by ryanbr** [comment]
I saw no issues. but changed the filter slightly.

**Comment by xceptionunhandled** [comment]
Issue is fixed now.

Before fix:

![image](https://user-images.githubusercontent.com/94994206/143721332-40ebcc69-6d1d-4613-a5df-259a1ce4a71a.png)


After fix:

![image](https://user-images.githubusercontent.com/94994206/143721333-fd821f46-e917-40dc-a450-d7b03fcf90db.png)
