### ISSUE TITLE
More Admiral hostnames

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/easylist#9832]
More Admiral hostnames:

`abacksoda.com`
`automaticairplane.com`
`combbit.com`
`curiouschalk.com`
`curlycannon.com`
`distancefinger.com`
`downtowndirection.com`
`encourageshock.com`
`encouragingvase.com`
`enthusiasticring.com`
`faintflag.com`
`honorablehydrant.com`
`hoplaugh.com`
`incompetentjoke.com`
`kittyaction.com`
`motionlessbelief.com`
`pailcrime.com`
`periodicpocket.com`
`scarcesurprise.com`
`shinestuart.com`
`skillfulsock.com`
`specialscissors.com`
`teenytinyshirt.com`
`verdantanswer.com`
`vivaciousveil.com`
`voraciousgrip.com`
`zestycrime.com`

**Comment by spirillen** [comment]
@ryanbr all the above domains have been check for availability and found active with PyFunceble 4.0.2b5

Status      Percentage   Amount      
----------- ------------ ------------
ACTIVE      100%         27          
INACTIVE    0%           0           
INVALID     0%           0
