### ISSUE TITLE
ebay.de

### ISSUE THREAD

**Issue by VolatileCable** [easylist/easylist#9834]
I'm not quite sure how to reproduce this, but it happens when you search something, and seemingly only when logged in.

Eg:
https://www.ebay.de/sch/i.html?_nkw=sharkoon+sgk3&_sacat=0

The page initially shows, but turns blank after a few seconds. The cause seems to be a smaller banner that appears at the top about cookie usage.

I fixed it with the following:
ebay.de#@##gh-gb
ebay.de#@##gh-bt
ebay.de#@#.gh-banner
ebay.de#@#.gh-banner-active

Note that #gh-bt is only in Fanboy Annoyance. I encountered it there first, before replacing it with EL Cookie, but it still happens.

uBO Chrome
uBO Filters + EasyList + Privacy + DEU + Cookie

**Comment by ryanbr** [comment]
The site looks fine here.

**Comment by VolatileCable** [comment]
It's weird. I just tried again and it's not even dependent on being logged in. I cleared my cookies and the banner appeared again. I disabled the exceptions and cleared them again and it no longer does.. Maybe it's IP based and possibly it only shows up from time to time for some (country-specific) legal requirement?

**Comment by krystian3w** [comment]
Maybe New Zeland IP something change and Ryanbr use only free/cheap VPN.

**Comment by ryanbr** [comment]
I have 3 different VPN's. Closing request, not reproducable.
