### ISSUE TITLE
ftm.eu registration popup

### ISSUE THREAD

**Issue by FireMasterK** [easylist/easylist#9846]
### List the website(s) you're having issues:
https://www.ftm.eu/articles/xiaomi-phones-spy-on-their-users

### What happens?
You see a banner telling you to register to 

### List Subscriptions you're using:
Default from uBlock Origin with EasyList Cookie and uBlock filters – Annoyances annoyances filter.

### Your settings

- OS/version: Linux
- Browser/version: Brave - latest stable
- Adblock Extension/version: uBlock Origin 1.38.6

### Other details:

![image](https://user-images.githubusercontent.com/20838718/143504182-88c57a04-067d-4cf6-bb4b-5b0246e7c0d5.png)

**Comment by ryanbr** [comment]
*Use FB Annoyances list
