### ISSUE TITLE
(NSFW) darknessporn.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#9865]
### List the website(s) you're having issues:

`https://darknessporn.com/tag/2278-vacbed/`

### What happens?

Various placeholders, and a few ads for `best-datinghotties1.com`

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/143658505-a8bb47c6-177d-480c-a242-255f52378a86.png)

### Your settings

- OS/version: Windows 11 stable x64
- Browser/version: Chrome 96.0.4664.45 x64
- Adblock Extension/version: uBO 1.38.7rc4 + IDCAC 3.3.4

### Other details:

I advise against browsing any other category on the site, considering how extreme its tag-list is.

I propose:
```
darknessporn.com##div[class$=-boxes]
darknessporn.com##div[class*=-boxes-]
darknessporn.com##.order-1.col-xl-4
darknessporn.com#?#.order-2:-abp-has(a[rel])
! Shows up when the window is ≤1000px wide
darknessporn.com##div[class*=textovka]
```

Screenshot: `https://images2.imgbox.com/f4/fe/MQ9Ph9Q9_o.png`

**Comment by spirillen** [comment]
This one will remove the ad place holder on all `https://www.mechbunny.com/tube-script` tube scripts templates.

And it will transform the frontpage into this

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/44526987/143691179-4d893abb-6ddb-4914-a136-c3b26686f2c1.png)

![image](https://user-images.githubusercontent.com/44526987/143691150-9154cc5a-832d-4c12-924f-54ce14b2b088.png)

</details>


```css
darknessporn.com##.order-sm-1
```
