### ISSUE TITLE
`bandcamp.com` new 1x1 transparent pixel tracking route

### ISSUE THREAD

**Issue by D4v1dH03** [easylist/easylist#9877]
### List the website(s) you're having issues:

`https://bandcamp.com/stat_record`

### What happens?

Bandcamp makes a `GET` request every few seconds to the specified URL above with parameters and generates a 1x1 transparent tracking pixel which fingerprints users

### List Subscriptions you're using:
EasyPrivacy
Easylist
Fanboy's Annoyances
Fanboy's Cookies
Fanboy's Socials

### Your settings

- OS/version: macOS 12.0.1 (Monterey)
- Browser/version: Firefox 96.0 (Nightly)
- Adblock Extension/version: uBlock Origin 1.39.0

### Other details:

<img width="1280" alt="Screenshot 2021-11-27 at 12 06 53" src="https://user-images.githubusercontent.com/81270448/143720797-10dbbde5-053f-42a9-9799-977fbd9646d6.png">

Evidence of tracking behaviour

Purposed filter `||bandcamp.com/stat_record`

**Comment by krystian3w** [comment]
test

`||bandcamp.com/stat_record$rewrite=abp-resource:1x1-transparent-gif`

**Comment by D4v1dH03** [comment]
> test in APB:
> 
> `||bandcamp.com/stat_record$rewrite=abp-resource:1x1-transparent-gif`
> 
> For uBO these:
> 
> `||bandcamp.com/stat_record$redirect=1x1.gif`

Thank you
The test works on uBO for me. I don't use Adblock Plus though

**Comment by D4v1dH03** [comment]
Thank you so much for the fix, Ryan!
