### ISSUE TITLE
`ABP Sepecific fixes` is mistakenly included in for uBO `Fanboy’s Annoyance`

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylist#9878]
I don't think these filters and comments (`! ABP Sepecific fixes`) should appear in the uBO filter list
![Screenshot_2021-11-28-12-06-59-173_org mozilla firefox](https://user-images.githubusercontent.com/66902050/143729254-5c74cb7c-cdfe-41f8-90aa-3999089e5fe6.jpg)

**Comment by ryanbr** [comment]
No way to avoid this.
