### ISSUE TITLE
krunkercentral.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#9888]
### List the website(s) you're having issues:
`https://krunkercentral.com`

### What happens?

Suspect requests from different xyz domains

### List Subscriptions you're using:

uBlock Origin default with EasyList, EasyPrivacy and EasyList germany

### Your settings

- OS/version: Win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin 1.39.0

### Other details:
Suspect requests unblocked:

`https://lasticalsdeb.xyz/`

`https://athyouglas.xyz/utx?tid=926102&top=krunkercentral.com&cb=gHT3NcV2nSeI`

`https://lasticalsdeb.xyz/UEVHSlQrZzQ9CyU3K2huci0zPiQjf2hlPyIwKSExIiYiJCAiJCtkNz8oaDkjfi80aHhyNiosdmp0a2gnPTNlcHZka3RoeHIxJi0LOSFlcHZpd3F7ZGJna2gnJScYIzBiZ31oY2R2dCs2YH1qKDExd2p%2BZzQgaisxNXVqKWRgcXV%2FNmh8dXJhcjg
`
<img width="604" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/143783065-bd20decd-badb-478c-9866-b06af973fdd9.PNG">

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7f1071f3e65c714046c363289384671630a68e4f
