### ISSUE TITLE
etsy.com

### ISSUE THREAD

**Issue by Raulsack69** [easylist/easylist#9889]
### List the website(s) you're having issues:
```
https://www.etsy.com/
```
### What happens?

When you sign in and click on favorites, the rendering of all the listings is messed-up. 
The category tags are in a small scroll box, most listings are missing thumbnails and all the listings are misaligned and joined together.

### List Subscriptions you're using:

Fanboy's Annoyance
Fanboy's Social

### Your settings:

- OS/version: Windows 10 Home Edition 64-Bit (Build 19042) 
- Browser/version: Google Chrome 96.0.4664.45 (64-Bit)
- Adblock Extension/version: Ublock Origin 1.38.6

### Other details:

Happens when using either Fanboy's Annoyance or Fanboy's Social filter lists (Individually and together)
No other filter lists are enabled
Ublock Origin is the only Chrome extension enabled

### Screenshots:

Incorrect Layout (With either Fanboy's Annoyance or Fanboy's Social enabled):
![Incorrect Layout](https://user-images.githubusercontent.com/56152606/143807701-6576f42c-0b07-4c25-bb66-58185756e565.png)

Incorrect Layout (Zoomed Out):
![Incorrect Layout (Zoomed out)](https://user-images.githubusercontent.com/56152606/143807703-63568f9c-e059-4f60-b53f-00915f6ee66d.png)

Correct Layout (With Fanboy's filter lists disabled):
![Correct Layout (With Fanboy's filter lists disabled)](https://user-images.githubusercontent.com/56152606/143807705-0d611188-11d0-4a89-9954-edcb56a9f9a2.png)

**Comment by ryanbr** [comment]
Works for me, what filters are being used/being hit by the social list?
