### ISSUE TITLE
Taiwanese `TaiwanPlus` taiwanplus.com tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#9893]
https://taiwanplus.com/vods?c=90000028&v=80001177 -->

`GET` https://taiwanplus.com/api/video/watch/80001177
`POST` https://taiwanplus.com/api/video/startVideo
`POST` https://taiwanplus.com/api/video/endVideo

```
https://taiwanplus.com/api/video/watch/80001177
https://taiwanplus.com/api/video/startVideo
https://taiwanplus.com/api/video/endVideo

||taiwanplus.com/api/video/watch^
||taiwanplus.com/api/video/startVideo^
||taiwanplus.com/api/video/endVideo^
```

![image](https://user-images.githubusercontent.com/75058881/143921391-c447ed91-5beb-410e-9c35-064bfe9e8572.png)

**Comment by ryanbr** [comment]
Only needed one.
