### ISSUE TITLE
usagoals.sx

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9896]
### List the website(s) you're having issues:
`https://www.usagoals.sx/portal.html`

### What happens?
Ads placeholders

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.2
- Adblock Extension/version: ublock 1.39.0

### Other details:
![image](https://user-images.githubusercontent.com/66517106/143975051-b5e5770f-de1a-4043-bda9-bd7cfadac19f.png)

Proposed filter:

`usagoals.sx##center`

**Comment by ryanbr** [comment]
Should be fixed, looks fine here
