### ISSUE TITLE
[NSFW] tube.perverzija.com

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9899]
### List the website(s) you're having issues:
`https://tube.perverzija.com/freeusemilf-brooklyn-chase-make-yourself-at-home/`

### What happens?
There's a `beacon` link with a `1x1` pixel gif link, maybe for tracking.
`https://fer2oxheou4nd.com/solid.gif?z=1879235`

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.2
- Adblock Extension/version: ublock 1.39.0

### Other details:
![image](https://user-images.githubusercontent.com/66517106/144045384-dbb1c1d5-c82f-448a-a3b9-32bc29c59a62.png)

Proposed filter:

`/solid.gif$ping`

or

`||fer2oxheou4nd.com^`

**Comment by spirillen** [comment]
Well it is not only tracking pixel, there are other tracking script as well from that domain,

https://fer2oxheou4nd.com/get/1879235?zoneid=1879235&jp=_cl98ypy2n4nvrzkgt0stx3&nojs=0&ix=0&t=0&x=1178&y=618&wcks=1&wgl=1&cnvs=1&os=-60&md=0&bb=0&lang=en-US&pf=Linux%20x86_64&cd=24&isRef=0&sp=1

**Comment by spirillen** [comment]
OH yeah it is owned by clicadu...
