### ISSUE TITLE
Merge ## and ### lines.

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#99]
Hello,

My Adblock is eating too much memory. I've analyzed easylist.txt and there's some lines that
can be merged into one line.

I wrote a simple script for this.
https://gist.github.com/advcleaner/909b6005fbd25d9c56b59624f0be87a4

**Comment by advcleaner** [comment]
updated: https://gist.github.com/advcleaner/262769d75b83ed4464fcb60b89dcf208

> Cleanup 2#, 3#, and domain= lines.
> Merge domains(and unique them to remove duplicate selection)
