### ISSUE TITLE
just-upload.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#9903]
### List the website(s) you're having issues:

`https://just-upload.com/rw/Krunker_Central_-_Free_Hacks_&_Cheats.rar`

### What happens?

Popups and many suspect requests

### List Subscriptions you're using:

uBlock Origin default with EasyList, EasyPrivacy and EasyList germany

### Your settings

- OS/version: Win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin 1.39.0

### Other details:

Its exacly the same like https://github.com/easylist/easylist/issues/9888

And there is FingerprintJS on `https://d1t4ekjh9ps4ob.cloudfront.net/uMVBmWGQOJA88WQhkVWpRBQ%3D%3D`

**Comment by spirillen** [comment]
Thanks for the FingerprintJS @JobcenterTycoon

**Comment by JobcenterTycoon** [comment]
There is another one `https://d2werg7o2mztut.cloudfront.net/NTkw0MlNxOF1Wbnd4BwBmeg%3D%3D`

**Comment by spirillen** [comment]
Super @JobcenterTycoon Is it possible I could make you copy/paste this to my project as well? Then I would receive the notification quicker to help getting them stopped.
