### ISSUE TITLE
Chinese `360` "Private" Search Engine: `Wuzhuiso`

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#9913]
https://www.v2ex.com/t/819378

```
https://www.wuzhuiso.com/?src=v2ex
https://www.wuzhuiso.com/help/policy.html?src=v2ex
https://www.wuzhuiso.com/s?q=test&a=image&src=tab_www&fr=none

||wuzhuiso.com^$queryprune=src
```

![image](https://user-images.githubusercontent.com/75058881/144289911-c6672899-d6ef-48b1-8913-31b78677437f.png)

![image](https://user-images.githubusercontent.com/75058881/144290419-01b28c13-2008-455b-ad61-eff36287b3e4.png)

**Comment by c2xusnpq6** [comment]
```
||improving.wuzhuiso.com^
/sou/home.gif
```

![image](https://user-images.githubusercontent.com/75058881/144292290-3d76588a-e5ee-49bb-9669-81c2d151e911.png)

**Comment by iam-py-test** [comment]
@c2xusnpq6 I don't think Easylist removes tracking params. See my comment https://github.com/uBlockOrigin/uAssets/issues/10690#issuecomment-984133272
