### ISSUE TITLE
mixpanel.com

### ISSUE THREAD

**Issue by pablofierro** [easylist/easylist#9920]
### List the website(s) you're having issues:

```mixpanel.com```

### What happens?

The site is not rendering properly since it's being blocked from fetching data to render.

### List Subscriptions you're using:

EasyPrivacy, `/mixpanel.$domain=~mixpanel.com`

### Your settings

- OS/version: any
- Browser/version: Brave 
- Adblock Extension/version: uBlock

### Other details:

URLs like `https://mixpanel.com/api/*` are being incorrectly marked as trackers and the site is not rendering properly since it can't fetch data to render, to reproduce you can signup and use a public demo dataset `https://mixpanel.com/project/2138137/view/290551/app/dashboards#id=639383`

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/965112/144368125-596d2790-4214-4ba6-a78b-0c00700df87e.png">

**Comment by ryanbr** [comment]
`/mixpanel.$domain=~mixpanel.com` should be enough. Does the same thing occur in uBO (with Brave shields disabled) ? @pablofierro
