### ISSUE TITLE
geizhals.de

### ISSUE THREAD

**Issue by VolatileCable** [easylist/easylist#9927]
This is more of a matter of understand the rules of the list, but Fanboy Social currently blocks the social links in the footer of the page, out of the way of any content and not being annoying. Is this the intended goal of the Social list? I noticed this when I made another issue report some days ago and wondered if I were missing this also on other sites.

Caused by:
##.footer-social

**Comment by spirillen** [comment]
You are right, the fanboy-social is a anti social list :smirk: and I give you that it should have been named better.

**Comment by VolatileCable** [comment]
I'm not confused by the name. I just thought it had different goals, like removing social icons next to or embedded "share this" type links in articles.

The social icons in the footer in this example are not hurting anyone and I feel like removing them just hurts the user more as he won't be able to find the relevant pages as quickly anymore, or identify which are official.

**Comment by spirillen** [comment]
> like removing social icons next to or embedded "share this" type links in articles.

To my understanding and knowledge it is.

>  removing them just hurts the user more as he won't be able to find the relevant pages as quickly anymore,

I'm lost here, how should it help any users finding "relevant pages" faster with the icons visible?

**Comment by ryanbr** [comment]
Social icons are blocked, without causing issues with social logins, if this includes header, article or footer social icons, then its fine.
