### ISSUE TITLE
howtogeek.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#9937]
### List the website(s) you're having issues:
`https://www.howtogeek.com/242428/whats-the-best-way-to-back-up-my-computer/`

### What happens?
advertising-related placeholder(s)

### List Subscriptions you're using:
The enabled-by-default filter lists (PC, english) + Fanboy's Annoyance

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin 1.39.2

**Comment by DandelionSprout** [comment]
For comparison, AdGuard Base Filter has `howtogeek.com##.entry-content > p ~ div[style] > span.future_inline_clone_target:upward(1)` to remove the placeholders, which would be non-trivial to easily convert to EasyList ABP syntax.

**Comment by ryanbr** [comment]
Should be resolved
