### ISSUE TITLE
aws-native.com / any hashnode blogs

### ISSUE THREAD

**Issue by emlimap** [easylist/easylist#9939]
### List the website(s) you're having issues:

```
https://aws-native.com/new-ec2-instance-types-of-reinvent-2021
```

This also can be seen on any of the blog links from here 
```
https://hashnode.com/explore
```

### What happens?

Hashnode blogs seem to be masking third party tracking as first party

### List Subscriptions you're using:

<details>

![image](https://user-images.githubusercontent.com/62358249/124452393-41884700-dd7e-11eb-9f76-7820fcee5844.png)

</details>

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox 95.0 RC1
- Adblock Extension/version: ublock origin 1.39.2

### Other details:

```
https://aws-native.com/ping/gamp
https://aws-native.com/ping/view
```
Gamp seems to refer to this `https://developers.google.com/analytics/devguides/collection/protocol/v1/` which allows proxying GA through a server. Not sure about the view endpoint though.
Suggested filter

```
/ping/gamp
/ping/view
```

**Comment by emlimap** [comment]
@ryanbr @spirillen The filter needs to be a bit more generic as this tracking happens in any hash node blog with their domain name.

For example 
```
https://blog.greenroots.info/how-to-create-dashboard-with-harperdb-custom-functions-and-recharts
```

More examples can be found at any of the links in here
```
https://hashnode.com/explore
```

**Comment by spirillen** [comment]
Try adding 

```
||hn-ping.hashnode.com^
```

To your local filters.it looks like it is replacing the `ping.hashnode.com` (https://mypdns.org/my-privacy-dns/matrix/-/issues/1931)

**Comment by emlimap** [comment]
Are we better off adding these instead since they seem to be frequently changing sub domains

```
||hashnode.com/api/gamp
||hashnode.com/api/data-event
```

They have changed it thrice in the last 6 months, https://github.com/easylist/easylist/issues/8294, https://github.com/easylist/easylist/issues/8673 and now

**Comment by spirillen** [comment]
You made we visit it again :smiley: 

I might even suggest `hashnode.com/api/` if you are looking in your log, then at first sight, there are only calls to gamp and data-event.

**Comment by emlimap** [comment]
The problem is that `hashnode.com/api/ `, is a bit too generic and could potentially cause false positives.

```
/ping/gamp
/ping/view
```
Adding these generic filter to Easyprivacy like you did in your list, would cover any hashnode hosted blog, not just `aws-native.com`. `/ping/view/` look a bit generic as well but gamp should be good to have as generic.

And these should cover hashnode website itself

```
||hashnode.com/api/gamp
||hashnode.com/api/data-event
```

**Comment by spirillen** [comment]
I agree with you that these are very generic, but, I prefer generic and the IF they become to generic, then tighten the rules accordingly.

I agree that these rules are probably as tight easylist might accept. Even tho I find `/api/gamp` rather special.

```css
||hashnode.com/api/gamp
||hashnode.com/api/data-event
```
