### ISSUE TITLE
zaful.com content hidden by EasyList

### ISSUE THREAD

**Issue by ivonxiao** [easylist/easylist#9944]
### List the website(s) you're having issues:
https://www.zaful.com/

### What happens?
all element with class 'custom-ad' is hidden, But thease are normal content

### List Subscriptions you're using:

EasyList
### Your settings

- OS/version: Windows 7
- Browser/version:  Google Chrome/96.0.4664.45
- Adblock Extension/version:  4.40.0

**Comment by ryanbr** [comment]
Works for me.

**Comment by ivonxiao** [comment]
> Works for me.
![hide](https://user-images.githubusercontent.com/4393780/144783253-7fdbb566-9454-4a64-9ea4-870ad2ae44a8.png)

Please look this picture, when I change a class name in yellow block, it is shown immediately
