### ISSUE TITLE
Break video vtvgo.vn

### ISSUE THREAD

**Issue by bigdargon** [easylist/easylist#9947]
### List the website(s) you're having issues:

https://vtvgo.vn/trang-chu.html

### What happens?

Select TV program playback, player can't load

![1638712889302](https://user-images.githubusercontent.com/10969626/144813078-3e4df18f-9990-411e-9570-03ddc72a1483.png)

Rule `||googletagmanager.com^` in EasyPrivacy prevents players from loading videos

Suggest a rule to ignore on this page

```
@@||googletagmanager.com/gtm.js^$domain=vtvgo.vn
```

### List Subscriptions you're using:

uBlock filter
EasyList
EasyPrivacy
ABPVN

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.2
- Adblock Extension/version: uBlock Origin 1.39.2

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/a5db87d915604a5ee5f86a4ad12db2a677edb463
