### ISSUE TITLE
coinpedia.org

### ISSUE THREAD

**Issue by LikesHisComputer** [easylist/easylist#9959]
### List the website(s) you're having issues:
`https://coinpedia.org/earning-site/adbtc/`

### What happens?
ad

### List Subscriptions you're using:
uBO ebd (PC, eng)

### Your settings

- OS/version: Windows 10
- Browser/version: Google Chrome
- Adblock Extension/version: uBlock Origin

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9713e91ec04c4073b336663d54d3dcea78497d72
