### ISSUE TITLE
security.org

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#9970]
### List the website(s) you're having issues:

`https://www.security.org/how-secure-is-my-password/`

### What happens?

Ad picture
<img width="602" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/145036348-0ee52a6d-2508-46a8-b1e0-cda6bc06d13a.PNG">

### List Subscriptions you're using:

uBlock Origin default with EasyList, EasyPrivacy and EasyList germany

### Your settings

- OS/version: win 10
- Browser/version: Firefox developer
- Adblock Extension/version:  uBlock Origin 1.39.2

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/37e2d4afed5d39803a0d29677d69dd8c702cd2d6
