### ISSUE TITLE
techwalla.com

### ISSUE THREAD

**Issue by LikesHisComputer** [easylist/easylist#9972]
### List the website(s) you're having issues:
`https://www.techwalla.com/articles/how-to-disable-chrome-sandbox`

### What happens?
space

### List Subscriptions you're using:

uBO's ebd (PC, eng)
### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 
- Adblock Extension/version: uBO

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9ffb288ab673118fde2dce9a6f1e78e87cd8bdd4
