### ISSUE TITLE
geo.dailymotion.com

### ISSUE THREAD

**Issue by dharFr** [easylist/easylist#9980]
### List the website(s) you're having issues:

```
https://www.cosmopolitan.fr/fromage-moins-calorique,2053031.asp
https://www.marieclaire.fr/pauline-lafont-mort,1321245.asp
https://dailymotion.github.io/player-test-offsite-pages/PES/PV-18741.html
```

### What happens?

Easylist blocks the Dailymotion video player from being displayed.

### List Subscriptions you're using:

- Subscriptions: Easylist

### Your settings

- OS/version: Big Sur 11.5.2
- Browser/version: Chrome 96.0
- Adblock Extension/version: uBlock Origin 1.39.2

### Other details:

The Dailymotion video player doesn't load when the `?ads_params` parameter is present in its URL, as this parameter is blocked in [the general blocklist](https://github.com/easylist/easylist/blob/c8fe213d77ef542e4f62be18dfb8052a36a93c70/easylist/easylist_general_block.txt#L6612).
The issue is visible on the third test page:
```
https://dailymotion.github.io/player-test-offsite-pages/PES/PV-18741.html
```
The first player contains an `?ads_params` parameter, and is not displayed. The second one, also using `?ads_params` parameter, but relying on an alternative embed URL, is displayed.

As stated in the [Dailymotion public docs](https://developer.dailymotion.com/player/#player-iframe-embed), the following URLs may be used to embed a video player:
- `https://geo.dailymotion.com/player.html`
- `https://geo.dailymotion.com/player/<xid>.html`
Hence, a solution could be to add those 2 URLs to the allow-list, as follow:
```
@@||geo.dailymotion.com/player.html?ads_params=$subdocument
@@||geo.dailymotion.com/player/*.html?ads_params=$subdocument
```

Lastly, please note that the existing allow-list rule bellow still applies on other websites and should not be removed: 
```
! Rule bellow still applies, for example on:
!   https://www.leparisien.fr/video/video-allemagne-angela-merkel-ovationnee-au-bundestag-juste-avant-lelection-dolaf-scholz-08-12-2021-4P4VCYI37NB2PCBGQKOSM62LLY.php
@@||dailymotion.com/embed/*?ads_params=$subdocument
```
Thank you!

**Comment by dharFr** [comment]
Related: https://github.com/easylist/easylist/pull/8925

**Comment by ryanbr** [comment]
Should be working. Closing
