### ISSUE TITLE
Datahjelperne.no - Blocked images (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#9985]
### Affected site:
`https://www.datahjelperne.no/`

### Issue:
Blocked images.

### Example:
`https://www.datahjelperne.no/er-du-lei-reklame-pa-facebook/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **EasyList**

### Problem rule:
`/annonser.`

### Possible fix:
`@@||wp.com/www.datahjelperne.no/wp-content/uploads/*annonse$image,domain=datahjelperne.no`
(Also covers the other problem filter, mentioned below)

### Other problem filters:
* ~~**Frellwit's Swedish Filter** https://github.com/lassekongo83/Frellwits-filter-lists/issues/121/~~ _(FIXED)_
~~`/wp-content/uploads/*annons$image`~~

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.4.2.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
I'm just about to go to bed, but can assist further with this tomorrow sometime.

**Comment by DandelionSprout** [comment]
Having analysed the matter for 35min, I was tempted to propose changing `/annonser.` to `://annonser.`; but it took me by surprise that `Datahjelperne`'s old website owner would title a file `annonser.png`

**Comment by THEtomaso** [comment]
When I pinged you, the idea was that you'd add a quick fix to your Nordic filter.

**Comment by DandelionSprout** [comment]
Oh, okay. Give me 5min.
